### PR TITLE
Correct the Webauthn options struct version number

### LINKED ISSUE #55290: tsh crashes on Windows when attempting to add a WebAuthn MFA device
Expected behavior:

`tsh mfa add` should let me confirm my identity before adding a new device.

Current behavior:

`tsh` crashes when attempting to show the WebAuthn dialog. Reproducible 2 of 5 times on Windows; unable to reproduce on v17.4.10 on the same machine with the same configuration.

Bug details:
- Teleport version: 18.0.0-alpha.1 (Windows 11 Home 23H2).
- Recreation steps:

1. Sign into a remote cluster.
2. Use `tsh mfa add`.
3. Use `webauthn` for the device type.
4. Enter device name.
5. Answer "yes" to the question about passwordless.

Right after I gave the last answer, `tsh` decided (correctly) to use webauthn identity confirmation method and then (sometimes) immediately crashed without giving me a chance to confirm my identity.

The user I was working with had multiple MFAs configured (OTP, at least one Ubikey, TouchID), though I don't know if it's relevant. I was also unable to reproduce the issue with `--mfa-mode` explicitly specified. That machine has an AMD TPM. Windows Hello doesn't support fingerprints or face recognition; it was configured using a PIN. There were no USB authentication keys attached to the computer.

- Debug logs: [error.txt](https://github.com/user-attachments/files/20521347/error.txt)

### PR DESCRIPTION
**Pull request by bl-nero**
This makes it consistent with the structure size and fixes an access violation exception. Version 6 of the structure includes some additional fields that WebAuthn API would then attempt to read from a potentially unallocated memory area. There are two potential fixes: this one (simply lowering the structure version, since we don't use the v6-specific fields anyway) or adding v6 fields and keeping them uninitialized. Simply lowering the version sounds much easier.

Fixes #55290.

### CODE REVIEW

**Comment by bl-nero** [comment]
@ravicious tested this change and made a comment on the bug, so let me move this conversation here.

> Now I suppose it's a matter of figuring out why we had it set to 6 in the first place and if it doesn't break anything else. Alan mentioned something about versions here https://github.com/gravitational/teleport/pull/16635#discussion_r979073986.

This shouldn't break anything, as API version and structure versions are two different beasts. One describes general contracts of the API, and the structure version is something specific to a given structure type, and its primary job is to tell the dynamicly loaded DLL code how big the structure actually is.

Also see [this conversation](https://github.com/gravitational/teleport/pull/16634#discussion_r978873714), which Alan most likely referred to.

**Review by probakowski — APPROVED** [review]

File: lib/auth/webauthnwin/conv.go [hunk 1]
```diff
@@ -50,7 +50,7 @@ func assertOptionsToCType(in wantypes.PublicKeyCredentialRequestOptions, loginOp
 		// https://github.com/microsoft/webauthn/blob/7ab979cc833bfab9a682ed51761309db57f56c8c/webauthn.h#L36-L97
 		// contains information about different versions.
 		// We can set newest version and it still works on older APIs.
-		dwVersion:                     6,
+		dwVersion:                     5,
```
Comment (ravicious) [inline lib/auth/webauthnwin/conv.go:53]: It seems like we only need to backport this to v18, right? I wasn't able to reproduce this on 15, 16, and 17.

**Review by ravicious — APPROVED** [review]

**Comment by zmb3** [comment]
Looks like a couple tests need updating.

File: lib/auth/webauthnwin/conv.go (hunk 1 above)
Comment (bl-nero) [reply lib/auth/webauthnwin/conv.go:53]: I think I'll backport it further, since while you couldn't reproduce it, it was possible it was just a luck; the version numbers are still inconsistent with structure sizes.

Comment (ravicious) [reply lib/auth/webauthnwin/conv.go:53]: That makes sense. I suspect it might have to do with a webauthn package getting updated on master and the update making its way to v18 but not other branches. I thought of doing a git bisect to find this, but compilation times in a Windows VM are rather bad so it'd take ages.
