### PR TITLE
Cache PIV connections to share across the program execution

### LINKED ISSUE #46372: Yubikey race condition using tsh
Expected behavior:
As a user who uses YubiKey solely for Teleport, and does not use multiple `tsh` commands at the same time, `tsh` should not give  me errors relating to Yubikey being used by another application.

Current behavior:
When using `tsh ls` or `tsh ssh` I sometimes get this error:
```
tsh ls
Enter your YubiKey PIV PIN:
ERROR: connection error: desc = "transport: authentication handshake failed: tls: failed to sign handshake: could not connect to YubiKey as another application is using it. Please try again once the program that uses the YubiKey, such as yubikey-agent is closed"
```

Bug details:
- Teleport version: 14.3.20, 16.1.0
- Recreation steps: run `tsh ls` multiple times until the bug is triggered
- Debug logs

Workaround: Retry failed command

Quote from @nklaassen:
> I'm pretty sure the issue is tsh trying to use the same yubikey concurrently. When we dial to the auth server for something like tsh ls we race like 5 different dial methods https://github.com/gravitational/teleport/blob/d8292350ed7bca30929c5f1c326547746599ee3b/api/client/client.go#L320-L321. One of those lucky connection methods is going to open the yubikey connection first and prompt for PIN/touch, meanwhile all the other connection methods are going to time out. If that lucky first connection method wasn't the right one, all connection methods fail and the request fails. It seems to usually work if you retry because IIRC we cache the tap for ~15s.

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/46372
I think this fix should close the linked issue, but unfortunately I couldn't reproduce it.
This also provides a foundation for the hardware keys support in Connect which issues many requests asynchronously.

This PR is in 90% based on @Joerger work on caching PIV connections. Thanks to it, subsequent calls to the YubiKey don't have to constantly open & close a connection (which is time-consuming and blocks the key), but instead use a shared connection directly.
However, the shared connection can't be kept open for the lifetime of the program, because it would block access to the YubiKey for other programs (for example, another instance of `tsh` or `tctl`). Therefore, the connection is released after 5 seconds.

In addition to Brian's changes, I added a "warm up" call to the YubiKey, as proposed by Nic. This is mainly needed for Connect so that we can wait indefinitely for the user to enter a PIN/touch. But what's more important, if the user cancels the prompt, we can return early, before we start dialing. Otherwise, the gRPC retry mechanism will try to establish a connection, showing the same prompt to the user over and over again.
I think "warming up" the key is useful for tsh too.

Best to review commit by commit.

changelog: Resolved an issue that caused false positive errors incorrectly indicating that the YubiKey was in use by another application, while only tsh was accessing it

### CODE REVIEW

File: api/utils/keys/yubikey.go [hunk 1]
```diff
@@ -621,15 +665,15 @@ func (y *YubiKey) open() (yk *piv.YubiKey, err error) {
...
 	})
 	if err != nil {
-		return nil, trace.Wrap(err)
+		return trace.Wrap(err)
 	}
 
-	// Backoff and retry for up to 1 second.
-	retryCtx, cancel := context.WithTimeout(context.Background(), time.Second)
+	// Backoff and retry for a time slightly greater than releaseConnectionDelay.
+	retryCtx, cancel := context.WithTimeout(context.Background(), releaseConnectionDelay+100*time.Millisecond)
```
Comment (gzdunek) [inline api/utils/keys/yubikey.go:672]: I believe this timeout needs to greater than the timeout for releasing a connection. Otherwise, a caller that doesn't use the shared connection has basically no chance to do it.

Unfortunately, this also made the tests take much longer (6-11 seconds for a test). I tried to reuse the same `YubiKey` object as much as possible in the tests, but `keys.GetYubiKeyPrivateKey()` opens its own connection, and I'm not able to easily pass the key that I get from `keys.FindYubiKey()`.

File: api/client/proxy/client.go [hunk 2]
```diff
@@ -115,6 +118,22 @@ func (c *ClientConfig) CheckAndSetDefaults() error {
...
+				// a PIN or touch before a gRPC dial timeout occurs.
+				// The resulting "dial timeout" error is generic and doesn't indicate an issue with the
+				// hardware key itself (since YubiKey is treated like any other key).
+				// To avoid this, we perform a "warm-up" call to the key, ensuring it is ready
+				// before initiating the gRPC dial.
+				// This approach works because the connection is cached for a few seconds,
+				// allowing subsequent calls without requiring additional user action.
+				if priv, ok := cert.PrivateKey.(*keys.YubiKeyPrivateKey); ok {
+					b := make([]byte, 256)
+					_, err := priv.Sign(rand.Reader, b, crypto.SHA256)
```
Comment (gzdunek) [inline api/client/proxy/client.go:132]: I just realized that with this warm up code added, I'm not able to interrupt the program with Ctrl-C. I guess it's because prompting for password/touch blocks the program execution? I'm not sure where I should look at.

File: api/client/proxy/client.go [hunk 3]
```diff
@@ -115,6 +118,22 @@ func (c *ClientConfig) CheckAndSetDefaults() error {
...
+
+				// When a hardware key is used to store the private key, the user may fail to provide
+				// a PIN or touch before a gRPC dial timeout occurs.
+				// The resulting "dial timeout" error is generic and doesn't indicate an issue with the
+				// hardware key itself (since YubiKey is treated like any other key).
+				// To avoid this, we perform a "warm-up" call to the key, ensuring it is ready
+				// before initiating the gRPC dial.
+				// This approach works because the connection is cached for a few seconds,
+				// allowing subsequent calls without requiring additional user action.
+				if priv, ok := cert.PrivateKey.(*keys.YubiKeyPrivateKey); ok {
```
Comment (gzdunek) [inline api/client/proxy/client.go:130]: Ah, I can't assert to `keys.YubiKeyPrivateKey` because it lives in `yubikey.go` which is built only if `piv` tag is set.
Is this okay to move just this single struct to `yubikey_common.go` or not really?
Btw originally I tried `priv, ok := cert.PrivateKey.(*keys.PrivateKey); ok && priv.IsHardware()` but it didn't work :/

Comment (nklaassen) [reply api/client/proxy/client.go:130]: You can't move the struct because 2 of the fields are types from `github.com/go-piv/piv-go/piv` which requires build support IIUC

Comment (nklaassen) [reply api/client/proxy/client.go:130]: perhaps you could make YubiKeyPrivateKey implement a func `WarmupHardwareKey(context.Context) error`, and here check if cert.PrivateKey implements that interface

File: api/client/proxy/client.go (hunk 2 above)
Comment (nklaassen) [reply api/client/proxy/client.go:132]: I think we handle ctrl-c by just cancelling a context and hoping everything exits quickly after that. You could try my suggestion here with passing down a context https://github.com/gravitational/teleport/pull/47091#discussion_r1784902191

Comment (gzdunek) [reply api/client/proxy/client.go]: Fortunately, there is a context in `NewClient`, so I passed it down to `CheckAndSetDefaults` and then to `WarmupHardwareKey`.
After some debugging, I realized that the problem with handling Ctrl-C was caused by the `singer.Sign` function that blocked the program, waiting for the user to provide a PIN or touch. My workaround for this was to wrap it in a goroutine and abandon the result when the context is canceled. I believe it is a standard way of dealing with such problems in Go.

File: api/client/proxy/client.go (hunk 3 above)
Comment (gzdunek) [reply api/client/proxy/client.go]: That's a great idea, thanks! It's actually better than what I had before, because I need to call the private `y.sign` (to pass the context).

**Comment by gzdunek** [comment]
Friendly ping @nklaassen, @Joerger

File: api/client/proxy/client.go [hunk 4]
```diff
@@ -115,6 +115,21 @@ func (c *ClientConfig) CheckAndSetDefaults() error {
...
+				// To avoid this, we perform a "warm-up" call to the key, ensuring it is ready
+				// before initiating the gRPC dial.
+				// This approach works because the connection is cached for a few seconds,
+				// allowing subsequent calls without requiring additional user action.
+				if priv, ok := cert.PrivateKey.(HardwareKeyWarmer); ok {
+					err := priv.WarmupHardwareKey(ctx)
+					if err != nil {
+						return nil, trace.Wrap(err)
+					}
+				}
```
Comment (nklaassen) [inline api/client/proxy/client.go:132]: it feels a bit off to call the warmup code in this function while just fetching the `grpc.TransportCredentials`. Seems like it could accidentally be called too early or too often.

See how clusterCredentials implements ClientHandshake (part of the grpc.TransportCredentials interface). It seems like ClientHandshake would be a more appropriate place to do this.

Maybe we could repurpose clusterCredentials to also handle this warmup. We could return a clusterCredentials here, instead of just credentials.NewTLS that gets wrapped in clusterCredentials at the call site. The clusterCredentials here could capture the hardware key and expose the cluster name with a method

Comment (Joerger) [reply api/client/proxy/client.go:132]: I agree in theory, but I tested your suggestion and it leads to the timeout we're trying to avoid:

```
2024-10-09T17:15:05-07:00 DEBU [CLIENT]    Attempting to issue a single-use user certificate with an MFA check. client/cluster_client.go:313
## warming up
Enter your YubiKey PIV PIN:
ERROR REPORT:
Original Error: *interceptors.RemoteError connection error: desc = &#34;transport: authentication handshake failed: context deadline exceeded&#34;
Stack Trace:
        github.com/gravitational/teleport/api/client/client.go:3709 github.com/gravitational/teleport/api/client.(*Client).CreateAuthenticateChallenge
        github.com/gravitational/teleport/lib/client/cluster_client.go:656 github.com/gravitational/teleport/lib/client.PerformMFACeremony
        github.com/gravitational/teleport/lib/client/cluster_client.go:442 github.com/gravitational/teleport/lib/client.(*ClusterClient).performMFACeremony
        github.com/gravitational/teleport/lib/client/cluster_client.go:314 github.com/gravitational/teleport/lib/client.(*ClusterClient).SessionSSHConfig
        github.com/gravitational/teleport/lib/client/api.go:1931 github.com/gravitational/teleport/lib/client.(*TeleportClient).connectToNodeWithMFA
        github.com/gravitational/teleport/lib/client/api.go:1812 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToNode.func3
        runtime/asm_arm64.s:1223 runtime.goexit
User Message: connection error: desc = &#34;transport: authentication handshake failed: context deadline exceeded&#34;
```

Same issue with adding the warmup to `tlsCfg.GetClientCertificate` and using the `CertificateRequestInfo.Context()`.

I think we would need to do the warmup before dialing the connection, if that's possible. I tried to add the warmup to the context dialer but it didn't work.

But the current implementation covers where we need the warmup, I think this is a good enough place for now.

File: api/utils/keys/yubikey.go [hunk 5]
```diff
@@ -644,150 +728,148 @@ func (y *YubiKey) open() (yk *piv.YubiKey, err error) {
...
+		return trace.LimitExceeded("could not connect to YubiKey as another application is using it. Please try again once the program that uses the YubiKey, such as yubikey-agent is closed")
 	} else if err != nil {
-		return nil, trace.Wrap(err)
+		return trace.Wrap(err)
 	}
-	return yk, nil
+
+	c.waitClose.Add(1)
+	go func() {
+		c.waitClose.Wait()
```
[the remark this answers is not in the document]
Comment (Joerger) [reply api/utils/keys/yubikey.go:738]: Fair point, maybe a waitgroup isn't the best option here, but I haven't thought of something simpler yet.

>  Something like return c.releaseConnection, err so that the caller couldn't avoid it without explicitly ignoring the return value could work

I like that idea

**Review by Joerger — COMMENTED** [review]
Tested it with `tsh`, LGTM, barring some minor comments.

File: api/client/proxy/client.go (hunk 4 above)
Comment (nklaassen) [reply api/client/proxy/client.go:132]: Oh, yeah I guess we want to do it before we hand off to any gRPC code, not just specifically the tls dial, makes sense. I'm okay with it here then.

File: api/utils/keys/yubikey.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (gzdunek) [reply api/utils/keys/yubikey.go:744]: I like it too! I also moved `c.releaseConnection` to a function inside `c.connect`. I hope I understood your comment correctly, Nic :)

File: api/client/proxy/client.go (hunk 4 above)
Comment (gzdunek) [reply api/client/proxy/client.go]: Yeah, I feel that warming up the key in `ClientHandshake` wouldn't give us anything, since that's where `YubiKeyPrivateKey.Sign` would be called anyway (I think so).

File: api/utils/keys/yubikey.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (Joerger) [reply api/utils/keys/yubikey.go:744]: There is actually a race condition here - if the waitgroup is empty and the connection is closed, right as a new connection tries to connect, it would get a nil connection. Since this is my faulty code, here's my suggested fix:

```diff
diff --git a/api/utils/keys/yubikey.go b/api/utils/keys/yubikey.go
index 4a402a311f..2399cdc78e 100644
--- a/api/utils/keys/yubikey.go
+++ b/api/utils/keys/yubikey.go
@@ -336,6 +336,7 @@ func (y *YubiKeyPrivateKey) sign(ctx context.Context, rand io.Reader, digest []b
 		return nil, trace.Wrap(err)
 	}
 	defer release()
+
 	var touchPromptDelayTimer *time.Timer
 	if y.attestation.TouchPolicy != piv.TouchPolicyNever {
 		touchPromptDelayTimer = time.NewTimer(signTouchPromptDelay)
@@ -675,9 +676,9 @@ type sharedPIVConnection struct {
 	card string
 
 	// conn is the shared PIV connection.
-	conn      *piv.YubiKey
-	mu        sync.Mutex
-	waitClose sync.WaitGroup
+	conn              *piv.YubiKey
+	mu                sync.Mutex
+	activeConnections int
 }
 
 // connect a connection to YubiKey PIV module. The returned connection should be closed once
@@ -688,14 +689,30 @@ func (c *sharedPIVConnection) connect() (func(), error) {
 	defer c.mu.Unlock()
 
 	release := func() {
-		go func() {
-			time.Sleep(releaseConnectionDelay)
-			c.waitClose.Done()
-		}()
+		c.mu.Lock()
+		defer c.mu.Unlock()
+		c.activeConnections--
+
+		// If this is the last active connection, close after a delay,
+		// giving other callers a chance to claim the connection first.
+		if c.activeConnections == 0 {
+			go func() {
+				time.Sleep(releaseConnectionDelay)
+
+				c.mu.Lock()
+				defer c.mu.Unlock()
+
+				// If there are still no new active connections, close the shared connection.
+				if c.activeConnections == 0 {
+					c.conn.Close()
+					c.conn = nil
+				}
+			}()
+		}
 	}
 
 	if c.conn != nil {
-		c.waitClose.Add(1)
+		c.activeConnections++
 		return release, nil
 	}
 
@@ -739,16 +756,7 @@ func (c *sharedPIVConnection) connect() (func(), error) {
 		return nil, trace.Wrap(err)
 	}
 
-	c.waitClose.Add(1)
-	go func() {
-		c.waitClose.Wait()
-
-		c.mu.Lock()
-		defer c.mu.Unlock()
-		c.conn.Close()
-		c.conn = nil
-	}()
-
+	c.activeConnections++
 	return release, nil
 }
```

File: api/utils/keys/yubikey.go [hunk 6]
```diff
@@ -648,146 +738,137 @@ func (y *YubiKey) open() (yk *piv.YubiKey, err error) {
...
-	const retryError = "connecting to smart card: the smart card cannot be accessed because of other connections outstanding"
-	return strings.Contains(err.Error(), retryError)
+	c.waitClose.Add(1)
+	go func() {
+		c.waitClose.Wait()
+
+		c.mu.Lock()
+		defer c.mu.Unlock()
+		c.conn.Close()
+		c.conn = nil
```
Comment (nklaassen) [inline api/utils/keys/yubikey.go:749]: Hmm I think there may be a race condition here

1. all current connections expire and c.waitClose.Wait() returns
2. this func tries to lock the mutex
3. there is a concurrent call to connect() which locks the mutex first, adds 1 to the waitgroup, unlocks the mutex and returns
4. then this func gets the lock, closes the conn and sets it to nil
5. the other caller of connect probably panics trying to use the nil connection

Could probably solve it a couple ways, maybe maintain a count of open connections protected by the mutex and loop here while it's not 0? something like
```go
go func() {
	for {
		c.waitClose.Wait()
		c.mu.Lock()
		if c.openConnections == 0 {
			defer c.mu.Unlock()
			break
		}
		c.mu.Unlock()
	}
	c.conn.Close()
	c.conn = nil
}()
```

Comment (Joerger) [reply api/utils/keys/yubikey.go:749]: Yep I found the same thing - https://github.com/gravitational/teleport/pull/47091#discussion_r1796015833

File: api/utils/keys/yubikey.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (gzdunek) [reply api/utils/keys/yubikey.go]: Thanks for the code!
I made minor modifications:
* Before decrementing `activeConnections` I check if the number is greater than 0. There is a chance that someone would call `release` twice.
* In the release goroutine I check if the connection hasn't been closed already. There was a bug in the following scenario:
1. Call `connect` and `release` the first time - the first release goroutine starts (`c.activeConnections == 0`).
2. Call `connect` and `release` the second time - the second release goroutine starts (`c.activeConnections == 0`).
3. The first goroutine closes the connection.
4. The second gouroutine makes an attempt to close the connection too (since `c.activeConnections == 0`) and it panics because it has already been closed.

File: api/utils/keys/yubikey.go (hunk 6 above)
Comment (gzdunek) [reply api/utils/keys/yubikey.go]: Thanks, I used the Brian's code, should be fixed now.

File: api/utils/keys/yubikey.go [hunk 7]
```diff
@@ -586,29 +657,71 @@ func (y *YubiKey) checkOrSetPIN(ctx context.Context) error {
...
+
+				// Close the shared connection if there are still no new active connections,
+				// and the connection hasn't been yet closed by another goroutine.
+				if c.activeConnections == 0 && c.conn != nil {
+					c.conn.Close()
+					c.conn = nil
+				}
+			}()
+		}
+	}
```
Comment (Joerger) [inline api/utils/keys/yubikey.go:718]: One fix and a couple nits.

fix: We should actually sleep from the start, before decrementing active connections. Otherwise, we could have the following situation: client connects, client disconnects. 4 seconds later, second client connects, and disconnects. 1 second later, the first client closes the connection. Instead, we should wait 5 seconds from the second client disconnect before closing. So we need to run the goroutine+sleep before decrementing the active connections.

nit: Now that we are decrementing and closing under the same lock, we can safely remove the `c.conn != nil` check, this should never be the case anymore.

nit2: We also don't need the `if c.activeConnections > 0` check. Every `connect` should be accompanied by `release`, so active connections will always be > 0 in this check, before it's decremented to its minimum value 0.

IMO the nits make it easier to implement bugs in the future, I'd rather the system fail loudly with faulty code (panic) so we fix it promptly.

```suggestion
	release := func() {
		go func() {
			time.Sleep(releaseConnectionDelay)
			
			c.mu.Lock()
			defer c.mu.Unlock()
			
			c.activeConnections--
			if c.activeConnections == 0 {
				c.conn.Close()
				c.conn = nil
			}
		}
	}
```

File: api/utils/keys/yubikey.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (Joerger) [reply api/utils/keys/yubikey.go]: Yeah good catch, shared a different suggestion below to fix the underlying issue.

**Review by nklaassen — APPROVED** [review]
lgtm assuming Brian's suggesting here gets accepted/resolved https://github.com/gravitational/teleport/pull/47091/files#r1797232730

File: api/utils/keys/yubikey.go (hunk 7 above)
Comment (gzdunek) [reply api/utils/keys/yubikey.go:718]: >Otherwise, we could have the following situation: client connects, client disconnects. 4 seconds later, second client connects, and disconnects. 1 second later, the first client closes the connection. Instead, we should wait 5 seconds from the second client disconnect before closing.

Yeah, I thought about it, but for some reason it seemed to me that the correct behavior is to close the connection only after waiting for the first client to release 🤦. But I agree, it makes much more sense to extend the duration with each connected client.
Fix applied.

**Review by Joerger — APPROVED** [review]
