### PR TITLE
Fixes ACME default configuration

### LINKED ISSUE #5771: ACME TLS-ALPN-01 challenge requires port 443
### Description

**What happened**:

Generate Teleport config using:

```
teleport configure --cluster-name=teleport.example.com --acme --acme-email=alice@example.com > /tmp/teleport.yaml
```

Start it as usual:

```
sudo -E /usr/local/bin/teleport start -d -c /tmp/teleport.yaml
```

Open https://teleport.example.com:3080 in browser and observe it fail to fetch certificate from Let's Encrypt:

```
ERRO [PROXY:SER] "proxy2021/02/27 00:49:17 http: TLS handshake error from 1.2.3.4:12345: acme/autocert: unable to satisfy \"https://acme-v02.api.letsencrypt.org/acme/authz-v3/123456789\" for domain \"teleport.example.com\": no viable challenge type found\n" utils/cli.go:272
```

Teleport uses [TLS-ALPN-01](https://letsencrypt.org/docs/challenge-types/#tls-alpn-01) challenge which it seems like can only be done on port 443:

> This challenge was developed after TLS-SNI-01 became deprecated, and is being developed as a separate standard. Like TLS-SNI-01, it is performed via TLS on port 443.

After editing `/tmp/teleport.yaml` to change web proxy port to 443, it works.

**What you expected to happen**:

Ideally the challenge should support any port but it doesn't seem to be currently possible.

Next best thing would probably be updating `teleport configure` command to generate config with port 443 and also add file config validation to make sure port is 443 if ACME is enabled.

### Reproduction Steps

Described above.

### Server Details
- Teleport version (run `teleport version`): `Teleport v6.0.0-rc.1 git:v6.0.0-rc.1-0-g5470bb912 go1.15.5`
- Server OS (e.g. from `/etc/os-release`): Amazon Linux 2
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS EC2 instance

### PR DESCRIPTION
**Pull request by klizhentas**
Fixes #5771, tctl configure has to generate port :443
when ACME is on, because TLS-ALPN-01 challenge only works on 443 port.

### CODE REVIEW

**Comment by klizhentas** [comment]
@russjones @r0mant can you folks please review
@benarent can you give it a run too?

**Comment by benarent** [comment]
I just tried this on a new cluster and it worked using the below, the one unrelated issue would be to change how we setup configure. I have a note below. 
 
```
$ sudo teleport configure --cluster-name=silver.asteroid.earth --acme --acme-email=ben@goteleport.com -o file
Wrote config to file "/etc/teleport.yaml". Now you can start the server. Happy Teleporting!
```

```diff
teleport:
  nodename: ip-172-31-13-209
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
  ca_pin: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: silver.asteroid.earth
ssh_service:
  enabled: "yes"
  labels:
    env: example
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3023
  web_listen_addr: :443
  public_addr: silver.asteroid.earth:443
  https_keypairs: []
  acme:
    enabled: "yes"
    email: ben@goteleport.com
```

When using the new script, I've noticed that the TLS certificate adds the node name into the cert. I've found that setting a public_addr is better as an IP/FQDN is needed for plugins to work. 

```
INFO [CA]        Generating TLS certificate {0x431d270 0xc000294180 1.3.9999.1.7=#131573696c7665722e61737465726f69642e6561727468,CN=eb704764-01dc-416c-8c8a-542de3c7abf1.silver.asteroid.earth,O=Admin,POSTALCODE=null,STREET= 2031-03-02 21:30:30.573250614 +0000 UTC [ip-172-31-13-209 *.teleport.cluster.local teleport.cluster.local]}. common_name:eb704764-01dc-416c-8c8a-542de3c7abf1.silver.asteroid.earth dns_names:[ip-172-31-13-209 *.teleport.cluster.local teleport.cluster.local] locality:[] not_after:2031-03-02 21:30:30.573250614 +0000 UTC org:[Admin] org_unit:[] tlsca/ca.go:562
```

File: lib/config/fileconf.go [hunk 1]
```diff
@@ -380,10 +380,10 @@ func MakeSampleFileConfig(flags SampleFlags) (fc *FileConfig, err error) {
...
 		p.ACME.EnabledFlag = "yes"
 		p.ACME.Email = flags.ACMEEmail
-		p.PublicAddr = utils.Strings{
-			net.JoinHostPort(flags.ClusterName,
-				fmt.Sprintf("%d", conf.Proxy.WebAddr.Port(defaults.HTTPListenPort))),
-		}
+		// ACME uses TLS-ALPN-01 challenge that requires port 443
+		// https://letsencrypt.org/docs/challenge-types/#tls-alpn-01
+		p.PublicAddr = utils.Strings{net.JoinHostPort(flags.ClusterName, fmt.Sprintf("%d", teleport.StandardHTTPSPort))}
+		p.WebAddr = fmt.Sprintf(":%d", teleport.StandardHTTPSPort)
```
Comment (russjones) [inline lib/config/fileconf.go:386]: You can use `strconv.Itoa` here like the following:

```go
p.PublicAddr = utils.Strings{net.JoinHostPort(flags.ClusterName, strconv.Itoa(teleport.StandardHTTPSPort))}
p.WebAddr = net.JoinHostPort("", strconv.Itoa(teleport.StandardHTTPSPort))
```

**Review by russjones — APPROVED** [review]

**Comment by klizhentas** [comment]
@benarent not sure I follow, can you please elaborate on the IP/FQDN?

**Comment by benarent** [comment]
> not sure I follow, can you please elaborate on the IP/FQDN?

^ I'm going to create another ticket that outlines this issue.
