### PR TITLE
Fix issue applying the --listen-ip flag

### LINKED ISSUE #51064: Using --listen-ip parameter shows error with starting teleport
Expected behavior:

The `--listen-ip` would be succesful or give informative information why this isn't a valid config.  The parameter otherwise needs to support a port as well.

Current behavior:

`teleport start --listen-ip=172.2.2.2`

```bash
ERRO             failed parsing address: '' config/configuration.go:2917
ERRO             failed parsing address: '' config/configuration.go:2917
ERRO             failed parsing address: '' config/configuration.go:2917
```

The issue appears to be it's setting this ip as a listen address when the services expect a host and port. Code here: https://github.com/gravitational/teleport/blob/228b392330563d17ccc21ec153e36f315eb78c83/lib/config/configuration.go#L2784

Bug details:
- Teleport version: 17.1.6
- Recreation steps

1. Run `teleport start --listen-ip=<ip>`

### PR DESCRIPTION
**Pull request by zmb3**
When you use the --listen-ip flag, some very old Teleport code attempts to replace the IP (but not the port) of a bunch of internal listening addresses.

Some of these addresses used to be required in older versions of Teleport, but are typically left empty in modern Teleport now that we have things like multiplexing and TLS routing.

The code that applies the listen IP was not written to be able to handle empty addresses, so it would log errors on startup.

Fix this by only updating addresses that are non-empty.

Note: there may well be more issues with the --listen-ip flag, as it is not frequently used and was written many years ago.

Closes #51064

### CODE REVIEW

File: lib/config/configuration.go [hunk 1]
```diff
@@ -2783,15 +2783,16 @@ func isCmdLabelSpec(spec string) (types.CommandLabel, error) {
 // a given IP
 func applyListenIP(ip net.IP, cfg *servicecfg.Config) {
 	listeningAddresses := []*utils.NetAddr{
-		&cfg.Auth.ListenAddr,
```
Comment (zmb3) [inline lib/config/configuration.go:2786]: This duplicate line has been in the code since at least Teleport 7, but I suspect even longer!

**Review by rosstimothy — APPROVED** [review]

**Review by avatus — APPROVED** [review]
