### PR TITLE
Refactor events listeners and fix a race condition when closing RDP stream

### LINKED ISSUE #38373: Bring back user friendly error messages for known disconnects in desktop access
See https://github.com/gravitational/teleport/pull/37962#discussion_r1491393312 for details.

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/38373

I included a few changes in this PR:
1. Replaced listening to events from a verbose `useEffect` to a shorter `useListener`. The only point of this change is to limit  repeating the same code, there's no functional changes.
2. Fixed a race condition that caused TDP errors to be overwritten with websocket close messages. This consists of two parts:
   * On the backend side, a graceful disconnection now emits an error event instead of info event (I followed Zac's comment). Alternatively, we could convert TDP_INFO events to something like TDP_GRACEFUL_DISCONNECT, but I don't think we need it. In the UI we show a generic error in any case.
   * On the frontend side, the `socket.onclose()` handler is removed before closing the socket when an error occurs first. Thanks to it, we don't overwrite the original error which is more important.
   * Users should now consistently see this error when they click sign out in the remote machine:
     image

3. I moved some functions from `useTdpClientCanvas` to the main component. The hook will be removed in a future PR, it only adds more layers of code which make navigating through it more difficult.  There's no functional changes.

changelog: Resolved an issue that could cause WebSocket errors to appear after the graceful shutdown of a desktop session

Best to review commit by commit.

### CODE REVIEW

File: web/packages/teleport/src/lib/tdp/client.ts [hunk 1]
```diff
@@ -795,13 +795,9 @@ export default class Client extends EventEmitterMfaSender {
     this.emit(TdpClientEvent.TDP_INFO, info);
   }
 
-  // Ensures full cleanup of this object.
-  // Note that it removes all listeners first and then cleans up the socket,
-  // so don't call this if your calling object is relying on listeners.
   // It's safe to call this multiple times, calls subsequent to the first call
   // will simply do nothing.
   shutdown(closeCode = WebsocketCloseCode.NORMAL) {
-    this.removeAllListeners();
```
Comment (gzdunek) [inline web/packages/teleport/src/lib/tdp/client.ts:730]: I think this shouldn't have been here in the first place. 
This class doesn't create event listeners for its own purposes—its callers do. Because of that, it shouldn't be responsible for clearing them; that should be left to the callers. This became a problem for `onWsClose` callback I added. It was removed before we closed the socket so the listeners were not notified about it.

Previously, it worked purely by accident. `useTdpClientCanvas.clientOnWsClient` wasn't wrapped in `useCallback`, so when the user clicked the Disconnect button in the UI, a re-render occurred, causing the callback to be re-created and reattached as a listener.

File: web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx [hunk 2]
```diff
@@ -140,14 +131,16 @@ export default function useTdpClientCanvas(props: Props) {
...
-    setClipboardSharingState(defaultClipboardSharingState);
-    setTdpConnection({
-      status: '', // gracefully disconnecting
-      statusText: info,
+    setAlerts(prevState => {
+      return [
+        ...prevState,
+        {
+          content: info,
+          severity: 'info',
```
Comment (gzdunek) [inline web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx]: `TDP_INFO` is no longer used to signal disconnection, so now I show info warnings when we receive it.
But I'm not sure if it makes any sense, we don't have any code that sends info level alerts?

Comment (zmb3) [reply web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx]: The original intent was that the TDP "notification" message can be used for both fatal errors or non-fatal messages.

- `SeverityError` means there was a fatal error and the proxy is about to close the connection.
- `SeverityInfo` and `SeverityWarning` are for non-fatal messages that show up in the top right corner.

In reality, Isaiah used `SeverityInfo` to show connection close "errors" in a state that's not error, which is why there's nothing else that's using INFO level.

Maybe we need to treat these as two separate concepts:
- a severity, which indicates to the UI how to render the message
- whether or not this message is preceding a disconnect

**Comment by zmb3** [comment]
Changes look good to me. I'll try to test it a bit later before approving.

**Review by zmb3 — APPROVED** [review]
Works well, thanks!

**Review by avatus — APPROVED** [review]

**Comment by zmb3** [comment]
I'm pretty sure this fixes #38373.
