### PR TITLE
fix local re-register

### LINKED ISSUE #43856: Changing a cluster's `proxy_service.public_addr` with no `https_keypairs` results in rotation state sync errors
## Expected behavior

Changing the `public_addr` of a cluster's `proxy_service` should result in new self-signed certificates being generated for the `Proxy` without error.

## Current behavior:

Changing `proxy_service.public_addr` causes a rotation state error to repeat ad infinitum:

```
2024-07-04T14:37:38Z DEBU [PROC:1]    Service has started. pid:7.1 service:proxy.shutdown service/supervisor.go:312
2024-07-04T14:37:38Z DEBU [PROXY:PRO] Not initializing Kube Cluster resource watcher. pid:7.1 proxy/watcher.go:38
2024-07-04T14:37:38Z INFO [PROC:1]    Rotation in progress, updating SSH principals. pid:7.1 identity:Proxy additional_principals:[teleport-local bastion.teleport.com 0.0.0.0 localhost 127.0.0.1 ::1 remote.kube.proxy.teleport.cluster.local] current_principals:[164cbed7-2832-472f-9711-6d868a02c555.127.0.0.1.nip.io 164cbed7-2832-472f-9711-6d868a02c555 teleport-local.127.0.0.1.nip.io teleport-local localhost 127.0.0.1 ::1 127.0.0.1.nip.io remote.kube.proxy.teleport.cluster.local] service/connect.go:903
2024-07-04T14:37:38Z DEBU [PROXY:PRO] Not initializing Kube Cluster resource watcher. pid:7.1 proxy/watcher.go:92
2024-07-04T14:37:38Z INFO [PROC:1]    Rotation in progress, updating DNS names. pid:7.1 identity:Proxy additional_dns_names:[*.teleport.cluster.local teleport.cluster.local *.bastion.teleport.com] current_dns_names:[teleport-local 127.0.0.1.nip.io localhost remote.kube.proxy.teleport.cluster.local *.teleport.cluster.local teleport.cluster.local *.127.0.0.1.nip.io] service/connect.go:907
2024-07-04T14:37:38Z DEBU [PROC:1]    Service has started. pid:7.1 service:proxy.tls.alpn.sni.proxy service/supervisor.go:312
2024-07-04T14:37:38Z INFO [PROC:1]    Service has updated principals and DNS Names, going to request new principals and update. pid:7.1 identity:Proxy principals:[teleport-local bastion.teleport.com 0.0.0.0 localhost 127.0.0.1 ::1 remote.kube.proxy.teleport.cluster.local] dns_names:[*.teleport.cluster.local teleport.cluster.local *.bastion.teleport.com] service/connect.go:998
2024-07-04T14:37:38Z DEBU [PROC:1]    Generating new key pair. pid:7.1 identity:Proxy reason:re-register service/connect.go:344
2024-07-04T14:37:38Z INFO [PROXY:SER] Starting TLS ALPN SNI proxy server on. pid:7.1 listen_address:[::]:443 service/service.go:4943
2024-07-04T14:37:38Z DEBU [MX:PROXY:] Starting serving MUX, ID "proxy:proxy:kube" on address [::]:443 multiplexer/multiplexer.go:260
2024-07-04T14:37:38Z DEBU [PROC:1]    Service is completed and removed. pid:7.1 service:update.aws-oidc.deploy.service service/supervisor.go:262
2024-07-04T14:37:38Z DEBU [PROC:1]    Service has started. pid:7.1 service:closer service/supervisor.go:312
2024-07-04T14:37:38Z WARN [PROC:1]    Failed to sync rotation state. pid:7.1 error:[
ERROR REPORT:
Original Error: *trace.BadParameterError missing parameter hostname
Stack Trace:
	github.com/gravitational/teleport/lib/utils/utils.go:286 github.com/gravitational/teleport/lib/utils.Host
	github.com/gravitational/teleport/lib/auth/auth.go:4242 github.com/gravitational/teleport/lib/auth.(*Server).GenerateHostCerts
	github.com/gravitational/teleport/lib/auth/register.go:122 github.com/gravitational/teleport/lib/auth.ReRegister
	github.com/gravitational/teleport/lib/service/connect.go:412 github.com/gravitational/teleport/lib/service.(*TeleportProcess).reRegister
	github.com/gravitational/teleport/lib/service/connect.go:999 github.com/gravitational/teleport/lib/service.(*TeleportProcess).rotate
	github.com/gravitational/teleport/lib/service/connect.go:869 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncServiceRotationState
	github.com/gravitational/teleport/lib/service/connect.go:848 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationState
	github.com/gravitational/teleport/lib/service/connect.go:811 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationStateAndBroadcast
	github.com/gravitational/teleport/lib/service/connect.go:743 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationStateCycle
	github.com/gravitational/teleport/lib/service/connect.go:707 github.com/gravitational/teleport/lib/service.(*TeleportProcess).periodicSyncRotationState
	github.com/gravitational/teleport/lib/service/supervisor.go:588 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	github.com/gravitational/teleport/lib/service/supervisor.go:313 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	runtime/asm_arm64.s:1222 runtime.goexit
User Message: missing parameter hostname] service/connect.go:816
2024-07-04T14:37:38Z WARN [PROC:1]    Sync rotation state cycle failed. pid:7.1 retry_interval:10s service/connect.go:712
2024-07-04T14:37:38Z DEBU [PROC:1]    Teleport component has started. pid:7.1 component:proxy service/state.go:118
2024-07-04T14:37:39Z DEBU [PROXY:1]   List of known proxies updated: ["164cbed7-2832-472f-9711-6d868a02c555"]. pid:7.1 services/watcher.go:534
2024-07-04T14:37:41Z INFO [PROC:1]    Initiating new sync rotation state cycle after backoff. pid:7.1 backoff_time:3.483435535s service/connect.go:717
2024-07-04T14:37:41Z INFO [PROC:1]    Rotation in progress, updating SSH principals. pid:7.1 identity:Proxy additional_principals:[teleport-local bastion.teleport.com 0.0.0.0 localhost 127.0.0.1 ::1 remote.kube.proxy.teleport.cluster.local] current_principals:[164cbed7-2832-472f-9711-6d868a02c555.127.0.0.1.nip.io 164cbed7-2832-472f-9711-6d868a02c555 teleport-local.127.0.0.1.nip.io teleport-local localhost 127.0.0.1 ::1 127.0.0.1.nip.io remote.kube.proxy.teleport.cluster.local] service/connect.go:903
2024-07-04T14:37:41Z INFO [PROC:1]    Rotation in progress, updating DNS names. pid:7.1 identity:Proxy additional_dns_names:[*.teleport.cluster.local teleport.cluster.local *.bastion.teleport.com] current_dns_names:[teleport-local 127.0.0.1.nip.io localhost remote.kube.proxy.teleport.cluster.local *.teleport.cluster.local teleport.cluster.local *.127.0.0.1.nip.io] service/connect.go:907
2024-07-04T14:37:41Z INFO [PROC:1]    Service has updated principals and DNS Names, going to request new principals and update. pid:7.1 identity:Proxy principals:[teleport-local bastion.teleport.com 0.0.0.0 localhost 127.0.0.1 ::1 remote.kube.proxy.teleport.cluster.local] dns_names:[*.teleport.cluster.local teleport.cluster.local *.bastion.teleport.com] service/connect.go:998
2024-07-04T14:37:41Z DEBU [PROC:1]    Returning existing key pair for. pid:7.1 identity:Proxy reason:re-register service/connect.go:341
2024-07-04T14:37:41Z WARN [PROC:1]    Failed to sync rotation state. pid:7.1 error:[
ERROR REPORT:
Original Error: *trace.BadParameterError missing parameter hostname
Stack Trace:
	github.com/gravitational/teleport/lib/utils/utils.go:286 github.com/gravitational/teleport/lib/utils.Host
	github.com/gravitational/teleport/lib/auth/auth.go:4242 github.com/gravitational/teleport/lib/auth.(*Server).GenerateHostCerts
	github.com/gravitational/teleport/lib/auth/register.go:122 github.com/gravitational/teleport/lib/auth.ReRegister
	github.com/gravitational/teleport/lib/service/connect.go:412 github.com/gravitational/teleport/lib/service.(*TeleportProcess).reRegister
	github.com/gravitational/teleport/lib/service/connect.go:999 github.com/gravitational/teleport/lib/service.(*TeleportProcess).rotate
	github.com/gravitational/teleport/lib/service/connect.go:869 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncServiceRotationState
	github.com/gravitational/teleport/lib/service/connect.go:848 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationState
	github.com/gravitational/teleport/lib/service/connect.go:811 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationStateAndBroadcast
	github.com/gravitational/teleport/lib/service/connect.go:743 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationStateCycle
	github.com/gravitational/teleport/lib/service/connect.go:707 github.com/gravitational/teleport/lib/service.(*TeleportProcess).periodicSyncRotationState
	github.com/gravitational/teleport/lib/service/supervisor.go:588 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	github.com/gravitational/teleport/lib/service/supervisor.go:313 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	runtime/asm_arm64.s:1222 runtime.goexit
User Message: missing parameter hostname] service/connect.go:816
2024-07-04T14:37:41Z WARN [PROC:1]    Sync rotation state cycle failed. pid:7.1 retry_interval:10s service/connect.go:712
2024-07-04T14:37:45Z DEBU [AUTH]      Checking for new teleport releases via github api. auth/auth.go:1458
2024-07-04T14:37:49Z INFO [PROC:1]    Initiating new sync rotation state cycle after backoff. pid:7.1 backoff_time:7.123259512s service/connect.go:717
2024-07-04T14:37:49Z INFO [PROC:1]    Rotation in progress, updating SSH principals. pid:7.1 identity:Proxy additional_principals:[teleport-local bastion.teleport.com 0.0.0.0 localhost 127.0.0.1 ::1 remote.kube.proxy.teleport.cluster.local] current_principals:[164cbed7-2832-472f-9711-6d868a02c555.127.0.0.1.nip.io 164cbed7-2832-472f-9711-6d868a02c555 teleport-local.127.0.0.1.nip.io teleport-local localhost 127.0.0.1 ::1 127.0.0.1.nip.io remote.kube.proxy.teleport.cluster.local] service/connect.go:903
2024-07-04T14:37:49Z INFO [PROC:1]    Rotation in progress, updating DNS names. pid:7.1 identity:Proxy additional_dns_names:[*.teleport.cluster.local teleport.cluster.local *.bastion.teleport.com] current_dns_names:[teleport-local 127.0.0.1.nip.io localhost remote.kube.proxy.teleport.cluster.local *.teleport.cluster.local teleport.cluster.local *.127.0.0.1.nip.io] service/connect.go:907
2024-07-04T14:37:49Z INFO [PROC:1]    Service has updated principals and DNS Names, going to request new principals and update. pid:7.1 identity:Proxy principals:[teleport-local bastion.teleport.com 0.0.0.0 localhost 127.0.0.1 ::1 remote.kube.proxy.teleport.cluster.local] dns_names:[*.teleport.cluster.local teleport.cluster.local *.bastion.teleport.com] service/connect.go:998
2024-07-04T14:37:49Z DEBU [PROC:1]    Returning existing key pair for. pid:7.1 identity:Proxy reason:re-register service/connect.go:341
2024-07-04T14:37:49Z WARN [PROC:1]    Failed to sync rotation state. pid:7.1 error:[
ERROR REPORT:
Original Error: *trace.BadParameterError missing parameter hostname
Stack Trace:
	github.com/gravitational/teleport/lib/utils/utils.go:286 github.com/gravitational/teleport/lib/utils.Host
	github.com/gravitational/teleport/lib/auth/auth.go:4242 github.com/gravitational/teleport/lib/auth.(*Server).GenerateHostCerts
	github.com/gravitational/teleport/lib/auth/register.go:122 github.com/gravitational/teleport/lib/auth.ReRegister
	github.com/gravitational/teleport/lib/service/connect.go:412 github.com/gravitational/teleport/lib/service.(*TeleportProcess).reRegister
	github.com/gravitational/teleport/lib/service/connect.go:999 github.com/gravitational/teleport/lib/service.(*TeleportProcess).rotate
	github.com/gravitational/teleport/lib/service/connect.go:869 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncServiceRotationState
	github.com/gravitational/teleport/lib/service/connect.go:848 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationState
	github.com/gravitational/teleport/lib/service/connect.go:811 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationStateAndBroadcast
	github.com/gravitational/teleport/lib/service/connect.go:743 github.com/gravitational/teleport/lib/service.(*TeleportProcess).syncRotationStateCycle
	github.com/gravitational/teleport/lib/service/connect.go:707 github.com/gravitational/teleport/lib/service.(*TeleportProcess).periodicSyncRotationState
	github.com/gravitational/teleport/lib/service/supervisor.go:588 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	github.com/gravitational/teleport/lib/service/supervisor.go:313 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	runtime/asm_arm64.s:1222 runtime.goexit
User Message: missing parameter hostname] service/connect.go:816
2024-07-04T14:37:49Z WARN [PROC:1]    Sync rotation state cycle failed. pid:7.1 retry_interval:10s service/connect.go:712
```

Config change was as shown here:
```diff
version: v3
teleport:
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
-  public_addr: 127.0.0.1.nip.io:443
+  public_addr: bastion.teleport.com:443
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme:
    enabled: "yes"
    email: gus+acme@goteleport.com
```

Changing `teleport.nodename` also has a similar effect.

Bug details:
- Teleport version: 16.0.1

### PR DESCRIPTION
**Pull request by fspmarshall**
Fixes an issue introduced in https://github.com/gravitational/teleport/pull/41467 which could cause reissue of certificates to fail for a service which was running alongside a local auth server, had a listener bound to `0.0.0.0`, and did not have `advertise_ip` set.  With this change, local re-register takes on the same behavior as local register, using `127.0.0.1` as the default remote address value.

Fixes https://github.com/gravitational/teleport/issues/43856

changelog: fixed an issue that would cause reissue of certificates to fail in some scenarios where a local auth service was present.

### CODE REVIEW

**Review by rosstimothy — APPROVED** [review]

File: lib/service/connect.go [hunk 1]
```diff
@@ -395,7 +395,13 @@ func (process *TeleportProcess) reRegister(conn *Connector, additionalPrincipals
...
 	if srv := process.getLocalAuth(); srv != nil {
 		clt = srv
-		remoteAddr = process.Config.AdvertiseIP
+		// auth server typically extracts remote addr from conn. since we're using the local auth
+		// directly we must supply a reasonable remote addr value. preferably the advertise IP, but
+		// otherwise localhost.
+		remoteAddr = defaults.Localhost
+		if process.Config.AdvertiseIP != "" {
+			remoteAddr = process.Config.AdvertiseIP
+		}
```
Comment (espadolini) [inline lib/service/connect.go:404]: It'd be nice to have this logic in a single place rather than duplicate it here and in `lib/auth.LocalRegister` - or at least have cross referencing comments between the two?

Comment (espadolini) [inline lib/service/connect.go:404]:
```suggestion
		remoteAddr = cmp.Or(
			process.Config.AdvertiseIP,
			defaults.Localhost,
		)
```

(also, do we really need to use a nonlocal `remoteAddr` variable here? we leave it blank if we don't have a local auth)

**Review by espadolini — APPROVED** [review]
