### PR TITLE
Fix flaky test `TestServer_Authenticate_headless`

### LINKED ISSUE #23505: Race in `TestServer_Authenticate_headless`
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4500917721/jobs/7920658061?pr=23228

#### Relevant snippet

```
WARNING: DATA RACE
Read at 0x00c00e1d2be8 by goroutine 39085:
  github.com/gravitational/teleport/api/utils.UTC()
      /__w/teleport/teleport/api/utils/time.go:29 +0x3e
  github.com/gravitational/teleport/api/types.(*Metadata).CheckAndSetDefaults()
      /__w/teleport/teleport/api/types/resource.go:401 +0x104
  github.com/gravitational/teleport/api/types.(*HeadlessAuthentication).CheckAndSetDefaults()
      /__w/teleport/teleport/api/types/headlessauthn.go:26 +0x79
  github.com/gravitational/teleport/lib/services.ValidateHeadlessAuthentication()
      /__w/teleport/teleport/lib/services/headlessauthn.go:32 +0x39
  github.com/gravitational/teleport/lib/auth.(*Server).GetHeadlessAuthentication.func1()
      /__w/teleport/teleport/lib/auth/auth.go:4753 +0x44
  github.com/gravitational/teleport/lib/services/local.(*HeadlessAuthenticationWatcher).Wait()
      /__w/teleport/teleport/lib/services/local/headlessauthn_watcher.go:279 +0x5bc
  github.com/gravitational/teleport/lib/auth.(*Server).GetHeadlessAuthentication()
      /__w/teleport/teleport/lib/auth/auth.go:4752 +0x204
  github.com/gravitational/teleport/lib/auth.TestServer_Authenticate_headless.func1.1()
      /__w/teleport/teleport/lib/auth/auth_login_test.go:718 +0x192

Previous write at 0x00c00e1d2be8 by goroutine 39078:
  github.com/gravitational/teleport/api/utils.UTC()
      /__w/teleport/teleport/api/utils/time.go:34 +0x212
  github.com/gravitational/teleport/api/types.(*Metadata).CheckAndSetDefaults()
      /__w/teleport/teleport/api/types/resource.go:401 +0x104
  github.com/gravitational/teleport/api/types.(*HeadlessAuthentication).CheckAndSetDefaults()
      /__w/teleport/teleport/api/types/headlessauthn.go:26 +0x79
  github.com/gravitational/teleport/lib/services/local.marshalHeadlessAuthenticationToItem()
      /__w/teleport/teleport/lib/services/local/headlessauthn.go:124 +0x47
  github.com/gravitational/teleport/lib/services/local.(*IdentityService).CompareAndSwapHeadlessAuthentication()
      /__w/teleport/teleport/lib/services/local/headlessauthn.go:63 +0x84
  github.com/gravitational/teleport/lib/auth.(*Server).CompareAndSwapHeadlessAuthentication()
      /__w/teleport/teleport/lib/auth/auth.go:4761 +0xe3
  github.com/gravitational/teleport/lib/auth.(*Server).authenticateHeadless()
      /__w/teleport/teleport/lib/auth/methods.go:383 +0x629
  github.com/gravitational/teleport/lib/auth.(*Server).authenticateUser()
      /__w/teleport/teleport/lib/auth/methods.go:208 +0x350
  github.com/gravitational/teleport/lib/auth.(*Server).AuthenticateUser()
      /__w/teleport/teleport/lib/auth/methods.go:118 +0xf0
  github.com/gravitational/teleport/lib/auth.(*Server).AuthenticateSSHUser()
      /__w/teleport/teleport/lib/auth/methods.go:567 +0x1f0
  github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).AuthenticateSSHUser()
      /__w/teleport/teleport/lib/auth/auth_with_roles.go:577 +0x2c7
  github.com/gravitational/teleport/lib/auth.(*APIServer).authenticateSSHUser()
      /__w/teleport/teleport/lib/auth/apiserver.go:495 +0x3ef
  github.com/gravitational/teleport/lib/auth.(*APIServer).authenticateSSHUser-fm()
      <autogenerated>:1 +0xeb
  github.com/gravitational/teleport/lib/auth.(*APIServer).WithAuth.func1()
      /__w/teleport/teleport/lib/auth/apiserver.go:204 +0x5d3
  github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:109 +0xad
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf88
  github.com/gravitational/teleport/lib/httplib.RewritePaths.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:237 +0x1e5
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2122 +0x4d
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:663 +0x5d6
  github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 +0x2f8
  github.com/gravitational/teleport/lib/limiter.(*RateLimiter).ServeHTTP()
      <autogenerated>:1 +0x6e
  github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 +0x48d
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      <autogenerated>:1 +0x84
  github.com/gravitational/teleport/lib/httplib.MakeSecurityHeaderHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:69 +0x75
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2122 +0x4d
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:94 +0x2d8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2122 +0x4d
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.40.0/handler.go:213 +0x1b52
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:2936 +0x682
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:[1995](https://github.com/gravitational/teleport/actions/runs/4500917721/jobs/7920658061?pr=23228#step:6:1996) +0xbd4
  net/http.(*Server).Serve.func3()
      /opt/go/src/net/http/server.go:3089 +0x58

Goroutine 39085 (running) created at:
  github.com/gravitational/teleport/lib/auth.TestServer_Authenticate_headless.func1()
      /__w/teleport/teleport/lib/auth/auth_login_test.go:715 +0x224
  github.com/gravitational/teleport/lib/auth.TestServer_Authenticate_headless.func7()
      /__w/teleport/teleport/lib/auth/auth_login_test.go:808 +0x862
  testing.tRunner()
      /opt/go/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1629 +0x47

Goroutine 39078 (running) created at:
  net/http.(*Server).Serve()
      /opt/go/src/net/http/server.go:3089 +0x817
  github.com/gravitational/teleport/lib/auth.(*TLSServer).Serve.func2()
      /__w/teleport/teleport/lib/auth/middleware.go:263 +0xaa
```

### PR DESCRIPTION
**Pull request by Joerger**
Avoid race condition on `headlessAuthentication.Metadata.Expires` when using in-memory storage.

Closes https://github.com/gravitational/teleport/issues/23505

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by timothyb89 — APPROVED** [review]

**Comment by Joerger** [comment]
@zmb3 @timothyb89 I found that my initial changes could still rarely result in the race condition. I've removed the race condition by no longer copying `item.Expires` to `headlessAuthn.Metada.Expires` on unmarshal.

File: lib/auth/auth_login_test.go [hunk 1]
```diff
@@ -772,39 +780,27 @@ func TestServer_Authenticate_headless(t *testing.T) {
 		},
 	} {
 		t.Run(tc.name, func(t *testing.T) {
-			tc := tc
-			t.Parallel()
```
Comment (zmb3) [inline lib/auth/auth_login_test.go:776]: Why was the parallel removed?

Comment (Joerger) [reply lib/auth/auth_login_test.go]: I thought it improved the speed but on re-testing I was mistaken. I've added it back.
