### PR TITLE
Dynamo-Athena migration - handle empty checkpoint file gracefully

### LINKED ISSUE #57670: DynamoDB to Athena migration fails with "Not enough checkpoints from workers"
### Bug details:

When running the dynamo athena migration tool, it completes the export successfully and then immediately errors out:

```
2025-08-04T15:20:47.754Z WARN  Not enough checkpoints from workers checkpoints_received:0 checkpoints_expected:5 dynamoathenamigration/migration.go:874
2025-08-04T15:20:47.754Z ERRO  migration failed error:[
ERROR REPORT:
Original Error: *json.SyntaxError unexpected end of JSON input
Stack Trace:
        /root/teleport/examples/dynamoathenamigration/migration.go:779 github.com/gravitational/teleport/examples/dynamoathenamigration.(*task).loadEmitterCheckpoint
        /root/teleport/examples/dynamoathenamigration/migration.go:364 github.com/gravitational/teleport/examples/dynamoathenamigration.(*task).getEventsFromDataFiles
        /root/teleport/examples/dynamoathenamigration/migration.go:256 github.com/gravitational/teleport/examples/dynamoathenamigration.(*task).ProcessDataObjects.func1
        /root/go/pkg/mod/golang.org/x/sync@v0.16.0/errgroup/errgroup.go:93 golang.org/x/sync/errgroup.(*Group).Go.func1
        /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.5.linux-amd64/src/runtime/asm_amd64.s:1700 runtime.goexit
User Message: unexpected end of JSON input] cmd/main.go:109
```

The same error appears whether the checkpoint is done during this tool's invocation, or whether an existing export arn is provided.

We tried a version from last November, and it worked correctly. That _working_ commit is https://github.com/gravitational/teleport/commit/bcbfa8192e4c60c33599fb7e38016804d26f958d. We didn't narrow it down further, but I suspect either #51448 or #55881 may have introduced the breaking change.

#### Teleport version

Dynamo Athena Migration tool (current master branch version as of time of writing)

https://github.com/gravitational/teleport/tree/7541d6d7d06e7a03ce12b52c6cda584eeb133d2b/examples/dynamoathenamigration

### PR DESCRIPTION
**Pull request by Joerger**
The error reported below was caused by an empty checkpoint file getting read and failing to unmarshal. This empty checkpoint file seems to have been generated after a run that failed with an OOM error.

This PR updates the tool to prompt for restart with it fails to load a checkpoint file, rather than erroring out with a non descriptive error.

Further improvements can be made to handle checkpoint issues and prompts at the start of the tool, but this tool is rarely used and does not warrant further optimizations and UX improvements.

Closes https://github.com/gravitational/teleport/issues/57670

### CODE REVIEW

**Comment by Joerger** [comment]
@flyinghermit @strideynet Very small fix when you get a chance to look

File: examples/dynamoathenamigration/migration.go [hunk 1]
```diff
@@ -361,9 +362,15 @@ func (t *task) getDataObjectsInfo(ctx context.Context, manifestPath string) ([]d
 }
 
 func (t *task) getEventsFromDataFiles(ctx context.Context, exportInfo *exportInfo, eventsC chan<- apievents.AuditEvent) error {
+	// TODO(Joerger): Rather than loading the checkpoint and prompting the user after completing the export step,
+	// this should be done at the beginning of program execution.
 	checkpoint, err := t.loadEmitterCheckpoint(ctx, exportInfo.ExportARN)
 	if err != nil {
-		return trace.Wrap(err)
+		t.Logger.InfoContext(ctx, "Failed to load checkpoint file from previous migration attempt", "file", t.CheckpointPath, "error", err)
+		_, err := prompt.Confirmation(ctx, os.Stdout, prompt.Stdin(), fmt.Sprintf("It seems that a previous migration %s stopped with error and there was an issue resuming it. Would you like to start a new migration?", exportInfo.ExportARN))
```
Comment (flyinghermit) [inline examples/dynamoathenamigration/migration.go:370]: Should we mention error message in this prompt? So that the user have more informed knowledge on the previous failure before starting a new migration.

Comment (Joerger) [reply examples/dynamoathenamigration/migration.go:370]: I didn't want to overcrowd the prompt, so I moved the error message into it's own INFO log, which is the default log level of this tool.

**Review by flyinghermit — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
