### PR TITLE
Fix cleanup of unused GCP KMS keys

### LINKED ISSUE #31375: GCP KMS "cannot find currently active CA key"
When setting up GCP KMS, there is a WARN level message that appears in the logs:

```console
teleport-auth-545565478c-zck5r teleport 2023-09-01T18:26:34Z WARN [AUTH]      Failed attempt to delete unused HSM keys error:[
teleport-auth-545565478c-zck5r teleport ERROR REPORT:
teleport-auth-545565478c-zck5r teleport Original Error: *trace.NotFoundError cannot find currently active CA key in &#34;projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/6e847a9d-1187-4eca-8fb5-b9ad236352e5/cryptoKeyVersions/1&#34; GCP KMS, aborting attempt to delete unused keys
teleport-auth-545565478c-zck5r teleport Stack Trace:
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/lib/auth/keystore/gcp_kms.go:276 github.com/gravitational/teleport/lib/auth/keystore.(*gcpKMSKeyStore).DeleteUnusedKeys
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/lib/auth/init.go:560 github.com/gravitational/teleport/lib/auth.initCluster
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/lib/auth/init.go:288 github.com/gravitational/teleport/lib/auth.Init.func1
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/lib/backend/helpers.go:220 github.com/gravitational/teleport/lib/backend.RunWhileLocked
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/lib/auth/init.go:279 github.com/gravitational/teleport/lib/auth.Init
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/lib/service/service.go:1682 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/lib/service/service.go:1086 github.com/gravitational/teleport/lib/service.NewTeleport
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/e/tool/teleport/process/process.go:57 github.com/gravitational/teleport/e/tool/teleport/process.NewTeleport
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/lib/service/service.go:686 github.com/gravitational/teleport/lib/service.Run
teleport-auth-545565478c-zck5r teleport 	github.com/gravitational/teleport/e/tool/teleport/main.go:28 main.main
teleport-auth-545565478c-zck5r teleport 	runtime/proc.go:250 runtime.main
teleport-auth-545565478c-zck5r teleport 	runtime/asm_amd64.s:1598 runtime.goexit
teleport-auth-545565478c-zck5r teleport User Message: cannot find currently active CA key in &#34;projects/projec-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/6e847a9d-1187-4eca-8fb5-b9ad236352e5/cryptoKeyVersions/1&#34; GCP KMS, aborting attempt to delete unused keys] auth/init.go:564
```

The [code that throws this message](https://github.com/gravitational/teleport/blob/v13.3.7/lib/auth/keystore/gcp_kms.go#L273-L281) has a comment that says that this means the cluster is "in a bad state". The comment for the function where this code is called makes reference to the HostUUID. This make it seem like the current host uuid didn't match the uuid in the message. This prompted some troubleshooting effort to figure out what was really going on and what all the IDs in the keyring really mean.

At minimum, this error handling should be refined so it is more clear that it isn't really a problem. The only consequence is that this auth server isn't going to do any cleanup. The "bad state" comment in the code also gives off the wrong impression.

A more clear wording for this message might be something softer like "skipping cleanup of key abc123 because it was not created by this auth server.  Continuing..."

A complete stacktrace for a WARN condition could also be dropped. I'm also a fan of writing a WARN message, and then a DEBUG stacktrace for the same event.

---

I do wonder whether the intended cleanup here is actually working. After performing the ["less downtime" steps](https://goteleport.com/docs/choose-an-edition/teleport-enterprise/gcp-kms/#migrating-an-existing-cluster) on my gcp teleport-cluster helm release, I see two sets of keys-- presumably due to two full CA rotations. After looking through the code while researching this error, I do wonder whether the `DeleteUnusedKeys` function should have actually deleted the old keys instead of logging this error.

<details>
<summary>List of keys after my second CA rotate</summary>

```console
% gcloud kms keys list --location us-east2 --keyring "jeff-teleport-keyring"
NAME                                                                                                                                    PURPOSE          ALGORITHM                   PROTECTION_LEVEL  LABELS                                                   PRIMARY_ID  PRIMARY_STATE
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/0e78a774-36a0-48a0-8ff7-e214158a061f  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_4096_SHA512  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/273f4250-794a-403d-9f1d-ac7d6b2581d0  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/353f85e1-1235-4dc5-b60a-0888600b12e2  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/36cbe918-882e-4c34-930d-cc7fb58d0b40  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/3f5e121c-bf37-48fe-a403-5973570e2ab7  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/4f99d1d5-d1e4-49cc-b901-75bb970a7682  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/561d6911-5ff5-4232-96a6-326b057eb492  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/6a7014de-251a-4074-a39a-72ebde1472b5  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_4096_SHA512  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/6b8dc77e-945d-4ca3-b9ef-d0164b5b3525  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_4096_SHA512  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/6e847a9d-1187-4eca-8fb5-b9ad236352e5  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/823529ec-4d5a-4514-9327-4beb8edaf0b2  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/8cbf5a79-42c7-4460-823f-2c2ba2659fdb  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_4096_SHA512  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/92dee8de-f1e2-45a0-99bc-604163477fd5  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/9a8ef144-1ed5-4a57-9f10-51db0f797a96  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_4096_SHA512  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/9d755a45-7c0f-44d4-abe9-da5f1d9ad935  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/a997fc64-1dfb-4caa-887f-10ff90bfa419  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/bd40d8d2-f8a5-4d78-8edf-d4b5df057d5a  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_2048_SHA256  SOFTWARE          teleport_auth_host=37715be3-76d6-4a23-9d27-9000f6b9bfee
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/dad5ea62-8a2f-46ba-a852-2ef89e164cbf  ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_4096_SHA512  SOFTWARE          teleport_auth_host=a0eb7107-18bb-42ef-bfde-5c96d03ce939
projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/test-key                              ASYMMETRIC_SIGN  RSA_SIGN_PKCS1_4096_SHA512  SOFTWARE
```

```console
% kubectl -n teleport exec deployments/teleport-auth -- tctl get cert_authority --with-secrets | yq -oyaml '.spec.active_keys."*"[0]."*key" | @base64d' | grep gcpkms:
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/dad5ea62-8a2f-46ba-a852-2ef89e164cbf/cryptoKeyVersions/1
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/3f5e121c-bf37-48fe-a403-5973570e2ab7/cryptoKeyVersions/1
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/8cbf5a79-42c7-4460-823f-2c2ba2659fdb/cryptoKeyVersions/1
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/a997fc64-1dfb-4caa-887f-10ff90bfa419/cryptoKeyVersions/1
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/273f4250-794a-403d-9f1d-ac7d6b2581d0/cryptoKeyVersions/1
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/6b8dc77e-945d-4ca3-b9ef-d0164b5b3525/cryptoKeyVersions/1
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/4f99d1d5-d1e4-49cc-b901-75bb970a7682/cryptoKeyVersions/1
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/6e847a9d-1187-4eca-8fb5-b9ad236352e5/cryptoKeyVersions/1
gcpkms:projects/project-1234/locations/us-east2/keyRings/jeff-teleport-keyring/cryptoKeys/92dee8de-f1e2-45a0-99bc-604163477fd5/cryptoKeyVersions/1
```

</details>

---

**Current Behavior:** big warn level stacktrace that made it seem like bad things were afoot

**Expected Behavior:**  softer and more clear warn message

**Teleport Version:** reported by a customer on 12.4.x, and recreated by myself on 13.3.7

### PR DESCRIPTION
**Pull request by nklaassen**
Fixes https://github.com/gravitational/teleport/issues/31375

This PR fixes the cleanup code for unused keys in GCP KMS which is currently failing to delete unused keys and emitting confusing warning logs whenever keys have been generated by multiple different Auth servers (no actual functionality is currently broken).

This bug was introduced in https://github.com/gravitational/teleport/pull/25025. This issue introduced there is that the function now checks that all currently active keys have actually been found in the keyring, but the ListCryptoKeys call used a filter that excluded all keys created by different Auth servers.

This fix improves some of the error messages, and also uses a more permissive filter in the ListCryptoKeys call to make sure we can list keys created by any auth server, but will only delete keys created by the local auth server.

changelog: Fix cleanup of unused GCP KMS keys

### CODE REVIEW

File: lib/auth/keystore/gcp_kms.go [hunk 1]
```diff
@@ -228,65 +228,96 @@ func (g *gcpKMSKeyStore) canSignWithKey(ctx context.Context, raw []byte, keyType
...
 
-	var unusedKeyIDs []gcpKMSKeyID
+	var keysToDelete []gcpKMSKeyID
 
 	listKeyRequest := &kmspb.ListCryptoKeysRequest{
 		Parent: g.keyRing,
-		Filter: fmt.Sprintf("labels.%s=%s", hostLabel, g.hostUUID),
+		// Only bother listing keys created by Teleport which should have the
+		// hostLabel set
+		Filter: fmt.Sprintf("labels.%s:*", hostLabel),
```
Comment (greedy52) [inline lib/auth/keystore/gcp_kms.go:277]: nit. 
```suggestion
		// Only bother listing keys created by Teleport which should have the
		// hostLabel set.
		Filter: fmt.Sprintf("labels.%s:*", hostLabel),
```
Also assuming `:*` checks if a key is defined?

File: lib/auth/keystore/gcp_kms.go [hunk 2]
```diff
@@ -228,65 +228,96 @@ func (g *gcpKMSKeyStore) canSignWithKey(ctx context.Context, raw []byte, keyType
...
 	if err != nil && !errors.Is(err, iterator.Done) {
-		return trace.Wrap(err)
+		return trace.Wrap(err, "unexpected error while iterating GCP KMS keys")
 	}
 
+	// If any member of activeKeys which is part of the same GCP KMS keyring
+	// queried here was not found in the ListCryptoKeys response, something has
+	// gone wrong and there's a chance we have a bug or GCP has made a breaking
+	// API change. In this case we should abort to avoid the chance of deleting
+	// any currently active keys.
```
Comment (greedy52) [inline lib/auth/keystore/gcp_kms.go:305]: should we continue deleting unused keys? 

or is it possible to filter activeKeys by current hostUUID?

File: lib/auth/keystore/gcp_kms_test.go [hunk 3]
```diff
@@ -593,3 +589,155 @@ func TestGCPKMSKeystore(t *testing.T) {
...
+			expectDestroyed: []keySpec{
+				{keyring: localKeyring, id: "id_inactive_local", host: localHostID},
+			},
+		},
+		{
+			// The presence of active keys created by a remote host in the local
+			// keyring should not break the DeleteUnusedKeys operation.
+			desc: "active key from other host",
+			existingKeys: []keySpec{
+				{keyring: localKeyring, id: "id_local_active", host: localHostID},
```
Comment (greedy52) [inline lib/auth/keystore/gcp_kms_test.go:643]: nit: just to be consistent

```suggestion
				{keyring: localKeyring, id: "id_active_local", host: localHostID},
```

**Review by greedy52 — APPROVED** [review]

File: lib/auth/keystore/gcp_kms.go (hunk 2 above)
Comment (nklaassen) [reply lib/auth/keystore/gcp_kms.go:305]: Hmm I don't quite see what you're getting at here, can you elaborate? One piece of info I can offer is that we have no record of the hostUUID which created the key on the Teleport side, it's only stored as a label on the key in GCP

Comment (greedy52) [reply lib/auth/keystore/gcp_kms.go:308]: Was thinking weird situations where an active key is not found in keyring, and it's not owned by this Auth. But reading the comment again `found == 0` only happens when something horribly went wrong? just ignore my previous comment =p

File: lib/auth/keystore/gcp_kms.go [hunk 4]
```diff
@@ -228,65 +228,99 @@ func (g *gcpKMSKeyStore) canSignWithKey(ctx context.Context, raw []byte, keyType
...
+//
+// The reason this does not delete any keys created by a different auth server
+// is to avoid a case where:
+// 1. A different auth server (auth2) creates a new key in GCP KMS
+// 2. This function (running on auth1) deletes that new key
+// 3. auth2 saves the id of this deleted key to the backend CA
+//
+// or a simpler case where: the other auth server is running in a completely
+// different Teleport cluster and the keys it's actively using will never appear
+// in the activeKeys argument
```
Comment (codingllama) [inline lib/auth/keystore/gcp_kms.go:247]: nit:

```suggestion
// in the activeKeys argument.
```

File: lib/auth/keystore/gcp_kms.go [hunk 5]
```diff
@@ -228,65 +228,99 @@ func (g *gcpKMSKeyStore) canSignWithKey(ctx context.Context, raw []byte, keyType
...
-	// they are found in KMS. If any active keys are not found in KMS, we are in
-	// a bad state, so key deletion will be aborted.
+	// check which keys in KMS are unused.
 	activeKmsKeyVersions := make(map[string]int)
 	for _, activeKey := range activeKeys {
-		keyID, err := parseGCPKMSKeyID(activeKey)
+		keyIsRelevant, err := g.canSignWithKey(ctx, activeKey, keyType(activeKey))
 		if err != nil {
-			// could be a different type of key
+			return trace.Wrap(err)
```
Comment (codingllama) [inline lib/auth/keystore/gcp_kms.go:255]: Should this log and continue? In what scenarios are we expected to hit this error?

File: lib/auth/keystore/gcp_kms.go [hunk 6]
```diff
@@ -228,65 +228,99 @@ func (g *gcpKMSKeyStore) canSignWithKey(ctx context.Context, raw []byte, keyType
...
+		if !keyIsRelevant {
+			// Ignore active keys that are not GCP KMS keys or are in a
+			// different keyring than the one this Auth is configured to use.
 			continue
 		}
+		keyID, err := parseGCPKMSKeyID(activeKey)
+		if err != nil {
+			// Realistically we should not hit this since canSignWithKey already
+			// calls parseGCPKMSKeyID.
+			return trace.Wrap(err)
```
Comment (codingllama) [inline lib/auth/keystore/gcp_kms.go:266]:
```suggestion
			return trace.Wrap(err, "parsing GCP KMS key failed unexpectedly")
```

File: lib/auth/keystore/gcp_kms.go [hunk 7]
```diff
@@ -228,65 +228,99 @@ func (g *gcpKMSKeyStore) canSignWithKey(ctx context.Context, raw []byte, keyType
...
+	var keysToDelete []gcpKMSKeyID
 
 	listKeyRequest := &kmspb.ListCryptoKeysRequest{
 		Parent: g.keyRing,
-		Filter: fmt.Sprintf("labels.%s=%s", hostLabel, g.hostUUID),
+		// Only bother listing keys created by Teleport which should have the
+		// hostLabel set. A filter of "labels.label:*" tests if the label is
+		// defined.
+		// https://cloud.google.com/sdk/gcloud/reference/topic/filters
+		// > Use key:* to test if key is defined
```
Comment (codingllama) [inline lib/auth/keystore/gcp_kms.go:279]: Maybe?

```suggestion
		// defined. Use key:* to test if key is defined.
		//
		// See https://cloud.google.com/sdk/gcloud/reference/topic/filters.
```

File: lib/auth/keystore/gcp_kms.go [hunk 8]
```diff
@@ -228,65 +228,99 @@ func (g *gcpKMSKeyStore) canSignWithKey(ctx context.Context, raw []byte, keyType
...
 	iter := g.kmsClient.ListCryptoKeys(ctx, listKeyRequest)
 	key, err := iter.Next()
 	for err == nil {
 		keyVersionName := key.Name + keyVersionSuffix
-		if _, active := activeKmsKeyVersions[keyVersionName]; active {
-			activeKmsKeyVersions[keyVersionName]++
-		} else {
-			unusedKeyIDs = append(unusedKeyIDs, gcpKMSKeyID{
+		_, keyIsActive := activeKmsKeyVersions[keyVersionName]
+		if keyIsActive {
```
Comment (codingllama) [inline lib/auth/keystore/gcp_kms.go:287]: nit: use smaller scope:

```suggestion	
		if _, active := activeKmsKeyVersions[keyVersionName]; active {
```

File: lib/auth/keystore/gcp_kms_test.go [hunk 9]
```diff
@@ -593,3 +589,155 @@ func TestGCPKMSKeystore(t *testing.T) {
...
+
+func TestGCPKMSDeleteUnusedKeys(t *testing.T) {
+	t.Parallel()
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	localHostID := "local-host-id"
+	otherHostID := "other-host-id"
+	localKeyring := "local-keyring"
+	otherKeyring := "other-keyring"
```
Comment (codingllama) [inline lib/auth/keystore/gcp_kms_test.go:601]:
```suggestion
	const localHostID = "local-host-id"
	const otherHostID = "other-host-id"
	const localKeyring = "local-keyring"
	const otherKeyring = "other-keyring"
```

**Review by codingllama — COMMENTED** [review]
Only minor comments, looks good.

**Review by zmb3 — APPROVED** [review]
