### PR TITLE
Paginate on capacity throttling, fixes #2576

### LINKED ISSUE #2576: List clusters doesn't work after DynamoDB capacity throttle
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
DynamoDB throthle event happen (now everything is under the limits) and since that time I'm not able to list clusters in UI and through `tsh clusters` (timeout)
`tctl get rc` returns 374 remote clusters

**What you expected to happen**:
Listing clusters should work

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Teleport version (use `teleport version`): v2.7.4
- Tsh version (use `tsh version`): v2.7.4
- OS (e.g. from /etc/os-release): Ubuntu 18.04

**Browser environment**

- Browser Version (for UI-related issues): Firefox 65.0.1  
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**
Teleport logs (i've remove some parts)
```
+ teleport start --insecure-no-tls --config=/etc/teleport.yml
+ /sbin/syslogd -n -O /dev/stdout
Feb 22 07:51:07 teleport-prd02-5955464986-2d4w8 syslog.info syslogd started: BusyBox v1.22.1
INFO [PROC]      Generating new host UUID: 2228f687-03a7-45da-86e3-46093ddbaf57. service/service.go:505
DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/proc dir/migrate.go:42
DEBU [KEYGEN]    SSH cert authority is going to pre-compute 25 keys. native/native.go:90
DEBU [PROC:1]    Using dynamodb backend. service/service.go:1837
INFO [DYNAMODB]  Initializing backend. dynamo/dynamodbbk.go:130
DEBU [DYNAMODB]  AWS session is created. dynamo/dynamodbbk.go:203
INFO [AUTH]      Auth server is running periodic operations. auth/auth.go:109
DEBU [AUTH]      Ticking with period: 12s. auth/auth.go:166
DEBU [AUTH]      Cluster configuration: ClusterName(Test). auth/init.go:215
INFO [AUTH]      Updating cluster configuration: StaticTokens([ProvisionToken(Token=411ec733fd7988b4388c01c381db6e26ba3bd0311a646b6681c52f545541951a,Roles=Trusted_cluster,Expires=never)]). auth/init.go:221
INFO [AUTH]      Updating cluster configuration: AuthPreference(Type="local",SecondFactor="otp"). auth/init.go:230
INFO [AUTH]      Created namespace: "default". auth/init.go:237
DEBU [AUTH]      Migrations: skipping local cluster cert authority "Test". auth/init.go:784
DEBU [AUTH]      Migrations: remote cluster already exists for cert authority "be-xxx.xxx.xxx.com-nrc-f44d30606850-01664". auth/init.go:790
DEBU [AUTH]      Migrations: remote cluster already exists for cert authority "undefined-nrc-000babd52f24". auth/init.go:790
DEBU [AUTH]      Migrations: remote cluster already exists for cert authority "undefined-nrc-000babe081f4". auth/init.go:790
DEBU [AUTH]      Migrations: remote cluster already exists for cert authority "undefined-nrc-000babe3b617". auth/init.go:790
DEBU [AUTH]      Migrations: remote cluster already exists for cert authority "undefined-nrc-f44d306f50b4". auth/init.go:790
DEBU [AUTH]      Migrations: remote cluster already exists for cert authority "undefined-nrc-f44d306f5309". auth/init.go:790
DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/proc dir/migrate.go:42
DEBU [PROC:1]    This server has local Auth server started, using it to add role to the cluster. service/connect.go:173
INFO [CA]        Generating TLS certificate. common_name:2228f687-03a7-45da-86e3-46093ddbaf57.Test dns_names:[XXXX.com XXXX.cluster.local] not_after:2029-02-19 07:51:19.027493145 +0000 UTC org:[Admin] tlsca/ca.go:160
INFO [PROC]      Admin has successfully registered with the cluster. service/connect.go:187
INFO [PROC:1]    The process has successfully wrote credentials and state of Admin to disk. service/connect.go:230
DEBU [PROC:1]    Connected client: Identity(Admin, cert(2228f687-03a7-45da-86e3-46093ddbaf57.Test issued by Test:226995491359536494171913255815216693294),trust root(Test:226995491359536494171913255815216693294)) service/connect.go:21
DEBU [PROC:1]    Connected server: Identity(Admin, cert(2228f687-03a7-45da-86e3-46093ddbaf57.Test issued by Test:226995491359536494171913255815216693294),trust root(Test:226995491359536494171913255815216693294)) service/connect.go:21
DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/cache/auth dir/migrate.go:42
DEBU [PRESENCE]  GetServers(0) in 3.237153ms. local/presence.go:196
DEBU [PRESENCE]  UpsertNodes(0) in 44.718µs local/presence.go:244
INFO [PROC:1]    Service auth is creating new listener on 0.0.0.0:3025. service/signals.go:210
INFO [AUTH:1]    Starting Auth service with PROXY protocol support. service/service.go:968
DEBU [PROC]      Adding service to supervisor. service:auth.tls service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:auth.heartbeat.broadcast service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:auth.heartbeat service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:auth.shutdown service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:register.proxy service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:auth.client service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:proxy.init service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:common.rotate service/supervisor.go:175
DEBU [PROC:1]    Service has started. service:proxy.init service/supervisor.go:220
DEBU [PROC:1]    Service has started. service:auth.client service/supervisor.go:220
DEBU [PROC:1]    Service has started. service:common.rotate service/supervisor.go:220
DEBU [PROC:1]    Service has started. service:auth.heartbeat service/supervisor.go:220
DEBU [PROC:1]    Service has started. service:auth.heartbeat.broadcast service/supervisor.go:220
WARN [AUTH:1]    Configuration setting auth_service/advertise_ip is not set. guessing 100.98.246.11:3025. service/service.go:1025
DEBU [PROC:1]    Connected state: never updated. service/connect.go:36
DEBU [PROC:1]    Service has started. service:auth.tls service/supervisor.go:220
INFO [AUTH]      Auth service is starting on 0.0.0.0:3025. utils/cli.go:157
[AUTH]    Auth service is starting on 0.0.0.0:3025.
DEBU [PROC:1]    Connected client: Identity(Admin, cert(2228f687-03a7-45da-86e3-46093ddbaf57.Test issued by Test:226995491359536494171913255815216693294),trust root(Test:226995491359536494171913255815216693294)) service/connect.go:21
DEBU [PROC:1]    Broadcasting event. event:AuthTLSReady service/supervisor.go:300
DEBU [PROC:1]    Service has started. service:auth.shutdown service/supervisor.go:220
DEBU [PROC:1]    Connected server: Identity(Admin, cert(2228f687-03a7-45da-86e3-46093ddbaf57.Test issued by Test:226995491359536494171913255815216693294),trust root(Test:226995491359536494171913255815216693294)) service/connect.go:21
DEBU [PROC:1]    Broadcasting event. event:AuthIdentity service/supervisor.go:300
DEBU [PROC]      Adding service to supervisor. service:auth.broadcast service/supervisor.go:175
DEBU [PROC:1]    Service has started. service:register.proxy service/supervisor.go:220
DEBU [PROC:1]    Service is completed and removed. service:auth.heartbeat.broadcast service/supervisor.go:207
DEBU [PROC:1]    Service has started. service:auth.broadcast service/supervisor.go:220
DEBU [PROC:1]    This server has local Auth server started, using it to add role to the cluster. service/connect.go:173
INFO [CA]        Generating TLS certificate. common_name:2228f687-03a7-45da-86e3-46093ddbaf57.Test dns_names:[XXX.com] not_after:2029-02-19 07:51:45.337800223 +0000 UTC org:[Proxy] tlsca/ca.go:160
INFO [PROC]      Proxy has successfully registered with the cluster. service/connect.go:187
INFO [PROC:1]    The process has successfully wrote credentials and state of Proxy to disk. service/connect.go:230
DEBU [PROC:1]    Connected client: Identity(Proxy, cert(2228f687-03a7-45da-86e3-46093ddbaf57.Test issued by Test:226995491359536494171913255815216693294),trust root(Test:226995491359536494171913255815216693294)) service/connect.go:21
DEBU [PROC:1]    Connected server: Identity(Proxy, cert(2228f687-03a7-45da-86e3-46093ddbaf57.Test issued by Test:226995491359536494171913255815216693294),trust root(Test:226995491359536494171913255815216693294)) service/connect.go:21
DEBU [PROC:1]    Broadcasting event. event:ProxyIdentity service/supervisor.go:300
DEBU [PROC:1]    Service is completed and removed. service:register.proxy service/supervisor.go:207
DEBU [PROC:1]    Received event "ProxyIdentity". service/service.go:1488
DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/cache/proxy dir/migrate.go:42
DEBU [PRESENCE]  GetServers(0) in 3.011611ms. local/presence.go:196
DEBU [PRESENCE]  UpsertNodes(0) in 41.642µs local/presence.go:244
DEBU [PROC:1]    Setup Proxy: Web Proxy Address: 0.0.0.0:3080, Reverse Tunnel Proxy Address: 0.0.0.0:3024 service/service.go:1524
DEBU [PROC:1]    Proxy reverse tunnel are listening on the separate ports. service/service.go:1579
INFO [PROC:1]    Service proxy:tunnel is creating new listener on 0.0.0.0:3024. service/signals.go:210
INFO [PROC:1]    Service proxy:web is creating new listener on 0.0.0.0:3080. service/signals.go:210
DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/cache/reverse/Test dir/migrate.go:42
DEBU [PRESENCE]  GetServers(0) in 3.183113ms. local/presence.go:196
DEBU [PRESENCE]  UpsertNodes(0) in 47.974µs local/presence.go:244
DEBU [SSH:PROXY] Supported ciphers: ["aes128-gcm@openssh.com" "chacha20-poly1305@openssh.com" "aes128-ctr" "aes192-ctr" "aes256-ctr"]. sshutils/server.go:184
DEBU [SSH:PROXY] Supported KEX algorithms: ["curve25519-sha256@libssh.org" "ecdh-sha2-nistp256" "ecdh-sha2-nistp384" "ecdh-sha2-nistp521"]. sshutils/server.go:194
DEBU [SSH:PROXY] Supported MAC algorithms: ["hmac-sha2-256-etm@openssh.com" "hmac-sha2-256"]. sshutils/server.go:204
DEBU [PROC]      Adding service to supervisor. service:proxy.reveresetunnel.server service/supervisor.go:175
DEBU [PROC:1]    Service has started. service:proxy.reveresetunnel.server service/supervisor.go:220
INFO [PROXY]     Reverse tunnel service is starting on 0.0.0.0:3024. utils/cli.go:157
[PROXY]   Reverse tunnel service is starting on 0.0.0.0:3024.
INFO [PROXY:SER] Starting on 0.0.0.0:3024 using cache that will expire after connection to database is lost after 20h0m0s, will cache frequently accessed items for 2s service/service.go:1679
DEBU [PROC:1]    Broadcasting event. event:ProxyReverseTunnelReady service/supervisor.go:300
DEBU [SSH:PROXY] Listening on [::]:3024. sshutils/server.go:318
DEBU             [web] GET zip:/index.html web/static.go:196
DEBU             [web] zip::Close(index.html) web/static.go:189
DEBU [PROC]      Adding service to supervisor. service:proxy.web service/supervisor.go:175
INFO [PROC:1]    Service proxy:ssh is creating new listener on 0.0.0.0:3023. service/signals.go:210
DEBU [PROC:1]    Service has started. service:proxy.web service/supervisor.go:220
INFO [PROXY]     Web proxy service is starting on 0.0.0.0:3080. utils/cli.go:157
[PROXY]   Web proxy service is starting on 0.0.0.0:3080.
INFO [PROXY:SER] Web proxy service is starting on 0.0.0.0:3080. service/service.go:1723
DEBU [PROC:1]    Broadcasting event. event:ProxyWebServerReady service/supervisor.go:300
DEBU [SSH:PROXY] Supported ciphers: ["aes128-gcm@openssh.com" "chacha20-poly1305@openssh.com" "aes128-ctr" "aes192-ctr" "aes256-ctr"]. sshutils/server.go:184
DEBU [SSH:PROXY] Supported KEX algorithms: ["curve25519-sha256@libssh.org" "ecdh-sha2-nistp256" "ecdh-sha2-nistp384" "ecdh-sha2-nistp521"]. sshutils/server.go:194
DEBU [SSH:PROXY] Supported MAC algorithms: ["hmac-sha2-256-etm@openssh.com" "hmac-sha2-256"]. sshutils/server.go:204
DEBU [PROC]      Adding service to supervisor. service:proxy.ssh service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:proxy.reversetunnel.agent service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:proxy.shutdown service/supervisor.go:175
INFO [AUDIT:1]   Creating directory /var/lib/teleport/log. service/service.go:1335
INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload. service/service.go:1335
INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/sessions. service/service.go:1335
INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/sessions/default. service/service.go:1335
DEBU [PROC]      Adding service to supervisor. service:uploader.service service/supervisor.go:175
DEBU [PROC]      Adding service to supervisor. service:uploader.shutdown service/supervisor.go:175
DEBU [PROC:1]    Service is completed and removed. service:proxy.init service/supervisor.go:207
DEBU [PROC:1]    Service has started. service:uploader.shutdown service/supervisor.go:220
DEBU [PROC:1]    Service has started. service:proxy.ssh service/supervisor.go:220
INFO [PROXY]     SSH proxy service is starting on 0.0.0.0:3023. utils/cli.go:157
[PROXY]   SSH proxy service is starting on 0.0.0.0:3023.
INFO [PROXY:SER] SSH proxy service is starting on 0.0.0.0:3023 service/service.go:1764
DEBU [PROC:1]    Broadcasting event. event:ProxySSHReady service/supervisor.go:300
DEBU [PROC:1]    Broadcasting mapped event. in:ProxySSHReady out:EventMapping(in=[AuthTLSReady ProxySSHReady], out=TeleportReady) service/supervisor.go:311
INFO [PROC:1]    The new service has started successfully. Starting syncing rotation status with period 10s. service/connect.go:241
DEBU [PROC:1]    Service has started. service:proxy.reversetunnel.agent service/supervisor.go:220
INFO [PROXY:AGE] Starting reverse tunnel agent pool. service/service.go:1775
DEBU [PROC:1]    Broadcasting event. event:ProxyAgentPoolReady service/supervisor.go:300
DEBU [PROC:1]    Service has started. service:proxy.shutdown service/supervisor.go:220
DEBU [PROC:1]    Service has started. service:uploader.service service/supervisor.go:220
DEBU [PROC:1]    Service is completed and removed. service:proxy.ssh service/supervisor.go:207
DEBU [SSH:PROXY] Listening on [::]:3023. sshutils/server.go:318
INFO [PROC:1]    New service has started successfully. service/service.go:662
DEBU [PROC:1]    No signal pipe to import, must be first Teleport process. service/signals.go:156
WARN [MX:1]      "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 127.0.0.1:3025->127.0.0.1:57788: i/o timeout\nStack Trace:\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:257 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:2338 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [MX:1]      "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 127.0.0.1:3025->127.0.0.1:57900: i/o timeout\nStack Trace:\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:257 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:2338 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Backoff: using cached value due to recent errors. state/cachingaccesspoint.go:846
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
WARN [CLIENT:CA] Connection problem: failed connect to the auth servers, using local cache. state/cachingaccesspoint.go:860
DEBU [KEYGEN]    generated user key for [Test root] with expiry on (1550867741) 2019-02-22 20:35:41.223840653 +0000 UTC m=+45873.281739479 native/native.go:234
INFO [CA]        Generating TLS certificate. common_name:jabwi dns_names:[] not_after:2019-02-22 20:35:41.626176021 +0000 UTC org:[admin default-implicit-role] tlsca/ca.go:160
INFO             [RBAC] read access to user [namespace default] denied for roles admin,default-implicit-role: no allow rule matched services/role.go:1637
INFO             [RBAC] read access to user [namespace default] denied for roles admin,default-implicit-role: no allow rule matched services/role.go:1637
INFO             [RBAC] read access to user [namespace default] denied for roles admin,default-implicit-role: no allow rule matched services/role.go:1637
INFO             [RBAC] update access to session [namespace default] denied for roles admin,default-implicit-role: no allow rule matched services/role.go:1637
INFO             [RBAC] create access to session [namespace default] denied for roles admin,default-implicit-role: no allow rule matched services/role.go:1637
INFO             [RBAC] delete access to session [namespace default] denied for roles admin,default-implicit-role: no allow rule matched services/role.go:1637
DEBU [PRESENCE]  GetServers(0) in 3.272937ms. local/presence.go:196
DEBU [AUDIT]     SearchSessionEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, 500) events/auditlog.go:885
DEBU [AUDIT]     SearchSessionEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, 500) events/filelog.go:170
DEBU [AUDIT]     SearchEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, query=event=session.start&event=session.end, limit=500) events/filelog.go:127
DEBU [AUDIT]     Called findInFile(/var/lib/teleport/log/2228f687-03a7-45da-86e3-46093ddbaf57/2019-02-22.00:00:00.log, map[event:[session.start session.end]]). events/filelog.go:371
DEBU [PRESENCE]  GetServers(0) in 3.640176ms. local/presence.go:196
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
DEBU [PRESENCE]  GetServers(0) in 55.068031ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.453631ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 88.370665ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 91.559531ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.318459ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 4.051672ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 4.12244ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 43.854625ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.444646ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.033775ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.261906ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 92.997375ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.680393ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.542855ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 2.879067ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 4.258141ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 48.555402ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.714607ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 2.932348ms. local/presence.go:196
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
DEBU [PRESENCE]  GetServers(0) in 85.460013ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 99.137146ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 98.827956ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 11.609104ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 5.840183ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 8.722587ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 4.635622ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 42.413736ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 4.528827ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.746697ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.69076ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.253979ms. local/presence.go:196
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
DEBU [PRESENCE]  GetServers(0) in 802.033303ms. local/presence.go:196
WARN [MX:1]      "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 127.0.0.1:3025->127.0.0.1:57608: i/o timeout\nStack Trace:\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:257 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:2338 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
DEBU [PRESENCE]  GetServers(0) in 820.390118ms. local/presence.go:196
WARN             http: named cookie not present request:GET /web web/apiserver.go:1885
DEBU [PRESENCE]  GetServers(0) in 3.293744ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 23.083869ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 3.257553ms. local/presence.go:196
DEBU [PRESENCE]  GetServers(0) in 5.615175ms. local/presence.go:196
DEBU [AUDIT]     SearchSessionEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, 500) events/auditlog.go:885
DEBU [AUDIT]     SearchSessionEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, 500) events/filelog.go:170
DEBU [AUDIT]     SearchEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, query=event=session.start&event=session.end, limit=500) events/filelog.go:127
DEBU [AUDIT]     Called findInFile(/var/lib/teleport/log/2228f687-03a7-45da-86e3-46093ddbaf57/2019-02-22.00:00:00.log, map[event:[session.start session.end]]). events/filelog.go:371
DEBU [PRESENCE]  GetServers(0) in 96.975218ms. local/presence.go:196
DEBU [AUDIT]     SearchSessionEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, 500) events/auditlog.go:885
DEBU [AUDIT]     SearchSessionEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, 500) events/filelog.go:170
DEBU [AUDIT]     SearchEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, query=event=session.start&event=session.end, limit=500) events/filelog.go:127
DEBU [AUDIT]     Called findInFile(/var/lib/teleport/log/2228f687-03a7-45da-86e3-46093ddbaf57/2019-02-22.00:00:00.log, map[event:[session.start session.end]]). events/filelog.go:371
DEBU [PRESENCE]  GetServers(0) in 3.824081ms. local/presence.go:196
DEBU [AUDIT]     SearchSessionEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, 500) events/auditlog.go:885
DEBU [AUDIT]     SearchSessionEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, 500) events/filelog.go:170
DEBU [AUDIT]     SearchEvents(2019-02-18 23:00:00 +0000 UTC, 2019-02-22 22:59:59 +0000 UTC, query=event=session.start&event=session.end, limit=500) events/filelog.go:127
DEBU [AUDIT]     Called findInFile(/var/lib/teleport/log/2228f687-03a7-45da-86e3-46093ddbaf57/2019-02-22.00:00:00.log, map[event:[session.start session.end]]). events/filelog.go:371
```

### PR DESCRIPTION
**Pull request by klizhentas**
This commit adds pagination for cases when DynamoDB turns on capacity throttling on large result sets.

I'm adding this backport per customer's request experiencing this issue on production.

### CODE REVIEW

File: lib/backend/dynamo/dynamodbbk.go [hunk 1]
```diff
@@ -332,8 +332,35 @@ func (b *DynamoDBBackend) fullPath(bucket ...string) string {
...
+			return nil, trace.Wrap(err)
+		}
+		result.records = append(result.records, re.records...)
+		if len(re.lastEvaluatedKey) == 0 {
+			result.lastEvaluatedKey = nil
+			return result.records, nil
+		}
+		result.lastEvaluatedKey = re.lastEvaluatedKey
+	}
+	return nil, trace.BadParameter("backend entered endless loop")
```
Comment (r0mant) [inline lib/backend/dynamo/dynamodbbk.go]: Have you considered returning whatever's been collected after 100 iterations instead of an error (and logging it too)?

**Review by r0mant — APPROVED** [review]
lgtm

File: lib/backend/dynamo/dynamodbbk.go (hunk 1 above)
Comment (klizhentas) [reply lib/backend/dynamo/dynamodbbk.go]: I think at this point it will be so much data, almost pointless

**Review by russjones — APPROVED** [review]
