### PR TITLE
fix duplicate seek entries.

### LINKED ISSUE #2987: Duplicate proxy entry on blind reverse-tunnel connection.
Minor bug in proxy-discovery algorithm:  Sometimes, when connecting to a previously unknown proxy, the claimed name doesn't match the name used in gossip messages, resulting in duplicate entries.  While this doesn't cause two agents to hold the proxy simultaneously, it does cause periodic attempts to discover a proxy which is already held, resulting in confusing log spam.

### PR DESCRIPTION
**Pull request by fspmarshall**
Preferentially extract and use UUIDs when identifying proxies based on their principals, preventing common issue where entries `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` and `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.clustername` are both created.

Fixes #2987

### CODE REVIEW

File: lib/reversetunnel/seek/seek.go [hunk 1]
```diff
@@ -248,6 +250,10 @@ func (p *proxyGroup) run(ctx context.Context) {
 			if stat.ShouldSeek() {
 				p.notifyShouldSeek()
 			}
+			ticks++
+			if ticks%8 == 0 {
```
Comment (russjones) [inline lib/reversetunnel/seek/seek.go]: What is `ticks%8`?

File: lib/reversetunnel/seek/seek.go [hunk 2]
```diff
@@ -369,13 +375,28 @@ func (p *proxyGroup) releaseProxy(t time.Time, principals ...string) (ok bool) {
 
 func (p *proxyGroup) resolveName(principals []string) string {
 	for _, name := range principals {
+		if len(name) >= 36 {
```
Comment (russjones) [inline lib/reversetunnel/seek/seek.go]: What's the significance of 36?

File: lib/reversetunnel/seek/seek.go (hunk 1 above)
Comment (fspmarshall) [reply lib/reversetunnel/seek/seek.go]: `gofmt` keeps removing the space around the remainder operator.  The above code is limiting log spam by only logging state once every 8 ticks.

File: lib/reversetunnel/seek/seek.go (hunk 2 above)
Comment (fspmarshall) [reply lib/reversetunnel/seek/seek.go]: The `uuid.Parse` function only accepts the hyphenated form of uuid encoding, which is 36 characters.  I'll rework into clearly labeled constant.

File: lib/reversetunnel/seek/seek.go [hunk 3]
```diff
@@ -248,6 +251,10 @@ func (p *proxyGroup) run(ctx context.Context) {
 			if stat.ShouldSeek() {
 				p.notifyShouldSeek()
 			}
+			ticks++
+			if ticks%logInterval == 0 {
+				log.Debugf("SeekStates(states=%+v,id=%s)", p.GetStates(), p.id)
```
Comment (klizhentas) [inline lib/reversetunnel/seek/seek.go]: here you can take advantage of the structured logging, also can you port this to a prometheus gauge instead to report the different states?

Comment (fspmarshall) [reply lib/reversetunnel/seek/seek.go]: Not very familiar with prometheus.  As far as I can tell, it only deals with scalar values.  The value being logged here is effectively a `map[string]string`.  Is there a mechanism I'm missing that is appropriate for this?

Side Note; I can definitely plug the more frequently calculated *summary* values into prometheus.  It won't indicate *which* proxies are in which state, but it will give a nice overview of the *number* of proxies in each state.  Think that would be sufficient?

Comment (klizhentas) [reply lib/reversetunnel/seek/seek.go]: Yes, I think this will be OK

Comment (fspmarshall) [reply lib/reversetunnel/seek/seek.go]: So I added prometheus gauge for the *connected* proxies, but it turns out that complete statistics require rework that I'd prefer to tackle sometime *after* `4.1` release.  Currently, there isn't a good "single source of truth" for most of the process-level stats, and its surprisingly easy to get some of the values wrong.
