### PR TITLE
kube: prevent init failure when proxy listener addr host is unspecified

### LINKED ISSUE #51838: Proxy fails to initialize with `empty hostname`
Expected behavior:

teleport proxy should start when web/kube listener address doesn't specify host.

Current behavior:

When specifying the web listener address without a host, teleport proxy fails to start.

```yaml
proxy_service:
  enabled: "yes"
  web_listen_addr: :443
```

```text
teleport[3055436]: 2025-02-04T09:50:06.510-07:00 WARN [PROC:1] Teleport process has exited with error. error:[
teleport[3055436]: ERROR REPORT:
teleport[3055436]: Original Error: *trace.BadParameterError empty hostname
teleport[3055436]: Stack Trace:
teleport[3055436]: github.com/gravitational/teleport/lib/utils/utils.go:310 github.com/gravitational/teleport/lib/utils.SplitHostPort
teleport[3055436]: github.com/gravitational/teleport/lib/kube/grpc/utils.go:45 github.com/gravitational/teleport/lib/kube/grpc.getWebAddrAndKubeSNI
teleport[3055436]: github.com/gravitational/teleport/lib/kube/grpc/grpc.go:65 github.com/gravitational/teleport/lib/kube/grpc.New
teleport[3055436]: github.com/gravitational/teleport/lib/service/service.go:6832 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initSecureGRPCServer
teleport[3055436]: github.com/gravitational/teleport/lib/service/service.go:5362 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint
teleport[3055436]: github.com/gravitational/teleport/lib/service/service.go:3920 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxy.func1
teleport[3055436]: github.com/gravitational/teleport/lib/service/supervisor.go:581 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
teleport[3055436]: github.com/gravitational/teleport/lib/service/supervisor.go:307 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
teleport[3055436]: runtime/asm_amd64.s:1700 runtime.goexit
```

Bug details:
- Teleport version
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by tigrato**
This PR fixes an issue caused by configuring Teleport proxy listener address without a host `:443` or in ipv6 form `[::]:443`.

The call to `utils.SplitHostPort` was checking if the host was empty after the split which caused proxies to fail to initialize.

`:443` is equivalent to `0.0.0.0:443`.

Fixes #51838

Changelog: Prevent Teleport proxy failing to initialize when listener address's host component is empty.

### CODE REVIEW

**Review by timothyb89 — APPROVED** [review]

File: lib/kube/grpc/utils.go [hunk 1]
```diff
@@ -42,15 +43,23 @@ import (
 // multiplexing mode, the Kube proxy is always reachable on the same address as
 // the web server using the SNI.
 func getWebAddrAndKubeSNI(proxyAddr string) (string, string, error) {
-	addr, port, err := utils.SplitHostPort(proxyAddr)
+	addr, port, err := net.SplitHostPort(proxyAddr)
```
Comment (zmb3) [inline lib/kube/grpc/utils.go:46]: I know we have test coverage, but just so someone doesn't come along and waste time trying to consolidate.

```suggestion
	// we avoid using utils.SplitHostPort because
	// we allow the host to be empty
	addr, port, err := net.SplitHostPort(proxyAddr)
```

**Review by zmb3 — APPROVED** [review]
