### PR TITLE
Fix converting gRPC errors from GCP SDK

### LINKED ISSUE #41954: Teleport dies on GCP if it cannot fetch the instance labels
### Expected behaviour:

- I am running an agent on GCP without permissions to fetch metadata from IMDS
- I update from 15.3.4 to 15.3.6
- Teleport logs a warning saying that it cannot get labels, but works as before

### Current behaviour:

- Teleport dies

### Bug details:
- Teleport version: 15.3.6
- Recreation steps
- Debug logs

```
2024-05-23T15:56:08Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=FULL&_txlock=immediate, poll stream period: 1s lite/lite.go:259
2024-05-23T15:56:09Z DEBU [SQLITE]    journal_mode=delete, synchronous=2, busy_timeout=10000 lite/lite.go:310
2024-05-23T15:56:09Z INFO [PROC:1]    Generating new host UUID pid:1.1 host_uuid:955c3292-562c-46f2-b708-a6538902cb1f service/service.go:6101
SDK 2024/05/23 15:56:09 WARN falling back to IMDSv1: operation error ec2imds: getToken, http response error StatusCode: 405, request to EC2 IMDS failed
2024-05-23T15:56:09Z WARN  Access denied to instance labels, does the instance have compute.instances.get permission? error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError access denied
Stack Trace:

Caught:
        github.com/gravitational/teleport/lib/cloud/gcp/vm.go:60 github.com/gravitational/teleport/lib/cloud/gcp.convertAPIError
        github.com/gravitational/teleport/lib/cloud/gcp/vm.go:322 github.com/gravitational/teleport/lib/cloud/gcp.(*instancesClient).GetInstance
        github.com/gravitational/teleport/lib/cloud/imds/gcp/imds.go:117 github.com/gravitational/teleport/lib/cloud/imds/gcp.(*InstanceMetadataClient).GetTags
        github.com/gravitational/teleport/lib/cloud/imds/gcp/imds.go:152 github.com/gravitational/teleport/lib/cloud/imds/gcp.(*InstanceMetadataClient).GetHostname
        github.com/gravitational/teleport/lib/service/service.go:940 github.com/gravitational/teleport/lib/service.NewTeleport
        github.com/gravitational/teleport/e/tool/teleport/process/process.go:59 github.com/gravitational/teleport/e/tool/teleport/process.NewTeleport
        github.com/gravitational/teleport/lib/service/service.go:719 github.com/gravitational/teleport/lib/service.Run
        github.com/gravitational/teleport/e/tool/teleport/main.go:28 main.main
        runtime/proc.go:267 runtime.main
        runtime/asm_amd64.s:1650 runtime.goexit
User Message: Request had insufficient authentication scopes.
        access denied
] gcp/imds.go:122

ERROR REPORT:
Original Error: *apierror.APIError rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
error details: name = ErrorInfo reason = ACCESS_TOKEN_SCOPE_INSUFFICIENT domain = googleapis.com metadata = map[method:google.cloud.resourcemanager.v3.TagBindings.ListEffectiveTags service:cloudresourcemanager.googleapis.com]
Stack Trace:
        github.com/gravitational/teleport/lib/cloud/gcp/vm.go:367 github.com/gravitational/teleport/lib/cloud/gcp.(*instancesClient).GetInstanceTags
        github.com/gravitational/teleport/lib/cloud/imds/gcp/imds.go:129 github.com/gravitational/teleport/lib/cloud/imds/gcp.(*InstanceMetadataClient).GetTags
        github.com/gravitational/teleport/lib/cloud/imds/gcp/imds.go:152 github.com/gravitational/teleport/lib/cloud/imds/gcp.(*InstanceMetadataClient).GetHostname
        github.com/gravitational/teleport/lib/service/service.go:940 github.com/gravitational/teleport/lib/service.NewTeleport
        github.com/gravitational/teleport/e/tool/teleport/process/process.go:59 github.com/gravitational/teleport/e/tool/teleport/process.NewTeleport
        github.com/gravitational/teleport/lib/service/service.go:719 github.com/gravitational/teleport/lib/service.Run
        github.com/gravitational/teleport/e/tool/teleport/main.go:28 main.main
        runtime/proc.go:267 runtime.main
        runtime/asm_amd64.s:1650 runtime.goexit
User Message: initialization failed
        rpc error: code = PermissionDenied desc = Request had insufficient authentication scopes.
error details: name = ErrorInfo reason = ACCESS_TOKEN_SCOPE_INSUFFICIENT domain = googleapis.com metadata = map[method:google.cloud.resourcemanager.v3.TagBindings.ListEffectiveTags service:cloudresourcemanager.googleapis.com]

```

### PR DESCRIPTION
**Pull request by atburke**
This change fixes a bug where Teleport would not convert gRPC errors from the GCP SDK.

Fixes #41954.

Changelog: Fixed failed startup on GCP if missing permissions

### CODE REVIEW

**Review by r0mant — APPROVED** [review]

**Comment by zmb3** [comment]
No tests?

File: lib/cloud/gcp/vm.go [hunk 1]
```diff
@@ -59,6 +61,14 @@ func convertAPIError(err error) error {
 	if errors.As(err, &googleError) {
 		return trace.ReadError(googleError.Code, []byte(googleError.Message))
 	}
+	var apiError *apierror.APIError
+	if errors.As(err, &apiError) {
+		if apiError.HTTPCode() != -1 {
+			return trace.ReadError(apiError.HTTPCode(), []byte(apiError.Reason()))
```
Comment (zmb3) [inline lib/cloud/gcp/vm.go:67]:
```suggestion
		if code := apiError.HTTPCode(); code != -1 {
			return trace.ReadError(code, []byte(apiError.Reason()))
```

**Review by zmb3 — APPROVED** [review]
