### PR TITLE
Pull kube proxy address from proxy ping endpoint

### LINKED ISSUE #10396: tctl auth sign --format=kubernetes does not respect `kube_public_addr` settings
### Description

**What happened**:
If using the `tctl auth sign --format=kubernetes` functionality as described in our kubernetes ci/cd docs (https://goteleport.com/docs/kubernetes-access/guides/cicd/) with a non-default port in the proxy `kube_public_addr`, this is not taken into account in the generated kubeconfig file and the credentials will not work.

For comparison, an interactive `tsh kube login` generates the correct kubeconfig file with the `server` respecting the `kube_public_addr`

This is of particular concern for cloud customers where changing the `kube_public_addr` is not possible and it can be set to a non-default value.

**What you expected to happen**:
 `tctl auth sign --format=kubernetes` should respect the `kube_public_addr` when generating a kubeconfig file.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.Set the `kube_public_addr` in the proxy service to something other than 3026 (leave `kube_listen_addr` port at 3026)
2.Run `tctl auth sign --format=kubernetes` as a remote user and observe the generated `server` value in the kubeconfig file

gz#5892

### PR DESCRIPTION
**Pull request by tigrato**
This PR picks the Kubernetes proxy address from the `/webapi/ping` endpoint when tls routing is disabled and the user didn't provide the `--proxy` flag when calling `tctl auth sign --format=kubernetes`

If tls routing is enabled, it takes precedence over `kube_public_addr`.

Fixes #10396

### CODE REVIEW

File: tool/tctl/common/auth_command.go [hunk 1]
```diff
@@ -926,14 +925,32 @@ func (a *AuthCommand) checkProxyAddr(ctx context.Context, clusterAPI auth.Client
...
 		if err != nil {
 			log.Warningf("Invalid public address on the proxy %q: %q: %v.", p.GetName(), addr, err)
 			continue
 		}
+
+		ping, err := webclient.Ping(
+			&webclient.Config{
+				Context:   ctx,
+				ProxyAddr: addr,
+				Insecure:  true,
```
Comment (nklaassen) [inline tool/tctl/common/auth_command.go:938]: why insecure?

Comment (tigrato) [reply tool/tctl/common/auth_command.go:938]: We are dialing to the proxy public address and it might use a self-signed certificate.

`tctl` has an insecure flag but it's supposed to control the auth server certificate, not the proxy.

**Review by camscale — APPROVED** [review]

File: tool/tctl/common/auth_command.go (hunk 1 above)
Comment (nklaassen) [reply tool/tctl/common/auth_command.go:938]: But this is actually insecure right? I don't understand why it would be okay to go insecure by default here

Comment (tigrato) [reply tool/tctl/common/auth_command.go]: We use the proxies registered in auth server, so at least they have valid credentials to connect to our cluster but I dropped the insecure.
If the connection fails, users are forced to provide the `--proxy` flag.

**Review by nklaassen — APPROVED** [review]

File: tool/tctl/common/auth_command.go (hunk 1 above)
Comment (nklaassen) [reply tool/tctl/common/auth_command.go]: thanks for the update, yeah we can be sure that's the real proxy address but we still want to be protected from MITM attacks
