### PR TITLE
Fix data race when calling Uploader's `Close` and `Serve` simultaneously

### LINKED ISSUE #30212: `TestEC2Hostname` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5805374952/job/15736367487

#### Relevant snippet

```
{"caller":"backend/buffer.go:280","component":"buffer","level":"debug","message":"Removing watcher 0xc0026f8000 via external close.","timestamp":"2023-08-09T05:54:04Z"}
{"caller":"backend/buffer.go:280","component":"buffer","level":"debug","message":"Removing watcher 0xc002dc8240 via external close.","timestamp":"2023-08-09T05:54:04Z"}
{"caller":"auth/middleware.go:269","component":"auth:3","error":"listener is closed\n\tlistener is closed","level":"warning","message":"Mux serve failed.","timestamp":"2023-08-09T05:54:04Z"}
{"caller":"srv/heartbeat.go:290","component":"auth:beat","level":"debug","message":"Heartbeat exited.","timestamp":"2023-08-09T05:54:04Z"}
    testing.go:1225: TempDir RemoveAll cleanup: unlinkat /tmp/TestEC2Hostname701209449/002/log: directory not empty
--- FAIL: TestEC2Hostname (0.28s)
```

### PR DESCRIPTION
**Pull request by tigrato**
This PR fixes a data race introduced by #30211 while trying to fix the uploader write after being closed.

The data race happens when `Serve` and `Close` methods are called simultaneously - i.e. `Serve` is spawned by `RegisterFunc` and `Close` is called via `OnExit` function.
There is no guarantee that when `OnExit` is called `Serve` is already spawn and running. This creates a data race when `Close` blocks on `wg.Wait()` but `Serve` still tries to call `wg.Add(1)` into the waitgroup.

To prevent the data race, we added an `isClosing` field that controls when the server is marked to be closing and we call `wg.Add(1)` if `isClosing=false` and under locking to prevent the race between `Close` and `Serve`.

Fixes #30212

### CODE REVIEW

File: lib/events/filesessions/fileasync.go [hunk 1]
```diff
@@ -167,8 +172,22 @@ func (u *Uploader) checkSessionError(sessionID session.ID) (bool, error) {
...
+	// and Close can be called before Serve starts which ends up in a data
+	// race because Close is waiting for wg to be 0 and Serve is adding to wg.
+	// To avoid this, we check if Close is already in progress and return
+	// immediately. If Close is not in progress, we add to wg under the mutex
+	// lock to ensure that Close can't reach wg.Wait() before Serve adds to wg.
+	u.mu.Lock()
+	if u.isClosing {
+		u.mu.Unlock()
+		return nil
+	}
```
Comment (smallinsky) [inline lib/events/filesessions/fileasync.go:186]: I think that select with closeC will work too so we can get rid of mutex and isClosing: 
```suggestion
	select {
	case <-u.closeC:
		return nil
	default:
	}
```

Comment (tigrato) [reply lib/events/filesessions/fileasync.go:186]: I don't think this would work because we need to ensure that close can't reach  `wg.Wait()` before we either exit `Serve` or call `wg.Add(1)`  there.

If the number of CPUs is >2, it's possible for `Close()` to reach `wg.Wait()` and `Serve` to reach `wg.Add` with that approach

**Review by smallinsky — APPROVED** [review]

**Review by flyinghermit — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
