### PR TITLE
Fix an issue sometimes MachineID does not work behind L7 LB

### LINKED ISSUE #28486: `tsh xxx --identity <identity-file>` fails when Proxy behind L7 LB
Expected behavior:
`tsh xxx --identity <identity-file>` should succeed

Current behavior:
`tsh xxx --identity <identity-file>` fail with tls dial errors

Bug details:
- Teleport version: v13, master
- Recreation steps: Proxy behind L7 LB, export an identity, then `tsh ls --identity <identity-file> --proxy <proxy> --debug`
- Debug logs:
```
$ tsh ls --identity terraform-identity --proxy $awsrootdev:443 --debug
2023-06-29T14:58:00-04:00 INFO [CLIENT]    ALPN connection upgrade required for "teleport.root.dev.aws.stevexin.me:443": false. client/api.go:653
...
ERROR REPORT:
Original Error: *tls.CertificateVerificationError tls: failed to verify certificate: x509: certificate is valid for <redacted> not <redacted>
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/alpn.go:148 github.com/gravitational/teleport/api/client.(*ALPNDialer).DialContext
	github.com/gravitational/teleport/lib/utils/proxy/proxy.go:71 github.com/gravitational/teleport/lib/utils/proxy.directDial.DialTimeout
	github.com/gravitational/teleport/lib/utils/proxy/proxy.go:58 github.com/gravitational/teleport/lib/utils/proxy.directDial.Dial
	github.com/gravitational/teleport/lib/client/api.go:3108 github.com/gravitational/teleport/lib/client.makeProxySSHClientWithTLSWrapper
	github.com/gravitational/teleport/lib/client/api.go:3027 github.com/gravitational/teleport/lib/client.makeProxySSHClient
```

Workaround:
`TELEPORT_TLS_ROUTING_CONN_UPGRADE=true tsh ls --identity <identity-file> --proxy <proxy>` would succeed though.

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #28486
- #28486

When `tbot` wraps `tsh`, it passes `--identity` instead of using a saved profile:
https://github.com/gravitational/teleport/blob/cf23101efbad671d6f65bd502f5025997e446be9/tool/tsh/common/tsh.go#L3325-L3338

The ALPN handshake test (to decide if ALPN conn upgrade is required) was missing in this case.

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -3334,9 +3334,6 @@ func (tc *TeleportClient) Login(ctx context.Context) (*Key, error) {
 		return nil, trace.Wrap(err)
 	}
 
-	// Perform the ALPN test once at login.
-	tc.TLSRoutingConnUpgradeRequired = client.IsALPNConnUpgradeRequired(ctx, tc.WebProxyAddr, tc.InsecureSkipVerify)
-
```
Comment (greedy52) [inline lib/client/api.go:3339]: moved inside `tc.Ping`

**Review by strideynet — APPROVED** [review]
Great, thanks for tackling this.

**Review by gabrielcorado — APPROVED** [review]
