### PR TITLE
Fixing blocking behavior when an encrypted recording upload fails

### LINKED ISSUE #61538: Failed async upload of encrypted recordings can prevent uploads of well-formed recordings
Expected behavior:
When using `node` or `proxy` recording modes with encrypted recordings, an attempt should always be made to upload a well-formed recording regardless of the state of other recordings on disk.

Current behavior:
A failure to upload a corrupted or malformed recording can prevent the upload of recordings that would otherwise succeed.

Bug details:
- Teleport version: v18.3.1
- Recreation steps
  - Record a session using an async recording mode with encryption enabled. This will generate a `.tar` recording file 
  - Modify or remove some of the data to simulate corruption and force an upload failure. The age header and first part header must be intact, so avoid changing the beginning of the file
  - Attempt to capture session recordings while the corrupted recording exists in the affected node's upload folder.
  - Recordings should not generate a thumbnail or metadata and they will not be replayable.

### PR DESCRIPTION
**Pull request by eriktate**
Fixes #61538

This PR ensures that a failure to upload an encrypted recording does not prevent uploading other well-formed recordings. If an encrypted recording fails to upload due to issues parsing the recording file itself, it will be moved into the corrupted recordings folder. Otherwise, the recording file will remain in the scan directory and retried without blocking other recordings from attempting upload.

This PR also includes a small change to omit debug logs complaining that the software keystore does not support fetching decrypters by label when using the manual encryption config.

changelog: Fixed an issue that caused a failed upload of an encrypted session recording to block other recordings from uploading

## Manual test plan
While running Teleport without the changes in this PR:
- [x] Make sure encrypted recordings are enabled and the recording mode is `proxy`
```yaml
# session_recording_config
spec:
  mode: proxy
  encrypted:
    enabled: true
```
- [x] Create enough sessions to exhaust the uploader's semaphore (default is 10)
- [x] Confirm that for sessions 11 and beyond the sync directory starts to back up with `.tar` files (`$TELEPORT_DATA/log/upload/streaming/default`)
- [x] Restart Teleport and confirm that N more recordings were uploaded (where N is `cfg.ConcurrentUploads`)
- [x] Run Teleport using this branch
- [x] Repeat step 1
- [x] Confirm that no `.tar` files remain
- [x] Generate a recording and remove the first line so that it's viewed as corrupted
- [x] Confirm the recording ends up in the corrupted folder

### CODE REVIEW

File: lib/events/filesessions/fileasync.go [hunk 1]
```diff
@@ -654,7 +625,61 @@ func (u *Uploader) startUpload(ctx context.Context, fileName string) (err error)
...
+	if err != nil {
+		return trace.Wrap(sessionError{err})
+	}
+
+	if header.Flags&events.ProtoStreamFlagEncrypted == 0 {
+		return trace.Wrap(errSkipEncryptedUpload, "recording not encrypted")
+	}
+
+	if u.cfg.EncryptedRecordingUploader == nil {
+		return trace.Wrap(errNoEncryptedUploader)
```
Comment (Joerger) [inline lib/events/filesessions/fileasync.go:646]: Should this be a `sessionError` instead? Are we failing with a sessionError later on when it tries to upload this as a non encrypted recording?

File: lib/events/filesessions/fileasync.go [hunk 2]
```diff
@@ -654,7 +625,61 @@ func (u *Uploader) startUpload(ctx context.Context, fileName string) (err error)
...
+	// The upload parts in the given reader are each ~128KB. Usually these parts are consumed and reconstructed
+	// by Auth in 5MB chunks to meet the minimum upload size of upload providers like S3. Since these uploads
+	// are proxied directly to the uploader from the agent here (see link below), this agent needs to combine
+	// these upload parts into larger, aggregated upload parts.
+	//
+	// https://github.com/gravitational/teleport/blob/master/rfd/0127-encrypted-session-recordings.md#session-recording-modes
+	partIter := encryptedUploadAggregateIter(up.file, u.cfg.EncryptedRecordingUploadTargetSize, u.cfg.EncryptedRecordingUploadMaxSize)
+
+	u.wg.Go(func() {
+		defer u.releaseSemaphore(ctx)
```
Comment (Joerger) [inline lib/events/filesessions/fileasync.go:662]: Aren't we already releasing this semaphore in `startUpload`? Will this cause a block on the second call until ctx is closed?

**Review by Joerger — COMMENTED** [review]
Did you run through manual tests as well?

File: lib/events/filesessions/fileasync.go (hunk 2 above)
Comment (eriktate) [reply lib/events/filesessions/fileasync.go:662]: It only gets called in `startUpload` when returning an error. So when an encrypted upload finished successfully, we weren't releasing it before. This is actually where the blocking behavior was coming from. Ironically this behavior only became noticeable because I fixed the bug where encrypted recordings were being double uploaded as plaintext. That just happened to release the semaphore for encrypted recordings as well

File: lib/events/filesessions/fileasync.go (hunk 1 above)
Comment (eriktate) [reply lib/events/filesessions/fileasync.go:646]: Making this a `sessionError` would end up causing the recording to be moved into the corrupted folder. Since this error doesn't actually signal an issue with the recording itself I opted to try and keep it around. This should also cause `startUpload` to return with an error instead of proceeding with a plaintext upload

Comment (Joerger) [reply lib/events/filesessions/fileasync.go:646]: Ahh yes I see it now, makes sense.

File: lib/events/filesessions/fileasync.go [hunk 3]
```diff
@@ -296,6 +296,10 @@ func (u *Uploader) Scan(ctx context.Context) (*ScanStats, error) {
 				u.log.DebugContext(ctx, "Recording was uploaded by another process.", "recording", fi.Name())
 				continue
 			}
+			if errors.Is(err, errNoEncryptedUploader) {
+				u.log.ErrorContext(ctx, "Skipped encrypted session recording due to missing uploader", "recording", fi.Name(), "error", err)
```
Comment (rosstimothy) [inline lib/events/filesessions/fileasync.go]: Will including the error in the output add any meaningful/additional information to this log? The errNoEncryptedUploader is defined as `no encrypted uploader configured while uploading encrypted recording` which seems to be the same as the log message in different words.
```suggestion
				u.log.ErrorContext(ctx, "Skipped encrypted session recording due to missing uploader", "recording", fi.Name())
```

File: lib/events/filesessions/fileasync.go [hunk 4]
```diff
@@ -486,7 +455,16 @@ func encryptedUploadAggregateIter(in io.Reader, targetSize int, maxSize int) ite
...
 
-	return func(yield func([]byte, error) bool) {
+	return func(yieldFn func([]byte, error) bool) {
+		// wrap any yielded errors with sessionError since any failure to
+		// read the file itself should be treated as a corrupted recording
+		yield := func(b []byte, err error) bool {
+			if err != nil {
+				err = sessionError{err}
+			}
+			return yieldFn(b, err)
```
Comment (rosstimothy) [inline lib/events/filesessions/fileasync.go]: Suggestion: return instead of shadowing?
```suggestion
			if err != nil {
				return yieldFn(b, sessionError{err})
			}
			return yieldFn(b, nil)
```

File: lib/events/filesessions/fileasync_test.go [hunk 5]
```diff
@@ -849,8 +942,14 @@ func newUploaderPack(ctx context.Context, t *testing.T, cfg uploaderPackConfig)
 	ctx, cancel := context.WithCancel(ctx)
 	t.Cleanup(cancel)
 
+	clock := cfg.clock
+	var fakeClock *clockwork.FakeClock
```
Comment (rosstimothy) [inline lib/events/filesessions/fileasync_test.go]: Why do we need two clocks?

**Review by rosstimothy — COMMENTED** [review]
Could you include a manual test plan?

File: lib/events/filesessions/fileasync_test.go (hunk 5 above)
Comment (eriktate) [reply lib/events/filesessions/fileasync_test.go]: We don't actually, this is way more confusing than just updating the existing tests to type assert the fake clock. I needed to be able to use a `clockwork.RealClock` since `synctest` doesn't play nice with `clockwork.FakeClock`

File: lib/events/filesessions/fileasync.go (hunk 3 above)
Comment (eriktate) [reply lib/events/filesessions/fileasync.go]: You're right, it's not adding anything useful to this log. Removed!

File: lib/events/filesessions/fileasync.go [hunk 6]
```diff
@@ -486,7 +455,16 @@ func encryptedUploadAggregateIter(in io.Reader, targetSize int, maxSize int) ite
...
 
-	return func(yield func([]byte, error) bool) {
+	return func(yieldFn func([]byte, error) bool) {
+		// wrap any yielded errors with sessionError since any failure to
+		// read the file itself should be treated as a corrupted recording
+		yield := func(b []byte, err error) bool {
+			if err != nil {
+				return yieldFn(b, sessionError{err})
+			}
+			return yieldFn(b, err)
```
Comment (rosstimothy) [inline lib/events/filesessions/fileasync.go]: nit: we know err is nil in this case
```suggestion
			return yieldFn(b, nil)
```

**Review by rosstimothy — APPROVED** [review]

**Review by Joerger — APPROVED** [review]
