### PR TITLE
Authentication Selection

### LINKED ISSUE #758: CLI login should ask for server's version and auth info
## Description

Teleport can be configured with various authentication back-ends (LDAP, local DB, OAuth2, etc). In addition to that, the 2nd factor can be on, off or via u2f. 

Currently the CLI client has no idea how to authenticate a user and it requires a CLI flag to select a method of authentication. This makes it cumbersome to use (why ask user for the auth method if the server already knows?).

## Proposal

The CLI client, before even asking anything, should first request the authentication type from the server. Then, based on the returned information, it should ask the user appropriate questions.

## Implementation

The client already makes an `HTTP GET /ping` call to the proxy server before asking a user for a password. The "ping" call was originally added to determine if HTTPs connection is secure and functional. `/ping` currently returns an empty page. 

Instead `/ping` should return a JSON structure of the following format:

```yaml
kind: ServerInfo
metadata:
    whatever: value
version: 2.0.1-beta-a # should be the same as $(teleport version)
authentication:
     type: local
     second_factor: u2f 
     ...
```

**NOTE** the contents of `authentication` section should contain the _safe subset_ of the `authentication` section in the configuration as shown in #757 - enough for the client to do its job but nothing else (@klizhentas need your input here).

### LINKED ISSUE #784: Broken backwards compatibility
I just rebuilt the last master and Teleport stopped working on the existing dataset.
Start log:

```
container(one) ~/go/src/github.com/gravitational/teleport: build/teleport start -c docker/one.yaml -d
WARN[0000] syslog not available. reverting to stderr     file=utils/cli.go:52 func=utils.InitLoggerCLI
INFO[0000] datadir: /var/lib/teleport
hostname: one
token: ""
authservers:
- addr: 0.0.0.0:3025
  addrnetwork: tcp
  path: ""
identities: []
advertiseip: ""
ssh:
  enabled: true
  addr:
    addr: 0.0.0.0:3022
    addrnetwork: tcp
    path: ""
  namespace: ""
  shell: /bin/bash
  limiter:
    rates: []
    maxconnections: 1000
    maxnumberofusers: 250
    clock: null
  labels:
    cluster: one
  cmdlabels:
    kernel:
      period:
        duration: 5m0s
      command:
      - /bin/uname
      - -r
      result: ""
auth:
  enabled: true
  sshaddr:
    addr: 0.0.0.0:3025
    addrnetwork: tcp
    path: ""
  authorities: []
  roles: []
  domainname: one
  statictokens:
  - roles:
    - Node
    - Auth
    - Proxy
    expires: 1970-01-01T00:00:00Z
    token: xxx
  storageconfig:
    type: bolt
    path: /var/lib/teleport
  limiter:
    rates: []
    maxconnections: 1000
    maxnumberofusers: 250
    clock: null
  noaudit: false
  preference: null
  u2f:
    kind: universal_second_factor
    version: v2
    metadata:
      name: universal-second-factor
      namespace: default
      description: ""
      labels: {}
    spec:
      appid: https://one:3080
      facets:
      - https://one:3080
keygen: null
proxy:
  enabled: true
  disablewebui: false
  reversetunnellistenaddr:
    addr: 0.0.0.0:3024
    addrnetwork: tcp
    path: ""
  webaddr:
    addr: 0.0.0.0:3080
    addrnetwork: tcp
    path: ""
  sshaddr:
    addr: 0.0.0.0:3023
    addrnetwork: tcp
    path: ""
  tlskey: ""
  tlscert: ""
  limiter:
    rates: []
    maxconnections: 1000
    maxnumberofusers: 250
    clock: null
hostuuid: ""
console: 0
reversetunnels: []
oidcconnectors: []
pidfile: ""
trust: null
presence: null
provisioner: null
identity: null
access: null
seedconfig: false
  file=common/teleport.go:127 func=common.Run
INFO[0000] Initializing Cluster Authentication Preference: <nil>  file=auth/init.go:143 func=auth.Init
INFO[0000] Initializing Universal Second Factor Settings: &{Kind:universal_second_factor Version:v2 Metadata:{Name:universal-second-factor Namespace:default Description: Labels:map[]} Spec:{AppID:https://one:3080 Facets:[https://one:3080]}}  file=auth/init.go:149 func=auth.Init

ERROR REPORT:
Original Error: *errors.errorString incompatible value
Stack Trace:
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/backend/boltbk/boltbk.go:307 github.com/gravitational/teleport/lib/backend/boltbk.UpsertBucket
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/backend/boltbk/boltbk.go:210 github.com/gravitational/teleport/lib/backend/boltbk.(*BoltBackend).upsertKey.func1
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/vendor/github.com/boltdb/bolt/db.go:547 github.com/gravitational/teleport/vendor/github.com/boltdb/bolt.(*DB).Update
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/backend/boltbk/boltbk.go:215 github.com/gravitational/teleport/lib/backend/boltbk.(*BoltBackend).upsertKey
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/backend/boltbk/boltbk.go:149 github.com/gravitational/teleport/lib/backend/boltbk.(*BoltBackend).upsertVal
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/backend/boltbk/boltbk.go:122 github.com/gravitational/teleport/lib/backend/boltbk.(*BoltBackend).UpsertVal
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/services/local/u2f.go:59 github.com/gravitational/teleport/lib/services/local.(*UniversalSecondFactorService).SetUniversalSecondFactor
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/auth/init.go:150 github.com/gravitational/teleport/lib/auth.Init
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/service/service.go:317 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/service/service.go:251 github.com/gravitational/teleport/lib/service.NewTeleport
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:160 github.com/gravitational/teleport/tool/teleport/common.onStart
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:140 github.com/gravitational/teleport/tool/teleport/common.Run
	/home/ekontsevoy/go/src/github.com/gravitational/teleport/tool/teleport/main.go:28 main.main
	/opt/go/src/runtime/proc.go:192 runtime.main
	/opt/go/src/runtime/asm_amd64.s:2087 runtime.goexit
User Message: initializing teleport
```

Also attaching the data + confing file (as a tarball). 
[docker-env.tar.gz](https://github.com/gravitational/teleport/files/795593/docker-env.tar.gz)

Unzip the tarball into teleport/docker (it will create `data` directory with the database) and then `cd docker` and `make shell`. Once inside you can run `teleport start -c docker/one.yaml` and you'll get this error.

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

As covered in https://github.com/gravitational/teleport/issues/758, at the moment `tsh` does not know how to authenticate a user. The user has to determine what kind of authentication method is supported by Teleport and then pass the appropriate command line flags to successfully authenticate. 

This PR changes this behavior, now `tsh` calls the `/webapi/ping` endpoint on the proxy to first determine the type of authentication supported and then prompts the user for the correct information needed to login.

In addition, several bugs were introduced in https://github.com/gravitational/teleport/pull/783 that broke backward compatibility with old (and new) configuration files. Those bugs have been fixed.

**Implementation Details**

* A variety of bugs introduced in https://github.com/gravitational/teleport/pull/783 have been fixed, including: permissions to access resources, endpoints on the auth server, old (and new) style configuration parsing, and correction to the backend path for authentication preferences.

* Initializing old (and new style) configuration has changed. Now new style configuration is only updated upon `firstStart`. Old style configuration is always pushed to the backend.

* `/webapi/ping` and `/web/config.js` now return something that looks like the following: 

      {
         "auth": {
            "second_factor": "otp",
            "type": "local",
            "u2f": {                       # optional
               "app_id": ""
            },
            "oidc": {                      # optional
               "name": "",
               "display": ""
            }
         },
         "server_version": "2.0.0-alpha.7"
      }

* Configuration is parsed and migrated into the new style earlier in `lib/config/configuration.go`.

* `CheckAndSetDefaults` has been introduced to `services.AuthPreference` to ensure valid authentication preferences are always set.

**Focus Areas For Review**

* Migration: In `lib/auth/init.go`, for new style configuration, authentication preferences are read on `firstStart` and pushed to the backend and never read from the configuration file again. To continue to support older style configuration, we always read and push U2F and OIDC settings to the backend.

* Login changes: In `lib/client/api.go` the `Login` logic has been updated to automatically select the correct type and second factor. In `tool/tsh/common/tsh.go` the command line flags have been removed.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/758
Fixes https://github.com/gravitational/teleport/issues/784

### CODE REVIEW

File: lib/auth/init.go [hunk 1]
```diff
@@ -136,36 +136,17 @@ func Init(cfg InitConfig, seedConfig bool) (*AuthServer, *Identity, error) {
 	// and this is NOT the first time teleport starts on this machine
 	skipConfig := seedConfig && !firstStart
 
-	// set the cluster auth prerference, the first time read them from the config
+	// upon first start, set the cluster auth prerference from the configuration file
 	// and create a resource on the backend, after that always read from the backend
-	if !skipConfig {
-		log.Infof("Initializing Cluster Authentication Preference: %+v", cfg.AuthPreference)
+	if firstStart {
```
Comment (klizhentas) [inline lib/auth/init.go]: do you only need to do this on first start (with empty db) what about upgrade scenario?

File: lib/backend/boltbk/boltbk.go [hunk 2]
```diff
@@ -267,7 +267,7 @@ func (b *BoltBackend) getKey(buckets []string, key string, val *[]byte) error {
 		if bytes == nil {
 			_, err := GetBucket(tx, append(buckets, key))
 			if err == nil {
-				return trace.BadParameter("key '%v 'is a bucket", key)
+				return trace.BadParameter("key '%v' is a bucket", key)
```
Comment (klizhentas) [inline lib/backend/boltbk/boltbk.go]: `%q` will work without quotes

File: lib/client/api.go [hunk 3]
```diff
@@ -960,35 +952,42 @@ func (tc *TeleportClient) Logout() error {
 // Login logs the user into a Teleport cluster by talking to a Teleport proxy.
 // If successful, saves the received session keys into the local keystore for future use.
 func (tc *TeleportClient) Login() (*CertAuthMethod, error) {
+	httpsProxyHostPort := tc.Config.ProxyWebHostPort()
```
Comment (klizhentas) [inline lib/client/api.go]: protocol suffix is redundant as we are always https for now

File: lib/client/api.go [hunk 4]
```diff
@@ -1001,6 +1000,28 @@ func (tc *TeleportClient) Login() (*CertAuthMethod, error) {
 	return tc.localAgent.AddKey(tc.ProxyHost(), tc.Config.Username, key)
 }
 
+func (tc *TeleportClient) localLogin(secondFactor string, pub []byte) (*SSHLoginResponse, error) {
+	var err error
+	var response *SSHLoginResponse
+
+	switch secondFactor {
```
Comment (klizhentas) [inline lib/client/api.go]: perfect

File: lib/client/weblogin.go [hunk 5]
```diff
@@ -237,21 +237,66 @@ func SSHAgentOIDCLogin(proxyAddr, connectorID string, pubKey []byte, ttl time.Du
 		log.Debugf("got timeout waiting for callback")
 		return nil, trace.Wrap(trace.Errorf("timeout waiting for callback"))
 	}
+}
+
+// PingResponse contains data about the Teleport server like supported authentication
+// types, server version, etc.
+type PingResponse struct {
+	// Auth contains the forms of authentication the auth server supports.
+	Auth *AuthenticationSettings `json:"auth"`
```
Comment (klizhentas) [inline lib/client/weblogin.go]: why is that a pointer? can it be `nil`?

File: lib/web/apiserver.go [hunk 6]
```diff
@@ -278,54 +284,78 @@ func (m *Handler) Close() error {
...
-	for _, connector := range connectors {
-		fmt.Printf("%v\n", connectors)
-		settings.Auth.OIDCConnectors = append(settings.Auth.OIDCConnectors, oidcConnector{
-			ID:      connector.GetName(),
-			Display: connector.GetDisplay(),
-		})
+	as.Type = cap.GetType()
+	as.SecondFactor = cap.GetSecondFactor()
+
+	if cap.GetSecondFactor() == "u2f" {
```
Comment (klizhentas) [inline lib/web/apiserver.go]: can you make all those "u2f" and "oidc" strings constants? and refer to them from one place?

File: lib/web/apiserver.go [hunk 7]
```diff
@@ -278,54 +284,78 @@ func (m *Handler) Close() error {
...
+		universalSecondFactor, err := authClient.GetUniversalSecondFactor()
+		if err != nil {
+			if !trace.IsNotFound(err) {
+				log.Infof("Unable to get U2F Settings: %v", err)
```
Comment (klizhentas) [inline lib/web/apiserver.go]: this should be debug at best

File: lib/web/apiserver.go [hunk 8]
```diff
@@ -278,54 +284,78 @@ func (m *Handler) Close() error {
...
+				goto oidc
```
Comment (klizhentas) [inline lib/web/apiserver.go]: can you split into two functions? `goto` makes it harder to read than it should probably be

File: lib/web/apiserver.go [hunk 9]
```diff
@@ -278,54 +284,78 @@ func (m *Handler) Close() error {
...
 	}
 
-	if len(settings.Auth.OIDCConnectors) == 0 {
-		settings.Auth.OIDCConnectors = make([]oidcConnector, 0)
+oidc:
+	if cap.GetType() == "oidc" {
+		oidcConnectors, err := authClient.GetOIDCConnectors(false)
+		if err != nil {
+			if !trace.IsNotFound(err) {
+				log.Infof("Unable to get U2F Settings: %v", err)
```
Comment (klizhentas) [inline lib/web/apiserver.go]: not an info-level thing I think

File: lib/web/apiserver.go [hunk 10]
```diff
@@ -278,54 +284,78 @@ func (m *Handler) Close() error {
...
+				goto end
+			}
+		}
+
+		// always use the first one as only allow a single oidc connector now
+		as.OIDC = &client.OIDCSettings{
+			Name:    oidcConnectors[0].GetName(),
```
Comment (klizhentas) [inline lib/web/apiserver.go]: what if there are no connectors? someone deleted them would we panic here?

**Review by klizhentas — CHANGES_REQUESTED** [review]

**Comment by kontsevoy** [comment]
Comment:

> for new style configuration, authentication preferences are read on firstStart and pushed to the backend and never read from the configuration file again

This is OK for now, but most likely this won't stay this way for long. We're thinking about adding an explicit switch regulating this behavior. Just FYI.

File: lib/auth/permissions.go [hunk 11]
```diff
@@ -171,18 +171,20 @@ func GetCheckerForBuiltinRole(role teleport.Role) (services.AccessChecker, error
...
+					services.KindEvent:                 services.RW(),
+					services.KindSession:               services.RW(),
+					services.KindNode:                  services.RO(),
+					services.KindAuthServer:            services.RO(),
+					services.KindReverseTunnel:         services.RO(),
+					services.KindCertAuthority:         services.RO(),
+					services.KindUser:                  services.RO(),
+					services.KindRole:                  services.RO(),
+					services.KindClusterAuthPreference: services.RO(),
+					services.KindUniversalSecondFactor: services.RO(),
```
Comment (kontsevoy) [inline lib/auth/permissions.go]: Why does "2nd factor" deserves to be a top-level thing? Isn't it one of many sub-properties of ClusterAuthPreference?

File: lib/client/weblogin.go (hunk 5 above)
Comment (kontsevoy) [inline lib/client/weblogin.go]: +1 structs are better be nested by default (reduces heap pressure, makes it easier to initialize them and removes the need to check for nils) unless there's an explicit reason to have nil in there.

File: lib/client/api.go (hunk 3 above)
Comment (kontsevoy) [inline lib/client/api.go]: I think this is good actualy because there are TWO "proxyhostport" values, one is HTTPS and another is SSH, so it makes it clearer which proxy port we're using here

Comment (klizhentas) [inline lib/client/api.go]: k, makes sense

File: lib/web/apiserver.go (hunk 6 above)
Comment (kontsevoy) [inline lib/web/apiserver.go]: +1

File: lib/auth/permissions.go (hunk 11 above)
Comment (russjones) [inline lib/auth/permissions.go]: The `authentication` section in the configuration file gets broken up into three resources on the backend: `AuthPreference`, `UniversalSecondFactor`, and `OIDCConnector`. That's what this is referring to.

File: lib/auth/init.go (hunk 1 above)
Comment (russjones) [inline lib/auth/init.go]: Not sure what the behavior should be here, @kontsevoy mentioned an explicit switch for this?

**Comment by russjones** [comment]
@klizhentas I've made the changes you suggested.

**Review by klizhentas — APPROVED** [review]
