### PR TITLE
Better Semaphore Lease Contention Handling

### LINKED ISSUE #10363: Slow session reclaim prevents using full max_connections allowance
### Description

**What happened**:

When running `tsh ssh` commands in parallel in batches sized equal to server limit big % of sessions fail with `too many concurrent ssh connections`. This issue does not improve when configuring proxies with `in-memory` mode.

**What you expected to happen**:

Parallel commands should be ran up to the configured connection limit.

### Reproduction Steps
1.  Configure teleport server with `max_connections` limit (10 in this example).
2. Run tsh ssh commands with parallelism equal to max connections settings: `tsh ls  -f names | xargs -P10 -I{} tsh ssh {} uptime`
3. Observe errors: `ERROR: ssh: rejected: administratively prohibited (too many concurrent ssh connections for user "$user@$domain" (max=10))`
4. Run tsh ssh commands with lowered parallelism: `tsh ls  -f names | xargs -P5 -I{} tsh ssh {} uptime`
5. Observe errors disappear.

### Server Details
- Teleport version (run `teleport version`): 7.3.13

### Client Details
- Tsh version (`tsh version`): 7.3.13

### PR DESCRIPTION
**Pull request by rosstimothy**
Add the same retry logic from `AcquireSemaphore` to `CancelSemaphoreLease`
to handle contetion. Without the retry it is possible for a cancellation
to fail and the lease in question to remain held for its entire expiry.
If the number of cancellations that fail is >= `max_connections` then
this causes a user to effectively be locked out until the leases are
expired.

Fixes #10363

### CODE REVIEW

File: lib/services/local/presence.go [hunk 1]
```diff
@@ -798,20 +798,20 @@ func (s *PresenceService) DeleteAllRemoteClusters() error {
 	return trace.Wrap(err)
 }
 
+// this combination of backoff parameters leads to worst-case total time spent
+// in backoff between 1200ms and 2400ms depending on jitter.  tests are in
+// place to verify that this is sufficient to resolve a 20-lease contention
+// event, which is worse than should ever occur in practice.
+const baseBackoff = time.Millisecond * 300
+const leaseRetryAttempts int64 = 6
```
Comment (jimbishopp) [inline lib/services/local/presence.go:806]: Not sure if it is worth doing now, but it would be nice if these were variables in PresenceService so we could add test coverage for the LimitExceeded error without having to wait 4.5 seconds.

**Review by jimbishopp — APPROVED** [review]
LGTM

**Review by r0mant — APPROVED** [review]

File: lib/services/local/presence.go (hunk 1 above)
Comment (rosstimothy) [reply lib/services/local/presence.go:806]: Yeah I agree. I was trying to limit the noise in this PR though.
