### PR TITLE
Fix pagerduty AMR test to prevent flakiness

### LINKED ISSUE #46253: `TestPagerdutyPluginOSS` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/10707851937/job/29688807890
- https://github.com/gravitational/teleport/actions/runs/10724980414/job/29741843186?pr=45937

#### Relevant snippet

```
    suite.go:469: 
        	Error Trace:	/__w/teleport/teleport/integrations/access/pagerduty/testlib/suite.go:469
        	Error:      	Not equal: 
        	            	expected: "service-2"
        	            	actual  : "service-1"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-service-2
        	            	+service-1
        	Test:       	TestPagerdutyPluginOSS/TestRecipientsFromAccessMonitoringRule
```

### PR DESCRIPTION
**Pull request by EdwardDowling**
Fixes #46253 

Changes test to retry until access monitoring rule begins applying as access request creation on the line following the rule creation may result in the plugin seeing the request before its cache of access monitoring rules has been updated.

Could not replicate the test flaking locally with a '-count 5000'

### CODE REVIEW

File: integrations/access/pagerduty/testlib/suite.go [hunk 1]
```diff
@@ -453,24 +453,27 @@ func (s *PagerdutySuiteOSS) TestRecipientsFromAccessMonitoringRule() {
...
-	// Validate the incident has been created in Pagerduty and its ID is stored
-	// in the plugin_data.
-	pluginData := s.checkPluginData(ctx, req.GetName(), func(data pagerduty.PluginData) bool {
-		return data.IncidentID != ""
-	})
+	// Incident creation may happen before plugins Access Monitoring Rule cache
+	// has been updated with new rule. Retry until the new rule starts applying.
+	require.Eventually(t, func() bool {
+		// Test execution: create an access request
+		req := s.CreateAccessRequest(ctx, integration.RequesterOSSUserName, nil)
```
Comment (tigrato) [inline integrations/access/pagerduty/testlib/suite.go:460]: should this run in the eventually clause?

Comment (zmb3) [reply integrations/access/pagerduty/testlib/suite.go:460]: Shouldn't you create **one** access request and continuously check until the AMR cache picks it up and starts to apply it?

File: integrations/access/pagerduty/testlib/suite.go [hunk 2]
```diff
@@ -453,24 +453,27 @@ func (s *PagerdutySuiteOSS) TestRecipientsFromAccessMonitoringRule() {
...
-	assert.Equal(t, incident.ID, pluginData.IncidentID)
-	assert.Equal(t, s.pdNotifyService2.ID, pluginData.ServiceID)
-
-	assert.Equal(t, pagerduty.PdIncidentKeyPrefix+"/"+req.GetName(), incident.IncidentKey)
-	assert.Equal(t, "triggered", incident.Status)
+		assert.Equal(t, pagerduty.PdIncidentKeyPrefix+"/"+req.GetName(), incident.IncidentKey)
+		assert.Equal(t, "triggered", incident.Status)
 
+		assert.Equal(t, s.pdNotifyService2.ID, hasIncidentID.ServiceID)
+	}, 10*time.Second, time.Second, "new access monitoring rule did not begin applying")
```
Comment (nklaassen) [inline integrations/access/pagerduty/testlib/suite.go:476]: heads up this will always sleep for a full second before the first check, maybe it should be faster

**Review by nklaassen — APPROVED** [review]

File: integrations/access/pagerduty/testlib/suite.go (hunk 1 above)
Comment (tigrato) [reply integrations/access/pagerduty/testlib/suite.go:460]: Yeah, I think so otherwise you are just creating 10 access requests that you immediately check if the rules were applied which will cause the flakiness to continue. 
What you should do instead is create the access request outside of the eventually loop and in the eventually loop check if the rules were correctly applied

Comment (EdwardDowling) [reply integrations/access/pagerduty/testlib/suite.go:460]: I was trying to avoid adding test specific code to the access monitoring rule watcher/cache to allow for this watching. If we create one request and it gets processed before the rule is added to the cache no amount of waiting will cause it to change recipients since they are determined as soon as the request is seen by the plugin. I could add a callback to the plugins or to the watcher to allow the tests to know if the rule has been picked up before creating the request, but that would require testing specific code being added outside of the _test.go files.

Comment (EdwardDowling) [reply integrations/access/pagerduty/testlib/suite.go:460]: I can add in the test specific code to the access monitoring rule cache so we can wait until its updated if you think that is better than just retrying the request creation until it catches up but having no test specific code leaking into the implementation.

Comment (EdwardDowling) [reply integrations/access/pagerduty/testlib/suite.go]: Is something like this more along the lines of what you were thinking?

File: integrations/access/pagerduty/testlib/suite.go [hunk 3]
```diff
@@ -453,24 +459,30 @@ func (s *PagerdutySuiteOSS) TestRecipientsFromAccessMonitoringRule() {
 		})
 	assert.NoError(t, err)
 
+	// Incident creation may happen before plugins Access Monitoring Rule cache
+	// has been updated with new rule. Retry until the new cache picks up the rule.
+	require.EventuallyWithT(t, func(t *assert.CollectT) {
+		require.Equal(t, lastRuleUpdated, ruleName)
+	}, 3*time.Second, time.Millisecond*100, "new access monitoring rule did not begin applying")
```
Comment (tigrato) [inline integrations/access/pagerduty/testlib/suite.go:466]:
```suggestion
	require.EventuallyWithT(t, func(t *assert.CollectT) {
		require.Contains(t, collectedNames, ruleName)
	}, 3*time.Second, time.Millisecond*100, "new access monitoring rule did not begin applying")
```

File: integrations/access/pagerduty/testlib/suite.go [hunk 4]
```diff
@@ -430,6 +430,15 @@ func (s *PagerdutySuiteOSS) TestRecipientsFromAccessMonitoringRule() {
 	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
 	t.Cleanup(cancel)
 
+	const ruleName = "test-pagerduty-amr"
+	var collectedNames []string
+	var mu sync.Mutex
+	s.appConfig.OnAccessMonitoringRuleCacheUpdateCallback = func(_ types.OpType, name string, _ *accessmonitoringrulesv1.AccessMonitoringRule) error {
+	        mu.Lock()
+		collectedNames=append(collectedNames, name)
```
Comment (zmb3) [inline integrations/access/pagerduty/testlib/suite.go:438]: Missing gofmt?

File: integrations/access/pagerduty/testlib/suite.go [hunk 5]
```diff
@@ -453,24 +462,32 @@ func (s *PagerdutySuiteOSS) TestRecipientsFromAccessMonitoringRule() {
...
+		mu.UnLock()
+	}, 3*time.Second, time.Millisecond*100, "new access monitoring rule did not begin applying")
+
 	// Test execution: create an access request
 	req := s.CreateAccessRequest(ctx, integration.RequesterOSSUserName, nil)
 
 	// Validate the incident has been created in Pagerduty and its ID is stored
 	// in the plugin_data.
-	pluginData := s.checkPluginData(ctx, req.GetName(), func(data pagerduty.PluginData) bool {
+	hasIncidentID := s.checkPluginData(ctx, req.GetName(), func(data pagerduty.PluginData) bool {
```
Comment (zmb3) [inline integrations/access/pagerduty/testlib/suite.go:478]: You can revert this name back to `pluginData`.

I was thinking the name of the closure that checks `data.IncidentID != ""` should be balled `hasIncidentID` when I originally made the suggestion, but that func is inlined so there's no need to name it at all.

**Review by zmb3 — APPROVED** [review]
