### PR TITLE
fix kubernetes waiting containers cache index

### LINKED ISSUE #60283: Kubernetes ephemeral containers broken in v18
Expected behavior:

`kubectl debug` commands should work when users require a moderator to join the session

Current behavior:

When users require moderation and they try to create a kubectl debug container, Teleport delays the creation of the moderator until the moderator joins the session.

This is done by creating an object called ephemeral container in the teleport backend which is later read by the agent. 

Teleport cache naming is broken which cause the session to fail with `container debugger-2t2ls is not valid for pod POD_NAME`

Bug details:
- Teleport version
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by tigrato**
This PR resolves an issue with the Kubernetes ephemeral containers cache used by Kubernetes agents, where the keys used in the index and get methods did not match.

This mismatch caused the get method to fail with not found error, preventing the debug container from being created.

Fixes #60283

Changelog: Fixed an issue that caused Kubernetes debug containers to fail with a “container not valid” error when launched by a user requiring moderated sessions.

### CODE REVIEW

File: lib/cache/kube_test.go [hunk 1]
```diff
@@ -133,3 +135,53 @@ func TestKubernetesServers(t *testing.T) {
...
+			})
+		},
+		list: func(ctx context.Context, i int, s string) ([]*kubewaitingcontainerpb.KubernetesWaitingContainer, string, error) {
+			return p.kubeWaitingContainers.ListKubernetesWaitingContainers(ctx, i, s)
+		},
+		cacheList: func(ctx context.Context, i int, s string) ([]*kubewaitingcontainerpb.KubernetesWaitingContainer, string, error) {
+			return p.cache.ListKubernetesWaitingContainers(ctx, i, s)
+		},
+
+		deleteAll: func(ctx context.Context) error {
```
Comment (rosstimothy) [inline lib/cache/kube_test.go:189]:
```suggestion
		},
		deleteAll: func(ctx context.Context) error {
```

**Review by rosstimothy — APPROVED** [review]

File: lib/cache/kube.go [hunk 2]
```diff
@@ -235,22 +234,13 @@ func newKubernetesWaitingContainerCollection(upstream services.KubeWaitingContai
 			proto.CloneOf[*kubewaitingcontainerv1.KubernetesWaitingContainer],
 			map[kubeWaitingContainerIndex]func(*kubewaitingcontainerv1.KubernetesWaitingContainer) string{
 				kubeWaitingContainerNameIndex: func(u *kubewaitingcontainerv1.KubernetesWaitingContainer) string {
-					return u.GetMetadata().GetName()
+					return u.GetSpec().GetUsername() + "/" + u.GetSpec().GetCluster() + "/" + u.GetSpec().GetNamespace() + "/" + u.GetSpec().GetPodName() + "/" + u.GetMetadata().GetName()
```
Comment (camscale) [inline lib/cache/kube.go]: This same construction is done in two other places - `ListKubernetesWaitingContainers()` which is identical and `GetKubernetesWaitingContainer()` which constructs the cache key from a request and not a resource.

At the very least, can this be factored out into a separate function that is used here and in `ListKubernetesWaitingContainers()`? It would be nice if it could also be used by `GetKubernetesWaitingContainer()`, which something like this poorly named code snippet does:

```
type kubernetesWaitingContainerCacheKeyFieldGetter interface {
        GetUsername() string
        GetCluster() string
        GetNamespace() string
        GetPodName() string
}

func kubernetesWaitingContainerCacheKey(c kubernetesWaitingContainerCacheKeyFieldGetter, containerName string) string {
        return c.GetUsername() + "/" + c.GetCluster() + "/" + c.GetNamespace() + "/" + c.GetPodName() + "/" + containerName
}
```

This would help prevent them diverging in future causing this issue again.

Then again, perhaps with the tests there now, this isn't necessary - if they do diverge again, the tests should pick it up.

**Review by camscale — APPROVED** [review]
One thought in the comments - I'll leave it up to you if you feel it's worthwhile.
