### PR TITLE
Fix flaky test `TestProxySSHJumpHost`

### LINKED ISSUE #39578: `TestProxySSHJumpHost/TLS_routing_enabled_for_root_and_disabled_for_leaf` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/8347360353/job/22846803567

#### Relevant snippet

```
FAIL: tool/tsh/common TestProxySSHJumpHost/TLS_routing_enabled_for_root_and_disabled_for_leaf (10.69s)
    testing.go:1225: TempDir RemoveAll cleanup: unlinkat /tmp/TestProxySSHJumpHostTLS_routing_enabled_for_root_and_disabled_for_leaf132326872/002: directory not empty
```

### PR DESCRIPTION
**Pull request by Joerger**
Attempt to fix https://github.com/gravitational/teleport/issues/39578

I turned of SSH connection resumption as it seems like that was causing the flake.

I also switch to `testserver.MakeTestServer` because `newTestSuite` was having issues in parallel runs, likely because the file descriptors for listeners are handled differently. This also improved the test speed from 9 to 8 seconds, so maybe it will have an impact.

The test was also outdated as it was testing if we issued a valid leaf certificate for `tsh proxy ssh -J`. This functionality was removed in favor of using `load_all_cas` since the leaf trusts the root cert and we just need the leaf CA.

### CODE REVIEW

File: tool/teleport/testenv/test_server.go [hunk 1]
```diff
@@ -330,6 +330,36 @@ func WithAuthPreference(authPref types.AuthPreference) TestServerOptFunc {
 	})
 }
 
+func SetupTrustedCluster(ctx context.Context, t *testing.T, rootServer, leafServer *service.TeleportProcess, additionalRoleMappings ...types.RoleMapping) {
```
Comment (zmb3) [inline tool/teleport/testenv/test_server.go:333]: Are there other trusted cluster tests that should use this in the future?

I'm concerned about leaving multiple ways to do the same thing in the codebase and having people reintroduce flaky tests in the future by picking the wrong one.

I'm not suggesting any larger changes in this PR, but maybe a comment or TODO would help.

Comment (Joerger) [reply tool/teleport/testenv/test_server.go:333]: I don't think this particular change contributes to the flakiness here, but agreed. I added deprecation comments. Ideally we would only use `tool/teleport/testenv` for test servers so that any fixes apply to all tests.

**Review by zmb3 — APPROVED** [review]
Looks good, assuming the `// deprecated` comments don't cause lint failures.

**Review by rosstimothy — APPROVED** [review]
