### PR TITLE
[Web] Fix users not being redirected back to the login page when their session expires

### LINKED ISSUE #50431: Web UI does not log out the user automatically after the session expires
Web UI used to log out the user when it detected that the session is expired. 

This what happens in dev tools (looks like we try to log out the user):
Image

I suspect this can be related to https://github.com/gravitational/teleport/pull/43071.
Previously, we ignored any errors from `api.delete()` in `session.logout()`. Now, we redirect to the login page only if deleting the websession succeeds (which does not).

As a result, the user sees a 'missing session cookie' error everywhere in Web UI, and even clicking Logout has no effect.
The page needs to be reloaded manually with Cmd+R.

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves https://github.com/gravitational/teleport/issues/50431

This PR fixes an issue where if a user's session expired, they would not automatically be logged out in the UI and taken back to the login page. The user is now redirected to the login page even if the `api.delete()` call returns an error, which happens if the session is expired/invalid.

### CODE REVIEW

File: web/packages/teleport/src/services/websession/websession.ts
Comment (zmb3) [inline web/packages/teleport/src/services/websession/websession.ts:1]: Any way we can get some test coverage in place?

**Review by gzdunek — APPROVED** [review]
I tested it locally, works properly now.

File: .github/ISSUE_TEMPLATE/webtestplan.md [hunk 1]
```diff
@@ -132,6 +132,8 @@ For each, test the invite, reset, and login flows
 - [ ] Verify that error message is shown if an invite/reset is expired/invalid
 - [ ] Verify that account is locked after several unsuccessful login attempts
 
+- [ ] Verify that after logging in, user is automatically redirected to the login page when the session expires.
```
Comment (kimlisa) [inline .github/ISSUE_TEMPLATE/webtestplan.md:135]: ~~hrm, i'm thinking the "logging in" part was a mistake? 🤔~~ ok now i got it 😅

File: web/packages/teleport/src/services/websession/websession.test.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+test('user should be redirected to login even if session delete call fails', async () => {
+  const mockPromise = {
+    then: jest.fn().mockReturnThis(),
+    catch: jest.fn().mockReturnThis(),
+    finally: jest.fn().mockImplementation(callback => {
+      callback();
+      return mockPromise;
+    }),
+    [Symbol.toStringTag]: 'Promise',
+  };
```
Comment (kimlisa) [inline web/packages/teleport/src/services/websession/websession.test.ts]: hrmmm, this part seems kinda hacky. i see we don't have a catch block in `websession.logout` but we force define it here? i'm guessing this was required b/c of the unhandled catch block.

if that's the case, i think we should add a catch block, console log the error (i think it's going to throw a "unhandled rejection" error without a catch block, so might as well handle it ourselves) and then modify the test to represent a more accurate flow:


```ts
  jest.spyOn(api, 'delete').mockRejectedValue(new Error('som error'));
  const goToLoginSpy = jest.spyOn(history, 'goToLogin').mockImplementation();
  jest.spyOn(websession, 'clear').mockImplementation();

  websession.logout();
  await waitFor(() => expect(goToLoginSpy).toHaveBeenCalled());
```

**Review by kimlisa — APPROVED** [review]
with minor comments

**Review by kimlisa — APPROVED** [review]
