### PR TITLE
only preload local cluster cas

### LINKED ISSUE #48331: Trusted Cluster failed to retrieve client cert pool
### Expected behavior:
Should not expect these error messages in the Trusted root cluster.

### Current behavior:
After establishing a trusted cluster connection between a root and leaf cluster, the root cluster continuously logs the follow error. As far as I can tell, the connection is successfully established and I am able to access resources on the leaf cluster through the root cluster. The error messages also seem to go away after the root cluster teleport service is restarted. I am not sure if this has any impact on usability or features of the trusted cluster.

### Bug details:
- Teleport version: 17.0.0-alpha.2
- Recreation steps: Establish a trusted cluster connection between a leaf and a root cluster.
- Debug logs: 
```
Nov 01 21:55:19 teleport-root teleport[4990]: 2024-11-01T21:55:19Z INFO [PROXY:SER] Connection <- [...]:55546, clusters: 1. cluster:[...] reversetunnel/srv.go:1019


Nov 01 21:57:54 teleport-root teleport[4990]: 2024-11-01T21:57:54Z ERRO  failed to retrieve client cert pool for target cluster cluster_name:[...] error:[
Nov 01 21:57:54 teleport-root teleport[4990]: ERROR REPORT:
Nov 01 21:57:54 teleport-root teleport[4990]: Original Error: *trace.NotFoundError key &#34;/authorities/user/[...]&#34; is not found
Nov 01 21:57:54 teleport-root teleport[4990]: Stack Trace:
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/backend/memory/memory.go:189 github.com/gravitational/teleport/lib/backend/memory.(*Memory).Get
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/backend/report.go:281 github.com/gravitational/teleport/lib/backend.(*Reporter).Get
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/services/local/trust.go:469 github.com/gravitational/teleport/lib/services/local.(*CA).getCertAuthority
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/services/local/trust.go:450 github.com/gravitational/teleport/lib/services/local.(*CA).GetCertAuthority
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/cache/cache.go:1790 github.com/gravitational/teleport/lib/cache.(*Cache).GetCertAuthority
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/auth/authclient/tls.go:63 github.com/gravitational/teleport/lib/auth/authclient.ClientCertPool
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/auth/authclient/tls.go:94 github.com/gravitational/teleport/lib/auth/authclient.DefaultClientCertPool
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/auth/client_tls_config_generator.go:157 github.com/gravitational/teleport/lib/auth.(*ClientTLSConfigGenerator).generator
Nov 01 21:57:54 teleport-root teleport[4990]:         github.com/gravitational/teleport/lib/utils/genmap/genmap.go:319 github.com/gravitational/teleport/lib/utils/genmap.(*GenMap[...]).generate
Nov 01 21:57:54 teleport-root teleport[4990]:         runtime/asm_amd64.s:1700 runtime.goexit
Nov 01 21:57:54 teleport-root teleport[4990]: User Message: key &#34;/authorities/user/[...]&#34; is not found] auth/client_tls_config_generator.go:159
```

### PR DESCRIPTION
**Pull request by fspmarshall**
The original implementation of the client TLS config generator tried to always pre-generate all TLS configs for all known CAs on all changes.  This was nice in theory, but created spurious error logs due to remote clusters not having all requisite CAs stored, and was wasted effort in many cases.

This PR tweaks the event-handling logic of the client TLS config generator to only aggressively generate TLS configs in response to modification events for the local cluster.  For all other clusters, it invalidates any now stale state, but waits until a connection actually comes in before nothing to try to build the TLS config.

Fixes https://github.com/gravitational/teleport/issues/48331

### CODE REVIEW

File: lib/auth/client_tls_config_generator.go [hunk 1]
```diff
@@ -254,8 +254,14 @@ func (c *ClientTLSConfigGenerator) watchForCAChanges(ctx context.Context) error
 					// ignore non-local cluster CA events when we aren't configured to support them
 					continue
 				}
-				// trigger regen of client tls configs for the associated cluster.
-				c.clientTLSConfigs.Generate(event.Resource.GetName())
+
```
Comment (bl-nero) [inline lib/auth/client_tls_config_generator.go:257]: Consider also updating the `watchForCAChanges` documentation comment.

**Review by bl-nero — APPROVED** [review]

**Review by bl-nero — COMMENTED** [review]
Sorry for duplicate comments, but I somehow managed to mishandle them: Consider also updating the `watchForCAChanges` documentation comment, as it's now outdated.

**Review by ravicious — APPROVED** [review]
Approving because the PR description and the code seem to make sense, though I know very little about how we handle CAs.
