### PR TITLE
fix TestGetHeadlessAuthentication

### LINKED ISSUE #54600: `TestGetHeadlessAuthentication` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/14889061716/job/41816328966#step:6:2190

#### Relevant snippet

```
    auth_with_roles_test.go:8104: 
        	Error Trace:	/__w/teleport/teleport/lib/auth/auth_with_roles_test.go:8104
        	            				/__w/teleport/teleport/lib/auth/auth_with_roles_test.go:8158
        	Error:      	Error "rpc error: code = DeadlineExceeded desc = stream terminated by RST_STREAM with error code: CANCEL" does not contain "context deadline exceeded"
        	Test:       	TestGetHeadlessAuthentication/NOK_different_user
        	Messages:   	expected context deadline error but got: rpc error: code = DeadlineExceeded desc = stream terminated by RST_STREAM with error code: CANCEL
```

### PR DESCRIPTION
**Pull request by GavinFrazar**
Handles the error ambiguity in timeout test cases introduced in grpc-go v1.72.0

Fixes https://github.com/gravitational/teleport/issues/54600
- https://github.com/gravitational/teleport/issues/54600

### CODE REVIEW

File: lib/auth/auth_with_roles_test.go [hunk 1]
```diff
@@ -8155,6 +8164,11 @@ func TestGetHeadlessAuthentication(t *testing.T) {
 			}
 
 			retrievedHeadlessAuthn, err := client.GetHeadlessAuthentication(ctx, tc.headlessID)
+			// handle context canceled error ambiguity
+			// https://github.com/grpc/grpc-go/issues/8281
+			if err != nil && ctx.Err() != nil {
+				err = trace.Wrap(err, ctx.Err())
+			}
```
Comment (kopiczko) [inline lib/auth/auth_with_roles_test.go:8171]: Should there be a TODO to remove this hack when they solve 8281?

**Review by kopiczko — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
