### PR TITLE
Fix TLS usage across multiple protocols

### LINKED ISSUE #15076: kubectl getting error "malformed HTTP response"
**Expected behavior:**

kubectl working should be same with teleport and without teleport

**Current behavior:**

```
error: Internal error occurred: error executing command in container: error sending request: Post "https://kube.teleport.cluster.local/api/v1/namespaces/teleport/pods/myshell/exec?command=%!F(MISSING)bin%!F(MISSING)sh&container=myshell&stdin=true&stdout=true&tty=true": malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x10\x00\x00"
```

**Bug details:**
**- Teleport version:**

> Teleport Enterprise v8.3.14, and I did testing with Teleport 10.0.0/10.0.2, same errors,

**- Recreation steps:**
**With Teleport, the steps to reproduce the problem,**

1. Open the first terminal, run,

```
while true; do kubectl get namespaces; done
```

2. Open the second terminal, run,

```
kubectl -n teleport exec -it myshell -- /bin/sh
```
error,
```
error: Internal error occurred: error executing command in container: error sending request: Post "https://kube.teleport.cluster.local/api/v1/namespaces/teleport/pods/myshell/exec?command=%!F(MISSING)bin%!F(MISSING)sh&container=myshell&stdin=true&stdout=true&tty=true": malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x10\x00\x00"
```
3. run,
```
kubectl -n teleport cp 1.txt myshell:/tmp
```
error,
```
error: Internal error occurred: error executing command in container: error sending request: Post "https://kube.teleport.cluster.local/api/v1/namespaces/teleport/pods/myshell/exec?command=tar&command=-xmf&command=-&command=-C&command=%!F(MISSING)&container=myshell&stderr=true&stdin=true&stdout=true": malformed HTTP response "\x00\x00\x18\x04\x00\x00\x00\x00\x00\x00\x05\x00\x10\x00\x00\x00\x03\x00\x00\x00\xfa\x00\x06\x00\x10\x01@\x00\x04\x00\x10\x00\x00"
E0728 14:48:38.187508   33854 v2.go:105] EOF
```
**To access EKS via kubectl directly without Teleport, all good with the above steps.**

### PR DESCRIPTION
**Pull request by tigrato**
Fix TLS usage across multiple protocols like SPDY used in `kube exec` or WebSockets for moderated sessions that require HTTP/1.1 as the initial protocol while other requests like get/edit/delete rely on HTTP/2 protocol.

The same `*tls.Config` was reused for mixed protocol, causing several issues including a data race while manipulating `*tls.Config.NextProtos` without any lock.

This commit clones the `*tls.Config` per request to prevent mixups between connection protocols.

Fixes #15076

### CODE REVIEW

File: lib/kube/proxy/forwarder.go [hunk 1]
```diff
@@ -1791,10 +1791,6 @@ func (f *Forwarder) makeSessionForwarder(sess *clusterSession) (*forward.Forward
 		if err := http2.ConfigureTransport(transport); err != nil {
 			return nil, trace.Wrap(err)
 		}
-	} else if sess.tlsConfig != nil {
-		// when certificate-authority-data is not provided in kubeconfig the tlsConfig can be nil,
-		// meaning that we will use the system default CA store.
-		sess.tlsConfig.NextProtos = nil
```
Comment (r0mant) [inline lib/kube/proxy/forwarder.go:1797]: Why did you remove this?

**Review by r0mant — COMMENTED** [review]
Is it possible to add test coverage here?

File: lib/kube/proxy/forwarder.go (hunk 1 above)
Comment (tigrato) [reply lib/kube/proxy/forwarder.go:1797]: Since I clone the `tls.Config` from the custom config, we do not need to reset the `NextProtos` field since it was never defined.

It was required before because the `tls.Config` was reused across multiple requests and `http2.ConfigureTransport(transport)` manipulated the `tls.Config` to setup the `h2` in `NextProtos` array which was not a valid config when using SPDY or Websockets and had to be reset.
Besides, that reset was generating a data race for concurrent connections

**Comment by tigrato** [comment]
> Is it possible to add test coverage here?

I think that we can. 

For this particular problem, we can validate if the `*clusterSession.tlsConfig` pointer is different than the one stored in the cache (returned by `Forwarder.getClientCreds(ctx)`) if in reverse proxy/direct dial between Teleport services mode, or the one stored in `Forwarder.creds` map for local cluster sessions.

If the pointer is different then we cloned our `tlsConfig` and it's safe to modify it by each connection.


Do you agree with the approach?

File: lib/kube/proxy/forwarder.go (hunk 1 above)
Comment (tigrato) [reply lib/kube/proxy/forwarder.go:1797]: tlsConfigs are generated in the following places:

- Reverse proxy/direct dial between Teleport Services

https://github.com/gravitational/teleport/blob/ff5c56dde077f7283a9dfe3ef085886dbf2e2f6e/lib/kube/proxy/forwarder.go#L1982-L1986

- Local cluster session
https://github.com/gravitational/teleport/blob/ff5c56dde077f7283a9dfe3ef085886dbf2e2f6e/lib/kube/proxy/auth.go#L177

**Comment by r0mant** [comment]
@tigrato Sure sounds good, I think it's better than having no test.

**Review by r0mant — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
