### PR TITLE
Web: Fix local storage clearing

### LINKED ISSUE #27254: Web UI immediately logs user out
After an upgrade to 12.4.4, users noticed being immediately logged out of the web UI after completing SSO via OIDC.

We traced this to a stale `grv_teleport_last_active` value in local storage, which triggered the activity checker here:

https://github.com/gravitational/teleport/blob/master/web/packages/teleport/src/components/Authenticated/Authenticated.tsx#L76

The web UI should:

1. Ensure that the last active value is cleared on logout
2. Update the last active value as soon as a log in completes (logging in is considered activity)

### PR DESCRIPTION
**Pull request by kimlisa**
fixes https://github.com/gravitational/teleport/issues/27254

fixes a bug where upon logout, the local storage was not getting cleared as expected. 

i'm not sure if i am explaining this right, but the previous code, as we were deleting keys, the next index value did not necessarily meant it was the `next key`. if the previous key was deleted, then the next index value may refer to next next key (or out of bounds). so depending on the order of keys, it was a delete or miss, which is why users were having `inconsistent` issues with login/logouts

the incident was: when a user logged in, the user got logged right back out, and it was because the local storage key `LAST_ACTIVE: 'grv_teleport_last_active'` was not getting deleted, so it kept the old expired value.

this bug was introduced (backported) starting from `12.4.0`

when i wrote the test, i tested it against the old code first, which failed

i was also able to replicate the issue where my local storage wasn't getting cleared

re @zac about https://github.com/gravitational/teleport/blob/dbcb8a890aa68d87a641e0558fef58a62a24761b/web/packages/teleport/src/components/Authenticated/Authenticated.tsx#L76, i think we do need this check to handle a case where user just closes tabs (but not the browser) which does not clear the storage, so user can step away, and someone else could go load the website and resume the user's session. granted i only tested this with idle time set to 1min...

### CODE REVIEW

**Comment by zmb3** [comment]
Shouldn't we also update last active on login as an extra measure to prevent this?

Can you also link to the PR that introduced the issue?

**Comment by kimlisa** [comment]
> Shouldn't we also update last active on login as an extra measure to prevent this?
> 
> Can you also link to the PR that introduced the issue?

i did think about it, but didn't think it was really necessary to reset the `LAST_ACTIVE` on login, b/c if clearing the storage on logout works correctly, there should never be a stagnant `LAST_ACTIVE` on login. If for some reason there is one (perhaps user logged out on the bugged version, which may not have deleted the `LAST_ACTIVE` and then use the patched version?), user will at most re-login once.

here are the cases where we auto log the user out (which should clear local storage):
- inactivity
- access request expired
- invalid session
- expired token

if you still think it's a nice to have, i'll add it

**Review by ryanclark — APPROVED** [review]

**Review by ryanclark — APPROVED** [review]

**Review by gzdunek — APPROVED** [review]

File: web/packages/teleport/src/services/localStorage/localStorage.ts [hunk 1]
```diff
@@ -29,13 +29,15 @@ const KEEP_LOCALSTORAGE_KEYS_ON_LOGOUT = [
...
-      const key = window.localStorage.key(i);
-
+      keys.push(window.localStorage.key(i));
+    }
+    keys.forEach(key => {
       if (!KEEP_LOCALSTORAGE_KEYS_ON_LOGOUT.includes(key)) {
         window.localStorage.removeItem(key);
       }
-    }
+    });
```
Comment (avatus) [inline web/packages/teleport/src/services/localStorage/localStorage.ts:40]: Not a blocker, but we can clean this up a bit by just using `Object.keys` 

```js
Object.keys(window.localStorage).forEach
```

**Review by avatus — APPROVED** [review]
