### PR TITLE
Fix connection fallback race in kube `Forwarder`

### LINKED ISSUE #56780: Data Race in `TestKube/EphemeralContainers`
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/16280177064/job/45968022086?pr=56777

#### Relevant snippet

```
==================
WARNING: DATA RACE
Read at 0x00c00408e248 by goroutine 94763:
  github.com/gravitational/teleport/lib/kube/proxy.(*clusterSession).close()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:2388 +0x48
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.deferwrap3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1679 +0x1f
  runtime.deferreturn()
      /opt/go/src/runtime/panic.go:610 +0x5d
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1735 +0x4bd
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1000 +0x997
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1729 +0x3b7
  github.com/gravitational/teleport/lib/kube/proxy.(*session).trackSession()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1438 +0x88d
  github.com/gravitational/teleport/lib/kube/proxy.newSession()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:511 +0x1e17
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1723 +0x2fb
  github.com/gravitational/teleport/lib/kube/proxy.upgradeRequestToRemoteCommandProxy()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:120 +0x444
  k8s.io/apimachinery/pkg/util/httpstream/spdy.responseUpgrader.UpgradeResponse()
      /go/pkg/mod/k8s.io/apimachinery@v0.33.2/pkg/util/httpstream/spdy/upgrade.go:104 +0x4e6
  github.com/gravitational/teleport/lib/kube/proxy.createSPDYStreams()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:145 +0x250
  github.com/gravitational/teleport/lib/kube/proxy.upgradeRequestToRemoteCommandProxy()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:109 +0x9c
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1708 +0x1964
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec-fm()
      <autogenerated>:1 +0xa5
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuth.func1()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:679 +0x7ec
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuth.MakeHandlerWithErrorWriter.func2()
      /__w/teleport/teleport/lib/httplib/httplib.go:128 +0xa5
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf82
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:296 +0xe8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:147 +0xe1
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:109 +0xd2
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.instrumentHTTPHandlerWithPrometheus.InstrumentHandlerInFlight.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:60 +0x104
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:422 +0x61
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:837 +0xa0c
  github.com/gravitational/teleport/lib/limiter/internal/ratelimit.(*TokenLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/internal/ratelimit/ratelimit.go:106 +0x301
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/limiter.go:82 +0x53
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:105 +0x27e
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:3301 +0x2a1
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:2102 +0x1304
  net/http.(*Server).Serve.gowrap3()
      /opt/go/src/net/http/server.go:3454 +0x4f

Previous write at 0x00c00408e248 by goroutine 94911:
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).getExecutor.func1()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:2225 +0x212
  k8s.io/client-go/tools/remotecommand.(*FallbackExecutor).StreamWithContext()
      /go/pkg/mod/k8s.io/client-go@v0.33.2/tools/remotecommand/fallback.go:55 +0x138
  github.com/gravitational/teleport/lib/kube/proxy.(*session).launch()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:719 +0x27b6
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).UpdateState()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:240 +0x402
  github.com/gravitational/teleport/lib/kube/proxy.(*session).launch()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:687 +0x21b0
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join.func3()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1105 +0x47

Goroutine 94763 (running) created at:
  net/http.(*Server).Serve()
      /opt/go/src/net/http/server.go:3454 +0x8c9
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).Serve()
      /__w/teleport/teleport/lib/kube/proxy/server.go:393 +0x9b1
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint.func19()
      /__w/teleport/teleport/lib/service/service.go:5460 +0x3fb
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:582 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:308 +0x4ba

Goroutine 94911 (running) created at:
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1104 +0x1d32
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1008 +0x9c9
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1000 +0x997
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join.func2()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1248 +0x3c4
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1278 +0xb76
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join-fm()
      <autogenerated>:1 +0xa5
  github.com/gravitational/teleport/lib/kube/proxy.NewForwarder.(*Forwarder).withAuthPassthrough.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:707 +0x5ea
  github.com/gravitational/teleport/lib/kube/proxy.NewForwarder.(*Forwarder).withAuthPassthrough.MakeHandlerWithErrorWriter.func6()
      /__w/teleport/teleport/lib/httplib/httplib.go:128 +0xa5
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf82
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:296 +0xe8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:147 +0xe1
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:109 +0xd2
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.instrumentHTTPHandlerWithPrometheus.InstrumentHandlerInFlight.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:60 +0x104
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:422 +0x61
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:837 +0xa0c
  github.com/gravitational/teleport/lib/limiter/internal/ratelimit.(*TokenLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/internal/ratelimit/ratelimit.go:106 +0x301
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/limiter.go:82 +0x53
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:105 +0x27e
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:3301 +0x2a1
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:2102 +0x1304
  net/http.(*Server).Serve.gowrap3()
      /opt/go/src/net/http/server.go:3454 +0x4f
==================
==================
WARNING: DATA RACE
Write at 0x00c0036a2510 by goroutine 94763:
  sync/atomic.CompareAndSwapInt32()
      /opt/go/src/runtime/race_amd64.s:361 +0xb
  sync/atomic.CompareAndSwapInt32()
      <autogenerated>:1 +0x18
  sync.(*Mutex).Lock()
      /opt/go/src/sync/mutex.go:46 +0x28
  context.(*cancelCtx).cancel()
      /opt/go/src/context/context.go:547 +0x84
  context.WithCancelCause.func1()
      /opt/go/src/context/context.go:270 +0x5d
  github.com/gravitational/teleport/lib/kube/proxy.(*clusterSession).close()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:2389 +0xa1
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.deferwrap3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1679 +0x1f
  runtime.deferreturn()
      /opt/go/src/runtime/panic.go:610 +0x5d
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1735 +0x4bd
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1000 +0x997
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1729 +0x3b7
  github.com/gravitational/teleport/lib/kube/proxy.(*session).trackSession()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1438 +0x88d
  github.com/gravitational/teleport/lib/kube/proxy.newSession()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:511 +0x1e17
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1723 +0x2fb
  github.com/gravitational/teleport/lib/kube/proxy.upgradeRequestToRemoteCommandProxy()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:120 +0x444
  k8s.io/apimachinery/pkg/util/httpstream/spdy.responseUpgrader.UpgradeResponse()
      /go/pkg/mod/k8s.io/apimachinery@v0.33.2/pkg/util/httpstream/spdy/upgrade.go:104 +0x4e6
  github.com/gravitational/teleport/lib/kube/proxy.createSPDYStreams()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:145 +0x250
  github.com/gravitational/teleport/lib/kube/proxy.upgradeRequestToRemoteCommandProxy()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:109 +0x9c
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1708 +0x1964
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec-fm()
      <autogenerated>:1 +0xa5
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuth.func1()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:679 +0x7ec
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuth.MakeHandlerWithErrorWriter.func2()
      /__w/teleport/teleport/lib/httplib/httplib.go:128 +0xa5
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf82
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:296 +0xe8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:147 +0xe1
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:109 +0xd2
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.instrumentHTTPHandlerWithPrometheus.InstrumentHandlerInFlight.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:60 +0x104
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:422 +0x61
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:837 +0xa0c
  github.com/gravitational/teleport/lib/limiter/internal/ratelimit.(*TokenLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/internal/ratelimit/ratelimit.go:106 +0x301
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/limiter.go:82 +0x53
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:105 +0x27e
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:3301 +0x2a1
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:2102 +0x1304
  net/http.(*Server).Serve.gowrap3()
      /opt/go/src/net/http/server.go:3454 +0x4f

Previous write at 0x00c0036a2510 by goroutine 94911:
  context.withCancel()
      /opt/go/src/context/context.go:277 +0x53
  context.WithCancelCause()
      /opt/go/src/context/context.go:269 +0x26
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).getExecutor.func1()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:2225 +0x1a5
  k8s.io/client-go/tools/remotecommand.(*FallbackExecutor).StreamWithContext()
      /go/pkg/mod/k8s.io/client-go@v0.33.2/tools/remotecommand/fallback.go:55 +0x138
  github.com/gravitational/teleport/lib/kube/proxy.(*session).launch()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:719 +0x27b6
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).UpdateState()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:240 +0x402
  github.com/gravitational/teleport/lib/kube/proxy.(*session).launch()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:687 +0x21b0
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join.func3()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1105 +0x47

Goroutine 94763 (running) created at:
  net/http.(*Server).Serve()
      /opt/go/src/net/http/server.go:3454 +0x8c9
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).Serve()
      /__w/teleport/teleport/lib/kube/proxy/server.go:393 +0x9b1
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint.func19()
      /__w/teleport/teleport/lib/service/service.go:5460 +0x3fb
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:582 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:308 +0x4ba

Goroutine 94911 (running) created at:
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1104 +0x1d32
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1008 +0x9c9
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1000 +0x997
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join.func2()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1248 +0x3c4
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1278 +0xb76
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join-fm()
      <autogenerated>:1 +0xa5
  github.com/gravitational/teleport/lib/kube/proxy.NewForwarder.(*Forwarder).withAuthPassthrough.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:707 +0x5ea
  github.com/gravitational/teleport/lib/kube/proxy.NewForwarder.(*Forwarder).withAuthPassthrough.MakeHandlerWithErrorWriter.func6()
      /__w/teleport/teleport/lib/httplib/httplib.go:128 +0xa5
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf82
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:296 +0xe8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:147 +0xe1
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:109 +0xd2
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.instrumentHTTPHandlerWithPrometheus.InstrumentHandlerInFlight.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:60 +0x104
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:422 +0x61
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:837 +0xa0c
  github.com/gravitational/teleport/lib/limiter/internal/ratelimit.(*TokenLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/internal/ratelimit/ratelimit.go:106 +0x301
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/limiter.go:82 +0x53
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:105 +0x27e
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:3301 +0x2a1
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:2102 +0x1304
  net/http.(*Server).Serve.gowrap3()
      /opt/go/src/net/http/server.go:3454 +0x4f
==================
==================
WARNING: DATA RACE
Read at 0x00c0036a2530 by goroutine 94763:
  context.(*cancelCtx).cancel()
      /opt/go/src/context/context.go:548 +0x9a
  context.WithCancelCause.func1()
      /opt/go/src/context/context.go:270 +0x5d
  github.com/gravitational/teleport/lib/kube/proxy.(*clusterSession).close()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:2389 +0xa1
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.deferwrap3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1679 +0x1f
  runtime.deferreturn()
      /opt/go/src/runtime/panic.go:610 +0x5d
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1735 +0x4bd
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1000 +0x997
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1729 +0x3b7
  github.com/gravitational/teleport/lib/kube/proxy.(*session).trackSession()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1438 +0x88d
  github.com/gravitational/teleport/lib/kube/proxy.newSession()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:511 +0x1e17
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1723 +0x2fb
  github.com/gravitational/teleport/lib/kube/proxy.upgradeRequestToRemoteCommandProxy()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:120 +0x444
  k8s.io/apimachinery/pkg/util/httpstream/spdy.responseUpgrader.UpgradeResponse()
      /go/pkg/mod/k8s.io/apimachinery@v0.33.2/pkg/util/httpstream/spdy/upgrade.go:104 +0x4e6
  github.com/gravitational/teleport/lib/kube/proxy.createSPDYStreams()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:145 +0x250
  github.com/gravitational/teleport/lib/kube/proxy.upgradeRequestToRemoteCommandProxy()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:109 +0x9c
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1708 +0x1964
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec-fm()
      <autogenerated>:1 +0xa5
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuth.func1()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:679 +0x7ec
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuth.MakeHandlerWithErrorWriter.func2()
      /__w/teleport/teleport/lib/httplib/httplib.go:128 +0xa5
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf82
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:296 +0xe8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:147 +0xe1
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:109 +0xd2
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.instrumentHTTPHandlerWithPrometheus.InstrumentHandlerInFlight.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:60 +0x104
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:422 +0x61
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:837 +0xa0c
  github.com/gravitational/teleport/lib/limiter/internal/ratelimit.(*TokenLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/internal/ratelimit/ratelimit.go:106 +0x301
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/limiter.go:82 +0x53
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:105 +0x27e
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:3301 +0x2a1
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:2102 +0x1304
  net/http.(*Server).Serve.gowrap3()
      /opt/go/src/net/http/server.go:3454 +0x4f

Previous write at 0x00c0036a2530 by goroutine 94911:
  context.withCancel()
      /opt/go/src/context/context.go:277 +0x53
  context.WithCancelCause()
      /opt/go/src/context/context.go:269 +0x26
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).getExecutor.func1()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:2225 +0x1a5
  k8s.io/client-go/tools/remotecommand.(*FallbackExecutor).StreamWithContext()
      /go/pkg/mod/k8s.io/client-go@v0.33.2/tools/remotecommand/fallback.go:55 +0x138
  github.com/gravitational/teleport/lib/kube/proxy.(*session).launch()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:719 +0x27b6
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).UpdateState()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:240 +0x402
  github.com/gravitational/teleport/lib/kube/proxy.(*session).launch()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:687 +0x21b0
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join.func3()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1105 +0x47

Goroutine 94763 (running) created at:
  net/http.(*Server).Serve()
      /opt/go/src/net/http/server.go:3454 +0x8c9
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).Serve()
      /__w/teleport/teleport/lib/kube/proxy/server.go:393 +0x9b1
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint.func19()
      /__w/teleport/teleport/lib/service/service.go:5460 +0x3fb
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:582 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:308 +0x4ba

Goroutine 94911 (running) created at:
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1104 +0x1d32
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1008 +0x9c9
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1000 +0x997
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join.func2()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1248 +0x3c4
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1278 +0xb76
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).join-fm()
      <autogenerated>:1 +0xa5
  github.com/gravitational/teleport/lib/kube/proxy.NewForwarder.(*Forwarder).withAuthPassthrough.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:707 +0x5ea
  github.com/gravitational/teleport/lib/kube/proxy.NewForwarder.(*Forwarder).withAuthPassthrough.MakeHandlerWithErrorWriter.func6()
      /__w/teleport/teleport/lib/httplib/httplib.go:128 +0xa5
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf82
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:296 +0xe8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:147 +0xe1
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:109 +0xd2
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.instrumentHTTPHandlerWithPrometheus.InstrumentHandlerInFlight.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:60 +0x104
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:422 +0x61
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:837 +0xa0c
  github.com/gravitational/teleport/lib/limiter/internal/ratelimit.(*TokenLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/internal/ratelimit/ratelimit.go:106 +0x301
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/limiter.go:82 +0x53
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:105 +0x27e
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:3301 +0x2a1
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:2102 +0x1304
  net/http.(*Server).Serve.gowrap3()
      /opt/go/src/net/http/server.go:3454 +0x4f
==================
==================
WARNING: DATA RACE
Write at 0x00c0036a2540 by goroutine 94763:
  context.(*cancelCtx).cancel()
      /opt/go/src/context/context.go:553 +0x138
  context.WithCancelCause.func1()
      /opt/go/src/context/context.go:270 +0x5d
  github.com/gravitational/teleport/lib/kube/proxy.(*clusterSession).close()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:2389 +0xa1
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.deferwrap3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1679 +0x1f
  runtime.deferreturn()
      /opt/go/src/runtime/panic.go:610 +0x5d
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1735 +0x4bd
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).AddParticipant()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:194 +0x4cf
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1000 +0x997
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1729 +0x3b7
  github.com/gravitational/teleport/lib/kube/proxy.(*session).trackSession()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1438 +0x88d
  github.com/gravitational/teleport/lib/kube/proxy.newSession()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:511 +0x1e17
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec.func3()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1723 +0x2fb
  github.com/gravitational/teleport/lib/kube/proxy.upgradeRequestToRemoteCommandProxy()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:120 +0x444
  k8s.io/apimachinery/pkg/util/httpstream/spdy.responseUpgrader.UpgradeResponse()
      /go/pkg/mod/k8s.io/apimachinery@v0.33.2/pkg/util/httpstream/spdy/upgrade.go:104 +0x4e6
  github.com/gravitational/teleport/lib/kube/proxy.createSPDYStreams()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:145 +0x250
  github.com/gravitational/teleport/lib/kube/proxy.upgradeRequestToRemoteCommandProxy()
      /__w/teleport/teleport/lib/kube/proxy/remotecommand.go:109 +0x9c
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:1708 +0x1964
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).exec-fm()
      <autogenerated>:1 +0xa5
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuth.func1()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:679 +0x7ec
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).withAuth.MakeHandlerWithErrorWriter.func2()
      /__w/teleport/teleport/lib/httplib/httplib.go:128 +0xa5
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf82
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:296 +0xe8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:147 +0xe1
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:109 +0xd2
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.instrumentHTTPHandlerWithPrometheus.InstrumentHandlerInFlight.func1()
      /go/pkg/mod/github.com/prometheus/client_golang@v1.22.0/prometheus/promhttp/instrument_server.go:60 +0x104
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:422 +0x61
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:837 +0xa0c
  github.com/gravitational/teleport/lib/limiter/internal/ratelimit.(*TokenLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/internal/ratelimit/ratelimit.go:106 +0x301
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*ConnectionsLimiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/connlimiter.go:82 +0x37a
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      /__w/teleport/teleport/lib/limiter/limiter.go:82 +0x53
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:105 +0x27e
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:179 +0x1a97
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.60.0/handler.go:67 +0x67
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2294 +0x47
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:3301 +0x2a1
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:2102 +0x1304
  net/http.(*Server).Serve.gowrap3()
      /opt/go/src/net/http/server.go:3454 +0x4f

Previous write at 0x00c0036a2540 by goroutine 94911:
  context.withCancel()
      /opt/go/src/context/context.go:277 +0x53
  context.WithCancelCause()
      /opt/go/src/context/context.go:269 +0x26
  github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).getExecutor.func1()
      /__w/teleport/teleport/lib/kube/proxy/forwarder.go:2225 +0x1a5
  k8s.io/client-go/tools/remotecommand.(*FallbackExecutor).StreamWithContext()
      /go/pkg/mod/k8s.io/client-go@v0.33.2/tools/remotecommand/fallback.go:55 +0x138
  github.com/gravitational/teleport/lib/kube/proxy.(*session).launch()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:719 +0x27b6
  github.com/gravitational/teleport/lib/srv.(*SessionTracker).UpdateState()
      /__w/teleport/teleport/lib/srv/sessiontracker.go:240 +0x402
  github.com/gravitational/teleport/lib/kube/proxy.(*session).launch()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:687 +0x21b0
  github.com/gravitational/teleport/lib/kube/proxy.(*session).join.func3()
      /__w/teleport/teleport/lib/kube/proxy/sess.go:1105 +0x47

Goroutine 94763 (running) created at:
  net/http.(*Server).Serve()
      /opt/go/src/net/http/server.go:3454 +0x8c9
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).Serve()
      /__w/teleport/teleport/lib/kube/proxy/server.go:393 +0x9b1
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint.func19()
      /__w/teleport/teleport/lib/service/service.go:5460 +0x3fb
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:582 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:308 +0x4ba

==================
```

### PR DESCRIPTION
**Pull request by rana**
Fixes #56780

Fixes a race condition in kube `clusterSession` related to `connMonitorCancel`. `getExecutor()`'s `NewFallbackExecutor` wrote to `connMonitorCancel`, while `close()` read.

This solution separates session lifecycle from the connection attempt lifecycle. There may be multiple connection attempts within a session using `FallbackExecutor` and `FallbackDialer`.

- Added a connection context deriving from the session in `monitorConn()` 

---
#### Notes

Stack trace shown in #56780 appears to be for `branch/v18` at commit `42d2639f7e`.
```zsh
git switch -C branch/v18 42d2639f7e
```

### CODE REVIEW

File: lib/kube/proxy/forwarder.go [hunk 1]
```diff
@@ -2387,34 +2383,45 @@ type clusterSession struct {
...
+	// TODO: DELETE
+	// // sessionCtx is the context used to monitor the connection.
+	// sessionCtx context.Context
+	// // connMonitorCancel is the conn monitor connMonitorCancel function.
+	// connMonitorCancel context.CancelCauseFunc
+
+	// sessionCtx is the context used to monitor the connection.
+	sessionCtx context.Context
+	// sessionCancel is the conn monitor sessionCancel function.
+	sessionCancel context.CancelCauseFunc
```
Comment (rosstimothy) [inline lib/kube/proxy/forwarder.go]: Is this left over from debugging the issue?

Comment (rana) [reply lib/kube/proxy/forwarder.go]: Yeah, that's cleanup now.

File: lib/kube/proxy/forwarder.go [hunk 2]
```diff
@@ -2387,34 +2383,38 @@ type clusterSession struct {
 	// rbacSupportedResources is the list of resources that support RBAC for the
 	// current cluster.
 	rbacSupportedResources rbacSupportedResources
-	// connCtx is the context used to monitor the connection.
-	connCtx context.Context
-	// connMonitorCancel is the conn monitor connMonitorCancel function.
-	connMonitorCancel context.CancelCauseFunc
+	// sessionCtx is used with one more connection contexts.
```
Comment (Joerger) [inline lib/kube/proxy/forwarder.go]: nit: Is this supposed to say:
```suggestion
	// sessionCtx is used with one or more connection contexts.
```

**Review by Joerger — APPROVED** [review]

**Review by creack — APPROVED** [review]

**Review by tigrato — APPROVED** [review]
thanks @rana

**Review by rosstimothy — APPROVED** [review]
