### PR TITLE
fix flaky TestDatabaseServerStart

### LINKED ISSUE #46512: `TestDatabaseServerStart` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/10819125736/job/30016292411?pr=45995

#### Relevant snippet

```
    server_test.go:73: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/db/server_test.go:73
        	Error:      	"[DatabaseServer(Name=mongo, Version=17.0.0-dev, Hostname=teleport.cluster.local, HostID=8cb21a80-6894-49e9-a123-0a4f2d18206d, Database=Database(Name=mongo, Type=self-hosted, Labels=map[echo:test])) DatabaseServer(Name=mysql, Version=17.0.0-dev, Hostname=teleport.cluster.local, HostID=8cb21a80-6894-49e9-a123-0a4f2d18206d, Database=Database(Name=mysql, Type=self-hosted, Labels=map[echo:test])) DatabaseServer(Name=postgres, Version=17.0.0-dev, Hostname=teleport.cluster.local, HostID=8cb21a80-6894-49e9-a123-0a4f2d18206d, Database=Database(Name=postgres, Type=self-hosted, Labels=map[echo:test]))]" should have 4 item(s), but has 3
        	Test:       	TestDatabaseServerStart
```

### PR DESCRIPTION
**Pull request by nklaassen**
Got this failure here https://github.com/gravitational/teleport/actions/runs/10819125736/job/30016292411?pr=45995
pretty easy to repro, this seems to fix it

fixes https://github.com/gravitational/teleport/issues/46512

### CODE REVIEW

File: lib/srv/db/server_test.go [hunk 1]
```diff
@@ -68,13 +70,21 @@ func TestDatabaseServerStart(t *testing.T) {
...
 
 	// Make sure servers were announced and their labels updated.
-	servers, err := testCtx.authClient.GetDatabaseServers(ctx, apidefaults.Namespace)
-	require.NoError(t, err)
-	require.Len(t, servers, 4)
-	for _, server := range servers {
-		require.Equal(t, map[string]string{"echo": "test"},
-			server.GetDatabase().GetAllLabels())
-	}
+	retryutils.RetryStaticFor(5*time.Second, 20*time.Millisecond, func() error {
```
Comment (zmb3) [inline lib/srv/db/server_test.go:73]: Any particular reason to use `retryutils` in test code over `EventuallyWithT`?

Comment (nklaassen) [reply lib/srv/db/server_test.go:73]: yeah EventuallyWithT always sleeps, this almost always passes without sleeping

Comment (nklaassen) [reply lib/srv/db/server_test.go:73]: RetryStaticFor is "intended mostly for tests" https://github.com/gravitational/teleport/blob/5292b2bfee0c5cd8f6ab7586c03a3737de2303c4/api/utils/retryutils/retry.go#L221

**Review by greedy52 — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
