### PR TITLE
tsh: skip invalid profiles instead of failing

### LINKED ISSUE #38302: Invalid profiles cause `tsh status` to fail
Expected behavior:
Adding a config file with entries does not break operation of tsh commands, especially those that did not have any configuration applied.

Current behavior:
Adding an aliases section to a new config file results in errors from some commands, the config followed one of the examples from https://goteleport.com/docs/connect-your-client/tsh/#aliases.  When the config contained:
```yaml
aliases:
    "l": "tsh login --auth=okta"
```
Commands such as `tsh login`, `tsh status` returned an error:
```
ERROR REPORT:
Original Error: *trace.BadParameterError key index field Username is not set
Stack Trace:
        github.com/gravitational/teleport/lib/client/interfaces.go:64 github.com/gravitational/teleport/lib/client.KeyIndex.Check
        github.com/gravitational/teleport/lib/client/keystore.go:311 github.com/gravitational/teleport/lib/client.(*FSKeyStore).GetKey
        github.com/gravitational/teleport/lib/client/client_store.go:95 github.com/gravitational/teleport/lib/client.(*Store).GetKey
        github.com/gravitational/teleport/lib/client/client_store.go:166 github.com/gravitational/teleport/lib/client.(*Store).ReadProfileStatus
        github.com/gravitational/teleport/lib/client/client_store.go:226 github.com/gravitational/teleport/lib/client.(*Store).FullProfileStatus
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:3942 github.com/gravitational/teleport/tool/tsh/common.(*CLIConf).FullProfileStatus
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:4295 github.com/gravitational/teleport/tool/tsh/common.onStatus
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1354 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:558 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:24 main.main
        runtime/proc.go:267 runtime.main
        runtime/asm_amd64.s:1650 runtime.goexit
User Message: GetKey with CertOptions requires a fully specified KeyIndex
        key index field Username is not set
```

Bug details:
- Teleport version 14.3.4
- Recreation steps
  1. Create config as mentioned
  2. Run `tsh status`
  3. Observe error

### PR DESCRIPTION
**Pull request by zmb3**
The tsh status command attempts to decode one profile per YAML file in $TSH_HOME. If an error is encountered along the way, the entire command fails and tsh does not display information about any profiles.

An especially confusing corner case is when a user mistakenly places tsh's configuration at $TSH_HOME/config.yaml instead of $TSH_HOME/config/config.yaml. In this case, the config file is assumed to be a profile and the user is presentedc with a confusing error message.

Fix this by skipping over profiles that fail to load but continuing to report on the ones that load successfully.

Closes #38302

changelog: Ensure that tsh continues to function if one of its profiles is invalid.

### CODE REVIEW

**Comment by zmb3** [comment]
@hugoShaka @Joerger PTAL

File: lib/client/client_store.go [hunk 1]
```diff
@@ -230,7 +230,8 @@ func (s *Store) FullProfileStatus() (*ProfileStatus, []*ProfileStatus, error) {
 		}
 		status, err := s.ReadProfileStatus(profileName)
 		if err != nil {
-			return nil, nil, trace.Wrap(err)
+			s.log.WithError(err).Debugf("skipping profile %q due to error", profileName)
```
Comment (hugoShaka) [inline lib/client/client_store.go:233]: should this be a warning? A corrupted profile is a problem and the user might not understand why they cannot log in.

**Review by hugoShaka — APPROVED** [review]

File: lib/client/client_store.go (hunk 1 above)
Comment (zmb3) [reply lib/client/client_store.go:233]: If they cannot log in, then they should get a real error when they try to log in.

No strong preference from my end whether this is a warning or debug. Let me know what you prefer.

**Review by Joerger — APPROVED** [review]
