### PR TITLE
Fix `HeadlessAuthenticationWatcher` race conditions

### LINKED ISSUE #23505: Race in `TestServer_Authenticate_headless`
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4500917721/jobs/7920658061?pr=23228

#### Relevant snippet

```
WARNING: DATA RACE
Read at 0x00c00e1d2be8 by goroutine 39085:
  github.com/gravitational/teleport/api/utils.UTC()
      /__w/teleport/teleport/api/utils/time.go:29 +0x3e
  github.com/gravitational/teleport/api/types.(*Metadata).CheckAndSetDefaults()
      /__w/teleport/teleport/api/types/resource.go:401 +0x104
  github.com/gravitational/teleport/api/types.(*HeadlessAuthentication).CheckAndSetDefaults()
      /__w/teleport/teleport/api/types/headlessauthn.go:26 +0x79
  github.com/gravitational/teleport/lib/services.ValidateHeadlessAuthentication()
      /__w/teleport/teleport/lib/services/headlessauthn.go:32 +0x39
  github.com/gravitational/teleport/lib/auth.(*Server).GetHeadlessAuthentication.func1()
      /__w/teleport/teleport/lib/auth/auth.go:4753 +0x44
  github.com/gravitational/teleport/lib/services/local.(*HeadlessAuthenticationWatcher).Wait()
      /__w/teleport/teleport/lib/services/local/headlessauthn_watcher.go:279 +0x5bc
  github.com/gravitational/teleport/lib/auth.(*Server).GetHeadlessAuthentication()
      /__w/teleport/teleport/lib/auth/auth.go:4752 +0x204
  github.com/gravitational/teleport/lib/auth.TestServer_Authenticate_headless.func1.1()
      /__w/teleport/teleport/lib/auth/auth_login_test.go:718 +0x192

Previous write at 0x00c00e1d2be8 by goroutine 39078:
  github.com/gravitational/teleport/api/utils.UTC()
      /__w/teleport/teleport/api/utils/time.go:34 +0x212
  github.com/gravitational/teleport/api/types.(*Metadata).CheckAndSetDefaults()
      /__w/teleport/teleport/api/types/resource.go:401 +0x104
  github.com/gravitational/teleport/api/types.(*HeadlessAuthentication).CheckAndSetDefaults()
      /__w/teleport/teleport/api/types/headlessauthn.go:26 +0x79
  github.com/gravitational/teleport/lib/services/local.marshalHeadlessAuthenticationToItem()
      /__w/teleport/teleport/lib/services/local/headlessauthn.go:124 +0x47
  github.com/gravitational/teleport/lib/services/local.(*IdentityService).CompareAndSwapHeadlessAuthentication()
      /__w/teleport/teleport/lib/services/local/headlessauthn.go:63 +0x84
  github.com/gravitational/teleport/lib/auth.(*Server).CompareAndSwapHeadlessAuthentication()
      /__w/teleport/teleport/lib/auth/auth.go:4761 +0xe3
  github.com/gravitational/teleport/lib/auth.(*Server).authenticateHeadless()
      /__w/teleport/teleport/lib/auth/methods.go:383 +0x629
  github.com/gravitational/teleport/lib/auth.(*Server).authenticateUser()
      /__w/teleport/teleport/lib/auth/methods.go:208 +0x350
  github.com/gravitational/teleport/lib/auth.(*Server).AuthenticateUser()
      /__w/teleport/teleport/lib/auth/methods.go:118 +0xf0
  github.com/gravitational/teleport/lib/auth.(*Server).AuthenticateSSHUser()
      /__w/teleport/teleport/lib/auth/methods.go:567 +0x1f0
  github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).AuthenticateSSHUser()
      /__w/teleport/teleport/lib/auth/auth_with_roles.go:577 +0x2c7
  github.com/gravitational/teleport/lib/auth.(*APIServer).authenticateSSHUser()
      /__w/teleport/teleport/lib/auth/apiserver.go:495 +0x3ef
  github.com/gravitational/teleport/lib/auth.(*APIServer).authenticateSSHUser-fm()
      <autogenerated>:1 +0xeb
  github.com/gravitational/teleport/lib/auth.(*APIServer).WithAuth.func1()
      /__w/teleport/teleport/lib/auth/apiserver.go:204 +0x5d3
  github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:109 +0xad
  github.com/julienschmidt/httprouter.(*Router).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0xf88
  github.com/gravitational/teleport/lib/httplib.RewritePaths.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:237 +0x1e5
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2122 +0x4d
  github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP()
      /__w/teleport/teleport/lib/auth/middleware.go:663 +0x5d6
  github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 +0x2f8
  github.com/gravitational/teleport/lib/limiter.(*RateLimiter).ServeHTTP()
      <autogenerated>:1 +0x6e
  github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP()
      /go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 +0x48d
  github.com/gravitational/teleport/lib/limiter.(*Limiter).ServeHTTP()
      <autogenerated>:1 +0x84
  github.com/gravitational/teleport/lib/httplib.MakeSecurityHeaderHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:69 +0x75
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2122 +0x4d
  github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1()
      /__w/teleport/teleport/lib/httplib/httplib.go:94 +0x2d8
  net/http.HandlerFunc.ServeHTTP()
      /opt/go/src/net/http/server.go:2122 +0x4d
  go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP()
      /go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.40.0/handler.go:213 +0x1b52
  net/http.serverHandler.ServeHTTP()
      /opt/go/src/net/http/server.go:2936 +0x682
  net/http.(*conn).serve()
      /opt/go/src/net/http/server.go:[1995](https://github.com/gravitational/teleport/actions/runs/4500917721/jobs/7920658061?pr=23228#step:6:1996) +0xbd4
  net/http.(*Server).Serve.func3()
      /opt/go/src/net/http/server.go:3089 +0x58

Goroutine 39085 (running) created at:
  github.com/gravitational/teleport/lib/auth.TestServer_Authenticate_headless.func1()
      /__w/teleport/teleport/lib/auth/auth_login_test.go:715 +0x224
  github.com/gravitational/teleport/lib/auth.TestServer_Authenticate_headless.func7()
      /__w/teleport/teleport/lib/auth/auth_login_test.go:808 +0x862
  testing.tRunner()
      /opt/go/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1629 +0x47

Goroutine 39078 (running) created at:
  net/http.(*Server).Serve()
      /opt/go/src/net/http/server.go:3089 +0x817
  github.com/gravitational/teleport/lib/auth.(*TLSServer).Serve.func2()
      /__w/teleport/teleport/lib/auth/middleware.go:263 +0xaa
```

### PR DESCRIPTION
**Pull request by Joerger**
Fix race conditions in headless authentication watcher that caused flaky tests.

Changes:
 - Update watcher to clone `*types.HeadlessAuthentication` before sending to each associated waiter.
 - Start waiting (and consuming channel) before doing the initial backend check. This way, the initial backend check won't cause the waiter to be marked as stale, but we still won't miss any events during the initial backend check.
 - Rework `TestHeadlessAuthenticationWatcher` to use more stable synchronization techniques.

Tested `TestHeadlessAuthenticationWatcher` and `TestServer_Authenticate_Headless` ~2000 times each without error.

Closes https://github.com/gravitational/teleport/issues/23505

### CODE REVIEW

File: lib/services/local/headlessauthn_watcher.go [hunk 1]
```diff
@@ -203,14 +207,14 @@ func (h *HeadlessAuthenticationWatcher) watch(ctx context.Context) error {
...
 	h.mux.Lock()
 	defer h.mux.Unlock()
-	for _, headlessAuthn := range headlessAuthns {
+	for _, item := range putEvent {
 		for i := range h.waiters {
-			if h.waiters[i].name == headlessAuthn.Metadata.Name {
+			if h.waiters[i].key == string(item.Key) {
 				select {
-				case h.waiters[i].ch <- headlessAuthn:
+				case h.waiters[i].ch <- item:
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:217]: The marshal/unmarshal dance seems a bit strange, I kind of prefer the stronger types we had before.

Would it help/simplify if you did `proto.Clone(headlessAuthn).(*types.HeadlessAuthentication)` before sending the item to the waiter?

File: lib/services/local/headlessauthn_watcher.go [hunk 2]
```diff
@@ -219,33 +223,34 @@ func (h *HeadlessAuthenticationWatcher) notify(headlessAuthns ...*types.Headless
...
 }
 
+type WaitConditionFunc func(*types.HeadlessAuthentication) (bool, error)
+
 // Wait watches for the headless authentication with the given id to be added/updated
 // in the backend, and waits for the given condition to be met, to result in an error,
 // or for the given context to close.
-func (h *HeadlessAuthenticationWatcher) Wait(ctx context.Context, name string, cond func(*types.HeadlessAuthentication) (bool, error)) (*types.HeadlessAuthentication, error) {
+func (h *HeadlessAuthenticationWatcher) Wait(ctx context.Context, name string, cond WaitConditionFunc) (*types.HeadlessAuthentication, error) {
+	var initialBackendCheck = true
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:232]: nit: using `var` for definition is a bit uncommon, use the `:=` shorthand?

```suggestion
	initialBackendCheck := true
```

File: lib/services/local/headlessauthn_watcher.go [hunk 3]
```diff
@@ -219,33 +223,34 @@ func (h *HeadlessAuthenticationWatcher) notify(headlessAuthns ...*types.Headless
 	}
 }
 
+type WaitConditionFunc func(*types.HeadlessAuthentication) (bool, error)
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:226]: What does the bool mean here? Could we add a name to the return params and/or a godoc, so it's clearer?

File: lib/services/local/headlessauthn_watcher.go [hunk 4]
```diff
@@ -219,33 +223,34 @@ func (h *HeadlessAuthenticationWatcher) notify(headlessAuthns ...*types.Headless
...
+
 // Wait watches for the headless authentication with the given id to be added/updated
 // in the backend, and waits for the given condition to be met, to result in an error,
 // or for the given context to close.
-func (h *HeadlessAuthenticationWatcher) Wait(ctx context.Context, name string, cond func(*types.HeadlessAuthentication) (bool, error)) (*types.HeadlessAuthentication, error) {
+func (h *HeadlessAuthenticationWatcher) Wait(ctx context.Context, name string, cond WaitConditionFunc) (*types.HeadlessAuthentication, error) {
+	var initialBackendCheck = true
 	checkBackend := func() (*types.HeadlessAuthentication, bool, error) {
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:233]: Ditto for "what does the bool mean"?

File: lib/services/local/headlessauthn_watcher.go [hunk 5]
```diff
@@ -219,33 +223,34 @@ func (h *HeadlessAuthenticationWatcher) notify(headlessAuthns ...*types.Headless
...
-
 		ok, err := cond(headlessAuthn)
-		if err != nil {
-			return nil, false, trace.Wrap(err)
+		if err == nil && ok {
+			return headlessAuthn, true, nil
 		}
-
-		return headlessAuthn, ok, nil
+		return nil, false, trace.Wrap(err)
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:247]: Maybe:

```go
		return headlessAuthn, ok, trace.Wrap(err)
```

It's not exactly the same, but it's likely alright (and arguably easier to read).

File: lib/services/local/headlessauthn_watcher.go [hunk 6]
```diff
@@ -292,9 +300,13 @@ func (h *HeadlessAuthenticationWatcher) assignWaiter(ctx context.Context, name s
...
 			continue
 		}
-		h.waiters[i].ch = make(chan *types.HeadlessAuthentication)
-		h.waiters[i].name = name
+		h.waiters[i].ch = make(chan backend.Item)
+		h.waiters[i].key = string(headlessAuthenticationKey(name))
 		h.waiters[i].stale = make(chan struct{})
+
+		// initialize waiter as stale to force an initial backend check.
+		close(h.waiters[i].stale)
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:308]: How does the channel "heal" after marked as stale? Does it get assigned a fresh channel? Isn't that racy?

I wonder if making the channel buffered and sending something on it would work instead?

File: lib/auth/auth_login_test.go [hunk 7]
```diff
@@ -800,7 +776,27 @@ func TestServer_Authenticate_headless(t *testing.T) {
 			ctx, cancel := context.WithTimeout(ctx, 2*time.Second)
 			defer cancel()
 
-			errC := updateHeadlessAuthnInGoroutine(ctx, srv, mfa.WebDev.MFA, tc.update)
+			// Start a goroutine to catch the headless authentication attempt and update with test case values.
+			errC := make(chan error)
+			go func() {
+				defer close(errC)
```
Comment (codingllama) [inline lib/auth/auth_login_test.go:782]: nit:

```suggestion
				defer close(errC)

```

File: lib/auth/auth_login_test.go [hunk 8]
```diff
@@ -800,7 +776,27 @@ func TestServer_Authenticate_headless(t *testing.T) {
...
+					errC <- err
+					return
+				}
+
+				// create a shallow copy and update for the compare and swap below.
+				replaceHeadlessAuthn := *headlessAuthn
+				tc.update(&replaceHeadlessAuthn, mfa.WebDev.MFA)
+
+				_, err = srv.Auth().CompareAndSwapHeadlessAuthentication(ctx, headlessAuthn, &replaceHeadlessAuthn)
+				if err != nil {
```
Comment (codingllama) [inline lib/auth/auth_login_test.go:794]: nit:

```suggestion
				if _, err := srv.Auth().CompareAndSwapHeadlessAuthentication(ctx, headlessAuthn, &replaceHeadlessAuthn); err != nil {
```

File: lib/services/local/headlessauthn_watcher_test.go [hunk 9]
```diff
@@ -106,6 +104,8 @@ func TestHeadlessAuthenticationWatcher(t *testing.T) {
 				Item: *item,
 			})
 
+			time.Sleep(100 * time.Millisecond)
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher_test.go:107]: Could you add a comment saying why we need the sleep?

File: lib/services/local/headlessauthn_watcher_test.go [hunk 10]
```diff
@@ -80,12 +81,9 @@ func TestHeadlessAuthenticationWatcher(t *testing.T) {
...
 		firstEventReceivedC = make(chan struct{})
 		go func() {
+			var closeOnce sync.Once
 			headlessAuthn, err := watcher.Wait(waitCtx, name, func(ha *types.HeadlessAuthentication) (bool, error) {
-				select {
-				case <-firstEventReceivedC:
-				default:
-					close(firstEventReceivedC)
-				}
+				closeOnce.Do(func() { close(firstEventReceivedC) })
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher_test.go:86]: Nice.

File: lib/services/local/headlessauthn_watcher_test.go [hunk 11]
```diff
@@ -191,7 +191,7 @@ func TestHeadlessAuthenticationWatcher(t *testing.T) {
 
 		_, err := s.watcher.Wait(waitCtx, pubUUID, func(ha *types.HeadlessAuthentication) (bool, error) { return true, nil })
 		require.Error(t, err)
-		require.Equal(t, waitCtx.Err(), err)
+		require.Equal(t, context.DeadlineExceeded, trace.Unwrap(err))
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher_test.go:194]:
```suggestion
		require.ErrorIs(t, race.Unwrap(err), context.DeadlineExceeded)
```

This should be a bit more resilient to changes. (We might not need the trace.Unwrap, I don't recall now.)

File: lib/services/local/headlessauthn_watcher.go (hunk 3 above)
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:226]: Because this is only used once, and we are in a general-ish package (services/local), I think it was best to declare this directly in the param, as before. Otherwise we are taking a somewhat general type name - WaitConditifionFunc - to something that's very specific to headless authn.

A rename to something more specific could do too, but naming is hard... ;)

**Review by codingllama — COMMENTED** [review]
Thanks, Brian. Always good to see a flaky fix.

I mainly have a question about the switch to backend.Item, but otherwise seems reasonable.

File: lib/services/local/headlessauthn_watcher.go (hunk 5 above)
Comment (Joerger) [reply lib/services/local/headlessauthn_watcher.go:247]: The only issue is that we can have `ok==false` and `headlessAuthn != nil`. Is this alright conventionally?

File: lib/services/local/headlessauthn_watcher.go (hunk 1 above)
Comment (Joerger) [reply lib/services/local/headlessauthn_watcher.go:217]: Yeah that's a fair point, I'll modify it

File: lib/services/local/headlessauthn_watcher.go (hunk 6 above)
Comment (Joerger) [reply lib/services/local/headlessauthn_watcher.go:308]: Right now the stale channel is protected by the watcher's mutex, but I also like the idea of sending to a buffered channel instead.

File: lib/services/local/headlessauthn_watcher_test.go (hunk 11 above)
Comment (Joerger) [reply lib/services/local/headlessauthn_watcher_test.go:194]: :+1:  looks the unwrap is not needed fyi

Comment (codingllama) [reply lib/services/local/headlessauthn_watcher_test.go:194]: Oh, cool. I think trace does errors.Is/errors.As correctly now, but I'm not sure if it was always the case, so I always end up double-checking.

File: lib/services/local/headlessauthn_watcher_test.go (hunk 9 above)
Comment (Joerger) [reply lib/services/local/headlessauthn_watcher_test.go:107]: I'll update this too use custom ticker logic instead of trying to rely on `require.Eventually`. This will make it more efficient and more clear.

**Comment by zmb3** [comment]
@Joerger let's make this top priority Monday, we're seeing lots of data races in CI and I suspect this will improve things.

**Comment by Joerger** [comment]
@codingllama @codingllama Friendly reminder to review

**Comment by codingllama** [comment]
I'm back from easter break today, will review shortly.

File: go.mod [hunk 12]
```diff
@@ -174,6 +174,8 @@ require (
 	github.com/mailgun/minheap v0.0.0-20170619185613-3dbe6c6bf55f // indirect
 )
 
+require github.com/golang/protobuf v1.5.3 // indirect
```
Comment (codingllama) [inline go.mod:177]: Do you mind reverting this change? It's best to keep it in the big indirect block below, with the others.

File: lib/auth/auth_login_test.go [hunk 13]
```diff
@@ -815,7 +811,9 @@ func TestServer_Authenticate_headless(t *testing.T) {
 				},
 				TTL: defaults.CallbackTimeout,
 			})
-			require.NoError(t, <-errC)
+
+			// Use assert so that we also output any test failures below.
+			assert.NoError(t, <-errC)
```
Comment (codingllama) [inline lib/auth/auth_login_test.go:816]: nit: Nit add a message to the assert, so we know what the errors means/where it comes from?

File: lib/services/local/headlessauthn_watcher.go [hunk 14]
```diff
@@ -140,10 +141,10 @@ func (h *HeadlessAuthenticationWatcher) runWatchLoop(ctx context.Context) {
 			h.Log.Debugf("Attempting to restart watch after waiting %v.", t.Sub(startedWaiting))
 			h.retry.Inc()
 		case <-ctx.Done():
-			h.Log.Debug("Context closed, returning from watch loop.")
+			h.Log.Debugf("Context closed with err: %v. returning from watch loop.", ctx.Err())
 			return
 		case <-h.closed:
-			h.Log.Debug("Watcher closed, returning from watch loop.")
+			h.Log.Debug("Watcher closed. returning from watch loop.")
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:147]: nit:

```suggestion
			h.Log.Debug("Watcher closed. Returning from watch loop.")
```

or revert?

File: lib/services/local/headlessauthn_watcher.go [hunk 15]
```diff
@@ -222,63 +222,87 @@ func (h *HeadlessAuthenticationWatcher) notify(headlessAuthns ...*types.Headless
...
+	// With the waiter allocated and the main channel serviced, check the backend for an existing entry.
+	go func() {
+		ha, err := h.identityService.GetHeadlessAuthentication(ctx, name)
+		if trace.IsNotFound(err) {
+			// Ignore not found errors in the initial stale check.
+			return
+		} else if err != nil {
+			conditionErr <- trace.Wrap(err)
+		} else {
+			checkCondition(ha)
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:289]: This makes 3 possible writes to each channel, right? Should we increase the buffer to 3?

File: lib/services/local/headlessauthn_watcher.go [hunk 16]
```diff
@@ -222,63 +222,87 @@ func (h *HeadlessAuthenticationWatcher) notify(headlessAuthns ...*types.Headless
...
 		}
+	}()
+
+	select {
+	case ha := <-conditionMet:
+		return ha, nil
+	case err := <-conditionErr:
+		return nil, trace.Wrap(err)
+	case <-ctx.Done():
+		return nil, ctx.Err()
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:299]: Maybe:

```suggestion
		return nil, trace.Wrap(ctx.Err())
```

File: lib/services/local/headlessauthn_watcher.go [hunk 17]
```diff
@@ -181,7 +182,6 @@ func (h *HeadlessAuthenticationWatcher) watch(ctx context.Context) error {
 
 	// Notify any waiters initiated before the new watcher initialized.
 	h.notify(headlessAuthns...)
-	h.retry.Reset()
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:184]: We don't need the reset anymore? I'm not super familiar with this, so I'm not sure I follow.

File: lib/services/local/headlessauthn_watcher.go [hunk 18]
```diff
@@ -294,7 +318,7 @@ func (h *HeadlessAuthenticationWatcher) assignWaiter(ctx context.Context, name s
 		}
 		h.waiters[i].ch = make(chan *types.HeadlessAuthentication)
 		h.waiters[i].name = name
-		h.waiters[i].stale = make(chan struct{})
+		h.waiters[i].stale = make(chan struct{}, 1)
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:321]:
```suggestion
		h.waiters[i].stale = make(chan struct{}, 1) // buffer required by markStale
```

File: lib/services/local/headlessauthn_watcher_test.go [hunk 19]
```diff
@@ -100,19 +99,39 @@ func TestHeadlessAuthenticationWatcher(t *testing.T) {
...
+		timeoutCtx, timeoutCancel := context.WithTimeout(ctx, 500*time.Millisecond)
+		defer timeoutCancel()
 
+		// We don't know when the waiter will be initialized, so we send
+		// events on each tick until one is received by the waiter.
+		for {
 			select {
+			case <-timeoutCtx.Done():
+				t.Errorf("Watcher never received an event")
+				t.FailNow()
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher_test.go:124]:
```suggestion
				t.Fatal("Watcher never received an event")
```

File: lib/services/local/headlessauthn_watcher.go [hunk 20]
```diff
@@ -222,63 +224,90 @@ func (h *HeadlessAuthenticationWatcher) notify(headlessAuthns ...*types.Headless
 // Wait watches for the headless authentication with the given id to be added/updated
 // in the backend, and waits for the given condition to be met, to result in an error,
 // or for the given context to close.
-func (h *HeadlessAuthenticationWatcher) Wait(ctx context.Context, name string, cond func(*types.HeadlessAuthentication) (bool, error)) (*types.HeadlessAuthentication, error) {
-	checkBackend := func() (*types.HeadlessAuthentication, bool, error) {
-		headlessAuthn, err := h.identityService.GetHeadlessAuthentication(ctx, name)
-		if err != nil {
-			return nil, false, trace.Wrap(err)
+func (h *HeadlessAuthenticationWatcher) Wait(ctx context.Context, name string, cond func(*types.HeadlessAuthentication) (ok bool, err error)) (*types.HeadlessAuthentication, error) {
+	bufferSize := 3 // one for each of the "main", "stale", and "initial backend check" goroutines.
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:228]: nit: const?

```suggestion
	const bufferSize = 3 // one for each of the "main", "stale", and "initial backend check" goroutines.
```

File: go.mod [hunk 21]
```diff
@@ -140,6 +140,7 @@ require (
 	golang.org/x/sys v0.6.0
 	golang.org/x/term v0.6.0
 	golang.org/x/text v0.8.0
+	golang.org/x/time v0.3.0
```
Comment (codingllama) [inline go.mod:143]: I don't see a related import in your changes, so this seems a bit unexpected. Outdated e_imports.go maybe?

**Review by codingllama — APPROVED** [review]
Thanks again, Brian!

File: lib/services/local/headlessauthn_watcher.go [hunk 22]
```diff
@@ -222,63 +224,90 @@ func (h *HeadlessAuthenticationWatcher) notify(headlessAuthns ...*types.Headless
...
-			return nil, ctx.Err()
-		case <-h.closed:
-			return nil, watcherClosedErr
+			return
+		}
+	}()
+
+	// With the waiter allocated and the main channel serviced, check the backend for an existing entry.
+	wg.Add(1)
+	go func() {
```
Comment (AntonAM) [inline lib/services/local/headlessauthn_watcher.go:285]: It seems we depend here on goroutines to run in order they are created in code, which I think is not guaranteed on multi-core machines. Don't know how much realistically this is a problem here though.

File: lib/auth/methods.go [hunk 23]
```diff
@@ -347,20 +347,16 @@ func (s *Server) authenticateHeadless(ctx context.Context, req AuthenticateUserR
...
-	headlessAuthn.SetExpiry(s.clock.Now().Add(defaults.CallbackTimeout))
+	expires := s.clock.Now().Add(defaults.CallbackTimeout)
+	headlessAuthn, err := types.NewHeadlessAuthenticationStub(req.HeadlessAuthenticationID, expires)
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
 
+	headlessAuthn.User = req.Username
+	headlessAuthn.PublicKey = req.PublicKey
+	headlessAuthn.ClientIpAddress = req.ClientMetadata.RemoteAddr
```
Comment (AntonAM) [inline lib/auth/methods.go:359]: nit: `ClientIPAddress`

Even better would be to rename this field to `ClientLoginIP`. But I see this field wasn't added in this PR.

**Review by AntonAM — APPROVED** [review]

File: lib/services/local/headlessauthn_watcher.go (hunk 22 above)
Comment (Joerger) [reply lib/services/local/headlessauthn_watcher.go:285]: In this case we don't really need to wait until the first goroutine starts, I've removed this part of the comment. Thanks for catching this.

File: lib/auth/methods.go (hunk 23 above)
Comment (Joerger) [reply lib/auth/methods.go:359]: As we are moving away from gogoproto, we are aiming to stick to the Protobuf best practices, including [using `snake_case` for proto fields](https://protobuf.dev/programming-guides/style/#message-field-names). There is no special case for names like `id` or `ip`, so unfortunately we get this result.
