### PR TITLE
Fix flaky `TestInitDatabaseService/enabled_invalid_databases`

### LINKED ISSUE #42963: `TestInitDatabaseService/enabled_invalid_databases` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/9514256517/job/26226076225#step:6:1579
- https://github.com/gravitational/teleport/actions/runs/9514855486/job/26227882953#step:6:1578

#### Relevant snippet

```
    service_test.go:1807: 
        	Error Trace:	/__w/teleport/teleport/lib/service/service_test.go:1807
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestInitDatabaseService/enabled_invalid_databases
```

### PR DESCRIPTION
**Pull request by hugoShaka**
Fixes the flaky test https://github.com/gravitational/teleport.e/actions/runs/12580662865/job/35063002827#step:7:598

Explanation:
- when an event is broadcast, we update the `Supervisor.events` map, if there was already an event with the same name, we override it. Last event wins.
- when `Supervisor.WaitForEvent` is invoked, it looks at `events[name]` and immediately returns the event value if not empty
- the test is waiting for "service exit in error" event
- after the DB service fails, the supervisor cancels the context, every service exits with ContextCancelledErr (which also emits a "service exit in error" event)
- if the test routine is not fast enough, it will miss the "db.init" event and will get one from another service, once we miss the event, we can't recover it

The fix is to create an event listener before starting the sevrices, so it can't miss any event, and look at the first failure instead of the last one.

Fixes: https://github.com/gravitational/teleport/issues/42963

### CODE REVIEW

File: lib/service/service_test.go [hunk 1]
```diff
@@ -1828,15 +1828,21 @@ func TestInitDatabaseService(t *testing.T) {
 			ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
 			defer cancel()
 
+			// Arbitrary channel size to avoid blocking.
+			// We should not receive more than 102 events as we have less than 1024 services.
```
Comment (zmb3) [inline lib/service/service_test.go:1832]:
```suggestion
			// We should not receive more than 1024 events as we have less than 1024 services.
```

**Review by zmb3 — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]

**Comment by hugoShaka** [comment]
> /excludeflake TestInitDatabaseService

The panic seems caused by a new race I introduced: I'm closing the channel while the supervisor is still trying to send events. I thought teleport would be stopped after waiting the errgroup but I was wrong.

**Comment by hugoShaka** [comment]
Depends on https://github.com/gravitational/teleport/pull/50710 for proper proxy shutdown.
