### PR TITLE
ClusterConfig fallback

### LINKED ISSUE #7623: Error connecting App service - GetClusterNetworkingConfig not implemented
Error when connecting an app service using teleport `v7.0.0-beta.2`. The app starts successfully with `v6.0.1`.

 The auth server is running in eks with server version is 6.2.7, which is why `GetClusterNetworkingConfig` is unimplemented. However `teleport start` should be backwards compatible with `v6` versions of teleport.
```
ERROR REPORT:
Original Error: *trace.NotImplementedError unknown method GetClusterNetworkingConfig for service proto.AuthService
Stack Trace:
	/home/bjoerger/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/client.go:1475 github.com/gravitational/teleport/api/client.(*Client).GetClusterNetworkingConfig
	/home/bjoerger/gravitational/teleport/lib/auth/clt.go:1628 github.com/gravitational/teleport/lib/auth.(*Client).GetClusterNetworkingConfig
	/home/bjoerger/gravitational/teleport/lib/cache/cache.go:1080 github.com/gravitational/teleport/lib/cache.(*Cache).GetClusterNetworkingConfig
	/home/bjoerger/gravitational/teleport/lib/srv/app/server.go:219 github.com/gravitational/teleport/lib/srv/app.New
	/home/bjoerger/gravitational/teleport/lib/service/service.go:3162 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initApps.func1
	/home/bjoerger/gravitational/teleport/lib/service/supervisor.go:457 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	/home/bjoerger/gravitational/teleport/lib/service/supervisor.go:246 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
User Message: unknown method GetClusterNetworkingConfig for service proto.AuthService
```

teleport.yaml:
```
teleport:
  data_dir: /specific/local/dir/
  auth_token: random_app_token
  auth_servers:
  - proxy.example.com:443
app_service:
    enabled: yes
    debug_app: true
    apps:
    - name: "kubernetes-dashboard"
      uri: "http://localhost:8001"
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: "no"
```

### PR DESCRIPTION
**Pull request by Joerger**
`GetClusterAuditConfig`, `GetClusterNetworkingConfig`, and `GetSessionRecordingConfig` now fallback to pulling respective fields from `ClusterConfig` when unimplemented.

Fixes https://github.com/gravitational/teleport/issues/7623

### CODE REVIEW

**Comment by russjones** [comment]
@andrejtokarcik @fspmarshall Can you review? I'd like to get this in 7.0.

**Review by fspmarshall — APPROVED** [review]

File: lib/auth/httpfallback.go [hunk 1]
```diff
@@ -672,3 +672,60 @@ func (c *Client) SetAuthPreference(ctx context.Context, cap types.AuthPreference
...
+	auditConfig, err := c.APIClient.GetClusterAuditConfig(ctx)
+	if err != nil {
+		if !trace.IsNotImplemented(err) {
+			return nil, trace.Wrap(err)
+		}
+	} else {
+		return auditConfig, nil
+	}
+
+	cfg, err := c.GetClusterConfig()
```
Comment (andrejtokarcik) [inline lib/auth/httpfallback.go:687]: Not sure whether we care about the `MarshalOption`s anymore but given this data is available we should probably pass it along
```suggestion
	cfg, err := c.GetClusterConfig(opts...)
```
here and below.

**Review by andrejtokarcik — APPROVED** [review]
Full fallback support would also have to involve extending a received `AuthPreference` resource based on `ClusterConfig`, cf. `services.UpdateAuthPreferenceWithLegacyClusterConfig`. Without such additional logic the two fields moved from `ClusterConfig` to `AuthPreference` could be erroneously set to their default value by a client that receives an incomplete `AuthPreference` from a pre-v7 auth server.

Since the `GetAuthPreference` auth API method existed prior to v7, it wouldn't return a `NotImplemented` error like these newly introduced methods, so this situation becomes more difficult to detect. An explicit auth version check would probably need to be applied.

I don't know whether this deserves so much attention though.

**Comment by Joerger** [comment]
@andrejtokarcik I added logic using server version to make `GetAuthPreference` backwards compatible.

Also, once this is merged, will the dynamic configuration resources be fully backwards compatible between an old auth server and new proxy, or are there remaining incompatibilities that you can think of?

File: lib/auth/httpfallback.go [hunk 2]
```diff
@@ -631,24 +632,42 @@ func (c *Client) GetNodes(ctx context.Context, namespace string, opts ...service
...
+		authPref, err = services.UnmarshalAuthPreference(out.Bytes())
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
 	}
 
-	cap, err := services.UnmarshalAuthPreference(out.Bytes())
+	// AuthPreference was updated in 7.0.0 to hold legacy cluster config fields. If the
+	// server version is < 7.0.0, we must update the AuthPreference with the legacy fields.
+	minServerVersion := "7.0.0"
```
Comment (andrejtokarcik) [inline lib/auth/httpfallback.go:652]: FWIW, this will also catch versions like `7.0.0-beta.1` (that already implement the new endpoints) since they are `< 7.0.0` according to the SemVer spec. You might consider moving this workaround https://github.com/gravitational/teleport/blob/b4006bcfc9f30e60def4cd2bb4496a4ba9da9fb4/lib/reversetunnel/srv.go#L1081 to `lib/utils/ver.go` and then using it here as well.

**Review by andrejtokarcik — APPROVED** [review]
@Joerger 
> are there remaining incompatibilities that you can think of?

Similarly to what happened with the `AuthPreference` fields, the field `ClusterID` was moved from `ClusterConfig` to `ClusterName`. However, `ClusterID` is considered quasi-internal so I wouldn't introduce a fallback for it.

File: lib/auth/httpfallback.go (hunk 2 above)
Comment (Joerger) [reply lib/auth/httpfallback.go]: Instead I added `utils.SetVersionBeforeAlpha` and went with the strategy of appending `"-aa"` to the version. This is being reused in a few places and won't need to be deleted.

File: lib/utils/ver.go [hunk 3]
```diff
@@ -17,30 +17,32 @@ limitations under the License.
...
+	"github.com/gravitational/trace"
 )
 
-// CheckVersions compares client and server versions and makes sure that the
-// client version is greater than or equal to the minimum version supported
-// by the server.
-func CheckVersions(clientVersion, minClientVersion string) error {
-	clientSemver, err := semver.NewVersion(clientVersion)
+// CheckVersion compares a version with a minimum version supported.
+// This is used for comparing server-client compatibility in both direction.
```
Comment (andrejtokarcik) [inline lib/utils/ver.go:25]:
```suggestion
// This is used for comparing server-client compatibility in both directions.
```

File: lib/utils/ver.go [hunk 4]
```diff
@@ -17,30 +17,32 @@ limitations under the License.
...
+	if currentSemver.LessThan(*minSemver) {
+		return trace.BadParameter("incompatible versions: %v < %v", currentVersion, minVersion)
 	}
 
 	return nil
 }
+
+// SetVersionBeforeAlpha appends "-aa" to the version so that it comes before <version>-alpha.
+// This ban be used to make version checks work during development.
+func SetVersionBeforeAlpha(version string) string {
```
Comment (andrejtokarcik) [inline lib/utils/ver.go:46]:
```suggestion
// VersionBeforeAlpha appends "-aa" to the version so that it comes before <version>-alpha.
// This can be used to make version checks work during development.
func VersionBeforeAlpha(version string) string {
```

**Review by andrejtokarcik — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.
