### PR TITLE
Fix Flaky test `TestWatchHeadlessAuthentications_usersCanOnlyWatchThemselves`

### LINKED ISSUE #37231: `TestWatchHeadlessAuthentications_usersCanOnlyWatchThemselves/OK_alice_can_filter_for_pending_requests` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/7646332808/job/20834907531

#### Relevant snippet

```
 auth_with_roles_test.go:6740: 
        	Error Trace:	/__w/teleport/teleport/lib/auth/auth_with_roles_test.go:6740
        	Error:      	Not equal: 
        	            	expected: []types.Event{types.Event{Type:1, Resource:(*types.HeadlessAuthentication)(0xc0069748c0)}}
        	            	actual  : []types.Event(nil)
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,43 +1,2 @@
        	            	-([]types.Event) (len=1) {
        	            	- (types.Event) {
        	            	-  Type: (types.OpType) 1,
        	            	-  Resource: (*types.HeadlessAuthentication)({
        	            	-   ResourceHeader: (types.ResourceHeader) {
        	            	-    Kind: (string) (len=23) "headless_authentication",
        	            	-    SubKind: (string) "",
        	            	-    Version: (string) (len=2) "v1",
        	            	-    Metadata: (types.Metadata) {
        	            	-     Name: (string) (len=36) "5ca53940-e7cd-4e21-bbcc-33677be77371",
        	            	-     Namespace: (string) (len=7) "default",
        	            	-     Description: (string) "",
        	            	-     Labels: (map[string]string) <nil>,
        	            	-     Expires: (*time.Time)({
        	            	-      wall: (uint64) 0,
        	            	-      ext: (int64) 63841728206,
        	            	-      loc: (*time.Location)(<nil>)
        	            	-     }),
        	            	-     ID: (int64) 0,
        	            	-     Revision: (string) "",
        	            	-     XXX_NoUnkeyedLiteral: (struct {}) {
        	            	-     },
        	            	-     XXX_unrecognized: ([]uint8) <nil>,
        	            	-     XXX_sizecache: (int32) 0
        	            	-    },
        	            	-    XXX_NoUnkeyedLiteral: (struct {}) {
        	            	-    },
        	            	-    XXX_unrecognized: ([]uint8) <nil>,
        	            	-    XXX_sizecache: (int32) 0
        	            	-   },
        	            	-   User: (string) (len=5) "alice",
        	            	-   PublicKey: ([]uint8) <nil>,
        	            	-   State: (types.HeadlessAuthenticationState) 1,
        	            	-   MfaDevice: (*types.MFADevice)(<nil>),
        	            	-   ClientIpAddress: (string) "",
        	            	-   XXX_NoUnkeyedLiteral: (struct {}) {
        	            	-   },
        	            	-   XXX_unrecognized: ([]uint8) <nil>,
        	            	-   XXX_sizecache: (int32) 0
        	            	-  })
        	            	- }
        	            	-}
        	            	+([]types.Event) <nil>
        	            	 
        	Test:       	TestWatchHeadlessAuthentications_usersCanOnlyWatchThemselves/OK_alice_can_filter_for_pending_requests
{"caller":"keygen/keygen.go:140","component":null,"level":"debug","message":"Generated SSH host certificate for role Instance with principals: [test-server.localhost test-server localhost 127.0.0.1 ::1].","timestamp":"2024-01-24T21:22:29Z"}
{"caller":"tlsca/ca.go:1187","component":"ca","dns_names":[],"key_usage":5,"level":"info","message":"Generating TLS certificate 1.3.9999.1.7=#13096c6f63616c686f7374,1.3.9999.2.11=#13044e6f6465,CN=test-server.localhost,O=Instance,POSTALCODE=null,STREET=","not_after":"2034-01-21T21:22:29Z","timestamp":"2024-01-24T21:22:29Z"}

=== FAIL: lib/auth TestWatchHeadlessAuthentications_usersCanOnlyWatchThemselves (4.50s)
```

### PR DESCRIPTION
**Pull request by Joerger**
Increase the test timeout to avoid flakes, and improve performance to compensate. The test is twice as fast as before despite the longer timeout.

Note: I actually could not reproduce the flake locally even with thousands of concurrent runs, but it seems clear from the code that this timeout was the issue.

Closes https://github.com/gravitational/teleport/issues/37231

### CODE REVIEW

File: lib/auth/auth_with_roles_test.go [hunk 1]
```diff
@@ -6679,8 +6680,12 @@ func TestWatchHeadlessAuthentications_usersCanOnlyWatchThemselves(t *testing.T)
 		},
 	}
 
+	// Initialize headless watcher for each test cases.
 	for _, tc := range testCases {
-		t.Run(tc.name, func(t *testing.T) {
+		tc := tc
+		t.Run(fmt.Sprintf("%v/init_watcher", tc.name), func(t *testing.T) {
```
Comment (zmb3) [inline lib/auth/auth_with_roles_test.go:6686]: The go tool automatically adds a / character for subtests, so by manually adding one here in the name it will end up looking like an extra level of subtest.

**Review by zmb3 — APPROVED** [review]

**Review by Tener — APPROVED** [review]
