### PR TITLE
pgbk: ensure TOASTed values in the change feed

### LINKED ISSUE #29911: Postgres Backend on Azure - Change Feed contantly crashing - ERROR: invalid hexadecimal digit: &#34;-&#34; (SQLSTATE 22023)
Expected behavior:
unclear whats broken and should be expected

Current behavior:
unclear whats actually broken - general working of teleport seems to be OK - but getting constant error about change feed stopping in logs

Bug details:
- Teleport version - 13.3.0
- Recreation steps

Deploy Helm chart on AKS using azure config for postgres and storage backend
using postgres single server in azure

- Debug logs

```
2023-08-02T15:01:33Z INFO [PGBK]      Change feed started. slot_name:da158aeccba74b6591580526fc587072 pgbk/background.go:170
2023-08-02T15:01:39Z WARN [AUTH:1:CA] Re-init the cache on error error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError watcher is closed: &lt;nil&gt;
Stack Trace:
	github.com/gravitational/teleport/lib/cache/cache.go:1158 github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch
	github.com/gravitational/teleport/lib/cache/cache.go:956 github.com/gravitational/teleport/lib/cache.(*Cache).update
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: watcher is closed: &lt;nil&gt;] cache/cache.go:962
2023-08-02T15:01:39Z ERRO [PGBK]      Change feed stream lost. error:[
ERROR REPORT:
Original Error: *pgconn.PgError ERROR: invalid hexadecimal digit: &#34;-&#34; (SQLSTATE 22023)
Stack Trace:
	github.com/gravitational/teleport/lib/backend/pgbk/background.go:263 github.com/gravitational/teleport/lib/backend/pgbk.(*Backend).pollChangeFeed
	github.com/gravitational/teleport/lib/backend/pgbk/background.go:175 github.com/gravitational/teleport/lib/backend/pgbk.(*Backend).runChangeFeed
	github.com/gravitational/teleport/lib/backend/pgbk/background.go:101 github.com/gravitational/teleport/lib/backend/pgbk.(*Backend).backgroundChangeFeed
	github.com/gravitational/teleport/lib/backend/pgbk/pgbk.go:206 github.com/gravitational/teleport/lib/backend/pgbk.NewWithConfig.func2
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: ERROR: invalid hexadecimal digit: &#34;-&#34; (SQLSTATE 22023)] pgbk/background.go:105
2023-08-02T15:01:39Z WARN [PROC:1]    Sync rotation state cycle failed. Retrying in ~10s pid:8.1 service/connect.go:826
2023-08-02T15:01:39Z WARN [KUBERNETE] Re-init the cache on error error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError watcher is closed: rpc error: code = Unknown desc = watcher closed
Stack Trace:
	github.com/gravitational/teleport/lib/cache/cache.go:1158 github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch
	github.com/gravitational/teleport/lib/cache/cache.go:956 github.com/gravitational/teleport/lib/cache.(*Cache).update
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: watcher is closed: rpc error: code = Unknown desc = watcher closed] cache/cache.go:962
2023-08-02T15:01:39Z WARN             Restarting watch on error after waiting 389.200812ms. Error: watcher closed. local/headlessauthn_watcher.go:156
2023-08-02T15:01:40Z WARN [AUTH:1]    Restart watch on error: watcher is closed: <nil>. pid:8.1 resource-kind:lock services/watcher.go:246
2023-08-02T15:01:44Z WARN [KUBERNETE] Restart watch on error: watcher is closed: rpc error: code = Unknown desc = watcher closed. pid:8.1 resource-kind:lock services/watcher.go:246
2023-08-02T15:01:49Z INFO [PGBK]      Starting change feed stream. pgbk/background.go:100
2023-08-02T15:01:49Z INFO [PGBK]      Setting up change feed. slot_name:46d6e54ad7aa4e4f8d8f99e530df1b4e pgbk/background.go:162
```

### PR DESCRIPTION
**Pull request by espadolini**
This PR makes it so that we forcibly update values during `KeepAlive`, because unchanged [TOASTed](https://www.postgresql.org/docs/current/storage-toast.html) values are not stored in the WAL, even at logical level. This can happen when doing `KeepAlive` on a `node` with a lot of labels, for example.

This relies on the planner not being able to see that we are not going to be actually mutating the value; from my tests it seems to work even with a literal `value = value || ''` but we go the extra mile and actually send an always-empty bytestring to concatenate to.

A more stable solution might be to switch to `REPLICA IDENTITY FULL` on the table, but that requires some smarter parsing of the change feed data and comes with some performance drawbacks (as the WAL essentially doubles in volume).

Fixes #29911.

### CODE REVIEW

File: lib/backend/pgbk/pgbk.go [hunk 1]
```diff
@@ -480,9 +480,19 @@ func (b *Backend) DeleteRange(ctx context.Context, startKey []byte, endKey []byt
...
+		// IDENTITY FULL and fill unchanged columns from the identity data; it's
+		// unclear if the benefits of having a more standard solution outweigh
+		// the penalty of essentially doubling the WAL writes for no good
+		// reason, but it might also become useful in the future to have backend
+		// events include the previous state for the item (i.e. it might become
+		// a good reason)
 		tag, err := b.pool.Exec(ctx,
-			"UPDATE kv SET expires = $1, revision = $2 WHERE key = $3 AND (expires IS NULL OR expires > now())",
-			zeronull.Timestamptz(expires.UTC()), revision, lease.Key)
+			"UPDATE kv SET value = value || $1, expires = $2, revision = $3 WHERE key = $4 AND (expires IS NULL OR expires > now())",
```
Comment (Tener) [inline lib/backend/pgbk/pgbk.go:494]: Scary. How sure we can be the planner doesn't get smarter and optimize this one away too?

Comment (espadolini) [reply lib/backend/pgbk/pgbk.go:494]: "Not very", although it would be kind of weird for the prepared statement to special case the empty string as an input parameter. I looked for a "black box" identity function that was guaranteed to not be inspectable by the query planner, but I couldn't find one.

After the work for #29966 (if we decide to go for `REPLICA IDENTITY FULL`) we will be able to drop this.

**Review by xacrimon — APPROVED** [review]

**Review by Tener — APPROVED** [review]
I think this is fine as a stopgap measure before https://github.com/gravitational/teleport/issues/29966 is fully implemented.

**Review by zmb3 — APPROVED** [review]
