### PR TITLE
[Access Lists] Specify blocking relationships on ACL deletion

### LINKED ISSUE #55627: ACL UX Improvement – Provide More Context When Nested Access List Is Still in Use
Image

When cleaning up the Okta integration, the deletion of an access list (e.g., AL1) fails because it is a member of one or more other access lists (e.g., AL2). However, the error message does not indicate which access list(s) AL1 is a member of, making it difficult to resolve the issue—especially in environments with a large number of access lists.

Expected Behavior:

- The error message should explicitly state the names of the access lists that AL1 is a member of (e.g., AL2), so the user can easily locate and remove the nested relationship before deletion.

Actual Behavior:

- The user has to manually search through all access lists to find where AL1 is referenced, which is not scalable or user-friendly.

### Workaround: 
 
The access list parents can be identify by looking at the child access list ``member_of` status spec property: 
```
tctl get access_lists/ef879a5b-56b2-404b-8cd3-6bdba6ef727c --format=json | jq '.[].status'
{
  "owner_of": null,
  "member_of": [
    "aws-readonly-approvers"
  ]
}
 
```

### PR DESCRIPTION
**Pull request by kiosion**
Name blocking `memberOf`/`ownerOf` relationships on Access List deletion, check relationships bidirectionally. Add test coverage for err formatting.

Resolves https://github.com/gravitational/teleport/issues/55627.

See https://github.com/gravitational/teleport/issues/55627#issuecomment-2989160255 – is this context that we want to provide in every case?

### CODE REVIEW

File: lib/services/local/access_list.go [hunk 1]
```diff
@@ -1249,3 +1239,75 @@ func (a *AccessListService) collectionToBackendItemsIter(collection *accesslists
...
+func quoteAndJoin(items []string) string {
+	if len(items) == 0 {
+		return ""
+	}
+
+	quotedItems := make([]string, len(items))
+	for i, item := range items {
+		quotedItems[i] = "'" + item + "'"
+	}
+	return strings.Join(quotedItems, ", ")
```
Comment (kopiczko) [inline lib/services/local/access_list.go:1432]:
```suggestion
	return `"` + strings.Join(items, `", "`) + `"`
```

I also changed to `"` because they feel more natural in Go, but feel free to change back to `'` if you prefer.

File: lib/services/local/access_list.go [hunk 2]
```diff
@@ -1249,3 +1239,75 @@ func (a *AccessListService) collectionToBackendItemsIter(collection *accesslists
...
+				}
+				return trace.Wrap(err, "fetching member for '%s'", memberOf)
+			}
+			if member.Spec.MembershipKind == accesslist.MembershipKindList {
+				memberOfTitles = append(memberOfTitles, parentList.Spec.Title)
+			}
+		}
+		if len(memberOfTitles) > 0 {
+			return trace.AccessDenied("Cannot delete '%s', as it is a member of one or more other Access Lists: %s",
+				accessList.Spec.Title, quoteAndJoin(memberOfTitles))
```
Comment (kopiczko) [inline lib/services/local/access_list.go]: I think it still looks reasonable even with a single title, WDYT?

```suggestion
			return trace.AccessDenied("Cannot delete %q, as it is a member of Access Lists: %s",
				accessList.Spec.Title, quoteAndJoin(memberOfTitles))
```

File: lib/services/local/access_list_test.go [hunk 3]
```diff
@@ -2414,3 +2415,193 @@ func TestInsertAccessListCollection(t *testing.T) {
...
+				relatedTitles[i] = fmt.Sprintf("'%s'", l.Spec.Title)
+			}
+
+			// Err should contain related lists
+			expected := fmt.Sprintf(
+				"Cannot delete '%s', as it is %s of one or more other Access Lists: %s",
+				target.Spec.Title,
+				tc.role,
+				strings.Join(relatedTitles, ", "),
+			)
```
Comment (kopiczko) [inline lib/services/local/access_list_test.go]: I think it basically duplicates the code constructing the error. We can add `tc.expectedErrMsg` and hardcode the expected error message there. I think that would be a better test for error message formatting.

Like 

```
expectedErrMsg: `Cannot delete "child-list", as it is a member of one or more other Access Lists: "parent-list"`
```

Can be argued it'll require changes in many places if the error format changes, but should be a single replace with any half-decent editor.

File: lib/services/local/access_list_test.go [hunk 4]
```diff
@@ -2414,3 +2415,193 @@ func TestInsertAccessListCollection(t *testing.T) {
...
+			case "an owner":
+				for _, owned := range relatedLists {
+					var newOwners []accesslist.Owner
+					for _, o := range owned.Spec.Owners {
+						if o.Name == target.GetName() {
+							continue
+						}
+						newOwners = append(newOwners, o)
+					}
+					owned.Spec.Owners = newOwners
```
Comment (kopiczko) [inline lib/services/local/access_list_test.go]: You can use `strings.DeleteFunc`

File: lib/services/local/access_list_test.go [hunk 5]
```diff
@@ -2414,3 +2415,193 @@ func TestInsertAccessListCollection(t *testing.T) {
...
+	ownerList := newAccessList(t, "owner-list", clock)
+	targetList := newAccessList(t, "target-list", clock)
+
+	_, err = service.UpsertAccessList(ctx, ownerList)
+	require.NoError(t, err)
+	_, err = service.UpsertAccessList(ctx, targetList)
+	require.NoError(t, err)
+
+	targetList, err = service.GetAccessList(ctx, targetList.GetName())
+	require.NoError(t, err)
```
Comment (kopiczko) [inline lib/services/local/access_list_test.go]:
```suggestion
```

Is that needed at all?

File: lib/services/local/access_list_test.go [hunk 6]
```diff
@@ -2414,3 +2415,193 @@ func TestInsertAccessListCollection(t *testing.T) {
...
+	err = service.memberService.WithPrefix(targetList.GetName()).DeleteAllResources(ctx)
+	require.NoError(t, err)
+
+	_, err = service.GetAccessList(ctx, targetList.GetName())
+	require.True(t, trace.IsNotFound(err), "targetList should be deleted")
+
+	ownerListAfterBypass, err := service.GetAccessList(ctx, ownerList.GetName())
+	require.NoError(t, err)
+	require.Contains(t, ownerListAfterBypass.Status.OwnerOf, targetList.GetName(),
+		"ownerList.Status.OwnerOf should contain stale reference to deleted targetList")
```
Comment (kopiczko) [inline lib/services/local/access_list_test.go]: Do we have a mirror test for member_of?

**Review by kopiczko — COMMENTED** [review]
Looks good, mostly minor comments. My suggestion is using `%q` instead of `'%s'`.

I'd only like to verify we have `TestAccessListDeletePrevention_DeletedReferencedLists` equivalent for `member_of` before approving https://github.com/gravitational/teleport/pull/61793#discussion_r2564529027.

File: lib/services/local/access_list_test.go (hunk 5 above)
Comment (kiosion) [reply lib/services/local/access_list_test.go]: nope, shouldn't be...

File: lib/services/local/access_list_test.go (hunk 6 above)
Comment (kiosion) [reply lib/services/local/access_list_test.go]: can add one

File: lib/services/local/access_list_test.go [hunk 7]
```diff
@@ -2414,3 +2415,193 @@ func TestInsertAccessListCollection(t *testing.T) {
...
+	ctx := t.Context()
+	clock := clockwork.NewFakeClock()
+
+	mem, err := memory.New(memory.Config{
+		Context: ctx,
+		Clock:   clock,
+	})
+	require.NoError(t, err)
+
+	service := newAccessListService(t, mem, clock, true /* igsEnabled */)
```
Comment (boxofrad) [inline lib/services/local/access_list_test.go:2680]: nit: Should we move this into the `t.Run` block below, to avoid any accidental cross-case pollution?

File: lib/services/local/access_list_test.go [hunk 8]
```diff
@@ -2414,3 +2415,193 @@ func TestInsertAccessListCollection(t *testing.T) {
...
+			relatedLists := make([]*accesslist.AccessList, 0, len(tc.relatedNames))
+			for _, name := range tc.relatedNames {
+				relatedList, err := service.UpsertAccessList(ctx, newAccessList(t, name, clock))
+				require.NoError(t, err)
+				relatedLists = append(relatedLists, relatedList)
+			}
+
+			// Setup relationships
+			switch tc.role {
+			case "a member":
```
Comment (boxofrad) [inline lib/services/local/access_list_test.go]: I think it might make this test easier to reason about if rather than switching on `role`, we have two separate test tables: one with members, one with owners.

File: lib/services/local/access_list.go [hunk 9]
```diff
@@ -1249,3 +1239,75 @@ func (a *AccessListService) collectionToBackendItemsIter(collection *accesslists
 		}
 	}
 }
+
+// checkDeletionBlockingRelationships checks if the access list has any relationships that would block deletion
+func (a *AccessListService) checkDeletionBlockingRelationships(ctx context.Context, accessList *accesslist.AccessList) error {
+	if len(accessList.Status.MemberOf) > 0 {
```
Comment (boxofrad) [inline lib/services/local/access_list.go]: There's quite a lot of nesting in this method. What do you think of breaking it out into two smaller methods?

```Go
func (a *AccessListService) checkDeletionBlockingRelationships(ctx context.Context, accessList *accesslist.AccessList) error {
  if err := a.checkDeletionMemberRelationships(ctx, accessList); err != nil {
    return trace.Wrap(err)
  }
  if err := a.checkDeletionOwnerRelationships(ctx, accessList); err != nil {
    return trace.Wrap(err)
  }
  return nil
}

func (a *AccessListService) checkDeletionMemberRelationships(ctx context.Context, accessList *accesslist.AccessList) error {
  if len(accessList.Status.MemberOf) == 0 {
    return nil
  }
  // less deeply nested code
```

**Review by boxofrad — APPROVED** [review]
Just a couple of non-blocking/stylistic comments from me 💄

File: lib/services/local/access_list.go (hunk 1 above)
Comment (kiosion) [reply lib/services/local/access_list.go:1432]: I think `"` is better, avoids confusion if apostrophes are present

File: lib/services/local/access_list.go (hunk 2 above)
Comment (kiosion) [reply lib/services/local/access_list.go]: Sure, I'm for shortening it .

File: lib/services/local/access_list_test.go (hunk 3 above)
Comment (kiosion) [reply lib/services/local/access_list_test.go]: hm, I guess, but I saw this from the angle of we're not expecting there to be an issue joining the strings, this is more testing that the correct lists are passed to that error building func in the first place... wdyt?

Comment (kopiczko) [reply lib/services/local/access_list_test.go]: Just to be clear I mean something like this:

```
		{
			name:           "handles formatting multiple member relationships",
  			relationship:   "member",     
			targetName:     "child-list",
			relatedNames:   []string{"parent-list-1", "parent-list-2"},
			expectedErrMsg: `Cannot delete "child-list", as it is a member of one or more other Access Lists: "parent-list-1", "parent-list-2"`,
		},
```

I like it more, but not a blocker. Proceed as you see the fit.

File: lib/services/local/access_list.go (hunk 1 above)
Comment (kopiczko) [reply lib/services/local/access_list.go:1432]: I think the essence of my previous comment was lost. Why not:

```go
func quoteAndJoin(items []string) string {
	if len(items) == 0 {
		return ""
	}
	return `"` + strings.Join(items, `", "`) + `"`
```

There no need to allocate an intermediate array.

File: lib/services/local/access_list_test.go [hunk 10]
```diff
@@ -2414,3 +2415,210 @@ func TestInsertAccessListCollection(t *testing.T) {
...
+			require.NoError(t, err)
+
+			related := make([]*accesslist.AccessList, 0, len(tc.relatedNames))
+			for _, name := range tc.relatedNames {
+				rel, err := service.UpsertAccessList(ctx, newAccessList(t, name, clock))
+				require.NoError(t, err)
+				related = append(related, rel)
+			}
+
+			setup(t, ctx, service, target, related)
```
Comment (kopiczko) [inline lib/services/local/access_list_test.go:2695]: My preference would be to switch on the role instead of passing setup/cleanup funcs. But not a blocker

**Review by kopiczko — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
