### PR TITLE
Fix `tsh` relogin on not found errors

### LINKED ISSUE #25668: tsh join prompts for password when attempting to join a session that doesn't exist
Expected behavior:

If I am already logged in and attempt to join a session that doesn't exist, `tsh` should show an error that the session does not exist.

Current behavior:

Instead, some sort of re-login behavior is triggered and I'm prompted to log in.

If I enter valid credentials, I then see the error I'd expect.

```
tsh login --proxy=proxy.127.0.0.1.nip.io:3080 --auth=local --user=zac2
> Profile URL:        https://proxy.127.0.0.1.nip.io:3080
  Logged in as:       zac2
  Cluster:            zac-local
  Roles:              auditor, editor, moderator, sre-can-join-sessions
  Logins:             ubuntu, debian, zmb
  Kubernetes:         enabled
  Valid until:        2023-05-04 23:41:09 -0600 MDT [valid for 8h0m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy

./build/tsh join --mode moderator ef92e95e-dc73-4b23-9a41-ee5a8c312660
Enter password for Teleport user zac2:
```

### PR DESCRIPTION
**Pull request by Joerger**
Closes https://github.com/gravitational/teleport/issues/25668

### CODE REVIEW

File: lib/client/client_store.go [hunk 1]
```diff
@@ -249,3 +252,11 @@ func LoadKeysToKubeFromStore(profile *profile.Profile, dirPath, teleportCluster,
 	}
 	return kubeCert, privKey, nil
 }
+
+func noCredentialsError(err error) error {
+	return trace.Wrap(err, "no credentials")
+}
+
+func isNoCredentialsError(err error) bool {
+	return strings.Contains(err.Error(), "no credentials")
```
Comment (jakule) [inline lib/client/client_store.go:261]: nit (as it's private): What if `err` is `nil`? 🙈

**Review by jakule — APPROVED** [review]

File: lib/client/client_store.go (hunk 1 above)
Comment (ravicious) [inline lib/client/client_store.go:261]: Should this line first check if `trace.IsNotFound` to avoid a situation where another type of error uses "no credentials" in its error message?

I'm no expert on this but the Go convention of relying solely or the error message instead of something akin to a class/type/variant always seemed a bit reckless to me. 😅 So I don't really know how this class of problems is usually dealt with in Go.

**Review by ravicious — APPROVED** [review]

File: lib/client/client_store.go (hunk 1 above)
Comment (Joerger) [reply lib/client/client_store.go]: Fair point. I've changed it so `errNoCredentials` is the inner `trace.NotFoundError`. This way, we can use `errors.Is(err, errNoCredentials)`, which is more idiomatic for Go.

Comment (Joerger) [reply lib/client/client_store.go]: This should be ok now that it is using `errors.Is` to perform the check.

**Review by rosstimothy — APPROVED** [review]
