### PR TITLE
Move predicate err check earlier, inside RetryWithRelogin

### LINKED ISSUE #13163: Invalid `tsh` queries force a relogin
Expected behavior:

When given an invalid query via the `--query` flag, `tsh` should inform the user that the query is invalid and error out. It should not require the user to log in again.

Current behavior:

Teleport interprets the invalid query error as to mean the user's credentials are expired, and forces the user to log in again. The error from the logs is:

```
Activating relogin on failed to parse predicate expression: ...
```

Teleport version: 9.3.3

### PR DESCRIPTION
**Pull request by kimlisa**
fixes https://github.com/gravitational/teleport/issues/13163

#### Description
In tsh, the list resources `nodes`, `apps`, `dbs`, and `kubes` are wrapped in `RetryWithRelogin`, so before the predicate error reaches the predicate error check, it prompts user to relogin and then shows predicate error. 

`RetryWithRelogin` now aborts the relogin attempt if the error is of type predicate.

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -714,6 +714,10 @@ func RetryWithRelogin(ctx context.Context, tc *TeleportClient, fn func() error)
 		return nil
 	}
 
+	if utils.IsPredicateError(err) {
+		return trace.Wrap(utils.PredicateError{Err: err})
```
Comment (zmb3) [inline lib/client/api.go:718]: If it's already a predicate error, why do you have to wrap it in another predicate error?

Comment (kimlisa) [reply lib/client/api.go:718]: the [IsPredicateError](https://github.com/gravitational/teleport/blob/master/lib/utils/cli.go#L500) looks for keyword in the error to determine if its predicate, then we use a wrapper to add a link to the predicate documentation: 

so if this is the error that returned:
```
failed to parse predicate expression: identifier "la" is not defined
```

it will get formatted to this:
```
ERROR: failed to parse predicate expression: identifier "la" is not defined
Check syntax at https://goteleport.com/docs/setup/reference/predicate-language/#resource-filtering
```

**Review by zmb3 — APPROVED** [review]

**Review by ibeckermayer — APPROVED** [review]

File: lib/client/api.go (hunk 1 above)
Comment (ravicious) [reply lib/client/api.go:725]: It feels to me that `RetryWithRelogin` shouldn't be concerned with doing special stuff with errors that have nothing to do with auth. 🤔

Is there a single place which could wrap the predicate error before `RetryWithRelogin` catches it? Then we could change `IsErrorResolvableWithRelogin` to return `false` for predicate errors and that would be it.

If that's not possible, then perhaps another solution would be to make `IsErrorResolvableWithRelogin` return `false` for predicate errors and then wrap them in specific callsites, as it was done before this PR.
