### PR TITLE
Return the actual IAM errors when configure database IAM policy fails

### LINKED ISSUE #19098: DB Access RDS missing permission unambiguous error
### Details:
During RDS access when Teleport DB agent don't have right permission to auth-configure IAM auththe following error is returned: 
```
2022-12-06T12:40:03Z ERRO [IAM]       Failed to auto-configure IAM for Database(Name=mydatabase, Type=rds, Labels=map[teleport.dev/origin:config-file]). error:[
ERROR REPORT:
Original Error: trace.aggregate expect no placeholders but got [{account_id} {resource_id}]
Stack Trace:
github.com/gravitational/teleport/lib/srv/db/cloud/aws.go:114 github.com/gravitational/teleport/lib/srv/db/cloud.(*awsClient).setupIAM
github.com/gravitational/teleport/lib/srv/db/cloud/iam.go:272 github.com/gravitational/teleport/lib/srv/db/cloud.(*IAM).processTask
github.com/gravitational/teleport/lib/srv/db/cloud/iam.go:121 github.com/gravitational/teleport/lib/srv/db/cloud.(*IAM).Start.func1
runtime/asm_amd64.s:1594 runtime.goexit
User Message: expect no placeholders but got [{account_id} {resource_id}]] cloud/iam.go:123
```

## Expected behaviour 
The error message in that case should be more verbose: the ` no placeholders but got [{account_id} {resource_id}]` error is ambiguous  and hides the root cause why IAM auth setup failed.

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #19098 #19264

In #17635, placeholders are introduced when creating an IAM policy for configuring IAM auth access for corresponding AWS databases. However, turned out that the extra placerholders check added in #17635 hides the actual IAM call error, especially when the agent has no permission to do so.

This change reverts back to return the original error logic as prior to #17635. And it logs a warning message instead when placeholders are detected.

### CODE REVIEW

File: lib/srv/db/cloud/aws.go [hunk 1]
```diff
@@ -196,18 +193,20 @@ func (r *awsClient) ensureIAMPolicy(ctx context.Context) error {
 	if err != nil {
 		return trace.Wrap(err)
 	}
+
+	if len(placeholders) > 0 {
+		r.log.Warnf("Placeholders %q are found when configuring the IAM policy for database %v. Please make sure the database agent has the IAM permissions to fetch cloud metadata, or make sure these values are set in the static config.",
```
Comment (smallinsky) [inline lib/srv/db/cloud/aws.go:198]: I think that the `Placeholders` part is less important that missing IAM permission. Can we swap the sentence and treat the placeholders as a error details nor root cause. Most like the 'placeholders` doesn't mean to much to teleport user.

**Review by smallinsky — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]
