### PR TITLE
Fix 'listener is closed' log spam

### LINKED ISSUE #5568: Log spam
### Description

```
**WARN [DB:SERVIC] Database proxy server exited with error. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError listener is closed
Stack Trace:
	/home/sasha/go/src/github.com/gravitational/teleport/lib/multiplexer/wrappers.go:92 github.com/gravitational/teleport/lib/multiplexer.(*Listener).Accept
	/home/sasha/go/src/github.com/gravitational/teleport/lib/srv/db/proxyserver.go:120 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).Serve
	/home/sasha/go/src/github.com/gravitational/teleport/lib/service/service.go:2736 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint.func9
	/home/sasha/go/src/github.com/gravitational/teleport/lib/service/supervisor.go:457 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	/home/sasha/go/src/github.com/gravitational/teleport/lib/service/supervisor.go:246 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message: listener is closed] service/service.go:2737
```

### PR DESCRIPTION
**Pull request by r0mant**
Closes https://github.com/gravitational/teleport/issues/5568.

### CODE REVIEW

**Review by a-palchikov — APPROVED** [review]

File: lib/srv/db/proxyserver.go [hunk 1]
```diff
@@ -119,7 +119,8 @@ func (s *ProxyServer) Serve(listener net.Listener) error {
 		// The connection is expected to come through via multiplexer.
 		clientConn, err := listener.Accept()
 		if err != nil {
-			if strings.Contains(err.Error(), teleport.UseOfClosedNetworkConnection) {
+			if strings.Contains(err.Error(), teleport.UseOfClosedNetworkConnection) ||
+				strings.Contains(err.Error(), teleport.ListenerIsClosed) {
```
Comment (klizhentas) [inline lib/srv/db/proxyserver.go:123]: seems hacky, I would go the other way - why not create an error compatible type for this problem and use `trace.IsAlreadyClosed` error here, instead of using string submatches

**Review by klizhentas — CHANGES_REQUESTED** [review]

File: lib/srv/db/proxyserver.go (hunk 1 above)
Comment (r0mant) [reply lib/srv/db/proxyserver.go]: @klizhentas Good point, seems like `trace.ConnectionProblem` should cover this as this is what multiplexer returns so no new error type seems to be needed. Updated.

**Review by klizhentas — APPROVED** [review]
