### PR TITLE
Fix issue AWS app access sends requests without path

### LINKED ISSUE #18345: `tsh aws s3 cp` fails with 400
Expected behavior:
`tsh aws s3 cp` should succeed

Current behavior:
```
upload failed: ./LICENSE to s3://steve-teleport-terraform/LICENSE An error occurred (MalformedXML) when calling the PutObject operation: The XML you provided was not well-formed or did not validate against our published schema
```

Bug details:
- Teleport version: master
- Recreation steps: `tsh aws s3 cp`
- Debug logs
With recent https://github.com/gravitational/oxy change, path/query info is no longer available in `r.URL.Opaque`
https://github.com/gravitational/teleport/blob/42dde44e1b2cacbe924d97c20e92163ea7bbe265/lib/srv/app/aws/handler.go#L202-L213

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #18345 
- #18345

Introduced by https://github.com/gravitational/oxy/pull/8, but luckily only one release (10.3.6) is affected so far.

Root cause is AWS app access was relying on `r.URL.Opaque` for request URI but the new oxy upstream fix changed this behaviour. 

This change applies a fix that is similar to regular app access:
https://github.com/gravitational/teleport/blob/2868069924786c8ec0754fa176fce86081ae4dc8/lib/srv/app/transport.go#L169-L179

Testing:
- `tsh aws s3 ls`
- `tsh aws s3 cp <file> <s3://path>`
- `tsh aws --endpoint-url ssm start-session --target <target>`
- `tsh aws --endpoint-url dynamodb list-tables`
- `tsh aws  dynamodb list-tables`
- `tsh proxy aws -p 8888` with `terraform apply`

### CODE REVIEW

**Review by mdwn — APPROVED** [review]

File: lib/srv/app/aws/handler_test.go [hunk 1]
```diff
@@ -157,6 +159,50 @@ func TestAWSSignerHandler(t *testing.T) {
...
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			actualURL, err := urlForResolvedEndpoint(test.inputReq, test.inputResolvedEnpoint)
+			require.Equal(t, test.expectURL, actualURL)
+			test.requireError(t, err)
+		})
+	}
+}
+
+func mustNewRequest(t testing.TB, method, url string, body io.Reader) *http.Request {
```
Comment (smallinsky) [inline lib/srv/app/aws/handler_test.go:198]: nit: Just for consistency - at first glance it might be a bit confused why  TB interface is used instead of where as all function in this file operates on `*testing.T` object. 
```suggestion
func mustNewRequest(t testing.T, method, url string, body io.Reader) *http.Request {
```

**Review by smallinsky — APPROVED** [review]

File: lib/srv/app/aws/handler_test.go (hunk 1 above)
Comment (greedy52) [reply lib/srv/app/aws/handler_test.go:198]: I can revert but i really think we should start doing `testing.TB` more often. It took me a really long time to write a `BenchmarkXXX` (for a different issue) to convert all our suite setup functions to work with `testing.B`.
