### PR TITLE
Fix `tcp scp` getting stuck in symlink loops

### LINKED ISSUE #23919: `tsh scp` can get stuck traversing recursive symlinks forever
Expected behavior:

When recursively copying directories, `tsh scp` will always terminate after copying each file only once.

Current behavior:

While traversing directories, if a symbolic link is found that points to a directory that was already traversed, `tsh scp` will continually transfer files forever in an endless loop.

### PR DESCRIPTION
**Pull request by atburke**
This change fixes `tsh scp` to no longer get caught in symlink loops and repeatedly copy files. When a loop is detected, Teleport logs it and skips traversing that path.

Fixes #23919.

Changelog: Fixed tsh scp getting stuck in symlink loops

### CODE REVIEW

File: lib/sshutils/sftp/local.go [hunk 1]
```diff
@@ -142,3 +142,14 @@ func (l localFS) Readlink(name string) (string, error) {
 func (l localFS) Getwd() (string, error) {
 	return os.Getwd()
 }
+
+func (l localFS) RealPath(path string) (string, error) {
+	if !filepath.IsAbs(path) {
+		wd, err := l.Getwd()
```
Comment (capnspacehook) [inline lib/sshutils/sftp/local.go]: Any reason we can't use `filepath.Abs` instead which does this and also cleans the path?

File: lib/sshutils/sftp/sftp_test.go [hunk 2]
```diff
@@ -633,6 +633,84 @@ func TestCopyingSymlinkedFile(t *testing.T) {
...
+
+			cfg, err := CreateDownloadConfig(tc.srcDir, dstDir, Options{Recursive: true})
+			require.NoError(t, err)
+			// use all local filesystems to avoid SSH overhead
+			srcFS := &mockFS{fileAccesses: make(map[string]int)}
+			cfg.srcFS = srcFS
+			require.NoError(t, cfg.initFS(nil))
+			require.NoError(t, cfg.transfer(t.Context()))
+
+			fmt.Println(srcFS.fileAccesses)
```
Comment (capnspacehook) [inline lib/sshutils/sftp/sftp_test.go]: Nit: use `t.Log`

File: lib/sshutils/sftp/sftp_test.go [hunk 3]
```diff
@@ -633,6 +633,84 @@ func TestCopyingSymlinkedFile(t *testing.T) {
 	checkTransfer(t, false, dstPath, linkPath)
 }
 
+type mockFS struct {
+	localFS
+	fileAccesses map[string]int
+}
+
+func (m *mockFS) Open(path string) (File, error) {
+	realPath, err := filepath.EvalSymlinks(path)
```
Comment (capnspacehook) [inline lib/sshutils/sftp/sftp_test.go:642]: Why is this here, is it required for the test to pass? If so it seems strange to me that the test won't pass with a standard localFS, as `transferDir` should be called which should call `Realpath` and do symlink loop detection

**Review by capnspacehook — APPROVED** [review]
Few mostly minor comments, looks good overall

File: lib/sshutils/sftp/sftp_test.go (hunk 3 above)
Comment (atburke) [reply lib/sshutils/sftp/sftp_test.go:642]: localFS works fine here, but I want to count how many times each file is opened so we can confirm that files aren't being copied repeatedly. `EvalSymlinks` here is only used for storing the counts, the unchanged path is passed to the underlying Open call.

**Comment by atburke** [comment]
Friendly ping @gzdunek and/or @timothyb89

File: lib/sshutils/sftp/sftp.go [hunk 4]
```diff
@@ -561,10 +564,19 @@ func (c *Config) transfer(ctx context.Context) error {
 }
 
 // transferDir transfers a directory
-func (c *Config) transferDir(ctx context.Context, dstPath, srcPath string, srcFileInfo os.FileInfo) error {
+func (c *Config) transferDir(ctx context.Context, dstPath, srcPath string, srcFileInfo os.FileInfo, visited map[string]struct{}) error {
+	realSrcPath, err := c.srcFS.RealPath(srcPath)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	if _, ok := visited[realSrcPath]; ok {
```
Comment (eriktate) [inline lib/sshutils/sftp/sftp.go:580]:
```suggestion
	if visited == nil {
		visited = make(map[string]struct{})
	}
	if _, ok := visited[realSrcPath]; ok {
```
Any reason not to automatically initialize `visited` if we're passed a `nil`? That way callers don't have to allocate an empty map and we shouldn't ever end up with a surprise panic on line 576

**Review by eriktate — APPROVED** [review]
Looks good! Left one comment but it's up to you whether or not it's worth doing :+1:
