### PR TITLE
Fix flaky test `TestChaosUpload`

### LINKED ISSUE #33099: `TestChaosUpload` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/6436546168/job/17480093775

#### Relevant snippet

```
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording 95c94596-9c0d-4579-ba78-c1e079ee3c34.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:460","component":"upload","error":"failed to create stream","level":"warning","message":"Upload failed.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording 95c94596-9c0d-4579-ba78-c1e079ee3c34.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording a120e7cc-28b2-47a9-98b1-e47bb627fb12.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording a120e7cc-28b2-47a9-98b1-e47bb627fb12.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording bc9852b4-2f15-484e-9ed2-95f721529d00.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording bc9852b4-2f15-484e-9ed2-95f721529d00.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording 95c94596-9c0d-4579-ba78-c1e079ee3c34.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
{"caller":"filesessions/fileasync.go:283","component":"upload","level":"debug","message":"Scan is skipping recording d49505b5-4e36-4d0d-a7a2-b967ecf8a068.tar that is locked by another process.","timestamp":"2023-10-06T21:17:11Z"}
    fileasync_chaos_test.go:182: 
        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/fileasync_chaos_test.go:182
        	Error:      	Received unexpected error:
        	            	could not acquire file lock for "/tmp/TestChaosUpload1617912356/001/95c94596-9c0d-4579-ba78-c1e079ee3c34.tar"
        	            		could not acquire lock on the file at this time
        	Test:       	TestChaosUpload
```

### PR DESCRIPTION
**Pull request by Joerger**
Change:
- Make the test run magnitudes faster and allow the --race flag. 
  - From my local testing, it doesn't not seem like the slow scan period was not warranted and may have just been covering up underlying issues with the test. That may change after seeing CI run it.
- Don't treat empty uploads as a `sessionError` in `uploadEncrypted`, mirroring the default `upload` method.
  - It's unclear whether this should actually be working this way in either case. We have had issues in the [recent past](https://github.com/gravitational/teleport/pull/60891) where recordings are truncated and never cleaned up - e.g. moved to the corrupted folder with an `.error` file if relevant. However, this can be handled in a follow up PR if the legacy behavior is deemed undesirable rather than blocking this high priority flaky test fix.
- Add a missing FS unlock when `uploadEncrypted` hits an unexpected error. This flake appeared once ^ was fixed.

Closes https://github.com/gravitational/teleport/issues/33099

### CODE REVIEW

**Review by Tener — APPROVED** [review]

File: lib/events/filesessions/fileasync.go [hunk 1]
```diff
@@ -588,6 +588,7 @@ func (u *Uploader) startUpload(ctx context.Context, fileName string) (err error)
 				Error:     err,
 				Created:   u.cfg.Clock.Now().UTC(),
 			})
+			upload.Close()
```
Comment (zmb3) [inline lib/events/filesessions/fileasync.go]: Should we defer the close? Are there any circumstances in which we _do not_ want to close the upload prior to returning?

Comment (Joerger) [reply lib/events/filesessions/fileasync.go]: The upload is done in a [goroutine](https://github.com/gravitational/teleport/blob/59ac781d8d7e6eebf5cd5b91e8f0f593df2ae048/lib/events/filesessions/fileasync.go#L615) so we can only close the upload here (deferred or otherwise) when the upload fails early.

Comment (Joerger) [reply lib/events/filesessions/fileasync.go]: Nevermind, changed to a defer with an error check - af921c2229c2cfac27eb443c9f063bacf200bb11

File: lib/events/filesessions/fileasync.go [hunk 2]
```diff
@@ -581,6 +581,14 @@ func (u *Uploader) startUpload(ctx context.Context, fileName string) (err error)
 		reader:       nil,
 	}
 
+	defer func() {
+		if err != nil {
```
Comment (tigrato) [inline lib/events/filesessions/fileasync.go:588]: I can see people removing the err check here and causing the upload function to fail a lot

Comment (Joerger) [reply lib/events/filesessions/fileasync.go:588]: This will cause the upload to fail which is easily caught by unit tests. That said, we do this type of err-check-defer quite a bit and can definitely see how it might be an anti-pattern, so I don't have a strong opinion on keeping it.

Comment (tigrato) [reply lib/events/filesessions/fileasync.go:588]: Add a comment explaining the intent here and under which conditions this cleanup should occur.

Alternatively, you could wrap the close call in a function guarded by sync.Once. If you trigger the sync.Once with a no-op before reaching wg.Go, the close won’t run in that path, but it will run in all other cases through the defer.

Unsure what's best here

Comment (Joerger) [reply lib/events/filesessions/fileasync.go:588]: Added a comment 8ff08e1178aa5214d6a86456fddf695d33987c28

**Comment by Joerger** [comment]
@rosstimothy @zmb3 Can you give this a flaky test skip? Looks like it's just timing out, takes just under 6s locally:

```
> go test -run ^TestChaosUpload$ github.com/gravitational/teleport/lib/events/filesessions -tags=libfido2,piv --count=1 --race              
ok  	github.com/gravitational/teleport/lib/events/filesessions	5.515s
```

**Review by rosstimothy — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

File: lib/events/filesessions/fileasync_chaos_test.go
Comment (ravicious) [inline lib/events/filesessions/fileasync_chaos_test.go:1]: Is it feasible to backport these changes to v17? I just got [a hit on v17](https://github.com/gravitational/teleport/actions/runs/21688436803/job/62541673585#step:6:992). I tried backporting this PR myself, but it doesn't backport cleanly.
