### PR TITLE
Fix tsh player issues

### LINKED ISSUE #11479: Race condition in tsh play
I was looking at the code in lib/client/player.go and suspected that we may have a data race, since `waitUntil()` is just polling a variable that's updated by another goroutine without any synchronization.

I built tsh with the race detector enabled and tried to playback a session, and sure enough, the race detector tripped.

```
WARNING: DATA RACE
Write at 0x00c00023d910 by goroutine 56:
  github.com/gravitational/teleport/lib/client.(*sessionPlayer).Stop()
      /Users/zmb/teleport/lib/client/player.go:69 +0x98
  github.com/gravitational/teleport/lib/client.(*sessionPlayer).playRange.func2()
      /Users/zmb/teleport/lib/client/player.go:218 +0x5fc

Previous read at 0x00c00023d910 by main goroutine:
  github.com/gravitational/teleport/lib/client.playSession()
      /Users/zmb/teleport/lib/client/api.go:3578 +0x530
  github.com/gravitational/teleport/lib/client.(*TeleportClient).Play()
      /Users/zmb/teleport/lib/client/api.go:1658 +0x43c
  main.onPlay()
      /Users/zmb/teleport/tool/tsh/tsh.go:822 +0x650
  main.Run()
      /Users/zmb/teleport/tool/tsh/tsh.go:712 +0x1a8dc
  main.main()
      /Users/zmb/teleport/tool/tsh/tsh.go:337 +0x2dc

Goroutine 56 (running) created at:
  github.com/gravitational/teleport/lib/client.(*sessionPlayer).playRange()
      /Users/zmb/teleport/lib/client/player.go:183 +0x268
  github.com/gravitational/teleport/lib/client.(*sessionPlayer).Play()
      /Users/zmb/teleport/lib/client/player.go:61 +0x528
  github.com/gravitational/teleport/lib/client.playSession()
      /Users/zmb/teleport/lib/client/api.go:3575 +0x518
  github.com/gravitational/teleport/lib/client.(*TeleportClient).Play()
      /Users/zmb/teleport/lib/client/api.go:1658 +0x43c
  main.onPlay()
      /Users/zmb/teleport/tool/tsh/tsh.go:822 +0x650
  main.Run()
      /Users/zmb/teleport/tool/tsh/tsh.go:712 +0x1a8dc
  main.main()
      /Users/zmb/teleport/tool/tsh/tsh.go:337 +0x2dc
==================
Found 1 data race(s)
```

This code is 5+ years old, so I suspect it has always been an issue and we just have no test coverage for SSH session playback.

### PR DESCRIPTION
**Pull request by zmb3**
This commit fixes race conditions in the tsh session player by using
a condition variable to detect state changes rather than unsafely
polling a variable that is written by a separate goroutine.

In addition, fix an off by one error when resuming playback
after pausing. The player's position variable has always stored
the index of the last succesfully played event, so when we resume
playback we should start at position+1 to not re-play the previous
event twice.

Fixes #11479

### CODE REVIEW

File: lib/client/player.go [hunk 1]
```diff
@@ -215,7 +238,30 @@ func (p *sessionPlayer) playRange(from, to int) {
 		}
 		// played last event?
 		if i == len(p.sessionEvents) {
-			p.Stop()
+			// we defer here so the stop notification happens after the deferred final state update
+			defer p.stopOnce.Do(func() { close(p.stopC) })
```
Comment (nklaassen) [inline lib/client/player.go:242]: I'm pretty sure defers are LIFO so wouldn't this still happen first?

File: lib/client/player.go [hunk 2]
```diff
@@ -215,7 +238,30 @@ func (p *sessionPlayer) playRange(from, to int) {
 		}
```
Comment (nklaassen) [inline lib/client/player.go:238]: looks like the write to `p.position` on the line above (gh won't let me comment there) is still unsynchronized

File: lib/client/player.go [hunk 3]
```diff
@@ -146,56 +180,45 @@ func timestampFrame(term *terminal.Terminal, message string) {
...
-			}
-			if delay > 1000 {
-				delay = 1000
-			}
-			timestampFrame(p.term, e.GetString("time"))
-			time.Sleep(time.Millisecond * delay)
-		}
-		prev = ms
-	}
+	// os.Stdout.Write([]byte("\x1bc"))
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/client/player.go:192]: oops, good catch. It needs to stay but I had to comment it out during some manual testing.

File: lib/client/player.go [hunk 4]
```diff
@@ -215,7 +238,30 @@ func (p *sessionPlayer) playRange(from, to int) {
...
+		delay = 250 * time.Millisecond
+	case delay > 500*time.Millisecond && delay < 1*time.Second:
+		delay = 500 * time.Millisecond
+	case delay > time.Second:
+		delay = time.Second
+	}
+
+	timestampFrame(p.term, e.GetString("time"))
+	p.clock.Sleep(delay)
+	*previousTimestamp = eventTime
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/client/player.go:266]: I had the same thought. Will do.

File: lib/client/player.go (hunk 2 above)
Comment (zmb3) [reply lib/client/player.go:238]: I thought so too, but I couldn't get the race detector to trip on this as-is (probably because the code ensures you only ever have one playback routine running at a time).

Added a lock anyway.

File: lib/client/player.go (hunk 1 above)
Comment (zmb3) [reply lib/client/player.go]: Yep, not sure what I was thinking here. Fixed.

File: lib/client/player.go (hunk 2 above)
Comment (nklaassen) [reply lib/client/player.go]: Yeah it actually looks like it would be implicitly protected, the lock can't hurt though

**Review by nklaassen — APPROVED** [review]

**Review by ibeckermayer — APPROVED** [review]
