### PR TITLE
When exporting a kubeconfig, overwrite the target file

### LINKED ISSUE #4409: tctl auth sign --format=kubernetes should always overwrite the destination file
### Description

**What happened**:

`tctl auth sign --format=kubernetes --out=./kubeconfig` fails when `./kubeconfig` exists and is not a valid kubeconfig.
When it is valid, `tctl auth sign` updates it (adds new credential/server entries)

**What you expected to happen**:

`tctl auth sign` should always overwrite the destination file.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ tctl auth sign --format=openssh --out=./cert.out
# success
$ tctl auth sign --format=kubernetes --out=./cert.out
error: failed to parse existing kubeconfig "./cert.out": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

### PR DESCRIPTION
**Pull request by awly**
Running `tctl auth sign --format=kubernetes --out=filepath` or `tsh login
--format=kubernetes --out=filepath` should overwrite the target
`filepath` regardless of its existing contents.

Without this, the command could fail if parsing the existing file as a
kubeconfig fails.

Fixes https://github.com/gravitational/teleport/issues/4409

### CODE REVIEW

**Review by r0mant — COMMENTED** [review]
Do you think it'd make sense to get any sort of confirmation from the user before overwriting the existing file? In gravity, many of our commands would also support `--confirm` flag to suppress confirmation prompt for automation friendliness. cc @benarent

**Comment by a-palchikov** [comment]
I agree with @r0mant that it should warn the user about the existing file.

**Comment by awly** [comment]
Makes sense, added a user prompt (for all export formats) and a flag to force the overwrite (for automation).
PTAL

File: lib/client/identityfile/identity.go [hunk 1]
```diff
@@ -55,48 +56,65 @@ const (
...
+	Key *client.Key
+	// Format is the output format for the identity file.
+	Format Format
+	// KubeProxyAddr is the public address of the proxy with its kubernetes
+	// port. KubeProxyAddr is only used when Format is FormatKubernetes.
+	KubeProxyAddr string
+	// OverwriteDestination forces all existing destination files to be
+	// overwritten. When false, user will be prompted for confirmation of
+	// overwite first.
+	OverwriteDestination bool
```
Comment (a-palchikov) [inline lib/client/identityfile/identity.go:80]: You might want to default this to `true` for `auth` command tests.

File: lib/client/identityfile/identity.go [hunk 2]
```diff
@@ -55,48 +56,65 @@ const (
...
+	switch cfg.Format {
 	// dump user identity into a single file:
 	case FormatFile:
-		filesWritten = append(filesWritten, filePath)
-		f, err := os.OpenFile(filePath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, fileMode)
+		if err := checkOverwrite(cfg.OutputPath, cfg.OverwriteDestination); err != nil {
+			return nil, trace.Wrap(err)
+		}
+		filesWritten = append(filesWritten, cfg.OutputPath)
+		f, err := os.OpenFile(cfg.OutputPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, writeFileMode)
```
Comment (a-palchikov) [inline lib/client/identityfile/identity.go:98]: I understand this is existing code being restructured but it would make sense to reuse `writeFile` here as well (which means formatting the output into the buffer first). Might help if we decide to use atomic file writes at some point.

File: lib/client/identityfile/identity.go [hunk 3]
```diff
@@ -186,6 +215,44 @@ func writeWithNewline(w io.Writer, data []byte) error {
...
+		// Something else went wrong, fail.
+		return trace.Wrap(err)
+	}
+	if force {
+		// File exists but we're asked not to prompt, proceed.
+		return nil
+	}
+
+	// File exists, prompt user whether to overwrite.
+	fmt.Fprintf(os.Stderr, "Destination file %q exists. Overwrite it? [y/N]: ", path)
```
Comment (a-palchikov) [inline lib/client/identityfile/identity.go:245]: nit: this is a nice candidate for a utility function. There's at least one other [place](https://github.com/gravitational/teleport/blob/8e1865464b1736f37acab89ba7d24b4d1b18e00a/lib/client/keyagent.go#L388-L396) which uses the same code.
Also, I have not dug deep but I saw that we're setting up signal handlers which might cause minor ux issues with interrupts. Not sure if this is an issue here though.

**Review by a-palchikov — APPROVED** [review]

File: lib/client/identityfile/identity.go [hunk 4]
```diff
@@ -117,59 +135,70 @@ func Write(filePath string, key *client.Key, format Format, clusterAddr string)
...
 			return nil, trace.Wrap(err)
 		}
 
-		err = ioutil.WriteFile(keyPath, key.Priv, fileMode)
+		err = writeFile(keyPath, cfg.Key.Priv, cfg.OverwriteDestination)
 		if err != nil {
 			return nil, trace.Wrap(err)
 		}
 
 	case FormatTLS:
```
Comment (r0mant) [inline lib/client/identityfile/identity.go:152]: I think you need to rebase, this case should also include `FormatDatabase`.

File: lib/client/identityfile/identity.go [hunk 5]
```diff
@@ -186,6 +215,44 @@ func writeWithNewline(w io.Writer, data []byte) error {
...
+	if os.IsNotExist(err) {
+		// File doesn't exist, proceed.
+		return nil
+	}
+	if err != nil {
+		// Something else went wrong, fail.
+		return trace.Wrap(err)
+	}
+	if force {
+		// File exists but we're asked not to prompt, proceed.
```
Comment (r0mant) [inline lib/client/identityfile/identity.go:240]: Nit: Wanna log this in debug?

File: lib/client/identityfile/identity.go [hunk 6]
```diff
@@ -186,6 +215,44 @@ func writeWithNewline(w io.Writer, data []byte) error {
 	return nil
 }
 
+func writeFile(path string, data []byte, forceOverwrite bool) error {
+	if err := checkOverwrite(path, forceOverwrite); err != nil {
```
Comment (r0mant) [inline lib/client/identityfile/identity.go:219]: With this approach, if the command produces 3 files (as most of them do), the user may be prompted 3 times. Think it makes sense to tweak this a bit to only ask for confirmation once if at least one of the destination files exists? The reasoning being, it's unlikely that user would want to overwrite one of the 3 and keep others intact for example.

File: lib/client/identityfile/identity.go [hunk 7]
```diff
@@ -186,6 +215,44 @@ func writeWithNewline(w io.Writer, data []byte) error {
...
+func checkOverwrite(path string, force bool) error {
+	// Check if destination file exists.
+	_, err := os.Stat(path)
+	if os.IsNotExist(err) {
+		// File doesn't exist, proceed.
+		return nil
+	}
+	if err != nil {
+		// Something else went wrong, fail.
+		return trace.Wrap(err)
```
Comment (r0mant) [inline lib/client/identityfile/identity.go:237]: `trace.ConvertSystemError(err)`

File: lib/client/identityfile/identity.go [hunk 8]
```diff
@@ -186,6 +215,44 @@ func writeWithNewline(w io.Writer, data []byte) error {
...
+	// File exists, prompt user whether to overwrite.
+	fmt.Fprintf(os.Stderr, "Destination file %q exists. Overwrite it? [y/N]: ", path)
+	scan := bufio.NewScanner(os.Stdin)
+	if !scan.Scan() {
+		return trace.WrapWithMessage(scan.Err(), "failed reading prompt response")
+	}
+	if strings.ToLower(strings.TrimSpace(scan.Text())) == "y" {
+		return nil
+	}
+	return trace.Errorf("NOT overwriting destination file %q", path)
```
Comment (r0mant) [inline lib/client/identityfile/identity.go:253]: Nit: Is `NOT` capitalized on purpose?

File: lib/client/identityfile/identity.go [hunk 9]
```diff
@@ -55,48 +56,65 @@ const (
...
+	// OverwriteDestination forces all existing destination files to be
+	// overwritten. When false, user will be prompted for confirmation of
+	// overwite first.
+	OverwriteDestination bool
+}
+
+// Write writes user credentials to disk in a specified format.
+// It returns the names of the files successfully written.
+func Write(cfg WriteConfig) (filesWritten []string, err error) {
+
```
Comment (r0mant) [inline lib/client/identityfile/identity.go:86]: Nit: Remove extra empty line.

**Review by r0mant — APPROVED** [review]
A couple of suggestions, otherwise lgtm.

File: lib/client/identityfile/identity.go (hunk 3 above)
Comment (awly) [reply lib/client/identityfile/identity.go]: Good idea, added `lib/utils/prompt.Confirmation` to handle this.
PTAL

File: lib/client/identityfile/identity.go [hunk 10]
```diff
@@ -59,121 +61,153 @@ const (
...
+			ClusterAddr:         cfg.KubeProxyAddr,
+			Credentials:         cfg.Key,
 		}); err != nil {
 			return nil, trace.Wrap(err)
 		}
 
 	default:
 		return nil, trace.BadParameter("unsupported identity format: %q, use one of %q, %q, %q, %q or %q",
-			format, FormatFile, FormatOpenSSH, FormatTLS, FormatKubernetes, FormatDatabase)
+			cfg.Format, FormatFile, FormatOpenSSH, FormatTLS, FormatKubernetes, FormatDatabase)
```
Comment (a-palchikov) [inline lib/client/identityfile/identity.go:210]: nit: it's easier to keep the known formats in a slice:
```go
var IdentityFileFormats = []string{FormatFile, FormatOpenSSH, FormatTLS, FormatKubernetes, FormatDatabase}
// ...
return nil, trace.BadParameter("unsupported identity format: %q, use one of %q",
	cfg.Format, IdentityFileFormats)
```

File: lib/client/identityfile/identity.go [hunk 11]
```diff
@@ -190,6 +224,41 @@ func writeWithNewline(w io.Writer, data []byte) error {
 	return nil
 }
 
+func writeFile(path string, data []byte) error {
+	return trace.Wrap(ioutil.WriteFile(path, data, writeFileMode))
+}
+
+func checkOverwrite(force bool, paths ...string) error {
+	var existingFiles []string
+	// Check if destination files exists.
```
Comment (a-palchikov) [inline lib/client/identityfile/identity.go:233]:
```suggestion
	// Check if the destination file exists.
```

File: lib/client/identityfile/identity.go [hunk 12]
```diff
@@ -190,6 +224,41 @@ func writeWithNewline(w io.Writer, data []byte) error {
...
+			return trace.ConvertSystemError(err)
+		}
+		existingFiles = append(existingFiles, path)
+	}
+	if len(existingFiles) == 0 || force {
+		// Files don't exist or we're asked not to prompt, proceed.
+		return nil
+	}
+
+	// File exists, prompt user whether to overwrite.
```
Comment (a-palchikov) [inline lib/client/identityfile/identity.go:251]:
```suggestion
	// Some files exist, prompt user whether to overwrite.
```

File: tool/tsh/tsh.go [hunk 13]
```diff
@@ -341,6 +345,7 @@ func Run(args []string) {
 		identityfile.FormatOpenSSH,
 		identityfile.FormatKubernetes,
 	)).Default(string(identityfile.DefaultFormat)).StringVar((*string)(&cf.IdentityFormat))
+	login.Flag("overwrite", "Whether to overwrite the existing identity file, if present.").BoolVar(&cf.IdentityOverwrite)
```
Comment (a-palchikov) [inline tool/tsh/tsh.go:348]:
```suggestion
	login.Flag("overwrite", "Whether to overwrite the existing identity file.").BoolVar(&cf.IdentityOverwrite)
```

**Review by a-palchikov — APPROVED** [review]
