### PR TITLE
Database agents to share same IAM policy

### LINKED ISSUE #10883: IAM Policy Limit Exceeded When Using DB Auto-Discovery on Kubernetes
### Description

**What happened**: When using DB auto-discovery In a Teleport cluster with ephemeral pods, the maximum amount of policies (10) in an IAM role will quickly be exceeded. This occurs because each time a pod with a new UUID spins up, it creates an additional policy and does not reuse the existing policies. 

**What you expected to happen**: I did not expect a new policy for every UUID. I expected there would be a blanket policy to cover every pod in the node. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Set up a Teleport cluster in Kubernetes on AWS and connect to a DB with AutoDiscovery
2. Delete the pods several times
3. Observe that a new IAM policy was created for every pod

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #10883
- #10883

Changes
- `IAM` configurator sevice
  - Changes inline policy name from `teleport-<host-id>` to a shared policy name `<cluster-name>-teleport-database-access` .
  - Uses a semaphore lock before configuring IAM for racing database agents.
  - Adds migration to remove old policy
- Fixes a small issue where incomplete IAM action resources can be added to IAM policy
- Update a gocheck UT to testify

### CODE REVIEW

**Review by smallinsky — COMMENTED** [review]
First pass left some comments though I will take a second look tomorrow.

**Review by r0mant — COMMENTED** [review]
@greedy52 @smallinsky So I have only briefly looked at the implementation but it looks like the change here is that instead of creating a policy per agent, each agent now creates the same `teleport-managed-database-access` policy? What happens if multiple database agents are using the same AWS identity but proxy different databases? Won't their updates race with each other?

**Review by r0mant — COMMENTED** [review]
I'm also not sure if the "diagnostics" stuff is related to the issue with IAM policies. It did not look that way at least, can it be split out in a separate PR if so?

**Comment by smallinsky** [comment]
@r0mant 
> What happens if multiple database agents are using the same AWS identity but proxy different databases? Won't their updates race with each other?

No sure if I missing something but in this case the update is be synced by Backend Semaphore so two agents that proxies different databases can extend the shared policy without any race. 

Thought there can be race in trusted cluster case where the same AWS Identity is used by two DB agent that are not connected to the same trusted cluster but in this case I think that we can prefix the shared policy by local cluster name or some other uniq unchanged cluster identifier.

**Comment by r0mant** [comment]
@smallinsky You're right, I forgot that we already ensure individual rules instead of updating the policy as a single document every time. Should be good then (if you guys made sure it works as expected). Prefixing the policy with the cluster name sounds good to me.

@greedy52 I would still probably ask to split out the "diagnostics" stuff. They're not directly related to the fix, are they? It would be easier to capture the full scope of the fix this way.

**Comment by greedy52** [comment]
@r0mant I added "diagnose" just in case one agent deletes IAM permissions that other agents may still need. Though, I do think this is probably a very rare corner case that normally shouldn't happen. I will remove it from this PR and adds the cluster name

File: lib/srv/db/diagnose.go [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+// addDiagnoseTask adds a database with error for diagnosis.
+func (s *Server) addDiagnoseTask(database types.Database, err error) error {
+	switch {
+	case common.IsIAMAuthError(err):
+	default:
+		return nil
+	}
+
+	// Rate limit the diagnosis per database to avoid repetition.
+	rates := ratelimit.NewRateSet()
```
[the remark this answers is not in the document]
Comment (greedy52) [reply lib/srv/db/diagnose.go]: i think the same token is used as long the period is the same. Though diagnose stuff is removed from this now =D

File: lib/srv/db/cloud/iam.go [hunk 2]
```diff
@@ -125,3 +185,117 @@ func (c *IAM) getAWSIdentity(ctx context.Context) (aws.Identity, error) {
...
+	if err != nil {
+		return "", trace.Wrap(err)
+	}
+
+	prefix := clusterName.GetClusterName()
+
+	maxPrefixLength := maxPolicyNameLength - len(policyNameSuffix)
+	if len(prefix) > maxPrefixLength {
+		prefix = prefix[:maxPrefixLength]
+	}
```
Comment (r0mant) [inline lib/srv/db/cloud/iam.go:201]: A comment explaining this logic would be helpful.

File: lib/srv/db/cloud/iam.go [hunk 3]
```diff
@@ -125,3 +185,117 @@ func (c *IAM) getAWSIdentity(ctx context.Context) (aws.Identity, error) {
...
+
+	// TODO(greedy52) ideally tasks can be bundled so the semaphore is acquired
+	// once per group, and the IAM policy is only get/put once per group.
+	lease, err := services.AcquireSemaphoreWithRetry(ctx, services.AcquireSemaphoreWithRetryConfig{
+		Service: c.cfg.AccessPoint,
+		Request: types.AcquireSemaphoreRequest{
+			SemaphoreKind: configurator.cfg.policyName,
+			SemaphoreName: configurator.cfg.identity.GetName(),
+			MaxLeases:     1,
+			Expires:       time.Now().Add(time.Minute),
```
Comment (r0mant) [inline lib/srv/db/cloud/iam.go:221]: Nit: Instead of using `time.Now()` directly, initialize `IAM` object with `clockwork.Clock` which can be set to fake clock in tests if needed.

File: lib/srv/db/server.go [hunk 4]
```diff
@@ -186,8 +187,6 @@ func (c *Config) CheckAndSetDefaults(ctx context.Context) (err error) {
 	return nil
 }
 
-// Server is a database server. It accepts database client requests coming over
```
Comment (r0mant) [inline lib/srv/db/server.go:189]: Nit: If you didn't think this godoc was helpful, would it make sense to make it more helpful instead of removing?

File: lib/srv/db/cloud/iam.go [hunk 5]
```diff
@@ -19,25 +19,40 @@ package cloud
...
 	// HostID is the host identified where this agent is running.
+	// DELETE IN 11.0.
 	HostID string
+	// onProcessTask is called after a task is processed.
+	onProcessTask func(task iamTask)
 }
 
 // Check validates the IAM configurator config.
-func (c *IAMConfig) Check() error {
+func (c *IAMConfig) Check() (err error) {
```
Comment (r0mant) [inline lib/srv/db/cloud/iam.go:52]:
```suggestion
func (c *IAMConfig) Check() error {
```

File: lib/srv/db/cloud/iam.go [hunk 6]
```diff
@@ -47,12 +62,27 @@ func (c *IAMConfig) Check() error {
 	return nil
 }
 
+// iamTask defines an IAM task for the database.
```
Comment (r0mant) [inline lib/srv/db/cloud/iam.go:65]: Nit: Clarify what an "IAM task" is in the godoc.

File: lib/srv/db/server.go (hunk 4 above)
Comment (greedy52) [reply lib/srv/db/server.go:189]: =p Its removed by accident. Will revert

File: lib/srv/db/cloud/iam.go [hunk 7]
```diff
@@ -61,31 +91,57 @@ func NewIAM(ctx context.Context, config IAMConfig) (*IAM, error) {
...
+		cfg:   config,
+		log:   logrus.WithField(trace.Component, "iam"),
+		tasks: make(chan iamTask, defaultIAMTaskQueueSize),
 	}, nil
 }
 
+// Start starts the IAM configurator service.
+func (c *IAM) Start(ctx context.Context) error {
+	// DELETE IN 11.0.
+	c.migrateInlinePolicy(ctx)
```
[the remark this answers is not in the document]
Comment (greedy52) [reply lib/srv/db/cloud/iam.go:103]: That is true. Though I think it's usually expected that the access can be "broken" at certain level while the database service is down getting an upgrade. The new policies should be added back within seconds. It's even less an issue in HA mode if services are upgraded at different times (at least one of the old or the new policy should exist).

On the other hand, if we do feel mitigation is necessary, we can either copy the entire old policy to the new policy if new does not exists, or migrate action/resource to new policy one by one. 

What do you think?

[the remark this answers is not in the document]
Comment (r0mant) [reply lib/srv/db/cloud/iam.go]: I think if we can do it in a way that does not prevent access, we should. Esp. since like this would be totally self-inflicted.

What if we don't delete the old policy unconditionally, but only if the new one is already present? This way it will be deleted, say, on the second restart. Or e.g. launch a goroutine that will delete it in 10 minutes or something instead of deleting right upon startup.

File: lib/srv/db/cloud/iam.go [hunk 8]
```diff
@@ -125,3 +192,119 @@ func (c *IAM) getAWSIdentity(ctx context.Context) (aws.Identity, error) {
...
+		Service: c.cfg.AccessPoint,
+		Request: types.AcquireSemaphoreRequest{
+			SemaphoreKind: configurator.cfg.policyName,
+			SemaphoreName: configurator.cfg.identity.GetName(),
+			MaxLeases:     1,
+			Expires:       c.cfg.Clock.Now().Add(time.Minute),
+		},
+		Retry: utils.LinearConfig{
+			Step:   10 * time.Second,
+			Max:    2 * time.Minute,
```
Comment (jakule) [inline lib/srv/db/cloud/iam.go:234]: Should we make those configurable? If not can you add a comment to explain why we're using these values?

File: lib/srv/db/cloud/iam_test.go [hunk 9]
```diff
@@ -203,11 +258,78 @@ func TestAWSIAMNoPermissions(t *testing.T) {
...
+	})
+	require.NoError(t, err)
+
+	// Old policy should not be deleted after Start.
+	require.NoError(t, configurator.Start(ctx))
+	_, err = iamClient.GetRolePolicyWithContext(ctx, &iam.GetRolePolicyInput{
+		RoleName:   aws.String("test-role"),
+		PolicyName: aws.String("teleport-host-id"),
+	})
+	require.True(t, trace.IsNotFound(common.ConvertError(err)), "expect err is trace.NotFound")
```
Comment (jakule) [inline lib/srv/db/cloud/iam_test.go:311]: Maybe `require.ErrorIs()`??

File: lib/srv/db/cloud/iam.go [hunk 10]
```diff
@@ -19,25 +19,46 @@ package cloud
...
 	"github.com/gravitational/teleport/lib/srv/db/common"
+	"github.com/gravitational/teleport/lib/utils"
 
 	"github.com/gravitational/trace"
 	"github.com/sirupsen/logrus"
 )
 
 // IAMConfig is the IAM configurator config.
 type IAMConfig struct {
+	// Clock used to control time.
```
Comment (r0mant) [inline lib/srv/db/cloud/iam.go:41]:
```suggestion
	// Clock is used to control time.
```

File: lib/srv/db/cloud/iam.go [hunk 11]
```diff
@@ -19,25 +19,46 @@ package cloud
...
+	Clock clockwork.Clock
+	// AccessPoint is a caching client connected to the Auth Server.
+	AccessPoint auth.DatabaseAccessPoint
 	// Clients is an interface for retrieving cloud clients.
 	Clients common.CloudClients
 	// HostID is the host identified where this agent is running.
+	// DELETE IN 11.0.
 	HostID string
+	// onProcessTask is called after a task is processed.
```
[the remark this answers is not in the document]
Comment (r0mant) [reply lib/srv/db/cloud/iam.go:50]: Or `onProcessedTask`.

File: lib/srv/db/cloud/iam.go [hunk 12]
```diff
@@ -61,31 +98,57 @@ func NewIAM(ctx context.Context, config IAMConfig) (*IAM, error) {
...
+		cfg:   config,
+		log:   logrus.WithField(trace.Component, "iam"),
+		tasks: make(chan iamTask, defaultIAMTaskQueueSize),
 	}, nil
 }
 
+// Start starts the IAM configurator service.
+func (c *IAM) Start(ctx context.Context) error {
+	// DELETE IN 11.0.
+	c.deleteOldPolicy(ctx)
```
Comment (r0mant) [inline lib/srv/db/cloud/iam.go:110]: I think this still deletes the policy right away, no?

Comment (greedy52) [reply lib/srv/db/cloud/iam.go]: Just updated. Will wait 10 minutes and checks if new policy is created.

File: lib/srv/db/cloud/iam.go [hunk 13]
```diff
@@ -47,12 +68,28 @@ func (c *IAMConfig) Check() error {
 	return nil
 }
 
+// iamTask defines a background task to either setup or teardown IAM policies
+// for cloud databases.
+type iamTask struct {
+	// isSetup indicates the task is a setup task if true, a teardown task if
+	// false.
+	isSetup bool
```
[the remark this answers is not in the document]
Comment (greedy52) [reply lib/srv/db/cloud/iam.go:76]: I have that initially but find it adds quite some extra code. I think we can add next time if there are more types than these two.

File: lib/srv/db/cloud/iam.go [hunk 14]
```diff
@@ -125,3 +192,119 @@ func (c *IAM) getAWSIdentity(ctx context.Context) (aws.Identity, error) {
...
+	clusterName, err := c.cfg.AccessPoint.GetClusterName()
+	if err != nil {
+		return "", trace.Wrap(err)
+	}
+
+	prefix := clusterName.GetClusterName()
+
+	// If the length of the policy name is over the limit, trim the cluster
+	// name from right and keep the policyNameSuffix intact.
+	maxPrefixLength := maxPolicyNameLength - len(policyNameSuffix)
```
[the remark this answers is not in the document]
Comment (greedy52) [reply lib/srv/db/cloud/iam.go:207]: I don't think it can happen. both are constants so if anything, unit test should catch it.

File: lib/srv/db/cloud/iam.go [hunk 15]
```diff
@@ -61,31 +98,57 @@ func NewIAM(ctx context.Context, config IAMConfig) (*IAM, error) {
...
+		defer c.log.Info("Stopped IAM configurator service.")
+		for {
+			select {
+			case <-ctx.Done():
+				return
+
+			case task := <-c.tasks:
+				err := c.processTask(ctx, task)
+				if err != nil {
+					c.log.WithError(err).Errorf("Failed to auto-configure IAM for %v.", task.database)
```
[the remark this answers is not in the document]
Comment (greedy52) [reply lib/srv/db/cloud/iam.go:123]: updated the callback to `onProcessedTask(processedTask, processError)`. It's actually only used in UT for catching the timing.

**Comment by greedy52** [comment]
@smallinsky @r0mant @jakule I have addressed the PR comments. Thanks!

**Review by smallinsky — APPROVED** [review]
LGTM

**Comment by greedy52** [comment]
@r0mant @jakule friendly ping. Thanks!

File: lib/srv/db/cloud/iam_test.go [hunk 16]
```diff
@@ -93,65 +101,112 @@ func TestAWSIAM(t *testing.T) {
...
-	policy = iamClient.attachedRolePolicies["test-role"]["teleport-host-id"]
-	require.NotContains(t, policy, rdsDatabase.GetAWS().RDS.ResourceID)
 
-	// Configure Aurora database and make sure IAM was enabled and policy was attached.
-	err = configurator.Setup(ctx, auroraDatabase)
-	require.NoError(t, err)
-	require.True(t, aws.BoolValue(auroraCluster.IAMDatabaseAuthenticationEnabled))
-	policy = iamClient.attachedRolePolicies["test-role"]["teleport-host-id"]
-	require.Contains(t, policy, auroraDatabase.GetAWS().RDS.ResourceID)
+	t.Run("RDS", func(t *testing.T) {
```
Comment (jakule) [inline lib/srv/db/cloud/iam_test.go:145]: Any chances to run all tests in parallel?

File: lib/srv/db/cloud/iam.go [hunk 17]
```diff
@@ -125,3 +192,168 @@ func (c *IAM) getAWSIdentity(ctx context.Context) (aws.Identity, error) {
...
+		})
+	case awslib.User:
+		_, err = iamClient.DeleteUserPolicyWithContext(ctx, &iam.DeleteUserPolicyInput{
+			PolicyName: aws.String(oldPolicyName),
+			UserName:   aws.String(identity.GetName()),
+		})
+	}
+
+	if err != nil && !trace.IsNotFound(common.ConvertError(err)) {
+		c.log.WithError(err).Errorf("Failed to delete inline policy %q for %v. It is recommended to remove this policy since it is no longer required.", oldPolicyName, identity)
```
Comment (jakule) [inline lib/srv/db/cloud/iam.go:345]: Is there a way to make this more visible? I wouldn't assume that everyone looks into the logs. Could we emit this as an event or something similar that is visible in the UI?
WDYGT?

**Review by jakule — APPROVED** [review]
pong LGTM

**Review by r0mant — APPROVED** [review]

File: lib/srv/db/cloud/iam.go (hunk 17 above)
Comment (greedy52) [reply lib/srv/db/cloud/iam.go:345]: I don't think we have a good way to deliver a message to UI at the moment.  For this particular error, it's not the end of the world. It's actually just our fault couldn't cleanup old policies.

File: lib/srv/db/cloud/iam_test.go (hunk 16 above)
Comment (greedy52) [reply lib/srv/db/cloud/iam_test.go:145]: i tried adding parallel but the test fails pretty bad as the test and the mock is not `-race` ready. I spent a little time but seems no easy fix without refactor the test so maybe we add parallel in a later time.
