### PR TITLE
Better handling of database access IAM errors

### LINKED ISSUE #7369: Detect IAM issues for cloud hosted databases
### What

Invalid IAM configuration is one of the most common issues folks are having when configuring database access with cloud-hosted dbs such as Aurora or Cloud SQL.

Teleport database service should detect errors that happen due to insufficient IAM permissions and log/return an appropriate error message explaining how to setup IAM policy and what kind of permission is missing. Couple scenarios where it will be helpful:

* Getting "PAM auth failed" error when connecting to RDS/Aurora.
* Permission errors trying to generate Cloud SQL auth token.

### PR DESCRIPTION
**Pull request by r0mant**
Improve the way database access IAM errors are reported to users. Teleport will now detect errors such as failure to generate an IAM token or connect to an RDS/Redshift/GCP database and report the error to the user in a readable format explaining the reason and showing an example IAM policy where appropriate. This is a first step to improving database access UX.

Closes https://github.com/gravitational/teleport/issues/7369 and updates https://github.com/gravitational/teleport/issues/7265.

### CODE REVIEW

**Review by timothyb89 — APPROVED** [review]

File: lib/srv/db/postgres/test.go [hunk 1]
```diff
@@ -203,6 +204,9 @@ func (s *TestServer) handleStartup(client *pgproto3.Backend) error {
 	// simulates cloud provider IAM auth.
 	if s.cfg.AuthToken != "" {
 		if err := s.handlePasswordAuth(client); err != nil {
+			if err := client.Send(&pgproto3.ErrorResponse{Code: pgerrcode.InvalidPassword, Message: err.Error()}); err != nil {
```
Comment (smallinsky) [inline lib/srv/db/postgres/test.go:207]: nit: Wondering if `InvalidPassword` should be send only on IsAccessDeniedError  errors.
```go
   if trace.IsAccessDeniedError(err) {
	  client.Send(&pgproto3.ErrorResponse{Code: pgerrcode.InvalidPassword ...
  } 
  ```

**Review by smallinsky — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.
