### PR TITLE
Reexec with `/proc/self/exe` on Linux

### LINKED ISSUE #11052: SIGHUP multiple times results in supervising process N which is not our child errors and no connectivity.
### Description

**What happened**: RPM upgrade from teleport 8.3.1 to teleport 8.3.4 prevented any new sessions (old sessions remained unaffected).  This node was reloaded/SIGHUP'd previously and the latest upgrade + reload resulted in errors on any new connections.

```
$ tsh ssh foo-bar
fork/exec /usr/local/bin/teleport;622a7e9a: no such file or directory
ERROR: ssh: could not start shell
```

**What you expected to happen**: New connections to the upgraded node should always be successful.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Connect 10+ times to node in question (# likely doesn't matter).
2. systemctl reload teleport
3. yum update teleport-ent-8.3.1 to teleport-ent-8.3.4
4. systemctl reload teleport
5. Attempt a new connection.

### Server Details
- Teleport version (run `teleport version`): `Teleport Enterprise v8.3.4 git:v8.3.4-0-g010bea1 go1.17.3`
- Server OS (e.g. from `/etc/os-release`): `Red Hat Enterprise Linux Server 7.7 (Maipo)`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated Hardware
- Additional details: N/A

### Client Details
- Tsh version (`tsh version`): `Teleport v8.3.1 git:v8.3.1-0-g64812df go1.17.3`
- Computer OS (e.g. Linux, macOS, Windows): `Linux` and `Mac`
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): yum
- Additional details: N/A

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!

```
Feb 24 16:47:16 foo-bar systemd[1]: Reloading Teleport SSH Service.
Feb 24 16:47:16 foo-bar systemd[1]: Reloaded Teleport SSH Service.
Feb 24 16:47:17 foo-bar teleport[95058]: [NODE]         Service 8.3.1:v8.3.1-0-g64812df is starting on 0.0.0.0:3022.
Mar 10 16:47:53 foo-bar systemd[1]: Reloading Teleport SSH Service.
Mar 10 16:47:53 foo-bar systemd[1]: teleport.service: Supervising process 63333 which is not our child. We'll most likely not notice when it exits.
Mar 10 16:47:53 foo-bar systemd[1]: Reloaded Teleport SSH Service.
Mar 10 16:49:00 foo-bar systemd[1]: teleport.service: Supervising process 63333 which is not our child. We'll most likely not notice when it exits.
Mar 10 16:49:00 foo-bar systemd[1]: teleport.service: Supervising process 63333 which is not our child. We'll most likely not notice when it exits.
Mar 10 16:49:59 foo-bar systemd[1]: teleport.service: Supervising process 63333 which is not our child. We'll most likely not notice when it exits.
Mar 10 16:49:59 foo-bar systemd[1]: teleport.service: Supervising process 63333 which is not our child. We'll most likely not notice when it exits.
Mar 10 16:50:04 foo-bar systemd[1]: teleport.service: Supervising process 63333 which is not our child. We'll most likely not notice when it exits.
Mar 10 16:50:04 foo-bar systemd[1]: teleport.service: Supervising process 63333 which is not our child. We'll most likely not notice when it exits.
Mar 10 19:01:20 foo-bar systemd[1]: Stopping Teleport SSH Service...
Mar 10 19:02:50 foo-bar systemd[1]: teleport.service stop-sigterm timed out. Killing.
Mar 10 19:02:50 foo-bar systemd[1]: Stopped Teleport SSH Service.
Mar 10 19:02:50 foo-bar systemd[1]: Unit teleport.service entered failed state.
Mar 10 19:02:50 foo-bar systemd[1]: teleport.service failed.
Mar 10 19:02:50 foo-bar systemd[1]: Started Teleport SSH Service.
Mar 10 19:02:50 foo-bar teleport[53924]: [NODE]         Service 8.3.4:v8.3.4-0-g010bea1 is starting on 0.0.0.0:3022.
```

USR1 trace available upon request.

### PR DESCRIPTION
**Pull request by espadolini**
Right now we're using the output of `os.Executable` to decide which binary to launch for our internal `teleport exec`/`teleport forward`/`teleport checkhomedir` reexecs. If the binary is replaced, for instance during an upgrade, we end up calling the new binary rather than the old one - which works fine but relies on the new version working correctly and having the exact semantics. If the binary is deleted (by accident, for instance) the `tsh ssh` functionality breaks, which could be problematic if Teleport is the only way to remote into a system.

We don't have a better way on Darwin, but on Linux (starting from Linux 2.2) running `execve` directly on `/proc/self/exe` will execute the currently running binary no matter what happened to any paths referring to it. To compensate for a qemu-user bug (see https://gitlab.com/qemu-project/qemu/-/issues/927) and general qemu-user weirdness, we do a runtime check at init time to try to detect if we're in a qemu-user that is misbehaving, and if not, we end up opening our binary and then reexecuting it via `/proc/self/fd/N`.

Closes #11052.

### CODE REVIEW

File: lib/srv/reexec_linux.go [hunk 1]
```diff
@@ -18,10 +18,47 @@
...
+	defer statFile.Close()
+
+	// ...and regular files with content (/proc/self/stat is not empty) report a
+	// nonzero size after fstat, whereas the actual procfs file reports zero
+	statInfo, err := statFile.Stat()
+	if err != nil {
+		return false
+	}
+
+	return statInfo.Size() != 0
```
Comment (nklaassen) [inline lib/srv/reexec_linux.go:46]: how did you figure out this check, is there a link somewhere? would it be possible to have a more general solution that checks the status of `/proc/self/exe`?

**Review by nklaassen — COMMENTED** [review]
This won't affect graceful restart, right? Since that is often used for upgrades and we'd want to load the new binary

**Comment by espadolini** [comment]
Yes, `(*TeleportProcess).forkChild()` (which is what is called on a HUP or USR2) uses `exec.LookPath(os.Args[0])` as the executable unconditionally, whereas the reexec machinery (used to launch user shells) uses `os.Executable()` and is affected by this change.

File: lib/srv/reexec_linux.go (hunk 1 above)
Comment (espadolini) [reply lib/srv/reexec_linux.go:46]: This is a bit of a doozy: the reason why we can't just execve `/proc/self/exe` is that qemu-user doesn't have that as a special case in [`linux-user/syscall.c`](https://gitlab.com/qemu-project/qemu/-/blob/v6.2.0/linux-user/syscall.c); however, `readlink`/`readlinkat` and `openat` have special cases (grep for `is_proc_myself` in that file).

Opening `/proc/self/exe` is intended to give you a file descriptor on the original binary (by reopening it, sadly) but because of [the bug I linked](https://gitlab.com/qemu-project/qemu/-/issues/927) you actually get a completely bogus file descriptor back if qemu-user was launched by the `binfmt_misc` machinery, as you just get the file descriptor that was used to load the program and was then closed afterwards. If this worked we could rework our code a bit to open `/proc/self/exe` and then launch `/proc/self/fd/number` instead; sadly, that's not the case.

Because of the way the `is_proc_myself` check is implemented (and has been implemented for the past eight years or so) we can actually access the original files by going through `/proc/self/./` or `/proc/./self/`; we could, then, do a readlink on both `/proc/./self/exe` and `/proc/self/exe` and see if they differ, but the whole point of this PR is to avoid flakiness during upgrades (which often involve renaming or replacing files), and that sort of racy thing will end up as a bug report of "we had one `tsh ssh` failure but we can't replicate it" as some automatic upgrade thing was running in the background or something like that.

`exe` is not the only special case, however: `maps`, `stat` and `auxv` are also special cased in qemu (and have been for a really long time). The initial workaround I had involved opening `/proc/self/stat` and `/proc/./self/stat` and checking if their `st_dev` and `st_ino` matched, but while I was doing that I noticed that the real procfs file didn't report a real size while the qemu one (being a real file) did. I'd say that we can rely on the emulation of `/proc/self/stat` not getting more realistic before execve on `/proc/self/exe` starts working as intended - besides, this is a best effort thing anyway.

In fact, I seriously considered not caring about qemu-user at all (as plenty of reexec libraries seem to do, like [`github.com/docker/docker/pkg/reexec`](https://github.com/moby/moby/tree/master/pkg/reexec), but we have plenty of people using arm macs, and x86_64 docker containers run under qemu-user there, so...

Do you think I need to drop all of this in a comment in the code, or is the PR discussion good enough?

Comment (espadolini) [reply lib/srv/reexec_linux.go]: Swapped out the test for a much simpler one 😅

@nklaassen can you PTAL?

Comment (nklaassen) [reply lib/srv/reexec_linux.go]: I'm going to trust you on all the `qemu` details, was just wondering if you found that check on the web somewhere we could link to or you came up with it.

But I'm really wondering if we can invert this condition? Instead of using `/proc/self/exe` unless (some mildly hacky check for qemu), we could only use `/proc/self/exe` if we can actually `Open` it and read a couple bytes or something, whatever is a sufficient check. Do you think that's feasible and could be safer in case some other random system breaks `/proc/self/exe`? It might properly handle more cases of qemu as well and not need a change if they ever fix this.

Comment (espadolini) [reply lib/srv/reexec_linux.go]: Two problems with that:
- in the situation that we mostly care about (amd64 docker container on arm64 macos), because the executable is passed to qemu through the `AT_EXECFD` mechanism, a bug causes `open("/proc/self/exe")` to return the file descriptor number for the program at the time qemu was launched - in the best case scenario, it's not an open file descriptor and we get an error when we try to use it or when we close it, and in the worst case scenario it's a completely unrelated open file and we end up screwing with whatever was using it

- you might not have read permissions on a program you're running, technically

The alternate check I wrote at 51a376599242d60c35995da517e45df02f8f4562 is much easier to reason about, however.

Comment (espadolini) [reply lib/srv/reexec_linux.go]: Oh and I don't believe there is a forward-compatible fix for this, the behavior is just too strange ☹️

Comment (nklaassen) [reply lib/srv/reexec_linux.go]: good points, thanks for taking the time to explain, your current solution LGTM then

**Review by nklaassen — DISMISSED** [review]

File: lib/srv/reexec_linux.go (hunk 1 above)
Comment (espadolini) [reply lib/srv/reexec_linux.go]: Got a forward-compatible fix in b02107d73bdcd4ad1dd04af3afe2b70c07940803

**Comment by espadolini** [comment]
@nklaassen @lxea PTAL, this should be the final version

File: lib/srv/reexec_linux.go [hunk 2]
```diff
@@ -30,6 +69,10 @@ func reexecCommandOSTweaks(cmd *exec.Cmd) {
 	// cleaning up child processes, send a signal for graceful shutdown
 	// to children.
 	cmd.SysProcAttr.Pdeathsig = syscall.SIGQUIT
+
+	if reexecPath != "" {
+		cmd.Path = reexecPath
```
Comment (nklaassen) [inline lib/srv/reexec_linux.go:74]: would be nice to leave a basic comment on why we do this, ie so it still works if the binary gets deleted

**Review by nklaassen — APPROVED** [review]

**Review by lxea — APPROVED** [review]
Thanks for the in-depth explanations also!
