### PR TITLE
SCP - Change file attrs only when requested

### LINKED ISSUE #22265: scp(sftp) without `-p` is attempting to preserve mode on copy
Expected behavior:
```
$ scp /home/foo/baz.conf foo@bar:/etc/baz.conf
baz.conf                                                                                      100% 3098    12.4KB/s   00:00
```

Current behavior:
```
$ scp /home/foo/baz.conf foo@bar:/etc/baz.conf
baz.conf                                                                                       0%    0     0.0KB/s   --:-- ETA
ERROR: chmod /etc/baz.conf: operation not permitted
```

Bug details:
- Teleport version: v11.2.1
- OpenSSH version (client) `OpenSSH_8.0p1`
- Recreation steps:
```
### destination: 
# touch /tmp/test
# chgrp bar /tmp/test
# chmod 664 /tmp/test

### source:
$ id foo
uid=1000(foo) gid=1000(bar)
$ touch /tmp/test
$ scp /tmp/test foo@host:/tmp/
```

- Debug logs

Not working using scp via teleport:
```
debug1: Sending command: scp -v -t /tmp/
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 2097152 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
Sending file modes: C0644 0 conf
debug2: channel 0: rcvd adjust 13
debug2: channel 0: rcvd ext data 58
ERROR: chmod /tmp/conf: operation not permitted

debug2: channel 0: written 58 to efd 8
conf                                                                                                                                                                                                 100%    0     0.0KB/s   00:00    debug3: receive packet: type 98
```

Working using scp direct using sshd on remote:
```
debug1: Sending command: scp -v -t /tmp/
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
Sending file modes: C0644 0 conf
debug2: channel 0: rcvd ext data 19
Sink: C0644 0 conf
debug2: channel 0: written 19 to efd 7
conf                                                                                                                                                                                                 100%    0     0.0KB/s   00:00
debug2: channel 0: read<=0 rfd 5 len 0
```

### PR DESCRIPTION
**Pull request by jakule**
OpenSSH sets 0644 by default and allows copying the source permissions by passing `-p` flag. Our current implementation sets the file permissions even when the client didn't use `-p` flag, which can fail if the user doesn't have permission to set it. This patch matches the OpenSSH behavior.

Closes https://github.com/gravitational/teleport/issues/22265

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by tobiaszheller — APPROVED** [review]

File: lib/sshutils/scp/scp.go [hunk 1]
```diff
@@ -517,9 +517,13 @@ func (cmd *command) receiveFile(st *state, fc newFileCmd, ch io.ReadWriter) erro
...
 
-	if err := cmd.FileSystem.Chmod(path, int(fc.Mode)); err != nil {
-		return trace.Wrap(err)
-	}
+  // Change the file permissions only when client requested it.
+  if cmd.Flags.PreserveAttrs {
+    if err := cmd.FileSystem.Chmod(path, int(fc.Mode)); err != nil {
+      return trace.Wrap(err)
+    }
+  }
```
Comment (r0mant) [inline lib/sshutils/scp/scp.go:525]: Indentation seems messed up in this block.

Comment (jakule) [reply lib/sshutils/scp/scp.go:525]: Linter confirms. Fixing now.
