### PR TITLE
mfa: add new second_factor options "on" and "optional"

### LINKED ISSUE #1929: Support Simultaneous TOTP/U2F and multiple UF2 keys on local authentication
**Problem**

Teleport local authentication currently only supports either TOTP or U2F separately.  Additionally, only a single U2F token can be registered at once.  This means broken/stolen U2F keys or wiped TOTP auth apps require an account reset to fix.

**Solution**

Support both TOTP and U2F at once on local connector, and allow mutliple U2F keys to be registered per account.  This has been adopted as a standard practice for 2-factor auth on many popular apps/sites (for example, GitLab):

screen shot 2018-04-26 at 11 51 09 am

### PR DESCRIPTION
**Pull request by awly**
```
    mfa: add new second_factor options "on" and "optional"

    "on" means that 2FA is required for all users, either TOTP or U2F.

    "optional" means that 2FA is supported for all users, but not required.
    Only users with MFA devices registered will be prompted for 2FA on
    login.

    The login with both supported methods is using the same API as the U2F
    login. It just now supports TOTP in addition. The API endpoints are
    still named after "u2f", I'll rename those in a future PR (in a
    backwards-compatible way).
```

Fixes https://github.com/gravitational/teleport/issues/1929

### CODE REVIEW

**Comment by awly** [comment]
Ping for reviewers

File: constants.go [hunk 1]
```diff
@@ -394,6 +385,16 @@ const (
 	MinimumEtcdVersion = "3.3.0"
 )
 
+// OTPType is the type of the One-time Password Algorithm.
+type OTPType string
+
+const (
+	// TOTP means Time-based One-time Password Algorithm. for Two-Factor Authentication.
```
Comment (webvictim) [inline constants.go:392]:
```suggestion
	// TOTP means Time-based One-time Password Algorithm (for Two-Factor Authentication)
```

File: constants.go [hunk 2]
```diff
@@ -394,6 +385,16 @@ const (
...
+	TOTP = OTPType("totp")
+	// HOTP means HMAC-based One-time Password Algorithm.for Two-Factor Authentication.
```
Comment (webvictim) [inline constants.go:394]:
```suggestion
	// HOTP means HMAC-based One-time Password Algorithm (for Two-Factor Authentication)
```

File: lib/auth/password.go [hunk 3]
```diff
@@ -358,18 +385,22 @@ func (s *Server) changePasswordWithToken(ctx context.Context, req ChangePassword
...
-	switch cap.GetSecondFactor() {
-	case teleport.OFF:
+	secondFactor := cap.GetSecondFactor()
+	if secondFactor == constants.SecondFactorOff {
 		return nil
-	case teleport.OTP, teleport.TOTP, teleport.HOTP:
+	}
+	if req.SecondFactorToken != "" {
+		if secondFactor == constants.SecondFactorU2F {
+			return trace.BadParameter("user %q sent a TOTP token during password reset but cluster only allows U2F for second factor", username)
```
Comment (webvictim) [inline lib/auth/password.go:402]: Should this be more generic like it is in the error below (as we also technically support HOTP, I think?)

```suggestion
			return trace.BadParameter("user %q sent an OTP token during password reset but cluster only allows U2F for second factor", username)
```

File: lib/client/api.go [hunk 4]
```diff
@@ -2314,13 +2318,13 @@ func (tc *TeleportClient) ssoLogin(ctx context.Context, connectorID string, pub
 }
 
 // directLogin asks for a password and performs the challenge-response authentication
```
Comment (webvictim) [inline lib/client/api.go:2320]:
```suggestion
// mfaLocalLogin asks for a password and performs the challenge-response authentication
```

File: lib/client/mfa.go [hunk 5]
```diff
@@ -0,0 +1,144 @@
...
+	default:
+		return nil, trace.BadParameter("bug: non-exhaustive switch in promptMFAChallenge")
+	}
+}
+
+func promptU2FChallenges(ctx context.Context, proxyAddr string, challenges []*proto.U2FChallenge) (*proto.MFAAuthenticateResponse, error) {
+	facet := proxyAddr
+	if !strings.HasPrefix(proxyAddr, "https://") {
+		facet = "https://" + facet
+	}
```
Comment (webvictim) [inline lib/client/mfa.go:123]: Is there a situation where we could be doing U2F logins in insecure mode i.e. HTTP? I can potentially see it for testing purposes, and adding `https` automatically when it isn't present would stop it from working, right?

File: lib/client/weblogin.go [hunk 6]
```diff
@@ -114,15 +116,20 @@ type CreateSSHCertReq struct {
...
+// CreateSSHCertWithMFAReq are passed by web client
 // to authenticate against teleport server and receive
 // a temporary cert signed by auth server authority
-type CreateSSHCertWithU2FReq struct {
+type CreateSSHCertWithMFAReq struct {
 	// User is a teleport username
 	User string `json:"user"`
-	// We only issue U2F sign requests after checking the password, so there's no need to check again.
+	// Password for the user, to authenticate in case no MFA check was
+	// preformed.
```
Comment (webvictim) [inline lib/client/weblogin.go:126]:
```suggestion
	// performed.
```

File: lib/client/mfa.go [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+		go func() {
+			resp, err := promptU2FChallenges(ctx, proxyAddr, c.U2F)
+			select {
+			case resCh <- response{kind: "U2F", resp: resp, err: err}:
+			case <-ctx.Done():
+			}
+		}()
+
+		go func() {
+			totpCode, err := prompt.Input(os.Stdout, os.Stdin, fmt.Sprintf("Tap any %ssecurity key or enter a code from an %sOTP device", promptDevicePrefix, promptDevicePrefix))
```
Comment (webvictim) [inline lib/client/mfa.go:82]: It looks the only string added in here so far is `*registered*`, which should be "a registered" rather than "an registered"?

```suggestion
			totpCode, err := prompt.Input(os.Stdout, os.Stdin, fmt.Sprintf("Tap any %ssecurity key or enter a code from a %sOTP device", promptDevicePrefix, promptDevicePrefix))
```

**Review by webvictim — COMMENTED** [review]
LGTM, few nits/questions

File: lib/auth/password.go [hunk 8]
```diff
@@ -389,7 +420,12 @@ func (s *Server) changeUserSecondFactor(req ChangePasswordWithTokenRequest, Rese
 		}
 
 		return nil
-	case teleport.U2F:
+	}
+	// Wish this was a pointer...
+	if req.U2FRegisterResponse != (u2f.RegisterChallengeResponse{}) {
```
[the remark this answers is not in the document]
Comment (awly) [reply lib/auth/password.go]: changed to a pointer, turns out it wasn't too widely used

File: lib/client/mfa.go [hunk 9]
```diff
@@ -0,0 +1,144 @@
...
+			res := response{kind: "TOTP", err: err}
+			if err == nil {
```
[the remark this answers is not in the document]
Comment (awly) [reply lib/client/mfa.go:80]: The error is set in `res` on the previous line
This check simply avoids populating `re.resp` if there was an error

File: lib/client/mfa.go (hunk 7 above)
Comment (awly) [reply lib/client/mfa.go]: Fixed message.

> Also, will you be able to read stdin (OTP) in U2F case? It looks like it could block forever.

Correct, if U2F succeeds first, this `prompt.Input` command hangs forever.
I have a TODO to support prompt cancellation: https://github.com/gravitational/teleport/blob/master/lib/utils/prompt/confirmation.go#L19-L20
It's not too bad for now, since this is for short-lived CLI commands. It only breaks when sending multiple prompts from the same process.

File: lib/client/mfa.go (hunk 5 above)
Comment (awly) [reply lib/client/mfa.go:119]: I don't think we support running a proxy without TLS.

File: lib/client/mfa.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (a-palchikov) [reply lib/client/mfa.go:80]: My bad - did not see it.

**Review by a-palchikov — APPROVED** [review]

**Comment by awly** [comment]
Ping @r0mant @russjones for reviews

File: lib/auth/auth.go [hunk 10]
```diff
@@ -841,63 +842,52 @@ func (a *Server) PreAuthenticatedSignIn(user string, identity tlsca.Identity) (s
...
+// MFAAuthenticateChallenge is a U2F authentication challenge sent on user
 // login.
-type U2FAuthenticateChallenge struct {
+type MFAAuthenticateChallenge struct {
 	// Before 6.0 teleport would only send 1 U2F challenge. Embed the old
 	// challenge for compatibility with older clients. All new clients should
 	// ignore this and read Challenges instead.
 	*u2f.AuthenticateChallenge
+
 	// The list of U2F challenges, one for each registered device.
```
Comment (r0mant) [inline lib/auth/auth.go:853]: Nit: "U2FChallenges is ..."

File: lib/auth/auth.go [hunk 11]
```diff
@@ -841,63 +842,52 @@ func (a *Server) PreAuthenticatedSignIn(user string, identity tlsca.Identity) (s
...
-	Challenges []u2f.AuthenticateChallenge `json:"challenges"`
+	U2FChallenges []u2f.AuthenticateChallenge `json:"u2f_challenges"`
+	// TOTPChallenge specifies whether TOTP is supported for this user.
+	TOTPChallenge bool
```
Comment (r0mant) [inline lib/auth/auth.go:856]: Does this field get marshaled? There's no json tag.

File: lib/client/mfa.go [hunk 12]
```diff
@@ -0,0 +1,140 @@
...
+		go func() {
+			resp, err := promptU2FChallenges(ctx, proxyAddr, c.U2F)
+			select {
+			case resCh <- response{kind: "U2F", resp: resp, err: err}:
+			case <-ctx.Done():
+			}
+		}()
+
+		go func() {
+			totpCode, err := prompt.Input(os.Stdout, os.Stdin, fmt.Sprintf("Tap any %[1]ssecurity key or enter a code from a %[1]sOTP device", promptDevicePrefix, promptDevicePrefix))
```
Comment (r0mant) [inline lib/client/mfa.go:78]: What happens with this input prompt in case if user taps security key? Will it return the gibberish string generated by the key, or keep waiting for the input?

File: lib/client/mfa.go [hunk 13]
```diff
@@ -0,0 +1,140 @@
...
+			res := response{kind: "TOTP", err: err}
+			if err == nil {
+				res.resp = &proto.MFAAuthenticateResponse{Response: &proto.MFAAuthenticateResponse_TOTP{
+					TOTP: &proto.TOTPResponse{Code: totpCode},
+				}}
+			}
+
+			select {
+			case resCh <- res:
```
Comment (r0mant) [inline lib/client/mfa.go:87]: Shouldn't this only be sent to the channel in `err == nil` case?

**Review by r0mant — APPROVED** [review]
Couple of questions, otherwise lgtm.

File: api/constants/constants.go [hunk 14]
```diff
@@ -89,3 +80,23 @@ const (
 	// KeepAliveDatabase is the keep alive type for database server.
 	KeepAliveDatabase = "db"
 )
+
+// SecondFactorType is the type of 2FA authentication.
+type SecondFactorType string
+
+const (
+	// SecondFactorOff means no second factor.
+	SecondFactorOff = SecondFactorType("off")
```
[the remark this answers is not in the document]
Comment (awly) [reply api/constants/constants.go:89]: AFAIK, no - exactly the same outcome

File: lib/auth/auth.go (hunk 11 above)
Comment (awly) [reply lib/auth/auth.go]: added JSON tag

File: lib/client/mfa.go (hunk 12 above)
Comment (awly) [reply lib/client/mfa.go:78]: It will hang waiting for actual user input.
I have a TODO to support prompt cancellation: https://github.com/gravitational/teleport/blob/master/lib/utils/prompt/confirmation.go#L19-L20

File: lib/client/mfa.go (hunk 13 above)
Comment (awly) [reply lib/client/mfa.go:87]: the loop below is responsible for handling errors
otherwise it wouldn't know when both U2F and TOTP fail

**Comment by webvictim** [comment]
We should add a set of steps to the [manual test plan](https://github.com/gravitational/teleport/blob/master/docs/testplan.md) which cover these changes - use both U2F and TOTP, two U2F keys, two TOTP devices, adding, removal etc.
