### PR TITLE
Fix connections to desktops in leaf clusters where w_d_s is connected via reverse tunnel

### LINKED ISSUE #19689: desktop access: cannot connect to a desktop in a leaf cluster via reverse tunnel
In Teleport 11.1.4, attempting to connect to a desktop in a leaf cluster works when the desktop is using direct dial mode (listening on port 3028).

Attempts to connect to a leaf cluster desktop that is connected via tunnel fail with error:

```
User Message: connection rejected: 
failed dialing through tunnel (no tunnel connection found: no windows_ desktop reverse tunnel for f69fafa7-9b10-4c@c-8c7a-58ebbabc found)
or directly (dial top: address remote.windows desktop.proxy. teleport .cluster. local: missing port in address)] 
reversetunnel/remotesite.go:912

```

### PR DESCRIPTION
**Pull request by ibeckermayer**
Tunnels are indexed by `<uuid>.<clusterName>`, so previously we were always looking for `<uuid>.<rootClusterName>`, which in the case of leaf clusters would fail to find a tunnel. With this change, we search for tunnels by their proper cluster name, which fixes https://github.com/gravitational/teleport/issues/19689

### CODE REVIEW

File: lib/web/desktop.go [hunk 1]
```diff
@@ -60,6 +60,11 @@ func (h *Handler) desktopConnectHandle(
 	sctx *SessionContext,
 	site reversetunnel.RemoteSite,
 ) (interface{}, error) {
+	clusterName := p.ByName("site")
+	if clusterName == "" {
+		return nil, trace.BadParameter("missing site in request URL")
```
Comment (hatched) [inline lib/web/desktop.go:65]: Is this possible as `site` is part of the path to get to this handler?

**Review by zmb3 — APPROVED** [review]

File: lib/web/desktop.go [hunk 2]
```diff
@@ -170,7 +176,7 @@ func (h *Handler) createDesktopConnection(
 		site:     site,
 		userAddr: r.RemoteAddr,
 	}
-	serviceConn, err := c.connectToWindowsService(sctx.cfg.RootClusterName, validServiceIDs)
+	serviceConn, err := c.connectToWindowsService(clusterName, validServiceIDs)
```
Comment (hatched) [inline lib/web/desktop.go:179]: As `clusterName` is user supplied, should we be sanitizing/validating the string first?

**Review by hatched — APPROVED** [review]
Thanks for the updates!
