### PR TITLE
select default tsh db user or db name from roles

### LINKED ISSUE #22717: Improve `tsh db connect` default user and database selection
Database access users have expressed concerns that `tsh db connect` first-use experience may be confusing for some users. Specifically, `tsh db connect` invoked without any parameters defaults to the system username which is the default behavior for most database clients it calls under the hoods (e.g. `psql`). This means if you run `tsh db connect` and your local user is not configured in the database (or in the role as allowed user), your connection will fail.

A better UX would be for `tsh db connect` to select the username more intelligently or guide the user better on which username to choose. The proposal is this:

- If there's only 1 allowed user for a database, select it automatically if `--db-user` flag is not provided. `tsh` knows which database users are allowed as it displays them in `tsh db ls` already.
  - When defaulting to this user, `tsh db connect` should print something in the terminal indicating the username, for example "Defaulting to the allowed database user postgres".
- If there're more than 1 allowed users and `--db-user` isn't provided, I don't think we should choose the user ourselves. Instead, let's return a clear error message explicitly asking to provide `--db-user` flag and presenting them with a list of allowed users.
- Apply the same logic to `--db-name`.

This technically can be considered a behavior change so this should only go into master branch and documented as a potentially breaking change in the next major release's notes.

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes https://github.com/gravitational/teleport/issues/22717

This PR changes `tsh db <cmd>` to select a default `--db-user` or `--db-name` when not provided by a user, by looking at the user's allowed `db_names` and `db_users` from their roles.

Default selection is only possible where there is a single explicitly allowed db user/name for a given database, otherwise the tsh user is given an error telling them to provide `--db-user` or `--db-name` along with a hint of what they are allowed to provide based on their roles.

depends on changes from another PR so it's stacked on that one: https://github.com/gravitational/teleport/pull/26182

### CODE REVIEW

**Comment by GavinFrazar** [comment]
@r0mant I added the release notes label because this is a breaking change, as you noted in the issue.

**Review by Tener — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]

**Comment by r0mant** [comment]
> I added the release notes label because this is a breaking change, as you noted in the issue.

Instead of adding PR label, can you just update CHANGELOG.md on master to start the "Breaking changes" section for Teleport 14?

**Comment by GavinFrazar** [comment]
oh, I guess this needs group 1 @smallinsky PTAL

File: tool/tsh/db.go [hunk 1]
```diff
@@ -858,54 +858,132 @@ func newDatabaseInfo(cf *CLIConf, tc *client.TeleportClient, route tlsca.RouteTo
...
+
+	var proxy *client.ProxyClient
+	err = client.RetryWithRelogin(cf.Context, tc, func() error {
+		proxy, err = tc.ConnectToProxy(cf.Context)
+		return trace.Wrap(err)
+	})
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+	defer proxy.Close()
```
Comment (smallinsky) [inline tool/tsh/db.go:896]: `tc.ConnectToProxy(cf.Context)` is heavy call and in our cloud env takes ~500ms We should avoid invoking  `ConnectToProxy`from from random places.  We already calling ConnectToProxy from ` dbInfo.GetDatabase` so we should be more  aware about pref impact.

We probably we should take a look at this flow and pref implication before v14 release. 
Could you add a TODO/Reminder comment issue that  we should unify `tc.ConnectToProxy` call in this flow ?

File: tool/tsh/db.go [hunk 2]
```diff
@@ -858,54 +858,132 @@ func newDatabaseInfo(cf *CLIConf, tc *client.TeleportClient, route tlsca.RouteTo
...
+		dbInfo.Database = dbName
 	}
-	if dbInfo.Database != "" {
-		switch dbInfo.Protocol {
-		case defaults.ProtocolDynamoDB:
-			log.Warnf("Database %v protocol %v does not support --db-name flag, ignoring --db-name=%v",
-				dbInfo.ServiceName, defaults.ReadableDatabaseProtocol(dbInfo.Protocol), dbInfo.Database)
-			dbInfo.Database = ""
+
+	return &dbInfo, nil
```
Comment (smallinsky) [inline tool/tsh/db.go:920]: nit: For readability can we move this logic into a  sperate function  ?  Could you also add a comment describing  default user behavior ?

**Review by smallinsky — APPROVED** [review]

File: tool/tsh/db.go (hunk 2 above)
Comment (GavinFrazar) [reply tool/tsh/db.go:920]: I had auto-merge enabled so this merged after you approved it, but I can do a followup PR

File: tool/tsh/db.go (hunk 1 above)
Comment (GavinFrazar) [reply tool/tsh/db.go:896]: I was aware of this extra connecttoproxy call, but I couldn't see a straightforward way to avoid it. Maybe we need to add a way to have TeleportClient reuse a proxy connection instead of opening/closing it for various API calls. I'll make an issue
