### PR TITLE
Capture stderr from "tsh db connect" and reformat redis error

### LINKED ISSUE #13731: Invalid `--insecure` flag when connecting to Redis database
When connecting to a Redis instance with the `insecure` flag it returns an error related to the flag not being recognized. Looking at the logs, it seems that the `tsh` flag is being passed to the `redis-cli` command, causing the error.
```
$ tsh db connect --insecure redis
Unrecognized option or bad number of args for: '--insecure'
ERROR: exit status 1
```

```
$ tsh db connect -d --insecure redis
...
DEBU [TSH]       Starting local proxy tsh/db.go:517
DEBU [TSH]       /usr/bin/redis-cli -h localhost -p 44949 --tls --key /home/ubuntu/.tsh/keys/teleport/alice --cert /home/ubuntu/.tsh/keys/teleport/alice-db/teleport/redis-x509.pem --insecure --cacert /home/ubuntu/.tsh/keys/teleport/cas/teleport.pem tsh/db.go:681
Unrecognized option or bad number of args for: '--insecure'

ERROR REPORT:
Original Error: *exec.ExitError exit status 1
Stack Trace:
        /home/ubuntu/teleport/tool/tsh/db.go:687 main.onDatabaseConnect
        /home/ubuntu/teleport/tool/tsh/tsh.go:920 main.Run
        /home/ubuntu/teleport/tool/tsh/tsh.go:396 main.main
        /usr/lib/go-1.18/src/runtime/proc.go:250 runtime.main
        /usr/lib/go-1.18/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: exit status 1
```

Bug details:
- Teleport version: `branch/v10`
- Redis CLI version: `6.0.16`
- Recreation steps:
  - `tsh db login --insecure redis`: Login into a Redis database with `insecure` set;
  - `tsh db connect --insecure redis`: Connect into the Redis database with `insecure` set;

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #13731
- #13731

```
$ tsh db connect --insecure steve-redis
Unrecognized option or bad number of args for: '--insecure'
ERROR: '/opt/homebrew/bin/redis-cli' has exited with the above error. Please make sure 'redis-cli' with version 6.2 or newer is installed.
```

### CODE REVIEW

File: tool/tsh/db.go [hunk 1]
```diff
@@ -659,12 +660,15 @@ func onDatabaseConnect(cf *CLIConf) error {
 		return trace.Wrap(err)
 	}
 	log.Debug(cmd.String())
+
+	peakStderr := utils.NewCaptureNBytesWriter(100)
 	cmd.Stdout = os.Stdout
-	cmd.Stderr = os.Stderr
+	cmd.Stderr = io.MultiWriter(os.Stdout, peakStderr)
```
Comment (gabrielcorado) [inline tool/tsh/db.go:666]: Shouldn't it be `os.Stderr`?

File: tool/tsh/db.go [hunk 2]
```diff
@@ -659,12 +660,15 @@ func onDatabaseConnect(cf *CLIConf) error {
 		return trace.Wrap(err)
 	}
 	log.Debug(cmd.String())
+
+	peakStderr := utils.NewCaptureNBytesWriter(100)
```
Comment (gabrielcorado) [inline tool/tsh/db.go:664]: Why not capture the entire stderr? It might be hard to guess which number of bytes we need to place here if we want to handle other database command errors.

**Review by gabrielcorado — APPROVED** [review]

File: tool/tsh/db.go (hunk 1 above)
Comment (greedy52) [reply tool/tsh/db.go:666]: good catch!

File: lib/utils/writer.go [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+		if len(capture) > w.maxRemaining {
+			capture = capture[:w.maxRemaining]
+		}
+
+		w.capture = append(w.capture, capture...)
+		w.maxRemaining -= len(capture)
+	}
+
+	// Always pretend to be successful.
+	return len(p), nil
```
Comment (smallinsky) [inline lib/utils/writer.go:47]: What about something like: 
```suggestion
	if w.curr < w.limit {
		w.curr += copy(w.buff[w.curr:], p)
	}
	return len(p), nil
```
where `NewCaptureNBytesWriter` is define as follow: 
```
func NewCaptureNBytesWriter(max int) *CaptureNBytesWriter {
	return &CaptureNBytesWriter{
		buff:  make([]byte, max),
		limit: max,
                curr:  0,
	}
}
```

**Review by smallinsky — APPROVED** [review]

File: lib/utils/writer.go (hunk 3 above)
Comment (greedy52) [reply lib/utils/writer.go:47]: I really like the simplicity of using `copy`. though, this way we are pre-allocating a buffer size of limit. this could be wasteful if the limit is large (there could be no incoming data at all).

File: tool/tsh/db.go (hunk 2 above)
Comment (gabrielcorado) [reply tool/tsh/db.go]: Yeah, I haven't considered this. In this case, limiting the output captured seems necessary. I'm still not sure about the size, but making it a constant might be easier to extend later (if needed).

**Review by ptgott — APPROVED** [review]

**Comment by GavinFrazar** [comment]
Could we backport this?
