### PR TITLE
expose logs of Teleport child processes

### LINKED ISSUE #17318: Re-exec sends Teleport logs to the connected client
#### Expected behavior:

Logging functions logs stuff.

#### Current behavior:

Logging doesn't work in re-exec Teleport processes, example https://github.com/gravitational/teleport/blob/9e22423d7a41ff2d23b7e671312d8e3c4d4ed78c/lib/srv/reexec.go
Logs are currently being sent to the connected client, for example https://github.com/gravitational/teleport/issues/17185, instead of backend logs.

We need to find a way to send the logs to the parent process (maybe using another file descriptor), so all logs can be written to the same place.

#### Bug details:
- Teleport version: probably all
- Recreation steps
- Debug logs

### LINKED ISSUE #53227: Failed to set groups for networking process
With versions from major v16 i was able to use a socks proxy through a teleport
```shell
tsht ssh --dynamic-forward 32768 --no-remote-exec nobody@customeraccess-vpn-teleport-test.example.com &
curl -x socks5h://localhost:32768 -kvI https://service.example.internal/
echo $?
```

Expected behavior:
Access through socks5 proxy works

Current behavior:
Something with the nobody user does not work anymore as before. Missing permissions?
```txt
Failed to launch: failed to set groups for networking process
operation not permitted.
```

Bug details:
- Teleport version: public.ecr.aws/gravitational/teleport-distroless:17.3.3
- Recreation steps: run the image, connect through it without a shell but with dynamic forward
- Debug logs
```txt
Failed to launch: failed to set groups for networking process
operation not permitted.
```

### PR DESCRIPTION
**Pull request by capnspacehook**
Configures Teleport child processes to log with the exact same configuration as the parent process. Logs from child processes previously were essentially discarded.

I used @rosstimothy's [commit](https://github.com/gravitational/teleport/commit/49565509ff2ecb07fe7d8759255313edfea5bb06) from a yr ago as somewhat of a reference.

I manually verified that the child log messages were present and were formatted exactly the same as the parent, testing with both the `text` and `json` output formats for each when:
- logging to terminal (stderr)
- logging to a file
- logging to syslog

Note: Holding off on backporting to v17 due to the size of the change. It may need to be backported later for dependent bug fixes.

Closes https://github.com/gravitational/teleport/issues/17318
Closes https://github.com/gravitational/teleport/issues/53227

### CODE REVIEW

File: lib/srv/reexec.go [hunk 1]
```diff
@@ -1288,6 +1324,18 @@ func copyCommand(ctx *ServerContext, cmdmsg *ExecCommand) {
...
 
+// copyLogs copies logs from the child process to the parent process
+// over the pipe attached to the context. It will exit when the pipe
+// is closed.
+func copyLogs(ctx *ServerContext) {
+	logWriter := ctx.srv.LogConfig().Writer
+
+	_, err := io.Copy(logWriter, ctx.logr)
+	if err != nil && !errors.Is(err, io.EOF) && !errors.Is(err, os.ErrClosed) {
+		slog.ErrorContext(ctx.CancelContext(), "Failed to copy logs over pipe", "error", err)
```
Comment (eriktate) [inline lib/srv/reexec.go]: Will this log ever actually be visible? 😅

File: lib/utils/log/log.go [hunk 2]
```diff
@@ -119,23 +124,23 @@ func Initialize(loggerConfig Config) (*slog.Logger, *slog.LevelVar, error) {
 		if err != nil {
 			slog.ErrorContext(context.Background(), "Failed to switch logging to syslog", "error", err)
 			slog.SetDefault(slog.New(slog.DiscardHandler))
-			return slog.Default(), level, nil
+			return slog.Default(), level, w, nil
```
Comment (eriktate) [inline lib/utils/log/log.go]:
```suggestion
			return slog.Default(), level, io.Discard, nil
```
If we're explicitly discarding the `slog` default, we should probably return `io.Discard` here as well? Or maybe `nil` like we do for the OS log? `w` ends up being `nil` if `NewSyslogWriter()` errors but I think it's less confusing not to fallback to `w`

File: lib/utils/log/slog_text_handler_darwin.go [hunk 3]
```diff
@@ -36,7 +37,7 @@ func NewSlogOSLogHandler(subsystem string, level slog.Leveler) (*SlogTextHandler
 			// timestamp fields in the message. os_log has dedicated handling for this kind of metadata.
 			ConfiguredFields: []string{CallerField},
 		},
-		out:        newOSLogWriter(subsystem),
+		out:        w,
```
Comment (eriktate) [inline lib/utils/log/slog_text_handler_darwin.go]: The changes to this file seem unnecessary unless we're planning to do more with `w`. Could this be removed to preserve the history?

File: lib/srv/reexec.go [hunk 4]
```diff
@@ -978,7 +978,17 @@ func RunAndExit(commandType string) {
...
 	}
 	if err != nil {
-		slog.ErrorContext(context.Background(), "Failed to launch subprocess", "commandType", commandType, "err", err)
+		msg := "Failed to launch subprocess"
+
+		// The "operation not permitted" error is expected from a variety of operations if the
+		// teleport process is running as a non-root user and is trying to spawn a process for
+		// a different OS user.
+		if strings.Contains(err.Error(), "operation not permitted") {
+			msg = ", is Teleport running as root?"
```
Comment (capnspacehook) [inline lib/srv/reexec.go]: Should that be a `+=` there?

File: lib/utils/log/log.go [hunk 5]
```diff
@@ -64,8 +64,9 @@ const (
 )
 
 // Initialize configures the default global logger based on the
-// provided configuration. The [slog.Logger] and [slog.LevelVar]
-func Initialize(loggerConfig Config) (*slog.Logger, *slog.LevelVar, error) {
+// provided configuration. Returns a [slog.Logger] with its underlying
+// [slog.LevelVar] and [io.Writer]. The writer may be nil.
```
Comment (rosstimothy) [inline lib/utils/log/log.go]: Why would the writer be nil? Is this only in error scenarios?

File: lib/utils/log/log.go [hunk 6]
```diff
@@ -79,23 +80,27 @@ func Initialize(loggerConfig Config) (*slog.Logger, *slog.LevelVar, error) {
...
+			return nil, nil, nil, trace.Wrap(err)
 		}
 		logger := slog.New(handler)
 		slog.SetDefault(logger)
-		return logger, level, nil
+
+		// Return nil writer as the os log does not implement [io.Writer]. This writer would need to be
+		// provided for a teleport reexec child process to record logs, except that the teleport binary
+		// does not currently support os_log anyways.
+		return logger, level, io.Discard, nil
```
Comment (rosstimothy) [inline lib/utils/log/log.go]: To avoid confusion I think we should replace all references to nil writer with an explicit reference to io.Discard. A nil writer is slightly ambiguous and will most likely be interpreted as a `nil`.
```suggestion
		// Return [io.Discard] as the [io.Writer] because the teleport binary
		// does not currently support os_log.
		return logger, level, io.Discard, nil
```

File: lib/service/servicecfg/config.go [hunk 7]
```diff
@@ -228,6 +230,9 @@ type Config struct {
 	// LoggerLevel defines the Logger log level.
 	LoggerLevel *slog.LevelVar
 
+	// LogConfig is the log configuration for handling logs from child processes.
+	LogConfig LogConfig
```
Comment (rosstimothy) [inline lib/service/servicecfg/config.go]: Should we combine all log related fields? It feels a bit disjoint having the Logger and the LoggerLevel be separate.

File: lib/srv/ctx.go [hunk 8]
```diff
@@ -588,6 +606,23 @@ func NewServerContext(ctx context.Context, parent *sshutils.ConnectionContext, s
 	child.AddCloser(child.killShellr)
 	child.AddCloser(child.killShellw)
 
+	// If the log writer is a file, we can pass it directly to the child
+	// process to write to. Otherwise, we need to create a pipe to the child
+	// process and stream the logs to the log writer.
+	logCfg := child.srv.LogConfig()
+	fileWriter, ok := logCfg.Writer.(*os.File)
+	if ok {
```
Comment (rosstimothy) [inline lib/srv/ctx.go]: Suggestion: Reduce variable scope 
```suggestion
	if fileWriter, ok := logCfg.Writer.(*os.File); ok {
```

File: lib/srv/forward/sshserver.go [hunk 9]
```diff
@@ -561,6 +561,17 @@ func (s *Server) GetLockWatcher() *services.LockWatcher {
 	return s.lockWatcher
 }
 
+// LogConfig returns the log configuration for handling logs from
+// child processes.
```
Comment (rosstimothy) [inline lib/srv/forward/sshserver.go]: Can we update this comment to explain that the returned logging config will always be a noop because forwarding servers don't launch child processes?

File: lib/srv/git/forward.go [hunk 10]
```diff
@@ -680,64 +680,92 @@ func (s *ForwardServer) EventMetadata() apievents.ServerMetadata {
...
+
 func (s *ForwardServer) GetHostSudoers() srv.HostSudoers {
 	return nil
 }
+
 func (s *ForwardServer) GetSELinuxEnabled() bool {
 	return false
 }
 
+func (s *ForwardServer) LogConfig() srv.LogConfig {
```
Comment (rosstimothy) [inline lib/srv/git/forward.go]: Can we add a similar comment as on the forward.Sever here?

File: lib/srv/reexec.go [hunk 11]
```diff
@@ -214,23 +236,31 @@ func RunCommand() (errw io.Writer, code int, err error) {
...
-	errorWriter := os.Stdout
+	// If we the command fails to launch, write the error to stdout for the parent process
+	// to digest. If we have a terminal, write it there for the user to see as well.
+	var tty *os.File
+	defer func() {
+		if err != nil && code == teleport.RemoteCommandFailure {
+			s := fmt.Sprintf("Failed to launch: %v.\r\n", err)
+			io.Copy(os.Stdout, bytes.NewBufferString(s))
+			if tty != nil {
+				io.Copy(tty, bytes.NewBufferString(s))
```
Comment (rosstimothy) [inline lib/srv/reexec.go]: Should we use an io.Multiwriter instead of copying the data twice?

File: lib/srv/reexec.go [hunk 12]
```diff
@@ -1243,13 +1277,19 @@ func ConfigureCommand(ctx *ServerContext, extraFiles ...*os.File) (*exec.Cmd, er
 	env := &envutils.SafeEnv{}
 	env.AddExecEnvironment()
 
+	// If the log reader is set, we need to copy the logs to the log writer.
+	if ctx.logr != nil {
+		go copyLogs(ctx)
+	}
```
Comment (rosstimothy) [inline lib/srv/reexec.go]: Is there anyway to avoid the copy goroutine?

Comment (Joerger) [reply lib/srv/reexec.go]: I don't think so, is there a way to attach an `io.Writer` to the reader from `os.Pipe` without a copy goroutine?

File: lib/service/servicecfg/config.go (hunk 7 above)
Comment (Joerger) [reply lib/service/servicecfg/config.go]: I agree the log config inheritance could use some cleanup, though I don't think combining them into one cfg field is best. We would end up with a log of `cfg.LogConfig.Logger.DebugContext(...)` calls and what not. Instead I tried to clean up the inheritance a bit so it is clear when the `ChildLogConfig` is initialized and where the values come from. LMK if you'd like to see a different change. 89a83924fe3e2898a758e88879a0655d9ed8ce9a

File: lib/srv/regular/sshserver.go [hunk 13]
```diff
@@ -349,6 +352,23 @@ func (s *Server) GetSELinuxEnabled() bool {
 	return s.enableSELinux
 }
 
+// ChildLogConfig returns the child log config.
+func (s *Server) ChildLogConfig() srv.ChildLogConfig {
+	if s.childLogConfig != nil {
+		return *s.childLogConfig
+	}
+
+	// Default to stderr debug logs (tests)
```
Comment (rosstimothy) [inline lib/srv/regular/sshserver.go]: Is it really safe to assume that if we have no `childLogConfig` that we are in a test context? Can we instead update tests to set a child logging config if we want test logs?

File: lib/srv/uacc/uacc.go [hunk 14]
```diff
@@ -77,6 +77,7 @@ func NewUserAccountHandler(cfg UaccConfig) *UserAccountHandler {
 		uacc.utmp = utmp
 		slog.DebugContext(ctx, "utmp user accounting is active")
 	}
+
```
Comment (rosstimothy) [inline lib/srv/uacc/uacc.go]: Let's revert this to preserve the history.
```suggestion
```

File: lib/srv/reexec.go [hunk 15]
```diff
@@ -214,23 +236,33 @@ func RunCommand() (errw io.Writer, code int, err error) {
...
+	var tty *os.File
+	defer func() {
+		if err != nil && code == teleport.RemoteCommandFailure {
+			var w io.Writer = os.Stdout
+			if tty != nil {
+				w = io.MultiWriter(os.Stdout, tty)
+			}
+
+			s := fmt.Sprintf("Failed to launch: %v.\r\n", err)
+			io.Copy(w, bytes.NewBufferString(s))
```
Comment (rosstimothy) [inline lib/srv/reexec.go]: What do you think about writing this directly to w?
```suggestion
			fmt.Fprintf(w, "Failed to launch: %v.\r\n", err)
```

File: lib/srv/reexec.go [hunk 16]
```diff
@@ -1430,3 +1467,37 @@ func (o *osWrapper) newParker(ctx context.Context, credential syscall.Credential
...
+	fields, err := logutils.ValidateFields(cfg.ExtraFields)
+	if err != nil {
+		return
+	}
+
+	var logger *slog.Logger
+	switch cfg.Format {
+	case "":
+		fallthrough // not set. defaults to 'text'
+	case "text":
```
Comment (rosstimothy) [inline lib/srv/reexec.go]: Suggestion: combine these two cases to avoid the fallthrough
```suggestion
	case "text", "":
```

File: lib/srv/reexec.go [hunk 17]
```diff
@@ -1430,3 +1467,37 @@ func (o *osWrapper) newParker(ctx context.Context, credential syscall.Credential
...
+	if logWriter == nil {
+		return
+	}
+
+	fields, err := logutils.ValidateFields(cfg.ExtraFields)
+	if err != nil {
+		return
+	}
+
+	var logger *slog.Logger
```
Comment (rosstimothy) [inline lib/srv/reexec.go]: Do we need this logger? It doesn't look referenced outside of the two cases where we could define a locally scoped logger instead.
```suggestion
```

File: lib/srv/git/forward.go [hunk 18]
```diff
@@ -680,64 +680,94 @@ func (s *ForwardServer) EventMetadata() apievents.ServerMetadata {
 		ServerSubKind:   s.cfg.TargetServer.GetSubKind(),
 	}
 }
+
```
Comment (rosstimothy) [inline lib/srv/git/forward.go]: Consider removing the white space changes to preserve the history.

**Review by rosstimothy — APPROVED** [review]

**Comment by Joerger** [comment]
@eriktate Friendly ping to review

File: lib/srv/reexec.go [hunk 19]
```diff
@@ -214,23 +235,32 @@ func RunCommand() (errw io.Writer, code int, err error) {
 	// ignore SIGQUIT signals.
 	signal.Ignore(syscall.SIGQUIT)
 
-	// errorWriter is used to return any error message back to the client. By
-	// default, it writes to stdout, but if a TTY is allocated, it will write
-	// to it instead.
-	errorWriter := os.Stdout
+	// If we the command fails to launch, write the error to stdout for the parent process
```
Comment (eriktate) [inline lib/srv/reexec.go]:
```suggestion
	// If the command fails to launch, write the error to stdout for the parent process
```

File: lib/srv/reexec.go [hunk 20]
```diff
@@ -939,25 +966,30 @@ func runPark() (errw io.Writer, code int, err error) {
...
 	if err != nil {
-		s := fmt.Sprintf("Failed to launch: %v.\r\n", err)
-		io.Copy(w, bytes.NewBufferString(s))
+		// The "operation not permitted" error is expected from a variety of operations if the
+		// teleport process is running as a non-root user and is trying to spawn a process for
+		// a different OS user.
+		if strings.Contains(err.Error(), "operation not permitted") {
+			slog.ErrorContext(context.Background(), "Failed to launch subprocess, is Teleport running as root?", "command_type", commandType, "err", err)
+		} else {
+			slog.ErrorContext(context.Background(), "Failed to launch subprocess", "command_type", commandType, "err", err)
```
Comment (eriktate) [inline lib/srv/reexec.go:991]: I think these logs will show up for `RunCommand` and `RunNetworking` as long as we don't error out before running `initLogger()`. Pretty sure we'll never see these for the `CheckHomeDir` sub command because it was never configured properly (which is on me :sweat_smile: ). Not something we need to fix right now, just calling it out for later

**Review by eriktate — APPROVED** [review]

**Comment by Joerger** [comment]
@rosstimothy Can this get a flaky test skip?
