### PR TITLE
Fix Per-session MFA for desktops

### LINKED ISSUE #50557: Per-session MFA for desktops is broken
When attempting to connect to a desktop where per-session MFA is required, I am correctly prompted for an MFA, but after tapping the webauthn device I never see the remote desktop - the UI just remains at the spinner.

Browser dev tools show the MFA challenge going out over websocket:

 Image

Nothing super interesting in the Teleport logs (I suspect this is a web UI issue):

```
2024-12-23T11:18:59.639-07:00 DEBU [WEB]       Attempting to connect to desktop user:zac session:73d7 desktop_name:dynamic-standalone-2019 cluster_name:zac-local username:Administrator web/desktop.go:109
2024-12-23T11:18:59.639-07:00 DEBU [WEB]       Attempting to connect to desktop user:zac session:73d7 desktop_name:dynamic-standalone-2019 cluster_name:zac-local username:Administrator width:1497 height:1291 web/desktop.go:130
2024-12-23T11:18:59.644-07:00 INFO  emitting audit event event_type:mfa_auth_challenge.create fields:map[challenge_allow_reuse:false challenge_scope:CHALLENGE_SCOPE_USER_SESSION cluster_name:zac-local code:T1015I ei:0 event:mfa_auth_challenge.create time:2024-12-23T18:18:59.644Z trace.component:audit uid:dc40a423-a865-4ce2-96d4-1abdeb31faa2 user:zac user_kind:1] events/emitter.go:287
2024-12-23T11:19:51.575-07:00 DEBU [WEB]       Received non-MFA message, withholding msg_type:tdp.ClientScreenSpec trace_id:b08dbd3cdc5bbde818c7c12e2d9e5fed span_id:81934a26473a88cd web/desktop.go:424
2024-12-23T11:19:58.096-07:00 ERRO [WEB]       creating desktop connection failed user:zac session:73d7 desktop_name:dynamic-standalone-2019 cluster_name:zac-local error:[websocket: close sent] web/desktop.go:79
```

Questions:
- why do we see two "attempting to connect to desktop" messages?

I confirmed that this brokenb behavior is present on master (d070ce0ec34c2426a5e7514194b45594c0c1c172), but is not present on branch/v17 (909aca2bd42eaea54992a5d1313e709ed2d9b817), which suggests that https://github.com/gravitational/teleport/pull/49794#discussion_r1895988060 is probably the culprit.

### PR DESCRIPTION
**Pull request by Joerger**
Restore `EventEmitterMfaSender` implementation for desktop access [mistakenly removed](https://github.com/gravitational/teleport/pull/49794/files#r1907853997) in https://github.com/gravitational/teleport/pull/49794.

This will be backported in https://github.com/gravitational/teleport/pull/50529

Closes https://github.com/gravitational/teleport/issues/50557

### CODE REVIEW

File: web/packages/teleport/src/lib/useMfa.ts [hunk 1]
```diff
@@ -172,7 +172,7 @@ export function useMfa({ req, isMfaRequired }: MfaProps): MfaState {
   };
 }
 
-export function useMfaTty(emitterSender: EventEmitterMfaSender): MfaState {
+export function useMfaEmitter(emitterSender: EventEmitterMfaSender): MfaState {
```
Comment (zmb3) [inline web/packages/teleport/src/lib/useMfa.ts:175]: Something still feels off about this. 

Are you sure desktop code should be calling this? AFAIK, the TermEvent enum is a bunch of events that our web SSH console depends on. I wouldn't expect the desktop player to depend on any term events since it is not a terminal. 

If your intent is some refactoring so that SSH and desktop MFA share more code I think that's a fine goal, but I think the abstraction is probably not quite right. I don't think desktop code should depend on TermEvent.

Comment (Joerger) [reply web/packages/teleport/src/lib/useMfa.ts:175]: I didn't make any significant refactor to the Desktop session MFA code, it was already using `useMfa`, which took `Tty` or `EventEmitterMfaSender` as an argument (`tdpClient` implements `EventEmitterMfaSender`). I renamed it to `useMfaTty` or `useMfaEmitter` so that I could make `useMfa` more generally usable. 

See the definition for Tty in the WebUI: `class Tty extends EventEmitterMfaSender`. This just represents the websocket used in WebUI sessions to send MFA challenges from the proxy and retrieve a challenge response from the client. I can take a stab at renaming to make this more clear.

Comment (Joerger) [reply web/packages/teleport/src/lib/useMfa.ts:175]: @avatus Can you help provide any more clarification? It is a dense section of the code base.

Comment (avatus) [reply web/packages/teleport/src/lib/useMfa.ts:175]: I think this is a result of poor naming/abstractions from the past. desktop and ssh docs both implemented the old `EventWebAuthnEmitter` or whatever it was called, which had a single non-implemented `sendMfa` method that tty and tdpClient had to implement themselves. And we've since updated it from `useWebauthn` to `useMfa` but that weird abstraction layer should probably just go imo. Outside of this PR probably

**Review by avatus — APPROVED** [review]
MFA works for me locally on windows desktop now

**Review by ryanclark — APPROVED** [review]
