### PR TITLE
Server data race

### LINKED ISSUE #4781: Data race in lib/srv/regular tests
```
==================
WARNING: DATA RACE
Read at 0x00c000c140a0 by goroutine 306:
  github.com/gravitational/teleport/lib/utils.UTC()
      /home/awly/src/teleport/lib/utils/time.go:40 +0x4e
  github.com/gravitational/teleport/lib/services.(*Metadata).CheckAndSetDefaults()
      /home/awly/src/teleport/lib/services/resource.go:728 +0x2ac
  github.com/gravitational/teleport/lib/services.(*ServerV2).CheckAndSetDefaults()
      /home/awly/src/teleport/lib/services/server.go:347 +0x5b
  github.com/gravitational/teleport/lib/services.(*TeleportServerMarshaler).MarshalServer()
      /home/awly/src/teleport/lib/services/server.go:873 +0x5e
  github.com/gravitational/teleport/lib/reversetunnel.marshalDiscoveryRequest()
      /home/awly/src/teleport/lib/reversetunnel/discovery.go:64 +0x114
  github.com/gravitational/teleport/lib/reversetunnel.(*remoteConn).sendDiscoveryRequest()
      /home/awly/src/teleport/lib/reversetunnel/conn.go:238 +0xb7
  github.com/gravitational/teleport/lib/reversetunnel.(*localSite).handleHeartbeat()
      /home/awly/src/teleport/lib/reversetunnel/localsite.go:372 +0x101b

Previous write at 0x00c000c140a0 by goroutine 316:
  github.com/gravitational/teleport/lib/utils.UTC()
      /home/awly/src/teleport/lib/utils/time.go:45 +0x15a
  github.com/gravitational/teleport/lib/services.(*Metadata).CheckAndSetDefaults()
      /home/awly/src/teleport/lib/services/resource.go:728 +0x2ac
  github.com/gravitational/teleport/lib/services.(*ServerV2).CheckAndSetDefaults()
      /home/awly/src/teleport/lib/services/server.go:347 +0x5b
  github.com/gravitational/teleport/lib/services.(*TeleportServerMarshaler).MarshalServer()
      /home/awly/src/teleport/lib/services/server.go:873 +0x5e
  github.com/gravitational/teleport/lib/reversetunnel.marshalDiscoveryRequest()
      /home/awly/src/teleport/lib/reversetunnel/discovery.go:64 +0x114
  github.com/gravitational/teleport/lib/reversetunnel.(*remoteConn).sendDiscoveryRequest()
      /home/awly/src/teleport/lib/reversetunnel/conn.go:238 +0xb7
  github.com/gravitational/teleport/lib/reversetunnel.(*localSite).handleHeartbeat()
      /home/awly/src/teleport/lib/reversetunnel/localsite.go:372 +0x101b

Goroutine 306 (running) created at:
  github.com/gravitational/teleport/lib/reversetunnel.(*server).handleNewService()
      /home/awly/src/teleport/lib/reversetunnel/srv.go:652 +0x352
  github.com/gravitational/teleport/lib/reversetunnel.(*server).handleHeartbeat()
      /home/awly/src/teleport/lib/reversetunnel/srv.go:620 +0x637
  github.com/gravitational/teleport/lib/reversetunnel.(*server).HandleNewChan()
      /home/awly/src/teleport/lib/reversetunnel/srv.go:557 +0x43c

Goroutine 316 (running) created at:
  github.com/gravitational/teleport/lib/reversetunnel.(*server).handleNewService()
      /home/awly/src/teleport/lib/reversetunnel/srv.go:652 +0x352
  github.com/gravitational/teleport/lib/reversetunnel.(*server).handleHeartbeat()
      /home/awly/src/teleport/lib/reversetunnel/srv.go:620 +0x637
  github.com/gravitational/teleport/lib/reversetunnel.(*server).HandleNewChan()
      /home/awly/src/teleport/lib/reversetunnel/srv.go:557 +0x43c
==================
OK: 24 passed, 1 skipped
--- FAIL: TestRegular (63.28s)
    testing.go:1023: race detected during execution of test
```

### PR DESCRIPTION
**Pull request by a-palchikov**
This PR fixes the data race I spotted the [RoundRobin](https://github.com/gravitational/teleport/blob/dmitri/4653-server-data-race/lib/srv/regular/sshserver_test.go#L866) test.

What's interesting with this changeset is that it prompted a [change](https://github.com/gravitational/protobuf/commit/def42e0f694b04018dd338eb82931be7ac019de0) in `gogo/protobuf` which I implemented in a temporary fork until the issue is resolved upstream. 
I've [submitted](https://github.com/gogo/protobuf/pull/710) a PR upstream.

```
google.protobuf.Timestamp Expires = 5 [
    (gogoproto.stdtime) = true,   // specifically this is causing issues with reflect-based cloning
    (gogoproto.nullable) = false,
    (gogoproto.jsontag) = "started,omitempty"
];
```

Basically, protobuf package provides a reflect-based implementation of [Clone](https://github.com/gogo/protobuf/blob/v1.3.1/proto/clone.go#L45). Attempting it on the Server type unfortunately in the version `v1.3.1` results in:

<details><summary><code>Logs</code></summary>

```
go test -race ./lib/services/... -check.f=ServerDeepCopy

----------------------------------------------------------------------
PANIC: services_test.go:105: ServicesSuite.TestServerDeepCopy

... Panic: reflect: reflect.flag.mustBeAssignable using value obtained using unexported field (PC=0x4674F2)

/home/deemok/dev/go/go/src/runtime/panic.go:975
  in gopanic
/home/deemok/dev/go/go/src/reflect/value.go:244
  in flag.mustBeAssignableSlow
/home/deemok/dev/go/go/src/reflect/value.go:234
  in flag.mustBeAssignable
/home/deemok/dev/go/go/src/reflect/value.go:1526
  in Value.Set
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:161
  in mergeAny
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:108
  in mergeStruct
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:240
  in mergeAny
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:203
  in mergeAny
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:108
  in mergeStruct
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:98
  in Merge
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:151
  in mergeAny
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:108
  in mergeStruct
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:98
  in Merge
/home/deemok/go/src/github.com/gravitational/teleport/vendor/github.com/gogo/protobuf/proto/clone.go:52
  in Clone
server.go:363
  in ServerV2.DeepCopy
services_test.go:160
  in ServicesSuite.TestServerDeepCopy
/home/deemok/dev/go/go/src/reflect/value.go:321
  in Value.Call
/home/deemok/dev/go/go/src/runtime/asm_amd64.s:1373
  in goexit
OOPS: 0 passed, 1 PANICKED
--- FAIL: TestServices (0.00s)
FAIL
FAIL	github.com/gravitational/teleport/lib/services	0.133s
ok  	github.com/gravitational/teleport/lib/services/local	0.053s
ok  	github.com/gravitational/teleport/lib/services/suite	0.071s
FAIL
```
</details>

### Before the change:

<details><summary><code>Output</code></summary>

```
$ go test -race -count=5 ./lib/srv/regular/... -check.f=RoundRobin
WARNING: Error cleaning up temporaries: unlinkat /tmp/check-4324745483838182873/1/log/upload/streaming/default: directory not emptyOK: 1 passed
==================
WARNING: DATA RACE
Read at 0x00c000406360 by goroutine 39:
  github.com/gravitational/teleport/lib/utils.UTC()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/utils/time.go:40 +0x4e
  github.com/gravitational/teleport/lib/services.(*Metadata).CheckAndSetDefaults()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/services/resource.go:728 +0x28c
  github.com/gravitational/teleport/lib/services.(*ServerV2).CheckAndSetDefaults()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/services/server.go:344 +0x56
  github.com/gravitational/teleport/lib/services.(*TeleportServerMarshaler).MarshalServer()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/services/server.go:897 +0x59
  github.com/gravitational/teleport/lib/reversetunnel.marshalDiscoveryRequest()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/discovery.go:65 +0x112
  github.com/gravitational/teleport/lib/reversetunnel.(*remoteConn).sendDiscoveryRequest()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/conn.go:238 +0xb1
  github.com/gravitational/teleport/lib/reversetunnel.(*localSite).handleHeartbeat()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:372 +0xf00

Previous write at 0x00c000406360 by goroutine 164:
  github.com/gravitational/teleport/lib/utils.UTC()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/utils/time.go:45 +0x158
  github.com/gravitational/teleport/lib/services.(*Metadata).CheckAndSetDefaults()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/services/resource.go:728 +0x28c
  github.com/gravitational/teleport/lib/services.(*ServerV2).CheckAndSetDefaults()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/services/server.go:344 +0x56
  github.com/gravitational/teleport/lib/services.(*TeleportServerMarshaler).MarshalServer()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/services/server.go:897 +0x59
  github.com/gravitational/teleport/lib/reversetunnel.marshalDiscoveryRequest()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/discovery.go:65 +0x112
  github.com/gravitational/teleport/lib/reversetunnel.(*remoteConn).sendDiscoveryRequest()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/conn.go:238 +0xb1
  github.com/gravitational/teleport/lib/reversetunnel.(*localSite).handleHeartbeat()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/localsite.go:372 +0xf00

Goroutine 39 (running) created at:
  github.com/gravitational/teleport/lib/reversetunnel.(*server).handleNewService()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:659 +0x343
  github.com/gravitational/teleport/lib/reversetunnel.(*server).handleHeartbeat()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:627 +0x664
  github.com/gravitational/teleport/lib/reversetunnel.(*server).HandleNewChan()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:564 +0x47a

Goroutine 164 (running) created at:
  github.com/gravitational/teleport/lib/reversetunnel.(*server).handleNewService()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:659 +0x343
  github.com/gravitational/teleport/lib/reversetunnel.(*server).handleHeartbeat()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:627 +0x664
  github.com/gravitational/teleport/lib/reversetunnel.(*server).HandleNewChan()
      /home/deemok/go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:564 +0x47a
==================
WARNING: Error cleaning up temporaries: unlinkat /tmp/check-2740103009342231109/1/log/upload/streaming/default: directory not emptyOK: 1 passed
--- FAIL: TestRegular (4.06s)
    testing.go:906: race detected during execution of test
WARNING: Error cleaning up temporaries: unlinkat /tmp/check-8995016276575641803/1/log/upload/streaming/default: directory not emptyOK: 1 passed
OK: 1 passed
WARNING: Error cleaning up temporaries: unlinkat /tmp/check-898860202204764712/1/log/upload/streaming/default: directory not emptyOK: 1 passed
FAIL
FAIL	github.com/gravitational/teleport/lib/srv/regular	23.328s
FAIL
```
</details>

### After the change:

<details><summary><code>Output</code></summary>

```
$ go test -race -count=10 ./lib/srv/regular/... -check.f=RoundRobin
ok  	github.com/gravitational/teleport/lib/srv/regular	45.447s
```
</details>

Fixes https://github.com/gravitational/teleport/issues/4781.

### CODE REVIEW

File: lib/reversetunnel/agent.go [hunk 1]
```diff
@@ -134,7 +136,7 @@ func (a *AgentConfig) CheckAndSetDefaults() error {
 // Discovering agent transitions between "discovering" -> "discovered" states.
 type Agent struct {
 	sync.RWMutex
-	*log.Entry
+	log.FieldLogger
```
Comment (awly) [inline lib/reversetunnel/agent.go:139]: don't embed the logger, to keep this type's API clean

File: lib/reversetunnel/discovery.go [hunk 2]
```diff
@@ -61,6 +61,7 @@ func marshalDiscoveryRequest(req discoveryRequest) ([]byte, error) {
 	var out discoveryRequestRaw
 	m := services.GetServerMarshaler()
 	for _, p := range req.Proxies {
+		p = p.DeepCopy()
```
Comment (awly) [inline lib/reversetunnel/discovery.go:64]: leave a comment explaining this

File: lib/reversetunnel/agent.go [hunk 3]
```diff
@@ -161,7 +163,11 @@ func NewAgent(cfg AgentConfig) (*Agent, error) {
 		authMethods: []ssh.AuthMethod{ssh.PublicKeys(cfg.Signer)},
 		state:       agentStateConnecting,
 	}
-	a.Entry = log.WithFields(log.Fields{
+	logger := cfg.Log
+	if cfg.Log == nil {
+		logger = log.StandardLogger()
+	}
```
Comment (awly) [inline lib/reversetunnel/agent.go:169]: do this in `AgentConfig.CheckAndSetDefaults`

File: lib/reversetunnel/srv.go [hunk 4]
```diff
@@ -253,14 +255,18 @@ func NewServer(cfg Config) (Server, error) {
 
 	ctx, cancel := context.WithCancel(cfg.Context)
 
-	entry := log.WithFields(log.Fields{
+	logger := cfg.Log
+	if cfg.Log == nil {
+		logger = log.StandardLogger()
+	}
```
Comment (awly) [inline lib/reversetunnel/srv.go:261]: do this in `Config.CheckAndSetDefaults`

File: lib/services/server.go [hunk 5]
```diff
@@ -367,6 +371,33 @@ func (s *ServerV2) CheckAndSetDefaults() error {
...
+	m, ok := src.(*Metadata)
+	if !ok {
+		return
+	}
+	*r = *m
+	if m.Expires != nil {
+		expires := *m.Expires
+		r.Expires = &expires
+	}
+}
```
Comment (awly) [inline lib/services/server.go:399]: leave comments explaining why these are implemented

File: lib/services/services_test.go [hunk 6]
```diff
@@ -99,3 +101,76 @@ func (s *ServicesSuite) TestLabelKeyValidation(c *check.C) {
 		c.Assert(IsValidLabelKey(tt.label), check.Equals, tt.ok, check.Commentf("tt=%+v", tt))
 	}
 }
+
+func (s *ServicesSuite) TestServerDeepCopy(c *check.C) {
```
Comment (awly) [inline lib/services/services_test.go:105]: Use the new testing style, with `testify` and stdlib `testing` packages

File: lib/sshutils/server.go [hunk 7]
```diff
@@ -44,7 +44,7 @@ import (
 // Server is a generic implementation of an SSH server. All Teleport
 // services (auth, proxy, ssh) use this as a base to accept SSH connections.
 type Server struct {
-	*log.Entry
+	log.FieldLogger
```
Comment (awly) [inline lib/sshutils/server.go:47]: don't embed the field here

**Review by awly — COMMENTED** [review]
Could you link the upstream patch please?
Let's wait a week or two, maybe it'll get accepted and we won't end up with yet another dependency fork.

File: lib/services/server.go [hunk 8]
```diff
@@ -370,6 +374,42 @@ func (s *ServerV2) CheckAndSetDefaults() error {
...
+// Merge overwrites r from src and
+// is part of support for cloning Server values
+// using proto.Clone.
+// Implements proto.Merger
+func (r *Rotation) Merge(src proto.Message) {
+	s, ok := src.(*Rotation)
+	if !ok {
+		return
+	}
+	*r = *s
```
Comment (awly) [inline lib/services/server.go:391]: The `proto.Merger` docs say:
```
	// Merge merges the contents of src into the receiver message.
	// It clones all data structures in src such that it aliases no mutable
	// memory referenced by src.
```
There are 2 possible issues:
- if `r.Foo` is set and `s.Foo` is empty, I assume that `r.Foo` value should be preserved
- if `Rotation` ever gets a pointer field, we break the promise of not keeping mutable memory references

I don't fully understand why we need to implement `proto.Merger`. Does `proto.Clone` not work on `Rotation` otherwise?

Comment (a-palchikov) [reply lib/services/server.go:391]: Can you link to the docs you reference, btw?
I know this is not the complete Merger implementation - it implements enough to support the Clone use-case so it assumes that the receiver is zero value. Unfortunately I was not able to find a concise way to implement it to fulfill the Merger requirements you described and yet be able to avoid exhaustive manual tests of each attribute which is exactly what I was trying to achieve with `Clone`.
Also, the [Merger](https://github.com/gogo/protobuf/blob/v1.3.1/proto/clone.go#L58-L60) interface used here has a somewhat less strict requirement:
```
// Merge merges src into this message.
// Required and optional fields that are set in src will be set to that value in dst.
// Elements of repeated fields will be appended.
// ...
```

As to why I implemented `Merger` also for `Rotation` - exactly for the same reason as for `Metadata` - b/c it was not working with reflect due to use of `time.Time` which sports unexported fields.

Comment (awly) [reply lib/services/server.go:391]: Ahh, I was looking at the regular protobuf docs, not gogoproto: https://github.com/golang/protobuf/blob/master/proto/proto.go#L99-L101

I think this merger implementation will cause problems later on, when it starts getting hit from non-Clone use-cases for whatever reason.
For now, it's OK merge to fix the race, but leave a comment explaining that it's a partial implementation. Next person reading this code will appreciate the background :)

**Review by awly — APPROVED** [review]
