### PR TITLE
Connect: Add useWorkspaceLoggedInUser

### LINKED ISSUE #20327: Connect: New Access Request doc crashes if the user is logs out
The New Access Request doc crashes when the user logs out. Before the doc is actually destroyed, `loggedInUser` is removed from the cluster so the doc re-renders with `loggedInUser` being undefined.

1. Log in to an enterprise cluster.
2. Open New Access Request doc.
3. Log out.

This is because `packages/webapps.e/teleterm/src/ui/DocumentAccessRequests/NewRequest/useNewRequest.ts` assumes that `useLoggedInUser()` always returns an object. It's an interesting case that we should document in `useLoggedInUser`.

I had exactly the same error happen when switching from a non-enterprise cluster to an enterprise cluster that had a New Access Request doc open. Unfortunately, I don't know how to reproduce this. Presumably the app makes some kind of request when switching from one workspace to another and it completely wipes `loggedInUser` from the cluster in `ClustersService`? Edit: Oh, I think I logged out of cluster and the only cluster left was the enterprise one.

cc @gzdunek @avatus as this is something to keep in mind going forward when depending on `loggenInUser`.

### PR DESCRIPTION
**Pull request by ravicious**
e counterpart: https://github.com/gravitational/teleport.e/pull/732

The e counterpart fixes #20327, this PR adds a function which that PR uses.

### CODE REVIEW

File: web/packages/teleterm/src/ui/hooks/useLoggedInUser.ts [hunk 1]
```diff
@@ -1,20 +1,52 @@
...
+ * It should be used for components which are bound to a particular workspace and which don't change
+ * their workspace over their lifecycle; typically those are Document-type components and anything
+ * rendered inside of them.
+ *
+ * In general, the callsite should always assume that this function might return undefined.
+ * One case where it will for sure return undefined is during the logout process as
+ * ClustersService state is cleared up before WorkspacesService state. On top of that, each
+ * workspace is always rendered, even when the cluster is not connected, with at least the default
+ * document. In that scenario useWorkspaceLoggedInUser could return undefined when used within the
+ * default document.
```
Comment (ravicious) [inline web/packages/teleterm/src/ui/hooks/useLoggedInUser.ts:43]: [Link to the discussion](https://gravitational.slack.com/archives/C03FJA391M3/p1674477509096979) for posterity.

**Review by avatus — APPROVED** [review]
This is a really cool change and good abstraction between the two different "types" of users we would handle.

**Review by gzdunek — APPROVED** [review]

File: web/packages/teleterm/src/ui/hooks/useLoggedInUser.ts [hunk 2]
```diff
@@ -1,20 +1,52 @@
 import { useAppContext } from 'teleterm/ui/appContextProvider';
+import { useWorkspaceContext } from 'teleterm/ui/Documents';
+import { LoggedInUser } from 'teleterm/services/tshd/types';
 
-export function useLoggedInUser() {
-  const ctx = useAppContext();
+/**
+ * useLoggedInUser returns the logged in user of the root cluster of the currently active workspace.
```
Comment (tigrato) [inline web/packages/teleterm/src/ui/hooks/useLoggedInUser.ts:6]:
```suggestion
 * useLoggedInUser returns the user logged into the root cluster of the active workspace.
```

Maybe simplify the comment?

**Review by tigrato — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
