### PR TITLE
Fix incorrect user accounting error handling

### LINKED ISSUE #54606: `/var/log/wtmp` not updated on session exit
### Expected behavior:

When a session ends, the `/var/log/wtmp` file should be updated to add an entry to indicate the user has logged out.

### Current behavior:

The file is not updated. This results in behavior like the `last` utility showing a user is `gone - no logout`

### Bug details:
- Teleport version
  - reported and reproduced with 16.5.5. Also observed in 17.4.6.
  - I used `tsh` 17.4.6 while testing both a Teleport 16.5.5 node and 17.4.6 node while connected to a 17.4.6 cluster.
- Recreation steps
  - Look at `/var/lib/wtmp` by running `last`. Also look at the checksum and timestamp of the file.
  - Connect to the host via Teleport. Observe that `last` and the `wtmp` file shows the newly logged in user.
  - Disconnect from the SSH session. You can use `ctrl+d` or type `exit`.
  - Note that while the session ends, the `/var/lib/wtmp` file is not updated. The `last` output doesn't see the PID of the process in the entry, so it shows "gone - no logout".
- Debug logs
  - Even in debug, there's no mention of the `wtmp` code. It just looks like normal activity on a host where a user connects and disconnects.

### PR DESCRIPTION
**Pull request by atburke**
This change fixes a bug where Teleport would incorrectly check for errors from `updwtmp()`, which doesn't report any (hence errno is unreliable).

Resolves #54606.

Changelog: Fixed failure to close user accounting session

### CODE REVIEW

File: lib/srv/uacc/uacc.h [hunk 1]
```diff
@@ -134,9 +134,7 @@ static int uacc_add_utmp_entry(const char *utmp_path, const char *wtmp_path, con
         return status;
     }
     updwtmp(wtmp_file, &entry);
-    if (errno != 0) {
-        return status_from_errno();
-    }
+    // updwtmp doesn't report errors, per the c standard we can't trust errno here.
```
Comment (zmb3) [inline lib/srv/uacc/uacc.h:137]: > per the c standard

Are you sure this is specified in the C standard? That feels odd to me. Have a reference to the standard text?

Comment (atburke) [reply lib/srv/uacc/uacc.h:137]: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3220.pdf
Section 7.5.3: "The value of errno may be set to nonzero by a library function call whether or not there is an error, provided the use of errno is not documented in the description of the function in this document."

**Comment by atburke** [comment]
friendly ping @zmb3 @rosstimothy

**Review by boxofrad — APPROVED** [review]
Approving because it's clear we shouldn't be checking `errno`, but I'm unsure about how this fixes the accounting issue. Were we previously checking the `uacc_*` function return value and then not proceeding to write the session close?

**Comment by atburke** [comment]
@boxofrad yep, exactly that

**Review by rosstimothy — APPROVED** [review]
