### PR TITLE
Fix an issue AWS Redshift auto-provisioned user not deleted in drop mode

### LINKED ISSUE #36708: AWS Redshift auto-user provisioning drop mode not deleting users
Expected behavior:
Auto-provisioned the user should be deleted after session exits.

Current behavior:
- [ ] Active session checking not working properly on `teleport_delete_user` call
- [ ] User (e.g `STeve`) is not removed after `teleport_delete_user` call

Bug details:
- Teleport version:  v15
- Recreation steps
  -  Setup Redshift auto-user provisioning with `best_effort_drop` mode
  - `tsh db connect`
- Debug logs
```
2024-01-15T17:44:54Z DEBU [DB:AUTH]   Generating Redshift auth token for db[manual-steve-redshift-auto-drop] identity[STeve] dbUser[teleport-admin] dbName[test] autoCreate[DB_USER_MODE_BEST_EFFORT_DROP] dbRoles[role1,role3]. common/auth.go:284
2024-01-15T17:44:54Z INFO [DB:SERVIC] Deleting PostgreSQL user "STeve". db:manual-steve-redshift-auto-drop id:0144eafc-449a-4828-81a5-3c3e600f4a79 postgres/users.go:116
2024-01-15T17:44:54Z DEBU [DB:SERVIC] User "STeve" deleted successfully. db:manual-steve-redshift-auto-drop id:0144eafc-449a-4828-81a5-3c3e600f4a79 postgres/users.go:131
```
(but not really deleted by checking `select * from pg_user`. manually `call teleport_delete_user('STeve')` suceeds)

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #36708

changelog: Fix an issue AWS Redshift auto-provisioned user not deleted in drop mode

### CODE REVIEW

File: lib/srv/db/postgres/sql/redshift-delete-user.sql [hunk 1]
```diff
@@ -3,8 +3,8 @@ LANGUAGE plpgsql
 AS $$
 BEGIN
     -- Only drop if the user doesn't have other active sessions.
-    IF EXISTS (SELECT usename FROM pg_stat_activity WHERE usename = username) THEN
-        RAISE NOTICE 'User has active connections';
+    IF EXISTS (SELECT user_name FROM stv_sessions WHERE user_name = CONCAT('IAM:', username)) THEN
+        RAISE EXCEPTION 'TP000: User has active connections';
```
Comment (greedy52) [inline lib/srv/db/postgres/sql/redshift-delete-user.sql:7]: Copied from:
https://github.com/gravitational/teleport/blob/88152574bf3da2236df960af5fe7cf98a236d0a0/lib/srv/db/postgres/sql/redshift-deactivate-user.sql#L7-L11

File: lib/srv/db/postgres/sql/redshift-delete-user.sql [hunk 2]
```diff
@@ -3,8 +3,8 @@ LANGUAGE plpgsql
 AS $$
 BEGIN
     -- Only drop if the user doesn't have other active sessions.
-    IF EXISTS (SELECT usename FROM pg_stat_activity WHERE usename = username) THEN
-        RAISE NOTICE 'User has active connections';
+    IF EXISTS (SELECT user_name FROM stv_sessions WHERE user_name = CONCAT('IAM:', username)) THEN
```
Comment (r0mant) [inline lib/srv/db/postgres/sql/redshift-delete-user.sql:6]: Nit: Maybe include a link to https://docs.aws.amazon.com/redshift/latest/dg/r_STV_SESSIONS.html that explains what this table is? I had to look it up.

**Review by r0mant — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
