### PR TITLE
Fix flaky test `TestUpdateHeadlessAuthenticationState`

### LINKED ISSUE #26189: `TestUpdateHeadlessAuthenticationState` flakiness
## Failure

Running locally, this is pretty consistent with `-count=10`.

```
➜ go test ./lib/auth
--- FAIL: TestUpdateHeadlessAuthenticationState (0.00s)
    --- FAIL: TestUpdateHeadlessAuthenticationState/NOK_same_user_approved_without_mfa (1.16s)
        auth_with_roles_test.go:4614:
            	Error Trace:	/Users/zmb/src/teleport/lib/auth/auth_with_roles_test.go:4614
            	            				/Users/zmb/src/teleport/lib/auth/auth_with_roles_test.go:4712
            	Error:      	Should be true
            	Test:       	TestUpdateHeadlessAuthenticationState/NOK_same_user_approved_without_mfa
            	Messages:   	expected access denied error but got: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    --- FAIL: TestUpdateHeadlessAuthenticationState/OK_same_user_denied (1.16s)
        auth_with_roles_test.go:4712:
            	Error Trace:	/Users/zmb/src/teleport/lib/auth/auth_with_roles_test.go:4712
            	Error:      	Received unexpected error:
            	            	rpc error: code = DeadlineExceeded desc = context deadline exceeded
            	Test:       	TestUpdateHeadlessAuthenticationState/OK_same_user_denied
    --- FAIL: TestUpdateHeadlessAuthenticationState/OK_same_user_approved_with_mfa (1.16s)
        auth_with_roles_test.go:4712:
            	Error Trace:	/Users/zmb/src/teleport/lib/auth/auth_with_roles_test.go:4712
            	Error:      	Received unexpected error:
            	            	rpc error: code = DeadlineExceeded desc = context deadline exceeded
            	Test:       	TestUpdateHeadlessAuthenticationState/OK_same_user_approved_with_mfa
```

### PR DESCRIPTION
**Pull request by Joerger**
This test would occasionally fail due to the headless authn expiring in the backend before the test completes, due to using the `time.Now` instead of `srv.Auth().clock.Now()`.

Closes https://github.com/gravitational/teleport/issues/26189#issuecomment-1546707391

### CODE REVIEW

File: lib/auth/auth_with_roles_test.go [hunk 1]
```diff
@@ -4530,6 +4531,11 @@ func TestGetHeadlessAuthentication(t *testing.T) {
 	username := "teleport-user"
 	otherUsername := "other-user"
 
+	assertTimeout := func(t require.TestingT, err error, i ...interface{}) {
+		require.Error(t, err)
+		require.ErrorContains(t, err, context.DeadlineExceeded.Error(), "expected context deadline error but got: %v", err)
```
Comment (zmb3) [inline lib/auth/auth_with_roles_test.go:4536]:
```suggestion
		require.ErrorIs(t, err, context.DeadlineExceeded)
```

Any reason not to use `ErrorIs` (here and below)?

**Review by zmb3 — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

File: lib/auth/auth_with_roles_test.go (hunk 1 above)
Comment (Joerger) [reply lib/auth/auth_with_roles_test.go:4536]: The error is malformed due to the gRPC layer:

```
Error:      	Target error should be in err chain:
            	           	expected: "context deadline exceeded"
            	           	in chain: "rpc error: code = DeadlineExceeded desc = context deadline exceeded"
            	           		"rpc error: code = DeadlineExceeded desc = context deadline exceeded"
            	Test:       	TestUpdateHeadlessAuthenticationState/NOK_admin_approved
            	Messages:   	expected context deadline error but got: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

Comment (zmb3) [reply lib/auth/auth_with_roles_test.go:4536]: Ok, we should probably update `trail.FromGRPC` to handle `codes.DeadlineExceeded` at some point.
