### PR TITLE
webclient.Ping: Return error on unsuccessful response

### LINKED ISSUE #40208: `lib/client.TeleportClient.Ping` returns empty ping response and no error when `/webapi/ping` returns non-successful response
Expected behavior:

When `/webapi/ping` returns a non-succesfull response with `{"error": "message": "…"}` as the body, `lib/client.TeleportClient.Ping` should return a non-nil error which includes that message.

Current behavior:

`lib/client.TeleportClient.Ping` returns empty `webclient.PingResponse` and no error.

The problem is likely with how `api/client/webclient.Ping` is implemented.

This generates support load because Teleport Connect uses the ping response to establish which auth and MFA types are the preferred ones during login. If the endpoint returns an error but Connect has no way of seeing that error, then the login form is broken with no clear message indicating what's wrong.

Bug details:
- Teleport version: master, I didn't check when this problem was introduced.
- Recreation steps:
   - Compile `teleport` with the patch below and start the cluster.
   - `tsh logout && tsh login --proxy=<proxy address>`
   - At this point, you should see `ERROR: unsupported authentication type: ""`. This is a symptom of tsh proceeding with an empty ping response. The same behavior can be observed when attempting to add such cluster to Connect.

<details>
<summary>Teleport patch</summary>

```diff
diff --git a/lib/web/apiserver.go b/lib/web/apiserver.go
index d89fad67a5..046f9a2f65 100644
--- a/lib/web/apiserver.go
+++ b/lib/web/apiserver.go
@@ -1418,6 +1418,7 @@ func (h *Handler) traces(w http.ResponseWriter, r *http.Request, _ httprouter.Pa
 
 func (h *Handler) ping(w http.ResponseWriter, r *http.Request, p httprouter.Params) (interface{}, error) {
 	var err error
+	return nil, trace.Errorf("oops, something went wrong")
 	authSettings, err := getAuthSettings(r.Context(), h.cfg.ProxyClient)
 	if err != nil {
 		return nil, trace.Wrap(err)

```
</details>

### PR DESCRIPTION
**Pull request by ravicious**
Closes #40208.

We'd often get confusing error reports from users when they weren't able to log in to a cluster. It turns out the code in tsh and Connect that pings the proxy was not handling an error response correctly, and instead it was proceeding with an empty ping response. All this while /webapi/ping returned an actually useful piece of information about a misconfigured cluster – usually the connector was the problem.

This PR changes makes it so that if /webapi/ping returns anything else than 200, the client is going to return an error. I'm going to let it sit on master before backporting.

Feedback wrt to user messages welcome!

<details>
<summary>Before</summary>

```
$ tsh login --proxy=teleport-local.dev:3090
ERROR: unsupported authentication type: ""

$ tsh login -d --proxy=teleport-local.dev:3090
2024-05-08T16:21:31+02:00 INFO [CLIENT]    No teleport login given. defaulting to rav client/api.go:1113
2024-05-08T16:21:31+02:00 INFO [CLIENT]    no host login given. defaulting to rav client/api.go:1123
2024-05-08T16:21:31+02:00 INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.n3b3Cd3cx3/Listeners" client/api.go:4460
2024-05-08T16:21:31+02:00 DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. common/tsh.go:3705
2024-05-08T16:21:31+02:00 DEBU [CLIENT]    attempting to use loopback pool for local proxy addr: teleport-local.dev:3090 client/api.go:4418
2024-05-08T16:21:31+02:00 DEBU [CLIENT]    reading self-signed certs from: /var/lib/teleport/webproxy_cert.pem client/api.go:4426
2024-05-08T16:21:31+02:00 DEBU [CLIENT]    could not open any path in: /var/lib/teleport/webproxy_cert.pem client/api.go:4430
2024-05-08T16:21:31+02:00 DEBU  Attempting request to Proxy web api method:GET host:teleport-local.dev:3090 path:/webapi/ping trace_id:096fa35861df37eb3a0a39850e4ffb1d span_id:5c656c392a0ab347 webclient/webclient.go:130
2024-05-08T16:21:31+02:00 DEBU  ALPN connection upgrade test complete address:teleport-local.dev:3090 upgrade_required:false trace_id:096fa35861df37eb3a0a39850e4ffb1d span_id:5c656c392a0ab347 client/alpn_conn_upgrade.go:96

ERROR REPORT:
Original Error: *trace.BadParameterError unsupported authentication type: &#34;&#34;
Stack Trace:
	github.com/gravitational/teleport/lib/client/api.go:3439 github.com/gravitational/teleport/lib/client.(*TeleportClient).getSSHLoginFunc
	github.com/gravitational/teleport/lib/client/api.go:3193 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1938 github.com/gravitational/teleport/tool/tsh/common.onLogin
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1409 github.com/gravitational/teleport/tool/tsh/common.Run
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:594 github.com/gravitational/teleport/tool/tsh/common.Main
	github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
	runtime/proc.go:271 runtime.main
	runtime/asm_arm64.s:1222 runtime.goexit
User Message: unsupported authentication type: &#34;&#34;

```
</details>

<details open>
<summary>After</summary>

```
$ tsh login --proxy=teleport-local.dev:3090
ERROR: proxy service returned unsuccessful ping response
	oops, something went wrong

$ tsh login -d --proxy=teleport-local.dev:3090
2024-05-08T16:11:21+02:00 INFO [CLIENT]    No teleport login given. defaulting to rav client/api.go:1113
2024-05-08T16:11:21+02:00 INFO [CLIENT]    no host login given. defaulting to rav client/api.go:1123
2024-05-08T16:11:21+02:00 INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.n3b3Cd3cx3/Listeners" client/api.go:4460
2024-05-08T16:11:21+02:00 DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. common/tsh.go:3705
2024-05-08T16:11:21+02:00 DEBU [CLIENT]    attempting to use loopback pool for local proxy addr: teleport-local.dev:3090 client/api.go:4418
2024-05-08T16:11:21+02:00 DEBU [CLIENT]    reading self-signed certs from: /var/lib/teleport/webproxy_cert.pem client/api.go:4426
2024-05-08T16:11:21+02:00 DEBU [CLIENT]    could not open any path in: /var/lib/teleport/webproxy_cert.pem client/api.go:4430
2024-05-08T16:11:21+02:00 DEBU  Attempting request to Proxy web api method:GET host:teleport-local.dev:3090 path:/webapi/ping trace_id:3dd37f581ab85e40258ba7e36896e58d span_id:8c5b4fddcac4d4b0 webclient/webclient.go:130
2024-05-08T16:11:21+02:00 DEBU  Received unsuccessful ping response code:500 trace_id:3dd37f581ab85e40258ba7e36896e58d span_id:8c5b4fddcac4d4b0 webclient/webclient.go:224

ERROR REPORT:
Original Error: *errors.errorString oops, something went wrong
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/webclient/webclient.go:231 github.com/gravitational/teleport/api/client/webclient.Ping
	github.com/gravitational/teleport/lib/client/api.go:4030 github.com/gravitational/teleport/lib/client.(*TeleportClient).Ping
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:3706 github.com/gravitational/teleport/tool/tsh/common.makeClientForProxy
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:3669 github.com/gravitational/teleport/tool/tsh/common.makeClient
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1819 github.com/gravitational/teleport/tool/tsh/common.onLogin
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1409 github.com/gravitational/teleport/tool/tsh/common.Run
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:594 github.com/gravitational/teleport/tool/tsh/common.Main
	github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
	runtime/proc.go:271 runtime.main
	runtime/asm_arm64.s:1222 runtime.goexit
User Message: proxy service returned unsuccessful ping response
	oops, something went wrong

```
</details>

changelog: Made tsh and Teleport Connect return early during login if ping to proxy service was not successful

### CODE REVIEW

File: api/client/webclient/webclient.go [hunk 1]
```diff
@@ -219,13 +219,18 @@ func Ping(cfg *Config) (*PingResponse, error) {
...
-		per := &PingErrorResponse{}
-		if err := json.NewDecoder(resp.Body).Decode(per); err != nil {
-			return nil, trace.Wrap(err)
+
+	if resp.StatusCode != http.StatusOK {
+		slog.DebugContext(req.Context(), "Received unsuccessful ping response", "code", resp.StatusCode)
+		errResp := &PingErrorResponse{}
+
+		if err := json.NewDecoder(resp.Body).Decode(errResp); err != nil {
+			return nil, trace.Wrap(err, "cannot parse unsuccessful ping response")
```
Comment (codingllama) [inline api/client/webclient/webclient.go:228]: Log status code and body here, so we have info to debug?

**Review by codingllama — APPROVED** [review]
LGTM.

I had noticed this before and found it rather strange too.

> I'm going to let it sit on master before backporting.

+1, let's testplan first. If it all goes well, then backport.

File: api/client/webclient/webclient.go (hunk 1 above)
Comment (ravicious) [reply api/client/webclient/webclient.go:228]: Status is logged a couple of lines above already: `slog.DebugContext(req.Context(), "Received unsuccessful ping response", "code", resp.StatusCode)`.

I can log the body though. I did consider it already, but I didn't like how it elaborate it makes the whole thing. (Even though it actually just adds one extra `io.ReadAll` call with error handling).

**Review by codingllama — APPROVED** [review]

File: api/client/webclient/webclient.go (hunk 1 above)
Comment (Tener) [reply api/client/webclient/webclient.go:235]: I think showing the body (under `--debug`) could be very helpful in some instances.

File: api/client/webclient/webclient.go [hunk 2]
```diff
@@ -219,13 +220,24 @@ func Ping(cfg *Config) (*PingResponse, error) {
...
-		per := &PingErrorResponse{}
-		if err := json.NewDecoder(resp.Body).Decode(per); err != nil {
-			return nil, trace.Wrap(err)
+
+	if resp.StatusCode != http.StatusOK {
+		slog.DebugContext(req.Context(), "Received unsuccessful ping response", "code", resp.StatusCode)
+
+		bodyBytes, err := io.ReadAll(resp.Body)
+		if err != nil {
+			return nil, trace.Wrap(err, "could not read ping response body")
```
Comment (Tener) [inline api/client/webclient/webclient.go:229]:
```suggestion
			return nil, trace.Wrap(err, "could not read ping response body; check the network connection")
```

File: api/client/webclient/webclient.go [hunk 3]
```diff
@@ -219,13 +220,24 @@ func Ping(cfg *Config) (*PingResponse, error) {
...
 		}
-		return nil, errors.New(per.Error.Message)
+
+		errResp := &PingErrorResponse{}
+		if err := json.Unmarshal(bodyBytes, errResp); err != nil {
+			slog.DebugContext(req.Context(), "Could not parse ping response body", "body", string(bodyBytes))
+			return nil, trace.Wrap(err, "cannot parse unsuccessful ping response")
```
Comment (Tener) [inline api/client/webclient/webclient.go:235]: I think this may happen with load balancers etc. in the mix. Perhaps we can suggest that? For example:

```suggestion
			return nil, trace.Wrap(err, "cannot parse ping response; is proxy reachable?")
```

File: api/client/webclient/webclient.go [hunk 4]
```diff
@@ -219,13 +220,24 @@ func Ping(cfg *Config) (*PingResponse, error) {
...
+		}
+
+		return nil, trace.Wrap(errors.New(errResp.Error.Message), "proxy service returned unsuccessful ping response")
```
Comment (Tener) [inline api/client/webclient/webclient.go:238]:
```suggestion
		return nil, trace.Wrap(errors.New(errResp.Error.Message), "proxy service returned unsuccessful ping response; Teleport cluster auth may be misconfigured")
```

**Review by Tener — APPROVED** [review]
Thank you for finding the time to improve the UX! Cryptic error messages are rarely fun.

I have left a couple of suggestions, but treat them merely as such. The overall idea here is to point at possible causes of particular errors. This is tricky though as the overall reason may be different and we risk giving the user the wrong idea.

**Comment by ravicious** [comment]
NVM, I forgot that for a while Connect in dev mode has not been using `--insecure` by default.
