### PR TITLE
Fixes Datadog Incident Management integration by updating on-call API client

### LINKED ISSUE #57790: Access Requests with Datadog Incident Management: case insensitive matching of teleport username and datadog email
What would you like Teleport to do?
Case-insensitive matching of teleport username and datadog email when setting up automatic approvals for [Access Requests with Datadog Incident Management](https://goteleport.com/docs/identity-governance/access-request-plugins/datadog-hosted/).

There is a requirement of this feature that `Automatic approvals requires that the Teleport username matches the Datadog on-call user email.`

If the datadog email does not exactly match the teleport username, this feature will not work, e.g.
teleport username: `My_User@email.com`
datadog email: `my_user@email.com`
^ will not work

What problem does this solve?
Allows easier integration between teleport and datadog and removes confusion during setup.

If a workaround exists, please include it.
Creating new datadog and/or teleport users that have matching case.

### LINKED ISSUE #59458: datadog incident management: Integration is broken due to changes in unstable on-call API
### Expected behavior:
The datadog incident management integration is expected to be able to fetch current on-call users of a datadog team and perform automatic reviews of access requests.

### Current behavior:
The integration is not able to fetch the current on-call users of a datadog team, and does not perform automatic reviews of access requests.

### Bug details:
- Teleport version: v18.2.1
- Recreation steps: Connect a datadog incident management integration following the [documentation](https://goteleport.com/docs/identity-governance/access-request-plugins/datadog-hosted/) and attempt to trigger an automatic review.
- Debug logs:

The unstable `on-call/teams` endpoint originally returned the fields https://github.com/gravitational/teleport/blob/90ec1c81107a149ab77ff5455602a3cd6de16a67/integrations/access/datadog/types.go#L120-L124
- `data` a list of teams. 
- `included` a list of users currently on-call for each team.

But the API no longer returns the `included` field.
```json
{
    "data": [
        {
            "id": "xxxx",
            "type": "teams",
            "attributes": {
                "avatar": "",
                "description": "",
                "handle": "teleport-access",
                "name": "Teleport Access"
            }
        },
        {
            "id": "xxxx",
            "type": "teams",
            "attributes": {
                "avatar": "",
                "description": "",
                "handle": "teleport-datadog-plugin-demo",
                "name": "Teleport Datadog Plugin Demo"
            }
        }
    ]
}
```

Datadog has since released a stable version of the on-call API https://docs.datadoghq.com/api/latest/on-call/

### PR DESCRIPTION
**Pull request by bernardjkim**
Closes: https://github.com/gravitational/teleport/issues/59458 Closes: https://github.com/gravitational/teleport/issues/57790

This PR migrates the Datadog client implementation to use the v2 stable on-call API instead of the unstable API. The request and response structure have changed a bit.

Additional minor change included to fix a bug caused by mismatch in user email casing.

The relevant APIs are:
- https://docs.datadoghq.com/api/latest/teams/#get-all-teams
- https://docs.datadoghq.com/api/latest/on-call/?s=teams#get-team-on-call-users

Required permissions now include:
- `on_call_read` https://docs.datadoghq.com/account_management/rbac/permissions/#on-call
- `teams_manage` https://docs.datadoghq.com/account_management/rbac/permissions/#teams

Note: Changes to permission requirements will be updated in the documentation and enrollment pages in follow up PRs.

Changelog: Fixed auto-approvals in the Datadog Incident Management integration by updating the on-call API client
Changelog: Fixed auto-approvals in the Datadog Incident Management integration to ignore case sensitivity in user emails

### CODE REVIEW

File: integrations/access/datadog/bot.go [hunk 1]
```diff
@@ -166,29 +166,48 @@ func (b Bot) FetchOncallUsers(ctx context.Context, req types.AccessRequest) ([]s
...
-	// Fetch all on-call teams
-	oncallTeams, err := b.datadog.GetOncallTeams(ctx)
-	if err != nil {
-		return nil, trace.Wrap(err)
-	}
+	var teamIDs []string
+
+	// Query a max of 10 pages with 100 teams per page.
+	const maxPages = 10
+	for page := range maxPages {
```
Comment (hugoShaka) [inline integrations/access/datadog/bot.go]: Instead of using a harcoded max amount of pages and doing potentially one request to get nothing, can we use `meta.pagination.total`?

**Review by hugoShaka — APPROVED** [review]
Can you also add the links to the DD API next to the types or functions doing the call?

**Review by tigrato — APPROVED** [review]
