### PR TITLE
Stop using shared buffer in logrus text formatter

### LINKED ISSUE #34410: `TestDynamicClientReuse` flakiness
#### Link(s) to logs

- [https://github.com/gravitational/teleport/actions/runs/<run-id>/jobs/<job-id>](https://github.com/gravitational/teleport/actions/runs/6815541546/job/18534877335?pr=34238#step:6:1642)

#### Relevant snippet
```
 === FAIL: lib/service TestDynamicClientReuse (2.11s)
    testing.go:1465: race detected during execution of test
```

### LINKED ISSUE #34426: `TestMonitor/degraded_event_causes_degraded_state` flakiness
#### Link(s) to logs

https://github.com/gravitational/teleport/actions/runs/6817409957/job/18540859632

#### Relevant snippet

Lengthy race detector output:

<details>
```
=== FAIL: lib/service TestMonitor/degraded_event_causes_degraded_state (0.10s)
INFO [PROC:6]    Detected Teleport component "auth" is running in a degraded state. pid:110440.6 service/state.go:106
==================
WARNING: DATA RACE
Write at 0x00c002b36400 by goroutine 3561:
  runtime.slicecopy()
      /opt/go/src/runtime/slice.go:310 +0x0
  fmt.Append()
      /opt/go/src/fmt/print.go:290 +0x104
  github.com/gravitational/teleport/lib/utils/log.(*writer).writeValue()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:348 +0x62c
  github.com/gravitational/teleport/lib/utils/log.(*writer).writeField()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:323 +0x156
  github.com/gravitational/teleport/lib/utils/log.(*TextFormatter).Format()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:183 +0x475
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:289 +0x123
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect()
      /__w/teleport/teleport/lib/service/connect.go:209 +0x701
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:162 +0xc4
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:72 +0x471
  github.com/gravitational/teleport/lib/service.testVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:936 +0xa4
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck.func3()
      /__w/teleport/teleport/lib/service/service_test.go:926 +0x39
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:[1648](https://github.com/gravitational/teleport/actions/runs/6817409957/job/18540859632#step:6:1649) +0x44

Previous read at 0x00c002b36400 by goroutine 3461:
  runtime.racereadrange()
      <autogenerated>:1 +0x24
  internal/poll.ignoringEINTRIO()
      /opt/go/src/internal/poll/fd_unix.go:736 +0x4cd
  internal/poll.(*FD).Write()
      /opt/go/src/internal/poll/fd_unix.go:380 +0x292
  os.(*File).write()
      /opt/go/src/os/file_posix.go:46 +0xa4
  os.(*File).Write()
      /opt/go/src/os/file.go:183 +0x75
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:294 +0x241
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*processState).update()
      /__w/teleport/teleport/lib/service/state.go:106 +0xa98
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initDiagnosticService.func2()
      /__w/teleport/teleport/lib/service/service.go:3110 +0x20f
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:552 +0x82
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:281 +0x21a

Goroutine 3561 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1648 +0x82a
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:925 +0xe04
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Goroutine 3461 (running) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:276 +0x14a
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:309 +0x2d8
  github.com/gravitational/teleport/lib/service.TestMonitor()
      /__w/teleport/teleport/lib/service/service_test.go:265 +0x797
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44
==================
==================
WARNING: DATA RACE
Write at 0x00c002b36410 by goroutine 3561:
  github.com/gravitational/teleport/lib/utils/log.(*buffer).WriteByte()
      /__w/teleport/teleport/lib/utils/log/buffer.go:48 +0xe4
  github.com/gravitational/teleport/lib/utils/log.(*writer).WriteByte()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:72 +0x67
  github.com/gravitational/teleport/lib/utils/log.(*writer).writeField()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:321 +0x66
  github.com/gravitational/teleport/lib/utils/log.(*TextFormatter).Format()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:211 +0xa2b
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:289 +0x123
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect()
      /__w/teleport/teleport/lib/service/connect.go:209 +0x701
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:162 +0xc4
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:72 +0x471
  github.com/gravitational/teleport/lib/service.testVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:936 +0xa4
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck.func3()
      /__w/teleport/teleport/lib/service/service_test.go:926 +0x39
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Previous read at 0x00c002b36410 by goroutine 3461:
  runtime.racereadrange()
      <autogenerated>:1 +0x24
  internal/poll.ignoringEINTRIO()
      /opt/go/src/internal/poll/fd_unix.go:736 +0x4cd
  internal/poll.(*FD).Write()
      /opt/go/src/internal/poll/fd_unix.go:380 +0x292
  os.(*File).write()
      /opt/go/src/os/file_posix.go:46 +0xa4
  os.(*File).Write()
      /opt/go/src/os/file.go:183 +0x75
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:294 +0x241
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*processState).update()
      /__w/teleport/teleport/lib/service/state.go:106 +0xa98
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initDiagnosticService.func2()
      /__w/teleport/teleport/lib/service/service.go:3110 +0x20f
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:552 +0x82
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:281 +0x21a

Goroutine 3561 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1648 +0x82a
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:925 +0xe04
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Goroutine 3461 (running) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:276 +0x14a
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:309 +0x2d8
  github.com/gravitational/teleport/lib/service.TestMonitor()
      /__w/teleport/teleport/lib/service/service_test.go:265 +0x797
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44
==================
==================
WARNING: DATA RACE
Write at 0x00c002b36454 by goroutine 3561:
  github.com/gravitational/teleport/lib/utils/log.(*buffer).WriteByte()
      /__w/teleport/teleport/lib/utils/log/buffer.go:48 +0xf3
  github.com/gravitational/teleport/lib/utils/log.(*writer).WriteByte()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:72 +0x76
  github.com/gravitational/teleport/lib/utils/log.(*writer).writeKeyValue()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:328 +0x75
  github.com/gravitational/teleport/lib/utils/log.(*writer).writeMap()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:384 +0x39a
  github.com/gravitational/teleport/lib/utils/log.(*TextFormatter).Format()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:215 +0xaaa
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:289 +0x123
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect()
      /__w/teleport/teleport/lib/service/connect.go:209 +0x701
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:162 +0xc4
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:72 +0x471
  github.com/gravitational/teleport/lib/service.testVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:936 +0xa4
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck.func3()
      /__w/teleport/teleport/lib/service/service_test.go:926 +0x39
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Previous read at 0x00c002b36450 by goroutine 3461:
  runtime.racereadrange()
      <autogenerated>:1 +0x24
  internal/poll.ignoringEINTRIO()
      /opt/go/src/internal/poll/fd_unix.go:736 +0x4cd
  internal/poll.(*FD).Write()
      /opt/go/src/internal/poll/fd_unix.go:380 +0x292
  os.(*File).write()
      /opt/go/src/os/file_posix.go:46 +0xa4
  os.(*File).Write()
      /opt/go/src/os/file.go:183 +0x75
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:294 +0x241
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*processState).update()
      /__w/teleport/teleport/lib/service/state.go:106 +0xa98
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initDiagnosticService.func2()
      /__w/teleport/teleport/lib/service/service.go:3110 +0x20f
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:552 +0x82
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:281 +0x21a

Goroutine 3561 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1648 +0x82a
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:925 +0xe04
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Goroutine 3461 (running) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:276 +0x14a
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:309 +0x2d8
  github.com/gravitational/teleport/lib/service.TestMonitor()
      /__w/teleport/teleport/lib/service/service_test.go:265 +0x797
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44
==================
==================
WARNING: DATA RACE
Write at 0x00c002b36458 by goroutine 3561:
  github.com/gravitational/teleport/lib/utils/log.(*buffer).WriteByte()
      /__w/teleport/teleport/lib/utils/log/buffer.go:48 +0x2b3
  github.com/gravitational/teleport/lib/utils/log.(*writer).WriteByte()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:72 +0x238
  github.com/gravitational/teleport/lib/utils/log.(*writer).writeKeyValue()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:331 +0x237
  github.com/gravitational/teleport/lib/utils/log.(*writer).writeMap()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:384 +0x39a
  github.com/gravitational/teleport/lib/utils/log.(*TextFormatter).Format()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:215 +0xaaa
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:289 +0x123
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect()
      /__w/teleport/teleport/lib/service/connect.go:209 +0x701
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:162 +0xc4
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:72 +0x471
  github.com/gravitational/teleport/lib/service.testVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:936 +0xa4
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck.func3()
      /__w/teleport/teleport/lib/service/service_test.go:926 +0x39
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Previous read at 0x00c002b36458 by goroutine 3461:
  runtime.racereadrange()
      <autogenerated>:1 +0x24
  internal/poll.ignoringEINTRIO()
      /opt/go/src/internal/poll/fd_unix.go:736 +0x4cd
  internal/poll.(*FD).Write()
      /opt/go/src/internal/poll/fd_unix.go:380 +0x292
  os.(*File).write()
      /opt/go/src/os/file_posix.go:46 +0xa4
  os.(*File).Write()
      /opt/go/src/os/file.go:183 +0x75
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:294 +0x241
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*processState).update()
      /__w/teleport/teleport/lib/service/state.go:106 +0xa98
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initDiagnosticService.func2()
      /__w/teleport/teleport/lib/service/service.go:3110 +0x20f
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:552 +0x82
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:281 +0x21a

Goroutine 3561 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1648 +0x82a
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:925 +0xe04
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Goroutine 3461 (running) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:276 +0x14a
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:309 +0x2d8
  github.com/gravitational/teleport/lib/service.TestMonitor()
      /__w/teleport/teleport/lib/service/service_test.go:265 +0x797
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44
==================
==================
WARNING: DATA RACE
Write at 0x00c002b36461 by goroutine 3561:
  github.com/gravitational/teleport/lib/utils/log.(*buffer).WriteByte()
      /__w/teleport/teleport/lib/utils/log/buffer.go:48 +0xe4
  github.com/gravitational/teleport/lib/utils/log.(*writer).WriteByte()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:72 +0x67
  github.com/gravitational/teleport/lib/utils/log.(*writer).writeField()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:321 +0x66
  github.com/gravitational/teleport/lib/utils/log.(*TextFormatter).Format()
      /__w/teleport/teleport/lib/utils/log/logrus_formatter.go:220 +0xb04
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:289 +0x123
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect()
      /__w/teleport/teleport/lib/service/connect.go:209 +0x701
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:162 +0xc4
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService()
      /__w/teleport/teleport/lib/service/connect.go:72 +0x471
  github.com/gravitational/teleport/lib/service.testVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:936 +0xa4
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck.func3()
      /__w/teleport/teleport/lib/service/service_test.go:926 +0x39
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Previous read at 0x00c002b36460 by goroutine 3461:
  runtime.racereadrange()
      <autogenerated>:1 +0x24
  internal/poll.ignoringEINTRIO()
      /opt/go/src/internal/poll/fd_unix.go:736 +0x4cd
  internal/poll.(*FD).Write()
      /opt/go/src/internal/poll/fd_unix.go:380 +0x292
  os.(*File).write()
      /opt/go/src/os/file_posix.go:46 +0xa4
  os.(*File).Write()
      /opt/go/src/os/file.go:183 +0x75
  github.com/sirupsen/logrus.(*Entry).write()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:294 +0x241
  github.com/sirupsen/logrus.(*Entry).log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:252 +0x9af
  github.com/sirupsen/logrus.(*Entry).Log()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x8b
  github.com/sirupsen/logrus.(*Entry).Logf()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0xbb
  github.com/sirupsen/logrus.(*Entry).Infof()
      /go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:362 +0x5d
  github.com/gravitational/teleport/lib/service.(*processState).update()
      /__w/teleport/teleport/lib/service/state.go:106 +0xa98
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initDiagnosticService.func2()
      /__w/teleport/teleport/lib/service/service.go:3110 +0x20f
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:552 +0x82
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:281 +0x21a

Goroutine 3561 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1648 +0x82a
  github.com/gravitational/teleport/lib/service.TestTeleportProcessAuthVersionCheck()
      /__w/teleport/teleport/lib/service/service_test.go:925 +0xe04
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44

Goroutine 3461 (running) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:276 +0x14a
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:309 +0x2d8
  github.com/gravitational/teleport/lib/service.TestMonitor()
      /__w/teleport/teleport/lib/service/service_test.go:265 +0x797
  testing.tRunner()
      /opt/go/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1648 +0x44
```
</details>

### PR DESCRIPTION
**Pull request by rosstimothy**
Since the formatter does not directly write the output it creates and instead returns it to later be written we cannot reuse the buffer in a pool without potential races. This reverts the behavior of the formatter to create a new buffer instead of pulling one from a pool of buffers during formatting.

Fixes https://github.com/gravitational/teleport/issues/34426 and https://github.com/gravitational/teleport/issues/34410.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: lib/utils/log/formatter_test.go [hunk 1]
```diff
@@ -379,8 +379,39 @@ func BenchmarkFormatter(b *testing.B) {
...
+	t.Run("logrus", func(t *testing.T) {
+		debugFormatter := NewDefaultTextFormatter(true)
+		require.NoError(t, debugFormatter.CheckAndSetDefaults())
+		logrus.SetFormatter(debugFormatter)
+		logrus.SetOutput(os.Stdout)
+
+		logger := logrus.WithField(trace.Component, "test")
+
+		for i := 0; i < 1000; i++ {
+			go func(i int) {
```
Comment (codingllama) [inline lib/utils/log/formatter_test.go:398]: Use a WaitGroup and wait for all goroutines to return before completing the test.

File: lib/utils/log/formatter_test.go [hunk 2]
```diff
@@ -379,8 +379,39 @@ func BenchmarkFormatter(b *testing.B) {
...
+
+	t.Run("slog", func(t *testing.T) {
+		logger := slog.New(NewSlogTextHandler(os.Stdout, &SlogTextHandlerConfig{
+			EnableColors: true,
+			WithCaller:   true,
+		})).With(trace.Component, "test")
+
+		ctx := context.Background()
+		for i := 0; i < 1000; i++ {
+			go func(i int) {
```
Comment (codingllama) [inline lib/utils/log/formatter_test.go:412]: Ditto.

**Review by codingllama — APPROVED** [review]
LGTM, minus the "leaking" test goroutines.
