### PR TITLE
Make TestLimiter test less flaky (#13526)

### LINKED ISSUE #13526: TestLimiter is flaky
From the CI:

```
FAIL: github.com/gravitational/teleport/lib/srv/regular
FAIL: github.com/gravitational/teleport/lib/srv/regular.TestLimiter
...
    sshserver_test.go:1491: 
        	Error Trace:	sshserver_test.go:1491
        	Error:      	Expected value not to be nil.
        	Test:       	TestLimiter
```
CI Logs:
- https://console.cloud.google.com/cloud-build/builds/a9a86131-7a3f-4485-9e63-8e880039d3ac;step=0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/e301f826-2435-4419-adf5-8d6c1c6470eb?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/d5048ba4-c06a-411d-9718-599a543e393c?project=ci-account

Investigate how to remove the test's reliance on time and make it non-flaky.

### PR DESCRIPTION
**Pull request by EdwardDowling**
Use clockwork fake clock instead of system clock during test

```
[edward@edward-21a0003xus teleport]$ go test -run TestLimiter -race -count=100 ./lib/srv/regular
ok  	github.com/gravitational/teleport/lib/srv/regular	178.904s
```
Unable to replicate panic case shown in ticket but this should address the initial flakiness problem mentioned.

### CODE REVIEW

File: lib/srv/regular/sshserver_test.go [hunk 1]
```diff
@@ -1411,13 +1411,51 @@ func TestClientDisconnect(t *testing.T) {
 	require.NoError(t, clt.Close())
 }
 
+func testHelperWaitForServerStart(t *testing.T, s *Server, config *ssh.ClientConfig, timeout time.Duration) {
+	for end :=  time.After(timeout); true;{
```
Comment (zmb3) [inline lib/srv/regular/sshserver_test.go:1415]:
```suggestion
	for end := time.After(timeout); true;{
```

Extra whitespace.

File: lib/srv/regular/sshserver_test.go [hunk 2]
```diff
@@ -1411,13 +1411,51 @@ func TestClientDisconnect(t *testing.T) {
...
+		select {
+		case <-end:
+			t.Fatalf("Server failed to start after: %v", timeout)
+			return
+		default:
```
Comment (zmb3) [inline lib/srv/regular/sshserver_test.go:1420]: This `default` case is going to execute every time since the read from `end` will block. This is likely not what you want.

Can you rewrite this to use `require.Eventually` instead?

File: lib/srv/regular/sshserver_test.go [hunk 3]
```diff
@@ -1411,13 +1411,51 @@ func TestClientDisconnect(t *testing.T) {
...
 	t.Parallel()
 	f := newFixture(t)
 	ctx := context.Background()
 
+	fClock := &fakeClock{
+		f.clock,
+	}
 	limiter, err := limiter.NewLimiter(
 		limiter.Config{
+			Clock: fClock,
```
Comment (zmb3) [inline lib/srv/regular/sshserver_test.go:1458]: Can we change the clock in here from `timetools` to `clockwork`? 

There's a bit of dependency mess in here, so if it's too much work feel free to push back, but this may be a good opportunity to simplify.

File: lib/srv/regular/sshserver_test.go (hunk 2 above)
Comment (EdwardDowling) [reply lib/srv/regular/sshserver_test.go]: Ah nice i didn't know that existed. TY this will be handy

File: lib/srv/regular/sshserver_test.go (hunk 3 above)
Comment (EdwardDowling) [reply lib/srv/regular/sshserver_test.go]: Yeah I think this would make a lot of sense. Since that will require changing gravitational/oxy it will need to be another PR.
Unless you just mean change it in this test and have the wrapper type just have a clockwork.clock in it instead?

Comment (zmb3) [reply lib/srv/regular/sshserver_test.go]: Ah, yes, now I recall. There's a pretty nasty mailgun dependency mess here.

Our limiter depends on `mailgun/ttlmap`, which depends on `mailgun/timetools`.

Note that we already _also_ depend on `gravitational/ttlmap` in other places. So the best thing would be to replace all uses of the `mailgun/ttlmap` with the gravitational one. When that's done, maybe we can get rid of `mailgun/timetools` as well.

In any case, it's out of scope for this PR. If you have time when you wrap this up to take a look I'd definitely appreciate the help and simplification!

**Comment by EdwardDowling** [comment]
Newest results after some changes
```
[edward@edward-21a0003xus teleport]$ go test -run TestLimiter -race -count=200 ./lib/srv/regular 
ok  	github.com/gravitational/teleport/lib/srv/regular	478.849s
```

File: lib/srv/regular/sshserver_test.go [hunk 4]
```diff
@@ -1411,13 +1411,53 @@ func TestClientDisconnect(t *testing.T) {
...
+		connNumber, err := limiter.GetNumConnection(token)
+		require.NoError(t, err)
+		return connNumber == num
+	}
+}
+
+type fakeClock struct {
+	clock clockwork.FakeClock
+}
+
```
Comment (espadolini) [inline lib/srv/regular/sshserver_test.go:1437]: We should add a `var _ timetools.TimeProvider = (*fakeClock)(nil)` here so it's more clear why we're wrapping `clockwork.FakeClock`.

**Review by espadolini — APPROVED** [review]

File: lib/srv/regular/sshserver_test.go (hunk 4 above)
Comment (espadolini) [reply lib/srv/regular/sshserver_test.go:1438]: `clockwork.FakeClock` is an interface, so I'd expect it to behave like a reference type in almost all cases.

File: lib/srv/regular/sshserver_test.go [hunk 5]
```diff
@@ -1481,8 +1528,8 @@ func TestLimiter(t *testing.T) {
 
 	// current connections = 2
```
Comment (r0mant) [inline lib/srv/regular/sshserver_test.go:1529]: @EdwardDowling I looked at bit into this test and I think that the numbers in these comments are all off which makes it very confusing. For example, above it says "current connections = 1 (one connection is opened from SetUpTest)" which I don't think is true - because we're creating a new SSH server with a new limiter. Also, it says "maxConnections =3" but it's actually 2. Could you fix up these comments so they're accurate while you're here?

File: lib/srv/regular/sshserver_test.go [hunk 6]
```diff
@@ -1492,13 +1539,17 @@ func TestLimiter(t *testing.T) {
 	require.Error(t, err)
 
 	require.NoError(t, se.Close())
+	se.Wait()
 	require.NoError(t, clt.Close())
-	time.Sleep(50 * time.Millisecond)
+	require.ErrorIs(t, clt.Wait(), net.ErrClosed)
```
Comment (r0mant) [inline lib/srv/regular/sshserver_test.go:1544]: I wanted to suggest to use `Wait()` on the client also. If we use it, do we still need time/sleeps here at all?

Upon closer look it doesn't seem like this test depends on timing at all so replacing it with fake clock basically does nothing here.

**Review by r0mant — CHANGES_REQUESTED** [review]

File: lib/srv/regular/sshserver_test.go (hunk 6 above)
Comment (EdwardDowling) [reply lib/srv/regular/sshserver_test.go:1542]: Ah you are right, I'll remove then

File: lib/srv/regular/sshserver_test.go [hunk 7]
```diff
@@ -1401,13 +1402,55 @@ func TestClientDisconnect(t *testing.T) {
 	require.NoError(t, clt.Close())
 }
 
+func testHelperGetWaitForServerStart(t *testing.T, s *Server, config *ssh.ClientConfig) func() bool {
```
Comment (r0mant) [inline lib/srv/regular/sshserver_test.go:1405]: Nit: This would be a more "customary" name for this function.
```suggestion
func getWaitForServerStartFunc(t *testing.T, s *Server, config *ssh.ClientConfig) func() bool {
```

File: lib/srv/regular/sshserver_test.go [hunk 8]
```diff
@@ -1401,13 +1402,55 @@ func TestClientDisconnect(t *testing.T) {
...
+		if clt != nil {
+			require.NoError(t, clt.Close())
+			require.ErrorIs(t, clt.Wait(), net.ErrClosed)
+			return true
+		}
+		return false
+	}
+}
+
+func testHelperGetWaitForNumberOfConns(t *testing.T, limiter *limiter.Limiter, token string, num int64) func() bool {
```
Comment (r0mant) [inline lib/srv/regular/sshserver_test.go:1417]:
```suggestion
func getWaitForNumberOfConnsFunc(t *testing.T, limiter *limiter.Limiter, token string, num int64) func() bool {
```

File: lib/srv/regular/sshserver_test.go [hunk 9]
```diff
@@ -1453,14 +1496,16 @@ func TestLimiter(t *testing.T) {
...
 
-	// maxConnection = 3
-	// current connections = 1 (one connection is opened from SetUpTest)
 	config := &ssh.ClientConfig{
 		User:            f.user,
 		Auth:            []ssh.AuthMethod{ssh.PublicKeys(f.up.certSigner)},
 		HostKeyCallback: ssh.FixedHostKey(f.signer.PublicKey()),
 	}
 
+	require.Eventually(t, testHelperGetWaitForServerStart(t, srv, config), time.Second*10, time.Millisecond*100)
```
Comment (r0mant) [inline lib/srv/regular/sshserver_test.go:1505]: Is this needed? Wouldn't the dial that this method does interfere with the dials that test does itself?

**Review by r0mant — COMMENTED** [review]
Couple more questions, mostly wondering if we need the blocking calls still. Curious if you see flakiness in the test without them.

File: lib/srv/regular/sshserver_test.go [hunk 10]
```diff
@@ -1469,43 +1514,49 @@ func TestLimiter(t *testing.T) {
...
 	require.Error(t, err)
 
 	require.NoError(t, se.Close())
+	se.Wait()
 	require.NoError(t, clt.Close())
-	time.Sleep(50 * time.Millisecond)
+	require.ErrorIs(t, clt.Wait(), net.ErrClosed)
 
-	// current connections = 2
+	require.Eventually(t, testHelperGetWaitForNumberOfConns(t, limiter, "127.0.0.1", 1), time.Second*10, time.Millisecond*100)
```
[the remark this answers is not in the document]
Comment (EdwardDowling) [reply lib/srv/regular/sshserver_test.go:1534]: I have yet to see any flakiness since adding these lines. Without them the tests are still flaky.

[the remark this answers is not in the document]
Comment (r0mant) [reply lib/srv/regular/sshserver_test.go:1534]: Got it.

**Review by r0mant — APPROVED** [review]

File: lib/srv/regular/sshserver_test.go (hunk 9 above)
Comment (EdwardDowling) [reply lib/srv/regular/sshserver_test.go]: You are right this isn't needed. I'll remove it now. 
Would it interfere with the rest since the connection is closed?
