### PR TITLE
Use the correct k8s port in tctl auth sign --format=kubernetes

### LINKED ISSUE #4408: tctl auth sign --format=kubernetes uses the wrong proxy address and HTTP by default
**What happened**: I added a local user and used `tctl auth sign` to generate a `kubeconfig`:

```console
# tctl auth sign --format=kubernetes --user=gus --out=test.kubeconfig --ttl=168h

The credentials have been written to test.kubeconfig
```

1) I didn't specify the `--proxy` argument so expected a sane default to be picked, but the server address is incorrectly set to the web proxy port (3080) rather than the Kubernetes proxy port (3026) in the generated `test.kubeconfig` file:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUd...
    server: example-root.gravitational.co:3080
  name: example-root.gravitational.co
contexts:
- context:
    cluster: example-root.gravitational.co
    user: example-root.gravitational.co
  name: example-root.gravitational.co
current-context: example-root.gravitational.co
kind: Config
preferences: {}
users:
- name: example-root.gravitational.co
  user:
    client-certificate-data: LS0tLS1CRUd...
    client-key-data: LS0tLS1CRUd...
```

This (predictably) doesn't work with `kubectl`:

```console
$ kubectl --v=5 --kubeconfig=test.kubeconfig get nodes
I0930 11:52:33.883644 2830154 cached_discovery.go:121] skipped caching discovery info due to Get http://example-root.gravitational.co:3080/api?timeout=32s: EOF
I0930 11:52:33.942693 2830154 cached_discovery.go:121] skipped caching discovery info due to Get http://example-root.gravitational.co:3080/api?timeout=32s: EOF
I0930 11:52:33.942735 2830154 shortcut.go:89] Error loading discovery information: Get http://example-root.gravitational.co:3080/api?timeout=32s: EOF
I0930 11:52:34.000724 2830154 cached_discovery.go:121] skipped caching discovery info due to Get http://example-root.gravitational.co:3080/api?timeout=32s: EOF
I0930 11:52:34.059347 2830154 cached_discovery.go:121] skipped caching discovery info due to Get http://example-root.gravitational.co:3080/api?timeout=32s: EOF
I0930 11:52:34.130961 2830154 cached_discovery.go:121] skipped caching discovery info due to Get http://example-root.gravitational.co:3080/api?timeout=32s: EOF
I0930 11:52:34.131010 2830154 helpers.go:217] Connection error: Get http://example-root.gravitational.co:3080/api?timeout=32s: EOF
F0930 11:52:34.131026 2830154 helpers.go:114] Unable to connect to the server: EOF
```

2) I manually changed the address to use the correct port (`example-root.gravitational.co:3026`), but then this happened:

```console
$ kubectl --v=5 --kubeconfig=test.kubeconfig get nodes
I0930 11:52:47.071968 2830193 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0930 11:52:47.072069 2830193 cached_discovery.go:121] skipped caching discovery info due to the server rejected our request for an unknown reason
I0930 11:52:47.140035 2830193 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0930 11:52:47.140059 2830193 cached_discovery.go:121] skipped caching discovery info due to the server rejected our request for an unknown reason
I0930 11:52:47.140078 2830193 shortcut.go:89] Error loading discovery information: the server rejected our request for an unknown reason
I0930 11:52:47.207345 2830193 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0930 11:52:47.207373 2830193 cached_discovery.go:121] skipped caching discovery info due to the server rejected our request for an unknown reason
I0930 11:52:47.292212 2830193 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0930 11:52:47.292231 2830193 cached_discovery.go:121] skipped caching discovery info due to the server rejected our request for an unknown reason
I0930 11:52:47.355611 2830193 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I0930 11:52:47.355628 2830193 cached_discovery.go:121] skipped caching discovery info due to the server rejected our request for an unknown reason
I0930 11:52:47.355773 2830193 helpers.go:199] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server rejected our request for an unknown reason",
  "reason": "BadRequest",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "Client sent an HTTP request to an HTTPS server."
      }
    ]
  },
  "code": 400
}]
F0930 11:52:47.355811 2830193 helpers.go:114] Error from server (BadRequest): the server rejected our request for an unknown reason
```

At this point, I changed the `server` address to `https://example-root.gravitational.co:3026` and everything works:

```console
$ kubectl --v=5 --kubeconfig=test.kubeconfig get nodes
NAME                                             STATUS   ROLES    AGE    VERSION
gke-teleport-demo-cluster-pool-1-afbf7cbd-x5ck   Ready    <none>   124d   v1.14.10-gke.36
```

**What you expected to happen**:
1) `tctl auth sign --format=kubeconfig` without a `--proxy` argument should use port 3026 rather than 3080 by default in the `server` address
2) `https://` should be prepended to the beginning of the `server` address

**How to reproduce it (as minimally and precisely as possible)**: See above.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.6git:v4.3.6-0-gfabee242d go1.13.2`
- `tctl version`: `Teleport Enterprise v4.3.6git:v4.3.6-0-gfabee242d go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.3.6 git:v4.3.6-0-gfabee242d go1.13.2`
- OS (e.g. from `/etc/os-release`):

Pods:
```
# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GKE

### PR DESCRIPTION
**Pull request by awly**
Previously, it used the public_addr of the proxy directly.
Now it parses it and replaces the port with k8s port.

Fixes https://github.com/gravitational/teleport/issues/4408

### CODE REVIEW

File: lib/service/cfg.go [hunk 1]
```diff
@@ -347,12 +347,27 @@ type ProxyConfig struct {
...
 }
 
+func (c ProxyConfig) KubeAddr() (string, error) {
+	if !c.Kube.Enabled {
+		return "", trace.NotFound("kubernetes support not enabled on this proxy")
+	}
+	if len(c.Kube.PublicAddrs) > 0 {
+		return c.Kube.PublicAddrs[0].String(), nil
+	}
+	host := "<replace this with proxy hostname>"
```
Comment (webvictim) [inline lib/service/cfg.go:357]: I think we usually use `<proxyhost>` as a placeholder in other situations where this might occur.

File: tool/tctl/common/auth_command_test.go [hunk 2]
```diff
@@ -46,35 +50,99 @@ func TestAuthSignKubeconfig(t *testing.T) {
...
+		{
+			desc: "k8s proxy running locally without public_addr",
+			ac: AuthCommand{
+				output:       filepath.Join(tmpDir, "kubeconfig"),
+				outputFormat: identityfile.FormatKubernetes,
+				config: &service.Config{Proxy: service.ProxyConfig{
+					Kube: service.KubeProxyConfig{
+						Enabled: true,
+					},
+					PublicAddrs: []utils.NetAddr{{Addr: "proxy-from-config.example.com:3080"}},
```
Comment (webvictim) [inline tool/tctl/common/auth_command_test.go:101]: Is there a situation where we shouldn't be appending `https://` to the Kubernetes proxy address? I appreciate that this is just a unit test, but it might be more representative of reality if the test addresses also had the prefix.

**Comment by webvictim** [comment]
retest this please

File: tool/tctl/common/auth_command_test.go (hunk 2 above)
Comment (awly) [reply tool/tctl/common/auth_command_test.go:101]: good point, changed the logic to always prepend `https://`

File: tool/tctl/common/auth_command.go [hunk 3]
```diff
@@ -400,20 +401,28 @@ func (a *AuthCommand) checkProxyAddr(clusterAPI auth.ClientI) error {
...
-		if addr := p.GetPublicAddr(); addr != "" {
-			a.proxyAddr = addr
-			return nil
+		addr := p.GetPublicAddr()
+		if addr == "" {
+			continue
 		}
+		uaddr, err := utils.ParseAddr(addr)
+		if err != nil {
+			logrus.Warningf("invalid public address on the proxy %q: %q: %v", p.GetName(), addr, err)
```
Comment (russjones) [inline tool/tctl/common/auth_command.go:421]:
```suggestion
			logrus.Warningf("Invalid public address on the proxy %q: %q: %v.", p.GetName(), addr, err)
```

**Review by russjones — COMMENTED** [review]
@awly This will only work if you are running Auth/Proxy in the same service or you have an identity file + running on the proxy right. Is this intended?

**Review by webvictim — APPROVED** [review]
LGTM, I'll let others approve too.

**Comment by awly** [comment]
@russjones it should work if you have auth and proxy separate too.
https://github.com/gravitational/teleport/pull/4419/files#diff-eaaccc3ece12f8331984b5003420a6c8R409-R426 fetches a list of registered proxies and takes any `public_addr` (with modified port)

**Review by fspmarshall — APPROVED** [review]

**Comment by awly** [comment]
retest this please

**Comment by awly** [comment]
retest this please
