### PR TITLE
Fix not being able to "login" with auth type set to sso but no connectors set yet

### LINKED ISSUE #27466: Web UI: can't log in as a local user when auth preference is SAML and no connector exists
It should be possible to set your cluster auth preference to SAML before you've created a SAML connector. In this case, local user login should work. `tsh` is able to log in when `--auth=local` is provided, but in the web UI you see the following error:

image

It looks like the login did succeed and I did get a valid session token. The web UI's requests for cluster alerts and license status completed successfully. It appears that the `/webapi/ping` endpoint fails with a `400 Bad Request` and that this causes the web UI to display an error page: 

```json
{
    "error": {
        "message": "no saml connectors found"
    }
}
```

Proxy logs show the following (note the empty `""` cluster name):

```
2023-06-06T10:01:44-06:00 WARN [WEB]       Failed to query site. cluster-name: error:[
ERROR REPORT:
Original Error: *trace.NotFoundError cluster &#34;&#34; is not found
Stack Trace:
	github.com/gravitational/teleport/lib/reversetunnel/srv.go:1021 github.com/gravitational/teleport/lib/reversetunnel.(*server).GetSite
	github.com/gravitational/teleport/lib/reversetunnel/api_with_roles.go:86 github.com/gravitational/teleport/lib/reversetunnel.(*TunnelWithRoles).GetSite
	github.com/gravitational/teleport/lib/web/apiserver.go:3526 github.com/gravitational/teleport/lib/web.(*Handler).getSiteByClusterName
	github.com/gravitational/teleport/lib/web/apiserver.go:3511 github.com/gravitational/teleport/lib/web.(*Handler).getSiteByParams
	github.com/gravitational/teleport/lib/web/apiserver.go:3490 github.com/gravitational/teleport/lib/web.(*Handler).authenticateRequestWithCluster
	github.com/gravitational/teleport/lib/web/apiserver.go:3714 github.com/gravitational/teleport/lib/web.(*Handler).unauthenticatedLimiterFunc.func1
	github.com/gravitational/teleport/lib/httplib/httplib.go:109 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1
	github.com/julienschmidt/httprouter@v1.3.0/router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	net/http/server.go:2165 net/http.StripPrefix.func1
	net/http/server.go:2122 net/http.HandlerFunc.ServeHTTP
	github.com/gravitational/teleport/lib/web/apiserver.go:435 github.com/gravitational/teleport/lib/web.NewHandler.func1
	net/http/server.go:2122 net/http.HandlerFunc.ServeHTTP
	github.com/julienschmidt/httprouter@v1.3.0/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	github.com/gravitational/teleport/lib/web/apiserver.go:296 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
	github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
	github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
	github.com/gravitational/teleport/lib/httplib/httplib.go:94 github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1
	net/http/server.go:2122 net/http.HandlerFunc.ServeHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
	net/http/server.go:2936 net/http.serverHandler.ServeHTTP
	net/http/server.go:1995 net/http.(*conn).serve
	runtime/asm_arm64.s:1172 runtime.goexit
User Message: cluster &#34;&#34; is not found] web/apiserver.go:3528
```

I've reproduced this on commit `g8c9fd0ceb7`.

### PR DESCRIPTION
**Pull request by kimlisa**
fixes https://github.com/gravitational/teleport/issues/27466
regression starts from `v12.1.3` 

The web UI was calling the `ping` endpoint where out of all the fields given in response, we only utilized flags for `assist` and `automatic upgrades`, but this endpoint did a bunch of other things such as looking up sso connectors. The `/ping` endpoint will return an error if cluster auth setting is set to either github,saml,oidc and no connectors were found.

I wasn't sure if this was already thought of (putting flags into webconfig instead) and there was a reason why we decided to call the public endpoint `ping` after calling private `usercontext`. If there is a reason, there is another way to fix it that keeps the original behavior, but if not, this PR saves a trip to the backend and save doing extra work. 

The web config is retrieved before the user is logged in (if this bit matters)

Also, if this fix is accepted, i am wondering if the flag `assist` and `automatic upgrade` is necessary in the web `ping` response? (tried looking into it and looked like it was only useful for the web UI) We have two ping endpoints where if i understand correctly, should give the same result (just handling of looking up sso connectors is different), and the response has diverged b/c of these flags (the two ping endpoints is used [here](https://github.com/gravitational/teleport/blob/5d53c91c7a8d41391422171749b3a3d7f23084ab/api/client/webclient/webclient.go#L205))

#### Manual testing
I tested that `automatic upgrades` can be enabled starting teleport with flag `TELEPORT_AUTOMATIC_UPGRADES=1` and disabled without the flag

~~I am still working on trying to test out the assist flag~~ tested by jakule 🙏 

To test yourself, start teleport with the flags you want to see enabled/disabled, load the web page, and under networks tab look for `config.js` request.

### CODE REVIEW

**Review by marcoandredinis — APPROVED** [review]
Thank you for fixing this :pray: 
I tested Automatic Upgrades as well and it works as expected :+1:

File: lib/web/apiserver.go [hunk 1]
```diff
@@ -1408,13 +1408,24 @@ func (h *Handler) getWebConfig(w http.ResponseWriter, r *http.Request, p httprou
 
 	// get tunnel address to display on cloud instances
 	tunnelPublicAddr := ""
-	if clusterFeatures.GetCloud() {
-		proxyConfig, err := h.cfg.ProxySettings.GetProxySettings(r.Context())
-		if err != nil {
-			h.log.WithError(err).Warn("Cannot retrieve ProxySettings, tunnel address won't be set in Web UI.")
-		} else {
+	assistEnabled := false // TODO(jakule)
```
Comment (jakule) [inline lib/web/apiserver.go:1411]: Impersonated TODO. Can I at least know what needs to be done? 😅

File: lib/web/apiserver.go [hunk 2]
```diff
@@ -1408,13 +1408,24 @@ func (h *Handler) getWebConfig(w http.ResponseWriter, r *http.Request, p httprou
...
+	proxyConfig, err := h.cfg.ProxySettings.GetProxySettings(r.Context())
+	if err != nil {
+		h.log.WithError(err).Warn("Cannot retrieve ProxySettings, tunnel address won't be set in Web UI.")
+	} else {
+		if clusterFeatures.GetCloud() {
```
Comment (jakule) [inline lib/web/apiserver.go:1416]: Why did we switch the logic from if the cloud get proxy setting to always get the proxy settings and set only in the cloud?

File: lib/web/apiserver.go (hunk 1 above)
Comment (kimlisa) [reply lib/web/apiserver.go:1411]: sorry, i think i  misunderstood. it was related to the TODO block for below (mostly copy pasta), i thought it meant to delete the whole block and flag (didn't want you to miss it and let it always be false)

i'll just remove the comment 😅 

```go
// TODO(jakule): This part should be removed once the plugin support is added to OSS.
		if proxyConfig.AssistEnabled {
			enabled, err := h.cfg.ProxyClient.IsAssistEnabled(r.Context())
			if err != nil {
				return nil, trace.Wrap(err)
			}

			// disable if auth doesn't support assist
			assistEnabled = enabled.Enabled
		}
```

File: lib/web/apiserver.go (hunk 2 above)
Comment (kimlisa) [reply lib/web/apiserver.go:1416]: the proxy setting was needed for checking if assist was enabled as well

File: lib/web/apiserver.go (hunk 1 above)
Comment (jakule) [reply lib/web/apiserver.go:1411]: It's fine. I'd just add `remove when plugins are implemented` as otherwise it's not clear what should be done without any context.

**Review by jakule — APPROVED** [review]
Tested OSS and in the Cloud. Works fine.

**Comment by kimlisa** [comment]
re: removing flags, i'll do this in another PR as discussed on slack
