### PR TITLE
 Fix transport request marshaling for old clusters.

### LINKED ISSUE #2748: Regression: 4.0.0 Teleport can't communicate with 3.2.0 cluster
## Steps to reproduce

* Create a two 3.2.0 clusters, main and trusted.
* Then, following the upgrade sequence, 
https://gravitational.com/teleport/docs/admin-guide/#upgrade-sequence

upgrade the main cluster.

* Trusted cluster becomes inaccessible. The following errors are visible in the logs:

```
one          | DEBU [PROXY:SER] Requesting connection to @remote-auth-server [] in remote cluster two. cluster:two reversetunnel/remotesite.go:577
one          | WARN [PROXY:SER] Request for connection to remote site failed: dial tcp: address {"address":"@remote-auth-server","Exclusive":false}: too many colons in address. cluster:two reversetunnel/remotesite.go:585

```
In addition to that. We can spot that `exclusive` is being marshaled incorrectly (and not sure if it's necessary to marshal at all.

Looks like it is caused by the new logic here:

https://github.com/gravitational/teleport/blob/master/lib/reversetunnel/transport.go#L145

The 3.2 logic is broken because it expects the string in another format:

https://github.com/gravitational/teleport/blob/v3.2.3/lib/reversetunnel/agent.go#L349

Compared to master

https://github.com/gravitational/teleport/blob/master/lib/reversetunnel/transport.go#L208

@russjones when you return back, the following questions are to be answered:

* Is this JSON stuff really necessary in 4.0? If it does not bring anything to the table in terms of functionality, revert it back to preserve backwards compatibility

* If it's absolutely necessary to have it, we should find a way for main cluster to understand that it talks to legacy version and send back dial requests in the old format during the migration procedure. All-in-all this should be fixed as it breaks our backwards compatibility guarantee.

This is a release blocker.

### PR DESCRIPTION
**Pull request by russjones**
**Description**

Pass version information between Trusted Clusters using global requests to allow clusters to request the version of Teleport of the remote cluster and then correctly marshal transport requests to that cluster.

When a remote cluster establishes a connection to a local cluster, only instantiate a auth cache if the remote cluster supports it. Older clusters like 3.2 do not support auth caches, because the auth cache relies on the Auth API having support for Watches.

In the proxy subsystem, pass ServerID (hostUUID.clusterName) when calling Dial on a cluster instead of passing SearchNames (list of principals).

Passing SearchNames was ununnecessary, nodes only register themselves by serverID (hostUUID.clusterName) and looking up SearchNames could lead to bugs.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/2748

### CODE REVIEW

File: lib/reversetunnel/srv.go [hunk 1]
```diff
@@ -1002,11 +1015,43 @@ func newRemoteSite(srv *server, domainName string) (*remoteSite, error) {
...
+// If a response is not received within one second, it's assumed it's a legacy
+// cluster.
+func sendVersionRequest(sconn ssh.Conn, closeContext context.Context) (string, error) {
+	errorCh := make(chan error, 1)
+	versionCh := make(chan string, 1)
+
+	go func() {
+		ok, payload, err := sconn.SendRequest(versionRequest, true, nil)
+		if err != nil {
+			errorCh <- err
```
Comment (r0mant) [inline lib/reversetunnel/srv.go]: Add `return` after this?

File: lib/reversetunnel/srv.go [hunk 2]
```diff
@@ -1002,11 +1015,43 @@ func newRemoteSite(srv *server, domainName string) (*remoteSite, error) {
...
+		}
+		if !ok {
+			errorCh <- trace.BadParameter("no response to %v request", versionRequest)
```
Comment (r0mant) [inline lib/reversetunnel/srv.go]: Here too.

File: lib/reversetunnel/transport.go [hunk 3]
```diff
@@ -101,13 +101,17 @@ type dialReq struct {
 	// special non-resolvable address like @remote-auth-server.
 	Address string `json:"address,omitempty"`
 
-	// SearchNames is a list of aliases for the host. SearchNames is used when
+	// ServerID is the hostUUID.clusterName of th enode. ServerID is used when
 	// dialing through a tunnel.
-	SearchNames []string `json:"search_names,omitempty"`
+	ServerID string `json:"server_id,omitempty"`
```
Comment (r0mant) [inline lib/reversetunnel/transport.go]: Won't this change in the json tag here and below cause some sort of compatibility issues b/w older/newer clusters?

**Review by r0mant — APPROVED** [review]

File: lib/reversetunnel/srv.go (hunk 1 above)
Comment (russjones) [reply lib/reversetunnel/srv.go]: Good catch, fixed.

File: lib/reversetunnel/srv.go (hunk 2 above)
Comment (russjones) [reply lib/reversetunnel/srv.go]: Good catch, fixed.

File: lib/reversetunnel/transport.go (hunk 3 above)
Comment (russjones) [reply lib/reversetunnel/transport.go]: This feature has not been released officially yet, will be in 4.0.0 final release.
