### PR TITLE
fix: enhance multi-resource editing in tctl edit

### LINKED ISSUE #38531: `tctl edit <resource_kind>` only applies the first resource in the list
Expected behavior:

If you perform `tctl edit <resource_kind>` instead of `tctl edit <resource_kind>/<resource_name> `, you'll be shown an editor with all of the resources of the given kind. For example, with `tctl edit roles` you'll see something like:

```vim
kind: role
metadata:
  description: Approves any access request
  id: 1708566131565499014
  labels:
    teleport.internal/resource-type: system
    teleport.internal/revision: "1"
  name: '@teleport-access-approver'
  revision: 299bd4e4-4da9-4120-a57d-6ffb6d2c48ad
spec:
  ...
version: v7
---
kind: role
metadata:
  description: Access cluster resources
  id: 1708549647357130812
  labels:
    teleport.internal/resource-type: preset
  name: access
  revision: c9073603-c4bf-414d-a590-746486b458aa
spec:
  ...
version: v7
---
kind: role
metadata:
  description: Review cluster events and replay sessions
  id: 1708549647354423484
  labels:
    teleport.internal/resource-type: preset
  name: auditor
  revision: b0dda408-831e-4c86-9161-60a079270594

Resolution: 

This functionality should either be disabled or properly implemented.
spec:
  ...
version: v7
---
...
```

As a user, you'd think this means you can update all the roles at once.

Current behavior:

Once you close the editor, only the first resource is updated:

```
> tctl edit roles
// complete edits
role '@teleport-access-approver' has been updated
```

### PR DESCRIPTION
**Pull request by tigrato**
This PR enhances tctl edit command to support multiple resources such as when editing all roles.

`tctl edit roles`

Now, all updated roles are reflected into the backend and not only the first one.

Changelog: Support multiple resource editing in `tctl edit` when editing collections

Fixes #38531

### CODE REVIEW

File: tool/tctl/common/edit_command.go [hunk 1]
```diff
@@ -149,11 +151,19 @@ func (e *EditCommand) editResource(ctx context.Context, client *authclient.Clien
...
 	}
 
-	originalName, err := resourceName(f.Name())
+	originalResources, err := editResources(f.Name())
 	if err != nil {
 		return trace.Wrap(err)
 	}
 
+	key := func(r services.UnknownResource) string {
+		return fmt.Sprintf("%s/%s", r.Kind, r.GetName())
```
Comment (zmb3) [inline tool/tctl/common/edit_command.go:160]: Don't we have a func in the backend package for this? (Instead of using sprintf)

**Review by zmb3 — APPROVED** [review]

File: tool/tctl/common/edit_command.go (hunk 1 above)
Comment (tigrato) [reply tool/tctl/common/edit_command.go:160]: it’s not specifically meant for the backend since the data doesn’t really depend on that. In fact, it should only support a single Kind - from what I remember all collections only support a single kind.  I left it as is just in case someone starts using multiple kinds and the names collide

**Review by avatus — APPROVED** [review]
