### PR TITLE
Fix flaky test for reissuing certificate for local kube proxy.

### LINKED ISSUE #43821: `TestKubeMiddleware/expired_certificate_is_still_reissued_if_request_context_expires` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/9783519373/job/27012313611?pr=43644

#### Relevant snippet

```
=== Failed
=== FAIL: lib/srv/alpnproxy TestKubeMiddleware/expired_certificate_is_still_reissued_if_request_context_expires (0.00s)
    local_proxy_test.go:540: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/alpnproxy/local_proxy_test.go:540
        	Error:      	Not equal: 
        	            	expected: 500
        	            	actual  : 200
        	Test:       	TestKubeMiddleware/expired_certificate_is_still_reissued_if_request_context_expires

=== FAIL: lib/srv/alpnproxy TestKubeMiddleware (2.60s)
```

### PR DESCRIPTION
**Pull request by AntonAM**
In CPU-constrained environment reissuing goroutine managed to successfully finish before parent goroutine had a chance to check if context is expired, so we got unexpected successful result even though we provided already expired context. We use `require.Eventually` to account for this rare event.

Fixes https://github.com/gravitational/teleport/issues/43821

### CODE REVIEW

**Review by marcoandredinis — APPROVED** [review]

File: lib/srv/alpnproxy/local_proxy_test.go [hunk 1]
```diff
@@ -533,12 +533,18 @@ func TestKubeMiddleware(t *testing.T) {
...
+		// successfully finish before the parent goroutine has a chance to check the context (and see that it's expired).
+		require.Eventually(t, func() bool {
+			rw = responsewriters.NewMemoryResponseWriter()
+			// HandleRequest will reissue certificate if needed.
+			km.HandleRequest(rw, req)
+
+			// request timed out.
+			return rw.Status() == http.StatusInternalServerError
+
+		}, time.Second, 100*time.Millisecond)
```
Comment (zmb3) [inline lib/srv/alpnproxy/local_proxy_test.go:547]: I would wait for 3-5 seconds. 1 second rarely seems long enough for us.

Comment (AntonAM) [reply lib/srv/alpnproxy/local_proxy_test.go]: This happens so rarely I think 10 attempts would be enough, but no harm in increasing the timeout to 5 seconds anyway - done.

**Review by zmb3 — APPROVED** [review]
