### PR TITLE
Remove agent binary before retrying Connect My Computer setup

### LINKED ISSUE #34342: Connect My Computer: Remove agent binary before retrying setup
If the setup fails and the user clicks "Retry", we should remove the agent binary before restarting the setup. This is because if the download is in any way malformed or something wrong happened with signature verification etc., the error will never get resolved until the user removes the binary from [its location](https://goteleport.com/docs/connect-your-client/teleport-connect/#agent-maintenance) (which is the only workaround for now).

The backstory is that I just ran into Connect My Computer setup failing for the first time. I was setting it up on my old MBP, the setup failed to launch `teleport node configure` with some cryptic error "Unknown system error -85". Console.app didn't show anything interesting when searching for "teleport", but attempting to start the binary from the terminal resulted in the process being immediately killed.

Console.app then shown "taskgated: no signature for pid=8409 (cannot make code: UNIX[No such process])". idk what exactly it is, it's related to signature verification most probably but `codesign --verify --deep --verbose` didn't show any problems.

Finally, just removing the agent from disk and downloading it again fixed the problem.

Other small improvements to consider:

- https://github.com/gravitational/teleport/pull/34829

### PR DESCRIPTION
**Pull request by ravicious**
Closes #34342, this issue also describes the rationale for this change.

During the setup, Connect My Computer downloads the `teleport` binary which it uses to add the device running Connect as an SSH node to the cluster. This PR makes it so that if the setup fails and the user clicks "Retry", we remove the binary. This will result in the binary being downloaded again.

I also included little bits of relevant and less relevant (like the comment about DocumentTshKube) cleanup.

### CODE REVIEW

**Review by gzdunek — APPROVED** [review]

File: web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts [hunk 1]
```diff
@@ -134,6 +134,11 @@ export interface DocumentGatewayCliClient extends DocumentBase {
   status: '' | 'connecting' | 'connected' | 'error';
 }
 
+/**
+ * DocumentGatewayKube replaced DocumentTshKube in Connect v14. Before removing DocumentTshKube
```
Comment (kimlisa) [inline web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts:138]: does "document" in `DocumentXXX` mean like "tabs" ? i know we have some document naming too in teleport but the meaning has always been elusive to me

**Review by kimlisa — APPROVED** [review]

File: web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts (hunk 1 above)
Comment (ravicious) [reply web/packages/teleterm/src/ui/services/workspacesService/documentsService/types.ts:138]: Yep, I think this is where the teleterm package got the concept of documents from. The way I think about it is that a Document is the equivalent of `window.document` in a way, meaning that it represent a particular page under that tab.
