### PR TITLE
Polishing desktop player

### LINKED ISSUE #36781: Desktop access recordings initial progress bar placement bug
When opening a new desktop access recording, the progress bar starts temporarily in roughly the middle of the screen before finding its way to its resting place at the the bottom:

https://github.com/gravitational/teleport/assets/13578537/c84826a9-6680-42f4-982d-d8c6d51aac78

### LINKED ISSUE #36827: Desktop access recording progress bar fails to reach the end in case of error
If a desktop access recording ends due to an error, the progress bar indicator doesn't reach the end of it's available track:

297496198-868e6e21-a361-401c-8cb0-4574bb6589eb

### PR DESCRIPTION
**Pull request by ibeckermayer**
This commit waits for the canvas to be fully defined before rendering the canvas and progress bar, which prevents visual glitches at pageload where the canvas starts out small and then suddenly expands to its full size (moving the progress bar down with it).

Fixes https://github.com/gravitational/teleport/issues/36781

Before:

https://github.com/gravitational/teleport/assets/13578537/c84826a9-6680-42f4-982d-d8c6d51aac78

After:

https://github.com/gravitational/teleport/assets/13578537/511e54e9-fe90-417a-8d56-5206322f8bfb

It also polishes off the error message display and fixes https://github.com/gravitational/teleport/issues/36827

### CODE REVIEW

**Review by ravicious — APPROVED** [review]

**Review by rudream — APPROVED** [review]

File: web/packages/teleport/src/Player/DesktopPlayer.tsx [hunk 1]
```diff
@@ -73,46 +73,62 @@ export const DesktopPlayer = ({
   const isPlaying = playerStatus === StatusEnum.PLAYING;
   const isComplete = isError || playerStatus === StatusEnum.COMPLETE;
 
-  const t = playerStatus === StatusEnum.COMPLETE ? durationMs : time;
+  const t =
+    playerStatus === StatusEnum.COMPLETE || playerStatus === StatusEnum.ERROR
```
Comment (zmb3) [inline web/packages/teleport/src/Player/DesktopPlayer.tsx:77]: Use the existing isComplete variable here.

Comment (ibeckermayer) [reply web/packages/teleport/src/Player/DesktopPlayer.tsx]: https://github.com/gravitational/teleport/pull/36843/commits/0a76a05884adfbc51e75479aeb7d8fefccca6a99

**Review by zmb3 — APPROVED** [review]
