### PR TITLE
fix error encoding for web terminal streaming

### LINKED ISSUE #2109: protobuf - not all output messages are encoded using protobuf
Some messages are not encoded using protobuf.

image

This is in master.

### PR DESCRIPTION
**Pull request by alex-kovoy**
+ closes #2109 
+ a little bit of refactoring

### CODE REVIEW

File: lib/web/terminal.go [hunk 1]
```diff
@@ -112,21 +112,27 @@ func NewTerminal(req TerminalRequest, authProvider AuthProvider, ctx *SessionCon
 		return nil, trace.BadParameter("invalid server name %q: %v", req.Server, err)
 	}
 
-	return &TerminalHandler{
+	terminalHanlder := newTerminalHandler()
```
Comment (russjones) [inline lib/web/terminal.go]: Since you have everything you need to create the terminal handler, why create it then set the fields individually? Why not create the struct yourself or have a `New` function that takes a `Config`. Examples below.

```golang
handler := NewTerminalHandler{
   Foo: "",
   Bar: ""
}
```

```golang
handler := NewTerminalHandler(&Config{
   Foo: "",
   Bar: "",
})
```

Comment (alex-kovoy) [reply lib/web/terminal.go]: > why create it then set the fields individually? 

I added a little factory method to isolate encoder/decoder initialization from the rest of the parameters. This is to make it easer for the unit-tests although it would be better to create that helper in unit-tests to avoid this confusing. 

I thought of adding a configuration object but decided to keep the scope of the changes small.

Comment (klizhentas) [reply lib/web/terminal.go]: This does not look consistent with the style we use in the codebase, which is outlined by @russjones. Just use the options structure and set defaults for encoder and decoder.

**Review by klizhentas — APPROVED** [review]

**Review by russjones — APPROVED** [review]
