### PR TITLE
Handle HTTP connections to TLS socket in a more graceful way

### LINKED ISSUE #2740: Avoid error in MUX by always responding with healthz response to HTTP get requests
## Description

Whenever anyone does HTTP get request when MUX is turned on on, you get: 

```
May 27 21:59:30 proxy1 /usr/local/bin/teleport[6342]: WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *trace.BadParameterError failed to detect protocol by prefix: [71 69 84]\nStack Trace:\n\t/home/sasha/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:318 github.com/gravitational/teleport/lib/multiplexer.detectProto\n\t/home/sasha/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:260 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/home/sasha/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/usr/local/go/src/runtime/asm_amd64.s:2362 runtime.goexit\nUser Message: failed to detect protocol by prefix: [71 69 84]\n" multiplexer/multiplexer.go:200
```
## Solution

It should be easy to respond to GET requests with healthz response, what will make it much easier for default healtchecks done by load balancers to work out of the box.

### PR DESCRIPTION
**Pull request by webvictim**
Fixes #2740 

~This diff is more or less an RFC - if anyone thinks that there's a better way to implement this then please let me know and I'll be happy to do it. I didn't want to extend the full diagnostic endpoint out to here as 1) that isn't really what the issue asks for and 2) it would probably expose too much information about the server to an unauthenticated user.~

~I'm not entirely sure this one is actually `good-starter-issue` material - it gets quite convoluted to deal with at times as there's a lot of different potential modes that this might need to run in.~

~At any rate, this code compiles and successfully responds to any HTTP GET request to port 3080 with an HTTP 200 and `{"status":"ok"}`, just as `/healthz` does on the diagnostic endpoint:~

```
> curl -v http://localhost:3080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3080 (#0)
> GET / HTTP/1.1
> Host: localhost:3080
> User-Agent: curl/7.61.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 30 Jul 2019 19:52:15 GMT
< Content-Length: 15
< 
* Connection #0 to host localhost left intact
{"status":"ok"}
```

The log spam about `failed to detect protocol by prefix:` is also gone.

~Everything else still seems to work OK. The main issue I have currently is that the unit test I wrote doesn't pass. I'm not 100% sure why as I copied a lot of the code and thought I was handling the mux closing properly:~

```
> go test ./lib/multiplexer
----------------------------------------------------------------------
FAIL: multiplexer_test.go:286: MuxSuite.TestMultiplexerHealthcheck

multiplexer_test.go:330:
    c.Assert(err, check.NotNil)
... value = nil

OOPS: 7 passed, 1 FAILED
--- FAIL: Test (0.30s)
FAIL
FAIL    github.com/gravitational/teleport/lib/multiplexer       0.303s
```

~Any input welcomed.~

Scope of the PR changed - we're now just going to detect HTTP connections (so removing the log spam from ~failed to detect protocol by prefix~), output a debug-level message saying `Detected an HTTP request. If this is for a health check, use an HTTPS request instead and drop the connection as before.`

This is a more graceful way to handle the failures without having to add more listeners or split HTTP/TLS traffic in some nasty way.

### CODE REVIEW

File: lib/defaults/defaults.go [hunk 1]
```diff
@@ -46,6 +46,9 @@ const (
 	// run behind an environment/firewall which only allows outgoing connections)
 	SSHProxyTunnelListenPort = 3024
 
+	// Default port to listen locally and respond to HTTP GET health check requests on
+	HealthcheckListenPort = 3027
```
Comment (webvictim) [inline lib/defaults/defaults.go]: This doesn't actually seem to be used - as in, when I run the client I don't see anything binding to `127.0.0.1:3027` as I would expect. I presume that this is a quirk of the multiplexer?

Comment (fspmarshall) [reply lib/defaults/defaults.go]: I don't have all the context, but the way I read the listener setup stuff in `lib/service/service.go` is that yeah, its going to either be multiplexing *or* be using that port.

**Comment by webvictim** [comment]
@klizhentas @russjones ping

File: lib/multiplexer/multiplexer_test.go [hunk 2]
```diff
@@ -281,6 +281,55 @@ func (s *MuxSuite) TestTimeout(c *check.C) {
 	c.Assert(err, check.NotNil)
 }
 
+// TestMultiplexerHealthcheck makes sure that the multiplexer replies with a
+// healthcheck response to an HTTP GET request
+func (s *MuxSuite) TestMultiplexerHealthcheck(c *check.C) {
+	ports, err := utils.GetFreeTCPPorts(1)
+	c.Assert(err, check.IsNil)
+
+	listener, err := net.Listen("tcp", net.JoinHostPort("127.0.0.1", ports[0]))
```
Comment (a-palchikov) [inline lib/multiplexer/multiplexer_test.go]: I think binding to `127.0.0.1:0` and then reading the port from `listener.Addr()` is safer - here's still a chance of a race between `GetFreeTCPPorts` and use of the port.

**Comment by klizhentas** [comment]
I agree with the part of adding a new HTTP handler, disagree with a part of adding a new listener to the process and making socket handoff logic there.

File: lib/multiplexer/multiplexer.go [hunk 3]
```diff
@@ -314,6 +340,8 @@ func detectProto(in []byte) (int, error) {
 		return ProtoSSH, nil
 	case bytes.HasPrefix(in, tlsPrefix):
 		return ProtoTLS, nil
+	case bytes.HasPrefix(in, httpPrefix):
```
Comment (russjones) [inline lib/multiplexer/multiplexer.go]: If the multiplexer is going to break out HTTP connections, then the other [verbs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods) should also be supported.

Maybe something like below. GET is the first verb, so the performance should be the same since it will return from the if statement right away.

```go
func detectProto(in []byte) (int, error) {
	switch {
	// reader peeks only 3 bytes, slice the longer proxy prefix
	case bytes.HasPrefix(in, proxyPrefix[:3]):
		return ProtoProxy, nil
	case bytes.HasPrefix(in, sshPrefix):
		return ProtoSSH, nil
	case bytes.HasPrefix(in, tlsPrefix):
		return ProtoTLS, nil
	case isHTTP(in):
		return ProtoHTTP, nil
	default:
		return ProtoUnknown, trace.BadParameter("failed to detect protocol by prefix: %v", in)
	}
}

// isHTTP returns true if the prefix is for a HTTP method.
func isHTTP(in []byte) bool {
   if in == []byte("GET") || 
      in == []byte("POST") ||
      in == []byte("PUT") || 
      in == []byte("DELETE") ||
      in == []byte("HEAD") ||
      in == []byte("CONNECT") ||
      in == []byte("OPTIONS") ||
      in == []byte("TRACE") ||
      in == []byte("PATCH")  {
      return true
   }
   return false
}
```

**Comment by webvictim** [comment]
@klizhentas Could you detail how you'd prefer that I do it? It seems at the moment like the multiplexer and its underlying listeners are pretty well hardcoded to speak either TLS or SSH, so are you suggesting that I should modify the TLS server's behaviour to identify HTTP traffic coming in and respond differently?

**Comment by klizhentas** [comment]
I would assume socket's protocol switcher will simply the request either to tls or http server, so no extra socket would be necessary.

**Comment by klizhentas** [comment]
I've digged into this. It seems like https server already includes the logic responding 400 to http requests sent to https:


https://go-review.googlesource.com/c/go/+/143177

I suggest to remove all logic except sending all HTTP requests to TLS listener, basically detect HTTP as HTTPS for the purposes of error handling and let https server handle the protocol upgrade with error.

**Comment by webvictim** [comment]
OK, so after talking to @klizhentas the scope of this PR has changed.

We're now just going to detect HTTP connections (so removing the log spam from `failed to detect protocol by prefix`), output a debug-level message saying `Detected an HTTP request. If this is for a health check, use an HTTPS request instead` and drop the connection as before. This is a bit more of a graceful way to handle the failures without having to add more listeners or split HTTP/TLS traffic in some nasty way.

**Review by fspmarshall — APPROVED** [review]

File: lib/multiplexer/multiplexer_test.go [hunk 4]
```diff
@@ -58,10 +58,7 @@ func (s *MuxSuite) SetUpSuite(c *check.C) {
 // TestMultiplexing tests basic use case of multiplexing TLS
 // and SSH on the same listener socket
 func (s *MuxSuite) TestMultiplexing(c *check.C) {
-	ports, err := utils.GetFreeTCPPorts(1)
-	c.Assert(err, check.IsNil)
-
-	listener, err := net.Listen("tcp", net.JoinHostPort("127.0.0.1", ports[0]))
+	listener, err := net.Listen("tcp", net.JoinHostPort("127.0.0.1", "0"))
```
Comment (a-palchikov) [inline lib/multiplexer/multiplexer_test.go]: `net.JoinHostPort("127.0.0.1", "0")` -> `"127.0.0.1:0"`

**Comment by webvictim** [comment]
@klizhentas Are you OK with this now?

**Comment by webvictim** [comment]
@klizhentas ping

**Review by klizhentas — APPROVED** [review]
