### PR TITLE
Fix `tsh db connect` failing to connect to database on separate ports

### LINKED ISSUE #47895: `tsh` fails to connect to Mongo databases when Cluster is on separate port
Expected behavior:
`tsh` connect should succeed

Current behavior:
`tsh db connect --db-user <user> --db-name <name> docdb` fails, when cluster has a separate port for mongo

Bug details:
- Teleport version: v16.4
- Recreation steps: `tsh db connect --db-user <user> --db-name <name> docdb`
- Debug logs
```
ERROR REPORT:
Original Error: *trace.NotFoundError missing GetDatabaseFunc
Stack Trace:
    github.com/gravitational/teleport/lib/client/db/dbcmd/dbcmd.go:548 github.com/gravitational/teleport/lib/client/db/dbcmd.(*CLICommandBuilder).getDatabase
    github.com/gravitational/teleport/lib/client/db/dbcmd/dbcmd.go:479 github.com/gravitational/teleport/lib/client/db/dbcmd.(*CLICommandBuilder).getMongoCommand
    github.com/gravitational/teleport/lib/client/db/dbcmd/dbcmd.go:189 github.com/gravitational/teleport/lib/client/db/dbcmd.(*CLICommandBuilder).GetConnectCommand
```

### PR DESCRIPTION
**Pull request by gabrielcorado**
Closes #47895 by consistently generating the `dbcmd` options even when the local proxy is disabled. A test case was added for this specific issue.

In addition, this PR also has some other refactors:
- Make the `WithGetDatabaseFunc` option a requirement, allowing us to catch such an error in tests if/when another database type uses the function and it was not correctly set up.
- Remove `WithGCP` `dbcmd` option in favor of the get database function. This required a small refactor on the Spanner command generation.

changelog: Fix `tsh db connect` failing to connect to databases using separate ports configuration (non-TLS routing mode).

### CODE REVIEW

File: lib/client/db/dbcmd/dbcmd.go [hunk 1]
```diff
@@ -152,6 +152,10 @@ func NewCmdBuilder(tc *client.TeleportClient, profile *client.ProfileStatus,
 		options.exe = &SystemExecer{}
 	}
 
+	if options.getDatabase == nil {
+		return nil, trace.BadParameter("WithGetDatabaseFunc option is required")
+	}
```
Comment (GavinFrazar) [inline lib/client/db/dbcmd/dbcmd.go]: nit: If it's not too much refactoring effort, should we just make this a required argument for `NewCmdBuilder` instead? That way it's a compiler error to not pass the arg

**Review by GavinFrazar — APPROVED** [review]

File: lib/client/db/dbcmd/dbcmd.go [hunk 2]
```diff
@@ -756,25 +755,35 @@ func (c *CLICommandBuilder) getDynamoDBCommand() (*exec.Cmd, error) {
...
 		// default placeholders for a print command if not all info is available
-		project, instance, database = "<project>", "<instance>", "<database>"
+		if c.options.printFormat {
+			project, instance, database = "<project>", "<instance>", "<database>"
+		} else {
+			return nil, trace.Wrap(err)
+		}
+	} else {
+		gcp = db.GetGCP()
 	}
```
Comment (codingllama) [inline lib/client/db/dbcmd/dbcmd.go:786]: Suggestion: Use a switch for less indent and to make it clearer that `err != nil && c.options.printFormat` is OK:

```suggestion
	db, err := c.getDatabase(ctx)
	switch {
	case err != nil && c.options.printFormat:
		// OK to continue in this case, we'll print the placeholders instead.
		project, instance, database = "<project>", "<instance>", "<database>"
	case err != nil:
		return nil, trace.Wrap(err)
	default:
		gcp = db.GetGCP()
	}
```

Please double-check the comment in the snippet to make sure I got it right.

File: tool/tsh/common/db_test.go [hunk 3]
```diff
@@ -2228,3 +2231,67 @@ func TestDatabaseInfo(t *testing.T) {
 		})
 	}
 }
+
+// TestMongoDBSeparatePortCommandError given a MongoDB database with cluster
+// using separate port mode ensures `tsh` generates the connect command without
+// errors.
+//
+// See https://github.com/gravitational/teleport/issues/47895
```
Comment (codingllama) [inline tool/tsh/common/db_test.go:2240]: +1 for linking the original issue!

File: tool/tsh/common/db_test.go [hunk 4]
```diff
@@ -2228,3 +2231,67 @@ func TestDatabaseInfo(t *testing.T) {
...
+					Protocol: defaults.ProtocolMongoDB,
+					URI:      "external-mongo:27017",
+				},
+			}
+		}),
+	)
+	require.NoError(t, err)
+	t.Cleanup(func() {
+		require.NoError(t, process.Close())
+		require.NoError(t, process.Wait())
```
Comment (codingllama) [inline tool/tsh/common/db_test.go]: nit: Don't abort on cleanups.

```suggestion
		assert.NoError(t, process.Close())
		assert.NoError(t, process.Wait())
```

**Review by codingllama — COMMENTED** [review]
LGTM, minor comments only

File: lib/client/db/dbcmd/dbcmd.go (hunk 1 above)
Comment (codingllama) [reply lib/client/db/dbcmd/dbcmd.go]: As a high-level comment the design here is a bit awkward:

1. The type is called a "builder", but it doesn't work as I'd expect it: no setters, no build() method (instead it "gets" a bunch of commands)
2. The function already has lots of arguments, plus also implements the functional args pattern
3. None of the "required" arguments are validated, but now an optional-looking one is

I'm not asking for changes, but this comment does fit within this thread. If you do go through the trouble of refactoring it you could take into consideration the comments above too.

Comment (gabrielcorado) [reply lib/client/db/dbcmd/dbcmd.go]: Thanks for the input here. This PR is already larger than expected (the scope was to solve an issue affecting customers and to improve the code so we don't have regressions), and moving the function arguments out to a "CheckAndSetDefaults" format or something similar would make this scope even bigger. For now, I'll move this option to a function argument (since it is now required, like the others that are passed as regular function arguments).

> 1. The type is called a "builder", but it doesn't work as I'd expect it: no setters, no build() method (instead it "gets" a bunch of commands)

This is just an ambiguous naming here. The idea is that his "constructs"/"generates" database commands.

> 2. The function already has lots of arguments, plus also implements the functional args pattern

Agreed, it seems the "required options" were kept as regular function arguments. I agree that the list is already extensive. We can propose a better solution for mixing those two (optional + required) arguments afterwards.

> 3. None of the "required" arguments are validated, but now an optional-looking one is

I'll add a simple validation on the required fields for now, and we can later decide where to move it. The option values are still optional, so I'll keep them without validation.

**Review by codingllama — APPROVED** [review]

File: lib/client/db/dbcmd/dbcmd.go (hunk 1 above)
Comment (codingllama) [reply lib/client/db/dbcmd/dbcmd.go]: Happy to discuss ideas if you want.

Comment (greedy52) [reply lib/client/db/dbcmd/dbcmd.go]: just for fun, i asked chatgpt to give redesign a try:

```golang
type CLICommandBuilderConfig struct {
	// Required
	TeleportClient *client.TeleportClient
	Profile        *client.ProfileStatus
	RouteToDB      tlsca.RouteToDatabase
	RootCluster    string
	GetDatabase    GetDatabaseFunc

	// Optional – connection behavior
	...
}

func NewCLICommandBuilder(cfg CLICommandBuilderConfig) (*CLICommandBuilder, error) {
	if cfg.TeleportClient == nil {
		return nil, trace.BadParameter("TeleportClient is required and cannot be nil")
	}
	...
}

type ConfigOption func(*CLICommandBuilderConfig)


func WithLocalProxy(host string, port int, caPath string) ConfigOption {
	return func(cfg *CLICommandBuilderConfig) {
		cfg.LocalProxyHost = host
		cfg.LocalProxyPort = port
		cfg.CAPath = caPath
	}
}
```
not bad
