### PR TITLE
Proxy line support for mysql

### LINKED ISSUE #6517: MySQL listener doesn't support proxy protocol
This causes issues when Teleport is behind a load balancer with proxy protocol feature enabled, e.g. this is the case for Cloud customers.

In such cases mysql client fails to connect with an error like:

```
➜  mysql --defaults-group-suffix=_xxx
ERROR 2026 (HY000): SSL connection error: error:00000000:lib(0):func(0):reason(0)
```

And there are following logs on the proxy:

```
ERRO [DB:PROXY]  Failed to handle MySQL client connection. error:[
ERROR REPORT:
Original Error: *errors.fundamental invalid sequence 88 != 1
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:119 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).performHandshake
	/go/src/github.com/gravitational/teleport/lib/srv/db/mysql/proxy.go:57 github.com/gravitational/teleport/lib/srv/db/mysql.(*Proxy).HandleConnection
	/go/src/github.com/gravitational/teleport/lib/srv/db/proxyserver.go:163 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).ServeMySQL.func1
	/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message: invalid sequence 88 != 1] db/proxyserver.go:165
```

### PR DESCRIPTION
**Pull request by r0mant**
Add proxy protocol support to MySQL listener. Without this, MySQL access doesn't currently work in the Cloud. Fixes https://github.com/gravitational/teleport/issues/6517.

Needs backport to 6.2.

### CODE REVIEW

**Comment by r0mant** [comment]
@awly @fspmarshall Could you folks take a look please?

File: lib/multiplexer/wrappers.go [hunk 1]
```diff
@@ -61,6 +69,28 @@ func (c *Conn) Protocol() int {
 	return c.protocol
 }
 
+// Detect detects the connection protocol by peeking into the first few bytes.
+func (c *Conn) Detect() (int, error) {
```
Comment (awly) [inline lib/multiplexer/wrappers.go:73]: while you're here, can you create a new type for these protocol numbers? something like `type Protocol int`

File: lib/srv/db/mysql/engine.go [hunk 2]
```diff
@@ -178,6 +177,11 @@ func (e *Engine) receiveFromClient(clientConn, serverConn net.Conn, clientErrCh
 	for {
 		packet, err := protocol.ParsePacket(clientConn)
 		if err != nil {
+			if utils.IsOKNetworkError(err) {
+				log.Debug("Client connection closed.")
+				clientErrCh <- nil
```
Comment (awly) [inline lib/srv/db/mysql/engine.go:182]: how about a `defer close(clientErrCh)` at the top of this method?

File: lib/srv/db/mysql/proxy.go [hunk 3]
```diff
@@ -51,10 +52,23 @@ type Proxy struct {
...
+	// Wrap the client connection in the connection that can detect the protocol
+	// by peeking into the first few bytes. This is needed to be able to detect
+	// proxy protocol which otherwise would interfere with MySQL protocol.
+	conn := multiplexer.NewConn(clientConn)
+	server := p.makeServer(conn)
+	// If any error happens, make sure to send it back to the client so it
+	// has a chance to close the connection from its side.
+	defer func() {
+		if err != nil {
+			if writeErr := server.WriteError(err); err != nil {
```
Comment (awly) [inline lib/srv/db/mysql/proxy.go:64]:
```suggestion
			if writeErr := server.WriteError(err); writeErr != nil {
```

File: lib/multiplexer/wrappers.go [hunk 4]
```diff
@@ -61,6 +69,28 @@ func (c *Conn) Protocol() int {
...
+	}
+	return proto, nil
+}
+
+// ReadProxyLine reads proxy-line from the connection.
+func (c *Conn) ReadProxyLine() (*ProxyLine, error) {
+	proxyLine, err := ReadProxyLine(c.reader)
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
```
Comment (awly) [inline lib/multiplexer/wrappers.go:90]: Since you have it, might as well store the proxy line to populate RemoteAddr
```suggestion
	}
	c.proxyLine = proxyLine
```

File: lib/srv/db/mysql/proxy.go [hunk 5]
```diff
@@ -128,6 +151,25 @@ func (p *Proxy) performHandshake(server *server.Conn) (*tls.Conn, error) {
...
+		return trace.Wrap(err)
+	}
+	if proto != multiplexer.ProtoProxy {
+		return nil
+	}
+	proxyLine, err := conn.ReadProxyLine()
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	p.Log.Infof("MySQL listener proxy-line: %s.", proxyLine)
```
Comment (awly) [inline lib/srv/db/mysql/proxy.go:169]:
```suggestion
	p.Log.Debugf("MySQL listener proxy-line: %s.", proxyLine)
```

File: lib/srv/db/proxy_test.go [hunk 6]
```diff
@@ -0,0 +1,192 @@
...
+	"github.com/stretchr/testify/require"
+)
+
+// TestProxyProtocolPostgres ensures that clients can successfully connect to a
+// Postgres database when Teleport is running behind a proxy that sends a proxy
+// line.
+func TestProxyProtocolPostgres(t *testing.T) {
+	ctx := context.Background()
+	testCtx := setupTestContext(ctx, t, withSelfHostedPostgres("postgres"))
+	t.Cleanup(func() { testCtx.Close() })
```
Comment (awly) [inline lib/srv/db/proxy_test.go:40]: optional: have `setupTestContext` add the cleanup function internally

File: lib/srv/db/proxy_test.go [hunk 7]
```diff
@@ -0,0 +1,192 @@
...
+	// Connect to the proxy instead of directly to MySQL listener and make
+	// sure the connection succeeds.
+	mysql, err := testCtx.mysqlClientAddr(proxy.Address(), "alice", "mysql", "root")
+	require.NoError(t, err)
+	require.NoError(t, mysql.Close())
+}
+
+// testProxy is tcp passthrough proxy that sends a proxy-line when connecting
+// to the target server.
+type testProxy struct {
```
Comment (awly) [inline lib/srv/db/proxy_test.go:84]: optional: move this to `lib/multiplexer`, in case other tests need a mock proxy-line implementation

File: lib/srv/db/proxy_test.go [hunk 8]
```diff
@@ -0,0 +1,192 @@
...
+	}
+}
+
+// handleConnection dials the target address, sends a proxy line to it and
+// then starts proxying all traffic b/w client and target.
+func (p *testProxy) handleConnection(clientConn net.Conn) error {
+	serverConn, err := net.Dial("tcp", p.target)
+	if err != nil {
+		return trace.Wrap(err)
+	}
```
Comment (awly) [inline lib/srv/db/proxy_test.go:132]:
```suggestion
	if err != nil {
		clientConn.Close()
		return trace.Wrap(err)
	}
```

File: lib/srv/db/proxy_test.go [hunk 9]
```diff
@@ -0,0 +1,192 @@
...
+	errCh := make(chan error, 2)
+	go func() { // Client -> server.
+		defer clientConn.Close()
+		defer serverConn.Close()
+		// Write proxy-line first and then start proxying from client.
+		err := p.sendProxyLine(clientConn, serverConn)
+		if err == nil {
+			_, err = io.Copy(serverConn, clientConn)
+		}
+		errCh <- err
```
Comment (awly) [inline lib/srv/db/proxy_test.go:143]:
```suggestion
		errCh <- trace.Wrap(err)
```

File: lib/srv/db/proxy_test.go [hunk 10]
```diff
@@ -0,0 +1,192 @@
...
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	defer serverConn.Close()
+	errCh := make(chan error, 2)
+	go func() { // Client -> server.
+		defer clientConn.Close()
+		defer serverConn.Close()
+		// Write proxy-line first and then start proxying from client.
+		err := p.sendProxyLine(clientConn, serverConn)
```
Comment (awly) [inline lib/srv/db/proxy_test.go:139]: Should this be in the Server -> Client goroutine instead?
Otherwise, you have a race between sending proxyline and the actual server sending data

File: lib/srv/db/proxy_test.go [hunk 11]
```diff
@@ -0,0 +1,192 @@
...
+		if err == nil {
+			_, err = io.Copy(serverConn, clientConn)
+		}
+		errCh <- err
+	}()
+	go func() { // Server -> client.
+		defer clientConn.Close()
+		defer serverConn.Close()
+		_, err := io.Copy(clientConn, serverConn)
+		errCh <- err
```
Comment (awly) [inline lib/srv/db/proxy_test.go:149]:
```suggestion
		errCh <- trace.Wrap(err)
```

File: lib/srv/db/mysql/engine.go (hunk 2 above)
Comment (r0mant) [reply lib/srv/db/mysql/engine.go:185]: Done.

File: lib/srv/db/proxy_test.go (hunk 10 above)
Comment (r0mant) [reply lib/srv/db/proxy_test.go]: Hmm, I don't think so? We first send proxy line to the server and then start sending whatever the client has to send?

File: lib/srv/db/mysql/engine.go [hunk 12]
```diff
@@ -174,10 +173,18 @@ func (e *Engine) receiveFromClient(clientConn, serverConn net.Conn, clientErrCh
...
+	defer func() {
+		log.Debug("Stop receiving from client.")
+		close(clientErrCh)
+	}()
 	for {
 		packet, err := protocol.ParsePacket(clientConn)
 		if err != nil {
+			if utils.IsOKNetworkError(err) {
+				log.Debug("Client connection closed.")
+				clientErrCh <- nil
```
Comment (awly) [inline lib/srv/db/mysql/engine.go:185]:
```suggestion
```

File: lib/srv/db/mysql/engine.go [hunk 13]
```diff
@@ -206,11 +213,14 @@ func (e *Engine) receiveFromServer(serverConn, clientConn net.Conn, serverErrCh
...
+		log.Debug("Stop receiving from server.")
+		close(serverErrCh)
+	}()
 	for {
 		packet, err := protocol.ParsePacket(serverConn)
 		if err != nil {
-			if strings.Contains(err.Error(), teleport.UseOfClosedNetworkConnection) {
+			if utils.IsOKNetworkError(err) {
 				log.Debug("Server connection closed.")
 				serverErrCh <- nil
```
Comment (awly) [inline lib/srv/db/mysql/engine.go:225]:
```suggestion
```

**Review by awly — APPROVED** [review]

File: lib/srv/db/proxy_test.go (hunk 10 above)
Comment (awly) [reply lib/srv/db/proxy_test.go]: You're right, forgot proxy line is a server-facing thing

**Review by fspmarshall — APPROVED** [review]

File: lib/srv/db/access_test.go [hunk 14]
```diff
@@ -327,10 +324,15 @@ func (c *testContext) startHandlingConnections() {
 // postgresClient connects to test Postgres through database access as a
 // specified Teleport user and database account.
 func (c *testContext) postgresClient(ctx context.Context, teleportUser, dbService, dbUser, dbName string) (*pgconn.PgConn, error) {
+	return c.postgresClientAddr(ctx, c.mux.DB().Addr().String(), teleportUser, dbService, dbUser, dbName)
+}
+
+// postgresClientAddr like postgresClient but allows to override connection address.
+func (c *testContext) postgresClientAddr(ctx context.Context, address, teleportUser, dbService, dbUser, dbName string) (*pgconn.PgConn, error) {
```
[the remark this answers is not in the document]
Comment (r0mant) [reply lib/srv/db/access_test.go]: Good point!

**Review by russjones — APPROVED** [review]
Bot.
