### PR TITLE
Fix `disconnect_expired_cert` when Kube Identity forwarding is used

### LINKED ISSUE #24910: Kubernetes identity forwarding broke `disconnect_expired_cert`
Expected behavior:
`disconnect_expired_cert` must be respected when certificates expire and Kubernetes identity forwarding is used

Current behavior:
Teleport 13 reads the identity expiration from the proxy certificate and never terminates the connection.

### PR DESCRIPTION
**Pull request by tigrato**
Teleport 13 introduces the identity forwarding mechanism that allows a proxy to forward the client's identity without re-signing a new certificate on his behalf. Proxy uses its certificate key pair and it's valid for a long period of time resulting in the current version not respecting the connection termination.

This PR removes the parsing of the connection certificate and uses the value provided by the unmapped identity - supporting the new and old forwarding methods.

Fixes #24910

### CODE REVIEW

File: lib/kube/proxy/forwarder_test.go [hunk 1]
```diff
@@ -751,6 +751,7 @@ func TestAuthenticate(t *testing.T) {
 					RouteToCluster:    tt.routeToCluster,
 					KubernetesCluster: tt.kubernetesCluster,
 					ActiveRequests:    tt.activeRequests,
+					Expires:           certExpiration,
```
Comment (zmb3) [inline lib/kube/proxy/forwarder_test.go:754]: If I add this line, but don't add the fixes above, the test still passes.

This makes me think we don't actually have a test that verifies this behavior is correct.

**Review by ibeckermayer — COMMENTED** [review]
I'm not quite clear on what identity is what here, but I notice that you say

> This PR removes the parsing of the connection certificate and uses the value provided by the unmapped identity - supporting the new and old forwarding methods.

but you are only using something called `UnmappedIdentity` in the `kubeResourceDeniedAccessMsg`. In `setupContext`, you're using `identity := authCtx.Identity.GetIdentity()`. Probably a definitional matter, but just double checking.

**Review by ibeckermayer — APPROVED** [review]

**Review by espadolini — APPROVED** [review]
