### PR TITLE
Fix file uploads/downloads when user doesn't have a home directory

### LINKED ISSUE #41417: File Upload/Download fails in the Web UI with `insecure-drop` mode set for host user creation
Expected behavior:
File uploads/downloads will succeed when using the `insecure-drop` host user creation drop mode to existing directories (like /tmp)

Current behavior:
File upload/downloads fail to existing directories like /tmp when using the `insecure-drop` mode.
Screenshot 2024-05-10 at 12 44 44 PM (3)

Logs from downloading/uploading to/from an existing /tmp directory
~~~
May 10 16:39:11 Test-Cluster-Node2-US-East-Grafana teleport[30587]: 2024-05-10T16:39:11Z DEBU [SUBSYSTEM] starting SFTP process regular/sftp.go:125
May 10 16:39:11 Test-Cluster-Node2-US-East-Grafana teleport[30587]: Could not set shell's cwd to home directory "/home/idontexisthere", defaulting to "/"
May 10 16:39:11 Test-Cluster-Node2-US-East-Grafana teleport[30587]: ERROR: stat /home/idontexisthere: no such file or directory
May 10 16:39:11 Test-Cluster-Node2-US-East-Grafana teleport[30587]: 2024-05-10T16:39:11Z DEBU [SUBSYSTEM] SFTP process finished regular/sftp.go:197
~~~

Bug details:
- Teleport version: v15
- Recreation steps: Attempt to use the Web UI file upload/download function to an existing directory after logging in as a non-existent user with `insecure-drop` mode set

### PR DESCRIPTION
**Pull request by atburke**
This change fixes a bug where file uploads/downloads in the web UI would fail if the local user (provisioned by Teleport in `insecure-drop` mode) didn't have a home directory.

Fixes #41417.

Changelog: Fixed file upload/download for Teleport-created users in `insecure-drop` mode

### CODE REVIEW

File: lib/utils/host/hostusers.go [hunk 1]
```diff
@@ -65,7 +67,7 @@ func UserAdd(username string, groups []string, home, uid, gid string) (exitCode
 	}
 
 	if home == "" {
-		return -1, trace.BadParameter("home is a required parameter")
+		home = string(os.PathSeparator)
 	}
```
Comment (timothyb89) [inline lib/utils/host/hostusers.go:71]: Definitely a nitpick, but maybe worth a comment here explaining why we default users to `/`? Just seemed a bit surprising, though I can't see any problem with it.

**Review by timothyb89 — APPROVED** [review]

**Review by gzdunek — APPROVED** [review]
