### PR TITLE
Fix `tsh proxy ssh -J leaf-proxy` with root shutdown

### LINKED ISSUE #17184: `tsh proxy ssh -J <leaf.proxy.example.com:3080>` doesn't work with root cluster shut down
Expected behavior:
`tsh proxy ssh -J <leaf.proxy.example.com:3080>` should work with root cluster shut down.

Current behavior:
It fails because it tries to connect to the root proxy.
```
tsh -d proxy ssh -J proxy.remote.com:5080 server02:5022
INFO [CLIENT]    no host login given. defaulting to bjoerger client/api.go:1418
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/run/user/1000/keyring/ssh" client/api.go:3957
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/bjoerger/.tsh/keys/proxy.example.com/dev-x509.pem" valid until "2022-10-08 02:15:21 +0000 UTC". client/keystore.go:319
DEBU [KEYSTORE]  Reading certificates from path "/home/bjoerger/.tsh/keys/proxy.example.com/dev-ssh/leaf-cluster-cert.pub". client/keystore.go:342
INFO [KEYAGENT]  Loading SSH key for user "dev" and cluster "leaf-cluster". client/keyagent.go:202
DEBU             Attempting GET proxy.remote.com:5080/webapi/find webclient/webclient.go:115
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/bjoerger/.tsh/keys/proxy.example.com/dev-x509.pem" valid until "2022-10-08 02:15:21 +0000 UTC". client/keystore.go:319
DEBU [KEYSTORE]  Reading certificates from path "/home/bjoerger/.tsh/keys/proxy.example.com/dev-ssh/leaf-cluster-cert.pub". client/keystore.go:342
INFO [KEYAGENT]  Loading SSH key for user "dev" and cluster "leaf-cluster". client/keyagent.go:202
INFO [CLIENT]    Connecting to proxy=proxy.example.com:3080 login="bjoerger" using TLS Routing client/api.go:2963
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/bjoerger/.tsh/keys/proxy.example.com/dev-x509.pem" valid until "2022-10-08 02:15:21 +0000 UTC". client/keystore.go:319
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:297

ERROR REPORT:
Original Error: *net.OpError dial tcp 127.0.0.1:3080: connect: connection refused
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/utils/proxy/proxy.go:79 github.com/gravitational/teleport/lib/utils/proxy.directDial.dialALPNWithDeadline
	/go/src/github.com/gravitational/teleport/lib/utils/proxy/proxy.go:116 github.com/gravitational/teleport/lib/utils/proxy.directDial.Dial
	/go/src/github.com/gravitational/teleport/lib/client/api.go:3013 github.com/gravitational/teleport/lib/client.makeProxySSHClientWithTLSWrapper
	/go/src/github.com/gravitational/teleport/lib/client/api.go:2964 github.com/gravitational/teleport/lib/client.makeProxySSHClient
	/go/src/github.com/gravitational/teleport/lib/client/api.go:2935 github.com/gravitational/teleport/lib/client.(*TeleportClient).connectToProxy
	/go/src/github.com/gravitational/teleport/lib/client/api.go:2855 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToProxy.func1
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: dial tcp 127.0.0.1:3080: connect: connection refused
```

Note: this was caught in the previous test plan cycle, but not fixed - https://github.com/gravitational/teleport/pull/13854#discussion_r906298369

### PR DESCRIPTION
**Pull request by Joerger**
Closes https://github.com/gravitational/teleport/issues/17184

### CODE REVIEW

File: tool/tsh/proxy_test.go [hunk 1]
```diff
@@ -262,6 +264,100 @@ func TestProxySSH(t *testing.T) {
 	}
 }
 
+// TestProxySSHJumpHost verifies "tsh proxy ssh -J" functionality.
+func TestProxySSHJumpHost(t *testing.T) {
+	lib.SetInsecureDevMode(true)
+	defer lib.SetInsecureDevMode(false)
```
Comment (jakule) [inline tool/tsh/proxy_test.go:270]: nit:
```suggestion
	t.Cleanup(func() {lib.SetInsecureDevMode(false)})
```

**Review by jakule — APPROVED** [review]

**Review by GavinFrazar — APPROVED** [review]
