### PR TITLE
Fix repeated installation for Azure and GCP VM auto-discovery

### LINKED ISSUE #28879: Azure VM auto-discovery keeps executing commands after successful installation
Expected behavior:
Once the node joins the Teleport cluster, AZ VM auto-discovery should stop trying to execute commands into the target machine.

Current behavior:
Installation procedure keeps retrying forever

### PR DESCRIPTION
**Pull request by atburke**
This PR fixes a bug where the keys of labels applied to discovered Azure and GCP VMs did not match the labels the Discovery Service expected, causing the Discovery Service to try to install them again.

This PR also adds a workaround for an Azure quirk where Azure would not run the same command more than once.

Fixes #28879.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: lib/srv/server/azure_installer.go [hunk 1]
```diff
@@ -72,5 +73,14 @@ func (ai *AzureInstaller) Run(ctx context.Context, req AzureRunRequest) error {
 }
 
 func getInstallerScript(installerName, publicProxyAddr string) string {
-	return fmt.Sprintf("curl -s -L https://%s/v1/webapi/scripts/installer/%v | bash -s $@", publicProxyAddr, installerName)
+	// Azure treats scripts with the same content as the same invocation and
+	// won't run them more than once. This is fine when the installer script
+	// succeeds, but it makes troubleshooting much harder when it fails. To
+	// work around this, we generate a random string and append it as a comment
+	// to the script, forcing Azure to see each invocation as unique.
```
Comment (tcsc) [inline lib/srv/server/azure_installer.go:80]: Ouch

**Review by tcsc — APPROVED** [review]
