### PR TITLE
tsh play error handling

### LINKED ISSUE #28191: `tsh play <aws-session-chunk-id>` returns not found
Expected behavior:
`tsh play` should show the session recodring or advice to use the right command to play app session recordings.

Current behavior:
```
 $ tsh play <aws-session-chunk-id>
ERROR: Recording for session  <aws-session-chunk-id> not found.
```
"not found" is very misleading. `tsh play <aws-session-chunk-id> -f json` with the same ID will "export" the session properly.

Bug details:
- Teleport version: master
- Recreation steps: `tsh apps login aws` && `tsh aws s3` and wait for session uploaded
- Debug logs
```
Original Error: *trace.NotFoundError offset 0 not found for session <aws-session-chunk-id>
Stack Trace:

Caught:
	github.com/gravitational/teleport/lib/httplib/httplib.go:198 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	github.com/gravitational/teleport/lib/auth/http_client.go:315 github.com/gravitational/teleport/lib/auth.(*HTTPClient).Get
	github.com/gravitational/teleport/lib/auth/http_client.go:954 github.com/gravitational/teleport/lib/auth.(*HTTPClient).GetSessionChunk
	github.com/gravitational/teleport/lib/client/api.go:1972 github.com/gravitational/teleport/lib/client.(*TeleportClient).Play
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1603 github.com/gravitational/teleport/tool/tsh/common.playSession
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1543 github.com/gravitational/teleport/tool/tsh/common.onPlay
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1214 github.com/gravitational/teleport/tool/tsh/common.Run
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:520 github.com/gravitational/teleport/tool/tsh/common.Main
	github.com/gravitational/teleport/tool/tsh/main.go:24 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_arm64.s:1172 runtime.goexit
User Message: offset 0 not found for session <aws-session-chunk-id>
] common/tsh.go:1605
```

### LINKED ISSUE #28978: `tsh play ./file.tar` should not return "no such file or directory" when the file exists.
### Current behavior:

The current error message when trying to play a non-interactive session could be more helpful:

```console
% ls ./02c0a346-517a-4e09-a9e6-b8e12d3c85fd.tar
./02c0a346-517a-4e09-a9e6-b8e12d3c85fd.tar
% tsh play ./02c0a346-517a-4e09-a9e6-b8e12d3c85fd.tar
ERROR: open : no such file or directory 

% tsh play ./02c0a346-517a-4e09-a9e6-b8e12d3c85fd.tar

ERROR REPORT:
Original Error: *fs.PathError open : no such file or directory
Stack Trace:
	github.com/gravitational/teleport/lib/events/playback.go:184 github.com/gravitational/teleport/lib/events.(*SSHPlaybackWriter).SessionChunks
	github.com/gravitational/teleport/lib/client/api.go:2033 github.com/gravitational/teleport/lib/client.PlayFile
	github.com/gravitational/teleport/tool/tsh/tsh.go:1589 main.playSession
	github.com/gravitational/teleport/tool/tsh/tsh.go:1538 main.onPlay
	github.com/gravitational/teleport/tool/tsh/tsh.go:1209 main.Run
	github.com/gravitational/teleport/tool/tsh/tsh.go:515 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: open : no such file or directory

% tsh play -f json ./02c0a346-517a-4e09-a9e6-b8e12d3c85fd.tar
{"ei":0,"event":"session.start","uid":"6a808967-ad1c-46a2-b724-fe020be2b491","code":"T2000I","time":"2023-07-10T14:32:46.092Z","cluster_name":"cvasquez-teleport-cluster","user":"TeleLos","login":"root","sid":"02c0a346-517a-4e09-a9e6-b8e12d3c85fd","namespace":"default","server_id":"c9a706b7-0b58-4a68-8c48-d43fbe2f37c5","server_hostname":"ip-172-31-43-7.sa-east-1.compute.internal","server_labels":{"teleport.internal/resource-id":"52a5c353-5578-4fe9-9590-8f6b5e325408"},"addr.remote":"127.0.0.1:44786","proto":"ssh","initial_command":["whoami"],"session_recording":"node"}
{"ei":1,"event":"exec","uid":"9e4e1caf-4ed9-4878-9245-ed844b36cf03","code":"T3002I","time":"2023-07-10T14:32:46.271Z","cluster_name":"cvasquez-teleport-cluster","user":"TeleLos","login":"root","addr.local":"172.31.43.7:42306","addr.remote":"127.0.0.1:44786","sid":"02c0a346-517a-4e09-a9e6-b8e12d3c85fd","namespace":"default","server_id":"c9a706b7-0b58-4a68-8c48-d43fbe2f37c5","server_hostname":"ip-172-31-43-7.sa-east-1.compute.internal","command":"whoami","exitCode":"0"}
{"ei":2,"event":"session.end","uid":"6224a9cb-2c23-4bd4-a2b8-a4716ac7665f","code":"T2004I","time":"2023-07-10T14:32:48.271Z","cluster_name":"cvasquez-teleport-cluster","user":"TeleLos","login":"root","sid":"02c0a346-517a-4e09-a9e6-b8e12d3c85fd","addr.remote":"127.0.0.1:44786","proto":"ssh","namespace":"default","server_id":"c9a706b7-0b58-4a68-8c48-d43fbe2f37c5","server_hostname":"ip-172-31-43-7.sa-east-1.compute.internal","server_labels":{"teleport.internal/resource-id":"52a5c353-5578-4fe9-9590-8f6b5e325408"},"enhanced_recording":false,"interactive":false,"participants":["TeleLos"],"session_start":"2023-07-10T14:32:46.083544156Z","session_stop":"2023-07-10T14:32:48.27072721Z","session_recording":"node"}
```

There is special error handling when it is invoked by id rather than by file, but it doesn't give the user a clear indicator that this is fine for a non-interactive session.

```console
tsh play 02c0a346-517a-4e09-a9e6-b8e12d3c85fd
ERROR: Recording for session 02c0a346-517a-4e09-a9e6-b8e12d3c85fd not found.
```

### Expected behavior:

```console
% tsh play 02c0a346-517a-4e09-a9e6-b8e12d3c85fd
ERROR: Cannot play a non-interactive session recording. Try `-f json` or  `-f yaml`
```

```console
% ls ./02c0a346-517a-4e09-a9e6-b8e12d3c85fd.tar
./02c0a346-517a-4e09-a9e6-b8e12d3c85fd.tar
% tsh play ./02c0a346-517a-4e09-a9e6-b8e12d3c85fd.tar
ERROR: Cannot play a non-interactive session recording. Try `-f json` or `-f yaml`
```

Bug details:
- Teleport version: 13.1.5
- Recreation steps: try to play a non-interactive session by id or from a downloaded .tar file
- Debug logs see above

### PR DESCRIPTION
**Pull request by stevenGravy**
fixes #28978 fixes #28191

Checks to see for files and online sessions for interactive play. A error message is given for non SSH and Kubernetes types that a format type of `json` or `yaml` is required.  Also includes checking for desktop replay

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -2066,6 +2070,18 @@ func PlayFile(ctx context.Context, tarFile io.Reader, sid string) error {
 	if err != nil {
 		return trace.Wrap(err)
 	}
+	// Checks to see if attempting to interactively play desktops or not SSH, Kube types
+	if len(sessionEvents) > 0 {
+		if sessionEvents[0].GetType() == events.WindowsDesktopSessionStartEvent {
```
Comment (zmb3) [inline lib/client/api.go:2075]: I'd convert this to a switch:

```
switch typ := sessionEvents[0].GetType(); typ {
case events.WindowsDesktopSessionStartEvent:
    return trace.BadParameter(...)
case events.AppSessionStartEvent, events.DatabaseSessionStart:
    return trace.BadParameter(...)
case events.SessionStart:
    // proceed without error
default:
    return trace.BadParameter("unknown session type %q", typ)
}
```

This makes it a bit more explicit as opposed to relying on "anything other than session start"

(I'd probably do the same in up on line 1991 too)

Comment (stevenGravy) [reply lib/client/api.go:2081]: Thanks @zmb3 , updated to use switch.

File: lib/client/api.go [hunk 2]
```diff
@@ -2066,6 +2076,23 @@ func PlayFile(ctx context.Context, tarFile io.Reader, sid string) error {
 	if err != nil {
 		return trace.Wrap(err)
 	}
+	// Return errors if this is desktop, app, db or unknown session.
+	if len(sessionEvents) > 0 {
+		switch typ := sessionEvents[0].GetType(); typ {
```
Comment (zmb3) [inline lib/client/api.go:2081]: Now that we have the same code in 2 places, I suggest we extract this to a `func checkPlayable(firstEvent apievents.AuditEvent) error` function and use it in both places.

File: lib/client/api.go [hunk 3]
```diff
@@ -2066,6 +2076,23 @@ func PlayFile(ctx context.Context, tarFile io.Reader, sid string) error {
...
+		case events.WindowsDesktopSessionStartEvent:
+			message := "Desktop sessions cannot be viewed with tsh." +
+				" Please use the browser to play this session or use tsh recordings export to get a video download."
+			return trace.BadParameter("%s", message)
+		case events.AppSessionStartEvent, events.DatabaseSessionStartEvent, events.AppSessionChunkEvent:
+			return trace.BadParameter("Interactive session replay with tsh is supported for SSH and Kubernetes sessions."+
+				" To play entries for Application and Database you must use the json or yaml format."+
+				" \nEx: tsh play -f json %s", sid)
```
Comment (zmb3) [inline lib/client/api.go:2089]:
```suggestion
				"\nEx: tsh play -f json %s", sid)
```

**Review by zmb3 — COMMENTED** [review]
Almost there :-)

File: lib/client/api.go (hunk 2 above)
Comment (stevenGravy) [reply lib/client/api.go:2081]: We'd have to do logic to determine if we can show the desktop url or not.  Since the `tsh play file` doesn't require a Teleport client it shows a different desktop error.  Do we still want to consolidate?

Comment (zmb3) [reply lib/client/api.go:2081]: I see. This is fine then.

**Review by zmb3 — APPROVED** [review]

**Review by AntonAM — APPROVED** [review]
