### PR TITLE
Better handle database access HA scenario

### LINKED ISSUE #5808: Better handle HA database access scenario
### What

Currently, if there are multiple database servers with the same name pointing to the same database, we just always return the first matching one so if it fails for some reason, the connection will not succeed:

https://github.com/gravitational/teleport/blob/v6.0.0-rc.2/lib/srv/db/proxyserver.go#L322-L328

Instead, we should try them all and return the one that can connect successfully.

These things need to happen:

- [ ] Randomly choose database service instead of trying the first one.
- [ ] If it is down, keep trying the other ones. Can tell by getting reverse tunnel not found error.
- [ ] When displaying in tsh db ls, deduplicate by name.
- [ ] Add HA documentation guide.

### Workaround

A workaround could be just registering two different database servers pointing to the same database (`aurora-1`, `aurora-2`) and trying the other one if first one doesn't succeed.

### PR DESCRIPTION
**Pull request by r0mant**
Closes https://github.com/gravitational/teleport/issues/5808.

Makes the following improvements to the scenario when there are multiple database servers proxying the same database:
* Pick server to proxy to randomly to provide some load balancing.
* Retry connection on a different server if one is down.
* Update tsh db ls to deduplicate database services with the same name.

### CODE REVIEW

File: lib/srv/db/proxyserver.go [hunk 1]
```diff
@@ -106,6 +109,15 @@ func (c *ProxyServerConfig) CheckAndSetDefaults() error {
 	if c.ServerID == "" {
 		return trace.BadParameter("missing ServerID")
 	}
+	if c.Shuffle == nil {
+		c.Shuffle = func(servers []types.DatabaseServer) []types.DatabaseServer {
+			rand.New(rand.NewSource(c.Clock.Now().Unix())).Shuffle(
```
Comment (smallinsky) [inline lib/srv/db/proxyserver.go:114]:
```suggestion
			rand.New(rand.NewSource(c.Clock.Now().UnixNano())).Shuffle(
```

**Review by smallinsky — APPROVED** [review]

**Review by xacrimon — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.
