### PR TITLE
db access denied error message improvement

### LINKED ISSUE #13293: DB access denied error improvement
When a user configures teleport the first time the default roles don't provide any db_users, and db_labels that allow a user to connect to db instance. During the db access flow teleport returns the` access to db denied` error that is omitted, or misunderstood by a  teleport user. 
 
 ```
 tsh db connect eks-app-db
psql: error: connection to server at "localhost" (127.0.0.1), port 61378 failed: access to db denied`
```

TSH flow should return an actionable error for example instead of `failed: access to db denied` the error should indicate that a user is not assigned to any roles that provide valid `db_users`. Additionally, the `tsh cli` can check if a user has access to a particular database and return a detailed error.  The work done is https://github.com/gravitational/teleport/pull/10458 can be reused to determine if a user has access to a particular DB from `tsh db login/connect` flow.

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #13293

Supersedes: #13824 with a much simpler and less risky change.

This PR improves the error message returned when a user tries to connect to a database that they are not authorized to connect to in Teleport.

Output diff before/after this change:
```diff
 > tsh db connect --db-user=baduser foo
 Tap any security key
 ERROR 1105 (HY000): access to db denied
+ ERROR: '/opt/homebrew/bin/mysql' exited with the error above. Use 'tsh db ls' to see your available logins, or ask your Teleport administrator to check the audit log.
```

Includes a message telling the user that the command failed due to an access error and directs them to check their allowed users with `tsh db ls`, or to ask the admin to check the audit log. The audit log will reveal details for why they got access denied.

### CODE REVIEW

File: lib/client/db/dbcmd/error.go [hunk 1]
```diff
@@ -46,6 +46,12 @@ func ConvertCommandError(cmd *exec.Cmd, err error, peakStderr string) error {
 		}
 	}
 
+	lowerCaseStderr := strings.ToLower(peakStderr)
+	if strings.Contains(lowerCaseStderr, "access to db denied") {
+		fmtString := "'%s' exited with the error above. Use 'tsh db ls' to see your available logins, " +
```
Comment (jakule) [inline lib/client/db/dbcmd/error.go:51]: I think that the error message is a bit confusing. I understand the first part, but why should a user ask the Teleport admin to check the audit log? I'd say if you're missing access, you should ask the admin to add the missing role/resource to your account. You could also add a link to our docs with the access request, but I'm not sure if this is something we want to do, link: https://goteleport.com/docs/access-controls/access-requests/.
cc @smallinsky

File: lib/client/db/dbcmd/error.go [hunk 2]
```diff
@@ -46,6 +46,12 @@ func ConvertCommandError(cmd *exec.Cmd, err error, peakStderr string) error {
 		}
 	}
 
+	lowerCaseStderr := strings.ToLower(peakStderr)
+	if strings.Contains(lowerCaseStderr, "access to db denied") {
```
Comment (jakule) [inline lib/client/db/dbcmd/error.go:50]: Can you add a UT that covers this scenario?

Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go:50]: So just a test of ConvertCommandError input/output?

Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go:50]: Ok simple enough, added

File: lib/client/db/dbcmd/error.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go:51]: Thinking about this more, I think I was getting ahead of myself with being "helpful" by assuming the Teleport admin would not know why the user was denied access 😄. How's this phrasing: "... or ask your Teleport administrator to grant you access."

Comment (smallinsky) [reply lib/client/db/dbcmd/error.go:51]: The error message looks fine thought can we create a db access troubleshooting entry and reference link to it similar like in https://github.com/gravitational/teleport/pull/14794/files#diff-f9a594b642a0869ab30233d33329c066571f4ecba227e8e32b30ca606beb0ccfR10 ? 

The access-denied can also occur when:
- Teleport RBAC allows to connect with a user x  but user x is not  created in db instance. 
- RBAC model allows to connect with a user x but db_name RBAC validation failed. 

This `access to db denied` tsh db connect error mostly confuses a new teleport users where they don't know to much about teleport RBAC model.

File: lib/client/db/dbcmd/dbcmd_test.go [hunk 3]
```diff
@@ -590,3 +590,89 @@ func TestGetConnectCommandNoAbsPathIsNoopWhenGivenRelativePath(t *testing.T) {
...
+					execOutput: map[string][]byte{
+						tt.wantBin: tt.stderr,
+					}}),
+			}
+			c := NewCmdBuilder(tc, profile, database, "root", opts...)
+			c.uid = utils.NewFakeUID()
+
+			cmd, err := c.GetConnectCommand()
+			require.NoError(t, err)
+			cmd.Run()
```
Comment (smallinsky) [inline lib/client/db/dbcmd/dbcmd_test.go:662]: Does the cmd.Run call is needed  ? the cmd contain the real exec.Command so in case of missing binaries the cmd.Run will fail.

File: lib/client/db/dbcmd/error.go [hunk 4]
```diff
@@ -46,6 +46,12 @@ func ConvertCommandError(cmd *exec.Cmd, err error, peakStderr string) error {
...
+		fmtString := "'%s' exited with the error above. Use 'tsh db ls' to see your available logins, " +
+			"or ask your Teleport administrator to grant you access."
+		return trace.AccessDenied(fmtString, cmd.Path)
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go:53]: ok

[the remark this answers is not in the document]
Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go:53]:
```diff
  > tsh db connect --db-user=baduser teleport-mysql
  Tap any security key
  ERROR 1105 (HY000): access to db denied
-  ERROR: '/opt/homebrew/bin/mysql' exited with the above error. Use 'tsh db ls' to see your available logins, or ask your Teleport administrator to grant you access.
+  ERROR: exit status 1: '/opt/homebrew/bin/mysql' exited with the above error. Use 'tsh db ls' to see your available logins, or ask your Teleport administrator to grant you access.
```

The error is just the exiterror of cmd.Run(), in this case just "exit status 1". The error message printed on stderr by `mysql` contains useful error message, which is what we examine via `peakStderr`. Let me know if you still want to add the `err` to the message.

File: lib/client/db/dbcmd/dbcmd_test.go (hunk 3 above)
Comment (GavinFrazar) [reply lib/client/db/dbcmd/dbcmd_test.go:663]: Not needed, I added by mistake. Thanks!

File: lib/client/db/dbcmd/error.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go]: Shall I simply link to https://goteleport.com/docs/database-access/troubleshooting (which will exist once #14794 merges) and open a PR against #14794 to add a section to the new troubleshooting section for RBAC?

Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go]:
```diff
  > tsh db connect --db-user=baduser teleport-mysql
  Tap any security key
  ERROR 1105 (HY000): access to db denied
  ERROR: exit status 1: '/opt/homebrew/bin/mysql' exited with the above error. Use 'tsh db ls' to see your available logins, or ask your Teleport administrator to grant you access. 
+ See https://goteleport.com/docs/database-access/troubleshooting for more information.
```

File: lib/client/db/dbcmd/error.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (smallinsky) [reply lib/client/db/dbcmd/error.go]: All right thanks for the explanation  
> Let me know if you still want to add the err to the message.
It is fine. I have confused this error with error returned by engine.

File: lib/client/db/dbcmd/error.go (hunk 1 above)
Comment (smallinsky) [reply lib/client/db/dbcmd/error.go]: > Shall I simply link to https://goteleport.com/docs/database-access/troubleshooting (which will exist once https://github.com/gravitational/teleport/pull/14794 merges) and open a PR against https://github.com/gravitational/teleport/pull/14794 to add a section to the new troubleshooting section for RBAC?

We should link to specific troubleshooting header like:  #certificate-expired-or-is-not-yet-valid but to do that the https://github.com/gravitational/teleport/pull/14794 needs to be merged.

**Review by jakule — APPROVED** [review]

File: lib/client/db/dbcmd/error.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go]: Updated to reference a new heading that will be added in #17259

Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go]: #17259 is approved and should auto-merge soon. @smallinsky I think this is ready if you want to approve

Comment (GavinFrazar) [reply lib/client/db/dbcmd/error.go]: #17259 merged

**Review by smallinsky — APPROVED** [review]
