### PR TITLE
Do not delete integration CAs on auth init

### LINKED ISSUE #51920: GitHub proxy throws `ssh: rejected: administratively prohibited` error for KMS keys
Expected behavior:
GitHub proxy should succeed.

Current behavior:
```
$ git fetch
11:36:22.609357 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Library/Developer/CommandLineTools/usr/bin/git
11:36:22.610072 exec-cmd.c:238          trace: resolved executable dir: /Library/Developer/CommandLineTools/usr/bin
11:36:22.610779 git.c:460               trace: built-in: git fetch
11:36:22.613435 run-command.c:655       trace: run_command: GIT_PROTOCOL=version=2 '"/Users/stevehuang/go/github.com/gravitational/teleport/build/tsh" git ssh --github-org <org>' -G -o SendEnv=GIT_PROTOCOL <org>@github.com
11:36:22.914285 run-command.c:655       trace: run_command: unset GIT_PREFIX; '"/Users/stevehuang/go/github.com/gravitational/teleport/build/tsh" git ssh --github-org <org>' org-112014280@github.com 'git-upload-pack '\''goteleport-core-test/test.git'\'''
ERROR: ssh: rejected: administratively prohibited (rpc error: code = Unknown desc = operation error KMS: Sign, https response error StatusCode: 400, RequestID: 2a8a3e54-bca0-4037-af0a-1e9c558e5a94, KMSInvalidStateException: arn:aws:kms:ca-central-1:<account-id>:key/<account-id> is pending deletion.)

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Bug details:
- Teleport version: v17.2.1 (new cloud tenant with KMS)
- Note that this issue does NOT affect software keys.

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #51920 

changelog: Fix an issue that GitHub integration CA gets deleted during Auth restart for non-software key stores like KMS. For broken GitHub integrations, the `integration` resource must be deleted and recreated.

### CODE REVIEW

File: lib/auth/init.go [hunk 1]
```diff
@@ -637,6 +639,22 @@ func initializeAuthorities(ctx context.Context, asrv *Server, cfg *InitConfig) e
 		return trace.Wrap(err)
 	}
 
+	// Collect CAs from integrations to avoid deleting them.
```
Comment (greedy52) [inline lib/auth/init.go:642]: I attempted to create a UT for this but `keyStore.DeleteUnusedKeys` has no effect on software keys. I've also tried test with `TELEPORT_TEST_AWS_KMS_ACCOUNT` but `keyStore.DeleteUnusedKeys` does not delete keys created in the last 5 minutes. I might leave as it is without tests

File: lib/auth/integration/credentials/credentials.go [hunk 2]
```diff
@@ -132,3 +132,38 @@ func GetIntegrationRef(ctx context.Context, integration string, igGetter Integra
 	}
 	return ref, nil
 }
+
+// GetIntegrationCertAuthorities attempts to retrieve certificate authorities
```
Comment (greedy52) [inline lib/auth/integration/credentials/credentials.go:136]: not new logic, moved from `lib/auth/integration/integrationsv1` to here

File: lib/auth/init.go [hunk 3]
```diff
@@ -637,6 +639,22 @@ func initializeAuthorities(ctx context.Context, asrv *Server, cfg *InitConfig) e
...
+	igs, err := clientutils.ListAllResources(ctx, asrv.Services.ListIntegrations)
```
Comment (zmb3) [inline lib/auth/init.go:643]: How many resources do we expect this to return? 

There's not really a need to buffer them all in memory before you start collecting the keys. If there are going to be many pages it will be more memory efficient to iterate a page at a time and collect the keys per-page.

Comment (greedy52) [reply lib/auth/init.go]: i would say a handful at most but agreed we shouldn't encourage holding everything in memory. changed it to an iterator.

File: api/utils/clientutils/resources.go [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+	"context"
+
+	"github.com/gravitational/trace"
+
+	"github.com/gravitational/teleport/api/defaults"
+)
+
+// IterateResources is a helper that iterates through each resource from all
+// pages and passes them one by one to the provided callback.
+func IterateResources[T any](
```
Comment (zmb3) [inline api/utils/clientutils/resources.go:31]: Should we make this a proper go iterator and return an `iter.Seq` instead of a manual loop with a callback?

Comment (greedy52) [reply api/utils/clientutils/resources.go:31]: also need to bump go.mod for `api/`

Comment (greedy52) [reply api/utils/clientutils/resources.go:31]: @zmb3 @rosstimothy this is how imagined the iterator version. Let me know if you prefer that over this PR and i can push it here:
https://github.com/gravitational/teleport/commit/4ecd694f57fc1a3f100f1f4bc67bdee56cde1985#diff-44eb64101a2a166c4fb093edec646884a14091b1cfe42adb9cbb67a53bfc17d1

Comment (zmb3) [reply api/utils/clientutils/resources.go:31]: I like it, but maybe we hold off on that for now to avoid bumping Go for /api. We can stick with what you've got in this PR.

**Comment by greedy52** [comment]
friendly ping @fheinecke @fspmarshall

**Review by zmb3 — APPROVED** [review]

**Review by GavinFrazar — APPROVED** [review]
