### PR TITLE
fix app access regression when the app is on a leaf cluster

### LINKED ISSUE #46951: Web application access with browser fails from root cluster with trusted clusters in Teleport >=16.4.0
Expected behavior:
Web application access should work seamlessly from a root cluster with trusted clusters configured.

Current behavior:
When trying to access a web application hosted in a leaf Teleport cluster from a root Teleport cluster with trust enabled, the access fails with the error message: "Access denied Failed to match applications with FQDN", we are never redirected to the application url. This issue is specific to browser-based access, as accessing the application using the Teleport CLI (tsh app login A) works without any problems.

Bug details:
Teleport version: 16.4.0 and 16.4.2 (tested on both versions)

Recreation steps:
Set up a Teleport root cluster with trust enabled to a leaf cluster
Configure a web application (A) in the leaf Teleport cluster
Attempt to access the web application (A) from the root cluster using a web browser

Debug logs:
The API response visible in the browser console shows the following:
```json
{
  "fqdn": "app-a.root.example.io",
  "requiredAppFQDNs": [
    "app-a.leaf.example.io"
  ]
}
```
I didn't found error on cluster logs.

Additional information:
Rolling back to Teleport version 16.3.0 resolved the issue, confirming that the problem is specific to versions 16.4.0 and more.

### PR DESCRIPTION
**Pull request by capnspacehook**
Fixes https://github.com/gravitational/teleport/issues/46951.

changelog: fix app access regression to apps on leaf clusters

### CODE REVIEW

**Review by avatus — COMMENTED** [review]
Logic seems fine to be. it'd be nice to change this from some nested `if` and just into two variables like
`const fqdnMatch` and `const isLeafApp` or whatever you think makes most sense. then we can just do `if !this && !that, return error`

might read a little nicer. but in general this is good!

**Comment by capnspacehook** [comment]
Thanks @avatus, moved the logic into it's own function to put the logic and comments in one place. Did some more testing and found that this PR fixes an `access denied` error popping up when attempting to access an app from a leaf cluster, but another issue prevents accessing the leaf app. I get a warning: `Request failed: state cookie is not set. app/auth.go:166`. I confirmed this issue started after my 2 commits that added and revised these app FQDN checks, the regression seems to have been created between https://github.com/gravitational/teleport/pull/45024 and https://github.com/gravitational/teleport/pull/45512. Do you mind confirming this for me?

**Comment by avatus** [comment]
The `fqdn` returned from a leaf resource gets updated in a weird way (which might be incorrect). It becomes something like `appname-rootcluster`. Which then causes the frontend to forward to the wrong app. I believe we need to update [our forwarding URL](https://github.com/gravitational/teleport/blob/capnspacehook/trusted-cluster-app-access-regression/web/packages/teleport/src/AppLauncher/AppLauncher.tsx#L141) to use `publicAddr` of the resolved app instead of the FQDN. I tested locally and works, but didn't consider the implications of the change. Please take a look when you get a chance @capnspacehook .

Thanks!

File: web/packages/teleport/src/AppLauncher/AppLauncher.tsx [hunk 1]
```diff
@@ -37,6 +37,43 @@ export function AppLauncher() {
...
+    localClusterName: string,
+    publicAddress: string
+  ) {
+    // Because the ports are stripped from the FQDNs before they are
+    // compared, an attacker can pass a FQDN with a different port than
+    // what the app's public address is configured with and have Teleport
+    // redirect to the public address with an arbitrary port. But because
+    // the attacker can't control what domain is redirected to this has
+    // a low risk factor.
+    if (prepareFqdn(fqdn) == prepareFqdn(params.fqdn)) {
```
Comment (ravicious) [inline web/packages/teleport/src/AppLauncher/AppLauncher.tsx:52]: At the time this check was added in #43525 (e22c004), this check seemed to work correctly, indicating that a regression was introduced elsewhere. Did you look into this by any chance?

FWIW, I couldn't get leaf app access working even on e22c004. Despite the fqdn check passing, I see the following message displayed by `AppLauncher`:

> Unable to serve application requests. Please try again. If the issue persists, verify if the Application Services are connected to Teleport.

The logs for the root cluster show this:

```
2024-10-28T12:15:45+01:00 WARN [PROXY:SER] Request for connection to remote site failed error:[
ERROR REPORT:
Original Error: *errors.errorString connection rejected: could not find reverse tunnel, check that Application Service agent proxying this application is up and running
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/utils/sshutils/conn.go:74 github.com/gravitational/teleport/api/utils/sshutils.ConnectProxyTransport
	github.com/gravitational/teleport/lib/reversetunnel/remotesite.go:970 github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).chanTransportConn
	github.com/gravitational/teleport/lib/reversetunnel/remotesite.go:943 github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).connThroughTunnel
	github.com/gravitational/teleport/lib/reversetunnel/remotesite.go:808 github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).DialTCP
	github.com/gravitational/teleport/lib/reversetunnel/remotesite.go:802 github.com/gravitational/teleport/lib/reversetunnel.(*remoteSite).Dial
	github.com/gravitational/teleport/lib/web/app/transport.go:436 github.com/gravitational/teleport/lib/web/app.dialAppServer
	github.com/gravitational/teleport/lib/web/app/match.go:117 github.com/gravitational/teleport/lib/web/app.(*Handler).HealthCheckAppServer.appServerMatcher.MatchHealthy.func2
	github.com/gravitational/teleport/lib/web/app/match.go:131 github.com/gravitational/teleport/lib/web/app.(*Handler).HealthCheckAppServer.appServerMatcher.MatchAll.func3
	github.com/gravitational/teleport/lib/web/app/match.go:76 github.com/gravitational/teleport/lib/web/app.MatchOne
	github.com/gravitational/teleport/lib/web/app/handler.go:236 github.com/gravitational/teleport/lib/web/app.(*Handler).HealthCheckAppServer
	github.com/gravitational/teleport/lib/web/apps.go:223 github.com/gravitational/teleport/lib/web.(*Handler).createAppSession
	github.com/gravitational/teleport/lib/web/apiserver.go:4464 github.com/gravitational/teleport/lib/web.(*Handler).bindDefaultEndpoints.(*Handler).WithAuth.func7
	github.com/gravitational/teleport/lib/httplib/httplib.go:127 github.com/gravitational/teleport/lib/web.(*Handler).bindDefaultEndpoints.(*Handler).WithAuth.MakeHandler.MakeHandlerWithErrorWriter.func161
	github.com/julienschmidt/httprouter@v1.3.0/router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	net/http/server.go:2214 github.com/gravitational/teleport/lib/web.NewHandler.func1.StripPrefix.1
	net/http/server.go:2171 net/http.HandlerFunc.ServeHTTP
	github.com/gravitational/teleport/lib/web/apiserver.go:528 github.com/gravitational/teleport/lib/web.NewHandler.func1
	net/http/server.go:2171 net/http.HandlerFunc.ServeHTTP
	github.com/julienschmidt/httprouter@v1.3.0/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	github.com/gravitational/teleport/lib/web/apiserver.go:366 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
	github.com/gravitational/oxy@v0.0.0-20231219172753-f855322f2a6c/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
	github.com/gravitational/oxy@v0.0.0-20231219172753-f855322f2a6c/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
	github.com/gravitational/teleport/lib/httplib/httplib.go:104 github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1
	net/http/server.go:2171 net/http.HandlerFunc.ServeHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.53.0/handler.go:218 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.53.0/handler.go:74 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
	net/http/server.go:2171 net/http.HandlerFunc.ServeHTTP
	net/http/server.go:3142 net/http.serverHandler.ServeHTTP
	net/http/server.go:2044 net/http.(*conn).serve
	runtime/asm_arm64.s:1222 runtime.goexit
User Message: connection rejected: could not find reverse tunnel, check that Application Service agent proxying this application is up and running] cluster:teleport-local-leaf reversetunnel/remotesite.go:947
```

Comment (capnspacehook) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:52]: > At the time this check was added in https://github.com/gravitational/teleport/pull/43525 (https://github.com/gravitational/teleport/commit/e22c004f5dab6759b681397f1b4441c8573351e7), it seemed to work correctly, indicating that a regression was introduced elsewhere. Did you look into this by any chance?

Yes, see the earlier comment by @avatus. I just tested and pushed another commit based on his diff which should fix this issue.

> FWIW, I couldn't get leaf app access working even on https://github.com/gravitational/teleport/commit/e22c004f5dab6759b681397f1b4441c8573351e7. Despite the fqdn check passing, I see the following message displayed by AppLauncher:

I noticed this behavior too, and @avatus did as well. I chocked it up to a MacOS DNS bug, as my leaf cluster wasn't respecting the entry in my hosts file for the leaf domain. I'm not sure what's causing this or if it's related, but I didn't remember running into the issue back when I pushed the https://github.com/gravitational/teleport/pull/43525.

Re: @avatus's comment on whether the FQDN being changed for a leaf app resource is correct/intended behavior, I'm not sure on that, but I did find that it's not new code. It was introduced in https://github.com/gravitational/teleport/commit/8720b1872a1a9722f6613f5940d422cd35678db5#diff-f635fca1ca174ba271760ef6e8dbe4aa703df1ba9acde1ae8828b86fb8992631 3 years ago and to my knowledge hasn't caused a problem since, I'm sure it's for a reason but am not presently sure what that reason was.

File: web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx [hunk 2]
```diff
@@ -36,42 +36,42 @@ const launcherPathTestCases: {
   {
     name: 'no state and no path',
     path: '?path=',
-    expectedPath: 'x-teleport-auth',
+    expectedPath: 'undefined/x-teleport-auth',
```
Comment (zmb3) [inline web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx:39]: Why would we ever expect "undefined" in a URL?

File: web/packages/teleport/src/AppLauncher/AppLauncher.tsx [hunk 3]
```diff
@@ -104,7 +138,10 @@ export function AppLauncher() {
       const session = await service.createAppSession(params);
 
       // Set all the fields expected by server to validate request.
-      const url = getXTeleportAuthUrl({ fqdn, port });
+      const url = getXTeleportAuthUrl({
+        publicAddr: publicAddr,
+        port,
+      });
```
Comment (nklaassen) [inline web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: I don't understand this change, looks like you are switching the redirect url from the fqdn to the app public_addr, which seems wrong to me. Let me write out an example and let's see if we agree on what we think happens and what we think *should* happen.

Customer has two clusters, `root.example.com` and `leaf.example.com`.
There's a wildcard DNS record for *.root.example.com that points to the root proxy.
There's a wildcard DNS entry for *.leaf.example.com that points to the leaf proxy.
The root proxy has a wildcard TLS cert for *.root.example.com
The leaf proxy has a wildcard TLS cert for *.leaf.example.com

In the leaf cluster there is an app with name `dashboard` and `public_addr: dashboard.leaf.example.com`

User `alice` is logged in to the web UI on cluster `root.example.com`. In the root cluster web UI they navigate to the resources page for `leaf.example.com`, and click to launch the app `dashboard`

Before this change, IIUC, we would redirect to `dashboard.root.example.com`. DNS resolves this to the root proxy which will handle the request, the user is already logged in, as long as the root proxy actually handles the request correctly it should all work fine. I'm assuming the root proxy is supposed to be able to handle this

After this change it looks like we will redirect to the leaf app's public_addr `dashboard.leaf.example.com`. This resolves to the leaf proxy, where the user is not logged in and may not be able to log in. There is probably no app session on this cluster and it probably doesn't work

I think either:
1. I'm wrong about what this is doing, or
2. I'm right, this case wasn't considered yet and this is probably broken, or
3. We want to call it a misconfiguration to set the leaf app public_addr to an address that doesn't resolve to the root proxy

Does this make sense and can you help me figure this out?

**Review by nklaassen — COMMENTED** [review]
In the PR description I see what bug this is supposed to fix, but can you please explain how this is meant to fix it?

File: web/packages/teleport/src/AppLauncher/AppLauncher.tsx (hunk 3 above)
Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: I suggested the change.
>  There is probably no app session on this cluster and it probably doesn't work


This is correct that the session doesn't exist. If an app session doesn't exist, then the app auth exchange takes care of this and creates the session (which is what seems like its trying to do, but missing the state cookie due to mismatched domain). Admittedly, I might be missing context on the desired behavior here.   

In the dashboard scenario you described above, what happens if both root and leaf have a dashboard.CLUSTER_HERE.example.com if we always resolve to the root? I'm unsure what the desired outcome should be.

Comment (nklaassen) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: Maybe/probably the user can't even log in to the leaf cluster though

I assumed we had the whole utils.AssembleAppFQDN thing so that the root web UI can always redirect leaf apps to itself and explicitly ignore the leaf app public_addr, and that the root proxy would handle forwarding the request along correctly

Comment (nklaassen) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: > In the dashboard scenario you described above, what happens if both root and leaf have a dashboard.CLUSTER_HERE.example.com if we always resolve to the root? I'm unsure what the desired outcome should be.

Obviously this is an edge case we need to handle, I have been assuming it connects to the app you last clicked on based on the cookie/state/token thing (im clearly not a web dev) set on that URL

Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: Hmm, fair enough. I think the mismatch of cookie domains during authentication is the real crux here in that case (which hasn't seemed to change for awhile but might have been broke for awhile too?) 

@capnspacehook can you double check the process in the app auth exchange? 

The RFD might help too (I'm unsure if leafs were included) https://github.com/gravitational/teleport/blob/87a0a1c26acf78a1630e1ba63b3f2e591ff559b4/rfd/0103-application-access-web-ui-auth-flow.md

Comment (nklaassen) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: IMO this current change is directionally the opposite of what we want. We should always set cookies for the FQDN and always redirect to the FQDN

Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: Agreed. Just for additional context in the comments, the app auth exchange (using your example) is currently starting on dashboard.root and trying to finish on dashboard.leaf and that causes the state cookie to be missing.

File: web/packages/teleport/src/AppLauncher/AppLauncher.tsx (hunk 1 above)
Comment (ravicious) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:52]: @capnspacehook So, I discovered that in e22c004f5dab6 app access wasn't working not because of the code, but because the web PKI cert I had in my leaf cluster had expired. After fixing this and adding appropriate entries in `/etc/hosts`, I got it to work.

After running `git bisect`, I found that it was #45512 that broke app access for leaf apps, which confirms your earlier thoughts.

Comment (ravicious) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:52]: After #45512, accessing a leaf app from a root cluster fails with `Failed to match applications with FQDN "example-leaf.teleport-local-leaf"`. As this check wasn't added in that PR, it suggests that #45512 introduced a regression in `lib/web.Handler.resolveApp`.

Question is, in order to fix this, do we need anything more than adjusting the behavior of `lib/web.Handler.resolveApp`? Are the changes in `AppLauncher` necessary?

Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:52]: Ah, it was me all along! Thanks for the find @ravicious .

if you get a fix to `resolveApp` (probably [the conditional I added](https://github.com/gravitational/teleport/pull/45512/files#diff-b14891674f8dd044033299cfe41f2bad8bd692e2661118d685c612523f37f264R348) ) can you make sure that it doesn't break automatic redirects? [I added an easy way to test](https://github.com/gravitational/teleport/blob/master/.github/ISSUE_TEMPLATE/webtestplan.md#required-applications) it in the web test plan that you can use to check.

Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:52]: Ok, i nailed it down to what caused the regression. During required app redirects, I changed [the hostname to the publicaddr of the redirect app](https://github.com/gravitational/teleport/pull/45512/files#diff-00b478b3d7d6aa201917b8129d4a7f923c5e268854c0f1776ab3b757341b0752R84) instead of the host in the request. 

Reverting this change fixes apps on leafs but then breaks required app redirects (causes an infinite loop). I reverted the change in the diff below and then moved the logic to change the hostname based on app redirect only instead of always.

This makes both scenarios work, automatic redirects for required apps AND also apps on leaf. I **did not** get a chance to test required apps _on leafs_. 

Also,I can confirm that [apps of the same name on root and leaf ](https://github.com/gravitational/teleport/pull/47778#discussion_r1819951083) causes the user to be redirected to the app on root (even if selecting the leaf). but i think that is a separate issue not related to any of these suggested changes or regression (but what do i know).

<details><summary>Open me!</summary>

```diff
diff --git a/lib/web/app/handler.go b/lib/web/app/handler.go
index 38de429b9c..e81f686042 100644
--- a/lib/web/app/handler.go
+++ b/lib/web/app/handler.go
@@ -618,10 +618,14 @@ const (
 // The URL's are formed this way to help isolate the path params reserved for the app
 // launchers route, where order and existence of previous params matter for this route.
 func makeAppRedirectURL(r *http.Request, proxyPublicAddr, hostname string, req launcherURLParams) string {
+	host := hostname
+	if req.requiresAppRedirect {
+		host = req.publicAddr
+	}
 	u := url.URL{
 		Scheme: "https",
 		Host:   proxyPublicAddr,
-		Path:   fmt.Sprintf("/web/launch/%s", hostname),
+		Path:   fmt.Sprintf("/web/launch/%s", host),
 	}
 
 	// Presence of a stateToken means we are beginning an app auth exchange.
@@ -634,7 +638,7 @@ func makeAppRedirectURL(r *http.Request, proxyPublicAddr, hostname string, req l
 		v.Add("required-apps", req.requiredAppFQDNs)
 		u.RawQuery = v.Encode()
 
-		urlPath := []string{"web", "launch", hostname}
+		urlPath := []string{"web", "launch", host}
 
 		// The order and existence of previous params matter.
 		//
diff --git a/lib/web/app/middleware.go b/lib/web/app/middleware.go
index 79e1586ff2..67b189de3a 100644
--- a/lib/web/app/middleware.go
+++ b/lib/web/app/middleware.go
@@ -81,12 +81,8 @@ func (h *Handler) redirectToLauncher(w http.ResponseWriter, r *http.Request, p l
 			"https://goteleport.com/docs/application-access/guides/connecting-apps/#start-authproxy-service.")
 		return trace.BadParameter("public address of the proxy is not set")
 	}
-	host := p.publicAddr
-	if host == "" {
-		host = r.Host
-	}
 
-	addr, err := utils.ParseAddr(host)
+	addr, err := utils.ParseAddr(r.Host)
 	if err != nil {
 		return trace.Wrap(err)
 	}

```
</details>

this was tested off of master btw, so unless there are some _other_ regressions or security holes filled by your first commit, your og change may not be necessary. 

Please take time to test this as I did some light testing locally but may have missed an edge case.

File: web/packages/teleport/src/AppLauncher/AppLauncher.tsx (hunk 3 above)
Comment (ravicious) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: > Obviously this is an edge case we need to handle, I have been assuming it connects to the app you last clicked on based on the cookie/state/token thing (im clearly not a web dev) set on that URL

I'm fairly sure that was the case when I was testing Grzegorz's implementation of app access in Connect a couple of months ago.

Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: It was the case that it was handled correctly or incorrectly?

Comment (nklaassen) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: i think it's hard to say exactly what's correct or incorrect, but it sounds like @ravicious was saying it used to connect to the last app you clicked on between two apps with the same name in root/leaf. I vaguely remember observing this too and being a bit surprised it actually "worked" like that

we should probably double check what this did around 16.0 and try to follow that, unless it was already broken that far back, but i do remember things working when i was testing for VNet

Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: I'll double check. It would have broke in 16.2 so 16.0 isn't a bad spot to look at. I'd probably the extra resolve option I added that might be resolving things incorrectly (or just "early" via root first instead of by some param). My guess it is worked as you expected before the regression otherwise we would have heard about it sooner. 

Thanks for all the input everyone!

Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: I was incorrect, my automatic redirects went in 16.4, not 16.2. 
regardless, I did check download 16.1.8 (teleport and Connect) and the root vs. leaf name issue is also present there. if i have `client.cluster.root` and `client.cluster.leaf` and try to open `client.cluster.leaf`, i eventually get directed to the `client.cluster.root` app instead. 

I confirmed the behavior but haven't bisected yet to figure out the cause.

Comment (capnspacehook) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: I'll bisect that and report back

Comment (capnspacehook) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: I did a lot of digging into this, and it seems this behavior has been present since at least v14.0.0. So I suppose it likely never worked correctly in this use case (root and leaf both have an app of the same name). Note that on this branch the behavior works as intended in that the leaf app is resolved correctly when it is clicked on from the web UI in the root cluster. I didn't have to login to the leaf cluster at all for this to work, so could this be actually the behavior we want? @nklaassen

Comment (nklaassen) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: > I did a lot of digging into this, and it seems this behavior has been present since at least v14.0.0

What behaviour? Do you mean that when a root and leaf app have the same name you connect to the root app? I'm less concerned about this case, it seems uncommon, as long as we're not making a breaking change it's okay

> Note that on this branch the behavior works as intended in that the leaf app is resolved correctly when it is clicked on from the web UI in the root cluster

What exactly do you mean by resolved "correctly"?

Let me try this out and report back

Comment (capnspacehook) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: > What behaviour? Do you mean that when a root and leaf app have the same name you connect to the root app?

Yes, as far as I can tell this has never worked.

> What exactly do you mean by resolved "correctly"?

If a apps exist on both root and leaf clusters with the same name, clicking on the leaf app while on logged into the root cluster will redirect you to the leaf app. Previously you would be redirected to the root app in this case.

Comment (nklaassen) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: Okay so I did a test on 16.0.0-alpha.2 which is an old version I happened to have saved, and on your branch. Everything I tried worked how I would expect on 16.0 and things on this branch were broken.

I have clusters `one.private:3080` and `two.private:5080`, one.private is the root, two.private is the leaf.

I have an app named `twotest` in `two.private`.
- On 16, if I click on this from the root web UI, I get directed to `twotest.one.private:3080` and it works perfectly.
- If I try the same on your branch, I get directed to `twotest.two.private:3080`, which is the wrong proxy address (I can't log in to the leaf) and it's the root cluster port. Doesn't work.

I also have an app named `netcat` in both clusters.
- On 16, if I click the leaf cluster version of this app from the root web UI, I get directed to `netcat.one.private:3080` and the connection actually goes to the app for the leaf cluster. Works perfectly.
- on your branch, if I click the leaf cluster version of this app from the root web UI, I get directed to `netcat.two.private:3080` which again is the wrong proxy and the port for the root cluster proxy. Doesn't work.

Comment (nklaassen) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: On 16 where things work, clicking the leaf version of `netcat` causes my browser to fetch these in order:
- https://one.private:3080/web/launch/netcat.one.private/two-prod-2/netcat.two.private
- https://netcat.one.private:3080/x-teleport-auth?cluster=two-prod-2&addr=netcat.two.private
- https://one.private:3080/web/launch/netcat.one.private/two-prod-2/netcat.two.private?path=&state=b951f0996db4508cc41aed4a483febcb_4dd1ece10463fd4c66ea715e4d3d716d
- https://netcat.one.private:3080/x-teleport-auth?state=b951f0996db4508cc41aed4a483febcb_4dd1ece10463fd4c66ea715e4d3d716d&subject=a7fe3de4e8f5d23744511278701e2044c8804574d24dfe051f6b19ccaf40f445
- https://netcat.one.private:3080/

the cluster_name for my leaf cluster is two-prod-2. Notice all of these are subdomains of my root proxy `one.private:3080` which is correct

Comment (avatus) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: I agree with your findings nic. I don't think the suggested change has been applied yet. The suggested change fixes the issues you speak of, just not the same name thing. 

https://github.com/gravitational/teleport/pull/47778#discussion_r1821160341

Comment (nklaassen) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx:144]: thanks @avatus I just tried your patch on master (without this PR)

i did not try dependent/recursive apps, but with my root/leaf apps, everything was working as i expect

When opening app named `netcat` in either cluster, I was always directed to the root proxy `netcat.one.private`. If i clicked it from the leaf cluster page, I got connected to the leaf app. If i clicked it from the root cluster page, i got connected to the root app. If i kept the tabs open, all of them would start being directed to whichever app I clicked on most recently (which is the original behaviour)

@capnspacehook can we just switch this PR to be Michael's patch?
```diff
diff --git a/lib/web/app/handler.go b/lib/web/app/handler.go
index 38de429b9c..e81f686042 100644
--- a/lib/web/app/handler.go
+++ b/lib/web/app/handler.go
@@ -618,10 +618,14 @@ const (
 // The URL's are formed this way to help isolate the path params reserved for the app
 // launchers route, where order and existence of previous params matter for this route.
 func makeAppRedirectURL(r *http.Request, proxyPublicAddr, hostname string, req launcherURLParams) string {
+	host := hostname
+	if req.requiresAppRedirect {
+		host = req.publicAddr
+	}
 	u := url.URL{
 		Scheme: "https",
 		Host:   proxyPublicAddr,
-		Path:   fmt.Sprintf("/web/launch/%s", hostname),
+		Path:   fmt.Sprintf("/web/launch/%s", host),
 	}
 
 	// Presence of a stateToken means we are beginning an app auth exchange.
@@ -634,7 +638,7 @@ func makeAppRedirectURL(r *http.Request, proxyPublicAddr, hostname string, req l
 		v.Add("required-apps", req.requiredAppFQDNs)
 		u.RawQuery = v.Encode()
 
-		urlPath := []string{"web", "launch", hostname}
+		urlPath := []string{"web", "launch", host}
 
 		// The order and existence of previous params matter.
 		//
diff --git a/lib/web/app/middleware.go b/lib/web/app/middleware.go
index 79e1586ff2..67b189de3a 100644
--- a/lib/web/app/middleware.go
+++ b/lib/web/app/middleware.go
@@ -81,12 +81,8 @@ func (h *Handler) redirectToLauncher(w http.ResponseWriter, r *http.Request, p l
 			"https://goteleport.com/docs/application-access/guides/connecting-apps/#start-authproxy-service.")
 		return trace.BadParameter("public address of the proxy is not set")
 	}
-	host := p.publicAddr
-	if host == "" {
-		host = r.Host
-	}
 
-	addr, err := utils.ParseAddr(host)
+	addr, err := utils.ParseAddr(r.Host)
 	if err != nil {
 		return trace.Wrap(err)
 	}
```

**Comment by zmb3** [comment]
Does this also fix https://github.com/gravitational/teleport/issues/10671?

File: web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx (hunk 2 above)
Comment (capnspacehook) [reply web/packages/teleport/src/AppLauncher/AppLauncher.test.tsx]: I originally misunderstood this test case, but this code is not included anymore so N/A

File: web/packages/teleport/src/AppLauncher/AppLauncher.tsx (hunk 3 above)
Comment (capnspacehook) [reply web/packages/teleport/src/AppLauncher/AppLauncher.tsx]: I tested this among all cases I can think of except automatic app redirects as I'm honestly not sure how to properly test that. Everything seems to be working, and I think the duplicate root/leaf app name issue isn't present with this change as well. I created an app with the same name on both the root and leaf clusters, but set the URIs so only the leaf app pointed to a listening web server. When I tried to navigate to the root app, I get an error as expected. When I navigate to the leaf app from the root cluster, I am redirected to the app successfully. The URL I'm redirected to is a root cluster URL, so that's what had me confused earlier at least.

**Comment by capnspacehook** [comment]
@zmb3 I'm not sure, will test and report back but I'm not optimistic it fixes that. @kimlisa can I get a review please?

**Comment by avatus** [comment]
> Does this (Michael's patch) also fix https://github.com/gravitational/teleport/issues/10671?

@zmb3 no, it won't fix that unfortunately. However, fixing the issue of same name on root/leaf would probably also fix same name on leaf1/leaf2.

File: lib/web/app/handler.go [hunk 4]
```diff
@@ -618,10 +618,14 @@ const (
 // The URL's are formed this way to help isolate the path params reserved for the app
 // launchers route, where order and existence of previous params matter for this route.
 func makeAppRedirectURL(r *http.Request, proxyPublicAddr, hostname string, req launcherURLParams) string {
+	host := hostname
+	if req.requiresAppRedirect {
+		host = req.publicAddr
+	}
```
Comment (zmb3) [inline lib/web/app/handler.go:624]:
```suggestion
	if req.requiresAppRedirect {
		hostname = req.publicAddr
	}
```

If you update the existing `hostname` variable instead of making a new variable with a similar name, there's less chance of us mistakenly using the wrong one later on in this function and breaking something.

**Review by nklaassen — APPROVED** [review]
i also tested this yesterday and it works well

File: lib/web/app/handler.go (hunk 4 above)
Comment (capnspacehook) [reply lib/web/app/handler.go:624]: Thinking about this more I agree with how it's done now a bit more; if the variable is set to the public addr calling it `hostname` isn't very accurate anymore

Comment (zmb3) [reply lib/web/app/handler.go:624]: Then change the input paramater to something like `addr`.

Having two variables in scope with a similar name, where one works and the other doesn't is a recipe for failure.

Comment (capnspacehook) [reply lib/web/app/handler.go]: Fair enough, done

Comment (zmb3) [reply lib/web/app/handler.go]: I was hoping you would rename the function parameter, which was not done.

I don't want two variables in scope where one works and one doesn't. Let's make a single variable (which we overwrite if necessary), so there's no potential for confusion. As written, we still have `addr` and `hostname` in scope.

Comment (capnspacehook) [reply lib/web/app/handler.go]: Ah I see, I misunderstood. That makes sense, I renamed the `hostname` parameter to `addr`. This should make this function less confusing

**Review by zmb3 — APPROVED** [review]
Thanks capn!

**Comment by ravicious** [comment]
Could we backport this to v16? According to #46951, it's broken on >= 16.4.0.

**Comment by avatus** [comment]
@ravicious @capnspacehook https://github.com/gravitational/teleport/pull/49056 backported it to v16 here
