### PR TITLE
uploader: move corrupted uploads to separate directory

### LINKED ISSUE #8173: gracefully handle corrupt teleport session recordings
### Description

**What happened**:

A corrupted session recording was rejected by the auth_server because it was corrupted. This prompted an infinite retry loop.

**What you expected to happen**:

Teleport should be able to gracefully handle corrupt session recording files. Instead of rejecting in a loop, it should attempt to store the session recording anyway. Corrupt sessions that won't play back correctly should be downloadable for manual inspection.

### Reproduction Steps

As minimally and precisely as possible, describe step-by-step how to reproduce the problem.

* Join a node to a teleport cluster.
* If possible, temporarily prevent session recordings from being uploadable. An easy way to do this is to fill up the /var/lib/teleport directory with a few large session recordings. Use `fallocate` to quickly make the disk be mostly full. Ideally, /var/lib/teleport should be its own mount so that / isn't full on the node.
* An easy command to create large session recordings: `dd if=/dev/urandom bs=1024 count=100 | base64`
* A full disk can possibly corrupt a session recording on its own, but you can intentionally corrupt one by overwriting bytes in place in one of the sesssion recording files.
* if applicable, remove your temporary large file created with fallocate, and restart teleport. If you prevented session uploads using another method, re-enable them now.
* Watch for errors on the auth_service logs about rejecting the session due to malformed files

### Server Details
- Teleport version (run `teleport version`): 6.2.5 enterprise
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws
- Additional details:

### Client Details
- Tsh version (`tsh version`): 6.2.5

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

### LINKED ISSUE #18936: Corrupted session recording files cause massive spike in CPU usage
Expected behavior:

Corrupted session recordings don't impact Teleport.

Current behavior:

Corrupted session recordings are retried over and over again causing a massive spike in CPU usage and the following log line is spamming.

```
{"caller":"filesessions/fileasync.go:252","component":"upload","error":"session file could be corrupted or is using unsupported format: session recording 1234abcd is either corrupted or is using unsupported format, remove the file /var/lib/teleport/log/upload/streaming/default/1234abcd.tar to correct the problem, remove the /var/lib/teleport/log/upload/streaming/default/1234abcd.error file to retry the upload","level":"warning","message":"Skipped session recording 1234abcd.tar.","timestamp":"2022-11-30T07:46:08-06:00"}
```

Proposed Behavior:

Move corrupted sessions to `/var/lib/teleport/log/corrupted/` and stop trying to upload it

### PR DESCRIPTION
**Pull request by zmb3**
This ensures that the uploader won't busy loop over the same corrupted upload file, while ensuring that the file is still preserved.

Fixes #18936
Fixes #8173

### CODE REVIEW

File: lib/events/filesessions/fileasync.go [hunk 1]
```diff
@@ -214,6 +219,9 @@ type ScanStats struct {
 	Scanned int
 	// Started is how many uploads have been started
 	Started int
+	// Corrupted is how many corrupted uploads have been
+	// moved out of the scan dir.
+	Corrupted int
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/events/filesessions/fileasync.go:224]: Yep, I was going to add that here and decided to leave it out of scope for now.

File: lib/auth/helpers.go [hunk 2]
```diff
@@ -102,14 +102,16 @@ func (cfg *TestAuthServerConfig) CheckAndSetDefaults() error {
...
-	if err := os.MkdirAll(filepath.Join(dir, teleport.LogsDir, teleport.ComponentUpload,
-		events.StreamingLogsDir, apidefaults.Namespace), teleport.SharedDirMode); err != nil {
-		return trace.ConvertSystemError(err)
+// CreateUploaderDirs creates the directory structure for the file uploader service.
+func CreateUploaderDirs(dir string) error {
+	var errs []error
+
+	for _, dirname := range []string{events.StreamingSessionsDir, events.CorruptedSessionsDir} {
+		path := filepath.Join(dir, teleport.LogsDir, teleport.ComponentUpload, dirname, apidefaults.Namespace)
+		errs = append(errs, os.MkdirAll(path, teleport.SharedDirMode))
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/auth/helpers.go:111]: Yeah because on first glance `ConvertSystemError` didn't seem to handle nil, and this is only a test helper so I thought I could get away with it. I'll take a closer look.

File: lib/events/filesessions/fileasync.go [hunk 3]
```diff
@@ -348,10 +358,24 @@ func (u *Uploader) startUpload(ctx context.Context, fileName string) error {
...
+		}
+		if len(moveErrs) > 0 {
+			u.log.Errorf("Failed to move corrupted recording: %v", trace.NewAggregate(moveErrs...))
+		}
+
 		return sessionError{
 			err: trace.BadParameter(
-				"session recording %v is either corrupted or is using unsupported format, remove the file %v to correct the problem, remove the %v file to retry the upload",
-				sessionID, sessionFilePath, u.sessionErrorFilePath(sessionID)),
+				"session recording %v; check the %v directory for artifacts",
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/events/filesessions/fileasync.go:377]: Yeah, `sessionError` already prefixes the message with `"session file could be corrupted or is using unsupported format: %v"` so we were saying the same thing twice.

Prior to this change, the error would say:

```
session file could be corrupted or is using unsupported format: session recording abcd is either corrupted or is using unsupported format, remove the file to correct the problem, remove the other file to retry the upload
```

Now it says:

```
session file could be corrupted or is using unsupported format: session recording 1234; check the corrupted directory for artifacts
```

File: lib/events/filesessions/fileasync.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/events/filesessions/fileasync.go:224]: cc @EdwardDowling ^

File: lib/srv/app/server.go [hunk 4]
```diff
@@ -759,7 +759,8 @@ func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 		err = s.serveHTTP(w, r)
 	}
 	if err != nil {
-		s.log.Warnf("Failed to serve request: %v.", err)
+		// s.log.Warnf("Failed to serve request: %v.", err)
+		s.log.WithError(err).Warnf("Failed to serve request")
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/srv/app/server.go:763]: Oops, never meant to commit this change. reverting to original

File: lib/events/auditlog.go [hunk 5]
```diff
@@ -52,11 +52,17 @@ const (
 	// in /var/lib/teleport/log/sessions
 	SessionLogsDir = "sessions"
 
-	// StreamingLogsDir is a subdirectory of sessions /var/lib/teleport/log/streaming
+	// StreamingSessionsDir is a subdirectory of sessions (/var/lib/teleport/log/upload/streaming)
 	// is used in new versions of the uploader. This directory is used in asynchronous
```
Comment (codingllama) [inline lib/events/auditlog.go:56]:
```suggestion
	// that is used in new versions of the uploader. This directory is used in asynchronous
```

Missing word, I think?

File: lib/events/filesessions/fileasync.go [hunk 6]
```diff
@@ -244,14 +259,16 @@ func (u *Uploader) Scan(ctx context.Context) (*ScanStats, error) {
...
+				stats.Corrupted++
 				continue
 			}
 			return nil, trace.Wrap(err)
 		}
 		stats.Started++
 	}
 	if stats.Scanned > 0 {
-		u.log.Debugf("Scanned %v uploads, started %v in %v.", stats.Scanned, stats.Started, u.cfg.ScanDir)
+		u.log.Debugf("Scanned %v uploads, started %v, found %v corrupted in %v.",
```
Comment (codingllama) [inline lib/events/filesessions/fileasync.go:270]: Maybe log corrupted stats only it if we've got at least one? I assume these are pretty rare.

File: lib/service/service.go [hunk 7]
```diff
@@ -2482,33 +2482,40 @@ func (process *TeleportProcess) initUploaderService() error {
...
+			dir := filepath.Join(path[:i+1]...)
+			log.Infof("Creating directory %v.", dir)
+			err := os.Mkdir(dir, 0o755)
+			err = trace.ConvertSystemError(err)
 			if err != nil {
-				return trace.ConvertSystemError(err)
+				if !trace.IsAlreadyExists(err) {
+					return trace.Wrap(err)
+				}
+			}
```
Comment (codingllama) [inline lib/service/service.go:2500]:
```suggestion
			if err != nil && !trace.IsAlreadyExists(err) {
				return trace.Wrap(err)
			}
```

File: lib/service/service.go [hunk 8]
```diff
@@ -2482,33 +2482,40 @@ func (process *TeleportProcess) initUploaderService() error {
...
+			if uid != nil && gid != nil {
+				log.Infof("Setting directory %v owner to %v:%v.", dir, *uid, *gid)
+				err := os.Chown(dir, *uid, *gid)
```
Comment (codingllama) [inline lib/service/service.go:2503]: I assume this is why we don't want to use os.MkdirAll? I wonder if MkdirAll followed by a Walk wouldn't be simpler?

**Review by codingllama — APPROVED** [review]

File: lib/events/filesessions/fileasync.go (hunk 6 above)
Comment (zmb3) [reply lib/events/filesessions/fileasync.go:270]: I don't think it hurts anything including it here. Another if statement inside here is just extra branching for little benefit.

File: lib/service/service.go (hunk 8 above)
Comment (zmb3) [reply lib/service/service.go:2503]: Not 100% sure to be honest, but that's my guess too. It's been this way for a looong time.

**Review by rosstimothy — APPROVED** [review]

File: lib/events/filesessions/fileasync.go [hunk 9]
```diff
@@ -348,10 +365,24 @@ func (u *Uploader) startUpload(ctx context.Context, fileName string) error {
 		return trace.Wrap(err)
 	}
 	if isSessionError {
```
Comment (r0mant) [inline lib/events/filesessions/fileasync.go:367]: Couple of questions here:

- Can we get the `isSessionError` for any other reason than corrupted file?
- Can it happen that the "corrupted" upload becomes "uncorrupted"? What I mean is, would it make sense to, say, declare it corrupted only after N unsuccessful upload attempts instead of right away?

File: lib/srv/db/streamer.go [hunk 10]
```diff
@@ -78,18 +76,7 @@ func (s *Server) newStreamer(ctx context.Context, sessionID string, recConfig ty
...
 		s.cfg.DataDir, teleport.LogsDir, teleport.ComponentUpload,
-		libevents.StreamingLogsDir, apidefaults.Namespace)
-	// Make sure the upload dir exists, otherwise file streamer will fail.
-	_, err := utils.StatDir(uploadDir)
-	if err != nil && !trace.IsNotFound(err) {
-		return nil, trace.Wrap(err)
-	}
-	if trace.IsNotFound(err) {
-		s.log.Debugf("Creating upload dir %v.", uploadDir)
-		if err := os.MkdirAll(uploadDir, 0755); err != nil {
```
Comment (r0mant) [inline lib/srv/db/streamer.go:89]: Are these directories created elsewhere now, or was this always redundant check?

**Review by r0mant — APPROVED** [review]
lgtm with a couple of questions

File: lib/events/filesessions/fileasync.go (hunk 9 above)
Comment (zmb3) [reply lib/events/filesessions/fileasync.go:367]: No, that error is only for corrupted files. If you look at its `Error() string` method you'll see it prefixes every error with "the file is corrupted".

This happens if the file contains data that can not be read (either because it's not properly gzipped, or because the uncompressed data inside is not a protobuf). In any case, the contents of the file on disk aren't going to magically change, so a retry is not going to have different results.

(This is why we're seeing customers with huge CPU spikes. Even though we don't try to re-upload the file after we know it's corrupted, we still call `startUpload` only to realize that we shoudl skip this upload over and over and over again)

File: lib/srv/db/streamer.go (hunk 10 above)
Comment (zmb3) [reply lib/srv/db/streamer.go:89]: The creation was moved to the component that actually depends on the directory being there.

https://github.com/gravitational/teleport/pull/19011/files#diff-19d75ef44d31857c535a22a5eefc8423ad461f311575142e0777c876c27cb254R95-R100

**Comment by zmb3** [comment]
Note to self: in order to backport to v10 and earlier we may want to backport #14521 as well.
