### PR TITLE
Fix NO_PROXY addr logic

### LINKED ISSUE #9191: Multiplexing mode should respect NO_PROXY setting
### Description

**What happened**:

Teleport v8.0.0 git:v8.0.0-0-g6720c97

When an ssh_service node attempts to connect in IOT mode to a multiplexed backend, it respects the https_proxy setting, but not the corresponding no_proxy setting. The teleport proxy hostname should have been ignored due to the NO_PROXY/no_proxy listing a *.example.com that it should have matched. The result is that the teleport node attempts the connection through the proxy, which is incorrect for this particular environment.

**What you expected to happen**:

teleport should never make http connect connections to the teleport multiplexing proxy backend if the teleport proxy hostname is excluded in the no_proxy/NO_PROXY env var.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`): Teleport v8.0.0 git:v8.0.0-0-g6720c97 go1.17.
- Server OS (e.g. from `/etc/os-release`): centos7 with tarball binaries distributed for centos6
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
N/A

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)

```
Dec 01 18:04:19 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/connect.go:133 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect
Dec 01 18:04:19 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/connect.go:83 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService
Dec 01 18:04:19 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/connect.go:51 github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService
Dec 01 18:04:19 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/service.go:2075 github.com/gravitational/teleport/lib/service.(*TeleportProcess).registerWithAuthServer.func1
Dec 01 18:04:19 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:494 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
Dec 01 18:04:19 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:263 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
Dec 01 18:04:19 iotmode.example.com teleport[30906]: /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
Dec 01 18:04:19 iotmode.example.com teleport[30906]: User Message: Get &#34;https://teleport.cluster.local/v2/domain&#34;: x509: certificate is valid for teleport.example.com, www.teleport.example.com, not 34232a25124c10389a7391067a9a71118857812b159a1c.teleport.cluster.local] service/connect.go:850
Dec 01 18:04:19 iotmode.example.com teleport[30906]: 2021-12-01T18:04:19-05:00 DEBU [PROC:1]    Failed to connect to Auth Server through tunnel. error:[Get "https://teleport.cluster.local/v2/domain": unable to proxy connection: 502 Bad Gateway] proxy-addr:teleport.example.com:443 service/connect.go:851
Dec 01 18:04:19 iotmode.example.com teleport[30906]: 2021-12-01T18:04:19-05:00 ERRO [PROC:1]    Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.. service/connect.go:68
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [PROC:1]    Connected state: never updated. service/connect.go:103
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 INFO [PROC:1]    Connecting to the cluster teleport.example.com with TLS client certificate. service/connect.go:132
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [PROC:1]    Attempting to connect to Auth Server directly. auth-addrs:[teleport.example.com:443] service/connect.go:818
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [PROC:1]    Failed to connect to Auth Server directly. auth-addrs:[teleport.example.com:443] service/connect.go:824
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [PROC:1]    Attempting to discover reverse tunnel address. auth-addrs:[teleport.example.com:443] service/connect.go:833
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU             Attempting GET teleport.example.com:443/webapi/find webclient/webclient.go:62
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [PROC:1]    Attempting to connect to Auth Server through tunnel. proxy-addr:teleport.example.com:443 service/connect.go:843
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU             Attempting GET teleport.example.com:443/webapi/find webclient/webclient.go:62
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU             Attempting GET teleport.example.com:443/webapi/find webclient/webclient.go:62
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [HTTP:PROX] Successfully parsed environment variable "HTTPS_PROXY": "http://198.51.100.77:8080" to "198.51.100.77:8080". proxy/proxy.go:306
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [HTTP:PROX] Found proxy "198.51.100.77:8080" in environment, returning proxy dialer. proxy/proxy.go:231
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [HTTP:PROX] Successfully parsed environment variable "HTTPS_PROXY": "http://198.51.100.77:8080" to "198.51.100.77:8080". proxy/proxy.go:306
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [HTTP:PROX] Found proxy "198.51.100.77:8080" in environment, returning proxy dialer. proxy/proxy.go:231
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 WARN [PROC:1]    Failed to close Auth Server tunnel client. error:[<nil>] service/connect.go:899
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [PROC:1]    Failed to connect to Auth Server directly. auth-addrs:[teleport.example.com:443] error:[
Dec 01 18:04:29 iotmode.example.com teleport[30906]: ERROR REPORT:
Dec 01 18:04:29 iotmode.example.com teleport[30906]: Original Error: *trace.ConnectionProblemError Get &#34;https://teleport.cluster.local/v2/domain&#34;: x509: certificate is valid for teleport.example.com, www.teleport.example.com, not 34232a25124c10389a7391067a9a71118857812b159a1c.teleport.cluster.local
Dec 01 18:04:29 iotmode.example.com teleport[30906]: Stack Trace:
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:133 github.com/gravitational/teleport/lib/httplib.ConvertResponse
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/auth/clt.go:280 github.com/gravitational/teleport/lib/auth.(*Client).Get
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/auth/clt.go:371 github.com/gravitational/teleport/lib/auth.(*Client).GetDomainName
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/auth/clt.go:1506 github.com/gravitational/teleport/lib/auth.(*Client).GetLocalClusterName
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/connect.go:923 github.com/gravitational/teleport/lib/service.(*TeleportProcess).newClientDirect
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/connect.go:819 github.com/gravitational/teleport/lib/service.(*TeleportProcess).newClient
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/connect.go:133 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connect
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/connect.go:83 github.com/gravitational/teleport/lib/service.(*TeleportProcess).connectToAuthService
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/connect.go:51 github.com/gravitational/teleport/lib/service.(*TeleportProcess).reconnectToAuthService
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/service.go:2075 github.com/gravitational/teleport/lib/service.(*TeleportProcess).registerWithAuthServer.func1
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:494 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:263 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
Dec 01 18:04:29 iotmode.example.com teleport[30906]: /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
Dec 01 18:04:29 iotmode.example.com teleport[30906]: User Message: Get &#34;https://teleport.cluster.local/v2/domain&#34;: x509: certificate is valid for teleport.example.com, www.teleport.example.com, not 34232a25124c10389a7391067a9a71118857812b159a1c.teleport.cluster.local] service/connect.go:850
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 DEBU [PROC:1]    Failed to connect to Auth Server through tunnel. error:[Get "https://teleport.cluster.local/v2/domain": unable to proxy connection: 502 Bad Gateway] proxy-addr:teleport.example.com:443 service/connect.go:851
Dec 01 18:04:29 iotmode.example.com teleport[30906]: 2021-12-01T18:04:29-05:00 ERRO [PROC:1]    Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.. service/connect.go:68
```

### PR DESCRIPTION
**Pull request by smallinsky**
## What: 
Fix https://github.com/gravitational/teleport/issues/9191

The `addr` env passed to `proxy.DialerFromEnvironment` is not actual remote address ( `addr` contains cluster name ) thus the `NO_PROXY` env variable is not correctly respected. 
Switch from `addr` to actual remote proxy address `t.ProxyAddr`

### CODE REVIEW

File: integration/proxy_test.go [hunk 1]
```diff
@@ -640,3 +641,71 @@ func TestALPNProxyDialProxySSHWithoutInsecureMode(t *testing.T) {
...
+	defer ts.Close()
+
+	u, err := url.Parse(ts.URL)
+	require.NoError(t, err)
+
+	require.NoError(t, os.Setenv("http_proxy", u.Host))
+	t.Cleanup(func() { os.Unsetenv("http_proxy") })
+
+	require.NoError(t, os.Setenv("no_proxy", "127.0.0.1"))
+	t.Cleanup(func() { os.Unsetenv("no_proxy") })
```
Comment (rosstimothy) [inline integration/proxy_test.go:689]: Use [`t.SetEnv`](https://pkg.go.dev/testing#T.Setenv)
```suggestion
	t.Setenv("http_proxy", u.Host)
	t.Setenv("no_proxy", "127.0.0.1")
```

**Review by rosstimothy — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]

**Comment by codingllama** [comment]
It looks like you are covered in the reviewer department, so silently sitting this one out.

@quinqu, I think the bot is assigning a new set of reviewers when the PR moves from "draft" to  "ready to review". FYI.

File: integration/proxy_test.go [hunk 2]
```diff
@@ -640,3 +641,71 @@ func TestALPNProxyDialProxySSHWithoutInsecureMode(t *testing.T) {
 	require.NoError(t, err)
 	require.Equal(t, "hello world\n", output.String())
 }
+
+// TestALPNProxyHTTPProxyNOProxyDial tests if a node joining to root cluster
+// takes into account http_proxy and no_proxy env variables.
+func TestALPNProxyHTTPProxyNOProxyDial(t *testing.T) {
```
Comment (r0mant) [inline integration/proxy_test.go:647]: Nit:

```suggestion
// TestALPNProxyHTTPProxyNoProxyDial tests if a node joining to root cluster
// takes into account http_proxy and no_proxy env variables.
func TestALPNProxyHTTPProxyNoProxyDial(t *testing.T) {
```

File: integration/proxy_test.go (hunk 1 above)
Comment (r0mant) [reply integration/proxy_test.go:689]: This is a nice trick to know.

File: integration/proxy_test.go [hunk 3]
```diff
@@ -640,3 +641,71 @@ func TestALPNProxyDialProxySSHWithoutInsecureMode(t *testing.T) {
...
+	require.NoError(t, os.Setenv("no_proxy", "127.0.0.1"))
+	t.Cleanup(func() { os.Unsetenv("no_proxy") })
+
+	rcProxyAddr := net.JoinHostPort(Loopback, rc.GetPortWeb())
+
+	// Start the node, due to no_proxy=127.0.0.1 env variable the connection established
+	// to the proxy should not go through the http_proxy server.
+	_, err = rc.StartNode(makeNodeConfig("first-root-node", rcProxyAddr))
+	require.NoError(t, err)
+	err = waitForNodeCount(context.Background(), rc, "root.example.com", 1)
```
Comment (r0mant) [inline integration/proxy_test.go:697]: Nit: Here and below, I'd pass a context with some timeout instead of background (unless waitForNodeCount already has a timeout).

**Review by r0mant — APPROVED** [review]

File: integration/proxy_test.go (hunk 1 above)
Comment (smallinsky) [reply integration/proxy_test.go:689]: Thanks.
