### PR TITLE
MWI: Fix flaky tests for automatic bot lockouts

### LINKED ISSUE #56303: `TestRegisterBotCertificateGenerationStolen` flakiness
#### Link(s) to logs

https://github.com/gravitational/teleport.e/actions/runs/15996158747/job/45119951023

#### Relevant snippet

```
    bot_test.go:580: 
        	Error Trace:	/__w/teleport.e/teleport.e/lib/auth/bot_test.go:580
        	Error:      	An error is expected but got nil.
        	Test:       	TestRegisterBotCertificateGenerationStolen
```

### PR DESCRIPTION
**Pull request by timothyb89**
This fixes a flaky test, `TestRegisterBotCertificateGenerationStolen`, which assumed authenticated clients would immediately lose access if locked. It also fixes another test introduced at the same time that contains a similar check.

Fixes #56303

### CODE REVIEW

File: lib/auth/bot_test.go [hunk 1]
```diff
@@ -575,9 +575,11 @@ func TestRegisterBotCertificateGenerationStolen(t *testing.T) {
 	require.NoError(t, err)
 	require.NotEmpty(t, locks)
 
-	// The original client should now be locked out.
-	_, err = renewedClient.Ping(ctx)
-	require.ErrorContains(t, err, "access denied")
+	// The original client should be locked out.
+	require.Eventually(t, func() bool {
```
Comment (timothyb89) [inline lib/auth/bot_test.go:579]: Wrapping this in a `require.Eventually()` isn't exactly my first choice but I wasn't able to reproduce the failure locally in several thousand iterations with the race detector enabled. I expect this is just some cache sync or other acceptable raciness but would be happy to hear alternative solutions!

**Review by zmb3 — APPROVED** [review]

File: lib/auth/bot_test.go [hunk 2]
```diff
@@ -575,9 +575,11 @@ func TestRegisterBotCertificateGenerationStolen(t *testing.T) {
...
+		_, err = renewedClient.Ping(ctx)
+		return err != nil && strings.Contains(err.Error(), "access denied")
+	}, 3*time.Second, 100*time.Millisecond)
```
Comment (rosstimothy) [inline lib/auth/bot_test.go]: Suggestion: bump the wait to something like 5s or 10s here and below to account for limited resources in CI
```suggestion
	}, 5*time.Second, 100*time.Millisecond)
```

**Review by rosstimothy — APPROVED** [review]

File: lib/auth/bot_test.go (hunk 2 above)
Comment (timothyb89) [reply lib/auth/bot_test.go]: Fair enough, I've raised both to 5 seconds!
