### PR TITLE
Fix improper report of status on success

### LINKED ISSUE #24106: Kubernetes exec protocol not being proxied correctly over WebSockets
**Expected Behaviour**

At the end of an exec session over WebSockets, the status of the session should be returned in a JSON form as part of the `WebSocket Connection Close [FIN]` message, like so:

```json
{"metadata":{},"status":"Success"}
```

**Current Behaviour**

The `WebSocket Connection Close [FIN]` message is empty, and does not contain the Status object as it ought to.

**Details**

Auth / Proxy Servers: Teleport Enterprise v10.3.13
Kubernetes Agent: Teleport v10.3.14
`tsh`: Teleport v10.3.13

**Recreation**

I have experienced this issue while using the [kubernetes-client/javascript](https://github.com/kubernetes-client/javascript) library - they provide [an example](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/exec/exec-example.ts) which, with a bit of tweaking to match your environment, should assist in reproducing the error.

The status callback on line 13 of that example will differ depending on whether Teleport proxies the call, as described above.

**Packet Capture**

I used Wireshark to capture the session of both a cluster without Teleport, and a cluster with Teleport.

<details><summary>without Teleport</summary>
<p>

image

</p>
</details> 

<details><summary>with Teleport</summary>
<p>

image

</p>
</details>

The missing payload can be clearly seen between these two screenshots.

**Debugging**

I have taken a look at the relevant Teleport code, and the only suspicious thing I've been able to find is [this function](https://github.com/gravitational/teleport/blob/3a429c27fb27fcc533c6216f7b48f53e2ffbb6f3/lib/kube/proxy/remotecommand.go#L417), which shouldn't even be getting called in this case (as I have verified in my packet capture that the V4 API was negotiated, not the V1 API).

### PR DESCRIPTION
**Pull request by tigrato**
This PR fixes an edge case where the exec status wasn't properly returned to the clients when the remote execution was successful.

Fixes #24106

### CODE REVIEW

File: lib/kube/proxy/websocket_client_testing.go [hunk 1]
```diff
@@ -350,7 +349,11 @@ func (e *wsStreamClient) stream(conn *gwebsocket.Conn, options clientremotecomma
 	}()
 
 	wg.Wait()
-	close(errChan)
+	// always expect an error from the errChan since it means that the connection was closed
+	// by the server by sending a streamErr with the error.
+	// If no error happened during the remote execution, the server sends a streamErr with
+	// status = Success field.
+	// If the server didn't send any error, this call will block forever.
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_testing.go:356]: Should we try to detect this and give a better error, so we don't rely solely on `go test -timeout` in case it fails this way?

**Review by codingllama — APPROVED** [review]

File: lib/kube/proxy/websocket_client_testing.go (hunk 1 above)
Comment (tigrato) [reply lib/kube/proxy/websocket_client_testing.go]: Introduced in b0b5212808dbad52f122844525ac897df8386a27

**Review by atburke — APPROVED** [review]

**Review by codingllama — APPROVED** [review]
