### PR TITLE
Fix data race in ClientTLSConfigGenerator

### LINKED ISSUE #46681: TLS config data race in initProxyEndpoint
Expected behavior:
no data races

Current behavior:
```
==================
WARNING: DATA RACE
Read at 0x00c00291ce48 by goroutine 1929:
  crypto/tls.(*Config).Clone()
      /opt/go/src/crypto/tls/common.go:887 +0x42b
  github.com/gravitational/teleport/lib/auth.(*ClientTLSConfigGenerator).generator()
      /__w/teleport/teleport/lib/auth/client_tls_config_generator.go:179 +0x529
  github.com/gravitational/teleport/lib/auth.(*ClientTLSConfigGenerator).generator-fm()
      <autogenerated>:1 +0x64
  github.com/gravitational/teleport/lib/utils/genmap.(*GenMap[go.shape.string,go.shape.*uint8]).generate()
      /__w/teleport/teleport/lib/utils/genmap/genmap.go:319 +0x3b7
  github.com/gravitational/teleport/lib/utils/genmap.(*GenMap[go.shape.string,go.shape.*uint8]).ensureEntry.gowrap1()
      /__w/teleport/teleport/lib/utils/genmap/genmap.go:265 +0x6b

Previous write at 0x00c00291ce48 by goroutine 829:
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint()
      /__w/teleport/teleport/lib/service/service.go:4802 +0x7c39
  github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxy.func1()
      /__w/teleport/teleport/lib/service/service.go:3789 +0x84
  github.com/gravitational/teleport/lib/service.(*LocalService).Serve()
      /__w/teleport/teleport/lib/service/supervisor.go:581 +0x35
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1()
      /__w/teleport/teleport/lib/service/supervisor.go:307 +0x488

Goroutine 1929 (running) created at:
  github.com/gravitational/teleport/lib/utils/genmap.(*GenMap[go.shape.string,go.shape.*uint8]).ensureEntry()
      /__w/teleport/teleport/lib/utils/genmap/genmap.go:265 +0x5d0
  github.com/gravitational/teleport/lib/utils/genmap.(*GenMap[go.shape.string,go.shape.*uint8]).Generate()
      /__w/teleport/teleport/lib/utils/genmap/genmap.go:156 +0x57
  github.com/gravitational/teleport/lib/auth.(*ClientTLSConfigGenerator).watchForCAChanges()
      /__w/teleport/teleport/lib/auth/client_tls_config_generator.go:251 +0x9c4
  github.com/gravitational/teleport/lib/auth.(*ClientTLSConfigGenerator).refreshClientTLSConfigs()
      /__w/teleport/teleport/lib/auth/client_tls_config_generator.go:189 +0x87
  github.com/gravitational/teleport/lib/auth.NewClientTLSConfigGenerator.gowrap1()
      /__w/teleport/teleport/lib/auth/client_tls_config_generator.go:108 +0x4f

Goroutine 829 (finished) created at:
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve()
      /__w/teleport/teleport/lib/service/supervisor.go:296 +0x104
  github.com/gravitational/teleport/lib/service.(*LocalSupervisor).Start()
      /__w/teleport/teleport/lib/service/supervisor.go:339 +0x304
  github.com/gravitational/teleport/integration/hsm.newTeleportService()
      /__w/teleport/teleport/integration/hsm/helpers.go:69 +0x2ba
  github.com/gravitational/teleport/integration/hsm.TestHSMRotation()
      /__w/teleport/teleport/integration/hsm/hsm_test.go:103 +0x4b7
  testing.tRunner()
      /opt/go/src/testing/testing.go:1690 +0x226
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1743 +0x44
==================
```

Bug details:
- Teleport version
  - master, probably introduced in https://github.com/gravitational/teleport/pull/43937
- Recreation steps
  - unclear, ci hit this in TestHSMRotation
- Debug logs
  - https://github.com/gravitational/teleport/actions/runs/10906548561/job/30268058419?pr=46658

### PR DESCRIPTION
**Pull request by espadolini**
Closes #46681

### CODE REVIEW

File: lib/auth/client_tls_config_generator.go [hunk 1]
```diff
@@ -87,6 +87,14 @@ func NewClientTLSConfigGenerator(cfg ClientTLSConfigGeneratorConfig) (*ClientTLS
 	if err := cfg.CheckAndSetDefaults(); err != nil {
 		return nil, trace.Wrap(err)
 	}
+	// we're going to start the generator, which means that we are potentially
+	// going to read from cfg.TLS at any point after returning, which means that
+	// either the caller must always give us a cloned [tls.Config], or we just
+	// make one here
+	cfg.TLS = cfg.TLS.Clone()
```
Comment (nklaassen) [inline lib/auth/client_tls_config_generator.go:94]: i don't know much about this tls config generator, but i'm curious, is there any potential correctness issue here? We are trying to set GetConfigForClient elsewhere which caused this race, is it wrong for this tls.Config to stick around without that GetConfigForClient?

Comment (espadolini) [reply lib/auth/client_tls_config_generator.go:94]: It is (and with this change we're effectively restoring the behavior that we had before #43937). The `GetConfigForClient` callback doesn't have an intrinsic way to access the "intended" `tls.Config` (much to @fspmarshall and I's chagrin) so any further changes to the original `tls.Config` would be lost anyway, and the `GetConfigForClient` in the `tls.Config` returned by `GetConfigForClient` is ignored, so this is correct as long as only `GetConfigForClient` is modified (which is all you can modify to begin with).

Comment (espadolini) [reply lib/auth/client_tls_config_generator.go:94]: (and that's the only field we modify after each call to `NewClientTLSConfigGenerator` currently in master)

**Review by nklaassen — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
