### PR TITLE
Return clearer error when FIPS build of tsh connects to non-FIPS cluster

### LINKED ISSUE #61118: Using a FIPS `tsh` build to connect to a non-FIPS cluster reports a confusing error
Expected behavior:

The user sees a clear error that suggests that they use a non-FIPS tsh build.

Current behavior:

The user sees an error that says:

```
ERROR REPORT:
Original Error: *trace.BadParameterError only RSA and ECDSA keys supported
```

This stack trace was captured with the 17.6.0 FIPS build of `tsh` during a `tsh login --debug`:

```
ERROR REPORT:

Original Error: *trace.BadParameterError only RSA and ECDSA keys supported

Stack Trace:

        [github.com/gravitational/teleport/api@v0.0.0/utils/sshutils/checker.go:142](mailto:github.com/gravitational/teleport/api@v0.0.0/utils/sshutils/checker.go:142) [github.com/gravitational/teleport/api/utils/sshutils.validateFIPSAlgorithm](http://github.com/gravitational/teleport/api/utils/sshutils.validateFIPSAlgorithm)

        [github.com/gravitational/teleport/api@v0.0.0/utils/sshutils/checker.go:109](mailto:github.com/gravitational/teleport/api@v0.0.0/utils/sshutils/checker.go:109) [github.com/gravitational/teleport/api/utils/sshutils.(*CertChecker).validateFIPS](http://github.com/gravitational/teleport/api/utils/sshutils.(*CertChecker).validateFIPS)

        [github.com/gravitational/teleport/api@v0.0.0/utils/sshutils/checker.go:61](mailto:github.com/gravitational/teleport/api@v0.0.0/utils/sshutils/checker.go:61) [github.com/gravitational/teleport/api/utils/sshutils.(*CertChecker).CheckCert](http://github.com/gravitational/teleport/api/utils/sshutils.(*CertChecker).CheckCert)

        [github.com/gravitational/teleport/lib/client/interfaces.go:643](http://github.com/gravitational/teleport/lib/client/interfaces.go:643) [github.com/gravitational/teleport/lib/client.(*KeyRing).checkCert](http://github.com/gravitational/teleport/lib/client.(*KeyRing).checkCert)

        [github.com/gravitational/teleport/lib/client/keyagent.go:633](http://github.com/gravitational/teleport/lib/client/keyagent.go:633) [github.com/gravitational/teleport/lib/client.(*LocalKeyAgent).Signers](http://github.com/gravitational/teleport/lib/client.(*LocalKeyAgent).Signers)

        [github.com/gravitational/teleport/lib/client/api.go:3267](http://github.com/gravitational/teleport/lib/client/api.go:3267) [github.com/gravitational/teleport/lib/client.(*TeleportClient).generateClientConfig](http://github.com/gravitational/teleport/lib/client.(*TeleportClient).generateClientConfig)

        [github.com/gravitational/teleport/lib/client/api.go:3154](http://github.com/gravitational/teleport/lib/client/api.go:3154) [github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToCluster](http://github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToCluster)

        [github.com/gravitational/teleport/lib/client/api.go:4305](http://github.com/gravitational/teleport/lib/client/api.go:4305) [github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToRootCluster](http://github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToRootCluster)

        [github.com/gravitational/teleport/tool/tsh/common/tsh.go:2243](http://github.com/gravitational/teleport/tool/tsh/common/tsh.go:2243) [github.com/gravitational/teleport/tool/tsh/common.onLogin](http://github.com/gravitational/teleport/tool/tsh/common.onLogin)

        [github.com/gravitational/teleport/tool/tsh/common/tsh.go:1661](http://github.com/gravitational/teleport/tool/tsh/common/tsh.go:1661) [github.com/gravitational/teleport/tool/tsh/common.Run](http://github.com/gravitational/teleport/tool/tsh/common.Run)

        [github.com/gravitational/teleport/tool/tsh/common/tsh.go:727](http://github.com/gravitational/teleport/tool/tsh/common/tsh.go:727) [github.com/gravitational/teleport/tool/tsh/common.Main](http://github.com/gravitational/teleport/tool/tsh/common.Main)

        [github.com/gravitational/teleport/tool/tsh/main.go:26](http://github.com/gravitational/teleport/tool/tsh/main.go:26) main.main

        runtime/proc.go:272 runtime.main

        runtime/asm_amd64.s:1700 runtime.goexit
```

### PR DESCRIPTION
**Pull request by tangyatsu**
# What 
Resolves #61118

This PR makes `tsh` return a user-friendly error message when a FIPS build of `tsh` attempts to connect to a non-FIPS cluster.

# Manual Tests

I built a custom `tsh` that always fails FIPS key validation. This behaves the same way as a real FIPS `tsh` connecting to a non-FIPS cluster.

The resulting error now looks like this:
```
tsh login --user tangyatsu
ERROR: tsh is running in FIPS mode, but the cluster's SSH keys are not FIPS-compliant. Please use a non-FIPS tsh binary to connect to this cluster.
	FIPS: only RSA and ECDSA keys supported
```

### CODE REVIEW

File: api/utils/sshutils/checker.go [hunk 1]
```diff
@@ -28,6 +28,8 @@ import (
 	"github.com/gravitational/teleport/api/constants"
 )
 
+var ErrNonFIPSKey = trace.BadParameter("only RSA and ECDSA keys supported")
```
Comment (zmb3) [inline api/utils/sshutils/checker.go]:
```suggestion
var ErrNonFIPSKey = errors.New("only RSA and ECDSA keys are supported")
```

Using `trace` for package-level errors generates a stack trace that is prior to `func main` and can slow down initialization.

**Review by zmb3 — APPROVED** [review]

File: api/utils/sshutils/checker.go [hunk 2]
```diff
@@ -28,6 +29,8 @@ import (
 	"github.com/gravitational/teleport/api/constants"
 )
 
+var ErrNonFIPSKey = errors.New("only RSA and ECDSA keys supported")
```
Comment (rosstimothy) [inline api/utils/sshutils/checker.go]: Should we update this error message (maybe the other errors returned from validateFIPSAlgorithm too?) to be less opaque and reference FIPS?

```suggestion
var ErrNonFIPSKey = errors.New("FIPS requires RSA or ECDSA keys")
```

File: tool/tsh/common/tsh.go [hunk 3]
```diff
@@ -1969,6 +1970,13 @@ func Run(ctx context.Context, args []string, opts ...CliOption) error {
 		return handleUnimplementedError(ctx, err, cf)
 	}
 
+	// A FIPS build of tsh is attempting to use a non-FIPS key returned by the cluster.
+	if moduleCfg.IsBoringBinary() && errors.Is(err, sshutils.ErrNonFIPSKey) {
+		return trace.Wrap(err,
+			"tsh is running in FIPS mode, but the cluster is not FIPS-compliant. Use a non-FIPS tsh binary to connect to the cluster.",
+		)
+	}
```
Comment (rosstimothy) [inline tool/tsh/common/tsh.go:1975]: Could we run into this same scenario with tctl too?

File: api/utils/sshutils/checker.go (hunk 2 above)
Comment (tangyatsu) [reply api/utils/sshutils/checker.go]: Sounds reasonable. I took another look, and I think it might be better to add a separate FIPSError struct that wraps FIPS related errors so we can detect all of them using errors.As.

File: tool/tsh/common/tsh.go (hunk 3 above)
Comment (tangyatsu) [reply tool/tsh/common/tsh.go:1975]: I haven’t looked into tctl yet, but I’ll check.

Comment (tangyatsu) [reply tool/tsh/common/tsh.go:1975]: From what I’ve checked, this should only trigger inside [keyRing.ProxyClientSSHConfig](https://github.com/gravitational/teleport/blob/2a5c3077d27abc0b084d3c1c066b6f579531a5fe/tool/tctl/common/config/profile.go#L101) when tctl is used against a remote auth server. But we can’t reach that part of the code before the user refreshes credentials via [tsh login](https://github.com/gravitational/teleport/blob/master/tool/tctl/common/config/profile.go#L71), so I’m not sure this is reproducible.

The only case I can imagine is: the user logs into a FIPS cluster and gets credentials, the cluster is then restarted in a non-FIPS mode, on the next request user gets this error.

I can add a similar error check into the [TryRun](https://github.com/gravitational/teleport/blob/0d17e1a075fc9d996c0c75eba82c984d231c140d/tool/tctl/common/tctl.go#L89) for tctl, but it might end up redundant. What’s your opinion?

Comment (rosstimothy) [reply tool/tsh/common/tsh.go:1975]: Thanks for taking a look. I'm happy to punt on tctl for now.

File: api/utils/sshutils/checker.go [hunk 4]
```diff
@@ -28,6 +29,18 @@ import (
...
+type FIPSError struct {
+	message string
+}
+
+func (f *FIPSError) Error() string {
+	return fmt.Sprintf("FIPS: %s", f.message)
+}
+
+func newFIPSError(message string, args ...interface{}) error {
+	return &FIPSError{fmt.Sprintf(message, args...)}
```
Comment (rosstimothy) [inline api/utils/sshutils/checker.go]: Is there any way to reduce this to a single fmt.Sprintf?

**Review by rosstimothy — APPROVED** [review]
