### PR TITLE
Fixes panic on group database errors during host user reconciliation

### LINKED ISSUE #53020: Teleport Agent Panic on Failed Group Lookup with SSSD
### Expected Behavior
Teleport should handle group lookup failures gracefully without crashing. If a group lookup fails due to issues with SSSD synchronization, the Teleport agent should continue running without causing a panic or service restart. Ideally, users should still be able to connect, even if not all group memberships can be verified.

### Current Behavior
A failed group lookup, specifically when SSSD synchronization is incomplete, results in a panic and crash of the Teleport agent. This causes a service restart and can lead to loss of connectivity for other users and services.

#### Teleport Version

Teleport Agent 17.2.9

#### Recreation Steps
1. Configure a Teleport node with user synchronization via SSSD.
2. Connect to the Teleport node using a user whose group synchronization is incomplete or fails (leading to invalid group ID lookups).
3. Observe the Teleport agent panic and crash.

Note that the Teleport user needs to have host user creation enabled in order to trigger the bug. The user exists via sssd, but when Teleport encounters the incomplete group entry, it panics.

#### Debug Logs

```
teleport[2650413]: 2025-03-11T08:21:55.093+01:00 DEBU [SESSION:N] Attempting to upsert host user host_username:unixlogin srv/sess.go:303
teleport[2650413]: 2025-03-11T08:21:55.093+01:00 DEBU [HOSTUSERS] Attempting to upsert host user host_username:unixlogin mode:1 uid: gid: srv/usermgmt.go:430
teleport[2650413]: panic: runtime error: invalid memory address or nil pointer dereference
teleport[2650413]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x56182bdccf48]
teleport[2650413]: goroutine 1016 [running]:
teleport[2650413]: github.com/gravitational/teleport/lib/srv.(*HostUserManagement).getHostUser(0xc003e1ecd0, {0xc003b46540, 0x7})
teleport[2650413]:         github.com/gravitational/teleport/lib/srv/usermgmt.go:686 +0x368
teleport[2650413]: github.com/gravitational/teleport/lib/srv.(*HostUserManagement).UpsertUser(0xc003e1ecd0, {0xc003b46540, 0x7}, {{0x56183b3025a0, 0x0, 0x0}, 0x1, {0x0, 0x0}, {0x0, ...}, ...})
teleport[2650413]:         github.com/gravitational/teleport/lib/srv/usermgmt.go:431 +0x1f9
teleport[2650413]: github.com/gravitational/teleport/lib/srv.(*SessionRegistry).UpsertHostUser(_, {0xc003b141e0, {0xc003b466d8, 0x7}, {0x0, 0x0}, {0xc003b46540, 0x7}, {0x561834a7f408, 0xc002e14d88}, ...})
teleport[2650413]:         github.com/gravitational/teleport/lib/srv/sess.go:320 +0x335
teleport[2650413]: github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewConn(0xc00382bc08, {0x5618349d62f0, 0xc004205180}, 0xc0022dac60)
teleport[2650413]:         github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1269 +0x2ba
teleport[2650413]: github.com/gravitational/teleport/lib/sshutils.(*Server).HandleConnection(0xc00382cfc8, {0x5618349fd4c8, 0xc00230eea0})
teleport[2650413]:         github.com/gravitational/teleport/lib/sshutils/server.go:578 +0xb7c
teleport[2650413]: github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleConnection(...)
teleport[2650413]:         github.com/gravitational/teleport/lib/srv/regular/sshserver.go:431
teleport[2650413]: github.com/gravitational/teleport/lib/resumption.(*SSHServerWrapper).HandleConnection(0xc003e76500, {0x5618349fd628, 0xc00230eae0})
teleport[2650413]:         github.com/gravitational/teleport/lib/resumption/server_detect.go:215 +0x378
teleport[2650413]: github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).handleLocalTransport(0xc003838340, {0x5618349d62f0, 0xc0044a9040}, {0x5618349ef628, 0xc003db2180}, 0xc0041da930, {0x7f333837f200, 0xc004328000})
teleport[2650413]:         github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:606 +0x598
teleport[2650413]: github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).handleTransport(0x56183ab690c0?, {0x5618349d62f0?, 0xc0044a9040?}, {0x5618349ef628?, 0xc003db2180?}, 0xc003051f98?, {0x7f333837f200?, 0xc004328000?})
teleport[2650413]:         github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:523 +0x185
teleport[2650413]: github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels.func2()
teleport[2650413]:         github.com/gravitational/teleport/lib/reversetunnel/agent.go:585 +0xae
teleport[2650413]: created by github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels in goroutine 383
teleport[2650413]:         github.com/gravitational/teleport/lib/reversetunnel/agent.go:583 +0x4d4
systemd[1]: teleport.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: teleport.service: Failed with result 'exit-code'.
```

### PR DESCRIPTION
**Pull request by eriktate**
Fixes #53020 

This fixes an issue where error returns from `user.LookupGroupByID` would cause host user reconciliation to panic and crash the teleport process. A missing `continue` meant that we would attempt to mark a group as found by accessing the `ID` field on a `nil` pointer.

changelog: Fixed an issue causing the teleport process to crash on group database errors when host user creation was enabled

### CODE REVIEW

**Review by marcoandredinis — APPROVED** [review]

File: lib/srv/usermgmt_test.go [hunk 1]
```diff
@@ -1105,3 +1110,30 @@ func TestHostUsersResolveGroups(t *testing.T) {
...
+	assert.NoError(t, err)
+	assert.Equal(t, nil, closer)
+	assert.Zero(t, backend.setUserGroupsCalls)
+	assert.ElementsMatch(t, append(userinfo.Groups, types.TeleportKeepGroup), backend.users["alice"])
+	assert.NotContains(t, backend.users["alice"], types.TeleportDropGroup)
+
+	backend.groupDatabaseErr = errors.New("could not find group")
+	require.NotPanics(t, func() {
+		closer, err = users.UpsertUser("alice", userinfo)
+	})
```
Comment (camscale) [inline lib/srv/usermgmt_test.go:1137]: I'm not sure this is how we should be testing this. You can make the argument that none of our code should panic (unless explicitly coded to do so), in which case we would have every test include a `requires.NotPanics()` wrapped around everything.

In this case, there was a panic due to mistaken error handling. Which says to me we need to test that the error handling is now correct, which means `UpsertUser()` returns an error when the group lookup returns an error. It is sufficient to just have the next line (`require.Error(t, err)`) and to remove the `NotPanic` assertion, as if it does panic, the test will still fail as panics in the code under test will always fail a test unless specifically caught and ignored.

**Review by camscale — APPROVED** [review]
Other than that, LGTM

File: lib/srv/usermgmt_test.go (hunk 1 above)
Comment (zmb3) [reply lib/srv/usermgmt_test.go:1137]: Spot on, Cam.

**Review by zmb3 — APPROVED** [review]

File: lib/srv/usermgmt_test.go (hunk 1 above)
Comment (eriktate) [reply lib/srv/usermgmt_test.go]: Great point. I included the `require.NotPanic()` just capture the specific regression this was guarding against, but you're right that it isn't actually testing anything valuable :+1: Updated!
