### PR TITLE
Fix dynamic windows registration

### LINKED ISSUE #52956: Dynamic Windows desktops should detect when agents are removed
When agents that are serving a dynamic_windows_desktop disappear, the corresponding windows_desktop resource should be removed so that Teleport doesn't try to route connections through an agent that no longer exists.

I suspect that we are currently watching the dynamic resource, but not watching the agent resources correctly.

### LINKED ISSUE #54723: Dynamic Windows apps are not refreshed
### Expected behavior:

If a `windows_desktop` object is manually deleted/edited outside the agent, the agent should recreate/announce it on its next heartbeat and/or announce interval. This is consistent with other dynamically loaded resources.

### Current behavior:

A deleted `windows_desktop` resource won't repopulate until the next time an agent cold-starts.

#### Recreation steps

* Create a `dynamic_windows_desktop` resource.
* Configure a Teleport Windows Desktop agent to load it.
* Observe a corresponding `windows_desktop` object is created for each agent that loads the resource.
* Delete one or more `windows_desktop` objects that correspond with a running agent.
* Observe that the `windows_desktop` object never repopulates.

Repeating the test with the `app` object instead of `dynamic_windows_desktop`, along with `app_server` instead of `windows_desktop`, and the app service _does_ repopulate the `app_server` resource.

### PR DESCRIPTION
**Pull request by probakowski**
This change adds expiry time for windows desktops created by WDS from dynamic windows desktops to provide a way to remove desktops after WDS goes away.
It also adds check if windows desktop still exists during reconciliation so we'll recreate windows desktops deleted by the user between checks (similarly to for example apps and app servers.

Closes https://github.com/gravitational/teleport/issues/54723
Closes https://github.com/gravitational/teleport/issues/52956

### CODE REVIEW

File: lib/srv/desktop/discovery.go [hunk 1]
```diff
@@ -399,6 +400,14 @@ func (s *WindowsService) startDynamicReconciler(ctx context.Context) (*services.
 			return services.MatchResourceLabels(s.cfg.ResourceMatchers, desktop.GetAllLabels())
 		},
 		GetCurrentResources: func() map[string]types.WindowsDesktop {
+			for k, v := range currentResources {
```
Comment (zmb3) [inline lib/srv/desktop/discovery.go]: You could use `maps.DeleteFunc` here.

File: lib/srv/desktop/discovery.go [hunk 2]
```diff
@@ -411,6 +420,9 @@ func (s *WindowsService) startDynamicReconciler(ctx context.Context) (*services.
 	if err != nil {
 		return nil, trace.Wrap(err)
 	}
+	tickDuration := 5 * time.Minute
+	expiryDuration := tickDuration + 10*time.Second
+	tick := s.cfg.Clock.NewTicker(tickDuration)
```
Comment (zmb3) [inline lib/srv/desktop/discovery.go]: Move these vars inside the goroutine since they're only used there.

Also, I would `defer tick.Stop()` as well, even if it's not strictly necessary anymore.

**Review by zmb3 — APPROVED** [review]

File: lib/srv/desktop/discovery.go [hunk 3]
```diff
@@ -414,12 +422,17 @@ func (s *WindowsService) startDynamicReconciler(ctx context.Context) (*services.
 	go func() {
 		defer s.cfg.Logger.DebugContext(ctx, "DynamicWindowsDesktop resource watcher done.")
 		defer watcher.Close()
+		tickDuration := 5 * time.Minute
+		expiryDuration := tickDuration + 10*time.Second
```
Comment (Tener) [inline lib/srv/desktop/discovery.go]: As written, we are having a small race whenever we need to update the desktop expiry time. On each tick we only have 10 seconds of expiry time remaining, which feels very short and may eventually lead to intermittent availability issues.

I think we can simply raise the delta without significant problems:

```suggestion
		tickDuration := 5 * time.Minute
		expiryDuration := tickDuration + 2*time.Minute
```

However, if there are thousands of desktops within the cluster, this will still add nontrivial load to the backend.

What is the highest we can go here without sacrificing UX?

Comment (probakowski) [reply lib/srv/desktop/discovery.go]: I bumped the expiry. We do similar thing for desktops from config file and discovered through LDAP (we refresh them every 5 min) so I think we should be OK here, @zmb3 thoughts?

**Review by Tener — APPROVED** [review]
