### PR TITLE
Forcibly exit VNet admin process if network stack doesn't shut down after timeout

### LINKED ISSUE #56834: Forcibly exit VNet admin process if network stack doesn't shut down after timeout
[We had reports](https://gravitational.zendesk.com/agent/tickets/14849) of the admin process of VNet on macOS not exiting after the user stops VNet through the UI, thus preventing VNet from starting again. Being unable to start VNet again manifests as "VNet is already running" error. This happens when the VNet daemon tells the user process that the daemon was already started.

```
[14-07-25 10:25:27] 2025-07-14T10:25:27.703-04:00 INFO [VNET]      Starting gRPC service addr:127.0.0.1:50222 vnet/user_process_darwin.go:89
[14-07-25 10:25:30] ERRO [CONN:APIS] Request failed. error:[
[14-07-25 10:25:30] ERROR REPORT:
[14-07-25 10:25:30] Original Error: *errors.errorString VNet is already running
[14-07-25 10:25:30] Stack Trace:
[14-07-25 10:25:30] 	github.com/gravitational/teleport/lib/vnet/daemon/client_darwin.go:292 github.com/gravitational/teleport/lib/vnet/daemon.startByCalling.func1
[14-07-25 10:25:30] 	runtime/asm_arm64.s:1223 runtime.goexit
[14-07-25 10:25:30] User Message: process manager exited before network stack info was received
[14-07-25 10:25:30] 	connecting to the VNet daemon
[14-07-25 10:25:30] 		VNet is already running] apiserver/middleware.go:39
[14-07-25 10:27:23] INFO             Captured terminated, stopping service. teleterm/teleterm.go:132
[14-07-25 10:27:23] INFO [DAEMON]    Stopping daemon/daemon.go:961
```

When we looked at `/var/log/vnet.log` from around the time when the user stopped VNet, we found that there was no logs that are emitted when VNet cleanly stops:

```
2025-07-15T14:55:27.595+02:00 INFO [VNET:DAEM] Stopping daemon trace_id:15fe639e9228a4b15ca2de36efad75e5 span_id:724e24204403f019 daemon/service_darwin.go:68
ERROR: running VNet admin process
	failed to ping client application, it may have exited, shutting down
		calling Ping rpc
			connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:49217: connect: connection refused"
```

Instead, the admin process seem to have stopped emitting logs from the OS configuration loop, just before the user stopped VNet.

This all means that the admin process likely got stuck while trying to clean up after itself, but the XPC service was still running and was able to respond to messages. This checks out, because [the XPC service runs until `RunDarwinAdminProcess` returns](https://github.com/gravitational/teleport/blob/deda8410b3d88a13f608428c383b396287c7a02d/lib/vnet/escalate_daemon_darwin.go#L37) and `RunDarwinAdminProcess` likely got stuck on cleanup.

[`RunDarwinAdminProcess` starts three goroutines](https://github.com/gravitational/teleport/blob/3d6ddf2d02758f075d6de80e9ca84fe61620b8f4/lib/vnet/admin_process_darwin.go#L90-L116). The one that pings the client is unlikely to hang, `clt.Ping` is bound to fail the moment the client shuts down the gRPC service. The goroutine that runs `osConfigurator.runOSConfigurationLoop` is also less likely to get stuck, as the moment the context gets canceled (because the `clt.Ping` goroutine returned an error), all it does is removes files in `/etc/resolver/` which is unlikely to hang the process for 3+ days, as was the case in the report linked at the start of the issue.

This leaves us with the goroutine running the network stack. `forwardBetweenTunAndNetstack` does some operations on the TUN device which can possibly block. The TUN device itself isn't closed until `ns.linkEndpoint.Close()` returns which needs to lock a mutex, so this could also be a culprit. But then we also have `ns.wg.Wait()` and `ns.stack.Destroy()`, both of which can possibly block.

We should add more logs so that we can find the exact call that blocks the cleanup. But in the meantime as a band-aid we can make the admin process forcibly exit if the network stack doesn't shut down within some timeout.

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/56834

I tried to reproduce the issue, but unfortunately with no luck. 
I implemented the proposed solution: better logging and forcibly exiting the admin process after a timeout.

changelog: Fixed an issue where VNet could not start because of "VNet is already running" error

### CODE REVIEW

File: lib/vnet/admin_process_darwin.go [hunk 1]
```diff
@@ -113,7 +117,29 @@ func RunDarwinAdminProcess(ctx context.Context, config daemon.Config) error {
...
+		return trace.Wrap(err, "running VNet admin process")
+	case <-ctx.Done():
+		timer := time.NewTimer(5 * time.Second)
+		defer timer.Stop()
+
+		select {
+		case <-done:
+			// network stack exited cleanly within timeout
+			return trace.Wrap(err, "running VNet admin process")
+		case <-timer.C:
```
Comment (ravicious) [inline lib/vnet/admin_process_darwin.go]:
```suggestion
		case <-time.After(10 * time.Second):
```

This is the new way of doing this, see the docs for [`time.After`](https://pkg.go.dev/time#After). I'd also bump the timeout to 10s just to be safe, the error message will have to be updated as well.

**Review by ravicious — APPROVED** [review]
I tested this by adding yet another goroutine to the errgroup that hangs forever and the code does its job. I tried it using an actual VNet daemon in a VM.

File: lib/vnet/network_stack.go
Comment (ravicious) [inline lib/vnet/network_stack.go:1]: @nklaassen Do you happen to know why the wireguard package isn't getting updated? I'm not familiar with our upgrade process for Go packages, but I see that we're on an old version. In May there were multiple commits in the device package that could be related to deadlocks. https://git.zx2c4.com/wireguard-go/log/

https://github.com/gravitational/teleport/blob/387e4efb0bf64fa21998950b4f73c441ffe57e3a/go.mod#L242-L243

File: lib/vnet/admin_process_darwin.go [hunk 2]
```diff
@@ -113,7 +117,29 @@ func RunDarwinAdminProcess(ctx context.Context, config daemon.Config) error {
...
+			log.ErrorContext(ctx, "VNet admin process did not exit within 5 seconds, forcing shutdown.")
+			os.Exit(1)
+			return nil
+		}
+	}
```
Comment (nklaassen) [inline lib/vnet/admin_process_darwin.go]: make sure to set `err` in the second select where you receive from the channel, you can also pull the second select out to reduce indentation
```suggestion
	case <-ctx.Done():
	}

	select {
	case err := <-done:
		// network stack exited cleanly within timeout
		return trace.Wrap(err, "running VNet admin process")
	case <-time.After(5*time.Second):
		log.ErrorContext(ctx, "VNet admin process did not exit within 5 seconds, forcing shutdown.")
		os.Exit(1)
		return nil
	}
```

**Review by nklaassen — APPROVED** [review]
