### PR TITLE
Fix moderated sessions joining when Kube cluster has multi-agents

### LINKED ISSUE #26684: Kubernetes moderated sessions joining is broken when kube agents replicas>1
Expected behavior:
Users must be able to join the kubernetes session independently of the number of replicas their kubernetes cluster runs with.

Current behavior:
```
❯ tsh kube join -m moderator 92687755-ac95-4e62-b0a3-89cb88325446
Joining session with participant mode: moderator. 

# 
Left session
❯ tsh kube join -m moderator 92687755-ac95-4e62-b0a3-89cb88325446
Joining session with participant mode: moderator. 

ERROR: session 92687755-ac95-4e62-b0a3-89cb88325446 not found

❯ tsh kube join -m moderator 92687755-ac95-4e62-b0a3-89cb88325446
Joining session with participant mode: moderator. 

ERROR: session 92687755-ac95-4e62-b0a3-89cb88325446 not found

❯ tsh kube join -m moderator 92687755-ac95-4e62-b0a3-89cb88325446
Joining session with participant mode: moderator. 

ERROR: session 92687755-ac95-4e62-b0a3-89cb88325446 not found

❯ tsh kube join -m moderator 92687755-ac95-4e62-b0a3-89cb88325446
Joining session with participant mode: moderator. 
```

### PR DESCRIPTION
**Pull request by tigrato**
This PR fixes a bug introduced in the original Moderated sessions implementation (#8563). When the same Kubernetes cluster is served by multiple kubernetes agents, the joining function didn't consider the `host_id` that owns the moderated session. This results in users receiving `session not found` errors when the reversetunnel dialer picks a random agent that does not own the session.

Given that we encourage multiple agents running in the same kube cluster, a user has $1/n$, where $n=number.of.agent.replicas$ probability of being able to join the session.

This PR fixes this bug by forcing the dialer to filter out kube agents that do not own the session. A new field, `HostID` was introduced into the session tracker to store this information and only Kubernetes proxies will request the session tracker from the Auth server to retrieve that value. With `host_id`, the kube proxy is able to filter the host that owns the session and will connect to it. If the agent is no longer available, an error is returned to the user.

Fixes #26684

### CODE REVIEW

File: lib/kube/proxy/forwarder.go [hunk 1]
```diff
@@ -1320,6 +1325,24 @@ func (f *Forwarder) remoteJoin(ctx *authContext, w http.ResponseWriter, req *htt
...
+// getSessionHostID returns the host ID that controls the session being joined.
+// If the session is remote, returns an empty string, otherwise returns the host ID
+// from the session tracker.
+func (f *Forwarder) getSessionHostID(ctx context.Context, authCtx *authContext, p httprouter.Params) (string, error) {
+	if authCtx.teleportCluster.isRemote {
+		return "", nil
+	}
+	session := p.ByName("session")
+	if session == "" {
+		return "", trace.BadParameter("missing session ID")
```
Comment (zmb3) [inline lib/kube/proxy/forwarder.go:1337]: Do we need to worry about backwards compatibility here, or did it never work so this is fine?

**Review by zmb3 — APPROVED** [review]

File: lib/kube/proxy/forwarder.go [hunk 2]
```diff
@@ -1320,6 +1325,24 @@ func (f *Forwarder) remoteJoin(ctx *authContext, w http.ResponseWriter, req *htt
...
+	}
+	sess, err := f.cfg.AuthClient.GetSessionTracker(ctx, session)
```
Comment (xacrimon) [inline lib/kube/proxy/forwarder.go:1339]: should we check the local set of trackers first to avoid an RTT in that case?

**Review by xacrimon — APPROVED** [review]

File: lib/kube/proxy/forwarder.go (hunk 2 above)
Comment (tigrato) [reply lib/kube/proxy/forwarder.go:1339]: This code path is only executed when the tracking session is remote (not local).
