### PR TITLE
fix: Agent Forwarding - Windows System Agent and 1Password agent

### LINKED ISSUE #46076: 1Password SSH agent forwarding fails (broken pipe) after 60 seconds
I'm using the 1Password SSH agent and forwarding it over a teleport connection (the `-A` argument in `tsh ssh --proxy=teleport.example.com -tA danepowell@bastion`)

Once connected to the bastion, I can SSH into other hosts using keys in my 1Password agent without any issue for 60 seconds. After 60 seconds, any further attempts to access the agent produce an error: `agent 11: agent: client error: write unix ->/Users/dane.powell/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock: write: broken pipe`

Someone [previously reported this error to 1Password](https://1password.community/discussion/136875/forwarded-ssh-agent-refuses-operation-after-a-while), you might find more details in that post. I'm coordinating with 1Password support, but it's unclear who's responsible. SSH agent forwarding works without issue if I use the stock Mac agent and keep my keys on disk. It also works fine with the 1Password agent if I connect to a non-proxy host.

Expected behavior:
- Forwarded SSH agents continue working indefinitely

Current behavior:
- A forwarded 1Password ssh agent works for 60 seconds, then any further attempts to access it produce an error: `agent 11: agent: client error: write unix ->/Users/dane.powell/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock: write: broken pipe`

Bug details:
```
❯ tsh version
Teleport v14.3.23 git:v14.3.23-0-g69e5efb go1.22.6
Proxy version: 14.3.26
```

### LINKED ISSUE #52008: SSH Agent Forwarding from Windows with `tsh ssh` Only Works Once
### Expected Behavior
SSH agent forwarding via `tsh ssh` from a Windows workstation to should consistently allow multiple SSH agent uses without needing to reconnect.

### Current Behavior
SSH agent forwarding via `tsh ssh` from a Windows host works only for the first connection attempt. Subsequent attempts fail with the error "agent 11: agent: client error: The pipe is being closed." Reconnecting temporarily resolves the issue, but it reoccurs on the next attempt.

#### Teleport Version

Reported with:
- `tsh`: v15.4.27
- Proxy version: 15.4.17

Reproduced with:
- `tsh`: Teleport v17.1.1 git: go1.23.4
- Proxy version: 17.2.6

#### Recreation Steps
1. Configure the Microsoft Windows OpenSSH component. (I reproduced with `OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2`).
2. Ensure that no other SSH agent is overriding the default OpenSSH `ssh-agent`.
3. Add an SSH key to the agent:

    ```
    PS C:\Users\jeff> ssh-add
    Identity added: C:\Users\jeff/.ssh/id_rsa (C:\Users\jeff/.ssh/id_rsa)
    PS C:\Users\jeff> ssh-add -l
    2048 SHA256:S3MFd1MRyBcForhDG9wdPe+R0FnTyBMUQB8l2lSqnLQ C:\Users\jeff/.ssh/id_rsa (RSA)
    ```

4. Log in to Teleport via `tsh` and SSH to a node with agent forwarding:

    ```
    PS C:\Users\jeff> tsh --debug ssh -A user@mynode
    ...
    2025-02-10T09:46:17-05:00 INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "" client\api.go:4692
    2025-02-10T09:46:17-05:00 DEBU [CLIENT]    Forwarding Selected Key Agent client\session.go:259
    jeff@mynode:~$ ssh-add -l
    2048 SHA256:S3MFd1MRyBcForhDG9wdPe+R0FnTyBMUQB8l2lSqnLQ C:\Users\jeff/.ssh/id_rsa (RSA)
    ```

5. Verify the SSH agent on the first connection attempt.

    ```
    jeff@mynode:~$ ssh -v jeff@otherhost
    ...
    debug1: Will attempt key: C:\\Users\\jeff/.ssh/id_rsa RSA SHA256:S3MFd1MRyBcForhDG9wdPe+R0FnTyBMUQB8l2lSqnLQ agent
    ...
    debug1: Offering public key: C:\\Users\\jeff/.ssh/id_rsa RSA SHA256:S3MFd1MRyBcForhDG9wdPe+R0FnTyBMUQB8l2lSqnLQ agent
    debug1: Server accepts key: C:\\Users\\jeff/.ssh/id_rsa RSA SHA256:S3MFd1MRyBcForhDG9wdPe+R0FnTyBMUQB8l2lSqnLQ agent
    ...
    jeff@otherhost:~$ exit
    logout
    Connection to othernode closed.
    ```

6. While staying in the same `tsh ssh -A` session, attempt to use the SSH agent a second time:

    ```
    jeff@mynode:~$ ssh -v jeff@othernode
    ...
    2025-02-10T11:19:05-05:00 INFO  agent 11: agent: client error: The pipe is being closed.
    debug1: get_agent_identities: ssh_fetch_identitylist: agent refused operation
    ...
    jeff@othernode's password:
    ```

7. Note the error: "agent 11: agent: client error: The pipe is being closed." coming from the `--debug` output from `tsh`. Every subsequent attempt to connect to the agent inside this session produces the same `tsh` debug output.

### PR DESCRIPTION
**Pull request by Joerger**
Currently, x/crypto/ssh/agent https://github.com/golang/go/issues/61383 for the Windows named pipe system agent. Instead, we have been using winio to open the named pipe connection and pass that into agent.NewClient like a normal net.Conn. The issue with this approach is that the named pipe connection does not seem to act just like a normal unix socket connection, and the connection is disrupted after an agent signature request, resulting in the forwarded agent becoming dysfunctional after just one use.

This PR works around this issue by opening a new agent connection for each incoming agent forwarding channel request, in the new sshagent.ServeChannelRequests method. Preparing a fresh connection ensures that temporary connection disruptions, agent service restarts, etc. won't affect future ssh agent requests. This approach should be more durable in general and is in line with the OpenSSH implementation. For example, this also fixes https://github.com/gravitational/teleport/issues/46076.

Fixes https://github.com/gravitational/teleport/issues/52008, https://github.com/gravitational/teleport/issues/46076

Changelog: Fix a bug on Windows where a forwarded SSH agent would become dysfunctional after a single connection using the agent.

### CODE REVIEW

File: lib/sshagent/client.go [hunk 1]
```diff
@@ -0,0 +1,135 @@
...
+)
+
+// Client extends the [agent.ExtendedAgent] interface with an [io.Closer].
+type Client interface {
+	agent.ExtendedAgent
+	io.Closer
+}
+
+// ClientGetter is a function used to get a new agent client.
+type ClientGetter func() (Client, error)
```
Comment (espadolini) [inline lib/sshagent/client.go]: I don't think we care about the newtyping here.

```suggestion
type ClientGetter = func() (Client, error)
```

File: lib/sshagent/client.go [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+
+type client struct {
+	agent.ExtendedAgent
+	conn io.ReadWriteCloser
```
Comment (espadolini) [inline lib/sshagent/client.go]:
```suggestion
	conn io.Closer
```

File: lib/sshagent/client.go [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+			if err != nil {
+				continue
+			}
+
+			go ssh.DiscardRequests(reqs)
+
+			forwardAgent, err := getForwardAgent()
+			if err != nil {
+				slog.ErrorContext(ctx, "failed to connect to forwarded agent", "err", err)
+				continue
```
Comment (espadolini) [inline lib/sshagent/client.go:123]: This leaks `channel`.

```suggestion
				_ = channel.Close()
				slog.ErrorContext(ctx, "failed to connect to forwarded agent", "err", err)
				continue
```

File: lib/sshagent/clientconn_windows.go [hunk 4]
```diff
@@ -35,32 +33,43 @@ import (
...
-// environment, a connection to a Cygwin SSH agent will be attempted.
-func Dial(socket string) (net.Conn, error) {
+// DialSystemAgent connects to the SSH agent listening on a Windows named pipe.
+// If connecting to a named pipe fails and we're in a Cygwin environment, a
+// connection to the Cygwin SSH agent advertised by SSH_AUTH_SOCK will be attempted.
+//
+// This is behind a build flag because winio.DialPipe is only available on Windows.
+func DialSystemAgent() (io.ReadWriteCloser, error) {
+	logger := slog.With(teleport.ComponentKey, teleport.ComponentKeyAgent)
+	logger.DebugContext(context.Background(), "Connecting to the Windows system agent", "socket_path", namedPipe)
```
Comment (espadolini) [inline lib/sshagent/clientconn_windows.go]: This log line feels somewhat random, there's no indication of who asked for it or in which context, just the path. If we're to add logging can't we add it to the caller (presumably srv/regular)? If you want to opportunistically recover the path you can try to assert the returned RWC into an `interface { RemoteAddr() net.Addr }`.

File: lib/sshagent/clientconn_windows.go [hunk 5]
```diff
@@ -35,32 +33,43 @@ import (
...
-// Windows. If connecting to a named pipe fails and we're in a Cygwin
-// environment, a connection to a Cygwin SSH agent will be attempted.
-func Dial(socket string) (net.Conn, error) {
+// DialSystemAgent connects to the SSH agent listening on a Windows named pipe.
+// If connecting to a named pipe fails and we're in a Cygwin environment, a
+// connection to the Cygwin SSH agent advertised by SSH_AUTH_SOCK will be attempted.
+//
+// This is behind a build flag because winio.DialPipe is only available on Windows.
+func DialSystemAgent() (io.ReadWriteCloser, error) {
+	logger := slog.With(teleport.ComponentKey, teleport.ComponentKeyAgent)
```
Comment (espadolini) [inline lib/sshagent/clientconn_windows.go]: Don't use `With` if you're going to use the resulting logger only once.

File: lib/sshagent/clientconn_unix.go [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+// DialSystemAgent connects to the SSH agent advertised by SSH_AUTH_SOCK.
+func DialSystemAgent() (io.ReadWriteCloser, error) {
+	socketPath := os.Getenv(teleport.SSHAuthSock)
+
+	if socketPath == "" {
+		return nil, trace.NotFound("no system agent advertised by SSH_AUTH_SOCK")
+	}
+
+	logger := slog.With(teleport.ComponentKey, teleport.ComponentKeyAgent)
+	logger.DebugContext(context.Background(), "Connecting to the system agent", "socket_path", socketPath)
```
Comment (espadolini) [inline lib/sshagent/clientconn_unix.go]: Same comments as clientconn_windows

File: lib/sshagent/clientconn_unix.go [hunk 7]
```diff
@@ -0,0 +1,49 @@
+//go:build !windows
```
Comment (espadolini) [inline lib/sshagent/clientconn_unix.go]: Let this fail to compile on non-windows non-unix targets (but beware, `unix` is not supported as an implicit build constraint in the filename).

```suggestion
//go:build unix
```

File: lib/sshagent/client_test.go [hunk 8]
```diff
@@ -0,0 +1,125 @@
...
+	require.True(t, ok)
+
+	agentDir := t.TempDir()
+	agentPath := filepath.Join(agentDir, "agent.sock")
+	startAgentServer := func() (stop func()) {
+		l, err := net.Listen("unix", agentPath)
+		require.NoError(t, err)
+
+		// create a context to close existing connections on server shutdown.
+		serveCtx, serveCancel := context.WithCancel(context.Background())
```
Comment (rosstimothy) [inline lib/sshagent/client_test.go]: Suggestion: Prefer using t.Context() as the base context in tests
```suggestion
		serveCtx, serveCancel := context.WithCancel(t.Context())
```

File: lib/sshagent/client_test.go [hunk 9]
```diff
@@ -0,0 +1,125 @@
...
+			for {
+				conn, err := l.Accept()
+				if err != nil {
+					assert.True(t, utils.IsUseOfClosedNetworkError(err))
+					return
+				}
+
+				connCtx, cancel := context.WithCancel(serveCtx)
+				connWg.Add(1)
+				context.AfterFunc(connCtx, func() {
```
Comment (rosstimothy) [inline lib/sshagent/client_test.go]: Do we need to handle/call the stop function returned at all?

File: lib/sshagent/client.go (hunk 1 above)
Comment (Joerger) [reply lib/sshagent/client.go]: What do you mean by newtyping? I didn't realize these have a nuanced difference and can't find any information on it.

File: lib/sshagent/client_test.go (hunk 9 above)
Comment (Joerger) [reply lib/sshagent/client_test.go]: It is being handled:

```
stopServer := startAgentServer()
t.Cleanup(stopServer)
```

Are you referring to something else?

File: lib/sshagent/clientconn_windows.go (hunk 4 above)
Comment (Joerger) [reply lib/sshagent/clientconn_windows.go]: This is for the keyagent and forward agent (client side). I was primarily trying to preserve the existing logging, but I think it can afford to be trimmed down a bit.

File: lib/sshagent/client_test.go (hunk 9 above)
Comment (rosstimothy) [reply lib/sshagent/client_test.go]: https://pkg.go.dev/context#AfterFunc returns a stop function similar to how context.WithCancel returns a cancel function.

Comment (Joerger) [reply lib/sshagent/client_test.go]: Ahh right, thank you. Right now it's written in a way that the stop is not necessary, and I'm not seeing a way to incorporate it without introducing a race condition.

File: lib/sshagent/client.go (hunk 1 above)
Comment (rosstimothy) [reply lib/sshagent/client.go]: `type Foo = string` is an alias. `type Foo string` is a declaration of a new type. The alias doesn't require explicit conversion and will inherit properties from the original type, while the new type is a distinct type that requires manual conversion to the original type.

Comment (espadolini) [reply lib/sshagent/client.go]: The distinction can often slip your mind because all literal expressions and untyped consts (in the case of functions, `func(...) ... {...}`) are implicitly coerced to the appropriate type, but if there's no need for a new type and we just want a shorter name for a func type, an alias is more appropriate.

File: lib/sshagent/client_test.go (hunk 9 above)
Comment (espadolini) [reply lib/sshagent/client_test.go]: I think this is correct, the context tree gets cancelled in `stopServer` which is set up as a test cleanup, and will actively wait for the afterfunc to get called.

If you want to be super sure about what's going on you can add 2 to the wait group and call Done both in the afterfunc and in the goroutine, so the Wait in the cleanup will wait until the serving goroutine is gone.

File: lib/sshagent/client_test.go [hunk 10]
```diff
@@ -0,0 +1,125 @@
...
+		l, err := net.Listen("unix", agentPath)
+		require.NoError(t, err)
+
+		// create a context to close existing connections on server shutdown.
+		serveCtx, serveCancel := context.WithCancel(t.Context())
+
+		// Track open connections.
+		var connWg sync.WaitGroup
+
+		go func() {
```
Comment (espadolini) [inline lib/sshagent/client_test.go]: You can only call Add if you're "guarded" by an existing add or if there's no way for anyone to have called Wait yet - with the code as is you can get this sequence of events:

- `l.Accept` returns a connection in this goroutine
- `l.Close` and `serveCancel` are called in `stopServer`
-  `connWg.Add` in this goroutine is called concurrently with `connWg.Wait` in `stopServer`, which blows up

```suggestion
		var connWg sync.WaitGroup

		connWg.Add(1)
		go func() {
			defer connWg.Done()
```

**Review by espadolini — APPROVED** [review]
LGTM other than the waitgroup business in the test

File: lib/sshagent/client_test.go (hunk 9 above)
Comment (Joerger) [reply lib/sshagent/client_test.go]: I didn't realize `context.AfterFunc` returns a `func() bool` and not just a `func()`. Refactored to use the stop fn as I think that's a bit cleaner than creating an extra connection context. 793948afc22c284e78ab146d0421d87e79f695f8

**Review by rosstimothy — APPROVED** [review]
