### PR TITLE
Fix role mapping for trusted clusters

### LINKED ISSUE #3252: Leaf cluster authentication regression in role mapping
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:

Security patches post 4.2 introduced the regression - leaf cluster ignores role mapping
and attempts to use role names coming from identity of the root cluster

**What you expected to happen**:

Mapping should work as designed

**How to reproduce it (as minimally and precisely as possible)**:

* On the root cluster, create a user with roles `admin`, `dev`
* On the leaf cluster, only map `dev` role from the trusted cluster setup
* Attempt to `tsh login leaf; tsh ls`
* Get error: "role `admin` is not found", although it should not be expected to exist in the first place

**Environment**:
- Teleport version (use `teleport version`):

4.1.13+

### PR DESCRIPTION
**Pull request by klizhentas**
This commit fixes #3252

Security patches 4.2 introduced a regression - leaf clusters ignore role mapping
and attempt to use role names coming from identity of the root cluster
whenever GetNodes method was used.

This commit reverts back the logic, however it ensures that the original
fix is preserved - traits and groups are updated on the user object.

Integration test has been extended to avoid the regression in the future, also manual testing with docker compose was done to verify that issue has been fixed.

### CODE REVIEW

File: lib/services/role.go [hunk 1]
```diff
@@ -1401,7 +1400,7 @@ func isFormatOld(cert *ssh.Certificate) bool {
 	_, hasRoles := cert.Extensions[teleport.CertExtensionTeleportRoles]
 	_, hasTraits := cert.Extensions[teleport.CertExtensionTeleportTraits]
 
-	if hasRoles && hasTraits {
+	if hasRoles || hasTraits {
```
Comment (r0mant) [inline lib/services/role.go]: Just making sure you intended to change the logic here, ignore if it's on purpose.

**Review by r0mant — APPROVED** [review]

File: lib/auth/testauthority/testauthority.go [hunk 2]
```diff
@@ -110,12 +111,19 @@ func (n *Keygen) GenerateUserCert(c services.UserCertParams) ([]byte, error) {
...
+	// Add roles, traits, and route to cluster in the certificate extensions if
+	// the standard format was requested. Certificate extensions are not included
+	// legacy SSH certificates due to a bug in OpenSSH <= OpenSSH 7.1:
+	// https://bugzilla.mindrot.org/show_bug.cgi?id=2387
+	if c.CertificateFormat == teleport.CertificateFormatStandard {
+		traits, err := wrappers.MarshalTraits(&c.Traits)
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
+		if len(traits) > 0 {
```
Comment (fspmarshall) [inline lib/auth/testauthority/testauthority.go]: Pretty sure this is always `true` since `traits` is going to marshall to `{}` or `null` when empty.

**Review by fspmarshall — APPROVED** [review]

**Review by russjones — APPROVED** [review]

File: lib/auth/testauthority/testauthority.go (hunk 2 above)
Comment (russjones) [reply lib/auth/testauthority/testauthority.go]: What about this? Same for `lib/auth/native.go`.

```go
if len(c.Traits) > 0 {
    traits, err := wrappers.MarshalTraits(&c.Traits)
    if err != nil {
      return nil, trace.Wrap(err)
    }
    cert.Permissions.Extensions[teleport.CertExtensionTeleportTraits] = string(traits)
}

File: lib/services/role.go (hunk 1 above)
Comment (klizhentas) [reply lib/services/role.go]: on purpose

File: lib/auth/testauthority/testauthority.go (hunk 2 above)
Comment (klizhentas) [reply lib/auth/testauthority/testauthority.go]: the traits were omitted in my tests

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

File: lib/auth/testauthority/testauthority.go (hunk 2 above)
Comment (fspmarshall) [reply lib/auth/testauthority/testauthority.go]: Just wrote a manual test, and `MarshalTraits` always returned either `{}` or `null` depending on whether the `*wrappers.Traits` value was empty or `nil`... :confused: 

Did your tests verify that the cert extension was actually omitted, or just that no traits were present in the decoded identity?

**Comment by klizhentas** [comment]
retest this please
