### PR TITLE
aws oidc skip aurora clusters without instances

### LINKED ISSUE #47197: RDS Discover flow error `database cluster <db-cluster> has no instance`
Expected behavior:
Aurora clusters with zero instances should be skipped

Current behavior:
`database fetch error: database cluster <db-cluster> has no instance` is returned while listing databases preventing the flow.
https://github.com/gravitational/teleport/blob/7a6dbcbafa6ed260fabb83c59894648ea6f361b9/lib/integrations/awsoidc/listdatabases.go#L224-L237

Bug details:
- Teleport version: v16
- Recreation steps: Create a Aurora cluster. Delete the instances without deleting the cluster.
- Debug logs:

`aws rds describe-db-clusters --region us-west-1 --db-cluster-identifier <db-cluster-id>` shows empty `"DBClusterMembers": [],`
`aws rds describe-db-instances --region us-west-1 --filters Name=db-cluster-id,Values=<db-cluster-id>` is also empty

### PR DESCRIPTION
**Pull request by GavinFrazar**
Changelog: Fixed an issue that prevented RDS Aurora discovery configuration in the AWS OIDC enrollment wizard when any cluster existed without member instances.

Closes #47197
- #47197

Instead of returning an error, just skip the cluster(s) that have no instances.

If any cluster in a region/vpc had no member instances, then the enrollment wizard would fail to list all of the aurora clusters in that region/vpc. Now it lists the ones that have member instances instead of giving up.

I verified that this fix works in a manual test as well by deploying to my cloud staging tenant.

### CODE REVIEW

File: lib/integrations/awsoidc/listdatabases.go [hunk 1]
```diff
@@ -233,7 +234,8 @@ func listDBClusters(ctx context.Context, clt ListDatabasesClient, req ListDataba
 		// All the members have the same network information, so picking one at random should not matter.
 		clusterInstance, err := fetchSingleRDSDBInstance(ctx, clt, req, aws.ToString(db.DBClusterIdentifier))
 		if err != nil {
-			return nil, trace.Wrap(err)
+			log.DebugContext(ctx, "Failed to fetch RDS instance", "error", err)
```
Comment (marcoandredinis) [inline lib/integrations/awsoidc/listdatabases.go:237]: Should we only log/continue when we know the error was `instance not found`? 
Can we also include the RDS identifier here?
```suggestion
			log.InfoContext(ctx, "Skipping RDS Cluster because it has no instances.", "rds_dbclusterid", db.DBClusterIdentifier, "error", err)
```

**Review by marcoandredinis — APPROVED** [review]

File: lib/integrations/awsoidc/listdatabases.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/integrations/awsoidc/listdatabases.go]: > Should we only log/continue when we know the error was instance not found?
> Can we also include the RDS identifier here?

yeah I think these are both good points.

Updated to only skip when it's not found, and changed to info level log: [diff](https://github.com/gravitational/teleport/compare/64e12dfd43c04846ca43b6c5786299d3f68b3790..22b232f3b1626217844e070cb22f7f4fc927c2bc)

**Review by probakowski — APPROVED** [review]
