### PR TITLE
fix: tolerate mismatched key PEM headers

### LINKED ISSUE #46710: SAML connector no longer gracefully handles PKCS8 `assertion_key_pair` in `RSA PRIVATE KEY` PEM block
Prior to https://github.com/gravitational/teleport/pull/43381, we would gracefully handle cases where a PKCS8 encoded private key was within a `RSA PRIVATE KEY` (which usually indicates PKCS1) PEM block.

After this PR, the following error will be encountered

```
 failed to parse certificate or private key defined in assertion_key_pair\n\tx509: failed to parse private key (use ParsePKCS8PrivateKey instead for this key format)
```

We probably ought to re-instate the old retry behaviour as this could cause customers to be locked out of their clusters upon an upgrade.

As to why a PKCS8 key is inside what is usually the PKCS1 header, I'm unsure. Some threads across the internet seem to suggest that this was potentially a bug/behaviour of the `openssl` CLI for some time (https://superuser.com/questions/606215/openssl-pkcs8-default-format-gives-rsa-private-key)

Workaround:
- Replace `RSA PRIVATE KEY` in `assertion_key_pair` PEM header with `PRIVATE KEY`

### PR DESCRIPTION
**Pull request by nklaassen**
Issue #43381 introduced a regression where we now fail to parse PKCS8 encoded RSA private keys within an "RSA PRIVATE KEY" PEM block in some cases. This format is somewhat non-standard, usually PKCS8 data should be in a "PRIVATE KEY" PEM block. However, certain versions of OpenSSL and possibly even Teleport in specific cases have generated private keys in this format.

This commit updates ParsePrivateKey and ParsePublicKey to be more tolerant of PKCS8, PKCS1, or PKIX key data no matter which PEM header is used.

Fixes #46710

changelog: fixed regression in private key parser to handle mismatched PEM headers

### CODE REVIEW

File: api/utils/keys/privatekey.go [hunk 1]
```diff
@@ -258,12 +239,35 @@ func ParsePrivateKey(keyPEM []byte) (*PrivateKey, error) {
 			cryptoSigner = *pEdwards
 		}
 		return NewPrivateKey(cryptoSigner, keyPEM)
-	case pivYubiKeyPrivateKeyType:
-		priv, err := parseYubiKeyPrivateKeyData(block.Bytes)
-		if err != nil {
-			return nil, trace.Wrap(err, "failed to parse YubiKey private key")
+	case PKCS1PrivateKeyType, PKCS8PrivateKeyType, ECPrivateKeyType:
+		// The DER format doesn't always exactly match the PEM header, various
+		// versions of Teleport and OpenSSH have been guilty of writing PKCS#8
```
Comment (espadolini) [inline api/utils/keys/privatekey.go:244]: ?
```suggestion
		// versions of Teleport and OpenSSL have been guilty of writing PKCS#8
```

**Review by espadolini — APPROVED** [review]

**Review by avatus — APPROVED** [review]
