### PR TITLE
Web UI disconnects

### LINKED ISSUE #5265: Sporadic disconnects when using web UI
### Description

**What happened**:
Sometimes (especially with multiple interactive sessions open), sessions disconnect on their own.

**What you expected to happen**:
The session(s) should stay active until explicitly disconnected from or the configured expiration time is reached.

**How to reproduce it (as minimally and precisely as possible)**:
Log into web UI. Open multiple SSH sessions. After a random amount of time, the session will automatically disconnect for no reason.

### Environment
- Teleport version (use `teleport version`): 4.x, 5.x

### PR DESCRIPTION
**Pull request by a-palchikov**
This PR fixes an issue with web UI sessions sporadically disconnecting.

In the scenario with multiple proxy instances running behind a load balancer (e.g. a kubernetes service)
the web session contexts (i.e. the scope of a single logged in user) were stored in memory in the corresponding proxy process upon creation. This also included open terminal handles. If the web session renewal request came to another proxy as the one that previously created the session, the session was renewed out-of-band. Once the internal cache clean up loop running inside of each proxy instance detected the expired session, it could release the resources associated with the previous session and forcefully close the terminals.
Additionally, a client holding to the old bearer token (until is has gotten the update) after the session has been renewed, might access the API using the expired token leading to the access denied error that would trigger the logout.

Now, the following counter measures were introduced:
  1. Renewing a session does not release any resources that were created when the initial session was created. This is implemented by persisting the resources on the user instead of the session level.
  1. Bearer tokens are not explicitly removed upon session renewal but are instead let to linger and expire naturally minimizing the chances of a "late" client

A new web token resource type is introduced and both web sessions and web tokens are made available in the cache layer to make validation logic cheaper.
As web sessions and web tokens (used as bearer tokens in this context) are two separate resources, independent lifecycle management is possible.
To simplify the implementation, web sessions are still constructed together with bearer tokens - e.g. a web session value
is used as a container for the initial bearer token. Once propagated to a client, bearer tokens are queried separately from web sessions and have independent expiration times.
To be able to cache the values of the new types, I chose a simpler backend storage story: instead of keeping the sessions under the user:
```
  /web/users/<user>/sessions/<id>
```
the sessions were moved up into its own namespace:
```
  /web/sessions/<id>
```
The same is with the new web tokens resource:
```
  /web/tokens/<id>
```
althoguh both resources are still bound to a user.
Apart from simpler implementation there was an issue I saw with the caching layer that does not have ordering guarantees in the way it handles refreshes - e.g. it seemed possible that had I kept the sessions/tokens under the user, the cache could invalidate the sessions/tokens before doing so for users and the users update would remove all sessions/tokens data due to the nesting in the backend - I'm open to suggestions here though.

No changes to base behavior were introduced:
 1. Bearer tokens are created with a fixed TTL (auth.BearerTokenTTL)
 1. Sessions have a top-level expiration but are capped at bearer token's TTL and are periodically renewed

A note on backwards-compatibility: since the data was moved to an alternative path in the backend, provisions were made to still read the data in the old path if not available in the new path.

The prominent changes:
  [lib/web/sessions.go](https://github.com/gravitational/teleport/compare/dmitri/web-ui-disconnects#diff-7e877d49db0989e2f62f90da78aa9a7ce5b3c665ea94f63a74d97c2ba34623ee)
  [lib/web/apiserver.go](https://github.com/gravitational/teleport/compare/dmitri/web-ui-disconnects#diff-5a12dd7747d28af8fe5043638cc11f31a3314b2a23f3e23fe0bcdc952a805fa6)
  [lib/cache/cache.go](https://github.com/gravitational/teleport/compare/dmitri/web-ui-disconnects#diff-3e237f973a30f7092dc18a706ecd95d8a7e1d99c5c50626b8bb0e7ac6cb7efd1)
  [lib/cache/collections.go](https://github.com/gravitational/teleport/compare/dmitri/web-ui-disconnects#diff-cb7927b8cb36bb63bc941389c91c41c50c69d81f892361c9f8ce939092e105fb)

Fixes https://github.com/gravitational/teleport/issues/5265

### CODE REVIEW

File: api/types/session.go [hunk 1]
```diff
@@ -84,6 +82,8 @@ func NewWebSession(name string, kind string, subkind string, spec WebSessionSpec
 		},
 		Spec: spec,
 	}
+	session.Metadata.SetExpiry(spec.Expires)
```
Comment (a-palchikov) [inline api/types/session.go:85]: I believe I misinterpreted `Metadata.Expires` and `Session.Spec.Expires`. Metadata.Expires is meant as a resource expiry in backend context while `Spec.Expires` declares the general expiration and these might differ - I'll update.

Comment (a-palchikov) [reply api/types/session.go:85]: No, I believe this is a correct assumption. I have not found a counter argument in the current code base and it seems that other resources (i.e. semaphores) default to the same behavior.

File: lib/services/identity.go [hunk 2]
```diff
@@ -246,6 +248,54 @@ type AppSession interface {
...
+// WebTokensGetter provides access to web tokens
+type WebTokensGetter interface {
+	// WebTokens returns the tokens manager
+	WebTokens() WebTokenInterface
+}
+
+// WebTokenInterface defines interface for managing web tokens
+type WebTokenInterface interface {
+	// Get returns a token specified by the request.
+	Get(ctx context.Context, req types.GetWebTokenRequest) (types.WebToken, error)
```
Comment (r0mant) [inline lib/services/identity.go:260]: IMHO the generic names of the methods in this interface and `WebSessionInterface` below make it unfriendly to embedding since the names will clash. All other interfaces I think call them like `GetWebToken`, `DeleteAllWebTokens`, etc. Have you considered doing the same?

I see you have respective `XXXGetter` interfaces likely for this reason, maybe they also won't be needed if you just named the methods with "full" names? Unless I'm missing something.

File: lib/services/local/session.go [hunk 3]
```diff
@@ -95,3 +97,249 @@ func (s *IdentityService) DeleteAllAppSessions(ctx context.Context) error {
 	}
 	return nil
 }
+
+// GetWebSession returns a web session state for the given user and session id
+func (s *IdentityService) GetWebSession(user, sessionID string) (services.WebSession, error) {
```
Comment (r0mant) [inline lib/services/local/session.go:102]: Nit: Since you're refactoring all these methods anyway, might be a good excuse to enhance them to accept contexts? Feel free to disregard if that's too much work / out of scope.

File: lib/services/local/session.go [hunk 4]
```diff
@@ -95,3 +97,249 @@ func (s *IdentityService) DeleteAllAppSessions(ctx context.Context) error {
...
+// Get returns the web session state described with req.
+func (r *webSessions) Get(ctx context.Context, req types.GetWebSessionRequest) (services.WebSession, error) {
+	if err := req.Check(); err != nil {
+		return nil, trace.Wrap(err)
+	}
+	item, err := r.backend.Get(ctx, webSessionKey(req.SessionID))
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+	session, err := services.GetWebSessionMarshaler().UnmarshalWebSession(item.Value, services.SkipValidation())
```
Comment (r0mant) [inline lib/services/local/session.go:138]: I'd just start importing from `types` instead of `services` in the new code to simplify future refactoring.

File: lib/services/local/session.go [hunk 5]
```diff
@@ -95,3 +97,249 @@ func (s *IdentityService) DeleteAllAppSessions(ctx context.Context) error {
...
+	}
+	// this is for backwards compatibility to ensure we
+	// always have these values
+	session.SetUser(user)
+	session.SetName(sessionID)
+	return session, nil
+}
+
+func webSessionKey(sessionID string) (key []byte) {
+	return backend.Key(webPrefix, sessionsPrefix, sessionID)
```
Comment (r0mant) [inline lib/services/local/session.go:336]: So with this change to store all sessions under the same key now, would it still be possible, for example, to implement features like "remove all sessions for a particular user" if we wanted? It'd just require iterating over all sessions?

File: lib/services/local/session.go [hunk 6]
```diff
@@ -95,3 +97,249 @@ func (s *IdentityService) DeleteAllAppSessions(ctx context.Context) error {
...
+func (r *webSessions) Upsert(ctx context.Context, session services.WebSession) error {
+	value, err := services.GetWebSessionMarshaler().MarshalWebSession(session)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	sessionMetadata := session.GetMetadata()
+	item := backend.Item{
+		Key:     webSessionKey(session.GetName()),
+		Value:   value,
+		Expires: backend.EarliestExpiry(session.GetBearerTokenExpiryTime(), sessionMetadata.Expiry()),
```
Comment (r0mant) [inline lib/services/local/session.go:183]: Nit: Doesn't resource already have `GetExpiryTime()` method, so you prob. don't need to extract metadata first?

File: lib/web/sessions.go [hunk 7]
```diff
@@ -342,19 +393,26 @@ func newSessionCache(config *sessionCache) (*sessionCache, error) {
...
 	cipherSuites []uint16
+
+	mu sync.Mutex
+	// sessions maps user/sessionID to an active web session.
+	// This is the client-facing session handle
+	sessions map[string]*SessionContext
+	// contexts maps user to an active user web session.
+	// These are used to maintain session state that would otherwise
+	// not survive renewal of the session
+	contexts map[string]*sessionContext
```
Comment (r0mant) [inline lib/web/sessions.go:415]: Sorry just looking at this is a little confusing - why are there two "session context" structs, one exported and one not, and what's the difference b/w them? And the fact that one field is called "sessions" and another one "contexts" is also a bit confusing.

File: lib/web/sessions.go [hunk 8]
```diff
@@ -497,148 +552,337 @@ func (s *sessionCache) ValidateTrustedCluster(validateRequest *auth.ValidateTrus
...
+		user, sessionID)
 }
 
-func (s *sessionCache) insertContext(user, sid string, ctx *SessionContext, ttl time.Duration) (*SessionContext, error) {
-	s.Lock()
-	defer s.Unlock()
+func (s *sessionCache) insertContext(user string, ctx *SessionContext) (exists bool) {
+	s.mu.Lock()
+	defer s.mu.Unlock()
+	id := user + ctx.session.GetName()
```
Comment (r0mant) [inline lib/web/sessions.go:603]: I'd consider making a function, `makeKey` or something, that implements this concatenation logic since it's used in a few places.

File: lib/web/sessions.go [hunk 9]
```diff
@@ -497,148 +552,337 @@ func (s *sessionCache) ValidateTrustedCluster(validateRequest *auth.ValidateTrus
...
 
-	ttl := utils.ToTTL(s.clock, sess.GetBearerTokenExpiryTime())
-	out, err := s.insertContext(user, sid, c, ttl)
-	if err != nil {
-		// this means that someone has just inserted the context, so
-		// close our extra context and return
-		if trace.IsAlreadyExists(err) {
-			defer c.Close()
-			return out, nil
+func (c *sessionContext) Close() error {
```
Comment (r0mant) [inline lib/web/sessions.go:761]: Nit: Add godoc.

File: lib/web/sessions.go [hunk 10]
```diff
@@ -497,148 +552,337 @@ func (s *sessionCache) ValidateTrustedCluster(validateRequest *auth.ValidateTrus
...
+	closers := c.transferClosers()
+	for _, closer := range closers {
+		c.log.Debugf("Closing %v.", closer)
+		closer.Close()
```
Comment (r0mant) [inline lib/web/sessions.go:765]: Doesn't this method also return an error?

File: lib/web/sessions.go [hunk 11]
```diff
@@ -497,148 +552,337 @@ func (s *sessionCache) ValidateTrustedCluster(validateRequest *auth.ValidateTrus
...
 
-func (s *sessionCache) ClearSession(w http.ResponseWriter) {
-	http.SetCookie(w, &http.Cookie{
-		Name:     "session",
-		Value:    "",
-		Path:     "/",
-		HttpOnly: true,
-		Secure:   true,
-	})
+func waitForResource(ctx context.Context, watcher services.Watcher, m eventMatcher, clock clockwork.Clock) (services.Resource, error) {
```
Comment (r0mant) [inline lib/web/sessions.go:845]: This feels like it doesn't really belong in the web package TBH, maybe move this somewhere to services closer to the `Watcher`, along with `eventMatcher`?

File: api/types/types.proto [hunk 12]
```diff
@@ -1351,3 +1351,66 @@ message KubernetesCluster {
...
+// DeleteWebSessionRequest describes a request to delete a web session
+message DeleteWebSessionRequest {
+    // User specifies the user the session is bound to
+    string User = 1 [ (gogoproto.jsontag) = "user" ];
+    // SessionID specifies the web session ID to delete.
+    string SessionID = 2 [ (gogoproto.jsontag) = "session_id" ];
+}
+
+// WebTokenV1 describes a web token
+message WebTokenV1 {
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/types/types.proto:1372]: Ok, was wondering myself. Will update.

File: api/client/proto/authservice.proto [hunk 13]
```diff
@@ -477,6 +507,24 @@ service AuthService {
     // DeleteAllAppSessions removes all application web sessions.
     rpc DeleteAllAppSessions(google.protobuf.Empty) returns (google.protobuf.Empty);
 
+    // GetWebSession gets a web session.
+    rpc GetWebSession(types.GetWebSessionRequest) returns (GetWebSessionResponse);
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/client/proto/authservice.proto:511]: The reasoning is that the request is not gRPC-specific whilte the response is.

File: api/defaults/defaults.go [hunk 14]
```diff
@@ -42,9 +42,12 @@ const (
 	// disconnected. The max count mirrors ClientAliveCountMax of sshd.
 	KeepAliveCountMax = 3
 
-	// MaxCertDuration limits maximum duration of validity of issued cert
+	// MaxCertDuration limits maximum duration of validity of issued certificate
 	MaxCertDuration = 30 * time.Hour
 
+	// CertDuration is a default certificate duration.
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/defaults/defaults.go:48]: Hmm, good question - I'll see if I can find out from history.

File: api/types/events.go [hunk 15]
```diff
@@ -18,10 +18,19 @@ package types
...
 import (
 	"context"
+	"fmt"
 
 	"github.com/gravitational/trace"
 )
 
+// String returns text description of this event
+func (r Event) String() string {
+	if r.Type == OpDelete {
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/types/events.go:28]: It's actually about a slightly different thing - the events for a deleted resource include only the header in `Resource` and formatting it with `fmt.SprintX` panics.

File: api/types/session.go [hunk 16]
```diff
@@ -412,3 +408,274 @@ func GetWebSessionMarshaler() WebSessionMarshaler {
...
+}
+
+// SetExpiry sets the token absolute expiration time
+func (r *WebTokenV1) SetExpiry(t time.Time) {
+	r.Spec.Expires = t
+}
+
+// CheckAndSetDefaults validates this token value and sets defaults
+func (r *WebTokenV1) CheckAndSetDefaults() error {
+	return r.Metadata.CheckAndSetDefaults()
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/types/session.go:549]: Yes - will update.

File: lib/cache/cache.go [hunk 17]
```diff
@@ -57,7 +58,9 @@ func ForAuth(cfg Config) Config {
 		{Kind: services.KindTunnelConnection},
 		{Kind: services.KindAccessRequest},
 		{Kind: services.KindAppServer},
-		{Kind: services.KindWebSession},
+		{Kind: services.KindWebSession, SubKind: services.KindAppSession},
+		{Kind: services.KindWebSession, SubKind: services.KindWebSession},
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply lib/cache/cache.go:62]: Yes, it's a bit complicated.
The app sessions already used the subkind but enjoyed the status of being the only web session in the caching layer hence the caching layer did not originally require any modifications. Also, I see a legit need to support resources with a subkind in cache hence I went forward with extending it to support that.

File: lib/services/identity.go (hunk 2 above)
Comment (a-palchikov) [reply lib/services/identity.go:260]: I still have a case when I need to support a couple of legacy APIs and I honestly did not want to come up with yet another prefixed or suffixed alternatives which required a different set of parameters. Also, I feel strongly against the flat namespace and I liked the direction that the kubernetes client took with its [Clientset](https://github.com/kubernetes/client-go/blob/c7a570ddfedd593495d663befa0f94bd127eac66/kubernetes/clientset.go#L70) and, for example, [CoreV1](https://github.com/kubernetes/client-go/blob/c7a570ddfedd593495d663befa0f94bd127eac66/kubernetes/typed/core/v1/core_client.go#L27) hence I made a small step towards the same thing here - using wrapper values with a well-defined set of APIs for all resources and differentiating them at the API entry with a corresponding getter.

The original layout is also unfriendly to versioning and this will eventually surface as an issue we'll need to solve.

File: lib/services/local/session.go (hunk 3 above)
Comment (a-palchikov) [reply lib/services/local/session.go:102]: I'd consider this out of scope for now due to the amount of additional changes. Will revisit in the future.

File: lib/services/local/session.go (hunk 5 above)
Comment (a-palchikov) [reply lib/services/local/session.go:336]: Yes, the downside is that it requires to iterate over all values in order to remove session only for a specific user. As the web/app sessions (and tokens) are explicitly expired, this is not such a big deal but might need to be fixed nonetheless at some point.

File: lib/services/local/session.go (hunk 6 above)
Comment (a-palchikov) [reply lib/services/local/session.go:183]: I kept the original behavior as much as possible where the `Metadata.Expires` is used as a resource expiration timestamp both ways. Although in case of web sessions the Spec.Expires is sort of redundant b/c of that. I'm on the fence but would probably be keen on keeping the redundancy.

File: lib/web/sessions.go (hunk 7 above)
Comment (a-palchikov) [reply lib/web/sessions.go:415]: It is - I'll update to reflect the actual purpose of the unexpected context.

File: api/client/proto/authservice.proto (hunk 13 above)
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/client/proto/authservice.proto]: Moved them to the proto package.

File: lib/auth/clt.go [hunk 18]
```diff
@@ -2117,6 +2118,15 @@ func (c *Client) CreateAuditStream(ctx context.Context, sid session.ID) (events.
...
 // WebService implements features used by Web UI clients
 type WebService interface {
+	// WebUIService implements web session support for UI clients
+	WebUIService
+
+	// AppSession defines application session features.
+	services.AppSession
+}
+
+// WebUIService implements features used by Web UI clients
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply lib/auth/clt.go]: Removed one of them - was no longer necessary to split.

File: lib/services/local/events.go [hunk 19]
```diff
@@ -832,6 +887,72 @@ func resourceHeader(event backend.Event, kind, version string, offset int) (serv
...
+		return nil, trace.ConnectionProblem(watcher.Error(), "watcher is closed")
+	case <-tick.Chan():
+		return nil, trace.LimitExceeded("timed out waiting for initialize event")
+	}
+
+	for {
+		select {
+		case event := <-watcher.Events():
+			res, err := m.Match(event)
+			if err == nil {
```
Comment (r0mant) [inline lib/services/local/events.go:927]: What if `err != nil`?

File: lib/web/apps.go [hunk 20]
```diff
@@ -174,18 +175,20 @@ func (h *Handler) createAppSession(w http.ResponseWriter, r *http.Request, p htt
...
-// waitForSession will block until the requested session shows up in the
+// waitForAppSession will block until the requested application session shows up in the
 // cache or a timeout occurs.
-func (h *Handler) waitForSession(ctx context.Context, sessionID string) error {
-	timeout := time.NewTimer(defaults.WebHeadersTimeout)
-	defer timeout.Stop()
-
+func (h *Handler) waitForAppSession(ctx context.Context, sessionID string) error {
+	_, err := h.cfg.AccessPoint.GetAppSession(ctx, services.GetAppSessionRequest{SessionID: sessionID})
+	if err == nil {
```
Comment (r0mant) [inline lib/web/apps.go:182]: Handle error other than not found?

File: lib/web/apps.go [hunk 21]
```diff
@@ -194,48 +197,22 @@ func (h *Handler) waitForSession(ctx context.Context, sessionID string) error {
...
 	defer watcher.Close()
-
-	select {
-	// Received an event, first event should always be an initialize event.
-	case event := <-watcher.Events():
-		if event.Type != backend.OpInit {
-			return trace.BadParameter("expected init event, got %v instead", event.Type)
+	matchEvent := func(event services.Event) (services.Resource, error) {
+		if event.Type == backend.OpPut &&
+			event.Resource.GetKind() == services.KindWebSession &&
```
Comment (r0mant) [inline lib/web/apps.go:202]: Should this also check the subkind?

File: lib/web/sessions.go [hunk 22]
```diff
@@ -282,55 +280,107 @@ func (c *SessionContext) GetAgent() (agent.Agent, *ssh.Certificate, error) {
...
+		return false
+	}
+	// Give the session some time to linger so existing users of the context
+	// have successfully disposed of them.
+	// If we remove the session immediately, a stale copy might still use the
+	// cached site clients.
+	// This is a cheaper way to avoid race without introducing object
+	// reference counters.
+	// TODO(dmitri): this leaks the implementation detail about the session TTL
+	return c.parent.clock.Since(expiry) > 2*auth.BearerTokenTTL
```
Comment (r0mant) [inline lib/web/sessions.go:357]: Maybe I'm reading this incorrectly, but doesn't this basically extend the session TTL by 3 times? It allows the session to linger for 20 minutes after expiration. Is this not going to be a security concern?

File: lib/web/sessions.go [hunk 23]
```diff
@@ -497,148 +555,302 @@ func (s *sessionCache) ValidateTrustedCluster(validateRequest *auth.ValidateTrus
...
+		},
+		MetricComponent: teleport.ComponentWebProxy,
 	})
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	defer watcher.Close()
+	matchEvent := func(event services.Event) (services.Resource, error) {
+		if event.Type == backend.OpPut &&
+			event.Resource.GetKind() == services.KindWebSession &&
```
Comment (r0mant) [inline lib/web/sessions.go:845]: Check subkind or that would be redundant?

**Review by r0mant — APPROVED** [review]
Code lgtm, I'd get a 2nd pair of eyes on the session/token management changes.

File: api/client/proto/proto.go [hunk 24]
```diff
@@ -0,0 +1,85 @@
...
+		SubKind:     wk.SubKind,
+		LoadSecrets: wk.LoadSecrets,
+		Filter:      wk.Filter,
+	}
+}
+
+// Check validates the request.
+func (r *GetWebSessionRequest) Check() error {
+	if r.User == "" {
+		return trace.BadParameter("user name missing")
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/client/proto/proto.go:52]: Wholeheartedly agree for the consistency in these messages. Just need to settle on the form.

File: lib/web/sessions.go (hunk 22 above)
Comment (a-palchikov) [reply lib/web/sessions.go:357]: This test is only for the proxy's internal memory cache - it does not affect expiration of the actual sessions in the backend. As given in the comment, it is the attempt to provide cheap protection against a client accessing served SessionContexts (which have cluster client caches) while the context is removed in parallel. The hope is that SessionContext instance should goes out of scope sooner than the double of the TTL.

File: lib/web/sessions.go (hunk 23 above)
Comment (a-palchikov) [reply lib/web/sessions.go:845]: I'll add the subkind although the IDs should be unique between (even types of) sessions.

File: lib/web/apps.go (hunk 20 above)
Comment (a-palchikov) [reply lib/web/apps.go:182]: I've added the log message similar to web session wait.

File: lib/services/local/events.go (hunk 19 above)
Comment (a-palchikov) [reply lib/services/local/events.go:927]: I'll log the error in that case.

**Review by alex-kovoy — APPROVED** [review]

File: api/types/session.go [hunk 25]
```diff
@@ -413,3 +411,245 @@ func GetWebSessionMarshaler() WebSessionMarshaler {
...
+	token := &WebTokenV3{
+		Kind:    KindWebToken,
+		Version: V3,
+		Metadata: Metadata{
+			Name:      spec.Token,
+			Namespace: defaults.Namespace,
+		},
+		Spec: spec,
+	}
+	token.Metadata.SetExpiry(spec.Expires)
```
Comment (awly) [inline api/types/session.go:426]: nit: can you set Expiry in the literal above?

File: api/types/types.proto [hunk 26]
```diff
@@ -1415,3 +1415,37 @@ message KubernetesCluster {
...
+    // User specifies the user the token is bound to.
+    string User = 1 [ (gogoproto.jsontag) = "user" ];
+    // Token specifies the token's value.
+    string Token = 2 [ (gogoproto.jsontag) = "token" ];
+    // Expires specifies the token's expiration time.
+    google.protobuf.Timestamp Expires = 3 [
+        (gogoproto.stdtime) = true,
+        (gogoproto.nullable) = false,
+        (gogoproto.jsontag) = "expires"
+    ];
```
Comment (awly) [inline api/types/types.proto:1450]: there's already an `Expires` field in `Metadata`, remove this

File: lib/services/local/events.go [hunk 27]
```diff
@@ -832,6 +887,75 @@ func resourceHeader(event backend.Event, kind, version string, offset int) (serv
...
+		Metadata: services.Metadata{
+			Name:      string(name),
+			Namespace: defaults.Namespace,
+		},
+	}, nil
+}
+
+// WaitForEvent waits for the event matched by the specified event matcher in the given watcher.
+func WaitForEvent(ctx context.Context, watcher services.Watcher, m EventMatcher, clock clockwork.Clock) (services.Resource, error) {
+	tick := clock.NewTicker(defaults.WebHeadersTimeout)
```
Comment (awly) [inline lib/services/local/events.go:908]: nit: you probably want `NewTimer`

File: lib/services/local/session.go [hunk 28]
```diff
@@ -95,3 +98,249 @@ func (s *IdentityService) DeleteAllAppSessions(ctx context.Context) error {
 	}
 	return nil
 }
+
+// GetWebSession returns a web session state for the given user and session id
+func (s *IdentityService) GetWebSession(user, sessionID string) (types.WebSession, error) {
```
Comment (awly) [inline lib/services/local/session.go:103]: here and below, can you take the context as an argument?

File: lib/services/local/session.go [hunk 29]
```diff
@@ -95,3 +98,249 @@ func (s *IdentityService) DeleteAllAppSessions(ctx context.Context) error {
...
+	return s.WebSessions().Get(context.TODO(), proto.GetWebSessionRequest{
+		User:      user,
+		SessionID: sessionID,
+	})
+}
+
+// UpsertWebSession updates or inserts a web session for the user and the session ID
+func (s *IdentityService) UpsertWebSession(user, sessionID string, session types.WebSession) error {
+	session.SetUser(user)
+	session.SetName(sessionID)
```
Comment (awly) [inline lib/services/local/session.go:113]: shouldn't the caller populate the session fields?

File: lib/services/local/session.go [hunk 30]
```diff
@@ -95,3 +98,249 @@ func (s *IdentityService) DeleteAllAppSessions(ctx context.Context) error {
 	}
 	return nil
 }
+
+// GetWebSession returns a web session state for the given user and session id
+func (s *IdentityService) GetWebSession(user, sessionID string) (types.WebSession, error) {
+	return s.WebSessions().Get(context.TODO(), proto.GetWebSessionRequest{
```
Comment (awly) [inline lib/services/local/session.go:104]: nit: trace.Wrap

File: lib/services/local/session.go [hunk 31]
```diff
@@ -95,3 +98,249 @@ func (s *IdentityService) DeleteAllAppSessions(ctx context.Context) error {
...
+		User:      user,
+		SessionID: sessionID,
+	})
+}
+
+// UpsertWebSession updates or inserts a web session for the user and the session ID
+func (s *IdentityService) UpsertWebSession(user, sessionID string, session types.WebSession) error {
+	session.SetUser(user)
+	session.SetName(sessionID)
+	return s.WebSessions().Upsert(context.TODO(), session)
```
Comment (awly) [inline lib/services/local/session.go:114]: nit: trace.Wrap

File: lib/web/apiserver_test.go [hunk 32]
```diff
@@ -606,8 +607,15 @@ func (s *WebSuite) TestPasswordChange(c *C) {
 }
 
 func (s *WebSuite) TestWebSessionsRenew(c *C) {
```
Comment (awly) [inline lib/web/apiserver_test.go:609]: optional: rewrite this test following https://github.com/gravitational/teleport/blob/master/rfd/0001-testing-guidelines.md if you have the time

**Review by awly — COMMENTED** [review]
ugh, github butchered some of these diffs...

File: lib/services/local/events.go (hunk 27 above)
Comment (a-palchikov) [reply lib/services/local/events.go:908]: Unfortunately  there's no timer support in clockwork.

File: api/client/proto/proto.go [hunk 33]
```diff
@@ -0,0 +1,85 @@
...
+// and the internal format
+func ToWatchKind(wk WatchKind) types.WatchKind {
+	return types.WatchKind{
+		Name:        wk.Name,
+		Kind:        wk.Kind,
+		SubKind:     wk.SubKind,
+		LoadSecrets: wk.LoadSecrets,
+		Filter:      wk.Filter,
+	}
+}
```
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/client/proto/proto.go:47]: This is good question. I've had a similar concern with @Joerger api refactoring [PR](https://github.com/gravitational/teleport/pull/5384#discussion_r564455486) - the stand there is that the api client needs to manage a separate set of types unrelated to protobuf to avoid leaking implementation details about internal use of gRPC which I have trouble justifying.
If, on the hand, the request types were to be removed from the protobuf side, it would look equally strange. So some consensus is required.

File: lib/services/local/session.go (hunk 29 above)
Comment (a-palchikov) [reply lib/services/local/session.go:113]: This is from my attempt to keep the old APIs for whatever reason. I now believe I can remove these as well.

File: api/client/sessions.go [hunk 34]
```diff
@@ -0,0 +1,152 @@
...
+*/
+
+package client
+
+import (
+	"context"
+
+	"github.com/gravitational/teleport/api/client/proto"
+	"github.com/gravitational/teleport/api/types"
+	"github.com/gravitational/teleport/lib/services"
```
Comment (Joerger) [inline api/client/sessions.go:24]: `lib/services` can't be imported here because it brings a ton of dependencies into `api` that we don't want. I can help refactor WebSessions to solve this.

File: api/client/proto/proto.go (hunk 33 above)
[the remark this answers is not in the document]
Comment (Joerger) [reply api/client/proto/proto.go:47]: The way we deduplicate this currently is to define the type in `api/types/types.proto`. You can then add methods in `types/sessions.go`, and import the types into `authservice.proto`. You can look at types like `types.CertAuthorityV2` for an example of that. 

But the problem here is that WatchKind is defined in `authservice.proto`. It should probably be deprecated and moved to `types.proto` to solve this issue. This is also an issue with `Events` and `Duration` which should likewise be refactored eventually.

File: lib/web/apiserver_test.go (hunk 32 above)
Comment (a-palchikov) [reply lib/web/apiserver_test.go]: Done although it turned into a bit more changes than anticipated: https://github.com/gravitational/teleport/pull/5276/commits/308177f1d15865a52ccec7b6452c3171cae05228 and https://github.com/gravitational/teleport/pull/5276/commits/4ba1f5396aaf467da1b1ad39f96cf4d633aed366

**Review by Joerger — APPROVED** [review]

**Review by awly — APPROVED** [review]

File: api/client/proto/proto.go (hunk 33 above)
[the remark this answers is not in the document]
Comment (a-palchikov) [reply api/client/proto/proto.go:45]: I'll deduplicate in a follow-up PR.
