### PR TITLE
Fix large event handling for DynamoDB backend

### LINKED ISSUE #61645: Event handler gets stuck on DynamoDB backend
tl;dr: if we have an event larger than 1MiB, event streaming gets stuck. This is a dynamoevent bug, and maybe affects other backends.

This bug is simiar to https://github.com/gravitational/teleport/issues/58365 but does not share he same root cause. When trying to fetch a large event, the event handler can become stuck and stops consuming events. This is a combination of 3 different issues, both in the dynamoevent backend and the event handler.

## Step-by-step

_Note: checkpoint and cursor are essentially the same thing. Checkpoint is from the event backend point of view, and cursor is from the event handler point of view._

- On day 1
  - You have a Teleport cluster with a dynamo backend
  - Teleport stores an event larger than 1MB, the event is the 498th one of the day
- On day 10
  - You start an event handler
  - The event handler gets events from day 1 with no checkpoint
  - Teleport runs the following code
    - QueryByDateIndex which sets checkpoint.Date
     https://github.com/gravitational/teleport/blob/eedb0b48dce586a6f9bf62b32e9754824d24e6ff/lib/events/dynamoevents/dynamoevents.go#L1688
    - processQueryOutput:
      https://github.com/gravitational/teleport/blob/eedb0b48dce586a6f9bf62b32e9754824d24e6ff/lib/events/dynamoevents/dynamoevents.go#L1648-L1657
      - processes the first 497 events
      - sees that the 498th makes the response too large
      - hashes the large event
      - sets checkpoint.EventKey = eventHash
      - sets checkpoint.Iterator = oldIterator (here "", as this is the first query)
     - returns 497 events, and a checkpoint with a date, an event key but no iterator
  - the event handler processes the events and asks for more, sending back the cursor
  - Teleport runs the exact same code and returns no events, and the same cursor
  - the event handler understands this as "no events left for day 1, should move to day 2"
  - the event handler sends the same cursor but with a day 2 time window
  - Teleport runs the following code:
    - searchEventsRaw:
      https://github.com/gravitational/teleport/blob/eedb0b48dce586a6f9bf62b32e9754824d24e6ff/lib/events/dynamoevents/dynamoevents.go#L875-L876
      - try to lookup "created at" from checkpoint but fails, as the checkpoint has no iterator
      - this causes the stale checkpoint to not be detected and dropped
      - sees that checkpoint.Date is not null and proceeds to drop every day from the requested window until the date is reached
      - the date is before the window, hence never reached and the entire window is discarded
      - there's no window left, immediately returns no events and an empty cursor
  - the event handler understands this as "no events left for day 2, should move to day 3"
  - the event handler sends the same cursor but with a day 3 time window
  - repeat until day 10

## Problems

Several issues are combined to cause this bug:

### Root cause: large events are not handled properly

DynamoDB event streaming won't return events larger than 1MiB, causing every other event from the day to be lost.

Suggested fixes:
- Remove the limit (this looks arbitrary)
- Skip the event if it exceeds the limit
- return an error

### Contributing factor: Event handler improper cursor usage when paginating over time

The event handler is reusing the last cursor when moving to the next window instead of clearing it out.

Suggestion:
- add support to the new bulk API and get rid of the legacy event fetcher
- rewrite the legacy event fetcher with tests and a simpler/saner time pagination support
- make sending a stale cursor something explicitely supported by the event backend (currently this causes a lot of warnings saying that it's a bug), and add test coverage for every event backend

During this investigation, a couple of other smells were identified about the event handler:
- poor test coverage
- use of a mix of time.Now() and the auth server time when paginating. Time skew will cause premature day change and the event handler will skip events.
- overly complex legacy event fetcher logic

<details>

<summary>Click here to see the event handler flow<summary>

```mermaid
flowchart TD
  ExportEvents((ExportEvents main loop))
  noBatch{is Batch empty}
  ExportEvents --> noBatch
  subgraph fetch
    clearBatch
    timeWindowLoop[next day]
    clearBatch --> timeWindowLoop
    getEvents
    timeWindowLoop --> getEvents
    convertAndBatch
    getEvents --> convertAndBatch
    hasNextPage{there is a next page}
    convertAndBatch --> hasNextPage
    batchEmptyAndRangeLeft{batch is empty and it's not last day}
    hasNextPage -- no --> batchEmptyAndRangeLeft
    batchEmptyAndRangeLeft -- yes --> timeWindowLoop
    findLastProcessedEvt
    batchEmptyAndRangeLeft -- no --> findLastProcessedEvt
    batchProcessedAndRangeLeft{batch is processed and it's not last day}
    findLastProcessedEvt --> batchProcessedAndRangeLeft
    batchProcessedAndRangeLeft -- yes --> timeWindowLoop
  end
  batchProcessedAndRangeLeft -- no --> noBatchNoCursor
  noBatch -- yes --> clearBatch
  noBatchNoCursor{are batch and cursor still empty}
  hasNextPage-- yes -->noBatchNoCursor
  noBatchNoCursor -- yes --> ExportEvents
  nonEmptyBatch[batch contains events]
  noBatch -- no --> nonEmptyBatch
  noBatchNoCursor -- no --> nonEmptyBatch
  lastEvtProcessed{did we proces the last event}
  nonEmptyBatch --> lastEvtProcessed
  nextPageAvailable{is there a next page}
  lastEvtProcessed -- yes --> nextPageAvailable
  flipPage[flip page and clear pos and batch]
  nextPageAvailable -- yes --> 
  flipPage --> ExportEvents

  subgraph fetch2
    clearBatch2
    timeWindowLoop2[next day]
    clearBatch2 --> timeWindowLoop2
    getEvents2
    timeWindowLoop2 --> getEvents2
    convertAndBatch2
    getEvents2 --> convertAndBatch2
    hasNextPage2{there is a next page}
    convertAndBatch2 --> hasNextPage2
    batchEmptyAndRangeLeft2{batch is empty and it's not last day}
    hasNextPage2 -- no --> batchEmptyAndRangeLeft2
    batchEmptyAndRangeLeft2 -- yes --> timeWindowLoop2
    findLastProcessedEvt2
    batchEmptyAndRangeLeft2 -- no --> findLastProcessedEvt2
    batchProcessedAndRangeLeft2{batch is processed and it's not last day}
    findLastProcessedEvt2 --> batchProcessedAndRangeLeft2
    batchProcessedAndRangeLeft2 -- yes --> timeWindowLoop2
    batchProcessedAndRangeLeft2 -- no --> lastEvtProcessed2
  end
  hasNextPage2 -- yes --> lastEvtProcessed2

  nextPageAvailable -- no --> clearBatch2
  lastEvtProcessed2{did we proces the last event}
  lastEvtProcessed2 -- yes --> ExportEvents

  processEvents
  lastEvtProcessed --> processEvents
  lastEvtProcessed2 --> processEvents
  processEvents --> ExportEvents
```

### Contributing factor: Improper checkpoint date handling

Because we're only using the checkpoint.Iterator to detect stale cursors, we miss checkpoints with no iterator but a stale date.
This is made worse by the legacy subpage checkpointing which is hashing every event instead of suing the iterator, as it increases the probability if returning a checkpoint with a nil Iterator.

Suggestions:
- Add a check to drop the checkpoint if the date is before the range for consistency with the iterator check
- Remove the sub-page checkpointing which is useless and harmful since we have proper pagination (https://github.com/gravitational/teleport/issues/58888)

### PR DESCRIPTION
**Pull request by kshi36**
Fixes #61645

This PR fixes a bug where the event handler would get stuck when querying large events (>1 MiB) from DynamoDB.

We attempt to trim the single large event first using `AuditEvent.TrimToMaxSize` before sending it over.

changelog: Fixed bug where event handler would get stuck on DynamoDB backend when handling large events

### CODE REVIEW

File: lib/events/dynamoevents/dynamoevents.go [hunk 1]
```diff
@@ -1621,10 +1622,53 @@ func (l *eventsFetcher) processQueryOutput(output *dynamodb.QueryOutput) ([]even
...
+			if err != nil {
+				return nil, false, trace.Wrap(err, "failed to trim event to max size")
+			}
+			trimmedData, err := json.Marshal(e.FieldsMap)
+			if err != nil {
 				return nil, false, trace.Wrap(err)
 			}
-			return out, true, nil
+
+			if l.totalSize+len(trimmedData) <= events.MaxEventBytesInResponse {
```
Comment (bernardjkim) [inline lib/events/dynamoevents/dynamoevents.go]: Probably a trivial mistake in line 1624, but just noticed a discrepancy between this line and 1624.
Do we allow the response size to be == `events.MaxEventBytesInResponse` or must the response size be <  `events.MaxEventBytesInResponse`?

Comment (kshi36) [reply lib/events/dynamoevents/dynamoevents.go]: I also noticed this discrepancy; I believe it is better to have it inclusive for line 1645, otherwise an error would be returned, and have line 1624 be exclusive (> `events.MaxEventBytesInResponse` over >=). This would also align with Athena backend's logic as well

File: lib/events/dynamoevents/dynamoevents_test.go [hunk 2]
```diff
@@ -1096,6 +1118,65 @@ func Test_eventsFetcher_QueryByDateIndex(t *testing.T) {
...
+		{
+			name:  "events with big trimmable event exceeding > MaxEventBytesInResponse",
+			limit: 10,
+			mockResponses: map[EventKey]mockResponse{
+				{}: {
+					events:    []apievents.AuditEvent{event1},
+					returnKey: &key1,
+				},
+				key1: {
+					events:    []apievents.AuditEvent{event2, event3, bigUntrimmableEvent},
```
Comment (juliaogris) [inline lib/events/dynamoevents/dynamoevents_test.go]: Should probably be `bigTrimmableEvent` to match description?

File: lib/events/dynamoevents/dynamoevents.go [hunk 3]
```diff
@@ -1640,6 +1684,25 @@ func (l *eventsFetcher) processQueryOutput(output *dynamodb.QueryOutput) ([]even
 	return out, false, nil
 }
 
+// trimToMaxSize attempts to trim the event to fit into the maximum response size (MaxEventBytesInResponse).
+// If the event is larger than the maximum response size, it will be trimmed
+// to the maximum size, which may result in loss of data.
+// Trimming requires unmarshalling the event to apievents.AuditEvent and then
+// calling TrimToMaxSize on it.
+// This is not an efficient operation, but it is executed once per page,
+// so it should not be a problem in practice.
```
Comment (juliaogris) [inline lib/events/dynamoevents/dynamoevents.go:1687]: nit:
executed at most once per page, and only when a single event exceeds the limit, so ....

File: lib/events/dynamoevents/dynamoevents_test.go [hunk 4]
```diff
@@ -1027,18 +1028,39 @@ func Test_eventsFetcher_QueryByDateIndex(t *testing.T) {
 			AppName: "app-4",
 		},
 	}
+	bigUntrimmableEvent := &apievents.AppCreate{
+		Metadata: apievents.Metadata{
+			ID:   uuid.NewString(),
+			Time: time.Now().UTC(),
```
Comment (juliaogris) [inline lib/events/dynamoevents/dynamoevents_test.go]: Maybe also use `Time: time.Date(2025, 2, 5, 0, 0, 0, 0, time.UTC),` for consistency with events above?

**Review by juliaogris — APPROVED** [review]
LGTM with a few minor comments.

One remark / question: Athena already had this large event handling, and Dynamo is now fixed by this PR. But PostgreSQL, Firestore, and Filelog don't have this handling and could potentially hit the same stuck behavior if they encounter a single event approaching 1 MiB, correct?

**Comment by kshi36** [comment]
> But PostgreSQL, Firestore, and Filelog don't have this handling and could potentially hit the same stuck behavior if they encounter a single event approaching 1 MiB, correct?

This is correct, I plan to open separate PR(s) to contain large event handling as well

**Review by bernardjkim — APPROVED** [review]

File: lib/events/dynamoevents/dynamoevents.go [hunk 5]
```diff
@@ -1620,11 +1621,54 @@ func (l *eventsFetcher) processQueryOutput(output *dynamodb.QueryOutput) ([]even
...
+			if err != nil {
+				return nil, false, trace.Wrap(err, "failed to trim event to max size")
+			}
+			trimmedData, err := json.Marshal(e.FieldsMap)
+			if err != nil {
 				return nil, false, trace.Wrap(err)
 			}
-			return out, true, nil
+
+			if l.totalSize+len(trimmedData) <= events.MaxEventBytesInResponse {
```
Comment (hugoShaka) [inline lib/events/dynamoevents/dynamoevents.go]: If we are here, I suppose we are in the single-event case, else we would have been caught in the early return `if len(out) > 0`. If so, how can `l.totalSize+len(trimmedData) <= events.MaxEventBytesInResponse` be true? `l.totalSize` is supposed to be zero in a single-event case, and we are trimming the event.

Is it possible for the trimmed event to still exceed the max size?

Comment (kshi36) [reply lib/events/dynamoevents/dynamoevents.go]: Yes, it may still be possible that the trim was unsuccessful, so we guard check here. We then return an error in this code path to indicate a bug with certain events not being trimmed properly (to avoid skipping large events altogether)

Comment (hugoShaka) [reply lib/events/dynamoevents/dynamoevents.go]: How does the event handler reacts to this error?

Comment (kshi36) [reply lib/events/dynamoevents/dynamoevents.go]: The error trickles up to `(*EventsJob).runPolling` and to `(*EventsJob).run`, and then the event handler re-enters the `runPolling` loop after 5s. The event handler doesn't seem to panic and crash, but will likely loop indefinitely because of the large event not being able to be exported.

<details><summary>events_job.go snippet</summary>
<p>

```golang
	for {
		err := j.runPolling(ctx)
		if err == nil || ctx.Err() != nil {
			j.app.log.DebugContext(ctx, "Watch loop exiting")
			return trace.Wrap(err)
		}

		j.app.log.ErrorContext(
			ctx, "Unexpected error in watch loop. Reconnecting in 5s...",
			"error", err,
		)

		select {
		case <-time.After(time.Second * 5):
		case <-ctx.Done():
			return nil
		}
	}
```

</p>
</details>

Comment (hugoShaka) [reply lib/events/dynamoevents/dynamoevents.go]: In this case I think we should either serve the oversized event, or skip it entirely. We are already blocking on this so it's not worse that the current state.

**Comment by kshi36** [comment]
After discussing with Hugo, we decided to serve the oversized event in the case that trimming is unsuccessful (bypassing the 1 MiB limit), as opposed to sending an error. If an error is returned, the event handler will re-engage the `runPolling` loop after 5 seconds. This would cause the event handler to loop indefinitely.

<details><summary>events_job.go snippet</summary>
<p>

```golang
	for {
		err := j.runPolling(ctx)
		if err == nil || ctx.Err() != nil {
			j.app.log.DebugContext(ctx, "Watch loop exiting")
			return trace.Wrap(err)
		}

		j.app.log.ErrorContext(
			ctx, "Unexpected error in watch loop. Reconnecting in 5s...",
			"error", err,
		)

		select {
		case <-time.After(time.Second * 5):
		case <-ctx.Done():
			return nil
		}
	}
```

</p>
</details>

File: lib/events/dynamoevents/dynamoevents_test.go [hunk 6]
```diff
@@ -1096,6 +1117,65 @@ func Test_eventsFetcher_QueryByDateIndex(t *testing.T) {
...
+				{}: {
+					events:    []apievents.AuditEvent{event1},
+					returnKey: &key1,
+				},
+				key1: {
+					events:    []apievents.AuditEvent{event2, event3, bigTrimmableEvent},
+					returnKey: nil,
+				},
+			},
+			// we don't expect bigTrimmedEvent because it should go to next batch
```
Comment (juliaogris) [inline lib/events/dynamoevents/dynamoevents_test.go]: nit: s/bigTrimmedEvent/bigTrimmableEvent/

File: lib/events/dynamoevents/dynamoevents.go [hunk 7]
```diff
@@ -1620,7 +1620,44 @@ func (l *eventsFetcher) processQueryOutput(output *dynamodb.QueryOutput) ([]even
...
+				events.MetricQueriedTrimmedEvents.Inc()
+			} else {
+				// Failed to trim the event to size.
+				// Even if we fail to trim the event, we still try to return the oversized event.
+				l.log.ErrorContext(context.Background(), "Failed to trim event exceeding maximum response size.",
+					"event_type", e.FieldsMap.GetType(),
+					"event_id", e.FieldsMap.GetID(),
+					"event_size", len(data),
+					"event_size after trim", len(trimmedData),
```
Comment (juliaogris) [inline lib/events/dynamoevents/dynamoevents.go]: Missing underscores? `event_size_after_trim`

**Review by juliaogris — APPROVED** [review]
Still LGTM, with minor comments, feel free to ignore.

One observation: IIUC Athena still returns an error when trimming fails (querier.go:1018-1020), which would cause the same infinite retry loop you're fixing here for DynamoDB. Might be worth a follow-up PR to align Athena with this approach (serve oversized event + log error) for consistency.

**Review by bernardjkim — APPROVED** [review]

**Comment by kshi36** [comment]
> IIUC Athena still returns an error when trimming fails

This makes sense, I will work on a follow-up PR for this. After rummaging around in issues, I encountered this! #54480

File: lib/events/dynamoevents/dynamoevents.go (hunk 5 above)
Comment (tigrato) [reply lib/events/dynamoevents/dynamoevents.go]: I agree that we should serve the event. As long as the event size is lower than 4MB, the gRPC max message size, we are good.

Retrospectively, we shouldn't trim the events to 1MB. That limit doesn't make much sense from an operational point of view

File: lib/events/dynamoevents/dynamoevents.go [hunk 8]
```diff
@@ -1620,7 +1620,44 @@ func (l *eventsFetcher) processQueryOutput(output *dynamodb.QueryOutput) ([]even
...
+				return out, true, nil
+			}
+
+			// A single event is larger than the max page size - the best we can
+			// do is try to trim it.
+			e.FieldsMap, err = trimToMaxSize(e.FieldsMap)
+			if err != nil {
+				return nil, false, trace.Wrap(err, "failed to trim event to max size")
+			}
+			trimmedData, err := json.Marshal(e.FieldsMap)
```
Comment (tigrato) [inline lib/events/dynamoevents/dynamoevents.go:1639]: I wonder if we really need to marshal it again here.

Do we care if we trimmed it correctly if we return it anw?

File: lib/events/dynamoevents/dynamoevents.go (hunk 5 above)
Comment (kshi36) [reply lib/events/dynamoevents/dynamoevents.go]: In that case, should we skip trimming events to 1MB? Should we set the limit to 4MB and try to trim to that size?

Comment (tigrato) [reply lib/events/dynamoevents/dynamoevents.go]: For consistency, I’d keep the 1 MB trim check in place for now.
Going forward, I’d like to eliminate this limit, either by splitting large events into several events or returning them intact.

There’s little value in recording and storing complete data if it can’t be read everything afterwards

File: lib/events/dynamoevents/dynamoevents.go (hunk 8 above)
Comment (kshi36) [reply lib/events/dynamoevents/dynamoevents.go:1639]: I guess for now it helps to keep track of the `events.MetricQueriedTrimmedEvents` metric, as well as display an error to see why certain events cannot be trimmed. In the case that a very large event (>4MiB?) causes unexpected behavior we can pinpoint it to this

File: lib/events/dynamoevents/dynamoevents.go [hunk 9]
```diff
@@ -1620,7 +1620,44 @@ func (l *eventsFetcher) processQueryOutput(output *dynamodb.QueryOutput) ([]even
...
+				events.MetricQueriedTrimmedEvents.Inc()
+			} else {
+				// Failed to trim the event to size.
+				// Even if we fail to trim the event, we still try to return the oversized event.
+				l.log.ErrorContext(context.Background(), "Failed to trim event exceeding maximum response size.",
+					"event_type", e.FieldsMap.GetType(),
+					"event_id", e.FieldsMap.GetID(),
+					"event_size", len(data),
+					"event_size_after_trim", len(trimmedData),
+				)
```
Comment (hugoShaka) [inline lib/events/dynamoevents/dynamoevents.go]: nit: maybe make this a Warning? I'd expect users to have to take immediate remediation action when reading an Error log, while Warning indicates it's not great but they don't need to fix stuff now.

File: lib/events/dynamoevents/dynamoevents.go [hunk 10]
```diff
@@ -1620,7 +1620,44 @@ func (l *eventsFetcher) processQueryOutput(output *dynamodb.QueryOutput) ([]even
...
+			if err != nil {
+				return nil, false, trace.Wrap(err, "failed to trim event to max size")
+			}
+			trimmedData, err := json.Marshal(e.FieldsMap)
+			if err != nil {
+				return nil, false, trace.Wrap(err)
+			}
+
+			if l.totalSize+len(trimmedData) <= events.MaxEventBytesInResponse {
+				events.MetricQueriedTrimmedEvents.Inc()
```
Comment (hugoShaka) [inline lib/events/dynamoevents/dynamoevents.go]: Should this metric increment live outside of the `if` statement? We will return the trimmed event anyway.

**Review by hugoShaka — APPROVED** [review]

**Review by tigrato — APPROVED** [review]
