### PR TITLE
Use the proper check for the SAML IdP session.

### LINKED ISSUE #27212: [v12] Using Teleport as SAML IdP fails on subsequent logins
### Expected behavior:

You should always be able to use Teleport as IdP to log into a service provider with SAML.

### Current behavior:

The first time you log into the SP using Teleport as IdP, it works as expected, however if you log out and then try to log in again in the same browser, the login fails with a `Forbidden` error. The Teleport console also logs the error shown below. 

Note that if you then clear your browser memory or open a new incognito window, you are able to log in. The first login works and any logins after that fail unless on a fresh browser.

### Bug details:
- Teleport version: `12.4.5`, this bug does not occur in `v13`.
- Recreation steps

1. Attempt to log in with SAML to an app you have set up with Teleport as the IdP. Observe that the attempt is successful.
2. Log out of the app and then try to log in again in the same browser. Observe that the login fails with a `Forbidden` error and that the Teleport console logs the error below.

- Debug logs

```
2023-06-01T17:01:22+01:00 WARN [PROXY:1:C] Re-init the cache on error error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError watcher is closed: received unsupported resource *proto.Event_SAMLIdPSession
Stack Trace:
	github.com/gravitational/teleport/lib/cache/cache.go:1119 github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch
	github.com/gravitational/teleport/lib/cache/cache.go:944 github.com/gravitational/teleport/lib/cache.(*Cache).update
	runtime/asm_arm64.s:1172 runtime.goexit
User Message: watcher is closed: received unsupported resource *proto.Event_SAMLIdPSession] cache/cache.go:950
2023-06-01T17:01:24+01:00 WARN [PROXY]     Restart watch on error: watcher is closed: watcher closed. pid:23279.1 resource-kind:cert_authority services/watcher.go:246
2023-06-01T17:01:25+01:00 WARN [PROXY:1]   Restart watch on error: watcher is closed: watcher closed. pid:23279.1 resource-kind:proxy services/watcher.go:246
2023-06-01T17:01:26+01:00 INFO [RBAC]      Access to read saml_idp_session in namespace default denied to roles Proxy,default-implicit-role: no allow rule matched. services/role.go:3014
2023-06-01T17:01:26+01:00 ERRO [IDP.SAML]  Failed to get session. error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError access denied to perform action &#34;read&#34; on &#34;saml_idp_session&#34;
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/client.go:1395 github.com/gravitational/teleport/api/client.(*Client).GetSAMLIdPSession
	github.com/gravitational/teleport/e/lib/idp/saml/session.go:42 github.com/gravitational/teleport/e/lib/idp/saml.(*Service).getExistingSession
	github.com/gravitational/teleport/e/lib/idp/saml/providers.go:76 github.com/gravitational/teleport/e/lib/idp/saml.(*Service).getSession
	github.com/gravitational/teleport/e/lib/idp/saml/providers.go:30 github.com/gravitational/teleport/e/lib/idp/saml.(*Service).GetSession
	github.com/crewjam/saml@v0.4.14-0.20230420111643-34930b26d33b/identity_provider.go:243 github.com/crewjam/saml.(*IdentityProvider).ServeSSO
	github.com/gravitational/teleport/e/lib/idp/saml/handler.go:144 github.com/gravitational/teleport/e/lib/idp/saml.(*Service).handleSSO
	github.com/gravitational/teleport/e/lib/idp/saml/handler.go:89 github.com/gravitational/teleport/e/lib/idp/saml.(*Service).withAuthCtx.func1
	github.com/julienschmidt/httprouter@v1.3.0/router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	github.com/gravitational/teleport/e/lib/idp/saml/handler.go:53 github.com/gravitational/teleport/e/lib/idp/saml.(*Service).ServeHTTP
	github.com/gravitational/teleport/e/lib/web/plugin.go:285 github.com/gravitational/teleport/e/lib/web.(*Plugin).withSAMLAuth.func1
	github.com/gravitational/teleport/lib/httplib/httplib.go:109 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1
	github.com/julienschmidt/httprouter@v1.3.0/router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	github.com/gravitational/teleport/lib/web/apiserver.go:295 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
	github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
	github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
	github.com/gravitational/teleport/lib/httplib/httplib.go:94 github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1
	net/http/server.go:2122 net/http.HandlerFunc.ServeHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.39.0/handler.go:213 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
	net/http/server.go:2936 net/http.serverHandler.ServeHTTP
	net/http/server.go:1995 net/http.(*conn).serve
	runtime/asm_arm64.s:1172 runtime.goexit
User Message: access denied to perform action &#34;read&#34; on &#34;saml_idp_session&#34;] pid:23279.1 saml/providers.go:32
```

### PR DESCRIPTION
**Pull request by mdwn**
KindWebSession should be used for checking SAML IdP permissions instead of KindSAMLIdPSession.

Closes https://github.com/gravitational/teleport/issues/27212

### CODE REVIEW

File: lib/auth/auth_with_roles.go [hunk 1]
```diff
@@ -4542,7 +4542,7 @@ func (a *ServerWithRoles) GetSAMLIdPSession(ctx context.Context, req types.GetSA
 	}
 	// Users can only fetch their own SAML IdP sessions.
```
Comment (zmb3) [inline lib/auth/auth_with_roles.go:4543]: Update the comment too?
```suggestion
	// Users can only fetch their own web sessions.
```

File: lib/auth/auth_with_roles.go [hunk 2]
```diff
@@ -4542,7 +4542,7 @@ func (a *ServerWithRoles) GetSAMLIdPSession(ctx context.Context, req types.GetSA
...
 	if err := a.currentUserAction(session.GetUser()); err != nil {
```
Comment (zmb3) [inline lib/auth/auth_with_roles.go:4544]: Why are we doing the RBAC check _after_ we've fetched the session?

**Comment by zmb3** [comment]
Can we add test coverage too? If RBAC was wrong the whole time and nothing failed that suggests a lack of coverage.

**Review by espadolini — APPROVED** [review]

File: lib/auth/auth_with_roles.go (hunk 2 above)
Comment (espadolini) [reply lib/auth/auth_with_roles.go:4544]: Wait, does this mean that in this and `GetAppSession`/`GetSnowflakeSession` we're actually revealing if a session exists even if the requester doesn't have permissions to read it?

Comment (mdwn) [reply lib/auth/auth_with_roles.go:4544]: Yes it does. IIRC I tried to fix this before, but I can't remember what the conversation was at the time. Want me to make this error opaque while I'm here?

Comment (mdwn) [reply lib/auth/auth_with_roles.go:4544]: Ahhh, I think I know what it was. I think there are things that depend on the `NotFound` return from sessions that makes fixing this non-trivial.

Comment (mdwn) [reply lib/auth/auth_with_roles.go:4544]: It's this: https://github.com/gravitational/teleport/pull/22586 that I was thinking of. :-) Not the same thing, but I think I maintained the semantics for a similar reason.

File: lib/auth/auth_with_roles.go [hunk 3]
```diff
@@ -4590,6 +4590,7 @@ func (a *ServerWithRoles) GetSnowflakeSessions(ctx context.Context) ([]types.Web
 
 // ListSAMLIdPSessions gets a paginated list of SAML IdP sessions.
 func (a *ServerWithRoles) ListSAMLIdPSessions(ctx context.Context, pageSize int, pageToken, user string) ([]types.WebSession, string, error) {
+	// Check if this a proxy service.
```
Comment (zmb3) [inline lib/auth/auth_with_roles.go:4593]: What does this comment mean? The code doesn't appear relayed to proxy in any way.

**Review by zmb3 — APPROVED** [review]

File: lib/auth/auth_with_roles.go (hunk 3 above)
Comment (mdwn) [reply lib/auth/auth_with_roles.go:4593]: Ahhh, leftover comment. I'll remove.
