### PR TITLE
Continue to emit session specific audit events when session recording is disabled.

### LINKED ISSUE #1519: Teleport does not send 'session.end' event when session is terminated (event stream web-socket)
Repro steps:
1. Disable session recording in teleport configuration file
2. Go to web app and open a terminal window
3. type `$ exit`

Expected behavior: the `session.end` event should be sent over event stream web socket connection 
(/webapi/sites/one/sessions/:sid/events/stream) and terminal window should be automatically closed.

Actual: `session.end` event never gets sent.

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

In #1430 the ability to not record sessions was introduced. Starting with #1430 events continued to go to the Audit Log, but session specific events and stream bytes were discarded. Unfortunately as covered in #1519 the stream specific events are required by the Web UI to do things like close terminal windows when a session is complete.

This PR reintroduces stream specific events when session recording is disabled.

**Implementation**

* Removed the `discardSessionLogger`.
* Only create the stream bytes file when session recording is enabled.
* In `WriteChunk`, chunks are only written if recording is enabled.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1519

### CODE REVIEW

**Review by kontsevoy — APPROVED** [review]
Makes sense.

File: lib/events/sessionlog.go [hunk 1]
```diff
@@ -213,6 +234,11 @@ func (sl *DiskSessionLogger) WriteChunk(chunk *SessionChunk) (written int, err e
 	sl.Lock()
 	defer sl.Unlock()
 
+	// when session recording is turned off, don't record the session byte stream
+	if sl.recordSessions == false {
+		return 0, nil
```
Comment (klizhentas) [inline lib/events/sessionlog.go]: should not return 0, should return lengh written, so implementations of io.Copy using it won't fail

File: lib/events/sessionlog.go [hunk 2]
```diff
@@ -196,14 +212,19 @@ func (sl *DiskSessionLogger) Close() error {
 func (sl *DiskSessionLogger) Finalize() error {
 	sl.Lock()
 	defer sl.Unlock()
+
+	sl.Debug("Finalize")
```
Comment (klizhentas) [inline lib/events/sessionlog.go]: remove this line as not necessary

File: lib/events/auditlog_test.go [hunk 3]
```diff
@@ -165,10 +165,14 @@ func (a *AuditTestSuite) TestSessionRecordingOff(c *check.C) {
 	c.Assert(found[0].GetString(EventLogin), check.Equals, "doggy")
 	c.Assert(found[1].GetString(EventLogin), check.Equals, "doggy")
 
-	// inspect the session log for "200". it should be empty.
+	// inspect the session log for "200". we should have two
```
Comment (klizhentas) [inline lib/events/auditlog_test.go]: let's not use `we` in the code and instead refer to the part of the code or algo in question. When I read "we" it takes me time to process who is meant by "we"

**Review by klizhentas — CHANGES_REQUESTED** [review]
need a couple of tweaks first

**Review by klizhentas — APPROVED** [review]
