### PR TITLE
[Web] Desktop Discovery UI fixes

### LINKED ISSUE #25161: Discovery Desktop Access off by one error
The yaml config highlighting animation is off by one line:

image

### LINKED ISSUE #25163: Discovery Desktop Access text color and margin error
The text color in light mode and the margin of the Teleport Proxy's IP are off

image

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR closes https://github.com/gravitational/teleport/issues/25163
This PR closes https://github.com/gravitational/teleport/issues/25161

Fixes minor UI bugs discovered in the Desktop discovery flow.

## Implementation

The issue outlined in https://github.com/gravitational/teleport/issues/25161 was caused because we assumed that the outputted config selected in the animated terminal window would start on line `4`, however this wouldn't be the case if the generated URL in the first command was shorter or longer and thus took up a different number of lines. By replacing the URL in the animated terminal window with a fixed example URL, the config will always start on the same line.

image

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

File: web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/DesktopService.tsx
Comment (kimlisa) [inline web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/DesktopService.tsx:1]: can we remove the hard coded colors in this file? (while we are at this)
lines
- 27
- 32
- 65

File: web/packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScriptAnimation.tsx [hunk 1]
```diff
@@ -32,7 +31,9 @@ import { JoinToken } from 'teleport/services/joinToken';
 
 const lines = (joinToken: JoinToken) => [
   {
-    text: generateCommand(cfg.getConfigureADUrl(joinToken.id)),
+    text: generateCommand(
+      'https://teleport.example/v1/webapi/scripts/desktop-access/configure/your-token/configure-ad.ps1'
```
Comment (kimlisa) [inline web/packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScriptAnimation.tsx:35]: make it more apparent:
```suggestion
      'https://teleport.example/v1/webapi/scripts/desktop-access/configure/<YOUR_TOKEN>/configure-ad.ps1'
```

**Review by kimlisa — APPROVED** [review]

File: web/packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScriptAnimation.tsx (hunk 1 above)
Comment (zmb3) [reply web/packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScriptAnimation.tsx:35]: Should we use `teleport.example.com` which is more in line with our docs than `teleport.example`?

File: web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/DesktopService.tsx
Comment (rudream) [reply web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/DesktopService.tsx:1]: Removed hardcoded colour on line `65`. The colours on `27` and `32` are at 0 opacity so they don't make a difference.

File: web/packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScriptAnimation.tsx (hunk 1 above)
Comment (rudream) [reply web/packages/teleport/src/Discover/Desktop/ConnectTeleport/RunConfigureScriptAnimation.tsx]: > though, can't we assume the length of a valid token instead?

I feel like using a realistic looking token in an example dummy URL doesn't serve any purpose and might just lead to potential confusion.

**Comment by rudream** [comment]
In 7874eeb11ea37eeb8b28ad18715cd7218e54ee60 I made some changes to the Server graphics to make them more dynamic because they contrasted very poorly on light theme.

### Before: 
image

### After:
image

image

File: web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/ServerIcon.tsx [hunk 2]
```diff
@@ -22,7 +22,8 @@ const Server = styled.div`
   height: 16px;
   padding: 0 7px;
   box-sizing: border-box;
-  background: #f5e6fe;
+  background: ${({ theme }) =>
+    theme.name === 'light' ? '#6c6c6c' : '#f2e9f7'};
```
Comment (zmb3) [inline web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/ServerIcon.tsx:26]: Eventually we'll have to fix this right? Depending on the theme name will break custom themes.

**Review by zmb3 — APPROVED** [review]

**Review by kimlisa — APPROVED** [review]

File: web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/ServerIcon.tsx (hunk 2 above)
Comment (rudream) [reply web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/ServerIcon.tsx:26]: Correct, we will need to remove these instances and define these specific colours in the theme
