### PR TITLE
Session fixes

### LINKED ISSUE #10983: SSH session stops outputting stdout and stderr

### PR DESCRIPTION
**Pull request by Joerger**
This PR reworks session ending logic to fix session freezing, deadlocks, race conditions, and other session end failures.

### Changes
- Split session end logic into two parts - `Stop` and `Close`
  - Stop can be called from anywhere to kill the session terminal, disconnect clients, and trigger background goroutines to complete cleanup (upload session recording, emit audit events, etc.)
  - Close is only called by the session creator to release remaining resources which can't be removed immediately. Stop will trigger Close.
- Rework party leaving logic, which was prone to deadlocks before - https://github.com/gravitational/teleport/pull/11647
- Fix session `lingerAndDie` logic, which could occur multiple times for a session, and could occur even after the session was closed.
- Fixed session freezing when the session is terminated, whether it is force terminated due to moderated sessions, or due to an internal server error.
  - `sess.io.Write` and `sess.io.Read` will now return `io.EOF` if `sess.io` is closed, unblocking the `io.Copy` loops and allowing session cleanup to complete.
- Session will no longer continue if the session recorder is broken, instead it will trigger `sess.Stop` with `s.io.OnWriteError`
- Session uploads will no longer fail due to the session writer closing before the uploader completes.
- Fix issue where exec sessions are closed immediately, preventing audit writing and stream recording.

### TODO:
 - Add tests (if possible), although it should be largely covered with existing tests

Closes https://github.com/gravitational/teleport/issues/10983
Related https://github.com/gravitational/teleport/issues/11599 - session.end event is more reliable now

### CODE REVIEW

File: lib/auth/permissions.go [hunk 1]
```diff
@@ -383,6 +383,7 @@ func GetCheckerForBuiltinRole(clusterName string, recConfig types.SessionRecordi
 					Rules: []types.Rule{
 						types.NewRule(types.KindNode, services.RW()),
 						types.NewRule(types.KindSSHSession, services.RW()),
+						types.NewRule(types.KindSession, services.RO()),
```
Comment (Joerger) [inline lib/auth/permissions.go:386]: This fixes some log spam / upload completer scan failure. 
```
{"caller":"filesessions/fileasync.go:226","component":"upload","error":"access denied to perform action \"read\" on \"session\"","level":"warning","message":"Completer scan failed.","timestamp":"2022-03-04T15:50:46-06:00"}
```

**Comment by xacrimon** [comment]
@Joerger Thanks for this, a lot of this went unnoticed in the sea of other things I was reworking with moderated sessions. Most of these aren't very applicable to K8S as it largely suffers from a lot of the historical cruft. The stop session on recorder failure is probably applicable though.

File: lib/srv/termmanager.go [hunk 2]
```diff
@@ -65,14 +65,14 @@ func NewTermManager() *TermManager {
...
-		closed:            false,
+		closed:            make(chan struct{}),
 		readStateUpdate:   sync.NewCond(&sync.Mutex{}),
 		incoming:          make(chan []byte, 100),
 		terminateNotifier: make(chan struct{}, 1),
 	}
 }
 
-func (g *TermManager) writeToClients(p []byte) int {
+func (g *TermManager) writeToClients(p []byte) (int, error) {
```
Comment (xacrimon) [inline lib/srv/termmanager.go:75]: Do we need to return an error here if it's never assigned to?

File: lib/srv/sess.go [hunk 3]
```diff
@@ -686,11 +484,19 @@ func newSession(id rsession.ID, r *SessionRegistry, ctx *ServerContext) (*sessio
...
+		doneCh:                         make(chan struct{}),
 		initiator:                      ctx.Identity.TeleportUser,
 		displayParticipantRequirements: utils.AsBool(ctx.env[teleport.EnvSSHSessionDisplayParticipantRequirements]),
 	}
 
+	sess.io.OnWriteError = func(idString string, err error) {
+		if idString == sessionRecorderID {
+			sess.log.Error("Failed to write to session recorder, stopping session.")
+			// stop in goroutine to avoid deadlock
+			go sess.Stop()
```
Comment (xacrimon) [inline lib/srv/sess.go:496]: This stops the session if any party has a flaky connection, would it be better to force the party to leave and remove the writer? If the party was required for the session to run as per moderated sessions, the leave mechanism should kick in and stop it.

File: lib/srv/sess.go [hunk 4]
```diff
@@ -730,52 +536,89 @@ func (s *session) Recorder() events.StreamWriter {
...
-				s.log.Warnf("Failed to set tracker state to %v", types.SessionState_SessionStateRunning)
-			}
-		}()
-	})
-	return nil
+	s.BroadcastMessage("Stopping session...")
+	s.log.Infof("Stopping session %v.", s.id)
+
+	// close io copy loops
+	if s.io != nil {
```
Comment (xacrimon) [inline lib/srv/sess.go:556]: Can stop be called where io is nil at any point? It seems to be set at session creation and never to nil

File: lib/srv/sess.go [hunk 5]
```diff
@@ -1681,16 +1627,8 @@ func (p *party) String() string {
...
-		p.log.Infof("Closing party %v", p.id)
-		if err = p.s.registry.leaveSession(p); err != nil {
-			p.ctx.Error(err)
-		}
-		close(p.closeC)
-		close(p.termSizeC)
-		err = p.ch.Close()
-	})
-	return err
+	p.log.Infof("Closing party %v", p.id)
```
Comment (xacrimon) [inline lib/srv/sess.go:1630]: Are we sure that this is never called twice?

File: lib/srv/sess.go (hunk 3 above)
Comment (xacrimon) [reply lib/srv/sess.go:496]: Nevermind, I misread this

File: lib/srv/sess.go (hunk 5 above)
Comment (Joerger) [reply lib/srv/sess.go:1621]: Yes this is the case now, as it is only called in `removeParty` which is performed behind the session mutex on `s.parties`.

Comment (xacrimon) [reply lib/srv/sess.go:1619]: 👍

**Review by xacrimon — APPROVED** [review]

File: lib/srv/sess.go [hunk 6]
```diff
@@ -1341,10 +1239,44 @@ func (s *session) SetLingerTTL(ttl time.Duration) {
...
+		return false
+	}
+}
+
+// If after a short linger duration there are no active
+// parties in the session, end the session.
+func (s *session) lingerAndDie(party *party) {
+	s.log.Debugf("Session %v has no active party members.", s.id)
+
+	time.Sleep(s.GetLingerTTL())
```
Comment (r0mant) [inline lib/srv/sess.go:1256]: Any reason not to use `s.scx.srv.GetClock()` instead of `time` here like it was before?

File: lib/srv/sess.go [hunk 7]
```diff
@@ -1367,8 +1299,11 @@ func (s *session) exportPartyMembers() []rsession.Party {
 
 // exportParticipants returns a list of all members that joined the party.
 func (s *session) exportParticipants() []string {
-	s.mu.Lock()
-	defer s.mu.Unlock()
```
Comment (r0mant) [inline lib/srv/sess.go:1371]: Why did you remove this?

File: lib/srv/sess.go [hunk 8]
```diff
@@ -731,54 +536,86 @@ func (s *session) Recorder() events.StreamWriter {
...
+		if err := s.term.Close(); err != nil {
+			s.log.Debugf("Failed to close the shell: %v", err)
+		}
+		if err := s.term.Kill(); err != nil {
+			s.log.Debugf("Failed to kill the shell: %v", err)
+		}
+	}
+
+	// Remove session parties and close client connections.
+	for _, p := range s.parties {
```
Comment (r0mant) [inline lib/srv/sess.go:569]: Is `s.parties` protected by the mutex above?

File: lib/srv/sess.go [hunk 9]
```diff
@@ -808,30 +645,206 @@ outer:
...
+	}
+
+	// Emit session join event to Audit Log.
+	if err := s.recorder.EmitAuditEvent(ctx.srv.Context(), sessionJoinEvent); err != nil {
+		s.log.WithError(err).Warn("Failed to emit session join event.")
+	}
 
+	// Notify all members of the party that a new member has joined over the
+	// "x-teleport-event" channel.
+	for _, p := range s.parties {
```
Comment (r0mant) [inline lib/srv/sess.go:730]: Doesn't look like `s.parties` is protected here, might be a data race?

File: lib/srv/sess.go [hunk 10]
```diff
@@ -808,30 +645,206 @@ outer:
...
+	}
+
+	// Emit session leave event to Audit Log.
+	if err := s.recorder.EmitAuditEvent(ctx.srv.Context(), sessionLeaveEvent); err != nil {
+		s.log.WithError(err).Warn("Failed to emit session leave event.")
+	}
+
+	// Notify all members of the party that a new member has left over the
+	// "x-teleport-event" channel.
+	for _, p := range s.parties {
```
Comment (r0mant) [inline lib/srv/sess.go:775]: Same as above.

**Review by r0mant — COMMENTED** [review]
Please also add some test coverage.

Also, how did you test this?

File: lib/srv/sess.go (hunk 7 above)
Comment (Joerger) [reply lib/srv/sess.go:1371]: It's called under lock in `emitSessionEndEvent`. I'll move this logic there since it's only called once.

File: lib/srv/sess.go (hunk 6 above)
Comment (Joerger) [reply lib/srv/sess.go:1256]: Thanks for catching this, fixed

**Review by r0mant — APPROVED** [review]

**Comment by Joerger** [comment]
@xacrimon @r0mant Can you re-review/re-approve? I've about doubled the size of the PR in order to incorporate good unit tests, a quick scan will hopefully be sufficient.

BTW Joel you may be able to use the new tests in `sess_test.go` to improve the test coverage of moderated sessions.

**Review by r0mant — APPROVED** [review]

**Review by xacrimon — APPROVED** [review]
