### PR TITLE
Fix http proxy basic auth

### LINKED ISSUE #12481: Corporate proxy authentication issue with tsh
### Discussed in https://github.com/gravitational/teleport/discussions/12408

<div type='discussions-op-text'>

<sup>Originally posted by **Wallerand** May  4, 2022</sup>
Hi everyone!

We successfully installed and configured a Teleport cluster on our external environment that stands outside our main internal network.
Everything works great when we `tsh login` from outside that network, but a "407 Proxy Authentication Required" error occur inside it. Indeed, this network requires to use a corporate http proxy with basic authentication.

To deal with this HTTP proxy and its authentication scheme, we set the http_proxy and https_proxy env variables as follow : `http://username:password@proxy-url:port`.

With this configuration, `tsh` seems to successfully authenticate to the cluster (since it ask for password and can retrieve cluster's config at `/webapi/ping` endpoint), but cannot finish the login process.

Does `tsh` supports the basic proxy authentication scheme ? Is there a workaround available in this situation ?

Thanks for your help 🙏

Please find the complete log below :
```bash
$ tsh login --proxy=teleport.example.com -d
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/teleportuser/.tsh/keys/teleport.example.com/teleportuser-x509.pem" valid until "2022-05-04 19:49:10 +0000 UTC". client/keystore.go:307
DEBU [KEYSTORE]  Reading certificates from path "/home/teleportuser/.tsh/keys/teleport.example.com/teleportuser-ssh/teleport.example.com-cert.pub". client/keystore.go:330
INFO [CLIENT]    no host login given. defaulting to teleportuser client/api.go:1155
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:3137
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/teleportuser/.tsh/keys/teleport.example.com/teleportuser-x509.pem" valid until "2022-05-04 19:49:10 +0000 UTC". client/keystore.go:307
DEBU [KEYSTORE]  Reading certificates from path "/home/teleportuser/.tsh/keys/teleport.example.com/teleportuser-ssh/teleport.example.com-cert.pub". client/keystore.go:330
INFO [KEYAGENT]  Loading SSH key for user "teleportuser" and cluster "teleport.example.com". client/keyagent.go:191
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3102
DEBU             Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:112
Enter password for Teleport user teleportuser:
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3102
DEBU [CLIENT]    HTTPS client init(proxyAddr=teleport.example.com:443, insecure=false) client/weblogin.go:228
DEBU [KEYAGENT]  Adding CA key for teleport.example.com client/keyagent.go:313
DEBU [KEYSTORE]  Adding known host teleport.example.com with proxy teleport.example.com and key: SHA256:[fingerprint] client/keystore.go:578
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/teleportuser/.tsh/keys/teleport.example.com/teleportuser-x509.pem" valid until "2022-05-04 19:49:10 +0000 UTC". client/keystore.go:307
DEBU [KEYAGENT]  Deleting obsolete stored key with index {ProxyHost:teleport.example.com Username:teleportuser ClusterName:teleport.example.com}. client/keyagent.go:514
INFO [KEYAGENT]  Loading SSH key for user "teleportuser" and cluster "teleport.example.com". client/keyagent.go:191
INFO [CLIENT]    Connecting to proxy=teleport.example.com:443 login="root" using TLS Routing client/api.go:2317
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/teleportuser/.tsh/keys/teleport.example.com/teleportuser-x509.pem" valid until "2022-05-04 19:49:53 +0000 UTC". client/keystore.go:307
DEBU [HTTP:PROX] Found proxy "http://username:password@proxy-url:port" in environment, returning proxy dialer. proxy/proxy.go:276

ERROR REPORT:
Original Error: *trace.BadParameterError unable to proxy connection: 407 Proxy Authentication Required
Stack Trace:
        /go/src/github.com/gravitational/teleport/api/client/proxy.go:72 github.com/gravitational/teleport/api/client.DialProxyWithDialer
        /go/src/github.com/gravitational/teleport/api/client/proxy.go:32 github.com/gravitational/teleport/api/client.DialProxy
        /go/src/github.com/gravitational/teleport/lib/utils/proxy/proxy.go:196 github.com/gravitational/teleport/lib/utils/proxy.proxyDial.Dial
        /go/src/github.com/gravitational/teleport/lib/client/api.go:2367 github.com/gravitational/teleport/lib/client.makeProxySSHClientWithTLSWrapper
        /go/src/github.com/gravitational/teleport/lib/client/api.go:2318 github.com/gravitational/teleport/lib/client.makeProxySSHClient
        /go/src/github.com/gravitational/teleport/lib/client/api.go:2290 github.com/gravitational/teleport/lib/client.(*TeleportClient).connectToProxy
        /go/src/github.com/gravitational/teleport/lib/client/api.go:2210 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToProxy.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: unable to proxy connection: 407 Proxy Authentication Required
```</div>

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #12481 

This is for a user's proxy, not to be confused with the teleport proxy. #12481 was a proxy on a corporate network.

A summary of the problem is that we were stripping out the "user:password" portion of the proxy url before dialing the proxy. I changed it to pass the full url to the proxy dialing functions in api/client/proxy.go and added a "Proxy-Authorization: Basic **(base64 encoded user:pass)**" header to the http request we send the proxy.

### CODE REVIEW

**Review by ptgott — APPROVED** [review]

File: api/client/proxy.go [hunk 1]
```diff
@@ -28,23 +29,34 @@ import (
...
+func DialProxyWithDialer(ctx context.Context, proxyURL *url.URL, addr string, dialer ContextDialer) (net.Conn, error) {
+	conn, err := dialer.DialContext(ctx, "tcp", proxyURL.Host)
 	if err != nil {
-		log.Warnf("Unable to dial to proxy: %v: %v.", proxyAddr, err)
+		log.Warnf("Unable to dial to proxy: %v: %v.", proxyURL.Host, err)
 		return nil, trace.ConvertSystemError(err)
 	}
 
+	header := make(http.Header)
+	if proxyURL != nil && proxyURL.User != nil {
```
Comment (r0mant) [inline api/client/proxy.go:45]: @GavinFrazar Is this scenario covered by a test? I didn't see any new tests added. Could you please add a unit test for this case?

**Review by r0mant — COMMENTED** [review]
@smallinsky @EdwardDowling Could you folks take a look too?

File: api/client/proxy.go (hunk 1 above)
Comment (GavinFrazar) [reply api/client/proxy.go:45]: Added parsing tests, but no test with an actual proxy - do you think that's needed as well? I tested manually that it actually works with a squid proxy server set up on my machine, but I'm not sure how I would add that kind of test to our suite.

Comment (smallinsky) [inline api/client/proxy.go:45]: If proxyURL == nil the code will panic in proxyURL.Host reference. Can we extract this check and move at the beginning of this function ?

File: api/client/proxy.go [hunk 2]
```diff
@@ -28,23 +29,34 @@ import (
...
+		// dont use User.String() because it performs url encoding (rfc 1738),
+		// which we don't want in our header
+		creds := proxyURL.User.Username()
+		if password, hasPass := proxyURL.User.Password(); hasPass {
+			creds += ":" + password
```
Comment (smallinsky) [inline api/client/proxy.go:50]: Does there is any difference in handling user without password case 
Namely  we will set basicAuth to "user" where GO https://github.com/golang/go/blob/690ac4071fa3e07113bf371c9e74394ab54d6749/src/net/http/transport.go#L849
in that case adds the ":" token and the end of user (`user:`)    ?

File: api/client/proxy/proxy_test.go [hunk 3]
```diff
@@ -109,14 +110,42 @@ func TestGetProxyAddress(t *testing.T) {
...
 				require.Equal(t, tt.proxyAddr, p.Host)
+				require.Nil(t, p.User)
+			}
+
+			// now reconstruct the env var with user:pass@host, set the env again, and test parsing that
+			expectedUser := "alice"
+			expectedPassword := "password"
+			creds := fmt.Sprintf("%v:%v@", expectedUser, expectedPassword)
+			for _, env := range tt.env {
+				if strings.EqualFold(env.name, "http_proxy") || strings.EqualFold(env.name, "https_proxy") {
```
Comment (smallinsky) [inline api/client/proxy/proxy_test.go:133]: At first glance this look like a separate test case could you extract this logic to a separate test function ? . Also what would you say about reusing `url.Parse` -> `u.String` to set the user and password instead of using "%v" template ?

File: api/client/proxy.go (hunk 1 above)
Comment (smallinsky) [reply api/client/proxy.go:45]: We have severals integration test that leverages the https_proxy env though you will need to add support to `Proxy-Authorization` header.

File: api/client/proxy.go (hunk 2 above)
Comment (GavinFrazar) [reply api/client/proxy.go:50]: Hmm, I went back and forth on this actually. I saw that in User.String() it only adds the ":" if the password is set, so I went with that, but I see they always add it in the code you linked for proxy auth header. Looking at the history for that code, it looks like they used to conditionally add the ":" but changed it to "fix basic authentication", so that must be the right way.

File: api/client/proxy/proxy_test.go (hunk 3 above)
Comment (GavinFrazar) [reply api/client/proxy/proxy_test.go:133]: I wanted to re-use these test cases, that's why I didn't make a separate test function. We can use url.Parse but only when the proxy addr is not in the form `host:port`, as it won't parse correctly as a valid url. I'll update this

File: integration/proxy_test.go [hunk 4]
```diff
@@ -807,5 +809,83 @@ func TestALPNProxyHTTPProxyNoProxyDial(t *testing.T) {
...
+	// proxy url is just the host with no auth credentials
+	t.Setenv("http_proxy", proxyURL.Host)
+	_, err = rc.StartNode(makeNodeConfig("first-root-node", rcProxyAddr))
+	require.Error(t, err)
+	require.ErrorIs(t, ph.LastError(), trace.AccessDenied("missing Proxy-Authorization header"))
+	require.Zero(t, ph.Count())
+
+	// proxy url is user:password@host with incorrect password
+	userPass := url.UserPassword(validUser, "incorrectPassword").String()
+	t.Setenv("http_proxy", fmt.Sprintf("%v@%v", userPass, proxyURL.Host))
```
Comment (smallinsky) [inline integration/proxy_test.go:876]: nit: Can we extract following logic: 
```go
userPass := url.UserPassword(validUser, "incorrectPassword").String()
fmt.Sprintf("%v@%v", userPass, proxyURL.Host))
```
to a function like
```go
func makeProxyAddr(user, pass, host) string {
   userPass := url.UserPassword(user, "incorrectPassword").String()
   return fmt.Sprintf("%v@%v", pass, proxyURL.Host))
}
```

File: integration/helpers.go [hunk 5]
```diff
@@ -1547,15 +1547,76 @@ func startAndWait(process *service.TeleportProcess, expectedEvents []string) ([]
 	return receivedEvents, nil
 }
 
-type proxyServer struct {
+type proxyBasicAuthHandler struct {
```
Comment (smallinsky) [inline integration/helpers.go:1550]: nit: Can we rename this to something like:   basicAuthMiddleware to emphasise that it wraps the proxyHandler ?

**Review by smallinsky — COMMENTED** [review]
Left some nit suggestions

File: integration/helpers.go [hunk 6]
```diff
@@ -1547,15 +1547,76 @@ func startAndWait(process *service.TeleportProcess, expectedEvents []string) ([]
...
+	sync.Mutex
+	lastError error
+	authDB    map[string]string
+	proxyHandler
+}
+
+func (p *proxyBasicAuthHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply integration/helpers.go:1557]: The problem I see with this is that I want to access the state of the proxyBasicAuthHandler. If I follow this suggestion then we could do something like:

```go
	ph := &proxyBasicAuthHandler{authDB: map[string]string{validUser: validPass}}
	wrappedHandler1 := ph.withProxyAuth(&proxyHandler{})
	// ...
	wrappedHandler2 := ph.withProxyAuth(&someOtherHandler{})
	// ...
	// ph.lastError refers to last error from which handler?
```

If I changed it so that the withProxyAuth function did not have a method receiver and instead created a new proxyAuthHandler inside the function, then that would work to prevent this subtle mistake but we would lose access to the struct's state.

I do like how this suggestion decouples proxy auth from a specific handler though. How about this:

```go
type proxyAuthorizer struct {
	next http.Handler
	sync.Mutex
	lastError error
	authDB    map[string]string
}

func NewProxyAuthorizer(handler http.Handler, authDB map[string]string) *proxyAuthorizer {
	return &proxyAuthorizer{next: handler, authDB: authDB}
}

func (p *proxyAuthorizer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	auth := r.Header.Get("Proxy-Authorization")
	if auth == "" {
		err := trace.AccessDenied("missing Proxy-Authorization header")
		p.SetError(err)
		trace.WriteError(w, err)
		return
	}
	user, password, ok := parseProxyAuth(auth)
	if !ok {
		err := trace.AccessDenied("bad Proxy-Authorization header")
		p.SetError(err)
		trace.WriteError(w, err)
		return
	}

	if p.isAuthorized(user, password) {
		p.SetError(nil)
		p.next.ServeHTTP(w, r)
		return
	}

	err := trace.AccessDenied("bad credentials")
	p.SetError(err)
	trace.WriteError(w, err)
}
```

File: api/client/proxy/proxy_test.go [hunk 7]
```diff
@@ -111,12 +117,46 @@ func TestGetProxyAddress(t *testing.T) {
...
+				if tt.proxyAddr == "" {
+					require.Nil(t, p)
+				} else {
+					require.NotNil(t, p)
+					require.Equal(t, tt.proxyAddr, p.Host)
+					require.NotNil(t, p.User)
+					require.Equal(t, expectedUser, p.User.Username())
+					password, _ := p.User.Password()
+					require.Equal(t, expectedPassword, password)
+				}
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply api/client/proxy/proxy_test.go]: I refactored this. I think latest is much easier to reason about. I want to keep the auth test "multiplied" with the existing tests so that each scenario is tested thoroughly.

**Review by smallinsky — APPROVED** [review]

File: api/client/proxy.go [hunk 8]
```diff
@@ -28,23 +29,35 @@ import (
...
+		log.Warnf("Unable to dial to proxy: %v: %v.", proxyURL.Host, err)
 		return nil, trace.ConvertSystemError(err)
 	}
 
+	header := make(http.Header)
+	if proxyURL.User != nil {
+		// dont use User.String() because it performs url encoding (rfc 1738),
+		// which we don't want in our header
+		password, _ := proxyURL.User.Password()
+		creds := proxyURL.User.Username() + ":" + password
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply api/client/proxy.go:52]: That's fine. A little strange to do that, but ":@proxyhost" will still parse correctly and will work if the proxy is configured to accept empty user/password. A single colon is the minimum required by the spec: https://datatracker.ietf.org/doc/html/rfc1945#section-11

[the remark this answers is not in the document]
Comment (r0mant) [reply api/client/proxy.go:52]: Got it, thank you for explanation! A comment might be helpful.

**Review by r0mant — APPROVED** [review]

File: api/client/proxy.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply api/client/proxy.go:52]: Yeah good point, it's not obvious. I'll reference the spec in the comment.

**Comment by webvictim** [comment]
@GavinFrazar I think this needs a backport to `branch/v10` - looks it was merged after the branch was cut so it's not working as expected in 10.0
