### PR TITLE
Fix "tsh app login" prompting for user login when multiple AWS roles are present

### LINKED ISSUE #48715: `tsh apps login` prompt for relogin when multiple cloud identities are available
Expected behavior:
`tsh apps login` should ask for user to pick a cloud identity

```
$ tsh apps login aws-dev-config
Available AWS roles:
Role Name       Role ARN                                       
--------------- ---------------------------------------------- 
does-not-exist  arn:aws:iam::<account-id>:role/does-not-exist  
steve-poweruser arn:aws:iam::<account-id>:role/steve-poweruser 

ERROR: --aws-role flag is required
```

Current behavior:
```
$ tsh apps login aws-dev-config
Available AWS roles:
Role Name       Role ARN                                       
--------------- ---------------------------------------------- 
does-not-exist  arn:aws:iam::<account-id>:role/does-not-exist  
steve-poweruser arn:aws:iam::<account-id>:role/steve-poweruser 

Enter password for Teleport user STeve:
```

Bug details:
- Teleport version: v17.0.0-alpha.2
- Recreation steps: setup AWS app access and grant two AWS roles. 
- Debug logs:
```
2024-11-08T16:07:16-05:00 DEBU [CLIENT]    Activating relogin on error="--aws-role flag is required" (type=*trace.BadParameterError) client/api.go:630
```

### PR DESCRIPTION
**Pull request by greedy52**
changelog: Fix "tsh app login" prompting for user login when multiple AWS roles are present

Fixes #48715
- #48715 

Thanks @codingllama for suggesting the non-retryable error check.

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -796,8 +796,43 @@ func WithMakeCurrentProfile(makeCurrentProfile bool) RetryWithReloginOption {
...
+// NewNonRetryableError wraps an error to indicate that the error should fail
+// IsErrorResolvableWithRelogin. This wrapper is used to workaround the false
+// positives like trace.IsBadParameter check in IsErrorResolvableWithRelogin.
+func NewNonRetryableError(err error) error {
+	return &nonRetryableError{
+		Err: err,
+	}
+}
+
+type nonRetryableError struct {
```
Comment (codingllama) [inline lib/client/api.go:808]: Suggestion: Make the type public and ditch the constructor?

[the remark this answers is not in the document]
Comment (codingllama) [reply lib/client/api.go:808]: lib/client is alright.

File: lib/client/api.go [hunk 2]
```diff
@@ -796,8 +796,43 @@ func WithMakeCurrentProfile(makeCurrentProfile bool) RetryWithReloginOption {
...
+}
+
+func (e *nonRetryableError) Unwrap() error {
+	if e == nil {
+		return nil
+	}
+	return e.Err
+}
+
+func isNonRetryableError(err error) bool {
```
Comment (codingllama) [inline lib/client/api.go:826]: Export and add godocs? We exported the constructor/type (depending on which suggestions you take).

File: lib/client/api.go [hunk 3]
```diff
@@ -796,8 +796,43 @@ func WithMakeCurrentProfile(makeCurrentProfile bool) RetryWithReloginOption {
...
+	}
+}
+
+type nonRetryableError struct {
+	Err error
+}
+
+func (e *nonRetryableError) Error() string {
+	if e == nil || e.Err == nil {
+		return "error"
```
Comment (codingllama) [inline lib/client/api.go:814]: I wonder if this should be just `return ""` - meaning that a nil error is no error. WDYT?

File: lib/client/api_test.go [hunk 4]
```diff
@@ -1365,3 +1375,11 @@ func TestGetTargetNodes(t *testing.T) {
 		})
 	}
 }
+
+func TestNonRetryableError(t *testing.T) {
+	err := NewNonRetryableError(trace.AccessDenied("do not enter"))
+	require.Error(t, err)
+	require.Equal(t, "do not enter", err.Error())
+	require.True(t, isNonRetryableError(err))
+	require.True(t, trace.IsAccessDenied(err))
```
Comment (codingllama) [inline lib/client/api_test.go:1384]: Test the unwrap?

Comment (codingllama) [inline lib/client/api_test.go:1384]: Keep going:

```suggestion
	assert.Equal(t, "do not enter", err.Error())
	assert.True(t, isNonRetryableError(err))
	assert.True(t, trace.IsAccessDenied(err))
```

Also please add error messages to the assertions.

* https://go.dev/wiki/TestComments#keep-going

**Review by codingllama — COMMENTED** [review]
Looks good!

File: lib/client/api.go (hunk 1 above)
Comment (greedy52) [reply lib/client/api.go]: 👍

File: lib/client/api.go (hunk 3 above)
Comment (greedy52) [reply lib/client/api.go]: I changed to empty string. otherwise maybe we can do `return "nil error"` but i like `""` better.

File: lib/client/api_test.go (hunk 4 above)
Comment (greedy52) [reply lib/client/api_test.go]: updated. we should do this more often in our repo.

File: lib/client/api.go [hunk 5]
```diff
@@ -796,8 +796,41 @@ func WithMakeCurrentProfile(makeCurrentProfile bool) RetryWithReloginOption {
...
+
+// Unwrap returns the original error.
+func (e *NonRetryableError) Unwrap() error {
+	if e == nil {
+		return nil
+	}
+	return e.Err
+}
+
+// IsNonRetryableError checks if the provided error is a NonRetryableError.
```
Comment (codingllama) [inline lib/client/api.go:823]: Suggestion:

```suggestion
// IsNonRetryableError checks if the provided error is a NonRetryableError.
// Equivalent to `errors.As(err, new(*NonRetryableError))`.
```

**Review by codingllama — APPROVED** [review]

File: lib/client/api_test.go (hunk 4 above)
Comment (codingllama) [reply lib/client/api_test.go]: For sure.

**Review by gabrielcorado — APPROVED** [review]

**Review by capnspacehook — APPROVED** [review]
