### PR TITLE
Remove `Dialer(client.Config)` from Credential interface

### LINKED ISSUE #30946: Remove `Dialer()` method from `client.Credentials` interface
This method is only implemented for the Profile credential type - it appears at the time it was to support another connection method to the Auth Server - but at a later date, the `proxyConnect` connector was introduced directly into the client to support this connection method.

These are remarkably similar - it would be my estimation that any deviation between the two is likely a bug. I imagine fixes and new features have been added to one implementation and not to the other:
```go
// proxyConnect connects to the Teleport Auth Server through the proxy.
func proxyConnect(ctx context.Context, params connectParams) (*Client, error) {
	if params.sshConfig == nil {
		return nil, trace.BadParameter("must provide ssh client config")
	}
	dialer := NewProxyDialer(*params.sshConfig, params.cfg.KeepAlivePeriod, params.cfg.DialTimeout, params.addr, params.cfg.InsecureAddressDiscovery, WithInsecureSkipVerify(params.cfg.InsecureAddressDiscovery))
	clt := newClient(params.cfg, dialer, params.tlsConfig)
	if err := clt.dialGRPC(ctx, params.addr); err != nil {
		return nil, trace.Wrap(err, "failed to connect to addr %v as a web proxy", params.addr)
	}
	return clt, nil
}

func (c *profileCreds) Dialer(cfg Config) (ContextDialer, error) {
	sshConfig, err := c.SSHClientConfig()
	if err != nil {
		return nil, trace.Wrap(err)
	}

	tlsConfig, err := c.profile.TLSConfig()
	if err != nil {
		return nil, trace.Wrap(err)
	}

	return NewProxyDialer(
		*sshConfig,
		cfg.KeepAlivePeriod,
		cfg.DialTimeout,
		c.profile.WebProxyAddr,
		cfg.InsecureAddressDiscovery,
		WithTLSConfig(tlsConfig),
	), nil
}
```

The implementation of the API client will try both of these if a Profile Credential is provided.

Why remove it?

- The current deviation between the two implementations is likely a bug - and is likely to introduce further bugs in future.
- The existence of `Dialer` on the `client.Credential` interface expands the responsibility of a `client.Credential` to be much more than "just a credential". It makes sense that the matter of dialling the Auth Server would be a responsibility of the client and not the credential.
- Providing a custom Dialer is already possible via the Client configuration itself - having two ways of doing this further complicates the behaviour of the client.

### PR DESCRIPTION
**Pull request by strideynet**
Closes https://github.com/gravitational/teleport/issues/30946

As described in the issue, the goal here is to simplify the client. The current `Dialer` method on the `client.Credential` creates complexity by expanding the responsibilities of `client.Credentials` from merely providing credentials to also orchestrating the dialling process. In combination with the fact a custom dialler can already be provided in `client.Config`, this seems redundant.

The `profileCreds.Dialer` was extremely similar to the existing `proxyConnect` connectFunc, but there is one difference: `WithTLSConfig` was provided as a `DialProxyOption` in `profileCreds.Dialer` method but is not provided by `proxyConnect`. My gut feeling looking through the history of this code is that a bug has been fixed in `proxyConnect` but not fixed within `profileCreds.Dialer`. I'd be curious if @Joerger or @greedy52 have any thoughts on whether or not this `WithTLSConfig` is necessary.

To preserve the behaviour where the Client works without specifying an address for the Profile credential, I've added an additional check for when no addresses are provided to use the address from the Profile. The behaviour has slightly changed, previously (in this case) it would only try `profileCreds.Dialer` - which fails when using TLS multiplexing - and now it will try all connection methods. This means it should work better out of the box with the examples we've given in docs.

Whilst this PR alone does not seem to achieve much - it sets the foundation for a future PRs which will aim clarify the role of `client.Credential` as a credential source rather than a configuration source which in turn sets the foundation for simplifying and extending the internals of `api.Client`.

changelog: Removes the `Dialer` method from `client.Credential`. Instead use `client.Config.Dialer` to override the connection method used by the client.

### CODE REVIEW

File: api/client/credentials.go [hunk 1]
```diff
@@ -313,28 +291,6 @@ type profileCreds struct {
...
-		return nil, trace.Wrap(err)
-	}
-
-	return NewProxyDialer(
-		*sshConfig,
-		cfg.KeepAlivePeriod,
-		cfg.DialTimeout,
-		c.profile.WebProxyAddr,
-		cfg.InsecureAddressDiscovery,
-		WithTLSConfig(tlsConfig),
```
Comment (greedy52) [inline api/client/credentials.go:334]: On this topic, the WithTLSConfig was added in https://github.com/gravitational/teleport/pull/22439 to support HTTPS_PROXY, and this TLS config shouldn't be used anywhere else. 

cc @atburke 

My understanding is there is no need to pass a full TLS config for HTTPS_PROXY. It doesn't make sense to me to pass custom cert or cas when dialing the proxyURL, and toggling insecure is probably enough here.

**Review by greedy52 — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]

File: api/client/client.go [hunk 2]
```diff
@@ -272,21 +272,28 @@ func connect(ctx context.Context, cfg Config) (*Client, error) {
...
-				syncConnect(ctx, dialerConnect, connectParams{
-					cfg:       cfg,
-					tlsConfig: tlsConfig,
-					dialer:    dialer,
+			addrs := cfg.Addrs
+			if len(addrs) == 0 {
+				// If there's no explicitly specified address, fall back to
+				// an address provided by the credential, if it provides one.
+				credAddrSource, ok := creds.(interface {
+					ProxyWebAddr() (string, error)
```
Comment (Joerger) [inline api/client/client.go:280]: suggestion: It might be worth generalizing this to just `GetDefaultAddrs` and adding it to some exported interface, like `CredentialsWithDefaultAddrs`. This is still intended as an external client which we'd want to standardize and make easy to use for external developers. Someone may for example want to create a credential type that returns an auth addr stored in some file in some file.

File: api/client/client.go [hunk 3]
```diff
@@ -272,21 +272,28 @@ func connect(ctx context.Context, cfg Config) (*Client, error) {
...
 				})
+				if ok {
+					addr, err := credAddrSource.ProxyWebAddr()
+					if err != nil {
+						sendError(trace.Wrap(err))
+						continue
+					}
+					addrs = []string{addr}
```
[the remark this answers is not in the document]
Comment (strideynet) [reply api/client/client.go:288]: > A minor downside to this approach is that we are now trying to connect to what we know is a proxy address as an

I'm actually not entirely convinced that this is a downside. When I tried connecting using just the Profile Credential dialer to my cluster, which is a fairly out of the box TLS routing enabled cluster, this failed. The type of dialer that the credential uses requires that the cluster has a separate or multiplexed SSH port (not just ALPN routed). Since switching to my implementation, the address and credentials sourced from the Profile can be used with a different technique and can connect succesfully.

File: api/client/client.go (hunk 2 above)
Comment (strideynet) [reply api/client/client.go:280]: Sure - I can implement that.

Comment (strideynet) [reply api/client/client.go]: 17c46eaa7b9d19174c54505576b222849ed0154c

File: api/client/client.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (Joerger) [reply api/client/client.go]: > When I tried connecting using just the Profile Credential dialer to my cluster, which is a fairly out of the box TLS routing enabled cluster, this failed. The type of dialer that the credential uses requires that the cluster has a separate or multiplexed SSH port (not just ALPN routed). Given the fairly common/standard setup that my cluster uses, I'm lead to believe that using the Profile credential with no explicitly specified address probably doesn't work for most customers anyway.

Well that sounds like a bug :smile: the profile credentials definitely should have worked out of the box, but I agree trying all methods is fine and potentially avoids pigeon-holing us.

**Review by Joerger — APPROVED** [review]

**Review by ryanclark — APPROVED** [review]
LGTM after `GetDefaultAddrs` -> `DefaultAddrs`

**Comment by Joerger** [comment]
@strideynet I'm getting this error when providing minimal client config, aka just the profile - `must provide Dialer or Addrs in config`

**Comment by strideynet** [comment]
> @strideynet I'm getting this error when providing minimal client config, aka just the profile - must provide Dialer or Addrs in config

Do you have a repro ? I've just tested again and this is working

**Comment by Joerger** [comment]
@strideynet I must have misconfigured something myself, apologies
