### PR TITLE
Forward flags to "tsh ssh" and "tsh aws"

### LINKED ISSUE #15965: `tsh aws` no longer accepts flags (e.g `--<flag>`) to forward to AWS CLI
Expected behavior:
`tsh aws s3 ls --page-size 5` should run.

Current behavior:
```
 $ tsh aws s3 ls --page-size 5
ERROR: unknown long flag '--page-size'
```

In fact this applies to any flag.

Bug details:
A recent change `Interspersed` to `true`  forces flags to be evaluated by tsh instead of forwarding to AWS CLI
https://github.com/gravitational/teleport/blob/6bf2f18435f12a5733b95b727473ab2be06c1ad9/tool/tsh/tsh.go#L502

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #15965 #16044
- #15965
- #16044

## Root cause
A recent change set our kingpin app to `Interspersed(true)` causing all flags to be evaluated as tsh flags.
https://github.com/gravitational/teleport/blob/bf67d200a8d7cc2fddf37423b52913b5112c33cb/tool/tsh/tsh.go#L502

Instead of reverting this, a new kingpin feature is added in (https://github.com/gravitational/kingpin/pull/9) to allow an individual command to set `Interspersed(false)` so all flags are parsed as part of the `StringsVar` args so they can be forwarded to SSH or AWS CLI.

## Testing
- `$ tsh aws s3 ls --page-size 5`
- `$ rsync -e 'tsh ssh' tsh.go root@proxy:tsh.go`

### CODE REVIEW

File: tool/tsh/aws_test.go [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+}
+
+func makeUserWithAWSRole(t *testing.T) (types.User, types.Role) {
+	alice, err := types.NewUser("alice@example.com")
+	require.NoError(t, err)
+
+	awsRole, err := types.NewRoleV3("aws", types.RoleSpecV5{
+		Allow: types.RoleConditions{
+			AppLabels: types.Labels{
+				"*": apiutils.Strings{"*"},
```
Comment (smallinsky) [inline tool/tsh/aws_test.go:124]: nit:
```suggestion
				types.Wildcard: apiutils.Strings{types.Wildcard},
```

**Review by smallinsky — APPROVED** [review]
Thanks for adding test coverage for this flow. 
LGTM.

**Review by Tener — APPROVED** [review]
