### PR TITLE
Determine node registration method based on server port

### LINKED ISSUE #4663: Disturbing error message when running the install-node script
When running the auto-install script, I see the following errors:

```bash
INFO [PROC]      Generating new host UUID: 8a2ff5e7-f8af-43f4-a9b3-d6b059877a1f. service/service.go:576
INFO [PROC:1]    Joining the cluster with a secure token. service/connect.go:349
ERRO [AUTH]      Failed to register through auth server: invalid character '<' looking for beginning of value; falling back to trying the proxy server auth/register.go:126
INFO [PROC]      Node has obtained credentials to connect to cluster. service/connect.go:377
```

> ERRO [AUTH]      Failed to register through auth server: invalid character '

Gus thinks that it's connecting to an auth server and if it gets a web response it logs that error and tries the proxy mode connection instead which is expected behavior.

If this error is expected behavior, we need to change it to INFO and provide a better message then  `invalid character '<' looking for beginning of value; falling back to trying the proxy server auth/register.go:126` as this is the first thing a user sees when trying out Teleport cloud.

### PR DESCRIPTION
**Pull request by andrejtokarcik**
Even though I haven't managed to reproduce the exact error, this PR should fix #4663. Instead of just changing the log-level or wording of the offending message, the logic of `Register` is adapted so that it attempts the proxy mode connection first in case the first auth server to connect to is specified with port `defaults.HTTPListenPort` (= 3080).

```
DEBU [AUTH]      Registering node to the cluster. auth-servers:[{127.0.0.1:5008 tcp }] auth/register.go:112
INFO [AUTH]      Attempting registration with auth server. auth/register.go:132
DEBU [AUTH]      Registration with auth server failed. error:"404 page not found\n" auth/register.go:136
INFO [AUTH]      Attempting registration via proxy server. auth/register.go:132
[...]
INFO [AUTH]      Successfully registered via proxy server. auth/register.go:139
```

### CODE REVIEW

File: lib/auth/register.go [hunk 1]
```diff
@@ -109,37 +109,48 @@ func Register(params RegisterParams) (*Identity, error) {
...
 		}
-
-		log.Debugf("Successfully registered through proxy server.")
-		return ident, nil
 	}
 
-	log.Debugf("Successfully registered through auth server.")
-	return ident, nil
+	aggregateErr := trace.NewAggregate(collectedErrs...)
+	log.WithError(aggregateErr).Errorf("Failed to register with the cluster.")
```
Comment (andrejtokarcik) [inline lib/auth/register.go:148]: This may be actually unnecessary since the `aggregateErr` error is reported anyway when returned.

File: lib/auth/register.go [hunk 2]
```diff
@@ -109,37 +109,48 @@ func Register(params RegisterParams) (*Identity, error) {
...
-			log.Debugf("Missing client, failing with error from Auth Server: %v.", err)
-			return nil, trace.Wrap(err)
-		}
-
-		log.Errorf("Failed to register through auth server: %v; falling back to trying the proxy server", err)
+	type registerMethod struct {
+		call func(token string, params RegisterParams) (*Identity, error)
+		desc string
+	}
+	registerThroughAuth := registerMethod{registerThroughAuth, "to auth server"}
```
Comment (webvictim) [inline lib/auth/register.go:116]:
```suggestion
	registerThroughAuth := registerMethod{registerThroughAuth, "with auth server"}
```

File: lib/auth/register.go [hunk 3]
```diff
@@ -109,37 +109,48 @@ func Register(params RegisterParams) (*Identity, error) {
...
+	registerThroughProxy := registerMethod{registerThroughProxy, "through proxy server"}
```
Comment (webvictim) [inline lib/auth/register.go:117]:
```suggestion
	registerThroughProxy := registerMethod{registerThroughProxy, "via proxy server"}
```

File: lib/auth/register.go [hunk 4]
```diff
@@ -109,37 +109,48 @@ func Register(params RegisterParams) (*Identity, error) {
...
+
+	var registerMethods []registerMethod
+	if params.GetHostCredentials == nil {
+		log.Debugf("Missing client, it is not possible to register through proxy.")
+		registerMethods = []registerMethod{registerThroughAuth}
+	} else if params.Servers[0].Port(0) == defaults.HTTPListenPort {
+		log.Debugf("The first specified auth server seems to be in fact a proxy.")
```
Comment (webvictim) [inline lib/auth/register.go:124]:
```suggestion
		log.Debugf("The first specified auth server appears to be a proxy.")
```

**Review by webvictim — COMMENTED** [review]
nit: couple of grammar fixes

File: lib/auth/register.go [hunk 5]
```diff
@@ -109,37 +109,48 @@ func Register(params RegisterParams) (*Identity, error) {
...
+		desc string
+	}
+	registerThroughAuth := registerMethod{registerThroughAuth, "to auth server"}
+	registerThroughProxy := registerMethod{registerThroughProxy, "through proxy server"}
+
+	var registerMethods []registerMethod
+	if params.GetHostCredentials == nil {
+		log.Debugf("Missing client, it is not possible to register through proxy.")
+		registerMethods = []registerMethod{registerThroughAuth}
+	} else if params.Servers[0].Port(0) == defaults.HTTPListenPort {
```
Comment (a-palchikov) [inline lib/auth/register.go:123]: Is there any validation of `RegisterParams` taking place prior to this? How do we know `params.Servers` is valid?
I'd even wrap this in a readable query:
```go
} else if authServerIsProxy(params) {
```

Comment (andrejtokarcik) [reply lib/auth/register.go]: You seem to be correct that `params.Servers` shouldn't be assumed to be valid at this point since `registerThroughProxy` actually checks `len(params.Servers)` as well. Updated the code, thanks!

File: lib/auth/register.go [hunk 6]
```diff
@@ -109,37 +109,51 @@ func Register(params RegisterParams) (*Identity, error) {
...
+	type registerMethod struct {
+		call func(token string, params RegisterParams) (*Identity, error)
+		desc string
+	}
+	registerThroughAuth := registerMethod{registerThroughAuth, "with auth server"}
+	registerThroughProxy := registerMethod{registerThroughProxy, "via proxy server"}
+
+	var registerMethods []registerMethod
+	if params.GetHostCredentials == nil {
+		log.Debugf("Missing client, it is not possible to register through proxy.")
```
Comment (a-palchikov) [inline lib/auth/register.go:121]: This sounds like a warning to me unless this is customary to have no client set, I'd hint at this if this is in fact noteworthy (`log.Warn`).

File: lib/auth/register.go [hunk 7]
```diff
@@ -109,37 +109,51 @@ func Register(params RegisterParams) (*Identity, error) {
...
+		registerMethods = []registerMethod{registerThroughAuth}
+	} else if authServerIsProxy(params) {
+		log.Debugf("The first specified auth server appears to be a proxy.")
+		registerMethods = []registerMethod{registerThroughProxy, registerThroughAuth}
+	} else {
+		registerMethods = []registerMethod{registerThroughAuth, registerThroughProxy}
```
Comment (a-palchikov) [inline lib/auth/register.go:127]: nit: I'd make this the default and avoid another else branch.

File: lib/auth/register.go [hunk 8]
```diff
@@ -109,37 +109,51 @@ func Register(params RegisterParams) (*Identity, error) {
...
-		return ident, nil
 	}
+	return nil, trace.NewAggregate(collectedErrs...)
+}
 
-	log.Debugf("Successfully registered through auth server.")
-	return ident, nil
+// authServerIsProxy returns true if the first specified auth server
+// to register with appears to be a proxy.
+func authServerIsProxy(params RegisterParams) bool {
```
Comment (a-palchikov) [inline lib/auth/register.go:151]: Provide as little context as necessary for this to work - e.g. instead of the whole params value, pass just the servers slice.

**Review by a-palchikov — COMMENTED** [review]
It would be worth testing these with a corresponding unit/integration test if there's none.

File: lib/auth/register.go (hunk 6 above)
Comment (andrejtokarcik) [reply lib/auth/register.go:121]: FWIW, this was a debug level message in the original code as well. The missing `GetHostCredentials` just causes the proxy registration method to be not considered as viable while the other pathway remains untouched by this. Therefore it doesn't seem reasonable to clutter the log with warnings saying "not possible to register through proxy" when there needed to be no intent of going through proxy at all in the first place.

File: lib/auth/register.go [hunk 9]
```diff
@@ -109,37 +109,51 @@ func Register(params RegisterParams) (*Identity, error) {
...
+		log.Debugf("Attempting registration %s.", method.desc)
+		ident, err := method.call(token, params)
 		if err != nil {
-			return nil, trace.Wrap(err, "failed to register through proxy server: %v", err)
+			collectedErrs = append(collectedErrs, err)
+			log.WithError(err).Debugf("Registration %s failed.", method.desc)
+			if i+1 < len(registerMethods) {
+				log.Infof("Unable to register %s, falling back to registration %s.",
+					method.desc, registerMethods[i+1].desc)
+			}
```
Comment (awly) [inline lib/auth/register.go:140]: nit: `continue` here and remove the `else` branch

Comment (awly) [inline lib/auth/register.go:140]: optional: I'd make the first log `Infof` and remove the conditional log

**Review by awly — APPROVED** [review]

**Comment by andrejtokarcik** [comment]
The integration test turned out to require some more involved changes so I'm going to submit it as a separate PR.

**Comment by webvictim** [comment]
@andrejtokarcik Could we get this PR backported to `branch/5.0` please? This will make sure that we get the fix out in Teleport 5.1.1.

File: lib/auth/register.go [hunk 10]
```diff
@@ -110,37 +110,47 @@ func Register(params RegisterParams) (*Identity, error) {
...
 	}
+	return nil, trace.NewAggregate(collectedErrs...)
+}
 
-	log.Debugf("Successfully registered through auth server.")
-	return ident, nil
+// authServerIsProxy returns true if the first specified auth server
+// to register with appears to be a proxy.
+func authServerIsProxy(servers []utils.NetAddr) bool {
+	return len(servers) > 0 && servers[0].Port(0) == defaults.HTTPListenPort
```
Comment (russjones) [inline lib/auth/register.go:149]: We should also check for 443 here.

Comment (webvictim) [reply lib/auth/register.go:149]: That's basically the whole ball game as it's very common to use a load balancer to forward 443 -> 3080.

Comment (andrejtokarcik) [reply lib/auth/register.go:149]: Implemented in #5600.
