### PR TITLE
Emit the correct session ID for SessionLeave events

### LINKED ISSUE #9574: Teleport emits the wrong session ID for session.leave events
### Description

**What happened**:

When a user leaves an SSH session, the `session.leave` event incorrectly uses the user's "party" ID as the session ID.

**What you expected to happen**:

The session ID in the `session.leave` event should match the session ID in the `session.start` and `session.end` events.

image

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Start an SSH session via the web UI or `tsh`
2. End the session
3. Observe the audit log

Note: this but does not occur for BPF sessions - they use the correct session ID.

I'm running off a recent commit but this bug looks to have been introduced many years ago in https://github.com/gravitational/teleport/commit/876e04af07f38b270575220fddaf14a18f78c1a9.

### PR DESCRIPTION
**Pull request by zmb3**
Fixes #9574

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -485,7 +485,7 @@ func testAuditOn(t *testing.T, suite *integrationTestSuite) {
 			start := findByType(events.SessionStartEvent)
 			require.Equal(t, first, start)
 			require.Equal(t, 0, start.GetInt("bytes"))
-			require.NotEmpty(t, start.GetString(events.SessionEventID))
+			require.Equal(t, string(sessionID), start.GetString(events.SessionEventID))
```
Comment (jimbishopp) [inline integration/integration_test.go:488]: nit: _not really related to this fix_, but it's strange that this test creates a `sessionID` variable from `session.ID` and then uses a mix of both throughout.

**Review by jimbishopp — APPROVED** [review]

File: integration/integration_test.go (hunk 1 above)
Comment (zmb3) [reply integration/integration_test.go:488]: Yeah, at some point we should use the `session.ID` type everywhere. There's still a fair amount of code that expects a string instead, which results in a bunch of conversions back and forth.

**Review by espadolini — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
