### PR TITLE
Use concurrent streams for SFTP connections

### LINKED ISSUE #20579: Massive degradation of performance in scp performance in Teleport 11 vs Teleport 10.
Observed Behavior:

I'm seeing a massive degradation in sftp performance with Teleport 11 vs what was seen with scp in prior releases.

For one session 'tsh scp' gets 220kbs transfer rates

If I use the local ssh connection (via -Llocalhost:2022:localhost:22 I get 100mbps transfer rates, multiple orders of magnitude different.

This is a massive performance degradation over what was seen before with SCP.

CPU and IO are not bound on the teleport server so I do not understand this degradation without it being a bug.

This test was repeated with same results with sender, receiver, and teleport server all running 11.2.2 

Traffic is normal.  I have 5GBPS ingres/egres through AWS.   Target sites have varying infrastructure but I could and did easily saturate an edge DSL link using sftp on Teleport 10.

Pushing (large)  artifacts (no, we cannot pull)  used to take seconds and now ETA is in hours (!!).

tsh scp TO the teleport server is fast, 20MB a second  within AWS, rate limit is write to disk.
tsh scp THROUGH the teleport server to another device in AWS falls to 5-10mb/s.

tcsh scp outside of AWS falls to kbps range no matter the target.  Prior performance for nodes on well-connected networks was write to disk speeds, up to 100mBps (800mbps).  I used to be able to saturate AWS egres with teleport. 

In all cases performance is much worse than it was with old obsolete SCP.

In all cases performance is almost two orders of magnitude slower than using scp with the edge device sshd via port redirection.

It seems that sftp performance is dependent on available CPU on the RECIPIENT node.

Expected behavior:

tsh scp (really tftp) should be as fast as running scp through a teleport connection using ssh tunneling.

How to test:

Send large files greater than 1GB in size to a client on another network over multiple network hops via 'tsh scp'.
Compare to sending that same vile using 'tsh ssh -Llocalhost:2222:localhost:22'

The transfer rates should be the same.

### PR DESCRIPTION
**Pull request by jakule**
Our current SFTP implementation uses a single channel to transfer data. Connections with a high latency cause very slow transfer. `github.com/pkg/sftp` allows transferring data using concurrent streams, which seems to solve the problem. In order to utilize the feature, the remote file must implement the `WriteTo()` or `ReadFrom()` and `Stat()` methods. I've moved the progress bar to relay the data from a local file, as we can still call `Read()` or `Write()` on it to update the progress.

This PR doesn't address the high CPU usage by `github.com/pkg/sftp` on low latency links.

Closes https://github.com/gravitational/teleport/issues/20579

### CODE REVIEW

File: lib/sshutils/sftp/sftp.go [hunk 1]
```diff
@@ -423,6 +425,49 @@ func (c *Config) transferFile(ctx context.Context, dstPath, srcPath string, srcF
 	return nil
 }
 
+// assertStreamsType checks if reader or writer implements correct interface to utilize concurrent SFTP streams.
+func assertStreamsType(reader io.Reader, writer io.Writer) error {
+	_, okReader := reader.(io.WriterTo)
+	_, okWriter := writer.(io.ReaderFrom)
+
+	if !okWriter && !okReader {
```
Comment (r0mant) [inline lib/sshutils/sftp/sftp.go:433]: Should this be "or" or is it ok for just one of them to implement it?
```suggestion
	if !okWriter || !okReader {
```

Comment (jakule) [reply lib/sshutils/sftp/sftp.go:433]: Just one needs to implement it. If we copy a file from local to remote, then `remote`(writer) needs to implement `io.ReadFrom` interface. The local side won't, as we need to call `Read/Write` to get the progress bar. Copying from remote to local has reverted conditions. I know this is super confusing, but I've no better idea how to assert this. Go sftp doesn't enforce any type, just do a few runtime checks on copy, and if "by mistake" all interfaces are implemented, it will allow concurrent copy.

**Review by gzdunek — COMMENTED** [review]
I tested it in Connect and works fine.

**Review by gzdunek — APPROVED** [review]
(for Connect part)

File: lib/sshutils/sftp/utils.go [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+// cancelReaderWriter implements io.ReadWriter interface with context cancellation.
+type cancelReaderWriter struct {
+	ctx context.Context
+}
+
+func (c *cancelReaderWriter) Read(_ []byte) (int, error) {
+	if err := c.ctx.Err(); err != nil {
+		return 0, err
+	}
+	return 0, nil
```
Comment (capnspacehook) [inline lib/sshutils/sftp/utils.go:89]: Why are you returning `0, nil` here? It is allowed but discouraged in the `io.Reader` docs. Are you trying to tell the caller that nothing occured as suggested in the `io.Reader` docs?

**Review by capnspacehook — APPROVED** [review]

File: lib/sshutils/sftp/sftp.go [hunk 3]
```diff
@@ -423,6 +425,49 @@ func (c *Config) transferFile(ctx context.Context, dstPath, srcPath string, srcF
...
+		}
+	} else {
+		streams := make([]io.Reader, 0, 2)
+		streams = append(streams, canceler)
+
+		if progressBar != nil {
+			streams = append(streams, progressBar)
+		}
+
+		reader = &fileStreamReader{
```
[the remark this answers is not in the document]
Comment (jakule) [reply lib/sshutils/sftp/sftp.go:462]: `io.MultiReader` doesn't implement `Stat()`, which is needed to enable the concurrent read/write.
https://github.com/pkg/sftp/blob/2489717da0f32a7b2ce70af9b1063dd40138fa81/client.go#L1791-L1795

File: lib/sshutils/sftp/utils.go (hunk 2 above)
Comment (jakule) [reply lib/sshutils/sftp/utils.go:89]: I was also thinking about it, but this function is broken by design. First of all, it never returns `io.EOF`. I can return `len(n)`, but I don't think this will change anything.

Comment (jakule) [reply lib/sshutils/sftp/utils.go:89]: More I think about it, more I think we should "wrap" a real stream in this canceler instead of using `MultiRead`/`MultiWrite` to enable cancelation.

Comment (capnspacehook) [reply lib/sshutils/sftp/utils.go:89]: What advantage does that have?

Comment (jakule) [reply lib/sshutils/sftp/utils.go:89]: API can return correct values. Currently, `cancelReaderWriter` never returns `EOF` as it doesn't know how long the stream is. If you embed another stream that returns `EOF`, you can propagate the values from that stream. Also, that solves the issue with returned "read bytes".

**Review by r0mant — APPROVED** [review]
