### PR TITLE
Connect login form: Refocus password field on submission error

### LINKED ISSUE #54508: Login form in Connect loses focus after entering incorrect password
It used to be that after entering an incorrect password, the focus would be back on the password field and you could quickly re-type the password. However, after #47883 the form loses focus and you have to either click on the field or press Shift + Tab then Tab, alternatively Tab then Shift + Tab.

So not only it's super irritating because you cannot just re-type the password, but also if you want to keep using the keyboard you have to shift focus twice. For some reason, the app acts as if the field was blurred, so you cannot simply press Tab to bring focus back – you always have to first focus on another element and then bring the focus back to the password field. 😠

### PR DESCRIPTION
**Pull request by ravicious**
Closes #54508.

To understand the fix, one first must understand how it worked before. I assumed that some normal browser behavior caused it to work, but that's not the case.

Prior to #47883, upon submission the form would immediately switch to the next "step", before a response from the login attempt even arrived. When the response arrived with an error, the form would go back to the previous step, thus re-firing all effects, including the one that would focus the password field.

https://github.com/gravitational/teleport/blob/33f2bbf360f7ee905ca9aee50082c0257244cc62/web/packages/teleterm/src/ui/ClusterConnect/ClusterLogin/FormLogin/FormLocal/FormLocal.tsx#L44-L46

<details>
https://github.com/user-attachments/assets/d834a228-65d3-4fbb-9cb8-fdf636e1b41e
</details>

After the cleanup from #47883, the form doesn't go into the next step immediately on submission. Instead it disables the fields and shows a progress bar. When an error response arrives, it enables the fields, but the focus is no longer on the form itself. The focus effects do not fire because their deps haven't changed.

<details>
https://github.com/user-attachments/assets/114d00f1-51b9-4a7a-babf-dfd3fc3993c4
</details>

The fix is to include the state of the form submission in the value that decides whether a particular field should be focused or not.

<details>
https://github.com/user-attachments/assets/df1c89fd-d793-4f34-81a9-4570f9f30dd3
</details>

I'm still not sure if regular forms lose focus on submission as well, or if the need to trigger those focus effects comes from the same place that the need to use `useRefAutoFocus` instead of `autoFocus`.

### CODE REVIEW

File: web/packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.ts [hunk 1]
```diff
@@ -24,6 +24,10 @@ import { DependencyList, MutableRefObject, useEffect, useRef } from 'react';
  */
 export function useRefAutoFocus<T extends { focus(): void }>(options: {
   shouldFocus: boolean;
+  /**
+   * @deprecated Include items from refocusDeps into the calculation of shouldFocus instead.
+   * The list of useEffect deps should be statically known.
+   */
   refocusDeps?: DependencyList;
```
Comment (ravicious) [inline web/packages/shared/hooks/useRefAutoFocus/useRefAutoFocus.ts:31]: I added this because arguably it's incompatible with hooks are "supposed to" be used.

In this specific scenario, it was easy to avoid using `refocusDeps` by just adding another comparison when constructing the value for `shouldFocus`. However, there are other places where we use this hook where this might be harder. For example:

https://github.com/gravitational/teleport/blob/f59fcb72ba5e22fd56edfeddeea7f66ca94e3ef7/web/packages/teleport/src/components/NewMfaDeviceForm/NewMfaDeviceForm.tsx#L89-L92

Here the callsite would like to retrigger focus when `mfaType.value` changes, which necessitates tracking the previous value of it, something like in ["Adjusting some state when a prop changes"](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes). Maybe there are some other ways to address this but nothing comes to my mind at the moment.

**Review by gzdunek — APPROVED** [review]
Works great 👍

**Review by ryanclark — APPROVED** [review]
