### PR TITLE
limit desktop discovery to IPv4 addresses

### LINKED ISSUE #28635: desktop discovery bug with some ipv6 (invalid port)
Expected behavior:
parse correctly ipv6 address

Current behavior:

some ipv6 address are wrongly parsed with "invalid port"

Bug details:
teleport version : 13.1.5

not working

```
2023-07-04T14:31:23+02:00 DEBU [WINDOWS_D] resolved yyyyy.domain.com => [2b0b:1581::3c 192.168.0.1] pid:9474.1 desktop/discovery.go:219
2023-07-04T14:31:23+02:00 WARN [WINDOWS_D] could not create Windows Desktop from LDAP entry: failed to parse "tcp://2a0b:1581::3c": parse "tcp://2b0b:1581::3c": invalid port ":3c" after host pid:9474.1 desktop/discovery.go:126
2023-07-04T14:31:23+02:00 DEBU [WINDOWS_D] resolved xxxx.domain.com => [2b0b:1581::3d 192.168.0.2] pid:9474.1 desktop/discovery.go:219
2023-07-04T14:31:23+02:00 WARN [WINDOWS_D] could not create Windows Desktop from LDAP entry: failed to parse "tcp://2a0b:1581::3d": parse "tcp://2b0b:1581::3d": invalid port ":3d" after host pid:9474.1 desktop/discovery.go:126
```

working

```
DEBU [WINDOWS_D] resolved server3.domain.com => [2b0b:1581::44 192.168.0.3] pid:10055.1 desktop/discovery.go:219
```

### PR DESCRIPTION
**Pull request by zmb3**
Fixes #28635

### CODE REVIEW

File: lib/srv/desktop/discovery.go [hunk 1]
```diff
@@ -185,19 +186,32 @@ func (s *WindowsService) applyLabelsFromLDAP(entry *ldap.Entry, labels map[strin
...
-		return addrs, nil
+		return stringAddrs(addrs), nil
 	}
 	if s.dnsResolver == nil {
 		return nil, trace.NewAggregate(err, trace.Errorf("DNS lookup for %q failed and there's no LDAP server to fallback to", hostname))
 	}
-	s.cfg.Log.WithError(err).Debugf("DNS lookup for %q failed, falling back to LDAP server", hostname)
-	return s.dnsResolver.LookupHost(ctx, hostname)
+	s.cfg.Log.Debugf("DNS lookup for %q failed, falling back to LDAP server", hostname)
+	addrs, err = s.dnsResolver.LookupNetIP(ctx, "ip4", hostname)
```
Comment (ibeckermayer) [inline lib/srv/desktop/discovery.go:209]: Do you know why we pass the context with the timeout above, but the passed context without the timeout here?

**Review by ibeckermayer — APPROVED** [review]

File: lib/srv/desktop/discovery.go (hunk 1 above)
Comment (zmb3) [reply lib/srv/desktop/discovery.go:209]: I think the idea was if the default resolver times out, then `tctx` would have alreayd expired and this would be guaranteed to fail.

Comment (ibeckermayer) [reply lib/srv/desktop/discovery.go:209]: Makes sense, do we perhaps want to create another timeout-context here?

**Review by camscale — COMMENTED** [review]
The linked bug has an expected behaviour of "parse correctly ipv6 address", but this PR removes any parsing of ipv6 at all. Can we really say this PR fixes the bug? I think this could be fixed and still work with IPv6 by putting square brackets around an IPv6 address so that the colons within are not interpreted as a port separator, as suggested in the code comment.

What do you think?

File: lib/srv/desktop/discovery.go [hunk 2]
```diff
@@ -185,19 +186,32 @@ func (s *WindowsService) applyLabelsFromLDAP(entry *ldap.Entry, labels map[strin
...
-func (s *WindowsService) lookupDesktop(ctx context.Context, hostname string) (addrs []string, err error) {
+func (s *WindowsService) lookupDesktop(ctx context.Context, hostname string) ([]string, error) {
 	tctx, cancel := context.WithTimeout(ctx, 10*time.Second)
 	defer cancel()
 
-	addrs, err = net.DefaultResolver.LookupHost(tctx, hostname)
+	stringAddrs := func(addrs []netip.Addr) []string {
+		result := make([]string, 0, len(addrs))
+		for _, addr := range addrs {
+			result = append(result, addr.String())
```
[the remark this answers is not in the document]
Comment (camscale) [reply lib/srv/desktop/discovery.go:196]: oh, and you need to change `"ip4"` to `"ip"` when you do the lookup too.

[the remark this answers is not in the document]
Comment (camscale) [reply lib/srv/desktop/discovery.go:196]: Further info: https://en.wikipedia.org/wiki/IPv6_address#Literal_IPv6_addresses_in_network_resource_identifiers

**Comment by zmb3** [comment]
The linked bug also showed that both an ipv4 and ipv6 address were resolved for the same host, meaning this will work just fine for them. 

Given that we have never supported ipv6, that's a larger feature request that would require more thorough testing (our parsing functions don't handle it correctly, our RDP library may need to be updated, etc)

The team does not have the bandwidth to develop and test IPv6 at this time, so I'm going with the low risk and quick fix.

**Comment by aderumier** [comment]
Hi, I'm the bug reporting.
This seem to be really a parsing problem, and it's working randomly. 
All my windows are have dual stack ipv4/ipv6,  and some of them are detect with ipv4,  other with ipv6,  and some of them return this error, with the port detected in ip.

image

I don't have any problem with ipv6 detected hosts (rdp session works fine)



(personnaly, I don't care if it's only work with ipv4, but I hope that some users are not only using ipv6)

**Review by nklaassen — APPROVED** [review]

**Review by camscale — APPROVED** [review]
