### PR TITLE
Fix key attestation error on `tsh login`

### LINKED ISSUE #20312: `e/tsh login` occasionally fails with key attestation error
When using Teleport Enterprise edition, `tsh login` will sometimes fail with a cryptic error about key attestation:

```
$ tsh logout; tsh login --proxy=zarquon --user=llama
> Logged out all users from all proxies.
> Enter password for Teleport user llama:
> Tap any security key
> ERROR: special characters are not allowed in resource names, please use name composed only from characters, hyphens, dots, and plus signs: "/key_attestations/SHA256:8L0QeXzd6Jx9TtgI9//th8tGIhcUHYodtvcwSunjVro"
```

This occurs when Teleport tries to hash a public key and check for key attestation data in the backend, but the hash contains "//", which is a forbidden character pattern for backend keys.

### PR DESCRIPTION
**Pull request by Joerger**
This PR changes key attestation logic to:
 - Only check for valid key attestation data when there is a required private key policy. This prevents unnecessary roundtrips to the backend.
 - Use Raw URL base64 encoding of Public Key DER form, instead of Standard base64 encoding of SSH public key.
   - Raw URL encoding Removes the possibility of public key fingerprint containing "//", which is a forbidden pattern for backend keys
   - Removes unnecessary conversions of public key format
   - `GetKeyAttestationData` will fallback to the old fingerprint to maintain backwards compatibility when upgrading from v11 to v12.

Closes https://github.com/gravitational/teleport/issues/20312

### CODE REVIEW

File: lib/services/local/users.go [hunk 1]
```diff
@@ -1491,6 +1490,21 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
...
+	sshPub, err := ssh.NewPublicKey(pub)
+	if err != nil {
+		return "", trace.Wrap(err)
+	}
+
+	key := ssh.FingerprintSHA256(sshPub)
+
+	// The SHA256 hash may contain "//", which is a forbidden pattern for database keys.
+	// We replace this pattern with "slashslash" so that we can insert the key without losing data.
+	key = strings.ReplaceAll(key, "//", "slashslash")
```
Comment (jakule) [inline lib/services/local/users.go:1503]: Shouldn't we base64 it or use URL encoding (something that has standard) instead of replacing it with a random string?

Comment (codingllama) [reply lib/services/local/users.go:1503]: +1 for using a proper encoding. `base64.URLEncoding` should do the job.

File: lib/services/local/users_test.go [hunk 2]
```diff
@@ -845,3 +848,55 @@ func TestIdentityService_SSODiagnosticInfoCrud(t *testing.T) {
...
 }
+
+func TestIdentityService_AttestationDataCrud(t *testing.T) {
+	identity := newIdentityService(t, clockwork.NewFakeClock())
+	ctx := context.Background()
+
+	for _, tc := range []struct {
+		name             string
+		pubKeyPEM        string
+		expectPubKeyHash string
```
Comment (codingllama) [inline lib/services/local/users_test.go:859]: This field is not used in the test body.

File: lib/services/local/users.go [hunk 3]
```diff
@@ -1470,13 +1470,12 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
...
 
-	sshPub, err := ssh.NewPublicKey(publicKey)
+	keyFingerprint, err := attestedKeyFingerprint(publicKey)
 	if err != nil {
 		return nil, trace.Wrap(err)
 	}
 
-	key := ssh.FingerprintSHA256(sshPub)
-	item, err := s.Get(ctx, backend.Key(attestationsPrefix, key))
+	item, err := s.Get(ctx, backend.Key(attestationsPrefix, keyFingerprint))
```
Comment (codingllama) [inline lib/services/local/users.go:1478]: @Joerger, refresh my memory, is key attestation already out?

What are the implications of changing the storage key at this stage?

Should we try to read the "old" key as well, for a few versions, as a fallback?

File: lib/services/local/users.go (hunk 1 above)
Comment (Joerger) [reply lib/services/local/users.go:1503]: Thanks for this suggestion, I was honestly not sure what the straightforward solution was, base64 encoding of course makes sense.

File: lib/services/local/users.go (hunk 3 above)
Comment (Joerger) [reply lib/services/local/users.go:1478]: Yes, changing this to be URL bas64 encoded will be backwards incompatible. This amounts to the user needing to relogin, as their previous login certs won't find validated attestation data. I agree that we should check for the old key as a fallback for now.

File: lib/services/local/users.go (hunk 1 above)
Comment (Joerger) [reply lib/services/local/users.go]: It looks like URL base64 encoding also has invalid characters (`=`). What do you guys think of using a UUID hashed from the public key data? Any other ideas?

Comment (codingllama) [reply lib/services/local/users.go]: Would RawURLEncoding work? I think it does `[a-zA-Z]-_` (no padding char).

https://pkg.go.dev/encoding/base64#RawURLEncoding

File: lib/services/local/users.go [hunk 4]
```diff
@@ -1441,17 +1441,7 @@ func (s *IdentityService) UpsertKeyAttestationData(ctx context.Context, attestat
 		return trace.Wrap(err)
 	}
 
-	pub, err := x509.ParsePKIXPublicKey(attestationData.PublicKeyDER)
```
Comment (codingllama) [inline lib/services/local/users.go:1444]: We probably want to keep this to make sure the key is valid before writing to storage. Let's make sure tests cover invalid keys as well.

File: lib/services/local/users.go [hunk 5]
```diff
@@ -1470,17 +1460,27 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
...
 		return nil, trace.Wrap(err)
 	}
 
-	key := ssh.FingerprintSHA256(sshPub)
+	key := fingerprintSha256(pubDER)
 	item, err := s.Get(ctx, backend.Key(attestationsPrefix, key))
-	if err != nil {
+	if trace.IsNotFound(err) {
+		// Fallback to old fingerprint (std base64 encoded ssh public key) for backwards compatibility.
+		// DELETE IN 13.0.0
```
Comment (codingllama) [inline lib/services/local/users.go:1472]:
```suggestion
		// DELETE IN 13.0, old fingerprints not in use by then (Joerger).
```

File: lib/services/local/users.go [hunk 6]
```diff
@@ -1491,6 +1491,20 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
 	return &resp, nil
 }
 
+func fingerprintSha256(pubDER []byte) string {
+	uuid := uuid.NewHash(crypto.SHA256.New(), uuid.UUID{}, pubDER, 0)
+	return uuid.String()
+}
+
+// DELETE IN 13.0.0
```
Comment (codingllama) [inline lib/services/local/users.go:1499]:
```suggestion
// DELETE IN 13.0, old fingerprints not in use by then (Joerger).
```

File: lib/services/local/users.go [hunk 7]
```diff
@@ -1470,17 +1460,27 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
...
+		}
+		item, err = s.Get(ctx, backend.Key(attestationsPrefix, key))
 		if trace.IsNotFound(err) {
 			return nil, trace.NotFound("hardware key attestation not found")
+		} else if err != nil {
+			return nil, trace.Wrap(err)
 		}
+	} else if err != nil {
 		return nil, trace.Wrap(err)
 	}
```
Comment (codingllama) [inline lib/services/local/users.go:1485]: Suggestion: Simplify a bit?

```suggestion
		}
	}
	if err != nil {
		return nil, trace.Wrap(err)
	}
```

File: lib/services/local/users.go [hunk 8]
```diff
@@ -1491,6 +1491,20 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
 	return &resp, nil
 }
 
+func fingerprintSha256(pubDER []byte) string {
```
Comment (codingllama) [inline lib/services/local/users.go:1494]: Let's make it purpose-specific.

```suggestion
func keyAttestationDataFingerprint(pubDER []byte) string {
```

File: lib/services/local/users.go [hunk 9]
```diff
@@ -1491,6 +1491,20 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
...
+	uuid := uuid.NewHash(crypto.SHA256.New(), uuid.UUID{}, pubDER, 0)
+	return uuid.String()
+}
+
+// DELETE IN 13.0.0
+func oldFingerprintSha256(pub crypto.PublicKey) (string, error) {
```
Comment (codingllama) [inline lib/services/local/users.go:1500]:
```suggestion
func keyAttestationDataFingerprintV11(pub crypto.PublicKey) (string, error) {
```

oldKeyAttestationBlabla also works, but this way we add more info to the name.

File: lib/services/local/users.go [hunk 10]
```diff
@@ -1491,6 +1491,20 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
 	return &resp, nil
 }
 
+func fingerprintSha256(pubDER []byte) string {
+	uuid := uuid.NewHash(crypto.SHA256.New(), uuid.UUID{}, pubDER, 0)
```
Comment (codingllama) [inline lib/services/local/users.go:1495]: crypto.SHA256 is a bit special, in that you need to import crypto/sha256 _somewhere_ for it to work.

We certainly do in Teleport, but the "correct" is to `import _ crypto/sha256` in the files where it is used.

https://pkg.go.dev/crypto#SHA256

Comment (codingllama) [inline lib/services/local/users.go:1495]: Use version 4?

```suggestion
	uuid := uuid.NewHash(crypto.SHA256.New(), uuid.UUID{}, pubDER, 4 /* version */)
```

File: lib/services/local/users_test.go [hunk 11]
```diff
@@ -845,3 +848,53 @@ func TestIdentityService_SSODiagnosticInfoCrud(t *testing.T) {
...
+		{
+			name: "standard public key",
+			pubKeyPEM: `-----BEGIN PUBLIC KEY-----
+MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCep78YgY5I8RrvhE5zra4k1hx
+JZoZL1NsgqBz/f49OZsck24rcxurnC0lKAJmSGtKZrv54E/XZuPtatUkrXtIFKC6
+shHLLAc/LAVtDX2/E/aLgM0srYtt1/kku9H1C9+Ou7RzOIdblRkNMYcbUOhKBNld
+AnYsqjU9/7IaQSp8DwIDAQAB
+-----END PUBLIC KEY-----`,
+		}, {
+			name: "public key with // in standard hash",
```
Comment (codingllama) [inline lib/services/local/users_test.go:870]: Should we add a case for a pub key with padding in URLEncoding? Or does this cover that also?

File: lib/services/local/users.go [hunk 12]
```diff
@@ -1470,17 +1460,27 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
...
 	if err != nil {
 		return nil, trace.Wrap(err)
 	}
 
-	key := ssh.FingerprintSHA256(sshPub)
+	key := fingerprintSha256(pubDER)
 	item, err := s.Get(ctx, backend.Key(attestationsPrefix, key))
-	if err != nil {
+	if trace.IsNotFound(err) {
+		// Fallback to old fingerprint (std base64 encoded ssh public key) for backwards compatibility.
```
Comment (jakule) [inline lib/services/local/users.go:1471]: We should also add a test to make sure that the old and new keys are supported.

File: lib/services/local/users.go (hunk 5 above)
Comment (Joerger) [reply lib/services/local/users.go:1472]: This key data is added each time you login (with PIV). This backwards compatibility check just makes it so your existing login, which was made using the old fingerprint, could still be found by the auth server.

File: lib/services/local/users.go (hunk 10 above)
Comment (Joerger) [reply lib/services/local/users.go:1495]: Good to know! will add.

File: lib/services/local/users_test.go (hunk 11 above)
Comment (Joerger) [reply lib/services/local/users_test.go:870]: Sorry I don't follow, why would there be padding? Do you think we need to `strings.TrimSpace()` the public key DER, or something else?

Comment (codingllama) [reply lib/services/local/users_test.go]: Sorry, I meant padding in the hypothetical b64 URL encoding, which is the `=` problem you had earlier.

File: lib/services/local/users.go [hunk 13]
```diff
@@ -1491,6 +1497,21 @@ func (s *IdentityService) GetKeyAttestationData(ctx context.Context, publicKey c
 	return &resp, nil
 }
 
+func keyAttestationDataFingerprint(pubDER []byte) string {
+	sha256sum := sha256.Sum256(pubDER)
+	encodedSHA := base64.RawURLEncoding.EncodeToString(sha256sum[:])
+	return encodedSHA
+}
+
+// DELETE IN 13.0, old fingerprints not in use by then (Joerger).
```
Comment (codingllama) [inline lib/services/local/users.go:1506]:
```suggestion
// KeyAttestationDataFingerprintV11 creates a "KeyAttestationData" fingerprint
// compatible with older patches of Teleport v11.
// Exposed for testing, do not use this function directly.
// DELETE IN 13.0, old fingerprints not in use by then (Joerger).
```

**Review by codingllama — APPROVED** [review]
Thanks for the fix, Brian!

**Review by jakule — APPROVED** [review]
