### PR TITLE
Include upload ID & session ID in failed upload warning logs

### LINKED ISSUE #6802: When uploads fail to complete, include the host's UUID in the error message
### What
Currently if Teleport has an error uploading a session, you just see a message at `WARN` level saying `Failed to complete upload.` with no extra information that can be used to track down the faulty session recording (like host UUID, hostname, filename etc)

```
WARN             Failed to complete upload. error:[
ERROR REPORT:
Original Error: *trace.BadParameterError MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
        status code: 400, request id: BASXNQNG0ADNMXDH, host id: dX59WtsYAs4YD3wYneXa/wSWEaoQIo9J4rHARNoXKROaPWSgosgFrkjSnTmL&#43;HySuDmrGskYMKI=
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/events/s3sessions/s3handler.go:365 github.com/gravitational/teleport/lib/events/s3sessions.ConvertS3Error
        /go/src/github.com/gravitational/teleport/lib/events/s3sessions/s3stream.go:112 github.com/gravitational/teleport/lib/events/s3sessions.(*Handler).CompleteUpload
        /go/src/github.com/gravitational/teleport/lib/events/stream.go:624 github.com/gravitational/teleport/lib/events.(*sliceWriter).completeStream
        /go/src/github.com/gravitational/teleport/lib/events/stream.go:497 github.com/gravitational/teleport/lib/events.(*sliceWriter).receiveAndUpload
        /opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message: MalformedXML: The XML you provided was not well-formed or did not validate against our published schema
        status code: 400, request id: BASXNQNG0ADNMXEL, host id: dX59WtsYAs4YD3wYneXa/wSWEaoQIo9J4rHARNoXKROaPWSgosgFrkjSnTmL&#43;HySuDmrGskYN1I=] events/stream.go:627
```

### How
Augment the warning message with the failing host's UUID so it can be looked up in `tctl get nodes`.

### Why
Spurious warnings in the auth server logs with no easy method to investigate them further are not useful.

### Workaround
Turn the log level on the auth servers up to `DEBUG` and hope that there's a related message containing UUID or other information immediately before/after the warning.

### PR DESCRIPTION
**Pull request by vitorenesduarte**
Fixes #6802.

Having the session ID in these logs should allow users to track down to which users host the session belongs to: https://github.com/gravitational/teleport/issues/6802#issuecomment-1327640494.

### CODE REVIEW

**Comment by zmb3** [comment]
Should we include the upload ID too?

**Comment by vitorenesduarte** [comment]
> Should we include the upload ID too?

Done in cc1b6d4ce704c3057bdf3477e161b2b72eb240b2.

File: lib/events/stream.go [hunk 1]
```diff
@@ -655,7 +655,7 @@ func (w *sliceWriter) completeStream() {
 		case upload := <-w.completedUploadsC:
 			part, err := upload.getPart()
 			if err != nil {
-				log.WithError(err).Warningf("Failed to upload part.")
+				log.WithError(err).Warningf("Failed to upload %q part for session id %q", w.proto.cfg.Upload.ID, w.proto.cfg.Upload.SessionID)
```
Comment (zmb3) [inline lib/events/stream.go:658]: This sounds like a part ID now though. I wonder if this would be better.
```suggestion
				log.WithError(err).
					WithField("upload", w.proto.cfg.Upload.ID).
					WithField("session", w.proto.cfg.Upload.SessionID). 
					Warning("Failed to upload part")
```

**Review by zmb3 — APPROVED** [review]

**Review by nklaassen — APPROVED** [review]
