### PR TITLE
Don't log error on tunnel node after its serving agent is stopped

### LINKED ISSUE #4252: Error showing in log after user exits session
### Description
**What happened**:
A user opens a web ssh session to a node. The node was added with a dynamic token using a reverse tunnel.  After typing exit in the session the following appears in the node teleport logs:

```
ERRO [NODE]      agent server for user "user@domain" stopped: accept unix /tmp/teleport-156436935/teleport-2391.socket: use of closed network connection id:4 local:10.0.2.15:46256 login:root remote:100.16.5X.YY:58046 teleportUser:user@domain regular/sshserver.go:804
```

**What you expected to happen**:

No error messages as this was a typical ssh session that was exited by the user.

**How to reproduce it (as minimally and precisely as possible)**:

Install a teleport 4.3.5 to a server and a node.  Within the auth server run the nodes add command.
`tctl nodes add`

Copy the output and change the port to 3080 from 3025 to use reverse tunneling.

Copy and paste this to a linux machine (ubuntu 20 desktop vm in this case). Run with `sudo`

### Environment
* Teleport version (use `teleport version`): 4.3.5
* OS (e.g. from `/etc/os-release`): ubuntu 20
* Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

* Browser Version (for UI-related issues): Chrome
* Install tools: 
* Others:

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190029021439585/1190410763244771) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by andrejtokarcik**
Fixes #4252.

### CODE REVIEW

**Review by awly — APPROVED** [review]

File: lib/teleagent/agent.go [hunk 1]
```diff
@@ -85,9 +85,10 @@ func (a *AgentServer) Serve() error {
 				return trace.Wrap(err, "unknown error")
 			}
 			if !neterr.Temporary() {
-				if !strings.Contains(neterr.Error(), "use of closed network connection") {
-					log.Errorf("got permanent error: %v", err)
+				if strings.Contains(neterr.Error(), "use of closed network connection") {
+					return nil
 				}
+				log.Errorf("got permanent error: %v", err)
```
Comment (r0mant) [inline lib/teleagent/agent.go:91]: Nit: We started trying to make all log entries into proper sentences some time ago which includes capitalizing log messages and ending them with a dot, so I'd refactor this one as well since you're here anyway:

```go
log.WithError(err).Error("Got permanent error.")
```

File: lib/teleagent/agent.go [hunk 2]
```diff
@@ -85,9 +85,10 @@ func (a *AgentServer) Serve() error {
...
 				return err
```
Comment (r0mant) [inline lib/teleagent/agent.go:92]: `trace.Wrap(err)`?

File: lib/teleagent/agent.go (hunk 1 above)
Comment (andrejtokarcik) [reply lib/teleagent/agent.go]: Done.

File: lib/teleagent/agent.go (hunk 2 above)
Comment (r0mant) [reply lib/teleagent/agent.go:92]: @andrejtokarcik Sorry, saw you resolve this - so you don't think `trace.Wrap` is needed here?

**Review by r0mant — APPROVED** [review]

File: lib/teleagent/agent.go (hunk 2 above)
Comment (andrejtokarcik) [reply lib/teleagent/agent.go:92]: Oh sorry, good catch, I totally misunderstood your message here. I thought you were referring to my changed line, i.e. suggesting to wrap the `err` being passed to the log function - which sounded a little strange but I thought I resolved it in the other way. Sure, I'll add `trace.Wrap` to the return statement (although it wasn't originally present - probably just a mishap).
