### PR TITLE
Do not exit teleport when unable to enumerate k8s cluster

### LINKED ISSUE #7215: Unavailable kubernetes cluster prevents Teleport from starting
### Description

**What happened**:

When using the `kubeconfig` in a `kubernetes_service` configuration if a k8s cluster is unavailable the Teleport executable will fail to start. That causes disruption to access for other k8s clusters or any other services configured. 
```
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal teleport[7991]: WARN [PROC:1]    "Teleport process has exited with error: failed to verify impersonation permissions for kubernetes: Post \"https://35.193.243.224/apis/authorization.k8s.io/v1/selfsubjectaccessreviews\": dial tcp 35.193.243.224:443: connect: connection refused; this may be due to missing the SelfSubjectAccessReview permission on the ClusterRole used by the proxy; please make sure that proxy has all the necessary permissions: https://goteleport.com/teleport/docs/kubernetes-ssh/#impersonation\n\tPost \"https://35.193.243.224/apis/authorization.k8s.io/v1/selfsubjectaccessreviews\": dial tcp 35.193.243.224:443: connect: connection refused" service:kube.init service/supervisor.go:251
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal teleport[7991]: ERRO [PROC:1]    "Critical service kube.init has exited with error failed to verify impersonation permissions for kubernetes: Post \"https://35.193.243.224/apis/authorization.k8s.io/v1/selfsubjectaccessreviews\": dial tcp 35.193.243.224:443: connect: connection refused; this may be due to missing the SelfSubjectAccessReview permission on the ClusterRole used by the proxy; please make sure that proxy has all the necessary permissions: https://goteleport.com/teleport/docs/kubernetes-ssh/#impersonation\n\tPost \"https://35.193.243.224/apis/authorization.k8s.io/v1/selfsubjectaccessreviews\": dial tcp 35.193.243.224:443: connect: connection refused, aborting." service/signals.go:144
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal teleport[7991]: ERROR: failed to verify impersonation permissions for kubernetes: Post "https://35.193.243.224/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": dial tcp 35.193.243.224:443: connect: connection refused; this may be due to missing the SelfSubjectAccessReview permission on the ClusterRole used by the proxy; please make sure that proxy has all the necessary permissions: https://goteleport.com/teleport/docs/kubernetes-ssh/#impersonation
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal teleport[7991]: Post "https://35.193.243.224/apis/authorization.k8s.io/v1/selfsubjectaccessreviews": dial tcp 35.193.243.224:443: connect: connection refused
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal systemd[1]: teleport.service: main process exited, code=exited, status=1/FAILURE
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal systemd[1]: Unit teleport.service entered failed state.
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal systemd[1]: teleport.service failed.
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal systemd[1]: teleport.service holdoff time over, scheduling restart.
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal systemd[1]: start request repeated too quickly for teleport.service
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal systemd[1]: Failed to start Teleport SSH Service.
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal systemd[1]: Unit teleport.service entered failed state.
Jun 08 14:52:46 ip-172-31-88-15.ec2.internal systemd[1]: teleport.service failed.

```

**What you expected to happen**:

A error or warning outputted to the log with Teleport still starting.  An error in the web console would be helpful to indicate an issue connecting. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure a `kubeconfig` to a valid k8s cluster installed in a `kubernetes_service`
2.Confirm the teleport agent is running
3. Modify the IP or DNS address for the `kubeconfig` to another ip or dns
4. Restart the service.  The service will fail to start

### Server Details
- Teleport version (run `teleport version`): 6.2.1
- Server OS (e.g. from `/etc/os-release`): AWS Linux 2

### PR DESCRIPTION
**Pull request by tcsc**
Teleport will fail to start when when a k8s cluster is unavailable when
using the kubeconfig in a `kubernetes_service` configuration. This means
that a single missing cluster can disrupt _all_ of the configured
clusters, even if the others are online.

This change makes failing the cluster credential enumeration a
per-k8s-cluster warning, rather than a stop-the-world error.

It also expands the testing shims inside the k8s proxy to allow more
sophisticated mocked scenarios, in order to test the above.

See-Also: #7215

### CODE REVIEW

**Comment by russjones** [comment]
@stevenGravy Can you verify this solves the customers issue?

**Review by timothyb89 — APPROVED** [review]

**Review by nklaassen — APPROVED** [review]

File: lib/kube/proxy/auth.go [hunk 1]
```diff
@@ -43,15 +43,19 @@ type kubeCreds struct {
 	kubeClient *kubernetes.Clientset
 }
 
-var skipSelfPermissionCheck bool
+type SelfPermissionsCheckTestingShimFn func(context.Context, string, authztypes.SelfSubjectAccessReviewInterface) error
```
Comment (r0mant) [inline lib/kube/proxy/auth.go:46]: Sorry to jump in last minute and I realize it was implemented in a similar way before your changes as well, but this feels a little too hacky IMHO.

Replacing implementation in tests is normal but it is usually done via providing a "test" implementation of a particular interface. Looking at the code `getKubeCreds` is called from `NewForwarder` - can we add the test implementation for getting the creds to the forwarder config which tests would set? It will be cleaner and there would not be any "TestOnlyMonkeyPatchXXX"  methods in the code.

**Review by r0mant — CHANGES_REQUESTED** [review]

**Comment by stevenGravy** [comment]
> @stevenGravy Can you verify this solves the customers issue?

@russjones yes this fixes the issue

File: lib/kube/proxy/auth.go [hunk 2]
```diff
@@ -121,57 +125,68 @@ func getKubeCreds(ctx context.Context, log logrus.FieldLogger, tpClusterName, ku
...
-			// via logs.
-			if kubeconfigPath != "" {
-				log.Info("If this is a proxy and you provided a dummy kubeconfig_path, you can remove it from teleport.yaml to get rid of this warning")
-			}
-		} else {
-			log.Debug("Have all necessary Kubernetes impersonation permissions.")
+			log.WithError(err).Warnf("failed to load credentials for cluster %q.", cluster)
+			continue
 		}
+		res[cluster] = clusterCreds
```
Comment (awly) [inline lib/kube/proxy/auth.go:133]: with this code, if anything in `extractKubeCreds` fails, the k8s cluster will not be registered by `kubernetes_service`.
for an admin to resolve the problem, they need to fix the underlying issue (permissions, firewall, etc) and restart the `kubernetes_service`.

it would be nicer to register the k8s cluster (even if it isn't fully operational) and have it recover without any restarts once the underlying issue is resolved.

this means:
- if anything about credential loading fails, return an error and maybe abort statup - these are local issues in configuration
- if impersonation permission check fails, log a warning, but add `clusterCreds` to `res[cluster` and proceed

**Review by awly — CHANGES_REQUESTED** [review]

File: lib/kube/proxy/auth.go (hunk 1 above)
Comment (tcsc) [reply lib/kube/proxy/auth.go:46]: @r0mant - So I've managed to get this working for the unit tests, and it looks OK.

It's proving _much_ harder to inject a mock for use with the integration tests, as the only point of contact between the test code and the forwarder is the initial process config - and specifying mocks for testing  in that seems like a bit overkill.

Any advice gratefully received.

Comment (r0mant) [reply lib/kube/proxy/auth.go:46]: Do integration tests actually need mocking, or do they use the actual logic (as I would assume)?

Frankly, I see nothing wrong with having ability to provide custom (e.g. test) implementation even in the process config - e.g. as a part of "Proxy.Kube" service configuration. However, if the integration test needs to only skip a part of this getKubeCreds logic, you could simply add a some sort of boolean field to the config instead of a full interface and use that in the code to run/skip that code.

We already do something similar to disable various listeners in integration tests e.g. see `DisableXXX` fields on the ProxyConfig.

Comment (tcsc) [reply lib/kube/proxy/auth.go:46]: The integration tests set the debug flag in the existing code, and fail if it's not set - so they definitely need some sort of switch to swap out the implementation for testing. Will follow the ProxyConfig example - thanks!

File: lib/kube/proxy/auth.go (hunk 2 above)
Comment (tcsc) [reply lib/kube/proxy/auth.go]: Done

File: lib/kube/proxy/auth.go (hunk 1 above)
Comment (tcsc) [reply lib/kube/proxy/auth.go]: Done

File: lib/kube/proxy/forwarder.go [hunk 3]
```diff
@@ -134,6 +134,8 @@ type ForwarderConfig struct {
 	DynamicLabels *labels.Dynamic
 	// LockWatcher is a lock watcher.
 	LockWatcher *services.LockWatcher
+
+	DisableImpersonationPermissionsCheck bool
```
Comment (r0mant) [inline lib/kube/proxy/forwarder.go:138]: Instead of passing a boolean, why not pass the checker function/interface?

Also, missing godoc.

File: lib/kube/proxy/auth.go [hunk 4]
```diff
@@ -43,16 +43,7 @@ type kubeCreds struct {
...
-
-// TestOnlySkipSelfPermissionCheck sets whether or not to skip checking k8s
-// impersonation permissions granted to this instance.
-//
-// Used in CI integration tests, where we intentionally scope down permissions
-// from what a normal prod instance should have.
-func TestOnlySkipSelfPermissionCheck(skip bool) {
-	skipSelfPermissionCheck = skip
-}
+type ImpersonationPermissionsChecker func(context.Context, string, authztypes.SelfSubjectAccessReviewInterface) error
```
Comment (r0mant) [inline lib/kube/proxy/auth.go:46]: Missing godoc.

File: integration/helpers.go [hunk 5]
```diff
@@ -171,6 +173,8 @@ type InstanceConfig struct {
 
 	// log specifies the logger
 	log utils.Logger
+
+	DisableKubeImpersonationPermissionsCheck bool
```
Comment (r0mant) [inline integration/helpers.go:177]: This looks very out of place in InstanceConfig and in TeleInstance to be honest. Can tests just always disable it when creating a kube forwarder (by passing a dummy implementation as I suggested below) or are there tests that actually need it?

File: lib/kube/proxy/auth_test.go [hunk 6]
```diff
@@ -113,14 +113,23 @@ func (c *mockSARClient) Create(_ context.Context, sar *authzapi.SelfSubjectAcces
 	return sar, nil
 }
 
+func alwaysSucceeds(context.Context, string, authztypes.SelfSubjectAccessReviewInterface) error {
+	return nil
+}
+
+func failsForCluster(clusterName string) ImpersonationPermissionsChecker {
+	return func(ctx context.Context, cluster string, a authztypes.SelfSubjectAccessReviewInterface) error {
+		if cluster == "bar" {
```
Comment (awly) [inline lib/kube/proxy/auth_test.go:122]:
```suggestion
		if cluster == clusterName {
```

File: lib/kube/proxy/forwarder.go [hunk 7]
```diff
@@ -203,7 +205,14 @@ func NewForwarder(cfg ForwarderConfig) (*Forwarder, error) {
 		trace.Component: cfg.Component,
 	})
 
-	creds, err := getKubeCreds(cfg.Context, log, cfg.ClusterName, cfg.KubeClusterName, cfg.KubeconfigPath, cfg.KubeServiceType)
+	log.Error("Selecting Impersonation Permissions Check")
```
Comment (awly) [inline lib/kube/proxy/forwarder.go:208]: This log seems redundant
```suggestion
```

File: lib/kube/proxy/server.go [hunk 8]
```diff
@@ -88,6 +88,8 @@ type TLSServer struct {
 
 // NewTLSServer returns new unstarted TLS server
 func NewTLSServer(cfg TLSServerConfig) (*TLSServer, error) {
+	log.Infof("Disable thingy %v", cfg.DisableImpersonationPermissionsCheck)
+
```
Comment (awly) [inline lib/kube/proxy/server.go:92]:
```suggestion
```

File: lib/kube/proxy/auth.go [hunk 9]
```diff
@@ -121,22 +112,33 @@ func getKubeCreds(ctx context.Context, log logrus.FieldLogger, tpClusterName, ku
...
+	log = log.WithField("cluster", cluster)
+
+	log.Debug("Checking Kubernetes impersonation permissions.")
+	client, err := kubernetes.NewForConfig(clientCfg)
+	if err != nil {
+		return nil, trace.Wrap(err, "failed to generate Kubernetes client for cluster %q", cluster)
+	}
+
+	// For each loaded cluster, check impersonation permissions. This
+	// failure is only critical for newKubeService.
```
Comment (awly) [inline lib/kube/proxy/auth.go:135]:
```suggestion
	// For each loaded cluster, check impersonation permissions. This
	// check only logs when permissions are not configured, but does not fail startup.
```

File: lib/kube/proxy/auth.go [hunk 10]
```diff
@@ -121,22 +112,33 @@ func getKubeCreds(ctx context.Context, log logrus.FieldLogger, tpClusterName, ku
...
+	if err := checkPermissions(ctx, cluster, client.AuthorizationV1().SelfSubjectAccessReviews()); err != nil {
+		// kubernetes_service must have valid RBAC permissions, otherwise
+		// it's pointless.
+
```
Comment (awly) [inline lib/kube/proxy/auth.go:139]:
```suggestion
```

File: lib/kube/proxy/auth.go [hunk 11]
```diff
@@ -121,22 +112,33 @@ func getKubeCreds(ctx context.Context, log logrus.FieldLogger, tpClusterName, ku
...
+		log.WithError(err).Warning("Failed to test the necessary Kubernetes permissions. The target Kubernetes cluster may be down. This teleport instance will still handle Kubernetes requests towards other Kubernetes clusters.")
```
Comment (awly) [inline lib/kube/proxy/auth.go:140]:
```suggestion
		log.WithError(err).Warning("Failed to test the necessary Kubernetes permissions. The target Kubernetes cluster may be down or have misconfigured RBAC. This teleport instance will still handle Kubernetes requests towards this Kubernetes cluster.")
```

File: lib/kube/proxy/auth.go [hunk 12]
```diff
@@ -121,22 +112,33 @@ func getKubeCreds(ctx context.Context, log logrus.FieldLogger, tpClusterName, ku
...
+		if serviceType != KubeService {
```
Comment (awly) [inline lib/kube/proxy/auth.go:141]:
```suggestion
		if serviceType != KubeService && kubeconfigPath != "" {
```

File: lib/kube/proxy/auth.go [hunk 13]
```diff
@@ -146,32 +148,31 @@ func getKubeCreds(ctx context.Context, log logrus.FieldLogger, tpClusterName, ku
 			if kubeconfigPath != "" {
 				log.Info("If this is a proxy and you provided a dummy kubeconfig_file, you can remove it from teleport.yaml to get rid of this warning")
 			}
```
Comment (awly) [inline lib/kube/proxy/auth.go:150]:
```suggestion
			log.Info("If this is a proxy and you provided a dummy kubeconfig_file, you can remove it from teleport.yaml to get rid of this warning")
```

**Review by awly — APPROVED** [review]
LGTM, after all comments are addressed

File: integration/helpers.go (hunk 5 above)
Comment (tcsc) [reply integration/helpers.go]: Done

File: lib/kube/proxy/auth.go (hunk 4 above)
Comment (tcsc) [reply lib/kube/proxy/auth.go]: Added

File: lib/kube/proxy/forwarder.go (hunk 3 above)
Comment (tcsc) [reply lib/kube/proxy/forwarder.go]: Done

**Review by r0mant — APPROVED** [review]
@tcsc Great, very clean now :+1:
