### PR TITLE
Export endpoint config

### LINKED ISSUE #41983: The updater cannot identify auto updates version endpoint if proxy_server is not specified
### Expected behavior:
The teleport updater should be compatible with any version of the `teleport.yaml` [config](https://goteleport.com/docs/reference/config/#configuration-versions).

Additionally, removing the use of the default global version server should be considered. This seems to be causing more problems than it solves.

### Current behavior:
The Teleport configuration supports cluster configuration using both `auth_server` and `proxy_server` values. Additionally, older versions of the configuration (v1 and v2) support the use of the list `auth_servers` config. The teleport updater is only able to correctly parse and identify the auto updates version endpoint if `proxy_server` is specified in the `teleport.yaml` config.

Because the updater is failing to identify the auto updates version endpoint, it falls back to using the global version server, which is problematic because this can result in a teleport upgrade to an incompatible version.

### Bug details:
- Teleport version: 15.3.5
- Recreation steps:
- Debug logs:

### PR DESCRIPTION
**Pull request by bernardjkim**
Closes https://github.com/gravitational/teleport/issues/41983

This PR registers an endpoint export function with the teleport process. On startup the proxy version endpoint will be exported to the `/etc/teleport-upgrade.d/endpoint` config. If an endpoint value is already configured, the value will not be overwritten.

This will allow the teleport updater to be compatible with the previous versions of the teleport config.

changelog: Fixes automatic updates with previous versions of the `teleport.yaml` config.

### CODE REVIEW

File: lib/service/service.go [hunk 1]
```diff
@@ -1129,6 +1130,20 @@ func NewTeleport(cfg *servicecfg.Config) (*TeleportProcess, error) {
 			process.logger.WarnContext(process.ExitContext(), "Use of external upgraders on control-plane instances is not recommended.")
 		}
 
+		if upgraderKind == "unit" {
+			process.RegisterFunc("autoupdates.endpoint.export", func() error {
```
Comment (hugoShaka) [inline lib/service/service.go:1134]: This function is not marked critical so it won't fail the process right?

File: lib/service/service.go [hunk 2]
```diff
@@ -1129,6 +1130,20 @@ func NewTeleport(cfg *servicecfg.Config) (*TeleportProcess, error) {
...
+				if err := endpoint.Export(process.ExitContext(), resolverAddr); err != nil {
```
Comment (hugoShaka) [inline lib/service/service.go:1135]: If we are joining via auth I think this will do weird things with the updater as it will set the endpoint override to `auth.example.com:3025` which is not a valid version server.

This is not a possible case for Cloud, but this can and will happen in self-hosted setups. I'm not sure we can catch all cases where we connect through a proxy, but known cases are:
- when `cfg.ProxyServer` is set
- (ugly) when port is 443 or 3080

We can also make this logic cloud-specific by looking for the `teleport.sh` suffix in the resolver address.

Comment (bernardjkim) [reply lib/service/service.go]: I've made changes in [57cf444](https://github.com/gravitational/teleport/pull/42810/commits/57cf4448f6e576ace75eb338c83a49046c0e76ae) so that this export function will only be run for Cloud instances.

Additionally, the export function will attempt to verify the endpoint first before writing the config. So if the resolver address results in an invalid version server, the endpoint will not be written.

File: lib/service/service.go (hunk 1 above)
Comment (bernardjkim) [reply lib/service/service.go:1134]: Yup, a failure will not fail the teleport process.

**Review by hugoShaka — APPROVED** [review]

**Review by fheinecke — COMMENTED** [review]
This directly couples the updater with Teleport, and it'll now be coupled in both directions. Are we 100% sure that we want this?

Doing so will also remove any chance of the updater being versioned outside of Teleport.

**Comment by bernardjkim** [comment]
> This directly couples the updater with Teleport, and it'll now be coupled in both directions.

The updater is already dependent on Teleport to export an update schedule, so I think it has already been coupled in both directions.

We can handle this in the teleport updater logic, but correctly parsing the different teleport.yaml config versions in bash doesn't sound like the simplest task. I can give it a shot if you're really against adding any updater logic into teleport.

**Comment by bernardjkim** [comment]
Hey @fheinecke, actually I think it would be preferred to implement this logic inside Teleport because it would also help address the issue with the global version endpoint https://github.com/gravitational/cloud/issues/8361. There are still a number of users that have not upgraded their teleport updater from the deprecated version, and they still query the target agent version from the global version endpoint.

This change would allow agents to override that default without requiring the updater package itself to be updated.

**Review by fheinecke — APPROVED** [review]
