### PR TITLE
Make k8s errors responses decode-able by kubectl

### LINKED ISSUE #5096: k8s: teleport should return a k8s Status object on error
### Description

**What happened**:

Teleport returns plaintext strings in k8s response when an error happens on teleport side.
From the `kubectl` debug output:
```
I1210 14:58:38.962604 3390962 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

**What you expected to happen**:

Teleport returns an error response body that `kubectl` can unmarshal and present to the user.
This means returning a [`Status` API object](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#status-v1-meta)

### PR DESCRIPTION
**Pull request by awly**
`kubectl` expects a k8s `Status` object in error responses.
Intercept generic handler errors and forwarder errors, and wrap them in
a `Status` object.

Before the change:
```sh
$ kubectl get nodes
Error from server (InternalError): an error on the server ("Internal Server Error") has prevented the request from succeeding
```

Example with the change:
```sh
# kubernetes_service went offline
$ kubectl get nodes
Error from server: the node is offline or has disconnected, if the issue persists, restart the node or re-register it in the cluster

# kubernetes cluster doesn't exist anymore
$ kubectl get nodes
Error from server: kubernetes cluster "minikube" is not registered in this teleport cluster; you can list registered kubernetes clusters using 'tsh kube ls'
```

Fixes https://github.com/gravitational/teleport/issues/5096

### CODE REVIEW

File: lib/kube/proxy/forwarder.go [hunk 1]
```diff
@@ -389,7 +395,36 @@ func (f *Forwarder) withAuth(handler handlerWithAuthFunc) httprouter.Handle {
...
+		Code:    int32(trace.ErrorToCode(respErr)),
+	}
+	data, err := runtime.Encode(statusCodecs.LegacyCodec(), status)
+	if err != nil {
+		f.log.Warningf("Failed encoding error into kube Status object: %v", err)
+		trace.WriteError(rw, respErr)
+		return
+	}
+	rw.Header().Set("Content-Type", "application/json")
+	// Always write InternalServerError, that's the only code that kubectl will
```
Comment (a-palchikov) [inline lib/kube/proxy/forwarder.go:421]: nit: Can you link to the code where kubectl does this so we might have an anchor for future updates.

**Review by a-palchikov — APPROVED** [review]

File: lib/httplib/httplib.go [hunk 2]
```diff
@@ -41,15 +41,27 @@ type HandlerFunc func(w http.ResponseWriter, r *http.Request, p httprouter.Param
...
 
+// ErrorWriter is a function responsible for writing the error into response
+// body.
+type ErrorWriter func(w http.ResponseWriter, err error)
+
 // MakeHandler returns a new httprouter.Handle func from a handler func
-func MakeHandler(fn HandlerFunc) httprouter.Handle {
+func MakeHandler(fn HandlerFunc, errWriter ...ErrorWriter) httprouter.Handle {
+	if len(errWriter) > 1 {
+		panic("at most 1 ErrorWriter can be passed to MakeHandler")
```
Comment (webvictim) [inline lib/httplib/httplib.go:51]: `panic` seems a bit extreme here given that we support passing a list of `ErrorWriter` - can we just take the first one instead? Is there something I missed?

File: lib/httplib/httplib.go [hunk 3]
```diff
@@ -59,14 +71,22 @@ func MakeHandler(fn HandlerFunc) httprouter.Handle {
 }
 
 // MakeStdHandler returns a new http.Handle func from http.HandlerFunc
-func MakeStdHandler(fn StdHandlerFunc) http.HandlerFunc {
+func MakeStdHandler(fn StdHandlerFunc, errWriter ...ErrorWriter) http.HandlerFunc {
+	if len(errWriter) > 1 {
+		panic("at most 1 ErrorWriter can be passed to MakeStdHandler")
```
Comment (webvictim) [inline lib/httplib/httplib.go:76]: Ditto above

File: lib/httplib/httplib.go (hunk 2 above)
Comment (a-palchikov) [reply lib/httplib/httplib.go:51]: Yes, I agree. If one wanted to solve this in Go, one option is using two APIs instead of abusing the slice arguments:
```go
func MakeHandler(fn HandlerFunc) { ... }
func MakeHandlerWithErrorWriter(fn HandlerFunc, errWriter ErrorWriter) { ... }
```
and just have `MakeHandler` invoke the other with `trace.WriteError`.

Comment (awly) [reply lib/httplib/httplib.go]: Good idea, better to enforce this at compile time rather than runtime.

File: lib/kube/proxy/forwarder.go (hunk 1 above)
Comment (awly) [reply lib/kube/proxy/forwarder.go:421]: `kubectl` code was inscrutable to me, due to a thick layer of abstractions and libraries. I don't know where this is handled.
I figured out this behavior after several hours of reverse-engineering the behavior.

**Review by fspmarshall — APPROVED** [review]
