### PR TITLE
Set contexts session for execs

### LINKED ISSUE #3916: Non-interactive session.end events are missing the user field
Non-interactive session.end events (the results of SCP and Exec) are missing the user field.

`"interactive": false`

```
{
  "code": "T2004I",
  "ei": 1,
  "enhanced_recording": false,
  "event": "session.end",
  "interactive": false,
  "namespace": "default",
  "participants": [
    "xxx"
  ],
  "server_addr": "172.10.1.1:3022",
  "server_hostname": "one",
  "server_id": "xxx",
  "session_start": "2020-06-25T19:48:39.377556994Z",
  "session_stop": "2020-06-25T19:48:41.465266935Z",
  "sid": "xxx",
  "time": "2020-06-25T19:48:41.466Z",
  "uid": "xxx"
}
```

#### How to Reproduce
1. `tsh login` to a node
1. `tsh scp` a file, which will trigger `scp` related events: `scp`, `session.start`, `session.end`, `session.data`

#### Screenshot
image

#### Related issue
https://github.com/gravitational/teleport/issues/3919

### LINKED ISSUE #3919: Running scp command results in missing fields in event Session.Data
#### Problem
 After running a `scp` command, `session.data` event is emitted but is missing the `sid` field:

```
{
  "addr.local": "172.10.1.1:3022",
  "addr.remote": "172.10.1.254:32832",
  "code": "T2006I",
  "ei": 2147483646,
  "event": "session.data",
  "login": "root",
  "rx": 3686,
  "server_id": "71705da3-2a74-4afe-84ce-23cc8aa82942",
  "time": "2020-06-26T03:24:20Z",
  "tx": 6274,
  "uid": "99a62481-46f0-45e6-9d07-7919d1df502e",
  "user": "mama"
}
```

#### How to Reproduce
1. `tsh login` to a node
1. `tsh scp` a file, which will trigger `scp` related events: `scp`, `session.start`, `session.end`, `session.data`

Possible location of problem where session is nil: https://github.com/gravitational/teleport/blob/master/lib/srv/ctx.go#L538

#### Screenshot
image

#### Related Issue
https://github.com/gravitational/teleport/issues/3916

### PR DESCRIPTION
**Pull request by kimlisa**
fixes https://github.com/gravitational/teleport/issues/3916
fixes https://github.com/gravitational/teleport/issues/3919

#### Description
- set ctx.session for non-interactive sessions (thank you @fspmarshall for help!)
- replace `session participants list` event field with `single user` event field

#### Screenshot
image

### CODE REVIEW

File: lib/srv/sess.go [hunk 1]
```diff
@@ -875,13 +876,11 @@ func (s *session) startExec(channel ssh.Channel, ctx *ServerContext) error {
 			events.EventNamespace:           ctx.srv.GetNamespace(),
 			events.SessionInteractive:       false,
 			events.SessionEnhancedRecording: s.hasEnhancedRecording,
-			events.SessionParticipants: []string{
-				ctx.Identity.TeleportUser,
-			},
```
Comment (kimlisa) [inline lib/srv/sess.go:880]: @russjones I wasn't sure why we opted for `events.SessionParticipants` over `events.EventUser`, so i replaced it.

File: lib/srv/sess.go [hunk 2]
```diff
@@ -214,6 +214,7 @@ func (s *SessionRegistry) OpenExecSession(channel ssh.Channel, req *ssh.Request,
 
 	// Start a non-interactive session (TTY attached). Close the session if an error
 	// occurs, otherwise it will be closed by the callee.
+	ctx.session = sess
```
Comment (awly) [inline lib/srv/sess.go:217]: Could you add a unit or integration test that would catch this?

**Review by awly — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]

File: lib/srv/sess.go (hunk 1 above)
Comment (russjones) [reply lib/srv/sess.go:880]: The Web UI uses this to display the list of participants in the session. Both scenarios: having a single or multiple participants is fine.

**Review by russjones — APPROVED** [review]

File: lib/srv/sess.go (hunk 2 above)
Comment (kimlisa) [reply lib/srv/sess.go:217]: revised: https://github.com/gravitational/teleport/pull/3955/commits/c334ef15b9aeb422c09467c639311f1d5e578f26

**Review by awly — APPROVED** [review]
