### PR TITLE
Fix data race in kube proxy watcher tests

### LINKED ISSUE #62166: `lib/kube/proxy.TestWatcher` flakiness
#### Link(s) to logs

https://github.com/gravitational/teleport/actions/runs/20136206746/job/57794986346?pr=62161

#### Relevant snippet

```
=== FAIL: lib/kube/proxy TestWatcher (0.28s)
==================
WARNING: DATA RACE
Write at 0x00c002112ad0 by goroutine 1500:
  github.com/gravitational/teleport/lib/kube/proxy.TestWatcher()
      /__w/teleport/teleport/lib/kube/proxy/watcher_test.go:91 +0x5f4
  github.com/gravitational/teleport/lib/kube/proxy.NewTLSServer()
      /__w/teleport/teleport/lib/kube/proxy/server.go:240 +0x204
  github.com/gravitational/teleport/lib/kube/proxy.SetupTestContext()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:260 +0x23fc
  github.com/gravitational/teleport/lib/kube/proxy.TestWatcher()
      /__w/teleport/teleport/lib/kube/proxy/watcher_test.go:75 +0x4a8
  testing.tRunner()
      /opt/go/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1997 +0x44

Previous read at 0x00c002112ad0 by goroutine 1686:
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).startHeartbeat()
      /__w/teleport/teleport/lib/kube/proxy/server.go:656 +0xbe
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).startHeartbeatAndHealthCheck()
      /__w/teleport/teleport/lib/kube/proxy/server.go:580 +0x97
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).startStaticClustersHeartbeat()
      /__w/teleport/teleport/lib/kube/proxy/server.go:692 +0x8ed
  github.com/gravitational/teleport/lib/kube/proxy.(*TLSServer).Serve()
      /__w/teleport/teleport/lib/kube/proxy/server.go:373 +0x68b
  github.com/gravitational/teleport/lib/kube/proxy.(*TestContext).startKubeServices.func1()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:425 +0x72

Goroutine 1500 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1997 +0x9d2
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:2477 +0x85
  testing.tRunner()
      /opt/go/src/testing/testing.go:1934 +0x21c
  testing.runTests()
      /opt/go/src/testing/testing.go:2475 +0x96c
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:2337 +0xed4
  github.com/gravitational/teleport/lib/kube/proxy.TestMain()
      /__w/teleport/teleport/lib/kube/proxy/forwarder_test.go:108 +0x30
  main.main()
      _testmain.go:161 +0x171

Goroutine 1686 (running) created at:
  github.com/gravitational/teleport/lib/kube/proxy.(*TestContext).startKubeServices()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:424 +0xc7
  github.com/gravitational/teleport/lib/kube/proxy.SetupTestContext()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:395 +0x33aa
  github.com/gravitational/teleport/lib/kube/proxy.SetupTestContext()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:334 +0x3157
  github.com/gravitational/teleport/lib/kube/proxy.NewTLSServer()
      /__w/teleport/teleport/lib/kube/proxy/server.go:240 +0x204
  github.com/gravitational/teleport/lib/kube/proxy.SetupTestContext()
      /__w/teleport/teleport/lib/kube/proxy/utils_test.go:260 +0x23fc
  github.com/gravitational/teleport/lib/kube/proxy.TestWatcher()
      /__w/teleport/teleport/lib/kube/proxy/watcher_test.go:75 +0x4a8
  testing.tRunner()
      /opt/go/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1997 +0x44
==================
    testing.go:1617: race detected during execution of test
```

### PR DESCRIPTION
**Pull request by tigrato**
This fixes a data race in the kube proxy watcher tests where the AuthClient field of mockAuthClient was being accessed concurrently without synchronization.

The issue was introduced in #61642 where the AuthClient was being set after the test context setup, creating a race condition between the server initialization and the test setup.

This commit resolves the race by using the WrapAuthClient hook in TestConfig to properly inject the mock client during setup, ensuring the AuthClient is set before any concurrent access can occur.

Fixes #62166

### CODE REVIEW

File: lib/kube/proxy/watcher_test.go [hunk 1]
```diff
@@ -86,9 +87,11 @@ func TestWatcher(t *testing.T) {
 				return
 			}
 		},
+		WrapAuthClient: func(client authclient.ClientI) authclient.ClientI {
+			authClient.ClientI = client
+			return authClient
```
Comment (rosstimothy) [inline lib/kube/proxy/watcher_test.go:92]: If we don't need a handle to the mock client outside of this function, then maybe restore the newMockAuthClient change and create it directly in this callback?
```suggestion
			return newMockAuthClient(client)
```

Comment (tigrato) [reply lib/kube/proxy/watcher_test.go:92]: The issue is that to access the internal channel you need to type assert the Client.
That's why i did it this way

Comment (rosstimothy) [reply lib/kube/proxy/watcher_test.go:92]: Oh, I guess we need to consume the delete channel below, though I wonder if that's truly how this test should be asserting clusters were deleted.

Comment (tigrato) [reply lib/kube/proxy/watcher_test.go:92]: That's not ideal but it was implemented this way by @atburke

**Review by rosstimothy — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
