### PR TITLE
Extend support for identity files in tsh

### LINKED ISSUE #11770: tsh db/app commands not working correctly with --identity flag
### Description

**What happened**:
When trying to use `tsh db` commands with a non-interactive user via an identity file, the commands fail on `ERROR: not logged in` or if the ~/.tsh is missing - `Failed to stat file: stat ~/.tsh: no such file or directory.`.  `tsh ls` works fine with the identity file.

`tsh db ls` and `tsh db login` have different outputs, but debug mode shows the same issue of the missing ~/.tsh/* files or the missing ~/.tsh directory.

If I'm already logged in with my normal user (via Github SSO) and then try the commands with --identity for the non-interactive user, the command partially ignores the identity flag passed in and later proceeds using the default profile.

**What you expected to happen**:
`tsh db` commands should respect the identity file passed to them and function normally.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. `tsh logout` to clear any existing profiles
2. generate an identity file either through `tsh login --out ...` or `tctl auth sign ...`
3. run `tsh db ls --identity=identity.txt --proxy=teleport.example.com:443 --login=username` and see failure
4. run `tsh ls --identity=identity.txt --proxy=teleport.example.com:443 --login=username` and see success
5. login via SSO or any normal user (not via --identity file)
6. run `tsh db ls --identity=identity.txt --proxy=teleport.example.com:443 --login=username` and see success but debug logs show SSO user certificates were used

### Server Details
- Teleport version (run `teleport version`): Teleport v9.0.2 git:v9.0.2-0-g354b8c037 go1.17.7
- Server OS (e.g. from `/etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): 9.0.3 (and 8.3.1)
- Computer OS (e.g. Linux, macOS, Windows): macOS and Ubuntu
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download): brew and yum
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

The non-interactive teleport user here is named `githubactions`, my local user is `joe` and my teleport user is my Github username - `joeportela`
Here we can see failures trying to run `tsh db ls` and `tsh db login`, but success with `tsh ls`
```
> tsh logout
Logged out all users from all proxies.

> tsh db ls --debug --proxy=teleport.example.com:443 --identity=githubactions.txt --login=githubactions --cluster=dev
[TSH]       DEBU Extracted username "githubactions" from the identity file githubactions.txt. tsh/tsh.go:1918
[TSH]       DEBU Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:2110
[CLIENT]    DEBU not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3074
            DEBU Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:105
[CLIENT]    INFO Connecting to proxy=teleport.example.com:3023 login="githubactions" client/api.go:2322
            DEBU No valid environment variables found. client/proxy.go:116
[HTTP:PROX] DEBU No proxy set in environment, returning direct dialer. proxy/proxy.go:268
[CLIENT]    INFO Successful auth with proxy teleport.example.com:3023. client/api.go:2327
[CLIENT]    DEBU Found clusters: [{"name":"admin","lastconnected":"2022-04-06T16:17:04.623738656Z","status":"online"},{"name":"dev","lastconnected":"2022-04-06T16:17:04.476063994Z","status":"online"}] client/client.go:127
[CLIENT]    DEBU Client  is connecting to auth server on cluster "dev". client/client.go:969
[CLIENT]    DEBU open /Users/joe/.tsh/teleport.example.com.yaml: no such file or directory client/api.go:781

ERROR REPORT:
Original Error: *trace.NotFoundError not logged in
Stack Trace:
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/lib/client/api.go:710 github.com/gravitational/teleport/lib/client.StatusCurrent
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/db.go:53 main.onListDatabases
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/tsh.go:739 main.Run
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/tsh.go:333 main.main
    /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/proc.go:250 runtime.main
    /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/asm_arm64.s:1259 runtime.goexit
User Message: not logged in

> tsh db login --debug --proxy=teleport.example.com:443 --identity=githubactions.txt --login=githubactions --cluster=dev dev-db-main
[TSH]       DEBU Extracted username "githubactions" from the identity file githubactions.txt. tsh/tsh.go:1918
[TSH]       DEBU Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:2110
[CLIENT]    DEBU not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3074
            DEBU Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:105
[CLIENT]    INFO Connecting to proxy=teleport.example.com:3023 login="githubactions" client/api.go:2322
            DEBU No valid environment variables found. client/proxy.go:116
[HTTP:PROX] DEBU No proxy set in environment, returning direct dialer. proxy/proxy.go:268
[CLIENT]    INFO Successful auth with proxy teleport.example.com:3023. client/api.go:2327
[CLIENT]    DEBU Found clusters: [{"name":"admin","lastconnected":"2022-04-06T16:17:10.089203088Z","status":"online"},{"name":"dev","lastconnected":"2022-04-06T16:17:04.476063994Z","status":"online"}] client/client.go:127
[CLIENT]    DEBU Client  is connecting to auth server on cluster "dev". client/client.go:969
[TSH]       DEBU Fetching database access certificate for Database(Service=dev-db-main, Protocol=postgres, Username=, Database=) on cluster dev. tsh/db.go:92
[CLIENT]    DEBU open /Users/joe/.tsh/teleport.example.com.yaml: no such file or directory client/api.go:781

ERROR REPORT:
Original Error: *trace.NotFoundError not logged in
Stack Trace:
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/lib/client/api.go:710 github.com/gravitational/teleport/lib/client.StatusCurrent
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/db.go:104 main.databaseLogin
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/db.go:79 main.onDatabaseLogin
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/tsh.go:741 main.Run
    /private/tmp/teleport-20220403-78546-m291hq/teleport-9.0.3/tool/tsh/tsh.go:333 main.main
    /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/proc.go:250 runtime.main
    /opt/homebrew/Cellar/go/1.18/libexec/src/runtime/asm_arm64.s:1259 runtime.goexit
User Message: not logged in

> tsh ls --debug --proxy=teleport.example.com:443 --identity=githubactions.txt --login=githubactions --cluster=dev
DEBU [TSH]       Extracted username "githubactions" from the identity file githubactions.txt. tsh/tsh.go:1918
DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:2110
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3074
DEBU             Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:105
INFO [CLIENT]    Connecting to proxy=teleport.example.com:3023 login="githubactions" client/api.go:2322
DEBU             No valid environment variables found. client/proxy.go:116
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:268
INFO [CLIENT]    Successful auth with proxy teleport.example.com:3023. client/api.go:2327
DEBU [CLIENT]    Found clusters: [{"name":"admin","lastconnected":"2022-04-06T16:19:13.044234568Z","status":"online"},{"name":"dev","lastconnected":"2022-04-06T16:19:04.475590873Z","status":"online"}] client/client.go:127
DEBU [CLIENT]    Client  is connecting to auth server on cluster "dev". client/client.go:969
Node Name                                Address         Labels
---------------------------------------- --------------- -----------------
<host>-us-east-2-compute-internal <host>:3022 nodetype=ecs-host
```

After logging in via Github SSO to my user, the same `tsh db ls` command begins with the provided identity user but ends up using my `joeportela` certs later on.
```
> tsh login --proxy=teleport.example.com:443
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:58438/b2ad2e08-e89c-46a5-822c-343822eaec07
> Profile URL:        https://teleport.example.com:443
  Logged in as:       joeportela
  Cluster:            admin
  Roles:              access, eng
  Logins:             joeportela, ec2-user
  Kubernetes:         enabled
  Valid until:        2022-04-06 20:20:01 -0400 EDT [valid for 8h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

> tsh db ls --debug --proxy=teleport.example.com:443 --identity=githubactions.txt --login=githubactions --cluster=dev
DEBU [TSH]       Extracted username "githubactions" from the identity file githubactions.txt. tsh/tsh.go:1918
DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:2110
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport.example.com:443 client/api.go:3074
DEBU             Attempting GET teleport.example.com:443/webapi/ping webclient/webclient.go:105
INFO [CLIENT]    Connecting to proxy=teleport.example.com:3023 login="githubactions" client/api.go:2322
DEBU             No valid environment variables found. client/proxy.go:116
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:268
INFO [CLIENT]    Successful auth with proxy teleport.example.com:3023. client/api.go:2327
DEBU [CLIENT]    Found clusters: [{"name":"admin","lastconnected":"2022-04-06T16:20:10.657186454Z","status":"online"},{"name":"dev","lastconnected":"2022-04-06T16:20:04.476102699Z","status":"online"}] client/client.go:127
DEBU [CLIENT]    Client  is connecting to auth server on cluster "dev". client/client.go:969
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/joe/.tsh/keys/teleport.example.com/joeportela-x509.pem" valid until "2022-04-07 00:20:01 +0000 UTC". client/keystore.go:307
DEBU [KEYSTORE]  Reading certificates from path "/Users/joe/.tsh/keys/teleport.example.com/joeportela-ssh/admin-cert.pub". client/keystore.go:330
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/joe/.tsh/keys/teleport.example.com/joeportela-x509.pem" valid until "2022-04-07 00:20:01 +0000 UTC". client/keystore.go:307
Name        Description                 Labels                                                                 Connect
----------- --------------------------- ---------------------------------------------------------------------- -------
dev-db-main Aurora cluster in us-east-2 account-id=<account>,endpoint-type=primary,engine-version=12.8,e...
```

### PR DESCRIPTION
**Pull request by timothyb89**
This enhances support for identity files in tsh, which previously only worked for regular SSH access. The largest blocker for support is that tsh uses profiles for all non-SSH resource access, and profiles have a direct mapping to some on-disk resources. This patch works around this in a few ways:
 * Virtual profiles: When an identity file is specified with `-i`, we use it to create an in-memory virtual profile using the cert as the root identity _and_ for every `RouteToDatabase` (and in the future, app) field contained in the cert.
 * Virtual profile paths: Certain profile operations require paths to valid certificates and other resources on disk, which may not exist inside the identity file.

   As the driving use-case for this change is integration with Machine ID, we can "cheat" and pass the correct paths to tsh via
   environment variables. A cooperating wrapper in `tbot` will execute `tsh` with appropriate flags and environment variables, which override tsh's usual certifiate paths. This allows commands like `tsh db connect ...` to work as expected.
 * Key stores: previously we used a `noLocalKeyStore{}` with which all lookups fail. This patch replaces it with an in-memory keystore if a client key is available.
 * Profile status: lastly, we modify `StatusCurrent()` to accept an identity file path and load virtual profiles when set.

This particular change is primarily targets database support, but lays the groundwork for app and Kubernetes support. We'll work on support for them in future PRs.

Partially fixes #11770

### CODE REVIEW

**Comment by Tener** [comment]
> * As the driving use-case for this change is integration with Machine ID, we can "cheat" and pass the correct paths to tsh via
>   environment variables. A cooperating wrapper in `tbot` will execute `tsh` with appropriate flags and environment variables, which override tsh's usual certifiate paths. This allows commands like `tsh db connect ...` to work as expected.

Can we use `tsh daemon` instead? This would have the benefit of sharing that capability with Teleport Connect, and we wouldn't have to invent some ad-hoc protocol, just use gRPC which is already in place.

File: tool/tsh/db.go [hunk 1]
```diff
@@ -124,33 +124,42 @@ func databaseLogin(cf *CLIConf, tc *client.TeleportClient, db tlsca.RouteToDatab
 		// ref: https://redis.io/commands/auth
 		db.Username = defaults.DefaultRedisUsername
 	}
-	profile, err := client.StatusCurrent(cf.HomePath, cf.Proxy)
+
+	// Note: we don't use StatusCurrentWithIdentity here as virtual identity
+	// profiles are read-only.
+	profile, err := client.StatusCurrentWithIdentity(cf.HomePath, cf.Proxy, cf.IdentityFileIn)
```
Comment (Tener) [inline tool/tsh/db.go:130]: Would it make sense to separate the concept of read-only profile from identity-based profile? Right now both are expressed with catch-all "virtual" designation, but it feels like a leaky abstraction.

File: tool/tsh/db.go [hunk 2]
```diff
@@ -124,33 +124,42 @@ func databaseLogin(cf *CLIConf, tc *client.TeleportClient, db tlsca.RouteToDatab
...
-		})
-		return trace.Wrap(err)
-	}); err != nil {
-		return trace.Wrap(err)
-	}
-	if err = tc.LocalAgent().AddDatabaseKey(key); err != nil {
-		return trace.Wrap(err)
+	// Identity files contain themselves act as the database credentials (if
+	// any), so don't bother fetching new certs.
+	if profile.IsVirtual {
```
Comment (Tener) [inline tool/tsh/db.go:137]: Is there a way to restructure the code so that we don't increase the complexity massively by having each and every operation support "virtual profiles" in explicit way?

File: tool/tsh/db.go [hunk 3]
```diff
@@ -124,33 +124,42 @@ func databaseLogin(cf *CLIConf, tc *client.TeleportClient, db tlsca.RouteToDatab
...
+		log.Info("Note: already logged in due to an identity file (`-i ...`); will only update database config files.")
+	} else {
+		var key *client.Key
+		if err = client.RetryWithRelogin(cf.Context, tc, func() error {
```
Comment (Tener) [inline tool/tsh/db.go:141]: Should we perhaps add virtual (read-only?) profile handling to `RetryWithLogin` to have uniform support across the various ops?

File: tool/tsh/db.go [hunk 4]
```diff
@@ -275,7 +292,7 @@ func onDatabaseConfig(cf *CLIConf) error {
 	if err != nil {
 		return trace.Wrap(err)
 	}
-	profile, err := client.StatusCurrent(cf.HomePath, cf.Proxy)
+	profile, err := client.StatusCurrentWithIdentity(cf.HomePath, cf.Proxy, cf.IdentityFileIn)
```
Comment (Tener) [inline tool/tsh/db.go:295]: Seeing how many instances of `StatusCurrent` had to be updated I wonder if we can have a helper method taking in CLIConf instead? This way we can ensure consistency across the board and reduce the risk of someone using the wrong method (without `cf.IdentityFileIn`)

**Review by Tener — COMMENTED** [review]
A couple of high-level comments. In general the concept of "virtual profiles" looks complex enough to benefit from RFD - we are adding a lot of complexity here which will be costly in the long run.

File: tool/tsh/db.go (hunk 3 above)
Comment (timothyb89) [reply tool/tsh/db.go:141]: I'd like to give this a deeper look. My gut feeling is that it'd be similarly verbose: everything that issues certs would need to see the identity file, skip reissuing certs, and then store to memory rather than disk. We'd still have issues with profiles and especially the paths that get passed to e.g. database CLIs that are expected to be on disk.

File: tool/tsh/db.go (hunk 2 above)
Comment (timothyb89) [reply tool/tsh/db.go:137]: I don't much like the verbosity either, but ultimately certain codepaths (like this one) do things that will fail when given an identity file. Arguably when using an identity file I don't think any additional certs should get written to disk, and moreover `RetryWithRelogin()` and `IssueUserCertsWithMFA()` will fail on Machine ID identity files as they're explicitly non-renewable.

If we (per your comment below) made `RetryWithRelogin` and friends identity-aware (i.e. effectively a no-op), we might be able to skip more of these checks. It's hard for me to predict if that'd be significantly simpler, though.

(and wow, that comment is unreadable, whoops...)

**Comment by timothyb89** [comment]
> Can we use `tsh daemon` instead? This would have the benefit of sharing that capability with Teleport Connect, and we wouldn't have to invent some ad-hoc protocol, just use gRPC which is already in place.

To be honest I wasn't aware of that new functionality - it's definitely worth a look. I fear it'll have similar limitations for our needs on the Machine ID front, though. We specifically need the proxying functionality and without changes none of these tsh codepaths will simply trust an external identity without trying to do problematic things (like fetching new certs or reading/writing files).

File: tool/tsh/db.go (hunk 1 above)
Comment (timothyb89) [reply tool/tsh/db.go:130]: It might, though I'm not sure what that use-case would be. As far as I know the only place read-only profiles make sense is identity-based profiles: there's no other way to get a certificate that has database/app/k8s/etc fields.

Either you go the usual way through tsh (which is inherently read/write), or you use `tctl auth sign ...` / Machine ID in which case you bring an identity file with whichever additional fields you'd like. A read-only tsh profile wouldn't be able to request e.g. database certs in a very useful way.

**Comment by Tener** [comment]
> > Can we use `tsh daemon` instead? This would have the benefit of sharing that capability with Teleport Connect, and we wouldn't have to invent some ad-hoc protocol, just use gRPC which is already in place.
> 
> To be honest I wasn't aware of that new functionality - it's definitely worth a look. I fear it'll have similar limitations for our needs on the Machine ID front, though. We specifically need the proxying functionality and without changes none of these tsh codepaths will simply trust an external identity without trying to do problematic things (like fetching new certs or reading/writing files).

Yes, I think the changes will be needed, I just figured the wrapper looks similar to `tsh daemon` functionality, so perhaps worth sharing the code paths. Also, it may be that Teleport Connect will need use the same functionality either directly (with user-provided identities) or behind the scenes (as some sort of background mechanism).

**Comment by timothyb89** [comment]
> Yes, I think the changes will be needed, I just figured the wrapper looks similar to `tsh daemon` functionality, so perhaps worth sharing the code paths. Also, it may be that Teleport Connect will need use the same functionality either directly (with user-provided identities) or behind the scenes (as some sort of background mechanism).

I've given the daemon functionality a quick glance and my takeaway so far is: I definitely like the gRPC interface and it could be a big help for Machine ID's needs in the future, but doesn't really provide any of the functionality we want at the moment (mainly `tsh proxy`, `tsh db`, `tsh ssh`). The latter already works and that `proxy` and `db` are broken is considered a bug (#11770).

That said, since our main supported interface to tsh will be through CLI wrappers in tbot (`tbot proxy`, etc) I think it would be feasible to migrate to `tsh daemon` if/when it supports the functionality we need for Machine ID.

Timeline-wise we're in a bit of a awkward spot with access capabilities in Machine ID: we don't support Teleport's new out-of-the-box configuration since everything's now behind TLS routing by default, which requires a local proxy. While we can issue certs for databases they're unusable currently, and even SSH needs awkward workarounds. So, there's a desire to get _some_ functionality in in the near term and I'm not opposed to replacing it with something better in the long/medium-term.

File: tool/tsh/db.go (hunk 4 above)
Comment (timothyb89) [reply tool/tsh/db.go]: I've gone ahead and merged all the functionality into `StatusCurrent()`. We need to pass along the identity path but it's easily available everywhere, so I think this should be modestly nicer overall.

File: tool/tsh/db.go (hunk 2 above)
Comment (timothyb89) [reply tool/tsh/db.go:155]: With the latest change I've merged everything into the one codepath (`StatusCurrent()`) and we have a total of 3 `IsVirtual` checks for core + database access.

I know app (and probably k8s) access will need some of their own when we circle back to support them properly, but I don't think this is especially onerous - worst case if some specific handling is missing it fails due to some identity-related error exactly as it would already today.

Overall, though, I think the alternative where we modify `RetryWithRelogin` to support identity files ends up quite a bit more complicated and I'd rather direct that effort to a proper refactoring where hacks like this aren't needed at all.

File: tool/tsh/db.go (hunk 3 above)
Comment (timothyb89) [reply tool/tsh/db.go:159]: I've looked a bit more, and I don't think we really save anything here: `RetryWithRelogin()` (and more specifically, `client.Login()`) just manages the core client identity which we already configure with the identity file at startup.

Database / Kubernetes / App access all use profile certs and never try to use the core identity even if it does actually have the proper permissions. Unfortunately the only shared codepath for these is the profiles system, which is what necessitated this hacky solution to begin with.

Ideally I'd like to see us invest in a larger refactoring to clean all of this up but frankly I don't even know what I'd want it to look like, tsh has a lot of functionality to juggle. In the mean time hopefully we can enable at least the Machine ID use-case.

File: lib/client/api.go [hunk 5]
```diff
@@ -398,6 +402,81 @@ func MakeDefaultConfig() *Config {
...
+func VirtualPathEnvName(kind VirtualPathKind, params VirtualPathParams) string {
+	components := append([]string{
+		VirtualPathEnvPrefix,
+		string(kind),
+	}, params...)
+
+	return strings.ToUpper(strings.Join(components, "_"))
+}
+
+// VirtualPathEnvName determines an ordered list of environment variables that
```
Comment (Tener) [inline lib/client/api.go:463]:
```suggestion
// VirtualPathEnvNames determines an ordered list of environment variables that
```

**Review by Tener — APPROVED** [review]

File: lib/client/api.go [hunk 6]
```diff
@@ -398,6 +402,81 @@ func MakeDefaultConfig() *Config {
...
+
+// VirtualPathParams are an ordered list of additional optional parameters
+// for a virtual path. They can be used to specify a more exact resource name
+// if multiple might be available. Simpler integrations can instead only
+// specify the kind and it will apply wherever a more specific env var isn't
+// found.
+type VirtualPathParams []string
+
+// VirtualPathCAParams returns parameters for selecting CA certificates.
+func VirtualPathCAParams(caType types.CertAuthType) VirtualPathParams {
```
Comment (zmb3) [inline lib/client/api.go:429]: If this needs to be kept in sync with the CA types I would put a comment in both locations mentioning that any updates need to be reflected on the other side.

File: lib/client/api.go [hunk 7]
```diff
@@ -705,31 +832,120 @@ func ReadProfileStatus(profileDir string, profileName string) (*ProfileStatus, e
...
+	opts.IsVirtual = true
+
+	return profileFromKey(key, opts)
+}
+
+// ReadProfileStatus reads in the profile as well as the associated certificate
+// and returns a *ProfileStatus which can be used to print the status of the
+// profile.
+func ReadProfileStatus(profileDir string, profileName string) (*ProfileStatus, error) {
+	var err error
```
Comment (zmb3) [inline lib/client/api.go:892]: Can you remove this?

File: lib/client/api.go [hunk 8]
```diff
@@ -1192,7 +1408,36 @@ func NewClient(c *Config) (tc *TeleportClient, err error) {
 		// if the client was passed an agent in the configuration and skip local auth, use
 		// the passed in agent.
 		if c.Agent != nil {
-			tc.localAgent = &LocalKeyAgent{Agent: c.Agent, keyStore: noLocalKeyStore{}, siteName: tc.SiteName}
+			webProxyHost, _ := tc.WebProxyHostPort()
```
Comment (zmb3) [inline lib/client/api.go:1411]: What's the _ that you're ignoring here?

**Review by zmb3 — APPROVED** [review]

File: lib/client/api.go (hunk 5 above)
Comment (timothyb89) [reply lib/client/api.go:463]: whoops, thanks!

File: lib/client/api.go (hunk 8 above)
Comment (timothyb89) [reply lib/client/api.go:1411]: That's the port (int). That said we also have a `WebProxyHost()` helper that does exactly this, so I'll switch to it.

File: lib/client/api.go (hunk 7 above)
Comment (timothyb89) [reply lib/client/api.go:892]: Assuming you mean the `err`, yup, will do.

File: lib/client/api.go (hunk 6 above)
Comment (timothyb89) [reply lib/client/api.go:429]: Oddly tsh only ever uses the HostCA. I do kind of wonder if this is a problem for new clusters since I think the database CA is meant to be used 

In any case the only thing that would need to be updated is on Machine ID's end if/when we ever needed to pass multiple CAs. Right now we're just using the fallback case (just `TSH_VIRTUAL_PATH_CA`, with no CA type) in https://github.com/gravitational/teleport/pull/12687 since we don't care to disambiguate (at least for now).
