### PR TITLE
Fix `underlying reader not a terminal` issues

### LINKED ISSUE #24810: rsync -rsh "tsh ssh" does not work with the `--headless` option
Expected behavior:
`rsync --rsh` functionality will continue to work with `tsh ssh` when using the `--headless` option

Current behavior:
`rsync --rsh` fails with errors.  A user observed the following error:
~~~
ERROR: underlying reader is not a terminal

rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.3]
~~~

In my recreate I hit the following error:
~~~
protocol version mismatch -- is your shell clean?
(see the rsync man page for an explanation)
rsync error: protocol incompatibility (code 2) at /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/rsync/rsync/compat.c(61) [sender=2.6.9]
~~~

Failed `rsync --rsh` with the `--headless` functionality attempted:
~~~
$ rsync --rsh="tsh ssh -d --headless --proxy=test-cluster1.plainsofconquest.com" ~/test-id2 root@iamtheappman:rsync-test-delete-me/
2023-04-19T11:16:12-04:00 DEBU [TSH]       Web proxy port was not set. Attempting to detect port number to use. tsh/tsh.go:3635
2023-04-19T11:16:12-04:00 DEBU [TSH]       Resolving default proxy port (insecure: false) tsh/resolve_default_addr.go:111
2023-04-19T11:16:12-04:00 DEBU [TSH]       Trying test-cluster1.plainsofconquest.com:3080... tsh/resolve_default_addr.go:99
2023-04-19T11:16:12-04:00 DEBU [TSH]       Trying test-cluster1.plainsofconquest.com:443... tsh/resolve_default_addr.go:99
2023-04-19T11:16:12-04:00 DEBU [TSH]       Address test-cluster1.plainsofconquest.com:443 succeeded. Selected as canonical proxy address tsh/resolve_default_addr.go:191
2023-04-19T11:16:12-04:00 DEBU [TSH]       Waiting for all in-flight proxy address tests to finish tsh/resolve_default_addr.go:139
2023-04-19T11:16:12-04:00 DEBU [TSH]       Proxy address test failed error:[Get "https://test-cluster1.plainsofconquest.com:3080/webapi/ping": context canceled] tsh/resolve_default_addr.go:63
2023-04-19T11:16:12-04:00 INFO [CLIENT]    No teleport login given. defaulting to paulschisa client/api.go:959
2023-04-19T11:16:12-04:00 INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.cECLhqmlHq/Listeners" client/api.go:3995
2023-04-19T11:16:12-04:00 DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:3449
2023-04-19T11:16:12-04:00 DEBU [CLIENT]    not using loopback pool for remote proxy addr: test-cluster1.plainsofconquest.com:443 client/api.go:3950
2023-04-19T11:16:12-04:00 DEBU             Attempting GET test-cluster1.plainsofconquest.com:443/webapi/ping/headless webclient/webclient.go:129
2023-04-19T11:16:12-04:00 INFO [CLIENT]    Connecting to proxy=test-cluster1.plainsofconquest.com:443 login="root" using TLS Routing client/api.go:2847
2023-04-19T11:16:12-04:00 DEBU [CLIENT]    "Activating relogin on error Unable to connect to ssh proxy at test-cluster1.plainsofconquest.com:443. Confirm connectivity and availability.\n\tfailed to fetch TLS key for paulschisa\n\t\tkey for {ProxyHost:test-cluster1.plainsofconquest.com Username:paulschisa ClusterName:} not found." client/api.go:530
2023-04-19T11:16:12-04:00 DEBU             ALPN connection upgrade required for "test-cluster1.plainsofconquest.com:443": false. alpnproxy/conn_upgrade.go:81
2023-04-19T11:16:12-04:00 DEBU [CLIENT]    Attempting to login with a new RSA private key. client/api.go:3343
protocol version mismatch -- is your shell clean?
(see the rsync man page for an explanation)
rsync error: protocol incompatibility (code 2) at /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/rsync/rsync/compat.c(61) [sender=2.6.9]
2023-04-19T11:16:13-04:00 DEBU [CLIENT]    HTTPS client init(proxyAddr=test-cluster1.plainsofconquest.com:443, insecure=false, extraHeaders=map[]) client/weblogin.go:308
~~~

Successful  `rsync -rsh` when the `--headless` flag is removed
~~~
$ rsync --rsh="tsh ssh -d --proxy=test-cluster1.plainsofconquest.com" ~/test-id2 root@iamtheappman:rsync-test-delete-me/
2023-04-19T11:17:32-04:00 DEBU [TSH]       Web proxy port was not set. Attempting to detect port number to use. tsh/tsh.go:3635
2023-04-19T11:17:32-04:00 DEBU [TSH]       Resolving default proxy port (insecure: false) tsh/resolve_default_addr.go:111
2023-04-19T11:17:32-04:00 DEBU [TSH]       Trying test-cluster1.plainsofconquest.com:3080... tsh/resolve_default_addr.go:99
2023-04-19T11:17:33-04:00 DEBU [TSH]       Trying test-cluster1.plainsofconquest.com:443... tsh/resolve_default_addr.go:99
2023-04-19T11:17:33-04:00 DEBU [TSH]       Address test-cluster1.plainsofconquest.com:443 succeeded. Selected as canonical proxy address tsh/resolve_default_addr.go:191
2023-04-19T11:17:33-04:00 DEBU [TSH]       Waiting for all in-flight proxy address tests to finish tsh/resolve_default_addr.go:139
2023-04-19T11:17:33-04:00 DEBU [TSH]       Proxy address test failed error:[Get "https://test-cluster1.plainsofconquest.com:3080/webapi/ping": context canceled] tsh/resolve_default_addr.go:63
2023-04-19T11:17:33-04:00 INFO [CLIENT]    No teleport login given. defaulting to paulschisa client/api.go:959
2023-04-19T11:17:33-04:00 INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.cECLhqmlHq/Listeners" client/api.go:3995
2023-04-19T11:17:33-04:00 DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:3449
2023-04-19T11:17:33-04:00 DEBU [CLIENT]    not using loopback pool for remote proxy addr: test-cluster1.plainsofconquest.com:443 client/api.go:3950
2023-04-19T11:17:33-04:00 DEBU             Attempting GET test-cluster1.plainsofconquest.com:443/webapi/ping webclient/webclient.go:129
2023-04-19T11:17:33-04:00 DEBU [CLIENT]    Activating relogin on error no SSH auth methods loaded, are you logged in?. client/api.go:530
2023-04-19T11:17:33-04:00 DEBU             ALPN connection upgrade required for "test-cluster1.plainsofconquest.com:443": false. alpnproxy/conn_upgrade.go:81
2023-04-19T11:17:33-04:00 DEBU [CLIENT]    Attempting to login with a new RSA private key. client/api.go:3343
2023-04-19T11:17:33-04:00 DEBU [CLIENT]    not using loopback pool for remote proxy addr: test-cluster1.plainsofconquest.com:443 client/api.go:3950
2023-04-19T11:17:33-04:00 DEBU [CLIENT]    HTTPS client init(proxyAddr=test-cluster1.plainsofconquest.com:443, insecure=false, extraHeaders=map[]) client/weblogin.go:308
2023-04-19T11:17:33-04:00 INFO [CLIENT]    Waiting for response at: http://127.0.0.1:50519. client/redirect.go:157
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:50519/d3c95bcd-d217-40b4-ad6d-6a7de1a790cb
2023-04-19T11:17:35-04:00 DEBU [CLIENT]    Got response from browser. client/weblogin.go:396
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Adding known host ip-172-31-36-239-ec2-internal with proxy test-cluster1.plainsofconquest.com client/trusted_certs_store.go:393
2023-04-19T11:17:35-04:00 INFO [KEYAGENT]  Loading SSH key for user "pschisa" and cluster "ip-172-31-36-239-ec2-internal". client/keyagent.go:195
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 INFO [CLIENT]    Connecting to proxy=test-cluster1.plainsofconquest.com:443 login="pschisa" using TLS Routing client/api.go:2847
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAglBnboY4SwM6gmpYFkr82AzMqx3awEjX7igKsM+EB2BoAAAADAQABAAABAQDfqNU5LkmqVpZ55NYz0gDrsz1wm9ctzCkAkw4a7XxkvWiBLvlNtnv609pLW3HyT32SjJRGiJ7OIynJXGPKitHbOIED9n+VVHWWh7VeTl7RW0SB7Lw8iFX/8+Szj2o3eHCMzxWw0j/uxQZbbyu0SkawCSTUJ6dFSeeXPZ4sjujALkqZNbK4giOH9soSbXyVGe9QMKdsgLflhPsp6iIjCBXvmcQflH/q3G9F1kiPzvfKTU4ZRA2B3l4DiaGJLyiYqvu/bxQrAxZ9AO2PDIa3B38QmCFzn8sz30XUn3CSLIxbXguiarR3eOpinVR1R2liSyQlUqOstFxYYI4Oj4GFwX9DAAAAAAAAAAAAAAACAAAAAAAAATsAAABCMzllMGJmZTYtYjBiMS00ZmM4LTkzNmMtMmJkODdmNmU2Yzc3LmlwLTE3Mi0zMS0zNi0yMzktZWMyLWludGVybmFsAAAAJDM5ZTBiZmU2LWIwYjEtNGZjOC05MzZjLTJiZDg3ZjZlNmM3NwAAADh0ZXN0LWNsdXN0ZXItbm9kZTEtdXMtZWFzdC5pcC0xNzItMzEtMzYtMjM5LWVjMi1pbnRlcm5hbAAAABp0ZXN0LWNsdXN0ZXItbm9kZTEtdXMtZWFzdAAAAAlsb2NhbGhvc3QAAAAJMTI3LjAuMC4xAAAAAzo6MQAAACJ0ZXN0LWNsdXN0ZXIxLnBsYWluc29mY29ucXVlc3QuY29tAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAY+pr9f//////////AAAAAAAAAF0AAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAhAAAAHWlwLTE3Mi0zMS0zNi0yMzktZWMyLWludGVybmFsAAAAD3gtdGVsZXBvcnQtcm9sZQAAAAkAAAAFUHJveHkAAAAAAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEA3aQcElB9GGFkE9lVYsJix8h6K6P5vo/MPCl4L582+Ppe2QpWY6bK2Z8XQ1HMtkXR18vnMY4a8Xv4PHob3fifTw1hzRFfbtWQdiihBD7y5oUZNZurBnKnELgVXxEgJYUBPWTNTF2wA2z6KoDX/w+cmUiTXp+WyDnlJiDXkWomsKCeRM+4oKee0I+Ht8qwMlyCS26Dqxlpl20h9mJalVRBhepK22wY24oOMFfqAinpD2dO61ocMj7rMiToRMe4ZboghCC18DXRtBxL2Zt1+qWVivp/vBQDiu7V1CrBRnoK85iGgPOxnMuk7E/XjXHUIv+0Pspz+UtZth63iWy6+/bbWwAAARQAAAAMcnNhLXNoYTItNTEyAAABANNWF2QHGRhFyzotmO6vRbvEGt9miypFPLVguyqh7YAGRJtkmRJ5T9/pBm+MSIwJOBPx2NAu/nje8PmNvQFiFwOf5/l2lMMPaxTTThaDItMHxaG2E36/tLJssT6K2TeyL2ADkCqIShiUs4pLRq4piuBiuS/CuRH2hc7yXmuW3SnzfURcgtcwZ0jxxFRBT5j9FagMhTj9frga3kIajlCYkGqRKRIXSeNAhnov+gxTNlU1cd/jAt5fjCsJvVGN4VANejYuSzW3CnmShSf+DuR0TqNj+laUvUYSmVUsdxRypjUHlLnR4eJVclVygxHq53W32A/lJcCs/z0FSEnUslVuXs8=\n." client/keyagent.go:367
2023-04-19T11:17:35-04:00 DEBU [KEYAGENT]  Validated host test-cluster1.plainsofconquest.com:443. client/keyagent.go:373
2023-04-19T11:17:35-04:00 INFO [CLIENT]    Successful auth with proxy test-cluster1.plainsofconquest.com:443. client/api.go:2852
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Adding known host ip-172-31-20-162-us-west-1-compute-internal with proxy test-cluster1.plainsofconquest.com client/trusted_certs_store.go:393
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Adding known host ip-172-31-36-239-ec2-internal with proxy test-cluster1.plainsofconquest.com client/trusted_certs_store.go:393
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Adding known host schisa.teleport.sh with proxy test-cluster1.plainsofconquest.com client/trusted_certs_store.go:393
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 INFO [CLIENT]    Connecting to proxy=test-cluster1.plainsofconquest.com:443 login="pschisa" using TLS Routing client/api.go:2847
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301
2023-04-19T11:17:35-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:35-04:00 DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAglBnboY4SwM6gmpYFkr82AzMqx3awEjX7igKsM+EB2BoAAAADAQABAAABAQDfqNU5LkmqVpZ55NYz0gDrsz1wm9ctzCkAkw4a7XxkvWiBLvlNtnv609pLW3HyT32SjJRGiJ7OIynJXGPKitHbOIED9n+VVHWWh7VeTl7RW0SB7Lw8iFX/8+Szj2o3eHCMzxWw0j/uxQZbbyu0SkawCSTUJ6dFSeeXPZ4sjujALkqZNbK4giOH9soSbXyVGe9QMKdsgLflhPsp6iIjCBXvmcQflH/q3G9F1kiPzvfKTU4ZRA2B3l4DiaGJLyiYqvu/bxQrAxZ9AO2PDIa3B38QmCFzn8sz30XUn3CSLIxbXguiarR3eOpinVR1R2liSyQlUqOstFxYYI4Oj4GFwX9DAAAAAAAAAAAAAAACAAAAAAAAATsAAABCMzllMGJmZTYtYjBiMS00ZmM4LTkzNmMtMmJkODdmNmU2Yzc3LmlwLTE3Mi0zMS0zNi0yMzktZWMyLWludGVybmFsAAAAJDM5ZTBiZmU2LWIwYjEtNGZjOC05MzZjLTJiZDg3ZjZlNmM3NwAAADh0ZXN0LWNsdXN0ZXItbm9kZTEtdXMtZWFzdC5pcC0xNzItMzEtMzYtMjM5LWVjMi1pbnRlcm5hbAAAABp0ZXN0LWNsdXN0ZXItbm9kZTEtdXMtZWFzdAAAAAlsb2NhbGhvc3QAAAAJMTI3LjAuMC4xAAAAAzo6MQAAACJ0ZXN0LWNsdXN0ZXIxLnBsYWluc29mY29ucXVlc3QuY29tAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAY+pr9f//////////AAAAAAAAAF0AAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAhAAAAHWlwLTE3Mi0zMS0zNi0yMzktZWMyLWludGVybmFsAAAAD3gtdGVsZXBvcnQtcm9sZQAAAAkAAAAFUHJveHkAAAAAAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEA3aQcElB9GGFkE9lVYsJix8h6K6P5vo/MPCl4L582+Ppe2QpWY6bK2Z8XQ1HMtkXR18vnMY4a8Xv4PHob3fifTw1hzRFfbtWQdiihBD7y5oUZNZurBnKnELgVXxEgJYUBPWTNTF2wA2z6KoDX/w+cmUiTXp+WyDnlJiDXkWomsKCeRM+4oKee0I+Ht8qwMlyCS26Dqxlpl20h9mJalVRBhepK22wY24oOMFfqAinpD2dO61ocMj7rMiToRMe4ZboghCC18DXRtBxL2Zt1+qWVivp/vBQDiu7V1CrBRnoK85iGgPOxnMuk7E/XjXHUIv+0Pspz+UtZth63iWy6+/bbWwAAARQAAAAMcnNhLXNoYTItNTEyAAABANNWF2QHGRhFyzotmO6vRbvEGt9miypFPLVguyqh7YAGRJtkmRJ5T9/pBm+MSIwJOBPx2NAu/nje8PmNvQFiFwOf5/l2lMMPaxTTThaDItMHxaG2E36/tLJssT6K2TeyL2ADkCqIShiUs4pLRq4piuBiuS/CuRH2hc7yXmuW3SnzfURcgtcwZ0jxxFRBT5j9FagMhTj9frga3kIajlCYkGqRKRIXSeNAhnov+gxTNlU1cd/jAt5fjCsJvVGN4VANejYuSzW3CnmShSf+DuR0TqNj+laUvUYSmVUsdxRypjUHlLnR4eJVclVygxHq53W32A/lJcCs/z0FSEnUslVuXs8=\n." client/keyagent.go:367
2023-04-19T11:17:35-04:00 DEBU [KEYAGENT]  Validated host test-cluster1.plainsofconquest.com:443. client/keyagent.go:373
2023-04-19T11:17:36-04:00 INFO [CLIENT]    Successful auth with proxy test-cluster1.plainsofconquest.com:443. client/api.go:2852
2023-04-19T11:17:36-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:36-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:36-04:00 DEBU [CLIENT]    Device Trust: device authentication failed error:[
ERROR REPORT:
Original Error: *native.statusError device key not found, was the device enrolled?
Stack Trace:
	github.com/gravitational/teleport/lib/devicetrust/native/device_darwin.go:134 github.com/gravitational/teleport/lib/devicetrust/native.getDeviceCredential
	github.com/gravitational/teleport/lib/devicetrust/native/api.go:40 github.com/gravitational/teleport/lib/devicetrust/native.GetDeviceCredential
	github.com/gravitational/teleport/lib/devicetrust/authn/authn.go:54 github.com/gravitational/teleport/lib/devicetrust/authn.RunCeremony
	github.com/gravitational/teleport/lib/client/api.go:3178 github.com/gravitational/teleport/lib/client.(*TeleportClient).DeviceLogin
	github.com/gravitational/teleport/lib/client/api.go:3132 github.com/gravitational/teleport/lib/client.(*TeleportClient).AttemptDeviceLogin
	github.com/gravitational/teleport/lib/client/api.go:555 github.com/gravitational/teleport/lib/client.RetryWithRelogin
	github.com/gravitational/teleport/tool/tsh/tsh.go:3027 main.onSSH.func1
	github.com/gravitational/teleport/tool/tsh/tsh.go:2936 main.retryWithAccessRequest
	github.com/gravitational/teleport/tool/tsh/tsh.go:3026 main.onSSH
	github.com/gravitational/teleport/tool/tsh/tsh.go:1116 main.Run
	github.com/gravitational/teleport/tool/tsh/tsh.go:499 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: device key not found, was the device enrolled?] client/api.go:3138
2023-04-19T11:17:36-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:36-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:36-04:00 INFO [CLIENT]    Connecting to proxy=test-cluster1.plainsofconquest.com:443 login="pschisa" using TLS Routing client/api.go:2847
2023-04-19T11:17:36-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:36-04:00 DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301
2023-04-19T11:17:36-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:36-04:00 DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAglBnboY4SwM6gmpYFkr82AzMqx3awEjX7igKsM+EB2BoAAAADAQABAAABAQDfqNU5LkmqVpZ55NYz0gDrsz1wm9ctzCkAkw4a7XxkvWiBLvlNtnv609pLW3HyT32SjJRGiJ7OIynJXGPKitHbOIED9n+VVHWWh7VeTl7RW0SB7Lw8iFX/8+Szj2o3eHCMzxWw0j/uxQZbbyu0SkawCSTUJ6dFSeeXPZ4sjujALkqZNbK4giOH9soSbXyVGe9QMKdsgLflhPsp6iIjCBXvmcQflH/q3G9F1kiPzvfKTU4ZRA2B3l4DiaGJLyiYqvu/bxQrAxZ9AO2PDIa3B38QmCFzn8sz30XUn3CSLIxbXguiarR3eOpinVR1R2liSyQlUqOstFxYYI4Oj4GFwX9DAAAAAAAAAAAAAAACAAAAAAAAATsAAABCMzllMGJmZTYtYjBiMS00ZmM4LTkzNmMtMmJkODdmNmU2Yzc3LmlwLTE3Mi0zMS0zNi0yMzktZWMyLWludGVybmFsAAAAJDM5ZTBiZmU2LWIwYjEtNGZjOC05MzZjLTJiZDg3ZjZlNmM3NwAAADh0ZXN0LWNsdXN0ZXItbm9kZTEtdXMtZWFzdC5pcC0xNzItMzEtMzYtMjM5LWVjMi1pbnRlcm5hbAAAABp0ZXN0LWNsdXN0ZXItbm9kZTEtdXMtZWFzdAAAAAlsb2NhbGhvc3QAAAAJMTI3LjAuMC4xAAAAAzo6MQAAACJ0ZXN0LWNsdXN0ZXIxLnBsYWluc29mY29ucXVlc3QuY29tAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAY+pr9f//////////AAAAAAAAAF0AAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAhAAAAHWlwLTE3Mi0zMS0zNi0yMzktZWMyLWludGVybmFsAAAAD3gtdGVsZXBvcnQtcm9sZQAAAAkAAAAFUHJveHkAAAAAAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEA3aQcElB9GGFkE9lVYsJix8h6K6P5vo/MPCl4L582+Ppe2QpWY6bK2Z8XQ1HMtkXR18vnMY4a8Xv4PHob3fifTw1hzRFfbtWQdiihBD7y5oUZNZurBnKnELgVXxEgJYUBPWTNTF2wA2z6KoDX/w+cmUiTXp+WyDnlJiDXkWomsKCeRM+4oKee0I+Ht8qwMlyCS26Dqxlpl20h9mJalVRBhepK22wY24oOMFfqAinpD2dO61ocMj7rMiToRMe4ZboghCC18DXRtBxL2Zt1+qWVivp/vBQDiu7V1CrBRnoK85iGgPOxnMuk7E/XjXHUIv+0Pspz+UtZth63iWy6+/bbWwAAARQAAAAMcnNhLXNoYTItNTEyAAABANNWF2QHGRhFyzotmO6vRbvEGt9miypFPLVguyqh7YAGRJtkmRJ5T9/pBm+MSIwJOBPx2NAu/nje8PmNvQFiFwOf5/l2lMMPaxTTThaDItMHxaG2E36/tLJssT6K2TeyL2ADkCqIShiUs4pLRq4piuBiuS/CuRH2hc7yXmuW3SnzfURcgtcwZ0jxxFRBT5j9FagMhTj9frga3kIajlCYkGqRKRIXSeNAhnov+gxTNlU1cd/jAt5fjCsJvVGN4VANejYuSzW3CnmShSf+DuR0TqNj+laUvUYSmVUsdxRypjUHlLnR4eJVclVygxHq53W32A/lJcCs/z0FSEnUslVuXs8=\n." client/keyagent.go:367
2023-04-19T11:17:36-04:00 DEBU [KEYAGENT]  Validated host test-cluster1.plainsofconquest.com:443. client/keyagent.go:373
2023-04-19T11:17:36-04:00 INFO [CLIENT]    Successful auth with proxy test-cluster1.plainsofconquest.com:443. client/api.go:2852
2023-04-19T11:17:36-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:36-04:00 INFO [CLIENT]    Client= connecting to node=iamtheappman on cluster ip-172-31-36-239-ec2-internal client/client.go:1392
2023-04-19T11:17:36-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:36-04:00 DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAgmoWxvahLKwwTn9XKsyay0hkSuB5oxKVuvaBTHtNCyCsAAAADAQABAAABAQDYuv6wsProDHF/1Zo6jZbX2a2zOw4YJtK2ALfY0HHi6GyGEjgCn97Big1PXfUt30D6kdpF6kWKT1M3IRNMiS/UgHZoFU501VzGAkHjpydiYssDQBD6uxoC87WU9vuJyEzzddHeGg7pO+s1C7nw93+CldR5npq4B8uL2e/cDZmlhBAQ6Te8ZdX8a2j/8BNQP8kT/pNqPkvc+OIjlEi0zZLRgRRZExNnEvwGI2b0BLG/HUjqBx1763hJX50MXU1ogMeIPHc9N8PXjuv1xEPeHRLTcEhIqhJ8W6RoRlhRIiTVWytJpAGo1aimvaNzH5NkEPZvJJdvSD5B/Fq9LCus+Ee5AAAAAAAAAAAAAAACAAAAAAAAAQwAAABCMDA3ODg5OTgtZTExMy00ZTgzLTgzNTctNTdkMWE3Zjc2NmE4LmlwLTE3Mi0zMS0zNi0yMzktZWMyLWludGVybmFsAAAAJDAwNzg4OTk4LWUxMTMtNGU4My04MzU3LTU3ZDFhN2Y3NjZhOAAAACppYW10aGVhcHBtYW4uaXAtMTcyLTMxLTM2LTIzOS1lYzItaW50ZXJuYWwAAAAMaWFtdGhlYXBwbWFuAAAACWxvY2FsaG9zdAAAAAkxMjcuMC4wLjEAAAADOjoxAAAAKmVjMi0xOC0yMDktMTM4LTI1My5jb21wdXRlLTEuYW1hem9uYXdzLmNvbQAAAA0xNzIuMzEuOTQuMTc0AAAAAGQwRU3//////////wAAAAAAAABcAAAAFHgtdGVsZXBvcnQtYXV0aG9yaXR5AAAAIQAAAB1pcC0xNzItMzEtMzYtMjM5LWVjMi1pbnRlcm5hbAAAAA94LXRlbGVwb3J0LXJvbGUAAAAIAAAABE5vZGUAAAAAAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEA3aQcElB9GGFkE9lVYsJix8h6K6P5vo/MPCl4L582+Ppe2QpWY6bK2Z8XQ1HMtkXR18vnMY4a8Xv4PHob3fifTw1hzRFfbtWQdiihBD7y5oUZNZurBnKnELgVXxEgJYUBPWTNTF2wA2z6KoDX/w+cmUiTXp+WyDnlJiDXkWomsKCeRM+4oKee0I+Ht8qwMlyCS26Dqxlpl20h9mJalVRBhepK22wY24oOMFfqAinpD2dO61ocMj7rMiToRMe4ZboghCC18DXRtBxL2Zt1+qWVivp/vBQDiu7V1CrBRnoK85iGgPOxnMuk7E/XjXHUIv+0Pspz+UtZth63iWy6+/bbWwAAARQAAAAMcnNhLXNoYTItNTEyAAABAEGXJ1tz4JFx+8bVz09+ClaBE7TuAupvUUM7Zr5qU4GDuZNMn3rASr3m4M+0gGKXpctoYkI1niAU455pfWtXxuRAn2tLUribpNU9iR/idUv/WyPOcyNJJSdmbwp+MAEAkPw7GQ/bvtkzxF+yCJdBJakjESPdUtuV05MvK5myAVD3FlUUR4VrmcBN+TYbtEPUxYHme98qOESELezRZ+hSwb5qaQlBhaXzqQphvlfYkB2LPnzwp1nJmMmZ+0ZAiaKoqQVaqpfS2NXYIgE7APDWR/ncF0VX2QJ0dz7Tui5RMGWfOVg2KIkjZkq/lkR9i9zS+EXwjajk11xLRnW79xZkT14=\n." client/keyagent.go:367
2023-04-19T11:17:36-04:00 DEBU [KEYAGENT]  Validated host iamtheappman:0@default@ip-172-31-36-239-ec2-internal. client/keyagent.go:373
2023-04-19T11:17:37-04:00 INFO [CLIENT]    "Access denied to root connecting to iamtheappman:0: failed to connect to \"iamtheappman:0@default@ip-172-31-36-239-ec2-internal\"\n\tssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain" client/client.go:1555
2023-04-19T11:17:37-04:00 DEBU [KEYSTORE]  Reading certificates from path "/Users/paulschisa/.tsh/keys/test-cluster1.plainsofconquest.com/pschisa-ssh/ip-172-31-36-239-ec2-internal-cert.pub". client/keystore.go:341
2023-04-19T11:17:37-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:37-04:00 DEBU [CLIENT]    Attempting to issue a single-use user certificate with an MFA check. client/client.go:484
2023-04-19T11:17:37-04:00 DEBU [CLIENT]    WebAuthn: prompting devices with origin "https://test-cluster1.plainsofconquest.com:443" client/mfa.go:225
2023-04-19T11:17:37-04:00 DEBU             Attempting platform login webauthncli/api.go:149
2023-04-19T11:17:37-04:00 DEBU             Touch ID: using credential "e9ce0bb6-3403-4239-bbf5-28f56c11d835" touchid/api.go:483
Using platform authenticator, follow the OS prompt
2023-04-19T11:17:40-04:00 DEBU [CLIENT]    Issued single-use user certificate after an MFA check. client/client.go:564
2023-04-19T11:17:40-04:00 INFO [CLIENT]    Client= connecting to node=iamtheappman on cluster ip-172-31-36-239-ec2-internal client/client.go:1392
2023-04-19T11:17:40-04:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-04-20 03:17:34 +0000 UTC". client/client_store.go:91
2023-04-19T11:17:40-04:00 DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAgmoWxvahLKwwTn9XKsyay0hkSuB5oxKVuvaBTHtNCyCsAAAADAQABAAABAQDYuv6wsProDHF/1Zo6jZbX2a2zOw4YJtK2ALfY0HHi6GyGEjgCn97Big1PXfUt30D6kdpF6kWKT1M3IRNMiS/UgHZoFU501VzGAkHjpydiYssDQBD6uxoC87WU9vuJyEzzddHeGg7pO+s1C7nw93+CldR5npq4B8uL2e/cDZmlhBAQ6Te8ZdX8a2j/8BNQP8kT/pNqPkvc+OIjlEi0zZLRgRRZExNnEvwGI2b0BLG/HUjqBx1763hJX50MXU1ogMeIPHc9N8PXjuv1xEPeHRLTcEhIqhJ8W6RoRlhRIiTVWytJpAGo1aimvaNzH5NkEPZvJJdvSD5B/Fq9LCus+Ee5AAAAAAAAAAAAAAACAAAAAAAAAQwAAABCMDA3ODg5OTgtZTExMy00ZTgzLTgzNTctNTdkMWE3Zjc2NmE4LmlwLTE3Mi0zMS0zNi0yMzktZWMyLWludGVybmFsAAAAJDAwNzg4OTk4LWUxMTMtNGU4My04MzU3LTU3ZDFhN2Y3NjZhOAAAACppYW10aGVhcHBtYW4uaXAtMTcyLTMxLTM2LTIzOS1lYzItaW50ZXJuYWwAAAAMaWFtdGhlYXBwbWFuAAAACWxvY2FsaG9zdAAAAAkxMjcuMC4wLjEAAAADOjoxAAAAKmVjMi0xOC0yMDktMTM4LTI1My5jb21wdXRlLTEuYW1hem9uYXdzLmNvbQAAAA0xNzIuMzEuOTQuMTc0AAAAAGQwRU3//////////wAAAAAAAABcAAAAFHgtdGVsZXBvcnQtYXV0aG9yaXR5AAAAIQAAAB1pcC0xNzItMzEtMzYtMjM5LWVjMi1pbnRlcm5hbAAAAA94LXRlbGVwb3J0LXJvbGUAAAAIAAAABE5vZGUAAAAAAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEA3aQcElB9GGFkE9lVYsJix8h6K6P5vo/MPCl4L582+Ppe2QpWY6bK2Z8XQ1HMtkXR18vnMY4a8Xv4PHob3fifTw1hzRFfbtWQdiihBD7y5oUZNZurBnKnELgVXxEgJYUBPWTNTF2wA2z6KoDX/w+cmUiTXp+WyDnlJiDXkWomsKCeRM+4oKee0I+Ht8qwMlyCS26Dqxlpl20h9mJalVRBhepK22wY24oOMFfqAinpD2dO61ocMj7rMiToRMe4ZboghCC18DXRtBxL2Zt1+qWVivp/vBQDiu7V1CrBRnoK85iGgPOxnMuk7E/XjXHUIv+0Pspz+UtZth63iWy6+/bbWwAAARQAAAAMcnNhLXNoYTItNTEyAAABAEGXJ1tz4JFx+8bVz09+ClaBE7TuAupvUUM7Zr5qU4GDuZNMn3rASr3m4M+0gGKXpctoYkI1niAU455pfWtXxuRAn2tLUribpNU9iR/idUv/WyPOcyNJJSdmbwp+MAEAkPw7GQ/bvtkzxF+yCJdBJakjESPdUtuV05MvK5myAVD3FlUUR4VrmcBN+TYbtEPUxYHme98qOESELezRZ+hSwb5qaQlBhaXzqQphvlfYkB2LPnzwp1nJmMmZ+0ZAiaKoqQVaqpfS2NXYIgE7APDWR/ncF0VX2QJ0dz7Tui5RMGWfOVg2KIkjZkq/lkR9i9zS+EXwjajk11xLRnW79xZkT14=\n." client/keyagent.go:367
2023-04-19T11:17:40-04:00 DEBU [KEYAGENT]  Validated host iamtheappman:0@default@ip-172-31-36-239-ec2-internal. client/keyagent.go:373
2023-04-19T11:17:40-04:00 DEBU [CLIENT]    No Key Agent selected. client/session.go:277
~~~

Bug details:
- Teleport version
~~~
$ tsh version
Teleport v12.2.1 git:api/v12.2.1-0-g6b7a47352e go1.20.3
Proxy version: 12.2.1
~~~

- Recreation steps
attempt to `rsync --rsh` with `tsh ssh --headless` functionality used

### LINKED ISSUE #24925: `tsh proxy ssh` tries to prompt for password on invalid login when stdin is not a terminal
Expected behavior:

The OpenSSH config generated by `tsh config` uses `tsh proxy ssh` as a ProxyCommand.
When I try to ssh to a node and use an invalid login, I'd expect to get some readable "Permission denied" error.

Actually, prompting for a password should not even be attempted when the current tsh credentials are still valid/not expired.
`tsh ssh` does not prompt for a password in this case.
Prompting for a password should *never* be attempted when stdin is not a terminal.

Current behavior:

`tsh proxy ssh` tries to prompt for a password, and fails because the underlying reader is not a terminal.

Bug details:
- Teleport version: v13.0.0-alpha.1 (did not test other versions)
- Recreation steps:
```
$ tsh config > ssh_config_teleport
$ ssh -F ssh_config_teleport invalid@one-node.cluster-one
Enter password for Teleport user tester:
ERROR: failed reading prompt response
underlying reader is not a terminal

kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```
- Debug logs
Proxy logs:
```
2023-04-20T11:52:18-07:00 WARN [SSH:PROXY] Error occurred in handshake for new SSH conn error:[[ssh: no auth passed yet, ssh: principal "invalid" not in the set of valid principals for given certificate: ["nklaassen" "ec2-user" "-teleport-internal-join"], ssh: principal "invalid" not in the set of valid principals for given certificate: ["nklaassen" "ec2-user" "-teleport-internal-join"], ssh: principal "invalid" not in the set of valid principals for given certificate: ["nklaassen" "ec2-user" "-teleport-internal-join"]]] remote_addr:127.0.0.1:53805 sshutils/server.go:500
```

### PR DESCRIPTION
**Pull request by Joerger**
Closes https://github.com/gravitational/teleport/issues/24810
Closes https://github.com/gravitational/teleport/issues/24925

### CODE REVIEW

**Review by probakowski — APPROVED** [review]

File: lib/client/api.go [hunk 1]
```diff
@@ -3855,15 +3859,19 @@ func (tc *TeleportClient) ShowMOTD(ctx context.Context) error {
...
+		fmt.Fprintln(tc.Config.Stderr, motd.Text)
+
+		// If possible, prompt the user for acknowledement before continuing.
+		if stdin := prompt.Stdin(); stdin.IsTerminal() {
+			// We're re-using the password reader for user acknowledgment for
+			// aesthetic purposes, because we want to hide any garbage the
+			// user might enter at the prompt. Whatever the user enters will
+			// be simply discarded, and the user can still CTRL+C out if they
+			// disagree.
+			fmt.Fprintln(tc.Stderr, "Press [ENTER] to continue.")
```
Comment (zmb3) [inline lib/client/api.go:3871]: Why do you use `tc.Config.Stderr` above and `tc.Stderr` here?

Comment (Joerger) [reply lib/client/api.go:3871]: Fixed

**Review by r0mant — APPROVED** [review]
@Joerger Is this ready to go?
