### PR TITLE
pass and preserve a path parameter during the app authentication

### LINKED ISSUE #8428: When an application user is asked to authenticate again, the browser path is not preserved for after redirection
### Description

**What happened**:
Users will send links to application pages behind Teleport to their colleagues.
If their colleagues have not authenticated recently, Teleport will ask the colleague to authenticate.
After the colleague is authenticated, they are redirected to the application main page, not to the link that the user sent to their colleague.

**What you expected to happen**:
For the link to be preserved.

In context, we have monitoring and alerting set up so that our alerts include links to monitoring dashboards that are behind a Teleport installation. When the user clicks on one of these links, we expect them to see the monitoring dashboard. If the user needs to click the link twice - once to login to the application through Teleport and once to reach the actual monitoring dashboard, then this is a source of friction that affects our Mean Time to Resolution. 

### Reproduction Steps
1. Presume Grafana is set up at `https://grafana.teleport.example.com`
2. Force a logout by going to `https://grafana.teleport.example.com/teleport-logout`
3. In a web browser, go to `https://grafana.teleport.example.com/dashboards`
4. As the user is unauthenticated, Teleport asks the user to authenticate
5. After the user is authenticated, the user is directed to `https://grafana.teleport.example.com` and not to `https://grafana.teleport.example.com/dashboards`

### Server Details
- Teleport version (run `teleport version`): 7.1.1
- Server OS (e.g. from `/etc/os-release`): Official Teleport Enterprise docker image
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): N/A
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): Firefox 92
- Installed via (e.g. apt, yum, brew, website download): N/A
- Additional details: N/A

### Debug Logs
N/A

gz#5647

### PR DESCRIPTION
**Pull request by avatus**
I left some detailed info in the [webapps PR](https://github.com/gravitational/webapps/pull/913) with some reproduction steps

This would add the requested path as a parameter to the redirect_uri during app access, which would only exist from a bookmarked or shared link since our dashboard links to root anyway.  This is where the problem arises, when a path is included in a request but the user is unauthenticated, the requested path is lost during the (many) redirects that happen during the authentication process.

Including this query parameter in the final javascript code in the redirection service will keep the path preserved. 

Also, cleaned up the state value params to not be hard coded to retrieve from a specific index and instead uses standard getters with URLSearchParams

### CODE REVIEW

**Comment by avatus** [comment]
The webassets submodule update isnt in yet because I want to get feedback on this before I merge the web one just in case this solution doesn't work out. Will push the webassets update before this is merged in

**Review by nklaassen — COMMENTED** [review]
Would it be feasible to add a test for this?

File: lib/web/app/handler.go [hunk 1]
```diff
@@ -337,7 +337,7 @@ func HasName(r *http.Request, proxyPublicAddrs []utils.NetAddr) (string, bool) {
 	u := url.URL{
 		Scheme: "https",
 		Host:   proxyPublicAddrs[0].String(),
-		Path:   fmt.Sprintf("/web/launch/%v", raddr.Host()),
+		Path:   fmt.Sprintf("/web/launch/%v?path=%v", raddr.Host(), r.URL),
```
[the remark this answers is not in the document]
Comment (avatus) [reply lib/web/app/handler.go]: Good call. I think `URL.Path` would be better suited in this case and is what I was intending to use. URL isn't always guaranteed to be just the relative path (which is was returning here rather than the full URL)

File: lib/web/app/redirect.go [hunk 2]
```diff
@@ -73,8 +77,8 @@ const js = `
           body: JSON.stringify(data),
         }).then(response => {
           if (response.ok) {
-            // redirect to the root and remove current URL from history (back button)
-            window.location.replace('/');
+            // redirect to the target path and remove current URL from history (back button)
+            window.location.replace(path || "/");
```
[the remark this answers is not in the document]
Comment (avatus) [reply lib/web/app/redirect.go]: Yeah, great call out. Oversight on my part. Replaced with a built url from origin + path, with error catching to return to path only just in case. No redirects to outside sources now

File: lib/web/app/handler.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (avatus) [reply lib/web/app/handler.go]: Any query string passed would be not preserved. We could think about passing any/all arbitrary query params through the redirect process, although I've only seen asks for the URL so far. Perhaps out of scope? (but also, solving the same problem in some cases I suppose).

**Comment by avatus** [comment]
Most of the meaningful logic is in the client side js returned so I don't really know if we can/should test that, but I did add a test to the app access logic to ensure any expected paths are added in the `path` param during the initial app request redirect

File: lib/web/app/redirect.go [hunk 3]
```diff
@@ -73,8 +77,13 @@ const js = `
           body: JSON.stringify(data),
         }).then(response => {
           if (response.ok) {
-            // redirect to the root and remove current URL from history (back button)
-            window.location.replace('/');
+            try {
+                window.location.replace(url.origin + path);
```
Comment (nklaassen) [inline lib/web/app/redirect.go:81]: I tried to test this myself locally but idk how to set up a custom webassets build and get all the redirects working.

Since anyone can share a link and modify the path parameter, we basically have to treat it as untrusted user input. Of course they could share any bad link they want, but if we're sending them to their secured teleport login page, I really want to make sure we're not going to redirect them anywhere weird.

Is there any way they could craft a path param that start with something like `.tld`? I'm imagining they share a link like `https://proxy.com/web/launch/app1.proxy.com%3Fpath=.io` so that someone would get redirected to `https://proxy.com.io` - a completely different website that could be in an attackers control

Comment (avatus) [reply lib/web/app/redirect.go]: Yeah its been a bit of a pain to get running/testing locally, I feel you there.

Very interesting to see that `.tld` vector, haven't personally seen that. Because any "real" path, including the default root path of "/" would all start with a forward slash, we can assert that any path given starts with that slash, otherwise redirect to origin only.

File: lib/web/app/redirect.go [hunk 4]
```diff
@@ -73,8 +77,16 @@ const js = `
           body: JSON.stringify(data),
         }).then(response => {
           if (response.ok) {
-            // redirect to the root and remove current URL from history (back button)
-            window.location.replace('/');
+            try {
+              if (path.charAt(0) !== "/") {
+                throw "malformed url"
+              }
+              window.location.replace(url.origin + path);
```
Comment (nklaassen) [inline lib/web/app/redirect.go:84]: I wonder about doing this instead to avoid the string concatenation and automatically handle whatever the path is
```suggestion
              redirect = new URL(path, url.origin)
              window.location.replace(url.toString());
```

Comment (avatus) [reply lib/web/app/redirect.go:84]: Great suggestion!

Comment (nklaassen) [reply lib/web/app/redirect.go:84]: I had a typo in the suggestion, should be fixed now

Comment (avatus) [reply lib/web/app/redirect.go]: Updated. Didnt even notice the typo because I slightly changed the var name anyway :)

**Review by nklaassen — APPROVED** [review]
LGTM, thanks for addressing all of my comments

**Review by Joerger — APPROVED** [review]
