### PR TITLE
Fix Assume Roles switch back, don't delete role if access list is using it.

### LINKED ISSUE #33675: Roles granted by access lists not active after switching back from assumed access request
Reproduction:

- Login as a user with some roles granted by an access list.
- Submit an access request and get it approved.
- Assume the access request roles and observe resources granted by new roles as expected.
- Unassume the access request (switch back) and observe empty resources screen.

Loom demo: https://www.loom.com/share/b27710d0f507429ead5ab8629f12d13a.

### PR DESCRIPTION
**Pull request by mdwn**
When switching back to the regular user permissions after assuming roles via an access request, Teleport will now use the user login state to ensure that access list permissions are taken into account.

Additionally, users will not be able to delete roles if they are in use by an access list. Finally, when refreshing the user while extending a web session, the user login state will be regenerated and used for permissions.

### CODE REVIEW

File: lib/auth/access_test.go [hunk 1]
```diff
@@ -68,6 +71,98 @@ func TestUpsertDeleteRoleEventsEmitted(t *testing.T) {
...
+	role, err = p.a.UpsertRole(ctx, role)
+	require.NoError(t, err)
+	user, err := types.NewUser("test-user")
+	require.NoError(t, err)
+	user.AddRole(role.GetName())
+	_, err = p.a.CreateUser(ctx, user)
+	require.NoError(t, err)
+
+	// Deletion should fail.
+	require.ErrorContains(t, p.a.DeleteRole(ctx, role.GetName()), "failed to delete a role that is still in use by a user")
```
Comment (zmb3) [inline lib/auth/access_test.go:97]: Can we wrap a sentinel error instead of using error contains? Matching on the exact string is rather brittle.

File: lib/auth/access.go [hunk 2]
```diff
@@ -126,8 +127,45 @@ func (a *Server) DeleteRole(ctx context.Context, name string) error {
...
 				// within the system.
 				log.Warnf("Failed to delete role: role %v is used by user cert authority %v", name, a.GetClusterName())
-				return trace.BadParameter("failed to delete a role that is still in use by a user, check the system server logs for more details")
+				return trace.BadParameter("failed to delete a role that is still in use by a certificate authority, check the system server logs for more details")
+			}
+		}
+	}
+
+	var nextToken string
+	for {
```
Comment (zmb3) [inline lib/auth/access.go:136]: There a _lot_ of for loops here. Do we have any performance concerns? Should we write a benchmark?

File: lib/auth/access.go [hunk 3]
```diff
@@ -111,7 +117,7 @@ func (a *Server) DeleteRole(ctx context.Context, name string) error {
 				// Mask the actual error here as it could be used to enumerate users
 				// within the system.
 				log.Warnf("Failed to delete role: role %v is used by user %v.", name, u.GetName())
-				return trace.BadParameter("failed to delete a role that is still in use by a user, check the system server logs for more details")
+				return errDeleteRoleUser
```
Comment (zmb3) [inline lib/auth/access.go:120]: I would still `trace.Wrap` it here, because otherwise you'll get a stack trace that points to the runtime's initialization (prior to `func main`).

File: lib/auth/access.go [hunk 4]
```diff
@@ -97,6 +98,12 @@ func (a *Server) UpsertRole(ctx context.Context, role types.Role) (types.Role, e
 	return upserted, nil
 }
 
+var (
+	errDeleteRoleUser       = trace.BadParameter("failed to delete a role that is still in use by a user, check the system server logs for more details")
```
Comment (zmb3) [inline lib/auth/access.go:102]: Looks better, last suggestion (up to you to accept or not) would be to use `errors.New` here.

We don't really need to embed a stack trace in these errors, since it won't point to anything interesting.

**Review by zmb3 — APPROVED** [review]

**Review by kimlisa — APPROVED** [review]

**Review by camscale — APPROVED** [review]

File: lib/auth/access.go [hunk 5]
```diff
@@ -126,8 +134,45 @@ func (a *Server) DeleteRole(ctx context.Context, name string) error {
...
+		accessLists, nextToken, err = a.Services.AccessListClient().ListAccessLists(ctx, 0 /* default page size */, nextToken)
+		if err != nil {
+			return trace.Wrap(err)
+		}
+
+		for _, accessList := range accessLists {
+			for _, r := range accessList.Spec.Grants.Roles {
+				if r == name {
+					log.Warnf("Failed to delete role: role %v is granted by access list %s", name, accessList.GetName())
+					return trace.Wrap(errDeleteRoleAccessList)
```
[the remark this answers is not in the document]
Comment (mdwn) [reply lib/auth/access.go:155]: I'm not opposed to that, but every user, CA, and access list more or less has the same issue today. I'd rather punt to solve this more thoroughly for all of these if that's alright.

File: lib/auth/access.go [hunk 6]
```diff
@@ -97,6 +99,12 @@ func (a *Server) UpsertRole(ctx context.Context, role types.Role) (types.Role, e
 	return upserted, nil
 }
 
+var (
+	errDeleteRoleUser       = errors.New("failed to delete a role that is still in use by a user, check the system server logs for more details")
```
[the remark this answers is not in the document]
Comment (mdwn) [reply lib/auth/access.go:103]: At the moment these are only needed for the tests. I think we can export these if we need to dlater.

**Comment by zmb3** [comment]
@mdwn does this fix #33675? I don't see the original issue linked.

**Comment by mdwn** [comment]
> @mdwn does this fix #33675? I don't see the original issue linked.

Ahhh, I didn't realize this issue existed. Yes it does.
