### PR TITLE
Fix Jamf plugin duration serialization

### LINKED ISSUE #57747: Bugged time duration serialization in Jamf plugin breaks access to all plugins through Web UI and tctl
Expected behavior:

`tctl edit plugin/jamf` should let you update the Jamf plugin settings, specifically the `page_size` (see #54635).

Current behavior:

Updating the Jamf plugin with the settings below completely breaks access to plugins through the Web UI and tctl. For example, it's no longer possible to do `tctl edit plugin/<any plugin>`, `tctl show plugin/<any plugin>` or access `/web/integrations` in the Web UI.

See [the Slack thread](https://gravitational.slack.com/archives/C01UV6NKQTS/p1754040204348109) for extra details.

```yaml
spec:
  Settings:
    jamf:
      jamf_spec:
        api_endpoint: https://teleporttest.jamfcloud.com
        inventory:
        - sync_period_partial: 6h
          sync_period_full: 24h
          on_missing: DELETE
          filter_rsql: 'general.remoteManagement.managed==true'
          page_size: 50
```

Bug details:
- Teleport version: all versions

### PR DESCRIPTION
**Pull request by ravicious**
* Closes https://github.com/gravitational/teleport/issues/57747.
* These two PRs need to be merged first. They ensure that this PR can be merged without breaking the build.
  * https://github.com/gravitational/teleport/pull/65940 
  * https://github.com/gravitational/teleport.e/pull/8557

gogoproto's jsonpb has a bug with int64 casttype fields that have custom `MarshalJSON`: marshal produces a quoted duration string like `"6h0m0s"`, but unmarshal [strips the quotes](https://github.com/gravitational/protobuf/blob/ece7d23c3faf56d7e28460c2cc12814c13f50bdb/jsonpb/jsonpb.go#L1221-L1223) (because the target kind is int64) and then calls `json.Unmarshal` on the bare value, which fails because `6h0m0s` isn't valid JSON.

This breaks the Jamf plugin when the user calls `tctl edit plugin/jamf` and sets a non-zero `sync_delay`, `sync_period_partial` or `sync_period_full`. And since `UnmarshalPlugin` lists all plugins, a broken Jamf plugin makes all plugins inaccessible.

The fix is to add `DurationStringForJamfSpecV1`, a new casttype used only by the three affected Jamf fields. It implements `jsonpb.JSONPBUnmarshaler`, which [gogo's jsonpb checks before the int64 quote-stripping path](https://github.com/gravitational/protobuf/blob/ece7d23c3faf56d7e28460c2cc12814c13f50bdb/jsonpb/jsonpb.go#L825-L827), and keeps `MarshalJSON`/`UnmarshalJSON` delegating to `Duration` so the human-readable string format is preserved in `tctl edit`.

Changelog: Fixed an issue where `tctl edit plugin/jamf` could break other plugins when providing non-zero duration value

### Test Environment

A local ent cluster with teleport.e set to `maja/jamf-duration/1-alias`. The Jamf plugin needs to have `selfHostable` flipped to `true` in `e/web/teleport/src/Integrations/IntegrationEnroll/PluginEnroll/plugins.tsx` in order to enable it through the Web UI.

### Test Cases
- [x] Running `tctl edit plugin/jamf` and setting `spec.Settings.jamf.jamf_spec.sync_delay` to `-1s` does not break subsequent edit commands like it used to and it causes the Jamf plugin to immediately sync devices on plugin start.
- [x] Re-running `tctl edit plugin/jamf` shows `-1s` as `sync_delay`. Changing it to `2s` doesn't break the plugin system.
- [x] Removing `sync_delay` from the spec brings the plugin back to the default behavior of starting after a random delay of up to 2 minutes.
- [x] Running `tctl edit plugin/jamf` on a broken version from master and then restarting the cluster with the patch applied unblocks `tctl edit plugin/jamf` while preserving the value set by the initial edit.

### CODE REVIEW

File: api/types/jamf_duration.go [hunk 1]
```diff
@@ -14,13 +14,55 @@
...
+// Implementing JSONPBUnmarshaler bypasses the broken path because gogo's
+// jsonpb checks that interface before the int64 quote-stripping.
 //
 // See https://github.com/gravitational/teleport/issues/57747.
-type DurationStringForJamfSpecV1 = Duration
+type DurationStringForJamfSpecV1 time.Duration
+
+// MarshalJSON delegates to [Duration.MarshalJSON]. Called by encoding/json,
+// which is used by both gogo's jsonpb marshal (via json.Marshal) and
+// ghodss/yaml in tctl edit.
```
Comment (espadolini) [inline api/types/jamf_duration.go:52]: Aren't we using jsonpb to support oneofs? How are we doing yaml without going through jsonpb in tctl edit? If `services.MarshalPlugin`/`services.UnmarshalPlugin` is intended for both storage and user consumption, I'd rather see them used consistently.

Comment (ravicious) [reply api/types/jamf_duration.go:52]: > Aren't we using jsonpb to support oneofs? How are we doing yaml without going through jsonpb in tctl edit?

[The backend calls `services.UnmarshalPlugin`](https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/lib/services/local/plugins.go#L128-L129) and [returns `PluginV1` to tctl](https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/tool/tctl/common/resource_command.go#L1124-L1130). tctl then [writes the plugin to a file using `lib/utils.WriteYAML`](https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/tool/tctl/common/resource_command.go#L266-L272) which [uses `ghodss/yaml` underneath](https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/lib/utils/jsontools.go#L229-L231). `ghodss/yaml` marshals the plugin into JSON (using `encoding/json`) and then converts the JSON to YAML.

The user edits the resource and [tctl unmarshals YAML from the file](https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/tool/tctl/common/edit_command.go#L189) using `k8s.io/apimachinery/pkg/util/yaml`. [`ResourceCommand.updatePlugin` unmarshals it again](https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/tool/tctl/common/resource_command.go#L1235-L1244) into `pluginResourceWrapper` which implements `UnmarshalJSON` using `encoding/json` and handles top level oneofs for plugins:

https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/tool/tctl/common/collection.go#L504-L514

The unmarshalled plugin is sent to the backend which [calls `services.MarshalPlugin`](https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/lib/services/local/plugins.go#L80-L88).

Comment (espadolini) [reply api/types/jamf_duration.go:52]: > [writes the plugin to a file using lib/utils.WriteYAML](https://github.com/gravitational/teleport/blob/248c5f6b789753e29629bb251d5411b5f42e2e2d/tool/tctl/common/resource_command.go#L266-L272)

Ok well that's wrong then, surely? If types.PluginV1 (which is embedded by value in `pluginResourceWrapper` even though protobuf messages should not be copied) needs special handling for marshaling and unmarshaling then we can't be passing a types.PluginV1 to encoding/json without defining MarshalJSON or using a wrapper.

In other words, if the resource needs special handling for json then the resource should define MarshalJSON and UnmarshalJSON, not individual fields nested three levels deep.

Comment (ravicious) [reply api/types/jamf_duration.go:52]: I don't disagree, but I have the bandwidth to address the issue with the Jamf plugin, not to refactor how `tctl edit` behaves when editing plugins in general. I can create a separate issue to track this.

File: api/types/jamf_duration.go [hunk 2]
```diff
@@ -14,13 +14,55 @@
...
+
+// UnmarshalJSON delegates to [Duration.UnmarshalJSON]. Called by encoding/json
+// (e.g. when ghodss/yaml is used by tctl edit).
+func (d *DurationStringForJamfSpecV1) UnmarshalJSON(data []byte) error {
+	return (*Duration)(d).UnmarshalJSON(data)
+}
+
+// UnmarshalJSONPB intercepts gogo's jsonpb unmarshal before it strips quotes
+// from the string value of int64 fields, delegating to [Duration.UnmarshalJSON]
+// which correctly parses the properly quoted JSON string.
```
Comment (espadolini) [inline api/types/jamf_duration.go]:
```suggestion
// UnmarshalJSONPB intercepts gogo's jsonpb unmarshal before it strips quotes
// from the string value of int64 fields, delegating to [Duration.UnmarshalJSON]
// which correctly parses the properly quoted JSON string. We only need this
// special handling during the unmarshaling, because marshaling will consistently
// use [json.Marshaler.MarshalJSON] if available.
```

File: api/types/jamf_duration.go [hunk 3]
```diff
@@ -14,13 +14,55 @@
...
+func (d *DurationStringForJamfSpecV1) UnmarshalJSONPB(_ *jsonpb.Unmarshaler, data []byte) error {
+	return (*Duration)(d).UnmarshalJSON(data)
```
Comment (espadolini) [inline api/types/jamf_duration.go]: nit

```suggestion
	return d.UnmarshalJSON(data)
```

**Review by espadolini — APPROVED** [review]

**Review by codingllama — APPROVED** [review]
Thanks for the fix and the careful work.

> Running tctl edit plugin/jamf on a broken version from master and then restarting the cluster with the patch applied unblocks tctl edit plugin/jamf while preserving the value set by the initial edit.

Perfect. +100.
