### PR TITLE
fix: show updated profile info after assuming an access request

### LINKED ISSUE #57472: `tsh login --request-id` omits assumed role in output
### Expected Behavior
When using `tsh login --request-id` to assume a role, the new role should immediately be displayed in the roles list of the confirmation output.

```
% tsh request create --roles requested
...
% tsh login --request-id=c975647d-b34f-4b49-4107-7bc4100af81c

Approval received, reason="approved"
Getting updated certificates...

> Profile URL:        https://teleport.example.com:443
  Logged in as:       someuser
  Cluster:            teleport.example.com
  Roles:              access, requested
  Logins:             someuser, ubuntu
  Valid until:        2025-08-02 18:48:25 -0400 EDT [valid for 10h9m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy, teleport-device-asset-tag, teleport-device-credential-id, teleport-device-id
```

### Current Behavior
The `tsh login --request-id` command confirms the assumption of a new role and updates certificates but does not immediately display the newly assumed role in the roles list.

Manually running The command `tsh status` after the initial incorrect output will reflect the role assumption.

```
% tsh request create --roles requested
...
% tsh login --request-id=c975647d-b34f-4b49-4107-7bc4100af81c

Approval received, reason="approved"
Getting updated certificates...

> Profile URL:        https://teleport.example.com:443
  Logged in as:       someuser
  Cluster:            teleport.example.com
  Roles:              access
  Logins:             someuser, ubuntu
  Valid until:        2025-08-02 18:48:25 -0400 EDT [valid for 10h9m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy, teleport-device-asset-tag, teleport-device-credential-id, teleport-device-id
```

#### Teleport Version
Observed on tsh versions 16.5.12, 17.5.4, and 17.5.6.

#### Recreation Steps
1. Execute `tsh logout`.
2. Log in using `tsh login --proxy=proxy.example.com:443`.
3. Request and assume a role using `tsh login --request-id=<request-id>`.
4. Observe that the role list does not include the newly assumed role.
5. Execute `tsh status`.
6. Observe that the correct roles, including the assumed role, are displayed.

#### Debug Logs

N/A

### PR DESCRIPTION
**Pull request by nklaassen**
Fixes #57472

`tsh login --request-id=<id>` was showing stale profile info from before assuming the access request that did not include the assumed access request or any new roles or allowed resource IDs. The fix reloads the profile status after assuming the access request.

### Test Environment

A teleport cluster with an enterprise license and the preset `requester` and `access` roles.

A user with only the `requester` role, logged in with `tsh`.

An approved access request created in the web UI or with tsh for any resource.

### Test Cases

- [x] `tsh login --request-id=<approved-request-id>` includes the assumed access request ID and role
```
$ tsh login --request-id 019cba1c-eaac-73c0-8832-edaacf555654

Approval received, getting updated certificates...

> Profile URL:        https://one.private:3080
  Logged in as:       nic
  Active requests:    019cba1c-eaac-73c0-8832-edaacf555654
  Cluster:            one.private
  Roles:              access, requester
  Logins:             root, nic
  Kubernetes:         enabled
  Allowed Resources:  ["/one.private/node/6df42bc6-6389-4092-a35f-164a433bbbda"]
  Valid until:        2026-03-04 22:13:46 -0800 PST [valid for 11h23m]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy, teleport-allowed-resource-access-ids
```

changelog: fixed `tsh login --request-id` to display up to date profile information including the assumed access request and roles

### CODE REVIEW

File: tool/tsh/common/tsh_test.go [hunk 1]
```diff
@@ -627,6 +627,94 @@ func TestOIDCLogin(t *testing.T) {
 	// request to be generated.
 }
 
+// TestLoginRequestIDPrintsUpdatedProfile asserts that tsh login --request-id
+// prints profile information that is up to date with the newly assumed access
+// request.
+func TestLoginRequestIDPrintsUpdatedProfile(t *testing.T) {
+	// Access requests require enterprise.
+	modulestest.SetTestModules(t, modulestest.Modules{TestBuildType: modules.BuildEnterprise})
```
Comment (zmb3) [inline tool/tsh/common/tsh_test.go]: Even with tsh?

**Review by zmb3 — APPROVED** [review]

File: tool/tsh/common/tsh_test.go (hunk 1 above)
Comment (nklaassen) [reply tool/tsh/common/tsh_test.go]: ah no you're right 😅 removed the modules and made the test parallel

**Review by atburke — APPROVED** [review]
