### PR TITLE
Fix launching AWS IC from Connect

### LINKED ISSUE #62288: Malformed URL when accessing AWS integration accounts from Connect
How to reproduce:
- open Teleport Connect and log in on `platform.teleport.sh`
- search the `teleport-dev` AWS account (note the duplicated scheme in the URL already)

Image

- press enter/pick the first match
- web browser opens and fails to load the console, because of the malformed URL

Image

Version: Version 18.2.1 (18.2.1.1688)

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/62288

changelog: Fixed launching AWS Identity Center from Teleport Connect

Fixes launching AWS IC from Connect by copying the logic from the Web UI, as described in https://github.com/gravitational/teleport/issues/62288#issuecomment-3728151262

### CODE REVIEW

File: web/packages/teleterm/src/mainProcess/navigationHandler.ts [hunk 1]
```diff
@@ -90,6 +90,10 @@ function isUrlSafe(
   if (url.host === 'github.com' && url.pathname.startsWith('/gravitational/')) {
     return true;
   }
+  // AWS IAM IC apps.
+  if (url.host.endsWith('.awsapps.com')) {
```
Comment (ravicious) [inline web/packages/teleterm/src/mainProcess/navigationHandler.ts]: I don't think this is safe, technically anyone can set up an app under this domain and it doesn't have to be an IAM IC app.

@flyinghermit Do you know if there's any way in which we could allowlist AWS IC apps? I suppose it's not like they all have the same subdomain pattern?

Comment (gzdunek) [reply web/packages/teleterm/src/mainProcess/navigationHandler.ts]: >By default, you can access the AWS access portal by using a URL that follows this format: d-xxxxxxxxxx.awsapps.com/start. You can customize the URL as follows: your_subdomain.awsapps.com/start.

https://docs.aws.amazon.com/singlesignon/latest/userguide/howtochangeURL.html 

It doesn't seem possible to build a more precise allowlist with the limited information available in the main process. The only option seems to be fetching the resources in that process and verifying whether there's an app with such public address, similarly to `makeRootClusterProxyHostAllowList`.

Comment (ravicious) [reply web/packages/teleterm/src/mainProcess/navigationHandler.ts]: Yeah, that just doesn't seem feasible because apps can change way more often than the list of clusters.

It looks like we'll have no choice but to allow `.awsapps.com` and maybe verify that the path is `/start` or starts with `/start/`. I just worry that it'll set a precedent and in the future it'll be way easier for us to add more exceptions like that.

Looking at [`webContents.setWindowOpenHandler`](https://www.electronjs.org/docs/latest/api/web-contents#contentssetwindowopenhandlerhandler), it doesn't seem like there's a way for us to enrich the window opening in a way which would prevent the attacker from opening windows to arbitrary apps.

We could pass custom data through `frameName`, but it'd require the main process and the renderer to share a secret that the attacker cannot access in the case of an XSS and that just doesn't seem to be possible, as we have to assume that in case of an XSS the attacker can access everything that the renderer can access.

One very elaborate solution would be to HMAC the URLs and share the key between the main process and tshd. tshd would return HMAC'd URLs and the main process would be able to verify their validity. The problem is that tshd would need to pre-hash all possible URLs. 🫩 Well, unless we hashed only the non-dynamic part of the URL, e.g. everything but `&role_name=<foo>`.

Comment (ravicious) [reply web/packages/teleterm/src/mainProcess/navigationHandler.ts]: Maybe hashing just the host would work and it'd be a way for the tshd to signal "This is a domain that can be trusted" – this would be universal and could work with more than just AWS IC. I think I'll draft an issue for this and leave it at that for now + add checking for the path.

Edit: Here's the issue. https://github.com/gravitational/teleport/issues/62808

**Review by ravicious — APPROVED** [review]

File: web/packages/teleterm/src/mainProcess/navigationHandler.ts [hunk 2]
```diff
@@ -90,6 +90,19 @@ function isUrlSafe(
...
+  // This of course allows an attacker to create an app on awsapps.com and open it from Connect.
+  // TODO(ravicious): Allow tsh to bless arbitrary hosts for opening in the browser.
+  // https://github.com/gravitational/teleport/issues/62808
+  if (
+    url.host.endsWith('.awsapps.com') &&
+    url.host.split('.').length === 3 &&
+    url.pathname === '/start/'
+  ) {
+    return true;
+  }
```
Comment (flyinghermit) [inline web/packages/teleterm/src/mainProcess/navigationHandler.ts]: This will not work for the AWS GovCloud URL as it has different format.

**Reference:**

- Commercial cloud URL: `https://<idstore_id>.awsapps.com/start/#/console?account_id=<account_id>`. Works for this format.
- GovCloud URL: `https://start.us-gov-home.awsapps.com/directory/<idstore_id>#/console?account_id=<account_id>`. Does not work for this format
- Backend code where URL format is defined: https://github.com/gravitational/teleport.e/blob/master/lib/aws/identitycenter/accounts.go#L94C3-L100C3

File: web/packages/teleterm/src/mainProcess/navigationHandler.ts (hunk 1 above)
Comment (flyinghermit) [reply web/packages/teleterm/src/mainProcess/navigationHandler.ts]: Good to know we have an allowlist for supported domains here 👍.

Coming back to the topic: What is the threat modal here? Is the allow list "catch all" for all outgoing URLs or do we have control over the context, e.g., is URL coming from the backend (`tsdhd`) or is user supplied etc?

Comment (ravicious) [reply web/packages/teleterm/src/mainProcess/navigationHandler.ts]: This is a list of allowed URLs the user is able to open by clicking on a link in the UI (or executing JS that calls `window.open`). If an attacker every gets to execute code from within the renderer context (XSS or some Electron/Chromium vuln), we don't want them to be able to open arbitrary URLs to minimize damage that can be done.

File: web/packages/teleterm/src/mainProcess/navigationHandler.ts (hunk 2 above)
Comment (ravicious) [reply web/packages/teleterm/src/mainProcess/navigationHandler.ts]: Thanks, added.

File: web/packages/teleterm/src/mainProcess/navigationHandler.ts (hunk 1 above)
Comment (gzdunek) [reply web/packages/teleterm/src/mainProcess/navigationHandler.ts]: I like the idea of hashing the host.
But I agree that for now we can keep the simpler `.awsapps.com` check.

File: proto/teleport/lib/teleterm/v1/app.proto [hunk 3]
```diff
@@ -131,3 +136,13 @@ message RouteToApp {
   // target_port is the port of a multi-port TCP app that the connection is going to be proxied to.
   uint32 target_port = 5;
 }
+
+// Defines a permission set that is available on an IdentityCenter account app.
```
Comment (flyinghermit) [inline proto/teleport/lib/teleterm/v1/app.proto:140]: Add comment that these proto messages and field structure should be in sync with the teleport core `IdentityCenterPermissionSet` types?

File: proto/teleport/lib/teleterm/v1/app.proto [hunk 4]
```diff
@@ -131,3 +136,13 @@ message RouteToApp {
...
+message IdentityCenterPermissionSet {
+  // Human-readable name of the permission set.
+  string name = 1;
+  // AWS-assigned ARN of the permission set.
+  string arn = 2;
+  // Assignment resource ID that will provision an Account assignment for this permission set on the enclosing account.
+  string assignment_id = 3;
```
Comment (flyinghermit) [inline proto/teleport/lib/teleterm/v1/app.proto:148]: I guess we do not need to JSON/YAML marshall in Connect and this is fine but otherwise I noticed that the proto message defined for the core type has the `assignment_id` as field name and `assignment_name` as JSON name https://github.com/gravitational/teleport/blob/917b1b82e790f8814013b3eda96a6cda4c75886a/api/proto/teleport/legacy/types/types.proto#L1103

File: web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToApp.test.ts [hunk 5]
```diff
@@ -78,14 +79,34 @@ describe('connectToApp', () => {
...
+
+      await connectToApp(
+        appContext,
+        launchVnet,
+        app,
+        { origin: 'resource_table' },
+        { arnForAwsAppOrRoleForAwsIc: 'foo-role' }
+      );
+      expect(window.open).toHaveBeenCalledWith(
+        'local-app.example.com&role_name=foo-role',
```
Comment (flyinghermit) [inline web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToApp.test.ts]: nit: use proper formatted `awsapps.com` URL here for demonstration?

**Review by flyinghermit — APPROVED** [review]
Thank you!

File: proto/teleport/lib/teleterm/v1/app.proto (hunk 3 above)
Comment (gzdunek) [reply proto/teleport/lib/teleterm/v1/app.proto:140]: I'm not sure if that's needed, many of Connect's types mirror the ones from teleport and we don't add such comments there.

File: proto/teleport/lib/teleterm/v1/app.proto (hunk 4 above)
Comment (gzdunek) [reply proto/teleport/lib/teleterm/v1/app.proto:148]: Hmm the JS code expects `assignmentId` and I see it being returned from the API.
https://github.com/gravitational/teleport/blob/93066da9fc8d86b7095585a00634386189f0cf98/web/packages/teleport/src/services/apps/types.ts#L125

EDIT: it comes from a different struct
https://github.com/gravitational/teleport/blob/917b1b82e790f8814013b3eda96a6cda4c75886a/lib/web/ui/app.go#L101-L109

File: web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToApp.test.ts (hunk 5 above)
Comment (gzdunek) [reply web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToApp.test.ts]: Thanks, done.

**Comment by gzdunek** [comment]
I wanted to back port it to v17, but there are many conflicts, so I think I'll discard it.

**Comment by ravicious** [comment]
I managed to solve them, I'll push a PR soon.

**Comment by ravicious** [comment]
I didn't doubt you @gzdunek, I just wanted to see what the conflicts are. 😅 And when I saw them I thought that they might not be that hard to address after all. And since AWS IC support launched in v17, I thought it might be worthwhile to backport the fix.

**Comment by gzdunek** [comment]
No problem, thanks for backporting it!

File: proto/teleport/lib/teleterm/v1/app.proto (hunk 4 above)
Comment (flyinghermit) [reply proto/teleport/lib/teleterm/v1/app.proto:148]: Gotcha. Thanks for checking that.

File: proto/teleport/lib/teleterm/v1/app.proto (hunk 3 above)
Comment (flyinghermit) [reply proto/teleport/lib/teleterm/v1/app.proto:140]: Understood. Its for situation like this one when comments https://github.com/gravitational/teleport/pull/62796#discussion_r2690707826 can be useful, especially for people like me who may not be well verse on Connect internals.
