### PR TITLE
Reject "Bot" role in auth server static token config

### LINKED ISSUE #45208: Disallow the configuration of Bot tokens using the Static Token config
Today, you can create a "Bot" role token using the static tokens config. This token will not work because it does not specify a specific bot. Static tokens also do not work with other elements of the bot join process.

E.G
```
auth_service:
  enabled: yes
  tokens:
    - "bot:mybottoken"
```

We should throw an explicit error rather than silently allowing this misconfiguration.

### PR DESCRIPTION
**Pull request by strideynet**
Closes https://github.com/gravitational/teleport/issues/45208

Rejects configuration of a "Bot" role static token in the auth server file config - this never actually worked but could produce confusing errors rather than a clear one. Since this is technically a breaking change, we'll have to leave this for v18.

Backport to v18 will switch the error for a logged warning.

changelog: Breaking - Teleport will now reject the configuration of a Bot role static token within the Auth Service file configuration (e.g. within `auth_service.tokens`)

### CODE REVIEW

File: lib/config/fileconf.go [hunk 1]
```diff
@@ -992,6 +992,9 @@ func (t StaticToken) Parse() ([]types.ProvisionTokenV1, error) {
 	if err != nil {
 		return nil, trace.Wrap(err)
 	}
+	if roles.Include(types.RoleBot) {
+		return nil, trace.BadParameter("role %q is not allowed in static token configuration", types.RoleBot)
+	}
```
Comment (marcoandredinis) [inline lib/config/fileconf.go:997]: Should we add a warning in v18 and do a breaking change for v19?
Or add a warning for the next v17 and v16 releases

**Review by marcoandredinis — APPROVED** [review]

File: lib/config/fileconf.go (hunk 1 above)
Comment (strideynet) [reply lib/config/fileconf.go:997]: That seems reasonable - I can do a backport and switch the error out for a warning.

Comment (espadolini) [reply lib/config/fileconf.go:997]: What does `Bot` in a static token even do?

Comment (zmb3) [reply lib/config/fileconf.go:997]: If it never actually worked and all this change does is cause the user to see a better error message then we should ship it in v18.

Comment (espadolini) [reply lib/config/fileconf.go:997]: I think that's the plan, my question was more about potentially backporting the error, but if Teleport currently starts (albeit with a broken join token) then we shouldn't break that.

**Review by espadolini — APPROVED** [review]

File: lib/config/fileconf.go (hunk 1 above)
Comment (strideynet) [reply lib/config/fileconf.go:997]: So configuring this does actually allow Teleport to start, however, when you try to join the Bot, it produces `ERROR: unsupported join method "" for bot`.

 If we want to take a more conservative route of emitting a warning in v18 and then making this a breaking change in 19 - that's fine by me. I'm a little concerned that a warning log in the early stages of a Teleport startup is unlikely to be spotted though.
