### PR TITLE
fix audit log file leak, fixes #1433

### LINKED ISSUE #1433: Teleport leak file descriptors
I'm using `teleport` for a particular use case, channeling `ansible` playbooks through it for hundred of machines at a time. During playbooks, the bastion's `teleport` process just piles up file descriptor in a linear manner and frequently reach the maximum allowed by the `systemd` unit file, crashing all sessions and becoming unresponsive until I restart the daemon.

I've first considered to increase the limit above the `systemd` default of 1024, but I'm now at 16386 and started to suspect `teleport` handling itself. I recognise that my usage is a bit... unconventional as `Ansible` output is logged by `teleport` itself.

Has anyone encountered this issue before ? I intend to do a bit of research on this topic in the coming months but I would appreciate insights from any seasoned `teleport` developers.

### PR DESCRIPTION
**Pull request by klizhentas**
This is a fix for file leak in audit log server caused
by design issue:

Session file descriptors in audit log were opened on demand
when the session event or byte stream chunk  was reported.

AuditLog server relied on SessionEnd event to close the
file descriptors associated with the session.

However, when SessionEnd event does not arrive (e.g.
there is a timeout or disconnect), the file descriptors
were not closed. This commit adds periodic clean up
of inactive sessions.

SessionEnd is now used as an optimization measure
to close the files, but is not used as the only
trigger to close files.

Now, inactive idle sessions, will close file descriptors
after periods of inactivity and will reopen the file
descriptors when the session activity resumes.

SessionLogger was not designed to open/close files
multiple times as it was reseting offsets
every time the session files were opened. This
change fixes this condition as well.

### CODE REVIEW

**Comment by klizhentas** [comment]
I will run a bit more manual tests tomorrow, so won't merge yet.

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

**Comment by klizhentas** [comment]
retest this please

File: lib/events/sessionlog.go [hunk 1]
```diff
@@ -49,10 +52,58 @@ type SessionLogger interface {
...
+}
+
+// NewDiskSessionLogger creates new disk based session logger
+func NewDiskSessionLogger(cfg DiskSessionLoggerConfig) (*DiskSessionLogger, error) {
+	writtenBytes, err := ReadWrittenBytes(cfg.EventsFileName)
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+	// create a new session stream file:
+	fstream, err := os.OpenFile(cfg.StreamFileName, os.O_WRONLY|os.O_CREATE|os.O_APPEND, 0640)
```
Comment (r0mant) [inline lib/events/sessionlog.go]: Is there a constant for `0640`? Below too.

File: lib/events/auditlog.go [hunk 2]
```diff
@@ -86,43 +90,83 @@ type AuditLog struct {
...
-		recordSessions: recordSessions,
+		AuditLogConfig: cfg,
+		Entry: log.WithFields(log.Fields{
+			trace.Component: teleport.ComponentAuditLog,
+		}),
+	}
+	loggers, err := ttlmap.New(defaults.AuditLogSessions,
+		ttlmap.CallOnExpire(al.asyncCloseSessionLogger), ttlmap.Clock(cfg.Clock))
+	if err != nil {
+		return nil, err
```
Comment (r0mant) [inline lib/events/auditlog.go]: trace.Wrap(err)

File: lib/srv/sess.go [hunk 3]
```diff
@@ -525,7 +534,24 @@ func (r *sessionRecorder) Write(data []byte) (int, error) {
...
+	// to do so before we send SessionEndEvent to advise the audit log
+	// to release resources associated with this session.
+	// not doing so will not result in memory leak, but could result
+	// in missing playback events
+	context, cancel := context.WithTimeout(context.TODO(), defaults.DefaultReadHeadersTimeout)
+	defer cancel() // releases resources if slowOperation completes before timeout elapses
+	err = r.alog.Wait(context)
+	if err != nil {
+		errors = append(errors, err)
+		log.Warningf("timeout waiting for session to flush events: %v", err)
```
Comment (r0mant) [inline lib/srv/sess.go]: trace.DebugReport(err)

File: lib/events/sessionlog.go (hunk 1 above)
Comment (klizhentas) [reply lib/events/sessionlog.go]: I will handle this in the next PR in the module

**Comment by klizhentas** [comment]
heads, up, I've spotted a couple of problems, fixing

File: lib/events/sessionlog.go [hunk 4]
```diff
@@ -49,10 +52,58 @@ type SessionLogger interface {
...
+		createdTime:  cfg.Clock.Now().In(time.UTC).Round(time.Second),
+	}
+	return sessionLogger, nil
+}
+
+// DiskSessionLogger implements a disk based session logger. The imporant
 // property of the disk based logger is that it never fails and can be used as
 // a fallback implementation behind more sophisticated loggers.
-type diskSessionLogger struct {
+type DiskSessionLogger struct {
```
Comment (russjones) [inline lib/events/sessionlog.go]: Why is this exported now?

File: lib/events/api.go [hunk 5]
```diff
@@ -145,6 +147,10 @@ type IAuditLog interface {
 	// SearchSessionEvents returns session related events only. This is used to
 	// find completed session.
 	SearchSessionEvents(fromUTC time.Time, toUTC time.Time) ([]EventFields, error)
+
+	// Wait waits for resources to be released and outstanding requests to
+	// complete after calling Close method
+	Wait(context.Context) error
```
Comment (russjones) [inline lib/events/api.go]: If `IAuditLog` was not embedded everywhere, `Wait` would be a reasonable name. Unfortunately `IAuditLog` is embedded everywhere, for example `auth.Client` and `auth.AuthWithRoles` where `Wait` is confusing.

It should be named something more specific.

File: lib/auth/auth_with_roles.go [hunk 6]
```diff
@@ -999,6 +1000,10 @@ func (a *AuthWithRoles) Close() error {
 	return a.authServer.Close()
 }
 
+func (a *AuthWithRoles) Wait(context.Context) error {
+	return nil
```
Comment (russjones) [inline lib/auth/auth_with_roles.go]: Might want to return an error here so the caller knows this is not something they can use.

```
return trace.BadParameter("not implemented")
```

**Comment by klizhentas** [comment]
@russjones addressed code review comments and fixed some outstanding problems

**Comment by klizhentas** [comment]
retest this please

File: lib/events/sessionlog.go (hunk 4 above)
Comment (klizhentas) [reply lib/events/sessionlog.go]: I thought it might be useful as a standalone tool (used in my local tests)

**Comment by klizhentas** [comment]
retest this please

**Review by russjones — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please
