### PR TITLE
Provides output for windows_desktop and kube tctl tokens add

### LINKED ISSUE #5679: Missing kube role for teleport start --roles
### Description

**What happened**:
No `kube` role is available for usage in `teleport start --roles=kube`.  `kube` is also not listed in the roles list in help.

If you do a `tctl tokens add --type=kube` you will receive this output

```bash
The invite token: c0179182079448c321aa8c2247
This token will expire in 60 minutes

Run this on the new node to join the cluster:

> teleport start \
   --roles=kube \
   --token=c013bc182079448c321aa8c2247 \
   --ca-pin=sha256:248203996f424cd60dd7014994fb736cf07ddf5e590f900de75b8d11a \
   --auth-server=authip:3025

Please note:

  - This invitation token will expire in 60 minutes
  - authip:3025 must be reachable from the new node
```

If you try to run with `--roles=kube` you get an error.

Also, both `kube` and `db/database` are missing from the list of roles in the help output:

```
$ teleport start --help
usage: teleport start [<flags>]

Starts the Teleport service.

Flags:
  -d, --debug            Enable verbose logging to stderr
      --insecure-no-tls  Disable TLS for the web socket
  -r, --roles            Comma-separated list of roles to start with [proxy,node,auth,app]
...
```

**What you expected to happen**:

As with node, proxy,.. you can run with only the kubernetes service enabled with a role designation.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.on the auth server add a `kube` token
2. attempt to start teleport with `teleport start --roles=kube`

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v5.2.0 git:v5.2.0-0-gccf3f4694 go1.15.5
- Server OS (e.g. from `/etc/os-release`): 
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Which platform(s)
- [X] Teleport Open Source
- [X] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [ ] Server Access
- [x] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [ ] Other

### PR DESCRIPTION
**Pull request by stevenGravy**
Add output for tokens type `kube` and `windows_desktop`.   Otherwise these output incorrect `teleport start` examples.  Did not give an advanced example for desktop as this will likely have multiple options in the coming release.

# Kube 
```bash
$ tctl tokens add --type=kube
The invite token: 124ffa40c84cc7ea0d855b9fe892176e
This token will expire in 60 minutes.

To use with Helm installation follow these steps:

# Retrieve the Teleport helm charts
helm repo add teleport https://charts.releases.teleport.dev
# Refresh the helm charts
helm repo update

> helm install teleport-agent teleport/teleport-kube-agent \
  --set kubeClusterName=cluster `# Change kubeClusterName variable to your preferred name.` \
  --set proxyAddr=teleport.example.com:443 \
  --set authToken=124ffa40c84cc7ea0d855b9fe892176e \
  --create-namespace \
  --namespace=teleport-agent
        
Please note:
        
  - This invitation token will expire in 60 minutes.
  - enterprise.teleportdemo.com:443 must be reachable from Kubernetes cluster.
  - The token is usable in a standalone Linux server with kubernetes_service.
  - See goteleport.com/docs/kubernetes-access/ for detailed installation information.
 ```

# Desktop
```bash
$ tctl tokens add --type=windows_desktop
The invite token: 4b9a405867bc42087b5394204a4ebc69
This token will expire in 60 minutes.

This token enables Desktop Access.  See https://goteleport.com/docs/desktop-access/
for detailed information on configuring Teleport Desktop Access with this token.
```

### CODE REVIEW

File: tool/tctl/common/kube_command.go [hunk 1]
```diff
@@ -83,3 +84,29 @@ func (c *KubeCommand) ListKube(ctx context.Context, client auth.ClientI) error {
...
+  --set authToken={{.token}} \
+  --create-namespace \
+  --namespace=teleport-agent
+        
+Please note:
+        
+  - This invitation token will expire in {{.minutes}} minutes.
+  - {{.auth_server}} must be reachable from Kubernetes cluster.
+  - The token is usable in a standalone Linux server with kubernetes_service.
+  - See goteleport.com/docs/kubernetes-access/ for detailed installation information.
```
Comment (zmb3) [inline tool/tctl/common/kube_command.go:110]: In the desktop template the docs link includes https:// but that's missing here.

Comment (stevenGravy) [reply tool/tctl/common/kube_command.go]: thanks for reviewing @zmb3 this part, fixed.

File: tool/tctl/common/token_command.go [hunk 2]
```diff
@@ -220,6 +220,26 @@ func (c *TokensCommand) Add(ctx context.Context, client auth.ClientI) error {
 
 	// Print signup message.
 	switch {
+	case roles.Include(types.RoleWindowsDesktop):
```
Comment (zmb3) [inline tool/tctl/common/token_command.go:223]: If the token includes both desktop and kube roles, you'll only print the destkop template here. Is this the behavior you intended?

Comment (stevenGravy) [reply tool/tctl/common/token_command.go:223]: They're all like this depending on the order. You only get one of them.

Comment (stevenGravy) [reply tool/tctl/common/token_command.go:223]: We can change it to iterate through and print all the situations

Comment (stevenGravy) [reply tool/tctl/common/token_command.go:223]: We can move desktop to the end.

Comment (GavinFrazar) [reply tool/tctl/common/token_command.go:223]: I prefer the desktop output that just links to docs for using the token instead of printing commands to use (but I have other issues with `tctl token add`, see: https://github.com/gravitational/teleport/issues/19894).

I think your PR is fine as-is because it's just doing the same as other types of tokens, but how would you feel about changing `tctl tokens add` to print a list of docs links for each token type in the `--token` list? For example:

```
$ tctl tokens add --type=kube,windows_desktop
The invite token: 124ffa40c84cc7ea0d855b9fe892176e
This token will expire in 60 minutes.

This token enables kubernetes and windows desktop services.
See Teleport documentation for more details:
- https://goteleport.com/docs/kubernetes-access
- https://goteleport.com/docs/desktop-access/

Comment (stevenGravy) [reply tool/tctl/common/token_command.go:223]: @GavinFrazar I'm fine with changing to that.  I think the output has caused more confusion in cases.

Comment (stevenGravy) [reply tool/tctl/common/token_command.go:223]: @zmb3 thoughts?

Comment (zmb3) [reply tool/tctl/common/token_command.go:223]: I'm fine with just moving desktop to the end.

Comment (stevenGravy) [reply tool/tctl/common/token_command.go]: @zmb3 moved

Comment (GavinFrazar) [reply tool/tctl/common/token_command.go]: @stevenGravy thanks, I just wanted your thoughts on that suggestion. If it wasn't clear, I should clarify that I wasn't suggesting you make that change (to use docs links only) in this PR.

**Review by GavinFrazar — APPROVED** [review]

File: tool/tctl/common/token_command.go (hunk 2 above)
Comment (stevenGravy) [reply tool/tctl/common/token_command.go]: @zmb3 good to go then?

**Review by zmb3 — APPROVED** [review]
