### PR TITLE
fncache test improvements

### LINKED ISSUE #14534: `TestFnCacheSanity` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/a47d1dff-fa4c-4ba6-88c9-aa474f19b96c?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/f74bb490-6b78-4f9b-959c-94e839d1b9a9?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/7fa3a357-ebcb-4ce0-84ab-bb178694efd0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/a548f2c3-a15e-4eb1-8f4e-735fb9e1d7fc?project=ci-account

#### Relevant snippet

```
=== RUN   TestFnCacheSanity/non-blocking
    fncache_test.go:151: 
        	Error Trace:	fncache_test.go:151
        	            				fncache_test.go:76
        	Error:      	Max difference between 11.10786165 and 9 allowed is 2, but difference was 2.1078616500000003
        	Test:       	TestFnCacheSanity/non-blocking
    --- FAIL: TestFnCacheSanity/non-blocking (0.45s)
```

### PR DESCRIPTION
**Pull request by fspmarshall**
Replaces previous fuzzy fncache sanity check with a couple more deterministic tests that cover _mostly_ the same stuff.  Instead of removing the fuzzy testing, it is now behind an env var so that fuzzy tests can still be run locally when making changes to the fncache, but no longer interfere with CI.

Fixes https://github.com/gravitational/teleport/issues/14534

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: lib/utils/fncache_test.go [hunk 1]
```diff
@@ -56,10 +60,99 @@ func TestFnCache_New(t *testing.T) {
...
+	// and now we're back to hitting a cached value
+	require.False(t, get())
+}
+
+// TestFnCacheFuzzy runs basic FnCache test cases that rely on fuzzy logic and timing to detect
+// success/failure. This test isn't really suitable for running in our CI env due to its sensitivery
+// to fluxuations in perf, but is arguably a *better* test in that it more accurately simulates real
+// usage. This test should be run locally with TEST_FNCACHE_FUZZY=yes when making changes.
+func TestFnCacheFuzzy(t *testing.T) {
+	if os.Getenv("TEST_FNCACHE_FUZZY") != "yes" {
```
Comment (jakule) [inline lib/utils/fncache_test.go:152]: Can we make it more generic and just check if the environment variable is set? I can see some people (including myself) setting it to `1` or `on` and being surprised that it is not working.
```suggestion
	if os.Getenv("TEST_FNCACHE_FUZZY") == "" {
```

File: lib/utils/fncache_test.go [hunk 2]
```diff
@@ -56,10 +60,99 @@ func TestFnCache_New(t *testing.T) {
...
+		t.Skip()
```
Comment (jakule) [inline lib/utils/fncache_test.go:153]: nit:
```suggestion
		t.Skip("Test disabled in CI. Enable it by setting env variable TEST_FNCACHE_FUZZY=yes")
```
Of course, I don't mind different wording.

File: lib/utils/fncache_test.go [hunk 3]
```diff
@@ -56,10 +60,99 @@ func TestFnCache_New(t *testing.T) {
...
+		require.Equal(t, val, r.val.(string))
+	}
+}
+
+// TestFnCacheExpiry verfies basic expiry.
+func TestFnCacheExpiry(t *testing.T) {
 	t.Parallel()
 
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
```
Comment (jakule) [inline lib/utils/fncache_test.go:112]: nit:
```suggestion
	t.Cleanup(cancel)
```

File: lib/utils/fncache_test.go [hunk 4]
```diff
@@ -56,10 +60,99 @@ func TestFnCache_New(t *testing.T) {
...
+}
+
+// TestFnCacheConcurrentReads verifies that many concurrent reads result in exactly one
+// value being actually loaded via loadfn if a reasonably long TTL is used.
+func TestFnCacheConcurrentReads(t *testing.T) {
+	const workers = 100
+	t.Parallel()
+
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
```
Comment (jakule) [inline lib/utils/fncache_test.go:75]: nit:
```suggestion
	t.Cleanup(cancel)
```

**Review by jakule — APPROVED** [review]
A few nits, LGTM

File: lib/utils/fncache_test.go (hunk 3 above)
Comment (fspmarshall) [reply lib/utils/fncache_test.go:114]: IMO `defer` is still the preferable way to do things like this.  `t.Cleanup` is great for simplifying the API of testing helpers/suites, and for handling the cleanup of resources shared across subtests, but IMO replacing a normal `defer` with a `t.Cleanup` is pointless and potentially harmful since it creates an unnecessary divergence between test and non-test code styles.
