### PR TITLE
tctl: fix create cmd when input starts with an empty doc

### LINKED ISSUE #4703: blank line at start of yaml not valid
### Description

**What happened**:

if the start of any manifest contains a blank line, teleport cannot parse the file

```
error: creating resources of type "" is not supported
```

Example:

```

---
kind: role
version: 3
....
```

note the empty line, on line 1

**What you expected to happen**:

File to be parsed

**How to reproduce it (as minimally and precisely as possible)**:

Have an empty line at the start of the file

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.3.7git:v4.3.7-0-g3687d398b go1.13.2
- Tsh version (use `tsh version`): Teleport v4.3.5 git:v4.3.5-0-g122349e78 go1.13.2
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

### PR DESCRIPTION
**Pull request by zmb3**
Closes #4703

### CODE REVIEW

**Review by marcoandredinis — APPROVED** [review]

**Review by gzdunek — APPROVED** [review]

File: tool/tctl/common/resource_command.go [hunk 1]
```diff
@@ -405,6 +406,13 @@ func (rc *ResourceCommand) Create(ctx context.Context, client *authclient.Client
 		}
 		count++
 
+		// An empty document at the beginning of the input will unmarshal without error.
+		// Keep reading - there may be a valid document later on.
+		// https://github.com/gravitational/teleport/issues/4703
+		if reflect.ValueOf(raw).IsZero() {
+			continue
+		}
+
```
Comment (hugoShaka) [inline tool/tctl/common/resource_command.go:415]: Should we skip before incrementing `count`?

**Review by hugoShaka — APPROVED** [review]
