### PR TITLE
Fix GoRoutine leak in `authclient.Connect`

### LINKED ISSUE #26085: Machine ID: `tbot` leaks memory
Reported versions:
- 12.3.3
- 12.1.1

Configuration is simple:
- IAM Joining
- Teleport Cloud
- 20m interval, 1h TTL
- Single destination with identity file

image

### PR DESCRIPTION
**Pull request by strideynet**
`authclient.Connect` would always leak a single goroutine when connecting directly to the auth server failed. In applications that make many clients, such as `tbot`, this becomes a significant leak over time.

Here's a profile from before the fix for `tbot`: https://gist.github.com/strideynet/0712ed070cca2fac9d3c26c3fce5a341

After the fix, the number of goRoutines waiting at `google.golang.org/grpc.(*ccBalancerWrapper).watcher+0x72` remains at 1, rather than slowly climbing.

Closes https://github.com/gravitational/teleport/issues/26085

### CODE REVIEW

File: lib/auth/authclient/authclient.go [hunk 1]
```diff
@@ -71,61 +71,68 @@ func Connect(ctx context.Context, cfg *Config) (auth.ClientI, error) {
...
+	})
+	if err != nil {
+		tunnelClientErr := trace.Wrap(err, "failed dial to auth server through reverse tunnel: %v", err)
+		return nil, trace.NewAggregate(directDialErr, tunnelClientErr)
+	}
+	// Check connectivity by calling something on the client.
+	if _, err := tunnelClient.GetClusterName(); err != nil {
+		_ = tunnelClient.Close() // This client didn't work for us, so we close it.
+		tunnelClientErr := trace.Wrap(err, "failed dial to auth server through reverse tunnel: %v", err)
+		return nil, trace.NewAggregate(directDialErr, tunnelClientErr)
```
Comment (smallinsky) [inline lib/auth/authclient/authclient.go:135]: nit: Could we move this code to a sperate function to improve readability ?

**Review by smallinsky — APPROVED** [review]
nice finding. LGTM.

File: lib/auth/authclient/authclient.go (hunk 1 above)
Comment (strideynet) [reply lib/auth/authclient/authclient.go:135]: Yeah that seems like a good idea !

**Review by tigrato — APPROVED** [review]
