### PR TITLE
Return better error during group creation with invalid group name

### LINKED ISSUE #21165: Improve Error Message for User Host Creation
What would you like Teleport to do?
Currently, failures in Host User Creation related to host groups creates the error message:
`User Message: error while creating groups`

Request is to improve this error message with further details around the exact command it ran including the group names

What problem does this solve?
Users hitting this error and unable to find the resolution swiftly.  A recent real world example, it took a while to isolate the root issue creating this error was a misconfiguration in the host_groups of a role:
~~~
host_groups:
  - "*"
~~~
Having this output by the error message would have made the problem immediately obvious to the end user to self solve.

Sample Logs
~~~
DEBU             "Error creating user xxxxx: error while creating groups\n\texit status 3" srv/sess.go:207
teleport[28462]: 2023-01-30T14:55:15Z ERRO             failure handling SSH "shell" request error:[
teleport[28462]: ERROR REPORT:
teleport[28462]: Original Error: trace.aggregate exit status 3
teleport[28462]: Stack Trace:
teleport[28462]: github.com/gravitational/teleport/lib/srv/usermgmt.go:211 github.com/gravitational/teleport/lib/srv.(*HostUserManagement).CreateUser
teleport[28462]: github.com/gravitational/teleport/lib/srv/sess.go:205 github.com/gravitational/teleport/lib/srv.(*SessionRegistry).TryCreateHostUser
teleport[28462]: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1603 github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch
teleport[28462]: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1487 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
teleport[28462]: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1208 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1
teleport[28462]: runtime/asm_amd64.s:1594 runtime.goexit
teleport[28462]: User Message: error while creating groups
~~~

### PR DESCRIPTION
**Pull request by eriktate**
Fixes #21165

Returns a `trace.BadParameter` error when `groupadd` fails with exit code 3 ("invalid argument to option"). If the command output contains "not a valid group name" then the message wrapped by `trace.BadParameter` specifies that. Otherwise we just report there was an invalid parameter. Regardless of which specific error message is resolved, adding the group name to the error returned in `createGroupIfNotExists` should help make it more obvious that a role's `host_groups` array has an invalid entry when session creation fails.

### CODE REVIEW

File: lib/srv/usermgmt.go [hunk 1]
```diff
@@ -451,11 +451,17 @@ func (u *HostUserManagement) createGroupIfNotExist(group string) error {
...
 	if trace.IsAlreadyExists(err) {
 		return nil
 	}
-	return trace.Wrap(err)
+
+	if err != nil {
+		return trace.Errorf("while creating group %q %w", group, err)
+	}
+
+	return nil
```
Comment (zmb3) [inline lib/srv/usermgmt.go:464]:
```suggestion
	return trace.Wrap(err, "creating group %q", group)
```

File: lib/utils/host/hostusers.go [hunk 2]
```diff
@@ -56,6 +57,15 @@ func GroupAdd(groupname string, gid string) (exitCode int, err error) {
 	if cmd.ProcessState.ExitCode() == GroupExistExit {
 		return cmd.ProcessState.ExitCode(), trace.AlreadyExists("group already exists")
 	}
+
+	if cmd.ProcessState.ExitCode() == GroupInvalidArg {
```
Comment (zmb3) [inline lib/utils/host/hostusers.go:61]: Up to you, but it may be about time to `switch code := cmd.ProcessState.ExitCode(); code {`...

**Review by zmb3 — APPROVED** [review]

File: lib/utils/host/hostusers.go (hunk 2 above)
Comment (eriktate) [reply lib/utils/host/hostusers.go:61]: Yeah I was thinking about that after I opened the PR. I'll go ahead and do that :+1:

File: lib/utils/host/hostusers.go [hunk 3]
```diff
@@ -53,9 +54,18 @@ func GroupAdd(groupname string, gid string) (exitCode int, err error) {
 	cmd := exec.Command(groupaddBin, args...)
 	output, err := cmd.CombinedOutput()
 	log.Debugf("%s output: %s", cmd.Path, string(output))
-	if cmd.ProcessState.ExitCode() == GroupExistExit {
+
+	switch cmd.ProcessState.ExitCode() {
```
Comment (zmb3) [inline lib/utils/host/hostusers.go:58]:
```suggestion
	switch code := cmd.ProcessState.ExitCode(); code {
```

Then you don't have to call `cmd.ProcessState.ExitCode()` 3 more times.

Comment (eriktate) [reply lib/utils/host/hostusers.go]: Good call, I totally forgot you could do that in a switch :sweat_smile:

**Review by rosstimothy — APPROVED** [review]
Slight nit: the error message returned to users is a bit repetitive 

```
ERROR: ssh: rejected: administratively prohibited (creating configured groups
	creating group "a13089da-29df-448a-b997-9029243d419c!@#$"
	invalid group name)
```
