### PR TITLE
Fix error message `tsh ssh` with no MFA device registered

### LINKED ISSUE #37146: Hardware keys - failed to SSH
`tsh ssh` fails when `require_session_mfa: hardware_key` is set in the auth config.

```
$ tsh ssh dffe30aa-cc94-47fa-b461-ae8e08cfacf9
Enter password for Teleport user bob:
ERROR: unknown or missing MFAAuthenticateResponse type <nil>
```

Bug details:
- Teleport version: 15.0.0-alpha.5
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by Joerger**
Restore the `ErrNoMFADevices` error previously returned by `tsh ssh` when no device is registered for the user.

This was changed by https://github.com/gravitational/teleport/pull/33305, which deprecated the use of `GenerateUserSingleUseCerts`.

Closes https://github.com/gravitational/teleport/issues/37146

### CODE REVIEW

**Comment by Joerger** [comment]
This PR currently regresses https://github.com/gravitational/teleport/issues/36482, putting in draft for now

File: lib/auth/auth.go [hunk 1]
```diff
@@ -3009,6 +3009,7 @@ func (a *Server) CreateAuthenticateChallenge(ctx context.Context, req *proto.Cre
 		log.Error(trace.DebugReport(err))
 		return nil, trace.AccessDenied("unable to create MFA challenges")
 	}
+
```
Comment (Joerger) [inline lib/auth/auth.go:3012]:
```suggestion
```

**Review by EdwardDowling — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
