### PR TITLE
Fix flaky test `TestIntegrations/X11Forwarding`

### LINKED ISSUE #47756: `TestIntegrations/X11Forwarding` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/11442800048/job/31833983642

#### Relevant snippet

```
==================
WARNING: DATA RACE
Write at 0x00c005069900 by goroutine 56906:
  github.com/gravitational/teleport/integration.testX11Forwarding.func3.3.3.1()
      /__w/teleport/teleport/integration/integration_test.go:4752 +0xa4
  github.com/stretchr/testify/assert.Eventually.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x33

Previous write at 0x00c005069900 by goroutine 56878:
  github.com/gravitational/teleport/integration.testX11Forwarding.func3.3.3.1()
      /__w/teleport/teleport/integration/integration_test.go:4752 +0xa4
  github.com/stretchr/testify/assert.Eventually.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x33

Goroutine 56906 (running) created at:
  github.com/stretchr/testify/assert.Eventually()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x3d5
  github.com/gravitational/teleport/integration.testX11Forwarding.func3.3.3()
      /__w/teleport/teleport/integration/integration_test.go:4749 +0x31e
  github.com/stretchr/testify/assert.EventuallyWithT.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1983 +0xb7

Goroutine 56878 (finished) created at:
  github.com/stretchr/testify/assert.Eventually()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x3d5
  github.com/gravitational/teleport/integration.testX11Forwarding.func3.3.3()
      /__w/teleport/teleport/integration/integration_test.go:4749 +0x31e
  github.com/stretchr/testify/assert.EventuallyWithT.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1983 +0xb7
==================
```

### PR DESCRIPTION
**Pull request by Joerger**
This test suffered from the same data race explained in https://github.com/gravitational/teleport/pull/48045, except that the race could now result in an `assert.Eventually` attempt sending display (and blocking the channel) after the outer `require.EventuallyWithT` had already moved on to a new `assert.Eventually` attempt with the next tick. The latter attempt would then block on `display <- ...` and end up failing.

The fix I chose is to stagger the outer eventually to ensure the inner eventually attempt has ample time to complete before moving on to another attempt.

### CODE REVIEW

**Review by marcoandredinis — APPROVED** [review]

**Review by bl-nero — APPROVED** [review]

File: integration/integration_test.go [hunk 1]
```diff
@@ -4858,7 +4858,7 @@ func testX11Forwarding(t *testing.T, suite *integrationTestSuite) {
 								}
 								return false
 							}, time.Second, 100*time.Millisecond, "failed to read display")
-						}, 10*time.Second, time.Second)
+						}, 10*time.Second, 2*time.Second)
```
Comment (tigrato) [inline integration/integration_test.go:4861]: isn't it better to just use a select statement instead of increasing the time? Is 2s enough?

select{
case display <- strings.TrimSpace(string(output)):
default:
return true

}

?

Comment (Joerger) [reply integration/integration_test.go:4861]: Yeah we can go with the select case, wasn't sure what's better

**Review by tigrato — APPROVED** [review]
