### PR TITLE
Remote clusters should only send their own CAs.

### LINKED ISSUE #1050: 2.0.6 to 2.2 alpha upgrade issue with DynamoDB backend
Originally reported by @ekristen in #896 (in comments at the bottom):

Well I upgraded to alpha8 and now I cannot add anymore nodes. Getting the cluster has no signing keys. There seems to be something with upgrading to a new version using dynamodb that breaks everything.

Logs:

```
level=warning 
msg="[AUTH] Node \"server-001\" [11fbfa42-17b9-4cfe-a863-65e791663838] can not join:
      certificate generation error: my-cluster has no signing keys" 

file="auth/auth.go:464" func="auth.(*AuthServer).GenerateServerKeys"
```

I cannot since I've already upgraded. However I was on 2.0.6 and now I am on Teleport v2.2.0-alpha.8 git:v2.1.0-alpha.6-43-g14cf169d-dirty

I can tell you that I've now seen this happen multiple times across multiple versions. I am using dynamodb as a backend. I attempted to replicate it using dir mode only and a single auth server and was unable to.

After that I went back to using dynamodb with mulitple auth servers however I only use 1 when registering nodes, so while the other 2 are running the auth service nothing is talking to them.

Everything seemed great for a while, I was able to add nodes and this bug seemed to not be present anymore until I upgraded to alpha8 and I completely lost the ability to register nodes again.

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

At the moment, when doing a Trusted Cluster exchange, the remote cluster sends all the CAs that it has to the main cluster which then adds these CAs to it's own backend. Then the main CA sends it's CAs to the Trusted Cluster which adds them to it's own backend.

This exchange works correctly the first time it occurs. However if you try and add an existing Trusted Cluster twice, since the Trusted Cluster sends all of the CAs it has, it sends back the CA for the main cluster as well, but it sends it back without signing keys. The main cluster adds it to it's backend which then causes an error similar to the following to occur when trying to add a node (because the CA legitimately no longer has it's signing keys).

```
failed to join the cluster: main has no signing keys
```

To fix this problem, the Trusted Cluster should only send it's own CAs to the main cluster.

**Implementation**

* When the remote cluster gets a list of CAs, filter out all non-local CAs.
* Improved logging so we log the certificate authorities we send and receive. 
* Added test coverage in the integration package to upsert a Trusted Cluster multiple time and check that the right certificates were exchanged.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1050

### CODE REVIEW

File: lib/auth/trustedcluster.go [hunk 1]
```diff
@@ -46,28 +47,48 @@ func (a *AuthServer) UpsertTrustedCluster(trustedCluster services.TrustedCluster
...
+		}
+	}
 
 	// create a request to validate a trusted cluster (token and local certificate authorities)
 	validateRequest := ValidateTrustedClusterRequest{
 		Token: trustedCluster.GetToken(),
 		CAs:   localCertAuthorities,
 	}
 
+	// log the local certificate authorities that we are sending
```
Comment (klizhentas) [inline lib/auth/trustedcluster.go]: seems like a lot of repetition of the same logic, can you factor this into separate function, e.g.

```go
type CertAuthorities []CertAuthority

func (s CertAuthorities) String() string {
  ... formatting logic
}

so later you can do this:

log.Debugf("[TRUSTED CLUSTER %v", CertAuthority(validateRequest.CAs))
```

**Review by klizhentas — COMMENTED** [review]
looks good except verbose formatting logic

**Review by kontsevoy — APPROVED** [review]
LGTM but I would like @klizhentas to take a look as well.

**Comment by russjones** [comment]
@klizhentas Made the changes you suggested.

**Review by klizhentas — APPROVED** [review]
