### PR TITLE
Make error messages specific

### LINKED ISSUE #6046: Teleport should emit "Audit Events" on SSO login errors
Currently it's impossible to troubleshoot SSO errors (SAML, OIDC, Github) without having access to Teleport logs (or restarting Teleport to enable a debug mode)

Instead, Teleport Proxy should emit audit "Failed Login" events with the error description. This way people can troubleshoot the issue from web UI.

### PR DESCRIPTION
**Pull request by kimlisa**
resolves https://github.com/gravitational/teleport/issues/6046

#### Description
Note: there is a bug with trace marshalling proxyErr: https://github.com/gravitational/teleport/pull/6108#discussion_r599795110

Purpose is to allow users with admin privilege that are able to view audit logs, to be able to debug SSO login failures from the UI as much as possible:
- emit audit events when there are failures from creating sso auth requests
- since we no longer expose any specific errors when users fail to login from UI, returned error messages are more specific so that it is clear what the error is when viewing audit logs
- return generic `login failed` message for sso CLI login failures (which are errors from creating an auth request) similar in the UI dashbaord where we also display generic error message

### CODE REVIEW

File: lib/auth/auth_test.go [hunk 1]
```diff
@@ -1085,6 +1085,28 @@ func TestU2FSignChallengeCompat(t *testing.T) {
 	})
 }
 
+func TestEmitSSOLoginFailureEvent(t *testing.T) {
+	mockE := &events.MockEmitter{}
+
+	emitSSOLoginFailureEvent(context.Background(), mockE, "test", trace.BadParameter("some error"))
+	event := mockE.LastEvent().(*events.UserLogin)
```
Comment (a-palchikov) [inline lib/auth/auth_test.go:1092]: Instead of type assertion (which might potentially trigger a panic), assert the equivalence with `require`, e.g. it should suffice to:
```go
require.Equal(t, mockE.LastEvent(), &events.UserLogin{
	Metadata: events.Metadata{
		Type: events.UserLoginEvent,
		Code: events.UserSSOLoginFailureCode,
	},
	Method: "test",
	Status: events.Status{
		Success:     false,
		Error:       "some error",
		UserMessage: "some error",
	},
})
```
and matching on `Method` will not be necessary since it's also part of the expectation.

File: lib/auth/oidc.go [hunk 2]
```diff
@@ -810,21 +809,21 @@ func (a *Server) getClaims(oidcClient *oidc.Client, connector services.OIDCConne
...
 	}
 	if uisub, exists, err = userInfoClaims.StringClaim("sub"); err != nil || !exists {
 		log.Debugf("Unable to extract OIDC sub claim from UserInfo.")
-		return nil, trace.Wrap(err)
+		return nil, trace.Wrap(err, "unable to extract OIDC sub claim from UserInfo")
 	}
 	if idsub != uisub {
-		log.Debugf("OIDC claim subjects don't match '%v' != '%v'.", idsub, uisub)
-		return nil, trace.BadParameter("invalid subject in UserInfo")
+		log.Debugf("OIDC claim subjects does not match '%v' != '%v'.", idsub, uisub)
```
Comment (a-palchikov) [inline lib/auth/oidc.go:819]: I think it was grammatically correct before?

File: lib/utils/cli.go [hunk 3]
```diff
@@ -196,8 +197,15 @@ func UserMessageFromError(err error) string {
 			}
 			fmt.Fprintln(&buf, AllowNewlines(trace.Unwrap(er).Error()))
 		} else {
-			fmt.Fprintln(&buf, AllowNewlines(err.Error()))
+			strErr := err.Error()
+			// Error can be of type trace.proxyError where error message didn't get captured.
```
Comment (a-palchikov) [inline lib/utils/cli.go:201]: This is somewhat misleading. Did you have a specific error that did not transport the message over the wire? All errors coming from the server over HTTP will be of type [trace.proxyError](https://github.com/gravitational/trace/blob/bbab4b868a4a8a002ffc76d005d53996506ef059/trace.go#L594) and it's supposed to transport the message with it - if that's not the case here, it's probably a bug to be fixed.

Comment (kimlisa) [reply lib/utils/cli.go:201]: I was trying to purposely cause errors when logging in with sso through CLI and I found errors came back as empty strings. I traced into it and I thought maybe it was by design to prevent sensitive error messages from auth from being exposed?

This is how errors get marshalled: https://github.com/gravitational/trace/blob/master/httplib.go#L87
And this is how errors get unmarshalled: https://github.com/gravitational/trace/blob/master/httplib.go#L59
And this is how requests are made in both client and proxy: https://github.com/gravitational/teleport/blob/master/lib/auth/clt.go#L251

Given tsh client -> proxy -> auth make request
First marshal/unmarshal auth to proxy: when error from auth gets marshalled,  the error is of type `TraceErr`, and when it gets unmarshalled, error is unmarshaled into `TraceErr` and wrapped in `proxyErr`

Second marshal/unmarshal proxy to client: When this proxyErr gets marshalled, b/c it is not a type of `TraceErr`, everything gets stripped except error field, and when this gets unmarshalled it gets unmarshalled into trace error struct that only has `message` as its field, so the error field never gets saved and message is empty.

Comment (a-palchikov) [reply lib/utils/cli.go:201]: Ok, I see. This a bug in trace and should be definitely fixed so it's possible to send errors over the wire multiple times. I'll see how complicated this would be.

File: lib/auth/auth_test.go (hunk 1 above)
Comment (kimlisa) [reply lib/auth/auth_test.go]: revised

File: lib/auth/oidc.go (hunk 2 above)
Comment (kimlisa) [reply lib/auth/oidc.go]: reverted

File: lib/utils/cli.go (hunk 3 above)
Comment (kimlisa) [reply lib/utils/cli.go:201]: Since this is a bug, I went back to all console logins `github`, `oidc`, `saml`, in the webapi layer and made sure to return a generic error message for all errors to hide sensitive data. This is what we did for UI dashboard logins (and validating auth callbacks) where any errors encountered we redirected users to a generic error page with direction to check teleports log: https://github.com/gravitational/teleport/pull/6108/commits/50078d3cbbaf743e457a719b93b4ce81b5c203e7

File: lib/auth/oidc.go [hunk 4]
```diff
@@ -103,25 +103,7 @@ func (a *Server) createOIDCClient(conn services.OIDCConnector) (*oidc.Client, er
...
-				UserMessage: err.Error(),
-			},
-		}); err != nil {
-			log.WithError(err).Warn("Failed to emit OIDC login failure event.")
-		}
-		// return user-friendly error hiding the actual error in the event
-		// logs for security purposes
-		return nil, trace.ConnectionProblem(nil,
-			"failed to login with %v",
-			conn.GetDisplay())
```
Comment (kimlisa) [inline lib/auth/oidc.go:124]: Since we no longer show the users the actual login errors (but a generic login failed msg), I didn't think it was necessary to hide this error and simply return the actual error for the outer caller to emit the events (also removes double emitting)

**Review by alex-kovoy — APPROVED** [review]

File: lib/auth/oidc.go [hunk 5]
```diff
@@ -242,43 +224,44 @@ func (a *Server) CreateOIDCAuthRequest(req services.OIDCAuthRequest) (*services.
...
-		if re != nil && re.claims != nil {
-			attributes, err := events.EncodeMap(re.claims)
-			if err != nil {
-				log.WithError(err).Debugf("Failed to encode identity attributes.")
-			} else {
-				event.IdentityAttributes = attributes
-			}
+
+		if err := a.emitter.EmitAuditEvent(a.closeCtx, event); err != nil {
+			log.WithError(err).Warn("Failed to emit OIDC login failed event.")
```
Comment (a-palchikov) [inline lib/auth/oidc.go:252]: nit: log these at `Debug` if these aren't critical.

File: lib/web/apiserver.go [hunk 6]
```diff
@@ -898,14 +903,22 @@ func (h *Handler) githubLoginWeb(w http.ResponseWriter, r *http.Request, p httpr
 }
 
 func (h *Handler) githubLoginConsole(w http.ResponseWriter, r *http.Request, p httprouter.Params) (interface{}, error) {
-	h.log.WithField("auth", "github").Debug("Console login start.")
+	logger := h.log.WithField("auth", "github")
+	logger.Debug("Console login start.")
+
+	generalErr := trace.AccessDenied(ssoLoginConsoleErr)
```
Comment (a-palchikov) [inline lib/web/apiserver.go:909]: Even though this seems to reduce the error handling (if that's the intent), it will obscure the actual point of error emission and might complicate analysis as several places would be likely candidates as the error source - it's better to emit the error at each point with the corresponding `trace` error constructor.

**Review by a-palchikov — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

File: lib/auth/oidc.go (hunk 5 above)
Comment (kimlisa) [reply lib/auth/oidc.go:252]: i constructed these to be consistent with others (others use warn), i think it also makes sense to use warn here b/c missing an event for auditing should stand out

File: lib/web/apiserver.go (hunk 6 above)
Comment (kimlisa) [reply lib/web/apiserver.go]: Revised so that each error returns its own trace err so tracing is closer to origin of actual error
