### PR TITLE
Fix `ssh -X -oControlMaster` to agentless nodes.

### LINKED ISSUE #38238: X11 forwarding should work when using `ControlMaster` with OpenSSH agentless nodes.
When connecting to an OpenSSH agentless node, the SSH session is terminated at the Teleport Proxy to enable proxy mode session recording. When combined with the `ControlMaster` functionality when using an `ssh` client, only the first `ssh` session that requests X11 forwarding will work. Subsequent `ssh` invocations that try to open an X11 channel forward will be denied by the Teleport Proxy. The `ssh_config` used in this case was generated by running `tsh config > ssh_config` and then adding the following to the second Host block: `ControlMaster auto`, `ControlPath /tmp/%r@%h-%p`, `ControlPersist 24h`.

```
% ssh -p 22 -v -F ssh_config root@ip-192-168-71-28.us-east-2.compute.internal.teleport.example.com
OpenSSH_9.4p1, LibreSSL 3.3.6
debug1: Reading configuration data ssh_config
debug1: ssh_config line 4: Applying options for *.teleport.example.com
debug1: ssh_config line 11: Applying options for *.teleport.example.com
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 4
X11 forwarding channel already open
                                   PTY allocation request failed
Shared connection to ip-192-168-71-28.us-east-2.compute.internal.teleport.example.com closed.
```

The Teleport Proxy itself logs the following:

```
teleport-proxy-d78c59654-gnlwv teleport 2024-02-14T17:17:34Z DEBU [NODE:FORW] Opening session request to 203.0.113.183:61052 in context 5. trace.fields:map[dst-addr:ec2-203-224-23-221.us-east-2.compute.amazonaws.com:22 src-addr:203.0.113.183:61052] forward/sshserver.go:1098
teleport-proxy-d78c59654-gnlwv teleport 2024-02-14T17:17:35Z DEBU [NODE:FORW] Handling request x11-req, want reply true. cert:2024-02-15 03:41:09 +0000 UTC id:5 local:ec2-203-224-23-221.us-east-2.compute.amazonaws.com:22 login:root remote:203.0.113.183:61052 teleportUser:jeff forward/sshserver.go:1173
teleport-proxy-d78c59654-gnlwv teleport 2024-02-14T17:17:35Z ERRO [NODE:FORW] failure handling SSH "x11-req" request error:[
teleport-proxy-d78c59654-gnlwv teleport ERROR REPORT:
teleport-proxy-d78c59654-gnlwv teleport Original Error: *trace.AlreadyExistsError X11 forwarding channel already open
teleport-proxy-d78c59654-gnlwv teleport Stack Trace:
teleport-proxy-d78c59654-gnlwv teleport 	github.com/gravitational/teleport/lib/sshutils/x11/forward.go:117 github.com/gravitational/teleport/lib/sshutils/x11.ServeChannelRequests
teleport-proxy-d78c59654-gnlwv teleport 	github.com/gravitational/teleport/lib/srv/forward/sshserver.go:1376 github.com/gravitational/teleport/lib/srv/forward.(*Server).handleX11Forward
teleport-proxy-d78c59654-gnlwv teleport 	github.com/gravitational/teleport/lib/srv/forward/sshserver.go:1230 github.com/gravitational/teleport/lib/srv/forward.(*Server).dispatch
teleport-proxy-d78c59654-gnlwv teleport 	github.com/gravitational/teleport/lib/srv/forward/sshserver.go:1144 github.com/gravitational/teleport/lib/srv/forward.(*Server).handleSessionChannel
teleport-proxy-d78c59654-gnlwv teleport 	runtime/asm_amd64.s:1650 runtime.goexit
teleport-proxy-d78c59654-gnlwv teleport User Message: X11 forwarding channel already open] trace.fields:map[dst-addr:ec2-203-224-23-221.us-east-2.compute.amazonaws.com:22 src-addr:203.0.113.183:61052] forward/sshserver.go:1497
teleport-proxy-d78c59654-gnlwv teleport 2024-02-14T17:17:35Z INFO [AUDIT]     x11-forward addr.local:ec2-203-224-23-221.us-east-2.compute.amazonaws.com:22 addr.remote:203.0.113.183:61052 code:T3008W ei:0 error:[X11 forwarding channel already open] event:x11-forward login:root success:false time:2024-02-14T17:17:35.067Z uid:2dc7725e-dd31-c9c9-dead-fa6a080342e2 user:jeff user_kind:1 events/emitter.go:274
teleport-proxy-d78c59654-gnlwv teleport 2024-02-14T17:17:35Z DEBU [NODE:FORW] Closing session request to 203.0.113.183:61052 in context 5. trace.fields:map[dst-addr:ec2-203-224-23-221.us-east-2.compute.amazonaws.com:22 src-addr:203.0.113.183:61052] forward/sshserver.go:1147
teleport-auth-7cb8bb5476-dc846 teleport 2024-02-14T17:17:35Z INFO [AUDIT]     x11-forward addr.local:ec2-203-224-23-221.us-east-2.compute.amazonaws.com:22 addr.remote:203.0.113.183:61052 cluster_name:teleport.example.com code:T3008W ei:0 error:[X11 forwarding channel already open] event:x11-forward login:root success:false time:2024-02-14T17:17:35.067Z uid:2dc7725e-dd31-c9c9-dead-fa6a080342e2 user:jeff user_kind:1 events/emitter.go:274
teleport-proxy-d78c59654-gnlwv teleport 2024-02-14T17:17:35Z INFO [AUDIT]     session.data addr.local:ec2-203-224-23-221.us-east-2.compute.amazonaws.com:22 addr.remote:203.0.113.183:61052 code:T2006I ei:2.147483646e+09 event:session.data login:root namespace:default private_key_policy:none rx:5752 server_id:4668fc7a-341a-ae6f-d0d5-bc49432f1780 sid: time:2024-02-14T17:17:35.072Z tx:6745 uid:758fe2f2-2f46-1b2c-e7d6-9a723ba14aa8 user:jeff user_kind:1 events/emitter.go:274
teleport-auth-7cb8bb5476-dc846 teleport 2024-02-14T17:17:35Z INFO [AUDIT]     session.data addr.local:ec2-203-224-23-221.us-east-2.compute.amazonaws.com:22 addr.remote:203.0.113.183:61052 cluster_name:teleport.example.com code:T2006I ei:2.147483646e+09 event:session.data login:root namespace:default private_key_policy:none rx:5752 server_id:4668fc7a-341a-ae6f-d0d5-bc49432f1780 sid: time:2024-02-14T17:17:35.072Z tx:6745 uid:758fe2f2-2f46-1b2c-e7d6-9a723ba14aa8 user:jeff user_kind:1 events/emitter.go:274
```

`ControlMaster` functionality seems to otherwise work. Port forwards and simultaneous client `ssh` sessions all properly use the existing `mux` process.

The Teleport Proxy forward/ssh should be able to handle multiple X11 channels, just like an upstream `sshd` or Teleport node can.

This was tested with Teleport 14.3.4 on the cluster, along with a 14.3.4 `tsh` client. My `ssh` version is `OpenSSH_9.4p1, LibreSSL 3.3.6` and the remote `sshd` is `OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017` (amazon linux 2)

### PR DESCRIPTION
**Pull request by Joerger**
Fixes an issue with X11 forwarding from an OpenSSH client with ControlMaster mode on through the Proxy SSH forwarding service (Proxy Recording Mode, Agentless nodes). Since the SSH connection is being reused in Control Master mode, the forwarded connection is already set up to handle x11 forwarding requests. We can therefore safely ignore the `ErrX11ForwardChannelAlreadyOpen`.

Added an X11 forwarding integration test, with a ControlMaster+ProxyRecording subtest that fails without this fix.

changelog: Fixes an issue with X11 Forwarding when an OpenSSH client is being used with ControlMaster mode on.

Fixes https://github.com/gravitational/teleport/issues/38238

### CODE REVIEW

File: integration/helpers/helpers.go [hunk 1]
```diff
@@ -62,19 +62,21 @@ import (
...
+	ProxyPort     string
+	NodePort      string
+	Command       string
 }
 
 // ExternalSSHCommand runs an external SSH command (if an external ssh binary
 // exists) with the passed in parameters.
 func ExternalSSHCommand(o CommandOptions) (*exec.Cmd, error) {
 	var execArgs []string
+	execArgs = append(execArgs, "-v")
```
Comment (russjones) [inline integration/helpers/helpers.go:79]: Why do you have to put it in verbose mode?

Comment (Joerger) [reply integration/helpers/helpers.go]: Removed, I was using it for debugging the test.

File: lib/srv/forward/sshserver.go [hunk 2]
```diff
@@ -1348,8 +1348,10 @@ func (s *Server) handleX11Forward(ctx context.Context, ch ssh.Channel, req *ssh.
 		return trace.AccessDenied("X11 forwarding request denied by server")
 	}
 
+	// Set up the server to handle x11 channel requests from the client. If the OpenSSH
+	// control master option is in use, then the server might already be handling such requests.
 	err = x11.ServeChannelRequests(ctx, s.remoteClient.Client, s.handleX11ChannelRequest)
-	if err != nil {
+	if err != nil && !errors.Is(err, x11.ErrX11ForwardChannelAlreadyOpen) {
 		return trace.Wrap(err)
 	}
```
Comment (espadolini) [inline lib/srv/forward/sshserver.go:1356]: This would benefit from being extracted as an `ensureX11Forwarding` method on `*Server` for clarity's sake.

Why do we even need this? Couldn't we handle `x11` channels all the time?

**Review by espadolini — APPROVED** [review]

File: lib/srv/forward/sshserver.go (hunk 2 above)
Comment (Joerger) [reply lib/srv/forward/sshserver.go]: > Why do we even need this? Couldn't we handle x11 channels all the time?

I think you're right and I've changed it to always handle x11 channel requests, but it may be up for debate. 

Quoting the comment in my latest changes: 
```
According to RFC 4254, client "implementations MUST reject any X11 
channel open requests if they have not requested X11 forwarding". 
However, since this is a forwarding client implementation, we should 
simply accept and forward, leaving it up to the remote client to reject
the channel request.
```

Since client implementations must reject x11 channel requests, the forwarding client can safely assume that the channel request it forwards will be rejected.

However if we want to be abundantly cautious and follow the spec to a T, we could instead introduce a `Server.x11Requested` flag to determine whether we accept or reject x11 channel requests in `Server.handleX11ChannelRequest`. We'd then set that flag to true at the end of `Server.handleX11Forward`.

**Review by rosstimothy — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Review by espadolini — APPROVED** [review]
