### PR TITLE
Fix an issue `tsh` fails when Proxy is in separate mode and web port is TLS-terminated by a load balancer

### LINKED ISSUE #32531: tsh 14.0 from macOS Sonoma cannot connect with certificate issues
Expected behavior:
`tsh ssh --cluster cluster-x server-y` will start an SSH session on a server

Current behavior:
After login in and authenticating with touchID
```console
$ tsh ssh -d --cluster cluster-x server-y
2023-09-26T04:11:10+02:00 INFO [CLIENT]    ALPN connection upgrade required for "teleport.domain.com:443": true. client/api.go:723
2023-09-26T04:11:10+02:00 DEBU [CLIENT]    Skipping connection to the local ssh-agent. client/keyagent.go:137
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Reading certificates from path "/Users/sean.molenaar/.tsh/keys/teleport.domain.com/sean-ssh/cluster-x-cert.pub". client/keystore.go:354
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 INFO [KEYAGENT]  Loading SSH key for user "sean" and cluster "cluster-x". client/keyagent.go:196
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU             ALPN connection upgrade for teleport.domain.com:3023. client/alpn_conn_upgrade.go:187
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU [CLIENT]    Attempting to issue a single-use user certificate with an MFA check. client/cluster_client.go:105

ERROR REPORT:
Original Error: transport.ConnectionError connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: “7b5563ef-4099-494e-b21f-29476f71046f.cluster-x” certificate is not standards compliant\&#34;&#34;
Stack Trace:
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:1617 github.com/gravitational/teleport/api/client.(*Client).GenerateUserSingleUseCerts
        github.com/gravitational/teleport/lib/client/cluster_client.go:241 github.com/gravitational/teleport/lib/client.(*ClusterClient).performMFACeremony
        github.com/gravitational/teleport/lib/client/cluster_client.go:106 github.com/gravitational/teleport/lib/client.(*ClusterClient).SessionSSHConfig
        github.com/gravitational/teleport/lib/client/api.go:1742 github.com/gravitational/teleport/lib/client.(*TeleportClient).connectToNodeWithMFA
        github.com/gravitational/teleport/lib/client/api.go:1623 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToNode.func2
        runtime/asm_arm64.s:1197 runtime.goexit
User Message: connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: “7b5563ef-4099-494e-b21f-29476f71046f.cluster-x” certificate is not standards compliant\&#34;&#34;
```

Bug details:
- Teleport version: 14.0.0 on client, cluster, trusted cluster and my local machine
- Recreation steps: Not sure, it seems to just be: run `tsh ssh` from the latest macOS version.
- Debug logs: See above

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #32531 

When Proxy is in separate mode and web port is TLS-terminated by a load balancer, `tsh` tries to perform connection upgrades on SSH proxy address.

This change disables connection upgrades if TLS routing is disabled when using the new proxy client.

### CODE REVIEW

File: integration/proxy/proxy_test.go [hunk 1]
```diff
@@ -140,30 +136,28 @@ func TestALPNSNIProxyMultiCluster(t *testing.T) {
...
-
-					// Run command in leaf through ALB address.
-					suite.mustConnectToClusterAndRunSSHCommand(t, helpers.ClientConfig{
-						Login:   username,
-						Cluster: suite.leaf.Secrets.SiteName,
-						Host:    helpers.Loopback,
-						Port:    helpers.Port(t, suite.leaf.SSH),
-						ALBAddr: albProxy.Addr().String(),
-					})
+			t.Run("WebProxyAddr behind ALB", func(t *testing.T) {
```
Comment (greedy52) [inline integration/proxy/proxy_test.go:139]: Removed `tc.testALPNConnUpgrade` so `tc.SSH` is tested for all setups. `StandardAndOnePortSetupMasterALPNDisabled` catches the case fixed by this change.

Renamed the subtest, and updated `NewUnauthenticatedClient`helper in `helpers.instance.go` when `i.IsSinglePortSetup`. No other change to these tests.

**Review by rosstimothy — APPROVED** [review]

**Review by Joerger — APPROVED** [review]
