### PR TITLE
Ensure we don't miss the resolution of an access request

### LINKED ISSUE #9003: regression: race condition causes tsh login can hang indefinitely when requesting a role
### Description

**What happened**:

As of teleport 7.1.1, running `tsh login --request-roles ...` can hang indefinitely if the request is approved before tsh starts its event watcher to watch for the approval.

Seen on 7.1.1 and 7.3.3 in a lab environment.

```
Request ID: 35949cc2-8dc8-448a-ae32-ba69853f266c
Username:   requester
Roles:      access, admin, auditor, editor
Reason:     "foo"
Reviewers:  [none] (suggested)
Status:     APPROVED

hint: use 'tsh login --request-id=<request-id>' to login with an approved request

Waiting for request approval...
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
```

**What you expected to happen**:

tsh should recognize that the request is already approved and skip setting up the event watcher.

When tsh doesn't lose the race, the output looks like the following:

```
$ tsh login --user requester --proxy tp:443 --insecure --request-roles requester --request-reason foo
Enter password for Teleport user requester:
WARNING: You are using insecure connection to SSH proxy https://tp:443

Creating request...
Request ID: fe651867-634a-4303-a23f-4bf8394ef58f
Username:   requester
Roles:      access, admin, auditor, editor
Reason:     "foo"
Reviewers:  [none] (suggested)
Status:     PENDING

hint: use 'tsh login --request-id=<request-id>' to login with an approved request

Waiting for request approval...

Approval received, getting updated certificates...

> Profile URL:        https://tp:443
  Logged in as:       requester
  Cluster:            old
  Roles:              access, admin, auditor, editor, requester
  Logins:             requester
  Kubernetes:         enabled
  Kubernetes groups:  system:masters
  Valid until:        2021-11-16 06:48:34 +0000 UTC [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

note that the request Status is listed as "APPROVED" before tsh outputs "Waiting for request approval".

If it's already approved, it should simply proceed:

```
Request ID: 35949cc2-8dc8-448a-ae32-ba69853f266c
Username:   requester
Roles:      access, admin, auditor, editor
Reason:     "foo"
Reviewers:  [none] (suggested)
Status:     APPROVED

hint: use 'tsh login --request-id=<request-id>' to login with an approved request

Approval received, getting updated certificates...

> Profile URL:        https://tp:443
  Logged in as:       requester
  Cluster:            old
  Roles:              access, admin, auditor, editor, requester
  Logins:             requester
  Kubernetes:         enabled
  Kubernetes groups:  system:masters
  Valid until:        2021-11-16 06:48:34 +0000 UTC [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

### Reproduction Steps

The easiest way to reproduce this is to do two things:

1. Set up a loop to approve all requests as soon as possible:

```
while true; do
	requests=$(tctl requests ls | grep PENDING | awk '{print $1}')
	echo $requests | xargs -n 1 tctl requests approve ;
	if [ ! -z $requests ];  then
		echo $requests
	fi
	sleep 0.1;
done
```

2. slow down tsh's ability to communicate. The easiest way to do this is in a container:

```
$ docker run --rm -it --privileged --entrypoint bash quay.io/gravitational/teleport:7.3.3
root@064eea0b8a43:/# RUN apt update && apt install -y iputils-ping iproute2
root@064eea0b8a43:/# tc qdisc add dev eth0 root netem delay 900ms
root@064eea0b8a43:/# tsh login --proxy teleport.example.com --user myuser --request-roles requesters --request-reason "testing"
```

That `tc` command will introduce an artificial 900ms of delay to every network packet on that container's eth0 interface. This means that tsh will take a lot longer to go through its procedure, and lose the race condition since the `tctl requests approve` happening in a loop will approve the request before `tsh` goes to wait for the request to change to approved, and it gets stuck waiting for the change.

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`): observed on 7.1.1 and 7.3.3. 7.1.0 is NOT affected.
- Computer OS (e.g. Linux, macOS, Windows): teleport image from quay: single node with local storage in the lab
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): teleport image from quay.
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`) N/A
- Run tsh with --debug flag (`tsh --debug`) 

```
root@ac5c2aaaf74c:~# tsh login --debug --user requester --proxy tp:443 --insecure --request-roles requester --request-reason foo
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:56:03 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Reading certificates from path "/root/.tsh/keys/tp/requester-ssh/old-cert.pub". client/keystore.go:303
INFO [CLIENT]    no host login given. defaulting to root client/api.go:1042
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:2795
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:56:03 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Reading certificates from path "/root/.tsh/keys/tp/requester-ssh/old-cert.pub". client/keystore.go:303
INFO [KEYAGENT]  Loading SSH key for user "requester" and cluster "old". client/keyagent.go:179
DEBU [CLIENT]    not using loopback pool for remote proxy addr: tp:443 client/api.go:2760
DEBU             Attempting GET tp:443/webapi/ping webclient/webclient.go:62
Enter password for Teleport user requester:
DEBU [CLIENT]    not using loopback pool for remote proxy addr: tp:443 client/api.go:2760
DEBU [CLIENT]    HTTPS client init(proxyAddr=tp:443, insecure=true) client/weblogin.go:212
WARNING: You are using insecure connection to SSH proxy https://tp:443
DEBU [KEYAGENT]  Adding CA key for old client/keyagent.go:301
DEBU [KEYSTORE]  Adding known host old with proxy tp and key: SHA256:6/pUEbbHF4RrTyvohFUk828SBpK+rvclzXsLn1rfHkE client/keystore.go:541
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:56:03 +0000 UTC". client/keystore.go:280
DEBU [KEYAGENT]  Deleting obsolete stored key with index {ProxyHost:tp Username:requester ClusterName:old}. client/keyagent.go:459
INFO [KEYAGENT]  Loading SSH key for user "requester" and cluster "old". client/keyagent.go:179
INFO [CLIENT]    Connecting proxy=tp:3023 login="-teleport-nologin-539c9470-e9f9-4258-90d4-e2d9e9744171" client/api.go:2056
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAg+L/DQFU3O5Pi9/96H1V7YJRhX5gdngfSI0nHrHuPPqgAAAADAQABAAABAQDz0p09UKtiA+3BwoU5CY6kbTMkke2yDQmTIWSdjeMqK2A3FPMSAxaaXhujtXqTLOQrAXLpWuFbkTAJ5KBDmjIyiGEXefum74xPELLG8yvTUTzBQoFbU2QLI2ZlFqNiUQwSKJdQQ1rdr6gu7RTlowcYAaJCFT69EDUJuiqg2IlnrxjY0kYqktp/xZt6glTwd9w+/J/+DOpddEj61TPUoptgqE+hcvlpwrahH8zoInO2MAXjVCCLSBiGnLuS5+iaVaEWF75U8hOyCcQwq6Ps3rjriEphhRA//BcM9GxzcBmlDzARoOCVLa24nUrb4FuFirP2erGDH8Il1ie0LXjA3e2VAAAAAAAAAAAAAAACAAAAAAAAALcAAAAoM2U3NDc3ODYtMGZhMC00NjhjLTg1YWYtMjEzMjFjMzMyZjg0Lm9sZAAAACQzZTc0Nzc4Ni0wZmEwLTQ2OGMtODVhZi0yMTMyMWMzMzJmODQAAAAJbG9jYWxob3N0AAAACTEyNy4wLjAuMQAAAAM6OjEAAAAMZWExYzNmMDMxNjMzAAAAAnRwAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAYZKrJ///////////AAAAAAAAAEMAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAHAAAAA29sZAAAAA94LXRlbGVwb3J0LXJvbGUAAAAJAAAABVByb3h5AAAAAAAAARcAAAAHc3NoLXJzYQAAAAMBAAEAAAEBAN2N6P0+1rc0Cl3cEOVf5ZFaTJmpdilQe1puuGpTDleLlovWLETH1pbWqprgNNxu72zMrGPrPaRCIxY9lIR/ooWAQGtyaty0QBUpCp5S6AHaoz+T2iDhiUGtPPTOVwc+tChGXQF8B2UedrxRBV3Lgj8mgvRbWm1QDw0OsfrKxgS97FWYjFEjJQQapQQtc2VJW+MQ6NBfbIaOdD97EEcSmYljQr2BX4corK0ZZQClRzJs5jgczU9itrXhacxdKyjSXJOJ+eQx9+QM7hYuxbLoJ6yB4YtR622CnPgcC1BuaFN+v/2K+5X41tQVj2j4N9Fh0wmdPeYMlyLgDlWlamMvHSUAAAEUAAAADHJzYS1zaGEyLTUxMgAAAQCs5uvIdKM1eFP+FqsCjWwP6vZDiypW70UKezITPZDDU5MnK3jB4hQnXNXkggV7corSC/csz1NbNuU9iDKx51hTp6Pha7ICRXx+Qobc9Kx1kIC5smUHpBpdgLSQr7NcRWjPdJ6iuQhJJh9NhORReBEhx7SiX9lB4J3n7YJtAjYAylqZSiCGzkGvU3c8DFfuzBOGnAdaSUGTBSMSpwSw0+nb0NdzWUxv3L2MSvX+78APxsmhyTHEF1zv7KsQrdFrgsV4QjzicCvp7q8O+tPvjBJqw5fkO0GQzZ1TeaV24uigIgF/0dhPCH0Vd2oJQ7hM/rPenuKU9A0Qt8LGBnH2PnTl\n." client/keyagent.go:337
DEBU [KEYAGENT]  Validated host tp:3023. client/keyagent.go:343
INFO [CLIENT]    Successful auth with proxy tp:3023. client/api.go:2064
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [KEYAGENT]  Adding CA key for old client/keyagent.go:301
DEBU [KEYSTORE]  Adding known host old with proxy tp and key: SHA256:6/pUEbbHF4RrTyvohFUk828SBpK+rvclzXsLn1rfHkE client/keystore.go:541
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
INFO [CLIENT]    Connecting proxy=tp:3023 login="-teleport-nologin-539c9470-e9f9-4258-90d4-e2d9e9744171" client/api.go:2056
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAg+L/DQFU3O5Pi9/96H1V7YJRhX5gdngfSI0nHrHuPPqgAAAADAQABAAABAQDz0p09UKtiA+3BwoU5CY6kbTMkke2yDQmTIWSdjeMqK2A3FPMSAxaaXhujtXqTLOQrAXLpWuFbkTAJ5KBDmjIyiGEXefum74xPELLG8yvTUTzBQoFbU2QLI2ZlFqNiUQwSKJdQQ1rdr6gu7RTlowcYAaJCFT69EDUJuiqg2IlnrxjY0kYqktp/xZt6glTwd9w+/J/+DOpddEj61TPUoptgqE+hcvlpwrahH8zoInO2MAXjVCCLSBiGnLuS5+iaVaEWF75U8hOyCcQwq6Ps3rjriEphhRA//BcM9GxzcBmlDzARoOCVLa24nUrb4FuFirP2erGDH8Il1ie0LXjA3e2VAAAAAAAAAAAAAAACAAAAAAAAALcAAAAoM2U3NDc3ODYtMGZhMC00NjhjLTg1YWYtMjEzMjFjMzMyZjg0Lm9sZAAAACQzZTc0Nzc4Ni0wZmEwLTQ2OGMtODVhZi0yMTMyMWMzMzJmODQAAAAJbG9jYWxob3N0AAAACTEyNy4wLjAuMQAAAAM6OjEAAAAMZWExYzNmMDMxNjMzAAAAAnRwAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAYZKrJ///////////AAAAAAAAAEMAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAHAAAAA29sZAAAAA94LXRlbGVwb3J0LXJvbGUAAAAJAAAABVByb3h5AAAAAAAAARcAAAAHc3NoLXJzYQAAAAMBAAEAAAEBAN2N6P0+1rc0Cl3cEOVf5ZFaTJmpdilQe1puuGpTDleLlovWLETH1pbWqprgNNxu72zMrGPrPaRCIxY9lIR/ooWAQGtyaty0QBUpCp5S6AHaoz+T2iDhiUGtPPTOVwc+tChGXQF8B2UedrxRBV3Lgj8mgvRbWm1QDw0OsfrKxgS97FWYjFEjJQQapQQtc2VJW+MQ6NBfbIaOdD97EEcSmYljQr2BX4corK0ZZQClRzJs5jgczU9itrXhacxdKyjSXJOJ+eQx9+QM7hYuxbLoJ6yB4YtR622CnPgcC1BuaFN+v/2K+5X41tQVj2j4N9Fh0wmdPeYMlyLgDlWlamMvHSUAAAEUAAAADHJzYS1zaGEyLTUxMgAAAQCs5uvIdKM1eFP+FqsCjWwP6vZDiypW70UKezITPZDDU5MnK3jB4hQnXNXkggV7corSC/csz1NbNuU9iDKx51hTp6Pha7ICRXx+Qobc9Kx1kIC5smUHpBpdgLSQr7NcRWjPdJ6iuQhJJh9NhORReBEhx7SiX9lB4J3n7YJtAjYAylqZSiCGzkGvU3c8DFfuzBOGnAdaSUGTBSMSpwSw0+nb0NdzWUxv3L2MSvX+78APxsmhyTHEF1zv7KsQrdFrgsV4QjzicCvp7q8O+tPvjBJqw5fkO0GQzZ1TeaV24uigIgF/0dhPCH0Vd2oJQ7hM/rPenuKU9A0Qt8LGBnH2PnTl\n." client/keyagent.go:337
DEBU [KEYAGENT]  Validated host tp:3023. client/keyagent.go:343
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
INFO [CLIENT]    Successful auth with proxy tp:3023. client/api.go:2064
DEBU [CLIENT]    Found clusters: [{"name":"old","lastconnected":"2021-11-15T18:59:49.3860081Z","status":"online"}] client/client.go:109
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [TSH]       Disabling exec plugin mode for kubeconfig because this Teleport cluster has no Kubernetes clusters. tsh/kube.go:333
INFO [CLIENT]    Connecting proxy=tp:3023 login="-teleport-nologin-539c9470-e9f9-4258-90d4-e2d9e9744171" client/api.go:2056
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAg+L/DQFU3O5Pi9/96H1V7YJRhX5gdngfSI0nHrHuPPqgAAAADAQABAAABAQDz0p09UKtiA+3BwoU5CY6kbTMkke2yDQmTIWSdjeMqK2A3FPMSAxaaXhujtXqTLOQrAXLpWuFbkTAJ5KBDmjIyiGEXefum74xPELLG8yvTUTzBQoFbU2QLI2ZlFqNiUQwSKJdQQ1rdr6gu7RTlowcYAaJCFT69EDUJuiqg2IlnrxjY0kYqktp/xZt6glTwd9w+/J/+DOpddEj61TPUoptgqE+hcvlpwrahH8zoInO2MAXjVCCLSBiGnLuS5+iaVaEWF75U8hOyCcQwq6Ps3rjriEphhRA//BcM9GxzcBmlDzARoOCVLa24nUrb4FuFirP2erGDH8Il1ie0LXjA3e2VAAAAAAAAAAAAAAACAAAAAAAAALcAAAAoM2U3NDc3ODYtMGZhMC00NjhjLTg1YWYtMjEzMjFjMzMyZjg0Lm9sZAAAACQzZTc0Nzc4Ni0wZmEwLTQ2OGMtODVhZi0yMTMyMWMzMzJmODQAAAAJbG9jYWxob3N0AAAACTEyNy4wLjAuMQAAAAM6OjEAAAAMZWExYzNmMDMxNjMzAAAAAnRwAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAYZKrJ///////////AAAAAAAAAEMAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAHAAAAA29sZAAAAA94LXRlbGVwb3J0LXJvbGUAAAAJAAAABVByb3h5AAAAAAAAARcAAAAHc3NoLXJzYQAAAAMBAAEAAAEBAN2N6P0+1rc0Cl3cEOVf5ZFaTJmpdilQe1puuGpTDleLlovWLETH1pbWqprgNNxu72zMrGPrPaRCIxY9lIR/ooWAQGtyaty0QBUpCp5S6AHaoz+T2iDhiUGtPPTOVwc+tChGXQF8B2UedrxRBV3Lgj8mgvRbWm1QDw0OsfrKxgS97FWYjFEjJQQapQQtc2VJW+MQ6NBfbIaOdD97EEcSmYljQr2BX4corK0ZZQClRzJs5jgczU9itrXhacxdKyjSXJOJ+eQx9+QM7hYuxbLoJ6yB4YtR622CnPgcC1BuaFN+v/2K+5X41tQVj2j4N9Fh0wmdPeYMlyLgDlWlamMvHSUAAAEUAAAADHJzYS1zaGEyLTUxMgAAAQCs5uvIdKM1eFP+FqsCjWwP6vZDiypW70UKezITPZDDU5MnK3jB4hQnXNXkggV7corSC/csz1NbNuU9iDKx51hTp6Pha7ICRXx+Qobc9Kx1kIC5smUHpBpdgLSQr7NcRWjPdJ6iuQhJJh9NhORReBEhx7SiX9lB4J3n7YJtAjYAylqZSiCGzkGvU3c8DFfuzBOGnAdaSUGTBSMSpwSw0+nb0NdzWUxv3L2MSvX+78APxsmhyTHEF1zv7KsQrdFrgsV4QjzicCvp7q8O+tPvjBJqw5fkO0GQzZ1TeaV24uigIgF/0dhPCH0Vd2oJQ7hM/rPenuKU9A0Qt8LGBnH2PnTl\n." client/keyagent.go:337
DEBU [KEYAGENT]  Validated host tp:3023. client/keyagent.go:343
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
INFO [CLIENT]    Successful auth with proxy tp:3023. client/api.go:2064
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779

Creating request...
INFO [CLIENT]    Connecting proxy=tp:3023 login="-teleport-nologin-539c9470-e9f9-4258-90d4-e2d9e9744171" client/api.go:2056
INFO [CLIENT]    Connecting proxy=tp:3023 login="-teleport-nologin-539c9470-e9f9-4258-90d4-e2d9e9744171" client/api.go:2056
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAg+L/DQFU3O5Pi9/96H1V7YJRhX5gdngfSI0nHrHuPPqgAAAADAQABAAABAQDz0p09UKtiA+3BwoU5CY6kbTMkke2yDQmTIWSdjeMqK2A3FPMSAxaaXhujtXqTLOQrAXLpWuFbkTAJ5KBDmjIyiGEXefum74xPELLG8yvTUTzBQoFbU2QLI2ZlFqNiUQwSKJdQQ1rdr6gu7RTlowcYAaJCFT69EDUJuiqg2IlnrxjY0kYqktp/xZt6glTwd9w+/J/+DOpddEj61TPUoptgqE+hcvlpwrahH8zoInO2MAXjVCCLSBiGnLuS5+iaVaEWF75U8hOyCcQwq6Ps3rjriEphhRA//BcM9GxzcBmlDzARoOCVLa24nUrb4FuFirP2erGDH8Il1ie0LXjA3e2VAAAAAAAAAAAAAAACAAAAAAAAALcAAAAoM2U3NDc3ODYtMGZhMC00NjhjLTg1YWYtMjEzMjFjMzMyZjg0Lm9sZAAAACQzZTc0Nzc4Ni0wZmEwLTQ2OGMtODVhZi0yMTMyMWMzMzJmODQAAAAJbG9jYWxob3N0AAAACTEyNy4wLjAuMQAAAAM6OjEAAAAMZWExYzNmMDMxNjMzAAAAAnRwAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAYZKrJ///////////AAAAAAAAAEMAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAHAAAAA29sZAAAAA94LXRlbGVwb3J0LXJvbGUAAAAJAAAABVByb3h5AAAAAAAAARcAAAAHc3NoLXJzYQAAAAMBAAEAAAEBAN2N6P0+1rc0Cl3cEOVf5ZFaTJmpdilQe1puuGpTDleLlovWLETH1pbWqprgNNxu72zMrGPrPaRCIxY9lIR/ooWAQGtyaty0QBUpCp5S6AHaoz+T2iDhiUGtPPTOVwc+tChGXQF8B2UedrxRBV3Lgj8mgvRbWm1QDw0OsfrKxgS97FWYjFEjJQQapQQtc2VJW+MQ6NBfbIaOdD97EEcSmYljQr2BX4corK0ZZQClRzJs5jgczU9itrXhacxdKyjSXJOJ+eQx9+QM7hYuxbLoJ6yB4YtR622CnPgcC1BuaFN+v/2K+5X41tQVj2j4N9Fh0wmdPeYMlyLgDlWlamMvHSUAAAEUAAAADHJzYS1zaGEyLTUxMgAAAQCs5uvIdKM1eFP+FqsCjWwP6vZDiypW70UKezITPZDDU5MnK3jB4hQnXNXkggV7corSC/csz1NbNuU9iDKx51hTp6Pha7ICRXx+Qobc9Kx1kIC5smUHpBpdgLSQr7NcRWjPdJ6iuQhJJh9NhORReBEhx7SiX9lB4J3n7YJtAjYAylqZSiCGzkGvU3c8DFfuzBOGnAdaSUGTBSMSpwSw0+nb0NdzWUxv3L2MSvX+78APxsmhyTHEF1zv7KsQrdFrgsV4QjzicCvp7q8O+tPvjBJqw5fkO0GQzZ1TeaV24uigIgF/0dhPCH0Vd2oJQ7hM/rPenuKU9A0Qt8LGBnH2PnTl\n." client/keyagent.go:337
DEBU [KEYAGENT]  Validated host tp:3023. client/keyagent.go:343
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAg+L/DQFU3O5Pi9/96H1V7YJRhX5gdngfSI0nHrHuPPqgAAAADAQABAAABAQDz0p09UKtiA+3BwoU5CY6kbTMkke2yDQmTIWSdjeMqK2A3FPMSAxaaXhujtXqTLOQrAXLpWuFbkTAJ5KBDmjIyiGEXefum74xPELLG8yvTUTzBQoFbU2QLI2ZlFqNiUQwSKJdQQ1rdr6gu7RTlowcYAaJCFT69EDUJuiqg2IlnrxjY0kYqktp/xZt6glTwd9w+/J/+DOpddEj61TPUoptgqE+hcvlpwrahH8zoInO2MAXjVCCLSBiGnLuS5+iaVaEWF75U8hOyCcQwq6Ps3rjriEphhRA//BcM9GxzcBmlDzARoOCVLa24nUrb4FuFirP2erGDH8Il1ie0LXjA3e2VAAAAAAAAAAAAAAACAAAAAAAAALcAAAAoM2U3NDc3ODYtMGZhMC00NjhjLTg1YWYtMjEzMjFjMzMyZjg0Lm9sZAAAACQzZTc0Nzc4Ni0wZmEwLTQ2OGMtODVhZi0yMTMyMWMzMzJmODQAAAAJbG9jYWxob3N0AAAACTEyNy4wLjAuMQAAAAM6OjEAAAAMZWExYzNmMDMxNjMzAAAAAnRwAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAYZKrJ///////////AAAAAAAAAEMAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAHAAAAA29sZAAAAA94LXRlbGVwb3J0LXJvbGUAAAAJAAAABVByb3h5AAAAAAAAARcAAAAHc3NoLXJzYQAAAAMBAAEAAAEBAN2N6P0+1rc0Cl3cEOVf5ZFaTJmpdilQe1puuGpTDleLlovWLETH1pbWqprgNNxu72zMrGPrPaRCIxY9lIR/ooWAQGtyaty0QBUpCp5S6AHaoz+T2iDhiUGtPPTOVwc+tChGXQF8B2UedrxRBV3Lgj8mgvRbWm1QDw0OsfrKxgS97FWYjFEjJQQapQQtc2VJW+MQ6NBfbIaOdD97EEcSmYljQr2BX4corK0ZZQClRzJs5jgczU9itrXhacxdKyjSXJOJ+eQx9+QM7hYuxbLoJ6yB4YtR622CnPgcC1BuaFN+v/2K+5X41tQVj2j4N9Fh0wmdPeYMlyLgDlWlamMvHSUAAAEUAAAADHJzYS1zaGEyLTUxMgAAAQCs5uvIdKM1eFP+FqsCjWwP6vZDiypW70UKezITPZDDU5MnK3jB4hQnXNXkggV7corSC/csz1NbNuU9iDKx51hTp6Pha7ICRXx+Qobc9Kx1kIC5smUHpBpdgLSQr7NcRWjPdJ6iuQhJJh9NhORReBEhx7SiX9lB4J3n7YJtAjYAylqZSiCGzkGvU3c8DFfuzBOGnAdaSUGTBSMSpwSw0+nb0NdzWUxv3L2MSvX+78APxsmhyTHEF1zv7KsQrdFrgsV4QjzicCvp7q8O+tPvjBJqw5fkO0GQzZ1TeaV24uigIgF/0dhPCH0Vd2oJQ7hM/rPenuKU9A0Qt8LGBnH2PnTl\n." client/keyagent.go:337
DEBU [KEYAGENT]  Validated host tp:3023. client/keyagent.go:343
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
INFO [CLIENT]    Successful auth with proxy tp:3023. client/api.go:2064
INFO [CLIENT]    Successful auth with proxy tp:3023. client/api.go:2064
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
INFO [CLIENT]    Connecting proxy=tp:3023 login="-teleport-nologin-539c9470-e9f9-4258-90d4-e2d9e9744171" client/api.go:2056
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAg+L/DQFU3O5Pi9/96H1V7YJRhX5gdngfSI0nHrHuPPqgAAAADAQABAAABAQDz0p09UKtiA+3BwoU5CY6kbTMkke2yDQmTIWSdjeMqK2A3FPMSAxaaXhujtXqTLOQrAXLpWuFbkTAJ5KBDmjIyiGEXefum74xPELLG8yvTUTzBQoFbU2QLI2ZlFqNiUQwSKJdQQ1rdr6gu7RTlowcYAaJCFT69EDUJuiqg2IlnrxjY0kYqktp/xZt6glTwd9w+/J/+DOpddEj61TPUoptgqE+hcvlpwrahH8zoInO2MAXjVCCLSBiGnLuS5+iaVaEWF75U8hOyCcQwq6Ps3rjriEphhRA//BcM9GxzcBmlDzARoOCVLa24nUrb4FuFirP2erGDH8Il1ie0LXjA3e2VAAAAAAAAAAAAAAACAAAAAAAAALcAAAAoM2U3NDc3ODYtMGZhMC00NjhjLTg1YWYtMjEzMjFjMzMyZjg0Lm9sZAAAACQzZTc0Nzc4Ni0wZmEwLTQ2OGMtODVhZi0yMTMyMWMzMzJmODQAAAAJbG9jYWxob3N0AAAACTEyNy4wLjAuMQAAAAM6OjEAAAAMZWExYzNmMDMxNjMzAAAAAnRwAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAYZKrJ///////////AAAAAAAAAEMAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAHAAAAA29sZAAAAA94LXRlbGVwb3J0LXJvbGUAAAAJAAAABVByb3h5AAAAAAAAARcAAAAHc3NoLXJzYQAAAAMBAAEAAAEBAN2N6P0+1rc0Cl3cEOVf5ZFaTJmpdilQe1puuGpTDleLlovWLETH1pbWqprgNNxu72zMrGPrPaRCIxY9lIR/ooWAQGtyaty0QBUpCp5S6AHaoz+T2iDhiUGtPPTOVwc+tChGXQF8B2UedrxRBV3Lgj8mgvRbWm1QDw0OsfrKxgS97FWYjFEjJQQapQQtc2VJW+MQ6NBfbIaOdD97EEcSmYljQr2BX4corK0ZZQClRzJs5jgczU9itrXhacxdKyjSXJOJ+eQx9+QM7hYuxbLoJ6yB4YtR622CnPgcC1BuaFN+v/2K+5X41tQVj2j4N9Fh0wmdPeYMlyLgDlWlamMvHSUAAAEUAAAADHJzYS1zaGEyLTUxMgAAAQCs5uvIdKM1eFP+FqsCjWwP6vZDiypW70UKezITPZDDU5MnK3jB4hQnXNXkggV7corSC/csz1NbNuU9iDKx51hTp6Pha7ICRXx+Qobc9Kx1kIC5smUHpBpdgLSQr7NcRWjPdJ6iuQhJJh9NhORReBEhx7SiX9lB4J3n7YJtAjYAylqZSiCGzkGvU3c8DFfuzBOGnAdaSUGTBSMSpwSw0+nb0NdzWUxv3L2MSvX+78APxsmhyTHEF1zv7KsQrdFrgsV4QjzicCvp7q8O+tPvjBJqw5fkO0GQzZ1TeaV24uigIgF/0dhPCH0Vd2oJQ7hM/rPenuKU9A0Qt8LGBnH2PnTl\n." client/keyagent.go:337
DEBU [KEYAGENT]  Validated host tp:3023. client/keyagent.go:343
INFO [CLIENT]    no host login given. defaulting to root client/api.go:1042
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:2795
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Reading certificates from path "/root/.tsh/keys/tp/requester-ssh/old-cert.pub". client/keystore.go:303
INFO [KEYAGENT]  Loading SSH key for user "requester" and cluster "old". client/keyagent.go:179
INFO [CLIENT]    Connecting proxy=tp:3023 login="-teleport-nologin-539c9470-e9f9-4258-90d4-e2d9e9744171" client/api.go:2056
INFO [CLIENT]    Successful auth with proxy tp:3023. client/api.go:2064
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAg+L/DQFU3O5Pi9/96H1V7YJRhX5gdngfSI0nHrHuPPqgAAAADAQABAAABAQDz0p09UKtiA+3BwoU5CY6kbTMkke2yDQmTIWSdjeMqK2A3FPMSAxaaXhujtXqTLOQrAXLpWuFbkTAJ5KBDmjIyiGEXefum74xPELLG8yvTUTzBQoFbU2QLI2ZlFqNiUQwSKJdQQ1rdr6gu7RTlowcYAaJCFT69EDUJuiqg2IlnrxjY0kYqktp/xZt6glTwd9w+/J/+DOpddEj61TPUoptgqE+hcvlpwrahH8zoInO2MAXjVCCLSBiGnLuS5+iaVaEWF75U8hOyCcQwq6Ps3rjriEphhRA//BcM9GxzcBmlDzARoOCVLa24nUrb4FuFirP2erGDH8Il1ie0LXjA3e2VAAAAAAAAAAAAAAACAAAAAAAAALcAAAAoM2U3NDc3ODYtMGZhMC00NjhjLTg1YWYtMjEzMjFjMzMyZjg0Lm9sZAAAACQzZTc0Nzc4Ni0wZmEwLTQ2OGMtODVhZi0yMTMyMWMzMzJmODQAAAAJbG9jYWxob3N0AAAACTEyNy4wLjAuMQAAAAM6OjEAAAAMZWExYzNmMDMxNjMzAAAAAnRwAAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9jYWwAAAAAYZKrJ///////////AAAAAAAAAEMAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAHAAAAA29sZAAAAA94LXRlbGVwb3J0LXJvbGUAAAAJAAAABVByb3h5AAAAAAAAARcAAAAHc3NoLXJzYQAAAAMBAAEAAAEBAN2N6P0+1rc0Cl3cEOVf5ZFaTJmpdilQe1puuGpTDleLlovWLETH1pbWqprgNNxu72zMrGPrPaRCIxY9lIR/ooWAQGtyaty0QBUpCp5S6AHaoz+T2iDhiUGtPPTOVwc+tChGXQF8B2UedrxRBV3Lgj8mgvRbWm1QDw0OsfrKxgS97FWYjFEjJQQapQQtc2VJW+MQ6NBfbIaOdD97EEcSmYljQr2BX4corK0ZZQClRzJs5jgczU9itrXhacxdKyjSXJOJ+eQx9+QM7hYuxbLoJ6yB4YtR622CnPgcC1BuaFN+v/2K+5X41tQVj2j4N9Fh0wmdPeYMlyLgDlWlamMvHSUAAAEUAAAADHJzYS1zaGEyLTUxMgAAAQCs5uvIdKM1eFP+FqsCjWwP6vZDiypW70UKezITPZDDU5MnK3jB4hQnXNXkggV7corSC/csz1NbNuU9iDKx51hTp6Pha7ICRXx+Qobc9Kx1kIC5smUHpBpdgLSQr7NcRWjPdJ6iuQhJJh9NhORReBEhx7SiX9lB4J3n7YJtAjYAylqZSiCGzkGvU3c8DFfuzBOGnAdaSUGTBSMSpwSw0+nb0NdzWUxv3L2MSvX+78APxsmhyTHEF1zv7KsQrdFrgsV4QjzicCvp7q8O+tPvjBJqw5fkO0GQzZ1TeaV24uigIgF/0dhPCH0Vd2oJQ7hM/rPenuKU9A0Qt8LGBnH2PnTl\n." client/keyagent.go:337
DEBU [KEYAGENT]  Validated host tp:3023. client/keyagent.go:343
DEBU [CLIENT]    Found clusters: [{"name":"old","lastconnected":"2021-11-15T19:00:19.1656044Z","status":"online"}] client/client.go:109
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
INFO [CLIENT]    Successful auth with proxy tp:3023. client/api.go:2064
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/root/.tsh/keys/tp/requester-x509.pem" valid until "2021-11-16 06:59:31 +0000 UTC". client/keystore.go:280
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
INFO [TSH]       Access-request watcher initialized... tsh/tsh.go:2138
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
Request ID: 35949cc2-8dc8-448a-ae32-ba69853f266c
Username:   requester
Roles:      access, admin, auditor, editor
Reason:     "foo"
Reviewers:  [none] (suggested)
Status:     APPROVED

hint: use 'tsh login --request-id=<request-id>' to login with an approved request

Waiting for request approval...
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
DEBU [CLIENT]    Client  is connecting to auth server on cluster "old". client/client.go:779
```

### LINKED ISSUE #9244: tsh will either fail or hang if issuing a request while logged in to a leaf cluster
### Description

**What happened**:

After 928aaf2f91e451f32684fe5d279d39cad9f6d2c6, `tsh` doesn't correctly watch for access request updates by connecting to the root cluster; therefore, when connected to a leaf cluster (after a `tsh login <leafclustername>`), issuing a new request with `tsh request new --roles <rolename>` will either fail with
```
ERROR: access denied to perform action "read" on "access_request"
```
if the logged-in user doesn't have read permissions for access requests on the leaf cluster, or it will hang at
```
Waiting for request approval...
```

**What you expected to happen**:
A user with access request permission should be allowed to issue a new request with `tsh` while logged into a leaf cluster.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Ensure you're logged in and that a leaf cluster is selected:
```
% tsh status
> Profile URL:        https://127.0.0.1:3080
  Logged in as:       requesty
  Cluster:            leafcluster
  Roles:              access, requester
  Logins:             requesty
  Kubernetes:         enabled
  Valid until:        2021-12-07 00:05:56 +0100 CET [valid for 11h56m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

% tsh clusters
Cluster Name Status Cluster Type Selected
------------ ------ ------------ --------
rootcluster  online root
leafcluster  online leaf         *
```
2. Issue a new request and see it fail:
```
% tsh request new --roles access
ERROR: access denied to perform action "read" on "access_request"
```
3. Switch back to the root cluster and see the request succeed:
```
% tsh login rootcluster
> Profile URL:        https://127.0.0.1:3080
  Logged in as:       requesty
  Cluster:            rootcluster
  Roles:              access, requester
  Logins:             requesty
  Kubernetes:         enabled
  Valid until:        2021-12-07 00:05:56 +0100 CET [valid for 11h53m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

% tsh requests new --roles access
Creating request...
Request ID: 32fc1de6-acdd-46c2-8fd3-a3d341247534
Username:   requesty
Roles:      access
Reason:     [none]
Reviewers:  [none] (suggested)
Status:     PENDING

hint: use 'tsh login --request-id=<request-id>' to login with an approved request

Waiting for request approval...
```

(view and approve the request)
```
# tctl requests ls
Token                                Requestor Metadata     Created At (UTC)    Status   Request Reason Resolve Reason
------------------------------------ --------- ------------ ------------------- -------- -------------- --------------
32fc1de6-acdd-46c2-8fd3-a3d341247534 requesty  roles=access 06 Dec 21 11:12 UTC PENDING
# tctl requests approve 32fc1de6-acdd-46c2-8fd3-a3d341247534
```
(back to the first session)
```

Approval received, getting updated certificates...

> Profile URL:        https://127.0.0.1:3080
  Logged in as:       requesty
  Cluster:            rootcluster
  Roles:              access, requester
  Logins:             requesty
  Kubernetes:         enabled
  Valid until:        2021-12-07 00:05:56 +0100 CET [valid for 11h51m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

```

### Server Details
- Teleport version (run `teleport version`): latest `master` (675fb3dc09f1e95b58dedb19021599ec84bb1b22 at time of writing)
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:
`rootcluster` and `leafcluster` are respectively the root and a leaf cluster in a trusted clusters setup, `requesty` is a user on `rootcluster` that belongs to the `requester` role, which is allowed to request the `access` role. Everything else is left at default settings.

### Client Details
- Tsh version (`tsh version`): latest `master`, but should be reproducible in every version after the commit mentioned above
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

### PR DESCRIPTION
**Pull request by espadolini**
Right now `tsh` fires up a watcher to wait for the access request to be resolved and then creates the request; however it doesn't wait for the watcher to be ready, and so it's possible to miss the resolution of the request (be it approval, denial or removal) and we get a hang.

This makes it so that we wait for the watcher to be ready before proceeding with the request creation. In addition, we create the watcher on the root cluster rather than whatever cluster we're connected to.

Closes #9003 and #9244.

### CODE REVIEW

**Comment by espadolini** [comment]
How should I go about adding a test for this? #9003 has some instructions on how to replicate it, but it could also be tested by artificially increasing the time it takes for the watcher to be ready in the code.

**Comment by russjones** [comment]
@fspmarshall Any suggestions for @espadolini on how to write tests for this?

**Comment by espadolini** [comment]
This also fixes #9244

**Comment by espadolini** [comment]
After some minor refactoring, the watcher now waits for access request updates on the root cluster, rather than whatever cluster we're currently connected to.

Closes #9244.

File: tool/tsh/tsh_test.go [hunk 1]
```diff
@@ -449,6 +451,168 @@ func TestMakeClient(t *testing.T) {
...
+	go func() {
+		errChan <- Run([]string{
+			"request",
+			"new",
+			"--insecure",
+			"--debug",
+			"--proxy", rootProxyAddr.String(),
+			"--roles=access",
+		})
+	}()
```
Comment (espadolini) [inline tool/tsh/tsh_test.go:559]: Is it ok to have this potentially hang? The test will `Fatal` after a timeout, and it's not parallel (we muck around with `~/.tsh` anyway).

**Comment by fspmarshall** [comment]
> I'm still not sure how to make a specific test for the spurious hangs

@espadolini Since this update removes the cause of the spurious hangs, I don't think there is a reasonable way to try to replicate them in a test.  As you said, we cover the codepath, so if a new spurious hang is introduced, hopefully we'll catch it.

File: tool/tsh/tsh_test.go (hunk 1 above)
Comment (fspmarshall) [reply tool/tsh/tsh_test.go:559]: I think its fine.  How about marking it as a duplicate though?  That way if we decide to create a collection of test helpers that fits with this in the future, it will be clear to anyone reading that its worth relocating.

File: tool/tsh/tsh_test.go [hunk 2]
```diff
@@ -449,6 +451,168 @@ func TestMakeClient(t *testing.T) {
...
+
+	select {
+	case err := <-errChan:
+		require.NoError(t, err)
+	case <-time.After(5 * time.Second):
+		t.Fatal("access request wasn't resolved after 30s")
+	}
+}
+
+// from integration/integration_test.go
```
[the remark this answers is not in the document]
Comment (fspmarshall) [reply tool/tsh/tsh_test.go:592]: I think its fine.  How about marking it as a duplicate though?  That way if we decide to create a collection of test helpers that fits with this in the future, it will be clear to anyone reading that its worth relocating.

File: tool/tsh/tsh_test.go (hunk 1 above)
Comment (fspmarshall) [reply tool/tsh/tsh_test.go:559]: How about a 1-2min timeout?  Just to save us time if this becomes flaky in the future.

**Review by fspmarshall — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
@espadolini Please backport this to `branch/v8` and `branch/v7`. You can create backport PRs now, but don't merge until next week.
