### PR TITLE
Fix panic when fetching user preferences

### LINKED ISSUE #28740: `/v1/webapi/user/preferences` crashes
Expected behavior:

`/v1/webapi/user/preferences` should return user preferences.

Current behavior:

Currently, this endpoint crashes:

```
2023-07-05T17:40:05-04:00 ERRO [PROXY:SER] "proxy2023/07/05 17:40:05 http: panic serving 127.0.0.1:33622: runtime error: invalid memory address or nil pointer dereference\ngoroutine 3573 [running]:\nnet/http.(*conn).serve.func1()\n\t/home/jnyckowski/sdk/go1.21rc2/src/net/http/server.go:1868 +0xb9\npanic({0x653f680?, 0xc5b1ac0?})\n\t/home/jnyckowski/sdk/go1.21rc2/src/runtime/panic.go:920 +0x270\ngithub.com/gravitational/teleport/lib/web.onboardUserPreferencesResponse(...)\n\t/home/jnyckowski/projects/teleport/lib/web/userpreferences.go:123\ngithub.com/gravitational/teleport/lib/web.userPreferencesResponse(...)\n\t/home/jnyckowski/projects/teleport/lib/web/userpreferences.go:102\ngithub.com/gravitational/teleport/lib/web.(*Handler).getUserPreferences(0x0?, {0xc002dcad98?, 0x4157e5?}, 0x10?, {0x616ff00?, 0xc002aa4580?, 0xc002dcae08?}, 0x2c2b6ad?)\n\t/home/jnyckowski/projects/teleport/lib/web/userpreferences.go:60 +0x17e\ngithub.com/gravitational/teleport/lib/web.(*Handler).bindDefaultEndpoints.(*Handler).WithAuth.func112({0x8964670, 0xc002bec0c0}, 0x0?, {0x0, 0x0, 0x0})\n\t/home/jnyckowski/projects/teleport/lib/web/apiserver.go:3705 +0xd7\ngithub.com/gravitational/teleport/lib/web.(*Handler).bindDefaultEndpoints.(*Handler).WithAuth.MakeHandler.MakeHandlerWithErrorWriter.func229({0x8964670, 0xc002bec0c0}, 0xc004ca6c30?, {0x0, 0x0, 0x0})\n\t/home/jnyckowski/projects/teleport/lib/httplib/httplib.go:117 +0x98\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc002fbc018, {0x8964670, 0xc002bec0c0}, 0xc001e1fb00)\n\t/home/jnyckowski/go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 +0x82b\ngithub.com/gravitational/teleport/lib/web.NewHandler.func1.StripPrefix.func1({0x8964670, 0xc002bec0c0}, 0xc001e1fa00)\n\t/home/jnyckowski/sdk/go1.21rc2/src/net/http/server.go:2179 +0x262\nnet/http.HandlerFunc.ServeHTTP(0x412f45?, {0x8964670?, 0xc002bec0c0?}, 0xc003381a01?)\n\t/home/jnyckowski/sdk/go1.21rc2/src/net/http/server.go:2136 +0x29\ngithub.com/gravitational/teleport/lib/web.NewHandler.func1({0x8964670, 0xc002bec0c0}, 0xc001e1fa00)\n\t/home/jnyckowski/projects/teleport/lib/web/apiserver.go:434 +0x782\nnet/http.HandlerFunc.ServeHTTP(0x64de7c0?, {0x8964670?, 0xc002bec0c0?}, 0x3?)\n\t/home/jnyckowski/sdk/go1.21rc2/src/net/http/server.go:2136 +0x29\ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc002fbc018, {0x8964670, 0xc002bec0c0}, 0xc001e1fa00)\n\t/home/jnyckowski/go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:460 +0x642\ngithub.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP(0xc002ccbe20, {0x8964670, 0xc002bec0c0}, 0xc001e1fa00)\n\t/home/jnyckowski/projects/teleport/lib/web/apiserver.go:295 +0xfd\ngithub.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP(0xc0025a0680, {0x8964670, 0xc002bec0c0}, 0xc001e1fa00)\n\t/home/jnyckowski/go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 +0x1c2\ngithub.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP(0xc002167e00, {0x8964670, 0xc002bec0c0}, 0xc002447470?)\n\t/home/jnyckowski/go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 +0x2fb\ngithub.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1({0x8964670, 0xc002bec0c0}, 0xc001e1fa00)\n\t/home/jnyckowski/projects/teleport/lib/httplib/httplib.go:94 +0x1a5\nnet/http.HandlerFunc.ServeHTTP(0x896ed70?, {0x8964670?, 0xc002bec0c0?}, 0x88ccf38?)\n\t/home/jnyckowski/sdk/go1.21rc2/src/net/http/server.go:2136 +0x29\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc0029555c0, {0x894c8d0?, 0xc0003b90a0}, 0xc001e1f900)\n\t/home/jnyckowski/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212 +0x1204\nnet/http.serverHandler.ServeHTTP({0xc004439da0?}, {0x894c8d0?, 0xc0003b90a0?}, 0x6?)\n\t/home/jnyckowski/sdk/go1.21rc2/src/net/http/server.go:2938 +0x8e\nnet/http.(*conn).serve(0xc003b2b0e0, {0x896ed70, 0xc004439d40})\n\t/home/jnyckowski/sdk/go1.21rc2/src/net/http/server.go:2009 +0x5f4\ncreated by net/http.(*Server).Serve in goroutine 1175\n\t/home/jnyckowski/sdk/go1.21rc2/src/net/http/server.go:3086 +0x5cb\n" pid:144463.1 utils/cli.go:425
```

It looks like this https://github.com/gravitational/teleport/pull/28530 change can be related.

Bug details:
- Teleport version `master`
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by jakule**
Closes https://github.com/gravitational/teleport/issues/28740

### CODE REVIEW

**Review by michellescripts — APPROVED** [review]

File: lib/services/local/userpreferences.go [hunk 1]
```diff
@@ -142,36 +146,71 @@ func createBackendItem(username string, preferences *userpreferencesv1.UserPrefe
...
-func mergeOnboardUserPreferences(dest, src *userpreferencesv1.OnboardUserPreferences) {
-	if src.PreferredResources != nil {
-		dest.PreferredResources = src.PreferredResources
+// mergeIfUnset merges the values in src with the values in dst if the values in dst are unset.
+func mergeIfUnset(dst, src any) {
+	if reflect.TypeOf(src) != reflect.TypeOf(dst) {
+		return
+	}
+
+	srcV := reflect.ValueOf(src).Elem()
```
Comment (zmb3) [inline lib/services/local/userpreferences.go:185]: 🙈

Comment (jakule) [reply lib/services/local/userpreferences.go:185]: I know :see_no_evil: But IMO doesn't make sense to have the default values already specified above and keep adding nested ifs to set the same values instead of using reflection here. I was hoping to find something in `proto` package, but `proto.Range()` only iterates over set values, and `proto.Merge()` merges collections, so it won't work here.

Comment (probakowski) [reply lib/services/local/userpreferences.go:199]: But we do want to iterate only over fields that are set in `src`, right? So it seems `Range()` should do the job?. OTOH `Range` is pretty close to reflection either way so.. 🤷

Comment (probakowski) [reply lib/services/local/userpreferences.go:199]: So.. it can be used? AFAICT the flow is as follow:
- find all fields that are set (non-default) in src
- check if field is set in dst
- if not set it to value from src
`Range` can give you the first step, right?

Comment (jakule) [reply lib/services/local/userpreferences.go]: @zmb3 @probakowski I've removed the reflection explicit from our code.

**Review by zmb3 — APPROVED** [review]

File: lib/services/local/userpreferences.go [hunk 2]
```diff
@@ -142,36 +153,34 @@ func createBackendItem(username string, preferences *userpreferencesv1.UserPrefe
 	return item, nil
 }
 
-// mergePreferences merges the values from src into dest.
-func mergePreferences(dest, src *userpreferencesv1.UserPreferences) {
-	if src.Theme != userpreferencesv1.Theme_THEME_UNSPECIFIED {
-		dest.Theme = src.Theme
-	}
+// overwriteValues overwrites the values in dst with the values in src.
+func overwriteValues(dst, src protoreflect.ProtoMessage) error {
```
Comment (tigrato) [inline lib/services/local/userpreferences.go:157]: can you please add a comment mentioning that it only works because proto.range only visits non-nil/non-empty fields? 

It would become clear to anyone using it how it works.

**Review by tigrato — APPROVED** [review]

File: lib/services/local/userpreferences.go (hunk 2 above)
Comment (jakule) [reply lib/services/local/userpreferences.go:159]: Added

**Review by probakowski — APPROVED** [review]
