### PR TITLE
Fix racy X11 forwarding test

### LINKED ISSUE #47756: `TestIntegrations/X11Forwarding` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/11442800048/job/31833983642

#### Relevant snippet

```
==================
WARNING: DATA RACE
Write at 0x00c005069900 by goroutine 56906:
  github.com/gravitational/teleport/integration.testX11Forwarding.func3.3.3.1()
      /__w/teleport/teleport/integration/integration_test.go:4752 +0xa4
  github.com/stretchr/testify/assert.Eventually.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x33

Previous write at 0x00c005069900 by goroutine 56878:
  github.com/gravitational/teleport/integration.testX11Forwarding.func3.3.3.1()
      /__w/teleport/teleport/integration/integration_test.go:4752 +0xa4
  github.com/stretchr/testify/assert.Eventually.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x33

Goroutine 56906 (running) created at:
  github.com/stretchr/testify/assert.Eventually()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x3d5
  github.com/gravitational/teleport/integration.testX11Forwarding.func3.3.3()
      /__w/teleport/teleport/integration/integration_test.go:4749 +0x31e
  github.com/stretchr/testify/assert.EventuallyWithT.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1983 +0xb7

Goroutine 56878 (finished) created at:
  github.com/stretchr/testify/assert.Eventually()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1902 +0x3d5
  github.com/gravitational/teleport/integration.testX11Forwarding.func3.3.3()
      /__w/teleport/teleport/integration/integration_test.go:4749 +0x31e
  github.com/stretchr/testify/assert.EventuallyWithT.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.9.0/assert/assertions.go:1983 +0xb7
==================
```

### PR DESCRIPTION
**Pull request by zmb3**
{require,assert}.Eventually run the passed in func on a new goroutine for each attempt, so it's not safe to write to a shared variable without any synchronization.

Closes #47756

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -4749,15 +4749,15 @@ func testX11Forwarding(t *testing.T, suite *integrationTestSuite) {
 							assert.Eventually(t, func() bool {
 								output, err := os.ReadFile(tmpFile.Name())
 								if err == nil && len(output) != 0 {
-									display = strings.TrimSpace(string(output))
+									display <- strings.TrimSpace(string(output))
```
Comment (zmb3) [inline integration/integration_test.go:4752]: I think a buffer of 1 should be okay, since as soon as this write occurs the entire `require.EventuallyWithT` should complete, but would appreciate more 👀

**Review by Joerger — APPROVED** [review]

**Review by espadolini — APPROVED** [review]
The fact that the `Eventually` functions can overlap in execution is insane, and I'm now worried if there's other tests where we assume they don't. 😰

File: integration/integration_test.go (hunk 1 above)
Comment (espadolini) [reply integration/integration_test.go:4752]: Could make it a non-blocking channel write that just discards the value if there's something in the channel already?

**Comment by zmb3** [comment]
> The fact that the `Eventually` functions can overlap in execution is insane, and I'm now worried if there's other tests where we assume they don't. 😰 

Agreed.
