### PR TITLE
Fix TestConnectorSelection flakiness by refactoring connector selection

### LINKED ISSUE #62895: `TestConnectorSelection` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/21046845633/job/60523314214?pr=62891
- https://github.com/gravitational/teleport/actions/runs/21047469838/job/60526912077?pr=62892

#### Relevant snippet

```
=== FAIL: lib/srv/db/sqlserver TestConnectorSelection/Azure_database_without_AD_configured (0.02s)
    connect_test.go:95: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/db/sqlserver/connect_test.go:95
        	            				/__w/teleport/teleport/lib/srv/db/sqlserver/connect_test.go:137
        	Error:      	"lookup random.database.windows.net on 127.0.0.11:53: no such host" does not contain "unable to open tcp connection with host"
        	Test:       	TestConnectorSelection/Azure_database_without_AD_configured

=== FAIL: lib/srv/db/sqlserver TestConnectorSelection (0.09s)
```

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #62895

Refactored the SQL Server connector code to extract connector selection logic into a separate `selectConnector()` method that can be tested independently without network connections. This eliminates the flakiness caused by DNS resolution and context cancellation races.

### CODE REVIEW

File: lib/srv/db/sqlserver/connect_test.go [hunk 1]
```diff
@@ -40,18 +41,14 @@ import (
...
 func TestConnectorSelection(t *testing.T) {
 	t.Parallel()
-	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
-	defer cancel()
-
-	connector := &connector{
-		DBAuth:   &mockDBAuth{},
-		kerberos: &mockKerberos{},
-	}
+	ctx := context.Background()
```
Comment (zmb3) [inline lib/srv/db/sqlserver/connect_test.go]: Use `t.Context()` here?

File: lib/srv/db/sqlserver/connect.go [hunk 2]
```diff
@@ -55,23 +55,60 @@ type connector struct {
 	DBAuth common.Auth
 
 	kerberos kerberos.ClientProvider
+
+	// Connector creation functions - can be mocked in tests
+	newAzureConnector         func(msdsn.Config) (*mssql.Connector, error)
+	newSecurityTokenConnector func(msdsn.Config, func(context.Context) (string, error)) (*mssql.Connector, error)
```
Comment (codingllama) [inline lib/srv/db/sqlserver/connect.go]: Could we add parameter names here, so it's clearer what the functions do?


```go
	newSecurityTokenConnector func(cfg msdsn.Config, GIVEMEANAME func(ctx context.Context) (GIVEMEANAME string, err error)) (*mssql.Connector, error)
```

**Review by codingllama — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
