### PR TITLE
Provide accurate error to clients trying to join a node in proxy recording mode

### LINKED ISSUE #42346: Misleading error when joining SSH session using Web UI in proxy recording mode
Expected behavior:
Joining an SSH session using the Web UI with the cluster in proxy recording mode should fail with an error that notifies that user that session joining in proxy recording mode is not supported.

Current behavior:
The returned error is `direct dialing to nodes not found in inventory is not supported`.

Bug details:
- Teleport version
v16.0.0-alpha.1
- Recreation steps
- Debug logs

The server ID returned by the forwarding SSH server can't be found by the router as it isn't a registered node, which causes the `direct dialing not supported` error. A check can be added to `lib/web.(Handler).fetchExistingSession` to return an error if the cluster is in proxy recording mode, however the returned error isn't displayed on the Web UI, only `disconnected` is displayed. The error is sent raw over the `AuthenticatedWebSocket` but currently isn't handled. I'm not sure how error messages should be properly displayed before the terminal stream has been created.

### PR DESCRIPTION
**Pull request by Joerger**
This PR introduces the same client-side check for session joining as seen in the [`tsh` client](https://github.com/gravitational/teleport/blob/3da95140e6b2089360858fe3887f8b1fa062e8e9/lib/client/api.go#L2399-L2427).

Note: The best way to handle this would be to remove the client side check (which has 1-2 additional round trips) and instead return an error from the forwarding node. Recent changes made it so that we do reach the forwarding node, but we still fail in odd ways, such as hanging on the terminal size request or the current session ID request. This could be fixed by changing the order or operations to create the session before attempting to make global requests, but such a change it outside the boundaries of this simple fix.

Fixes https://github.com/gravitational/teleport/issues/42346

Manual tests:
- Proxy recording mode:
  - [x] Attempt to join a Teleport Node session from the WebUI, get the `session joining is not supported in proxy recording mode` error. 
  - [x] Attempt to join an OpenSSH Node session from the WebUI, get the `session joining is not supported in proxy recording mode` error. 
- Node recording mode:
  - [x] Attempt to join an OpenSSH Node session from the WebUI, get the `session joining is only supported for Teleport nodes, not OpenSSH nodes` error.

### CODE REVIEW

File: lib/web/apiserver.go [hunk 1]
```diff
@@ -4271,9 +4269,19 @@ func (h *Handler) generateSession(ctx context.Context, req *TerminalRequest, clu
 	}, nil
 }
 
-// fetchExistingSession fetches an active or pending SSH session by the SessionID passed in the TerminalRequest.
-func (h *Handler) fetchExistingSession(ctx context.Context, clt authclient.ClientI, req *TerminalRequest, siteName string) (session.Session, types.SessionTracker, error) {
-	sessionID, err := session.ParseID(req.SessionID.String())
+// fetchJoinSession fetches an active or pending SSH session by the SessionID passed in the TerminalRequest.
+func (h *Handler) fetchJoinSession(ctx context.Context, clt authclient.ClientI, req *TerminalRequest, siteName string) (session.Session, types.SessionTracker, error) {
+	// Session joining is not supported in proxy recording mode
+	if recConfig, err := clt.GetSessionRecordingConfig(ctx); err != nil {
```
Comment (rosstimothy) [inline lib/web/apiserver.go]: Is this available via the proxy cache? Do we need to retrieve this as the user's identity?

**Review by rosstimothy — APPROVED** [review]

**Comment by Joerger** [comment]
@hugoShaka @doggydogworld friendly ping to review

File: lib/web/apiserver.go [hunk 2]
```diff
@@ -4271,9 +4269,19 @@ func (h *Handler) generateSession(ctx context.Context, req *TerminalRequest, clu
...
+// fetchJoinSession fetches an active or pending SSH session by the SessionID passed in the TerminalRequest.
+func (h *Handler) fetchJoinSession(ctx context.Context, clt authclient.ClientI, req *TerminalRequest, siteName string) (session.Session, types.SessionTracker, error) {
+	// Session joining is not supported in proxy recording mode
+	if recConfig, err := h.auth.accessPoint.GetSessionRecordingConfig(ctx); err != nil {
+		// If the user can't see the recording mode, just let them try joining below
+		if !trace.IsAccessDenied(err) {
+			return session.Session{}, nil, trace.Wrap(err)
+		}
+	} else if services.IsRecordAtProxy(recConfig.GetMode()) {
+		return session.Session{}, nil, trace.BadParameter("session joining is not supported in proxy recording mode")
```
Comment (hugoShaka) [inline lib/web/apiserver.go]: non-blocking:

Should we link to the recording modes docs? I fear that most users don't know what recording modes are. Also the users seeing this error might not be admins and might not understand that they cannot do anything about this.

```suggestion
		return session.Session{}, nil, trace.BadParameter("session joining is not supported in proxy recording mode. If you are a Teleport administrator, you can learn more about recording modes at: https://goteleport.com/docs/reference/architecture/session-recording")
```

File: lib/web/apiserver.go [hunk 3]
```diff
@@ -4284,6 +4292,10 @@ func (h *Handler) fetchExistingSession(ctx context.Context, clt authclient.Clien
 		return session.Session{}, nil, trace.Wrap(err)
 	}
 
+	if types.IsOpenSSHNodeSubKind(tracker.GetTargetSubKind()) {
+		return session.Session{}, nil, trace.BadParameter("session joining is only supported for Teleport nodes, not OpenSSH nodes")
```
Comment (hugoShaka) [inline lib/web/apiserver.go]: nit: openssh nodes can be considered Teleport nodes, this can be ambiguous

```suggestion
		return session.Session{}, nil, trace.BadParameter("session joining is only supported for nodes which are Teleport agents, not OpenSSH nodes")
```

**Review by hugoShaka — APPROVED** [review]
