### PR TITLE
Fix MFA always required for file transfers

### LINKED ISSUE #51694: File transfers in the WebUI always think MFA is required
Caused by https://github.com/gravitational/teleport/pull/49794

This [segment of code](https://github.com/gravitational/teleport/blob/e103a1fd0f718323ad1df74ee3a9d6e6b293e324/web/packages/teleport/src/lib/useMfa.ts#L62-L68) does not function correctly.

### PR DESCRIPTION
**Pull request by Joerger**
Changelog: Fixed a bug in the WebUI where file transfers would always prompt for MFA, even when not required.

https://github.com/gravitational/teleport/pull/49794 introduced some hacky `useEffect` logic that failed to properly share the mfa state between sessions and file transfers within that session. This PR fixes it by having the two straightforwardly share mfa state within the same object.

Fixes https://github.com/gravitational/teleport/issues/51694

### CODE REVIEW

File: web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx [hunk 1]
```diff
@@ -54,14 +54,15 @@ function DocumentSsh({ doc, visible }: PropTypes) {
   const { tty, status, closeDocument, session } = useSshSession(doc);
   const [showSearch, setShowSearch] = useState(false);
 
-  const ttyMfa = useMfaEmitter(tty);
-  const ftMfa = useMfa({
-    isMfaRequired: ttyMfa.required,
+  const mfa = useMfaEmitter(tty, {
+    // The MFA requirement will be determined by whether we do/don't get
+    // an mfa challenge over the event emitter at session start.
+    isMfaRequired: false,
```
Comment (avatus) [inline web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:60]: if this field `isMfaRequired` is optional, it will default to false anyway,

besides a test, i dont see this field ever being used. is it needed? (i dont see it set true anywhere outside of a test)

Comment (Joerger) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:60]: It defaults to undefined if it isn't passed in

Comment (avatus) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:60]: Sorry, I meant defaults to a falsey value, which we can just parse to a Boolean

Comment (Joerger) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:60]: We compare to false directly in order to get the behavior of skipping MFA / MFA check when we are certain mfa is not necessary:

https://github.com/gravitational/teleport/blob/ce976bbe9d83c97589e8db32e825c83c0e64a6ba/web/packages/teleport/src/lib/useMfa.ts#L76

Comment (avatus) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:60]: Thats the state value tho, im talking about the `isMfaRequired` prop. because its optional, you can give it a default value
```js
export function useMfa({ req, isMfaRequired = false }: MfaProps): MfaState {
```
you dont have to pass `false` for the prop

Comment (Joerger) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:60]: We're initializing the state from the prop now so that we don't need any `useEffect` trickery - https://github.com/gravitational/teleport/blob/ce976bbe9d83c97589e8db32e825c83c0e64a6ba/web/packages/teleport/src/lib/useMfa.ts#L58

Comment (avatus) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:60]: Sure whatever the default should be, I was just suggesting we could have that default set in the destructuring.

**Review by avatus — APPROVED** [review]

File: web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx [hunk 2]
```diff
@@ -74,13 +75,10 @@ function DocumentSsh({ doc, visible }: PropTypes) {
 
   useEffect(() => {
     // when switching tabs or closing tabs, focus on visible terminal
-    if (
-      ttyMfa.attempt.status === 'processing' ||
-      ftMfa.attempt.status === 'processing'
-    ) {
+    if (mfa.attempt.status === 'processing') {
```
Comment (ravicious) [inline web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:78]: Why do we need to check the status of the MFA attempt here? I feel like the comment doesn't quite explain this.

File: web/packages/teleport/src/Console/DocumentSsh/useFileTransfer.ts [hunk 3]
```diff
@@ -54,7 +54,7 @@ export const useFileTransfer = (
   currentDoc: DocumentSsh,
   mfa: MfaState
 ) => {
-  const { filesStore } = useFileTransferContext();
+  const { filesStore, openedDialog } = useFileTransferContext();
```
Comment (ravicious) [inline web/packages/teleport/src/Console/DocumentSsh/useFileTransfer.ts:57]: Optimally we wouldn't need to pass `openedDialog` like this, `DocumentSsh` would call `useFileTransferContext` to get it. That's just a nit for the future, as it might be that either `DocumentSsh`, `useFileTransferContext`, or `useFileTransfer` are written in a way that doesn't support that for some reason.

File: web/packages/teleport/src/lib/useMfa.test.tsx [hunk 4]
```diff
@@ -119,48 +118,42 @@ describe('useMfa', () => {
...
+    });
 
-    // If isMfaRequiredRequest changes, the mfaRequired value should be reset.
-    setReq({
-      ...mockChallengeReq,
-      isMfaRequiredRequest: {
-        admin_action: {},
-      },
+    // mfa required will be updated to true as usual once the server returns an mfa challenge.
+    mfa.current.getChallengeResponse();
```
Comment (ravicious) [inline web/packages/teleport/src/lib/useMfa.test.tsx:153]: Operations that update React state need to be wrapped in `act`. https://react.dev/reference/react/act

<details>

```diff
diff --git a/web/packages/teleport/src/lib/useMfa.test.tsx b/web/packages/teleport/src/lib/useMfa.test.tsx
index e3af0abd90..3c2522edcc 100644
--- a/web/packages/teleport/src/lib/useMfa.test.tsx
+++ b/web/packages/teleport/src/lib/useMfa.test.tsx
@@ -17,6 +17,7 @@
  */
 
 import { renderHook, waitFor } from '@testing-library/react';
+import { act } from 'react';
 
 import { CreateAuthenticateChallengeRequest } from 'teleport/services/auth';
 import auth, { MfaChallengeScope } from 'teleport/services/auth/auth';
@@ -137,23 +138,23 @@ describe('useMfa', () => {
 
     // The mfa required state can be changed directly, in case the requirement
     // need to be updated by the caller.
-    mfa.current.setMfaRequired(true);
-    await waitFor(() => {
-      expect(mfa.current.mfaRequired).toEqual(true);
+    await act(async () => {
+      mfa.current.setMfaRequired(true);
     });
+    expect(mfa.current.mfaRequired).toEqual(true);
 
     // The mfa required state can be changed back to undefined (default) or null to force
     // the next mfa attempt to re-check mfa required / attempt to get a challenge.
-    mfa.current.setMfaRequired(null);
-    await waitFor(() => {
-      expect(mfa.current.mfaRequired).toEqual(null);
+    await act(async () => {
+      mfa.current.setMfaRequired(null);
     });
+    expect(mfa.current.mfaRequired).toEqual(null);
 
     // mfa required will be updated to true as usual once the server returns an mfa challenge.
-    mfa.current.getChallengeResponse();
-    await waitFor(() => {
-      expect(mfa.current.mfaRequired).toEqual(true);
+    await act(async () => {
+      await mfa.current.getChallengeResponse();
     });
+    expect(mfa.current.mfaRequired).toEqual(true);
   });
 
   test('mfa challenge error', async () => {

```
</details>

However, once I do that, for some reason this test times out while waiting for `mfa.current.getChallengeResponse()` to finish. On top of that, other tests start failing, which suggests that something is wrong with the setup.

What's more, I noticed that the tests in this file mock `console.error`:

https://github.com/gravitational/teleport/blob/e7bbfbafdb14b4a62970bebec577e64a498704fc/web/packages/teleport/src/lib/useMfa.test.tsx#L63-L65

I suspect it was added because of the errors that were logged by React due to not wrapping updates in `act`. We should not mock `console.error` unless our code is actually expected to use `console.error`, otherwise it's going to swallow actually useful errors that might help uncover bugs in the implementation. From what I see, `useMfa` does not use `console.error`, so we should remove the mock and fix the tests.

**Comment by ravicious** [comment]
Sorry for not reviewing this earlier, I was a bit swamped with other reviews.

File: web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx (hunk 2 above)
Comment (Joerger) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:78]: Here's the original piece of code, which I don't fully understand:

```
  useEffect(() => {
    // when switching tabs or closing tabs, focus on visible terminal
    terminalRef.current?.focus();
  }, [visible, mfa.requested]);
```

I thought this was meant to focus the page when mfa is requested, but does the useEffect also get called at the start, when the user opens the terminal?

Comment (Joerger) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx:78]: This doesn't seem to do anything in the current or previous state. If I Cmd+click to open the terminal in a new tab, shouldn't it autofocus me to that tab?

File: web/packages/teleport/src/lib/useMfa.test.tsx (hunk 4 above)
Comment (Joerger) [reply web/packages/teleport/src/lib/useMfa.test.tsx]: Got it. Looks like I was using `waitFor` when `act` is a much better way to do it (and doesn't result in error logs...).

The only test I couldn't fix is:

```
useMfa › reset mfa attempt

    User canceled MFA attempt

      133 |   const cancelAttempt = () => {
      134 |     if (mfaResponseRef.current) {
    > 135 |       mfaResponseRef.current.reject(new MfaCanceledError());
          |                                     ^
      136 |     }
      137 |   };
      138 |

      at Object.cancelAttempt (web/packages/teleport/src/lib/useMfa.ts:135:37)
      at cancelAttempt (web/packages/teleport/src/lib/useMfa.test.tsx:243:39)
      at act (node_modules/.pnpm/react@18.3.1/node_modules/react/cjs/react.development.js:2512:16)
      at Object.<anonymous> (web/packages/teleport/src/lib/useMfa.test.tsx:243:14)
```

The test is expecting this error - I don't understand why it isn't caught by the ` await expect(resp).rejects.toThrow(new MfaCanceledError());` line.

```js
     let resp;
    await act(async () => {
      resp = mfa.current.getChallengeResponse();
    });

    await act(async () => mfa.current.cancelAttempt());

    await expect(resp).rejects.toThrow(new MfaCanceledError());
```

File: web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx (hunk 2 above)
Comment (ravicious) [reply web/packages/teleport/src/Console/DocumentSsh/DocumentSsh.tsx]: > I thought this was meant to focus the page when mfa is requested, but does the useEffect also get called at the start, when the user opens the terminal even if mfa.requested is false?

Yes, the effect gets called whenever the deps change. It doesn't matter what their values are, as long as at least for one dep `Object.is(oldDep, newDep)` returns false.

I think "tabs" here refers not to browser tabs but to a little-known feature that I'm not sure how many people use. :D Probably not much since no one complained about focus not working.

When you connect to an SSH node through the Web UI, there's one in-page "tab" at the top with a plus button next to it. When you click the plus button, you can connect to another SSH node, similar how in Connect you can have multiple tabs.

We should probably bring back the previous behavior where it calls `focus` whenever `visible` changes or MFA is requested. Though I'm not sure which `mfa` prop we should check, `mfaRequired`? I think the intent might have been that after you go through the MFA check, the focus is automatically on the terminal.

The whole check should first see if `visible` is truthy, otherwise it'll keep calling `focus` even on tabs that are not visible. Which might not break anything but why do something that's unnecessary.

File: web/packages/teleport/src/lib/useMfa.test.tsx (hunk 4 above)
Comment (ravicious) [reply web/packages/teleport/src/lib/useMfa.test.tsx]: Ooof I figured it out. I ran into a weird behavior of Jest around promises a few weeks ago. After poking around, I think it boils down to an unhandled promise. https://github.com/jestjs/jest/issues/9210

Browsers give you warnings when you create a promise but don't handle its rejection. https://jakearchibald.com/2023/unhandled-rejections/#unhandled-rejections-are-problematic Jest just fails the test if there's an unhandled promise, but it doesn't tell you that explicitly, instead it depends on Node.js showing you an appropriate warning. This is especially pernicious when running `pnpm tdd`, because it's easy to miss it.

When you run `pnpm test`, you can see it more easily:

```
(node:46684) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
```

The issue was related to the fact that at the moment when we call `mfa.current.cancelAttempt`, `resp` gets rejected, but there's nothing to handle it, so Jest fails the test. The solution is to write some kind of code that attaches to the rejection handler of the promise, so that when the promise actually gets rejected, Jest sees that there's something handling the rejection.

**Review by ravicious — APPROVED** [review]

File: web/packages/teleport/src/lib/useMfa.test.tsx (hunk 4 above)
Comment (Joerger) [reply web/packages/teleport/src/lib/useMfa.test.tsx]: Ah that makes sense, thanks for finding the fix!
