### PR TITLE
fix leaf SSH sessions not getting recorded

### LINKED ISSUE #31776: Playing a leaf SSH session recorded at the proxy fails
Expected behavior:
Playing a leaf SSH session recorded at the proxy succeeds

Current behavior:
Playing a leaf SSH session recorded at the proxy fails

Bug details:
- Teleport version
Teleport v14.0.0-beta.1
- Recreation steps
Using `tsh` or the WebUI, connect to a node and try to play back the recorded session. The leaf auth server must be set to record sessions on the proxy and the root auth server must not be set to record sessions on the proxy, otherwise playing back the session succeeds.

- Debug logs
```
2023-09-12T18:24:58-04:00 [WEB]       DEBU Unable to find events for session 923f620d-507b-4796-8153-86c0fb64b9ec. error:[
ERROR REPORT:                                                                                                                     
Original Error: *trace.NotFoundError open /var/lib/teleport2-new/log/records/923f620d-507b-4796-8153-86c0fb64b9ec.tar: no such fil
e or directory 
Stack Trace:                                                                                                             [0/37604]
Caught:
        github.com/gravitational/teleport/lib/httplib/httplib.go:206 github.com/gravitational/teleport/lib/httplib.ConvertResponse
        github.com/gravitational/teleport/lib/auth/http_client.go:314 github.com/gravitational/teleport/lib/auth.(*HTTPClient).Get
        github.com/gravitational/teleport/lib/auth/http_client.go:918 github.com/gravitational/teleport/lib/auth.(*HTTPClient).Get
SessionEvents
        github.com/gravitational/teleport/lib/web/apiserver.go:3480 github.com/gravitational/teleport/lib/web.(*Handler).siteSessi
onEventsGet
        github.com/gravitational/teleport/lib/web/apiserver.go:3656 github.com/gravitational/teleport/lib/web.(*Handler).bindDefau
ltEndpoints.(*Handler).WithClusterAuth.func34
        github.com/gravitational/teleport/lib/httplib/httplib.go:117 github.com/gravitational/teleport/lib/web.(*Handler).bindDefa
ultEndpoints.(*Handler).WithClusterAuth.MakeHandler.MakeHandlerWithErrorWriter.func157
        github.com/julienschmidt/httprouter@v1.3.0/router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
        net/http/server.go:2179 github.com/gravitational/teleport/lib/web.NewHandler.func1.StripPrefix.func1
        net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
        github.com/gravitational/teleport/lib/web/apiserver.go:463 github.com/gravitational/teleport/lib/web.NewHandler.func1
        net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
        github.com/julienschmidt/httprouter@v1.3.0/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
        github.com/gravitational/teleport/lib/web/apiserver.go:317 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHT
TP
        github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy
/ratelimit.(*TokenLimiter).ServeHTTP
        github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 github.com/gravitational/oxy/con
nlimit.(*ConnLimiter).ServeHTTP
        github.com/gravitational/teleport/lib/httplib/httplib.go:94 github.com/gravitational/teleport/lib/httplib.MakeTracingHandl
er.func1
        net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212 go.opentelemetry.io/contrib/instrumen
tation/net/http/otelhttp.(*Handler).ServeHTTP
        net/http/server.go:2938 net/http.serverHandler.ServeHTTP
        net/http/server.go:2009 net/http.(*conn).serve
        runtime/asm_amd64.s:1650 runtime.goexit
User Message: open /var/lib/teleport2-new/log/records/923f620d-507b-4796-8153-86c0fb64b9ec.tar: no such file or directory
] web/apiserver.go:3482
```

---

The recorded session is recorded and uploaded to the root cluster, but when playback is requested it is searched for in the leaf cluster.

### PR DESCRIPTION
**Pull request by capnspacehook**
Fixes https://github.com/gravitational/teleport/issues/31776.

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -1136,6 +1137,112 @@ func testSessionRecordingModes(t *testing.T, suite *integrationTestSuite) {
...
 }
 
+func testLeafProxySessionRecording(t *testing.T, suite *integrationTestSuite) {
+	rootRecCfg, err := types.NewSessionRecordingConfigFromConfigFile(types.SessionRecordingConfigSpecV2{
+		Mode: types.RecordAtNode,
+	})
+	require.NoError(t, err)
+
+	leafRecCfg, err := types.NewSessionRecordingConfigFromConfigFile(types.SessionRecordingConfigSpecV2{
+		Mode: types.RecordAtProxy,
```
Comment (AntonAM) [inline integration/integration_test.go:1147]: We probably should make it into table test and test inverted condition as well (when leaf is atNode and local is atProxy)

File: lib/reversetunnel/remotesite.go [hunk 2]
```diff
@@ -755,15 +755,21 @@ func (s *remoteSite) DialAuthServer(params reversetunnelclient.DialParams) (net.
...
 
-	// If the proxy is in recording mode and a SSH connection is being
-	// requested or the target server is a registered OpenSSH node, build
-	// an in-memory forwarding server.
-	if shouldDialAndForward(params, recConfig) {
+	// If the remote cluster is recording at the proxy we need to respect
+	// that and forward and record the session. We will be connecting
+	// to the node without connecting through the remote Proxy, so the
+	// session won't have a chance to get recorded at the remote Proxy.
+	if remoteProxyRec || shouldDialAndForward(params, localRecCfg) {
```
Comment (AntonAM) [inline lib/reversetunnel/remotesite.go:772]: Maybe it can be beneficial to split this condition and call `return s.dialAndForward(params)` separately for each part? That way we don't need to call `s.remoteAccessPoint.GetSessionRecordingConfig(s.ctx)` if local one satisfies the condition.

**Review by AntonAM — APPROVED** [review]

File: integration/integration_test.go [hunk 3]
```diff
@@ -1136,6 +1137,112 @@ func testSessionRecordingModes(t *testing.T, suite *integrationTestSuite) {
...
+		}
+	}
+
+	require.Eventually(t, func() bool {
+		events, err := rootTC.GetSessionEvents(ctx, defaults.Namespace, sessionID)
+		if err == nil && len(events) != 0 {
+			return true
+		}
+		return false
+	}, time.Second*5, time.Millisecond*200)
```
Comment (espadolini) [inline integration/integration_test.go:1243]: nit for style

```suggestion
	require.EventuallyWithT(t, func(t *assert.CollectT) {
		events, err := rootTC.GetSessionEvents(ctx, defaults.Namespace, sessionID)
		assert.NoError(t, err)
		assert.NotEmpty(t, events)
	}, time.Second*5, time.Millisecond*200)
```

File: lib/reversetunnel/remotesite.go (hunk 2 above)
Comment (espadolini) [reply lib/reversetunnel/remotesite.go:772]: I don't understand this comment. Shouldn't the remote proxy be responsible for the last leg of the connection and thus for the recording?

Comment (capnspacehook) [reply lib/reversetunnel/remotesite.go:772]: @espadolini as I understood it when connecting to a leaf node through a root proxy the root cluster should have the recording. Here are the items in the test plan that lead me to finding this issue: 

- [Sessions can be recorded at the proxy](https://goteleport.com/docs/server-access/guides/recording-proxy-mode/)
  - Sessions on remote clusters are recorded in the local cluster

File: integration/integration_test.go (hunk 3 above)
Comment (capnspacehook) [reply integration/integration_test.go]: Thanks, done

File: lib/srv/sess.go [hunk 4]
```diff
@@ -1302,6 +1302,7 @@ func newRecorder(s *session, ctx *ServerContext) (events.SessionPreparerRecorder
 	// Nodes discard events in cases when proxies are already recording them.
 	if s.registry.Srv.Component() == teleport.ComponentNode &&
 		services.IsRecordAtProxy(ctx.SessionRecordingConfig.GetMode()) {
+		s.log.Debug("not recording session on node, will be recorded at proxy")
```
[the remark this answers is not in the document]
Comment (capnspacehook) [reply lib/srv/sess.go:1305]: As this only is emitted when a session is started I don't see an issue, if you feel strongly about this I can change it but considering everything else we log at the Debug level when handling an SSH session it seems reasonable to me.

File: integration/integration_test.go [hunk 5]
```diff
@@ -184,6 +184,7 @@ func TestIntegrations(t *testing.T) {
 	t.Run("SSHTracker", suite.bind(testSSHTracker))
 	t.Run("ListResourcesAcrossClusters", suite.bind(testListResourcesAcrossClusters))
 	t.Run("SessionRecordingModes", suite.bind(testSessionRecordingModes))
+	t.Run("LeafSessionRecording", suite.bind(testLeafProxySessionRecording))
```
[the remark this answers is not in the document]
Comment (capnspacehook) [reply integration/integration_test.go]: Hmm that's unfortunate... I made it more in order but won't fix the bottom statements as I don't want to add too much noise/make it difficult to backport

File: integration/integration_test.go [hunk 6]
```diff
@@ -1136,6 +1137,151 @@ func testSessionRecordingModes(t *testing.T, suite *integrationTestSuite) {
...
+				assert.NoError(t, err)
+
+				errCh <- nodeClient.RunInteractiveShell(ctx, types.SessionPeerMode, nil, nil)
+				assert.NoError(t, nodeClient.Close())
+			}()
+
+			var sessionID string
+			require.Eventually(t, func() bool {
+				trackers, err := authSrv.GetActiveSessionTrackers(ctx)
+				require.NoError(t, err)
```
[the remark this answers is not in the document]
Comment (capnspacehook) [reply integration/integration_test.go]: Thanks, didn't realize `require.Eventually` called the function in a goroutine but it makes total sense that it does.

File: lib/srv/sess.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (capnspacehook) [reply lib/srv/sess.go]: Sure looks reasonable to me

**Review by rosstimothy — APPROVED** [review]
