### PR TITLE
Fix Heartbeat (v1) health reporting logic

### LINKED ISSUE #52273: teleports readyz should fail if backend is unreachable
Expected behavior:
When the teleport auth service is unable to connect to the backend the readyz endpoint should fail.

Current behavior:

Currently when the auth service enters a `Degraded` state it quickly transitions to `Recovering` and then `OK`. Until the next heartbeat fails and the cycle happens again. This prevents kubernetes from marking the pod as not ready and prevents us from being able to automatically failover to auth servers in another region.

```

{"timestamp":"2025-02-13T22:52:25Z","level":"info","caller":"service/state.go:122","message":"Teleport component is recovering from a degraded state.","component":"proc:1","pid":"7.1","component":"auth"} |  
{"timestamp":"2025-02-13T22:52:39Z","level":"info","caller":"service/state.go:126","message":"Teleport component has recovered from a degraded state.","component":"proc:1","pid":"7.1","component":"auth"} |  
{"timestamp":"2025-02-13T22:58:36Z","level":"info","caller":"service/state.go:108","message":"Detected Teleport component is running in a degraded state.","component":"proc:1","pid":"7.1","component":"auth"} |  
{"timestamp":"2025-02-13T22:58:36Z","level":"info","caller":"service/state.go:122","message":"Teleport component is recovering from a degraded state.","component":"proc:1","pid":"7.1","component":"auth"} |  
{"timestamp":"2025-02-13T22:58:48Z","level":"info","caller":"service/state.go:126","message":"Teleport component has recovered from a degraded state.","component":"proc:1","pid":"7.1","component":"auth"} |  
{"timestamp":"2025-02-13T23:01:45Z","level":"info","caller":"service/state.go:108","message":"Detected Teleport component is running in a degraded state.","component":"proc:1","pid":"7.1","component":"auth"} |  
{"timestamp":"2025-02-13T23:01:45Z","level":"info","caller":"service/state.go:122","message":"Teleport component is recovering from a degraded state.","component":"proc:1","pid":"7.1","component":"auth"} |  
{"timestamp":"2025-02-13T23:01:59Z","level":"info","caller":"service/state.go:126","message":"Teleport component has recovered from a degraded state.","component":"proc:1","pid":"7.1","component":"auth"}

```

The state is flipped to degraded when an error is returned from `fetchAndAnnounced` and passed to `OnHeartbeat`.

https://github.com/gravitational/teleport/blob/320dff5c4f5375bad75470889526ae17d6b35ca8/lib/srv/heartbeat.go#L284-L288

However `announce()` will always return a nil error on the next call after an error occured as the state transitions to `HeartbeatStateAnnounceWait`.

https://github.com/gravitational/teleport/blob/320dff5c4f5375bad75470889526ae17d6b35ca8/lib/srv/heartbeat.go#L395-L396

### PR DESCRIPTION
**Pull request by espadolini**
This PR fixes a long-standing logic error in the heartbeat (v1) health reporting logic: the heartbeat state machine is frequently polled to make a decision on how to act, but the return value of "no error" whenever the state of the heartbeat resulted in no action being taken yet was taken to mean "successful heartbeat" by the reporting logic. This PR fixes the problem by only calling the health reporting function if a heartbeat actually happened, either as an upsert or as a keepalive.

Fixes #52273 

changelog: fixed logic error that could result in Teleport reporting as ready shortly after becoming not ready

### CODE REVIEW

**Comment by espadolini** [comment]
@rosstimothy should we be concerned that for several services (including the control plane ones) this is essentially a breaking change?

File: lib/srv/heartbeat.go [hunk 1]
```diff
@@ -389,68 +391,68 @@ func (h *Heartbeat) fetch() error {
 	}
 }
 
-func (h *Heartbeat) announce() error {
+func (h *Heartbeat) announce() (doneSomething bool, _ error) {
```
Comment (fspmarshall) [inline lib/srv/heartbeat.go:394]: nit: document the meaning/implications of `doneSomething`.

**Review by fspmarshall — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Comment by sclevine** [comment]
Context on breaking change: https://github.com/gravitational/teleport/issues/52273#issuecomment-2666962372

Hopefully we can coordinate the change. I agree the new behavior is better, but we'll need a documented way to keep proxies routable when all auth servers are unavailable.

**Comment by sclevine** [comment]
After discussion, this should be okay to merge with coordination / communication about the change in behavior.

File: lib/srv/heartbeat.go (hunk 1 above)
Comment (espadolini) [reply lib/srv/heartbeat.go:394]: Missed this before merging, addressed in backports and #52384
