### PR TITLE
Fix switching between users in a cluster

### LINKED ISSUE #15436: Switching users with tsh requires two `tsh login` attempts.
Expected behavior:
```
> tsh login --user=dev --proxy=proxy.example.com
// successfully login and print status
> tsh login --user=dev2 --proxy=proxy.example.com
// successfully login and print status
```

Current behavior:
```
> tsh login --user=dev --proxy=proxy.example.com
// successfully login and print status
> tsh login --user=dev2 --proxy=proxy.example.com
ERROR: open /home/bjoerger/.tsh/keys/proxy.example.com/dev2: no such file or directory
> tsh login --user=dev2 --proxy=proxy.example.com
// successfully login and print status
```

Logs:
```
> tsh -d login --user=dev2 --proxy=proxy.example.com:3080 
[KEYSTORE]  DEBU Returning Teleport TLS certificate "/home/bjoerger/.tsh/keys/proxy.example.com/dev-x509.pem" valid until "2022-08-12 01:55:43 +0000 UTC". client/keystore.go:319
[KEYSTORE]  DEBU Reading certificates from path "/home/bjoerger/.tsh/keys/proxy.example.com/dev-ssh/root-cluster-cert.pub". client/keystore.go:342
[CLIENT]    INFO no host login given. defaulting to bjoerger client/api.go:1418
[CLIENT]    INFO [KEY AGENT] Connected to the system agent: "/run/user/1000/keyring/ssh" client/api.go:3931
[KEYSTORE]  ERRO open /home/bjoerger/.tsh/keys/proxy.example.com/dev2: no such file or directory client/keystore.go:281
[TSH]       DEBU open /home/bjoerger/.tsh/keys/proxy.example.com/dev2: no such file or directory tsh/tsh.go:3092
[CLIENT]    DEBU attempting to use loopback pool for local proxy addr: proxy.example.com:3080 client/api.go:3889
[CLIENT]    DEBU reading self-signed certs from: /var/lib/teleport/webproxy_cert.pem client/api.go:3897
[CLIENT]    DEBU could not open any path in: /var/lib/teleport/webproxy_cert.pem client/api.go:3901
            DEBU Attempting GET proxy.example.com:3080/webapi/ping webclient/webclient.go:115
[KEYSTORE]  ERRO open /home/bjoerger/.tsh/keys/proxy.example.com/dev2: no such file or directory client/keystore.go:281

ERROR REPORT:
Original Error: *trace.NotFoundError open /home/bjoerger/.tsh/keys/proxy.example.com/dev2: no such file or directory
Stack Trace:
	/home/bjoerger/gravitational/teleport/lib/client/keystore.go:282 github.com/gravitational/teleport/lib/client.(*FSLocalKeyStore).GetKey
	/home/bjoerger/gravitational/teleport/lib/client/keyagent.go:300 github.com/gravitational/teleport/lib/client.(*LocalKeyAgent).GetKey
	/home/bjoerger/gravitational/teleport/lib/client/keyagent.go:306 github.com/gravitational/teleport/lib/client.(*LocalKeyAgent).GetCoreKey
	/home/bjoerger/gravitational/teleport/tool/tsh/kube.go:1002 main.fetchKubeStatus
	/home/bjoerger/gravitational/teleport/tool/tsh/kube.go:1097 main.updateKubeConfig
	/home/bjoerger/gravitational/teleport/tool/tsh/tsh.go:1359 main.onLogin
	/home/bjoerger/gravitational/teleport/tool/tsh/tsh.go:961 main.Run
	/home/bjoerger/gravitational/teleport/tool/tsh/tsh.go:414 main.main
	/home/bjoerger/.tools/go/1.18.3/src/runtime/proc.go:250 runtime.main
	/home/bjoerger/.tools/go/1.18.3/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: open /home/bjoerger/.tsh/keys/proxy.example.com/dev2: no such file or directory
```

It looks like this is caused by https://github.com/gravitational/teleport/pull/14443

### PR DESCRIPTION
**Pull request by Joerger**
Closes https://github.com/gravitational/teleport/issues/15436

### CODE REVIEW

File: tool/tsh/tsh.go [hunk 1]
```diff
@@ -1389,11 +1389,12 @@ func onLogin(cf *CLIConf) error {
 				return trace.Wrap(err)
 			}
 			if err := updateKubeConfig(cf, tc, ""); err != nil {
```
Comment (zmb3) [inline tool/tsh/tsh.go:1391]: This empty if branch is really confusing to me. Let's invert the check and get rid of the else.

```
if err := updateKubeConfig(cf, tc, ""); err == nil {
    return trace.Wrap(onStatus(cf))
}
```

**Review by jakule — APPROVED** [review]

File: tool/tsh/tsh.go [hunk 2]
```diff
@@ -1388,11 +1388,12 @@ func onLogin(cf *CLIConf) error {
...
 				return trace.Wrap(err)
 			}
-			if err := updateKubeConfig(cf, tc, ""); err != nil {
-				return trace.Wrap(err)
+			if err := updateKubeConfig(cf, tc, ""); err == nil {
+				return trace.Wrap(onStatus(cf))
 			}
 
-			return trace.Wrap(onStatus(cf))
+			// If we fail to update the kube config, we may be switching to
```
Comment (zmb3) [inline tool/tsh/tsh.go:1395]: This comment looks a little weird here with the indentation, but LGTM otherwise.

**Review by zmb3 — APPROVED** [review]
