### PR TITLE
Reject access requests with invalid cluster names

### LINKED ISSUE #19494: Teleport accepts access requests with an invalid cluster name
The Teleport API will allow you to create an access request with an invalid cluster name.

For example, a common mistake is to include the port in the cluster name field - something like `mycluster.teleport.sh:443`.

Teleport will happily accept this request and allow you to assume an elevated role set once it is approved, but you'll find that you don't have access to any resources due to the incorrect cluster name.

Investigate ways to improve the UX:

- consider rejecting the request to create the access request in the first place
- consider validating that the requested resource UUIDs belong to the specified cluster (may not be possible with trusted clusters)
- at a minimum, try to detect this state and present a clear error message rather than making it appear that everything is working

### PR DESCRIPTION
**Pull request by EdwardDowling**
Reject access requests with unknown cluster names.

Teleport will currently accept requests for non existent clusters and allow you to assume an elevated role set once it is approved, but you'll find that you don't have access to any resources due to the incorrect cluster name.

closes #19494

### CODE REVIEW

**Review by zmb3 — COMMENTED** [review]
Some test coverage would be good here.

**Comment by GavinFrazar** [comment]
@EdwardDowling the test changes you made pass with and without your changes to access requests

File: lib/auth/grpcserver.go [hunk 1]
```diff
@@ -792,6 +792,23 @@ func (g *GRPCServer) CreateAccessRequest(ctx context.Context, req *types.AccessR
...
+	}
+	for _, resourceID := range req.Spec.RequestedResourceIDs {
+		if resourceID.ClusterName != "" {
+			if resourceID.ClusterName == localClusterName.GetClusterName() {
+				continue
+			}
+			if _, err := auth.GetRemoteCluster(resourceID.ClusterName); err == nil {
+				continue
+			}
+			return nil, trace.NotFound("remote cluster %q is not found", resourceID.ClusterName)
```
Comment (r0mant) [inline lib/auth/grpcserver.go:808]: This error message is confusing. For example, why does it mention "remote cluster"? A couple suggestions:
- Make error message more user-friendly, for example "access request contains invalid cluster name xxx".
- Instead of returning on the first error, can we validate all cluster names provided in the request and include them in the message?

File: lib/auth/tls_test.go [hunk 2]
```diff
@@ -1377,6 +1377,12 @@ func TestWebSessionMultiAccessRequests(t *testing.T) {
 	err = clt.CreateAccessRequest(ctx, roleReq)
 	require.NoError(t, err)
 
+	// Create remote cluster
+	rc, err := types.NewRemoteCluster("foobar")
+	require.NoError(t, err)
+	err = tt.server.AuthServer.AuthServer.CreateRemoteCluster(rc)
+	require.NoError(t, err)
```
Comment (r0mant) [inline lib/auth/tls_test.go:1384]: Like @GavinFrazar mentioned, it's not very clear what creating a "foobar" remote cluster is accomplishing w/r/t testing invalid cluster names in access requests.

**Review by r0mant — CHANGES_REQUESTED** [review]

File: lib/auth/tls_test.go (hunk 2 above)
Comment (EdwardDowling) [reply lib/auth/tls_test.go]: Have added more tests for the cluster name validation and added a comment to the change in that existing change to explain why it was changed.

**Comment by EdwardDowling** [comment]
@zmb3 Could you give this another look when you get the chance?

**Review by zmb3 — APPROVED** [review]

File: lib/services/access_request.go [hunk 3]
```diff
@@ -60,6 +60,44 @@ func ValidateAccessRequest(ar types.AccessRequest) error {
...
+		}
+		if resourceID.ClusterName == localClusterName.GetClusterName() {
+			continue
+		}
+		_, err := cg.GetRemoteCluster(resourceID.ClusterName)
+		if err == nil {
+			continue
+		}
+		if trace.IsNotFound(err) {
+			errs = append(errs, trace.NotFound("access request contains invalid cluster name %q", resourceID.ClusterName))
```
Comment (r0mant) [inline lib/services/access_request.go:90]: Don't mean to be too pedantic but instead of returning a list of "access request contains invalid cluster name" errors for each invalid name, can we return a single error with a list of invalid cluster names? Basically, collect invalid cluster names instead of collecting multiple and returning aggregate.

File: lib/services/access_request.go [hunk 4]
```diff
@@ -60,6 +60,44 @@ func ValidateAccessRequest(ar types.AccessRequest) error {
...
+			continue
+		}
+		if resourceID.ClusterName == localClusterName.GetClusterName() {
+			continue
+		}
+		_, err := cg.GetRemoteCluster(resourceID.ClusterName)
+		if err == nil {
+			continue
+		}
+		if trace.IsNotFound(err) {
```
Comment (r0mant) [inline lib/services/access_request.go:89]: When I asked about handling "not found" before, I didn't mean to ignore everything else but rather return.

```go
_, err = cg.GetRemoteCluster(resourceID.ClusterName)
if err != nil && !trace.IsNotFound(err) {
  return trace.Wrap(err, "failed to fetch remote cluster %q", resourceID.ClusterName)
}
if trace.IsNotFound(err) {
  // add cluster name to the list of invalid clusters
}
```

**Review by r0mant — APPROVED** [review]
lgtm with 2 more comments

File: lib/services/access_request.go [hunk 5]
```diff
@@ -60,6 +60,44 @@ func ValidateAccessRequest(ar types.AccessRequest) error {
...
+			errs = append(errs, trace.NotFound("access request contains invalid cluster name %q", resourceID.ClusterName))
+			continue
+		}
+		errs = append(errs, err)
+	}
+	if errs != nil {
+		return trace.NewAggregate(errs...)
+	}
+	return nil
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply lib/services/access_request.go:98]: ignore this if you remove the aggregate error as Roman suggested

**Review by GavinFrazar — APPROVED** [review]

File: lib/services/access_request.go (hunk 4 above)
Comment (EdwardDowling) [reply lib/services/access_request.go]: Ah that makes more sense than how i first read it.
