### PR TITLE
[Web] Fix availability filter on unified resources not updating results immediately

### LINKED ISSUE #48469: [Web] Changing "show requestable resources" filter on the unified resources page requires a refresh to take effect
Expected behavior:

When toggling on or off the "show requestable resources" filter on the unified resources page, the results should be updated immediately.

Current behavior:

When toggling on or off the "show requestable resources" filter on the unified resources page, results are only updated after a refresh.

Bug details:
- Teleport version: v17.0.0-alpha.4

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves https://github.com/gravitational/teleport/issues/48469

Fixes a bug where changing the "Show requestable resources" filter on the unified resources page would not update results immediately. This was because recent changes to the `useUrlFiltering` logic relied entirely on the URL as the source of truth,  but this particular filter is not stored in the URL query params.

### CODE REVIEW

File: web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts [hunk 1]
```diff
@@ -61,19 +62,23 @@ export function useUrlFiltering(
   }
 
   const [initialParamsState] = useState(initialParams);
+  const [includedResourceMode, setIncludedResourceMode] =
```
Comment (gzdunek) [inline web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts:65]: I don't think we should add more state. The resource mode is kept in user preferences so we already have a state for it. 
Ideally, we should probably refactor `useUserFiltering` to set and read `includedResourceMode` from `useUser`, but for now I'd just pass that variable through the hook:
```
Subject: [PATCH] Do not add another state for `includedResourceMode`
---
Index: web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx b/web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx
--- a/web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx	(revision 2f3d3ad6ad41576e351d81657db5f2315e344747)
+++ b/web/packages/teleport/src/UnifiedResources/UnifiedResources.tsx	(date 1731429193528)
@@ -132,15 +132,18 @@
   const canCreate = teleCtx.storeUser.getTokenAccess().create;
   const [loadClusterError, setLoadClusterError] = useState('');
 
-  const { params, setParams, replaceHistory, pathname } = useUrlFiltering({
-    sort: {
-      fieldName: 'name',
-      dir: 'ASC',
-    },
-    includedResourceMode: availabilityFilter?.mode,
-    pinnedOnly:
-      preferences?.unifiedResourcePreferences?.defaultTab === DefaultTab.PINNED,
-  });
+  const { params, setParams, replaceHistory, pathname } = useUrlFiltering(
+    {
+      sort: {
+        fieldName: 'name',
+        dir: 'ASC',
+      },
+      pinnedOnly:
+        preferences?.unifiedResourcePreferences?.defaultTab ===
+        DefaultTab.PINNED,
+    },
+    availabilityFilter?.mode
+  );
 
   const getCurrentClusterPinnedResources = useCallback(
     () => getClusterPinnedResources(clusterId),
Index: web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts b/web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts
--- a/web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts	(revision 2f3d3ad6ad41576e351d81657db5f2315e344747)
+++ b/web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts	(date 1731429193524)
@@ -40,7 +40,8 @@
 }
 
 export function useUrlFiltering(
-  initialParams: Partial<ResourceFilter>
+  initialParams: Partial<Omit<ResourceFilter, 'includedResourceMode '>>,
+  includedResourceMode?: IncludedResourceMode
 ): UrlFilteringState {
   const { search, pathname } = useLocation();
 
@@ -62,8 +63,6 @@
   }
 
   const [initialParamsState] = useState(initialParams);
-  const [includedResourceMode, setIncludedResourceMode] =
-    useState<IncludedResourceMode>(initialParamsState.includedResourceMode);
   const params = useMemo(() => {
     const urlParams = getResourceUrlQueryParams(search);
     return {
@@ -78,7 +77,6 @@
   }, [search, includedResourceMode]);
 
   function setParams(newParams: ResourceFilter) {
-    setIncludedResourceMode(newParams.includedResourceMode);
     replaceHistory(
       encodeUrlQueryParams({
         pathname,
```

File: web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts [hunk 2]
```diff
@@ -39,7 +40,8 @@ export interface UrlFilteringState {
 }
 
 export function useUrlFiltering(
-  initialParams: Partial<ResourceFilter>
+  initialParams: Partial<Omit<ResourceFilter, 'includedResourceMode '>>,
+  includedResourceMode?: IncludedResourceMode
```
Comment (ravicious) [inline web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts:44]: How does `includedResourceMode` gets updated? `useUrlFiltering` exposes `setParams` that accepts the `includedResourceMode` field, but as far as I understand it has no effect?

FWIW, passing an arg through a hook like that (you accept something as an input and then pass it to the output with no changes) indicates that this could've been done outside of the hook. But I don't know how difficult it'd be to refactor this.

Comment (rudream) [reply web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts:44]: Updating the `availabilityFilter` prop passed to the unified resources component (`ClusterResources`) updates the `includedResourceMode` value passed to `useUrlFiltering`, and in `useUrlFiltering` when updating the `params`, we include that `includedResourceMode` in the returned object:

```
  const params = useMemo(() => {
    const urlParams = getResourceUrlQueryParams(search);
    return {
      ...initialParamsState,
      ...urlParams,
      includedResourceMode,
      pinnedOnly:
        urlParams.pinnedOnly !== undefined
          ? urlParams.pinnedOnly
          : initialParamsState.pinnedOnly,
    };
  }, [search, includedResourceMode]);
  ```

File: web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts [hunk 3]
```diff
@@ -66,12 +68,13 @@ export function useUrlFiltering(
...
+      includedResourceMode,
       pinnedOnly:
         urlParams.pinnedOnly !== undefined
           ? urlParams.pinnedOnly
           : initialParamsState.pinnedOnly,
     };
-  }, [search]);
+  }, [search, includedResourceMode]);
 
   function setParams(newParams: ResourceFilter) {
```
Comment (ravicious) [inline web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts:79]: I feel like it'd be nice to omit `includedResourceMode` from here as well, perhaps create a new type in this file that can be reused? Something like `type URLResourceFilter = Omit<ResourceFilter, 'includedResourceMode'>`.

File: web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts [hunk 4]
```diff
@@ -39,7 +40,8 @@ export interface UrlFilteringState {
 }
 
 export function useUrlFiltering(
-  initialParams: Partial<ResourceFilter>
+  initialParams: Partial<Omit<ResourceFilter, 'includedResourceMode '>>,
```
Comment (ravicious) [inline web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts:43]: All of the keys in `ResourceFilter` are already optional, `Partial` doesn't seem necessary. There's also an extra space after `includedResourceMode`.

```suggestion
  initialParams: Omit<ResourceFilter, 'includedResourceMode'>,
```

**Review by ravicious — APPROVED** [review]

File: web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts (hunk 3 above)
Comment (ravicious) [reply web/packages/teleport/src/components/hooks/useUrlFiltering/useUrlFiltering.ts:79]: This would avoid a situation where someone passes `includedResourceMode` to `setParams` since it's allowed by types but doesn't actually do anything.

**Review by gzdunek — APPROVED** [review]
With Rafał's comments.
