### PR TITLE
handle postgres GSSEncRequest startup message

### LINKED ISSUE #6284: Postgres clients can send GSSEncRequest as a startup message instead of SSLRequest
### Description

**What happened**:

Under some circumstances, which are still unclear, Postgres clients (psql or pgAdmin for example), send a different initial handshake message than we expect. We expect the first message to be `SSLRequest` which indicates the start of TLS connection, but sometimes the first message is `GSSENCRequest`. This manifests into the error similar to this on the client side:

```
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

And corresponding logs on the server:

```
Apr 01 16:14:44 ip-172-31-25-182 teleport[723468]: WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *trace.BadParameterError multiplexer failed to detect connection protocol, first few bytes were: []byte{0x0, 0x0, 0x0, 0x8, 0x4, 0xd2, 0x16, 0x30}\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:396 github.com/gravitational/teleport/lib/multiplexer.detectProto\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:285 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:206 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: multiplexer failed to detect connection protocol, first few bytes were: []byte{0x0, 0x0, 0x0, 0x8, 0x4, 0xd2, 0x16, 0x30}" multiplexer/multiplexer.go:209
```

The unexpected message here is the encoded `GSSENCRequest` (see https://www.postgresql.org/docs/12/protocol-message-formats.html), the `SSLRequest` we expect is slightly different:

```
➜  src go run pgproto.go
SSLRequest:	[]byte{0x0, 0x0, 0x0, 0x8, 0x4, 0xd2, 0x16, 0x2f}
GSSEncRequest:	[]byte{0x0, 0x0, 0x0, 0x8, 0x4, 0xd2, 0x16, 0x30}
```

**What you expected to happen**:

We should reply with `N` to GSSEncRequest messages to indicate that server doesn't support it and have client gracefully fallback to TLS. Also, add the following line to each service configuration in ~/.pg_service.conf file we generate to disable GSS encryption explicitly:

```
gssencmode=disable
```

**Workaround**

Until the issue is fixed, manually updating pg_service.conf file to add the line shown above fixes the issue.

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #6284

## What
1. Recognize the "GSSEncRequest" message in multiplexer as postgres protocol.
2. Change postgres engine to handle this request at connection startup and respond 'N' for "not supported" to make client choose SSL encryption instead or disconnect.
3. Add `gssencmode=disable` to the ~/.pg_service.conf file we save on db login.

## Why
We don't support GSS encryption, but this message is sent at startup and we can easily respond with 'N' to let the client try SSL. This way they don't just automatically get an error.

### CODE REVIEW

**Review by hugoShaka — APPROVED** [review]

File: lib/srv/db/proxy_test.go [hunk 1]
```diff
@@ -54,6 +57,31 @@ func TestProxyProtocolPostgres(t *testing.T) {
...
+			require.NoError(t, err)
+			require.Equal(t, []byte("N"), buf[:bytesRead], "server should respond with 'N' to indicate GSS encryption is not supported'")
+			sslReq := pgproto3.SSLRequest{}
+			msg = sslReq.Encode(nil)
+			bytesWritten, err = conn.Write(msg)
+			require.NoError(t, err, "server should not have closed conn after rejecting GSS")
+			require.Equal(t, len(msg), bytesWritten)
+			bytesRead, err = conn.Read(buf)
+			require.NoError(t, err)
+			require.Equal(t, []byte("S"), buf[:bytesRead], "server should respond with 'S' to indicate SSL encryption is supported'")
```
Comment (smallinsky) [inline lib/srv/db/proxy_test.go:84]: nit: can we extract this GSS check to a separate function ?

Also from the test desc: 
> TestProxyProtocolPostgres ensures that clients can successfully connect to a
// Postgres database when Teleport is running behind a proxy that sends a proxy
// line.

Can we consider adding a new test instead of extending current test ?

**Review by smallinsky — APPROVED** [review]

File: lib/srv/db/proxy_test.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/srv/db/proxy_test.go:84]: Will address this after fixing what we suggested in the other repo.

Comment (GavinFrazar) [reply lib/srv/db/proxy_test.go]: Refactored into a (substantial) test that covers all code paths in `handleStartup`. I also made the tests run in parallel which sped things up substantially for tests running `lib/srv/db/proxy_test.go` from 15s runtime to 4.5 seconds locally. All tests still passed and I ran with the race detector on.

**Comment by GavinFrazar** [comment]
@smallinsky @hugoShaka I added substantial changes to the test code in `lib/srv/db/proxy_test.go` and I refactored `lib/srv/db/postgres/proxy.go:handleStartup` to use a loop instead of recursion. Please take another look and approve. I don't want to merge this without letting you guys review these additional changes.

**Review by hugoShaka — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]

**Comment by GavinFrazar** [comment]
@smallinsky you added a backport label for v8, but do we need to do that since we only support the last 3 versions (v9, v10, v11)?
