### PR TITLE
Several 2.0 regression fixes

### LINKED ISSUE #867: BoltDB backend: 'path' is not set, initializing teleport with config file.
Hey guys, 

First of, great job on building this toolkit!

I'm running (or at least trying to) Teleport v2.0.0-rc.1 fetching the binaries from the GH's releases section.

I've been able to make teleport work w/ the ad-hoc commands described at the docs.
But I've been getting a few strange errors while trying to start the teleport service using a config file (production-like deployment).

I tried to use the following config file: 
https://gist.github.com/lucazz/944391ceea2bc4ff5f2aa4600172ef7a

And got the following error message: 
```
sudo teleport start -c /etc/teleport/teleport.yaml
BoltDB backend: 'path' is not set, initializing teleport
```

Here's a more verbose output (using the -d flag):
https://gist.github.com/lucazz/7ff54439c941d3a91add1a2ed1565e84

Browsing the source code, I've been able to see the check that exits w/ code 1:
https://github.com/gravitational/teleport/blob/be5ab6cb3ebf0c67c0b063dc85dd9dfdd990f080/lib/backend/boltbk/boltbk.go#L72

But according to this comment on the code, it's supposed to load that path from the `data_dir` variable:
https://github.com/gravitational/teleport/blob/be5ab6cb3ebf0c67c0b063dc85dd9dfdd990f080/lib/backend/boltbk/boltbk.go#L65

What am I missing here guys? Is that a real issue?

### LINKED ISSUE #875: Every log message under systemd is logged twice
When teleport is running under system, every message it logs into its own log appears twice

### PR DESCRIPTION
**Pull request by kontsevoy**
I recommend reviewing this PR by looking at each commit individually. Commits are well-annotated and easy to understand.

## The summary:

1. Fixed #867 by "promoting" a top-level `data_dir` configuration value into back-end's `params` section. This was the original intent, there was even code which was looking up for this value, but it was never copied.
2. Fixed #875 by properly switching between syslog and stderr. Also cleaned up logging initialization, it's much easier to understand now.
3. Found and killed some dead code: there was a function nobody ever called.
4. Added comments here and there
5. Fixed Makefile in `build.assets` so it doesn't destroy `VERSION` variable anymore, so when you call `make -C build.assets release` you get a properly formatted tarball.
6. Fixed `SSH exec` unit test on OSX.
7. Fixed `forwarding request denied` unit test that failed on macOS.

## Notes

I am at Kubecon, so if you see issues with this PR please fix yourself, do not wait for me to return. Thanks!

### CODE REVIEW

**Review by russjones — APPROVED** [review]

**Comment by russjones** [comment]
I can reproduce the `forwarding request denied` issue, let me hunt that down.

**Comment by russjones** [comment]
The reason the agent forwarding test was failing on macOS while passing on Linux was due to the path length restrictions on macOS for Unix sockets. From the the `UNIX(4)` manpage: `UNIX-domain addresses are variable-length file system pathnames of	at most 104 characters.`.

I shortened the UUID to the first 8 characters and also made the tests more cross platform friendly (used `os.TempDir` instead of `/tmp` because macOS temporary directories look something like `/var/folders/00/l7kftvrn2tx7cv0_w2x_c4_c0000gn/T/`).

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Comment by russjones** [comment]
@gravitational-jenkins test this please

File: lib/config/configuration.go [hunk 1]
```diff
@@ -608,6 +613,12 @@ func Configure(clf *CommandLineFlags, cfg *service.Config) error {
 		cfg.AuthServers = append(cfg.AuthServers, cfg.Auth.SSHAddr)
 	}
 
+	// add data_dir to the backend config:
+	if cfg.Auth.StorageConfig.Params == nil {
+		cfg.Auth.StorageConfig.Params = backend.Params{}
+	}
+	cfg.Auth.StorageConfig.Params["data_dir"] = cfg.DataDir
```
Comment (klizhentas) [inline lib/config/configuration.go]: @russjones this overwrites the user-supplied value at all times, what should not be the case. We should only overwrite the value if user haven't supplied the value. You can fix that yourself as @kontsevoy is OOO at the moment.

File: lib/srv/proxy.go [hunk 2]
```diff
@@ -247,7 +247,10 @@ func (t *proxySubsys) proxyToHost(
 	// if port is 0, it means the client wants us to figure out
 	// which port to use
 	useExactPort := len(t.port) > 0 && t.port != "0"
-	ips, _ := net.LookupHost(t.host)
+	log.Debugf("proxy connecting to host=%v port=%v, exact port=%v\n", t.host, t.port, useExactPort)
+
+	ips, err := net.LookupHost(t.host)
+	log.Debugf("host lookup (%v)=%v, err=%v", t.host, ips, err)
```
Comment (klizhentas) [inline lib/srv/proxy.go]: the problem with `err=` is that it will be 99% of the time equal to `err=nil` and grep catches it all the time, so we should try to make it less verbose even for debug.

File: lib/srv/sshserver.go [hunk 3]
```diff
@@ -878,7 +878,7 @@ func (s *Server) handleAgentForward(ch ssh.Channel, req *ssh.Request, ctx *ctx)
 	ctx.setAgent(clientAgent, authChan)
 
 	pid := os.Getpid()
-	socketPath := filepath.Join(os.TempDir(), fmt.Sprintf("teleport-agent-%v.socket", uuid.New()))
+	socketPath := filepath.Join(os.TempDir(), fmt.Sprintf("teleport-agent-%v.socket", uuid.New()[0:8]))
```
Comment (klizhentas) [inline lib/srv/sshserver.go]: @russjones it's a bit too late for me now, what are the chances of collision for this given your change?

**Review by klizhentas — CHANGES_REQUESTED** [review]
@russjones spotted some issues

File: lib/config/configuration.go (hunk 1 above)
Comment (kontsevoy) [inline lib/config/configuration.go]: @klizhentas there are no user-supplied values in "storage config" anymore [1]. Storage config are backend-specific configuration values and they are static-per-backend, with "data_dir" being a reserved word (needs to be reflected in backend developer README). So this behavior is as-designed.

[1] Bolt used to take a random JSON, so that's why you think there are user-supplied values. This is no longer true.

File: lib/srv/proxy.go (hunk 2 above)
Comment (kontsevoy) [inline lib/srv/proxy.go]: what do you mean by "grep catches it all the time"? adding error logging here helped me solve DNS-related issue on a customer POC.

File: lib/srv/sshserver.go (hunk 3 above)
Comment (kontsevoy) [inline lib/srv/sshserver.go]: just a comment: most UNIX tools use their own PID instead of UUID.

Comment (klizhentas) [inline lib/srv/sshserver.go]: they also create random temp dir though, not in root dir.

File: lib/srv/proxy.go (hunk 2 above)
Comment (klizhentas) [inline lib/srv/proxy.go]: your error logs look like `host lookup (%v)=%v err=nil`, so If I grep for gre logs err I will get all these false positives.

File: lib/config/configuration.go (hunk 1 above)
Comment (klizhentas) [inline lib/config/configuration.go]: I think users can supply Params["path"] for backend, at least what I have observed in configs and the code, so I don't quite understand the fix then. Why is it setting "data_dir" and not "path" like for example "boltdb" requires.

Comment (klizhentas) [inline lib/config/configuration.go]: My question basically is - can you explain to me how does this change fixes the case reported here:

https://github.com/gravitational/teleport/issues/867

File: lib/srv/sshserver.go (hunk 3 above)
Comment (russjones) [inline lib/srv/sshserver.go]: Two other options:

1. We create the socket under `/var/run/teleport/`. This way our socket files are on the same place on all platforms. We can name the socket itself `teleport-{random number}-{pid}.socket` and still be under the 104 character limit.

2. We do this instead: `ioutil.TempDir(os.TempDir(), "teleport-")` which will create `/tmp/teleport-699583643` on Linux and `/var/folders/00/l7kftvrn2tx7cv0_w2x_c4_c0000gn/T/teleport-699583643 ` on macOS. We can name the socket itself `teleport-{pid}.socket`.

Comment (klizhentas) [inline lib/srv/sshserver.go]: @russjones let's go with option 2. because it protects us from collisions on the implementation level - AFAIK golang checks for collisions

File: lib/srv/proxy.go (hunk 2 above)
Comment (kontsevoy) [inline lib/srv/proxy.go]: k, kill it. I'm not attached to it :)

File: lib/config/configuration.go (hunk 1 above)
Comment (klizhentas) [inline lib/config/configuration.go]: @russjones: @kontsevoy explained to me how it works, so this part lgtm, please fix the part with socket path and merge the whole thing

**Comment by russjones** [comment]
@klizhentas Made the changes you suggested, can you approve?

File: lib/srv/sshserver_test.go [hunk 4]
```diff
@@ -238,7 +239,8 @@ func (s *SrvSuite) TestAgentForward(c *C) {
 	_, err = io.WriteString(writer, fmt.Sprintf("printenv %v\n\r", teleport.SSHAuthSock))
 	c.Assert(err, IsNil)
 
-	re := regexp.MustCompile(`/tmp/[^\s]+`)
+	pattern := fmt.Sprintf(`%vteleport-[0-9]+[^\s]+`, os.TempDir())
+	re := regexp.MustCompile(pattern)
```
Comment (russjones) [inline lib/srv/sshserver_test.go]: This is not actually the line that has the problem, but it's the loop below:

```go
 	for i := 0; i < 3; i++ {
 		_, err = reader.Read(buf)
 		c.Assert(err, IsNil)
 		matches = re.FindStringSubmatch(string(buf))
 		if len(matches) != 0 {
 			break
 		}
 		time.Sleep(50 * time.Millisecond)
 	}
```

On Linux tests hang on the line `_, err = reader.Read(buf)`. Works fine on macOS.

Comment (russjones) [inline lib/srv/sshserver_test.go]: @klizhentas ^

Comment (klizhentas) [inline lib/srv/sshserver_test.go]: let me try to fix that

**Comment by russjones** [comment]
@klizhentas Tested your fix, works on macOS as well.

**Comment by klizhentas** [comment]
@russjones let's merge then

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Comment by russjones** [comment]
@gravitational-jenkins test this please

**Review by klizhentas — APPROVED** [review]
