### PR TITLE
Conditionally render User edit/delete actions in the web UI

### LINKED ISSUE #6885: Users Options box still present when no privileges
### Description
Even though you don't have any update/delete permissions both update and delete functionality is shown in the GUI

**What happened**:
Options box in Users list present

**What you expected to happen**:
Options box in Users list not present

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Login to cloud, create a role that only has list + read permission for users
2. Go to the Users menu with this user, the Options box is present with edit/delete/reset password
3. If pressing one of the options you will get a "permission denied" box

### Server Details
- Teleport Cloud

### PR DESCRIPTION
**Pull request by avatus**
This will only show the Edit and Reset options in the web UI if the viewing user has permissions to edit. This also hides the Create New User button because, although they can add a user, the action still fails as it tries to "reset" the user to get their first time login token. I thought about trying to decouple this but being able to create a user and not receive a link seems unproductive.

Delete is hidden if the user cannot delete, and the entire option box is removed if a users can't edit or delete

This does not affect the invite collaborators button/menu which emails the users their login info (as this is add only).
Screenshot 2024-12-02 at 10 18 14 AM
Screenshot 2024-12-02 at 10 18 17 AM
Screenshot 2024-12-02 at 10 36 22 AM

Closes https://github.com/gravitational/teleport/issues/6885

### CODE REVIEW

File: web/packages/teleport/src/Users/Users.tsx [hunk 1]
```diff
@@ -62,20 +64,30 @@ export function Users(props: State) {
...
-                intent="primary"
-                fill="border"
-                ml="auto"
-                width="240px"
-                onClick={onStartCreate}
+              <HoverTooltip
+                tipContent={
+                  canEditUsers
+                    ? ''
+                    : 'You do not have permission to edit users.'
```
Comment (ryanclark) [inline web/packages/teleport/src/Users/Users.tsx:76]: Should this be

```suggestion
                    : 'You do not have permission to create users.'
```

Comment (avatus) [reply web/packages/teleport/src/Users/Users.tsx:76]: techincally they can create, but the edit is required in the second step. I'm not sure which is better as the "edit" version is more correct, but its on the 'create' button.

Comment (avatus) [reply web/packages/teleport/src/Users/Users.tsx:76]: and i don't want to hide the button, because we don't want to hide features anymore, only display permission errors

Comment (ryanclark) [reply web/packages/teleport/src/Users/Users.tsx:76]: I think it should make sense from the user's perspective, i.e. I'm trying to create a user and don't have permissions, so I don't have permission to create users. Maybe this could be more vague, "You do not have enough permissions" or something better worded

We should indicate the missing permissions, I do this in TAG:

image

image

with a different message if they're able to edit roles themselves (maybe not needed)

image

cc @roraback

Comment (zmb3) [reply web/packages/teleport/src/Users/Users.tsx:76]: That popover looks great (and I agree we should show what permissions are missing), but it would be nice if TAG stuck to our design system so that the user's Teleport experience was consistent. We don't to my knowledge have anything in our design system that uses these colors in this way.

Comment (ryanclark) [reply web/packages/teleport/src/Users/Users.tsx:76]: I'll make a note to update the colours (I think that grey is just a default I haven't changed)

**Review by zmb3 — APPROVED** [review]

**Review by ryanclark — APPROVED** [review]
