### PR TITLE
[buddy] Truncate AssumeRole session name to API limits

### LINKED ISSUE #44833: Internal server error due to long AWS AssumeRole session name
Expected behavior:
I expect calls to AWS API via `tsh` to succeed (eg. `tsh aws s3 ls`) even when logged in to a leaf cluster via its root cluster.

Current behavior:
After logging in to a leaf cluster via its root cluster, I get an error when making an AWS API call via `tsh`, such as:
```
$ tsh aws s3 ls

An error occurred (500) when calling the ListBuckets operation (reached max retries: 2): Internal Server Error
ERROR: exit status 254
```

Running the same command with debug enabled:
```
$ tsh -d aws s3 ls
...
2024-07-30T16:59:32+01:00 WARN [LOCALPROX] "ERROR REPORT: Original Error: *awserr.requestError ValidationError: 1 validation error detected: Value &#39;remote-some.randomname@jumo.world-teleport.test-vocal-cougar.eu-dev.awsmmcn.private&#39; at &#39;roleSessionName&#39; failed to satisfy constraint: Member must have length less than or equal to 64\n\tstatus code: 400, request id: 2542a4b3-49c3-4c85-970b-f4ae10de6583 Stack Trace:\n\tgithub.com/gravitational/teleport/lib/utils/aws/signing.go:183 github.com/gravitational/teleport/lib/utils/aws.(*SigningService).SignRequest\n\tgithub.com/gravitational/teleport/lib/srv/app/aws/handler.go:168 github.com/gravitational/teleport/lib/srv/app/aws.(*signerHandler).serveCommonRequest\n\tgithub.com/gravitational/teleport/lib/srv/app/aws/handler.go:152 github.com/gravitational/teleport/lib/srv/app/aws.(*signerHandler).serveHTTP\n\tgithub.com/gravitational/teleport/lib/srv/app/aws/handler.go:129 github.com/gravitational/teleport/lib/srv/app/aws.(*signerHandler).ServeHTTP\n\tgithub.com/gravitational/teleport/lib/srv/app/connections_handler.go:369 github.com/gravitational/teleport/lib/srv/app.(*ConnectionsHandler).serveSession\n\tgithub.com/gravitational/teleport/lib/srv/app/connections_handler.go:446 github.com/gravitational/teleport/lib/srv/app.(*ConnectionsHandler).serveHTTP\n\tgithub.com/gravitational/teleport/lib/srv/app/connections_handler.go:701 github.com/gravitational/teleport/lib/srv/app.(*ConnectionsHandler).ServeHTTP\n\tgithub.com/gravitational/teleport/lib/auth/middleware.go:790 github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP\n\tgithub.com/gravitational/teleport/lib/httplib/httplib.go:104 github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1\n\tnet/http/server.go:2171 net/http.HandlerFunc.ServeHTTP\n\tgo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.51.0/handler.go:212 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP\n\tgo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.51.0/handler.go:73 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1\n\tnet/http/server.go:2171 net/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:3142 net/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2044 net/http.(*conn).serve\n\truntime/asm_amd64.s:1695 runtime.goexit\n\n\tUser Message: ValidationError: 1 validation error detected: Value &#39;remote-some.randomname@jumo.world-teleport.test-vocal-cougar.eu-dev.awsmmcn.private&#39; at &#39;roleSessionName&#39; failed to satisfy constraint: Member must have length less than or equal to 64\n\tstatus code: 400, request id: 2542a4b3-49c3-4c85-970b-f4ae10de6583" alpnproxy/local_proxy.go:284
```

Essentially, the error is:
> roleSessionName - failed to satisfy constraint: Member must have length less than or equal to 64

The [AWS AssumeRole documentation](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) describes this limit.

Looking at the source code: 
- When a user is a [remote user](https://github.com/gravitational/teleport/blob/master/lib/authz/permissions.go#L708), its identity username is [computed](https://github.com/gravitational/teleport/blob/v16.0.4/lib/services/user.go#L144) as `remote-LOCAL_USERNAME-LOCAL_CLUSTERNAME`. The logs above show the same. 
- The username is then propagated to the [AssumeRole options](https://github.com/gravitational/teleport/blob/v16.0.4/lib/utils/aws/credentials.go#L77) as a RoleSessionName([here](https://github.com/gravitational/teleport/blob/v16.0.4/lib/srv/app/cloud.go#L194) as well?). 
- In a trusted cluster setup, it's quite easy for the 64 characters limit to be exceeded given that it can include an email address and a hostname, besides the static prefix.
- Because there's no restriction in the session name applied by Teleport, the AWS API error is propagated to the user.

I am happy to open a PR, however I am not sure about the implications of applying some sort of truncation to the role session name given that it's meant to [associate CloudTrail events with Teleport users](https://github.com/gravitational/teleport/blob/v16.0.4/lib/srv/app/cloud.go#L193C6-L193C56). This possibly needs further consideration.

Bug details:
- Teleport version: 16.0.4 enterprise
- Recreation steps:
1. `tsh login leaf_cluster.example.com  --proxy=root.example.com`
2. `tsh app login aws_app --aws-role SomeIAMRole`
4. `tsh aws s3 ls`
- Debug logs: refer to `Current behavior`

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #44833

buddy PR:
- #44836

changelog: Fixed an issue AWS access fails when the username is longer than 64 characters

### CODE REVIEW

File: lib/srv/app/cloud.go [hunk 1]
```diff
@@ -191,7 +191,7 @@ func (c *cloud) getAWSSigninToken(ctx context.Context, req *AWSSigninRequest, en
 	options = append(options, func(creds *stscreds.AssumeRoleProvider) {
 		// Setting role session name to Teleport username will allow to
 		// associate CloudTrail events with the Teleport user.
-		creds.RoleSessionName = req.Identity.Username
+		creds.RoleSessionName = awsutils.TruncateRoleSessionName(req.Identity.Username)
```
Comment (codingllama) [inline lib/srv/app/cloud.go:194]: This is now truncated, which means that theoretically we can have "RoleSessionName" clashes if some names share the same 64-chars prefix.

Is this acceptable?

Should we mention that in the comment above?

File: lib/utils/aws/credentials.go [hunk 2]
```diff
@@ -74,7 +74,7 @@ func (g *credentialsGetter) Get(_ context.Context, request GetCredentialsRequest
 	logrus.Debugf("Creating STS session %q for %q.", request.SessionName, request.RoleARN)
 	return stscreds.NewCredentials(request.Provider, request.RoleARN,
 		func(cred *stscreds.AssumeRoleProvider) {
-			cred.RoleSessionName = request.SessionName
+			cred.RoleSessionName = TruncateRoleSessionName(request.SessionName)
```
Comment (codingllama) [inline lib/utils/aws/credentials.go:77]: Same remark about clashes here.

File: lib/srv/app/cloud.go (hunk 1 above)
Comment (greedy52) [reply lib/srv/app/cloud.go:194]: > This is now truncated, which means that theoretically we can have "RoleSessionName" clashes if some names share the same 64-chars prefix.

Theoretically yes. It's not common to have names over 64 chars. And even when that happens, they usually share the suffix, not the prefix. But agreed theoretically yes.

> Is this acceptable?

The main use for `RoleSessionName` is for Cloud Trail searching. Initially, I thought collisions are acceptable as Teleport also has audit logs for AWS access. Now thinking about it again, we can only record apis from `tsh aws`. We cannot record AWS Web Console so whatever users do there must be traced by Cloud Trail. I guess you can still reference our session start event against Cloud Trial time but it's unreliable (and cumbersome).

Alternatively, we can hash the username and use the hashed name for `RoleSessionName`. Then put the hashed name in the audit events for cross reference. Something similar to this:
https://github.com/gravitational/teleport/blob/7906e139522b26e5c75a9a2573b9065bd563208c/lib/srv/db/mysql/autousers.go#L428-L439
Well, theoretically hash can collide too =p

Comment (codingllama) [reply lib/srv/app/cloud.go:194]: I thought in similar lines to you - if the username is too long we could keep some of the prefix, hash the entire username and make the last N character the hash.

Up to you, I just wanted to make sure we had considered this.

> And even when that happens, they usually share the suffix, not the prefix

Makes sense. That makes it a bit better.

Comment (greedy52) [reply lib/srv/app/cloud.go:194]: @smallinsky what is your opinion on this? thanks 🙏

Comment (smallinsky) [reply lib/srv/app/cloud.go:194]: Agree, 

We can hash whole username but this make sessionName unfriendly for the reader. 

So I agree that test beast solution for the reader will be keep prefix add a sufix as username hash: 

Let's say that we have a following username 
`verylongcomplictedusernameoftheuserthatusesteleportthatexeeds64charaters@google.com`

so we can trim username like: 

`tp-altered-verylongcompl-61521eabd63c11160345c869abba1c53e59de79`

or just skip prefix: `verylongcomplicteduserna-61521eabd63c11160345c869abba1c53e59de79` 

that will be a bit more valuable for the reader instead of just random sha1 hash.

Comment (greedy52) [reply lib/srv/app/cloud.go:194]: > verylongcomplicateduserna-61521eabd63c11160345c869abba1c53e59de79

That's perfect. I will add a `role_session_name` field in audit events and save this value.

@joaoubaldo, as discussed, I will take it from here and update the changes in this PR.

Comment (marcoandredinis) [reply lib/srv/app/cloud.go:194]: I like that approach.
If it exceeds the max, then replace the last 8 or 16 chars with some hash of the full string.

Comment (greedy52) [reply lib/srv/app/cloud.go]: Updated. Decide to keep the entire 40byte of sha1.

File: api/proto/teleport/legacy/types/events/events.proto [hunk 3]
```diff
@@ -2745,6 +2745,13 @@ message AppSessionStart {
     (gogoproto.embed) = true,
     (gogoproto.jsontag) = ""
   ];
+
+  // AWS contains common AWS session information.
+  AWSSessionMetadata AWS = 9 [
```
Comment (smallinsky) [inline api/proto/teleport/legacy/types/events/events.proto:2750]: Can we make it more generic like 
```suggestion
  AWSMetadata AWS = 9 [
```

I wonder what other fields can be added to AWSSessionMetadata, where AWSMetadata would be more flexible and in the case of other AWS fields not related to AWSSession context  I think that  the  AWSMetadata it will be a better fit.

**Review by smallinsky — APPROVED** [review]

File: api/proto/teleport/legacy/types/events/events.proto [hunk 4]
```diff
@@ -2874,6 +2881,13 @@ message AppSessionRequest {
   ];
 }
 
+// AWSSessionMetadata contains extra AWS metadata of an AWS session.
+message AWSSessionMetadata {
+  // AWSRoleSessionName is used to specify the username when assuming the AWS
+  // IAM role.
+  string AWSRoleSessionName = 1 [(gogoproto.jsontag) = "aws_role_session_name,omitempty"];
```
Comment (codingllama) [inline api/proto/teleport/legacy/types/events/events.proto:2888]: Could this be just role_session_name?

Also, could we use "proper" proto style for new messages?

- https://protobuf.dev/programming-guides/style/#message-field-names

File: lib/auth/sessions.go [hunk 5]
```diff
@@ -792,3 +799,13 @@ func (a *Server) CreateSAMLIdPSession(ctx context.Context, req types.CreateSAMLI
 
 	return session, nil
 }
+
+// guessAWSRoleSessionName make an educated guess of the role session name.
+func guessAWSRoleSessionName(localClusterName string, req NewAppSessionRequest) string {
+	// App service uses the Teleport username as the RoleSessionName.
+	user := req.User
+	if req.ClusterName != "" && localClusterName != req.ClusterName {
+		user = services.UsernameForRemoteCluster(req.User, localClusterName)
```
Comment (codingllama) [inline lib/auth/sessions.go:808]: This one doesn't need to be trimmed?

File: lib/auth/sessions.go [hunk 6]
```diff
@@ -623,6 +624,12 @@ func (a *Server) CreateAppSessionFromReq(ctx context.Context, req NewAppSessionR
 			AppPublicAddr: req.PublicAddr,
 			AppName:       req.AppName,
 		},
+		AWSSessionMetadata: apievents.AWSSessionMetadata{
+			// Make an educated guess of the role session name. We have to
+			// guess here since this event is emitted on Auth instead of the
+			// App service that issues the actual AssumeRole call.
+			AWSRoleSessionName: guessAWSRoleSessionName(clusterName.GetClusterName(), req),
```
Comment (codingllama) [inline lib/auth/sessions.go:631]: Guessing a value for audit makes me uneasy. The docs on AWSSessionMetadata make no mention of this being guessed either.

File: lib/auth/sessions_test.go [hunk 7]
```diff
@@ -83,3 +84,35 @@ func TestServer_CreateWebSessionFromReq_deviceWebToken(t *testing.T) {
 		}
 	})
 }
+
+func Test_guessAWSRoleSessionName(t *testing.T) {
```
Comment (codingllama) [inline lib/auth/sessions_test.go:88]: nit: Test naming.

```suggestion
func TestGuessAWSRoleSessionName(t *testing.T) {
```

File: lib/auth/sessions_test.go [hunk 8]
```diff
@@ -83,3 +84,35 @@ func TestServer_CreateWebSessionFromReq_deviceWebToken(t *testing.T) {
...
+				NewWebSessionRequest: NewWebSessionRequest{
+					User: "raimundo.oliveira@abigcompany.com",
+				},
+				ClusterName: "leaf.teleport.abigcompany.com",
+			},
+			expected: "remote-raimundo.oliveir-8fe1f87e599b043e6a0108338feee3f111e9c1e4",
+		},
+	} {
+		t.Run(fmt.Sprintf("%s@%s", tt.request.User, tt.request.ClusterName), func(t *testing.T) {
+			require.Equal(t, tt.expected, guessAWSRoleSessionName(localClusterName, tt.request))
```
Comment (codingllama) [inline lib/auth/sessions_test.go:115]: Could we test this without reaching for the private function?

File: lib/auth/sessions_test.go [hunk 9]
```diff
@@ -83,3 +84,35 @@ func TestServer_CreateWebSessionFromReq_deviceWebToken(t *testing.T) {
...
+		expected string
+	}{
+		{
+			request: NewAppSessionRequest{
+				NewWebSessionRequest: NewWebSessionRequest{
+					User: "raimundo.oliveira@abigcompany.com",
+				},
+				ClusterName: "teleport.abigcompany.com",
+			},
+			expected: "raimundo.oliveira@abigcompany.com",
```
Comment (codingllama) [inline lib/auth/sessions_test.go:102]: Should we test with a local username that gets hashed too, in addition to this one?

File: lib/utils/aws/aws.go [hunk 10]
```diff
@@ -484,3 +490,30 @@ func iamResourceARN(partition, accountID, resourceType, resourceName string) str
...
+	hash.Write([]byte(roleSessionName))
+	hex := hex.EncodeToString(hash.Sum(nil))
+
+	// "1" for the delimiter.
+	keepPrefixIndex := MaxRoleSessionName - len(hex) - 1
+
+	if keepPrefixIndex < 0 {
+		// This should not happen since sha1 length and MaxRoleSessionName are
+		// both constant.
+		ret = hex[:MaxRoleSessionName]
```
Comment (codingllama) [inline lib/utils/aws/aws.go:512]: Hypothetically, if we hit this, `MaxRoleSessionName` could still be larger than `len(hex)`, which would make this line panic.

I would remove this branch and keep the suggestion above.

File: lib/utils/aws/aws.go [hunk 11]
```diff
@@ -484,3 +490,30 @@ func iamResourceARN(partition, accountID, resourceType, resourceName string) str
...
+	if len(roleSessionName) <= MaxRoleSessionName {
+		return roleSessionName
+	}
+
+	hash := sha1.New()
+	hash.Write([]byte(roleSessionName))
+	hex := hex.EncodeToString(hash.Sum(nil))
+
+	// "1" for the delimiter.
+	keepPrefixIndex := MaxRoleSessionName - len(hex) - 1
```
Comment (codingllama) [inline lib/utils/aws/aws.go:507]:
```suggestion
	keepPrefixIndex := MaxRoleSessionName - len(hex) - 1
	// Sanity check. Should never happen.
	if keepPrefixIndex < 0 {
		keepPrefixIndex = 0
	}
```

File: lib/utils/aws/aws.go [hunk 12]
```diff
@@ -484,3 +490,30 @@ func iamResourceARN(partition, accountID, resourceType, resourceName string) str
...
+// when the original role session name is greater than AWS character limit
+// (64).
+func MaybeHashRoleSessionName(roleSessionName string) (ret string) {
+	if len(roleSessionName) <= MaxRoleSessionName {
+		return roleSessionName
+	}
+
+	hash := sha1.New()
+	hash.Write([]byte(roleSessionName))
+	hex := hex.EncodeToString(hash.Sum(nil))
```
Comment (codingllama) [inline lib/utils/aws/aws.go:504]: Suggestion: Make the hash smaller? Aesthetic only.

```suggestion
	const hashLen = 10
	hex := hex.EncodeToString(hash.Sum(nil))[:hashLen]
```

**Review by codingllama — COMMENTED** [review]
It seems like this exploded in scope a bit with the audit and proto changes. I would do audit separately, but happy to keep it here if you prefer.

**Comment by greedy52** [comment]
> Guessing a value for audit makes me uneasy.

I feel the same but it's not an easy fix. I decided to drop the audit from the PR and make the fix separately. Another issue with current design (how the session event is sent) is the event happens on the root but not on the leaf.

**Review by codingllama — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]
