### PR TITLE
fix: supports newline and whitespace in motd

### LINKED ISSUE #28201: Support multiline MOTD in UI
Expected behavior:
Should support multiline MOTD. More details reported here: https://github.com/gravitational/teleport/pull/27922#issuecomment-1594955385

Current behavior:
Multiline is not supported

Bug details:
This issue hits MOTD feature added to v13, v12 and v11.

### PR DESCRIPTION
**Pull request by flyinghermit**
- renders newline and whitespace as configured.
- renders vertical scrollbar for longer message.
- shows "acknowledge" button at the end of the scroll so that users can see all motd message before acknowledging.
- caps width to `600px`, height to `500px`

closes https://github.com/gravitational/teleport/issues/28201

### CODE REVIEW

**Comment by sshahcodes** [comment]
screenshots:
Screenshot 2023-07-05 at 3 49 06 PM
Screenshot 2023-07-05 at 3 51 49 PM
Screenshot 2023-07-05 at 3 55 03 PM

**Review by zmb3 — APPROVED** [review]

File: web/packages/teleport/src/Login/Motd/Motd.tsx [hunk 1]
```diff
@@ -15,24 +15,43 @@ limitations under the License.
...
 }
 
 type Props = {
   message: string;
   onClick(): void;
 };
+
+const StyledCard = styled(Card)`
+  overflow-y: auto;
+  max-width: 600px;
```
Comment (ryanclark) [inline web/packages/teleport/src/Login/Motd/Motd.tsx:50]: Should this have a min-width too?

Comment (sshahcodes) [reply web/packages/teleport/src/Login/Motd/Motd.tsx:50]: (not a css pro)
I tried `min-width` but it didn't have any affect. Specifying a default `width` prevented `max-width`. Any possible issue if we don't include `min-width` here and leave it as is?

**Review by ryanclark — APPROVED** [review]
