### PR TITLE
fix X-Forwarded-For HTTP header not getting passed in app access requests

### LINKED ISSUE #44569: Application access should include `X-Forwarded-For` (regression)
### Expected behavior:

Teleport should send the `X-Forwarded-For` header in HTTP requests sent to Application Access backends.

### Current behavior:

This appears to be a regression. Teleport has had this expected behavior for a long time. 15.4.4 was tested and has the correct behavior. 15.4.9 is Problematically omitting the header.

I suspect https://github.com/gravitational/teleport/pull/43368 accidentally introduced this regression.

### Bug details:
- **Teleport version**: observed in 15.4.9 and 16.0.4
- **Recreation steps**:
  - Set up a 15.4.4 Teleport Cluster with an `app_service` with `debug_app` enabled.
  - navigate to the dumper app and view the header is present.
  - Upgrade to 15.4.9 and revisit the dumper app. Note that the header is absent.
- **Debug logs**: 

15.4.4:

```plaintext
X-Forwarded-For: 203.0.113.183
X-Forwarded-Host: dumper.old.example.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: eps-teleport-app-0
X-Forwarded-Ssl: on
X-Real-Ip: 203.0.113.183
```

15.4.9:

```plaintext
X-Forwarded-Host: dumper.new.example.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: teleport-app-1
X-Forwarded-Ssl: on
X-Real-Ip: 203.0.113.183
```

---

Many applications require the X-Forwarded-For header, or may be configured to expect that it is there. I'll add a comment with details about pgAdmin or any other app behaviors that we find due to this.

### PR DESCRIPTION
**Pull request by capnspacehook**
I didn't realize that `httputil` doesn't set `X-Forwarded-For` when `ReverseProxy.Rewrite` is set: https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L435

Fixes https://github.com/gravitational/teleport/issues/44569.

changelog: fixed Application Access regression where an HTTP header wasn't set in forwarded requests

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

**Comment by capnspacehook** [comment]
Sure just kicked off a dev build

File: lib/httplib/reverseproxy/rewriter.go [hunk 1]
```diff
@@ -126,9 +126,11 @@ func maybeSetXRealIP(req *http.Request) {
 // maybeSetForwarded sets X-Forwarded-* headers if it is not set to the
 // scheme of the request.
 func maybeSetForwarded(req *http.Request) {
-	// We need to delete the value because httputil.ReverseProxy
-	// appends to the existing value.
-	req.Header.Del(XForwardedFor)
+	// Set X-Forwarded-For since net/http/httputil.ReverseProxy won't
+	// do this when Rewrite is set.
+	if clientIP, _, err := net.SplitHostPort(req.RemoteAddr); err == nil {
+		req.Header.Set("X-Forwarded-For", clientIP)
```
Comment (zmb3) [inline lib/httplib/reverseproxy/rewriter.go:132]:
```suggestion
		req.Header.Set(XForwardedFor, clientIP)
```

**Review by programmerq — APPROVED** [review]
I deployed the test build into my lab. I was able to see that the X-Forwarded-For header is again present, as expected.

I first deployed this dev build image to my teleport-cluster release. That alone didn't fix the problem. Once I deployed this image to my teleport-kube-agent release, the header shows up again.

I also deployed the dev build to another lab cluster's teleport-kube-agent release where the original problem with pgadmin had been seen. It fixed the problem there too.

LGTM!

**Review by tigrato — APPROVED** [review]
