### PR TITLE
Fix logging, collect status of forked processes

### LINKED ISSUE #1776: teleport start default output
## Problem 1

Our quickstart promises this output:

```
$ mkdir -p /var/lib/teleport
$ sudo teleport start

[AUTH]  Auth service is starting on 0.0.0.0:3025
[PROXY] Reverse tunnel service is starting on 0.0.0.0:3024
[PROXY] Web proxy service is starting on 0.0.0.0:3080
[PROXY] SSH proxy service is starting on 0.0.0.0:3023
[SSH]   Service is starting on 0.0.0.0:3022
```

Notice the absence of `--debug` flag.
2.5 is giving this:

```bash
WARN [PROCESS]   No TLS Keys provided, using self signed certificate. service/service.go:1474
WARN [AUTH]      Parameter advertise_ip is not set for this auth server. Trying to guess the IP this server can be reached at: 192.168.122.1:3025. service/service.go:684
```

## Problem 2

```
$ tctl users add ekontsevoy
user "User(name=ekontsevoy, roles=[], identities=[])" already exists
```

Should be "user ekontsevoy already exists"

## Proposal

* When in "zero-configuration mode" (i.e. no YAML config provided) Teleport should start with `ERROR` log level (so those warnings won't confuse first-timers).
* Default stderr output should be as before.
* Make the warning more readable / less verbose for `advertise_ip` (Ev: I'll update the text myself)

### LINKED ISSUE #1785: regular/sshserver.go errors after v2.4.2 -> v2.5.1 upgrade
**What happened**:
Stream of errors every few minutes in systemd logs for teleport:
```
Mar 16 12:30:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
Mar 16 12:51:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
Mar 16 14:03:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
Mar 16 14:09:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
Mar 16 14:13:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
Mar 16 14:20:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
Mar 16 14:37:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
Mar 16 14:58:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
Mar 16 15:09:01 enterprise.whiteforest.info teleport[10287]: ERRO             waitid: no child processes regular/sshserver.go:510
Mar 16 15:22:01 enterprise.whiteforest.info teleport[10287]: ERRO             wait: no child processes regular/sshserver.go:510
```

Using teleport config file:
```
teleport:
    nodename: enterprise.whiteforest.info
    data_dir: /var/lib/teleport
    advertise_ip: 10.10.0.139
    auth_servers:
        - localhost:3025
    connection_limits:
        max_connections: 1000
        max_users: 250
    log:
        output: stderr
        severity: ERROR
    storage:
        type: bolt
auth_service:
    enabled: yes
    dynamic_config: false
    authentication:
        type: local
        second_factor: u2f
        u2f:
            app_id: https://teleport.whiteforest.info
            facets:
            - https://teleport.whiteforest.info
            - https://teleport.whiteforest.info:443
    listen_addr: 0.0.0.0:3025
    cluster_name: "whiteforest.info"
    session_recording: "off"
ssh_service:
    enabled: yes
    listen_addr: 0.0.0.0:3022
    labels:
        role: master
    commands:
    - name: hostname
      command: [/bin/hostname]
      period: 1m0s
    - name: arch
      command: [/bin/uname, -p]
      period: 1h0m0s
proxy_service:
    enabled: no
    listen_addr: 0.0.0.0:3023
    tunnel_listen_addr: 0.0.0.0:3024
    web_listen_addr: 0.0.0.0:3080
```

**What you expected to happen**:
Didn't expect these errors.

**How to reproduce it (as minimally and precisely as possible)**:
Upgraded cluster from v2.4.2 -> v2.5.1

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.5.1
- Tsh version (use `tsh version`): N/A
- OS (e.g. from /etc/os-release): Gentoo

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

### PR DESCRIPTION
**Pull request by klizhentas**
fixes #1785, fixes #1776

This commit fixes several issues with output:

First teleport start now prints output
matching quickstart guide and sets default
console logging to ERROR.

SIGCHLD handler now only collects
processes PID forked during live restart
to avoid confusing other wait calls that
have no process status to collect any more.

### CODE REVIEW

**Review by r0mant — APPROVED** [review]

File: lib/service/service.go [hunk 1]
```diff
@@ -728,6 +733,8 @@ func (process *TeleportProcess) initAuthService() error {
 	})
 
 	process.RegisterFunc("auth.tls", func() error {
+		utils.Consolef(cfg.Console, "[AUTH]  Auth service is starting on %v.", cfg.Auth.SSHAddr.Addr)
```
Comment (russjones) [inline lib/service/service.go]: These log lines will be misaligned because they don't use the new component logger we have.

Should be easy to fix because `utils.Consolf` jus writes to a writer and then to the logs: https://github.com/gravitational/teleport/blob/v2.5.2/lib/utils/cli.go#L140-L148

File: lib/service/signals.go [hunk 2]
```diff
@@ -367,11 +366,65 @@ func (process *TeleportProcess) forkChild() error {
...
+func (process *TeleportProcess) collectStatuses() {
+	pids := process.getForkedPIDs()
+	if len(pids) == 0 {
+		return
+	}
+	for _, pid := range pids {
+		var wait syscall.WaitStatus
+		rpid, err := syscall.Wait4(pid, &wait, syscall.WNOHANG, nil)
+		if err != nil {
+			log.Errorf("Wait call failed: %v.", err)
```
Comment (russjones) [inline lib/service/signals.go]: `continue` after this line.

File: lib/service/signals.go [hunk 3]
```diff
@@ -367,11 +366,65 @@ func (process *TeleportProcess) forkChild() error {
...
+
+// if forked teleport process exited with an error during graceful
+// restart, parent process has to collect the child process status
+// otherwise the child process will become a zombie process.
+// Callid Wait4(-1) trying to collect status of **any** child
+// leads to warnings in logs, because other parts of go could
+// have tried to collect the status of this process.
+// Instead this logic tries to collect statuses of the processes
+// forked during restart procedure.
+func (process *TeleportProcess) collectStatuses() {
```
Comment (russjones) [inline lib/service/signals.go]: Comment should start with `collectStatuses`.

**Review by russjones — APPROVED** [review]
Couple of minor issues, otherwise looks good.

**Review by russjones — APPROVED** [review]
