### PR TITLE
Machine ID: Fix `tshwrap` destination dir handling

### LINKED ISSUE #48107: Machine ID: `tbot proxy` and `tbot db connect` should be able to load config from the CLI
Expected behavior:

`tbot db connect --destination-dir=/foo/bar ...` should work as expected

Current behavior:

Due to CLI changes `tshwrap.GetDestinationDirectory()` fails with the following:

```
ERROR REPORT:
Original Error: *trace.BadParameterError either --destination-dir or a config file containing an output or service must be specified
Stack Trace:
	github.com/gravitational/teleport/lib/tbot/tshwrap/wrap.go:153 github.com/gravitational/teleport/lib/tbot/tshwrap.GetDestinationDirectory
	github.com/gravitational/teleport/tool/tbot/db.go:43 main.onDBCommand
	github.com/gravitational/teleport/tool/tbot/main.go:108 main.Run.func5
	github.com/gravitational/teleport/lib/tbot/cli/cli.go:122 github.com/gravitational/teleport/lib/tbot/cli.(*genericExecutorHandler[...]).TryRun
	github.com/gravitational/teleport/tool/tbot/main.go:256 main.Run
	github.com/gravitational/teleport/tool/tbot/main.go:50 main.main
	runtime/proc.go:272 runtime.main
	runtime/asm_arm64.s:1223 runtime.goexit
User Message: either --destination-dir or a config file containing an output or service must be specified
```

`tshwrap.GetDestinationDirectory()` relied on old behavior where a destination would be initialized unconditionally if `--destination-dir` was set. That flag is now deprecated, and we only initialize a destination for commands that explicitly use one so one won't just be present on the generated `BotConfig` (since it can't make sense without knowing what service said destination is a part of).

`GetDestinationDirectory()` doesn't really need to be aware of any of this, though - it just needs a path. It can instead do something like:
* If a config file is specified, and `--destination-dir` is specified, use that destination path
* Else if only `--destination-dir` is specified, just use that path
* Else if only a config is specified, and only one destination is defined, use that path
* Else raise an error

This also affects `tbot proxy`

Bug details:
- Teleport version: v17.0.0
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by timothyb89**
Recent CLI handling changes broke destination dir resolution for commands that use `tshwrap.GetDestinationDir()` to resolve destinations from either the CLI or config file.

The old behavior depends on implicit creation of an identity service if `--destination-dir` was provided on the CLI and no config file is loaded. We now no longer make this assumption and prefer to only resolve explicit configurations, so this tweaks
`tshwrap.GetDestinationDir()` to explicitly handle the CLI parameter rather than hoping it appears in the generated config.

While this is legacy functionality, it's not slated for removal in v17. Most users should still prefer to use the new app and database tunnel services wherever possible.

Fixes #48107

### CODE REVIEW

File: lib/tbot/tshwrap/wrap.go [hunk 1]
```diff
@@ -130,22 +130,28 @@ type destinationHolder interface {
...
 		if v, ok := svc.(destinationHolder); ok {
 			destinationHolders = append(destinationHolders, v)
 		}
 	}
-	// WARNING:
-	// This code is dependent on some unexpected "behavior" in
-	// config.FromCLIConf() - when users provide --destination-dir then all
-	// outputs configured in the YAML file are overwritten by an identity
-	// output with a directory destination with a path of --destination-dir.
-	// See: https://github.com/gravitational/teleport/issues/27206
```
Comment (timothyb89) [inline lib/tbot/tshwrap/wrap.go:148]: I removed this warning, I think #27206 was more or less resolved after this and #47130?

**Review by strideynet — APPROVED** [review]

**Review by vapopov — APPROVED** [review]
