### PR TITLE
Fix test-time fake clock race condition

### LINKED ISSUE #60796: `TestDatabaseRootLeafIdleTimeout` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/18939984027/job/54076098158?pr=60791#step:6:23028

#### Relevant snippet

```
      fixture.go:149: 
          	Error Trace:	/__w/teleport/teleport/integration/db/fixture.go:149
          	            				/__w/teleport/teleport/integration/db/fixture.go:433
          	            				/__w/teleport/teleport/integration/db/fixture.go:369
          	            				/__w/teleport/teleport/integration/db/db_integration_test.go:464
          	Error:      	Received unexpected error:
          	            	timed out, only 0/3 events received. received: [], expected: [DatabasesIdentity DatabasesReady TeleportReady]
          	Test:       	TestDatabaseRootLeafIdleTimeout
```

### PR DESCRIPTION
**Pull request by Tener**
Fix the test-specific race condition in `StartMonitor()` where tests using fake clocks could fail intermittently. 

The issue occurred when `clock.Advance()` was called immediately after `StartMonitor()` returned - the monitor goroutine might not have registered its idle timeout timer yet, causing the clock advance to have no effect.

`StartMonitor()` now waits for the idle timeout timer to be registered before returning.

To reproduce, run `TestFakeClockCanSafelyAdvance` with commented out `<-ready` line.

Fixes #60796.

### CODE REVIEW

**Review by bernardjkim — APPROVED** [review]

File: lib/srv/monitor.go [hunk 1]
```diff
@@ -309,16 +309,20 @@ func StartMonitor(cfg MonitorConfig) error {
...
 
+	// Wait for the monitor goroutine to register its idle timeout timer before
+	// returning, so callers can safely advance fake clocks after StartMonitor.
+	ready := make(chan struct{})
 	go func() {
-		w.start(lockWatch)
+		w.start(lockWatch, ready)
 		if w.MonitorCloseChannel != nil {
-			// Non blocking send to the close channel.
+			// Non-blocking send to the close channel.
```
Comment (zmb3) [inline lib/srv/monitor.go:318]: Hmm, usually I'd expect something referred to as a "close channel" to be `close()`d when we're done with it as opposed to conditionally written to.

Comment (Tener) [reply lib/srv/monitor.go:318]: I guess this way you can pass the same channel to multiple producers yet still consume the outputs in a single select? 

But I agree this is bit unusual.

**Review by zmb3 — APPROVED** [review]
