### PR TITLE
Fix user mismatch in postgres backend

### LINKED ISSUE #12221: Postgres backend always uses system username to connect
### Description

**What happened**: When using the new Postgres backend, there's no way to specify the username to use to connect to the database.

1) Issue a client certificate with `CN=teleport`:

```
root@artemis:/var/lib/teleport# openssl x509 -in /var/lib/teleport/postgresql-client.crt -noout -text | grep Subject:
        Subject: C = CA, ST = NS, L = Halifax, O = zeus.home.lan, CN = teleport
```

2. Add a `teleport` user to Postgres:

```
postgres=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 teleport  | Create DB                                                  | {}
```

3. Set up Teleport like this:

```yaml
teleport:
  storage:
    type: postgres
    addr: "zeus.home.lan:5432"
    database: "teleport"
    tls:
      client_cert_file: "/var/lib/teleport/postgresql-client.crt"
      client_key_file: "/var/lib/teleport/postgresql-client.key"
      ca_file: "/var/lib/teleport/postgresql-ca.crt"
```

When doing this, you get an error when trying to connect (presumably because Teleport here runs as `root` and there's no way for me to override the database user):
```
2022-04-25T18:54:54-03:00 DEBU [PROC:1]    Using postgres backend. service/service.go:3763

ERROR REPORT:
Original Error: *trace.BadParameterError failed to verify &#34;teleport&#34; database exists: failed to connect to `host=zeus.home.lan user=root database=postgres`: server error (FATAL: certificate authentication failed for user &#34;root&#34; (SQLSTATE 28000))
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/backend/postgres/driver.go:112 github.com/gravitational/teleport/lib/backend/postgres.(*pgDriver).maybeCreateDatabase
	/go/src/github.com/gravitational/teleport/lib/backend/postgres/driver.go:65 github.com/gravitational/teleport/lib/backend/postgres.(*pgDriver).open
	/go/src/github.com/gravitational/teleport/lib/backend/postgres/driver.go:52 github.com/gravitational/teleport/lib/backend/postgres.(*pgDriver).Open
	/go/src/github.com/gravitational/teleport/lib/backend/sqlbk/backend.go:52 github.com/gravitational/teleport/lib/backend/sqlbk.newWithConfig
	/go/src/github.com/gravitational/teleport/lib/backend/sqlbk/backend.go:38 github.com/gravitational/teleport/lib/backend/sqlbk.New
	/go/src/github.com/gravitational/teleport/lib/backend/postgres/backend.go:59 github.com/gravitational/teleport/lib/backend/postgres.New
	/go/src/github.com/gravitational/teleport/lib/service/service.go:3779 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthStorage
	/go/src/github.com/gravitational/teleport/lib/service/service.go:1108 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
	/go/src/github.com/gravitational/teleport/lib/service/service.go:781 github.com/gravitational/teleport/lib/service.NewTeleport
	/go/src/github.com/gravitational/teleport/e/tool/teleport/process/process.go:67 github.com/gravitational/teleport/e/tool/teleport/process.NewTeleport
	/go/src/github.com/gravitational/teleport/lib/service/service.go:505 github.com/gravitational/teleport/lib/service.Run
	/go/src/github.com/gravitational/teleport/e/tool/teleport/main.go:27 main.main
	/opt/go/src/runtime/proc.go:255 runtime.main
	/opt/go/src/runtime/asm_arm64.s:1133 runtime.goexit
User Message: initialization failed
	failed to verify &#34;teleport&#34; database exists: failed to connect to `host=zeus.home.lan user=root database=postgres`: server error (FATAL: certificate authentication failed for user &#34;root&#34; (SQLSTATE 28000))
```

Making a manual connection and overriding the user in the command to `teleport` works fine:
```
root@artemis:~# psql "dbname=postgres host=zeus.home.lan port=5432 user=teleport sslcert=/var/lib/teleport/postgresql-client.crt sslkey=/var/lib/teleport/postgresql-client.key sslrootcert=/var/lib/teleport/postgresql-ca.crt sslmode=verify-full"
psql (12.9 (Ubuntu 12.9-0ubuntu0.20.04.1), server 13.4)
WARNING: psql major version 12, server major version 13.
         Some psql features might not work.
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=>
```

**What you expected to happen**: Either:
- the database username should be inferred from the common name on the client certificate
- there should be a `teleport.storage.user` key in `/etc/teleport.yaml` to allow a database username to be specified

### Reproduction Steps
See above.

### Server Details
- Teleport version (run `teleport version`): `Teleport Enterprise v9.1.0 git:v9.1.0-0-g4d9708f85 go1.17.9`

### PR DESCRIPTION
**Pull request by jimbishopp**
Always set the user field of the database connection string to the same user defined in the CommonName field of the client certificate.

The pgx library always includes a user field in the connection string and defaults to $USER. The database connection will fail when $USER is not the same as the value defined in the CommonName field of the client certificate. 

Fixes: #12221

### CODE REVIEW

File: lib/backend/postgres/driver.go [hunk 1]
```diff
@@ -61,6 +63,14 @@ func (d *pgDriver) open(ctx context.Context, u *url.URL) (sqlbk.DB, error) {
 	}
 	connConfig.Logger = d.sqlLogger
 
+	// extract the user from the first client certificate in TLSConfig.
+	if connConfig.TLSConfig != nil {
+		connConfig.User, err = tlsConfigUser(connConfig.TLSConfig)
+		if err != nil {
+			return nil, trace.Wrap(err)
```
Comment (r0mant) [inline lib/backend/postgres/driver.go:70]: Should we treat this as a non-critical error and fallback to default behavior if CN doesn't include the username? Maybe log a warning.

**Review by r0mant — APPROVED** [review]

File: lib/backend/postgres/driver.go (hunk 1 above)
Comment (jimbishopp) [reply lib/backend/postgres/driver.go:70]: Probably not. Client certs are required for the PG backend, so the default behavior is to include the username in the CN field. FYI the nil check for TLSConfig is really for tests - the default for tests is no TLS.

That said, the error message as the code is currently written is a bit cryptic when the CN is empty: no PostgreSQL user name specified in startup packet.  Maybe it would be better to detect an empty CN field and provide a more useful error message.

Comment (jimbishopp) [reply lib/backend/postgres/driver.go:70]: Probably not. Client certs are required for the PG backend, so the default behavior assumes the username is included in the CN field. FYI the nil check for TLSConfig is really for tests - the default for tests is no TLS.

If the cert's CN is empty and we allow the User field in the connection string to be set by $USER or $PGUSER, then the error message will be:  certificate authentication failed for user "jim"; which is a little confusing.

That said, the error message as the code is currently written is a bit cryptic when the CN is empty: no PostgreSQL user name specified in startup packet. Maybe it would be better to detect an empty CN field and provide a more useful error message.

Comment (jimbishopp) [reply lib/backend/postgres/driver.go:70]: Added a better error message.

**Review by smallinsky — APPROVED** [review]

**Review by webvictim — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
bot
