### PR TITLE
Make Web Add User prompt for MFA just once

### LINKED ISSUE #37159: "Access denied" when inviting users to Teleport v15 Cloud instance
Expected behavior: When adding a new user to an existing Cloud cluster by their email via the Web UI, a user is created and an invite is sent to their email.

Current behavior: When inviting users to an existing Teleport Cloud cluster with version v15, the user gets created, but the invitation email does not get sent, and the Web UI shows an "access denied" message.

Screenshot 2024-01-24 at 14 03 48

Bug details:

Teleport version: v15.0.0-alpha.5
MFA type: FIDO2 physical (YubiKey 5C)
Deployment type: Cloud (dev environment)
Browser: Firefox v121.0.1

Browser dev tools show an error response to an HTTP request to `https://<CLUSTERURL>/v1/enterprise/cloud/teleportinvite`:

```
HTTP/1.1 403 Forbidden
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Expires: 0
Pragma: no-cache
Referrer-Policy: strict-origin
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
Date: Wed, 24 Jan 2024 11:48:16 GMT
Content-Length: 59

{
    "error": {
        "message": "access denied"
    }
}
```

Auth server log:
```
{"caller":"authz/permissions.go:1273","component":null,"level":"warning","message":"MFA response validation failed: \"/web/users/justinas@goteleport.com/webauthnsessiondata/login\" is not found","timestamp":"2024-01-24T11:50:36Z"}
```

MFA using the same method works otherwise.

### PR DESCRIPTION
**Pull request by Joerger**
Similar to https://github.com/gravitational/teleport/pull/36997, this PR updates adding a user from the WebUI to perform the admin action MFA ceremony upfront, allowing reuse so `CreateUser` and `CreateResetPasswordToken` only require one prompt.

This PR is also a pre-req for other similar PRs since it adds the `webauthnResponse` argument to `post/put/delete` requests.

### CODE REVIEW

File: web/packages/teleport/src/services/auth/auth.ts [hunk 1]
```diff
@@ -315,15 +302,53 @@ const auth = {
...
+    if (isMFARequiredRequest) {
+      try {
+        const isMFARequired = await checkMfaRequired(isMFARequiredRequest);
+        if (!isMFARequired.required) {
+          return;
+        }
+      } catch {
+        // checking MFA requirement for admin actions is not supported by old
+        // auth servers, we expect an error instead. In this case, assume MFA is
+        // not required. Callers should fallback to retrying with MFA if needed.
```
Comment (ryanclark) [inline web/packages/teleport/src/services/auth/auth.ts:322]: Can you check for that specific error instead of ignoring all errors?

File: web/packages/teleport/src/Users/useUsers.ts [hunk 2]
```diff
@@ -82,11 +83,21 @@ export default function useUsers({
     });
   }
 
-  function onCreate(u: User) {
+  async function onCreate(u: User) {
+    const webauthnResponse = await auth.getWebauthnResponseForAdminAction(
+      'CreateUser',
```
Comment (ryanclark) [inline web/packages/teleport/src/Users/useUsers.ts:88]: Similar to the other PR, I think we should have `AdminAction.CREATE_USER` or something

**Comment by Joerger** [comment]
@rudream @ryanclark Sorry for the short timeline but could you please review today or tomorrow? I have multiple fixes depending on this change that ought to get into v15.

File: web/packages/teleport/src/config.ts [hunk 3]
```diff
@@ -381,6 +381,10 @@ const cfg = {
     return cfg.auth.allowPasswordless;
   },
 
+  isAdminActionMFAEnforced() {
```
Comment (zmb3) [inline web/packages/teleport/src/config.ts:384]:
```suggestion
  isAdminActionMfaEnforced() {
```

In the web code we only capitalize the first letter of an acronym.

File: web/packages/teleport/src/services/auth/auth.ts [hunk 4]
```diff
@@ -315,15 +298,55 @@ const auth = {
     return api.post(cfg.api.createPrivilegeTokenPath, {});
   },
 
-  getWebauthnResponse(
+  async getWebauthnResponse(
     scope: MFAChallengeScope,
     allowReuse?: boolean,
     isMFARequiredRequest?: IsMfaRequiredRequest
```
Comment (zmb3) [inline web/packages/teleport/src/services/auth/auth.ts:304]:
```suggestion
    isMfaRequiredRequest?: IsMfaRequiredRequest
```

File: web/packages/teleport/src/services/auth/auth.ts [hunk 5]
```diff
@@ -315,15 +298,55 @@ const auth = {
...
+    if (isMFARequiredRequest) {
+      try {
+        const isMFARequired = await checkMfaRequired(isMFARequiredRequest);
+        if (!isMFARequired.required) {
+          return;
+        }
+      } catch (err) {
+        if (
+          err?.response?.status === 400 &&
+          err?.message.includes('missing target for MFA check')
```
Comment (zmb3) [inline web/packages/teleport/src/services/auth/auth.ts:318]: I would put a comment on the Go side where this error is defined that says that the UI depends on this not changing.

File: web/packages/teleport/src/services/auth/auth.ts [hunk 6]
```diff
@@ -315,15 +298,55 @@ const auth = {
...
+
+  getWebauthnResponseForAdminAction(allowReuse?: boolean) {
+    // If the client is checking if MFA is required for an admin action,
+    // but we know admin action MFA is not enforced, return early.
+    if (!cfg.isAdminActionMFAEnforced()) {
+      return;
+    }
+
+    return auth.getWebauthnResponse(
+      MFAChallengeScope.ADMIN_ACTION,
```
Comment (zmb3) [inline web/packages/teleport/src/services/auth/auth.ts:343]:
```suggestion
      MfaChallengeScope.ADMIN_ACTION,
```

You get the idea..

**Review by zmb3 — APPROVED** [review]

File: web/packages/teleport/src/services/auth/auth.ts (hunk 5 above)
Comment (Joerger) [reply web/packages/teleport/src/services/auth/auth.ts:318]: The UI only depends on this for old versions, new versions will know how to handle the `IsMfaRequiredAdminAction` request.

**Review by r0mant — APPROVED** [review]
