### PR TITLE
remove warning on unpopulated ssh proxy address

### LINKED ISSUE #24973: Warning on Invalid SSH Proxy Address in multiplex setup.
# Expected behavior:

SSH proxy address not specified in multiplex is valid setting and should not produce a warning.

# Current behavior:

If running in multiplex with a default `teleport configure` Teleport configuration you get this on startup. This would make you think something is off in the setup.

```bash
2023-04-21T10:48:06-04:00 WARN [WEB]       Invalid SSH proxy address "", will use default port 3023. error:[missing port in address] web/apiserver.go:328
```

Bug details:
- Teleport version: 13
- Recreation steps

Run `teleport configure` to a Teleport yaml
Run `teleport start -c ./teleport.yaml`

### PR DESCRIPTION
**Pull request by stevenGravy**
fixes #24973

This was showing an error on parsing when no ssh proxy address was set.

### CODE REVIEW

**Review by mdwn — APPROVED** [review]

File: lib/web/apiserver.go [hunk 1]
```diff
@@ -353,14 +353,19 @@ func NewHandler(cfg Config, opts ...HandlerOption) (*APIHandler, error) {
 		return nil, trace.Wrap(err)
 	}
 	h.auth = sessionCache
+	sshPortValue := strconv.Itoa(defaults.SSHProxyListenPort)
+	if cfg.ProxySSHAddr.String() != "" {
+		_, sshPort, err := net.SplitHostPort(cfg.ProxySSHAddr.String())
+		if err != nil {
+			h.log.WithError(err).Warnf("Invalid SSH proxy address %q, will use default port %v.",
+				cfg.ProxySSHAddr.String(), defaults.SSHProxyListenPort)
```
Comment (codingllama) [inline lib/web/apiserver.go:361]:
```suggestion
	if sshAddr := cfg.ProxySSHAddr.String(); sshAddr != "" {
		_, sshPort, err := net.SplitHostPort(sshAddr)
		if err != nil {
			h.log.WithError(err).Warnf(
				"Invalid SSH proxy address %q, will use default port %v.",
				sshAddr, defaults.SSHProxyListenPort)
```

**Review by codingllama — APPROVED** [review]
