### PR TITLE
Fix Kube impersonation header overwrite when dealing with remote clusters

### LINKED ISSUE #22226: Kube exec commands fail on leaf cluster
Expected behavior:
Kube exec commands will work through a root->leaf->kube agent connection as they did on v11.2.2

Current behavior:
After upgrading all components and tsh to v11.3.3, kube exec commands through the leaf cluster fail with the attached error.  All other tested kube commands work.  Maybe related to the work from https://github.com/gravitational/teleport/issues/21088?

~~~
error: Internal error occurred: error executing command in container: error sending request: Post "https://kube.teleport.cluster.local/api/v1/namespaces/teleport-agent/pods/teleport-kube-agent/exec?command=bash&container=teleport&stdin=true&stdout=true&tty=true": impersonation request has been denied, invalid user header []
~~~

Bug details:
- Teleport version: 11.3.3/11.3.4
- Recreation steps: attempt a `kube exec` to a pod through a kube agent attached to a leaf cluster after logging in to the root cluster

### PR DESCRIPTION
**Pull request by tigrato**
When forwarding exec requests to remote clusters I introduced an empty header that failed the validation in `setupImpersonationHeaders`. This results in the request being denied.

This problem only affects Teleport 11 and 10, but I am fixing the behavior on master as well.

Fixes #22226

### CODE REVIEW

File: lib/kube/proxy/forwarder.go [hunk 1]
```diff
@@ -1718,7 +1718,7 @@ func setupImpersonationHeaders(log logrus.FieldLogger, ctx authContext, headers
 
 	// Make sure to overwrite the exiting headers, instead of appending to
 	// them.
-	headers[ImpersonateGroupHeader] = nil
+	headers.Del(ImpersonateGroupHeader)
```
Comment (codingllama) [inline lib/kube/proxy/forwarder.go:1721]: Does it make sense to test for this scenario, so we avoid regressions?

Comment (tigrato) [reply lib/kube/proxy/forwarder.go:1721]: Done in 983117bfa430da1a2d5add537d90766d62683121

**Review by codingllama — APPROVED** [review]

**Review by avatus — APPROVED** [review]
