### PR TITLE
Benchmarks Will Now Be Tested During CI

### LINKED ISSUE #8401: Exercise benchmarks in CI
Our CI builds do not exercise benchmarks, making it hard to catch breakages that occur in benchmarks but not tests.

For example, `BenchmarkCheckAccessToServer` has been broken for about 4 months.

At a minimum, ensure that CI runs the benchmarks. As an extra, it might be nice to actually catch performance regressions by failing builds if benchmarks increase greater than some threshold.

### PR DESCRIPTION
**Pull request by doggydogworld**
Closes #8401

# Purpose

Benchmarks aren't included in CI unit tests and potentially breaking changes to them are not caught. This change will run benchmarks through CI unit tests.

This won't test performance regressions but simply ensure that benchmarks will run successfully.

# Implementation

* Created a new Makefile target `test-go-bench` that will run benchmarks only once. It had to be a separate target since the race detector is enabled for unit tests. The race detector slows down benchmarks way too much adding ~30mins. Unit tests should catch any races anyway.
* `gotestsum` is not currently compatible with benchmarks and will always flag them as failed no matter their actual outcome. (see https://github.com/gotestyourself/gotestsum/issues/332)
* Since `gotestsum` isn't compatible the benchmarks will be run in a separate step so that it isn't noisy.
* To speed up the benchmarks only packages with benchmarks (`grep -l testing.B`) are passed in to the `go test` command.
* `sed` will process benchmark failures and set a [workflow error message](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message) which marks the failed benchmark in the summary.

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -864,6 +864,16 @@ ifneq ("$(TOUCHID_TAG)", "")
 		| gotestsum --raw-command -- cat
 endif
 
+# Runs benchmarks once to make sure they pass.
+# This is intended to run in CI during unit testing to make sure benchmarks don't break.
+# To limit noise and improve speed this will only run on packages that have benchmarks.
+# Race detection is not enabled because it significantly slows down benchmarks.
+# todo: Use gotestsum when it is compatible with benchmark output. Currently will consider all benchmarks failed.
+.PHONY: test-go-bench
+test-go-bench: PACKAGES = $(shell grep --exclude-dir api --include "*_test.go" -lr testing.B .  | xargs dirname | xargs go list)
```
Comment (camscale) [inline Makefile:873]: you could put a `sort -u` in the pipeline that would remove the duplicate directories (which is not really necessary as go test will not test the same package even if specified multiple times) but also make the order deterministic. Also, I think the `go list` is not necessary as you can run the tests by package path and does not need the fully-qualified package name.

**Review by camscale — COMMENTED** [review]
Do you and any info on how much longer this workflow job will take now? I guess less than 5 minutes given the timeout, but hopefully not close to that - this is already one of the slower jobs on a PR ISTR.

**Review by r0mant — COMMENTED** [review]
@doggydogworld Since we're not going to be testing performance regressions by automatically comparing this with previous runs for now, can we output the summary of the run as a PR comment or something, so we can at least potentially compare results on different PRs manually if need be?

@rosstimothy What do you think? Would that be useful?

**Comment by doggydogworld** [comment]
> @doggydogworld Since we're not going to be testing performance regressions by automatically comparing this with previous runs for now, can we output the summary of the run as a PR comment or something, so we can at least potentially compare results on different PRs manually if need be?
> 
> @rosstimothy What do you think? Would that be useful?

So right now it actually does output failed jobs in the run summary:
image

I can update the script to just put a notice out which should show up there too for all benchmarks.

I think I might separate this into its own job so that it doesn't slow down the unit-testing workflow and provides more focused reporting on benchmarks specifically. It would probably also fit in with the eventual direction of this effort. For now I wanted to make sure benchmarks aren't breaking anymore. Once that's done I was imagining that a nightly build can be run for benchmarks to serve as a "baseline" that CI benchmarks are checked against and to provide some view of the performance of those benchmarks over time.

**Comment by fheinecke** [comment]
FYI because we collect GHA job metrics now, we could probably create a dashboard to show the change in benchmark time for nightly runs (if nightly runs are added).

**Review by rosstimothy — COMMENTED** [review]
I'm in the process of adding a benchmark test for a feature that requires running as root - https://github.com/gravitational/teleport/pull/45164. Can we copy our integration test workflows here and have a Benchmark and Benchmark Root workflow?

File: Makefile [hunk 2]
```diff
@@ -871,8 +871,9 @@ endif
 # todo: Use gotestsum when it is compatible with benchmark output. Currently will consider all benchmarks failed.
 .PHONY: test-go-bench
 test-go-bench: PACKAGES = $(shell grep --exclude-dir api --include "*_test.go" -lr testing.B .  | xargs dirname | xargs go list | sort -u)
+test-go-bench: BENCHMARK_PATTERN = "[^(?:(?:BenchmarkRoot|BenchmarkMux_ProxyV2Signature).*)].*"
```
[the remark this answers is not in the document]
Comment (doggydogworld) [reply Makefile:888]: Ah I added that just to get a passing job to see if I could see the output. Unfortunately one of cache benchmarks fails as well which is a bit weird because it works on my machine. Looks like the testing code for that might be flaky. 

I added a new workflow for the root tests already so it would fail those anyway. I was planning to fix that benchmark and include the fix here as well and then remove that from the pattern.

File: lib/multiplexer/multiplexer_test.go [hunk 3]
```diff
@@ -1273,74 +1273,58 @@ func startSSHServer(t *testing.T, listener net.Listener) {
...
-	ok := roots.AppendCertsFromPEM(ca.GetTrustedTLSKeyPairs()[0].Cert)
-	require.True(b, ok)
-
 	ip := "1.2.3.4"
 	sAddr := net.TCPAddr{IP: net.ParseIP(ip), Port: 444}
 	dAddr := net.TCPAddr{IP: net.ParseIP(ip), Port: 555}
+	listener4, err := net.Listen("tcp", "127.0.0.1:")
+	require.NoError(b, err)
+
+	startServing := func(muxListener net.Listener, cluster string) (*Mux, *httptest.Server) {
```
Comment (r0mant) [inline lib/multiplexer/multiplexer_test.go:1283]: This is basically the same as in the unit test: https://github.com/gravitational/teleport/blob/9f08fc37b5dd686d033467b71c443ef4664c9fdf/lib/multiplexer/multiplexer_test.go#L835-L861

The only difference I can see is here we're not using TLS listener - is there a reason, can we unify, factor out and reuse this in both tests? Then both tests become more compact.

File: Makefile [hunk 4]
```diff
@@ -878,6 +878,24 @@ ifneq ("$(TOUCHID_TAG)", "")
...
 endif
 
+# Runs benchmarks once to make sure they pass.
+# This is intended to run in CI during unit testing to make sure benchmarks don't break.
+# To limit noise and improve speed this will only run on packages that have benchmarks.
+# Race detection is not enabled because it significantly slows down benchmarks.
+# todo: Use gotestsum when it is compatible with benchmark output. Currently will consider all benchmarks failed.
+.PHONY: test-go-bench
+test-go-bench: PACKAGES = $(shell grep --exclude-dir api --include "*_test.go" -lr testing.B .  | xargs dirname | xargs go list | sort -u)
+test-go-bench: BENCHMARK_SKIP_PATTERN = "^BenchmarkRoot|^BenchmarkGetMaxNodes$$"
```
[the remark this answers is not in the document]
Comment (doggydogworld) [reply Makefile:888]: It's a bit of a flaky benchmark and I couldn't decide how to deal with it. It adds 2 million server objects to a cache and allows for 200ms for each update. If the cache eviction and/or GC kick it at the wrong time the latency added is enough to push it past that time limit. I pushed it to 300ms and 400ms and it still sometimes fails.

File: lib/multiplexer/multiplexer_test.go (hunk 3 above)
Comment (doggydogworld) [reply lib/multiplexer/multiplexer_test.go:1283]: Ah yeah I can just move that function out. I wanted to keep any refactors to the absolute minimum but considering this is just for setup it shouldn't affect much.

**Review by r0mant — APPROVED** [review]
@doggydogworld Let's ship this and make further changes/tweaks in followups if needed.

**Review by rosstimothy — APPROVED** [review]

**Comment by doggydogworld** [comment]
> @doggydogworld can we backport this to active release branches?

Yup will do
