### PR TITLE
Fix server info reconciler not restarting after an error

### LINKED ISSUE #44793: The server info reconciler can fail without recovering
Expected behavior:
The server info reconciler keeps working (with some backoff) after errors

Current behavior:
The server info reconciler exits on error and never runs again, the only indication of this being a single log line at warning level with `"message":"Non-critical service has exited with error , continuing to operate.","service":"auth.server_info"`.

Bug details:
- Teleport version: latest v14, v15, v16, master, from what I can tell
- Recreation steps: have an error (maybe a backend error? this issue was prompted by a dynamodbbk error:
```
"error":"failed to get \"/serverInfos/cloudLabels/REDACTED\" (dynamo error)\n\tRequestError: send request failed\ncaused by: Post \"https://dynamodb.us-west-2.amazonaws.com/\": read tcp REDACTED:0->35.71.66.12:443: read: connection reset by peer"
```

### PR DESCRIPTION
**Pull request by atburke**
This change fixes the server info reconciler to restart on an error.

Fixes #44793.

Changelog: Fixed the resource-based labels handler crashing without restarting

### CODE REVIEW

File: lib/auth/server_info.go [hunk 1]
```diff
@@ -20,57 +20,99 @@ package auth
...
+
 // ReconcileServerInfos periodically reconciles the labels of ServerInfo
 // resources with their corresponding Teleport SSH servers.
-func (a *Server) ReconcileServerInfos(ctx context.Context) error {
-	const batchSize = 100
-	const timeBetweenBatches = 10 * time.Second
-	const timeBetweenReconciliationLoops = 10 * time.Minute
-	clock := a.GetClock()
+func ReconcileServerInfos(ctx context.Context, ap ServerInfoAccessPoint) error {
+	retry, err := retryutils.NewLinear(retryutils.LinearConfig{
```
Comment (zmb3) [inline lib/auth/server_info.go:60]: Does retry need any sort of defer to stop it when this function returns?

Comment (atburke) [reply lib/auth/server_info.go:60]: It doesn't have a `Close()` method and it doesn't have any internal things to cancel, so I don't think so.

**Comment by atburke** [comment]
Friendly ping @rosstimothy

**Review by rosstimothy — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]
