### PR TITLE
Fix the access list reminder pagination loop.

### LINKED ISSUE #36225: Permissions missing for Access Lists Reminder produces `access denied to perform action "read" on "access_list"` log spam
Customers report receiving a significant number ("8 billion log entries over an 7 day period") of the following log upon upgrading to 14.2.4 from 14.1.0:

`ERRO   error listing access lists: access denied to perform action "read" on "access_list", access denied to perform action "list" on "access_list" accesslist/app.go:144`

The root cause of this is that the role assigned to their access plugins does not have access to the new "access_list" resource/verb. We should handle this more gracefully and ensure we've provided appropriate advice in the change-log upgrade instructions **and in the documentation for the plugins** - it doesn't feel like this has occurred.

The huge amount of logs emitted is down to a logic error in the implementation that causes this failed request to be retried immediately:

```go
	for {
		select {
		case <-remindInterval.Next():
			log.Info("Looking for Access List Review reminders")

			var nextToken string
			var err error
			for {
				var accessLists []*accesslist.AccessList
				accessLists, nextToken, err = a.apiClient.AccessListClient().ListAccessLists(ctx, 0 /* default page size */, nextToken)
				if err != nil {
					if trace.IsNotImplemented(err) {
						log.Errorf("access list endpoint is not implemented on this auth server, so the access list app is ceasing to run.")
						return nil
					}
					log.Errorf("error listing access lists: %v", err)
					continue
				}
```

The `continue` in the error handling does not go up to the correct loop (e.g waiting for the next run) and hence retries immediately.

Introduced by https://github.com/gravitational/teleport/pull/34461

## Workaround

Modify the role used for your access plugin: 

```yaml
spec:
  allow:
    rules:
      - resources: ['access_list']
        verbs: ['list', 'read']
```

### PR DESCRIPTION
**Pull request by mdwn**
On error in the access list reminder pagination loop, the loop now breaks instead of continuing, which is the intended behavior. A test has been added to exercise this. This test will time out with the previous behavior. A light refactoring has been done to make it easier to mock the ListAccessLists response.

Users running their own Slack plugins (outside of cloud) were running into an issue here due to the plugin user not having permissions to read access lists. On cloud tenants, the plugins should have this access, so the impact there is minimal.

Additionally, the docs have been updated to include the access list permissions.

changelog: Fix spammy logging with access list reminders in Slack plugin when the plugin user lacks access list permissions.

Fixes https://github.com/gravitational/teleport/issues/36225

### CODE REVIEW

File: integrations/access/accesslist/app_test.go [hunk 1]
```diff
@@ -181,6 +182,68 @@ func TestAccessListReminders(t *testing.T) {
...
+		recipients: map[string]*common.Recipient{
+			"owner1": {Name: "owner1"},
+			"owner2": {Name: "owner2"},
+		},
+	}
+	app := common.NewApp(&mockPluginConfig{client: client, bot: bot}, "test-plugin")
+	app.Clock = clock
+	ctx := context.Background()
+	go func() {
+		require.NoError(t, app.Run(ctx))
```
Comment (zmb3) [inline integrations/access/accesslist/app_test.go:225]: We can't call require in a goroutine like this.

File: integrations/access/accesslist/app_test.go [hunk 2]
```diff
@@ -181,6 +182,68 @@ func TestAccessListReminders(t *testing.T) {
...
+	args := m.Called(ctx, pageSize, pageToken)
+	return args.Get(0).([]*accesslist.AccessList), args.String(1), args.Error(2)
+}
+
+func TestAccessListReminders_BadClient(t *testing.T) {
+	t.Parallel()
+
+	clock := clockwork.NewFakeClockAt(time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC))
+
+	server, err := auth.NewTestServer(auth.TestServerConfig{
```
Comment (zmb3) [inline integrations/access/accesslist/app_test.go:200]: Do we need to shut this server down on connection close?

File: integrations/access/accesslist/app_test.go [hunk 3]
```diff
@@ -181,6 +182,68 @@ func TestAccessListReminders(t *testing.T) {
...
+	require.True(t, ready)
+
+	t.Cleanup(func() {
+		app.Terminate()
+		<-app.Done()
+		require.NoError(t, app.Err())
+	})
+
+	for i := 1; i <= 6; i++ {
+		clock.Advance(6 * time.Hour)
```
Comment (zmb3) [inline integrations/access/accesslist/app_test.go:239]: I'm not used to seeing `Advance` without `BlockUntil` - are we sure this is correct?

File: integrations/access/accesslist/app_test.go [hunk 4]
```diff
@@ -181,6 +182,68 @@ func TestAccessListReminders(t *testing.T) {
...
+		require.Eventuallyf(t, func() bool {
+			return len(client.Calls) == i
+		}, 5*time.Second, 5*time.Millisecond, "timeout waiting for expected number of calls (%d/%d)", len(client.Calls), i)
```
Comment (zmb3) [inline integrations/access/accesslist/app_test.go:242]: 5 millisecond retry period seems pretty quick for our slow CI environments. I would lean closer to 50 or 100.

But then again, if you use `clock.BlockUntil` correctly you might not need `Eventuallyf` at all, which is going to lead to a less flaky and more consistent test.

Comment (mdwn) [reply integrations/access/accesslist/app_test.go:242]: So I was unaware of `BlockUntil` until now, but it looks like there's a latency that requires `Eventuallyf` even with `BlockUntil`, unfortunately. So I'll leave this as is, including the above comment.

Comment (zmb3) [reply integrations/access/accesslist/app_test.go:248]: I'm not sure I agree that `Eventuallyf` is necessary.

Your reminder loop runs every `<-remindInterval.Next()`.

If you block until your loop is waiting for the tick, then set up the test conditions, then advance the clock the app loop will start to process.

Then you block again until the next `<-remindInterval.Next()`. At this point, you can be sure that the previous iteration of the reminder loop completed and can make assertions as to what should have happened.

Am I missing something?

Comment (mdwn) [reply integrations/access/accesslist/app_test.go:248]: So, if I replace that wait logic with this:

```
	clock.BlockUntil(1)

	for i := 1; i <= 6; i++ {
		clock.Advance(6 * time.Hour)
		clock.BlockUntil(1)
		require.Len(t, client.Calls, i)
	}
```

When running the test locally, I get:
```
--- FAIL: TestAccessListReminders_BadClient (0.06s)
    /Users/mike/go/src/github.com/gravitational/teleport/integrations/access/accesslist/app_test.go:249: 
        	Error Trace:	/Users/mike/go/src/github.com/gravitational/teleport/integrations/access/accesslist/app_test.go:249
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestAccessListReminders_BadClient
```

However, if I add a `time.Sleep(1*time.Second)` before the `require.Len` check above, the test passes. So the only thing I can think of is that the call to count the number of calls is not synchronous for some reason? I'll dig a little more, but that's what I'm finding at the moment.

File: docs/pages/includes/plugins/rbac-with-friendly-name.mdx [hunk 5]
```diff
@@ -19,6 +19,11 @@ spec:
       - resources: ['access_plugin_data']
         verbs: ['update']
 
+      # In order to provide access list review reminders, permissions to access lists
+      # are necessary. This is currently only supported for a subset of plugins.
```
Comment (ptgott) [inline docs/pages/includes/plugins/rbac-with-friendly-name.mdx:23]:
```suggestion
      # In order to provide access list review reminders, permissions to list and read access lists
      # are necessary. This is currently only supported for a subset of plugins.
```

**Review by ptgott — APPROVED** [review]
Approved from a docs standpoint with a minor suggestion

File: integrations/access/accesslist/app.go [hunk 6]
```diff
@@ -116,35 +115,28 @@ func (a *App) run(ctx context.Context) error {
...
-	defer remindInterval.Stop()
 	log := logger.Get(ctx)
 
 	log.Info("Access list monitor is running")
 
 	a.job.SetReady(true)
 	for {
 		select {
-		case <-remindInterval.Next():
+		case <-a.clock.After(reminderInterval):
```
Comment (hugoShaka) [inline integrations/access/accesslist/app.go:125]: why is a static `clock.After()` better than a jittered interval with a ~30s first duration? It's easier for testing purposes? I'm afraid that if your plugin restarts every 2 hours for some reason you will never get any notification with this ticker.

Comment (zmb3) [reply integrations/access/accesslist/app.go:125]: Our `interval` utility is not very testable right now, and `clock.After()` allows for a deterministic test that behaves the same every run and doesn't depend on `require.Eventually`.

Valid point about restarting every 2 hours though. I wonder if we can solve for that by doing one check manually before entering the loop..

File: docs/pages/includes/plugins/rbac-with-friendly-name.mdx [hunk 7]
```diff
@@ -19,6 +19,11 @@ spec:
       - resources: ['access_plugin_data']
         verbs: ['update']
 
+      # In order to provide access list review reminders, permissions to list and read access lists
+      # are necessary. This is currently only supported for a subset of plugins.
```
[the remark this answers is not in the document]
Comment (mdwn) [reply docs/pages/includes/plugins/rbac-with-friendly-name.mdx:23]: I intentionally did not here because I'm nearly positive this doc will lag at some point. This way we sort of avoid it.

File: integrations/access/accesslist/app.go
Comment (tigrato) [inline integrations/access/accesslist/app.go:1]: I can't comment on particular lines but:

```go

allRecipients := a.fetchRecipients(ctx, accessList, now, notificationStart)
	if len(allRecipients) == 0 {
		return trace.NotFound("no recipients could be fetched for access list %s", accessList.GetName())
	}

...

// fetchRecipients will return all recipients.
func (a *App) fetchRecipients(ctx context.Context, accessList *accesslist.AccessList, now, notificationStart time.Time) map[string]common.Recipient {
	log := logger.Get(ctx)
	allRecipients := make(map[string]common.Recipient, len(accessList.Spec.Owners))
	// If the current time before the notification start time, skip notifications.
	if now.Before(notificationStart) {
		log.Debugf("Access list %s is not ready for notifications, notifications start at %s", accessList.GetName(), notificationStart.Format(time.RFC3339))
		return nil
}
...
```

Should we return an error when time.Now is before the notification start date?
Is it possible to skip the ticker each 30s and run on the next access list notify date? Not sure if ticking each 30s is a great fit

Comment (mdwn) [reply integrations/access/accesslist/app.go:1]: Ahh, so it's now a timer -- the timer waits 30 seconds for the first notification, then 3 hours per notification from there. Is that reasonable?

As for the error, I'm sort of ambivalent about it. This works as is.

Comment (mdwn) [reply integrations/access/accesslist/app.go:1]: Talked offline. This error is now only returned if there are issues fetching recipients, and avoided if now if before the notification start date.

**Review by strideynet — APPROVED** [review]

**Review by tigrato — APPROVED** [review]
