### PR TITLE
Terminate sessions when peers disconnect

### LINKED ISSUE #17848: zombie kube sessions never exit
### Expected behavior:

When a user is disconnected from a kube session, it should not continue indefinitely as an active session.

### Current behavior:

A user is connected to a kube session, such as `kubectl exec -it pod/mypod -- bash`. Their connection is interrupted in a way that their client kubectl nor os is able to send any RST/FIN packet to the proxy (network cable unplug, sudden power failure of client machine or other network equipment, OpenVPN disconnect, etc). Their session still shows up as an active session in the Teleport console. It is never cleaned up, and the recording is not uploaded. Additionally, the bash process still exists in the container.

This was observed in a cluster with proxy-sync session recording mode.

### Bug details:
- Teleport version: 10.3.3

### Recreation steps

The reporting user runs Teleport in proxy-sync recording mode. They created kubernetes manifests using the teleport-cluster helm chart, but have customized the manifest files directly since. They use dynamodb for storage and events, s3 for session recordings, and every pod in the deployment is auth+proxy+kubernetes_service. They only have the one kubernetes cluster in this environment.

<details>
<summary>teleport.yaml with proxy-sync recording mode.</summary>

```yaml
auth_service:
  authentication:
    local_auth: "true"
    second_factor: "off"
    #type: saml
  client_idle_timeout: 30m
  client_idle_timeout_message: Terminating session as no activities.
  cluster_name: proxysynclab
  enabled: true
  license_file: /var/lib/teleport/license.pem
  proxy_listener_mode: multiplex
  session_recording: proxy-sync
  web_idle_timeout: 10m
kubernetes_service:
  enabled: true
  kube_cluster_name: mykubecluster
  labels:
    environment_class: lab
  listen_addr: 0.0.0.0:3027
proxy_service:
  enabled: true
  https_keypairs:
    - cert_file: /etc/teleport-tls/tls.crt
      key_file: /etc/teleport-tls/tls.key
  kube_listen_addr: 0.0.0.0:3026
  mysql_listen_addr: 0.0.0.0:3036
  public_addr: teleport.example.com:443
  web_listen_addr: 0.0.0.0:443
ssh_service:
  enabled: true
teleport:
  log:
    format:
      extra_fields:
        - timestamp
        - level
        - component
        - caller
      output: text
    output: stdout
    severity: DEBUG
  storage:
    audit_events_uri:
      - dynamodb://teleport.example.com-audit
      - stdout://
    audit_sessions_uri: s3://teleport.example.com
    continuous_backups: false
    region: us-east-2
    table_name: teleport.example.com-backend
    type: dynamodb
version: 2
```
</details>

Once the lab was running, I was able to reproduce the condition by starting a kubectl exec session, and then use iptables to completely block the flow of packets on the already established connection. kubectl itself exited when it could no longer communicate on the established connection. The teleport web interface still shows the session as active the next day. Load balancer timeouts in front of the lab are set to 600 seconds.

image

<details>
<summary>Click for details on the iptables blocking</summary>

I utilized a docker container to make it easy to implement an iptables rule that only affected my containerized kubectl exec procedure.

```
docker run --name kubetest -it --entrypoint='' quay.io/gravitational/teleport-ent:10.3.3 bash --login
root@ba1bf16096d0:/# apt -y install net-tools curl
root@ba1bf16096d0:/# curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
root@ba1bf16096d0:/# tsh login --proxy=teleport.example.com:443 --user=jeff proxysynclab
root@ba1bf16096d0:/# export KUBECONFIG=${HOME?}/teleport-kubeconfig.yaml
root@ba1bf16096d0:/# tsh kube login mykubecluster
root@ba1bf16096d0:/# kubectl get ns
root@ba1bf16096d0:/# kubectl get pods
root@ba1bf16096d0:/# kubectl exec -it mypod -- bash --login
```

Then in another terminal, I can exec into the docker container as a privileged user and add my own iptables rule:

```
docker exec -it --priveleged kubetest bash --login
root@ba1bf16096d0:/# iptables -nL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
root@ba1bf16096d0:/# iptables -I OUTPUT -p tcp --dport 443 -j DROP
root@ba1bf16096d0:/# iptables -nL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
DROP       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443
root@ba1bf16096d0:/# iptables-save -c
# Generated by iptables-save v1.8.4 on Wed Oct 26 15:46:00 2022
*filter
:INPUT ACCEPT [18:3354]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
[52:11009] -A OUTPUT -p tcp -m tcp --dport 443 -j DROP
COMMIT
# Completed on Wed Oct 26 15:46:00 2022
```

Rerunning the last command shows the counts of the rules. As I typed in my kubectl exec session, that count went up. Finally, kubectl's connection timed out because no response packets ever made it back, and kubectl exited.

The same iptables rule could be used for any other number of environments. The privileged docker container is just a handy approach.

</details>

Running `ps faux` inside the pod shows that the original bash process is still running:

```
$ kubectl -n other exec -it mypod -- ps faux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     31621  0.0  0.1   5896  2916 pts/3    Rs+  16:29   0:00 ps faux
root      1980  0.0  0.1   4244  3496 pts/0    Ss+  Oct25   0:00 bash --login
root         1  0.3  7.3 1618336 147056 ?      Ssl  Oct24   8:54 nginx -g daemon
```

The session will stay as active until the teleport auth/proxy/agent pod is cycled. This doesn't always result in a successful session.end and session upload event. It simply no longer shows up in active sessions.

Stopping the `mypod` pod will result in the session ending as well. The recording will be uploaded too.

Killing the bash process inside the container also causes the session to gracefully end.

- Debug logs 
[waitlogs.txt.gz](https://github.com/gravitational/teleport/files/9872009/waitlogs.txt.gz) (entire logs for the lab over the course of a day, including a USR1 signal sent while the session was stuck. It has audit events mixed in to the log stream as well.

### LINKED ISSUE #18194: Moderated Kube session recordings aren't uploaded if the moderator terminates the session
Expected behavior:

All session recordings are uploaded.

Current behavior:

If a moderator joins a kube session and terminates it by pressing `t` the recording is never uploaded. SSH sessions might have the same behavior, haven't tried.

Bug details:

- Teleport version: 3b4c144b2acb2a046459fd8bfb54f8094c68c1cd

Recreation steps:

User 1:

```
$ tsh kube login foo
$ kubectl exec -it somepod -- /bin/bash
$ echo hello
```

User 2:

```
$ tsh kube sessions
$ tsh kube join <ID> --mode=moderator
<press t>
```

### PR DESCRIPTION
**Pull request by tigrato**
When any peer disconnects from a session without closing it, Teleport marks it as active and does not publish the session recordings. 

This PR closes the session once every peer disconnects to avoid leaving zombie sessions when a user intentionally blocks traffic or when a VPN disconnects.

It also waits until all events are pushed before closing the recorder.

Fixes #17848
Fixes #18194

### CODE REVIEW

File: lib/srv/termmanager.go [hunk 1]
```diff
@@ -221,6 +220,8 @@ func (g *TermManager) AddReader(name string, r io.Reader) {
 			if err != nil {
 				log.Warnf("Failed to read from remote terminal: %v", err)
 				g.DeleteReader(name)
+				// close session if any peer disconnects
+				g.Close()
```
Comment (tigrato) [inline lib/srv/termmanager.go:224]: @zmb3 @xacrimon 

I decided to close the session if any peer disconnects, however in theory we can continue the session if there are multiple peers.

Comment (xacrimon) [reply lib/srv/termmanager.go:224]: @tigrato I don't think we can do this. Moderated sessions relies on the fact that people can come and go, the session should only close if it cannot continue per a require policy. This would be a terribly breaking change that would disrupt current customer workflows. Can we work around this?

**Review by xacrimon — CHANGES_REQUESTED** [review]
marking as rc due to the feature-changing nature of this PR in it's current state

**Comment by xacrimon** [comment]
IMO what we should do is close out the term manager properly once we realize there are zero users connected at all, we might have to check for this periodically or on any change to the term manager state.

**Comment by xacrimon** [comment]
Actually, @espadolini reminded me that zombie sessions are actually a feature (somewhat), you're supposed to be able to leave and then reconnect to a session without loosing the terminal, this might only be implemented for SSH but we should be wary of it. So I don't think the solution I recommended will work either. I believe that this sort of monitoring will have to happen within the core session code for that respective thing (sess.go in the kube package) in this case to ensure the session is closed once no parties remain. I believe SSH already has this sort of monitoring and will close out automatically after some linger time.

This is also needed for smooth session resumption in case of disconnects.

**Comment by tigrato** [comment]
@xacrimon @espadolini
Thanks. I wasn't aware of that "feature".

I will change it

**Comment by zmb3** [comment]
I bet https://github.com/gravitational/teleport/issues/18194 is also related.

**Comment by tigrato** [comment]
@xacrimon @espadolini @zmb3,
 can you please take another look?

 #18194 is fixed as well by this PR

File: lib/kube/proxy/sess.go [hunk 2]
```diff
@@ -928,24 +949,33 @@ func (s *session) leave(id uuid.UUID) error {
...
 	}
 
 	err = party.Close()
 	if err != nil {
 		s.log.WithError(err).Error("Error closing party")
-		return trace.Wrap(err)
+		errs = append(errs, trace.Wrap(err))
 	}
 
 	if len(s.parties) == 0 || id == s.initiator {
```
Comment (tigrato) [inline lib/kube/proxy/sess.go:961]: @xacrimon @espadolini @zmb3 

In kube, once the initiator leaves the session is closed.
Should I change the behavior to be the same as the one in Server access?

Comment (zmb3) [reply lib/kube/proxy/sess.go:961]: I don't think you need to change the behavior of Kube right now, so long as recordings work.

Of course, if a moderator leaves, the session should remain open (though it may be locked).

File: lib/kube/proxy/forwarder.go [hunk 3]
```diff
@@ -864,9 +862,9 @@ func (f *Forwarder) join(ctx *authContext, w http.ResponseWriter, req *http.Requ
 		party := newParty(*ctx, stream.Mode, client)
 		go func() {
 			<-stream.Done()
-			session.mu.Lock()
-			defer session.mu.Unlock()
-			session.leave(party.ID)
+			if err := session.leave(party.ID); err != nil {
```
Comment (zmb3) [inline lib/kube/proxy/forwarder.go:865]: Do you need to hold `mu` for `session.leave()`?

**Review by zmb3 — COMMENTED** [review]
I don't feel super confident approving this one as I'm not very familiar with the code and it's quite complicated.

Are you happy with the existing test coverage or could we write a test to exercise the issues that this fixes?

File: lib/kube/proxy/forwarder.go (hunk 3 above)
Comment (tigrato) [reply lib/kube/proxy/forwarder.go:865]: I moved the lock into the `session.leave` to simplify the call.

**Review by xacrimon — APPROVED** [review]
looks good otherwise to me but please make sure to test this out in a live cluster and add an automated test or two if possible.

**Comment by tigrato** [comment]
I added some unit tests and fixed a data race.

File: lib/kube/proxy/forwarder.go [hunk 4]
```diff
@@ -886,6 +884,34 @@ func (f *Forwarder) join(ctx *authContext, w http.ResponseWriter, req *http.Requ
...
 }
 
+// getSession retrieves the session from in-memory database.
+// If the session was not found, returns nil.
+// This method locks f.mu.
+func (f *Forwarder) getSession(id uuid.UUID) *session {
+	f.mu.Lock()
+	defer f.mu.Unlock()
+	// Currently, Teleport closes the session when the initiator exits.
+	// So, it is safe to remove it
```
Comment (espadolini) [inline lib/kube/proxy/forwarder.go:894]: Was this supposed to go in `deleteSession`?

**Review by espadolini — APPROVED** [review]
LGTM but I'm not very familiar with the session handling code.

File: lib/kube/proxy/forwarder.go [hunk 5]
```diff
@@ -864,9 +862,9 @@ func (f *Forwarder) join(ctx *authContext, w http.ResponseWriter, req *http.Requ
 		party := newParty(*ctx, stream.Mode, client)
 		go func() {
 			<-stream.Done()
-			session.mu.Lock()
-			defer session.mu.Unlock()
-			session.leave(party.ID)
+			if err := session.leave(party.ID); err != nil {
+				f.log.Debugf("Participant %q was unable to leave session %s: %v", party.ID, session.id)
```
Comment (zmb3) [inline lib/kube/proxy/forwarder.go:866]: I think this is missing the error. There's 3 format verbs and 2 additional arguments.

File: lib/kube/proxy/moderated_sessions_test.go [hunk 6]
```diff
@@ -0,0 +1,425 @@
+/*
+Copyright 2016 The Kubernetes Authors.
```
Comment (zmb3) [inline lib/kube/proxy/moderated_sessions_test.go:2]: Is this correct? Is this kube code or Teleport code?

File: lib/kube/proxy/sess.go [hunk 7]
```diff
@@ -364,6 +380,22 @@ func newSession(ctx authContext, forwarder *Forwarder, req *http.Request, params
...
+	if idString == sessionRecorderID {
+		s.log.Error("Failed to write to session recorder, closing session.")
+		s.Close()
+	}
+
+	s.log.Errorf("Encountered error: %v with party %v. Disconnecting them from the session.", err, idString)
+	id, _ := uuid.Parse(idString)
+
+	if err = s.leave(id); err != nil {
+		s.log.Errorf("Failed to disconnect party %v from the session: %v.", idString, err)
```
Comment (zmb3) [inline lib/kube/proxy/sess.go:395]: If `Parse` fails, `id` will be an empty string, and this log message will be pretty confusing.

File: lib/kube/proxy/sess.go [hunk 8]
```diff
@@ -419,29 +451,15 @@ func (s *session) launch() error {
...
-			}
-		}
-	}
 
 	onFinished, err := s.lockedSetupLaunch(request, q, eventPodMeta)
 	if err != nil {
 		return trace.Wrap(err)
 	}
+	defer func() {
+		// catch err by reference so we can access any write into it in the two calls that follow
```
Comment (zmb3) [inline lib/kube/proxy/sess.go:460]: I don't understand this comment. What is "catch by reference"?

File: lib/kube/proxy/utils_test.go [hunk 9]
```diff
@@ -184,6 +205,17 @@ func setupTestContext(ctx context.Context, t *testing.T, cfg testConfig) *testCo
 		OnReconcile:      cfg.onReconcile,
 	})
 	require.NoError(t, err)
+	// create session recording path
+	// testCtx.kubeServer.DataDir/log/upload/streaming/default
+	err = os.MkdirAll(
```
Comment (zmb3) [inline lib/kube/proxy/utils_test.go:210]: What's going to clean up this directory? Should you use `t.TempDir` instead?

File: lib/kube/proxy/moderated_sessions_test.go (hunk 6 above)
Comment (tigrato) [reply lib/kube/proxy/moderated_sessions_test.go:2]: I copied the wrong header

File: lib/kube/proxy/utils_test.go (hunk 9 above)
Comment (tigrato) [reply lib/kube/proxy/utils_test.go:210]: `testCtx.kubeServer.DataDir` is already a [`t.TempDir`](https://github.com/gravitational/teleport/blob/a647ca4254d5f0db34f4819decf325d8ed47c188/lib/kube/proxy/utils_test.go#L172). I am just creating the correct folder structure for storing the sessions.

Comment (zmb3) [reply lib/kube/proxy/utils_test.go:210]: Ah, got it!

**Review by zmb3 — APPROVED** [review]
