### PR TITLE
Reconnect broken LDAP connections

### LINKED ISSUE #9808: windows_desktop_service doesn't automatically recreate broken ldap connection
### Description

**What happened**:
windows_desktop_service attempted an ldap query with a closed connection.

**What you expected to happen**:
windows_desktop_service will automatically recreate connection if connection is broken for some reason.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Successfully setup Windows desktop service.
2. Restart AD server
3. Windows desktop service will attempt query over closed connection

### Server Details
- Teleport version (run `teleport version`): 8.1.0
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): on-prem k8s cluster
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

```
2022-01-17 03:19:48.514821 I | tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 10.244.19.174:50758->10.192.2.124:636: write: broken pipe
2022-01-17T03:23:03Z DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) desktop/discovery.go:115
2022-01-17T03:23:03Z WARN [WINDOWS_D] "could not discover Windows Desktops: fetching LDAP object \"DC=ad,DC=carsonanderson,DC=net\": LDAP Result Code 200 \"Network Error\": ldap: connection closed\n\tLDAP Result Code 200 \"Network Error\": ldap: connection closed" desktop/discovery.go:119
```

### PR DESCRIPTION
**Pull request by zmb3**
Ensure that our LDAP client returns trace.ConnectionProblem errors
for LDAP error 200 (network error).

When this condition is detected, we re-initialize our LDAP client
to get a fresh connection.

Also clean up some of the errors in the reconciler so that they
include the resources kind and name without stringify-ing the
entire resource.

Lastly, add both a connect and request timeout for our LDAP client,
allowing us to detect connection issues sooner.

Fixes #9808

### CODE REVIEW

**Comment by zmb3** [comment]
Tested this by lowering the reconcile period from 5 minutes to 1 minute and rebooting the domain controller while teleport is running.

```
2022-02-06T17:52:34-07:00 DEBU [WINDOWS_D] Reconciling 1 current resources with 1 new resources. services/reconciler.go:102
2022-02-06T17:52:34-07:00 INFO [WINDOWS_D] windows_desktop WIN-I44F9TN11M3-zacmanual-example-com updated, updating. services/reconciler.go:169

<reboot here>

2022-02-06T17:53:34-07:00 DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) desktop/discovery.go:122
2022-02-06T17:53:54-07:00 INFO [WINDOWS_D] LDAP connection error when searching for desktops, reinitializing client desktop/discovery.go:130
2022-02-06T17:53:54-07:00 INFO [CA]        Generating TLS certificate 
2022-02-06T17:53:54-07:00 INFO [WINDOWS_D] Teleport CA already present in NTAuthStore in LDAP desktop/windows_server.go:877
2022-02-06T17:53:54-07:00 INFO [WINDOWS_D] Updated CRL for Windows logins via LDAP desktop/windows_server.go:937
2022-02-06T17:53:54-07:00 DEBU [WINDOWS_D] Reconciling 1 current resources with 1 new resources. services/reconciler.go:102
2022-02-06T17:53:54-07:00 DEBU [WINDOWS_D] windows_desktop WIN-I44F9TN11M3-zacmanual-example-com is already registered. services/reconciler.go:182

2022-02-06T17:54:34-07:00 DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) desktop/discovery.go:122
2022-02-06T17:54:34-07:00 DEBU [WINDOWS_D] discovered 1 Windows Desktops desktop/discovery.go:138
```

File: lib/srv/desktop/discovery.go [hunk 1]
```diff
@@ -122,7 +122,15 @@ func (s *WindowsService) getDesktopsFromLDAP() types.ResourcesWithLabels {
...
 
 	entries, err := s.lc.readWithFilter(s.cfg.DiscoveryBaseDN, filter, computerAttribtes)
-	if err != nil {
+	if trace.IsConnectionProblem(err) {
+		// If the connection was broken, re-initialize the LDAP client so that it's
+		// ready for the next reconcile loop. Return the last known set of desktops
+		// in this case, so that the reconciler doesn't delete the desktops it already
+		// knows about.
+		s.cfg.Log.Info("LDAP connection error when searching for desktops, reinitializing client")
+		s.initializeLDAP()
```
Comment (rosstimothy) [inline lib/srv/desktop/discovery.go:131]: Looks like this error isn't being handled. Logging it might be the only actionable thing to do here though.

File: lib/srv/desktop/ldap.go [hunk 2]
```diff
@@ -113,6 +114,8 @@ func (c *ldapClient) create(dn string, class string, attrs map[string][]string)
 				return trace.BadParameter("object constraint violation on %q: %v", dn, err)
 			case ldap.LDAPResultInsufficientAccessRights:
 				return trace.AccessDenied("insufficient permissions to create %q: %v", dn, err)
+			case ldap.ErrorNetwork:
+				return trace.ConnectionProblem(err, "LDAP network error")
```
Comment (rosstimothy) [inline lib/srv/desktop/ldap.go:118]: Looks like all other `trace.ConnectionProblem` that were added contain the `dn`, should we add it here as well?

**Review by rosstimothy — APPROVED** [review]

File: lib/srv/desktop/discovery.go (hunk 1 above)
Comment (zmb3) [reply lib/srv/desktop/discovery.go:131]: Yeah, I was thinking I would avoid spamming with the same error message in case this takes several retries before it succeeds, but I'm not opposed to logging it.

File: lib/srv/desktop/ldap.go (hunk 2 above)
Comment (zmb3) [reply lib/srv/desktop/ldap.go:118]: Will do.

**Review by ibeckermayer — COMMENTED** [review]
Tested it locally and it worked for me as well.

**Review by rcanderson23 — APPROVED** [review]
echo @ibeckermayer that this fixed the issue in my dev environment

**Comment by rcanderson23** [comment]
May have jumped the gun. I see the reconnect succeed but I think the resource is still expiring (gone in the UI) and subsequent updates fail:
```
2022-02-07T17:14:18Z DEBU [WINDOWS_D] Changing state connecting -> connected. leaseID:1 target:dev-teleport.carsonanderson.net:3024 reversetunnel/agent.go:208
2022-02-07T17:14:18Z DEBU [WINDOWS_D] Discovery request channel opened: teleport-discovery. leaseID:1 target:dev-teleport.carsonanderson.net:3024 reversetunnel/agent.go:517
2022-02-07T17:14:18Z DEBU [WINDOWS_D] handleDiscovery requests channel. leaseID:1 target:dev-teleport.carsonanderson.net:3024 reversetunnel/agent.go:535
2022-02-07T17:14:18Z INFO [WINDOWS_D] Teleport CA already present in NTAuthStore in LDAP desktop/windows_server.go:877
2022-02-07T17:14:18Z INFO [WINDOWS_D] Updated CRL for Windows logins via LDAP desktop/windows_server.go:937
2022-02-07T17:14:33Z DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) desktop/discovery.go:122
2022-02-07T17:14:33Z DEBU [WINDOWS_D] discovered 1 Windows Desktops desktop/discovery.go:138
2022-02-07T17:14:33Z DEBU [WINDOWS_D] resolved WIN-ONUR9EC95N5.ad.carsonanderson.net => [10.192.2.124] desktop/discovery.go:194
2022-02-07T17:14:33Z DEBU [WINDOWS_D] Reconciling 0 current resources with 1 new resources. services/reconciler.go:102
2022-02-07T17:14:33Z INFO [WINDOWS_D] windows_desktop WIN-ONUR9EC95N5-ad-carsonanderson-net matches, creating. services/reconciler.go:148
2022-02-07T17:19:18Z DEBU [WINDOWS_D] Ping -> 10.192.101.5:3024. leaseID:1 target:dev-teleport.carsonanderson.net:3024 reversetunnel/agent.go:479
2022-02-07T17:19:34Z DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) desktop/discovery.go:122
2022-02-07T17:19:34Z DEBU [WINDOWS_D] discovered 1 Windows Desktops desktop/discovery.go:138
2022-02-07T17:19:34Z DEBU [WINDOWS_D] resolved WIN-ONUR9EC95N5.ad.carsonanderson.net => [10.192.2.124] desktop/discovery.go:194
2022-02-07T17:19:34Z DEBU [WINDOWS_D] Reconciling 1 current resources with 1 new resources. services/reconciler.go:102
2022-02-07T17:19:34Z INFO [WINDOWS_D] windows_desktop WIN-ONUR9EC95N5-ad-carsonanderson-net updated, updating. services/reconciler.go:169
2022/02/07 17:20:20 tls: failed to send closeNotify alert (but connection was closed anyway): write tcp 10.244.19.181:37592->10.192.2.124:636: write: broken pipe
2022-02-07T17:24:18Z DEBU [WINDOWS_D] Ping -> 10.192.101.5:3024. leaseID:1 target:dev-teleport.carsonanderson.net:3024 reversetunnel/agent.go:479
2022-02-07T17:24:22Z DEBU [WINDOWS_D] Attempting to restart watch after waiting 4.429096757s. resource-kind:lock services/watcher.go:211
2022-02-07T17:24:22Z DEBU [WINDOWS_D] Triggering scheduled refetch. resource-kind:lock services/watcher.go:220
2022-02-07T17:24:22Z DEBU [WINDOWS_D] Starting watch. resource-kind:lock services/watcher.go:182
2022-02-07T17:24:34Z DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) desktop/discovery.go:122
2022-02-07T17:24:34Z INFO [WINDOWS_D] LDAP connection error when searching for desktops, reinitializing client desktop/discovery.go:130
2022-02-07T17:24:34Z INFO [WINDOWS_D] Teleport CA already present in NTAuthStore in LDAP desktop/windows_server.go:877
2022-02-07T17:24:34Z INFO [WINDOWS_D] Updated CRL for Windows logins via LDAP desktop/windows_server.go:937
2022-02-07T17:24:34Z DEBU [WINDOWS_D] Reconciling 1 current resources with 1 new resources. services/reconciler.go:102
2022-02-07T17:24:34Z DEBU [WINDOWS_D] windows_desktop WIN-ONUR9EC95N5-ad-carsonanderson-net is already registered. services/reconciler.go:182
2022-02-07T17:29:18Z DEBU [WINDOWS_D] Ping -> 10.192.101.5:3024. leaseID:1 target:dev-teleport.carsonanderson.net:3024 reversetunnel/agent.go:479
2022-02-07T17:29:34Z DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) desktop/discovery.go:122
2022-02-07T17:29:34Z DEBU [WINDOWS_D] discovered 1 Windows Desktops desktop/discovery.go:138
2022-02-07T17:29:34Z DEBU [WINDOWS_D] resolved WIN-ONUR9EC95N5.ad.carsonanderson.net => [10.192.2.124] desktop/discovery.go:194
2022-02-07T17:29:34Z DEBU [WINDOWS_D] Reconciling 1 current resources with 1 new resources. services/reconciler.go:102
2022-02-07T17:29:34Z INFO [WINDOWS_D] windows_desktop WIN-ONUR9EC95N5-ad-carsonanderson-net updated, updating. services/reconciler.go:169
2022-02-07T17:29:34Z ERRO [WINDOWS_D] "desktop reconciliation failed: failed to update windows_desktop WIN-ONUR9EC95N5-ad-carsonanderson-net\n\twindows desktop \"WIN-ONUR9EC95N5-ad-carsonanderson-net\" doesn't exist" desktop/discovery.go:96
```

If this is a known issue than you can ignore the update as the ldap reconnection part seems to be working for me.

File: lib/srv/desktop/discovery.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/srv/desktop/discovery.go:131]: Yes, will add some logging as Tim pointed out the same.

We're not "leaking" that goroutine, as it will be terminated when the service shuts down. We do still need to periodically renew our certificate, but I think what you're pointing out is that we can technically cancel the renewal we've already scheduled as this will schedule a new one.

I don't think there's an issue here though, as:

- there's nothing bad about renewing our certificate more frequently than necessary
- we only schedule a renewal if we successfully got a cert, so in cases where we're in an error loop we won't be scheduling a bunch of renewals.

Thoughts?

**Comment by zmb3** [comment]
Thanks @rcanderson23 - I thought I had resolved all such instances of that, but the best option is probably to use upsert everywhere. Let me push a small revision and I'd love for you to give it another try.

File: lib/srv/desktop/discovery.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/srv/desktop/discovery.go]: @ibeckermayer check out the latest commit - I think it's a better way to address the renewal and should address your comment.

File: lib/srv/desktop/windows_server.go [hunk 3]
```diff
@@ -519,6 +540,10 @@ func (s *WindowsService) startStaticHostHeartbeats() error {
 // Close instructs the server to stop accepting new connections and abort all
 // established ones. Close does not wait for the connections to be finished.
 func (s *WindowsService) Close() error {
+	s.mu.Lock()
+	defer s.mu.Unlock()
+
+	s.ldapCertRenew.Stop()
```
Comment (rosstimothy) [inline lib/srv/desktop/windows_server.go:546]: Is there any chance `s.ldapCertRenew` will be `nil` here? Can I `Close` before the first successful call to `initializeLDAP`?

File: lib/srv/desktop/discovery.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (ibeckermayer) [reply lib/srv/desktop/discovery.go]: > We're not "leaking" that goroutine, as it will be terminated when the service shuts down.

True, bad description of the problem on my part.

> check out the latest commit - I think it's a better way to address the renewal and should address your comment.

Yeah looks good.

File: lib/srv/desktop/windows_server.go (hunk 3 above)
Comment (zmb3) [reply lib/srv/desktop/windows_server.go]: Good catch, it is possible. Unlikely, but possible. Fixed.

File: lib/srv/desktop/discovery.go [hunk 4]
```diff
@@ -113,7 +112,7 @@ func (s *WindowsService) ldapSearchFilter() string {
 
 // getDesktopsFromLDAP discovers Windows hosts via LDAP
 func (s *WindowsService) getDesktopsFromLDAP() types.ResourcesWithLabels {
-	if atomic.LoadInt32(&s.ldapInitialized) == 0 {
+	if !s.ldapReady() {
```
Comment (ibeckermayer) [inline lib/srv/desktop/discovery.go:115]: I think this check here has the potential to cause us issues:

Consider the case that in one reconcile loop,
`readWithFilter` (line 123 below this) fails and we call `s.initializeLDAP` again (line 130). If that `initializeLDAP` fails, then inside it we'll be setting `s.ldapInitialized = false`. So on the next reconcile loop, this check will be triggered and we'll return `nil`, but won't try to `initializeLDAP` again, and will do so for every subsequent reconcile loop.

**Review by rosstimothy — APPROVED** [review]

**Review by ibeckermayer — APPROVED** [review]
