### PR TITLE
Fix listing of available participant modes in the UI for Moderated Sessions

### LINKED ISSUE #23237: [Web UI] Join button for Moderated Sessions doesn't show up unless joiner's own role is defined in join policy
#### Expected behavior:

The join button with participant modes dropdown should show up if your user is allowed to join the session with any participant mode.

#### Current behavior:

In order for the join button to show up, your own role must be listed in the `roles` section of your join policy:
```
join_sessions:
    roles:
       - .....
```

#### Bug details:
- Teleport version: `v13`

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR closes https://github.com/gravitational/teleport/issues/23237

https://github.com/gravitational/teleport/pull/23807 should be merged first.

Fixes a bug that caused the available participant modes in the UI to be inaccurate and only show up if your own role was defined in your `join_sessions` policy.

## Implementation

The bug was caused by a typo when initializing the `sessionAccessEvaluator`, it was using the policy sets of the user, rather than the policy sets of the session host.

While reading the code I discovered another bug with the way we used `regexp.MatchString()` to match the join policy roles with the roles in the policy set. The way we used `MatchString()` before only checked for any match of the expression within the string, so if the string contained a substring that matches the expression, it would return `true` even if the full string isn't an exact match. For example this means that if your join policy only allowed you to join users with the role `auditor`, it would still return `true` for roles such as `prod-auditor`.

### CODE REVIEW

File: lib/auth/session_access.go [hunk 1]
```diff
@@ -162,7 +162,7 @@ func (e *SessionAccessEvaluator) matchesJoin(allow *types.SessionJoinPolicy) boo
 
 	for _, allowRole := range allow.Roles {
 		// GlobToRegexp makes sure this is always a valid regexp.
-		expr := regexp.MustCompile(utils.GlobToRegexp(allowRole))
+		expr := regexp.MustCompile("^" + utils.GlobToRegexp(allowRole) + "$")
```
Comment (zmb3) [inline lib/auth/session_access.go:165]: This looks like a pretty important bug fix. Can you add a test to ensure that this doesn't regress in the future?

**Comment by zmb3** [comment]
Looks like we've got some lint failures still @rudream

**Review by xacrimon — APPROVED** [review]
👍 thanks for taking care of this!

**Review by gabrielcorado — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
