### PR TITLE
Fix webauthnwin c types size

### LINKED ISSUE #31333: `tsh mfa add --type=WEBAUTHN` panics on Windows
__Expected behavior:__

It works.

__Current behavior:__

It panics. See excerpt below:

```
.\tsh.exe mfa add --type=WEBAUTHN --name=tshwin
Allow passwordless logins [YES, NO]: no
Using platform authentication for *registered* device, follow the OS dialogs
Using platform authentication for *new* device, follow the OS dialogs
(follow dialog, touch yubikey, then immediately after:)
Exception 0xc0000005 0x0 0x7800000001 0x7ff9dd2d8f2a
PC=0x7ff9dd2d8f2a
signal arrived during external code execution

runtime.cgocall(0x7ff62b3097a0, 0xc000100ac8)
        runtime/cgocall.go:157 +0x3e fp=0xc001d1d6b0 sp=0xc001d1d678 pc=0x7ff62b2995fe
syscall.SyscallN(0xc001d1d7e0?, {0xc001d1d748?, 0x7ff62ec312cd?, 0x23?})
        runtime/syscall_windows.go:544 +0x107 fp=0xc001d1d728 sp=0xc001d1d6b0 pc=0x7ff62b304ae7
syscall.Syscall9(0x0?, 0x7ff62b2ffff9?, 0x0?, 0xc001d1d7e0?, 0x7ff62b67b665?, 0xc000080700?, 0xc001d1d840?, 0x7ff62b67b5a5?, 0xc001469050?, 0x0, ...)
        runtime/syscall_windows.go:494 +0x72 fp=0xc001d1d7a0 sp=0xc001d1d728 pc=0x7ff62b304812
golang.org/x/sys/windows.(*Proc).Call(0x7ff62e016440?, {0xc001072180?, 0x7ff62e2e4660?, 0x100c001d1d801?})
        golang.org/x/sys@v0.11.0/windows/dll_windows.go:182 +0x2cf fp=0xc001d1d850 sp=0xc001d1d7a0 pc=0x7ff62b67ab6f
golang.org/x/sys/windows.(*LazyProc).Call(0x7ff62e016440, {0xc001072180, 0x7, 0x7})
        golang.org/x/sys@v0.11.0/windows/dll_windows.go:348 +0x4a fp=0xc001d1d880 sp=0xc001d1d850 pc=0x7ff62b67b78a
github.com/gravitational/teleport/lib/auth/webauthnwin.(*nativeImpl).MakeCredential(0x7ff62f4fc6c0?, {0xc00009a060?, 0xc001d1db20?}, 0xc000fca500)
        github.com/gravitational/teleport/lib/auth/webauthnwin/webauthn_windows.go:167 +0x18f fp=0xc001d1d998 sp=0xc001d1d880 pc=0x7ff62d45606f
github.com/gravitational/teleport/lib/auth/webauthnwin.Register({0x2b4d508c2b8?, 0x2b4d5080a28?}, {0xc000a940c0, 0x18}, 0xc001d1df00)
        github.com/gravitational/teleport/lib/auth/webauthnwin/api.go:144 +0x3f4 fp=0xc001d1dcd0 sp=0xc001d1d998 pc=0x7ff62d4539f4
github.com/gravitational/teleport/lib/auth/webauthncli.Register({0x7ff62f548748, 0xc001c69ef0}, {0xc000a940c0, 0x18}, 0xc001d1dd98?, {0x7ff62f51bb68, 0xc0000b0300})
        github.com/gravitational/teleport/lib/auth/webauthncli/api.go:240 +0x1b2 fp=0xc001d1dd38 sp=0xc001d1dcd0 pc=0x7ff62d460432
github.com/gravitational/teleport/tool/tsh/common.promptWebauthnRegisterChallenge({0x7ff62f548748?, 0xc001c69ef0}, {0xc000a940c0, 0x18}, 0x8?)
        github.com/gravitational/teleport/tool/tsh/common/mfa.go:542 +0x209 fp=0xc001d1ddb8 sp=0xc001d1dd38 pc=0x7ff62dc520a9
github.com/gravitational/teleport/tool/tsh/common.promptRegisterChallenge({0x7ff62f548748, 0xc001c69ef0}, {0xc001c70300?, 0x0?}, {0xc00000a117, 0x8}, 0xc001c12000)
        github.com/gravitational/teleport/tool/tsh/common/mfa.go:450 +0x267 fp=0xc001d1e140 sp=0xc001d1ddb8 pc=0x7ff62dc511c7
github.com/gravitational/teleport/tool/tsh/common.(*mfaAddCommand).addDeviceRPC.func1()
        github.com/gravitational/teleport/tool/tsh/common/mfa.go:387 +0x5e5 fp=0xc001d1e378 sp=0xc001d1e140 pc=0x7ff62dc50685
github.com/gravitational/teleport/lib/client.RetryWithRelogin({0x7ff62f548748, 0xc001c69ef0}, 0xc001c7e400, 0xc001d1e6a8, {0x0, 0x0, 0x1?})
        github.com/gravitational/teleport/lib/client/api.go:570 +0x6e fp=0xc001d1e620 sp=0xc001d1e378 pc=0x7ff62d55fd8e
github.com/gravitational/teleport/tool/tsh/common.(*mfaAddCommand).addDeviceRPC(0xc001c68bd0, {0x7ff62f548748, 0xc001c69ef0}, 0xc001c7e400)
        github.com/gravitational/teleport/tool/tsh/common/mfa.go:314 +0x1c5 fp=0xc001d1e7a0 sp=0xc001d1e620 pc=0x7ff62dc4ffa5
github.com/gravitational/teleport/tool/tsh/common.(*mfaAddCommand).run(0xc001c68bd0, 0xc001a78e00)
        github.com/gravitational/teleport/tool/tsh/common/mfa.go:282 +0x655 fp=0xc001d1e8b0 sp=0xc001d1e7a0 pc=0x7ff62dc4fc15
github.com/gravitational/teleport/tool/tsh/common.Run({0x7ff62f548e58, 0xc001bdda00}, {0xc0000b0210?, 0x5, 0x7}, {0x0, 0x0, 0xc000097ed8?})
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1391 +0xdc46 fp=0xc001d1fe68 sp=0xc001d1e8b0 pc=0x7ff62dc715a6
github.com/gravitational/teleport/tool/tsh/common.Main()
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:540 +0x2e5 fp=0xc001d1ff30 sp=0xc001d1fe68 pc=0x7ff62dc636a5
main.main()
        github.com/gravitational/teleport/tool/tsh/main.go:24 +0xf fp=0xc001d1ff40 sp=0xc001d1ff30 pc=0x7ff62dcda2ef
runtime.main()
        runtime/proc.go:267 +0x2b2 fp=0xc001d1ffe0 sp=0xc001d1ff40 pc=0x7ff62b2d4e92
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc001d1ffe8 sp=0xc001d1ffe0 pc=0x7ff62b307fc1

(many other goroutines omitted)
```

I doesn't matter whether the registration is passwordless or not.

__Bug details:__
- Teleport version: 14 alpha2
- Recreation steps: see above
- Debug logs: see above

### PR DESCRIPTION
**Pull request by tobiaszheller**
https://github.com/gravitational/teleport/pull/29750 removed unused `icon` fields from webauthwin internal C types. Unfortunately it causes panic because now types have wrong size. 

Manual tests on windows machine confirm issue and fix.

Fixes: https://github.com/gravitational/teleport/issues/31333

Changelog: Fix WebAuthn Windows registration breakage

### CODE REVIEW

File: lib/auth/webauthnwin/ctypes.go [hunk 1]
```diff
@@ -35,6 +35,10 @@ type webauthnRPEntityInformation struct {
 	// "Acme Corporation", "Widgets Inc" or "Awesome Site".
 	// This field is required.
 	pwszName *uint16
+
+	// Optional URL pointing to RP's logo.
```
Comment (codingllama) [inline lib/auth/webauthnwin/ctypes.go:39]:
```suggestion
	// RP icon (previously pwszIcon).
```

File: lib/auth/webauthnwin/ctypes.go [hunk 2]
```diff
@@ -46,6 +50,10 @@ type webauthnUserEntityInformation struct {
 	// "john.p.smith@example.com".
 	// It holds the Teleport user name.
 	pwszName *uint16
+	// Optional URL that can be used to retrieve an image containing the user's current avatar,
+	// or a data URI that contains the image data.
```
Comment (codingllama) [inline lib/auth/webauthnwin/ctypes.go:54]:
```suggestion
	// User icon (previously pwszIcon).
```

**Review by codingllama — APPROVED** [review]
Many thanks. I completely missed the structs had to be aligned.

Any ideas on how we could test to avoid future size/align regressions?

**Review by Tener — APPROVED** [review]
Tricky one. Having this tested would be lovely, for sure.

**Comment by tobiaszheller** [comment]
> Any ideas on how we could test to avoid future size/align regressions?

Do you have some ideas? I have tried using `unsafe.Sizeof(webauthnRPEntityInformation{})` however it won't for example catch change from uint32 to uint8 (due to Go padding and alignment). @Tener @codingllama

File: lib/auth/webauthnwin/ctypes.go [hunk 3]
```diff
@@ -35,6 +35,10 @@ type webauthnRPEntityInformation struct {
 	// "Acme Corporation", "Widgets Inc" or "Awesome Site".
 	// This field is required.
 	pwszName *uint16
+
+	// RP icon (previously pwszIcon).
+	// This field is kept just to keep size of struct valid.
+	_ *uint16
```
Comment (zmb3) [inline lib/auth/webauthnwin/ctypes.go:41]: Hmm, if the size of the struct matters, shouldn't we be more explicit? A `*uint16` can have different sizes on different platforms, no?

Comment (tobiaszheller) [reply lib/auth/webauthnwin/ctypes.go:41]: i believe we don't support 32bit tsh at all for windows

**Comment by codingllama** [comment]
Manually verified the fix as well, looking good. FYI, I'm happy to merge this and do whatever testing/refinements we see fit as a follow up.

**Comment by tobiaszheller** [comment]
> Manually verified the fix as well, looking good. FYI, I'm happy to merge this and do whatever testing/refinements we see fit as a follow up.

Yep, let's merge it.
