### PR TITLE
Fix event handler to gracefully drop malformed sessions

### LINKED ISSUE #60317: Event handler dies when facing a malformed session start event
Expected behavior:

- malformed session start events are droppped
- event handler gracefully deals with a malformed session

Current behavior:

- the event handler tries to get the session, fails and exits in error after 3 retries

Bug details:
- Teleport version: Cluster version v17.7.0 enterprise, self hosted / Event handler version (Kubernetes deployed) v17.7.0
- Recreation steps: ????
- Debug logs

```
INFO  Using batch size batch:20 event-handler/cli.go:256
INFO  Using concurrency concurrency:5 event-handler/cli.go:257
INFO  Using type filter types:[] event-handler/cli.go:258
INFO  Skipping audit events of type types:map[] event-handler/cli.go:259
INFO  Skipping session recording events of type types:map[desktop.recording:{} print:{}] event-handler/cli.go:260
INFO  Using start time value:<nil> event-handler/cli.go:261
INFO  Using timeout timeout:10s event-handler/cli.go:262
INFO  Using Fluentd url url:https://fluentd-forwarder.REDACTED.svc.cluster.local:8888/teleport.log event-handler/cli.go:263
INFO  Using Fluentd session url url:https://fluentd-forwarder.REDACTED.svc.cluster.local:8888/teleport.session event-handler/cli.go:264
INFO  Using Fluentd ca ca:/var/lib/teleport/plugins/event-handler/ca.crt event-handler/cli.go:265
INFO  Using Fluentd cert cert:/var/lib/teleport/plugins/event-handler/client.crt event-handler/cli.go:266
INFO  Using Fluentd key key:/var/lib/teleport/plugins/event-handler/client.key event-handler/cli.go:267
INFO  Using Fluentd max connections max_connections:10 event-handler/cli.go:268
INFO  Using window size window_size:24h0m0s event-handler/cli.go:269
INFO  Using Teleport identity file file:/var/lib/teleport/plugins/event-handler/teleport-identity/identity event-handler/cli.go:272
INFO  Using Teleport identity file refresh interval:1m0s event-handler/cli.go:275
INFO  Using existing storage directory dir:storage/teleport-proxy.19bc5bfd-25de-4c8f-8c4c-5887a9e59ee7.net_443 event-handler/state.go:148
WARN  Encountering backpressure from outbound event processing event-handler/legacy_events_watcher.go:395
WARN  Encountering backpressure from outbound event processing event-handler/legacy_events_watcher.go:395
WARN  Encountering backpressure from outbound event processing event-handler/legacy_events_watcher.go:395
WARN  Encountering backpressure from outbound event processing event-handler/legacy_events_watcher.go:395
WARN  Encountering backpressure from outbound event processing event-handler/legacy_events_watcher.go:395
WARN  Encountering backpressure from outbound event processing event-handler/legacy_events_watcher.go:395
ERRO  Session ingestion error, retrying id: index:0 error:[
ERROR REPORT:
Original Error: *interceptors.RemoteError InvalidUri
Stack Trace:
    github.com/gravitational/teleport/api@v0.0.0/client/client.go:2754 github.com/gravitational/teleport/api/client.(*Client).StreamUnstructuredSessionEvents.func1
    runtime/asm_amd64.s:1700 runtime.goexit
User Message: InvalidUri
    ] attempt:2 event-handler/session_events_job.go:202
ERRO  Session ingestion error, retrying id: index:0 error:[
ERROR REPORT:
Original Error: *interceptors.RemoteError InvalidUri
Stack Trace:
    github.com/gravitational/teleport/api@v0.0.0/client/client.go:2754 github.com/gravitational/teleport/api/client.(*Client).StreamUnstructuredSessionEvents.func1
    runtime/asm_amd64.s:1700 runtime.goexit
User Message: InvalidUri
    ] attempt:1 event-handler/session_events_job.go:202
ERRO  Session ingestion exceeded attempt limit, aborting id: index:0 limit:3 event-handler/session_events_job.go:195
ERRO  Failed to export event, retrying... error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled
Stack Trace:
    github.com/gravitational/teleport/integrations/event-handler/fluentd_client.go:126 main.(*FluentdClient).Send
    github.com/gravitational/teleport/integrations/event-handler/app.go:116 main.(*App).SendEvent
    github.com/gravitational/teleport/integrations/event-handler/events_job.go:313 main.(*EventsJob).sendEvent
    github.com/gravitational/teleport/integrations/event-handler/events_job.go:288 main.(*EventsJob).handleEvent
    github.com/gravitational/teleport/integrations/event-handler/legacy_events_watcher.go:414 main.(*LegacyEventsWatcher).ExportEvents
    github.com/gravitational/teleport/integrations/event-handler/events_job.go:262 main.(*EventsJob).runLegacyPolling
    github.com/gravitational/teleport/integrations/event-handler/events_job.go:125 main.(*EventsJob).runPolling
    github.com/gravitational/teleport/integrations/event-handler/events_job.go:91 main.(*EventsJob).run
    github.com/gravitational/teleport@v0.0.0/integrations/lib/process.go:234 main.NewApp.NewEventsJob.NewServiceJob.func1
    github.com/gravitational/teleport@v0.0.0/integrations/lib/process.go:255 github.com/gravitational/teleport/integrations/lib.(*serviceJob).DoJob
    github.com/gravitational/teleport@v0.0.0/integrations/lib/process.go:101 github.com/gravitational/teleport/integrations/lib.NewProcess.func2.1
    runtime/asm_amd64.s:1700 runtime.goexit
User Message: context canceled] event-handler/legacy_events_watcher.go:419
ERRO  Terminating with fatal error error_number:1 error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled
Stack Trace:
    github.com/gravitational/teleport/integrations/event-handler/legacy_events_watcher.go:422 main.(*LegacyEventsWatcher).ExportEvents
    github.com/gravitational/teleport/integrations/event-handler/events_job.go:262 main.(*EventsJob).runLegacyPolling
    github.com/gravitational/teleport/integrations/event-handler/events_job.go:125 main.(*EventsJob).runPolling
    github.com/gravitational/teleport/integrations/event-handler/events_job.go:91 main.(*EventsJob).run
    github.com/gravitational/teleport@v0.0.0/integrations/lib/process.go:234 main.NewApp.NewEventsJob.NewServiceJob.func1
    github.com/gravitational/teleport@v0.0.0/integrations/lib/process.go:255 github.com/gravitational/teleport/integrations/lib.(*serviceJob).DoJob
    github.com/gravitational/teleport@v0.0.0/integrations/lib/process.go:101 github.com/gravitational/teleport/integrations/lib.NewProcess.func2.1
    runtime/asm_amd64.s:1700 runtime.goexit
User Message: context canceled] lib/bail.go:36
```

### PR DESCRIPTION
**Pull request by kshi36**
Fixes #60317

Instead of panicking when ingesting malformed session events, the event handler now logs the errors and gracefully drops them. This change refactors `SpawnCriticalJob` to eliminate the panic by aligning behavior with `IterateMissingRecordings`.

In addition, for ingesting missing session recordings, the max in-flight sessions is now controlled by a value of double the `concurrency`, instead of a fixed 10. This ensures regular ingestion and missing recordings ingestion is synced to one field.

changelog: Fixed bug where event handler dies on malformed session events
changelog: Updated event handler to ingest missing session recordings at twice the `concurrency` instead of only 10 sessions at a time

### CODE REVIEW

**Review by bernardjkim — APPROVED** [review]

File: integrations/event-handler/session_events_job.go [hunk 1]
```diff
@@ -261,21 +266,7 @@ func (j *SessionEventsJob) processMissingRecordings(ctx context.Context) error {
...
-			go func() {
-				defer func() { <-semaphore }()
-
-				if err := j.processSession(ctx, sess, attempts); err != nil {
-					j.app.log.DebugContext(ctx, "Failed processing session recording", "error", err)
-				}
-			}()
-
-			return nil
+			return j.ingestSession(ctx, sess, attempts)
```
Comment (zmb3) [inline integrations/event-handler/session_events_job.go]: It looks like we went from allowing 10 sessions in flight at a time to 5 (by default). Is that expected?

Comment (kshi36) [reply integrations/event-handler/session_events_job.go]: I figured it made more sense for in-flight sessions to both be controlled by the `concurrency` value, instead of missing recordings ingestion using a fixed value of 10 and only regular ingestion synced to `concurrency`. WDYT?

Alternatively, shall we have it double the concurrency, to match default behavior?

Comment (hugoShaka) [reply integrations/event-handler/session_events_job.go]: > I figured it made more sense for in-flight sessions to both be controlled by the concurrency value,

I think this is a good call 👍 .

> shall we have it double the concurrency

Using twice the concurrency to ensure the defaults stay the same makes sense.

If we do this change:
- the concurrency part should not be backported to v17, this is not a bugfix and might affect customers in unexpected ways
- this should be reflected in the changelog as this changes the event handler behaviour and might be relevant for customers who had concurrency issues, or observe that the handler consumes more resources now.

As you work on the Teleport codebase you'll find many small papercuts or things that can be improved. Sometimes they don't deserve their own PR and it's fine to send them with some other changes to save the PR overhead.

But as you improve the code quality, please mention potential additional/unrelated changes in the PR description. This helps reviewers understand what happens, and makes troubleshooting easier if you're really unlucky and the seemingly insignificant change causes a regression.

Comment (kshi36) [reply integrations/event-handler/session_events_job.go]: Sounds good. I will make sure to remove the concurrency part in v17's backport, and modify the changelog for master & v18.

I must've missed mentioning this change, since I remembered for my other PRs

**Review by hugoShaka — APPROVED** [review]
