### PR TITLE
kube: resolve Kubernetes cluster domain

### LINKED ISSUE #39007: Kubernetes Application Discovery fails when the cluster DNS suffix is not cluster.local
I have been attempting to get Teleport's Kubernetes Application Discovery to work with a new GKE cluster I have created. This GKE cluster has a non-standard DNS suffix, `gke.local`. Although the Teleport Agent appears to successfully discover the application, I am not able to connect to it - instead I receive an `Internal Server Error`.

Looking in the logs reveals that the Teleport Agent is attempting to forward my request to a hostname with the suffix `cluster.local`.

I have located what I believe is the cause - the `cluster.local` suffix is hardcoded in the `getServiceFQDN()` function, which the autodiscovery code seems to rely upon.

https://github.com/gravitational/teleport/blob/4c26c2a426315292a905db33e351813764933ac3/lib/srv/discovery/fetchers/kube_services.go#L284

I would expect that the Teleport Agent would either not append a suffix (allowing the normal FQDN search to take place on the upstream DNS server), or would lookup the correct suffix to append instead of assuming it will be `cluster.local`.

### PR DESCRIPTION
**Pull request by tigrato**
This PR enhances teleport by no longer assuming the cluster domain must be `cluster.local`. Since many clusters use a non-default cluster domain, this assumption can disrupt app discovery access.

To address this, the PR allows to set `clusterDomain` via the helm chart when installing/upgrading the agent.

Fixes #39007

Changelog: Extend Teleport ability to use non-default cluster domains in Kubernetes, avoiding the assumption of `cluster.local`.

### CODE REVIEW

File: lib/services/app.go [hunk 1]
```diff
@@ -274,3 +285,101 @@ func getAppLabels(serviceLabels map[string]string, clusterName string) (map[stri
...
+		return resolveKubeClusterDomain(etcResolvConf)
+
+	})
+	// kubeDNSResolver is a DNS resolver used to resolve the cluster domain from the DNS.
+	kubeDNSResolver interface {
+		LookupCNAME(ctx context.Context, host string) (string, error)
+	} = net.DefaultResolver
+)
+
+// resolveKubeClusterDomain resolves the cluster domain from the DNS, resolv.conf, or a default value.
```
Comment (AntonAM) [inline lib/services/app.go:305]:
```suggestion
// resolveKubeClusterDomain resolves the cluster domain from the env variable
TELEPORT_KUBE_CLUSTER_DOMAIN, the DNS, resolv.conf, or a default value.
```

**Review by AntonAM — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]

File: docs/pages/reference/helm-reference/includes/zz_generated.teleport-kube-agent.mdx [hunk 2]
```diff
@@ -199,6 +199,20 @@ Once `appResources` is set, you can dynamically register application with
 `tsh` by following [the Dynamic App Registration guide](../../../application-access/guides/dynamic-registration.mdx).
 </Admonition>
 
+## `clusterDomain`
+
+| Type | Default |
+|------|---------|
+| `string` | `""` |
+
+`clusterDomain` Sets the domain name used by the Kubernetes cluster. This value is used to build the
```
Comment (webvictim) [inline docs/pages/reference/helm-reference/includes/zz_generated.teleport-kube-agent.mdx:208]: nit:

```suggestion
`clusterDomain` sets the domain name used by the Kubernetes cluster. This value is used to build the
```

**Review by webvictim — APPROVED** [review]

**Comment by tigrato** [comment]
After discussing with @hugoShaka  we decided to leave the service stupid and remove the self-resolution logic so that it is clearer what each person will have to do.

**Review by hugoShaka — APPROVED** [review]

**Review by webvictim — APPROVED** [review]

**Review by AntonAM — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]

**Comment by 1st8** [comment]
@tigrato is there a reason that this has only been added to the deployment.yaml, and not to the statefulset.yaml?

**Comment by tigrato** [comment]
> @tigrato is there a reason that this has only been added to the deployment.yaml, and not to the statefulset.yaml?

No, not at all. I though I also added it but doesn't look like the case. PR https://github.com/gravitational/teleport/pull/46144 fixes it

**Comment by 1st8** [comment]
Nice, thank you!
