### PR TITLE
Avoid a hard crash when WebAssembly is missing

### LINKED ISSUE #65697: Teleport web UI crashes when WASM is disabled
Expected behavior:
Teleport.sh should load, even if there is a restrictive Chrome policy.

Current behavior:

Image

Bug details:
- Teleport version: 
     Web app `18.7.3`
- Recreation steps
 Launch Chrome with WASM disabled. Can attach a quick and dirty playwright script.

```js
import { chromium } from "playwright";

const url = process.argv[2] || "https://<tenant>.teleport.sh";

const browser = await chromium.launch({
  headless: false,
  args: ["--disable-web-security"], // avoid other CSP issues
});

const context = await browser.newContext();
const page = await context.newPage();

// Delete WebAssembly before any page script runs — simulates a restrictive enterprise policy
await page.addInitScript(() => {
  delete globalThis.WebAssembly;
});

// Capture console errors
page.on("pageerror", (err) => {
  console.error("PAGE ERROR:", err.message);
});

console.log(`Loading ${url} with WebAssembly disabled...`);
await page.goto(url, { waitUntil: "domcontentloaded", timeout: 30000 });

// Wait a moment for scripts to execute
await page.waitForTimeout(3000);

// Take a screenshot
await page.screenshot({ path: "crash.png", fullPage: true });
console.log("Screenshot saved to crash.png");

// Keep browser open for inspection
console.log("Browser is open. Press Ctrl+C to close.");
await new Promise(() => {});
```

### PR DESCRIPTION
**Pull request by ryanclark**
`@xterm/addon-image` references `WebAssembly` at the top level, so the fact that `features.tsx` imports the view session recording page, which then imports the player, resulted in the app crashing completely when `WebAssembly` is not available.

The image addon is not necessary for recording playback, so this changes it to a dynamic import that only loads of the import doesn't error.

Additionally, the desktop session/recording player didn't check if `WebAssembly` was defined, so that would show a "WebAssembly is not defined error", so this adds a check there and shows a nicer error message instead.

image

(ignore the sidebar, this is on a local desktop recording that has a session summary locally)

image

Fixes #65697

Changelog: Fixed an issue where WebAssembly not being available would crash the web UI

### Test Environment
Local, Chrome launched with and without WebAssembly

### Test Cases
- [x] WebAssembly available
  - [x] Connecting to a desktop works fine
  - [x] Watching a desktop recording works fine
  - [x] Watching a TTY recording works fine
- [x] WebAssembly not available
  - [x] TTY session recordings can still be watched
  - [x] Error is shown when trying to watch a desktop recording
  - [x] Error is shown when trying to connect to a desktop

### CODE REVIEW

File: web/packages/teleport/src/lib/term/terminal.ts [hunk 1]
```diff
@@ -103,9 +102,15 @@ export default class TtyTerminal implements TerminalSearcher {
...
     this.term.loadAddon(this._webLinksAddon);
-    this.term.loadAddon(this._imageAddon);
     this.term.loadAddon(this._searchAddon);
 
+    // @xterm/addon-image uses WebAssembly at the top level, so we load it dynamically to
+    // avoid crashing the app when WebAssembly is unavailable.
+    import('@xterm/addon-image').then(({ ImageAddon }) => {
+      this._imageAddon = new ImageAddon();
+      this.term.loadAddon(this._imageAddon);
+    }).catch(() => {});
```
Comment (ravicious) [inline web/packages/teleport/src/lib/term/terminal.ts]: Should we `logger.error` the error in the catch at least?

File: web/packages/teleport/src/SessionRecordings/view/player/tty/TtyPlayer.ts [hunk 2]
```diff
@@ -67,9 +66,16 @@ export class TtyPlayer extends Player<TtyEvent> {
...
-    this.addons.push(this.aspectFitAddon, linksAddon, imageAddon);
+    this.addons.push(this.aspectFitAddon, linksAddon);
+
+    // @xterm/addon-image uses WebAssembly at the top level, so we load it dynamically to
+    // avoid crashing the app when WebAssembly is unavailable.
+    import('@xterm/addon-image').then(({ ImageAddon }) => {
+      const imageAddon = new ImageAddon();
+      this.addons.push(imageAddon);
+      this.terminal?.loadAddon(imageAddon);
+    }).catch(() => {});
```
Comment (ravicious) [inline web/packages/teleport/src/SessionRecordings/view/player/tty/TtyPlayer.ts]: Same here wrt the error.

File: web/packages/teleport/src/lib/term/terminal.ts [hunk 3]
```diff
@@ -103,9 +102,15 @@ export default class TtyTerminal implements TerminalSearcher {
 
     this.term.loadAddon(this._fitAddon);
     this.term.loadAddon(this._webLinksAddon);
-    this.term.loadAddon(this._imageAddon);
     this.term.loadAddon(this._searchAddon);
 
+    // @xterm/addon-image uses WebAssembly at the top level, so we load it dynamically to
+    // avoid crashing the app when WebAssembly is unavailable.
+    import('@xterm/addon-image').then(({ ImageAddon }) => {
```
Comment (ravicious) [inline web/packages/teleport/src/lib/term/terminal.ts]: How does Vite actually manage that? Is `@xterm/addon-image` added to the app bundle but the actual "module" is then added dynamically with no extra network requests?

**Review by ravicious — APPROVED** [review]

File: web/packages/teleport/src/lib/term/terminal.ts (hunk 3 above)
Comment (bl-nero) [reply web/packages/teleport/src/lib/term/terminal.ts]: Also: won't this be a bad idea anyway (just as React's own lazy loading) because of our approach to managing JS bundle versions? If this leads to code splitting, I'd ask @avatus to look at it, since I remember he was deliberately turning off all splitting in order to have control over bundle versioning in self-hosted environments.

Comment (ryanclark) [reply web/packages/teleport/src/lib/term/terminal.ts]: Ah yeah that's a brain fart, a separate bundle was what I wanted to avoid. Not sure what I was thinking. I've replaced it with a Vite plugin that rewrites `WebAssembly` in `@xterm/addon-image` to a WASM shim that'll throw an error we log during `WebAssembly.instantiate` instead

image

File: web/packages/build/vite/guard-wasm.ts [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+  Memory: class { constructor() { throw new Error('WebAssembly is not available'); } },
+};
+`;
+
+export function guardWasmPlugin(): Plugin {
+  return {
+    name: 'guard-wasm',
+    transform(code, id) {
+      if (id.includes('@xterm/addon-image')) {
+        return shim + '\n' + code.replace(/\bWebAssembly\b/g, '__WASM__');
```
Comment (ravicious) [inline web/packages/build/vite/guard-wasm.ts:45]: This _feels_ brittle but I don't have a better idea here honestly. Hopefully no one defines their own `WebAssembly` identifier, which tbh isn't very likely to happen. And at the moment it runs only for `@xterm/addon-image` anyway.

**Review by ravicious — APPROVED** [review]
This was pretty easy to verify by going to `about:config` in Firefox and flipping `javascript.options.wasm` to `false`.

**Review by avatus — APPROVED** [review]
