### PR TITLE
fix double-init emission and buffer overflows

### LINKED ISSUE #7534: Rebooting 1 Auth Server Causes Unstable Cluster
### Description

**What happened**:
While performing kernel patching it was discovered when one auth node is restarted the cluster becomes very unstable.

dynamodb reads skyrocketed from 30 units baseline to more than 1000 units, upsized the provisioned read capacity to 2000 but reads then went up to 2000. The cluster continued to remain unstable until restarted all auth servers + all proxy servers.

**What you expected to happen**:
Teleport should continue normal operation as there are redundancies in with the Auth. There are 8 Auth nodes and they are sharing a Dynamodb backend table.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. restart teleport auth node

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:
  - This is a multi-region cluster. 4 Regions, 2 Auth per region (8 total), 1 NLB per region (4 total), 2 Proxies under 1 NLB for cluster
  - node have auth public addr to the auth nlb in region
  - All auth share single dynamodb table
  - Over 15k ssh nodes and over 80 trusted clusters

### Client Details
- Tsh version (`tsh version`): Teleport Enterprise FIPS 6.1.5

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

```
Jun 30 17:47:59 teleportauth-1 [kern.warning] /usr/local/bin/teleport[7672]:  WARN [NODE:1:CA] Re-init the cache on error: timeout waiting for watcher init. cache/cache.go:675
Jun 30 17:48:01 teleportauth-1 [kern.warning] /usr/local/bin/teleport[7672]:  WARN [AUTH]      "\nERROR REPORT:\nOriginal Error: *trace.NotFoundError cluster configuration not found\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/services/local/configuration.go:218 github.com/gravitational/teleport/lib/services/local.(*ClusterConfigurationService).GetClusterConfig\n\t/go/src/github.com/gravitational/teleport/lib/cache/cache.go:1014 github.com/gravitational/teleport/lib/cache.(*Cache).GetClusterConfig\n\t/go/src/github.com/gravitational/teleport/lib/auth/permissions.go:221 github.com/gravitational/teleport/lib/auth.(*authorizer).authorizeBuiltinRole\n\t/go/src/github.com/gravitational/teleport/lib/auth/permissions.go:116 github.com/gravitational/teleport/lib/auth.(*authorizer).fromUser\n\t/go/src/github.com/gravitational/teleport/lib/auth/permissions.go:102 github.com/gravitational/teleport/lib/auth.(*authorizer).Authorize\n\t/go/src/github.com/gravitational/teleport/lib/auth/apiserver.go:273 github.com/gravitational/teleport/lib/auth.(*APIServer).withAuth.func1\n\t/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:61 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/julienschmidt/httprouter/router.go:387 github.com/julienschmidt/httprouter.(*Router).ServeHTTP\n\t/go/src/github.com/gravitational/teleport/lib/httplib/httplib.go:173 github.com/gravitational/teleport/lib/httplib.RewritePaths.func1\n\t/opt/go/src/net/http/server.go:2042 net/http.HandlerFunc.ServeHTTP\n\t/go/src/github.com/gravitational/teleport/lib/auth/middleware.go:541 github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP\n\t/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/oxy/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP\n\t/opt/go/src/net/http/server.go:2843 net/http.serverHandler.ServeHTTP\n\t/opt/go/src/net/http/server.go:1925 net/http.(*conn).serve\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: cluster configuration not found" auth/apiserver.go:283

Jun 30 17:48:36 ops-ovb-teleportauth-1 [kern.err] /usr/local/bin/teleport[7672]:  ERRO [AUTH:1]    "Failed to retrieve client pool. Client cluster cluster-teleport, target cluster cluster-teleport, error:  \nERROR REPORT:\nOriginal Error: *trace.NotFoundError &#34;/authorities/host/cluster-teleport&#34; is not found\nStack Trace:\n\t/go/src/github.com/gravitational/teleport/lib/backend/dynamo/dynamodbbk.go:862 github.com/gravitational/teleport/lib/backend/dynamo.(*Backend).getKey\n\t/go/src/github.com/gravitational/teleport/lib/backend/dynamo/dynamodbbk.go:453 github.com/gravitational/teleport/lib/backend/dynamo.(*Backend).Get\n\t/go/src/github.com/gravitational/teleport/lib/backend/sanitize.go:97 github.com/gravitational/teleport/lib/backend.(*Sanitizer).Get\n\t/go/src/github.com/gravitational/teleport/lib/backend/report.go:161 github.com/gravitational/teleport/lib/backend.(*Reporter).Get\n\t/go/src/github.com/gravitational/teleport/lib/services/local/trust.go:207 github.com/gravitational/teleport/lib/services/local.(*CA).GetCertAuthority\n\t/go/src/github.com/gravitational/teleport/lib/cache/cache.go:942 github.com/gravitational/teleport/lib/cache.(*Cache).GetCertAuthority\n\t/go/src/github.com/gravitational/teleport/lib/auth/middleware.go:571 github.com/gravitational/teleport/lib/auth.ClientCertPool\n\t/go/src/github.com/gravitational/teleport/lib/auth/middleware.go:265 github.com/gravitational/teleport/lib/auth.(*TLSServer).GetConfigForClient\n\t/opt/go/src/crypto/tls/handshake_server.go:141 crypto/tls.(*Conn).readClientHello\n\t/opt/go/src/crypto/tls/handshake_server.go:40 crypto/tls.(*Conn).serverHandshake\n\t/opt/go/src/crypto/tls/conn.go:1362 crypto/tls.(*Conn).Handshake\n\t/go/src/github.com/gravitational/teleport/lib/multiplexer/tls.go:144 github.com/gravitational/teleport/lib/multiplexer.(*TLSListener).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: &#34;/authorities/host/cluster-teleport&#34; is not found." auth/middleware.go:271
```

We observed Dynamodb reads shot up from 35 units to 1000 units and requests became throttled as our provisioned capacity was 100 units. The following errors occurred:

this continued for sometime until the service failed:

```
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d524e6]
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: goroutine 1051 [running]:
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: github.com/gravitational/teleport/lib/cache.resourceKindFromResource(0x0, 0x0, 0xa, 0x2, 0x2a91820, 0x0)
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: /go/src/github.com/gravitational/teleport/lib/cache/collections.go:189 +0x26
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: github.com/gravitational/teleport/lib/cache.(*Cache).processEvent(0xc0000b4840, 0x32c45a0, 0xc001247dc0, 0x0, 0x0, 0x0, 0x0, 0x0)
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: /go/src/github.com/gravitational/teleport/lib/cache/cache.go:920 +0x4d
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch(0xc0000b4840, 0x32c45a0, 0xc001247dc0, 0x32cf020, 0xc00147ed20, 0xc000138780, 0x0, 0x0)
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: /go/src/github.com/gravitational/teleport/lib/cache/cache.go:858 +0x7fe
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: github.com/gravitational/teleport/lib/cache.(*Cache).update(0xc0000b4840, 0x32c45a0, 0xc001247dc0, 0x32cf020, 0xc00147ed20)
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: /go/src/github.com/gravitational/teleport/lib/cache/cache.go:669 +0xe8
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: created by github.com/gravitational/teleport/lib/cache.New
Jun 30 21:21:34 teleportauth-4.local teleport[15663]: /go/src/github.com/gravitational/teleport/lib/cache/cache.go:613 +0xd36
Jun 30 21:21:34 teleportauth-4.local systemd[1]: teleport.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 30 21:21:34 teleportauth-4.local systemd[1]: Unit teleport.service entered failed state.
Jun 30 21:21:34 teleportauth-4.local systemd[1]: teleport.service failed.
```

Other relevant logs we noticed:

```
Closing Watcher(name=auth:1:cache, prefixes=/access_requests, /apps/servers/default, /apps/sessions, /authentication/preference/general, /authorities, /authservers, /cluster_configuration/general, /cluster_configuration/name, /cluster_configuration/static_tokens, /databaseServers/default, /kubeServices, /namespaces, /nodes/default, /proxies, /remoteClusters, /reverseTunnels, /roles, /tokens, /tunnelConnections, /web/sessions, /web/tokens, /web/users, capacity=8192, size=8192), buffer overflow at 8192 elements. backend/buffer.go:171	4
 [NODE:1:CA] Failed to set tombstone: database is closed cache/cache.go:703
```

### PR DESCRIPTION
**Pull request by fspmarshall**
Fixes two related event system issues:

1. If a watcher was enqueued in an uninitialized fanout instance, it would recieve multiple init events when the fanout instance was initialized if the watcher was registered for more than one resource kind.  Watcher init emission is now protected by a `sync.Once`.
2. Backends in very large clusters could emit a massive number of simultaneous events which would trigger buffer overflow errors in backend event watchers.  Changed backend buffer to now observe a "grace period" where a watcher may exceed its allotted capacity, so long as it catches up before the grace period elapses.  This allows the watcher system to continue to prune slow chronically slow watchers without failing on spikes of activity.

The above issues could "feed into" one another, as errors in the buffer could cause caches to re-initialize, and double-inits could cause crashes that lead to flurries of reconnects and reset heartbeat intervals that would induce spiky load.

Fixes #7534

### CODE REVIEW

File: lib/backend/buffer.go [hunk 1]
```diff
@@ -327,6 +355,55 @@ func (w *BufferWatcher) Done() <-chan struct{} {
 	return w.ctx.Done()
 }
 
+// flushBacklog attempts to push any backlogged events into the
+// event channel.  returns true if backlog is empty.
+func (w *BufferWatcher) flushBacklog() (ok bool) {
```
Comment (codingllama) [inline lib/backend/buffer.go:360]: nit: named var unused

```suggestion
func (w *BufferWatcher) flushBacklog() bool {
```

File: lib/backend/buffer.go [hunk 2]
```diff
@@ -327,6 +355,55 @@ func (w *BufferWatcher) Done() <-chan struct{} {
...
+			w.backlog = w.backlog[i:]
+			return false
+		}
+	}
+	w.backlogSince = time.Time{}
+	w.backlog = nil
+	return true
+}
+
+// emit attempts to emit an event.  returns false if the watcher has
```
Comment (codingllama) [inline lib/backend/buffer.go:374]: nit:

```suggestion
// emit attempts to emit an event. Returns false if the watcher has
```

File: lib/backend/buffer.go [hunk 3]
```diff
@@ -327,6 +355,55 @@ func (w *BufferWatcher) Done() <-chan struct{} {
...
+// exceeded the backlog grace period.
+func (w *BufferWatcher) emit(e Event) (ok bool) {
```
Comment (codingllama) [inline lib/backend/buffer.go:376]: nit: same as above:

```suggestion
func (w *BufferWatcher) emit(e Event) bool {
```

File: lib/backend/buffer.go [hunk 4]
```diff
@@ -319,6 +344,9 @@ func (w *BufferWatcher) String() string {
 
 // Events returns events channel
 func (w *BufferWatcher) Events() <-chan Event {
+	w.bmu.Lock()
+	defer w.bmu.Unlock()
+	w.flushBacklog()
```
Comment (codingllama) [inline lib/backend/buffer.go:349]: Could you add a comment mentioning why it's OK not to check the result of flushBacklog here (and thus miss a possible backlogSince update)?

File: lib/backend/buffer_test.go [hunk 5]
```diff
@@ -96,8 +98,9 @@ func (s *BufferSuite) TestBufferSizesReset(c *check.C) {
 // TestWatcherSimple tests scenarios with watchers
 func (s *BufferSuite) TestWatcherSimple(c *check.C) {
 	ctx := context.TODO()
```
Comment (codingllama) [inline lib/backend/buffer_test.go:100]: Could we change this one to `context.Background()` since we are here?

File: lib/backend/buffer_test.go [hunk 6]
```diff
@@ -134,11 +137,69 @@ func (s *BufferSuite) TestWatcherSimple(c *check.C) {
 	}
 }
 
+// TestWatcherCapacity checks various watcher capacity scenarios
+func (s *BufferSuite) TestWatcherCapacity(c *check.C) {
+	const gracePeriod = time.Second
+
+	ctx := context.TODO()
```
Comment (codingllama) [inline lib/backend/buffer_test.go:144]: nit: context.Background instead of TODO - there is no TODO to address, since there is no other context to push here.

```suggestion
	ctx := context.Background()
```

File: lib/backend/buffer_test.go [hunk 7]
```diff
@@ -134,11 +137,69 @@ func (s *BufferSuite) TestWatcherSimple(c *check.C) {
...
+	w, err := b.NewWatcher(ctx, Watch{
+		QueueSize: 1,
+	})
+	c.Assert(err, check.IsNil)
+	defer w.Close()
+
+	select {
+	case e := <-w.Events():
+		c.Assert(e.Type, check.Equals, types.OpInit)
+	case <-time.After(100 * time.Millisecond):
```
Comment (codingllama) [inline lib/backend/buffer_test.go:161]: Is the timeout necessary? It doesn't look like there is room for flakiness here. I suggest we make this a single-case select and let `go test -timeout=...` deal with timing out the tests.

Same throughout.

File: lib/backend/buffer_test.go [hunk 8]
```diff
@@ -134,11 +137,69 @@ func (s *BufferSuite) TestWatcherSimple(c *check.C) {
...
+		c.Fatalf("Timeout waiting for event.")
+	}
+
+	// emit and then consume 10 events.  this is much larger than our queu size,
```
Comment (codingllama) [inline lib/backend/buffer_test.go:165]:
```suggestion
	// emit and then consume 10 events.  this is much larger than our queue size,
```

File: lib/backend/buffer_test.go [hunk 9]
```diff
@@ -134,11 +137,69 @@ func (s *BufferSuite) TestWatcherSimple(c *check.C) {
...
+	// but should succeed since we consume within our grace period.
+	for i := 0; i < 10; i++ {
+		b.Emit(Event{Item: Item{Key: []byte{Separator}, ID: int64(i + 1)}})
+	}
+	for i := 0; i < 10; i++ {
+		select {
+		case e := <-w.Events():
+			c.Assert(e.Item.ID, check.Equals, int64(i+1))
+		case <-time.After(100 * time.Millisecond):
```
Comment (codingllama) [inline lib/backend/buffer_test.go:174]: Ditto for the timeout?

File: lib/backend/buffer_test.go [hunk 10]
```diff
@@ -134,11 +137,69 @@ func (s *BufferSuite) TestWatcherSimple(c *check.C) {
...
+			c.Fatalf("Timeout waiting for event.")
+		}
+	}
+
+	for i := 0; i < 10; i++ {
+		b.Emit(Event{Item: Item{Key: []byte{Separator}, ID: int64(i + 10)}})
+	}
+
+	// force grace period to expire
+	time.Sleep(gracePeriod)
```
Comment (codingllama) [inline lib/backend/buffer_test.go:184]: Could we use a fake clock and avoid the sleep? If you prefer not to we can also replace time.Now for testing.

File: lib/backend/buffer.go [hunk 11]
```diff
@@ -31,11 +32,33 @@ import (
...
+	gracePeriod time.Duration
+	capacity    int
+}
+
+type BufferOption func(*bufferConfig)
+
+// BufferCapacity sets the event capacity of the circular buffer.
+func BufferCapacity(c int) BufferOption {
+	return func(cfg *bufferConfig) {
+		cfg.capacity = c
```
Comment (codingllama) [inline lib/backend/buffer.go:45]: Should we guard against zero or negative capacity? Maybe logging and setting the default?

File: lib/backend/buffer.go [hunk 12]
```diff
@@ -31,11 +32,33 @@ import (
...
+	}
+}
+
+// BacklogGracePeriod sets the amount of time a watcher with a backlog will be tolerated.
+func BacklogGracePeriod(d time.Duration) BufferOption {
+	return func(cfg *bufferConfig) {
+		cfg.gracePeriod = d
```
Comment (codingllama) [inline lib/backend/buffer.go:52]: Should we guard against a zeroed period? Similarly as above.

File: lib/services/fanout.go [hunk 13]
```diff
@@ -284,13 +283,28 @@ func newFanoutWatcher(ctx context.Context, f *Fanout, watch types.Watch) (*fanou
...
+	watch    types.Watch
+	eventC   chan types.Event
+	cancel   context.CancelFunc
+	ctx      context.Context
+	initOnce sync.Once
+	initOk   bool
+}
+
+// init transmits the OpInit event.  safe to double-call.
+func (w *fanoutWatcher) init() (ok bool) {
```
Comment (codingllama) [inline lib/services/fanout.go:298]: nit:

```suggestion
func (w *fanoutWatcher) init() bool {
```

File: lib/services/fanout_test.go [hunk 14]
```diff
@@ -32,15 +32,40 @@ func TestFanoutWatcherClose(t *testing.T) {
...
+func TestFanoutInit(t *testing.T) {
+	f := NewFanout()
+
+	w, err := f.NewWatcher(context.TODO(), types.Watch{
+		Name:  "test",
+		Kinds: []types.WatchKind{{Name: "spam"}, {Name: "eggs"}},
+	})
+	require.NoError(t, err)
+
+	f.SetInit()
```
Comment (codingllama) [inline lib/services/fanout_test.go:57]: Test an init failure as well?

File: lib/backend/buffer.go (hunk 1 above)
Comment (fspmarshall) [reply lib/backend/buffer.go:381]: This is deliberate.  IMO the `(ok bool)` pattern is a useful idiom for distinguishing between bools as "checks" and bools as success/failure indicators.

File: lib/backend/buffer.go (hunk 3 above)
Comment (fspmarshall) [reply lib/backend/buffer.go:397]: same as above.

File: lib/services/fanout.go (hunk 13 above)
Comment (fspmarshall) [reply lib/services/fanout.go:298]: same as above.

File: lib/services/fanout_test.go (hunk 14 above)
Comment (fspmarshall) [reply lib/services/fanout_test.go:58]: Init itself doesn't fail (just sets a bool).  Only individual watchers fail (which will show up below).

File: lib/backend/buffer.go (hunk 1 above)
Comment (codingllama) [reply lib/backend/buffer.go:381]: Ack. Fair enough.

**Review by codingllama — APPROVED** [review]
LGTM.

Please don't squash review fixes (at least before merging). It makes it hard to figure out what you changed since the initial review, specially after a few days.

**Review by rosstimothy — APPROVED** [review]

**Review by r0mant — APPROVED** [review]
lgtm
