### PR TITLE
Stop validating schema for labels in k8s operator

### LINKED ISSUE #15204: Teleport Operator: `<resource>_labels` does not accept wildcard matcher
Expected behavior:
We must be able to set wildcard when configuring Allow rules for any `<resource>_labels` of a Role.

```yaml
kind: role
version: v5
metadata:
  name: interns
spec:
  allow:
    node_labels:
      '*': ['*']
```

Current behavior:
This returns an error:
```
# * <nil>: Invalid value: "The edited file failed validation": ValidationError(TeleportRole.spec.allow.app_labels): invalid type for dev.teleport.resources.v5.TeleportRole.spec.allow.app_labels: got "array", expected "map"
```

Adding another value to the list allows for the object to be correctly loaded
```yaml
    node_labels:
      '*': ['*', 'test']
```
But then Teleport complains of 
```
 "error": "selector *:<val> is not supported"
```
https://github.com/gravitational/teleport/blob/5485498775df97997f71c59b398027366423f268/api/types/role.go#L777

Bug details:
- Teleport version
10.1.2
- Recreation steps
`kubectl create -f ` using the role described above or create the following test in Roles

Or use this test
```go

func TestRoleCreationFromYAML(t *testing.T) {
	ctx := context.Background()

	teleportServer, operatorName := defaultTeleportServiceConfig(t)

	require.NoError(t, teleportServer.Start())

	tClient := clientForTeleport(t, teleportServer, operatorName)
	k8sClient := startKubernetesOperator(t, tClient)

	namespace := createNamespaceForTest(t, k8sClient)
	roleName := "interns"

	roleYAML := yaml.NewYAMLOrJSONDecoder(bytes.NewBuffer([]byte(`
kind: role
version: v5
metadata:
  name: interns
spec:
  allow:
    node_labels:
      '*': ['*']
`)), 1024)

	var roleX resourcesv5.TeleportRole
	err := roleYAML.Decode(&roleX)
	require.NoError(t, err)

	roleX.Namespace = namespace.Name
	err = k8sClient.Create(ctx, &roleX)
	require.NoError(t, err)

	fastEventually(t, func() bool {
		tRole, err := tClient.GetRole(ctx, roleName)
		if trace.IsNotFound(err) {
			return false
		}
		require.NoError(t, err)

		require.Equal(t, tRole.GetName(), roleName)

		require.Contains(t, tRole.GetMetadata().Labels, types.OriginLabel)
		require.Equal(t, tRole.GetMetadata().Labels[types.OriginLabel], types.OriginKubernetes)

		return true
	})

	// The role is deleted in K8S
	k8sDeleteRole(ctx, t, k8sClient, roleName, namespace.Name)

	fastEventually(t, func() bool {
		_, err := tClient.GetRole(ctx, roleName)
		return trace.IsNotFound(err)
	})
}
```
- Debug logs
See above

### PR DESCRIPTION
**Pull request by hugoShaka**
Proposal to fix #15204

### CODE REVIEW

File: operator/controllers/resources/role_controller_test.go [hunk 1]
```diff
@@ -73,6 +75,62 @@ func TestRoleCreation(t *testing.T) {
...
+
+	roleYAML := yaml.NewYAMLOrJSONDecoder(bytes.NewBuffer([]byte(`
+kind: role
+version: v5
+metadata:
+  name: interns
+spec:
+  allow:
+    node_labels:
+      'foo': ['bar']
```
Comment (marcoandredinis) [inline operator/controllers/resources/role_controller_test.go:99]: I'm confident it should work, but can we please add the example that triggered the issue as test?
```yaml
'*': ['*']
```

File: examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml [hunk 2]
```diff
@@ -40,9 +40,7 @@ spec:
                 properties:
                   app_labels:
                     additionalProperties:
```
Comment (codingllama) [inline examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml:42]: What's the implication of dropping `items` and `type`? Could I do something totally wild like `app_labels: 1` ?

File: operator/controllers/resources/role_controller_test.go [hunk 3]
```diff
@@ -73,6 +75,62 @@ func TestRoleCreation(t *testing.T) {
...
+
+	require.NoError(t, teleportServer.Start())
+
+	tClient := clientForTeleport(t, teleportServer, operatorName)
+	k8sClient := startKubernetesOperator(t, tClient)
+
+	namespace := createNamespaceForTest(t, k8sClient)
+	roleName := "interns"
+
+	roleYAML := yaml.NewYAMLOrJSONDecoder(bytes.NewBuffer([]byte(`
```
Comment (codingllama) [inline operator/controllers/resources/role_controller_test.go:91]: Do you mind refactoring into a table test, so we can add more examples? (Like the totally absurd one I mentioned earlier?)

File: operator/controllers/resources/role_controller_test.go [hunk 4]
```diff
@@ -73,6 +75,62 @@ func TestRoleCreation(t *testing.T) {
...
+kind: role
+version: v5
+metadata:
+  name: interns
+spec:
+  allow:
+    node_labels:
+      '*': ['*']
```
Comment (codingllama) [inline operator/controllers/resources/role_controller_test.go:99]: Is `'*': '*'` also OK? Mind adding a test for it?

Also, since we are here, let's test something more reasonable too, like two regular labels and multiple labels in the array.

File: operator/controllers/resources/role_controller_test.go [hunk 5]
```diff
@@ -73,6 +75,62 @@ func TestRoleCreation(t *testing.T) {
...
+`)), 1024)
+
+	var roleX resourcesv5.TeleportRole
+	err := roleYAML.Decode(&roleX)
+	require.NoError(t, err)
```
Comment (codingllama) [inline operator/controllers/resources/role_controller_test.go:104]: Where does the test break before the change? Could we add some messages to the require calls so it's easier to distinguish what is setup and what is the focus of the test?

File: operator/crdgen/schemagen.go [hunk 6]
```diff
@@ -167,6 +167,19 @@ func (generator *SchemaGenerator) traverseInner(message *Message) (*Schema, erro
...
 
+		// Labels are relying on `utils.Strings`, which can either marshall as an array of strings or a single string
+		// This does not pass Schema validation from the apiserver, to workaround we don't specify type for those fields
+		// and ask Kubernetes to preserve unknown fields.
+		if field.CustomType() == "Labels" {
+			prop.Type = "object"
+			truthy := true
+			prop.AdditionalProperties = &apiextv1.JSONSchemaPropsOrBool{
+				Schema: &apiextv1.JSONSchemaProps{
+					XPreserveUnknownFields: &truthy,
```
Comment (codingllama) [inline operator/crdgen/schemagen.go:178]:
```suggestion
			preserveUnknownFields := true
			prop.AdditionalProperties = &apiextv1.JSONSchemaPropsOrBool{
				Schema: &apiextv1.JSONSchemaProps{
					XPreserveUnknownFields: &preserveUnknownFields,
```

**Review by codingllama — COMMENTED** [review]
Apologies for the silly Qs, I'm not familiar with this part of the codebase.

**Comment by codingllama** [comment]
PR title change is a suggestion, feel free to revert.

File: examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml (hunk 2 above)
Comment (hugoShaka) [reply examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml:42]: Yes, app_labels is still an object but we don't validate anything in it, so you could totally do
```
app_labels:
  key: value
  key2: ["val1", "val2"]
  key3: {"totally":"invalid"}
  key4: 1
```

This is an obviously terrible solution, the alternative is to change the `utils.Strings` marshalling behaviour. @r0mant  thinks we should not touch `utils.Strings` but @marcoandredinis  and @tigrato don't agree. I'll switch back the PR to draft until we reach a consensus

Comment (marcoandredinis) [reply examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml:42]: Please note that Teleport would reject the invalid ones
So, while it would pass the K8S validations, changes wouldn't be persisted and an error would be returned to the user

Comment (codingllama) [reply examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml:42]: I'd be wary of messing with `utils.Strings`, but no strong opinions on my part.

Comment (r0mant) [reply examples/chart/teleport-cluster/charts/teleport-operator/templates/resources.teleport.dev_roles.yaml:42]: Yeah I think changing utils.Strings marshaling is asking for more trouble than needed at this point.

File: operator/controllers/resources/role_controller_test.go (hunk 5 above)
Comment (hugoShaka) [reply operator/controllers/resources/role_controller_test.go]: I refacto-ed the test, is this clearer now ?

**Comment by hugoShaka** [comment]
After more testing I had to change the types used by the `TeleportRole` controller. It now decodes everything into an unstructured object and we can "gracefully" handle when invalid resources are sent to us.

I think the PR is now in good-enough shape for another review.

File: operator/controllers/resources/role_controller_test.go [hunk 7]
```diff
@@ -33,57 +39,189 @@ import (
 	resourcesv5 "github.com/gravitational/teleport/operator/apis/resources/v5"
 )
 
+// When I create a TeleportRole CR in Kubernetes, the corresponding TeleportRole must be created in Teleport
+// When I delete a TeleportRole CR in Kubernetes, the corresponding TeleportRole must be deleted in Teleport
```
Comment (marcoandredinis) [inline operator/controllers/resources/role_controller_test.go:43]:
```suggestion
// When I delete a TeleportRole CR in Kubernetes, the corresponding TeleportRole must be deleted in Teleport
```

File: operator/controllers/resources/role_controller_test.go [hunk 8]
```diff
@@ -33,57 +39,189 @@ import (
...
 		require.Equal(t, tRole.GetName(), roleName)
-
 		require.Contains(t, tRole.GetMetadata().Labels, types.OriginLabel)
 		require.Equal(t, tRole.GetMetadata().Labels[types.OriginLabel], types.OriginKubernetes)
 
 		return true
 	})
 
-	// The role is deleted in K8S
+	// Cleanup and test, we delete the role in Kubernetes```
```
Comment (marcoandredinis) [inline operator/controllers/resources/role_controller_test.go:67]:
```suggestion
	// Cleanup and test, we delete the role in Kubernetes
```

File: operator/controllers/resources/role_controller_test.go [hunk 9]
```diff
@@ -33,57 +39,189 @@ import (
...
+			obj.Object["spec"] = roleManifest
+			obj.SetName(roleName)
+			obj.SetNamespace(ns.Name)
+			err = k8sClient.Create(ctx, obj)
+			require.NoError(t, err)
+
+			// If failure is expected we should not see the resource in Teleport
+			if tc.shouldFail {
+				// We wait 1 second to ensure reconciliation happened
+				time.Sleep(time.Second)
```
Comment (marcoandredinis) [inline operator/controllers/resources/role_controller_test.go:176]: Can we replace this `Sleep` with an `Eventually`?

File: operator/controllers/resources/role_controller_test.go [hunk 10]
```diff
@@ -33,57 +39,189 @@ import (
...
+`),
+			true,
+			nil,
+		},
+	}
 
-	teleportServer, operatorName := defaultTeleportServiceConfig(t)
+	for _, tc := range tests {
+		t.Run(tc.name, func(t *testing.T) {
+			// Creating the Kubernetes resource. We are using an untyped client to be able to create invalid resources.
```
Comment (marcoandredinis) [inline operator/controllers/resources/role_controller_test.go:159]: I think we can mark the inner `t *testing.T` test as Parallel 
Each test has its own role name, so it should be safe

File: operator/controllers/resources/role_controller_test.go (hunk 9 above)
Comment (hugoShaka) [reply operator/controllers/resources/role_controller_test.go:176]: Not really, because if I understand correctly `Evevntally` will retry gradually. Here I want to assert this does not work after 1 second. If I use eventually it will fail on the first try, maybe before the operator finishes its reconciliation. I think the way to fix this test would be to get the kubernetes object and validate the error condition is here. I'll fix it today.

File: operator/controllers/resources/role_controller_test.go [hunk 11]
```diff
@@ -33,57 +39,189 @@ import (
...
+  - ubuntu
+  - root
+`),
+			false,
+			&types.RoleSpecV5{
+				Allow: types.RoleConditions{
+					Logins: []string{"ubuntu", "root"},
+				},
+			},
+		},
```
Comment (codingllama) [inline operator/controllers/resources/role_controller_test.go:99]: nit: Use labeled struct initialization? It has better readability and is easier to extend later.

```suggestion
		{
			name: "Valid login list",
			roleSpecYAML: []byte(`
allow:
  logins:
  - ubuntu
  - root
`),
			shouldFail: false,
			expectedSpec: &types.RoleSpecV5{
				Allow: types.RoleConditions{
					Logins: []string{"ubuntu", "root"},
				},
			},
		},
```

Same for others.

File: operator/controllers/resources/role_controller_test.go [hunk 12]
```diff
@@ -33,57 +39,189 @@ import (
...
 	})
 }
 
-func TestRoleDeletionDrift(t *testing.T) {
-	ctx := context.Background()
+func TestRoleCreationFromYAML(t *testing.T) {
+	ctx, tClient, k8sClient, ns := setupKubernetesAndTeleport(t)
+	tests := []struct {
+		name         string
+		roleSpecYAML []byte
```
Comment (codingllama) [inline operator/controllers/resources/role_controller_test.go:81]: Use `string` instead of `[]byte`?

File: operator/controllers/resources/role_controller_test.go [hunk 13]
```diff
@@ -197,6 +326,20 @@ func TestRoleUpdate(t *testing.T) {
 	})
 }
 
+func setupKubernetesAndTeleport(t *testing.T) (context.Context, auth.ClientI, kclient.Client, *v1.Namespace) {
```
Comment (codingllama) [inline operator/controllers/resources/role_controller_test.go:329]: Let's wrap the response in a struct, so each component has a name.

Returning a context also looks a bit like a smell - I'd either keep it entirely within the function or get it as a parameter.

File: operator/controllers/resources/utils.go [hunk 14]
```diff
@@ -94,3 +98,29 @@ func getReconciliationCondition(err error) metav1.Condition {
...
+		}
+	} else {
+		condition = metav1.Condition{
+			Type:    ConditionTypeValidStructure,
+			Status:  metav1.ConditionFalse,
+			Reason:  ConditionReasonFailedToDecode,
+			Message: fmt.Sprintf("Failed to decode Kubernetes CR: %s", err),
+		}
+	}
+	return condition
```
[the remark this answers is not in the document]
Comment (codingllama) [reply operator/controllers/resources/utils.go:119]: +1

File: operator/controllers/resources/utils.go [hunk 15]
```diff
@@ -94,3 +98,29 @@ func getReconciliationCondition(err error) metav1.Condition {
 
 	return condition
 }
+
+func getValidStructureCondition(err error) metav1.Condition {
```
Comment (codingllama) [inline operator/controllers/resources/utils.go:102]: Maybe: getStructureConditionFromError?  I think this deserves a godoc explaining what is the error we are supposed to pass to it.

File: operator/controllers/resources/utils.go [hunk 16]
```diff
@@ -94,3 +98,29 @@ func getReconciliationCondition(err error) metav1.Condition {
...
+			Type:    ConditionTypeValidStructure,
+			Status:  metav1.ConditionFalse,
+			Reason:  ConditionReasonFailedToDecode,
+			Message: fmt.Sprintf("Failed to decode Kubernetes CR: %s", err),
+		}
+	}
+	return condition
+}
+
+func getUnstructuredObjectFromGVK(gvk schema.GroupVersionKind) *unstructured.Unstructured {
```
Comment (codingllama) [inline operator/controllers/resources/utils.go:122]: Move this and getValidStructureCondition to role_controller.go? They don't seem to be used in other files.

File: operator/controllers/resources/role_controller_test.go (hunk 5 above)
Comment (codingllama) [reply operator/controllers/resources/role_controller_test.go]: Better, thanks!

**Review by codingllama — COMMENTED** [review]
Mostly style nits.

File: operator/crdgen/schemagen.go [hunk 17]
```diff
@@ -167,6 +167,19 @@ func (generator *SchemaGenerator) traverseInner(message *Message) (*Schema, erro
 			prop.Nullable = true
 		}
 
+		// Labels are relying on `utils.Strings`, which can either marshall as an array of strings or a single string
+		// This does not pass Schema validation from the apiserver, to workaround we don't specify type for those fields
+		// and ask Kubernetes to preserve unknown fields.
+		if field.CustomType() == "Labels" {
```
[the remark this answers is not in the document]
Comment (hugoShaka) [reply operator/crdgen/schemagen.go:173]: The issue only happens when we use custom types that don't marshall consistently. As we're inconsistant in our inconsistencies `User.Traits` are not leveraging the `utils.Strings` type, hence everything is ok.

I added similar YAMLSpec tests for users anyway as this will be handy if we need to reproduce issues.

File: operator/controllers/resources/role_controller_test.go (hunk 13 above)
Comment (hugoShaka) [reply operator/controllers/resources/role_controller_test.go]: Done, and extended to user tests as well.

File: operator/controllers/resources/role_controller_test.go (hunk 9 above)
Comment (marcoandredinis) [reply operator/controllers/resources/role_controller_test.go:177]: Oh I see.
So, we should ideally wait for the reconciliation to happen :thinking:
Yeah, validating the error condition of the K8s object seems to be a good approach :+1:

File: operator/controllers/resources/role_controller.go [hunk 18]
```diff
@@ -74,42 +96,68 @@ func (r *RoleReconciler) Delete(ctx context.Context, obj kclient.Object) error {
...
+		k8sResource, true, /* returnUnknownFields */
+	)
+	newStructureCondition := getStructureConditionFromError(err)
+	meta.SetStatusCondition(&k8sResource.Status.Conditions, newStructureCondition)
+	if err != nil {
+		// We update the status conditions on exit and aggregate the eventual error with the original one.
+		return trace.NewAggregate(
+			trace.WrapWithMessage(
+				err,
+				fmt.Sprintf("failed to convert unstructured Object into resource object: %T", k8sResource)),
```
Comment (codingllama) [inline operator/controllers/resources/role_controller.go:118]:
```suggestion
			trace.Wrap(err, "failed to convert unstructured Object into resource object: %T", k8sResource),
```

File: operator/controllers/resources/suite_test.go [hunk 19]
```diff
@@ -200,3 +200,38 @@ func validRandomResourceName(prefix string) string {
...
+	require.NoError(t, teleportServer.Start())
+
+	tClient := clientForTeleport(t, teleportServer, operatorName)
+	k8sClient := startKubernetesOperator(t, tClient)
+
+	ns := createNamespaceForTest(t, k8sClient)
+	return testSetup{tClient: tClient, k8sClient: k8sClient, namespace: ns}
+}
+
+func teleportCreateDummyRole(ctx context.Context, t *testing.T, roleName string, tClient auth.ClientI) error {
```
Comment (codingllama) [inline operator/controllers/resources/suite_test.go:222]: nit: Let's be consistent with the order of context.Context and testing.T between this and setupKubernetesAndTeleport.

Comment (codingllama) [inline operator/controllers/resources/suite_test.go:222]: Either ditch the error return from the func or remove the testing.T parameter? As it stands, this always fails instead of returning an error.

File: operator/controllers/resources/role_controller_test.go [hunk 20]
```diff
@@ -29,68 +34,203 @@ import (
...
-
-	teleportServer, operatorName := defaultTeleportServiceConfig(t)
-
-	require.NoError(t, teleportServer.Start())
-
-	tClient := clientForTeleport(t, teleportServer, operatorName)
-	k8sClient := startKubernetesOperator(t, tClient)
-
-	ns := createNamespaceForTest(t, k8sClient)
+	setup := setupKubernetesAndTeleport(t, ctx)
```
Comment (codingllama) [inline operator/controllers/resources/role_controller_test.go:44]: Should we free resources like the auth client and k8s client?

Maybe add a Close method to setup so we can immediately follow this with `defer setup.Close()`?

Same for other usages.

File: operator/controllers/resources/user_controller_test.go [hunk 21]
```diff
@@ -31,26 +35,26 @@ import (
...
-	ctx := context.Background()
-
-	teleportServer, operatorName := defaultTeleportServiceConfig(t)
+const TeleportUserKind = "TeleportUser"
 
-	require.NoError(t, teleportServer.Start())
-
-	tClient := clientForTeleport(t, teleportServer, operatorName)
-	k8sClient := startKubernetesOperator(t, tClient)
+var TeleportUserGVK = schema.GroupVersionKind{
```
Comment (codingllama) [inline operator/controllers/resources/user_controller_test.go:40]: nit: Use private / non-exported variables?

File: operator/controllers/resources/role_controller.go [hunk 22]
```diff
@@ -74,10 +98,33 @@ func (r *RoleReconciler) Delete(ctx context.Context, obj kclient.Object) error {
...
 	}
+	k8sResource := &resourcesv5.TeleportRole{}
+	err := runtime.DefaultUnstructuredConverter.FromUnstructuredWithValidation(u.Object, k8sResource, true)
+
+	newStructureCondition := getValidStructureCondition(err)
+	meta.SetStatusCondition(&k8sResource.Status.Conditions, newStructureCondition)
+
+	// We want to update Status.Conditions at the end of the reconciliation, or if the reconciliation fails
+	defer func() {
+		err := r.Status().Update(ctx, k8sResource)
```
[the remark this answers is not in the document]
Comment (codingllama) [reply operator/controllers/resources/role_controller.go]: The aggregate does looks a bit off, I think we can just log the Update error if it happens. WDYT?

File: operator/controllers/resources/user_controller_test.go [hunk 23]
```diff
@@ -65,35 +69,163 @@ func TestUserCreation(t *testing.T) {
...
+			obj.Object["spec"] = userManifest
+			obj.SetName(userName)
+			obj.SetNamespace(setup.namespace.Name)
+			err = setup.k8sClient.Create(ctx, obj)
+			require.NoError(t, err)
+
+			// If failure is expected we should not see the resource in Teleport
+			if tc.shouldFail {
+				// We wait 1 second to ensure reconciliation happened
+				time.Sleep(time.Second)
```
Comment (codingllama) [inline operator/controllers/resources/user_controller_test.go:165]: As the other thread said, let's try and refactor the Sleeps out. This is flakiness waiting to happen.

File: operator/controllers/resources/utils.go (hunk 16 above)
Comment (codingllama) [reply operator/controllers/resources/utils.go]: That sounds OK. Thanks.

File: operator/controllers/resources/role_controller.go [hunk 24]
```diff
@@ -74,42 +101,81 @@ func (r *RoleReconciler) Delete(ctx context.Context, obj kclient.Object) error {
...
+		k8sResource, true, /* returnUnknownFields */
+	)
+	newStructureCondition := getStructureConditionFromError(err)
+	meta.SetStatusCondition(&k8sResource.Status.Conditions, newStructureCondition)
+	if err != nil {
+		// We update the status conditions on exit
+		statusErr := r.Status().Update(ctx, k8sResource)
+		if statusErr != nil && !errors.Is(statusErr, &json.UnmarshalTypeError{}) {
+			log.Errorf("Failed to report error in status conditions: %s", statusErr)
+		}
```
Comment (codingllama) [inline operator/controllers/resources/role_controller.go:123]: Suggestion:

Extract:

```go
	silentUpdateStatus := func() {
		if err := r.Status().Update(ctx, k8sResource); err != nil {
			log.Errorf("Failed to report error in status conditions: %s", err)
		}
	}
```

and then changes calls to:

```suggestion
		silentUpdateStatus()
```

Note that I dropped the special handling of err; unless we expect UnmarshalTypeError to be _very_ common then we should be OK logging them.

File: operator/controllers/resources/role_controller.go [hunk 25]
```diff
@@ -74,42 +101,81 @@ func (r *RoleReconciler) Delete(ctx context.Context, obj kclient.Object) error {
...
+		if statusErr != nil {
+			log.Errorf("Error while writing status conditions: %s", statusErr)
+		}
 		return trace.Wrap(err)
 	}
-	return err
+
+	// We update the status conditions on exit
+	statusErr := r.Status().Update(ctx, k8sResource)
+	return trace.Wrap(statusErr)
```
Comment (codingllama) [inline operator/controllers/resources/role_controller.go:178]: Simplify?

```suggestion
	return trace.Wrap(r.Status().Update(ctx, k8sResource))
```

File: operator/controllers/resources/role_controller_test.go (hunk 20 above)
Comment (codingllama) [reply operator/controllers/resources/role_controller_test.go]: I think this one is still an issue.

**Review by codingllama — COMMENTED** [review]
We're getting there, nice to see the sleeps gone.

Let's cut down on some of the repetition and address the comment about closing test resources, but then I suppose that's it.

File: operator/controllers/resources/role_controller.go (hunk 24 above)
Comment (hugoShaka) [reply operator/controllers/resources/role_controller.go]: Done

File: operator/controllers/resources/role_controller.go (hunk 25 above)
Comment (hugoShaka) [reply operator/controllers/resources/role_controller.go]: Done

File: operator/controllers/resources/role_controller_test.go (hunk 20 above)
Comment (hugoShaka) [reply operator/controllers/resources/role_controller_test.go]: kube client does not seem to offer a close/cleanup method (or at least I was not able to find one).

I added teleport client & server cleanup in `setupKubernetesAndTeleport`.

**Review by codingllama — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]
