### PR TITLE
Fix WebUI Admin Action infinite retry with no MFA devices

### LINKED ISSUE #51105: User creation hangs in the web UI with no error message if no MFA method is added
Expected behavior:
- Web UI returns clear error message if the user cannot complete MFA check for administrative action

Current behavior:
- Web UI simply hangs with no error message when user tries to "Create New User" if user has no MFA method added

Bug details:
- Teleport version: 17.1.4
- Recreation steps: log in to a user with the `editor` role --> ensure that the user does not have an MFA methods added (remove them if necessary) --> go to the "Users" tab and try creating a new user, click save --> hangs

### PR DESCRIPTION
**Pull request by Joerger**
Changelog: Fixed a bug where performing an admin action in the WebUI would hang indefinitely instead of getting an actionable error if the user has no MFA devices registered.

https://github.com/gravitational/teleport/pull/49679 and subsequently https://github.com/gravitational/teleport/pull/50570 introduced a change where `getMfaChallengeResponse` could return `null | undefined` when the user had no MFA challenges (no devices or not required). `fetchJsonWithMfaAuthnRetry` expects `getMfaChallengeResponse` to return `{}` in these cases, and will retry with MFA until it gets either an empty or non-empty object.

This PR fixes the issue by:
1.  addressing the recursive `fetchJsonWithMfaAuthnRetry` which could result in an infinite loop. It's no longer recursive so it will only retry once even if null or undefined is received.
2. Reverting part of https://github.com/gravitational/teleport/pull/50570/files and instead making `getMfaChallengeResponse` return `{}` so we can properly determine at any point whether an mfa response is undefined or an empty response resulting from a no-op challenge attempt (no devices or not required).

Closes https://github.com/gravitational/teleport/issues/51105

image

### CODE REVIEW

File: web/packages/teleport/src/services/api/api.ts
Comment (ravicious) [inline web/packages/teleport/src/services/api/api.ts:1]: The test file under `web/packages/teleport/src/services/api/api.test.ts` should be updated to say `fetchJsonWithMfaAuthnRetry` instead of `fetchJson`, since `fetchJson` doesn't exist anymore.

File: web/packages/teleport/src/services/api/api.ts [hunk 1]
```diff
@@ -142,66 +142,30 @@ const api = {
...
-    const shouldRetry = isAdminActionMfaError && !mfaResponse;
-    if (!shouldRetry) {
-      throw new ApiError({
-        message: parseError(json),
-        response,
-        proxyVersion: parseProxyVersion(json),
-        messages: json.messages,
-      });
-    }
+  async getAdminActionMfaResponse(allowReuse?: boolean) {
```
Comment (ravicious) [inline web/packages/teleport/src/services/api/api.ts:156]: It looks like the `allowReuse` argument is not used anymore?

File: web/packages/teleport/src/services/api/api.ts
Comment (ravicious) [inline web/packages/teleport/src/services/api/api.ts:1]: Tests for api.fetch are failing because api.fetch is incorrectly mocked, this should fix them. It'd be good to add tests for `fetchJsonWithMfaAuthnRetry` though.

<details>

```diff
diff --git a/web/packages/teleport/src/services/api/api.test.ts b/web/packages/teleport/src/services/api/api.test.ts
index 2cf717cfda8..48493586b88 100644
--- a/web/packages/teleport/src/services/api/api.test.ts
+++ b/web/packages/teleport/src/services/api/api.test.ts
@@ -16,6 +16,7 @@
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
  */
 
+import { MfaChallengeResponse } from '../mfa';
 import api, {
   defaultRequestOptions,
   getAuthHeaders,
@@ -24,9 +25,18 @@ import api, {
 } from './api';
 
 describe('api.fetch', () => {
-  const mockedFetch = jest.spyOn(global, 'fetch').mockResolvedValue({} as any); // we don't care about response
+  let mockedFetch: jest.SpiedFunction<typeof fetch>;
+  beforeEach(() => {
+    mockedFetch = jest
+      .spyOn(global, 'fetch')
+      .mockResolvedValue({ json: async () => ({}), ok: true } as Response); // we don't care about response
+  });
+
+  afterEach(() => {
+    jest.resetAllMocks();
+  });
 
-  const mfaResp = {
+  const mfaResp: MfaChallengeResponse = {
     webauthn_response: {
       id: 'some-id',
       type: 'some-type',
@@ -43,7 +53,7 @@ describe('api.fetch', () => {
     },
   };
 
-  const customOpts = {
+  const customOpts: RequestInit = {
     method: 'POST',
     // Override the default header from `defaultRequestOptions`.
     headers: {
@@ -51,10 +61,6 @@ describe('api.fetch', () => {
     },
   };
 
-  afterEach(() => {
-    jest.resetAllMocks();
-  });
-
   test('default (no optional params provided)', async () => {
     await api.fetch('/something');
     expect(mockedFetch).toHaveBeenCalledTimes(1);

```
</details>

**Review by ravicious — COMMENTED** [review]
Looks good, but there are still a few failing tests, even after fixing those in api.test.ts.

File: web/packages/teleport/src/services/api/api.ts [hunk 2]
```diff
@@ -149,6 +149,8 @@ const api = {
       if (!mfaResponse && isAdminActionRequiresMfaError(err)) {
         mfaResponse = await api.getAdminActionMfaResponse();
         return await api.fetch(url, customOptions, mfaResponse);
+      } else {
+        throw err;
```
Comment (ravicious) [inline web/packages/teleport/src/services/api/api.ts:153]: Omg good catch, I missed this.

File: web/packages/teleport/src/services/api/api.ts
Comment (ravicious) [inline web/packages/teleport/src/services/api/api.ts:1]: Leaving a preemptive approval, but how do I even test it, bar what Xin described in the issue? If I set second factor to optional, I cannot even log in as a user with no MFA. The login form shows "t is undefined" error and I'm forced to select a multi-factor type anyway.

I managed to work around this by choosing an authenticator app as the MFA type and then providing a bogus code. But how is it supposed to work for normal users? 🤔

**Review by ravicious — APPROVED** [review]

File: web/packages/teleport/src/services/api/api.ts [hunk 3]
```diff
@@ -142,66 +142,31 @@ const api = {
...
-        /* Don't remember location after login, since they may no longer have access to the page they were on. */
-        rememberLocation: false,
-        /* Show "access changed" notice on login page. */
-        withAccessChangedMessage: true,
-      });
-      return;
+      // Retry with MFA if we get an admin action MFA error.
+      if (!mfaResponse && isAdminActionRequiresMfaError(err)) {
+        mfaResponse = await api.getAdminActionMfaResponse();
+        return await api.fetch(url, customOptions, mfaResponse);
```
Comment (ryanclark) [inline web/packages/teleport/src/services/api/api.ts:151]: No need for the `await`s here

Comment (ravicious) [reply web/packages/teleport/src/services/api/api.ts:151]: Yeah, it's not a big deal, but if you have a promise, you can return it from an async function without awaiting.

I'm not sure if there's a lint rule which would automatically take care of this. await-thenable and no-misused-promises seem to be about different cases entirely. https://github.com/typescript-eslint/typescript-eslint/issues/8517

File: web/packages/teleport/src/services/api/api.ts
Comment (Joerger) [reply web/packages/teleport/src/services/api/api.ts:1]: You have to make an SSO user, which wouldn't have an MFA device until you add one

File: web/packages/teleport/src/services/api/api.ts (hunk 3 above)
Comment (Joerger) [reply web/packages/teleport/src/services/api/api.ts:151]: I see, I wasn't sure how the try/catch would work without the first await

Comment (ryanclark) [reply web/packages/teleport/src/services/api/api.ts]: Sorry @Joerger, you're absolutely correct

image

Comment (Joerger) [reply web/packages/teleport/src/services/api/api.ts]: No problem, reverted that one.

**Review by ryanclark — APPROVED** [review]
