### PR TITLE
mfa: prevent the user from deleting the last MFA device

### LINKED ISSUE #5803: mfa: user can delete the last MFA device when "second_factor: on"
### Description

**What happened**:

`auth_service` has `second_factor: on` set.
User can remove the only registered MFA device with `tsh mfa rm`.

**What you expected to happen**:

Per https://github.com/gravitational/teleport/blob/master/rfd/0015-2fa-management.md, user should not be able to remove the last device when MFA is required.
Without a device, user will get locked out once their session expires.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Set `second_factor: on` on the `auth_service`
2. Create a user with 1 MFA device
3. Run `tsh mfa rm $DEVICE_NAME`

### Details
- Teleport version (run `teleport version`): v6.0.0-rc.1

### PR DESCRIPTION
**Pull request by awly**
When the cluster requires MFA for all users (when `second_factor` is
`on`, `u2f` or `totp`, and not `off` or `optional`), users could lock
themselves out by deleting the last device. Prevent that.

Fixes https://github.com/gravitational/teleport/issues/5803

### CODE REVIEW

**Review by r0mant — APPROVED** [review]

File: lib/auth/grpcserver.go [hunk 1]
```diff
@@ -1723,13 +1723,26 @@ func (g *GRPCServer) DeleteMFADevice(stream proto.AuthService_DeleteMFADeviceSer
...
 	for _, d := range devs {
 		// Match device by name or ID.
 		if d.Metadata.Name != initReq.DeviceName && d.Id != initReq.DeviceName {
 			continue
 		}
+
+		// Make sure that the user won't be locked out by deleting the last MFA
+		// device. This only applies when the cluster requires MFA.
+		if authPref.GetSecondFactor() != constants.SecondFactorOff &&
+			authPref.GetSecondFactor() != constants.SecondFactorOptional &&
```
Comment (andrejtokarcik) [inline lib/auth/grpcserver.go:1741]: Would removing a last MFA device cause lock-out with `SecondFactorOTP`?

It might be clearer to introduce a helper function which evaluates whether an MFA device must be/remain registered.

Comment (andrejtokarcik) [reply lib/auth/grpcserver.go:1741]: Please ignore, I now see OTP devices are also registered as a type of MFA.

**Review by andrejtokarcik — APPROVED** [review]

File: lib/auth/grpcserver.go (hunk 1 above)
Comment (andrejtokarcik) [reply lib/auth/grpcserver.go:1741]: However, the check should probably be stricter though:
* `SecondFactorOTP` => return error when the last **OTP** device is attempted to be removed;
* `SecondFactorU2F` => return error when the last **U2F** device is attempted to be removed.

File: lib/auth/grpcserver.go [hunk 2]
```diff
@@ -1723,13 +1723,49 @@ func (g *GRPCServer) DeleteMFADevice(stream proto.AuthService_DeleteMFADeviceSer
...
 		}
+
+		// Make sure that the user won't be locked out by deleting the last MFA
+		// device. This only applies when the cluster requires MFA.
+		switch authPref.GetSecondFactor() {
+		case constants.SecondFactorOff, constants.SecondFactorOptional: // MFA is not required, allow deletion
+		case constants.SecondFactorOTP:
+			if numTOTPDevs == 1 {
+				return trail.ToGRPC(trace.BadParameter("cannot delete the last OTP device for this user; add a replacement device first to avoid getting locked out"))
+			}
```
Comment (andrejtokarcik) [inline lib/auth/grpcserver.go:1756]: Does `SecondFactorOTP` mean there can be no MFA devices stored for the user? If a user had a single OTP device but he intended to delete some of the (now unusable) MFA devices, wouldn't this error be incorrectly returned since the type of the device to be deleted doesn't seem to be taken into account?

Analogically for `SecondFactorMFA` when deleting an OTP device.

Comment (awly) [reply lib/auth/grpcserver.go:1756]: This block only returns an error if cluster requires `SecondFactorOTP` and there is exactly 1 OTP device registered (regardless of how many U2F devices there are).
Same thing for `SecondFactorU2F`, the error only happens when there's 1 U2F device, regardless of any OTP devices.

Maybe I misunderstand the question?

Comment (andrejtokarcik) [reply lib/auth/grpcserver.go:1756]: Yes, I understand that.

My worry is that this error would be returned even if a user requested to delete an MFA device and not the last OTP device. In other words, the type of the device to be deleted should be checked and there should be no error when deleting an MFA device even if there is only a single OTP device left.

Comment (awly) [reply lib/auth/grpcserver.go:1756]: OTP is a sub-type of MFA, not a separate group.
Each user has multiple MFA devices. Each of those devices is either U2F or OTP.
In the loop above I calculate the number of devices of each type (`numTOTPDevs` and `numU2FDevs`).
Does that clarify the logic?
