### PR TITLE
Specify the `NodeName` in `auth.ReRegister`

### LINKED ISSUE #12212: SSH connectivity is broken after CA rotation due to change in principals on host certificates
### Description

**What happened**: When performing a CA rotation, the list of principals on the host certificate changes.

There is an additional principal on the certificate before rotation (`<hostname>.<cluster-name>`) which is not present after rotation.

This change breaks connectivity over SSH when using `tsh config`, as well as affecting the use of things like `HostKeyAlias` in an SSH client configuration.

I'm not sure if this is technically a regression as I don't have a comparison with an older version of Teleport, but this broke my existing home lab setup and required intervention to fix so I'm adding the label. I think this is a fairly serious bug. It's certainly going to affect anyone else who rotates their CA and uses `ssh` (especially with Machine ID) to connect to their cluster.

### Before rotation

`tctl status`:
```
vagrant@teleport:~$ sudo tctl status
Cluster  teleport.vagrant
Version  9.1.0
Host CA  never updated
User CA  never updated
Jwt CA   never updated
CA pin   sha256:baf0e18812c9ca0d0b5ec1b3467a8826536e25ee5a92ac2479e0f7017ed78f0b
```

`tsh ls`:
```
~ » tsh ls
Node Name         Address        Labels
----------------- -------------- ---------------------
teleport          127.0.0.1:3022 env=vagrant
teleport-one-node ⟵ Tunnel       env=vagrant,role=node
```

`tsh config`:
```
#
# Begin generated Teleport configuration for teleport.vagrant:443 from `tsh config`
#

# Common flags for all teleport.vagrant hosts
Host *.teleport.vagrant teleport.vagrant
    UserKnownHostsFile "/Users/gus/.tsh/known_hosts"
    IdentityFile "/Users/gus/.tsh/keys/teleport.vagrant/gus"
    CertificateFile "/Users/gus/.tsh/keys/teleport.vagrant/gus-ssh/teleport.vagrant-cert.pub"

# Flags for all teleport.vagrant hosts except the proxy
Host *.teleport.vagrant !teleport.vagrant
    Port 3022
    ProxyCommand "/usr/local/bin/tsh" proxy ssh --cluster=teleport.vagrant --proxy=teleport.vagrant %r@%h:%p

# End generated Teleport configuration
```

Host certificate principals on auth/proxy (`teleport`):
```
debug1: Server host certificate: ssh-rsa-cert-v01@openssh.com SHA256:YZRNV4+z6AGJlwrFKwYrxd/CCY79+vQsHDnS6YSrZOo, serial 0 ID "" CA ssh-rsa SHA256:buPCC22GhYv1EcAvXZw2zb+6YpiCNZUqaCIQvEgK3C8 valid after 2022-04-25T11:30:57
debug2: Server host certificate hostname: 6249157c-32cf-41cc-9754-7ef65c757bd4.teleport.vagrant
debug2: Server host certificate hostname: 6249157c-32cf-41cc-9754-7ef65c757bd4
debug2: Server host certificate hostname: teleport.teleport.vagrant
debug2: Server host certificate hostname: teleport
debug2: Server host certificate hostname: localhost
debug2: Server host certificate hostname: 127.0.0.1
debug2: Server host certificate hostname: ::1
```

Host certificate principals on agent (`teleport-one-node`):
```
debug1: Server host certificate: ssh-rsa-cert-v01@openssh.com SHA256:9YU5ZVGdFUM2fu3o5mxX4zVjQ0SG+vu/exhQKzsfnG0, serial 0 ID "" CA ssh-rsa SHA256:buPCC22GhYv1EcAvXZw2zb+6YpiCNZUqaCIQvEgK3C8 valid after 2022-04-25T13:36:44
debug2: Server host certificate hostname: 264115cc-cd5f-43a4-90b7-910d29807f3c.teleport.vagrant
debug2: Server host certificate hostname: 264115cc-cd5f-43a4-90b7-910d29807f3c
debug2: Server host certificate hostname: teleport-one-node.teleport.vagrant
debug2: Server host certificate hostname: teleport-one-node
debug2: Server host certificate hostname: localhost
debug2: Server host certificate hostname: 127.0.0.1
debug2: Server host certificate hostname: ::1
```

Connectivity to both nodes with `ssh teleport.teleport.vagrant` and `ssh teleport-one-node.teleport.vagrant` works fine.

### After rotation

`tctl status`:
```
vagrant@teleport:~$ sudo tctl status
Cluster  teleport.vagrant
Version  9.1.0
Host CA  rotated Apr 25 17:47:23 UTC
User CA  rotated Apr 25 17:47:23 UTC
Jwt CA   rotated Apr 25 17:47:23 UTC
CA pin   sha256:009bebb6a910d2030c95a48394421e897f7be7755e1a3b3601689562b37dd113
```

`tsh ls`:
```
~ » tsh ls
Node Name         Address        Labels
----------------- -------------- ---------------------
teleport          127.0.0.1:3022 env=vagrant
teleport-one-node ⟵ Tunnel       env=vagrant,role=node
```

`tsh config`:
```
#
# Begin generated Teleport configuration for teleport.vagrant:443 from `tsh config`
#

# Common flags for all teleport.vagrant hosts
Host *.teleport.vagrant teleport.vagrant
    UserKnownHostsFile "/Users/gus/.tsh/known_hosts"
    IdentityFile "/Users/gus/.tsh/keys/teleport.vagrant/gus"
    CertificateFile "/Users/gus/.tsh/keys/teleport.vagrant/gus-ssh/teleport.vagrant-cert.pub"

# Flags for all teleport.vagrant hosts except the proxy
Host *.teleport.vagrant !teleport.vagrant
    Port 3022
    ProxyCommand "/usr/local/bin/tsh" proxy ssh --cluster=teleport.vagrant --proxy=teleport.vagrant %r@%h:%p

# End generated Teleport configuration
```

Host certificate principals on auth/proxy (`teleport`):
```
debug1: Server host certificate: ssh-rsa-cert-v01@openssh.com SHA256:k5aWaTv9dAsLDit46WAJzqUqvLy6tFHUpTdgqdpzyYs, serial 0 ID "" CA ssh-rsa SHA256:F5uTEMDXCZ1T6XF7O/nDqZmAQHbaSdNhzShARjFqM1c valid after 2022-04-25T14:46:24
debug2: Server host certificate hostname: 6249157c-32cf-41cc-9754-7ef65c757bd4.teleport.vagrant
debug2: Server host certificate hostname: 6249157c-32cf-41cc-9754-7ef65c757bd4
debug2: Server host certificate hostname: localhost
debug2: Server host certificate hostname: 127.0.0.1
debug2: Server host certificate hostname: ::1
debug2: Server host certificate hostname: teleport
```

Host certificate principals on agent (`teleport-one-node`):
```
debug1: Server host certificate: ssh-rsa-cert-v01@openssh.com SHA256:HjBNL6zQJgo1TVo/p4teLtkuSpXkn46HEwu/iOCc6cE, serial 0 ID "" CA ssh-rsa SHA256:F5uTEMDXCZ1T6XF7O/nDqZmAQHbaSdNhzShARjFqM1c valid after 2022-04-25T14:46:24
debug2: Server host certificate hostname: 264115cc-cd5f-43a4-90b7-910d29807f3c.teleport.vagrant
debug2: Server host certificate hostname: 264115cc-cd5f-43a4-90b7-910d29807f3c
debug2: Server host certificate hostname: localhost
debug2: Server host certificate hostname: 127.0.0.1
debug2: Server host certificate hostname: ::1
debug2: Server host certificate hostname: teleport-one-node
```

Connectivity with `ssh` is broken:
```
~ » ssh -F ~/.ssh/vagrant_config root@teleport-one-node.teleport.vagrant
Certificate invalid: name is not a listed principal
The authenticity of host '[teleport-one-node.teleport.vagrant]:3022 (<no hostip for proxy command>)' can't be established.
RSA key fingerprint is SHA256:HjBNL6zQJgo1TVo/p4teLtkuSpXkn46HEwu/iOCc6cE.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? ^C
ERROR: exit status 255

~ » ssh -F ~/.ssh/vagrant_config root@teleport.teleport.vagrant
Certificate invalid: name is not a listed principal
The authenticity of host '[teleport.teleport.vagrant]:3022 (<no hostip for proxy command>)' can't be established.
RSA key fingerprint is SHA256:k5aWaTv9dAsLDit46WAJzqUqvLy6tFHUpTdgqdpzyYs.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? ^C
ERROR: exit status 255
```

**What you expected to happen**: The list of principals on host certificates should be the same before and after rotation to prevent breaking connectivity to client environments.

### Reproduction Steps
Perform a CA rotation, observe changes in the principals on the certificate.

### Server Details
- Teleport version (run `teleport version`): `Teleport v9.1.0 git:v9.1.0-0-g4d9708f85 go1.17.9`

### PR DESCRIPTION
**Pull request by espadolini**
We currently specify the `NodeName` parameter when calling `auth.Register` as part of `(*TeleportProcess).firstTimeConnect`, but not when we call `auth.ReRegister` in `(*TeleportProcess).reRegister`. This PR makes it so that we correctly specify the local process hostname as the `NodeName` in the latter case as well.

Fixes #12212.

### CODE REVIEW

**Review by ravicious — APPROVED** [review]

File: integration/integration_test.go [hunk 1]
```diff
@@ -3852,6 +3869,21 @@ func testRotateRollback(t *testing.T, s *integrationTestSuite) {
 
 	svc, err := waitForProcessStart(serviceC)
 	require.NoError(t, err)
+	defer svc.Shutdown(context.TODO())
```
Comment (zmb3) [inline integration/integration_test.go:3872]: nit: I would prefer `context.Background()` unless you actually intend to go back and update this to plumb a context through.

**Review by zmb3 — APPROVED** [review]

File: integration/integration_test.go (hunk 1 above)
Comment (espadolini) [reply integration/integration_test.go]: Actually removed those `Shutdown` calls from `testRotateSuccess` instead.
