### PR TITLE
Fetch advertised proxy addresses when using an identity file

### LINKED ISSUE #3513: tsh ssh --identity does not use `ping` information
### Description

**What happened**:

`example.dev` and `1.2.3.4` used as an example here

```
➜  .tsh tsh ls --proxy ssh.example.dev:443 --login svc  --identity "../.ssh/svc.pem" -d
INFO             Reading identity file: ../.ssh/svc.pem common/identity.go:44
DEBU [TSH]       Extracted username "svc" from the identity file ../.ssh/svc.pem. tsh/tsh.go:945
INFO [CLIENT]    Connecting proxy=ssh.example.dev:3023 login='svc' method=0 client/api.go:1588
ERROR REPORT:
Original Error: *net.OpError dial tcp 1.2.3.4:3023: connect: operation timed out
Stack Trace:
Collapse
```

The proxy is correctly configured to provide the following ping information:

```
curl -k https://ssh.example.dev:443/webapi/ping
{"auth":{"type":"saml","second_factor":"off","saml":{"name":"OktaSAML","display":"SSO"}},"proxy":{"kube":{},"ssh":{"listen_addr":"0.0.0.0:3023","tunnel_listen_addr":"0.0.0.0:3024","public_addr":"ssh.example.dev:443","ssh_public_addr":"lb.example.dev:3023","ssh_tunnel_public_addr":"lb.example.dev:3024"}},"server_version":"4.2.6","min_client_version":"3.0.0"}
```

It seems that `tsh -i` does not use the `ssh_public_addr` information provided by ping, only `tsh ssh` uses it correctly.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): 4.2.6
- Tsh version (use `tsh version`): 4.2.6
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by awly**
Proxy advertises its preferred web/ssh/kube addresses via the `Ping`
endpoint. `tsh` hits this endpoint on login and caches addresses on disk
(in profile, along with credentials).
For all subsequent commands, `tsh` loads the cached information from
disk.

When using an identity file, `tsh` skips loading the profile (and it can
be missing entirely). In this case, we need to `Ping` the proxy
explicitly to fetch the correct public addresses for a proxy.

Fixes #3513

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -756,6 +757,10 @@ type TeleportClient struct {
 	// eventsCh is a channel used to inform clients about events have that
 	// occurred during the session.
 	eventsCh chan events.EventFields
+
+	// Note: there's no mutex guarding this, making TeleportClient NOT safe for
+	// concurrent use.
+	lastPing *PingResponse
```
Comment (russjones) [inline lib/client/api.go:763]: Why not add a mutex?

Comment (awly) [reply lib/client/api.go:763]: `TeleportClient` already not thread-safe due to `localAgent` field.
We'd need to go through all methods and add locking to make any promises about thread-safety, adding a bit of performance penalty too.
I assume nothing uses the client concurrently now (race detector in tests should catch it), so there's no need?

**Review by russjones — APPROVED** [review]
