### PR TITLE
Fixes a SharedDirectoryAnnounce incompatibility

### LINKED ISSUE #25939: Directory sharing broken for Teleport v12.2.5, v12.3.0 - v12.3.3, and v13.0.0 (`windows_desktop_service`)
The `windows_desktop_service` for both of Teleport v13.0.0, Teleport v12.3.0-v12.3.3 has a broken directory sharing implementation. Users should avoid running w_d_s with these versions if directory sharing is required.

Bug details:
- Teleport version
**v12.2.5**, **v12.3.0**, **v12.3.1**, **v12.3.2**, **v12.3.3**, **v13.0.0**
- Recreation steps
**Share a directory**
- Debug logs
```
May 09 15:02:42 ip-172-31-30-140 teleport[1051638]: 2023-05-09T15:02:42Z [WINDOWS_D] WARN Failed reading TDP input message: unsupported desktop protocol message type 0 client-ip:172.31.30.140 desktop-addr:172.31.6.213:3389 desktop-name:EC2AMAZ-VQ8P4SU-teleportad-local pid:1051638.1 rdp-addr:172.31.6.213:3389 rdpclient/client.go:337
May 09 15:02:42 ip-172-31-30-140 teleport[1051638]: 2023-05-09T15:02:42Z [WINDOWS_D] INFO TDP input streaming finished client-ip:172.31.30.140 desktop-addr:172.31.6.213:3389 desktop-name:EC2AMAZ-VQ8P4SU-teleportad-local pid:1051638.1 rdp-addr:172.31.6.213:3389 rdpclient/client.go:338
May 09 15:02:42 ip-172-31-30-140 teleport[1051638]: 2023-05-09T15:02:42Z [WINDOWS_D] DEBU RDP connection closed successfully client-ip:172.31.30.140 desktop-addr:172.31.6.213:3389 desktop-name:EC2AMAZ-VQ8P4SU-teleportad-local pid:1051638.1 rdp-addr:172.31.6.213:3389 rdpclient/client.go:837
May 09 15:02:42 ip-172-31-30-140 teleport[1051638]: 2023-05-09T15:02:42Z [WINDOWS_D] DEBU TDP connection closed successfully client-ip:172.31.30.140 desktop-addr:172.31.6.213:3389 desktop-name:EC2AMAZ-VQ8P4SU-teleportad-local pid:1051638.1 rdp-addr:172.31.6.213:3389 rdpclient/client.go:844
```

### PR DESCRIPTION
**Pull request by ibeckermayer**
The SharedDirectoryAnnounce message was changed to remove an unnecessary completionID field, however this change caused an incompatibility between the proxy and previous versions of the wds. This commit reverts that specific change and adds notes to the code explaining the situation.

The original change is here: https://github.com/gravitational/teleport/pull/25260/files#diff-98a4bee57beb7f007614e4810d2cf8413bddf48484c8aad6dd0756a218797c36R677-R678

closes https://github.com/gravitational/teleport/issues/25939

### CODE REVIEW

File: lib/srv/desktop/tdp/proto.go [hunk 1]
```diff
@@ -675,8 +675,16 @@ func (s SharedDirectoryAnnounce) Encode() ([]byte, error) {
 }
 
 func decodeSharedDirectoryAnnounce(in io.Reader) (SharedDirectoryAnnounce, error) {
+	// TODO(isaiah): The completionID here is a copy-paste error, but we need to keep it
+	// for now in order that the proxy stay compatible with previous versions of the wds.
+	var completionID uint32
```
Comment (zmb3) [inline lib/srv/desktop/tdp/proto.go:680]:
```suggestion
	var discard uint32
```

Let's make it clear that this is not actually a completion ID. (here and below)

**Review by zmb3 — APPROVED** [review]

**Review by ravicious — APPROVED** [review]

**Comment by zmb3** [comment]
Interesting that v12 backport failed, I wonder what's different about v12.
