### PR TITLE
Fix an issue docker container launched by MCP commands are not removed sometimes

### LINKED ISSUE #59768: Docker mcp server not exited after claude desktop closes
Expected behavior:
MCP server launched by docker command should exit properly when Claude Desktop closes.

Current behavior:
```
2025-09-30T13:06:52.399-04:00 WARN [APP:SERVI] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *exec.ExitError exit status 1
Stack Trace:
	github.com/gravitational/teleport/lib/srv/mcp/stdio.go:189 github.com/gravitational/teleport/lib/srv/mcp.(*execServer).run
```

```
$ docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS                  PORTS                                         NAMES
16dc03b1dd35   mcp/everything           "docker-entrypoint.s…"   43 seconds ago   Up 42 seconds                                                         wonderful_curran
```

Bug details:
- Teleport version: v18
- Recreation steps:
```
kind: app
metadata:
  description: Everything MCP server
  labels:
    env: dev
    teleport.dev/origin: dynamic
    teleport.internal/app-sub-kind: mcp
  name: everything
  revision: abde182b-687e-4241-8632-7d3729a945e4
spec:
  insecure_skip_verify: false
  mcp:
    args:
    - run
    - -i
    - --rm
    - mcp/everything
    command: docker
    run_as_host_user: stevehuang
  uri: mcp+stdio://
sub_kind: mcp
version: v3
```

### PR DESCRIPTION
**Pull request by greedy52**
fixes #59768
- #59768

changelog: Fixed an issue where Docker containers launched by MCP commands are sometimes not removed

see original ticket for more details of the claude desktop issue.

### CODE REVIEW

**Review by avatus — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]

File: lib/srv/mcp/stdio.go [hunk 1]
```diff
@@ -214,21 +214,31 @@ func makeExecServerRunner(ctx context.Context, session *sessionHandler) (stdioSe
...
 	// the server handler, we make sure 'cmdCancel' is called to cancel the
 	// command in that case.
-	cmd.Cancel = sync.OnceValue(func() error {
+	//
+	// There is also a race where cmd.Cancel may be called before cmd.Process is
+	// available. To make sure the signal is sent, do not use sync.Once on the
+	// entire "cmd.Cancel". Instead, use sync.Once after cmd.Process non-nil
+	// check so we have a better chance to clean up.
+	signalOnce := sync.OnceValue(func() error {
+		// Use SIGINT for graceful shutdown since stdio servers are
```
Comment (Tener) [inline lib/srv/mcp/stdio.go:228]: CommandContext is implemented like this:

```go
func CommandContext(ctx context.Context, name string, arg ...string) *Cmd {
	if ctx == nil {
		panic("nil Context")
	}
	cmd := Command(name, arg...)
	cmd.ctx = ctx
	cmd.Cancel = func() error {
		return cmd.Process.Kill()
	}
	return cmd
}
```

I see why we might want to do graceful shutdown with SIGINT, but I think we should send SIGKILL if the process is still running after a few seconds.

Comment (greedy52) [reply lib/srv/mcp/stdio.go:228]: it's handled by https://github.com/gravitational/teleport/blob/e54e9c2d8040c9ae51b0b22193edf4ace67dc7ba/lib/srv/mcp/stdio.go#L215-L217

and tested by `wait for SIGKILL` test case.

**Review by Tener — APPROVED** [review]
