### PR TITLE
Fix discrepancies between Node and Proxy recording modes.

### LINKED ISSUE #4146: Incorrect Event Data, Proxy Recording Mode
### Description

**What happened**:
With Proxy Recording mode enabled, the audit log displays incorrect session event data for IoT nodes. The following values are incorrect:

- server_hostname
- server_id
- server_labels

When proxy recording mode is enabled, these values seem to be populated with the proxy server's details, rather than the node's details.

**What you expected to happen**:
Regardless of recording mode, the event details should reflect accurately which node was accessed. 

**How to reproduce it (as minimally and precisely as possible)**:
1. With a Teleport Cluster and IoT mode node, ensure `session_recording` is set to "node". 
2. Create a session with the IoT mode node. End the session.
3. Update your Teleport Cluster `session_recording` to "proxy". 
4. Create a session with the IoT mode node. End the session.
5. Compare the two session.start events. 

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.3.2git:v4.3.2-0-gc6d702ad8 go1.13.2
- Tsh version (use `tsh version`): N/A, used web console for testing
- OS (e.g. from `/etc/os-release`): Ubuntu 16.0.4

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

Nroxy recording mode enabled:
```json
{
  "addr.remote": "xx.xx.xx.xx:40542",
  "code": "T2000I",
  "ei": 0,
  "event": "session.start",
  "login": "root",
  "namespace": "default",
  "server_hostname": "raspberrypi",
  "server_id": "eb1221ba-a82f-4fa9-9258-9cbb20a45b81",
  "server_labels": {
    "arch": "Linux",
    "role": "fileserver",
    "type": "raspberrypi"
  },
  "sid": "0682d59a-d1d0-11ea-b0f0-42010a800002",
  "size": "80:25",
  "time": "2020-07-29T19:16:40.337Z",
  "uid": "5383f670-2f17-449c-baf0-67ca6849fd77",
  "user": "<me>"
}
```
Proxy recording mode enabled:
```json
{
  "addr.remote": "xx.xx.xx.xx:40616",
  "code": "T2000I",
  "ei": 0,
  "event": "session.start",
  "login": "root",
  "namespace": "default",
  "server_hostname": "",  # Missing hostname
  "server_id": "5f86b005-3e8e-4bc3-88e4-3d383c225a73",  # Proxy UUID
  "server_labels": {},  # Missing server labels
  "sid": "fa4c8647-0a46-4efb-88ff-9bb9ad566c39",
  "size": "80:25",
  "time": "2020-07-29T19:18:45.142Z",
  "uid": "9dcdb3c5-1224-4684-9423-0f656772942b",
  "user": "<me>"
}
```
On Proxy:
```sh
$ cat /var/lib/teleport/host_uuid
5f86b005-3e8e-4bc3-88e4-3d383c225a73
```
On Node:
```sh
$ cat /var/lib/teleport/host_uuid
eb1221ba-a82f-4fa9-9258-9cbb20a45b81
```

### PR DESCRIPTION
**Pull request by Joerger**
Changes:
- Remove the unique ID from the ephemeral forwarding server, which provided no benefit. Instead, the ID of the server will be the Node ID. Combined with the `forwarded_by: <proxy_id>` field in events, it will be clear that the actual component being connected to is the ephemeral forwarding server for that node session.
- Rename the forwarding server field `hostUUID` to `proxyUUID` for clarity. `HostUUID()` still returns the same proxy uuid.
- Update the forwarding server `GetInfo` method to return the full end server info, including labels, subkind, etc.
  - Build event metadata from the server info from `GetInfo`. This eliminates some of the discrepancies I found between the events and the actual server info, and between the forwarding vs. node recording events.

Adapted from https://github.com/gravitational/teleport/pull/52920

Depends on https://github.com/gravitational/teleport/pull/58700

Closes https://github.com/gravitational/teleport/issues/4146

Diff between Node recordings before and after this PR:
```diff
{
  "addr.remote": "127.0.0.1:52234",
  "cluster_name": "root.example.com",
  "code": "T2000I",
  "ei": 0,
  "event": "session.start",
  "initial_command": [
    ""
  ],
  "login": "bjoerger",
  "namespace": "default",
  "private_key_policy": "none",
  "proto": "ssh",
  "server_hostname": "node",
  "server_id": "978e143e-6271-4ff0-8344-3d71528615b1",
  "server_labels": {
    "arch": "arm",
    "cluster": "root.example.com",
    "env": "production",
    "hostname": "Brians-MacBook-Pro-2.local"
  },
+ "server_sub_kind": "teleport",
  "server_version": "19.0.0-dev",
  "session_recording": "node",
  "sid": "7f3da66e-eab4-437f-bc96-65cf40363d18",
  "size": "167:23",
  "time": "2025-09-03T21:29:50.374Z",
  "uid": "0ae3ecae-1f57-4436-8493-60a24870a932",
  "user": "dev",
  "user_kind": 1
}
```

Diff between Proxy recordings before and after this PR:
```diff
{
  "addr.remote": "127.0.0.1:52863",
  "cluster_name": "root.example.com",
  "code": "T2000I",
  "ei": 0,
  "event": "session.start",
  "forwarded_by": "7dae42bb-6401-405f-b683-efa44d57e484",
  "initial_command": [
    ""
  ],
  "login": "bjoerger",
  "namespace": "default",
  "private_key_policy": "none",
  "proto": "ssh",
- "server_addr": "@local-node",
  "server_hostname": "node",
- "server_id": "7f4ce963-f184-4fe7-a0fe-13f35a7d9e42.root.example.com",
+ "server_id": "7f4ce963-f184-4fe7-a0fe-13f35a7d9e42",
+ "server_labels": {
+   "arch": "arm",
+   "cluster": "root.example.com",
+   "env": "production",
+   "hostname": "Brians-MacBook-Pro-2.local"
+ },
  "server_sub_kind": "teleport",
  "server_version": "19.0.0-dev",
  "session_recording": "proxy",
  "sid": "00e55c91-7bd3-48e7-96c4-30e17d78da2f",
  "size": "167:23",
  "time": "2025-09-03T21:47:12.505Z",
  "uid": "995f48d4-684c-4d72-bfa8-cd52ac00bab4",
  "user": "dev",
  "user_kind": 1
}
```

Diff between Node and Proxy recordings after this PR:
```diff
{
  "addr.remote": "127.0.0.1:52562",
  "cluster_name": "root.example.com",
  "code": "T2000I",
  "ei": 0,
  "event": "session.start",
+ "forwarded_by": "1d3f9f84-3f63-4267-be51-0fae1e2fe4b0",
  "initial_command": [
    ""
  ],
  "login": "bjoerger",
  "namespace": "default",
  "private_key_policy": "none",
  "proto": "ssh",
  "server_hostname": "node",
  "server_id": "27a558dd-2d35-407c-bfcc-3333dca34b48",
  "server_labels": {
    "arch": "arm",
    "cluster": "root.example.com",
    "env": "production",
    "hostname": "Brians-MacBook-Pro-2.local"
  },
  "server_sub_kind": "teleport",
  "server_version": "19.0.0-dev",
- "session_recording": "node",
+ "session_recording": "proxy",
  "sid": "3a1c8d5b-9719-4df2-ac6a-12191062d8eb",
  "size": "167:23",
  "time": "2025-09-03T21:34:45.056Z",
  "uid": "9dd08c52-7f68-4a03-b827-bb3230e76c43",
  "user": "dev",
  "user_kind": 1
}
```

Diff between Node and Proxy recordings after this PR, connecting to node w/o tunnel mode:
```diff
{
- "addr.local": "127.0.0.1:3080",
+ "addr.local": "127.0.0.1:3022",
  "addr.remote": "127.0.0.1:53139",
  "cluster_name": "root.example.com",
  "code": "T2000I",
  "ei": 0,
  "event": "session.start",
+ "forwarded_by": "7dae42bb-6401-405f-b683-efa44d57e484",
  "initial_command": [
    ""
  ],
  "login": "bjoerger",
  "namespace": "default",
  "private_key_policy": "none",
  "proto": "ssh",
- "server_addr": "[::]:3022",
+ "server_addr": "127.0.0.1:3022",
  "server_hostname": "server01",
  "server_id": "7dae42bb-6401-405f-b683-efa44d57e484",
  "server_labels": {
    "arch": "arm",
    "cluster": "root.example.com",
    "env": "staging",
    "hostname": "Brians-MacBook-Pro-2.local",
    "idp_1": "access_teleport_template",
    "oidc-client-id": "dev"
  },
  "server_sub_kind": "teleport",
  "server_version": "19.0.0-dev",
- "session_recording": "node",
+ "session_recording": "proxy",
  "sid": "bd6a3988-8f28-40a8-a4fd-464382e11a42",
  "size": "167:33",
  "time": "2025-09-03T22:03:14.344Z",
  "uid": "6dfa4428-09d3-405f-827b-794efb5ec6e0",
  "user": "dev",
  "user_kind": 1
}
```

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -183,6 +183,8 @@ func TestIntegrations(t *testing.T) {
 	t.Run("PAM", suite.bind(testPAM))
 	t.Run("PortForwarding", suite.bind(testPortForwarding))
 	t.Run("ProxyHostKeyCheck", suite.bind(testProxyHostKeyCheck))
+	t.Run("RecordingModesSessionTrackers", suite.bind(testRecordingModesSessionTrackers))
+
```
Comment (rosstimothy) [inline integration/integration_test.go]:
```suggestion
```

File: integration/integration_test.go [hunk 2]
```diff
@@ -1038,6 +1040,82 @@ func testSessionRecordingModes(t *testing.T, suite *integrationTestSuite) {
...
+			// Validate that the session tracker exists and contains
+			// the correct target address.
+			var sessionID string
+			require.EventuallyWithT(t, func(t *assert.CollectT) {
+				trackers, err := auth.GetActiveSessionTrackers(ctx)
+				assert.NoError(t, err)
+				if !assert.Len(t, trackers, 1) {
+					return
+				}
+				assert.Equal(t, helpers.HostID, trackers[0].GetAddress())
```
Comment (rosstimothy) [inline integration/integration_test.go]: As of testify v1.10.0, require is now able to be used within a EventuallyWith assertion function. 
```suggestion
				require.NoError(t, err)
				require.Len(t, trackers, 1)
				require.Equal(t, helpers.HostID, trackers[0].GetAddress())
```

File: integration/integration_test.go [hunk 3]
```diff
@@ -1038,6 +1040,82 @@ func testSessionRecordingModes(t *testing.T, suite *integrationTestSuite) {
...
+
+			ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
+			defer cancel()
+			errCh <- cl.SSH(ctx, nil)
+		}()
+
+		return term, errCh
+	}
+
+	auth := teleport.Process.GetAuthServer()
```
Comment (rosstimothy) [inline integration/integration_test.go:1085]: Should we wait for the node to exist within the inventory before trying to connect to it? See https://github.com/gravitational/teleport/pull/58737 as an example.

File: lib/proxy/router.go [hunk 4]
```diff
@@ -247,59 +246,52 @@ func (r *Router) DialHost(ctx context.Context, clientSrcAddr, clientDstAddr net.
 	}
 	span.AddEvent("retrieved target server")
 
+	if target == nil {
+		return nil, trace.ConnectionProblem(errors.New("connection problem"), "direct dialing to nodes not found in inventory is not supported")
+	}
```
Comment (rosstimothy) [inline lib/proxy/router.go]: Same comment as on the base PR - should we move this within serverResolver and no longer return nil, nil?

File: lib/proxy/router.go [hunk 5]
```diff
@@ -247,59 +246,52 @@ func (r *Router) DialHost(ctx context.Context, clientSrcAddr, clientDstAddr net.
...
+	serverID := target.GetName() + "." + clusterName
+	proxyIDs := target.GetProxyIDs()
+
 	principals := []string{
 		host,
-		// Add in principal for when nodes are on leaf clusters.
+		// Required when nodes are in leaf clusters.
 		host + "." + clusterName,
+		// add hostUUID.cluster to the principals
+		serverID,
```
Comment (rosstimothy) [inline lib/proxy/router.go]: Won't there be some cases where serverID is equal to `host + "." + clusterName` from two lines above?

Comment (Joerger) [reply lib/proxy/router.go]: Fixed in the parent PR - 2ec85b89970ba0636ecf005560a31f9621904432

File: lib/srv/ctx.go [hunk 6]
```diff
@@ -155,6 +155,7 @@ type Server interface {
 	GetClock() clockwork.Clock
 
 	// GetInfo returns a services.Server that represents this server.
+	// In the case of the Proxy forwarder, this will is the node target.
```
Comment (zmb3) [inline lib/srv/ctx.go]:
```suggestion
	// In the case of the Proxy forwarder, this is the node target.
```

File: lib/srv/forward/sshserver.go [hunk 7]
```diff
@@ -409,16 +396,18 @@ func New(c ServerConfig) (*Server, error) {
...
-		ServerHostname:  s.targetHostname,
-		ForwardedBy:     s.hostUUID,
-		ServerSubKind:   s.targetServer.GetSubKind(),
+		ServerNamespace: serverInfo.GetNamespace(),
+		ServerID:        serverInfo.GetName(),
+		ServerAddr:      serverInfo.GetAddr(),
+		ServerLabels:    serverInfo.GetAllLabels(),
+		ServerHostname:  serverInfo.GetHostname(),
+		ServerSubKind:   serverInfo.GetSubKind(),
+		ForwardedBy:     s.proxyUUID,
```
Comment (zmb3) [inline lib/srv/forward/sshserver.go:410]: What do you think about calling it ForwardedByProxy?

Comment (Joerger) [reply lib/srv/forward/sshserver.go:410]: That would be better, but the field already exists in `events.proto`. Do you think it's worth changing?

File: integration/integration_test.go [hunk 8]
```diff
@@ -1038,6 +1039,83 @@ func testSessionRecordingModes(t *testing.T, suite *integrationTestSuite) {
 	}
 }
 
+func testRecordingModesSessionTrackers(t *testing.T, suite *integrationTestSuite) {
+	ctx := context.Background()
```
Comment (rosstimothy) [inline integration/integration_test.go]:
```suggestion
	ctx := t.Context()
```

**Review by rosstimothy — APPROVED** [review]

**Comment by Joerger** [comment]
@doggydogworld Friendly ping to review

**Comment by Joerger** [comment]
Reopened... this got automatically closed due to a faulty rebase (git machete) that reset the branch to master.

**Comment by Joerger** [comment]
@doggydogworld @zmb3 Friendly ping to review

**Review by zmb3 — APPROVED** [review]
