### PR TITLE
Fix GCP metadata errors crashing Teleport

### LINKED ISSUE #42312: CrashLoopBackOff in Teleport clusteron GCP with v15.3.7
After upgrading Teleport on GCP from `15.3.5` to `15.3.7`, the `teleport-proxy` pod dies with CrashLoopBackOff. The logs show the following error:

```
Defaulted container "teleport" out of: teleport, wait-auth-update (init)
{"caller":"automaticupgrades/channel.go:65","component":null,"level":"debug","message":"'default' automatic update channel not specified, teleport will serve its version by default.","timestamp":"2024-05-30T09:03:23Z"}
{"timestamp":"2024-05-30T09:03:23Z","level":"info","caller":"common/teleport.go:661","message":"Starting Teleport with a config file","version":"15.3.7","config_file":"/etc/teleport/teleport.yaml"}
{"caller":"lite/lite.go:259","component":"sqlite","level":"debug","message":"Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000\u0026_sync=FULL\u0026_txlock=immediate, poll stream period: 1s","timestamp":"2024-05-30T09:03:23Z"}
{"caller":"lite/lite.go:310","component":"sqlite","level":"debug","message":"journal_mode=delete, synchronous=2, busy_timeout=10000","timestamp":"2024-05-30T09:03:23Z"}
SDK 2024/05/30 09:03:23 WARN falling back to IMDSv1: operation error ec2imds: getToken, http response error StatusCode: 404, request to EC2 IMDS failed

ERROR REPORT:
Original Error: *url.Error Get &#34;https://compute.googleapis.com/compute/v1/projects/my-project/zones/us-east4-a/instances/gke-cluster-primary-7706f694-cdg9&#34;: compute: Received 403 `Unable to generate access token; IAM returned 403 Forbidden: Permission &#39;iam.serviceAccounts.getAccessToken&#39; denied on resource (or it may not exist).
This error could be caused by a missing IAM policy binding on the target IAM service account.
For more information, refer to the Workload Identity documentation:
	https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to

`
Stack Trace:
	github.com/gravitational/teleport/lib/cloud/gcp/vm.go:332 github.com/gravitational/teleport/lib/cloud/gcp.(*instancesClient).GetInstance
	github.com/gravitational/teleport/lib/cloud/imds/gcp/imds.go:117 github.com/gravitational/teleport/lib/cloud/imds/gcp.(*InstanceMetadataClient).GetTags
	github.com/gravitational/teleport/lib/cloud/imds/gcp/imds.go:152 github.com/gravitational/teleport/lib/cloud/imds/gcp.(*InstanceMetadataClient).GetHostname
	github.com/gravitational/teleport/lib/service/service.go:940 github.com/gravitational/teleport/lib/service.NewTeleport
	github.com/gravitational/teleport/lib/service/service.go:703 github.com/gravitational/teleport/lib/service.newTeleportProcess
	github.com/gravitational/teleport/lib/service/service.go:719 github.com/gravitational/teleport/lib/service.Run
	github.com/gravitational/teleport/tool/teleport/common/teleport.go:663 github.com/gravitational/teleport/tool/teleport/common.OnStart
	github.com/gravitational/teleport/tool/teleport/common/teleport.go:560 github.com/gravitational/teleport/tool/teleport/common.Run
	github.com/gravitational/teleport/tool/teleport/main.go:33 main.main
	runtime/proc.go:267 runtime.main
	runtime/asm_amd64.s:1650 runtime.goexit
User Message: initialization failed
	Get &#34;https://compute.googleapis.com/compute/v1/projects/my-project/zones/us-east4-a/instances/gke-cluster-primary-7706f694-cdg9&#34;: compute: Received 403 `Unable to generate access token; IAM returned 403 Forbidden: Permission &#39;iam.serviceAccounts.getAccessToken&#39; denied on resource (or it may not exist).
This error could be caused by a missing IAM policy binding on the target IAM service account.
For more information, refer to the Workload Identity documentation:
	https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to
```

### PR DESCRIPTION
**Pull request by atburke**
This change:

- Fixes Teleport starting up on isolated cloud nodes.
- Changes imds errors to logs in lib/service, so an unexpected imds error doesn't prevent Teleport from starting.

Fixes #42312.

Changelog: Fixed crashes related to importing GCP labels

### CODE REVIEW

File: lib/cloud/imds/gcp/imds.go [hunk 1]
```diff
@@ -76,8 +76,20 @@ func NewInstanceMetadataClient(ctx context.Context) (*InstanceMetadataClient, er
...
+}
+
+func (client *InstanceMetadataClient) getNumericID(ctx context.Context) (uint64, error) {
+	idStr, err := client.GetID(ctx)
+	if err != nil {
+		return 0, trace.Wrap(err)
+	}
+	id, err := strconv.ParseUint(idStr, 10, 64)
+	if err != nil {
+		return 0, trace.Wrap(err)
```
Comment (zmb3) [inline lib/cloud/imds/gcp/imds.go:90]: Let's return a better error here. Maybe something like this?

```suggestion
		return 0, trace.BadParameter("Invalid instance ID %q", idStr)
```

Otherwise the logs will say something like: "Error looking for cloud instance metadata: parsing "asdf": invalid syntax"

**Review by zmb3 — APPROVED** [review]

File: lib/cloud/imds/gcp/imds.go [hunk 2]
```diff
@@ -96,11 +107,7 @@ func (client *InstanceMetadataClient) GetTags(ctx context.Context) (map[string]s
 	if err != nil {
 		return nil, trace.Wrap(err)
 	}
-	idStr, err := client.GetID(ctx)
-	if err != nil {
-		return nil, trace.Wrap(err)
-	}
-	id, err := strconv.ParseUint(idStr, 10, 64)
+	id, err := client.getNumericID(ctx)
```
Comment (codingllama) [inline lib/cloud/imds/gcp/imds.go:110]: Should we check for `id != 0` here too, or is that not relevant here?

File: lib/cloud/imds/gcp/imds_test.go [hunk 3]
```diff
@@ -58,16 +58,44 @@ func (m *mockInstanceGetter) GetInstanceTags(ctx context.Context, req *gcp.Insta
...
+			},
+			assert: require.False,
+		},
+		{
+			name: "on mocked gcp",
+			getMetadata: func(ctx context.Context, path string) (string, error) {
+				return "12345678", nil
+			},
+			assert: require.True,
+		},
```
Comment (codingllama) [inline lib/cloud/imds/gcp/imds_test.go:86]: Test the zero ID?

File: lib/service/service.go [hunk 4]
```diff
@@ -967,8 +967,12 @@ func NewTeleport(cfg *servicecfg.Config) (*TeleportProcess, error) {
...
 	if imClient == nil {
 		imClient, err = cloud.DiscoverInstanceMetadata(supervisor.ExitContext())
-		if err != nil && !trace.IsNotFound(err) {
-			return nil, trace.Wrap(err)
+		if err == nil {
+			cfg.Logger.InfoContext(supervisor.ExitContext(),
+				"Found an instance metadata service. Teleport will import labels from this cloud instance.",
+				"type", imClient.GetType())
+		} else if !trace.IsNotFound(err) {
+			cfg.Logger.ErrorContext(supervisor.ExitContext(), "Error looking for cloud instance metadata.", "error", err)
```
Comment (codingllama) [inline lib/service/service.go:975]: Suggestion: make it clearer that not returning here is on purpose?

nit: Drop punctuation. https://github.com/gravitational/teleport/blob/master/rfd/0154-logging-guidelines.md#logging-standards - "The message should be a fragment, and not a full sentence. Terminating the message with punctuation should be avoided."

```suggestion
			cfg.Logger.ErrorContext(supervisor.ExitContext(), "Error looking for cloud instance metadata", "error", err)
			// Keep going.
```

Comment (codingllama) [inline lib/service/service.go:975]: As a question to the above, why is it OK to keep going in this case (and the ones below)?

Do we have test coverage for this?

File: lib/service/service.go [hunk 5]
```diff
@@ -985,15 +989,15 @@ func NewTeleport(cfg *servicecfg.Config) (*TeleportProcess, error) {
 				cfg.Logger.InfoContext(supervisor.ExitContext(), "Found invalid hostname in cloud tag TeleportHostname.", "hostname", cloudHostname)
 			}
 		} else if !trace.IsNotFound(err) {
-			return nil, trace.Wrap(err)
+			cfg.Logger.ErrorContext(supervisor.ExitContext(), "Error looking for hostname tag.", "error", err)
```
Comment (codingllama) [inline lib/service/service.go:992]:
```suggestion
			cfg.Logger.ErrorContext(supervisor.ExitContext(), "Error looking for hostname tag", "error", err)
			// Keep going.
```

File: lib/service/service.go [hunk 6]
```diff
@@ -985,15 +989,15 @@ func NewTeleport(cfg *servicecfg.Config) (*TeleportProcess, error) {
...
 		}
 
 		cloudLabels, err = labels.NewCloudImporter(supervisor.ExitContext(), &labels.CloudConfig{
 			Client: imClient,
 			Clock:  cfg.Clock,
 		})
 		if err != nil {
-			return nil, trace.Wrap(err)
+			cfg.Logger.ErrorContext(supervisor.ExitContext(), "Cloud labels will not be imported.", "error", err)
```
Comment (codingllama) [inline lib/service/service.go:1000]:
```suggestion
			cfg.Logger.ErrorContext(supervisor.ExitContext(), "Cloud labels will not be imported", "error", err)
			// Keep going.
```

File: lib/service/service.go (hunk 4 above)
Comment (atburke) [reply lib/service/service.go]: Sometimes a user doesn't need labels to be imported, so they don't configure their instance to do so. An error here isn't a problem for them and shouldn't prevent Teleport from starting. (all of this is now in a comment)

Comment (codingllama) [reply lib/service/service.go]: Thanks, that helps.

File: lib/service/service.go [hunk 7]
```diff
@@ -967,8 +967,14 @@ func NewTeleport(cfg *servicecfg.Config) (*TeleportProcess, error) {
 	imClient := cfg.InstanceMetadataClient
 	if imClient == nil {
 		imClient, err = cloud.DiscoverInstanceMetadata(supervisor.ExitContext())
-		if err != nil && !trace.IsNotFound(err) {
-			return nil, trace.Wrap(err)
+		if err == nil {
+			cfg.Logger.InfoContext(supervisor.ExitContext(),
+				"Found an instance metadata service. Teleport will import labels from this cloud instance",
```
Comment (codingllama) [inline lib/service/service.go:972]: Suggestion: Since you have 2 sentences here I would keep the full stop, I think it's fine in cases like this.

```suggestion
				"Found an instance metadata service. Teleport will import labels from this cloud instance.",
```

**Review by codingllama — APPROVED** [review]
