### PR TITLE
Quiet noisy logging of k8s port forwarding streams

### LINKED ISSUE #5594: Log spam in kube/proxy/portforward.go
### Description

**What happened**:

Function `monitorStreamPair` is spamming logs. See [/lib/kube/proxy/portforward.go:263-272](https://github.com/gravitational/teleport/blob/master/lib/kube/proxy/portforward.go#L263-L272). 

See [gist](https://gist.githubusercontent.com/travelton/7aa5c148f9f25c5b9ae12638ca74146c/raw/ca1def8e8a019e3e7d5a9259467dddb12851d273/gistfile1.txt) for example of log spam.

**What you expected to happen**:

This method should print the pointer using `%p` instead of `%v`. 

### Reproduction Steps
1. Configure a Teleport cluster w/ Kubernetes node. 
2. `kubectl port-forward <pod> <port>:<port>`
3. Pull data over the forwarded port and watch Teleport Proxy logs. 

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
```
Feb 17 00:20:53 server-1 teleport[29552]: INFO             (conn=&{0xc000eccc60 [0xc001ac3360 0xc001ac3400 0xc0006ff5e0 0xc0006ff680 0xc001a0ec80 0xc001a0ed20 0xc001a0f4a0 0xc001a0f540 0xc00203e140 0xc00203e1e0 0xc00203e8c0 0xc00203eb40 0xc00203f9a0 0xc00203fc20 0xc00203e640 0xc00203e6e0 0xc00203edc0 0xc00203ee60 0xc00203f720 0xc00203f7c0 0xc000fd4460 0xc000fd4500 0xc000fd4a00 0xc000fd4b40 0xc000fd4f00 0xc000fd4fa0 0xc000eec000 0xc000eec0a0] {0 0} 0x1e507a0 0x1e2e420}, request=13) successfully received error and data streams proxy/portforward.go:269
```

### Which platform(s)
- [ ] Teleport Open Source
- [ ] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [ ] Server Access
- [x] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [ ] Other

### PR DESCRIPTION
**Pull request by travelton**
Closes #5594 

```sh
$ kubectl port-forward -n teleport <kube agent pod> 3000:3000
$ curl localhost:3000
```

Before:

```
Feb 17 00:20:51 build-box teleport[29552]: INFO (conn=&{0xc000eccc60 [0xc001ac3360 0xc001ac3400 0xc0006ff5e0 0xc0006ff680 0xc001a0ec80 0xc001a0ed20 0xc001a0f4a0 0xc001a0f540 0xc00203e140 0xc00203e1e0 0xc00203e8c0 0xc00203eb40 0xc00203f9a0 0xc00203fc20 0xc00203e640 0xc00203e6e0 0xc00203edc0 0xc00203ee60 0xc00203f720 0xc00203f7c0 0xc000fd4460 0xc000fd4500 0xc000fd4a00 0xc000fd4b40 0xc000fd4f00 0xc000fd4fa0] {0 0} 0x1e507a0 0x1e2e420}, request=12) successfully received error and data streams proxy/portforward.go:269
```

After:

```
Feb 17 00:54:44 build-box teleport[5100]: DEBU (conn=0xc001cbcc80, request=12) successfully received error and data streams proxy/portforward.go:269
```

### CODE REVIEW

File: lib/kube/proxy/portforward.go [hunk 1]
```diff
@@ -263,10 +263,10 @@ func (h *portForwardProxy) getStreamPair(requestID string) (*httpStreamPair, boo
 func (h *portForwardProxy) monitorStreamPair(p *httpStreamPair, timeout <-chan time.Time) {
 	select {
 	case <-timeout:
-		err := fmt.Errorf("(conn=%v, request=%s) timed out waiting for streams", h.sourceConn, p.requestID)
+		err := fmt.Errorf("(conn=%p, request=%s) timed out waiting for streams", h.sourceConn, p.requestID)
```
Comment (r0mant) [inline lib/kube/proxy/portforward.go:266]: Do we need to log the pointer address for the connection here (and everywhere else in this method) at all? Just wondering what kind of debugging it can be potentially useful for, other than maybe correlating the addresses to find logs for the same connection. Is there maybe a more useful connection property we can log here which is also more human-readable, say, remote addr?

Comment (travelton) [reply lib/kube/proxy/portforward.go:266]: If I log through `portForwardProxy` (w/ `h.Infof()`), I get `log.WithFields` that includes the remote address.  https://github.com/gravitational/teleport/blob/master/lib/kube/proxy/portforward.go#L80-L83

Given that `portForwardProxy.sourceConn` is the connection handler for the remote request, it seems that `log.WithFields` appending remote address should provide enough context to correlate log lines between source connections. 

Proposal:
```golang
// Before
log.Debugf("(conn=%p, request=%s) successfully received error and data streams", h.sourceConn, p.requestID)
// After
h.Debugf("Request: %s, successfully received error and data streams.", p.requestID)
```
Output:
```
DEBU [PROXY:KUB] Request: 5, successfully received error and data streams. addr.remote:24.27.x.x:63537 proxy/portforward.go:270
```

Any idea why we print this error, instead of logging it? 
https://github.com/gravitational/teleport/blob/master/lib/kube/proxy/portforward.go#L266-L267

Comment (awly) [reply lib/kube/proxy/portforward.go:266]: that code is pretty old, but I assume the `printError` call is to give the client some feedback on the problem (instead of only showing it in the server's log)

**Review by awly — APPROVED** [review]

**Review by xacrimon — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.
