### PR TITLE
Prevent flakiness in TestKube/Join

### LINKED ISSUE #55044: `TestKube/Join` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/15163475780/job/42635072346#step:9:1483
- https://github.com/gravitational/teleport/actions/runs/15182009981/job/42693381271?pr=55042#step:9:940

#### Relevant snippet

```
    kube_integration_test.go:2362: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:2362
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:175
        	Error:      	"/ # \x1b[6n\r\nTeleport > Joining session with participant mode: peer\r\nTeleport > Controls\r\nTeleport >   - CTRL-C: Leave the session\r\nhi from peer\r\n/bin/sh: hi: not found\r\n/ # \r\n/ # \x1b[6n" does not contain "hi from term"
        	Test:       	TestKube/Join
```

### PR DESCRIPTION
**Pull request by rosstimothy**
The test was reliant on all the output of a session being replicated to all parties before a 5s timer closed the session. To make the test more resiliant it was rewritten such that it validates the expected output from one of the parties output, then exits the session, then when all parties have been closed, it examines the entire output of the other parties to validate their output.

Fixes https://github.com/gravitational/teleport/issues/55044

### CODE REVIEW

File: integration/kube_integration_test.go [hunk 1]
```diff
@@ -2530,31 +2530,73 @@ func testKubeJoin(t *testing.T, suite *KubeSuite) {
...
 	for _, capture := range observerCaptures {
-		assert.Contains(t, capture.String(), "hi from peer")
-		assert.Contains(t, capture.String(), "hi from term")
+		output := capture.String()
+		assert.Contains(t, output, "hi from peer")
+		assert.Contains(t, output, "hi from term")
+	}
+}
+
+func waitForOutput(ctx context.Context, r ReaderWithDeadline, expected string) error {
```
Comment (rosstimothy) [inline integration/kube_integration_test.go:2559]: This was taken from lib/web/apiserver_test.go with a slight modification.

**Review by kshi36 — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
