### PR TITLE
Fix crash when AWS Redshift does not have Endpoint info

### LINKED ISSUE #10592: Database service may crash while provisioning AWS Redshift [v9 testing]
### Description

**What happened**:
Database service crashes while provisioning AWS Redshift.

Turned out `redshift.Endpoint` is still `nil` when cluster is being provisioned, and if database service is trying to auto discover at this unfortunate time, the service will crash.

Didn't catch in original implementation, as the timing is not easily reproduced.

The line crashing is https://github.com/gravitational/teleport/blob/2e7a14daf9fd9743cc7b37c560f3b5c2cd2a5a21/lib/services/database.go#L227

**What you expected to happen**:
Database service should not  crash

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Enable redshift autodiscovery
2. Wait for database server to scan

### Server Details
- Teleport version (run `teleport version`): `branch/v9`

### Client Details
- Tsh version (`tsh version`): `branch/v9`

### Debug Logs
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14039f9]
goroutine 1125 [running]:                                                                                                                        
github.com/gravitational/teleport/lib/services.NewDatabaseFromRedshiftCluster(0xc0002c4a00)
/go/teleport/lib/services/database.go:227 +0xf9       
github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*redshiftFetcher).Get(0xc000dcd240, {0x522fa70, 0xc00028c7c0})                       
/go/teleport/lib/srv/db/cloud/watchers/redshift.go:89 +0x105                                         
github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).fetchAndSend(0xc0002b9340)                      
/go/teleport/lib/srv/db/cloud/watchers/watcher.go:120 +0x18b                               
github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).Start(0xc0002b9340)       
/go/teleport/lib/srv/db/cloud/watchers/watcher.go:108 +0xc5                                                                                                              
created by github.com/gravitational/teleport/lib/srv/db.(*Server).startCloudWatcher       
/go/teleport/lib/srv/db/watcher.go:116 +0x1dc                                                                                                   
teleport_db.service: main process exited, code=exited, status=2/INVALIDARGUMENT                            
Unit teleport_db.service entered failed state.                                                                       
teleport_db.service failed.
```

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #10592
- #10592 

When AWS Redshift is being created, it may not have `Endpoint` info yet. If we happen to do an auto discovery during this, it crashes database service as we are missing the nil check for `redshift.Cluster.Endpoint`

### CODE REVIEW

File: lib/services/database_test.go [hunk 1]
```diff
@@ -384,46 +385,58 @@ func TestRDSTagsToLabels(t *testing.T) {
...
-		ClusterNamespaceArn: aws.String("arn:aws:redshift:us-east-1:1234567890:namespace:u-u-i-d"),
-		Endpoint: &redshift.Endpoint{
-			Address: aws.String("localhost"),
-			Port:    aws.Int64(5439),
-		},
-		Tags: []*redshift.Tag{
-			{
-				Key:   aws.String("key"),
-				Value: aws.String("val"),
+	t.Run("success", func(t *testing.T) {
```
Comment (greedy52) [inline lib/services/database_test.go:388]: just moving existing test in a subtest. ignore whitespace may hide all these shifts.

File: lib/services/database_test.go [hunk 2]
```diff
@@ -384,46 +385,58 @@ func TestRDSTagsToLabels(t *testing.T) {
...
+		require.NoError(t, err)
+		require.Equal(t, expected, actual)
+	})
+
+	t.Run("missing endpoint", func(t *testing.T) {
+		_, err := NewDatabaseFromRedshiftCluster(&redshift.Cluster{
+			ClusterIdentifier: aws.String("still-creating"),
+		})
+		require.Error(t, err)
+		require.True(t, trace.IsBadParameter(err))
```
Comment (codingllama) [inline lib/services/database_test.go:440]: Suggestion: simplify and add description

```suggestion
		require.True(t, trace.IsBadParameter(err), "DESCRIBE FAILURE HERE")
```

Failures saying that `false != true` aren't the best.

**Review by codingllama — APPROVED** [review]
Could you set a shorter title before merging? This is going to look rough in the git logs.

Personally I aim for 72 chars in title, up to you.

File: lib/services/database.go [hunk 3]
```diff
@@ -213,6 +213,10 @@ func NewDatabasesFromRDSClusterCustomEndpoints(cluster *rds.DBCluster) (types.Da
 
 // NewDatabaseFromRedshiftCluster creates a database resource from a Redshift cluster.
 func NewDatabaseFromRedshiftCluster(cluster *redshift.Cluster) (types.Database, error) {
+	if cluster.Endpoint == nil {
```
Comment (espadolini) [inline lib/services/database.go:216]: Perhaps we should add a note saying that this can happen in the course of normal operation due to the race condition described in #10592 and thus is not an immediate cause of worry.

**Review by espadolini — APPROVED** [review]

File: lib/services/database.go (hunk 3 above)
Comment (espadolini) [reply lib/services/database.go:216]: Also, could we filter these earlier, during `(*redshiftFetcher).Get` maybe?

**Review by smallinsky — APPROVED** [review]

File: lib/services/database_test.go [hunk 4]
```diff
@@ -384,46 +385,58 @@ func TestRDSTagsToLabels(t *testing.T) {
...
+		require.NoError(t, err)
+		require.Equal(t, expected, actual)
+	})
+
+	t.Run("missing endpoint", func(t *testing.T) {
+		_, err := NewDatabaseFromRedshiftCluster(&redshift.Cluster{
+			ClusterIdentifier: aws.String("still-creating"),
+		})
+		require.Error(t, err)
+		require.True(t, trace.IsBadParameter(err), fmt.Sprintf("expected trace.BadParameter, got %v", err))
```
Comment (codingllama) [inline lib/services/database_test.go:440]: Drop the printf, require functions do formatting:

```suggestion
		require.True(t, trace.IsBadParameter(err), "Expected trace.BadParameter, got %v", err)
```

I would drop the check above too, as this ends up doing both and has an error description. Up to you.

Comment (greedy52) [reply lib/services/database_test.go]: ah, nice. removed the fmt. i think i will keep the `require.Error`.

**Review by espadolini — APPROVED** [review]

File: lib/services/database.go [hunk 5]
```diff
@@ -213,6 +213,12 @@ func NewDatabasesFromRDSClusterCustomEndpoints(cluster *rds.DBCluster) (types.Da
 
 // NewDatabaseFromRedshiftCluster creates a database resource from a Redshift cluster.
 func NewDatabaseFromRedshiftCluster(cluster *redshift.Cluster) (types.Database, error) {
+	// Endpoint can be nil while the cluster is being created. Return an error
+	// until the Endpoint is available.
+	if cluster.Endpoint == nil {
+		return nil, trace.BadParameter("missing endpoint in Redshift cluster %v", aws.StringValue(cluster.ClusterIdentifier))
```
Comment (r0mant) [inline lib/services/database.go:219]: This error is handled gracefully by the caller and doesn't prevent auto-discovery of other databases, correct? I'm pretty sure it should be the case, just double-checking. If so, lgtm.

**Review by codingllama — APPROVED** [review]

File: lib/services/database.go (hunk 5 above)
Comment (greedy52) [reply lib/services/database.go:219]: yes. it will log the message but it will not prevent the loop to discover others
https://github.com/gravitational/teleport/blob/278b3b7e051fde9790dd05c29d48194cae35fbf7/lib/srv/db/cloud/watchers/redshift.go#L88-L94
