### PR TITLE
integrations/operator: Use a dedicated scheme in tests

### LINKED ISSUE #26753: `TestLoginRuleController` flakiness
## Failure

`TestLoginRuleController` is flaky since the introduction of the race detector in e/.

#### Link(s) to logs

- https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470

#### Relevant snippet

```
go test -v ./lib/operatortest -race
=== RUN   TestLoginRuleController
=== PAUSE TestLoginRuleController
=== CONT  TestLoginRuleController
time="2023-05-22T17:18:3[9](https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470#step:9:10)Z" level=info msg="Generating TLS certificate 1.3.9999.1.7=#13096c6f63616c686f7374,CN=test-tls-server.localhost,O=Auth,POSTALCODE=null,STREET=" dns_names="[*.teleport.cluster.local teleport.cluster.local]" key_usage=5 not_after="2033-05-19 17:18:39.222604203 +0000 UTC" trace.component=ca
time="2023-05-22T17:18:39Z" level=info msg="Generating TLS certificate 1.3.9999.1.7=#13096c6f63616c686f7374,CN=Admin.localhost,O=Admin,POSTALCODE=null,STREET=" dns_names="[*.teleport.cluster.local teleport.cluster.local]" key_usage=5 not_after="2033-05-19 17:18:39.222604203 +0000 UTC" trace.component=ca
=== RUN   TestLoginRuleController/creation
=== PAUSE TestLoginRuleController/creation
=== RUN   TestLoginRuleController/deletion_drift
=== PAUSE TestLoginRuleController/deletion_drift
=== RUN   TestLoginRuleController/update
=== PAUSE TestLoginRuleController/update
=== CONT  TestLoginRuleController/update
=== CONT  TestLoginRuleController/deletion_drift
=== CONT  TestLoginRuleController/creation
==================
WARNING: DATA RACE
Write at 0x00c00085f3e0 by goroutine 91:
  runtime.mapassign()
      /opt/go/src/runtime/map.go:578 +0x0
  k8s.io/apimachinery/pkg/runtime.(*Scheme).AddUnversionedTypes()
      /go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/runtime/scheme.go:[12](https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470#step:9:13)9 +0x58b
  k8s.io/apimachinery/pkg/apis/meta/v1.AddToGroupVersion()
      /go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/apis/meta/v1/register.go:75 +0x60a
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).Register.func1()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.[14](https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470#step:9:15).6/pkg/scheme/scheme.go:72 +0xbb
  k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme()
      /go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/runtime/scheme_builder.go:29 +0xa1
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).AddToScheme()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/scheme/scheme.go:86 +0x2c
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).AddToScheme-fm()
      <autogenerated>:1 +0x44
  github.com/gravitational/teleport/integrations/operator/controllers/resources/testlib.SetupTestEnv()
      /__w/teleport.e/teleport.e/integrations/operator/controllers/resources/testlib/env.go:262 +0x3b8
  github.com/gravitational/teleport/integrations/operator/controllers/resources/testlib.ResourceDeletionDriftTest[...]()
      /__w/teleport.e/teleport.e/integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go:89 +0xab
  github.com/gravitational/teleport/integrations/operator/controllers/resources/testlib.LoginRuleDeletionDriftTest()
      /__w/teleport.e/teleport.e/integrations/operator/controllers/resources/testlib/login_rule_controller_tests.go:149 +0xbc
  github.com/gravitational/teleport/e/lib/operatortest.TestLoginRuleController.func1()
      /__w/teleport.e/teleport.e/e/lib/operatortest/loginrule_controller_test.go:43 +0x52
  testing.tRunner()
      /opt/go/src/testing/testing.go:[15](https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470#step:9:16)76 +0x2[16](https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470#step:9:17)
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).Register.func1()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/scheme/scheme.go:72 +0xbb
  k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme()
      /go/pkg/mod/k8s.io/apimachinery@v0.26.3/pkg/runtime/scheme_builder.go:29 +0xa1
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).AddToScheme()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/scheme/scheme.go:86 +0x2c
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).AddToScheme-fm()
      <autogenerated>:1 +0x44
  github.com/gravitational/teleport/integrations/operator/controllers/resources/testlib.SetupTestEnv()
      /__w/teleport.e/teleport.e/integrations/operator/controllers/resources/testlib/env.go:271 +0x624
  github.com/gravitational/teleport/integrations/operator/controllers/resources/testlib.ResourceDeletionDriftTest[...]()
      /__w/teleport.e/teleport.e/integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go:89 +0xab
  github.com/gravitational/teleport/integrations/operator/controllers/resources/testlib.LoginRuleDeletionDriftTest()
      /__w/teleport.e/teleport.e/integrations/operator/controllers/resources/testlib/login_rule_controller_tests.go:149 +0xbc
  github.com/gravitational/teleport/e/lib/operatortest.TestLoginRuleController.func1()
      /__w/teleport.e/teleport.e/e/lib/operatortest/loginrule_controller_test.go:43 +0x52
  testing.tRunner()
      /opt/go/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1629 +0x47

Goroutine 95 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1629 +0x805
  github.com/gravitational/teleport/e/lib/operatortest.TestLoginRuleController()
      /__w/teleport.e/teleport.e/e/lib/operatortest/loginrule_controller_test.go:41 +0x168
  testing.tRunner()
      /opt/go/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1629 +0x47

Goroutine 91 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1629 +0x805
  github.com/gravitational/teleport/e/lib/operatortest.TestLoginRuleController()
      /__w/teleport.e/teleport.e/e/lib/operatortest/loginrule_controller_test.go:41 +0x168
  testing.tRunner()
      /opt/go/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1629 +0x47
==================
=== NAME  TestLoginRuleController/update
    testing.go:1446: race detected during execution of test
=== NAME  TestLoginRuleController/deletion_drift
    testing.go:1446: race detected during execution of test
=== NAME  TestLoginRuleController/creation
    testing.go:1446: race detected during execution of test
time="2023-05-22T[17](https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470#step:9:18):[18](https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470#step:9:19):48Z" level=warning msg="Mux serve failed." error="listener is closed\n\taccept tcp 127.0.0.1:40281: use of closed network connection" trace.component=auth
--- FAIL: TestLoginRuleController (0.68s)
    --- FAIL: TestLoginRuleController/update (7.65s)
    --- FAIL: TestLoginRuleController/deletion_drift (7.79s)
    --- FAIL: TestLoginRuleController/creation (8.15s)
FAIL
FAIL	github.com/gravitational/teleport/e/lib/operatortest	9.0[21](https://github.com/gravitational/teleport.e/actions/runs/5048568926/jobs/9056926772?pr=1470#step:9:22)s
FAIL
```

### PR DESCRIPTION
**Pull request by hugoShaka**
Fixes https://github.com/gravitational/teleport/issues/26753

Relying on a global scheme can cause race-conditions when registering schema in multiple tests. This commit does two things in an attempt to fix https://github.com/gravitational/teleport/issues/26753:

- use a separate Scheme for tests to avoid being affected by what others might be doing with the scheme
- initiate the Scheme only once during import

### CODE REVIEW

File: integrations/operator/controllers/resources/testlib/env.go [hunk 1]
```diff
@@ -48,6 +50,18 @@ import (
 	"github.com/gravitational/teleport/lib/service/servicecfg"
 )
 
+// Scheme is our own test-specific scheme to avoid using the global
+// unprotected scheme.Scheme that triggers the race detector
+var Scheme = apiruntime.NewScheme()
```
Comment (zmb3) [inline integrations/operator/controllers/resources/testlib/env.go:55]: Can we unexport this?

**Review by marcoandredinis — APPROVED** [review]
Aside from that exported `Scheme`, LGTM 👍

**Review by tigrato — APPROVED** [review]
un-export scheme

**Review by zmb3 — APPROVED** [review]
