### PR TITLE
fix: prevent deleting AWS OIDC integration used by EAS

### LINKED ISSUE #37950: AWS OIDC integration used for EAS can be deleted which blocks Auth startup
Expected behavior:
If I set up External Audit Storage, which requires an AWS OIDC integration to work, I should not be able to delete that AWS OIDC integration (without first deleting the External Audit Storage integration). In any case, Auth startup should never be blocked by a user action.

Current behavior:
I am able to delete an AWS OIDC integration even if it is used by an active External Audit Storage integration. The next time the Auth service restarts, it will not be able to start, because External Audit Storage will be broken.
I get an error like this in the Auth Service logs and it fails to start:
```
Error: *trace.NotFoundError ExternalAuditStorage: configured AWS OIDC integration &#34;Consolidated&#34; not found
```

This also affects discovery services using the integration, but that is less critical because at least the Auth service can still start up.

Bug details:
- Teleport version: 14.3+ Cloud
- Recreation steps
  - Create AWS OIDC integration
  - Create External Audit Storage integration
  - Delete AWS OIDC integration
  - Don't restart the Auth service or it won't come back up and it will be very difficult to fix
- Debug logs

### PR DESCRIPTION
**Pull request by nklaassen**
The External Audit Storage feature for Teleport Cloud depends on an AWS OIDC integration to exist in order to get credentials for the customer AWS account.
It's currently possible for a customer to delete the AWS OIDC integration referenced by the EAS configuration, leading to the EAS integration breaking and the Auth service crashing the next time it's started up.

This commit prevents deleting an AWS OIDC integration currently referenced by and EAS integration, and prevents creating an EAS integration referencing an unknown AWS OIDC integration.

Screenshot 2024-04-18 at 2 57 11 PM

Fixes https://github.com/gravitational/teleport/issues/37950

teleport.e buddy: https://github.com/gravitational/teleport.e/pull/3978
followup to use the better service constructor name: https://github.com/gravitational/teleport/pull/40631

Changelog: prevent deleting AWS OIDC integration used by External Audit Storage.

### CODE REVIEW

**Comment by marcoandredinis** [comment]
I was thinking about what we need to do to ensure we don't delete integrations for other resources.
The way it is now, it will require adding other services into the IntegrationService.
I think that can become confusing as we add more.

Instead, I tried to add a concept of `PreDeleteChecks` to the IntegrationsService.
It's list of `func(ctx context.Context, integrationName string) error` functions that are called before the `s.svc.DeleteResource(ctx, name)` .
It might require double SemaphoreLocking, but with proper namespacing/formatting I think we can get that right.

```go
func deleteIntegrationLockNameFmt(name string) string {
	return fmt.Sprintf("integration_storage_lock_%s", name)
}

// IntegrationsService manages Integrations in the Backend.
type IntegrationsService struct {
	svc              generic.Service[types.Integration]
	backend          backend.Backend
	deleteAllEnabled bool
	preDeleteChecks  []PreDeleteCheck
}

type PreDeleteCheck func(ctx context.Context, integrationName string) error

func WithPreDeleteCheck(fn PreDeleteCheck) func(*IntegrationsService) {
	return func(svc *IntegrationsService) {
		svc.preDeleteChecks = append(svc.preDeleteChecks, fn)
	}
}
// ....

// DeleteIntegration removes the specified Integration resource.
func (s *IntegrationsService) DeleteIntegration(ctx context.Context, name string) error {
	err := backend.RunWhileLocked(ctx, backend.RunWhileLockedConfig{
		LockConfiguration: backend.LockConfiguration{
			Backend:  s.backend,
			LockName: deleteIntegrationLockNameFmt(name),
			TTL:      externalAuditStorageLockTTL,
		},
	}, func(ctx context.Context) error {
		for _, check := range s.preDeleteChecks {
			if err := check(ctx, name); err != nil {
				return trace.Wrap(err)
			}
		}

		return trace.Wrap(s.svc.DeleteResource(ctx, name))
	})
	return trace.Wrap(err)
}
```

Then, when starting the service, we add a pre-delete check that will ensure the deletion doesn't happen if that is being used in the EAS.


```go

func (p *Plugin) registerExternalAuditStorageService(ctx context.Context) error {
	externalAuditStorage := local.NewExternalAuditStorageService(p.authServer.GetBackend())

	integrationsSvc, err := local.NewIntegrationsService(p.authServer.GetBackend(), local.WithPreDeleteCheck(externalAuditStorage.PreventIntegrationDeletionForEAS))
	if err != nil {
		return trace.Wrap(err)
	}
```


```go
// this runs under lock `integration_storage_lock_<integrationName>`
func (s *ExternalAuditStorageService) PreventIntegrationDeletionForEAS(ctx context.Context, integrationName string) error {
	// Avoid deleting AWS OIDC integrations referenced by any External Audit Storage integration.
	// It's necessary to do this under the same lock that is used to create and promote EAS configurations to
	// avoid a race condition where an AWS OIDC configuration could be deleted immediately after a new EAS
	// configuration is added.
	err := backend.RunWhileLocked(ctx, backend.RunWhileLockedConfig{
		LockConfiguration: backend.LockConfiguration{
			Backend:  s.backend,
			LockName: externalAuditStorageLockName,
			TTL:      externalAuditStorageLockTTL,
		},
	}, func(ctx context.Context) error {
		if draft, err := s.GetDraftExternalAuditStorage(ctx); err == nil {
			if draft.Spec.IntegrationName == integrationName {
				return trace.BadParameter("cannot delete AWS OIDC integration currently referenced by draft External Audit Storage integration")
			}
		} else if !trace.IsNotFound(err) {
			return trace.Wrap(err)
		}
		if cluster, err := s.GetClusterExternalAuditStorage(ctx); err == nil {
			if cluster.Spec.IntegrationName == integrationName {
				return trace.BadParameter("cannot delete AWS OIDC integration currently referenced by cluster External Audit Storage integration")
			}
		} else if !trace.IsNotFound(err) {
			return trace.Wrap(err)
		}
		return nil
	})
	return trace.Wrap(err)
}
```

Let me know what you think about this approach

**Comment by nklaassen** [comment]
@marcoandredinis I like the PreDeleteCheck suggestion, I'm doing a version of it in the latest, check it out

File: lib/services/local/externalauditstorage.go [hunk 1]
```diff
@@ -233,10 +258,81 @@ func (s *ExternalAuditStorageService) PromoteToClusterExternalAuditStorage(ctx c
...
+	})
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+	// Be sure to release the lock if returning an error, otherwise the caller will be responsible for releasing it.
+	defer func() {
+		if err != nil {
+			lock.Release(ctx, bk)
+		}
+	}()
```
[the remark this answers is not in the document]
Comment (nklaassen) [reply lib/services/local/externalauditstorage.go:319]: Yeah it's a bit unintuitive but it definitely works, I find it to be a pretty handy Go feature in some cases like this where I want to be 100% sure that the lock gets released if returning any error later on.

The relevant part of the spec is
> Regardless of how they are declared, all the result values are initialized to the [zero values](https://go.dev/ref/spec#The_zero_value) for their type upon entry to the function. A "return" statement that specifies results sets the result parameters before any deferred functions are executed.

File: lib/services/local/externalauditstorage.go [hunk 2]
```diff
@@ -47,31 +47,48 @@ var (
...
+		logger:          logrus.WithField(teleport.ComponentKey, "ExternalAuditStorage.backend"),
+	}, nil
+}
+
+// NewExternalAuditStorageServiceFallible returns a new *ExternalAuditStorageService.
+// TODO(nklaassen): once teleport.e is updated unify this with NewExternalAuditStorageServiceFallible.
+func NewExternalAuditStorageService(backend backend.Backend) *ExternalAuditStorageService {
+	svc, err := NewExternalAuditStorageServiceFallible(backend)
+	if err != nil {
+		panic(err)
```
[the remark this answers is not in the document]
Comment (nklaassen) [reply lib/services/local/externalauditstorage.go:76]: yep I'm deleting it in https://github.com/gravitational/teleport/pull/40631

File: lib/auth/integration/integrationv1/service_test.go [hunk 3]
```diff
@@ -375,7 +433,10 @@ func initSvc(t *testing.T, ca types.CertAuthority, clusterName string, proxyPubl
 	})
 	require.NoError(t, err)
 
-	localResourceService, err := local.NewIntegrationsService(backend)
+	localResourceService, err := local.NewIntegrationsService(backend,
+		local.WithPreDeleteChecks(local.EASIntegrationPreDeleteCheck),
+		local.WithDeleteAllIntegrationsEnabled(true),
```
[the remark this answers is not in the document]
Comment (nklaassen) [reply lib/auth/integration/integrationv1/service_test.go:443]: I specifically wanted both just for this test to work 😅 DeleteAll doesn't seem to be called anywhere except potentially by the cache stuff, so I didn't think it was worth setting up the PreDeleteChecks properly in there, especially since i would have to handle paging and it seemed pointless, and we probably shouldn't actually be running PreDeleteChecks in a cache

File: lib/auth/integration/integrationv1/service_test.go [hunk 4]
```diff
@@ -244,6 +246,53 @@ func TestIntegrationCRUD(t *testing.T) {
 			},
 			ErrAssertion: noError,
 		},
+		{
```
[the remark this answers is not in the document]
Comment (nklaassen) [reply lib/auth/integration/integrationv1/service_test.go:256]: I moved the passing case after these cases for the same effect

File: lib/auth/integration/integrationv1/service_test.go [hunk 5]
```diff
@@ -244,6 +246,53 @@ func TestIntegrationCRUD(t *testing.T) {
...
+					Verbs:     []string{types.VerbDelete},
+				}}},
+			},
+			Setup: func(t *testing.T, igName string) {
+				_, err := localClient.CreateIntegration(ctx, sampleIntegrationFn(t, igName))
+				require.NoError(t, err)
+				_, err = localClient.GenerateDraftExternalAuditStorage(ctx, igName, "us-west-2")
+				require.NoError(t, err)
+				err = localClient.PromoteToClusterExternalAuditStorage(ctx)
+				require.NoError(t, err)
```
[the remark this answers is not in the document]
Comment (nklaassen) [reply lib/auth/integration/integrationv1/service_test.go]: added

**Review by marcoandredinis — APPROVED** [review]

**Comment by nklaassen** [comment]
@camscale @fspmarshall I'm looking for one more review on this one

**Review by camscale — APPROVED** [review]
I don't know this stuff all that well, but it looks ok to me.

File: lib/services/local/integrations.go [hunk 6]
```diff
@@ -36,11 +36,43 @@ const (
 
 // IntegrationsService manages Integrations in the Backend.
 type IntegrationsService struct {
-	svc generic.Service[types.Integration]
+	svc              generic.Service[types.Integration]
+	backend          backend.Backend
+	preDeleteChecks  []PreDeleteCheck
```
Comment (espadolini) [inline lib/services/local/integrations.go:41]: Is this intended to be called for any deletion in the `IntegrationsService`, or just the deletion of OIDC integrations? What happens if we extend the scope of `IntegrationsService` to multiple types of integrations, for example? Why should the caller be responsible for figuring out the interdependency between resources managed by the two services?

 Is this really better than spawning a new `ExternalAuditStorageService` on the fly, depending on the same "cache mode" that's enabled if `deleteAllEnabled` is set?

File: lib/services/local/externalauditstorage.go [hunk 7]
```diff
@@ -47,31 +47,48 @@ var (
 
 // ExternalAuditStorageService manages External Audit Storage resources in the Backend.
 type ExternalAuditStorageService struct {
-	backend backend.Backend
-	logger  *logrus.Entry
+	backend         backend.Backend
+	integrationsSvc *IntegrationsService
```
Comment (espadolini) [inline lib/services/local/externalauditstorage.go:51]: Can't we just call `NewIntegrationsService(s.backend)` as needed?

Comment (nklaassen) [reply lib/services/local/externalauditstorage.go]: yeah that simplifies things thanks

File: lib/services/local/externalauditstorage.go [hunk 8]
```diff
@@ -36,8 +35,6 @@ const (
 	externalAuditStoragePrefix      = "external_audit_storage"
 	externalAuditStorageDraftName   = "draft"
 	externalAuditStorageClusterName = "cluster"
-	externalAuditStorageLockName    = "external_audit_storage_lock"
```
Comment (nklaassen) [inline lib/services/local/externalauditstorage.go:39]: I will add a ConditionalAction that this lock doesn't exist to all new AtomicWrites in the backports to v15 and v14.

This should prevent e.g. a v15.2.3+ auth with these changes from racing with a v15.2.2 auth that's till using the lock

File: lib/services/local/integrations.go (hunk 6 above)
Comment (nklaassen) [reply lib/services/local/integrations.go]: I reworked this with the AtomicWrite rewrite

File: lib/services/local/externalauditstorage.go (hunk 8 above)
Comment (nklaassen) [reply lib/services/local/externalauditstorage.go:39]: well I guess in v14 I'll go back to using the lock since atomicwrite doesn't exist

File: lib/services/local/externalauditstorage.go [hunk 9]
```diff
@@ -109,22 +113,28 @@ func (s *ExternalAuditStorageService) UpsertDraftExternalAuditStorage(ctx contex
...
+			Action:    backend.Put(item),
 		},
-	}, func(ctx context.Context) error {
-		_, err = s.backend.Put(ctx, backend.Item{
-			Key:   draftExternalAuditStorageBackendKey,
-			Value: value,
-		})
-		return trace.Wrap(err)
 	})
 	return in, trace.Wrap(err)
```
Comment (espadolini) [inline lib/services/local/externalauditstorage.go:139]: The returned `*externalauditstorage.ExternalAuditStorage` should have the revision returned by the successful `AtomicWrite`; not sure if it's necessary to clone it or not, but considering that this is a configuration change that happens rarely (and thus isn't very perf-critical) it might be worth doing.

File: lib/services/local/externalauditstorage.go [hunk 10]
```diff
@@ -109,22 +113,28 @@ func (s *ExternalAuditStorageService) UpsertDraftExternalAuditStorage(ctx contex
...
-	err = backend.RunWhileLocked(ctx, backend.RunWhileLockedConfig{
-		LockConfiguration: backend.LockConfiguration{
-			Backend:  s.backend,
-			LockName: externalAuditStorageLockName,
-			TTL:      externalAuditStorageLockTTL,
+	integrationKey, integrationRevision, err := s.checkAWSIntegration(ctx, in.Spec.IntegrationName)
+	if err != nil {
+		return nil, trace.Wrap(err, "checking AWS OIDC integration")
+	}
+	_, err = s.backend.AtomicWrite(ctx, []backend.ConditionalAction{
```
Comment (espadolini) [inline lib/services/local/externalauditstorage.go:125]: If the `AtomicWrite` fails due to a concurrent change of the relevant OIDC integration we should probably try again, and only fail after some iterations (3? 5?), or if `checkAWSIntegration` detects an invalid state; same for `CreateDraftExternalAuditStorage`.

File: lib/services/local/integrations.go [hunk 11]
```diff
@@ -36,11 +36,25 @@ const (
 
 // IntegrationsService manages Integrations in the Backend.
 type IntegrationsService struct {
-	svc generic.Service[types.Integration]
+	svc              generic.Service[types.Integration]
+	backend          backend.Backend
+	deleteAllEnabled bool
```
Comment (espadolini) [inline lib/services/local/integrations.go:41]: What do you think of a more general `unchecked` or `cacheMode`? The only reason why the conditional operations are guaranteed to not fail is that the external audit config is not cached, so there's no way for out of order events to cause conditional checks to fail, but it'd be cleaner to just have a flag for that - `notReferencedByEAS` could be a method on `IntegrationsService` that always returns no conditions if the flag is set, so the rest of the code can just keep using `AtomicWrite`.

File: lib/services/local/integrations.go [hunk 12]
```diff
@@ -100,10 +118,56 @@ func (s *IntegrationsService) UpdateIntegration(ctx context.Context, ig types.In
...
 // DeleteIntegration removes the specified Integration resource.
 func (s *IntegrationsService) DeleteIntegration(ctx context.Context, name string) error {
-	return trace.Wrap(s.svc.DeleteResource(ctx, name))
+	conditionalActions, err := notReferencedByEAS(ctx, s.backend, name)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	conditionalActions = append(conditionalActions, backend.ConditionalAction{
+		Key:       s.svc.MakeKey(name),
+		Condition: backend.Whatever(),
```
Comment (espadolini) [inline lib/services/local/integrations.go:127]: The preparation phase should check that the integration exists and error out with a `trace.NotFound` if it doesn't, and the write should assert that it still exists.

```suggestion
		Condition: backend.Exists(),
```

File: lib/services/local/integrations.go (hunk 11 above)
Comment (nklaassen) [reply lib/services/local/integrations.go]: I introduced the cacheMode and deprecated the gRPC DeleteAllIntegrations

File: lib/services/local/externalauditstorage.go (hunk 10 above)
Comment (nklaassen) [reply lib/services/local/externalauditstorage.go]: These things change so infrequently and slowly, is it really necessary? And you probably really don't want to be editing your EAS configuration live while someone else is concurrently editing the OIDC integrations

Comment (espadolini) [reply lib/services/local/externalauditstorage.go]: It's just a little weird to get `CompareFailed` from a `Delete` or `Upsert` operation, but EAS config is something that's going to be written exactly zero times or one time for basically all cloud tenants anyway, so we can just decide that it's ok to get `CompareFailed`.

**Review by espadolini — APPROVED** [review]
