### PR TITLE
Fix TestAuditSpanner

### LINKED ISSUE #49495: `TestAuditSpanner/access_denied` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/12048114969/job/33592068420#step:6:2132

#### Relevant snippet

```
     spanner_test.go:254: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/db/audit_test.go:423
        	            				/__w/teleport/teleport/lib/srv/db/audit_test.go:394
        	            				/__w/teleport/teleport/lib/srv/db/spanner_test.go:254
        	Error:      	timed out waiting for an audit event
        	Test:       	TestAuditSpanner/access_denied
        	Messages:   	didn't receive any event in time
```

### PR DESCRIPTION
**Pull request by GavinFrazar**
Fixes https://github.com/gravitational/teleport/issues/49495
- https://github.com/gravitational/teleport/issues/49495

### CODE REVIEW

File: lib/srv/db/spanner_test.go [hunk 1]
```diff
@@ -241,45 +242,39 @@ func TestAuditSpanner(t *testing.T) {
...
-		require.ErrorContains(t, err, "access to db denied")
-		require.Nil(t, row)
+		sessionIDs := map[string]struct{}{}
+		require.EventuallyWithT(t, func(t *assert.CollectT) {
+			row, err := pingSpanner(ctx, clt, 42)
+			require.Error(t, err)
+			require.ErrorContains(t, err, "access to db denied")
+			require.Nil(t, row)
 
-		ev = requireEvent(t, testCtx, libevents.DatabaseSessionStartFailureCode)
```
Comment (greedy52) [inline lib/srv/db/spanner_test.go:265]: how was this flaking initially? is it just wait is not long enough or some race condition?

Comment (GavinFrazar) [reply lib/srv/db/spanner_test.go:265]: I think it was caused by the client's connection pool probably reusing a connection instead of opening a new one right away.

Comment (greedy52) [reply lib/srv/db/spanner_test.go:265]: so is this fix to keep sending ping until we see a certain number of session start failures? is it possible to tune the client behavior?

File: lib/srv/db/spanner_test.go [hunk 2]
```diff
@@ -241,45 +242,39 @@ func TestAuditSpanner(t *testing.T) {
...
-		require.Error(t, err)
-		require.ErrorContains(t, err, "access to db denied")
-		require.Nil(t, row)
-
-		ev = requireEvent(t, testCtx, libevents.DatabaseSessionStartFailureCode)
-		dbStart2, ok := ev.(*events.DatabaseSessionStart)
-		require.True(t, ok)
-		require.Equal(t, "googlesql", dbStart1.DatabaseName)
-
 		require.True(t, <-reconnectingCh, "timed out waiting for the spanner client to reconnect")
```
Comment (greedy52) [inline lib/srv/db/spanner_test.go]: is `<-reconnectingCh` still needed? like maybe just run `clt.ClientConn.WaitForStateChange` without the goroutine.

File: lib/srv/db/spanner_test.go [hunk 3]
```diff
@@ -241,45 +242,39 @@ func TestAuditSpanner(t *testing.T) {
...
-		case <-time.After(1 * time.Second):
+		for {
+			select {
+			case evt := <-testCtx.emitter.C():
+				if evt.GetCode() == libevents.DatabaseSessionStartFailureCode {
+					continue
+				}
+				require.FailNow(t, "an unexpected audit event was emitted", "got an audit event with code %v", evt.GetCode())
+			case <-time.After(1 * time.Second):
+				return
```
Comment (greedy52) [inline lib/srv/db/spanner_test.go:269]: understand this is same behavior as before. but there is a chance for false positive when things are slow? not sure if we can improve it though

Comment (GavinFrazar) [reply lib/srv/db/spanner_test.go:269]: it actually passes if the time elapses, but I don't think the timer is needed here. I can just check that no other events have been emitted yet

File: lib/srv/db/spanner_test.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/srv/db/spanner_test.go:265]: I don't see a way to tune the client behavior. I think the important thing is that the test shows that multiple RPCs on the same session handle don't trigger multiple session start failure events.

**Review by greedy52 — APPROVED** [review]

**Comment by GavinFrazar** [comment]
@gabrielcorado

**Review by gabrielcorado — APPROVED** [review]
