### PR TITLE
Fix panic when incoming request is nil

### LINKED ISSUE #24186: Panic in `TestIntegrations`
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4628180314/jobs/8186957687

#### Relevant snippet

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f5991a]

goroutine 42584 [running]:
github.com/gravitational/teleport/lib/sshutils.(*Server).HandleConnection(0xc0022aae00, {0xb048388?, 0xc003b6ad20})
	/__w/teleport/teleport/lib/sshutils/server.go:569 +0x177a
created by github.com/gravitational/teleport/lib/sshutils.(*Server).acceptConnections
	/__w/teleport/teleport/lib/sshutils/server.go:460 +0x56a
FAIL	github.com/gravitational/teleport/integration	85.327s
```

### PR DESCRIPTION
**Pull request by tigrato**
This PR prevents a panic when the SSH request channel is closed by [`mux.loop`](https://github.com/gravitational/crypto/blob/c3f983bc73dcf711908e49d91bda9cffbecb13cd/ssh/mux.go#L197-L199) if it encounters a connection error.

Fixes #24186

### CODE REVIEW

**Review by rosstimothy — APPROVED** [review]

File: lib/sshutils/server.go [hunk 1]
```diff
@@ -565,6 +565,10 @@ func (s *Server) HandleConnection(conn net.Conn) {
 			for {
 				select {
 				case req := <-reqs:
+					if req == nil {
```
Comment (codingllama) [inline lib/sshutils/server.go:568]: Is a `nil` req something we expect to happen, or may we have bug somewhere else too?

(Definitely keep the change, I'm just curious on what prompted you to fix it.)

**Review by codingllama — APPROVED** [review]

**Review by AntonAM — APPROVED** [review]

File: lib/sshutils/server.go (hunk 1 above)
Comment (tigrato) [reply lib/sshutils/server.go:568]: I saw the panic during an integration test and went to investigate it.
The problem is caused [here](https://github.com/gravitational/crypto/blob/c3f983bc73dcf711908e49d91bda9cffbecb13cd/ssh/mux.go#L189-L191).
When an error is returned, the `loop` function closes the channels and the receiver receives a nil value and panics.

We also have another usage of the same channel outside of the error handling that does this check.
