### PR TITLE
Deflake discovery tests

### LINKED ISSUE #30387: `TestDiscoveryServer ` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5843481607/job/15845668364?pr=30385

#### Relevant snippet

```
=== FAIL: lib/srv/discovery TestDiscoveryServer/chunked_nodes_get_2_log_messages (1.58s)
    discovery_test.go:447: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/discovery/discovery_test.go:447
        	Error:      	Condition never satisfied
        	Test:       	TestDiscoveryServer/chunked_nodes_get_2_log_messages
```

### PR DESCRIPTION
**Pull request by atburke**
This PR deflakes some discovery server tests.

Fixes #30387.

### CODE REVIEW

File: lib/srv/discovery/discovery_test.go [hunk 1]
```diff
@@ -422,35 +413,20 @@ func TestDiscoveryServer(t *testing.T) {
...
-				case <-done:
-				}
-			}
-
-			if tc.wantEvents > 0 {
+			if len(tc.wantInstalledInstances) > 0 {
 				require.Eventually(t, func() bool {
-					return reporter.EventsCount() == tc.wantEvents
-				}, 100*time.Millisecond, 10*time.Millisecond)
+					require.ElementsMatch(t, tc.wantInstalledInstances, installer.GetInstalledInstances())
```
Comment (zmb3) [inline lib/srv/discovery/discovery_test.go:422]: We shouldn't use require inside an Eventually, as the predicate runs in a separate goroutine and require must only be called on the test's main goroutine

**Review by zmb3 — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
