### PR TITLE
(v6) Fix app access websockets support

### LINKED ISSUE #5264: Application Access does not support websockets
**What happened**: Trying to establish a websocket connection through AAP does not allow websockets to connect.

**What you expected to happen**: Websockets should work.

**How to reproduce it (as minimally and precisely as possible)**: Deploy something that requires websockets and proxy it through AAP. It will not work.

For my testing I used [Node-Red](https://nodered.org/docs/getting-started/docker). Deploy it in Docker using default port 1880. Set up AAP like so:

`/etc/teleport.yaml`:
```yaml
app_service:
  enabled: yes
  apps:
  - name: nodered
    public_addr: nodered.teleport.example.com
    uri: http://hades:1880
```

Connecting to https://nodered.teleport.example.com through a browser will load the UI, but websocket connections will fail. You can see this in Chrome dev tools:

Screenshot 2021-01-11 at 10 29 39

For contrast, here's the websocket traffic working correctly using Caddy:

Screenshot 2021-01-11 at 10 25 00

I can see no relevant logs outputted from Teleport during these attempted websocket connections, even at DEBUG level. Regardless, here is the full log section for the connection from start to finish:

```
Jan 11 10:31:41 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:41 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:41 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:41 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:41 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:41 hades teleport[436900]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
Jan 11 10:31:41 hades teleport[436900]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
Jan 11 10:31:41 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:41 hades teleport[436900]: DEBU [APP:SERVI] Using async streamer for session e62b9e05-1930-471e-964a-901cc4a9877c. app/session.go:169
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /, code: 304, duration: 3.836414ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/jquery/css/base/jquery-ui.min.css, code: 304, duration: 1.907483ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/style.min.css, code: 304, duration: 1.838274ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/font-awesome/css/font-awesome.min.css, code: 304, duration: 2.012946ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/vendor.js, code: 304, duration: 2.316669ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/main.min.js, code: 304, duration: 1.86439ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/red.min.js, code: 304, duration: 1.672763ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/purify.min.js.map, code: 404, duration: 3.858245ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/editor?lng=en-GB, code: 304, duration: 2.788147ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /theme, code: 304, duration: 1.550436ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/node-red?lng=en-GB, code: 304, duration: 2.432359ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/jsonata?lng=en-GB, code: 304, duration: 5.126189ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/editor?lng=en-US, code: 304, duration: 6.561891ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/node-red?lng=en-US, code: 304, duration: 2.726082ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/jsonata?lng=en-US, code: 304, duration: 4.077259ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/infotips?lng=en-GB, code: 304, duration: 5.5184ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/infotips?lng=en-US, code: 304, duration: 5.265811ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/node-red.svg, code: 304, duration: 2.286183ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /favicon.ico, code: 200, duration: 6.999832ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /settings?_=1610375502103, code: 200, duration: 1.081867ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /settings/user?_=1610375502104, code: 200, duration: 972.548µs tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/spin.svg, code: 304, duration: 3.144964ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/keymap.json, code: 304, duration: 3.607199ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-full-o.svg, code: 304, duration: 1.87505ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-full.svg, code: 304, duration: 1.681191ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-flows.svg, code: 304, duration: 1.955782ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/grip.png, code: 304, duration: 1.754156ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-reload.svg, code: 304, duration: 1.562247ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-nodes.svg, code: 304, duration: 1.619736ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0, code: 304, duration: 1.732088ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /nodes?_=1610375502105, code: 200, duration: 2.952736ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /nodes/messages?lng=en-GB&_=1610375502106, code: 200, duration: 3.240719ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /nodes/messages?lng=en-US&_=1610375502107, code: 200, duration: 3.845578ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons?_=1610375502108, code: 200, duration: 1.861736ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /nodes?_=1610375502109, code: 200, duration: 8.279227ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /debug/view/debug-utils.js, code: 304, duration: 3.007197ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/debug.svg, code: 304, duration: 2.500075ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/inject.svg, code: 304, duration: 2.110012ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/status.svg, code: 304, duration: 2.935912ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/alert.svg, code: 304, duration: 3.076684ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/link-out.svg, code: 304, duration: 2.517856ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/comment.svg, code: 304, duration: 2.356024ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /flows?_=1610375502110, code: 200, duration: 2.535374ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/trigger.svg, code: 304, duration: 2.47691ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/template.svg, code: 304, duration: 2.22044ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/timer.svg, code: 304, duration: 2.177253ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/cog.svg, code: 304, duration: 2.346898ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red-node-rbe/rbe.png, code: 304, duration: 2.286374ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/swap.svg, code: 304, duration: 3.936646ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/function.svg, code: 304, duration: 4.605236ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/range.svg, code: 304, duration: 4.697525ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/switch.svg, code: 304, duration: 2.371219ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/white-globe.svg, code: 304, duration: 3.221799ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/bridge.svg, code: 304, duration: 3.938426ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/subflow_tab.svg, code: 304, duration: 1.376884ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/bridge-dash.svg, code: 304, duration: 1.733373ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/split.svg, code: 304, duration: 1.532646ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/join.svg, code: 304, duration: 1.460828ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/sort.svg, code: 304, duration: 2.395725ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/batch.svg, code: 304, duration: 1.260347ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-csv.svg, code: 304, duration: 2.268534ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-json.svg, code: 304, duration: 3.996973ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-html.svg, code: 304, duration: 3.689769ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/file-out.svg, code: 304, duration: 1.917863ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-yaml.svg, code: 304, duration: 2.119178ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-xml.svg, code: 304, duration: 1.355629ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/file-in.svg, code: 304, duration: 2.569952ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/file.svg, code: 304, duration: 1.433782ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/watch.svg, code: 304, duration: 971.332µs tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
```

### Environment
- Teleport version (use `teleport version`): `Teleport v5.1.0 git:v5.1.0-0-g46679fb34 go1.15.5`
- OS (e.g. from `/etc/os-release`): `Fedora 32`

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Intel NUC

**Browser environment**

- Browser Version (for UI-related issues): `Google Chrome Version 87.0.4280.88 (Official Build) (arm64)`

### PR DESCRIPTION
**Pull request by r0mant**
Fixes https://github.com/gravitational/teleport/issues/5264.

### What

This pull request fixes websockets proxying through the application access.

I used the Node-RED application to test this according to the @webvictim's example in the ticket linked above. With these changes the websockets connection gets proxied correctly and the output in the inspector is consistent with the "working" screenshot from that ticket.

### How

The meat of the fix is in `lib/utils/fakeconn.go`. Websockets forwarding works by hijacking the raw connection from ResponseWriter and passing all traffic back/forth between the client/server:

https://github.com/gravitational/oxy/blob/1.0.4/forward/fwd.go#L270

```go
underlyingConn, _, err := hijacker.Hijack()
```

During investigation I found out that Hijack call is where it would hang indefinitely.

After further investigation, I found that before returning raw connection to the user during hijack, Go runtime tries to cancel all pending reads on the connection:

https://github.com/golang/go/blob/go1.15.10/src/net/http/server.go#L315

```go
c.r.abortPendingRead()
```

It does that by setting read deadline far in the past and waiting for pending reads to fail:

https://github.com/golang/go/blob/go1.15.10/src/net/http/server.go#L736

```go
cr.conn.rwc.SetReadDeadline(aLongTimeAgo)
```

The problem is that all connections coming out of reverse tunnel are wrapped in `utils.ChConn`:

https://github.com/gravitational/teleport/blob/master/lib/reversetunnel/transport.go#L301

```go
p.server.HandleConnection(utils.NewChConn(p.sconn, p.channel))
```

which doesn't implement deadlines:

https://github.com/gravitational/teleport/blob/master/lib/utils/fakeconn.go#L192-L196

```go
// SetReadDeadline sets a connection read deadline
// ignored for the channel connection
func (c *ChConn) SetReadDeadline(t time.Time) error {
	return nil
}
```

Thus, this PR introduces a `CancelableChConn` that extends `ChConn` with read deadlines support, based on the `net.Pipe`.

Note, I only used CancelableChConn for App Access servers to limit the scope and potential impact of the change. We could just update regular ChConn so it applies to all reverse tunnel connections but I opted to be on a safe side since this functionality is only required for websockets support through AAP.

There also were a couple of tweaks required here and there to have oxy/forward properly forward websockets.

### CODE REVIEW

File: lib/utils/fakeconn.go [hunk 1]
```diff
@@ -201,6 +198,64 @@ func (c *ChConn) SetWriteDeadline(t time.Time) error {
...
+		ChConn: NewChConn(conn, ch),
+		reader: reader,
+		writer: writer,
+	}
+	// Start copying from the SSH channel to the writer part of the pipe. The
+	// clients are reading from the reader part of the pipe (see Read below).
+	//
+	// This goroutine stops when either the SSH channel closes or this
+	// connection is closed e.g. by a http.Server (see Close below).
+	go io.Copy(writer, ch)
```
Comment (a-palchikov) [inline lib/utils/fakeconn.go:225]: nit: not sure if this goroutine races with `writer.Close` but I'd ensure that it exits before `CancelableChConn.Close` exits at least. On the bonus side, I'd ensure that it exits before the `writer` is closed,

File: lib/utils/fakeconn.go [hunk 2]
```diff
@@ -201,6 +198,64 @@ func (c *ChConn) SetWriteDeadline(t time.Time) error {
...
+}
+
+// Read reads from the channel.
+func (c *CancelableChConn) Read(data []byte) (int, error) {
+	return c.reader.Read(data)
+}
+
+// SetDeadline sets the channel connection read/write deadlines.
+func (c *CancelableChConn) SetDeadline(t time.Time) error {
+	return c.reader.SetDeadline(t)
```
Comment (a-palchikov) [inline lib/utils/fakeconn.go:236]: Which makes me wonder whether the original `ChConn` should return errors instead of `nil` for the APIs it does not implement - WDYT? Would be at least interesting to see whether it breaks anywhere in tests.

File: lib/utils/fakeconn.go [hunk 3]
```diff
@@ -201,6 +198,64 @@ func (c *ChConn) SetWriteDeadline(t time.Time) error {
...
+	if err := c.ChConn.Close(); err != nil {
+		errors = append(errors, err)
+	}
+	if err := c.reader.Close(); err != nil {
+		errors = append(errors, err)
+	}
+	if err := c.writer.Close(); err != nil {
+		errors = append(errors, err)
+	}
+	return trace.NewAggregate(errors...)
```
Comment (a-palchikov) [inline lib/utils/fakeconn.go:256]:
```go
return trace.NewAggregate(c.ChConn.Close(), c.reader.Close(), c.writer.Close())
```

File: lib/utils/fakeconn_test.go [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+		doneCh := make(chan error)
+		go func() {
+			// Nothing is sent on the channel so this will block until the
+			// read is canceled by the deadline set below.
+			_, err := ioutil.ReadAll(chConn)
+			doneCh <- err
+		}()
+		// Set the read deadline and make sure that the read above is
+		// canceled with a timeout error within a second.
+		chConn.SetReadDeadline(time.Now().Add(200 * time.Millisecond))
```
Comment (a-palchikov) [inline lib/utils/fakeconn_test.go:65]: Why not use the same approach with a deadline in the past to avoid waiting?

File: lib/web/app/transport.go [hunk 5]
```diff
@@ -156,6 +156,23 @@ func (t *transport) rewriteRequest(r *http.Request) error {
 	return nil
 }
 
+// websocketsDialer returns a function that dials a websocket connection
+// over the transport's reverse tunnel.
+func (t *transport) websocketsDialer() forward.Dialer {
+	return func(network, address string) (net.Conn, error) {
+		tr, ok := t.tr.(*http.Transport)
```
Comment (a-palchikov) [inline lib/web/app/transport.go:163]: hmm, why not save the TLS configuration in the transport so this is not necessary? Anything can trip over this if `t.tr` is ever an alternative implementation of `http.RoundTripper`

**Review by a-palchikov — APPROVED** [review]

File: lib/utils/fakeconn_test.go (hunk 4 above)
Comment (r0mant) [reply lib/utils/fakeconn_test.go:65]: Good idea.

File: lib/web/app/transport.go (hunk 5 above)
Comment (r0mant) [reply lib/web/app/transport.go:163]: Yeah, thought about it as well but for some reason decided to do without an additional field in transport. In hindsight, that'd probably be better, I'll update.

File: lib/utils/fakeconn.go (hunk 1 above)
Comment (r0mant) [reply lib/utils/fakeconn.go:225]: Yeah, I'm not sure there's necessarily a race - if any part of the connection (writer or ChConn) closes, the copy will just stop which isn't much different from just closing the connection during a read.

My primary concern with this was to avoid a goroutine leak which I think can't happen if any part of the connection closes (which it does). We could add a channel signaling that the copy has exited to be a bit paranoid though.

File: lib/utils/fakeconn.go (hunk 2 above)
Comment (r0mant) [reply lib/utils/fakeconn.go:236]: Yeah, I'm pretty sure things will break in mysterious ways :) A lot of Go runtime uses deadlines and will trip if we start returning errors. I'm actually more surprised that things seems to work ok without deadlines implemented on ChConn (well, besides this websockets issue).

File: lib/reversetunnel/transport.go [hunk 6]
```diff
@@ -297,8 +298,16 @@ func (p *transport) start() {
...
+			p.log.Debugf("Handing off connection to a local %q service.", dreq.ConnType)
+			switch dreq.ConnType {
+			case types.AppTunnel:
+				// Use channel connection wrapper that supports deadlines when
+				// proxying applications. This is required for websockets to
+				// work over Application Access.
+				p.server.HandleConnection(utils.NewCancelableChConn(p.sconn, p.channel))
+			default:
+				p.server.HandleConnection(utils.NewChConn(p.sconn, p.channel))
+			}
```
Comment (russjones) [inline lib/reversetunnel/transport.go:310]: Any reason why you separated these two and created `CancelableChConn` instead of just adding deadline support to `ChConn`?

File: lib/srv/app/transport.go [hunk 7]
```diff
@@ -280,3 +286,16 @@ func isRedirect(code int) bool {
...
+// Implements forward.ReqRewriter.
+type websocketsRewriter struct {
+	uri *url.URL
+}
+
+// Rewrite rewrites the websockets request.
+func (r *websocketsRewriter) Rewrite(req *http.Request) {
+	// Update host to the target app's host to make sure it's forwarded correctly.
+	req.URL.Host = r.uri.Host
+}
```
Comment (russjones) [inline lib/srv/app/transport.go:301]: This doesn't go through the round tripper?

File: lib/reversetunnel/transport.go (hunk 6 above)
Comment (r0mant) [reply lib/reversetunnel/transport.go:310]: @russjones No good reason other than out of abundance of caution. I can just update ChConn if you feel strongly about it, but I just felt that this functionality is only required for app access and wanted to avoid the risk of potentially introducing some side-effects to other types of services like ssh (and esp. since it's going to a minor release).

File: lib/srv/app/transport.go (hunk 7 above)
Comment (r0mant) [reply lib/srv/app/transport.go:301]: No, websockets use their own forwarder logic and a separate rewriter as well:

https://github.com/gravitational/oxy/blob/master/forward/fwd.go#L124-L128

File: lib/utils/fakeconn.go (hunk 3 above)
Comment (r0mant) [reply lib/utils/fakeconn.go:256]: I prefer the more verbose version in this case TBH.

File: lib/reversetunnel/transport.go (hunk 6 above)
Comment (russjones) [reply lib/reversetunnel/transport.go:310]: Makes sense for 6.1. What do you think updating `ChConn` on master to support deadlines but keeping them separate on `branch/v6`?

Comment (r0mant) [reply lib/reversetunnel/transport.go:310]: @russjones Yeah, that was one of my alternative ideas as well. We can do that. I'll rebase this PR off of `branch/v6` and open the one to master with just updated ChConn.

Comment (russjones) [reply lib/reversetunnel/transport.go:310]: Alright, looks good to me, merge it in after rebase off of `branch/v6`.

**Review by russjones — APPROVED** [review]
