### PR TITLE
Close leaky directClient

### LINKED ISSUE #6291: "remote error: tls: bad certificate" when connecting service through tunnel
### Description

**What happened**:

While going through the test plan, I was working on the scenario with connecting an application server to the cluster, and noticed the following error in the proxy logs printed over and over as soon as app server comes online:

```
ERRO [PROXY:SER] "proxy2021/04/01 15:42:46 http: TLS handshake error from 127.0.0.1:59409: remote error: tls: bad certificate\n" utils/cli.go:304
ERRO [PROXY:SER] "proxy2021/04/01 15:42:46 http: TLS handshake error from 127.0.0.1:59410: remote error: tls: bad certificate\n" utils/cli.go:304
```

The same error appears in proxy logs when connecting SSH node in IoT mode (over reverse tunnel) as well, and I presume that would be also true for database and K8s services as well. No errors are visible in the app server process logs.

After some investigations I think I tracked it down to dialing to the auth server through the tunnel:

https://github.com/gravitational/teleport/blob/branch/v6.0/lib/service/connect.go#L876

This code was updated in 6.0 to use the new API client which also does gRPC dial now. My theory is that since grpc.Dial is non-blocking by default, it keeps failing and retrying in the background producing this error on the proxy side. "remote error: tls: bad certificate" indicates that the connecting client can't validate the server's certificate which I think can be related to the fact that ServerName is set to the encoded cluster name (`xxx.teleport.cluster.local`) while the certificate presented by the proxy obviously doesn't have it among its SANs.

This error only appears in 6.0, it's not present in 5.0. Also, it's not clear what its implications are, everything seems to be working normally so it might be just a harmless side-effect leading to grpc client being effectively not connected when we're dialing internally, but we should fix it anyway.

**What you expected to happen**:

Not see the error in the logs.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Start auth/proxy process.
2. Start app server process (or SSH server connecting over reverse tunnel).
3. Observe the error in the proxy logs.

### Server Details
- Teleport version (run `teleport version`): 6.0 and later

### PR DESCRIPTION
**Pull request by Joerger**
Fixes #6291

### CODE REVIEW

File: lib/service/connect.go [hunk 1]
```diff
@@ -793,8 +793,8 @@ func (process *TeleportProcess) newClient(authServers []utils.NetAddr, identity
 	// Try and connect to the Auth Server. If the request fails, try and
 	// connect through a tunnel.
 	process.log.Debugf("Attempting to connect to Auth Server directly.")
-	_, err = directClient.GetLocalClusterName()
-	if err != nil {
+	if _, err = directClient.GetLocalClusterName(); err != nil {
+		directClient.Close()
```
Comment (r0mant) [inline lib/service/connect.go:797]: If this can return an error, I'd consider logging it

```go
if err := directClient.Close(); err != nil {
  process.log.WithError(err).Warn("Failed to close direct auth server client.")
}
```

**Review by r0mant — APPROVED** [review]
@Joerger Nice catch!

**Review by awly — APPROVED** [review]
