### PR TITLE
reduce sensitivity of fncache cancellation test

### LINKED ISSUE #14556: `TestFnCacheCancellation` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/1ddfaee7-0787-49ed-a3a6-0b236d5ba3f2?project=ci-account

#### Relevant snippet

```
=== CONT  TestFnCacheCancellation
    fncache_test.go:189: 
        	Error Trace:	fncache_test.go:189
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestFnCacheCancellation
{"caller":"utils/loadbalancer.go:272","component":"loadbalancer","dest":{"IP":"127.0.0.1","Port":34899,"Zone":""},"level":"debug","message":"forward","source":{"IP":"127.0.0.1","Port":43326,"Zone":""},"timestamp":"2022-07-16T01:01:59Z","trace.fields":{"listen":"127.0.0.1:0"}}
{"caller":"utils/loadbalancer.go:201","component":"loadbalancer","level":"debug","message":"created listening socket","timestamp":"2022-07-16T01:01:59Z","trace.fields":{"listen":"127.0.0.1:0"}}
--- FAIL: TestFnCacheCancellation (0.21s)
```

### PR DESCRIPTION
**Pull request by fspmarshall**
The `FnCacheCancellation` test was using a 10ms timeout for an operation that required waking a background goroutine and completing multiple channel operations in order to succeed.  Given the resource constraints of our CI env, I think this was probably optimistic, especially for a parallel test.  Also fixes an invocation of `t.Fatal` that was outside of the main test goroutine.

Closes https://github.com/gravitational/teleport/issues/14556

### CODE REVIEW

File: lib/utils/fncache_test.go [hunk 1]
```diff
@@ -178,14 +181,21 @@ func TestFnCacheCancellation(t *testing.T) {
...
+	loadFnWasRun := atomic.NewBool(false)
 	v, err = cache.Get(ctx, "key", func(context.Context) (interface{}, error) {
-		t.Fatal("this should never run!")
+		loadFnWasRun.Store(true)
 		return nil, nil
 	})
 
+	if loadFnWasRun.Load() {
+		t.Fatal("loadfn was run unexpectedly")
+	}
```
Comment (jakule) [inline lib/utils/fncache_test.go:197]: nit: 
```suggestion
	require.False(t, loadFnWasRun.Load(), "loadfn was run unexpectedly")
```

File: lib/utils/fncache_test.go [hunk 2]
```diff
@@ -178,14 +181,21 @@ func TestFnCacheCancellation(t *testing.T) {
...
 	defer cancel()
 
+	loadFnWasRun := atomic.NewBool(false)
 	v, err = cache.Get(ctx, "key", func(context.Context) (interface{}, error) {
-		t.Fatal("this should never run!")
+		loadFnWasRun.Store(true)
 		return nil, nil
 	})
 
+	if loadFnWasRun.Load() {
```
Comment (jakule) [inline lib/utils/fncache_test.go:195]: Checking the status here doesn't create the race condition? We check the condition, and the function above runs after?

File: lib/utils/fncache_test.go [hunk 3]
```diff
@@ -178,14 +181,21 @@ func TestFnCacheCancellation(t *testing.T) {
 	// unblock the loading operation which is still in progress
 	close(blocker)
 
-	ctx, cancel = context.WithTimeout(context.Background(), timeout)
+	// use long timeout since we need to wait for some concurrent operations to complete
+	// behind the scenes, and that can take a while in a resource-constrained environment.
+	ctx, cancel = context.WithTimeout(context.Background(), longTimeout)
 	defer cancel()
 
+	loadFnWasRun := atomic.NewBool(false)
```
Comment (jakule) [inline lib/utils/fncache_test.go:189]: I'm not 100% sure, but I think this will panic on a 32-bit arch. We've already had issues like that https://github.com/gravitational/teleport/pull/11822

Comment (zmb3) [reply lib/utils/fncache_test.go:189]: Can we just use stdlib atomic int64 for now? Next version of Go will have a built-in atomic bool.

Comment (jakule) [reply lib/utils/fncache_test.go:189]: > go.uber.org/atomic automatically handles alignment and protects from non-atomic access.

I don't think this is entirely true, ex: https://github.com/uber-go/atomic/issues/105
But I checked, and this use seems to work on the 32bit arch. I didn't realize that this is `uber` atomic, not `stdlib`.
I agree with @zmb3 that we should prefer stuff that is in the stdlib, but atomics is one of those things that so far causes us a lot of problems, and Go 1.19 is not available for us now.

@fspmarshall Do you know why did we decide to stop using Uber atomics?

Comment (fspmarshall) [reply lib/utils/fncache_test.go:189]: I'd consider the linked issue to be an abuse of the API rather than a failure of the library.  They are manually dereferencing the wrapper returned by `NewDuration()`, which breaks alignment.  IMO if you're dereferencing opaque types returned by concurrency libraries, you should expect some problems 😬 

> Do you know why did we decide to stop using Uber atomics?

If we stopped, I certainly wasn't aware of it.  I always encourage people to use it when I'm reviewing, and I use it in all the code I write 🤷 The team was a lot smaller [back then](https://github.com/gravitational/teleport/pull/3536#discussion_r406474964).  Probably just something that got lost along the way.

We do deliberately avoid it in the `api` package because we are a more aggressive about introducing external deps in there.

File: lib/utils/fncache_test.go (hunk 2 above)
Comment (fspmarshall) [reply lib/utils/fncache_test.go]: The previous call to `Get` returns for one of 3 cases:

- We loaded the already cached value (success).
- We hit the context timeout (failure, checked below).
- Load function was run to completion before the timeout was hit (failure, checked here).

So it would be racy if we didn't check for the timeout, but since we do its safe.

**Comment by zmb3** [comment]
@fspmarshall is there a way we can write a deterministic test to cover this cancellation logic rather than something that depends on time and just tweaking timeouts?

**Comment by fspmarshall** [comment]
@zmb3 Took another pass.  Wasn't able to remove timeouts, not sure if that's practical for this kind of test, but I was able to move all timeouts out of the happy path, which means I can use much larger timeouts without them affecting the runtime of the test when everything is working correctly.

**Review by jakule — APPROVED** [review]
Looks like this test is currently the top offender. I think it makes sense to merge this change and see what happens. If the timeouts are still a problem, we can revisit this topic.

File: lib/utils/fncache_test.go (hunk 3 above)
Comment (jakule) [reply lib/utils/fncache_test.go:192]: I think that we/I just lost the context. When I was looking at our code, I wasn't aware that we were using Uber atomics as most of the usage that I saw used the `std` library.

**Review by zmb3 — APPROVED** [review]

**Review by Tener — APPROVED** [review]
