### PR TITLE
Ansible Regressions

### LINKED ISSUE #849: SSH exec parsing issues
Ansible usage exposed issues in how Teleport parses bash commands. It does not support quotes properly.

@russjones you have the full context.

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

Two Ansible regressions exist:

1. When running a playbook, Ansible returns `bad widthPTY allocation request failed`. This is because Ansible requests a `0x0` terminal which Teleport considers invalid.
2. As covered in https://github.com/gravitational/teleport/issues/849, when running a playbook, Ansible returns an error that looks like:  `-p: 1: -p: Syntax error: Unterminated quoted string`. This is because Ansible runs a command that looks something like this `'/bin/sh -c "mkdir -p /tmp"'` and Teleport uses `strings.Split(" ")` instead of shell aware splitting.

**Implementation**

* The first issue, requesting a terminal of size `0x0`, is solved by returning a default sized terminal if an invalid size is requested.
* The second is fixed by using a shell aware splitting function. This way `'/bin/sh -c "mkdir -p /tmp"'` is split into `["/bin/sh", "-c", "mkdir -p /tmp"]` instead of `["/bin/sh", "-c", "mkdir", "-p", "/tmp"]`.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/849

### CODE REVIEW

File: lib/session/session.go [hunk 1]
```diff
@@ -384,21 +385,21 @@ func (s *server) UpdateSession(req UpdateRequest) error {
 // NewTerminalParamsFromUint32 returns new terminal parameters from uint32 width and height
 func NewTerminalParamsFromUint32(w uint32, h uint32) (*TerminalParams, error) {
```
Comment (klizhentas) [inline lib/session/session.go]: I don't think it's a job of this funciton to make a decision to set to default. I would keep it as is and will let caller to decide to resort to defaults, or create a separate functions with explicit semantics

**Review by klizhentas — COMMENTED** [review]
aside from my comment about the function semantics looks good

**Comment by russjones** [comment]
@klizhentas Made the changes you suggested, can you take another look?

**Review by klizhentas — APPROVED** [review]
