### PR TITLE
Fix event handler `types` filter when using bulk export API

### LINKED ISSUE #56099: Event Handler `types` filter should work with new  bulk export API
### Expected behavior:

Setting `types = "db.session.query"` in `teleport-event-handler.toml` should make the event handler export only that event type.

### Current behavior:

When using an event backend that supports the new bulk export API, both `types` and `skip-event-types` settings seem to be ignored.

These settings work correctly on a Teleport cluster that uses the legacy event watcher.

#### Teleport version

17.5.2

reported and reproduced with Teleport Cloud

#### Recreation steps

Follow any typical `teleport-event-handler` setup instructions. We were following https://goteleport.com/docs/admin-guides/management/export-audit-events/fluentd/ when we ran into this.

Add `types = "db.session.query"` to the config file. Observe every event type is sent to the FluentD endpoint, and not only `db.session.query`.

Adding `skip-session-types` to the config file also had no effect. Here's the first several lines of the TOML. It was originally generated with `teleport-event-handler configure ...` and the two options were manually added below the `batch = 20` line.

```toml
storage = "./storage"
timeout = "10s"
batch = 20
types = "db.session.query"
skip-session-types = "access_list.create,access_list.delete,access_list.member.create,access_list.member.delete,access_list.member.update,access_list.review,access_list.update,access_request.create,access_request.review,auth,bot.join,cert.create,db.session.query.failed,db.session.start,device.authenticate,device.enroll,exec,instance.join,join_token.create,kube.request,lock.created,lock.deleted,recovery_code.used,reset_password_token.create,saml.idp.auth,session.command,session.join,session.rejected,session.start,user.create,user.login,user.password_change,windows.desktop.session.end,windows.desktop.session.start"

[forward.fluentd]

```

#### Debug logs

N/A

### PR DESCRIPTION
**Pull request by kshi36**
Fixes #56099

<details><summary>Manual Tests</summary>
<p>

Test: `types` filter works correctly for clients using new bulk export API

- [x]  When connected to a storage backend supporting bulk export API (eg. Teleport Cloud, Athena backend), and setting `toml` configuration file with the following options:
    - [x]  Verify `types="user.login"` filter forwards only `user.login` events to fluentd audit events endpoint
    - [x]  Verify `skip-event-types="user.login"` filter skips forwarding `user.login` events to fluentd audit events endpoint
    - [x]  Verify `skip-session-types="db.session.query"` filter skips forwarding `db.session.query` events to fluentd session events endpoint
    - [x]  Verify options above yield same results using both `toml` config file and CLI arguments

</p>
</details> 

changelog: Fixed bug where event handler `types` filter is ignored for Teleport clients using Athena storage backend

### CODE REVIEW

File: integrations/event-handler/events_job.go [hunk 1]
```diff
@@ -264,14 +266,21 @@ func (j *EventsJob) runLegacyPolling(ctx context.Context) error {
 
 // handleEventV2 processes an event from the newer export API.
 func (j *EventsJob) handleEventV2(ctx context.Context, evt *auditlogpb.ExportEventUnstructured) error {
-
 	// filter out unwanted event types (in the v1 event export logic this was an internal behavior
 	// of the event processing helper since it would perform conversion prior to storing the event
 	// in its internal buffer).
+	if len(j.app.Config.Types) > 0 && !slices.Contains(j.app.Config.Types, evt.Event.Type) {
```
Comment (tigrato) [inline integrations/event-handler/events_job.go]: No need for the length check since the slice contains does exactly that check before. 
Should we create a map to avoid looping through config types?

Similar to skip events

Comment (kshi36) [reply integrations/event-handler/events_job.go]: My understanding was that if the types option was an empty slice, we would forward all event types (default behavior). Then `slices.Contains` would return false given the slice is empty, and the event type would be erroneously skipped.

I can change it into a map, although the length check will still be required

Comment (tigrato) [reply integrations/event-handler/events_job.go]: You are correct. I forgot about that

File: integrations/event-handler/events_job.go [hunk 2]
```diff
@@ -264,14 +266,21 @@ func (j *EventsJob) runLegacyPolling(ctx context.Context) error {
...
+		j.app.log.DebugContext(ctx, "Skipping event from types filter", "type", evt.Event.Type)
+		return nil
+	}
+
 	if _, ok := j.app.Config.SkipEventTypes[evt.Event.Type]; ok {
+		j.app.log.DebugContext(ctx, "Skipping event from skip-event-types filter", "type", evt.Event.Type)
 		return nil
 	}
 
+	j.app.log.DebugContext(ctx, "Not skipping event", "type", evt.Event.Type)
```
Comment (zmb3) [inline integrations/event-handler/events_job.go]: I'd remove this one. The event handler processes many thousands of events, we probably don't need to debug log the normal operation.

File: integrations/event-handler/events_job_test.go [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+			for _, event := range generateEvents {
+				exportEvent := &auditlogpb.ExportEventUnstructured{Event: event}
+
+				err := job.handleEventV2(t.Context(), exportEvent)
+				require.NoError(t, err)
+
+			}
+
+			require.NotRegexp(t, regexp.MustCompile("\"Event sent\".*type=role.created"), out.String())
+			require.Regexp(t, regexp.MustCompile("\"Event sent\".*type=join_token.create"), out.String())
```
Comment (zmb3) [inline integrations/event-handler/events_job_test.go]: Compile these regexes outside of the loop so you don't waste time recompiling them for each test case.

File: integrations/event-handler/README.md [hunk 4]
```diff
@@ -38,7 +38,6 @@ You may specify configuration options via command line arguments, environment va
 | skip-session-types        | Comma-separated list of session event types to skip                                                   | FDFWD_SKIP_SESSION_TYPES        |
 | start-time                | Minimum event time (RFC3339 format)                                                                   | FDFWD_START_TIME                |
 | timeout                   | Polling timeout                                                                                       | FDFWD_TIMEOUT                   |
-| cursor                    | Start cursor value                                                                                    | FDFWD_CURSOR                    |
```
Comment (zmb3) [inline integrations/event-handler/README.md:41]: Why was this removed?

File: integrations/event-handler/session_events_job.go [hunk 5]
```diff
@@ -357,6 +357,8 @@ Loop:
 
 			_, ok = j.app.Config.SkipSessionTypes[e.Type]
 			if !ok {
+				j.app.log.DebugContext(ctx, "Not skipping session event", "type", e.Type)
```
Comment (zmb3) [inline integrations/event-handler/session_events_job.go]: Similarly, I'd remove this one.

File: integrations/event-handler/teleport_event.go [hunk 6]
```diff
@@ -77,18 +77,18 @@ func NewTeleportEvent(e *auditlogpb.EventUnstructured) (*TeleportEvent, error) {
...
+		ID:    e.Id,
 		Type:  e.GetType(),
 		Time:  e.Time.AsTime(),
 		Index: e.GetIndex(),
-		ID:    e.Id,
-		Event: payload,
 	}
 
-	switch e.GetType() {
+	switch evt.Type {
```
Comment (zmb3) [inline integrations/event-handler/teleport_event.go:87]: Was this change necessary?

File: integrations/event-handler/events_job.go [hunk 7]
```diff
@@ -264,14 +266,21 @@ func (j *EventsJob) runLegacyPolling(ctx context.Context) error {
 
 // handleEventV2 processes an event from the newer export API.
 func (j *EventsJob) handleEventV2(ctx context.Context, evt *auditlogpb.ExportEventUnstructured) error {
-
 	// filter out unwanted event types (in the v1 event export logic this was an internal behavior
 	// of the event processing helper since it would perform conversion prior to storing the event
 	// in its internal buffer).
+	if len(j.app.Config.Types) > 0 && !slices.Contains(j.app.Config.Types, evt.Event.Type) {
+		j.app.log.DebugContext(ctx, "Skipping event from types filter", "type", evt.Event.Type)
```
Comment (r0mant) [inline integrations/event-handler/events_job.go]: To echo Zac's similar comments, I would consider removing all of these extra debug statements that are logged whenever an event is processed, whether it's skipped or not. They can still clog the logs if you e.g. choose to skip a frequent event.

**Review by r0mant — COMMENTED** [review]
Just a small comment in addition to what other people commented on already.

Good job figuring this out @kshi36!

File: integrations/event-handler/events_job.go (hunk 7 above)
Comment (hugoShaka) [reply integrations/event-handler/events_job.go]: I like the idea of logging a debug message when dropping an event. This can help troubleshoot issues like this one: https://github.com/gravitational/teleport/issues/61729.

For the config I agree that this is not especially useful as we usually have access to the config.

File: integrations/event-handler/README.md (hunk 4 above)
Comment (kshi36) [reply integrations/event-handler/README.md:41]: The cursor CLI option (and environment variable) do not seem to exist anymore

File: integrations/event-handler/teleport_event.go (hunk 6 above)
Comment (kshi36) [reply integrations/event-handler/teleport_event.go:87]: Wasn't necessary, although it matches how we are operating on the newly created event (hence removing the unused method fields as well)

Although if there is some other drawback or inconvenience I can revert it

**Review by tigrato — COMMENTED** [review]
I’m wondering whether we should do the same logic we do in SearchUnstructuredEvents. In that call, we pass the filter types directly to the auth server as a request parameter. Should we do the same here?
It would improve gRPC API throughput and avoid unnecessary unmarshalling and marshalling of events server side that we’ll ultimately discard anyway.

**Comment by kshi36** [comment]
> In that call, we pass the filter types directly to the auth server as a request parameter. Should we do the same here?

I will take a look into this.

**Comment by kshi36** [comment]
```
// ExportUnstructuredEvents exports events from a given event chunk returned by GetEventExportChunks. This API prioritizes
// performance over ordering and filtering, and is intended for bulk export of events.
ExportUnstructuredEvents(ctx context.Context, req *auditlogpb.ExportUnstructuredEventsRequest) stream.Stream[*auditlogpb.ExportEventUnstructured]
```
Based on the documentation on the usage of the bulk export API, it seems to favor not filtering types within `ExportUnstructuredEvents`. Shall we proceed with filtering types on the server-side after the API call?

**Comment by hugoShaka** [comment]
> Shall we proceed with filtering types on the server-side after the API call?

I think that your PR is fine. We do have some stretch goal this quarter to improve event export performance. But before spending more time improving the design for performance, we'll need to measure where we spend time, what is slow, and where we can reap gains.

Tiago is right and we can definitely improve the design here but if this provides a marginal 2% speedup in the general case (very likely as few events are usually filtered) while we could achieve a 30% speedup by fixing something else (and there's a lot to fix 🫠 ) this would not be a very efficient usage of our time.

**Review by r0mant — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
