### PR TITLE
Coordinate session ID with Node in Proxy recording mode

### LINKED ISSUE #42263: Duplicated SSH session recordings
Expected behavior:
Each SSH session should have exactly one recording and it should have the correct length.

Current behavior:
Each SSH session has two recordings with the same Session ID. Second recording is slightly longer and that length is incorrect - the recording ends before it reaches the displayed session duration (screenshot included below). The length of the shorter recording is correct (it matches actual session duration and actual recording length).

We tested tsh ssh on windows and Teleport WebUI, bug occurs in both situations.

Sessions list

The longer recording ends in the middle (that's when the session actually ended).
Longer recording

Bug details:
- Teleport version: First noticed by us in 15.3.7, still present in 15.4.0.
- Session recording mode: proxy

### PR DESCRIPTION
**Pull request by Joerger**
Changelog: Fix a bug in Proxy recording mode where Teleport Node sessions would result in duplicate audit events with a different session ID.

### Details

<details>
<summary>Overview</summary>

When Proxy recording mode is enabled, Teleport Node sessions consist of two actual SSH server sessions - one in an ephemeral Proxy Forwarding Node, and one on the Teleport Node. Currently, these two sessions are handled separately and mistakenly share the same responsibilities, resulting in duplicate audit events and session trackers with mismatched session IDs.

This PR introduces two primary changes to fix the above issue:
- Coordinate the session ID between the Teleport Node and the Proxy Forwarding Node sessions.
- Properly delegate session recording responsibilities to the forwarding Node:
  - recording the session
  - emitting audit events
  - creating the session tracker backend resource
- Add "session-id-query-v2@goteleport.com" global server request. See the flow and backwards compatibility sections below for details.

</details>

<details>
<summary>Session ID coordination flow</summary>

In v17+ servers, the current session ID is sent to the client after a session is started. However, a session is not "started" until the shell/exec request is handled. By this time, the Forwarding Node has already created its own session with a unique ID and made decisions about whether to create a session tracker, emit events, etc.

```mermaid
sequenceDiagram
  participant Client
  participant Proxy
  participant Forwarding Node
  participant Teleport Node

  Client ->> Proxy: ssh Dial
  Proxy ->> Forwarding Node: Create new ephemeral Forwarding Node and forward connection
  Client ->> Forwarding Node: ssh "session" channel request
  Forwarding Node ->> Teleport Node: ssh "session" channel request
  Teleport Node ->> Forwarding Node: Accept session channel
  Forwarding Node ->> Client: Accept session channel
  Client ->> Forwarding Node: ssh "shell" channel request
  Note over Forwarding Node: Start session (set ID, create tracker, start recorder, emit events)
  Forwarding Node ->> Client: send "current-session-id@goteleport.com"
  Forwarding Node ->> Teleport Node: ssh "shell" channel request
  Note over Teleport Node: Start session (set ID, create tracker, start terminal, emit events)
  Teleport Node ->> Forwarding Node: send "current-session-id@goteleport.com"
  Client <<->> Teleport Node: Forwarded shell session success
```

In the new flow, the session ID is set and sent to the client as soon as the "session" channel is handled. This allows the Forwarding Node to save the session ID and use it when the session is started. Now that the session ID is shared by both server sessions, session responsibilities are properly delegated without any mismatches or duplicates.

Note that in the new flow, the Forwarding Node does not accept the session channel until it receives the current session ID from the Teleport Node. In order to determine whether the session ID will be sent, the Forwarding Node must determine whether the current session ID will actually be sent.  only waits for the session ID to be sent if it receives a reply with the `session-id-query-v2@goteleport.com` request.

```mermaid
sequenceDiagram
  participant Client
  participant Proxy
  participant Forwarding Node
  participant Teleport Node

  Client ->> Proxy: ssh Dial
  Proxy ->> Forwarding Node: Create new ephemeral Forwarding Node and forward connection
  Client ->> Forwarding Node: ssh "session" channel request
  Forwarding Node ->> Teleport Node: ssh "session" channel request
  Teleport Node ->> Forwarding Node: Accept session channel and set session ID
  Forwarding Node ->> Teleport Node: send "session-id-query-v2@goteleport.com" request
  Note over Forwarding Node: If the above query returns true, wait for the current session ID. Otherwise, set new session ID
  Teleport Node ->> Forwarding Node: send "current-session-id@goteleport.com"
  Forwarding Node ->> Client: Accept session channel
  Forwarding Node ->> Client: send "current-session-id@goteleport.com"
  Client ->> Forwarding Node: ssh "shell" channel request
  Note over Forwarding Node: Start session (start terminal, start recorder, emit events)
  Forwarding Node ->> Teleport Node: ssh "shell" channel request
  Note over Teleport Node: Start session (create tracker, start terminal)
  Client <<->> Teleport Node: Forwarded shell session success
```

</details>

<details>
<summary>Backwards Compatibility</summary>

This change is backwards compatible in the sense that if either the Node or Proxy is outdated, every session responsibility will still be delegated to at least one of the two services. However, the outdated component may still result in duplicate and mismatched audit events and session trackers:
- An outdated Node will not send the session ID in time for the Forwarding Node to use it. As a result, the Proxy will create its own session ID and its own session tracker. The node will continue to emit audit events with the mismatched session ID.
- An outdated Proxy will not use the session ID sent by the Teleport Node. It will also continue to create a session tracker, resulting in a duplicate session tracker that doesn't match the Teleport Node session ID. However, only the proxy will emit audit events and these events will match the session ID of the session recording.

To enable the above, this PR introduces the "session-id-query-v2@goteleport.com" global server request. The Forwarding Node sends this request to determine whether it should wait for the Teleport Node to send the current session ID. If the Teleport Node does not reply to this request (old Teleport Node), the Forwarding Node will continue with its own session ID like it does currently.

Note that the original "session-id-query@goteleport.com" has been marked for deletion in v20, and "session-id-query-v2@goteleport.com" is marked for deletion in v21. If extended backwards compatibility is a concern (> 1 major version), servers can continue to reply for an additional major version or even though no v19+/v20+ client (respectively) will send the query.

</details>

<details>
<summary>Manual Tests</summary>

Last run: (292d06481de838ddb075090e413fa27b71a7db09)
- [x] Proxy recording mode:
  - [x] Teleport Node
    - [x] Start a session and use `teleport status` to get the session ID. it should appear in the session list (e.g. `tsh session ls`).
    - [x] End the session. Observe session `start`, `end`, `data`, and `leave` events are emitted with the same session ID.
      - [x] No duplicate events
      - [x] these events should have the `forwarded_by` and `recording_mode: proxy` fields.
  - [x] Agentless Node
     - [x] Start a session and use `teleport status` to get the session ID. it should appear in the session list (e.g. `tsh session ls`).
    - [x] End the session. Observe session `start`, `end`, `data`,  and `leave` events are emitted with the same session ID.
      - [x] these events should have the `forwarded_by` and `recording_mode: proxy` fields.
- [x] Node recording mode:
  - [x] Teleport Node
    - [x] Start a session and use `teleport status` to get the session ID. it should appear in the session list (e.g. `tsh session ls`).
    - [x] End the session. Observe session `start`, `end`, `data`, , and `leave` events are emitted with the same session ID.
      - [x] these events should **not** have the `forwarded_by` and `recording_mode: proxy` fields.
  - [x] Agentless Node
     - [x] Start a session and use `teleport status` to get the session ID. it should appear in the session list (e.g. `tsh session ls`).
    - [x] End the session. Observe session `start`, `end`, `data`, and `leave` events are emitted with the same session ID.
      - [x] these events should have the `forwarded_by` and `recording_mode: proxy` fields.

Backwards compatibility:
| Proxy | Node | Mismatched ID w/ tracker | Duplicate events |  ✅  |
|------|-------|------|------|-------|
| new | new | no | no  | ✅ |
| new | old  | no | yes | ✅ |
| old  | new | yes | no  | ✅ |
| old  | old   | yes | yes | ✅ |

</details>

Depends on https://github.com/gravitational/teleport/pull/59206

Fixes https://github.com/gravitational/teleport/issues/42263, https://github.com/gravitational/teleport/issues/20063

### CODE REVIEW

File: lib/srv/forward/sshserver.go [hunk 1]
```diff
@@ -1150,6 +1167,46 @@ func (s *Server) handleSessionChannel(ctx context.Context, nch ssh.NewChannel) {
...
+		}
+
+		if !willReceiveSID {
+			s.logger.WarnContext(ctx, "Failed to query session ID from target node. Ensure the targeted Teleport Node is upgraded to v19.0.0+ to avoid duplicate events due to mismatched session IDs.")
+		}
+	}
+
+	// Register handler to receive the current session ID before starting the session.
+	newSessionID := make(chan session.ID, 1)
+	if willReceiveSID {
```
Comment (rosstimothy) [inline lib/srv/forward/sshserver.go]: I'm finding the multiple if statements for `willReceiveSID` a bit hard to follow, especially since the variable is updated within one of the branches here.

File: lib/srv/ctx.go [hunk 2]
```diff
@@ -319,6 +320,18 @@ type ServerContext struct {
 	// sessionParams are parameters associated with this server session.
 	sessionParams *tracessh.SessionParams
 
+	// newSessionID is set if this server context is going to create a new session.
+	// This field must be set through [ServerContext.SetNewSessionID] for non-join
+	// sessions before as soon as a session channel is accepted in order to inform
```
Comment (rosstimothy) [inline lib/srv/ctx.go]:
```suggestion
	// sessions as soon as a session channel is accepted in order to inform
```

File: lib/srv/ctx.go [hunk 3]
```diff
@@ -879,8 +917,7 @@ func (c *ServerContext) reportStats(conn utils.Stater) {
 	// sessions are being recorded at the proxy (this would result in double
 	// events).
 	// Do not emit session data for git commands as they have their own events.
-	if c.GetServer().Component() == teleport.ComponentProxy ||
-		c.GetServer().Component() == teleport.ComponentForwardingGit {
+	if c.GetServer().Component() == teleport.ComponentForwardingGit {
```
Comment (rosstimothy) [inline lib/srv/ctx.go]: The comment and the code no longer appear in sync here, unless the first half of the comment is now referencing the if statement below. If that is the case perhaps we should split the comment here and below?

File: lib/srv/sess.go [hunk 4]
```diff
@@ -824,11 +824,19 @@ func newSession(ctx context.Context, r *SessionRegistry, scx *ServerContext, ch
 		return nil, nil, trace.BadParameter("session creation only supported in context of ssh access or proxying permit")
 	}
 
+	sid := scx.GetNewSessionID(ctx)
+	if sid == "" {
+		// Some flows (particularly tests) do not set the session ID ahead of time.
+		sid = rsession.NewID()
+		scx.SetNewSessionID(ctx, sid, ch)
+		r.logger.WarnContext(ctx, "newSessionID should be set prior to session creation. If this log is seen outside of tests, this is a bug.")
+	}
```
Comment (rosstimothy) [inline lib/srv/sess.go]: Should we fix all tests instead of logging here and moving on?

File: lib/srv/sess.go [hunk 5]
```diff
@@ -2381,12 +2389,12 @@ func (s *session) trackSession(ctx context.Context, teleportUser string, policyS
...
+	// - This is a proxy forwarding server for a Teleport Node (tracking is handled by the target node server)
+	// - this is a non-interactive session
+	// - the session was initiated by a bot
 	svc := s.registry.SessionTrackerService
-	// Only propagate the session tracker when the recording mode and component are in sync
-	// AND the sesssion is interactive
-	// AND the session was not initiated by a bot
-	if (s.registry.Srv.Component() == teleport.ComponentNode && services.IsRecordAtProxy(s.scx.SessionRecordingConfig.GetMode())) ||
-		(s.registry.Srv.Component() == teleport.ComponentProxy && !services.IsRecordAtProxy(s.scx.SessionRecordingConfig.GetMode())) ||
+	if (s.registry.Srv.Component() == teleport.ComponentForwardingNode && !s.registry.Srv.GetInfo().IsOpenSSHNode() && !s.scx.proxyShouldCreateSessionTracker) ||
```
Comment (rosstimothy) [inline lib/srv/sess.go]: In what cases would an agentless connection _not_ be proxied by a `teleport.ComponentForwardingNode` instance?

File: lib/srv/ctx.go (hunk 3 above)
Comment (Joerger) [reply lib/srv/ctx.go]: This was a mistake on my part. I thought we would never have the Proxy component here, only the forwarding node component. I see now that subsystem requests do actually expect the proxy component in the regular ssh server. Thanks for catching this, I should have dug a bit deeper.

File: lib/srv/sess.go (hunk 5 above)
Comment (Joerger) [reply lib/srv/sess.go]: I don't believe there is one, did I miss something? This conditional will ensure the forwarding node always tracks the session for the agentless node.

File: lib/srv/forward/sshserver.go (hunk 1 above)
Comment (Joerger) [reply lib/srv/forward/sshserver.go]: Is this better? - 788d87b8972a2e4d844812da0fc323bb2bae0952

**Review by rosstimothy — COMMENTED** [review]
Are the changes introduced in this PR causing the integration test failures?

```
2025-10-10T00:07:19.3723034Z {"timestamp":"2025-10-09T23:57:48Z","level":"warning","caller":"forward/sshserver.go:1208","message":"Failed to query session ID from target node. Ensure the targeted Teleport Node is upgraded to v19.0.0+ to avoid duplicate events due to mismatched session IDs.","component":"node:forward","src_addr":"127.0.0.1:40788","dst_addr":"127.0.0.1:40529"}
2025-10-10T00:07:19.3723581Z {"timestamp":"2025-10-09T23:57:48Z","level":"warning","caller":"forward/sshserver.go:1218","message":"Remote session open failed","component":"node:forward","src_addr":"127.0.0.1:40788","dst_addr":"127.0.0.1:40529","error":"EOF"}
2025-10-10T00:07:19.3725697Z {"timestamp":"2025-10-09T23:57:48Z","level":"info","caller":"events/emitter.go:287","message":"emitting audit event","event_type":"session.data","fields":{"addr.local":"127.0.0.1:40529","addr.remote":"127.0.0.1:40788","code":"T2006I","ei":2147483646,"event":"session.data","forwarded_by":"00000000-0000-0000-0000-000000000000","login":"ci","namespace":"default","private_key_policy":"none","rx":3722,"server_addr":"127.0.0.1:40529","server_hostname":"e77bb0694b97","server_id":"00000000-0000-0000-0000-000000000000","server_sub_kind":"teleport","server_version":"19.0.0-dev","sid":"","time":"2025-10-09T23:57:48.583Z","trace.component":"audit","tx":4240,"uid":"6c7225c6-8514-4d16-878c-380857132eaa","user":"ci","user_cluster_name":"local-site","user_kind":1,"user_roles":["devs"],"user_traits":{"testing":["integration"]}}}
2025-10-10T00:07:19.3726448Z {"timestamp":"2025-10-09T23:57:48Z","level":"debug","caller":"forward/sshserver.go:863","message":"Closing forwarding server connection and releasing resources","component":"node:forward","src_addr":"127.0.0.1:40788","dst_addr":"127.0.0.1:40529","server_addr":"127.0.0.1:40529"}
2025-10-10T00:07:19.3726532Z     integration_test.go:2190: 
2025-10-10T00:07:19.3726714Z         	Error Trace:	/__w/teleport/teleport/integration/integration_test.go:2190
2025-10-10T00:07:19.3726869Z         	            				/__w/teleport/teleport/integration/integration_test.go:2072
2025-10-10T00:07:19.3726943Z         	Error:      	Async error
2025-10-10T00:07:19.3727197Z         	Test:       	TestIntegrations/Disconnection/concurrent_connection_limits_exceeded_proxy_recording
2025-10-10T00:07:19.3727570Z         	Messages:   	Expected error to contain "administratively prohibited", got: ssh: rejected: connect failed (remote session open failed: EOF)
```

File: lib/srv/forward/sshserver.go [hunk 6]
```diff
@@ -1150,6 +1167,45 @@ func (s *Server) handleSessionChannel(ctx context.Context, nch ssh.NewChannel) {
...
+				// Only handle the first request - only one is expected.
+				receiveSessionIDOnce.Do(func() {
+					sid, err := session.ParseID(string(req.Payload))
+					if err != nil {
+						s.logger.WarnContext(ctx, "Unable to parse session ID", "error", err)
+						return
+					}
+
+					newSessionIDFromServer <- *sid
+					close(newSessionIDFromServer)
```
Comment (rosstimothy) [inline lib/srv/forward/sshserver.go]: > Note that it is only necessary to close a channel if the receiver is looking for a close. Closing the channel is a control signal on the channel indicating that no more data follows.

https://groups.google.com/g/golang-nuts/c/pZwdYRGxCIk/m/qpbHxRRPJdUJ

```suggestion
```

**Comment by Joerger** [comment]
> Are the changes introduced in this PR causing the integration test failures?

Yeah, it turned out to be a pretty obscure issue related to https://github.com/gravitational/teleport/pull/18658, since we now send the `session-id-query-v2@goteleport.com` global request before the session channel request for proxy forwarded sessions. We'll see whether that fixes all of the test failures or just one.

**Comment by rosstimothy** [comment]
> Yeah, it turned out to be a pretty obscure issue related to #18658, since we now send the `session-id-query-v2@goteleport.com` global request before the session channel request for proxy forwarded sessions. We'll see whether that fixes all of the test failures or just one.

It looks like multiple tests are still failing.

**Comment by Joerger** [comment]
> > Yeah, it turned out to be a pretty obscure issue related to #18658, since we now send the `session-id-query-v2@goteleport.com` global request before the session channel request for proxy forwarded sessions. We'll see whether that fixes all of the test failures or just one.
> 
> It looks like multiple tests are still failing.

Yes, there is some changes to leaf cluster behavior, working on tweaking the behavior / tests and then I'll update the comment description and request re-review.

**Comment by Joerger** [comment]
@rosstimothy @nklaassen @marcoandredinis Sorry for letting this one go stale, but all the tests are _finally_ passing. I ended up not making changes to leaf clusters and instead prioritizing existing behavior.

File: lib/srv/ctx.go [hunk 7]
```diff
@@ -922,6 +944,15 @@ func (c *ServerContext) reportStats(conn *utils.TrackingConn) {
 	serverRX.Add(float64(rxBytes))
 }
 
+// shouldHandleRecording returns whether this server context is responsible for
```
Comment (rosstimothy) [inline lib/srv/ctx.go]:
```suggestion
// ShouldHandleRecording returns whether this server context is responsible for
```

**Review by rosstimothy — APPROVED** [review]

**Comment by Joerger** [comment]
@nklaassen @marcoandredinis Friendly ping to review

edit: I am investigating the integration test flake but I don't expect it'll require any big changes.

File: lib/srv/forward/sshserver.go [hunk 8]
```diff
@@ -1182,9 +1265,18 @@ func (s *Server) handleSessionChannel(ctx context.Context, nch ssh.NewChannel) {
 		return
 	}
 	scx.AddCloser(ch)
-
 	ch = scx.TrackActivity(ch)
 
+	// inform the client of the session ID that is going to be used in a new
+	// goroutine to reduce latency.
+	go func() {
+		s.logger.DebugContext(ctx, "Sending current session ID")
```
Comment (marcoandredinis) [inline lib/srv/forward/sshserver.go]: Should we also add the session id to both logs or the node id?

File: lib/srv/forward/sshserver.go [hunk 9]
```diff
@@ -1153,6 +1170,53 @@ func (s *Server) handleSessionChannel(ctx context.Context, nch ssh.NewChannel) {
...
+			// presumably due to an authz error, and the server is trying to communicate the error with the first
+			// req/chan received.
+			s.logger.WarnContext(ctx, "Remote session open failed", "error", err)
+			if err := nch.Reject(ssh.Prohibited, fmt.Sprintf("remote session open failed: %v", string(payload))); err != nil {
+				s.logger.WarnContext(ctx, "Failed to reject channel", "channel", nch.ChannelType(), "error", err)
+			}
+			return
+		}
+
+		if reply {
```
Comment (marcoandredinis) [inline lib/srv/forward/sshserver.go]: At this point `err` might be non-nil, and we still decide the flow based on the `reply`.

Usually, using other returned fields when `err` is non-nil is considered dangerous, because by convention, when a function returns an error, we should not consider the other other returned fields.

If this is safe, can at least add a comment explaining?

File: lib/srv/forward/sshserver.go [hunk 10]
```diff
@@ -1153,6 +1170,53 @@ func (s *Server) handleSessionChannel(ctx context.Context, nch ssh.NewChannel) {
...
+			newSessionIDFromServer = make(chan session.ID, 1)
+			var receiveSessionIDOnce sync.Once
+			s.remoteClient.HandleSessionRequest(ctx, teleport.CurrentSessionIDRequest, func(ctx context.Context, req *ssh.Request) {
+				// Only handle the first request - only one is expected.
+				receiveSessionIDOnce.Do(func() {
+					sid, err := session.ParseID(string(req.Payload))
+					if err != nil {
+						s.logger.WarnContext(ctx, "Unable to parse session ID", "error", err)
+						return
```
Comment (marcoandredinis) [inline lib/srv/forward/sshserver.go]: If this happens, we will still wait (a little less than) 10 seconds.
Should we close the channel and consider this in the receiving end?

File: lib/srv/forward/sshserver.go [hunk 11]
```diff
@@ -1172,6 +1236,25 @@ func (s *Server) handleSessionChannel(ctx context.Context, nch ssh.NewChannel) {
...
+		select {
+		case sid := <-newSessionIDFromServer:
+			scx.SetNewSessionID(ctx, sid)
+		case <-time.After(10 * time.Second):
+			s.logger.WarnContext(ctx, "Failed to receive session ID from target node. Ensure the targeted Teleport Node is upgraded to v19.0.0+ to avoid duplicate events due to mismatched session IDs.")
+			if err := nch.Reject(ssh.ConnectionFailed, "target Teleport Node failed to report session ID"); err != nil {
+				s.logger.WarnContext(ctx, "Failed to reject channel", "channel", nch.ChannelType(), "error", err)
+			}
+			return
+		}
```
Comment (marcoandredinis) [inline lib/srv/forward/sshserver.go:1257]: We are not checking for context cancellation. Should we?

**Review by marcoandredinis — COMMENTED** [review]
I did a small test and it seems to work fine.
Running with `master`, it generated two `Session Ended` events, but with your branch, it only generated one.

Image

**Review by marcoandredinis — APPROVED** [review]
