### PR TITLE
fix reverse tunnel cannot connect if proxy address contains https

### LINKED ISSUE #24796: `public_addr` can no longer specify protocol
Expected behavior:

Prior to https://github.com/gravitational/teleport/pull/23866 this used to work:

```
proxy_service:
  enabled: "true"
  public_addr:  ['https://teleport.example.com']
```

Now this needs to be:

```
proxy_service:
  enabled: "true"
  public_addr:  ['teleport.example.com']
```

Current behavior:

If `https` is part of the `public_addr`, these errors will be spammed:

```
2023-04-19T12:35:01+02:00 DEBU [PROXY:AGE] Failed to dial boson.tener.io:3080. error:[
ERROR REPORT:
Original Error: *net.OpError dial https: unknown network https
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/alpn.go:139 github.com/gravitational/teleport/api/client.(*ALPNDialer).DialContext
	github.com/gravitational/teleport/lib/utils/proxy/proxy.go:102 github.com/gravitational/teleport/lib/utils/proxy.directDial.DialTimeout
	github.com/gravitational/teleport/lib/reversetunnel/agent_dialer.go:52 github.com/gravitational/teleport/lib/reversetunnel.(*agentDialer).DialContext
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:364 github.com/gravitational/teleport/lib/reversetunnel.(*agent).connect
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:319 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:314 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).connectAgent
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:273 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).run
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:257 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).Start.func1
```

Notes:

I'm not sure why I put `https://` in my test configuration, as all the docs for `public_addr` do not mention the protocol at all. That being said, it *used* to work, even if by accident, and no longer does.

Version: `Teleport v13.0.0-alpha.1 git:v13.0.0-alpha.1-0-gf9b7326 go1.20.3`

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #24796 

Related change:
https://github.com/gravitational/teleport/pull/23866

Prior to the above change, TLS routing dialer was forcing "tcp" network when "https" is passed in:
https://github.com/gravitational/teleport/blob/eec5803ed6ac25cbd6d967e9840171c96e728839/lib/utils/proxy/proxy.go#L154

Instead re-applying the same forcing-network-tcp fix, this change tries to make sure "tcp" is passed in.

### CODE REVIEW

File: lib/service/service.go [hunk 1]
```diff
@@ -5175,6 +5175,12 @@ func (process *TeleportProcess) SingleProcessModeResolver(mode types.ProxyListen
 		if !ok {
 			return nil, mode, trace.BadParameter(`failed to find reverse tunnel address, if running in single process mode, make sure "auth_service", "proxy_service", and "app_service" are all enabled`)
 		}
+
+		// In case the web address has "https" scheme for TLS Routing, make
+		// sure "tcp" is used when dialing reverse tunnel.
+		if mode == types.ProxyListenerMode_Multiplex && addr.AddrNetwork == "https" {
+			addr.AddrNetwork = "tcp"
+		}
```
Comment (smallinsky) [inline lib/service/service.go:5183]: Can we move this  logic to `process.singleProcessMode(mode)` where we already doing the `mode == types.ProxyListenerMode_Multiplex` check ?

**Review by smallinsky — APPROVED** [review]

**Review by Tener — APPROVED** [review]

**Comment by Tener** [comment]
@greedy52 should we backport this to v13?
