### PR TITLE
Fix `known_hosts` locking by refactoring our locks in `utils/fs`

### LINKED ISSUE #16217: Replace usage of file locks in `utils/fs_*` with `flock`
We introduced file locking library `flock` in https://github.com/gravitational/teleport/pull/16057 . It superseeds our own fs utils for locking (found in `utils/fs_unix.go` and stub for windows in `utils/fs_windows.go`), since it supports not just nix, but also windows.
Our own util is only used in one place, we should remove it and use `flock` consistently instead.

### PR DESCRIPTION
**Pull request by AntonAM**
Turned out linux/mac and windows versions of `flock` work differently - on windows it's impossible to read/write file after locking, and `tsh` failed to read `known_hosts` file after locking on it.
To fix it we refactor file locks in `utils/fs` to take advantage of the split os approach - on non windows it will be working with just locking on target file as `known_hosts` currently works, but on windows we'll be creating .lock file. We still get benefits of automatic unlocking if something bad happens and process dies without explicitly unlocking the file, so we don't have to worry about handling leftover lockfiles. We also remove .lock file on unlock.

Related to #16057 and #15298
Fixes #16217

### CODE REVIEW

File: lib/client/keystore.go [hunk 1]
```diff
@@ -582,10 +582,10 @@ func (fs *fsLocalNonSessionKeyStore) kubeCertPath(idx KeyIndex, kubename string)
 	return keypaths.KubeCertPath(fs.KeyDir, idx.ProxyHost, idx.Username, idx.ClusterName, kubename)
 }
 
-// acquireFileLock is trying to lock the file, until it's successful or timeout is exceeded.
-// File will be created if it doesn't exist.
+// acquireFileLock is trying to acquire lock, until it's successful or timeout is exceeded.
+// Lock file for the path will be created if it doesn't exist.
 func acquireFileLock(filePath string, timeout time.Duration) (func() error, error) {
-	fileLock := flock.New(filePath)
+	fileLock := flock.New(filePath + ".lock")
```
Comment (r0mant) [inline lib/client/keystore.go:588]: Do we want to lock it "properly" on Unix systems (i.e. lock the actual file) and have a different implementation for Windows? The benefit would be that the file would be protected by external modifications also (on Unix systems at least).

Comment (AntonAM) [reply lib/client/keystore.go:588]: It doesn't really provide protection from external modification for *nix, because it's advisory locking. It works only as long as process is cooperating, but some non-cooperating process can still modify the file. Essentially it's like a mutex - as long as code tries to lock first, everything's good, but nothing really stops direct modification of protected variable :)
But fortunately I don't think we'll have a problem here, since only we are writing to `known_hosts`.

Comment (r0mant) [reply lib/client/keystore.go:588]: Will this approach leave .lock files behind? Might be confusing unless .lock file is also deleted when the lock is released.

Comment (AntonAM) [reply lib/client/keystore.go:588]: Yes, currently .lock files are left behind, because their presence doesn't matter to the actual locking. But I can add removal on unlocking for regular operations. It will be left over in case process dies unexpectedly, but as I said before, it will not matter and it will be just deleted on next unlocking.

Comment (r0mant) [reply lib/client/keystore.go:588]: Having a .lock file always present may be confusing for users, I think it would be preferable if we didn't leave it behind.

File: lib/utils/fs_windows.go [hunk 2]
```diff
@@ -21,26 +21,22 @@ limitations under the License.
...
-}
-
-// FSUnlock not supported on Windows.
-func FSUnlock(f *os.File) error {
-	return trace.BadParameter("file locking not supported on Windows")
+// On Windows we use auxiliary .lock files to acquire locks, so we can still read/write target files
+// themselves. On unlock we delete the .lock file.
+const lockPostfix = ".lock"
+
+var unlockWrapper = func(unlockFn func() error, path string) func() error {
```
Comment (tigrato) [inline lib/utils/fs_windows.go:30]: why is this an assigned var?
You can just declare it as a normal function

File: lib/client/keystore.go (hunk 1 above)
Comment (AntonAM) [reply lib/client/keystore.go]: Refactored `utils/fs` as we discussed.

**Review by r0mant — COMMENTED** [review]
@AntonAM I'll let @tigrato and @timothyb89 to review the code but before we merge this, let's please test the following `tsh login` scenarios on both Linux (or Mac) and Windows to make sure nothing else breaks:

- [ ] Simple login with local user.
- [ ] Login with SSO (e.g. Github or Okta SAML connector).
- [ ] Login with MFA (e.g. TouchID).

File: lib/utils/fs.go [hunk 3]
```diff
@@ -144,3 +153,59 @@ func StatDir(path string) (os.FileInfo, error) {
...
+		return nil, trace.Wrap(ErrUnsuccessfulLockTry)
+	}
+
+	return unlockWrapper(fileLock.Unlock, fileLock.Path()), nil
+}
+
+// FSTryReadLockTimeout tries to grab read lock, it's doing it until locks is acquired, or timeout is expired,
+// or context is expired.
+func FSTryReadLockTimeout(ctx context.Context, filePath string, timeout time.Duration) (unlock func() error, err error) {
+	fileLock := flock.New(filePath + lockPostfix)
```
Comment (tigrato) [inline lib/utils/fs.go:203]: To simplify and avoid confusion, it's better if you wrap the lock file name in a function.
```
fileLock := flock.New(getPlatformLockFile(filePath))
```
I think this is more clear than filename+lockPostfix.
What do you think?

**Comment by AntonAM** [comment]
@r0mant 👍 I've already checked with OTP on Mac and Windows during development, will check the rest.

File: lib/utils/fs.go [hunk 4]
```diff
@@ -17,13 +17,22 @@ limitations under the License.
...
+
+	"github.com/gofrs/flock"
 
 	"github.com/gravitational/teleport"
 	"github.com/gravitational/trace"
 )
 
+// ErrUnsuccessfulLockTry designates an error when we temporarily couldn't acquire lock
+// (most probably it was already locked by someone else), another try might succeed.
+var ErrUnsuccessfulLockTry = errors.New("could not acquire lock on the file at this time")
```
Comment (tigrato) [inline lib/utils/fs.go:34]: maybe return a `trace.Retry` error if the idea is to inform users they can retry?

**Review by tigrato — APPROVED** [review]

File: lib/utils/fs.go (hunk 3 above)
Comment (AntonAM) [reply lib/utils/fs.go:203]: Yep, might be good idea, will change it.

File: lib/utils/fs.go (hunk 4 above)
Comment (AntonAM) [reply lib/utils/fs.go:34]: Hm, so something like `return nil, trace.Retry(ErrUnsuccessfulLockTry, "")`? Because we still need to provide error to retry.

**Review by timothyb89 — APPROVED** [review]

File: lib/utils/fs.go [hunk 5]
```diff
@@ -154,16 +154,20 @@ func StatDir(path string) (os.FileInfo, error) {
 	return fi, nil
 }
 
+func getPlatformLockFilePath(path string) string {
```
Comment (tigrato) [inline lib/utils/fs.go:157]: move the function to the `_unix.go` and `_windows.go` files so the function is closer to `lockPostFix`(unix does not need it if the function is defined local).
And merge it!

Comment (AntonAM) [reply lib/utils/fs.go]: Done 👍
