### PR TITLE
Fix issue "tsh db env" returns error when TLS routing enabled

### LINKED ISSUE #16209: "tsh db env" for Postgres database when TLS routing is enabled
Expected behavior:
`tsh db env/config` should work for postgres even if TLS routing is enabled.

Current behavior:
```
ERROR: "tsh db env" is not supported when TLS routing is enabled on the Teleport Proxy Service.
```
The "tsh db env" is used in an automated script, and the environment variables are set to run `pg_dump`.

Bug details:
- Teleport version: v10

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #16209 
- #16209

Root cause:
There were some WRONG assumptions that when TLS routing is enabled, an ALPN local proxy MUST be used. 

Change:
- Now `ERROR: "tsh db env" is not supported when TLS routing is enabled on the Teleport Proxy Service.` only applies to MySQL
- Move Snowflake to the tier where ALPN local proxy is always required.
- Fix Redis/ElasticSearch native client cmd -> Web Proxy direct connection without local proxy.

### CODE REVIEW

File: tool/tsh/db.go [hunk 1]
```diff
@@ -1007,12 +1008,36 @@ func formatDatabaseConfigCommand(clusterFlag string, db tlsca.RouteToDatabase) s
...
-// for connecting to the provided database. Currently return true if:
-//   - TLS routing is enabled.
-//   - A SQL Server connection always requires a local proxy.
+// for connecting to the provided database.
 func isLocalProxyRequiredForDatabase(tc *client.TeleportClient, db *tlsca.RouteToDatabase) bool {
-	return tc.TLSRoutingEnabled || db.Protocol == defaults.ProtocolSQLServer
+	if isLocalProxyAlwaysRequired(db.Protocol) {
+		return true
+	}
+	if tc.TLSRoutingEnabled && isLocalProxyRequiredForTLSRouting(db.Protocol) {
```
Comment (smallinsky) [inline tool/tsh/db.go:1037]: This condition doesn't look current. 
Let's say that we want to connect with 
 `tsh db connect` to a  postgres database when Teleport proxy support TLS routing. 
The `isLocalProxyRequiredForTLSRouting`  call will return false so the connection established to a teleport proxy won't leverage TLS routing features like db ping protocol.

Comment (greedy52) [reply tool/tsh/db.go:1037]: Good point. How about separating local proxy dependency to two levels `required` and `preferred`?

In `tsh db env/config`, we check if local proxy is required. And in `tsh db connect` we check if local proxy is preferred where local proxy is always used when TLS routing is enabled?

Comment (smallinsky) [reply tool/tsh/db.go:1037]: >we check if local proxy is preferred where local proxy is always preferred/used when TLS routing is enabled?

Yes, if a TLS routing is enable we should always use a local TLS/ALPN proxy in order to connect to teleport proxy. Where if TLS routing is disable we are leveraging ALPN local proxy to support MsSQL and Snowflake connections (MsSQL client doesn't support x509 certs and SnowSQL cli has some limitation that doesn't allow to set a custom client certs). 


> Or should tsh db connect always use local proxy regardless of multiplex mode?

The local proxy should be alway used for multiplex mode and for MSSQL and Snowflake connection in case if multiplex mode is disabled. 

The `tsh db config/env` commands aims to support GUI access where in case of TLS routing enable we are recomeneing to use `tsh db proxy` or `tsh db proxy --tunnel`  commands instead of `tsh db config/env` 
https://goteleport.com/docs/connect-your-client/gui-clients/#get-connection-information

Comment (greedy52) [reply tool/tsh/db.go:1037]: > The tsh db config/env commands aims to support GUI access where in case of TLS routing enable we are recommending to use tsh db proxy or tsh db proxy --tunnel commands instead of tsh db config/env

In the case of the reported issue, the `tsh db config/env` is used for native clients *directly* and in a *script*. And the particular database client used is `pg_dump`. So both `tsh db connect` and `tsh proxy db` is not viable alternative.

Comment (greedy52) [reply tool/tsh/db.go]: Reverted `tsh db connect` to always use the local proxy.

File: lib/client/db/dbcmd/dbcmd.go [hunk 2]
```diff
@@ -465,6 +465,11 @@ func (c *CLICommandBuilder) getRedisCommand() *exec.Cmd {
 		if c.options.caPath != "" {
 			args = append(args, []string{"--cacert", c.options.caPath}...)
 		}
+
+		// Set SNI when sending to remote web proxy.
+		if c.options.localProxyHost == "" {
+			args = append(args, []string{"--sni", c.tc.WebProxyHost()}...)
```
Comment (smallinsky) [inline lib/client/db/dbcmd/dbcmd.go:471]: I'm struggle to grasp why this is needed 
Does in case of non local proxy the --sni = c.tc.WebProxyHost() should be always part of the `-h` destination  host address  so the connection string will look like  `--sni teleport.example.com -h teleoprt.exampe.com:443` ?

**Review by smallinsky — COMMENTED** [review]
Left one question otherwise LGTM.

File: lib/client/db/dbcmd/dbcmd.go (hunk 2 above)
Comment (greedy52) [reply lib/client/db/dbcmd/dbcmd.go:471]: Yes. Without `--sni teleport.example.com`, I get the following error on the server side
```
2022-09-15T14:54:15Z WARN [ALPN:PROX] Failed to handle client connection. error:[
ERROR REPORT:
Original Error: *errors.errorString acme/autocert: missing server name
Stack Trace:
/go/teleport/lib/srv/alpnproxy/proxy.go:389 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).handleConn
/go/teleport/lib/srv/alpnproxy/proxy.go:327 github.com/gravitational/teleport/lib/srv/alpnproxy.(*Proxy).Serve.func1
/usr/local/go/src/runtime/asm_amd64.s:1571 runtime.goexit
```
I have acme on and i think this is part of the default web TLS config. Alternatively, we can try to allow this on the server side. WDYT?

Comment (smallinsky) [reply lib/client/db/dbcmd/dbcmd.go:471]: Ah I see. I think that teleport cloud require proper SNI to route the request to correct tenant so it should be fixed in the client side.

**Review by smallinsky — APPROVED** [review]

**Review by Tener — APPROVED** [review]
