### PR TITLE
Prevent race from causing remote clients from being closed

### LINKED ISSUE #17173: Teleport should retry when encountering "use of closed network connection"
### Expected behavior:

When attempting to list the resources in a trusted cluster, if a tunnel connection has been closed but not yet cleaned up, the web UI can display a big red banner with the following text:

```
error reading from server: use of closed network connection
```

Subsequent requests succeed. The agent tunnel state seems to be able to recover very quickly, and the web or teleport backend could simply retry if this error occurs.

This was also difficult to troubleshoot because there was no corresponding "use of closed network connection" message in the logs. I ended up finding that message in the codebase and setting a debug mode breakpoint to try to figure out why it was triggering.

### Current behavior:

Currently, if a read attempt is failed on a tunnel, this message makes it back to the end user and they must refresh.

This was initially observed in a usecase where multiple trusted clusters in various aws zones would seemingly have this error happen at random. While the underlying network is the suspected true root cause, this same error can be artificially induced, and Teleport would be able to gracefully handle this situation by a simple retry.

### Recreate Steps

To force this to happen, set up a trusted cluster, but use a socat mitm proxy so you can interrupt the connection. The easiest way that I do this is to run something like the following on a single node teleport instance:

```
$ host teleport.example.com
teleport.example.com has address 10.22.9.2
$ sudo /bin/bash -c "echo 127.0.0.1 teleport.example.com >> /etc/hosts"
$ sudo socat tcp-listen:443,reuseaddr,fork tcp:10.22.9.2:443
```

I can then add a trusted cluster like normal. due to the `fork` option, socat will spawn one cloned process per connection made through its listener. You can list all the child pids of the main socat process, and send a SIGKILL to the child pid.

Immediately load the https://teleport.example.com/web/cluster/leaf/nodes in the web browser. Since the socat is running on the same host as the leaf cluster, the leaf agent quickly recognizes that it needs to reconnect. The root cluster doesn't notice that there is a problem until the web browser hits it. It should trigger about every other attempt if you are quick on the alt+tab to the browser.

The red user-facing error message doesn't tell the end user what they need to do, and it seems like in some cases, a few short successions of attempts might be all it takes to get another tunnel to try.

### Bug details:
- **Teleport version** 10.3.1
- **Debug logs**

<details>
<summary>root cluster logs</summary>

```
2022-10-07T09:33:26-04:00 DEBU             Skipping login no-login-13828f58-239e-4033-a051-555b1848c50c, not a valid Unix login. services/role.go:261
2022-10-07T09:33:26-04:00 DEBU             Skipping login no-login-13828f58-239e-4033-a051-555b1848c50c, not a valid Unix login. services/role.go:261
2022-10-07T09:33:26-04:00 DEBU [PROXY:SER] Requesting connection to @remote-auth-server [] in remote cluster. cluster:boros-leaf reversetunnel/remotesite.go:850
2022-10-07T09:33:26-04:00 DEBU [RBAC]      Grant access to cluster boros-leaf - no role in [access editor auditor] uses cluster labels and the cluster is not labeled. services/role.go:1377
2022-10-07T09:33:26-04:00 DEBU [RBAC]      Grant access to cluster leaf - no role in [access editor auditor] uses cluster labels and the cluster is not labeled. services/role.go:1377
2022-10-07T09:33:26-04:00 DEBU [PROXY:SER] Requesting connection to @remote-auth-server [] in remote cluster. cluster:boros-leaf reversetunnel/remotesite.go:850
2022-10-07T09:33:26-04:00 DEBU             Skipping login no-login-13828f58-239e-4033-a051-555b1848c50c, not a valid Unix login. services/role.go:261
Breakpoint reached: 
2022-10-07T09:33:27-04:00 DEBU [SSH:PROXY] Closed connection 192.168.168.191:59408. pid:52705.1 sshutils/server.go:477
2022-10-07T09:33:27-04:00 INFO [PROXY:SER] Cluster agent disconnected. cluster:boros-leaf reversetunnel/remotesite.go:389
2022-10-07T09:33:27-04:00 DEBU [DISCOVERY] Disconnecting connection to boros-leaf 192.168.168.191:59408: agent disconnected. reversetunnel/conn.go:163
2022-10-07T09:33:27-04:00 DEBU [PROXY:SER] Deleting connection record. cluster:boros-leaf reversetunnel/remotesite.go:392
2022-10-07T09:33:27-04:00 INFO [PROXY:SER] Cluster connection closed. cluster:boros-leaf reversetunnel/remotesite.go:359
2022-10-07T09:33:27-04:00 DEBU [REVERSE:B] Cache is closing, returning from update loop. cache/cache.go:797
```
</details>

<details>
<summary>leaf cluster logs</summary>
```
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:goland reversetunnel/agentpool.go:318
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Starting agent {localhost:8443 tcp } leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:292
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Changing state initial -> connecting. leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:280
2022-10-07T07:33:26-06:00 DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Changing state connecting -> connected. leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:280
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Active agent count: 1 cluster:goland reversetunnel/agentpool.go:445
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Active agent count: 1 cluster:goland reversetunnel/agentpool.go:445
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Discovery request channel opened: teleport-discovery. leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:600
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] handleDiscovery requests channel. leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:623
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Received discovery request: [a47d2d39-ea98-433f-887a-4cb1f6e7cbb9] leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:651
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Transport request: teleport-transport. leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:569
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Transport request: teleport-transport. leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:569
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Received out-of-band proxy transport request for @remote-auth-server []. cluster:goland reversetunnel/transport.go:206
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Attempting to dial through tunnel with server ID "". cluster:goland reversetunnel/transport.go:377
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Attempting to dial directly "0.0.0.0:4025". cluster:goland reversetunnel/transport.go:394
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Returning direct dialed connection to "0.0.0.0:4025". cluster:goland reversetunnel/transport.go:400
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Successfully dialed to @remote-auth-server "", start proxying. cluster:goland reversetunnel/transport.go:313
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Received out-of-band proxy transport request for @remote-auth-server []. cluster:goland reversetunnel/transport.go:206
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Attempting to dial through tunnel with server ID "". cluster:goland reversetunnel/transport.go:377
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Attempting to dial directly "0.0.0.0:4025". cluster:goland reversetunnel/transport.go:394
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Returning direct dialed connection to "0.0.0.0:4025". cluster:goland reversetunnel/transport.go:400
2022-10-07T07:33:26-06:00 DEBU [PROXY:AGE] Successfully dialed to @remote-auth-server "", start proxying. cluster:goland reversetunnel/transport.go:313
2022-10-07T07:33:26-06:00 DEBU [AUTH]      ClientCertPool -> cert(goland issued by goland:314747983570344253491410991077144178540) auth/middleware.go:673
2022-10-07T07:33:26-06:00 DEBU [AUTH]      ClientCertPool -> cert(goland issued by goland:60640241679546410073834377934895566282) auth/middleware.go:673
2022-10-07T07:33:26-06:00 DEBU [AUTH:1]    Server certificate cert(2223b814-5785-4c8a-be7b-c58c6d4665c6.boros-leaf issued by boros-leaf:271015750646153867261637086614527188712). auth/middleware.go:310
2022-10-07T07:33:26-06:00 DEBU [AUTH]      ClientCertPool -> cert(goland issued by goland:314747983570344253491410991077144178540) auth/middleware.go:673
2022-10-07T07:33:26-06:00 DEBU [AUTH]      ClientCertPool -> cert(goland issued by goland:60640241679546410073834377934895566282) auth/middleware.go:673
2022-10-07T07:33:26-06:00 DEBU [AUTH:1]    Server certificate cert(2223b814-5785-4c8a-be7b-c58c6d4665c6.boros-leaf issued by boros-leaf:271015750646153867261637086614527188712). auth/middleware.go:310
2022-10-07T07:33:27-06:00 DEBU             Mapped roles [access editor auditor] of remote user "admin" to local roles [access auditor editor] and traits map[aws_role_arns:[] db_names:[] db_users:[] kubernetes_groups:[] kubernetes_users:[] logins:[-teleport-internal-join -teleport-nologin-d545b646-4b07-4df2-a298-f4134ae06000] windows_logins:[]]. services/access_checker.go:449
2022-10-07T07:33:27-06:00 DEBU             Mapped roles [access editor auditor] of remote user "admin" to local roles [access auditor editor] and traits map[aws_role_arns:[] db_names:[] db_users:[] kubernetes_groups:[] kubernetes_users:[] logins:[-teleport-internal-join -teleport-nologin-d545b646-4b07-4df2-a298-f4134ae06000] windows_logins:[]]. services/access_checker.go:449
2022-10-07T07:33:27-06:00 DEBU             Skipping login -teleport-internal-join, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login -teleport-nologin-d545b646-4b07-4df2-a298-f4134ae06000, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login -teleport-internal-join, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login -teleport-nologin-d545b646-4b07-4df2-a298-f4134ae06000, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login no-login-1b8fa2eb-c400-4c16-9bf1-50df231e0462, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login no-login-1b8fa2eb-c400-4c16-9bf1-50df231e0462, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Mapped roles [access editor auditor] of remote user "admin" to local roles [access auditor editor] and traits map[aws_role_arns:[] db_names:[] db_users:[] kubernetes_groups:[] kubernetes_users:[] logins:[-teleport-internal-join -teleport-nologin-d545b646-4b07-4df2-a298-f4134ae06000] windows_logins:[]]. services/access_checker.go:449
2022-10-07T07:33:27-06:00 DEBU             Skipping login -teleport-internal-join, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login -teleport-nologin-d545b646-4b07-4df2-a298-f4134ae06000, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login no-login-1b8fa2eb-c400-4c16-9bf1-50df231e0462, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU [AUTH]      GetServers(1->1) in 146.641µs. elapsed_fetch:122.973µs elapsed_filter:23.668µs user:remote-admin-goland auth/auth_with_roles.go:1176
2022-10-07T07:33:27-06:00 DEBU             Mapped roles [access editor auditor] of remote user "admin" to local roles [access auditor editor] and traits map[aws_role_arns:[] db_names:[] db_users:[] kubernetes_groups:[] kubernetes_users:[] logins:[-teleport-internal-join -teleport-nologin-d545b646-4b07-4df2-a298-f4134ae06000] windows_logins:[]]. services/access_checker.go:449
2022-10-07T07:33:27-06:00 DEBU             Skipping login -teleport-internal-join, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login -teleport-nologin-d545b646-4b07-4df2-a298-f4134ae06000, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU             Skipping login no-login-1b8fa2eb-c400-4c16-9bf1-50df231e0462, not a valid Unix login. services/role.go:261
2022-10-07T07:33:27-06:00 DEBU [PROXY:AGE] Failed to handle drainable channels. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError heartbeat: connection closed
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:542 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels
	/go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:331 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start.func3
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: heartbeat: connection closed] leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:332
2022-10-07T07:33:27-06:00 DEBU [PROXY:AGE] Failed to handle global requests. error:[
ERROR REPORT:
Original Error: *errors.errorString global request channel is closing
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:450 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleGlobalRequests
	/go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:320 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start.func2
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: global request channel is closing] leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:321
2022-10-07T07:33:27-06:00 DEBU [PROXY:AGE] Changing state connected -> closed. leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:280
2022-10-07T07:33:27-06:00 INFO [PROXY:AGE] Connection closed, returning leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:637
2022-10-07T07:33:27-06:00 WARN [PROXY:AGE] Failed to close discovery channel: EOF leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:626
2022-10-07T07:33:27-06:00 DEBU [PROXY:AGE] Failed to handle channels. error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:594 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleChannels
	/go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:340 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start.func4
	/opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: context canceled] leaseID:13 target:localhost:8443 cluster:goland reversetunnel/agent.go:341
2022-10-07T07:33:27-06:00 DEBU [PROXY:AGE] Active agent count: 0 cluster:goland reversetunnel/agentpool.go:445
2022-10-07T07:33:33-06:00 DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:goland reversetunnel/agentpool.go:318
2022-10-07T07:33:33-06:00 DEBU             Attempting GET localhost:8443/webapi/find webclient/webclient.go:119
```
</details>

<details>
<summary>tshark output of traffic between socat and root cluster</summary>
```
 3098 74.605612416 13:33:27.134803325 192.168.168.191 → 192.168.168.103 TLSv1.3 442 19 64 Application Data, Application Data, Application Data, Application Data
 3099 74.613257881 13:33:27.142448790 192.168.168.103 → 192.168.168.191 TCP 66 19 64 8443 → 59408 [ACK] Seq=13317 Ack=14172 Win=130496 Len=0 TSval=2916680571 TSecr=100964903
 3100 74.640418054 13:33:27.169608963 192.168.168.103 → 192.168.168.191 TCP 66 19 64 [TCP Previous segment not captured] 8443 → 59408 [FIN, ACK] Seq=13341 Ack=14172 Win=131072 Len=0 TSval=2916680599 TSecr=100964903
 3101 74.640479875 13:33:27.169670784 192.168.168.191 → 192.168.168.103 TCP 54 19 64 59408 → 8443 [RST] Seq=14172 Win=0 Len=0
 3102 74.640513863 13:33:27.169704772 192.168.168.103 → 192.168.168.191 TLSv1.3 90 19 64 [TCP Out-Of-Order] , Application Data
 3103 74.640533824 13:33:27.169724733 192.168.168.191 → 192.168.168.103 TCP 54 19 64 59408 → 8443 [RST] Seq=14172 Win=0 Len=0
```
</details>

<details>
<summary>info from chrome dev tools on failed request</summary>
```
## General
Request URL: https://127.0.0.1:8443/v1/webapi/sites/boros-leaf/nodes?searchAsRoles=&limit=15&startKey=&query=&search=&sort=hostname:asc
Request Method: GET
Status Code: 504 
Remote Address: 127.0.0.1:8443
Referrer Policy: no-referrer

## Response Headers
cache-control: no-cache, no-store, must-revalidate
content-length: 105
content-type: application/json
date: Fri, 07 Oct 2022 13:33:27 GMT
expires: 0
pragma: no-cache

## Request Headers
:authority: 127.0.0.1:8443
:method: GET
:path: /v1/webapi/sites/boros-leaf/nodes?searchAsRoles=&limit=15&startKey=&query=&search=&sort=hostname:asc
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
authorization: Bearer 811f914e936ccbce85538389fd7524d45e382c406adea0d745d69ff8ae966b74
content-type: application/json; charset=utf-8
cookie: __Host-grv_csrf=04ac897c6b1cbcb2ec519cc895355ab7dda5af00f4aed624ae64458acda0857f; __Host-session=7b2275736572223a2261646d696e222c22736964223a2261373730333437613039306532336431643935393433636663366533326562653864323763646564643961366234326666363035306562316539353836303537227d
sec-ch-ua: "Chromium";v="106", "Google Chrome";v="106", "Not;A=Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: same-origin
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
x-csrf-token: 04ac897c6b1cbcb2ec519cc895355ab7dda5af00f4aed624ae64458acda0857f

Response Body:

{
    "error": {
        "message": "error reading from server: use of closed network connection"
    }
}
```
</details>

root-127 0 0 1

Additional info can be shared if needed.

### PR DESCRIPTION
**Pull request by rosstimothy**
`web.SessionContext` was susceptible to races retrieving `auth.ClientI` for remote sites. The mutex on the remote client cache was not held for the duration of the `GetUserClient` which meant two simultaneous requests could find no client existed in the cache, create one and then add it to the cache. When the second client is added to the cache it would close the first client created, which results in the `use of closed network connection` error displaying on the web UI as described in #17173.

To remedy this the portion of `GetUserClient` that retrieves the remote client is now protected by a `singleflight.Group`. This ensures that races on creating a client no longer happen.

`web.SessionContext` was slightly refactored to make it easier to test, to remove some unnecessary operations, and to provide `context.Context` to `GetUserClient`. Additionally, all `web.SessionContext` variables which were named `ctx` in `lib/web` have been renamed to avoid confusion as that often refers to a `context.Context`.

Fixes #17173

### CODE REVIEW

File: lib/web/apiserver.go [hunk 1]
```diff
@@ -1602,8 +1602,8 @@ type CreateSessionResponse struct {
 	SessionInactiveTimeoutMS int `json:"sessionInactiveTimeout"`
 }
 
-func newSessionResponse(ctx *SessionContext) (*CreateSessionResponse, error) {
-	accessChecker, err := ctx.GetUserAccessChecker()
+func newSessionResponse(scx *SessionContext) (*CreateSessionResponse, error) {
```
Comment (zmb3) [inline lib/web/apiserver.go:1605]: It doesn't really matter, but I've encouraged `sctx` to others recently if you want to be consistent.

File: lib/web/sessions.go [hunk 2]
```diff
@@ -55,72 +56,137 @@ import (
...
+	if c.Resources == nil {
+		return trace.BadParameter("Resources required")
+	}
+
+	if c.Session == nil {
+		return trace.BadParameter("Session required")
+	}
+
+	if c.Log == nil {
+		c.Log = logrus.WithFields(logrus.Fields{
```
Comment (zmb3) [inline lib/web/sessions.go:124]: Should we also set component to web?

**Review by zmb3 — APPROVED** [review]

File: lib/web/apiserver.go [hunk 3]
```diff
@@ -2629,12 +2629,12 @@ func (h *Handler) clusterSearchSessionEvents(w http.ResponseWriter, r *http.Requ
 	searchSessionEvents := func(clt auth.ClientI, from, to time.Time, limit int, order types.EventOrder, startKey string) ([]apievents.AuditEvent, string, error) {
 		return clt.SearchSessionEvents(from, to, limit, order, startKey, nil, "")
 	}
-	return clusterEventsList(ctx, site, r.URL.Query(), searchSessionEvents)
+	return clusterEventsList(r.Context(), ctx, site, r.URL.Query(), searchSessionEvents)
```
Comment (ibeckermayer) [inline lib/web/apiserver.go:2632]: nit: `ctx` --> `sctx`

**Review by ibeckermayer — APPROVED** [review]
