### PR TITLE
Fix theme picker text when unspecified theme

### LINKED ISSUE #42395: Theme picker text is incorrect by default
### Expected behaviour:

The theme picker text is correct.

### Current behaviour:

I create a new private tab in chrome, my system theme is dark mode.
Teleport loads in dark but the menu says "switch to dark theme".

image

### Bug details:
- Teleport version v16.0.0-alpha.3

### PR DESCRIPTION
**Pull request by avatus**
Fixes https://github.com/gravitational/teleport/issues/42395
Currently, we work under the assumption that the theme is a binary decision between light/dark. The default user theme is now `UNSPECIFIED` which will default to the system theme. This PR adds a few utility options to get the current/next theme with this unspecified in mind. We can remove them once we add the user settings page to make "use system theme" a valid option to select.

To test, you can create a new user in an incognito window. The theme _should_ be whatever your system theme is. Also, the theme selector should know which theme is being used a properly show text for what the next theme should be.

### CODE REVIEW

**Review by ryanclark — COMMENTED** [review]
Can you add some tests for your new helper methods?

File: web/packages/design/src/ThemeProvider/index.tsx [hunk 1]
```diff
@@ -39,6 +39,23 @@ function themePreferenceToTheme(themePreference: Theme) {
   return themePreference === Theme.LIGHT ? lightTheme : darkTheme;
 }
 
+// because unspecific can exist but only used as a fallback and not an option,
```
Comment (zmb3) [inline web/packages/design/src/ThemeProvider/index.tsx:42]:
```suggestion
// because unspecified can exist but only used as a fallback and not an option,
```

File: web/packages/design/src/ThemeProvider/index.tsx [hunk 2]
```diff
@@ -39,6 +39,23 @@ function themePreferenceToTheme(themePreference: Theme) {
...
+// we need to get the current/next themes with getPrefersDark in mind.
+// TODO (avatus) when we add user settings page, we can add a Theme.SYSTEM option
+// and remove the checks for unspecified
+export function getCurrentTheme(currentTheme: Theme): Theme {
+  if (currentTheme === Theme.UNSPECIFIED) {
+    return getPrefersDark() ? Theme.DARK : Theme.LIGHT;
+  }
+}
```
Comment (zmb3) [inline web/packages/design/src/ThemeProvider/index.tsx:50]: Are you intentionally not returning anything if `currentTheme !== Theme.UNSPECIFIED`?

Comment (avatus) [reply web/packages/design/src/ThemeProvider/index.tsx:52]: No. Thanks!

File: web/packages/design/src/ThemeProvider/index.tsx [hunk 3]
```diff
@@ -39,6 +39,25 @@ function themePreferenceToTheme(themePreference: Theme) {
...
+  }
+
+  return currentTheme;
+}
+
+export function getNextTheme(currentTheme: Theme): Theme {
+  if (currentTheme === Theme.UNSPECIFIED) {
+    return getPrefersDark() ? Theme.LIGHT : Theme.DARK;
+  }
+  return currentTheme === Theme.LIGHT ? Theme.DARK : Theme.LIGHT;
```
Comment (ryanclark) [inline web/packages/design/src/ThemeProvider/index.tsx:58]: Can this be
```suggestion
  return getCurrentTheme(currentTheme) === Theme.LIGHT ? Theme.DARK : Theme.LIGHT;
```

**Comment by avatus** [comment]
friendly ping @ryanclark @kimlisa @rudream

File: web/packages/design/src/ThemeProvider/index.tsx [hunk 4]
```diff
@@ -39,6 +39,24 @@ function themePreferenceToTheme(themePreference: Theme) {
   return themePreference === Theme.LIGHT ? lightTheme : darkTheme;
 }
 
+// because unspecified can exist but only used as a fallback and not an option,
+// we need to get the current/next themes with getPrefersDark in mind.
+// TODO (avatus) when we add user settings page, we can add a Theme.SYSTEM option
+// and remove the checks for unspecified
+export function getCurrentTheme(currentTheme: Theme): Theme {
+  if (currentTheme === Theme.UNSPECIFIED) {
+    return getPrefersDark() ? Theme.DARK : Theme.LIGHT;
```
Comment (kimlisa) [inline web/packages/design/src/ThemeProvider/index.tsx:48]: how do i test this?  i created a new user, and it defaulted to light theme (using brave)

image

image

**Review by kimlisa — APPROVED** [review]
just a minor comment, otherwise lgtm

File: web/packages/design/src/ThemeProvider/index.tsx (hunk 4 above)
Comment (avatus) [reply web/packages/design/src/ThemeProvider/index.tsx:48]: I wasn't able to reproduce this first click not working in incognito or normal mode

**Comment by avatus** [comment]
friendly ping @ryanclark

**Review by ryanclark — APPROVED** [review]
Sorry, was waiting for the reply to Lisa's comment 🙂
