### PR TITLE
Ensure correct workspace is set before opening desktop document

### LINKED ISSUE #55248: Connect: Selecting a desktop from the search bar does not switch workspace
Steps to repro:

1. Log in to a cluster with Windows desktops.
2. Switch to another workspace.
3. From the search bar, find a desktop from the cluster from point 1 and attempt to connect to it.

Expected behavior:

A new desktop tab is opened and the workspace is switched to the workspace from point 1.

Current behavior:

A new desktop tab is opened in the correct workspace, however the app doesn't automatically switch to that workspace.

TODO:

- [x] Add a regression test.

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/55248

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToWindowsDesktop.ts [hunk 1]
```diff
@@ -32,6 +32,8 @@ export async function connectToWindowsDesktop(
     origin: DocumentOrigin;
   }
 ): Promise<void> {
+  const rootClusterUri = routing.ensureRootClusterUri(target.uri);
+  await ctx.workspacesService.setActiveWorkspace(rootClusterUri);
   ctx.workspacesService
     .getWorkspaceDocumentService(routing.ensureRootClusterUri(target.uri))
```
Comment (ravicious) [inline web/packages/teleterm/src/ui/services/workspacesService/documentsService/connectToWindowsDesktop.ts]: This line can reuse `rootClusterUri` from line 35.

**Review by ravicious — APPROVED** [review]
