### PR TITLE
Fixing default shell assignment

### LINKED ISSUE #47283: `create_host_user_default_shell` seems to be ignored
When using `create_host_user_default_shell: /bin/bash` with host user creation, Teleport should respect that option.

The current behavior seems to be that it ignores `create_host_user_default_shell` and goes with the `SHELL` value as set in `/etc/default/useradd`.

This was observed on a 16.4.2 cluster with a 16.4.2 node, with a user in a single role that has `create_host_user_default_shell` set.

When Teleport creates the user, `useradd` logs the following:

```
Oct 07 10:13:40 myhost useradd[2351677]: new group: name=ubuntu, GID=1007
Oct 07 10:13:40 myhost useradd[2351677]: new user: name=ubuntu, UID=1003, GID=1007, home=/home/ubuntu, shell=/bin/sh, from=none
Oct 07 10:13:40 myhost useradd[2351677]: add 'ubuntu' to group 'teleport-keep'
Oct 07 10:13:40 myhost useradd[2351677]: add 'ubuntu' to shadow group 'teleport-keep'
```

This happens whether the value is set to `bash` or `/bin/bash`. The `/etc/shells` file lists `/bin/bash`.

### PR DESCRIPTION
**Pull request by eriktate**
Fixes #47283

This fixes a bug preventing role-defined default shell assignment from propagating to host users.

Changelog: Fixed an issue preventing default shell assignment for host users

### CODE REVIEW

File: lib/services/access_checker.go [hunk 1]
```diff
@@ -1060,7 +1060,7 @@ func (a *accessChecker) HostUsers(s types.Server) (*HostUsersInfo, error) {
 
 		hostUserShell := role.GetOptions().CreateHostUserDefaultShell
 		if hostUserShell != "" {
-			if shell != "" {
+			if shell == "" {
```
Comment (eriktate) [inline lib/services/access_checker.go:1063]: This was definitely working at one point, so I must've fat fingered this comparison :facepalm: Added a test to catch this in the future

**Review by strideynet — APPROVED** [review]

File: lib/services/access_checker.go (hunk 1 above)
Comment (zmb3) [reply lib/services/access_checker.go:1063]: Can this whole thing collapse down to a one liner? `shell = cmp.Or(shell, role.GetOptions().CreateHostUserDefaultShell)`?

- If `shell` is already set it's a no-op.
- If `shell` is not set and the role doesn't specify a default `shell` remains empty
- If `shell` is not set and the role does specify a shell, then `shell` is overwritten

Comment (eriktate) [reply lib/services/access_checker.go]: Good call, shell assignment totally can be :+1: I really need to start reaching for the `cmp` package more often

**Review by rosstimothy — APPROVED** [review]
