### PR TITLE
deny access in case of missing roles, fixes #724

### LINKED ISSUE #724: Return access denied in case if no roles found
## Description

In case of dynamic mapping, we should return access denied if we have failed to map any roles to the authentication. Otherwise it is possible to have a case when users can authenticate but will have no permissions at all, that is not only confusing but creates potential risk.

### PR DESCRIPTION
**Pull request by klizhentas**

### CODE REVIEW

File: lib/auth/auth.go [hunk 1]
```diff
@@ -782,6 +782,7 @@ func (a *AuthServer) createOIDCUser(connector services.OIDCConnector, ident *oid
 	if len(roles) == 0 {
 		log.Warningf("[OIDC] could not find any of expected claims: %v in the set returned by provider %v: %v",
 			strings.Join(connector.GetClaims(), ","), connector.GetName(), strings.Join(services.GetClaimNames(claims), ","))
+		return trace.AccessDenied("access to %v is denied", ident.Email)
```
Comment (kontsevoy) [inline lib/auth/auth.go]: the error message does not seem right. Looks to me it will say `access to ev@kontsevoy.com is denied`. Is that correct? In that case it should change to `access denied to ev@kontsevoy.com`

**Review by kontsevoy — CHANGES_REQUESTED** [review]

**Comment by klizhentas** [comment]
applied comments, merging
