### PR TITLE
Synchronize access to tsh exit status

### LINKED ISSUE #21089: `TestIntegrations/CmdLabels` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695

#### Relevant snippet

```
integration_test.go:5237: 
[976](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:977)
        	Error Trace:	/__w/teleport/teleport/integration/integration_test.go:5237
[977](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:978)
        	Error:      	Received unexpected error:
[978](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:979)
        	            	failed connecting to node 00000000-0000-0000-0000-000000000000. Teleport proxy failed to connect to "node" agent "" over reverse tunnel:
[979](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:980)
        	            	
[980](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:981)
        	            	  no tunnel connection found: no node reverse tunnel for 00000000-0000-0000-0000-000000000000.local-site found
[981](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:982)
        	            	
[982](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:983)
        	            	This usually means that the agent is offline or has disconnected. Check the
[983](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:984)
        	            	agent logs and, if the issue persists, try restarting it or re-registering it
[984](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:985)
        	            	with the cluster.
[985](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:986)
        	Test:       	TestIntegrations/CmdLabels/Worker_only
[986](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:987)
        --- FAIL: TestIntegrations/CmdLabels/Worker_only (1.14s)```

### PR DESCRIPTION
**Pull request by atburke**
This change synchronizes access to the exit status in the Teleport client. It also reverts a RunCommand change in #54423 to only set the exit status on error.

Fixes #21089.

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -1264,6 +1260,9 @@ type DTAutoEnrollFunc func(context.Context, devicepb.DeviceTrustServiceClient) (
 // TeleportClient is NOT safe for concurrent use.
 type TeleportClient struct {
 	Config
+	exitStatus int
+	statusMu   sync.RWMutex
```
Comment (zmb3) [inline lib/client/api.go:1264]: I wouldn't use an RWMutex for something so trivial. A regular mutex should be fine here.

File: lib/client/api.go [hunk 2]
```diff
@@ -1330,6 +1329,20 @@ func NewClient(c *Config) (tc *TeleportClient, err error) {
 	return tc, nil
 }
 
+// ExitStatus returns the exit status of the most recent ssh command.
```
Comment (zmb3) [inline lib/client/api.go:1332]:
```suggestion
// ExitStatus returns the exit status of the most recent SSH command.
```

Is it worth mentioning that it's the caller's responsibility to ensure that the command has already exited before checking this?

File: lib/client/api.go [hunk 3]
```diff
@@ -1330,6 +1329,20 @@ func NewClient(c *Config) (tc *TeleportClient, err error) {
...
+func (tc *TeleportClient) ExitStatus() int {
+	tc.statusMu.Lock()
+	defer tc.statusMu.Unlock()
+	return tc.exitStatus
+}
+
+// SetExitStatus sets the exit status of the most recent ssh command.
```
Comment (zmb3) [inline lib/client/api.go:1339]:
```suggestion
// SetExitStatus sets the exit status of the most recent SSH command.
```

**Review by avatus — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
