### PR TITLE
tctl: fix error reporting when server is down

### LINKED ISSUE #28129: `tctl` silently exits when the server is down
Expected behavior:

If the server is down, and `tctl` exits due to that fact, it should show an appropriate error message.

Current behavior:

No message is shown unless `--debug` is provided.

Bug details:

- https://github.com/gravitational/teleport/pull/25780 removed `utils.Consolef` call: https://github.com/gravitational/teleport/pull/25780/files#diff-e87b24a58b433f3d328d081196ff301f239308714fa63ead2d9e7527c8186342

Logs:

```
> tctl get all
> tctl get all --debug
2023-06-22T11:15:40+02:00 DEBU             Debug logging has been enabled. common/tctl.go:239
2023-06-22T11:15:40+02:00 DEBU             reading config file: /etc/teleport.yaml config/configuration.go:214
2023-06-22T11:15:40+02:00 ERRO             "Cannot connect to the auth server. Is the auth server running on \"boson.tener.io:3025\"? failed direct dial to auth server: dial tcp 192.168.7.186:3025: connect: connection refused\n\tdial tcp 192.168.7.186:3025: connect: connection refused" common/tctl.go:202
```

cc @stevenGravy

### PR DESCRIPTION
**Pull request by zmb3**
A regresion in #25780 changed text that used to be reported to standard output to go to the logger instead. Since the logger output is only visible when the debug flag is set, this caused a fatal error to go unreported to the user.

Fixes #28129

### CODE REVIEW

**Review by flyinghermit — APPROVED** [review]

File: tool/tctl/common/tctl.go [hunk 1]
```diff
@@ -199,8 +199,8 @@ func TryRun(commands []CLICommand, args []string) error {
 		if utils.IsUntrustedCertErr(err) {
 			err = trace.WrapWithMessage(err, utils.SelfSignedCertsMsg)
 		}
-		log.Errorf("Cannot connect to the auth server. Is the auth server running on %q? %v",
-			cfg.AuthServerAddresses()[0].Addr, err)
+		fmt.Printf("ERROR: Cannot connect to the auth server. Is the auth server running on %q?\n",
+			cfg.AuthServerAddresses()[0].Addr)
```
Comment (fspmarshall) [inline tool/tctl/common/tctl.go:203]:
```suggestion
		fmt.Fprintf(os.Stderr, "ERROR: Cannot connect to the auth server. Is the auth server running on %q?\n",
			cfg.AuthServerAddresses()[0].Addr)
```

**Review by fspmarshall — APPROVED** [review]
