### PR TITLE
Downgrade DNS errors to a warning log when creating MongoDB databases

### LINKED ISSUE #18891: Invalid MongoDB database connection string prevents Teleport from starting
After rebasing off of latest master I get this trying to start Teleport:

```
2022-11-29T18:18:27-08:00 WARN [AUTH:1:CA] Re-init the cache on error: invalid MongoDB database "atlas" connection string "mongodb+srv://cluster0.e4hrv.mongodb.net": error parsing uri: lookup _mongodb._tcp.cluster0.e4hrv.mongodb.net on 75.75.75.75:53: no such host. cache/cache.go:823
```

And the cluster doesn't start because cache fails to initialize.

I think this PR might be the issue: https://github.com/gravitational/teleport/pull/18776. I don't think we should be trying to resolve the endpoint while initializing the service.

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #18891 
- #18891

### CODE REVIEW

File: lib/services/database.go [hunk 1]
```diff
@@ -200,6 +195,40 @@ func ValidateDatabase(db types.Database) error {
...
+	connString, err := connstring.ParseAndValidate(db.GetURI())
+	if err != nil {
+		// connstring.ParseAndValidate requires DNS resolution on TXT/SRV
+		// records for a full validation for "mongodb+srv" URIs. Log a warning
+		// here when DNS resolution fails as we mostly care if the URI is
+		// "lexically" correct at this point. Full validation is more
+		// approriate for health checks or new connections.
+		if isDNSError(err) {
+			logrus.Warnf("MongoDB database %q (connection string %q) failed validation with DNS error: %v", db.GetName(), db.GetURI(), err)
+			return nil
```
Comment (r0mant) [inline lib/services/database.go:209]: If we hit DNS error and return here, we won't do any of the checks below, right? So an incorrect read preference for example can sneak in? I assume the returned connString is empty - is there a way to still do the other checks?

Comment (greedy52) [reply lib/services/database.go:209]: `connString` will not be empty but without reading driver code, it's hard to tell what has been parsed and what's not when this DNS error is returned.

> is there a way to still do the other checks?
We have to fork mongo-driver and add/expose some extra options for parsing.

Comment (r0mant) [reply lib/services/database.go:209]: Looking at the driver's code, it only tries to use DNS resolver if the scheme is `mongodb+srv://`. What if we change the scheme to `mongodb://` just for the sake of validation? A bit hacky but might work?

Comment (greedy52) [reply lib/services/database.go:209]: i think it will work but the driver does some extra validations for `mongodb+srv://` type like `mongodb+srv://` URI must have no port, or `srv` specific parameters like `srvmaxhosts` etc. so we will lose those if we replace the scheme.

the `dnsResolver` is an interface so ideally if we can just pass in a fake for this case, but driver doesn't provide that option. we can technically overwrite the `DefaultResolver` from `"go.mongodb.org/mongo-driver/x/mongo/driver/dns"` but there could be race condition if someone is actually making a mongo connection at the same time.

Comment (greedy52) [reply lib/services/database.go:209]: maybe we only replace scheme when we run into the DNS error and `ParseAndValidate` again withe the replaced URI?

Comment (r0mant) [reply lib/services/database.go:209]: Yep that sounds like a good idea.

File: lib/services/database.go [hunk 2]
```diff
@@ -200,6 +195,45 @@ func ValidateDatabase(db types.Database) error {
...
+	return nil
+}
+
+func isDNSError(err error) bool {
+	if unwrapped := errors.Unwrap(err); unwrapped != nil {
+		err = unwrapped
+	}
+
+	_, ok := err.(*net.DNSError)
+	return ok
```
Comment (smallinsky) [inline lib/services/database.go:234]: nit: can we just call ? 
```suggestion
	var dnsErr *net.DNSError
	return errors.As(err, &dnsErr)
```

File: lib/services/database.go [hunk 3]
```diff
@@ -34,6 +35,7 @@ import (
 	"github.com/aws/aws-sdk-go/service/redshift"
 	"github.com/coreos/go-semver/semver"
 	"github.com/gravitational/trace"
+	"github.com/sirupsen/logrus"
```
Comment (smallinsky) [inline lib/services/database.go:38]: nit: The package is already imported below as `log "github.com/sirupsen/logrus"`

File: lib/services/database.go [hunk 4]
```diff
@@ -200,6 +194,48 @@ func ValidateDatabase(db types.Database) error {
...
+	return nil
+}
+
+func isDNSError(err error) bool {
+	if err == nil {
+		return false
+	}
+	if unwrapped := errors.Unwrap(err); unwrapped != nil {
+		err = unwrapped
+	}
```
Comment (smallinsky) [inline lib/services/database.go:233]: I think that this lines are superfluous - undraping will be done inside the `errors.As` call.

**Review by smallinsky — APPROVED** [review]

**Review by r0mant — APPROVED** [review]

File: lib/services/database.go (hunk 4 above)
Comment (greedy52) [reply lib/services/database.go:233]: good catch!
