### PR TITLE
Fix session recording truncation

### LINKED ISSUE #60860: Session Upload Completer wipes recent session recordings every 24 hours
Expected behavior:
Session recordings should be uploaded when the session ends and should be kept in storage to be played later.

Current behavior:
Session recordings are uploaded after the session ends, the recording is uploaded, but the multipart metadata/directories are [not cleaned up](https://github.com/gravitational/teleport/pull/10608). The next time the upload completer runs, it scans the records directory and sees empty multipart upload directories left behind. Thinking this is an abandoned upload, the completer wipes the stored session recording.

Before:
```
> ls -lR ~c/local/storage/data/dir/root/log
...
/Users/bjoerger/src/gravitational/teleport-config/local/storage/data/dir/root/log/records:
total 1080
-rw-r--r--@ 1 bjoerger  staff   45935 Oct 30 18:40 983fcf69-de54-460d-a1e0-94eb16dec873.metadata
-rw-------@ 1 bjoerger  staff  494963 Oct 30 18:40 983fcf69-de54-460d-a1e0-94eb16dec873.tar
-rw-r--r--@ 1 bjoerger  staff    6777 Oct 30 18:40 983fcf69-de54-460d-a1e0-94eb16dec873.thumbnail
drwx------@ 3 bjoerger  staff      96 Oct 30 18:40 multi

/Users/bjoerger/src/gravitational/teleport-config/local/storage/data/dir/root/log/records/multi:
total 0
drwx------@ 3 bjoerger  staff  96 Oct 30 18:40 00b92187-1f65-420b-a3c4-90809797ed0a

/Users/bjoerger/src/gravitational/teleport-config/local/storage/data/dir/root/log/records/multi/00b92187-1f65-420b-a3c4-90809797ed0a:
total 0
drwx------@ 2 bjoerger  staff  64 Oct 30 18:40 983fcf69-de54-460d-a1e0-94eb16dec873
...
```

After:
```
> ls -lR ~c/local/storage/data/dir/root/log
/Users/bjoerger/src/gravitational/teleport-config/local/storage/data/dir/root/log/records:
total 112
-rw-r--r--@ 1 bjoerger  staff  45935 Oct 30 18:40 983fcf69-de54-460d-a1e0-94eb16dec873.metadata
-rw-------@ 1 bjoerger  staff      0 Oct 30 18:44 983fcf69-de54-460d-a1e0-94eb16dec873.tar
-rw-r--r--@ 1 bjoerger  staff   6777 Oct 30 18:40 983fcf69-de54-460d-a1e0-94eb16dec873.thumbnail
drwx------@ 2 bjoerger  staff     64 Oct 30 18:44 multi
```

Debug Logs:
```
2025-10-30T18:44:01.828-07:00 DEBU [AUTH:COMP] Upload was abandoned, trying to complete upload:00b92187-1f65-420b-a3c4-90809797ed0a session:983fcf69-de54-460d-a1e0-94eb16dec873 events/complete.go:252
2025-10-30T18:44:01.828-07:00 DEBU [AUTH:COMP] found upload with parts upload:00b92187-1f65-420b-a3c4-90809797ed0a session:983fcf69-de54-460d-a1e0-94eb16dec873 part_count:0 events/complete.go:274
2025-10-30T18:44:01.830-07:00 DEBU [AUTH:COMP] Completed upload upload:00b92187-1f65-420b-a3c4-90809797ed0a session:983fcf69-de54-460d-a1e0-94eb16dec873 events/complete.go:282
2025-10-30T18:44:01.830-07:00 DEBU [AUTH:COMP] Found active uploads active:1 completed:1 events/complete.go:223
```

Bug details:
- Teleport version: v18.3.0*
  - Had to make slight modifications to reproduce it without waiting 24 hours: (5abf63db22f126355f8c0e184374752694e9814b)
- Recreation steps
  - node async recording mode, did not test other modes.
  - file audit storage 
    - S3 (tested) and GC seem to be safe thanks to [prior changes](https://github.com/gravitational/teleport/pull/10608). 
    - Azure needs to be tested as it may be impacted.

### PR DESCRIPTION
**Pull request by Joerger**
Changelog: fix an issue which could lead to session recordings saved on disk being truncated.

Fixes https://github.com/gravitational/teleport/issues/60860

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: lib/events/filesessions/filestream_test.go [hunk 1]
```diff
@@ -169,3 +169,48 @@ func TestCompleteUpload(t *testing.T) {
 		})
 	}
 }
+
+func TestCleanupEmptyUpload(t *testing.T) {
+	ctx := context.Background()
```
Comment (rosstimothy) [inline lib/events/filesessions/filestream_test.go]:
```suggestion
	ctx := t.Context()
```

**Review by rosstimothy — APPROVED** [review]

File: lib/events/filesessions/filestream_test.go [hunk 2]
```diff
@@ -128,14 +128,6 @@ func TestCompleteUpload(t *testing.T) {
...
 			},
 		},
-		{
-			desc:            "OnlyReservation",
-			expectedContent: []byte{},
-			partsFunc: func(t *testing.T, handler *Handler, upload *events.StreamUpload) {
-				createPart(t, handler, upload, int64(1), []byte{})
-				createPart(t, handler, upload, int64(2), []byte{})
-			},
-		},
```
Comment (Joerger) [inline lib/events/filesessions/filestream_test.go:138]: @rosstimothy FYI I had to remove this test as it was basically ensuring that we _do_ upload empty uploads if we find an empty upload instead of discarding it.

File: lib/events/filesessions/filestream_test.go [hunk 3]
```diff
@@ -169,3 +161,48 @@ func TestCompleteUpload(t *testing.T) {
...
+	require.NoError(t, err)
+
+	// The empty upload should be cleaned up without impacting the original completed upload.
+	uploadPath := handler.recordingPath(upload.SessionID)
+	f, err := os.Open(uploadPath)
+	require.NoError(t, err)
+
+	gotContent, err := io.ReadAll(f)
+	require.NoError(t, err)
+	require.Equal(t, content, gotContent)
```
Comment (rosstimothy) [inline lib/events/filesessions/filestream_test.go:204]: Let's take a closer look at this fix since test is failing in CI. 
```        	Error Trace:	/__w/teleport/teleport/lib/events/filesessions/filestream_test.go:204
        	Error:      	Not equal: 
        	            	expected: []byte{0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x77, 0x6f, 0x72, 0x6c, 0x64}
        	            	actual  : []byte{}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,3 +1,2 @@
        	            	-([]uint8) (len=11) {
        	            	- 00000000  68 65 6c 6c 6f 20 77 6f  72 6c 64                 |hello world|
        	            	+([]uint8) {
        	            	 }
        	Test:       	TestCleanupEmptyUpload
```

Comment (Joerger) [reply lib/events/filesessions/filestream_test.go:204]: This was caused by 9177f922bf1cdcf0df4b112afb52b03dafe4dd29, reverted. Sorry for the haphazard change, in addition to being done wrong, I don't think it's necessary.

**Review by rosstimothy — APPROVED** [review]
