### PR TITLE
Fix TestAgentStart flakiness

### LINKED ISSUE #14553: `TestAgentStart` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/1d1d3095-984a-4a8e-9091-bd97a8f6be9c?project=ci-account

#### Relevant snippet

```
WARNING: DATA RACE
Write at 0x00c0001f00a8 by goroutine 68:
  github.com/gravitational/teleport/lib/reversetunnel.TestAgentStart.func2.1()
      /workspace/lib/reversetunnel/agent_test.go:275 +0x66
  github.com/gravitational/teleport/lib/reversetunnel.(*mockSSHChannel).SendRequest()
      /workspace/lib/reversetunnel/agent_test.go:122 +0xa2
  github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels()
      /workspace/lib/reversetunnel/agent.go:543 +0x68f
  github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start.func3()
      /workspace/lib/reversetunnel/agent.go:324 +0x45

Previous read at 0x00c0001f00a8 by goroutine 61:
  github.com/gravitational/teleport/lib/reversetunnel.TestAgentStart()
      /workspace/lib/reversetunnel/agent_test.go:298 +0x684
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1486 +0x47

Goroutine 68 (running) created at:
  github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start()
      /workspace/lib/reversetunnel/agent.go:323 +0x555
  github.com/gravitational/teleport/lib/reversetunnel.TestAgentStart()
      /workspace/lib/reversetunnel/agent_test.go:294 +0x5d0
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1486 +0x47

Goroutine 61 (finished) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1486 +0x724
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:1839 +0x99
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.runTests()
      /opt/go/src/testing/testing.go:1837 +0x7e4
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:1719 +0xa71
  main.main()
      _testmain.go:173 +0x3a9
==================
=== CONT  TestAgentCertChecker
    testing.go:1312: race detected during execution of test
--- FAIL: TestAgentCertChecker (5.77s)
===================================================
OUTPUT github.com/gravitational/teleport/lib/reversetunnel.TestAgentStart
===================================================
=== RUN   TestAgentStart
    agent_test.go:299: 
        	Error Trace:	agent_test.go:299
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestAgentStart
        	Messages:   	Expected 1 version reply.
--- FAIL: TestAgentStart (0.00s)
==================
WARNING: DATA RACE
Write at 0x00c0001f00b8 by goroutine 66:
  github.com/gravitational/teleport/lib/reversetunnel.TestAgentStart.func3()
      /workspace/lib/reversetunnel/agent_test.go:287 +0x84
  github.com/gravitational/teleport/lib/reversetunnel.(*mockSSHClient).Reply()
      /workspace/lib/reversetunnel/agent_test.go:94 +0xa6
  github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleGlobalRequests()
      /workspace/lib/reversetunnel/agent.go:457 +0x928
  github.com/gravitational/teleport/lib/reversetunnel.(*agent).connect.func1()
      /workspace/lib/reversetunnel/agent.go:372 +0x94

Previous read at 0x00c0001f00b8 by goroutine 61:
  github.com/gravitational/teleport/lib/reversetunnel.TestAgentStart()
      /workspace/lib/reversetunnel/agent_test.go:299 +0x704
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1486 +0x47

Goroutine 66 (running) created at:
  github.com/gravitational/teleport/lib/reversetunnel.(*agent).connect()
      /workspace/lib/reversetunnel/agent.go:371 +0x4ca
  github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start()
      /workspace/lib/reversetunnel/agent.go:305 +0x3d1
  github.com/gravitational/teleport/lib/reversetunnel.TestAgentStart()
      /workspace/lib/reversetunnel/agent_test.go:294 +0x5d0
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1486 +0x47

Goroutine 61 (finished) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1486 +0x724
  testing.runTests.func1()
      /opt/go/src/testing/testing.go:1839 +0x99
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.runTests()
      /opt/go/src/testing/testing.go:1837 +0x7e4
  testing.(*M).Run()
      /opt/go/src/testing/testing.go:1719 +0xa71
  main.main()
      _testmain.go:173 +0x3a9
```

### PR DESCRIPTION
**Pull request by dboslee**
The main issue here is that the `versionReplies` counter is incremented after closing the `waitForVersion` channel. This makes it possible for `require.Equal(t, 1, int(atomic.LoadInt32(versionReplies)), "Expected 1 version reply.")` to be evaluated before the increment happens. Moving the `versionReplies` increment above `close(waitForVersion)` should prevent this.

I also added atomic operations to prevent any races, although none are expected with the changes I described above.

There was also goroutines leaked due to not calling `tracker.StopAll()`.

Fixes #14553

### CODE REVIEW

File: lib/reversetunnel/agent_test.go [hunk 1]
```diff
@@ -269,34 +277,37 @@ func TestAgentStart(t *testing.T) {
...
+
+	err := agent.Start(ctx)
 
 	require.NoError(t, err)
-	require.Equal(t, 1, openChannels, "Expected only heartbeat channel to be opened.")
-	require.GreaterOrEqual(t, 1, sentPings, "Expected at least 1 ping to be sent.")
-	require.Equal(t, 1, versionReplies, "Expected 1 version reply.")
+	require.Equal(t, 1, int(atomic.LoadInt32(openChannels)), "Expected only heartbeat channel to be opened.")
+	require.GreaterOrEqual(t, 1, int(atomic.LoadInt32(sentPings)), "Expected at least 1 ping to be sent.")
+	require.Equal(t, 1, int(atomic.LoadInt32(versionReplies)), "Expected 1 version reply.")
```
Comment (nklaassen) [inline lib/reversetunnel/agent_test.go:310]: are these guaranteed to be incremented before `agent.Start` returns, or does that happen in the background?

Comment (dboslee) [reply lib/reversetunnel/agent_test.go:310]: It is expected to happen before `agent.Start` returns.

**Review by nklaassen — APPROVED** [review]

**Review by codingllama — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
can confirm I am no longer able to reproduce the race condition or the goroutine leaks with this fix.
