### PR TITLE
Fix identity file relogin issue

### LINKED ISSUE #20373: `tsh` no longer loads identity files properly, breaks `tbot`'s `ssh_config`
Expected behavior:

When given an identity file, e.g. from `tbot`, `tsh ls` should work:
```
$ tsh -d -i tbot-user/identity --proxy=example.com:3080 ls
Node Name Address        Labels                                     
--------- -------------- ------------------------------------------ 
example   127.0.0.1:3022 env=staging 
```

Current behavior:

As of https://github.com/gravitational/teleport/commit/488af75797326e92145497955fdadbd97711171b, the certificate is rejected and `tsh` prompts for a password, which should never happen when an identity file is provided.

```
INFO [CLIENT]    no host login given. defaulting to tim client/api.go:923
DEBU [CLIENT]    Skipping connection to the local ssh-agent. client/keyagent.go:136
DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-01-18 23:09:44 +0000 UTC". client/client_store.go:89
INFO [KEYAGENT]  Loading SSH key for user "bot-testplan2" and cluster "example.com". client/keyagent.go:206
DEBU [TSH]       Pinging the proxy to fetch listening addresses for non-web ports. tsh/tsh.go:3213
DEBU [CLIENT]    not using loopback pool for remote proxy addr: example.com:3080 client/api.go:3807
DEBU             Attempting GET example.com:3080/webapi/ping webclient/webclient.go:129
DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-01-18 23:09:44 +0000 UTC". client/client_store.go:89
DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-01-18 23:09:44 +0000 UTC". client/client_store.go:89
INFO [CLIENT]    Connecting to proxy=example.com:3080 login="-teleport-nologin-f3e945c3-7cbd-48bc-af1b-fb3d727093f4" using TLS Routing client/api.go:2763
DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-01-18 23:09:44 +0000 UTC". client/client_store.go:89
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301
DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-01-18 23:09:44 +0000 UTC". client/client_store.go:89
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com <snip>\n." client/keyagent.go:363
DEBU [KEYAGENT]  Host example.com:3080 presented a public key not signed by Teleport. Rejecting due to insecure mode being OFF. client/keyagent.go:409
DEBU [KEYAGENT]  Host validation failed: ssh: no authorities for hostname: example.com:3080. client/keyagent.go:366
DEBU [CLIENT]    Activating relogin on ssh: handshake failed: ssh: no authorities for hostname: example.com:3080. client/api.go:514
DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-01-18 23:09:44 +0000 UTC". client/client_store.go:89
DEBU [CLIENT]    Attempting to login with a new RSA private key. client/api.go:3237
Enter password for Teleport user bot-testplan2:^C
DEBU             Captured signal interrupt, attempting to restore terminal state prompt/context_reader.go:197
```

This works as expected with tsh v11.2.1.

Bug details:
- Teleport version: v12.0.0-alpha.1
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by Joerger**
https://github.com/gravitational/teleport/pull/19420 created two bugs:

1. `tsh -i` could initiate relogin on failure

This PR properly flags when an identity file is in use and relogin should not be initiated.

2. `tsh -i` and `tctl -i` would fail to create ssh connections with identity files created by `tbot` and `tctl`, because the known hosts in these identity files do not include the proxy host as a host name. e.g:
```
@cert-authority root-cluster,*.root-cluster ssh-rsa AAAA... type=host
versus 
@cert-authority proxy.example.com,root-cluster,*.root-cluster ssh-rsa AAAA... type=host
```

This PR updates `KeyFromIdentityFile` to properly use all known hosts in the identity file, even when the proxy host is not set.

Closes https://github.com/gravitational/teleport/issues/20373

### CODE REVIEW

**Review by fspmarshall — APPROVED** [review]

**Comment by Joerger** [comment]
Friendly reminder @hugoShaka

File: lib/client/identityfile/identity_test.go [hunk 1]
```diff
@@ -330,13 +329,18 @@ func TestKeyFromIdentityFile(t *testing.T) {
 	})
 	require.NoError(t, err)
 
+	proxyHost := "proxy.example.com"
+	cluster := "cluster"
```
Comment (jakule) [inline lib/client/identityfile/identity_test.go:333]: nit:
```suggestion
	const proxyHost = "proxy.example.com"
	const cluster = "cluster"
```

**Review by jakule — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Review by AntonAM — APPROVED** [review]
