### PR TITLE
Fix removing resources from access request when they share the same name

### LINKED ISSUE #42352: Can't remove resources from access request in Connect when they share the same name but come from different clusters
https://github.com/gravitational/teleport/assets/27113/30e92b81-c942-4fbc-b12c-c90fe5303029

To recreate it, add two resources to an access request that have the same name and type but one comes from a root cluster and the other from a leaf cluster.

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/42352

Removing resources with the same name did not work, because when converting a “shared” access request to a “Connect” access request, we always passed the active cluster URI, not the URI of the cluster to which the resource belonged.
To fix this, I allowed extending the object passed to `data` in `RequestCheckout`, so we can keep the original items there. 
Another benefit of that is that we no longer have to convert the "shared" request to "Connect" request.

I also added some improvements:
* cluster name is shown in the checkout if there's a resource from a leaf cluster,
* we no longer show an unformatted resource kind in the checkout.

### CODE REVIEW

File: web/packages/design/src/DataTable/types.ts [hunk 1]
```diff
@@ -105,7 +105,7 @@ export type ServersideProps = {
 
 // Makes it so either key or altKey is required
 type TableColumnWithKey<T> = TableColumnBase<T> & {
-  key: Extract<keyof T, string>;
+  key: keyof T & string;
```
Comment (gzdunek) [inline web/packages/design/src/DataTable/types.ts:108]: The previous version was causing errors after I changed the type passed to the request checkout table from (roughly) `PendingListItem` to  `T extends PendingListItem`. 
The error was:
image

I believe the new version works the same and the issue is gone.

File: web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts [hunk 2]
```diff
@@ -385,3 +375,13 @@ export default function useAccessRequestCheckout() {
...
+
+type PendingListItemWithOriginalItem = Omit<PendingListItem, 'kind'> & {
+  kind: ResourceKind;
+  originalItem:
+    | {
+        kind: 'role';
+        role: string;
+      }
+    | { kind: 'resource'; resource: ResourceRequest };
+};
```
Comment (ravicious) [inline web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts:396]: Something like this maybe?

```typescript
type PendingListItemWithOriginalItem = Omit<PendingListItem, 'kind'> &
  (
    | {
        kind: Exclude<ResourceKind, 'role'>;
        originalItem: ResourceRequest;
      }
    | {
        kind: 'role';
      }
  );
```

<details>
<summary>Patch</summary>

```diff
diff --git a/web/packages/teleterm/src/ui/AccessRequestCheckout/AccessRequestCheckout.tsx b/web/packages/teleterm/src/ui/AccessRequestCheckout/AccessRequestCheckout.tsx
index b676138087..5e2678e967 100644
--- a/web/packages/teleterm/src/ui/AccessRequestCheckout/AccessRequestCheckout.tsx
+++ b/web/packages/teleterm/src/ui/AccessRequestCheckout/AccessRequestCheckout.tsx
@@ -160,7 +160,7 @@ export function AccessRequestCheckout() {
                       case 'role':
                         break;
                       default:
-                        c.kind satisfies never;
+                        c satisfies never;
                     }
                     return resource;
                   })
diff --git a/web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts b/web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
index 2050888705..a6ec0516c8 100644
--- a/web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
+++ b/web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts
@@ -170,10 +170,6 @@ export default function useAccessRequestCheckout() {
             id: role,
             name: role,
             clusterName,
-            originalItem: {
-              kind: 'role',
-              role: role,
-            },
           });
         });
         break;
@@ -186,7 +182,7 @@ export default function useAccessRequestCheckout() {
             kind,
             id,
             name,
-            originalItem: { kind: 'resource', resource: resourceRequest },
+            originalItem: resourceRequest,
             clusterName: ctx.clustersService.findClusterByResource(
               resourceRequest.resource.uri
             )?.name,
@@ -204,15 +200,17 @@ export default function useAccessRequestCheckout() {
     return workspaceAccessRequest.getCollapsed();
   }
 
-  async function toggleResource({
-    originalItem,
-  }: PendingListItemWithOriginalItem) {
-    if (originalItem.kind === 'role') {
-      await workspaceAccessRequest.addOrRemoveRole(originalItem.role);
+  async function toggleResource(
+    pendingListItem: PendingListItemWithOriginalItem
+  ) {
+    if (pendingListItem.kind === 'role') {
+      await workspaceAccessRequest.addOrRemoveRole(pendingListItem.id);
       return;
     }
 
-    await workspaceAccessRequest.addOrRemoveResource(originalItem.resource);
+    await workspaceAccessRequest.addOrRemoveResource(
+      pendingListItem.originalItem
+    );
   }
 
   function getAssumedRequests() {
@@ -385,12 +383,13 @@ export default function useAccessRequestCheckout() {
   };
 }
 
-type PendingListItemWithOriginalItem = Omit<PendingListItem, 'kind'> & {
-  kind: ResourceKind;
-  originalItem:
+type PendingListItemWithOriginalItem = Omit<PendingListItem, 'kind'> &
+  (
+    | {
+        kind: Exclude<ResourceKind, 'role'>;
+        originalItem: ResourceRequest;
+      }
     | {
         kind: 'role';
-        role: string;
       }
-    | { kind: 'resource'; resource: ResourceRequest };
-};
+  );

```
</details>

It's not ideal, because you can still write code like this:

```typescript
const node: PendingListItemWithOriginalItem = {
  kind: 'node',
  id: 'foo',
  name: 'bar',
  clusterName: 'hello',
  originalItem: { kind: 'database', resource: { uri: '' } }
}
```

But at least it rules out code like this:

```typescript
const item: PendingListItemWithOriginalItem = {
  kind: 'node',
  id: 'foo',
  name: 'bar',
  clusterName: 'hello',
  originalItem: { kind: 'role', role: 'baz' },
};
```

File: web/packages/design/src/DataTable/types.ts (hunk 1 above)
Comment (ravicious) [reply web/packages/design/src/DataTable/types.ts:108]: I'm not sure what `Extract<keyof T, string>` does. `keyof T` extracts keys from `T` and those keys themselves already are strings (I think). I tried removing it but I got lost.

**Review by ravicious — COMMENTED** [review]
I'll continue the review tomorrow.

File: web/packages/design/src/DataTable/types.ts (hunk 1 above)
Comment (ravicious) [reply web/packages/design/src/DataTable/types.ts:108]: It seems that it was likely introduced due to this error you get after removing it:

```
Type 'string | number | symbol' is not assignable to type 'string'.
  Type 'number' is not assignable to type 'string'
```

But I think the solution is to clean up how those types are defined, particularly `TableColumnWithKey<T>` and `TableColumnWithAltKey<T>`.

**Review by avatus — APPROVED** [review]
Works for me 👍

File: web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts (hunk 2 above)
Comment (gzdunek) [reply web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts:396]: That's better, thanks.

File: web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx [hunk 3]
```diff
@@ -623,6 +627,29 @@ function TextBox({
...
+    case 'db':
+      return 'Database';
+    case 'kube_cluster':
+      return 'Kubernetes';
+    case 'user_group':
+      return 'User Group';
+    case 'windows_desktop':
+      return 'Desktop';
+    default:
+      kind satisfies never;
```
Comment (ravicious) [inline web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx:649]:
```suggestion
      kind satisfies never;
      return kind;
```

In this scenario, I think it's hard to say what the source of truth for those kinds is and if it's always going to be in sync with types. Since this function returns a value that's meant for display purposes only, we can return regular `kind` to be safe.

File: web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx [hunk 4]
```diff
@@ -250,6 +251,11 @@ export function RequestCheckout<T extends PendingListItem>({
                     key: 'name',
                     headerText: 'Name',
                   },
+                  {
+                    key: 'clusterName',
+                    headerText: 'Cluster Name',
+                    isNonRender: !showClusterNameColumn,
+                  },
```
Comment (ravicious) [inline web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx:261]: The Web UI shows the cluster name as the first column when you go see details of an access request. Would it make sense to show it as the first column here as well?

File: web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx [hunk 5]
```diff
@@ -623,6 +627,29 @@ function TextBox({
...
+    case 'app':
+      return 'Application';
+    case 'node':
+      return 'Server';
+    case 'resource':
+      return 'Resource';
+    case 'db':
+      return 'Database';
+    case 'kube_cluster':
+      return 'Kubernetes';
```
Comment (ravicious) [inline web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx:643]:
```suggestion
      return 'Kube cluster';
```

`tsh kube ls` uses this as a column name as well.

**Review by ravicious — APPROVED** [review]

File: web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx (hunk 5 above)
Comment (gzdunek) [reply web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx:643]: I decided to use `Kubernetes` because in the unified resources we use this name, so I thought that it would be consistent: 
image
WDYT?

Comment (ravicious) [reply web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/RequestCheckout.tsx:643]: Oh, in that case I guess it's okay. I didn't realize that there are other places which use plain "Kubernetes" already.
