### PR TITLE
Set the key id in JWT

### LINKED ISSUE #44245: JWT Missing KID Claim Results in Verification Issue
### Expected behavior:
JWTs provided by Teleport should include a Key ID (KID) in accordance with RFC 7517 to allow systems to identify the specific key used to sign the token.

While the `Kid` field is optional in [RFC 7517](https://datatracker.ietf.org/doc/html/rfc7517#section-4.5), it should be included in cases where multiple keys may appear in the corresponding JWKS.

### Current behavior:

JWTs generated by Teleport do not include the KID claim. If I bring up an older version of Teleport, I see only one entry in the `.well-known/jwks.json` response. It has its `"kid":` set to a blank string. In more recent versions of Teleport, it looks like it populates the JWKS with two copies of the key. One that has `"kid":` set to a blank string, and one that has a "kid" populated.

<details><summary>edit: removed incorrect theory</summary>

~~I believe this may have been introduced by https://github.com/gravitational/teleport/pull/39489 (15.1.9) / https://github.com/gravitational/teleport/pull/39490 (14.3.12), but I wasn't able to confirm this for sure.~~

edit: the previous version they were running was 14.3.19, so this suspected change is not the root cause.

</details>

Additionally, while a CA rotation is in progress, the jwks.json response should return both the old and the new key. The JWT should include the corresponding kid in that scenario as well. I didn't test a CA rotate condition, but I believe this would result in a similar failure.

To reproduce, try to verify a JWT with a library that will throw an error if the JWT does not include the key ID, and the jwks.json is returning two keys.

This was reported after upgrading to 15.4.7 from 14.3.19

This is the library that was in use when the issue was encountered: https://www.npmjs.com/package/jwks-rsa

I had ChatGPT help write a small debug tool that can reproduce this error.

<details><summary>server.js</summary>

`npm install express jwks-rsa jsonwebtoken`

```javascript
const express = require('express');
const jwksClient = require('jwks-rsa');
const jwt = require('jsonwebtoken');

const app = express();
const port = 3000;

// Configure the JWKS client
const client = jwksClient({
  jwksUri: 'https://teleport.example.com/.well-known/jwks.json',
  requestHeaders: {}, // Optional
  timeout: 30000 // Defaults to 30s
});

// Function to get the signing key
const getKey = (header, callback) => {
  console.log('Getting signing key for kid:', header.kid);
  client.getSigningKey(header.kid, (err, key) => {
    if (err) {
      console.log('Error getting signing key:', err);
      callback(err);
    } else {
      const signingKey = key.getPublicKey();
      console.log('Signing key retrieved:', signingKey);
      console.log('JWKS:', key);
      callback(null, signingKey);
    }
  });
};

app.get('/', (req, res) => {
  console.log('Received request');
  // Display all HTTP header values
  const headers = req.headers;
  console.log('Request headers:', headers);
  const jwtToken = headers['teleport-jwt-assertion'];
  let responseHtml = '<h1>HTTP Headers</h1><pre>' + JSON.stringify(headers, null, 2) + '</pre>';

  // If the JWT is present, decode it
  if (jwtToken) {
    console.log('JWT found:', jwtToken);

    // Decode without verification
    const decodedWithoutVerification = jwt.decode(jwtToken, { complete: true });
    console.log('Decoded JWT without verification:', decodedWithoutVerification);
    responseHtml += '<h2>Decoded JWT without verification</h2><pre>' + JSON.stringify(decodedWithoutVerification, null, 2) + '</pre>';

    jwt.verify(jwtToken, getKey, { algorithms: ['RS256'] }, (err, decoded) => {
      if (err) {
        console.log('JWT verification error:', err);
        responseHtml += '<h2>JWT Decoding Error</h2><pre>' + JSON.stringify(err, Object.getOwnPropertyNames(err), 2) + '</pre>';
      } else {
        console.log('JWT decoded:', decoded);
        responseHtml += '<h2>Decoded JWT</h2><pre>' + JSON.stringify(decoded, null, 2) + '</pre>';
      }
      res.send(responseHtml);
    });
  } else {
    console.log('No JWT found in Teleport-Jwt-Assertion header');
    responseHtml += '<h2>No JWT found in Teleport-Jwt-Assertion header</h2>';
    res.send(responseHtml);
  }
});

app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}/`);
});
```

</details>

On my test cluster running 15.4.9, I have a `/.well-known/jwks.json` that returns two keys. This server.js will display this error:

```
JsonWebTokenError: error in secret or public key callback: No KID specified and JWKS endpoint returned more than 1 key
```

### PR DESCRIPTION
**Pull request by programmerq**
Some JWT libraries panic with multiple keys present in the JWKS. A second JWKS key entry was added in #40998

Fixes #44245

### CODE REVIEW

File: lib/jwt/jwt.go [hunk 1]
```diff
@@ -216,7 +216,15 @@ func (k *Key) Sign(p SignParams) (string, error) {
...
-	return k.sign(claims, nil)
+	// grab the key id
+	publicKey := k.config.PublicKey
+	kid, _ := KeyID(publicKey)
+
+	// RFC 7517 requires that `kid` be present in the JWT header if there are multiple keys in the JWKS.
+	// go-jose will explicitly omit the `kid` if it is set to an empty string.
+	opts := (&jose.SignerOptions{}).
+		WithHeader(jose.HeaderKey("kid"), kid)
+	return k.sign(claims, opts)
```
Comment (zmb3) [inline lib/jwt/jwt.go:227]:
```suggestion
	// RFC 7517 requires that `kid` be present in the JWT header if there are multiple keys in the JWKS.
	// We ignore the error because go-jose omits the kid if it is empty.
	kid, _ := KeyID(k.config.PublicKey)
	return k.sign(claims, WithHeader(jose.HeaderKey("kid"), kid)
```

**Review by zmb3 — APPROVED** [review]
Thanks Jeff!

**Review by marcoandredinis — APPROVED** [review]

File: lib/jwt/jwt.go (hunk 1 above)
Comment (zmb3) [reply lib/jwt/jwt.go]: @programmerq it looks like this change somehow got reverted prior to merging the PR.

**Comment by programmerq** [comment]
The automatic backports failed due to differences in the master branch for the work done as part of the 17.x [modern signature algorithm](https://github.com/gravitational/teleport/blob/a9c6dba236c387cd1fa140b3e6668fdb1b490e52/docs/pages/upcoming-releases.mdx#modern-signature-algorithms) work.

Manual backports for 16.x and 15.x are still feasible.
