### PR TITLE
Web-Discover: Add support for connection testers with per-session MFA enabled

### LINKED ISSUE #16702: Teleport discover fails to connect when existing roles require MFA
Hi Team,

I have followed new teleport discover flow on the existing account.

I have created a new principal `user` on the screen that asked for new SSH logins.

When I tried to test the connection it failed:

logicoma

Also, for some reason it added principal `user` twice. I assume It has discovered principal `user` on my host, and I added another one. But it should check for duplicates.

### PR DESCRIPTION
**Pull request by kimlisa**
resolves https://github.com/gravitational/teleport/issues/16702

#### Description
Implements the frontend part of [RFD 0111](https://github.com/gravitational/teleport/pull/22458)
backend here: https://github.com/gravitational/teleport/pull/22528

Before connection testing, we check if MFA is required.
If required:
- we render a MFA dialog that asks user to provide MFA credentials
- take this response and send it with the test connection request

Only supported for resource type `node`, `kube`, and `database` (no support for windows desktops yet)

#### Testing
Manually tested for a node, kube, and a database resource with a user assigned a role with `option.require_session_mfa: true`

If you want to test run yourself, this PR has all it needs, or I have a cloud cluster already running with changes if interested

#### Demo testing connection to a node

https://user-images.githubusercontent.com/43280172/220775608-5691c4e1-eb1c-4526-9f66-c063dd624930.mov

### CODE REVIEW

File: web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts [hunk 1]
```diff
@@ -14,33 +14,44 @@ See the License for the specific language governing permissions and
...
-export default function useReAuthenticate({
-  onAuthenticated,
-  onClose,
-  actionText = defaultActionText,
-}: Props) {
+import type { MfaAuthnResponse } from 'teleport/services/mfa';
+
+export default function useReAuthenticate(props: Props) {
+  const { onClose, actionText = defaultActionText } = props;
   const { attempt, setAttempt, handleError } = useAttempt('');
```
Comment (ibeckermayer) [inline web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts:26]: How does `setAttempt` ever get set to `success` here?

File: web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts [hunk 2]
```diff
@@ -14,33 +14,44 @@ See the License for the specific language governing permissions and
...
 import auth from 'teleport/services/auth';
 
-export default function useReAuthenticate({
-  onAuthenticated,
-  onClose,
-  actionText = defaultActionText,
-}: Props) {
+import type { MfaAuthnResponse } from 'teleport/services/mfa';
+
+export default function useReAuthenticate(props: Props) {
```
Comment (ibeckermayer) [inline web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts:24]: A comment about the distinct prompt shapes and how they change the behavior of the hook would be helpful.

**Review by ibeckermayer — COMMENTED** [review]
Seems like something we should add to the manual test plan.

**Comment by kimlisa** [comment]
@ibeckermayer @ryanclark i made this commit as an example: https://github.com/gravitational/teleport/pull/22529/commits/90e50507bfcfdf08313a0b6c01a0605c5d4c8274, where i am using snake cased fields outside the service layer...

was wondering if that was okay, the conversion of field names just to satisfy JS convention was getting tiring. will change back if requested.

File: web/packages/teleport/src/Discover/Shared/ConnectionDiagnostic/useConnectionDiagnostic.ts [hunk 3]
```diff
@@ -20,55 +20,89 @@ import useAttempt from 'shared/hooks/useAttemptNext';
...
+      // test itself can fail:
+      if (!diag.success) {
+        // Append all possible errors:
+        const errors = diag.traces
+          .filter(trace => trace.status === 'failed')
+          .map(
+            trace => `[${trace.traceType}] ${trace.error} (${trace.details})`
+          )
+          .join('\n');
+        emitErrorEvent(`testing failed: ${errors}`);
```
[the remark this answers is not in the document]
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Shared/ConnectionDiagnostic/useConnectionDiagnostic.ts:93]: no, perhaps this should be renamed to `diagnosis failed: ...`. the `handleError` is for non-200 codes. this block of code means the request itself is 200 (success), but the diagnosis resulted in error (we tried to connect to resource, but couldn't), hope that made sense

File: web/packages/teleport/src/Discover/Shared/ConnectionDiagnostic/useConnectionDiagnostic.ts [hunk 4]
```diff
@@ -20,55 +20,89 @@ import useAttempt from 'shared/hooks/useAttemptNext';
...
   const canTestConnection = access.create && access.edit && access.read;
 
-  function runConnectionDiagnostic(req: ConnectionDiagnosticRequest) {
+  const [showMfaDialog, setShowMfaDialog] = useState(false);
+
+  // runConnectionDiagnostic will initially make a call to check if
+  // resource target requires MFA authentication. After this initial
+  // check depending on if user successfully authenticated or not (
+  // determined by the presence of the token field), will make a call
+  // to test connection.
```
[the remark this answers is not in the document]
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Shared/ConnectionDiagnostic/useConnectionDiagnostic.ts:50]: i found your explanation confusing, so i cleared it up like this (i try to follow golang convention commenting so i don't have to think too hard when switching):

```
  // runConnectionDiagnostic depending on the value of `mfaAuthnResponse` does the following:
  //   1) If param `mfaAuthnResponse` is undefined or null, it will check if MFA is required.
  //      - If MFA is required, it sets a flag that indicates a users
  //        MFA credentials are required, and skips the request to test connection.
  //      - If MFA is NOT required, it makes the request to test connection.
  //   2) If param `mfaAuthnResponse` is defined, it skips checking if MFA is required,
  //      and makes the request to test connection.
```

File: web/packages/teleport/src/Discover/Shared/ConnectionDiagnostic/useConnectionDiagnostic.ts [hunk 5]
```diff
@@ -20,55 +20,89 @@ import useAttempt from 'shared/hooks/useAttemptNext';
...
+  //
+  // Each test connection request will require a MFA check since the
+  // fields for the request may have changed eg: for nodes, the login
+  // field may change.
```
[the remark this answers is not in the document]
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Shared/ConnectionDiagnostic/useConnectionDiagnostic.ts:54]: I deleted this comment. i put it there because i made the initial mistake thinking that one request to `IsMFARequired` was all we needed, but in fact, each request for test connection required its own check because a user can change the request fields to test out different combos for the same resource: https://github.com/gravitational/teleport/blob/b798144dbb1ceaea1e29c256f294bbd8ddc893eb/lib/auth/auth.go#L4082

File: web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts (hunk 1 above)
Comment (kimlisa) [reply web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts:26]: it doesn't or rather it's not necessary. i think this component was created in such that after a successful "submit" the control is passed back to the parent (with the `onAuthenticate` or `onMfaReponse` func). I thought it made sense b/c there shouldn't be anything else that needs to be done after user submits. Perhaps it would've made more sense to call `onClose` before `onAuthenticate/onMfaResponse`. So if we are closing the dialog, it's clearer that we don't need anything to re-render, which is the purpose of `setAttempt(success)`

**Comment by kimlisa** [comment]
> Seems like something we should add to the manual test plan.

I will do this in another PR. there is a lot that needs to be added/updated in the test plan

File: web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts [hunk 6]
```diff
@@ -90,4 +113,23 @@ export type Props = {
...
+type MfaResponseProps = BaseProps & {
+  onMfaResponse(res: MfaAuthnResponse): void;
+  onAuthenticated?: never;
+};
+
+// Default defines a function that
+// accepts a privilegeTokenId that is only
+// obtained after MFA response has been
+// validated.
+type Default = BaseProps & {
```
Comment (ryanclark) [inline web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts:128]: Can we name this something other than `Default`?

File: web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts (hunk 1 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts:37]: Maybe worth a concise comment explaining this because it's not the standard usage pattern.

**Comment by ibeckermayer** [comment]
> @ibeckermayer @ryanclark i made this commit as an example: [90e5050](https://github.com/gravitational/teleport/commit/90e50507bfcfdf08313a0b6c01a0605c5d4c8274), where i am using snake cased fields outside the service layer...
> 
> was wondering if that was okay, the conversion of field names just to satisfy JS convention was getting tiring. will change back if requested.
> 
> context: [#22528 (comment)](https://github.com/gravitational/teleport/pull/22528#discussion_r1127075475)

My preference is that we change the backend's responses to use `camelCase` like you and Alexey were doing. AFAIK the web endpoints are all only used by the web client, and so there's no good reason not to tailor them for the web client in a way that reduces boilerplate.

I'd prefer to avoid doing it ad-hoc like this, as it will make the pattern inconsistent and therefore more difficult to change to the correct solution, whatever that is.

File: web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts (hunk 6 above)
Comment (kimlisa) [reply web/packages/teleport/src/components/ReAuthenticate/useReAuthenticate.ts]: asked discussed in call, renamed to `DefaultProps`

**Comment by kimlisa** [comment]
> My preference is that we change the backend's responses to use `camelCase` like you and Alexey were doing. AFAIK the web endpoints are all only used by the web client, and so there's no good reason not to tailor them for the web client in a way that reduces boilerplate.

Pushing for camel consistency is a losing battle b/c we have a lot more devs touching the web layer. Hard to reinforce camel when everything else is snaked so folks will naturally default to snake.

> I'd prefer to avoid doing it ad-hoc like this, as it will make the pattern inconsistent and therefore more difficult to change to the correct solution, whatever that is.

Most devs will default to snake, so if we all get onboard, eventually it'll become consistent? 🥲  But the correct solution is to transition into grpc.

Btw, I double checked that ryan was okay with my approach.

**Review by ibeckermayer — APPROVED** [review]

**Review by avatus — APPROVED** [review]

**Review by ryanclark — APPROVED** [review]
