### PR TITLE
Fix ALPN ping connection compilation and test flakiness.

### LINKED ISSUE #15867: `TestPingConnection` panic
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/800e3022-7448-4998-a9c9-ab56333703ed;step=0?project=ci-account

#### Relevant snippet

```
=== RUN   TestPingConnection/ConcurrentReads
time="2022-08-26T17:12:35Z" level=info msg="Generating TLS certificate {0x794f568 0xc001074660 CN=test-user,POSTALCODE=null,STREET= 2022-08-26 17:13:35.918079471 +0000 UTC [localhost *.localhost] [] 5 []}." common_name=test-user dns_names="[localhost *.localhost]" locality="[]" not_after="2022-08-26 17:13:35.918079471 +0000 UTC" org="[]" org_unit="[]" trace.component=ca
    --- FAIL: TestPingConnection/ConcurrentReads (5.00s)
panic: interface conversion: interface {} is []uint8, not string [recovered]
	panic: interface conversion: interface {} is []uint8, not string

goroutine 311 [running]:
testing.tRunner.func1.2({0x41df200, 0xc000b04180})
	/opt/go/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
	/opt/go/src/testing/testing.go:1392 +0x5d2
panic({0x41df200, 0xc000b04180})
	/opt/go/src/runtime/panic.go:844 +0x258
github.com/stretchr/testify/assert.messageFromMsgAndArgs({0xc000adbe78, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:191 +0x1aa
github.com/stretchr/testify/assert.Fail({0x7fcf3a728ab8, 0xc000e88680}, {0x45f7b53, 0x37}, {0xc000adbe78, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:257 +0x271
github.com/stretchr/testify/require.Fail({0x5694ea0, 0xc000e88680}, {0x45f7b53, 0x37}, {0xc000adbe78, 0x2, 0x2})
	/go/pkg/mod/github.com/stretchr/testify@v1.7.1/require/require.go:412 +0xa5
github.com/gravitational/teleport/lib/srv/alpnproxy.TestPingConnection.func2(0x0?)
	/workspace/lib/srv/alpnproxy/conn_test.go:163 +0x734
testing.tRunner(0xc000e88680, 0x46ae430)
	/opt/go/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/opt/go/src/testing/testing.go:1486 +0x725
===================================================
Makefile:520: recipe for target 'test-go' failed
make: *** [test-go] Error 1
```

### PR DESCRIPTION
**Pull request by gabrielcorado**
Closes #15867 by checking the message size instead of its content to guarantee all concurrent reads are being performed correctly. This change makes the test more predictable since the reads are being performed concurrently, and the content produced in the result channel could be out-of-order (causing the test to fail).

This PR also removes the `math.MaxUint32` cast to `int` by casting:
1. [Casting result of `len` to `uint64` on the comparison;](https://github.com/gravitational/teleport/pull/15878/files#diff-6b320f4958aa2d3da9a7623cabc1ce98ca6191721e554bb0ab12231ad8fdef9bR174)
2. [Casting `math.MaxUint32` itself to `uint64` for string formatting;](https://github.com/gravitational/teleport/pull/15878/files#diff-6b320f4958aa2d3da9a7623cabc1ce98ca6191721e554bb0ab12231ad8fdef9bR175)

This change avoid the compiler to fail with:
```
cannot use math.MaxUint32 - 1 (untyped int constant 4294967294) as int value
```

### CODE REVIEW

File: lib/srv/alpnproxy/conn.go [hunk 1]
```diff
@@ -168,13 +167,6 @@ func (c *PingConn) Write(p []byte) (int, error) {
 	c.muWrite.Lock()
 	defer c.muWrite.Unlock()
 
-	// Avoid overflow when casting data length. It is only present to avoid
-	// panicking if the size cannot be cast. Callers should handle packet length
-	// limits, such as protocol implementations and audits.
-	if len(p) > math.MaxUint32 {
```
Comment (codingllama) [inline lib/srv/alpnproxy/conn.go:174]: I suppose `len(p)` can't be bigger than an `uint32` if int==int32, but isn't the overflow if int==int64?

Is this useful: `if uint64(len(p)) > math.MaxUint32 {` ?

File: lib/srv/alpnproxy/conn_test.go [hunk 2]
```diff
@@ -143,8 +145,8 @@ func TestPingConnection(t *testing.T) {
 				buf := make([]byte, len(dataWritten)/2)
 				for {
 					n, err := r.Read(buf)
-					if err != nil {
-						return
+					if err != nil && !errors.Is(err, io.EOF) {
+						require.Fail(t, "failed to read from connection")
```
Comment (codingllama) [inline lib/srv/alpnproxy/conn_test.go:149]:
```suggestion
						require.Fail(t, "Failed to read from connection: %v", err)
```

File: lib/srv/alpnproxy/conn_test.go [hunk 3]
```diff
@@ -154,20 +156,18 @@ func TestPingConnection(t *testing.T) {
...
 
-	readLoop:
 		for i := 0; i < nWrites; i++ {
 			var aggregator []byte
-			for {
+			for j := 0; j < 3; j++ {
 				select {
 				case <-ctx.Done():
-					require.Fail(t, "failed to read message, expected '%v' but received '%v'", dataWritten, aggregator)
+					require.Fail(t, "failed to read message")
```
Comment (codingllama) [inline lib/srv/alpnproxy/conn_test.go:164]: nit:

```suggestion
					require.Fail(t, "Failed to read message (context timeout)")
```

File: lib/srv/alpnproxy/conn_test.go [hunk 4]
```diff
@@ -154,20 +156,18 @@ func TestPingConnection(t *testing.T) {
...
 				case data := <-readChan:
 					aggregator = append(aggregator, data...)
-					if bytes.Equal(dataWritten, aggregator) {
-						continue readLoop
-					}
 				}
 			}
+
+			require.Len(t, aggregator, len(dataWritten))
```
Comment (codingllama) [inline lib/srv/alpnproxy/conn_test.go:170]: Please add a message here with a brief explanation of what the failure means.

**Review by codingllama — COMMENTED** [review]
Thanks for the quick fix!

File: lib/srv/alpnproxy/conn.go (hunk 1 above)
Comment (gabrielcorado) [reply lib/srv/alpnproxy/conn.go:174]: > I suppose `len(p)` can't be bigger than an `uint32` if int==int32, but isn't the overflow if int==int64?

Yes, you're right, that's why I initially added this check.

> Is this useful: `if uint64(len(p)) > math.MaxUint32 {` ?

I've tried something along these lines. This works because we're comparing two `uint64` numbers capable of handling values greater than `MaxUInt32`. I felt this check might be a little hacky, but it is better than having nothing. I'm going to add it back. Thanks!

File: lib/srv/alpnproxy/conn.go [hunk 5]
```diff
@@ -171,8 +171,8 @@ func (c *PingConn) Write(p []byte) (int, error) {
 	// Avoid overflow when casting data length. It is only present to avoid
 	// panicking if the size cannot be cast. Callers should handle packet length
 	// limits, such as protocol implementations and audits.
-	if len(p) > math.MaxUint32 {
-		return 0, trace.BadParameter("invalid content size, max size permitted is %d", math.MaxUint32)
+	if uint64(len(p)) > math.MaxUint32 {
+		return 0, trace.BadParameter("invalid content size, max size permitted is %d", uint64(math.MaxUint32))
```
Comment (codingllama) [inline lib/srv/alpnproxy/conn.go:175]: nit: Is the cast necessary?

```suggestion
		return 0, trace.BadParameter("invalid content size, max size permitted is %d", math.MaxUint32)
```

**Review by codingllama — APPROVED** [review]
LGTM.

File: lib/srv/alpnproxy/conn_test.go [hunk 6]
```diff
@@ -154,20 +156,18 @@ func TestPingConnection(t *testing.T) {
 			}()
 		}
 
-	readLoop:
 		for i := 0; i < nWrites; i++ {
 			var aggregator []byte
-			for {
+			for j := 0; j < 3; j++ {
```
Comment (jakule) [inline lib/srv/alpnproxy/conn_test.go:161]: nit: Can you add a comment why 3 or even better, create a constant with some meaningful name?

**Review by jakule — APPROVED** [review]

File: lib/srv/alpnproxy/conn.go (hunk 5 above)
Comment (gabrielcorado) [reply lib/srv/alpnproxy/conn.go:175]: Yeah, it complains the same way as the line above. I think it is because `%d` considers the input as `int`.

File: lib/srv/alpnproxy/conn.go (hunk 1 above)
Comment (codingllama) [reply lib/srv/alpnproxy/conn.go:174]: Oh, right. Use `%v` and drop the cast?

File: lib/srv/alpnproxy/conn.go (hunk 5 above)
Comment (codingllama) [reply lib/srv/alpnproxy/conn.go:175]: Oh, right. Use %v and drop the cast?

Comment (gabrielcorado) [reply lib/srv/alpnproxy/conn.go:175]: It still complains, it might be because this constant is untyped and is being cast by default to `int`.
