### PR TITLE
Inline IronRDP WASM Module

### LINKED ISSUE #63412: Desktop Access: Desktop Sessions May Fail to Connect During Cluster Upgrade
Expected behavior:
During a cluster upgrade, opening new desktop sessions should work as normal.

Current behavior:
When Proxy service instances live behind a load balancer, desktop sessions can fail to start if they end up fetching the WASM module from a different proxy. They appear to hang indefinitely during connection initialization, but opening browser developer tools reveals an error.

Image

Bug details:
- Teleport version:
Proxy instance A: `v17.7.16`, Proxy instance B: `branch/v18`
- Recreation steps
Set up a simple, local cluster with one auth server, one windows desktop service, and two proxy instances. Configure a layer 4 proxy of your choice (my environment uses traefik with TLS passthrough) with your proxy instances as backends.
- Debug logs
See screenshot of browser console output above.

### PR DESCRIPTION
**Pull request by rhammonds-teleport**
Currently, our WASM module is fetched separately from our app bundle. When users deploy the proxy behind a load balancer, the app.js bundle and WASM module may be retrieved from separate instances. This is problematic while rolling out a proxy upgrade as the glue code (contained main app.js bundle) and WASM module may be incompatible if we've upgraded our wasm-bindgen dependency, or simply made breaking changes to the WASM module. 

This PR attempts prevent incompatibility issues from arising during upgrades by inlining the WASM module with the main app bundle. This will fix #63412 going forward, but only slightly mitigates the issue for users who need to upgrade.

To prevent any desktop connection failures during upgrades, we'll probably need to backport this PR, plus make some additional change that allow us to serve the WASM module used in the previous release.

### CODE REVIEW

**Review by avatus — APPROVED** [review]
what is the size difference between the wasm binary we fetch, and the one that needs to be `?inline` ? generally that base64 overhead might increase the size quite a bit.

**Comment by rhammonds-teleport** [comment]
> what is the size difference between the wasm binary we fetch, and the one that needs to be `?inline` ? generally that base64 overhead might increase the size quite a bit.

The fetched module weighs about 120kB. Inlined is around 180kB. The overall size of app.js goes from 1094kB to 1277kB.
Is there another inlining/embedding approach that I could take which would reduce the size?

**Comment by avatus** [comment]
> Is there another inlining/embedding approach that I could take which would reduce the size?

no, this is fine. i was just curious of the size implications

File: web/packages/shared/libs/tdp/client.ts [hunk 1]
```diff
@@ -25,6 +25,8 @@ import init, {
   FastPathProcessor,
   init_wasm_log,
 } from 'shared/libs/ironrdp/pkg/ironrdp';
+// Inlines the wasm module as a static asset bundled with our app.
+import wasmUrl from 'shared/libs/ironrdp/pkg/ironrdp_bg.wasm?inline';
```
Comment (ravicious) [inline web/packages/shared/libs/tdp/client.ts:29]: When I run `pnpm build-ui-oss`, I still see `ironrdp_bg.wasm` in the output and in the webassets dir. Is it supposed to work like this?

```
../../../webassets/teleport/app/ironrdp_bg.wasm                                   475.45 kB │ gzip:   160.82 kB
```

Comment (rhammonds-teleport) [reply web/packages/shared/libs/tdp/client.ts:29]: Oh, good find. Looks like Vite keeps it around even though we've told it to inline the module. I'll see if there's a way to force Vite to remove it so we can avoid some bloat.

Comment (rhammonds-teleport) [reply web/packages/shared/libs/tdp/client.ts:29]: Looks like that did the trick. I don't see it in the build output anymore, plus I can no longer fetch it from `<hostname>/web/ironrdp_bg.wasm`.

Comment (ravicious) [reply web/packages/shared/libs/tdp/client.ts:29]: Were you able to find some more details on why a custom plugin is needed in the first place? It seems weird that despite telling Vite to inline a file it can still be found in the output.

File: lib/httplib/httpheaders.go [hunk 2]
```diff
@@ -79,6 +79,7 @@ var defaultContentSecurityPolicy = CSPMap{
 
 var defaultFontSrc = CSPMap{"font-src": {"'self'", "data:"}}
 var defaultConnectSrc = CSPMap{"connect-src": {"'self'", "wss:"}}
+var wasmConnectSrc = CSPMap{"connect-src": {"'self'", "wss:", "data:"}}
```
Comment (ravicious) [inline lib/httplib/httpheaders.go]: How do we know that this is safe? I wasn't able to find much on the internet about the nuances of using `data:` with `connect-src`.

**Review by ravicious — COMMENTED** [review]
Sorry, I should've asked about that CSP addition way sooner! But it feels important to have an answer on that.

File: lib/httplib/httpheaders.go (hunk 2 above)
Comment (ravicious) [reply lib/httplib/httpheaders.go]: There's something on this here, though not in relation to `connect-src` specifically.

https://security.stackexchange.com/questions/94993/is-including-the-data-scheme-in-your-content-security-policy-safe

https://www.w3.org/TR/CSP3/#csp-directives

> In either case, developers SHOULD NOT include either [`'unsafe-inline'`](https://www.w3.org/TR/CSP3/#grammardef-unsafe-inline), or `data:` as valid sources in their policies. Both enable XSS attacks by allowing code to be included directly in the document itself; they are best avoided completely.

Comment (rhammonds-teleport) [reply lib/httplib/httpheaders.go]: Thanks for pushing back on that. It sounds like using `connect-src data:` would've introduced some risk for no good reason. As it turns out, we can actually load the inlined WASM module without having to mess with the CSP. I just needed to spend a little more time researching and iterating. There are surprisingly few people out there who are inlining WASM modules.

Comment (rhammonds-teleport) [reply lib/httplib/httpheaders.go]: > Were you able to find some more details on why a custom plugin is needed in the first place? 

I was hoping someone could tell me 😁. Oddly enough, we have no trouble loading and executing the WASM module if we drop the wasm plugin from our vite config. ... and I still have to include that new deletion plugin in there to keep it from getting included as a static asset.

Comment (ravicious) [reply lib/httplib/httpheaders.go]: > Oddly enough, we have no trouble loading and executing the WASM module if we drop the wasm plugin from our vite config.

That's a good observation. I think the plugin might be needed only if we do import from `.wasm` files directly, but we've never done that – we used to call `init` from `web/packages/shared/libs/ironrdp/pkg/ironrdp.js` which pulls the `.wasm` file manually. The plugin would be needed only if we did a direct import from `.wasm` without `?inline`.

Do you mind adding the removal of the plugin to your todo list? There's very few people who'd be up for doing that since testing this feature involves having a Windows desktop added to your cluster – I suspect very few people have it set up. 😅

File: web/packages/build/vite/config.ts [hunk 3]
```diff
@@ -88,6 +103,7 @@ export function createViteConfig(
         generateAppHashFile(outputDirectory, ENTRY_FILE_NAME),
         wasm(),
       ],
+      assetsInclude: ['**/shared/libs/ironrdp/**/*.wasm'],
```
Comment (ravicious) [inline web/packages/build/vite/config.ts:106]: I tried removing this since it seemed unnecessary as we already do an explicit inline in `web/packages/shared/libs/tdp/client.ts`. But without it Vite actually fails so I guess it has to be there. 🫩

```
error during build:
../../../web/packages/shared/libs/ironrdp/pkg/ironrdp_bg.wasm?inline (1:0): Unexpected character '\0' (Note that you need plugins to import files that are not JavaScript)
file: /Users/m/src/teleport/web/packages/shared/libs/ironrdp/pkg/ironrdp_bg.wasm?inline:1:0
```

File: web/packages/shared/libs/tdp/client.ts (hunk 1 above)
Comment (ravicious) [inline web/packages/shared/libs/tdp/client.ts:29]: FWIW, on my machine inlining the WASM module incresease the gzipped size of app.js by ~228 kB (the number is just a tiny bit different for OSS vs ent). But it also means that the teleport binary is smaller by 160 kB which is the size of that gzipped .wasm file.

**Review by ravicious — APPROVED** [review]
I tested this by compiling the teleport binary and then accessing a Windows desktop.

File: web/packages/build/vite/config.ts [hunk 4]
```diff
@@ -79,6 +79,21 @@ export function createViteConfig(
             // this will remove hashing from asset (non-js) files.
             assetFileNames: `app/[name].[ext]`,
           },
+          plugins: [
+            {
+              // The wasm module is embedded into the main app earlier in the build.
+              // Exclude it here, otherwise rollup still emits it as a static asset
+              // by default.
+              name: 'drop-wasm-assets',
```
Comment (ravicious) [inline web/packages/build/vite/config.ts:87]: TBH, we might want to add this plugin only in v20. Say we merge it now and it lands in v18.7. If the v18.6 frontend app sends a request for the .wasm file and it gets routed to a v18.7 proxy, the proxy will not be able to find the .wasm file.

Comment (rhammonds-teleport) [reply web/packages/build/vite/config.ts:87]: Yep! I was planning doing just that. I have a notion page (which needs updating now that we don't have CSP issues) where I've been documenting this issue and a proposed upgrade strategy.

Once we backport this change to v17 and v18 (keeping the fetch-able module around), minor/point upgrades will work fine. We got kind of lucky in that the last breaking WASM update happened across a major version update. For users upgrading from v17 -> v18, they'll need to make a pit stop on v17.x.y (wherever this lands) before proceeding to v18.  Same with v18 -> v19. Once a cluster picks up this inlining change, future upgrades will be fine.

**Comment by nklaassen** [comment]
@rhammonds-teleport I think this broke `pnpm start-term` locally

```
12:58:10 p.m. [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .wasm?inline file format, or if it's an asset, add "**/*.wasm?inline" to `assetsInclude` in your configuration.
  Plugin: vite:import-analysis
  File: /Users/nic/src/vnet/web/packages/shared/libs/ironrdp/pkg/ironrdp_bg.wasm?inline
      at TransformPluginContext._formatLog (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:28999:43)
      at TransformPluginContext.error (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:28996:14)
      at TransformPluginContext.transform (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:27082:10)
      at async EnvironmentPluginContainer.transform (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:28797:14)
      at async loadAndTransform (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:22670:26)
      at async viteTransformMiddleware (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:24542:20)
```

**Comment by rhammonds-teleport** [comment]
> @rhammonds-teleport I think this broke `pnpm start-term` locally
> 
> ```
> 12:58:10 p.m. [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .wasm?inline file format, or if it's an asset, add "**/*.wasm?inline" to `assetsInclude` in your configuration.
>   Plugin: vite:import-analysis
>   File: /Users/nic/src/vnet/web/packages/shared/libs/ironrdp/pkg/ironrdp_bg.wasm?inline
>       at TransformPluginContext._formatLog (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:28999:43)
>       at TransformPluginContext.error (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:28996:14)
>       at TransformPluginContext.transform (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:27082:10)
>       at async EnvironmentPluginContainer.transform (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:28797:14)
>       at async loadAndTransform (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:22670:26)
>       at async viteTransformMiddleware (file:///Users/nic/src/vnet/node_modules/.pnpm/vite@7.3.1_@types+node@24.10.9_jiti@2.6.1_yaml@2.8.2/node_modules/vite/dist/node/chunks/config.js:24542:20)
> ```

Thanks @nklaassen, I've opened #63997 to update our Vite configuration for teleterm.
