### PR TITLE
Fix `TestHeadlessAuthenticationWatcher` flakiness

### LINKED ISSUE #24409: `TestHeadlessAuthenticationWatcher ` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4670024507/jobs/8269249576

#### Relevant snippet

```
--- FAIL: TestHeadlessAuthenticationWatcher (0.04s)
{"caller":"local/headlessauthn_watcher.go:144","component":null,"error":"context canceled","level":"debug","message":"Context closed with err. Returning from watch loop.","timestamp":"2023-04-11T17:00:52Z"}
{"caller":"backend/buffer.go:280","component":"buffer","level":"debug","message":"Removing watcher 0xc0005b4300 via external close.","timestamp":"2023-04-11T17:00:52Z"}
===================================================
OUTPUT github.com/gravitational/teleport/lib/services/local.TestHeadlessAuthenticationWatcher/WaitEventWithConditionUnmet
===================================================
=== RUN   TestHeadlessAuthenticationWatcher/WaitEventWithConditionUnmet
=== PAUSE TestHeadlessAuthenticationWatcher/WaitEventWithConditionUnmet
=== CONT  TestHeadlessAuthenticationWatcher/WaitEventWithConditionUnmet
    headlessauthn_watcher_test.go:123: Watcher never received an event
--- FAIL: TestHeadlessAuthenticationWatcher/WaitEventWithConditionUnmet (0.51s)
```

### PR DESCRIPTION
**Pull request by Joerger**
After repeatedly getting `TestHeadlessAuthenticationWatcher` flakiness and mistakenly just shifting the problem around, I decided this time to restructure the headless watcher and subscriber logic to make testing without race conditions possible.

For context, the headless authentication watcher uses a stale channel to skip slow subscribers. Subscribers are expected to watch the stale channel and check the backend on receive. This PR breaks out this logic from the single `headlessAuthenticationWatcher.Wait` method into a new `HeadlessAuthenticationSubscriber` interface. This interface gives tests more insight into the stale mechanism, etc, without creating `// Only used in tests` [backdoors into the watcher](https://github.com/gravitational/teleport/pull/23417#discussion_r1145001227).

This change also makes the TestHeadlessAuthenticationWatcher much faster :rocket: since it avoids unstable waiting/ticking logic.

Closes https://github.com/gravitational/teleport/issues/24409

### CODE REVIEW

File: lib/services/local/headlessauthn_watcher_test.go [hunk 1]
```diff
@@ -18,283 +18,281 @@ package local_test
...
+			case update := <-sub.Updates():
+				// We should receive an update of the current backend state on watcher reset.
+				assert.Equal(t, stub, update)
+				return
+			case <-sub.Stale():
+				// We may miss the update but get marked as stale, this is also fine.
+				return
+			case <-ticker.C:
+				t.Error("Expected subscriber to receive an update")
 				return
```
Comment (mdwn) [inline lib/services/local/headlessauthn_watcher_test.go:150]: Same as above.

**Review by mdwn — COMMENTED** [review]
Overall this looks good to me. I've got two questions, but feel free to push back on these.

File: lib/services/local/headlessauthn_watcher.go [hunk 2]
```diff
@@ -201,165 +188,192 @@ func (h *HeadlessAuthenticationWatcher) watch(ctx context.Context) error {
...
+		MetricComponent: types.KindHeadlessAuthentication,
+		Prefixes:        [][]byte{headlessAuthenticationKey("")},
+	})
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+
+	select {
+	case <-watcher.Done():
+		return nil, fmt.Errorf("watcher closed")
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher.go:208]:
```suggestion
		return nil, errors.New("watcher closed")
```

File: lib/services/local/headlessauthn_watcher_test.go [hunk 3]
```diff
@@ -18,283 +18,281 @@ package local_test
...
-func TestHeadlessAuthenticationWatcher(t *testing.T) {
+type headlessAuthenticationWatcherTestEnv struct {
+	watcher       *local.HeadlessAuthenticationWatcher
+	watcherClock  clockwork.FakeClock
+	watcherCancel context.CancelFunc
+	identity      *local.IdentityService
+}
+
+func newHeadlessAuthenticationWatcherTestEnv(t *testing.T) *headlessAuthenticationWatcherTestEnv {
+	identity := newIdentityService(t, clockwork.NewFakeClock())
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher_test.go:41]: Suggestion: get the clock from the caller?

File: lib/services/local/headlessauthn_watcher_test.go [hunk 4]
```diff
@@ -18,283 +18,281 @@ package local_test
...
+
+	watcherCtx, watcherCancel := context.WithCancel(context.Background())
+	t.Cleanup(watcherCancel)
+
+	watcherClock := clockwork.NewFakeClock()
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher_test.go:46]: Use the same clock as above?

File: lib/services/local/headlessauthn_watcher_test.go [hunk 5]
```diff
@@ -18,283 +18,281 @@ package local_test
...
 
-		watcherClock := clockwork.NewFakeClock()
-		w, err := local.NewHeadlessAuthenticationWatcher(watcherCtx, local.HeadlessAuthenticationWatcherConfig{
-			Clock:          watcherClock,
-			WatcherService: buf,
-			Backend:        identity.Backend,
-		})
+		for {
+			select {
+			case <-sub.Updates():
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher_test.go:83]: Should we be checking the contents of the update?

File: lib/services/local/headlessauthn_watcher_test.go [hunk 6]
```diff
@@ -18,283 +18,281 @@ package local_test
...
+				// We should receive the update below.
+				return
+			case <-sub.Stale():
+				// We may miss the update but get marked as stale, this is also fine.
+				return
+			case <-ticker.C:
+				t.Error("Expected subscriber to receive an update")
+				return
```
[the remark this answers is not in the document]
Comment (codingllama) [reply lib/services/local/headlessauthn_watcher_test.go:91]: +1 for a more deterministic solution. It's hard to reason that something is working as intended if there are multiple outcomes.

File: lib/services/local/headlessauthn_watcher_test.go [hunk 7]
```diff
@@ -18,283 +18,281 @@ package local_test
...
+		require.NoError(t, err)
 
 		// Ensure that the waiter did not finish with the condition unmet.
 		select {
 		case err := <-errC:
-			t.Errorf("Expected waiter to continue but instead the waiter returned with err: %v", err)
+			t.Fatalf("Expected waiter to continue but instead the waiter returned with err: %v", err)
 		default:
-			waitCancel()
+			cancel()
```
Comment (codingllama) [inline lib/services/local/headlessauthn_watcher_test.go:225]: Won't this almost instantly fall into the cancel? Should we give some time for the waiter to (not) process the update?

**Review by codingllama — COMMENTED** [review]
Thanks for the fix, Brian!

File: lib/services/local/headlessauthn_watcher.go [hunk 8]
```diff
@@ -138,7 +146,7 @@ func (h *HeadlessAuthenticationWatcher) runWatchLoop(ctx context.Context) {
 		startedWaiting := h.Clock.Now()
 		select {
 		case t := <-h.retry.After():
-			h.Log.Debugf("Attempting to restart watch after waiting %v.", t.Sub(startedWaiting))
+			h.Log.Warningf("Restarting watch on error after waiting %v. Error: %v.", t.Sub(startedWaiting), err)
```
[the remark this answers is not in the document]
Comment (Joerger) [reply lib/services/local/headlessauthn_watcher.go:149]: Yes, `h.watch` should always return non-nil error, and we want to restart the watcher on any error received, unless it's a context canceled/deadline error or the watcher is closed, which is covered by the select case.

File: lib/services/local/headlessauthn_watcher.go [hunk 9]
```diff
@@ -84,14 +77,16 @@ func (cfg *HeadlessAuthenticationWatcherConfig) CheckAndSetDefaults() error {
 	return nil
 }
 
-// HeadlessAuthenticationWatcher is a custom backend watcher for the headless authentication resource.
+// HeadlessAuthenticationWatcher is a light weight backend watcher for the headless authentication resource.
 type HeadlessAuthenticationWatcher struct {
+	// HeadlessAuthenticationWatcherConfig is the configuration of a HeadlessAuthenticationWatcher.
```
Comment (zmb3) [inline lib/services/local/headlessauthn_watcher.go:82]: We can probably do without this comment. I don't think it says anything that's not already obvious.

File: lib/services/local/headlessauthn_watcher_test.go [hunk 10]
```diff
@@ -18,283 +18,306 @@ package local_test
...
 
-		waitForPutEvent(t, s, stub, firstEventReceivedC)
+		ticker := time.NewTicker(time.Second)
+		t.Cleanup(ticker.Stop)
 
-		require.NoError(t, <-errC)
-		require.Equal(t, stub, <-headlessAuthnCh)
+		select {
+		case <-sub.Stale():
+		case <-ticker.C:
```
Comment (zmb3) [inline lib/services/local/headlessauthn_watcher_test.go:124]: A ticker is best for use cases where you need it to tick multiple times. Looks like you're just in need of a single timeout here. Would time.After be a better tool for the job?

**Review by zmb3 — APPROVED** [review]
I like the new approach. See comments for some minor suggestions.

**Review by codingllama — APPROVED** [review]

File: lib/services/local/headlessauthn_watcher_test.go (hunk 10 above)
Comment (Joerger) [reply lib/services/local/headlessauthn_watcher_test.go:124]: I was trying to avoid a [memory leak issue with `time.After`](https://medium.com/@oboturov/golang-time-after-is-not-garbage-collected-4cbc94740082), though I'm not sure how important that is here. WDYT?

Comment (zmb3) [reply lib/services/local/headlessauthn_watcher_test.go:124]: It's not a leak, it's just that the timer won't be collected until after it expires. This matters if you'll be allocating many thousands of timers that won't expire until much later.

In your case:

1. The timer expires in a second.
2. This is a test, which means it's a short lived program. Even if it takes a second for the memory to be GC'd, your tests will likely have already completed by then and the process will have exited.
