### PR TITLE
[Web] Fix terminal resizing

### LINKED ISSUE #31565: Resizing web terminal is broken
Expected behavior:

Resizing an active web terminal results in the session being resized.

Current behavior:

Resizing web terminal doesn't work, old dimensions are sticky. This only affects web terminal, regular `SSH` session behaves correctly.

Bug details:
- Teleport version: `Teleport v14.0.0-alpha.2 git:api/v14.0.0-alpha.2-0-g71aea8d go1.21.0`
- Recreation steps: 

1. Open new session via web UI.
2. Start `htop` or other full-terminal program (for ease of observation).
3. Resize browser window. 
4. Observe malformed output: the old terminal dimensions remain in effect.
5. Observe the warning being logged:

```
2023-09-07T13:10:21Z WARN [WEBSOCKET] Failed to parse resize payload: json: cannot unmarshal number into Go value of type string session_id:447db0bb-408f-4932-9354-04eace45e7ec web/terminal.go:1115
```

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves https://github.com/gravitational/teleport/issues/31565 

Fixes resizing not working properly in the web terminal. This was caused because we were trying to unmarshal the payload which contains number values into a `map[string]string`.

### Before

https://github.com/gravitational/teleport/assets/56373201/ad87defe-e9f0-4fb9-a77e-6d494bb262dc

### After

https://github.com/gravitational/teleport/assets/56373201/b06f346e-b46e-4027-9355-a98c2aff045a

### CODE REVIEW

File: lib/web/terminal.go [hunk 1]
```diff
@@ -1109,14 +1109,20 @@ func (t *TerminalStream) handleWindowResize(ctx context.Context, envelope Envelo
...
 	}
 
-	params, err := session.UnmarshalTerminalParams(e["size"])
+	size, ok := e["size"].(string)
+	if !ok {
+		t.log.Errorf("expected size to be of type string, got type %T instead", size)
+		return
+	}
+
+	params, err := session.UnmarshalTerminalParams(e["size"].(string))
```
Comment (zmb3) [inline lib/web/terminal.go:1125]:
```suggestion
	params, err := session.UnmarshalTerminalParams(size)
```

**Review by rosstimothy — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
