### PR TITLE
Joerger/tctl add user print format fix

### LINKED ISSUE #4364: Tctl users add --format=json returns empty string
### Description

**What happened**:

```bash
$tctl users add bob --roles=admin --format=json
# prints nothing
```

**What you expected to happen**:

```
$tctl users add bob --roles=admin --format=json
{"token": "hex", "ttl": "24h"}
```

**How to reproduce it (as minimally and precisely as possible)**:
see subject

### Environment
- Teleport version (use `teleport version`):
Teleport 4.4 server and client
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

### PR DESCRIPTION
**Pull request by Joerger**
The --format flag for `tctl users add` was a bit finicky and gave unexpected results.
e.g --format=JSON would print nothing (expected --format=json)

- format will now default to 'text' if a format is misspelled
- formats are no longer case sensitive, so --format=JsOn would work.

Fixes #4364

### CODE REVIEW

File: tool/tctl/common/user_command.go [hunk 1]
```diff
@@ -161,21 +161,19 @@ func (u *UserCommand) PrintResetPasswordTokenAsInvite(token services.ResetPasswo
...
-		return trace.Wrap(err)
+// PrintResetPasswordToken prints ResetPasswordToken
+func (u *UserCommand) printResetPasswordToken(token services.ResetPasswordToken, format string, messageFormat string) (err error) {
+	switch strings.ToLower(u.format) {
+	case teleport.JSON:
+		err = printTokenAsJSON(token)
+	case teleport.Text:
+		err = printTokenAsText(token, messageFormat)
+	default:
+		err = printTokenAsText(token, messageFormat)
```
Comment (awly) [inline tool/tctl/common/user_command.go:172]: log a warning about invalid format here

**Review by awly — APPROVED** [review]
