### PR TITLE
Fix flaky tests

### LINKED ISSUE #24105: Unit tests fail with "this Teleport cluster is not licensed for application access"
In the past couple of days we've started getting periodic unit test failures from lib/web/apiserver_test.go tests with a strange error:

```
    apiserver_test.go:4785: 
        	Error Trace:	/__w/teleport/teleport/lib/web/apiserver_test.go:4785
        	Error:      	Received unexpected error:
        	            	this Teleport cluster is not licensed for application access, please contact the cluster administrator
        	Test:       	TestCreateAppSessionHealthCheckAppServer/request_to_application_that_can_be_served
--- FAIL: TestCreateAppSessionHealthCheckAppServer/request_to_application_that_can_be_served (0.21s)
```

I suspect https://github.com/gravitational/teleport/pull/23858 may have been the culprit as it updates the test modules features which probably races with other tests:

https://github.com/gravitational/teleport/commit/bdee053ca985c7a26c5bf2f0d8400fa4834c7a98#diff-7ccc0b653c1df2f24c01f64ed2525daa493092ad3c97df16de3c36e7f05e3911R1928

### LINKED ISSUE #24115: `TestCheckAccessToRegisteredResource/has_registered_kube_server` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4617768497/jobs/8164410407

#### Relevant snippet

```
=== RUN   TestCheckAccessToRegisteredResource/has_registered_kube_server
{"caller":"services/watcher.go:239","component":null,"level":"debug","message":"Attempting to restart watch after waiting 3.577371211s.","resource-kind":"lock","timestamp":"2023-04-05T11:09:35Z"}
{"caller":"services/watcher.go:246","component":null,"level":"warning","message":"Restart watch on error: watcher is closed: rpc error: code = Canceled desc = grpc: the client connection is closing.","resource-kind":"lock","timestamp":"2023-04-05T11:09:35Z"}
    testing.go:1471: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
--- FAIL: TestCheckAccessToRegisteredResource/has_registered_kube_server (0.00s)
```

### PR DESCRIPTION
**Pull request by rudream**
Fixes flaky tests caused by updating a test module while using `t.Parallel()` with `modules.SetTestModules()`

Closes #24115
Closes #24105

### CODE REVIEW

File: lib/web/apiserver_test.go [hunk 1]
```diff
@@ -1920,7 +1920,6 @@ func TestWebAgentForward(t *testing.T) {
 }
 
 func TestActiveSessions(t *testing.T) {
-	t.Parallel()
 	s := newWebSuite(t)
```
Comment (zmb3) [inline lib/web/apiserver_test.go:1923]: While you're here, I would also move `SetTestModules` to the very first line of the test.

Probably not a good idea to start a test auth server in OSS mode and then after it's already running tell it that it's now enterprise.

File: lib/web/apiserver_test.go [hunk 2]
```diff
@@ -1920,13 +1920,13 @@ func TestWebAgentForward(t *testing.T) {
 }
 
 func TestActiveSessions(t *testing.T) {
+	// Use enterprise license (required for moderated sessions).
+	modules.SetTestModules(t, &modules.TestModules{TestBuildType: modules.BuildEnterprise})
+
 	t.Parallel()
```
Comment (zmb3) [inline lib/web/apiserver_test.go:1926]: You still need to remove `t.Parallel()` to fix the bug.

File: lib/web/apiserver_test.go [hunk 3]
```diff
@@ -1920,13 +1920,13 @@ func TestWebAgentForward(t *testing.T) {
 }
 
 func TestActiveSessions(t *testing.T) {
+	// Use enterprise license (required for moderated sessions).
+	modules.SetTestModules(t, &modules.TestModules{TestBuildType: modules.BuildEnterprise})
```
Comment (tigrato) [inline lib/web/apiserver_test.go:1924]: We can't do this since other tests that do not require special features will receive the wrong module content. I.e. Kubernetes now enforces a valid license when upserting `kube_servers`
This affects  https://github.com/gravitational/teleport/pull/24118

If the test changes the modules it cannot run in // with other tests

**Review by zmb3 — APPROVED** [review]

File: lib/web/apiserver_test.go (hunk 3 above)
Comment (tigrato) [reply lib/web/apiserver_test.go:1924]: ups looks like you already fixed it

Comment (zmb3) [reply lib/web/apiserver_test.go:1924]: It's no longer a parallel test, so we should be good to go.

File: lib/modules/test.go [hunk 4]
```diff
@@ -62,6 +62,7 @@ type TestModules struct {
 func SetTestModules(t *testing.T, testModules *TestModules) {
 	defaultModules := GetModules()
 	t.Cleanup(func() { SetModules(defaultModules) })
+	t.Setenv("TELEPORT_TEST_NOT_SAFE_FOR_PARALLEL", "true")
```
Comment (tigrato) [inline lib/modules/test.go:65]: can we add a check that verifies if GetModules doesn't have the default content? It would be a stronger check than this one.

cc @zmb3

**Review by tigrato — APPROVED** [review]
We have other tests that do the same thing

File: lib/modules/test.go (hunk 4 above)
Comment (zmb3) [reply lib/modules/test.go:65]: That wouldn't verify whether or not we are currently in a parallel test, it would only verify whether the modules were previously changed, which is technically something that's allowed in a non-parallel test. This would be a weaker check IMO.

Go's testing package doesn't expose an API to tell you whether or not you are in a parallel test, but they do have those checks internally, and `t.Setenv` will panic if called in a parallel test.

With this in place, it would not have been possible to merge the bad code in the first place.

**Review by zmb3 — APPROVED** [review]
