### PR TITLE
Gracefully handle metadata/summaries failing to load when viewing a session recording

### LINKED ISSUE #63952: Windows session playback fails in 18.7.0 when Identity Security session summaries are enabled
Users are presented with a white screen when attempting to play back a session.

The web console shows the following:

```
Uncaught TypeError: Cannot read properties of undefined (reading '2')
    at ii.displayName (app.js:216:49023)
    at cm (app.js:59:13068)
    at e.generateAndInjectStyles (app.js:59:14195)
    at app.js:59:16332
    at app.js:59:16394
    at v (app.js:59:16547)
    at o4 (app.js:48:34426)
    at gee (app.js:48:61528)
    at kee (app.js:48:76107)
    at Zee (app.js:48:108535)
```

The issue does not reproduce in clusters without Identity Security / Session Summaries enabled.

### PR DESCRIPTION
**Pull request by ryanclark**
When there's a custom `withSummaryComponent` (e), the component wasn't wrapped in an error boundary to fall back to the player if anything fails to load

This adds the fallback to the player

Fixes #63952

#### Desktop

- [x] Play, pause, seeking works

image

#### SSH

- [x] Play, pause, seeking works

image

- [x] Metadata + player shown correctly

image

- [x] When missing metadata - player is shown

image

#### Database

- [x] Play, pause, seeking works

image

#### Kubernetes

- [x] Play, pause, seeking works

image

- [x] Metadata + player shown correctly

image

- [x] When missing metadata - player is shown

image

### Enterprise

- [x] Verified that before this fix, there was a white screen showed for desktop recordings
image

#### Verified desktop recordings still display

- [x] Verified with an actual windows desktop recording that it plays back correctly using the old player
  - [x] Play, pause, seeking works
image

#### Verified that SSH recordings still display
- [x] Play, pause, seeking works
image

- [x] When enhanced summary is present
image

- [x] When legacy summary is present
image

- [x] When missing metadata + summary - player is shown
image

- [x] When missing only summary - metadata + player is shown
image

- [x] When missing only metadata - summary + player is shown
image

#### Verified that Kubernetes recordings still display
- [x] Play, pause, seeking works
image

- [x] When enhanced summary is present
image

- [x] When legacy summary is present
image

- [x] When missing metadata + summary - player is shown
image

- [x] When missing only metadata - summary + player is shown
image

- [x] When missing only summary - metadata + player is shown
image

#### Verified that Database recordings still display 
- [x] Play, pause, seek works
image

- [x] When legacy summary is present
image

- [x] When missing summary (they don't have metadata generated yet)
image

Note - due to the assumption that if metadata fails to load it would be because of a possible proxy upgrade situation where one proxy returned a 404 for the new endpoint added, we'd fall back to just showing the player. I updated this and tested that if the metadata fails to load, we try to load the summary and show that anyway, and if they both fail to load, we fall back to the player.

changelog: Fixed an issue where desktop session recordings would show a white screen instead of the recording player, and fixed an issue where if a session's metadata failed to load and the session had a summary it didn't display the summary

### CODE REVIEW

**Comment by ryanclark** [comment]
~Just had the thought that the OSS variants should also be in the test plan. Will update and test once back from lunch.~ Added above

**Review by avatus — APPROVED** [review]

File: web/packages/teleport/src/SessionRecordings/view/ViewSessionRecordingRoute.tsx [hunk 1]
```diff
@@ -110,6 +110,31 @@ export function ViewSessionRecordingRoute({
...
+                  durationMs={durationMs}
+                  recordingType={recordingType}
+                />
+              }
+            >
+              <RecordingWithMetadataComponent
+                clusterId={clusterId}
+                recordingType={recordingType}
+                sessionId={sid}
+              />
```
Comment (gzdunek) [inline web/packages/teleport/src/SessionRecordings/view/ViewSessionRecordingRoute.tsx]: WDYT of extracting these components to variables? Then use them here, in the line 141 and 155.
```tsx
  const recordingWithSummaryComponent = (
    <RecordingWithSummaryComponent
      clusterId={clusterId}
      sessionId={sid}
      durationMs={durationMs}
      recordingType={recordingType}
    />
  );
  const recordingWithMetadataComponent = (
    <RecordingWithMetadataComponent
      clusterId={clusterId}
      recordingType={recordingType}
      sessionId={sid}
    />
  );
```
It would be easier to understand the order of fallbacks.

**Review by gzdunek — APPROVED** [review]

File: web/packages/teleport/src/SessionRecordings/view/ViewSessionRecordingRoute.tsx (hunk 1 above)
Comment (ryanclark) [reply web/packages/teleport/src/SessionRecordings/view/ViewSessionRecordingRoute.tsx]: Good shout
