### PR TITLE
fix tsh db connect with hardware backed key

### LINKED ISSUE #20799: `tsh db connect` fails when PIV is enabled
Expected behavior:
- `tsh db connect` should work for any db protocol when PIV is enabled.

Current behavior:
- it fails for certain configurations

The problem is that if a local proxy is started for `tsh db connect`, it *must* be a `--tunnel` local proxy, or the local proxy will fail to access the hardware backed private key.

The following configurations cause `tsh db connect` to start a local proxy without a tunnel:
- TLS routing is enabled and db protocol *is not* one of: elasticsearch, dynamodb, snowflake
- TLS routing is disabled and db protocol *is* one of: sql server, cassandra

Bug details:
- Teleport version: v12.0.0-alpha.2
- Recreation steps:
  1. enable TLS routing
  2. `tsh db connect` to a mysql db for example. That's what failed for me.

### PR DESCRIPTION
**Pull request by GavinFrazar**
Fixes #20799

Leaving this in draft until I've added test cases, but from manually trying out the fix it seems to have done the trick.

Test by building with `PIV=yes` and enabling PIV with `require_session_mfa: hardware_key # or hardware_key_touch` and then connecting to a database. The issue describes configurations with the problem.

### CODE REVIEW

**Comment by GavinFrazar** [comment]
I added test cases for login or whenever a new client is created. This way if, for example, the user has an old profile (such that `TeleportClient` is created before trying to use their private key), then login should always update `TeleportClient.PrivateKeyPolicy`.

I also verified that the following scenarios are handled:
1. `tsh db connect --user=alice --db-user=foo --db-name=bar somedb` will trigger a login flow if the user has not done `tsh login` before and will detect the key policy
2. `tsh db connect..` will trigger relogin and detect key policy if the profile has expired
3. `tsh db connect ...` will always setup a proxy tunnel if hardware key policy is in effect

 `tsh db connect` should now work with PIV regardless of config/protocol.

File: lib/client/api_login_test.go [hunk 1]
```diff
@@ -282,10 +283,27 @@ func TestTeleportClient_Login_local(t *testing.T) {
...
 			tc.PreferOTP = test.preferOTP
 			tc.AuthenticatorAttachment = test.authenticatorAttachment
+			require.Empty(t, tc.PrivateKeyPolicy,
+				"key policy should be empty before initial login")
 
 			clock.Advance(30 * time.Second)
-			_, err = tc.Login(ctx)
+			key, err := tc.Login(ctx)
 			require.NoError(t, err)
+			require.NotNil(t, key, "no client key returned from login")
```
Comment (codingllama) [inline lib/client/api_login_test.go:292]: Suggestion: Could we do a separate, abridged test case that covers only this?

The assertions are always the same, meaning the scenarios don't really have an influence on it.

File: tool/tsh/db.go [hunk 2]
```diff
@@ -560,11 +561,15 @@ func maybeStartLocalProxy(ctx context.Context, cf *CLIConf, tc *client.TeleportC
...
-	if requiresLocalProxyTunnel(db.Protocol) || db.Protocol == defaults.ProtocolElasticsearch {
+	if requiresLocalProxyTunnel(tc, db.Protocol) || db.Protocol == defaults.ProtocolElasticsearch {
 		localProxyTunnel = true
 	}
 
-	log.Debugf("Starting local proxy")
+	if localProxyTunnel {
+		log.Debugf("Starting local proxy tunnel")
+	} else {
+		log.Debugf("Starting local proxy")
```
Comment (codingllama) [inline tool/tsh/db.go:571]:
```suggestion
		log.Debug("Starting local proxy tunnel")
	} else {
		log.Debug("Starting local proxy")
```

File: tool/tsh/db.go [hunk 3]
```diff
@@ -1064,12 +1069,16 @@ func formatDatabaseConfigCommand(clusterFlag string, db tlsca.RouteToDatabase) s
...
 }
 
 // isLocalProxyAlwaysRequired returns true for protocols that always requires
 // an ALPN local proxy.
-func isLocalProxyAlwaysRequired(protocol string) bool {
+func isLocalProxyAlwaysRequired(tc *client.TeleportClient, protocol string) bool {
+	switch tc.PrivateKeyPolicy {
+	case keys.PrivateKeyPolicyHardwareKey, keys.PrivateKeyPolicyHardwareKeyTouch:
+		return true
+	}
```
Comment (codingllama) [inline tool/tsh/db.go:1081]: nit: single-case switch:

```suggestion
	if tc.PrivateKeyPolicy == keys.PrivateKeyPolicyHardwareKey ||
		tc.PrivateKeyPolicy == keys.PrivateKeyPolicyHardwareKeyTouch {
		return true
	}
```

File: tool/tsh/proxy.go [hunk 4]
```diff
@@ -922,7 +922,11 @@ func envVarCommand(format, key, value string) (string, error) {
 }
 
 // requiresLocalProxyTunnel returns whether the given protocol requires a local proxy with the --tunnel flag.
-func requiresLocalProxyTunnel(protocol string) bool {
+func requiresLocalProxyTunnel(tc *libclient.TeleportClient, protocol string) bool {
+	switch tc.PrivateKeyPolicy {
+	case keys.PrivateKeyPolicyHardwareKey, keys.PrivateKeyPolicyHardwareKeyTouch:
+		return true
+	}
```
Comment (codingllama) [inline tool/tsh/proxy.go:929]: nit: same:

```suggestion
	if tc.PrivateKeyPolicy == keys.PrivateKeyPolicyHardwareKey ||
		tc.PrivateKeyPolicy == keys.PrivateKeyPolicyHardwareKeyTouch {
		return true
	}
```

**Review by codingllama — APPROVED** [review]
~I would prefer having a the test separate from `TestTeleportClient_Login_local`, but LGTM.~

Edit: not applicable anymore, LGTM.

File: tool/tsh/db.go (hunk 3 above)
Comment (GavinFrazar) [reply tool/tsh/db.go:1081]: it's really two cases and I prefer the concise switch syntax

Comment (codingllama) [reply tool/tsh/db.go:1081]: Fair enough.

File: lib/client/api.go [hunk 5]
```diff
@@ -1001,6 +1001,13 @@ func NewClient(c *Config) (tc *TeleportClient, err error) {
 		tc.HostKeyCallback = tc.localAgent.CheckHostKey
 	}
 
+	// If we haven't already set the private key policy, load it into the client based on the private key.
+	if tc.PrivateKeyPolicy == "" {
+		if key, err := tc.LocalAgent().GetCoreKey(); err == nil {
+			tc.PrivateKeyPolicy = keys.GetPrivateKeyPolicy(key.PrivateKey)
+		}
+	}
```
Comment (Joerger) [inline lib/client/api.go:1009]: Once https://github.com/gravitational/teleport/pull/20849 is merged (in merge queue), can we merge master and remove this?

**Review by Joerger — COMMENTED** [review]
LGTM

File: lib/client/api_login_test.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/client/api_login_test.go:292]: I'm not sure what you mean - by "this" are you referring to testing that key policy is set after the user logs in?

And after reviewing @Joerger's PR I think these test cases will need to be reworked anyway, since the policy will be saved in the profile

**Review by codingllama — APPROVED** [review]

**Review by Joerger — APPROVED** [review]
