### PR TITLE
Make relogin attempts use the strongest auth method

### LINKED ISSUE #11709: `tsh ssh` when authenticating eats the first two keypresses
### Description

**What happened**: 

When _not_ currently authenticated, either via explicit `tsh logout`, or auth having expired, the first `tsh ssh` connection successfully re-auths, but consumes the first two keypresses of input to the host.  Here's me connecting, pasting in my password, pressing my Yubikey, and then typing "12345" once I see the remote host's prompt appear:

```
$ tsh logout
Logged out all users from all proxies.

$ tsh ssh --proxy teleport.example.net --user alexmv -l username hostname.example.net
Enter password for Teleport user alexmv:
Tap any security key or enter a code from a OTP device:
username@hostname:~$ 345
```

It's not just visible characters; if I wait until the `username@hostname:~$` prompt appears, I have to press Ctrl-D three times before it closes the connection.

**What you expected to happen**: Once the remote prompt appears, all input should get sent to the remote server.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. `tsh logout`
2. `tsh ssh --proxy teleport.example.net --user alexmv -l username --debug hostname.example.net`

### Server Details
- Teleport version (run `teleport version`): `Teleport v9.0.2 git:v9.0.2-0-g354b8c037 go1.17.7`
- Server OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.4 LTS (Focal Fossa)`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

### Client Details
- Tsh version (`tsh version`): `Teleport v9.0.3 git: go1.18`
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Installed via (e.g. apt, yum, brew, website download) brew

### PR DESCRIPTION
**Pull request by codingllama**
Fixes a potential stdin hijacking bug by making relogin attempts default to a single MFA method (the strongest available).

The problematic scenario is as follows:

1. User has both OTP and security keys registered
2. "Relogin" is triggered via a tsh command (say, `tsh logout; tsh ssh --proxy=example.com llama@myserver`)
3. User is prompted to pick either OTP or security key ("Tap any security key or enter a code from a OTP device")
4. An stdin read is fired in the background to read the OTP code (via prompt.Stdin)
5. User picks the security method, thus the stdin read is "abandoned"

In most cases this is fine, as the program ends right after. The issue is when a relogin is triggered by a long living tsh invocation (again, `tsh ssh ...`): in this case the stdin hijack causes input to be swallowed.

Forcing a single MFA option avoids the potential stdin hijack, fixing the problem for all relogin invocations. `tsh login` behavior remains the same.

Note that we have to default to cluster's most secure method _without_ checking the user devices. The user is not logged in yet, thus the backend cannot reveal any information about that user.

Fixes #11709.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Comment by codingllama** [comment]
Confirmed that changes work for v9 ([codingllama/v9-hungry-hungry-tsh](https://github.com/gravitational/teleport/tree/codingllama/v9-hungry-hungry-tsh)). Prepping a v8 backport now.

**Comment by codingllama** [comment]
Friendly ping @greedy52 @smallinsky ?

File: lib/client/mfa.go [hunk 1]
```diff
@@ -76,6 +91,9 @@ func PromptMFAChallenge(
 		hasWebauthn = false
 	}
 
+	// Prompt only for the strongest auth method available?
+	hasTOTP = !(opts.UseStrongestAuth && hasWebauthn) && hasTOTP
```
Comment (greedy52) [inline lib/client/mfa.go:95]: nit. I stared at this line for quite some time try to understand it. is this the same as
```suggestion
	if opts.UseStrongestAuth && hasWebauthn {
		hasTOTP = false
	}
```
up to you if you prefer to keep the one liner.

**Review by greedy52 — APPROVED** [review]

File: lib/client/api.go [hunk 2]
```diff
@@ -553,10 +561,21 @@ func RetryWithRelogin(ctx context.Context, tc *TeleportClient, fn func() error)
 	}
 	log.Debugf("Activating relogin on %v.", err)
 
+	if !tc.UseStrongestAuth {
+		defer func() {
+			tc.UseStrongestAuth = false
+		}()
+		// Avoid stdin hijack on relogin attempts.
+		// Uses can pick an alternative MFA method by explicitly calling Login (or
```
[the remark this answers is not in the document]
Comment (codingllama) [reply lib/client/api.go:569]: Done, well spotted.

File: lib/client/mfa.go (hunk 1 above)
Comment (codingllama) [reply lib/client/mfa.go:95]: I agree, this seems better. That's what I started with, but then I felt the urge to "simplify".

**Comment by codingllama** [comment]
Thanks, @greedy52.

@smallinsky, let me know if you'd like to take a look or if you are happy for me to merge with the current approvals.

**Comment by codingllama** [comment]
I'll go ahead and merge this one so I can get the backports going. Happy to address any comments in a future PR.
