### PR TITLE
Fix HTTP CONNECT response handling

### LINKED ISSUE #1659: Integration tests intermittently fail when building a tunnel between clusters using a proxy
**Problem**

```
----------------------------------------------------------------------
FAIL: integration_test.go:769: IntSuite.TestTwoClustersProxy

integration_test.go:804:
    c.Fatalf("two sites do not see each other: tunnels are not working")
... Error: two sites do not see each other: tunnels are not working

OOPS: 0 passed, 1 FAILED
--- FAIL: TestIntegrations (11.31s)
FAIL
exit status 1
```

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

As covered in https://github.com/gravitational/teleport/issues/1659, the `TestTwoClustersProxy` test would intermittently fail with `two sites do not see each other: tunnels are not working`. Investigating further it appeared that the connection could not be established due to a failure in the SSH handshake: `ssh: handshake failed: ssh: overflow reading version string`.

Investigating the above revealed the true cause of the failure. Upon receipt of the response to the HTTP CONNECT request, `http.ReadResponse` is used to parse the status line. This function takes a buffered reader and as a side effect occasionally part of the body is read (and buffered) as well. This would mainly happen when the traffic being tunneled is copied over the connection before the response has been read from the connection.

Due to the above, part of the SSH handshake would be lost, leading to the handshake failing, leading the the inability of the connection to be established.

To resolve this issue, a internal `*bufferedConn` is used which first reads any buffered data, then reads from the underlying connection.

**Implementation**

* After parsing the HTTP CONNECT response, return a `*bufferedConn` which will first return any buffered data and then data from the connection.
* Changed the order of writing the response and hijacking the connection so the following logs are not written to stdout during integration tests:
    ```
    2018/02/08 16:51:13 http: response.WriteHeader on hijacked connection
    2018/02/08 16:51:13 http: response.Write on hijacked connection
    ```

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1659

### CODE REVIEW

File: lib/utils/proxy/proxy.go [hunk 1]
```diff
@@ -134,24 +138,35 @@ func dialProxy(proxyAddr string, addr string) (net.Conn, error) {
...
 		return nil, trace.Wrap(err)
 	}
 	if resp.StatusCode != http.StatusOK {
 		f := strings.SplitN(resp.Status, " ", 2)
 		conn.Close()
-		return nil, trace.BadParameter("Unable to proxy connection, StatusCode %v: %v", resp.StatusCode, f[1])
-	}
-
-	return conn, nil
+		return nil, trace.BadParameter("unable to proxy connection, StatusCode %v: %v", resp.StatusCode, f[1])
```
Comment (klizhentas) [inline lib/utils/proxy/proxy.go]: unable to proxy connection, status code:

File: lib/utils/proxy/proxy.go [hunk 2]
```diff
@@ -134,24 +138,35 @@ func dialProxy(proxyAddr string, addr string) (net.Conn, error) {
...
+	}
+
+	// return a bufferedConn that wraps a net.Conn and a *bufio.Reader. this
```
Comment (klizhentas) [inline lib/utils/proxy/proxy.go]: Can you cap the first words of sentences? `Return a bufferedConn`

**Review by klizhentas — APPROVED** [review]
