### PR TITLE
Fix MOTD not showing up on tsh login with certain arguments

### LINKED ISSUE #10503: "message_of_the_day" is not showing up in some scenarios.
### Description
"message_of_the_day" is not showing up in some scenarios.

**What happened**:
1. "message_of_the_day" is not showing  with `tsh login` if `--auth` option is added to the login command.
2. "message_of_the_day" is not showing with `tsh login` if `auth` node does not have `authentication` parameter.

**What you expected to happen**:

MOTD should always show when using `tsh login`.

### Reproduction Steps

1.
- spin up teleport cluster with below config:
- login to proxy using `tsh login --insecure --proxy=127.0.0.1:3080 --auth=local` command.
- MOTD will not appear, even if its setup in auth_service.
- if login using `tsh login --insecure --proxy=127.0.0.1:3080` command, MOTD is showing as expected.

2.
- spin up teleport cluster with below auth config:
- login to proxy using `tsh login --insecure --proxy=127.0.0.1:5080` command.
- MOTD will not appear, even if its setup in auth_service.

Attached scripts to reproduce this issue on local laptop [repro_4149_2.tar.gz](https://github.com/gravitational/teleport/files/8113147/repro_4149_2.tar.gz)

Steps to follow: 
- extract file from repro_4149_2.tar.gz.

```
tar xvzf repro_4149_2.tar.gz
```
- cd to extracted directory and run below commands:

```
cd repro_4149_2

# setup 2 teleport clusters with 2 different configs
./cluster_setup.sh

# run tests (this script shows MOTD behaviour)

./test.sh


# stop clusters
./stop_clusters.sh


```

### Server Details
- Teleport version (run `teleport version`): 8.1.x+

### Client Details
- Tsh version (`tsh version`): 8.1.x+

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- tsh debug logs when MOTD was shown.
[tsh_logs_debug_MOTD.txt](https://github.com/gravitational/teleport/files/8113140/tsh_logs_debug_MOTD.txt)

-  tsh debug logs when MOTD was NOT shown.
[tsh_logs_debug_no_MOTD.txt](https://github.com/gravitational/teleport/files/8113146/tsh_logs_debug_no_MOTD.txt)

### PR DESCRIPTION
**Pull request by lxea**
- changes to configuration.go: fixes tsh login in the first case from the repro files
  `tsh login --insecure --proxy=127.0.0.1:3080 --user=test`
- changes to apiserver.go fixes `--auth` and `--with-roles` not showing motd

These changes also add a test and part of that required moving `export_test.go` to `export.go` so the `passwordFromConsole` function could be overridden when testing for the MOTD

fixes: #10503

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -2390,14 +2390,8 @@ func (tc *TeleportClient) LogoutAll() error {
...
 
-// Login logs the user into a Teleport cluster by talking to a Teleport proxy.
-//
-// The returned Key should typically be passed to ActivateKey in order to
-// update local agent state.
-//
-func (tc *TeleportClient) Login(ctx context.Context) (*Key, error) {
-	// Ping the endpoint to see if it's up and find the type of authentication
-	// supported.
+// PingAndShowMOTD makes a ping aisplays the MOTD.
```
Comment (r0mant) [inline lib/client/api.go:2393]:
```suggestion
// PingAndShowMOTD pings the Teleport Proxy and displays the MOTD if it's available.
```

File: lib/config/configuration.go [hunk 2]
```diff
@@ -547,8 +547,8 @@ func applyAuthConfig(fc *FileConfig, cfg *service.Config) error {
 		if err != nil {
 			return trace.Wrap(err)
 		}
-		cfg.Auth.Preference.SetMessageOfTheDay(fc.Auth.MessageOfTheDay)
 	}
+	cfg.Auth.Preference.SetMessageOfTheDay(fc.Auth.MessageOfTheDay)
```
Comment (r0mant) [inline lib/config/configuration.go:551]: Should this only be set in case `fc.Auth.MessageOfTheDay != ""`?

File: lib/web/apiserver.go [hunk 3]
```diff
@@ -788,33 +788,40 @@ func (h *Handler) pingWithConnector(w http.ResponseWriter, r *http.Request, p ht
...
+	if !authPresent && err == nil {
+		as = githubSettings(githubConnector, cap)
+		authPresent = true
+	}
+
+	if authPresent {
+		as.HasMessageOfTheDay = cap.GetMessageOfTheDay() != ""
+		response.Auth = as
 		return response, nil
 	}
```
Comment (r0mant) [inline lib/web/apiserver.go:826]: If you kept the old logic of assigning `response.Auth = xxx` directly above, would you be able to get rid of the extra `authPresent` boolean flag and just use `if response.Auth != nil` check instead? Then you could something like
```suggestion
	if response.Auth != nil {
		response.Auth.HasMessageOfTheDay = cap.GetMessageOfTheDay() != ""
	}
```

which is a bit cleaner.

File: tool/tsh/tsh.go [hunk 4]
```diff
@@ -864,6 +868,10 @@ func onLogin(cf *CLIConf) error {
 				return trace.Wrap(err)
 			}
 			printProfiles(cf.Debug, profile, profiles)
+			_, err := tc.PingAndShowMOTD(cf.Context)
```
Comment (r0mant) [inline tool/tsh/tsh.go:871]: Hmm, you already have PingAndShowMOTD above, aren't we going to display it twice if you also put it in each "case" branch here?

**Review by r0mant — COMMENTED** [review]
Please also include test coverage. We have some tsh tests already, should be pretty straightforward.

File: lib/web/apiserver.go (hunk 3 above)
Comment (lxea) [reply lib/web/apiserver.go:826]: response.Auth isn't nilable at the moment, should I make it a pointer in this pr?

File: tool/tsh/tsh.go (hunk 4 above)
Comment (lxea) [reply tool/tsh/tsh.go:871]: Ah yeah, I meant to remove that, it could also print twice being at the top if it flows through too.

Comment (lxea) [reply tool/tsh/tsh.go:877]: I did it like this to retain the previous `tc.Login` behavior -- it shows the MOTD when its called and uses the result of the ping. I can change it so showing the MOTD is done separatly and the ping is passed in

Comment (r0mant) [reply tool/tsh/tsh.go:877]: @lxea Ah yes, it makes sense. In that case it should be fine.

Comment (r0mant) [reply tool/tsh/tsh.go:877]: But can you please move it so MOTD is displayed before everything else like profiles?

**Review by r0mant — APPROVED** [review]

**Comment by r0mant** [comment]
@jakule or @zmb3 can one of you folks take a look as well pls?

File: lib/client/api.go [hunk 5]
```diff
@@ -2390,14 +2390,8 @@ func (tc *TeleportClient) LogoutAll() error {
...
 
-// Login logs the user into a Teleport cluster by talking to a Teleport proxy.
-//
-// The returned Key should typically be passed to ActivateKey in order to
-// update local agent state.
-//
-func (tc *TeleportClient) Login(ctx context.Context) (*Key, error) {
-	// Ping the endpoint to see if it's up and find the type of authentication
-	// supported.
+// PingAndShowMOTD pings the Teleport Proxy and displays the MOTD if it's available.
```
Comment (jakule) [inline lib/client/api.go:2393]: nit: I don't abbreviation in the function name, but I'd assume that comment explains what MOTD is. Without any context this can be not obvious.
```suggestion
// PingAndShowMOTD pings the Teleport Proxy and displays the Message Of The Day if it's available.
```

File: tool/tsh/tsh_test.go [hunk 6]
```diff
@@ -231,11 +240,24 @@ func TestOIDCLogin(t *testing.T) {
...
+func findMOTD(t *testing.T, sc *bufio.Scanner, motd string) {
+	t.Helper()
+	found := false
+	for sc.Scan() {
+		if strings.Contains(sc.Text(), motd) {
+			found = true
+			break
+		}
+	}
+	require.True(t, found, "Failed to find %q MOTD in the logs", motd)
```
Comment (jakule) [inline tool/tsh/tsh_test.go:258]: nit: I don't think `found`variable is needed here. You could replace the break a few lines above with `return` and this line with `require.Fail`.  In my opinion that would simplify this function.

File: tool/tsh/tsh_test.go [hunk 7]
```diff
@@ -1252,7 +1294,12 @@ func withBootstrap(bootstrap ...types.Resource) testServerOptFunc {
 
 func withAuthConfig(fn func(cfg *service.AuthConfig)) testServerOptFunc {
 	return func(o *testServersOpts) {
-		o.authConfigFunc = fn
+		fmt.Println("honk1", o.authConfigFuncs)
```
Comment (jakule) [inline tool/tsh/tsh_test.go:1297]: This looks like some debug leftover.

**Review by jakule — APPROVED** [review]
One comment, two nits.
