### PR TITLE
remove incorrect error messages from password reset flow

### LINKED ISSUE #1711: Password change form problems
There are two issues:

1. "Enter" is ignored in the form
2. Invalid OTP token leads to the user getting logged out. Sometimes it's an instant redirect to Login, sometimes you get "Internal error"

### PR DESCRIPTION
**Pull request by alex-kovoy**
closes #1711

### CODE REVIEW

**Comment by klizhentas** [comment]
this does not seem like a proper fix, especially removing password check.

File: lib/auth/password.go [hunk 1]
```diff
@@ -112,7 +114,7 @@ func (s *AuthServer) CheckOTP(user string, otpToken string) error {
 
 		// look ahead n tokens to see if we can find a matching token
 		if !otp.Scan(otpToken, defaults.HOTPFirstTokensRange) {
-			return trace.AccessDenied("bad htop token")
+			return trace.BadParameter("bad htop token")
```
Comment (klizhentas) [inline lib/auth/password.go]: one time token - htop token is a typo

**Review by klizhentas — APPROVED** [review]
