### PR TITLE
web: stream recorded SSH/Kube sessions rather than downloading them

### LINKED ISSUE #10578: Playback of long (~200 MB) session crashes the browser tab
### Description

**What happened**:

Playback of session with single command ("find /") caused the browser (Google Chrome) to crash, after several seconds of wait. When measured with `tsh play` I found the session to be ~200 MB long.

**What you expected to happen**:

Playback working.

### PR DESCRIPTION
**Pull request by zmb3**
Prior to this, the web UI would download the entire session recording
and store it in JavaScript memory before starting playback. This caused
the browser tab to crash when attempting to play back sessions larger
than ~5MB.

Updates https://github.com/gravitational/teleport-private/issues/1024
Closes https://github.com/gravitational/teleport-private/issues/665
Closes https://github.com/gravitational/teleport/issues/10578

### CODE REVIEW

File: web/packages/teleport/src/Assist/service.ts [hunk 1]
```diff
@@ -101,6 +101,8 @@ export async function resolveServerMessage(
   }
 }
 
+// TODO(zmb3): check with Ryan about replacing this with streaming
```
Comment (zmb3) [inline web/packages/teleport/src/Assist/service.ts:104]: cc @ryanclark how critical is `getSessionEvents` / `getSessionStream` given the de-investment in assist?

I'd really like to remove these APIs from the frontend for v15 so that I can remove them from the backend in v16.

File: web/packages/teleport/src/Player/ProgressBar/ProgressBar.tsx [hunk 2]
```diff
@@ -67,13 +69,15 @@ function Restart(props: { onRestart?: () => void }) {
 export type ProgressBarProps = {
   max: number;
   min: number;
-  time: any;
+  time: string;
```
Comment (avatus) [inline web/packages/teleport/src/Player/ProgressBar/ProgressBar.tsx:72]: 🙌

File: web/packages/teleport/src/Player/SshPlayer.tsx [hunk 3]
```diff
@@ -53,22 +56,31 @@ export default function Player({ sid, clusterId }) {
...
       </Flex>
-      {eventCount > 0 && <ProgressBarTty tty={tty} />}
+      <ProgressBar
+        min={0}
+        max={durationMs}
+        current={time}
+        disabled={
+          playerStatus === TtyStatusEnum.ERROR ||
+          playerStatus === TtyStatusEnum.COMPLETE
+        }
```
Comment (avatus) [inline web/packages/teleport/src/Player/SshPlayer.tsx:71]: I don't think we should disable when complete. I haven't used it much, but it seems like wanting to move through/restart a completed video would be a valid choice.

Comment (zmb3) [reply web/packages/teleport/src/Player/SshPlayer.tsx:71]: Yeah but it doesn't work and it would be a fair amount of work to make it work when there's already a replay button that will restart it for us.

Comment (avatus) [reply web/packages/teleport/src/Player/SshPlayer.tsx:71]: Fair enough

File: web/packages/teleport/src/Player/Player.tsx [hunk 4]
```diff
@@ -63,15 +62,15 @@ export default function Player() {
       <StyledPlayer>
         <Box textAlign="center" mx={10} mt={5}>
           <Danger mb={0}>
-            Invalid query parameter recordingType: {recordingType}, should be
-            'ssh' or 'desktop'
+            Invalid query parameter recordingType: {recordingType}, should be on
+            of {validRecordingTypes.join(', ')}.
```
Comment (avatus) [inline web/packages/teleport/src/Player/Player.tsx:66]:
```suggestion
            Invalid query parameter recordingType: {recordingType}, should be one
            of the following: {validRecordingTypes.join(', ')}.
```

File: web/packages/teleport/src/Player/SshPlayer.tsx [hunk 5]
```diff
@@ -53,22 +56,31 @@ export default function Player({ sid, clusterId }) {
...
+        isPlaying={isPlaying}
+        time={formatDisplayTime(time)}
+        onRestart={() => window.location.reload()}
+        onStartMove={() => tty.suspendTimeUpdates()}
```
Comment (avatus) [inline web/packages/teleport/src/Player/SshPlayer.tsx:75]:
```suggestion
        onRestart={window.location.reload}
        onStartMove={tty.suspendTimeUpdates}
```

File: web/packages/teleport/src/Player/SshPlayer.tsx [hunk 6]
```diff
@@ -87,35 +99,45 @@ const StyledPlayer = styled.div`
...
+      .replace(':token', getAccessToken());
+    return new TtyPlayer({ url, setPlayerStatus, setStatusText, setTime });
+  }, [clusterId, sid, setPlayerStatus, setStatusText, setTime]);
 
   React.useEffect(() => {
-    function onChange() {
-      // trigger rerender when status changes
-      rerender(tty.status);
-    }
+    tty.connect(0, 0);
```
Comment (avatus) [inline web/packages/teleport/src/Player/SshPlayer.tsx:117]: I'm getting a type error here saying this expects no arguments. perhaps a left over?

**Review by avatus — APPROVED** [review]
Frontend looks good to me

File: web/packages/teleport/src/Player/SshPlayer.tsx (hunk 6 above)
Comment (zmb3) [reply web/packages/teleport/src/Player/SshPlayer.tsx:117]: The base class expects `connect(width, height)`. I tried to leave them in the definition as `connect(_w, _h)` but then linter complained that those variables were unused. What's proper protocol here?

Comment (avatus) [reply web/packages/teleport/src/Player/SshPlayer.tsx:117]: We aren't calling the base `connect` in this method so we don't need to pass those params in. It overrides just fine with your overridden parameterless method declaration because the callsite is properly typed as `TtyPlayer` and knows its a parameterless `connect`. If i remove the `0,0` from this call of `tty.connect` all lint errors go away, is this different on your end?

File: lib/web/tty_playback.go [hunk 7]
```diff
@@ -0,0 +1,343 @@
...
+					player.Pause()
+				}
+			case messageTypeSeek:
+				if len(payload) != 8 {
+					log.Warn("skipping invalid seek message")
+					continue
+				}
+				pos := binary.BigEndian.Uint64(payload)
+				player.SetPos(time.Duration(pos) * time.Millisecond)
+			}
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/web/tty_playback.go:152]: Good catch. Added a fuzz test as well, which also caught the error.

(Note: fuzzing seems busted on macOS with the new ld-prime linker. I had to run in Docker to get it to work..)

[the remark this answers is not in the document]
Comment (Tener) [reply lib/web/tty_playback.go]: It works if you tell it to use classic linker: `go test -ldflags -extldflags=-ld_classic ...` (kudos @espadolini).

**Review by Tener — APPROVED** [review]
To ensure the fuzz tests are actually executed, you need to add them to `fuzz/oss-fuzz-build.sh`. @jentfoo we should have an automated test checking this, is this anywhere on a radar?

**Comment by jentfoo** [comment]
> we should have an automated test checking this, is this anywhere on a radar?

A couple months ago I went and reviewed all of our fuzzing, ensured good seeds and coverage as well as oss-fuzz.  So I think we are generally in a good place.  However after that effort I did have to remove several tests from oss-fuzz due to a bug on their side resulting in timeout failures that were unable to be reproduced outside of oss-fuzz.

Long story short, we should add this to oss-fuzz, but we can not ensure all fuzzing is done within oss-fuzz due to the timeout false positives.  And there is not currently any automation to validate what is in oss-fuzz or not.
