### PR TITLE
Deflake database access test suite setup helper

### LINKED ISSUE #56304: ` TestAccessSQLServer/has_access_to_all_database_users` flakiness
#### Link(s) to logs

https://github.com/gravitational/teleport.e/actions/runs/15996158747/job/45119951023

#### Relevant snippet

```
    access_test.go:887: 
        	Error Trace:	/__w/teleport.e/teleport.e/lib/srv/db/access_test.go:887
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestAccessSQLServer/has_access_to_all_database_users
--- FAIL: TestAccessSQLServer/has_access_to_all_database_users (0.05s)
```

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #56304
-  #56304

Wait for database heartbeats to become available to the proxy's access point.

I actually couldn't reproduce the failure from that flaky test run even with `-race -cover -count=1000`.

The root cause of the failure seems to be that the proxy hasn't observed database heartbeats yet, so it fails the connection.
If that's the case, then we just need to make sure the proxy has observed the database heartbeats before we start testing connections through the proxy.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by EdwardDowling — APPROVED** [review]

File: lib/srv/db/access_test.go [hunk 1]
```diff
@@ -2637,6 +2639,19 @@ func (c *testContext) setupDatabaseServer(ctx context.Context, t testing.TB, p a
 				t.Fatal("timed out waiting for inventory handle sender")
 			}
 		}
+		require.EventuallyWithT(t, func(t *assert.CollectT) {
```
Comment (greedy52) [inline lib/srv/db/access_test.go:2629]: `inventoryHandle.Sender()` above can be removed?

File: lib/srv/db/access_test.go [hunk 2]
```diff
@@ -2637,6 +2639,19 @@ func (c *testContext) setupDatabaseServer(ctx context.Context, t testing.TB, p a
...
+			if !assert.NoError(t, err) {
+				return
+			}
+			names := map[string]struct{}{}
+			for _, srv := range dbServers {
+				names[srv.GetName()] = struct{}{}
+			}
+			for _, db := range p.Databases {
+				assert.Contains(t, names, db.GetName())
+			}
```
Comment (greedy52) [inline lib/srv/db/access_test.go]: nit: probably can do something like this
```golang
			assert.ElementsMatch(t,
				slices.Collect(types.ResourceNames(p.Databases)),
				slices.Collect(types.ResourceNames(dbServers)),
			)
```
doesn't save a lot of lines but slightly easier to read

**Review by greedy52 — APPROVED** [review]

File: lib/srv/db/access_test.go (hunk 2 above)
Comment (GavinFrazar) [reply lib/srv/db/access_test.go]: oh nice, but this fails for cases with dynamic or discovered databases. However I found `assert.Subset` which does what we want.

File: lib/srv/db/access_test.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/srv/db/access_test.go:2629]: looks like it can be, but I had to fix `TestHealthCheck` which apparently relied on it because we don't have early heartbeat announcement for health status changes yet.

Instead of polling for announced heartbeats I'll just poll current db server info in that test: [diff](https://github.com/gravitational/teleport/compare/2fd0a1996012f3eb186849e6f9dd6ef7e4949089..9583853cfc45273c7ed618bd024a6b1776b0f57a)
