### PR TITLE
Fix reading TDP messages from websockets

### LINKED ISSUE #37894: Clipboard issues with RDP, v 15.0.0
I am having issues using the clipboard in Windows Desktop Access (Remote Desktop).
I used the latest Edge Browser on Windows 11. (Firefox did not allow any Clipboard access at all)

### Expected behavior:
seamless clipboard access without errors

### Current behavior:
- tiny amount of text in clipboard works as expected (about 500 characters).
- when I have more than about 1024 chars in clipboard, then try to start a remote session, I immediately get an error:
_Disconnected: ClipboardData: client_update_clipboard (len=1027): 1_
- when I have much more, e.g. 10'000 chars in clipboard, I do not get an immediate error, but the session freezes quite immediately, and after a longer time (can be several minutes) I then sometimes see a similar error:
_Disconnected: ClipboardData: client_update_clipboard (len=10428): 1_

#### Recreation steps:
using the Edge Browser,
put < 1000 chars in clipboard, connect to a windows server, should work.
put > 1024 chars in clipboard, connect to a windows server, fails with error immediately
put > 10000 chars in clipboard, connect to a windows server, connection works, but when I click in the window, it freezes. Sometimes I saw the error after a long freeze. Emptying the clipboard (or puttung just a few chars inside) and then reconnecting to the same session makes it all work again.

### LINKED ISSUE #37940: Desktop Access Directory Sharing: reads hang indefinitely on `teleport-windows-auth-setup-v15.0.1-amd64.exe`
When sharing a directory with `teleport-windows-auth-setup-v15.0.1-amd64.exe` in it on macOS Sonoma (14.3) with Brave Version 1.62.156 Chromium: 121.0.6167.139 (Official Build) (arm64) I am running into read requests for that file which elicit no response.

This causes the entire operating system to freeze up, suggesting that we ought to implement some sort of timeout on read (and write) requests.

It's also curious that this particular file is causing a problem, perhaps it's related to attempting to read a windows executable on a macOS. We should debug this as well.

image

Update: when I disconnected that session I wound up with logs suggesting that the read did somehow complete, then a bunch of weird logs about "skipping unimplemented message type ScreenSpec" followed by a `unsupported desktop protocol message type 140` error.

<details>

```
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] req=ServerCreateDriveRequest(DeviceCreateRequest { device_io_request: DeviceIoRequest { device_id: 2, file_id: 0, completion_id: 4, major_function: Create, minor_function: MinorFunction(0x00000000) }, desired_access: DesiredAccess(FILE_READ_DATA_OR_FILE_LIST_DIRECTORY | FILE_READ_EA | FILE_READ_ATTRIBUTES | READ_CONTROL | SYNCHRONIZE), allocation_size: 0, file_attributes: FileAttributes(FILE_ATTRIBUTE_NORMAL), shared_access: SharedAccess(FILE_SHARE_READ | FILE_SHARE_DELETE), create_disposition: CreateDisposition(FILE_OPEN), create_options: CreateOptions(FILE_SYNCHRONOUS_IO_NONALERT | FILE_NON_DIRECTORY_FILE), path: "\\teleport-windows-auth-setup-v15.0.1-amd64.exe" })
[2024-02-08T17:47:54Z DEBUG rdp_client::rdpdr::filesystem] sending tdp: SharedDirectoryInfoRequest { completion_id: 4, directory_id: 2, path: UnixPath { path: "teleport-windows-auth-setup-v15.0.1-amd64.exe" } }
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 2, file_id: 9, completion_id: 0, major_function: Read, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] req=DeviceReadRequest(DeviceReadRequest { device_io_request: DeviceIoRequest { device_id: 2, file_id: 9, completion_id: 0, major_function: Read, minor_function: MinorFunction(0x00000000) }, length: 32768, offset: 0 })
[2024-02-08T17:47:54Z DEBUG rdp_client::rdpdr::filesystem] sending tdp: SharedDirectoryReadRequest { completion_id: 0, directory_id: 2, path: UnixPath { path: "teleport-windows-auth-setup-v15.0.1-amd64.exe" }, offset: 0, length: 32768 }
[2024-02-08T17:47:54Z DEBUG rdp_client::client] received tdp: SharedDirectoryInfoResponse { completion_id: 4, err_code: Nil, fso: FileSystemObject { last_modified: 1707413303289, size: 7162808, file_type: File, is_empty: 1, path: UnixPath { path: "teleport-windows-auth-setup-v15.0.1-amd64.exe" } } }
[2024-02-08T17:47:54Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceCreateResponse { device_io_reply: DeviceIoResponse { device_id: 2, completion_id: 4, io_status: STATUS_SUCCESS }, file_id: 10, information: Information(0x0) })
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:54Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 2, file_id: 10, completion_id: 5, major_function: QueryInformation, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] req=ServerDriveQueryInformationRequest(ServerDriveQueryInformationRequest { device_io_request: DeviceIoRequest { device_id: 2, file_id: 10, completion_id: 5, major_function: QueryInformation, minor_function: MinorFunction(0x00000000) }, file_info_class_lvl: FileBasicInformation })
[2024-02-08T17:47:54Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(ClientDriveQueryInformationResponse { device_io_response: DeviceIoResponse { device_id: 2, completion_id: 5, io_status: STATUS_SUCCESS }, buffer: Some(Basic(FileBasicInformation { creation_time: 133518869030000000, last_access_time: 133518869030000000, last_write_time: 133518869030000000, change_time: 133518869030000000, file_attributes: FileAttributes(FILE_ATTRIBUTE_NORMAL) })) })
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 168, io_control_code: ReadCacheW }
[2024-02-08T17:47:54Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_File_Freshness", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:54Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 2, file_id: 10, completion_id: 5, major_function: QueryInformation, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=ServerDriveQueryInformationRequest(ServerDriveQueryInformationRequest { device_io_request: DeviceIoRequest { device_id: 2, file_id: 10, completion_id: 5, major_function: QueryInformation, minor_function: MinorFunction(0x00000000) }, file_info_class_lvl: FileStandardInformation })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(ClientDriveQueryInformationResponse { device_io_response: DeviceIoResponse { device_id: 2, completion_id: 5, io_status: STATUS_SUCCESS }, buffer: Some(Standard(FileStandardInformation { allocation_size: 7162808, end_of_file: 7162808, number_of_links: 0, delete_pending: False, directory: False })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 176, io_control_code: ReadCacheW }
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_Container_Freshness", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 160, io_control_code: ReadCacheW }
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardProperty_Read Only Mode_0", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 184, io_control_code: WriteCacheW }
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req.io_control_code=WriteCacheW call=WriteCacheCall(WriteCacheCall { lookup_name: "Cached_CardProperty_Read Only Mode_0", common: WriteCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0] } })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 5, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 5, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 152, io_control_code: ReadCacheW }
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardProperty_Cache Mode_0", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 5, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 5, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 5, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 176, io_control_code: WriteCacheW }
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req.io_control_code=WriteCacheW call=WriteCacheCall(WriteCacheCall { lookup_name: "Cached_CardProperty_Cache Mode_0", common: WriteCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 1, 0, 0, 0] } })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 5, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 5, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 5, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 192, io_control_code: ReadCacheW }
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardProperty_Supports Windows x.509 Enrollment_0", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 5, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 216, io_control_code: WriteCacheW }
[2024-02-08T17:47:55Z DEBUG ironrdp_rdpdr] req.io_control_code=WriteCacheW call=WriteCacheCall(WriteCacheCall { lookup_name: "Cached_CardProperty_Supports Windows x.509 Enrollment_0", common: WriteCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0] } })
[2024-02-08T17:47:55Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 152, io_control_code: ReadCacheW }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_GeneralFile/mscp/cmapfile", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 152, io_control_code: ReadCacheW }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_CMAPFile", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 184, io_control_code: ReadCacheW }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_PIV_Authentication_Key", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 11, send_buffer: [0, 203, 63, 255, 5, 92, 3, 95, 193, 5, 0], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetData, p1: 63, p2: 255, data: [92, 3, 95, 193, 5], le: 256, extended: false }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] command data: 5C035FC105
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] send response: Response { data: Some([83, 130, 4, 189, 112, 130, 4, 180, 48, 130, 4, 176, 48, 130, 3, 152, 160, 3, 2, 1, 2, 2, 17, 0, 199, 148, 88, 0, 8, 108, 105, 206, 248, 163, 66, 249, 224, 41, 24, 59, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 122, 49, 34, 48, 32, 6, 3, 85, 4, 10, 19, 25, 73, 115, 97, 105, 97, 104, 115, 45, 77, 97, 99, 66, 111, 111, 107, 45, 80, 114, 111, 46, 108, 111, 99, 97, 108, 49, 34, 48, 32, 6, 3, 85, 4, 3, 19, 25, 73, 115, 97, 105, 97, 104, 115, 45, 77, 97, 99, 66, 111, 111, 107, 45, 80, 114, 111, 46, 108, 111, 99, 97, 108, 49, 48, 48, 46, 6, 3, 85, 4, 5, 19, 39, 49, 56, 57, 50, 51, 56, 51, 48, 50, 52, 50, 50, 52, 48, 52, 56, 56, 56, 48, 49, 48, 51, 50, 56, 57, 49, 53, 53, 55, 56, 55, 54, 55, 50, 52, 57, 50, 53, 51, 48, 30, 23, 13, 50, 52, 48, 50, 48, 56, 49, 55, 52, 54, 49, 54, 90, 23, 13, 50, 52, 48, 50, 48, 56, 49, 55, 53, 50, 49, 54, 90, 48, 24, 49, 22, 48, 20, 6, 3, 85, 4, 3, 19, 13, 65, 100, 109, 105, 110, 105, 115, 116, 114, 97, 116, 111, 114, 48, 130, 1, 34, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 1, 5, 0]), status: MoreAvailable(0) }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] response data: 538204BD708204B4308204B030820398A003020102021100C7945800086C69CEF8A342F9E029183B300D06092A864886F70D01010B0500307A31223020060355040A1319497361696168732D4D6163426F6F6B2D50726F2E6C6F63616C3122302006035504031319497361696168732D4D6163426F6F6B2D50726F2E6C6F63616C3130302E06035504051327313839323338333032343232343034383838303130333238393135353738373637323439323533301E170D3234303230383137343631365A170D3234303230383137353231365A3018311630140603550403130D41646D696E6973747261746F7230820122300D06092A864886F70D01010105006100
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [83, 130, 4, 189, 112, 130, 4, 180, 48, 130, 4, 176, 48, 130, 3, 152, 160, 3, 2, 1, 2, 2, 17, 0, 199, 148, 88, 0, 8, 108, 105, 206, 248, 163, 66, 249, 224, 41, 24, 59, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 122, 49, 34, 48, 32, 6, 3, 85, 4, 10, 19, 25, 73, 115, 97, 105, 97, 104, 115, 45, 77, 97, 99, 66, 111, 111, 107, 45, 80, 114, 111, 46, 108, 111, 99, 97, 108, 49, 34, 48, 32, 6, 3, 85, 4, 3, 19, 25, 73, 115, 97, 105, 97, 104, 115, 45, 77, 97, 99, 66, 111, 111, 107, 45, 80, 114, 111, 46, 108, 111, 99, 97, 108, 49, 48, 48, 46, 6, 3, 85, 4, 5, 19, 39, 49, 56, 57, 50, 51, 56, 51, 48, 50, 52, 50, 50, 52, 48, 52, 56, 56, 56, 48, 49, 48, 51, 50, 56, 57, 49, 53, 53, 55, 56, 55, 54, 55, 50, 52, 57, 50, 53, 51, 48, 30, 23, 13, 50, 52, 48, 50, 48, 56, 49, 55, 52, 54, 49, 54, 90, 23, 13, 50, 52, 48, 50, 48, 56, 49, 55, 53, 50, 49, 54, 90, 48, 24, 49, 22, 48, 20, 6, 3, 85, 4, 3, 19, 13, 65, 100, 109, 105, 110, 105, 115, 116, 114, 97, 116, 111, 114, 48, 130, 1, 34, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 1, 5, 0, 97, 0] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 5, send_buffer: [0, 192, 0, 0, 0], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetResponse, p1: 0, p2: 0, data: [], le: 256, extended: false }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] command data: 
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] send response: Response { data: Some([3, 130, 1, 15, 0, 48, 130, 1, 10, 2, 130, 1, 1, 0, 179, 105, 59, 194, 152, 17, 63, 42, 79, 137, 114, 228, 255, 123, 81, 203, 116, 64, 45, 253, 212, 135, 5, 91, 163, 134, 135, 158, 147, 134, 72, 191, 247, 25, 78, 181, 156, 5, 183, 121, 52, 67, 108, 16, 21, 211, 196, 243, 159, 166, 57, 53, 21, 18, 169, 41, 179, 123, 34, 183, 249, 0, 56, 240, 216, 86, 8, 99, 43, 49, 230, 119, 169, 84, 176, 45, 223, 81, 177, 105, 193, 253, 50, 0, 127, 72, 161, 91, 8, 146, 250, 34, 243, 82, 99, 173, 175, 138, 108, 181, 146, 178, 154, 140, 98, 251, 140, 171, 190, 15, 61, 219, 252, 154, 151, 241, 104, 38, 16, 199, 116, 213, 77, 72, 132, 95, 46, 59, 193, 54, 193, 182, 202, 20, 40, 183, 68, 239, 42, 13, 188, 177, 118, 66, 67, 248, 174, 115, 158, 30, 133, 246, 234, 4, 201, 227, 102, 2, 157, 182, 41, 96, 105, 182, 63, 45, 44, 64, 240, 142, 93, 199, 207, 232, 12, 34, 198, 109, 108, 139, 146, 3, 242, 0, 1, 26, 121, 96, 130, 108, 133, 26, 1, 151, 36, 193, 180, 100, 249, 194, 53, 173, 242, 140, 44, 54, 102, 47, 109, 110, 148, 82, 62, 27, 242, 42, 28, 130, 173, 9, 101, 218, 108, 244, 167, 98, 114, 218, 14, 234, 51, 233, 98, 27, 225, 52, 36, 101, 227, 153, 19, 164]), status: MoreAvailable(0) }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] response data: 0382010F003082010A0282010100B3693BC298113F2A4F8972E4FF7B51CB74402DFDD487055BA386879E938648BFF7194EB59C05B77934436C1015D3C4F39FA639351512A929B37B22B7F90038F0D85608632B31E677A954B02DDF51B169C1FD32007F48A15B0892FA22F35263ADAF8A6CB592B29A8C62FB8CABBE0F3DDBFC9A97F1682610C774D54D48845F2E3BC136C1B6CA1428B744EF2A0DBCB1764243F8AE739E1E85F6EA04C9E366029DB6296069B63F2D2C40F08E5DC7CFE80C22C66D6C8B9203F200011A7960826C851A019724C1B464F9C235ADF28C2C36662F6D6E94523E1BF22A1C82AD0965DA6CF4A76272DA0EEA33E9621BE1342465E39913A46100
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [3, 130, 1, 15, 0, 48, 130, 1, 10, 2, 130, 1, 1, 0, 179, 105, 59, 194, 152, 17, 63, 42, 79, 137, 114, 228, 255, 123, 81, 203, 116, 64, 45, 253, 212, 135, 5, 91, 163, 134, 135, 158, 147, 134, 72, 191, 247, 25, 78, 181, 156, 5, 183, 121, 52, 67, 108, 16, 21, 211, 196, 243, 159, 166, 57, 53, 21, 18, 169, 41, 179, 123, 34, 183, 249, 0, 56, 240, 216, 86, 8, 99, 43, 49, 230, 119, 169, 84, 176, 45, 223, 81, 177, 105, 193, 253, 50, 0, 127, 72, 161, 91, 8, 146, 250, 34, 243, 82, 99, 173, 175, 138, 108, 181, 146, 178, 154, 140, 98, 251, 140, 171, 190, 15, 61, 219, 252, 154, 151, 241, 104, 38, 16, 199, 116, 213, 77, 72, 132, 95, 46, 59, 193, 54, 193, 182, 202, 20, 40, 183, 68, 239, 42, 13, 188, 177, 118, 66, 67, 248, 174, 115, 158, 30, 133, 246, 234, 4, 201, 227, 102, 2, 157, 182, 41, 96, 105, 182, 63, 45, 44, 64, 240, 142, 93, 199, 207, 232, 12, 34, 198, 109, 108, 139, 146, 3, 242, 0, 1, 26, 121, 96, 130, 108, 133, 26, 1, 151, 36, 193, 180, 100, 249, 194, 53, 173, 242, 140, 44, 54, 102, 47, 109, 110, 148, 82, 62, 27, 242, 42, 28, 130, 173, 9, 101, 218, 108, 244, 167, 98, 114, 218, 14, 234, 51, 233, 98, 27, 225, 52, 36, 101, 227, 153, 19, 164, 97, 0] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 5, send_buffer: [0, 192, 0, 0, 0], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetResponse, p1: 0, p2: 0, data: [], le: 256, extended: false }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] command data: 
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] send response: Response { data: Some([157, 211, 65, 169, 36, 82, 35, 232, 186, 167, 176, 166, 20, 185, 2, 3, 1, 0, 1, 163, 130, 1, 145, 48, 130, 1, 141, 48, 14, 6, 3, 85, 29, 15, 1, 1, 255, 4, 4, 3, 2, 7, 128, 48, 12, 6, 3, 85, 29, 19, 1, 1, 255, 4, 2, 48, 0, 48, 31, 6, 3, 85, 29, 35, 4, 24, 48, 22, 128, 20, 171, 253, 63, 101, 19, 143, 160, 188, 223, 135, 95, 0, 250, 242, 75, 243, 201, 83, 122, 126, 48, 129, 213, 6, 3, 85, 29, 31, 4, 129, 205, 48, 129, 202, 48, 129, 199, 160, 129, 196, 160, 129, 193, 134, 129, 190, 108, 100, 97, 112, 58, 47, 47, 47, 67, 78, 61, 73, 115, 97, 105, 97, 104, 115, 45, 77, 97, 99, 66, 111, 111, 107, 45, 80, 114, 111, 46, 108, 111, 99, 97, 108, 44, 67, 78, 61, 84, 101, 108, 101, 112, 111, 114, 116, 44, 67, 78, 61, 67, 68, 80, 44, 67, 78, 61, 80, 117, 98, 108, 105, 99, 32, 75, 101, 121, 32, 83, 101, 114, 118, 105, 99, 101, 115, 44, 67, 78, 61, 83, 101, 114, 118, 105, 99, 101, 115, 44, 67, 78, 61, 67, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 44, 68, 67, 61, 116, 101, 108, 101, 112, 111, 114, 116, 44, 68, 67, 61, 100, 101, 118, 63, 99, 101, 114, 116, 105, 102, 105, 99, 97, 116, 101, 82, 101]), status: MoreAvailable(0) }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] response data: 9DD341A9245223E8BAA7B0A614B90203010001A38201913082018D300E0603551D0F0101FF040403020780300C0603551D130101FF04023000301F0603551D23041830168014ABFD3F65138FA0BCDF875F00FAF24BF3C9537A7E3081D50603551D1F0481CD3081CA3081C7A081C4A081C18681BE6C6461703A2F2F2F434E3D497361696168732D4D6163426F6F6B2D50726F2E6C6F63616C2C434E3D54656C65706F72742C434E3D4344502C434E3D5075626C6963204B65792053657276696365732C434E3D53657276696365732C434E3D436F6E66696775726174696F6E2C44433D74656C65706F72742C44433D6465763F636572746966696361746552656100
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [157, 211, 65, 169, 36, 82, 35, 232, 186, 167, 176, 166, 20, 185, 2, 3, 1, 0, 1, 163, 130, 1, 145, 48, 130, 1, 141, 48, 14, 6, 3, 85, 29, 15, 1, 1, 255, 4, 4, 3, 2, 7, 128, 48, 12, 6, 3, 85, 29, 19, 1, 1, 255, 4, 2, 48, 0, 48, 31, 6, 3, 85, 29, 35, 4, 24, 48, 22, 128, 20, 171, 253, 63, 101, 19, 143, 160, 188, 223, 135, 95, 0, 250, 242, 75, 243, 201, 83, 122, 126, 48, 129, 213, 6, 3, 85, 29, 31, 4, 129, 205, 48, 129, 202, 48, 129, 199, 160, 129, 196, 160, 129, 193, 134, 129, 190, 108, 100, 97, 112, 58, 47, 47, 47, 67, 78, 61, 73, 115, 97, 105, 97, 104, 115, 45, 77, 97, 99, 66, 111, 111, 107, 45, 80, 114, 111, 46, 108, 111, 99, 97, 108, 44, 67, 78, 61, 84, 101, 108, 101, 112, 111, 114, 116, 44, 67, 78, 61, 67, 68, 80, 44, 67, 78, 61, 80, 117, 98, 108, 105, 99, 32, 75, 101, 121, 32, 83, 101, 114, 118, 105, 99, 101, 115, 44, 67, 78, 61, 83, 101, 114, 118, 105, 99, 101, 115, 44, 67, 78, 61, 67, 111, 110, 102, 105, 103, 117, 114, 97, 116, 105, 111, 110, 44, 68, 67, 61, 116, 101, 108, 101, 112, 111, 114, 116, 44, 68, 67, 61, 100, 101, 118, 63, 99, 101, 114, 116, 105, 102, 105, 99, 97, 116, 101, 82, 101, 97, 0] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 5, send_buffer: [0, 192, 0, 0, 0], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetResponse, p1: 0, p2: 0, data: [], le: 256, extended: false }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] command data: 
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] send response: Response { data: Some([118, 111, 99, 97, 116, 105, 111, 110, 76, 105, 115, 116, 63, 98, 97, 115, 101, 63, 111, 98, 106, 101, 99, 116, 67, 108, 97, 115, 115, 61, 99, 82, 76, 68, 105, 115, 116, 114, 105, 98, 117, 116, 105, 111, 110, 80, 111, 105, 110, 116, 48, 31, 6, 3, 85, 29, 37, 4, 24, 48, 22, 6, 8, 43, 6, 1, 5, 5, 7, 3, 2, 6, 10, 43, 6, 1, 4, 1, 130, 55, 20, 2, 2, 48, 53, 6, 3, 85, 29, 17, 4, 46, 48, 44, 160, 42, 6, 10, 43, 6, 1, 4, 1, 130, 55, 20, 2, 3, 160, 28, 12, 26, 65, 100, 109, 105, 110, 105, 115, 116, 114, 97, 116, 111, 114, 64, 116, 101, 108, 101, 112, 111, 114, 116, 46, 100, 101, 118, 48, 12, 6, 5, 43, 206, 15, 2, 14, 4, 3, 111, 115, 115, 48, 14, 6, 5, 43, 206, 15, 2, 17, 4, 5, 102, 97, 108, 115, 101, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 3, 130, 1, 1, 0, 83, 148, 187, 82, 89, 204, 185, 102, 8, 74, 57, 209, 221, 88, 70, 193, 4, 231, 18, 90, 177, 180, 209, 49, 237, 178, 218, 118, 86, 238, 142, 253, 31, 5, 217, 97, 18, 195, 161, 62, 213, 93, 69, 238, 50, 93, 45, 203, 90, 121, 229, 32, 121, 37, 121, 96, 82, 187, 85, 152, 250, 39, 187, 48, 88, 139, 169, 103]), status: MoreAvailable(193) }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] response data: 766F636174696F6E4C6973743F626173653F6F626A656374436C6173733D63524C446973747269627574696F6E506F696E74301F0603551D250418301606082B06010505070302060A2B06010401823714020230350603551D11042E302CA02A060A2B060104018237140203A01C0C1A41646D696E6973747261746F724074656C65706F72742E646576300C06052BCE0F020E04036F7373300E06052BCE0F0211040566616C7365300D06092A864886F70D01010B050003820101005394BB5259CCB966084A39D1DD5846C104E7125AB1B4D131EDB2DA7656EE8EFD1F05D96112C3A13ED55D45EE325D2DCB5A79E5207925796052BB5598FA27BB30588BA96761C1
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [118, 111, 99, 97, 116, 105, 111, 110, 76, 105, 115, 116, 63, 98, 97, 115, 101, 63, 111, 98, 106, 101, 99, 116, 67, 108, 97, 115, 115, 61, 99, 82, 76, 68, 105, 115, 116, 114, 105, 98, 117, 116, 105, 111, 110, 80, 111, 105, 110, 116, 48, 31, 6, 3, 85, 29, 37, 4, 24, 48, 22, 6, 8, 43, 6, 1, 5, 5, 7, 3, 2, 6, 10, 43, 6, 1, 4, 1, 130, 55, 20, 2, 2, 48, 53, 6, 3, 85, 29, 17, 4, 46, 48, 44, 160, 42, 6, 10, 43, 6, 1, 4, 1, 130, 55, 20, 2, 3, 160, 28, 12, 26, 65, 100, 109, 105, 110, 105, 115, 116, 114, 97, 116, 111, 114, 64, 116, 101, 108, 101, 112, 111, 114, 116, 46, 100, 101, 118, 48, 12, 6, 5, 43, 206, 15, 2, 14, 4, 3, 111, 115, 115, 48, 14, 6, 5, 43, 206, 15, 2, 17, 4, 5, 102, 97, 108, 115, 101, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 11, 5, 0, 3, 130, 1, 1, 0, 83, 148, 187, 82, 89, 204, 185, 102, 8, 74, 57, 209, 221, 88, 70, 193, 4, 231, 18, 90, 177, 180, 209, 49, 237, 178, 218, 118, 86, 238, 142, 253, 31, 5, 217, 97, 18, 195, 161, 62, 213, 93, 69, 238, 50, 93, 45, 203, 90, 121, 229, 32, 121, 37, 121, 96, 82, 187, 85, 152, 250, 39, 187, 48, 88, 139, 169, 103, 97, 193] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 5, send_buffer: [0, 192, 0, 0, 193], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetResponse, p1: 0, p2: 0, data: [], le: 193, extended: false }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] command data: 
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] send response: Response { data: Some([90, 121, 156, 28, 143, 109, 49, 96, 60, 216, 227, 134, 249, 63, 233, 8, 199, 73, 120, 126, 214, 86, 239, 199, 67, 130, 36, 20, 188, 11, 74, 109, 171, 69, 189, 154, 73, 174, 75, 90, 73, 228, 210, 95, 0, 148, 191, 28, 213, 147, 6, 198, 242, 108, 171, 218, 230, 15, 42, 224, 239, 191, 127, 142, 85, 67, 172, 196, 156, 89, 8, 196, 190, 55, 38, 22, 242, 2, 207, 183, 249, 126, 33, 215, 79, 62, 202, 115, 192, 18, 135, 94, 136, 150, 186, 164, 25, 177, 210, 222, 190, 237, 214, 225, 240, 152, 41, 130, 90, 78, 119, 32, 106, 202, 228, 164, 130, 71, 170, 149, 57, 238, 152, 15, 190, 242, 81, 232, 87, 205, 10, 252, 231, 204, 12, 36, 7, 45, 119, 125, 26, 222, 14, 99, 153, 182, 138, 208, 12, 218, 72, 59, 57, 197, 144, 134, 175, 21, 249, 26, 182, 43, 104, 241, 187, 39, 122, 228, 4, 168, 5, 100, 3, 99, 161, 170, 20, 243, 95, 156, 131, 1, 65, 102, 195, 191, 75, 237, 113, 1, 0, 254, 0]), status: Success }
[2024-02-08T17:47:56Z DEBUG rdp_client::piv] response data: 5A799C1C8F6D31603CD8E386F93FE908C749787ED656EFC743822414BC0B4A6DAB45BD9A49AE4B5A49E4D25F0094BF1CD59306C6F26CABDAE60F2AE0EFBF7F8E5543ACC49C5908C4BE372616F202CFB7F97E21D74F3ECA73C012875E8896BAA419B1D2DEBEEDD6E1F09829825A4E77206ACAE4A48247AA9539EE980FBEF251E857CD0AFCE7CC0C24072D777D1ADE0E6399B68AD00CDA483B39C59086AF15F91AB62B68F1BB277AE404A805640363A1AA14F35F9C83014166C3BF4BED710100FE009000
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [90, 121, 156, 28, 143, 109, 49, 96, 60, 216, 227, 134, 249, 63, 233, 8, 199, 73, 120, 126, 214, 86, 239, 199, 67, 130, 36, 20, 188, 11, 74, 109, 171, 69, 189, 154, 73, 174, 75, 90, 73, 228, 210, 95, 0, 148, 191, 28, 213, 147, 6, 198, 242, 108, 171, 218, 230, 15, 42, 224, 239, 191, 127, 142, 85, 67, 172, 196, 156, 89, 8, 196, 190, 55, 38, 22, 242, 2, 207, 183, 249, 126, 33, 215, 79, 62, 202, 115, 192, 18, 135, 94, 136, 150, 186, 164, 25, 177, 210, 222, 190, 237, 214, 225, 240, 152, 41, 130, 90, 78, 119, 32, 106, 202, 228, 164, 130, 71, 170, 149, 57, 238, 152, 15, 190, 242, 81, 232, 87, 205, 10, 252, 231, 204, 12, 36, 7, 45, 119, 125, 26, 222, 14, 99, 153, 182, 138, 208, 12, 218, 72, 59, 57, 197, 144, 134, 175, 21, 249, 26, 182, 43, 104, 241, 187, 39, 122, 228, 4, 168, 5, 100, 3, 99, 161, 170, 20, 243, 95, 156, 131, 1, 65, 102, 195, 191, 75, 237, 113, 1, 0, 254, 0, 144, 0] })) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:56Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:56Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 464, io_control_code: WriteCacheW }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=WriteCacheW call=WriteCacheCall(WriteCacheCall { lookup_name: "Cached_CardmodFile\\Cached_PIV_Authentication_Key", common: WriteCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data: [6, 2, 0, 0, 0, 164, 0, 0, 82, 83, 65, 49, 0, 8, 0, 0, 1, 0, 1, 0, 185, 20, 166, 176, 167, 186, 232, 35, 82, 36, 169, 65, 211, 157, 164, 19, 153, 227, 101, 36, 52, 225, 27, 98, 233, 51, 234, 14, 218, 114, 98, 167, 244, 108, 218, 101, 9, 173, 130, 28, 42, 242, 27, 62, 82, 148, 110, 109, 47, 102, 54, 44, 140, 242, 173, 53, 194, 249, 100, 180, 193, 36, 151, 1, 26, 133, 108, 130, 96, 121, 26, 1, 0, 242, 3, 146, 139, 108, 109, 198, 34, 12, 232, 207, 199, 93, 142, 240, 64, 44, 45, 63, 182, 105, 96, 41, 182, 157, 2, 102, 227, 201, 4, 234, 246, 133, 30, 158, 115, 174, 248, 67, 66, 118, 177, 188, 13, 42, 239, 68, 183, 40, 20, 202, 182, 193, 54, 193, 59, 46, 95, 132, 72, 77, 213, 116, 199, 16, 38, 104, 241, 151, 154, 252, 219, 61, 15, 190, 171, 140, 251, 98, 140, 154, 178, 146, 181, 108, 138, 175, 173, 99, 82, 243, 34, 250, 146, 8, 91, 161, 72, 127, 0, 50, 253, 193, 105, 177, 81, 223, 45, 176, 84, 169, 119, 230, 49, 43, 99, 8, 86, 216, 240, 56, 0, 249, 183, 34, 123, 179, 41, 169, 18, 21, 53, 57, 166, 159, 243, 196, 211, 21, 16, 108, 67, 52, 121, 183, 5, 156, 181, 78, 25, 247, 191, 72, 134, 147, 158, 135, 134, 163, 91, 5, 135, 212, 253, 45, 64, 116, 203, 81, 123, 255, 228, 114, 137, 79, 42, 63, 17, 152, 194, 59, 105, 179] } })
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 168, io_control_code: ReadCacheW }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_PIV_Signature_Key", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 11, send_buffer: [0, 203, 63, 255, 5, 92, 3, 95, 193, 10, 0], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetData, p1: 63, p2: 255, data: [92, 3, 95, 193, 10], le: 256, extended: false }
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] command data: 5C035FC10A
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] send response: Response { data: None, status: NotFound }
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] response data: 6A82
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [106, 130] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 184, io_control_code: ReadCacheW }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_PIV_Key_Management_Key", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 11, send_buffer: [0, 203, 63, 255, 5, 92, 3, 95, 193, 11, 0], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetData, p1: 63, p2: 255, data: [92, 3, 95, 193, 11], le: 256, extended: false }
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] command data: 5C035FC10B
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] send response: Response { data: None, status: NotFound }
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] response data: 6A82
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [106, 130] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 192, io_control_code: ReadCacheW }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_PIV_Card_Authentication_Key", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 11, send_buffer: [0, 203, 63, 255, 5, 92, 3, 95, 193, 1, 0], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetData, p1: 63, p2: 255, data: [92, 3, 95, 193, 1], le: 256, extended: false }
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] command data: 5C035FC101
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] send response: Response { data: None, status: NotFound }
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] response data: 6A82
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [106, 130] })) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 96, io_control_code: Transmit }
[2024-02-08T17:47:57Z DEBUG ironrdp_rdpdr] req.io_control_code=Transmit call=TransmitCall(TransmitCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, send_pci: SCardIORequest { protocol: CardProtocol(SCARD_PROTOCOL_T1), extra_bytes_length: 0, extra_bytes: [] }, send_length: 11, send_buffer: [0, 203, 63, 255, 5, 92, 3, 95, 193, 12, 0], recv_pci: None, recv_buffer_is_null: false, recv_length: 258 })
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] got command: Command { class: Class { cla: 0, range: Interindustry(First) }, instruction: GetData, p1: 63, p2: 255, data: [92, 3, 95, 193, 12], le: 256, extended: false }
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] command data: 5C035FC10C
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] send response: Response { data: None, status: NotFound }
[2024-02-08T17:47:57Z DEBUG rdp_client::piv] response data: 6A82
[2024-02-08T17:47:57Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(TransmitReturn { return_code: Success, recv_pci: None, recv_buffer: [106, 130] })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 248, io_control_code: WriteCacheW }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=WriteCacheW call=WriteCacheCall(WriteCacheCall { lookup_name: "Cached_CardmodFile\\Cached_CMAPFile", common: WriteCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data: [54, 0, 97, 0, 48, 0, 98, 0, 56, 0, 57, 0, 98, 0, 51, 0, 45, 0, 53, 0, 49, 0, 56, 0, 98, 0, 45, 0, 102, 0, 53, 0, 52, 0, 99, 0, 45, 0, 98, 0, 97, 0, 55, 0, 102, 0, 45, 0, 53, 0, 99, 0, 56, 0, 51, 0, 51, 0, 99, 0, 53, 0, 102, 0, 99, 0, 49, 0, 48, 0, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 8] } })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 152, io_control_code: ReadCacheW }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_CMAPFile", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: Success, data: [54, 0, 97, 0, 48, 0, 98, 0, 56, 0, 57, 0, 98, 0, 51, 0, 45, 0, 53, 0, 49, 0, 56, 0, 98, 0, 45, 0, 102, 0, 53, 0, 52, 0, 99, 0, 45, 0, 98, 0, 97, 0, 55, 0, 102, 0, 45, 0, 53, 0, 99, 0, 56, 0, 51, 0, 51, 0, 99, 0, 53, 0, 102, 0, 99, 0, 49, 0, 48, 0, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 8] })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 256, io_control_code: WriteCacheW }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=WriteCacheW call=WriteCacheCall(WriteCacheCall { lookup_name: "Cached_GeneralFile/mscp/cmapfile", common: WriteCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 86, 0, 0, 0, 54, 0, 97, 0, 48, 0, 98, 0, 56, 0, 57, 0, 98, 0, 51, 0, 45, 0, 53, 0, 49, 0, 56, 0, 98, 0, 45, 0, 102, 0, 53, 0, 52, 0, 99, 0, 45, 0, 98, 0, 97, 0, 55, 0, 102, 0, 45, 0, 53, 0, 99, 0, 56, 0, 51, 0, 51, 0, 99, 0, 53, 0, 102, 0, 99, 0, 49, 0, 48, 0, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 8] } })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 32, io_control_code: ReleaseContext }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=ReleaseContext call=ContextCall(ContextCall { context: ScardContext { value: 9 } })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 56, io_control_code: EndTransaction }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=EndTransaction call=HCardAndDispositionCall(HCardAndDispositionCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, disposition: 0 })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 64, io_control_code: StatusW }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=StatusW call=StatusCall(StatusCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, reader_names_is_null: false, reader_length: 4294967295, atr_length: 32 })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(StatusReturn { return_code: Success, reader_names: ["Teleport"], state: SpecificMode, protocol: CardProtocol(SCARD_PROTOCOL_T1), atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], atr_length: 11, encoding: Unicode })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 56, io_control_code: BeginTransaction }
[2024-02-08T17:47:58Z DEBUG ironrdp_rdpdr] req.io_control_code=BeginTransaction call=HCardAndDispositionCall(HCardAndDispositionCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, disposition: 0 })
[2024-02-08T17:47:58Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 160, io_control_code: ReadCacheW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_Pin_Freshness", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 168, io_control_code: ReadCacheW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_File_Freshness", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 136, io_control_code: GetStatusChangeW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=GetStatusChangeW call=GetStatusChangeCall(GetStatusChangeCall { context: ScardContext { value: 10 }, timeout: 0, states_ptr_length: 1, states_ptr: 131076, states_length: 1, states: [ReaderState { reader: "Teleport", common: ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(0x0), atr_length: 0, atr: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] } }] })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetStatusChangeReturn { return_code: Success, reader_states: [ReaderStateCommonCall { current_state: CardStateFlags(0x0), event_state: CardStateFlags(SCARD_STATE_CHANGED | SCARD_STATE_PRESENT), atr_length: 11, atr: [59, 149, 19, 129, 1, 128, 115, 255, 1, 0, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 176, io_control_code: ReadCacheW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_CardmodFile\\Cached_Container_Freshness", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 152, io_control_code: ReadCacheW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_GeneralFile/mscp/cmapfile", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: Success, data: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 86, 0, 0, 0, 54, 0, 97, 0, 48, 0, 98, 0, 56, 0, 57, 0, 98, 0, 51, 0, 45, 0, 53, 0, 49, 0, 56, 0, 98, 0, 45, 0, 102, 0, 53, 0, 52, 0, 99, 0, 45, 0, 98, 0, 97, 0, 55, 0, 102, 0, 45, 0, 53, 0, 99, 0, 56, 0, 51, 0, 51, 0, 99, 0, 53, 0, 102, 0, 99, 0, 49, 0, 48, 0, 53, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 8] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 32, io_control_code: ReleaseContext }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=ReleaseContext call=ContextCall(ContextCall { context: ScardContext { value: 8 } })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 144, io_control_code: ReadCacheW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=ReadCacheW call=ReadCacheCall(ReadCacheCall { lookup_name: "Cached_GeneralFile/mscp/msroots", common: ReadCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data_is_null: false, data_len: 4294967295 } })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(ReadCacheReturn { return_code: CacheItemNotFound, data: [] })) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 168, io_control_code: WriteCacheW }
[2024-02-08T17:47:59Z DEBUG ironrdp_rdpdr] req.io_control_code=WriteCacheW call=WriteCacheCall(WriteCacheCall { lookup_name: "Cached_GeneralFile/mscp/msroots", common: WriteCacheCommon { context: ScardContext { value: 10 }, card_uuid: [179, 137, 11, 106, 139, 81, 76, 245, 186, 127, 92, 131, 60, 136, 84, 135], freshness_counter: 0, data: [1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0] } })
[2024-02-08T17:47:59Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 56, io_control_code: EndTransaction }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=EndTransaction call=HCardAndDispositionCall(HCardAndDispositionCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, disposition: 0 })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 32, io_control_code: Cancel }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=Cancel call=ContextCall(ContextCall { context: ScardContext { value: 10 } })
[2024-02-08T17:48:00Z WARN  rdp_client::rdpdr::scard] Received SCARD_IOCTL_CANCEL for a context without a pending SCARD_IOCTL_GETSTATUSCHANGEW
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 56, io_control_code: Disconnect }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=Disconnect call=HCardAndDispositionCall(HCardAndDispositionCall { handle: ScardHandle { context: ScardContext { value: 10 }, value: 1 }, disposition: 0 })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 32, io_control_code: ReleaseContext }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=ReleaseContext call=ContextCall(ContextCall { context: ScardContext { value: 10 } })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 24, io_control_code: EstablishContext }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=EstablishContext call=EstablishContextCall(EstablishContextCall { scope: System })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(EstablishContextReturn { return_code: Success, context: ScardContext { value: 11 } })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 72, io_control_code: GetDeviceTypeId }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=GetDeviceTypeId call=GetDeviceTypeIdCall(GetDeviceTypeIdCall { context: ScardContext { value: 11 }, reader_ptr: 131076, reader_name: "Teleport" })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetDeviceTypeIdReturn { return_code: Success, device_type_id: 240 })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 32, io_control_code: ReleaseContext }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=ReleaseContext call=ContextCall(ContextCall { context: ScardContext { value: 11 } })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 2048, input_buffer_length: 24, io_control_code: EstablishContext }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=EstablishContext call=EstablishContextCall(EstablishContextCall { scope: System })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(EstablishContextReturn { return_code: Success, context: ScardContext { value: 12 } })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 133120, input_buffer_length: 72, io_control_code: GetReaderIcon }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=GetReaderIcon call=GetReaderIconCall(GetReaderIconCall { context: ScardContext { value: 12 }, reader_name: "Teleport" })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(GetReaderIconReturn { return_code: UnsupportedFeature, data: [] })) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] received RdpdrPdu(DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) })
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req=DeviceControlRequest { header: DeviceIoRequest { device_id: 1, file_id: 1, completion_id: 3, major_function: DeviceControl, minor_function: MinorFunction(0x00000000) }, output_buffer_length: 133120, input_buffer_length: 32, io_control_code: ReleaseContext }
[2024-02-08T17:48:00Z DEBUG ironrdp_rdpdr] req.io_control_code=ReleaseContext call=ContextCall(ContextCall { context: ScardContext { value: 12 } })
[2024-02-08T17:48:00Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceControlResponse { device_io_reply: DeviceIoResponse { device_id: 1, completion_id: 3, io_status: STATUS_SUCCESS }, output_buffer: Some(Pdu(LongReturn { return_code: Success })) })
2024-02-08T09:48:30-08:00 DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) pid:23438.2 desktop/discovery.go:105
2024-02-08T09:48:30-08:00 DEBU [WINDOWS_D] discovered 1 Windows Desktops pid:23438.2 desktop/discovery.go:127
2024-02-08T09:48:30-08:00 DEBU [WINDOWS_D] DNS lookup for EC2AMAZ-2VKH71R.teleport.dev failed with default resolver: lookup EC2AMAZ-2VKH71R.teleport.dev: no such host pid:23438.2 desktop/discovery.go:209
2024-02-08T09:48:30-08:00 DEBU [WINDOWS_D] resolved EC2AMAZ-2VKH71R.teleport.dev => [172.31.16.172] pid:23438.2 desktop/discovery.go:270
2024-02-08T09:48:30-08:00 DEBU [WINDOWS_D] Reconciling 1 current resources with 1 new resources. pid:23438.2 services/reconciler.go:114
2024-02-08T09:48:30-08:00 INFO [WINDOWS_D] windows_desktop EC2AMAZ-2VKH71R-teleport-dev-3eaae4a0 updated, updating. pid:23438.2 services/reconciler.go:187
2024-02-08T09:49:10-08:00 DEBU [AUTH:COMP] session has active tracker and is not ready to be uploaded session:91252a0a-5499-4248-8710-e44f81ac1e94 upload:0735e776-3a66-45bc-ac23-2d8905715709 events/complete.go:185
2024-02-08T09:49:19-08:00 DEBU [AUTH:2]    Server certificate cert(8f1ed2bc-65fb-48de-b32f-cac76676f8db.Isaiahs-MacBook-Pro.local issued by Isaiahs-MacBook-Pro.local:281296387376463031351125731320971465316). auth/middleware.go:343
2024-02-08T09:49:19-08:00 DEBU             generated user key for [root ibm ibeckermayer visitor -teleport-internal-join] with expiry on (1707456469) 2024-02-09 05:27:49.318191 +0000 UTC keygen/keygen.go:165
2024-02-08T09:49:19-08:00 INFO [CA]        Generating TLS certificate 1.3.9999.1.15=#13046e6f6e65,1.3.9999.1.9=#13093132372e302e302e31,1.3.9999.1.7=#1319497361696168732d4d6163426f6f6b2d50726f2e6c6f63616c,CN=joe,O=access+O=editor+O=auditor,POSTALCODE={\"kubernetes_groups\":[\"\"]\,\"kubernetes_users\":[\"\"]\,\"logins\":[\"root\"\,\"ibm\"\,\"ibeckermayer\"\,\"visitor\"]\,\"windows_logins\":[\"Administrator\"]},STREET=Isaiahs-MacBook-Pro.local,L=root+L=ibm+L=ibeckermayer+L=visitor+L=-teleport-internal-join dns_names:[] key_usage:5 not_after:2024-02-09 05:27:49.3221 +0000 UTC tlsca/ca.go:1187
2024-02-08T09:49:19-08:00 INFO [AUDIT]     cert.create cert_type:user cluster_name:Isaiahs-MacBook-Pro.local code:TC000I ei:0 event:cert.create client_ip:127.0.0.1 expires:2024-02-09T05:27:49.3221Z logins:[root ibm ibeckermayer visitor -teleport-internal-join] prev_identity_expires:0001-01-01T00:00:00Z private_key_policy:none roles:[access editor auditor] route_to_cluster:Isaiahs-MacBook-Pro.local teleport_cluster:Isaiahs-MacBook-Pro.local kubernetes_groups:[] kubernetes_users:[] logins:[root ibm ibeckermayer visitor] windows_logins:[Administrator] user:joe time:2024-02-08T17:49:19.71Z uid:e6d9d39e-3812-43ae-9ec2-5c6e0839502f events/emitter.go:278
2024-02-08T09:49:19-08:00 DEBU [AUTH:2]    Server certificate cert(8f1ed2bc-65fb-48de-b32f-cac76676f8db.Isaiahs-MacBook-Pro.local issued by Isaiahs-MacBook-Pro.local:281296387376463031351125731320971465316). auth/middleware.go:343
2024-02-08T09:50:49-08:00 DEBU [AUTH:2]    Server certificate cert(8f1ed2bc-65fb-48de-b32f-cac76676f8db.Isaiahs-MacBook-Pro.local issued by Isaiahs-MacBook-Pro.local:281296387376463031351125731320971465316). auth/middleware.go:343
2024-02-08T09:50:50-08:00 DEBU [PROXY:2]   List of known proxies updated: ["8f1ed2bc-65fb-48de-b32f-cac76676f8db"]. pid:23438.2 services/watcher.go:491
2024-02-08T09:51:07-08:00 DEBU [AUTH]      Checking for new teleport releases via github api. auth/auth.go:1315
2024-02-08T09:52:09-08:00 DEBU [WEB]       Context expired. ctx:WebSession(user=joe,id=381e,expires=2024-02-09 05:27:49.315876 +0000 UTC,bearer_expires=2024-02-08 17:52:09.704685 +0000 UTC) web/sessions.go:732
2024-02-08T09:52:16-08:00 DEBU             Inactivity timer ticked at 2024-02-08 17:52:16.3703 +0000 UTC, inactivity period: 4m21.338569s have not exceeded threshold. Set timer to tick after 38.661431s. events/stream.go:571
2024-02-08T09:52:46-08:00 INFO [AUDIT]     desktop.directory.read addr.local:127.0.0.1 addr.remote:54.144.205.187:3389 cluster_name:Isaiahs-MacBook-Pro.local code:TDP05I desktop_addr:54.144.205.187:3389 directory_id:2 directory_name:tmp ei:0 event:desktop.directory.read file_path:teleport-windows-auth-setup-v15.0.1-amd64.exe length:32768 offset:0 private_key_policy:none proto:tdp sid:91252a0a-5499-4248-8710-e44f81ac1e94 success:true time:2024-02-08T17:52:46.770651Z uid:cdc11b08-921f-45e5-b02b-2411310387f8 user:joe user_kind:1 events/emitter.go:278
[2024-02-08T17:52:46Z DEBUG rdp_client::client] received tdp: SharedDirectoryReadResponse { completion_id: 0, err_code: Nil, read_data: "&[u8] of length 32768" }
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
[2024-02-08T17:52:46Z DEBUG rdp_client::client] sending rdp: RdpdrPdu(DeviceReadResponse { device_io_reply: DeviceIoResponse { device_id: 2, completion_id: 0, io_status: STATUS_SUCCESS }, read_data: "Vec<u8> of length 32768" })
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Skipping unimplemented TDP message type tdp.ClientScreenSpec client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:603
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] Failed reading TDP input message: unsupported desktop protocol message type 140 client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:348
2024-02-08T09:52:46-08:00 INFO [WINDOWS_D] TDP input streaming finished client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:349
[2024-02-08T17:52:46Z TRACE rdp_client] client_stop
2024-02-08T09:52:46-08:00 INFO [WINDOWS_D] Rust RDP loop finished client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 rdp-addr:54.144.205.187:3389 rdpclient/client.go:316
2024-02-08T09:52:46-08:00 INFO [AUDIT]     windows.desktop.session.end cluster_name:Isaiahs-MacBook-Pro.local code:TDP01I desktop_addr:54.144.205.187:3389 teleport.dev/ad:false teleport.dev/origin:config-file testing1:label1 testing2:label2 testing3:label3 desktop_name:cac76676f8db-static-54-144-205-187 ei:4674 event:windows.desktop.session.end login:Administrator participants:[joe] private_key_policy:none recorded:true session_start:2024-02-08T17:47:16.365Z session_stop:2024-02-08T17:52:46.935808Z sid:91252a0a-5499-4248-8710-e44f81ac1e94 time:2024-02-08T17:52:46.936Z uid:c23fa65d-0ff7-438e-a19b-abe376ed8f1e user:joe user_kind:1 windows_desktop_service:8f1ed2bc-65fb-48de-b32f-cac76676f8db windows_domain:teleport.dev windows_user:Administrator events/emitter.go:278
2024-02-08T09:52:46-08:00 ERRO [WINDOWS_D] RDP connection failed: unsupported desktop protocol message type 140 client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 desktop/windows_server.go:758
2024-02-08T09:52:46-08:00 WARN [WINDOWS_D] could not record desktop recording event error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError context canceled or timed out
Stack Trace:
	github.com/gravitational/teleport/lib/events/session_writer.go:303 github.com/gravitational/teleport/lib/events.(*SessionWriter).RecordEvent
	github.com/gravitational/teleport/lib/events/setter.go:167 github.com/gravitational/teleport/lib/events.SetupAndRecordEvent
	github.com/gravitational/teleport/lib/srv/desktop/windows_server.go:968 github.com/gravitational/teleport/lib/srv/desktop.(*WindowsService).connectRDP.(*WindowsService).makeTDPSendHandler.func5
	github.com/gravitational/teleport/lib/srv/desktop/tdp/conn.go:108 github.com/gravitational/teleport/lib/srv/desktop/tdp.(*Conn).WriteMessage
	github.com/gravitational/teleport/lib/srv/desktop/tdp/conn.go:131 github.com/gravitational/teleport/lib/srv/desktop/tdp.(*Conn).SendNotification
	github.com/gravitational/teleport/lib/srv/desktop/windows_server.go:690 github.com/gravitational/teleport/lib/srv/desktop.(*WindowsService).handleConnection.func1
	github.com/gravitational/teleport/lib/srv/desktop/windows_server.go:764 github.com/gravitational/teleport/lib/srv/desktop.(*WindowsService).handleConnection
	runtime/asm_arm64.s:1222 runtime.goexit
User Message: context canceled or timed out] pid:23438.2 desktop/windows_server.go:969
2024-02-08T09:52:46-08:00 DEBU [WINDOWS_D] Windows desktop disconnected client-ip:127.0.0.1 desktop-addr:54.144.205.187:3389 desktop-name:cac76676f8db-static-54-144-205-187 pid:23438.2 desktop/windows_server.go:765
2024-02-08T09:52:46-08:00 DEBU [WEB]       proxyWebsocketConn returned with no error cluster-name:Isaiahs-MacBook-Pro.local desktop-name:cac76676f8db-static-54-144-205-187 session:381e user:joe windows-service-addr:Isaiahs-MacBook-Pro.local:3028 windows-service-uuid:8f1ed2bc-65fb-48de-b32f-cac76676f8db windows-service-version:16.0.0-dev web/desktop.go:552
2024-02-08T09:52:46-08:00 INFO [AUDIT]     session.upload cluster_name:Isaiahs-MacBook-Pro.local code:T2005I ei:2.147483647e+09 event:session.upload sid:91252a0a-5499-4248-8710-e44f81ac1e94 time:2024-02-08T17:52:46.949Z uid:79f93998-7b74-4992-88a1-3aa09d0b3cfd url:file:///Users/ibeckermayer/teleport-config/desktop-access/data/log/records/multi/91252a0a-5499-4248-8710-e44f81ac1e94 events/emitter.go:278
2024-02-08T09:52:46-08:00 DEBU [AUTH:GRPC] Completed stream for session 91252a0a-5499-4248-8710-e44f81ac1e94 auth/grpcserver.go:330
2024-02-08T09:52:46-08:00 DEBU [AUTH:GRPC] Flushed and closed the stream. auth/grpcserver.go:253
2024-02-08T09:53:30-08:00 DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) pid:23438.2 desktop/discovery.go:105
2024-02-08T09:53:30-08:00 DEBU [WINDOWS_D] discovered 1 Windows Desktops pid:23438.2 desktop/discovery.go:127
2024-02-08T09:53:30-08:00 DEBU [WINDOWS_D] DNS lookup for EC2AMAZ-2VKH71R.teleport.dev failed with default resolver: lookup EC2AMAZ-2VKH71R.teleport.dev: no such host pid:23438.2 desktop/discovery.go:209
2024-02-08T09:53:31-08:00 DEBU [WINDOWS_D] resolved EC2AMAZ-2VKH71R.teleport.dev => [172.31.16.172] pid:23438.2 desktop/discovery.go:270
2024-02-08T09:53:31-08:00 DEBU [WINDOWS_D] Reconciling 1 current resources with 1 new resources. pid:23438.2 services/reconciler.go:114
2024-02-08T09:53:31-08:00 INFO [WINDOWS_D] windows_desktop EC2AMAZ-2VKH71R-teleport-dev-3eaae4a0 updated, updating. pid:23438.2 services/reconciler.go:187
2024-02-08T09:56:20-08:00 DEBU [AUTH:2]    Server certificate cert(8f1ed2bc-65fb-48de-b32f-cac76676f8db.Isaiahs-MacBook-Pro.local issued by Isaiahs-MacBook-Pro.local:281296387376463031351125731320971465316). auth/middleware.go:343
2024-02-08T09:56:20-08:00 DEBU             generated user key for [root ibm ibeckermayer visitor -teleport-internal-join] with expiry on (1707456469) 2024-02-09 05:27:49.325505 +0000 UTC keygen/keygen.go:165
2024-02-08T09:56:20-08:00 INFO [CA]        Generating TLS certificate 1.3.9999.1.15=#13046e6f6e65,1.3.9999.1.9=#13093132372e302e302e31,1.3.9999.1.7=#1319497361696168732d4d6163426f6f6b2d50726f2e6c6f63616c,CN=joe,O=access+O=editor+O=auditor,POSTALCODE={\"kubernetes_groups\":[\"\"]\,\"kubernetes_users\":[\"\"]\,\"logins\":[\"root\"\,\"ibm\"\,\"ibeckermayer\"\,\"visitor\"]\,\"windows_logins\":[\"Administrator\"]},STREET=Isaiahs-MacBook-Pro.local,L=root+L=ibm+L=ibeckermayer+L=visitor+L=-teleport-internal-join dns_names:[] key_usage:5 not_after:2024-02-09 05:27:49.327108 +0000 UTC tlsca/ca.go:1187
2024-02-08T09:56:20-08:00 INFO [AUDIT]     cert.create cert_type:user cluster_name:Isaiahs-MacBook-Pro.local code:TC000I ei:0 event:cert.create client_ip:127.0.0.1 expires:2024-02-09T05:27:49.327108Z logins:[root ibm ibeckermayer visitor -teleport-internal-join] prev_identity_expires:0001-01-01T00:00:00Z private_key_policy:none roles:[access editor auditor] route_to_cluster:Isaiahs-MacBook-Pro.local teleport_cluster:Isaiahs-MacBook-Pro.local kubernetes_groups:[] kubernetes_users:[] logins:[root ibm ibeckermayer visitor] windows_logins:[Administrator] user:joe time:2024-02-08T17:56:20.742Z uid:a7f20716-892a-42f3-a5a0-0694d3c38395 events/emitter.go:278
2024-02-08T09:56:20-08:00 DEBU [AUTH:2]    Server certificate cert(8f1ed2bc-65fb-48de-b32f-cac76676f8db.Isaiahs-MacBook-Pro.local issued by Isaiahs-MacBook-Pro.local:281296387376463031351125731320971465316). auth/middleware.go:343
2024-02-08T09:56:39-08:00 DEBU [AUTH:2]    Server certificate cert(8f1ed2bc-65fb-48de-b32f-cac76676f8db.Isaiahs-MacBook-Pro.local issued by Isaiahs-MacBook-Pro.local:281296387376463031351125731320971465316). auth/middleware.go:343
2024-02-08T09:56:40-08:00 DEBU [PROXY:2]   List of known proxies updated: ["8f1ed2bc-65fb-48de-b32f-cac76676f8db"]. pid:23438.2 services/watcher.go:491
2024-02-08T09:58:30-08:00 DEBU [WINDOWS_D] searching for desktops with LDAP filter (&(objectClass=computer)(!(objectClass=msDS-GroupManagedServiceAccount))) pid:23438.2 desktop/discovery.go:105
2024-02-08T09:58:30-08:00 DEBU [WINDOWS_D] discovered 1 Windows Desktops pid:23438.2 desktop/discovery.go:127
2024-02-08T09:58:30-08:00 DEBU [WINDOWS_D] DNS lookup for EC2AMAZ-2VKH71R.teleport.dev failed with default resolver: lookup EC2AMAZ-2VKH71R.teleport.dev: no such host pid:23438.2 desktop/discovery.go:209
2024-02-08T09:58:30-08:00 DEBU [WINDOWS_D] resolved EC2AMAZ-2VKH71R.teleport.dev => [172.31.16.172] pid:23438.2 desktop/discovery.go:270
2024-02-08T09:58:30-08:00 DEBU [WINDOWS_D] Reconciling 1 current resources with 1 new resources. pid:23438.2 services/reconciler.go:114
2024-02-08T09:58:30-08:00 INFO [WINDOWS_D] windows_desktop EC2AMAZ-2VKH71R-teleport-dev-3eaae4a0 updated, updating. pid:23438.2 services/reconciler.go:187
```

</details>

image

### PR DESCRIPTION
**Pull request by probakowski**
This fixes a bug introduced in #37393 where large TDP messages coming
from the browser can be truncated.

Fixes #37894
Fixes #37940

changelog: Fixed a bug that prevented desktop clipboard sharing from working when large amounts of text are placed on the clipboard.

### CODE REVIEW

File: lib/web/desktop.go [hunk 1]
```diff
@@ -495,28 +495,15 @@ func proxyWebsocketConn(ws *websocket.Conn, wds net.Conn) error {
...
-			}
+		// io.Copy is fine here, as the Windows Desktop Service
+		// operates on a stream and doesn't care if TPD messages
+		// are fragmented
+		stream := &WebsocketIO{Conn: ws}
+		_, err := io.Copy(wds, stream)
+		if utils.IsOKNetworkError(err) {
+			err = nil
 		}
+		errs <- err
```
Comment (zmb3) [inline lib/web/desktop.go:506]: Here's how I would write it. This keeps the behavior of reusing the same read buf for each message, but uses a `bytes.Buffer` that can grow rather than a fixed-capacity slice. (While still making it easy to check the first byte on v15)
```suggestion
		var buf bytes.Buffer
		for {
			_, reader, err := ws.NextReader()
			switch {
			case utils.IsOKNetworkError(err):
				errs <- nil
				return
			case err != nil:
				errs <- err
				return
			}
			buf.Reset()
			if _, err := io.Copy(&buf, reader); err != nil {
				errs <- err
				return
			}

			if _, err := wds.Write(buf.Bytes()); err != nil {
				errs <- trace.Wrap(err, "sending TDP message to desktop agent")
				return
			}
		}
```

**Review by zmb3 — APPROVED** [review]

**Review by ibeckermayer — APPROVED** [review]
