### PR TITLE
Filter out internal teleport defined logins

### LINKED ISSUE #6789: Odd Logins output when a user has no login
### Description

**What happened**:

If a user has no login there is a long uuid like id. 

```bash
tsh login --proxy=teleport.example.com:443 
Enter password for Teleport user steven:
Enter your OTP token:
668332
> Profile URL:        https://teleport.example.com:443
  Logged in as:       steven
  Cluster:            ip-172-31-68-3
  Roles:              admin
  Logins:             -teleport-nologin-0a430fb6-8d1b-4d33-9bca-086d3687a30e
  Kubernetes:         disabled
  Valid until:        2021-05-08 09:19:40 -0400 EDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

**What you expected to happen**:

A message that indicates no logins instead of a random no login id.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a Teleport instance and a user with `admin` role
2. Login via `tsh` with the user

### Server Details
- Teleport version (run `teleport version`): 6.1.5
- Server OS (e.g. from `/etc/os-release`): ubuntu 
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`): 6.1.5
- Computer OS (e.g. Linux, macOS, Windows): ubuntu linux

### LINKED ISSUE #21948: tsh login: Remove "-teleport-internal-join" logins
What would you like Teleport to do?
We want to remove the `-teleport-internal-join" login from the tsh login (logins). If this cannot be done, we would like to allow explicit denying from the logins list as this is currently not possible. 
deny-logins

What problem does this solve?
After upgrading from 9.3.x -> 10.3.x the `-teleport-internal-join` logins started to show in the tsh status. This currently breaks some automation logic around retrieving a username as the login scripts rely on the `Logins` entry. Updating the script across the board is not an easy task. 

If a workaround exists, please include it.
We could update the script across the board, however, this looks more like a bug.

### PR DESCRIPTION
**Pull request by kimlisa**
When `tsh login` and generating user cert, we append the following teleport defined logins:
- [-teleport-internal-join](https://github.com/gravitational/teleport/blob/471a82bd6f9ac595f88df7bf698158d8ed539452/lib/auth/auth.go#L1927): added for every user for the `join-only` joining sessions
- [-teleport-nologin-](https://github.com/gravitational/teleport/blob/471a82bd6f9ac595f88df7bf698158d8ed539452/lib/services/role.go#L1599): added when user has no defined logins and ssh certs must contain at least one login

This PR just filters out these internally defined logins from the tsh output, and removes the login row if there were no logins:

image

With a valid login:

image

Closes #21948
Closes #6789

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

File: tool/tsh/tsh_test.go [hunk 1]
```diff
@@ -3950,3 +3950,36 @@ func TestShowSessions(t *testing.T) {
...
+			name: "with valid logins and internal logins",
+			profile: &client.ProfileStatus{
+				Logins: []string{constants.NoLoginPrefix, "alpaca", teleport.SSHSessionJoinPrincipal, "llama"},
+			},
+			expectedLogins: []string{"alpaca", "llama"},
+		},
+	}
+
+	for _, test := range tests {
+		test := test
```
Comment (zmb3) [inline tool/tsh/tsh_test.go:3979]: This is only necessary if the subtest is a parallel test, which is not the case here.

**Review by zmb3 — APPROVED** [review]
