### PR TITLE
assist: fix flaky assist test

### LINKED ISSUE #28945: `Test_runAssistError` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5519632646/jobs/10065148170?pr=28939#step:6:1007

#### Relevant snippet

```
     assistant_test.go:251: 
        	Error Trace:	/__w/teleport/teleport/lib/web/assistant_test.go:251
        	            				/opt/go/src/testing/testing.go:1150
        	            				/opt/go/src/testing/testing.go:1328
        	            				/opt/go/src/testing/testing.go:1570
        	Error:      	An error is expected but got nil.
        	Test:       	Test_runAssistError
```

### PR DESCRIPTION
**Pull request by hugoShaka**
Fixes: https://github.com/gravitational/teleport/issues/28945

A race between the websocket close and the TLS close causes the flakiness. The websocket lib receives the websocket close message and doesn't do anything to the underlying TLS connection (which is still open). The server can also close the TLS connection, but this happens asynchronously. Calling `ws.Close()` returns an error only if the underlying TLS connection is closed.

The TLS connection being closed is an implementation detail. What we really want to check is whether the websocket gets appropriately closed. The underlying connection will eventually be closed and reclaimed by the server. We can skip checking the error; the test should not be less valid.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: lib/web/assistant_test.go [hunk 1]
```diff
@@ -247,8 +247,10 @@ func Test_runAssistError(t *testing.T) {
 	ws, err := s.makeAssistant(t, authPack, conversationID)
 	require.NoError(t, err)
 	t.Cleanup(func() {
-		// Close should yield an error as the server closes the connection
-		require.Error(t, ws.Close())
+		// The websocket has been closed, but the underlying tls connection
```
Comment (jakule) [inline lib/web/assistant_test.go:250]: I'd re-phrase that and explain why we are fine with ignoring that error rather than explaining what is happening here.

**Review by jakule — APPROVED** [review]

File: lib/web/assistant_test.go [hunk 2]
```diff
@@ -247,8 +247,10 @@ func Test_runAssistError(t *testing.T) {
...
+		// might not be closed yet (it is closed by another message sent by the
+		// server).
```
Comment (hugoShaka) [inline lib/web/assistant_test.go:252]:
```suggestion
		// The TLS connection might or might not be closed, this is an implementation detail.
		// We want to check whether the websocket gets appropriately closed, not the underlying TLS connection.
		// The connection will eventually be closed and reclaimed by the server. We can skip checking the error.
```
