### PR TITLE
deflake `TestLockWatcherStale` test

### LINKED ISSUE #33371: `TestLockWatcherStale` flakiness
## Failure

[Link to logs](https://github.com/gravitational/teleport/actions/runs/6497804816/job/17647702255?pr=32980#step:6:1632)

#### Relevant snippet

```
=== Failed
=== FAIL: lib/services TestLockWatcherStale (17.01s)
    watcher_test.go:486: Timeout waiting for OpPut.
```

### PR DESCRIPTION
**Pull request by tigrato**
This PR deflakes `TestLockWatcherStale` test by leveraging the new `synctest` package.

Previously, the test didn't ensure that we had one or more listeners for the clock so we could advance the time before the goroutine is locked.

Fixes https://github.com/gravitational/teleport/issues/33371

### CODE REVIEW

File: lib/services/watcher_test.go [hunk 1]
```diff
@@ -397,108 +398,117 @@ func TestLockWatcherSubscribeWithEmptyTarget(t *testing.T) {
 func TestLockWatcherStale(t *testing.T) {
 	t.Parallel()
 
-	ctx := context.Background()
-	clock := clockwork.NewFakeClock()
+	synctest.Test(t, func(t *testing.T) {
+		ctx := context.Background()
```
Comment (rosstimothy) [inline lib/services/watcher_test.go]: While you are here...
```suggestion
		ctx := t.Context()
```

**Review by rosstimothy — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
