### PR TITLE
Set server_addr in audit events from connection info

### LINKED ISSUE #4938: Server Addr missing Address  "server_addr": "[::]:3022",
### Description

**What happened**:
It doesn't look like we are parsing server addr, because of IPV6 maybe? 

```json
{
  "code": "T2004I",
  "ei": 35,
  "enhanced_recording": false,
  "event": "session.end",
  "interactive": true,
  "namespace": "default",
  "participants": [
    "benarent"
  ],
  "server_addr": "[::]:3022",
  "server_hostname": "i-083e63d0daecd1315",
  "server_id": "a0518380-0d53-4188-ac8b-8ddd8103e45b",
  "session_start": "2020-11-19T19:45:11.238914025Z",
  "session_stop": "2020-11-19T20:29:30.95539198Z",
  "sid": "09d03df7-27d0-4e3e-ba74-6fa9d2d58c4a",
  "time": "2020-11-19T20:29:30.955Z",
  "uid": "6a351453-dea2-467d-8fcb-98fd14106bfa",
  "user": "benarent"
}
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

### PR DESCRIPTION
**Pull request by awly**
This sets a useful server IP, when no advertise_ip is set. Previously,
the address was taken from the listener, and is usually "0.0.0.0:3022"
or "[::]:3022".

Also, make the new etcd test skip when etcd isn't running locally (like
with other tests).
Also, add some test cases in utils for IPv6 handling.

Fixes https://github.com/gravitational/teleport/issues/4938

### CODE REVIEW

File: lib/backend/etcdbk/etcd_test.go [hunk 1]
```diff
@@ -384,6 +384,12 @@ func TestCompareAndSwapOversizedValue(t *testing.T) {
 		"dial_timeout":                   500 * time.Millisecond,
 		"etcd_max_client_msg_size_bytes": maxClientMsgSize,
 	})
+	if err != nil && (strings.Contains(err.Error(), "connection refused") || strings.Contains(err.Error(), "context deadline exceeded")) {
+		t.Logf("WARNING: etcd cluster is not available: %v.", err)
+		t.Logf("WARNING: Start examples/etcd/start-etcd.sh.")
+		t.Skip(err.Error())
+	}
+	require.NoError(t, err)
```
Comment (r0mant) [inline lib/backend/etcdbk/etcd_test.go:392]: Seems like `require.NoError(t, err)` is duplicated now?

**Review by r0mant — APPROVED** [review]

File: lib/backend/etcdbk/etcd_test.go [hunk 2]
```diff
@@ -384,6 +384,11 @@ func TestCompareAndSwapOversizedValue(t *testing.T) {
 		"dial_timeout":                   500 * time.Millisecond,
 		"etcd_max_client_msg_size_bytes": maxClientMsgSize,
 	})
+	if err != nil && (strings.Contains(err.Error(), "connection refused") || strings.Contains(err.Error(), "context deadline exceeded")) {
```
Comment (a-palchikov) [inline lib/backend/etcdbk/etcd_test.go:387]: Oh, my bad - did not think to validate them w/o the etcd instance.

On a side note, I think this could benefit if the check was encapsulated into a function (to share the same functionality with the go.check-based setup) and that it would be preferable to make etcd availability an external configuration - e.g. `make test` that spawns the etcd container would set the configuration while the normal `go test` would not (unless 
specified explicitly). Then the configuration could be an environment variable and tests would test for that? WDYT?

Testing for error conditions is till prone to errors as there maybe more cases - i.e. when the etcd is, in fact, running but is having temporary issues - the test would be skipped when it should've failed and the environment inspected.

For example:
```go
func etcdTestEnabled() bool {
	return os.Getenv("TELEPORT_TEST_ETCD") != ""
}
```

**Review by a-palchikov — APPROVED** [review]

File: lib/backend/etcdbk/etcd_test.go (hunk 2 above)
Comment (awly) [reply lib/backend/etcdbk/etcd_test.go]: Yeah, your solution looks better :+1: 
I removed the diff from my PR to avoid conflicts.
