### PR TITLE
local proxy not required for mysql separate port

### LINKED ISSUE #23364: MySQL tsh db env command with TLS Routing mode enabled.
Expected behavior:
If TLS Routing is enabled and teleport proxy is configured with a separate  MySQL listener (`proxy_service.mysql_listen_addr != ""`) 
The `tsh db env` and `tsh db config` commands should be supported.

Current behavior:
```
> tsh db env --db mysqldb
ERROR: "tsh db env" is not supported when:
  - database protocol is MySQL and cluster teleport.example.com proxy is using TLS routing.
```

where if a proxy runs on `proxy_service.mysql_listen_addr != ""` the direct connection to `mysql_listen_addr` via external tools is still supported and the TSH local proxy forwarding is not required to connect to MySQL instance. 

Related: 
https://github.com/gravitational/teleport/issues/16209

### PR DESCRIPTION
**Pull request by GavinFrazar**
Fixes https://github.com/gravitational/teleport/issues/23364

This PR will change `tsh` to not require a local proxy for MySQL in TLS routing mode if `tsh` configuration is aware of a separate MySQL listener.

### Context
With Teleport config v2+, if TLS routing mode is enabled on the proxy then all db listeners are advertised as listening on the web port regardless of whether a separate listener was configured. However, if a public addr was configured for a separate port listener, then the proxy settings advertise that public addr. Postgres is an exception, in that if `postgres_public_addr == ""`, it will advertise `postgres_public_addr: <webhost>:<postgres listen addr's port>`, although this seems to be intended as a temporary backwards compatibililty fix: https://github.com/gravitational/teleport/blob/4ec2c05905577a12330b188d47d4167a845c6aa5/lib/service/proxy_settings.go#L133-L156

For example:
```yaml
proxy_service:
  enabled: true
  ...
  postgres_listen_addr: "0.0.0.0:6543"
  postgres_public_addr: ""
  mysql_listen_addr: "0.0.0.0:3036"
  mysql_public_addr: ""
```

```sh
$ curl https://mars.local.gd:443/webapi/find -k | jq
{
  "auth": {
    "type": "",
    "private_key_policy": "",
    "has_motd": false
  },
  "proxy": {
    "kube": {
      "enabled": true,
      "listen_addr": "0.0.0.0:443"
    },
    "ssh": {
      "listen_addr": "0.0.0.0:443",
      "tunnel_listen_addr": "0.0.0.0:443",
      "web_listen_addr": "0.0.0.0:443",
      "public_addr": "mars.local.gd:443"
    },
    "db": {
      "postgres_listen_addr": "0.0.0.0:443",
      "postgres_public_addr": "mars.local.gd:6543",
      "mysql_listen_addr": "0.0.0.0:443"
    },
    "tls_routing_enabled": true
  },
  "server_version": "13.0.0-dev",
  "min_client_version": "12.0.0",
  "cluster_name": "mars.local.gd",
  "automatic_upgrades": false
}
```

With that context in mind, this PR will not require a local proxy for MySQL in TLS routing mode if `tsh` configuration is aware of a separate MySQL listener. Based on the config explanation above, that means on v2+ with TLS routing mode enabled, the client will only be aware of a separate MySQL listener if `mysql_public_addr != ""`.

On v1, `tsh` will be aware of a separate listener if `mysql_listen_addr != ""` in the proxy config.

Without that local proxy requirement, `tsh db env` and `tsh db config` will work.

## UX Diff

For all examples, assume we have TLS routing enabled (UX is only affected by this PR when TLS routing is enabled):
```yaml
auth_service:
  enabled: true
  ...
  proxy_listener_mode: "multiplex"
```

### separate MySQL listener with public addr
config:
```yaml
proxy_service:
  ...
  mysql_listen_addr: "0.0.0.0:3036"
  mysql_public_addr: "example.com:3036"
```
UX Diff:
```diff
$ tsh db login --db-user=alice mysql-aurora
Connection information for database "mysql-aurora" has been saved.

You can now connect to it using the following command:

  tsh db connect mysql-aurora

-You can start a local proxy for database GUI clients:
-
-  tsh proxy db --tunnel mysql-aurora
+You can view the connect command for the native database CLI client:
+
+  tsh db config --format=cmd mysql-aurora
$ tsh db env
-ERROR: "tsh db env" is not supported when:
-  - database protocol is MySQL and cluster mars.local.gd proxy is using TLS routing.
-
-Please use one of the following commands to connect to the database:
-    tsh db connect mysql-aurora
-    tsh proxy db --tunnel mysql-aurora
+ export MYSQL_GROUP_SUFFIX=_mars.local.gd-mysql-aurora

$ tsh db config --format=cmd
-ERROR: "tsh db config" is not supported when:
-  - database protocol is MySQL and cluster mars.local.gd proxy is using TLS routing.
-
-Please use one of the following commands to connect to the database:
-   tsh db connect mysql-aurora
-   tsh proxy db --tunnel mysql-aurora
+ /opt/homebrew/bin/mysql --defaults-group-suffix=_mars.local.gd-mysql-aurora --user alice
```

### separate MySQL listener without public addr (MySQL handled on proxy web port via ALPN router OR via port 3036)
config:
```yaml
proxy_service:
  ...
  mysql_listen_addr: "0.0.0.0:3036"
  mysql_public_addr: ""
```
proxy config v2/v3 UX Diff: none, since the proxy does not advertise the separate MySQL listener.
proxy config v1 UX Diff: same diff as for the public addr case above.

### no separate MySQL listener (MySQL handled on proxy web port via ALPN router)
config:
```yaml
proxy_service:
  ...
  mysql_listen_addr: ""
  mysql_public_addr: ""
```
UX Diff: none.

### CODE REVIEW

**Comment by GavinFrazar** [comment]
The PR is tiny, but I wanted to document what exactly is going on since I had to figure all this out to make sense of it 😅

**Review by avatus — APPROVED** [review]

File: tool/tsh/db.go [hunk 1]
```diff
@@ -1171,7 +1171,7 @@ func getDBLocalProxyRequirement(tc *client.TeleportClient, route *tlsca.RouteToD
 		// Some protocols only work in the local tunnel mode.
 		out.addLocalProxyWithTunnel(formatDBProtocolReason(route.Protocol))
 	case defaults.ProtocolMySQL:
-		if tc.TLSRoutingEnabled {
+		if tc.TLSRoutingEnabled && tc.DoesDatabaseUseWebProxyHostPort(*route) {
```
Comment (smallinsky) [inline tool/tsh/db.go:1174]: Could you add a comment explain this logic and describe dependency on `MySQLProxyAddr`

**Review by smallinsky — APPROVED** [review]
