### PR TITLE
Better error message for invalid `/etc/nsswitch.conf`

### LINKED ISSUE #23911: Host User Creation stops working after package install on ubuntu
### Expected behavior:

Host user creation should work

### Current behavior:

On ubuntu 22.04, Teleport's host user creation works. Once installing the ubuntu-desktop and xrdp packages, Teleport is no longer able to create the host user. The following log appears when that happens:

```
Error creating user jefferya: user: lookup username jefferya: no such file or directory srv/sess.go:208
```

<details>
<summary>click to expand</summary>

```
Mar 31 14:00:59 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:00:59Z DEBU [PROXY:AGE] Transport request: teleport-transport. leaseID:1 target:other.proving.cf:443 cluster:other reversetunnel/agent.go:570
Mar 31 14:00:59 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:00:59Z DEBU [PROXY:AGE] Received out-of-band proxy transport request for @local-node [afd9798b-ae6a-4f55-ae4d-e8241c7c7ff5.other]. cluster:other reversetunnel/transport.go:199
Mar 31 14:00:59 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:00:59Z DEBU [PROXY:AGE] Handing off connection to a local "node" service. cluster:other reversetunnel/transport.go:274
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      conn(192.168.8.99:54067->172.31.20.236:51646, user=jefferya) auth attempt fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:iEASMDiohc5h/Da1+5JlYqVbpqDvqwgJaAA9qBOULSs local:172.31.20.236:51646 remote:192.168.8.99:54067 user:jefferya srv/authhandlers.go:291
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      conn(192.168.8.99:54067->172.31.20.236:51646, user=jefferya) auth attempt with key ssh-rsa-cert-v01@openssh.com SHA256:iEASMDiohc5h/Da1+5JlYqVbpqDvqwgJaAA9qBOULSs, &ssh.Certificate{Nonce:[]uint8{0xa8, 0x88, 0xa, 0xd8, 0xe9, 0x88, 0xc6, 0x9d, 0x4e, 0xc7, 0x36, 0x71, 0x3e, 0xda, 0xf, 0x6, 0x89, 0xc3, 0x30, 0xc6, 0x38, 0x51, 0xbd, 0xc1, 0x5, 0xae, 0x7f, 0x55, 0x87, 0x85, 0x50, 0xae}, Key:(*ssh.rsaPublicKey)(0xc0011169b0), Serial:0x0, CertType:0x1, KeyId:"admin", ValidPrincipals:[]string{"root", "ubuntu", "ec2-user", "admin", "jeff", "jefferya", "-teleport-internal-join"}, ValidAfter:0x6426e444, ValidBefore:0x64278d40, Permissions:ssh.Permissions{CriticalOptions:map[string]string{}, Extensions:map[string]string{"login-ip":"192.168.8.99", "permit-X11-forwarding":"", "permit-agent-forwarding":"", "permit-port-forwarding":"", "permit-pty":"", "private-key-policy":"none", "teleport-roles":"{\"version\":\"v1\",\"roles\":[\"admin\",\"contractor\"]}", "teleport-route-to-cluster":"other", "teleport-traits":"{\"aws_role_arns\":null,\"db_names\":null,\"db_users\":null,\"kubernetes_groups\":null,\"kubernetes_users\":null,\"logins\":[\"root\",\"ubuntu\",\"ec2-user\",\"admin\",\"jeff\",\"jefferya\"],\"windows_logins\":null}"}}, Reserved:[]uint8{}, SignatureKey:(*ssh.rsaPublicKey)(0xc001116a60), Signature:(*ssh.Signature)(0xc00110d500)} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:iEASMDiohc5h/Da1+5JlYqVbpqDvqwgJaAA9qBOULSs local:172.31.20.236:51646 remote:192.168.8.99:54067 user:jefferya srv/authhandlers.go:294
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Successfully authenticated fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:iEASMDiohc5h/Da1+5JlYqVbpqDvqwgJaAA9qBOULSs local:172.31.20.236:51646 remote:192.168.8.99:54067 user:jefferya srv/authhandlers.go:381
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Checking permissions for (admin,jefferya) to login to node with RBAC checks. srv/authhandlers.go:546
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [RBAC]      Access to node "afd9798b-ae6a-4f55-ae4d-e8241c7c7ff5" granted, allow rule in role "admin" matched. services/role.go:2528
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [SSH:NODE]  Incoming connection 192.168.8.99:54067 -> 172.31.20.236:51646 version: SSH-2.0-Go, certtype: "user" sshutils/server.go:502
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [KEEPALIVE] Starting keep-alive loop with interval 5m0s and max count 3. srv/keepalive.go:64
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request env, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request env, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request env, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request env, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU             Will create new session for SSH connection 192.168.8.99:54067. srv/ctx.go:632
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request env, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU             Will create new session for SSH connection 192.168.8.99:54067. srv/ctx.go:632
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request env, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU             Will create new session for SSH connection 192.168.8.99:54067. srv/ctx.go:632
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request env, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU             Will create new session for SSH connection 192.168.8.99:54067. srv/ctx.go:632
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request pty-req, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Requested terminal "xterm-256color" of size {80 25} id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin srv/termhandlers.go:77
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU             "Unable to set TTY owner: user: lookup username jefferya: no such file or directory.\n" srv/term.go:168
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [SESSION:N] Unable to update window size, no session found in context. srv/sess.go:347
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU             Will create new session for SSH connection 192.168.8.99:54067. srv/ctx.go:632
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Handling request shell, want reply true. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin regular/sshserver.go:1520
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU             Error creating user jefferya: user: lookup username jefferya: no such file or directory srv/sess.go:208
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z ERRO             failure handling SSH "shell" request error:[
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: ERROR REPORT:
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: Original Error: *errors.errorString user: lookup username jefferya: no such file or directory
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: Stack Trace:
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]:         github.com/gravitational/teleport/lib/srv/usermgmt.go:157 github.com/gravitational/teleport/lib/srv.(*HostUserManagement).CreateUser
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]:         github.com/gravitational/teleport/lib/srv/sess.go:206 github.com/gravitational/teleport/lib/srv.(*SessionRegistry).TryCreateHostUser
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]:         github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1606 github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]:         github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1488 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]:         github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1222 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]:         runtime/asm_amd64.s:1598 runtime.goexit
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: User Message: user: lookup username jefferya: no such file or directory] regular/sshserver.go:1961
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [TERM:LOCA] Closing TTY srv/term.go:319
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [TERM:LOCA] Closed TTY srv/term.go:337
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [NODE]      Releasing associated resources - context has been closed. id:1 local:172.31.20.236:51646 login:jefferya remote:192.168.8.99:54067 teleportUser:admin srv/monitor.go:266
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [TERM:LOCA] Closed PTY srv/term.go:357
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z INFO [AUDIT]     session.data addr.remote:192.168.8.99:54067 code:T2006I ei:2.147483646e+09 event:session.data login:jefferya namespace:default rx:4718 server_id:afd9798b-ae6a-4f55-ae4d-e8241c7c7ff5 sid: time:2023-03-31T14:01:00.533Z tx:5712 uid:df340197-d67a-4d04-80c8-4338d1739baa user:admin events/emitter.go:265
Mar 31 14:01:00 ip-172-31-20-236 teleport[29745]: 2023-03-31T14:01:00Z DEBU [SSH:NODE]  Closed connection 192.168.8.99:54067. sshutils/server.go:507
```
</details>

I tried restarting the teleport service, restarting the whole ubuntu server, and a few other things. The error persisted. I ran teleport inside strace, and saw that wasn't even calling the `useradd` binary at all.

The section of code that outputs the user message is here: https://github.com/gravitational/teleport/blob/v12.1.3/lib/srv/sess.go#L206-L210

It looks like it is encountering that "no such file or directory" even before it is even able to attempt the useradd.

Bug details:
- Teleport version 12.1.3
- Recreation steps - ✅
- Debug logs - ✅

### PR DESCRIPTION
**Pull request by eriktate**
Fixes #23911

This PR adds some extra context to the error message returned when an invalid `/etc/nsswitch.conf` results in an ENOENT while trying to lookup a user.

### CODE REVIEW

File: lib/srv/usermgmt_linux.go [hunk 1]
```diff
@@ -72,7 +72,15 @@ func newHostSudoersBackend(uuid string) (HostSudoersBackend, error) {
 
 // Lookup implements host user information lookup
 func (*HostUsersProvisioningBackend) Lookup(username string) (*user.User, error) {
-	return user.Lookup(username)
+	user, err := user.Lookup(username)
+	if err != nil {
+		if strings.Contains(err.Error(), "no such file or directory") {
```
Comment (eriktate) [inline lib/srv/usermgmt_linux.go:77]: I tried to detect this error a couple of different ways, but a string contains was the only one that ended up working. For some reason `users.Lookup()` eats the original error context because it formats with `%s` instead of `%w`.

Comment (flyinghermit) [reply lib/srv/usermgmt_linux.go:77]: Should we first check if error is [UnknownUserError](https://pkg.go.dev/os/user#UnknownUserError) so that we check for a known error message first before doing string contains?

**Review by flyinghermit — APPROVED** [review]
LGTM, just a minor suggestion on the error message.

File: lib/srv/usermgmt_linux.go (hunk 1 above)
Comment (eriktate) [reply lib/srv/usermgmt_linux.go]: Is this sort of what you had in mind @flyinghermit? Since the handling for `UnknownUserError` is the same as `err != nil` I just added a negative check before running the string contains. The error itself in this scenario doesn't actually contain `UnkownUserError` so I don't think there's a better way to avoid unnecessary containment checks 🤔

Comment (flyinghermit) [reply lib/srv/usermgmt_linux.go]: Got it, Thanks for clarifying.

My suggestion originated more for readability. Reading the godoc for `user.Lookup` it is not apparent that the `no such file or directory` error would be return. So explicitly including `UnknownUserError` check in the error block makes it clear that there may be error besides `UnknownUserError`.

File: lib/srv/usermgmt_linux.go [hunk 2]
```diff
@@ -72,7 +73,16 @@ func newHostSudoersBackend(uuid string) (HostSudoersBackend, error) {
 
 // Lookup implements host user information lookup
 func (*HostUsersProvisioningBackend) Lookup(username string) (*user.User, error) {
-	return user.Lookup(username)
+	usr, err := user.Lookup(username)
+	if err != nil {
+		if !errors.Is(err, user.UnknownUserError(username)) && strings.Contains(err.Error(), "no such file or directory") {
+			return nil, trace.Errorf("error while looking up user %q, sources configured for passwd in host's /etc/nsswitch.conf may be misconfigured", username)
```
[the remark this answers is not in the document]
Comment (eriktate) [reply lib/srv/usermgmt_linux.go]: Yeah good call. I think the original error is a _little_ misleading, but there's no reason not to include it with the additional context

**Review by rosstimothy — APPROVED** [review]
