### PR TITLE
Fix `tsh app login` when setting up access for AWS using Roles Anywhere integration

### LINKED ISSUE #59969: AWS Roles Anywhere AWS Profile with Config File Issue
Expected behavior:

When running `tsh apps login` profiles are correctly written to `~/.aws/config` or managed via Teleport for multiple roles/accounts. 

Current behavior:

Teleport modifies the `~/.aws/config` file to add the AWS session. On any subsequent runs Teleport declares that `~/.aws/config` is not managed by Teleport. 

```
user@host /tmp % tsh apps login profile-aws-dev 
ERROR: failed to add AWS profile to config
	/Users/user/.aws/config: section "profile profile-aws-dev" is not managed by teleport, remove the section and try again
```

Bug details:
- Teleport version

Teleport version: 18.2.0 (server), 18.1.4 (client)

- Recreation steps

1. Login to an AWS Roles Anywhere profile via `tsh apps login` 
2. Login to a new profile after the first one. 
 
- Debug logs

### PR DESCRIPTION
**Pull request by marcoandredinis**
When a user logs in to an AWS app which relies on AWS IAM Roles Anywhere integration for credentials, `tsh` will write a new entry to `~/.aws/config` file.

If the user logs out, the entry is removed.
However, if the user logs in again it will complain that:
```bash
$ tsh app login My-App --aws-role MyRole
ERROR: failed to add AWS profile to config
    /Users/user/.aws/config: section "profile My-App" is not managed by teleport, remove the section and try again
```

`tsh` uses the profile's comment section to check whether the profile already exists.
However, the comment was not properly escaped by the `; ` symbol, and so it was not being marked as managed by Teleport.

This PR fixes that, and escapes the comment (only if not already escaped).

Changelog: Fixes AWS CLI access when using the AWS Roles Anywhere integration.

Fixes: https://github.com/gravitational/teleport/issues/59969
Fixes: https://github.com/gravitational/teleport/issues/59867

### CODE REVIEW

File: lib/aws/awsconfigfile/awsconfigfile.go
Comment (espadolini) [inline lib/aws/awsconfigfile/awsconfigfile.go]: Should we maybe make the check less strict? Aren't we also treating any section that does _not_ have a comment as managed by us?

Comment (marcoandredinis) [reply lib/aws/awsconfigfile/awsconfigfile.go]: > Aren't we also treating any section that does not have a comment as managed by us?

Yes, we were. Fixed, thank you.

> Should we maybe make the check less strict?

Care to elaborate a little on this one?
Do you suggest just checking part of the comment? Or just the profile name?

**Comment by marcoandredinis** [comment]
@espadolini @vapopov Can you please take a look when you get a chance?

File: lib/aws/awsconfigfile/awsconfigfile.go
Comment (espadolini) [reply lib/aws/awsconfigfile/awsconfigfile.go]: Well, we could check that the comment contains "this section is managed by teleport" with a case folded comparison, for example, or strip any leading semicolons and spaces before checking for a prefix in the message.

File: lib/aws/awsconfigfile/awsconfigfile.go [hunk 1]
```diff
@@ -64,13 +63,25 @@ func addCredentialProcessToSection(configFilePath, sectionName, sectionComment,
...
+
+	switch {
+	case iniFile.HasSection(sectionName):
+		section = iniFile.Section(sectionName)
+
+		if !strings.HasPrefix(sectionComment, "; ") {
+			sectionComment = "; " + sectionComment
+		}
+		// Check ownership of the section by comparing comments.
+		if section.Comment != sectionComment {
```
Comment (espadolini) [inline lib/aws/awsconfigfile/awsconfigfile.go]: What do you think of doing something like this?

```suggestion
		current := strings.TrimSpace(strings.TrimLeft(section.Comment, ";"))
		expected := strings.TrimSpace(strings.TrimLeft(sectionComment, ";"))
		// Check ownership of the section by comparing comments.
		if current != expected {
```

File: lib/aws/awsconfigfile/awsconfigfile.go [hunk 2]
```diff
@@ -64,13 +63,25 @@ func addCredentialProcessToSection(configFilePath, sectionName, sectionComment,
...
+			return trace.BadParameter("%s: section %q is not managed by teleport, remove the section and try again", configFilePath, sectionName)
```
Comment (espadolini) [inline lib/aws/awsconfigfile/awsconfigfile.go]:
```suggestion
			return trace.BadParameter("%s: section %q is not managed by Teleport, remove the section and try again", configFilePath, sectionName)
```

File: lib/aws/awsconfigfile/awsconfigfile.go (hunk 1 above)
Comment (marcoandredinis) [reply lib/aws/awsconfigfile/awsconfigfile.go]: Can you please check the new commit?
I'm now using a different comment and only checking if the profile contains that comment.

**Review by espadolini — APPROVED** [review]
Should we add a backwards compatible check too for the old comment format or are we ok with making people clean out their config file once after they upgrade?

**Comment by marcoandredinis** [comment]
> Should we add a backwards compatible check too for the old comment format or are we ok with making people clean out their config file once after they upgrade?

There's a test that exercises that:
https://github.com/gravitational/teleport/blob/68b947056dccf0e2993798e9269b2becdd7888b2/lib/aws/awsconfigfile/awsconfigfile_test.go#L203-L221

**Comment by marcoandredinis** [comment]
@vapopov can you please take a look when you get a chance?

**Review by tigrato — APPROVED** [review]
