### PR TITLE
Take cloud labels into account for application access permissions calculation.

### LINKED ISSUE #17929: Instance metadata tag does not effect app RBAC as expected.
**Expected behavior:**
Because AWS instance metadata tags display as an app-level label, it was expected that they could be used to grant access to apps through Teleport RBAC. 

**Current behavior:**
Instance metadata tags display as an app-level label when they are applied to a node that is running the Teleport application service. However, they do not allow access to the app. 

**Example:** 
A user with the following in their role...
```
spec:
  allow:
    app_labels:
      aws/Name: grafana
```
will not be able to access this app:
image

**App service logs when a user tries to connect to the app in the above example:**
```
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: 2022-10-28T22:00:19Z WARN [APP:SERVI] Failed to handle client connection. error:[
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: ERROR REPORT:
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: Original Error: *errors.errorString EOF
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: Stack Trace:
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/lib/srv/app/server.go:731 github.com/gravitational/teleport/lib/srv/app.(*Server).getConnectionInfo
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/lib/srv/app/server.go:599 github.com/gravitational/teleport/lib/srv/app.(*Server).handleConnection
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/lib/srv/app/server.go:584 github.com/gravitational/teleport/lib/srv/app.(*Server).HandleConnection
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/transport.go:282 github.com/gravitational/teleport/lib/reversetunnel.(*transport).start
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:580 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels.func2
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: User Message: TLS handshake failed
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         EOF] app/server.go:585
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: 2022-10-28T22:00:19Z WARN [APP:SERVI] Failed to close client connection. error:[
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: ERROR REPORT:
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: Original Error: trace.aggregate EOF
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: Stack Trace:
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/api/utils/sshutils/chconn.go:113 github.com/gravitational/teleport/api/utils/sshutils.(*ChConn).Close
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/lib/srv/app/server.go:586 github.com/gravitational/teleport/lib/srv/app.(*Server).HandleConnection
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/transport.go:282 github.com/gravitational/teleport/lib/reversetunnel.(*transport).start
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:580 github.com/gravitational/teleport/lib/reversetunnel.(*agent).handleDrainChannels.func2
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]:         /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: User Message: EOF] app/server.go:587
Oct 28 22:00:19 ip-192-168-8-165 teleport[115775]: 2022-10-28T22:00:19Z WARN [APP:SERVI] Failed to serve request: not found. app/server.go:646
```

**Logs from auth/proxy (note that a 404 error is returned):**
```
2022-10-28T22:06:08Z INFO [CA]        Generating TLS certificate {0x9e08608 0xc000875150 1.3.9999.2.6=#1309646576656c6f706572,1.3.9999.2.5=#0c012a,1.3.9999.1.7=#1315726f6f742e74656c65706f72742d6373652e636f6d,1.3.9999.1.5=#1315726f6f742e74656c65706f72742d6373652e636f6d,1.3.9999.1.6=#131d67726166616e612e726f6f742e74656c65706f72742d6373652e636f6d,1.3.9999.1.4=#132466646164383936352d393737632d343831362d623239332d663338613039343436353136,1.3.9999.1.3=#1315726f6f742e74656c65706f72742d6373652e636f6d,1.3.9999.1.2=#1309646576656c6f706572,1.3.9999.1.1=#1303646576,CN=aws,OU=usage:apps,O=aws,POSTALCODE=null,STREET=root.teleport-cse.com,L=ubuntu+L=debian+L=-teleport-internal-join 2022-10-29 06:00:07.003392344 +0000 UTC [] [] 5 []}. common_name:aws dns_names:[] locality:[ubuntu debian -teleport-internal-join] not_after:2022-10-29 06:00:07.003392344 +0000 UTC org:[aws] org_unit:[usage:apps] tlsca/ca.go:874
2022-10-28T22:06:08Z INFO [AUDIT]     cert.create cert_type:user cluster_name:root.teleport-cse.com code:TC000I ei:0 event:cert.create identity:map[database_names:[*] database_users:[developer] expires:2022-10-29T06:00:07.003392344Z kubernetes_cluster:root.teleport-cse.com kubernetes_groups:[developer] kubernetes_users:[dev] logins:[ubuntu debian -teleport-internal-join] roles:[aws] route_to_app:map[cluster_name:root.teleport-cse.com name: public_addr:grafana.root.teleport-cse.com session_id:fdad8965-977c-4816-b293-f38a09446516] route_to_cluster:root.teleport-cse.com teleport_cluster:root.teleport-cse.com usage:[usage:apps] user:aws] time:2022-10-28T22:06:08.33Z uid:d7a6ed8f-40c6-4240-8c6f-a5767e98d420 events/emitter.go:263
2022-10-28T22:06:09Z INFO [AUDIT]     app.session.start addr.remote:192.168.16.199:31065 app_name:grafana app_public_addr:grafana.root.teleport-cse.com app_uri:http://localhost:3000 cluster_name:root.teleport-cse.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:grafana.root.teleport-cse.com server_id:dec9af99-11d1-4576-96b6-0848c44b726a sid:fdad8965-977c-4816-b293-f38a09446516 time:2022-10-28T22:06:09.425Z uid:b31caf36-82f2-4880-80c1-0a6a4f057d80 user:aws events/emitter.go:263
2022-10-28T22:06:09Z INFO [AUDIT]     app.session.start addr.remote:192.168.16.199:31065 app_name:grafana app_public_addr:grafana.root.teleport-cse.com app_uri:http://localhost:3000 cluster_name:root.teleport-cse.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:grafana.root.teleport-cse.com server_id:dec9af99-11d1-4576-96b6-0848c44b726a sid:fdad8965-977c-4816-b293-f38a09446516 time:2022-10-28T22:06:09.425Z uid:b31caf36-82f2-4880-80c1-0a6a4f057d80 user:aws events/emitter.go:263
2022-10-28T22:06:09Z INFO [APP:WEB]   Round trip: GET /, code: 404, duration: 19.336355ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:root.teleport-cse.com forward/fwd.go:187 
```

**Version:** 10.3.2

### PR DESCRIPTION
**Pull request by mdwn**
The app access service now takes cloud labels into account for determining permissions to an application. Previously, the app service didn't recognize cloud labels w/r/t determining whether users had access to a particular application. This was particularly confusing because this worked in the UI, i.e. the application would show in the list of applications the user had permissions to, but the app service itself would reject them. This is because the dynamic and cloud labels were not being properly injected into the application before running authorize within the app service.

Closes https://github.com/gravitational/teleport/issues/17929

### CODE REVIEW

**Comment by zmb3** [comment]
Is there an issue that this is solving? I'm not sure based on the commit message if this is just adding tests or changing behavior.

File: lib/srv/app/server.go [hunk 1]
```diff
@@ -956,12 +937,31 @@ func (s *Server) getApp(ctx context.Context, publicAddr string) (types.Applicati
...
 	for _, a := range s.getApps() {
 		if publicAddr == a.GetPublicAddr() {
-			return a, nil
+			return s.appWithUpdatedLabels(a), nil
 		}
 	}
 	return nil, trace.NotFound("no application at %v found", publicAddr)
 }
 
+func (s *Server) appWithUpdatedLabels(app types.Application) *types.AppV3 {
```
Comment (ibeckermayer) [inline lib/srv/app/server.go:946]: You should either take the `RLock` here, bring back `getDynamicLabels`, or clearly document that the caller must hold the `RLock` before calling this function.

**Review by ibeckermayer — APPROVED** [review]
LGTM with a comment about lock enforcement

File: lib/srv/app/server.go (hunk 1 above)
Comment (mdwn) [reply lib/srv/app/server.go:946]: I'll document it -- I removed `getDynamicLabels` because it was only used in one place and the two callers of `appWithUpdatedLabels` have different semantics about locking.

**Review by strideynet — APPROVED** [review]
