### PR TITLE
Prevent sending TDP messages in chunks during desktop sessions in Connect

### LINKED ISSUE #56921: Teleport Connect Windows Desktop crashes with large clipboard contents.
### Expected behavior:

When using Windows Desktop access inside Teleport Connect, a clipboard copy should work.

### Current behavior:

If a user puts at least 16381 bytes on the clipboard with a "Copy" operation, the session disconnects and displays a red error message `Invalid typed array length: 31254 bytes`. The number in the message reflects the amount of data in the clipboard.

#### Teleport version

Teleport Connect 17.5.5

#### Recreation steps

Connect to a Windows Desktop via Teleport Connect. Highlight at least 16381 bytes of data to copy into the clipboard, and choose "copy".

In a PowerShell window, run `'0' * 16381`. This will repeat the first character that many times. Double click to highlight. If you have copy-on-highlight enabled, you'll be disconnected and see the error. The number you specified in the PowerShell command will be the number in the error message.

I used a simple binary search approach to find the byte count threshold that triggers the issue reliably. This is 3 bytes fewer than `2^14` (16384), or 16 KiB.

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/56921

Disables chunking TDP messages between tsh daemon and Electron, as described in https://github.com/gravitational/teleport/issues/56921#issuecomment-3101903793.
Clipboard data sent through this connection is limited to a maximum size of 1 MB, which is a restriction in the TDP message decoder. https://github.com/gravitational/teleport/blob/22ce46d00e1db2ff276e5bc459c40fc4c9d0d6f0/lib/srv/desktop/tdp/proto.go#L1791

changelog: Fixed a crash in Teleport Connect that could occur when copying large clipboard content during desktop sessions

### CODE REVIEW

File: api/utils/grpc/stream/stream.go [hunk 1]
```diff
@@ -110,7 +139,7 @@ func (c *ReadWriter) Write(b []byte) (int, error) {
 	var sent int
 	for len(b) > 0 {
 		chunk := b
-		if len(chunk) > MaxChunkSize {
+		if !c.options.DisableChunking && len(chunk) > MaxChunkSize {
```
Comment (ravicious) [inline api/utils/grpc/stream/stream.go:141]: The comment for the `Write` method needs to be updated, now that there's a difference in behavior.

File: api/utils/grpc/stream/stream.go [hunk 2]
```diff
@@ -47,17 +47,46 @@ type ReadWriter struct {
...
+	DisableChunking bool
+}
+
+// Option allows setting options as functional arguments to NewReadWriter.
+type Option func(s *Options)
+
+// WithDisabledChunking	disables automatic splitting of data messages
+// that exceed MaxChunkSize during writes.
+// This is useful when the receiver does not support chunked reads.
+// Useful when the receiver doesn't support reading chunks.
```
Comment (ravicious) [inline api/utils/grpc/stream/stream.go]: I suppose one of those was meant to be removed. ;)

**Review by ravicious — APPROVED** [review]

File: api/utils/grpc/stream/stream_test.go [hunk 3]
```diff
@@ -122,6 +122,30 @@ func TestReadWriter_WriteChunk(t *testing.T) {
...
+		assert.NoError(t, err)
+		assert.Len(t, data, n)
+	}()
+	go func() {
+		defer wg.Done()
+		b := make([]byte, 2*MaxChunkSize)
+		n, err := local.Read(b)
+		assert.NoError(t, err)
+		assert.Len(t, data, n)
+		assert.Equal(t, data[:n], b[:n])
```
Comment (zmb3) [inline api/utils/grpc/stream/stream_test.go:143]: Isn't this racy? Writing to data in one goroutine and reading in another.

Comment (gzdunek) [reply api/utils/grpc/stream/stream_test.go:143]: The goroutines only read from `data` and do not modify it, so there shouldn't be a race condition?
`go test -race` also didn't find anything.

**Review by zmb3 — APPROVED** [review]
