### PR TITLE
Changed redirect endpoint when session is expired.

### LINKED ISSUE #4559: Unclear that I need to sign in again via the web interface to access AAP app
**What happened**: I refreshed a tab which I had opened yesterday with an AAP app loaded. The page went away and was replaced with the single word "Forbidden" in black text on a white background.

I signed into my Teleport cluster via another tab and refreshed the page again - still the same "Forbidden" message.

In the end, I had to close my existing tab, go back to the "Applications" tab in Teleport and start completely a new session by clicking on the app. This wasn't very clear to me - I initially expected that if I needed to reauthenticate to access the app, I would be redirected to the Teleport sign-in page to complete the sign-in and then sent back to the app afterwards.

Not sure if this is a deliberate decision for security, but it breaks the use of deep links to other apps via AAP. My expected flow would be that if you need to sign in to access an app, you are redirected to a sign-in page and then sent back to the URL you initially requested after this is complete - Teleport does this for its own internal links as well.

**What you expected to happen**: Either I should be redirected to the Teleport sign-in page when trying to load an app that I no longer have a session for, or the "Forbidden" message should be edited to say something like "Reauthentication via Teleport is required to access this service." as a clue that I need to go and log in again to start a brand new session.

It isn't currently clear at all whether "Forbidden" is a message coming from Teleport or being returned by the app that Teleport is proxying (I know now that it's coming from Teleport, but another user might not)

**How to reproduce it (as minimally and precisely as possible)**: Access an app via Teleport, let your session time out and then try to refresh the page.

### Environment
- Teleport version (use `teleport version`): `Teleport v5.0.0-beta.2 git:v5.0.0-beta.2-0-g412fb2062 go1.14.4`

### PR DESCRIPTION
**Pull request by russjones**
**Description**

When the user does not have a session, if the user tries to access a proxied application at it's FQDN, Teleport does best effort resolution.

This fix changes the behavior of what happens when the user has a session but the session is expired. The user was being redirected to the login page. This fix changes the behavior to by in sync with the no-session behavior in doing best effort resolution.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/4559

### CODE REVIEW

**Review by fspmarshall — APPROVED** [review]

File: lib/web/app/middleware.go [hunk 1]
```diff
@@ -47,14 +50,29 @@ func (h *Handler) withAuth(handler handlerAuthFunc) http.HandlerFunc {
...
+					for _, err := range errs {
+						aerrs = append(aerrs, trace.BadParameter(err))
+					}
+					return trace.NewAggregate(aerrs...)
+				}
 				u := url.URL{
 					Scheme: "https",
 					Host:   h.c.WebPublicAddr,
-					Path:   "/web/login",
+					Path:   fmt.Sprintf("/web/launch/%v", addr.Host()),
```
Comment (r0mant) [inline lib/web/app/middleware.go:75]: Not sure if I'm missing anything, but this will redirect to the "root" page of the application - so if you e.g. try to go to `grafana.proxy.teleport.io/dashboards/main`, then after login you will get redirected to just `grafana.proxy.teleport.io`? Does this `/launch` handler support redirects to "deep" links?

**Review by r0mant — APPROVED** [review]
Code lgtm, just have a question about behavior.

File: lib/web/app/middleware.go (hunk 1 above)
Comment (russjones) [reply lib/web/app/middleware.go:75]: I'm not sure if deep links are supported, that'd be a @alex-kovoy question. That being said, I think it's fine to redirect to the root because this gives you a new "session" similar to an SSH session which starts from a clean slate.

Comment (webvictim) [reply lib/web/app/middleware.go:75]: I can see deep links being a requested feature, so if it's possible for us to add this then we should at some point.

Comment (alex-kovoy) [reply lib/web/app/middleware.go:75]: Deep links is a must. For now it redirects back to the app home url.

**Comment by alex-kovoy** [comment]
Thanks for fixing this one!

File: lib/web/app/middleware.go (hunk 1 above)
Comment (russjones) [reply lib/web/app/middleware.go:75]: Okay, let's do it in a patch release for 5.0.
