### PR TITLE
Restart DiscoveryConfig watcher in Discovery Service

### LINKED ISSUE #63030: Discovery Service stops watching for discovery config updates
DiscoveryService has a list of cloud matchers, which it uses to enroll cloud resources.
Those matcher can come from the `teleport.yaml/discovery_service.[aws|azure|gcp]` or from DiscoveryConfig resources (matching by the service's `discovery_group` with the DiscoveryConfig's `discovery_group`).

When using DiscoveryConfig as source of matchers, the DiscoveryService initiates a watcher for that resource:
https://github.com/gravitational/teleport/blob/4d61a6af5382e45a685adffd24598ee610f66676/lib/srv/discovery/discovery.go#L540-L544

When a DiscoveryConfig is created/updated, the service will re-create the in-memory list of matchers, and start iterating on the new list of matchers.

**Expected behavior:**
Discovery Service must never stop watching discovery config updates.

**Current behavior:**
If there's an error in the discovery config watcher, discovery service will not resume it.

This can happen with a network hiccup where the watcher fails with `EOF` or `event fanout system reset`

https://github.com/gravitational/teleport/blob/4d61a6af5382e45a685adffd24598ee610f66676/lib/srv/discovery/discovery.go#L1832-L1835

Discovery Service must restart the watcher in order to keep watching for new DiscoveryConfig resources.
Either that or shutdown the process.
A silent failure is the least desirable, which is what happens today.

**Bug details:**
- Teleport version: 18.6.2

- Recreation steps
I don't have a deterministic way of recreating this failure, but an error in the watcher only (not the whole process) is enough to trigger this failure.

- Debug logs
```
{"timestamp":"2026-01-06T18:33:47Z","level":"warning","caller":"discovery/discovery.go:1816","message":"Dynamic matcher watcher error","component":"proc:1","pid":"7.1","component":"discovery:service","error":"event fanout system reset"}
```

### PR DESCRIPTION
**Pull request by marcoandredinis**
Discovery Service calls cloud (aws, azure, gcp) APIs to enroll resources into the cluster.
Which resources should be enrolled are defined as matchers.

A matcher can be instantiated in the Discovery Service's `teleport.yaml/discovery_service.[aws|azure|gcp]`, or can came from a Discovery Config.

The DiscoveryService creates a watcher for the DiscoveryConfig, so that any change in those resources is also applied to the Discovery Service.

The issue here is that sometimes the watcher can fail with a transient error.
Currently, this failure means that the watcher stops but the service continues working with the current snapshot of matchers.
Creating new DiscoveryConfigs or changing them does nothing, because the watcher is not working at this point.

This PR changes the watcher code, so that it restarts when there's a failure.
It waits 1 minute before retrying to ensure it gives some time for the cluster to recover from whatever issue it encountered when it failed for the first time.

Changelog: Fixed an issue that caused Discovery Service to stop working for Discovery Configs, also affecting AWS OIDC resource enrollments created from the UI.

Fixes: https://github.com/gravitational/teleport/issues/63030

### CODE REVIEW

File: lib/srv/discovery/discovery.go [hunk 1]
```diff
@@ -556,16 +549,48 @@ func (s *Server) startDynamicMatchersWatcher(ctx context.Context) error {
 		return trace.Wrap(watcher.Error())
 	}
 
+	s.dynamicMatcherWatcherMu.Lock()
```
Comment (gzdunek) [inline lib/srv/discovery/discovery.go]: In `startDynamicWatcherUpdater` we read from  `s.dynamicMatcherWatcher` without locking the mutex. 
Maybe we could instead pass the watcher as an argument to `startDynamicWatcherUpdater`?

**Review by gzdunek — APPROVED** [review]

**Comment by marcoandredinis** [comment]
@nklaassen Can you please take a look when you get a chance?

File: lib/srv/discovery/discovery.go [hunk 2]
```diff
@@ -556,16 +549,48 @@ func (s *Server) startDynamicMatchersWatcher(ctx context.Context) error {
...
 
-	go s.startDynamicWatcherUpdater()
+	s.startDynamicWatcherUpdater()
 	return nil
 }
 
+// startDynamicMatchersWatcher starts a watcher for DiscoveryConfig events.
+// Does not block and runs until the provided context is done.
+// Restarts on watcher errors, with a 1 minute delay between retries.
+func (s *Server) startDynamicMatchersWatcher(ctx context.Context) {
```
Comment (nklaassen) [inline lib/srv/discovery/discovery.go:560]: nit: this function accepts a context argument that it passes down to runDynamicMatchersWatcher, but then uses s.ctx to break out of the loop, so I had to figure out if they are the same or different, turns out they are the same?

File: lib/srv/discovery/discovery.go [hunk 3]
```diff
@@ -556,16 +549,48 @@ func (s *Server) startDynamicMatchersWatcher(ctx context.Context) error {
...
 	s.dynamicMatcherWatcher = watcher
+	s.dynamicMatcherWatcherMu.Unlock()
 
 	if err := s.loadExistingDynamicDiscoveryConfigs(); err != nil {
 		return trace.Wrap(err)
 	}
 
-	go s.startDynamicWatcherUpdater()
+	s.startDynamicWatcherUpdater()
 	return nil
```
Comment (nklaassen) [inline lib/srv/discovery/discovery.go]: now that you're not putting startDynamicWatcherUpdater in a goroutine, you could make it return an error so you don't have to return nil here when it has failed

File: lib/srv/discovery/discovery.go
Comment (nklaassen) [inline lib/srv/discovery/discovery.go:544]: the watcher is not closed here. I might recommend deferring the close after creating the watcher, and removing the close attempt from Server.Stop. I think the watcher doesn't even need to be a field on Server unless you just want to reach in to it in the tests

File: lib/srv/discovery/discovery.go [hunk 4]
```diff
@@ -556,16 +549,48 @@ func (s *Server) startDynamicMatchersWatcher(ctx context.Context) error {
 		return trace.Wrap(watcher.Error())
 	}
 
+	s.dynamicMatcherWatcherMu.Lock()
 	s.dynamicMatcherWatcher = watcher
+	s.dynamicMatcherWatcherMu.Unlock()
```
Comment (nklaassen) [inline lib/srv/discovery/discovery.go]: this watcher might not get closed (if Server.Stop has already completed or if it gets replace later)

File: lib/srv/discovery/discovery.go (hunk 2 above)
Comment (marcoandredinis) [reply lib/srv/discovery/discovery.go:560]: They are the same, I'll re-use the argument one.

File: lib/srv/discovery/discovery.go
Comment (marcoandredinis) [reply lib/srv/discovery/discovery.go:544]: Removed the watcher from the Server.
It was used only for tests.
Slightly changed the tests to account for the lack of direct access using the Server.

File: lib/srv/discovery/discovery.go (hunk 4 above)
Comment (marcoandredinis) [reply lib/srv/discovery/discovery.go]: It is now closed.
Thank you

**Review by nklaassen — APPROVED** [review]

File: lib/srv/discovery/discovery_test.go [hunk 5]
```diff
@@ -976,6 +979,111 @@ func fetchAllUserTasks(t *testing.T, userTasksClt services.UserTasks, minUserTas
...
+	require.NoError(t, err)
+
+	// DynamicMatcher watcher waits 1 minute before restarting, but in tests we can speed this up by advancing the fake clock.
+	fakeClock.Advance(2 * time.Minute)
+
+	require.Eventually(t, func() bool {
+		server.dynamicDiscoveryConfigMu.RLock()
+		defer server.dynamicDiscoveryConfigMu.RUnlock()
+		return len(server.dynamicDiscoveryConfig) == 2
+	}, 5*time.Second, 50*time.Millisecond)
```
Comment (nklaassen) [inline lib/srv/discovery/discovery_test.go]: actually, flaky test detector shows this failing

Comment (nklaassen) [reply lib/srv/discovery/discovery_test.go]: I believe you have to wait for the loop to actually block on the clock before advancing it

Comment (nklaassen) [reply lib/srv/discovery/discovery_test.go]: I've also been experimenting with net.Pipe-based networking so that you can use synctest in tests that use authtest.TLSServer https://github.com/gravitational/teleport/pull/63942

Comment (marcoandredinis) [reply lib/srv/discovery/discovery_test.go]: Changed to a _less real_ auth server w/ synctest. It is now passing the tests.
