### PR TITLE
use hostname to find an existing server

### LINKED ISSUE #1410: SSH login via web UI does not work
I have a very simple setup: Teleport running on localhost (called `luna`). It has one user `ekontsevoy` which is authorized to login as `ekontsevoy`.

When I click on `ekontsevoy` button, it works.
But if I type `ekontsevoy@luna` into that form - I get "access denied".

Basically the web-based login-via-editbox stopped working.

### PR DESCRIPTION
**Pull request by alex-kovoy**
closes #1410

### CODE REVIEW

**Review by russjones — APPROVED** [review]

File: lib/web/terminal.go [hunk 1]
```diff
@@ -285,3 +263,36 @@ func getUserCredentials(agent auth.AgentCloser) (string, ssh.AuthMethod, error)
...
+// resolveHostPort parses an input value and attempts to resolve hostname and port of requested server
+func resolveHostPort(value string, existingServers []services.Server) (string, int, error) {
+	var hostName = ""
+	// if port is 0, it means the client wants us to figure out which port to use
+	var hostPort = 0
+
+	// check if server exists by comparing its UUID or hostname
+	for i := range existingServers {
+		node := existingServers[i]
+		if node.GetName() == value || node.GetHostname() == value {
```
Comment (kontsevoy) [inline lib/web/terminal.go]: but `lunA` == `Luna`

**Review by klizhentas — APPROVED** [review]

**Review by kontsevoy — CHANGES_REQUESTED** [review]

File: lib/web/terminal.go (hunk 1 above)
Comment (alex-kovoy) [reply lib/web/terminal.go]: fixed

**Review by kontsevoy — APPROVED** [review]
