### PR TITLE
Use first available auth server

### LINKED ISSUE #10019: Stale DynamoDB Auth Service Items
A customer has a need to frequently restart auth/proxy pods that are deployed by the `teleport-cluster` Helm chart. This results in stale DynamoDB auth service items that persist for a time period typically not exceeding one hour. All issues are resolved when the stale DynamoDB auth service items are deleted manually or the DynamoDB auth service items expire.

The following are logs that are observed when the issue is occurring:

Error from client:
```
ERROR REPORT:
Original Error: *trace.TraceErr connection error: desc = &#34;transport: authentication handshake failed: read tcp 192.168.248.193:65080-&gt;172.31.150.10:443: i/o timeout&#34;
Stack Trace:
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/client.go:2340 github.com/gravitational/teleport/api/client.(*Client).GetResources
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/client.go:1095 github.com/gravitational/teleport/api/client.(*Client).GetDatabaseServers
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/auth/clt.go:1589 github.com/gravitational/teleport/lib/auth.(*Client).GetDatabaseServers
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/client.go:617 github.com/gravitational/teleport/lib/client.(*ProxyClient).GetDatabaseServers
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/api.go:1925 github.com/gravitational/teleport/lib/client.(*TeleportClient).ListDatabaseServers
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/api.go:1930 github.com/gravitational/teleport/lib/client.(*TeleportClient).ListDatabases
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/db.go:50 main.onListDatabases.func1
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/lib/client/api.go:504 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/db.go:49 main.onListDatabases
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:659 main.Run
        /tmp/build-darwin-amd64/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:285 main.main
        /var/folders/ys/8czjjsys38x504kj8172pd_m0000gp/T/drone-c5rOl7CA9nUzyqDD/home/drone/build-9935-1643075385-toolchains/go/src/runtime/proc.go:255 runtime.main
        /var/folders/ys/8czjjsys38x504kj8172pd_m0000gp/T/drone-c5rOl7CA9nUzyqDD/home/drone/build-9935-1643075385-toolchains/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: connection error: desc = &#34;transport: authentication handshake failed: read tcp 192.168.248.193:65080-&gt;172.31.150.10:443: i/o timeout&#34;
```

error from kube-agent:

```
teleport-kube-agent-9bc9d67f9-8gg5g teleport 2022-01-27T14:49:18Z WARN [DB:SERVIC] Failed to create remote tunnel: failed to dial: all auth methods failed, conn: <nil>. leaseID:900 target:redacted.com:443 reversetunnel/agent.go:384

```

gz#4346

gz#3996

### PR DESCRIPTION
**Pull request by probakowski**
Currently we use random auth server from the list but if it's unavailable (for example it was restarted but there's still entry in cache, dynamodb backend etc) we return error.
This change tries all servers (in random order) and uses first that is available.

Closes https://github.com/gravitational/teleport/issues/10019

### CODE REVIEW

File: lib/srv/alpnproxy/auth/auth_proxy.go [hunk 1]
```diff
@@ -113,13 +114,21 @@ func (s *AuthProxyDialerService) dialLocalAuthServer(ctx context.Context) (net.C
 	if len(authServers) == 0 {
 		return nil, trace.NotFound("empty auth servers list")
 	}
-	//TODO(smallinksy) Better support for HA. Add dial retry on auth network errors.
-	authServerIndex := rand.Intn(len(authServers))
-	conn, err := net.Dial("tcp", authServers[authServerIndex].GetAddr())
-	if err != nil {
-		return nil, trace.Wrap(err)
+	var errors []string
```
Comment (zmb3) [inline lib/srv/alpnproxy/auth/auth_proxy.go:117]: You could make this `var errors []error`.

Then use `errors = append(errors, fmt.Errorf("%s: %w", addr, err)`.

And then return `trace.NewAggregate(errors)`

File: lib/srv/alpnproxy/auth/auth_proxy.go [hunk 2]
```diff
@@ -113,13 +114,21 @@ func (s *AuthProxyDialerService) dialLocalAuthServer(ctx context.Context) (net.C
...
+
+	//select random server from list, try others if it's unavailable
+	for len(authServers) > 0 {
```
Comment (espadolini) [inline lib/srv/alpnproxy/auth/auth_proxy.go:120]: Instead of doing this, just build a map with the auth servers (or even just the addresses) as keys, and iterate over it; iteration order is random (a little biased, but it's going to be biased in hash space anyway).

File: lib/srv/alpnproxy/auth/auth_proxy.go [hunk 3]
```diff
@@ -113,13 +114,21 @@ func (s *AuthProxyDialerService) dialLocalAuthServer(ctx context.Context) (net.C
...
 		return nil, trace.NotFound("empty auth servers list")
 	}
-	//TODO(smallinksy) Better support for HA. Add dial retry on auth network errors.
-	authServerIndex := rand.Intn(len(authServers))
-	conn, err := net.Dial("tcp", authServers[authServerIndex].GetAddr())
-	if err != nil {
-		return nil, trace.Wrap(err)
+	var errors []string
+
+	//select random server from list, try others if it's unavailable
```
Comment (espadolini) [inline lib/srv/alpnproxy/auth/auth_proxy.go:119]: It's idiomatic to leave a space between the `//` and the comment if it's not a comment meant for automated tools:

```suggestion
	// iterate over the addresses in random order
```

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+	require.Equal(t, "empty auth servers list", err.Error())
+}
+
+func TestDialLocalAuthServerNoAvailableServers(t *testing.T) {
+	server1, err := types.NewServer("s1", "auth", types.ServerSpecV2{Addr: "invalid:8000"})
+	require.Nil(t, err)
+	s := NewAuthProxyDialerService(nil, mockAuthGetter{servers: []types.Server{server1}})
+	_, err = s.dialLocalAuthServer(context.Background())
+	require.Error(t, err)
+	require.Equal(t, "all auth servers unavailable: invalid:8000: dial tcp: lookup invalid: no such host", err.Error())
```
Comment (espadolini) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:37]: CI disagrees with this exact error; a bit of a moot point if you might change the error anyway, but I'd be a little lax on the exact error message - something along the lines of `require.Contains(t, "all auth servers unavailable: invalid:8000", err.Error())` would be better.

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+	require.Nil(t, err)
+	servers := []types.Server{server}
+	// multiple invalid servers to minimize chance that we select good one first try
+	for i := 0; i < 20; i++ {
+		server, err := types.NewServer("s1", "auth", types.ServerSpecV2{Addr: "invalid2:8000"})
+		require.Nil(t, err)
+		servers = append(servers, server)
+	}
+	s := NewAuthProxyDialerService(nil, mockAuthGetter{servers: servers})
+	_, err = s.dialLocalAuthServer(context.Background())
```
Comment (espadolini) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:54]: Won't this block indefinitely, because you're not actually accepting connections on your listener? Either way, pass a context with a timeout here.

File: lib/srv/alpnproxy/auth/auth_proxy.go [hunk 6]
```diff
@@ -113,13 +114,21 @@ func (s *AuthProxyDialerService) dialLocalAuthServer(ctx context.Context) (net.C
...
+	for len(authServers) > 0 {
+		authServerIndex := rand.Intn(len(authServers))
+		var conn net.Conn
+		addr := authServers[authServerIndex].GetAddr()
+		conn, err = net.Dial("tcp", addr)
```
Comment (espadolini) [inline lib/srv/alpnproxy/auth/auth_proxy.go:124]: While we're touching this:
```suggestion
		var d net.Dialer
		conn, err = d.DialContext(ctx, "tcp", addr)
```

File: lib/srv/alpnproxy/auth/auth_proxy.go (hunk 2 above)
Comment (codingllama) [reply lib/srv/alpnproxy/auth/auth_proxy.go:120]: My 2c: I'd rather take the random, otherwise I fear this becomes stable if the list of auth servers is always the same.

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+
+func (m mockAuthGetter) GetAuthServers() ([]types.Server, error) {
+	return m.servers, nil
+}
+
+func TestDialLocalAuthServerNoServers(t *testing.T) {
+	s := NewAuthProxyDialerService(nil, mockAuthGetter{servers: []types.Server{}})
+	_, err := s.dialLocalAuthServer(context.Background())
+	require.Error(t, err)
+	require.Equal(t, "empty auth servers list", err.Error())
```
Comment (codingllama) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:28]: As Edoardo mentioned below, I'd go with a Contains and match just enough of the message to be satisfied.

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+}
+
+func TestDialLocalAuthServerNoAvailableServers(t *testing.T) {
+	server1, err := types.NewServer("s1", "auth", types.ServerSpecV2{Addr: "invalid:8000"})
+	require.Nil(t, err)
```
Comment (codingllama) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:33]: nit:

```suggestion
	require.NoError(t, err)
```

Same for others.

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+	s := NewAuthProxyDialerService(nil, mockAuthGetter{servers: []types.Server{server1}})
+	_, err = s.dialLocalAuthServer(context.Background())
+	require.Error(t, err)
```
Comment (codingllama) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:36]: Add a short description if the error pertains to the method we are testing:

```suggestion
	require.Error(t, err, "dialLocalAuthServer expected to fail")
```

Same for others.

File: lib/srv/alpnproxy/auth/auth_proxy_test.go (hunk 4 above)
Comment (codingllama) [reply lib/srv/alpnproxy/auth/auth_proxy_test.go:37]: +1

File: lib/srv/alpnproxy/auth/auth_proxy_test.go (hunk 5 above)
Comment (codingllama) [reply lib/srv/alpnproxy/auth/auth_proxy_test.go:54]: +1 for a short timeout

**Review by codingllama — COMMENTED** [review]
Overall seems reasonable to me.

File: lib/srv/alpnproxy/auth/auth_proxy.go (hunk 2 above)
Comment (probakowski) [reply lib/srv/alpnproxy/auth/auth_proxy.go:120]: I'd rather not do that for couple of reasons:

- iteration order is currently starting from random start point but then it's always the same, so for map {1:1,2:2,3:3} iteration order can be (keys only): [1,2,3], [2,3,1] or [3,1,2]. If first server is unavailable, then second one will handle 2/3 of the traffic instead of 50%
- iteration order is undefined not random so it can change in future versions of Go (unlikely but still)
- most of the time first server will work so building map will be waste of time

File: lib/srv/alpnproxy/auth/auth_proxy.go (hunk 1 above)
Comment (probakowski) [reply lib/srv/alpnproxy/auth/auth_proxy.go]: thanks! I haven't spotted `trace.NewAggregate`

File: lib/srv/alpnproxy/auth/auth_proxy_test.go (hunk 7 above)
Comment (codingllama) [reply lib/srv/alpnproxy/auth/auth_proxy_test.go:29]: Missed this one?

**Review by codingllama — APPROVED** [review]

File: lib/srv/alpnproxy/auth/auth_proxy.go (hunk 2 above)
Comment (espadolini) [reply lib/srv/alpnproxy/auth/auth_proxy.go:120]: You're right, for a small fixed list turned to map (which is what we'll almost always have) the iteration order is not only the same except rotated, but it's also very much skewed towards a specific order.

It's fine like this although I'd prefer swapping in the last item in the slice in the removed item's position instead of sliding everything by one index.

**Review by espadolini — APPROVED** [review]

File: lib/srv/alpnproxy/auth/auth_proxy.go (hunk 2 above)
Comment (probakowski) [reply lib/srv/alpnproxy/auth/auth_proxy.go:120]: That's even better, I've changed it

File: lib/srv/alpnproxy/auth/auth_proxy_test.go (hunk 7 above)
Comment (probakowski) [reply lib/srv/alpnproxy/auth/auth_proxy_test.go:29]: It has the comment now, maybe something was not refreshed earlier?

**Comment by probakowski** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|branch/v8|[](https://github.com/gravitational/teleport/pull/11597)|
|✅|branch/v9|[](https://github.com/gravitational/teleport/pull/11598)|

Note: Successful backport PRs will be merged automatically after passing CI.

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
