### PR TITLE
Use lib/cloud/aws instead of db errors for ec2 discovery

### LINKED ISSUE #31507: EC2 watcher should not depend on database access
The EC2 watcher code is importing code from `lib/srv/db` just to convert an AWS error:

https://github.com/gravitational/teleport/blob/07db0ffb9cdd9ec7756b87698ce5a0716a085b35/lib/srv/server/ec2_watcher.go#L390

This code handles errors from several types of databases and several different public cloud providers and should not be used from code that is specific to EC2.

We should write our own conversion logic or maybe use `lib/cloud/aws.ConvertRequestFailureError`.

### PR DESCRIPTION
**Pull request by lxea**
Closes https://github.com/gravitational/teleport/issues/31507

### CODE REVIEW

File: lib/srv/server/ec2_watcher.go [hunk 1]
```diff
@@ -30,9 +30,9 @@ import (
 	usageeventsv1 "github.com/gravitational/teleport/api/gen/proto/go/usageevents/v1"
 	"github.com/gravitational/teleport/api/types"
 	"github.com/gravitational/teleport/lib/cloud"
+	taws "github.com/gravitational/teleport/lib/cloud/aws"
```
Comment (marcoandredinis) [inline lib/srv/server/ec2_watcher.go:33]: Can we re-use one of the already existing alias for this import?
`libcloudaws` or `awslib`

**Review by marcoandredinis — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
