### PR TITLE
Web discover minor fixes

### LINKED ISSUE #48802: Optional security group is required in discovery flow
Expected behavior:

Default security group would be used or a meaningful error why it's required.

Current behavior:

The Step indicates that selecting a security group is optional. However when you try not to select one you get an error and have to select one.

Image

Bug details:
- Teleport version: 16.4.7
- Recreation steps

1. Go through Aurora RDS PostgreSQL discover flow
2. Do not select a security group
3. Attempt to deploy Teleport db service

### LINKED ISSUE #48844: WebDiscover: EKS flow stuck on deployment step when kube agent already exists in the cluster
When you have a teleport agent already installed in the kube cluster, `enrolleksclusters` api returns this:

Image

but in the web UI, instead of showing the message, we continue to poll with a resourceID `undefined` (b/c the `enrolleksclusters` api endpoint returned empty resourceId string) and user gets stuck in this step:

Image

the query with undefined that will never resolve: `https://<cluster>/v1/webapi/sites/<cluster>/kubernetes?searchAsRoles=&limit=1&startKey=&query=&search=teleport.internal%2Fresource-id%20undefined&sort=`

### PR DESCRIPTION
**Pull request by kimlisa**
resolves https://github.com/gravitational/teleport/issues/48844
resolves https://github.com/gravitational/teleport/issues/48802

- removes `optional` wording from RDS select security groups (it's required now)
- fixes `kubectl log` command, i suspect this was incorrect from very beginning
- when a teleport-agent already exists in a EKS cluster, show message that it already exists, instead of continously polling for a resource ID we don't know about (and will never resolve)

image

### CODE REVIEW

**Comment by kimlisa** [comment]
should i also show `debugging` message?

like `don't see your server?`:
image

**Comment by kimlisa** [comment]
> Is the screenshot in the PR description before or after the fix?

after (before it was like a pending dialog)

> Shouldn't it be using the danger component that shows a red outline around the text?

that's a good question. i think this was one of those where i just made the design decision and apologize later 😅 . 

i think with the new alert design though, it won't look so awkward anymore. i'll double check with Kenny, any design changes will be in another PR.

File: web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEksCluster.tsx [hunk 1]
```diff
@@ -302,16 +308,15 @@ export function EnrollEksCluster(props: AgentStepProps) {
...
-        )
-      ) {
-        setEnrollmentState({
+      } else if (result.error) {
+        const errorState: EKSClusterEnrollmentState = {
           status: 'error',
           error: `Cluster enrollment error: ${result.error}`,
-        });
+        };
+        if (result.error.includes('teleport-kube-agent is already installed')) {
```
Comment (marcoandredinis) [inline web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEksCluster.tsx:316]:
```suggestion
        if (result.error.includes('teleport-kube-agent is already installed on the cluster')) {
```
We have to be stricter here because this string appears in two scenarios:
- agent is already installed
- could not determine if agent is already installed

https://github.com/gravitational/teleport/blob/3aa6f3c5cf71b81e61f4dd1653913e848e084981/lib/integrations/awsoidc/eks_enroll_clusters.go#L440-L445

Comment (kimlisa) [reply web/packages/teleport/src/Discover/Kubernetes/EnrollEKSCluster/EnrollEksCluster.tsx]: thanks for the catch

**Review by GavinFrazar — APPROVED** [review]
LGTM

**Review by marcoandredinis — APPROVED** [review]

**Review by ryanclark — APPROVED** [review]
