### PR TITLE
fix connection tester error for Aurora databases

### LINKED ISSUE #47206: RDS Discover flow connection test fails with per-session MFA enabled
Expected behavior:
MFA prompt and continue connection test.

Current behavior:

Bug details:
- Teleport version: 16.4.2 cloud
- Recreation steps: enable per-session MFA (example, `require_session_mfa: true` in `access` role) then follow RDS discover flow till connection tester

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #47206

These changes were originally made to fix #47206. The fix for #47206 was preempted by https://github.com/gravitational/teleport/pull/48811 fixing a duplicate issue, but this PR still adds other database engines to the protocol conversion func, so I'm keeping that set of changes.
- #47206 
- https://github.com/gravitational/teleport/pull/48811

Other than that, this PR fixes a related (unreported) issue I came across where a user can try to test connection an Aurora Postgres without a "Database name" - that doesn't work because Aurora postgres requires a database name just like other Postgres protocol engines:

image

So this PR makes database name a required field in the connection tester for any "postgres" protocol db.

### CODE REVIEW

**Review by avatus — APPROVED** [review]

File: web/packages/teleport/src/Discover/SelectResource/databases.tsx [hunk 1]
```diff
@@ -421,10 +421,27 @@ export function getDatabaseProtocol(engine: DatabaseEngine): DbProtocol {
...
+    case DatabaseEngine.SqlServer:
+      return 'sqlserver';
+    case DatabaseEngine.Snowflake:
+      return 'snowflake';
+    case DatabaseEngine.Cassandra:
+      return 'cassandra';
+    case DatabaseEngine.ElasticSearch:
+      return 'elasticsearch';
+    case DatabaseEngine.DynamoDb:
+      return 'dynamodb';
```
Comment (gzdunek) [inline web/packages/teleport/src/Discover/SelectResource/databases.tsx:444]: We can make this switch exhaustive by adding:
```ts
    default:
      engine satisfies never;
```
at the end. This will return a TS error when someone adds a new DB engine but not provide a protocol for it here.
We can also remove `return '' as any`.

File: web/packages/teleport/src/Discover/Database/TestConnection/TestConnection.tsx [hunk 2]
```diff
@@ -186,7 +186,7 @@ export function TestConnection() {
                   attempt.status === 'processing' || nameOpts.length === 0
                 }
                 // Database name is required for Postgres.
```
Comment (gzdunek) [inline web/packages/teleport/src/Discover/Database/TestConnection/TestConnection.tsx:188]: Maybe we should remove this comment? Or at least move it to `isDbNameRequired`?

**Review by gzdunek — APPROVED** [review]

File: web/packages/teleport/src/Discover/Database/TestConnection/TestConnection.tsx [hunk 3]
```diff
@@ -238,3 +238,13 @@ function getInputValue(input: string, inputKind: 'name' | 'user') {
   }
   return input;
 }
+
+function isDbNameRequired(engine: DatabaseEngine) {
```
Comment (greedy52) [inline web/packages/teleport/src/Discover/Database/TestConnection/TestConnection.tsx:242]: FYI:
https://github.com/gravitational/teleport/blob/1a6f8d4c8a11056e9d9bae75c39be8d86ee6f28d/web/packages/teleport/src/Databases/ConnectDialog/ConnectDialog.tsx#L51-L58

File: web/packages/teleport/src/Discover/SelectResource/databases.tsx (hunk 1 above)
Comment (GavinFrazar) [reply web/packages/teleport/src/Discover/SelectResource/databases.tsx:444]: thank you! This actually caught that I missed the `doc` engine type and highlighted it in my editor. However it doesn't seem to cause any build failure when I rebuild Teleport.
