### PR TITLE
Workload ID: Add support for Federated Trust Bundles into `spiffe-svid` output

### LINKED ISSUE #46471: `TestTrustBundleCache_Run` Flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport.e/actions/runs/10790207729/job/29924903268

#### Relevant snippet

```
-test.shuffle 1725967802673722549
{"caller":"regular/sftp.go:216","component":"subsystem:sftp","level":"debug","message":"SFTP process finished","timestamp":"2024-09-10T11:30:12Z"}
FAIL	github.com/gravitational/teleport/lib/srv/regular	600.301s
===================================================
OUTPUT github.com/gravitational/teleport/lib/tbot/spiffe
===================================================
-test.shuffle 1725967004099324319
FAIL
{"timestamp":"2024-09-10T11:16:45Z","level":"info","caller":"spiffe/trust_bundle_cache.go:502","message":"Processed update for local trust bundle","event_type":"Put","event_resource_kind":"cert_authority","event_resource_name":"example.com","x509_authorities":2}
coverage: 59.4% of statements
FAIL	github.com/gravitational/teleport/lib/tbot/spiffe	1.328s
===================================================
OUTPUT github.com/gravitational/teleport/lib/tbot/spiffe.TestTrustBundleCache_Run
===================================================
=== RUN   TestTrustBundleCache_Run
=== PAUSE TestTrustBundleCache_Run
=== CONT  TestTrustBundleCache_Run
    trust_bundle_cache_test.go:283: 
        	Error Trace:	/__w/teleport.e/teleport.e/lib/tbot/spiffe/trust_bundle_cache_test.go:283
        	Error:      	"[0xc000264008]" should have 2 item(s), but has 1
        	Test:       	TestTrustBundleCache_Run
{"timestamp":"2024-09-10T11:16:45Z","level":"debug","caller":"spiffe/trust_bundle_cache.go:476","message":"Processing update for local trust bundle","event_type":"Put","event_resource_kind":"cert_authority","event_resource_name":"example.com","trusted_tls_key_pairs":2}
```

### PR DESCRIPTION
**Pull request by strideynet**
Part of https://github.com/gravitational/teleport/issues/44863
Builds on https://github.com/gravitational/teleport/pull/45749 
Should also close https://github.com/gravitational/teleport/issues/46471

https://github.com/gravitational/teleport/pull/45749  added the support for federated trust bundles into the main Workload API. This PR also adds it as an option within the `spiffe-svid` output. I've continued to try and ensure broad compatibility with `spiffe-helper` here in terms of format.

Backports will be stacked onto those for https://github.com/gravitational/teleport/pull/45749  so we can release for v16.3

### CODE REVIEW

**Comment by strideynet** [comment]
I will manually backport this into the backport branches for https://github.com/gravitational/teleport/pull/45749 so we can do a synchronised release for a specific version.

File: lib/tbot/spiffe/trust_bundle_cache.go [hunk 1]
```diff
@@ -557,13 +512,68 @@ func (m *TrustBundleCache) processEvent(ctx context.Context, event types.Event)
...
 			bundleSet.Federated[federation.Metadata.Name] = bundle
-			m.setAndBroadcastBundleSet(bundleSet)
+			m.setBundleSet(bundleSet)
 		}
 	default:
 		log.WarnContext(ctx, "Ignoring unexpected event type")
 	}
 }
 
+func FetchInitialBundleSet(
```
Comment (bl-nero) [inline lib/tbot/spiffe/trust_bundle_cache.go:522]: Doc comment please?

File: lib/tbot/service_spiffe_svid_output.go [hunk 2]
```diff
@@ -50,61 +50,124 @@ const (
 
 // SPIFFESVIDOutputService
```
Comment (bl-nero) [inline lib/tbot/service_spiffe_svid_output.go:51]: It would be great if you could amend this doc comment. Knowing what kind of "output" we mean here, what is the service's role in the grand scheme of things, would be greatly appreciated and would help understanding it at glance.

File: lib/tbot/service_spiffe_svid_output.go [hunk 3]
```diff
@@ -134,8 +197,35 @@ func (s *SPIFFESVIDOutputService) generate(ctx context.Context) error {
...
+	privateKey *rsa.PrivateKey,
+) error {
+	ctx, span := tracer.Start(
+		ctx,
+		"SPIFFESVIDOutputService/render",
+	)
+	defer span.End()
+	s.log.InfoContext(ctx, "Rendering output")
+
+	// Check the ACLs. We can't fix them, but we can warn if they're
```
Comment (bl-nero) [inline lib/tbot/service_spiffe_svid_output.go:218]: Why was this moved down to the `render()` function?

File: lib/tbot/service_spiffe_svid_output.go [hunk 4]
```diff
@@ -134,8 +197,35 @@ func (s *SPIFFESVIDOutputService) generate(ctx context.Context) error {
 		s.botCfg.CertificateTTL,
 	)
 	if err != nil {
+		return nil, nil, trace.Wrap(err)
+	}
+	return res, privateKey, nil
+}
+
+func (s *SPIFFESVIDOutputService) render(
```
Comment (bl-nero) [inline lib/tbot/service_spiffe_svid_output.go:205]: What exactly does the word `render` mean in this context? Does it mean "write to the config"? "Write to the certificate store"? Please make it more explicit and/or add a doc comment.

File: lib/tbot/service_spiffe_svid_output.go [hunk 5]
```diff
@@ -169,17 +254,23 @@ func (s *SPIFFESVIDOutputService) generate(ctx context.Context) error {
 		return trace.Wrap(err, "writing svid certificate")
 	}
 
-	trustBundleBytes := &bytes.Buffer{}
-	for _, ca := range spiffeCAs {
-		for _, cert := range services.GetTLSCerts(ca) {
-			// Values are already PEM encoded, so we just append to the buffer
-			if _, err := trustBundleBytes.Write(cert); err != nil {
-				return trace.Wrap(err, "writing trust bundle to buffer")
+	trustBundleBytes, err := bundleSet.Local.X509Bundle().Marshal()
```
Comment (bl-nero) [inline lib/tbot/service_spiffe_svid_output.go:257]: I'm having trouble understanding this piece. Here, we are marshalling the federated bundles from `bundleSet.Federated`, as opposed to "whatever was returned from `GetCertAuthorities`. Can you elaborate a bit about what are both of these things and why the result of `GetCertAuthorities` and `services.GetTLSCerts` can now be replaced by this piece of code?

File: lib/tbot/spiffe/trust_bundle_cache.go [hunk 6]
```diff
@@ -47,13 +50,21 @@ type BundleSet struct {
 	// (the name of the SPIFFEFederation resource) and excludes the spiffe://
 	// prefix.
 	Federated map[string]*spiffebundle.Bundle
+	stale     chan struct{}
```
Comment (bl-nero) [inline lib/tbot/spiffe/trust_bundle_cache.go:53]: I'm curious: is the change from a subscription model to a "getter/stale" model motivated just by making the interface a bit easier to use, or is there something else I'm missing?

File: lib/tbot/spiffe/trust_bundle_cache.go [hunk 7]
```diff
@@ -338,70 +322,41 @@ func (m *TrustBundleCache) getBundleSet() *BundleSet {
...
-	return outCh, func() {
-		m.mu.Lock()
-		delete(m.subscribers, notifyCh)
-		m.mu.Unlock()
+// GetBundleSet returns the current BundleSet. If the cache is not yet
+// initialized, it will block until it is.
+func (m *TrustBundleCache) GetBundleSet(
+	ctx context.Context,
+) (*BundleSet, error) {
+	bundleSet := m.getBundleSet()
```
[the remark this answers is not in the document]
Comment (strideynet) [reply lib/tbot/spiffe/trust_bundle_cache.go:351]: Ah good catch, this is definitely redundant.

File: lib/tbot/spiffe/trust_bundle_cache.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (strideynet) [reply lib/tbot/spiffe/trust_bundle_cache.go:522]: Yeah - moving it around a little bit so it can be called in a once-off nature by a caller who doesn't want to spin up the whole cache. `tbot` operates either as a daemon (in which the cache makes a lot of sense) and also in a "one-shot" mode. In "one-shot" spinning up the cache is unnecessary as the info can just be fetched once.

File: lib/tbot/spiffe/trust_bundle_cache.go [hunk 8]
```diff
@@ -576,6 +586,11 @@ func listAllSPIFFEFederations(
 			PageToken: token,
 		})
 		if err != nil {
+			// Support auth server being too old.
```
[the remark this answers is not in the document]
Comment (strideynet) [reply lib/tbot/spiffe/trust_bundle_cache.go:589]: Before `FetchInitialBundleSet` was introduced, as part of the cache init, it would determine if the auth server was new enough, and then conditionally call `listAllSPIFFEFederations`. However, since introducing `FetchInitialBundleSet`, there's now no clean place to perform that check ahead of time, and it's safe to fail to just not returning anything here.

File: lib/tbot/service_spiffe_svid_output.go (hunk 4 above)
Comment (strideynet) [reply lib/tbot/service_spiffe_svid_output.go:205]: It's a bit of a standard within this package, all of the Output services will have some code that fetches all the necessary data, and then they call the `render` to actually convert that into some config files and write them. Previously the `SPIFFESVIDOutputService` was a little odd in that it just had a `generate` and no `render`.

File: lib/tbot/spiffe/trust_bundle_cache.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (strideynet) [reply lib/tbot/spiffe/trust_bundle_cache.go]: 735d16669c

File: lib/tbot/spiffe/trust_bundle_cache.go [hunk 9]
```diff
@@ -338,70 +322,41 @@ func (m *TrustBundleCache) getBundleSet() *BundleSet {
...
 	return m.bundleSet.Clone()
 }
 
-func (m *TrustBundleCache) setAndBroadcastBundleSet(bundleSet *BundleSet) {
+func (m *TrustBundleCache) setBundleSet(bundleSet *BundleSet) {
 	m.mu.Lock()
-	// Clone the bundle set to avoid the caller mutating the state after it has
-	// been set.
+	old := m.bundleSet
+
```
[the remark this answers is not in the document]
Comment (strideynet) [reply lib/tbot/spiffe/trust_bundle_cache.go:332]: 735d16669c

File: lib/tbot/spiffe/trust_bundle_cache.go (hunk 1 above)
Comment (strideynet) [reply lib/tbot/spiffe/trust_bundle_cache.go:523]: cd5fea0816

File: lib/tbot/service_spiffe_svid_output.go (hunk 2 above)
Comment (strideynet) [reply lib/tbot/service_spiffe_svid_output.go]: cd5fea0816

File: lib/tbot/service_spiffe_svid_output.go (hunk 3 above)
Comment (strideynet) [reply lib/tbot/service_spiffe_svid_output.go:220]: I think the diff really looks a bit odd here since the PR introduced the render function. It makes more sense for this to be in render since it actually touches/writes to the destination.

File: lib/tbot/service_spiffe_svid_output.go (hunk 5 above)
Comment (strideynet) [reply lib/tbot/service_spiffe_svid_output.go:259]: Sure. So a "Trust Bundle" is really just the SPIFFE terminology for the information you need to verify that a certificate has been issued by a Certificate Authority. The "local" trust bundle is actually just the SPIFFE CA from your local Teleport cluster. The major change here is that the SPIFFE trust bundle cache introduced in my last PR is now responsible for converting the CertificateAuthority into the TrustBundle format. This lets the conversion be shared by a few different consumers now instead of each consumer independently converting the SPIFFE CertificateAuthority into a trust bundle.

File: lib/tbot/service_spiffe_svid_output.go (hunk 3 above)
Comment (timothyb89) [reply lib/tbot/service_spiffe_svid_output.go:220]: (Admittedly most other outputs make these verification calls during `generate()` but it's all pretty arbitrary. The two could just as well be one long function.)

File: lib/tbot/service_spiffe_svid_output.go [hunk 10]
```diff
@@ -48,63 +48,128 @@ const (
...
+		var retryAfter <-chan time.Time
+		if failures > 0 {
+			backoffTime := time.Second * time.Duration(math.Pow(2, float64(failures-1)))
+			if backoffTime > time.Minute {
+				backoffTime = time.Minute
+			}
+			backoffTime = jitter(backoffTime)
+			s.log.WarnContext(
+				ctx,
+				"Last attempt to generated failed, will retry",
```
Comment (timothyb89) [inline lib/tbot/service_spiffe_svid_output.go:112]:
```suggestion
				"Last attempt to generate output failed, will retry",
```

maybe?

**Review by timothyb89 — APPROVED** [review]
Looks quite nice, I like that stale / getter pattern a lot!

**Review by ryanclark — APPROVED** [review]

**Comment by strideynet** [comment]
Will manually backport into backports for https://github.com/gravitational/teleport/pull/45749
