### PR TITLE
Fix several issues with audit events.

### LINKED ISSUE #1687: Cache hit/miss logs
Logs are cluttered with the following.

````
DEBU [CLIENT:CA] Recent cache hit. key:clusterName state/cachingaccesspoint.go:777
DEBU [CLIENT:CA] Recent cache hit. key:clusterConfig state/cachingaccesspoint.go:777
DEBU [CLIENT:CA] Recent cache miss. key:clusterName state/cachingaccesspoint.go:782
DEBU [CLIENT:CA] Recent cache miss. key:clusterConfig state/cachingaccesspoint.go:782
DEBU [CLIENT:CA] Recent cache hit. key:clusterName state/cachingaccesspoint.go:777
DEBU [CLIENT:CA] Recent cache hit. key:clusterConfig state/cachingaccesspoint.go:777
DEBU [CLIENT:CA] Recent cache miss. key:clusterName state/cachingaccesspoint.go:782
DEBU [CLIENT:CA] Recent cache miss. key:clusterConfig state/cachingaccesspoint.go:782
```

### LINKED ISSUE #1690: Missing gops-addr flag
Docker workflow is broken, complains about missing `--gops-addr` upon startup.

```
$ make up
docker-compose up
Recreating two-auth ... 
Recreating two-node ... 
Recreating one ... 
Recreating one-proxy ... 
Recreating one-node ... 
Recreating one ... done
Attaching to two-auth, one-node, two-node, one-proxy, two-proxy, one
two-auth     | unknown long flag '--gops-addr'
one-node     | unknown long flag '--gops-addr'
two-auth exited with code 1
one-node exited with code 1
two-node     | unknown long flag '--gops-addr'
one-proxy    | unknown long flag '--gops-addr'
two-node exited with code 1
two-proxy    | unknown long flag '--gops-addr'
one          | unknown long flag '--gops-addr'
one-proxy exited with code 1
two-proxy exited with code 1
one exited with code 1
```

### PR DESCRIPTION
**Pull request by klizhentas**
1. Fixes several cosmetic issues with logs:

Fixes #1690, fixes #1687

2. Fixes deadlocks that were revealed during stress
testing on slow encrypted EFS system.

The following deadlock scenario was happening:

Goroutine 1:

t1. auditlock.Lock <- success
t3. diskSessionLogger.Lock <- blocked

Gorotuine 2:

t2. diskSessionLogger.Lock <- success
t4. auditLock.Lock  <- blocked

3. Update ansible upgrade scripts
to support custom binary upgrades.

4. Fix docker flow by removing deprecated
--gops-addr flag

5. Remove verbose logging lines.

6. Reduce compression efficiency to
reduce large memory load.

### CODE REVIEW

File: lib/events/sessionlog.go [hunk 1]
```diff
@@ -154,11 +152,15 @@ func (sl *DiskSessionLogger) finalize() error {
...
-		sl.chunksFile.Close()
+		if err := sl.chunksFile.Close(); err != nil {
+			log.Warningf("failed closing chunks file: %v", err)
+		}
 	}
 
 	if sl.eventsFile != nil {
-		sl.eventsFile.Close()
+		if err := sl.eventsFile.Close(); err != nil {
+			log.Warningf("failed closing events file: %v")
```
Comment (r0mant) [inline lib/events/sessionlog.go]: Missing `err`. Also, "Failed" and dot at the end.

File: lib/events/sessionlog.go [hunk 2]
```diff
@@ -154,11 +152,15 @@ func (sl *DiskSessionLogger) finalize() error {
 	}
 
 	if sl.chunksFile != nil {
-		sl.chunksFile.Close()
+		if err := sl.chunksFile.Close(); err != nil {
+			log.Warningf("failed closing chunks file: %v", err)
```
Comment (r0mant) [inline lib/events/sessionlog.go]: "Failed", dot at the end.

**Review by r0mant — APPROVED** [review]

**Review by russjones — APPROVED** [review]
