### PR TITLE
Fix `useMfa` error handling

### LINKED ISSUE #50582: web: canceling MFA dialog shows same error twice
If you cancel the per-session MFA dialog when opening a web app from the resources view, the error message shows up both in the modal and in the page behind it.

Image

### PR DESCRIPTION
**Pull request by Joerger**
The original error is now displayed in the MFA dialog, and the `MFA canclled by user` error is displayed at the top level after the MFA dialog is closed:

Screenshot 2025-01-07 at 12 22 32 PM
Screenshot 2025-01-07 at 12 23 37 PM

Fixes https://github.com/gravitational/teleport/issues/50582

This will be backported with https://github.com/gravitational/teleport/pull/50529

### CODE REVIEW

**Comment by zmb3** [comment]
Can we use the American-English spelling (canceled) instead of the British-English spelling (cancelled)?

File: web/packages/teleport/src/lib/useMfa.ts [hunk 1]
```diff
@@ -91,62 +90,63 @@ export function useMfa({ req, isMfaRequired }: MfaProps): MfaState {
...
+      };
+
+      const [resp, err] = await getResponse(promise, challenge);
+
       if (err) throw err;
-      return resp;
+
+      if (resp instanceof Error) {
+        throw resp;
+      }
```
Comment (gzdunek) [inline web/packages/teleport/src/lib/useMfa.ts:135]: This may be really confusing for future readers. What's the reason of having errors both in `resp` and in `err`? What is the difference between them? 

On a conceptual level, the _cancellation error_ is still an error, so I think we should not keep it in `resp`. The only thing we actually need is a way to say that the error is a cancellation error. We can do this in the following way:

1. Add a new error type:
```ts
export class MfaCanceledError extends Error {
  constructor() {
    super('User canceled MFA attempt');
  }
}
```
2. Throw it instead of the generic `Error` class:
```ts
const cancelAttempt = () => {
     if (mfaResponseRef.current) {
       mfaResponseRef.current.reject(new MfaCanceledError());
     }
   };
```
3. Do not render the dialog if know that it was canceled (something along these lines):
```ts
  if (attempt.status === 'error' && attempt.error instanceof MfaCanceledError) {
    return;
  }
```

Comment (Joerger) [reply web/packages/teleport/src/lib/useMfa.ts:135]: Thanks for the help, this is much better

File: web/packages/teleport/src/lib/useMfa.ts [hunk 2]
```diff
@@ -91,62 +91,62 @@ export function useMfa({ req, isMfaRequired }: MfaProps): MfaState {
...
+        reject = rej;
+      });
+
+      mfaResponseRef.current = {
+        promise,
+        resolve,
+        reject,
+      };
+
+      const [resp, err] = await getResponse(promise, challenge);
```
Comment (gzdunek) [inline web/packages/teleport/src/lib/useMfa.ts:133]: These changes can be reverted, no?

File: web/packages/teleport/src/lib/useMfa.ts [hunk 3]
```diff
@@ -91,62 +91,62 @@ export function useMfa({ req, isMfaRequired }: MfaProps): MfaState {
...
+
       if (err) throw err;
-      return resp;
+
+      return resp as MfaChallengeResponse;
```
Comment (gzdunek) [inline web/packages/teleport/src/lib/useMfa.ts:137]: This assertion should not be needed.

File: web/packages/teleport/src/lib/useMfa.test.tsx [hunk 4]
```diff
@@ -232,14 +232,18 @@ describe('useMfa', () => {
...
+    mfa.current.cancelAttempt();
 
-    await expect(respPromise).rejects.toThrow(
-      new Error('MFA attempt cancelled by user')
-    );
+    await expect(respPromise).rejects.toThrow(new MfaCanceledError());
 
+    // If the user cancels the MFA attempt and closes the dialog, the mfa status
+    // should be 'success', or else the dialog would remain open to display the error.
+    // This error is meant to be handled by the caller.
```
Comment (gzdunek) [inline web/packages/teleport/src/lib/useMfa.test.tsx:241]: This comment is no longer true.

**Review by gzdunek — APPROVED** [review]

**Comment by Joerger** [comment]
@kimlisa @kiosion Friendly ping to review

File: web/packages/teleport/src/components/AuthnDialog/AuthnDialog.tsx [hunk 5]
```diff
@@ -33,11 +33,16 @@ export type Props = {
...
 export default function AuthnDialog({
-  mfaState: { options, challenge, submit, attempt, resetAttempt },
+  mfaState: { options, challenge, submit, attempt, cancelAttempt },
   replaceErrorText,
-  onClose,
+  onClose = () => {},
 }: Props) {
-  if (!challenge && attempt.status !== 'error') return;
+  const showMfaDialog =
+    !!challenge ||
```
Comment (kimlisa) [inline web/packages/teleport/src/components/AuthnDialog/AuthnDialog.tsx:41]: i just want to make sure this is `show mfa dialog if there IS a challenge`? i think that `not` is throwing me off (brain farting)

File: web/packages/teleport/src/components/AuthnDialog/AuthnDialog.tsx [hunk 6]
```diff
@@ -33,11 +33,16 @@ export type Props = {
 };
 
 export default function AuthnDialog({
-  mfaState: { options, challenge, submit, attempt, resetAttempt },
+  mfaState: { options, challenge, submit, attempt, cancelAttempt },
   replaceErrorText,
-  onClose,
+  onClose = () => {},
```
Comment (kimlisa) [inline web/packages/teleport/src/components/AuthnDialog/AuthnDialog.tsx:38]: can you add a comment on why this is optional?

**Review by kimlisa — APPROVED** [review]

File: web/packages/teleport/src/components/AuthnDialog/AuthnDialog.tsx (hunk 5 above)
Comment (Joerger) [reply web/packages/teleport/src/components/AuthnDialog/AuthnDialog.tsx]: Yeah I don't know why I thought it was more readable this way, updated to:
```
  const showError =
    attempt.status === 'error' && !(attempt.error instanceof MfaCanceledError);

  if (!challenge && !showError) return;
```
