### PR TITLE
Fix kernel version parsing on WSL2

### LINKED ISSUE #18210: tbot CLI errors out with any command
After a fresh install of the teleport CLI tools, 'tbot' command fails to provide output or guidance of what kind of configuration is required to be able to run the commands. This currently seems to affect any command that I execute, even the 'tbot version' command.

Expected behavior:
'tbot version' prints out the version

Current behavior:
'tbot version' command errors out with following output: 

```
$ tbot version
ERROR: validating merged bot config
strconv.ParseInt: parsing "16.3": invalid syntax
```

Additional details:

This behavior has been observed on two different machines running Ubuntu on WSL2, as well as within a teleport container.

Repro steps using Docker:

```
$ docker run -it --entrypoint ./usr/local/bin/tbot public.ecr.aws/gravitational/teleport:11.0.1 version
ERROR: validating merged bot config
strconv.ParseInt: parsing "16.3": invalid syntax
```

### PR DESCRIPTION
**Pull request by strideynet**
Our existing Kernel version parsing cannot handle WSL2 kernel versions which include a fourth digit within the semantic version to indicate the patches made by Microsoft to the Linux kernel.

See https://github.com/gravitational/teleport/issues/18210 for more information about the bug experienced on WSL2.

Closes https://github.com/gravitational/teleport/issues/18210

### CODE REVIEW

File: lib/utils/kernel.go [hunk 1]
```diff
@@ -51,6 +50,12 @@ func KernelVersion() (*semver.Version, error) {
 	return ver, nil
 }
 
+// kernelVersionRegex extracts the first three digits of a version from
+// a kernel version - this strips off any additional digits or additional
+// information appended to the kernel version e.g:
+// 5.15.68.1-microsoft-standard-WSL2 => 5.15.68
+var kernelVersionRegex = regexp.MustCompile(`\d+\.\d+\.\d+`)
```
Comment (AntonAM) [inline lib/utils/kernel.go:57]:
```suggestion
var kernelVersionRegex = regexp.MustCompile(`^\d+\.\d+\.\d+`)
```

**Review by AntonAM — APPROVED** [review]
LGTM, just a small optional suggestion :)

File: lib/utils/kernel.go (hunk 1 above)
Comment (strideynet) [reply lib/utils/kernel.go]: 5609b3df59

**Review by rosstimothy — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
