### PR TITLE
Authentication Selection Regressions

### LINKED ISSUE #1272: Adding local users with `tctl users add` fails for Enterprise
Enterprise edition of Teleporot will fail adding user:

```
$ tctl users add rjones --roles=admin
```

... if the auth preference is set to SAML in the YAML config.

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

This PR fixes two authentication selection regressions. The first issue is that the second factor type was not being returned at the `/webapi/ping` endpoint which broke local fallback logins. The second issue was a regressions introduced by the changes in https://github.com/gravitational/teleport/pull/1237 which cause `CheckAndSetDefaults` to be called every time a resource is unmarshaled.

**Implementation**

The first issue was fixed by always returning the second factor type when returning the `AuthenticationSettings` when calling the `/webapi/ping` endpoint.

The second issue was resolved by reducing the scope of what `CheckAndSetDefaults` did. In https://github.com/gravitational/teleport/pull/1237 we updated the `UnmarshalSAMLConnector` method to always call `CheckAndSetDefaults` so we can re-add missing fields that were stripped (like namespaces and expires). This is an issue when you are requesting a connector without secrets because `CheckAndSetDefaults` was looking for signing keys. To fix this the scope of `CheckAndSetDefaults` has been reduced so it checks that the connector has all the required fields but does not validate their values.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1272

### CODE REVIEW

File: lib/services/saml.go [hunk 1]
```diff
@@ -687,10 +687,22 @@ func (o *SAMLConnectorV2) CheckAndSetDefaults() error {
 	if err != nil {
 		return trace.Wrap(err)
 	}
+	if o.Metadata.Name == teleport.Local {
```
Comment (kontsevoy) [inline lib/services/saml.go]: This is a strangely specific check... So you expect it to be "local" sometimes, but how about "anybadvalue"?

**Review by kontsevoy — APPROVED** [review]
Looks clean enough. I did notice, after opening these files in vim (to see the broader picture) that SAML/OIDC related functions generally have no descriptions, so following this code is mentally taxing. As a general desire to keep a healthy level of useful comments I would at least follow both login paths throughout the code and added some explanations to function headers (not just what it does, but also who's the usual caller and it what context)

File: lib/services/saml.go (hunk 1 above)
Comment (russjones) [reply lib/services/saml.go]: This is to make sure no one names their SAML (or OIDC) connector `local` because we now support `tsh --auth=local`.

Comment (kontsevoy) [reply lib/services/saml.go]: got it. I clearly remember that saw a better error message in your code for this purpose, you used to say that "local" is a reserved word and cannot be used to name a connector.

Comment (russjones) [reply lib/services/saml.go]: Rolled back to the original message and original `CheckAndSetDefaults`.

**Review by klizhentas — APPROVED** [review]
