### PR TITLE
Fixes unhandled v1 prefixed 'web/config.js' path

### LINKED ISSUE #51362: Unable to retrieve cluster auth preferences error with Teleport Connect
Expected behavior:

Login to teleport with Teleport Connect

Current behavior:

Users are unable to login or use the device trust flow with Teleport Connect:

Image

Bug details:
- Teleport version: v17.2.0
- Recreation steps
  - run a v17.2.0 teleport cluster
  - run an older version of v17.2.0 (eg v16) teleport connect
- Debug logs: no helpful logs produced

### PR DESCRIPTION
**Pull request by kimlisa**
fixes https://github.com/gravitational/teleport/issues/51362

starting v17.2.0, PR https://github.com/gravitational/teleport/pull/50472 goes into affect where the `lib/web/apiserver.go:NewHandler` now checks for a fixed list of known paths after a `/v1` prefix, before stripping of the `/v1`.

Teleport Connect users (with versions below v17.2.0) were unable to login to clusters with versions v17.2.0, because connect calls this endpoint [web/config.js](https://github.com/gravitational/teleport/blob/89254927ab5b485b1e67bd4150720a9ec6db7e17/lib/client/weblogin.go#L857) with `v1` prefixed, where `web` wasn't part of the list of known paths so `/v1/web/config.js` didn't get handled

The `WebClient.endpoint` func would auto prefix endpoints with `v1` because that's how it was configured.  https://github.com/gravitational/teleport/pull/50472 removes this configuration and i missed the `web/config`

I went through all use cases of `webclient.endpoint` to make sure no other paths were unhandled. Tested fix with branch/v16 connect and master cluster

changelog: Fix backwards compatibility error where users were unable to login with Teleport Connect if Connect version is below v17.2.0 with Teleport cluster version v17.2.0

### CODE REVIEW

**Review by flyinghermit — APPROVED** [review]

File: lib/web/apiserver.go [hunk 1]
```diff
@@ -629,7 +629,7 @@ func NewHandler(cfg Config, opts ...HandlerOption) (*APIHandler, error) {
 				// part[0] is empty space from leading slash "/"
 				// part[1] is the prefix "v1"
 				switch pathParts[2] {
-				case "webapi", "enterprise", "scripts", ".well-known", "workload-identity":
+				case "webapi", "enterprise", "scripts", ".well-known", "workload-identity", "web":
```
Comment (avatus) [inline lib/web/apiserver.go:632]: are we sure we want to include every request that is prefixed with web or only web/config.js?

**Review by avatus — APPROVED** [review]

File: lib/web/apiserver.go (hunk 1 above)
Comment (kimlisa) [reply lib/web/apiserver.go:632]: i think it's fine because we are just saying if `/v1/web` strip the `/v1`

**Review by zmb3 — APPROVED** [review]

**Comment by ravicious** [comment]
I know that some on-call devs use `/web/config.js` to debug customer issues, since it returns data not included in `/webapi/ping`. At the last offsite I've been to, I've also briefly talked with Hugo and Tiago about refactoring it to return plain JS, because now it essentially allows any code to be injected into the Web UI.
