### PR TITLE
Make TestWebClientClosesIdleConnections more stable

### LINKED ISSUE #30535: `TestWebClientClosesIdleConnections ` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5873600105/job/15927105348?pr=30532

#### Relevant snippet

```
=== FAIL: client/webclient TestWebClientClosesIdleConnections (0.01s)
time="2023-08-16T01:46:58Z" level=warning msg="Request for GET 127.0.0.1:33901/webapi/find falling back to PLAIN HTTP"
    webclient_test.go:495: 
        	Error Trace:	/__w/teleport/teleport/api/client/webclient/webclient_test.go:495
        	Error:      	Not equal: 
        	            	expected: 4
        	            	actual  : 0
        	Test:       	TestWebClientClosesIdleConnections
        	Messages:   	expected connection state closed got new
```

### PR DESCRIPTION
**Pull request by rosstimothy**
Improves reliability of the test by eliminating the reliance of connection states being received in the expected order. Instead all states are sorted and compared with the expected states.

Fixes #30535

### CODE REVIEW

File: api/client/webclient/webclient_test.go [hunk 1]
```diff
@@ -489,13 +490,18 @@ func TestWebClientClosesIdleConnections(t *testing.T) {
...
 		case <-time.After(3 * time.Second):
-			t.Fatalf("timeout waiting for expected connection state %s", expected.String())
+			t.Fatalf("timeout waiting for expected connection state %d", i)
 		}
 	}
 
+	slices.Sort(expectedStates)
+	slices.Sort(got)
+
+	require.Equal(t, expectedStates, got)
```
Comment (tigrato) [inline api/client/webclient/webclient_test.go:506]: can't you use `require.ElementsMatch(t, []int{1, 2, 3, 4}, []int{4, 3, 2, 5})`? 
It ignores the order of the events and ensures the two lists include the same values

Comment (tigrato) [reply api/client/webclient/webclient_test.go:506]: It's kinda the same but preserves the ordering which might be important when debugging why a certain test is wrong.

**Review by tigrato — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
