### PR TITLE
Fix TestAuthorizeWithLocksForLocalUser flakiness

### LINKED ISSUE #27604: `TestAuthorizeWithLocksForLocalUser` flakiness
https://github.com/gravitational/teleport/actions/runs/5195772600
https://github.com/gravitational/teleport/actions/runs/5180433207
https://github.com/gravitational/teleport/actions/runs/5179411625
https://github.com/gravitational/teleport/actions/runs/5151590009

The test creates 2 locks and it seems there's a race condition where the second watcher is sometimes created so fast that it receives the event for the first created lock as well:

```
    permissions_test.go:242: 
        	Error Trace:	/__w/teleport/teleport/lib/authz/permissions_test.go:242
        	            				/__w/teleport/teleport/lib/authz/permissions_test.go:176
        	Error:      	Should be empty, but was   &types.LockV2{
        	            	  	Kind:    "lock",
        	            	  	SubKind: "",
make: *** [Makefile:701: test-go-unit] Error 1
        	            	  	Version: "v2",
        	            	  	Metadata: types.Metadata{
        	            	- 		Name: "request-lock",
        	            	+ 		Name: "mfa-lock",
        	            	  		... // 2 ignored and 6 identical fields
        	            	  	},
        	            	  	Spec: types.LockSpecV2{
        	            	  		Target: types.LockTarget{
        	            	  			... // 2 identical fields
        	            	  			Login:          "",
        	            	  			Node:           "",
        	            	- 			MFADevice:      "",
        	            	+ 			MFADevice:      "mfa-device-id",
        	            	  			WindowsDesktop: "",
        	            	- 			AccessRequest:  "test-request",
        	            	+ 			AccessRequest:  "",
        	            	  			Device:         "",
        	            	  			ServerID:       "",
        	            	  			... // 3 identical fields
        	            	  		},
        	            	  		Message: "",
        	            	  		Expires: nil,
        	            	  		... // 5 identical fields
        	            	  	},
        	            	  	XXX_NoUnkeyedLiteral: {},
        	            	  	XXX_unrecognized:     nil,
        	            	  	XXX_sizecache:        0,
        	            	  }
        	Test:       	TestAuthorizeWithLocksForLocalUser
--- FAIL: TestAuthorizeWithLocksForLocalUser (0.03s)
===================================================
```

### PR DESCRIPTION
**Pull request by r0mant**
Closes https://github.com/gravitational/teleport/issues/27604.

### CODE REVIEW

**Review by russjones — APPROVED** [review]

File: lib/authz/permissions_test.go [hunk 1]
```diff
@@ -236,14 +236,29 @@ func upsertLockWithPutEvent(ctx context.Context, t *testing.T, client *testClien
...
+		case event := <-lockWatch.Events():
+			require.Equal(t, types.OpPut, event.Type)
+			if resourceDiff(lock, event.Resource) == "" {
+				return
+			}
+		case <-lockWatch.Done():
+			t.Fatalf("Watcher exited with error: %v.", lockWatch.Error())
+		case <-localCtx.Done():
+			t.Fatalf("Timeout waiting for lock put: %v.", lock)
+		}
```
Comment (tigrato) [inline lib/authz/permissions_test.go:261]: Can we transform it to use `require.Eventually`? It feels easier to read

```suggestion
	require.Eventually(t, func() bool {
		select {
		case event := <-lockWatch.Events():
			return types.OpPut == event.Type && resourceDiff(lock, event.Resource) == ""
		case <-lockWatch.Done():
			return false
		}
	}, 2*time.Second, 200*time.Millisecond)
```

**Review by tigrato — APPROVED** [review]

File: lib/authz/permissions_test.go (hunk 1 above)
Comment (r0mant) [reply lib/authz/permissions_test.go]: Good idea, done.
