### PR TITLE
Fixes potential `cgo.Handle` panic

### LINKED ISSUE #13407: desktop access crash
I was able to get Teleport to crash by:

- starting a session to a desktop (Windows Server 2019, if it matters)
- closing the browser tab as the smart card login was occuring

Logs:

```
2022-06-13T08:53:17-06:00 WARN [WEB]       Error proxying a desktop protocol websocket to windows_desktop_service desktop-name:5e44754f8189-static-ec2-54-189-12-111-us-west-2-compute-amazonaws-com error:[
ERROR REPORT:
Original Error: trace.aggregate websocket: close 1001 (going away)
Stack Trace:
	/Users/zmb/teleport/lib/web/desktop.go:331 github.com/gravitational/teleport/lib/web.proxyWebsocketConn
	/Users/zmb/teleport/lib/web/desktop.go:182 github.com/gravitational/teleport/lib/web.(*Handler).createDesktopConnection
	/Users/zmb/teleport/lib/web/desktop.go:61 github.com/gravitational/teleport/lib/web.(*Handler).desktopConnectHandle
	/Users/zmb/teleport/lib/web/apiserver.go:2534 github.com/gravitational/teleport/lib/web.(*Handler).WithClusterAuth.func1
	/Users/zmb/teleport/lib/httplib/httplib.go:68 github.com/gravitational/teleport/lib/httplib.MakeHandlerWithErrorWriter.func1
	/Users/zmb/go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:399 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/net/http/server.go:2127 net/http.StripPrefix.func1
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 net/http.HandlerFunc.ServeHTTP
	/Users/zmb/teleport/lib/web/apiserver.go:454 github.com/gravitational/teleport/lib/web.NewHandler.func1
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/net/http/server.go:2084 net/http.HandlerFunc.ServeHTTP
	/Users/zmb/go/pkg/mod/github.com/gravitational/httprouter@v1.3.1-0.20220408074523-c876c5e705a5/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
	/Users/zmb/teleport/lib/web/apiserver.go:215 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
	/Users/zmb/go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
	/Users/zmb/go/pkg/mod/github.com/gravitational/oxy@v0.0.0-20211213172937-a1ba0900a4c9/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 net/http.serverHandler.ServeHTTP
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 net/http.(*conn).serve
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1263 runtime.goexit
User Message: websocket: close 1001 (going away)] session:4079 user:zac windows-service-addr:mbp13.local:3028 windows-service-uuid:316a3ffa-23e6-4d85-92a1-5e44754f8189 web/desktop.go:183
2022-06-13T08:53:17-06:00 INFO [WINDOWS_D] TDP input streaming finished client-ip:::1 desktop-addr:ec2-54-189-12-111.us-west-2.compute.amazonaws.com:3389 desktop-name:5e44754f8189-static-ec2-54-189-12-111-us-west-2-compute-amazonaws-com rdp-addr:ec2-54-189-12-111.us-west-2.compute.amazonaws.com:3389 rdpclient/client.go:270
2022-06-13T08:53:17-06:00 INFO [WINDOWS_D] RDP output streaming finished client-ip:::1 desktop-addr:ec2-54-189-12-111.us-west-2.compute.amazonaws.com:3389 desktop-name:5e44754f8189-static-ec2-54-189-12-111-us-west-2-compute-amazonaws-com rdp-addr:ec2-54-189-12-111.us-west-2.compute.amazonaws.com:3389 runtime/panic.go:838
panic: runtime/cgo: misuse of an invalid Handle

goroutine 1339 [running]:
runtime/cgo.Handle.Value(...)
	/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/cgo/handle.go:124
github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient.handle_bitmap(0x108baeb20?, 0x140019ce4e0?)
	/Users/zmb/teleport/lib/srv/desktop/rdp/rdpclient/client.go:386 +0x8c
github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient._Cfunc_read_rdp_output(0x600003cb0000)
	_cgo_gotypes.go:251 +0x3c
github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient.(*Client).start.func1.1(0x1400174e550?)
	/Users/zmb/teleport/lib/srv/desktop/rdp/rdpclient/client.go:248 +0x54
github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient.(*Client).start.func1()
	/Users/zmb/teleport/lib/srv/desktop/rdp/rdpclient/client.go:248 +0xdc
created by github.com/gravitational/teleport/lib/srv/desktop/rdp/rdpclient.(*Client).start
	/Users/zmb/teleport/lib/srv/desktop/rdp/rdpclient/client.go:241 +0x80
```

### PR DESCRIPTION
**Pull request by ibeckermayer**
The `rdpclient.Client` in Go has a [`cgo.Handle` field](https://github.com/gravitational/teleport/blob/ad841e0235e308cc3293f03e5a036ece0824f283/lib/srv/desktop/rdp/rdpclient/client.go#L132), which is a [special type cgo provides](https://pkg.go.dev/runtime/cgo?utm_source=gopls#Handle) to deal with on of the idiosyncrasies of working between Go and C:

> Handle provides a way to pass values that contain Go pointers (pointers to memory allocated by Go) between Go and C without breaking the cgo pointer passing rules. A Handle is an integer value that can represent any Go value. A Handle can be passed through C and back to Go, and Go code can use the Handle to retrieve the original Go value.

The underlying object of a `cgo.Handle` can be retrieved by calling `handle.Value()`, like we do in `handle_bitmap`:
https://github.com/gravitational/teleport/blob/ad841e0235e308cc3293f03e5a036ece0824f283/lib/srv/desktop/rdp/rdpclient/client.go#L393-L396

and its memory must be explicitly released after use by calling `handle.Delete()`. Previously, we were calling `handle.Delete()` in `Client.Close()`
https://github.com/gravitational/teleport/blob/8ce4e6bfbf59c9cfa3dfed135c0c44419cf26fad/lib/srv/desktop/rdp/rdpclient/client.go#L445-L456

which was deferred in both the video output streaming goroutine (which calls `handle_bitmap` repeatedly)
https://github.com/gravitational/teleport/blob/8ce4e6bfbf59c9cfa3dfed135c0c44419cf26fad/lib/srv/desktop/rdp/rdpclient/client.go#L239-L245

and in the user input streaming goroutine:
https://github.com/gravitational/teleport/blob/8ce4e6bfbf59c9cfa3dfed135c0c44419cf26fad/lib/srv/desktop/rdp/rdpclient/client.go#L259-L264.

When a user closes a tab like in https://github.com/gravitational/teleport/issues/13407, the input streaming goroutine returns
https://github.com/gravitational/teleport/blob/8ce4e6bfbf59c9cfa3dfed135c0c44419cf26fad/lib/srv/desktop/rdp/rdpclient/client.go#L268-L270

meaning the `defer c.Close()` gets called and calls `c.handle.Delete()`. Therefore, its possible that the video output streaming goroutine continues running for long enough to call `handle_bitmap` again, which attempts to call `c.handle.Value()` on an invalid handle (the one that's been `Delete()`ed), which causes the panic. The _precise_ mechanics of how this happens, and why it happens more often when smartcard negotiation is taking place but not in other circumstances, is not entirely clear to me (though I have the beginnings of a hypothesis). However with these changes, such a scenario is now impossible, and so the panic should never occur.

Closes https://github.com/gravitational/teleport/issues/13407

### CODE REVIEW

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 1]
```diff
@@ -108,17 +108,33 @@ func init() {
 }
 
 // Client is the RDP client.
+// It's lifecycle is:
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:111]:
```suggestion
// Its lifecycle is:
```

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 2]
```diff
@@ -435,23 +449,25 @@ func (c *Client) handleRemoteCopy(data []byte) C.CGOErrCode {
...
+	c.Cleanup()
 }
 
-// Close shuts down the client and closes any existing connections.
-// It is safe to call multiple times, from multiple goroutines.
-// Calls other than the first one are no-ops.
-func (c *Client) Close() {
-	c.closeOnce.Do(func() {
+// Cleanup frees the memory of the cgo.Handle, closes the RDP client connection,
+// and frees the Rust client.
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:458]: This is an exported method, so you should write it from the perspective of an external package calling into the RDP client (meaning internal details like CGo handles and Rust clients should probably not be exposed).

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 3]
```diff
@@ -435,23 +449,25 @@ func (c *Client) handleRemoteCopy(data []byte) C.CGOErrCode {
...
+func (c *Client) Cleanup() {
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:459]: I don't really see the need for the rename from Close to Cleanup. Close is a pretty common name for a Go method that frees up resources, and is already used throughout the codebase.

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 4]
```diff
@@ -435,23 +449,25 @@ func (c *Client) handleRemoteCopy(data []byte) C.CGOErrCode {
...
+	c.cleanupOnce.Do(func() {
+		// Release the memory of the cgo.Handle
 		c.handle.Delete()
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:462]: Shouldn't we move `handle.Delete()` after `C.close_rdp()` to ensure that the Rust code  is done running and won't try to use the handle after we've deleted it?

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 5]
```diff
@@ -108,17 +108,33 @@ func init() {
...
+//
+// ```
+// rdpc := New() // creates client and kicks off RDP connection
+// rdpc.Wait()   // waits for the duration of the connection
+// ```
+//
+// rdpc.Wait() typically takes care of calling rdpc.Cleanup().
+// However, if something fails between the call to New() and
+// rdpc.Wait(), the caller MUST call rdpc.Cleanup() to ensure
+// all memory is released.
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:121]: This is a confusing API and I would like to avoid it.

How is someone supposed to know if "something fails between New() and Wait()" anyway?

Is there some way we could perhaps:
- unexport `cleanup()`
- make it a required convention to always call `Wait()` after new, to ensure cleanup happens
- make `Wait()` just perform cleanup and return immediately if something failed with `New`

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 6]
```diff
@@ -108,17 +108,33 @@ func init() {
...
-	// handle allows the rust code to call back into the client
+	// handle allows the rust code to call back into the client.
+	// Once it is created with cgo.NewHandle(), the original caller
+	// MUST release it with a call to handle.Delete().
 	handle cgo.Handle
 
 	// RDP client on the Rust side.
+	// Once it is created by assigning this field to the result of C.connect_rdp(),
+	// the caller SHOULD end the RDP connection by passing it to C.close_rdp(),
+	// and the caller MUST free its memory by passing it to C.free_rdp().
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:137]: These comments are so detailed that they are both:

- hard for someone not familiar with the internal details to understand, and
- easy to go out of date in the future

Can we get rid of them?

**Review by zmb3 — CHANGES_REQUESTED** [review]
Looks like you've definitely tracked down the source of the issue, but I'd like to clean up the solution a bit.

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 7]
```diff
@@ -128,8 +134,8 @@ type Client struct {
 
 	// wg is used to wait for the input/output streaming
 	// goroutines to complete
-	wg        sync.WaitGroup
-	closeOnce sync.Once
+	wg          sync.WaitGroup
+	cleanupOnce sync.Once
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:138]: Restore this to `closeOnce`

**Review by zmb3 — APPROVED** [review]
Looks much better. A few nits but otherwise LGTM.

File: lib/srv/desktop/windows_server.go [hunk 8]
```diff
@@ -871,17 +871,21 @@ func (s *WindowsService) connectRDP(ctx context.Context, log logrus.FieldLogger,
 		monitorCfg.DisconnectExpiredCert = identity.Expires
 	}
 
+	// UpdateClientActivity before starting monitor to
+	// be doubly sure that the client isn't disconnected
+	// due to an idle timeout before its had the chance to
+	// call StartAndWait()
```
Comment (zmb3) [inline lib/srv/desktop/windows_server.go:877]:
```suggestion
	// call Run()
```

**Review by jakule — APPROVED** [review]

**Comment by zmb3** [comment]
@ibeckermayer don't forget to open backports :-)

**Comment by ibeckermayer** [comment]
v9 backport fixed: https://github.com/gravitational/teleport/pull/13590
