### PR TITLE
Fix AWS CLI access using AWS OIDC integration

### LINKED ISSUE #57831: tsh app login fails with a AWS OIDC integration
Expected behavior:
- tsh login <proxy>
- tsh app login <app> --aws-role <role> should work with an AWS OIDC integration app

Current behavior:
```bash
$ tsh apps login teleport-dev-2 --aws-role gavin-tf-permission-tester
ERROR: application "teleport-dev-2" is using integration "teleport-dev-2" for access, which does not support AWS credential generation
```

Bug details:
- Teleport version: 18.1.1
- tsh version: 18.1.1

This bug was introduced in https://github.com/gravitational/teleport/pull/56075 which was backported and released in 18.0.2

integration spec:
```bash
$ tctl get integration/teleport-dev-2
kind: integration
metadata:
  name: teleport-dev-2
  revision: 5756783e-dc16-401d-b94b-a67fffb6d81f
spec:
  aws_oidc:
    role_arn: arn:aws:iam::*redacted*:role/gavin-tf-gavin-leaf-cloud-gravitational-io
  aws_ra:
    profile_sync_config: null
  azure_oidc: {}
  github: {}
status: {}
sub_kind: aws-oidc
version: v1
```

app spec:
```bash
$ tctl get app_server/teleport-dev-2
kind: app_server
metadata:
  name: teleport-dev-2
  revision: e4dd8a93-10ff-41b0-ad1b-26dad2a29d17
spec:
  app:
    kind: app
    metadata:
      name: teleport-dev-2
    spec:
      cloud: AWS
      insecure_skip_verify: false
      integration: teleport-dev-2
      public_addr: teleport-dev-2.gavin-leaf.cloud.gravitational.io:443
      uri: https://console.aws.amazon.com
    version: v3
  host_id: b6915079-2112-42ea-ab94-3ad843faa52f
  hostname: ""
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 16.4.8
version: v3
```

### PR DESCRIPTION
**Pull request by marcoandredinis**
Fixes https://github.com/gravitational/teleport/issues/57831

changelog: Fix AWS CLI access using AWS OIDC integration

### CODE REVIEW

File: lib/auth/auth_with_roles_test.go [hunk 1]
```diff
@@ -867,6 +867,56 @@ func TestAWSRolesAnywhereCredentialGenerationForApps(t *testing.T) {
 
 	require.Equal(t, roleARN, identity.AWSRoleARNs[0], "Expected AWS Role ARN to match the one requested")
 	require.JSONEq(t, `{"Version":1,"AccessKeyId":"aki","SecretAccessKey":"sak","SessionToken":"st","Expiration":"2025-06-25T12:07:02.474135Z"}`, identity.RouteToApp.AWSCredentialProcessCredentials)
+
+	t.Run("app using aws oidc integration does not fail", func(t *testing.T) {
```
Comment (zmb3) [inline lib/auth/auth_with_roles_test.go]: It's a little bit odd to me to have a test that is both a standalone test but also contains a single subtest.

Subtests are well suited towards table tests when you have some common setup and then a series of test scenarios.

This code almost looks like a completely independent test to me.

Comment (marcoandredinis) [reply lib/auth/auth_with_roles_test.go]: Totally agreed, it was an oversight.

Created a specific test for this test case.

**Review by zmb3 — APPROVED** [review]

File: lib/auth/auth.go [hunk 2]
```diff
@@ -3565,10 +3565,10 @@ func generateCert(ctx context.Context, a *Server, req certRequest, caType types.
...
-	// Generate AWS credential process credentials if the user is trying to access an App with an AWS Roles Anywhere Integration.
-	awsCredentialProcessCredentials, err := generateAWSConfigCredentialProcessCredentials(ctx, a, req, notAfter)
+	// Generate AWS client side credentials if the user is trying to access an AWS App with an AWS Roles Anywhere Integration.
+	awsCredentialProcessCredentials, err := generateAWSClientSideCredentials(ctx, a, req, notAfter)
 	switch {
-	case errors.Is(err, errNotIntegrationApp):
+	case errors.Is(err, errAppWithoutAWSClientSideCredentials):
 	case err != nil:
 		return nil, trace.Wrap(err)
 	}
```
Comment (r0mant) [inline lib/auth/auth.go:3574]: I think that trying to determine whether to generate credentials or not based on the returned error is very awkward and error-prone (and not very Go idiomatic) - which is why I suspect we got this regression in the first place.

Can this be done by doing explicit checks on the integration type and request instead of doing this opportunistically based on the error?

Comment (marcoandredinis) [reply lib/auth/auth.go:3574]: Integration type is explicitly checked.
The request is not checked because it is un-changed from regular AWS App access, the client does not explicitly ask for client side credentials.

I can add other sentinel errors, and check all of them here.
```go
	// Generate AWS client side credentials if the user is trying to access an AWS App with an AWS Roles Anywhere Integration.
	awsCredentialProcessCredentials, err := generateAWSClientSideCredentials(ctx, a, req, notAfter)
	switch {
	case errors.Is(err, errNotAWSAccessApp) || errors.Is(err, errAWSAppWithoutIntegration) || errors.Is(err, errProxiedAWSApp):
	case err != nil:
		return nil, trace.Wrap(err)
	}
```
I'm not convinced by this, it adds a list of errors which can become an oversight later on.
On 2nd thought, maybe this is not what you meant.

I don't think moving the logic from the function to here is a good approach as it would add quite a lot of code to an already large method.

Comment (GavinFrazar) [reply lib/auth/auth.go:3574]: i'm not strongly opposed to leaving it as-is, but you could refactor this to just return nil in cases where you would return the `errAppWithoutAWSClientSideCredentials`?

It seems like the graceful error handling behavior just ignores the error anyway and allowing for empty credentials is the expected behavior, so `return "", nil` makes sense to me.

I'm not convinced the error handling scheme had anything to do with the bug though. We just forgot to check for the AWS OIDC subkind, and for other subkinds it makes sense to return an error e.g. it should be an error to request an --aws-role with an Azure OIDC integration subkind.

**Review by GavinFrazar — APPROVED** [review]

File: lib/auth/auth.go (hunk 2 above)
Comment (GavinFrazar) [reply lib/auth/auth.go:3574]: imo we should have an exported list of integration subkinds and then table test against that.
That way if a subkind is added in the future that supports aws client side credentials, the tests will force us to update the switch statement to account for it

**Review by r0mant — APPROVED** [review]

File: lib/auth/auth.go (hunk 2 above)
Comment (marcoandredinis) [reply lib/auth/auth.go:3574]: > so return "", nil makes sense to me.

(when I first implemented, it was like that before code review 😅)

As for adding all the integration subkinds to table test them, maybe that's a good idea.
For now, their features barely intercept, so that's why it wasn't an issue in the past.
