### PR TITLE
Fix `TestKubernetesLicenseEnforcement` data race

### LINKED ISSUE #25357: `TestKubernetesLicenseEnforcement ` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4834472626/jobs/8615732335

#### Relevant snippet

```
===================================================
OUTPUT github.com/gravitational/teleport/lib/kube/proxy.TestKubernetesLicenseEnforcement/kubernetes_agent_is_licensed
===================================================
make: *** [test-go-unit] Error 1
=== RUN   TestKubernetesLicenseEnforcement/kubernetes_agent_is_licensed
=== PAUSE TestKubernetesLicenseEnforcement/kubernetes_agent_is_licensed
=== CONT  TestKubernetesLicenseEnforcement/kubernetes_agent_is_licensed
{"caller":"proxy/auth.go:140","cluster":"foo","component":null,"level":"debug","message":"Checking Kubernetes impersonation permissions.","timestamp":"2023-04-28T20:28:35Z"}
{"caller":"proxy/auth.go:140","cluster":"teleport-cluster","component":null,"level":"debug","message":"Checking Kubernetes impersonation permissions.","timestamp":"2023-04-28T20:28:35Z"}
{"caller":"proxy/auth.go:140","cluster":"baz","component":null,"level":"debug","message":"Checking Kubernetes impersonation permissions.","timestamp":"2023-04-28T20:28:35Z"}
{"caller":"proxy/auth.go:151","cluster":"teleport-cluster","component":null,"level":"debug","message":"Have all necessary Kubernetes impersonation permissions.","timestamp":"2023-04-28T20:28:35Z"}
{"caller":"proxy/auth.go:176","cluster":"teleport-cluster","component":null,"level":"debug","message":"Initialized Kubernetes credentials","timestamp":"2023-04-28T20:28:35Z"}
{"caller":"proxy/auth.go:73","component":null,"kubeClusterName":"","kubeconfigPath":"/tmp/TestGetKubeCreds4273838333/001/kubeconfig","level":"debug","message":"Reading Kubernetes details.","serviceType":"kube_proxy","timestamp":"2023-04-28T20:28:35Z"}
    testing.go:1446: race detected during execution of test
--- FAIL: TestKubernetesLicenseEnforcement/kubernetes_agent_is_licensed (0.92s)
time="2023-04-28T20:28:36Z" level=warning msg="Mux serve failed." error="listener is closed\n\taccept tcp 127.0.0.1:43395: use of closed network connection" trace.component=auth
time="2023-04-28T20:28:36Z" level=warning msg="Mux serve failed." error="listener is closed\n\taccept tcp 127.0.0.1:46393: use of closed network connection" trace.component=auth
===================================================
OUTPUT github.com/gravitational/teleport/lib/kube/proxy.TestKubernetesLicenseEnforcement/kubernetes_isn't_licensed
===================================================
=== RUN   TestKubernetesLicenseEnforcement/kubernetes_isn't_licensed
=== PAUSE TestKubernetesLicenseEnforcement/kubernetes_isn't_licensed
{"caller":"proxy/auth.go:73","component":null,"kubeClusterName":"","kubeconfigPath":"/tmp/TestGetKubeCreds4273838333/001/kubeconfig","level":"debug","message":"Reading Kubernetes details.","serviceType":"kube_service","timestamp":"2023-04-28T20:28:35Z"}
=== CONT  TestKubernetesLicenseEnforcement/kubernetes_isn't_licensed
{"caller":"proxy/auth.go:73","component":null,"kubeClusterName":"","kubeconfigPath":"","level":"debug","message":"Reading Kubernetes details.","serviceType":"kube_proxy","timestamp":"2023-04-28T20:28:35Z"}
    testing.go:1446: race detected during execution of test
--- FAIL: TestKubernetesLicenseEnforcement/kubernetes_isn't_licensed (0.92s)
```

### PR DESCRIPTION
**Pull request by tigrato**
When `TestKubernetesLicenseEnforcement`'s parallel tests run, they inherit the  `err` var from the main function and tried to write the result into it without any protection which results in a data race.

The PR allocates the `err` var locally to the closure in order to prevent the data race. (It was a typo)

Fixes #25357

### CODE REVIEW

File: lib/kube/proxy/utils_testing.go [hunk 1]
```diff
@@ -223,7 +223,12 @@ func SetupTestContext(ctx context.Context, t *testing.T, cfg TestConfig) *TestCo
 		// this is used to make sure that heartbeat started and the clusters
 		// are registered in the auth server
 		OnHeartbeat: func(err error) {
-			require.NoError(t, err)
+			// ignore not found errors because although the heartbeat is called before
+			// the close does not wait for the resource cleanup to finish.
+			if trace.IsNotFound(err) {
+				return
```
Comment (camscale) [inline lib/kube/proxy/utils_testing.go:229]: It looks like there may be cases where this causes the test runner to hang, as when this heartbeat function is called, it does not trigger a test error and it does not put a value on the `heartbeatsWaitChannel` channel, so the code below that is waiting for all the heartbeats will miss one and block forever. This is assuming that there is only one heartbeat per cluster - which seems a little odd, as I would not expect this to be 1:1 - but I haven't seen this part of the code before now.

Comment (tigrato) [reply lib/kube/proxy/utils_testing.go]: You are correct but I don't think that would be a big issue since you cannot start the test without valid clusters 
Fixed it anw in [5986926](https://github.com/gravitational/teleport/pull/25441/commits/5986926072cacb483caec9120a0c32303a878525)

Comment (camscale) [reply lib/kube/proxy/utils_testing.go]: I see now I misunderstood the structure of the test. I didn't realise this was all in the startup phase so the waiting was waiting for a single heartbeat from each cluster before continuing with the tests. It is only after that the error you are handling in this PR is generated - I'm happy for you to drop that extra commit if you like - I'm not sure it is needed and now makes the test setup a little more complicated than needed. Up to you.

**Review by camscale — APPROVED** [review]
LGTM - I've unresolved my previous comment as I replied there.

File: lib/kube/proxy/utils_testing.go (hunk 1 above)
Comment (tigrato) [reply lib/kube/proxy/utils_testing.go]: I will leave the last commit as it is since the check is strong. Thanks!

**Review by r0mant — APPROVED** [review]
