### PR TITLE
Track and sync modifier states

### LINKED ISSUE #54725: Windows RDP SHIFT+CMD/WINDOWS key stickness
Expected behavior:

SHIFT+CMD/Windows key combination should not remain sticky after being pressed unless explicitly mapped to do so by the user.

Current behavior:

In certain situations, using SHIFT key along with other keys (e.g., WINDOWS or CMD) causes the keys to remain sticky until the user clicks the key combo again to reset it.

Bug details:
- Teleport version: first observed by customer on 17.2.7 but confirmed on the latest available 17.4.6 as well
- Recreation steps:
1. Open Teleport RDP session and notepad (or any task/program)
2. Hold down SHIFT+CMD+5 (or SHIFT+WINDOWS+5) to take a screenshot.
4. After taking the screenshot, click the direction arrows (up/down/left/right).

If the bug has manifested, you will see the task/program windows moving around and SHIFT will appear to be locked (e.g, manifests in caps-lock behavior unexpectedly), indicating that the keys have become sticky. Hitting the key combo again a few times resets the behavior. 

- Debug logs:

n/a (no relevant logs appear in the teleport_windows_service agent logs)

### PR DESCRIPTION
**Pull request by danielashare**
We're seeing issues where keys are getting stuck on remote desktop sessions when users use host OS shortcuts, most commonly Cmd+Shift+[3|4|5] to take a screenshot on MacOS. This is happening because when MacOS takes focus away from the browser, it doesn't send any key up events. The browser also doesn't detect focus out or blur events.

To fix this, I track the remote state of modifier keys in the `InputHandler`. When a key is pressed, the local modifiers are compared to the remote modifiers. If there's a difference in state, the remote modifiers are updated before sending the original key.

Closes: #54725, #53075

changelog: Prevent modifier keys from getting stuck during remote desktop sessions

### CODE REVIEW

File: web/packages/shared/components/DesktopSession/InputHandler.tsx
Comment (ravicious) [inline web/packages/shared/components/DesktopSession/InputHandler.tsx:1]: Is there any sort of test we can add for this new behavior?

Comment (ravicious) [inline web/packages/shared/components/DesktopSession/InputHandler.tsx:1]: I found a very niche way of reproducing the error, but this happens only because I have my Caps Lock set with Karabiner to send Command+Control+Option+Shift at the same time. 😏 It's niche enough that we probably don't have to worry about it, but I just wanted to let you know about this.

https://github.com/user-attachments/assets/42de72b6-f730-4295-a38f-8e151a5b2d43

Comment (ravicious) [inline web/packages/shared/components/DesktopSession/InputHandler.tsx:1]: It works just fine in the Web UI, however I'm still able to reproduce it in Connect by pressing the screenshot shortcut while some files in Explorer are selected. I suspect there might be some differences as to how Electron handles key events? Was this PR meant to fix this in Connect too?

Comment (danielashare) [reply web/packages/shared/components/DesktopSession/InputHandler.tsx:1]: Good idea, that caught a bug. `synchronizeModiferState` shouldn't handle modifier keys because `shiftDownEvent.getModifierState("Shift")` returns false 🙃

Comment (danielashare) [reply web/packages/shared/components/DesktopSession/InputHandler.tsx:1]: The problem is that I'm only checking for stuck keys on keyboard events, not mouse events. I did notice this before, but thought that it would generate lot more modifier checks. But, thinking about it some more, there are likely a lot more keyboard events than there are mouse events, so there won't be that many more checks, comparatively. Also, stuck keys paired with mouse events is equally as disruptive, as you've shown. Scroll events with a stuck Control key would also be very annoying in browsers etc. I'll add modifier checks to mouse events.

Comment (danielashare) [reply web/packages/shared/components/DesktopSession/InputHandler.tsx:1]: This is meant to fix Connect too. I think this is fixed with the changes I made for your previous comment, if I'm understanding correctly. Would you mind double checking? 🙂

File: web/packages/shared/components/DesktopSession/InputHandler.tsx [hunk 1]
```diff
@@ -118,6 +134,77 @@ export class InputHandler {
...
+  private isModifierKey(key: string): boolean {
+    return ['Shift', 'Control', 'Alt', 'Meta'].some(modifier =>
+      key.startsWith(modifier)
+    );
+  }
+
+  /**
+   * Synchronizes the local modifier state with the remote machine.
+   * This is called when a key event occurs to ensure that the remote machine
+   * has the correct state of modifier keys. If not, it sends the current state.
```
Comment (ravicious) [inline web/packages/shared/components/DesktopSession/InputHandler.tsx]: The comment needs to be updated since it's no longer called only on a key event.

**Review by ravicious — APPROVED** [review]
Yup, it works correctly now!

**Review by kiosion — APPROVED** [review]
