### PR TITLE
Verify if proxy can handle application requests when creating session

### LINKED ISSUE #10519: app access: redirect loop
### Description

**What happened**:

When attempting to access an app, the browser entered a redirect loop that would continuously fail on the `POST /x-teleport-auth` call, and eventually fails with a 403.

The browser console shows:

```
Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.
https://APP.TENANT.cloud.gravitational.io/x-teleport-auth
```

The proxy/auth logs showed:

```
"{\"caller\":\"app/handler.go:179\",\"component\":\"app:web\",\"level\":\"warning\",\"message\":\"Failed to get session: failed to match applications.\",\"timestamp\":\"2022-02-22T19:24:50Z\"}\n"
```
It appears that this started happening after proxy/auth were upgraded.

A restart of the Teleport instance running the app service resolved the issue, so it's possible that app service gets into a bad state if it loses connection to auth.

### Server Details
- Teleport version (run `teleport version`): 8.3.1
- Server OS (e.g. from `/etc/os-release`): Debian Bullseye (app service)
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Teleport Cloud

### PR DESCRIPTION
**Pull request by gabrielcorado**
Closes #10519.

When a create app session is made from the WebUI, the endpoint will check if the proxy can handle application requests. This flow is the same as when directly making requests to the application's public address, the difference is that it is performed earlier, and we can show an error on the Web UI.

With these changes, when the proxy cannot handle the (e.g., due to application services not being available), it will return to the launch route (web UI) and show an error instead of getting into an infinity redirect loop (as described in the issue).

For the CLI flow, the proxy will return an error when it can't handle the requests instead of redirecting to the launch route (which wouldn't have any effect when using certificates).

## Before
Screen Recording 2023-01-19 at 12 11 06

## After
Screen Recording 2023-01-19 at 12 07 21

### CODE REVIEW

File: lib/web/app/handler.go [hunk 1]
```diff
@@ -257,6 +257,30 @@ func (h *Handler) HandleConnection(ctx context.Context, clientConn net.Conn) err
...
+	clusterClient, err := h.c.ProxyClient.GetSite(identity.RouteToApp.ClusterName)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	accessPoint, err := clusterClient.CachingAccessPoint()
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	// At least on AppServer needs to be present to serve the requests. Using
```
Comment (ravicious) [inline lib/web/app/handler.go:273]:
```suggestion
	// At least one AppServer needs to be present to serve the requests. Using
```

File: lib/web/app/session.go [hunk 2]
```diff
@@ -126,6 +117,23 @@ func (h *Handler) newSession(ctx context.Context, ws types.WebSession) (*session
 	}, nil
 }
 
+// appServerMatcher returns a Matcher function used to find which AppServer can
+// handle the application requests.
+func appServerMatcher(proxyClient reversetunnel.Tunnel, identity *tlsca.Identity) Matcher {
+	// Match(ctx, accessPoint,
```
Comment (ravicious) [inline lib/web/app/session.go:123]: It seems that this is a leftover comment, no?

File: lib/web/apps.go [hunk 3]
```diff
@@ -77,14 +77,22 @@ func (h *Handler) clusterAppsGet(w http.ResponseWriter, r *http.Request, p httpr
...
 	// FQDN is application FQDN.
 	FQDN string `json:"fqdn"`
 }
 
-type CreateAppSessionRequest resolveAppParams
+// CreateAppSessionRequest respresents the payload present when creating
+// application sessions.
+type CreateAppSessionRequest struct {
+	ResolveAppParams
+	// PreflightConnection when set the proxy preflight a connection to an
```
Comment (ravicious) [inline lib/web/apps.go:91]:
```suggestion
	// PreflightConnection when set the proxy preflights a connection to an
```

File: lib/web/apps.go [hunk 4]
```diff
@@ -196,6 +204,22 @@ func (h *Handler) createAppSession(w http.ResponseWriter, r *http.Request, p htt
...
+		err := h.preflightAppConnection(r.Context(), identity)
+		if err != nil {
+			deleteSessionErr := authClient.DeleteAppSession(r.Context(), types.DeleteAppSessionRequest{
+				SessionID: ws.GetName(),
+			})
+			if deleteSessionErr != nil {
+				h.log.WithError(err).Error("Failed to delete app session")
+			}
+
+			return nil, trace.ConnectionProblem(err, "Unable to serve application requests. Please try requesting again. If the issue persists, verify if the Application Services are connected to Teleport.")
```
Comment (ravicious) [inline lib/web/apps.go:219]: What about changing "Please try requesting again" to "Please try again"? I feel like "requesting" without an object doesn't tell the user what exactly they should try requesting again.

File: lib/web/apiserver.go [hunk 5]
```diff
@@ -229,6 +235,10 @@ type Config struct {
 
 	// TracerProvider generates tracers to create spans with
 	TracerProvider oteltrace.TracerProvider
+
+	// ServeAppChecker is a function that checks if the proxy can handle
+	// application requests.
+	ServeAppChecker preflightAppConnectionFunc
```
Comment (ravicious) [inline lib/web/apiserver.go:241]: Couldn't this field also be named `PreflightAppConnection`? The name `ServeAppChecker` is used exclusively here and I don't understand what's special about this struct that warrants a different field name. 🤔

**Review by ravicious — COMMENTED** [review]
I'm not familiar with app access so this is a rather superficial review.

How can I test this change? Is there a specific `app_service` config I can use or do I need to set up an agent for that?

File: lib/web/apps.go [hunk 6]
```diff
@@ -77,14 +77,22 @@ func (h *Handler) clusterAppsGet(w http.ResponseWriter, r *http.Request, p httpr
...
 
-type CreateAppSessionRequest resolveAppParams
+// CreateAppSessionRequest respresents the payload present when creating
+// application sessions.
+type CreateAppSessionRequest struct {
+	ResolveAppParams
+	// PreflightConnection when set the proxy preflight a connection to an
+	// AppServer, ensuring it can handle the request. If the preflight fails,
+	// the session is not created and it returns an error.
+	PreflightConnection bool `json:"preflight_connection"`
```
Comment (smallinsky) [inline lib/web/apps.go:94]: Wo we need a additional flag for that ? Can we use the caller by   PeerCert and check if the call was done via WebUI or tsh app access ?

File: lib/web/app/handler.go [hunk 7]
```diff
@@ -257,6 +257,30 @@ func (h *Handler) HandleConnection(ctx context.Context, clientConn net.Conn) err
 	return nil
 }
 
+// PreflightConnection establishes a connection to a AppServer that can handle
+// application requests. Can be used to ensure the proxy can handle application
+// requests before they arrive.
+func (h *Handler) PreflightConnection(ctx context.Context, identity *tlsca.Identity) error {
```
Comment (smallinsky) [inline lib/web/app/handler.go:263]: Can we rename it to more meaningful like `checkIfAppIsAccesable` ?  At first glance the `PreflightConnection` is quite enigmatic and without reading the comment hard to grasp what it does.

File: lib/web/apps.go (hunk 6 above)
Comment (gabrielcorado) [reply lib/web/apps.go:94]: Yes, we could rely on the requested certificate. However, since it is an API endpoint, my thought is that having this behavior set explicitly is better than assuming it based on caller characteristics. Rather than that, I don't mind changing it to be the default behavior for non-certificate requests.

**Comment by gabrielcorado** [comment]
> How can I test this change? Is there a specific app_service config I can use or do I need to set up an agent for that?

@ravicious To reproduce this issue, you'll need to make an application request that doesn't have any app service online to serve it. I've done the following:
* Start Teleport instance without app service enabled;
* Start a Teleport app service instance with an application registered (could be on config or dynamic registration), and let it register itself and the application;
* Stop the app service;
* Launch the application from the WebUI or make a request using the CLI. Due to the cache, the application will still be present on the Teleport cluster. However, after a period, it will no longer be available.

File: lib/web/app/handler.go (hunk 7 above)
Comment (gabrielcorado) [reply lib/web/app/handler.go:263]: Do you mean renaming all occurrences of "preflight connection" or just this one?

Comment (smallinsky) [reply lib/web/app/handler.go:263]: Yes I was thinking about renaming it because  as far I understand the `Preflight" mostly referee to HTTP preflight request: 

> A preflight request is a small request that is sent by the browser before the actual request. It contains information like which HTTP method is used, as well as if any custom HTTP headers are present. The preflight gives the server a chance to examine what the actual request will look like before it’s made.

and here we are just doing the tcp health check in order to check if any app agent is available. 

but I don't have strong opinion about it.

File: lib/web/apps.go [hunk 8]
```diff
@@ -196,6 +204,22 @@ func (h *Handler) createAppSession(w http.ResponseWriter, r *http.Request, p htt
 		return nil, trace.Wrap(err)
 	}
 
+	// Ensuring proxy can handle the connection is an optional step.
+	if h.preflightAppConnection != nil && req.PreflightConnection {
```
Comment (smallinsky) [inline lib/web/apps.go:208]: can we trigger the preflight request before app session is created so the `DeleteAppSession` call won't be needed ?

File: lib/web/app/middleware.go [hunk 9]
```diff
@@ -64,6 +64,12 @@ func (h *Handler) withAuth(handler handlerAuthFunc) http.HandlerFunc {
 // redirectToLauncher redirects to the proxy web's app launcher if the public
 // address of the proxy is set.
 func (h *Handler) redirectToLauncher(w http.ResponseWriter, r *http.Request, p launcherURLParams) error {
+	// When handling requests with certificate, redirecting to launcher won't
```
Comment (smallinsky) [inline lib/web/app/middleware.go:67]: Could you extend the command and explain when this scenario happens ?

**Review by smallinsky — COMMENTED** [review]
Mostly LGTM. I have left some nit comments/suggestions

One open questions is: Do we want to use `preflight_connection` param send by frontend or just relay on HasCert method. Personally I would inclined to using HasCert since it is already used in severals places to check if flow originates from CLI or Web UI like in https://github.com/gravitational/teleport/blob/5e0dc8c4c0ad22d38eb6a55d389c262fdf391725/lib/web/app/handler.go#L369







@mdwn Could you also take a look at this PR ?

File: lib/web/app/middleware.go (hunk 9 above)
Comment (gabrielcorado) [reply lib/web/app/middleware.go]: I've changed the comment and the redirect rule to clarify it.

**Review by mdwn — APPROVED** [review]

File: lib/web/apps.go (hunk 6 above)
Comment (gabrielcorado) [reply lib/web/apps.go]: We cannot use the `HasClientCert` and `HasSession` functions because they rely on application session credentials, which are not present here. They become available only after the application launcher is executed on the WebUI or after this API endpoint is called on the CLI.

**Review by smallinsky — APPROVED** [review]
