### PR TITLE
Fix missing shadow of resource cards in Connect

### LINKED ISSUE #48065: The resource card in Connect lacks a shadow when hovered
In Connect there is no shadow:
Image

Web UI works fine:
Image

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/48065

Since the Electron 33.x update, the hover shadow stopped appearing in unified resources in Connect. At first I thought that something changed in Chromium but both the Web UI and storybook looked fine in Chrome. This led me to think that it's a bug in Electron itself. 
However, I was not able to reproduce the issue in Electron Fiddle. I decided to check the story for unified resources one more time in Chrome, and surprise, there was no shadow. I realized that when I checked it for the first time, I opened the "shared" story, not the Connect's one (where unified resources are wrapped in `Document`).

After testing, I fixed the issue by removing the background from `Document`. It seems that Chromium v130 (or 129) changed how it renders stacking contexts, causing the shadow (with `z-index: -1`) to be rendered below `Document`, making it invisible. 
On a side note, the story looked fine in both Safari and Firefox, so I guess it's a bug in Chromium.

Alternatively, we could fix this by setting `z-index: 0` on the unified resources container. However, the background in `Document` is unnecessary (it’s already set on `TabHost`) so I removed it.

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

File: web/packages/teleterm/src/ui/Document/Document.tsx [hunk 1]
```diff
@@ -34,7 +34,6 @@ const Document: React.FC<{
       tabIndex={visible ? 0 : -1}
       flex="1"
       ref={ref}
-      bg="levels.sunken"
```
Comment (ravicious) [inline web/packages/teleterm/src/ui/Document/Document.tsx:37]: > However, the background in `Document` is unnecessary (it’s already set on `TabHost`) so I removed it.

Where exactly is it set?

Comment (gzdunek) [reply web/packages/teleterm/src/ui/Document/Document.tsx:37]: Ah sorry, we set it on `body`. But I think it's still fine?

Comment (ravicious) [reply web/packages/teleterm/src/ui/Document/Document.tsx:37]: Yeah, it should be fine. I just wanted to have a confirmation since I didn't see it in `TabHost`. For posterity: https://github.com/gravitational/teleport/blob/965c98d29c5c357dd536b020adccfff189c0a487/web/packages/teleterm/src/ui/ThemeProvider/globals.ts#L31

Maybe leave a comment saying that the background-color of `Document` is controlled through `<body>` and that it cannot be set on `Document` directly because of Chromium issues? We could link to this PR as well.

**Review by ravicious — APPROVED** [review]

File: web/packages/teleterm/src/ui/Document/Document.tsx (hunk 1 above)
Comment (ravicious) [reply web/packages/teleterm/src/ui/Document/Document.tsx:37]: It's not only fine but should be straight up better, I think we should generally avoid setting bg color where it's not necessary.
