### PR TITLE
Fix max_duration when session TTL is short

### LINKED ISSUE #32355: Short TTL shows empty `max_duration` in WebUI
Short access request TTL when creating an access request, displays an empty field.

image

### PR DESCRIPTION
**Pull request by jakule**
Fixes https://github.com/gravitational/teleport/issues/32355

### CODE REVIEW

File: web/packages/teleport/src/AccessRequests/service.ts [hunk 1]
```diff
@@ -83,10 +83,12 @@ export async function getDurationOptions(
...
 
-  return middleValues(accessRequest.sessionTTL, accessRequest.maxDuration).map(
-    duration => ({
-      value: duration.timestamp,
-      label: formatDuration(duration.duration),
-    })
-  );
+  return middleValues(
+    accessRequest.created,
+    accessRequest.sessionTTL,
```
Comment (zmb3) [inline web/packages/teleport/src/AccessRequests/service.ts:88]: I don't personally care, but our typescript naming conventions are a bit different than Go. This would typically be named `sessionTtl` in this part of the codebase.

File: web/packages/teleport/src/AccessRequests/utils.test.ts [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+        {
+          days: 6,
+          hours: 0,
+          minutes: 0,
+        },
+      ],
+    },
+  ];
+
+  for (let tc of cases) {
```
Comment (zmb3) [inline web/packages/teleport/src/AccessRequests/utils.test.ts:182]: The proper way to do this with Jest would be a `describe.each` block (similar to Go subtests): https://jestjs.io/docs/api#describeeachtablename-fn-timeout

**Review by zmb3 — APPROVED** [review]

File: web/packages/teleport/src/AccessRequests/utils.ts [hunk 3]
```diff
@@ -22,55 +22,55 @@ import {
...
+  const getInterval = (d: Date) =>
+    intervalToDuration({
+      start: created,
+      end: d,
+    });
 
   const points: Date[] = [start];
 
-  if (isAfter(addDays(start, 1), end)) {
+  if (isAfter(addDays(created, 1), end)) {
```
Comment (kimlisa) [inline web/packages/teleport/src/AccessRequests/utils.ts:53]: can we add a test for this case too? if i understand correctly, this will only produce one option and not sure i saw it on the test

**Review by kimlisa — APPROVED** [review]

File: web/packages/teleport/src/AccessRequests/utils.test.ts (hunk 2 above)
Comment (jakule) [reply web/packages/teleport/src/AccessRequests/utils.test.ts:182]: I've tried to use it, but I had some issues. I'll try again tho 😅
