### PR TITLE
teleport: Add more context to auth server connection failed errors

### LINKED ISSUE #13178: Improve confusing error message
If user misconfigures certs on their proxy, and uses IOT mode, they get error that looks like this:

"Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.\n\tGet \"https://teleport.cluster.local/v2/domain\": x509: certificate is valid for [teleport.example.com](http://teleport.example.com, not 15312345135123531253125123531252315312513253125.teleport.cluster.local, Get \"https://teleport.cluster.local/v2/domain\": dial tcp 1.2.3.4:3024: connect: connection refused." service/connect.go:86

Instead, we should explain what is going on and how to fix it:

Node failed to establish connection to Teleport Proxy. We have tried the following endpoints:

* `teleport.example.com:443` - TLS certificate error. Certificate is invalid or not trusted. Fix the certificate to correct this error: [link to docs]
* `1.2.3.4:3024` - Connection refused. This is the alternative port we tried and it's not configured.

### PR DESCRIPTION
**Pull request by EdwardDowling**
closes 13178
example of new logs with more user friendly context
```
2022-07-04T15:16:30+01:00 ERRO [PROC:1]    Node failed to establish connection to Teleport Proxy. We have tried the following endpoints: pid:321089.1 service/connect.go:1067
2022-07-04T15:16:30+01:00 ERRO [PROC:1]    "- connecting to auth server directly: TLS certificate error. Certificate is invalid or not trusted. Fix the certificate to correct this error: https://goteleport.com/docs/architecture/authentication/\n\tconnection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for localhost, not 74656c65706f72742d6f6e65.teleport.cluster.local\"" pid:321089.1 service/connect.go:1073
2022-07-04T15:16:30+01:00 ERRO [PROC:1]    "- connecting to auth server through tunnel: This is the alternative port we tried and it's not configured.\n\tconnection error: desc = \"transport: Error while dialing failed to dial: dial tcp 127.0.0.1:3024: connect: connection refused\"" pid:321089.1 service/connect.go:1077
```

### CODE REVIEW

**Review by lxea — APPROVED** [review]

File: lib/service/connect.go [hunk 1]
```diff
@@ -1066,8 +1064,17 @@ func (process *TeleportProcess) newClient(authServers []utils.NetAddr, identity
...
-		logger.WithError(err).Debug("Failed to connect to Auth Server through tunnel.")
+		process.log.Errorf("Node failed to establish connection to Teleport Proxy. We have tried the following endpoints:")
+		// Can't errors.As directErr in the "x509: certificate is valid for x but not y" error case, as only message field is set
+		if trace.IsConnectionProblem(directErr) && strings.Contains(directErr.Error(), "x509: certificate is valid for") {
+			directErr = trace.Wrap(directErr, "TLS certificate error. Certificate is invalid or not trusted. "+
+				"Fix the certificate to correct this error: https://goteleport.com/docs/architecture/authentication/")
+		}
+		process.log.Errorf("- connecting to auth server directly: %v", directErr)
+		if trace.IsConnectionProblem(err) && strings.Contains(err.Error(), "connection refused") {
+			err = trace.Wrap(err, "This is the alternative port we tried and it's not configured.")
```
Comment (timothyb89) [inline lib/service/connect.go:1075]: What's "this" referring to? Should we mention some port number that was tried to help debug, or will it be pretty evident in context?

**Review by timothyb89 — APPROVED** [review]
Just have a phrasing question about one of the messages.

File: lib/service/connect.go (hunk 1 above)
Comment (EdwardDowling) [reply lib/service/connect.go:1075]: The port is included in the connection refused error that is being wrapped here.
Unless there is a case I am unaware of and was not able to find it should be pretty clear to the user from the context.
