### PR TITLE
Moderated Sessions improvements

### LINKED ISSUE #10586: "session_recording: proxy" causes unexpected side-effects and issues
### What

Discovered during v9 beta testing.

Enabling `session_recording: "proxy"` is causing unexpected side effects:

1. Seemingly doubled notification about session creation. Each time we will see:
```
tsh ssh graviton-node

Teleport > Creating session with ID: a7012025-db3e-45fa-b3a1-277893cbc3f9...

Teleport > User tener joined the session.

Teleport > Launching session...

Teleport > Creating session with ID: f18c2231-c218-49b4-b746-79bbace74bb4...

Teleport > User tener joined the session.

Teleport > Launching session...
```
2. From the 2 session IDs, only the second ("f18c2231-c218-49b4-b746-79bbace74bb4") above will be in audit log.
3. The active sessions are listed, but they cannot be joined either by Web UI or with `tsh join`. 
4. After finishing, "Session Recordings" tab does not display the node name. Instead "N/A" is shown.
5. In audit log the "Session started" event lacks "server_labels" and "server_hostname" information.

Note: the recording on its own *works*. After the session is finished `tsh play` works fine, playback with Web UI is functional too.

### LINKED ISSUE #10659: starting a session with `require_session_mfa` closes session in few seconds
### Description

**What happened**:
In the web UI, i started a session, and in a few seconds, my session closes (as shown in image below) and hangs. Because it hangs, I am unable to ssh into the same node anymore even as a different user or when I try to ssh with `tsh`. I also get the same behavior in `tsh` where it closes session and hangs. I could not escape the hanging, so I had to restart teleport.

image

This is the logs:
```
2022-02-28T03:20:28Z DEBU             Will join session 9c8a21dd-85e4-43c3-98e7-0fc48607aa92 for SSH connection 174.127.243.201:47324. srv/ctx.go:514
2022-02-28T03:20:28Z DEBU [SESSION:N] Starting poll and sync of terminal size to all parties. srv/sess.go:1391
2022-02-28T03:20:28Z DEBU [SESSION:N] Launching session 9c8a21dd-85e4-43c3-98e7-0fc48607aa92. srv/sess.go:803
2022-02-28T03:20:28Z INFO [AUDIT]     session.start addr.local:127.0.0.1:3022 addr.remote:174.127.243.201:47324 cluster_name:cfg-auth-service-cluster-name-ALL-svc code:T2000I ei:0 event:session.start login:root namespace:default server_addr:127.0.0.1:3022 server_hostname:cfg-teleport-nodename-ALL-svc server_id:3b3cd3b0-663c-4b3e-8321-198eea7b57c0 server_labels:map[environment:test] session_recording:node sid:9c8a21dd-85e4-43c3-98e7-0fc48607aa92 size:80:25 time:2022-02-28T03:20:28.249Z uid:b506ee62-4ca3-4a42-b359-24bfcfd0c0e1 user:lisa events/emitter.go:325
2022-02-28T03:20:28Z DEBU [NODE]      Handling request window-change, want reply false. id:6 local:127.0.0.1:3022 login:root remote:174.127.243.201:47324 teleportUser:lisa regular/sshserver.go:1398
2022-02-28T03:20:28Z DEBU             Will join session 9c8a21dd-85e4-43c3-98e7-0fc48607aa92 for SSH connection 174.127.243.201:47324. srv/ctx.go:514
2022-02-28T03:20:39Z DEBU [AUTH]      ClientCertPool -> cert(cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:216377719071506119846396333477626861121) auth/middleware.go:609
2022-02-28T03:20:39Z DEBU [AUTH]      ClientCertPool -> cert(cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:9751102761758653151994458698299553566) auth/middleware.go:609
2022-02-28T03:20:39Z DEBU [AUTH]      ClientCertPool -> cert(cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:216377719071506119846396333477626861121) auth/middleware.go:609
2022-02-28T03:20:39Z DEBU [AUTH]      ClientCertPool -> cert(cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:9751102761758653151994458698299553566) auth/middleware.go:609
2022-02-28T03:20:39Z DEBU [AUTH:1]    Server certificate cert(3b3cd3b0-663c-4b3e-8321-198eea7b57c0.cfg-auth-service-cluster-name-ALL-svc issued by cfg-auth-service-cluster-name-ALL-svc:216377719071506119846396333477626861121). auth/middleware.go:293
2022-02-28T03:20:43Z ERRO [SESSION:N] Failed to check presence, closing session as a security measure error:[
ERROR REPORT:
Original Error: *trace.BadParameterError cannot fetch session without auth service
Stack Trace:
  /go/src/github.com/gravitational/teleport/lib/srv/sess.go:1669 github.com/gravitational/teleport/lib/srv.(*session).trackerGet
  /go/src/github.com/gravitational/teleport/lib/srv/sess.go:1421 github.com/gravitational/teleport/lib/srv.(*session).checkPresence
  /go/src/github.com/gravitational/teleport/lib/srv/sess.go:827 github.com/gravitational/teleport/lib/srv.(*session).launch.func1
  /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: cannot fetch session without auth service] srv/sess.go:829
2022-02-28T03:20:43Z INFO [SESSION:N] Closing session 9c8a21dd-85e4-43c3-98e7-0fc48607aa92. srv/sess.go:734
2022-02-28T03:20:43Z INFO [SESSION:N] Closing party 8bf4484e-c82a-477e-810f-51f9ad945b27 srv/sess.go:1656
2022-02-28T03:20:43Z DEBU [SESSION:N] Stopping poll and sync of terminal size to all parties. srv/sess.go:1412
2022-02-28T03:20:43Z DEBU [SESSION:N] Copying from PTY to writer completed with error read /dev/ptmx: input/output error. srv/sess.go:851
```

I turned off the `require_session_mfa` flag, restarted my teleport, and I do not get the same problem. I also switched my teleport version from `9.0.0-beta.1` to `v8.0.0.rc.1` (sorry, that was the latest v8 i had at the moment) and i do not get the same problem in both `tsh` and in the web UI with the flag on.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. run teleport `9.0.0-beta.1`
2. login with a user with a role with `require_session_mfa` set to true
3. in the web UI and tsh, try ssh into a node, wait for a few seconds, and the message `closing session...` will appear

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v9.0.0-beta.1 git:v9.0.0-beta.1-0-g5696e0b8e go1.17.2
- Server OS (e.g. from `/etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): aws

### Client Details
- Tsh version (`tsh version`): Teleport v9.0.0-beta.1 git:v8.0.0-alpha.1-663-g051da5e0f go1.17.3
- Computer OS (e.g. Linux, macOS, Windows): linux
- Additional details:
config:
```
teleport:
  nodename: cfg-teleport-nodename-ALL-svc

auth_service:
  enabled: yes
  cluster_name: cfg-auth-service-cluster-name-ALL-svc

  authentication:
    type: local
    second_factor: webauthn
    u2f:
      app_id: https://kimlisa.dev:3080
      facets:
      - https://kimlisa.dev:3080
    require_session_mfa: no
  tokens: 
       - "node,auth,proxy:hello"
  license_file: /home/ubuntu/license.pem

ssh_service:
  enabled: yes
  labels:
    environment: test

```

### LINKED ISSUE #10818: Improve UX for moderated sessions
### Description

While testing moderated sessions, I found the lack of feedback a tough UX. Sessions the require a use to join, look like they just hang. 

**What happened**:
```
Teleport > Creating session with ID: 544c73f5-a56d-4160-8f70-4779e3ec433e...

Teleport > User ben-test joined the session.
```

**What you expected to happen**:
We should provide context for which roles need to join. 

```
Creating session with uuid <example-uuid>...
This session requires moderator. Waiting for others to join:
- role: auditor-role x1
```

### LINKED ISSUE #10872: Can't cancel session start during moderation.
### Description
**What happened**:

I'm unable to send a sigterm/sigstop to stop a moderation request. If had to close my tab. OS: MacOS. 

image

### PR DESCRIPTION
**Pull request by xacrimon**
Items addressed:
- Implemented UX changes discussed in #10725 closing #10818 
- Fix #10659 
- Fix #10872 
- Fix #10586 
- Docs fixes
- Get rid of empty lines in between Teleport broadcast within sessions
- Fix RBAC engine being too restrictive with policysets with no matching require policies after kind filtering
- Don't silently ignore errors due to session message broadcasts.
- Fix exec requests blowing up.

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -789,6 +790,36 @@ func testUUIDBasedProxy(t *testing.T, suite *integrationTestSuite) {
...
+	personA.Type("\aecho hi\n\r")
+	go cl.SSH(ctx, []string{}, false)
+
+	// wait for the tracker to be created
+	time.Sleep(5 * time.Second)
+
+	// verify that the tracker was created
+	trackers, err := site.GetActiveSessionTrackers(ctx)
+	require.NoError(t, err)
+	require.Len(t, trackers, 1)
```
Comment (espadolini) [inline integration/integration_test.go:820]: This should use `require.Eventually`

**Review by espadolini — APPROVED** [review]

File: lib/auth/session_access.go [hunk 2]
```diff
@@ -36,17 +37,28 @@ import (
 // that is harder to debug in the case of misconfigured policies or other error and are harder to intuitively follow.
 // In the real world, the number of roles and session are small enough that this doesn't have a meaningful impact.
 type SessionAccessEvaluator struct {
-	kind       types.SessionKind
-	policySets []*types.SessionTrackerPolicySet
+	kind        types.SessionKind
+	policySets  []*types.SessionTrackerPolicySet
+	IsModerated bool
```
Comment (zmb3) [inline lib/auth/session_access.go:42]: Should this be exported? Do external clients ever need to set this, or does the access evaluator determine on its own when the session is moderated?

File: lib/auth/session_access.go [hunk 3]
```diff
@@ -36,17 +37,28 @@ import (
...
 func NewSessionAccessEvaluator(policySets []*types.SessionTrackerPolicySet, kind types.SessionKind) SessionAccessEvaluator {
-	return SessionAccessEvaluator{
-		kind,
-		policySets,
+	e := SessionAccessEvaluator{
+		kind:       kind,
+		policySets: policySets,
 	}
+
+Outer:
```
Comment (zmb3) [inline lib/auth/session_access.go:53]: No need for this label, there's only one loop to break from.

File: lib/auth/session_access.go [hunk 4]
```diff
@@ -209,6 +221,39 @@ func (e *SessionAccessEvaluator) hasPolicies() bool {
...
+func (e *SessionAccessEvaluator) PrettyRequirementsList() string {
+	s := "require all:"
+
+	for _, policySet := range e.policySets {
+		policies := e.extractApplicablePolicies(policySet)
+		if len(policies) == 0 {
+			continue
+		}
+
+		s += fmt.Sprintf("\n\t  one of (%v):", policySet.Name)
```
Comment (zmb3) [inline lib/auth/session_access.go:234]: This is okay, but [`strings.Builder`](https://pkg.go.dev/strings#Builder) would be better than a bunch of Sprintf and concatenation.

File: lib/client/api.go [hunk 5]
```diff
@@ -353,6 +353,10 @@ type Config struct {
 
 	// Invited is a list of people invited to a session.
 	Invited []string
+
+	// ParticipantRequirements is set if debug information about participants requirements
+	// should be printed in moderated sessions.
+	ParticipantRequirements bool
```
Comment (zmb3) [inline lib/client/api.go:359]: This name was a little confusing to me. How about `DisplayParticipantRequirements` instead?

File: lib/srv/sess.go [hunk 6]
```diff
@@ -669,25 +672,34 @@ func newSession(id rsession.ID, r *SessionRegistry, ctx *ServerContext) (*sessio
...
+		presenceEnabled:     ctx.Identity.Certificate.Extensions[teleport.CertExtensionMFAVerified] != "",
+		io:                  NewTermManager(),
+		stateUpdate:         sync.NewCond(&sync.Mutex{}),
+		doneCh:              make(chan struct{}, 2),
+		initiator:           ctx.Identity.TeleportUser,
+		verboseRequirements: utils.AsBool(ctx.env[teleport.EnvSSHSessionParticipantRequirements]),
 	}
 
+	go func() {
+		<-sess.io.TerminateNotifier()
```
Comment (zmb3) [inline lib/srv/sess.go:696]: From what I can tell, it's not guaranteed that we write to this channel. That means this goroutine can leak. Am I missing something?

File: tool/tsh/kube.go [hunk 7]
```diff
@@ -406,6 +410,7 @@ func newKubeExecCommand(parent *kingpin.CmdClause) *kubeExecCommand {
 	c.Flag("tty", "Stdin is a TTY").Short('t').BoolVar(&c.tty)
 	c.Flag("reason", "The purpose of the session.").StringVar(&c.reason)
 	c.Flag("invite", "A comma separated list of people to mark as invited for the session.").StringVar(&c.invited)
+	c.Flag("participant-req", "Displays a verbose list of required participants in a moderated session.").BoolVar(&c.participantRequirements)
```
Comment (zmb3) [inline tool/tsh/kube.go:413]: Did you and @xinding33 agree on the naming of this `--participant-req` flag? I think we could choose a better name, but no need to bikeshed if it was already decided.

Comment (xacrimon) [reply tool/tsh/kube.go:413]: @zmb3 Yep, we did agree on it.

File: lib/auth/session_access.go (hunk 2 above)
Comment (xacrimon) [reply lib/auth/session_access.go:42]: We never need to set this but we do read it. Switched to a getter to prevent accidental assignment

File: lib/srv/termmanager.go [hunk 8]
```diff
@@ -214,6 +227,20 @@ func (g *TermManager) AddReader(name string, r io.Reader) {
 				return
 			}
 
+			for _, b := range buf[:n] {
+				if b == 0x03 {
```
[the remark this answers is not in the document]
Comment (xacrimon) [reply lib/srv/termmanager.go:231]: The CTRLC control code. Added a comment

File: lib/client/api.go (hunk 5 above)
Comment (xacrimon) [reply lib/client/api.go:359]: Sure

File: lib/srv/sess.go (hunk 6 above)
Comment (xacrimon) [reply lib/srv/sess.go:696]: Correct. Fixed the leak now

File: constants.go [hunk 9]
```diff
@@ -644,9 +644,9 @@ const (
 	// EnvSSHSessionInvited is an environment variable listning people invited to a session.
 	EnvSSHSessionInvited = "TELEPORT_SESSION_JOIN_MODE"
 
-	// EnvSSHSessionParticipantRequirements is set to true or false to indicate if participant
+	// EnvSSHSessiondisplayDisplayParticipantRequirements is set to true or false to indicate if participant
```
Comment (zmb3) [inline constants.go]: You've got a double `displayDisplay` in here.

File: lib/auth/session_access.go [hunk 10]
```diff
@@ -223,22 +227,30 @@ func (e *SessionAccessEvaluator) hasPolicies() bool {
...
 		}
 
-		s += fmt.Sprintf("\n\t  one of (%v):", policySet.Name)
+		s.WriteString("\n\t  one of (")
+		s.WriteString(policySet.Name)
+		s.WriteString("):")
 
 		for _, require := range policies {
-			s += fmt.Sprintf("\n\t    - %vx %v with mode %v", require.Count, require.Filter, strings.Join(require.Modes, ","))
+			s.WriteString("\n\t    - ")
```
Comment (zmb3) [inline lib/auth/session_access.go:244]: builder implements `io.Writer`, so you can use `fmt.Fprintf(s, "", ...)` if that's cleaner.

File: lib/srv/termmanager.go [hunk 11]
```diff
@@ -240,6 +268,7 @@ func (g *TermManager) CountRead() uint64 {
 }
 
 func (g *TermManager) Close() {
+	close(g.terminateNotifier)
```
Comment (zmb3) [inline lib/srv/termmanager.go:271]: We still have the possibility of a double close panic here, right? Should probably atomically check `g.closed` and only close the channel the first time.

Comment (xacrimon) [reply lib/srv/termmanager.go:271]: Ah yeah, that's true. I was basing of assumption off this only getting called once but lets resolve that.

**Review by zmb3 — APPROVED** [review]

**Review by espadolini — APPROVED** [review]

**Review by ptgott — APPROVED** [review]

**Comment by r0mant** [comment]
@xacrimon Looks like this is approved, can you please merge it and backport to branch/v9?
