### PR TITLE
Wraps go-redis internal logger and logs at TRACE level.

### LINKED ISSUE #31303: redis driver spams error logs when accessing redis database
Expected behavior:
No spam

Current behavior:

```
redis: 2023/08/31 17:34:11 cluster.go:1760: getting command info: NOPERM this user has no permissions to run the 'command' command or its subcommand      
redis: 2023/08/31 17:34:11 cluster.go:1760: getting command info: NOPERM this user has no permissions to run the 'command' command or its subcommand       
2023-08-31T17:34:12Z             DEBU Initializing AWS session for region ca-central-1. cloud/clients.go:635     
```

Note that these are logged by teleport driver

Bug details:
- Teleport version: 14.0.0-alpha.2
- Steps
  - `tsh db connect --db-user <user> memorydb`
  - `get name`

Test Plan:
https://github.com/gravitational/teleport/issues/31122

Need to test versions with older driver to see if this is a regression.

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #31303

Will backport together will the new driver to older branches.

### CODE REVIEW

File: lib/srv/db/redis/engine.go [hunk 1]
```diff
@@ -484,3 +485,19 @@ func isTeleportErr(err error) bool {
...
 	return ok
 }
+
+// driverLogger implements go-redis driver's internal logger using logrus and
+// logs everything at TRACE level.
+type driverLogger struct {
+	*logrus.Entry
+}
+
+func (l *driverLogger) Printf(_ context.Context, format string, v ...interface{}) {
```
Comment (jakule) [inline lib/srv/db/redis/engine.go:495]: nit: 
```suggestion
func (l *driverLogger) Printf(_ context.Context, format string, v ...any) {
```

**Review by jakule — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
