### PR TITLE
fix: Address flakiness and revisit TestTeleportClient_Login_local

### LINKED ISSUE #18683: `TestTeleportClient_Login_local` flakiness
Fails on Github Actions:

https://github.com/gravitational/teleport/actions/runs/3525019115/jobs/5911196047

```
===================================================
5181 tests passed. 4 failed, 97 skipped
===================================================
FAIL: github.com/gravitational/teleport/lib/client
FAIL: github.com/gravitational/teleport/lib/client.TestTeleportClient_Login_local/OTP_device_login_with_hijack
FAIL: github.com/gravitational/teleport/lib/client.TestTeleportClient_Login_local/OTP_preferred
FAIL: github.com/gravitational/teleport/lib/client.TestTeleportClient_Login_local
===================================================
OUTPUT github.com/gravitational/teleport/lib/client.TestTeleportClient_Login_local
===================================================
=== RUN   TestTeleportClient_Login_local
--- FAIL: TestTeleportClient_Login_local (33.53s)
===================================================
OUTPUT github.com/gravitational/teleport/lib/client.TestTeleportClient_Login_local/OTP_device_login_with_hijack
===================================================
=== RUN   TestTeleportClient_Login_local/OTP_device_login_with_hijack
WARNING: You are using insecure connection to SSH proxy https://localhost:46179
    api_login_test.go:263: 
        	Error Trace:	/__w/teleport/teleport/lib/client/api_login_test.go:263
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestTeleportClient_Login_local/OTP_device_login_with_hijack
    --- FAIL: TestTeleportClient_Login_local/OTP_device_login_with_hijack (5.00s)
===================================================
OUTPUT github.com/gravitational/teleport/lib/client.TestTeleportClient_Login_local/OTP_preferred
===================================================
=== RUN   TestTeleportClient_Login_local/OTP_preferred
WARNING: You are using insecure connection to SSH proxy https://localhost:46179
Enter an OTP code from a device:
    api_login_test.go:[263](https://github.com/gravitational/teleport/actions/runs/3525019115/jobs/5911196047#step:6:264): 
        	Error Trace:	/__w/teleport/teleport/lib/client/api_login_test.go:263
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestTeleportClient_Login_local/OTP_preferred
    --- FAIL: TestTeleportClient_Login_local/OTP_preferred (5.00s)
===================================================
make: *** [test-go] Error 1
```

### PR DESCRIPTION
**Pull request by codingllama**
Fix flakiness due to OTP goroutine cancel changes introduced by #47114 and do various improvements to the test.

The OTP cancel was moved from PromptPIN to PromptTouch, assuming well-behaved implementations, but functions inside TestTeleportClient_Login_local deviate from the norm. The cancel at PromptPIN was reintroduced.

Improvements to the test include:

* Removing calls to prompt.SetStdin
* Removing the global client.hasTouchIDCredentials variable
* (The changes above make the test truly parallel)
* Making sub-tests parallel

Closes #18683.

### CODE REVIEW

**Comment by codingllama** [comment]
@nklaassen @GavinFrazar @ravicious, mind giving this a try? It looks to work for me but I'd rather be sure.

```shell
gotestsum --format=dots --max-fails=1 ./lib/client -run=TestTeleportClient_Login_local -count=100
```

**Comment by codingllama** [comment]
Backport labels are aspirational - if there aren't too many conflicts I'll go as far as v14, but otherwise I'll stop.

**Comment by codingllama** [comment]
Looks like it still flakes, it's just less common: https://github.com/gravitational/teleport/actions/runs/11260895244/job/31313121483?pr=47406.  😢

**Comment by codingllama** [comment]
I think I got it this time, but the test is still too slow. I'll see if I can make it a bit faster, then I'll update the PR title/description according to changes.

**Comment by GavinFrazar** [comment]
> @nklaassen @GavinFrazar @ravicious, mind giving this a try? It looks to work for me but I'd rather be sure.
> 
> ```shell
> gotestsum --format=dots --max-fails=1 ./lib/client -run=TestTeleportClient_Login_local -count=100
> ```

just ran this on a94e51539ba78a749c195c16afda304c258efb87 and it passed all runs for me

File: lib/client/api_login_test.go [hunk 1]
```diff
@@ -66,232 +66,256 @@ func TestTeleportClient_Login_local(t *testing.T) {
...
-			pref, err := authServer.GetAuthPreference(ctx)
-			require.NoError(t, err)
-			if pref.GetSecondFactor() != test.secondFactor {
-				pref.SetSecondFactor(test.secondFactor)
-				_, err = authServer.UpsertAuthPreference(ctx, pref)
-				require.NoError(t, err)
-			}
-
+			t.Parallel()
+
```
Comment (GavinFrazar) [inline lib/client/api_login_test.go:268]: when backporting this to v15 I think you'll need to do the `test := test` thing since go.mod there is still on 1.21

**Review by GavinFrazar — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Comment by codingllama** [comment]
Thanks, everyone. Merging.
