### PR TITLE
App Access: Support AWS Console for US GovCloud Partition

### LINKED ISSUE #13426: AWS Console Access doesn't work in GovCloud regions
AWS console access currently hardcodes federated login URLs for regular regions which doesn't work for govcloud.

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #13426
- #13426 

Changes:

- recognize AWS US Gov and AWS China console URLs
- use AWS US Gov and AWS China federation endpoints

Docs:
https://github.com/gravitational/teleport/pull/15958/files

Test build:
https://get.gravitational.com/teleport-ent-v9.3.5-us-gov-fix-linux-arm64-bin.tar.gz

Note that with this change, either `AWS_REGION` or `AWS_DEFAULT_REGION` is required through env var or AWS credentials file when launching the Teleport service. Will do a separate change to auto-get region from IMDSv2 and use regional STS endpoint.

Testing:
- [x] ca-central-1
- [x] cn-northwest-1
- [x] us-gov-west-1

### CODE REVIEW

File: api/types/app_test.go [hunk 1]
```diff
@@ -164,3 +164,53 @@ func TestAppServerSorter(t *testing.T) {
...
+		},
+		{
+			name:         "Region based not supported yet",
+			uri:          "https://us-west-1.console.aws.amazon.com",
+			isAWSConsole: false,
+		},
+		{
+			name:         "Not an AWS Console URL",
+			uri:          "https://hello.world",
+			isAWSConsole: false,
```
Comment (jakule) [inline api/types/app_test.go:197]: nit: If you change the type to `require.BoolAssertionFunc` and assign na assert function instead of `bool`, then you can remove the `if` below in the test.

**Comment by russjones** [comment]
@greedy52 Can you also create a docs PR so if another customers runs into this they can work around it without our help?

**Review by smallinsky — APPROVED** [review]

**Review by codingllama — APPROVED** [review]
Nicely done, @greedy52. Easy to follow and well tested.
