### PR TITLE
fix window resize for OpenSSH, fixes #800

### LINKED ISSUE #800: unable to resize terminal
Im connecting via openssh client using iterm2 3.0.14 on osx to a teleport node and anytime i resize my window i get disconnected with the following error:

$ ssh: unmarshal error for field Modes of type WinChangeReqParamsConnection to xxxx closed.
Killed by signal 1.

### PR DESCRIPTION
**Pull request by klizhentas**

### CODE REVIEW

File: lib/sshutils/req.go [hunk 1]
```diff
@@ -24,11 +24,10 @@ type EnvReqParams struct {
 
 // WinChangeReqParams specifies parameters for window changes
 type WinChangeReqParams struct {
-	W     uint32
-	H     uint32
-	Wpx   uint32
-	Hpx   uint32
-	Modes string
+	W   uint32
```
Comment (russjones) [inline lib/sshutils/req.go]: What do these fields mean?

**Review by russjones — APPROVED** [review]

File: lib/sshutils/req.go (hunk 1 above)
Comment (klizhentas) [inline lib/sshutils/req.go]: terminal size, Modes should not have been there as I've copy-pasted it from PtyReq
