### PR TITLE
Fix sftp handling of colons in paths

### LINKED ISSUE #33921: `tsh scp` should work with windows full path
### Expected behavior:

```console
PS C:\Users\jeff> tsh scp jeff@mynode:test3.txt C:\Users\jeff\test3.txt
test3.txt 100% |█████████████████████████████████████████████████████████████████████████| (12/12 B, 23 kB/s)
```

### Current behavior:

```console
PS C:\Users\jeff> tsh scp jeff@mynode:test3.txt C:\Users\jeff\test3.txt
ERROR: failed connecting to host C:0: failed to dial target host
        Direct dialing to nodes not found in the inventory is not supported.
If you want to connect to a node without installing Teleport on it, consider registering it with
your cluster with 'teleport join openssh'.

See https://goteleport.com/docs/ver/14.x/server-access/guides/openssh/ for more details.
```

When using `tsh scp` and specifying a full windows path with the drive letter, it attempts to treat the path as a remote path.

This function is called to determine if a path is a local or remote path, and it only looks for the presence of `:` https://github.com/gravitational/teleport/blob/v14.1.1/lib/client/api.go#L2256-L2258

Bug details:
- **Teleport version** - `Teleport v14.1.1 git:api/v14.1.1-0-gfb6429eba7 go1.21.3` (tsh version)
- **Recreation steps** - attempt to use `tsh scp` on Windows, and specify a local path with a drive letter.
- **Debug logs** - n/a

### PR DESCRIPTION
**Pull request by atburke**
This change fixes some edge cases in sftp target string (user@host:/path) with the ":" character.
- Absolute Windows paths (e.g. C:\Users\foo\bar.txt) are no longer mistaken for remote destinations.
- Local paths containing a colon are correctly detected if they are preceded by a path separator.

Fixes #33921.

Changelog: Fixed handling of local tsh scp targets that contain a colon

### CODE REVIEW

File: lib/sshutils/sftp/parse.go [hunk 1]
```diff
@@ -39,13 +41,40 @@ type Destination struct {
...
+		// Can't be remote without a colon.
+		return false
+	}
+	slashIndex := strings.Index(input, string(os.PathSeparator))
+	// On Unix, colons are valid in path names, so check if the first colon is
+	// part of the path.
+	//
+	// If we get something like "foo:bar", we have no way to tell if that's local
+	// path "foo:bar" or remote path "bar" on host "foo". We'll assume it's the
+	// former, as the latter can also be written as "./foo:bar".
```
Comment (zmb3) [inline lib/sshutils/sftp/parse.go]: Have we mixed up "former" and "latter" in this comment or am I just confused? :-)

File: lib/sshutils/sftp/parse.go [hunk 2]
```diff
@@ -39,13 +41,40 @@ type Destination struct {
 	Path string
 }
 
+var windowsDrivePattern = regexp.MustCompile(`^[A-Z]:\\`)
```
Comment (bl-nero) [inline lib/sshutils/sftp/parse.go:44]: Nit: I'm not sure if it's important in this context, but technically, Windows can accept paths that don't have a backslash after the colon. Path `C:foo\bar` would then be interpreted as "`foo\bar`, relative to the current directory on drive C".

**Review by bl-nero — APPROVED** [review]

**Comment by atburke** [comment]
Friendly ping @zmb3 and/or @tigrato

**Review by tigrato — APPROVED** [review]
