### PR TITLE
Fix interactive sessions always exiting with code 0

### LINKED ISSUE #3202: Interactive sessions do not exit with correct exit code.
When running exec commands, `tsh` will exit with the correct exit code.

```
$ tsh ssh server01 exit 2
error: Process exited with status 2
$ echo $?
2
```

However, with an interactive session (shell), Teleport always returns `0`.

```
$ tsh ssh server01
$ exit 2
logout
the connection was closed on the remote side on  10 Dec 19 01:07 UTC
$ echo $?
0
```

Compared to OpenSSH which does return the appropriate exit code.

```
$ ssh server01
Warning: Permanently added '[localhost]:3023' (RSA) to the list of known hosts.
Warning: Permanently added '[localhost]:3022' (RSA) to the list of known hosts.
$ exit 2
logout
Connection to localhost closed.
$ echo $?
2
```

It should be noted this is purely a client side issue with `tsh`. The server, `teleport`, correctly sends the exit code, it is just ignored and not printed by `tsh`.

This is because for exec commands, `session.Run()` is used which will block until completion and return the exit code and interactive sessions use `session.Start()` or `session.Shell()` which do not block and `session.Wait()` is never used.

https://github.com/gravitational/teleport/blob/branch/4.1/lib/client/session.go#L472
https://github.com/gravitational/teleport/blob/branch/4.1/lib/client/session.go#L440
https://github.com/gravitational/teleport/blob/branch/4.1/lib/client/session.go#L409

### PR DESCRIPTION
**Pull request by rosstimothy**
**Purpose**

Correctly propagate error codes from an interactive `tsh ssh` session - fixes #3202

**Implementation**

- Explicitly call `Wait` on the `ssh.Session` for interactive sessions
- Set `TeleportClient.ExitStatus` if there was an  `ssh.ExitError` or `ssh.ExitMissingError` returned by `runShell`

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -4758,6 +4759,138 @@ func testBPFExec(t *testing.T, suite *integrationTestSuite) {
...
+			desc:           "Run Command Interactively and Fail With Code 2",
+			command:        []string{"exit 2"},
+			interactive:    true,
+			errorAssertion: require.Error,
+			statusCode:     2,
+		},
+		// A failed interactive session should have a non-zero status code
+		{
+			desc:           "Interactively Fail With Code 3",
+			input:          "exit 3\n\r",
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4801]: Maybe add another test case for
```go
			input:          fmt.Sprintf("%v\n\rexit 3\n\r", lsPath),
```
?

File: integration/integration_test.go [hunk 2]
```diff
@@ -4758,6 +4759,138 @@ func testBPFExec(t *testing.T, suite *integrationTestSuite) {
...
+			interactive:    true,
+			errorAssertion: require.Error,
+			statusCode:     3,
+		},
+		// A successful interactive session should have a zero status code
+		{
+			desc:           "Interactively Exist Successfully",
+			input:          fmt.Sprintf("%v\n\rexit\n\r", lsPath),
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4809]: Maybe test plain `exit` separately as well
```go
			input:          fmt.Sprintf("exit\n\r", lsPath),
```
?

File: integration/integration_test.go [hunk 3]
```diff
@@ -4758,6 +4759,138 @@ func testBPFExec(t *testing.T, suite *integrationTestSuite) {
...
+				tconf.Proxy.Enabled = true
+				tconf.Proxy.DisableWebService = false
+				tconf.Proxy.DisableWebInterface = true
+
+				// Configure Node.
+				tconf.SSH.Enabled = true
+				return t, nil, nil, tconf
+			}
+			main := suite.newTeleportWithConfig(makeConfig())
+			defer main.StopAll()
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4838]: Consider
```suggestion
			t.Cleanup(func() { main.StopAll() })
```

File: integration/integration_test.go [hunk 4]
```diff
@@ -4758,6 +4759,138 @@ func testBPFExec(t *testing.T, suite *integrationTestSuite) {
...
+					cli.Stdout = term
+					cli.Stdin = term
+					term.Type(tt.input)
+				}
+
+				err = cli.SSH(doneContext, tt.command, false)
+				if err == nil && tt.statusCode != 0 {
+					t.Errorf("ssh session exited with status code 0. expected to receive status code %d", tt.statusCode)
+					return
+				}
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4867]: This `if` shouldn't be necessary, it's covered by the `errorAssertion` right below?

File: integration/integration_test.go [hunk 5]
```diff
@@ -4758,6 +4759,138 @@ func testBPFExec(t *testing.T, suite *integrationTestSuite) {
...
+				tt.errorAssertion(t, err)
+
+				//check that the exit code of the session matches the expected one
+				if err != nil {
+					exitError, ok := trace.Unwrap(err).(*ssh.ExitError)
+					require.True(t, ok)
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4873]: Using `require.ErrorAs` instead (if possible) might be a bit more idiomatic.

File: integration/integration_test.go [hunk 6]
```diff
@@ -4758,6 +4759,138 @@ func testBPFExec(t *testing.T, suite *integrationTestSuite) {
...
+				doneCancel()
+			}()
+
+			for {
+				// Wait for either the session to finish or the timeout to occur
+				select {
+				case <-doneContext.Done():
+					return
+				case <-failedContext.Done():
+					require.NoError(t, failedContext.Err(), "Timed out waiting for session to complete")
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4887]: In addition to my goroutine remark above, I'd prefer avoiding this `for/select` loop entirely and replacing the two contexts with a single one configured with the 10s timeout. The sole context would be then passed in to `cli.SSH` -- should the timeout occur during a prolonged operation within `cli.SSH`, the latter would fail with an error to be caught by the test.

File: integration/integration_test.go [hunk 7]
```diff
@@ -4758,6 +4759,138 @@ func testBPFExec(t *testing.T, suite *integrationTestSuite) {
...
+			}
+			main := suite.newTeleportWithConfig(makeConfig())
+			defer main.StopAll()
+
+			// context to signal when the client is done with the terminal.
+			failedContext, failedCancel := context.WithTimeout(context.Background(), time.Second*10)
+			defer failedCancel()
+			doneContext, doneCancel := context.WithCancel(context.Background())
+
+			go func() {
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4845]: Why is this run in a goroutine? I'd say it can be run directly as is.

File: lib/client/api.go [hunk 8]
```diff
@@ -1933,6 +1933,11 @@ func (tc *TeleportClient) runShell(nodeClient *NodeClient, sessToJoin *session.S
 		return trace.Wrap(err)
 	}
 	if err = nodeSession.runShell(tc.OnShellCreated); err != nil {
+		originErr := trace.Unwrap(err)
+		exitErr, ok := originErr.(*ssh.ExitError)
+		if ok {
```
Comment (andrejtokarcik) [inline lib/client/api.go:1938]:
```suggestion
		if exitErr, ok := trace.Unwrap(err).(*ssh.ExitError); ok {
```
might be more idiomatic.

**Comment by andrejtokarcik** [comment]
The issue linked to in the PR description seems to be incorrect BTW.

File: integration/integration_test.go (hunk 3 above)
Comment (rosstimothy) [reply integration/integration_test.go:4848]: Can do, copied most of the setup stuff from other tests that had this.

File: integration/integration_test.go (hunk 1 above)
Comment (rosstimothy) [reply integration/integration_test.go:4811]: Done.

File: integration/integration_test.go (hunk 2 above)
Comment (rosstimothy) [reply integration/integration_test.go:4819]: Done.

File: integration/integration_test.go (hunk 4 above)
Comment (rosstimothy) [reply integration/integration_test.go:4877]: Yeah I don't think this is necessary. I was trying to prevent an invalid `errorAssertion` and `statusCode` combination.

File: integration/integration_test.go (hunk 5 above)
Comment (rosstimothy) [reply integration/integration_test.go:4883]: +1 - didn't know that existed

File: integration/integration_test.go [hunk 9]
```diff
@@ -4758,6 +4785,139 @@ func testBPFExec(t *testing.T, suite *integrationTestSuite) {
...
+			errorAssertion: require.NoError,
+			statusCode:     0,
+		},
+		// A successful interactive session should have a zero status code
+		{
+			desc:           "Interactively Exit",
+			input:          "exit\n\r",
+			interactive:    true,
+			errorAssertion: require.NoError,
+			statusCode:     -100,
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4854]: This looks weird. Since `statusCode` isn't checked when `errorAssertion` is `require.NoError`, the `statusCode` parameter can be entirely omitted from those test-case structs that have `require.NoError`.

File: integration/integration_test.go [hunk 10]
```diff
@@ -1218,10 +1219,20 @@ func runDisconnectTest(t *testing.T, suite *integrationTestSuite, tc disconnectT
...
 			}
+
+			isSSHError := func(e error) bool {
+				switch trace.Unwrap(err).(type) {
+				case *ssh.ExitError, *ssh.ExitMissingError:
+					return true
+				default:
+					return false
+				}
+			}
```
Comment (andrejtokarcik) [inline integration/integration_test.go:1230]: Could you extract this into a standalone function `isSSHError` (within this file) so that it can be reused in `testPAM` and `testWindowChange` where virtually the same `switch` is introduced again?

File: integration/integration_test.go [hunk 11]
```diff
@@ -4197,11 +4218,17 @@ func testWindowChange(t *testing.T, suite *integrationTestSuite) {
...
+			case nil, *ssh.ExitError, *ssh.ExitMissingError:
+				err = nil
+			default:
+				require.NoError(t, err)
+			}
+
 			if err == nil {
 				break
 			}
 		}
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4231]: For example, if the `isSSHError` function (see above) was available, this could be rewritten as
```suggestion
			if err == nil || isSSHError(err) {
				err = nil
				break
			}
		}
		require.NoError(t, err)
```

File: lib/client/api.go [hunk 12]
```diff
@@ -1933,6 +1933,15 @@ func (tc *TeleportClient) runShell(nodeClient *NodeClient, sessToJoin *session.S
 		return trace.Wrap(err)
 	}
 	if err = nodeSession.runShell(tc.OnShellCreated); err != nil {
+		switch e := trace.Unwrap(err).(type) {
+		case *ssh.ExitError:
+			tc.ExitStatus = e.ExitStatus()
+		case *ssh.ExitMissingError:
+			tc.ExitStatus = 1
```
Comment (andrejtokarcik) [inline lib/client/api.go:1940]: Not sure if this is semantically correct. Must `ExitMissingError` imply a failed/non-zero `ExitStatus`?

Comment (rosstimothy) [reply lib/client/api.go:1940]: I copied the behavior of non interactive sessions: https://github.com/gravitational/teleport/blob/master/lib/client/api.go#L1918

File: lib/client/api.go [hunk 13]
```diff
@@ -1933,6 +1933,15 @@ func (tc *TeleportClient) runShell(nodeClient *NodeClient, sessToJoin *session.S
...
+		default:
+			break
```
Comment (andrejtokarcik) [inline lib/client/api.go:1942]:
```suggestion
```

File: integration/integration_test.go (hunk 11 above)
Comment (rosstimothy) [reply integration/integration_test.go]: Done.

File: integration/integration_test.go [hunk 14]
```diff
@@ -4163,7 +4176,12 @@ func testWindowChange(t *testing.T, suite *integrationTestSuite) {
 		cl.Stdin = personA
 
 		err = cl.SSH(context.TODO(), []string{}, false)
-		require.NoError(t, err)
+		switch trace.Unwrap(err).(type) {
+		case nil, *ssh.ExitError, *ssh.ExitMissingError:
+			break
+		default:
+			require.NoError(t, err)
+		}
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4184]: Use `isSSHError` here as well...?

File: integration/integration_test.go [hunk 15]
```diff
@@ -4197,11 +4215,12 @@ func testWindowChange(t *testing.T, suite *integrationTestSuite) {
 
 		for i := 0; i < 10; i++ {
 			err = cl.Join(context.TODO(), apidefaults.Namespace, session.ID(sessionID), personB)
-			if err == nil {
+			if err == nil || isSSHError(err) {
 				break
 			}
+
+			require.NoError(t, err)
```
Comment (andrejtokarcik) [inline integration/integration_test.go:4222]: This should be called outside the for loop as before.

**Review by andrejtokarcik — APPROVED** [review]

**Review by fspmarshall — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]
