### PR TITLE
Reduce flakiness of Testbot_Run_CARotation

### LINKED ISSUE #14471: `TestBot_Run_CARotation` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/a5d8a355-0c28-43f0-9c84-06c60978387d?project=ci-account

#### Relevant snippet

```
=== CONT  TestBot_Run_CARotation
    tbot_test.go:86: teleport process did not instantiate in 10 seconds
2022-07-14T14:59:15Z INFO             Shutting down long running test processes.. tbot/tbot_test.go:140
2022-07-14T14:59:15Z INFO [AUDIT]     role.created cluster_name:02b75d1401d6 code:T9000I ei:0 event:role.created expires:0001-01-01T00:00:00Z name:db-role time:2022-07-14T14:59:15.484Z uid:5080872e-24e8-45de-b50b-0e92a1c142df user:273f7c04-d92b-4a3a-a3c9-3ba85dba808d.02b75d1401d6 events/emitter.go:263
2022-07-14T14:59:15Z WARN [PROC:4]    Failed to write Admin identity: disk I/O error. pid:53002.4 service/connect.go:648
    tbot_test.go:80: 
        	Error Trace:	tbot_test.go:80
        	            				asm_amd64.s:1571
        	Error:      	Received unexpected error:
        	            	initialization failed
        	            		database is in readonly mode
        	Test:       	TestBot_Run_CARotation
--- FAIL: TestBot_Run_CARotation (10.06s)
```

### PR DESCRIPTION
**Pull request by strideynet**
Closes #14471 

Addresses the flakiness that was caused by Teleport not having enough time to start under loaded conditions. Eventually we'll add some readiness events to `lib/tbot.Bot` which will be able to be used instead of these abitrary waits.

Also removes a temporary patch from the tests that is no longer needed due to a fix in Teleport.

### CODE REVIEW

File: lib/tbot/tbot_test.go [hunk 1]
```diff
@@ -169,24 +167,24 @@ func TestBot_Run_CARotation(t *testing.T) {
 	rotate(ctx, t, log, teleportProcess(), types.RotationPhaseInit)
 	// TODO: These sleeps allow the client time to rotate. They could be
 	// replaced if tbot emitted a CA rotation/renewal event.
-	time.Sleep(time.Second * 15)
+	time.Sleep(time.Second * 30)
```
Comment (marcoandredinis) [inline lib/tbot/tbot_test.go:170]: Could we use https://pkg.go.dev/github.com/stretchr/testify/require#Eventually here?

Comment (strideynet) [reply lib/tbot/tbot_test.go:170]: Not really unfortunately. Because the rotation isn't an immediate process, something which started checking immediately could mean that we'd be checking it's healthy before the rotation has started. This would potentially cause a more confusing failure at the next step.

We have plans to introduce an events emitter for the `tbot.Bot` which will allow us to do this a bit more intelligently in the near future.

Comment (strideynet) [reply lib/tbot/tbot_test.go:170]: So, that would provide half the story, but still wouldn't provide much insight as to whether or not the Bot had received and started processing the update events from the server. This becomes a little more complex since the Bot applies a bit of a debounce (it waits ten seconds after receiving the first event to trigger a CA rotation caused renewal, so that we don't renew multiple times in a row when all of the CAs are rotated at once).

Comment (marcoandredinis) [reply lib/tbot/tbot_test.go:170]: Yeah, it seems tricky to validate
Thank you for the explanation

**Review by marcoandredinis — APPROVED** [review]

**Review by lxea — APPROVED** [review]

**Review by timothyb89 — APPROVED** [review]
