### PR TITLE
fix `tctl auth sign` access denied

### LINKED ISSUE #17367: `tctl auth sign` fails with access denied error
```
> tctl auth sign --user api-token-creator --out api-identity-file --ttl 8760h
ERROR: access denied to perform action "read" on "cluster_networking_config"
```

This is caused by https://github.com/gravitational/teleport/pull/15536 which added a call to `GetClusterNetworkingConfig` in `tctl auth sign`.

### PR DESCRIPTION
**Pull request by Joerger**
Closes https://github.com/gravitational/teleport/issues/17367

### CODE REVIEW

File: tool/tctl/common/auth_command.go [hunk 1]
```diff
@@ -778,15 +778,15 @@ func (a *AuthCommand) generateUserKeys(ctx context.Context, clusterAPI auth.Clie
 	}
 	key.TrustedCA = auth.AuthoritiesToTrustedCerts(hostCAs)
 
-	networkConfig, err := clusterAPI.GetClusterNetworkingConfig(ctx)
-	if err != nil {
-		return trace.Wrap(err)
+	// Is TLS routing enabled?
+	proxyListenerMode := a.config.Auth.NetworkingConfig.GetProxyListenerMode()
+	if networkConfig, err := clusterAPI.GetClusterNetworkingConfig(ctx); err == nil {
+		proxyListenerMode = networkConfig.GetProxyListenerMode()
```
Comment (strideynet) [inline tool/tctl/common/auth_command.go:784]: Can we just output a debug log here so it's clear another mode of behaviour is in play ?

**Review by strideynet — APPROVED** [review]

**Review by espadolini — APPROVED** [review]
Why is `cluster_networking_config` even considered sensitive to begin with? Doesn't it have roughly the same info as the proxy's `webapi/find` endpoint?

**Comment by Joerger** [comment]
> Why is `cluster_networking_config` even considered sensitive to begin with? Doesn't it have roughly the same info as the proxy's `webapi/find` endpoint?

I agree it's a bit weird, as we do make some config options discover-able, but the majority of networking config options are not available through `webapi/find`. I think on the whole we want to enforce authorization on `networking_config`, `auth_preference`, and `session_recoring_config`, and only expose options as needed. I do think we should find a better way to expose these options though, at the very least with a new grpc API endpoint like `ServerInfo`. Or we could add some with/without secrets logic to these config endpoints.

**Review by AntonAM — APPROVED** [review]
