### PR TITLE
Fix nil pointer exception when wrapping listener

### LINKED ISSUE #9350: Running with `--insecure-no-tls` results in `missing parameter Listener`
### Description
Trying to run Teleport 8 behind reverse proxy using the flag `--insecure-no-tls`.

**What happened**:
Container exits with error: `ERROR: missing parameter Listener`

**What you expected to happen**:
It should work

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Run in docker `docker run --hostname localhost --rm -v teleport_config:/etc/teleport -v teleport_data:/var/lib/teleport -p 3023:3023 -p 3025:3025 -p 3080:3080 quay.io/gravitational/teleport:8.0.1 --insecure-no-tls`
2. Crash

### Server Details
- Teleport version (run `teleport version`): 8.0.1 quay image
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

```
2021-12-11T20:01:22Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:172
2021-12-11T20:01:22Z DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
2021-12-11T20:01:22Z DEBU [KEYGEN]    SSH cert authority is going to pre-compute 25 keys. native/native.go:102
2021-12-11T20:01:22Z [PROC:1]    DEBU Using sqlite backend. service/service.go:3662
2021-12-11T20:01:22Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/backend/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:172
2021-12-11T20:01:22Z DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
2021-12-11T20:01:22Z INFO [AUTH]      Updating cluster networking configuration: Kind:"cluster_networking_config" Version:"v2" Metadata:<Name:"cluster-networking-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"config-file" > > Spec:<KeepAliveInterval:300000000000 KeepAliveCountMax:3 ProxyListenerMode:Multiplex > . auth/init.go:432
2021-12-11T20:01:22Z INFO [AUTH]      Updating session recording configuration: Kind:"session_recording_config" Version:"v2" Metadata:<Name:"session-recording-config" Namespace:"default" Labels:<key:"teleport.dev/origin" value:"config-file" > > Spec:<Mode:"node" ProxyChecksHostKeys:"\010\001" > . auth/init.go:450
2021-12-11T20:01:22Z INFO [AUTH]      Updating cluster auth preference: AuthPreference(Type="local",SecondFactor="otp"). auth/init.go:414
2021-12-11T20:01:22Z DEBU [AUTH]      Cluster configuration: ClusterName(localhost, ID=219f510e-7590-4498-abc6-6d41b90a1e0c). auth/init.go:301
2021-12-11T20:01:22Z INFO [AUTH]      Updating cluster configuration: StaticTokens([]). auth/init.go:307
2021-12-11T20:01:22Z INFO [AUTH]      Created namespace: "default". auth/init.go:314
2021-12-11T20:01:22Z DEBU [AUTH]      Migrations: skipping local cluster cert authority "localhost". auth/init.go:957
2021-12-11T20:01:22Z INFO [AUTH]      Auth server is running periodic operations. auth/init.go:392
2021-12-11T20:01:22Z DEBU [AUTH]      Ticking with period: 14s. auth/auth.go:388
2021-12-11T20:01:22Z [AUTH:1]    DEBU Starting watch. resource-kind:lock retry:Linear(attempt=0, duration=0s) services/watcher.go:177
2021-12-11T20:01:22Z DEBU [BUFFER]    Add Watcher(name=auth, prefixes=/locks, capacity=1024, size=0). backend/buffer.go:312
2021-12-11T20:01:22Z [PROC:1]    DEBU Connected state: never updated. service/connect.go:103
2021-12-11T20:01:22Z [PROC:1]    DEBU Connected client: Identity(Admin, cert(0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost issued by localhost:189250250046672973150827989179581290897),trust root(localhost:189250250046672973150827989179581290897)) service/connect.go:87
2021-12-11T20:01:22Z [PROC:1]    DEBU Creating in-memory backend for [auth]. service/service.go:1555
2021-12-11T20:01:22Z DEBU [BUFFER]    Add Watcher(name=auth:1:cache, prefixes=/access_requests, /appServers/default, /applications, /apps/servers/default, /apps/sessions, /authentication/preference/general, /authorities, /authservers, /cluster_configuration/audit, /cluster_configuration/name, /cluster_configuration/networking, /cluster_configuration/session_recording, /cluster_configuration/static_tokens, /databaseServers/default, /db, /kubeServices, /locks, /namespaces, /nodes/default, /proxies, /remoteClusters, /restrictions/network, /reverseTunnels, /roles, /tokens, /tunnelConnections, /web/sessions, /web/tokens, /web/users, /windowsDesktop, capacity=8192, size=0). backend/buffer.go:312
2021-12-11T20:01:23Z DEBU [SQLITE]    Initialized event ID iterator to 79 lite/periodic.go:149
2021-12-11T20:01:23Z INFO [AUTH:1:CA] Cache "auth" first init succeeded. cache/cache.go:676
2021-12-11T20:01:23Z [PROC:1]    INFO Service auth is creating new listener on 0.0.0.0:3025. service/signals.go:213
2021-12-11T20:01:23Z [AUTH:1]    INFO Starting Auth service with PROXY protocol support. service/service.go:1334
2021-12-11T20:01:23Z DEBU [AUTH]      GRPC(SERVER): keep alive 1m0s count: 3. auth/grpcserver.go:3493
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:auth.tls service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:auth.heartbeat.broadcast service/supervisor.go:201
2021-12-11T20:01:23Z [AUTH:1]    WARN Configuration setting auth_service/advertise_ip is not set. guessing 172.17.0.2:3025. service/service.go:1412
2021-12-11T20:01:23Z DEBU [AUTH:BEAT] Starting Auth heartbeat with announce period: 1m0s, keep-alive period 5m41.079451445s, poll period: 5s srv/heartbeat.go:152
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:auth.heartbeat service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:auth.shutdown service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:register.node service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:ssh.node service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:ssh.shutdown service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:register.proxy service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.init service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:common.rotate service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:auth.shutdown service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:auth.tls service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:ssh.shutdown service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:ssh.node service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU No signal pipe to import, must be first Teleport process. service/service.go:874
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:auth.heartbeat.broadcast service/supervisor.go:262
2021-12-11T20:01:23Z [AUTH:1]    INFO Auth service 8.0.1:v8.0.1-0-gb95fb530b is starting on 172.17.0.2:3025. utils/cli.go:282
2021-12-11T20:01:23Z [PROC:1]    DEBU Broadcasting event. event:AuthTLSReady service/supervisor.go:370
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:proxy.init service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Connected state: never updated. service/connect.go:103
2021-12-11T20:01:23Z [PROC:1]    DEBU Connected client: Identity(Admin, cert(0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost issued by localhost:189250250046672973150827989179581290897),trust root(localhost:189250250046672973150827989179581290897)) service/connect.go:87
2021-12-11T20:01:23Z [PROC:1]    DEBU Broadcasting event. event:AuthIdentity service/supervisor.go:370
2021-12-11T20:01:23Z [PROC:1]    DEBU Adding service to supervisor. service:auth.broadcast service/supervisor.go:201
2021-12-11T20:01:23Z [PROC:1]    DEBU Service is completed and removed. service:auth.heartbeat.broadcast service/supervisor.go:239
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:auth.broadcast service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:register.proxy service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:auth.heartbeat service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Connected state: never updated. service/connect.go:103
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:common.rotate service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Service has started. service:register.node service/supervisor.go:262
2021-12-11T20:01:23Z [PROC:1]    DEBU Connected state: never updated. service/connect.go:103
2021-12-11T20:01:23Z [PROC:1]    INFO Connecting to the cluster localhost with TLS client certificate. service/connect.go:132
2021-12-11T20:01:23Z [PROC:1]    DEBU Attempting to connect to Auth Server directly. auth-addrs:[0.0.0.0:3025] service/connect.go:835
2021-12-11T20:01:23Z [PROC:1]    INFO Connecting to the cluster localhost with TLS client certificate. service/connect.go:132
2021-12-11T20:01:23Z [PROC:1]    DEBU Attempting to connect to Auth Server directly. auth-addrs:[0.0.0.0:3025] service/connect.go:835
2021-12-11T20:01:23Z DEBU [AUTH]      ClientCertPool -> cert(localhost issued by localhost:189250250046672973150827989179581290897) auth/middleware.go:619
2021-12-11T20:01:23Z DEBU [AUTH]      ClientCertPool -> cert(localhost issued by localhost:226743188425627352627073062014398200809) auth/middleware.go:619
2021-12-11T20:01:23Z DEBU [AUTH:1]    Server certificate cert(0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost issued by localhost:189250250046672973150827989179581290897). auth/middleware.go:300
2021-12-11T20:01:23Z DEBU [AUTH]      ClientCertPool -> cert(localhost issued by localhost:189250250046672973150827989179581290897) auth/middleware.go:619
2021-12-11T20:01:23Z DEBU [AUTH]      ClientCertPool -> cert(localhost issued by localhost:226743188425627352627073062014398200809) auth/middleware.go:619
2021-12-11T20:01:23Z DEBU [AUTH:1]    Server certificate cert(0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost issued by localhost:189250250046672973150827989179581290897). auth/middleware.go:300
2021-12-11T20:01:23Z DEBU [AUTH]      ClientCertPool -> cert(localhost issued by localhost:189250250046672973150827989179581290897) auth/middleware.go:619
2021-12-11T20:01:23Z DEBU [AUTH]      ClientCertPool -> cert(localhost issued by localhost:226743188425627352627073062014398200809) auth/middleware.go:619
2021-12-11T20:01:23Z DEBU [AUTH:1]    Server certificate cert(0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost issued by localhost:189250250046672973150827989179581290897). auth/middleware.go:300
2021-12-11T20:01:23Z DEBU [AUTH]      ClientCertPool -> cert(localhost issued by localhost:189250250046672973150827989179581290897) auth/middleware.go:619
2021-12-11T20:01:23Z DEBU [AUTH]      ClientCertPool -> cert(localhost issued by localhost:226743188425627352627073062014398200809) auth/middleware.go:619
2021-12-11T20:01:23Z DEBU [AUTH:1]    Server certificate cert(0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost issued by localhost:189250250046672973150827989179581290897). auth/middleware.go:300
2021-12-11T20:01:23Z [PROC:1]    DEBU Connected to Auth Server with direct connection. auth-addrs:[0.0.0.0:3025] service/connect.go:838
2021-12-11T20:01:23Z [PROC:1]    DEBU Connected client: Identity(Proxy, cert(0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost issued by localhost:189250250046672973150827989179581290897),trust root(localhost:189250250046672973150827989179581290897)) service/connect.go:87
2021-12-11T20:01:23Z [PROC:1]    INFO Proxy: features loaded from auth server: Kubernetes:true App:true DB:true  service/connect.go:59
2021-12-11T20:01:23Z [PROC:1]    DEBU Broadcasting event. event:ProxyIdentity service/supervisor.go:370
2021-12-11T20:01:23Z [PROC:1]    DEBU Service is completed and removed. service:register.proxy service/supervisor.go:239
2021-12-11T20:01:23Z [PROC:1]    DEBU Received event "ProxyIdentity". service/service.go:2491
2021-12-11T20:01:23Z [PROC:1]    DEBU Creating sqlite backend for [proxy]. service/service.go:1566
2021-12-11T20:01:23Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/cache/proxy/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 100ms lite/lite.go:172
2021-12-11T20:01:23Z [PROC:1]    DEBU Connected to Auth Server with direct connection. auth-addrs:[0.0.0.0:3025] service/connect.go:838
2021-12-11T20:01:23Z [PROC:1]    DEBU Connected client: Identity(Node, cert(0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost issued by localhost:189250250046672973150827989179581290897),trust root(localhost:189250250046672973150827989179581290897)) service/connect.go:87
2021-12-11T20:01:23Z DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
2021-12-11T20:01:23Z [PROC:1]    INFO Node: features loaded from auth server: Kubernetes:true App:true DB:true  service/connect.go:59
2021-12-11T20:01:23Z [PROC:1]    DEBU Broadcasting event. event:SSHIdentity service/supervisor.go:370
2021-12-11T20:01:23Z [PROC:1]    DEBU Service is completed and removed. service:register.node service/supervisor.go:239
2021-12-11T20:01:23Z [NODE:1]    DEBU Received event "SSHIdentity". service/service.go:1804
2021-12-11T20:01:23Z [PROC:1]    DEBU Creating sqlite backend for [node]. service/service.go:1566
2021-12-11T20:01:23Z DEBU [SQLITE]    Connected to: file:/var/lib/teleport/cache/node/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 100ms lite/lite.go:172
2021-12-11T20:01:23Z DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
2021-12-11T20:01:23Z INFO [NODE:1:CA] Cache "node" first init succeeded. cache/cache.go:676
2021-12-11T20:01:23Z DEBU [BPF]       Enhanced session recording is not enabled, skipping. bpf/bpf.go:124
2021-12-11T20:01:23Z DEBU [RESTRICTE] Restricted session is not enabled, skipping. restrictedsession/restricted.go:93
2021-12-11T20:01:23Z [NODE:1]    DEBU Starting watch. resource-kind:lock retry:Linear(attempt=0, duration=0s) services/watcher.go:177
2021-12-11T20:01:23Z DEBU [SSH:NODE]  Supported ciphers: ["aes128-gcm@openssh.com" "chacha20-poly1305@openssh.com" "aes128-ctr" "aes192-ctr" "aes256-ctr"]. sshutils/server.go:229
2021-12-11T20:01:23Z DEBU [SSH:NODE]  Supported KEX algorithms: ["curve25519-sha256@libssh.org" "ecdh-sha2-nistp256" "ecdh-sha2-nistp384" "ecdh-sha2-nistp521"]. sshutils/server.go:239
2021-12-11T20:01:23Z DEBU [SSH:NODE]  Supported MAC algorithms: ["hmac-sha2-256-etm@openssh.com" "hmac-sha2-256"]. sshutils/server.go:249
2021-12-11T20:01:23Z DEBU [NODE:BEAT] Starting Node heartbeat with announce period: 1m0s, keep-alive period 5m3.581658398s, poll period: 5s srv/heartbeat.go:152
2021-12-11T20:01:23Z [PROC:1]    INFO Service node is creating new listener on 0.0.0.0:3022. service/signals.go:213
2021-12-11T20:01:23Z [NODE:1]    INFO Service 8.0.1:v8.0.1-0-gb95fb530b is starting on 0.0.0.0:3022 sqlite cache will store frequently accessed items. service/service.go:1977
2021-12-11T20:01:23Z [NODE:1]    INFO Service 8.0.1:v8.0.1-0-gb95fb530b is starting on 0.0.0.0:3022. utils/cli.go:282
2021-12-11T20:01:23Z [PROC:1]    DEBU Broadcasting event. event:NodeReady service/supervisor.go:370
2021-12-11T20:01:23Z DEBU [SSH:NODE]  Listening on [::]:3022. sshutils/server.go:382
2021-12-11T20:01:23Z DEBU [AUTH:GRPC] Got heartbeat connection from 0a25db4c-ba1a-44dd-a2b3-2b76d26539b2.localhost. auth/grpcserver.go:129
2021-12-11T20:01:23Z INFO [PROXY:1:C] Cache "proxy" first init succeeded. cache/cache.go:676
2021-12-11T20:01:23Z [PROC:1]    DEBU Setup Proxy: Web Proxy Address: 0.0.0.0:3080, Reverse Tunnel Proxy Address:  service/service.go:2576
2021-12-11T20:01:23Z [PROC:1]    DEBU Setup Proxy: Proxy and reverse tunnel are listening on separate ports. service/service.go:2663
2021-12-11T20:01:23Z [PROC:1]    INFO Service proxy:web is creating new listener on 0.0.0.0:3080. service/signals.go:213
2021-12-11T20:01:23Z [PROC:1]    DEBU Setup Proxy: TLS is disabled, multiplexing is off. service/service.go:2699
2021-12-11T20:01:23Z [PROXY]     DEBU Starting watch. resource-kind:lock retry:Linear(attempt=0, duration=0s) services/watcher.go:177
2021-12-11T20:01:23Z WARN [PROXY:1:C] Re-init the cache on error: watcher is closed: rpc error: code = Canceled desc = grpc: the client connection is closing. cache/cache.go:725
2021-12-11T20:01:23Z [PROC:1]    WARN Teleport process has exited with error. error:[
ERROR REPORT:
Original Error: *trace.BadParameterError missing parameter Listener
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:219 github.com/gravitational/teleport/lib/reversetunnel.(*Config).CheckAndSetDefaults
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:267 github.com/gravitational/teleport/lib/reversetunnel.NewServer
        /go/src/github.com/gravitational/teleport/lib/service/service.go:2805 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint
        /go/src/github.com/gravitational/teleport/lib/service/service.go:2502 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxy.func1
        /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:494 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
        /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:263 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: missing parameter Listener] service:proxy.init service/supervisor.go:268
2021-12-11T20:01:23Z DEBU [PROXY:1:C] Reloading Linear(attempt=0, duration=0s). cache/cache.go:728
2021-12-11T20:01:23Z [PROC:1]    DEBU Broadcasting event. event:ServiceExitedWithError service/supervisor.go:370
2021-12-11T20:01:23Z WARN [PROXY:1:C] Re-init the cache on error: rpc error: code = Canceled desc = grpc: the client connection is closing. cache/cache.go:725
2021-12-11T20:01:23Z DEBU [PROXY:1:C] Reloading Linear(attempt=1, duration=1s). cache/cache.go:728
2021-12-11T20:01:23Z [PROC:1]    DEBU Service is completed and removed. service:proxy.init service/supervisor.go:239
2021-12-11T20:01:23Z [PROXY]     WARN Restart watch on error: watcher is closed. resource-kind:lock services/watcher.go:203
2021-12-11T20:01:23Z [PROC:1]    ERRO Critical service proxy.init has exited with error missing parameter Listener, aborting. service/signals.go:144
2021-12-11T20:01:23Z DEBU [AUTH:BEAT] Heartbeat exited. srv/heartbeat.go:278
2021-12-11T20:01:23Z [PROC:1]    DEBU Broadcasting event. event:TeleportExit service/supervisor.go:370
2021-12-11T20:01:23Z DEBU [PROXY:1:C] Cache is closing, returning from update loop. cache/cache.go:709
2021-12-11T20:01:23Z [PROC:1]    DEBU Service is completed and removed. service:common.rotate service/supervisor.go:239
2021-12-11T20:01:23Z DEBU [NODE:1:CA] Cache is closing, returning from update loop. cache/cache.go:709
2021-12-11T20:01:23Z [PROC:1]    DEBU Service is completed and removed. service:auth.heartbeat service/supervisor.go:239
2021-12-11T20:01:23Z [PROXY]     DEBU Starting watch. resource-kind:lock retry:Linear(attempt=1, duration=1s) services/watcher.go:177
2021-12-11T20:01:23Z WARN [NODE:1:CA] Failed to set tombstone: database is closed cache/cache.go:750
2021-12-11T20:01:23Z DEBU [AUTH:1:CA] Cache is closing, returning from update loop. cache/cache.go:709
2021-12-11T20:01:23Z [AUTH:1]    INFO Shutting down immediately. service/service.go:1469
2021-12-11T20:01:23Z DEBU [BUFFER]    Removing watcher 0xc000b88000 via external close. backend/buffer.go:330
2021-12-11T20:01:23Z [NODE:1]    INFO Shutting down immediately. service/service.go:2035
2021-12-11T20:01:23Z DEBU [AUTH:GRPC] Failed to receive heartbeat: rpc error: code = Canceled desc = context canceled auth/grpcserver.go:139
2021-12-11T20:01:23Z [AUTH:1]    INFO Exited. service/service.go:1484

ERROR REPORT:
Original Error: *trace.BadParameterError missing parameter Listener
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:219 github.com/gravitational/teleport/lib/reversetunnel.(*Config).CheckAndSetDefaults
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/srv.go:267 github.com/gravitational/teleport/lib/reversetunnel.NewServer
        /go/src/github.com/gravitational/teleport/lib/service/service.go:2805 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint
        /go/src/github.com/gravitational/teleport/lib/service/service.go:2502 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxy.func1
        /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:494 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
        /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:263 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
        /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: missing parameter Listener
2021-12-11T20:01:23Z [AUTH:1]    WARN TLS server exited with error: http: Server closed. service/service.go:1367
2021-12-11T20:01:23Z DEBU [BUFFER]    Removing watcher 0xc000a04000 via external close. backend/buffer.go:330
```

### LINKED ISSUE #24310: Teleport crashed with nil pointer error when giving '--insecure-no-tls' option without setting 'tunnel_listen_addr'
### Expected behavior

The program should not crash due to a nil pointer reference error.

### Current behavior

Teleport crashed with nil pointer error when giving '--insecure-no-tls' option without setting 'tunnel_listen_addr' flag. I have attached a config file that reproduces the error.

Bug details:

- Teleport version
  12.1.2

### Recreation steps

Set the `/etc/teleport.yaml` file to the following configuration and run the `teleport start --insecure-no-tls` command.

```yaml
version: v3
teleport:
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:xxxxxxxxxxxxxxxxxxxx
  diag_addr: ""
  auth_server: my-auth-server:3025
  auth_token: my-token
auth_service:
  enabled: "no"
  proxy_listener_mode: multiplex
proxy_service:
  enabled: "yes"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
  public_addr: mine.teleport.com:443
  web_listen_addr: "0.0.0.0:443"
  mysql_listen_addr: "0.0.0.0:3306"
```

### Debug logs

```
2023-04-08T12:49:43Z DEBU [PROC:1]    Service has started. pid:29859.1 service:proxy.reversetunnel.server service/supervisor.go:275
2023-04-08T12:49:43Z INFO [PROXY:SER] Reverse tunnel service 12.1.2:api/v12.1.2-0-gbfd4ff0 is starting on . pid:29859.1 utils/cli.go:286
2023-04-08T12:49:43Z INFO [PROXY:SER] Starting 12.1.2:api/v12.1.2-0-gbfd4ff0 on  using in-memory cache pid:29859.1 service/service.go:3500
2023-04-08T12:49:43Z DEBU [PROC:1]    Broadcasting event. event:ProxyReverseTunnelReady pid:29859.1 service/supervisor.go:383
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x168d464]

goroutine 301 [running]:
github.com/gravitational/teleport/lib/limiter.(*Listener).Addr(0x5fc8f7?)
        <autogenerated>:1 +0x24
github.com/gravitational/teleport/lib/sshutils.(*Server).Addr(0x3acde5cb?)
        github.com/gravitational/teleport/lib/sshutils/server.go:312 +0x92
github.com/gravitational/teleport/lib/sshutils.(*Server).acceptConnections(0xc000179600)
        github.com/gravitational/teleport/lib/sshutils/server.go:409 +0x5b
github.com/gravitational/teleport/lib/sshutils.(*Server).Serve(0xc000090fd0?, {0x760a740?, 0xc001504768?})
        github.com/gravitational/teleport/lib/sshutils/server.go:319 +0x69
created by github.com/gravitational/teleport/lib/reversetunnel.(*server).Start
        github.com/gravitational/teleport/lib/reversetunnel/srv.go:592 +0xa5
jenkins@teleport-pro-proxy:~$ sudo service teleport start
```

### Cause of the bug

The code wrapping the reverse tunnel listener is not validating that the embedded listener is nil. 

https://github.com/gravitational/teleport/blob/40c113b8dad017613c154efaa16997a186eec7fb/lib/limiter/listener.go#L34-L39

The wrapped structure does not implement all the methods of net.Listener and delegates some of them to the embedded member.

https://github.com/gravitational/teleport/blob/40c113b8dad017613c154efaa16997a186eec7fb/lib/limiter/listener.go#L26-L29

Because the structure is not nil, it passes the defense code, but when you try to call a method implemented by the embedded member, you encounter a nil pointer reference.

https://github.com/gravitational/teleport/blob/e667486c31144de1f3180062235c3c0859106e92/lib/sshutils/server.go#L337-L340

### How to fix it

Consider modifying the `NewListener` function to look like this:

```go
func NewListener(ln net.Listener, limiter *ConnectionsLimiter) *Listener {
        if ln == nil || limiter == nil {
            return nil
        }
	return &Listener{
		Listener: ln,
		limiter:  limiter,
	}
}
```

This will make the defense code work properly. I'll make a pull request if my suggestion is accepted.

### PR DESCRIPTION
**Pull request by Joerger**
Fixes https://github.com/gravitational/teleport/issues/24310

Note: this does not fix https://github.com/gravitational/teleport/issues/9350, which should be solved with better detection/errors around what listeners are necessary and missing.

### CODE REVIEW

File: lib/limiter/limiter.go [hunk 1]
```diff
@@ -180,7 +180,10 @@ func (l *Limiter) StreamServerInterceptor(srv interface{}, serverStream grpc.Ser
 
 // WrapListener returns a [Listener] that wraps the provided listener
 // with one that limits connections
-func (l *Limiter) WrapListener(ln net.Listener) *Listener {
+func (l *Limiter) WrapListener(ln net.Listener) net.Listener {
```
Comment (zmb3) [inline lib/limiter/limiter.go:183]: Should we be adding nil checks at the call-site now?

Comment (Joerger) [reply lib/limiter/limiter.go]: Changed `WrapListener` to return an error instead.

**Review by espadolini — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]
