### PR TITLE
tsh: Silent webauthnwin warning on app init

### LINKED ISSUE #22833: tsh on windows reports errors about missing webauthn.dll
The warnings are shown even when mfa isn't being used:

```bash
tsh.exe version
time="2023-03-09T13:42:24Z" level=warning msg="WebAuthnWin: failed to check version" error="A device attached to the system is not functioning."
Teleport v12.1.0 git:api/v12.1.0-0-g49a6de744a go1.19.6
```

When establishing a session via `tsh ssh` or Connect the warning is also present even though mfa is successful.

### PR DESCRIPTION
**Pull request by tobiaszheller**
Previously if webauthn.dll is missing on windows machine, we will print warning on every command.

This PR changes warning to debug. Additionally if someone tried to login/register via local auth, if dll is missing, we will print warning.

Fixes: https://github.com/gravitational/teleport/issues/22833

### CODE REVIEW

File: lib/auth/webauthnwin/api.go [hunk 1]
```diff
@@ -188,7 +190,12 @@ type CheckSupportResult struct {
 // false positives.
 // See CheckSupport.
 func IsAvailable() bool {
-	return CheckSupport().IsAvailable
+	supports := CheckSupport()
+	if supports.HasCompileSupport && !supports.IsAvailable {
+		log.Warn("WebAuthnWin: not supported on your windows version, supported from version 1903")
```
Comment (codingllama) [inline lib/auth/webauthnwin/api.go:195]: Should we wrap this in a sync.Once to avoid spamming if the flow changes?

**Review by codingllama — APPROVED** [review]

File: lib/auth/webauthnwin/api.go (hunk 1 above)
Comment (tobiaszheller) [reply lib/auth/webauthnwin/api.go:195]: i was thinking about that, but execution via tsh will mostly call it just once, because we execute single command and exit, right?

Comment (zmb3) [inline lib/auth/webauthnwin/api.go:195]:
```suggestion
		log.Warn("Webauthn is not supported on this version of Windows, supported from version 1903")
```

**Review by zmb3 — APPROVED** [review]

File: lib/auth/webauthnwin/api.go [hunk 2]
```diff
@@ -188,7 +189,12 @@ type CheckSupportResult struct {
 // false positives.
 // See CheckSupport.
 func IsAvailable() bool {
-	return CheckSupport().IsAvailable
+	supports := CheckSupport()
+	if supports.HasCompileSupport && !supports.IsAvailable {
+		log.Warn("Webauthn is not supported on this version of Windows, supported from version 1903")
```
Comment (codingllama) [inline lib/auth/webauthnwin/api.go:194]:
```suggestion
		log.Warn("Webauthn is not supported on this version of Windows, it requires Windows 10 version 1903 or newer")
```

Right?

File: lib/auth/webauthnwin/api.go (hunk 1 above)
Comment (codingllama) [reply lib/auth/webauthnwin/api.go]: I think so too. Your call.

File: lib/auth/webauthnwin/api.go (hunk 2 above)
Comment (tobiaszheller) [reply lib/auth/webauthnwin/api.go:194]: we just learned that webauthn.dll is also present on windows server. And 1903 is valid version of windows server:
> Windows Server, version 1903 (unsupported as of December 8, 2020; 2 years ago)

so maybe we can leave it without windows10 info.

Comment (codingllama) [reply lib/auth/webauthnwin/api.go:194]: Could we say "Windows 10 or Windows Server, version 1903"? Would that be correct?

Feel free to ignore if you think that makes is worse.
