### PR TITLE
Fix access to leaf resources

### LINKED ISSUE #25619: Desktop Access Per-session MFA not working with 12.3.1
Expected behavior:
Per-session MFA box should appear

Current behavior:
Teleport displays message "desktopnot found"
image

Following error is being displayed in the legs of Desktop GW:
image

Bug details:
- Teleport version
12.3.1
- Recreation steps
Set-up teleport cluster with 12.3.1, WebAuthN MFA and enable Per-session MFA for a role for Desktop Access.
- Debug logs
see attached file

### PR DESCRIPTION
**Pull request by rosstimothy**
The MFA required check added to the Auth server in
https://github.com/gravitational/teleport/pull/24250 is now
only performed if the `RouteToCluster` indicates that the request
is for the local cluster and not a remote cluster. When the root
cluster checks if mfa is required to a resource in another cluster
it would always return a not found error since the resource didn't
exist in the root backend. This results in the behavior described
in https://github.com/gravitational/teleport/issues/25619.

This step is now skipped for any resources in another cluster to allow
certificates for remote cluster resources to be generated by the root.
`tsh` detects that a resource is in a leaf cluster and will first call
`proto.AuthService/IsMFARequired` on the leaf cluster before requesting
certificates from the root cluster to prevent a user from being
prompted to complete an MFA ceremony if one is not required.

Closes https://github.com/gravitational/teleport/issues/25619

### CODE REVIEW

**Review by ibeckermayer — APPROVED** [review]

File: lib/web/terminal.go [hunk 1]
```diff
@@ -732,14 +733,22 @@ func (t *TerminalHandler) connectToHost(ctx context.Context, ws *websocket.Conn,
...
+	// if MFA is required, take precedent over MFA errors due to users not having any
+	// enrolled devices.
+	case !trace.IsAccessDenied(directErr) && errors.Is(mfaErr, auth.ErrNoMFADevices):
+		return nil, trace.Wrap(directErr)
+	case !errors.Is(mfaErr, io.EOF) && // Ignore any errors from MFA due to locks being enforced, the direct error will be friendlier
+		!errors.Is(mfaErr, client.MFARequiredUnknownErr{}) && // Ignore any failures that occurred before determining if MFA was required
+		!errors.Is(mfaErr, services.ErrSessionMFANotRequired): // Ignore any errors caused by attempting the MFA ceremony when MFA will not grant access
 		return nil, trace.Wrap(mfaErr)
+	default:
+		return nil, trace.Wrap(directErr)
```
Comment (ibeckermayer) [inline lib/web/terminal.go:750]: I notice we have this same section twice, is it worth abstracting out into a function?

**Review by capnspacehook — APPROVED** [review]

**Review by nklaassen — APPROVED** [review]

File: lib/auth/grpcserver_test.go [hunk 2]
```diff
@@ -1641,6 +1647,122 @@ func TestGenerateUserSingleUseCert(t *testing.T) {
...
+					require.Equal(t, webDevID, cert.Extensions[teleport.CertExtensionMFAVerified])
+					require.Equal(t, userCertExpires.Format(time.RFC3339), cert.Extensions[teleport.CertExtensionPreviousIdentityExpires])
+					require.True(t, net.ParseIP(cert.Extensions[teleport.CertExtensionLoginIP]).IsLoopback())
+					pinnedIP, ok := cert.CriticalOptions[teleport.CertCriticalOptionSourceAddress]
+					require.True(t, ok)
+					require.Equal(t, "127.0.0.1/32", pinnedIP)
+					require.Equal(t, uint64(clock.Now().Add(teleport.UserSingleUseCertTTL).Unix()), cert.ValidBefore)
+				},
+			},
+		},
```
Comment (ibeckermayer) [inline lib/auth/grpcserver_test.go:1765]: Should we add tests for app/desktop certs?
