### PR TITLE
Fix kube discovery service `poll_interval` value not set correctly

### LINKED ISSUE #52581: poll_interval for the discovery service does not seem to be honored
Expected behavior:

Setting 
```
    discovery_service:
      enabled: true
      poll_interval: 1m
```
Current behavior:

It seems that the default 5mn poll is being enforced

```
│ 2025-02-27T18:18:44.760Z INFO [DISCOVERY] app discovery-app-changed2-websecure matches, creating. kind:app pid:7.1 services/reconciler.go:1 │
│ 2025-02-27T18:18:44.857Z INFO [DISCOVERY] app discovery-app-changed2-web matches, creating. kind:app pid:7.1 services/reconciler.go:167     │
│ 2025-02-27T18:18:46.189Z INFO [APP:SERVI] app discovery-app-changed2-websecure matches, creating. services/reconciler.go:167                │
│ 2025-02-27T18:18:46.189Z INFO [APP:SERVI] app discovery-app-changed2-web matches, creating. services/reconciler.go:167                      │
│ 2025-02-27T18:23:44.757Z INFO [DISCOVERY] app discovery-app-changed2-websecure removed, deleting. kind:app pid:7.1 services/reconciler.go:1 │
│ 2025-02-27T18:23:44.811Z INFO [DISCOVERY] app discovery-app-changed2-web removed, deleting. kind:app pid:7.1 services/reconciler.go:147     │
│ 2025-02-27T18:23:45.136Z INFO [APP:SERVI] app discovery-app-changed2-websecure removed, deleting. services/reconciler.go:147                │
│ 2025-02-27T18:23:45.205Z INFO [APP:SERVI] app discovery-app-changed2-web removed, deleting. services/reconciler.go:147
```

Bug details:
- Teleport version : Agent version  teleport-kube-agent-16.4.16

- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by kshi36**
Fixes #52581

<details><summary>Manual Tests</summary>
<p>

Test: Specify a poll interval not equal to the default value of 5 minutes

- [x]  Verify that before the change, discovery service polls every 5 minutes regardless of `poll_interval` field
- [x]  Verify that after the change, discovery service polls based on value of `poll_interval` field

</p>
</details> 

Examples:

<details><summary>config file</summary>
<p>

```yaml
app_service:
      enabled: true
      resources:
      - labels:
          teleport.dev/kubernetes-cluster: main-cluster
          teleport.dev/origin: discovery-kubernetes
    auth_service:
      enabled: false
    db_service:
      enabled: false
    discovery_service:
      discovery_group: main-cluster
      enabled: true
      kubernetes:
      - labels:
          '*': '*'
        namespaces:
        - '*'
        types:
        - app
      poll_interval: 1m
    jamf_service:
      enabled: false
    kubernetes_service:
      enabled: true
      kube_cluster_name: main-cluster
    proxy_service:
      enabled: false
    ssh_service:
      enabled: false
    teleport:
      join_params:
        method: token
        token_name: /etc/teleport-secrets/auth-token
      log:
        format:
          extra_fields:
          - timestamp
          - level
          - component
          - caller
          output: text
        output: stderr
        severity: INFO
      proxy_server: kevin.dev:443
    version: v3
```

</p>
</details> 

<details><summary>result</summary>
<p>

```
2025-11-14T17:09:18.103Z INFO [DISCOVERY] New resource matches, creating pid:11.1 kind:app kind:app name:dummy-service-no-pods-5-default-main-cluster services/reconciler.go:264
2025-11-14T17:09:18.925Z INFO [APP:SERVI] New resource matches, creating kind:app kind:app name:dummy-service-no-pods-5-default-main-cluster services/reconciler.go:264
2025-11-14T17:10:18.112Z INFO [DISCOVERY] Resource was removed, deleting pid:11.1 kind:app kind:app name:dummy-service-no-pods-5-default-main-cluster services/reconciler.go:219
2025-11-14T17:10:18.925Z INFO [APP:SERVI] Resource was removed, deleting kind:app kind:app name:dummy-service-no-pods-5-default-main-cluster services/reconciler.go:219
```

</p>
</details> 

changelog: Fixed bug where Kubernetes App Discovery `poll_interval` is not set correctly

### CODE REVIEW

**Comment by rosstimothy** [comment]
@kshi36 could you update your PR description with the manual testing that you did to validate this change? See https://github.com/gravitational/teleport/pull/59850 for an example.

File: lib/srv/discovery/discovery_test.go [hunk 1]
```diff
@@ -1302,6 +1300,97 @@ func TestDiscoveryKubeServices(t *testing.T) {
 	}
 }
 
+// TestDiscoveryKubeServicesInterval tests that the poll interval is honored for Kube App Discovery.
+func TestDiscoveryKubeServicesInterval(t *testing.T) {
+	const mainDiscoveryGroup = "main"
+	clock := clockwork.NewFakeClock()
+	waitForReconcileTimeout := 5 * time.Second
+	tickDuration := 200 * time.Millisecond
```
Comment (rosstimothy) [inline lib/srv/discovery/discovery_test.go]: Suggestion: make these constants as well
```suggestion
	const waitForReconcileTimeout = 5 * time.Second
	const tickDuration = 200 * time.Millisecond
```

File: lib/srv/discovery/discovery_test.go [hunk 2]
```diff
@@ -1302,6 +1300,97 @@ func TestDiscoveryKubeServices(t *testing.T) {
...
+	ctx := context.Background()
```
Comment (rosstimothy) [inline lib/srv/discovery/discovery_test.go]: Suggestion: use the test aware context provided by testing.T. See https://pkg.go.dev/testing#T.Context.
```suggestion
	ctx := t.Context()
```

File: lib/srv/discovery/discovery_test.go [hunk 3]
```diff
@@ -1302,6 +1300,97 @@ func TestDiscoveryKubeServices(t *testing.T) {
...
+	// Kubernetes app matcher
+	kubernetesMatchers := []types.KubernetesMatcher{
+		{
+			Types:      []string{"app"},
+			Namespaces: []string{types.Wildcard},
+			Labels:     map[string]utils.Strings{"test-label": {"testval"}},
+		},
+	}
+
+	pollInterval := 1 * time.Minute
```
Comment (rosstimothy) [inline lib/srv/discovery/discovery_test.go]: Suggestion: make this a constant
```suggestion
	const pollInterval = 1 * time.Minute
```

File: lib/srv/discovery/discovery_test.go [hunk 4]
```diff
@@ -1302,6 +1300,97 @@ func TestDiscoveryKubeServices(t *testing.T) {
...
+		require.NoError(t, err)
+		require.Len(t, existingApps, 1)
+	}, waitForReconcileTimeout, tickDuration)
+
+	// After deleting in auth server, should have no apps
+	err = tlsServer.Auth().DeleteApp(ctx, app1.GetName())
+	require.NoError(t, err)
+	actualApps, err := tlsServer.Auth().GetApps(ctx)
+	require.NoError(t, err)
+	require.Empty(t, actualApps)
```
Comment (rosstimothy) [inline lib/srv/discovery/discovery_test.go]: Are deleted apps guaranteed to be removed instantaneously? Should this also be wrapped in a require.EventuallyWithT?

File: lib/srv/discovery/discovery_test.go [hunk 5]
```diff
@@ -1302,6 +1300,97 @@ func TestDiscoveryKubeServices(t *testing.T) {
...
+
+	clock.Advance(pollInterval)
```
Comment (rosstimothy) [inline lib/srv/discovery/discovery_test.go]: How do we know that the consumer of this clock is blocked and will see the time change? Should we verify that with [clock.BlockUntil](https://pkg.go.dev/github.com/jonboulle/clockwork#FakeClock.BlockUntilContext)? Should/Can we rewrite this test to leverage [synctest](https://pkg.go.dev/testing/synctest)?

Comment (kshi36) [reply lib/srv/discovery/discovery_test.go]: I am unsure about the blocking behavior (via `clock.BlockUntil`), since multiple discovery services start up when creating the Discovery Server `discServer` (`kind=app, kind=kube_cluster, kind=db`).

However, for the particular discovery service being tested (`kind=app`), if the watcher timer's `Interval` is not met, then the discovery is not reconciled/polled and the test fails. I have verified this with a smaller `clock.Advance` time, and can add an extra assert for this case. I also verified the fake clock is passed down to the target code.

<details><summary>Target code</summary>
<p>

```go
// Start starts fetching cloud resources and sending them to the channel.
func (w *Watcher) Start() {
	pollTimer := w.cfg.Clock.NewTimer(w.cfg.Interval)
	defer pollTimer.Stop()
	w.cfg.Logger.InfoContext(w.ctx, "Starting watcher")
	w.fetchAndSend()
	for {
		select {
		case <-pollTimer.Chan():
			w.cfg.Logger.InfoContext(w.ctx, "Poll interval met")
			w.fetchAndSend()
			pollTimer.Reset(w.cfg.Interval)

		case <-w.cfg.TriggerFetchC:
			w.fetchAndSend()

			// stop and drain timer
			if !pollTimer.Stop() {
				<-pollTimer.Chan()
			}
			pollTimer.Reset(w.cfg.Interval)

		case <-w.ctx.Done():
			w.cfg.Logger.InfoContext(w.ctx, "Watcher done")
			return
		}
	}
}
```

</p>
</details> 

Within unit tests in `watcher_test.go`, I notice similar testing behavior without adding a `clock.BlockUntil`, which may also encounter a similar problem (or not)? I will look into synctest to see if that is a more intended approach. Perhaps migrating to synctest should be looked at in a future PR as well?

Comment (rosstimothy) [reply lib/srv/discovery/discovery_test.go]: Given that this is a brand new test I think it would be best to investigate this more to ensure the test won't become flaky.

File: lib/srv/discovery/discovery_eks_test.go [hunk 6]
```diff
@@ -372,6 +372,22 @@ func (m *mockAuthServer) RangeDatabases(ctx context.Context, start, end string)
...
+}
+
+func (m *mockAuthServer) ListApps(ctx context.Context, limit int, startKey string) ([]types.Application, string, error) {
+	return nil, "", nil
+}
+
+func (m *mockAuthServer) RangeApps(ctx context.Context, start, end string) iter.Seq2[types.Application, error] {
+	return func(yield func(types.Application, error) bool) {}
+}
+
```
Comment (kshi36) [inline lib/srv/discovery/discovery_eks_test.go]: Currently, I have extended the `mockAuthServer` implementation here for use in my test in `discovery_test.go`, since it contains similar logic for my usage with `synctest`. I felt this was the best way to write the test without interfering with existing test logic in `discovery_test.go`. I specifically needed the functionality of a mock AccessPoint to eliminate non-durably blocking gRPC calls that impact `synctest`.

In a future PR, I want to migrate everything in `discovery_eks_test.go` back to `discovery_test.go`, and modify existing tests to utilize `synctest` (and use the same `mockAuthServer` implementation), but this would be extra scope not intended for this PR.

File: lib/srv/discovery/discovery_test.go [hunk 7]
```diff
@@ -1302,6 +1303,75 @@ func TestDiscoveryKubeServices(t *testing.T) {
...
+			Types:      []string{"app"},
+			Namespaces: []string{types.Wildcard},
+			Labels:     map[string]utils.Strings{"test-label": {"testval"}},
+		},
+	}
+
+	synctest.Test(t, func(t *testing.T) {
+		ctx := t.Context()
+
+		fakeKubeClient := fake.NewSimpleClientset(mockKubeServices[0])
```
Comment (rosstimothy) [inline lib/srv/discovery/discovery_test.go]: Can we use `fake.NewClientset` instead of the deprecated `fake.NewSimpleClientset` here?

File: lib/srv/discovery/discovery_eks_test.go [hunk 8]
```diff
@@ -372,6 +372,22 @@ func (m *mockAuthServer) RangeDatabases(ctx context.Context, start, end string)
 	return stream.Empty[types.Database]()
 }
 
+func (f *mockAuthServer) CreateApp(ctx context.Context, _ types.Application) error {
```
Comment (rosstimothy) [inline lib/srv/discovery/discovery_eks_test.go]: All other receiver methods are `m` not `f`. 
```suggestion
func (m *mockAuthServer) CreateApp(ctx context.Context, _ types.Application) error {
```

File: lib/srv/discovery/discovery_test.go [hunk 9]
```diff
@@ -1302,6 +1303,75 @@ func TestDiscoveryKubeServices(t *testing.T) {
...
+
+		bk, err := memory.New(memory.Config{})
+		require.NoError(t, err)
+		mockAccessPoint := &mockAuthServer{
+			events: local.NewEventsService(bk),
+		}
```
Comment (rosstimothy) [inline lib/srv/discovery/discovery_test.go:1334]: This backend is only created so that watchers can be subscribed, however, since nothing else uses this backend no events will ever be emitted. I think we should improve this while we are here to create a new `fakeWatcher` type that is always returned by `(m *mockAuthServer) NewWatcher`.

```go
type mockAuthServer struct {
	authclient.DiscoveryAccessPoint

	storeDiscoveryConfigs map[string]*discoveryconfig.DiscoveryConfig
	storeUserTasks        map[string]*usertasksv1.UserTask

	usageEvents []*proto.SubmitUsageEventRequest

	enrollEKSClusters func(context.Context, *integrationpb.EnrollEKSClustersRequest, ...grpc.CallOption) (*integrationpb.EnrollEKSClustersResponse, error)
}


type fakeWatcher struct {
	done     chan struct{}
	events   chan types.Event
	doneOnce sync.Once
}

func (f *fakeWatcher) Events() <-chan types.Event {
	return f.events
}

func (f *fakeWatcher) Close() error {
	f.doneOnce.Do(func() {
		close(f.done)
		close(f.events)
	})
	return nil
}

func (f *fakeWatcher) Error() error {
	return nil
}

func (f *fakeWatcher) Done() <-chan struct{} {
	return f.done
}

func (m *mockAuthServer) NewWatcher(ctx context.Context, watch types.Watch) (types.Watcher, error) {
	w := &fakeWatcher{
		done:   make(chan struct{}),
		events: make(chan types.Event, 1),
	}

	w.events <- types.Event{
		Type: types.OpInit,
	}
	return w, nil
}
```

**Review by rosstimothy — COMMENTED** [review]
Thanks for taking the time to convert the new test to use synctest @kshi36! The changes look good and I've validated them locally as well, just a few further comments I'd like to see addressed before approving.

**Review by rosstimothy — APPROVED** [review]
Nice work @kshi36!

**Comment by kshi36** [comment]
It seems that converting the deprecated `fake.NewSimpleClientset()` to `fake.NewClientset()` introduced flakiness, unless there's something else I'm missing. I will consider reverting previous tests to the old call

**Comment by rosstimothy** [comment]
> It seems that converting the deprecated `fake.NewSimpleClientset()` to `fake.NewClientset()` introduced flakiness, unless there's something else I'm missing. I will consider reverting previous tests to the old call

Using NewClientset is not the source of the flakiness, the number of locations that have been modified to use it is. The Flaky Test Detector runs all _modified_ tests N times and expects them to complete in M seconds. You've modified so many tests that they no cannot complete fast enough.

We can either change these one test at a time, or we can bypass the flaky test detector on this PR as is.

**Comment by kshi36** [comment]
> We can either change these one test at a time, or we can bypass the flaky test detector on this PR as is.

Thank you for the explanation. I was wondering if it was something particular with the flaky test detector, or that I couldn't track flakiness from my local tests passing

**Comment by kshi36** [comment]
Friendly ping @r0mant @bernardjkim @kopiczko

**Review by r0mant — APPROVED** [review]
3 line fix + 80 lines of tests. Love it!

**Review by bernardjkim — APPROVED** [review]

**Comment by kshi36** [comment]
@rosstimothy Was the bypassing flaky test detector successful?

**Comment by rosstimothy** [comment]
@kshi36 you have to rerun the action for it to see the exclusion comment.
