### PR TITLE
Disables kubeconfig update on `tsh login` when `--kube-cluster` is empty

### LINKED ISSUE #9718: tsh login changes kubeconfig context when no kubernetes clusters are configured in teleport
### Description

**What happened**:
Logging into fresh Teleport cluster updated my kubeconfig with additional cluster, context, and user as well as changing my `current-context`. If I have a kubernetes cluster configured in the Teleport cluster, my `current-context` does _not_ change as is expected when using `tsh login`. 
**What you expected to happen**:
No modification to my kubeconfig or `current-context`. https://github.com/gravitational/teleport/issues/6045

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Have a kubeconfig setup with certificate authentication to k8s cluster
2. Create Teleport cluster and user
3. Login with `tsh login` and see that kubeconfig is updated with change to `current-context`

### Server Details
- Teleport version (run `teleport version`): Teleport v8.0.7 git:v8.0.7-0-geb8076446 go1.17.3
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated hardware 
- Additional details: Teleport is running as a pod in a k8s cluster

### Client Details
- Tsh version (`tsh version`): Teleport v8.0.0 git:v8.0.0-0-g6720c97e9 go1.17.3
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

<details>
  <summary>tsh login with debug</summary>

```
➜ tsh login --proxy=test-teleport.carsonanderson.net:443 --user=randerson --debug
DEBU [CLIENT]    open /Users/randerson/.tsh/test-teleport.carsonanderson.net.yaml: no such file or directory client/api.go:733
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/teleport.carsonanderson.net/rcanderson23-x509.pem" valid until "2022-01-10 15:52:35 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Reading certificates from path "/Users/randerson/.tsh/keys/teleport.carsonanderson.net/rcanderson23-ssh/teleport.carsonanderson.net-cert.pub". client/keystore.go:303
INFO [CLIENT]    no host login given. defaulting to randerson client/api.go:1071
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.hEoZvro7jj/Listeners" client/api.go:2881
DEBU [CLIENT]    not using loopback pool for remote proxy addr: test-teleport.carsonanderson.net:443 client/api.go:2842
DEBU             Attempting GET test-teleport.carsonanderson.net:443/webapi/ping webclient/webclient.go:62
Enter password for Teleport user randerson:
Enter your OTP token:
708397
DEBU [CLIENT]    not using loopback pool for remote proxy addr: test-teleport.carsonanderson.net:443 client/api.go:2842
DEBU [CLIENT]    HTTPS client init(proxyAddr=test-teleport.carsonanderson.net:443, insecure=false) client/weblogin.go:221
DEBU [KEYAGENT]  Adding CA key for test-teleport.carsonanderson.net client/keyagent.go:302
DEBU [KEYSTORE]  Adding known host test-teleport.carsonanderson.net with proxy test-teleport.carsonanderson.net and key: SHA256:/EmSHKGztjLDIuWuviNdI4fMHCY2vGoXVHavxQaJW64 client/keystore.go:541
ERRO [KEYSTORE]  open /Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson: no such file or directory client/keystore.go:243
INFO [KEYAGENT]  Loading SSH key for user "randerson" and cluster "test-teleport.carsonanderson.net". client/keyagent.go:180
INFO [CLIENT]    Connecting proxy=test-teleport.carsonanderson.net:3080 login="root" client/api.go:2099
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAgcxLXLt+YV18GvxYI7ADjzPowaG0XYEmsC+gjz4aeFjoAAAADAQABAAABAQDtpQqiMR8c/aknwW+zpa0Bz3zNRKOcs608zVv70s9KE+BC0Z0M0l+cGbAgx+FN46EZNDuPT
inF5ZEmGeXMW2QZYS4GaQ+qMMzZQJUS7DU8wk4cw1BZZZ2szKD7rL/ok6CDQFlbmd0dSii8QPG4u+Y4K9AS+Zrq8EYUvYEArG7bIvrYN+gxwPRsgvK3WVeQlHI6gQUR2V+Gkepu6VyGWXW6ooZaNdhKqH219I2gFEj7bxZUfPtiQDLrZpgRhqvNKxx4MkkuEEeNdLC7ZRzYaVNEButbnbA93zHFPDuI/qcQw+DbeTh86lZ
vUpYbaYQeGCTA33SVU36sE1bInbElOdORAAAAAAAAAAAAAAACAAAAAAAAATsAAABFNTZmYWZkMjYtZWY4YS00ZGMxLWFkZjEtZGEzM2Y5MGNmMjhmLnRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAJDU2ZmFmZDI2LWVmOGEtNGRjMS1hZGYxLWRhMzNmOTBjZjI4ZgAAADl0ZWxlcG9ydC04ZGRmZDQ5N
jctMmtrenYudGVzdC10ZWxlcG9ydC5jYXJzb25hbmRlcnNvbi5uZXQAAAAYdGVsZXBvcnQtOGRkZmQ0OTY3LTJra3p2AAAACWxvY2FsaG9zdAAAAAkxMjcuMC4wLjEAAAADOjoxAAAAIHRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9
jYWwAAAAAYdx+8f//////////AAAAAAAAAGAAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAkAAAAIHRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAD3gtdGVsZXBvcnQtcm9sZQAAAAkAAAAFUHJveHkAAAAAAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEAtN4DlSRj3uUHAmVM28mmVpAOsAzHtN82X
Og/Nuhett3cD0EKzpyGl8MiZLvUT0yvyDrZIMtZryovCBGRKEEza1WeZedglqpqf7xFuq7darkljPhKld8aUO76G6rgDuCAMDIMybR1AtasJQ7e2538256pr2UMTrPUhXwINAi22ZKoOOq6ny3zBlaWNuvjYelJ2Yne1DQNVgDiVjdW3UxIaxnW/cgCPsLLPc2ZO8ts3OMrrhAFsRzQIlP/50iQbC9EerKqq0Y/Gab+L15
+22zXK80zOMEpC4hqzhy8XX1Lbh2EEPTXnyJ6M6qt/D+B78VnbVjdWOXRRscCmr2zyJczHQAAARQAAAAMcnNhLXNoYTItNTEyAAABAIv7bKCXqvqlvunlfdSAf48HT3gsILGw9o+joLhwTgH5V6iJgZ0VvkChY9yduvBqZsEC+AhtGEffWZ02sy6JgLEP4dGvGmHb0WvFNg1ZGssjMYfIoZedJsqy1luELAqgcdtJgrThY
EQ7gJ20wuYX6YBLR3MHHgyKupOjwoT4ILw3oxkSOb++er2NKPAHQJD2U4zFIH5OlImsBV6xRGaCvkEu5VUj7nG15hqt7qjdzXhIJNv3v21f0D+P+F/C/Y9i5kEHqWhoLP6nx8n9RE/vDqkoaDftmo9aX2U4ed0mg+8hpD7xZpGMI0YGd6ZoSv6M/Gw2vMqiu003YzzEaOk7LJQ=\n." client/keyagent.go:338
DEBU [KEYAGENT]  Validated host test-teleport.carsonanderson.net:443. client/keyagent.go:344
INFO [CLIENT]    Successful auth with proxy test-teleport.carsonanderson.net:3080. client/api.go:2106
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
DEBU [KEYAGENT]  Adding CA key for test-teleport.carsonanderson.net client/keyagent.go:302
DEBU [KEYSTORE]  Adding known host test-teleport.carsonanderson.net with proxy test-teleport.carsonanderson.net and key: SHA256:/EmSHKGztjLDIuWuviNdI4fMHCY2vGoXVHavxQaJW64 client/keystore.go:541
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
INFO [CLIENT]    Connecting proxy=test-teleport.carsonanderson.net:3080 login="root" client/api.go:2099
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAgcxLXLt+YV18GvxYI7ADjzPowaG0XYEmsC+gjz4aeFjoAAAADAQABAAABAQDtpQqiMR8c/aknwW+zpa0Bz3zNRKOcs608zVv70s9KE+BC0Z0M0l+cGbAgx+FN46EZNDuPT
inF5ZEmGeXMW2QZYS4GaQ+qMMzZQJUS7DU8wk4cw1BZZZ2szKD7rL/ok6CDQFlbmd0dSii8QPG4u+Y4K9AS+Zrq8EYUvYEArG7bIvrYN+gxwPRsgvK3WVeQlHI6gQUR2V+Gkepu6VyGWXW6ooZaNdhKqH219I2gFEj7bxZUfPtiQDLrZpgRhqvNKxx4MkkuEEeNdLC7ZRzYaVNEButbnbA93zHFPDuI/qcQw+DbeTh86lZ
vUpYbaYQeGCTA33SVU36sE1bInbElOdORAAAAAAAAAAAAAAACAAAAAAAAATsAAABFNTZmYWZkMjYtZWY4YS00ZGMxLWFkZjEtZGEzM2Y5MGNmMjhmLnRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAJDU2ZmFmZDI2LWVmOGEtNGRjMS1hZGYxLWRhMzNmOTBjZjI4ZgAAADl0ZWxlcG9ydC04ZGRmZDQ5N
jctMmtrenYudGVzdC10ZWxlcG9ydC5jYXJzb25hbmRlcnNvbi5uZXQAAAAYdGVsZXBvcnQtOGRkZmQ0OTY3LTJra3p2AAAACWxvY2FsaG9zdAAAAAkxMjcuMC4wLjEAAAADOjoxAAAAIHRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9
jYWwAAAAAYdx+8f//////////AAAAAAAAAGAAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAkAAAAIHRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAD3gtdGVsZXBvcnQtcm9sZQAAAAkAAAAFUHJveHkAAAAAAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEAtN4DlSRj3uUHAmVM28mmVpAOsAzHtN82X
Og/Nuhett3cD0EKzpyGl8MiZLvUT0yvyDrZIMtZryovCBGRKEEza1WeZedglqpqf7xFuq7darkljPhKld8aUO76G6rgDuCAMDIMybR1AtasJQ7e2538256pr2UMTrPUhXwINAi22ZKoOOq6ny3zBlaWNuvjYelJ2Yne1DQNVgDiVjdW3UxIaxnW/cgCPsLLPc2ZO8ts3OMrrhAFsRzQIlP/50iQbC9EerKqq0Y/Gab+L15
+22zXK80zOMEpC4hqzhy8XX1Lbh2EEPTXnyJ6M6qt/D+B78VnbVjdWOXRRscCmr2zyJczHQAAARQAAAAMcnNhLXNoYTItNTEyAAABAIv7bKCXqvqlvunlfdSAf48HT3gsILGw9o+joLhwTgH5V6iJgZ0VvkChY9yduvBqZsEC+AhtGEffWZ02sy6JgLEP4dGvGmHb0WvFNg1ZGssjMYfIoZedJsqy1luELAqgcdtJgrThY
EQ7gJ20wuYX6YBLR3MHHgyKupOjwoT4ILw3oxkSOb++er2NKPAHQJD2U4zFIH5OlImsBV6xRGaCvkEu5VUj7nG15hqt7qjdzXhIJNv3v21f0D+P+F/C/Y9i5kEHqWhoLP6nx8n9RE/vDqkoaDftmo9aX2U4ed0mg+8hpD7xZpGMI0YGd6ZoSv6M/Gw2vMqiu003YzzEaOk7LJQ=\n." client/keyagent.go:338
DEBU [KEYAGENT]  Validated host test-teleport.carsonanderson.net:443. client/keyagent.go:344
INFO [CLIENT]    Successful auth with proxy test-teleport.carsonanderson.net:3080. client/api.go:2106
DEBU [CLIENT]    Found clusters: [{"name":"test-teleport.carsonanderson.net","lastconnected":"2022-01-10T19:03:35.276843635Z","status":"online"}] client/client.go:110
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
DEBU [TSH]       Disabling exec plugin mode for kubeconfig because this Teleport cluster has no Kubernetes clusters. tsh/kube.go:361
INFO [CLIENT]    Connecting proxy=test-teleport.carsonanderson.net:3080 login="root" client/api.go:2099
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
DEBU [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAgcxLXLt+YV18GvxYI7ADjzPowaG0XYEmsC+gjz4aeFjoAAAADAQABAAABAQDtpQqiMR8c/aknwW+zpa0Bz3zNRKOcs608zVv70s9KE+BC0Z0M0l+cGbAgx+FN46EZNDuPT
inF5ZEmGeXMW2QZYS4GaQ+qMMzZQJUS7DU8wk4cw1BZZZ2szKD7rL/ok6CDQFlbmd0dSii8QPG4u+Y4K9AS+Zrq8EYUvYEArG7bIvrYN+gxwPRsgvK3WVeQlHI6gQUR2V+Gkepu6VyGWXW6ooZaNdhKqH219I2gFEj7bxZUfPtiQDLrZpgRhqvNKxx4MkkuEEeNdLC7ZRzYaVNEButbnbA93zHFPDuI/qcQw+DbeTh86lZ
vUpYbaYQeGCTA33SVU36sE1bInbElOdORAAAAAAAAAAAAAAACAAAAAAAAATsAAABFNTZmYWZkMjYtZWY4YS00ZGMxLWFkZjEtZGEzM2Y5MGNmMjhmLnRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAJDU2ZmFmZDI2LWVmOGEtNGRjMS1hZGYxLWRhMzNmOTBjZjI4ZgAAADl0ZWxlcG9ydC04ZGRmZDQ5N
jctMmtrenYudGVzdC10ZWxlcG9ydC5jYXJzb25hbmRlcnNvbi5uZXQAAAAYdGVsZXBvcnQtOGRkZmQ0OTY3LTJra3p2AAAACWxvY2FsaG9zdAAAAAkxMjcuMC4wLjEAAAADOjoxAAAAIHRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAKHJlbW90ZS5rdWJlLnByb3h5LnRlbGVwb3J0LmNsdXN0ZXIubG9
jYWwAAAAAYdx+8f//////////AAAAAAAAAGAAAAAUeC10ZWxlcG9ydC1hdXRob3JpdHkAAAAkAAAAIHRlc3QtdGVsZXBvcnQuY2Fyc29uYW5kZXJzb24ubmV0AAAAD3gtdGVsZXBvcnQtcm9sZQAAAAkAAAAFUHJveHkAAAAAAAABFwAAAAdzc2gtcnNhAAAAAwEAAQAAAQEAtN4DlSRj3uUHAmVM28mmVpAOsAzHtN82X
Og/Nuhett3cD0EKzpyGl8MiZLvUT0yvyDrZIMtZryovCBGRKEEza1WeZedglqpqf7xFuq7darkljPhKld8aUO76G6rgDuCAMDIMybR1AtasJQ7e2538256pr2UMTrPUhXwINAi22ZKoOOq6ny3zBlaWNuvjYelJ2Yne1DQNVgDiVjdW3UxIaxnW/cgCPsLLPc2ZO8ts3OMrrhAFsRzQIlP/50iQbC9EerKqq0Y/Gab+L15
+22zXK80zOMEpC4hqzhy8XX1Lbh2EEPTXnyJ6M6qt/D+B78VnbVjdWOXRRscCmr2zyJczHQAAARQAAAAMcnNhLXNoYTItNTEyAAABAIv7bKCXqvqlvunlfdSAf48HT3gsILGw9o+joLhwTgH5V6iJgZ0VvkChY9yduvBqZsEC+AhtGEffWZ02sy6JgLEP4dGvGmHb0WvFNg1ZGssjMYfIoZedJsqy1luELAqgcdtJgrThY
EQ7gJ20wuYX6YBLR3MHHgyKupOjwoT4ILw3oxkSOb++er2NKPAHQJD2U4zFIH5OlImsBV6xRGaCvkEu5VUj7nG15hqt7qjdzXhIJNv3v21f0D+P+F/C/Y9i5kEHqWhoLP6nx8n9RE/vDqkoaDftmo9aX2U4ed0mg+8hpD7xZpGMI0YGd6ZoSv6M/Gw2vMqiu003YzzEaOk7LJQ=\n." client/keyagent.go:338
DEBU [KEYAGENT]  Validated host test-teleport.carsonanderson.net:443. client/keyagent.go:344
INFO [CLIENT]    Successful auth with proxy test-teleport.carsonanderson.net:3080. client/api.go:2106
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-x509.pem" valid until "2022-01-11 07:03:35 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Reading certificates from path "/Users/randerson/.tsh/keys/test-teleport.carsonanderson.net/randerson-ssh/test-teleport.carsonanderson.net-cert.pub". client/keystore.go:303
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/Users/randerson/.tsh/keys/teleport.carsonanderson.net/rcanderson23-x509.pem" valid until "2022-01-10 15:52:35 +0000 UTC". client/keystore.go:280
DEBU [KEYSTORE]  Reading certificates from path "/Users/randerson/.tsh/keys/teleport.carsonanderson.net/rcanderson23-ssh/teleport.carsonanderson.net-cert.pub". client/keystore.go:303
> Profile URL:        https://test-teleport.carsonanderson.net:443
  Logged in as:       randerson
  Cluster:            test-teleport.carsonanderson.net
  Roles:              access, auditor, editor
  Traits:             kubernetes_groups: []
                      kubernetes_users: []
                      logins: [root]
                      windows_logins: []
  Logins:             root
  Kubernetes:         enabled
  Valid until:        2022-01-11 00:03:35 -0700 MST [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```
</details>
<details>
  <summary>kubeconfig before</summary>
  
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [redacted]
    server: https://k8s.carsonanderson.net:6443
  name: homelab
contexts:
- context:
    cluster: homelab
    namespace: teleport
    user: kubernetes-admin
  name: homelab
current-context: homelab
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: [redacted]
    client-key-data: [redacted]
```
</details>

<details>
  <summary>kubeconfig after</summary>
  
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [redacted]
    server: https://k8s.carsonanderson.net:6443
  name: homelab
- cluster:
    certificate-authority-data: [redacted]
    server: https://test-teleport.carsonanderson.net:443
    tls-server-name: kube.test-teleport.carsonanderson.net
  name: test-teleport.carsonanderson.net
contexts:
- context:
    cluster: homelab
    namespace: teleport
    user: kubernetes-admin
  name: homelab
- context:
    cluster: test-teleport.carsonanderson.net
    user: test-teleport.carsonanderson.net
  name: test-teleport.carsonanderson.net
current-context: test-teleport.carsonanderson.net
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: [redacted]
    client-key-data: [redacted]
- name: test-teleport.carsonanderson.net
  user:
    client-certificate-data: [redacted]
    client-key-data: [redacted]
```
</details>

### PR DESCRIPTION
**Pull request by tigrato**
This PR disables the update of kubeconfig when `tsh login` does not have the `--kube-cluster` flag.

The new behavior will update the kubeconfig only if the user provided a non-empty value in  `--kube-cluster`.

This PR also introduces a mechanism to restore the current context on `tsh logout`. On `tsh login --kube-cluster=<cluster>` or `tsh kube login <cluster>`, Teleport updates the selected context - if it's not from Teleport - to add an extension whose key is: `selected_context`. Once `tsh logout` is called and the active context was a Teleport cluster, we restore the current context to the cluster that has the `selected_context` key in extensions.

Fixes #9718

### CODE REVIEW

**Comment by zmb3** [comment]
Also fixes #6045

File: lib/kube/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -359,9 +367,46 @@ func SelectContext(teleportCluster, kubeCluster string) error {
...
+// in order to restore the the CurrentContext value.
+// If no such key is found, it returns an empty selected cluster.
+func searchForSelectedCluster(contexts map[string]*clientcmdapi.Context) string {
+	for k, v := range contexts {
+		if _, ok := v.Extensions[selectedExtension]; ok {
+			delete(v.Extensions, selectedExtension)
+			return k
+		}
+	}
+	return ""
```
Comment (hugoShaka) [inline lib/kube/kubeconfig/kubeconfig.go:411]: I understand that `setSelectedExtension` flushes all other `selected_context` extensions, but users are sometimes editing/merging kubeconfigs and might end up with the extension set twice. Should this case be handled?

File: lib/kube/kubeconfig/kubeconfig.go [hunk 2]
```diff
@@ -359,9 +367,46 @@ func SelectContext(teleportCluster, kubeCluster string) error {
...
 	}
+	setSelectedExtension(kc.Contexts, kc.CurrentContext, teleportCluster)
 	kc.CurrentContext = kubeContext
 	if err := Save("", *kc); err != nil {
 		return trace.Wrap(err)
 	}
 	return nil
 }
+
+const selectedExtension = "selected_context"
```
Comment (hugoShaka) [inline lib/kube/kubeconfig/kubeconfig.go:378]: Is the name standard? Should we prefix it with `teleport` or something to ensure no other app will rely on the same extension?

**Review by hugoShaka — APPROVED** [review]
LGTM with minor nits

File: lib/kube/kubeconfig/kubeconfig.go (hunk 1 above)
Comment (tigrato) [reply lib/kube/kubeconfig/kubeconfig.go:411]: Yeah, that's a good case. I will change it to return a non-empty current context only if a single cluster has the selected extension.

File: lib/kube/kubeconfig/kubeconfig.go (hunk 2 above)
Comment (tigrato) [reply lib/kube/kubeconfig/kubeconfig.go]: done

**Review by mdwn — APPROVED** [review]

File: lib/kube/kubeconfig/kubeconfig.go [hunk 3]
```diff
@@ -359,9 +367,52 @@ func SelectContext(teleportCluster, kubeCluster string) error {
...
+	for _, v := range contexts {
+		delete(v.Extensions, selectedExtension)
+	}
+
+	selected.Extensions[selectedExtension] = nil
+}
+
+// searchForSelectedCluster looks for contexts that were previously selected
+// in order to restore the the CurrentContext value.
+// If no such key is found, it returns an empty selected cluster.
```
Comment (jakule) [inline lib/kube/kubeconfig/kubeconfig.go:403]: This function also returns an empty string if more than one occurrence has been found.

**Review by jakule — APPROVED** [review]

**Review by strideynet — APPROVED** [review]

File: lib/kube/kubeconfig/kubeconfig.go [hunk 4]
```diff
@@ -359,9 +367,52 @@ func SelectContext(teleportCluster, kubeCluster string) error {
...
+// setSelectedExtension sets an extension to indentify that the current non-teleport
+// context was selected before introducing Teleport contexts in kubeconfig.
+// If the currentContext is not from Teleport, this function adds the following
+// extensions:
+//   - extension: null
+//     name: teleport-prev-selec-ctx
+//
+// Only one context is allowed to have the selected extension. If other context has it,
+// this function deletes it and introduces it in the desired context.
+func setSelectedExtension(contexts map[string]*clientcmdapi.Context, prevCluster string, teleportCluster string) {
```
Comment (smallinsky) [inline lib/kube/kubeconfig/kubeconfig.go:389]: Wonder why the top [config.extensions](https://github.com/kubernetes/client-go/blob/674e53a7cb8f1ea160ac4485ffc7582e1a790215/tools/clientcmd/api/v1/types.go#L51) was not used  but I'm fine with relaying on `config.contexts.extensions`

**Review by smallinsky — APPROVED** [review]

File: lib/kube/kubeconfig/kubeconfig.go (hunk 4 above)
Comment (tigrato) [reply lib/kube/kubeconfig/kubeconfig.go:389]: I decided to use context extensions because when merging multiple kubeconfig files, `config.extensions` might be overwritten/merged which is difficult to resolve.
