### PR TITLE
 Fix missing roles in access lists causing users to be locked out of their account

### LINKED ISSUE #43775: User is locked out if role expires before Access List
A customer has reported that a user will be locked out from Teleport if they are granted access by an Access List and one of the roles in the Access List has a TTL that has been expired.

From the customer:

> For instance, when using the tsh login command with a request id, it respects the shortest TTL among the granted roles for the identity file TTL. However, it does not respect the shortest TTL among roles in the access lists that associate with the user. This means that if there's a short-lived role in the access list, the certificate will still be issued with the default TTL. The error arises when the role is deleted but still in the identity file. We anticipate that the issued identity file will also adhere to the shortest TTL of the roles in the access lists.

Steps to reproduce are below.

1. Create a role with a TTL
2. Create an access list without TTL and set the user as the owner and grant the created role
3. Re-login to acquire the new role
4. Once the role expires, the error will occur
5. The user will be completely locked out and unable to re-login

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves https://github.com/gravitational/teleport/issues/43775

This PR fixes an issue where users would be logged out and locked out of their accounts if their access list references a role which no longer exists. This can occur when the role in the access list has a TTL and expires.

When generating the `UserLoginState`, any access lists which reference one or more non-existent roles will be skipped entirely, and an audit event is emitted as a notice.

image
image
image

changelog: Fix missing roles in access lists causing users to be locked out of their account

### CODE REVIEW

**Comment by fspmarshall** [comment]
While use of deny rules in access lists is discouraged, we do not have a mechanism of preventing it, meaning that it isn't sane to skip roles as it might constitute a privilege escalation.

Because of the risk of malformed access lists breaking login, we've already made a single exception to this rule.  We allow access list application to fail "atomically".  I.e. we assume that failure to apply the _entire_ access lists will not result in privilege escalation, and we make it the user's responsibility to only ever use access lists _as a whole_ as a means of privilege escalation, not privilege limiting the way an individual role might be used.

We _can_ solve missing roles locking out users, but it must be solved s.t. the entire access list that assigned the roles is skipped, rather than just skipping the specific role (i.e. none of the roles, traits, etc from that list get applied).

**Comment by rudream** [comment]
> We can solve missing roles locking out users, but it must be solved s.t. the entire access list that assigned the roles is skipped, rather than just skipping the specific role (i.e. none of the roles, traits, etc from that list get applied).

@fspmarshall After confirming with the customer, I've gone with this approach and updated this PR.

**Comment by zmb3** [comment]
@smallinsky I would appreciate your review on this one too if you have a few minutes this week 🙏

File: lib/events/api.go [hunk 1]
```diff
@@ -737,6 +737,9 @@ const (
 	// AccessListMemberDeleteAllForAccessListEvent is emitted when all members are deleted from an access list.
 	AccessListMemberDeleteAllForAccessListEvent = "access_list.member.delete_all_for_access_list"
 
+	// AccessListSkippedEvent is emitted when a user logs in as a member of an invalid access list, causing the access list to be skipped.
+	AccessListSkippedEvent = "access_list.skipped"
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/events/api.go:741]: `user_login.invalid_access_list`

File: api/proto/teleport/legacy/types/events/events.proto [hunk 2]
```diff
@@ -7869,28 +7869,27 @@ message GitCommandAction {
   string New = 4 [(gogoproto.jsontag) = "new,omitempty"];
 }
 
-// AccessListSkippedMetadata contains metadata for access list skipped events.
-message AccessListSkippedMetadata {
-  // AccessListName is the name of the access list that was skipped.
+// AccessListInvalidMetadata contains metadata for access list skipped events.
```
Comment (zmb3) [inline api/proto/teleport/legacy/types/events/events.proto:7872]:
```suggestion
// AccessListInvalidMetadata contains metadata about invalid access lists.
```

File: api/proto/teleport/legacy/types/events/events.proto [hunk 3]
```diff
@@ -7869,28 +7869,27 @@ message GitCommandAction {
...
+message AccessListInvalidMetadata {
+  // AccessListName is the name of the invalid access list.
   string AccessListName = 1 [(gogoproto.jsontag) = "access_list_name, omitempty"];
-  // User is the name of the access list member/owner for whom the access list was not applied.
+  // User is the username of the user who attempted to consume this access list.
```
Comment (zmb3) [inline api/proto/teleport/legacy/types/events/events.proto:7876]:
```suggestion
  // User is the username of the access list member who attempted to log in.
```

File: api/proto/teleport/legacy/types/events/events.proto [hunk 4]
```diff
@@ -7869,28 +7869,27 @@ message GitCommandAction {
...
   string User = 2 [(gogoproto.jsontag) = "user,omitempty"];
-  // MissingRoles are the names of the non-existent roles being referenced by the access list, causing it to be skipped.
+  // MissingRoles are the names of the non-existent roles being referenced by the access list, causing it to be invalid.
   repeated string MissingRoles = 3 [(gogoproto.jsontag) = "missing_roles,omitempty"];
 }
 
-// UserLoginAccessListSkipped is emitted when a user logs in with an invalid access list, resulting in
-// the access list being skipped.
-message UserLoginAccessListSkipped {
+// UserLoginAccessListInvalid is emitted when a user logs in with an invalid access list.
```
Comment (zmb3) [inline api/proto/teleport/legacy/types/events/events.proto:7882]:
```suggestion
// UserLoginAccessListInvalid is emitted when a user who is a member of an invalid
// access list logs in. It is used to indicate that the access list could not be
// applied to the user's session.
```

File: lib/auth/userloginstate/generator.go [hunk 5]
```diff
@@ -186,8 +197,6 @@ func (g *Generator) Generate(ctx context.Context, user types.User, ulsService se
 	return uls, nil
 }
 
-// addAccessListsToState will add the user's applicable access lists to the user login state,
-// returning any inherited roles and traits.
```
Comment (zmb3) [inline lib/auth/userloginstate/generator.go:190]: Why did we remove the godoc here? If it's no longer accurate can we replace it with something that is accurate rather than removing it completely?

Also, while you're here, it probably makes sense to name the return values - it's not clear from the name of the function what the `[]string` and `map[string][]string` are supposed to be.

File: lib/auth/userloginstate/generator.go [hunk 6]
```diff
@@ -199,38 +208,97 @@ func (g *Generator) addAccessListsToState(ctx context.Context, user types.User,
...
+		allInheritedRoles = append(allInheritedRoles, inheritedRoles...)
+		for k, values := range inheritedTraits {
+			allInheritedTraits[k] = append(allInheritedTraits[k], values...)
 		}
 	}
 
 	return allInheritedRoles, allInheritedTraits, nil
 }
 
+// handleAccessListMembership validates the access list and applies the grants and traits from the access list to the user if they are a member of the access list.
```
Comment (zmb3) [inline lib/auth/userloginstate/generator.go:234]:
```suggestion
// handleAccessListMembership validates the access list and applies the grants and traits from the access list to the user if they are a member of the access list.
// If the access list is invalid (because it references a non-existent role, for example,
// then it will not be applied.
```

File: lib/auth/userloginstate/generator.go [hunk 7]
```diff
@@ -199,38 +208,97 @@ func (g *Generator) addAccessListsToState(ctx context.Context, user types.User,
...
+func (g *Generator) handleAccessListMembership(ctx context.Context, user types.User, accessList *accesslist.AccessList, state *userloginstate.UserLoginState) ([]string, map[string][]string, error) {
+	var inheritedRoles []string
+	inheritedTraits := make(map[string][]string)
+
+	membershipKind, err := accesslists.IsAccessListMember(ctx, user, accessList, g.accessLists, g.accessLists, g.clock)
+	if err != nil {
+		g.log.WithError(err).Warn("checking access list membership")
+	}
+	if err == nil && membershipKind != accesslists.MembershipOrOwnershipTypeNone {
```
Comment (zmb3) [inline lib/auth/userloginstate/generator.go:243]: Can we return in the `err != nil` case so all of this code doesn't have to be inside a `err == nil` check?

File: lib/auth/userloginstate/generator.go [hunk 8]
```diff
@@ -199,38 +208,97 @@ func (g *Generator) addAccessListsToState(ctx context.Context, user types.User,
...
+		// Validate that all the roles in the access list exist.
+		missingRoles, notFoundErrs, err := g.validateRoles(ctx, accessList.Spec.Grants.Roles)
+		if err != nil {
+			return nil, nil, trace.Wrap(err)
+		}
+
+		// If there are any missing roles, emit an audit event and return early.
```
Comment (zmb3) [inline lib/auth/userloginstate/generator.go:250]:
```suggestion
		// If there are any missing roles, then we cannot apply the access list.
		// Emit an audit event and return early.
```

File: lib/auth/userloginstate/generator.go [hunk 9]
```diff
@@ -199,38 +208,97 @@ func (g *Generator) addAccessListsToState(ctx context.Context, user types.User,
...
+				inheritedTraits[k] = append(inheritedTraits[k], values...)
+			}
+		}
+	}
+
+	return inheritedRoles, inheritedTraits, nil
+}
+
+// handleAccessListOwnership validates the access list and applies the owner grants and traits from the access list to the user if they are an owner of the access list.
+func (g *Generator) handleAccessListOwnership(ctx context.Context, user types.User, accessList *accesslist.AccessList, state *userloginstate.UserLoginState) ([]string, map[string][]string, error) {
```
Comment (zmb3) [inline lib/auth/userloginstate/generator.go:269]: Same comments as above.

File: lib/auth/userloginstate/generator.go [hunk 10]
```diff
@@ -364,3 +431,49 @@ func (g *Generator) LoginHook(ulsService services.UserLoginStates) func(context.
 		return trace.Wrap(err)
 	}
 }
+
+// validateRoles is a helper function which validates that a given list of roles exist.
+func (g *Generator) validateRoles(ctx context.Context, roles []string) ([]string, []error, error) {
```
Comment (zmb3) [inline lib/auth/userloginstate/generator.go:436]: Do we really need to return the `notFoundErrs` we basically know they're going to be "role xyz not found" right?

Also I would explore different names here. I'd expect something named validate to just return an error. Maybe this should be named something like `identifyMissingRoles`?

File: lib/auth/userloginstate/generator.go [hunk 11]
```diff
@@ -364,3 +431,49 @@ func (g *Generator) LoginHook(ulsService services.UserLoginStates) func(context.
...
+	}
+
+	if len(missingRoles) > 0 {
+		return missingRoles, notFoundErrs, nil
+	}
+
+	return nil, nil, nil
+}
+
+// emitSkippedAccessListEvent emits an audit log event to warn that an access list was skipped due to it referencing a non-existent role.
```
Comment (zmb3) [inline lib/auth/userloginstate/generator.go:459]: Maybe for the godoc here we just say invalid and don't hint at the reason. Today the only reason is that it may reference a non-existent role, but we may add more ways to invalidate access lists in the future and I imagine we would re-use the same audit event.

```suggestion
// emitSkippedAccessListEvent emits an audit log event to indicate that an invalid
// access list could not be applied during user login.
```

**Review by zmb3 — COMMENTED** [review]
Just some minor cleanup suggestions.

File: lib/auth/userloginstate/generator.go (hunk 7 above)
Comment (rudream) [reply lib/auth/userloginstate/generator.go:243]: This is based on the previous implementation, we don't actually want to return if there's an error, just warn and continue.

https://github.com/gravitational/teleport/blob/ed46e873212e6e07225ccf25cecfa604851016d3/lib/auth/userloginstate/generator.go#L206

Comment (zmb3) [reply lib/auth/userloginstate/generator.go:243]: If there is an error, this condition will be false, so the entire if statement will be skipped and you'll go straight to line 265: `return inheritedRoles, inheritedTraits, nil`.

I would invert the check so that you can `return inheritedRoles, inheritedTraits, nil` and then the main body of this function doesn't need to be indented in an if.

**Review by smallinsky — APPROVED** [review]
LGTM.

**Review by zmb3 — APPROVED** [review]
