### PR TITLE
Deflake HTTP_PROXY tests

### LINKED ISSUE #33197: `TestNewWebClientNoProxy` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/6461962139/job/17542695997#step:6:1185

#### Relevant snippet

I'm not sure if this related to timeouts or not as this job has failed after 10 minutes and 1 second.

```
webclient_test.go:356: 
        	Error Trace:	/__w/teleport/teleport/api/client/webclient/webclient_test.go:356
        	Error:      	"Get \"[https://fakedomain.example.com\](https://fakedomain.example.com/)": dial tcp: lookup fakedomain.example.com on 127.0.0.11:53: server misbehaving" does not contain "no such host"
        	Test:       	TestNewWebClientNoProxy
```

### PR DESCRIPTION
**Pull request by atburke**
This change rewrites a few HTTP_PROXY related tests to be less flaky.

Resolves #33197.

### CODE REVIEW

File: api/testhelpers/proxy.go [hunk 1]
```diff
@@ -98,3 +101,55 @@ func (p *ProxyHandler) Count() int {
...
+	}
+	return "", trace.NotFound("No non-loopback local IP address found")
+}
+
+type TestServerOption func(*testing.T, *httptest.Server)
+
+func WithTestServerAddress(ip string) TestServerOption {
+	return func(t *testing.T, srv *httptest.Server) {
+		// Replace the test server's address.
+		l, err := net.Listen("tcp", ip+":0")
```
Comment (zmb3) [inline api/testhelpers/proxy.go:140]: We've had flakiness due to this in the past.

You can't (safely) specify a port of 0 to let the OS pick a port for you, close the listener, and then assume that the port that was previously available will remain available.

File: api/client/webclient/webclient_test.go [hunk 2]
```diff
@@ -324,36 +325,61 @@ func TestParse(t *testing.T) {
...
+		{
+			name: "ignore proxy when no_proxy is set",
+			env: map[string]string{
+				"HTTPS_PROXY": proxyServer.URL,
+				"NO_PROXY":    "*",
+			},
+		},
+	}
+	for _, tc := range tests {
+		t.Run(tc.name, func(t *testing.T) {
```
Comment (bl-nero) [inline api/client/webclient/webclient_test.go:363]: Can we avoid variable name hiding here, and say, use `tt`? I was surprised seeing the `proxyHandler.Reset` passed to the cleanup function and was wondering how the hell we expect to get back to between loop iterations.

File: api/client/webclient/webclient_test.go [hunk 3]
```diff
@@ -324,36 +325,61 @@ func TestParse(t *testing.T) {
...
+				"HTTPS_PROXY": proxyServer.URL,
+			},
+			expectedProxyCount: 1,
+		},
+		{
+			name: "ignore proxy when no_proxy is set",
+			env: map[string]string{
+				"HTTPS_PROXY": proxyServer.URL,
+				"NO_PROXY":    "*",
+			},
```
Comment (bl-nero) [inline api/client/webclient/webclient_test.go:359]: Consider setting `expectedProxyCount` explicitly to 0 to clearly state the intent.

File: api/client/webclient/webclient_test.go (hunk 2 above)
Comment (zmb3) [reply api/client/webclient/webclient_test.go:363]: Are you referring to `t`? Shadowing `t` in subtests is quite common and is actually the preferred approach.

If you have `tt` and `t` in scope, it's possible to mistakenly use the wrong one and (for example) fail the top-level test instead of the subtest. Shadowing `t` makes that impossible because the outer `t` is no longer accessible to the closure.

It's even written this way in the official docs for the `testing` package: https://pkg.go.dev/testing#hdr-Subtests_and_Sub_benchmarks

**Comment by atburke** [comment]
Friendly ping @bl-nero @zmb3

**Review by zmb3 — APPROVED** [review]

**Review by bl-nero — APPROVED** [review]
