### PR TITLE
Self signed certificates `tsh` TTL fixes

### LINKED ISSUE #13782: `tsh login` confusing error messages
_Umbrella: Improve user experience for users trying teleport with self-signed certificates._

Tsh login will fail:

```
tsh ssh --proxy=teleport.example.com --user=test ubuntu@test
ERROR: Get "https://teleport.example.com:3080/webapi/ping": dial tcp 172.16.30.98:3080: connect: connection refused
```

If you run the command with --debug you will see:

```
DEBU [TSH]       Race request failed error:[Get "https://teleport.example.com3080/webapi/ping": dial tcp 1.2.3.4:3080: connect: connection refused] tsh/resolve_default_addr.go:83
DEBU [TSH]       Trying teleport.example.com:443... tsh/resolve_default_addr.go:109
DEBU [TSH]       Race request failed error:[Get "[https://teleport.example.com:443/webapi/ping](https://teleport.example.com/webapi/ping)": x509: certificate signed by unknown authority] tsh/resolve_default_addr.go:83
```

First of all, let's improve this unclear "Race request failed error`. Seems like some strange internal phrasing.

Second, the user facing error should be:

```bash
tsh ssh --proxy=teleport.example.com --user=test ubuntu@test
ERROR: Failed to connect to https://eleport.example.com. The certificate has expired or signed by untrusted certificate authority. Please update your certificate. 

If you are trying teleport with self-signed certificate, please follow this guide: https://goteleport.com/docs/getting-started/self-signed#tsh
```

### PR DESCRIPTION
**Pull request by strideynet**
Closes #13782

This PR changes the race logic that tries `:3080` and `:443` when no proxy port has been specified to propagate both errors that occur, rather than the last error to occur. This fixes an issue where often the less useful error would be propagated (e.g `connection refused` on the closed port, rather than the `not trusted` error on the correct port) and ensures that the `not trusted` error displays the useful warning with steps the user can take to rectify.

**Old output with debug disabled and enabled**
```sh
➜  teleport git:(strideynet/self-signed-tsh-experience-fixes) ✗ build/tsh login --proxy self-signed.local.ottr.sh
ERROR: Get "https://self-signed.local.ottr.sh:3080/webapi/ping": dial tcp 127.0.0.1:3080: connect: connection refused

➜  teleport git:(strideynet/self-signed-tsh-experience-fixes) ✗ build/tsh login --proxy self-signed.local.ottr.sh -d
DEBU [CLIENT]    open /Users/noahstride/.tsh/self-signed.local.ottr.sh.yaml: no such file or directory client/api.go:1056
DEBU [TSH]       Web proxy port was not set. Attempting to detect port number to use. tsh/tsh.go:3163
DEBU [TSH]       Resolving default proxy port (insecure: false) tsh/resolve_default_addr.go:108
DEBU [TSH]       Trying self-signed.local.ottr.sh:3080... tsh/resolve_default_addr.go:96
DEBU [TSH]       Race request failed error:[Get "https://self-signed.local.ottr.sh:3080/webapi/ping": dial tcp 127.0.0.1:3080: connect: connection refused] tsh/resolve_default_addr.go:60
DEBU [TSH]       Trying self-signed.local.ottr.sh:443... tsh/resolve_default_addr.go:96
DEBU [TSH]       Race request failed error:[Get "https://self-signed.local.ottr.sh:443/webapi/ping": x509: “localhost” certificate is not trusted] tsh/resolve_default_addr.go:60
DEBU [TSH]       Waiting for all in-flight racers to finish tsh/resolve_default_addr.go:131
DEBU [TSH]       Proxy port resolution failed, falling back to legacy default. error:[
ERROR REPORT:
Original Error: trace.aggregate Get &#34;https://self-signed.local.ottr.sh:3080/webapi/ping&#34;: dial tcp 127.0.0.1:3080: connect: connection refused, Get &#34;https://self-signed.local.ottr.sh:443/webapi/ping&#34;: x509: “localhost” certificate is not trusted
Stack Trace:
        /Users/noahstride/code/gravitational/teleport/tool/tsh/resolve_default_addr.go:201 main.pickDefaultAddr
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:3167 main.setClientWebProxyAddr
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:2934 main.makeClientForProxy
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:2743 main.makeClient
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:1294 main.onLogin
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:942 main.Run
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:403 main.main
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:250 runtime.main
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1263 runtime.goexit
User Message: Get &#34;https://self-signed.local.ottr.sh:3080/webapi/ping&#34;: dial tcp 127.0.0.1:3080: connect: connection refused, Get &#34;https://self-signed.local.ottr.sh:443/webapi/ping&#34;: x509: “localhost” certificate is not trusted] tsh/tsh.go:3171
INFO [CLIENT]    No teleport login given. defaulting to noahstride client/api.go:1408
INFO [CLIENT]    no host login given. defaulting to noahstride client/api.go:1418
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.d3dZ9xRmm0/Listeners" client/api.go:3957
DEBU [CLIENT]    attempting to use loopback pool for local proxy addr: self-signed.local.ottr.sh:3080 client/api.go:3915
DEBU [CLIENT]    reading self-signed certs from: /var/lib/teleport/webproxy_cert.pem client/api.go:3923
DEBU [CLIENT]    using local pool for loopback proxy: /var/lib/teleport/webproxy_cert.pem, err: <nil> client/api.go:3944
DEBU             Attempting GET self-signed.local.ottr.sh:3080/webapi/ping webclient/webclient.go:115

ERROR REPORT:
Original Error: *url.Error Get &#34;https://self-signed.local.ottr.sh:3080/webapi/ping&#34;: dial tcp 127.0.0.1:3080: connect: connection refused
Stack Trace:
        /Users/noahstride/code/gravitational/teleport/api/client/webclient/webclient.go:127 github.com/gravitational/teleport/api/client/webclient.doWithFallback
        /Users/noahstride/code/gravitational/teleport/api/client/webclient/webclient.go:194 github.com/gravitational/teleport/api/client/webclient.Ping
        /Users/noahstride/code/gravitational/teleport/lib/client/api.go:3534 github.com/gravitational/teleport/lib/client.(*TeleportClient).Ping
        /Users/noahstride/code/gravitational/teleport/lib/client/api.go:3150 github.com/gravitational/teleport/lib/client.(*TeleportClient).PingAndShowMOTD
        /Users/noahstride/code/gravitational/teleport/lib/client/api.go:3194 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:1398 main.onLogin
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:942 main.Run
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:403 main.main
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:250 runtime.main
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1263 runtime.goexit
User Message: Get &#34;https://self-signed.local.ottr.sh:3080/webapi/ping&#34;: dial tcp 127.0.0.1:3080: connect: connection refused
```
**New output with debug disabled and enabled**
```sh
➜  teleport git:(strideynet/self-signed-tsh-experience-fixes) ✗ build/tsh login --proxy self-signed.local.ottr.sh
ERROR: WARNING:
The proxy you are connecting to has presented a certificate signed by a
unknown authority. This is most likely due to either being presented
with a self-signed certificate or the certificate was truly signed by an
authority not known to the client.

If you know the certificate is self-signed and would like to ignore this
error use the --insecure flag.
If you have your own certificate authority that you would like to use to
validate the certificate chain presented by the proxy, set the
SSL_CERT_FILE and SSL_CERT_DIR environment variables respectively and try
again.

If you think something malicious may be occurring, contact your Teleport
system administrator to resolve this issue.

➜  teleport git:(strideynet/self-signed-tsh-experience-fixes) ✗ build/tsh login --proxy self-signed.local.ottr.sh -d
DEBU [CLIENT]    open /Users/noahstride/.tsh/self-signed.local.ottr.sh.yaml: no such file or directory client/api.go:1056
DEBU [TSH]       Web proxy port was not set. Attempting to detect port number to use. tsh/tsh.go:3163
DEBU [TSH]       Resolving default proxy port (insecure: false) tsh/resolve_default_addr.go:108
DEBU [TSH]       Trying self-signed.local.ottr.sh:3080... tsh/resolve_default_addr.go:96
DEBU [TSH]       Proxy address test failed error:[Get "https://self-signed.local.ottr.sh:3080/webapi/ping": dial tcp 127.0.0.1:3080: connect: connection refused] tsh/resolve_default_addr.go:60
DEBU [TSH]       Trying self-signed.local.ottr.sh:443... tsh/resolve_default_addr.go:96
DEBU [TSH]       Proxy address test failed error:[Get "https://self-signed.local.ottr.sh:443/webapi/ping": x509: “localhost” certificate is not trusted] tsh/resolve_default_addr.go:60
DEBU [TSH]       Waiting for all in-flight proxy address tests to finish tsh/resolve_default_addr.go:131

ERROR REPORT:
Original Error: trace.aggregate Get &#34;https://self-signed.local.ottr.sh:3080/webapi/ping&#34;: dial tcp 127.0.0.1:3080: connect: connection refused, Get &#34;https://self-signed.local.ottr.sh:443/webapi/ping&#34;: x509: “localhost” certificate is not trusted
Stack Trace:
        /Users/noahstride/code/gravitational/teleport/tool/tsh/resolve_default_addr.go:201 main.pickDefaultAddr
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:3167 main.setClientWebProxyAddr
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:2934 main.makeClientForProxy
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:2743 main.makeClient
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:1294 main.onLogin
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:942 main.Run
        /Users/noahstride/code/gravitational/teleport/tool/tsh/tsh.go:403 main.main
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/proc.go:250 runtime.main
        /opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1263 runtime.goexit
User Message: Get &#34;https://self-signed.local.ottr.sh:3080/webapi/ping&#34;: dial tcp 127.0.0.1:3080: connect: connection refused, Get &#34;https://self-signed.local.ottr.sh:443/webapi/ping&#34;: x509: “localhost” certificate is not trusted
```

### CODE REVIEW

File: tool/tsh/tsh.go [hunk 1]
```diff
@@ -3165,11 +3166,8 @@ func setClientWebProxyAddr(cf *CLIConf, c *client.Config) error {
 
 			proxyAddress, err = pickDefaultAddr(
 				timeout, cf.InsecureSkipVerify, parsedAddrs.Host, defaultWebProxyPorts)
-
-			// On error, fall back to the legacy behavior
 			if err != nil {
-				log.WithError(err).Debug("Proxy port resolution failed, falling back to legacy default.")
```
Comment (strideynet) [inline tool/tsh/tsh.go:3171]: My change removes this fallback. I'm not too sure what this fallback was effective. It ended up retrying `:3080` which is already tried by `pickDefaultAddr`, and masking the underlying errors that had occurred in `pickDefaultAddr`. If I'm missing some additional functionality/coverage this was providing, let me know and I can add it back in with a `trace.NewAggregate`.

File: lib/utils/cli.go [hunk 2]
```diff
@@ -211,40 +211,43 @@ func formatErrorWriter(err error, w io.Writer) {
 }
 
 func formatCertError(err error) string {
+	const unknownAuthority = `WARNING:
+The proxy you are connecting to has presented a certificate signed by a
```
Comment (greedy52) [inline lib/utils/cli.go:215]: Is it intentional that some of the new lines are removed in both warnings? Also seems each line had two extra spaces at the beginning.

File: lib/utils/cli.go [hunk 3]
```diff
@@ -211,40 +211,43 @@ func formatErrorWriter(err error, w io.Writer) {
...
+If you know the certificate is self-signed and would like to ignore this
+error use the --insecure flag.
+If you have your own certificate authority that you would like to use to
+validate the certificate chain presented by the proxy, set the
+SSL_CERT_FILE and SSL_CERT_DIR environment variables respectively and try
+again.
+
+If you think something malicious may be occurring, contact your Teleport
+system administrator to resolve this issue.
+  `
```
Comment (greedy52) [inline lib/utils/cli.go:229]: extra spaces

File: lib/utils/cli.go [hunk 4]
```diff
@@ -211,40 +211,43 @@ func formatErrorWriter(err error, w io.Writer) {
...
-
   Contact your Teleport system administrator to resolve this issue.`, innerError)
-	default:
-		return ""
 	}
+
+	// Check for less explicit errors
+	if strings.Contains(err.Error(), "certificate is not trusted") {
+		return unknownAuthority
+	}
```
Comment (greedy52) [inline lib/utils/cli.go:248]: nit: are we doing the string comparison because it's an aggregate? If so, is it possible to get individual errors out of it?

File: tool/tsh/tsh.go (hunk 1 above)
Comment (greedy52) [reply tool/tsh/tsh.go:3171]: One corner case I see is when things time out in 2 seconds, it doesn't mean it's not reachable.

File: lib/utils/cli.go (hunk 4 above)
Comment (strideynet) [reply lib/utils/cli.go:248]: Unfortunately, my original plan was to use `errors.Is/errors.As` here, as I made changes to the Aggregate error type to properly support these, however, I was foiled by the Go stdlib. The x509 package makes generous use of `errors.New` rather than better error types.

File: tool/tsh/resolve_default_addr.go [hunk 5]
```diff
@@ -156,6 +156,7 @@ func pickDefaultAddr(ctx context.Context, insecure bool, host string, ports []in
 	ticker := time.NewTicker(250 * time.Millisecond)
 	defer ticker.Stop()
 
+	errors := []error{}
```
[the remark this answers is not in the document]
Comment (strideynet) [reply tool/tsh/resolve_default_addr.go]: [8f4e8d2](https://github.com/gravitational/teleport/pull/14985/commits/8f4e8d222ac836315e1dfff7e96afa769aeda246)

File: lib/utils/cli.go (hunk 3 above)
Comment (strideynet) [reply lib/utils/cli.go]: [8f4e8d2](https://github.com/gravitational/teleport/pull/14985/commits/8f4e8d222ac836315e1dfff7e96afa769aeda246)

File: lib/utils/cli.go (hunk 2 above)
Comment (strideynet) [reply lib/utils/cli.go]: [8f4e8d2](https://github.com/gravitational/teleport/pull/14985/commits/8f4e8d222ac836315e1dfff7e96afa769aeda246)

**Review by rosstimothy — APPROVED** [review]

**Comment by strideynet** [comment]
> One corner case I see is when things time out in 2 seconds, it doesn't mean it's not reachable.

In which case, if I'm removing the fallback, I probably ought to raise the time out. If it's running them concurrently it shouldn't be an issue to raise it since if one succeeds, the other will be cancelled.

File: lib/utils/cli.go [hunk 6]
```diff
@@ -227,7 +220,6 @@ func formatCertError(err error) string {
 
   If you know the certificate is self-signed and would like to ignore this
   error use the --insecure flag.
-
```
Comment (greedy52) [inline lib/utils/cli.go:230]: revert deleted line?

File: lib/utils/cli.go [hunk 7]
```diff
@@ -236,15 +228,27 @@ func formatCertError(err error) string {
...
+			innerError.Host,
+			innerError.Error(),
+			"try a different hostname for --proxy or specify --insecure flag if you know what you're doing.")
+	case x509.UnknownAuthorityError:
+		return unknownAuthority
 	case x509.CertificateInvalidError:
 		return fmt.Sprintf(`WARNING:
-
   The certificate presented by the proxy is invalid: %v.
-
```
Comment (greedy52) [inline lib/utils/cli.go:243]: revert deleted lines?

**Review by greedy52 — APPROVED** [review]

File: lib/utils/cli.go (hunk 7 above)
Comment (strideynet) [reply lib/utils/cli.go:243]: Sorry, not sure how I missed these.
