### PR TITLE
fix TestGetHeadlessAuthentication

### LINKED ISSUE #54600: `TestGetHeadlessAuthentication` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/14889061716/job/41816328966#step:6:2190

#### Relevant snippet

```
    auth_with_roles_test.go:8104: 
        	Error Trace:	/__w/teleport/teleport/lib/auth/auth_with_roles_test.go:8104
        	            				/__w/teleport/teleport/lib/auth/auth_with_roles_test.go:8158
        	Error:      	Error "rpc error: code = DeadlineExceeded desc = stream terminated by RST_STREAM with error code: CANCEL" does not contain "context deadline exceeded"
        	Test:       	TestGetHeadlessAuthentication/NOK_different_user
        	Messages:   	expected context deadline error but got: rpc error: code = DeadlineExceeded desc = stream terminated by RST_STREAM with error code: CANCEL
```

### PR DESCRIPTION
**Pull request by GavinFrazar**
Fixes https://github.com/gravitational/teleport/issues/54600
- https://github.com/gravitational/teleport/issues/54600

### CODE REVIEW

**Review by mvbrock — APPROVED** [review]

File: lib/auth/auth_with_roles_test.go [hunk 1]
```diff
@@ -8081,8 +8081,13 @@ func TestGetHeadlessAuthentication(t *testing.T) {
 			// handle context canceled error ambiguity
 			// TODO(gavin): remove this after this issue is fixed:
 			// https://github.com/grpc/grpc-go/issues/8281
```
Comment (zmb3) [inline lib/auth/auth_with_roles_test.go:8083]: Does this still apply? the linked issue is now closed.

**Review by zmb3 — APPROVED** [review]

**Comment by zmb3** [comment]
@GavinFrazar I'm still hitting this on branch/v16 backports, can you please backport the fix to all relevant branches?
