### PR TITLE
fix aws rds discovery invalid engine filter

### LINKED ISSUE #17533: AWS RDS Discovery fails with invalid parameter in AWS API Request
Expected behavior:

Starting a Teleport Node which runs the `db_service` for AWS RDS Discovery should work and find databases.

Current behavior:

Starting a Teleport Node with `db_service` prints a stack trace on boot saying:

```
teleport[32435]: ERROR REPORT:
teleport[32435]: Original Error: *awserr.requestError InvalidParameterValue: Unrecognized engine name: aurora
teleport[32435]: status code: 400, request id: *snip*
teleport[32435]: Stack Trace:
teleport[32435]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/rds.go:169 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*rdsAuroraClustersFetcher)
teleport[32435]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:120 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).fetchAndSend
teleport[32435]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:104 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).Start
teleport[32435]: /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
teleport[32435]: User Message: InvalidParameterValue: Unrecognized engine name: aurora
teleport[32435]: status code: 400, request id: *snip*] watchers/watcher.go:129
```

Bug details:
- Teleport version
```
tsh version
Teleport v10.3.2 git: go1.19.2
Proxy version: 10.1.9
```
- Recreation steps
Run a Teleport node with e.g. the following config for `db_service`:
```yaml
db_service:
  enabled: yes
  resources:
  - labels:
      environment: qa
  # Matchers for registering AWS-hosted databases.
  aws:
  # RDS/Aurora databases auto-discovery.
  # For more information about RDS/Aurora auto-discovery: https://goteleport.com/docs/database-access/guides/rds/
  - types: ["rds"]
    # AWS regions to register databases from.
    regions:
    - {REGION}
    # AWS resource tags to match when registering databases.
    tags:
      teleport-access: true
      environment: qa
```
- Debug logs
<details>
  <summary>debug logs</summary>

```
systemd[1]: Stopping Teleport SSH Node Service...
teleport[8981]: 2022-10-18T09:31:54Z INFO [PROC:1]    Got signal "terminated", exiting immediately. pid:8981.1 service/signals.go:83
systemd[1]: Stopped Teleport SSH Node Service.
systemd[1]: Started Teleport SSH Node Service.
teleport[9762]: 2022-10-18T09:31:54Z DEBU [SQLITE]    Connected to: file:%2Fvar%2Flib%2Fteleport%2Fproc%2Fsqlite.db?_busy_timeout=10000&_sync=FULL&_txlock=immediate, poll stream period: 1s lite/lite.go:246
teleport[9762]: 2022-10-18T09:31:54Z DEBU [SQLITE]    journal_mode=delete, synchronous=2, busy_timeout=10000 lite/lite.go:293
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:readyz.monitor service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z INFO [PROC:1]    Service diag is creating new listener on 127.0.0.1:3000. pid:9762.1 service/signals.go:212
teleport[9762]: 2022-10-18T09:31:54Z INFO [DIAG:1]    Starting diagnostic service on 127.0.0.1:3000. pid:9762.1 service/service.go:2703
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:diagnostic.service service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:diagnostic.shutdown service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:register.node service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:ssh.node service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:ssh.shutdown service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:register.db service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:db.init service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:common.rotate service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:register.instance service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:instance.init service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    No signal pipe to import, must be first Teleport process. pid:9762.1 service/service.go:1113
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:readyz.monitor service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:register.db service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:register.node service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:diagnostic.service service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:diagnostic.shutdown service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:db.init service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:common.rotate service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:register.instance service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:instance.init service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:ssh.node service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service has started. pid:9762.1 service:ssh.shutdown service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected state: never updated. pid:9762.1 service/connect.go:237
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected state: never updated. pid:9762.1 service/connect.go:237
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected state: never updated. pid:9762.1 service/connect.go:237
teleport[9762]: 2022-10-18T09:31:54Z INFO [PROC:1]    Connecting to the cluster example-teleport with TLS client certificate. pid:9762.1 service/connect.go:256
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to connect to Auth Server directly. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1052
teleport[9762]: 2022-10-18T09:31:54Z INFO [PROC:1]    Connecting to the cluster example-teleport with TLS client certificate. pid:9762.1 service/connect.go:256
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to connect to Auth Server directly. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1052
teleport[9762]: 2022-10-18T09:31:54Z INFO [PROC:1]    Connecting to the cluster example-teleport with TLS client certificate. pid:9762.1 service/connect.go:256
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to connect to Auth Server directly. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1052
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Failed to connect to Auth Server directly. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1058
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to discover reverse tunnel address. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1067
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to connect to Auth Server through tunnel. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1069
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Failed to connect to Auth Server directly. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1058
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to discover reverse tunnel address. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1067
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to connect to Auth Server through tunnel. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1069
teleport[9762]: 2022-10-18T09:31:54Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:54Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Failed to connect to Auth Server directly. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1058
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to discover reverse tunnel address. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1067
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Attempting to connect to Auth Server through tunnel. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1069
teleport[9762]: 2022-10-18T09:31:54Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:54Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:54Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:54Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:54Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:296
teleport[9762]: 2022-10-18T09:31:54Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:296
teleport[9762]: 2022-10-18T09:31:54Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:296
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected to Auth Server through tunnel. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1083
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected client: Identity(Instance, cert(60270730-6425-493f-b462-ceaaec60fcb3.example-teleport issued by example-teleport:267433341790791834760895412702658808193),trust root(example-teleport:267433341790791834760895412702658808193)) pid:9762.1 service/connect.go:202
teleport[9762]: 2022-10-18T09:31:54Z INFO [PROC:1]    Instance: features loaded from auth server: Kubernetes:true App:true DB:true OIDC:true SAML:true AccessControls:true AdvancedAccessWorkflows:true HSM:true Desktop:true  pid:9762.1 service/connect.go:90
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Broadcasting event. event:InstanceIdentity pid:9762.1 service/supervisor.go:376
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service is completed and removed. pid:9762.1 service:register.instance service/supervisor.go:245
teleport[9762]: 2022-10-18T09:31:54Z DEBU [INSTANCE:] Received event "InstanceIdentity". pid:9762.1 service/service.go:2089
teleport[9762]: 2022-10-18T09:31:54Z INFO [INSTANCE:] Successfully registered instance client. pid:9762.1 service/service.go:2101
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Broadcasting event. event:InstanceReady pid:9762.1 service/supervisor.go:376
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service is completed and removed. pid:9762.1 service:instance.init service/supervisor.go:245
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected to Auth Server through tunnel. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1083
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected client: Identity(Node, cert(60270730-6425-493f-b462-ceaaec60fcb3.example-teleport issued by example-teleport:267433341790791834760895412702658808193),trust root(example-teleport:267433341790791834760895412702658808193)) pid:9762.1 service/connect.go:202
teleport[9762]: 2022-10-18T09:31:54Z INFO [PROC:1]    Node: features loaded from auth server: Kubernetes:true App:true DB:true OIDC:true SAML:true AccessControls:true AdvancedAccessWorkflows:true HSM:true Desktop:true  pid:9762.1 service/connect.go:90
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Broadcasting event. event:SSHIdentity pid:9762.1 service/supervisor.go:376
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service is completed and removed. pid:9762.1 service:register.node service/supervisor.go:245
teleport[9762]: 2022-10-18T09:31:54Z DEBU [NODE:1]    Received event "SSHIdentity". pid:9762.1 service/service.go:2134
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Creating in-memory backend for [node]. pid:9762.1 service/service.go:1857
teleport[9762]: 2022-10-18T09:31:54Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected to Auth Server through tunnel. auth-addrs:[teleport.example.dev:443] pid:9762.1 service/connect.go:1083
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Connected client: Identity(Db, cert(60270730-6425-493f-b462-ceaaec60fcb3.example-teleport issued by example-teleport:267433341790791834760895412702658808193),trust root(example-teleport:267433341790791834760895412702658808193)) pid:9762.1 service/connect.go:202
teleport[9762]: 2022-10-18T09:31:54Z INFO [PROC:1]    Db: features loaded from auth server: Kubernetes:true App:true DB:true OIDC:true SAML:true AccessControls:true AdvancedAccessWorkflows:true HSM:true Desktop:true  pid:9762.1 service/connect.go:90
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Broadcasting event. event:DatabasesIdentity pid:9762.1 service/supervisor.go:376
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Service is completed and removed. pid:9762.1 service:register.db service/supervisor.go:245
teleport[9762]: 2022-10-18T09:31:54Z DEBU [DB:SERVIC] Received event "DatabasesIdentity". pid:9762.1 service/db.go:58
teleport[9762]: 2022-10-18T09:31:54Z DEBU [PROC:1]    Creating in-memory backend for [db:service]. pid:9762.1 service/service.go:1857
teleport[9762]: 2022-10-18T09:31:54Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:296
teleport[9762]: 2022-10-18T09:31:54Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:54Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:296
teleport[9762]: 2022-10-18T09:31:54Z INFO [NODE:1:CA] Cache "node" first init succeeded. cache/cache.go:725
teleport[9762]: 2022-10-18T09:31:54Z DEBU [BPF]       Enhanced session recording is not enabled, skipping. bpf/bpf.go:127
teleport[9762]: 2022-10-18T09:31:54Z DEBU [RESTRICTE] Restricted session is not enabled, skipping. restrictedsession/restricted.go:95
teleport[9762]: 2022-10-18T09:31:54Z DEBU [NODE:1]    Starting watch. pid:9762.1 resource-kind:lock services/watcher.go:183
teleport[9762]: 2022-10-18T09:31:54Z DEBU [SSH:NODE]  Supported ciphers: ["aes128-gcm@openssh.com" "chacha20-poly1305@openssh.com" "aes128-ctr" "aes192-ctr" "aes256-ctr"]. sshutils/server.go:221
teleport[9762]: 2022-10-18T09:31:55Z DEBU [SSH:NODE]  Supported KEX algorithms: ["curve25519-sha256" "curve25519-sha256@libssh.org" "ecdh-sha2-nistp256" "ecdh-sha2-nistp384" "ecdh-sha2-nistp521" "diffie-hellman-group14-sha256"]. sshutils/server.go:231
teleport[9762]: 2022-10-18T09:31:55Z DEBU [SSH:NODE]  Supported MAC algorithms: ["hmac-sha2-256-etm@openssh.com" "hmac-sha2-256"]. sshutils/server.go:241
teleport[9762]: 2022-10-18T09:31:55Z INFO [DB:SERVIC] Cache "db" first init succeeded. cache/cache.go:725
teleport[9762]: 2022-10-18T09:31:55Z INFO [NODE]      debug -> starting control-stream based heartbeat. regular/sshserver.go:802
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Creating directory /var/lib/teleport/log. pid:9762.1 service/service.go:2452
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Setting directory /var/lib/teleport/log owner to 0:4. pid:9762.1 service/service.go:2461
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload. pid:9762.1 service/service.go:2452
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Setting directory /var/lib/teleport/log/upload owner to 0:4. pid:9762.1 service/service.go:2461
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/streaming. pid:9762.1 service/service.go:2452
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Setting directory /var/lib/teleport/log/upload/streaming owner to 0:4. pid:9762.1 service/service.go:2461
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/streaming/default. pid:9762.1 service/service.go:2452
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Setting directory /var/lib/teleport/log/upload/streaming/default owner to 0:4. pid:9762.1 service/service.go:2461
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:fileuploader.service service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:fileuploader.shutdown service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:fileuploadcompleter.service service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:fileuploadcompleter.shutdown service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Starting agent pool 60270730-6425-493f-b462-ceaaec60fcb3.example-teleport.example-teleport... cluster:example-teleport reversetunnel/agentpool.go:240
teleport[9762]: 2022-10-18T09:31:55Z INFO [NODE:1]    Service is starting in tunnel mode. pid:9762.1 service/service.go:2363
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Broadcasting event. event:NodeReady pid:9762.1 service/supervisor.go:376
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Creating directory /var/lib/teleport/log. pid:9762.1 service/service.go:2452
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Setting directory /var/lib/teleport/log owner to 0:4. pid:9762.1 service/service.go:2461
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload. pid:9762.1 service/service.go:2452
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Setting directory /var/lib/teleport/log/upload owner to 0:4. pid:9762.1 service/service.go:2461
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/streaming. pid:9762.1 service/service.go:2452
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Setting directory /var/lib/teleport/log/upload/streaming owner to 0:4. pid:9762.1 service/service.go:2461
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Creating directory /var/lib/teleport/log/upload/streaming/default. pid:9762.1 service/service.go:2452
teleport[9762]: 2022-10-18T09:31:55Z INFO [AUDIT:1]   Setting directory /var/lib/teleport/log/upload/streaming/default owner to 0:4. pid:9762.1 service/service.go:2461
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:fileuploader.service service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:fileuploader.shutdown service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:fileuploadcompleter.service service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:fileuploadcompleter.shutdown service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [DB:SERVIC] Starting database resource watcher. db/watcher.go:71
teleport[9762]: 2022-10-18T09:31:55Z DEBU             Initializing AWS session for region REGION. common/cloud.go:223
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Starting agent pool 60270730-6425-493f-b462-ceaaec60fcb3.example-teleport.example-teleport... cluster:example-teleport reversetunnel/agentpool.go:240
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Adding service to supervisor. pid:9762.1 service:db.stop service/supervisor.go:207
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Broadcasting event. event:DatabasesReady pid:9762.1 service/supervisor.go:376
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Broadcasting mapped event. in:DatabasesReady out:EventMapping(in=[InstanceReady NodeReady DatabasesReady], out=TeleportReady) pid:9762.1 service/supervisor.go:401
teleport[9762]: 2022-10-18T09:31:55Z INFO [DB:SERVIC] Database service has successfully started: []. pid:9762.1 service/db.go:283
teleport[9762]: 2022-10-18T09:31:55Z INFO [PROC:1]    The new service has started successfully. Starting syncing rotation status with period 10m0s. pid:9762.1 service/connect.go:671
teleport[9762]: 2022-10-18T09:31:55Z DEBU             Attempting GET teleport.example.dev:443/webapi/find webclient/webclient.go:115
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:fileuploader.service service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:fileuploader.shutdown service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:fileuploadcompleter.service service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:fileuploadcompleter.shutdown service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:fileuploader.service service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:fileuploader.shutdown service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:fileuploadcompleter.service service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:fileuploadcompleter.shutdown service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z DEBU [DB:SERVIC] Starting watch. pid:9762.1 resource-kind:lock services/watcher.go:183
teleport[9762]: 2022-10-18T09:31:55Z DEBU [DB:SERVIC] Starting watch. resource-kind:db services/watcher.go:183
teleport[9762]: 2022-10-18T09:31:55Z DEBU             Initializing AWS session for region . common/cloud.go:223
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Teleport component "db:service" has started. pid:9762.1 service/state.go:115
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Service has started. pid:9762.1 service:db.stop service/supervisor.go:268
teleport[9762]: 2022-10-18T09:31:55Z INFO [IAM]       Started IAM configurator service. cloud/iam.go:114
teleport[9762]: 2022-10-18T09:31:55Z DEBU [CLOUDUSER] Starting cloud users service. users/users.go:147
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROC:1]    Teleport component "node" has started. pid:9762.1 service/state.go:115
teleport[9762]: 2022-10-18T09:31:55Z DEBU [DB:SERVIC] Reconciling 0 current resources with 0 new resources. services/reconciler.go:102
teleport[9762]: 2022-10-18T09:31:55Z DEBU [WATCHER:C] Starting cloud databases watcher. watchers/watcher.go:103
teleport[9762]: 2022-10-18T09:31:55Z DEBU             'teleport-service' group not found, not deleting users srv/usermgmt.go:278
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:example-teleport reversetunnel/agentpool.go:317
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Starting agent {teleport.example.dev:443 tcp } leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:285
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Changing state initial -> connecting. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:273
teleport[9762]: 2022-10-18T09:31:55Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:296
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:example-teleport reversetunnel/agentpool.go:317
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Starting agent {teleport.example.dev:443 tcp } leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:285
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Changing state initial -> connecting. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:273
teleport[9762]: 2022-10-18T09:31:55Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:296
teleport[9762]: 2022-10-18T09:31:55Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:296
teleport[9762]: 2022-10-18T09:31:55Z DEBU [WATCHER:C] Skipping fetcher rdsDBInstancesFetcher(Region=REGION, Labels=map[environment:[qa] teleport-access:[true]]). error:[
teleport[9762]: ERROR REPORT:
teleport[9762]: Original Error: *trace.AccessDeniedError AccessDenied: User: arn:aws:sts::ACCOUNT_ID:assumed-role/example-teleport-qa-db-agent/i-0b69627bdae090b67 is not authorized to perform: rds:DescribeDBInstances on resource: arn:aws:rds:REGION:ACCOUNT_ID:db:* because no identity-based policy allows the rds:DescribeDBInstances action
teleport[9762]: status code: 403, request id: 008a4e08-0269-4e4e-9ea5-c345d246ded1
teleport[9762]: Stack Trace:
teleport[9762]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/rds.go:84 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*rdsDBInstancesFetcher).Get
teleport[9762]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:120 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).fetchAndSend
teleport[9762]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:104 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).Start
teleport[9762]: /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
teleport[9762]: User Message: AccessDenied: User: arn:aws:sts::ACCOUNT_ID:assumed-role/example-teleport-qa-db-agent/i-0b69627bdae090b67 is not authorized to perform: rds:DescribeDBInstances on resource: arn:aws:rds:REGION:ACCOUNT_ID:db:* because no identity-based policy allows the rds:DescribeDBInstances action
teleport[9762]: status code: 403, request id: 008a4e08-0269-4e4e-9ea5-c345d246ded1] watchers/watcher.go:125
teleport[9762]: 2022-10-18T09:31:55Z ERRO [WATCHER:C] rdsAuroraClustersFetcher(Region=REGION, Labels=map[environment:[qa] teleport-access:[true]]) failed. error:[
teleport[9762]: ERROR REPORT:
teleport[9762]: Original Error: *awserr.requestError InvalidParameterValue: Unrecognized engine name: aurora
teleport[9762]: status code: 400, request id: ab301d3d-3666-420b-9878-77bd4bb99972
teleport[9762]: Stack Trace:
teleport[9762]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/rds.go:169 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*rdsAuroraClustersFetcher).Get
teleport[9762]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:120 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).fetchAndSend
teleport[9762]: /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:104 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).Start
teleport[9762]: /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
teleport[9762]: User Message: InvalidParameterValue: Unrecognized engine name: aurora
teleport[9762]: status code: 400, request id: ab301d3d-3666-420b-9878-77bd4bb99972] watchers/watcher.go:129
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Changing state connecting -> connected. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:273
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Active agent count: 1 cluster:example-teleport reversetunnel/agentpool.go:442
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Active agent count: 1 cluster:example-teleport reversetunnel/agentpool.go:442
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Discovery request channel opened: teleport-discovery. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:593
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] handleDiscovery requests channel. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:616
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Received discovery request: [ff4e37c0-dbc2-4e95-823b-6ab93ca2f5b0] leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:644
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Changing state connecting -> connected. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:273
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Active agent count: 1 cluster:example-teleport reversetunnel/agentpool.go:442
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Active agent count: 1 cluster:example-teleport reversetunnel/agentpool.go:442
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Discovery request channel opened: teleport-discovery. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:593
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] handleDiscovery requests channel. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:616
teleport[9762]: 2022-10-18T09:31:55Z DEBU [PROXY:AGE] Received discovery request: [ff4e37c0-dbc2-4e95-823b-6ab93ca2f5b0] leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:644
teleport[9762]: 2022-10-18T09:32:55Z DEBU [PROXY:AGE] Ping -> XXX:443. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:548
teleport[9762]: 2022-10-18T09:32:55Z DEBU [PROXY:AGE] Ping -> XXX:443. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:548
teleport[9762]: 2022-10-18T09:33:55Z DEBU [PROXY:AGE] Ping -> XXX:443. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:548
teleport[9762]: 2022-10-18T09:33:55Z DEBU [PROXY:AGE] Ping -> XXX:443. leaseID:1 target:teleport.example.dev:443 cluster:example-teleport reversetunnel/agent.go:548
```

</details>

Note that there is an IAM "not allowed" in the debug logs because we don't allow Teleport to describe DB Instances, but it does have permission to describe DB Clusters.

I think this might be because the filter query tries using the value `aurora` for engine value, which fails in the AWS CLI as well:
```
aws rds describe-db-clusters --filters Name=engine,Values=aurora

An error occurred (InvalidParameterValue) when calling the DescribeDBClusters operation: Unrecognized engine name: aurora
```
In the same way as a non-existing engine fails:
```
aws rds describe-db-clusters --filters Name=engine,Values=not-a-valid-engine

An error occurred (InvalidParameterValue) when calling the DescribeDBClusters operation: Unrecognized engine name: not-a-valid-engine
```

But for example `Values=aurora-postgresql` works fine.

This "aurora" value comes from here: https://github.com/gravitational/teleport/blob/master/lib/services/database.go#L1009, and it might be something AWS has recently removed?

EDIT:
Related to the previous statement, the following API query does **not** list "aurora" as a DB engine:
```
aws rds describe-db-engine-versions | jq '.DBEngineVersions[].Engine' | sort | uniq
"aurora-mysql"
"aurora-postgresql"
"custom-sqlserver-ee"
"custom-sqlserver-se"
"custom-sqlserver-web"
"mariadb"
"mysql"
"neptune"
"oracle-ee"
"oracle-ee-cdb"
"oracle-se2"
"oracle-se2-cdb"
"postgres"
"sqlserver-ee"
"sqlserver-ex"
"sqlserver-se"
"sqlserver-web"
```
EDIT2: This seems to be specific to some regions... e.g. `eu-north-1`.

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #17533

## What
This PR changes AWS RDS Discovery to handle unrecognized engine names in filters gracefully.

## How
When AWS returns an error like `Unrecognized engine name: aurora`, we detect this as an engine name filter error and fallback to querying for all DB engine versions in the region. Then we filter Teleport-supported engine names that are not found in the results, and retry the describe instances/clusters RDS API calls with the reduced filter engine names. If this *stilll* fails with unrecognized engine name (never seen this/don't know if it can actually happen), then the fetcher returns an error and we skip that fetcher - this "unrecognized engine" error has been observed to be region-specific and intermittent - we should not stop the watcher just because a single fetcher in one region failed.

## Tests
A great deal of this PR is just tests and mocking changes. I had to mock the `DescribeDBEngineVersionsPagesWithContext` API and I also needed to make our `Describe*` mock APIs respect engine filters - this was needed to verify behavior in tests.

I fixed up the watcher tests and added two new tests: one for handling unrecognized engines gracefully with a retry, and one for verifying that when the retry fails we just skip the fetcher instead of quitting.

### CODE REVIEW

File: lib/srv/db/cloud/watchers/rds.go [hunk 1]
```diff
@@ -268,24 +286,84 @@ func (f *rdsAuroraClustersFetcher) String() string {
...
+		return nil, trace.Wrap(err)
+	}
+	recognized := make(map[string]struct{})
+	for _, result := range engineVersions {
+		if result == nil || result.Engine == nil {
+			continue
+		}
+		recognized[*result.Engine] = struct{}{}
+	}
+	engines := []string{}
```
Comment (smallinsky) [inline lib/srv/db/cloud/watchers/rds.go:359]: nit:
```suggestion
	var engines string{}
```
https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices

File: lib/srv/db/cloud/watchers/rds.go [hunk 2]
```diff
@@ -268,24 +286,84 @@ func (f *rdsAuroraClustersFetcher) String() string {
...
-			services.RDSEngineAuroraPostgres}),
-	}}
+		Name:   aws.String("engine"),
+		Values: aws.StringSlice(engines),
+	}}, nil
+}
+
+// recognizedRDSEngines returns the names of engines which are recognized in the region of the RDS client,
+// filtered to only include Teleport supported engines.
+func recognizedRDSEngines(ctx context.Context, rdsClient rdsiface.RDSAPI, supportedEngines []string, maxPages int) ([]string, error) {
```
Comment (smallinsky) [inline lib/srv/db/cloud/watchers/rds.go:339]: can we split this function into to functions: 
* fetch supported engine from API
* filter out logic

File: lib/srv/db/cloud/watchers/rds.go [hunk 3]
```diff
@@ -268,24 +286,84 @@ func (f *rdsAuroraClustersFetcher) String() string {
...
+		services.RDSEngineAuroraPostgres,
+	}
+	if !checkFilters {
+		return []*rds.Filter{{
+			Name:   aws.String("engine"),
+			Values: aws.StringSlice(supportedEngines),
+		}}, nil
+	}
+
+	engines, err := recognizedRDSEngines(ctx, rdsClient, supportedEngines, maxPages)
```
Comment (smallinsky) [inline lib/srv/db/cloud/watchers/rds.go:327]: Could you add a comment describing describing the `recognizedRDSEngines` logic.

File: lib/srv/db/cloud/watchers/rds.go [hunk 4]
```diff
@@ -173,7 +182,12 @@ func (f *rdsAuroraClustersFetcher) Get(ctx context.Context) (types.Databases, er
 
 // getAuroraDatabases returns a list of database resources representing RDS clusters.
 func (f *rdsAuroraClustersFetcher) getAuroraDatabases(ctx context.Context) (types.Databases, error) {
-	clusters, err := getAllDBClusters(ctx, f.cfg.RDS, common.MaxPages)
+	clusters, err := getAllDBClusters(ctx, f.cfg.RDS, common.MaxPages, false)
+	if common.IsUnrecognizedAWSEngineNameError(err) {
+		f.log.WithError(err).Warn("Teleport supports an engine which is unrecognized in this AWS region. Querying engine versions.")
+		// fallback to try to describe only clusters with engines recognized in the AWS region.
+		clusters, err = getAllDBClusters(ctx, f.cfg.RDS, common.MaxPages, true)
```
Comment (smallinsky) [inline lib/srv/db/cloud/watchers/rds.go:189]: What would you say about moving the fallback logic inside `getAllDBClusters` ?

File: lib/srv/db/common/errors.go [hunk 5]
```diff
@@ -236,3 +236,14 @@ agent's service principal. See: https://goteleport.com/docs/database-access/guid
...
+// IsUnrecognizedAWSEngineNameError checks if the err is non-nil and came from using an engine filter that the
+// AWS region does not recognize.
+func IsUnrecognizedAWSEngineNameError(err error) (res bool) {
+	if err == nil {
+		res = false
+		return
+	}
+	res = strings.Contains(strings.ToLower(err.Error()), "unrecognized engine name")
+	return
+}
```
Comment (smallinsky) [inline lib/srv/db/common/errors.go:249]: nit: 6 lines vs 4 lines 😄 : 
```suggestion
func IsUnrecognizedAWSEngineNameError(err error) bool {
	if err == nil {
		return false
	}
	return strings.Contains(strings.ToLower(err.Error()), "unrecognized engine name")
}
```

File: lib/srv/db/cloud/mocks.go [hunk 6]
```diff
@@ -618,3 +663,72 @@ func (m *MemoryDBMock) UpdateUserWithContext(_ aws.Context, input *memorydb.Upda
...
+
+// engineFilterSet builds a string set of engine names from a list of RDS filters.
+func engineFilterSet(filters []*rds.Filter) map[string]struct{} {
+	out := make(map[string]struct{})
+	for _, f := range filters {
+		if *f.Name != "engine" {
+			continue
+		}
+		for _, v := range f.Values {
+			out[*v] = struct{}{}
```
Comment (smallinsky) [inline lib/srv/db/cloud/mocks.go:718]:
```suggestion
			out[aws.StringValue(v)] = struct{}{}
```

**Comment by greedy52** [comment]
A new API also means we have to update IAM permissions for db configurator tool and we have to ask existing users to add the new permission. I think in this case it's not that bad since only ppl with this problem need to update their agent's IAM permissions.

One alternative i think we can just call the current API, but with one engine type per call. We triple the number of calls but it's not that many compared to some other discovery we have to make calls per db instance. What do you think?

I am also ok with the current approach if we decided to do the fallback. Make sure to update the configurator.

File: lib/srv/db/cloud/watchers/rds.go [hunk 7]
```diff
@@ -88,7 +88,12 @@ func (f *rdsDBInstancesFetcher) Get(ctx context.Context) (types.Databases, error
 
 // getRDSDatabases returns a list of database resources representing RDS instances.
 func (f *rdsDBInstancesFetcher) getRDSDatabases(ctx context.Context) (types.Databases, error) {
-	instances, err := getAllDBInstances(ctx, f.cfg.RDS, common.MaxPages)
+	instances, err := getAllDBInstances(ctx, f.cfg.RDS, common.MaxPages, false)
+	if common.IsUnrecognizedAWSEngineNameError(err) {
```
Comment (greedy52) [inline lib/srv/db/cloud/watchers/rds.go:92]: do you think if we can remember this decision so we don't have to fall back every time?

File: lib/srv/db/common/errors.go (hunk 5 above)
Comment (GavinFrazar) [reply lib/srv/db/common/errors.go:249]: oops, this was a leftover of some debugging I was doing with a deferred function to print the result lol. Yes will fix.

File: lib/srv/db/cloud/watchers/rds.go (hunk 7 above)
Comment (GavinFrazar) [reply lib/srv/db/cloud/watchers/rds.go:92]: I wanted to avoid the extra complexity of caching, especially since the problem with AWS was intermittent and eventually resolved itself. You're suggesting an optimization, but I don't think it's likely to ever be a performance problem, and we should wait and see if it becomes one before adding a lot of extra logic around caching

**Comment by GavinFrazar** [comment]
> A new API also means we have to update IAM permissions for db configurator tool and we have to ask existing users to add the new permission. I think in this case it's not that bad since only ppl with this problem need to update their agent's IAM permissions.
> 
> One alternative i think we can just call the current API, but with one engine type per call. We triple the number of calls but it's not that many compared to some other discovery we have to make calls per db instance. What do you think?
> 
> I am also ok with the current approach if we decided to do the fallback by checking supported engines. Make sure to update the configurator.
> 
> (-- update, or maybe the fallback can just do the separate calls with the same API, without calling the get engine version)

Good point about the permissions. I think this solution is better for the happy-path in RDS discovery since the alternative triples the number of API calls always, but does requires the extra permissions... I think I'd prefer we just add this permission - I can't think of a reason why any customer would be opposed to allow it

File: lib/srv/db/cloud/watchers/rds.go (hunk 4 above)
Comment (GavinFrazar) [reply lib/srv/db/cloud/watchers/rds.go:189]: That's where I put the fallback logic in the first place, but then I wanted to log the error if it happens... so if I move it in there I need to pass the fetcher's logger in as well

File: lib/srv/db/cloud/watchers/rds.go (hunk 3 above)
Comment (GavinFrazar) [reply lib/srv/db/cloud/watchers/rds.go:327]: sure

File: lib/srv/db/cloud/watchers/rds.go (hunk 2 above)
Comment (GavinFrazar) [reply lib/srv/db/cloud/watchers/rds.go:339]: I split out the engine version API call and engine name string set construction into another func

**Comment by greedy52** [comment]
> I can't think of a reason why any customer would be opposed to allow it

No, i don't think it's a big deal either for customer to grant us permission for that. Just for existing users they probably don't know they are missing a permission. well, i guess if they happen to run into this problem and observe the log, they will know =p.

File: lib/srv/db/cloud/watchers/rds.go (hunk 7 above)
Comment (greedy52) [reply lib/srv/db/cloud/watchers/rds.go:93]: my bad, i thought this is a permanent thing where a region is retiring old aurora types. seems that's not the case. Then agreed to keep it simple 👍

File: lib/srv/db/cloud/watchers/rds.go [hunk 8]
```diff
@@ -268,24 +287,96 @@ func (f *rdsAuroraClustersFetcher) String() string {
...
+	// now filter for supported + recognized engine names.
+	var engines []string
+	for _, engine := range supportedEngines {
+		if _, ok := recognized[engine]; ok {
+			engines = append(engines, engine)
+		}
+	}
+	// important that we don't return 0 engine names, as that would apply no filtering at all in AWS DescribeDBClusters/Instances calls.
+	if len(engines) == 0 {
+		return nil, trace.NotFound("Teleport supports engine names %v but none are recognized in this region.", supportedEngines)
```
Comment (greedy52) [inline lib/srv/db/cloud/watchers/rds.go:355]: nit
```suggestion
		return nil, trace.NotFound("Teleport supports engine names %v but none are recognized in this region", supportedEngines)
```

File: lib/srv/db/cloud/watchers/watcher.go [hunk 9]
```diff
@@ -126,7 +127,9 @@ func (w *Watcher) fetchAndSend() {
 			// others. This is acceptable, thus continue to other fetchers.
 			// DB agent may also query for resources that do not exist. This is ok.
 			// If the resource is created in the future, we will fetch it then.
-			if trace.IsAccessDenied(err) || trace.IsNotFound(err) {
+			// DB agent may be run into "unrecognized" engine filters in certain regions.
+			// This is also ok, other regions may be unaffected.
+			if trace.IsAccessDenied(err) || trace.IsNotFound(err) || common.IsUnrecognizedAWSEngineNameError(err) {
```
Comment (greedy52) [inline lib/srv/db/cloud/watchers/watcher.go:132]: doesn't rds and aurora fetcher capture the unrecognized error inside already?

**Review by greedy52 — APPROVED** [review]
lets also add the permission to the database configurator

https://github.com/gravitational/teleport/blob/1ab74c113028186d9e6cf874a4cf63990eb35994/lib/configurators/aws/aws.go#L72-L75

File: lib/srv/db/cloud/watchers/watcher.go (hunk 9 above)
Comment (GavinFrazar) [reply lib/srv/db/cloud/watchers/watcher.go:132]: this is to cover the case where the describe engines and retry still fails with "unrecognized engine name" - I haven't seen that happen, but if it does I'd prefer we just skip the fetcher. I considered this case because this unrecognized error shouldn't have happened in the first place - AWS documents the engine name "aurora" as a valid engine name - so I'm just covering my bases here

File: lib/srv/db/cloud/watchers/rds.go [hunk 10]
```diff
@@ -268,24 +287,96 @@ func (f *rdsAuroraClustersFetcher) String() string {
...
+	}
+	return engines, nil
+}
+
+// getRecognizedRDSEngines gets all engine versions within an AWS region and builds a string set of AWS recognized engine names.
+func getRecognizedRDSEngines(ctx context.Context, rdsClient rdsiface.RDSAPI, maxPages int) (map[string]struct{}, error) {
+	var engines []string
+	var pageNum int
+	// https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#RDS.DescribeDBEngineVersionsPages
+	err := rdsClient.DescribeDBEngineVersionsPagesWithContext(ctx, &rds.DescribeDBEngineVersionsInput{},
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply lib/srv/db/cloud/watchers/rds.go:365]: hard to say if this takes longer than the "try each engine one at a time" approach because it probably depends on how many instances/clusters you have in AWS. I believe each page is 100 items

[the remark this answers is not in the document]
Comment (greedy52) [reply lib/srv/db/cloud/watchers/rds.go:365]: well if there are a lot instances/clusters, the next describe-call after the get-engine-version-call will be slow too 😉

File: lib/srv/db/cloud/watchers/rds.go [hunk 11]
```diff
@@ -266,26 +284,60 @@ func (f *rdsAuroraClustersFetcher) String() string {
...
-			services.RDSEnginePostgres,
-			services.RDSEngineMySQL,
-			services.RDSEngineMariaDB}),
-	}}
+func rdsInstanceEngines() []string {
+	return []string{
+		services.RDSEnginePostgres,
+		services.RDSEngineMySQL,
+		services.RDSEngineMariaDB,
+	}
```
Comment (greedy52) [inline lib/srv/db/cloud/watchers/rds.go:294]: nitpick: these probably can be just `var rdsInstanceEngines = []string{...}`?

**Review by greedy52 — APPROVED** [review]
Thanks for updating this 😄. I don't think time is wasted as now we know how the engine version thing works it will likely be handy in the future.

**Review by smallinsky — APPROVED** [review]

File: lib/srv/db/cloud/watchers/rds.go (hunk 11 above)
Comment (GavinFrazar) [reply lib/srv/db/cloud/watchers/rds.go:294]: I thought the same, but I wanted to make it const which is unfortunately not possible in Go. I think mutable globals are a code smell

File: lib/srv/db/cloud/mocks.go [hunk 12]
```diff
@@ -618,3 +647,72 @@ func (m *MemoryDBMock) UpdateUserWithContext(_ aws.Context, input *memorydb.Upda
...
+				return trace.Errorf("unrecognized engine name %q", *v)
+			}
+		}
+	}
+	return nil
+}
+
+// applyInstanceFilters filters RDS DBInstances using the provided RDS filters.
+func applyInstanceFilters(in []*rds.DBInstance, filters []*rds.Filter) ([]*rds.DBInstance, error) {
+	out := []*rds.DBInstance{}
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply lib/srv/db/cloud/mocks.go:672]: I've been trying to be mindful of avoiding this mistake but it still creeps in 😄

File: lib/srv/db/common/errors.go [hunk 13]
```diff
@@ -236,3 +236,14 @@ agent's service principal. See: https://goteleport.com/docs/database-access/guid
 		return trace.Wrap(err)
 	}
 }
+
+// IsUnrecognizedAWSEngineNameError checks if the err is non-nil and came from using an engine filter that the
+// AWS region does not recognize.
+func IsUnrecognizedAWSEngineNameError(err error) (res bool) {
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply lib/srv/db/common/errors.go]: I debugged to see the type of error.

The err is an `awserr.requestError`, it's not wrapping an `InvalidParameterValue` error. The "InvalidParamterValue" is a part of the error's string content. Since this fix is specific to unrecognized engine names, I think I'd prefer to just check for the "Unrecognized engine name" substring in the error message

File: lib/srv/db/cloud/watchers/rds.go [hunk 14]
```diff
@@ -266,26 +284,60 @@ func (f *rdsAuroraClustersFetcher) String() string {
...
+
+// rdsFilterFn is a function that takes RDS filters and performs some operation with them, returning any error encountered.
+type rdsFilterFn func([]*rds.Filter) error
+
+// retryWithIndividualEngineFilters is a helper error handling function for AWS RDS unrecognized engine name filter errors,
+// that will call the provided RDS querying function with filters, check the returned error,
+// and if the error is an AWS unrecognized engine name error then it will retry once by calling the function with one filter
+// at a time. If any error other than an AWS unrecognized engine name error occurs, this function will return that error
+// without retrying, or skip retrying subsequent filters if it has already started to retry.
+func retryWithIndividualEngineFilters(log logrus.FieldLogger, engines []string, fn rdsFilterFn) error {
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply lib/srv/db/cloud/watchers/rds.go:323]: That being said, do you have an alternative name to suggest? I can't think of something more appropriate...

[the remark this answers is not in the document]
Comment (smallinsky) [reply lib/srv/db/cloud/watchers/rds.go:323]: Don't have strong suggestion but maybe `retryOn..WithIndividualEngineFilters`. As you pointed we use the same approach in `RetryWithRelogin` so leaving it up to you to decide.
