### PR TITLE
Fix Token creation TTL regression

### LINKED ISSUE #14916: --ttl is not honored when creating token
Expected behavior:
 When user pass `--ttl` at the time of token creation teleport should honor it. 

Current behavior:
Irrespective of what value users pass as `--ttl`; the token is generated with TTL 30 min. 

Recreation steps
```
root@teleport-cluster-bb55bf7bd-j42xz:/# tctl tokens add --type=node --ttl 8760h
The invite token: xxxx.
This token will expire in 525600 minutes.

Run this on the new node to join the cluster:

> teleport start \
   --roles=node \
   --token=xxx \
   --ca-pin=sha256:xxxx \
   --auth-server=xxxxx:3025

Please note:

  - This invitation token will expire in 525600 minutes
  - xxxx:3025 must be reachable from the new node

 root@teleport-cluster-bb55bf7bd-j42xz:/# tctl tokens ls 
Token                            Type    Labels Expiry Time (UTC)                 
-------------------------------- ------- ------ ---------------------------------    
xxxxxxx Node           27 Jul 22 10:34 UTC (29m53s)    
```

- Teleport version :  v10.0.2

### PR DESCRIPTION
**Pull request by strideynet**
Closes #14916 

`time.Time.Add` takes a value receiver rather than a pointer receiver, so we need to assign the returned value back to `expires`. This could have resulted in tokens being produced that would've expired immediately, but lower level logic in `tokenToItem` was detecting this short expiry and defaulting to `ProvisioningTokenTTL`.

Introduces a test to ensure we don't regress on this again.

### CODE REVIEW

File: lib/auth/auth.go [hunk 1]
```diff
@@ -2018,9 +2018,9 @@ func (a *Server) CreateWebSession(ctx context.Context, user string) (types.WebSe
 func (a *Server) GenerateToken(ctx context.Context, req *proto.GenerateTokenRequest) (string, error) {
 	expires := a.clock.Now().UTC()
 	if req.TTL != 0 {
-		expires.Add(req.TTL.Get())
+		expires = expires.Add(req.TTL.Get())
 	} else {
-		expires.Add(defaults.ProvisioningTokenTTL)
+		expires = expires.Add(defaults.ProvisioningTokenTTL)
 	}
```
Comment (tigrato) [inline lib/auth/auth.go:2024]:
```go
tokenTTL:=defaults.ProvisioningTokenTTL
if req.TTL != 0 {
tokenTTL= req.TTL
}
expires := a.clock.Now().UTC().Add( tokenTTL)
```

Seems easier to follow

Comment (strideynet) [reply lib/auth/auth.go:2024]: Agreed.

Comment (strideynet) [reply lib/auth/auth.go]: Addressed in [3e224d5](https://github.com/gravitational/teleport/pull/14936/commits/3e224d5d8361853b7981db505116931135d2637d)

**Review by zmb3 — APPROVED** [review]

**Review by tigrato — APPROVED** [review]
