### PR TITLE
Stop spamming "checking access list membership error" logs

### LINKED ISSUE #49054: Log spam when a user is locked on access lists checking
Expected behavior:

A user locked that isn't in access lists wouldn't include errors or much information.

Current behavior:

If a user is locked the log can spam on access lists checking. This repeats for multiple lines. In this case the instance only has two access lists and didn't have this user.

This repeats at least 4 times:
```bash
Nov 15 14:44:34 teleporthost teleport[286293]: 2024-11-15T14:44:34Z WARN [AUTH]      checking access list membership error:[
Nov 15 14:44:34 teleporthost teleport[286293]: ERROR REPORT:
Nov 15 14:44:34 teleporthost teleport[286293]: Original Error: *trace.AccessDeniedError User &#39;dev-derek&#39; is currently locked
Nov 15 14:44:34 teleporthost teleport[286293]: Stack Trace:
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/lib/accesslists/hierarchy.go:530 github.com/gravitational/teleport/lib/accesslists.IsAccessListMember
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/lib/auth/userloginstate/generator.go:185 github.com/gravitational/teleport/lib/auth/userloginstate.(*Generator).addAccessListsToState
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/lib/auth/userloginstate/generator.go:152 github.com/gravitational/teleport/lib/auth/userloginstate.(*Generator).Generate
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/lib/auth/userloginstate/generator.go:314 github.com/gravitational/teleport/lib/auth/userloginstate.(*Generator).Refresh
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/lib/auth/userloginstate/generator.go:326 github.com/gravitational/teleport/lib/auth.NewServer.(*Generator).LoginHook.func7
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/lib/auth/auth.go:1150 github.com/gravitational/teleport/lib/auth.(*Server).CallLoginHooks
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/e/lib/auth/usermonitor.go:310 github.com/gravitational/teleport/e/lib/auth.(*UserMonitor).processUserChange
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/e/lib/auth/usermonitor.go:195 github.com/gravitational/teleport/e/lib/auth.(*UserMonitor).reconcile
Nov 15 14:44:34 teleporthost teleport[286293]:         github.com/gravitational/teleport/e/lib/auth/usermonitor.go:125 github.com/gravitational/teleport/e/lib/auth.(*UserMonitor).reconciler
```

Bug details:
- Teleport version: 17.0.0 beta 2
- Recreation steps

1. Register a couple access lists
2. Register a user
3. Lock the user
4. REstart and monitor the Teleport auth service log.

### PR DESCRIPTION
**Pull request by kopiczko**
Fixes https://github.com/gravitational/teleport/issues/49054

Stop spamming "checking access list membership error" logs when member users are locked.

### CODE REVIEW

File: lib/auth/userloginstate/generator.go [hunk 1]
```diff
@@ -257,9 +258,12 @@ func (g *Generator) handleAccessListMembership(ctx context.Context, user types.U
 	membershipKind, err := accesslists.IsAccessListMember(ctx, user, accessList, g.accessLists, g.accessLists, g.clock)
 	// Return early if there was an error or the user isn't a member of the access list.
 	if err != nil || membershipKind == accesslistv1.AccessListUserAssignmentType_ACCESS_LIST_USER_ASSIGNMENT_TYPE_UNSPECIFIED {
-		// Log any error.
+		// Log any error besides user being locked.
 		if err != nil {
-			g.log.WarnContext(ctx, "checking access list membership", "error", err)
+			lockedError := trace.IsAccessDenied(err) && strings.Contains(err.Error(), "locked")
```
Comment (camscale) [inline lib/auth/userloginstate/generator.go:263]: Can we use error wrapping instead and check with `errors.Is()` or `errors.As()`? It was introduced to Go to avoid these sorts of error message string comparisons.

Comment (kopiczko) [reply lib/auth/userloginstate/generator.go:263]: The problem here is that the error message is dynamic:

```go
return accesslistv1.AccessListUserAssignmentType_ACCESS_LIST_USER_ASSIGNMENT_TYPE_UNSPECIFIED, trace.AccessDenied("User '%s' is currently locked", user.GetName())
```

The only reasonable way I can think of to make it `trace.AccessDenied` is to do var like:

```go
var ErrUserLocked = trace.AccessDenied("User is currently locked")
```

But then we lose the information but the user. From the looks for the error message format, it looks like it cloud be displayed somewhere. So I'm not sure how to go about it.

Does that look good?

```diff
- trace.AccessDenied("User '%s' is currently locked", user.GetName())
+ trace.Wrap(ErrUserLocked, "user=%q", user.GetName())
```

Comment (kopiczko) [reply lib/auth/userloginstate/generator.go]: PTALA

**Review by smallinsky — APPROVED** [review]

**Comment by kopiczko** [comment]
@camscale PTALA

**Review by camscale — APPROVED** [review]

File: lib/accesslists/hierarchy.go [hunk 2]
```diff
@@ -440,6 +441,26 @@ func maxDepthUpwards(
...
 }
 
+// userLockedError is used to check specific condition of user being locked with [IsUserLocked]. It
+// is also being matched by [trace.IsAccessDenied] while allowing creating a dynamic error message
+// containing the user name.
+type userLockedError struct{ err error }
+
+// newUserLockedError returns a new userLockedError.
+func newUserLockedError(user string) userLockedError {
+	return userLockedError{trace.AccessDenied("User '%q' is currently locked", user)}
```
Comment (smallinsky) [inline lib/accesslists/hierarchy.go:451]:
```suggestion
	return userLockedError{trace.AccessDenied("User %q is currently locked", user)}
```
