### PR TITLE
Web UI passes the true client IP into SSH sessions for correct audit

### LINKED ISSUE #735: Proxy IP is reported as"remote IP" for web UI sessions
We added "Client IP" column to the UI, but it's currently showing the proxy IP, not the client IP. The audit log also (incorrectly) stores proxy IP instead of a true client IP.

### PR DESCRIPTION
**Pull request by kontsevoy**
This PR closes #735 

## Description
This is how the web client passes the client IP taken from the HTTP session into SSH:
   
- When a web-based client creates a Teleport Client object, it now passes the
  true client IP (as taken from HTTP requests) into the created SSH-to-proxy
  session via an environment variable.
    
- The Teleport proxy interprets that variable when it dials the destination
  server and passes it on using the same handshake protocol as a regular
  teleport CLI client.

## Warning

This PR should be reviewed only after #751 is merged because it depends on the CLI client-to-web integration. (also it would make it smaller and MUCH easier to review this PR, because 95% of the changes you see are actually from #751)

### CODE REVIEW

File: lib/srv/proxy.go [hunk 1]
```diff
@@ -122,6 +122,17 @@ func (t *proxySubsys) start(sconn *ssh.ServerConn, ch ssh.Channel, req *ssh.Requ
 		tunnel     = t.srv.proxyTun
 		clientAddr = sconn.RemoteAddr()
 	)
+	// did the client pass us a true client IP ahead of time via an environment variable?
+	// (usually the web client would do that)
+	ctx.Lock()
+	trueClientIP, ok := ctx.env["TELEPORT_TRUE_CLIENT_IP"]
```
Comment (klizhentas) [inline lib/srv/proxy.go]: is it always created? can it panic?

**Review by klizhentas — COMMENTED** [review]
have a question about this one
