### PR TITLE
Stablize RemoteConnCleanup

### LINKED ISSUE #19827: `TestRemoteConnCleanup` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/3837119436/jobs/6532332112

#### Relevant snippet

```
=== CONT  TestRemoteConnCleanup
    localsite_test.go:124: LocalSite heart beat handler never terminated
--- FAIL: TestRemoteConnCleanup (30.02s)
```

This is coming from a timeout in the test: https://github.com/gravitational/teleport/blob/514bfc7ac6f01f928218de3ee1c0642c337cba67/lib/reversetunnel/localsite_test.go#L120-L125

### PR DESCRIPTION
**Pull request by rosstimothy**
Alters `RemoteConnCleanup` to rely less on `BlockUntil` by artificially adjusting the last heartbeat manually in the test. Additionally, the tests in `localsite_test` no longer call `native.PreComputeKey` by injecing an uninitialized `certificateCache` into the localsite constructor since it is not used for the tests. The logger is now also initialized for all tests within the `reversetunnel` package.

Closes #19827

### CODE REVIEW

File: lib/reversetunnel/localsite_test.go [hunk 1]
```diff
@@ -37,9 +38,16 @@ import (
 	"github.com/gravitational/teleport/lib/utils"
 )
 
+func TestMain(m *testing.M) {
+	utils.InitLoggerForTests()
```
Comment (jakule) [inline lib/reversetunnel/localsite_test.go:42]:
```suggestion
	helpers.TestMainImplementation(m)
```

File: lib/reversetunnel/localsite.go [hunk 2]
```diff
@@ -560,7 +573,7 @@ func (s *localSite) handleHeartbeat(rconn *remoteConn, ch ssh.Channel, reqC <-ch
 	for {
 		select {
 		case <-s.srv.ctx.Done():
-			logger.Infof("closing")
+			logger.Info("closing")
```
Comment (jakule) [inline lib/reversetunnel/localsite.go:576]: nit:
```suggestion
			logger.Info("Closing")
```

**Review by jakule — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
