### PR TITLE
Fix Alt+Click in desktop sessions

### LINKED ISSUE #50725: Alt key shortcut handling issue with Windows Desktop Access
Expected behavior:

Excel power users need to spawn multiple instances of MS Excel in Windows Desktop sessions. The most commonly used approach to do this is to hold  the "Alt" key while clicking the existing Excel application instance in the Taskbar. Teleport Desktop Access does not currently pick up the holding of the "Alt" key in this scenario.

A workaround is to hold the "Right Shift + Alt" keys while clicking the existing Excel application instance in the Taskbar but this is not a commonly used/known combination; as known below:

1. Hold the "Right Shift + Alt" keys and click the existing Excel application instance in the Taskbar: 

Image

2. User is prompted to start a new instance of Excel: 

Image

3. A second instance of Excel is started: 

Image

Current behavior:

Spawning a new/second instance of MS Excel with the "Alt" key does not work in Windows Desktop Access

Bug details:
- Teleport version: v16.4.11

### PR DESCRIPTION
**Pull request by danielashare**
This PR fixes #50725, where a user couldn't Alt+Click.

This was being blocked by the `Withholder` class that withholds the `Alt` key until another key is pressed to avoid stuck keys. To fix this issue, I modified `Withholder` to also handle mouse events so that when a click is registered it flushes any held keys to the remote desktop.

Before:
Notice that after finish selecting each line and release `Alt`, the VSCode menu items at the top left are underlined showing that `Alt` is only sent to the client after I release it.
https://github.com/user-attachments/assets/873e31b8-07e5-4fde-8285-c9149c4cb384

After:
I start holding `Alt` after selecting the first line, but it isn't sent to the remote desktop until I click on the second line. This shows that `Withholder` logic is maintained until another event comes in.
https://github.com/user-attachments/assets/5fbd091f-044d-43a1-8867-bc046da09931

changelog: Fix Alt+Click not being registered in remote desktop sessions.

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

File: web/packages/shared/components/DesktopSession/Withholder.tsx [hunk 1]
```diff
@@ -42,22 +42,23 @@ export class Withholder {
...
   ) {
-    const key = params.e.key;
-
-    // If this is not a key we withhold, immediately flush any withheld keys
+    // If this is not a key we withhold or a mouse event, immediately flush any withheld keys
     // and handle this key.
-    if (!this.keysToWithhold.includes(key)) {
+    if (
+      params.e instanceof MouseEvent ||
+      !this.keysToWithhold.includes((params.e as KeyboardEvent).key)
```
Comment (gzdunek) [inline web/packages/shared/components/DesktopSession/Withholder.tsx]: TS narrows down the type:
```suggestion
      !this.keysToWithhold.includes(params.e.key)
```

File: web/packages/shared/components/DesktopSession/Withholder.tsx [hunk 2]
```diff
@@ -42,22 +42,23 @@ export class Withholder {
    * The internal array of keystrokes that are currently
    * being withheld.
    */
-  private withheldKeys: Array<WithheldKeyboardEventHandler> = [];
+  private withheldKeys: Array<WithheldInputEventHandler> = [];
```
Comment (gzdunek) [inline web/packages/shared/components/DesktopSession/Withholder.tsx]: ?
```suggestion
  private withheldInputs: Array<WithheldInputEventHandler> = [];
```
Also the comment should be adjusted.

**Review by gzdunek — APPROVED** [review]

File: web/packages/shared/components/DesktopSession/Withholder.tsx (hunk 2 above)
Comment (ryanclark) [reply web/packages/shared/components/DesktopSession/Withholder.tsx]: Whilst we're here, `Array<T>` -> `T[]`
