### PR TITLE
dial reversetunnel nodes by UUID

### LINKED ISSUE #3891: Failed to join session in certain scenarios.
I found the following issues with `tsh join` when using classic Teleport (sessions are recorded at the node).

I created a cluster with a Teleport IoT node and tried to join that session.

```
$ tsh join 0f0ca8c4-24ff-4c34-bda1-0311b52bf741
error: failed connecting to node . invalid format for proxy request: "proxy:@default@root.com", 
   expected 'proxy:host:port@cluster'
```

A similar error is seen when using `tsh ssh` and labels.

---

I created two clusters `root.com` and `leaf.com` and established a trust relationship between then. I started a session on `leaf.com` and tried to join that session and saw the following. I saw the error for both a regular node as well as for IoT nodes.

```
$ tsh join --cluster=leaf.com d612da7f-f6cd-4685-9eb7-288b962e48f2
error: session 'd612da7f-f6cd-4685-9eb7-288b962e48f2' not found or it has ended
```

### PR DESCRIPTION
**Pull request by fspmarshall**
Have `tsh` fallback to dialing by UUID when it encounters a node with an empty address field.  Fixes an issue where attempting to join sessions, or run commands via labels, on IoT nodes resulted in `tsh` attempting to dial an empty string.

Fixes #3891

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -888,7 +888,12 @@ func (tc *TeleportClient) getTargetNodes(ctx context.Context, proxy *ProxyClient
 			return nil, trace.Wrap(err)
 		}
 		for i := 0; i < len(nodes); i++ {
-			retval = append(retval, nodes[i].GetAddr())
+			addr := nodes[i].GetAddr()
+			if addr == "" {
+				// address is empty, try dialing by UUID instead.
+				addr = fmt.Sprintf("%s:0", nodes[i].GetName())
+			}
```
Comment (awly) [inline lib/client/api.go:895]: Should this fallback live within `GetAddr()` method itself to prevent future confusion?

**Review by awly — COMMENTED** [review]
Please also add a unit test

**Review by russjones — APPROVED** [review]
Looks good to me once suggestion from @awly is addressed.

File: lib/client/api.go (hunk 1 above)
Comment (fspmarshall) [reply lib/client/api.go:895]: This value isn't a useful default outside of very specific contexts.  The rest of teleport seems to know that `GetAddr() == ""` means that we're dealing with a reversetunnel node... we just missed these two cases because there wasn't proper test coverage for `tsh` operations against reversetunnel nodes.

I *do* want to do some refactoring around how both `tsh` and the web UI handle dialing nodes, but I don't want that to be a blocker for fixing the issue at hand.

File: integration/integration_test.go [hunk 2]
```diff
@@ -676,13 +724,35 @@ func (s *IntSuite) TestUUIDBasedProxy(c *check.C) {
...
+	s.verifySessionJoin(c, t)
+}
+
+// TestInteractive covers SSH into shell and joining the same session from another client
+// against a reversetunnel node.
+func (s *IntSuite) TestInteractiveReverseTunnel(c *check.C) {
+	tr := utils.NewTracer(utils.ThisFunction()).Start()
+	defer tr.Stop()
+
+	lib.SetInsecureDevMode(true)
```
Comment (awly) [inline integration/integration_test.go:744]: Add a comment about why this is needed.

File: integration/integration_test.go [hunk 3]
```diff
@@ -3946,6 +4016,92 @@ func (s *IntSuite) TestList(c *check.C) {
 	}
 }
 
+// TestCmdLabels verifies the behavior of running commands via labels
+// with a mixture of regular and reversetunnel nodes.
+func (s *IntSuite) TestCmdLabels(c *check.C) {
+	tr := utils.NewTracer(utils.ThisFunction()).Start()
+	defer tr.Stop()
+
+	lib.SetInsecureDevMode(true)
```
Comment (awly) [inline integration/integration_test.go:4025]: Also add a comment here

File: integration/integration_test.go [hunk 4]
```diff
@@ -3946,6 +4016,92 @@ func (s *IntSuite) TestList(c *check.C) {
...
+	defer lib.SetInsecureDevMode(false)
+
+	// Create and start a Teleport cluster with auth, proxy, and node.
+	makeConfig := func() (*check.C, []string, []*InstanceSecrets, *service.Config) {
```
Comment (awly) [inline integration/integration_test.go:4029]: this should only return `*service.Config`

File: integration/integration_test.go [hunk 5]
```diff
@@ -3946,6 +4016,92 @@ func (s *IntSuite) TestList(c *check.C) {
...
+	// node individually.
+	tts := []struct {
+		command []string
+		labels  map[string]string
+		expect  string
+	}{
+		{
+			command: []string{"echo", "two"},
+			labels:  map[string]string{"spam": "eggs"},
+			expect:  "two\ntwo\n",
```
Comment (awly) [inline integration/integration_test.go:4079]: why is this printing twice?

**Review by awly — APPROVED** [review]

File: integration/integration_test.go (hunk 5 above)
Comment (fspmarshall) [reply integration/integration_test.go:4081]: Labels match both nodes, so command is run twice.
