### PR TITLE
Don't check for KDC address in non-AD environments

### LINKED ISSUE #61087: Windows Desktop Service can’t log in to **local** Windows users after 18.3.1 (KDC DNS discovery regression)
# Windows Desktop Service can’t log in to **local** Windows users after [18.3.1](https://github.com/gravitational/teleport/pull/60988) (KDC DNS discovery regression)

## Summary
After upgrading to **Teleport 18.3.1**, I can no longer access **local Windows accounts** via the Windows Desktop Service. This appears to be a regression related to the change _“Windows Desktop service can now discover the KDC server address via DNS. (#60988)”_.  
The service now attempts KDC discovery even for non-AD hosts and fails the session.

## Versions
- Teleport: **18.3.1** (worked prior to upgrading; issue began in 18.3.1)
- Component: **Windows Desktop Service**
- Deployment: agents & services running in containers
- DNS resolver inside container: `127.0.0.11`

## Background / Topology
- Teleport Proxy is published behind **Traefik** (reverse proxy) on `:443`.
- Proxy uses `proxy_listener_mode: multiplex` (single port for Web/ALPN/SSH).
- RDP access is via the **Windows Desktop Service** agent registered to this cluster.
- The issue occurs when connecting to **non-AD** Windows hosts using **local** accounts.

## Environment
- Using a **static host** with `ad: false` (local Windows user sign-in expected).
- Target host:
  - Name: `ho1`
  - Address: `192.168.10.61`
  - Labels: `datacenter=win-11`

## Configuration
```yaml
windows_desktop_service:
  enabled: true
  listen_addr: "0.0.0.0:3028"
  public_addr: "127.0.0.1:3028"
  static_hosts:
  - name: ho1
    ad: false
    addr: 192.168.10.61
    labels:
      datacenter: win-11
```

## Steps to Reproduce

1. Upgrade Teleport to **18.3.1**.
2. Run the **Windows Desktop Service** in a container whose DNS resolver is `127.0.0.11`.
3. Publish the Teleport Proxy behind **Traefik** on `:443` with  
   `proxy_listener_mode: multiplex` enabled.
4. Configure a **static** Windows host with `ad: false` (local account expected), e.g.:
   - Hostname: `ho1`
   - Address: `192.168.10.61`
5. From a client, attempt to connect and sign in as a **local** Windows user  
   (e.g., `.\localadmin` or `ho1\localadmin`) via Teleport Windows Desktop.
6. Observe that the connection fails and the agent logs show KDC DNS discovery.

## How Teleport has been set up

- Reverse proxy: Traefik (terminating TLS on :443)
- Teleport Proxy setting: proxy_listener_mode: multiplex

## Relevant logs
```
getting KDC address
  locating KDC server
    looking up SRV records for 
      lookup _kerberos._tcp. on 127.0.0.11:53: no such host
```

## Expected: 

For ad: false (local logon), the Windows Desktop Service skips KDC discovery and proceeds with local authentication.

Actual: KDC discovery is attempted; SRV lookup fails and the session is aborted.

### PR DESCRIPTION
**Pull request by danielashare**
Fixes regression from #60228 where WDS would attempt to discover KDC servers for non-AD desktops.

Fixes #61087

Tests:

- [x] AD Desktop with NLA
- [x] AD Desktop without NLA
- [x] Non-AD Desktop

changelog: Fixed regression when connecting to non-AD desktops

### CODE REVIEW

File: lib/srv/desktop/windows_server.go [hunk 1]
```diff
@@ -790,9 +790,13 @@ func (s *WindowsService) connectRDP(ctx context.Context, log *slog.Logger, tdpCo
 	}
 	log = log.With("computer_name", computerName)
 
-	kdcAddr, err := s.getKDCAddress(ctx)
-	if err != nil {
-		return trace.Wrap(err, "getting KDC address")
+	var kdcAddr string
+	if !desktop.NonAD() {
+		var err error
+		kdcAddr, err = s.getKDCAddress(ctx)
```
Comment (zmb3) [inline lib/srv/desktop/windows_server.go:798]: We don't need a KDC address if NLA is not enabled, so we should move this after line 802 and do a `if nla { ... }`

**Review by zmb3 — APPROVED** [review]

**Review by rhammonds-teleport — APPROVED** [review]
