### PR TITLE
SIGINT handling

### LINKED ISSUE #1650: ctrl-c ignored.
tsh doesn't properly shutdown when it recieves interrupt signals.

```
# easy way to reproduce: network is down / vpn is offline.
tsh ssh user@host
^C^C^C^C^C^C^C^C^C^C
```

also happens when running a command against mutliple servers, like following logs.

distro: Arch linux
tsh: Teleport v2.4.0 git:v2.4.0-0-ge9d6645

### PR DESCRIPTION
**Pull request by russjones**
**Problem**

https://github.com/gravitational/teleport/issues/1650 raised two issues with SIGINT handling of `tsh`. The first is that Ctrl-C does not work when network connectivity is down. The second is that Ctrl-C does not work when running a command against multiple nodes (like tailing log files).

**Implementation**

* Propagate the cancelation context to `ConnectToProxy` where it should try to connect to the proxy in another goroutine and exit early if the context has been canceled.
* When running a command on multiple servers, close the connection and kill the client if SIGINT if the context has been canceled.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1650

### CODE REVIEW

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

File: lib/client/api.go [hunk 1]
```diff
@@ -957,8 +959,35 @@ func (tc *TeleportClient) authMethods() []ssh.AuthMethod {
...
+	// returned from connectToProxy.
+	connectContext, cancel := context.WithCancel(context.Background())
+	go func() {
+		defer cancel()
+		proxyClient, err = tc.connectToProxy()
+	}()
+
+	select {
+	// ConnectToProxy returned a result, return that back to the caller.
+	case <-connectContext.Done():
```
Comment (klizhentas) [inline lib/client/api.go]: I remember I left a comment earlier today about merging parent context and this one, but disregard it, your code is actually correct and my suggestion will not work.

**Review by klizhentas — APPROVED** [review]
