### PR TITLE
Provide agentless error message for openssh/eice connection failures

### LINKED ISSUE #59672: Provide error specific to openssh connect vs node agents
Expected behavior:

An error message specific to openssh scenarios. Typically either the firewall is blocking or the machine is down.

Current behavior:

If a openssh node fails to connect you get the same error as with a Teleport ssh_service. This mentions an agent but there is no agent.

```bash
disconnected
Teleport proxy failed to connect to "node" agent "ip-2-3-45" over direct dial:

  dial tcp 1.2.3.4:22: i/o timeout

This usually means that the agent is offline or has disconnected. Check the
agent logs and, if the issue persists, try restarting it or re-registering it
with the cluster.
```

Bug details:
- Teleport version: 18.2.2
- Recreation steps
1. Add a openssh node configuration
2. Block or take down the machine
3. Attempt to connect

### PR DESCRIPTION
**Pull request by stevenGravy**
Fixes #59672
Update error message to provide agentless connection problem reasons when a OpenSSH or EICE server does not connect.

### CODE REVIEW

File: lib/reversetunnel/local_cluster.go [hunk 1]
```diff
@@ -576,6 +576,15 @@ This usually means that the agent is offline or has disconnected. Check the
 agent logs and, if the issue persists, try restarting it or re-registering it
 with the cluster.`
 
+	if params.TargetServer != nil && (params.TargetServer.IsOpenSSHNode() || params.TargetServer.IsEICE()) {
+		errorMessageTemplate = `Teleport proxy failed to connect to %q resource %q over %s:
+
+  %v
+
+This usually means that the resource is offline or network permissions block the connection.
+Check the resource health status and network permissions.`
```
Comment (rosstimothy) [inline lib/reversetunnel/local_cluster.go]: Can we make the wording here a bit more specific by replacing resource with something like agentless host? EICE is all but dead due to AWS quotas so I don't think we need to try accommodating it here in this error message.

Comment (stevenGravy) [reply lib/reversetunnel/local_cluster.go]: Sure, thanks @rosstimothy , please see the update with server specific and SSH language.

File: lib/reversetunnel/local_cluster.go [hunk 2]
```diff
@@ -576,6 +576,15 @@ This usually means that the agent is offline or has disconnected. Check the
 agent logs and, if the issue persists, try restarting it or re-registering it
 with the cluster.`
 
+	if params.TargetServer != nil && (params.TargetServer.IsOpenSSHNode() || params.TargetServer.IsEICE()) {
+		errorMessageTemplate = `Teleport proxy failed to connect to %q server %q over %s:
+
+  %v
+
+This usually means that the server is offline or network permissions block the SSH connection.
+Check the server health status, SSHD service and network permissions.`
```
Comment (rosstimothy) [inline lib/reversetunnel/local_cluster.go]: What do you think about rewording the troubleshooting steps a bit?
```suggestion
Check the network permissions and verify that the instance is running and the SSHD service is active.`
```

Comment (stevenGravy) [reply lib/reversetunnel/local_cluster.go]: thanks @rosstimothy , please see updates.

**Review by rosstimothy — APPROVED** [review]
Thanks @stevenGravy

File: lib/reversetunnel/local_cluster.go [hunk 3]
```diff
@@ -576,6 +576,15 @@ This usually means that the agent is offline or has disconnected. Check the
 agent logs and, if the issue persists, try restarting it or re-registering it
 with the cluster.`
 
+	if params.TargetServer != nil && (params.TargetServer.IsOpenSSHNode() || params.TargetServer.IsEICE()) {
+		errorMessageTemplate = `Teleport proxy failed to connect to %q server %q over %s:
+
+  %v
+
+This usually means that the server is offline or network permissions block the SSH connection.
+Check the network permissions, verify that the instance is running and the SSHD service is active.`
```
Comment (zmb3) [inline lib/reversetunnel/local_cluster.go]: Is this proper? I don't know that I've ever seen SSHD in all caps like that.

Comment (stevenGravy) [reply lib/reversetunnel/local_cluster.go]: I've seen it more in high level context vs using `sshd` makes more sense here it seems for them for technical troubleshooting. Updated to `sshd`.

Comment (stevenGravy) [reply lib/reversetunnel/local_cluster.go]: @zmb3 is this looking good to go forward with?  thanks.

Comment (zmb3) [reply lib/reversetunnel/local_cluster.go]: I don't love "network permissions" - should we say firewall instead?

Comment (stevenGravy) [reply lib/reversetunnel/local_cluster.go]: Sure @zmb3 , I've updated and we had used "firewall" in other places like https://github.com/gravitational/teleport/blob/9be2746fc1928d211169f147c293ade5739afa3b/lib/utils/errors.go#L137

Comment (stevenGravy) [reply lib/reversetunnel/local_cluster.go]: Anything else you'd like done here @zmb3 ?

**Review by zmb3 — APPROVED** [review]
