### PR TITLE
Fix TestIntegrations/CmdLabels output clobbering from multiple ssh attempts

### LINKED ISSUE #21089: `TestIntegrations/CmdLabels` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695

#### Relevant snippet

```
integration_test.go:5237: 
[976](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:977)
        	Error Trace:	/__w/teleport/teleport/integration/integration_test.go:5237
[977](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:978)
        	Error:      	Received unexpected error:
[978](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:979)
        	            	failed connecting to node 00000000-0000-0000-0000-000000000000. Teleport proxy failed to connect to "node" agent "" over reverse tunnel:
[979](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:980)
        	            	
[980](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:981)
        	            	  no tunnel connection found: no node reverse tunnel for 00000000-0000-0000-0000-000000000000.local-site found
[981](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:982)
        	            	
[982](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:983)
        	            	This usually means that the agent is offline or has disconnected. Check the
[983](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:984)
        	            	agent logs and, if the issue persists, try restarting it or re-registering it
[984](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:985)
        	            	with the cluster.
[985](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:986)
        	Test:       	TestIntegrations/CmdLabels/Worker_only
[986](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:987)
        --- FAIL: TestIntegrations/CmdLabels/Worker_only (1.14s)```

### PR DESCRIPTION
**Pull request by atburke**
This change deflakes TestIntegrations/CmdLabels/Both by ensuring that each command run uses a new stdout buffer, instead of all attempts sharing one.

Resolves #21089.

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -7077,35 +7077,62 @@ func runCommandWithCertReissue(t *testing.T, instance *helpers.TeleInstance, cmd
...
-	tc, err := instance.NewClient(cfg)
-	if err != nil {
-		return "", trace.Wrap(err)
-	}
+func runCommand(ctx context.Context, tc *client.TeleportClient, cmd []string) (string, error) {
 	// since this helper is sometimes used for running commands on
 	// multiple nodes concurrently, we use io.Pipe to protect our
 	// output buffer from concurrent writes.
 	read, write := io.Pipe()
+	defer write.Close()
```
Comment (codingllama) [inline integration/integration_test.go]: Defer-close `read` too?

File: integration/integration_test.go [hunk 2]
```diff
@@ -7077,35 +7077,62 @@ func runCommandWithCertReissue(t *testing.T, instance *helpers.TeleInstance, cmd
...
-	<-doneC
-	return output.String(), nil
+	var cmdErr error
+	for range attempts {
+		var out string
+		out, cmdErr = runCommand(ctx, tc, cmd)
+		if cmdErr == nil {
+			return out, nil
+		} else if ctx.Err() != nil {
+			return "", trace.Wrap(ctx.Err())
```
Comment (codingllama) [inline integration/integration_test.go]: Suggestion: I think we can leave this one out if favor of both runCommand() and the select below.

```suggestion
```

File: integration/integration_test.go [hunk 3]
```diff
@@ -7077,35 +7077,62 @@ func runCommandWithCertReissue(t *testing.T, instance *helpers.TeleInstance, cmd
...
+		return "", trace.Wrap(ctx.Err())
+	}
+	return output.String(), nil
+}
+
+// RunCommand is a shortcut for running SSH command, it creates a client
+// connected to proxy of the passed in instance, runs the command, and returns
+// the result. If multiple attempts are requested, a one second delay is
+// added between them before giving up.
+func RunCommand(
```
Comment (codingllama) [inline integration/integration_test.go]: nit: I don't think it makes sense for this func to be public.

I'd be happy with runCommand and runCommandImpl (or something else if you have a better idea).

File: integration/integration_test.go (hunk 1 above)
Comment (codingllama) [inline integration/integration_test.go]: Close `read` too?

```suggestion
	read, write := io.Pipe()
	defer read.Close()
	defer write.Close()
```

**Review by codingllama — COMMENTED** [review]
LGTM.

**Review by codingllama — APPROVED** [review]

**Review by kshi36 — APPROVED** [review]
