### PR TITLE
fix aws e2e test

### LINKED ISSUE #46245: `TestDatabases/redshift_cluster/auto_user_keep` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/10705690243/job/29681682584?pr=45876

#### Relevant snippet

```
=== CONT  TestDatabases/redshift_cluster/auto_user_keep
    redshift_test.go:176: 
        	Error Trace:	/__w/teleport/teleport/e2e/aws/redshift_test.go:289
        	            				/opt/go/src/runtime/asm_amd64.s:1695
        	Error:      	Should be false
        	Messages:   	user "auto_keep_6bce1c" should not be able to login after deactivating
    redshift_test.go:176: 
        	Error Trace:	/__w/teleport/teleport/e2e/aws/redshift_test.go:266
        	            				/__w/teleport/teleport/e2e/aws/redshift_test.go:176
        	            				/__w/teleport/teleport/e2e/aws/redshift_test.go:210
        	Error:      	Condition never satisfied
        	Test:       	TestDatabases/redshift_cluster/auto_user_keep
        	Messages:   	waiting for auto user "auto_keep_6bce1c" to be deactivated
```

### LINKED ISSUE #62465: AWS E2E test failures + data race
#### Link(s) to logs

https://github.com/gravitational/teleport/actions/runs/20437055344/job/58720839266?pr=62436

#### Relevant snippet

First we see a failure with `TestDatabases/redshift_cluster/auto_user_drop`.

```
=== FAIL: e2e/aws TestDatabases/redshift_cluster/auto_user_drop (79.76s)
    redshift_test.go:185: 
        	Error Trace:	/__w/teleport/teleport/e2e/aws/redshift_test.go:306
        	            				/opt/go/src/runtime/asm_amd64.s:1693
        	Error:      	Should be false
        	Messages:   	user "auto_drop_33fa5f66" should have been dropped automatically after disconnecting
    redshift_test.go:185: 
        	Error Trace:	/__w/teleport/teleport/e2e/aws/redshift_test.go:295
        	            				/__w/teleport/teleport/e2e/aws/redshift_test.go:185
        	            				/__w/teleport/teleport/e2e/aws/redshift_test.go:208
        	Error:      	Condition never satisfied
        	Test:       	TestDatabases/redshift_cluster/auto_user_drop
        	Messages:   	waiting for auto user "auto_drop_33fa5f66" to be dropped
==================
```

Then we see a data race in `jackc/pgconn`:

```
WARNING: DATA RACE
Read at 0x00c00b63f380 by goroutine 148:
  github.com/jackc/pgconn.(*PgConn).lock()
      /go/pkg/mod/github.com/jackc/pgconn@v1.14.3/pgconn.go:713 +0x69
  github.com/jackc/pgconn.(*PgConn).Exec()
      /go/pkg/mod/github.com/jackc/pgconn@v1.14.3/pgconn.go:1002 +0xe6
  github.com/jackc/pgx/v4.(*Conn).execSimpleProtocol()
      /go/pkg/mod/github.com/jackc/pgx/v4@v4.18.3/conn.go:459 +0xeb
  github.com/jackc/pgx/v4.(*Conn).exec()
      /go/pkg/mod/github.com/jackc/pgx/v4@v4.18.3/conn.go:429 +0x4f3
  github.com/jackc/pgx/v4.(*Conn).Exec()
      /go/pkg/mod/github.com/jackc/pgx/v4@v4.18.3/conn.go:389 +0xc4
  github.com/gravitational/teleport/e2e/aws.(*pgConn).Exec.func1()
      /__w/teleport/teleport/e2e/aws/databases_test.go:396 +0xd1
  github.com/gravitational/teleport/e2e/aws.withRetry()
      /__w/teleport/teleport/e2e/aws/databases_test.go:422 +0x19e
  github.com/gravitational/teleport/e2e/aws.(*pgConn).Exec()
      /__w/teleport/teleport/e2e/aws/databases_test.go:394 +0x1bc
  github.com/gravitational/teleport/e2e/aws.testRedshiftCluster.func1()
      /__w/teleport/teleport/e2e/aws/redshift_test.go:128 +0x5aa
  testing.(*common).Cleanup.func1()
      /opt/go/src/testing/testing.go:1308 +0x168
  testing.(*common).runCleanup()
      /opt/go/src/testing/testing.go:1572 +0x225
  testing.tRunner.func1()
      /opt/go/src/testing/testing.go:1898 +0xa88
  runtime.deferreturn()
      /opt/go/src/runtime/panic.go:589 +0x5d
  github.com/gravitational/teleport/e2e/aws.testRedshiftCluster()
      /__w/teleport/teleport/e2e/aws/redshift_test.go:102 +0xb44
  github.com/gravitational/teleport/e2e/aws.testRedshiftCluster()
      /__w/teleport/teleport/e2e/aws/redshift_test.go:98 +0xa0b
  github.com/gravitational/teleport/integration/helpers.(*TeleInstance).createTeleportProcess()
      /__w/teleport/teleport/integration/helpers/instance.go:661 +0xd1
  github.com/gravitational/teleport/integration/helpers.(*TeleInstance).CreateWithConf()
      /__w/teleport/teleport/integration/helpers/instance.go:678 +0xa4
  github.com/gravitational/teleport/integration/helpers.(*TeleInstance).CreateEx()
      /__w/teleport/teleport/integration/helpers/instance.go:656 +0xaa
  github.com/gravitational/teleport/e2e/aws.createTeleportCluster()
      /__w/teleport/teleport/e2e/aws/fixtures_test.go:167 +0x724
  github.com/gravitational/teleport/e2e/aws.createTeleportCluster()
      /__w/teleport/teleport/e2e/aws/fixtures_test.go:155 +0x36b
  github.com/gravitational/teleport/e2e/aws.makeDBTestCluster()
      /__w/teleport/teleport/e2e/aws/rds_test.go:69 +0x786
  github.com/gravitational/teleport/e2e/aws.testRedshiftCluster()
      /__w/teleport/teleport/e2e/aws/redshift_test.go:84 +0x732
  testing.tRunner()
      /opt/go/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /opt/go/src/testing/testing.go:1997 +0x44

Previous write at 0x00c00b63f380 by goroutine 107833:
  github.com/jackc/pgconn.(*PgConn).lock()
      /go/pkg/mod/github.com/jackc/pgconn@v1.14.3/pgconn.go:721 +0x1c4
  github.com/jackc/pgconn.(*PgConn).execExtendedPrefix()
      /go/pkg/mod/github.com/jackc/pgconn@v1.14.3/pgconn.go:1173 +0x1a9
  github.com/jackc/pgconn.(*PgConn).ExecPrepared()
      /go/pkg/mod/github.com/jackc/pgconn@v1.14.3/pgconn.go:1145 +0x9b
  github.com/jackc/pgx/v4.(*Conn).Query()
      /go/pkg/mod/github.com/jackc/pgx/v4@v4.18.3/conn.go:655 +0x17d1
  github.com/gravitational/teleport/e2e/aws.waitForRedshiftAutoUserDrop.func1()
      /__w/teleport/teleport/e2e/aws/redshift_test.go:302 +0x11c
  github.com/stretchr/testify/assert.EventuallyWithT.func1()
      /go/pkg/mod/github.com/stretchr/testify@v1.11.1/assert/assertions.go:2096 +0xb3
```

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes https://github.com/gravitational/teleport/issues/46245
- https://github.com/gravitational/teleport/issues/46245

Closes https://github.com/gravitational/teleport/issues/62465
- https://github.com/gravitational/teleport/issues/62465

This PR is intended to fix redshift flaky test failures and a data race.
I also included some logging updates that weren't worth a separate PR imo.

### CODE REVIEW

File: e2e/aws/databases_test.go [hunk 1]
```diff
@@ -39,6 +39,7 @@ import (
 	"github.com/jackc/pgconn"
 	"github.com/jackc/pgerrcode"
 	"github.com/jackc/pgx/v4"
+	"github.com/jackc/pgx/v4/pgxpool" // TODO(gavin): change this to v5 after updating other test packages to use v5 as well
```
Comment (GavinFrazar) [inline e2e/aws/databases_test.go:42]: I originally used v5 and started changing this package to use v5 everywhere, but some external test helpers still use v4.
To avoid cluttering this PR, I'll update everything to use v5 in a separate PR.

File: api/utils/retryutils/retry.go [hunk 2]
```diff
@@ -190,7 +190,7 @@ func (r *Linear) For(ctx context.Context, retryFn func() error) error {
 		if errors.As(trace.Unwrap(err), &permanentRetryError) {
 			return trace.Wrap(err)
 		}
-		slog.DebugContext(ctx, "Waiting to retry operation again", "wait", r.Duration(), "error", err)
+		slog.DebugContext(ctx, "Waiting to retry operation again", "wait", r.Duration().String(), "error", err)
```
Comment (greedy52) [inline api/utils/retryutils/retry.go:193]: nit: `logutils.StringerAttr(r.Duration())`

File: e2e/aws/databases_test.go [hunk 3]
```diff
@@ -383,26 +382,60 @@ func getSecretValue(t *testing.T, ctx context.Context, secretID string) secretsm
...
+		c.logger.InfoContext(ctx, "Executed query",
+			"sql", sql,
+		)
+	}
+	return rows, trace.Wrap(err)
+}
+
+func (c *pgConn) mustQuery(t require.TestingT, ctx context.Context, sql string, args ...any) []any {
+	var out []any
+	rows, _ := c.Query(ctx, sql, args...)
```
Comment (greedy52) [inline e2e/aws/databases_test.go:427]: nit: close `rows`?

File: lib/srv/db/postgres/users.go [hunk 4]
```diff
@@ -437,6 +437,9 @@ func (e *Engine) updateAutoUsersRole(ctx context.Context, conn *pgx.Conn, adminU
 	} else {
 		e.Log.DebugContext(ctx, "Created PostgreSQL role", "role", teleportAutoUserRole)
 	}
+	if db.IsRedshift() {
```
Comment (greedy52) [inline lib/srv/db/postgres/users.go:440]: is this what actually fixing the issue where wait-for-drop times out?

File: api/utils/retryutils/retry.go (hunk 2 above)
Comment (GavinFrazar) [reply api/utils/retryutils/retry.go:193]: this is api/ code and that's a lib/ func

File: e2e/aws/databases_test.go (hunk 3 above)
Comment (GavinFrazar) [reply e2e/aws/databases_test.go:427]: I left that out because rows.Next() will close the rows when it returns false.

However it's probably best to defer close anyway, in case of a panic or something.

Added.

File: lib/srv/db/postgres/users.go (hunk 4 above)
Comment (GavinFrazar) [reply lib/srv/db/postgres/users.go:440]: no, I just noticed while testing these changes that I kept seeing a syntax error in the logs for redshift auto users.

Some more info in the commit: https://github.com/gravitational/teleport/pull/62528/changes/fa57735f2a790a7e34a446f336851d3bfb681945

File: e2e/aws/databases_test.go (hunk 3 above)
Comment (GavinFrazar) [reply e2e/aws/databases_test.go:427]: [607ccd3](https://github.com/gravitational/teleport/pull/62528/commits/607ccd320e5c31a1cfc291ae73e851c0f167af0c)

File: e2e/aws/databases_test.go [hunk 5]
```diff
@@ -383,26 +382,61 @@ func getSecretValue(t *testing.T, ctx context.Context, secretID string) secretsm
...
+	rows, err := c.pool.Query(ctx, sql, args...)
+	if err != nil {
+		c.logger.WarnContext(ctx, "Failed to execute query",
+			"sql", sql,
+			"error", err,
+		)
+	} else {
+		c.logger.InfoContext(ctx, "Executed query",
+			"sql", sql,
+		)
```
Comment (zmb3) [inline e2e/aws/databases_test.go]:
```suggestion
		c.logger.InfoContext(ctx, "Executed query", "sql", sql)
```

File: e2e/aws/databases_test.go [hunk 6]
```diff
@@ -383,26 +382,61 @@ func getSecretValue(t *testing.T, ctx context.Context, secretID string) secretsm
...
-	)
+	if err != nil {
+		c.logger.WarnContext(ctx, "Failed to execute SQL statement",
+			"sql", sql,
+			"error", err,
+		)
+	} else {
+		c.logger.InfoContext(ctx, "Executed SQL statement",
+			"sql", sql,
+		)
```
Comment (zmb3) [inline e2e/aws/databases_test.go]:
```suggestion
		c.logger.InfoContext(ctx, "Executed SQL statement", "sql", sql)
```

File: e2e/aws/databases_test.go [hunk 7]
```diff
@@ -383,26 +382,61 @@ func getSecretValue(t *testing.T, ctx context.Context, secretID string) secretsm
...
+	} else {
+		c.logger.InfoContext(ctx, "Executed query",
+			"sql", sql,
+		)
+	}
+	return rows, trace.Wrap(err)
+}
+
+func (c *pgConn) mustQuery(t require.TestingT, ctx context.Context, sql string, args ...any) []any {
+	var out []any
```
Comment (zmb3) [inline e2e/aws/databases_test.go:426]:
```suggestion
	t.Helper()
	var out []any
```

File: e2e/aws/redshift_test.go [hunk 8]
```diff
@@ -268,25 +260,14 @@ func waitForRedshiftAutoUserDeactivate(t *testing.T, ctx context.Context, conn *
 		// rows.Err() will also contain any error from executing the query after
 		// closing rows. Hence, we do not check the error until after reading
 		// and closing rows.
-		rows, _ := conn.Query(ctx, "SELECT 1 FROM pg_user_info as a WHERE a.usename = $1", user)
-		gotRow := rows.Next()
-		rows.Close()
-		require.NoError(t, rows.Err())
+		values := conn.mustQuery(t, ctx, "SELECT a.usename FROM pg_user_info as a WHERE a.usename = $1", user)
```
Comment (zmb3) [inline e2e/aws/redshift_test.go:259]: Is this supposed to be `usename` or `username`?

Comment (GavinFrazar) [reply e2e/aws/redshift_test.go:259]: confusingly, it is `usename`: https://docs.aws.amazon.com/redshift/latest/dg/pg_user_info.html

File: e2e/aws/databases_test.go (hunk 7 above)
Comment (GavinFrazar) [reply e2e/aws/databases_test.go:426]: it's a require.TestingT interface because I use it within a `EventuallyWithT` func, so I'll do a type assertion and conditional call to `t.Helper()` here.

Comment (GavinFrazar) [reply e2e/aws/databases_test.go:426]: be988c6f3fad99cc185325d87bcf37a08bef2f58

File: e2e/aws/databases_test.go (hunk 6 above)
Comment (GavinFrazar) [reply e2e/aws/databases_test.go]: be988c6f3fad99cc185325d87bcf37a08bef2f58

File: e2e/aws/databases_test.go (hunk 5 above)
Comment (GavinFrazar) [reply e2e/aws/databases_test.go]: be988c6f3fad99cc185325d87bcf37a08bef2f58

File: e2e/aws/redshift_test.go
Comment (greedy52) [inline e2e/aws/redshift_test.go]: nit: this comment needs an update

File: lib/srv/db/postgres/users.go (hunk 4 above)
Comment (greedy52) [reply lib/srv/db/postgres/users.go:440]: thanks! didn't see the comment before. Then what is the fix for this?
```
=== FAIL: e2e/aws TestDatabases/redshift_cluster/auto_user_keep (134.63s)
    redshift_test.go:175: 
        	Error Trace:	/__w/teleport/teleport/e2e/aws/redshift_test.go:274
        	            				/opt/go/src/runtime/asm_amd64.s:1693
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
    redshift_test.go:175: 
        	Error Trace:	/__w/teleport/teleport/e2e/aws/redshift_test.go:264
        	            				/__w/teleport/teleport/e2e/aws/redshift_test.go:175
        	            				/__w/teleport/teleport/e2e/aws/redshift_test.go:208
        	Error:      	Condition never satisfied
        	Test:       	TestDatabases/redshift_cluster/auto_user_keep
        	Messages:   	waiting for auto user "auto_keep_0fbf6961" to be deactivated
```

Comment (GavinFrazar) [reply lib/srv/db/postgres/users.go:440]: Is that from an old run or did you test this PR and saw that failure again?

I think this https://github.com/gravitational/teleport/pull/62528/changes/95297b5f7236899f895a2d7af5939938c2d430dd will help - I haven't seen it fail since.

auto user deactivation/deletion was failing because our deactivation script checks for active user connections and aborts if there are any.
I suspect that `stv_sessions` updates may be delayed when a user disconnects.
Reducing test parallelism may just be helping but not actually fixing the problem if that's the case.

We could retry on TP000 exceptions (we raise that exception in our plpgsql script for active user conns).
However, then it will retry when a user actually does have active connections, which isn't ideal either.

For now let's see if it reoccurs with the parallelism removed?

Comment (greedy52) [reply lib/srv/db/postgres/users.go:440]: sounds good.

**Review by greedy52 — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Comment by rosstimothy** [comment]
@GavinFrazar can we backport this fix? I'm still hitting failures in branch/v18.



https://github.com/gravitational/teleport/actions/runs/20723337878/job/59492728339
```
=== FAIL: e2e/aws TestDatabases/redshift_cluster/auto_user_keep (80.07s)
    redshift_test.go:175: 
        	Error Trace:	/__w/teleport/teleport/e2e/aws/redshift_test.go:288
        	            				/opt/go/src/runtime/asm_amd64.s:1700
        	Error:      	Should be false
        	Messages:   	user "auto_keep_a84ec916" should not be able to login after deactivating
    redshift_test.go:175: 
        	Error Trace:	/__w/teleport/teleport/e2e/aws/redshift_test.go:265
        	            				/__w/teleport/teleport/e2e/aws/redshift_test.go:175
        	            				/__w/teleport/teleport/e2e/aws/redshift_test.go:209
        	Error:      	Condition never satisfied
        	Test:       	TestDatabases/redshift_cluster/auto_user_keep
        	Messages:   	waiting for auto user "auto_keep_a84ec916" to be deactivated
```
