### PR TITLE
Sanitize aws service custom endpoints

### LINKED ISSUE #48760: Teleport does not seem to honour the s3 `endpoint` parameter
### Expected behaviour:

Teleport can use any s3-like API with a custom endpoint. e.g. 
```
audit_sessions_uri: 's3://hugo-teleport-17/readonly/records?endpoint=s3.direct.ca-tor.cloud-object-storage.appdomain.cloud&region=ibm'
```

### Current behaviour:

Teleport fails to read from the bucket with the error:
```
2024-11-11T18:01:58Z WARN [AUTH:COMP] Failed to check uploads. error:[
ERROR REPORT:
Original Error: *smithy.OperationError operation error S3: ListMultipartUploads, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get &#34;https://s3.ibm.amazonaws.com/hugo-teleport-17?prefix=readonly%2Frecords&amp;uploads=&#34;: dial tcp: lookup s3.ibm.amazonaws.com on 172.21.0.10:53: no such host
Stack Trace:
        github.com/gravitational/teleport/lib/events/complete.go:217 github.com/gravitational/teleport/lib/events.(*UploadCompleter).CheckUploads
        github.com/gravitational/teleport/lib/events/complete.go:206 github.com/gravitational/teleport/lib/events.(*UploadCompleter).PerformPeriodicCheck
        github.com/gravitational/teleport/lib/events/complete.go:170 github.com/gravitational/teleport/lib/events.(*UploadCompleter).Serve
        runtime/asm_amd64.s:1700 runtime.goexit
User Message: operation error S3: ListMultipartUploads, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Get &#34;https://s3.ibm.amazonaws.com/hugo-teleport-17?prefix=readonly%2Frecords&amp;uploads=&#34;: dial tcp: lookup s3.ibm.amazonaws.com on 172.21.0.10:53: no such host] events/complete.go:209
```

### Bug details:
- Teleport version v17.0.0-alpha.5
- might be caused by the aws-sdk-v2 migration that happened in #44728

### PR DESCRIPTION
**Pull request by rosstimothy**
There is a slight behavior change in aws-sdk-go-v2 regarding custom endpoints. The new sdk requires the endpoints to be a valid URI, and the legacy sdk would allow a hostname only enpoint and automatically apply a scheme. To prevent breaking existing configurations when upgrading to v17, we now have to apply the same logic to endpoints manually that the legacy sdk used to apply for us.

Closes https://github.com/gravitational/teleport/issues/48760.

### CODE REVIEW

**Review by hugoShaka — APPROVED** [review]
LGTM, a few files are missing licenses

File: lib/utils/aws/endpoint/endpoint.go [hunk 1]
```diff
@@ -0,0 +1,29 @@
+package endpoint
+
+import (
+	"fmt"
+	"regexp"
+)
+
+var schemeRegex = regexp.MustCompile("^([^:]+)://")
```
Comment (hugoShaka) [inline lib/utils/aws/endpoint/endpoint.go:8]: nit: Do we really have to write our own regular expression? There is no function in the standard packages doing that?

**Review by r0mant — APPROVED** [review]
