### PR TITLE
Fix incorrect autofill in safari

### LINKED ISSUE #31592: [Safari]: Login options blocked by Safari keychain widget
Safari appears to treat our login options `<input>` as keychain-widget-worthy, making it effectively impossible to click any of the options that it's blocking. One can hit `Esc` to make the keychain widget go away, but that also causes our dropdown to close.

image

### PR DESCRIPTION
**Pull request by avatus**
Fixes: https://github.com/gravitational/teleport/issues/31592

Took me a bit to debug why this was happening. Apparently, `autocomplete` is ignored by almost every browser now. The only reason this showed up in safari specifically is, our input wasn't named or typed like "password" so the browsers think "cool, just an input". but safari actually also checks the PLACEHOLDER text, and since our placeholder text included the word "login", it would ignore the autocomplete and add the widget. You can test this out yourself by changing the placeholder text in this input field with something like "hi". Blew my mind.

The added name prop and value are what safari prescribes to ignore autofill. 

Some info [here](https://stackoverflow.com/questions/22661977/disabling-safari-autofill-on-usernames-and-passwords) with the answer found below the accepted answer (although its all good info)

### CODE REVIEW

**Review by ibeckermayer — APPROVED** [review]

File: web/packages/shared/components/MenuLogin/MenuLogin.tsx [hunk 1]
```diff
@@ -127,6 +127,7 @@ const LoginItemList = ({
       <Input
         p="2"
         m="2"
+        name="notsearch_password"
```
Comment (kimlisa) [inline web/packages/shared/components/MenuLogin/MenuLogin.tsx:130]: can we add explanation here? because i found it pretty strange too

**Review by kimlisa — APPROVED** [review]

File: web/packages/shared/components/MenuLogin/MenuLogin.tsx (hunk 1 above)
Comment (avatus) [reply web/packages/shared/components/MenuLogin/MenuLogin.tsx:136]: Done!
