### PR TITLE
Exit with an error if the auth server is too old

### LINKED ISSUE #11854: Don't start Teleport agents if Auth Server is older, add `--skip-version-check` to override
Starting in Teleport 10, do not start Teleport agents if Auth Server is older than the node. This will prevent issues like the following from happening: https://github.com/gravitational/teleport/issues/11161.

* Add version check on startup of agents.
* Fail if the Auth Server is one major version older than the agent. Return an error to the user indicating they should use `--skip-version-check` if they still want to connect.
* Add `--skip-version-check`. This flag should match the one `tsh` already supports.
* Update Teleport 10 release notes with these breaking changes.

### PR DESCRIPTION
**Pull request by capnspacehook**
If the auth server's major version is less than the connecting Teleport
agent, the agent will now log an error and exit to avoid cryptic errors like
in #11161. '--skip-version-check' flag was added so users can override this
behavior if they wish.

Fixes #11854.

### CODE REVIEW

File: lib/service/connect.go [hunk 1]
```diff
@@ -104,19 +111,22 @@ func (process *TeleportProcess) reconnectToAuthService(role types.SystemRole) (*
 	}
 }
 
-func (process *TeleportProcess) compareVersions(resp *proto.PingResponse) error {
+func (process *TeleportProcess) authServerTooOld(resp *proto.PingResponse) (bool, error) {
```
Comment (Joerger) [inline lib/service/connect.go:114]: nit: this can be made simpler by returning a `trace.NotImplemented` instead of an extra `bool` return. Then, the caller can check `trace.IsNotImplemented(err)` instead. Something like:

```
if err := process.authServerTooOld(...); trace.IsNotImplemented(err) {
    if !process.Config.SkipVersionCheck {
        return nil, trace.Wrap(err)
    }
} else if err != nil {
    return nil, trace.Wrap(err)
}
```

File: lib/service/connect.go [hunk 2]
```diff
@@ -104,19 +111,22 @@ func (process *TeleportProcess) reconnectToAuthService(role types.SystemRole) (*
...
 	teleportVersion, err := semver.NewVersion(teleport.Version)
 	if err != nil {
-		return trace.Wrap(err)
+		return false, trace.Wrap(err)
 	}
-	if math.Abs(float64(serverVersion.Major-teleportVersion.Major)) > 1 {
-		process.log.Warnf("Only versions %d and %d are supported, auth server is %s.", teleportVersion.Major, teleportVersion.Major-1, serverVersion.Major)
+
+	if serverVersion.Major < teleportVersion.Major {
+		process.log.Errorf("Only versions %d and greater are supported, auth server is version %d. To connect anyway pass the '--skip-version-check' flag.", teleportVersion.Major, serverVersion.Major)
```
Comment (Joerger) [inline lib/service/connect.go:125]: Do we want to log this even if the user provided "--skip-version-check"? If so, it might make more sense to change the logged message depending on whether it was provided.

File: lib/service/connect.go [hunk 3]
```diff
@@ -67,8 +66,16 @@ func (process *TeleportProcess) reconnectToAuthService(role types.SystemRole) (*
...
-					process.log.Debugf("Error comparing formats: %v", err)
+
+				if !process.Config.SkipVersionCheck {
+					isOlder, compareErr := process.authServerTooOld(&pingResponse)
+					if compareErr != nil {
+						process.log.Errorf("Error comparing formats: %v", compareErr)
+						return nil, trace.Wrap(err)
+					}
+					if isOlder {
+						return nil, trace.NotImplemented("auth server is too old")
```
Comment (Joerger) [inline lib/service/connect.go:77]: nit: This error "auth server is too old" will be logged as an `ERROR` and will be the first thing the user sees rather than `WARN` "Only versions %d and greater are supported, auth server is version %d ...", the latter being much more descriptive.

Related to my other comment, we should aim for one good `WARN` log if `--skip-version-check=true` and one good `ERROR` log if `--skip-version-check=false`

**Review by Joerger — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Review by r0mant — COMMENTED** [review]
@capnspacehook Before we can merge this, please also:
- Write a unit test for this scenario.
- Update documentation to show the new flag: teleport CLI reference and upgrade compatibility page: https://goteleport.com/docs/setup/operations/upgrading/.
