### PR TITLE
make tsh match against discovered db name

### LINKED ISSUE #31286: `tsh db connect <rds-primary-endpoint>`  throws `matches multiple databases` error
Expected behavior:
`tsh db connect <rds-primary-endpoint>`  should connect to db

Current behavior:
```
$ tsh db logout
$ tsh db ls --search steve-mysql
Name                   Description                                      Allowed Users Labels                                                                                                                                                            Connect 
---------------------- ------------------------------------------------ ------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------- ------- 
steve-mysql-custom-one Aurora cluster in ca-central-1 (custom endpoint) [*]           Env=dev,Name=steve-mysql,Owner=STeve,account-id=123123123123,endpoint-type=custom,engine-version=8.0.mysql_aurora.3.02.2,engine=aurora-mysql,region=ca-central-1          
steve-mysql-custom-two Aurora cluster in ca-central-1 (custom endpoint) [*]           Env=dev,Name=steve-mysql,Owner=STeve,account-id=123123123123,endpoint-type=custom,engine-version=8.0.mysql_aurora.3.02.2,engine=aurora-mysql,region=ca-central-1
steve-mysql            Aurora cluster in ca-central-1                   [*]           Env=dev,Name=steve-mysql,Owner=STeve,account-id=123123123123,endpoint-type=primary,engine-version=8.0.mysql_aurora.3.02.2,engine=aurora-mysql,region=ca-central-1
steve-mysql-reader     Aurora cluster in ca-central-1 (reader endpoint) [*]           Env=dev,Name=steve-mysql,Owner=STeve,account-id=123123123123,endpoint-type=reader,engine-version=8.0.mysql_aurora.3.02.2,engine=aurora-mysql,region=ca-central-1

$ tsh db connect --db-user alice --db-name test steve-mysql
ERROR: database "steve-mysql" matches multiple databases:

Name                                                        Description                                      Protocol Type URI                                                                     Allowed Users Labels
                                                      Connect 
----------------------------------------------------------- ------------------------------------------------ -------- ---- ----------------------------------------------------------------------- ------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------- ------- 
steve-mysql-custom-one-rds-aurora-ca-central-1-123123123123 Aurora cluster in ca-central-1 (custom endpoint) mysql    rds  one.cluster-custom-aabbccddeeff.ca-central-1.rds.amazonaws.com:3306     (unknown)     Env=dev,Name=steve-mysql,Owner=STeve,account-id=123123123123,endpoint-type=custom,engine-version=8.0.mysql_aurora.3.02.2,engine=aurora-mysql,region=ca-central-1,teleport.dev/cloud=AWS,teleport.dev/origin=cloud,tel
eport.internal/discovered-name=steve-mysql-custom-one         
steve-mysql-custom-two-rds-aurora-ca-central-1-123123123123 Aurora cluster in ca-central-1 (custom endpoint) mysql    rds  two.cluster-custom-aabbccddeeff.ca-central-1.rds.amazonaws.com:3306     (unknown)     Env=dev,Name=steve-mysql,Owner=STeve,account-id=123123123123,endpoint-type=custom,engine-version=8.0.mysql_aurora.3.02.2,engine=aurora-mysql,region=ca-central-1,teleport.dev/cloud=AWS,teleport.dev/origin=cloud,tel
eport.internal/discovered-name=steve-mysql-custom-two         
steve-mysql-rds-aurora-ca-central-1-123123123123            Aurora cluster in ca-central-1                   mysql    rds  steve-mysql.cluster-aabbccddeeff.ca-central-1.rds.amazonaws.com:3306    (unknown)     Env=dev,Name=steve-mysql,Owner=STeve,account-id=123123123123,endpoint-type=primary,engine-version=8.0.mysql_aurora.3.02.2,engine=aurora-mysql,region=ca-central-1,teleport.dev/cloud=AWS,teleport.dev/origin=cloud,te
leport.internal/discovered-name=steve-mysql                   
steve-mysql-reader-rds-aurora-ca-central-1-123123123123     Aurora cluster in ca-central-1 (reader endpoint) mysql    rds  steve-mysql.cluster-ro-aabbccddeeff.ca-central-1.rds.amazonaws.com:3306 (unknown)     Env=dev,Name=steve-mysql,Owner=STeve,account-id=123123123123,endpoint-type=reader,engine-version=8.0.mysql_aurora.3.02.2,engine=aurora-mysql,region=ca-central-1,teleport.dev/cloud=AWS,teleport.dev/origin=cloud,tel
eport.internal/discovered-name=steve-mysql-reader

Hint: use 'tsh db ls -v' or 'tsh db ls --format=[json|yaml]' to list all databases with full details.
Hint: try selecting the database with a more specific name (ex: tsh db connect steve-mysql-custom-one-rds-aurora-ca-central-1-123123123123).
Hint: try selecting the database with additional --labels or --query predicate.
```

Bug details:
- Teleport version: `"server_version": "14.0.0-alpha.2",`

Workaround:
`tsh db connect --db-user alice --db-name test steve-mysql-rds-aurora-ca-central-1-123123123123`

Feels like a regression but it could also be "as designed" from the renaming feature.

Besides `tsh db connect` throws an error, the table dumped from the error is not very readable when there are lots of tags and the row running over to next line.

Test Plan: https://github.com/gravitational/teleport/issues/31122

### PR DESCRIPTION
**Pull request by GavinFrazar**
Fixes https://github.com/gravitational/teleport/issues/31286

changelog: `tsh` commands can select a database by the original database name instead of the more detailed name generated by the v14+ Teleport Discovery service.

## What
This PR changes `tsh db` commands to check for an exact match of the "discovered name" label that is added to discovered databases.

## Why
The purpose of this change, is to avoid breaking any existing scripts after v14 discovery renaming goes live.

The logic here was getting quite complicated, and test coverage was insufficient, so I refactored to simplify the code and make it easier to unit test functions.

### CODE REVIEW

File: tool/tsh/common/db.go [hunk 1]
```diff
@@ -908,66 +962,48 @@ type databaseInfo struct {
...
 	// that database over any others.
 	for _, db := range databases {
-		if db.GetName() == nameOrPrefix {
+		if db.GetName() == selectors.name {
 			return db, nil
 		}
 	}
+	// look for a single database with a matching discovered name label.
+	if dbs, ok := findDatabasesByDiscoveredName(databases, selectors.name); ok {
+		databases = dbs
```
Comment (smallinsky) [inline tool/tsh/common/db.go:1000]: For readability and safety can we create a internal variable instead of using input param ?

File: tool/tsh/common/db.go [hunk 2]
```diff
@@ -1248,115 +1292,95 @@ func isMFADatabaseAccessRequired(ctx context.Context, tc *client.TeleportClient,
 //
 // If logged into multiple databases, returns an error unless one specified
 // explicitly via --db flag.
-func pickActiveDatabase(cf *CLIConf, tc *client.TeleportClient) (*tlsca.RouteToDatabase, error) {
-	profile, err := tc.ProfileStatus()
-	if err != nil {
-		return nil, trace.Wrap(err)
+func pickActiveDatabase(cf *CLIConf, tc *client.TeleportClient, routes []tlsca.RouteToDatabase) (*tlsca.RouteToDatabase, error) {
```
Comment (smallinsky) [inline tool/tsh/common/db.go:1295]: The input parameter for this function is `routes []tlsca.RouteToDatabase`   that orginates from 
```
routes, err := profile.DatabasesForCluster(tc.SiteName) 
``` 
notice that the `DatabasesForCluster`  call already returns active databases   [findActiveDatabases](https://github.com/gravitational/teleport/blob/master/lib/client/profile.go#L554)

File: tool/tsh/common/db.go [hunk 3]
```diff
@@ -1248,115 +1292,95 @@ func isMFADatabaseAccessRequired(ctx context.Context, tc *client.TeleportClient,
...
 	}
-
-	routes, err := profile.DatabasesForCluster(tc.SiteName)
+	info, err := getDatabaseInfo(cf, tc, routes)
 	if err != nil {
 		return nil, trace.Wrap(err)
 	}
+	if !info.isActive {
+		return nil, trace.NotFound(formatDbNotLoggedIn(cf.SiteName, selectors))
+	}
```
Comment (smallinsky) [inline tool/tsh/common/db.go:1308]: The input parameter for this function is `routes []tlsca.RouteToDatabase`   that orginates from 
```
routes, err := profile.DatabasesForCluster(tc.SiteName) 
``` 
notice that the `DatabasesForCluster`  call already returns active databases   [findActiveDatabases](https://github.com/gravitational/teleport/blob/master/lib/client/profile.go#L554)

Why we need to check isActive one more time ?

File: tool/tsh/common/db.go [hunk 4]
```diff
@@ -1373,6 +1397,44 @@ func findActiveDatabase(name string, activeRoutes []tlsca.RouteToDatabase) (tlsc
...
+	var out []tlsca.RouteToDatabase
+	for _, r := range routes {
+		if strings.HasPrefix(r.ServiceName, prefix) {
+			out = append(out, r)
+		}
+	}
+	return out
+}
+
+func formatDbNotLoggedIn(clusterFlag string, selectors resourceSelectors) string {
```
Comment (smallinsky) [inline tool/tsh/common/db.go:1420]:
```suggestion
func formatDBNotLoggedIn(clusterFlag string, selectors resourceSelectors) string {
```

File: tool/tsh/common/db.go [hunk 5]
```diff
@@ -1248,115 +1292,95 @@ func isMFADatabaseAccessRequired(ctx context.Context, tc *client.TeleportClient,
...
+// Logout selection is done by matching on database name/prefix, label, query
+// predicate selectors from the Teleport client.
+func getDatabasesForLogout(cf *CLIConf, tc *client.TeleportClient, activeRoutes []tlsca.RouteToDatabase) ([]tlsca.RouteToDatabase, error) {
+	selectors := newDatabaseResourceSelectors(cf)
+	activeRoutes = filterRoutesByPrefix(activeRoutes, selectors.name)
+	if len(activeRoutes) == 0 || selectors.IsEmpty() {
+		// nothing to filter further
+		return activeRoutes, nil
+	}
+	if route, ok := maybeFindActiveDatabase(selectors, activeRoutes); ok {
```
Comment (greedy52) [inline tool/tsh/common/db.go:1323]: How is the rest of this function starting here different from `pickActiveDatabase`? To me this is a better implementation. Could we merge the two?

Comment (GavinFrazar) [reply tool/tsh/common/db.go:1323]: In a couple of ways.  This function can return multiple databases for logout. It can also select an active route to logout of even when the database is no longer registered.

Whereas `pickActiveDatabase` needs to get exactly one database, and it should ignore active routes that correspond to databases that no longer exist.

File: tool/tsh/common/db.go (hunk 3 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go:1308]: Because it calls `getDatabaseInfo` - that func will resolve the name, labels, and query selectors to a single database and then search for that database's full name in the active db routes passed to it. `getDatabaseInfo` doesn't necessarily find an active db though, it just looks for one so it can copy the db user/schema from an active route

File: tool/tsh/common/db.go (hunk 2 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go:1295]: Because it calls getDatabaseInfo - that func will resolve the name, labels, and query selectors to a single database and then search for that database's full name in the active db routes passed to it. getDatabaseInfo doesn't necessarily find an active db though, it just looks for one so it can copy the db user/schema from an active route

Comment (GavinFrazar) [reply tool/tsh/common/db.go:1295]: It needs to pick among the active routes it is passed. Doing so requires that it resolve the full db name.

It has to filter routes by name prefix, labels, query predicate, and then look for:
1. an exact full name match
2. an exact match of a discovered name
3. a single remaining database

File: tool/tsh/common/db.go [hunk 6]
```diff
@@ -785,83 +804,114 @@ func onDatabaseConnect(cf *CLIConf) error {
...
-		routes, err := profile.DatabasesForCluster(tc.SiteName)
+// getDatabaseInfoFromActiveRoutes queries the cluster for databases matching
+// the currently active database routes in profile, and selects one.
+// Callers should ensure that there are no database name, --labels, or --query
+// selectors given, because this function assumes there are none; panics if any
+// selectors are given.
+func getDatabaseInfoFromActiveRoutes(cf *CLIConf, tc *client.TeleportClient, routes []tlsca.RouteToDatabase) (*databaseInfo, error) {
+	selectors := newDatabaseResourceSelectors(cf)
+	if !selectors.IsEmpty() {
+		panic(trace.BadParameter("getDatabaseInfoFromActiveRoutes called with selectors `%v` (this is a bug)", selectors))
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply tool/tsh/common/db.go:848]: sure

File: tool/tsh/common/db.go (hunk 1 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go:1000]: could you clarify what you mean?

File: tool/tsh/common/db.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply tool/tsh/common/db.go]: 07fb4b627ab15ec577848e069eaca541b6617aa1

File: tool/tsh/common/db.go [hunk 7]
```diff
@@ -361,7 +369,7 @@ func onDatabaseLogout(cf *CLIConf) error {
 	if err != nil {
 		return trace.Wrap(err)
 	}
-	logout, _, err := filterActiveDatabases(cf.Context, tc, activeRoutes)
+	logout, err := getDatabasesForLogout(cf, tc, activeRoutes)
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply tool/tsh/common/db.go]: fbedee8936702b63119864eaf892515026896b0a

File: tool/tsh/common/db.go (hunk 4 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go]: d79309fbc6ae4778807446d2de8754103061adce

File: tool/tsh/common/db.go (hunk 2 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go:1295]: also, the reason I made these functions take the `[]tlsca.RouteToDatabase` as an argument instead of just getting them from the profile, was to make unit testing them much easier - allows me to control which databases are "logged into" in tests.

File: tool/tsh/common/db.go (hunk 5 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go:1323]: fwiw, this function was originally just `filterActiveDatabases`, and it was used by both `pickActiveDatabase` and `onDatabaseLogout`. I find it easier to understand the code if I keep `tsh db logic` selection logic separate from the other `tsh db` commands, because it's uniquely able to select multiple databases unlike the other commands.

So this way, `tsh db logout` does its special case logic in this func, and all other `tsh db` commands flow through `getDatabaseInfo` to get a single database

File: tool/tsh/common/db.go (hunk 3 above)
Comment (greedy52) [reply tool/tsh/common/db.go:1308]: What happens in this case?

0. user has access to `mysql` and mysql2`?
1. `tsh db login mysql --db-user user`
2. `tsh db login mysql2 --db-user user`
3. remove `mysql` from "backend"
4. `tsh db config mysql`

Or the same sequence without #2. 

I thought I was somewhat familiar with the recent changes, but I am having a hard time tracking cases through these calls =p.

File: tool/tsh/common/db.go (hunk 5 above)
Comment (greedy52) [reply tool/tsh/common/db.go:1323]: > This function can return multiple databases for logout. 

For example, say there are two databases `aurora` and `aurora-reader`
- `tsh db logout aurora` logs out one database
- `tsh db logout auror` or `tsh db logout aurora-` logs out both databases?

To be honest, personally, I would just ask the user to pick one to log out in the later cases.

>  It can also select an active route to logout of even when the database is no longer registered.

That's a good point.  Just now we have three version of very similar logic (connect/proxy, env/config, logout). The next person working on changing this logic will definitely have a hard time =p

File: tool/tsh/common/db.go (hunk 3 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go:1308]: If you `tctl rm db/mysql` in step 2, then in step 4 you will get an error since you are not logged into `foo2` which matches by prefix now:
```
$ tsh db ls env=test 
Name Description                   Allowed Users Labels   Connect 
---- ----------------------------- ------------- -------- ------- 
foo  Example dyn database resource [*]           env=test         
foo2 Example dyn database resource [*]           env=test         

$ tsh db login --db-user=alice foo 
Connection information for database "foo" has been saved.

You can now connect to it using the following command:

  tsh db connect foo

You can view the connect command for the native database CLI client:

  tsh db config --format=cmd foo

$ tctl rm db/foo 
database "foo" has been deleted

$ tsh db config foo 
ERROR: please provide the database user using the --db-user flag, allowed database users for foo2: [*]
```

If you don't delete the backend database, then it works:
```
$ tsh db config foo 
Name:      foo
Host:      gavin-leaf.cloud.gravitational.io
Port:      3080
User:      alice
Database:  
CA:        /Users/gavin/.tsh/keys/gavin-leaf.cloud.gravitational.io/cas/gavin-leaf.cloud.gravitational.io.pem
Cert:      /Users/gavin/.tsh/keys/gavin-leaf.cloud.gravitational.io/gavin.frazar@goteleport.com-db/gavin-leaf.cloud.gravitational.io/foo-x509.pem
Key:       /Users/gavin/.tsh/keys/gavin-leaf.cloud.gravitational.io/gavin.frazar@goteleport.com
```

File: tool/tsh/common/db.go (hunk 5 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go:1323]: what changes would you like to see?

1. make `tsh db logout <some name/labels/query>` requires only one database selected? So it disallows logging out of multiple except in the case where they just do `tsh db logout` and it logs out of all?
2. config/env will just pick the active database regardless of whether it exists in backend? note that `tsh db ls` has never displayed logged in databases that aren't registered in the backend anymore. so it's kinda like a phantom cert in their profile if we don't ignore it.

Comment (greedy52) [reply tool/tsh/common/db.go:1323]: > Now, if they have a logged in db that doesn't exist, it can interfere with selecting a registered database if the name matches exactly.

Could you give an example of this case?

Maybe disallow prefix match when <db-service-name> is specified? just exact-full-name or exactly-one-discover-name?

Comment (GavinFrazar) [reply tool/tsh/common/db.go:1323]: This is on master:

```
$ tsh db ls env=test
tsh dName                 Description                   Allowed Users Labels   Connect
-------------------- ----------------------------- ------------- -------- -------------------
> foo (user: alice)  Example dyn database resource [*]           env=test tsh db connect foo
> foo2 (user: alice) Example dyn database resource [*]           env=test tsh db connect foo2

$ tsh db env foo
export MYSQL_GROUP_SUFFIX=_gavin-leaf.cloud.gravitational.io-foo

$ tctl rm db/foo
database "foo" has been deleted

$ tsh db ls env=test
Name                 Description                   Allowed Users Labels   Connect
-------------------- ----------------------------- ------------- -------- -------------------
> foo2 (user: alice) Example dyn database resource [*]           env=test tsh db connect foo2

$ tsh db env foo
export MYSQL_GROUP_SUFFIX=_gavin-leaf.cloud.gravitational.io-foo

$ tsh db logout foo
Logged out of database foo

$ tsh db logout foo
Logged out of database foo2
```

Comment (GavinFrazar) [reply tool/tsh/common/db.go:1323]: I figured this might screw up a script after the v13->v14 upgrade.

Suppose they're logged into `mysql-rds`.
Then discovery agent upgrades to v14 and it renames it to `mysql-rds-etc...`
then the script does `tsh db login mysql-rds && tsh db [env | config] mysql-rds`
The script will login to `mysql-rds-etc...`, then get config for the stale cert they had instead of the database they just logged into

Maybe I'm just overthinking it. It's not terrible lol.

File: tool/tsh/common/db.go (hunk 3 above)
Comment (greedy52) [reply tool/tsh/common/db.go:1308]: > edit: oh, you asked about logging into both. In that case, it will display config for mysql2

I just ran into a similar situation

1.  `tsh db connect self-hosted-redis`
2.  `self-hosted-redis` from my config, restart db agent
3.  `tsh db connect self-hosted-redis` connects to `self-hosted-redis-cluster`.

I would rather see:
```
$ tsh db connect self-hosted-redis
ERROR: database "self-hosted-redis" not found, use 'tsh db ls' to see registered databases
```

> I figured this might screw up a script after the v13->v14 upgrade.

Personally I am not that worried about stale certs. I am sure it happens today even without the renaming change when admin removes a database. I think the above not-found error is very clear.

Here is my recommendation to adjust the logic for `tsh db connect/config/env/logout`/`tsh proxy db`

- If `--labels/--query` is specified for, the API must return exactly one DB (same as now?)
- If `database-service-name` is specified
  - Prefer exact full name match
  - Then exactly one discovered name match
  - Do NOT allow any other prefix matching. like input `mysq` shouldn't connect a database `mysql`.
- `database-service-name` vs `--labels/--query` should be mutually exclusive

@smallinsky @GavinFrazar what do you guys think?

Comment (smallinsky) [reply tool/tsh/common/db.go:1308]: > I just ran into a similar situation

> tsh db connect self-hosted-redis
> self-hosted-redis from my config, restart db agent
> tsh db connect self-hosted-redis connects to self-hosted-redis-cluster.

> Here is my recommendation to adjust the logic for tsh db connect/config/env/logout/tsh proxy db

> If --labels/--query is specified, the API must return exactly one DB (same as now?)
If database-service-name is specified
Prefer exact full name match
Then exactly one discovered name match
Do NOT allow any other prefix matching. like input mysq shouldn't connect a database mysql.
database-service-name vs --labels/--query should be mutually exclusive

This can also also happen for `database-service-name` for instance if  the `rds-instance01` db has been  removed/deleted and another db was added with the shared db name prefix like `rds-instance02` the ` tsh db connect rds-instance` will connect to `rds-instance02` 

But for backward compatibility this is safer because we will not silently select  unintended db. So I agree that for backward capability this logic is better.

Comment (GavinFrazar) [reply tool/tsh/common/db.go:1308]: > database-service-name vs --labels/--query should be mutually exclusive
Why?

File: tool/tsh/common/db.go (hunk 1 above)
Comment (GavinFrazar) [reply tool/tsh/common/db.go:1000]: it doesn't modify the slice in any way, if that's the concern

File: tool/tsh/common/db.go (hunk 3 above)
Comment (greedy52) [reply tool/tsh/common/db.go:1308]: > Why ?

👍 hmm. or use the stricter rules when both are specified. I guess `tsh db connect rds --labels env=prod` is a very good use case

Comment (GavinFrazar) [reply tool/tsh/common/db.go]: @smallinsky @greedy52  I reworked the selection logic to follow Steve's suggestions here: faed6ca 

- match full name exactly
- OR match an unambiguous "discovered name"
- no prefix matching.

This preserves backwards compatibility, without being a nightmare of edge cases and unexpected or suprising UX.
Great suggestion Steve!

If these changes are approved then I'll do the same for `tsh kube` and `tctl` as well, which should be a much smaller and easier change for those commands.

Comment (GavinFrazar) [reply tool/tsh/common/db.go]: one caveat that I discussed with Steve over slack:

if a user has to resolve an ambiguous discovered name with a label to login, the logged in db can resolve ambiguity with further commands.

For example:

```
suppose you have databases like
...
foo-rds-us-west-1 (short name: foo)
foo-rds-us-west-2 (short name: foo)

$ tsh db login foo
...<ambiguous db error>...

$ tsh db login foo --labels region=us-west-1
...<logs into foo-rds-us-west-1>...

$ tsh db connect foo
...connects to foo-rds-us-west-1...
```

This seems more consistent UX, given that we support `tsh db connect` auto-selecting an active route.

**Review by smallinsky — APPROVED** [review]
Thanks for the fix. LGMT if tested. 
I will do an additional testing later.

File: tool/tsh/common/db.go [hunk 8]
```diff
@@ -977,52 +976,78 @@ func chooseOneDatabase(cf *CLIConf, nameOrPrefix string, databases types.Databas
...
 }
 
-// listDatabasesByName lists database that match a given name.
-func listDatabasesByName(ctx context.Context, tc *client.TeleportClient, name string) (types.Databases, error) {
-	predicate := fmt.Sprintf("name == %q", name)
-	return listDatabasesWithPredicate(ctx, tc, predicate)
+func makeDiscoveredNameOrNamePredicate(name string) string {
+	matchName := makeNamePredicate(name)
+	matchDiscoveredName := makeDiscoveredNamePredicate(name)
+	return makePredicateDisjunction(matchName, matchDiscoveredName)
```
Comment (greedy52) [inline tool/tsh/common/db.go:995]: nice 👍

File: tool/tsh/common/db_test.go [hunk 9]
```diff
@@ -1395,3 +1123,537 @@ func TestChooseOneDatabase(t *testing.T) {
...
+}
+
+// TestDatabaseSelection tests database selection by name, prefix name, labels,
+// query, etc.
+func TestDatabaseSelection(t *testing.T) {
+	testenv.WithResyncInterval(t, 0)
+	testenv.WithInsecureDevMode(t, true)
+	t.Run("GetDatabasesForLogout", testGetDatabasesForLogout)
+	t.Run("GetDatabaseInfo", testGetDatabaseInfo)
+	t.Run("PickActiveDatabase", testPickActiveDatabase)
```
Comment (greedy52) [inline tool/tsh/common/db_test.go:1252]: nit: can these tests share a setup?

**Review by greedy52 — APPROVED** [review]
Thanks for the update. Love it 👍 

One small nit: maybe we can add debug log in important branches just in case we have to debug this in the field. Maybe the predicate used for the API too.

File: tool/tsh/common/db_test.go (hunk 9 above)
Comment (GavinFrazar) [reply tool/tsh/common/db_test.go]: done: [e73a2b1](https://github.com/gravitational/teleport/pull/31689/commits/e73a2b1888a8e6fbeda44d15fb4484f4a1dd2bdb)
