### PR TITLE
Check for shell user's home directory as that user

### LINKED ISSUE #10177: PR #9413 results in user home directories set to "/" when root squashing is enabled
### Description

**What happened**:

#9413 results in user home directories set to "/" when root squashing is enabled.

**What you expected to happen**:

The users home directory should be tested in the context of the user with appropriate permissions, not root which is re-mapped to an anonymous user / nfsnobody.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup an NFS export with `root_squash` (which is the default).
2. Mount the above export to `/home`.
3. Restrict permissions on `/home` to `2750` or similar.
4. Populate with a user directory and attempt to login as that user.
5. You'll get dropped into `/` with `$HOME=/`

```
    [drwsr-S---]  /home
    ├── [drwx--S---]  bar
    ├── [drwx--S---]  baz
    └── [drwxr-s---]  foo
```

### Server Details
- Teleport version (run `teleport version`): 8.1.1
- Server OS (e.g. from `/etc/os-release`): `PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicated

### Client Details
- Tsh version (`tsh version`): 8.1.1
- Computer OS (e.g. Linux, macOS, Windows): Linux, macOS, Windows
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): yum

### Debug Logs
Nothing relevant in either set of debug logs but can provide if necessary.

### PR DESCRIPTION
**Pull request by Joerger**
This PR updates the use's home dir check when starting a shell session to check the dir in the context of the logged in user rather than root. This is done by re-execing teleport with the new subcommand `checkhomedir`.

Another small change: In https://github.com/gravitational/teleport/pull/9413, $HOME would be set to "/" if $HOME doesn't exist. However, in OpenSSH $HOME is not changed when dropping the user into "/", so I updated the logic to match OpenSSH.

Closes https://github.com/gravitational/teleport/issues/10177

### CODE REVIEW

File: lib/srv/reexec.go [hunk 1]
```diff
@@ -412,6 +412,18 @@ func RunForward() (io.Writer, int, error) {
 	return ioutil.Discard, teleport.RemoteCommandSuccess, nil
 }
 
+// runCheckHomeDir check's if the active user's $HOME dir exists.
+func runCheckHomeDir() (io.Writer, int, error) {
```
Comment (zmb3) [inline lib/srv/reexec.go:416]: In this case, I might name the return values.

Also, returning a nil writer feels like it could cause an issue, as the caller never checks if `w != nil`.  How about returning `io.Discard` instead of nil

**Review by zmb3 — APPROVED** [review]

File: lib/srv/reexec.go (hunk 1 above)
Comment (Joerger) [reply lib/srv/reexec.go]: I'll also update `RunForward` and `RunCommand` to use named returns to keep it consistent.

**Review by timothyb89 — APPROVED** [review]

**Comment by russjones** [comment]
@Joerger This test keeps failing on CI and seems to be killed at this 6 minute mark. Something odd going on.

**Comment by Joerger** [comment]
@zmb3 Could you make another pass since I've made some changes (mostly to tests)

File: integration/integration_test.go [hunk 2]
```diff
@@ -624,7 +624,7 @@ func TestMain(m *testing.M) {
 	// If the test is re-executing itself, execute the command that comes over
 	// the pipe.
 	if len(os.Args) == 2 &&
-		(os.Args[1] == teleport.ExecSubCommand || os.Args[1] == teleport.ForwardSubCommand) {
+		(os.Args[1] == teleport.ExecSubCommand || os.Args[1] == teleport.ForwardSubCommand || os.Args[1] == teleport.CheckHomeDirSubCommand) {
```
Comment (zmb3) [inline integration/integration_test.go:627]:
```
switch os.Args[1] {
    case teleport.ExecSubCommand, teleport.ForwardSubCommand, teleport.CheckHomeDirSubCommand:
        srv.RunAndExit(os.Args[1])
        return
}
```

A switch might be a tiny bit nicer, but totally up to you.

**Review by zmb3 — APPROVED** [review]
