### PR TITLE
Fix flaky test `TestTSHConfigConnectWithOpenSSHClient`

### LINKED ISSUE #13623: `TestTSHConfigConnectWithOpenSSHClient` flakiness
## Failure
saw this fail off of branch/v10

### CI Logs
- https://console.cloud.google.com/cloud-build/builds/8cd306c3-13b3-454f-bbb3-f3ccf70f797b?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/d926b469-8a79-41a0-891f-bcb54f9b8ae1;step=0?project=ci-account

### Relevant snippet
```
proxy_test.go:590: failed to find AuthAttemptFailureCode event
    --- FAIL: TestTSHConfigConnectWithOpenSSHClient/node_recording_mode_with_TLS_routing_enabled (6.28s)
```

### PR DESCRIPTION
**Pull request by Joerger**
Closes https://github.com/gravitational/teleport/issues/13623

### CODE REVIEW

**Review by greedy52 — APPROVED** [review]

File: tool/tsh/common/proxy_test.go [hunk 1]
```diff
@@ -1100,14 +1100,15 @@ func mustSearchEvents(t *testing.T, auth *auth.Server) []apievents.AuditEvent {
 }
 
 func mustFindFailedNodeLoginAttempt(t *testing.T, s *suite, nodeLogin string) {
-	av := mustSearchEvents(t, s.root.GetAuthServer())
-	for _, e := range av {
-		if e.GetCode() == events.AuthAttemptFailureCode {
-			require.Equal(t, e.(*apievents.AuthAttempt).Login, nodeLogin)
-			return
+	require.Eventually(t, func() bool {
+		es := mustSearchEvents(t, s.root.GetAuthServer())
```
Comment (zmb3) [inline tool/tsh/common/proxy_test.go:1104]: `mustSearchEvents` is going to call `require.NoError`, which will fail the entire test the first time this fails, even if a future call succeeds. This is probably not what you want. (On top of this, the closure will now run in a different goroutine where it's not legal to call `require.NoError`)

I think `require.EventuallyWithT` and updating `mustSearchEvents` to use `assert` instead of `require` should do the trick.

**Review by zmb3 — CHANGES_REQUESTED** [review]

File: tool/tsh/common/proxy_test.go [hunk 2]
```diff
@@ -1086,28 +1086,24 @@ func mustFailToRunOpenSSHCommand(t *testing.T, configFile string, sshConnString
...
-	return events
-}
-
 func mustFindFailedNodeLoginAttempt(t *testing.T, s *suite, nodeLogin string) {
-	av := mustSearchEvents(t, s.root.GetAuthServer())
-	for _, e := range av {
-		if e.GetCode() == events.AuthAttemptFailureCode {
-			require.Equal(t, e.(*apievents.AuthAttempt).Login, nodeLogin)
-			return
+	require.EventuallyWithT(t, func(t *assert.CollectT) {
```
Comment (tigrato) [inline tool/tsh/common/proxy_test.go:1090]: can you just rename `t *assert.CollectT` ti something like `c *assert.CollectT` to make it clear that it's not `t *testing.T`

**Review by tigrato — APPROVED** [review]

File: tool/tsh/common/proxy_test.go (hunk 2 above)
Comment (zmb3) [reply tool/tsh/common/proxy_test.go:1090]: I disagree. Shadowing t makes it impossible to use the wrong one. Keep it!

File: tool/tsh/common/proxy_test.go [hunk 3]
```diff
@@ -1086,28 +1086,24 @@ func mustFailToRunOpenSSHCommand(t *testing.T, configFile string, sshConnString
...
+		ctx := context.Background()
+		es, _, err := s.root.GetAuthServer().SearchEvents(ctx, events.SearchEventsRequest{
+			From:  now.Add(-time.Hour),
+			To:    now.Add(time.Hour),
+			Order: types.EventOrderDescending,
+		})
+		assert.NoError(t, err)
+
+		for _, e := range es {
+			if e.GetCode() == events.AuthAttemptFailureCode && e.(*apievents.AuthAttempt).Login == nodeLogin {
```
Comment (zmb3) [inline tool/tsh/common/proxy_test.go:1101]: The semantics here are slightly different than what we had before - is this intentional?

Before, if there was an AuthAttempt failure, the test would fail if the login was incorrect.

After, we just ignore these events if the login is incorrect.

Comment (Joerger) [reply tool/tsh/common/proxy_test.go]: Good catch, fixed

**Review by zmb3 — APPROVED** [review]

**Comment by nklaassen** [comment]
I went ahead and opened the backports since Brian is still OOO and I just hit this on branch/v14
