### PR TITLE
remove symlink usage for tsh profile

### LINKED ISSUE #4095: Non-admin windows users error with tsh login
### Description
**What happened**:
If a non-admin user in Win10 attempts to login they can get an error on symbolic links.

**What you expected to happen**:

`tsh` will allo login or provide a workaround.

**How to reproduce it (as minimally and precisely as possible)**:

Create a windows 10 environment.  Create a non-admin default user.  Attempt to login with `tsh login` with that user.

### Environment
* Teleport version (use `teleport version`): 4.3.0
* Tsh version (use `tsh version`): 4.3.0
* OS (e.g. from `/etc/os-release`): Windows 10
* Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Relevant Debug Logs If Applicable**

* `tsh --debug`

```cmd
←[37mDEBU←[0m [KEYSTORE]  Returning SSH certificate "C:\\Users\\testuser\\.tsh\\keys\\tele1c.gravitational.co\\steven@gravitational.com-cert.pub" valid until "2020-07-22 00:04:08 -0400 EDT", TLS certificate "C:\\Users\\testuser\\.tsh\\keys\\tele1c.gravitational.co\\user@site.com-x509.pem" valid until "2020-07-22 04:04:08 +0000 UTC". client\keystore.go:277
←[33mWARN←[0m [CLIENT]    Failed to remove symlink: remove C:\Users\testuser\.tsh\profile: The system cannot find the file specified. client\profile.go:150

ERROR REPORT:
Original Error: *os.LinkError symlink tele1c.gravitational.co.yaml C:\Users\testuser\.tsh\profile: A required privilege is not held by the client.
Stack Trace:
        /gopath/src/github.com/gravitational/teleport/lib/client/profile.go:154 github.com/gravitational/teleport/lib/client.(*ClientProfile).SaveTo
        /gopath/src/github.com/gravitational/teleport/lib/client/api.go:645 github.com/gravitational/teleport/lib/client.(*Config).SaveProfile
        /gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:511 main.onLogin
        /gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:351 main.Run
        /gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:188 main.main
        /opt/go/src/runtime/proc.go:212 runtime.main
        /opt/go/src/runtime/asm_amd64.s:1358 runtime.goexit
User Message:
```

### PR DESCRIPTION
**Pull request by fspmarshall**
Changes how `tsh` tracks the currently active profile.  Previously, the currently active profile was tracked via a symlink at `~/.tsh/profile` which linked directly to the file.  Now, `tsh` stores the name of the currently active profile in a regular text file at `~/.tsh/current-profile`.

Fixes #4095 

(bug was reproduced and fix was verified on Windows Server 2019)

### CODE REVIEW

**Comment by benarent** [comment]
@fspmarshall if you can easily make a binary I can try it on my system.

**Comment by benarent** [comment]
I tested the binary this morning. I noticed that It wasn't working as I had installed my binary to Windows and my user was picking this file.

```
PS C:\Users\benar\.tsh> (get-command tsh).Path
C:\Windows\system32\tsh.exe
```

I ran across https://github.com/gravitational/teleport/issues/3012 again, and this would be good to go out with this release for locked down windows environments.

**Comment by benarent** [comment]
Just to clarify, this did work on my machine. I was picked an earlier version to start.

File: lib/client/profile.go [hunk 1]
```diff
@@ -85,71 +162,61 @@ func FullProfilePath(pDir string) string {
 		home = u.HomeDir
 	}
 	return filepath.Join(home, ProfileDir)
-
 }
 
 // ProfileFromDir reads the user (yaml) profile from a given directory. The
 // default is to use the ~/<dir-path>/profile symlink unless another profile
 // is explicitly asked for. It works by looking for a "profile" symlink in
 // that directory pointing to the profile's YAML file first.
```
Comment (awly) [inline lib/client/profile.go:170]: nit: update the comment

**Review by awly — APPROVED** [review]

File: lib/client/profile.go [hunk 2]
```diff
@@ -74,6 +74,17 @@ func (c *ClientProfile) Name() string {
 // DELETE IN: 6.0
 func migrateCurrentProfile(dir string) {
 	link := filepath.Join(dir, CurrentProfileSymlink)
+	linfo, err := os.Lstat(link)
+	if err != nil {
+		return
+	}
+	if finfo, err := os.Stat(filepath.Join(dir, CurrentProfileFilename)); err == nil {
+		if !linfo.ModTime().After(finfo.ModTime()) {
```
Comment (awly) [inline lib/client/profile.go:82]:
```suggestion
		if linfo.ModTime().Before(finfo.ModTime()) {
```

File: lib/client/profile.go [hunk 3]
```diff
@@ -85,14 +96,35 @@ func migrateCurrentProfile(dir string) {
 	if err := SetCurrentProfileName(dir, name); err != nil {
 		return
 	}
-	os.Remove(link)
+
+	// TODO(fspmarshall): Re-enable removal once we've confirmed
+	// that nothing else relies on `link` (note: this should be
+	// done at least one minor version prior to removing migration).
```
Comment (awly) [inline lib/client/profile.go:102]: nit: specify the target release to do this

**Review by awly — APPROVED** [review]

**Comment by russjones** [comment]
What do you think about the following: we continue to write the symlink as well as the new file that has the profile in it. We create a new package specific file to read in the current profile, for example:

```
symlink_windows.go
symlink_unix.go
```

Then macOS/Linux can continue to use the symlink and Windows can use the new format.

@awly @fspmarshall The main thing that worries me here is regressions in macOS/Linux tsh clients. People upgrade `tsh` through things like Homebrew which means this change can have a large negative impact. I know creating platform specific files will increase code duplication, but that's a trade off I feel is worth taking for increased stability.

What do you guys think?

**Comment by awly** [comment]
@russjones I think having different profile structure on different platforms will cause problems for Windows users down the line.
We will make changes with the assumption of symlinks and test them on Linux/Mac, but forget about the special Windows behavior.

Any regressions are likely to happen in the migration code (since we'll exercise the new profile structure regularly). Worst case, the user can delete `~/.tsh` to fix a botched migration.

My vote is for keeping this PR as is.

**Comment by fspmarshall** [comment]
I agree with @awly.  Platform-dependent systems seem likely to create more problems than they solve.

**Comment by webvictim** [comment]
+1 from me for having consistent behaviour across all platforms too.

I agree that the mitigation of deleting the `~/.tsh` directory is acceptable. Maybe we could add some detail to the error output to advise users to do that if they're experiencing problems?
