### PR TITLE
scp compatibility with open ssh server 

### LINKED ISSUE #1048: scp with OpenSSH client
To reproduce:
```
$ scp host:/home/dir/* .
unexpected /home/dir/greplog
```

Happens when:

```
openssh client -> teleport proxy -> teleport sshd
```

This works as expected:
```
openssh client -> teleport proxy -> opens sshd
```
adding `-r` flag does not help

### PR DESCRIPTION
**Pull request by kontsevoy**
**Purpose**

This PR make several changes to increase interoperability with OpenSSH `scp` and fix bugs.

* We let bash expand `*` for us.
* Mitigate double error message.
* Added `-d` flag.
* Files no longer contain Teleport log data.

**Implementation**

* Logging is sent to `syslog` because Teleport logs were being propagated to the client and were being included in the files being transferred.
* If an error occurs while `scp` is executing, only return an error if `scp` is running on the client. Otherwise use the `scp` protocol to return the error. This mitigates the double error messages issue that was occurring.
* Changed `Target` in `scp` from a string to a slice of strings.
* Added `-d` flag because OpenSSH sends it sometimes but it's a NOP.
* We are no longer escaping shell variables because bash needs to expand `*`. This also brings us in-line with OpenSSH.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1048

### CODE REVIEW

**Comment by kontsevoy** [comment]
retest this please

File: tool/teleport/common/teleport.go [hunk 1]
```diff
@@ -242,24 +243,27 @@ func onConfigDump() {
 //
 // This is the entry point of "teleport scp" call (the parent process is the teleport daemon)
 func onSCP(cmd *scp.Command) (err error) {
+	// when 'teleport scp' is executed, it cannot write logs to stderr (because
+	// they're automatically replayed by the scp client)
+	utils.SwitchLoggingtoSyslog()
```
Comment (russjones) [inline tool/teleport/common/teleport.go]: Do the logs get switched back after this command has finished executing?

**Comment by kontsevoy** [comment]
@russjones added minor changes per our hangout review

**Review by russjones — APPROVED** [review]
