### PR TITLE
cluster specific ssh-agent keys

### LINKED ISSUE #11678: tsh with ssh-agent and openssh does not work for multiple clusters with same username
### Description

`tsh` loads keys into the ssh-agent with an identifier which includes the username but not the cluster name. When connecting to two clusters with the same username, the second `tsh login` mistakenly deletes the Agent keys for the first, as they use the same identifier.

This is most apparent when using openssh to connect; the connection to the other cluster will fail (whichever one is not loaded into the agent). When using `tsh ssh` it is less obvious as the `tsh` app is continually replacing the keys for the other cluster.

### Reproduction Steps
Log in to first cluster:
`tsh login --login=oliver --proxy=cluster-a.ecample.com`
Show keys:
`ssh-add -l`
Log in to second cluster using same username:
`tsh login --login=oliver --proxy=cluster-b.ecample.com`
Show keys:
`ssh-add -l`

The identifier (comment) looks like "teleport:USERNAME" and you can verify this using `ssh-add -l`.

### Client Details
- `tsh` 9.0.1
- Computer OS macOS 12.2.1
- Browser version: n/a
- Installed via: brew
- Additional details: we are an enterprise customer and are experiencing the issue.

### Workaround
One option is to run an `ssh-agent` in different shell processes. Not very user friendly.

Another option is to not use the SSH Agent at all, and add ssh client config to point at the SSH key files. However some security sensitive installations do not create the local key files.

### Code references
The identifier is called the "comment" and is set here, using the SSH Key ID which defaults to username:
https://github.com/gravitational/teleport/blob/e1c3f80aa0e6dc724f7e27802bf5559c82e18228/api/utils/sshutils/ssh.go#L155

The code which then mistakenly removes the other cluster keys for the user, is here:
https://github.com/gravitational/teleport/blob/550d23d15d3b88f4d03380877e2b64b6ee8ac484/lib/client/keyagent.go#L243

And I think this code is used to log out of a cluster, but actually blows away all clusters' keys:
https://github.com/gravitational/teleport/blob/550d23d15d3b88f4d03380877e2b64b6ee8ac484/lib/client/keyagent.go#L273

And throughout `tsh` codebase the "teleport:USERNAME" convention is used.

### Possible solution
 Suggestion is to add the cluster name into this identifier ("comment"), for example "teleport:CLUSTERNAME:USERNAME".

### PR DESCRIPTION
**Pull request by Joerger**
This adds the cluster name of a certificate to it's corresponding agent keys, so that teleport users can have several teleport agent keys simultaneously loaded for different users and clusters, rather than only having the agent key for the active profile loaded.

Closes https://github.com/gravitational/teleport/issues/11678

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

**Review by jakule — APPROVED** [review]

**Comment by Joerger** [comment]
I've made a significant change, to use name agent keys as `teleport:proxy_host:user` instead of `teleport:cluster_name:user`.

This is important for trusted clusters, where it's common to use the root proxy to sign root and leaf certificates with a single private key, in `~/.tsh/keys/proxy.root.com`. Otherwise, a user's ssh-agent could be clogged up with multiple identical agent keys, labeled for different leaf clusters, while any one of them could be used to access both root and leaf cluster services.

**Comment by r0mant** [comment]
@Joerger @jakule If we don't include the cluster name in the key, doesn't it bring us back where we are now? How do we differentiate between the credentials you got with `tsh login clusterA` and `tsh login clusterB` for the same proxy?

**Comment by Joerger** [comment]
> @Joerger @jakule If we don't include the cluster name in the key, doesn't it bring us back where we are now? How do we differentiate between the credentials you got with `tsh login clusterA` and `tsh login clusterB` for the same proxy?
> 
> Maybe include both? `teleport:<proxy>:<cluster>:<user>`

Good point, this only works as is because both root and leaf cluster certs are accepted by root and leaf. I've updated with your suggestion:

```
2048 SHA256:jkHi0wJaVbLWP9ZFoSk1KajnsOnkdTuK9X9FzXa+sFE teleport:proxy.example.com:dev:root-cluster (RSA-CERT)
2048 SHA256:jkHi0wJaVbLWP9ZFoSk1KajnsOnkdTuK9X9FzXa+sFE teleport:proxy.example.com:dev:leaf-cluster (RSA-CERT)
2048 SHA256:jkHi0wJaVbLWP9ZFoSk1KajnsOnkdTuK9X9FzXa+sFE teleport:proxy.example.com:dev (RSA)
```

The lone key (RSA) uses just `teleport:proxy:user` because it's shared between the trusted clusters. Naming it with the cluster would result in it being overwritten with the last cluster login, which might confuse users:

```
2048 SHA256:jkHi0wJaVbLWP9ZFoSk1KajnsOnkdTuK9X9FzXa+sFE teleport:proxy.example.com:dev:root-cluster (RSA-CERT)
2048 SHA256:jkHi0wJaVbLWP9ZFoSk1KajnsOnkdTuK9X9FzXa+sFE teleport:proxy.example.com:dev:leaf-cluster (RSA-CERT)
2048 SHA256:jkHi0wJaVbLWP9ZFoSk1KajnsOnkdTuK9X9FzXa+sFE teleport:proxy.example.com:dev:leaf-cluster (RSA)
```

File: api/constants/constants.go [hunk 1]
```diff
@@ -273,3 +273,9 @@ const (
 	// allowed AWS role ARNs.
 	TraitAWSRoleARNs = "aws_role_arns"
 )
+
+const (
+	// CertExtensionTeleportRouteToCluster is used to encode
+	// the target cluster to route to in the certificate
+	CertExtensionTeleportRouteToCluster = "teleport-route-to-cluster"
```
Comment (r0mant) [inline api/constants/constants.go:280]: Is this change related to this PR?

File: lib/client/interfaces.go [hunk 2]
```diff
@@ -384,14 +386,80 @@ func (k *Key) CertRoles() ([]string, error) {
...
+)
+
+// teleportAgentKeyName returns a teleport agent key name like "teleport:<proxyHost>:<userName>".
+// This name should be used/seen in the comment section of Teleport agent keys, as the prefix for
+// Teleport agent cert keys.
+func teleportAgentKeyName(k KeyIndex) string {
+	return strings.Join([]string{agentCommentPrefix, k.ProxyHost, k.Username}, agentCommentSeparator)
+}
+
+// teleportAgentKeyCertName returns a teleport agent key cert name like "teleport:<proxyHost>:<userName>:<clusterName>".
```
Comment (r0mant) [inline lib/client/interfaces.go:401]: Nit: This may be my OCD speaking but can we make it `teleport:proxy:cluster:user` instead? :) To keep proper "hierarchy".

File: lib/client/interfaces.go [hunk 3]
```diff
@@ -384,14 +386,80 @@ func (k *Key) CertRoles() ([]string, error) {
...
+// This name should be used/seen in the comment section of Teleport agent cert keys.
+func teleportAgentKeyCertName(k KeyIndex) string {
+	return strings.Join([]string{teleportAgentKeyName(k), k.ClusterName}, agentCommentSeparator)
+}
+
+// // teleportAgentKeyName returns an teleport agent key name like "teleport:<proxyHost>:<clusterName>:<userName>".
+// // This name should be used/seen in the comment section of Teleport agent keys.
+// func teleportAgentKeyName(k KeyIndex) string {
+// 	return strings.Join([]string{agentCommentPrefix, k.ProxyHost, k.ClusterName, k.Username}, agentCommentSeparator)
+// }
```
Comment (r0mant) [inline lib/client/interfaces.go:411]: Delete this?

**Comment by Joerger** [comment]
@ryanclark @jakule @r0mant Can you re-review / re-approve when you get a chance?

File: lib/client/interfaces.go [hunk 4]
```diff
@@ -402,14 +415,69 @@ func (k *Key) CertRoles() ([]string, error) {
...
+
+	return KeyIndex{
+		ProxyHost:   parts[1],
+		ClusterName: parts[2],
+		Username:    parts[3],
+	}, true
+}
+
+// isTeleportAgentKey returns whether the given agent key was added
+// by teleport by checking the key's comment.
```
Comment (jakule) [inline lib/client/interfaces.go:450]: nit:
```suggestion
// by Teleport by checking the key's comment.
```

File: lib/client/keyagent.go [hunk 5]
```diff
@@ -250,47 +250,45 @@ func (a *LocalKeyAgent) LoadKey(key Key) error {
...
 	}
 
 	// iterate over all teleport and system agent and load key
+	var errs []error
 	for _, agent := range agents {
 		for _, agentKey := range agentKeys {
 			err = agent.Add(agentKey)
 			if err != nil {
-				a.log.Warnf("Unable to communicate with agent and add key: %v", err)
+				errs = append(errs, trace.Wrap(err, "Failed to add key to agent"))
```
Comment (jakule) [inline lib/client/keyagent.go:264]:
```suggestion
				errs = append(errs, trace.Wrap(err, "failed to add key to agent"))
```

File: lib/client/keyagent_test.go [hunk 6]
```diff
@@ -125,104 +120,123 @@ func TestAddKey(t *testing.T) {
...
+	}
 
-	// get all the keys in the teleport and system agent
-	teleportAgentKeys, err = lka.ExtendedAgent.List()
-	require.NoError(t, err)
-	systemAgentKeys, err = lka.sshAgent.List()
-	require.NoError(t, err)
+	// We should see two agent keys for each key added
+	agentsPerKey := 2
+	if runtime.GOOS == constants.WindowsOS {
```
Comment (jakule) [inline lib/client/keyagent_test.go:174]: Can you even run our tests on Windows? 😅

**Review by jakule — APPROVED** [review]

File: lib/client/keyagent_test.go (hunk 6 above)
Comment (Joerger) [reply lib/client/keyagent_test.go:174]: I'm not sure :grimacing: but I'll keep this here just in case / to clarify why we expect 2 agent keys per key.
