### PR TITLE
Add `btmp` support + fix user accounting IP address

### LINKED ISSUE #17243: wtmp updates broken on el8/el9
**Expected behavior:**

As per the previous issue https://github.com/gravitational/teleport/issues/3987 teleport should be properly writing to:
utmp -- current logins (working)
wtmp -- login history (not working)
btmp -- bad logins (not currently implemented but would be useful to see those in `lastb`)

`wtmp` updates fail on RHEL 8 & 9 today because `wtmp` is in `/var/log` and not `/var/run`, it appears this broke after https://github.com/gravitational/teleport/pull/10460.

If at all possible, can we please create the utmp/wtmp/btmp entries with hostname instead of just IP addresses?  Thanks!

**Current behavior:**

Teleport attempts to update `/var/run/wtmp` (which doesn't exist) which results in no `wtmp` updates.  This can be validated by symlink, auditd, or strace.

Bug details:
- Teleport version: v10.2.6
- Recreation steps: login+logout on rhel8/rhel9 and check `last`
- Debug logs: N/A

### PR DESCRIPTION
**Pull request by atburke**
This PR extends user accounting by adding support for the `btmp` file. When a user attempts to SSH into a node with a login that doesn't exist on the node and user accounting is supported, Teleport will log the attempt in `btmp` just as it would log a successful login in `wtmp`.

This PR also fixes a bug where the remote address of a connection was not being correctly logged.

Resolves #17243.

### CODE REVIEW

File: lib/srv/reexec.go [hunk 1]
```diff
@@ -275,6 +278,13 @@ func RunCommand() (errw io.Writer, code int, err error) {
 	var pty *os.File
 	uaccEnabled := false
 
+	localUser, err := user.Lookup(c.Login)
+	if err != nil {
+		// Ignore error since there's no way to log it.
+		_ = uacc.LogFailedLogin(c.UaccMetadata.BtmpPath, c.Login, c.UaccMetadata.Hostname, c.UaccMetadata.RemoteAddr)
```
Comment (Tener) [inline lib/srv/reexec.go:284]: Why can't we log it? There are logging calls above, e.g.: `log.WithError(err).Debugf("failed to send UserEnd event to auditd: %v", err)`

File: lib/srv/uacc/uacc_linux.go [hunk 2]
```diff
@@ -234,6 +244,61 @@ func UserWithPtyInDatabase(utmpPath string, username string) error {
...
+	defer C.free(unsafe.Pointer(cBtmpPath))
+	cUsername := C.CString(username)
+	defer C.free(unsafe.Pointer(cUsername))
+	cHostname := C.CString(hostname)
+	defer C.free(unsafe.Pointer(cHostname))
+
+	// Convert IPv6 array into C integer format.
+	cIP := [4]C.int{0, 0, 0, 0}
+	for i := 0; i < 4; i++ {
+		cIP[i] = (C.int)(remote[i])
```
Comment (Tener) [inline lib/srv/uacc/uacc_linux.go:275]: In C the parameter is `const int32_t remote_addr_v6[4]`, so I think we should use `C.int32_t` here.
```suggestion
		cIP[i] = (C.int32_t)(remote[i])
```

Seeing as the original code in `Open` has the same issue, it might be beneficial to refactor this code to use shared helper functions.

File: lib/srv/uacc/uacc_linux.go [hunk 3]
```diff
@@ -234,6 +244,61 @@ func UserWithPtyInDatabase(utmpPath string, username string) error {
...
+	case C.UACC_UTMP_FAILED_OPEN:
+		return trace.AccessDenied("failed to open user account database, code: %d", errno)
+	case C.UACC_UTMP_FAILED_TO_SELECT_FILE:
+		return trace.BadParameter("failed to select file")
+	case C.UACC_UTMP_PATH_DOES_NOT_EXIST:
+		return trace.NotFound("user accounting files are missing from the system, running in a container?")
+	default:
+		return decodeUnknownError(int(status))
+	}
+}
```
Comment (Tener) [inline lib/srv/uacc/uacc_linux.go:300]: Will any of this materialize due to the final call in the `C.uacc_add_btmp_entry` function?

```c
    updwtmp(file, &entry);
    return 0;
```

In `uacc_add_btmp_entry`, we expect the caller to check `errno`, but in Go `LogFailedLogin` expects non-zero status in case of errors. Both sides of the call effectively expect the other to do the job.

**Comment by Tener** [comment]
We should also add `LogFailedLogin` to `uacc_stub.go`.

**Comment by Tener** [comment]
Should we backport the fix to v13, v12 and (possibly) v11 too?

File: integration/utmp_integration_test.go [hunk 4]
```diff
@@ -72,51 +75,110 @@ func TestRootUTMPEntryExists(t *testing.T) {
...
-	require.NoError(t, se.RequestPty("xterm", 80, 80, modes), nil)
-	err = se.Shell()
-	require.NoError(t, err)
+		require.NoError(t, se.RequestPty("xterm", 80, 80, modes), nil)
+		err = se.Shell()
+		require.NoError(t, err)
+
+		start := time.Now()
+		for time.Since(start) < 5*time.Minute {
+			time.Sleep(time.Second)
```
Comment (zmb3) [inline integration/utmp_integration_test.go:117]: Isn't this basically what `require.EventuallyWithT` does?

File: lib/srv/uacc/uacc.h [hunk 5]
```diff
@@ -235,4 +235,37 @@ static int uacc_has_entry_with_user(const char *utmp_path, const char *user) {
     return errno == 0 ? UACC_UTMP_ENTRY_DOES_NOT_EXIST : errno;
 }
 
+// Low level C function to add a new entry to the failed login log.
+// This function does not perform any argument validation.
```
Comment (zmb3) [inline lib/srv/uacc/uacc.h:239]: What does `This function does not perform any argument validation.` mean?

Validation is critical in C code. And I see you validating `btmp_path` below.

File: lib/srv/uacc/uacc.h [hunk 6]
```diff
@@ -235,4 +235,37 @@ static int uacc_has_entry_with_user(const char *utmp_path, const char *user) {
...
+static int uacc_add_btmp_entry(const char *btmp_path, const char *username,
+  const char *hostname, const int32_t remote_addr_v6[4],
+  int32_t tv_sec, int32_t tv_usec) {
+
+    if (btmp_path == NULL) {
+      // Return open failed error if the provided path is NULL.
+      return UACC_UTMP_FAILED_OPEN;
+    }
+
+    UACC_PATH_ERR = NULL;
```
Comment (zmb3) [inline lib/srv/uacc/uacc.h:249]: Should we rename this global var? SCREAMING_SNAKE_CASE is generally meant to mean "this is a constant"

File: lib/srv/uacc/uacc.h [hunk 7]
```diff
@@ -235,4 +235,37 @@ static int uacc_has_entry_with_user(const char *utmp_path, const char *user) {
...
+    char resolved_btmp_buffer[PATH_MAX];
+    const char* file = realpath(btmp_path, &resolved_btmp_buffer[0]);
```
Comment (zmb3) [inline lib/srv/uacc/uacc.h:251]: Alternatively, you can pass a null pointer to realpath and it will allocate a large enough buffer for you. Not sure if I like that idea though, as then you have to remember to free it.

File: lib/srv/uacc/uacc_linux.go (hunk 2 above)
Comment (zmb3) [reply lib/srv/uacc/uacc_linux.go:275]: Came to ask the same thing. You're memcpying `4 * sizeof(int32_t)`, but on 64-bit platforms this array is probably twice as big.

Also, arrays are zero-valued by default in Go. `cIP := [4]C.int{0, 0, 0, 0}` is equivalent to `var cIP [4]C.int`.

File: lib/srv/mock.go [hunk 8]
```diff
@@ -264,8 +264,8 @@ func (m *mockServer) Context() context.Context {
 }
 
 // GetUtmpPath returns the path of the user accounting database and log. Returns empty for system defaults.
-func (m *mockServer) GetUtmpPath() (utmp, wtmp string) {
-	return "test", "test"
+func (m *mockServer) GetUtmpPath() (utmp, wtmp, btmp string) {
+	return "test", "test", "test"
```
[the remark this answers is not in the document]
Comment (atburke) [reply lib/srv/mock.go:268]: I don't think it matters in this case, the function is just here to satisfy an interface and won't actually be called.

File: lib/srv/uacc/uacc_linux.go (hunk 3 above)
Comment (atburke) [reply lib/srv/uacc/uacc_linux.go:289]: `check_abs_path_err` can generate these statuses, and it's called in `uacc_add_btmp_entry`.

File: lib/srv/uacc/uacc.h (hunk 5 above)
Comment (atburke) [reply lib/srv/uacc/uacc.h:239]: I'm not actually sure, it's just how the other C functions are in this file. In practice everything should be validated on the Go side, but we can add validation here too if you want.

File: lib/srv/uacc/uacc_linux.go (hunk 3 above)
Comment (Tener) [reply lib/srv/uacc/uacc_linux.go:289]: True, but later on we call `updwtmp` which may report error using `errno`. We should check it after the call, either in C or in Go. For consistency I think we should do it in C, similar to the code in `check_abs_path_err`.

File: lib/srv/uacc/uacc.h [hunk 9]
```diff
@@ -235,4 +235,37 @@ static int uacc_has_entry_with_user(const char *utmp_path, const char *user) {
...
+        .ut_type = USER_PROCESS,
+        .ut_tv.tv_sec = tv_sec,
+        .ut_tv.tv_usec = tv_usec
+    };
+    strncpy((char*) &entry.ut_host, hostname, sizeof(entry.ut_host));
+    strncpy((char*) &entry.ut_user, username, sizeof(entry.ut_user));
+    memcpy(&entry.ut_addr_v6, remote_addr_v6, sizeof(int32_t) * 4);
+
+    updwtmp(file, &entry);
+    return 0;
```
Comment (Tener) [inline lib/srv/uacc/uacc.h:268]: I think we should check the `errno` values here.

**Comment by xacrimon** [comment]
I don't have much to add aside from existing comments but changing the function names away from the `createUtmp` style naming to be more descriptive of their broader scope is probably a good idea.

File: lib/srv/uacc/uacc.h [hunk 10]
```diff
@@ -65,12 +63,18 @@ static int check_abs_path_err(const char* buffer) {
...
+    if (buffer == NULL) {
+        return status_from_errno();
     }
 
     // check for GNU extension errors
     if (errno == EACCES || errno == ENOENT) {
-        UACC_PATH_ERR = (char*)malloc(PATH_MAX);
-        strcpy(UACC_PATH_ERR, buffer);
+        uaccPathErr = (char*)malloc(PATH_MAX);
+        strcpy(uaccPathErr, buffer);
```
Comment (Tener) [inline lib/srv/uacc/uacc.h:77]: Although very unlikely, `malloc` above can fail.

I know this was the original design, but the memory management of `uaccPathErr` makes me nervous. I have carefully reviewed how it is assigned and freed, and while I don't think there is an error _now_, I still wish we had used a simpler pattern.

Perhaps we can use a static buffer instead? This should be safe given that we lock `accountDb` anyway.

**Review by Tener — APPROVED** [review]

File: lib/srv/uacc/uacc.h (hunk 5 above)
Comment (xacrimon) [reply lib/srv/uacc/uacc.h:249]: Generally I decided to write as much logic in Go here for simplicity and have C just trust what Go passes in. Otherwise we end up with a lot more C code that could've been cleaner Go.

The only requirement is that we document what properties the arguments must uphold clearly.

File: lib/srv/uacc/uacc.h (hunk 7 above)
Comment (xacrimon) [reply lib/srv/uacc/uacc.h:261]: I think've we've always done it this way and hey, if we can save a malloc and a possible future leak that sounds rosy.

**Review by xacrimon — APPROVED** [review]

File: lib/srv/uacc/uacc.h (hunk 10 above)
Comment (xacrimon) [reply lib/srv/uacc/uacc.h:77]: Malloc in CGO will just abort on failure I'm pretty sure so this should be a non-concern.

Comment (xacrimon) [reply lib/srv/uacc/uacc.h:77]: Global/statics scare me and can go wrong fast. Could we also use the relatively simple pattern of passing in pointer to    an array on the stack from go?

**Comment by atburke** [comment]
> I don't have much to add aside from existing comments but changing the function names away from the `createUtmp` style naming to be more descriptive of their broader scope is probably a good idea.

@xacrimon Which functions are you referring to? The ones in `uacc.h`?

File: lib/srv/uacc/uacc_linux.go [hunk 11]
```diff
@@ -270,8 +275,8 @@ func LogFailedLogin(btmpPath, username, hostname string, remote [4]int32) error
 
 	accountDb.Lock()
 	defer accountDb.Unlock()
-
-	status, errno := C.uacc_add_btmp_entry(cBtmpPath, cUsername, cHostname, &cIP[0], secondsElapsed, microsFraction)
+	var uaccPathErr [uaccPathErrMaxLength]C.char
```
Comment (Tener) [inline lib/srv/uacc/uacc_linux.go:278]: Huh, interesting. I thought you'd have to use `C.malloc` here, but I guess this may work too...?

File: lib/srv/uacc/uacc.h [hunk 12]
```diff
@@ -39,7 +39,7 @@ int UACC_UTMP_PATH_DOES_NOT_EXIST = 8;
 // We use this string pointer to store a potential error message from glibc in certain cases.
 //
 // At first glance this may seem racy, however this pointer is protected by the mutex that wraps all uacc logic on the Go side.
-char* uaccPathErr;
+// char* uaccPathErr;
```
Comment (Tener) [inline lib/srv/uacc/uacc.h:42]: I think we should remove this commented-out global along with the comment above it.

**Review by Tener — APPROVED** [review]

File: lib/srv/uacc/uacc_linux.go (hunk 11 above)
Comment (xacrimon) [reply lib/srv/uacc/uacc_linux.go:278]: it will because that memory is going to be part of the heap allocation that makes up the stack for the goroutine which is bound to the CGO call anyway.

**Review by xacrimon — APPROVED** [review]

**Review by probakowski — APPROVED** [review]
