### PR TITLE
Show application session recordings in `tsh recordings ls` and WebUI

### LINKED ISSUE #53797: Extend `tsh recordings ls` so it shows app session recordings
What would you like Teleport to do?
Currently, using `tsh recordings ls` will not return any app sessions even though they can be replayed with `tsh play` if an app session is found in the audit log.

What problem does this solve?
Fills in a gap in UX of `tsh recordings ls`. Users will now be able to list app recordings which should be listed here.

If a workaround exists, please include it.
Search the audit log for session recordings.

Note: A Hint from @zmb3 on why we don't list app recordings:
https://github.com/gravitational/teleport/blob/v17.4.2/lib/events/api.go#L895-L901

### LINKED ISSUE #61945: copy button for session id not working for non-interactive sessions
Expected behavior:

The session id copy button will work for non-interactive and interactive.

Current behavior:

The copy session id button is disabled for non-interactive sessions. The Click to copy text won't appear and the button doesn't work.

Image

Bug details:
- Teleport version: 18.4.2
- Recreation steps

1. Create a interactive and non-interactive ssh sessions
2. Attempt to hit the copy button for the non-interactive sessions in the recorded sessions page.

### PR DESCRIPTION
**Pull request by tangyatsu**
# What 
Resolves #53797
Resolves #61945

These changes add application session recordings to the recordings list. The `tsh recordings ls` command and the Web UI now show recordings for `app.session.chunk`events alongside other session recordings.

This also fixes an issue where the copy button for the session id did not work
on non-interactive sessions.

changelog: Added support for listing application session recordings in `tsh recording ls` and Web UI.
changelog: Fixed an issue where the copy button for the session id did not work for
non-interactive sessions.

# Manual Tests

A local test cluster was created with an Web application, SSH node, a PostgreSQL database and Minikube.

The following tests were performed:

* `tsh recordings ls` shows application recordings together with other session types:

```
ID                                   Type      Participants Target     Timestamp
------------------------------------ --------- ------------ ---------- ------------------------
60a45924-4df9-4081-a651-3b262d747451 app-chunk tangyatsu    hello-app Nov 27 2025 20:06:05 UTC
3a2ae696-0faf-496a-ac5b-62136bdf659c app-chunk tangyatsu    hello-app Nov 27 2025 21:23:05 UTC
ebc0b013-c27d-40bb-bdfa-e66786658723 kube      tangyatsu    minikube  Nov 27 2025 21:09:01 UTC
d9460090-bdda-4472-a419-3f99c0cb198d ssh       tangyatsu    local     Nov 27 2025 18:35:08 UTC
537216f3-6e7c-4c41-80cc-d40a885da5f6 postgres  tangyatsu    test      Nov 27 2025 18:06:35 UTC
```

* `tsh play <id> --format=json` correctly shows application request events using the IDs from the recordings list.

Example:

```json
{
  "ei": 1572531710000,
  "event": "app.session.request",
  "code": "T2009I",
  "time": "2025-11-26T21:23:41.532Z",
  "cluster_name": "teleport.dev",
  "status_code": 200,
  "path": "/example",
  "raw_query": "",
  "method": "GET",
  "app_uri": "http://localhost:8080",
  "app_public_addr": "hello-app.teleport.tangyatsu.com",
  "app_name": "hello-app"
}
```

* The Web UI displays application recordings with correct application name and chunk ID.  And you are able to copy session id with the copy button

### CODE REVIEW

File: lib/events/api.go [hunk 1]
```diff
@@ -1005,6 +1005,13 @@ var SessionRecordingEvents = []string{
 	SessionEndEvent,
 	WindowsDesktopSessionEndEvent,
 	DatabaseSessionEndEvent,
+
+	// HTTP/HTTPS application sessions do not emit AppSessionEndEvent.
+	// Their recordings ids are in AppSessionChunkEvent, so it is included.
```
Comment (zmb3) [inline lib/events/api.go]:
```suggestion
	// Their recording IDs are in AppSessionChunkEvent, so it is included.
```

File: tool/common/common.go [hunk 2]
```diff
@@ -86,8 +86,18 @@ func (e *SessionsCollection) WriteText(w io.Writer) error {
...
 			target = session.DatabaseName
 			timestamp = session.GetTime().Format(constants.HumanDateFormatSeconds)
+		case *events.AppSessionChunk:
+			id = session.GetSessionChunkID()
+			typ = "app-chunk"
+			participants = session.User
+			target = session.AppName
+			if target == "" {
+				target = session.AppURI
+			}
```
Comment (zmb3) [inline tool/common/common.go]:
```suggestion
			target = cmp.Or(session.AppName, session.AppURI)
```

File: web/packages/teleport/src/services/recordings/makeRecording.ts [hunk 3]
```diff
@@ -29,11 +29,35 @@ export function makeRecording(event: any): Recording {
...
+  const { time, user, session_chunk_id, app_name } = event;
+
+  return {
+    duration: 0,
+    durationText: '-',
+    sid: session_chunk_id,
+    createdDate: new Date(time),
+    users: user,
+    hostname: app_name,
+    description: 'non-interactive',
```
Comment (zmb3) [inline web/packages/teleport/src/services/recordings/makeRecording.ts]: Should we say something other than `non-interactive` here?

Maybe this?
```suggestion
    description: `HTTP access to app ${app_name}`,
```

**Review by zmb3 — APPROVED** [review]

**Review by avatus — APPROVED** [review]

File: web/packages/teleport/src/SessionRecordings/list/RecordingItem.tsx [hunk 4]
```diff
@@ -196,10 +203,9 @@ const RecordingItemContainer = styled(Link).withConfig({
     overflow: hidden; // Needed to keep the rectangular contents from bleeding out of the round corners.
     display: flex;
     flex-grow: 0;
-    cursor: pointer;
+    cursor: ${p.playable ? 'pointer' : 'default'};
```
Comment (avatus) [inline web/packages/teleport/src/SessionRecordings/list/RecordingItem.tsx:206]: lets use `not-allowed` instead of `default`

**Review by avatus — APPROVED** [review]
