### PR TITLE
Fix backend init event emission & dynamo shard iterator errors.

### LINKED ISSUE #6201: Errors after switching between "On-Demand" and "Provisioned" DynamoDB Capacity
### Description

**What happened**:
After switching between `on-demand` and `provisioned` mode on the dynamo db cluster state table, the following errors begin showing up periodically in both auth servers:

~~~
DEBU [DYNAMODB]  Shard ID  closed with error: ExpiredIteratorException: Shard iterator has expired, reseting buffers. dynamo/shards.go:115
ERRO [DYNAMODB]  Poll streams returned with error: ExpiredIteratorException: Shard iterator has expired. dynamo/shards.go:61
~~~

No noted functionality issues with the cluster except the error logging.

**What you expected to happen**:
Switching between capacity modes in DynamoDB backend for cluster state will not cause errors.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create a Teleport cluster using a DynamoDB backend with the HA terraform example.  I also added a single node and some trusted cluster relationships to generate some activity.
2. In the AWS console, go to the cluster state table and change the mode from 'Provisioned' to 'On-demand' and back again with the same values under the 'Capacity' tab
3. Observe the logs of the auth server (the messages should start occurring periodically every ~15-20 minutes)

### Server Details
- Teleport version (run `teleport version`): Teleport Enterprise v5.1.2
- Server OS (e.g. from `/etc/os-release`): AWS Linux
- Where are you running Teleport? AWS

### LINKED ISSUE #7486: Stale node TTL with in-memory cache
### Description

After the proxy/auth cluster has been booted for a little while, stale nodes are reported when you run `tsh ls`. These nodes do not show up in dynamo, which leads us to believe it's an in-memory cache cleanup issue. When we deploy new auth/proxy clusters (for example, when we bump versions), the stale nodes go away.

**What happened**:
nodes aren't properly TTL'ed

**What you expected to happen**:
old nodes that have been recycled (as part of ASGs) should not show up when we run a `tsh ls`

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. boot proxy/auth cluster
2. boot ~8-10k teleport nodes
3. continually deploy those 8-10k nodes and observe the issue

### Server Details
- 6.1.5 (and all prior versions)
- ubuntu 18.0.4
- AWS
- single cluster in iot mode

### Client Details
- n/a

### Debug Logs

```
Jul 06 15:23:50 ip-10-66-145-96 /usr/local/bin/teleport[1029]: ERRO [DYNAMODB]  Poll streams returned with error: ExpiredIteratorException: Shard iterator has expired. dynamo/shards.go:59
```

[More info in a private slack thread](https://gravitational.slack.com/archives/CAHQS4HB5/p1625583894045700)

CC @fspmarshall

### PR DESCRIPTION
**Pull request by fspmarshall**
Fixes #6201 by correctly updating shard iterators.

Fixes #7486, which turned out to be an instance of a broader problem with how all backends handled event emission.  Backends were not correctly signaling broken event streams, and were emitting `OpInit` events while their event streams were unhealthy, both of which are violations of the contract relied upon by the caching system.

*edit*: Also fixed an issue where dynamo events may arrive out of order due to child shards getting polled before their parent shards were exhausted.

### CODE REVIEW

File: lib/backend/buffer.go [hunk 1]
```diff
@@ -36,16 +36,17 @@ import (
...
-	end      int
-	size     int
-	watchers *watcherTree
+	ctx          context.Context
+	cancel       context.CancelFunc
+	events       []Event
+	start        int
+	end          int
+	size         int
+	init, closed bool
```
Comment (andrejtokarcik) [inline lib/backend/buffer.go:45]: Is `closed` necessary? Wouldn't it suffice to check `ctx.Err()`?

File: lib/backend/dynamo/shards.go [hunk 2]
```diff
@@ -83,26 +83,70 @@ func (b *Backend) pollStreams(externalCtx context.Context) error {
...
+		if init {
+			// block on shard iterator registration.
+			for i := 0; i < started; i++ {
+				select {
+				case err = <-initC:
+					if err != nil {
+						return false, trace.Wrap(err)
+					}
+				case <-ctx.Done():
+					return true, nil
```
Comment (andrejtokarcik) [inline lib/backend/dynamo/shards.go:134]: The return type of `refreshShards` should perhaps be just `error`, with `ctx.Err()` being returned here instead of `true, nil`. As it stands, when the `closing` condition is encountered below this cancellation info is simply discarded.

**Review by andrejtokarcik — APPROVED** [review]

File: lib/backend/buffer.go [hunk 3]
```diff
@@ -84,10 +100,39 @@ func (c *CircularBuffer) Reset() {
 	}
 }
 
+func (c *CircularBuffer) SetInit() {
```
Comment (r0mant) [inline lib/backend/buffer.go:103]: Nit: Missing godoc.

File: lib/backend/buffer.go [hunk 4]
```diff
@@ -84,10 +100,39 @@ func (c *CircularBuffer) Reset() {
...
+	}
+
+	var watchersToDelete []*BufferWatcher
+	c.watchers.walk(func(watcher *BufferWatcher) {
+		if ok := watcher.init(); !ok {
+			watchersToDelete = append(watchersToDelete, watcher)
+		}
+	})
+
+	for _, watcher := range watchersToDelete {
```
Comment (r0mant) [inline lib/backend/buffer.go:117]: I don't have too much context about how this is being used, but is it intended behavior to set `init` flag to true even if some watchers failed to initialize?

File: lib/backend/buffer.go [hunk 5]
```diff
@@ -66,11 +67,26 @@ func NewCircularBuffer(ctx context.Context, size int) (*CircularBuffer, error) {
...
-// and closes all active watchers
+// Clear clears all events from the queue and closes all active watchers,
+// but does not modify init state.
+func (c *CircularBuffer) Clear() {
+	c.Lock()
+	defer c.Unlock()
+	c.clear()
+}
+
+// Reset is equivlant to Clear except that is also sets the buffer into
```
Comment (r0mant) [inline lib/backend/buffer.go:78]: equivalent

File: lib/backend/buffer.go [hunk 6]
```diff
@@ -119,24 +164,27 @@ func (c *CircularBuffer) eventsCopy() []Event {
...
-	defer c.Unlock()
-	c.push(r)
+	for i := range events {
+		c.emit(events[i])
+	}
+	return true
 }
 
-func (c *CircularBuffer) push(r Event) {
+func (c *CircularBuffer) emit(r Event) {
```
Comment (r0mant) [inline lib/backend/buffer.go:184]: Nit: I'd rename to `emitLocked` to indicate that this is called under lock.

File: lib/backend/dynamo/shards.go [hunk 7]
```diff
@@ -83,26 +83,70 @@ func (b *Backend) pollStreams(externalCtx context.Context) error {
...
 
-	refreshShards := func() error {
+	shouldStartPoll := func(shard *dynamodbstreams.Shard) bool {
+		sid := aws.StringValue(shard.ShardId)
+		if _, ok := set[sid]; ok {
+			// already being polled
+			return false
+		}
+		if _, ok := set[aws.StringValue(shard.ParentShardId)]; ok {
+			b.Warnf("Skipping child shard: %s, still polling parent %s", sid, aws.StringValue(shard.ParentShardId))
```
Comment (r0mant) [inline lib/backend/dynamo/shards.go:93]: Nit: Can this be Debug or do you need this as a warning?

File: lib/backend/dynamo/shards.go [hunk 8]
```diff
@@ -83,26 +83,70 @@ func (b *Backend) pollStreams(externalCtx context.Context) error {
...
+			// still processing parent
+			return false
+		}
+		return true
+	}
+
+	refreshShards := func(init bool) (bool, error) {
```
Comment (r0mant) [inline lib/backend/dynamo/shards.go:100]: Nit: Could you explain either with a comment or named return args what the bool return argument indicates?

**Review by r0mant — APPROVED** [review]

File: lib/backend/buffer.go (hunk 1 above)
Comment (fspmarshall) [reply lib/backend/buffer.go:45]: `closed` is necessary because the parent context might be canceled while the buffer lock is held, so using the context as the indicator of the closed state might cause inconsistent/racy behavior.

In thinking about your comment though, I've realized that the buffer doesn't really need to embed a context now that we're using `closed`, so I'm going to factor out the context.

File: lib/backend/dynamo/shards.go (hunk 2 above)
Comment (fspmarshall) [reply lib/backend/dynamo/shards.go:134]: Good point.  The `closing` bool used to be used to suppress spurious logs during an earlier iteration of this code.  Since then I changed to checking `isClosed()` directly before emitting the error log, so it isn't needed anymore.

File: lib/backend/buffer.go (hunk 4 above)
Comment (fspmarshall) [reply lib/backend/buffer.go:117]: Yes.  The purpose of the init state is to record the fact that the parent event stream (i.e. the event stream from the real backend) has been successfully established.  If an individual watcher can't receive its init event, that just means the individual watcher is unhealthy, and doesn't have any bearing on the overall init state of the buffer and its parent stream.

File: lib/backend/dynamo/shards.go (hunk 8 above)
Comment (fspmarshall) [reply lib/backend/dynamo/shards.go]: Bool flag has been removed.  It wasn't really necessary anymore.
