### PR TITLE
[buddy] Error if TTL in `tctl auth sign` is too long

### LINKED ISSUE #15329: tctl should have a WARN log level by default
https://github.com/gravitational/teleport/pull/9265 - this was merged last December, but the message is silenced unless tctl is in debug mode even though the message is logged at the WARN level.

For the message to successfully warn the user that something unexpected to happen, it should be printed by default rather than only during situations where debug is set.

current:

```
tctl auth sign --user=terraform --out=auth.pem --ttl 17520h

The credentials have been written to auth.pem
```

expected:

```
tctl auth sign --user=terraform --out=auth.pem --ttl 17520h

The credentials have been written to auth.pem
            WARN Requested TTL of 17520h0m0s was not granted. User may have a role with a shorter max session TTL or an existing session ending before the requested TTL. Proceeding with 29h59m59s common/auth_command.go:748
```

### PR DESCRIPTION
**Pull request by vitorenesduarte**
Fixes #15329.
Buddy PR for #15384.

As recommended [here](https://github.com/gravitational/teleport/pull/15384#issuecomment-1216009724), in case the TTL requested in `tctl auth sign` is too long, `tctl` should:
- return an error, and
- not issue a credential.

To achieve the second, the TTL validation was moved up, just before the credential is written to the output file.

### CODE REVIEW

File: tool/tctl/common/auth_command.go [hunk 1]
```diff
@@ -671,6 +671,19 @@ func (a *AuthCommand) generateUserKeys(ctx context.Context, clusterAPI auth.Clie
...
 
+	expires, err := key.TeleportTLSCertValidBefore()
+	if err != nil {
+		log.WithError(err).Warn("Failed to check TTL validity")
+		// err swallowed on purpose
+		return nil
+	}
+	if reqExpiry.Sub(expires) > time.Minute {
+		maxAllowedTTL := time.Until(expires).Round(time.Second)
+		return trace.Errorf(`The credential was not issued because the requested TTL of %s exceeded the maximum allowable value of %s. To successfully request a credential, please reduce the requested TTL.`,
```
Comment (codingllama) [inline tool/tctl/common/auth_command.go:682]: nit: I've been told to avoid naked trace.Errorf.

```suggestion
		return trace.BadParameter(`The credential was not issued because the requested TTL of %s exceeded the maximum allowed value of %s. To successfully request a credential, please reduce the requested TTL.`,
```

**Review by codingllama — APPROVED** [review]

**Review by ravicious — APPROVED** [review]
