### PR TITLE
Fix overflow issues for username and cluster name in profile switcher

### LINKED ISSUE #48881: Connect doesn't show logout button if username + cluster name combo is too long
Most of the time, the identity picker looks like this:

regular identity picker

But if the username + cluster name combo is too long, the logout button disappears:

identity picker with a long username + cluster name combo

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/48881

To fix the username and cluster name overflowing the popover, I added a `width: 100%` on the container. I'm not sure when exactly it broke, I didn't find anything interesting in the file history.

However, it's not the only problem, recently I added showing a profile error in the item. It can go outside of the container as well when it's too long. I fixed it by setting `min-width:0` on the flex container so that it can shrink (it's an old trick that prevents children from overflowing the flex parent).

### CODE REVIEW

File: web/packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
Comment (ravicious) [inline web/packages/teleterm/src/ui/TopBar/Identity/Identity.tsx:1]: I bisected this and it appears that it was broken by #46835. From a quick look it's hard to tell which change in Popover caused this, the styles appear to be pretty much the same.

**Review by ravicious — APPROVED** [review]

File: web/packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
Comment (ravicious) [reply web/packages/teleterm/src/ui/TopBar/Identity/Identity.tsx:1]: Which also means we probably don't need to backport this to v15 and it doesn't look like #46835 ended up being backported to v16, is that right @bl-nero? So this PR can probably go just into v17.

File: web/packages/teleterm/src/ui/TopBar/Identity/Identity.story.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default {
 
 const makeTitle = (userWithClusterName: string) => userWithClusterName;
 const profileStatusError =
-  'No YubiKey device connected with serial number 14358031';
+  'No YubiKey device connected with serial number 14358031. Connect the device and try again.';
```
Comment (bl-nero) [inline web/packages/teleterm/src/ui/TopBar/Identity/Identity.story.tsx:36]: This seems unrelated. Are you sure it should also be here?

File: web/packages/teleterm/src/ui/TopBar/Identity/Identity.tsx
Comment (bl-nero) [reply web/packages/teleterm/src/ui/TopBar/Identity/Identity.tsx:1]: That one didn't even get backported to v16, since it relied on another PR that @ravicious wanted to go through entire manual testing round.

**Review by bl-nero — APPROVED** [review]
Tested on my end, it works. Thank you!

File: web/packages/teleterm/src/ui/TopBar/Identity/Identity.story.tsx (hunk 1 above)
Comment (gzdunek) [reply web/packages/teleterm/src/ui/TopBar/Identity/Identity.story.tsx:36]: I made the text longer in the story to see what it looks like when it is longer than the container.
