### PR TITLE
Workload Identity: Kubernetes Attestor Bug Fixes

### LINKED ISSUE #54283: Workload Identity: Kubernetes attestor can't find container details
While testing the k8s attestor against a minikube cluster, I discovered that we're failing to attach the container name, image, and digest for two reasons:

1. We're comparing the hexadecimal ID from the container's cgroup path to the kubelet API's `containerID` field as-is, but kubelet returns this in the form: `<type>://<hex id>`.
2. There's a race condition where if the container calls the SPIFFE workload identity API too quickly (e.g. on start), the kubelet might return no container status or a previous run's status.

### PR DESCRIPTION
**Pull request by boxofrad**
Closes #54283.

Fixes two bugs in the Kubernetes attestor which prevented it from picking up container details:

1. We were comparing the hexadecimal ID from the container's cgroup path to the kubelet API's `containerID` field as-is, but kubelet returns this in the form: `<type>://<hex id>`.
2. There's a race condition where if the container calls the SPIFFE workload identity API too quickly (e.g. on start), the kubelet might return no container status or a previous run's status. We now retry for up to 30s.

changelog: Workload Identity: bug fixes for the Kubernetes workload attestor's container resolution

### CODE REVIEW

File: lib/tbot/workloadidentity/workloadattest/kubernetes_unix.go [hunk 1]
```diff
@@ -126,19 +128,80 @@ func (a *KubernetesAttestor) Attest(ctx context.Context, pid int) (*workloadiden
...
+	var (
+		pod             *v1.Pod
+		containerStatus *v1.ContainerStatus
+	)
+LOOP:
+	for {
+		pod, containerStatus, err = a.tryGetPodAndContainerStatus(ctx, podID, containerID)
+		switch {
+		case err != nil:
+			log.WarnContext(ctx, "Failed to get pod and container status from kubelet", "error", err)
```
Comment (boxofrad) [inline lib/tbot/workloadidentity/workloadattest/kubernetes_unix.go:155]: I'm not 100% sure about retrying on-error, because if we can't reach the attestor due to a misconfiguration we'll now block for 30s. It might be better to fail quickly.

WDYT?

Comment (strideynet) [reply lib/tbot/workloadidentity/workloadattest/kubernetes_unix.go:155]: Hm - I'd definitely also be cautious about hammering the kubelet API - I can imagine a scenario shortly after a node comes online and there may be many workloads requesting an identity at once.

I'm definitely leaning towards propagating the failure.

**Review by strideynet — APPROVED** [review]

**Review by timothyb89 — APPROVED** [review]
