### PR TITLE
Fix two issues with Oracle MySQL client on Windows

### LINKED ISSUE #20042: Windows tsh client connects to local host instead of proxy when trying to access MySQL
**Expected behavior:**
`tsh db connect` connects users to the MySQL DB. 

**Current behavior:**
Users receive the error message `ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)` when trying to connect to MySQL using the tsh Windows client. I expected tsh to try to connect to the DB at the proxy addr, not localhost, when not using multiplexing. 

**Workaround:**
Connect to the DB with an [authenticated tunnel ](https://goteleport.com/docs/connect-your-client/gui-clients/#get-connection-information)and the MySQL client.

**Bug details:**
- Teleport version
   tsh: 11.0.3 db-agent: 11.0.1 auth/proxy: 11.1.4
- Recreation steps
   On a windows client, attempt to connect to a database. The cluster should not use multiplexing and should have the `mysql_listen_addr` set
- Debug logs

No logs are generated in the db service or the auth/proxy service from the connection attempt.

Client logs:
```
>tsh db connect -d
←[36mINFO←[0m [CLIENT]    no host login given. defaulting to exampleuser client\api.go:1471
←[36mINFO←[0m [CLIENT]    [KEY AGENT] Connected to the system agent: "" client\api.go:4341
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-ssh\\examplecompany-teleport-cert.pub". client\keystore.go:346
←[36mINFO←[0m [KEYAGENT]  Loading SSH key for user "exampleuser@examplecompany.com" and cluster "examplecompany-teleport". client\keyagent.go:246
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-ssh\\examplecompany-teleport-cert.pub". client\keystore.go:346
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-db\\examplecompany-teleport". client\keystore.go:346
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-ssh\\examplecompany-teleport-cert.pub". client\keystore.go:346
←[37mDEBU←[0m [KEYSTORE]  Reading certificates from path "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-db\\examplecompany-teleport". client\keystore.go:346
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[36mINFO←[0m [CLIENT]    Connecting to proxy=tele.accessiq.examplecompany.com:3023 login="-teleport-nologin-f5348840-1c2e-4293-b9ad-7d5e1a676c20" client\api.go:3320
←[37mDEBU←[0m [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy\proxy.go:301
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [KEYAGENT]  "Checking key: ssh-rsa-cert-v01@openssh.com <omitted>" client\keyagent.go:418
←[37mDEBU←[0m [KEYAGENT]  Validated host tele.accessiq.examplecompany.com:3023. client\keyagent.go:424
←[36mINFO←[0m [CLIENT]    Successful auth with proxy tele.accessiq.examplecompany.com:3023. client\api.go:3329
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [CLIENT]    Client  is connecting to auth server on cluster "examplecompany-teleport". client\client.go:1404
←[37mDEBU←[0m [KEYSTORE]  Returning Teleport TLS certificate "C:\\Users\\exampleuser\\.tsh\\keys\\tele.accessiq.examplecompany.com\\exampleuser@examplecompany.com-x509.pem" valid until "2023-01-06 11:34:30 +0000 UTC". client\keystore.go:323
←[37mDEBU←[0m [TSH]       C:\ProgramData\chocolatey\bin\mysql.exe --defaults-group-suffix=_examplecompany-teleport-stg06-useast1-cis-d --user teleport_devops_ro tsh\db.go:762
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
ERROR REPORT:
Original Error: *exec.ExitError exit status 1
Stack Trace:
        github.com/gravitational/teleport/lib/client/db/dbcmd/error.go:56 github.com/gravitational/teleport/lib/client/db/dbcmd.ConvertCommandError
        github.com/gravitational/teleport/tool/tsh/db.go:775 main.onDatabaseConnect
        github.com/gravitational/teleport/tool/tsh/tsh.go:1070 main.Run
        github.com/gravitational/teleport/tool/tsh/tsh.go:457 main.main
        runtime/proc.go:250 runtime.main
        runtime/asm_amd64.s:1594 runtime.goexit
User Message: exit status 1
```

### PR DESCRIPTION
**Pull request by Tener**
* Add `--defaults-extra-file` as `~/.my.cnf` is not read on Windows.

* Escape `\` as `\\` in paths saved to the config file.

Fixes https://github.com/gravitational/teleport/issues/20042.

### CODE REVIEW

File: lib/client/db/mysql/optionfile.go [hunk 1]
```diff
@@ -88,9 +96,10 @@ func (o *OptionFile) Upsert(profile profile.ConnectProfile) error {
 	} else {
 		section.NewKey("ssl-mode", MySQLSSLModeVerifyIdentity)
 	}
-	section.NewKey("ssl-ca", profile.CACertPath)
-	section.NewKey("ssl-cert", profile.CertPath)
-	section.NewKey("ssl-key", profile.KeyPath)
+	// On Windows paths will contain \, which must be escaped to \\ as per https://dev.mysql.com/doc/refman/8.0/en/option-files.html
+	section.NewKey("ssl-ca", strings.ReplaceAll(profile.CACertPath, `\`, `\\`))
```
Comment (smallinsky) [inline lib/client/db/mysql/optionfile.go:100]: Does this change should be only applied for Windows OS ?

Comment (Tener) [reply lib/client/db/mysql/optionfile.go:100]: No, because the parsing is identical for all platforms and we should escape `\` for all platforms. It is true that outside of Windows `\` are less likely to appear, but in principle, they can.

**Review by smallinsky — APPROVED** [review]

**Review by nklaassen — APPROVED** [review]
