### PR TITLE
Stabilize TestInteractiveCompatibilityFlags

### LINKED ISSUE #53736: `TestInteractiveCompatibilityFlags/force_pseudo-terminal_allocation` flakiness
#### Link(s) to logs

(branch/v17)

https://github.com/gravitational/teleport/actions/runs/14269910645/job/40000524748

#### Relevant snippet

```
    tsh_test.go:6866: 
        	Error Trace:	/__w/teleport/teleport/tool/tsh/common/tsh_test.go:6866
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestInteractiveCompatibilityFlags/force_pseudo-terminal_allocation
```

### PR DESCRIPTION
**Pull request by rosstimothy**
The test was immediately attempting to connect to the target host, but due to cache propagation the proxy may not yet have it's inventory updated. This sporadically causes the test to fail as dial requests to the target cannot be honored. To make the test more robust to this situation a retry mechanism was added. In other tests we first wait for the node to be visible in the correct cache, however, this is not exposed in the TeleportProcess and thus not available to this test.

Closes #53736.

### CODE REVIEW

File: tool/tsh/common/tsh_test.go [hunk 1]
```diff
@@ -6877,8 +6877,14 @@ func TestInteractiveCompatibilityFlags(t *testing.T) {
...
 			t.Parallel()
-			err := exec.Command(tshBin, "ssh", tt.flag, hostname, tty).Run()
-			tt.assertError(t, err)
+
+			// Add some resiliency for cases where connections are attempted
+			// prior to the inventory being updated to contain the target node
+			// above.
+			require.EventuallyWithT(t, func(t *assert.CollectT) {
+				err := exec.Command(tshBin, "ssh", tt.flag, hostname, tty).Run()
+				tt.assertError(t, err)
```
Comment (zmb3) [inline tool/tsh/common/tsh_test.go:6886]:
```suggestion
				out, err := exec.Command(tshBin, "ssh", tt.flag, hostname, tty).CombinedOutput()
				tt.assertError(t, err, string(out))
```

**Review by zmb3 — APPROVED** [review]

**Review by gabrielcorado — APPROVED** [review]
