### PR TITLE
fix peer addr for in-memory control stream

### LINKED ISSUE #14786: Change in behavior and potential inconsistency with the in-memory Inventory Control Stream
A configuration like

```yaml
teleport:
  auth_servers: ["12.34.56.78"]
auth_service:
  enabled: yes
ssh_service:
  enabled: yes
```

(where `12.34.56.78` is the publicly reachable address of the server) will result in a ssh heartbeat with an address of `12.34.56.78` in v9, and an address of `::1` in v10, because the in-memory ICS doesn't have a way to extract the intended local address.

I'm not sure what the correct behavior should be, especially as we currently don't (can't?) really check that the auth server specified in `auth_servers` points to ourselves.

### PR DESCRIPTION
**Pull request by fspmarshall**
Updates the `Ping` method's response to include the peer address of the client as observed by the auth server handling the request.  This value is now used to create a `PeerAddr` for in-memory control streams, which is used to set the address of heartbeating nodes which don't know their public address.

Fixes https://github.com/gravitational/teleport/issues/14786

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: lib/auth/auth_with_roles.go [hunk 1]
```diff
@@ -749,7 +749,7 @@ func (a *ServerWithRoles) RegisterInventoryControlStream(ics client.UpstreamInve
 func (a *ServerWithRoles) GetInventoryStatus(ctx context.Context, req proto.InventoryStatusRequest) (proto.InventoryStatusSummary, error) {
 	// admin-only for now, but we'll eventually want to develop an RBAC syntax for
```
Comment (strideynet) [inline lib/auth/auth_with_roles.go:750]: Should we update this comment (as it's no longer admin-only)

**Review by strideynet — APPROVED** [review]
