### PR TITLE
Fix flaky TestAgentRolloutController

### LINKED ISSUE #49885: `TestAgentRolloutController` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/12202249813/job/34042510989?pr=49850

#### Relevant snippet

```
=== Failed
=== FAIL: lib/service TestAgentRolloutController (3.15s)
    service_test.go:1911: 
        	Error Trace:	/__w/teleport/teleport/lib/service/service_test.go:1911
        	Error:      	Condition never satisfied
        	Test:       	TestAgentRolloutController
```

### PR DESCRIPTION
**Pull request by hugoShaka**
Fixes https://github.com/gravitational/teleport/issues/49885

My guess is that the fake clock is advanced before the controller's ticker waits for the clock.
I don't want to rely on `WaitUntil()` because too many things are using the fake clock and the test will become flaky again the next time we add a new service or just a ticker in existing one.

### CODE REVIEW

File: lib/service/service_test.go [hunk 1]
```diff
@@ -1905,10 +1905,16 @@ func TestAgentRolloutController(t *testing.T) {
...
+	// There is no way of precisely knowing how many services are waiting for the fake clock to advance.
+	// If we were to do `fakeClock.BlockUntil(waiterCount)`, this wait would break the next time we add a new service
+	// waiting for the clock.
+	// To avoid deadlocks, we advance the clock during each require.Eventually() try.
+	// This is hacky but avoids the controller's ticker to hang, waiting for a clock Advance that already happened.
 	fakeClock.Advance(2 * time.Minute)
 
 	// Test validation: check that a new autoupdate_agent_rollout config was created
 	require.Eventually(t, func() bool {
+		fakeClock.Advance(2 * time.Minute)
```
Comment (hugoShaka) [inline lib/service/service_test.go:1917]: The alternative is using a real clock, maybe this would be better due to the test starting a whole teleport process.

Comment (hugoShaka) [reply lib/service/service_test.go]: Switched to a real clock as a fake clock has no benefits here, and can only make the test slower.

File: lib/service/service_test.go [hunk 2]
```diff
@@ -1851,13 +1851,13 @@ func TestInitDatabaseService(t *testing.T) {
...
 	t.Parallel()
 
-	// Test setup: create a Teleport Auth config
-	fakeClock := clockwork.NewFakeClock()
-
 	dataDir := makeTempDir(t)
 
 	cfg := servicecfg.MakeDefaultConfig()
-	cfg.Clock = fakeClock
+	// We use a real clock because too many sevrices are using the clock and it's not possible ot accurately wait for
```
Comment (codingllama) [inline lib/service/service_test.go:1857]:
```suggestion
	// We use a real clock because too many sevrices are using the clock and it's not possible to accurately wait for
```

**Review by codingllama — COMMENTED** [review]
Thanks, Hugo!

**Review by espadolini — APPROVED** [review]

**Comment by codingllama** [comment]
It looks like it's failing consistently now (see CI and also locally for me).

**Review by bl-nero — APPROVED** [review]

**Comment by hugoShaka** [comment]
> It looks like it's failing consistently now (see CI and also locally for me).

When switching to a real clock I forgot why I used a fake one initially: the controller sync every minute.
I created a parameter to control the period in tests and added an unstable env var to control it as this will become very useful when we'll want to do end2end test tests.

**Comment by hugoShaka** [comment]
As I changed the PR content quite a bit since you stamped it, could you take another look?

**Review by bl-nero — APPROVED** [review]

**Review by espadolini — DISMISSED** [review]

File: lib/config/configuration.go [hunk 3]
```diff
@@ -2747,6 +2747,14 @@ func Configure(clf *CommandLineFlags, cfg *servicecfg.Config, legacyAppFlags boo
 		cfg.Proxy.QUICProxyPeering = true
 	}
 
+	if rawPeriod := os.Getenv("TELEPORT_UNSTABLE_AGENT_ROLLOUT_SYNC_PERIOD"); rawPeriod != "" {
+		period, err := time.ParseDuration(rawPeriod)
+		if err != nil {
+			return trace.Wrap(err, "invalid agent rollout period %q: %v", rawPeriod, err)
```
Comment (codingllama) [inline lib/config/configuration.go:2753]: nit: Don't echo que error on trace.Wrap, it's already captured by the first parameter.

```suggestion
			return trace.Wrap(err, "invalid agent rollout period: %q", rawPeriod)
```

File: lib/service/service_test.go [hunk 4]
```diff
@@ -1866,6 +1866,8 @@ func TestAgentRolloutController(t *testing.T) {
 	cfg.DebugService.Enabled = false
 	cfg.Auth.StorageConfig.Params["path"] = dataDir
 	cfg.Auth.ListenAddr = utils.NetAddr{AddrNetwork: "tcp", Addr: "127.0.0.1:0"}
+	// Speed up the reconciliation period from 1 minute to 200ms for testing purposes
```
Comment (codingllama) [inline lib/service/service_test.go:1869]: nit: Don't call out the values in case they change.

```suggestion
	// Speed up the reconciliation period for testing purposes.
```

File: lib/service/service_test.go [hunk 5]
```diff
@@ -1866,6 +1866,8 @@ func TestAgentRolloutController(t *testing.T) {
...
+	cfg.Auth.AgentRolloutControllerSyncPeriod = 200 * time.Millisecond
```
Comment (codingllama) [inline lib/service/service_test.go:1870]: Could we make it faster or will it not make a difference?

File: lib/config/configuration.go [hunk 6]
```diff
@@ -2747,6 +2747,14 @@ func Configure(clf *CommandLineFlags, cfg *servicecfg.Config, legacyAppFlags boo
 		cfg.Proxy.QUICProxyPeering = true
 	}
 
+	if rawPeriod := os.Getenv("TELEPORT_UNSTABLE_AGENT_ROLLOUT_SYNC_PERIOD"); rawPeriod != "" {
```
[the remark this answers is not in the document]
Comment (hugoShaka) [reply lib/config/configuration.go:2750]: We will need this when we'll do end to end testing in cloud and check if rollout happens. This will allow us to reduce the test duration from hours to minutes.

File: lib/service/service_test.go (hunk 5 above)
Comment (hugoShaka) [reply lib/service/service_test.go:1870]: I can reduce it to 100ms, I'm afraid it might cause some load if we go lower. I used 200ms because this is the same test period we use for our inventory controller tests.

File: lib/config/configuration.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (hugoShaka) [reply lib/config/configuration.go]: removed

File: lib/service/service_test.go (hunk 5 above)
Comment (codingllama) [reply lib/service/service_test.go:1870]: If you think it's good do 100ms, otherwise feel free to leave as-is.

**Review by codingllama — APPROVED** [review]
Thanks, Hugo!

~Does this need backport labels?~

Edit: no need for backports, test is only on master.

**Review by espadolini — APPROVED** [review]

**Review by codingllama — APPROVED** [review]
