### PR TITLE
Fix an issue `tsh aws s3` fails when using path with special characters

### LINKED ISSUE #15765: S3 bucket issue when using tsh aws s3
Expected behavior:

The customer would like the ability for an S3 bucket name to have the `=` and successfully upload using `tsh aws s3` command. 

Current behavior:

The customer has multiple s3 buckets with special characters specifically `=` in them.  When executing `tsh aws s3 cp test.txt ` the commands fails with following error:  An error occurred (403) when calling the PutObject operation: Forbidden. Once they remove the `=` from the name they are successfully able to copy to their bucket. We have tested using the `aws s3 cp test.txt` with name having `=` and this method works as expected. 

```
tsh aws s3 cp test.txt s3://my-bucket/process/priority=1/
upload failed: ./test.txt to s3://my-bucket/process/priority=1/test.txt An error occurred (403) when calling the PutObject operation: Forbidden
```
```
tsh aws s3 cp test.txt s3://my-bucket/process/priority1/
upload: ./test.txt to s3://my-bucket/process/priority1/test.txt
```

```
aws s3 cp test.txt s3://my-bucket/process/priority=1/
upload: ./test.txt to s3://my-bucket/process/priority=1/test.txt
```
Bug details:
- Teleport version
- v9.3.3
- Recreation steps:
- Create S3 bucket folder name that contain `=`
- Debug logs
- I have debug logs, however it has sensitive information.

### PR DESCRIPTION
**Pull request by greedy52**
Fix #15765 
- #15765 

Root cause:
AWS SDKs have special handling when signing s3 requests.
https://github.com/aws/aws-sdk-go/blob/d4f5f556a9fb0bdca8da5e52f752b7fba6bedce5/service/s3/service.go#L77-L80
```
	// Handlers
	svc.Handlers.Sign.PushBackNamed(v4.BuildNamedHandler(v4.SignRequestHandler.Name, func(s *v4.Signer) {
		s.DisableURIPathEscaping = true
	}))
```

So when s3 path name contains special characters like `=`, the current/old code will generate a different signature. This happens at two places:
- tsh local proxy when verifying signature from AWS CLI
- app service sends an invalid signature to AWS

Testing:
- `tsh aws s3 ls`
- `tsh aws s3 cp test.text s3://steve-teleport-terraform/test=1/test.text1`
- `tsh proxy aws` and `terraform plan`

### CODE REVIEW

File: lib/srv/alpnproxy/local_proxy_test.go [hunk 1]
```diff
@@ -101,6 +104,34 @@ func TestHandleAWSAccessSigVerification(t *testing.T) {
...
+		require.NoError(t, err)
+
+		s3client := s3.New(session)
+
+		// Use a bucket name with special charaters. AWS SDK actually signs the
+		// request with the unescaped bucket name.
+		_, err = s3client.ListObjects(&s3.ListObjectsInput{
+			Bucket: aws.String("=bucket=name="),
+		})
+		require.NoError(t, err)
```
Comment (smallinsky) [inline lib/srv/alpnproxy/local_proxy_test.go:133]: nit: It looks like a separate  independed  test flow. Can we move it to a separate Test ?

**Review by smallinsky — COMMENTED** [review]
Don't we need to alight the [verifyAWSSignature](https://github.com/gravitational/teleport/blob/2da838fca16fb207b6dceaff60edc2c48e66dcdf/lib/utils/aws/aws.go#L193) logic too ?

**Comment by greedy52** [comment]
> Don't we need to alight the [verifyAWSSignature](https://github.com/gravitational/teleport/blob/2da838fca16fb207b6dceaff60edc2c48e66dcdf/lib/utils/aws/aws.go#L193) logic too ?

@smallinsky yes it is there right above the new `NewSigner` function =D
https://github.com/gravitational/teleport/blob/fac96c341cbd0d5ba2349422c69c959cd67e7096/lib/utils/aws/aws.go#L193

Will move the UT to a separate test

**Review by smallinsky — APPROVED** [review]

**Review by r0mant — APPROVED** [review]
