### PR TITLE
Use test IP addresses for auth_proxy_test.

### LINKED ISSUE #21453: `TestDialLocalAuthServerNoAvailableServers` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4124635357/jobs/7124129959

#### Relevant snippet

```
===================================================
FAIL: github.com/gravitational/teleport/lib/srv/alpnproxy/auth
FAIL: github.com/gravitational/teleport/lib/srv/alpnproxy/auth.TestDialLocalAuthServerNoAvailableServers
===================================================
OUTPUT github.com/gravitational/teleport/lib/srv/alpnproxy/auth.TestDialLocalAuthServerNoAvailableServers
===================================================
=== RUN   TestDialLocalAuthServerNoAvailableServers
    auth_proxy_test.go:38: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/alpnproxy/auth/auth_proxy_test.go:38
        	Error:      	An error is expected but got nil.
        	Test:       	TestDialLocalAuthServerNoAvailableServers
        	Messages:   	dialLocalAuthServer expected to fail
--- FAIL: TestDialLocalAuthServerNoAvailableServers (0.00s)
===================================================
```

### PR DESCRIPTION
**Pull request by mdwn**
The auth_proxy_test file now uses IP addresses from the block `TEST-NET-3` as specified in https://www.rfc-editor.org/rfc/rfc5735#section-3. Previously, it was using `0.0.0.0` IP addresses. This has a chance of actually hitting locally running services depending on the test runner setup, making the tests non-deterministic. The hope here is that this change will avoid the spurious test failures seen in CI.

Fixes #21453

### CODE REVIEW

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 1]
```diff
@@ -33,13 +34,15 @@ func TestDialLocalAuthServerNoServers(t *testing.T) {
 }
 
 func TestDialLocalAuthServerNoAvailableServers(t *testing.T) {
-	s := NewAuthProxyDialerService(nil /* reverseTunnelServer */, "clustername", []string{"0.0.0.0:3025"}, nil, nil)
-	_, err := s.dialLocalAuthServer(context.Background())
+	s := NewAuthProxyDialerService(nil /* reverseTunnelServer */, "clustername", []string{"203.0.113.1:3025"}, nil, nil)
```
Comment (timothyb89) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:37]: A quick comment about the reserved IP range might be nice here, since it otherwise looks valid-ish at first glance.

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 2]
```diff
@@ -33,13 +34,15 @@ func TestDialLocalAuthServerNoServers(t *testing.T) {
...
+	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
+	defer cancel()
```
Comment (jakule) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:39]:
```suggestion
	t.Cleanup(cancel)
```

**Review by timothyb89 — APPROVED** [review]

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 3]
```diff
@@ -51,11 +54,13 @@ func TestDialLocalAuthServerAvailableServers(t *testing.T) {
 	authServers[0] = socket.Addr().String()
 	// multiple invalid servers to minimize chance that we select good one first try
 	for i := 0; i < 10; i++ {
-		authServers = append(authServers, "0.0.0.0:3025")
+		authServers = append(authServers, fmt.Sprintf("203.0.113.%d:3025", i+1))
 	}
 	s := NewAuthProxyDialerService(nil /* reverseTunnelServer */, "clustername", authServers, nil, nil)
 	require.Eventually(t, func() bool {
-		conn, err := s.dialLocalAuthServer(context.Background())
+		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Millisecond)
```
Comment (espadolini) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:61]: Should we give ourselves a little more than 10ms?
```suggestion
		ctx, cancel := context.WithTimeout(context.Background(), 50*time.Millisecond)
```

File: lib/srv/alpnproxy/auth/auth_proxy_test.go [hunk 4]
```diff
@@ -51,11 +54,13 @@ func TestDialLocalAuthServerAvailableServers(t *testing.T) {
...
+		defer cancel()
```
Comment (jakule) [inline lib/srv/alpnproxy/auth/auth_proxy_test.go:62]:
```suggestion
		t.Cleanup(cancel)
```

**Review by jakule — APPROVED** [review]
Looks good. Please add the comment as @timothyb89 mentioned. I'd also be surprised by that without reading the PR description.

**Review by espadolini — APPROVED** [review]

**Comment by zmb3** [comment]
Thanks for jumping on this @mdwn!

**Review by zmb3 — APPROVED** [review]
