### PR TITLE
Deflake Discovery Server tests

### LINKED ISSUE #30387: `TestDiscoveryServer ` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5843481607/job/15845668364?pr=30385

#### Relevant snippet

```
=== FAIL: lib/srv/discovery TestDiscoveryServer/chunked_nodes_get_2_log_messages (1.58s)
    discovery_test.go:447: 
        	Error Trace:	/__w/teleport/teleport/lib/srv/discovery/discovery_test.go:447
        	Error:      	Condition never satisfied
        	Test:       	TestDiscoveryServer/chunked_nodes_get_2_log_messages
```

### PR DESCRIPTION
**Pull request by marcoandredinis**
Moved all the tests in `lib/srv/discovery` to use synctest.

Added some mutexes in the storage mocks (eg, for discovery config resources).

Ran the stress tool for quite some time:
```
> go test -c github.com/gravitational/teleport/lib/srv/discovery -race && stress -p 60 ./discovery.test -test.count 10
...
20m0s: 300 runs so far, 0 failures, 60 active
```

Testing the whole package went from
```
(master)> go test github.com/gravitational/teleport/lib/srv/discovery -race -count 2
ok      github.com/gravitational/teleport/lib/srv/discovery     13.848s
```
to

```
(marco/deflake_test_discoveryserver)> go test github.com/gravitational/teleport/lib/srv/discovery -race -count 2
ok      github.com/gravitational/teleport/lib/srv/discovery     6.883s
```

Fixes: https://github.com/gravitational/teleport/issues/30387

### CODE REVIEW

**Comment by marcoandredinis** [comment]
@claude review

**Comment by zmb3** [comment]
Which change here actually fixes the flakiness? Do we understand what caused it?

**Comment by marcoandredinis** [comment]
> Which change here actually fixes the flakiness? Do we understand what caused it?

This was fixed by re-writing the test to use synctest.
It was caused by the async flow of the EC2 discovery
When discovering/enrolling EC2 instances we have the following goroutines:
- ec2 watcher: discovers ec2 instances and sends them to a channel
- ssm installer: gets instances from the channel and calls `ssm.Run` so that we install teleport on them
We update the DiscoveryConfig status when the watcher starts a new iteration.

The following can happen:
```
ec2 watcher:
t0: updates status; resets counter; poll; sends 1 instance (iteration1)
t1: updates status; resets counter; poll;
t2: 
t3: sends 1 instance (iteration2)
t4: 
t5: updates status; resets counter; poll; sends 1 instance (iteration3)

ssm installer:
t0:
t1:
t2: receives 1 instance (from iteration1); increments found count
t3:
t4: receives 1 instance (from iteration2); increments found count
t5:
```
At t5, when the ec2 watcher updates the status, it will have two found resources.

So, while this could happen in a real world scenario, it's very unlikely 

We are moving away from this channel based flow anyway in https://github.com/gravitational/teleport/pull/64956

When testing this I also found other flaky tests, that's why I ended up fixing the others.

**Review by avatus — APPROVED** [review]

**Comment by zmb3** [comment]
Help me understand - it looks like the fix is to protect a bunch of fields with new mutexes. Does this mean we had a data race?

**Comment by marcoandredinis** [comment]
> Help me understand - it looks like the fix is to protect a bunch of fields with new mutexes. Does this mean we had a data race?

We had a data race in the test code/mocks. They can be called from multiple places and we were not accounting for it.

At this point, I'm trying to fix all the tests in `lib/srv/discovery`.
Mostly by converting them to `synctest`.
Just found out some other scenarios where this is failing, so I converted the PR to draft until I fix those as well.

I'll fix whatever comes out of
```
$ go test -c github.com/gravitational/teleport/lib/srv/discovery -race && stress -p 60 ./discovery.test -test.count 10
```

**Comment by marcoandredinis** [comment]
@zmb3 @tigrato Can you please take a look?

File: lib/srv/discovery/discovery_eks_test.go [hunk 1]
```diff
@@ -305,11 +305,17 @@ func TestDiscoveryServerEKS(t *testing.T) {
 type mockAuthServer struct {
 	authclient.DiscoveryAccessPoint
 
-	storeDiscoveryConfigs map[string]*discoveryconfig.DiscoveryConfig
-	storeUserTasks        map[string]*usertasksv1.UserTask
+	discoveryConfigSemaphore sync.Mutex
```
Comment (zmb3) [inline lib/srv/discovery/discovery_eks_test.go:308]:
```suggestion
	discoveryConfigMu sync.Mutex
```
I would use the same naming conventions as the other mutex fields.

**Review by zmb3 — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

File: lib/srv/discovery/discovery_eks_test.go (hunk 1 above)
Comment (marcoandredinis) [reply lib/srv/discovery/discovery_eks_test.go:308]: This one is meant to be used by the Acquire/Cancel Semaphore APIs.
I think calling it a Semaphore (which we expect to only ever allow 1 concurrent access) is a better indication of what this variable is protecting/being used for.
