### PR TITLE
fix: access graph fails to fetch s3 bucket details

### LINKED ISSUE #50757: Access Graph AWS sync  fails with incorrect s3 bucket region
Expected behavior:
Access Graph AWS sync shouldn't fail with incorrect location

Current behavior:

```
BucketRegionError: incorrect region, the bucket is not in 'ap-south-1' region at endpoint '', bucket is in 'eu-central-1' region
status code: 301, request id: QS5C24H12ZV3VNM4, host id: mzVDk4010MPTCFdxyE/XwERX9W35MSge85PG+h5Jvwyvi7MhxdXLaysb2PTZCMY9r1ngBi6Gv6g=, failed to fetch bucket "xyz" acls polic
```

### PR DESCRIPTION
**Pull request by tigrato**
With SDK V1, AWS get bucket details such as policies, acls, status... didn't require the specification of the target s3 bucket location. With the recent changes to support newer versions of the AWS SDK, the get bucket details started to fail with the following error:

```
BucketRegionError: incorrect region, the bucket is not in 'ap-south-1' region at endpoint '', bucket is in 'eu-central-1' region
status code: 301, request id: QS5C24H12ZV3VNM4, host id: mzVDk4010MPTCFdxyE/XwERX9W35MSge85PG+h5Jvwyvi7MhxdXLaysb2PTZCMY9r1ngBi6Gv6g=, failed to fetch bucket "cyz" acls polic
```

This PR uses `HeadBucket` to retrieve the location of the s3 bucket and then uses the bucket location client to retrieve the s3 bucket details.

Fixes #50757

Changelog: Fixes a bug where S3 bucket details fail to fetch due to incorrect bucket region.

### CODE REVIEW

**Review by ryanclark — APPROVED** [review]

File: lib/cloud/aws/policy_statements.go [hunk 1]
```diff
@@ -406,6 +406,9 @@ func StatementAccessGraphAWSSync() *Statement {
 			"s3:ListBucket",
 			"s3:GetBucketLocation",
 			"s3:GetBucketTagging",
+			"s3:GetBucketPolicyStatus",
+			"s3:GetBucketAcl",
```
Comment (marcoandredinis) [inline lib/cloud/aws/policy_statements.go:410]: Do we need to update this doc file as well?
https://github.com/gravitational/teleport/blob/b6ffcee62146e16741458970bad27d7e0de69935/docs/pages/admin-guides/teleport-policy/integrations/aws-sync.mdx?plain=1#L154-L158

File: lib/srv/discovery/fetchers/aws-sync/s3.go [hunk 2]
```diff
@@ -237,3 +228,93 @@ func mergeS3Protos(existing, new *accessgraphv1alpha.AWSS3BucketV1, failedReqs f
...
+
+	details.policy, err = s3Client.GetBucketPolicyWithContext(ctx, &s3.GetBucketPolicyInput{
+		Bucket: bucket.Name,
+	})
+	const noSuchBucketPolicy = "NoSuchBucketPolicy"
+	var awsErr awserr.Error
+	if errors.As(err, &awsErr) && awsErr.Code() == noSuchBucketPolicy {
+		// If there is no policy, set the error to nil.
+		err = nil
+	}
```
Comment (marcoandredinis) [inline lib/srv/discovery/fetchers/aws-sync/s3.go:271]: I would move this and others to helper functions.
Mutating the `err` variable can lead to confusion

File: lib/srv/discovery/fetchers/aws-sync/s3.go [hunk 3]
```diff
@@ -76,23 +76,40 @@ func (a *awsFetcher) fetchS3Buckets(ctx context.Context) ([]*accessgraphv1alpha.
...
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
+		rsp, err := globalS3Client.ListBucketsWithContext(
+			ctx,
+			&s3.ListBucketsInput{},
+		)
+		if err != nil {
+			return existing.S3Buckets, trace.Wrap(err)
+		}
```
[the remark this answers is not in the document]
Comment (tigrato) [reply lib/srv/discovery/fetchers/aws-sync/s3.go:96]: The error is always collected and logged in the integration status

File: lib/srv/discovery/fetchers/aws-sync/s3.go [hunk 4]
```diff
@@ -76,23 +76,40 @@ func (a *awsFetcher) fetchS3Buckets(ctx context.Context) ([]*accessgraphv1alpha.
...
+				ctx,
+				&s3.HeadBucketInput{
+					Bucket: bucket,
+				},
+			)
+			if err != nil {
+				return "", trace.Wrap(err, "failed to fetch bucket %q region", aws.ToString(bucket))
+			}
+			return aws.ToString(rsp.BucketRegion), nil
+		}
```
[the remark this answers is not in the document]
Comment (tigrato) [reply lib/srv/discovery/fetchers/aws-sync/s3.go]: done

File: lib/srv/discovery/fetchers/aws-sync/s3.go [hunk 5]
```diff
@@ -237,3 +193,130 @@ func mergeS3Protos(existing, new *accessgraphv1alpha.AWSS3BucketV1, failedReqs f
...
+	}
+	return false
+}
+
+func isS3BucketNoTagSet(err error) bool {
+	var awsErr awserr.Error
+	if errors.As(err, &awsErr) && awsErr.Code() == "NoSuchTagSet" {
+		return true
+	}
+	return false
```
Comment (marcoandredinis) [inline lib/srv/discovery/fetchers/aws-sync/s3.go:284]:
```suggestion
	return errors.As(err, &awsErr) && awsErr.Code() == "NoSuchTagSet"
```

**Review by marcoandredinis — APPROVED** [review]
