### PR TITLE
Use TELEPORT_LOGIN_BIND_ADDR if set

### LINKED ISSUE #2881: TELEPORT_LOGIN_BIND_ADDR not respected in automatic login
My `tsh` session had expired, and I executed `tsh clusters`
**What happened**:
I got prompted to log in, but the URL did no match the`TELEPORT_LOGIN_BIND_ADDR` I had set.
```
$ echo $TELEPORT_LOGIN_BIND_ADDR
:38987
$ tsh clusters
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:37561/08900932-1a1c-4007-bacd-747c93b12345
```

**What you expected to happen**:
I would get a login URL that respected `TELEPORT_LOGIN_BIND_ADDR`
```
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:38987/08900932-1a1c-4007-bacd-747c93b12345
```
**How to reproduce it (as minimally and precisely as possible)**:
- Set `TELEPORT_LOGIN_BIND_ADDR`
- `tsh login`
- Wait for the session to expire
- `tsh clusters`

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.2.4 git:v3.2.4-0-g339827c6 go1.11.5
- Tsh version (use `tsh version`): Teleport v3.2.4 git:v3.2.4-0-g339827c6 go1.11.5
- OS (e.g. from /etc/os-release): Alpine Linux v3.9.3

### PR DESCRIPTION
**Pull request by webvictim**
We didn't always honour the `TELEPORT_LOGIN_BIND_ADDR` environment variable if it was set - it was only applied when running `tsh login`. Making this a global flag means that it will apply to _any_ `tsh` command, such as `tsh ls` or `tsh clusters`.

Unfortunately this does introduce another global flag (which seems contrary to the intention of #4078) but I think it's important that we fix this bug.

Fixes #2881

### CODE REVIEW

File: tool/tsh/tsh.go [hunk 1]
```diff
@@ -231,6 +231,7 @@ func Run(args []string) {
 	app.Flag("enable-escape-sequences", "Enable support for SSH escape sequences. Type '~?' during an SSH session to list supported sequences. Default is enabled.").
 		Default("true").
 		BoolVar(&cf.EnableEscapeSequences)
+	app.Flag("bind-addr", "Address in the form of host:port to bind to for login command webhook").Envar(bindAddrEnvVar).StringVar(&cf.BindAddr)
```
Comment (benarent) [inline tool/tsh/tsh.go:234]: I personally find the naming of this confusing, since we are mixing implementation details with the flag.

```
bind-addr", "Override default host:port for tsh login"
```
^ Open to feedback?

Comment (webvictim) [reply tool/tsh/tsh.go:234]: Yeah, it's confusing. The thing is that we're going to be triggering the `tsh login` flow automatically if someone is logged out and they run `tsh ls` or `tsh clusters` for example, so it's hard to explain it. There's also the fact that users who don't use SSO will never even see a loopback listener.

Comment (benarent) [reply tool/tsh/tsh.go:234]: Maybe 

```
`bind-addr", "Override default host:port for explicit port and host mapping"
```

Comment (webvictim) [reply tool/tsh/tsh.go:234]: I think that's even more vague...!

Comment (benarent) [reply tool/tsh/tsh.go:234]: I think that's ok, I'm mainly trying to drop the 'webhook' terminology.

It seems the two main use cases for this are 
- Connecting to docker container on mac https://github.com/gravitational/teleport/issues/2620
- Changing the default port / host for SSO logins

Comment (webvictim) [reply tool/tsh/tsh.go:234]: How about `Override host:port used when opening a browser for cluster logins`?

More explicit about exactly what it does and removes "webhook".

**Comment by webvictim** [comment]
retest this please

**Review by awly — APPROVED** [review]

**Review by russjones — APPROVED** [review]
