### PR TITLE
Mask token in logs

### LINKED ISSUE #7827: Mask token in logs.
In https://github.com/gravitational/teleport/commit/e9ab2ba0c49e2b7e71f66f5eb2ec60a1b76f7d49 we added support for obfuscation to diagnostic metrics so tokens didn't show up in `tctl top`.

Similarly, when emitting a token to logs, even invalid tokens, we should mask them.

```
WARN [AUTH]      "<node hostname>" [00000000-0000-0000-0000-000000000000] can not join the cluster with
   role Node, token error: key "/tokens/12345789" is not found auth/auth.go:1511
```

### PR DESCRIPTION
**Pull request by Joerger**
- Refactored existing key-masking logic to be more reusable
- Added `apiutils.MaskSubString` which can be used to mask messages and error messages before logging them.
  - applied this masking logic to several logs in `lib/auth`.

Examples:

```
2021-08-17T17:22:41-07:00 [AUTH]      WARN "" [not nil] can not join the cluster with role Node, token error: key "/tokens/*********************dinvalid" is not found auth/auth.go:1696
```
```
2021-08-17T17:23:51-07:00 [AUTH]      DEBU Sending validate request; token=************************336951dc, CAs=[CA(name=remote.example.com, type=host)] auth/trustedcluster.go:267
```
```
2021-08-17T17:25:50-07:00 [AUTH]      DEBU Received validate request: token=************************336951dc, CAs=[CA(name=remote.example.com, type=host)] auth/trustedcluster.go:455
```

Closes https://github.com/gravitational/teleport/issues/7827

### CODE REVIEW

File: lib/backend/backend.go [hunk 1]
```diff
@@ -244,6 +245,27 @@ func NextPaginationKey(r types.Resource) string {
 	return string(nextKey([]byte(r.GetName())))
 }
 
+// MaskKey masks the given key if any of the given sensitive prefixes are detected.
+// If no sensitive prefixes are given, then defaults will be used.
+// e.g "/tokens/123456789" -> "/tokens/******789"
+func MaskKey(key []byte, sensitivePrefixes ...string) []byte {
```
Comment (andrejtokarcik) [inline lib/backend/backend.go:251]: I think it's better to keep this unexported in `backend/report.go` and tied with the only current use case. Although you may have some future use cases in mind, unless we need to support them immediately it [might be bad practice](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) to introduce this generalization at this point.

Also notice how you're splitting and rejoining with `Separator` in `buildKeyLabel` and then splitting and rejoining once again here in `MaskKey` just because the functions are now standalone. Is there anything to outweigh this cumbersome complexity?

File: lib/backend/backend.go [hunk 2]
```diff
@@ -244,6 +245,27 @@ func NextPaginationKey(r types.Resource) string {
...
+	if len(sensitivePrefixes) == 0 {
+		sensitivePrefixes = sensitiveBackendPrefixes
+	}
+
+	// If a prefix is found in the key parts, mask the subsequent key part (presumably the key name).
+	parts := bytes.Split(key, []byte{Separator})
+	for i := 0; i < len(parts)-1; i++ {
```
Comment (andrejtokarcik) [inline lib/backend/backend.go:258]: I'm a bit worried this approach might cause accidental maskings, especially in conjunction with the fact the function now gives the appearance of being available for general use. In the original code the sensitive prefix was compared with the first key only, i.e. in `/a/b/c` only `a` were checked to be sensitive.

With this approach, suppose there was a role named `tokens` stored under the backend key `/roles/tokens/params`, `MaskKey` would then unexpectedly return something like `/roles/tokens/****ms`.

File: lib/auth/register.go [hunk 3]
```diff
@@ -145,8 +146,8 @@ func Register(params RegisterParams) (*Identity, error) {
 		log.Infof("Attempting registration %s.", method.desc)
 		ident, err := method.call(token, params)
 		if err != nil {
-			collectedErrs = append(collectedErrs, err)
-			log.WithError(err).Debugf("Registration %s failed.", method.desc)
+			maskedErr := trace.Errorf(apiutils.MaskSubString(token, err.Error()))
```
[the remark this answers is not in the document]
Comment (Joerger) [reply lib/auth/register.go:149]: Good catch, sorry I was going to make a pass myself this morning to catch typos.

File: lib/backend/backend.go (hunk 1 above)
Comment (Joerger) [reply lib/backend/backend.go:251]: I found the code to be confusing and was worried about it being misused in the future, so I was trying to separate out the "keylabel" and "keymask" logic and generalize it. I think you're right that this isn't needed right now and instead I might just add some comments to the original code.

**Review by russjones — COMMENTED** [review]
Mask just the token at the source where it's embedded into the error and then you don't have to do substring masking.

File: lib/backend/report.go [hunk 4]
```diff
@@ -288,26 +287,22 @@ func (s *Reporter) trackRequest(opType types.OpType, key []byte, endKey []byte)
...
-func buildKeyLabel(key []byte, sensitivePrefixes []string) string {
-	// Take just the first two parts, otherwise too many distinct requests
-	// can end up in the map.
-	parts := bytes.Split(key, []byte{Separator})
+// buildKeyLabel builds the key label for storing to the backend. The key's name
+// is masked if it is determined to be sensitive based on sensitivePrefixes.
+func buildKeyLabel(key string, sensitivePrefixes []string) string {
+	parts := strings.Split(key, string(Separator))
 	if len(parts) > 3 {
+		// Cut the key down to 3 parts. otherwise too many
```
Comment (andrejtokarcik) [inline lib/backend/report.go:295]:
```suggestion
		// Cut the key down to 3 parts, otherwise too many
```

**Review by andrejtokarcik — APPROVED** [review]

File: lib/backend/backend.go [hunk 5]
```diff
@@ -244,6 +245,14 @@ func NextPaginationKey(r types.Resource) string {
 	return string(nextKey([]byte(r.GetName())))
 }
 
+// MaskKeyName masks the given key name.
+// e.g "123456789" -> "******789"
+func MaskKeyName(str string) string {
```
Comment (zmb3) [inline lib/backend/backend.go:250]: This seems pretty general purpose and not specific to the backend - is there a better package we could put this logic in?

File: lib/backend/backend.go [hunk 6]
```diff
@@ -244,6 +245,14 @@ func NextPaginationKey(r types.Resource) string {
...
+	hiddenBefore := int(math.Floor(0.75 * float64(len(str))))
```
Comment (zmb3) [inline lib/backend/backend.go:251]: You don't need to import math to accomplish this.
```suggestion
	hiddenBefore := int(0.75 * float64(len(str)))
```

File: lib/backend/backend.go [hunk 7]
```diff
@@ -244,6 +245,14 @@ func NextPaginationKey(r types.Resource) string {
...
+	asterisks := bytes.Repeat([]byte("*"), hiddenBefore)
+	return string(append(asterisks, str[hiddenBefore:]...))
```
Comment (zmb3) [inline lib/backend/backend.go:253]: Depending on how frequently this is called, you may want to accept a `[]byte` instead of a string, and mask the data out by mutating the slice.

Strings allocate, and if this is called frequently as we stream logs we're generating a lot of tiny strings for the GC to clean up.

Comment (tcsc) [reply lib/backend/backend.go:253]: From looking at the call site, the source data already seems to be a string. Copying the `string` into a `[]byte` doesn't really save you anything, especially if you have to copy it back to a `string` afterwards.

**Review by tcsc — APPROVED** [review]

File: lib/backend/backend.go (hunk 7 above)
Comment (zmb3) [reply lib/backend/backend.go:253]: Right, but you don't need to copy it back to a `string` afterwords if all you're going to do is write it to the logger.  `%s` will print a `[]byte` just fine.

Really not a big deal unless we expect to be masking in hundreds of thousands of log lines - in which case all those tiny allocations add up.

File: lib/backend/backend.go (hunk 5 above)
Comment (Joerger) [reply lib/backend/backend.go:250]: I put it here because right now it is only being used to mask backend key names. This could be moved to a new file in `lib/utils`, but our utils are already overflowing and I think it's better to keep this here until (if) it is needed for more general use cases.

File: lib/backend/backend.go (hunk 7 above)
Comment (Joerger) [reply lib/backend/backend.go:253]: If I understand stack allocation correctly in go, this shouldn't be a concern. The `str` parameter will be copied and allocated to the stack, not the heap, so as soon as `MaskKeyName` returns, the copied `str` value and other allocated values within the function will be popped off the stack without any work for the GC.

**Review by zmb3 — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]
