### PR TITLE
Gavinfrazar/fix tsh status cluster env var

### LINKED ISSUE #12479: tsh status doesn't respect TELEPORT_CLUSTER env var
Expected behavior:

`tsh status` takes the `TELEPORT_CLUSTER` env var into account when reporting the current cluster.

Current behavior:

`tsh status` seems to report the `cluster` value set in the profile YAML file.

`tsh status` might not be the only affected command, though other commands like `tsh ls` or `tsh db ls` generally take `TELEPORT_CLUSTER` into account. 

Bug details:
- Teleport version: running `tsh` from master (`9f2f7bf52`).
- Recreation steps:
   * In one shell session execute `tsh login --proxy=root-cluster && eval $(tsh env)`.
   * In another shell session do `tsh login leaf-cluster`.
   * `tsh status` in the first shell session reports the cluster as `leaf-cluster`, while I'd expect it to report `root-cluster`.

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #12479

This adds info about the relevant active env variables when a user invokes `tsh status` or `tsh login`.

This should improve UX when a user logs in and expects their updated profile to be used as the source of truth for their cluster/proxy/user. If they have env vars set which override profile settings, those env vars will be displayed.

### CODE REVIEW

File: tool/tsh/tsh.go [hunk 1]
```diff
@@ -2832,6 +2833,17 @@ func serializeProfiles(profile *client.ProfileStatus, profiles []*client.Profile
 	return string(out), nil
 }
 
+func getStatusEnv() map[string]string {
+	env := map[string]string{}
+	envVars := []string{proxyEnvVar, clusterEnvVar, siteEnvVar, userEnvVar}
```
Comment (GavinFrazar) [inline tool/tsh/tsh.go:2838]: I think these are the most relevant env vars. I could include TELEPORT_HOME and these env vars defined in tsh.go:

https://github.com/gravitational/teleport/blob/50fdea64136c83f446f6696088844c458b750873/tool/tsh/tsh.go#L375-L384

I'm not sure if those are relevant enough info to display though. We probably don't want to display every env var being picked up by tsh, right?

File: tool/tsh/tsh.go [hunk 2]
```diff
@@ -2846,6 +2858,15 @@ func printProfiles(debug bool, profile *client.ProfileStatus, profiles []*client
 	for _, p := range profiles {
 		printStatus(debug, p, false)
 	}
+
+	// Print relevant active env vars, if they are set.
+	env := getStatusEnv()
+	if len(env) > 0 {
```
Comment (r0mant) [inline tool/tsh/tsh.go:2864]: @GavinFrazar @ravicious Couple of notes here:

- Is this going to be printed by default? I'm not sure we'd want that, this should probably be hidden behind a `-v` flag (we should have verbose flag already).
- I'm not sure why we don't want to just show the cluster name from TELEPORT_CLUSTER variable in the tsh status by default? It's supposed to show the currently active cluster so if you have the env var set, then it makes sense to show it. Showing both might only be more confusing for users IMO.

I think that displaying set env. vars with -v flag is a good idea, but I would go back to the original suggestion and also showed the actual cluster name in tsh status.

**Review by r0mant — CHANGES_REQUESTED** [review]

File: tool/tsh/tsh.go (hunk 2 above)
Comment (GavinFrazar) [reply tool/tsh/tsh.go:2864]: I did that originally, but thought that it might be cleaner to just show the profile and environment separately. Should we add an indicator that the cluster is being selected by the env var, like "(from TELEPORT_CLUSTER)" next to the name?

Comment (r0mant) [reply tool/tsh/tsh.go:2864]: Sure, that sounds good. You can also "pin" a kube cluster same way using `TELEPORT_KUBE_CLUSTER` variable, let's also do the same for it while we're here.

Comment (GavinFrazar) [reply tool/tsh/tsh.go:2864]: For `$ tsh status` it's fine to display `(TELEPORT_CLUSTER is set)` next to the active profile cluster, but what if they specify `$ tsh status --format=json` or use `--format=yaml`? I don't know if we want to put that info in there still, since it may be consumed by some other program by a user (I have no idea whether anyone actually does this).

This makes me want to lean towards just displaying the info separately beneath the profile(s), or in yaml/json, adding an "environment:" entry. We can still gate this new behavior behind a "-v --verbose" flag, which tsh status/login does not have currently.

Examples:
```
> tsh status -v                                                                                     (base) 
> Profile URL:        https://proxy1.local.gd:3080
  Logged in as:       bob
  Cluster:            cluster2
  Roles:              access, auditor, editor
  Logins:             gavin, -teleport-internal-join
  Kubernetes:         enabled
  Valid until:        2022-06-02 00:43:03 -0700 PDT [valid for 11h20m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

Active Environment
TELEPORT_SITE=cluster2
```

```
> tsh status -v --format=yaml                                                                       (base) 
active:
  cluster: cluster1
  extensions:
  - permit-agent-forwarding
  - permit-port-forwarding
  - permit-pty
  kubernetes_enabled: true
  logins:
  - gavin
  - -teleport-internal-join
  profile_url: https://proxy1.local.gd:3080
  roles:
  - access
  - auditor
  - editor
  traits:
    logins:
    - gavin
  username: bob
  valid_until: "2022-06-02T00:43:03-07:00"
environment:
  TELEPORT_CLUSTER: cluster1
  TELEPORT_PROXY: proxy1.local.gd:3080
profiles: []
```

Comment (GavinFrazar) [reply tool/tsh/tsh.go]: I've made the behavior this:

`$ tsh status` displays the active profile with proxy, cluster, and kube cluster settings from env variables, if they are set. It will display the env var shadowing the active profile setting next to the output in parentheses.

A new verbose flag (-v, --verbose) can be specified to display the active environment below the profiles.

Example output:
```fish
> tsh status -v                                                                                     (base) 
> Profile URL:        https://proxy1.local.gd:3080 (TELEPORT_PROXY)
  Logged in as:       alice
  Cluster:            cluster2 (TELEPORT_CLUSTER)
  Roles:              access, auditor, editor
  Logins:             gavin, -teleport-internal-join
  Kubernetes:         enabled
  Kubernetes cluster: "kubeSTUB (TELEPORT_KUBE_CLUSTER)"
  Valid until:        2022-06-07 02:44:33 -0700 PDT [valid for 11h55m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

Active Environment
TELEPORT_CLUSTER=cluster2
TELEPORT_KUBE_CLUSTER=kubeSTUB
TELEPORT_PROXY=proxy1.local.gd:3080
```

And json output example:
```fish
{
  "active": {
    "profile_url": "https://proxy1.local.gd:3080",
    "username": "alice",
    "cluster": "cluster2",
    "roles": [
      "access",
      "auditor",
      "editor"
    ],
    "traits": {
      "aws_role_arns": null,
      "db_names": null,
      "db_users": null,
      "kubernetes_groups": null,
      "kubernetes_users": null,
      "logins": [
  "gavin"
],
      "windows_logins": null
    },
    "logins": [
      "gavin",
      "-teleport-internal-join"
    ],
    "kubernetes_enabled": true,
    "kubernetes_cluster": "kubeSTUB",
    "valid_until": "2022-06-07T02:44:33-07:00",
    "extensions": [
      "permit-agent-forwarding",
      "permit-port-forwarding",
      "permit-pty"
    ]
  },
  "profiles": [],
  "environment": {
    "TELEPORT_CLUSTER": "cluster2",
    "TELEPORT_KUBE_CLUSTER": "kubeSTUB",
    "TELEPORT_PROXY": "proxy1.local.gd:3080"
  }
}
```

File: tool/tsh/tsh.go [hunk 3]
```diff
@@ -656,6 +657,7 @@ func Run(ctx context.Context, args []string, opts ...cliOption) error {
 	login.Arg("cluster", clusterHelp).StringVar(&cf.SiteName)
 	login.Flag("browser", browserHelp).StringVar(&cf.Browser)
 	login.Flag("kube-cluster", "Name of the Kubernetes cluster to login to").StringVar(&cf.KubernetesCluster)
+	login.Flag("verbose", "Show extra status information").Short('v').BoolVar(&cf.Verbose)
```
Comment (ravicious) [inline tool/tsh/tsh.go:660]: I'm not 100% sure if `tsh login` needs to have the verbose flag. But I guess maybe it's fine in terms of consistency, since it shows the same info as `tsh status` and `tsh status` does support this flag?

**Review by ravicious — APPROVED** [review]
I tested this in a couple of scenarios within Connect and it seems to work well.

File: tool/tsh/tsh_test.go [hunk 4]
```diff
@@ -2175,7 +2177,40 @@ func TestSerializeProfilesNoActive(t *testing.T) {
 	}
 	`
 	testSerialization(t, expected, func(f string) (string, error) {
-		return serializeProfiles(nil, nil, f)
+		return serializeProfiles(nil, nil, nil, f)
+	})
+}
+
+func TestSerializeProfilesWithEnvVars(t *testing.T) {
```
Comment (ravicious) [inline tool/tsh/tsh_test.go:2184]: Thanks for adding the tests, it's a shame that we don't have an established way to test the output of `tsh status` itself. It'd definitely be useful to have some test cases for the behavior implemented in this PR.

File: tool/tsh/tsh.go (hunk 2 above)
Comment (GavinFrazar) [reply tool/tsh/tsh.go]: @r0mant can we mark this resolved?

File: tool/tsh/tsh.go [hunk 5]
```diff
@@ -3114,19 +3176,40 @@ func serializeProfiles(profile *client.ProfileStatus, profiles []*client.Profile
 	return string(out), nil
 }
 
-func printProfiles(debug bool, profile *client.ProfileStatus, profiles []*client.ProfileStatus) {
+func getTshEnv() map[string]string {
+	env := map[string]string{}
+	envVars := []string{proxyEnvVar, clusterEnvVar, siteEnvVar, kubeClusterEnvVar, teleport.EnvKubeConfig}
```
Comment (r0mant) [inline tool/tsh/tsh.go:3181]: Can we move this into a global level variable that sits next to where these env vars are defined? Otherwise noone will know that they have to update it here as well if for example adding a new one.

**Review by r0mant — APPROVED** [review]

File: tool/tsh/tsh.go [hunk 6]
```diff
@@ -2951,30 +2958,52 @@ func onShow(cf *CLIConf) error {
...
+		if _, ok := env[clusterEnvVar]; ok {
+			cluster += fmt.Sprintf(" (%v)", clusterEnvVar)
+		} else if _, ok := env[siteEnvVar]; ok {
+			cluster += fmt.Sprintf(" (%v)", siteEnvVar)
+		}
+
+		// check if kube cluster env var is set and no cluster was selected by kube config
+		if _, ok := env[kubeClusterEnvVar]; ok && kubeCluster == "" {
+			kubeCluster = fmt.Sprintf("%v (%v)", p.KubernetesCluster, kubeClusterEnvVar)
+		}
```
[the remark this answers is not in the document]
Comment (GavinFrazar) [reply tool/tsh/tsh.go]: Added

**Comment by ravicious** [comment]
@GavinFrazar Could you backport this to v10? It'd be useful for Connect users.
