### PR TITLE
Fix file audit log rotation, fixes #2388

### LINKED ISSUE #2388: make teleport log naming convention easier for log aggregators
I followed https://gravitational.com/blog/shipping-ssh-logs-to-sumologic/ to configure sending ssh logs to sumologic. But instead of the sumologic/collector docker image, I used https://github.com/SumoLogic/fluentd-kubernetes-sumologic because it has already been used for kubernetes and containers logs.

The tutorial recommends using /var/lib/teleport/log/*.log as pathExpression to configure sumo sources. However when I configured the sumologic collector that way it started following every file in /var/lib/teleport/log/ (which was more than 100 files because we keep the logs for a long time).

I tried to configure fluentd to keep track of the latest log file only using the following configuration:
```
      <source>
        @type tail
        tag teleport
        path /mnt/teleport/%Y-%m-%d.*.log
        pos_file /mnt/pos/teleport.log.pos
        <parse>
          @type json
          time_key time
          time_type string
          time_format %Y-%m-%dT%H:%M:%SZ
        </parse>
      </source>
       <filter teleport.**>
        @type kubernetes_sumologic
        source_category teleport
        source_name teleport
      </filter>
```
where /mnt/teleport/ is a mount of /var/lib/gravity/site/teleport/log/.
The corresponding fluentd documentation can be found at https://docs.fluentd.org/v1.0/articles/in_tail

Here I ran into problems.

1. Despite having name 2018-11-01.00:00:00.log the file is created 12 hours before that time, and is rotated 12 hours after it. 
```
[root@ip-10-104-2-176 log]# head -1 2018-11-01.00:00:00.log
{"event":"user.login","method":"local","time":"2018-10-31T12:00:11Z","user":"opscenter@gravitational.io"}
[root@ip-10-104-2-176 log]# tail -1 2018-11-01.00:00:00.log
{"event":"user.login","method":"local","time":"2018-11-01T11:59:11Z","user":"opscenter@gravitational.io"}
```
2. The name of log files contains dates and times in UTC and doesn't respect local timezone set on the server.

These 2 issues cause fluentd to start reading the latest log file in 12 + local_timezone_difference_with_UTC hours which is a very big delay.

I wonder if it is possible to make this naming convention more predictable and easier to use for log aggregator software?

For instance, teleport could write current records to current.log or last.log, and rotate it to YYYY-mm-DD.00:00:00.log when it is time to rotate.

### PR DESCRIPTION
**Pull request by klizhentas**
This commit improves on-disk events log rotation:

* Previously, log rotation was not deterministic,
as logs could be rotated mid-day UTC, and events
from the same day could end up in different files.

This commit makes sure that logs are rotated
on the UTC boundary of the day, and log entries
from this day are located in the appropriate file,
e.g. 2019-02-09.00:00:00.log will contain all
event logs from 2019-02-09 day.

* To improve UX, additional symlink event.log
is located (by default in /var/lib/teleport/events.log)
and is pointing to the latest events log file.

### CODE REVIEW

File: lib/events/filelog.go [hunk 1]
```diff
@@ -60,9 +62,20 @@ func (cfg *FileLogConfig) CheckAndSetDefaults() error {
...
+	}
+	if !utils.IsDir(cfg.SymlinkDir) {
+		return trace.BadParameter("path %q does not exist or is not a directory", cfg.SymlinkDir)
+	}
 	if cfg.RotationPeriod == 0 {
 		cfg.RotationPeriod = defaults.LogRotationPeriod
 	}
+	// make sure that rotation period is a multiple of one day
+	rotationDays := cfg.RotationPeriod / (24 * time.Hour)
+	if cfg.RotationPeriod != (rotationDays * 24 * time.Hour) {
```
Comment (r0mant) [inline lib/events/filelog.go]: If you want to make sure that `cfg.RotationPeriod` is a multiple of "24 hours", you could just do:

```go
if cfg.RotationPeriod % (24 * time.Hour) == 0 { ... }
```

File: lib/events/filelog.go [hunk 2]
```diff
@@ -60,9 +62,20 @@ func (cfg *FileLogConfig) CheckAndSetDefaults() error {
...
+		return trace.BadParameter("rotation period should be expressed in multiples of a single day, got %v instead", cfg.RotationPeriod)
```
Comment (r0mant) [inline lib/events/filelog.go]: If this message is gonna be shown to a user, I would add an example (e.g. `24h`, `48h`), otherwise it might not be clear what "multiples of a single day" means.

Also, is that okay that this new restriction might cause teleport not to start after upgrade for users who have a "wrong" value in their config?

**Review by kontsevoy — APPROVED** [review]
LGTM

File: lib/events/filelog.go [hunk 3]
```diff
@@ -363,6 +395,12 @@ func (l *FileLog) matchingFiles(fromUTC, toUTC time.Time) ([]eventFile, error) {
 	return filtered, nil
 }
 
+// parseFileTimte parses file's timestamp encoded into name
```
Comment (r0mant) [inline lib/events/filelog.go]: Timte -> Time

**Review by r0mant — APPROVED** [review]

File: lib/events/filelog.go (hunk 1 above)
Comment (klizhentas) [reply lib/events/filelog.go]: great point!

File: lib/events/filelog.go (hunk 2 above)
Comment (klizhentas) [reply lib/events/filelog.go]: this value is not exposed in the config right now
