### PR TITLE
Fix flaky test `TestIntegrations/Disconnection/verify_that_lost_connections_to_auth_server_terminate_controlled_connections`

### LINKED ISSUE #13699: `TestIntegrations/Disconnection/verify_that_lost_connections_to_auth_server_terminate_controlled_connections` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/7b377a2f-27d4-4d2b-9d00-c4a891768780?project=ci-account
- v10 https://github.com/gravitational/teleport/actions/runs/4639027594/jobs/8209429583#step:6:1378

#### Relevant snippet

```
    integration_test.go:1325: 
        	Error Trace:	integration_test.go:1325
        	            				integration_test.go:1219
        	Error:      	Async error
        	Test:       	TestIntegrations/Disconnection/Test_6
        	Messages:   	expected EOF, ExitError, or nil, got ssh: could not start shell instead
```

### PR DESCRIPTION
**Pull request by Joerger**
Fixes https://github.com/gravitational/teleport/issues/13699

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -2170,25 +2170,15 @@ func testDisconnectScenarios(t *testing.T, suite *integrationTestSuite) {
...
-					case <-time.After(time.Millisecond * 100):
-					case <-ctx.Done():
-						return
-					}
-				}
-				require.NoError(t, err)
-				require.Len(t, sems, 1)
+					assert.NoError(t, err)
+					assert.Len(t, sems, 1)
+				}, time.Second, 100*time.Millisecond)
```
Comment (nklaassen) [inline integration/integration_test.go:2179]: If I'm reading this right, are we essentially just increasing this timeout from 600ms to 1 second? Is that enough?

Comment (Joerger) [reply integration/integration_test.go]: Yeah, I think 1 second is enough, but 2 seconds will be a safer bet. Updated.

**Review by nklaassen — APPROVED** [review]

**Review by camscale — APPROVED** [review]
