### PR TITLE
Fix coordinated omission bug

### LINKED ISSUE #4601: Coordinated omission bug
### Description

**What happened**:
When using the bench code for progressive load benchmarks, the benchmarks aren't working as they theoretically should. It seems like work is being produced faster than producer goroutines can run. The producer won't continue to the next iteration of its loop until something receives off the request channel. With the example input below.

The error is waiting for the threads to finish and not running all of the measures due to  the block and exiting because of the timeout (duration).

Example:  
```
tsh bench  --rate 100 --duration 10s localhost ls -l /


* Requests originated: 244
* Requests failed: 3
* Last error: several requests hang: timeout waiting for 10 threads to finish

Histogram

Percentile Duration 
---------- -------- 
25         20 ms    
50         21 ms    
75         24 ms    
90         30 ms    
95         43 ms    
99         68 ms    
100        82 ms    

```

**What you expected to happen**:
Requests originated should be 1000 in 10s if rate is 100 for 10s 

As you can see from the latency profile below, it is not recording 1000 measures. Also it says the last request is ~82ms when it should be closer to ~2500ms because it should be recording response time, not service time.

Screenshot from 2020-10-21 12-12-43

### PR DESCRIPTION
**Pull request by quinqu**
# Purpose 

@wadells surfaced a coordinated omission bug in the code. The cause of coordinated omission was each thread would send a request, wait for a response, and then go on. This makes the response time longer, however the original bench code was only showing the service time. We care about the response time more because this is the wait time our users experience. 

# Implementation 

Each measure is now spawned in its own goroutine, which is described as an open system model, so there is no need for threads. This means there is no blocking so the program can create needed rps. I added an extra time `ResponseStart` to record the creation of each measure and a `ServiceStart` to record the start of the execution and these two fields are used to catch coordinated omission. 

For the output when using the `tsh bench` in the CLI to run benchmarks, there is now an extra column that shows the Response Duration 

Example: `tsh bench --rate=50 --duration=10s localhost ls -l /`
```
* Requests originated: 500
* Requests failed: 0

Histogram

Percentile Response Duration Service Duration 
---------- ----------------- ---------------- 
25         17 ms             17 ms            
50         18 ms             17 ms            
75         18 ms             18 ms            
90         19 ms             19 ms            
95         19 ms             19 ms            
99         22 ms             22 ms            
100        35 ms             35 ms            

```

From running `examples/bench/example.go`, this is now the output: 

```
Benchmark #0
Duration: 1m40.032304861s // 10rps for at least 30s until 1000 measures -> ~100s
Requests Originated: 1000
Requests Failed: 0
Benchmark #1
Duration: 50.059115391s // 20rps for at least 30s until 1000 measures -> ~50s
Requests Originated: 1000
Requests Failed: 0
Benchmark #2
Duration: 33.349786192s // 30rps for at least 30s until 1000 measures -> ~33s
Requests Originated: 1000
Requests Failed: 0
Benchmark #3
Duration: 30.017707877s
Requests Originated: 1200 // 40rps for at least 30s until 1000 measures -> ~30s
Requests Failed: 0
Benchmark #4 // 1000 measures in 40 seconds ~25rps should be 50 but overloaded
Duration: 40.360542117s
Requests Originated: 1000 // should be 50rps for at least 30s until 1000 measures -> 30s
Requests Failed: 50
```
fixes #4601

### CODE REVIEW

File: lib/benchmark/bench.go [hunk 1]
```diff
@@ -0,0 +1,225 @@
...
+	ResponseHistogram *hdrhistogram.Histogram
+	//ServiceHistogram is the duration of service histogram
+	ServiceHistogram *hdrhistogram.Histogram
+	// LastError contains last recorded error
+	LastError error
+	// Duration it takes for the whole benchmark to run
+	Duration time.Duration
+}
+
+//
```
Comment (klizhentas) [inline lib/benchmark/bench.go:70]: extra line

File: lib/benchmark/bench.go [hunk 2]
```diff
@@ -0,0 +1,225 @@
...
+	result.ServiceHistogram = hdrhistogram.New(MinValue, MaxValue, SignificantFigures)
+	results := make([]*benchMeasure, 0, c.MinimumMeasurements)
+	statusTicker := time.NewTicker(1 * time.Second)
+	timeElapsed := false
+	start := time.Now()
+	for {
+		if c.MinimumWindow <= time.Since(start) {
+			timeElapsed = true
+		}
+		select {
```
Comment (klizhentas) [inline lib/benchmark/bench.go:125]: nit: seems like formatting a bit off?

File: lib/benchmark/bench.go [hunk 3]
```diff
@@ -0,0 +1,225 @@
...
+
+		m.Error = m.client.SSH(context.TODO(), nil, false)
+		m.End = time.Now()
+		return
+	}
+	config := m.client.Config
+	client, err := client.NewClient(&config)
+	reader, writer := io.Pipe()
+	client.Stdin = reader
+	out := &bytes.Buffer{}
```
Comment (klizhentas) [inline lib/benchmark/bench.go:209]: let's use `utils.SyncBuffer` to avoid data races on concurrent writes to `Stdout` and `Stderr`

File: lib/benchmark/benchmark.go [hunk 4]
```diff
@@ -0,0 +1,111 @@
+package benchmark
```
Comment (klizhentas) [inline lib/benchmark/benchmark.go:1]: missing license header

File: lib/benchmark/benchmark.go [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+type Generator interface {
+	// Generate advances the Generator to the next generation.
+	// It returns false when the generator no longer has configurations to run.
+	Generate() bool
+	// GetBenchmark returns the benchmark config for the current generation.
+	// If called after Generate() returns false, this will result in an error.
+	GetBenchmark() (context.Context, Config, error)
+	// Benchmark runs the benchmark of receiver type
+	// return an array of Results that contain information about the generations
+	Benchmark([]string, *client.TeleportClient) ([]*Result, error)
```
Comment (klizhentas) [inline lib/benchmark/benchmark.go:32]: pass context as a first argument to handle cancellations

File: lib/benchmark/benchmark.go [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+// Run is used to run the benchmarks, it is given a generator, command to run,
+// a host, host login, and proxy. If host login or proxy is an empty string, it will
+// use the default login
+func Run(cnf interface{}, cmd, host, login, proxy string) ([]Result, error) {
```
Comment (klizhentas) [inline lib/benchmark/benchmark.go:38]: Let's pass the context here too

File: lib/benchmark/benchmark.go [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+	if err != nil {
+		return nil, err
+	}
+	logrus.SetLevel(logrus.ErrorLevel)
+	switch c := cnf.(type) {
+	case *Linear:
+		return c.Benchmark(context.Background(), cmd, tc)
+
+	}
+	return nil, errors.New("Invalid generator, not of type Linear")
```
Comment (klizhentas) [inline lib/benchmark/benchmark.go:49]: Let's not capitalize error strings following our [Go code guidelines](https://github.com/golang/go/wiki/CodeReviewComments#error-strings)

Comment (klizhentas) [inline lib/benchmark/benchmark.go:49]: Let's use `trace` package here and in other parts too `return nil, trace.BadParameter()`

File: lib/benchmark/benchmark.go [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+	Benchmark([]string, *client.TeleportClient) ([]*Result, error)
+}
+
+// Run is used to run the benchmarks, it is given a generator, command to run,
+// a host, host login, and proxy. If host login or proxy is an empty string, it will
+// use the default login
+func Run(cnf interface{}, cmd, host, login, proxy string) ([]Result, error) {
+	tc, err := makeTeleportClient(host, login, proxy)
+	if err != nil {
+		return nil, err
```
Comment (klizhentas) [inline lib/benchmark/benchmark.go:41]: `trace.Wrap(err)`

File: lib/benchmark/linear.go [hunk 9]
```diff
@@ -0,0 +1,75 @@
+package benchmark
```
Comment (klizhentas) [inline lib/benchmark/linear.go:1]: missing header comment

File: lib/benchmark/linear.go [hunk 10]
```diff
@@ -0,0 +1,75 @@
...
+	var result Result
+	var results []Result
+	c := strings.Split(cmd, " ")
+	lg.config.Command = c
+	sleep := false
+
+	for lg.Generate() {
+		// artificial pause between generations to allow remote state to pause
+		if sleep {
+			time.Sleep(PauseTimeBetweenBenchmarks)
```
Comment (klizhentas) [inline lib/benchmark/linear.go:60]: `time.Sleep` does not allow to cancel via context, instead let's use:

```go
select {
   case <- time.After(...)
   case <- ctx.Done():
      /// operation cancelled
      return trace.ConnectionProblem(ctx.Err(), "context canceled or timed out")
}```

File: lib/benchmark/linear.go [hunk 11]
```diff
@@ -0,0 +1,75 @@
...
+		benchmarkC, err := lg.GetBenchmark()
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
+		result, err = benchmarkC.Benchmark(context.TODO(), tc)
+		if err != nil {
+			return results, trace.Wrap(err)
+		}
+		results = append(results, result)
+		fmt.Printf("current generation requests: %v, duration: %v\n", result.RequestsOriginated, result.Duration)
```
Comment (klizhentas) [inline lib/benchmark/linear.go:71]: In console messages let's use full sentence format, with capital letter and ending with .

File: lib/benchmark/linear_test.go [hunk 12]
```diff
@@ -0,0 +1,211 @@
...
+
+import (
+	"testing"
+	"time"
+
+	"github.com/google/go-cmp/cmp"
+	"github.com/stretchr/testify/assert"
+)
+
+func TestGenerate(t *testing.T) {
```
Comment (klizhentas) [inline lib/benchmark/linear_test.go:11]: props for test

File: lib/benchmark/linear_test.go [hunk 13]
```diff
@@ -0,0 +1,211 @@
+package benchmark
+
+import (
+	"testing"
+	"time"
+
+	"github.com/google/go-cmp/cmp"
+	"github.com/stretchr/testify/assert"
```
Comment (klizhentas) [inline lib/benchmark/linear_test.go:8]: let's switch to `testify/require` that stops the test in flight

File: lib/benchmark/linear_test.go [hunk 14]
```diff
@@ -0,0 +1,211 @@
...
+		LowerBound:          10,
+		UpperBound:          50,
+		Step:                10,
+		MinimumMeasurements: 1000,
+		MinimumWindow:       d,
+		config:              initial,
+	}
+	// First generation
+	res := linearConfig.Generate()
+	if res != true {
```
Comment (klizhentas) [inline lib/benchmark/linear_test.go:32]: `require.True(t, "message")`

File: lib/benchmark/linear_test.go [hunk 15]
```diff
@@ -0,0 +1,211 @@
...
+	res = linearConfig.Generate()
+	if res != true {
+		t.Errorf("failed to generate #3 generation")
+	}
+
+	bm, err = linearConfig.GetBenchmark()
+	if err != nil {
+		t.Errorf("failed to get current benchmark")
+	}
+	expected.Rate = 30
```
Comment (klizhentas) [inline lib/benchmark/linear_test.go:68]: Can you replace this with loop?

File: lib/benchmark/linear_test.go [hunk 16]
```diff
@@ -0,0 +1,211 @@
...
+		t.Errorf("expected false, got true")
+	}
+
+	_, err = linearConfig.GetBenchmark()
+	if err == nil {
+		t.Errorf("generating more benchmarks than expected")
+	}
+}
+
+func TestGenerateNotEvenMultiple(t *testing.T) {
```
Comment (klizhentas) [inline lib/benchmark/linear_test.go:109]: Same here - could you use table driven tests for this too?

https://github.com/golang/go/wiki/TableDrivenTests

**Review by klizhentas — COMMENTED** [review]
Did a first quick pass, will do in depth dive of the omission bug logic a bit later this week. Great progress!
Take a look at passing and using contexts instead of `context.TODO()` and table driven tests 

 @quinqu

File: lib/benchmark/bench.go [hunk 17]
```diff
@@ -59,175 +57,169 @@ type Result struct {
...
 
-type benchmarkThread struct {
-	id          int
-	ctx         context.Context
-	client      *client.TeleportClient
-	command     []string
-	interactive bool
-	receiveC    chan benchMeasure
-	sendC       chan benchMeasure
+func worker(ctx context.Context, m *benchMeasure, send chan<- *benchMeasure) {
```
Comment (wadells) [inline lib/benchmark/bench.go:183]: the "*er" naming pattern (e.g. worker, reader, writer) is typically used for interfaces/structs.  I'd recommend an imperative verbe instead of a noun. (e.g. work, run, execute).

File: lib/benchmark/bench.go [hunk 18]
```diff
@@ -59,175 +57,169 @@ type Result struct {
...
+	if !m.interactive {
 		// do not use parent context that will cancel in flight requests
 		// because we give test some time to gracefully wrap up
 		// the in-flight connections to avoid extra errors
-		measure.Error = b.client.SSH(context.TODO(), nil, false)
-		measure.End = time.Now()
-		b.sendMeasure(measure)
+
+		m.Error = m.client.SSH(context.TODO(), nil, false)
+		m.End = time.Now()
```
Comment (wadells) [inline lib/benchmark/bench.go:202]: `m.End` is set outside of `execute` (line 176).  I don't think we need to set it inside of `execute` as well -- it will just be overwritten.

File: lib/benchmark/bench.go [hunk 19]
```diff
@@ -59,175 +57,169 @@ type Result struct {
...
 	client.Stdin = reader
 	out := &bytes.Buffer{}
 	client.Stdout = out
 	client.Stderr = out
 	if err != nil {
-		measure.Error = err
-		measure.End = time.Now()
-		b.sendMeasure(measure)
+		m.Error = err
+		m.End = time.Now()
```
Comment (wadells) [inline lib/benchmark/bench.go:214]: See remark about setting `m.End` inside `execute`.

File: lib/benchmark/bench.go [hunk 20]
```diff
@@ -59,175 +57,169 @@ type Result struct {
...
 		return
 	}
 	done := make(chan bool)
 	go func() {
-		measure.Error = b.client.SSH(b.ctx, nil, false)
-		measure.End = time.Now()
-		b.sendMeasure(measure)
+		m.Error = m.client.SSH(m.ctx, nil, false)
+		m.End = time.Now()
```
Comment (wadells) [inline lib/benchmark/bench.go:220]: See remark about setting `m.End` inside `execute`.

File: tool/tsh/tsh.go [hunk 21]
```diff
@@ -316,7 +314,6 @@ func Run(args []string) {
 	bench.Arg("[user@]host", "Remote hostname and the login to use").Required().StringVar(&cf.UserHost)
 	bench.Arg("command", "Command to execute on a remote host").Required().StringsVar(&cf.RemoteCommand)
 	bench.Flag("port", "SSH port on a remote host").Short('p').Int32Var(&cf.NodePort)
-	bench.Flag("threads", "Concurrent threads to run").Default("10").IntVar(&cf.BenchThreads)
```
Comment (wadells) [inline tool/tsh/tsh.go:320]: This is a backwards incompatible change (removing a flag from the CLI as well as the ability to limit the number of max requests open at a moment).  SemVer says backwards incompatible changes should only go out in Major releases (e.g. 5.0). Do we care about this regression?

File: lib/benchmark/bench.go [hunk 22]
```diff
@@ -59,175 +57,169 @@ type Result struct {
...
-			id:          i,
-			ctx:         ctx,
-			client:      tc,
-			command:     c.Command,
-			interactive: c.Interactive,
-			receiveC:    requestC,
-			sendC:       responseC,
+	var delay time.Duration = 0
+
+	ctx, cancel := context.WithCancel(context.Background())
```
Comment (wadells) [inline lib/benchmark/bench.go:81]: Should this inherit from `ctx context.Context` passed in as the first parameter to the `Benchmark` function?

File: lib/benchmark/bench.go [hunk 23]
```diff
@@ -59,175 +57,169 @@ type Result struct {
...
+	go func() {
+		interval := time.Duration(float64(1) / float64(c.Rate) * float64(time.Second))
+		ticker := time.NewTicker(interval)
+		defer ticker.Stop()
+		start := time.Now()
+		for {
+			select {
+			case <-ticker.C:
+				delay = delay + interval
+				t := start.Add(delay)
```
Comment (wadells) [inline lib/benchmark/bench.go:96]: I think a comment about why you choose `t := start.Add(delay)` wouldn't go awry here.  Particularly getting at why this is preferred to `t := time.Now()`.  It may be obvious to those who have thought about coordinated omission, but I'd guess it isn't intuitive to folks new to the codebase.

**Review by wadells — COMMENTED** [review]
I only reviewed https://github.com/gravitational/teleport/pull/4643/files/9ad2b58c252ee650464075e569b16b5d202603ab..72c1b3aae2957cd182ca273182a81bb4bc81fcbc, as the rest is already covered under #4588.  I'd recommend that get merged first, to keep more bite-sized commit history.

File: examples/bench/README.md [hunk 24]
```diff
@@ -0,0 +1,12 @@
...
+
+
+## Linear Benchmark Generator
+
+### What is this
+A linear generator generates benchmarks between a lower and upper bound using a fixed step as configured by the user. 
+
+
+### Use case
+Linear generators are useful when benchmarking setups with understood performance profiles or generating graphs for user-facing materials.
```
Comment (benarent) [inline examples/bench/README.md:12]: Can you add in more instructions for how to use `tsh bench` and how someone can create graphs etc.

File: examples/bench/README.md [hunk 25]
```diff
@@ -0,0 +1,12 @@
+
+# Tsh Bench
+
+
```
Comment (benarent) [inline examples/bench/README.md:4]:
```suggestion
# Tsh Bench
```

File: lib/benchmark/bench.go (hunk 3 above)
Comment (quinqu) [reply lib/benchmark/bench.go:209]: I can't find docs for `utils.SyncBuffer`, did you happen to mean a different type of buffer? Alternatively, we can use bytes.Buffer, but make it concurrent safe and add a mutex

**Comment by quinqu** [comment]
Here are the newer changes to be reviewed:
https://github.com/gravitational/teleport/pull/4643/files/9ad2b58c252ee650464075e569b16b5d202603ab..4eb5d81814f1167387eda62453ea9937e1570e32

File: lib/benchmark/bench.go [hunk 26]
```diff
@@ -74,160 +76,140 @@ func (c *Config) Benchmark(ctx context.Context, tc *client.TeleportClient) (Resu
...
-	id          int
-	ctx         context.Context
-	client      *client.TeleportClient
-	command     []string
-	interactive bool
-	receiveC    chan benchMeasure
-	sendC       chan benchMeasure
+func work(ctx context.Context, m *benchMeasure, send chan<- *benchMeasure) {
+	m.ServiceStart = time.Now()
+	execute(m)
```
Comment (wadells) [inline lib/benchmark/bench.go:180]: Perhaps consider having `execute` return an error (potentially nil) and then having `m` pass by value instead of by reference.  That would consolidate all of the modification to `m` into this this function, and let `execute` be more pure.

File: lib/benchmark/linear.go [hunk 27]
```diff
@@ -57,21 +69,24 @@ func (lg *Linear) Benchmark(ctx context.Context, cmd string, tc *client.Teleport
...
 		}
-		result, err = benchmarkC.Benchmark(context.TODO(), tc)
+		result, err = benchmarkC.Benchmark(ctx, tc)
 		if err != nil {
 			return results, trace.Wrap(err)
 		}
 		results = append(results, result)
-		fmt.Printf("current generation requests: %v, duration: %v\n", result.RequestsOriginated, result.Duration)
 		sleep = true
+		fmt.Printf("The current generation made %v requests in %v.\n", result.RequestsOriginated, result.Duration)
```
Comment (wadells) [inline lib/benchmark/linear.go:89]: This is a library function.  I'd use a log instead of a fmt.print here.

File: tool/tsh/tsh.go [hunk 28]
```diff
@@ -972,7 +969,7 @@ func onBenchmark(cf *CLIConf) {
 	fmt.Printf("\n")
 
 	if cf.BenchExport {
-		path, err := benchmark.ExportLatencyProfile(cf.BenchExportPath, result.Histogram, cf.BenchTicks, cf.BenchValueScale)
+		path, err := benchmark.ExportLatencyProfile(cf.BenchExportPath, result.ServiceHistogram, cf.BenchTicks, cf.BenchValueScale)
```
Comment (wadells) [inline tool/tsh/tsh.go:972]: Do we want the response histogram here?  Admittedly, with the coordinated omission fixed, they should be more or less the same.

Better yet, why not export both -- as the plotter can accept different files.  That way users can do an eyeball check to make sure that response & service look similar.

File: examples/bench/README.md [hunk 29]
```diff
@@ -0,0 +1,59 @@
...
+## Exporting Latency Profile 
+
+Run `tsh bench` as usual, but use the `--export` flag to export. Use `--path` to specify a directory to save the file to. If the path is not specified, the file will be saved to your current working directory. 
+
+Example:  
+
+`tsh bench --export --rate 100 --duration 10s localhost ls -l /` 
+
+The file its saved in the following format: latency_profile_2006-10-27_15:04:05.txt
```
Comment (wadells) [inline examples/bench/README.md:26]: If you update the logic to export both service & response time series, make sure to update the instructions here to explain which is which & how to plot both.

File: examples/bench/README.md [hunk 30]
```diff
@@ -1,12 +1,59 @@
...
+		LowerBound:          10,
+		UpperBound:          50,
+		Step:                10,
+		MinimumMeasurements: 1000,
+		MinimumWindow:       30 * time.Second,
+	}
+
+```
+
+_To see a full script example, go to `example.go` in `examples/bench`_
```
[the remark this answers is not in the document]
Comment (quinqu) [reply examples/bench/README.md:59]: The underscores are markdown for italicizing

[the remark this answers is not in the document]
Comment (wadells) [reply examples/bench/README.md:59]: Whoops, missed the leading one.

File: tool/tsh/tsh.go (hunk 28 above)
Comment (quinqu) [reply tool/tsh/tsh.go:972]: I think exporting both is a good idea.

**Comment by awly** [comment]
@quinqu what the commit range to review now?

**Comment by quinqu** [comment]
I just updated the branch, here are the newest changes https://github.com/gravitational/teleport/pull/4643/commits/44a70906f6394333c0950f35d58385e755a98867

**Comment by quinqu** [comment]
Sorry, posted wrong link last time, here are the new changes https://github.com/gravitational/teleport/pull/4643/files/a95b155359b2e9edfadd99ab3e09b1d2c587997f..12df05c302f13e6ff138a5e3a2928840cc0fa2f1

**Comment by quinqu** [comment]
I removed threads and initially I was going to display and export both service and response latency profiles (if specified), but decided against so because there is a small chance they will ever differ, now that the bench code runs requests (goroutines) independent of each other. It just seemed a bit redundant to keep both. But if you guys think it's a good idea to keep both, let me know.

**Review by fspmarshall — APPROVED** [review]

**Review by benarent — APPROVED** [review]

**Comment by quinqu** [comment]
https://github.com/gravitational/teleport/pull/4643/files/bc96b09daa6ddb6d42eb181d2d3ba8c4e1f27580..379732f7bd95be869ea7abec288f9c3ce444462f

File: lib/benchmark/benchmark.go [hunk 31]
```diff
@@ -149,157 +157,133 @@ func (c *Config) Benchmark(ctx context.Context, tc *client.TeleportClient) (Resu
...
 
-func produceMeasures(ctx context.Context, rate int, c chan<- benchMeasure) {
-	interval := time.Duration(1 / float64(rate) * float64(time.Second))
-	ticker := time.NewTicker(interval)
-	defer ticker.Stop()
+type benchMeasure struct {
+	ResponseStart time.Time
+	End           time.Time
+	Error         error
+	ctx           context.Context
```
Comment (awly) [inline lib/benchmark/benchmark.go:230]: this seems to be unused
and context should be always passed as a separate parameter: https://github.com/golang/go/wiki/CodeReviewComments#contexts

File: lib/benchmark/benchmark.go [hunk 32]
```diff
@@ -149,157 +157,133 @@ func (c *Config) Benchmark(ctx context.Context, tc *client.TeleportClient) (Resu
...
 		// the in-flight connections to avoid extra errors
-		measure.Error = b.client.SSH(context.TODO(), nil, false)
-		measure.End = time.Now()
-		b.sendMeasure(measure)
-		return
+		err := m.client.SSH(context.TODO(), nil, false)
+		if err != nil {
+			return err
+		}
+		return nil
```
Comment (awly) [inline lib/benchmark/benchmark.go:269]:
```suggestion
		return m.client.SSH(context.TODO(), nil, false)
```

File: lib/benchmark/benchmark.go [hunk 33]
```diff
@@ -149,157 +157,133 @@ func (c *Config) Benchmark(ctx context.Context, tc *client.TeleportClient) (Resu
...
 	}
-	config := b.client.Config
+	config := m.client.Config
 	client, err := client.NewClient(&config)
```
Comment (awly) [inline lib/benchmark/benchmark.go:272]: handle this error right after `client.NewClient`

File: lib/benchmark/benchmark.go [hunk 34]
```diff
@@ -149,157 +157,133 @@ func (c *Config) Benchmark(ctx context.Context, tc *client.TeleportClient) (Resu
...
-	if err != nil {
-		measure.Error = err
-		measure.End = time.Now()
-		b.sendMeasure(measure)
-		return
-	}
 	reader, writer := io.Pipe()
```
Comment (awly) [inline lib/benchmark/benchmark.go:273]: close both ends of the pipe

File: tool/tsh/tsh.go (hunk 21 above)
Comment (awly) [reply tool/tsh/tsh.go:332]: AFAIK this command is for internal use only.
It definitely shouldn't be depended on by anybody for production use.
Should be safe to remove.

File: lib/benchmark/benchmark.go [hunk 35]
```diff
@@ -149,157 +157,133 @@ func (c *Config) Benchmark(ctx context.Context, tc *client.TeleportClient) (Resu
...
+		ticker := time.NewTicker(interval)
+		defer ticker.Stop()
+		start := time.Now()
+		for {
+			select {
+			case <-ticker.C:
+				// ticker makes its first tick after the given duration, not immediately
+				// this sets the send measure ResponseStart time accurately
+				delay = delay + interval
+				t := start.Add(delay)
```
[the remark this answers is not in the document]
Comment (wadells) [reply lib/benchmark/benchmark.go:178]: If this producer loop blocks for longer than the tick rate for any reason (e.g. the `requestsC <- measure` send) `time.Now()` will no longer be accurate -- resulting in coordinated omission.

Thus we prefer using math to calculate start time as currently equivalent, and more future proof. E.g. if we add back in `--threads` or some logic to handle throttling/back-pressure based on clientside resource (fh?) exhaustion, the math based approach remains correct.

Based on your comment, I worry that this subtlety may be lost on future maintainers, as response vs service time is not as explicitly called out anymore.

[the remark this answers is not in the document]
Comment (awly) [reply lib/benchmark/benchmark.go:178]: ahh, in that case you can use the value from `ticker.C`, which emits `time.Time` value for when the tick was emitted

[the remark this answers is not in the document]
Comment (wadells) [reply lib/benchmark/benchmark.go:178]: `ticker.C` will still result in coordinated omission.  Per the [docs](https://golang.org/pkg/time/#NewTicker):

"[Ticker] adjusts the intervals or drops ticks to make up for slow receivers."

For a brief illustration:

```
$ cat tickertest.go   
package main

import (
        "context"
        "log"
        "time"
)

func main() {
        ctx, cancel := context.WithCancel(context.TODO())
        defer cancel()
        go func() {
                time.Sleep(5 * time.Second)
                cancel()
        }()
        go func() {
                ticker := time.NewTicker(250 * time.Millisecond)
                for {
                        select {
                        case t := <-ticker.C:
                                log.Println("tick at ", t)
                                time.Sleep(1 * time.Second)
                        case <-ctx.Done():
                                return
                        }
                }
        }()
        <-ctx.Done()
}
$ go run tickertest.go
2020/11/30 12:21:41 tick at  2020-11-30 12:21:41.879970194 -0800 PST m=+0.250283039
2020/11/30 12:21:42 tick at  2020-11-30 12:21:42.129849762 -0800 PST m=+0.500162518
2020/11/30 12:21:43 tick at  2020-11-30 12:21:43.130051902 -0800 PST m=+1.500364734
2020/11/30 12:21:44 tick at  2020-11-30 12:21:44.130045267 -0800 PST m=+2.500358106
2020/11/30 12:21:45 tick at  2020-11-30 12:21:45.12999193 -0800 PST m=+3.500304768
$
```

[the remark this answers is not in the document]
Comment (quinqu) [reply lib/benchmark/benchmark.go:178]: We could do something like this and there wouldn't be coordinated omission, but it's essentuially the same. It sounds like we really want to use ticker.C though 

```
	go func() {
		interval := time.Duration(1 / float64(c.Rate) * float64(time.Second))
		ticker := time.NewTicker(interval)
		defer ticker.Stop()
		for {
			select {
			case <-ticker.C:
				// ticker makes its first tick after the given duration, not immediately
				// this sets the send measure ResponseStart time accurately
				delay = delay + interval
				tickerTime := <-ticker.C
				t := tickerTime.Add(-delay)
				measure := benchMeasure{
					ResponseStart: t,
					command:       c.Command,
					client:        tc,
					interactive:   c.Interactive,
				}
				go work(ctx, measure, resultC)
			case <-ctx.Done():
				close(requestsC)
				return
			}
		}
	}()
```

**Comment by quinqu** [comment]
I tested it out with the newest change and didn't see anything bad, but I can keep it in

File: lib/benchmark/benchmark.go (hunk 32 above)
Comment (quinqu) [reply lib/benchmark/benchmark.go:252]: I think we should keep it at is (I am going to revert it back because I made the change) because we still need to execute the command and exit out of the session with `writer.Write([]byte(strings.Join(m.command, " ") + "\r\nexit\r\n"))`. And it doesn't make sense to write the command before we ssh.

File: lib/benchmark/benchmark.go (hunk 35 above)
[the remark this answers is not in the document]
Comment (awly) [reply lib/benchmark/benchmark.go:179]: Hmm... if you miss ticker events, aren't you then mis-representing your RPS?

For example: your rate is 10 rps, and you miss 1 ticker event (due to 1 slow iteration). Your actual RPS is 9 (for that second) and the calculated start time for all measurements after the missed event are increased by 100ms.
If you miss 1 event every second, you start accumulating this calculated start time gap by 100ms every 1s.
After 10s, even if everything returns to normal with no server slowness or missed events, all your measurements are increased by 1s because of 10 missed ticks.

I think there are 2 possible approaches:
1. detect missed ticks (by checking elapsed time since last tick) and mark those measurements as failed
2. make the ticker loop extremely fast, independent of server response time so that ticks are never dropped

The 2nd option is what you already have: each iteration creates a measurement object and kicks of a goroutine with it. This should consistently run fast and not cause ticks to be missed.

Please let me know if I'm mis-understanding coordinated omission though :)

File: lib/benchmark/benchmark.go (hunk 32 above)
Comment (awly) [reply lib/benchmark/benchmark.go:252]: Hmm, `writer.Write` is only for interactive commands.
It looks like this code is not calling any command here at all. This line should be something like:
```
return m.client.SSH(context.TODO(), m.command, false)
```

File: lib/benchmark/benchmark.go (hunk 35 above)
[the remark this answers is not in the document]
Comment (awly) [reply lib/benchmark/benchmark.go:179]: https://play.golang.org/p/fLMrlvh222b illustrates what I mean by "accumulating start time gap"

File: lib/benchmark/benchmark.go (hunk 32 above)
Comment (quinqu) [reply lib/benchmark/benchmark.go:252]: I am dealing with non-interactive sessions on lines 244-253. So if we get passed the conditional `if !m.interative { ... }` then we will be dealing with interactive sessions.

File: lib/benchmark/benchmark.go (hunk 35 above)
[the remark this answers is not in the document]
Comment (quinqu) [reply lib/benchmark/benchmark.go:179]: So coordinated omission just means you are not correctly recording response time. There aren't any ticks that are being missed, I am just simply starting them when they are mathematically supposed to be started. 

In your example, you are adding delay. I am subtracting it when using ticker in the example above. But your right, what I already have works cause it is an open system and does not depend on anything else

[the remark this answers is not in the document]
Comment (wadells) [reply lib/benchmark/benchmark.go:179]: You're right: if the current implementation falls behind (it shouldn't :crossed_fingers:) it would never catch up. At best it would return back to the expected RPS with a fixed delay. However, in the event this happens, is better to measure & report on that delay -- that will show up as a red flag to investigate.

> 2. make the ticker loop extremely fast, independent of server response time so that ticks are never dropped

I agree that we prefer the current implementation.  Downsides:

 - OS contention (I think @quinqu was hitting filehandle/socket limits when pushing `tsh bench` to demonstrate coordinated omission)
 - goroutines become a poor unbounded & unordered queue, and will pile up if the response rate < request rate, and requests aren't failing for other reasons (above OS limits, teleport backpressure).  We're creating an expected leak.  Not that testing RPS >> limits is a particular useful perf test to run... but it is expected during exploratory/redlines testing.

Back to the original question that started this thread: Should we record the scheduled start of the request or the observed start of the request?  I personally prefer both.  The scheduled start time should be used for response time latency calculation.  The observed time can be used to measure service time (which should always be equal to response time in a system without backpressure).

If we only record one, scheduled start & response time is better, as service time ignores throttling.  At best `time.Now()` is equivalent to `start + delay`. At its worst using `time.Now()` obscures perf issues.

[the remark this answers is not in the document]
Comment (quinqu) [reply lib/benchmark/benchmark.go:179]: I see what you mean by your example though

[the remark this answers is not in the document]
Comment (wadells) [reply lib/benchmark/benchmark.go:179]: > https://play.golang.org/p/fLMrlvh222b illustrates what I mean by "accumulating start time gap"

This nicely illustrates the difference between service time & response time.  In your exampe the last request has 5ms service time and 105ms response time.  Coordinated omission is the claim that service time is response time.

[the remark this answers is not in the document]
Comment (wadells) [reply lib/benchmark/benchmark.go:179]: P.S.  This is a lot of back & forth for a PR comment.  If we still need to hash out a consensus, we might do have a video call to get on the same page.

[the remark this answers is not in the document]
Comment (awly) [reply lib/benchmark/benchmark.go:179]: I'm okay with any solution you pick.
Just wanted to point out that manually calculating tick times seemed redundant and bug-prone.

As for unbounded goroutine leak - there should be some hard timeout on all commands (e.g. 30s or something longer). But even without it, it's ok since this is a client-side tool and not a backend system stealing resources from other critical software.

File: lib/benchmark/benchmark.go (hunk 32 above)
Comment (awly) [reply lib/benchmark/benchmark.go:252]: Hmm, maybe github is showing us different code spans.
I highlighted this comment on the block (244-253):
```
	if !m.interactive {
		// do not use parent context that will cancel in flight requests
		// because we give test some time to gracefully wrap up
		// the in-flight connections to avoid extra errors
		err := m.client.SSH(context.TODO(), nil, false)
		if err != nil {
			return err
		}
		return nil
	}
```
which is for non-interactive sessions.

The original comment was that it's equivalent to:
```
	if !m.interactive {
		// do not use parent context that will cancel in flight requests
		// because we give test some time to gracefully wrap up
		// the in-flight connections to avoid extra errors
		return m.client.SSH(context.TODO(), nil, false)
	}
```

But I also notice that the 2nd parameter to `m.client.SSH` for non-interactive sessions is `nil`, but should be `m.command`.
Or is the command for non-interactive sessions passed somewhere else to `m.client`?

Comment (quinqu) [reply lib/benchmark/benchmark.go:252]: Oh yes, I only saw a portion of the code span, that is my bad. You're right, returning like you suggested above will work

File: lib/benchmark/benchmark.go (hunk 35 above)
[the remark this answers is not in the document]
Comment (quinqu) [reply lib/benchmark/benchmark.go:179]: To me, it makes sense to keep just response time because that is the only thing we _should_ care about. Maybe a feature (down the line) could be added to show both if specified, but only response by default

[the remark this answers is not in the document]
Comment (quinqu) [reply lib/benchmark/benchmark.go:179]: I think if we were to keep both and a user didn't know the difference, service time could be valued over response time since it "looks" better, that is just my thought process.

File: lib/benchmark/benchmark.go [hunk 36]
```diff
@@ -149,157 +158,113 @@ func (c *Config) Benchmark(ctx context.Context, tc *client.TeleportClient) (Resu
...
-			b.sendMeasure(benchMeasure{
-				ThreadCompleted: true,
-			})
-			return
-		}
+	err = m.client.SSH(context.TODO(), nil, false)
+	if err != nil {
+		return err
 	}
+	writer.Write([]byte(strings.Join(m.command, " ") + "\r\nexit\r\n"))
```
Comment (awly) [inline lib/benchmark/benchmark.go:266]: Maybe for a future PR: check the error from `Write`, to make sure we actually successfully write the command out.

Also, I start to suspect that we're not actually running an interactive shell command at all.
`m.client.SSH` looks like it should block until the interactive session is over. So we don't get to write the command at all - session is over once `m.client.SSH` returns.

If I'm right, we should replace the `io.Pipe` with a simple `bytes.Reader` containing the command.
If I'm wrong, it's unclear when the SSH session ends, since we're not deferring any cleanup code matching `m.client.SSH`.

**Review by awly — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]
