### PR TITLE
Fix flaky test `TestImportantModalSemaphore`

### LINKED ISSUE #29879: `TestImportantModalSemaphore` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/5731165515/job/15531498916

#### Relevant snippet

```
=== FAIL: lib/teleterm/daemon TestImportantModalSemaphore (0.20s)
    daemon_test.go:536: important modal operations failed to acquire unclaimed semaphore
    daemon_test.go:547: important modal operations failed to acquire unclaimed semaphore
    daemon_test.go:554: 
        	Error Trace:	/__w/teleport/teleport/lib/teleterm/daemon/daemon_test.go:554
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestImportantModalSemaphore
        	Messages:   	Unexpected number of calls to service.Relogin
```

### PR DESCRIPTION
**Pull request by Joerger**
Changes:
 - Decrease the aggressive test timeout of 20ms to 1 second. 
 - Fixed a race condition on `service.callCounts` by using `atomic` counts instead
 - Fixed a potential race condition between `server.Serve` and `server.GracefulStop` - See https://github.com/gravitational/teleport/pull/29218

Closes https://github.com/gravitational/teleport/issues/29879#event-9980721395

### CODE REVIEW

File: integration/proxy/teleterm_test.go [hunk 1]
```diff
@@ -199,8 +198,7 @@ func newMockTSHDEventsServiceServer(t *testing.T, tc *libclient.TeleportClient,
 	t.Cleanup(grpcServer.GracefulStop)
 
 	go func() {
-		err := grpcServer.Serve(ls)
-		assert.NoError(t, err)
```
Comment (codingllama) [inline integration/proxy/teleterm_test.go:203]: Keep the assert? It's not a bad idea to track errors here.

File: lib/teleterm/daemon/daemon_test.go [hunk 2]
```diff
@@ -453,7 +454,7 @@ func TestRetryWithRelogin(t *testing.T) {
 			}
 			require.Equal(t, tt.wantFnCalls, fnCallCount,
 				"Unexpected number of calls to fn")
-			require.Equal(t, tt.wantReloginCalls, service.callCounts["Relogin"],
+			require.EqualValues(t, tt.wantReloginCalls, service.reloginCount.Load(),
```
Comment (Joerger) [inline lib/teleterm/daemon/daemon_test.go:457]: Note: `require.Equal` does not allow comparing `int` to `uint32`.

File: integration/teleterm_test.go [hunk 3]
```diff
@@ -707,8 +707,7 @@ func newMockTSHDEventsServiceServer(t *testing.T) (service *mockTSHDEventsServic
 	t.Cleanup(grpcServer.GracefulStop)
 
 	go func() {
-		err := grpcServer.Serve(ls)
-		assert.NoError(t, err)
+		grpcServer.Serve(ls)
```
Comment (codingllama) [inline integration/teleterm_test.go:710]: Ditto.

File: lib/teleterm/daemon/daemon_test.go [hunk 4]
```diff
@@ -505,7 +506,7 @@ func TestImportantModalSemaphore(t *testing.T) {
 		t.Error("relogin completed successfully without acquiring the important modal semaphore")
 	case <-sphaErrC:
 		t.Error("sendPendingHeadlessAuthentication completed successfully without acquiring the important modal semaphore")
-	case <-time.After(5 * customWaitDuration):
+	case <-time.After(10 * customWaitDuration):
```
Comment (codingllama) [inline lib/teleterm/daemon/daemon_test.go:509]: Maybe bump `customWaitDuration` to 100ms or 200ms? It's still pretty fast, but not as punishing. (We could drop the `2*` then.)

File: lib/teleterm/daemon/daemon_test.go [hunk 5]
```diff
@@ -543,70 +544,59 @@ func TestImportantModalSemaphore(t *testing.T) {
...
 	ls, err := net.Listen("tcp", "127.0.0.1:0")
 	require.NoError(t, err)
 
 	grpcServer := grpc.NewServer()
 	api.RegisterTshdEventsServiceServer(grpcServer, tshdEventsService)
+	t.Cleanup(grpcServer.GracefulStop)
 
-	serveErr := make(chan error)
 	go func() {
-		serveErr <- grpcServer.Serve(ls)
```
Comment (codingllama) [inline lib/teleterm/daemon/daemon_test.go:579]: Could we keep the error handling? Same reasoning as the others.

File: lib/teleterm/daemon/daemon_test.go (hunk 2 above)
Comment (codingllama) [reply lib/teleterm/daemon/daemon_test.go:457]: FYI you can cast the values too, but this is fine as well.

**Review by codingllama — COMMENTED** [review]
Thanks for the quick fix!

File: lib/teleterm/daemon/daemon_test.go (hunk 4 above)
Comment (Joerger) [reply lib/teleterm/daemon/daemon_test.go:509]: Having a short wait duration increases the speed of the test overall, so I think we are better off as is. I'll change this to just be 100ms as there isn't really a connection to the wait duration here.

File: e
Comment (codingllama) [inline e:1]: Is the e/ change intentional?

File: integration/proxy/teleterm_test.go [hunk 6]
```diff
@@ -196,13 +195,24 @@ func newMockTSHDEventsServiceServer(t *testing.T, tc *libclient.TeleportClient,
...
+	t.Cleanup(func() {
+		grpcServer.GracefulStop()
+
+		// For test cases that did not send any grpc calls, test may finish
+		// before grpcServer.Serve is called and grpcServer.Serve will return
+		// grpc.ErrServerStopped.
+		err := <-serveErr
+		if len(tshdEventsService.callCounts) == 0 || err != grpc.ErrServerStopped {
+			require.NoError(t, err)
+		}
```
Comment (codingllama) [inline integration/proxy/teleterm_test.go:213]: I don't follow why the counts are relevant here, could this be:

```suggestion
		if err != grpc.ErrServerStopped {
			assert.NoError(t, err, "gRPC server exited with error")
		}
```

(I suggest the require->assert change nonetheless.)

File: integration/teleterm_test.go [hunk 7]
```diff
@@ -704,13 +704,24 @@ func newMockTSHDEventsServiceServer(t *testing.T) (service *mockTSHDEventsServic
...
+	t.Cleanup(func() {
+		grpcServer.GracefulStop()
+
+		// For test cases that did not send any grpc calls, test may finish
+		// before grpcServer.Serve is called and grpcServer.Serve will return
+		// grpc.ErrServerStopped.
+		err := <-serveErr
+		if (tshdEventsService.sendPendingHeadlessAuthenticationCount.Load() == 0) || err != grpc.ErrServerStopped {
+			require.NoError(t, err)
+		}
```
Comment (codingllama) [inline integration/teleterm_test.go:722]: Same as above?

```suggestion
		if err != grpc.ErrServerStopped {
			assert.NoError(t, err, "gRPC server exited with error")
		}
```

File: e
Comment (Joerger) [reply e:1]: Nope, thanks for catching it

File: integration/proxy/teleterm_test.go (hunk 6 above)
Comment (Joerger) [reply integration/proxy/teleterm_test.go:213]: Yeah that's probably fine too

**Review by codingllama — APPROVED** [review]

File: lib/teleterm/daemon/daemon_test.go [hunk 8]
```diff
@@ -19,11 +19,13 @@ import (
 	"net"
 	"net/http"
 	"net/http/httptest"
+	"sync/atomic"
 	"testing"
 	"time"
 
 	"github.com/gravitational/trace"
 	"github.com/stretchr/testify/require"
+	"github.com/zeebo/assert"
```
Comment (codingllama) [inline lib/teleterm/daemon/daemon_test.go:28]: FYI, wrong assert import.

**Review by codingllama — APPROVED** [review]

**Review by jakule — APPROVED** [review]
