### PR TITLE
Fix ClusterConfig caching with pre-v7 remote clusters

### LINKED ISSUE #7689: Access to read `cluster_networking_config` / `cluster_audit_config` denied (7.0 <- 6.2)
### Description

**What happened**:

When 6.2 leaf cluster is connected to 7.0 root cluster the following messages appear in the logs.

Leaf:

```
2021-07-26T14:50:59+03:00 INFO [RBAC]      Access to read cluster_networking_config in namespace default denied to roles RemoteProxy,default-implicit-role: no allow rule matched. services/role.go:2114
2021-07-26T14:51:09+03:00 INFO [RBAC]      Access to read cluster_audit_config in namespace default denied to roles RemoteProxy,default-implicit-role: no allow rule matched. services/role.go:2114
```

Root:

```
2021-07-26T14:54:39+03:00 [REVERSE:L] WARN Re-init the cache on error. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError watcher is closed
Stack Trace:
	/Users/r0mant/code/go/src/github.com/gravitational/teleport/lib/cache/cache.go:857 github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch
	/Users/r0mant/code/go/src/github.com/gravitational/teleport/lib/cache/cache.go:715 github.com/gravitational/teleport/lib/cache.(*Cache).update
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/asm_amd64.s:1371 runtime.goexit
User Message: watcher is closed] cache/cache.go:721
2021-07-26T14:54:39+03:00 [REVERSE:L] DEBU Reloading Linear(attempt=43, duration=10s). cache/cache.go:727
```

Things like `tsh ls` and `tsh ssh` appear to work but not sure what other functionality may be affected.

**What you expected to happen**:

No errors/warnings in the logs.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Connect 6.2 leaf to 7.0 root.
2. Look in the logs.

### Server Details
- Teleport version (run `teleport version`): 7.0.0-beta.3 root and 6.2.8 leaf

### Client Details
- Tsh version (`tsh version`): 7.0.0-beta.3

### PR DESCRIPTION
**Pull request by andrejtokarcik**
Fixes https://github.com/gravitational/teleport/issues/7689 which is a symptom of incorrectly configured caches / access points for pre-v7 remote clusters. The newer `ClusterConfig`-derived resources ([RFD 28](https://github.com/gravitational/teleport/blob/master/rfd/0028-cluster-config-resources.md)) should not be monitored with the `ForOldRemoteProxy` caching policy. The latter is hereby also updated to be assigned to pre-v7 remote clusters.

As far as I can tell, besides the verbose/confusing logging messages, the only location actually impacted by the bug would be: https://github.com/gravitational/teleport/blob/4751f82956b34761dc04abb00ae3839451468d5e/lib/web/apiserver.go#L1713-L1723

This PR will need to be backported to `branch/v7`.

### CODE REVIEW

**Review by Joerger — APPROVED** [review]

File: lib/services/clusterconfig.go [hunk 1]
```diff
@@ -20,9 +20,80 @@ import (
...
+		}
+		recConfigSpec := types.SessionRecordingConfigSpecV2{
+			Mode:                ccV3.Spec.LegacySessionRecordingConfigSpec.Mode,
+			ProxyChecksHostKeys: types.NewBoolOption(proxyChecksHostKeys),
+		}
+		recConfig, err = types.NewSessionRecordingConfigFromConfigFile(recConfigSpec)
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
+	}
```
Comment (Joerger) [inline lib/services/clusterconfig.go:75]: I added helpers for each of these in https://github.com/gravitational/teleport/pull/7702. If this merges first, I'll update this code in my PR.

File: lib/service/service.go [hunk 2]
```diff
@@ -1557,10 +1557,10 @@ func (process *TeleportProcess) newLocalCacheForRemoteProxy(clt auth.ClientI, ca
 	return process.newLocalCache(clt, cache.ForRemoteProxy, cacheName)
 }
 
-// DELETE IN: 5.1.
+// DELETE IN: 8.0.0
 //
 // newLocalCacheForOldRemoteProxy returns new instance of access point
-// configured for an old remote proxy.
+// configured for a pre-v7 remote proxy.
```
Comment (r0mant) [inline lib/service/service.go:1563]: Nit: TBH I think the previous "is old" / "an old" terminology was fine since now we have to update all these comments and function names with each release whereas before we would just update version in the "isOld" function and that's it.

**Review by r0mant — APPROVED** [review]

File: lib/cache/cache.go [hunk 3]
```diff
@@ -83,7 +82,6 @@ func ForProxy(cfg Config) Config {
 	cfg.Watches = []types.WatchKind{
 		{Kind: types.KindCertAuthority, LoadSecrets: false},
 		{Kind: types.KindClusterName},
-		{Kind: types.KindClusterConfig},
```
[the remark this answers is not in the document]
Comment (andrejtokarcik) [reply lib/cache/cache.go:86]: Since 7.0 its definitions are kept only for backward compatibility and it should be completely removed in 8.0.

File: lib/service/service.go (hunk 2 above)
Comment (andrejtokarcik) [reply lib/service/service.go:1563]: My general conviction is that how code is written should favour readability as opposed to "editability" (when the two are in conflict) since code is attempted to be understood more often than it gets edited.

I can easily revert this though.

Comment (r0mant) [reply lib/service/service.go]: Yeah that's fair and I agree from readability standpoint it's better. Let's keep your version.

File: lib/services/clusterconfig.go (hunk 1 above)
Comment (andrejtokarcik) [reply lib/services/clusterconfig.go:75]: Already merged, I'll be grateful if you remember to improve this with your helpers.
