### PR TITLE
Fix inverted check for `join_params` and `auth_token` mutual exclusion

### LINKED ISSUE #15512: `ERROR: only one of auth_token or join_params should be set` when only setting `join_params`
Expected behavior:
Should be able to set either `join_params` or `auth_token`

Current behavior:
If `join_params` is set at all, the node will fail to start. This breaks the IAM and EC2 join methods.

Bug details:
- Teleport version: master
- Recreation steps: set `join_params` in teleport.yaml and attempt to start a new node
- Debug logs: `ERROR: only one of auth_token or join_params should be set`

### PR DESCRIPTION
**Pull request by nklaassen**
Fixes https://github.com/gravitational/teleport/issues/15512

https://github.com/gravitational/teleport/commit/29175e57d32b76d1466448c193eb75f5fc609981 introduced an inverted check which makes any `join_params` set in the file config cause teleport to fail startup. This PR fixes the check and adds a test so we can't do this again.

### CODE REVIEW

File: lib/config/configuration.go [hunk 1]
```diff
@@ -2146,12 +2146,10 @@ func applyTokenConfig(fc *FileConfig, cfg *service.Config) error {
 	if fc.AuthToken != "" {
 		cfg.JoinMethod = types.JoinMethodToken
 		cfg.SetToken(fc.AuthToken)
-
-		return nil
```
Comment (nklaassen) [inline lib/config/configuration.go:2150]: removing the early return here so that we'll actually catch cases where `auth_token` and `join_params` are both set.

**Review by r0mant — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
