### PR TITLE
Fix sticky windows key

### LINKED ISSUE #24342: Windows Copy/Paste issue when we use command+tab in Web UI
Expected behavior:
Copy/paste should work in Web UI for Windows desktops when using a MAC keyboard when changing tabs using command+tab.

Current behavior:
It works fine when we copy/paste within Web UI using control copy(c)/control paster (v). It works well in RDP sessions.
But when we change tabs using command+tab (Mac keyboard) copy/paste not working until we hit the command button twice or paster command+v twice.
Bug details:
- Teleport version: v12
- Chrome Browser version: 111.
- Recreation steps: 
   Logged on to Windows desktop session from Web UI
   Open Browser/Notepad and try copy/paste works. Copy Data from another session without using command+tab will copy/paste works.
   But when we use command+tab and try copy/paste dint work.

https://www.loom.com/share/fe66e21182bd4d7ca85ef54919fd22e1
- Debug logs
   NA

### PR DESCRIPTION
**Pull request by ibeckermayer**
This moves all keyboard handling in the `useTdpClientCanvas` hook to a new `KeyboardHandler` object which contains a couple of additional features that improve cmd+tab / alt+tab UX:

1. Key down events for cmd/alt are put into an internal cache and "withheld". They are then either
    **a.** Sent to the server when another key down/up event is encountered. Encountering another key event suggests that
          the original cmd/alt key down was a normal event, and should be treated as such.
    **b.** The cache is cleared `onfocusout`. This scenario is a proxy for a cmd+tab / alt+tab event, meaning the cmd/alt key down was never meant to be sent to the server. This is the change the fixes https://github.com/gravitational/teleport/issues/24342

2. Key up events for cmd/alt are delayed via a 10ms timeout. This was added because, empirically, I was able to hit cmd+tab in a way that both the cmd down and cmd up events were registered by the browser, thus popping up the windows-menu on the remote machine even though I'd switched to another window. These delayed events then either:
    **a.** Get sent to the server after the barely-noticeable 10ms delay
    **b.** Are cleared by an `onfocusout` which happens within 10ms, thus solving the problem I originally encountered above.

Changelog: Prevents the windows key from sticking and otherwise registering when cmd+tab-ing or alt+tab-ing away from the browser during desktop sessions.

Fixes https://github.com/gravitational/teleport/issues/24342
Fixes https://github.com/gravitational/customer-sensitive-requests/issues/166

Depends on
- https://github.com/gravitational/teleport/pull/37962

### CODE REVIEW

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx [hunk 1]
```diff
@@ -0,0 +1,271 @@
...
+
+import { TdpClient, ButtonState } from 'teleport/lib/tdp';
+import { SyncKeys } from 'teleport/lib/tdp/codec';
+
+/**
+ * Handles keyboard events.
+ */
+export class KeyboardHandler {
+  /**
+   * Cache for keys whose down event has been withheld until the next keydown or keyup,
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:29]: nit: I wouldn't call these caches. A cache is generally a performance optimization that replaces slow lookups with fast one.

This is really just a lookup table, not a cache for some slower downstream store.

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx [hunk 2]
```diff
@@ -0,0 +1,271 @@
...
+   * or to never be sent if this cache is cleared onfocusout.
+   */
+  private withheldDown: Map<string, boolean> = new Map();
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:32]: Should these be [unordered] maps? Would some sort of queue structure make more sense?

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx [hunk 3]
```diff
@@ -0,0 +1,271 @@
...
+   * - On component initialization, so keys are synced before the first keydown/keyup event.
+   * - On focusout, so keys are synced when the user returns to the window.
+   */
+  private syncBeforeNextKey: boolean = true;
+  private isMac: boolean = getPlatform() === Platform.macOS;
+
+  /**
+   * Primary method for handling keyboard events.
+   */
+  public handleKeyboardEvent(
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:51]: You did a really nice job breaking this class up into small and easily comprehensible functions.

Seems like a great candidate for some unit tests, no?

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx [hunk 4]
```diff
@@ -0,0 +1,271 @@
...
+      // And add the timeout to the cache.
+      this.delayedUp.set(e.code, timeout);
+
+      return true;
+    }
+
+    return false;
+  }
+
+  private isWitholdableOrDelayeable(e: KeyboardEvent): boolean {
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:146]:
```suggestion
  private isWitholdableOrDelayable(e: KeyboardEvent): boolean {
```

I think?

**Review by zmb3 — COMMENTED** [review]
Haven't been able to break anything yet.

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx (hunk 2 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:32]: An unordered map indexed by key makes sense because there should never be more than 1 down or up "pending" for any given key.

Consider the state for a single key (say `MetaLeft`). We always start with a DOWN being withheld, which is sent [to te server] either by another key being pressed, or a `MetaLeft` UP being registered. Then, if we get an UP, the UP is delayed on a timeout, and it's sent by either the timeout timing out, another key being pressed (note: I think my current logic misses this, but this is how it should work for correctness), or a `MetaLeft` DOWN being registered. And so on.

IOW, we should never have anything but a single, withheld-with-optional-timeout, per key. That suggests that this should actually just be one Map-like structure that automagically works this way.

File: web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx [hunk 5]
```diff
@@ -70,15 +68,14 @@ export default function useTdpClientCanvas(props: Props) {
...
-   */
-  const syncBeforeNextKey = useRef(true);
+  const keyboardHandler = useRef(new KeyboardHandler());
+  useEffect(() => {
+    // On unmount, clear all the timeouts on the keyboardHandler.
+    return () => {
+      // eslint-disable-next-line react-hooks/exhaustive-deps
+      keyboardHandler.current.onUnmount();
+    };
+  }, []);
```
Comment (ravicious) [inline web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx:78]: There's this fragment in React docs:

> Try to [write every Effect as an independent process](https://react.dev/learn/lifecycle-of-reactive-effects#each-effect-represents-a-separate-synchronization-process) and [think about a single setup/cleanup cycle at a time.](https://react.dev/learn/lifecycle-of-reactive-effects#thinking-from-the-effects-perspective) It shouldn’t matter whether your component is mounting, updating, or unmounting. When your cleanup logic correctly “mirrors” the setup logic, your Effect is resilient to running setup and cleanup as often as needed.

Making sure that our code adheres to React's rules will be even more important once something like [the React compiler](https://react.dev/blog/2024/02/15/react-labs-what-we-have-been-working-on-february-2024) drops.

In Strict mode, this effect would be called twice. But the effect is not symmetrical, so this component would break.

Fortunately, I think the fix here is quite straightforward. `keyboardHandler.current` is used only from within key handlers, which pretty much guarantees that none of our code will call the handler until the component actually gets rendered (and thus the effect gets executed).

In this case, we could initialize a new instance of `KeyboardHandler` only within the effect itself and assign it to `keyboardHandler.current`. This way the effect becomes symmetrical and adheres to React's rules.

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx [hunk 6]
```diff
@@ -0,0 +1,271 @@
...
+   */
+  public onFocusOut() {
+    this.clearAllWithholdingAndDelay();
+    this.syncBeforeNextKey = true;
+  }
+
+  /**
+   * To be called before unmounting the component.
+   */
+  public onUnmount() {
```
Comment (ravicious) [inline web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:253]: `KeyboardHandler` seems to be well defined as a sort of class that exists outside of the React environment. To that point, I feel like we don't have to be "leaking" the fact that it ends up being used in a React component. How do you feel about calling this function `dispose` instead of `onUnmount`? This would also look nicer from the perspective of `useEffect` as well, which hides inherently imperative APIs behind a more declarative function call.

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx [hunk 7]
```diff
@@ -0,0 +1,271 @@
...
+   */
+  private getModifierState = (
+    e: KeyboardEvent,
+    keyArg: string
+  ): ButtonState => {
+    return e.getModifierState(keyArg) ? ButtonState.DOWN : ButtonState.UP;
+  };
+
+  /**
+   * Called before every keydown or keyup event. This witholds the
```
Comment (ravicious) [inline web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:96]:
```suggestion
   * Called before every keydown or keyup event. This withholds the
```

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx (hunk 4 above)
Comment (ravicious) [reply web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:146]: Perhaps even `isWithholdable…`? https://en.wiktionary.org/wiki/withholdable

**Review by ravicious — APPROVED** [review]
LGTM, though as Zac suggested, it'd be nice to have some unit tests.

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx (hunk 2 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx]: I ended up going with a queue like you suggested, which better represents the inherently ordered nature of keystokes: 44595889eba30982176bf283d415879cf35e169d

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx (hunk 4 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx]: Becomes irrelevant in 44595889eba30982176bf283d415879cf35e169d

File: web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx (hunk 5 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx:78]: In this case I don't think calling `onUnmout` in the case of a double render would break the component. Still, granted it makes sense to keep these "symmetrical".

63f1dfd6bc7e9a429639225572a0060a0925f1f0

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx (hunk 6 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx]: db77c991e08b3c0b10e4100ddb2a138a02cb46d6

Comment (ibeckermayer) [reply web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx]: db77c991e08b3c0b10e4100ddb2a138a02cb46d6

File: web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx [hunk 8]
```diff
@@ -0,0 +1,135 @@
...
+  /**
+   * Tracks whether the next keydown or keyup event should sync the
+   * local toggle key state to the remote machine.
+   *
+   * Set to true:
+   * - On component initialization, so keys are synced before the first keydown/keyup event.
+   * - On focusout, so keys are synced when the user returns to the window.
+   */
+  private syncBeforeNextKey: boolean = true;
+  private isMac: boolean = getPlatform() === Platform.macOS;
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/KeyboardHandler.tsx:40]:
```suggestion
  private static isMac: boolean = getPlatform() === Platform.macOS;
```

Perhaps?

File: web/packages/teleport/src/DesktopSession/Withholder.tsx [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+ *
+ * Events are either processed immediately, delayed, or cancelled based on user actions and focus changes.
+ */
+export class Withholder {
+  /**
+   * The list of keys which are to be withheld.
+   */
+  private keysToWithhold: string[] = ['Meta', 'Alt'];
+  /**
+   * The internal map of keystrokes that are currently
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/Withholder.tsx:42]:
```suggestion
   * The set of keystrokes that are currently
```

File: web/packages/teleport/src/DesktopSession/Withholder.tsx [hunk 10]
```diff
@@ -0,0 +1,123 @@
...
+      timeout = setTimeout(() => {
+        // Just flush after the timeout, the handler will
+        // be in the queue by then and thus will be called.
+        //
+        // Technically this might flush some keys that were
+        // pressed after this one, but that works okay in practice.
+        // A user would have to be doing something extremely unusual
+        // for this to become a noticeable problem.
+        this.flush();
+      }, 10); // 10 ms was determined empirically to work well.
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/Withholder.tsx:84]: Make a constant for the 10 value?

File: web/packages/teleport/src/DesktopSession/Withholder.tsx [hunk 11]
```diff
@@ -0,0 +1,123 @@
...
+      params,
+      handler: handleKeyboardEvent,
+      timeout,
+    });
+  }
+
+  // Cancel all withheld keys.
+  public cancel() {
+    while (this.withheldKeys.length > 0) {
+      const withheld = this.withheldKeys.shift();
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/Withholder.tsx:97]: I suspect this is less efficient than something like:

```
this.withheldKeys.forEach(w => clearTimeout(w.timeout));
this.withheldKeys = [];
```

Take it or leave it. Probably doesn't matter much, especially when the array is small.

File: web/packages/teleport/src/DesktopSession/Withholder.tsx [hunk 12]
```diff
@@ -0,0 +1,123 @@
...
+      if (withheld && withheld.timeout) {
+        clearTimeout(withheld.timeout);
+      }
+    }
+  }
+
+  // Flush all withheld keys.
+  private flush() {
+    while (this.withheldKeys.length > 0) {
```
Comment (zmb3) [inline web/packages/teleport/src/DesktopSession/Withholder.tsx:106]: Lot of duplication between `cancel` and `flush`. Is it worth consolidating?

**Review by zmb3 — APPROVED** [review]

File: web/packages/teleport/src/DesktopSession/Withholder.tsx (hunk 12 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/DesktopSession/Withholder.tsx:106]: I couldn't come up with a good one, they're tiny now based on your other suggestion so it's probably fine:

```typescript
  // Cancel all withheld keys.
  public cancel() {
    this.withheldKeys.forEach(w => clearTimeout(w.timeout));
    this.withheldKeys = [];
  }

  // Flush all withheld keys.
  private flush() {
    this.withheldKeys.forEach(w => {
      clearTimeout(w.timeout);
      w.handler(w.params);
    });
    this.withheldKeys = [];
  }
```

File: web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx [hunk 13]
```diff
@@ -69,16 +67,16 @@ export default function useTdpClientCanvas(props: Props) {
   const initialTdpConnectionSucceeded = useRef(false);
   const encoder = useRef(new TextEncoder());
   const latestClipboardDigest = useRef('');
+  const keyboardHandler = useRef(new KeyboardHandler());
```
Comment (ravicious) [inline web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx:70]: We should be able to drop the initialization of `KeyboardHandler` here since it's already done in the effect.

**Review by ravicious — APPROVED** [review]

File: web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx (hunk 13 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx:70]: I tried but couldn't get the type system to play nicely with it. I could make this a `MutableRefObject<KeyboardHandler | undefined>` but that's misleading, because in effect its always there when it matters.

Comment (ravicious) [reply web/packages/teleport/src/DesktopSession/useTdpClientCanvas.tsx:70]: FWIW, `const keyboardHandler = useRef<KeyboardHandler>();` doesn't yield any type errors for me.
