### PR TITLE
Fix headless server access requests

### LINKED ISSUE #25341: Access requests should work in conjunction with `tsh --headless`
**Description:**

When using the Preview mode `tsh --headless` functionality, I tried it out in conjunction with access requests. It appears that there is no support for using this in the early Preview since this feature just came out recently.

**Reproduction Steps:**

1. Run the following command:
```console
$ tsh --headless --user username --proxy teleport.example.com:443 ssh user@node
```

2. Observe the following output and error message:
```console
Complete headless authentication in your local web browser:

https://teleport.example.com:443/web/headless/4e84861a-a38b-5ddf-afca-21dadfae53f4

or execute this command in your local terminal:

tsh headless approve --user=admin --proxy=teleport.example.com:443 4e84861a-a38b-5ddf-afca-21dadfae53f4
ERROR: access denied to user connecting to node:0

You do not currently have access to user@node, attempting to request access.

Creating request...

Waiting for request approval...
```

after approving the request, the output continues:

```console
Approval received, getting updated certificates...

ERROR: cannot reissue certificates while using an identity file (-i)
```

I tried a few things to try to make it work, but none of them succeeded:

* assume the role in the web ui before opening the URL to approve the headless request
* Pass an id of an approved request `tsh --headless --user username --proxy teleport.example.com:443 --request-id 0e55f808-17f5-4757-9192-9c682142f5a8 ssh user@node`
* pass in a request reason `tsh --headless --user username --proxy teleport.example.com:443 --request-reason reasons ssh user@node`

**Expected Outcome:**

It is expected that using `tsh --headless` functionality should properly support the access request feature without encountering errors related to certificates and identity files.

**Teleport Version:**

```
Teleport Enterprise v12.2.4 git:api/v12.2.4-0-g0f5a2d8 go1.20.3
```

### PR DESCRIPTION
**Pull request by Joerger**
Closes https://github.com/gravitational/teleport/issues/25341

### CODE REVIEW

File: tool/tsh/tsh.go [hunk 1]
```diff
@@ -4328,9 +4328,6 @@ func reissueWithRequests(cf *CLIConf, tc *client.TeleportClient, newRequests []s
 	if err != nil {
 		return trace.Wrap(err)
 	}
-	if profile.IsVirtual {
-		return trace.BadParameter("cannot reissue certificates while using an identity file (-i)")
-	}
```
Comment (Joerger) [inline tool/tsh/tsh.go:4333]: Now that[ identity files are treated as an in memory store](https://github.com/gravitational/teleport/pull/19420), this restriction is no longer necessary. The user's certificates will just be updated in memory to carry out that single request. This also applies to `--add-keys-to-agent=only` and `--headless`.

**Review by tigrato — APPROVED** [review]

**Review by strideynet — APPROVED** [review]

**Comment by Joerger** [comment]
@tigrato @strideynet `TestSSHHeadless` was taking > 6 seconds, which causes it to fail to the flaky test detector. I made some basic refactors and split up the tests to speed it up. Please give a quick re-review.

File: tool/tsh/tsh_test.go [hunk 2]
```diff
@@ -1924,15 +1935,93 @@ func tryCreateTrustedCluster(t *testing.T, authServer *auth.Server, trustedClust
...
+			name: "NOK --headless without explicit user",
+			modifyCLIConf: func(c *CLIConf) {
+				c.Headless = true
+			},
+			assertErr: func(t require.TestingT, err error, msgAndArgs ...interface{}) {
+				require.True(t, trace.IsBadParameter(err), "expected trace.BadParameter error but got %v", err)
+			},
+		},
+	} {
+		t.Run(tc.name, func(t *testing.T) {
```
Comment (tigrato) [inline tool/tsh/tsh_test.go:1995]: can you parallelize subtests too?
