### PR TITLE
Fixing node-join script for macos to support app bundles

### LINKED ISSUE #50171: Error on installation on macOS
Expected behavior:
Get OSX client installed when i run sudo bash -c "$(curl -fsSL https://teleport.XXX.XXX/scripts/XXX/install-node.sh)"

Current behavior:
sudo bash -c "$(curl -fsSL https://teleport.XXX.XXX/scripts/XXX/install-node.sh)"
2024-12-12 20:52:14 CET [teleport-installer] TELEPORT_VERSION: 17.0.5
2024-12-12 20:52:14 CET [teleport-installer] TARGET_HOSTNAME: teleport.XXX.XXX
2024-12-12 20:52:14 CET [teleport-installer] TARGET_PORT: 443
2024-12-12 20:52:14 CET [teleport-installer] JOIN_TOKEN: XXXX
2024-12-12 20:52:14 CET [teleport-installer] CA_PIN_HASHES: sha256:7db9be6456cbe557062af6956aafd5c85b7d8f088acd04fc843c437f914f4f42
2024-12-12 20:52:14 CET [teleport-installer] Checking TCP connectivity to Teleport server (teleport.XXX.XXX:443)
2024-12-12 20:52:14 CET [teleport-installer] Connectivity to Teleport server (via nc) looks good
2024-12-12 20:52:14 CET [teleport-installer] Detected host: darwin24.0.0, using Teleport binary type darwin
2024-12-12 20:52:14 CET [teleport-installer] Detected macOS arm64 architecture, using Teleport arch arm64
2024-12-12 20:52:14 CET [teleport-installer] Using Teleport distribution: tarball
2024-12-12 20:52:14 CET [teleport-installer] Created temp dir /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/teleport-XXXXXXXXXX.xww1yvUABi
2024-12-12 20:52:14 CET [teleport-installer] Installing from binary file.
2024-12-12 20:52:14 CET [teleport-installer] Downloading Teleport tarball release 17.0.5
2024-12-12 20:52:14 CET [teleport-installer] Running curl -fsSL --retry 5 --retry-delay 5 https://cdn.teleport.dev/teleport-v17.0.5-darwin-arm64-bin.tar.gz
2024-12-12 20:52:14 CET [teleport-installer] Downloading to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/teleport-XXXXXXXXXX.xww1yvUABi/teleport-v17.0.5-darwin-arm64-bin.tar.gz
2024-12-12 20:52:18 CET [teleport-installer] Downloaded file size: 160439946 bytes
2024-12-12 20:52:18 CET [teleport-installer] Will use shasum -a 256 to validate the checksum of the downloaded file
2024-12-12 20:52:18 CET [teleport-installer] The downloaded file's checksum validated correctly
cp: teleport/tctl: No such file or directory

Bug details:
- Teleport version: 17.0.5
- Recreation steps:
1. Enroll New Resource
2. Choose server macOS
3. Run command
- Debug logs
[Debuglog.txt](https://github.com/user-attachments/files/18117047/Debuglog.txt)

### PR DESCRIPTION
**Pull request by doggydogworld**
macOS distribution methods were updated to include Application Bundles for `tsh.app` and `tctl.app` replacing the standalone binaries. Other installation methods were updated for this change but this script was forgotten. The node join script should now successfully install on macOS.

Fixes #50171

changelog: Fixed a bug that prevented the node-join script from working on macOS.

### CODE REVIEW

File: lib/web/scripts/node-join/install.sh [hunk 1]
```diff
@@ -261,6 +264,10 @@ log_cleanup_message() {
         log_only "- unload and remove Teleport launchd config ${LAUNCHD_CONFIG_PATH}/${LAUNCHD_PLIST_FILE}"
         log_only "  - launchctl unload ${LAUNCHD_CONFIG_PATH}/${LAUNCHD_PLIST_FILE}"
         log_only "  - rm -f ${LAUNCHD_CONFIG_PATH}/${LAUNCHD_PLIST_FILE}"
+
+        log_only "- remove any teleport application bundles"
+        for APP_BUNDLE in ${TELEPORT_APP_BUNDLES_darwin}; do EXAMPLE_DELETE_COMMAND+="/Applications/${APP_BUNDLE} "; done
```
Comment (fheinecke) [inline lib/web/scripts/node-join/install.sh:269]:
```suggestion
        for APP_BUNDLE in "${TELEPORT_APP_BUNDLES_darwin[@]}"; do EXAMPLE_DELETE_COMMAND+="/Applications/${APP_BUNDLE} "; done
```

Does this (and elsewhere) need to be quoted and expanded?

File: lib/web/scripts/node-join/install.sh [hunk 2]
```diff
@@ -633,6 +640,12 @@ teleport_config_exists() { if [ -f ${TELEPORT_CONFIG_PATH} ]; then return 0; els
 teleport_datadir_exists() { if [ -d ${TELEPORT_DATA_DIR} ]; then return 0; else return 1; fi; }
 # checks whether a launchd plist file for teleport already exists on the host
 launchd_plist_file_exists() { if [ -f ${LAUNCHD_CONFIG_PATH}/${LAUNCHD_PLIST_FILE} ]; then return 0; else return 1; fi; }
+# checks whether application bundles for teleport clients already exist on the host
+application_bundles_exist() {
+    for APP_BUNDLE in ${TELEPORT_APP_BUNDLES_darwin}; do
+        if [ -d "/Applications/${APP_BUNDLE}" ]; then return 0; else return 1; fi
```
Comment (fheinecke) [inline lib/web/scripts/node-join/install.sh:646]: This will only run for the first app bundle. Is that intentional?

File: lib/web/scripts/node-join/install.sh (hunk 1 above)
Comment (fheinecke) [inline lib/web/scripts/node-join/install.sh:269]: nit: this should probably be quoted

```suggestion
        for APP_BUNDLE in ${TELEPORT_APP_BUNDLES_darwin}; do EXAMPLE_DELETE_COMMAND+="'/Applications/${APP_BUNDLE}' "; done
```

Otherwise it won't be quoted in the logged `rm` command, which could become a problem if `APP_BUNDLE` ever happens to contain a space, or an asterisk, or some other special undesired character.

Alternatively, to cover every case in this script, maybe the log function should implement one of [these suggestions](https://stackoverflow.com/a/27817504)?

File: lib/web/scripts/node-join/install.sh [hunk 3]
```diff
@@ -15,9 +16,11 @@ MACOS_STDERR_LOG="/var/log/teleport-stderr.log"
 MACOS_STDOUT_LOG="/var/log/teleport-stdout.log"
 SYSTEMD_UNIT_PATH="/lib/systemd/system/teleport.service"
 TARGET_PORT_DEFAULT=443
+TELEPORT_APP_BUNDLES_darwin="tctl.app tsh.app"
```
Comment (fheinecke) [inline lib/web/scripts/node-join/install.sh:19]:
```suggestion
TELEPORT_APP_BUNDLES_darwin=(tctl.app tsh.app)
```

This is treated like an array but not declared as one

File: lib/web/scripts/node-join/install.sh [hunk 4]
```diff
@@ -15,9 +16,11 @@ MACOS_STDERR_LOG="/var/log/teleport-stderr.log"
...
 TELEPORT_ARCHIVE_PATH='{{.packageName}}'
 TELEPORT_BINARY_DIR="/usr/local/bin"
 TELEPORT_BINARY_LIST="teleport tctl tsh teleport-update"
+TELEPORT_BINARY_LIST_darwin="teleport"
```
Comment (fheinecke) [inline lib/web/scripts/node-join/install.sh:23]: Not critical because there's only one item, but this should be declared as an array if it's going to be used as one below.

File: lib/web/scripts/node-join/install.sh [hunk 5]
```diff
@@ -842,6 +863,11 @@ install_from_file() {
         for BINARY in ${TELEPORT_BINARY_LIST}; do
             ${COPY_COMMAND} "${TELEPORT_ARCHIVE_PATH}/${BINARY}" "${TELEPORT_BINARY_DIR}/"
         done
+        if is_macos_host; then
+            for APP_BUNDLE in ${TELEPORT_APP_BUNDLES_darwin}; do
+                ${APP_BUNDLE_COPY_COMMAND} "${TELEPORT_ARCHIVE_PATH}/${APP_BUNDLE}/" "/Applications/${APP_BUNDLE}/"
```
Comment (fheinecke) [inline lib/web/scripts/node-join/install.sh:868]:
```suggestion
                "${APP_BUNDLE_COPY_COMMAND[@]}" "${TELEPORT_ARCHIVE_PATH}/${APP_BUNDLE}/" "/Applications/${APP_BUNDLE}/"
```

**Review by fheinecke — APPROVED** [review]

**Comment by marcoandredinis** [comment]
I don't think we need any client tools when running this script 🤔 
Installing client tools has their own docs.
AFAIK, this script is only meant to create a teleport service with `ssh_service.enabled=true` and have it join the cluster.

So, I would instead remove any client binary from the installation.

**Comment by doggydogworld** [comment]
> I don't think we need any client tools when running this script 🤔 Installing client tools has their own docs. AFAIK, this script is only meant to create a teleport service with `ssh_service.enabled=true` and have it join the cluster.
> 
> So, I would instead remove any client binary from the installation.

Ah that's fair. I was following current convention for most of this since it was a regression for macOS after v17 release. To keep current functionality on Linux I can keep that and just remove the client libraries for macOS since that doesn't work right now (script will error on darwin).

**Comment by zmb3** [comment]
Let's try to get Marco's comments addressed so we can merge this soon.

**Review by marcoandredinis — APPROVED** [review]

File: lib/web/scripts/node-join/install.sh (hunk 4 above)
Comment (doggydogworld) [reply lib/web/scripts/node-join/install.sh]: All other stuff got removed. I kept this as just a string to keep it consistent. The original `TELEPORT_BINARY_LIST` is a space separated list of tools and the loops are based on that.

**Review by nklaassen — APPROVED** [review]
