### PR TITLE
Check if system assigned identity is present before using it (Azure VM)

### LINKED ISSUE #20370: Azure SQLServer access
### What 
When there is not system assignment identity to VM instance running the SQL Server DB Agent the `tsh db connect` result in following error: 
```     
 Initializing Azure default credential chain. cloud/clients.go:476panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x25c0ad1]
goroutine 387 [running]:github.com/gravitational/teleport/lib/cloud/azure.(*vmClient).Get(0xc000ea38f0, {0x70d2708, 0xc000e12450}, {0xc000d177a0?, 0xc000e12450?})   
github.com/gravitational/teleport/lib/cloud/azure/vm.go:92
 +0x171github.com/gravitational/teleport/lib/srv/db/common.(*dbAuth).getCurrentAzureVM(0xc000f78e60, {0x70d2708, 0xc000e12450}
 github.com/gravitational/teleport/lib/srv/db/common/auth.go:716
 +0x137github.com/gravitational/teleport/lib/utils.FnCacheGet[...].func1()    github.com/gravitational/teleport/lib/utils/fncache.go:135
+0x33github.com/gravitational/teleport/lib/utils.(*FnCache).get.func1()    github.com/gravitational/teleport/lib/utils/fncache.go:199
+0x85created by github.com/gravitational/teleport/lib/utils.(*FnCache).get    github.com/gravitational/teleport/lib/utils/fncache.go:195
+0x392

```
Most likely this error comes from nil  `PrincipalID`  in the [ identities = append(identities, Identity{ResourceID: *resp.Identity.PrincipalID})](https://github.com/gravitational/teleport/blob/master/lib/cloud/azure/vm.go#L97) call. 
DB agent should validate and handle this case printing verbose error message to the user.

### PR DESCRIPTION
**Pull request by gabrielcorado**
Fix #20370.

### CODE REVIEW

**Review by EdwardDowling — APPROVED** [review]

File: lib/cloud/azure/vm.go [hunk 1]
```diff
@@ -94,7 +94,10 @@ func (c *vmClient) Get(ctx context.Context, resourceID string) (*VirtualMachine,
 
 	var identities []Identity
 	if resp.Identity != nil {
-		identities = append(identities, Identity{ResourceID: *resp.Identity.PrincipalID})
+		if systemAssigned := StringVal(resp.Identity.PrincipalID); systemAssigned != "" {
+			identities = append(identities, Identity{ResourceID: systemAssigned})
```
Comment (smallinsky) [inline lib/cloud/azure/vm.go:98]: @gabrielcorado 
Do we need to add a system assigned identity to `Identities` pool that are used as SQLServer database users ? 
Maybe we can create a `VirtualMachine.SystemIdenitty` field where only a user assigned identify will be considered as valid db users ?

Comment (gabrielcorado) [reply lib/cloud/azure/vm.go:98]: I've kept it because this is a more generic client; if someone needs this information, they can still use it.

**Review by smallinsky — APPROVED** [review]

File: lib/cloud/azure/vm.go (hunk 1 above)
Comment (GavinFrazar) [reply lib/cloud/azure/vm.go:98]: note that `Identity.PrincipalID` is not a valid `ResourceID` and will fail to parse with `arm.ParseResourceID` - this prevents SQL Server login using system assigned identity from ever working.

Principal ID looks like: `11111111-2222-3333-4444-555555555555`

User assigned Identity keys from the response are valid resource ID like: 
```
/subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/database-access/providers/Microsoft.ManagedIdentity/userAssignedIdentities/sqlserver-alice
````

From https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview the name of a system-assigned managed identity is the same as the resource it was created for. However, I tested creating a managed identity with the same name as my Azure VM and it allowed me to do so and to assign it as a user-assigned managed identity. So there is potentially ambiguity if a system-assigned identity and user-assigned managed identity have the same name. I'd rather we just advise customers that using the system-assigned managed identity as a login is not supported.

Furthermore, we should handle the case where there is no default managed identity better and include info about that in the troubleshooting docs. See info about default identity here: https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/managed-identities-faq#what-identity-will-imds-default-to-if-dont-specify-the-identity-in-the-request relevant bit: ` If system assigned managed identity isn’t enabled, and multiple user assigned managed identities exist, then you are required to specify a managed identity in the request.`

I worked around the issue by setting environment variables AZURE_TENANT_ID and AZURE_CLIENT_ID to match my tenant and the managed identity that has discovery permissions, and that resolved the issue. The alternative is to just use a system-assigned managed identity and give that discovery permissions.

Comment (gabrielcorado) [reply lib/cloud/azure/vm.go:98]: Currently, it won't work with system-managed identities because we require it to be in the `ResourceID` format. We could make it more explicit in the code by separating user-managed and system-managed, as @smallinsky mentioned. Although, I'm not sure if we can provide a better error message for this case, and the guide we currently have only mentioned that they need to give a user-managed identity. Do you think we should change that?

I've created an issue for that second part where we should have better error handling when the SDK cannot define which identity to use: https://github.com/gravitational/teleport/issues/20513.

Comment (GavinFrazar) [reply lib/cloud/azure/vm.go:98]: @gabrielcorado I think we should change the guide to advise them to use a system assigned managed identity for the discovery permissions, and then use user assigned identities for each SQL Server login they want to create.

For code changes: we should change the code for `vmClient.Get` such that it puts all the user assigned identities in one field and the system-assigned identity's prinicipal ID in a a separate field inside the `VirtualMachine` struct.
