### PR TITLE
Prevent auth from starting when an incompatible major upgrade is detected

### LINKED ISSUE #41782: Teleport auth should refuse to start when jumping major versions
From time to time we get S1's from folks who attempt to jump multiple major versions at once when upgrading despite our [compatibility guarantees](https://goteleport.com/docs/upgrading/overview/#component-compatibility) that state that only adjacent major upgrades are supported. This leads to corrupted backend, broken cluster and lengthy recovery time.

Let's prevent these situations by having auth to just refuse to start when it detects an incompatible upgrade path is being attempted. One way to implement this would be to have auth save its version in the backend and then check it the first thing during startup to make sure that last "saved" version is not more than 1 major version behind, and abort startup if it is before any backend migrations are done, and exit with an error exit code and a clear error message explaining that this is unsupported upgrade path and linking to the compatibility documentation.

### PR DESCRIPTION
**Pull request by vapopov**
Added KV for storing teleport version in backend. If the current major version of teleport bigger than previous one more than one we must refuse to start.

Closes #41782

changelog: Teleport auth prevents upgrade major version more than one

### CODE REVIEW

**Review by rosstimothy — COMMENTED** [review]
Couple of high level thoughts:
1) I don't think we need the version quasi resource in api/types. This should only be internal to Auth and not something exposed to users.
2) We should use the semver package instead of regular expressions to parse versions.
3) ValidateAndUpdateTeleportVersion is currently very racy. Multiple Auth processes that start at the same time will both see no initial version in the backend and overwrite the others version. We should make use of ConditionalUpdate or AtomicWrite to guarantee that we are always acting on the most recent data stored in the backend and cannot accidentally overwrite the version of another process.
4) The error returned when the differences in versions should prevent starting Auth should be more informative and actionable. Let's make sure the users know that what they are trying to do is not supported, and inform them of the proper major version to upgrade to in an effort to reduce support load.
5) We should also consider in the future that an absence of a version in the backend might also mean the upgrade should not proceed. If this is introduced in v17, any updates from < v17 to >= v18 will not have a persisted version but would be an attempt to skip major versions.

File: lib/services/local/version.go [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package local
+
+import (
+	"context"
+
+	"github.com/gravitational/trace"
+	"github.com/sirupsen/logrus"
```
Comment (zmb3) [inline lib/services/local/version.go:25]: Can we use slog for new code so we don't have to convert it in the future?

File: lib/services/local/version.go [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+ * This program is distributed in the hope that it will be useful,
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU Affero General Public License for more details.
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+package local
```
[the remark this answers is not in the document]
Comment (zmb3) [reply lib/services/local/version.go:19]: Sure, but we're not trying to make this bulletproof. You could make the same argument for the backend - "couldn't the user just remove the version entry from the backend to violate the upgrade guidance?"

[the remark this answers is not in the document]
Comment (r0mant) [reply lib/services/local/version.go:19]: I think keeping it in local process storage would also not work in cases when auth runs in Kubernetes and pods recycle (which is every upgrade basically).

[the remark this answers is not in the document]
Comment (r0mant) [reply lib/services/local/version.go:19]: Actually, ignore my previous comment, we use secrets for local storage in Kubernetes so it would work. In fact, it looks like @fspmarshall added something called [InitialLocalVersion](https://github.com/gravitational/teleport/blob/c44530d985cf07ad4fa849b30281d09fc6ca2813/lib/auth/state/state.go#L90) to process storage a few weeks ago in https://github.com/gravitational/teleport/pull/42189. Is this something we can piggy-back on, or add the version we need to record alongside it? @fspmarshall Is "InitialLocalVersion" supposed to be updated when teleport upgrades?

File: lib/services/local/version.go [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+func (s *VersionService) GetTeleportVersion(ctx context.Context) (types.Version, error) {
+	item, err := s.Get(ctx, backend.Key(versionPrefix))
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+	return services.UnmarshalVersion(item.Value, services.WithRevision(item.Revision))
+}
+
+const (
+	versionPrefix = "version"
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/services/local/version.go:80]: What about moving it to auth scope like `backend.Key(authPrefix, versionPrefix)`

File: lib/services/local/version.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/services/local/version.go:19]: @r0mant I've launched latest v17, so we keep initial version `"initial_local_version":"15.4.5"`
what about to extend this state object to add version history field as array to keep track all version launch (as usually migration logic does)

[the remark this answers is not in the document]
Comment (r0mant) [reply lib/services/local/version.go:19]: I don't know if we need to keep the version history necessarily but adding another process state field for tracking the latest and current version (unless we can reuse initial_local_version) seems reasonable.

File: lib/service/version.go [hunk 4]
```diff
@@ -0,0 +1,95 @@
...
+
+const (
+	// majorVersionConstraint is the major version constraint when previous major version must be
+	// present in the storage, if not - we must refuse to start.
+	majorVersionConstraint = 18
+)
+
+var (
+	// errMajorVersionUpgrade default error for restricting upgrade major version.
+	errMajorVersionUpgrade = errors.New(`Teleport supports upgrade only one major version behind. ` +
```
Comment (r0mant) [inline lib/service/version.go:38]: As mentioned below, I don't think you need this variable. I'd just `return trace.BadParameter(<message>)` inline.

File: lib/service/version.go [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+	if trace.IsNotFound(err) {
+		// If the Instance state has not been found, it means this is the first launch,
+		// and we don't need to check the version since this is the initial launch.
+		return nil
+	} else if err != nil {
+		return trace.Wrap(err)
+	}
+
+	if st.Spec.LocalVersion == "" {
+		if currentMajor >= majorVersionConstraint {
```
Comment (r0mant) [inline lib/service/version.go:60]: Do we ensure that new clusters have the local version set during the first start?

File: lib/service/connect.go [hunk 6]
```diff
@@ -552,6 +552,7 @@ func (process *TeleportProcess) firstTimeConnect(role types.SystemRole) (*Connec
 		Spec: state.StateSpecV2{
 			Rotation:            ca.GetRotation(),
 			InitialLocalVersion: teleport.Version,
+			LocalVersion:        teleport.Version,
```
Comment (r0mant) [inline lib/service/connect.go:555]: Hmm I'm not sure this is the correct place to ensure auth server has this version set in its local state upon first start. I think this code runs on agents. You might wanna look at Init in https://github.com/gravitational/teleport/blob/master/lib/auth/init.go.

File: lib/service/version.go [hunk 7]
```diff
@@ -0,0 +1,95 @@
...
+			return trace.Wrap(errMajorVersionUpgrade, "Teleport is going to update to version %s, but before must be upgraded to %d.x.x first",
+				currentVersion, currentMajor-1)
+		}
+
+		st.Spec.LocalVersion = currentVersion
+		if err := process.storage.WriteState(types.RoleInstance, *st); err != nil {
+			return trace.Wrap(err)
+		}
+		return nil
```
Comment (r0mant) [inline lib/service/version.go:69]: I think the logic would be slightly cleaner if you moved this out of the loop (or rather just removed it since it's already done below) and put the version check under "else". So it would look like this:

```go
if st.Spec.LocalVersion == "" {
  // check version constraint
} else {
  // check existing local version
}

st.Spec.LocalVersion = currentVersion
if err := process.storage.WriteState(types.RoleInstance, *st); err != nil {
	return trace.Wrap(err)
}
return nil
```

File: lib/service/version.go [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+	}
+
+	localMajor, err := getMajorVersion(st.Spec.LocalVersion)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	if currentMajor-localMajor > 1 {
+		return trace.Wrap(errMajorVersionUpgrade, "Teleport version %s is going to upgrade to %s, but first you need to upgrade to version %d.x.x at least",
```
Comment (r0mant) [inline lib/service/version.go:77]: Couple of comments:

- Here you don't need to wrap an error, I would just return a single `trace.BadParameter(<error message>)` so you don't have to define a separate `errMajorVersionUpgrade`.
- This error message is better than the previous one but I would tweak it a bit more. For example:

```suggestion
			return trace.BadParameter("Unsupported upgrade path detected: from %v to %v. Teleport supports direct upgrades to the next major version only. Please upgrade your cluster to version %d.x.x first. See compatibility guarantees for details: https://goteleport.com/docs/upgrading/overview/#component-compatibility.",
```

File: lib/service/version.go [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+
+// validateAndUpdateTeleportVersion validates that the major version persistent in the backend
+// meets our upgrade compatibility guide.
+func (process *TeleportProcess) validateAndUpdateTeleportVersion(currentVersion string) error {
+	currentMajor, err := getMajorVersion(currentVersion)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	st, err := process.storage.GetState(process.GracefulExitContext(), types.RoleInstance)
```
Comment (r0mant) [inline lib/service/version.go:50]: Nit: `st` -> `state`. Prefer full variable names, shorthands make code harder to read. It's a bit against [style guide](https://go.dev/wiki/CodeReviewComments#variable-names) but I think it more applies to loop variables, for vars that are used throughout the function we prefer reasonably descriptive names.

File: lib/service/version.go [hunk 10]
```diff
@@ -0,0 +1,95 @@
...
+
+	st.Spec.LocalVersion = currentVersion
+	if err := process.storage.WriteState(types.RoleInstance, *st); err != nil {
+		return trace.Wrap(err)
+	}
+	return nil
+}
+
+// getMajorVersion parses string to fetch major version number.
+func getMajorVersion(version string) (int64, error) {
```
Comment (r0mant) [inline lib/service/version.go:89]: Consider moving this to https://github.com/gravitational/teleport/blob/master/lib/utils/ver.go. There's already [MajorSemver](https://github.com/gravitational/teleport/blob/8d102a37881519a5da8d44f0d2e7d521c2f47973/lib/utils/ver.go#L77) function but it returns a string. Maybe move it there and call `MajorSemverNum` or something?

File: lib/service/version.go [hunk 11]
```diff
@@ -0,0 +1,95 @@
...
+	currentMajor, err := getMajorVersion(currentVersion)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	st, err := process.storage.GetState(process.GracefulExitContext(), types.RoleInstance)
+	if trace.IsNotFound(err) {
+		// If the Instance state has not been found, it means this is the first launch,
+		// and we don't need to check the version since this is the initial launch.
+		return nil
```
Comment (r0mant) [inline lib/service/version.go:54]: I think we need to test a scenario when local process state gets removed, for whatever reason (shouldn't normally happen but people can get their clusters in all sorts of weird states). What would happen in this case? This will not be considered "first time start" because that is determined based on the presence of CA IIRC, will we re-init the process state with correct version? I'm mostly worried about scenario where it would get into some state which we'll have to recover manually which we need to avoid.

**Review by r0mant — COMMENTED** [review]
In addition to the comments, can you add test coverage to the PR?

File: lib/service/version.go (hunk 11 above)
Comment (vapopov) [reply lib/service/version.go:54]: For instance if we remove process database completely or specifically this `/states/instance/state` item, first we should go in this version check so `/states/instance/state` not created yet, this item managed by `process.connect` and going to be created after validation. Currently looking to in integration tests, to cover this case

Worst case scenario might be, if the user manually change `local_version` of `/states/instance/state` item in database

**Comment by zmb3** [comment]
@vapopov I've changed the title a bit so that it describes what the change does, not what the change _should_ do.

I also removed the corresponding issue from the PR title. It's better to link the issue in the PR body, not the title.

File: lib/service/version.go (hunk 11 above)
Comment (vapopov) [reply lib/service/version.go:54]: Was testing couple of scenarios with integration tests, found that in configuration when we enable only auth service
```golang
	cfg.Auth.Enabled = true
	cfg.Proxy.Enabled = false
	cfg.SSH.Enabled = false
```
We never register the instance state in the process storage
https://github.com/gravitational/teleport/blob/dc1199636558f85ed275512175a12207a8034d44/lib/service/service.go#L2564-L2574
this leads to skipping version check in auth service

Comment (r0mant) [reply lib/service/version.go:54]: @fspmarshall Any advice here?

File: integration/version_test.go [hunk 12]
```diff
@@ -0,0 +1,258 @@
...
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	// Create temporary directory for the auth service.
+	authDir := t.TempDir()
+
+	processStorage, err := storage.NewProcessStorage(ctx, filepath.Join(authDir, teleport.ComponentProcess))
+	require.NoError(t, err)
+
+	authAddr, err := getFreeListenAddr()
```
Comment (zmb3) [inline integration/version_test.go:59]: I would avoid `getFreeListenAddr()` if you can. It's a flawed approach.

File: integration/version_test.go [hunk 13]
```diff
@@ -0,0 +1,258 @@
...
+	case <-signal:
+		localVersion, err := processStorage.GetTeleportVersion(ctx)
+		require.NoError(t, err)
+
+		assert.Equal(t, teleport.Version, localVersion)
+	}
+}
+
+// TestVersionCheckUpgradeFailed tests version upgrade restriction with incompatible major upgrade.
+func TestVersionCheckUpgradeFailed(t *testing.T) {
```
Comment (zmb3) [inline integration/version_test.go:193]: Looks like these 3 tests share a lot of common code. Can we turn them into table tests?

File: lib/auth/storage/storage.go [hunk 14]
```diff
@@ -45,6 +45,10 @@ const (
 	statesPrefix = "states"
 	// idsPrefix is a key prefix for identities
 	idsPrefix = "ids"
+	// teleportPrefix is a key prefix to store internal data
+	teleportPrefix = "teleport"
+	// latestVersion is a key for storing latest version of teleport
```
Comment (zmb3) [inline lib/auth/storage/storage.go:50]: "latest" is a big ambiguous here. Is it the latest released version, the latest version running in the cluster, etc..

Should we call this `lastKnownVersion` or something similar?

File: lib/service/version.go [hunk 15]
```diff
@@ -33,63 +31,47 @@ const (
 	majorVersionConstraint = 18
```
Comment (zmb3) [inline lib/service/version.go:31]:
```suggestion
	// TODO(vapopov): DELETE IN 19
	majorVersionConstraint = 18
```

File: lib/service/version.go [hunk 16]
```diff
@@ -33,63 +31,47 @@ const (
...
+		//applying the majorVersionConstraint check.
+		_, err := process.storage.GetState(process.GracefulExitContext(), types.RoleAdmin)
+		if !trace.IsNotFound(err) && err != nil {
+			return trace.Wrap(err)
+		}
+		if currentMajor >= majorVersionConstraint && !trace.IsNotFound(err) {
+			return trace.BadParameter("Unsupported upgrade path detected: to %v. "+
+				"Teleport supports direct upgrades to the next major version only.\n Please upgrade "+
+				"your cluster to version %d.x.x first. See compatibility guarantees for details: "+
+				"https://goteleport.com/docs/upgrading/overview/#component-compatibility.",
```
Comment (zmb3) [inline lib/service/version.go:54]: I think this error message is incorrect.

If you were on Teleport 15 and you tried to upgrade straight to Teleport 18, wouldn't it say "Please upgrade your cluster to version 17.x.x first" ?? 

If so, that's not right, we should be telling them to upgrade to v16 first.

File: lib/utils/ver.go [hunk 17]
```diff
@@ -82,6 +82,15 @@ func MajorSemver(version string) (string, error) {
 	return fmt.Sprintf("%d.0.0", ver.Major), nil
 }
 
+// MajorVersion parses string to fetch major version number.
+func MajorVersion(version string) (int64, error) {
+	v, err := semver.NewVersion(version)
+	if err != nil {
+		return 0, trace.Wrap(err, "unsupported version format: %q", version)
```
Comment (zmb3) [inline lib/utils/ver.go:89]:
```suggestion
		return 0, trace.BadParameter(err, "unsupported version format: %q", version)
```

File: lib/service/version.go (hunk 16 above)
Comment (vapopov) [reply lib/service/version.go:54]: in this specific case we couldn't know exact version of previous setup, I would probably change the message with example from docs instead of this version suggestion

File: lib/auth/storage/storage.go [hunk 18]
```diff
@@ -203,6 +207,28 @@ func (p *ProcessStorage) WriteIdentity(name string, id state.Identity) error {
 	return trace.Wrap(err)
 }
 
+// GetTeleportVersion reads the latest teleport version.
```
Comment (zmb3) [inline lib/auth/storage/storage.go:210]:
```suggestion
// GetTeleportVersion reads the last known Teleport version from storage.
```

File: lib/auth/storage/storage.go [hunk 19]
```diff
@@ -203,6 +207,28 @@ func (p *ProcessStorage) WriteIdentity(name string, id state.Identity) error {
...
+	return string(item.Value), nil
+}
+
+// WriteTeleportVersion writes the latest teleport version to the backend.
+func (p *ProcessStorage) WriteTeleportVersion(version string) error {
+	item := backend.Item{
+		Key:   backend.Key(teleportPrefix, lastKnownVersion),
+		Value: []byte(version),
+	}
+	_, err := p.stateStorage.Put(context.TODO(), item)
```
Comment (zmb3) [inline lib/auth/storage/storage.go:225]: Do you plan to address this TODO? If not, use `context.Background()`.

File: lib/auth/storage/storage.go [hunk 20]
```diff
@@ -203,6 +207,28 @@ func (p *ProcessStorage) WriteIdentity(name string, id state.Identity) error {
...
+// GetTeleportVersion reads the latest teleport version.
+func (p *ProcessStorage) GetTeleportVersion(ctx context.Context) (string, error) {
+	item, err := p.stateStorage.Get(ctx, backend.Key(teleportPrefix, lastKnownVersion))
+	if err != nil {
+		return "", trace.Wrap(err)
+	}
+	return string(item.Value), nil
+}
+
+// WriteTeleportVersion writes the latest teleport version to the backend.
```
Comment (zmb3) [inline lib/auth/storage/storage.go:219]: As mentioned, I think "latest" is confusing here.

File: lib/service/version.go [hunk 21]
```diff
@@ -0,0 +1,79 @@
...
+				currentVersion)
+		}
+	} else if err != nil {
+		return trace.Wrap(err)
+	} else {
+		localMajor, err := utils.MajorVersion(localVersion)
+		if err != nil {
+			return trace.Wrap(err)
+		}
+		if currentMajor-localMajor > 1 {
```
Comment (zmb3) [inline lib/service/version.go:66]: Hmm, any way we can simplify this function? We're like 5 levels deep in if statements at this point.

File: lib/auth/storage/storage.go [hunk 22]
```diff
@@ -203,6 +207,28 @@ func (p *ProcessStorage) WriteIdentity(name string, id state.Identity) error {
...
+	return string(item.Value), nil
+}
+
+// WriteTeleportVersion writes the last known Teleport version to the storage.
+func (p *ProcessStorage) WriteTeleportVersion(version string) error {
+	item := backend.Item{
+		Key:   backend.Key(teleportPrefix, lastKnownVersion),
+		Value: []byte(version),
+	}
+	_, err := p.stateStorage.Put(context.Background(), item)
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/auth/storage/storage.go:225]: yes, I made similar as state written

File: lib/service/version.go [hunk 23]
```diff
@@ -0,0 +1,82 @@
...
+		return nil
+	} else if err != nil {
+		return trace.Wrap(err)
+	}
+
+	localMajor, err := utils.MajorVersion(localVersion)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	if currentMajor-localMajor > 1 {
```
Comment (r0mant) [inline lib/service/version.go:71]: It just occurred to me: we should probably prevent accidental downgrades by more than 1 major apart too.

File: integration/version_test.go [hunk 24]
```diff
@@ -0,0 +1,146 @@
...
+			case err := <-authRunErrCh:
+				if test.expectError {
+					assert.Error(t, err)
+				} else {
+					require.NoError(t, err)
+				}
+			case <-timeout:
+				t.Fatal("timed out waiting for fetching identity")
+			case <-signal:
+			}
```
Comment (r0mant) [inline integration/version_test.go:139]: We have a pretty major problem with flaky tests in Teleport, due to tests starting and waiting for various services which we largely have under control now but still, is there a way to make this test not depend on time?

For example, why do we need to start auth? Can we just instantiate auth of version X, call "initAuthService" on it, then start another auth of version X+1, init, make sure it works, then another of version X+3, init, make sure it fails, something like that? There would be no potential flakiness and the test would probably be simpler as well.

**Review by r0mant — COMMENTED** [review]
I think we're getting there but left a few more comments.

File: lib/service/version.go [hunk 25]
```diff
@@ -0,0 +1,82 @@
...
+	currentMajor, err := utils.MajorVersion(currentVersion)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	localVersion, err := process.storage.GetTeleportVersion(process.GracefulExitContext())
+	if trace.IsNotFound(err) {
+		// We have to ensure that the process database is newly created before
+		//applying the majorVersionConstraint check.
+		_, err := process.storage.GetState(process.GracefulExitContext(), types.RoleAdmin)
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/service/version.go:47]: By default we create state `RoleAdmin` only (in setup where we configure Teleport with auth service and disable everything else)

File: integration/version_test.go (hunk 24 above)
Comment (vapopov) [reply integration/version_test.go:139]: I need to additionally ensure that state for `RoleAdmin` created and this logic might be changed in time in initialization flow, thats why initially I choose to use integration test for such case. I check this state to identify if we have new install with empty database rather than existing one.

For instance if I add tests which trigger `initAuthService` only, we will never cover the case with `majorVersionConstraint` (this case covers situation: let say we have version 15, we know that storing information about version added in v17, and we are trying to update to v18, so if we check that we have any version in storage means that we have older version that <v17)

File: lib/auth/storage/storage.go [hunk 26]
```diff
@@ -203,6 +207,28 @@ func (p *ProcessStorage) WriteIdentity(name string, id state.Identity) error {
 	return trace.Wrap(err)
 }
 
+// GetTeleportVersion reads the last known Teleport version from storage.
+func (p *ProcessStorage) GetTeleportVersion(ctx context.Context) (string, error) {
+	item, err := p.stateStorage.Get(ctx, backend.Key(teleportPrefix, lastKnownVersion))
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/auth/storage/storage.go:212]: @fspmarshall proposed to make it global in context of the roles, should I change it?

File: lib/service/version.go [hunk 27]
```diff
@@ -0,0 +1,82 @@
...
+		if !trace.IsNotFound(err) && err != nil {
+			return trace.Wrap(err)
+		}
+		if currentMajor >= majorVersionConstraint && !trace.IsNotFound(err) {
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/service/version.go:51]: yes, this logic is related to identifying the first launch, we have something similar for `firstTimeConnect` but can't reuse it. Another option might be to add to the process backend interface a method to check if we have any items stored in the backend

File: integration/version_test.go (hunk 24 above)
Comment (vapopov) [reply integration/version_test.go]: I rewrite the test to use `initAuthService` instead

File: lib/service/version.go [hunk 28]
```diff
@@ -0,0 +1,81 @@
...
+const (
+	// majorVersionConstraint is the major version constraint when previous major version must be
+	// present in the storage, if not - we must refuse to start.
+	// TODO(vapopov): DELETE IN 18.0.0
+	majorVersionConstraint = 18
+)
+
+// validateAndUpdateTeleportVersion validates that the major version persistent in the backend
+// meets our upgrade compatibility guide.
+func (process *TeleportProcess) validateAndUpdateTeleportVersion(currentVersion *semver.Version, firstTimeStart bool) error {
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/service/version.go:37]: I wanted to have this check before backend storage init

https://github.com/gravitational/teleport/blob/fbc4636da8d72b7d21ac572ea0282289d0dfdbf9/lib/service/service.go#L1781-L1790

[the remark this answers is not in the document]
Comment (vapopov) [reply lib/service/version.go]: @rosstimothy I've moved logic to `auth.Init`

I've checked migration functionality in `pgbk` and `lite` backend drivers happens in `process.initAuthStorage()`, as I understood we don't plan to extend schemas or do any upgrades of existing tables so we should be good with check in `auth.Init`

**Review by bl-nero — APPROVED** [review]

File: lib/auth/storage/storage.go (hunk 26 above)
[the remark this answers is not in the document]
Comment (r0mant) [reply lib/auth/storage/storage.go:212]: Probably fine as is.

File: lib/auth/version.go [hunk 29]
```diff
@@ -0,0 +1,89 @@
...
+const (
+	// majorVersionConstraint is the major version constraint when previous major version must be
+	// present in the storage, if not - we must refuse to start.
+	// TODO(vapopov): DELETE IN 18.0.0
+	majorVersionConstraint = 18
+)
+
+// validateAndUpdateTeleportVersion validates that the major version persistent in the backend
+// meets our upgrade compatibility guide.
+func validateAndUpdateTeleportVersion(
```
Comment (r0mant) [inline lib/auth/version.go:40]: Should we have some kind of a hidden escape hatch? Like an (undocumented) environment variable that skips this check. Would be useful for development purposes.

File: lib/auth/init.go [hunk 30]
```diff
@@ -76,6 +77,9 @@ type InitConfig struct {
 	// Backend is auth backend to use
 	Backend backend.Backend
 
+	// ProcessStorage is a backend for local process
+	ProcessStorage *storage.ProcessStorage
```
Comment (r0mant) [inline lib/auth/init.go:81]: Need to update lib/auth/auth.go:NewServer now to make sure this field is not nil to avoid potential panics.

**Review by r0mant — COMMENTED** [review]
mostly lgtm with a couple remaining comments

File: lib/auth/version.go (hunk 29 above)
Comment (vapopov) [reply lib/auth/version.go:40]: I might add something similar as we already have in `InitConfig`:
```
	// SkipPeriodicOperations turns off periodic operations
	// used in tests that don't need periodic operations.
	SkipPeriodicOperations bool
```
so this value going to be accessible only from code

Comment (r0mant) [reply lib/auth/version.go:40]: @vapopov Having it in the code only won't help much for development IMO. The idea is that when working on multiple different versions of Teleport you might need to switch back-and-forth between them on the same cluster, e.g. from v14 to v16 and vice versa to test something. That's been my experience before at least - and even though for production scenarios it is not supported upgrade/downgrade path, for development it works fine most of the time. So the idea is that there should be something devs can set in their environment to bypass this check.

File: lib/auth/init.go (hunk 30 above)
Comment (vapopov) [reply lib/auth/init.go:81]: I've added PR with tests fix: https://github.com/gravitational/teleport.e/pull/4594

File: lib/auth/storage/storage.go [hunk 31]
```diff
@@ -203,6 +207,28 @@ func (p *ProcessStorage) WriteIdentity(name string, id state.Identity) error {
 	return trace.Wrap(err)
 }
 
+// GetTeleportVersion reads the last known Teleport version from storage.
+func (p *ProcessStorage) GetTeleportVersion(ctx context.Context) (string, error) {
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/auth/storage/storage.go:211]: I intentionally left the string not to have dependency in storage from another package

File: lib/auth/version.go [hunk 32]
```diff
@@ -0,0 +1,98 @@
...
+	ctx context.Context,
+	storage *storage.ProcessStorage,
+	currentVersion *semver.Version,
+	firstTimeStart bool,
+) error {
+	if skip := os.Getenv(skipVersionUpgradeCheckEnv); skip != "" {
+		return nil
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/auth/version.go:52]: If we want to test something with major version upgrade and disable this check, by constraint we anyway shouldn't  persist the version, in other cases we don't need to disable it

File: lib/auth/init.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/auth/init.go:81]: I would add other methods to the interface as well. if the process storage constructor doesn't initialize the backend internally but rather accepts it as an argument. In such a case, we can mock the backend storage instead

**Review by fspmarshall — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

File: lib/auth/auth_test.go [hunk 33]
```diff
@@ -84,10 +86,11 @@ import (
 )
 
 type testPack struct {
-	bk          backend.Backend
-	clusterName types.ClusterName
-	a           *Server
-	mockEmitter *eventstest.MockRecorderEmitter
+	bk             backend.Backend
+	processStorage *storage.ProcessStorage
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/auth/auth_test.go:90]: @rosstimothy in-memory implementation shouldn't work?

File: lib/auth/helpers.go [hunk 34]
```diff
@@ -1128,6 +1131,26 @@ func (t *TestTLSServer) Stop() error {
 	return err
 }
 
+// fakeTeleportVersion fake version storage implementation always return current version.
+type fakeTeleportVersion struct {
+	version *semver.Version
+}
+
+// FakeTeleportVersion creates fake version storage.
+func FakeTeleportVersion() VersionStorage {
```
[the remark this answers is not in the document]
Comment (vapopov) [reply lib/auth/helpers.go]: misprint, I was changing from in-memory implementation

File: lib/auth/version.go [hunk 35]
```diff
@@ -0,0 +1,91 @@
...
+		return trace.Wrap(err)
+	}
+
+	if currentVersion.Major-lastKnownVersion.Major > 1 {
+		return trace.BadParameter("Unsupported upgrade path detected: from %v to %v. "+
+			"Teleport supports direct upgrades to the next major version only.\n Please upgrade "+
+			"your cluster to version %d.x.x first. See compatibility guarantees for details: "+
+			"https://goteleport.com/docs/upgrading/overview/#component-compatibility.",
+			lastKnownVersion, currentVersion.String(), lastKnownVersion.Major+1)
+	}
```
Comment (ravicious) [inline lib/auth/version.go:79]: I just did what Roman described in another thread (https://github.com/gravitational/teleport/pull/43520/files#r1667060081): I switched to branch/v14, ran `make build/teleport`, started teleport and then switched back to master. Now I cannot start my cluster from master on 4aa48dbcbf0, because I keep getting this error:

```
initialization failed
	Unsupported upgrade path detected: from 14.3.21 to 17.0.0-dev. Teleport supports direct upgrades to the next major version only.
 Please upgrade your cluster to version 15.x.x first. See compatibility guarantees for details: https://goteleport.com/docs/upgrading/overview/#component-compatibility.
```

So I downloaded 15.4.9 and 16.1.0, started them one after the other, but it didn't fix the problem. How does it know that my last version was 14.3.21 but cannot figure out that I ran 15.4.9 and 16.1.0 in the meantime? 🤔 Do I need to trigger a particular code path while 15.x and 16.x are running?

Comment (vapopov) [reply lib/auth/version.go:79]: @ravicious you need to switch to branch/v15, because seems like 15.4.9 
 https://github.com/gravitational/teleport/pull/44051 has no these changes in this release, also you can use `TELEPORT_UNSTABLE_SKIP_VERSION_UPGRADE_CHECK=yes` to skip this check
