### PR TITLE
UX improvements for tbot

### LINKED ISSUE #10781: Machine ID `ssh_config` generation for older versions of OpenSSH
Ubuntu 20.04 ships with OpenSSH 8.2p1.

When I try and run `ssh -F ~/machine-id/ssh_config root@node-name`, I get the following:

```
ssh_config: line 10: Bad configuration option: pubkeyacceptedalgorithms
ssh_config: terminating, 1 bad configuration options
```

Commenting out the following line fixes this issue.

```
PubkeyAcceptedAlgorithms +ssh-rsa-cert-v01@openssh.com
```

Machine ID should try and detect the version of OpenSSH running on the host and generate and appropriate `ssh_config` since I think `PubkeyAcceptedAlgorithms` support was only added recently.

### LINKED ISSUE #10782: `tbot version` returns an error
Running `version` subcommand returns an error unlike other Teleport binaries.

```
$ ./tbot version
ERROR: expected command but got "version"
```

### LINKED ISSUE #10783: Add support for `--format=json` flag to `tctl bots add`
Adding support for the `--format=json` flag for `tctl bots add` would be really useful for automation.

For example, `tctl users add` already supports this.

```
$ tctl users add foo --roles=access --logins=root --format=json
{
  "kind": "user_token",
  "sub_kind": "invite",
  "version": "v3",
  "metadata": {
    "name": "00000000000000000000000000000000",
    "expires": "2022-03-03T05:38:07.971830993Z"
  },
  "spec": {
    "user": "foo",
    "url": "https://proxy.example.com:3080/web/invite/00000000000000000000000000000000",
    "created": "2022-03-03T04:38:07.971831423Z"
  }
}
```

### LINKED ISSUE #10813: Add support for `cut` to `ProxyCommand`
To use Machine ID, at the moment you must have DNS configured to connect to a host. The `ssh_config` automatically generated contains the following.

```
Host *.example.com !proxy.example.com
    Port 3022
    ProxyCommand ssh -F /opt/machine-id/secondary/ssh_config -l %r -p 3023 proxy.example.com -s proxy:%h:%p@example.com
```

This is expanded to the following when running `ssh -F /opt/machine-id/secondary/ssh_config root@server01.example.com`:

```
debug1: Executing proxy command: exec ssh -F /opt/machine-id/secondary/ssh_config -l rjones -p 3023 proxy.example.com -s proxy:server01.example.com:3022@example.com
```

The proxy subsystem will try and match on exact `nodename` so `server01.example.com` and always fail to match.

We should update the `ProxyCommand` to execute a program on disk like `cut` to manipulate `ProxyCommand` to work.

### LINKED ISSUE #10926: Update tbot name in CLI
### What
Output the correct name for tbot. 

```diff
Usage: tbot [<flags>] <command> [<args> ...]

- tbot: Teleport Credential Bot
+ tbot: Teleport MachineID
```

### Why
Branding 

### Workaround
If a workaround exists, please include it.

### PR DESCRIPTION
**Pull request by timothyb89**
A last batch of UX tweaks for 9.0:
 - rename `--renew-interval` to `--renewal-interval`
 - add `--oneshot` mode to fetch one set of certs and exit (client side only, no server enforcement yet)
 - add `tbot version` (fixes #10782)
 - add unix signal handling: graceful exit on SIGINT, reload on SIGHUP/SIGUSR1
 - make auth server an optional config option and check it only when needed (i.e. `tbot start`)
 - add `cut` workaround to allow SSH to work without DNS (fixes #10813)
 - fix product name in CLI help (fixes #10926)
 - add `--format=json` to `tctl bots add` (fixes #10783)
 - check SSH version and exclude the RSA deprecation workaround for older SSH clients (fixes #10781)

### CODE REVIEW

**Comment by timothyb89** [comment]
I know there's a few other renames being discussed in https://github.com/gravitational/teleport/issues/10030

I do like the `-lifetime` suffix and can still make that change tctl/tbot if we'd like.

For context, here's the `tbot start` syntax as of this PR:
```
$ ./tbot start --help
usage: tbot start [<flags>]

Starts the renewal bot, writing certificates to the data dir at a set interval.

Flags:
  -d, --debug             Verbose logging to stdout
  -c, --config            tbot.yaml path
  -a, --auth-server       Specify the Teleport auth server host
      --token             A bot join token, if attempting to onboard a new bot; used on first connect.
      --ca-pin            A repeatable auth server CA hash to pin; used on first connect.
      --data-dir          Directory to store internal bot data.
      --destination-dir   Directory to write generated certificates
      --certificate-ttl   TTL of generated certificates
      --renewal-interval  Interval at which certificates are renewed; must be less than the certificate TTL.
      --join-method       Method to use to join the cluster.
      --oneshot           If set, quit after the first renewal.
```


`tbot init`:
```
usage: tbot init --bot-user=BOT-USER [<flags>]

Initialize a certificate destination directory for writes from a separate bot user.

Flags:
  -d, --debug            Verbose logging to stdout
  -c, --config           tbot.yaml path
      --destination-dir  If NOT using a config file, specify the destination directory.
      --init-dir         If using a config file and multiple destinations are configured, specify which to initialize
      --clean            If set, remove unexpected files and directories from the destination
      --bot-user         Name of the bot Unix user which should have write access to the destination.

Aliases:

```

`tctl bots add`:
```
usage: tctl bots add --roles=ROLES [<flags>] <name>

Add a new certificate renewal bot to the cluster.

Flags:
  -d, --debug        Enable verbose logging to stderr
  -c, --config       Path to a configuration file [/etc/teleport.yaml]. Can also be set via the TELEPORT_CONFIG_FILE environment variable.
      --auth-server  Attempts to connect to specific auth/proxy address(es) instead of local auth [127.0.0.1:3025]
  -i, --identity     Path to an identity file. Must be provided to make remote connections to auth. An identity file can be exported with 'tctl auth sign'
      --insecure     When specifying a proxy address in --auth-server, do not verify its TLS certificate. Danger: any data you send can be intercepted or modified by an attacker.
      --roles        Roles the bot is able to assume.
      --ttl          TTL for the bot join token.
      --token        Name of an existing token to use.

Args:
  <name>  A name to uniquely identify this bot in the cluster.

Aliases:
```

**Comment by benarent** [comment]
@timothyb89 When trying the above, I'm unable to use --token when using `tctl bots add`

```
tctl bots add --roles=access --token=blah terminator
ERROR: unknown long flag '--token'
```

**Comment by timothyb89** [comment]
> @timothyb89 When trying the above, I'm unable to use --token when using `tctl bots add`
> 
> ```
> tctl bots add --roles=access --token=blah terminator
> ERROR: unknown long flag '--token'
> ```

Hmm, that definitely should work. My initial guess is that you might have an outdated tctl, but I'll dig into this more tomorrow.

File: tool/tbot/config/configtemplate_ssh.go [hunk 1]
```diff
@@ -40,6 +44,66 @@ type TemplateSSHClient struct {
...
+	}
+
+	return &semver.Version{
+		Major: int64(major),
+		Minor: int64(minor),
+		Patch: int64(patch),
+	}, nil
+}
+
+// getSSHVersion attempts to query the system SSH for it's current version.
```
Comment (zmb3) [inline tool/tbot/config/configtemplate_ssh.go:92]:
```suggestion
// getSSHVersion attempts to query the system SSH for its current version.
```

File: tool/tbot/main.go [hunk 2]
```diff
@@ -144,6 +155,10 @@ func onWatch(botConfig *config.BotConfig) error {
 }
 
 func onStart(botConfig *config.BotConfig) error {
+	if botConfig.AuthServer == "" {
+		return trace.BadParameter("An auth server must be set via --auth-server or configuration")
```
Comment (zmb3) [inline tool/tbot/main.go:159]: Do we support tunneling through proxy? If so, I recommend we change the wording to mention that it can be an auth or proxy server.

File: tool/tbot/config/config.go [hunk 3]
```diff
@@ -117,17 +120,14 @@ type BotConfig struct {
...
-	RenewInterval  time.Duration `yaml:"renew_interval"`
+	Debug           bool          `yaml:"debug"`
+	AuthServer      string        `yaml:"auth_server"`
+	CertificateTTL  time.Duration `yaml:"certificate_ttl"`
+	RenewalInterval time.Duration `yaml:"renewal_interval"`
+	Oneshot         bool          `yaml:"oneshot"`
 }
 
 func (conf *BotConfig) CheckAndSetDefaults() error {
-	if conf.AuthServer == "" {
```
[the remark this answers is not in the document]
Comment (timothyb89) [reply tool/tbot/config/config.go:127]: It's been moved to when it's actually needed. It was really awkward to need to specify `--auth-server` for all subcommands, like we needed `tbot init --auth-server=...` just for the config to validate properly even though it was never used.

File: tool/tbot/config/configtemplate_ssh.go (hunk 1 above)
Comment (timothyb89) [reply tool/tbot/config/configtemplate_ssh.go:92]: heh, whoops

File: tool/tbot/main.go (hunk 2 above)
Comment (timothyb89) [reply tool/tbot/main.go:159]: Good point, will reword.

File: tool/tbot/config/config.go [hunk 4]
```diff
@@ -214,6 +214,10 @@ func FromCLIConf(cf *CLIConf) (*BotConfig, error) {
 		config.Debug = true
 	}
 
+	if cf.Oneshot {
```
[the remark this answers is not in the document]
Comment (timothyb89) [reply tool/tbot/config/config.go:217]: I think it would always override in that case, right? If you don't set `cf.Oneshot` we should fall back to the config value (which itself defaults to the zero value)

**Comment by codingllama** [comment]
89 commits and 2.7k+ added lines is a tough review. Any chance we could split this into reasonably-sized parts?

**Comment by timothyb89** [comment]
> 89 commits and 2.7k+ added lines is a tough review. Any chance we could split this into reasonably-sized parts?

Hrm, GitHub got confused over the merge base change, it's supposed to be just +300 or so. I'll try to fix it.

**Comment by timothyb89** [comment]
Alright, apologies for confusion, the diff should now be back under control. Hopefully +230/-50 is a little more sane :slightly_smiling_face:

File: tool/tbot/config/config.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (codingllama) [reply tool/tbot/config/config.go:217]: +1 for direct assignment.

File: tool/tbot/config/config_test.go [hunk 5]
```diff
@@ -125,9 +126,53 @@ func TestConfigFile(t *testing.T) {
...
+		},
+	}
+
+	for _, test := range tests {
+		version, err := parseSSHVersion(test.str)
+		if test.err {
+			require.Error(t, err)
+		} else {
+			require.NoError(t, err)
+			require.True(t, version.Equal(*test.version))
```
Comment (codingllama) [inline tool/tbot/config/config_test.go:168]: nit: better error message.

```suggestion
			require.True(t, version.Equal(*test.version), "got version = %v, want = %v", version, test.version)
```

File: tool/tbot/config/config.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (zmb3) [reply tool/tbot/config/config.go:217]: ah, right

File: tool/tbot/config/configtemplate_ssh.go [hunk 6]
```diff
@@ -40,6 +44,66 @@ type TemplateSSHClient struct {
...
+
+// openSSHMinVersionForRSAWorkaround is the OpenSSH version after which the
+// RSA deprecation workaround should be added to generated ssh_config.
+var openSSHMinVersionForRSAWorkaround = semver.New("8.5.0")
+
+// parseSSHVersion attempts to parse
+func parseSSHVersion(versionString string) (*semver.Version, error) {
+	versionTokens := strings.Split(versionString, " ")
+	if len(versionTokens) == 0 {
+		return nil, trace.Errorf("invalid version string: %s", versionString)
```
Comment (codingllama) [inline tool/tbot/config/configtemplate_ssh.go:58]: nit: prefer BadParameter to Errorf? 

```suggestion
		return nil, trace.BadParameter("invalid version string: %s", versionString)
```

Same for others.

File: tool/tbot/config/configtemplate_ssh.go [hunk 7]
```diff
@@ -111,18 +175,31 @@ func (c *TemplateSSHClient) Render(ctx context.Context, authClient auth.ClientI,
 		return trace.Wrap(err)
 	}
 
+	// Default to including the RSA deprecation workaround.
```
Comment (codingllama) [inline tool/tbot/config/configtemplate_ssh.go:178]: What is the RSA workaround? Do we have it explained somewhere?

File: tool/tbot/main.go [hunk 8]
```diff
@@ -144,6 +155,10 @@ func onWatch(botConfig *config.BotConfig) error {
 }
 
 func onStart(botConfig *config.BotConfig) error {
+	if botConfig.AuthServer == "" {
+		return trace.BadParameter("An auth or proxy server must be set via --auth-server or configuration")
```
Comment (codingllama) [inline tool/tbot/main.go:159]: nit: uppercase error string

```suggestion
		return trace.BadParameter("an auth or proxy server must be set via --auth-server or configuration")
```

File: tool/tbot/main.go [hunk 9]
```diff
@@ -144,6 +155,10 @@ func onWatch(botConfig *config.BotConfig) error {
 }
 
 func onStart(botConfig *config.BotConfig) error {
```
Comment (codingllama) [inline tool/tbot/main.go:157]: Not for this PR, but we should consider refactoring the bulk of this logic outside of `package main` and test it.

**Review by codingllama — APPROVED** [review]

**Comment by codingllama** [comment]
> Alright, apologies for confusion, the diff should now be back under control. Hopefully +230/-50 is a little more sane 🙂

Much better :)

File: tool/tbot/main.go (hunk 9 above)
Comment (timothyb89) [reply tool/tbot/main.go:157]: Yeah, there's a lot of cleanup and refactoring needed here. Hoping to prioritize that sooner rather than later :slightly_smiling_face:

**Review by jakule — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
