### PR TITLE
Fix known cases where audit log events can be bypassed by exceeding limit

### LINKED ISSUE #15645: trace.aggregate record size 216167 exceeds max message size of 65536 bytes
Expected behavior:

The teleport-agent pod is not producing so many errors and the ram usage stays consistent.

Current behavior:

The teleport agent pod in the kubernetes Cluster produces this Error messages:
```bash
User Message: breaker is tripped] events/emitter.go:96
2022-08-18T14:55:46Z ERRO             Failed to emit audit event db.session.query(TDB02I). error:[
ERROR REPORT:
Original Error: trace.aggregate record size 216167 exceeds max message size of 65536 bytes
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:507 github.com/gravitational/teleport/lib/events.(*TeeStream).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:420 github.com/gravitational/teleport/lib/events.(*CheckingStream).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/auditwriter.go:444 github.com/gravitational/teleport/lib/events.(*AuditWriter).processEvents
        /go/src/github.com/gravitational/teleport/lib/events/auditwriter.go:66 github.com/gravitational/teleport/lib/events.NewAuditWriter.func1
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: record size 216167 exceeds max message size of 65536 bytes] events/emitter.go:422
2022-08-18T14:55:46Z ERRO             Failed to emit audit event. error:[
ERROR REPORT:
Original Error: trace.aggregate breaker is tripped
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:289 github.com/gravitational/teleport/lib/events.(*MultiEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:168 github.com/gravitational/teleport/lib/events.(*CheckingEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:94 github.com/gravitational/teleport/lib/events.(*AsyncEmitter).forward
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: breaker is tripped] events/emitter.go:170
2022-08-18T14:55:46Z ERRO             Failed to emit audit event. error:[
ERROR REPORT:
Original Error: trace.aggregate breaker is tripped
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:289 github.com/gravitational/teleport/lib/events.(*MultiEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:168 github.com/gravitational/teleport/lib/events.(*CheckingEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:94 github.com/gravitational/teleport/lib/events.(*AsyncEmitter).forward
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: breaker is tripped] events/emitter.go:96
2022-08-18T14:55:46Z ERRO             Failed to emit audit event. error:[
ERROR REPORT:
Original Error: trace.aggregate breaker is tripped
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:289 github.com/gravitational/teleport/lib/events.(*MultiEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:168 github.com/gravitational/teleport/lib/events.(*CheckingEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:94 github.com/gravitational/teleport/lib/events.(*AsyncEmitter).forward
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: breaker is tripped] events/emitter.go:170
2022-08-18T14:55:46Z ERRO             Failed to emit audit event. error:[
ERROR REPORT:
Original Error: trace.aggregate breaker is tripped
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:289 github.com/gravitational/teleport/lib/events.(*MultiEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:168 github.com/gravitational/teleport/lib/events.(*CheckingEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:94 github.com/gravitational/teleport/lib/events.(*AsyncEmitter).forward
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: breaker is tripped] events/emitter.go:96
2022-08-18T14:55:46Z ERRO             Failed to emit audit event db.session.query(TDB02I). error:[
ERROR REPORT:
Original Error: trace.aggregate record size 216288 exceeds max message size of 65536 bytes
Stack Trace:
^CEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:168 github.com/gravitational/teleport/lib/events.(*CheckingEmitter).EmitAuditEvent
        /go/src/github.com/gravitational/teleport/lib/events/emitter.go:94 github.com/gravitational/teleport/lib/events.(*AsyncEmitter).forward
        /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
User Message: breaker is tripped] events/emitter.go:170
2022-08-18T14:55:46Z ERRO             Failed to emit audit event. error:[
ERROR REPORT:
Original Error: trace.aggregate breaker is tripped
````
And is using more and more RAM until kubernetes kills it.

Bug details:
- Teleport version: 
Teleport v10.1.4 git:v10.1.4-0-gf095c6f go1.18.3 teleport-agent: 10.1.4
- Recreation steps
A teleport cluster on a seperate machine.
Teleport-agent helm Chart in a kubernetes Cluster with a mongodb as database.
Running mongorestore command on a local maschine to the database.

- Debug logs

### PR DESCRIPTION
**Pull request by sfreiberg**
### Purpose

Fixes known cases where audit log events can be bypassed by exceeding the entry size limit. Also fixes gravitational/teleport#15645 where memory can balloon when doing large inserts in MongoDB and audit records are lost. 

### Implementation

1. Increase the ballast size when trimming to max size. This helps account for additional quoting required in MongoDB queries.
2. When adding an additional factor limit the Device Name to 30 characters or less.
3. When logging the UserAgent on login limit it to the first 2048 characters. When researching this I found some browsers like IE can send very long UAs but I think this is more than enough.
4. Implement TrimToMaxSize in ProtoStream.

### CODE REVIEW

**Review by rosstimothy — COMMENTED** [review]
Can we add a few test cases to ensure there are no regressions?

**Comment by sfreiberg** [comment]
@rosstimothy I added a couple of tests to test a mongo query and one for ProtoStream.

**Review by rosstimothy — COMMENTED** [review]
Looks reasonable to me. @smallinsky @r0mant any objections/concerns about the changes to `DatabaseSessionQuery`?

**Comment by sfreiberg** [comment]
@rosstimothy I just added another test for trimming the user agent.

File: lib/auth/methods_test.go [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+	count int
+}
+
+func (e *emitter) EmitAuditEvent(_ context.Context, event apievents.AuditEvent) error {
+	loginEvent, ok := event.(*apievents.UserLogin)
+	if ok && len(loginEvent.UserAgent) <= maxUserAgentLen {
+		e.count++
+	}
+	return nil
+}
```
Comment (zmb3) [inline lib/auth/methods_test.go:38]: You can replace all of this with `eventstest.MockEmitter` instead.

File: api/types/events/events.go [hunk 2]
```diff
@@ -48,8 +48,8 @@ func (m *DatabaseSessionQuery) TrimToMaxSize(maxSize int) AuditEvent {
 	out.DatabaseQuery = ""
 	out.DatabaseQueryParameters = nil
 
-	// Use 10% max size ballast + message size without custom fields.
-	sizeBallast := maxSize/10 + out.Size()
+	// Use 12% max size ballast + message size without custom fields.
+	sizeBallast := maxSize/8 + out.Size()
```
Comment (r0mant) [inline api/types/events/events.go:52]: Could you explain how changing this from 10% to 12% helps?

File: lib/auth/auth.go [hunk 3]
```diff
@@ -2289,6 +2292,10 @@ type newMFADeviceFields struct {
 
 // verifyMFARespAndAddDevice validates MFA register response and on success adds the new MFA device.
 func (a *Server) verifyMFARespAndAddDevice(ctx context.Context, req *newMFADeviceFields) (*types.MFADevice, error) {
+	if len(req.newDeviceName) > mfaDeviceNameMaxLen {
```
Comment (r0mant) [inline lib/auth/auth.go:2295]: Is this change backwards compatible? I.e. if there's already MFA device in the backend with >30 character name, will it still work?

File: lib/auth/methods.go [hunk 4]
```diff
@@ -35,6 +35,11 @@ import (
 	"github.com/gravitational/teleport/lib/utils"
 )
 
+const (
+	// maxUserAgentLen is the maximum length of a user agent that will be logged.
```
Comment (r0mant) [inline lib/auth/methods.go:39]: Nit: Explain why.

File: lib/auth/methods_test.go (hunk 1 above)
Comment (sfreiberg) [reply lib/auth/methods_test.go]: Done

File: api/types/events/events.go (hunk 2 above)
Comment (sfreiberg) [reply api/types/events/events.go:55]: I added some additional comments to the code but basically MongoDB requires a lot of escaping when converting from binary format that caused the overall size to still exceed the limits even after trimming.

File: lib/auth/methods.go (hunk 4 above)
Comment (sfreiberg) [reply lib/auth/methods.go:39]: Done.

File: lib/auth/auth.go (hunk 3 above)
Comment (sfreiberg) [reply lib/auth/auth.go:2295]: Yes, this is backwards compatible. It only applies to adding a new device.

File: api/types/events/events.go (hunk 2 above)
Comment (r0mant) [reply api/types/events/events.go:55]: Yes, I was more curious how you picked this 12% number and not say, 15% or 20%? Is there a formula or is it more based on the "feel" and to get a bit more buffer? Can we be sure that we won't run into the same issue with size again?

**Review by r0mant — APPROVED** [review]

File: lib/auth/auth.go (hunk 3 above)
Comment (zmb3) [reply lib/auth/auth.go:2295]: @codingllama any concerns with limiting the length of MFA devices here?

@kimlisa do you think this warrants a web UI update to prevent users from creating MFA devices with names that are too long?

File: api/types/events/events.go (hunk 2 above)
Comment (sfreiberg) [reply api/types/events/events.go:55]: Ah, gotcha. This was based on the tests I ran locally. There is an example in the tests. But your question got me thinking about the pathological cases and how I could better handle those. I'm working on an implementation that will be more reliable.

File: lib/auth/auth.go (hunk 3 above)
Comment (kimlisa) [reply lib/auth/auth.go:2295]: sure i think it's worth it, it's always nice to visually point out to a user where they specifically messed up (highlight red the input box) versus just getting an error message

File: lib/events/stream.go [hunk 5]
```diff
@@ -386,16 +386,21 @@ func (s *ProtoStream) Done() <-chan struct{} {
 
 // EmitAuditEvent emits a single audit event to the stream
 func (s *ProtoStream) EmitAuditEvent(ctx context.Context, event apievents.AuditEvent) error {
+	messageSize := event.Size()
+	if messageSize > MaxProtoMessageSizeBytes {
```
Comment (smallinsky) [inline lib/events/stream.go:390]: not related to PR but I was always curios why the max limit for Proto message was set to  64KB ?

**Review by smallinsky — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
