### PR TITLE
fix: open with RDWR for exclusive file lock

### LINKED ISSUE #3779: Upload fails if NFS storage is used for /var/lib/teleport
### Description

**What happened**:

Upload of exec session recording fails if NFS storage has been used for Teleport because it is unable to take the exclusive lock, failing with "bad file descriptor"

**What you expected to happen**:

Upload to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.2.8git:v4.2.8-0-ga9015b33 go1.13.2
- Tsh version (use `tsh version`): Teleport v4.2.8 git:v4.2.8-0-ga9015b33 go1.13.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS"

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): IBM Cloud

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

```
Uploader scan failed: 
ERROR REPORT:
Original Error: *trace.ConnectionProblemError bad file descriptor
Stack Trace:
	/gopath/src/github.com/gravitational/teleport/lib/utils/fs_unix.go:45 github.com/gravitational/teleport/lib/utils.FSTryWriteLock
	/gopath/src/github.com/gravitational/teleport/lib/events/uploader.go:226 github.com/gravitational/teleport/lib/events.(*Uploader).uploadFile
	/gopath/src/github.com/gravitational/teleport/lib/events/uploader.go:303 github.com/gravitational/teleport/lib/events.(*Uploader).Scan
	/gopath/src/github.com/gravitational/teleport/lib/events/uploader.go:151 github.com/gravitational/teleport/lib/events.(*Uploader).Serve
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:1661 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initUploaderService.func1
	/gopath/src/github.com/gravitational/teleport/lib/service/supervisor.go:452 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	/gopath/src/github.com/gravitational/teleport/lib/service/supervisor.go:242 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	/
```

This is because when teleport opens the file in the uploader code, there aren't any open flags passed to the func so the file handle is read-only.
https://github.com/gravitational/teleport/blob/732dfd5a64b6534555466c0e776cccf72f86c4a8/lib/events/uploader.go#L222

Then teleport tries to take an exclusive lock on it before uploading by calling https://github.com/gravitational/teleport/blob/796464162000fa17d1615dd48e29c0b335f5cc3b/lib/utils/fs_unix.go#L40

However, on NFS storage it needs to have opened the file for read+write access as per the manpage:

http://manpages.ubuntu.com/manpages/bionic/en/man2/flock.2.html

> Since Linux 2.6.12, NFS clients support flock() locks by emulating them as fcntl(2)  byte-
range  locks  on  the entire file.  This means that fcntl(2) and flock() locks do interact
with one another over NFS.  It also means that in order to place an  exclusive  lock,  the
file must be opened for writing.

### PR DESCRIPTION
**Pull request by dnwe**
In order to place an exclusive lock on NFS storage, the file must be
opened for writing.

Fixes gravitational/teleport#3779

Signed-off-by: Dominic Evans <dominic.evans@uk.ibm.com>

### CODE REVIEW

**Comment by webvictim** [comment]
ok to test

**Comment by webvictim** [comment]
retest this please

**Comment by benarent** [comment]
ok to test

**Comment by webvictim** [comment]
```
# github.com/gravitational/teleport/lib/events
lib/events/uploader.go:222:26: too many arguments in call to os.Open
	have (string, int, number)
	want (string)
# github.com/gravitational/teleport/lib/events [github.com/gravitational/teleport/lib/events.test]
lib/events/uploader.go:222: too many arguments in call to os.Open
	have (string, int, number)
	want (string)
FAIL	github.com/gravitational/teleport/e/lib/auth [build failed]
```

File: lib/events/uploader.go [hunk 1]
```diff
@@ -219,7 +219,7 @@ func (u *Uploader) emitEvent(e UploadEvent) {
 }
 
 func (u *Uploader) uploadFile(lockFilePath string, sessionID session.ID) error {
-	lockFile, err := os.Open(lockFilePath)
+	lockFile, err := os.OpenFile(lockFilePath, os.O_RDWR, 0640)
```
Comment (fspmarshall) [inline lib/events/uploader.go:222]: Nit: Cleaner to just pass `0` for permission bits since we aren't using `O_CREATE`.

**Review by fspmarshall — APPROVED** [review]
Looks good to me, thanks for the PR!

**Comment by dnwe** [comment]
(Fixed. That’ll teach me to manually rebase a commit in my head)

File: lib/events/uploader.go (hunk 1 above)
Comment (dnwe) [reply lib/events/uploader.go]: @fspmarshall good point, fixed 👍

**Review by russjones — APPROVED** [review]
