### PR TITLE
Use signal pipe to make live reload better.

### LINKED ISSUE #1844: Teleport HUP is unreliable with systemd
**What happened**:

`systemctl reload teleport.service` results in stopped unit when ExecReload sends HUP signal

**What you expected to happen**:

`systemctl` reload works

**How to reproduce it (as minimally and precisely as possible)**:

Use live reload example with systemctl reload several times.

**Environment**:
- Teleport version (use `teleport version`):
2.4.5
- Tsh version (use `tsh version`):
- OS (e.g. from /etc/os-release):
Ubuntu 16.04

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

### PR DESCRIPTION
**Pull request by klizhentas**
This commit allows teleport parent process to track
the status of the forked child process using os.Pipe.

Child process signals success to parent process by writing
to Pipe.

This allows HUP and USR2 to be more intelligent as they
can now detect the failure or success of the process.

fixes #1844

### CODE REVIEW

**Comment by klizhentas** [comment]
retest this please

File: lib/service/signals.go [hunk 1]
```diff
@@ -370,8 +436,28 @@ func (process *TeleportProcess) forkChild() error {
...
+	defer cancel()
+	go func() {
+		data := make([]byte, 1024)
+		len, err := readPipe.Read(data)
+		if err != nil {
+			log.Debugf("Failed to read from pipe")
+			return
+		}
+		log.Infof("Received message from pid %v: %v", p.Pid, string(data[:len]))
+		cancel()
```
Comment (russjones) [inline lib/service/signals.go]: `cancel()` is called twice.

File: lib/service/signals.go [hunk 2]
```diff
@@ -134,6 +133,37 @@ func (process *TeleportProcess) WaitForSignals(ctx context.Context) error {
...
+
+	messageSent, cancel := context.WithCancel(context.TODO())
+	defer cancel()
+	go func() {
+		_, err := signalPipe.Write([]byte(message))
+		if err != nil {
+			log.Debugf("Failed to write to pipe: %v", trace.DebugReport(err))
+			return
+		}
+		cancel()
```
Comment (russjones) [inline lib/service/signals.go]: `cancel()` called twice.

File: lib/service/signals.go [hunk 3]
```diff
@@ -134,6 +133,37 @@ func (process *TeleportProcess) WaitForSignals(ctx context.Context) error {
...
+	}()
+
+	select {
+	case <-time.After(signalPipeTimeout):
+		return trace.BadParameter("Failed to write to parent process pipe")
+	case <-messageSent.Done():
+		log.Infof("Signalled success to parent process")
```
Comment (russjones) [inline lib/service/signals.go]: Signaled. Might want to use structured logging like below as well.

File: lib/service/signals.go [hunk 4]
```diff
@@ -134,6 +133,37 @@ func (process *TeleportProcess) WaitForSignals(ctx context.Context) error {
 	}
 }
 
+func (process *TeleportProcess) writeToSignalPipe(message string) error {
+	signalPipe, err := process.importSignalPipe()
+	if err != nil {
+		if !trace.IsNotFound(err) {
+			return trace.Wrap(err)
+		}
+		log.Debugf("No signal pipe found, not going to signal")
```
Comment (russjones) [inline lib/service/signals.go]: Maybe change message to, "No signal pipe to import, must be first Teleport process."

File: lib/service/signals.go [hunk 5]
```diff
@@ -134,6 +133,37 @@ func (process *TeleportProcess) WaitForSignals(ctx context.Context) error {
...
+		return nil
+	}
+	defer signalPipe.Close()
+
+	messageSent, cancel := context.WithCancel(context.TODO())
```
Comment (russjones) [inline lib/service/signals.go]: Since in this case `context.TODO()` will never be replaced (it's only used to signal when the write is complete), I'd use `context.Background()`. That way it won't highlight `TODO` in editors.

File: lib/service/service.go [hunk 6]
```diff
@@ -441,6 +431,20 @@ func NewTeleport(cfg *Config) (*TeleportProcess, error) {
 		return nil, trace.BadParameter("all services failed to start")
 	}
 
+	if err := process.writeToSignalPipe(fmt.Sprintf("Process %v has started.", os.Getpid())); err != nil {
+		log.Warningf("Failed to write to signal pipe: %v", trace.DebugReport(err))
```
Comment (russjones) [inline lib/service/service.go]: Return an error here, otherwise you'll always write the pid file.

**Review by russjones — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please

**Review by r0mant — APPROVED** [review]
