### PR TITLE
Fix HSM tests

### LINKED ISSUE #14172: `TestHSMMigrate` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/c8063521-9f7a-4663-82ed-01266d39a199?project=ci-account

#### Relevant snippet

```
        	Messages:   	error while closing auth2 during test cleanup
        	Test:       	TestHSMMigrate
        	            	context canceled
        	Error:      	Received unexpected error:
        	            				hsm_test.go:826
        	            				hsm_test.go:811
        	            				testing.go:864
        	            				panic.go:500
        	            				testing.go:1433
        	            				testing.go:1203
        	            				testing.go:1034
        	            				hsm_test.go:76
        	            				testing.go:864
        	            				panic.go:500
        	            				testing.go:1187
        	            				testing.go:1203
        	            				testing.go:1034
        	Error Trace:	hsm_test.go:76
    hsm_test.go:76: 
```

### LINKED ISSUE #20217: `TestHSMDualAuthRotation` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/3899133392/jobs/6658521134
- https://github.com/gravitational/teleport/actions/runs/4318474372/jobs/7536803081

#### Relevant snippet

```
    hsm_test.go:701: 
        	Error Trace:	/__w/teleport/teleport/integration/hsm/hsm_test.go:701
        	            				/__w/teleport/teleport/integration/hsm/hsm_test.go:712
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestHSMDualAuthRotation
```

### PR DESCRIPTION
**Pull request by nklaassen**
This PR fixes the current flakiness of TestHSMMigrate and TestHSMDualAuthRotation.

I finally managed consistently to reproduce the errors we were seeing in CI by hacking lib/utils.LoadBalancer to introduce intermittent network errors. I found that connection problems to auth at certain times during proxy startup can cause the proxy process to exit without recovering. This is fairly likely to happen when a proxy is connected to two auth servers behind a load balancer, and they all reload ~simultaneously due to a CA rotation. The rough timeline to trigger the error is:

1. auth1 starts a rotation and reloads itself
1. proxy detects the rotation and triggers a reload
1. proxy connects to auth2 and gets a client
1. proxy starts proxy.init with the auth2 client
1. auth2 detects the rotation and triggers a reload
1. proxy.init fails and the proxy exits without recovering

The tests were relying on the proxy to always reload successfully during CA rotations. Whenever the tests flaked, the proxy was not reaching a ready state, and the logs match those I was able to reproduce.

This got markedly worse after https://github.com/gravitational/teleport/pull/36549, now that an auth no longer needs to be removed from the load balancer during a migration and the test was updated to reflect that.

We could arguably call this a product bug because the proxy is usually tolerant of temporarily losing a connection to Auth, but it seems non-trivial to recover from errors during a proxy reload. At that point there is already an old and new proxy running, the new one has failed to start and the old one hasn't completely shut down, it's not obvious what should be done. Currently the proxy process will exit and the systemd service should reload the process at that point.

For now, I have modified the HSM integration tests to avoid relying on any non-auth Teleport service reloads in any tests that use 2 auths behind a load balancer.

The changes in lib/auth/init.go fix a bug I found after re-enabling TestHSMDualAuthRotation, which I introduced in https://github.com/gravitational/teleport/pull/36780

Fixes https://github.com/gravitational/teleport/issues/14172
Fixes https://github.com/gravitational/teleport/issues/20217

### CODE REVIEW

File: integration/hsm/helpers.go [hunk 1]
```diff
@@ -111,17 +109,43 @@ func (t *teleportService) waitForNewProcess(ctx context.Context) error {
...
+		}
+	}()
+	select {
+	case err := <-waitForEventErr:
+		return trace.Wrap(err)
+	case err := <-t.errorChannel:
+		if err != nil {
+			return trace.Wrap(err, "process unexpectedly exited while waiting for event %s", event)
+		}
+		return trace.Errorf("process unexpectedly exited while waiting for event %s", event)
```
Comment (zmb3) [inline integration/hsm/helpers.go:130]: Isn't `err` nil in this case? Why are we returning an error?

Comment (nklaassen) [reply integration/hsm/helpers.go:130]: Yes it's nil, but the only thing written to this `errorChannel` is the result of `service.Run` which should not return until the service is closed. It should not even return when the process is just reloading, only when it actually exits. Even if it somehow returned a nil error, in this function we are waiting for an event, if the service just exited before we got the event then that's an error

**Review by zmb3 — APPROVED** [review]

File: integration/hsm/helpers.go [hunk 2]
```diff
@@ -60,9 +61,6 @@ func newTeleportService(t *testing.T, config *servicecfg.Config, name string) *t
 		serviceChannel: make(chan *service.TeleportProcess, 1),
 		errorChannel:   make(chan error, 1),
 	}
-	t.Cleanup(func() {
-		require.NoError(t, s.close(), "error while closing %s during test cleanup", name)
-	})
```
Comment (greedy52) [inline integration/hsm/helpers.go:65]: curious why this cleanup is removed?

**Review by greedy52 — APPROVED** [review]

File: integration/hsm/helpers.go (hunk 2 above)
Comment (nklaassen) [reply integration/hsm/helpers.go:65]: just because it doesn't really matter, slows down the test, doesn't usually work if the test failed, and lots of people in https://github.com/gravitational/teleport/issues/14172 were reporting the cleanup errors instead of the actual/initial error
