### PR TITLE
Change utmp error handling to best-effort

### LINKED ISSUE #6782: Detect musl at runtime and don't call utmp functions.
As reported in https://github.com/gravitational/teleport/pull/6192, When running Teleport in an alpine container, you get the following error when attempting to start as shell.

```
disconnected
Failed to launch: failed to select file.
```

As @coderigo reported:

```
This is due to the presence of but inability to handle utmp/wtmp. As it happens, the offical musl docs flag
this as a basically-useless and possibly-harmful “feature” - see ref here.
```

To fix this, Teleport should attempt to discover the libc version at runtime if musl is found, not call the utmp functions.

### PR DESCRIPTION
**Pull request by nklaassen**
Issue #6782

Since utmp support is meant to be best effort, this change departs a bit from the issue description - rather than attempting to detect musl at runtime, if there is any error in `uacc.Open(...)` we can just give up on utmp support and continue with the user's command.

I considered logging the error from `uacc.Open(...)`, but since teleport has already been re-exec'd at this point the output would be mixed in with the user command's output rather than the teleport log.

If `uacc.Open(..)` was successful but there is an error with `uacc.Close(...)`, then something unexpected has happened and we should return the error.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/6782

### CODE REVIEW

**Review by xacrimon — APPROVED** [review]

File: lib/srv/reexec.go [hunk 1]
```diff
@@ -165,10 +165,7 @@ func RunCommand() (io.Writer, int, error) {
 		errorWriter = tty
 		err = uacc.Open(c.UaccMetadata.UtmpPath, c.UaccMetadata.WtmpPath, c.Login, c.UaccMetadata.Hostname, c.UaccMetadata.RemoteAddr, tty)
 		if err != nil {
-			// the error is critical and we should fail command execution
-			if !trace.IsAccessDenied(err) && !trace.IsNotFound(err) {
-				return errorWriter, teleport.RemoteCommandFailure, trace.Wrap(err)
-			}
+			// uacc support is best-effort, just disable it and continue
```
Comment (smallinsky) [inline lib/srv/reexec.go:168]: nit: Move it to log debug ?

**Review by smallinsky — APPROVED** [review]

File: lib/srv/reexec.go (hunk 1 above)
Comment (nklaassen) [reply lib/srv/reexec.go:168]: I considered that, but at this point teleport has re-executed itself and stdout and stderr will be used for the output of the child command and returned to the user rather than written to the teleport log

File: lib/srv/reexec.go [hunk 2]
```diff
@@ -165,10 +165,7 @@ func RunCommand() (io.Writer, int, error) {
 		errorWriter = tty
 		err = uacc.Open(c.UaccMetadata.UtmpPath, c.UaccMetadata.WtmpPath, c.Login, c.UaccMetadata.Hostname, c.UaccMetadata.RemoteAddr, tty)
 		if err != nil {
```
Comment (r0mant) [inline lib/srv/reexec.go:167]: Nit: Seems this "if" branch is basically empty now, save for the comment, so you could do instead:

```go
// uacc support is best-effort, ...
if err == nil {
  uaccEnabled = true
}
```

File: lib/srv/reexec.go [hunk 3]
```diff
@@ -245,7 +242,7 @@ func RunCommand() (io.Writer, int, error) {
 
 	if uaccEnabled {
 		uaccErr := uacc.Close(c.UaccMetadata.UtmpPath, c.UaccMetadata.WtmpPath, tty)
-		if uaccErr != nil && !trace.IsAccessDenied(uaccErr) && !trace.IsNotFound(uaccErr) {
```
Comment (r0mant) [inline lib/srv/reexec.go:248]: So the change above makes uacc.Open best-effort, but this change here makes the condition more strict (i.e. we return any error now whereas previously access-denied/not-found were ignored). Is that intended?

File: lib/srv/reexec.go (hunk 2 above)
Comment (nklaassen) [reply lib/srv/reexec.go]: true, fixed in latest commit

File: lib/srv/reexec.go (hunk 3 above)
Comment (nklaassen) [reply lib/srv/reexec.go:248]: This was intentional on my part. In my mind, if Open passes there should be no good reason for Close to fail, and we should return the error to let the user know that their user accounting database may be in a bad state.

File: lib/srv/reexec.go [hunk 4]
```diff
@@ -164,12 +164,8 @@ func RunCommand() (io.Writer, int, error) {
...
 		errorWriter = tty
 		err = uacc.Open(c.UaccMetadata.UtmpPath, c.UaccMetadata.WtmpPath, c.Login, c.UaccMetadata.Hostname, c.UaccMetadata.RemoteAddr, tty)
-		if err != nil {
-			// the error is critical and we should fail command execution
-			if !trace.IsAccessDenied(err) && !trace.IsNotFound(err) {
-				return errorWriter, teleport.RemoteCommandFailure, trace.Wrap(err)
-			}
-		} else {
+		// uacc support is best-effort, only enable it if Open is successful
+		if err == nil {
```
Comment (r0mant) [inline lib/srv/reexec.go:168]: So there's no good way to log this error?

**Review by r0mant — APPROVED** [review]

File: lib/srv/reexec.go (hunk 4 above)
Comment (nklaassen) [reply lib/srv/reexec.go:168]: Currently the only way is to write it to stdout or stderr, both of which will also contain output of the actual command the user is trying to run, and they will be sent back to the user rather than written to the teleport logs. This doesn't seem like the right thing to do when the command is successful but utmp is unsupported.

With some more effort it would be possible to set up a pipe or something to communicate warning logs to the parent process out-of-band with the command output, let me know if you think this would be worthwhile

Comment (r0mant) [reply lib/srv/reexec.go:168]: @nklaassen It's ok, I would just leave a todo item or explanation as to why we're basically ignoring the error here.

Comment (nklaassen) [reply lib/srv/reexec.go:170]: thanks, I left a comment to that effect
