### PR TITLE
Make rejected connections easier to identify

### LINKED ISSUE #45139: Provide warnings on rejected connections in addition to login
Expected behavior:

Not just logins it would be good to provide warnings when a incompatible `tsh` is being used.  A user could be on v14 session with a v15. v15 is upgraded during their session to v16. The user should get a message on their incompatible client.

Current behavior:

If a user attempts to use `tsh` with a n+2  proxy/auth that's rejecting unsupported connections you get the following.

```bash
$ tsh ls
ERROR: error reading from server: EOF
```
They get a very generic error that doesn't tell them they are not using a valid version anymore.

Bug details:
- Teleport version: 16.1.1

### PR DESCRIPTION
**Pull request by rosstimothy**
Updates cluster alerts created when connections from clients with an unsupported version are rejected to allow identifying whether the connection was from an agent, a plugin, a client tool. The message is now targeted based on the user agent and identity of the connection and includes the system roles, host uuid, username, ip address.

tsh was also extended to display a version warning if any command executed failed by calling tc.Ping which analyzes the minimum client version in the response and outputs a message to standard error. During testing it was found that the connector specific ping endpoint was not populating this field, so that was updated as well.

Closes https://github.com/gravitational/teleport/issues/45139

Changelog: Improve discoverability of the source or rejected connections due to unsupported versions

### CODE REVIEW

**Review by hugoShaka — APPROVED** [review]

File: lib/auth/middleware.go [hunk 1]
```diff
@@ -466,9 +461,27 @@ func (a *Middleware) displayRejectedClientAlert(ctx context.Context, userAgent s
...
+
+	match := clientUARegex.FindStringSubmatch(userAgent)
+	i := ident.GetIdentity()
+	br, builtin := ident.(authz.BuiltinRole)
+	rbr, remoteBuiltin := ident.(authz.RemoteBuiltinRole)
+
+	var message string
+	switch {
+	case len(match) > 1: // A match indicates the connection was from a client tool
+		message = fmt.Sprintf("Connection from %s v%s by %s was rejected. Connections will be allowed after upgrading %s to >= v%s", match[1], clientVersion, i.Username, match[1], alertVersion.String())
```
Comment (zmb3) [inline lib/auth/middleware.go:473]:
```suggestion
		message = fmt.Sprintf("Connection from %s v%s by %s was rejected. Connections will be allowed after upgrading %s to v%s or newer", match[1], clientVersion, i.Username, match[1], alertVersion.String())
```

Similar for below.

**Review by zmb3 — APPROVED** [review]
Seems fine, one question though:

If multiple users/agents are connecting with unsupported versions,  will the alert "flap" and continue to update with whatever invalid version most recently attempted?
