### PR TITLE
Fix flaky test `TestHeadlessAuthenticationWatcher_WaitForUpdate`

### LINKED ISSUE #27682: `TestHeadlessAuthenticationWatcher_WaitForUpdate ` flakiness
Just hit it here: https://github.com/gravitational/teleport/actions/runs/5223904549/jobs/9431418640?pr=27652.

```
    headlessauthn_watcher_test.go:200: 
        	Error Trace:	/__w/teleport/teleport/lib/services/local/headlessauthn_watcher_test.go:200
        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestHeadlessAuthenticationWatcher_WaitForUpdate/ConditionMet
--- FAIL: TestHeadlessAuthenticationWatcher_WaitForUpdate/ConditionMet (5.01s)
```

### PR DESCRIPTION
**Pull request by Joerger**
Yet another flaky test fix for the headless authentication watcher. This time, I have removed the stale check system in favor of keeping the `Updates` channel populated with the most up-to-date update, draining old updates. This avoids unnecessary backend checks and makes the system much simpler. 

The race condition causing the flaky test was very rare and took >10,000 runs to reproduce locally. Essentially, it was possible for a subscriber to be marked as stale at the same time that the update channel is consumed. As a result, the main wait loop would not
catch the stale check and would instead wait for the main update. 

```go
select {
	case ha := <-subscriber.Updates():
		select {
		case <-subscriber.Stale():
			// If stale, then this update is not the most recent. Check the backend.
			ha, err = h.identityService.GetHeadlessAuthentication(ctx, subscriber.Name())
			if err != nil {
				return nil, trace.Wrap(err)
			}
		default:
		}
		if ok, err := cond(ha); err != nil {
			return nil, trace.Wrap(err)
		} else if ok {
			return ha, nil
		}
	case <-ctx.Done():
		return nil, trace.Wrap(ctx.Err())
	case <-h.Done():
		return nil, ErrHeadlessAuthenticationWatcherClosed
	}
}
```

This could have been solved in other ways, like adding a select case which checks the stale channel and drains updates, but I figured the new system without a stale channel is simpler and will avoid further issues.

Closes https://github.com/gravitational/teleport/issues/27682

Note: I am running this test >100k times locally to ensure the flakiness is fixed.

### CODE REVIEW

File: lib/services/local/headlessauthn_watcher.go [hunk 1]
```diff
@@ -316,11 +307,10 @@ func (h *HeadlessAuthenticationWatcher) unassignSubscriber(i int) {
...
 	name string
-	// updates is a channel used by the watcher to send resource updates.
-	updates chan *types.HeadlessAuthentication
-	// stale is a channel used to determine if the subscriber is stale and
-	// needs to check the backend for missed data.
-	stale chan struct{}
+	// updates is a channel used by the watcher to send resource updates. This channel
+	// will either be empty or have the latest update in its buffer.
+	updates    chan *types.HeadlessAuthentication
+	updatesMux sync.Mutex
```
Comment (zmb3) [inline lib/services/local/headlessauthn_watcher.go:313]: I usually read "mux" as short for multiplexer. How about updatesMu instead?

**Review by zmb3 — APPROVED** [review]

**Review by EdwardDowling — APPROVED** [review]
