### PR TITLE
block SFTP connections when moderated sessions are enforced

### LINKED ISSUE #17341: SFTP is not blocked in moderated session
#### Expected behavior:

SFTP and SCP should be blocked when users only have permission to connect in moderated sessions.

#### Current behavior:

SFTP is not blocked
```
% tsh ssh example.com
Teleport > Creating session with ID: 3d03ed78-15ff-4182-a65f-30e26cc94d18...
Teleport > Controls
  - CTRL-C: Leave the session
  - t: Forcefully terminate the session (moderators only)
Teleport > User bob joined the session.
Teleport > Waiting for required participants...
Teleport > Forcefully terminating session...
Teleport > Stopping session...
Teleport > Closing session...
Teleport > User bob left the session.
ERROR: Process exited with status 4294967295

% scp -O ubuntu@example.com:~/file.log . # Use SCP protocol
exec request failed on channel 0
% scp  ubuntu@example.com:~/file.log . # Use SFTP 
file.log
```

#### Bug details:
- Teleport version v10.1+
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by capnspacehook**
Fixes #17341.

### CODE REVIEW

File: lib/srv/ctx.go [hunk 1]
```diff
@@ -644,6 +647,28 @@ func (c *ServerContext) CheckFileCopyingAllowed() error {
...
+
+	// ensure moderated session policies allow starting an unattended session
+	policySets := c.Identity.AccessChecker.SessionPolicySets()
+	checker := auth.NewSessionAccessEvaluator(policySets, types.SSHSessionKind, c.Identity.TeleportUser)
+	canStart, _, err := checker.FulfilledFor(nil)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	if !canStart {
+		return trace.AccessDenied("lacking privileges to start unattended session")
```
Comment (nklaassen) [inline lib/srv/ctx.go:666]:
```suggestion
		return errCannotStartUnattendedSession
```

**Review by nklaassen — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

File: lib/srv/ctx.go (hunk 1 above)
Comment (capnspacehook) [reply lib/srv/ctx.go]: Thanks, done
