### PR TITLE
OIDC: validate the client_secret field

### LINKED ISSUE #39107: Improve error message when invalid `client_secret` is used
Customer updated `client_secret` on OIDC connector from `client_secret: some_value` to `client_secret: file://mnt/secret_file`. This format is unsupported, see https://github.com/gravitational/teleport/issues/6815. This format appears to be supported because the `oidc.google_service_account_uri` field does support it.

The error the customer did see was:

```
2024-02-22T09:59:41Z ERRO [WEB.ENTER] Error while processing callback. auth:oidc error:[
ERROR REPORT:
...
User Message: Failed to extract OIDC claims. Check your Google Workspace plan and enabled APIs. See: https://goteleport.com/docs/enterprise/sso/google-workspace/#ensure-your-google-workspace-plan-is-correct
```

## Proposed Solution

* Improve error message to guide so the customer knows to fix the `client_secret` value.
* Resolve https://github.com/gravitational/teleport/issues/6815 so the secret can be read from a file and does not have to be included in configuration.

### PR DESCRIPTION
**Pull request by zmb3**
- Make the client_secret required, as OIDC auth won't work without it
- Raise a clear error if unsupported file:// URLs are used

Closes #39107

image

### CODE REVIEW

File: api/types/oidc.go [hunk 1]
```diff
@@ -394,7 +395,15 @@ func (o *OIDCConnectorV3) CheckAndSetDefaults() error {
...
 
 	if o.Spec.ClientID == "" {
-		return trace.BadParameter("ClientID: missing client id")
+		return trace.BadParameter("OIDC connector is missing required client_id")
+	}
+
+	if o.Spec.ClientSecret == "" {
+		return trace.BadParameter("OIDC connector is missing required client_secret")
+	}
+	// note: remove this check when https://github.com/gravitational/teleport/issues/6815 is resolved
```
Comment (ryanclark) [inline api/types/oidc.go:404]: Should this have `TODO(zmb3):` as a prefix?

**Review by ryanclark — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]
I would just add a test for this, other than that ✅
