### PR TITLE
Web: Improve RDS flow 2

### LINKED ISSUE #44366: Resource enrollment flows should not default to "auto-discovery"
Currently all our resource enrollment flows have "auto-enroll" option turned on by default. Our original reasoning was that "we want users to enroll more resources" but in my opinion it hurts getting started experience. The purpose of Discover flows is to provide easy Day 1 UX where I want to kick the tires and quickly enroll a database that I maybe have or a server, etc. Auto-discovery is not Day 1. I propose we toggle this off by default.

Screenshot 2024-07-17 at 4 01 40 PM

### LINKED ISSUE #44368: Discover RDS database registration issues
While going through the RDS database enrollment flow, I encountered a number of failure cases during the first step.

## Database registration stalls sometimes

I managed to get in a state where "register database" would always fail with a timeout, even though the database itself was being registered in the cluster (and showed up in "tctl get db"):

Screenshot 2024-07-17 at 3 18 48 PM

I don't have exact repro steps but I suspect it's related to the fact that I wanted to do a "reset" and start from scratch so I removed the old database ECS service that would be proxying this database as the step resumed working after some time (I suspect after 10 minute TTL of the terminated ECS agent expired). We should handle this scenario more gracefully and not block the step.

## Failed to update database: database doesn't exist

I've seen the following error as well:

Screenshot 2024-07-17 at 3 19 17 PM

I'm not sure how exactly I got this, I _think_ this happened after encountering the timeout error above, I clicked "close", then removed the database using "tctl" and tried to enroll again by clicking "next" under the table.

## Already exists

Kind of the opposite of the above but once the database is registered, you can't get past this step without using CLI to remove it if e.g. you exited the flow early:

Screenshot 2024-07-17 at 4 08 29 PM

Feels like the UI should be able to handle this e.g. by giving user an option to force-overwrite it instead of asking to use CLI.

### PR DESCRIPTION
**Pull request by kimlisa**
resolves https://github.com/gravitational/teleport/issues/44368
resolves https://github.com/gravitational/teleport/issues/44366

🛑  requires https://github.com/gravitational/teleport/pull/45180

- EKS flow now defaults to single enrollment (ec2 was also touched, but we currently don't use it in our flow atm)
- Allows user to proceed to deploy step if querying for a database server times out (likely b/c database service shut down but is not expired yet from the back)
- Allows user to re-deploy database on auto deploy step (this helps single enrollment flows being stuck on the pending state and re-deploying allows them to change their security group and subnet selections)
- Also as discussed in discover meeting, removed custom label definer for auto deployment
- Improve pending state hint message
- Allows user to completely overwrite an existing database
- Emit "create discovery config" event for other parts of flow (eks and ec2)

image

image

no change log because it's an extension of https://github.com/gravitational/teleport/pull/44671 (it'll be backported together)

### CODE REVIEW

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx [hunk 1]
```diff
@@ -499,18 +486,57 @@ const DeployHints = ({
...
+          <Text>
+            Visit your AWS{' '}
+            <Link target="_blank" href={svcDeployedAwsUrl}>
+              dashboard
+            </Link>{' '}
+            to see progress details.
+          </Text>
+          <Text>
+            There are a couple of possible reasons for why we haven't been able
+            to detect your database service:
```
Comment (kimlisa) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:499]: cc @GavinFrazar the photo in the PR description is outdated, i'll update it when i get to it, but format is the same, the wording is slightly different starting from here

File: web/packages/teleport/src/Discover/Database/CreateDatabase/const.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+ *
+ * You should have received a copy of the GNU Affero General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+export const timeoutErrorMsg =
+  'Teleport could not detect your new database in time. Please try again.';
+
+export const dbWithoutDbServerExistsErrorMsg =
+  'already exists but there are no database servers for it';
```
Comment (GavinFrazar) [inline web/packages/teleport/src/Discover/Database/CreateDatabase/const.ts:23]:
```suggestion
  'already exists but there are no Teleport agents proxying it';
```

nit: I feel like the `db_server` vs `db` thing is not well understood by users, so maybe wording it like this instead is more clear?

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx [hunk 3]
```diff
@@ -499,18 +486,57 @@ const DeployHints = ({
...
+          </Text>
+          <ul
+            css={`
+              margin: 0;
+              padding-left: ${p => p.theme.space[3]}px;
+            `}
+          >
+            <li>
+              The subnets you selected does not route to an internet gateway
+              (igw) or a NAT gateway in a public subnet.
```
Comment (GavinFrazar) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:509]:
```suggestion
              The subnets you selected do not route to an internet gateway
              (igw) or a NAT gateway in a public subnet.
```

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx [hunk 4]
```diff
@@ -499,18 +486,57 @@ const DeployHints = ({
...
+            </li>
+            <li>
+              The security groups you selected does not allow outbound traffic
+              (eg: <Mark>0.0.0.0/0</Mark>) to reach Teleport cluster.
```
Comment (GavinFrazar) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:513]:
```suggestion
              The security groups you selected do not allow outbound traffic
              (eg: <Mark>0.0.0.0/0</Mark>) to pull the public Teleport image and to reach your Teleport cluster.
```

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx [hunk 5]
```diff
@@ -499,18 +486,57 @@ const DeployHints = ({
...
+            </li>
+            <li>
+              The security group attached to your database(s) does not allow
+              inbound traffic from the security group you selected or does not
+              allow inbound traffic from all IPs in the subnets you selected.
```
Comment (GavinFrazar) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:518]:
```suggestion
              The security groups attached to your database(s) neither allow
              inbound traffic from the security group you selected nor allow
              inbound traffic from all IPs in the subnets you selected.
```

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx [hunk 6]
```diff
@@ -499,18 +486,57 @@ const DeployHints = ({
...
+                target="_blank"
+                href="https://health.aws.amazon.com/health/status"
+              >
+                AWS Health Dashboard
+              </ExternalLink>{' '}
+              for any problems.
+            </li>
+            <li>
+              The network may be slow. Try continuing to wait for a few more
+              minutes or{' '}
```
Comment (GavinFrazar) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:533]:
```suggestion
              The network may be slow. Try waiting for a few more
              minutes or{' '}
```

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx [hunk 7]
```diff
@@ -499,18 +486,57 @@ const DeployHints = ({
...
+              <AlternateInstructionButton onClick={abortDeploying}>
+                try manually deploying your own service.
```
Comment (GavinFrazar) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:535]:
```suggestion
                try manually deploying your own database service.
```

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx [hunk 8]
```diff
@@ -499,18 +486,57 @@ const DeployHints = ({
...
+        <Flex flexDirection="column" gap={3}>
+          <Text>
+            Visit your AWS{' '}
+            <Link target="_blank" href={svcDeployedAwsUrl}>
+              dashboard
+            </Link>{' '}
+            to see progress details.
+          </Text>
+          <Text>
+            There are a couple of possible reasons for why we haven't been able
```
Comment (GavinFrazar) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:498]:
```suggestion
            There are a few possible reasons for why we haven't been able
```

File: web/packages/teleport/src/Discover/Database/CreateDatabase/const.ts [hunk 9]
```diff
@@ -20,4 +20,4 @@ export const timeoutErrorMsg =
   'Teleport could not detect your new database in time. Please try again.';
 
 export const dbWithoutDbServerExistsErrorMsg =
-  'already exists but there are no database servers for it';
+  'already exists but there are no Teleport agents proxying for it';
```
Comment (GavinFrazar) [inline web/packages/teleport/src/Discover/Database/CreateDatabase/const.ts:23]:
```suggestion
  'already exists but there are no Teleport agents proxying it';
```

File: web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.tsx [hunk 10]
```diff
@@ -49,21 +57,42 @@ export function CreateDatabaseDialog({
...
+   * but no db_server heartbeats. Most likely cause is because db_service
+   * has been stopped but is not removed from teleport yet (there is some
+   * minutes delay on expiry)
+   */
+  const skipOnTimeout =
+    attempt.status === 'failed' && attempt.statusText === timeoutErrorMsg;
+
   let content: JSX.Element;
-  if (attempt.status === 'failed') {
+  if (attempt.status === 'failed' && !skipOnTimeout) {
```
Comment (ravicious) [inline web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.tsx:73]: Also, regarding `else if (attempt.status === 'processing')` below: I'm not sure if it matters that much here, but I think it's a good practice to always account for the `''` status as well. In 90% the handling of it is similar to that of `processing`. But the way the conditional in this component is written at the moment means that if `attempt.status` ends up being set from within an effect from `''` to `'processing'`, for a split second we'll end up rendering the "success" branch of the conditional.

File: web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.tsx [hunk 11]
```diff
@@ -49,21 +57,42 @@ export function CreateDatabaseDialog({
...
       <>
         <Flex mb={5} alignItems="center">
-          {' '}
           <Icons.Warning size="large" ml={1} mr={2} color="error.main" />
           <Text>{attempt.statusText}</Text>
         </Flex>
-        <Flex>
-          <ButtonPrimary mr={3} width="50%" onClick={retry}>
+        <Flex gap={3}>
+          <ButtonPrimary width="50%" onClick={retry}>
```
Comment (ravicious) [inline web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.tsx:88]: `width` has no effect here because the parent flex doesn't set its width to 100%. Also, in practice three children with `width="50%"` work, but conceptually it's kinda weird. ;) It's a good candidate to set `flex: 1;` on each of the buttons, but also AFAIR we're yet to add support for `flex` on the button. It seems like it'd be a good idea, seeing how it's another place having access to such prop would be useful.

File: web/packages/teleport/src/services/integrations/types.ts [hunk 12]
```diff
@@ -318,8 +318,10 @@ export type AwsOidcDeployServiceRequest = {
   region: Regions;
   subnetIds: string[];
   taskRoleArn: string;
-  databaseAgentMatcherLabels: Label[];
+  databaseAgentMatcherLabels?: Label[];
```
Comment (ravicious) [inline web/packages/teleport/src/services/integrations/types.ts:321]: Is this field used anywhere in the UI? Grepping the project by its name doesn't yield any references to it.

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
Comment (ravicious) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:1]: idk if it's caused by this PR, but is it expected to some of the names to be empty?

no-name

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx [hunk 13]
```diff
@@ -268,36 +266,22 @@ export function AutoDeploy({ toggleDeployMethod }: DeployServiceProp) {
...
                 type="submit"
                 onClick={() => handleDeploy(validator)}
-                disabled={attempt.status === 'processing'}
+                disabled={isProcessing}
                 mt={2}
                 mb={2}
               >
-                Deploy Teleport Service
+                {isDeploying
+                  ? 'Redeploy Teleport Service'
```
Comment (ravicious) [inline web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:283]: When I'm in the story for this component and I click on "Redeploy Teleport Service", my position on the page is moved up. Is this supposed to happen? Maybe it has to do with some elements temporarily disappearing and then appearing again because `attempt.status` got updated?

https://github.com/user-attachments/assets/0ad12ab8-e444-4ff5-929d-b9aae4a564fd

File: web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.story.tsx [hunk 14]
```diff
@@ -40,11 +42,30 @@ export const Success = () => (
...
+    />
+  </>
+);
+
+export const AllowOverwrite = () => (
+  <CreateDatabaseDialog
+    {...props}
+    attempt={{ status: 'failed', statusText: dbWithoutDbServerExistsErrorMsg }}
+  />
+);
```
[the remark this answers is not in the document]
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.story.tsx:60]: oh that's just a story example, the actual looks like this:

image

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:1]: yes it's expected, it's not required for names to be defined in aws

File: web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.tsx (hunk 11 above)
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.tsx:88]: agh sorry that was mindless copy and paste

File: web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx (hunk 13 above)
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Database/DeployService/AutoDeploy/AutoDeploy.tsx:282]: i had to screen record this and see where the jump was coming from, but i think it's because when user hits `redeploy` the hint box hides during processing, but it happens so fast in stories that you couldn't see it.

it takes some ms for this to succeed during production though.

File: web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.story.tsx (hunk 14 above)
[the remark this answers is not in the document]
Comment (ravicious) [reply web/packages/teleport/src/Discover/Database/CreateDatabase/CreateDatabaseDialog.story.tsx:60]: I think it'd be good to update the example then so that it's closer to the real thing.

**Review by ravicious — APPROVED** [review]
Thanks for addressing that nit about `SuccessContent`!

**Comment by kimlisa** [comment]
PTAL? @rudream 🙏

**Review by rudream — APPROVED** [review]
