### PR TITLE
ensure higher severity alerts always take priority

### LINKED ISSUE #28965: tsh login does not show high severity cluster alerts
Expected behavior:
`tsh login` shows high severity alerts all the time.

Current behavior:

`tsh login` only shows high severity alerts if you are already logged in.

Reproduction steps:

```bash
tctl alerts create --severity=high "hello"

tsh logout 

tsh login <--- no alert will be displayed

tsh login <--- the alert will be displayed
```

### PR DESCRIPTION
**Pull request by fspmarshall**
Fixes https://github.com/gravitational/teleport/issues/28965

### CODE REVIEW

**Review by rosstimothy — APPROVED** [review]

**Review by probakowski — APPROVED** [review]

File: tool/tsh/common/tsh.go [hunk 1]
```diff
@@ -1927,21 +1927,13 @@ func onLogin(cf *CLIConf) error {
 		return trace.Wrap(err)
 	}
 
-	// Show on-login alerts, all high severity alerts are shown by onStatus
-	// so can be excluded here, except when Hardware Key Touch is required
-	// which skips on-status alerts.
-	alertSeverityMax := types.AlertSeverity_MEDIUM
-	if tc.PrivateKeyPolicy == keys.PrivateKeyPolicyHardwareKeyTouch {
```
Comment (zmb3) [inline tool/tsh/common/tsh.go:1934]: Do we no longer need to treat hardware key touch as a special case?

File: tool/common/common.go [hunk 2]
```diff
@@ -116,11 +116,11 @@ type ClusterAlertGetter interface {
 }
 
 // ShowClusterAlerts shows cluster alerts with the given labels and severity.
```
Comment (zmb3) [inline tool/common/common.go:118]: So we know show everything at the specified severity and higher? If so, can you update the godoc here? As written it sounds like we only show exactly the severity you asked for.

File: tool/tsh/common/tsh.go (hunk 1 above)
Comment (fspmarshall) [reply tool/tsh/common/tsh.go:1934]: We're now always doing what we used to only do for hardware key touch, so it's effectively always the special case.
