### PR TITLE
Require all audit events to be able to be trimmed

### LINKED ISSUE #36442: Event handler loop fails on large database events using Athena audit backend
Expected behavior:
Oversize database events should be trimmed to 1 MiB 

Current behavior:
```
ERRO   Error ingesting Audit Log err:rpc error: code = Unknown desc = db.session.postgres.statements.parse event e3c6ff72-3085-4d6f-8248-20aee63b38f4 is 1.1 MiB and cannot be returned because it exceeds the maximum response size of 1.0 MiB event-handler/events_job.go:96
ERRO   Watcher event loop failed error:[
ERROR REPORT:
Original Error: *status.Error rpc error: code = Unknown desc = db.session.postgres.statements.parse event e3c6ff72-3085-4d6f-8248-20aee63b38f4 is 1.1 MiB and cannot be returned because it exceeds the maximum response size of 1.0 MiB
Stack Trace:
    /go/pkg/mod/github.com/gravitational/teleport/api@v0.0.0-20231229230854-390d33c42bbe/client/client.go:2208 github.com/gravitational/teleport/api/client.(*Client).SearchUnstructuredEvents
    /workspace/event-handler/teleport_events_watcher.go:225 main.(*TeleportEventsWatcher).getEvents
    /workspace/event-handler/teleport_events_watcher.go:153 main.(*TeleportEventsWatcher).fetch
    /workspace/event-handler/teleport_events_watcher.go:262 main.(*TeleportEventsWatcher).Events.func1
    /usr/local/go/src/runtime/asm_amd64.s:1650 runtime.goexit
User Message: rpc error: code = Unknown desc = db.session.postgres.statements.parse event e3c6ff72-3085-4d6f-8248-20aee63b38f4 is 1.1 MiB and cannot be returned because it exceeds the maximum response size of 1.0 MiB] event-handler/events_job.go:81
ERRO   Terminating with fatal error [1]... error:[
ERROR REPORT:
Original Error: *status.Error rpc error: code = Unknown desc = db.session.postgres.statements.parse event e3c6ff72-3085-4d6f-8248-20aee63b38f4 is 1.1 MiB and cannot be returned because it exceeds the maximum response size of 1.0 MiB
Stack Trace:
    /go/pkg/mod/github.com/gravitational/teleport/api@v0.0.0-20231229230854-390d33c42bbe/client/client.go:2208 github.com/gravitational/teleport/api/client.(*Client).SearchUnstructuredEvents
    /workspace/event-handler/teleport_events_watcher.go:225 main.(*TeleportEventsWatcher).getEvents
    /workspace/event-handler/teleport_events_watcher.go:153 main.(*TeleportEventsWatcher).fetch
    /workspace/event-handler/teleport_events_watcher.go:262 main.(*TeleportEventsWatcher).Events.func1
    /usr/local/go/src/runtime/asm_amd64.s:1650 runtime.goexit
User Message: rpc error: code = Unknown desc = db.session.postgres.statements.parse event e3c6ff72-3085-4d6f-8248-20aee63b38f4 is 1.1 MiB and cannot be returned because it exceeds the maximum response size of 1.0 MiB] lib/bail.go:28
```

Bug details:
- Teleport version: v14

#35402 already implements trimming of large events in Athena querier. However, not all database events implements `TrimToMaxSize`.

### PR DESCRIPTION
**Pull request by capnspacehook**
We have encountered several audit events that sometimes are too large for a specific backend to process. Historically we've just addressed the offending events on a per-event basis. This PR requires all audit events to implement `TrimToMaxSize` to trim themselves to prevent this from happening again, and/or making it much easier to deal with large events in the future.

The `TrimToMaxSize` method has been implemented for all events, however for many events you will notice that the event is returned unchanged. When implementing these methods I only trimmed fields that are generally controlled by user input, or that can easily grow quite large (error messages for example). Many events have no such fields and as such don't attempt to trim themselves. Trimming general event metadata (`UserMetadata`, `ConnectionMetadata`, etc) was not in scope but this can be easily added in the future.

The existing code that calls `TrimToMaxSize` methods have been modified to take into account the fact that all audit events implement `TrimToMaxSize` and that trimming to a specific size may not be possible.

I recommend you review commit by commit. Most of the additions are `TrimToMaxSize` methods which are very repetitive  and verbose.

Fixes https://github.com/gravitational/teleport-private/issues/1299.
Fixes https://github.com/gravitational/teleport/issues/36442.

changelog: allow all audit events to be trimmed if necessary

### CODE REVIEW

File: api/types/events/api.go [hunk 1]
```diff
@@ -69,6 +69,12 @@ type AuditEvent interface {
 	GetClusterName() string
 	// SetClusterName sets the name of the teleport cluster on the event.
 	SetClusterName(string)
+
+	// TrimToMaxSize returns a copy of the event trimmed to a smaller
+	// size. The desired size may not be achievable so callers
+	// should always check the size of the returned event before
+	// using it.
```
Comment (flyinghermit) [inline api/types/events/api.go:76]: are all the fields in an audit event in scope for trimming? or this is only applied to specific fields?
I think that is worth explaining in this comment.

File: lib/events/events_test.go [hunk 2]
```diff
@@ -987,3 +995,145 @@ func TestEvents(t *testing.T) {
 		})
 	}
 }
+
+var (
```
Comment (flyinghermit) [inline lib/events/events_test.go:999]: nit: make this a const?

File: api/types/events/api.go [hunk 3]
```diff
@@ -69,6 +69,12 @@ type AuditEvent interface {
...
+	TrimToMaxSize(maxSize int) AuditEvent
```
Comment (flyinghermit) [inline api/types/events/api.go:77]: Does `TrimToMaxSize` cap on maximum or minimum size for the `maxSize` input? What are the chances of providing a smaller maxSize than necessary and loosing out important event data? Is that something we need to worry about?

File: lib/events/events_test.go (hunk 2 above)
Comment (flyinghermit) [reply lib/events/events_test.go:999]: Also looks like we can actually move them inside `getDefaultValue()` where they are used?

File: api/types/events/api.go (hunk 3 above)
Comment (capnspacehook) [reply api/types/events/api.go:77]: There's no hard min or max cap that is known beforehand, because only certain fields are trimmed the minimum `maxSize` input really depends on what other fields are set to in the event (ie in `UserMetadata` etc). I don't think it's really something to worry about, all callers of  `TrimToMaxSize` check that the trimmed event is small enough so this shouldn't be an issue

File: lib/events/events_test.go (hunk 2 above)
Comment (capnspacehook) [reply lib/events/events_test.go]: I can't make `eventString` a const and don't want to move it into `getDefaultValue` as that would run `strings.Repeat` every time `getDefaultValue` is called which seems wasteful

File: api/types/events/api.go (hunk 1 above)
Comment (capnspacehook) [reply api/types/events/api.go]: Good idea, added to comment

**Comment by greedy52** [comment]
This implementation does fix https://github.com/gravitational/teleport/issues/36442 which will prevent the event handler from crashing. 

But I don't think this fully addresses https://github.com/gravitational/teleport-private/issues/1299. Big events are now partially logged but the trimmed parts are lost. 

FYI, database events are duplicated to session recordings so it's kinda ok that db events are partially logged. But other types will likely lose the trimmed parts forever.

File: api/types/events/events.go [hunk 4]
```diff
@@ -45,94 +96,315 @@ func trimN(s string, n int) string {
...
+func (m *SessionPrint) TrimToMaxSize(maxSize int) AuditEvent {
+	return m
+}
+
 // TrimToMaxSize trims the SessionStart event to the given maximum size.
 // Currently assumes that the largest field will be InitialCommand and tries to
 // trim that.
-func (e *SessionStart) TrimToMaxSize(maxSize int) AuditEvent {
-	size := e.Size()
+func (m *SessionStart) TrimToMaxSize(maxSize int) AuditEvent {
```
Comment (greedy52) [inline api/types/events/events.go:290]: instead of implementing this one by one, is it possible to do some reflect magic for common struct and types?

Comment (capnspacehook) [reply api/types/events/events.go:290]: A reflection based approach was my first thought and I actually made a PoC for it first. However due to the additional overhead and increased memory usage combined with the code complexity it was decided that manual methods would be created instead. It's possible, but we want to avoid complex "magic" code where we can.

**Comment by capnspacehook** [comment]
@greedy52 trimming isn't ideal, but it should be a relatively rare occurrence. Since only certain fields are trimmed, most fields will still have the original data fully intact. Currently larger events are dropped, so trimming certain fields is better than dropping the whole thing.

When I was discussing this with @r0mant he did mention that it would probably be possible to spit large events into several smaller events, but for now we are just going to trim events because events that are too large are pretty rare and trimming is much simpler to implement.

**Comment by greedy52** [comment]
> gravitational/teleport-private#1299

Not opposing to this solution. Just saying this does not fully fix https://github.com/gravitational/teleport-private/issues/1299. We should either leave the issue open, or create a separate issue to track that trimmed parts are missing from audit logs.

**Review by r0mant — APPROVED** [review]

**Review by greedy52 — APPROVED** [review]

File: lib/events/stream.go [hunk 5]
```diff
@@ -390,10 +390,8 @@ func (s *ProtoStream) RecordEvent(ctx context.Context, pe apievents.PreparedSess
 	event := pe.GetAuditEvent()
 	messageSize := event.Size()
 	if messageSize > MaxProtoMessageSizeBytes {
-		switch v := event.(type) {
-		case messageSizeTrimmer:
-			event = v.TrimToMaxSize(MaxProtoMessageSizeBytes)
-		default:
+		event = event.TrimToMaxSize(MaxProtoMessageSizeBytes)
+		if event.Size() > MaxProtoMessageSizeBytes {
```
Comment (greedy52) [inline lib/events/stream.go:394]: Will this still be possible after trimming, or will it be rare? Any way to prevent the event handler from crashing when running into this case?

Comment (capnspacehook) [reply lib/events/stream.go:394]: This will still be possible but should be very rare, as some metadata is not trimmed but is unlikely to be very large. I don't think returning an error here will cause the event handler to crash, an error could be returned here before and I don't believe this caused the event handler to crash.

File: api/types/events/api.go [hunk 6]
```diff
@@ -69,6 +69,14 @@ type AuditEvent interface {
...
 	// SetClusterName sets the name of the teleport cluster on the event.
 	SetClusterName(string)
+
+	// TrimToMaxSize returns a copy of the event trimmed to a smaller
+	// size. The desired size may not be achievable so callers
+	// should always check the size of the returned event before
+	// using it. Generally fields that are unique to the event
+	// will be trimmed, other fields are not currently modified
+	// (ie *Metadata messages).
+	TrimToMaxSize(maxSize int) AuditEvent
```
[the remark this answers is not in the document]
Comment (capnspacehook) [reply api/types/events/api.go]: Done
