### PR TITLE
Fix memory leak on Kubernetes port-forwarding

### LINKED ISSUE #10966: Memory leak when using Kubernetes port-forwarding
### Description

**What happened**:

Customer is seeing their Kubernetes agents and proxies memory increase and never release when using a custom tool against Teleport Kubernetes Access which opens many port-forward connections. The customer is claiming that even after stopping the tool, Kube agent does not release connections to Kubernetes API server.

Attached are a few Go profile dumps (goroutine/cpu/heap) from 2 runs: [profile.zip](https://github.com/gravitational/teleport/files/8208555/profile.zip). Goroutine dumps show a lot of connection monitor goroutines which seems to support the theory of connections not being closed.

Number of goroutines/open FDs also seems to increase:

Screen Shot 2022-03-08 at 10 02 54 AM

Screen Shot 2022-03-08 at 10 03 06 AM

Screen Shot 2022-03-08 at 10 03 13 AM

Let's see if we can try to reproduce this and see if this is a bug or something specific to the customer environment.

### Server Details
- Teleport version (run `teleport version`): 8.x

### PR DESCRIPTION
**Pull request by tigrato**
This PR fixes a memory leak on Kubernetes access when using the SPDY protocol - used by `kubectl`.

The memory leak happens when a new connection is established using the SPDY's HTTPStreams. Each time a new connection is created locally, `kubectl` creates two streams for it - one for data and another for returning errors. When the multiplexed streams finish, they weren't properly cleanup from the SPDY connection and, although closed, their memory was kept alive and reachable for the duration of the SPDY long-lived connection. This ends up leaking memory and results in OOM events for the Proxy and Kubernetes services if a large number of connections are established within the same port-forwarding session.

Fixes #10966

### CODE REVIEW

File: lib/kube/proxy/portforward_spdy.go [hunk 1]
```diff
@@ -174,77 +173,54 @@ func (h *portForwardProxy) forwardStreamPair(p *httpStreamPair, remotePort int64
 
 	// read and write from the error stream
 	targetErrorStream, err := h.targetConn.CreateStream(headers)
+	h.onPortForward(fmt.Sprintf("%v:%v", h.podName, remotePort), err == nil /* success */)
 	if err != nil {
-		h.onPortForward(fmt.Sprintf("%v:%v", h.podName, remotePort), false)
-		return trace.ConnectionProblem(err, "error creating error stream for port %d", remotePort)
+		err := trace.ConnectionProblem(err, "error creating error stream for port %d", remotePort)
+		p.sendErr(err)
+		p.close()
```
Comment (codingllama) [inline lib/kube/proxy/portforward_spdy.go:180]: I noticed we close `p` on errors, but not on success. Who "owns" `p`? Is it feasible to make a single place responsible for closing it?

An alternative is to document the behavior of `forwardStreamPair` in regards to `p`, so others looking at it knows what it's expected to do.

File: lib/kube/proxy/portforward_spdy.go [hunk 2]
```diff
@@ -174,77 +173,54 @@ func (h *portForwardProxy) forwardStreamPair(p *httpStreamPair, remotePort int64
...
+	defer func() {
+		// on stream close, remove the stream from the connection and close it.
+		h.targetConn.RemoveStreams(targetErrorStream)
+		targetErrorStream.Close()
 	}()
+	wg := &sync.WaitGroup{}
+	wg.Add(1)
 
-	errClose := make(chan struct{})
 	go func() {
```
Comment (codingllama) [inline lib/kube/proxy/portforward_spdy.go:191]: nit: Keep the `Add` right beside the `go`.

```suggestion

	wg.Add(1)
	go func() {
```

File: lib/kube/proxy/portforward_spdy.go [hunk 3]
```diff
@@ -174,77 +173,54 @@ func (h *portForwardProxy) forwardStreamPair(p *httpStreamPair, remotePort int64
...
-		h.Debugf("Context is closing, cleaning up.")
-	}
-
-	// always expect something on errorChan (it may be nil)
-	select {
-	case <-errClose:
-	case <-h.context.Done():
-		h.Debugf("Context is closing, cleaning up.")
-	}
+	wg.Wait()
```
Comment (codingllama) [inline lib/kube/proxy/portforward_spdy.go:223]: Collecting all goroutines before returning a func is always a +1 for me. 👍

File: lib/kube/proxy/portforward_spdy.go [hunk 4]
```diff
@@ -326,8 +309,8 @@ func (h *portForwardProxy) run() {
 				go h.monitorStreamPair(p, time.After(h.streamCreationTimeout))
 			}
 			if complete, err := p.add(stream); err != nil {
-				msg := fmt.Sprintf("error processing stream for request %s: %v", requestID, err)
-				p.printError(msg)
+				err := trace.Errorf("error processing stream for request %s: %v", requestID, err)
```
Comment (codingllama) [inline lib/kube/proxy/portforward_spdy.go:312]: I've been told before to avoid naked trace.Errorf, so passing it along:

```suggestion
				err := trace.BadParameter("error processing stream for request %s: %v", requestID, err)
```

**Review by codingllama — COMMENTED** [review]
It would be great to have a regression test for this, but I suppose it would be fairly difficult to test - either we'd have to measure memory, which takes a while and can be finicky, or we'd have to change production code in unnatural ways.

File: lib/kube/proxy/portforward_spdy.go (hunk 1 above)
Comment (tigrato) [reply lib/kube/proxy/portforward_spdy.go:180]: Moved the closing logic to the `portForward` function.

**Review by codingllama — APPROVED** [review]

File: lib/kube/proxy/portforward_spdy.go [hunk 5]
```diff
@@ -174,77 +178,53 @@ func (h *portForwardProxy) forwardStreamPair(p *httpStreamPair, remotePort int64
 
 	// read and write from the error stream
 	targetErrorStream, err := h.targetConn.CreateStream(headers)
+	h.onPortForward(fmt.Sprintf("%v:%v", h.podName, remotePort), err == nil /* success */)
```
Comment (zmb3) [inline lib/kube/proxy/portforward_spdy.go:181]:
```suggestion
	h.onPortForward(net.JoinHostPort(h.podName, remotePort), err == nil /* success */)
```

**Review by zmb3 — APPROVED** [review]

File: lib/kube/proxy/portforward_test.go [hunk 6]
```diff
@@ -213,3 +219,171 @@ type portForwarder interface {
...
+	h.run()
+	// targetConn is closed once all streams are removed. It is an hack to
+	// unblock the targetConn.waitForClose() call otherwise it will block
+	// forever.
+	targetConn.waitForClose()
+	// Make sure all streams are removed from the connection.
+	require.Empty(t, sourceConn.streams)
+	// Make sure all streams are removed from the connection.
+	require.Empty(t, targetConn.streams)
+	require.True(t, sourceConn.wereStreamsClosed())
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:278]:
```suggestion
	require.True(t, sourceConn.wereStreamsClosed(), "sourceConn streams not closed")
```

File: lib/kube/proxy/portforward_test.go [hunk 7]
```diff
@@ -213,3 +219,171 @@ type portForwarder interface {
...
+	require.True(t, targetConn.wereStreamsClosed())
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:279]:
```suggestion
	require.True(t, targetConn.wereStreamsClosed(), "targetConn streams not closed")
```

File: lib/kube/proxy/portforward_test.go [hunk 8]
```diff
@@ -213,3 +219,171 @@ type portForwarder interface {
...
+}
+
+var _ httpstream.Stream = (*fakeSPDYStream)(nil)
+
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:283]: Guaranteed by use, assertion shouldn't be necessary.

```suggestion
```

File: lib/kube/proxy/portforward_test.go [hunk 9]
```diff
@@ -213,3 +219,171 @@ type portForwarder interface {
...
+	return f.identifier
+}
+
+func (f *fakeSPDYStream) Close() error {
+	f.closed = true
+	return nil
+}
+
+var _ httpstream.Connection = (*fakeSPDYConnection)(nil)
+
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:316]: Same.

```suggestion
```

File: lib/kube/proxy/portforward_test.go [hunk 10]
```diff
@@ -213,3 +219,171 @@ type portForwarder interface {
...
+func newfakeSPDYConnection() *fakeSPDYConnection {
+	return &fakeSPDYConnection{
+		streams: make(map[uint32]*fakeSPDYStream),
+		closed:  make(chan bool),
+	}
+}
+
+// CreateStream creates a new Stream with the supplied headers.
+func (f *fakeSPDYConnection) CreateStream(headers http.Header) (httpstream.Stream, error) {
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:333]: We don't expect concurrent access here, right?

Should we use a lock just in case this changes in the future, or do you think that's too unlikely?

File: lib/kube/proxy/portforward_test.go [hunk 11]
```diff
@@ -213,3 +219,171 @@ type portForwarder interface {
...
+}
+
+var _ httpstream.Connection = (*fakeSPDYConnection)(nil)
+
+type fakeSPDYConnection struct {
+	count        int
+	streams      map[uint32]*fakeSPDYStream
+	streamsSlice []*fakeSPDYStream
+	closed       chan bool
+	once         sync.Once
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:322]: Maybe?

```suggestion
	closedOnce   sync.Once
```

File: lib/kube/proxy/portforward_test.go [hunk 12]
```diff
@@ -213,3 +219,171 @@ type portForwarder interface {
...
+
+// CloseChan returns a channel that is closed when the underlying connection is closed.
+func (f *fakeSPDYConnection) CloseChan() <-chan bool {
+	return f.closed
+}
+
+// SetIdleTimeout sets the amount of time the connection may remain idle before
+// it is automatically closed.
+func (f *fakeSPDYConnection) SetIdleTimeout(_ time.Duration) {
+}
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:362]: nit:

```suggestion
func (f *fakeSPDYConnection) SetIdleTimeout(_ time.Duration) {}
```

File: lib/kube/proxy/portforward_spdy.go [hunk 13]
```diff
@@ -401,10 +390,25 @@ func (p *httpStreamPair) add(stream httpstream.Stream) (bool, error) {
 }
 
 // printError writes s to p.errorStream if p.errorStream has been set.
```
Comment (AntonAM) [inline lib/kube/proxy/portforward_spdy.go:392]: function name in godoc needs fixing.

File: lib/kube/proxy/portforward_test.go [hunk 14]
```diff
@@ -213,3 +219,171 @@ type portForwarder interface {
...
+	if len(f.streams) == 0 {
+		f.Close()
+	}
+}
+
+func (f *fakeSPDYConnection) waitForClose() {
+	<-f.closed
+}
+
+func (f *fakeSPDYConnection) wereStreamsClosed() bool {
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:382]: Suggestion: I would go with `streamsClosed` or maybe `isStreamsClosed`, out of habit most likely.

**Review by codingllama — APPROVED** [review]
I wasn't really expecting a test, this is a nice surprise.

Silly Q, but have you tried running the test before the fix? Does it behave as expected?

**Review by AntonAM — APPROVED** [review]

**Comment by tigrato** [comment]
> Silly Q, but have you tried running the test before the fix? Does it behave as expected?

yes. Since the streams weren't removed, the eventually loop fails
