### PR TITLE
Store `host_uuid` into Kubernetes Secret

### LINKED ISSUE #17474: `host_uuid` is never stored in Kubernertes Secret and does not survive Pod w/out storage restart
Expected behavior:
`host_uuid` must survive pod restarts when no storage is configured

Current behavior:
The `host_uuid` value changes each time a pod is restarted which results in authentication failure.

Bug details:
- Teleport version
11.0.0-beta.x
- Debug logs
`Inventory control stream failed: inventory control stream closed: control streams do not support impersonation ("e342d190-62ea-4e75-8999-82bb4759cf39" -> "a7be082a-3a79-44da-850f-53a6f1a35ade") inventory/inventory.go:146`

### PR DESCRIPTION
**Pull request by tigrato**
When recovering after a restart, `host_uuid` changes and Auth Server authentication fails. This happens because `host_uuid` is not stored in the Kubernetes Secret but it's stored in the certificate Common Name.
This PR forces the storage of the `host_uuid` into Kubernetes Secrets for later reuse.

Fixes #17474

### CODE REVIEW

File: lib/utils/utils.go [hunk 1]
```diff
@@ -452,9 +454,24 @@ func GetFreeTCPPorts(n int, offset ...int) (PortList, error) {
...
+	_, err := ReadPath(filepath.Join(dataDir, HostUUIDFile))
+	return err == nil
+}
+
 // ReadHostUUID reads host UUID from the file in the data dir
 func ReadHostUUID(dataDir string) (string, error) {
 	out, err := ReadPath(filepath.Join(dataDir, HostUUIDFile))
+	// When running in a Kubernetes Cluster we need to check if the `host_uuid`
+	// was previously written into the Secret.
+	if err != nil && kubernetes.InKubeCluster() {
```
Comment (r0mant) [inline lib/utils/utils.go:468]: My 2c is I would handle "if inside Kubernetes, do this" logic outside of these simple "Read/WriteHostUUID" method that are supposed to just deal with files. I'd let it return an error and handle it on the caller side.

File: lib/utils/utils.go [hunk 2]
```diff
@@ -469,6 +486,39 @@ func ReadHostUUID(dataDir string) (string, error) {
...
 
+// writeHostUUIDToKubeSecret reads the host_uuid from the Kubernetes secret
+// with the expected key: `/host_uuid`.
+func loadHostUUIDFromKubeSecret() ([]byte, error) {
+	st, err := kubernetes.New()
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+
+	k, err := st.Get(context.Background(), backend.Key(HostUUIDFile))
```
Comment (r0mant) [inline lib/utils/utils.go:497]: Pass context to the method.

File: lib/utils/utils.go [hunk 3]
```diff
@@ -469,6 +486,39 @@ func ReadHostUUID(dataDir string) (string, error) {
...
+// writeHostUUIDToKubeSecret writes the host_uuid into the Kubernetes secret
+// under the key `/host_uuid`.
+func writeHostUUIDToKubeSecret(id string) error {
+	st, err := kubernetes.New()
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	_, err = st.Put(
+		context.Background(),
```
Comment (r0mant) [inline lib/utils/utils.go:513]: Pass context to the method.

File: lib/utils/utils.go (hunk 1 above)
Comment (tigrato) [reply lib/utils/utils.go]: fair

File: lib/service/service.go [hunk 4]
```diff
@@ -4813,3 +4822,73 @@ func isDebugMode() bool {
...
+	// Even if running in Kubernetes fallback to local storage if `host_uuid` was
+	// not found in secret.
+	hostUUID, err := utils.ReadHostUUID(dataDir)
+	return hostUUID, trace.Wrap(err)
+}
+
+// persistHostUUIDToStorages writes the HostUUID to local data and  and to
+// Kubernetes Secret if this process is running on a Kubernetes Cluster.
+func persistHostUUIDToStorages(ctx context.Context, cfg *Config) error {
+	if err := utils.WriteHostUUID(cfg.DataDir, cfg.HostUUID); err != nil {
```
Comment (r0mant) [inline lib/service/service.go:4847]: When running inside Kubernetes, why does it need to be saved to filesystem? `readHostUUIDFromStorages` will still read it from a secret, no?

File: lib/service/service.go [hunk 5]
```diff
@@ -873,10 +883,15 @@ func NewTeleport(cfg *Config, opts ...NewTeleportOption) (*TeleportProcess, erro
...
-			}
+		// persistHostUUIDToStorages will persist the host_uuid to the local storage
+		// and to Kubernetes Secret if this process is running on a Kubernetes Cluster.
+		if err := persistHostUUIDToStorages(supervisor.ExitContext(), cfg); err != nil {
+			return nil, trace.Wrap(err)
+		}
+	} else if kubernetes.InKubeCluster() && utils.HostUUIDExistsLocaly(cfg.DataDir) {
+		// Forces the copy of the host_uuid into the Kubernetes Secret if PV storage is enabled.
+		// This is only required if PV storage is removed later.
+		if err := persistHostUUIDToStorages(supervisor.ExitContext(), cfg); err != nil {
```
Comment (r0mant) [inline lib/service/service.go:894]: As implemented, this will try to save it to file again even though it already exists, see my comment below. Would it make sense to either update this function to not save to file when in K8s, or call writeHostUUIDToKubeSecret directly here?

**Review by r0mant — COMMENTED** [review]
This PR also needs test coverage (and some thorough manual testing).

File: lib/utils/utils.go [hunk 6]
```diff
@@ -452,6 +452,12 @@ func GetFreeTCPPorts(n int, offset ...int) (PortList, error) {
 	return PortList{ports: list}, nil
 }
 
+// HostUUIDExistsLocaly checks if dataDir/host_uuid file exists in local storage.
+func HostUUIDExistsLocaly(dataDir string) bool {
```
Comment (espadolini) [inline lib/utils/utils.go:456]: I'd just use `ReadHostUUID` and discard the string value, either instead of this function or instead of `ReadPath` here.

File: lib/service/service.go [hunk 7]
```diff
@@ -4813,3 +4822,73 @@ func isDebugMode() bool {
...
 	return v
 }
+
+// readHostUUUIDFromStorage tries to read the `host_uuid` value from different storages,
+// depending on where the process is running.
+// If the process is running in a Kubernetes Cluster, this function will attempt
+// to read the `host_uuid` from the Kubernetes Secret. If it does not exist or
+// if it is not running on a Kubernetes cluster the read is done from the local
+// storage: `dataDir/host_uuid`.
+func readHostUUIDFromStorages(ctx context.Context, dataDir string) (string, error) {
```
Comment (espadolini) [inline lib/service/service.go:4832]:
```suggestion
func readHostIDFromStorage(ctx context.Context, dataDir string) (string, error) {
```

I'm not sure if it ever applies to kube pods, but the host ID is not guaranteed to be a UUID, as we're also allowing EC2 instance IDs, so for naming consistency I'd refer to it as "host ID", here and in the following functions.

File: lib/service/service.go [hunk 8]
```diff
@@ -4813,3 +4822,73 @@ func isDebugMode() bool {
...
+	if kubernetes.InKubeCluster() {
+		if hostUUID, err := loadHostUUIDFromKubeSecret(ctx); err == nil && len(string(hostUUID)) > 0 {
```
Comment (espadolini) [inline lib/service/service.go:4834]: Already a `string`:
```suggestion
		if hostUUID, err := loadHostUUIDFromKubeSecret(ctx); err == nil && len(hostUUID) > 0 {
```

File: lib/service/service.go (hunk 4 above)
Comment (espadolini) [reply lib/service/service.go:4847]: I reckon that `tctl` might need the file on disk to work properly - although that would only apply to the auth server storing its own credentials in kubernetes, which isn't really needed.

Comment (tigrato) [reply lib/service/service.go:4847]: Kube secret identity storage only applies to the Kube Agent chart which does not have the auth server.
I wrote the `host_uuid` to disk for the cases where storage is enabled and we need to downgrade to a pre-11 version

**Review by r0mant — APPROVED** [review]
@espadolini Can you take another look as well pls?

File: lib/service/service.go [hunk 9]
```diff
@@ -832,64 +833,33 @@ func NewTeleport(cfg *Config, opts ...NewTeleportOption) (*TeleportProcess, erro
...
+	// `host_uuid` from local data directory.
+	// If no host id is available, it will generate a new host id and persist it to available storages.
+	if err := readOrGenerateHostID(supervisor.ExitContext(), cfg, kubeBackend); err != nil {
+		return nil, trace.Wrap(err)
 	}
 
-	supervisor := NewSupervisor(processID, cfg.Log)
-	storage, err := auth.NewProcessStorage(supervisor.ExitContext(), filepath.Join(cfg.DataDir, teleport.ComponentProcess))
+	_, err = uuid.Parse(cfg.HostUUID)
 	if err != nil {
```
Comment (espadolini) [inline lib/service/service.go:861]: While we're touching this, this is the actual (inverse of the) check in `(*proxySubsys).getMatchingServer`, but totally fine if you don't want to bother as it's not really the point of this PR anyway.
```suggestion
	_, err = uuid.Parse(cfg.HostUUID)
	if err != nil && !utils.IsEC2NodeId(cfg.HostUUID) {
```

File: lib/service/service.go [hunk 10]
```diff
@@ -4813,3 +4783,146 @@ func isDebugMode() bool {
...
+			return hostID, nil
+		}
+	}
+	// Even if running in Kubernetes fallback to local storage if `host_uuid` was
+	// not found in secret.
+	hostID, err := utils.ReadHostUUID(dataDir)
+	return hostID, trace.Wrap(err)
+}
+
+// persistHostIDToStorages writes the cfg.HostUUID to local data and  and to
```
Comment (espadolini) [inline lib/service/service.go:4888]:
```suggestion
// persistHostIDToStorages writes the cfg.HostUUID to local data and to
```

File: lib/utils/utils.go (hunk 6 above)
Comment (espadolini) [inline lib/utils/utils.go:456]:
```suggestion
func HostUUIDExistsLocally(dataDir string) bool {
```

**Review by espadolini — APPROVED** [review]
