### PR TITLE
Fix `certificate signed by unknown authority` after reconciling a dynamic RDS resource

### LINKED ISSUE #19395: `certificate signed by unknown authority` after reconciling a dynamic RDS resource
## Expected behavior

Updating a dynamic `RDS` resource should not result in a loss of access to the database.

## Current behavior
Once the DB agent reconciliation ends, the DB becomes unavailable to everyone and returns the following error:

```
psql: error: connection to server at "localhost" (127.0.0.1), port 56481 failed: Database service cannot validate database's certificate: failed to connect to `...`: failed to write startup message (x509: certificate signed by unknown authority). Please verify if the correct CA bundle is used in the database config.
```

Fixing the problem requires restarting the DB agent.  The agent was running as a stateless pod and once restarted it downloads the CA bundle from AWS and becomes operational.

## Teleport version

`v10.3.2`

## Recreation steps

1. Create an RDS DB
2. Deploy a db agent with a dynamic db watcher
3. Create a dynamic db resource
4. Connect to the db with tsh db connect - works
5. `tctl get db/<db_name> > db.yaml`
6. Edit the file and add an extra label
7. Update the db resource: `tctl create -f  db.yaml`
8. Wait for reconciliation
9. `tsh db connect ... ` fails with: `certificate signed by an unknown authority`

<details>
<summary>db.yaml</summary>
```
kind: db
metadata:
  description: 
  labels:
    engine: postgres
    environment: prod
    teleport.dev/origin: dynamic
  name: testdb
spec:
  aws:
    rds:
      iam_auth: false
      instance_id: <instance>
    redshift: {}
    region: <region>
    secret_store: {}
  protocol: postgres
  tls:
    mode: 0
  uri: <uri>
version: v3
```

</details>

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #19395 

Happens when proxy is newer, and db reconciler gets dynamic resource update, `database.GetAWS()` can give something like
```
{ { {} [] 0} {   false {} [] 0}  { [] false  {} [] 0} {  {} [] 0} {  false  {} [] 0} {} [66 0] 0}
```
Where status AWS returned with `XXX_unrecognized` field set to `[]byte{66,0}`. This tricks `database.GetAWS()` to use the "empty" status AWS and `GetType()` returns `self-hosted`

### CODE REVIEW

File: api/types/cmp.go [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+// equalProtoIngoreXXXFields returns true if provided proto-generated structs
+// are equal, ignoring XXX_* fields.
+func equalProtoIngoreXXXFields[T any, PT protoMessage[T]](a, b T) bool {
+	return cmp.Equal(a, b, cmp.FilterPath(isXXXField, cmp.Ignore()))
+}
+
+func isXXXField(path cmp.Path) bool {
+	return strings.HasPrefix(path.Last().String(), ".XXX_")
+}
```
Comment (greedy52) [inline api/types/cmp.go:47]: I believe [`proto.Equal`](https://github.com/gogo/protobuf/blob/f67b8970b736e53dbd7d0a27146c8f1ac52f74e5/proto/equal.go#L133-L140) does check for `XXX_ XXX_unrecognized `.

And `cmpopts.IgnoreFields` does not work for nested `XXX_`. 

So end up doing this way.

Comment (tigrato) [reply api/types/cmp.go:47]: I saw the first continue and assumed it skipped their validation but it validates the XXX fields as a special case.

**Review by tigrato — APPROVED** [review]
LGTM

**Review by strideynet — APPROVED** [review]

File: api/types/cmp.go (hunk 1 above)
Comment (smallinsky) [inline api/types/cmp.go:47]: Why not just: 
```suggestion
func protoEqual(lhs proto.Message, rhs proto.Message) bool {
	return cmp.Equal(lhs, rhs, cmp.FilterPath(func(path cmp.Path) bool {
		return strings.HasPrefix(path.Last().String(), ".XXX_")
	}, cmp.Ignore()))
}
```
and then it can be just like before ? 
```go
// IsEmpty returns true if AWS metadata is empty.
func (a AWS) IsEmpty() bool {
	return protoEqual(&a, &AWS{})
}
```

File: api/types/cmp_test.go [hunk 2]
```diff
@@ -0,0 +1,142 @@
...
+					XXX_unrecognized: []byte{99, 0},
+				},
+			},
+			assert: require.True,
+		},
+	}
+
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			test.assert(t, isProtoEmpty(test.input))
```
Comment (smallinsky) [inline api/types/cmp_test.go:65]:
```suggestion
			test.assert(t, test.Input.IsEmpty())
```

File: api/types/cmp_test.go [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+
+package types
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestIsProtoEmpty(t *testing.T) {
```
Comment (smallinsky) [inline api/types/cmp_test.go:25]:
```suggestion
func TestIsAWSProtoEmpty(t *testing.T) {
```

File: api/types/cmp.go (hunk 1 above)
Comment (greedy52) [reply api/types/cmp.go:47]: will do. I started with `cmpopt.IgnoreFields` which requires the struct. But now since no longer using that, I can go back without the generics. Thanks!

**Review by smallinsky — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Comment by greedy52** [comment]
Seems this PR makes the  `TestIntegrations/RotateXX` fails all the time in CI. Will investigate before able to merge this.

**Comment by greedy52** [comment]
Turned out that `CertAuthoritiesEquivalent` is called 200+ times and uses one-third of the CPU during `TestIntegrations/Rotate*` tests. 
Screenshot 2023-01-03 at 12 34 27 PM


On my mac, benchmark `CertAuthoritiesEquivalent` with two different CAs takes 10ms PER CALL! And the longer it takes, the more likely `TestIntegrations/Rotate*` will fail. Will do a separate change to optimize compare performance.

**Comment by tigrato** [comment]
@greedy52 please backport this PR
