### PR TITLE
Use dbcmd.WithPrintFormat only for preview of teleterm gateway command

### LINKED ISSUE #39836: Error reported attempting to connect to MongoDB resources via Teleport Connect
Expected behavior:
User should be able to seamlessly connect MongoDB resources in Teleport Connect. 

Current behavior:
Attempt to RUN the command via Teleport UI will produce error: _MongoshInvalidInputError: [COMMON-10001] Invalid URI: "mongodb://localhost:55138/?serverSelectionTimeoutMS=5000"_

Bug details:
- Teleport version

      Teleport Connect Version 15.1.9 (15.1.9.92) on macOS 14.4.1 and the mongosh version is 2.2.1.

- Recreation steps

      1. Login to Teleport Connect
      2. Select the Database Tab
      3. Connect to a MongoDB resource with an appropriate user
      4. This creates a new window with the command to RUN. See screenshot.  
      5. Attempt to RUN the command. This will produce error _MongoshInvalidInputError: [COMMON-10001] Invalid URI: "mongodb://localhost:55138/?serverSelectionTimeoutMS=5000"_
      6. If instead you select to open a new terminal in Teleport Connect and past the same command shown in step 4, it works. 
 
- [Proposed solution](https://github.com/gravitational/teleport/issues/39836#issuecomment-2022553281)

### PR DESCRIPTION
**Pull request by ravicious**
Fixes #39836.

Changelog: Fixed "Invalid URI" error when starting mongosh from database connection tab in Teleport Connect

Currently lib/teleterm uses `dbcmd.WithPrintFormat` when generating db commands. This option is meant to be used when the command is printed rather than executed, i.e. `tsh db config --format cmd`. It wraps connection strings in quotes. This way when the user copies a command and tries to execute it in a shell, the shell doesn't interpret certain characters in the connection string as special characters.

This worked in Connect because for a long time we did put those commands directly into a shell. However, in #26441 we switched to spawning CLI clients directly, which means that the quotes are at best unnecessary and at worst cause problems like the one described in #39836.

To fix this, `daemon.Service.GetGatewayCLICommand` returns two `exec.Cmd`s: one that doesn't use the print format and one that does. The one that does use the print format should be used for `api.GatewayCLICommand.Preview`, while other fields should come from the `exec.Cmd` that doesn't use the print format.

This way when the user clicks "Run", we execute the command without the quotes. But in the UI we display the version with the quotes, so that the user can simply copy and paste the command somewhere outside of Teleport Connect.

At the moment it mostly affects Mongodb. Looking at dbcmd, I don't think other protocols were affected.

mongo-gateway

### CODE REVIEW

File: lib/teleterm/cmd/db_test.go [hunk 1]
```diff
@@ -88,14 +103,34 @@ func TestNewDBCLICommand(t *testing.T) {
...
+			tc.checkCmds(t, mockGateway, cmds)
 		})
 	}
 }
+
+func checkMongoCmds(t *testing.T, gw fakeDatabaseGateway, cmds Cmds) {
+	execConnString := cmds.Exec.Args[1]
+	previewConnString := cmds.Preview.Args[1]
+	require.Len(t, cmds.Exec.Args, 2)
+	require.Len(t, cmds.Preview.Args, 2)
```
Comment (greedy52) [inline lib/teleterm/cmd/db_test.go:121]: nit:
```suggestion
func checkMongoCmds(t *testing.T, gw fakeDatabaseGateway, cmds Cmds) {
	t.Helper()
	require.Len(t, cmds.Exec.Args, 2)
	require.Len(t, cmds.Preview.Args, 2)
	execConnString := cmds.Exec.Args[1]
	previewConnString := cmds.Preview.Args[1]
```

**Review by greedy52 — APPROVED** [review]

**Comment by ravicious** [comment]
@probakowski Ping, we have a customer waiting for this fix.

**Review by probakowski — APPROVED** [review]
