### PR TITLE
Use 'path.Join' instead of 'filepath.Join' to build remote file paths

### LINKED ISSUE #18919: Regression: SCP Expands ~ to a Windows Path
## Expected behavior:
If I use scp over teleport to copy a file to/from a server I expect "~" to be the user's home directory _on the server in question_.  

This is how standard ssh/scp works.  It was also how earlier versions of tsh scp worked, so this is a regression in 11

## Current behavior:
The Windows teleport client seems to be expanding the ~ to a windows-style path with backslashes, so then the remote server then says it isn't found (as the remote is a Linux server).  I tried both from standard Windows command line (CMD) and from a Cygwin bash shell (which is where I actually work)

E.g. if I run (assuming I have a file called foo.txt in the Alice user's home folder on server1)
```
scp alice@server1:~/foo.txt .
```
then it copies the file from the server to the current directory on my local machine.

However, if I run
```
tsh scp --proxy teleport.example.com alice@server1:~/foo.txt .
```
then I get an error:
> ERROR: could not access remote path "\\home\\alice\\foo.txt": file does not exist

I can work around it by using
```
tsh scp --proxy teleport.example.com alice@server1:/home/alice/foo.txt .
```
but I expect the first version (with the "~" in the path) to work as it works for standard scp.

### Versions Tested
Teleport version is (as reported by "tsh version")
> Teleport v11.1.0 git:v11.1.0-0-g4ef520e81 go1.19.2
> Proxy version: 11.1.0

I had previously been using version 
> Teleport v9.3.18 git:v9.3.18-0-g386356255 go1.17.11

and I have re-tested that and with that it still works as expected (no problem with "~" in the path) even against the newer server version that we have updated to.

### To recreate:

- Create a file foo.txt in your home folder on a remote server
- Run the command (adjust proxy, user and server as needed)
```
tsh scp --proxy teleport.example.com alice@server1:~/foo.txt .
```

### Debug Output
If I run the same command with --debug added then the output (for the error part - I have skipped the certificate stuff which works fine) is
```
ERROR REPORT:
Original Error: *errors.errorString could not access remote path &#34;\\home\\alice\\foo.txt&#34;: file does not exist
Stack Trace:
        github.com/gravitational/teleport/lib/sshutils/sftp/sftp.go:305 github.com/gravitational/teleport/lib/sshutils/sftp.(*Config).transfer
        github.com/gravitational/teleport/lib/sshutils/sftp/sftp.go:166 github.com/gravitational/teleport/lib/sshutils/sftp.(*Config).TransferFiles
        github.com/gravitational/teleport/lib/client/client.go:1948 github.com/gravitational/teleport/lib/client.(*NodeClient).TransferFiles
        github.com/gravitational/teleport/lib/client/api.go:2555 github.com/gravitational/teleport/lib/client.(*TeleportClient).TransferFiles
        github.com/gravitational/teleport/lib/client/api.go:2457 github.com/gravitational/teleport/lib/client.(*TeleportClient).SFTP
        github.com/gravitational/teleport/tool/tsh/tsh.go:2867 main.onSCP.func1
        github.com/gravitational/teleport/lib/client/api.go:731 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        github.com/gravitational/teleport/tool/tsh/tsh.go:2866 main.onSCP
        github.com/gravitational/teleport/tool/tsh/tsh.go:995 main.Run
        github.com/gravitational/teleport/tool/tsh/tsh.go:448 main.main
        runtime/proc.go:250 runtime.main
        runtime/asm_amd64.s:1594 runtime.goexit
User Message: could not access remote path &#34;\\home\\alice\\foo.txt&#34;: file does not exist

ERROR REPORT:
Original Error: *errors.errorString could not access remote path &#34;\\home\\alice\\foo.txt&#34;: file does not exist
Stack Trace:
        github.com/gravitational/teleport/lib/sshutils/sftp/sftp.go:305 github.com/gravitational/teleport/lib/sshutils/sftp.(*Config).transfer
        github.com/gravitational/teleport/lib/sshutils/sftp/sftp.go:166 github.com/gravitational/teleport/lib/sshutils/sftp.(*Config).TransferFiles
        github.com/gravitational/teleport/lib/client/client.go:1948 github.com/gravitational/teleport/lib/client.(*NodeClient).TransferFiles
        github.com/gravitational/teleport/lib/client/api.go:2555 github.com/gravitational/teleport/lib/client.(*TeleportClient).TransferFiles
        github.com/gravitational/teleport/lib/client/api.go:2457 github.com/gravitational/teleport/lib/client.(*TeleportClient).SFTP
        github.com/gravitational/teleport/tool/tsh/tsh.go:2867 main.onSCP.func1
        github.com/gravitational/teleport/lib/client/api.go:731 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        github.com/gravitational/teleport/tool/tsh/tsh.go:2866 main.onSCP
        github.com/gravitational/teleport/tool/tsh/tsh.go:995 main.Run
        github.com/gravitational/teleport/tool/tsh/tsh.go:448 main.main
        runtime/proc.go:250 runtime.main
        runtime/asm_amd64.s:1594 runtime.goexit
User Message: could not access remote path &#34;\\home\\alice\\foo.txt&#34;: file does not exist
```

### PR DESCRIPTION
**Pull request by capnspacehook**
tsh on Windows when using 'filepath.Join' would create paths with forward slashes in them, which non-Windows Nodes couldn't handle. Consistently use 'path.Join' to avoid issues.

Fixes #18919

### CODE REVIEW

File: lib/sshutils/sftp/sftp.go [hunk 1]
```diff
@@ -233,7 +231,7 @@ func expandPath(path string, getHomeDir homeDirRetriever) (string, error) {
 
 	// this is safe because we verified that all paths are non-empty
 	// in CreateUploadConfig/CreateDownloadConfig
-	return filepath.Join(homeDir, path[1:]), nil
+	return path.Join(homeDir, pathStr[1:]), nil
```
Comment (zmb3) [inline lib/sshutils/sftp/sftp.go:234]: I'd add a comment here, because most people are used to using filepath for file paths.

```
// note: intentionally prefer path.Join over filepath.Join because 
// SCP requires Linux-style path separators
```

**Review by ravicious — APPROVED** [review]

File: lib/sshutils/sftp/sftp.go (hunk 1 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go:237]: Added a comment to the `path` import as `path.Join` is used 3 other places in the file and it wouldn't make sense to only add a comment here

**Review by gzdunek — APPROVED** [review]

File: lib/sshutils/sftp/sftp.go (hunk 1 above)
Comment (zmb3) [reply lib/sshutils/sftp/sftp.go:236]: The comments immediately above the package clause are the package level doc, which shows up for example when you run `go doc github.com/gravitational/teleport/lib/sshutils/sftp`.

I think this info is an internal detail and not relevant for the package level documentation.

Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go:236]: I tried to put the comment directly preceding the `path` import, but the `gci` linter didn't like that. Where do you think the next best place would be, directly under the `import` statement?

Comment (zmb3) [reply lib/sshutils/sftp/sftp.go:236]: Does `gci` mind if the comment is on the same line?

```
import (
  "path" // SCP requires Linux-style path separators
)
```

If not, that works. If that's still a problem, I don't think including the comment at all 3 call sites is a bad idea.

Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go:236]: Attempting the former here: https://github.com/gravitational/teleport/pull/21106
