### PR TITLE
Fix setting request reason for automatic ssh access requests.

### LINKED ISSUE #42634: "tsh ssh --request-reason" doesn't create access request with the provided reason.
Expected behavior:
`tsh ssh --request-reason=myreason foo@bar` to open access request with a reason "myreason" if user doesn't have access to bar

Current behavior:
Access request is opened, but the reason is not propagated.

Bug details:
When auth server gets request to create it, the reason field is empty.

### PR DESCRIPTION
**Pull request by AntonAM**
It seems that after adding automatic role access requests ( #39003 ) , request reason functionality got broken - in tsh codepath we never set reason for resource requests and only set reason for role requests if there's more than one role. This PR fixes that, so we again get request reason from the flag or prompt user for it. 
I also added tsh logout/login in the tests, I think second test case didn't actually work because we had approved access request from the first one.

Changelog: Fix setting request reason for automatic ssh access requests.

Fixes #42634

### CODE REVIEW

File: tool/tsh/common/tsh_test.go [hunk 1]
```diff
@@ -1994,6 +2009,18 @@ func TestSSHAccessRequest(t *testing.T) {
...
+
+			found := false
+			for _, r := range requests {
+				if r.GetRequestReason() == requestReason {
+					found = true
+					break
+				}
+			}
+			require.True(t, found, "access request with the specified reason was not found")
+
```
Comment (zmb3) [inline tool/tsh/common/tsh_test.go:2023]: How about a one-liner with `require.True(t, slices.ContainsFunc(requests, func(){...})`?

**Review by zmb3 — APPROVED** [review]

**Review by atburke — APPROVED** [review]

**Review by nklaassen — APPROVED** [review]

**Comment by AntonAM** [comment]
@zmb3 can I get excludeflake for this? `TestSSHAccessRequest` is pretty slow and I didn't find a simple way to make it faster without removing stuff (previous PR also required excludeflake).
