### PR TITLE
fix: Fix panic on `tsh device enroll --current-device`

### LINKED ISSUE #31816: "tsh device enroll --current-device" panics when limit exceeds in Team plan
### Expected behavior:
When 5 device limit is reached in Team plan, it is expected to register device but return error during enrollment `ERROR: cluster has reached its enrolled trusted device limit, please contact the cluster administrator`. 

### Current behavior:
running `tsh device enroll --current-device` when 5 devices limit is reached, the command registers the device but panics:

```
% tsh device enroll --current-device
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x10294f188]

goroutine 1 [running]:
github.com/gravitational/teleport/tool/tsh/common.printEnrollOutcome(0xc001d9e548?, 0x103fdd8a8?)
	github.com/gravitational/teleport/tool/tsh/common/device.go:146 +0x68
github.com/gravitational/teleport/tool/tsh/common.(*deviceEnrollCommand).run.func1()
	github.com/gravitational/teleport/tool/tsh/common/device.go:118 +0x28e
github.com/gravitational/teleport/lib/client.RetryWithRelogin({0x103fdd8a8, 0xc000f72780}, 0xc001247000, 0xc001d9e870, {0x0, 0x0, 0x1?})
	github.com/gravitational/teleport/lib/client/api.go:570 +0x6e
github.com/gravitational/teleport/tool/tsh/common.(*deviceEnrollCommand).run(0xc001219dc0, 0xc001642000)
	github.com/gravitational/teleport/tool/tsh/common/device.go:100 +0x11d
github.com/gravitational/teleport/tool/tsh/common.Run({0x103fddff8, 0xc001cc8140}, {0xc000074190?, 0x3, 0x3}, {0x0, 0x0, 0xc0000b66d8?})
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1431 +0xda85
github.com/gravitational/teleport/tool/tsh/common.Main()
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:540 +0x2e5
main.main()
	github.com/gravitational/teleport/tool/tsh/main.go:24 +0xf
```

`tsh device enroll --token=<token>` command works perfectly but
`tsh device enroll --current-device` panics.

### PR DESCRIPTION
**Pull request by codingllama**
Fix a panic that happens on `tsh device enroll --current-device` when the device wasn't previously registered and the subsequent enrollment fails (for example, because the cluster devices limit was reached).

Fixes #31816.

Changelog: Fix panic on `tsh device enroll --current-device` when the cluster has reached its devices limit.

### CODE REVIEW

File: lib/devicetrust/enroll/enroll.go [hunk 1]
```diff
@@ -154,7 +154,7 @@ func (c *Ceremony) RunAdmin(
 	// Then proceed onto enrollment.
 	enrolled, err := c.Run(ctx, devicesClient, debug, token)
 	if err != nil {
-		return enrolled, outcome, trace.Wrap(err)
+		return currentDev, outcome, trace.Wrap(err)
```
Comment (codingllama) [inline lib/devicetrust/enroll/enroll.go:157]: This line is the bugfix proper, everything else is the cherry on top.

**Comment by codingllama** [comment]
Unit tested and manually confirmed as well.

**Review by zmb3 — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
