### PR TITLE
Change the application access authentication flow

### LINKED ISSUE #15935: State cookie race condition when opening multiple app sessions simultaneously
### Current behavior

When opening multiple sessions of the same application in a quick succession via application access launcher in web UI e.g. in multiple tabs, only one of them (usually, the last tab) will actually load the target application.

Others will be stuck at the following endpoint getting 403 response:

```
https://app.example.com:3080/x-teleport-auth?state=726b4be6c287a5dc5f637c1b48975d20#value=61d2dc0884318ccb07240bb6493bbdf15650866d87c1fe2834c1d692a200dc97
```

### Expected behavior

Application should load in all tabs.

### Repro steps

1. Have a Teleport cluster with a registered application. Default dumper app will do.
2. Go to the Applications tab and quickly open multiple instances of the dumper app e.g. by holding Ctrl (or Cmd on Mac) and clicking "Launch" button multiple times.
3. Observe that only the last tab (most likely) will load the apps, other tabs will be stuck on the x-teleport-auth URL.

### Analysis

x-teleport-auth handler sets [state token](https://github.com/gravitational/teleport/blob/v10.1.7/lib/web/app/fragment.go#L55) in a cookie to protect against CSRF attacks, which then gets [validated and reset](https://github.com/gravitational/teleport/blob/v10.1.7/lib/web/app/fragment.go#L83-L94) before setting a cookie with the session ID.

The problem is that cookies are per-browser, not per-tab, so when opening the same application in multiple tabs, the last tab's state cookie "wins" and thus application in other tabs that have different state cookies get "state token does not match" error:

```
2022-08-29T17:12:20-07:00 INFO [AUDIT]     app.session.start addr.remote:127.0.0.1:64213 app_name:dumper app_public_addr:dumper.root.gravitational.io app_uri:http://localhost:4321 cluster_name:root code:T2007I ei:0 event:app.session.start namespace:default public_addr:dumper.root.gravitational.io server_id:8e70002c-7a07-4513-a3fa-ac556a1d7534 sid:f12e429e-5f6c-44c3-83b7-c90030ecfe9a time:2022-08-30T00:12:20.017Z uid:3aeb2b97-129b-4649-83ef-206dba26d2e8 user:alice events/emitter.go:263
2022-08-29T17:12:20-07:00 WARN [APP:WEB]   Request failed: state token does not match. app/fragment.go:89
2022-08-29T17:12:20-07:00 WARN [APP:WEB]   Request failed: state token does not match. app/fragment.go:89
```

This is the original commit where state token was introduced: https://github.com/gravitational/teleport/commit/ee7693f41dc87195f17d82f0244b1e0c6b140bb2.

### Possible solutions

Needs some investigation but a couple of ideas that come to mind are:

* Store state cookie in the backend instead of a cookie and then validate by fetching from backend instead of a cookie [here](https://github.com/gravitational/teleport/blob/v10.1.7/lib/web/app/fragment.go#L83)?
  * Similar to how we store state for [auth connectors](https://github.com/gravitational/teleport/blob/v10.1.7/lib/auth/oidc.go#L275-L283) and then [validate it in the callback](https://github.com/gravitational/teleport/blob/v10.1.7/lib/web/apiserver.go#L1355-L1361).
* Is there per-tab storage we can use for state token instead of cookies?

### Teleport version

This issue affects all supported Teleport versions (master, v10, v9, v8).

### PR DESCRIPTION
**Pull request by ryanclark**
Previously, we'd pass the value of the cookie that needed to be set to `/x-teleport-auth` via the `POST` body. This opened it up to CSRF attacks, which was mediated by implementing a `?state=` query param and a cookie.

This added quite a few different redirects, which can be simplified by allowing cross origin requests from the proxy address to the application's `/x-teleport-auth` endpoint, and sending the cookie value via a custom `X-Cookie-Value` header instead.

Custom headers cannot be added to `<form>` elements, nor included in a `no-cors` `fetch()` request. This means a user cannot be tricked into launching an application by a third party malicious actor.

This would fix https://github.com/gravitational/teleport/issues/15935, as we're no longer relying on the cookie that gets unset by the `x-teleport-auth` dance.

### CODE REVIEW

File: lib/web/apiserver.go [hunk 1]
```diff
@@ -232,6 +232,21 @@ func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 	// request is already authenticated (has a session cookie), forward to
 	// application handlers. If the request is unauthenticated and requesting a
 	// FQDN that is not of the proxy, redirect to application launcher.
+
+	// Allow minimal CORS from only the proxy origin
+	// This allows for requests from the proxy to `POST` to `/x-teleport-auth` and only
+	// permits the header `X-Cookie-Value`.
+	// This is for the web UI to post a request to the application to get the proper app session
+	// cookie set on the right application subdomain.
+	w.Header().Set("Access-Control-Allow-Origin", "https://"+h.handler.cfg.ProxyPublicAddrs[0].Host())
```
Comment (ikkisoft) [inline lib/web/apiserver.go:241]: Isn't this going to break when the Teleport installation has multiple web proxy public addresses? The user might access the proxy from IP `ProxyPublicAddrs[1]` but the CORS header will always return `ProxyPublicAddrs[0]` hence failing after the preflight request.

**Review by ikkisoft — COMMENTED** [review]
In term of security and protection against Login CSRF, the current implementation is comparable to the previous one. I did leave one comment, since I believe this mechanism will break for teleport installations that are configured with multiple public IPs/Domain names.

However, it's important to note that this security mechanism fully relies on a properly configured CORS policy.  Given that the `Access-Control-Allow-Origin` uses the teleport's configuration (`public_addr` field), it is particularly important to ensure that all hostnames listed in this setting are trusted. Arbitrary HTML/Javascript hosted under such domains will have full access to cross-origin requests hence bypassing this protection.

File: lib/web/app/auth.go [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+
+	"github.com/gravitational/teleport/api/types"
+	"github.com/gravitational/teleport/lib/httplib"
+	"github.com/gravitational/trace"
+
+	"github.com/julienschmidt/httprouter"
+)
+
+// handleAuth handles authentication for an app
+// When a `POST` request comes in, it'll check the request's cookies for one matching the name of the value of
```
[the remark this answers is not in the document]
Comment (ryanclark) [reply lib/web/app/auth.go:31]: My bad, it's a comment left in from when I was trying a different approach

File: lib/web/apiserver.go (hunk 1 above)
Comment (ryanclark) [reply lib/web/apiserver.go:241]: Proxies only have one public address AFAIK, I will double check on this

**Comment by ryanclark** [comment]
> In term of security and protection against Login CSRF, the current implementation is comparable to the previous one. I did leave one comment, since I believe this mechanism will break for teleport installations that are configured with multiple public IPs/Domain names.
> 
> However, it's important to note that this security mechanism fully relies on a properly configured CORS policy. Given that the `Access-Control-Allow-Origin` uses the teleport's configuration (`public_addr` field), it is particularly important to ensure that all hostnames listed in this setting are trusted. Arbitrary HTML/Javascript hosted under such domains will have full access to cross-origin requests hence bypassing this protection.

Arbitrary HTML/JS on any proxy address is an issue in general, as it'll give access to the proxy API without CORS being needed. 

I don't see this being an issue, there would be more attack vectors if there was arbitrary HTML/JS on a proxy endpoint than a `POST /x-teleport-auth` setting a cookie value (that doesn't guarantee app access, as the cookie value needs to be known).

That being said, I wouldn't be against a HMAC signature for the cookie that's also passed along, so brute force attempts to guess a cookie value couldn't be achieved.

Thanks for taking the time to review this.

**Comment by ikkisoft** [comment]
Agree. I was mostly concerned about a user's misconfiguration in which the CORS Access-Control-Allow-Origin returns an host that is not owned by the admin. E.g. dangling DNS records

File: lib/web/app/handler.go [hunk 3]
```diff
@@ -133,6 +135,58 @@ func NewHandler(ctx context.Context, c *HandlerConfig) (*Handler, error) {
...
+
+			return
+		}
+
+		isMatch := false
+		originPort := origin.Port()
+		for _, addr := range h.c.ProxyPublicAddrs {
+			addrPort := addr.Port(0)
+
+			if addrPort != 443 { // the port should be present in the origin header
```
[the remark this answers is not in the document]
Comment (ryanclark) [reply lib/web/app/handler.go:170]: When you're not using a port in the URL (as is the case for 443), the origin isn't populated with the port

File: lib/web/app/handler_test.go [hunk 4]
```diff
@@ -48,60 +46,6 @@ import (
 	"github.com/gravitational/teleport/lib/utils"
 )
 
-// TestAuthPOST tests the handler of POST /x-teleport-auth.
-func TestAuthPOST(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (ryanclark) [reply lib/web/app/handler_test.go:52]: Updated to add a test for setting the correct cookie value with a correct origin, and getting a 403 forbidden when attempting the same from an incorrect origin

File: lib/web/app/handler_test.go [hunk 5]
```diff
@@ -48,56 +46,50 @@ import (
...
 
-// TestAuthPOST tests the handler of POST /x-teleport-auth.
 func TestAuthPOST(t *testing.T) {
 	const (
-		stateValue  = "012ac605867e5a7d693cd6f49c7ff0fb"
 		cookieValue = "5588e2be54a2834b4f152c56bafcd789f53b15477129d2ab4044e9a3c1bf0f3b"
 	)
 
 	fakeClock := clockwork.NewFakeClockAt(time.Date(2017, 05, 10, 18, 53, 0, 0, time.UTC))
 	tests := []struct {
```
[the remark this answers is not in the document]
Comment (ryanclark) [reply lib/web/app/handler_test.go:55]: Done!

File: lib/web/app/auth.go [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+
+// handleAuth handles authentication for an app
+// When a `POST` request comes in from a trusted proxy address, it'll set the value from the
+// `X-Cookie-Value` header to the `__Host-grv_app_session` cookie.
+func (h *Handler) handleAuth(w http.ResponseWriter, r *http.Request, p httprouter.Params) error {
+	httplib.SetNoCacheHeaders(w.Header())
+
+	cookieValue := r.Header.Get("X-Cookie-Value")
+	if cookieValue == "" {
+		return trace.BadParameter("X-Cookie-Value header missing")
```
Comment (r0mant) [inline lib/web/app/auth.go:37]: Should we log that X-Cookie-Value header is missing and return generic "access denied" error here instead, like we do below?

File: lib/web/apiserver.go [hunk 7]
```diff
@@ -245,14 +245,12 @@ func (h *APIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 	// request is already authenticated (has a session cookie), forward to
 	// application handlers. If the request is unauthenticated and requesting a
 	// FQDN that is not of the proxy, redirect to application launcher.
+
 	if h.appHandler != nil && (app.HasFragment(r) || app.HasSession(r) || app.HasClientCert(r)) {
 		h.appHandler.ServeHTTP(w, r)
 		return
 	}
-	if redir, ok := app.HasName(r, h.handler.cfg.ProxyPublicAddrs); ok {
```
Comment (r0mant) [inline lib/web/apiserver.go:252]: Why is this redirect no longer needed? Does it still work if you try to access an application over its "custom" public address that doesn't match the proxy public addr?

File: lib/web/app/handler.go [hunk 8]
```diff
@@ -133,6 +135,53 @@ func NewHandler(ctx context.Context, c *HandlerConfig) (*Handler, error) {
...
+
+		if r.Method == http.MethodOptions {
+			return
+		}
+
+		// Validate that the origin for the request matches any of the public proxy addresses.
+		// This is instead of protecting via CORS headers, as that only supports a single domain.
+		originValue := r.Header.Get("Origin")
+		origin, err := url.Parse(originValue)
+		if err != nil {
```
Comment (r0mant) [inline lib/web/app/handler.go:159]: Let's log this error at least so it's not lost.

File: lib/web/app/handler.go [hunk 9]
```diff
@@ -133,6 +135,53 @@ func NewHandler(ctx context.Context, c *HandlerConfig) (*Handler, error) {
...
+		}
+
+		var match bool
+		originPort := origin.Port()
+		if originPort == "" {
+			originPort = "443"
+		}
+
+		for _, addr := range h.c.ProxyPublicAddrs {
+			if strconv.Itoa(addr.Port(0)) == originPort && addr.Host() == origin.Hostname() {
```
Comment (r0mant) [inline lib/web/app/handler.go:172]: Doesn't this break the scenario when you're connecting to application over its public_addr?

Comment (ryanclark) [reply lib/web/app/handler.go:172]: This code is only ran for the `POST /x-teleport-auth` request from the proxy webpage to the application FQDN + `/x-teleport-auth`, so it doesn't break

File: lib/web/apiserver.go (hunk 7 above)
Comment (ryanclark) [reply lib/web/apiserver.go:252]: My bad, I think I had removed this originally when trying something else out and forgot to add it back in. Added.

**Review by r0mant — DISMISSED** [review]
@ryanclark I tried this branch in my local cluster and I can't connect to any applications. I get "Access to XXX was denied" from the browser.
Screenshot 2022-12-21 at 7 35 00 PM

**Comment by r0mant** [comment]
@ryanclark I've now tried with webassets from branch `ryan/change-app-access-login-flow` and I still can't connect albeit the error is different now:

Screenshot 2022-12-22 at 8 22 52 PM

And I see the following warnings in Chrome inspector:

Screenshot 2022-12-22 at 8 25 02 PM

File: lib/web/app/auth.go [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+	//
+	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
+
+	http.SetCookie(w, &http.Cookie{
+		Name:     CookieName,
+		Value:    cookieValue,
+		Path:     "/",
+		HttpOnly: true,
+		Secure:   true,
+		SameSite: http.SameSiteNoneMode,
```
Comment (ikkisoft) [inline lib/web/app/auth.go:96]: This can be made "Lax" to harden a bit the application. Just verified dynamically that works.

File: lib/web/app/auth.go [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+	})
+
+	http.SetCookie(w, &http.Cookie{
+		Name:     SubjectCookieName,
+		Value:    subjectCookieValue,
+		Path:     "/",
+		HttpOnly: true,
+		Secure:   true,
+		SameSite: http.SameSiteNoneMode,
```
Comment (ikkisoft) [inline lib/web/app/auth.go:105]: Same here. This can be made "Lax" to harden a bit the application.

File: lib/web/app/auth.go (hunk 10 above)
Comment (ikkisoft) [reply lib/web/app/auth.go:96]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#lax
> Cookies are not sent on normal cross-site subrequests (for example to load images or frames into a third party site), but are sent when a user is navigating to the origin site (i.e., when following a link).

File: lib/web/apiserver.go [hunk 12]
```diff
@@ -396,7 +399,13 @@ func NewHandler(cfg Config, opts ...HandlerOption) (*APIHandler, error) {
 			session.XCSRF = csrfToken
 
 			httplib.SetNoCacheHeaders(w.Header())
-			httplib.SetIndexContentSecurityPolicy(w.Header())
+
+			// app access needs to make a CORS fetch request, so we only set the default CSP on that page
+			if strings.HasPrefix(r.URL.Path, "/web/launch") {
+				httplib.SetDefaultContentSecurityPolicy(w.Header())
```
Comment (ikkisoft) [inline lib/web/apiserver.go:405]: While retesting on https://doyensec2.teleport.sh/, I encountered this error
Screen Shot 2023-01-11 at 15 36 19

I believe this was fixed by this code, and my cluster is just old.

File: lib/web/app/handler_test.go [hunk 13]
```diff
@@ -74,53 +73,70 @@ func hasAuditEventCount(want int) eventCheckFn {
...
 	const (
-		stateValue  = "012ac605867e5a7d693cd6f49c7ff0fb"
-		cookieValue = "5588e2be54a2834b4f152c56bafcd789f53b15477129d2ab4044e9a3c1bf0f3b"
+		cookieValue = "5588e2be54a2834b4f152c56bafcd789f53b15477129d2ab4044e9a3c1bf0f3b" // random value we set in the header and expect to get back as a cookie
 	)
 
 	fakeClock := clockwork.NewFakeClockAt(time.Date(2017, 05, 10, 18, 53, 0, 0, time.UTC))
 	clusterName := "test-cluster"
-	publicAddr := "app.example.com"
+	publicAddr := "proxy.teleport.com:443"
```
Comment (zmb3) [inline lib/web/app/handler_test.go:81]:
```suggestion
	publicAddr := "proxy.goteleport.com:443"
```

Might as well use a domain we actually own

**Review by zmb3 — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

**Review by hatched — APPROVED** [review]
