### PR TITLE
Connect: create Unix sockets in temp directory

### LINKED ISSUE #60039: Connect: Create sockets under a path guaranteed not to exceed the character limit
If you create a user on macOS with a long username, say foobarbazfoobarbazfoobarbazfoobarbaz which is 36 characters, the destination for the socket with the longest name will be `/Users/foobarbazfoobarbazfoobarbazfoobarbaz/Library/Application Support/Teleport Connect/tshd_events.socket` which is 107 characters, [exceeding the limit](https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars) by 3 characters.

This is similar to #43250, but here it's Node.js which creates the socket. Instead of giving a hard error, it truncates the name of the socket so that it fits the limit (`tshd_events.soc`) and just continues, but the rest of the app doesn't know about it and attempts to use the original address. The tshd events service essentially doesn't work which impairs every feature which depends on it.

Instead of creating the sockets in the user's home dir which can result in exceeding the limit, we should create it under a path that guarantees that the limit won't be exceeded.

A good candidate is user's tmp dir (`$TMPDIR` on macOS). I don't know if its path is guaranteed to have a constant length, but on my device it's 49 characters at the moment. As long as the socket file has the same permissions as it currently has we should be good. We also need to check if Linux has a similar implementation of user's tmp dir. Then we just create a dir in there with the app's name and can be more confident that we don't exceed the limit.

I also discovered that we never remove `tshd_events.socket` because we never properly shut down the tshd events service. Unlike PTY host service in the shared process, we never call `server.forceShutdown`. This is not terribly important though because as shown by the current behavior, the gRPC library is able to handle that.

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/60039

Tested on macOS, Ubuntu, and Fedora.

changelog: Fixed a startup error `EADDRINUSE: address already in use` in Teleport Connect on macOS and Linux that could occur with long system usernames

### CODE REVIEW

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts [hunk 1]
```diff
@@ -218,21 +218,67 @@ function requestGrpcServerAddresses(): GrpcServerAddresses {
...
-function getUnixSocketNetworkAddress(socketName: string) {
-  const unixSocketPath = path.resolve(app.getPath('userData'), socketName);
+async function getUnixSocketNetworkAddress(
+  tempDir: string,
+  socketName: string
+) {
+  const socketPath = path.join(tempDir, socketName);
+  try {
+    // Try to clean up after a previous process that unexpectedly crashed.
+    await fs.promises.unlink(socketPath);
```
Comment (avatus) [inline web/packages/teleterm/src/mainProcess/runtimeSettings.ts]: Did the last version throw when we tried to clean up? should it be "best effort" or fail here, im unsure the consequences either way

**Review by avatus — APPROVED** [review]

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts (hunk 1 above)
Comment (gzdunek) [reply web/packages/teleterm/src/mainProcess/runtimeSettings.ts]: >Did the last version throw when we tried to clean up? 

Yes, but it checked first if the file exists with `existSync`.
However, such checks are prone to race conditions. Instead, we can just perform the action and catch `ENOENT`.

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts [hunk 2]
```diff
@@ -218,21 +218,67 @@ function requestGrpcServerAddresses(): GrpcServerAddresses {
...
+  // On Linux the temp dir is like /tmp, and it's accessible by anyone,
+  // so create a user-specific subdirectory, e.g. "Teleport Connect-1000".
+  const dirPath = path.join(
+    appTempDir,
+    // UID can have at most 10 chars.
+    `${appName}-${process.getuid().toString()}`
+  );
+  await fs.promises.mkdir(dirPath, { mode: 0o700, recursive: true });
+  // The directory may already exist, validate it.
+  const stat = await fs.promises.lstat(dirPath);
```
Comment (ravicious) [inline web/packages/teleterm/src/mainProcess/runtimeSettings.ts]: Instead of performing those checks below (which are hard errors if something is wrong) and caring about uid, what if we used `fs.mkdtemp` with an app name prefix and created a new directory each time?

`fs.mkdtemp` doesn't let you specify the mode, but it's a thin wrapper on top of `mkdtemp`, which itself creates directories with mode 0700, according to `man mkdtemp`.

FWIW, we could have the same code for macOS and Linux then. We also wouldn't need to have the code which cleans up the old sockets.

Based on https://www.netmeister.org/blog/mktemp.html, the only thing we'd miss is the cleanup of the tmp dir itself, but it's not super important and I don't want to ask you to go out of your way under a PR that was made during a support shift.

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts [hunk 3]
```diff
@@ -218,21 +218,67 @@ function requestGrpcServerAddresses(): GrpcServerAddresses {
...
+  return `unix://${socketPath}`;
+}
 
-  // try to cleanup after previous process that unexpectedly crashed
-  if (fs.existsSync(unixSocketPath)) {
-    fs.unlinkSync(unixSocketPath);
+async function getUnixUserTempDir(): Promise<string> {
+  const appTempDir = app.getPath('temp');
+  const appName = app.getName();
+  // On macOS, 'temp' dir is like //var/folders/y5/yqg8xz555_v7xfsr0wn6b4q80000gn/T/.
```
Comment (ravicious) [inline web/packages/teleterm/src/mainProcess/runtimeSettings.ts]:
```suggestion
  // On macOS, 'temp' dir is like /var/folders/y5/yqg8xz555_v7xfsr0wn6b4q80000gn/T/.
```

**Review by ravicious — APPROVED** [review]
It seems to work just fine and I'm glad you thought of Linux. But I think we could avoid a bunch of fs operations if we used `fs.mkdtemp`.

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts (hunk 2 above)
Comment (gzdunek) [reply web/packages/teleterm/src/mainProcess/runtimeSettings.ts]: Oh, I was thinking that directories created with `fs.mkdtemp` inherit parent directory permissions, but you are right, they are created with 0700 mode.
I agree that it's much cleaner to use that API than to do all these checks by hand.

When it comes to cleaning up, I think we can skip it for now. I've left a TODO for myself :)

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts [hunk 4]
```diff
@@ -218,21 +218,33 @@ function requestGrpcServerAddresses(): GrpcServerAddresses {
...
+      // maximum allowed path length for Unix domain sockets.
+      // Limits: macOS - 104 characters, Linux - 108 characters.
+      const tempDir = await getUnixUserTempDir();
       return {
-        tsh: getUnixSocketNetworkAddress('tsh.socket'),
-        shared: getUnixSocketNetworkAddress('shared.socket'),
-        tshdEvents: getUnixSocketNetworkAddress('tshd_events.socket'),
+        tsh: getUnixSocketPath(tempDir, 'tsh.sock'),
+        shared: getUnixSocketPath(tempDir, 'shared.sock'),
+        tshdEvents: getUnixSocketPath(tempDir, 'tshde.sock'),
```
Comment (ravicious) [inline web/packages/teleterm/src/mainProcess/runtimeSettings.ts:228]: I shortened the filenames slightly because I was still a bit uncomfortable with how close to the limit we were in the packaged version.

$TMPDIR points to `/var/folders/…`, but `/var` is actually a symlink to `/private/var`. It's a stretch but say one day $TMPDIR starts pointing to the full path instead. In that case, we'd end up with something like this:

```
/private/var/folders/kz/2d_vhlks21l3g1s4g5yytzwr0000gn/T/Teleport Connect-MI5YfN/tshd_events.socket
```

which is 99 characters. After shortening the file names a little bit, the longest one is 92 characters:

```
/private/var/folders/kz/2d_vhlks21l3g1s4g5yytzwr0000gn/T/Teleport Connect-MI5YfN/shared.sock
```

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts [hunk 5]
```diff
@@ -218,21 +218,33 @@ function requestGrpcServerAddresses(): GrpcServerAddresses {
...
+  const socketPath = path.join(tempDir, socketName);
+  return `unix://${socketPath}`;
+}
 
-  return `unix://${path.resolve(app.getPath('userData'), socketName)}`;
+async function getUnixUserTempDir(): Promise<string> {
+  // On macOS, the 'temp' dir is like /var/folders/y5/yqg8xz555_v7xfsr0wn6b4q80000gn/T/.
+  // That dir is per-user and secure by default.
+  // On Linux the temp dir is like /tmp, and it's accessible by anyone.
+  const tempDir = app.getPath('temp');
```
Comment (ravicious) [inline web/packages/teleterm/src/mainProcess/runtimeSettings.ts:242]: I read that on some Linux distros, /tmp is cleaned periodically by looking at access time of files and removing ones that are older than x amount of time. https://serverfault.com/questions/377348/when-does-tmp-get-cleared

Hopefully this doesn't bite us. But I don't think there's a better directory for this, `$XDG_RUNTIME_DIR` isn't guaranteed to exist, I also don't think it's guaranteed to be cleaned up (so we'd need to do that ourselves). We can't write to `/run` because we're a user process.

Also, I don't fully understand how sockets work, since the gRPC client continues to work even if I remove the socket file, as long as the connection has been established before I removed the file. The communication with the shared process doesn't start until the PTY is created though, I think. And I'm not sure how this work when gRPC reconnects the client or something.

**Review by ravicious — APPROVED** [review]

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts (hunk 4 above)
Comment (gzdunek) [reply web/packages/teleterm/src/mainProcess/runtimeSettings.ts:228]: Nice, thanks!

File: web/packages/teleterm/src/mainProcess/runtimeSettings.ts (hunk 5 above)
Comment (gzdunek) [reply web/packages/teleterm/src/mainProcess/runtimeSettings.ts:242]: AFAIK once the server has bound to the socket and the client has connected to it, it's safe to remove the socket file.

https://unix.stackexchange.com/questions/498395/detect-unix-domain-socket-deletion/498405#498405

File: web/packages/teleterm/src/services/tshdEvents/index.ts [hunk 6]
```diff
@@ -64,7 +64,9 @@ export async function createTshdEventsServer(
   const { service, setupTshdEventContextBridgeService } = createService(logger);
 
   server.addService(apiService.tshdEventsServiceDefinition, service);
-
+  window.addEventListener('unload', () => {
```
Comment (ravicious) [inline web/packages/teleterm/src/services/tshdEvents/index.ts:67]: This creates a warning in the console about the use of a deprecated feature.

* https://chromestatus.com/feature/5579556305502208
* https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes
* https://developer.chrome.com/docs/web-platform/page-lifecycle-api#the_unload_event

Comment (gzdunek) [reply web/packages/teleterm/src/services/tshdEvents/index.ts:67]: From what I see, we could replace it with `pagehide`:
>In all modern browsers, it's recommended to always use the [pagehide](https://developer.chrome.com/docs/web-platform/page-lifecycle-api#event-pagehide) event to detect possible page unloads (a.k.a the [terminated](https://developer.chrome.com/docs/web-platform/page-lifecycle-api#state-terminated) state) rather than the unload event. If you need to support Internet Explorer versions 10 and lower, you should feature detect the pagehide event and only use unload if the browser doesn't support pagehide:

I tested it and it seems to work fine.

The docs says that [visibilitychange](https://developer.chrome.com/docs/web-platform/page-lifecycle-api#event-visibilitychange) is more reliable, but it our case it would fire when we the app enters the background mode.
