### PR TITLE
lazy init of prometheus collectors

### LINKED ISSUE #6271: Reduce high cardinality in metrics endpoint
### Description

**What happened**:
Using prometheus to scrape a large number of clusters for monitoring data, the metrics endpoint currently produces what appears to be a lot of high cardinality but low value data. Stuff like backends that are not in use are still initialized and present empty metrics, which takes up storage in the metrics system.

**What you expected to happen**:
Basically to do a pass at lazy initializing only metrics that are required.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. `curl http://127.0.0.1:3000/metric` and inspect the metrics

### Server Details
- Teleport version (run `teleport version`): 6

### Sample metrics output

For example, this node isn't using etcd, but produces 80 etcd vectors per instance... same for toher backends.

```
# HELP audit_failed_disk_monitoring Number of times disk monitoring failed.
# TYPE audit_failed_disk_monitoring counter
audit_failed_disk_monitoring 0
# HELP audit_failed_emit_events Number of times emitting audit event failed.
# TYPE audit_failed_emit_events counter
audit_failed_emit_events 0
# HELP audit_percentage_disk_space_used Percentage disk space used.
# TYPE audit_percentage_disk_space_used gauge
audit_percentage_disk_space_used 6
# HELP audit_server_open_files Number of open audit files
# TYPE audit_server_open_files gauge
audit_server_open_files 0
# HELP auth_generate_requests Number of current generate requests for server keys
# TYPE auth_generate_requests gauge
auth_generate_requests 0
# HELP auth_generate_requests_throttled_total Number of throttled requests to generate new server keys
# TYPE auth_generate_requests_throttled_total counter
auth_generate_requests_throttled_total 0
# HELP auth_generate_requests_total Number of requests to generate new server keys
# TYPE auth_generate_requests_total counter
auth_generate_requests_total 1
# HELP auth_generate_seconds Latency for generate requests for server keys
# TYPE auth_generate_seconds histogram
auth_generate_seconds_bucket{le="0.001"} 1
auth_generate_seconds_bucket{le="0.002"} 1
auth_generate_seconds_bucket{le="0.004"} 1
auth_generate_seconds_bucket{le="0.008"} 1
auth_generate_seconds_bucket{le="0.016"} 1
auth_generate_seconds_bucket{le="0.032"} 1
auth_generate_seconds_bucket{le="0.064"} 1
auth_generate_seconds_bucket{le="0.128"} 1
auth_generate_seconds_bucket{le="0.256"} 1
auth_generate_seconds_bucket{le="0.512"} 1
auth_generate_seconds_bucket{le="1.024"} 1
auth_generate_seconds_bucket{le="2.048"} 1
auth_generate_seconds_bucket{le="4.096"} 1
auth_generate_seconds_bucket{le="8.192"} 1
auth_generate_seconds_bucket{le="16.384"} 1
auth_generate_seconds_bucket{le="32.768"} 1
auth_generate_seconds_bucket{le="+Inf"} 1
auth_generate_seconds_sum 7e-08
auth_generate_seconds_count 1
# HELP backend_batch_read_requests_total Number of read requests to the backend
# TYPE backend_batch_read_requests_total counter
backend_batch_read_requests_total{component="backend"} 278
backend_batch_read_requests_total{component="cache"} 222038
# HELP backend_batch_read_seconds Latency for batch read operations
# TYPE backend_batch_read_seconds histogram
backend_batch_read_seconds_bucket{component="backend",le="0.001"} 0
backend_batch_read_seconds_bucket{component="backend",le="0.002"} 0
backend_batch_read_seconds_bucket{component="backend",le="0.004"} 242
backend_batch_read_seconds_bucket{component="backend",le="0.008"} 273
backend_batch_read_seconds_bucket{component="backend",le="0.016"} 277
backend_batch_read_seconds_bucket{component="backend",le="0.032"} 278
backend_batch_read_seconds_bucket{component="backend",le="0.064"} 278
backend_batch_read_seconds_bucket{component="backend",le="0.128"} 278
backend_batch_read_seconds_bucket{component="backend",le="0.256"} 278
backend_batch_read_seconds_bucket{component="backend",le="0.512"} 278
backend_batch_read_seconds_bucket{component="backend",le="1.024"} 278
backend_batch_read_seconds_bucket{component="backend",le="2.048"} 278
backend_batch_read_seconds_bucket{component="backend",le="4.096"} 278
backend_batch_read_seconds_bucket{component="backend",le="8.192"} 278
backend_batch_read_seconds_bucket{component="backend",le="16.384"} 278
backend_batch_read_seconds_bucket{component="backend",le="32.768"} 278
backend_batch_read_seconds_bucket{component="backend",le="+Inf"} 278
backend_batch_read_seconds_sum{component="backend"} 0.9828407739999996
backend_batch_read_seconds_count{component="backend"} 278
backend_batch_read_seconds_bucket{component="cache",le="0.001"} 222037
backend_batch_read_seconds_bucket{component="cache",le="0.002"} 222038
backend_batch_read_seconds_bucket{component="cache",le="0.004"} 222038
backend_batch_read_seconds_bucket{component="cache",le="0.008"} 222038
backend_batch_read_seconds_bucket{component="cache",le="0.016"} 222038
backend_batch_read_seconds_bucket{component="cache",le="0.032"} 222038
backend_batch_read_seconds_bucket{component="cache",le="0.064"} 222038
backend_batch_read_seconds_bucket{component="cache",le="0.128"} 222038
backend_batch_read_seconds_bucket{component="cache",le="0.256"} 222038
backend_batch_read_seconds_bucket{component="cache",le="0.512"} 222038
backend_batch_read_seconds_bucket{component="cache",le="1.024"} 222038
backend_batch_read_seconds_bucket{component="cache",le="2.048"} 222038
backend_batch_read_seconds_bucket{component="cache",le="4.096"} 222038
backend_batch_read_seconds_bucket{component="cache",le="8.192"} 222038
backend_batch_read_seconds_bucket{component="cache",le="16.384"} 222038
backend_batch_read_seconds_bucket{component="cache",le="32.768"} 222038
backend_batch_read_seconds_bucket{component="cache",le="+Inf"} 222038
backend_batch_read_seconds_sum{component="cache"} 0.9224637709999659
backend_batch_read_seconds_count{component="cache"} 222038
# HELP backend_batch_write_requests_total Number of batch write requests to the backend
# TYPE backend_batch_write_requests_total counter
backend_batch_write_requests_total{component="cache"} 20
# HELP backend_batch_write_seconds Latency for backend batch write operations
# TYPE backend_batch_write_seconds histogram
backend_batch_write_seconds_bucket{component="cache",le="0.001"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.002"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.004"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.008"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.016"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.032"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.064"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.128"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.256"} 20
backend_batch_write_seconds_bucket{component="cache",le="0.512"} 20
backend_batch_write_seconds_bucket{component="cache",le="1.024"} 20
backend_batch_write_seconds_bucket{component="cache",le="2.048"} 20
backend_batch_write_seconds_bucket{component="cache",le="4.096"} 20
backend_batch_write_seconds_bucket{component="cache",le="8.192"} 20
backend_batch_write_seconds_bucket{component="cache",le="16.384"} 20
backend_batch_write_seconds_bucket{component="cache",le="32.768"} 20
backend_batch_write_seconds_bucket{component="cache",le="+Inf"} 20
backend_batch_write_seconds_sum{component="cache"} 2.0111e-05
backend_batch_write_seconds_count{component="cache"} 20
# HELP backend_read_requests_total Number of read requests to the backend
# TYPE backend_read_requests_total counter
backend_read_requests_total{component="backend"} 219100
backend_read_requests_total{component="cache"} 538073
# HELP backend_read_seconds Latency for read operations
# TYPE backend_read_seconds histogram
backend_read_seconds_bucket{component="backend",le="0.001"} 219100
backend_read_seconds_bucket{component="backend",le="0.002"} 219100
backend_read_seconds_bucket{component="backend",le="0.004"} 219100
backend_read_seconds_bucket{component="backend",le="0.008"} 219100
backend_read_seconds_bucket{component="backend",le="0.016"} 219100
backend_read_seconds_bucket{component="backend",le="0.032"} 219100
backend_read_seconds_bucket{component="backend",le="0.064"} 219100
backend_read_seconds_bucket{component="backend",le="0.128"} 219100
backend_read_seconds_bucket{component="backend",le="0.256"} 219100
backend_read_seconds_bucket{component="backend",le="0.512"} 219100
backend_read_seconds_bucket{component="backend",le="1.024"} 219100
backend_read_seconds_bucket{component="backend",le="2.048"} 219100
backend_read_seconds_bucket{component="backend",le="4.096"} 219100
backend_read_seconds_bucket{component="backend",le="8.192"} 219100
backend_read_seconds_bucket{component="backend",le="16.384"} 219100
backend_read_seconds_bucket{component="backend",le="32.768"} 219100
backend_read_seconds_bucket{component="backend",le="+Inf"} 219100
backend_read_seconds_sum{component="backend"} 0.21188745799998257
backend_read_seconds_count{component="backend"} 219100
backend_read_seconds_bucket{component="cache",le="0.001"} 538072
backend_read_seconds_bucket{component="cache",le="0.002"} 538073
backend_read_seconds_bucket{component="cache",le="0.004"} 538073
backend_read_seconds_bucket{component="cache",le="0.008"} 538073
backend_read_seconds_bucket{component="cache",le="0.016"} 538073
backend_read_seconds_bucket{component="cache",le="0.032"} 538073
backend_read_seconds_bucket{component="cache",le="0.064"} 538073
backend_read_seconds_bucket{component="cache",le="0.128"} 538073
backend_read_seconds_bucket{component="cache",le="0.256"} 538073
backend_read_seconds_bucket{component="cache",le="0.512"} 538073
backend_read_seconds_bucket{component="cache",le="1.024"} 538073
backend_read_seconds_bucket{component="cache",le="2.048"} 538073
backend_read_seconds_bucket{component="cache",le="4.096"} 538073
backend_read_seconds_bucket{component="cache",le="8.192"} 538073
backend_read_seconds_bucket{component="cache",le="16.384"} 538073
backend_read_seconds_bucket{component="cache",le="32.768"} 538073
backend_read_seconds_bucket{component="cache",le="+Inf"} 538073
backend_read_seconds_sum{component="cache"} 1.3880030649999617
backend_read_seconds_count{component="cache"} 538073
# HELP backend_requests Number of write requests to the backend
# TYPE backend_requests counter
backend_requests{component="backend",range="false",req=".locks/anadelia.cloud.gravitational.io"} 3
backend_requests{component="backend",range="false",req="/authentication/preference"} 1
backend_requests{component="backend",range="false",req="/authorities/host"} 73032
backend_requests{component="backend",range="false",req="/authorities/jwt"} 73030
backend_requests{component="backend",range="false",req="/authorities/user"} 73030
backend_requests{component="backend",range="false",req="/cloud/lock"} 3894
backend_requests{component="backend",range="false",req="/cluster_configuration/general"} 3
backend_requests{component="backend",range="false",req="/cluster_configuration/name"} 5
backend_requests{component="backend",range="false",req="/cluster_configuration/static_tokens"} 2
backend_requests{component="backend",range="false",req="/namespaces/default"} 1
backend_requests{component="backend",range="false",req="/roles/access"} 1
backend_requests{component="backend",range="false",req="/roles/admin"} 1
backend_requests{component="backend",range="false",req="/roles/auditor"} 1
backend_requests{component="backend",range="false",req="/roles/editor"} 1
backend_requests{component="backend",range="true",req="/access_requests"} 1
backend_requests{component="backend",range="true",req="/apps/servers"} 51
backend_requests{component="backend",range="true",req="/apps/sessions"} 1
backend_requests{component="backend",range="true",req="/authorities/host"} 2
backend_requests{component="backend",range="true",req="/authorities/jwt"} 1
backend_requests{component="backend",range="true",req="/authorities/user"} 1
backend_requests{component="backend",range="true",req="/authservers"} 3
backend_requests{component="backend",range="true",req="/databaseServers/default"} 51
backend_requests{component="backend",range="true",req="/kubeServices"} 51
backend_requests{component="backend",range="true",req="/namespaces"} 1
backend_requests{component="backend",range="true",req="/nodes/default"} 51
backend_requests{component="backend",range="true",req="/proxies"} 1
backend_requests{component="backend",range="true",req="/remoteClusters"} 3
backend_requests{component="backend",range="true",req="/reverseTunnels"} 1
backend_requests{component="backend",range="true",req="/roles"} 2
backend_requests{component="backend",range="true",req="/tokens"} 1
backend_requests{component="backend",range="true",req="/tunnelConnections"} 1
backend_requests{component="backend",range="true",req="/web/sessions"} 1
backend_requests{component="backend",range="true",req="/web/tokens"} 1
backend_requests{component="backend",range="true",req="/web/users"} 53
backend_requests{component="cache",range="false",req="/authorities/host"} 7297
backend_requests{component="cache",range="false",req="/authorities/jwt"} 1
backend_requests{component="cache",range="false",req="/authorities/user"} 3469
backend_requests{component="cache",range="false",req="/cache/6.0.2"} 1
backend_requests{component="cache",range="false",req="/cluster_configuration/general"} 227142
backend_requests{component="cache",range="false",req="/cluster_configuration/name"} 300170
backend_requests{component="cache",range="false",req="/cluster_configuration/static_tokens"} 2
backend_requests{component="cache",range="false",req="/namespaces/default"} 2
backend_requests{component="cache",range="false",req="/roles/access"} 1
backend_requests{component="cache",range="false",req="/roles/admin"} 1
backend_requests{component="cache",range="false",req="/roles/auditor"} 1
backend_requests{component="cache",range="false",req="/roles/editor"} 1
backend_requests{component="cache",range="false",req="/web/users"} 2
backend_requests{component="cache",range="true",req="/access_requests"} 1
backend_requests{component="cache",range="true",req="/apps/servers"} 1
backend_requests{component="cache",range="true",req="/apps/sessions"} 1
backend_requests{component="cache",range="true",req="/authorities/host"} 3
backend_requests{component="cache",range="true",req="/authorities/jwt"} 3
backend_requests{component="cache",range="true",req="/authorities/user"} 3
backend_requests{component="cache",range="true",req="/authservers"} 1
backend_requests{component="cache",range="true",req="/databaseServers/default"} 1
backend_requests{component="cache",range="true",req="/kubeServices"} 1
backend_requests{component="cache",range="true",req="/namespaces"} 3
backend_requests{component="cache",range="true",req="/nodes/default"} 3
backend_requests{component="cache",range="true",req="/proxies"} 1849
backend_requests{component="cache",range="true",req="/remoteClusters"} 1
backend_requests{component="cache",range="true",req="/reverseTunnels"} 220178
backend_requests{component="cache",range="true",req="/roles"} 3
backend_requests{component="cache",range="true",req="/tokens"} 1
backend_requests{component="cache",range="true",req="/tunnelConnections"} 2
backend_requests{component="cache",range="true",req="/web/sessions"} 1
backend_requests{component="cache",range="true",req="/web/tokens"} 1
backend_requests{component="cache",range="true",req="/web/users"} 1
# HELP backend_watcher_queues_total Watcher queue sizes
# TYPE backend_watcher_queues_total gauge
backend_watcher_queues_total{component="auth:cache"} 0
# HELP backend_watchers_total Number of active backend watchers
# TYPE backend_watchers_total gauge
backend_watchers_total{component="backend"} 1
# HELP backend_write_requests_failed_total Number of failed write requests to the backend
# TYPE backend_write_requests_failed_total counter
backend_write_requests_failed_total{component="backend"} 3849
# HELP backend_write_requests_total Number of write requests to the backend
# TYPE backend_write_requests_total counter
backend_write_requests_total{component="backend"} 10605
backend_write_requests_total{component="cache"} 14049
# HELP backend_write_seconds Latency for backend write operations
# TYPE backend_write_seconds histogram
backend_write_seconds_bucket{component="backend",le="0.001"} 0
backend_write_seconds_bucket{component="backend",le="0.002"} 0
backend_write_seconds_bucket{component="backend",le="0.004"} 2540
backend_write_seconds_bucket{component="backend",le="0.008"} 10079
backend_write_seconds_bucket{component="backend",le="0.016"} 10505
backend_write_seconds_bucket{component="backend",le="0.032"} 10584
backend_write_seconds_bucket{component="backend",le="0.064"} 10601
backend_write_seconds_bucket{component="backend",le="0.128"} 10604
backend_write_seconds_bucket{component="backend",le="0.256"} 10604
backend_write_seconds_bucket{component="backend",le="0.512"} 10605
backend_write_seconds_bucket{component="backend",le="1.024"} 10605
backend_write_seconds_bucket{component="backend",le="2.048"} 10605
backend_write_seconds_bucket{component="backend",le="4.096"} 10605
backend_write_seconds_bucket{component="backend",le="8.192"} 10605
backend_write_seconds_bucket{component="backend",le="16.384"} 10605
backend_write_seconds_bucket{component="backend",le="32.768"} 10605
backend_write_seconds_bucket{component="backend",le="+Inf"} 10605
backend_write_seconds_sum{component="backend"} 53.006567974999925
backend_write_seconds_count{component="backend"} 10605
backend_write_seconds_bucket{component="cache",le="0.001"} 14049
backend_write_seconds_bucket{component="cache",le="0.002"} 14049
backend_write_seconds_bucket{component="cache",le="0.004"} 14049
backend_write_seconds_bucket{component="cache",le="0.008"} 14049
backend_write_seconds_bucket{component="cache",le="0.016"} 14049
backend_write_seconds_bucket{component="cache",le="0.032"} 14049
backend_write_seconds_bucket{component="cache",le="0.064"} 14049
backend_write_seconds_bucket{component="cache",le="0.128"} 14049
backend_write_seconds_bucket{component="cache",le="0.256"} 14049
backend_write_seconds_bucket{component="cache",le="0.512"} 14049
backend_write_seconds_bucket{component="cache",le="1.024"} 14049
backend_write_seconds_bucket{component="cache",le="2.048"} 14049
backend_write_seconds_bucket{component="cache",le="4.096"} 14049
backend_write_seconds_bucket{component="cache",le="8.192"} 14049
backend_write_seconds_bucket{component="cache",le="16.384"} 14049
backend_write_seconds_bucket{component="cache",le="32.768"} 14049
backend_write_seconds_bucket{component="cache",le="+Inf"} 14049
backend_write_seconds_sum{component="cache"} 0.12124157699999907
backend_write_seconds_count{component="cache"} 14049
# HELP bpf_lost_command_events Number of lost command events.
# TYPE bpf_lost_command_events counter
bpf_lost_command_events 0
# HELP bpf_lost_disk_events Number of lost disk events.
# TYPE bpf_lost_disk_events counter
bpf_lost_disk_events 0
# HELP bpf_lost_network_events Number of lost network events.
# TYPE bpf_lost_network_events counter
bpf_lost_network_events 0
# HELP etcd_backend_batch_read_requests Number of read requests to the database
# TYPE etcd_backend_batch_read_requests counter
etcd_backend_batch_read_requests 0
# HELP etcd_backend_batch_read_seconds Latency for etcd read operations
# TYPE etcd_backend_batch_read_seconds histogram
etcd_backend_batch_read_seconds_bucket{le="0.001"} 0
etcd_backend_batch_read_seconds_bucket{le="0.002"} 0
etcd_backend_batch_read_seconds_bucket{le="0.004"} 0
etcd_backend_batch_read_seconds_bucket{le="0.008"} 0
etcd_backend_batch_read_seconds_bucket{le="0.016"} 0
etcd_backend_batch_read_seconds_bucket{le="0.032"} 0
etcd_backend_batch_read_seconds_bucket{le="0.064"} 0
etcd_backend_batch_read_seconds_bucket{le="0.128"} 0
etcd_backend_batch_read_seconds_bucket{le="0.256"} 0
etcd_backend_batch_read_seconds_bucket{le="0.512"} 0
etcd_backend_batch_read_seconds_bucket{le="1.024"} 0
etcd_backend_batch_read_seconds_bucket{le="2.048"} 0
etcd_backend_batch_read_seconds_bucket{le="4.096"} 0
etcd_backend_batch_read_seconds_bucket{le="8.192"} 0
etcd_backend_batch_read_seconds_bucket{le="16.384"} 0
etcd_backend_batch_read_seconds_bucket{le="32.768"} 0
etcd_backend_batch_read_seconds_bucket{le="+Inf"} 0
etcd_backend_batch_read_seconds_sum 0
etcd_backend_batch_read_seconds_count 0
# HELP etcd_backend_read_requests Number of read requests to the database
# TYPE etcd_backend_read_requests counter
etcd_backend_read_requests 0
# HELP etcd_backend_read_seconds Latency for etcd read operations
# TYPE etcd_backend_read_seconds histogram
etcd_backend_read_seconds_bucket{le="0.001"} 0
etcd_backend_read_seconds_bucket{le="0.002"} 0
etcd_backend_read_seconds_bucket{le="0.004"} 0
etcd_backend_read_seconds_bucket{le="0.008"} 0
etcd_backend_read_seconds_bucket{le="0.016"} 0
etcd_backend_read_seconds_bucket{le="0.032"} 0
etcd_backend_read_seconds_bucket{le="0.064"} 0
etcd_backend_read_seconds_bucket{le="0.128"} 0
etcd_backend_read_seconds_bucket{le="0.256"} 0
etcd_backend_read_seconds_bucket{le="0.512"} 0
etcd_backend_read_seconds_bucket{le="1.024"} 0
etcd_backend_read_seconds_bucket{le="2.048"} 0
etcd_backend_read_seconds_bucket{le="4.096"} 0
etcd_backend_read_seconds_bucket{le="8.192"} 0
etcd_backend_read_seconds_bucket{le="16.384"} 0
etcd_backend_read_seconds_bucket{le="32.768"} 0
etcd_backend_read_seconds_bucket{le="+Inf"} 0
etcd_backend_read_seconds_sum 0
etcd_backend_read_seconds_count 0
# HELP etcd_backend_tx_requests Number of transaction requests to the database
# TYPE etcd_backend_tx_requests counter
etcd_backend_tx_requests 0
# HELP etcd_backend_tx_seconds Latency for etcd transaction operations
# TYPE etcd_backend_tx_seconds histogram
etcd_backend_tx_seconds_bucket{le="0.001"} 0
etcd_backend_tx_seconds_bucket{le="0.002"} 0
etcd_backend_tx_seconds_bucket{le="0.004"} 0
etcd_backend_tx_seconds_bucket{le="0.008"} 0
etcd_backend_tx_seconds_bucket{le="0.016"} 0
etcd_backend_tx_seconds_bucket{le="0.032"} 0
etcd_backend_tx_seconds_bucket{le="0.064"} 0
etcd_backend_tx_seconds_bucket{le="0.128"} 0
etcd_backend_tx_seconds_bucket{le="0.256"} 0
etcd_backend_tx_seconds_bucket{le="0.512"} 0
etcd_backend_tx_seconds_bucket{le="1.024"} 0
etcd_backend_tx_seconds_bucket{le="2.048"} 0
etcd_backend_tx_seconds_bucket{le="4.096"} 0
etcd_backend_tx_seconds_bucket{le="8.192"} 0
etcd_backend_tx_seconds_bucket{le="16.384"} 0
etcd_backend_tx_seconds_bucket{le="32.768"} 0
etcd_backend_tx_seconds_bucket{le="+Inf"} 0
etcd_backend_tx_seconds_sum 0
etcd_backend_tx_seconds_count 0
# HELP etcd_backend_write_requests Number of wrtie requests to the database
# TYPE etcd_backend_write_requests counter
etcd_backend_write_requests 0
# HELP etcd_backend_write_seconds Latency for etcd write operations
# TYPE etcd_backend_write_seconds histogram
etcd_backend_write_seconds_bucket{le="0.001"} 0
etcd_backend_write_seconds_bucket{le="0.002"} 0
etcd_backend_write_seconds_bucket{le="0.004"} 0
etcd_backend_write_seconds_bucket{le="0.008"} 0
etcd_backend_write_seconds_bucket{le="0.016"} 0
etcd_backend_write_seconds_bucket{le="0.032"} 0
etcd_backend_write_seconds_bucket{le="0.064"} 0
etcd_backend_write_seconds_bucket{le="0.128"} 0
etcd_backend_write_seconds_bucket{le="0.256"} 0
etcd_backend_write_seconds_bucket{le="0.512"} 0
etcd_backend_write_seconds_bucket{le="1.024"} 0
etcd_backend_write_seconds_bucket{le="2.048"} 0
etcd_backend_write_seconds_bucket{le="4.096"} 0
etcd_backend_write_seconds_bucket{le="8.192"} 0
etcd_backend_write_seconds_bucket{le="16.384"} 0
etcd_backend_write_seconds_bucket{le="32.768"} 0
etcd_backend_write_seconds_bucket{le="+Inf"} 0
etcd_backend_write_seconds_sum 0
etcd_backend_write_seconds_count 0
# HELP firestore_events_backend_batch_read_requests Number of batch read requests to firestore events
# TYPE firestore_events_backend_batch_read_requests counter
firestore_events_backend_batch_read_requests 0
# HELP firestore_events_backend_batch_read_seconds Latency for firestore events batch read operations
# TYPE firestore_events_backend_batch_read_seconds histogram
firestore_events_backend_batch_read_seconds_bucket{le="0.001"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.002"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.004"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.008"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.016"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.032"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.064"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.128"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.256"} 0
firestore_events_backend_batch_read_seconds_bucket{le="0.512"} 0
firestore_events_backend_batch_read_seconds_bucket{le="1.024"} 0
firestore_events_backend_batch_read_seconds_bucket{le="2.048"} 0
firestore_events_backend_batch_read_seconds_bucket{le="4.096"} 0
firestore_events_backend_batch_read_seconds_bucket{le="8.192"} 0
firestore_events_backend_batch_read_seconds_bucket{le="16.384"} 0
firestore_events_backend_batch_read_seconds_bucket{le="32.768"} 0
firestore_events_backend_batch_read_seconds_bucket{le="+Inf"} 0
firestore_events_backend_batch_read_seconds_sum 0
firestore_events_backend_batch_read_seconds_count 0
# HELP firestore_events_backend_batch_write_requests Number of batch write requests to firestore events
# TYPE firestore_events_backend_batch_write_requests counter
firestore_events_backend_batch_write_requests 0
# HELP firestore_events_backend_batch_write_seconds Latency for firestore events batch write operations
# TYPE firestore_events_backend_batch_write_seconds histogram
firestore_events_backend_batch_write_seconds_bucket{le="0.001"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.002"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.004"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.008"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.016"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.032"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.064"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.128"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.256"} 0
firestore_events_backend_batch_write_seconds_bucket{le="0.512"} 0
firestore_events_backend_batch_write_seconds_bucket{le="1.024"} 0
firestore_events_backend_batch_write_seconds_bucket{le="2.048"} 0
firestore_events_backend_batch_write_seconds_bucket{le="4.096"} 0
firestore_events_backend_batch_write_seconds_bucket{le="8.192"} 0
firestore_events_backend_batch_write_seconds_bucket{le="16.384"} 0
firestore_events_backend_batch_write_seconds_bucket{le="32.768"} 0
firestore_events_backend_batch_write_seconds_bucket{le="+Inf"} 0
firestore_events_backend_batch_write_seconds_sum 0
firestore_events_backend_batch_write_seconds_count 0
# HELP firestore_events_backend_write_requests Number of write requests to firestore events
# TYPE firestore_events_backend_write_requests counter
firestore_events_backend_write_requests 0
# HELP firestore_events_backend_write_seconds Latency for firestore events write operations
# TYPE firestore_events_backend_write_seconds histogram
firestore_events_backend_write_seconds_bucket{le="0.001"} 0
firestore_events_backend_write_seconds_bucket{le="0.002"} 0
firestore_events_backend_write_seconds_bucket{le="0.004"} 0
firestore_events_backend_write_seconds_bucket{le="0.008"} 0
firestore_events_backend_write_seconds_bucket{le="0.016"} 0
firestore_events_backend_write_seconds_bucket{le="0.032"} 0
firestore_events_backend_write_seconds_bucket{le="0.064"} 0
firestore_events_backend_write_seconds_bucket{le="0.128"} 0
firestore_events_backend_write_seconds_bucket{le="0.256"} 0
firestore_events_backend_write_seconds_bucket{le="0.512"} 0
firestore_events_backend_write_seconds_bucket{le="1.024"} 0
firestore_events_backend_write_seconds_bucket{le="2.048"} 0
firestore_events_backend_write_seconds_bucket{le="4.096"} 0
firestore_events_backend_write_seconds_bucket{le="8.192"} 0
firestore_events_backend_write_seconds_bucket{le="16.384"} 0
firestore_events_backend_write_seconds_bucket{le="32.768"} 0
firestore_events_backend_write_seconds_bucket{le="+Inf"} 0
firestore_events_backend_write_seconds_sum 0
firestore_events_backend_write_seconds_count 0
# HELP gcs_event_storage_downloads Number of downloads from the GCS backend
# TYPE gcs_event_storage_downloads counter
gcs_event_storage_downloads 0
# HELP gcs_event_storage_downloads_seconds Latency for GCS download operations
# TYPE gcs_event_storage_downloads_seconds histogram
gcs_event_storage_downloads_seconds_bucket{le="0.001"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.002"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.004"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.008"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.016"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.032"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.064"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.128"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.256"} 0
gcs_event_storage_downloads_seconds_bucket{le="0.512"} 0
gcs_event_storage_downloads_seconds_bucket{le="1.024"} 0
gcs_event_storage_downloads_seconds_bucket{le="2.048"} 0
gcs_event_storage_downloads_seconds_bucket{le="4.096"} 0
gcs_event_storage_downloads_seconds_bucket{le="8.192"} 0
gcs_event_storage_downloads_seconds_bucket{le="16.384"} 0
gcs_event_storage_downloads_seconds_bucket{le="32.768"} 0
gcs_event_storage_downloads_seconds_bucket{le="+Inf"} 0
gcs_event_storage_downloads_seconds_sum 0
gcs_event_storage_downloads_seconds_count 0
# HELP gcs_event_storage_uploads Number of uploads to the GCS backend
# TYPE gcs_event_storage_uploads counter
gcs_event_storage_uploads 0
# HELP gcs_event_storage_uploads_seconds Latency for GCS upload operations
# TYPE gcs_event_storage_uploads_seconds histogram
gcs_event_storage_uploads_seconds_bucket{le="0.001"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.002"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.004"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.008"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.016"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.032"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.064"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.128"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.256"} 0
gcs_event_storage_uploads_seconds_bucket{le="0.512"} 0
gcs_event_storage_uploads_seconds_bucket{le="1.024"} 0
gcs_event_storage_uploads_seconds_bucket{le="2.048"} 0
gcs_event_storage_uploads_seconds_bucket{le="4.096"} 0
gcs_event_storage_uploads_seconds_bucket{le="8.192"} 0
gcs_event_storage_uploads_seconds_bucket{le="16.384"} 0
gcs_event_storage_uploads_seconds_bucket{le="32.768"} 0
gcs_event_storage_uploads_seconds_bucket{le="+Inf"} 0
gcs_event_storage_uploads_seconds_sum 0
gcs_event_storage_uploads_seconds_count 0
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 3.8781e-05
go_gc_duration_seconds{quantile="0.25"} 4.9561e-05
go_gc_duration_seconds{quantile="0.5"} 5.8951e-05
go_gc_duration_seconds{quantile="0.75"} 7.8432e-05
go_gc_duration_seconds{quantile="1"} 0.001554102
go_gc_duration_seconds_sum 1.848155996
go_gc_duration_seconds_count 23944
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 50
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.15.5"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.3952152e+07
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 2.15517080672e+11
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 3.3975e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 2.287033452e+09
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 1.4517610885242157e-05
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 6.009264e+06
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 1.3952152e+07
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 4.8308224e+07
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 1.7457152e+07
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 75362
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 4.4040192e+07
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 6.5765376e+07
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.6172465024539893e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 0
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 2.287108814e+09
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 6944
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 220728
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 327680
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 1.8327456e+07
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 817876
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 1.343488e+06
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 1.343488e+06
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 7.7677568e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 12
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 4556.81
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1e+06
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 19
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 8.0830464e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.61607804542e+09
# HELP process_state State of the teleport process: 0 - ok, 1 - recovering, 2 - degraded, 3 - starting
# TYPE process_state gauge
process_state 0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.550143488e+09
# HELP process_virtual_memory_max_bytes Maximum amount of virtual memory available in bytes.
# TYPE process_virtual_memory_max_bytes gauge
process_virtual_memory_max_bytes -1
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 77901
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
# HELP proxy_ssh_sessions_total Number of active sessions through this proxy
# TYPE proxy_ssh_sessions_total gauge
proxy_ssh_sessions_total 0
# HELP rx Number of bytes received.
# TYPE rx counter
rx 0
# HELP server_interactive_sessions_total Number of active sessions to this host
# TYPE server_interactive_sessions_total gauge
server_interactive_sessions_total 0
# HELP tx Number of bytes transmitted.
# TYPE tx counter
tx 0
```

### PR DESCRIPTION
**Pull request by NajiObeid**
issue https://github.com/gravitational/teleport/issues/6271

Basically what this does is to lazy init prometheus collectors when they're first accessed instead of at the `init()` stage.
That means we would not be collecting a bunch of zeros for collectors that will never be used.

### CODE REVIEW

**Comment by russjones** [comment]
@r0mant Can you review this?

File: lib/utils/prometheus.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+
+import (
+	"github.com/prometheus/client_golang/prometheus"
+)
+
+// RegisterPrometheusCollectors is a wrapper around prometheus.Register that
+// - ignores equal or re-registered collectors
+// - return an error if a collector does not fulfill the consistency and
+//   uniqueness criteria
+func RegisterPrometheusCollectors(collectors ...prometheus.Collector) error {
```
Comment (knisbet) [inline lib/utils/prometheus.go:11]: If I understand this correctly, the teleport team would need to be careful with things like re-init a service that registry prometheus metrics, since they might get dropped due to a previous registration of the same metric? And if it were to happen the metrics would just be missing, since they're being recorded in an unregistered object?

Comment (NajiObeid) [reply lib/utils/prometheus.go:11]: No, re-registering is fine. but changing a metric type is not.
So if someone is re-registering a metric with the same name under a different type, we'd get an error here, while teleport would panic in the previous implementation.

File: lib/auth/auth.go [hunk 2]
```diff
@@ -73,6 +73,12 @@ type ServerOption func(*Server)
 
 // NewServer creates and configures a new Server instance
 func NewServer(cfg *InitConfig, opts ...ServerOption) (*Server, error) {
+	err := utils.RegisterPrometheusCollectors(generateRequestsCount, generateThrottledRequestsCount,
```
Comment (r0mant) [inline lib/auth/auth.go:76]: Nit: As a small stylistic suggestion, I would keep the list of prometheus collectors as a package-level variable, then this Register call would be cleaner when there are a lot of collectors and also easier to see all collectors:

```go
func NewServer(...) (*Server, error) {
  err := utils.RegisterPrometheusCollectors(prometheusCollectors)
  ...
}

var prometheusCollectors = []prometheusCollector{
  generateRequestCount,
  generateThrottleRequestsCount,
  ...
}
```

File: lib/backend/etcdbk/etcd.go [hunk 3]
```diff
@@ -182,6 +170,13 @@ var _ backend.Backend = &EtcdBackend{}
 // New returns new instance of Etcd-powered backend
 func New(ctx context.Context, params backend.Params) (*EtcdBackend, error) {
 	var err error
+
+	err = utils.RegisterPrometheusCollectors(writeLatencies, txLatencies, batchReadLatencies,
```
Comment (r0mant) [inline lib/backend/etcdbk/etcd.go:174]: Same comment as above about keeping file-level list of collectors.

Comment (r0mant) [reply lib/backend/etcdbk/etcd.go:174]: Also, remove `var err error` above and just do `err := ...` here.

File: lib/backend/report.go [hunk 4]
```diff
@@ -77,6 +77,14 @@ type Reporter struct {
 
 // NewReporter returns a new Reporter.
 func NewReporter(cfg ReporterConfig) (*Reporter, error) {
+	err := utils.RegisterPrometheusCollectors(watchers, watcherQueues, requests, writeRequests,
```
Comment (r0mant) [inline lib/backend/report.go:80]: Same comment as above.

File: lib/bpf/command.go [hunk 5]
```diff
@@ -85,6 +79,11 @@ type exec struct {
 func startExec(closeContext context.Context, pageCount int) (*exec, error) {
 	var err error
 
+	err = utils.RegisterPrometheusCollectors(lostCommandEvents)
```
Comment (r0mant) [inline lib/bpf/command.go:82]: Remove `var err error` and do `err :=`.

File: lib/bpf/disk.go [hunk 6]
```diff
@@ -82,6 +76,11 @@ type open struct {
 func startOpen(closeContext context.Context, pageCount int) (*open, error) {
 	var err error
 
+	err = utils.RegisterPrometheusCollectors(lostDiskEvents)
```
Comment (r0mant) [inline lib/bpf/disk.go:79]: Use `err :=` like above.

File: lib/bpf/network.go [hunk 7]
```diff
@@ -114,6 +108,11 @@ type conn struct {
 func startConn(closeContext context.Context, pageCount int) (*conn, error) {
 	var err error
 
+	err = utils.RegisterPrometheusCollectors(lostNetworkEvents)
```
Comment (r0mant) [inline lib/bpf/network.go:111]: `err :=` :)

File: lib/events/auditlog.go [hunk 8]
```diff
@@ -236,6 +228,11 @@ func (a *AuditLogConfig) CheckAndSetDefaults() error {
 // a given directory. Session recording can be disabled by setting
 // recordSessions to false.
 func NewAuditLog(cfg AuditLogConfig) (*AuditLog, error) {
+	err := utils.RegisterPrometheusCollectors(auditOpenFiles, auditDiskUsed, auditFailedDisk, AuditFailedEmit)
```
Comment (r0mant) [inline lib/events/auditlog.go:231]: Same comment as above with list of collectors.

File: lib/events/firestoreevents/firestoreevents.go [hunk 9]
```diff
@@ -268,6 +258,12 @@ type event struct {
 // New returns new instance of Firestore backend.
 // It's an implementation of backend API's NewFunc
 func New(cfg EventsConfig) (*Log, error) {
+	err := utils.RegisterPrometheusCollectors(writeRequests, batchWriteRequests, batchReadRequests,
```
Comment (r0mant) [inline lib/events/firestoreevents/firestoreevents.go:261]: Same as above.

File: lib/events/gcssessions/gcshandler.go [hunk 10]
```diff
@@ -193,6 +185,11 @@ func DefaultNewHandler(cfg Config) (*Handler, error) {
 
 // NewHandler returns a new handler with specific context, cancelFunc, and client
 func NewHandler(ctx context.Context, cancelFunc context.CancelFunc, cfg Config, client *storage.Client) (*Handler, error) {
+	err := utils.RegisterPrometheusCollectors(uploadRequests, downloadRequests, uploadLatencies, downloadLatencies)
```
Comment (r0mant) [inline lib/events/gcssessions/gcshandler.go:188]: Same as above.

File: lib/utils/prometheus.go [hunk 11]
```diff
@@ -0,0 +1,21 @@
...
+	for _, c := range collectors {
+		if err := prometheus.Register(c); err != nil {
+			if _, ok := err.(prometheus.AlreadyRegisteredError); ok {
+				continue
+			}
+			return err
```
Comment (r0mant) [inline lib/utils/prometheus.go:17]: trace.Wrap(err)

File: lib/srv/authhandlers.go [hunk 12]
```diff
@@ -65,6 +81,34 @@ type AuthHandlers struct {
...
 
+// NewAuthHandlers initializes authorization and authentication handlers
+func NewAuthHandlers(
+	server Server,
+	component string,
+	accessPoint auth.AccessPoint,
+	fips bool,
+	emitter events.Emitter,
+	clock clockwork.Clock,
+) (*AuthHandlers, error) {
```
Comment (r0mant) [inline lib/srv/authhandlers.go:92]: If you're making a constructor method, let's then also make a respective `AuthHandlersConfig` struct so that we don't have to pass 6 arguments.

File: lib/utils/prometheus.go [hunk 13]
```diff
@@ -0,0 +1,21 @@
+package utils
+
+import (
+	"github.com/prometheus/client_golang/prometheus"
+)
+
+// RegisterPrometheusCollectors is a wrapper around prometheus.Register that
+// - ignores equal or re-registered collectors
+// - return an error if a collector does not fulfill the consistency and
```
Comment (r0mant) [inline lib/utils/prometheus.go:9]: return**s**

File: lib/utils/prometheus.go [hunk 14]
```diff
@@ -0,0 +1,21 @@
+package utils
```
Comment (r0mant) [inline lib/utils/prometheus.go:1]: Missing license header.

File: lib/srv/authhandlers.go [hunk 15]
```diff
@@ -65,6 +80,30 @@ type AuthHandlers struct {
...
+	err := utils.RegisterPrometheusCollectors(prometheusCollectors...)
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+
+	return &AuthHandlers{
+		c: config,
+		Entry: log.WithFields(log.Fields{
+			trace.Component:       config.Component,
+			trace.ComponentFields: log.Fields{},
```
Comment (r0mant) [inline lib/srv/authhandlers.go:102]: Feels like this can be removed? If you want to get a logger with component, this is what I usually do:

```go
log.WithField(trace.Component, config.Component)
```

File: lib/srv/authhandlers.go [hunk 16]
```diff
@@ -65,6 +80,30 @@ type AuthHandlers struct {
 	Clock clockwork.Clock
 }
 
+// AuthHandlers are common authorization and authentication related handlers
+// used by the regular and forwarding server.
+type AuthHandlers struct {
+	*log.Entry
```
Comment (r0mant) [inline lib/srv/authhandlers.go:86]: Nit: Could you also unembed the logger please while you're here if it's not too much refactoring?

```go
type AuthHandlers struct {
  log *log.Entry
  ...
}
```

File: lib/utils/prometheus.go [hunk 17]
```diff
@@ -0,0 +1,39 @@
+/*
+Copyright 2015-2021 Gravitational, Inc.
```
Comment (r0mant) [inline lib/utils/prometheus.go:2]: Nit: Just do `2021`, we only usually write the year the file was created/updated in.

**Review by r0mant — APPROVED** [review]

**Review by r0mant — APPROVED** [review]
@NajiObeid This should be good to merge once you address the merge conflict.
