### PR TITLE
Fix missing identity in certs logic

### LINKED ISSUE #10081: access plugin credentials cause unexpected auth server WARN message
### Description

**What happened**:

When following the instructions in the readme at https://github.com/gravitational/teleport/tree/master/examples/workflows

The plugin connects with the credentials generated via `tctl auth sign` with no problem.

However, the following warning appears in the auth service log:

```
2022-02-01T17:33:50Z WARN             "Failed to find roles or traits in x509 identity for access-plugin. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:748
```

The role information appears to exist in the x509 cert generated by `tctl auth sign` as `O=rolename` in the Subject, so I believe that this warning should not happen.

**What you expected to happen**:

`tctl auth sign` should produce a certificate with the role information in the certificate so this warning never appears, or teleport should respect the role information that does appear to be present already.

### Reproduction Steps

Follow the instructions starting at https://github.com/gravitational/teleport/tree/master/examples/workflows#create-resources until the plugin is connected. Observe the error in the logs.

### Server Details
Teleport Enterprise 8.0.6 running in kubernetes

### Client Details
I reproduced this by using an identity file produced by the tctl 8.1.0 darwin binary from the official teleport enterprise .pkg distribution.

I compiled the workflow example fresh today from master when trying to reproduce the issue. gz#3899

### PR DESCRIPTION
**Pull request by Joerger**
This PR fixes the missing identity in cert logic to only check if the roles extension is missing, rather than roles or traits. This logic was originally intended from discerning legacy certs from standard certs.

There are many supported use cases where traits will be nil in standard certs, such as in Teleport plugins where the user+role is created from a yaml file, and checking the roles alone is sufficient for differentiating legacy certs.

Closes https://github.com/gravitational/teleport/issues/10081

### CODE REVIEW

File: lib/services/role.go [hunk 1]
```diff
@@ -778,9 +778,9 @@ func ExtractFromCertificate(cert *ssh.Certificate) ([]string, wrappers.Traits, e
 // which Teleport passes along as a *tlsca.Identity. If roles and traits do not
 // exist in the certificates, they are extracted from the backend.
 func ExtractFromIdentity(access UserGetter, identity tlsca.Identity) ([]string, wrappers.Traits, error) {
-	// For legacy certificates, fetch roles and traits from the services.User
-	// object in the backend.
-	if missingIdentity(identity) {
+	// Legacy certs are not encoded with roles or traits,
+	// so we fallback to the traits and roles in the backend.
+	if identity.Groups == nil {
```
Comment (rosstimothy) [inline lib/services/role.go:783]: Should this check for length == 0 like in `missingIdentity`?
```suggestion
	if len(identity.Groups) == 0 {
```

File: lib/services/role.go [hunk 2]
```diff
@@ -778,9 +778,9 @@ func ExtractFromCertificate(cert *ssh.Certificate) ([]string, wrappers.Traits, e
 // which Teleport passes along as a *tlsca.Identity. If roles and traits do not
 // exist in the certificates, they are extracted from the backend.
 func ExtractFromIdentity(access UserGetter, identity tlsca.Identity) ([]string, wrappers.Traits, error) {
-	// For legacy certificates, fetch roles and traits from the services.User
-	// object in the backend.
-	if missingIdentity(identity) {
+	// Legacy certs are not encoded with roles or traits,
```
Comment (rosstimothy) [inline lib/services/role.go:781]: This PR removes the check for `or traits`, perhaps this comment could reflect that and elaborate on why checking for groups is sufficient.

File: lib/services/role.go (hunk 1 above)
Comment (Joerger) [reply lib/services/role.go:783]: I intentionally changed it to nil since what we want to check is whether the certificate was encoded with roles, not whether the user has any roles. If a user somehow had empty roles but `{}` was encoded, then we don't need to fallback.

In practice a user can't have empty roles so this is functionally the same, but more expressive of the intent IMO.

Comment (jimbishopp) [reply lib/services/role.go:785]: Your reasoning for changing it to nil makes sense. I think the problem is that it relies on all upstream callers initializing the slice correctly. I try to avoid making a distinction between a nil slice and a zero-length slice for this reason. E.g. some decoders will initialize slices to nil or zero length indiscriminately. Since our contract for roles/Groups properly says there is no difference between nil and zero-length (user has roles or is not initialized), it may be better if this checks len/zero so we're not relying on callers to make the distinction.

**Review by jimbishopp — APPROVED** [review]

**Review by rosstimothy — COMMENTED** [review]
It looks like this might be breaking `TestAuthorizeWithLocksForLocalUser`

**Review by rosstimothy — APPROVED** [review]
