### PR TITLE
Fixed regressions in "tsh login <clusterName>".

### LINKED ISSUE #3102: Logging into a trusted cluster from the command line does not work if authentication is needed
**What happened**: I tried to log into a trusted cluster (`gus-east.gravitational.co`) via the main cluster (`gus-main.gravitational.co`) but this did not work - my context was set to `gus-main.gravitational.co` instead.

```
$ tsh login --proxy=gus-main.gravitational.co gus-east.gravitational.co
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:41565/8d088c1a-2250-42e4-84f7-5a88451db35b
> Profile URL:  https://gus-main.gravitational.co:3080
  Logged in as: gus@gravitational.com
  Cluster:      gus-main.gravitational.co
  Roles:        clusteradmin*
  Logins:       root
  Valid until:  2019-10-24 04:53:13 -0300 ADT [valid for 12h0m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty


* RBAC is only available in Teleport Enterprise
  https://gravitational.com/teleport/docs/enterprise
```

Running exactly the same command again at this point achieved the desired result:

```
$ tsh login --proxy=gus-main.gravitational.co gus-east.gravitational.co
> Profile URL:  https://gus-main.gravitational.co:3080
  Logged in as: gus@gravitational.com
  Cluster:      gus-east.gravitational.co
  Roles:        clusteradmin*
  Logins:       root
  Valid until:  2019-10-24 04:53:13 -0300 ADT [valid for 12h0m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty


* RBAC is only available in Teleport Enterprise
  https://gravitational.com/teleport/docs/enterprise
```

**What you expected to happen**: To be logged straight into `gus-east.gravitational.co` after authentication was complete.

**How to reproduce it (as minimally and precisely as possible)**: Try to log into a trusted cluster via a root cluster without a valid certificate.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.1.2git:v4.1.2-0-g7886df10 go1.12.1`
- Tsh version (use `tsh version`): `Teleport v4.1.2 git:v4.1.2-0-g7886df10 go1.12.1`
- OS (e.g. from /etc/os-release): `Fedora 29`

### LINKED ISSUE #3550: tsh doesn't set default cluster name
### Description

**What happened**:
tsh doesn't set the correct default cluster name

**What you expected to happen**:
tsh sets the cluster name from tsh login command 

**How to reproduce it (as minimally and precisely as possible)**:
- run `tsh login cluster_name`. cluster_name should be a name of a "leaf" cluster
- check the cluster name in the tsh status. It will be set to the "root" cluster instead of the "leaf"

### Environment
- Teleport version (use `teleport version`): n/a
- Tsh version (use `tsh version`): Teleport v4.2.8 git:v4.2.8-0-ga9015b33 go1.13.2
- OS (e.g. from `/etc/os-release`): MacOs Catalina 10.15.4

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
mixed
**Browser environment**

- Browser Version (for UI-related issues):n/a
- Install tools:n/a
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`

```
tsh -d login cluster-name
INFO [CLIENT]    no host login given. defaulting to user client/api.go:784
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "/private/tmp/com.apple.launchd.vdXVPLJrzF/Listeners". client/api.go:2061
DEBU [CLIENT]    not using loopback pool for remote proxy addr: tproxy.example.com:3080 client/api.go:2026
DEBU [CLIENT]    HTTPS client init(proxyAddr=tproxy.example.com:3080 , insecure=false) client/weblogin.go:252
DEBU [CLIENT]    samlLogin start client/api.go:1971
DEBU [CLIENT]    not using loopback pool for remote proxy addr: tproxy.example.com:3080 :3080 client/api.go:2026
DEBU [CLIENT]    HTTPS client init(proxyAddr=tproxy.example.com:3080 , insecure=false) client/weblogin.go:252
INFO [CLIENT]    Waiting for response at: http://127.0.0.1:51577. client/redirect.go:128
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:51577/a753d15b-daa1-487a-92b1-36d9e83dba26
DEBU [CLIENT]    Got response from browser. client/weblogin.go:387
DEBU [KEYAGENT]  Adding CA key for root-cluster client/keyagent.go:238
DEBU [KEYSTORE]  Adding known host root-cluster with key: SHA256:4sZfFBFs4CmKUbs9tYyyTSMj+VsA client/keystore.go:355
INFO [CLIENT]    Connecting proxy=tproxy.example.com:3023  login='root' method=0 client/api.go:1603
DEBU [KEYAGENT]  Validated host tproxy.example.com:3023. client/keyagent.go:280
INFO [CLIENT]    Successful auth with proxytproxy.example.com:3023 client/api.go:1594
DEBU [KEYSTORE]  Adding trusted cluster certificate authority "SERIALNUMBER=76453733570814102584253280780757284658,CN=root-cluster,O=root-cluster" to trusted pool. client/keystore.go:328
DEBU [KEYSTORE]  Returning SSH certificate "/Users/username/.tsh/keys/tproxy.root-cluster.aws.reg.example.com/username@int.example.com-cert.pub" valid until "2020-04-09 02:05:07 -0700 PDT", TLS certificate "/Users/username/.tsh/keys/tproxy.root-cluster.aws.reg.example.com/username@int.example.com-x509.pem" valid until "2020-04-09 09:05:07 +0000 UTC". client/keystore.go:262
DEBU [CLIENT]    Client  is connecting to auth server on cluster "root-cluster". client/client.go:469
DEBU [KEYAGENT]  Adding CA key for root-cluster client/keyagent.go:238
DEBU [KEYSTORE]  Adding known host root-cluster with key: SHA256:4sZfFBFs4jeOSt6EKUbs9tYyyTSMj+VsA client/keystore.go:355
DEBU [CLIENT:KU] Found kubeconfig in environment at ''. client/kubeclient.go:156
DEBU [KEYSTORE]  Returning SSH certificate "/Users/username/.tsh/keys/tproxy.root-cluster.aws.reg.example.com/username@int.example.com-cert.pub" valid until "2020-04-09 02:05:07 -0700 PDT", TLS certificate "/Users/username/.tsh/keys/tproxy.root-cluster.aws.reg.example.com/username@int.example.com-x509.pem" valid until "2020-04-09 09:05:07 +0000 UTC". client/keystore.go:262
DEBU [CLIENT:KU] Found kubeconfig in environment at ''. client/kubeclient.go:156
DEBU [KEYSTORE]  Returning SSH certificate "/Users/username/.tsh/keys/tproxy.root-cluster.aws.reg.example.com/username@int.example.com-cert.pub" valid until "2020-04-09 02:05:07 -0700 PDT", TLS certificate "/Users/username/.tsh/keys/tproxy.root-cluster.aws.reg.example.com/username@int.example.com-x509.pem" valid until "2020-04-09 09:05:07 +0000 UTC". client/keystore.go:262
> Profile URL:  https://tproxy.root-cluster.aws.reg.example.com:3080
  Logged in as: username@int.example.com
  Cluster:      root-cluster
  Roles:        role, role1*
  Traits:       groups: [Everyone role1]
                username: [username]
  Logins:       root, username
  Valid until:  2020-04-09 02:05:07 -0700 PDT [valid for 12h0m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty


* RBAC is only available in Teleport Enterprise
  https://gravitational.com/teleport/docs/enterprise
```

### PR DESCRIPTION
**Pull request by russjones**
**Description**

Fixed regressions in how the cluster name was set in the profile when doing `tsh login <clusterName>`. The following examples illustrate expected behavior.

Suppose root cluster is `example.com` and the leaf cluster is `leaf.example.com`.

* `tsh login` will update profile to `example.com`.
* `tsh login example.com` will update profile to `example.com`.
* `tsh login leaf.example.com` will update profile to `leaf.example.com`.
* `tsh login invalid.example.com` will return an error.

Note: The profile will not be updated if an identity flag is provided. This means the following command will NOT update the profile:

```
tsh --proxy=example.com login --out=certs.pem leaf.example.com
```

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/3550
Fixes https://github.com/gravitational/teleport/issues/3102

### CODE REVIEW

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Review by fspmarshall — APPROVED** [review]

File: lib/client/api.go [hunk 1]
```diff
@@ -1752,15 +1753,58 @@ func (tc *TeleportClient) Login(ctx context.Context, activateKey bool) (*Key, er
...
+	leafClusters, err := certGetter.GetTrustedCA(ctx, certificateClusterName)
+	if err != nil {
+		return "", trace.Wrap(err)
+	}
+	for _, leafCluster := range leafClusters {
+		if leafCluster.GetClusterName() == clusterName {
+			return clusterName, nil
+		}
+	}
+	return "", trace.BadParameter("unknown cluster: %v, run \"tsh clusters\" for a list of clusters", clusterName)
```
Comment (awly) [inline lib/client/api.go:1805]: nit: use a raw string to avoid escaping.
also, use `%q` to catch any invisible characters.

**Review by awly — APPROVED** [review]

**Review by webvictim — APPROVED** [review]
