### PR TITLE
Kubernetes Portforward via Websockets

### LINKED ISSUE #18783: Kubernetes PortForward fails when called from a Kubernetes client that only supports websockets
Expected behavior:
Teleport must upgrade WebSocket connections.

Current behavior:
Teleport does not support WebSocket upgrades when using portforward

Related to #15463

### PR DESCRIPTION
**Pull request by tigrato**
This PR extends the Kubernetes Service to support the WebSocket protocol in Kubernetes Porforward calls.

The Websocket protocol is required so that Kubernetes clients like C#, Python, and Javascript can create port forward requests to Kubernetes PODs. Although Teleport supports clients using WebSocket protocol, it still uses SPDY protocol when connecting to upstreams - Teleport Services or Kubernetes API.

Contrary to requests through SPDY, WebSocket requests do not support any concurrency or multiplexing. This is a protocol limitation since it only creates a single stream pair per port - data and error streams. When using it concurrently, requests will be mixed and fail.

Fixes #18783

### CODE REVIEW

File: lib/kube/proxy/testing/kube_server/kube_mock.go [hunk 1]
```diff
@@ -76,6 +76,15 @@ const (
 	// underlying protocol does not support half closed streams.
 	// It is only required for websockets.
 	CloseStreamMessage = "\r\nexit_message\r\n"
+
+	// PortForwardProtocolV1Name is the subprotocol "portforward.k8s.io" is used for port forwarding
+	PortForwardProtocolV1Name = "portforward.k8s.io"
```
Comment (codingllama) [inline lib/kube/proxy/testing/kube_server/kube_mock.go:81]: Do we need the new consts to be public?

File: lib/kube/proxy/testing/kube_server/kube_mock.go [hunk 2]
```diff
@@ -527,3 +538,82 @@ func (s *KubeMockServer) selfSubjectAccessReviews(w http.ResponseWriter, req *ht
...
+			break
+		}
+	}
+
+	buf := make([]byte, 1024)
+	n, err := data.Read(buf)
+	if err != nil {
+		errStream.Write([]byte(err.Error()))
+	}
+	data.Write([]byte(fmt.Sprintf(PortForwardPayload, p.ByName("podName"), string(buf[:n]))))
```
Comment (codingllama) [inline lib/kube/proxy/testing/kube_server/kube_mock.go:587]: I'd rather write `PortForwardPayload` explicitly here, makes it easier to reason about it when reading.

File: lib/kube/proxy/testing/kube_server/kube_mock.go [hunk 3]
```diff
@@ -527,3 +538,82 @@ func (s *KubeMockServer) selfSubjectAccessReviews(w http.ResponseWriter, req *ht
...
+
+// portforward supports SPDY protocols only. Teleport always uses SPDY when
+// portforwarding to upstreams even if the original request is WebSocket.
+func (s *KubeMockServer) portforward(w http.ResponseWriter, req *http.Request, p httprouter.Params) (resp interface{}, err error) {
+	_, err = httpstream.Handshake(req, w, []string{PortForwardProtocolV1Name})
+	if err != nil {
+		return
+	}
+
+	streamChan := make(chan httpstream.Stream, 1)
```
Comment (codingllama) [inline lib/kube/proxy/testing/kube_server/kube_mock.go:550]: Does this need the buffer? If yes, why is it `1`? Use unbuffered otherwise.

File: lib/kube/proxy/testing/kube_server/kube_mock.go [hunk 4]
```diff
@@ -527,3 +538,82 @@ func (s *KubeMockServer) selfSubjectAccessReviews(w http.ResponseWriter, req *ht
...
+	data.Write([]byte(fmt.Sprintf(PortForwardPayload, p.ByName("podName"), string(buf[:n]))))
+	return
+}
+
+// httpStreamReceived is the httpstream.NewStreamHandler for port
+// forward streams. It checks each stream's port and stream type headers,
+// rejecting any streams that with missing or invalid values. Each valid
+// stream is sent to the streams channel.
+func httpStreamReceived(ctx context.Context, streams chan httpstream.Stream) func(httpstream.Stream, <-chan struct{}) error {
+	return func(stream httpstream.Stream, replySent <-chan struct{}) error {
```
Comment (codingllama) [inline lib/kube/proxy/testing/kube_server/kube_mock.go:596]: Is `replySent` unused on purpose? Could we add a comment, or rename to `unusedReplySent`, so it's more explicit.

File: lib/kube/proxy/testing/kube_server/kube_mock.go [hunk 5]
```diff
@@ -527,3 +538,82 @@ func (s *KubeMockServer) selfSubjectAccessReviews(w http.ResponseWriter, req *ht
...
+		}
+		if streamType != StreamTypeError && streamType != StreamTypeData {
+			return trace.BadParameter("invalid stream type %q", streamType)
+		}
+
+		select {
+		case streams <- stream:
+			return nil
+		case <-ctx.Done():
+			return trace.BadParameter("request has been canceled")
```
Comment (codingllama) [inline lib/kube/proxy/testing/kube_server/kube_mock.go:616]: Typically we'd pass ctx.Err() forward:

```suggestion
			return trace.Wrap(ctx.Err())
```

File: lib/kube/proxy/websocket_client_test.go [hunk 6]
```diff
@@ -64,23 +66,67 @@ type wsStreamExecutor struct {
...
+// Unfortunately, the K8S Websocket protocol does not support half-closed streams,
+// i.e. indicating that nothing else will be sent via stdin. If the server
+// reads the stdin stream until io.EOF is received, it will block on reading.
+// This issue is being tracked by https://github.com/kubernetes/kubernetes/issues/89899
+// To prevent this issue, and uniquely for testing, this client will send
+// an exit keyword specified by testingkubemock.CloseStreamMessage. Our mock server is expecting that
+// keyword and will return once it's received.
+
+// The protocol docs are at https://pkg.go.dev/k8s.io/apiserver/pkg/util/wsstream#pkg-constants
+// Bellow we have a copy of the implemented binary protocol specification.
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:114]:
```suggestion
// Below we have a copy of the implemented binary protocol specification.
```

File: lib/kube/proxy/websocket_client_test.go [hunk 7]
```diff
@@ -241,7 +323,111 @@ func (e *wsStreamExecutor) stream(conn *gwebsocket.Conn, options clientremotecom
...
+)
+
+// portforward opens a listener at the specified port and waits for new connections.
+// once a connection is received, it waits for the upstream data and writes it
+// into the original connection.
+// Due to portforward websocket limitations, the listener do not accept
+// concurrent connections.
+func (e *wsStreamClient) portforward(remoteConn *gwebsocket.Conn) (err error) {
+	if e.localPort == nil || e.readyChan == nil {
+		return trace.Errorf("cannot use portforward without proper initialization")
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:340]: I've been told before to avoid trace.Errorf and default to trace.BadParameter instead:

```suggestion
		return trace.BadParameter("cannot use portforward without proper initialization")
```

File: lib/kube/proxy/websocket_client_test.go [hunk 8]
```diff
@@ -241,7 +323,111 @@ func (e *wsStreamExecutor) stream(conn *gwebsocket.Conn, options clientremotecom
...
+		errChan := make(chan error, 3)
+		conn, err := e.listener.Accept()
+		if err != nil {
+			if errors.Is(err, net.ErrClosed) {
+				err = nil
+			}
+			return trace.Wrap(err)
+		}
+
+		wg.Add(2)
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:359]: Suggestion: Move wg, errChan and the body below to a "handlePortForward(conn)" func?

File: lib/kube/proxy/websocket_client_test.go [hunk 9]
```diff
@@ -241,7 +323,111 @@ func (e *wsStreamExecutor) stream(conn *gwebsocket.Conn, options clientremotecom
...
+
+		go func() {
+			defer wg.Done()
+			p := make([]byte, 1024)
+			for {
+				n, err := conn.Read(p)
+				if err != nil {
+					if errors.Is(err, io.EOF) {
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:367]: io.EOF doesn't mean that `n==0`, so shouldn't we look at `n` to decide whether to call WriteMessage below?

File: lib/kube/proxy/websocket_client_test.go [hunk 10]
```diff
@@ -241,7 +323,111 @@ func (e *wsStreamExecutor) stream(conn *gwebsocket.Conn, options clientremotecom
...
+	}
+
+	e.listener, err = net.Listen("tcp", fmt.Sprintf("localhost:%d", *e.localPort))
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	close(e.readyChan)
+	for {
+		wg := sync.WaitGroup{}
+		errChan := make(chan error, 3)
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:350]: Why is the buffer for errChan 3? Please add a comment.

File: lib/kube/proxy/websocket_client_test.go [hunk 11]
```diff
@@ -241,7 +323,111 @@ func (e *wsStreamExecutor) stream(conn *gwebsocket.Conn, options clientremotecom
...
+						err = nil
+					}
+					errChan <- trace.Wrap(err)
+					return
+				}
+				if err := remoteConn.WriteMessage(
+					gwebsocket.BinaryMessage,
+					append([]byte{portforwardDataChan}, p[:n]...),
+				); err != nil {
+					errChan <- trace.Wrap(err)
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:377]: Should we always send something on errChan, so it's simpler to reason about it?

File: lib/kube/proxy/websocket_client_test.go [hunk 12]
```diff
@@ -241,7 +323,111 @@ func (e *wsStreamExecutor) stream(conn *gwebsocket.Conn, options clientremotecom
...
+					case portforwardErrChan:
+						err := trace.Errorf(string(buf[1:]))
+						errChan <- trace.Wrap(err)
+						// Once we receive an error from streamErr, we must stop processing.
+						// The server also stops the execution and closes the connection.
+						return
+					}
+				}
+
+				if err != nil {
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:409]: This looks unusual, can ReadMessage() fail and return a valid `buf` at the same time? Should this error be handled earlier instead?

If it does return both a valid `buf` and an `err`, then let's rename the variable so the error is not accidentally overriden.

File: lib/kube/proxy/websocket_client_test.go [hunk 13]
```diff
@@ -241,7 +323,111 @@ func (e *wsStreamExecutor) stream(conn *gwebsocket.Conn, options clientremotecom
...
+					errChan <- trace.Wrap(err)
+					return
+				}
+			}
+		}()
+
+		wg.Wait()
+		close(errChan)
+		err = <-errChan
+		if err != nil {
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:424]: This assumes that either the first error is non-nil, or all errors are nil. Is that correct? Could we write down the assumption in a comment?

File: lib/kube/proxy/portforward_test.go [hunk 14]
```diff
@@ -0,0 +1,194 @@
...
+		portforwardBuilder func(*testing.T, portForwardRequestConfig) forwardPorts
+	}
+	tests := []struct {
+		name string
+		args args
+	}{
+		{
+			name: "SPDY protocol",
+			args: args{
+				portforwardBuilder: spdyPortForward,
```
Comment (codingllama) [inline lib/kube/proxy/portforward_test.go:86]: Is it viable to test using public methods, or maybe test through using Teleport itself?

File: lib/kube/proxy/portforward_websocket.go [hunk 15]
```diff
@@ -0,0 +1,310 @@
...
+		}()
+	}
+
+	wg.Wait()
+}
+
+// portForward copies the client and upstream streams.
+func (h *websocketPortforwardHandler) portForward(p *websocketChannelPair) {
+	defer p.dataStream.Close()
+	defer p.errorStream.Close()
```
[the remark this answers is not in the document]
Comment (tigrato) [reply lib/kube/proxy/portforward_websocket.go:216]: I placed them there because we use the `errorStream` to send the returned error back to the user.
https://github.com/gravitational/teleport/pull/18791/files/95299546214802e33bd6d1c7b876cfd4482ae0f8#diff-975e7e305dc75c442ad250e946d07435f3fd0bac13e31b1c5a1028781460ccbcR224

File: lib/kube/proxy/portforward_websocket.go [hunk 16]
```diff
@@ -0,0 +1,310 @@
...
+	defer dataStream.Close()
+
+	localError := make(chan struct{})
+	remoteDone := make(chan struct{})
+
+	go func() {
+		// inform the select below that the remote copy is done
+		defer close(remoteDone)
+		// Copy from the remote side to the local port.
+		if _, err := io.Copy(p.dataStream, dataStream); err != nil && !strings.Contains(err.Error(), "use of closed network connection") {
```
[the remark this answers is not in the document]
Comment (tigrato) [reply lib/kube/proxy/portforward_websocket.go:275]: It's the error returned and we do not want to log it. I left it by mistake. It should be `errors.Is(err, net.ErrClosed)` instead.
It happens when the upstream server closes the connection

File: lib/kube/proxy/portforward_test.go (hunk 14 above)
Comment (tigrato) [reply lib/kube/proxy/portforward_test.go:86]: This test already launches an instance of the Teleport Kubernetes Service, configures the user, and makes a request through the API to carry out a port-forward.

File: lib/kube/proxy/portforward_test.go [hunk 17]
```diff
@@ -0,0 +1,194 @@
...
+				readyCh:      readyCh,
+			})
+			require.NoError(t, err)
+			t.Cleanup(fw.Close)
+			go func() {
+				defer close(errCh)
+				errCh <- trace.Wrap(fw.ForwardPorts())
+			}()
+
+			select {
```
[the remark this answers is not in the document]
Comment (tigrato) [reply lib/kube/proxy/portforward_test.go:129]: No need. The `t.Cleanup(func() {require.NoError(t, <-errCh)})` captures the error once  cleaning is triggered

File: lib/kube/proxy/portforward_test.go [hunk 18]
```diff
@@ -0,0 +1,194 @@
...
+			}
+		})
+	}
+}
+
+func portforwardURL(namespace, podName string, host string, query string) *url.URL {
+	path := fmt.Sprintf("/api/v1/namespaces/%s/pods/%s/portforward",
+		namespace, podName)
+	// trim https://
+	hostIP := strings.TrimLeft(host, "htps:/")
```
[the remark this answers is not in the document]
Comment (tigrato) [reply lib/kube/proxy/portforward_test.go:151]: The pattern is correct. From godocs:
```
TrimLeft returns a slice of the string s with all leading Unicode code points contained in cutset removed.

To remove a prefix, use TrimPrefix instead.
```

An example: https://go.dev/play/p/eHPUs0oigSn

Anw, I changed the logic so it won't be confusing

File: lib/kube/proxy/websocket_client_test.go (hunk 11 above)
Comment (tigrato) [reply lib/kube/proxy/websocket_client_test.go:377]: We always send to errChan. Since we are in a loop, only those two conditions can return from it.

File: lib/kube/proxy/websocket_client_test.go [hunk 19]
```diff
@@ -346,85 +347,93 @@ func (e *wsStreamClient) portforward(remoteConn *gwebsocket.Conn) (err error) {
...
+	}
+}
 
-		wg.Add(2)
+// handlePortForwardRequest copies data streams from local connection to upstream and
+// vice versa.
+func (e *wsStreamClient) handlePortForwardRequest(conn net.Conn, remoteConn *gwebsocket.Conn) error {
+	wg := sync.WaitGroup{}
+	// errChan will receive the errors returned from 2 goroutines.
+	// It needs to be buffered because we relly on sync.Waitgroup to control
```
Comment (codingllama) [inline lib/kube/proxy/websocket_client_test.go:368]:
```suggestion
	// It needs to be buffered because we rely on sync.WaitGroup to control
```

File: lib/kube/proxy/portforward_test.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (codingllama) [reply lib/kube/proxy/portforward_test.go:123]: The issue I see here is that the test could be falling into the `case err := <-errCh:`, in which case none of the logic under `<-readyCh` would be running (and it's hard to tell without debugging).

Could we write it in a way that makes it simple to know we are hitting the expected scenarios?

File: lib/kube/proxy/portforward_test.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (codingllama) [reply lib/kube/proxy/portforward_test.go]: Yep, I totally read it as TrimPrefix, thanks for the change.

**Review by codingllama — APPROVED** [review]
LGTM.

I have one open comment that I think is worth addressing (https://github.com/gravitational/teleport/pull/18791#discussion_r1036116997), but apart from that it's only a couple of typos.

**Review by codingllama — APPROVED** [review]

File: lib/kube/proxy/portforward_websocket.go [hunk 20]
```diff
@@ -0,0 +1,339 @@
...
+			requestID: fmt.Sprintf("%d", port),
+			podName:   req.podName,
+		}
+
+		portBytes := make([]byte, 2)
+		binary.LittleEndian.PutUint16(portBytes, port)
+		// Protocol requires sending the port to identify which channels belong to
+		// each port.
+		dataStream.Write(portBytes)
+		errorStream.Write(portBytes)
```
Comment (r0mant) [inline lib/kube/proxy/portforward_websocket.go:132]: Should we check errors here?

File: lib/kube/proxy/portforward_websocket.go [hunk 21]
```diff
@@ -0,0 +1,339 @@
...
+
+	errClose := make(chan struct{})
+	go func() {
+		defer wg.Done()
+		defer close(errClose)
+		_, err := io.Copy(p.errorStream, targetErrorStream)
+		if err != nil && !errors.Is(err, io.EOF) {
+			h.Debugf("Copy stream error: %v.", err)
+		}
+	}()
```
Comment (r0mant) [inline lib/kube/proxy/portforward_websocket.go:271]: Can we use [lib/utils.ProxyConn](https://github.com/gravitational/teleport/blob/master/lib/utils/proxyconn.go#L31) here instead of reimplementing the double-copy-loop logic?

Below too.

**Review by r0mant — APPROVED** [review]

File: lib/kube/proxy/portforward_websocket.go (hunk 21 above)
Comment (tigrato) [reply lib/kube/proxy/portforward_websocket.go]: Nice. Didn't know that
