### PR TITLE
Web: Fix differing duration between unified resource and access request page

### LINKED ISSUE #42562: Connect and Web UI submit access requests with different durations
Steps to reproduce:

1. Set up a user account for resource access requests as described in the web test plan.
2. Make the same access request from Connect and Web UI.

The duration of the request coming from Connect will be almost 12h, while the duration of the request from the Web UI will be 4 minutes.

https://github.com/gravitational/teleport/assets/27113/96ae99d2-d21c-4257-a552-6b0999988a18

### PR DESCRIPTION
**Pull request by kimlisa**
fixes https://github.com/gravitational/teleport/issues/42562

required enterprise changes: https://github.com/gravitational/teleport.e/pull/4379

And refactors some React anti pattern i introduced a while back.

- Extracted all shared states into a hook called `useSpecifiableFields` (please advise me on how to rename it better... ;;)
- Lifted some states up to parent
- Removed redundant states that can be calculated with existing props
- Re dryrun attempt per added/pending resources changes

https://github.com/gravitational/teleport/assets/43280172/f92cf50b-4ae6-4fac-9baa-21f51cefc5ca

### CODE REVIEW

File: web/packages/shared/components/AccessRequests/useSpecifiableFields.ts [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+} from 'shared/components/AccessRequests/NewRequest';
+import { AccessRequest } from 'shared/services/accessRequests';
+
+import {
+  getDurationOptionIndexClosestToOneWeek,
+  getDurationOptionsFromStartTime,
+} from './AccessDuration/durationOptions';
+
+export function useSpecifiableFields() {
+  // Fetched response from `createAccessRequest` with dry run enabled.
```
Comment (gzdunek) [inline web/packages/shared/components/AccessRequests/useSpecifiableFields.ts:16]: Can we convert all these comments to JSDocs?

File: web/packages/shared/components/AccessRequests/useSpecifiableFields.ts
Comment (gzdunek) [inline web/packages/shared/components/AccessRequests/useSpecifiableFields.ts:1]: I'd move this file to `web/packages/shared/components/AccessRequests/NewRequest/useSpecifiableFields.ts`, it's used only for new requests.

I was thinking about a better name, but I didn't have a good idea either.

**Review by gzdunek — COMMENTED** [review]
Nice!

I'm leaving a preemptive approval not to block you.

**Review by gzdunek — APPROVED** [review]

**Review by avatus — APPROVED** [review]
