### PR TITLE
Fix a bug causing the webUI to be unusable if automatic upgrades are misconfigured

### LINKED ISSUE #37060: Unable to login to UI when automatic upgrades is misconfigured
Expected behavior:
I should always be able to log in to the web UI, even if some non-critical feature like automatic upgrades is misconfigured

Current behavior:
I see only local login options (not able to log in with passwordless or SSO):
Screenshot 2024-01-19 at 5 07 56 PM

and errors in the browser console:
```
GET https://nic-test.cloud.gravitational.io/web/config.js net::ERR_ABORTED 500 (Internal Server Error)
login:1 Refused to execute script from 'https://nic-test.cloud.gravitational.io/web/config.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
```

I believe this happens because `getWebConfig` returns early [here](https://github.com/gravitational/teleport/blob/2644ad4e031cfc1792c3e3538e3aa127b57ac1ce/lib/web/apiserver.go#L1608) after encountering an error fetching the target version for automatic upgrades. The upgrade base URL is currently configured as `https://updates.releases.teleport.dev/v1/stable/cloud/v15` which is not set up for v15 yet.

Bug details:
- Teleport version: v15.0.0-alpha.5
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by hugoShaka**
changelog: Fix a bug that was breaking webUI if automatic upgrades are misconfigured.

Fixes #37060 

Also fixes an ineffective sync.OnceValues.

### CODE REVIEW

File: lib/automaticupgrades/channel.go [hunk 1]
```diff
@@ -179,26 +179,28 @@ func (c *Channel) GetCritical(ctx context.Context) (bool, error) {
...
+			ForwardURL: forwardURL,
+		}
+		if err := defaultChannel.CheckAndSetDefaults(); err != nil {
+			return nil, trace.Wrap(err)
+		}
+		return defaultChannel, nil
+	})
+
 // NewDefaultChannel creates a default automatic upgrade channel
 // It looks up the environment variable, and if not found uses the default
```
Comment (zmb3) [inline lib/automaticupgrades/channel.go:198]: What is _the environment variable_?

**Review by zmb3 — APPROVED** [review]

**Review by nklaassen — APPROVED** [review]
