### PR TITLE
Fix OpenSSH EICE nodes connections

### LINKED ISSUE #59922: OpenSSH connections using EICE don't work in 17.7.7
## Expected behavior

Connections to OpenSSH nodes using EICE endpoints should work.

## Current behavior

Reported in Slack: https://goteleport.slack.com/archives/CEZH6UL64/p1759514462452009

Connections using EICE endpoints fail with an error:

```
ERROR: failed connecting to host xxxRedactedxxx: failed to receive cluster details response
        failed to dial target host
        agentless signer is required for OpenSSH Nodes
```

Downgrading the Teleport auth/proxy to 17.7.4 resolved the issue.

I suspect this may be related to https://github.com/gravitational/teleport/pull/58700

Bug details:
- Teleport version: 17.7.7

### PR DESCRIPTION
**Pull request by Joerger**
Changelog: Fix a bug where OpenSSH EICE node connections would fail.

In https://github.com/gravitational/teleport/pull/58700, we mistakenly began to require `AgentlessSigner` to be set for OpenSSH EICE node before [it is actually set](https://github.com/gravitational/teleport/blob/b063fad8d6697ded2c387c5ea8a9f652a3c00156/lib/srv/forward/sshserver.go#L661).

Fixes https://github.com/gravitational/teleport/issues/59922

### CODE REVIEW

File: lib/srv/forward/sshserver.go
Comment (zmb3) [inline lib/srv/forward/sshserver.go:1]: Can we write a test that would have caught this bug?

Comment (Joerger) [reply lib/srv/forward/sshserver.go:1]: I added a basic test for `CheckDefaults`. I'm not sure about adding a more in-depth test (e.g. fully mocked EICE flow in an integration test) given that [the EICE flow is deprecated](https://github.com/gravitational/teleport/pull/51107).

File: lib/reversetunnel/local_cluster.go [hunk 1]
```diff
@@ -411,7 +411,7 @@ func (s *localCluster) dialAndForward(params reversetunnelclient.DialParams) (_
 	ctx := s.srv.ctx
 
 	if params.GetUserAgent == nil && !params.TargetServer.IsOpenSSHNode() {
-		return nil, trace.BadParameter("agentless node require an agent getter")
+		return nil, trace.BadParameter("user agent getter is required for teleport nodes")
```
Comment (espadolini) [inline lib/reversetunnel/local_cluster.go]: Is this always a bug? If so, here and in the other always-bug errors:
```suggestion
		return nil, trace.BadParameter("user agent getter is required for teleport nodes (this is a bug)")
```

File: lib/srv/forward/sshserver.go [hunk 2]
```diff
@@ -268,14 +268,17 @@ func (s *ServerConfig) CheckDefaults() error {
 	if s.TargetServer == nil {
 		return trace.BadParameter("target server is required")
 	}
-	if s.TargetServer.IsOpenSSHNode() {
+	switch s.TargetServer.GetSubKind() {
+	case types.SubKindTeleportNode:
```
Comment (espadolini) [inline lib/srv/forward/sshserver.go:272]: Should we add a "" case too just to be safe? I'm not sure we enforce that the subkind must be "teleport" for regular node heartbeats.

```suggestion
	case types.SubKindTeleportNode, "":
```

**Review by espadolini — APPROVED** [review]

File: lib/srv/forward/sshserver.go (hunk 2 above)
Comment (Joerger) [reply lib/srv/forward/sshserver.go:272]: `SubKind()` defaults to Teleport Node if unset: https://github.com/gravitational/teleport/blob/5e2b4a72a2b85f1f4f36cd7c0cf809d33b69c64a/api/types/server.go#L178-L182

**Review by marcoandredinis — APPROVED** [review]
Just tested this and it works 👍 

Image
