### PR TITLE
Connect: Stop execution of main process on child process spawn error

### LINKED ISSUE #56272: Refactor error handling to stop execution after an error from `MainProcess.create`
## The problem

When there are problems with the tsh executable on Windows, we sometimes get error reports with just bad looking errors. The logs include the actual cause of the problem, which is likely related to some kind of [EDR](https://en.wikipedia.org/wiki/Endpoint_detection_and_response) blocking tsh.exe, but the UI ends up displaying an irrelevant error.

<details open>
<summary>17.5.2</summary>

```
[30-06-25 14:32:00] [Main] info: Starting Teleport Connect version 17.5.2
[30-06-25 14:32:00] [Main] info: Starting tsh daemon from C:\Program Files\Teleport Connect\resources\bin\tsh.exe
[30-06-25 14:32:00] [Main] error: Failed to start main process:  spawn EPERM
[30-06-25 14:32:00] [Main] error: Could not initialize tsh daemon client in the main process TypeError: Cannot read properties of undefined (reading 'then')
    at MainProcess.getTshdClient (C:\Program Files\Teleport Connect\resources\app.asar\build\app\main\index.js:80640:60)
    at C:\Program Files\Teleport Connect\resources\app.asar\build\app\main\index.js:82505:42
    at initializeApp (C:\Program Files\Teleport Connect\resources\app.asar\build\app\main\index.js:82511:5)
```

error
</details>

<details>
<summary>17.4.4</summary>

```
[11-02-25 13:20:43] [Main] info: Starting Teleport Connect version 17.1.6
[11-02-25 13:20:43] [Main] info: Starting tsh daemon from C:\Users\user_abc\AppData\Local\Programs\teleport-connect\resources\bin\tsh.exe
[11-02-25 13:20:44] [Main] error: Failed to start main process:  spawn EPERM
[11-02-25 13:20:45] [Main] error: Could not initialize tsh daemon client in the main process TypeError: Cannot destructure property 'tsh' of '(intermediate value)' as it is undefined.
    at MainProcess.initTshdClient (C:\Users\user_abc\AppData\Local\Programs\teleport-connect\resources\app.asar\build\app\main\index.js:71781:18)
    at async C:\Users\user_abc\AppData\Local\Programs\teleport-connect\resources\app.asar\build\app\main\index.js:74439:24
```

error
</details>

## Triage

Soon after this line is logged:

```
[30-06-25 14:32:00] [Main] error: Failed to start main process:  spawn EPERM
```

the app should quit immediately:

https://github.com/gravitational/teleport/blob/1b2785b41dca4d132b58502230e8290ae7f5c930/web/packages/teleterm/src/mainProcess/mainProcess.ts#L160-L172

However, `app.exit(1)` doesn't seem to cause an immediate exit and the rest of the code is still executed, as we cannot explain otherwise why the next line is logged:

```
[11-02-25 13:20:45] [Main] error: Could not initialize tsh daemon client in the main process TypeError: Cannot destructure property 'tsh' of '(intermediate value)' as it is undefined.
```

https://github.com/gravitational/teleport/blob/1b2785b41dca4d132b58502230e8290ae7f5c930/web/packages/teleterm/src/main.ts#L157-L174

Todo:

- [x] Attempt to reproduce the issue (by e.g., calling a non-existent binary or maybe quarantining the executable somehow). It might be possible to reproduce it only on Windows.
- [x] Move the try/catch from `MainProcess.prototype.init` to around the invocation of `MainProcess.create` in `main.ts`. Catch the error, log it and call `dialog.showErrorBox` like we do in other places.
- [x] See if the error shown in the UI and logs can include more context. `spawn EPERM` doesn't say much on its own, it'd be good to know whether it was tshd or the shared process. We might end up wrapping each `this.init*` call in `MainProcess.prototype.init`.

### PR DESCRIPTION
**Pull request by ravicious**
Closes #56272

This PR makes it so that when tshd or the shared process fails to spawn, we show a dialog box with a relevant error message rather than with "Cannot read properties of undefined (reading 'then')", as shown in #56272. It makes it so that when a user sends a screenshot of the dialog, we can identify the process which caused the problem instead of having to ask the user for logs.

I posted an RCA under the issue (https://github.com/gravitational/teleport/issues/56272#issuecomment-3101904652) if you'd like to learn more about the problem. In short, we thought that Electron's `app.exit(1)` immediately stops the execution of a program, but that is not the case. On top of that, macOS and Windows behave differently when attempting to spawn a child process (this is described below in the Screenshots section), so the original issue could be reproduced only on Windows.

## Screenshots

The screenshots both show the error that is shown after trying to start the dev version of the app with `README.md` as the tsh binary.

```
E_DO_NOT_USE=1 CONNECT_TSH_BIN_PATH=$PWD/README.md pnpm start-term
```

(`E_DO_NOT_USE` is just so that I don't execute this by mistake when going through my shell history)

On Windows, `child_process.spawn` throws a sync error. The error message doesn't indicate which process failed to spawn, but the stacktrace does include this information (`MainProcess.initTshd`).

windows-spawn-error

On macOS, the error isn't thrown immediately on spawn, rather it's emitted with the error event on a process. Thus the title of the dialog is different as the error is surfaced later in the initialization process. On macOS, the error dialog content is unfortunately centered, so the stacktrace looks a bit weird. We're forced to use it though, as according to [the docs of `dialog.showErrorBox`](https://www.electronjs.org/docs/latest/api/dialog#dialogshowerrorboxtitle-content):

> This API can be called safely before the ready event the app module emits, it is usually used to report errors in early stage of startup.

macos-spawn-error

### CODE REVIEW

File: web/packages/teleterm/src/main.ts [hunk 1]
```diff
@@ -87,15 +88,25 @@ async function initializeApp(): Promise<void> {
...
+      logger,
+      configService,
+      appStateFileStorage,
+      configFileStorage,
+      windowsManager,
+    });
+  } catch (error) {
+    const message = 'Could not initialize the main process';
+    logger.error(message, error);
+    dialog.showErrorBox(message, ensureError(error).message);
```
Comment (ravicious) [inline web/packages/teleterm/src/main.ts]: I had a TODO item that said:

> Investigate why the code from this branch actually doesn't show any error dialog box when tsh cannot start. The error is logged and the process remains in the background but no dialog error is shown, indicating that the app is blocked on the code that's supposed to show the dialog.

After starting the app in dev mode, I discovered this error:

```
(node:10220) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 1, conversion failure from
    at Object.showErrorBox (node:electron/js2c/browser_init:2:21451)
    at initializeApp (C:\teleport\web\packages\teleterm\build\app\main\index.js:38975:21)
```

This led to https://github.com/electron/electron/issues/6793 which made me realize that I was passing `error` as the second argument to `dialog.showErrorBox` and it was throwing an error because of that. The second argument is supposed to be a string, but since `error` in this context has type `any`, TS wasn't complaining about this.

It looks like the `ensureError` utility is actually paying off!

File: web/packages/teleterm/src/mainProcess/resolveNetworkAddress.ts [hunk 2]
```diff
@@ -94,11 +94,23 @@ function waitForMatchInStdout(
...
 
+    const rejectOnError = (error: Error) => {
+      const errorToReport = error.message.includes(process.spawnfile)
+        ? error
+        : // Attach spawnfile so that the process can be identified without looking at the stacktrace.
+          // resolveNetworkAddress is the only function that ends up surfacing to the UI the error
+          // event of a process.
+          new Error(`${process.spawnfile}: ${error.message}`, {
+            cause: error,
+          });
```
Comment (ravicious) [inline web/packages/teleterm/src/mainProcess/resolveNetworkAddress.ts:110]: I'm not sure if this is necessary, but I don't think there's any guarantee that the error message of an error from [the error event of a process](https://nodejs.org/docs/latest-v22.x/api/child_process.html#event-error) is going to include the spawnfile.

It certainly happens for EACCESS on macOS as shown in the screenshot, hence why I'm prepending the spawnfile only if the message doesn't already include it. Since it's an async error, the stacktrace itself is not going to include any relevant part like `MainProcess.initTshd`, that's why I'm trying to ensure that the error message itself identifies the process.

macos-spawn-error

File: web/packages/teleterm/src/mainProcess/mainProcess.ts [hunk 3]
```diff
@@ -162,15 +169,10 @@ export default class MainProcess {
...
     this.updateAboutPanelIfNeeded();
     this.setAppMenu();
-    try {
-      this.initTshd();
-      this.initSharedProcess();
-      this.initResolvingChildProcessAddresses();
-      this.initIpc();
-    } catch (err) {
-      this.logger.error('Failed to start main process: ', err.message);
-      app.exit(1);
```
Comment (ravicious) [inline web/packages/teleterm/src/mainProcess/mainProcess.ts:172]: Error handling was moved out of here to `main.ts` so that we can properly stop execution code after catching an error, as `app.exit(1)` does not stop execution immediately (see RCA for more info).

File: web/packages/teleterm/src/mainProcess/mainProcess.ts [hunk 4]
```diff
@@ -191,6 +193,15 @@ export default class MainProcess {
     const { binaryPath, homeDir } = this.settings.tshd;
     this.logger.info(`Starting tsh daemon from ${binaryPath}`);
 
+    // spawn might either fail immediately by throwing an error or cause the error event to be emitted
```
Comment (gzdunek) [inline web/packages/teleterm/src/mainProcess/mainProcess.ts:196]: Theoretically, we could unify this behavior by checking if the process [has `.pid` set](https://nodejs.org/api/child_process.html#subprocesspid).
I tired it and seems to work correctly.

```ts
    this.tshdProcess = spawn(
      binaryPath,
      ['daemon', 'start', ...this.getTshdFlags()],
      {
        stdio: 'pipe', // stdio must be set to `pipe` as the gRPC server address is read from stdout
        windowsHide: true,
        env: {
          ...process.env,
          TELEPORT_HOME: homeDir,
          [TSH_AUTOUPDATE_ENV_VAR]: TSH_AUTOUPDATE_OFF,
        },
      }
    );
    if (!this.tshdProcess.pid) {
      return new Promise((_, reject) => {
        this.tshdProcess.on('error', reject);
      });
    }
```

Comment (ravicious) [reply web/packages/teleterm/src/mainProcess/mainProcess.ts:196]: Hmm, I don't understand why a promise is returned there since `initTshd` is not async. The docs for the pid property says "If the child process fails to spawn due to errors, then the value is undefined and error is emitted." so it looks like this should be built-in?

We could probably add a try/catch around spawn and on error just swallow it and let the error event fire I suppose. But also I'm not sure if it's strictly necessary, the stack trace for sync errors is much better than the one from the error event. Not to mention that funny behavior of Node.js event emitter, where the error event is throw as an error instead if there are no listeners for the error event at the time of emitting it.

Comment (gzdunek) [reply web/packages/teleterm/src/mainProcess/mainProcess.ts:196]: >Hmm, I don't understand why a promise is returned there since initTshd is not async. 

Ah, I forgot to mention that `initTshd` should become async  :)

>The docs for the pid property says "If the child process fails to spawn due to errors, then the value is undefined and error is emitted." so it looks like this should be built-in?

Yeah, it's a bit weird that the error is only available in the `error` event listener instead of being thrown from `spawn`, while `pid: undefined` is set immediately. 

>We could probably add a try/catch around spawn and on error just swallow it and let the error event fire I suppose. But also I'm not sure if it's strictly necessary, the stack trace for sync errors is much better than the one from the error event.

A better stack trace sounds like a good reason to keep it as is.

**Review by gzdunek — APPROVED** [review]

**Review by ryanclark — APPROVED** [review]
