### PR TITLE
Fix GCP VM auto-discovery project ID propagation + default installer

### LINKED ISSUE #31386: GCP discovery can't enroll instances
Given the following discovery config:

```yaml
discovery_service:
  enabled: "yes"
  gcp:
    - types: ["gce"]
      project_ids: ["<redacted>"]
      locations: ["us-central1-a"]
      tags:
        "project": "*"
```

User is seeing the following error in the logs:

```
2023-09-01T21:24:49Z DEBU [DISCOVERY] GCP instances discovered (ProjectID: <REDACTED>, Instances [teleport-discovery-node]), starting installation pid:2919.1 discovery/discovery.go:737
2023-09-01T21:24:49Z DEBU [DISCOVERY] Running Teleport installation on these virtual machines: ProjectID: <REDACTED>, VMs: [teleport-discovery-node] pid:2919.1 discovery/discovery.go:712
2023-09-01T21:24:49Z ERRO [DISCOVERY] Failed to enroll discovered GCP VMs. error:[
ERROR REPORT:
Original Error: *trace.BadParameterError 
Stack Trace:

Caught:
	github.com/gravitational/teleport/lib/cloud/gcp/vm.go:52 github.com/gravitational/teleport/lib/cloud/gcp.convertAPIError
	github.com/gravitational/teleport/lib/cloud/gcp/vm.go:304 github.com/gravitational/teleport/lib/cloud/gcp.(*instancesClient).GetInstance
	github.com/gravitational/teleport/lib/cloud/gcp/vm.go:498 github.com/gravitational/teleport/lib/cloud/gcp.RunCommand
	github.com/gravitational/teleport/lib/srv/server/gcp_installer.go:69 github.com/gravitational/teleport/lib/srv/server.(*GCPInstaller).Run.func1
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 golang.org/x/sync/errgroup.(*Group).Go.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: Invalid resource field value in the request.
```

Seems like this [GetInstance](https://github.com/gravitational/teleport/blob/beeabd6419640c129392a1b51228ef6c9205c796/lib/cloud/gcp/vm.go#L498) call is failing for some reason.

### PR DESCRIPTION
**Pull request by atburke**
This PR fixes multiple bugs in GCP VM auto-discovery:
- Fix project ID not propagating to the GCP client, causing failed API calls. Resolves #31386.
- Fix the default installer not recognizing when it was running on GCP.
- Fix newlines in instance metadata breaking `jq` in default installer.
- Fix zone parsing from instance metadata in default installer.

### CODE REVIEW

File: api/types/installers/installer.sh.tmpl [hunk 1]
```diff
@@ -91,10 +91,10 @@ on_gcp() {
     JOIN_METHOD=iam
     LABELS="teleport.dev/instance-id=${INSTANCE_ID},teleport.dev/account-id=${ACCOUNT_ID}"
   elif on_gcp; then
-    INSTANCE_INFO=$(curl -m5 -sS -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/?recursive=true")
+    INSTANCE_INFO=$(curl -m5 -sS -H "Metadata-Flavor:Google" "http://metadata.google.internal/computeMetadata/v1/instance/?recursive=true")
 
-    NAME="$(echo "$INSTANCE_INFO" | jq -r .name)"
-    ZONE="$(echo "$INSTANCE_INFO" | jq -r .zone | awk -F "/" '{print $9}')"
+    NAME="$(curl -m5 -sS -H "Metadata-Flavor:Google" "http://metadata.google.internal/computeMetadata/v1/instance/name")"
+    ZONE="$(curl -m5 -sS -H "Metadata-Flavor:Google" "http://metadata.google.internal/computeMetadata/v1/instance/zone" | awk '{n=split($0,A,"/"); print A[n]}')"
```
Comment (GavinFrazar) [inline api/types/installers/installer.sh.tmpl:97]: could we add a comment here explaining what the awk code is doing, and why it needs to do it for zone but not name?

**Review by GavinFrazar — APPROVED** [review]

File: api/types/installers/installer.sh.tmpl [hunk 2]
```diff
@@ -15,7 +15,7 @@ on_azure() {
 }
 
 on_gcp() {
-  GCP_STATUS=$(curl -o /dev/null -w "%{http_code}" -m5 -sS -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1")
+  GCP_STATUS=$(curl -o /dev/null -w "%{http_code}" -m5 -sS -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/")
```
Comment (r0mant) [inline api/types/installers/installer.sh.tmpl:18]: Does calling root `/` return a list of all available keys?

File: api/types/installers/installer.sh.tmpl (hunk 1 above)
Comment (r0mant) [inline api/types/installers/installer.sh.tmpl:97]: Here we should:
a) Add a comment that `zone` key returns a zone in the format `projects/PROJECT_NUM/zones/ZONE` so it needs parsing.
b) Instead of `awk` magic, can we just use `$(curl xxxx | basename)` since the format resembles a path?

File: lib/cloud/gcp/vm.go [hunk 3]
```diff
@@ -365,7 +366,11 @@ func addSSHKey(meta *computepb.Metadata, pubKey ssh.PublicKey, expires time.Time
 		meta.Items = append(meta.Items, sshKeyItem)
 	}
 
-	existingKeys := strings.Split(sshKeyItem.GetValue(), "\n")
+	rawKeys := sshKeyItem.GetValue()
+	var existingKeys []string
+	if rawKeys != "" {
+		existingKeys = strings.Split(sshKeyItem.GetValue(), "\n")
```
Comment (r0mant) [inline lib/cloud/gcp/vm.go:372]:
```suggestion
		existingKeys = strings.Split(rawKeys, "\n")
```

File: api/types/installers/installer.sh.tmpl [hunk 4]
```diff
@@ -91,10 +91,10 @@ on_gcp() {
...
     LABELS="teleport.dev/instance-id=${INSTANCE_ID},teleport.dev/account-id=${ACCOUNT_ID}"
   elif on_gcp; then
-    INSTANCE_INFO=$(curl -m5 -sS -H "Metadata-Flavor: Google" "http://metadata.google.internal/computeMetadata/v1/instance/?recursive=true")
-
-    NAME="$(echo "$INSTANCE_INFO" | jq -r .name)"
-    ZONE="$(echo "$INSTANCE_INFO" | jq -r .zone | awk -F "/" '{print $9}')"
+    NAME="$(curl -m5 -sS -H "Metadata-Flavor:Google" "http://metadata.google.internal/computeMetadata/v1/instance/name")"
+    # GCP metadata returns fully qualified zone ("projects/<project-id>/zones/<zone>"), so we need to parse the zone name.
+    FULL_ZONE="$(curl -m5 -sS -H "Metadata-Flavor:Google" "http://metadata.google.internal/computeMetadata/v1/instance/zone")"
+    ZONE="$(basename $FULL_ZONE)"
```
Comment (r0mant) [inline api/types/installers/installer.sh.tmpl:97]: I know I suggested this before, but I hope you tested this and it works.

**Review by r0mant — APPROVED** [review]
