### PR TITLE
Fix kube port-forward to exit on pod removal

### LINKED ISSUE #54814: Kubernetes port-forward does not disconnect on loss of connection
Expected behavior:
Teleport should terminate kubernetes port-forward connections as soon as underlying resource is no longer available or reachable.

Current behavior:
Teleport keeps a kubernetes port-forward connection open well after the underlying resource is no longer available or reachable, such as in case of a pod being recycled or network connection between client and server being interrupted for a prolonged amount of time. 

Bug details:
- Teleport version::

* v17.2.3+ 

- Recreation steps:

1. Start a kubectl port-forward to a specific pod in a Teleport-connected and proxied kube cluster like so: `kubectl port-forward pod/test-web-657b6f6575-5tt99 --v=8 8080:8080 -n test`
2. In a separate terminal/tab, start a continuous curl loop to simulate user/client access like so: `while true; do curl http://localhost:8080; sleep 5; done`
3. Scale the server pod replica down to 0 like so: `k scale deploy test-web -n test --replicas=0`
4. Observe that the port-forward connection appears to remain open even after the server pod is completely terminated. The while loop should also start to report `Empty reply from server` messages (or similar).

If you repeat the same test going directly to the Kube API, you observe the kubectl port-forward connection terminate immediately on the next curl request sent after the server pod is terminated.

- Debug logs:

```
~/tmp/tmp  kubectl port-forward pod/test-web-657b6f6575-tkwtc --v=8 8080:8080 -n test
I0417 15:59:00.295771   97099 loader.go:402] Config loaded from file:  /Users/deusxanima/.kube/config
I0417 15:59:00.295968   97099 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0417 15:59:00.295978   97099 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0417 15:59:00.295981   97099 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0417 15:59:00.295984   97099 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0417 15:59:00.297870   97099 helper.go:105] "Request Body" body=""
I0417 15:59:00.297903   97099 round_trippers.go:470] GET https://4e3009f01ec8d6d93bfbfdcb27e3ed9f.gr7.us-west-1.eks.amazonaws.com/api/v1/namespaces/test/pods/test-web-657b6f6575-tkwtc
I0417 15:59:00.297907   97099 round_trippers.go:476] Request Headers:
I0417 15:59:00.297911   97099 round_trippers.go:480]     Accept: application/json, */*
I0417 15:59:00.297913   97099 round_trippers.go:480]     User-Agent: kubectl/v1.32.3 (darwin/arm64) kubernetes/32cc146
I0417 15:59:00.774067   97099 round_trippers.go:581] Response Status: 200 OK in 476 milliseconds
I0417 15:59:00.774186   97099 round_trippers.go:584] Response Headers:
I0417 15:59:00.774202   97099 round_trippers.go:587]     Audit-Id: 5afc98c9-1561-4451-a8fd-5b45bfb16245
I0417 15:59:00.774242   97099 round_trippers.go:587]     Cache-Control: no-cache, private
I0417 15:59:00.774249   97099 round_trippers.go:587]     Content-Type: application/json
I0417 15:59:00.774254   97099 round_trippers.go:587]     X-Kubernetes-Pf-Flowschema-Uid: 2b35d6e1-1633-4c0a-8394-b6d8de3d5252
I0417 15:59:00.774259   97099 round_trippers.go:587]     X-Kubernetes-Pf-Prioritylevel-Uid: 1c552eab-90fe-47f1-9f96-73daafa49576
I0417 15:59:00.774285   97099 round_trippers.go:587]     Date: Thu, 17 Apr 2025 19:59:00 GMT
I0417 15:59:00.774808   97099 helper.go:105] "Response Body" body="{\"kind\":\"Pod\",\"apiVersion\":\"v1\",\"metadata\":{\"name\":\"test-web-657b6f6575-tkwtc\",\"generateName\":\"test-web-657b6f6575-\",\"namespace\":\"test\",\"uid\":\"0358f762-7605-4971-aee1-ab93ffaa91f4\",\"resourceVersion\":\"47258943\",\"creationTimestamp\":\"2025-04-17T19:58:00Z\",\"labels\":{\"app\":\"test-web\",\"pod-template-hash\":\"657b6f6575\"},\"ownerReferences\":[{\"apiVersion\":\"apps/v1\",\"kind\":\"ReplicaSet\",\"name\":\"test-web-657b6f6575\",\"uid\":\"9bdf6206-dd20-4468-9535-4bf683093985\",\"controller\":true,\"blockOwnerDeletion\":true}],\"managedFields\":[{\"manager\":\"kube-controller-manager\",\"operation\":\"Update\",\"apiVersion\":\"v1\",\"time\":\"2025-04-17T19:58:00Z\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:generateName\":{},\"f:labels\":{\".\":{},\"f:app\":{},\"f:pod-template-hash\":{}},\"f:ownerReferences\":{\".\":{},\"k:{\\\"uid\\\":\\\"9bdf6206-dd20-4468-9535-4bf683093985\\\"}\":{}}},\"f:spec\":{\"f:containers\":{\"k:{\\\"name\\\":\\\"web\\\"}\":{\".\":{},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:name\":{},\"f:ports\":{\".\":{},\"k:{\\\"containerPort\\\":80,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:containe [truncated 3800 chars]"
I0417 15:59:00.782284   97099 type.go:168] "Request Body" body=""
I0417 15:59:00.782390   97099 round_trippers.go:470] GET https://4e3009f01ec8d6d93bfbfdcb27e3ed9f.gr7.us-west-1.eks.amazonaws.com/api/v1/namespaces/test/pods/test-web-657b6f6575-tkwtc
I0417 15:59:00.782404   97099 round_trippers.go:476] Request Headers:
I0417 15:59:00.782415   97099 round_trippers.go:480]     Accept: application/vnd.kubernetes.protobuf,application/json
I0417 15:59:00.782424   97099 round_trippers.go:480]     User-Agent: kubectl/v1.32.3 (darwin/arm64) kubernetes/32cc146
I0417 15:59:00.859480   97099 round_trippers.go:581] Response Status: 200 OK in 77 milliseconds
I0417 15:59:00.859546   97099 round_trippers.go:584] Response Headers:
I0417 15:59:00.859572   97099 round_trippers.go:587]     Date: Thu, 17 Apr 2025 19:59:00 GMT
I0417 15:59:00.859588   97099 round_trippers.go:587]     Audit-Id: 78b85cbb-e5b8-4921-86b4-a4906afb4891
I0417 15:59:00.859600   97099 round_trippers.go:587]     Cache-Control: no-cache, private
I0417 15:59:00.859610   97099 round_trippers.go:587]     Content-Type: application/vnd.kubernetes.protobuf
I0417 15:59:00.859619   97099 round_trippers.go:587]     X-Kubernetes-Pf-Flowschema-Uid: 2b35d6e1-1633-4c0a-8394-b6d8de3d5252
I0417 15:59:00.859631   97099 round_trippers.go:587]     X-Kubernetes-Pf-Prioritylevel-Uid: 1c552eab-90fe-47f1-9f96-73daafa49576
I0417 15:59:00.859641   97099 round_trippers.go:587]     Content-Length: 3009
I0417 15:59:00.861127   97099 type.go:168] "Response Body" body=<
        00000000  6b 38 73 00 0a 09 0a 02  76 31 12 03 50 6f 64 12  |k8s.....v1..Pod.|
        00000010  ab 17 0a de 0d 0a 19 74  65 73 74 2d 77 65 62 2d  |.......test-web-|
        00000020  36 35 37 62 36 66 36 35  37 35 2d 74 6b 77 74 63  |657b6f6575-tkwtc|
        00000030  12 14 74 65 73 74 2d 77  65 62 2d 36 35 37 62 36  |..test-web-657b6|
        00000040  66 36 35 37 35 2d 1a 04  74 65 73 74 22 00 2a 24  |f6575-..test".*$|
        00000050  30 33 35 38 66 37 36 32  2d 37 36 30 35 2d 34 39  |0358f762-7605-49|
        00000060  37 31 2d 61 65 65 31 2d  61 62 39 33 66 66 61 61  |71-aee1-ab93ffaa|
        00000070  39 31 66 34 32 08 34 37  32 35 38 39 34 33 38 00  |91f42.472589438.|
        00000080  42 08 08 c8 ba 85 c0 06  10 00 5a 0f 0a 03 61 70  |B.........Z...ap|
        00000090  70 12 08 74 65 73 74 2d  77 65 62 5a 1f 0a 11 70  |p..test-webZ...p|
        000000a0  6f 64 2d 74 65 6d 70 6c  61 74 65 2d 68 61 73 68  |od-template-hash|
        000000b0  12 0a 36 35 37 62 36 66  36 35 37 35 6a 54 0a 0a  |..657b6f6575jT..|
        000000c0  52 65 70 6c 69 63 61 53  65 74 1a 13 74 65 73 74  |ReplicaSet..tes [truncated 13892 chars]
 >
I0417 15:59:00.862581   97099 tunneling_dialer.go:75] Before WebSocket Upgrade Connection...
I0417 15:59:00.862662   97099 round_trippers.go:470] GET https://4e3009f01ec8d6d93bfbfdcb27e3ed9f.gr7.us-west-1.eks.amazonaws.com/api/v1/namespaces/test/pods/test-web-657b6f6575-tkwtc/portforward
I0417 15:59:00.862682   97099 round_trippers.go:476] Request Headers:
I0417 15:59:00.862721   97099 round_trippers.go:480]     Sec-Websocket-Protocol: SPDY/3.1+portforward.k8s.io
I0417 15:59:00.862748   97099 round_trippers.go:480]     User-Agent: kubectl/v1.32.3 (darwin/arm64) kubernetes/32cc146
I0417 15:59:01.099550   97099 round_trippers.go:581] Response Status: 101 Switching Protocols in 236 milliseconds
I0417 15:59:01.099630   97099 round_trippers.go:584] Response Headers:
I0417 15:59:01.099656   97099 round_trippers.go:587]     Upgrade: websocket
I0417 15:59:01.099672   97099 round_trippers.go:587]     Connection: Upgrade
I0417 15:59:01.099683   97099 round_trippers.go:587]     Sec-Websocket-Accept: Vew2WT/dAGKuXh6FaV2fKLHupGU=
I0417 15:59:01.099697   97099 round_trippers.go:587]     Sec-Websocket-Protocol: SPDY/3.1+portforward.k8s.io
I0417 15:59:01.099719   97099 tunneling_dialer.go:85] negotiated protocol: portforward.k8s.io
Forwarding from 127.0.0.1:8080 -> 8080
I0417 15:59:01.100105   97099 tunneling_connection.go:56] client: tunneling connection read...
I0417 15:59:01.100196   97099 tunneling_connection.go:60] client: tunneling connection read before NextReader()...
Forwarding from [::1]:8080 -> 8080
I0417 15:59:11.101242   97099 tunneling_connection.go:90] client: write: 2 bytes, bytes=80 03
I0417 15:59:11.101738   97099 tunneling_connection.go:106] client: tunneling connection write...complete
I0417 15:59:11.101774   97099 tunneling_connection.go:90] client: write: 2 bytes, bytes=00 06
I0417 15:59:11.101947   97099 tunneling_connection.go:106] client: tunneling connection write...complete
I0417 15:59:11.102002   97099 tunneling_connection.go:90] client: write: 4 bytes, bytes=00 00 00 04
I0417 15:59:11.102092   97099 tunneling_connection.go:106] client: tunneling connection write...complete
I0417 15:59:11.102110   97099 tunneling_connection.go:90] client: write: 4 bytes, bytes=00 00 00 01
I0417 15:59:11.102171   97099 tunneling_connection.go:106] client: tunneling connection write...complete
I0417 15:59:11.175418   97099 tunneling_connection.go:75] client: tunneling connection read in progress message...
I0417 15:59:11.175482   97099 tunneling_connection.go:80] client: read 2 bytes, error=<nil>, bytes=80 03
I0417 15:59:11.175502   97099 tunneling_connection.go:81] client: tunneling connection read...complete
I0417 15:59:11.175511   97099 tunneling_connection.go:56] client: tunneling connection read...
I0417 15:59:11.175517   97099 tunneling_connection.go:75] client: tunneling connection read in progress message...
I0417 15:59:11.175524   97099 tunneling_connection.go:60] client: tunneling connection read before NextReader()...
I0417 15:59:11.175536   97099 tunneling_connection.go:75] client: tunneling connection read in progress message...
I0417 15:59:11.175544   97099 tunneling_connection.go:80] client: read 2 bytes, error=<nil>, bytes=00 06
I0417 15:59:11.175552   97099 tunneling_connection.go:81] client: tunneling connection read...complete
I0417 15:59:11.175561   97099 tunneling_connection.go:56] client: tunneling connection read...
I0417 15:59:11.175567   97099 tunneling_connection.go:75] client: tunneling connection read in progress message...
I0417 15:59:11.175572   97099 tunneling_connection.go:60] client: tunneling connection read before NextReader()...
I0417 15:59:11.175580   97099 tunneling_connection.go:75] client: tunneling connection read in progress message...
I0417 15:59:11.175587   97099 tunneling_connection.go:80] client: read 4 bytes, error=<nil>, bytes=00 00 00 04
I0417 15:59:11.175594   97099 tunneling_connection.go:81] client: tunneling connection read...complete
I0417 15:59:11.175623   97099 tunneling_connection.go:56] client: tunneling connection read...
I0417 15:59:11.175638   97099 tunneling_connection.go:75] client: tunneling connection read in progress message...
I0417 15:59:11.175802   97099 tunneling_connection.go:80] client: read 4 bytes, error=<nil>, bytes=00 00 00 01
I0417 15:59:11.175825   97099 tunneling_connection.go:81] client: tunneling connection read...complete
I0417 15:59:11.175861   97099 tunneling_connection.go:56] client: tunneling connection read...
I0417 15:59:11.175871   97099 tunneling_connection.go:75] client: tunneling connection read in progress message...
I0417 15:59:11.175914   97099 tunneling_connection.go:60] client: tunneling connection read before NextReader()...
```

### PR DESCRIPTION
**Pull request by rana**
Fixes #54814

`kubectl port-forward` now exits when a pod disconnects. 

This addresses `kubectl` user expectations that the Teleport Kubernetes proxy behave transparently, and identical to direct-to-Kubernetes. Previously `kubectl` over Teleport port-forwarding would remain open indefinitely even though no pods were available. That behavior was different from the `kubectl` direct-to-Kubernetes experience.

In this PR:
- Changed error stream copying to uni-directional (target -> source) in SPDY and WebSocket `forwardStreamPair()` functions
- Added `WaitGroup` to SPDY `run()` enabling all port-forward streams to fully complete before returning
- Added an integration test for Kubernetes port-forwarding with pod disconnection
- Updated existing port-forward integration tests to allow and expect `ErrLostConnectionToPod`

## Manual Bug Reproduction

The bug was manually reproduced using `kubectl` direct-to-Kubernetes, and `kubectl` over Teleport.

### Bug Behavior (Teleport) 

Observing the bug with `kubectl` and Teleport.

Here we see the `kubectl port-forward` process *running* after all pods are removed.

```bash
> tsh logout
Credentials expired for proxy "localhost:3080", skipping...
Logged out all users from all proxies.

> k delete all --all
service "kubernetes" deleted
deployment.apps "test-web" deleted
replicaset.apps "test-web-6875846678" deleted

> tsh login --proxy=localhost:3080
Enter password for Teleport user rana.ian:
Enter an OTP code from a device:

> Profile URL:        https://localhost:3080
  Logged in as:       rana.ian
  Cluster:            kube-test-cluster
  Roles:              access, editor, kube-admin
  Kubernetes:         enabled
  Kubernetes groups:  system:masters
  Valid until:        2025-07-22 23:47:05 -0700 PDT [valid for 12h0m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy

> tsh kube login colima
Logged into Kubernetes cluster "colima". Try 'kubectl version' to test the connection.

> kubectl create deployment test-web --image=nginx
deployment.apps/test-web created

> kubectl wait --for=condition=ready pod -l app=test-web
pod/test-web-6875846678-pk8kd condition met

> kubectl port-forward deployment/test-web 8080:80 &
PF_PID=$!
[1] 18578

> Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
kubectl scale deployment test-web --replicas=0
deployment.apps/test-web scaled

> sleep 5

> curl --max-time 2 http://localhost:8080
Handling connection for 8080
curl: (52) Empty reply from server

> ps -p $PF_PID > /dev/null && echo "❌ BUG: kubectl still running"
❌ BUG: kubectl still running

> kill $PF_PID
[1]  + terminated  kubectl port-forward deployment/test-web 8080:80 
```

### Expected Behavior (Direct k8s)

Observing `kubectl` behavior when directly connected to Kubernetes (no Teleport).

Here we see the `kubectl port-forward` process *exits* after all pods are removed.

```bash
> tsh logout
Logged out all users from all proxies.

> k delete all --all
service "kubernetes" deleted
deployment.apps "test-web" deleted

> kubectl config use-context colima
Switched to context "colima".

> kubectl create deployment test-web --image=nginx
deployment.apps/test-web created

> kubectl wait --for=condition=ready pod -l app=test-web
pod/test-web-6875846678-jx8cn condition met

> kubectl port-forward deployment/test-web 8080:80 &
DIRECT_PID=$!
[1] 19650

> Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
kubectl scale deployment test-web --replicas=0
deployment.apps/test-web scaled

> sleep 5

> curl --max-time 2 http://localhost:8080
Handling connection for 8080
E0722 11:59:15.648965   19650 portforward.go:424] "Unhandled Error" err="an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod d085c4246eb130a7fd585cda71cf69d4a90a6156b8cf659bcc0a4adeca7d66f5, uid : network namespace for sandbox \"d085c4246eb130a7fd585cda71cf69d4a90a6156b8cf659bcc0a4adeca7d66f5\" is closed"
curl: (52) Empty reply from server
error: lost connection to pod
[1]  + exit 1     kubectl port-forward deployment/test-web 8080:80    

> ps -p $DIRECT_PID > /dev/null || echo "✓ EXPECTED: kubectl exited"
✓ EXPECTED: kubectl exited
```

### Fix Behavior (Teleport) 

Observing the fix with `kubectl` and Teleport.

Here we see the `kubectl port-forward` process *exits* after all pods are removed.

```bash
> tsh logout
All users logged out.

> kubectl delete deployment test-web
Error from server (NotFound): deployments.apps "test-web" not found

> tsh login --proxy=localhost:3080
Enter password for Teleport user rana.ian:
Enter an OTP code from a device:
> Profile URL:        https://localhost:3080
  Logged in as:       rana.ian
  Cluster:            teleport-laptop
  Roles:              access, editor, kube-admin
  Kubernetes:         enabled
  Kubernetes groups:  system:masters
  Valid until:        2025-07-26 00:30:19 -0700 PDT [valid for 12h0m0s]
  Extensions:         login-ip, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy

> tsh kube login colima
Logged into Kubernetes cluster "colima". Try 'kubectl version' to test the connection.

> kubectl create deployment test-web --image=nginx
deployment.apps/test-web created

> kubectl wait --for=condition=ready pod -l app=test-web
pod/test-web-6875846678-ds94t condition met

> kubectl port-forward deployment/test-web 8080:80 & PF_PID=$!
[1] 34723
> Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80

> kubectl scale deployment test-web --replicas=0
deployment.apps/test-web scaled

> sleep 5

> curl --max-time 2 http://localhost:8080
Handling connection for 8080
E0725 12:32:31.608718   34723 portforward.go:424] "Unhandled Error" err="an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod f3382c71de162fc90a1c696de37bc0a6473813f8e6776e356046b25b5bb8b5b8, uid : network namespace for sandbox \"f3382c71de162fc90a1c696de37bc0a6473813f8e6776e356046b25b5bb8b5b8\" is closed"
curl: (52) Empty reply error: lost connection to pod
from server
[1]  + exit 1     kubectl port-forward deployment/test-web 8080:80

> ps -p $PF_PID > /dev/null && echo "❌ BUG: kubectl still running" || echo "✓ Fixed: kubectl exited"
✓ Fixed: kubectl exited
```

Changelog: Kubernetes Access: `kubectl port-forward` now exits cleanly when backend pods are removed

### CODE REVIEW

File: lib/kube/proxy/portforward_spdy.go [hunk 1]
```diff
@@ -305,6 +305,15 @@ func (h *portForwardProxy) run() {
 		case <-h.sourceConn.CloseChan():
 			h.logger.DebugContext(h.context, "Upgraded connection closed")
 			return
+		case <-h.targetConn.CloseChan():
+			// Backend pod lifecycle completed
+			h.logger.DebugContext(h.context, "Target connection closed")
+			// Close source connection
+			err := h.sourceConn.Close()
+			if err != nil {
```
Comment (rosstimothy) [inline lib/kube/proxy/portforward_spdy.go]: Suggestion: Reduce the scope of variables to the smallest possible scope
```suggestion
			if err := h.sourceConn.Close(); err != nil {
```

File: lib/kube/proxy/portforward_test.go [hunk 2]
```diff
@@ -330,6 +330,41 @@ func TestPortForwardProxy_run_connsClosed(t *testing.T) {
...
 }
 
+func TestPortForwardProxy_run_targetConnClosed(t *testing.T) {
+	t.Parallel()
+
+	sourceConn := newfakeSPDYConnection()
+	targetConn := newfakeSPDYConnection()
+	h := &portForwardProxy{
+		portForwardRequest: portForwardRequest{
+			context:       context.Background(),
```
Comment (rosstimothy) [inline lib/kube/proxy/portforward_test.go]: Suggestion: Prefer t.Context() instead of background or TODO contexts so that resource lifetimes that respect context cancellation are guaranteed to be tied to the life of the test.
```suggestion
			context:       t.Context(),
```

File: lib/kube/proxy/portforward_test.go [hunk 3]
```diff
@@ -330,6 +330,41 @@ func TestPortForwardProxy_run_connsClosed(t *testing.T) {
...
+
+	// Look for the source connection to close
+	require.Eventually(t, func() bool {
+		select {
+		case <-sourceConn.closed:
+			return true
+		default:
+			return false
+		}
+	}, 5*time.Second, time.Millisecond, "expected source connection to close")
```
Comment (rosstimothy) [inline lib/kube/proxy/portforward_test.go]: What do you think about removing the eventually and polling in favor of a simple select with a timeout branch?
```suggestion
	select {
		case <-sourceConn.closed:
		case <-time.After(5*time.Second):
			t.Fatal("expected source connection to close")
	}
```

File: lib/kube/proxy/portforward_test.go [hunk 4]
```diff
@@ -330,6 +330,41 @@ func TestPortForwardProxy_run_connsClosed(t *testing.T) {
...
+		logger:                logtest.NewLogger(),
+		sourceConn:            sourceConn,
+		targetConn:            targetConn,
+		streamChan:            make(chan httpstream.Stream),
+		streamPairs:           map[string]*httpStreamPair{},
+		streamCreationTimeout: 5 * time.Second,
+	}
+
+	// Place `run` in goroutine since it blocks
+	go h.run()
```
Comment (rosstimothy) [inline lib/kube/proxy/portforward_test.go]: How is run terminated? What prevents this goroutine from leaking?

**Comment by creack** [comment]
Looks good so far, but we'll need to update the websocket version as well, right?

File: lib/kube/proxy/portforward_spdy.go (hunk 1 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go]: Yes, makes sense. I committed the suggestion.

File: lib/kube/proxy/portforward_test.go (hunk 2 above)
Comment (rana) [reply lib/kube/proxy/portforward_test.go]: Thank you, suggestion committed.

File: lib/kube/proxy/portforward_test.go (hunk 3 above)
Comment (rana) [reply lib/kube/proxy/portforward_test.go]: Yes, definitely, fewer lines of code. Suggestion committed.

File: lib/kube/proxy/portforward_spdy.go [hunk 5]
```diff
@@ -305,6 +305,14 @@ func (h *portForwardProxy) run() {
 		case <-h.sourceConn.CloseChan():
 			h.logger.DebugContext(h.context, "Upgraded connection closed")
 			return
+		case <-h.targetConn.CloseChan():
```
Comment (tigrato) [inline lib/kube/proxy/portforward_spdy.go:316]: I don't think this change will be enough to fix this problem.  I tested it locally and the target connection is never closed when running proxy-service path - `h.targetConn.CloseChan()` never returns from the kube api call.

From my perspective, the issue comes from the error stream not being correctly closed on the client side (proxy and kube_service) before copying to the upstream to downstream error data.
The error stream is a read only stream and we should close it before copying the upstream to downstream data.
Unfortunately, we used `utils.ProxyConn` which waits for both sides of the connection to terminate, but that doesn't seem to be the case because the server never receives the io.EOF from the client error stream and hangs before closing the connection.

I would also suggest waiting for all port-forward pairs before closing the remote connection, so we ensure we copied all the data.

Can you check if [Instead](https://github.com/gravitational/teleport/blob/a686433a33fa73d25d1b5960f73e133dc6a22a23/lib/kube/proxy/portforward_spdy.go#L200-L205) of 

```go
	wg.Add(1)
	go func() {
		defer wg.Done()
		if err := utils.ProxyConn(h.context, p.errorStream, targetErrorStream); err != nil {
			h.logger.DebugContext(h.context, "Unable to proxy portforward error-stream", "error", err)
		}
	}()
```

The following code works better?

```go
	wg.Add(1)
	// the client never writes to the error stream.
	// thus, we can close the client side stream immediately so the server receives the
	// io.EOF for this stream and closes the connection.
	// Instead of using utils.ProxyConn, we must copy from target to client error streams.
	_ = targetErrorStream.Close()
	go func() {
		defer wg.Done()
		if _, err := io.Copy(p.errorStream, targetErrorStream); err != nil {
			h.logger.DebugContext(h.context, "Unable to proxy portforward error-stream", "error", err)
		}
	}()
```

The SPDY over websocket also uses the SPDY forwarding logic, so this will also apply

You should test the portforwarding with clients that do not support SPDY such as python client or js/typescript clients.

**Review by tigrato — COMMENTED** [review]
Can you also include an integration test for this functionality? 
We run a kind cluster in our CI so this should be trivial to model with a real Kubernetes cluster and native SPDY + SPDY over websocket protocol

File: lib/kube/proxy/portforward_spdy.go (hunk 5 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:316]: Thank you for making the time to review.

After further testing I also found that the original solution isn't effective. Improper manual testing led to some incorrect choices.

I'll test your suggested solution, that would be great if that's a fix.

I'm also working working on a fix which monitors the target error stream. I'll post that soon.

I'll look into integration testing, and non-SPDY clients too.

Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:316]: @tigrato Many thanks for your suggestion!

Manual testing showed your suggestion works well 👍 
```go
if _, err := io.Copy(p.errorStream, targetErrorStream); err != nil {
  h.logger.DebugContext(h.context, "Unable to proxy portforward error-stream", "error", err)
}
```

I added that change to both `lib/kube/proxy/portforward_spdy.go` and `lib/kube/proxy/portforward_websocket.go`.

I've yet to look into integration testing.

Regarding:
> I would also suggest waiting for all port-forward pairs before closing the remote connection, so we ensure we copied all the data.

That makes sense. I also wonder if that's scope creep beyond the focus of the bug fix? Possibly a new issue? Thoughts?

Comment (tigrato) [reply lib/kube/proxy/portforward_spdy.go:316]: @rana I would keep the same check for conn close you had before and still close the stream on client side. kubectl does exactly that to inform the server nothing will ever be received from that stream so I think we should keep it.

> That makes sense. I also wonder if that's scope creep beyond the focus of the bug fix? Possibly a new issue? Thoughts?

that's trivial to implement so I think it should go on this pr. just add a wait group that waits until all `forwardStreamPair` terminate before closing the source conn

File: fixtures/alpine/Dockerfile [hunk 6]
```diff
@@ -2,7 +2,7 @@ FROM scratch
 
 ARG ALPINE_VERSION
 
-ADD alpine-minirootfs-$ALPINE_VERSION-x86_64.tar.gz /
```
Comment (tigrato) [inline fixtures/alpine/Dockerfile]: should we revert this? our runners are x86

File: fixtures/alpine/alpine-minirootfs-3.20.3-aarch64.tar.gz
Comment (tigrato) [inline fixtures/alpine/alpine-minirootfs-3.20.3-aarch64.tar.gz:1]: should we revert?

File: integration/kube_integration_test.go [hunk 7]
```diff
@@ -593,6 +595,196 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+						rsp, err := suite.CoreV1().Pods(testNamespace).Get(context.Background(), testPod, metav1.GetOptions{})
+						if err != nil {
+							return false
+						}
+						return rsp.Status.Phase == v1.PodRunning
+					}, 60*time.Second, time.Millisecond*500)
+				})
+
+				// Forward local port to container port.
+				listener, err := net.Listen("tcp", "localhost:0")
```
Comment (tigrato) [inline integration/kube_integration_test.go:699]: for future reference, I think we don't need this.
We can pass port :0 to the portforward and then parse the first line written to stdout (portforward allows custom stdout io.Writer) 
```
$ kubectl port-forward deployment/test-web 0:80
Forwarding from 127.0.0.1:43123 -> 80
```

File: integration/kube_integration_test.go [hunk 8]
```diff
@@ -593,6 +595,196 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				resp, err := http.Get(fmt.Sprintf("http://localhost:%v", localPort))
+				require.NoError(t, err)
+				require.Equal(t, http.StatusOK, resp.StatusCode)
+				require.NoError(t, resp.Body.Close())
+
+				// Delete the pod.
+				err = suite.CoreV1().Pods(testNamespace).Delete(context.Background(), testPod, metav1.DeleteOptions{})
+				require.NoError(t, err)
+
+				impersonatingForwarder, err := tt.builder(impersonatingProxyClientConfig, kubePortForwardArgs{
```
Comment (tigrato) [inline integration/kube_integration_test.go]: you can discard this section and ensure `forwarderCh` exits after deleting the pod

File: integration/kube_integration_test.go [hunk 9]
```diff
@@ -1955,8 +2149,19 @@ func newPod(ns, name string) *v1.Pod {
 		},
 		Spec: v1.PodSpec{
 			Containers: []v1.Container{{
-				Name:  "nginx",
+				Name:  nginx,
 				Image: localPodImage,
+				ReadinessProbe: &v1.Probe{
```
Comment (tigrato) [inline integration/kube_integration_test.go]: you can discard the readiness probe. our binary is always ready

File: integration/kube_integration_test.go [hunk 10]
```diff
@@ -180,23 +181,24 @@ func (s *KubeSuite) bind(test kubeIntegrationTest) func(t *testing.T) {
...
+	// t.Run("Join", suite.bind(testKubeJoin))
+	// t.Run("JoinWeb", suite.bind(testKubeJoinWeb))
+	// t.Run("IPPinning", suite.bind(testIPPinning))
+	// // ExecWithNoAuth tests that a user can get the pod and exec into it when
+	// // moderated session is not enforced.
+	// // Users under moderated session should only be able to get the pod and shouldn't
+	// // be able to exec into a pod
+	// t.Run("ExecWithNoAuth", suite.bind(testExecNoAuth))
+	// t.Run("EphemeralContainers", suite.bind(testKubeEphemeralContainers))
+	// t.Run("ExecInWeb", suite.bind(testKubeExecWeb))
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]: Let's restore all of these commented out tests.

File: integration/kube_integration_test.go [hunk 11]
```diff
@@ -593,6 +595,196 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
 
 }
 
+// TestKubePortForward tests kubernetes port forwarding
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]:
```suggestion
// testKubePortForwardPodDisconnect tests Kubernetes port forwarding
```

File: integration/kube_integration_test.go [hunk 12]
```diff
@@ -593,6 +595,196 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				// 	if len(pod.Status.ContainerStatuses) == 0 {
+				// 		return false
+				// 	}
+				// 	for _, containerStatus := range pod.Status.ContainerStatuses {
+				// 		if containerStatus.Name == nginx {
+				// 			return containerStatus.Ready
+				// 		}
+				// 	}
+				// 	return false
+				// }, 60*time.Second, time.Millisecond*500)
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]: Remove commented out parts of the test if they aren't needed?

File: integration/kube_integration_test.go [hunk 13]
```diff
@@ -593,6 +595,196 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+						require.True(t, kubeerrors.IsAlreadyExists(err), "Failed to create test pod: %v", err)
+					}
+					// Wait for pod to be running.
+					require.Eventually(t, func() bool {
+						rsp, err := suite.CoreV1().Pods(testNamespace).Get(context.Background(), testPod, metav1.GetOptions{})
+						if err != nil {
+							return false
+						}
+						return rsp.Status.Phase == v1.PodRunning
+					}, 60*time.Second, time.Millisecond*500)
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]: Can this be done as the first step of the test instead of a cleanup operation? Can each test case operate on a unique pod instead of reusing pods to avoid this kind of dependence?

File: integration/kube_integration_test.go [hunk 14]
```diff
@@ -593,6 +595,196 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+
+				// Forward local port to container port.
+				listener, err := net.Listen("tcp", "localhost:0")
+				require.NoError(t, err)
+				t.Cleanup(func() {
+					require.NoError(t, listener.Close())
+				})
+				localPort := listener.Addr().(*net.TCPAddr).Port
+				forwarder, err := tt.builder(proxyClientConfig, kubePortForwardArgs{
+					ports:        []string{fmt.Sprintf("%v:80", localPort)},
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]: Prefer net.JoinHostPort over fmt.Sprintf

File: integration/kube_integration_test.go [hunk 15]
```diff
@@ -593,6 +595,196 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+					podNamespace: testNamespace,
+				})
+				require.NoError(t, err)
+
+				forwarderCh := make(chan error, 1)
+				go func() {
+					err := forwarder.ForwardPorts()
+					forwarderCh <- err
+					if err != nil {
+						t.Logf("Port forwarding error: %v", err)
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]: Calling `t.Log` from a goroutine can result in a panic _if_ called after the test has completed. I suggest avoiding the logging here and instead consuming `forwarderCh` from the main goroutine of the test.

File: integration/kube_integration_test.go [hunk 16]
```diff
@@ -593,6 +595,196 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				localPort := listener.Addr().(*net.TCPAddr).Port
+				forwarder, err := tt.builder(proxyClientConfig, kubePortForwardArgs{
+					ports:        []string{fmt.Sprintf("%v:80", localPort)},
+					podName:      testPod,
+					podNamespace: testNamespace,
+				})
+				require.NoError(t, err)
+
+				forwarderCh := make(chan error, 1)
+				go func() {
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]: How is this goroutine terminated? What prevents it from leaking?

File: integration/kube_integration_test.go (hunk 9 above)
Comment (rosstimothy) [reply integration/kube_integration_test.go]: It's probably worthwhile to restore the pod name constant introduced here to keep this PR scoped to fixing the issue at hand and moving any additional refactoring to a dedicated PR.

File: fixtures/alpine/webserver
Comment (rosstimothy) [inline fixtures/alpine/webserver:1]: Revert as well?

File: fixtures/alpine/Dockerfile (hunk 6 above)
Comment (rana) [reply fixtures/alpine/Dockerfile]: Yes, definitely. This is reveted.

File: integration/kube_integration_test.go (hunk 12 above)
Comment (rana) [reply integration/kube_integration_test.go]: Yes, commented code is removed.

File: integration/kube_integration_test.go (hunk 10 above)
Comment (rana) [reply integration/kube_integration_test.go]: Done. Tests are re-enabled.

File: fixtures/alpine/alpine-minirootfs-3.20.3-aarch64.tar.gz
Comment (rana) [reply fixtures/alpine/alpine-minirootfs-3.20.3-aarch64.tar.gz:1]: Yes, that's reverted now.

File: integration/kube_integration_test.go (hunk 9 above)
Comment (rana) [reply integration/kube_integration_test.go]: ReadinessProbe removed, and original pod naming restored.

File: integration/kube_integration_test.go (hunk 13 above)
Comment (rana) [reply integration/kube_integration_test.go]: Great questions.

> Can this be done as the first step of the test instead of a cleanup operation? 

Not currently (see below). At first run the pod exists, is deleted, then re-created. There are two subtests. So it's an either or scenario.

> Can each test case operate on a unique pod instead of reusing pods to avoid this kind of dependence?

Not currently (would be nice though). 

Currently, there's a singleton pod named `test-pod` used across each kube integration test. Ideally there might be a pod per test, for this new test, port forward disconnect, but not strictly necessary. Essentially we are creating a new pod instance with an identical name. But to your point, it would be nice to have more per-test isolation for slightly cleaner design.

I did try the approach of creating a pod at the beginning of the test with a unique named pod. It worked with local integration testing, but not in CI. Delving a bit deeper, there's `test-pod` RBAC for CI in `fixtures/ci-teleport-rbac/ci-teleport.yaml`. 

CI RBAC might be updated to accommodate the new test with two new constant pod names, or allow random named pods. But the simplest approach is to use the RBAC approved pod name `test-pod`. So for the current working integration test, `test-pod` is used, and the pod is re-created in the `Cleanup()` func. The approach happens to require the fewest changes. 

A future refactor PR adjusting RBAC for random pod name generation for any test might make sense. Just depends on which actions we want to make, and when. Thoughts?

File: integration/kube_integration_test.go (hunk 14 above)
Comment (rana) [reply integration/kube_integration_test.go]: Updated to `net.JoinHostPort(strconv.Itoa(localPort), "80")`

File: integration/kube_integration_test.go (hunk 15 above)
Comment (rana) [reply integration/kube_integration_test.go]: Nice observation! `t.Log` removed.

File: fixtures/alpine/webserver
Comment (rana) [reply fixtures/alpine/webserver:1]: Yes, `webserver` reverted.

File: integration/kube_integration_test.go (hunk 16 above)
Comment (rana) [reply integration/kube_integration_test.go]: Great question. Not obvious how the routine ends. In our test case of pod disconnection, an error is returned from `ForwardPorts()`, and the routine exited. If there were a bug in the code, and `ForwardPorts()` didn't return an error (or we didn't explicitly close it) it would leak into the test process. But in practice it does exit. It also happens to be a code pattern copied over from `testKubePortForward()`.

File: integration/kube_integration_test.go (hunk 8 above)
Comment (rana) [reply integration/kube_integration_test.go]: That section is discarded and `forwarderCh` is now checked.

File: lib/kube/proxy/portforward_websocket.go [hunk 17]
```diff
@@ -266,11 +266,13 @@ func (h *websocketPortforwardHandler) forwardStreamPair(p *websocketChannelPair)
...
 	wg := &sync.WaitGroup{}
-	wg.Add(1)
 
+	wg.Add(1)
 	go func() {
 		defer wg.Done()
-		if err := utils.ProxyConn(h.context, p.errorStream, targetErrorStream); err != nil {
+		// Use a unidirectional copy from Kube API to client.
+		// Enables error propagation from Kube API server to kubectl client.
+		if _, err := io.Copy(p.errorStream, targetErrorStream); err != nil {
```
Comment (creack) [inline lib/kube/proxy/portforward_websocket.go:278]: ~nit: probably should filter out EOF, which would be the expected error.~ scratch that, io.Copy returns nil upon EOF.

File: integration/kube_integration_test.go [hunk 18]
```diff
@@ -593,6 +594,177 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+					t.Fatalf("Timeout waiting for port forwarding after %v", time.Since(start))
+				case err := <-forwarderCh:
+					t.Fatalf("Port forwarding failed immediately: %v", err)
+				case <-forwarder.readyC:
+					t.Logf("Port forwarding ready after %v", time.Since(start))
+				}
+
+				// Validate that port-forwarding is working.
+				t.Log("Checking port forwarding")
+				resp, err := http.Get(fmt.Sprintf("http://localhost:%v", localPort))
```
Comment (creack) [inline integration/kube_integration_test.go]:
```suggestion
				resp, err := http.Get(fmt.Sprintf("http://localhost:%d", localPort))
```

File: integration/kube_integration_test.go [hunk 19]
```diff
@@ -593,6 +594,177 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+
+				// Wait for port-forwarding to be ready.
+				start := time.Now()
+				select {
+				case <-time.After(5 * time.Second):
+					t.Fatalf("Timeout waiting for port forwarding after %v", time.Since(start))
+				case err := <-forwarderCh:
+					t.Fatalf("Port forwarding failed immediately: %v", err)
+				case <-forwarder.readyC:
+					t.Logf("Port forwarding ready after %v", time.Since(start))
```
Comment (creack) [inline integration/kube_integration_test.go]:
```suggestion
					t.Logf("Port forwarding ready after %s", time.Since(start))
```

File: integration/kube_integration_test.go [hunk 20]
```diff
@@ -593,6 +594,177 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				require.NoError(t, err)
+
+				forwarderCh := make(chan error)
+				go func() { forwarderCh <- forwarder.ForwardPorts() }()
+
+				// Wait for port-forwarding to be ready.
+				start := time.Now()
+				select {
+				case <-time.After(5 * time.Second):
+					t.Fatalf("Timeout waiting for port forwarding after %v", time.Since(start))
```
Comment (creack) [inline integration/kube_integration_test.go]:
```suggestion
					t.Fatalf("Timeout waiting for port forwarding after %s", time.Since(start))
```

File: integration/kube_integration_test.go [hunk 21]
```diff
@@ -593,6 +594,177 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				case err := <-forwarderCh:
+					t.Fatalf("Port forwarding failed immediately: %v", err)
```
Comment (creack) [inline integration/kube_integration_test.go]: is it expected to fatal if the error is nil?

File: lib/kube/proxy/portforward_websocket.go (hunk 17 above)
Comment (rana) [reply lib/kube/proxy/portforward_websocket.go:278]: Okay, thanks for the eyes on that though.

File: integration/kube_integration_test.go [hunk 22]
```diff
@@ -593,6 +594,177 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				localPort := listener.Addr().(*net.TCPAddr).Port
+				forwarder, err := tt.builder(proxyClientConfig, kubePortForwardArgs{
+					ports:        []string{net.JoinHostPort(strconv.Itoa(localPort), "80")},
+					podName:      testPod,
+					podNamespace: testNamespace,
+				})
+				require.NoError(t, err)
+
+				forwarderCh := make(chan error)
+				go func() { forwarderCh <- forwarder.ForwardPorts() }()
```
Comment (creack) [inline integration/kube_integration_test.go:715]: if something goes wrong, this may leak. It would be interesting to have add a select so the goroutine terminates as the test ends (success or failure)

File: integration/kube_integration_test.go [hunk 23]
```diff
@@ -593,6 +594,177 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+					}
+
+					// Wait for pod to be running.
+					require.Eventually(t, func() bool {
+						rsp, err := suite.CoreV1().Pods(testNamespace).Get(context.Background(), testPod, metav1.GetOptions{})
+						if err != nil {
+							t.Logf("Get pod error: %v", err)
+							return false
+						}
+						t.Logf("Get pod `%v`: Status:%v", testPod, rsp.Status.Phase)
```
Comment (creack) [inline integration/kube_integration_test.go]:
```suggestion
						t.Logf("Get pod %q: Status: %s", testPod, rsp.Status.Phase)
```

File: integration/kube_integration_test.go [hunk 24]
```diff
@@ -593,6 +594,177 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+
+	for _, tt := range tests {
+		t.Run(tt.name,
+			func(t *testing.T) {
+				t.Cleanup(func() {
+					// Test pod would have been deleted if test is successful.
+					// Setup next test with test pod as needed.
+					pod := newPod(testNamespace, testPod)
+					if _, err := suite.CoreV1().Pods(testNamespace).Create(context.Background(), pod, metav1.CreateOptions{}); err != nil {
+						require.True(t, kubeerrors.IsAlreadyExists(err), "Failed to create test pod: %v", err)
```
Comment (creack) [inline integration/kube_integration_test.go]:
```suggestion
						require.True(t, kubeerrors.IsAlreadyExists(err), "Failed to create test pod: %s.", err)
```

File: integration/kube_integration_test.go [hunk 25]
```diff
@@ -593,6 +594,177 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name,
+			func(t *testing.T) {
+				t.Cleanup(func() {
+					// Test pod would have been deleted if test is successful.
+					// Setup next test with test pod as needed.
+					pod := newPod(testNamespace, testPod)
+					if _, err := suite.CoreV1().Pods(testNamespace).Create(context.Background(), pod, metav1.CreateOptions{}); err != nil {
```
Comment (creack) [inline integration/kube_integration_test.go:680]: I may be missing something, but isn't this going to always leak a pod a the end of the test?

Maybe would be better to create the pod before running / delete after the test instead of having a create in the cleanup?

File: integration/kube_integration_test.go (hunk 21 above)
Comment (rana) [reply integration/kube_integration_test.go]: Good point, `nil` error wouldn't be fatal. I added the nil check.

File: integration/kube_integration_test.go (hunk 22 above)
Comment (rana) [reply integration/kube_integration_test.go:715]: Good point.

`select` and `cancel()` would work there.

After looking at several of the kube integration tests (`testKubePortForward`, `testKubeTrustedClustersClientCert`, `testKubeTrustedClustersSNI`), a common pattern of `close(forwarder.stopC)` is used to operate with the k8s client SDK package. So I added a cleanup closure:
```go
t.Cleanup(func() { close(forwarder.stopC) })
```
`close(forwarder.stopC)` ensures is `ForwardPorts()` is called, and the goroutine exits. Though it's not as directly obvious as `select/cancel`, it appears to be a preferred patten in the tests.

File: integration/kube_integration_test.go (hunk 16 above)
Comment (rana) [reply integration/kube_integration_test.go]: I added a cleanup closure:
```go
t.Cleanup(func() { close(forwarder.stopC) })
```
`close(forwarder.stopC)` ensures is `ForwardPorts()` is called, though it's not as directly obvious as `select/cancel`, it appears to be a preferred patten in the tests. Looking at several of the kube integration tests (`testKubePortForward`, `testKubeTrustedClustersClientCert`, `testKubeTrustedClustersSNI`), a common pattern of `close(forwarder.stopC)` is used to operate with the k8s client SDK package.

File: integration/kube_integration_test.go (hunk 25 above)
Comment (rana) [reply integration/kube_integration_test.go:680]: It's actually maintaining a single `test-pod` instance used in multiple kube integration tests. This particular test happens to be deleting pods. So it's restoring state prior to the test. So, it's actually not going to leak a pod. 

Creating a pod per test was initially attempted until I found that CI RBAC modification would be required. I'd like to limit the scope of changes to so as not to modify CI RBAC yet.

It would be cleaner, easier-to-reason with a per pod per test approach, and worth re-visiting in the not too distance future.

Code comments were added to more clearly explain the design decision.

File: lib/kube/proxy/portforward_test.go [hunk 26]
```diff
@@ -556,7 +557,14 @@ func TestPortForwardUnderlyingProtocol(t *testing.T) {
 			readyCh := make(chan struct{})
 			// errCh receives a single error from ForwardPorts goroutine.
 			errCh := make(chan error)
-			t.Cleanup(func() { require.NoError(t, <-errCh) })
+			t.Cleanup(func() {
+				err := <-errCh
+				// ErrLostConnectionToPod is an expected error.
+				// Server allowed to communicate error to client.
+				if !errors.Is(err, portforward.ErrLostConnectionToPod) {
+					require.NoError(t, <-errCh)
```
Comment (creack) [inline lib/kube/proxy/portforward_test.go]: is it expected to read twice from the errCh?

File: lib/kube/proxy/portforward_test.go [hunk 27]
```diff
@@ -556,7 +557,14 @@ func TestPortForwardUnderlyingProtocol(t *testing.T) {
 			readyCh := make(chan struct{})
 			// errCh receives a single error from ForwardPorts goroutine.
 			errCh := make(chan error)
-			t.Cleanup(func() { require.NoError(t, <-errCh) })
+			t.Cleanup(func() {
+				err := <-errCh
```
Comment (creack) [inline lib/kube/proxy/portforward_test.go]: This may block the whole test suite. Are you sure it won't be an issue and errCh will always be readable?

File: lib/kube/proxy/portforward_test.go (hunk 26 above)
Comment (rana) [reply lib/kube/proxy/portforward_test.go]: That's not expected. I just corrected that. Reading from the channel can be done once.
```go
require.NoError(t, err)
```

File: lib/kube/proxy/portforward_test.go (hunk 27 above)
Comment (rana) [reply lib/kube/proxy/portforward_test.go]: The test was meant to read from the channel once. I just updated that. But it happened not to be an issue, with the test passing in CI and locally before the change.

The updated code:
```go
t.Cleanup(func() {
	  err := <-errCh
	  // ErrLostConnectionToPod is an expected error.
	  // Server allowed to communicate error to client.
	  if !errors.Is(err, portforward.ErrLostConnectionToPod) {
	  	  require.NoError(t, err)
	  }
})
```

File: lib/kube/proxy/portforward_spdy.go (hunk 5 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:316]: Hi @tigrato, Here's a [draft branch and PR](https://github.com/gravitational/teleport/pull/57329) which implements a wait group in `(h *portForwardProxy) run()`. 

Is that what you had in mind? when you mentioned:
> I would also suggest waiting for all port-forward pairs before closing the remote connection, so we ensure we copied all the data.

> that's trivial to implement so I think it should go on this pr. just add a wait group that waits until all forwardStreamPair terminate before closing the source conn

Comment (tigrato) [reply lib/kube/proxy/portforward_spdy.go:316]: @rana yes, that does the job but you need to wait when the remote connection ends and before closing the source connection

File: integration/kube_integration_test.go (hunk 16 above)
Comment (rana) [reply integration/kube_integration_test.go]: Goroutine leak protection was extended with context timeout and a cleanup cancel call in this test and other existing tests.
```go
ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
done := make(chan struct{})
forwarderCh := make(chan error, 1)
go func() {
	defer close(done)
	select {
	case forwarderCh <- forwarder.ForwardPorts():
	case <-ctx.Done():
		forwarderCh <- ctx.Err()
	}
}()
t.Cleanup(func() {
	close(forwarder.stopC)
	cancel()
	<-done
})
```

File: lib/kube/proxy/portforward_spdy.go (hunk 5 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:316]: Hi @tigrato  `Wait()` was added, and the draft branch changes are moved into the current branch.
```go
case <-h.targetConn.CloseChan():
  // Backend pod lifecycle completed
  h.logger.DebugContext(h.context, "Target connection closed")
  // Wait for all other pairs to complete
  // to ensure data transfer completes fully.
  wg.Wait()
  // Close source connection
  if err := h.sourceConn.Close(); err != nil {
    h.logger.ErrorContext(h.context, "Unable to close source connection", "error", err)
  }
  return
```

On a separate item you mentioned:
> You should test the portforwarding with clients that do not support SPDY such as python client or js/typescript clients.

Are you thinking of seeing manual test output for a python client or js/typescript clients?

File: integration/kube_integration_test.go (hunk 22 above)
Comment (rana) [reply integration/kube_integration_test.go:715]: Goroutine leak protection was extended with context timeout and a cleanup cancel call in this test and other existing tests.
```go
ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
done := make(chan struct{})
forwarderCh := make(chan error, 1)
go func() {
	defer close(done)
	select {
	case forwarderCh <- forwarder.ForwardPorts():
	case <-ctx.Done():
		forwarderCh <- ctx.Err()
	}
}()
t.Cleanup(func() {
	close(forwarder.stopC)
	cancel()
	<-done
})
```

**Comment by rana** [comment]
> Looks good so far, but we'll need to update the websocket version as well, right?

@creack Here's a summary of the additions to `lib/kube/proxy/portforward_spdy.go` and  `lib/kube/proxy/portforward_websocket.go` with eye towards what can be symmetric.
* `run()` function in SPDY & Websocket
  - `<-h.targetConn.CloseChan():` only in SPDY. Originally I think you were asking about  the SPDY `(h *portForwardProxy) run()` [ case <-h.targetConn.CloseChan():](https://github.com/gravitational/teleport/blob/205b0b2a0b65fe268f729f758adb53cee6f7bd9b/lib/kube/proxy/portforward_spdy.go#L313) also being added to the websocket version. I looked at adding a similar case to websocket, but it wasn't added. Looking at the [websocket run() function](https://github.com/gravitational/teleport/blob/205b0b2a0b65fe268f729f758adb53cee6f7bd9b/lib/kube/proxy/portforward_websocket.go#L223-L236), the websocket version is setup a bit differently without select and cases.
  - [WaitGroup](https://github.com/gravitational/teleport/blob/205b0b2a0b65fe268f729f758adb53cee6f7bd9b/lib/kube/proxy/portforward_spdy.go#L303-L304) was added to SPDY to to allow all transfers to complete before closing a source connection. Similar [WaitGroup logic](https://github.com/gravitational/teleport/blob/205b0b2a0b65fe268f729f758adb53cee6f7bd9b/lib/kube/proxy/portforward_websocket.go#L224-L225) was already in websocket. 
* `forwardStreamPair()` function in SPDY & Websocket
  - `io.Copy(p.errorStream, targetErrorStream)` was added to both [SPDY](https://github.com/gravitational/teleport/blob/205b0b2a0b65fe268f729f758adb53cee6f7bd9b/lib/kube/proxy/portforward_spdy.go#L205) and [websocket](https://github.com/gravitational/teleport/blob/205b0b2a0b65fe268f729f758adb53cee6f7bd9b/lib/kube/proxy/portforward_websocket.go#L275).

File: integration/kube_integration_test.go [hunk 28]
```diff
@@ -558,15 +559,28 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+					select {
+					case forwarderCh <- forwarder.ForwardPorts():
+					case <-ctx.Done():
+						forwarderCh <- ctx.Err()
+					}
+				}()
+				t.Cleanup(func() {
+					cancel()
+					<-done
+				})
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]: I think this could be simplified by using [testing.T.Context()](https://pkg.go.dev/testing#T.Context).
```suggestion
				// Forward local port to container port.
				forwarderCh := make(chan error, 1)
				go func() {
					defer close(done)
					select {
					case forwarderCh <- forwarder.ForwardPorts():
					case <-t.Context().Done():
						forwarderCh <- ctx.Err()
					}
				}()
```

Though I think we could achieve the same behavior by explicitly closing the forwarder during cleanup.

```suggestion
				// Forward local port to container port.
				t.Cleanup(func() { forwarder.Close() })
				go func() { forwarderCh <- forwarder.ForwardPorts() }()
	
```

File: integration/kube_integration_test.go [hunk 29]
```diff
@@ -558,15 +559,16 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
 				})
 				require.NoError(t, err)
 
+				// Forward local port to container port.
 				forwarderCh := make(chan error)
+				t.Cleanup(func() { forwarder.Close() })
 				go func() { forwarderCh <- forwarder.ForwardPorts() }()
```
Comment (creack) [inline integration/kube_integration_test.go:563]: Why remove the timeout?

File: integration/kube_integration_test.go [hunk 30]
```diff
@@ -593,6 +595,192 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+					pod := newPod(testNamespace, testPod)
+					if _, err := suite.CoreV1().Pods(testNamespace).Create(context.Background(), pod, metav1.CreateOptions{}); err != nil {
+						require.True(t, kubeerrors.IsAlreadyExists(err), "Failed to create test pod: %s.", err)
+					}
+
+					// Wait for pod to be running.
+					require.Eventually(t, func() bool {
+						rsp, err := suite.CoreV1().Pods(testNamespace).Get(context.Background(), testPod, metav1.GetOptions{})
+						if err != nil {
+							t.Logf("Get pod error: %v", err)
```
Comment (creack) [inline integration/kube_integration_test.go]:
```suggestion
							t.Logf("Get pod error: %s", err)
```

File: integration/kube_integration_test.go [hunk 31]
```diff
@@ -593,6 +595,192 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+							return false
+						}
+						t.Logf("Get pod %q: Status: %s", testPod, rsp.Status.Phase)
+						if rsp.Status.Phase == v1.PodRunning {
+							t.Logf("Pod `%v` is running", testPod)
```
Comment (creack) [inline integration/kube_integration_test.go]:
```suggestion
							t.Logf("Pod %q is running", testPod)
```

File: integration/kube_integration_test.go (hunk 22 above)
Comment (creack) [reply integration/kube_integration_test.go:715]: 60sec seems way too much, can we make it 1 or 2sec?

File: integration/kube_integration_test.go [hunk 32]
```diff
@@ -593,6 +595,192 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				localPort := listener.Addr().(*net.TCPAddr).Port
+				forwarder, err := tt.builder(proxyClientConfig, kubePortForwardArgs{
+					ports:        []string{net.JoinHostPort(strconv.Itoa(localPort), "80")},
+					podName:      testPod,
+					podNamespace: testNamespace,
+				})
+				require.NoError(t, err)
+
+				// Forward local port to container port.
+				forwarderCh := make(chan error)
```
Comment (creack) [inline integration/kube_integration_test.go]:
```suggestion
				forwarderCh := make(chan error, 1)
```

File: integration/kube_integration_test.go [hunk 33]
```diff
@@ -593,6 +595,192 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+
+				// Attempt an http GET after pod deletion.
+				// This enables error reporting from KubeAPI back to client.
+				t.Log("Checking for port-forward disconnection")
+				//nolint:bodyclose // http response is expected to be nil and return an error
+				_, err = http.Get(fmt.Sprintf("http://localhost:%d", localPort))
+				require.Error(t, err)
+
+				// Wait for port-forwarding to exit.
+				start = time.Now()
```
Comment (creack) [inline integration/kube_integration_test.go]: Seems superfluous, I'd recommend to remvoe this and just Fatal with "timed out", or if you want, "timed out after 5 seconds" as it is hard-coded.

File: lib/kube/proxy/portforward_test.go [hunk 34]
```diff
@@ -139,7 +140,14 @@ func TestPortForwardKubeService(t *testing.T) {
...
```
Comment (creack) [inline lib/kube/proxy/portforward_test.go]:
```suggestion
				// ErrLostConnectionToPod is an expected error.
				// Server allowed to communicate error to client.
				if err := <-errCh; !errors.Is(err, portforward.ErrLostConnectionToPod) {
```

File: lib/kube/proxy/portforward_test.go [hunk 35]
```diff
@@ -330,6 +338,39 @@ func TestPortForwardProxy_run_connsClosed(t *testing.T) {
...
 }
 
+func TestPortForwardProxy_run_targetConnClosed(t *testing.T) {
+	t.Parallel()
+
+	sourceConn := newfakeSPDYConnection()
+	targetConn := newfakeSPDYConnection()
+	h := &portForwardProxy{
+		portForwardRequest: portForwardRequest{
+			context:       t.Context(),
```
Comment (creack) [inline lib/kube/proxy/portforward_test.go]: this may cause issue when backporting.

File: lib/kube/proxy/portforward_test.go [hunk 36]
```diff
@@ -523,7 +564,14 @@ func TestPortForwardUnderlyingProtocol(t *testing.T) {
 			readyCh := make(chan struct{})
 			// errCh receives a single error from ForwardPorts goroutine.
 			errCh := make(chan error)
-			t.Cleanup(func() { require.NoError(t, <-errCh) })
+			t.Cleanup(func() {
+				err := <-errCh
```
Comment (creack) [inline lib/kube/proxy/portforward_test.go]: nit: smallest scope, would be better in the if block.

File: integration/kube_integration_test.go (hunk 29 above)
Comment (rana) [reply integration/kube_integration_test.go:563]: Tim suggested suggested changing to the two-line form:
```go
t.Cleanup(func() { forwarder.Close() })
go func() { forwarderCh <- forwarder.ForwardPorts() }()
```
The two lines are effective and more readable. Tests passing with the change. So, I just revised four tests back to using those two lines.

There's definitely a few valid approaches.

Do you greatly prefer including the timeout?

File: lib/kube/proxy/portforward_test.go (hunk 35 above)
Comment (rosstimothy) [reply lib/kube/proxy/portforward_test.go]: I think it's fine to use this on master and v18 and adjust to an alternate context on other branches.

File: integration/kube_integration_test.go (hunk 28 above)
Comment (rana) [reply integration/kube_integration_test.go]: Yeah, that two line change is effective and easier to read.
```go
t.Cleanup(func() { forwarder.Close() })
go func() { forwarderCh <- forwarder.ForwardPorts() }()
```
Testing locally shows it passes as expected. There's definitely a few ways to go about it. The two lines is quite readable.

I went ahead an updated related test cases with that pattern, tested, and committed the changes.

File: lib/kube/proxy/portforward_test.go (hunk 36 above)
Comment (rana) [reply lib/kube/proxy/portforward_test.go]: Yeah, good point. I updated with moving `err` into the if clause.

File: lib/kube/proxy/portforward_test.go (hunk 35 above)
Comment (rana) [reply lib/kube/proxy/portforward_test.go]: I noticed a similar mock test `TestPortForwardProxy_run_connsClosed` using `context.Background()`. So, I switched it to use `context.Background()`.  Hopefully that will be smooth for backporting.

File: integration/kube_integration_test.go (hunk 33 above)
Comment (rana) [reply integration/kube_integration_test.go]: Good point, `start = time.Now()` is now removed.

File: integration/kube_integration_test.go (hunk 22 above)
Comment (rana) [reply integration/kube_integration_test.go:715]: 60sec is quite long. Was thinking of CI. 60sec probably isn't needed for each test. Maybe 15-30 seconds? Though a test with pod deletion might need some lengthy waiting. It might depend on a reasonable time span in CI.

But with that said, based on some feedback from Tim, I removed the timeout and changed it to:
```go
t.Cleanup(func() { forwarder.Close() })
go func() { forwarderCh <- forwarder.ForwardPorts() }()
```
It's effective and also readable. I also mention the change in another thread.

File: lib/kube/proxy/portforward_spdy.go (hunk 5 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:316]: Hi @tigrato I came up with a Python script to manually test a Python client with only WebSocket port-forwarding. The WebSocket behavior is identical to the SPDY behavior, showing the expected port-forward disconnect after pod removal. That's the same behavior we see using `kubectl` and a SPDY Go integration test.

The Python client test uses only WebSockets (no-SPDY) with a Python module [portforward](https://pypi.org/project/portforward/).

Here's a manual test run of the custom script from my laptop showing a WebSocket test passing.
```zsh
--- Setting up test deployment 'test-web-py' ---
✓ Deployment created.
Waiting for pod to become ready...
✓ Pod 'test-web-py-6d65b99566-22pll' is ready.
--- Running Test Scenario for: python-client ---
  Starting port-forward via portforward library (WebSocket)...
✓ Port-forward active via portforward library: localhost:8080 -> pod:8080
  Testing HTTP GET to localhost:8080 (expecting success)...
  ✓ Correctly got success.

Scaling deployment to 0 replicas to terminate pod...
✓ Deployment scaled.
  Waiting for connection to drop...
  Testing HTTP GET to localhost:8080 (expecting failure)...
[2025-07-31T23:46:31Z ERROR portforward::portforward] failed to forward connection: failed to upgrade to a WebSocket connection: failed to switch protocol: 404 Not Found
  ✓ Correctly got failure.
  Python client thread stopped.
✓ SUCCESS: Port-forward for 'python-client' correctly terminated after pod deletion.

--- Cleaning up deployment 'test-web-py' ---
✓ Deployment deleted.

========================================
           TEST SUMMARY
========================================
  portforward library (WebSocket) ✅ PASSED
========================================
```

This case covers Kubernetes >= v1.31, which switched to WebSocket only approach.

Also, as you may know, `TestPortForwardKubeService` has a [Websocket protocol test case](https://github.com/gravitational/teleport/blob/f578fdf058648893d0c7c45c68c96594879bcbc4/lib/kube/proxy/portforward_test.go#L77).

Maybe we can consider automating multi-language client testing in a future iteration as well?

Questions? Comments? 😃

File: integration/kube_integration_test.go (hunk 29 above)
Comment (rosstimothy) [reply integration/kube_integration_test.go:563]: What if we stop writing the result to a channel and use assert instead of require to validate the error directly in the goroutine?

File: integration/kube_integration_test.go [hunk 37]
```diff
@@ -593,6 +595,191 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+
+				// Wait for port-forwarding to be ready.
+				start := time.Now()
+				select {
+				case <-time.After(5 * time.Second):
+					t.Fatalf("Timeout waiting for port forwarding after %s", time.Since(start))
+				case err := <-forwarderCh:
+					if err != nil {
+						t.Fatalf("Port forwarding failed immediately: %s", err)
+					}
```
Comment (rosstimothy) [inline integration/kube_integration_test.go]:
```suggestion
					require.NoError(t, err)
```

File: lib/kube/proxy/portforward_spdy.go (hunk 5 above)
Comment (rosstimothy) [reply lib/kube/proxy/portforward_spdy.go:316]: I don't think Tiago was proposing we add automated test that used python or javascript. I believe Tiago was suggesting that you should manually test this change with the clients directly to make sure the fix works for clients that behave slightly differently than kubectl does.

@rana it might be helpful if you could include the script you used in addition to the output it generated.

File: lib/kube/proxy/portforward_websocket.go [hunk 38]
```diff
@@ -266,11 +266,13 @@ func (h *websocketPortforwardHandler) forwardStreamPair(p *websocketChannelPair)
...
 
 	wg := &sync.WaitGroup{}
-	wg.Add(1)
 
+	wg.Add(1)
 	go func() {
 		defer wg.Done()
-		if err := utils.ProxyConn(h.context, p.errorStream, targetErrorStream); err != nil {
+		// Use a unidirectional copy from Kube API to client.
+		// Enables error propagation from Kube API server to kubectl client.
```
Comment (tigrato) [inline lib/kube/proxy/portforward_websocket.go:277]:
```suggestion
		_ = targetErrorStream.Close()
		// Enables error propagation from Kube API server to kubectl client.
```

File: lib/kube/proxy/portforward_spdy.go [hunk 39]
```diff
@@ -199,7 +200,9 @@ func (h *portForwardProxy) forwardStreamPair(p *httpStreamPair, remotePort int64
 	wg.Add(1)
 	go func() {
 		defer wg.Done()
-		if err := utils.ProxyConn(h.context, p.errorStream, targetErrorStream); err != nil {
+		// Use a unidirectional copy from Kube API to client.
+		// Enables error propagation from Kube API server to kubectl client.
```
Comment (tigrato) [inline lib/kube/proxy/portforward_spdy.go:207]:
```suggestion
		_ = targetErrorStream.Close()
		// Enables error propagation from Kube API server to kubectl client.
```

I would keep the _ = targetErrorStream.Close() just like kubectl does to ensure the same behavior

File: lib/kube/proxy/portforward_spdy.go (hunk 5 above)
Comment (tigrato) [reply lib/kube/proxy/portforward_spdy.go:316]: I mean testing a python client. 
From what I remember when I wrote `websocketPortForwardClientBuilder`, you can actually add a test using that client to mimic the old websocket client

File: integration/kube_integration_test.go (hunk 29 above)
Comment (rana) [reply integration/kube_integration_test.go:563]: That also works for the `testKubePortForward` test. Local test passes with that change. I think leaving it as-is would be fine though.

We might consider refactoring kube integration tests at some point? Possibly in connection to CI RBAC.

File: lib/kube/proxy/portforward_spdy.go (hunk 5 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:316]: @tigrato, @rosstimothy  Sounds good. I believe we have the Python WebSocket client covered then. A WebSocket only test path is exercised on my machine with a Python client script (see below) and Colima + k3s v1.33.2+k3s1.

The test exercises:
- WebSocket only port forwarding (no SPDY)
- Also `kubectl port-forward` which is essentially the manual test. `kubectl` uses SPDY when connecting to k8s v1.30 and earlier.

### Setup instructions
- Build teleport, tsh, tctl
- Run teleport
- Login with tsh
- Install `uv` package manager
- Run Python client test script

An example shell session.
```zsh
> pwd
~/dev/teleport
> make build/teleport build/tctl build/tsh

# New terminal
> teleport start

# New terminal
> tsh login --proxy=localhost:3080

# Install uv, a python package manager
> brew install uv

# Save the python script (below) to a file
# File name can be portforward_test.py

# Set file permissions
> chmod +x portforward_test.py

# Run the python script
> uv run portforward_test.py
```

The Python client is relying on the selection and use of the `portforward` module for the websocket logic. The function `_port_forward_python_client` does the websocket port forwarding.

Here's the Python test script `portforward_test.py`:
```python
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "kubernetes",
#   "requests",
#   "portforward",
# ]
# ///
"""
Test Kubernetes port-forward disconnection behavior through Teleport proxy.

This script validates two scenarios:
1. `kubectl`: Uses SPDY-over-WebSocket, testing the `portforward_spdy.go` path.
2. `python-client`: Uses pure WebSocket, testing the `portforward_websocket.go` path.

It ensures that for both protocols, the connection is terminated promptly
when the target pod is deleted.
"""
import time
import threading
import socket
import subprocess
import sys
import requests
from contextlib import contextmanager

from kubernetes import client, config
from kubernetes.stream import portforward
from kubernetes.client.exceptions import ApiException


class PortForwardDisconnectionTest:
    def __init__(self, namespace="default"):
        self.namespace = namespace
        self.deployment_name = "test-web-py"
        self.local_port = 8080
        # The pod will be configured to listen on the same port to avoid mapping issues.
        self.pod_port = self.local_port
        self.pod_name = None

        # Find an available local port
        if self._is_port_in_use(self.local_port):
            print(f"⚠️  Port {self.local_port} is in use. Finding another...")
            for p in range(8081, 8090):
                if not self._is_port_in_use(p):
                    self.local_port = p
                    self.pod_port = p # Ensure pod port matches
                    print(f"✓ Using available port {self.local_port}")
                    break
            else:
                raise RuntimeError("Could not find an available local port between 8080-8090.")

        config.load_kube_config()
        self.v1 = client.CoreV1Api()
        self.apps_v1 = client.AppsV1Api()

    def _is_port_in_use(self, port):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            return s.connect_ex(('localhost', port)) == 0

    def setup(self):
        """Create test deployment and wait for it to be ready."""
        print(f"\n--- Setting up test deployment '{self.deployment_name}' ---")
        # This deployment configures nginx to listen on the selected high port (`self.pod_port`)
        deployment = client.V1Deployment(
            metadata=client.V1ObjectMeta(name=self.deployment_name),
            spec=client.V1DeploymentSpec(
                replicas=1,
                selector=client.V1LabelSelector(match_labels={"app": self.deployment_name}),
                template=client.V1PodTemplateSpec(
                    metadata=client.V1ObjectMeta(labels={"app": self.deployment_name}),
                    spec=client.V1PodSpec(
                        containers=[
                            client.V1Container(
                                name="nginx",
                                image="nginx:alpine",
                                ports=[client.V1ContainerPort(container_port=self.pod_port)],
                                command=["/bin/sh", "-c"],
                                args=[
                                    f"sed -i 's/listen.*80;/listen {self.pod_port};/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
                                ]
                            )
                        ]
                    )
                )
            )
        )
        try:
            self.apps_v1.create_namespaced_deployment(namespace=self.namespace, body=deployment)
            print(f"✓ Deployment created.")
        except ApiException as e:
            if e.status == 409:
                print(f"✓ Deployment already exists.")
            else:
                raise

        self.pod_name = self._wait_for_pod_ready()

    def _wait_for_pod_ready(self, timeout=60):
        print("Waiting for pod to become ready...")
        start = time.time()
        while time.time() - start < timeout:
            pods = self.v1.list_namespaced_pod(namespace=self.namespace, label_selector=f"app={self.deployment_name}")
            if pods.items and pods.items[0].status.phase == "Running":
                if all(c.ready for c in (pods.items[0].status.container_statuses or [])):
                    pod_name = pods.items[0].metadata.name
                    print(f"✓ Pod '{pod_name}' is ready.")
                    return pod_name
            time.sleep(1)
        raise TimeoutError("Pod did not become ready in time.")

    def scale_down(self):
        """Scale the deployment to 0 replicas, deleting the pod."""
        print("\nScaling deployment to 0 replicas to terminate pod...")
        body = {"spec": {"replicas": 0}}
        self.apps_v1.patch_namespaced_deployment_scale(name=self.deployment_name, namespace=self.namespace, body=body)
        print("✓ Deployment scaled.")

    def cleanup(self):
        """Delete the test deployment."""
        print(f"\n--- Cleaning up deployment '{self.deployment_name}' ---")
        try:
            self.apps_v1.delete_namespaced_deployment(name=self.deployment_name, namespace=self.namespace)
            print(f"✓ Deployment deleted.")
        except ApiException as e:
            if e.status != 404:
                print(f"⚠️  Could not delete deployment: {e}")

    @contextmanager
    def _port_forward_kubectl(self):
        """Context manager for port forwarding using kubectl subprocess."""
        cmd = [
            "kubectl", "port-forward", f"pod/{self.pod_name}",
            f"{self.local_port}:{self.pod_port}", "-n", self.namespace
        ]
        print(f"  Starting: {' '.join(cmd)}")
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        
        try:
            time.sleep(2)
            if proc.poll() is not None:
                _, stderr = proc.communicate()
                raise RuntimeError(f"kubectl port-forward failed to start: {stderr.strip()}")
            
            print(f"✓ Port-forward active via kubectl: localhost:{self.local_port} -> pod:{self.pod_port}")
            yield proc
        finally:
            if proc.poll() is None:
                proc.terminate()
                proc.wait(timeout=5)
            print("  kubectl process terminated.")

    @contextmanager
    def _port_forward_python_client(self):
        """Context manager for port forwarding using the portforward library (WebSocket)."""
        import portforward
        
        print("  Starting port-forward via portforward library (WebSocket)...")
        
        pf = portforward.PortForwarder(
            namespace=self.namespace,
            pod_or_service=self.pod_name,  # Just the pod name, not pod/name format
            from_port=self.local_port,      # Local port
            to_port=self.pod_port,          # Remote port
        )
        
        try:
            # Start forwarding - this creates a background thread internally
            pf.forward()
            
            # Give it time to establish the connection
            time.sleep(2)
            
            print(f"✓ Port-forward active via portforward library: localhost:{self.local_port} -> pod:{self.pod_port}")
            yield pf  # Yield the PortForwarder object itself
            
        finally:
            # Stop the forwarding
            pf.stop()
            time.sleep(0.5)  # Brief pause to ensure clean shutdown
            print("  Python client thread stopped.")

    def _test_http_connection(self, should_succeed=True, retries=3):
        """Test if an HTTP GET request to the forwarded port works as expected."""
        print(f"  Testing HTTP GET to localhost:{self.local_port} (expecting {'success' if should_succeed else 'failure'})...")
        last_error = None
        
        # Add a retry loop for the initial success check to handle timing issues.
        attempts = retries if should_succeed else 1
        
        for i in range(attempts):
            try:
                response = requests.get(f"http://localhost:{self.local_port}", timeout=2)
                is_success = response.status_code == 200
            except (requests.exceptions.ConnectionError, requests.exceptions.ReadTimeout) as e:
                is_success = False
                last_error = e

            if is_success == should_succeed:
                print(f"  ✓ Correctly got {'success' if is_success else 'failure'}.")
                return True
            
            if i < attempts - 1:
                time.sleep(1) # Wait before retrying
        
        print(f"  ✗ FAILED: Expected {'success' if should_succeed else 'failure'}, but got the opposite.")
        if last_error:
            print(f"    Last error: {type(last_error).__name__}")
        return False


    def run_scenario(self, method):
        """Runs the test scenario for a given port-forwarding method."""
        print(f"--- Running Test Scenario for: {method} ---")
        
        port_forwarder_cm = {
            "kubectl": self._port_forward_kubectl,
            "python-client": self._port_forward_python_client,
        }[method]

        try:
            with port_forwarder_cm():
                # 1. Verify initial connection
                if not self._test_http_connection(should_succeed=True):
                    return False

                # 2. Delete the pod
                self.scale_down()
                print("  Waiting for connection to drop...")
                time.sleep(5) 

                # 3. Verify connection is now dead
                if not self._test_http_connection(should_succeed=False):
                    return False

            print(f"✓ SUCCESS: Port-forward for '{method}' correctly terminated after pod deletion.")
            return True

        except (RuntimeError, TimeoutError) as e:
            print(f"✗ FAILED: Could not establish port-forward for '{method}': {e}")
            return False
        except Exception as e:
            print(f"✗ FAILED: An unexpected error occurred during '{method}' test: {e}")
            return False

def main():
    try:
        subprocess.run(["tsh", "status"], check=True, capture_output=True, text=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("Error: Not logged into Teleport. Please run 'tsh login' first.")
        sys.exit(1)

    results = {}
    methods_to_test = {
        "kubectl (SPDY)": "kubectl",
        "portforward library (WebSocket)": "python-client"
    }
    
    for display_name, method_key in methods_to_test.items():
        test = PortForwardDisconnectionTest()
        try:
            test.setup()
            results[display_name] = test.run_scenario(method_key)
        finally:
            test.cleanup()

    print("\n" + "="*40)
    print("           TEST SUMMARY")
    print("="*40)
    all_passed = True
    for method, passed in results.items():
        status = "✅ PASSED" if passed else "❌ FAILED"
        print(f"  {method:<25} {status}")
        if not passed:
            all_passed = False
    print("="*40)

    if not all_passed:
        print("\nOne or more tests failed.")
        sys.exit(1)
    else:
        print("\nAll tests passed. The fix correctly handles both SPDY and WebSocket protocols. 🎉")
        sys.exit(0)

if __name__ == "__main__":
    main()
```

File: integration/kube_integration_test.go [hunk 40]
```diff
@@ -593,6 +595,189 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+		HostID:      helpers.HostID,
+		NodeName:    Host,
+		Priv:        suite.priv,
+		Pub:         suite.pub,
+		Logger:      suite.log,
+	})
+
+	username := suite.me.Username
+	kubeGroups := []string{kube.TestImpersonationGroup}
+	role, err := types.NewRole("kubemaster", types.RoleSpecV6{
```
Comment (creack) [inline integration/kube_integration_test.go:614]: This should use types.NewRoleWithVersion and set it to V8 to avoid issues next time we bump role version.

**Review by creack — COMMENTED** [review]
Maybe I am missing something, but I still can reproduce the issue on 35ce01b71b1b0bd3fdfa12f32767d10ef71ff8f2.

```
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
```

Even after deleting the pod, it keeps handling the connections.


Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
```

Port forward:

```sh
tsh kube login kind1
kubectl apply -f deploy.yaml
kubectl port-forward deployments/nginx 8080:80
```

Check loop:

```sh
while true; do curl localhost:8080; sleep 1; done
```

Scale down:

```sh
kubectl scale deployment nginx --replicas=0
```

After scale down, curl returns:

```
curl: (52) Empty reply from server
```

instead of 

```
curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server
```

and the port-forward doesn't exits.

File: lib/kube/proxy/portforward_test.go [hunk 41]
```diff
@@ -139,7 +140,17 @@ func TestPortForwardKubeService(t *testing.T) {
...
-			t.Cleanup(func() { require.NoError(t, <-errCh) })
+			t.Cleanup(func() {
+				// ErrLostConnectionToPod is an expected error.
+				// Server allowed to communicate error to client.
+				if err := <-errCh; !errors.Is(err, portforward.ErrLostConnectionToPod) {
+					// ErrLostConnectionToPod is an expected error.
+					// Server allowed to communicate error to client.
+					if !errors.Is(err, portforward.ErrLostConnectionToPod) {
+						require.NoError(t, err)
+					}
```
Comment (zmb3) [inline lib/kube/proxy/portforward_test.go]: Why are we checking if the error is `ErrLostConnectionToPod` twice like this?

Comment (rana) [reply lib/kube/proxy/portforward_test.go]: Nice observation. One check is enough there. That's updated.

**Review by creack — APPROVED** [review]

File: integration/kube_integration_test.go [hunk 42]
```diff
@@ -593,6 +595,189 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				go func() { forwarderCh <- forwarder.ForwardPorts() }()
+
+				// Wait for port-forwarding to be ready.
+				start := time.Now()
+				select {
+				case <-time.After(5 * time.Second):
+					t.Fatalf("Timeout waiting for port forwarding after %s", time.Since(start))
+				case err := <-forwarderCh:
+					require.NoError(t, err)
+				case <-forwarder.readyC:
```
Comment (zmb3) [inline integration/kube_integration_test.go]: What's the difference between `forwarderCh` and the `readyC` channel?

If we get something on the `forwarderCh`, do we also need to wait for the ready channel, or are we good to proceed without additional waiting?

File: integration/kube_integration_test.go [hunk 43]
```diff
@@ -593,6 +595,189 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+				// Validate that port-forwarding is working.
+				t.Log("Checking port forwarding")
+				resp, err := http.Get(fmt.Sprintf("http://localhost:%d", localPort))
+				require.NoError(t, err)
+				require.Equal(t, http.StatusOK, resp.StatusCode)
+				require.NoError(t, resp.Body.Close())
+				t.Log("Port forward working")
+
+				// Delete the pod.
+				t.Log("Requesting pod deletion")
```
Comment (zmb3) [inline integration/kube_integration_test.go]: Are all these log entries necessary? Looks more like something you might have been relying on during debugging.

File: lib/kube/proxy/portforward_spdy.go [hunk 44]
```diff
@@ -199,7 +200,10 @@ func (h *portForwardProxy) forwardStreamPair(p *httpStreamPair, remotePort int64
 	wg.Add(1)
 	go func() {
 		defer wg.Done()
-		if err := utils.ProxyConn(h.context, p.errorStream, targetErrorStream); err != nil {
+		// Use a unidirectional copy from Kube API to client.
+		_ = targetErrorStream.Close()
```
Comment (zmb3) [inline lib/kube/proxy/portforward_spdy.go]: Is there a reason we're not checking the error here?

File: lib/kube/proxy/portforward_spdy.go [hunk 45]
```diff
@@ -199,7 +200,10 @@ func (h *portForwardProxy) forwardStreamPair(p *httpStreamPair, remotePort int64
...
+		// Enables error propagation from Kube API server to kubectl client.
+		if _, err := io.Copy(p.errorStream, targetErrorStream); err != nil {
```
Comment (zmb3) [inline lib/kube/proxy/portforward_spdy.go:208]: Are we reading from `targetErrorStream` after closing it? Is that expected?

File: lib/kube/proxy/portforward_spdy.go [hunk 46]
```diff
@@ -305,6 +311,17 @@ func (h *portForwardProxy) run() {
 		case <-h.sourceConn.CloseChan():
 			h.logger.DebugContext(h.context, "Upgraded connection closed")
 			return
+		case <-h.targetConn.CloseChan():
+			// Backend pod lifecycle completed
+			h.logger.DebugContext(h.context, "Target connection closed")
+			// Wait for all other pairs to complete
+			// to ensure data transfer completes fully.
+			wg.Wait()
```
Comment (zmb3) [inline lib/kube/proxy/portforward_spdy.go]: Can you help me understand why there are two calls to `Wait()` here?

**Comment by creack** [comment]
> Maybe I am missing something, but I still can reproduce the issue on [35ce01b](https://github.com/gravitational/teleport/commit/35ce01b71b1b0bd3fdfa12f32767d10ef71ff8f2).
> 
> ```
> Forwarding from 127.0.0.1:8080 -> 80
> Forwarding from [::1]:8080 -> 80
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> Handling connection for 8080
> ```
> 
> Even after deleting the pod, it keeps handling the connections.
> 
> Deployment:
> 
> ```yaml
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: nginx
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: nginx
>   template:
>     metadata:
>       labels:
>         app: nginx
>     spec:
>       containers:
>       - name: nginx
>         image: nginx:latest
>         ports:
>         - containerPort: 80
> ```
> 
> Port forward:
> 
> ```shell
> tsh kube login kind1
> kubectl apply -f deploy.yaml
> kubectl port-forward deployments/nginx 8080:80
> ```
> 
> Check loop:
> 
> ```shell
> while true; do curl localhost:8080; sleep 1; done
> ```
> 
> Scale down:
> 
> ```shell
> kubectl scale deployment nginx --replicas=0
> ```
> 
> After scale down, curl returns:
> 
> ```
> curl: (52) Empty reply from server
> ```
> 
> instead of
> 
> ```
> curl: (7) Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server
> ```
> 
> and the port-forward doesn't exits.

It was user error. Helm using a different version as the built one. Sorry about this. Tested properly and confirmed it works as expected.

File: integration/kube_integration_test.go (hunk 43 above)
Comment (rana) [reply integration/kube_integration_test.go:739]: The log entries aren't a necessity. 
The log entries helped during debugging locally and in CI. 
I preserved the logs because I thought it would be helpful for the next person, especially in CI.
Do you prefer no logs?

File: lib/kube/proxy/portforward_spdy.go (hunk 46 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:319]: The main intent of the wait group is to enable each port forward to complete before exiting `run()`.

`defer wg.Wait()` handles the cases in `<-h.context.Done()` and `<-h.sourceConn.CloseChan()` which rely on `return` statements to exit the for loop.

The `<-h.targetConn.CloseChan()` case calls `wg.Wait()` before the source connection close to ensure full data transfer to the source connection.

File: integration/kube_integration_test.go (hunk 42 above)
Comment (rana) [reply integration/kube_integration_test.go]: Receiving on `ready.C` indicates that the port forwarding was successfully setup and functioning.
Receiving on `forwarderCh` indicates that port forwarding completed, possibly with an error. 

The expected sequence is first `ready.C`, and eventually a message from `forwarderCh`.
So, if we get something on `forwarderCh`, `ready.C` was already signaled, we wouldn't wait for `ready.C`, and there would be nothing to proceed with, except perhaps a test assertion and test exit.

File: integration/kube_integration_test.go (hunk 43 above)
Comment (rana) [reply integration/kube_integration_test.go]: The log entries aren't a necessity.The log entries did help during debugging both locally and in CI.
I preserved the logs because I thought it would be helpful for the next person, especially in CI.
Would you prefer removing the logs?

File: lib/kube/proxy/portforward_spdy.go (hunk 46 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go]: The main intent of the wait group is to enable each port forward to complete before exiting `run()`.

`defer wg.Wait()` handles the cases in `<-h.context.Done()` and `<-h.sourceConn.CloseChan()` which rely on `return` statements to exit the for loop.

The `<-h.targetConn.CloseChan()` case calls `wg.Wait()` before the source connection close to ensure full data transfer to the source connection.

File: integration/kube_integration_test.go (hunk 40 above)
Comment (rana) [reply integration/kube_integration_test.go:614]: Thank you for pointing that out, and our our sync call.

I updated to `types.NewRoleWithVersion` and `V7` for backporting.

I also updated `KubernetesResource`:
- "pods" -> "pod"
- Removed APIGroup for backporting
```go
KubernetesResources: []types.KubernetesResource{
{
  Kind: "pod", Name: types.Wildcard, Namespace: types.Wildcard, Verbs: []string{types.Wildcard},
},
```

File: lib/kube/proxy/portforward_spdy.go (hunk 45 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:208]: You are spot on. That is not expected. I removed `_ = targetErrorStream.Close()`.

File: lib/kube/proxy/portforward_spdy.go (hunk 44 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go]: ~I removed this line (see below).~

Error checking is added.

File: lib/kube/proxy/portforward_spdy.go (hunk 45 above)
Comment (rosstimothy) [reply lib/kube/proxy/portforward_spdy.go:208]: Are you sure that we should be removing `_ = targetErrorStream.Close()`? Tiago specifically requested this behavior to match kubectl multiple times during review, first [here](https://github.com/gravitational/teleport/pull/57051#discussion_r2225322546), then [here](https://github.com/gravitational/teleport/pull/57051#discussion_r2248421057) and [here](https://github.com/gravitational/teleport/pull/57051#discussion_r2248424282).

Comment (tigrato) [reply lib/kube/proxy/portforward_spdy.go:208]: Yep we should not remove it. Look at the code https://github.com/kubernetes/client-go/blob/d99dd130a2fc7519c0bc2bd7271447b2a16c04a2/tools/portforward/portforward.go#L361

The reason for the logic, close says that this side is done instead of actually closing the connection/stream https://github.com/moby/spdystream/blob/77eb080123d208697674a07b74ceaf94c98bee8b/stream.go#L169-L180

File: integration/kube_integration_test.go (hunk 42 above)
Comment (zmb3) [reply integration/kube_integration_test.go]: > The expected sequence is first ready.C, and eventually a message from forwarderCh.

If that's the expected sequence, then shouldn't that be what our test is checking for? (In other words, any receive on `forwarderCh` at this point should be considered an error, right?)

File: integration/kube_integration_test.go (hunk 40 above)
Comment (rana) [reply integration/kube_integration_test.go:614]: This is revised to `NewRole` with and a KubernetesResource for `v19\v18`. This is based on my research into roles and backporting discussed in [more detail in this thread](https://github.com/gravitational/teleport/pull/57474#discussion_r2255077744).

File: integration/kube_integration_test.go (hunk 42 above)
Comment (rana) [reply integration/kube_integration_test.go]: Yeah, it's too early to be checking `forwarderCh` in that select. I removed it in the latest change.

File: integration/kube_integration_test.go (hunk 43 above)
Comment (rana) [reply integration/kube_integration_test.go]: The log entries are removed. The tests will run faster without the logging.

File: lib/kube/proxy/portforward_spdy.go (hunk 45 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:208]: Thank you for clarifying the logic. `targetErrorStream.Close()` with error checking is restored in the latest update.

File: lib/kube/proxy/portforward_spdy.go (hunk 46 above)
Comment (rosstimothy) [reply lib/kube/proxy/portforward_spdy.go]: Is the explicit close of sourceConn, and the second wait needed here though? IIUC `(portForwardProxy) Close` will close the sourceConn if one exists and the contract for portForwardProxy seems to be that callers are expected to clean up by calling Close. I guess doing this here prevents a potential footgun, but if that's the contract of portForwardProxy then maybe we're making things more confusing than needed here?

File: lib/kube/proxy/portforward_spdy.go (hunk 45 above)
Comment (zmb3) [reply lib/kube/proxy/portforward_spdy.go:208]: Can we update the comment on the `targetErrorStream.Close()` line to say that close is indicating that we won't do any more writes?

The comment right now says `// Use a unidirectional copy from Kube API to client.` which doesn't seem relevant to the close call.

Comment (rana) [reply lib/kube/proxy/portforward_spdy.go:208]: Definitely, it's updated to 
`// Close the target error stream to indicate no more writes.`

File: lib/kube/proxy/portforward_spdy.go (hunk 46 above)
Comment (rana) [reply lib/kube/proxy/portforward_spdy.go]: A few observations about the `run()` function in `portforward_spdy.go`.

> Is the explicit close of sourceConn, and the second wait needed here though?

It depends on how we look at this. Explicit close of sourceConn, and the second wait are not needed for the user reported bug we're fixing.

The whole `<-h.targetConn.CloseChan():` case can be removed and the bug will still be fixed. The integration test and re-testing manually today with the Python script for `kubetctl` and Python client for WebSocket shows `<-h.targetConn.CloseChan():` does not effect the bug. The `io.Copy(p.errorStream, targetErrorStream)` in `forwardStreamPair()` is what fixes the bug. All other additions might be seen as, "while we're here, let's make some improvements". That's valid too. 

The logic for adding `<-h.targetConn.CloseChan():` seems to make sense. 

Wait group. Adding the wait group to SPDY `run()` allows all streams to complete before exiting is good behavior. That also brings SPDY `run()` into parity with WebSocket [run()](https://github.com/gravitational/teleport/blob/036babf15474ea451dbdcf583bbd639cccdb07c8/lib/kube/proxy/portforward_websocket.go#L223) which happened to already have that wait group logic.

> (portForwardProxy) Close will close the sourceConn if one exists and the contract for portForwardProxy seems to be that callers are expected to clean up by calling Close.

Yes.

> maybe we're making things more confusing than needed here?

I would agree. The second call to `Wait()` may be more complexity than needed, and for a slight return on value. 

Remove the second `Wait()` call? 

Remove `<-h.targetConn.CloseChan():`?

@zmb3 @rosstimothy @tigrato Thoughts?

**Review by fspmarshall — APPROVED** [review]
LGTM once the pending points are resolved.

File: lib/kube/proxy/portforward_spdy.go (hunk 46 above)
Comment (rosstimothy) [reply lib/kube/proxy/portforward_spdy.go]: I don't know about removing the `h.targetConn.CloseChan():` branch; don't we want to return from run in this case? Would that get caught by one of the other branches?

Comment (rana) [reply lib/kube/proxy/portforward_spdy.go]: It's symmetric to handle both `h.targetConn.CloseChan():` and `h.sourceConn.CloseChan():`, and makes sense to cover both cases. Its not obvious where else the case may be covered. It is interesting thought that the bug fix is effected by another code path. So `h.targetConn.CloseChan():` may be exercised elsewhere. Preserving it as-is is a safe approach.

Comment (tigrato) [reply lib/kube/proxy/portforward_spdy.go]: I don't think you need to have an explicit close of the source conn here.

If you return from that function - running the wg.Wait() as defer, the caller already closes the source conn right after. That said, you can re-write the `<-h.targetConn.CloseChan():`  as a log + return and you let the caller close the source conn.
https://github.com/gravitational/teleport/blob/a3fd8432fb59a058d944924e6752551099a08339/lib/kube/proxy/portforward_spdy.go#L105

We should definitely wait for the portforward pairs to terminate before returning from this function .

**Review by rosstimothy — APPROVED** [review]

File: integration/kube_integration_test.go [hunk 47]
```diff
@@ -593,6 +595,169 @@ func testKubePortForward(t *testing.T, suite *KubeSuite) {
...
+
+				// Setup port-forwarding configuration.
+				listener, err := net.Listen("tcp", "localhost:0")
+				require.NoError(t, err)
+				t.Cleanup(func() {
+					require.NoError(t, listener.Close())
+				})
+				localPort := listener.Addr().(*net.TCPAddr).Port
+				forwarder, err := tt.builder(proxyClientConfig, kubePortForwardArgs{
+					ports:        []string{net.JoinHostPort(strconv.Itoa(localPort), "80")},
```
Comment (zmb3) [inline integration/kube_integration_test.go]: I'm not sure I'd use `JoinHostPort` here because you're not joining a host and a port, you're joining two ports.

Comment (rana) [reply integration/kube_integration_test.go]: Updated
https://github.com/gravitational/teleport/blob/2e54b37c2ac4c0c36bc4c29d69caeee9c488fcd4/integration/kube_integration_test.go#L706
