### PR TITLE
Fix Windows pointer

### LINKED ISSUE #39986: Desktop access: mouse cursor disappears or gets stuck
The custom mouse cursor behavior in 15.1 can sometimes cause the mouse cursor to disappear completely, and other times cause it to get stuck as a custom icon instead of the standard pointer.

### PR DESCRIPTION
**Pull request by probakowski**
This PR fixes couple of problems with pointer in desktop access:
- stuck/hidden pointer by handling correctly `PointerHidden` and `PointerDefault` messages
- Windows 2019 not updating cursor at all in most cases by disabling cursor shadows (using `DISABLE_CURSOR_SHADOW` performance flag)
- pointer going back to default near the bottom of the screen by resizing big cursor to at most 32x32px which is maximum size fully supported by the browser

Fixes https://github.com/gravitational/teleport/issues/39986

changelog: Fix Windows cursor getting stuck

### CODE REVIEW

File: lib/srv/desktop/rdp/rdpclient/src/client.rs [hunk 1]
```diff
@@ -1168,7 +1168,7 @@ fn create_config(params: &ConnectParams, pin: String) -> Config {
         no_server_pointer: false,
         autologon: true,
         pointer_software_rendering: false,
-        performance_flags: PerformanceFlags::default()
+        performance_flags: PerformanceFlags::DISABLE_CURSOR_SHADOW
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/src/client.rs:1171]: Are we losing any other default flags by doing this?

Shoudln't we do `PerformanceFlags::default() | PerformanceFlags::DISABLE_CURSOR_SHADOW`?

Comment (probakowski) [reply lib/srv/desktop/rdp/rdpclient/src/client.rs]: We should, I don't know why I assumed that default is empty. It's fixed.

File: lib/srv/desktop/rdp/rdpclient/src/client.rs [hunk 2]
```diff
@@ -1169,6 +1169,7 @@ fn create_config(params: &ConnectParams, pin: String) -> Config {
         autologon: true,
         pointer_software_rendering: false,
         performance_flags: PerformanceFlags::default()
+            | PerformanceFlags::DISABLE_CURSOR_SHADOW
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/src/client.rs:1172]: I'd consider putting a comment on here so that we don't mistakenly remove the flag in the future.

**Review by zmb3 — APPROVED** [review]

**Comment by probakowski** [comment]
@ravicious @ibeckermayer friendly ping

File: lib/srv/desktop/rdp/rdpclient/src/client.rs [hunk 3]
```diff
@@ -1169,6 +1169,7 @@ fn create_config(params: &ConnectParams, pin: String) -> Config {
         autologon: true,
         pointer_software_rendering: false,
         performance_flags: PerformanceFlags::default()
+            | PerformanceFlags::DISABLE_CURSOR_SHADOW // this is required for pointer to work correctly in Windows 2019
```
Comment (ibeckermayer) [inline lib/srv/desktop/rdp/rdpclient/src/client.rs:1172]: Wireshark is showing me a value of `0x00000086` here with FreeRDP, which is `PerformanceFlags(DISABLE_FULLWINDOWDRAG | DISABLE_MENUANIMATIONS | ENABLE_FONT_SMOOTHING)`. 

Does this issue reproduce with FreeRDP?

File: web/packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx [hunk 4]
```diff
@@ -110,20 +108,29 @@ function TdpClientCanvas(props: Props) {
...
         }
-        const cursor = document.createElement('canvas');
+        let cursor = document.createElement('canvas');
         cursor.width = pointer.data.width;
         cursor.height = pointer.data.height;
         cursor
           .getContext('2d', { colorSpace: pointer.data.colorSpace })
           .putImageData(pointer.data, 0, 0);
+        if (pointer.data.width > 32 || pointer.data.height > 32) {
+          // scale the cursor down to at most 32px - max size fully supported by browsers
```
Comment (ibeckermayer) [inline web/packages/teleport/src/components/TdpClientCanvas/TdpClientCanvas.tsx:121]: We currently tell the server we can handle up to 384x384px cursors. Maybe it would be better not to advertise for that?

https://github.com/Devolutions/IronRDP/blob/1f067069bab87e15b758e6e5ecc9a0330bc49639/crates/ironrdp-connector/src/connection_activation.rs#L336-L341

**Review by ibeckermayer — COMMENTED** [review]
I'm skeptical this is truly fixing the root of the problem unless this reproduces with FreeRDP.

**Comment by zmb3** [comment]
@ibeckermayer @probakowski I would like to see this merged today so that it goes in the next release. What are we missing in order to make that happen?

**Comment by ibeckermayer** [comment]
Update just for reference:

- https://github.com/Devolutions/IronRDP/pull/444

has @probakowski's changes which fix the pointer disappearing issue. Those are merged, however we cannot update to IronRDP's `master` rev because we're currently relying on the still-open-as-of-this-comment

- https://github.com/Devolutions/IronRDP/pull/436

to fix licensing issues. As a temporary solution, I have merged IronRDP `master` into https://github.com/Devolutions/IronRDP/pull/436 so it includes https://github.com/Devolutions/IronRDP/pull/444, and we've updated the rev to that.

(I will work on getting https://github.com/Devolutions/IronRDP/pull/436 merged and then updating rev to IronRDP `master` ASAP)

**Review by ibeckermayer — APPROVED** [review]
