### PR TITLE
AWS IAM role matching for database users

### LINKED ISSUE #20359: Access check fails when using IAM role ARNs as db_users in user roles
Found by #20168

Expected behavior:
`tsh db connect --db-user <role-name> --db-name <db-name> redshift-serverless-wg` should succeed.

Current behavior:
```
connection to server at "localhost" (127.0.0.1), port 59922 failed: access to db denied. User does not have permissions. Confirm database user and name.
```
The current workaround is to specify the "short" role name (instead of the ARN) in `db_users`.

Bug details:
- Teleport version: v12
- Recreation steps
  - `tctl users update --set-db-users arn:aws:iam::<account-id>:role/steve-redshiftserverless-readonly alice`
  - `tsh login --proxy <proxy> --user alice`
  - `tsh db connect --db-user steve-redshiftserverless-readonly --db-name test steve-wg`

We currently do a "dumb" comparison such that `--db-user` match one of `db_users`. So if AWS role ARNs are used in `db_users`, using short role names in `tsh db connect --db-user <role-name>` will fail the match. This is also true the other way where an ARN is used as `--db-user` but short role names are used in `db_users`.

This problem should apply to all AWS databases that impersonate an IAM role: Keysapces, DynamoDB, Redshift Serverless

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #20359 

For databases that require AWS IAM roles as database users (AWS Keyspaces, DynamoDB, Redshift Serverless), today `tsh` accepts either the short-IAM-role-name or the full-IAM-role-ARN as `--db-user`.

This change allows either format to be specified in the teleport role, and will mix-match either format when IAM role is specified through `--db-user`.

Matching example from UT:
role
```
types.RoleSpecV6{             
     Allow: types.RoleConditions{       
         Namespaces:     []string{apidefaults.Namespace},       
         DatabaseLabels: types.Labels{types.Wildcard: []string{types.Wildcard}},           
         DatabaseUsers: []string{                 
             "allow-role-with-short-name",           
             "arn:aws:iam::123456789012:role/allow-role-with-full-arn",           
         },                                                          
     },                                               
 },   
```
access
```
access: []access{            
    {server: dbRequireAWSRoles, dbUser: "allow-role-with-short-name", access: true},            
    {server: dbRequireAWSRoles, dbUser: "allow-role-with-full-arn", access: true},              
    {server: dbRequireAWSRoles, dbUser: "arn:aws:iam::123456789012:role/allow-role-with-full-arn", access: true},            
    {server: dbRequireAWSRoles, dbUser: "arn:aws:iam::123456789012:role/allow-role-with-short-name", access: true},            
    {server: dbRequireAWSRoles, dbUser: "unknown-role-name", access: false},                                                   
    {server: dbRequireAWSRoles, dbUser: "arn:aws:iam::123456789012:role/unknown-role-name", access: false},            
    {server: dbRequireAWSRoles, dbUser: "arn:aws:iam::123456789012:user/username", access: false},                     
    {server: dbRequireAWSRoles, dbUser: "arn:aws-cn:iam::123456789012:role/allow-role-with-short-name", access: false},            
},  
```

### CODE REVIEW

File: lib/srv/db/common/role/role.go [hunk 1]
```diff
@@ -17,14 +17,39 @@ limitations under the License.
...
+}
+
+// RequireDatabaseNameMatcher returns true if databases with provided protocol
+// require database names.
+func RequireDatabaseNameMatcher(protocol string) bool {
+	_, ok := databaseNameMatcher(protocol, "")
+	return ok
+}
+
+func databaseNameMatcher(dbProtocol, database string) (*services.DatabaseNameMatcher, bool) {
```
Comment (Tener) [inline lib/srv/db/common/role/role.go:50]: Nit: can we check for `nil` instead of having an additional `bool` as a parameter?

**Review by Tener — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
