### PR TITLE
install-node.sh: Fix error with more robust Teleport process checking

### LINKED ISSUE #59689: [v16] Install script for Ubuntu is broken since 16.5.17-0
Expected behavior:

When I paste and execute the installation script from «Enroll new resource => Ubuntu >= 18.04», Teleport gets installed and pre-configured.

Current behavior:

Here the machine is running a freshly installed and updated Ubuntu 22.04 amd64. Teleport has never been installed on it. Teleport is probably detecting itself.

```bash
$ sudo bash -c "$(curl -fsSL https://<cluster hostname>/scripts/<token>/install-node.sh)"
2025-09-29 11:44:37 CEST [teleport-installer] TELEPORT_VERSION: 16.5.17
2025-09-29 11:44:37 CEST [teleport-installer] TARGET_HOSTNAME: <cluster hostname>
2025-09-29 11:44:37 CEST [teleport-installer] TARGET_PORT: 443
2025-09-29 11:44:37 CEST [teleport-installer] JOIN_TOKEN: <token>
2025-09-29 11:44:37 CEST [teleport-installer] CA_PIN_HASHES: <ca hash>
2025-09-29 11:44:37 CEST [teleport-installer] Checking TCP connectivity to Teleport server (<cluster hostname>:443)
2025-09-29 11:44:37 CEST [teleport-installer] Connectivity to Teleport server (via nc) looks good
2025-09-29 11:44:37 CEST [teleport-installer] Detected host: linux-gnu, using Teleport binary type linux
2025-09-29 11:44:37 CEST [teleport-installer] Detected arch: x86_64, using Teleport arch amd64
2025-09-29 11:44:37 CEST [teleport-installer] Detected distro type: debian
2025-09-29 11:44:37 CEST [teleport-installer] Using Teleport distribution: deb
2025-09-29 11:44:38 CEST [teleport-installer] Created temp dir /tmp/teleport-DZC6nvnVmz

Warning: Teleport appears to already be running on this host (pid: 70645 70646 70647 70690)

This script does not overwrite any existing settings or Teleport installations.
Please clean up by running any of the following steps as necessary:
- stop teleport's service
  - systemctl stop teleport
- stop any running Teleport processes
  - pkill -f teleport
- remove any data under /var/lib/teleport, along with the directory itself
  - rm -rf /var/lib/teleport
- remove any configuration at /etc/teleport.yaml
  - rm -f /etc/teleport.yaml
- remove teleport package
  - apt remove teleport
Run this installer again when done.


$ sudo ps -ax | grep teleport
  70716 pts/1    R+     0:00 grep --color=auto teleport
$ apt list --installed | grep teleport

WARNING: apt does not have a stable CLI interface. Use with caution in scripts
```

Bug details:
- Teleport version: cluster: git:v16.5.17-0-g98827ce (installed from APT repository)
- Recreation steps
    -  As an administrator, from the Web GUI, go to «Enroll new resource» then «Ubuntu».
    - Copy the installation script.
    - Paste the script into the terminal of the machine to configure.
- Debug logs

Probably introduced by https://github.com/gravitational/teleport/pull/59494

### PR DESCRIPTION
**Pull request by webvictim**
#59452 made Teleport process checking more robust, but introduced a bug when running the script in a `sudo bash -c $(curl...)` flow where `pgrep teleport` appears in the script name because the entire script is executed in-line.

This change grabs all the PIDs in the new `pgrep -f` way, then adds a check whether the base process for each PID is named `teleport` or not. This removes false positives.

Tested in Docker and on an Ubuntu 22.04 VM using the copy/pasted command from the web UI.

Closes https://github.com/gravitational/teleport/issues/59689

changelog: Fixes a bug with the check for a running Teleport process in the install-node.sh script.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: lib/web/scripts/node-join/install.sh [hunk 1]
```diff
@@ -418,8 +418,18 @@ download() {
...
+    POTENTIAL_PIDS=$(pgrep -f "teleport start" | xargs echo)
+    # filter PIDS to look for teleport as base process
+    for PID in ${POTENTIAL_PIDS}; do
+        if [ -f /proc/${PID}/exe ]; then
+            EXE=$(basename $(readlink /proc/${PID}/exe))
+            if [[ "${EXE}" == "teleport" ]]; then TELEPORT_PIDS="${PID} ${TELEPORT_PIDS}"; fi
+        fi
+    done
+    # return filtered list of pids with whitespace trimmed from the end
+    echo ${TELEPORT_PIDS%%[[:space::]*}
```
Comment (hugoShaka) [inline lib/web/scripts/node-join/install.sh]: Is this a typo? How did the script work with it? 🤔 

```suggestion
    echo ${TELEPORT_PIDS%%[[:space:]]*}
```

Comment (webvictim) [reply lib/web/scripts/node-join/install.sh]: Yeah it's a typo, I must have hit the wrong button during commit. Thanks!

Edit: It looks like I did test the script before committing with the typo in, but it doesn't stop things working and just fails to trim the whitespace from the end which is why I didn't notice 🙃

```
$ export TELEPORT_PIDS="1234 "
$ export TEST_ONE=${TELEPORT_PIDS%%[[:space::]*}
$ export TEST_TWO=${TELEPORT_PIDS%%[[:space:]]*}
$ echo ${#TEST_ONE}
5
$ echo ${#TEST_TWO}
4
```

`shellcheck` doesn't catch it either...

File: lib/web/scripts/node-join/install.sh [hunk 2]
```diff
@@ -418,8 +418,18 @@ download() {
...
 # gets the pid of any running teleport process (and converts newlines to spaces)
 get_teleport_pid() {
-    check_exists_fatal pgrep xargs
-    pgrep -f "teleport start" | xargs echo
+    check_exists_fatal pgrep xargs basename readlink
+    TELEPORT_PIDS=""
+    POTENTIAL_PIDS=$(pgrep -f "teleport start" | xargs echo)
+    # filter PIDS to look for teleport as base process
+    for PID in ${POTENTIAL_PIDS}; do
+        if [ -f /proc/${PID}/exe ]; then
```
Comment (marcoandredinis) [inline lib/web/scripts/node-join/install.sh]: I don't think this will work in mac os

Comment (webvictim) [reply lib/web/scripts/node-join/install.sh]: Good point. I pushed a fix in [3759c62](https://github.com/gravitational/teleport/pull/59706/commits/3759c62db8e4fa05eaca9207702626f5f88662b8)

**Comment by webvictim** [comment]
Reworked the script to use the original `pgrep teleport` behaviour by default, then use `pgrep -f "teleport start"` with the `/proc/<pid>/exe` check if `procfs` is available.

This should mean script functionality is unchanged on MacOS, but will fix the original bug from #59452 as intended _and_ resolve #59689 too on Linux.

**Review by hugoShaka — APPROVED** [review]

**Review by marcoandredinis — APPROVED** [review]

**Comment by zmb3** [comment]
@webvictim I'm not sure how this made it in, but I'm now seeing [merge failures ](https://github.com/gravitational/teleport/actions/runs/18204177558/job/51830393935)due to this lint error:

```
In ./lib/web/scripts/node-join/install.sh line 433:
                EXE=$(basename $(readlink /proc/${PID}/exe))
                               ^--------------------------^ SC2046 (warning): Quote this to prevent word splitting.
```

**Comment by timothyb89** [comment]
Fix is here: https://github.com/gravitational/teleport/pull/59886

I think the shellcheck lint job is run as part of the Go linters, which only trigger if some Go code is modified. This PR only touched a shell script, so it slipped past the linter.

File: lib/web/scripts/node-join/install.sh (hunk 1 above)
Comment (daniloaf) [reply lib/web/scripts/node-join/install.sh]: Fixed in e3c8602b4 — handleSave now calls stopAudioPlayback() before onClose(), mirroring handleClose. Added a source-inspection test asserting the call order. Thanks @bugbot — solid catch on the Radix open-prop / onOpenChange asymmetry.
