### PR TITLE
Gavinfrazar/start postgres listener with no tls no mux

### LINKED ISSUE #12181: `--insecure-no-tls` should not disable the postgresql listener on the proxy
### Description

**What happened**:

When running a teleport proxy that has TLS disabled and has a `postgres_listen_addr` set in the teleport config, it currently skips setting up the postgres listener entirely. The mongo, mysql, and kube listeners start as expected, but only the postgres_listen_addr seems to be skipped.

It looks like it is the `setupProxyListeners()` function in lib/service/service.go that handles the logic.

**What you expected to happen**:

The separate postgres listener should still be set up (just like the mongo, db, and kube listeners), even when `--insecure-no-tls` is used for the web_listen_addr.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. start a proxy service as `teleport start -d -c /etc/teleport/teleport.yaml --insecure-no-tls` with the config as seen below. Specifically, there should be a postgres_listen_addr set.
2. run `netstat -nlp` and see that the port specified by postgres_listen_addr is not listening.

(see compose file and instructions at https://gist.github.com/programmerq/4c388baeb472eeb97f889bfca6468151)

### Server Details
- Teleport version (run `teleport version`): tested with both teleport enterprise 8.3.7 and 9.1.0
- Server OS (e.g. from `/etc/os-release`): n/a
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): containerized
- Additional details:

### Client Details
n/a

### Debug Logs

given the following proxy config file, started as `teleport start -d -c /etc/teleport/teleport.yaml --insecure-no-tls`

```yaml
teleport:
  nodename: z4870proxy
  data_dir: /var/lib/teleport
  auth_servers:
  - auth:3025
  auth_token: 951f9d1f766992df36ece898ea177ace
  log:
    output: stderr
    severity: INFO
    format:
      output: text
auth_service:
  enabled: "no"
ssh_service:
  enabled: "no"
proxy_service:
  enabled: yes
  public_addr: teleport.example.com:443
  web_listen_addr: 0.0.0.0:443
  listen_addr: 0.0.0.0:3023
  ssh_public_addr: teleport.example.com:3023
  tunnel_public_addr: teleport.example.com:3024
  kube_listen_addr: 0.0.0.0:3026
  kube_public_addr: teleport.example.com:3026
  mysql_listen_addr: 0.0.0.0:3306
  mysql_public_addr: teleport.example.com:3307
  postgres_listen_addr: 0.0.0.0:5432
  postgres_public_addr: teleport.example.com:5433
  mongo_listen_addr: 0.0.0.0:27017
  mongo_public_addr: teleport.example.com:27018
```

It produces the following debug output:

```
2022-04-22T17:42:44Z             INFO Generating new host UUID: 794225fe-210f-40d8-9f86-1f673b02a0ee. service/service.go:689
2022-04-22T17:42:44Z [SQLITE]    DEBU Connected to: file:%2Fvar%2Flib%2Fteleport%2Fproc%2Fsqlite.db?_busy_timeout=10000&_sync=FULL&_txlock=immediate, poll stream period: 1s lite/lite.go:225
2022-04-22T17:42:44Z [SQLITE]    DEBU journal_mode=delete, synchronous=2, busy_timeout=10000 lite/lite.go:272
2022-04-22T17:42:44Z [KEYGEN]    DEBU SSH cert authority is going to pre-compute 25 keys. native/native.go:102
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:register.proxy service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.init service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:common.rotate service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:common.rotate service/supervisor.go:262
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:register.proxy service/supervisor.go:262
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.init service/supervisor.go:262
2022-04-22T17:42:44Z [PROC:1]    DEBU No signal pipe to import, must be first Teleport process. service/service.go:883
2022-04-22T17:42:44Z [PROC:1]    INFO Joining the cluster with a secure token. service/connect.go:395
2022-04-22T17:42:44Z [PROC:1]    DEBU Generating new key pair for Proxy first-time-connect. service/connect.go:302
2022-04-22T17:42:44Z [AUTH]      DEBU Registering node to the cluster. auth-servers:[{auth:3025 tcp }] auth/register.go:153
2022-04-22T17:42:44Z [AUTH]      INFO Attempting registration with auth server. auth/register.go:173
2022-04-22T17:42:44Z [AUTH]      WARN Joining cluster without validating the identity of the Auth Server. This may open you up to a Man-In-The-Middle (MITM) attack if an attacker can gain privileged network access. To remedy this, use the CA pin value provided when join token was generated to validate the identity of the Auth Server. auth/register.go:329
2022-04-22T17:42:44Z [AUTH]      INFO Successfully registered with auth server. auth/register.go:180
2022-04-22T17:42:44Z [PROC:1]    DEBU Deleted generated key pair Proxy first-time-connect. service/connect.go:288
2022-04-22T17:42:44Z [PROC:1]    INFO Proxy has obtained credentials to connect to the cluster. service/connect.go:429
2022-04-22T17:42:44Z [PROC:1]    DEBU Attempting to connect to Auth Server directly. auth-addrs:[auth:3025] service/connect.go:863
2022-04-22T17:42:44Z [PROC:1]    DEBU Connected to Auth Server with direct connection. auth-addrs:[auth:3025] service/connect.go:867
2022-04-22T17:42:44Z [PROC:1]    INFO The process successfully wrote the credentials and state of Proxy to the disk. service/connect.go:470
2022-04-22T17:42:44Z [PROC:1]    DEBU Connected client: Identity(Proxy, cert(794225fe-210f-40d8-9f86-1f673b02a0ee.z4870auth issued by z4870auth:53941192834394419089041111233297346647),trust root(z4870auth:53941192834394419089041111233297346647)) service/connect.go:129
2022-04-22T17:42:44Z [PROC:1]    INFO Proxy: features loaded from auth server: Kubernetes:true App:true DB:true OIDC:true SAML:true AccessControls:true AdvancedAccessWorkflows:true HSM:true  service/connect.go:76
2022-04-22T17:42:44Z [PROC:1]    DEBU Broadcasting event. event:ProxyIdentity service/supervisor.go:377
2022-04-22T17:42:44Z [PROC:1]    DEBU Service is completed and removed. service:register.proxy service/supervisor.go:239
2022-04-22T17:42:44Z [PROC:1]    DEBU Received event "ProxyIdentity". service/service.go:2450
2022-04-22T17:42:44Z [PROC:1]    DEBU Creating in-memory backend for [proxy]. service/service.go:1555
2022-04-22T17:42:44Z [PROXY:1:C] INFO Cache "proxy" first init succeeded. cache/cache.go:713
2022-04-22T17:42:44Z [PROC:1]    DEBU Setup Proxy: Web Proxy Address: 0.0.0.0:443, Reverse Tunnel Proxy Address: 0.0.0.0:3024 service/service.go:2544
2022-04-22T17:42:44Z [PROC:1]    INFO Service proxy:ssh is creating new listener on 0.0.0.0:3023. service/signals.go:213
2022-04-22T17:42:44Z [PROC:1]    DEBU Setup Proxy: turning on Kubernetes proxy. service/service.go:2556
2022-04-22T17:42:44Z [PROC:1]    INFO Service proxy:kube is creating new listener on 0.0.0.0:3026. service/signals.go:213
2022-04-22T17:42:44Z [PROC:1]    DEBU Setup Proxy: MySQL proxy address: 0.0.0.0:3306. service/service.go:2565
2022-04-22T17:42:44Z [PROC:1]    INFO Service proxy:mysql is creating new listener on 0.0.0.0:3306. service/signals.go:213
2022-04-22T17:42:44Z [PROC:1]    DEBU Setup Proxy: Mongo proxy address: 0.0.0.0:27017. service/service.go:2574
2022-04-22T17:42:44Z [PROC:1]    INFO Service proxy:mongo is creating new listener on 0.0.0.0:27017. service/signals.go:213
2022-04-22T17:42:44Z [PROC:1]    DEBU Setup Proxy: Proxy and reverse tunnel are listening on separate ports. service/service.go:2642
2022-04-22T17:42:44Z [PROC:1]    INFO Service proxy:tunnel is creating new listener on 0.0.0.0:3024. service/signals.go:213
2022-04-22T17:42:44Z [PROC:1]    INFO Service proxy:web is creating new listener on 0.0.0.0:443. service/signals.go:213
2022-04-22T17:42:44Z [PROC:1]    DEBU Setup Proxy: TLS is disabled, multiplexing is off. service/service.go:2677
2022-04-22T17:42:44Z [PROXY]     DEBU Starting watch. resource-kind:lock services/watcher.go:182
2022-04-22T17:42:44Z [PROC:1]    DEBU Creating in-memory backend for [reverse z4870auth]. service/service.go:1555
2022-04-22T17:42:44Z [PROXY:1]   DEBU Starting watch. resource-kind:proxy services/watcher.go:182
2022-04-22T17:42:44Z [REVERSE:Z] INFO Cache "remote-proxy" first init succeeded. cache/cache.go:713
2022-04-22T17:42:44Z [SSH:PROXY] DEBU Supported ciphers: ["aes128-gcm@openssh.com" "chacha20-poly1305@openssh.com" "aes128-ctr" "aes192-ctr" "aes256-ctr"]. sshutils/server.go:229
2022-04-22T17:42:44Z [SSH:PROXY] DEBU Supported KEX algorithms: ["curve25519-sha256@libssh.org" "ecdh-sha2-nistp256" "ecdh-sha2-nistp384" "ecdh-sha2-nistp521"]. sshutils/server.go:239
2022-04-22T17:42:44Z [SSH:PROXY] DEBU Supported MAC algorithms: ["hmac-sha2-256-etm@openssh.com" "hmac-sha2-256"]. sshutils/server.go:249
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.reversetunnel.server service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.reversetunnel.server service/supervisor.go:262
2022-04-22T17:42:44Z [PROXY:SER] INFO Reverse tunnel service 9.1.0:v9.1.0-0-g4d9708f85 is starting on 0.0.0.0:3024. utils/cli.go:275
2022-04-22T17:42:44Z [PROXY:SER] INFO Starting 9.1.0:v9.1.0-0-g4d9708f85 on 0.0.0.0:3024 using in-memory cache service/service.go:2842
2022-04-22T17:42:44Z [PROC:1]    DEBU Broadcasting event. event:ProxyReverseTunnelReady service/supervisor.go:377
2022-04-22T17:42:44Z [SSH:PROXY] DEBU Listening on [::]:3024. sshutils/server.go:382
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.web service/supervisor.go:201
2022-04-22T17:42:44Z [SSH:PROXY] DEBU Supported ciphers: ["aes128-gcm@openssh.com" "chacha20-poly1305@openssh.com" "aes128-ctr" "aes192-ctr" "aes256-ctr"]. sshutils/server.go:229
2022-04-22T17:42:44Z [SSH:PROXY] DEBU Supported KEX algorithms: ["curve25519-sha256@libssh.org" "ecdh-sha2-nistp256" "ecdh-sha2-nistp384" "ecdh-sha2-nistp521"]. sshutils/server.go:239
2022-04-22T17:42:44Z [SSH:PROXY] DEBU Supported MAC algorithms: ["hmac-sha2-256-etm@openssh.com" "hmac-sha2-256"]. sshutils/server.go:249
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.web service/supervisor.go:262
2022-04-22T17:42:44Z [PROXY:SER] INFO Web proxy service 9.1.0:v9.1.0-0-g4d9708f85 is starting on 0.0.0.0:443. utils/cli.go:275
2022-04-22T17:42:44Z [PROXY:SER] INFO Web proxy service 9.1.0:v9.1.0-0-g4d9708f85 is starting on 0.0.0.0:443. service/service.go:2931
2022-04-22T17:42:44Z [PROC:1]    DEBU Broadcasting event. event:ProxyWebServerReady service/supervisor.go:377
2022-04-22T17:42:44Z [PROXY:BEA] DEBU Starting Proxy heartbeat with announce period: 5m22.302255346s, keep-alive period 1m0s, poll period: 5s srv/heartbeat.go:155
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.ssh service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.reversetunnel.watcher service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.ssh service/supervisor.go:262
2022-04-22T17:42:44Z [PROXY:SER] INFO SSH proxy service 9.1.0:v9.1.0-0-g4d9708f85 is starting on 0.0.0.0:3023. utils/cli.go:275
2022-04-22T17:42:44Z [PROXY:SER] INFO SSH proxy service 9.1.0:v9.1.0-0-g4d9708f85 is starting on {0.0.0.0:3023 tcp } service/service.go:2972
2022-04-22T17:42:44Z [PROC:1]    DEBU Broadcasting event. event:ProxySSHReady service/supervisor.go:377
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.reversetunnel.watcher service/supervisor.go:262
2022-04-22T17:42:44Z [PROXY:AGE] INFO Starting reverse tunnel agent pool. service/service.go:3005
2022-04-22T17:42:44Z [PROC:1]    DEBU Service is completed and removed. service:proxy.ssh service/supervisor.go:239
2022-04-22T17:42:44Z [SSH:PROXY] DEBU Listening on [::]:3023. sshutils/server.go:382
2022-04-22T17:42:44Z [PROC:1]    DEBU Broadcasting event. event:ProxyAgentPoolReady service/supervisor.go:377
2022-04-22T17:42:44Z [PROXY:PRO] DEBU Reading Kubernetes creds. kubeClusterName: kubeconfigPath: serviceType:1 proxy/auth.go:91
2022-04-22T17:42:44Z             DEBU No local kube credentials on proxy, will not start kubernetes_service heartbeats proxy/server.go:158
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.kube service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.kube service/supervisor.go:262
2022-04-22T17:42:44Z [PROXY:PRO] INFO Starting Kube proxy on 0.0.0.0:3026. service/service.go:3064
2022-04-22T17:42:44Z [PROC:1]    DEBU Broadcasting event. event:ProxyKubeReady service/supervisor.go:377
2022-04-22T17:42:44Z [PROC:1]    DEBU Broadcasting mapped event. in:ProxyKubeReady out:EventMapping(in=[ProxySSHReady ProxyKubeReady], out=TeleportReady) service/supervisor.go:388
2022-04-22T17:42:44Z [PROC:1]    INFO The new service has started successfully. Starting syncing rotation status with period 10m0s. service/connect.go:482
2022-04-22T17:42:44Z             INFO Service has started successfully. service/service.go:523
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.db.mysql service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.db.mongo service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:proxy.shutdown service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.db.mysql service/supervisor.go:262
2022-04-22T17:42:44Z [DB:SERVIC] INFO Starting MySQL proxy server on 0.0.0.0:3306. service/service.go:3142
2022-04-22T17:42:44Z [DB:PROXY]  DEBU Started MySQL proxy. db/proxyserver.go:222
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.db.mongo service/supervisor.go:262
2022-04-22T17:42:44Z [DB:SERVIC] INFO Starting Database Mongo proxy server on 0.0.0.0:27017. service/service.go:3161
2022-04-22T17:42:44Z [DB:PROXY]  DEBU Started mongodb proxy. db/proxyserver.go:252
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:proxy.shutdown service/supervisor.go:262
2022-04-22T17:42:44Z [AUDIT:1]   INFO Creating directory /var/lib/teleport/log. service/service.go:2087
2022-04-22T17:42:44Z [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload. service/service.go:2087
2022-04-22T17:42:44Z [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload/sessions. service/service.go:2087
2022-04-22T17:42:44Z [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload/sessions/default. service/service.go:2087
2022-04-22T17:42:44Z [AUDIT:1]   INFO Creating directory /var/lib/teleport/log. service/service.go:2087
2022-04-22T17:42:44Z [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload. service/service.go:2087
2022-04-22T17:42:44Z [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload/streaming. service/service.go:2087
2022-04-22T17:42:44Z [AUDIT:1]   INFO Creating directory /var/lib/teleport/log/upload/streaming/default. service/service.go:2087
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:fileuploader.service service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Adding service to supervisor. service:fileuploader.shutdown service/supervisor.go:201
2022-04-22T17:42:44Z [PROC:1]    DEBU Service is completed and removed. service:proxy.init service/supervisor.go:239
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:fileuploader.shutdown service/supervisor.go:262
2022-04-22T17:42:44Z [PROC:1]    DEBU Service has started. service:fileuploader.service service/supervisor.go:262
2022-04-22T17:42:48Z [PROXY:1]   DEBU Attempting to restart watch after waiting 3.699996321s. resource-kind:proxy services/watcher.go:211
2022-04-22T17:42:48Z [PROXY:1]   WARN Restart watch on error: empty proxy list. resource-kind:proxy services/watcher.go:218
2022-04-22T17:42:48Z [PROXY:1]   DEBU Starting watch. resource-kind:proxy services/watcher.go:182
2022-04-22T17:42:48Z [PROXY:1]   DEBU List of known proxies updated: ["794225fe-210f-40d8-9f86-1f673b02a0ee"]. services/watcher.go:421
```

and the following netstat output:

```
$ netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::3026                 :::*                    LISTEN      8/teleport
tcp6       0      0 :::443                  :::*                    LISTEN      8/teleport
tcp6       0      0 :::27017                :::*                    LISTEN      8/teleport
tcp6       0      0 :::3306                 :::*                    LISTEN      8/teleport
tcp6       0      0 :::3023                 :::*                    LISTEN      8/teleport
tcp6       0      0 :::3024                 :::*                    LISTEN      8/teleport
```

Note the configured listener of port 5432 is absent, but the mysql, mongo kube, web, and ssh ports are present.

gz#4870

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #12181

Simple fix to start a postgres listener when TLS is disabled via `--insecure-no-tls`

### CODE REVIEW

File: lib/service/service.go [hunk 1]
```diff
@@ -2995,22 +2995,30 @@ func (process *TeleportProcess) setupProxyListeners(networkingConfig types.Clust
...
+			process.log.Debugf("Setup Proxy: Mongo proxy address: %v.", cfg.Proxy.MongoAddr.Addr)
+			listener, err := process.importOrCreateListener(listenerProxyMongo, cfg.Proxy.MongoAddr.Addr)
+			if err != nil {
+				return nil, trace.Wrap(err)
+			}
+			listeners.db.mongo = listener
+		}
+
+		if !cfg.Proxy.PostgresAddr.IsEmpty() {
+			if err := process.setPostgresListener(cfg, &listeners); err != nil {
```
Comment (espadolini) [inline lib/service/service.go:3018]: Won't this start the postgres listener twice, depending on the rest of the proxy configuration?

Comment (GavinFrazar) [reply lib/service/service.go]: Yes it will... I thought that before and fixed it, but I discard some changes and forgot to check that again. Thanks for catching it!

**Review by smallinsky — APPROVED** [review]

**Review by tigrato — APPROVED** [review]
