### PR TITLE
[Web] Fix contrast in SelectCreatable component

### LINKED ISSUE #29674: Low contrast of db users and db names with light theme in the SetupAccess step in Discover
http://localhost:9002/?path=/story/teleport-discover-database-setupaccess--no-traits&globals=theme:Light+Theme

setup access step

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves https://github.com/gravitational/teleport/issues/29674

Fixes the low contrast in light theme for the `SelectCreatable` component found in various Discover flows.

## Implementation

I initially tried to just use our existing themed `Select` component (which we use for the roles selector in the `Create User` dialog), however doing so meant that we would lose the ability to have `isFixed` items. As an alternative I manually added the styles here to match it as close as possible.

## Demo
image

image

### CODE REVIEW

File: web/packages/teleport/src/Discover/Shared/SelectCreatable/SelectCreatable.tsx [hunk 1]
```diff
@@ -21,7 +21,9 @@ import { Cross } from 'design/Icon';
 
 const styles = theme => ({
   multiValue: (base, state) => {
-    return state.data.isFixed ? { ...base, backgroundColor: 'gray' } : base;
+    return state.data.isFixed
+      ? { ...base, backgroundColor: `${theme.colors.spotBackground[2]}` }
+      : { ...base, backgroundColor: `${theme.colors.spotBackground[1]}` };
```
Comment (ravicious) [inline web/packages/teleport/src/Discover/Shared/SelectCreatable/SelectCreatable.tsx:26]: I feel like the difference between fixed and regular is too small. Changing the regular version from spot background 1 to spot background 0 feels better to me, but YMMV.

What's more, if I swap the colors (0 for fixed, 2 for regular), it brings the light version closer to the actual select component. However, the same is not true for the dark version.

I wonder if something like this wouldn't work even better:

```typescript
      backgroundColor: `${
        state.data.isFixed
          ? theme.colors.action.disabledBackground
          : theme.colors.buttons.secondary.default
      }`,
```

The downside is that in the light version, it makes the fixed labels lose the background altogether, though it's not bad for me.

Again, those are just suggestions, if I had to choose I'd compare that against the designs or something.

**Review by ravicious — APPROVED** [review]

**Review by gzdunek — APPROVED** [review]

File: web/packages/teleport/src/Discover/Shared/SelectCreatable/SelectCreatable.tsx (hunk 1 above)
Comment (rudream) [reply web/packages/teleport/src/Discover/Shared/SelectCreatable/SelectCreatable.tsx:26]: I think going with `spotBackground[0]` instead of `spotBackground[1]` for regular as you suggested looks the best. 
image
image
