### PR TITLE
Fail when JS test uses console.error or console.warn

### LINKED ISSUE #34286: Fix tests that output console errors and make Jest fail on console errors
There's quite a lot of tests which output some warnings or errors to the console.

```
$ yarn test 2>&1 | rg "^\s+console\." | wc -l
      16
```

This pollutes the test output and makes it harder to see what tests have actually failed.

Since Jest doesn't fail automatically on `console.error`, it's easy to introduce those messages unknowingly during some kind of refactoring or even making changes that we didn't think are related to the tests that start outputting warnings.

After fixing the tests, we should use [jest-fail-on-console](https://github.com/ValentinH/jest-fail-on-console) to make Jest fail if `console` gets called within tests. It seems to be a popular library and gives better error messages than just overriding `console.error` ourselves.

If there's code that needs to use console for whatever reason, it can continue doing so by [mocking the console in tests](https://github.com/ValentinH/jest-fail-on-console#but-i-have-some-expected-console-errorswarning).

### PR DESCRIPTION
**Pull request by ravicious**
Closes #34286.

`console.error` or `console.warn` used in tests typically point at an issue in either the code itself or the test setup, but they don't cause tests to fail.

```
    console.error
      Warning: An update to TestComponent inside a test was not wrapped in act(...).

      When testing, code that causes React state updates should be wrapped into act(...):

      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */

      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
          at TestComponent (/Users/rav/src/teleport/node_modules/@testing-library/react/dist/pure.js:278:5)



    console.error
      Warning: Failed prop type: Invalid prop `hasError` of type `string` supplied to `Input`, expected `boolean`.
```

Since #34286 was opened, `console` use in tests only grew, from 16 to 23 instances as of b6d4af111e002. Those messages pollute test output and might point to real issues in code or tests, but it's hard to know when your PR causes `console` to be used in tests.

This PR makes it so that calls to `console.error` or `console.warn` fail a test. Since we don't have time to fix existing issues, I added an ignore list.

If there's a test that expects either of those methods to be used, it can use them, they just have to be explicitly mocked.

From my quick tests, this PR does not slow down `yarn test`.

### CODE REVIEW

File: web/packages/shared/setupTests.tsx [hunk 1]
```diff
@@ -17,6 +17,22 @@
...
+try {
+  entFailOnConsoleIgnoreList = require('../../../e/web/testsWithIgnoredConsole');
+} catch (err) {
+  // Ignore errors related to teleport.e not being present. This allows OSS users and OSS CI to run
+  // tests without teleport.e.
+  const moduleNotFound =
+    err instanceof Error && err['code'] === 'MODULE_NOT_FOUND';
+  if (!moduleNotFound) {
+    throw err;
+  }
```
Comment (ravicious) [inline web/packages/shared/setupTests.tsx:34]: This doesn't seem to actually catch the error when `teleport.e` is not present, hence why the CI check fails. I'll take care of it tomorrow.

It should work though when you run this branch and the teleport.e branch on your machine though. https://github.com/gravitational/teleport.e/pull/4101

File: web/packages/shared/setupTests.tsx [hunk 2]
```diff
@@ -29,3 +43,24 @@ global.ResizeObserver = jest.fn().mockImplementation(() => ({
...
+// or console.warn to be used.
+//
+// If the test is expected to use either of those console functions, follow the advice from the
+// error message.
+const failOnConsoleIgnoreList = new Set([
+  'web/packages/design/src/utils/match/matchers.test.ts',
+  'web/packages/shared/components/TextEditor/TextEditor.test.tsx',
+  'web/packages/teleport/src/components/BannerList/useAlerts.test.tsx',
+  'web/packages/teleport/src/Navigation/NavigationItem.test.tsx',
+  'web/packages/teleterm/src/ui/TabHost/TabHost.test.tsx',
```
Comment (kimlisa) [inline web/packages/shared/setupTests.tsx:58]: i was testing it out and we may need to add one more?

**Review by kimlisa — APPROVED** [review]

**Review by gzdunek — APPROVED** [review]
Thanks for adding this.

**Comment by ravicious** [comment]
Backporting this only to v15. The most important thing is that it works on master. I don't want to have to go through the tests on each branch just to re-check whether the ignore list is correct or not. 😩

File: web/packages/shared/setupTests.tsx (hunk 2 above)
Comment (ravicious) [reply web/packages/shared/setupTests.tsx:58]: It just failed on CI though. ;f I'm going to add it to the list then.

https://github.com/gravitational/teleport/actions/runs/9015736034/job/24770973952#step:7:1125

Comment (ravicious) [reply web/packages/shared/setupTests.tsx:58]: Same thing with `web/packages/teleport/src/Recordings/Recordings.story.test.tsx` locally just now. Definitely a flake since I cannot even reproduce it with the same seed.
