### PR TITLE
Fix caching of client credentials when users re-login to incorporate new attributes

### LINKED ISSUE #18070: Cached Kubernetes client credentials lead to access denied requests
## Problem

Kube Access customer uses SAML attributes to control access to their Kubernetes clusters. These custom SAML attributes are returned from their IdP, however their users normally get assigned these attributes _after_ they had already logged into Teleport. So their usage scenario is:

- User logs into Teleport: `tsh login`. Their certificate doesn't have required SAML attributes.
  - User can't use Kube Access which is expected.
- User requests these custom SAML attributes using their own internal access requests tool.
- User logs out of Teleport and logs back in: `tsh logout && tsh login && tsh kube login`.
  - At this point user can now see Kube clusters in `tsh kube ls` but any `kubectl` command still fails with "access denied".
- After about an hour (or max role TTL, whichever is smaller), they can logout/login again, at which point `kubectl` works fine.

## Analysis

During troubleshooting we figured that the most likely cause is that Kube proxy caches client credentials in a TTL map:

https://github.com/gravitational/teleport/blob/v8.3.20/lib/kube/proxy/forwarder.go#L276

So in the above scenario, even after logging out and back in, the proxy still uses the client certificate without SAML traits in it that was cached during the initial login. If we look at the cache key, we see that it does not really include anything that can differentiate between user login sessions:

https://github.com/gravitational/teleport/blob/v8.3.20/lib/kube/proxy/forwarder.go#L321-L325

It does include `disconnect_expired_cert` timestamp that is only added to the cache key if this role option is enabled. The customer didn't have it enabled. We tried enabling it and saw that it solved the issue which confirmed that it's related to the cached credential applying to different sessions. This is not a great workaround however since enabling this setting would lead to all sessions (incl. database, SSH) being terminated in case of expired certificate which isn't desirable behavior for the customer.

## Fix

A prototype fix is below, which updates the credentials cache key to always use the client certificate's expiration time which should give us best of both worlds: cert for the same session will be cached and reused but when user logs out and logs back in again, we'll request a new cert. See the diff here:

https://github.com/gravitational/teleport/compare/branch/v8...roman/v8/cachefix

I've confirmed this behavior locally and shared dev build with the customer (`v8.3.21-cachefix.1`) so they can confirm if it fixes the issue for them as well. _**UPDATE: The customer confirmed this fixes the issue for them.**_

## Scope

The fix should be backported to all active versions, as well as v8 as this is the version that the customer is still running.

### PR DESCRIPTION
**Pull request by tigrato**
When users re-login after a failed attempt to access a Kubernetes cluster, Teleport may continue to use the old credentials for cluster access. This behavior results in successive failures until the credential cache expires (~1h).

This PR includes changes made by @r0mant to resolve the cache issue. It introduces certificate expiration in the cache key. Every time the user logs in again, the key will be different because the certificate expiration date is different. Thus, Teleport won't reuse the cached credentials.

Fixes #18070

### CODE REVIEW

File: lib/kube/proxy/forwarder.go [hunk 1]
```diff
@@ -1898,12 +1901,14 @@ func (f *Forwarder) getClientCreds(ctx authContext) *tls.Config {
 	if !validClientCreds(f.cfg.Clock, c) {
 		return nil
 	}
+	f.log.Debugf("Returning cached client credentials with key: %v", ctx.key())
```
Comment (r0mant) [inline lib/kube/proxy/forwarder.go:1904]: This was useful for debugging but I think this might be spammy IRL, I'd probably remove these debug logs here and below now.

**Review by r0mant — APPROVED** [review]

**Review by strideynet — APPROVED** [review]
