### PR TITLE
Fix `tsh` from a `tsh ssh` session

### LINKED ISSUE #26702: `tsh` errors inside nested teleport session on `ssh` and `logout`
Expected behavior:
```
$ tsh login
<snip> # successful login
$ tsh ssh user@node
[user@node ~]$ tsh login  
<snip> # successful login
[user@node ~]$ tsh ssh foobar uptime
 11:32:46 up 181 days, 19:05, 12 users,  load average: 0.08, 0.02, 0.01
[user@node ~]$ tsh logout
Logged out foo@bar from proxy.foobar.com
```

Current behavior:
```
$ tsh login
<snip> # successful login
$ tsh ssh user@node
[user@node ~]$ tsh login
<snip> # successful login
[user@node ~]$ tsh ssh foobar
ERROR: Get "https://<proxyhost>:3080/webapi/ping": dial tcp: lookup <proxyhost>: no such host
[user@node ~]$ tsh logout
Specify --proxy and --user to remove keys for specific user from a proxy or neither to log out all users from all proxies.
```

Workaround:
`export SSH_SESSION_WEBPROXY_ADDR=$(cat ~/.tsh/current-profile):3080`

Bug details:
- Teleport version 
  - v12.4.3
- Recreation steps 
  - `tsh login && (tsh ssh foobar uptime || tsh logout)`
- Debug logs 
  - Available upon request

### PR DESCRIPTION
**Pull request by Joerger**
https://github.com/gravitational/teleport/issues/24241 was intended for headless use cases, but breaks non headless cases. Specifically, the `SSH_TELEPORT_` env variables would be used in place of the user's active profile, unless they provide the corresponding flags explicitly.

Updates https://github.com/gravitational/teleport/issues/26946
Closes https://github.com/gravitational/teleport/issues/26702

### CODE REVIEW

**Comment by zmb3** [comment]
Please add test coverage, especially in cases like this where we had a regression.

File: tool/tsh/tsh.go [hunk 1]
```diff
@@ -3391,6 +3391,19 @@ func makeClientForProxy(cf *CLIConf, proxy string) (*client.TeleportClient, erro
 		}
 	}
 
+	// When using Headless, check for missing proxy/user/cluster values from the teleport session env variables.
+	if cf.AuthConnector == constants.HeadlessConnector {
```
Comment (Tener) [inline tool/tsh/tsh.go:3395]: Why do we check for headless auth connector here and not `cf.Headless` as above? Even if `--headless` is a shorthand for `--auth=headless`, we should only have one way of performing this check.

File: tool/tsh/tsh.go [hunk 2]
```diff
@@ -4579,22 +4592,12 @@ func setEnvFlags(cf *CLIConf, getEnv envGetter) {
 			cf.SiteName = clusterName
 		} else if clusterName = getEnv(siteEnvVar); clusterName != "" {
 			cf.SiteName = clusterName
-		} else if clusterName = getEnv(teleport.SSHTeleportClusterName); clusterName != "" {
```
Comment (Tener) [inline tool/tsh/tsh.go:4582]: The purpose of `setEnvFlags` is to populate the `cf` from env. Moving this code to a different function breaks that, making it harder to reason about the code. We also lose `getEnv`, which helps with tests.

File: tool/tsh/tsh.go [hunk 3]
```diff
@@ -3391,6 +3391,19 @@ func makeClientForProxy(cf *CLIConf, proxy string) (*client.TeleportClient, erro
...
 	}
 
+	// When using Headless, check for missing proxy/user/cluster values from the teleport session env variables.
+	if cf.AuthConnector == constants.HeadlessConnector {
+		if c.WebProxyAddr == "" {
+			c.WebProxyAddr = os.Getenv(teleport.SSHSessionWebproxyAddr)
+		}
+		if c.Username == "" {
+			c.Username = os.Getenv(teleport.SSHTeleportUser)
+		}
```
Comment (nklaassen) [inline tool/tsh/tsh.go:3401]: how does this interact with the ExplicitUsername check above? Should we also be doing the ExplicitUsername check when the user provides `--auth=headless` instead of `--headless`?

File: tool/tsh/tsh.go (hunk 1 above)
Comment (Joerger) [reply tool/tsh/tsh.go:3395]: In the check above, we use `cf.Headless` to set `cf.AuthConnector` so that below we can just check `cf.AuthConnector`.

File: tool/tsh/tsh.go (hunk 3 above)
Comment (Joerger) [reply tool/tsh/tsh.go:3401]: Yes, and it should also count `SSHTeleportUser` as explicity username. Thanks for catching this.

File: tool/tsh/tsh_test.go [hunk 4]
```diff
@@ -2245,6 +2245,73 @@ func TestEnvFlags(t *testing.T) {
 			},
 		}))
 	})
+
+	t.Run("tsh ssh session env", func(t *testing.T) {
```
Comment (nklaassen) [inline tool/tsh/tsh_test.go:2249]: could add a case to test for an error on headless login without explicit username

**Review by nklaassen — APPROVED** [review]

File: tool/tsh/tsh_test.go (hunk 4 above)
Comment (Joerger) [reply tool/tsh/tsh_test.go:2249]: This is covered in `TestSSHHEadless`

**Comment by Joerger** [comment]
@Tener can you re-review when you get a chance?

**Review by Tener — APPROVED** [review]
