### PR TITLE
relax local log restrictions & improve file log errors

### LINKED ISSUE #3771: Changing path for Audit logs (audit_events_uri) results in Teleport initialization failure
### Description
Changing the local file path to another directory (e.g. `/var/lib/teleport/audit`) requires `audit_sessions_uri` to also be set otherwise Teleport does not initialize/start.

**What happened**:
added the following configuration to `teleport.yaml`

```
teleport:
  storage:
    type: dir
    audit_events_uri: ['file:///var/lib/teleport/audit']
```

**What you expected to happen**:
Teleport to start and Audit events get placed in new root directory

**How to reproduce it (as minimally and precisely as possible)**:
add configuration above

### Environment
- Teleport version (use `teleport version`): 4.2.6
- Tsh version (use `tsh version`): 4.2.6
- OS (e.g. from `/etc/os-release`): 
Teleport container image:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
```

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
Kubernetes

**Browser environment**

- Browser Version (for UI-related issues): N/A
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**
```
ERROR REPORT:
Original Error: *trace.BadParameterError please specify audit_sessions_uri when using external audit backends
Stack Trace:
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:823 github.com/gravitational/teleport/lib/service.initExternalLog
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:942 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:648 github.com/gravitational/teleport/lib/service.NewTeleport
	/gopath/src/github.com/gravitational/teleport/e/lib/pro/process.go:41 github.com/gravitational/teleport/e/lib/pro.NewTeleport
	/gopath/src/github.com/gravitational/teleport/e/tool/teleport/main.go:35 main.run.func1
	/gopath/src/github.com/gravitational/teleport/lib/service/service.go:401 github.com/gravitational/teleport/lib/service.Run
	/gopath/src/github.com/gravitational/teleport/e/tool/teleport/main.go:43 main.run
	/gopath/src/github.com/gravitational/teleport/e/tool/teleport/main.go:27 main.main
	/opt/go/src/runtime/proc.go:212 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1358 runtime.goexit
User Message: please specify audit_sessions_uri when using external audit backends, initialization failed
```

- `tsh --debug`
- `teleport --debug`

### PR DESCRIPTION
**Pull request by fspmarshall**
Previously, `teleport` would refuse to start if `audit_events_uri` only contained only file-based loggers, or if `audit_events_uri` was defined, but `audit_sessions_uri` was not.  This was intended to prevent accidental misuse, but disallowed to legitimate use of `audit_events_uri` for overriding the default event output path.

This PR partially relaxes the above restrictions, allowing the use of `audit_events_uri`, but still requiring that audit events are uploaded if session recordings are being uploaded.

Fixes #3771

### CODE REVIEW

File: lib/service/service.go [hunk 1]
```diff
@@ -817,7 +817,7 @@ func initUploadHandler(auditConfig services.AuditConfig) (events.UploadHandler,
 }
 
 // initExternalLog initializes external storage, if the storage is not
-// setup, returns nil
+// setup, returns (nil, nil).
 func initExternalLog(auditConfig services.AuditConfig) (events.IAuditLog, error) {
 	if auditConfig.AuditTableName != "" {
 		log.Warningf("Please note that 'audit_table_name' is deprecated and will be removed in several releases. Use audit_events_uri: '%v://%v' instead.", dynamo.GetName(), auditConfig.AuditTableName)
```
Comment (webvictim) [inline lib/service/service.go:823]: Should we add a `// REMOVE IN` comment here? We've been saying we're going to deprecate `audit_table_name` for a long time.

**Review by awly — COMMENTED** [review]
Add a unit test please :)

File: lib/service/service.go [hunk 2]
```diff
@@ -885,28 +888,26 @@ func initExternalLog(auditConfig services.AuditConfig) (events.IAuditLog, error)
...
-			return nil, trace.BadParameter(
-				"file:// or stdout:// log can not be used on it's own, " +
-					"can be only used in combination with external session logs, e.g. dynamodb://")
-		}
+
+	if len(loggers) < 1 {
+		return nil, nil
+	}
+
+	if !hasNonFileLog {
```
Comment (russjones) [inline lib/service/service.go:896]: I think we'll have customers running Teleport in environments where storing sessions locally is acceptable, I'd remove this warning.

**Review by russjones — APPROVED** [review]

File: lib/service/service.go [hunk 3]
```diff
@@ -866,6 +863,12 @@ func initExternalLog(auditConfig services.AuditConfig) (events.IAuditLog, error)
 			}
 			loggers = append(loggers, logger)
 		case teleport.SchemeFile:
+			if uri.Path == "" {
+				return nil, trace.BadParameter("unsupported audit uri: %s (missing path component)", uri)
```
[the remark this answers is not in the document]
Comment (fspmarshall) [reply lib/service/service.go:867]: Woah, TIL `%q` works with the `String` method.  Neat.

**Comment by fspmarshall** [comment]
retest this please
