### PR TITLE
Periodically reload proxy certificates

### LINKED ISSUE #3815: Teleport-proxy does not serve updated https certificates without restart
### Description
We use short-lived SSL certificates from a private CA in our environment, and we have provisioned our private teleport-proxies to serve these short-lived https certificates. (teleport.yaml directive: proxy_service.https_cert_file)

It appears that when these short-lived certificates are rotated and placed on the server, the teleport service continues to pass the old certificate out.  Obvs this is no good - we COULD code 'systemctl restart teleport' into the cert rotation, but much better for teleport to handle automated cert changes (so we don't have to force-disconnect users)!

**What happened**:
contents of proxy_service.https_cert_file changed, but teleport service did not reflect the change until after a restart

**What you expected to happen**:
the teleport service to accurately reflect the cert file after any possible updates without requiring a restart

**How to reproduce it (as minimally and precisely as possible)**:
Helps to have your own CA, but you can spoof this, too!
1. have a testing teleport proxy up-and-running.  Be sure you can reach it from a browser.
2. generate a keypair on teleport-proxy and self-sign the public key into a certificate with some unique metadata (for instance, expiry date of tomorrow)
3. point your teleport proxy's 'proxy_service.https_cert_file' and 'proxy_service.https_key_file' to the generated key/cert
4. start the teleport service on the teleport-proxy
5. Point a browser to the teleport-proxy node and view the certificate that is returned (paying close attention to the unique metadata you've set in step 2)
6. on the teleport-proxy, regenerate/re-sign the certificate, but vary the unique metadata from step 2 (for instance, change the expiry date to next week)
7. Confirm that teleport-proxy's teleport.yaml is still pointing to the correct key/cert, but DO NOT restart the teleport service
8. Point a browser to the teleport proxy node and view the certificate that is returned.  Notice that the unique metadata from steps 2/6 have NOT been changed from the previous cert you received!

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.2.10git:v4.2.10-0-g7fd6c7348 go1.13.2
- Tsh version (use `tsh version`): Teleport v4.2.10 git:v4.2.10-0-g7fd6c7348 go1.13.2
- OS (e.g. from `/etc/os-release`): CentOS Linux release 7.7.1908 (Core)

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS EC2s, but treat it like baremetal

**Browser environment**

- Browser Version (for UI-related issues): Google Chrome, Version 83.0.4103.97 (Official Build) (64-bit)
- Install tools: NA
- Others: NA

**Relevant Debug Logs If Applicable**

NA

gz#3739

### PR DESCRIPTION
**Pull request by vitorenesduarte**
Fixes #3815

This commit adds a certificate reloader that periodically reloads proxy certificates.

Implementation was intentionally kept as simple as possible:
- periodically go through all key pairs and try to load them again
- if any key pair fails to load, then no certificate is updated
- no retry mechanism
- `inotify` is not used

The interval between reloads is configurable by setting `https_keypairs_reload_interval` to some duration. If not set, or if set to `0`, then certificates are not reloaded periodically. Thus, this feature is opt-in and the current behaviour is maintained.

---

<details>
  <summary>Additional testing</summary>

- teleport config `config.yaml`:
```yaml
version: v3
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: json

auth_service:
  enabled: yes
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport
  authentication:
    type: local
    second_factor: on
    webauthn:
      rp_id: go.teleport
    connector_name: passwordless

ssh_service:
  enabled: no
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  tunnel_listen_addr: 0.0.0.0:3024
  web_listen_addr: 0.0.0.0:443
  public_addr: go.teleport:443
  https_keypairs:
  - key_file: certs/server.key
    cert_file: certs/server.crt
  https_keypairs_reload_interval: 1ms
  acme: {}
```

- https://github.com/ryanclark/development#dns-resolution

- start teleport (terminal 1):
```bash
make release
sudo rm -rf /var/lib/teleport && sudo build/teleport start --config=config.yaml --debug 2>&1
```

- generate certs in a loop (terminal 2):
```bash
seq 1 1000000 | while read i; do echo -en "\r$i"; mkdir -p certs && mkcert -cert-file certs/server.crt -key-file certs/server.key go.teleport "*.teleport" "*.go.teleport" >/dev/null 2>&1; done
```

- watch certs (terminal 3):
```bash
watch -n0 'echo | openssl s_client -showcerts -servername gnupg.org -connect go.teleport:443 2>/dev/null | openssl x509 -inform pem -noout -text | grep "Not Before"'
```

</details>

### CODE REVIEW

File: lib/service/certreloader_test.go [hunk 1]
```diff
@@ -0,0 +1,269 @@
...
+				require.Equal(t, before[1], after[1])
+			},
+		},
+	}
+
+	for _, tc := range testCases {
+		t.Run(tc.desc, func(t *testing.T) {
+			// Create empty certs and ensure they get cleaned up.
+			certs := newCerts(t)
+			defer certs.cleanup(t)
```
Comment (zmb3) [inline lib/service/certreloader_test.go:153]:
```suggestion
			t.Cleanup(certs.cleaup)
```

You'll also have to change the signature of `certs.cleanup` to no longer take a `testing.T`. 

Though, on second though, I would get rid of the cleanup method and have `newCerts` register the appropriate cleanup action (see below comments)

File: lib/service/certreloader_test.go [hunk 2]
```diff
@@ -0,0 +1,269 @@
...
+	c2Key *os.File
+	c2Crt *os.File
+}
+
+// newCerts creates files for 2 certificate key pairs,
+// generates 2 certificate key pairs, and writes them
+// to the files created.
+func newCerts(t *testing.T) certFiles {
+	// Create files where key-pair certs will be written to.
+	c1Key, err := os.CreateTemp("", "cert1_*.key")
```
Comment (zmb3) [inline lib/service/certreloader_test.go:199]: These files are never closed. I would probably close them before removing them.

Additionally, you can make things even easier on yourself by registering the cleanup call(s) here and removing the `cleanup` func completely.

Another improvement you might find worthwhile is to stop dealing with `*os.File`. Instead you could create a root dir for your certs with `t.TempDir` and then just use `os.WriteFile` to write data to them. This way you don't have to mess with truncating and seeking, and the files will get removed automatically when the test completes.

**Review by zmb3 — COMMENTED** [review]
Looks good, just have some suggestions for cleaning up the tests.

**Review by espadolini — COMMENTED** [review]
Are we sure about the approach of just reloading every n minutes?

Also, we should at least document that the certificate chain should be updated atomically, because as it stands, it's possible that we read the cert file containing the full leaf and then just a truncated chain, which would result in the proxy happily not sending the full chain to clients.

File: lib/service/certreloader_test.go (hunk 2 above)
Comment (vitorenesduarte) [reply lib/service/certreloader_test.go]: Thanks for the suggestion! Done in 467913190b4330f63350cc8ae0969bcec50696e3.

File: lib/service/certreloader.go [hunk 3]
```diff
@@ -0,0 +1,145 @@
...
+	certs := []tls.Certificate{}
+	for _, pair := range c.cfg.KeyPairs {
+		c.Debugf("Loading TLS certificate %v and key %v.", pair.Certificate, pair.PrivateKey)
+
+		certificate, err := tls.LoadX509KeyPair(pair.Certificate, pair.PrivateKey)
+		if err != nil {
+			// If one certificate fails to load, then no certificate is updated.
+			return trace.Wrap(err)
+		}
+		certs = append(certs, certificate)
```
[the remark this answers is not in the document]
Comment (vitorenesduarte) [reply lib/service/certreloader.go]: Thanks for suggestion! Done in 2090e2b2a3e4936e2b470dc9273eaa77958e1ada.

**Comment by vitorenesduarte** [comment]
> Are we sure about the approach of just reloading every n minutes?

This seemed to be the simplest approach that would work on cloud.
There we have a ~30-day grace period (https://github.com/gravitational/cloud/pull/3053), so setting `https_keypairs_reload_interval` to e.g. 1 day should work well.

The issue also mentions the case of short-lived certs (https://github.com/gravitational/teleport/issues/3815#issuecomment-1145711151), but even in those situations setting the interval to e.g. 1 minute should be fine.

WDYT @espadolini?

File: lib/service/certreloader.go [hunk 4]
```diff
@@ -0,0 +1,158 @@
...
+			return trace.Wrap(err)
+		}
+
+		// Parse the end entity cert and add it to certificate.Leaf.
+		// With this, the SupportsCertificate call doesn't have to
+		// parse it on every GetCertificate call.
+		leaf, err := x509.ParseCertificate(certificate.Certificate[0])
+		if err != nil {
+			// If one certificate fails to load, then no certificate is updated.
+			return trace.Wrap(err)
```
Comment (strideynet) [inline lib/service/certreloader.go:119]: Maybe these wraps ought to include a message or field that indicates which certificate path has failed, otherwise, users with multiple configured certificates will have to work it out themselves which is causing the issue.

**Review by strideynet — APPROVED** [review]
I think this is a nice first implementation of this, and we can consider adding `inotify` as a trigger down the road.

Please ensure we update the docs to include this feature and ensure that we mention that one certificate failing to load will cause all to fail to load.

File: lib/service/certreloader_test.go [hunk 5]
```diff
@@ -0,0 +1,231 @@
...
+	"path/filepath"
+	"testing"
+	"time"
+
+	"github.com/stretchr/testify/require"
+
+	"github.com/gravitational/teleport/lib/utils"
+)
+
+func TestCertReloader(t *testing.T) {
```
Comment (strideynet) [inline lib/service/certreloader_test.go:32]: It seems safe to add `t.Parallel()` to this test and given we generate certs, maybe this is worth doing.

File: lib/service/certreloader.go (hunk 4 above)
Comment (vitorenesduarte) [reply lib/service/certreloader.go]: Thanks for the review! Done in b79840d120a6975ac21b77c35e349c3429a63bd6.

File: lib/service/certreloader_test.go (hunk 5 above)
Comment (vitorenesduarte) [reply lib/service/certreloader_test.go:32]: Done in 6a030b8f04232190222e51415bafe8d5f1236bcc.

**Review by espadolini — APPROVED** [review]

**Review by espadolini — APPROVED** [review]

File: docs/pages/reference/config.mdx [hunk 6]
```diff
@@ -716,6 +716,12 @@ proxy_service:
     - key_file: /etc/letsencrypt/live/*.teleport.example.com/privkey.pem
       cert_file: /etc/letsencrypt/live/*.teleport.example.com/fullchain.pem
 
+    # Interval between attempts to reload the certificate key pairs.
+    # If one of the key pairs fails to load, then no key pair is reloaded.
+    # If set to 0, then periodic reloading is disabled.
+    # To use this feature correctly, certificate files should be updated atomically.
+    https_keypairs_reload_interval: 1h
```
Comment (strideynet) [inline docs/pages/reference/config.mdx:723]: Should we include a comment on the fact the default for this is 0 (e.g disabled)

**Review by strideynet — APPROVED** [review]

File: docs/pages/reference/config.mdx (hunk 6 above)
Comment (vitorenesduarte) [reply docs/pages/reference/config.mdx:723]: Done in 95cb8dcee5ccc6087b4e61a7e0c22613394eb9af. Please let me know if it can be improved somehow.

**Review by zmb3 — APPROVED** [review]

File: docs/pages/reference/config.mdx [hunk 7]
```diff
@@ -716,6 +716,12 @@ proxy_service:
     - key_file: /etc/letsencrypt/live/*.teleport.example.com/privkey.pem
       cert_file: /etc/letsencrypt/live/*.teleport.example.com/fullchain.pem
 
+    # Interval between attempts to reload the certificate key pairs.
+    # If one of the key pairs fails to load, then no key pair is reloaded.
+    # If set to 0 (the default), then periodic reloading is disabled.
+    # To use this feature correctly, certificate files should be updated atomically.
```
Comment (alexfornuto) [inline docs/pages/reference/config.mdx:722]: I just want to confirm that this is supposed to be "atomically" and not "automatically"

**Review by alexfornuto — APPROVED** [review]
👍 with one confirmation requested.

File: docs/pages/reference/config.mdx (hunk 7 above)
Comment (vitorenesduarte) [reply docs/pages/reference/config.mdx:722]: Yes, "atomically" is correct.
