### PR TITLE
[gke] skip hard error when client misses permissions for some projects

### LINKED ISSUE #48101: Gracefully fail and continue discovery if GKE project is missing required wildcard project_ids permissions
What would you like Teleport to do?

Implement graceful fail and continue discovery for GKE clusters using auto-discover if IAM permissions are missing for some projects when wildcard `project_ids` option is used. A single project missing permissions should not preclude discovery of clusters in other projects that do have the permissions. Instead, we should note and skip the ones with missing permissions to allow users to audit and cure at a later time if necessary without impacting rest of auto-discovery.

What problem does this solve?

Teleport now [allows users to set wildcards in the `project_ids` field for GKE auto-discovery](https://goteleport.com/docs/enroll-resources/auto-discovery/kubernetes/google-cloud/#create-an-iam-role-for-the-discovery-service).

Users with mixed environments where some projects don't have (and will not have) the required IAM permissions, however, have observed that when Teleport encounters such a project, it will immediately break and terminate auto-discovery with the following trace:

```
2024-10-22T20:12:34Z WARN [DISCOVERY] Unable to fetch resources for kube_cluster at GCP. error:[

ERROR REPORT:

Original Error: *apierror.APIError rpc error: code = PermissionDenied desc = Required &#34;container.clusters.list&#34; permission(s) for &#34;projects/<project_name>&#34;.

error details: name = ErrorInfo reason = IAM_PERMISSION_DENIED domain = [container.googleapis.com](http://container.googleapis.com/) metadata = map[]
error details: name = RequestInfo id = <some_id> data =

Stack Trace:
                [github.com/gravitational/teleport/lib/cloud/gcp/kubernetes.go:189](http://github.com/gravitational/teleport/lib/cloud/gcp/kubernetes.go:189) [github.com/gravitational/teleport/lib/cloud/gcp.(*gkeClient).ListClusters](http://github.com/gravitational/teleport/lib/cloud/gcp.(*gkeClient).ListClusters)
                [github.com/gravitational/teleport/lib/srv/discovery/fetchers/gke.go:114](http://github.com/gravitational/teleport/lib/srv/discovery/fetchers/gke.go:114) [github.com/gravitational/teleport/lib/srv/discovery/fetchers.(*gkeFetcher).getGKEClusters](http://github.com/gravitational/teleport/lib/srv/discovery/fetchers.(*gkeFetcher).getGKEClusters)
                [github.com/gravitational/teleport/lib/srv/discovery/fetchers/gke.go:100](http://github.com/gravitational/teleport/lib/srv/discovery/fetchers/gke.go:100) [github.com/gravitational/teleport/lib/srv/discovery/fetchers.(*gkeFetcher).Get](http://github.com/gravitational/teleport/lib/srv/discovery/fetchers.(*gkeFetcher).Get)
                [github.com/gravitational/teleport/lib/srv/discovery/common/watcher.go:152](http://github.com/gravitational/teleport/lib/srv/discovery/common/watcher.go:152) [github.com/gravitational/teleport/lib/srv/discovery/common.(*Watcher).fetchAndSend.func1](http://github.com/gravitational/teleport/lib/srv/discovery/common.(*Watcher).fetchAndSend.func1)
                [golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78](http://golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78) [golang.org/x/sync/errgroup.(*Group).Go.func1](http://golang.org/x/sync/errgroup.(*Group).Go.func1)
                runtime/asm_amd64.s:1695 runtime.goexit
```

If a workaround exists, please include it.

n/a

### PR DESCRIPTION
**Pull request by tigrato**
This PR fixes a behavior problem that results in GKE discovery to completely fail when the client misses permissions in some of the discovered projects.

If the client misses list permissions for projectID 1 but has the required permissions for projectID 2, the discovery service should continue with the projectID 2 discovery and skip the failing one.

Fixes #48101

Changelog: Fixed a bug in GKE auto-discovery where the process failed to discover any clusters if the identity lacked permissions for one or more detected GCP project IDs.

### CODE REVIEW

File: lib/srv/discovery/fetchers/gke.go [hunk 1]
```diff
@@ -114,6 +114,12 @@ func (a *gkeFetcher) getGKEClusters(ctx context.Context, projectID string) (type
 	var clusters types.KubeClusters
 
 	gkeClusters, err := a.GKEClient.ListClusters(ctx, projectID, a.Location)
+	if trace.IsAccessDenied(err) {
+		a.Logger.WarnContext(ctx, "Access denied to list GKE clusters", "project_id", projectID, "location", a.Location)
+		return nil, nil
+	} else if err != nil {
+		return nil, trace.Wrap(err)
+	}
```
Comment (ryanclark) [inline lib/srv/discovery/fetchers/gke.go:122]: I feel like this is a nicer way of doing this

```suggestion
	if err != nil {
		if trace.IsAccessDenied(err) {
			a.Logger.WarnContext(ctx, "Access denied to list GKE clusters", "project_id", projectID, "location", a.Location)
			return nil, nil
		}
		return nil, trace.Wrap(err)
	}
```

**Review by ryanclark — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
