### PR TITLE
Deflake TestProxyWatcher

### LINKED ISSUE #18311: `TestProxyWatcher` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/bb24fd75-755e-40c0-9e74-f632fc7ca656;step=0?project=ci-account

#### Relevant snippet

```
=== RUN   TestProxyWatcher
    watcher_test.go:143: 
        	Error Trace:	/workspace/lib/services/watcher_test.go:143
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestProxyWatcher
--- FAIL: TestProxyWatcher (0.05s)
```

Seems flaky in CI but it also seems to fail 100% of the time for me locally on master. Git bisect points to https://github.com/gravitational/teleport/commit/514bfc7ac6f01f928218de3ee1c0642c337cba67 as first introducing the failure.

### PR DESCRIPTION
**Pull request by rosstimothy**
Changes the ProxyWatcher to only emit an empty proxy list if the watcher has already been initialized. This prevents an empty set of proxies from being emitted after the creation of the watcher, but allows an empty list to be emitted if the proxies become zero during the life of the watcher.

Closes #18311

### CODE REVIEW

**Review by mdwn — APPROVED** [review]

File: lib/services/watcher.go [hunk 1]
```diff
@@ -462,6 +466,15 @@ func (p *proxyCollector) initializationChan() <-chan struct{} {
...
 }
 
+func (p *proxyCollector) isInitialized() bool {
+	select {
+	case <-p.initializationC:
+		return true
+	default:
+		return false
+	}
+}
```
Comment (ibeckermayer) [inline lib/services/watcher.go:476]: I'm not familiar with this part of the codebase, but at first look it seems like this might disrupt the logic here
https://github.com/gravitational/teleport/blob/eb48c8ef55b6714df95fe2673a4a25f4cf7eb3de/lib/services/watcher.go#L181

because `initializationC` is only ever written to once

https://github.com/gravitational/teleport/blob/eb48c8ef55b6714df95fe2673a4a25f4cf7eb3de/lib/services/watcher.go#L411-L416

**Review by ibeckermayer — APPROVED** [review]

File: lib/services/watcher.go (hunk 1 above)
Comment (ibeckermayer) [reply lib/services/watcher.go:476]: TIL that `close` behavior is different from `send`

https://go.dev/play/p/z932MncG1MV

**Review by nklaassen — APPROVED** [review]

**Comment by mdwn** [comment]
Hey all, I might have another approach to this. I was able to steadily reproduce this issue by propagating the fake clock in the test -- I have a PR including a fix to this if you're interested in preserving the existing behavior.
