### PR TITLE
fix jira error parsing

### LINKED ISSUE #38231: Jira plugin fails to unmarshal errors from Jira API
Expected behavior:
When the Jira API returns errors we should log them or return them to the user

Current behavior:
We get a log like this, which isn't helpful when trying to debug the issue:
```
"caller":"jira/app.go:270","component":"jira","error":"json: cannot unmarshal object into Go struct field ErrorResult.Errors of type []string","level":"error","message":"Failed to process request","plugin_name":"jira","plugin_type":"jira"
```

[here](https://github.com/gravitational/teleport/blob/ddeec3db91c3b29edffe048e502827c5a2c4f406/integrations/access/jira/client.go#L107) we configure the client to unmarshal errors into an `ErrorResult`, defined here https://github.com/gravitational/teleport/blob/ddeec3db91c3b29edffe048e502827c5a2c4f406/integrations/access/jira/types.go#L23-L26

`ErrorResult.Errors` there has type `[]string`, but according to the [schema](https://docs.atlassian.com/software/jira/docs/api/REST/1000.1223.0/#error-responses) from Jira it will be a JSON object. We should either fix the type of `ErrorResult.Errors` or just remove it and only use `ErrorResult.ErrorMessages`

Bug details:
- Teleport version
  - The hosted Jira plugin has been included in the Teleport repo since 14.0.0 with this incorrect schema, it was probably wrong before that too
- Recreation steps
  - Try to set up the hosted Jira plugin in a Cloud tenant
  - Make it return an error somehow, possibly by creating the Jira API token with the wrong permissions
- Debug logs

### PR DESCRIPTION
**Pull request by hugoShaka**
Fixes https://github.com/gravitational/teleport/issues/38231

Changelog: Make the Jira access plugin log Jira errors properly.

### CODE REVIEW

File: integrations/access/jira/types.go [hunk 1]
```diff
@@ -18,11 +18,76 @@
...
+// https://docs.atlassian.com/software/jira/docs/api/REST/1000.1223.0/#error-responses
+// However JIRA does not consistently respect the schema (especially for old instances).
+// We need to support legacy errors as well (array of strings).
 type ErrorResult struct {
 	ErrorMessages []string `url:"errorMessages"`
-	Errors        []string `url:"errors"`
+	Errors        Errors   `url:"errors"`
+}
+
+func (e ErrorResult) String() string {
```
[the remark this answers is not in the document]
Comment (hugoShaka) [reply integrations/access/jira/types.go]: Done in 34eed06b6df64babca0c719ea1e495ae923a33cd

File: integrations/access/jira/types_test.go [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+import (
+	"encoding/json"
+	"testing"
+
+	"github.com/google/go-cmp/cmp"
+	"github.com/google/go-cmp/cmp/cmpopts"
+	"github.com/stretchr/testify/require"
+)
+
+func TestErrorResultUnmarshall(t *testing.T) {
```
Comment (zmb3) [inline integrations/access/jira/types_test.go:30]:
```suggestion
func TestErrorResultUnmarshal(t *testing.T) {
```

**Review by zmb3 — APPROVED** [review]

File: integrations/access/jira/types.go [hunk 3]
```diff
@@ -18,11 +18,79 @@
...
+	ErrorMessages []string     `url:"errorMessages"`
+	Details       ErrorDetails `url:"errors"`
+}
+
+// Error implements the error interface and returns a string describing the
+// error returned by Jira.
+func (e ErrorResult) Error() string {
+	sb := strings.Builder{}
+	if len(e.ErrorMessages) > 0 {
+		sb.WriteString(fmt.Sprintf("error messages: %s ", e.ErrorMessages))
```
Comment (r0mant) [inline integrations/access/jira/types.go:46]: Nit: Should we maybe `string.Join(e.ErrorMessages, ";")` or something like this here?

File: integrations/access/jira/types.go [hunk 4]
```diff
@@ -18,11 +18,79 @@
...
+	}
+	if details := e.Details.String(); details != "" {
+		sb.WriteString(fmt.Sprintf("error details: %s", details))
+	}
+	result := sb.String()
+	if result == "" {
+		return "Unknown jira error"
```
Comment (r0mant) [inline integrations/access/jira/types.go:53]:
```suggestion
		return "Unknown Jira error"
```

File: integrations/access/jira/types.go [hunk 5]
```diff
@@ -18,11 +18,79 @@
...
+	// Try to parse as a legacy error
+	var legacyErrors []string
+	if err := json.Unmarshal(data, &legacyErrors); err == nil {
+		e.LegacyErrors = legacyErrors
+		return nil
+	}
+
+	// Everything failed, we return an unrmarshalling error that contains the data.
+	// This way, even if everything failed, the user still has the original response in the logs.
+	return trace.Errorf("Failed to unmarshall Jira error: %q", string(data))
```
Comment (r0mant) [inline integrations/access/jira/types.go:82]:
```suggestion
	return trace.Errorf("Failed to unmarshal Jira error: %q", string(data))
```

File: integrations/access/jira/types.go [hunk 6]
```diff
@@ -18,11 +18,79 @@
...
+		return "Unknown jira error"
+	}
+	return result
+}
+
+// ErrorDetails are used to unmarshall inconsistently formatted Jira errors
+// details.
+type ErrorDetails struct {
+	Errors       map[string]string
+	LegacyErrors []string
```
Comment (r0mant) [inline integrations/access/jira/types.go:62]: Nit: Godocs here would be helpful explaining how "legacy errors" differ from "errors" and why would Jira return them differently.

**Review by r0mant — APPROVED** [review]

File: integrations/access/jira/types.go (hunk 3 above)
Comment (hugoShaka) [reply integrations/access/jira/types.go:46]: I always find those hard to read when multiple error happen, I'd prefer JSON-style array for those, which is done natively by Sprintf %s.

File: integrations/access/jira/types.go [hunk 7]
```diff
@@ -18,11 +18,86 @@
...
+// ErrorDetails are used to unmarshall inconsistently formatted Jira errors
+// details.
+type ErrorDetails struct {
+	// errors contain object-formatted Jira errors. Usually Jira returns
+	// errors in an object where keys are single word representing what is
+	// broken, and values containing text descrption of the issue.
+	// This is the official return format, according to Jira's docs.
+	errors map[string]string
+	// legacyErrors ensures backward compatibility with Jira errors returned as
+	// a list. It's unclear wich Jira version and which part of jira can return
```
Comment (hugoShaka) [inline integrations/access/jira/types.go:67]:
```suggestion
	// a list. It's unclear which Jira version and which part of jira can return
```

File: integrations/access/jira/types.go (hunk 3 above)
Comment (marcoandredinis) [reply integrations/access/jira/types.go:46]: I'm not sure about the error messages format (do they include some punctuation?), but adding a join char should help with readability.
Otherwise we might end up with a long string without knowing where a particular ErrorMessage starts and where it ends
Eg
```
V=[issue invalid format error]
using join=issue invalid; format error
```

**Review by marcoandredinis — APPROVED** [review]

File: integrations/access/jira/client.go [hunk 8]
```diff
@@ -131,7 +131,7 @@ func NewJiraClient(conf JiraConfig, clusterName, teleportProxyAddr string, statu
 				if resp.IsError() {
 					switch result := resp.Error().(type) {
 					case *ErrorResult:
-						return trace.Errorf("http error code=%v, errors=[%v]", resp.StatusCode(), strings.Join(result.ErrorMessages, ", "))
+						return trace.Errorf("http error code=%v, errors=[%s]", resp.StatusCode(), result)
 					case nil:
 						return nil
 					default:
```
[the remark this answers is not in the document]
Comment (hugoShaka) [reply integrations/access/jira/client.go:137]: I think this should be unreachable, but I'm quite afraid of breaking something 😓
