### PR TITLE
Fix interleaved output from `tsh ssh` on multiple nodes

### LINKED ISSUE #21089: `TestIntegrations/CmdLabels` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695

#### Relevant snippet

```
integration_test.go:5237: 
[976](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:977)
        	Error Trace:	/__w/teleport/teleport/integration/integration_test.go:5237
[977](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:978)
        	Error:      	Received unexpected error:
[978](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:979)
        	            	failed connecting to node 00000000-0000-0000-0000-000000000000. Teleport proxy failed to connect to "node" agent "" over reverse tunnel:
[979](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:980)
        	            	
[980](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:981)
        	            	  no tunnel connection found: no node reverse tunnel for 00000000-0000-0000-0000-000000000000.local-site found
[981](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:982)
        	            	
[982](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:983)
        	            	This usually means that the agent is offline or has disconnected. Check the
[983](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:984)
        	            	agent logs and, if the issue persists, try restarting it or re-registering it
[984](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:985)
        	            	with the cluster.
[985](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:986)
        	Test:       	TestIntegrations/CmdLabels/Worker_only
[986](https://github.com/gravitational/teleport/actions/runs/4067295252/jobs/7004473695#step:6:987)
        --- FAIL: TestIntegrations/CmdLabels/Worker_only (1.14s)```

### PR DESCRIPTION
**Pull request by atburke**
This change fixes an occasional bug where output from a command run on multiple nodes would interleave, making it harder to read. The client now:
- buffers output from each node and only prints complete lines (under a lock)
- wraps lines to the width of the terminal when possible so we don't buffer an arbitrarily large amount of output

Resolves #21089.

### CODE REVIEW

File: integration/integration_test.go [hunk 1]
```diff
@@ -6160,6 +6160,19 @@ func testList(t *testing.T, suite *integrationTestSuite) {
 	}
 }
 
+func containsSubsequence(s, subseq string) bool {
```
Comment (zmb3) [inline integration/integration_test.go:6163]: Can you add a godoc to this? It's not clear to me how it differs from a standard `strings.Contains`.

File: lib/client/client.go [hunk 2]
```diff
@@ -419,28 +419,42 @@ func (c *NodeClient) RunInteractiveShell(ctx context.Context, mode types.Session
...
+	w             io.Writer
+	maxLineLength int
+
+	shouldWritePrefix   bool
+	currentLineProgress int
 }
 
-func newLineLabeledWriter(w io.Writer, label string) io.Writer {
+func newLineLabeledWriter(w io.Writer, label string, maxLineLength int) (io.Writer, error) {
+	prefix := []byte(fmt.Sprintf("[%v] ", label))
```
Comment (capnspacehook) [inline lib/client/client.go:431]: nit: `fmt.Sprintf` is necessary here IMO as `label` is guaranteed to be a string and the format string is so simple

```suggestion
	prefix := "[" + label + "] "
```

**Review by capnspacehook — APPROVED** [review]

**Comment by atburke** [comment]
@espadolini Thanks for your patience on this one, it's finally ready for another look.

File: lib/client/api.go [hunk 3]
```diff
@@ -2747,6 +2749,28 @@ func (tc *TeleportClient) runCommandOnNodes(ctx context.Context, clt *ClusterCli
...
+		}
+		var ctrlErr error
+		err = conn.Control(func(fd uintptr) {
+			width, _, ctrlErr = term.GetSize(int(fd))
+		})
+		if err != nil {
+			return trace.Wrap(err)
+		} else if ctrlErr != nil {
+			return trace.Wrap(ctrlErr)
+		}
```
Comment (espadolini) [inline lib/client/api.go:2768]: Swap the two variables?
```suggestion
		ctrlErr := conn.Control(func(fd uintptr) {
			width, _, err = term.GetSize(int(fd))
		})
		if ctrlErr != nil {
			return trace.Wrap(ctrlErr)
		} else if err != nil {
			return trace.Wrap(err)
		}
```

File: lib/client/api.go [hunk 4]
```diff
@@ -2747,6 +2749,28 @@ func (tc *TeleportClient) runCommandOnNodes(ctx context.Context, clt *ClusterCli
...
+	}
+
+	stdout := logutils.NewSharedWriter(tc.Stdout)
+	stderr := logutils.NewSharedWriter(tc.Stderr)
```
Comment (espadolini) [inline lib/client/api.go:2772]:
```suggestion
	stdout := logutils.NewSharedWriter(tc.Stdout)
	stderr := stdout
	if tc.Stderr != tc.Stdout {
		stderr = logutils.NewSharedWriter(tc.Stderr)
	}
```

File: lib/client/api.go [hunk 5]
```diff
@@ -2747,6 +2749,28 @@ func (tc *TeleportClient) runCommandOnNodes(ctx context.Context, clt *ClusterCli
...
+	// Get the width of the terminal so we can wrap properly.
+	var width int
+	if stdoutFile, ok := tc.Stdout.(*os.File); ok {
+		conn, err := stdoutFile.SyscallConn()
+		if err != nil {
+			return trace.Wrap(err)
+		}
+		var ctrlErr error
+		err = conn.Control(func(fd uintptr) {
+			width, _, ctrlErr = term.GetSize(int(fd))
```
Comment (espadolini) [inline lib/client/api.go:2762]: This can fail if the output isn't a terminal - do we know for sure that it is, at this point?

**Review by espadolini — APPROVED** [review]
Pretty good! 👍 

Does it behave appropriately when redirecting stdout, stderr or both to the same and to different files?
