### PR TITLE
Teleterm: fix incorrect cluster URI when fetching kube namespaces on a leaf cluster (access request)

### LINKED ISSUE #48510: Selecting kube namespace for access request in Connect sources cluster URI from wrong place
https://github.com/gravitational/teleport/blob/ee1726ef684b7162de241ba63674cfdcdbfe074b/web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.ts#L401-L417

`fetchKubeNamespaces` uses `clusterUri` to query for namespaces. However, `clusterUri` comes from the cluster selector to the left of the search bar, present only if there are leaf clusters. If someone adds root kube cluster to a request and then goes to browse a leaf Teleport cluster, then opens the checkout and tries to modify requested namespaces, that request is going to either fail or return wrong data. Unless both the root cluster and the leaf cluster have a kube cluster with the same name and the same namespaces.

To fix this, `fetchKubeNamespaces` would at least need to provide the name of the cluster that the kube cluster belongs to. Ideally, the shared components in access requests would operate on some kind of URIs so that a single identifier points at a specific kube cluster.

On top of that, [the `ListKubernetesResourcesRequest` gRPC message](https://github.com/gravitational/teleport/blob/ee1726ef684b7162de241ba63674cfdcdbfe074b/proto/teleport/lib/teleterm/v1/service.proto#L323-L345) should operate on a single `kubeClusterUri` to identify the kube cluster, not on a combo of `cluster_uri` + `kubernetes_cluster`. This is possible today without any changes to the shared access request components.

### PR DESCRIPTION
**Pull request by kimlisa**
resolves https://github.com/gravitational/teleport/issues/48510

- teleterm: fixes fetching namespaces with incorrect cluster URI when on leaf cluster. we already had the correct URI info from the kube_cluster's `originalItem`, so i just used that
- teleterm: fixes re-ordering of selected namespaces when done selecting. this is only half fixed. it's fixed for `teleterm` but not for web UI. teleterm uses a set, while web UI still uses a map (which doesn't preserve order). web UI really needs an entire data refactor, but i didn't deem this little quirk to be bad enough to spend time on it

changelog: Fix incorrect cluster name when querying for Kubernetes namespaces on a leaf cluster for Connect UI.

### CODE REVIEW

**Comment by kimlisa** [comment]
@ravicious also gave feedback on removing the `nextKey`, but i didn't think it hurt to be there, b/c what if we did want to provide pagination in the future? i can remove it if it still bothers you though

File: lib/teleterm/daemon/daemon.go [hunk 1]
```diff
@@ -822,8 +823,10 @@ func (s *Service) ListKubernetesResources(ctx context.Context, clusterURI uri.Re
 			UseSearchAsRoles:    req.GetUseSearchAsRoles(),
 			KubernetesCluster:   req.GetKubernetesCluster(),
 			KubernetesNamespace: req.GetKubernetesNamespace(),
-			TeleportCluster:     cluster.Name,
-		})
+			TeleportCluster:     tc.SiteName,
+		}
+
+		resources, err = apiclient.GetKubernetesResourcesWithFilters(ctx, kubeServiceClient, req)
```
Comment (gzdunek) [inline lib/teleterm/daemon/daemon.go:829]: Just curious, what's the reason behind this change?

File: web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx [hunk 2]
```diff
@@ -141,10 +141,9 @@ export function KubeNamespaceSelector({
   }
 
   return (
-    <Box width="100%" mb={-3}>
+    <Box width="100%" mb={-3} mt={2}>
       <StyledSelect
-        label={`Namespaces`}
```
Comment (gzdunek) [inline web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx:146]: What about the label?

File: web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx [hunk 3]
```diff
@@ -102,34 +91,25 @@ export function KubeNamespaceSelector({
...
-        clusterName: kubeClusterItem.clusterName,
-        name: namespace,
-      })),
+    updateNamespacesForKubeCluster(
+      getPendingNamespaces(selectedOpts),
       kubeClusterItem
     );
   };
 
+  function getPendingNamespaces(
```
Comment (gzdunek) [inline web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx:100]: Maybe `optionsToKubeNamespaces`?

File: web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx [hunk 4]
```diff
@@ -283,3 +288,147 @@ test('after creating an access request, pending requests and specifiable fields
     });
   });
 });
+
+test(`updating kube namespaces`, async () => {
```
Comment (gzdunek) [inline web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx:309]:
```suggestion
test('updating kube namespaces', async () => {
```

File: web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx [hunk 5]
```diff
@@ -283,3 +288,147 @@ test('after creating an access request, pending requests and specifiable fields
...
+          clusterName: 'local',
+          id: kube1.name,
+          name: 'n1',
+          subResourceName: 'n1',
+        },
+      ],
+      kubeItem
+    );
+
+    const savaedRequestIds = result.current.pendingAccessRequests
```
Comment (gzdunek) [inline web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx:377]:
```suggestion
    const savedRequestIds = result.current.pendingAccessRequests
```

File: web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx [hunk 6]
```diff
@@ -283,3 +288,147 @@ test('after creating an access request, pending requests and specifiable fields
...
+          clusterName: 'local',
+          id: kube1.name,
+          name: 'n3',
+          subResourceName: 'n3',
+        },
+      ],
+      kubeItem
+    );
+
+    const savaedRequestIds = result.current.pendingAccessRequests
```
Comment (gzdunek) [inline web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx:412]:
```suggestion
    const savedRequestIds = result.current.pendingAccessRequests
```

File: web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts [hunk 7]
```diff
@@ -99,34 +99,40 @@ export class AccessRequestsService {
     });
   }
 
-  async addOrRemoveKubeNamespaces(namespaceUris: KubeResourceNamespaceUri[]) {
+  async updateNamespacesForKubeCluster(
+    namespaceUris: KubeResourceNamespaceUri[],
+    kubeClusterUri: string
```
Comment (gzdunek) [inline web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts:104]: So we need `kubeClusterUri` to validate if all namespaceUris come from the same kube cluster? 
It feels to me too complicated, perhaps we shouldn't store namespace uris but just their names.
Since a namespace is always kept in a specific kube cluster, we don't need its whole uri.
So it would be:
```ts
async updateNamespacesForKubeCluster(
    kubeUri: KubeUri
    namespaces: string[],
)
```

File: lib/teleterm/daemon/daemon.go (hunk 1 above)
Comment (ravicious) [reply lib/teleterm/daemon/daemon.go:829]: `kubernetesServiceClient.ListKubernetesResources` fetches just a single page of resources. `api/client.GetKubernetesResourcesWithFilters` fetches everything.

File: web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts [hunk 8]
```diff
@@ -99,34 +99,40 @@ export class AccessRequestsService {
...
       if (draftState.pending.kind !== 'resource') {
         throw new Error('Cannot add a kube namespace to a role access request');
       }
 
       const { resources } = draftState.pending;
 
+      // Validate each namespace uri's.
       namespaceUris.forEach(resourceUri => {
-        const requestedResource = resources.get(
+        const kubeRequestedResource = resources.get(
```
[the remark this answers is not in the document]
Comment (ravicious) [reply web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts:115]: But maybe we could partially follow Grzegorz's advice, but instead of dropping namespace URIs, we could drop `kubeClusterUri` as an arg of this specific method of `AccessRequestsService`. At this layer, we just need namespace URIs alone.

Then we could convert them all to a kube cluster URI, put them in a set, check if its length is 1 (this ensures all namespace URIs point to a single cluster) and then we're pretty much set.

File: web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx [hunk 9]
```diff
@@ -283,3 +288,147 @@ test('after creating an access request, pending requests and specifiable fields
...
+      kind: 'kube',
+      resource: {
+        uri: kube1.uri,
+      },
+    },
+  };
+
+  // Test order of request are retained.
+  await waitFor(() => {
+    result.current.updateNamespacesForKubeCluster(
```
[the remark this answers is not in the document]
Comment (kimlisa) [reply web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx:350]: thanks, i replaced with act

File: web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (kimlisa) [reply web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts:115]: > Instead, I'd implement something similar to routing.belongsToProfile, e.g., routing.belongsToKubeCluster which checks if two URIs point to something under the same kube cluster. Then you could check if each URL in the array belongs to the cluster that kubeClusterUri points to.

i wasn't sure i understood, but doesn't this (code below) already do what you suggested? (or do you mean like pull it out into its function?)

```ts
namespaceUris.forEach(namespaceUri => {
        const namespaceKubeResource = resources.get(
          routing.getKubeUri(
            routing.parseKubeResourceNamespaceUri(namespaceUri).params
          )
        );
        if (namespaceKubeResource.resource.uri != kubeClusterUri) {
          throw new Error(
            'Only namespace belonging to the same requested kube cluster can be updated'
          );
        }
      });
```

> we could drop kubeClusterUri as an arg of this specific method of AccessRequestsService

hrm... but what if a namespace was cleared? i would still need to know the kube cluster URI to get to the namespaces b/c my list of namespaces will be empty:

```ts
      const kubeRequestedResource = resources.get(kubeClusterUri);   // here
      if (kubeRequestedResource.kind === 'kube') {
        kubeRequestedResource.resource.namespaces = new Set(namespaceUris);  // namespaceUris could be empty
      }
```

File: web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx
[the remark this answers is not in the document]
Comment (kimlisa) [reply web/packages/shared/components/AccessRequests/NewRequest/RequestCheckout/KubeNamespaceSelector.tsx:1]: no it's just a js object, now that you mention it... maybe it will be easy to just replace it with a js map (but not in this PR)

File: lib/teleterm/apiserver/handler/handler_kubes.go
Comment (ravicious) [inline lib/teleterm/apiserver/handler/handler_kubes.go:1]: > @ravicious also gave feedback on removing the `nextKey`, but i didn't think it hurt to be there, b/c what if we did want to provide pagination in the future? i can remove it if it still bothers you though

I think we should just remove it to signify that the RPC does not offer pagination. If we ever need to add it back, we can create `ListKubernetesResourcesV2`. I wouldn't want someone to look at the response message and think that the RPC supports pagination.

File: web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx [hunk 10]
```diff
@@ -230,83 +230,86 @@ test('after creating an access request, pending requests and specifiable fields
     wrapper,
   });
 
-  await waitFor(() => {
-    result.current.setSelectedReviewers([{ value: 'bob', label: 'bob' }]);
-    expect(result.current.selectedReviewers).toEqual([
-      { value: 'bob', label: 'bob' },
-    ]);
-  });
+  await act(() =>
```
Comment (ravicious) [inline web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx:233]: `await` on `act` is not necessary, unless the callback passed to `act` returns a promise. This is the case for a lot of `await act` in this file. TypeScript's lang server should highlight all of them if you have it enabled in your editor. There's also the `@typescript-eslint/await-thenable` rule, but enabling it requires adjusting the ESLint config a little bit.

File: web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (ravicious) [reply web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts]: > > Instead, I'd implement something similar to routing.belongsToProfile, e.g., routing.belongsToKubeCluster which checks if two URIs point to something under the same kube cluster. Then you could check if each URL in the array belongs to the cluster that kubeClusterUri points to.
> 
> i wasn't sure i understood, but doesn't this (code below) already do what you suggested? (or do you mean like pull it out into its function?)

It does, but:

1. We take `namespaceUri` and convert it to a kube cluster URI
2. Then we `resources.get` with that URI
3. Then we look at `namespaceKubeResource.resource.uri`

Aren't the last two steps unnecessary? We can convert straight from from `namespaceUri`  to a kube cluster URI and compare it against `kubeClusterUri`.

On top of that, since there's no `routing.ensureKubeUri`, you have to manually call `routing.parseKubeResourceNamespaceUri` and `routing.getKubeUri` _and then_ you have to assing the result to a variable – otherwise the code would appear too busy.

This poses a problem – how are you going to name that intermediate variable? `namespaceKubeClusterUri`? This make it seem like it's a URI for a namespace. `kubeClusterUri` is already taken. `kubeClusterUriFromNamespaceUri` is a bit lengthy.

If you had `routing.ensureKubeUri`, you could write this:

```typescript
        if (routing.ensureKubeUri(namespaceUri) != kubeClusterUri) {
          throw new Error(
            'Only namespace belonging to the same requested kube cluster can be updated'
          );
        }
```

This could be taken one step further and we could add `routing.belongsToKube` (similar to `routing.belongsToProfile`:

```typescript
        if (routing.belongsToKube(kubeClusterUri, namespaceUri) {
          throw new Error(
            'Only namespace belonging to the same requested kube cluster can be updated'
          );
        }
```

[the remark this answers is not in the document]
Comment (ravicious) [reply web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts]: > > we could drop kubeClusterUri as an arg of this specific method of AccessRequestsService
> 
> hrm... but what if a namespace was cleared? i would still need to know the kube cluster URI to get to the namespaces b/c my list of namespaces will be empty:

Good point, I forgot that this might be the case.

**Review by ravicious — APPROVED** [review]
I tested this against #48510 and the repro for selection order from https://github.com/gravitational/teleport/pull/47347#discussion_r1812814366 and it works for both.

File: web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts
Comment (ravicious) [inline web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts:1]: @gzdunek In the test for `useAccessRequestCheckout` I noticed that we await a few methods from `AccessRequestsService`. I looked at them and it's because they do this:

```typescript
    if (!(await this.canUpdateRequest('resource'))) {
      return;
    }
```

I think making those methods async might have been a mistake. This layer should be kept as simple as possible and `canUpdateRequest` could be taken care of one layer above, on a layer that has access to both `AccessRequestsService` _and_ `ModalsService`. Like in some kind of a hook or a context.

This would reduce coupling between services and avoid async methods in a class that's largely responsible for just managing some state.

I know we use async methods in `WorkspacesService` already, but that class is in a bit of a mess itself. `ClustersService`'s usage of async methods feels better because it's all about getting data and storing data. The way `WorkspacesService` and `AccessRequestsService` use async methods mixes together the data layer and the UI layer.

File: web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts (hunk 7 above)
Comment (gzdunek) [reply web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts:104]: >If we stored sole namespace names, we'd have to always remember about converting them to URIs when taking them out of AccessRequestsService.

Right, converting to URI could be inconvenient. Well, I don't have a strong opinion on this, so let's keep it as is.

File: web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (gzdunek) [reply web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts]: I like the idea of `routing.belongsToKube(kubeClusterUri, namespaceUri)`.

File: web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts
Comment (gzdunek) [reply web/packages/teleterm/src/ui/services/workspacesService/accessRequestsService.ts:1]: I think my reasoning was to have a centralized place where changing request type is handled. But yeah, it would be better to do it on a different level, and `AccessRequestsService` should just overwrite the existing state with the new request (e.g. when trying to add role to a resource request etc).
I will keep that mind.

**Review by gzdunek — APPROVED** [review]

File: web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx (hunk 10 above)
Comment (kimlisa) [reply web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx:233]: hrm, i actually do need them in almost all cases, b/c most are react state setters which are async? (the test fails without them)

Comment (ravicious) [reply web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx:233]: React state setters are technically sync and they don't need to be awaited. TS lang server highlights those callsites because `act` is given a sync function, so there's nothing to await.

The errors after removing `await` stem from the fact that `useAccessRequestCheckout` has an effect which fetches resource roles every time you change `pendingAccessRequestRequest`. This means each call to `updateNamespacesForKubeCluster` causes this effect to be run again.

At first I removed those await calls and added `waitFor` for `fetchResourceRolesAttempt`. But then I looked up [the docs for `act`](https://react.dev/reference/react/act#reference) and the React team actually recommends passing an async function to `act`. So I left the awaits, but I made sure that we always pass an async function there. This way the TS language server doesn't complain about those callsites.

Comment (ravicious) [reply web/packages/teleterm/src/ui/AccessRequestCheckout/useAccessRequestCheckout.test.tsx:233]: I made a PR with those changes: https://github.com/gravitational/teleport/pull/48969
