### PR TITLE
Mongo clients with `serverSelectionTimeoutMS` set to 5000

### LINKED ISSUE #13195: Mongo timeouts to Atlas from tsh db connect
Expected behavior:

A method of increasing the timeout to a MongoDB.  

Current behavior:

Users that connect via `tsh db connect` experience timeouts when connecting to Atlas.  This is more pronounced in Teleport Cloud even with AWS Global Balancing enabled.  The `tsh db connect` to a MongoDB atlas DB can experience timeouts since it defaults to `2000` ms in the `mongo` shell invocation.  Note that the direction  

Bug details:
- Teleport version 9.3.3
- Recreation steps

Open a MongoDB Atlas account.  Connect a Teleport cloud instance to it.  `tsh db connects` will connect w/o timing out half the time. 

- Debug logs

```
$ tsh db connect --db-user=mongouser  mongodb-atlas
Current Mongosh Log ID:	6298cf9b669c3e9914acf0d9
Connecting to:		mongodb://localhost:51230/?directConnection=true&serverSelectionTimeoutMS=2000&tls=true&tlsCertificateKeyFile=%2FUsers%2Fstevenmartinsr%2F.tsh%2Fkeys%2Fskyward.teleport.sh%2Fsteven-db%2Fskyward.teleport.sh%2Fmongodb-atlas-x509.pem&tlsCAFile=%2FUsers%2Fstevenmartinsr%2F.tsh%2Fkeys%2Fskyward.teleport.sh%2Fcas%2Fskyward.teleport.sh.pem&appName=mongosh+1.4.2
MongoServerSelectionError: Server selection timed out after 2000 ms
ERROR: exit status 1
```

### PR DESCRIPTION
**Pull request by greedy52**
fixes #13195 
- #13195 

Testing:
- `tsh db connect`
  - `mongosh`: works as expected, can use the env var to test scenarios
  - `mongo`: connects fine with provided URL but never times out - I think the client is ignoring the parameter. 
  - Tested with an empty or a specific database name. Both work as expected.
- `tsh proxy db --tunnel` works as expected

Note:
This is a temporary solution that tries to resolve most situations. Further investigation will be conducted to find why `tsh db connect` takes very long. 
Another temporary workaround that can be done by the user is to downgrade to old `mongo` client instead of using `mongosh`

### CODE REVIEW

File: lib/client/db/dbcmd/dbcmd.go [hunk 1]
```diff
@@ -413,6 +412,33 @@ func (c *CLICommandBuilder) getMongoCommand() *exec.Cmd {
 	return c.exe.Command(mongoBin, args...)
 }
 
+func (c *CLICommandBuilder) getMongoAddress() string {
+	query := make(url.Values)
+
+	// Use 5 seconds for server selection timeout to be more align with the
+	// backend. The environment variable serves as a hidden option to force a
+	// different timeout for debugging purpose or extreme situations.
+	serverSelectionTimeoutMS := "5000"
```
Comment (smallinsky) [inline lib/client/db/dbcmd/dbcmd.go:421]: Can we move the https://github.com/gravitational/teleport/blob/master/lib/srv/db/mongodb/connect.go#L209 to some common package and reuse it here ? I think that the CLI client selection timeout value and selection timeout in teleport mongo engine should be in sync.

File: lib/client/db/dbcmd/dbcmd.go [hunk 2]
```diff
@@ -413,6 +412,33 @@ func (c *CLICommandBuilder) getMongoCommand() *exec.Cmd {
...
+	if envValue := os.Getenv(envVarMongoServerSelectionTimeoutMS); envValue != "" {
+		c.options.log.Infof("Using environment variable %s=%s.", envVarMongoServerSelectionTimeoutMS, envValue)
+		serverSelectionTimeoutMS = envValue
+	}
+	query.Set("serverSelectionTimeoutMS", serverSelectionTimeoutMS)
+
+	address := url.URL{
+		Scheme:   "mongodb",
```
Comment (smallinsky) [inline lib/client/db/dbcmd/dbcmd.go:429]: nit:
```suggestion
		Scheme:  connstring.SchemeMongoDB,
```

File: lib/client/db/dbcmd/dbcmd.go [hunk 3]
```diff
@@ -413,6 +412,33 @@ func (c *CLICommandBuilder) getMongoCommand() *exec.Cmd {
...
+		Host:     fmt.Sprintf("%s:%d", c.host, c.port),
+		RawQuery: query.Encode(),
+		Path:     fmt.Sprintf("/%s", c.db.Database),
+	}
+
+	// Quote the address for printing as the address contains "?".
+	if c.options.printFormat {
+		return fmt.Sprintf(`"%s"`, address.String())
+	}
+	return address.String()
```
Comment (smallinsky) [inline lib/client/db/dbcmd/dbcmd.go:439]: Don't we need to quote the connectionString to mitigate shell parsing errors ? 
So instead of invoking `mongosh mongodb://localhost:12345/mydb?serverSelectionTimeoutMS=5000` we   should alywas call `mongosh "mongodb://localhost:12345/mydb?serverSelectionTimeoutMS=5000"` even if TLS routing is disabled ?

Comment (greedy52) [reply lib/client/db/dbcmd/dbcmd.go:440]: quoted URL will fail `exec.Cmd.Run` as clients sees the quotation as invalid URL. 

I tested this with Teleport Connect today and I've added `WithPrintFormat` for it to make sure postgres and mongo connection urls are quoted.

after fix:
Screen Shot 2022-06-23 at 10 29 58 AM

I've also added @ravicious for review on that part.

**Review by smallinsky — APPROVED** [review]

**Review by ravicious — APPROVED** [review]
Tested this on a Connect build and I managed to successfully connect to my mongo instance.

**Comment by greedy52** [comment]
Thanks @ravicious for confirming =D
