### PR TITLE
Fix Client IP issues.

### LINKED ISSUE #2751: IP handling is broken in 4.x
## Problem 1: Node IPs

When Teleport is used in "IoT mode", node IPs become meaningless, i.e. 

```
$ tsh ls
Node Name Address         Labels    
--------- --------------- --------- 
mars      10.5.100.1:3022 env=stage 
moon      10.5.100.1:3022 env=stage 
smb       10.5.100.1:3022 env=prod  
sun       10.5.100.1:3022 env=prod  
```

See? Same IP. BTW the same issue with the web UI.
Also, I cannot SSH into my nodes using their IP addresses.

## Problem 2: Client IP

The client IP as reported in the audit log is not valid:

```
"event":"session.start",
"login":"ekontsevoy", 
"addr.local":"10.2.1.159:39014",
"addr.remote":"172.16.0.1:38560"
```

In this case, `addr.local` is actually correct (!) - that's the IP of the host. But the "remote" IP, i.e. the machine I am accessing this from, is invalid. 

[edit] Looks like the "remote" IP is broken even for non-IoT mode. It's always reporting `172.16.0.1` for me... not even sure where it's getting it from.

## Problem 3: Address Resolution

See comments ([at the bottom](https://github.com/gravitational/teleport/issues/803#issuecomment-497461251)) for #803. User @speeltronics is reporting that when he tries to connect to any "IoT node" he always lands onto a proxy (!).

### PR DESCRIPTION
**Pull request by russjones**
**Description**

Don't heartbeat address for nodes connected to clusters over a reverse tunnel. Print warning to users if `listen_addr` or `public_addr` are set as these are not used.

Pass connection to target node, even if it's a node connected over a reverse tunnel, to the forwarding server.

Fixes https://github.com/gravitational/teleport/issues/2751

### CODE REVIEW

File: lib/reversetunnel/localsite.go [hunk 1]
```diff
@@ -193,47 +183,35 @@ func (s *localSite) Dial(params DialParams) (net.Conn, error) {
...
-	dialer := proxy.DialerFromEnvironment(params.To.String())
-	return dialer.DialTimeout(params.To.Network(), params.To.String(), defaults.DefaultDialTimeout)
-}
-
 func (s *localSite) dialWithAgent(params DialParams) (net.Conn, error) {
 	s.log.Debugf("Dialing with an agent from %v to %v.", params.From, params.To)
 
-	// Get a host certificate for the forwarding node from the cache.
-	hostCertificate, err := s.certificateCache.GetHostCertificate(params.Address, params.Principals)
+	// If server ID matchs a node that has self registered itself over the tunnel,
```
Comment (r0mant) [inline lib/reversetunnel/localsite.go]: matches

File: lib/reversetunnel/localsite.go [hunk 2]
```diff
@@ -262,6 +242,47 @@ func (s *localSite) dialWithAgent(params DialParams) (net.Conn, error) {
...
+	conn, err := s.chanTransportConn(rconn)
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+
+	return conn, nil
+}
+
+func (s *localSite) getConn(params DialParams) (net.Conn, bool, error) {
+	// If server ID matchs a node that has self registered itself over the tunnel,
```
Comment (r0mant) [inline lib/reversetunnel/localsite.go]: matches

File: lib/reversetunnel/localsite.go [hunk 3]
```diff
@@ -262,6 +242,47 @@ func (s *localSite) dialWithAgent(params DialParams) (net.Conn, error) {
...
+
+	conn, err := s.chanTransportConn(rconn)
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+
+	return conn, nil
+}
+
+func (s *localSite) getConn(params DialParams) (net.Conn, bool, error) {
```
Comment (r0mant) [inline lib/reversetunnel/localsite.go]: Nit: Named return arguments would really help in this case, e.g. to understand what the bool parameter is.

File: lib/reversetunnel/transport.go [hunk 4]
```diff
@@ -186,10 +161,36 @@ func connectProxyTransport(sconn ssh.Conn, req *dialReq) (net.Conn, bool, error)
 	return utils.NewChConn(sconn, channel), false, nil
 }
 
-// proxyTransport runs either in the agent or reverse tunnel itself. It's
-// used to establish connections from remote clusters into the main cluster
-// or for remote nodes that have no direct network access to the cluster.
-func proxyTransport(p *transportParams) {
+// transport are used to build a connection to the target host.
```
Comment (r0mant) [inline lib/reversetunnel/transport.go]: is used?

File: lib/reversetunnel/transport.go [hunk 5]
```diff
@@ -316,43 +324,72 @@ func proxyTransport(p *transportParams) {
...
+		select {
+		case req := <-p.requestCh:
+			if req == nil {
+				return
+			}
+			switch req.Type {
+			case utils.ConnectionTypeRequest:
+				err := req.Reply(useTunnel, nil)
+				if err != nil {
+					logrus.Debugf("Failed to reply to %v request: %v.", req.Type, err)
```
Comment (r0mant) [inline lib/reversetunnel/transport.go]: `p.log.Debugf`? Same below.

File: lib/utils/fakeconn.go [hunk 6]
```diff
@@ -138,6 +139,31 @@ type ChConn struct {
...
+		}
+		responseCh <- ok
+	}()
+
+	for {
+		select {
+		case response := <-responseCh:
+			return response
+		case <-time.After(1 * time.Second):
+			return false
```
Comment (r0mant) [inline lib/utils/fakeconn.go]: Would it be helpful to log the timeout case?

File: tool/tsh/tsh.go [hunk 7]
```diff
@@ -621,13 +626,17 @@ func onListNodes(cf *CLIConf) {
 	case false:
 		t := asciitable.MakeTable([]string{"Node Name", "Address", "Labels"})
 		for _, n := range nodes {
+
```
Comment (r0mant) [inline tool/tsh/tsh.go]: Nit: Extra empty line.

File: lib/utils/fakeconn.go [hunk 8]
```diff
@@ -138,6 +139,31 @@ type ChConn struct {
...
+	go func() {
+		ok, err := c.SendRequest(ConnectionTypeRequest, true, nil)
+		if err != nil {
+			responseCh <- false
+			return
+		}
+		responseCh <- ok
+	}()
+
+	for {
```
Comment (r0mant) [inline lib/utils/fakeconn.go]: What's this `for` here for?

**Review by r0mant — APPROVED** [review]

**Comment by speeltronics** [comment]
I tried the latest master branch and still cannot get it to work. The device is showing on the main server now with the ip of the modem the device is connected to. However, I keep getting this error on the main server.

No valid environment variables found. proxy/proxy.go:217
Jun 13 14:17:40 Updates teleport[11066]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137

Tried to turn the proxy off on the client and also turned the proxy on with all the listen addresses commented out. Then tried to uncomment the  listen addresses one by one and tried it each time, but still didn't work. Even when I comment out the listen addresses, it looks like from the logs it defaults to using them anyways.

All the ports are open on my device 3022 3023 3024 3025 3080 and my main server which is on Digital Ocean. They are not open on my router. I wouldn't think they would need to be open on my device since I thought the device would create the tunnel to the server without having to open ports.

Anyways, if it is suppose to be working, it is probably just a config problem, but I have tried everything I can think to try. Do you have example config files that should work? Thanks!

File: lib/reversetunnel/localsite.go [hunk 9]
```diff
@@ -262,6 +242,47 @@ func (s *localSite) dialWithAgent(params DialParams) (net.Conn, error) {
...
+
+	conn, err := s.chanTransportConn(rconn)
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+
+	return conn, nil
+}
+
+func (s *localSite) getConn(params DialParams) (conn net.Conn, useTunnel bool, err error) {
```
Comment (klizhentas) [inline lib/reversetunnel/localsite.go]: @russjones Charn, instead of third parameter, please refactor this method to be more like this:

https://github.com/gravitational/teleport/commit/e3ca4df5fc1efb45e42809463b065fae5b76ddc8#diff-32cceab2787108fd6eadc9b8c982f4ff

Note that in my commit I had to remove the 'useTunnel` everywhere as it cluttered the code paths. Instead I made the 'useTunnel` to be a property of the connection to be used when necessary.

https://github.com/gravitational/teleport/commit/e3ca4df5fc1efb45e42809463b065fae5b76ddc8#diff-b2616f8fc5d7121127fe898e501d328dR176

@russjones please ack.
