### PR TITLE
Delete app sessions on logout

### LINKED ISSUE #9124: Explicitly end application access sessions on teleport gui sign out
### Description

**What happened**: When logging out of the teleport web UI, any teleport application access sessions remain valid.

**What you expected to happen**: Logging out of the teleport web UI should server-side invalidate all application access sessions immediately.

NIST 800-53r5 has AC12 and SC-23(1) that would support the behavior of logging out of the gui invalidating all sessions for that user on that browser.

We do provide _a_ way to log out of an individual application, one at a time by hitting `/teleport-logout` and this is [documented here](https://goteleport.com/docs/application-access/guides/connecting-apps/#logging-out-of-applications). This isn't enough on its own since a user cannot confidently know that they have no active session cookies for teleport resources after they click on the "sign out" button in teleport. This is especially true since the application access cookie is still valid after the browser tab is closed.

### Reproduction Steps

As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Log in to a teleport web gui.
2. Access any application access application.
3. Log out of teleport web gui.
4. Observe that you can still access the already open application.

### Server Details

- Teleport version (run `teleport version`): tested and observed on 7.2.0, 7.3.3, and 8.0.0
- Server OS (e.g. from `/etc/os-release`): N/A
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): kubernetes
- Additional details:

### Client Details

- Tsh version (`tsh version`): N/A
- Computer OS (e.g. Linux, macOS, Windows): N/A
- Browser version (for UI-related issues): Google Chrome 96.0.4664.45 on osx
- Installed via (e.g. apt, yum, brew, website download): N/A
- Additional details:

### Debug Logs

Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

### PR DESCRIPTION
**Pull request by gabrielcorado**
Closes #9124. It introduces a new gRPC endpoint, `DeleteUserAppSessions`, to delete all the user app sessions. This call is now being used on the logout flow. An integration test was added, it uses the reproduction steps described on the issue.

### CODE REVIEW

File: lib/auth/auth_with_roles.go [hunk 1]
```diff
@@ -3160,6 +3157,55 @@ func (a *ServerWithRoles) DeleteAllAppSessions(ctx context.Context) error {
...
+
+	sessions, err := a.authServer.GetAppSessions(ctx)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	for _, session := range sessions {
+		// The check is done against each session to avoid comparing user input
+		// with resources that the user doesn’t have access to.
+		if err := a.checkPermissionToDeleteUserWebSession(req.Username); err != nil {
```
Comment (rosstimothy) [inline lib/auth/auth_with_roles.go:3175]: This check is identical to the one on line 3163. How will this be any different inside this loop?

File: lib/auth/auth_with_roles_test.go [hunk 2]
```diff
@@ -110,7 +110,6 @@ func TestGenerateUserCertsWithRoleRequest(t *testing.T) {
 	require.NoError(t, err)
 
 	dummyUserRole, err := types.NewRole("dummy-user-role", types.RoleSpecV4{})
-	require.NoError(t, err)
```
Comment (rosstimothy) [inline lib/auth/auth_with_roles_test.go:113]: Was this accidental?

File: lib/auth/auth_with_roles_test.go [hunk 3]
```diff
@@ -1620,3 +1619,102 @@ func TestNoElevatedAccessRequestDeletion(t *testing.T) {
...
+		app, err := types.NewAppV3(types.Metadata{
+			Name: application.name,
+		}, types.AppSpecV3{
+			URI:        "localhost",
+			PublicAddr: application.publicAddr,
+		})
+		require.NoError(t, err)
+		server, err := types.NewAppServerV3FromApp(app, "host", uuid.New().String())
+		require.NoError(t, err)
+		_, err = srv.Auth().UpsertApplicationServer(context.Background(), server)
```
Comment (rosstimothy) [inline lib/auth/auth_with_roles_test.go:1666]:
```suggestion
		_, err = srv.Auth().UpsertApplicationServer(ctx, server)
```

File: lib/services/local/session_test.go [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+
+	"github.com/gravitational/teleport/api/client/proto"
+	"github.com/gravitational/teleport/api/types"
+
+	"github.com/google/uuid"
+	"github.com/stretchr/testify/require"
+)
+
+func TestDeleteUserAppSessions(t *testing.T) {
+	identity, clock := newIdentityService(t)
```
Comment (rosstimothy) [inline lib/services/local/session_test.go:30]: Create a local background context and replace all the `context.TODO` with it.

File: lib/auth/auth_with_roles.go (hunk 1 above)
Comment (gabrielcorado) [reply lib/auth/auth_with_roles.go]: It was wrong. The check here will be with the `session.GetUser()` instead of `req.Username`.

File: lib/auth/auth_with_roles.go [hunk 5]
```diff
@@ -3160,6 +3157,55 @@ func (a *ServerWithRoles) DeleteAllAppSessions(ctx context.Context) error {
...
+		if err := a.checkPermissionToDeleteUserWebSession(session.GetUser()); err != nil {
+			if trace.IsAccessDenied(err) {
+				continue
+			}
+
+			return trace.Wrap(err)
+		}
+
+		// A request will only delete web sessions from the `Username` provided.
+		if req.Username != session.GetUser() {
```
Comment (rosstimothy) [inline lib/auth/auth_with_roles.go:3184]: Should this check happen before `checkPermissionToDeleteUserWebSession`?

File: lib/web/sessions.go [hunk 6]
```diff
@@ -698,6 +698,9 @@ func (s *sessionCache) invalidateSession(ctx *SessionContext) error {
 	if err != nil && !trace.IsNotFound(err) {
 		return trace.Wrap(err)
 	}
+	if err := clt.DeleteUserAppSessions(context.Background(), &proto.DeleteUserAppSessionsRequest{Username: ctx.user}); err != nil {
```
Comment (rosstimothy) [inline lib/web/sessions.go:701]:
```suggestion
	if err := clt.DeleteUserAppSessions(context.TODO(), &proto.DeleteUserAppSessionsRequest{Username: ctx.user}); err != nil {
```

File: lib/auth/auth_with_roles.go [hunk 7]
```diff
@@ -3160,6 +3157,55 @@ func (a *ServerWithRoles) DeleteAllAppSessions(ctx context.Context) error {
...
+			return trace.Wrap(err)
+		}
+	}
+
+	return nil
+}
+
+// checkPermissionToDeleteUserWebSession checks if the current user can delete
+// WebSessions from the provided `username`.
+func (a *ServerWithRoles) checkPermissionToDeleteUserWebSession(username string) error {
```
Comment (r0mant) [inline lib/auth/auth_with_roles.go:3199]: Nit: A little too verbose I think, how about `canDeleteWebSession`?

File: lib/auth/auth_with_roles.go [hunk 8]
```diff
@@ -3160,6 +3157,55 @@ func (a *ServerWithRoles) DeleteAllAppSessions(ctx context.Context) error {
...
 }
 
+// DeleteUserAppSessions delete all user’s application sessions.
+func (a *ServerWithRoles) DeleteUserAppSessions(ctx context.Context, req *proto.DeleteUserAppSessionsRequest) error {
+	// First, check if the current user can delete the request user sessions.
+	if err := a.checkPermissionToDeleteUserWebSession(req.Username); err != nil {
+		return trace.Wrap(err)
+	}
+
+	sessions, err := a.authServer.GetAppSessions(ctx)
```
Comment (r0mant) [inline lib/auth/auth_with_roles.go:3167]: Can we either make a backend method that returns user's app sessions instead of checking `req.Username != session.GetUser()` below, or encapsulate it in the helper method? Something like `GetAppSessionsFor(ctx, <user>)`.

File: lib/auth/auth_with_roles.go [hunk 9]
```diff
@@ -3160,6 +3157,55 @@ func (a *ServerWithRoles) DeleteAllAppSessions(ctx context.Context) error {
...
+	if err != nil {
+		return trace.Wrap(err)
+	}
+
+	for _, session := range sessions {
+		// The check is done against each session to avoid comparing user input
+		// with resources that the user doesn’t have access to.
+		if err := a.checkPermissionToDeleteUserWebSession(session.GetUser()); err != nil {
```
Comment (r0mant) [inline lib/auth/auth_with_roles.go:3175]: Isn't this check redundant if we're only retrieving sessions for a particular user?

File: lib/auth/auth_with_roles.go [hunk 10]
```diff
@@ -3160,6 +3157,55 @@ func (a *ServerWithRoles) DeleteAllAppSessions(ctx context.Context) error {
...
+
+	return nil
+}
+
+// checkPermissionToDeleteUserWebSession checks if the current user can delete
+// WebSessions from the provided `username`.
+func (a *ServerWithRoles) checkPermissionToDeleteUserWebSession(username string) error {
+	if err := a.currentUserAction(username); err != nil {
+		if err := a.action(apidefaults.Namespace, types.KindWebSession, types.VerbDelete); err != nil {
+			return err
```
Comment (r0mant) [inline lib/auth/auth_with_roles.go:3202]:
```suggestion
			return trace.Wrap(err)
```

File: lib/services/local/session.go [hunk 11]
```diff
@@ -89,6 +90,27 @@ func (s *IdentityService) DeleteAppSession(ctx context.Context, req types.Delete
 	return nil
 }
 
+// DeleteAllAppSessions removes all application web sessions.
+func (s *IdentityService) DeleteUserAppSessions(ctx context.Context, req *proto.DeleteUserAppSessionsRequest) error {
```
Comment (r0mant) [inline lib/services/local/session.go:94]: Is this Identity method actually used anywhere? In the ACL layer we still delete each session individually AFAICS. Is it needed to just satisfy some interface?

**Review by r0mant — COMMENTED** [review]
@gabrielcorado With these changes, do we invalidate app sessions during password reset flow also?

**Review by smallinsky — COMMENTED** [review]
Right now the user app session can be either created by web UI and tsh app login. 
Wonder if an app session generated by `tsh app login` should affected by Web UI Logout handler ?

**Comment by gabrielcorado** [comment]
@rosstimothy @r0mant I've updated the logic to use `GetUserAppSessions` function internally, so the `DeleteUserAppSessions` doesn't need to filter sessions. Besides that, the `DeleteUserAppSessions` on the ACL layer now only checks user permission and calls the `DeleteUserAppSessions` from the backend.

@smallinsky As implemented, it will be affected (I added an integration test to validate that). Currently, I don't see any way of differentiating an AppSession created through Web or `tsh`. We could add a new field in the `WebSessionSpecV2` to identify where the session was created and pass this "origin" as a filter to `DeleteUserAppSessions`. What do you think?

File: lib/services/local/session.go (hunk 11 above)
Comment (gabrielcorado) [reply lib/services/local/session.go]: I've changed the implementation to use this function on the ACL layer.

File: api/client/client.go [hunk 12]
```diff
@@ -1093,6 +1093,12 @@ func (c *Client) DeleteAllAppSessions(ctx context.Context) error {
 	return trail.FromGRPC(err)
 }
 
+// DeleteUserAppSessions delete all user’s application sessions.
```
Comment (r0mant) [inline api/client/client.go:1096]:
```suggestion
// DeleteUserAppSessions deletes all user’s application sessions.
```

File: api/client/proto/authservice.proto [hunk 13]
```diff
@@ -1563,6 +1567,8 @@ service AuthService {
     rpc DeleteAppSession(DeleteAppSessionRequest) returns (google.protobuf.Empty);
     // DeleteAllAppSessions removes all application web sessions.
     rpc DeleteAllAppSessions(google.protobuf.Empty) returns (google.protobuf.Empty);
+    // DeleteUserAppSessions delete all user’s application sessions.
```
Comment (r0mant) [inline api/client/proto/authservice.proto:1570]:
```suggestion
    // DeleteUserAppSessions deletes all user’s application sessions.
```

File: integration/app_integration_test.go [hunk 14]
```diff
@@ -1175,38 +1232,38 @@ func (p *pack) createAppSession(t *testing.T, publicAddr, clusterName string) st
...
 	u := url.URL{
 		Scheme: "https",
 		Host:   net.JoinHostPort(Loopback, p.rootCluster.GetPortWeb()),
-		Path:   "/v1/webapi/sessions/app",
+		Path:   fmt.Sprintf("/v1/webapi/%s", endpoint),
+	}
+
+	req, err := http.NewRequest(method, u.String(), bytes.NewBuffer(payload))
+	if err != nil {
+		return 0, nil, err
```
Comment (r0mant) [inline integration/app_integration_test.go:1256]:
```suggestion
		return 0, nil, trace.Wrap(err)
```

File: integration/app_integration_test.go [hunk 15]
```diff
@@ -1175,38 +1232,38 @@ func (p *pack) createAppSession(t *testing.T, publicAddr, clusterName string) st
...
-	defer resp.Body.Close()
-	require.Equal(t, http.StatusOK, resp.StatusCode)
-
-	var casResp *web.CreateAppSessionResponse
-	err = json.NewDecoder(resp.Body).Decode(&casResp)
-	require.NoError(t, err)
-
-	return casResp.CookieValue
+	statusCode, body, err := p.sendRequest(req, nil)
+	return statusCode, []byte(body), err
```
Comment (r0mant) [inline integration/app_integration_test.go:1266]:
```suggestion
	return statusCode, []byte(body), trace.Wrap(err)
```

File: lib/auth/auth_with_roles.go [hunk 16]
```diff
@@ -3193,6 +3190,32 @@ func (a *ServerWithRoles) DeleteAllAppSessions(ctx context.Context) error {
 	return nil
 }
 
+// DeleteUserAppSessions delete all user’s application sessions.
```
Comment (r0mant) [inline lib/auth/auth_with_roles.go:3193]:
```suggestion
// DeleteUserAppSessions deletes all user’s application sessions.
```

File: lib/auth/auth_with_roles.go [hunk 17]
```diff
@@ -3193,6 +3190,32 @@ func (a *ServerWithRoles) DeleteAllAppSessions(ctx context.Context) error {
...
+	}
+
+	return nil
+}
+
+// canDeleteWebSession checks if the current user can delete
+// WebSessions from the provided `username`.
+func (a *ServerWithRoles) canDeleteWebSession(username string) error {
+	if err := a.currentUserAction(username); err != nil {
+		if err := a.action(apidefaults.Namespace, types.KindWebSession, types.VerbDelete); err != nil {
```
Comment (r0mant) [inline lib/auth/auth_with_roles.go:3211]: In the case where we're deleting all sessions, this should also check for VerbList on web sessions.

File: lib/services/identity.go [hunk 18]
```diff
@@ -266,6 +267,8 @@ type AppSession interface {
 	DeleteAppSession(context.Context, types.DeleteAppSessionRequest) error
 	// DeleteAllAppSessions removes all application web sessions.
 	DeleteAllAppSessions(context.Context) error
+	// DeleteUserAppSessions delete all user’s application sessions.
```
Comment (r0mant) [inline lib/services/identity.go:270]:
```suggestion
	// DeleteUserAppSessions deletes all user’s application sessions.
```

File: lib/services/local/session.go [hunk 19]
```diff
@@ -89,6 +90,40 @@ func (s *IdentityService) DeleteAppSession(ctx context.Context, req types.Delete
...
+	for _, session := range sessions {
+		if session.GetUser() == user {
+			userSessions = append(userSessions, session)
+		}
+	}
+
+	return userSessions, nil
+}
+
+// DeleteAllAppSessions removes all application web sessions.
```
Comment (r0mant) [inline lib/services/local/session.go:110]:
```suggestion
// DeleteAllAppSessions removes all application web sessions for a particular user.
```

File: lib/web/sessions.go [hunk 20]
```diff
@@ -698,6 +698,9 @@ func (s *sessionCache) invalidateSession(ctx *SessionContext) error {
 	if err != nil && !trace.IsNotFound(err) {
 		return trace.Wrap(err)
 	}
+	if err := clt.DeleteUserAppSessions(context.TODO(), &proto.DeleteUserAppSessionsRequest{Username: ctx.user}); err != nil {
```
Comment (r0mant) [inline lib/web/sessions.go:701]: Should we also do this when user does `tsh app logout` in the CLI?

**Review by r0mant — COMMENTED** [review]
Mostly looks good, just a few other comments/typos.

File: lib/web/sessions.go (hunk 20 above)
Comment (gabrielcorado) [reply lib/web/sessions.go:701]: Looking at the code, it does something similar by removing the application sessions one by one.

**Review by smallinsky — APPROVED** [review]

**Review by r0mant — APPROVED** [review]
@gabrielcorado Sorry for delay here, for some reason I thought we already merged this. Let's get this in and backport to v9 pls.
