### PR TITLE
Skip session recording reservation files (filessesion)

### LINKED ISSUE #13640: Warning - Skipped session recording
I see this warning printed in Teleport logs after closing SSH session:

```
2022-06-17T16:52:53-04:00 DEBU [UPLOAD]    Scanned 1 uploads, started 0 in /var/lib/teleport/log/upload/streaming/default. filesessions/fileasync.go:261
2022-06-17T16:52:58-04:00 WARN [UPLOAD]    Skipped session recording 4c8bb22a-a8f4-489c-bc8e-32ecd3730608.tar. error:[session file could be corrupted or is using unsupported format: session recording 4c8bb22a-a8f4-489c-bc8e-32ecd3730608 is either corrupted or is using unsupported format, remove the file /var/lib/teleport/log/upload/streaming/default/4c8bb22a-a8f4-489c-bc8e-32ecd3730608.tar to correct the problem, remove the /var/lib/teleport/log/upload/streaming/default/4c8bb22a-a8f4-489c-bc8e-32ecd3730608.error file to retry the upload] filesessions/fileasync.go:253
```
Files and the content:

```
$ sudo ls -la /var/lib/teleport/log/upload/streaming/default/
total 208
drwxr-xr-x 3 root root   4096 Jun 17 16:49 .
drwxr-xr-x 3 root root   4096 Jun 15 17:53 ..
-rw------- 1 root root      0 Jun 17 16:22 4c8bb22a-a8f4-489c-bc8e-32ecd3730608.checkpoint
-rw------- 1 root root     94 Jun 17 16:22 4c8bb22a-a8f4-489c-bc8e-32ecd3730608.error
-rw------- 1 root root 196608 Jun 17 16:22 4c8bb22a-a8f4-489c-bc8e-32ecd3730608.tar
drwx------ 2 root root   4096 Jun 17 16:49 multi
$ sudo cat /var/lib/teleport/log/upload/streaming/default/4c8bb22a-a8f4-489c-bc8e-32ecd3730608.error
session file could be corrupted or is using unsupported format: unsupported protocol version 0
```

Bug details:
- Teleport version: v10 alpha
- Recreation steps: Start and stop SSH session (error is not deterministic).
- Debug logs (attached)

### PR DESCRIPTION
**Pull request by gabrielcorado**
Closes #13640 by skipping reservation files when completing a session recording upload. To do so, now we create the reservation files with a different extension so we can differentiate them from regular upload parts.

### Context
[Session recording modes](https://github.com/gravitational/teleport/pull/12916) introduce ["disk reservation"](https://github.com/gravitational/teleport/blob/master/lib/events/api.go#L650-L652), where Teleport creates placeholder files to guarantee that the node has enough disk space to record sessions. This reservation happens every time a new part file is required. Those files are replaced with recording contents on the [`UploadPart`](https://github.com/gravitational/teleport/blob/master/lib/events/filesessions/filestream.go#L106) flow.

In scenarios where the upload couldn't run (for example, if the node is killed during a session), the reservation file was left on the node. When the [`UploadComplete`](https://github.com/gravitational/teleport/blob/master/lib/events/complete.go#L143) was executed, it created broken recording files (`.tar`), causing the uploads to fail (as we can see in the logs presented on the related issue).

### CODE REVIEW

File: lib/events/filesessions/filestream.go [hunk 1]
```diff
@@ -384,6 +395,46 @@ func checkUploadID(uploadID string) error {
...
 
+// generateReservationFileContent generates the content placed on the
+// reservation files.
+func generateReservationFileContents(partNumber int64) ([]byte, error) {
+	// Create a buffer with the max size that a part file can have.
+	buf := make([]byte, minUploadBytes+events.MaxProtoMessageSizeBytes)
+
+	// Encode reservation content.
+	encoded := &bytes.Buffer{}
+	encoder := gob.NewEncoder(encoded)
```
Comment (zmb3) [inline lib/events/filesessions/filestream.go:406]: What is going on here? Why do we need to introduce yet another encoding format?

Comment (gabrielcorado) [reply lib/events/filesessions/filestream.go:406]: I wasn't sure what encoding to use to identify those "reservation" files. First, I've added a Protobuf message, but it seemed like a little of an overkill for this since we're not using the data inside those messages. Do you think we should still use Protobuf for this, or do you have any other suggestions? The idea is to have some content on those files to differentiate them from regular session recording parts (Protobuf encoded).

Comment (espadolini) [reply lib/events/filesessions/filestream.go:406]: Why not just rename them to `<uuid>.reserve` or something along those lines?

**Comment by espadolini** [comment]
Side note: don't we lose the disk space reservation the moment we open the file for writing again in  [`openUploadPart`](https://github.com/gravitational/teleport/blob/3ffe935f478e51a339257464e5de0f0e28e398b6/lib/events/filesessions/filestream.go#L321)?

File: lib/events/filesessions/filestream.go (hunk 1 above)
Comment (gabrielcorado) [reply lib/events/filesessions/filestream.go:406]: > Why not just rename them to <uuid>.reserve or something along those lines?

I think that it is a good alternative because the [`ListParts`](https://github.com/gravitational/teleport/blob/3ffe935f478e51a339257464e5de0f0e28e398b6/lib/events/filesessions/filestream.go#L353) wouldn't recognize those files (not causing it to create broken session recordings) and they will be removed by the [`CompleteUpload`](https://github.com/gravitational/teleport/blob/master/lib/events/filesessions/filestream.go#L184).

**Comment by espadolini** [comment]
> Do you mean it because we truncate the file when opening?

Yes, as opposed to writing whatever content we need and then truncating before closing.

**Comment by gabrielcorado** [comment]
@zmb3 I've updated the PR with @espadolini suggestion: create the reservation files with a different extension, so we don't need to check their content.

> Yes, as opposed to writing whatever content we need and then truncating before closing.
I have updated the PR with this also. Thanks for pointing it out.

**Review by espadolini — APPROVED** [review]
Never mucked around the session recording code so take this approval with a grain of salt

**Review by smallinsky — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
