### PR TITLE
fix tsh logout flags

### LINKED ISSUE #33681: `tsh logout` flags do not work.
Expected behavior:
`tsh logout --user sean` deletes certificates.

Current behavior:
```
~ [1]$ tsh logout --user
tsh: error: expected argument for flag '--user'
usage: tsh logout

Delete a cluster certificate.

Flags:
  -l, --login                    Remote host login
      --proxy                    Teleport proxy address
      --user                     Teleport user, defaults to current local user
      --ttl                      Minutes to live for a session
  -i, --identity                 Identity file
      --cert-format              SSH certificate format
      --[no-]insecure            Do not verify server's certificate and host name.
                                 Use only in test environments
      --auth                     Specify the name of authentication connector to
                                 use.
      --[no-]skip-version-check  Skip version checking between server and client.
  -d, --[no-]debug               Verbose logging to stdout
  -k, --add-keys-to-agent        Controls how keys are handled. Valid values are
                                 [auto no yes only].
      --[no-]enable-escape-sequences
                                 Enable support for SSH escape sequences.
                                 Type '~?' during an SSH session to list supported
                                 sequences. Default is enabled.
      --bind-addr                Override host:port used when opening a browser
                                 for cluster logins
      --mfa-mode                 Preferred mode for MFA and Passwordless
                                 assertions (auto, cross-platform, platform, otp)
      --[no-]headless            Use headless login. Shorthand for
                                 --auth=headless.
      --mlock                    Determines whether process memory will be locked
                                 and whether failure to do so will be accepted
                                 (off, auto, best_effort, strict).
      --piv-slot                 Specify a PIV slot key to use for Hardware Key
                                 support instead of the default. Ex: "9d"
  -J, --jumphost                 SSH jumphost

Aliases:

ERROR: expected argument for flag '--user'

~ [1]$ tsh logout --user sean
ERROR: unexpected argument: sean
```

Bug details:
- Teleport version: v14.1.0 git:v14.1.0-0-g508ccc5 go1.21.3
- Recreation steps: run `tsh logout --user`
- Debug logs

### PR DESCRIPTION
**Pull request by GavinFrazar**
Changelog: Fixed a bug where tsh logout failed to parse flags passed with spaces.

Fixes #33681
- #33681

## Before

```
$ tsh logout --user gavin.frazar@goteleport.com --proxy=gavin-leaf.cloud.gravitational.io
ERROR: unexpected argument: gavin.frazar@goteleport.com

$ tsh logout --user=gavin.frazar@goteleport.com --proxy gavin-leaf.cloud.gravitational.io
ERROR: unexpected argument: gavin-leaf.cloud.gravitational.io
```

## After
```
$ tsh logout --user gavin.frazar@goteleport.com --proxy gavin-leaf.cloud.gravitational.io:443
Logged out gavin.frazar@goteleport.com from gavin-leaf.cloud.gravitational.io.
```

### CODE REVIEW

**Review by tigrato — COMMENTED** [review]
Not related but can you also fix this log message:

> Specify --proxy and --user to remove keys for specific user from a proxy or neither to log out all users from all proxies.

After reading it 10 times, I can't understand what it means

**Comment by GavinFrazar** [comment]
> Not related but can you also fix this log message:
> 
> > Specify --proxy and --user to remove keys for specific user from a proxy or neither to log out all users from all proxies.
> 
> After reading it 10 times, I can't understand what it means

how's this?

```
$ ~/code/teleport/build/tsh logout --user=gavin
Specify --proxy to log out user "gavin" from a specific proxy or remove the --user flag to log out all users from all proxies.

$ ~/code/teleport/build/tsh logout --proxy=gavin-leaf.cloud.gravitational.io:443
Specify --user to log out a specific user from "gavin-leaf.cloud.gravitational.io" or remove the --proxy flag to log out all users from all proxies.
```

File: tool/tsh/common/tsh.go [hunk 1]
```diff
@@ -2213,9 +2210,10 @@ func onLogout(cf *CLIConf) error {
 		}
 
 		fmt.Printf("Logged out all users from all proxies.\n")
-	default:
-		fmt.Printf("Specify --proxy and --user to remove keys for specific user ")
-		fmt.Printf("from a proxy or neither to log out all users from all proxies.\n")
+	case proxyHost != "" && cf.Username == "":
+		fmt.Printf("Specify --user to log out a specific user from %q or remove the --proxy flag to log out all users from all proxies.\n", proxyHost)
```
Comment (tigrato) [inline tool/tsh/common/tsh.go:2214]: It would be great if we can check how many users we had for each proxy and if we only have a single one, we wouldn't need to specify the username as it's filled automatically

Comment (GavinFrazar) [reply tool/tsh/common/tsh.go:2214]: It would be nice, but doesn't seem to be a simple change and would add a lot of scope to this PR

**Review by tigrato — APPROVED** [review]

**Review by greedy52 — APPROVED** [review]
