### PR TITLE
[Web] Fix scrolling in Node list in web terminal

### LINKED ISSUE #26604: There's no more rolling on session screen
Expected behavior:
I expected to be able to roll the screen down and see all servers available.

Current behavior:
On te session screen, when click on the plus button, on the right-to, the servers available for connection does not have a rolling bar anymore.

Screenshot_1

Bug details:
- Teleport version 13.0.2
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves https://github.com/gravitational/teleport/issues/26604

Fixes the scrolling on the Nodes list in the web terminal.

Also, for active sessions, makes it so the participant mode menu closes after joining a session rather than staying open.

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

File: web/packages/teleport/src/Console/DocumentNodes/DocumentNodes.tsx [hunk 1]
```diff
@@ -128,6 +128,7 @@ const Container = styled(Box)`
   display: flex;
   flex: 1;
   max-width: 1024px;
+  height: fit-content;
```
Comment (ravicious) [inline web/packages/teleport/src/Console/DocumentNodes/DocumentNodes.tsx:131]: Do you remember why [`overflow: hidden` was added to StyledTableWrapper](https://github.com/gravitational/teleport/commit/5a46f044b56#diff-56a64e0fa19fefcaa7f5fd1bb401ab3097a04b27a60e8a2b15fb942a460f3046R102)? If it's possible to get rid of it then I think long-term it might be a better fix than adding `height: fit-content` here.

File: web/packages/teleport/src/Sessions/SessionList/SessionList.tsx [hunk 2]
```diff
@@ -112,7 +112,7 @@ const renderJoinCell = ({
   showActiveSessionsCTA,
 }: renderJoinCellProps) => {
   const { joinable } = kinds[kind];
-  if (!joinable || participantModes.length === 0) {
```
Comment (ravicious) [inline web/packages/teleport/src/Sessions/SessionList/SessionList.tsx:115]: Is this second check handled on the backend now?

File: web/packages/teleport/src/Sessions/SessionList/SessionJoinBtn.tsx [hunk 3]
```diff
@@ -35,8 +35,14 @@ export const SessionJoinBtn = ({
   participantModes: ParticipantMode[];
   showCTA: boolean;
 }) => {
+  const [anchorEl, setAnchorEl] = useState<HTMLElement>(null);
```
Comment (ravicious) [inline web/packages/teleport/src/Sessions/SessionList/SessionJoinBtn.tsx:38]: A feedback for the future as this pattern wasn't introduced by this PR specifically, but I don't think it's a good practice to store HTML elements in the state – you might end up storing an element in the state that's no longer in DOM. Was this done as a workaround for some other problem?

Looking at the previous version of `JoinMenu`, I think a more idiomatic solution would be to create a new ref with `useRef`, pass it as the `ref` prop to `<ButtonBorder>`. Then to control whether `<Menu>` is supposed to be open or not, we could have `const [isOpen, setIsOpen] = useState(false)` and on the button click we could flip it to true.

**Review by ravicious — APPROVED** [review]
It fixes the problem but I think we should pursue the solution with removing `overflow: hidden` if possible. Doing so will make it harder to reintroduce this problem in the future.

File: web/packages/teleport/src/Sessions/SessionList/SessionJoinBtn.tsx (hunk 3 above)
Comment (ravicious) [reply web/packages/teleport/src/Sessions/SessionList/SessionJoinBtn.tsx:38]: [`MenuLogin`](https://github.com/gravitational/teleport/blob/2bb38605136375803416ebf10c7437e80b5938d4/web/packages/shared/components/MenuLogin/MenuLogin.tsx#L80) does it this way already. It looks like the prop has to be named `setRef` for the button components, I'm not exactly sure why it's done like this.

https://github.com/gravitational/teleport/blob/2bb38605136375803416ebf10c7437e80b5938d4/web/packages/design/src/Button/Button.jsx#L23-L25

File: web/packages/teleport/src/Console/DocumentNodes/DocumentNodes.tsx (hunk 1 above)
Comment (rudream) [reply web/packages/teleport/src/Console/DocumentNodes/DocumentNodes.tsx:131]: The reasoning was for all our different tables (paginated, searchable, simple, etc.) to have rounded corners. Wrapping all tables with it and having it round the corners with a `borderRadius` made it so we didn't have to always manually add a border radius for every table individually.

File: web/packages/teleport/src/Sessions/SessionList/SessionList.tsx (hunk 2 above)
Comment (rudream) [reply web/packages/teleport/src/Sessions/SessionList/SessionList.tsx:115]: No, previously we would completely hide the join button if the user had access to no participant modes. However since we added a better join menu with descriptions as well as a "You do not have permission to join as a ____" disclaimer for modes you don't have access to, we can now show the button and just have all the options greyed out. This is less confusing for a user who might be wondering why the join button isn't there. 

This change should've actually been made in https://github.com/gravitational/teleport/pull/24961 but I had forgotten to and only noticed it here while testing.
