### PR TITLE
fix tctl insecure flag with remote proxy

### LINKED ISSUE #13369: Error when trying to access tctl
Expected behavior:
`tctl status --insecure` to return it's proper output.

Current behavior:
`[CLIENT]       Cannot connect to the auth server: failed direct dial to auth server: Get "https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech": stopped after 10 redirects
	Get "https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech": stopped after 10 redirects, failed dial to auth server through reverse tunnel: Get "https://teleport.cluster.local/v2/configuration/name": Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech
	Get "https://teleport.cluster.local/v2/configuration/name": Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech.
Is the auth server running on "teleport.internalmediagroup.tech:443"?`

Bug details:
- Teleport version - 9.2.3
- Recreation steps
Install teleport in kubernetes, with --set-acme false, create a user, then login with tsh, then try to run `tctl status --insecure`
- Debug logs
`DEBU             Debug logging has been enabled. common/tctl.go:196
DEBU             No config file or identity file, loading auth config via extension. common/tctl.go:223
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/sfulham/.tsh/keys/teleport.internalmediagroup.tech/sfulham-x509.pem" valid until "2022-06-10 13:37:44 +0000 UTC". client/keystore.go:307
DEBU [KEYSTORE]  Reading certificates from path "/home/sfulham/.tsh/keys/teleport.internalmediagroup.tech/sfulham-ssh/teleport.internalmediagroup.tech-cert.pub". client/keystore.go:330
DEBU             Found active profile. proxy:https://teleport.internalmediagroup.tech:443 user:sfulham common/tctl.go:342
DEBU [KEYSTORE]  Returning Teleport TLS certificate "/home/sfulham/.tsh/keys/teleport.internalmediagroup.tech/sfulham-x509.pem" valid until "2022-06-10 13:37:44 +0000 UTC". client/keystore.go:307
DEBU [KEYSTORE]  Reading certificates from path "/home/sfulham/.tsh/keys/teleport.internalmediagroup.tech/sfulham-ssh/teleport.internalmediagroup.tech-cert.pub". client/keystore.go:330
DEBU             Setting auth server to web proxy teleport.internalmediagroup.tech:443. common/tctl.go:384
DEBU             Connecting to: [{teleport.internalmediagroup.tech:443 tcp }]. authclient/authclient.go:50
DEBU             Attempting GET teleport.internalmediagroup.tech:443/webapi/find webclient/webclient.go:118
ERRO             Failed to resolve tunnel address Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech reversetunnel/transport.go:90
ERRO             Failed to resolve tunnel address Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech reversetunnel/transport.go:90
INFO [CLIENT]    "Cannot connect to the auth server: failed direct dial to auth server: Get \"https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech\": stopped after 10 redirects\n\tGet \"https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech\": stopped after 10 redirects, failed dial to auth server through reverse tunnel: Get \"https://teleport.cluster.local/v2/configuration/name\": Get \"https://teleport.internalmediagroup.tech:443/webapi/find\": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech\n\tGet \"https://teleport.cluster.local/v2/configuration/name\": Get \"https://teleport.internalmediagroup.tech:443/webapi/find\": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech.\nIs the auth server running on \"teleport.internalmediagroup.tech:443\"?" utils/cli.go:275
[CLIENT]       Cannot connect to the auth server: failed direct dial to auth server: Get "https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech": stopped after 10 redirects
	Get "https://teleport.internalmediagroup.tech:443/web/launch/teleport.internalmediagroup.tech": stopped after 10 redirects, failed dial to auth server through reverse tunnel: Get "https://teleport.cluster.local/v2/configuration/name": Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech
	Get "https://teleport.cluster.local/v2/configuration/name": Get "https://teleport.internalmediagroup.tech:443/webapi/find": x509: certificate is valid for teleport-cluster-567df7cf88-sg4rl, localhost, localhost.local, not teleport.internalmediagroup.tech.
Is the auth server running on "teleport.internalmediagroup.tech:443"?`

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #13369

This PR fixes `tctl --insecure` so that it can be used with a proxy that has self-signed certs after logging in with tsh. I also: 
* refactored tctl's main `Run` function to call to a helper `TryRun`, in order to add a test for remote tctl usage with a proxy.
* moved `exitCodeError` into the tool/common package so it can be used from both tsh and tctl

### CODE REVIEW

File: tool/tctl/common/tctl.go [hunk 1]
```diff
@@ -27,6 +27,7 @@ import (
 	"syscall"
 
 	"github.com/gravitational/teleport/api/breaker"
+	toolcommon "github.com/gravitational/teleport/tool/common"
```
Comment (espadolini) [inline tool/tctl/common/tctl.go:30]: Please regroup and reformat the imports with `-local github.com/gravitational/teleport` (in vscode, `"gopls": { "formatting.local": "github.com/gravitational/teleport" }`).

File: tool/common/common.go [hunk 2]
```diff
@@ -30,6 +31,17 @@ import (
...
 )
 
+// ExitCodeError wraps an exit code as an error.
+type ExitCodeError struct {
+	// Code is the exit code
+	Code int
+}
+
+// Error implements the error interface.
+func (e *ExitCodeError) Error() string {
```
Comment (espadolini) [inline tool/common/common.go:41]: Should we pass `ExitCodeError` by value?

**Review by espadolini — APPROVED** [review]
Is there a matching PR for tctl enterprise?

**Review by capnspacehook — APPROVED** [review]

File: tool/tctl/common/tctl.go (hunk 1 above)
Comment (GavinFrazar) [reply tool/tctl/common/tctl.go:30]: I didn't know gopls could be configured to do that for me, thanks!

File: tool/common/common.go (hunk 2 above)
Comment (GavinFrazar) [reply tool/common/common.go:41]: No I don't think so, both because the exitCodeError that was originally defined in tsh.go used a pointer receiver to implement `error` and because from what I've found online it's best to use a pointer receiver. 

The semantics of error checking are more complicated (and mistake-prone) using a value receiver, because the underlying error may or may not be a pointer and may or may not be equal to another error depending on whether the underlying type is a value or a pointer - this means error checking code needs to consider both cases and handle appropriately. `errors.As` in particular has behavior I find to be too subtle depending on the underlying type. See the difference here:
https://go.dev/play/p/OzdcZal12OC

Comment (GavinFrazar) [reply tool/common/common.go:41]: It's not so common for code to be concerned about the underlying type of interfaces in general, but in the case of the `error` interface, it's common for code to inspect the underlying type of an `error` to decide how to handle it.

**Comment by GavinFrazar** [comment]
> Is there a matching PR for tctl enterprise?

No, but this should fix it for both right? They both call into the same Run function in `tool/tctl/common/tctl.go`.
