### PR TITLE
Fix scp regressions for 6.x

### LINKED ISSUE #5695: scp regression on 6.0.0-rc.1
### Description

**What happened**:

```
# build/teleport is a binary
$ ls -l build/teleport
-rwxr-xr-x. 1 gus gus 70682783 Feb 24 17:23 build/teleport

# try to scp it to hades (node running 6.0.0-rc.1), it fails with this weird error
$ scp build/teleport hades:~/tmp
ERROR:
	open home/gus/tmp: no such file or directory

lost connection

# try to scp it to zeus (5.1.2) with the same command, works
$ scp build/teleport zeus:~/tmp
teleport                                                                                                                    100%   67MB  14.6MB/s   00:04

# file was created as expected
$ ssh zeus -- ls -l tmp
-rwxr-xr-x 1 gus gus 70682783 Feb 24 17:29 tmp

# same happens with `tsh scp` to hades, same error in the teleport logs
$ tsh scp build/teleport hades:~/tmp
-> build/teleport (70682783)
error: Process exited with status 1

# tsh scp works to zeus
$ tsh scp build/teleport zeus:~/tmp
-> build/teleport (70682783)
```

Not sure why the `home/gus/tmp` is missing the preceding `/` in the error.

Teleport logs from hades:
```
Feb 24 17:32:25 hades teleport[1830443]: DEBU [NODE]      Handling request exec, want reply true. id:13 local:192.168.64.201:55646 login:gus remote:192.168.64.1:57146 teleportUser:webvictim regular/sshserver.go:1269
Feb 24 17:32:25 hades teleport[1830443]: INFO [NODE]      Creating (exec) session ff83677f-df42-4cf0-87cf-7fb8b9654f61. id:13 local:192.168.64.201:55646 login:gus remote:192.168.64.1:57146 teleportUser:webvictim srv/sess.go:234
Feb 24 17:32:25 hades teleport[1830443]: DEBU [SESSION:N] Using async streamer for session ff83677f-df42-4cf0-87cf-7fb8b9654f61. srv/sess.go:1043
Feb 24 17:32:25 hades teleport[1830443]: INFO [AUDIT]     session.start addr.remote:192.168.64.1:57146 cluster_name:teleport.example.com code:T2000I ei:0 event:session.start login:gus namespace:default server_addr:192.168.64.201:55646 server_hostname:hades server_id:0065053d-e8e9-4880-aebb-e2d9499b681e server_labels:map[arch:x86_64 external_ipv4:142.167.142.235 external_ipv6:No IPv6 hostname:hades running_containers:alertmanager caddy cadvisor delugevpn grafana homebridge jackett lidarr nodeexporter nodered ombi plex plexpy prometheus pushgateway radarr sensorexporter smokeping sonarr watchtower stopped_containers: teleport_version:Teleport v6.0.0-rc.1 git:v6.0.0-rc.1-0-g5470bb912 go1.15.5 type:node] sid:ff83677f-df42-4cf0-87cf-7fb8b9654f61 time:2021-02-24T21:32:25.464Z uid:5435bd13-0028-41d8-83fa-cdca81ab9c32 user:webvictim events/emitter.go:317
Feb 24 17:32:25 hades teleport[1830443]: INFO [NODE]      Started local command execution: "/usr/local/bin/teleport scp --remote-addr=192.168.64.1:57146 --local-addr=192.168.64.201:55646 -t ~/tmp" id:13 local:192.168.64.201:55646 login:gus remote:192.168.64.1:57146 teleportUser:webvictim srv/exec.go:182
Feb 24 17:32:25 hades teleport[1830443]: INFO [SESSION:N] Closing session ff83677f-df42-4cf0-87cf-7fb8b9654f61. srv/sess.go:632
Feb 24 17:32:25 hades teleport[1830443]: ERROR:
Feb 24 17:32:25 hades teleport[1830443]:         open home/gus/tmp: no such file or directory
Feb 24 17:32:25 hades teleport[1830443]: DEBU [NODE]      Local command failed: exit status 1. id:13 local:192.168.64.201:55646 login:gus remote:192.168.64.1:57146 teleportUser:webvictim srv/exec.go:196
Feb 24 17:32:25 hades teleport[1830443]: DEBU [NODE]      Exec request ("/usr/local/bin/teleport scp --remote-addr=192.168.64.1:57146 --local-addr=192.168.64.201:55646 -t ~/tmp") complete: 1 id:13 local:192.168.64.201:55646 login:gus remote:192.168.64.1:57146 teleportUser:webvictim regular/sshserver.go:1249
Feb 24 17:32:25 hades teleport[1830443]: INFO [AUDIT]     scp action:upload addr.local:192.168.64.201:55646 addr.remote:192.168.64.1:57146 cluster_name:teleport.example.com code:T3005E command:/usr/local/bin/teleport scp --remote-addr=192.168.64.1:57146 --local-addr=192.168.64.201:55646 -t ~/tmp ei:0 event:scp exitCode:1 exitError:exit status 1 login:gus namespace:default path:~/tmp server_id:0065053d-e8e9-4880-aebb-e2d9499b681e sid:ff83677f-df42-4cf0-87cf-7fb8b9654f61 time:2021-02-24T21:32:25.556Z uid:68fb14f6-5b5a-4915-8e32-9aac0abe8853 user:webvictim events/emitter.go:317
Feb 24 17:32:25 hades teleport[1830443]: DEBU [SSH:NODE]  Closed connection 192.168.64.1:57146. sshutils/server.go:448
Feb 24 17:32:25 hades teleport[1830443]: INFO [AUDIT]     session.data addr.remote:192.168.64.1:57146 cluster_name: code:T2006I ei:2.147483646e+09 event:session.data login:gus namespace:default rx:3822 server_id:0065053d-e8e9-4880-aebb-e2d9499b681e sid:ff83677f-df42-4cf0-87cf-7fb8b9654f61 time:2021-02-24T21:32:25.56Z tx:5463 uid:32822ba3-8323-4aec-a2ab-22911882acec user:webvictim events/emitter.go:317
```

Also note weird line break in the error message.

**What you expected to happen**: scp to hades should work just as it does to zeus.

### Reproduction Steps
See above.

Here's my `~/.ssh/config` if it helps:

```
Host teleport.example.com
    User gus
    Port 3023
    IdentityFile ~/.tsh/keys/teleport.example.com/webvictim
    UserKnownHostsFile ~/.ssh/teleport/known_hosts

Host hades
    User gus
    ProxyCommand sh -c '~/.ssh/teleport/login.sh teleport.example.com webvictim && ssh teleport.example.com -s proxy:%h:%p'
    Port 3022
    IdentityFile ~/.tsh/keys/teleport.example.com/webvictim
    HostKeyAlias hades.teleport.example.com
    UserKnownHostsFile ~/.ssh/teleport/known_hosts

Host zeus
    User gus
    ProxyCommand sh -c '~/.ssh/teleport/login.sh teleport.example.com webvictim && ssh teleport.example.com -s proxy:%h:%p'
    Port 3022
    IdentityFile ~/.tsh/keys/teleport.example.com/webvictim
    HostKeyAlias zeus.teleport.example.com
    UserKnownHostsFile ~/.ssh/teleport/known_hosts
```

(there are more details about the exact setup at 

### Server Details
- Teleport version (run `teleport version`):
```
$ ssh hades -- teleport version
Teleport v6.0.0-rc.1 git:v6.0.0-rc.1-0-g5470bb912 go1.15.5

$ ssh zeus -- teleport version
Teleport v5.1.2 git:v5.1.2-0-g822d10b44 go1.15.5
```
- tsh version: `Teleport v5.1.2 git:v5.1.2-0-g822d10b44 go1.15.5`
- Server OS (e.g. from `/etc/os-release`): Fedora 32
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Home lab

### PR DESCRIPTION
**Pull request by a-palchikov**
Use correct target directory path in error message.
Handle target directory/file renames properly.

I've only tested these changes manually and I was working on automatic test coverage for the rest of the use-cases but I'm not sure I can make it in time for rc.2.

Fixes https://github.com/gravitational/teleport/issues/5695.

### CODE REVIEW

**Review by xacrimon — APPROVED** [review]

**Comment by russjones** [comment]
@andrejtokarcik Can you review this?

**Comment by russjones** [comment]
@a-palchikov If we can't make it to rc.2, let's aim for rc.3?

**Comment by a-palchikov** [comment]
Ok - I'll work on the tests to be on the safe side.

File: lib/sshutils/scp/scp.go [hunk 1]
```diff
@@ -532,8 +534,17 @@ func (cmd *command) receiveFile(st *state, fc newFileCmd, ch io.ReadWriter) erro
...
-	st.push(fc.Name, st.stat)
-	err := cmd.FileSystem.MkDir(st.path.join(), int(fc.Mode))
+	if cmd.FileSystem.IsDir(cmd.Flags.Target[0]) {
+		// Copying into an existing directory? append to it:
+		st.push(fc.Name, st.stat)
+	} else {
+		// If target specifies a new directory, we need to reset
+		// state with it
+		st.path = newPathFromDirAndTimes(cmd.Flags.Target[0], st.stat)
+	}
```
Comment (andrejtokarcik) [inline lib/sshutils/scp/scp.go:544]: This could cause unexpected data duplication, especially in automated scripts which may simply rely on the fact that `tsh scp` always overwrites its target. For example:

```bash
$ stat /tmp/zz
stat: cannot stat '/tmp/zz': No such file or directory
$ tsh scp -r ./large-tree/ /tmp/zz/
[...]
$ diff ./large-tree/ /tmp/zz/ && echo same tree
same tree
$ tsh scp -r ./large-tree/ /tmp/zz/   # re-run the same tsh scp command
[...]
$ diff ./large-tree/ /tmp/zz/
Only in /tmp/zz/: large-tree
```
The files of `large-tree` would end up in two copies under `/tmp/zz`: once directly under `/tmp/zz`, once under `/tmp/zz/large-tree`.

**Review by andrejtokarcik — APPROVED** [review]

**Comment by andrejtokarcik** [comment]
BTW I had to apply the following to make `tsh scp` work with zsh:
```diff
diff --git a/lib/srv/exec.go b/lib/srv/exec.go
index e8cf6232d..a822b0293 100644
--- a/lib/srv/exec.go
+++ b/lib/srv/exec.go
@@ -247,7 +247,7 @@ func (e *localExec) transformSecureCopy() error {
        if err != nil {
                return trace.Wrap(err)
        }
-       e.Command = fmt.Sprintf("%s scp --remote-addr=%s --local-addr=%s %v",
+       e.Command = fmt.Sprintf("%s scp --remote-addr=%q --local-addr=%q %v",
                teleportBin,
                e.Ctx.ServerConn.RemoteAddr().String(),
                e.Ctx.ServerConn.LocalAddr().String(),
```
The encountered error was:
```
zsh:1: no matches found: --remote-addr=[::1]:59236
```

File: lib/sshutils/scp/scp.go (hunk 1 above)
Comment (a-palchikov) [reply lib/sshutils/scp/scp.go:544]: Yes, this is consistent with OpenSSH client's behavior - initial attempt to copy a directory into a new non-existing location causes a rename, but existing location appends to it.

Comment (andrejtokarcik) [reply lib/sshutils/scp/scp.go:544]: I can't test it right now but IIRC, OpenSSH `scp` changes its dir-copying behaviour [based on the trailing slash](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=76054) which I think `tsh scp` would not.

Comment (a-palchikov) [reply lib/sshutils/scp/scp.go:544]: That could be possible - I'll test that as well.

File: lib/sshutils/scp/scp_test.go [hunk 2]
```diff
@@ -197,40 +201,93 @@ func TestReceive(t *testing.T) {
...
-			cmd, err := CreateCommand(tt.config)
-			require.NoError(t, err)
 
 			sourceDir := t.TempDir()
-			source := filepath.Join(sourceDir, tt.config.Flags.Target[0])
+			source := filepath.Join(sourceDir, tt.source)
 			args := append(tt.args, source)
 
-			// Source is missing, expect an error.
-			err = runSCP(cmd, args...)
```
Comment (a-palchikov) [inline lib/sshutils/scp/scp_test.go:213]: I factored this into a dedicated test - no need to test this for each local testcase.

File: lib/sshutils/scp/local.go [hunk 3]
```diff
@@ -49,7 +49,7 @@ func (l *localFileSystem) Chtimes(path string, atime, mtime time.Time) error {
 // MkDir creates a directory
 func (l *localFileSystem) MkDir(path string, mode int) error {
 	fileMode := os.FileMode(mode & int(os.ModePerm))
-	err := os.MkdirAll(path, fileMode)
+	err := os.Mkdir(path, fileMode)
```
Comment (a-palchikov) [inline lib/sshutils/scp/local.go:52]: This differed from OpenSSH's behavior which does not automatically create intermediate directories. If that's a concern, we can revert this change.

File: lib/sshutils/scp/scp.go (hunk 1 above)
Comment (a-palchikov) [reply lib/sshutils/scp/scp.go:544]: I did not see any difference between trailing slash and no slash in behavior.

Comment (a-palchikov) [reply lib/sshutils/scp/scp.go:544]: client (ubuntu):
```
$ ssh -V
OpenSSH_8.4p1, OpenSSL 1.1.1f  31 Mar 2020
```
server (centos):
```
$ ssh -V
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
```
Trailing slash does not change the behavior as described in the linked issue.

File: lib/sshutils/scp/local.go (hunk 3 above)
Comment (xacrimon) [reply lib/sshutils/scp/local.go:52]: Adhering to OpenSSH behaviour seems more logical to me. When people type `scp` they expect it to behave just like scp does when it comes to things like this.

File: lib/sshutils/scp/scp.go (hunk 1 above)
Comment (xacrimon) [reply lib/sshutils/scp/scp.go:544]: I'm getting the same results.

**Comment by russjones** [comment]
@xacrimon @andrejtokarcik Can you to re-review?

**Review by xacrimon — APPROVED** [review]

**Review by andrejtokarcik — APPROVED** [review]

**Review by russjones — APPROVED** [review]
Bot.

**Comment by russjones** [comment]
@a-palchikov Just to clarify, we now match OpenSSH behavior right? I agree, I think that's what users expectation here is.

**Comment by a-palchikov** [comment]
> @a-palchikov Just to clarify, we now match OpenSSH behavior right? I agree, I think that's what users expectation here is.

Yes, w.r.t to copying a directory to a remote path with intermediates that do not exist.

File: lib/sshutils/scp/local.go (hunk 3 above)
Comment (webvictim) [reply lib/sshutils/scp/local.go:52]: I agree, we should be as consistent as possible with OpenSSH.

Comment (russjones) [reply lib/sshutils/scp/local.go:52]: @alex-kovoy Any reason you made this `MkdirAll`? https://github.com/gravitational/teleport/pull/2055

Comment (alex-kovoy) [reply lib/sshutils/scp/local.go:52]: @russjones That was original implementation, it appeared in my PR because I move some code around while working on HTTP transfers. See the original (deleted) `scp.go` file in that PR.

Comment (russjones) [reply lib/sshutils/scp/local.go:52]: Hrm, interesting the original commit seems to indicate `MkdirAll` lines up with OpenSSH behavior: https://github.com/gravitational/teleport/pull/788/commits/80df1bbc2d68f9a7aa7103ad4eb7eeac4b8b7700

File: lib/sshutils/scp/scp.go (hunk 1 above)
Comment (a-palchikov) [reply lib/sshutils/scp/scp.go:544]: Yes, the server is `sshd`. It does not have a version flag but outputs the version anyways:
```
$ sshd -V
unknown option -- V
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
```

File: lib/sshutils/scp/local.go (hunk 3 above)
Comment (a-palchikov) [reply lib/sshutils/scp/local.go:52]: The original commit that introduced this changes is https://github.com/gravitational/teleport/commit/2ad2fb4ff1f9874a4f6265974518c42f0561ec70 and it seems to be fixing this [problem](https://github.com/gravitational/teleport/issues/274#issuecomment-198626834) from https://github.com/gravitational/teleport/issues/274.
Since the solution caused another issue, it was changed in https://github.com/gravitational/teleport/commit/c6c77a183c9a32d076dd0110eebfdc35d249ad96 but `os.MkdirAll` remained.

Comment (a-palchikov) [reply lib/sshutils/scp/local.go:52]: As for the behavior of OpenSSH (7.4p1 from above) and the following source layout:
```
$ tree foo
foo
├── foo1
└── foo-dir
    └── foo-file
```

Copying to a non-existing directory (`zz`, 1 level), renames the source into it (or creates it remotely and copies the contents of the source directory):
```
$ scp -r ./foo centos@35.226.107.203:zz
foo1                                                                                     100%    0     0.0KB/s   00:00    
foo-file                                                                                 100%    0     0.0KB/s   00:00
```
with the resulting remote layout:
```
# tree zz
zz
├── foo1
└── foo-dir
    └── foo-file
```
while opening into a directory with an intermediate non-existing directory:
```
$ scp -r ./foo centos@35.226.107.203:non-existing/zz
scp: non-existing/zz: No such file or directory
```
but it works with tsh in `5.2.1`.
