### PR TITLE
fix an issue expired app session won't redirect to login on DynamoDB backend

### LINKED ISSUE #53091: Expired client certificates for application access not prompting re-authentication
### Expected behavior:
When a user's App Access session (and its associated client cert) expires, Teleport should prompt for re-authentication to renew the certificate and continue access seamlessly.

### Current behavior:

When a user's app access session is expired in a browser, they can receive "Bad Gateway" messages. This happens when the browser has a session token that corresponds to the **expired** client certificate stored in the backend.

Users need to manually re-log into Teleport or the specific application to renew the certificate and regain access.

Restarting a Teleport auth service instance was also reported to clear out the issue.

This **feels** like a caching bug. The old web session object is cached and used even if the associated client cert is expired.

### Bug details:
- **Teleport version**: 17.3.3 (issue began after upgrading from 16.x)
- **Recreation steps**:
  1. User logs into an application (e.g., Grafana) via Teleport using app access.
  2. Wait for the client certificate to reach its expiration (e.g., 12 hours later).
  3. Attempt to continue accessing the application.
  4. Observe that the certificate expires without renewal, resulting in 502 errors.

- **Debug logs**:

  From the agent itself, it will log the error about the expired cert:

  ```
  {"timestamp":"2025-03-04T04:10:10Z","level":"warning","caller":"app/connections_handler.go:330","message":"Failed to handle client connection.","component":"app:service","error":"TLS handshake failed\n\ttls: failed to verify certificate: x509: certificate has expired or is not yet valid" }
  ```

  From the proxy, it logs the error that says the remote side rejected the client cert:

  ```
  {"caller":"reverseproxy/reverse_proxy.go:218","component":"app:web","level":"error","message":"Error forwarding to /some/path, err: remote error: tls: expired certificate","timestamp":"2025-03-05T10:07:43Z"}
  ```

The issue was seen in a fairly typical `teleport-cluster` helm deployment inside AWS. This includes DynamoDB for storage.

### PR DESCRIPTION
**Pull request by greedy52**
fixes #53091:
- #53091 

changelog: fix an issue expired app session won't redirect to login page when Teleport is using DynamoDB backend

related:
- https://github.com/gravitational/teleport/pull/46899

App session object may still be retrievable after it expires with DynamoDB backend. Old ttlmap will cause `authenticate` to fail as it won't  create a new session when TTL is negative. However, this is not the case with FnCache replacement. Instead of fixing the AccessPoint cache or the local FnCache, this quick fix adds an explicit check on app session's `Expiry`. Better solution should be explored to fix the general issue but i would like to deliver this quick fix now.

### CODE REVIEW

File: lib/web/app/handler_test.go [hunk 1]
```diff
@@ -808,3 +774,119 @@ func TestMakeAppRedirectURL(t *testing.T) {
...
+			fakeRemote: fakeRemoteSite,
+		},
+		Config: &http.Server{Handler: http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
+			fmt.Fprint(w, "Hello application")
+		})},
+	}
+	server.StartTLS()
+	t.Cleanup(func() {
+		// Close fake remote site first to make sure fake listener quits.
+		fakeRemoteSite.Close()
```
Comment (bernardjkim) [inline lib/web/app/handler_test.go:799]: Should we still require that `Close` does not return an error?

**Review by bernardjkim — APPROVED** [review]

File: lib/web/app/handler.go [hunk 2]
```diff
@@ -388,6 +388,11 @@ func (h *Handler) getAppSession(r *http.Request) (ws types.WebSession, err error
 		h.logger.WarnContext(r.Context(), "Failed to get session", "error", err)
 		return nil, trace.AccessDenied("invalid session")
 	}
+
+	if ws.Expiry().Before(h.c.Clock.Now()) {
+		h.logger.WarnContext(r.Context(), "Session expired")
+		return nil, trace.AccessDenied("session expired")
```
Comment (espadolini) [inline lib/web/app/handler.go:394]: I'm not sure what the implications are about revealing that a session is still accessible in the backend but expired, but we're not disclosing details about the specific error we hit when obtaining the session, so I reckon it's better to be consistent here.

```suggestion
		return nil, trace.AccessDenied("invalid session")
```

Comment (espadolini) [reply lib/web/app/handler.go:394]: Should the check be in `getAppSessionFromCert` and `getAppSessionFromCookie`? Is this the only place where we're fetching an `AppSession` where we should error out if it's expired?

Comment (greedy52) [reply lib/web/app/handler.go]: added a helper and updated other places calling accesspoint.GetAppSession. Updated the return error to `invalid session` and downgraded the log to debug.

10ab463

**Review by espadolini — APPROVED** [review]
