### PR TITLE
Deflake `TestSSHServerBasics`

### LINKED ISSUE #54711: `TestSSHServerBasics` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/14968567787/job/42044055213#step:6:2192

#### Relevant snippet

**replace everything below here with your snippet**

```
    controller_test.go:1758: 
        	Error Trace:	/__w/teleport/teleport/lib/inventory/controller_test.go:1758
        	            				/__w/teleport/teleport/lib/inventory/controller_test.go:322
        	Error:      	unexpected event
        	Test:       	TestSSHServerBasics
        	Messages:   	event=ssh-keep-alive-err
```

### PR DESCRIPTION
**Pull request by espadolini**
This PR fixes a (logical) race condition that could happen in `lib/inventory.TestSSHServerBasics` where the inventory controller was instructed to fail the following node heartbeat upsert after queuing up the node heartbeat that was intended to fail, making it possible for it to succeed depending on timing. Other tests in the package already correctly set the flag before sending the heartbeat, so this PR aligns the behavior of the flaky test to the other tests.

In addition, this PR also puts the `lib/inventory` tests into synctest bubbles (in go 1.25) for a 4000-fold reduction in execution time. 

Fixes #54711

### CODE REVIEW

File: lib/inventory/inventory_nosynctest_test.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+// You should have received a copy of the GNU Affero General Public License
+// along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+//go:build !go1.25
+
+package inventory
+
+import "testing"
+
+// TODO(espadolini): DELETE IN v21 or after the oldest supported Teleport
```
Comment (rosstimothy) [inline lib/inventory/inventory_nosynctest_test.go:23]: Is there any reason we can't use synctest on all release branches? All currently supported releases use Go 1.24 which has the unstable API available.

Comment (espadolini) [reply lib/inventory/inventory_nosynctest_test.go:23]: Added support for the experimental synctest (with an ugly but functional wart) in 1b115395e84b9bf89e7f12b8b476de00b772f0d9

File: lib/inventory/store_test.go [hunk 2]
```diff
@@ -99,6 +99,12 @@ func BenchmarkStore(b *testing.B) {
 // 1. Handles are loadable by ID.
 // 2. When multiple handles have the same ID, loads are distributed across them.
 func TestStoreAccess(t *testing.T) {
+	if testing.Short() {
```
Comment (rosstimothy) [inline lib/inventory/store_test.go:102]: Are these only skipped locally? Do we still run these in CI?

**Review by zmb3 — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

File: lib/inventory/store_test.go (hunk 2 above)
Comment (espadolini) [reply lib/inventory/store_test.go:102]: Yes, these are only skipped when passing -short, I figured it was appropriate here since they're quite a bit heavier than anything else in the package, and it would be nice if we could start marking "slow" tests to make it relatively cheaper to run tests locally.
