### PR TITLE
[Web] Fix notification text dialog max width and add support for newline characters

### LINKED ISSUE #53593: [notifications] General UX Improvements
While performing tests with in cluster notifications I noticed a few UX improvements that would be helpful for Cloud leveraging in cluster notifications.

- Long messages take up the entire width of the window.  Consider a max width.
- Support for new line breaks. 
- ~Hyperlink support.  Useful for pointing to public documentation.~

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves #53593 

This PR fixes a bug related to the width of custom notifications. This PR also adds support for including `\n` characters in the text content to add line breaks.

## Demo

image

### TODO:
- [ ] Update notifications docs to mention support for `\n`

### CODE REVIEW

**Review by avatus — APPROVED** [review]

File: web/packages/teleport/src/Notifications/Notification.tsx [hunk 1]
```diff
@@ -229,26 +220,60 @@ export function Notification({
...
+          setShowTextContentDialog={setShowTextContentDialog}
+          title={content.title}
+          content={content.textContent}
+        />
       )}
     </>
   );
 }
 
+function TextNotificationDialog({
```
Comment (kimlisa) [inline web/packages/teleport/src/Notifications/Notification.tsx:234]: export and write story? `WithNewline` and `WithoutNewline`

**Review by kimlisa — APPROVED** [review]
