### PR TITLE
fix test alpn proxy http proxy basic auth dial flakiness

### LINKED ISSUE #14143: `TestALPNProxyHTTPProxyBasicAuthDial` flakiness
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=us-west1/391f6966-8d99-4d9d-a1d5-a2c1753555bc;step=0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/365fbf4d-9061-4204-9d82-95c88bffb373?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/c96fa16b-3f09-433a-aaef-07b08a585650?project=ci-account

#### Relevant snippet

```
    proxy_test.go:886: 
        	Error Trace:	proxy_test.go:886
        	Error:      	Received unexpected error:
        	            	did not find 1 nodes
        	Test:       	TestALPNProxyHTTPProxyBasicAuthDial
```

### PR DESCRIPTION
**Pull request by GavinFrazar**
Closes #14143

## What
Fixes flaky test behavior

## Why was it flaky?
This test was flaky because it started 3 nodes, and expected 2 of the nodes to fail to register, however all 3 would successfully register and the `WaitForNodeCount(ctx, rc, rc.Secrets.SiteName, 1)` call would only pass if it happened to check the node count after only 1 node had finished registering.
The reason the 2 nodes eventually succeed in registering, is that they continue trying to connect to the auth service via proxy tunnel, and before starting the 3rd node I had set the `http_proxy` variable with correct proxy basic auth credentials. This allowed their reconnect attempts to then succeed.

## How this PR fixes it
I refactored the test such that it only starts 1 node instead of 3, since the extra nodes are not necessary to test the behavior when auth credentials are invalid. So now the test:
1. starts one node with improper auth credentials in `http_proxy` env var and waits for the node to attempt to connect via the mock proxy basic auth handler. It checks that the requests are being rejected for bad credentials.
2. sets the mock auth proxy credentials to match the credentials in `http_proxy` and waits for the node to attempt to connect again. Then it checks that requests are succeeding.
3. waits for the node to complete registering successfully.

I also refactored `ProxyAuthorizer` to support waiting for a new request with a timeout so that if nodes fail to connect to it the test will fail in an obvious way rather than timing out the entire test suite.

### CODE REVIEW

File: integration/helpers/proxy.go [hunk 1]
```diff
@@ -92,68 +92,109 @@ func (p *ProxyHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
+		}
+		if waiter != nil {
+			p.notifyWaiter(waiter, err)
+		}
+	}()
+	select {
+	case waiter = <-p.waitersC:
+	default:
+	}
+
```
Comment (espadolini) [inline integration/helpers/proxy.go:135]:
```suggestion
	var err error
	// we detect if someone is waiting for a new request to come in.
	select {
	case waiter := <-p.waitersC:
		defer func() { p.notifyWaiter(waiter, err) }
	default:
	}
	defer func() {
		if err != nil {
			trace.WriteError(w, err)
		}
	}()
```

**Review by espadolini — APPROVED** [review]

**Review by hugoShaka — APPROVED** [review]
