### PR TITLE
Respect HTTP_PROXY/HTTPS_PROXY

### LINKED ISSUE #8108: tsh ignores HTTPS_PROXY
### Description

With HTTPS_PROXY set, I would expect `tsh login` to use that. It seems to ignore that and instead try to make the connections directly.

Our docs do make reference to using HTTP_PROXY / HTTPS_PROXY environment variables, but not specifically for tsh.

### Reproduction Steps

I have a clonable gist that illustrates the problem: https://gist.github.com/programmerq/d053ae8acde4c7e467b44a32817750ef

Clone the gist, put your own license.pem (since it is using teleport enterprise), and follow the instructions in the gist readme.

If not using the gist, the idea is to set up a teleport server and try to access it via an HTTP CONNECT style proxy with `http_proxy`, `HTTP_PROXY`, `https_proxy`, and `HTTPS_PROXY` all set to the same thing. In my test, I used a tinyproxy instance and confirmed that `curl` was able to access the teleport API endpoint successfully with those variables set. In a proper lab setup, unsetting the variables should cause a failure due to the teleport URL due to timing out.

### Server Details

reproduced in the compose file with the following:

- Teleport version (run `teleport version`): 7.1.0 (from the `quay.io/gravitational/teleport-ent:7.1.0` docker image)
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): docker container via compose
- Additional details:  https://gist.github.com/programmerq/d053ae8acde4c7e467b44a32817750ef "teleport" container in compose file.

### Client Details
- Tsh version (`tsh version`): Teleport v7.1.0 git:v7.1.0-0-gb52a7d89f go1.16.2
- Computer OS (e.g. Linux, macOS, Windows): CentOS Linux release 7.9.2009
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): https://get.gravitational.com/teleport-ent-7.1.0-1.x86_64.rpm
- Additional details: https://gist.github.com/programmerq/d053ae8acde4c7e467b44a32817750ef "shell" container in compose file

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

```
[root@236b59f41927 ~]# tsh --debug login --user admin --proxy teleport:3080 --insecure
DEBU [CLIENT]    Failed to stat file: stat /root/.tsh: no such file or directory. client/api.go:679
INFO [CLIENT]    no host login given. defaulting to root client/api.go:1033
ERRO [CLIENT]    [KEY AGENT] Unable to connect to SSH agent on socket: "". client/api.go:2780
DEBU [CLIENT]    not using loopback pool for remote proxy addr: teleport:3080 client/api.go:2745

ERROR REPORT:
Original Error: *url.Error Get &#34;https://teleport:3080/webapi/ping&#34;: dial tcp 192.168.208.40:3080: connect: connection timed out
Stack Trace:
	/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/webclient/webclient.go:87 github.com/gravitational/teleport/api/client/webclient.Ping
	/go/src/github.com/gravitational/teleport/lib/client/api.go:2342 github.com/gravitational/teleport/lib/client.(*TeleportClient).Ping
	/go/src/github.com/gravitational/teleport/lib/client/api.go:2196 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:800 main.onLogin
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:588 main.Run
	/go/src/github.com/gravitational/teleport/tool/tsh/tsh.go:261 main.main
	/opt/go/src/runtime/proc.go:225 runtime.main
	/opt/go/src/runtime/asm_amd64.s:1371 runtime.goexit
User Message: Get &#34;https://teleport:3080/webapi/ping&#34;: dial tcp 192.168.208.40:3080: connect: connection timed out
[root@236b59f41927 ~]#
```

### PR DESCRIPTION
**Pull request by atburke**
Fixes #8108.

### CODE REVIEW

**Comment by russjones** [comment]
@atburke This needs test coverage.

File: api/client/webclient/webclient_test.go [hunk 1]
```diff
@@ -289,3 +290,12 @@ func TestExtract(t *testing.T) {
 		})
 	}
 }
+
+func TestNewWebClientRespectHTTPProxy(t *testing.T) {
+	os.Setenv("HTTPS_PROXY", "localhost:9999")
+	defer os.Unsetenv("HTTPS_PROXY")
+	client := newWebClient(false, nil)
```
Comment (codingllama) [inline api/client/webclient/webclient_test.go:297]: Comment ambiguous arguments?

```suggestion
	client := newWebClient(false /* insecure */, nil /* pool */)
```

File: api/client/webclient/webclient_test.go [hunk 2]
```diff
@@ -289,3 +290,12 @@ func TestExtract(t *testing.T) {
...
+	_, err := client.Get("https://example.com")
+	// Client should try to proxy through nonexistent server at localhost.
+	require.Error(t, err)
```
Comment (codingllama) [inline api/client/webclient/webclient_test.go:300]: Anything we can assert in the error so it's clear it failed as we expected?

File: lib/client/https_client_test.go [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+	"github.com/stretchr/testify/require"
+)
+
+func TestNewInsecureWebClientHTTPProxy(t *testing.T) {
+	os.Setenv("HTTPS_PROXY", "localhost:9999")
+	defer os.Unsetenv("HTTPS_PROXY")
+	client := NewInsecureWebClient()
+	_, err := client.Get("https://example.com")
+	// Client should try to proxy through nonexistent server at localhost.
+	require.Error(t, err)
```
Comment (codingllama) [inline lib/client/https_client_test.go:32]: Ditto for assert.

File: lib/client/https_client_test.go [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+}
+
+func TestNewClientWithPoolHTTPProxy(t *testing.T) {
+	os.Setenv("HTTPS_PROXY", "localhost:9999")
+	defer os.Unsetenv("HTTPS_PROXY")
+	client := newClientWithPool(nil)
+	_, err := client.Get("https://example.com")
+	// Client should try to proxy through nonexistent server at localhost.
+	require.Error(t, err)
```
Comment (codingllama) [inline lib/client/https_client_test.go:41]: Ditto for assert.

**Review by jimbishopp — APPROVED** [review]
I tested this locally as well. `tsh` login seems to work with and without proxy environment variables set.

**Review by codingllama — APPROVED** [review]

File: api/client/webclient/webclient_test.go [hunk 5]
```diff
@@ -289,3 +290,14 @@ func TestExtract(t *testing.T) {
 		})
 	}
 }
+
+func TestNewWebClientRespectHTTPProxy(t *testing.T) {
+	os.Setenv("HTTPS_PROXY", "localhost:9999")
```
Comment (zmb3) [inline api/client/webclient/webclient_test.go:295]: `t.Setenv` would remove the need for `Unsetenv`

**Review by zmb3 — APPROVED** [review]

**Comment by russjones** [comment]
@atburke Take a look at the comments (and diff) from @johns-carta in https://github.com/gravitational/teleport/issues/8108.

**Comment by johns-carta** [comment]
Sorry, that fix is incomplete, this is going to dial directly , again, instead of through the proxy:
https://github.com/gravitational/teleport/blob/atburke/tsh-https-proxy/lib/client/client.go#L718 

you need to implement a CONNECT proxy dialer in api/client/contextdialer.go and pass that as a dialer (instead of Addr) to ConnectToAuthServiceThroughALPNSNIProxy 

There are almost certainly other similar cases littered about

I suggest testing this with a deployment that is only accessible via HTTP CONNECT, because if the dev machine or test machine can directly connect to the Teleport cluster it will look successful when it is in fact, not.

**Review by codingllama — CHANGES_REQUESTED** [review]
Withdrawing approval, as it seems we didn't quite hit the mark here yet. @atburke, let me know when you are ready for review again.

**Comment by johns-carta** [comment]
@atburke This code added to this PR works (I've done an end-to-end test) but you almost certainly don't want to integrate it as-is. I'm relatively sure authConnect shouldn't be the one creating the dialer & I don't feel like tracking down where the right place is but something that looks like this.

```
diff --git a/api/client/client.go b/api/client/client.go
index c2ec9efe6..c0f32325e 100644
--- a/api/client/client.go
+++ b/api/client/client.go
@@ -34,6 +34,7 @@ import (
 	"github.com/gravitational/teleport/api/types"
 	"github.com/gravitational/teleport/api/types/events"
 	"github.com/gravitational/teleport/api/utils"
+	utilproxy "github.com/gravitational/teleport/lib/utils/proxy"
 
 	"github.com/golang/protobuf/ptypes/empty"
 	"github.com/gravitational/trace"
@@ -284,6 +285,12 @@ type connectParams struct {
 // authConnect connects to the Teleport Auth Server directly.
 func authConnect(ctx context.Context, params connectParams) (*Client, error) {
 	dialer := NewDirectDialer(params.cfg.KeepAlivePeriod, params.cfg.DialTimeout)
+	proxyAddr := utilproxy.GetProxyAddress(params.addr)
+	if proxyAddr != "" {
+		dialer = ContextDialerFunc(func(ctx context.Context, network, _ string) (conn net.Conn, err error) {
+			return utilproxy.DialProxy(ctx, proxyAddr, params.addr)
+		})
+	}
 	clt := newClient(params.cfg, dialer, params.tlsConfig)
 	if err := clt.dialGRPC(ctx, params.addr); err != nil {
 		return nil, trace.Wrap(err, "failed to connect to addr %v as an auth server", params.addr)
diff --git a/lib/auth/clt.go b/lib/auth/clt.go
index 49a5f23b8..5bc6a672b 100644
--- a/lib/auth/clt.go
+++ b/lib/auth/clt.go
@@ -43,6 +43,7 @@ import (
 	"github.com/gravitational/teleport/lib/services"
 	"github.com/gravitational/teleport/lib/session"
 	"github.com/gravitational/teleport/lib/utils"
+	utilproxy "github.com/gravitational/teleport/lib/utils/proxy"
 
 	"github.com/gravitational/roundtrip"
 	"github.com/gravitational/trace"
@@ -131,7 +132,12 @@ func NewHTTPClient(cfg client.Config, tls *tls.Config, params ...roundtrip.Clien
 		contextDialer := client.NewDirectDialer(cfg.KeepAlivePeriod, cfg.DialTimeout)
 		dialer = client.ContextDialerFunc(func(ctx context.Context, network, _ string) (conn net.Conn, err error) {
 			for _, addr := range cfg.Addrs {
-				conn, err = contextDialer.DialContext(ctx, network, addr)
+				proxyAddr := utilproxy.GetProxyAddress(addr)
+				if proxyAddr == "" {
+					conn, err = contextDialer.DialContext(ctx, network, addr)
+				} else {
+					conn, err = utilproxy.DialProxy(ctx, proxyAddr, addr)
+				}
 				if err == nil {
 					return conn, nil
 				}
diff --git a/lib/utils/proxy/proxy.go b/lib/utils/proxy/proxy.go
index 6aba7c404..88e2c20dd 100644
--- a/lib/utils/proxy/proxy.go
+++ b/lib/utils/proxy/proxy.go
@@ -311,6 +311,10 @@ func dialProxy(ctx context.Context, proxyAddr string, addr string) (net.Conn, er
 	}, nil
 }
 
+func DialProxy(ctx context.Context, proxyAddr string, addr string) (net.Conn, error) {
+	return dialProxy(ctx, proxyAddr, addr)
+}
+
 func getProxyAddress(addr string) string {
 	envs := []string{
 		teleport.HTTPSProxy,
@@ -341,6 +345,10 @@ func getProxyAddress(addr string) string {
 	return ""
 }
 
+func GetProxyAddress(addr string) string {
+	return getProxyAddress(addr)
+}
+
 // bufferedConn is used when part of the data on a connection has already been
 // read by a *bufio.Reader. Reads will first try and read from the
 // *bufio.Reader and when everything has been read, reads will go to the

```

**Comment by russjones** [comment]
@atburke Make sure you test `NO_PROXY` support as well. We have a customer that wants to send all HTTP traffic through their proxy but SSH traffic should not go through the proxy. So I imagine what you want to test is something like `NO_PROXY=localhost:3023` (maybe also 3024, I forget?) will cause only HTTP traffic to be proxied, not SSH traffic.

You also want to test with TLS routing.

File: lib/utils/proxy/proxy.go [hunk 6]
```diff
@@ -56,19 +53,23 @@ func dialWithDeadline(network string, addr string, config *ssh.ClientConfig) (*s
...
 	if err != nil {
 		return nil, trace.Wrap(err)
 	}
-	tlsConn, err := tls.DialWithDialer(dialer, network, addr, &tls.Config{
-		NextProtos:         []string{string(alpncommon.ProtocolReverseTunnel)},
-		InsecureSkipVerify: insecure,
-		ServerName:         address.Host(),
-	})
+	conf := tlsConfig.Clone()
+	if conf == nil {
```
Comment (r0mant) [inline lib/utils/proxy/proxy.go:65]: How can `conf` be nil here?

File: lib/utils/proxy/proxy.go [hunk 7]
```diff
@@ -114,11 +117,15 @@ func (d directDial) DialTimeout(network, address string, timeout time.Duration)
 		if err != nil {
 			return nil, trace.Wrap(err)
 		}
-		tlsConn, err := tls.Dial("tcp", address, &tls.Config{
-			NextProtos:         []string{string(alpncommon.ProtocolReverseTunnel)},
-			InsecureSkipVerify: d.insecure,
-			ServerName:         addr.Host(),
-		})
+		conf := d.tlsConfig.Clone()
+		if conf == nil {
```
Comment (r0mant) [inline lib/utils/proxy/proxy.go:121]: How can `conf` be nil here?

File: lib/utils/proxy/proxy.go [hunk 8]
```diff
@@ -183,11 +196,15 @@ func (d proxyDial) Dial(network string, addr string, config *ssh.ClientConfig) (
...
-		pconn = tls.Client(pconn, &tls.Config{
-			NextProtos:         []string{string(alpncommon.ProtocolReverseTunnel)},
-			InsecureSkipVerify: d.insecure,
-			ServerName:         address.Host(),
-		})
+		conf := d.tlsConfig.Clone()
+		if conf == nil {
+			conf = &tls.Config{
+				NextProtos:         []string{string(alpncommon.ProtocolReverseTunnel)},
+				InsecureSkipVerify: lib.IsInsecureDevMode(),
```
Comment (r0mant) [inline lib/utils/proxy/proxy.go:203]: Why is this using `lib.IsInsecureMode()` while others are using `d.insecure`?

File: lib/client/https_client_test.go [hunk 9]
```diff
@@ -0,0 +1,53 @@
...
+			resp.Body.Close()
+		}
+	}()
+	// Client should try to proxy through nonexistent server at localhost.
+	require.Error(t, err, "GET unexpectedly succeeded: %+v", resp)
+	require.Contains(t, err.Error(), "proxyconnect")
+	require.Contains(t, err.Error(), "no such host")
+}
+
+func TestNewClientWithPoolHTTPProxy(t *testing.T) {
```
Comment (r0mant) [inline lib/client/https_client_test.go:40]: Can you add a test for NO_PROXY case as well?

File: lib/client/api.go [hunk 10]
```diff
@@ -2232,37 +2233,22 @@ func (tc *TeleportClient) connectToProxy(ctx context.Context) (*ProxyClient, err
...
-	}
-	c, chans, reqs, err := ssh.NewClientConn(tlsConn, cfg.WebProxyAddr, sshConfig)
-	if err != nil {
-		// tlsConn is closed inside ssh.NewClientConn function
-		return nil, trace.Wrap(err, "failed to authenticate with proxy %v", cfg.WebProxyAddr)
-	}
-	return ssh.NewClient(c, chans, reqs), nil
-}
-
 func makeProxySSHClient(tc *TeleportClient, sshConfig *ssh.ClientConfig) (*ssh.Client, error) {
```
Comment (r0mant) [inline lib/client/api.go:2236]: I think if we refactor this a bit to keep the method that creates the ssh client over TLS tunnel like before, the code would be cleaner and easier to understand. Something like:

```go
func makeProxySSHClient(tc *TeleportClient, sshConfig *ssh.ClientConfig) (*ssh.Client, error) {
	if tc.Config.TLSRoutingEnabled {
		return makeProxySSHClientWithTLSWrapper(tc, sshConfig)
	}
	return makeProxySSHClientDirect(tc, sshConfig)
}

func makeProxySSHClientDirect(tc *TeleportClient, sshConfig *ssh.ClientConfig) (*ssh.Client, error) {
	dialer := proxy.DialerFromEnvironment(tc.Config.SSHProxyAddr, opts...)
	return dialer.Dial("tcp", tc.Config.SSHProxyAddr, sshConfig)
}

func makeProxySSHClientWithTLSWrapper(tc *TeleportClient, sshConfig *ssh.ClientConfig) (*ssh.Client, error) {
	clientTLSConf, err := tc.loadTLSConfig()
	if err != nil {
		return nil, trace.Wrap(err)
	}

	clientTLSConf.NextProtos = []string{string(alpncommon.ProtocolProxySSH)}
	clientTLSConf.InsecureSkipVerify = tc.Config.InsecureSkipVerify

	dialer := proxy.DialerFromEnvironment(tc.Config.WebProxyAddr,
		proxy.WithALPNDialer(), proxy.WithTLSConfig(tlsConfig))

	return dialer.Dial("tcp", tc.Config.WebProxyAddr, sshConfig)
}
```

File: lib/utils/proxy/proxy.go [hunk 11]
```diff
@@ -158,11 +167,15 @@ func (d proxyDial) DialTimeout(network, address string, timeout time.Duration) (
 		if err != nil {
 			return nil, trace.Wrap(err)
 		}
-		conn = tls.Client(conn, &tls.Config{
-			NextProtos:         []string{string(alpncommon.ProtocolReverseTunnel)},
-			InsecureSkipVerify: d.insecure,
-			ServerName:         address.Host(),
-		})
+		conf := d.tlsConfig.Clone()
+		if conf == nil {
```
Comment (r0mant) [inline lib/utils/proxy/proxy.go:171]: Same q as above.

File: lib/utils/proxy/proxy.go [hunk 12]
```diff
@@ -149,7 +158,7 @@ func (d proxyDial) DialTimeout(network, address string, timeout time.Duration) (
 		defer cancel()
 		ctx = timeoutCtx
 	}
-	conn, err := dialProxy(ctx, d.proxyHost, address)
+	conn, err := apiclient.DialProxy(ctx, d.proxyHost, address, nil)
```
Comment (r0mant) [inline lib/utils/proxy/proxy.go:161]: Why are we passing `nil` here?

File: lib/utils/proxy/proxy.go [hunk 13]
```diff
@@ -183,11 +196,15 @@ func (d proxyDial) Dial(network string, addr string, config *ssh.ClientConfig) (
 		if err != nil {
 			return nil, trace.Wrap(err)
 		}
-		pconn = tls.Client(pconn, &tls.Config{
-			NextProtos:         []string{string(alpncommon.ProtocolReverseTunnel)},
-			InsecureSkipVerify: d.insecure,
-			ServerName:         address.Host(),
-		})
+		conf := d.tlsConfig.Clone()
+		if conf == nil {
```
Comment (r0mant) [inline lib/utils/proxy/proxy.go:200]: Same q as above.

**Review by r0mant — CHANGES_REQUESTED** [review]

File: lib/utils/proxy/proxy.go (hunk 6 above)
Comment (atburke) [reply lib/utils/proxy/proxy.go:65]: `conf` can be nil when the caller doesn't use `proxy.WithTLSConfig()` to use a custom tls config.

File: lib/utils/proxy/proxy.go (hunk 12 above)
Comment (atburke) [reply lib/utils/proxy/proxy.go:161]: This tells `DialProxy` to use the default `net.Dialer` instead of a passed in dialer. Would it be clearer to always pass in the dialer, or to do something else?

File: lib/utils/proxy/proxy.go (hunk 6 above)
Comment (r0mant) [reply lib/utils/proxy/proxy.go:64]: To be honest, I'm not sure I fully understand this tlsConfig logic. Why are we setting NextProtos to `ProtocolReverseTunnel` here in what (I think) is supposed to be a generic proxy, but only in the case when tlsConfig wasn't passed in?

@smallinsky Can you take a look at these changes too pls - do you remember why we're setting ProtocolReverseTunnel here? Is this proxy supposed to be used by the agents only? Just want to make sure we don't break any scenarios.

Is this proxy is now used by both reverse tunnel agents and tsh, I wonder if we should make the TLS config mandatory and have the caller pass it appropriately.

Comment (atburke) [reply lib/utils/proxy/proxy.go:64]: `ProtocolReverseTunnel` is the default from before the tls config was injected. As long as it doesn't break anything, I think making tls config mandatory is the way to go.

Comment (smallinsky) [reply lib/utils/proxy/proxy.go:64]: > do you remember why we're setting ProtocolReverseTunnel here?

The name of the dialer is misleading. It is used in `TunnelAuthDialer` and Reverse tunnel Agent call so under the hood it is Reverse Tunnel Dialer where a connection is established to Reverse tunnel service thus in case of TLSRouting mode the `alpncommon.ProtocolReverseTunnel` protocol is set.

File: lib/client/api.go [hunk 14]
```diff
@@ -2232,37 +2233,28 @@ func (tc *TeleportClient) connectToProxy(ctx context.Context) (*ProxyClient, err
...
+	tlsConfig, err := tc.loadTLSConfig()
 	if err != nil {
-		return nil, trace.Wrap(err, "failed to authenticate with proxy %v", tc.Config.SSHProxyAddr)
+		return nil, trace.Wrap(err)
 	}
-	return client, nil
+	tlsConfig.NextProtos = []string{string(alpncommon.ProtocolProxySSH)}
+	tlsConfig.InsecureSkipVerify = tc.Config.InsecureSkipVerify
+
+	dialer := proxy.DialerFromEnvironment(tc.Config.WebProxyAddr, proxy.WithALPNDialer(), proxy.WithTLSConfig(tlsConfig))
```
Comment (smallinsky) [inline lib/client/api.go:2256]: Right it looks that if `proxy.WithTLSConfig(tlsConfig)` was set with `[]string{string(alpncommon.ProtocolProxySSH)}` the `proxy.WithALPNDialer()` option is also required
I think that it can be cleaned by adding the ability to set forward correct ALPNProtocol  by extending `WithALPNDialer` -> `func WithALPNDialer(protocol ...)`

**Review by smallinsky — COMMENTED** [review]
@russjones 
> NO_PROXY support. We have a customer that wants to send all HTTP traffic through their proxy but SSH traffic should not go through the proxy (so this is mode (1) above). So I imagine what you want to test is something like NO_PROXY=localhost:3023 (maybe also 3024, I forget?) will cause only HTTP traffic to be proxied, not SSH traffic.

I don't think that it will work because right now NO_PROXY can only distinguish addr based on host. NO_PROXY=`example.com:1234` will lead to NO proxy behaviouir for all `example.com` calls. 

https://github.com/gravitational/teleport/blob/740d184d1cfc69ae2e96c50ee738b13884fb232b/lib/utils/proxy/noproxy.go#L51

File: lib/utils/proxy/proxy.go [hunk 15]
```diff
@@ -56,19 +51,18 @@ func dialWithDeadline(network string, addr string, config *ssh.ClientConfig) (*s
...
 		return nil, trace.Wrap(err)
 	}
-	tlsConn, err := tls.DialWithDialer(dialer, network, addr, &tls.Config{
-		NextProtos:         []string{string(alpncommon.ProtocolReverseTunnel)},
-		InsecureSkipVerify: insecure,
-		ServerName:         address.Host(),
-	})
+	conf := d.tlsConfig.Clone()
+	conf.ServerName = address.Host()
+	conf.InsecureSkipVerify = d.insecure
```
Comment (r0mant) [inline lib/utils/proxy/proxy.go:64]: Couple of things:

1. This block repeats multiple times in the directDial and proxyDial. Can it be encapsulated into some `getTLSConfig()` method on them?
2. The DialerFromEnvironment contract doesn't actually prevent anyone from creating it without TLS config so it still can potentially be nil and lead to a panic here. Should we explicitly return an error in this case?

```go
func (d directDial) getTLSConfig(addr <type>) (*tls.Config, error) {
  if d.tlsConfig == nil {
    return nil, trace.BadParameter("directDial TLS config was nil")
  }
  tlsConfig := d.tlsConfig.Clone()
  tlsConfig.ServerName = addr.Host()
  tlsConfig.InsecureSkipVerify = d.insecure
  return tlsConfig, nil
}

func (d proxyDial) getTLSConfig(addr <type>) (*tls.Config, error) {
  // same
}
```

**Review by r0mant — APPROVED** [review]
@smallinsky Could you please give this another look? FYI we have pushed the NO_PROXY respecting ports work to a follow up PR.

File: api/client/proxy.go [hunk 16]
```diff
@@ -0,0 +1,150 @@
...
+	"github.com/siddontang/go/log"
+)
+
+// DialProxy creates a connection to a server via an HTTP Proxy.
+func DialProxy(ctx context.Context, proxyAddr, addr string) (net.Conn, error) {
+	return DialProxyWithDialer(ctx, proxyAddr, addr, &net.Dialer{})
+}
+
+// DialProxyWithDialer creates a connection to a server via an HTTP Proxy using a specified dialer.
+func DialProxyWithDialer(ctx context.Context, proxyAddr, addr string, dialer ContextDialer) (net.Conn, error) {
```
Comment (smallinsky) [inline api/client/proxy.go:39]: nit:
We can combined this using optional parameters but leaving it up to you. 

```func DialProxy(ctx context.Context, proxyAddr, addr string, opts ...dialOptions)```

File: api/client/webclient/webclient.go [hunk 17]
```diff
@@ -46,6 +47,9 @@ func newWebClient(insecure bool, pool *x509.CertPool) *http.Client {
 				RootCAs:            pool,
 				InsecureSkipVerify: insecure,
 			},
+			Proxy: func(req *http.Request) (*url.URL, error) {
+				return httpproxy.FromEnvironment().ProxyFunc()(req.URL)
+			},
```
Comment (smallinsky) [inline api/client/webclient/webclient.go:52]:
```suggestion
			Proxy: httpproxy.FromEnvironment().ProxyFunc(),
```

File: api/client/proxy.go [hunk 18]
```diff
@@ -0,0 +1,150 @@
...
+	"context"
+	"net"
+	"net/http"
+	"net/url"
+	"os"
+	"strings"
+
+	"github.com/gravitational/teleport/api/constants"
+	"github.com/gravitational/trace"
+	"github.com/siddontang/go/log"
```
Comment (smallinsky) [inline api/client/proxy.go:30]: I don't recall that we are using `siddontang` for logging. Probably this was IDE auto import and it should be switched to `Logrus` instead.

**Review by smallinsky — APPROVED** [review]
Left some nit comments otherwise LGTM.

File: api/client/webclient/webclient.go (hunk 17 above)
Comment (atburke) [reply api/client/webclient/webclient.go:52]: @codingllama Can you take one more look at this when you have a moment?

**Comment by atburke** [comment]
@codingllama Can you take one more look at this when you have a moment?

File: api/client/webclient/webclient.go (hunk 17 above)
Comment (atburke) [reply api/client/webclient/webclient.go:52]: This would be nice, but the function returned by `ProxyFunc()` expects a URL while `Proxy:` expects it to be a Request.

File: api/client/contextdialer.go [hunk 19]
```diff
@@ -52,6 +52,18 @@ func NewDirectDialer(keepAlivePeriod, dialTimeout time.Duration) ContextDialer {
 	}
 }
 
+// NewDialer makes a new dialer that connects to an Auth server either directly or via an HTTP proxy, depending
+// on the environment.
+func NewDialer(keepAlivePeriod, dialTimeout time.Duration) ContextDialer {
```
Comment (codingllama) [inline api/client/contextdialer.go:57]: What is the distinction, now, between NewDialer and NewDirectDialer? Should NewDialer be favored?

Could we make NewDirectDialer private? If not, please document the distinction in both method's godocs.

File: api/client/contextdialer.go [hunk 20]
```diff
@@ -52,6 +52,18 @@ func NewDirectDialer(keepAlivePeriod, dialTimeout time.Duration) ContextDialer {
...
+	dialer := NewDirectDialer(keepAlivePeriod, dialTimeout)
+	return ContextDialerFunc(func(ctx context.Context, network, addr string) (net.Conn, error) {
+		if proxyAddr := GetProxyAddress(addr); proxyAddr != "" {
```
Comment (codingllama) [inline api/client/contextdialer.go:60]: nit: push to the smaller scope?

```suggestion
	return ContextDialerFunc(func(ctx context.Context, network, addr string) (net.Conn, error) {
				dialer := NewDirectDialer(keepAlivePeriod, dialTimeout)
				if proxyAddr := GetProxyAddress(addr); proxyAddr != "" {
```

File: api/client/proxy.go [hunk 21]
```diff
@@ -0,0 +1,150 @@
...
+	}
+
+	connectReq := &http.Request{
+		Method: http.MethodConnect,
+		URL:    &url.URL{Opaque: addr},
+		Host:   addr,
+		Header: make(http.Header),
+	}
+	err = connectReq.Write(conn)
+	if err != nil {
```
Comment (codingllama) [inline api/client/proxy.go:53]: nit: push to smaller scope

```suggestion
	if err := connectReq.Write(conn); err != nil {
```

File: api/client/webclient/webclient_test.go [hunk 22]
```diff
@@ -289,3 +289,25 @@ func TestExtract(t *testing.T) {
...
+	require.Contains(t, err.Error(), "no such host")
+}
+
+func TestNewWebClientNoProxy(t *testing.T) {
+	t.Setenv("HTTPS_PROXY", "fakeproxy.example.com:9999")
+	t.Setenv("NO_PROXY", "example.com")
+	client := newWebClient(false /* insecure */, nil /* pool */)
+	resp, err := client.Get("https://example.com")
+	require.NoError(t, err)
+	defer resp.Body.Close()
```
Comment (codingllama) [inline api/client/webclient/webclient_test.go:311]: nit: drain and close.

```suggestion
	io.Copy(io.Discard, resp.Body)
	resp.Body.Close()
```

File: lib/client/https_client_test.go [hunk 23]
```diff
@@ -0,0 +1,68 @@
...
+	require.Error(t, err, "GET unexpectedly succeeded: %+v", resp)
+	require.Contains(t, err.Error(), "proxyconnect")
+	require.Contains(t, err.Error(), "no such host")
+}
+
+func TestNewInsecureWebClientNoProxy(t *testing.T) {
+	t.Setenv("HTTPS_PROXY", "fakeproxy.example.com:9999")
+	t.Setenv("NO_PROXY", "example.com")
+	client := NewInsecureWebClient()
+	resp, err := client.Get("https://example.com")
```
Comment (codingllama) [inline lib/client/https_client_test.go:42]: Could we remove the test dependency from example.com? Maybe hit a localhost port we control instead?

It seems off to have our tests depend on example.com being up.

File: lib/client/https_client_test.go [hunk 24]
```diff
@@ -0,0 +1,68 @@
...
+	require.Error(t, err, "GET unexpectedly succeeded: %+v", resp)
+	require.Contains(t, err.Error(), "proxyconnect")
+	require.Contains(t, err.Error(), "no such host")
+}
+
+func TestNewClientWithPoolNoProxy(t *testing.T) {
+	t.Setenv("HTTPS_PROXY", "fakeproxy.example.com:9999")
+	t.Setenv("NO_PROXY", "example.com")
+	client := newClientWithPool(nil)
+	resp, err := client.Get("https://example.com")
```
Comment (codingllama) [inline lib/client/https_client_test.go:64]: Same as above, could we remove the test dependency from example.com?

**Review by codingllama — COMMENTED** [review]
Mostly minor comments. Sorry about the delay.

**Review by codingllama — APPROVED** [review]
