### PR TITLE
Fix flaky test `TestTeleterm/Test_headless_watcher`

### LINKED ISSUE #30044: `TestTeleterm/Test_headless_watcher` flakiness
https://github.com/gravitational/teleport/actions/runs/5763608694/job/15625793973
```
=== FAIL: integration TestTeleterm/Test_headless_watcher (1.07s)
    teleterm_test.go:88: 
        	Error Trace:	/__w/teleport/teleport/integration/teleterm_test.go:304
        	            				/__w/teleport/teleport/integration/teleterm_test.go:88
        	Error:      	Condition never satisfied
        	Test:       	TestTeleterm/Test_headless_watcher
```

### PR DESCRIPTION
**Pull request by Joerger**
Fix flaky test by waiting for Teleport Connect headless watcher to finish initializing in tests. 

Generally, we don't want to wait for the watcher to initialize as this could slow down Teleport Connect during startup and login. The headless watcher is not critical enough to warrant this slowdown, IMO.

Closes https://github.com/gravitational/teleport/issues/30044

### CODE REVIEW

File: integration/teleterm_test.go [hunk 1]
```diff
@@ -290,20 +290,19 @@ func testHeadlessWatcher(t *testing.T, pack *dbhelpers.DatabasePack, creds *help
 		tshdEventsService.sendPendingHeadlessAuthenticationCount.Store(0)
 
 		err = pack.Root.Cluster.Process.GetAuthServer().UpsertHeadlessAuthentication(ctx, ha)
-		require.NoError(t, err)
+		assert.NoError(t, err)
 
 		assert.Eventually(t, func() bool {
 			return tshdEventsService.sendPendingHeadlessAuthenticationCount.Load() == 1
-		}, 100*time.Millisecond, 20*time.Millisecond, "Expected tshdEventService to receive a SendPendingHeadlessAuthentication message")
+		}, time.Second, 200*time.Millisecond, "Expected tshdEventService to receive 1 SendPendingHeadlessAuthentication message but got %v", tshdEventsService.sendPendingHeadlessAuthenticationCount.Load())
```
Comment (r0mant) [inline integration/teleterm_test.go:297]: Should we just set this to 5 seconds as well? 1 second seems too short still.

File: integration/teleterm_test.go [hunk 2]
```diff
@@ -317,8 +316,8 @@ func testHeadlessWatcher(t *testing.T, pack *dbhelpers.DatabasePack, creds *help
 	// Ensure the watcher catches events and sends them to the Electron App.
 
 	require.EventuallyWithT(t, func(collect *assert.CollectT) {
-		eventuallyCatchAndSendHeadlessAuthn(collect)
-	}, time.Second, 100*time.Millisecond)
+		eventuallyCatchAndSendHeadlessAuthn(t)
```
Comment (zmb3) [inline integration/teleterm_test.go:319]: I'm not sure I fully understand `EventuallyWithT`. Should we be using `collect` here?

File: integration/helpers/internal.go [hunk 3]
```diff
@@ -40,7 +40,7 @@ func StartAndWait(process *service.TeleportProcess, expectedEvents []string) ([]
 	// wait for all events to arrive or a timeout. if all the expected events
 	// from above are not received, this instance will not start
 	receivedEvents := make([]service.Event, 0, len(expectedEvents))
-	ctx, cancel := context.WithTimeout(process.ExitContext(), 10*time.Second)
+	ctx, cancel := context.WithTimeout(process.ExitContext(), 30*time.Second)
```
Comment (Joerger) [inline integration/helpers/internal.go:43]: During testing, I found that this was also causing flaky tests.

File: lib/teleterm/daemon/daemon_headless.go [hunk 4]
```diff
@@ -134,6 +140,21 @@ func (s *Service) startHeadlessWatcher(cluster *clusters.Cluster) error {
 		}
 		defer closeResolutionWatcher()
 
+		// Wait for the pending watcher to finish initializing. the resolution watcher is not as critical,
+		// so we skip waiting for it.
+
+		select {
+		case event := <-pendingWatcher.Events():
+			if event.Type != types.OpInit {
+				return trace.ConnectionProblem(nil, "unexpected event type %q", event.Type)
```
Comment (zmb3) [inline lib/teleterm/daemon/daemon_headless.go:149]: Is BadParameter more appropriate than ConnectionProblem here?

File: integration/teleterm_test.go [hunk 5]
```diff
@@ -272,53 +272,34 @@ func testHeadlessWatcher(t *testing.T, pack *dbhelpers.DatabasePack, creds *help
...
 
-	require.EventuallyWithT(t, func(collect *assert.CollectT) {
-		eventuallyCatchAndSendHeadlessAuthn(collect)
-	}, time.Second, 100*time.Millisecond)
+	err = pack.Root.Cluster.Process.GetAuthServer().UpsertHeadlessAuthentication(ctx, ha)
+	assert.NoError(t, err)
+
+	assert.Eventually(t, func() bool {
+		return tshdEventsService.sendPendingHeadlessAuthenticationCount.Load() == 1
+	}, 10*time.Second, 500*time.Millisecond, "Expected tshdEventService to receive 1 SendPendingHeadlessAuthentication message but got %v", tshdEventsService.sendPendingHeadlessAuthenticationCount.Load())
```
Comment (zmb3) [inline integration/teleterm_test.go:302]: can we break up this long line?

**Review by zmb3 — APPROVED** [review]

**Review by ravicious — APPROVED** [review]
