### PR TITLE
Extend timeout for child process continue signal

### LINKED ISSUE #46515: `WaitForChild` function times out waiting for "continue signal" during user session startup
### Current and Expected behaviors:

In the event that a misconfiguration or heavy load slows down a login process, Teleport should still allow that to progress. Instead, there is a hard-coded 20 second timeout.

This was observed on a system that had `sssd` configured to use an LDAP source. The user was in lots of groups, and the LDAP endpoint that was specified was in the wrong region.

The user should still be able to access the system, even if it takes longer than 20 seconds. As it stands, the user is locked out and must use an alternate method to access the server to fix the problem.

Specifically, this appears to be the `WaitForChild` function within `lib/srv/term.go`.

This was first observed on v14.3.21

https://github.com/gravitational/teleport/blob/v14.3.21/lib/srv/term.go#L250-L256

It is reproducible in v16.2.2

https://github.com/gravitational/teleport/blob/v16.2.2/lib/srv/term.go#L263-L269

This is a separate timeout from the recently implemented `ssh_dial_timeout` configurable setting.

https://github.com/gravitational/teleport/pull/45507

`ssh_dial_timeout` affects how SSH clients determine when a remote SSH server has taken too long to respond. This 20 second WaitForChild timeout gets in the way in a more specific situation, so the default 30 second `ssh_dial_timeout` is never reached.

#### Debug Logs ####

When a user tries to connect, it will sit for 20 seconds and then say EOF. (tsh debug log omitted for brevity)

```
% tsh ssh user@node03
ERROR: EOF
```

This appears in the node's logs at the same time the user-facing "EOF" appears:

```
    Sep  9 20:13:56 node03 teleport: ERROR REPORT:
    Sep  9 20:13:56 node03 teleport: Original Error: trace.aggregate timed out waiting for continue signal
    Sep  9 20:13:56 node03 teleport: Stack Trace:
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/term.go:255 github.com/gravitational/teleport/lib/srv.(*terminal).WaitForChild
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/sess.go:1302 github.com/gravitational/teleport/lib/srv.(*session).startInteractive
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/sess.go:345 github.com/gravitational/teleport/lib/srv.(*SessionRegistry).OpenSession
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/termhandlers.go:126 github.com/gravitational/teleport/lib/srv.(*TermHandlers).HandleShell
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1767 github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1632 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1399 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1
    Sep  9 20:13:56 node03 teleport: runtime/asm_amd64.s:1650 runtime.goexit
```

The session fails due to the hardcoded 20-second timeout in `WaitForChild`, which is not enough time for user information resolution in some cases, especially when directory services are misconfigured or slow.

### Bug details:
- **Teleport version**: `v16.2.2` (but issue affects other versions, as seen from different stack traces)
- **Recreation steps**:
  1. Configure Teleport to authenticate users using an LDAP-backed directory service (e.g., `sssd`).
  2. Point `sssd` to an LDAP or Active Directory service in a different region or with a misconfiguration.
  3. Attempt to log in as an LDAP user via SSH.
  4. The session fails due to the 20-second timeout, as Teleport closes the connection while waiting for the child process to signal readiness.
  
- **Debug logs**:
  Relevant stack trace:
  ```
    Sep  9 20:13:56 node03 teleport: ERROR REPORT:
    Sep  9 20:13:56 node03 teleport: Original Error: trace.aggregate timed out waiting for continue signal
    Sep  9 20:13:56 node03 teleport: Stack Trace:
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/term.go:255 github.com/gravitational/teleport/lib/srv.(*terminal).WaitForChild
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/sess.go:1302 github.com/gravitational/teleport/lib/srv.(*session).startInteractive
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/sess.go:345 github.com/gravitational/teleport/lib/srv.(*SessionRegistry).OpenSession
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/termhandlers.go:126 github.com/gravitational/teleport/lib/srv.(*TermHandlers).HandleShell
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1767 github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1632 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
    Sep  9 20:13:56 node03 teleport: github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1399 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1
    Sep  9 20:13:56 node03 teleport: runtime/asm_amd64.s:1650 runtime.goexit
  ```

### Recreate steps

Any early login delay that exceeds 20 seconds can trigger the same behavior. The easiest approach I found:

Enable PAM integration on the Teleport node.

Put this script at `/usr/local/bin/pam_delay.sh` and make it executable.

```bash
#!/bin/bash
sleep 20
exit 0
```

Add `session required pam_exec.so /usr/local/bin/pam_delay.sh` to the pam profile.

Now every attempt to connect will fail after 20 seconds, effectively locking every user out of the system. (reproduced on 16.2.2)

### Proposed Solution

I tried to find an analagous limit in other sshd implementations, and didn't see anything that was relevant. It might make sense to _completely remove_ this timeout rather than bother with making it configurable. A very large value might also be appropriate.

### PR DESCRIPTION
**Pull request by Joerger**
Extend the timeout for child process continue signal to 3 minutes to account for long PAM setup times. This timeout should be long enough that it is never hit in reasonable configurations. The only reason we keep the timeout at all is to prevent failed shells from hogging resources endlessly, working in tandem with the new canceled context select case for when the end client gives up on the connection.

Manual tests (c3c2417):
- Following the repro steps in the issue below, setup a PAM module with a 20 second sleep. In each of the tests below, the session should succeed after the 20 second timeout
- [x] Proxy recording mode (remote terminal / exec)
  - [x] Enable BPF recording
    - [x] exec session
    - [x] interactive session
  - [x] Disable BPF recording 
    - [x] exec session
    - [x] interactive session
- [x] Node recording mode
  - [x] Enable BPF recording
    - [x] exec session
    - [x] interactive session
  - [x] Disable BPF recording 
    - [x] exec session
    - [x] interactive session

Closes https://github.com/gravitational/teleport/issues/46515

### CODE REVIEW

File: lib/srv/exec.go [hunk 1]
```diff
@@ -51,6 +51,10 @@ const (
 	defaultEnvRootPath   = "PATH=" + defaultRootPath
 	defaultTerm          = "xterm"
 	defaultLoginDefsPath = "/etc/login.defs"
+
+	// The child does not signal until completing PAM setup, which can take an arbitrary
+	// amount of time, so we use a reasonably long timeout to avoid dubious lockouts.
+	childContinueWaitTimeout = 3 * time.Minute
```
Comment (rosstimothy) [inline lib/srv/exec.go]: Does this apply to all sessions or just those sessions which leverage PAM? If the latter should we dynamically adjust the wait time if a session will be making use of PAM?

Comment (capnspacehook) [inline lib/srv/exec.go]: I think the name is a bit confusing, as this timeout is only used when waiting on `ServerContext.readyr`, while `ServerContext.cont{r,w}` also exist. Maybe rename to `childReadyWaitTimeout` or something similar?

Comment (Joerger) [reply lib/srv/exec.go]: We only need to wait for the child when PAM and BPF are both enabled, so no need to change the timeout. Instead, I've updated the logic to be clear about waiting only in this scenario for both shell and exec sessions - a148db409f3ba75ab53d7c9ec43646f338ee9a57.

File: lib/srv/ctx.go [hunk 2]
```diff
@@ -1330,3 +1330,36 @@ func (c *ServerContext) ConsumeApprovedFileTransferRequest() *FileTransferReques
...
 }
+
+// The child does not signal until completing PAM setup, which can take an arbitrary
+// amount of time, so we use a reasonably long timeout to avoid dubious lockouts.
+const childReadyWaitTimeout = 3 * time.Minute
+
+// WaitForChild waits for the child process to signal ready through the named pipe.
+func (c *ServerContext) WaitForChild(ctx context.Context) error {
+	bpfService := c.srv.GetBPF()
+	pam, err := c.srv.GetPAM()
```
Comment (rosstimothy) [inline lib/srv/ctx.go]: It feels wrong to bail with an here with an error if PAM is not supported. What do you think about changing the GetPAM signature to remove the error and have any implementations that don't support PAM always return `servicecfg.PAMConfig.Enabled: false` instead of an error?

File: lib/srv/reexec.go [hunk 3]
```diff
@@ -1416,3 +1416,30 @@ func (o *osWrapper) newParker(ctx context.Context, credential syscall.Credential
...
+	timer := time.NewTimer(timeout)
+	defer timer.Stop()
+
+	select {
+	case <-ctx.Done():
+		return trace.Wrap(ctx.Err(), "got context error while waiting for continue signal")
+	case <-timer.C:
+		return trace.LimitExceeded("timed out waiting for continue signal")
+	case err := <-waitCh:
+		return err
```
Comment (rosstimothy) [inline lib/srv/reexec.go]:
```suggestion
		return trace.Wrap(err)
```

File: lib/srv/ctx.go [hunk 4]
```diff
@@ -1330,3 +1326,34 @@ func (c *ServerContext) ConsumeApprovedFileTransferRequest() *FileTransferReques
...
+		if err = waitForSignal(ctx, c.readyr, childReadyWaitTimeout); err != nil {
+			c.Logger.ErrorContext(ctx, "Child process never became ready.", "error", err)
+			return trace.Wrap(err)
+		}
+	}
+
+	closeErr := c.readyr.Close()
+	// Set to nil so the close in the context doesn't attempt to re-close.
+	c.readyr = nil
+	return trace.NewAggregate(err, closeErr)
```
Comment (rosstimothy) [inline lib/srv/ctx.go]: Won't the error from waitForSignal always be handled directly in the inner if? Is there any need to include it below as well?
```suggestion
	if bpfService.Enabled() && pam.Enabled {
		if err := waitForSignal(ctx, c.readyr, childReadyWaitTimeout); err != nil {
			c.Logger.ErrorContext(ctx, "Child process never became ready.", "error", err)
			return trace.Wrap(err)
		}
	}

	err := c.readyr.Close()
	// Set to nil so the close in the context doesn't attempt to re-close.
	c.readyr = nil
	return trace.Wrap(err)
```

File: lib/srv/ctx.go [hunk 5]
```diff
@@ -1330,3 +1326,33 @@ func (c *ServerContext) ConsumeApprovedFileTransferRequest() *FileTransferReques
 
 	return req
 }
+
+// The child does not signal until completing PAM setup, which can take an arbitrary
+// amount of time, so we use a reasonably long timeout to avoid dubious lockouts.
+const childReadyWaitTimeout = 3 * time.Minute
```
Comment (rosstimothy) [inline lib/srv/ctx.go:1332]: What happens if PAM takes 5 minutes?

Comment (Joerger) [reply lib/srv/ctx.go:1332]: Then it will timeout after 3 minutes. I think having PAM take longer than 3 minutes is probably an unreasonable configuration, but If that becomes an issue, we can push this timeout further back or remove it.

File: lib/srv/exec.go [hunk 6]
```diff
@@ -414,7 +385,7 @@ func (e *remoteExec) Wait() *ExecResult {
 	}
 }
 
-func (e *remoteExec) WaitForChild() error { return nil }
+func (e *remoteExec) WaitForChild(_ context.Context) error { return nil }
```
Comment (rosstimothy) [inline lib/srv/exec.go]: Alternatively we could omit the variable name entirely since there is only one variable.
```suggestion
func (e *remoteExec) WaitForChild(context.Context) error { return nil }
```

File: lib/srv/term.go [hunk 7]
```diff
@@ -617,7 +613,7 @@ func (t *remoteTerminal) Wait() (*ExecResult, error) {
 	}, nil
 }
 
-func (t *remoteTerminal) WaitForChild() error {
+func (t *remoteTerminal) WaitForChild(_ context.Context) error {
```
Comment (rosstimothy) [inline lib/srv/term.go]: If you take the suggestion from above.
```suggestion
func (t *remoteTerminal) WaitForChild(context.Context) error {
```

File: lib/srv/sess.go [hunk 8]
```diff
@@ -1455,30 +1455,11 @@ func (s *session) startInteractive(ctx context.Context, scx *ServerContext, p *p
...
-		}
-	} else {
-		// Clean up the read half of the pipe, and set it to nil so that when the
-		// ServerContext is closed it doesn't attempt to a second close.
-		if err := s.scx.readyr.Close(); err != nil {
-			s.logger.ErrorContext(ctx, "Failed closing child ready pipe", "error", err)
-		}
-		s.scx.readyr = nil
+	if err := s.term.WaitForChild(ctx); err != nil {
+		return trace.Wrap(err)
```
Comment (rosstimothy) [inline lib/srv/sess.go:1459]: Should we keep the error log around to know when this is happening?
```suggestion
		s.logger.ErrorContext(ctx, "Child process never became ready.", "error", err)
		return trace.Wrap(err)
```

File: lib/srv/sess.go [hunk 9]
```diff
@@ -1671,8 +1652,7 @@ func (s *session) startExec(ctx context.Context, channel ssh.Channel, scx *Serve
 		Events:                eventsMap,
 	}
 
-	if err := execRequest.WaitForChild(); err != nil {
-		s.logger.ErrorContext(ctx, "Child process never became ready.", "error", err)
```
Comment (rosstimothy) [inline lib/srv/sess.go:1675]: Should we keep the error log around to know when this is happening?

File: lib/srv/sess.go (hunk 8 above)
Comment (Joerger) [reply lib/srv/sess.go:1459]: I relocated this log with the wait logic - https://github.com/gravitational/teleport/blob/2d93965f1508f50b75790818d973568825710bbf/lib/srv/ctx.go#L1350

**Review by rosstimothy — APPROVED** [review]

**Comment by Joerger** [comment]
@aadc-dev @greedy52 @capnspacehook Friendly ping to review

**Review by greedy52 — APPROVED** [review]

**Comment by Joerger** [comment]
@rosstimothy Can you give this a flaky test skip? It times out.

**Review by capnspacehook — APPROVED** [review]
