### PR TITLE
Fix Per-session MFA for leaf apps

### LINKED ISSUE #51350: App MFA disable keeps failing MFA challenge
Expected behavior:

When I have a role to access an application with MFA disabled, even when there is other roles with different allows with MFA enabled, I expect to be able to access the application. 

Current behavior:
It returns 

Image

Bug details:
- Teleport version: v17.1.6

**Recreation steps:** 
Root leaf architecture.  Kubernetes auto discovery
```yaml
    discovery_service:
      discovery_group: cicd-eu-aug24
      enabled: true
      kubernetes:
      - labels:
          foo/teleport-app: "true"
        namespaces:
        - '*'
        types:
        - app
```

App object
```
kind: app
metadata:
  description: Discovered application in Kubernetes cluster "cicd-eu-aug24"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.13.2
    helm.sh/chart: argo-cd-7.7.10
    foo/teleport-app: "true"
    teleport.dev/discovery-type: app
    teleport.dev/kubernetes-cluster: cicd-eu-aug24
    teleport.dev/origin: discovery-kubernetes
    teleport.internal/discovery-group-name: cicd-eu-aug24
  name: argocd
  revision: acf49a4b-c044-488d-8bb5-3d46e84aff8e
spec:
  insecure_skip_verify: false
  uri: http://argo-argocd-server.argocd-system.svc.cluster.local:80
version: v3
```

Image

User has 2 roles: 

One for the application. Same role in the root and the leaf that are mapped in trusted cluster
```yaml
kind: role
metadata:
  labels:
    teleport.dev/origin: kubernetes
  name: argocd-read-access
spec:
  allow:
    app_labels:
      app.kubernetes.io/name: argocd-server
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v7
```
Other for SSH access 
```yaml
kind: role
metadata:
  labels:
    teleport.dev/origin: kubernetes
  name: server-access
spec:
  allow:
    logins:
    - ec2-user
    node_labels:
      Owner: foo
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: true
    idp:
      saml:
        enabled: true
    max_session_ttl: 30h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    require_session_mfa: true
    ssh_file_copy: true
version: v7
```

If I set `require_session_mfa: false` on the server-access role, Im able to access the application.

Another test that I did for troubleshooting before I found the MFA thing, was to add the same app in the root cluster that just points the uri the one defined in the leaf and it works. In this scenario MFA is not an issue. Not sure why. 
```
apps:
  - name: "argocd"
    uri: "<uri defined in leaf app>"
    labels:
      visibility_control: "hide_from_root"
```

### PR DESCRIPTION
**Pull request by Joerger**
MFA for app access in the WebUI mistakenly used the user's root client to check if mfa is required when connecting to a leaf app:

```go
	// MFA verification should run in the cluster that holds the target resource.
	// If you are issuing challenges from the root cluster, but accessing a leaf,
	// call [AuthService.IsMFARequired] in the leaf instead of setting this field.
	MFARequiredCheck *IsMFARequiredRequest `protobuf:"bytes,5,opt,name=MFARequiredCheck,proto3" json:"mfa_required_check,omitempty"`
```

Fixes https://github.com/gravitational/teleport/issues/51350

Changelog: Fix connecting to Apps in a leaf cluster when Per-session MFA is enabled.

### CODE REVIEW

**Review by ravicious — APPROVED** [review]

File: lib/web/mfa.go [hunk 1]
```diff
@@ -180,6 +180,8 @@ type createAuthenticateChallengeRequest struct {
 // createAuthenticateChallengeHandle creates and returns MFA authentication challenges for the user in context (logged in user).
 // Used when users need to re-authenticate their second factors.
 func (h *Handler) createAuthenticateChallengeHandle(w http.ResponseWriter, r *http.Request, p httprouter.Params, c *SessionContext) (interface{}, error) {
+	ctx := r.Context()
```
Comment (flyinghermit) [inline lib/web/mfa.go:183]: why not use `r.Context()`?

File: lib/web/mfa.go [hunk 2]
```diff
@@ -192,10 +194,36 @@ func (h *Handler) createAuthenticateChallengeHandle(w http.ResponseWriter, r *ht
...
 	if req.IsMFARequiredRequest != nil {
-		mfaRequiredCheckProto, err = h.checkAndGetProtoRequest(r.Context(), c, req.IsMFARequiredRequest)
+		mfaRequiredCheckProto, err = h.checkAndGetProtoRequest(ctx, c, req.IsMFARequiredRequest)
 		if err != nil {
 			return nil, trace.Wrap(err)
 		}
+
+		// If the MFA requirement check is being performed for a leaf host, we must check directly
+		// with the leaf cluster before the authentication challenge request through root.
+		if req.IsMFARequiredRequest.ClusterID != "" && req.IsMFARequiredRequest.ClusterID != c.cfg.RootClusterName {
```
Comment (flyinghermit) [inline lib/web/mfa.go:204]: Can we add some test coverage for the fix?

File: lib/web/mfa.go (hunk 1 above)
Comment (Joerger) [reply lib/web/mfa.go:183]: Just because we're using it several times below, I found it more dextrous to rename it.

File: lib/web/mfa.go [hunk 3]
```diff
@@ -192,10 +194,41 @@ func (h *Handler) createAuthenticateChallengeHandle(w http.ResponseWriter, r *ht
...
-		mfaRequiredCheckProto, err = h.checkAndGetProtoRequest(r.Context(), c, req.IsMFARequiredRequest)
+		mfaRequiredCheckProto, err = h.checkAndGetProtoRequest(ctx, c, req.IsMFARequiredRequest)
 		if err != nil {
 			return nil, trace.Wrap(err)
 		}
+
+		// If this is an mfa required check for a leaf host, we need to check the requirement through
+		// the leaf cluster, rather than through root in the authenticate challenge request below
+		//
+		// TODO(Joerger): Currently, we only leafs hosts that we check mfa requirements for directly
```
Comment (flyinghermit) [inline lib/web/mfa.go:205]: nit: this commentry reads like its missing some words

**Review by flyinghermit — APPROVED** [review]
Many thanks for the tests.

File: lib/web/mfa.go (hunk 3 above)
Comment (Joerger) [reply lib/web/mfa.go:205]: Nice catch, the first "we" should be "the"...

**Comment by Joerger** [comment]
@zmb3 @rosstimothy May I have a flaky test skip? The new test takes >6 seconds

**Comment by Joerger** [comment]
FYI I ran into https://github.com/gravitational/teleport/issues/10671 in testing this:

conditions:
1) MFA is required on root, not leaf 
2) Root and Leaf both have an app with the same name
3) you try to connect to the leaf app from the root proxy

result: As per https://github.com/gravitational/teleport/issues/10671, you'll be routed to the root app rather than the leaf app. It will fail to connect since MFA was not provided. This is caused by the launcher correctly passing the cluster name when getting details / checking if mfa is required, but not having a way to pass the clustername into the fqdn (e.g. dumper.root.example.com).

Same issue would occur if you had overlapping leaf apps where only one leaf cluster requires MFA.

To be clear, this issue is a preexisting limitation of our leaf app routing logic, not caused by this PR.
