### PR TITLE
[vnet] fix: configure DNS when Windows group policy settings are enabled

### LINKED ISSUE #56060: VNet DNS policies are ineffective on Windows hosts with Group Policy DNS settings
Expected behavior:
VNet's DNS policies should always take effect

Current behavior:
VNet currently writes DNS policies under the registry key `SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig`.

If Group Policy writes any DNS policies to `SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig`, those policies not only take precedence but any of the SYSTEM policies used by VNet are completely ignored.

If the key at `SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig` is present, even if empty, VNet DNS policies will not take effect.

We may need to detect presence of any Group Policy DNS policies and add VNet's DNS policies there, and watch for updates in case VNet's policies get deleted or overwritten.

Bug details:
- Teleport version
  - all Windows VNet versions
- Recreation steps
  - create an empty registry key at `SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig` and reboot
- Debug logs

### PR DESCRIPTION
**Pull request by nklaassen**
Fixes #56060

VNet on Windows currently writes its split DNS configuration as an NRPT rule under the registry key `SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig`. However, when Windows Group Policy sets any DNS settings, they are written as NRPT rules under `SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig`. When this group policy parent key is present, the SYSTEM NRPT rules get completely ignored.

With this change, VNet looks for the presence of the `SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig` key and also writes its NRPT rule there. Similar VPN-like tools use the same strategy.

I tested this by creating two Windows server VMs, the first as a domain controller that sets DNS group policy rules, and the second as a machine that joined the domain and had DNS rules set via group policy from the controller VM. It reproduced the bug, and this fix resolves it.

changelog: fixed VNet DNS configuration on Windows hosts joined to Active Directory domains

### CODE REVIEW

**Review by zmb3 — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]

File: lib/vnet/osconfig_windows.go [hunk 1]
```diff
@@ -136,37 +129,66 @@ func addrMaskForCIDR(cidr string) (string, string, error) {
...
+		}
+		// The group policy parent key doesn't exist, no need to write under it.
+		return nil
+	}
+	if err := groupPolicyKey.Close(); err != nil {
+		return trace.Wrap(err, "closing registry key %s", groupPolicyNRPTParentKey)
+	}
+
+	nrptRegKey = groupPolicyNRPTParentKey + `\` + vnetNRPTKeyID
+	return trace.Wrap(configureDNSAtNRPTKey(ctx, nrptRegKey, zones, nameservers),
```
Comment (ravicious) [inline lib/vnet/osconfig_windows.go:173]: Just a couple of notes from looking into [the customer issue](https://gravitational.zendesk.com/agent/tickets/14559) that I found to be too technical to include in the support request:

I found [a comment](https://github.com/tailscale/tailscale/issues/4607#issuecomment-1130586168) in Tailscale's issue tracker claiming that changes to those keys are not picked up by the DNS client until the group policy is refreshed. Indeed, [Tailscale's solution does issue a refresh at the end](https://github.com/tailscale/tailscale/pull/4777/files#diff-f0aeef11af128394e1c4468f5139e97885e2078b620b94640e7a1030721bddc8R281). AFAIK, we now run `configureDNS` on Windows every 10s just like on macOS, so I think issuing a refresh of group policies every 10s might be too much.

Despite Tailscale's solution, there's still [someone for whom it didn't work](https://github.com/tailscale/tailscale/issues/4607#issuecomment-2501954988) until they addressed empty NRPT rules set by some group policies.

Though in my testing where I manually created an empty `HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig`, the current solution that we have did work just as it did for Nic when this was implemented.
