### PR TITLE
Check for remote command exit errors

### LINKED ISSUE #4025: Unknown user error is not shown in Web UI (Failed SSH connect attempts are not handled as errors by the server)
### Description

**What happened**:

Attempting to open a session with a non-existent user on a machine via the Web simply displays the "start a new session" button.  The user does not know the issue.  They have to replay the session to see the unknown user message which they may not have access to.

**What you expected to happen**:

The error message would display of unknown user and some indication in the audit log of a failed session would be written.

image

**How to reproduce it (as minimally and precisely as possible)**:

Add logins (myuser3, myuser4,..).  Through the web ui attempt to open a ssh session with a user that doesn't exist on a ssh node.

### Environment
- Teleport version (use `teleport version`): 4.3.0
- Tsh version (use `tsh version`): 4.3.0
- OS (e.g. from `/etc/os-release`): Ubuntu

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Browser environment**

- Browser Version (for UI-related issues):  chrome Version 83.0.4103.116 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by kimlisa**
fixes https://github.com/gravitational/teleport/issues/4025

#### Description

Currently Teleport does not handle all errors that can occur during SSH session creation. It can mistakenly create an interactive session record (recording) and write initialization errors directly into the stream as if these errors happened within an actual SSH session. It then proceeds with emitting the rest of audit events as if interactive session successfully started and ended even though it never did. 

One example would be starting a session [from non-existent user ](https://github.com/gravitational/teleport/blob/master/lib/srv/term.go#L156)

But in general, this line of code: https://github.com/gravitational/teleport/blob/master/lib/srv/reexec.go#L317, is an error from a failed command, but wasn't getting propagated up high enough to be handled properly. 

I noticed I could get the exit code by using [`session.Wait`](https://pkg.go.dev/golang.org/x/crypto/ssh?tab=doc#Session.Wait)

EDIT: Calling ssh/session.Wait() is the only way to consume the value in the exitStatus channel. We weren't using Wait() before because we used other methods to "wait" or block until session completed. I am guaranteed a value will be there to consume because to [return back from a session](https://github.com/gravitational/teleport/blob/master/lib/web/terminal.go#L300), you have to send a request to session "exit" which sends a value to the exitStatus channel. ~~So this guarantees that Wait() won't be blocking b/c its unconsumed.~~ It may block for a tiny bit if the control is returned first before the value is finished sending over the channel. But I don't think the order should matter much and the time waiting shouldn't be very long.

### CODE REVIEW

File: lib/web/terminal.go [hunk 1]
```diff
@@ -299,6 +299,17 @@ func (t *TerminalHandler) streamTerminal(ws *websocket.Conn, tc *client.Teleport
 	// either an error occurs or it completes successfully.
 	err := tc.SSH(t.terminalContext, t.params.InteractiveCommand, false)
 
+	// Catches remote command exit errors to prevent sending a close event to UI,
+	// which prevents the UI terminal from closing the tab before user sees errors.
```
Comment (alex-kovoy) [inline lib/web/terminal.go:303]: This comment is incorrect as the purpose of this change is to stop swallowing errors during session initialization. In other words, if remote process exists with an error code, make sure we handle it.

Comment (kimlisa) [reply lib/web/terminal.go]: revised comment: https://github.com/gravitational/teleport/pull/4088/commits/a7564cca82d40bf719208c272ebe6a2d00aca73c

Comment (alex-kovoy) [reply lib/web/terminal.go]: Does it still creates a session record? (can you view it in the Audit Logs)? (it should not)
Does it show an actual error text? (Looks like it does not. If so, we may want to introduce our own "ExitCode" value for the errors we know (such as NotFound login) and handle it accordingly by mapping them to description text. 

Also, it might be actually **a feature** where we write errors into the teleport session stdout stream upon failing to create an SSH session :) If this is the case, lets try to be "smart" on the client where necessary.

File: lib/web/terminal.go [hunk 2]
```diff
@@ -299,6 +299,16 @@ func (t *TerminalHandler) streamTerminal(ws *websocket.Conn, tc *client.Teleport
...
+	// Handle remote processes that exit with error codes, eg: RemoteCommandFailure (255).
+	if t.sshSession != nil {
+		if err := t.sshSession.Wait(); err != nil {
+			if exitErr, ok := err.(*ssh.ExitError); ok {
+				t.log.Warnf("Remote shell exited with error code: %v", exitErr.ExitStatus())
+				return
+			}
+		}
+	}
+
```
Comment (awly) [inline lib/web/terminal.go:311]: Should this happen after the error from `tc.SSH` is handled?
There's a fallback to a different `tc.SSH` call below for example.

**Comment by awly** [comment]
Also, please add a test to catch the bug that is being fixed

File: lib/web/terminal.go (hunk 1 above)
Comment (kimlisa) [reply lib/web/terminal.go]: > Does it still create a session record? (can you view it in the Audit Logs)? (it should not)

Yes and yes. I was thinking maybe that this is a correct behavior because we want to log users who has a valid certificate to ssh into correct node, which starts a successful session, but b/c the user doesn't exist as a system user, exec command fails. I think this is what you meant by it being a feature?

> Does it show an actual error text? 

Yes, b/c at this point, websocket c/n has been established, and error are wrote back into it as displayed below:
Screenshot from 2020-07-20 23-39-38

File: lib/web/terminal.go (hunk 2 above)
Comment (kimlisa) [reply lib/web/terminal.go]: revised and tested: https://github.com/gravitational/teleport/pull/4088/commits/9fe8b7c148ae9c30e3d81adead0b32f171b03433

File: lib/web/apiserver_test.go [hunk 3]
```diff
@@ -980,9 +986,33 @@ func (s *WebSuite) TestWebAgentForward(c *C) {
...
+
+	// This seems to trigger reading of the next incoming message:
+	// "the connection was closed on the remote side on..."
+	websocket.Message.Send(ws, []byte{})
+	err = s.waitForRawEvent(ws, 5*time.Second)
+	c.Assert(err, IsNil)
+
+	// If process exits with error codes,
+	// no close event is sent and this will timeout.
+	err = s.waitForCloseEvent(ws, 5*time.Second)
```
Comment (awly) [inline lib/web/apiserver_test.go:1009]: set a lower time out here (maybe 1s), since it's expected.
unit tests should generally last <1s.

File: lib/web/apiserver_test.go [hunk 4]
```diff
@@ -980,9 +986,33 @@ func (s *WebSuite) TestWebAgentForward(c *C) {
...
+
+	defer ws.Close()
+
+	// Receive "Failed to launch: user: unknown user baz."
+	err = s.waitForRawEvent(ws, 5*time.Second)
+	c.Assert(err, IsNil)
+
+	// This seems to trigger reading of the next incoming message:
+	// "the connection was closed on the remote side on..."
+	websocket.Message.Send(ws, []byte{})
```
Comment (awly) [inline lib/web/apiserver_test.go:1003]: check the returned error

File: lib/web/apiserver_test.go [hunk 5]
```diff
@@ -1851,6 +1881,45 @@ func (s *WebSuite) waitForRawEvent(ws *websocket.Conn, timeout time.Duration) er
 	}
 }
 
+func (s *WebSuite) waitForCloseEvent(ws *websocket.Conn, timeout time.Duration) error {
+	timeoutContext, timeoutCancel := context.WithTimeout(context.Background(), timeout)
+	defer timeoutCancel()
+	doneContext, doneCancel := context.WithCancel(context.Background())
+	defer doneCancel()
```
Comment (awly) [inline lib/web/apiserver_test.go:1888]: You can use a single context here.

```
<-ctx.Done()
switch ctx.Err() {
  case context.Canceled: return nil
  case context.DeadlineExceeded: return trace.BadParameter("...")
  default: return trace.Wrap(err)
}
```

File: lib/web/apiserver_test.go [hunk 6]
```diff
@@ -1851,6 +1881,45 @@ func (s *WebSuite) waitForRawEvent(ws *websocket.Conn, timeout time.Duration) er
...
+
+	go func() {
+		for {
```
Comment (awly) [inline lib/web/apiserver_test.go:1891]: terminate this loop when the context is closed too: `for ctx.Err() == nil {`

File: lib/web/apiserver_test.go [hunk 7]
```diff
@@ -1851,6 +1881,45 @@ func (s *WebSuite) waitForRawEvent(ws *websocket.Conn, timeout time.Duration) er
...
+			}
+
+			if envelope.GetType() == defaults.WebsocketClose {
+				doneCancel()
+				return
+			}
+		}
+	}()
+
+	for {
```
Comment (awly) [inline lib/web/apiserver_test.go:1913]: no need for this outer loop, the loop body always returns

File: lib/web/apiserver_test.go [hunk 8]
```diff
@@ -1851,6 +1881,45 @@ func (s *WebSuite) waitForRawEvent(ws *websocket.Conn, timeout time.Duration) er
...
 
+func (s *WebSuite) waitForCloseEvent(ws *websocket.Conn, timeout time.Duration) error {
+	timeoutContext, timeoutCancel := context.WithTimeout(context.Background(), timeout)
+	defer timeoutCancel()
+	doneContext, doneCancel := context.WithCancel(context.Background())
+	defer doneCancel()
+
+	go func() {
+		for {
+			time.Sleep(250 * time.Millisecond)
```
[the remark this answers is not in the document]
Comment (webvictim) [reply lib/web/apiserver_test.go:1892]: The time for a full Teleport unit test run in CI is around 5 minutes at the moment - an extra second or two isn't going to make a huge difference. I'd rather have a slightly slow test that works than no test at all - just in case the planned refactoring never happens or takes longer than expected.

[the remark this answers is not in the document]
Comment (awly) [reply lib/web/apiserver_test.go:1892]: Actually this loop doesn't need a sleep at all.
Read from a websocket should block.

I do agree with Gus. While slow tests are annoying we do suffer from low coverage more.

**Review by russjones — APPROVED** [review]

File: lib/web/apiserver_test.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (alex-kovoy) [reply lib/web/apiserver_test.go:1892]: This is not a general discussion about unit-tests which is obvious (so I agree with Gus too). This is about being mindful as in everything we do. Adding a dozens of lines of code and introducing additional delays to test not-critical 4 lines of code does not make much sense to me. 

@awly  yeah, that loop is not needed at all. I quickly checked other tests in this file which has the same unnecessary loop. It seems we can make our tests ~5sec faster.

Again, I would slightly refactor `streamTerminal` and fix its existing tests altogether rather than becoming a victim of a  "broken window" effect.

[the remark this answers is not in the document]
Comment (awly) [reply lib/web/apiserver_test.go:1892]: > Adding a dozens of lines of code and introducing additional delays to test not-critical 4 lines of code does not make much sense to me.

I disagree with that philosophy.
The opposite extreme would be only testing critical parts of code (leaving out a ton of non-core functionality).
While writing smaller tests is definitely better, we shouldn't be reluctant to test code just because it takes a lot of lines.
Also, the number of lines being tested is not an important metric. Even 1 line can make a huge difference in behavior.

If the main issue is how long tests take to run, we need to move away from `gocheck` and use parallelized (`t.Parallel()`) standard go tests.

[the remark this answers is not in the document]
Comment (alex-kovoy) [reply lib/web/apiserver_test.go:1892]: > The opposite extreme

That's the thing that it's not about black/white situation or extremes which is the _main point_. Writing a good unit-test is a mindful process. It increases the overall complexity of the system as any other part of production code with the same consequences. 

Again, my choice would be to fix the function to make it testable than throwing yet another potentially flaky test. If we do not have time for this, I would rather drop the _expensive_ test if said functionality is not critical.

[the remark this answers is not in the document]
Comment (alex-kovoy) [reply lib/web/apiserver_test.go:1892]: > If the main issue is how long tests take to run, we need to move away from gocheck and use parallelized (t.Parallel()) standard go tests.

@awly  The main issue is that we are not testing it correctly. Most of these tests do not need that much time to run. `t.Parallel` will make it even worse if not addressed correctly.

[the remark this answers is not in the document]
Comment (awly) [reply lib/web/apiserver_test.go:1892]: You provide some good points. I don't necessarily agree with everything (like the cost of writing a test or whether this specific test is correct), but that's okay.
We can debate software testing strategy separately elsewhere :)

To unblock this PR (and not take up more of @kimlisa's time), let's delete the test.
Refactoring the code to be more testable would take a while.

At some point in the future, I'd like to spend some dedicated time improving test coverage outside of bug fixes and feature work. Hopefully, this fix won't regress before then.

**Review by awly — APPROVED** [review]

File: lib/web/apiserver_test.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (kimlisa) [reply lib/web/apiserver_test.go]: reverted testing
