### PR TITLE
Fix K8s Port Forward audit log event

### LINKED ISSUE #48452: Add Kubernetes Cluster and Resource Metadata to PortForward Event
### Expected Behavior
Port-forward event messages should contain Kubernetes cluster metadata and Kubernetes resource metadata, similar to other Kubernetes events, such as `kube.request`.

Especially for use-cases with multiple kubernetes clusters, this data is important for relating what actions are happening where.

### Current Behavior
Port-forward event messages currently lack Kubernetes cluster and resource metadata fields.

#### Teleport Version
16.4.6

#### Recreation Steps
1. Perform a `kubectl port-forward` operation to a pod via Teleport, and make a connection.
2. Observe the event message generated in Teleport logs for the port-forward operation.
3. Notice the absence of Kubernetes cluster metadata and Kubernetes resource metadata in the event message.

#### Debug Logs

Example event for a kube request that isn't a port-forward:

```json
{
  "addr.remote": "203.0.113.183:60172",
  "cluster_name": "teleport.example.com",
  "code": "T3009I",
  "ei": 0,
  "event": "kube.request",
  "kubernetes_cluster": "mykube",
  "kubernetes_groups": [
    "operator",
    "system:authenticated"
  ],
  "kubernetes_users": [
    "jeff"
  ],
  "login": "jeff",
  "namespace": "default",
  "proto": "kube",
  "request_path": "/api/v1/namespaces/teleport/pods/teleport-proxy-5bc9db8cb8-k76c4",
  "resource_api_group": "core/v1",
  "resource_kind": "pods",
  "resource_name": "teleport-proxy-5bc9db8cb8-k76c4",
  "resource_namespace": "teleport",
  "response_code": 200,
  "server_hostname": "teleport.example.com",
  "server_id": "b67414b6-cca6-4d3c-f884-4aacf3b18b29",
  "server_version": "16.4.6",
  "sid": "",
  "time": "2024-11-05T16:54:11.828Z",
  "uid": "db21a16b-10da-bcae-8273-1da9c524593c",
  "user": "jeff",
  "user_kind": 1,
  "verb": "GET"
}
```

Example event for a connection made via a `kubectl port-forward` to the same pod:

```json
{
  "addr": "teleport-proxy-5bc9db8cb8-k76c4:3080",
  "addr.remote": "203.0.113.183:60173",
  "cluster_name": "teleport.example.com",
  "code": "T3003I",
  "ei": 0,
  "event": "port",
  "login": "jeff",
  "proto": "kube",
  "success": true,
  "time": "2024-11-05T16:55:06.551Z",
  "uid": "aa27c8df-33c9-ca2c-30a2-f42c2ec725bc",
  "user": "jeff",
  "user_kind": 1
}
```

### PR DESCRIPTION
**Pull request by creack**
- Emit port forward event only once at setup instead than upon each connection
- Include k8s cluster info in event

Fixes #48452

### CODE REVIEW

**Review by rosstimothy — APPROVED** [review]

File: lib/kube/proxy/forwarder.go [hunk 1]
```diff
@@ -1772,7 +1772,15 @@ func (f *Forwarder) portForward(authCtx *authContext, w http.ResponseWriter, req
 		return nil, trace.Wrap(err)
 	}
 
+	onForwardConnection := func(addr string, success bool) {
```
Comment (tigrato) [inline lib/kube/proxy/forwarder.go:1775]: I would switch these. 

for `onForwardConnection` you have access to which ports are being forwarded so you can emit real portforward events instead of doing nothing.

File: lib/kube/proxy/forwarder.go [hunk 2]
```diff
@@ -1772,7 +1772,15 @@ func (f *Forwarder) portForward(authCtx *authContext, w http.ResponseWriter, req
...
+		if !success {
+			f.log.Warn("Failed to establish connection to %q.", addr)
+		}
+		// TODO: Consider emit audit log events. Here we have the target pod port and an actual success value.
+	}
+
 	onPortForward := func(addr string, success bool) {
```
Comment (tigrato) [inline lib/kube/proxy/forwarder.go:1782]: for this one I would print the request as a API request. The interesting part comes from the portforward ports which we aren't logging here

File: lib/kube/proxy/forwarder.go (hunk 1 above)
Comment (creack) [reply lib/kube/proxy/forwarder.go:1775]: This was the behavior before this PR, but that would be inconsistent with ssh forward and results in many events on each connection without any event when setting it up

Comment (tigrato) [reply lib/kube/proxy/forwarder.go:1775]: you can track which ports you already emit events for and skip them. It's important to note that auditing ports is important

File: lib/kube/proxy/forwarder.go (hunk 2 above)
Comment (creack) [reply lib/kube/proxy/forwarder.go:1777]: reverted to the original behavior, emitting only once.

File: api/proto/teleport/legacy/types/events/events.proto [hunk 3]
```diff
@@ -1617,6 +1617,13 @@ message PortForward {
 
   // Addr is a target port forwarding address
   string Addr = 5 [(gogoproto.jsontag) = "addr"];
+
+  // Kubernetes has information about a kubernetes cluster, if applicable.
+  KubernetesClusterMetadata Kubernetes = 6 [
```
[the remark this answers is not in the document]
Comment (creack) [reply api/proto/teleport/legacy/types/events/events.proto]: Done.

File: lib/kube/proxy/forwarder.go (hunk 2 above)
Comment (creack) [reply lib/kube/proxy/forwarder.go:1777]: Updated.

File: lib/kube/proxy/forwarder.go (hunk 1 above)
Comment (creack) [reply lib/kube/proxy/forwarder.go]: Done.

**Review by tigrato — APPROVED** [review]
