### PR TITLE
Remove timeouts from discover flows, fix desktop discovery

### LINKED ISSUE #19492: Make SSH/Kubernetes token lifetimes from Teleport Discover more obvious
**What would you like Teleport to do?**

When clicking the "Add server" button to start the Teleport Discover wizard, the 5 minute timer which counts down next to the install script link for adding a server makes it look like the token/script will only be valid for 5 minutes.

Screenshot 2022-12-19 152840

It's very unclear that the token and script link is actually still valid for 4 hours as it has always been:

```
gus@artemis:~$ sudo tctl tokens ls
Token                                                            Type     Labels Expiry Time (UTC)
---------------------------------------------------------------- -------- ------ ------------------------------
92b3561a...                                                      Node            19 Dec 22 23:28 UTC (3h58m37s)
```

This is confusing - both for people who were used to the old link which specified a 4 hour timer, and for people who might be trying to use the script to connect multiple servers within the timeframe.

Adding text near the link (like we used to have) saying "this link can be used as many times as needed within the next 4 hours" would be good.

The same thing should be done for the Kubernetes onboarding flow.

The database and application flows are fine, as they still have the old 4 hour text: 

image

image

**What problem does this solve?**

Clarifies expectations of Teleport join links and makes them more useful than having to figure out how to add a join token manually in the docs and run someone through the convoluted experience of manually installing Teleport and adding a node.

**If a workaround exists, please include it.**

Teleport staff explain to people that the link is valid for longer.

### LINKED ISSUE #20149: Glitch on Windows Desktop Discover timeout
In Teleport Discover, if the wait to detect the desktop service times out and the user clicks retry, the interface begins glitching out like so:

https://user-images.githubusercontent.com/13578537/212161198-3810ffd6-d7e5-402b-80b4-b7d14370339d.mov

This is possibly related to https://github.com/gravitational/teleport/issues/20148

### PR DESCRIPTION
**Pull request by ryanclark**
## Fix desktop discovery

This adds a cache to the `useJoinToken` hook that caches the result of the join token against the resource kind. This is cleared only once a user leaves the entire flow, instead of the previous behaviour of clearing when the hook was unmounted.

This fixes the desktop discovery stage, as the cached result persists even though the hook has been unmounted between steps.

## Timer removal

This removes the concept of a script timing out in the discover workflows.

Instead, after 5 minutes of not being able to detect the relevant resource, we show a hint box that explains why we might not be seeing the resource, but we still let the user know we're still looking.

### Servers

node

### Databases

database

### Kubernetes

For kubernetes, the flow has changed a little as we allowed the user to regenerate the command after editing the labels. As we don't actually need to regenerate the command, when editing the text fields the script value would change. To avoid this weirdness, I've made it so once you click on next, it disables the text fields.

Clicking on edit to change them will then hide the command, and once they click next again, they'll see the command again.

kubernetes

### Desktops

desktops

discover-desktops

This fixes https://github.com/gravitational/teleport/issues/20149, https://github.com/gravitational/teleport/issues/20148 and https://github.com/gravitational/teleport/issues/19492.

### CODE REVIEW

File: web/packages/teleport/src/Discover/Shared/useJoinToken.ts [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+      throw existing.error;
+    }
+
+    if (existing.response) {
+      return {
+        joinToken: existing.response,
+        reloadJoinToken() {
+          joinTokenCache.delete(resourceKind);
+
+          rerender(c => c + 1);
```
Comment (ibeckermayer) [inline web/packages/teleport/src/Discover/Shared/useJoinToken.ts:92]:
```suggestion
          // Delete the cached token and force a rerender
          // so that this hook runs again and creates a new one.
          joinTokenCache.delete(resourceKind);
          rerender(c => c + 1);
```

File: web/packages/teleport/src/Discover/Shared/useJoinToken.ts [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+        },
+      };
+    }
+
+    throw existing.promise;
+  }
+
+  throw run().promise;
```
Comment (ibeckermayer) [inline web/packages/teleport/src/Discover/Shared/useJoinToken.ts:100]: What happens with this on a re-render? Is `<Suspense>` smart enough to know to go back into its fallback state?

File: web/packages/teleport/src/Discover/Shared/useJoinToken.ts [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+}
+
+let abortController: AbortController;
+let joinTokenCache = new Map<ResourceKind, SuspendResult>();
+
+export function clearCachedJoinTokenResult(resourceKind: ResourceKind) {
+  joinTokenCache.delete(resourceKind);
+}
+
+export function useJoinToken(
```
Comment (ibeckermayer) [inline web/packages/teleport/src/Discover/Shared/useJoinToken.ts:26]: Thinking that we should create (and document in a developer section of the README) a naming convention that denotes this as a suspense hook (perhaps something like `useJoinTokenSuspender`). 

My reasoning is that `Suspense` is an experimental feature, and it's API is still unconfirmed and I wasn't able to find reliable documentation for it when initially googling. If I was new to the project, I would be totally baffled by this component.

That [example you linked me](https://codesandbox.io/s/frosty-hermann-bztrp?file=/src/fakeApi.js) is pretty good, although I wonder if there's also an official or unofficial documentation page that I missed.

File: web/packages/teleport/src/Discover/Shared/usePoll.ts [hunk 4]
```diff
@@ -2,20 +2,17 @@ import { useEffect, useRef, useState } from 'react';
 
 export function usePoll<T>(
   callback: (signal: AbortSignal) => Promise<T | null>,
-  timeout: number,
   enabled: boolean,
   interval = 1000
-) {
+): T | null {
```
Comment (ibeckermayer) [inline web/packages/teleport/src/Discover/Shared/usePoll.ts:7]: Are you noticing a bug here wherein Typescript doesn't seem to pick up that this can return `null`? I notice that my editor (vscode) doesn't seem to pick it up, and if I take out `&& result` from this line

https://github.com/gravitational/teleport/blob/b20144dd090fd4128502c1cf2ac978f7de87d25f/web/packages/teleport/src/Discover/Desktop/DiscoverDesktops/DiscoverDesktops.tsx#L109

a run of `yarn type-check` doesn't complain at me

```
$ yarn type-check
yarn run v1.22.19
$ tsc --noEmit
✨  Done in 43.69s.
```

File: web/packages/teleport/src/Discover/Shared/usePoll.ts [hunk 5]
```diff
@@ -24,16 +21,6 @@ export function usePoll<T>(
     }
   }, [callback, enabled, running]);
```
Comment (ibeckermayer) [inline web/packages/teleport/src/Discover/Shared/usePoll.ts:22]: Why is `callback` needed in this sensitivity list?

**Comment by kimlisa** [comment]
> Databases
> I've removed the generate command button from this flow. The script isn't dependent on the labels, so it doesn't make sense to hide it behind a button.

the script isn't dependent on labels, but the join token that we fetch right before generating script, is (it has a field for `suggested matcher labels`) use case is something like this:

1) create db step: create a database with labels `env: dev`
2) deploy service step: user wants to have this db service also pick up `env: prod` or `env: staging` for next time

i think the only case where we should not allow user to add more labels at deploy step, is when we default to asteriks.

Also, i don't think we handle the case where the token does expire (user takes a while trouble shooting or steps out for a while). Granted might not likely happen but if it does, the user will be stuck and have to start over?

File: web/packages/teleport/src/Discover/Shared/usePoll.ts (hunk 5 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/Discover/Shared/usePoll.ts:22]: In fact, can we not simplify this whole hook to be

```typescript
export function usePoll<T>(
  callback: (signal: AbortSignal) => Promise<T | null>,
  enabled: boolean,
  interval = 1000
): T | null {
  const abortController = useRef(new AbortController());
  const [result, setResult] = useState<T | null>(null);

  useEffect(() => {
    if (enabled) {
      abortController.current = new AbortController();

      const id = window.setInterval(async () => {
        try {
          const result = await callback(abortController.current.signal);

          if (result) {
            clearInterval(id);
            setResult(result);
          }
          // eslint-disable-next-line no-empty
        } catch {}
      }, interval);

      return () => {
        clearInterval(id);
        abortController.current.abort();
      };
    } else {
      setResult(null);
    }
  }, [enabled, interval, callback]);

  return result;
}
```

File: web/packages/teleport/src/Discover/Shared/PingTeleportContext.tsx [hunk 6]
```diff
@@ -3,41 +3,37 @@ import React, { useCallback, useContext, useEffect, useState } from 'react';
 import { useTeleport } from 'teleport';
```
Comment (ibeckermayer) [inline web/packages/teleport/src/Discover/Shared/PingTeleportContext.tsx:3]: Looks like we can delete the `TODO` comment in this file (line 72-74)

File: web/packages/teleport/src/Discover/Server/DownloadScript/DownloadScript.tsx [hunk 7]
```diff
@@ -137,6 +107,60 @@ export function DownloadScript(props: AgentStepProps) {
...
+            white-space: pre;
+          `}
+        >
+          <Icons.Restore fontSize={4} />
+        </TextIcon>
+        After running the command above, we'll automatically detect your new
+        Teleport instance.
+      </WaitingInfo>
+    );
+  }
```
Comment (ibeckermayer) [inline web/packages/teleport/src/Discover/Server/DownloadScript/DownloadScript.tsx:162]: Something similar pops up multiple times, it looks like something we can parameterize with props (including the timeout) and hold in `web/packages/teleport/src/Discover/Shared`.

**Review by ibeckermayer — CHANGES_REQUESTED** [review]
Nice work getting rid of the context and keeping join token logic in a single hook

**Review by kimlisa — COMMENTED** [review]
looks like stories broke from the story changes, and some story states will not be needed (if we ultimately not do certain things like, handling 4 hour timeout)

File: web/packages/teleport/src/Discover/Shared/usePoll.ts (hunk 5 above)
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Shared/usePoll.ts:22]: actually nvm, i think i can make use of the `enabled` flag

File: web/packages/teleport/src/Discover/Shared/usePoll.ts [hunk 8]
```diff
@@ -2,20 +2,17 @@ import { useEffect, useRef, useState } from 'react';
...
   callback: (signal: AbortSignal) => Promise<T | null>,
-  timeout: number,
   enabled: boolean,
   interval = 1000
-) {
+): T | null {
   const abortController = useRef(new AbortController());
 
   const [running, setRunning] = useState(false);
-  const [timedOut, setTimedOut] = useState(false);
```
[the remark this answers is not in the document]
Comment (kimlisa) [reply web/packages/teleport/src/Discover/Shared/usePoll.ts:12]: actually nvm, i think i can make use of the `enabled` flag

File: web/packages/teleport/src/Discover/Shared/useJoinToken.ts (hunk 2 above)
Comment (ryanclark) [reply web/packages/teleport/src/Discover/Shared/useJoinToken.ts:100]: On a re-render it'll go down the `if (existing)` route and return the existing promise

File: web/packages/teleport/src/Discover/Shared/useJoinToken.ts (hunk 3 above)
Comment (ryanclark) [reply web/packages/teleport/src/Discover/Shared/useJoinToken.ts:26]: Sure, we can rename this

File: web/packages/teleport/src/Discover/Shared/usePoll.ts (hunk 4 above)
Comment (ryanclark) [reply web/packages/teleport/src/Discover/Shared/usePoll.ts:7]: Yeah I noticed this as well, it just returns `T`. I was just trying to be strict with typings by adding this 🤷

File: web/packages/teleport/src/Discover/Shared/usePoll.ts (hunk 5 above)
Comment (ryanclark) [reply web/packages/teleport/src/Discover/Shared/usePoll.ts:22]: Yeh I think so, I've updated it to use yours

File: web/packages/teleport/src/Discover/Server/DownloadScript/DownloadScript.tsx (hunk 7 above)
Comment (ryanclark) [reply web/packages/teleport/src/Discover/Server/DownloadScript/DownloadScript.tsx:162]: I've simplified the usage of `HintBox` and moved the common hook behaviour into a new `useShowHint()`

File: web/packages/teleport/src/Discover/Kubernetes/HelmChart/HelmChart.tsx [hunk 9]
```diff
@@ -45,27 +48,26 @@ import type { AgentStepProps } from '../../types';
 import type { JoinToken } from 'teleport/services/joinToken';
 import type { AgentMeta, KubeMeta } from 'teleport/Discover/useDiscover';
 import type { Kube } from 'teleport/services/kube';
-import type { Poll } from 'teleport/Discover/Shared/CommandWithTimer';
 
-export default function Container(
-  props: AgentStepProps & { runJoinTokenPromise?: boolean }
-) {
+const SHOW_HINT_TIMEOUT = 1000 * 60 * 5; // 5 minutes
```
[the remark this answers is not in the document]
Comment (ryanclark) [reply web/packages/teleport/src/Discover/Kubernetes/HelmChart/HelmChart.tsx:52]: Done

File: web/packages/teleport/src/Discover/Shared/usePoll.ts (hunk 4 above)
Comment (ibeckermayer) [reply web/packages/teleport/src/Discover/Shared/usePoll.ts:7]: Huh, seems like a ts bug. It might be worth adding explicit typings to places where the automatic typing is failing us and see if that helps.

**Review by ibeckermayer — APPROVED** [review]
LGTM once we've manually checked that everything is running as expected.

**Review by kimlisa — APPROVED** [review]
i tested on my staging cloud cluster and everything works (i did not thoroughly test the desktop flow though, i just clicked through it but did not set anything up)

the only thing we need is to have a success state after discovering resources so it's more obvious something happened

File: web/packages/teleport/src/Discover/Shared/usePoll.ts [hunk 10]
```diff
@@ -7,9 +7,21 @@ export function usePoll<T>(
...
   useEffect(() => {
-    if (enabled) {
+    if (enabled && !running) {
+      setResult(null);
+      setRunning(true);
+    }
+
+    if (!enabled && running) {
+      setRunning(false);
+    }
```
Comment (kimlisa) [inline web/packages/teleport/src/Discover/Shared/usePoll.ts:20]: i copy-pasta from your old code, but looking at this block again, it doesn't seem like i need it 🤔

**Comment by ravicious** [comment]
Is it fine if I leave an approval just to unblock the CI? I feel like I don't have enough context on Discovery to give this a proper review.

**Comment by kimlisa** [comment]
@ravicious @ryanclark i think it's fine to just leave a bot approval since we have two approvals for this PR. this is what i often do on teleport side after I get two approvals of my selection (i try to manually pick people with the most context and they sometimes don't satisfy the reviewers requirement)

**Review by ravicious — APPROVED** [review]
