### PR TITLE
Try fixing `TestGetKubeCreds`

### LINKED ISSUE #23510: Race in `TestGetKubeCreds`
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4501060766/jobs/7920991671

#### Relevant snippet

```
=== RUN   TestGetKubeCreds
make: *** [test-go] Error 1
    testing.go:1446: race detected during execution of test
--- FAIL: TestGetKubeCreds (0.03s)
```

### PR DESCRIPTION
**Pull request by tigrato**
This PR tries to fix an unknown and weirdly reported data race.

Fixes #23510

### CODE REVIEW

**Comment by mdwn** [comment]
Is the issue the `defer os.Remove(tmpFile.Name())` call? Could this be fixed by making it a `t.Cleanup` instead?

**Comment by tigrato** [comment]
> Is the issue the `defer os.Remove(tmpFile.Name())` call? Could this be fixed by making it a `t.Cleanup` instead?

`t.TempDir` schedules a `os.RemoveAll` when the test finishes.

I am still not 100% confident of what happened there since the race detected does not show any details besides "race detected". At least I hope this will help either fixing or help understand the issue

**Review by mdwn — APPROVED** [review]

File: lib/kube/proxy/auth_test.go [hunk 1]
```diff
@@ -278,8 +278,10 @@ current-context: foo
 		},
 	}
 	for _, tt := range tests {
+		tt := tt
```
Comment (timothyb89) [inline lib/kube/proxy/auth_test.go:281]: Out of curiosity, what's the purpose of this? Is it a workaround for loop memory aliasing or something?

**Review by timothyb89 — APPROVED** [review]

File: lib/kube/proxy/auth_test.go (hunk 1 above)
Comment (tigrato) [reply lib/kube/proxy/auth_test.go:281]: The loop variable `tt` is by default captured by reference and all the goroutines spawn by `t.Run` will receive the same reference to `tt`.
Once all tests execute, all of them will referer to the same reference and run the same test.

Using this, we create a new in-loop variable `tt` and the test will capture that variable instead of the old one. With `tt:=tt` we allocate new stack space and when the closure captures the reference, it captures the new allocated space reference, which is different from test to test.
