### PR TITLE
(7.0) Fix app access websockets support

### LINKED ISSUE #5264: Application Access does not support websockets
**What happened**: Trying to establish a websocket connection through AAP does not allow websockets to connect.

**What you expected to happen**: Websockets should work.

**How to reproduce it (as minimally and precisely as possible)**: Deploy something that requires websockets and proxy it through AAP. It will not work.

For my testing I used [Node-Red](https://nodered.org/docs/getting-started/docker). Deploy it in Docker using default port 1880. Set up AAP like so:

`/etc/teleport.yaml`:
```yaml
app_service:
  enabled: yes
  apps:
  - name: nodered
    public_addr: nodered.teleport.example.com
    uri: http://hades:1880
```

Connecting to https://nodered.teleport.example.com through a browser will load the UI, but websocket connections will fail. You can see this in Chrome dev tools:

Screenshot 2021-01-11 at 10 29 39

For contrast, here's the websocket traffic working correctly using Caddy:

Screenshot 2021-01-11 at 10 25 00

I can see no relevant logs outputted from Teleport during these attempted websocket connections, even at DEBUG level. Regardless, here is the full log section for the connection from start to finish:

```
Jan 11 10:31:41 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:41 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:41 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:41 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:41 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:41 hades teleport[436900]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
Jan 11 10:31:41 hades teleport[436900]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
Jan 11 10:31:41 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:41 hades teleport[436900]: DEBU [APP:SERVI] Using async streamer for session e62b9e05-1930-471e-964a-901cc4a9877c. app/session.go:169
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /, code: 304, duration: 3.836414ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/jquery/css/base/jquery-ui.min.css, code: 304, duration: 1.907483ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/style.min.css, code: 304, duration: 1.838274ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/font-awesome/css/font-awesome.min.css, code: 304, duration: 2.012946ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/vendor.js, code: 304, duration: 2.316669ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
Jan 11 10:31:42 hades teleport[436900]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/main.min.js, code: 304, duration: 1.86439ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/red.min.js, code: 304, duration: 1.672763ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/purify.min.js.map, code: 404, duration: 3.858245ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Transport request: teleport-transport. leaseID:1 target:teleport.example.com:3080 reversetunnel/agent.go:428
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Received out-of-band proxy transport request for @local-node [0065053d-e8e9-4880-aebb-e2d9499b681e.teleport.example.com]. leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:229
Jan 11 10:31:42 hades teleport[436900]: DEBU [APP:SERVI] Handing off connection to a local SSH service leaseID:1 target:teleport.example.com:3080 reversetunnel/transport.go:301
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:134459308287134350927232826641598365919) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: DEBU [AUTH]      ClientCertPool -> cert(teleport.example.com issued by teleport.example.com:125861568327795827078182794666495814353) auth/middleware.go:569
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/editor?lng=en-GB, code: 304, duration: 2.788147ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /theme, code: 304, duration: 1.550436ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/node-red?lng=en-GB, code: 304, duration: 2.432359ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/jsonata?lng=en-GB, code: 304, duration: 5.126189ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/editor?lng=en-US, code: 304, duration: 6.561891ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/node-red?lng=en-US, code: 304, duration: 2.726082ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/jsonata?lng=en-US, code: 304, duration: 4.077259ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/infotips?lng=en-GB, code: 304, duration: 5.5184ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /locales/infotips?lng=en-US, code: 304, duration: 5.265811ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/node-red.svg, code: 304, duration: 2.286183ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /favicon.ico, code: 200, duration: 6.999832ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /settings?_=1610375502103, code: 200, duration: 1.081867ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /settings/user?_=1610375502104, code: 200, duration: 972.548µs tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/spin.svg, code: 304, duration: 3.144964ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/keymap.json, code: 304, duration: 3.607199ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-full-o.svg, code: 304, duration: 1.87505ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-full.svg, code: 304, duration: 1.681191ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-flows.svg, code: 304, duration: 1.955782ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/grip.png, code: 304, duration: 1.754156ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-reload.svg, code: 304, duration: 1.562247ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/deploy-nodes.svg, code: 304, duration: 1.619736ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /vendor/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0, code: 304, duration: 1.732088ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /nodes?_=1610375502105, code: 200, duration: 2.952736ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /nodes/messages?lng=en-GB&_=1610375502106, code: 200, duration: 3.240719ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /nodes/messages?lng=en-US&_=1610375502107, code: 200, duration: 3.845578ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons?_=1610375502108, code: 200, duration: 1.861736ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /nodes?_=1610375502109, code: 200, duration: 8.279227ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /debug/view/debug-utils.js, code: 304, duration: 3.007197ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/debug.svg, code: 304, duration: 2.500075ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/inject.svg, code: 304, duration: 2.110012ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/status.svg, code: 304, duration: 2.935912ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/alert.svg, code: 304, duration: 3.076684ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/link-out.svg, code: 304, duration: 2.517856ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/comment.svg, code: 304, duration: 2.356024ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /flows?_=1610375502110, code: 200, duration: 2.535374ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/trigger.svg, code: 304, duration: 2.47691ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/template.svg, code: 304, duration: 2.22044ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/timer.svg, code: 304, duration: 2.177253ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/cog.svg, code: 304, duration: 2.346898ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red-node-rbe/rbe.png, code: 304, duration: 2.286374ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/swap.svg, code: 304, duration: 3.936646ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/function.svg, code: 304, duration: 4.605236ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/range.svg, code: 304, duration: 4.697525ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/switch.svg, code: 304, duration: 2.371219ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/white-globe.svg, code: 304, duration: 3.221799ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/bridge.svg, code: 304, duration: 3.938426ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /red/images/subflow_tab.svg, code: 304, duration: 1.376884ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/bridge-dash.svg, code: 304, duration: 1.733373ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/split.svg, code: 304, duration: 1.532646ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/join.svg, code: 304, duration: 1.460828ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/sort.svg, code: 304, duration: 2.395725ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/batch.svg, code: 304, duration: 1.260347ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-csv.svg, code: 304, duration: 2.268534ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-json.svg, code: 304, duration: 3.996973ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-html.svg, code: 304, duration: 3.689769ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/file-out.svg, code: 304, duration: 1.917863ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-yaml.svg, code: 304, duration: 2.119178ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/parser-xml.svg, code: 304, duration: 1.355629ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/file-in.svg, code: 304, duration: 2.569952ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: DEBU             Skipping login 95c2d1cd-86d2-4845-aea1-d3a062bc42d5, not a valid Unix login. services/role.go:360
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/file.svg, code: 304, duration: 1.433782ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
Jan 11 10:31:42 hades teleport[436900]: INFO             Round trip: GET /icons/node-red/watch.svg, code: 304, duration: 971.332µs tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:74656c65706f72742e776562766963742e696d.teleport.cluster.local forward/fwd.go:196
```

### Environment
- Teleport version (use `teleport version`): `Teleport v5.1.0 git:v5.1.0-0-g46679fb34 go1.15.5`
- OS (e.g. from `/etc/os-release`): `Fedora 32`

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Intel NUC

**Browser environment**

- Browser Version (for UI-related issues): `Google Chrome Version 87.0.4280.88 (Official Build) (arm64)`

### PR DESCRIPTION
**Pull request by r0mant**
https://github.com/gravitational/teleport/pull/6028 forward-port to master. Fixes https://github.com/gravitational/teleport/issues/5264.

### CODE REVIEW

**Review by russjones — APPROVED** [review]
Bot.

File: lib/utils/fakeconn_test.go [hunk 1]
```diff
@@ -0,0 +1,115 @@
...
+func TestChConn(t *testing.T) {
+	listener, err := net.Listen("tcp", "127.0.0.1:0")
+	require.NoError(t, err)
+	t.Cleanup(func() { listener.Close() })
+
+	sshConnCh := make(chan sshConn)
+
+	go startSSHServer(t, listener, sshConnCh)
+
+	client, err := ssh.Dial("tcp", listener.Addr().String(), &ssh.ClientConfig{
```
Comment (a-palchikov) [inline lib/utils/fakeconn_test.go:45]: nit: I could imagine this racing with `startSSHServer` and hitting the `connection refused` if the server takes time to start. It is unlikely but not impossible unless this ensures that dialing only happens after the listener had started `Accept`ing.

File: lib/utils/fakeconn_test.go [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+	require.NoError(t, err)
+
+	_, _, err = client.OpenChannel("test", []byte("hello ssh"))
+	require.NoError(t, err)
+
+	select {
+	case sshConn := <-sshConnCh:
+		chConn := NewChConn(sshConn.conn, sshConn.ch)
+		t.Cleanup(func() { chConn.Close() })
+		doneCh := make(chan error)
```
Comment (a-palchikov) [inline lib/utils/fakeconn_test.go:57]: Make the channel buffered. There's a chance the following goroutine will get stuck at send if it takes longer than 1s.

**Review by a-palchikov — APPROVED** [review]

File: lib/utils/fakeconn_test.go (hunk 1 above)
Comment (r0mant) [reply lib/utils/fakeconn_test.go:45]: At least according to my experiments, it won't get connection refused since listener is already listening.
