### PR TITLE
Deflake TestCreateAccessListReminderNotifications

### LINKED ISSUE #52808: `TestCreateAccessListReminderNotifications ` flakiness
#### Link(s) to logs

https://github.com/gravitational/teleport/actions/runs/13680667923/job/38251952673

#### Relevant snippet

```
 auth_test.go:4547: 
        	Error Trace:	/__w/teleport/teleport/lib/auth/auth_test.go:4547
        	Error:      	"[sub_kind:"access-list-review-overdue-3d" metadata:{name:"01956725-05b2-743e-bb62-1499c04293f7" labels:{key:"teleport.internal/scope" value:"global"} labels:{key:"teleport.internal/title" value:"You have access lists that are more than 3 days overdue for review"} expires:{seconds:1743784234}} spec:{created:{seconds:1741192234}} sub_kind:"access-list-review-due-0d" metadata:{name:"01956725-0560-725f-b5bb-ebbd35748d57" labels:{key:"teleport.internal/scope" value:"global"} labels:{key:"teleport.internal/title" value:"You have access lists due for review today."} expires:{seconds:1743784234}} spec:{created:{seconds:1741192234}} sub_kind:"access-list-review-due-3d" metadata:{name:"01956725-0536-7dbd-b39c-46dd9d3d3089" labels:{key:"teleport.internal/scope" value:"global"} labels:{key:"teleport.internal/title" value:"You have access lists due for review in less than 3 days."} expires:{seconds:1743784234}} spec:{created:{seconds:1741192234}} sub_kind:"access-list-review-due-7d" metadata:{name:"01956725-04e5-73fb-aa98-f095f8c49fd1" labels:{key:"teleport.internal/scope" value:"global"} labels:{key:"teleport.internal/title" value:"You have access lists due for review in less than 7 days."} expires:{seconds:1743784234}} spec:{created:{seconds:1741192234}} sub_kind:"access-list-review-due-14d" metadata:{name:"01956725-046a-73f2-a2f8-7bdb35b11381" labels:{key:"teleport.internal/scope" value:"global"} labels:{key:"teleport.internal/title" value:"You have access lists due for review in less than 14 days."} expires:{seconds:1743784234}} spec:{created:{seconds:1741192234}}]" should have 6 item(s), but has 5
        	Test:       	TestCreateAccessListReminderNotifications
```

### PR DESCRIPTION
**Pull request by zmb3**
Closes #52808

### CODE REVIEW

File: lib/auth/auth.go [hunk 1]
```diff
@@ -6936,16 +6938,10 @@ func (a *Server) CreateAccessListReminderNotifications(ctx context.Context) {
 		for _, al := range accessLists {
 			dueDate := al.Spec.Audit.NextAuditDate
 			timeDiff := dueDate.Sub(now)
-			daysDiff := int(timeDiff.Hours() / 24)
+			threshold := time.Hour * 24 * time.Duration(threshold.days)
```
Comment (zmb3) [inline lib/auth/auth.go:6941]: I'm pretty sure the actual problem was in this math where we lose precision by converting to days first.

File: lib/auth/auth.go [hunk 2]
```diff
@@ -6936,16 +6938,10 @@ func (a *Server) CreateAccessListReminderNotifications(ctx context.Context) {
...
-				if daysDiff <= threshold.days {
-					relevantLists = append(relevantLists, al)
-				}
-			} else {
-				if daysDiff >= 0 && daysDiff <= threshold.days {
-					relevantLists = append(relevantLists, al)
-				}
+			if timeDiff <= threshold.Abs() {
+				relevantLists = append(relevantLists, al)
 			}
```
Comment (zmb3) [inline lib/auth/auth.go:6947]: I believe this to be algebraically equivalent, but would appreciate close eyes on this change.

File: lib/auth/auth.go [hunk 3]
```diff
@@ -6894,7 +6896,7 @@ func (a *Server) CreateAccessListReminderNotifications(ctx context.Context) {
 		case <-ctx.Done():
 			return
 		}
-		response, nextKey, err := a.Cache.ListAccessLists(ctx, 20, accessListsPageKey)
+		response, nextKey, err := a.Cache.ListAccessLists(ctx, accessListsPageSize, accessListsPageKey)
```
Comment (tigrato) [inline lib/auth/auth.go:6899]: Not specific to this PR, but reading 20 access lists per request from a pool of up to 50k will be slow. The 5ms ticker-based rate limit also isn’t a great implementation

Should we create an issue to track these?

File: lib/auth/auth.go (hunk 2 above)
Comment (tigrato) [reply lib/auth/auth.go:6947]: algebraically this won't be the same when dealing with overdue access lists. 
From the logic, looks like if an access list is due in 3 days, it will also pick the overdue 7d because we completely discard the negative part of the threshold i.e `3<|-7|`

Also, I wonder if we should just pick the most severe threshold and use it, instead of creating notifications for all of them

File: lib/auth/auth.go (hunk 3 above)
Comment (zmb3) [reply lib/auth/auth.go:6899]: Sure. I had the same thought looking at this that we probably have some perf issues.

File: lib/auth/auth.go (hunk 2 above)
Comment (zmb3) [reply lib/auth/auth.go:6947]: > Also, I wonder if we should just pick the most severe threshold and use it, instead of creating notifications for all of them

That's a good idea, but we should do that separately so that we don't combine a test fix and behavior change in the same PR.

**Comment by zmb3** [comment]
@tigrato can you take another look?

**Review by flyinghermit — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

File: lib/auth/auth.go (hunk 2 above)
Comment (rudream) [reply lib/auth/auth.go:6947]: > Also, I wonder if we should just pick the most severe threshold and use it, instead of creating notifications for all of them

Unless I'm misunderstanding what you mean, in real-world scenarios this wouldn't make a difference because how soon it is due/overdue would progress with time (ie. for an access list to be due for review in 3 days, it must have first been "due in 7 days" 4 days before, and "due in 14 days" 7 days before that, and likewise for overdue notifications). It must be the case that if an access list continuously goes unreviewed, it should eventually have triggered all the different types of reminder notifications.

The only way this could lead to odd behaviour is if you manually set an access list's next review date to a date after one of the thresholds, eg. if I have an access list currently due for review in 20 days, and then I manually change its next review date to actually be due in 2 days, it would trigger the `14d`, `7d`, and `3d` notifications simultaneously
