### PR TITLE
Fix remote port forwarding when local login doesn't match node user

### LINKED ISSUE #20619: Unable to use remote interpreter or ssh with IntelliJ IDEs (pycharm) on Windows
Expected behavior:
Configuration for ssh with PyCharm, etc, works on Mac and Linux. Does not work on Windows.

Current behavior:
IntelliJ fails to connect through ssh (specifically on Windows)

Bug details:
- Teleport version: 10
- Recreation steps: Configure pycharm with remote operator on Windows
- Debug logs: none contain errors or information

### LINKED ISSUE #42254: `tsh ssh -R` fails to open socket: `unexpected user UID for the socket: 0`
Expected behavior:

`tsh ssh -R` should reverse tunnel a port similar to ssh.

Current behavior:

When running an httpbin container on `localhost:8111`:
```
$ docker run -p 8111:80 kennethreitz/httpbin
```

... forwarding to a remote host and the socket hangs forever:
```
$ tsh ssh -R 8111:localhost:8111 teleport-node curl localhost:8111/get
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0^CERROR: connection canceled
```

The auth server log shows the following:
```
2024-05-31T18:17:08-06:00 INFO [NODE:RESU] Handling new resumable SSH connection. pid:2437.1 resumption/server_exchange.go:91
2024-05-31T18:17:08-06:00 INFO [NODE:RESU] Handing resumable connection to the SSH server. pid:2437.1 resumption/server_exchange.go:135
2024-05-31T18:17:08-06:00 WARN             failed to handle tcpip forward request error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError unexpected user UID for the socket: 0
Stack Trace:
        github.com/gravitational/teleport/lib/srv/regular/sshserver_linux.go:56 github.com/gravitational/teleport/lib/srv/regular.validateListenerSocket
        github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1189 github.com/gravitational/teleport/lib/srv/regular.(*Server).listenTCPIP
        github.com/gravitational/teleport/lib/srv/regular/sshserver.go:2299 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleTCPIPForwardRequest
        github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1371 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleRequest
        github.com/gravitational/teleport/lib/sshutils/server.go:648 github.com/gravitational/teleport/lib/sshutils.(*Server).HandleConnection.func2
        runtime/asm_amd64.s:1695 runtime.goexit
User Message: unexpected user UID for the socket: 0] regular/sshserver.go:1372
2024-05-31T18:17:08-06:00 INFO [AUDIT]     session.data addr.remote:192.168.10.144:36424 code:T2006I ei:2.147483646e+09 event:session.data login:tim namespace:default private_key_policy:none rx:4342 server_hostname:teleport-node server_id:e0f26ea6-56d8-432e-b8ed-5beb343b63ff sid: time:2024-06-01T00:17:08.805Z tx:4976 uid:58b89b5d-481c-4bad-8f49-662c97da2a38 user:tim user_kind:1 events/emitter.go:288
2024-05-31T18:17:08-06:00 INFO [NODE]      Creating (interactive) session 83a16979-c35a-48ef-887e-af1e56bb5146. id:5 local:192.168.10.186:32770 login:tim remote:192.168.10.144:36424 teleportUser:tim srv/sess.go:340
2024-05-31T18:17:08-06:00 INFO [SESSION:N] New party ServerContext(192.168.10.144:36424->192.168.10.186:32770, user=tim, id=5) party(id=f9460939-03f9-406e-90d4-8df5e6e40b58) joined the session with participant mode: peer. session_id:83a16979-c35a-48ef-887e-af1e56bb5146 srv/sess.go:1917
2024-05-31T18:17:08-06:00 INFO [AUDIT]     session.start addr.remote:192.168.10.144:36424 cluster_name:teleport.ethernet.fyi code:T2000I ei:0 event:session.start initial_command:[] login:tim namespace:default private_key_policy:none proto:ssh server_hostname:teleport-node server_id:e0f26ea6-56d8-432e-b8ed-5beb343b63ff session_recording:node sid:83a16979-c35a-48ef-887e-af1e56bb5146 size:272:72 time:2024-06-01T00:17:08.836Z uid:c25894c6-f246-44c6-af9d-734033888c58 user:tim user_kind:1 events/emitter.go:288
2024-05-31T18:18:58-06:00 INFO [SESSION:N] Closing party f9460939-03f9-406e-90d4-8df5e6e40b58 srv/sess.go:2086
2024-05-31T18:18:58-06:00 INFO [SESSION:N] Removing party ServerContext(192.168.10.144:36424->192.168.10.186:32770, user=tim, id=5) party(id=f9460939-03f9-406e-90d4-8df5e6e40b58) from session session_id:83a16979-c35a-48ef-887e-af1e56bb5146 srv/sess.go:1520
2024-05-31T18:18:58-06:00 INFO [AUDIT]     session.leave cluster_name:teleport.ethernet.fyi code:T2003I ei:41 event:session.leave login:tim namespace:default private_key_policy:none server_hostname:teleport-node server_id:e0f26ea6-56d8-432e-b8ed-5beb343b63ff sid:83a16979-c35a-48ef-887e-af1e56bb5146 time:2024-06-01T00:18:58.723Z uid:4592510f-81ef-44bf-8577-f35c0c4d82b8 user:tim user_kind:1 events/emitter.go:288
2024-05-31T18:18:58-06:00 INFO [AUDIT]     session.data addr.remote:192.168.10.144:36424 code:T2006I ei:2.147483646e+09 event:session.data login:tim namespace:default private_key_policy:none rx:6470 server_hostname:teleport-node server_id:e0f26ea6-56d8-432e-b8ed-5beb343b63ff sid:83a16979-c35a-48ef-887e-af1e56bb5146 time:2024-06-01T00:18:58.725Z tx:6708 uid:15f01c52-95b9-4480-a6ba-703c4f6072aa user:tim user_kind:1 events/emitter.go:288
2024-05-31T18:19:01-06:00 WARN             Forcibly terminating remote forwarder subprocess. regular/sshserver.go:1298
2024-05-31T18:19:01-06:00 INFO [NODE:RESU] Resumable connection completed. pid:2437.1 resumption/server_exchange.go:137
2024-05-31T18:19:03-06:00 ERRO [SESSION:N] Timed out waiting for PTY copy to finish, session data  may be missing. session_id:83a16979-c35a-48ef-887e-af1e56bb5146 srv/sess.go:1331
2024-05-31T18:19:03-06:00 INFO [SESSION:N] Closing session session_id:83a16979-c35a-48ef-887e-af1e56bb5146 srv/sess.go:907
2024-05-31T18:19:03-06:00 INFO [SESSION:N] Stopping session session_id:83a16979-c35a-48ef-887e-af1e56bb5146 srv/sess.go:855
2024-05-31T18:19:03-06:00 INFO [AUDIT]     session.end addr.remote:192.168.10.144:36424 cluster_name:teleport.ethernet.fyi code:T2004I ei:42 enhanced_recording:false event:session.end interactive:true login:tim namespace:default participants:[tim] private_key_policy:none proto:ssh server_hostname:teleport-node server_id:e0f26ea6-56d8-432e-b8ed-5beb343b63ff session_recording:node session_start:2024-06-01T00:17:08.810523515Z session_stop:2024-06-01T00:19:03.700070123Z sid:83a16979-c35a-48ef-887e-af1e56bb5146 time:2024-06-01T00:19:03.701Z uid:f100a756-7127-40ea-8b6c-d48039b798b2 user:tim user_kind:1 events/emitter.go:288
```

An equivalent `ssh` command directly to the machine does succeed:
```
$ ssh -R 8111:localhost:8111 192.168.10.94 curl localhost:8111/get
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
{ 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "localhost:8111", 
    "User-Agent": "curl/7.88.1"
  }, 
  "origin": "172.17.0.1", 
  "url": "http://localhost:8111/get"
}
100   189  100   189    0     0  28996      0 --:--:-- --:--:-- --:--:-- 31500
```

Using `ssh` to connect via the Teleport proxy with a config from `tsh config` fails with the same symptoms, but does at least explicitly say that it failed instead of silently hanging the connection:
```
$ ssh -F ~/.ssh/tsh_config -R 8111:localhost:8111 teleport-node.teleport.ethernet.fyi
Warning: remote port forwarding failed for listen port 8111
```

Bug details:
- Teleport version: v16.0.0-alpha.3
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by atburke**
This change fixes a bug where remote port forwarding would fail if the local login the user is SSHing with doesn't match the local user running the node due to incorrect socket validation on the node. The incorrect Linux validation code has been removed and the rest merged with darwin since they're now identical. The remote port forwarding subprocess has also been updated to run as the correct user and group.

Fixes #42254
Fixes https://github.com/gravitational/teleport/issues/20619

Changelog: Fixed remote port forwarding validation error

### CODE REVIEW

File: lib/srv/reexec.go [hunk 1]
```diff
@@ -1100,12 +1100,35 @@ func ConfigureCommand(ctx *ServerContext, extraFiles ...*os.File) (*exec.Cmd, er
...
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
+		credential, err := getCmdCredential(localUser)
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
+
+		if os.Getuid() != int(credential.Uid) || os.Getgid() != int(credential.Gid) {
+			cmd.SysProcAttr.Credential = credential
```
Comment (espadolini) [inline lib/srv/reexec.go:1123]: Does an empty, non-nil SysProcAttr have a meaning? If not, can't we just set it here instead?
```suggestion
			cmd.SysProcAttr = &syscall.SysProcAttr{Credential: credential}
```

**Review by espadolini — APPROVED** [review]

**Review by espadolini — COMMENTED** [review]
Is there a decent way to add a test to exercise a different host user than the one running `teleport` using `-R`?

File: lib/srv/reexec.go (hunk 1 above)
Comment (codingllama) [reply lib/srv/reexec.go:1123]: +1

File: lib/srv/reexec.go [hunk 2]
```diff
@@ -1100,12 +1100,35 @@ func ConfigureCommand(ctx *ServerContext, extraFiles ...*os.File) (*exec.Cmd, er
...
+			log.Debugf("Creating process with UID %v, GID: %v, and Groups: %v.",
```
Comment (codingllama) [inline lib/srv/reexec.go:1124]: Please use structured logging.

File: lib/srv/reexec.go [hunk 3]
```diff
@@ -1100,12 +1100,35 @@ func ConfigureCommand(ctx *ServerContext, extraFiles ...*os.File) (*exec.Cmd, er
...
+				credential.Uid, credential.Gid, credential.Groups)
+		} else {
+			log.Debugf("Creating process with ambient credentials UID %v, GID: %v, Groups: %v.",
```
Comment (codingllama) [inline lib/srv/reexec.go:1127]: Same for structured logging.

Comment (codingllama) [inline lib/srv/reexec.go:1127]:
```suggestion
			log.Debugf("Creating process with environment credentials UID %v, GID: %v, Groups: %v.",
```

I think?

File: lib/srv/regular/sshserver_unix_test.go [hunk 4]
```diff
@@ -63,29 +62,18 @@ func TestValidateListenerSocket(t *testing.T) {
 		return left, listenerFD
 	}
 
-	u, err := user.Current()
-	require.NoError(t, err)
-
 	tests := []struct {
```
Comment (codingllama) [inline lib/srv/regular/sshserver_unix_test.go:65]: Does the existing test suite already reproduces the bug fixed here?

If not, could we make sure we have test coverage for it (and that it fails without the fix)?

**Comment by atburke** [comment]
> Is there a decent way to add a test to exercise a different host user than the one running `teleport` using `-R`?

Maybe, but I haven't been able to find it. To ensure that there are two users to test with, the test would have to run as root to create a second user. But if the test then tries to re-exec as the second user, it fails with permission denied to `/proc/self/exe`.

File: lib/srv/exec_linux_test.go [hunk 5]
```diff
@@ -132,6 +137,36 @@ func TestConfigureCommand(t *testing.T) {
 	require.NotContains(t, cmd.Env, unexpectedKey+"="+unexpectedValue)
 }
 
+func TestRootConfigureCommand(t *testing.T) {
+	utils.RequireRoot(t)
+
+	login := "teleport-test-user"
+	_, err := host.UserAdd(login, nil, "", "", "")
```
Comment (codingllama) [inline lib/srv/exec_linux_test.go:144]: Will this fail if the user exists?

Could we avoid creating a new OS user just for testing?

File: lib/srv/reexec.go [hunk 6]
```diff
@@ -1106,6 +1107,29 @@ func ConfigureCommand(ctx *ServerContext, extraFiles ...*os.File) (*exec.Cmd, er
...
 
+	// For remote port forwarding, the child needs to run as the user to
+	// create listeners with the correct permissions.
+	if subCommand == teleport.RemoteForwardSubCommand {
+		localUser, err := user.Lookup(ctx.Identity.Login)
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
+		// Ensure that the working directory is one that the child has access to.
+		cmd.Dir = localUser.HomeDir
```
Comment (codingllama) [inline lib/srv/reexec.go:1118]: Why is this necessary?

Could this have unintended consequences? What if the user doesn't have a home?

File: lib/srv/exec_linux_test.go (hunk 5 above)
Comment (atburke) [reply lib/srv/exec_linux_test.go:144]: I'm not sure how to avoid creating a user for the test given that the behavior between multiple users is exactly what we're testing, but I've updated this to generate a new login each time so pre-existing users won't be a problem.

File: lib/srv/reexec.go (hunk 6 above)
Comment (atburke) [reply lib/srv/reexec.go]: Default behavior is for the child process to inherit the workdir from the parent, but if the processes are running under different users (i.e. root parent and non-root child) the child will get a permission error and port forwarding will fail.

If the user doesn't have a home, they should be dropped at root, but I updated this to drop everyone at root so we don't have to worry about it.

File: lib/srv/reexec.go [hunk 7]
```diff
@@ -1106,6 +1107,29 @@ func ConfigureCommand(ctx *ServerContext, extraFiles ...*os.File) (*exec.Cmd, er
...
 
+	// For remote port forwarding, the child needs to run as the user to
+	// create listeners with the correct permissions.
+	if subCommand == teleport.RemoteForwardSubCommand {
+		localUser, err := user.Lookup(ctx.Identity.Login)
+		if err != nil {
+			return nil, trace.Wrap(err)
+		}
+		// Ensure that the working directory is one that the child has access to.
+		cmd.Dir = string(os.PathSeparator)
```
Comment (codingllama) [inline lib/srv/reexec.go:1118]: nit: semantics:

```suggestion
		cmd.Dir = "/"
```

File: lib/utils/testhelpers.go [hunk 8]
```diff
@@ -87,3 +91,28 @@ func RunTestBackgroundTask(ctx context.Context, t *testing.T, task *TestBackgrou
...
+// RequireRoot skips the current test if it is not running as root.
+func RequireRoot(t *testing.T) {
+	t.Helper()
+	if os.Geteuid() != 0 {
+		t.Skip("This test will be skipped because tests are not being run as root.")
+	}
+}
+
+// GenerateLocalUsername generates the username for a local user that does not
+// already exist (but it does not create the user).
```
Comment (codingllama) [inline lib/utils/testhelpers.go:104]:
```suggestion
// already exists (but it does not create the user).
```

File: lib/srv/exec_linux_test.go (hunk 5 above)
Comment (codingllama) [reply lib/srv/exec_linux_test.go:144]: If we could cleanup after ourselves that would be best.

File: lib/utils/testhelpers.go [hunk 9]
```diff
@@ -87,3 +91,28 @@ func RunTestBackgroundTask(ctx context.Context, t *testing.T, task *TestBackgrou
...
+func GenerateLocalUsername(t *testing.T) string {
+	login := uuid.NewString()[:12]
```
Comment (codingllama) [inline lib/utils/testhelpers.go:106]: This will have a in it dash, right?

Will this cause problems if the username begins with a number?

Should we do something more directed, maybe "teleport-$(random hex characters from crypto/rand.Reader)"

File: lib/utils/testhelpers.go [hunk 10]
```diff
@@ -87,3 +91,28 @@ func RunTestBackgroundTask(ctx context.Context, t *testing.T, task *TestBackgrou
...
+	for i := 0; i < 10; i++ {
+		if _, err := user.Lookup(login); err == nil {
+			login = uuid.NewString()[:12]
+			continue
+		}
+		notFound = true
+		break
+	}
+	require.True(t, notFound, "unable to generate a new username")
+	return login
```
Comment (codingllama) [inline lib/utils/testhelpers.go:117]:
```suggestion
	const maxAttempts = 10
	for i := 0; i < maxAttempts; i++ {
		login = uuid.NewString()[:12]
		if _, err := user.Lookup(login); errors.Is(err, ErrorThatSignifiesNotFound) {
			return login
		} else if err != nil {
			t.Fatalf("user.Lookup failed unexpectedly: %v", err)
		}
	}
	t.Fatalf("Unable to generate unused username after %v attempts", maxAttempts)
```

File: lib/srv/exec_linux_test.go (hunk 5 above)
Comment (atburke) [reply lib/srv/exec_linux_test.go:144]: We do a few lines down. https://github.com/gravitational/teleport/blob/5ca7c657005ef3201562adfdbbf4c92c0ee23fc1/lib/srv/exec_linux_test.go#L146-L149

**Review by codingllama — APPROVED** [review]
