### PR TITLE
Fix agent mesh integration test

### LINKED ISSUE #13631: `TestProxyTunnelStrategyAgentMesh` flakiness
## Failure
saw this fail off branch/v10

### CI Logs
- https://console.cloud.google.com/cloud-build/builds/e6c0fcec-d830-4cae-8512-ce19b7331e35;step=0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/80cc41dc-82a7-44dd-9cfb-f36f2d54fbbc?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/a3df41b7-98d8-4d8e-b4d0-d53ae38a6740?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/72ebc849-860d-46f1-9580-641372a7bb29?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/81f3d83b-e829-43d3-9f5f-f92e2c897bd1?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/95c9172b-1b23-4892-a56b-b1e626e1111a?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/fca8334c-03a5-4f5d-bace-3241d2c0a1be?project=ci-account

### Relevant snippet
```
    integration_test.go:3242: 
        	Error Trace:	integration_test.go:3242
        	            				proxy_tunnel_strategy_test.go:109
        	Error:      	Condition never satisfied
        	Test:       	TestProxyTunnelStrategyAgentMesh
        	Messages:   	Active tunnel connections did not reach 2 in the expected time frame
```

### PR DESCRIPTION
**Pull request by dboslee**
By using a randomized load balancer we improve the chances of an agent ~~failing
to connect~~ connecting to all proxy servers within the given time period.

I did have an alternative solution where we wait for each agent to connect before starting the next but this is essentially the same as adding a longer timeout to the test.

Closes #13631

### CODE REVIEW

File: integration/proxy_tunnel_strategy_test.go [hunk 1]
```diff
@@ -226,11 +226,19 @@ func (p *proxyTunnelStrategy) makeLoadBalancer(t *testing.T) {
 		require.Fail(t, "load balancer already initialized")
 	}
 
+	ctx, cancel := context.WithCancel(context.Background())
+	t.Cleanup(func() {
+		cancel()
+	})
```
Comment (zmb3) [inline integration/proxy_tunnel_strategy_test.go:232]:
```suggestion
	t.Cleanup(cancel)
```

**Review by NajiObeid — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Review by ibeckermayer — APPROVED** [review]
