### PR TITLE
Regenerate host UUID of node if host_uuid is empty

### LINKED ISSUE #10613: regenerated UUID of teleport node if file 'host_uuid' is empty.
### What
teleport node start fails with error `WARN Host UUID "" is not a true UUID (not eligible for UUID-based proxying) service/service.go:667` and `Node failed to establish connection to cluster: missing parameter HostID, Get "[https://teleport.cluster.local/v2/cacert":](https://teleport.cluster.local/v2/cacert%22:) EOF. service/connect.go:68` if `host_uuid` file under `data_dir` is empty. 

`host_uuid` file can be empty if teleport process starts in a node, which is not connected to network or `host_uuid` file is manually emptied.

### How
If teleport node process find `host_uuid` file empty, it should generate UUID again, than failing to start.

### Why
Why do you need this?
In some automation cases, nodes might not be able to connect to teleport cluster at first startup, which can cause `host_uuid` file to be empty (There may be other scenarios which can cause it). teleport node process should be able to re-generate UUID, if its not already present in teleport cluster.

### Workaround
If a workaround exists, please include it.

Manual removal teleport data_dir and restart of teleport process on node fixes it. But in some automation usecases, it might not be a good option.

### PR DESCRIPTION
**Pull request by atburke**
In this PR, nodes now regenerate their UUID if the `host_uuid` file exists but is empty.

Tests in `lib/utils/utils_test.go` were also ported to testify.

Fixes #10613.

### CODE REVIEW

**Comment by zmb3** [comment]
I don't see the code that regenerates the host UUID, can you point me to it?

**Comment by atburke** [comment]
@zmb3 https://github.com/gravitational/teleport/blob/d01f3e084582dc87e4e25b29f235d7210a1e4280/lib/utils/utils.go#L468-L487

The UUID generation specifically is on line 478.

**Comment by zmb3** [comment]
But that code already existed, so how does this change the behavior?

**Comment by atburke** [comment]
`ReadHostUUID()` now also returns `trace.NotFound` if `host_uuid` is empty, not just when the file is missing. `ReadOrMakeHostUUID()` treats both cases the same.

File: lib/utils/utils.go [hunk 1]
```diff
@@ -471,7 +475,11 @@ func ReadOrMakeHostUUID(dataDir string) (string, error) {
 	if !trace.IsNotFound(err) {
 		return "", trace.Wrap(err)
 	}
-	id = uuid.New().String()
+	rawID, err := uuid.NewRandom()
```
Comment (r0mant) [inline lib/utils/utils.go:478]: Do you know if it's possible that this returns an empty UUID with a nil error?

**Review by r0mant — APPROVED** [review]
Looks good to me!

**Comment by russjones** [comment]
@atburke 

* Can you share a sample error message?
* Let's make sure to share a dev build with the customer before we merge this.

File: lib/utils/utils.go (hunk 1 above)
Comment (atburke) [reply lib/utils/utils.go:478]: It is not possible. `uuid.UUID` is an alias for `[16]byte`, so the emptiest it can get is a string of zeros (and `NewRandom()` ensures that there are a few nonzero bytes).

**Comment by atburke** [comment]
It just does a `trace.Wrap()` of the output of `NewRandom()`, so the error looks like
```
$ teleport start
ERROR: initialization failed
unexpected EOF
```
Would it be worth making that more specific?

**Comment by r0mant** [comment]
@atburke Yes, we need to make it better. For example, say "Teleport failed to generate host UUID. This may happen if randomness source is not fully initialized when the node is starting up. Please try restarting Teleport again". @russjones Does this message look ok to you?

File: api/utils/slices_test.go [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+
+	"github.com/stretchr/testify/require"
+)
+
+func TestSliceContainsStr(t *testing.T) {
+	tests := []struct {
+		name          string
+		slice         []string
+		target        string
+		shouldContain bool
```
Comment (codingllama) [inline api/utils/slices_test.go:30]: Maybe:

```suggestion
		wantContains bool
```

so it matches the usual Go `got` and `want` in tests.

File: api/utils/slices_test.go [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+		})
+	}
+}
+
+func TestDeduplicate(t *testing.T) {
+	tests := []struct {
+		name         string
+		in, expected []string
+	}{
+		{"empty slice", []string{}, []string{}},
```
Comment (codingllama) [inline api/utils/slices_test.go:48]: Ditto for field names, same throughout the PR.

**Review by codingllama — COMMENTED** [review]
Thanks for the test migrations and sorry about the delay.

**Review by codingllama — APPROVED** [review]

**Review by hatched — APPROVED** [review]

File: lib/service/service.go [hunk 4]
```diff
@@ -666,7 +666,11 @@ func NewTeleport(cfg *Config) (*TeleportProcess, error) {
 		} else {
 			switch cfg.JoinMethod {
 			case types.JoinMethodToken, types.JoinMethodUnspecified, types.JoinMethodIAM:
-				cfg.HostUUID = uuid.New().String()
+				rawID, err := uuid.NewRandom()
+				if err != nil {
+					return nil, trace.Wrap(err)
+				}
+				cfg.HostUUID = rawID.String()
```
[the remark this answers is not in the document]
Comment (r0mant) [reply lib/service/service.go]: @codingllama @atburke Guys, we specifically wanted to avoid using NewString to avoid the panic and print a proper error message to users. This can (and does) happen when Teleport starts very early in the node initialization cycle and urandom isn't initialized yet. A customer is seeing this in their environment.

@atburke Can you please roll this back to the way it was originally implemented and make sure we return an proper error message as specified in https://github.com/gravitational/teleport/pull/11810#issuecomment-1093154334.

[the remark this answers is not in the document]
Comment (r0mant) [reply lib/service/service.go]: Yeah, I think for now doing this only for node ID generation would suffice to address the customer issue, it's pretty "edge-casey" scenario for sure and only happens when Teleport starts for the very first time. Agree with adding a clarifying comment.
