### PR TITLE
X11 forwarding fixes for Mac and Windows

### LINKED ISSUE #11075: tsh ssh -X fails on windows
```
> tsh ssh -X somehost
ERROR: stderr: ""
exit status 1
```

`tsh ssh -Y` still works and this seems to be a windows only issue. It is likely that the error has to do with `xauth` but the error isn't being reported correctly and results in an empty string.

Edit: 

I did some debugging, and unfortunately there are a lot of issues at play.

First of all, in MobaXterm, the `-X` flag does not work in `tsh ssh` or `ssh`. When using a Standalone XServer, `tsh ssh -X` does not return the error reported above, but does fail to finish the untrusted forwarding set up.

In all cases, it looks like the errors are related to `xauth` failing to perform as expected. `xauth` creates a ~/.Xauthority-n` file, but does not finalize it into the ~/.Xauthority` file, so neither `tsh` or `ssh` can use the generated xauthentication data.

In `ssh -X` this results in the following warning, and x11 forwarding is disabled for the session.
```
Warning: untrusted X11 forwarding setup failed: xauth key data not generated
```

In `tsh ssh -X`, there is no error or warning when it fails to detect the xauth data, but attempts to run X Programs result in:
```
DEBU [CLIENT]    received X11 channel request from 127.0.0.1:3022 client\x11_session.go:153
X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  55 (X_CreateGC)
  Resource id in failed request:  0x5a
  Serial number of failed request:  3
  Current serial number in output stream:  4
```

So ultimately, this appears to be a problem with the `xauth` executable that ships with MobaXterm -`v1.0.8`. Upgrading to `v1.0.10` through the MobaXTerm packages tool does not fix the issues. If it's possible to upgrade to `v1.1`, that may help, but I'm not sure where to find that.

### PR DESCRIPTION
**Pull request by Joerger**
Changes:
  - Update xauth command to capture stderr properly - prevents the `stderr:""` issue in the issue below
  - Fix untrusted X11 forwarding Windows by closing temporary xauth file before running `xauth`
  - Fix X11 forwarding server on Mac by using "/tmp/.X11-unix"

Fixes https://github.com/gravitational/teleport/issues/11075

### CODE REVIEW

File: lib/sshutils/x11/display.go [hunk 1]
```diff
@@ -227,5 +227,7 @@ func ParseDisplay(displayString string) (Display, error) {
 }
 
 func x11SockDir() string {
-	return filepath.Join(os.TempDir(), x11SocketDirName)
+	// We use "/tmp" instead of "os.TempDir" because X11
+	// is not OS aware and uses "/tmp" regardless of OS.
+	return filepath.Join("/tmp", x11SocketDirName)
```
Comment (zmb3) [inline lib/sshutils/x11/display.go:232]: Even on Windows?

File: lib/srv/reexec.go [hunk 2]
```diff
@@ -286,10 +286,9 @@ func RunCommand() (errw io.Writer, code int, err error) {
 
 		// Copy the re-exec command's io and user environment fields.
 		cpyCmdFields := func(cmd *exec.Cmd, params *exec.Cmd) {
-			cmd.Stdout = params.Stdout
-			cmd.Stdin = params.Stdin
-			cmd.Stderr = params.Stderr
-			cmd.SysProcAttr = params.SysProcAttr
```
Comment (zmb3) [inline lib/srv/reexec.go:292]: So `params.SysProcAttr` is just ignored?

File: lib/sshutils/x11/display.go (hunk 1 above)
Comment (Joerger) [reply lib/sshutils/x11/display.go:232]: I'm not sure, I've tested with `Xming`, `MobaXTerm`, and `VcXsrv` on Windows, which all use tcp sockets instead of unix sockets, so those won't be affected. I don't know of a Windows XServer that uses a unix socket, but my current assumption is that `/tmp/.X11-unix` is a hard coded value in the X Window System. A $DISPLAY like `unix:n` or `:n` always gets translated to `/tmp/.X11-unix/Xn` by X Programs from what I have tested.

Comment (nklaassen) [reply lib/sshutils/x11/display.go:232]: I don't think `/tmp` is ever going to work on windows, could we return an error?

Comment (Joerger) [reply lib/sshutils/x11/display.go:232]: With MobaXterm, Cgywin, and other custom unix-like windows terminals, `/tmp` can be used this way. In fact, given the X11 protocol, I believe this is the only way for any OS to support unix sockets for their X Server.

I actually just tested out Cgywin/X because I found out that it uses unix sockets for its X Server implementation (`/tmp/.X11-unix/X0`), so I believe the current implementation is correct.

Comment (nklaassen) [reply lib/sshutils/x11/display.go:232]: hmm, TIL, thanks

File: lib/sshutils/x11/auth.go [hunk 3]
```diff
@@ -148,24 +148,40 @@ func (x *XAuthCommand) GenerateUntrustedCookie(display Display, timeout time.Dur
...
+	if err := x.Cmd.Start(); err != nil {
+		return nil, trace.Wrap(err)
+	}
+
+	out, err := io.ReadAll(stdout)
+	if err != nil {
+		return nil, trace.Wrap(err)
+	}
+
+	errOut, err := io.ReadAll(stderr)
```
[the remark this answers is not in the document]
Comment (nklaassen) [reply lib/sshutils/x11/auth.go]: What if it's not actually `xauth`? I'm imagining a DOS where someone can replace the `xauth` command in the path and spam stderr (but there are probably bigger problems if someone can replace `xauth` tbh). I was thinking of a big limit just as a safety, like 1MB or something but I don't really know anything about this code path so up to you

**Review by nklaassen — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]
