### PR TITLE
Terminal Size Sync

### LINKED ISSUE #1692: Teleport does not set terminal size correctly on connection
**What happened**: Terminal size is not set correctly and text wrapping does not work correctly. Fix for #1087 does not work.

**What you expected to happen**: Text to wrap correctly as per every other terminal app.

**How to reproduce it (as minimally and precisely as possible)**:
```
adama@swiftdesk6:~$ tsh version
Teleport v2.4.1 git:v2.4.1-0-gf90cc7c
adama@swiftdesk6:~$ tput cols
90
adama@swiftdesk6:~$ tput lines
57
adama@swiftdesk6:~$ tsh --proxy=teleport.local --cluster=od003 ssh root@od003
root@od003:~# tsh version
Teleport v2.4.1 git:v2.4.1-0-gf90cc7c
root@od003:~# tput cols
80
root@od003:~# tput lines
24
root@od003:~# 
```

This was run in gnome-terminal and mate-terminal as per my original comments on #1087 with the same failure results

**Environment**:
- Teleport version (use `teleport version`):  Teleport v2.4.1 git:v2.4.1-0-gf90cc7c
- Tsh version (use `tsh version`):  Teleport v2.4.1 git:v2.4.1-0-gf90cc7c
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

In https://github.com/gravitational/teleport/pull/1601 and https://github.com/gravitational/teleport/pull/1584 a regression was fixed in Teleport 2.4.0 where sessions are being recorded at both the node and the proxy. To solve this problem a  discarding session server was used so when the cluster is recording session at the proxy nodes don't update the sessions stored in the backend, all changes come from the proxy.

Due to this, when the `pollAndSync` loop was run in Teleport nodes, it got incorrect information on terminal sizes from the discarding session server and would then update the size incorrectly. The fix is to not update terminal sizes in the node if sessions are being recorded at the proxy.

**Implementation**

* If sessions are being recorded at the proxy and `pollAndSync` is running in a Teleport node, don't sync, allow that to happen in the proxy.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1692

### CODE REVIEW

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

File: lib/srv/sess.go [hunk 1]
```diff
@@ -734,13 +735,28 @@ func (s *session) getNamespace() string {
...
-// pollAndSync is a loop inside a goroutite which keeps synchronizing the terminal
-// size to what's in the session (so all connected parties have the same terminal size)
-// it also updates 'active' field on the session.
+// pollAndSync is a loops forever trying to sync terminal size to what's in
+// the session (so all connected parties have the same terminal size) and
+// update the "active" field of the session. If the session are recorded at
+// the proxy, then this function does nothing as it's counterpart in the proxy
+// will do this work.
 func (s *session) pollAndSync() {
 	log.Debugf("[session.registry] start pollAndSync()\b")
```
Comment (klizhentas) [inline lib/srv/sess.go]: while we are on it, can you remove `\b` and user log.WithFields? otherwise it renders strange in logs

File: lib/srv/sess.go [hunk 2]
```diff
@@ -734,13 +735,28 @@ func (s *session) getNamespace() string {
...
 	defer log.Debugf("[session.registry] end pollAndSync()\n")
 
+	// If sessions are being recorded at the proxy, an identical version of this
+	// goroutine is running in the proxy, which means it does not need to run here.
+	clusterConfig, err := s.registry.srv.GetAccessPoint().GetClusterConfig()
+	if err != nil {
+		log.Errorf("Unable to sync terminal size: %v.", err)
+		return
+	}
+	if clusterConfig.GetSessionRecording() == services.RecordAtProxy {
```
Comment (klizhentas) [inline lib/srv/sess.go]: why not use logical `&&` and use nested if?

Comment (russjones) [reply lib/srv/sess.go]: The line got too long, didn't look nice.

File: lib/srv/sess.go [hunk 3]
```diff
@@ -66,8 +69,28 @@ func init() {
...
 	sessions map[rsession.ID]*session
-	srv      Server
+
+	// srv refers to the upon which this session registry is created.
+	srv Server
+}
+
+func NewSessionRegistry(srv Server) *SessionRegistry {
+	if srv.GetSessionServer() == nil {
+		panic("need a session server")
```
Comment (klizhentas) [inline lib/srv/sess.go]: let's not panic in libraries as a rule of thumb

File: constants.go [hunk 4]
```diff
@@ -118,6 +118,18 @@ const (
 	// ComponentKeyGen is the public/private keypair generator.
 	ComponentKeyGen = "keygen"
 
+	// ComponentSessionParty is a member of the session.
+	ComponentSessionParty = "session:party"
```
Comment (klizhentas) [inline constants.go]: I think this is too many components, let's just keep one component - `session`

File: lib/srv/sess.go [hunk 5]
```diff
@@ -98,7 +123,7 @@ func (s *SessionRegistry) OpenSession(ch ssh.Channel, req *ssh.Request, ctx *Ser
 			events.RemoteAddr:      ctx.Conn.RemoteAddr().String(),
 			events.SessionServerID: ctx.srv.ID(),
 		})
-		ctx.Infof("[SESSION] joining session: %v", ctx.session.id)
+		ctx.Infof("Joining session %v already in context.", ctx.session.id)
```
Comment (klizhentas) [inline lib/srv/sess.go]: what is already in context? not clear

File: lib/srv/sess.go [hunk 6]
```diff
@@ -116,7 +141,7 @@ func (s *SessionRegistry) OpenSession(ch ssh.Channel, req *ssh.Request, ctx *Ser
 	}
 	ctx.session = sess
 	s.addSession(sess)
-	ctx.Infof("[SESSION] new session %v", sid)
+	ctx.Infof("Creating new session %v in context.", sid)
```
Comment (klizhentas) [inline lib/srv/sess.go]: what is in context?

File: lib/srv/sess.go [hunk 7]
```diff
@@ -264,21 +289,139 @@ func (s *SessionRegistry) findSession(id rsession.ID) (*session, bool) {
...
+		party.termSizePusher(ch)
+		return nil
 	}
-	return &SessionRegistry{
-		srv:      srv,
-		sessions: make(map[rsession.ID]*session),
+
+	return trace.Errorf("unable to push term size to party")
+}
+
```
Comment (klizhentas) [inline lib/srv/sess.go]: this reads like a lot of new code was just added/changed that was not there?

File: lib/srv/sess.go [hunk 8]
```diff
@@ -363,10 +506,13 @@ func newSession(id rsession.ID, r *SessionRegistry, ctx *ServerContext) (*sessio
 		// return nil, trace.Wrap(err)
 		// No need to abort. Perhaps the auth server is down?
 		// Log the error and continue:
-		log.Errorf("failed logging new session: %v", err)
+		r.log.Errorf("Failed to create new session: %v.", err)
 	}
 
 	sess := &session{
+		log: logrus.WithFields(logrus.Fields{
+			trace.Component: fmt.Sprintf("%v:%v", teleport.ComponentSession, r.srv.Component()),
```
Comment (klizhentas) [inline lib/srv/sess.go]: there is a function for that: `teleport.Component` that constructs components vs using sprintf directly

File: lib/srv/sess.go (hunk 2 above)
Comment (klizhentas) [reply lib/srv/sess.go]: you can use multi-line if :)

**Review by klizhentas — CHANGES_REQUESTED** [review]
With new code reshuffling the patch became too big to merge in patch release due to the scope of changes, can you bring the PR to a state that focuses on your fix.

**Review by klizhentas — APPROVED** [review]
