### PR TITLE
LocalKeyAgent only loads keys for a user logged into a proxy.

### LINKED ISSUE #1541: tsh logout
## Logout

```
# In case if user is logged in as `bob@example.com`, but current shell username is `bob`,
# this will be effect
tsh logout
bob is not logged in
```

Instead, `tsh logout` should just clean up all ~/tsh folder basically logging user out at all times.

### LINKED ISSUE #1611: Teleport login problem
**What happened**:

Tsh login does not work normally with two proxies/auth servers connected to the same SAML/OIDC auth provider.

**What you expected to happen**:

Credentials will work for both first proxy and second proxy.

**How to reproduce it (as minimally and precisely as possible)**:

Have two proxies/auth servers connected to the same OIDC/SAML provider.
Login to the first proxy with a user
Login to the second proxy with a user

As long as user does second login, tsh ls stops working for both first and second login, always prompting user to relogin.

**Environment**:
- Teleport version (use `teleport version`):
2.4.0
- Tsh version (use `tsh version`):
2.4.0
- OS (e.g. from /etc/os-release):
linux
**Browser environment**
N/A

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

### PR DESCRIPTION
**Pull request by russjones**
**Purpose**

https://github.com/gravitational/teleport/issues/1541 and https://github.com/gravitational/teleport/issues/1611 cover two problems `tsh` has. The first is that Teleport will use the incorrect key when trying to connect to a cluster if you use the same username across different proxies. The second issue is that Teleport does not log a user out correctly.

**Implementation**

* `GetKeys` has been removed from `LocalKeyAgent` as it now only operates on a single user and proxy at a time. This was done to simplify the logic for `LocalKeyAgent` otherwise to fix https://github.com/gravitational/teleport/issues/1541 `LocalKeyAgent` would have to be updated to know about multiple proxies. 
* Added `DeleteKeys` to remove all keys to `FSLocalKeyStore` to remove all keys for all users connected to all proxies.
* `tsh logout` without any parameters will call `DeleteKeys` and remove all keys for all users connected to all proxies.
* `tsh --proxy=one.example.com --user=rjones` will log out `rjones` from `one.example.com`.

**Related Issues**

Fixes https://github.com/gravitational/teleport/issues/1541
Fixes https://github.com/gravitational/teleport/issues/1611

### CODE REVIEW

File: lib/client/keystore.go [hunk 1]
```diff
@@ -190,37 +184,54 @@ func (fs *FSLocalKeyStore) DeleteKey(host string, username string) error {
 	return nil
 }
 
+// DeleteKeys removes all session keys from disk.
+func (fs *FSLocalKeyStore) DeleteKeys() error {
+	dirPath := filepath.Join(fs.KeyDir, sessionKeyDir)
+
+	err := os.RemoveAll(dirPath)
```
Comment (klizhentas) [inline lib/client/keystore.go]: what if you logout twice this will be an error? probably should handle not found error on the upper level

File: tool/tsh/tsh.go [hunk 2]
```diff
@@ -343,21 +343,39 @@ func onLogin(cf *CLIConf) {
...
 		}
-		if err = tc.Logout(); err != nil {
-			if trace.IsNotFound(err) {
-				utils.FatalError(trace.Errorf("you are not logged into proxy '%s'", cf.Proxy))
-			}
-			utils.FatalError(err)
+		fmt.Printf("Logged out %v from %v.\n", cf.Username, proxyHost)
+	// remove all keys
+	case proxyHost == "" && cf.Username == "":
+		err = flka.DeleteKeys()
```
Comment (klizhentas) [inline tool/tsh/tsh.go]: check NotFound condition here - tsh logout called twice should not result in error

**Review by klizhentas — COMMENTED** [review]
Have a couple of comments, see inline

**Review by kontsevoy — APPROVED** [review]

File: lib/client/keystore.go (hunk 1 above)
Comment (russjones) [reply lib/client/keystore.go]: Doesn't return an error if called twice: https://golang.org/pkg/os/#RemoveAll

```
RemoveAll removes path and any children it contains. It removes everything it can
but returns the first error it encounters. If the path does not exist, RemoveAll
returns nil (no error).
```

File: tool/tsh/tsh.go (hunk 2 above)
Comment (russjones) [reply tool/tsh/tsh.go]: `DeleteKeys` does not return an error. However, I cleaned up the error message when logging out a specific user a few lines up.

**Review by klizhentas — APPROVED** [review]
