### PR TITLE
Fix an issue tsh throws assertion error on REDIS_REPLY_STATUS for Redis 7

### LINKED ISSUE #19240: AWS Redis ElastiCache 7.0.4 Engine Version failing to connect
Current behavior:
AWS ElastiCache connectin to Redis with 7.0.4 Engine Version is not deterministic and fails depending on the db  agent state: 
```
$ tsh db connect --db-user=test marek-redis07
Assertion failed: (flags->element[j]->type == REDIS_REPLY_STATUS), function cliAddArgument, file redis-cli.c, line 585.
ERROR: signal: abort trap

$ tsh db connect --db-user=test marek-redis07
Assertion failed: (flags->element[j]->type == REDIS_REPLY_STATUS), function cliAddArgument, file redis-cli.c, line 585.
ERROR: signal: abort trap

$ tsh db connect --db-user=test marek-redis07
Assertion failed: (flags->element[j]->type == REDIS_REPLY_STATUS), function cliAddArgument, file redis-cli.c, line 585.
ERROR: signal: abort trap

$ tsh db connect --db-user=test marek-redis07
Assertion failed: (flags->element[j]->type == REDIS_REPLY_STATUS), function cliAddArgument, file redis-cli.c, line 585.
ERROR: signal: abort trap

$ tsh db connect --db-user=test marek-redis07
Assertion failed: (flags->element[j]->type == REDIS_REPLY_STATUS), function cliAddArgument, file redis-cli.c, line 585.
ERROR: signal: abort trap

$ tsh db connect --db-user=test marek-redis07
Assertion failed: (flags->element[j]->type == REDIS_REPLY_STATUS), function cliAddArgument, file redis-cli.c, line 585.
ERROR: signal: abort trap
```
I was able to connect when db agent was restarted and `tsh db connect` was triggered immediately after db agent restart: 
```
$ tsh db connect --db-user=test marek-redis07
localhost:56752> get a
"foobar"
```
but after closing the redis-cli client and trying to connect second time the same error is returned:
```
$ tsh db connect --db-user=test marek-redis07
Assertion failed: (flags->element[j]->type == REDIS_REPLY_STATUS), function cliAddArgument, file redis-cli.c, line 585.
ERROR: signal: abort trap
```

Bug details:
- Teleport version
    - Teleport DB agent : v11.0.3
    - Teleprot Proxy/Auth v11.1.2
    - redis-cli: 7.0.5
- Recreation steps
  - AWS ElastiCache setup with Redis engine version >= 7.0

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #19240 
- #19240

Error from `tsh db connect <redis-7>`
```
$ tsh db connect --db-user=test marek-redis07
Assertion failed: (flags->element[j]->type == REDIS_REPLY_STATUS), function cliAddArgument, file redis-cli.c, line 585.
ERROR: signal: abort trap
```

Root cause:
`redis-cli` sends `COMMAND DOCS` to construct docs for commands and expect status type (`+<status>`) as part of the response. The go-redis driver however reads status into golang strings and writes them as string types (`$<len><string>`). 

Changes:
- Driver side change: https://github.com/gravitational/redis/pull/22
- Adding a UT for regression test

Notes:

- `COMMAND DOCS` is new to Redis 7, so using `redis-cli` 6.2 would not see this issue
- There was a test escpae from my side when first testing out Redis 7 as I was testing with a user without `COMMAND XXX` permissions so `redis-cli` will always get `NO PERM` thus not seeing this error.

### CODE REVIEW

File: lib/srv/alpnproxy/local_proxy.go [hunk 1]
```diff
@@ -28,7 +28,6 @@ import (
 
 	"github.com/gravitational/trace"
 	"github.com/jonboulle/clockwork"
-	"github.com/siddontang/go/log"
```
Comment (greedy52) [inline lib/srv/alpnproxy/local_proxy.go:31]: caught this when `go mod tidy` tries to add this a "direct" dependency

**Review by jakule — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
