### PR TITLE
Fix utmp accounting on system with bad glibc default

### LINKED ISSUE #8360: re-exec (teleport exec) "Failed to launch: unknown error with code 7."
### Description

**What happened**:

error "[Failed to launch:](https://github.com/gravitational/teleport/blob/v6.2.8/lib/srv/reexec.go#L354) [unknown error with code](https://github.com/gravitational/teleport/blob/v6.2.8/lib/srv/uacc/uacc_linux.go#L177) [7](https://github.com/gravitational/teleport/blob/v6.2.8/lib/srv/uacc/uacc.h#L81)" appears on logout.

This error comes from a child process `/usr/local/bin/teleport exec` .
See debug logs what happens there.

**What you expected to happen**:
- no error or failed message
- /var/run/utmp should be modified on exit

### Reproduction Steps
1. ssh rhel-8.4-server
2. exit

### Server Details
- Teleport version: Teleport v6.2.8 git:v6.2.8-0-g0bbeffb63 go1.15.5
- Server OS: Red Hat Enterprise Linux 8.4 (Ootpa)
   - glibc-2.28-151.el8.x86_64 : The GNU libc libraries
     Repo        : rhel-8-for-x86_64-baseos-rpms
- Where are you running Teleport? Dedicated Hardware / vmware

### Client Details
- Tsh version (`tsh version`): Teleport v6.2.8 git:v6.2.8-0-g0bbeffb63 go1.15.5
- Computer OS (e.g. Linux, macOS, Windows): Linux/Windows(native ssh with RSA-CERT from tsh)
- Installed via: Linux(yum/dnf), Windows(choco install teleport-tsh)

### Debug Logs

strace `teleport exec` process [exited with 255](https://github.com/gravitational/teleport/blob/v6.2.8/lib/srv/reexec.go#L247):

```
strace: Process 735567 attached
waitid(P_PID, 735574, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=735574, si_uid=1001, si_status=0, si_utime=0, si_stime=0}, WEXITED|WNOWAIT, NULL) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=735574, si_uid=1001, si_status=0, si_utime=14, si_stime=5} ---
rt_sigreturn({mask=[]})                 = 0
futex(0x4800cd8, FUTEX_WAKE_PRIVATE, 1) = 1
wait4(735574, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, {ru_utime={tv_sec=0, tv_usec=337927}, ru_stime={tv_sec=0, tv_usec=265840}, ...}) = 735574
readlinkat(AT_FDCWD, "/proc/self/fd/6", "/dev/pts/0", 128) = 10
lstat("/var", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/var/run", {st_mode=S_IFLNK|0777, st_size=6, ...}) = 0
readlink("/var/run", "../run", 4095)    = 6
lstat("/run", {st_mode=S_IFDIR|0755, st_size=1220, ...}) = 0
lstat("/run/utmp", {st_mode=S_IFREG|0664, st_size=5376, ...}) = 0
write(6, "Failed to launch: unknown error "..., 46) = 46
exit_group(255)                         = ?
+++ exited with 255 +++
```

`stat /var/run/utmp`:

```
  File: /var/run/utmp
  Size: 6528            Blocks: 16         IO Block: 4096   regular file
Device: 18h/24d Inode: 13232       Links: 1
Access: (0664/-rw-rw-r--)  Uid: (    0/    root)   Gid: (   22/    utmp)
Context: system_u:object_r:initrc_var_run_t:s0
Access: 2021-09-23 22:59:27.550760932 +0200
Modify: 2021-09-23 22:40:28.503557706 +0200
Change: 2021-09-23 22:40:28.503557706 +0200
 Birth: -
```

`namei -l /var/run/utmp`:

```
f: /var/run/utmp
dr-xr-xr-x root root /
drwxr-xr-x root root var
lrwxrwxrwx root root run -> ../run
dr-xr-xr-x root root   ..
drwxr-xr-x root root   run
-rw-rw-r-- root utmp utmp
```

### PR DESCRIPTION
**Pull request by xacrimon**
On some systems, mainly RHEL, the `_*_PATH` macros used to resolve the utmp UNIX user accounting database are sometimes wrong. Did some digging, still not sure why, added further details as a comment. This seems to work everywhere and I've had users test this on affected systems.

This PR also adds additional diagnostics if `realpath` decides to fail in such a way that glibc exposes extra debugging info as a non-posix extension.

Needs backport to v8.

Fixes #8360

### CODE REVIEW

**Review by hatched — APPROVED** [review]

File: lib/srv/uacc/uacc.h [hunk 1]
```diff
@@ -78,6 +92,8 @@ static int check_abs_path_err(const char* buffer) {
 
     // check for GNU extension errors
     if (errno == EACCES || errno == ENOENT) {
+        UACC_PATH_ERR = (char*)malloc(PATH_MAX);
```
Comment (smallinsky) [inline lib/srv/uacc/uacc.h:95]: I'm not C POSIX export but does the `buff != NULL &&(errno == EACCES || errno == ENOENT)` can really happen ?
The input parameter `const char* buffer` in current flow is always result of the`realpath(path, buffer);` call where `realpath` RETURN VALUE  is defined as: [realpath](https://man7.org/linux/man-pages/man3/realpath.3.html#top_of_page)

> If there is no error, realpath() returns a pointer to the resolved_path.
> 
> Otherwise, it returns NULL, the contents of the array
resolved_path are undefined, and [errno](https://man7.org/linux/man-pages/man3/errno.3.html) is set to indicate the
error.

So based on POSIX [errno doc ](https://man7.org/linux/man-pages/man3/errno.3.html) if errno != 0 the `buffer` == NULL

Comment (xacrimon) [reply lib/srv/uacc/uacc.h:95]: This isn’t posix standardized, this is a glibc specific extension that’s sparsely documented . POSIX is a nice standard but a lot of stuff deviates and has subtle differences from it by now. This is one of them.

Comment (xacrimon) [reply lib/srv/uacc/uacc.h:95]: This was mentioned in the top level description of the PR:
`This PR also adds additional diagnostics if realpath decides to fail in such a way that glibc exposes extra debugging info as a non-posix extension`

Comment (xacrimon) [reply lib/srv/uacc/uacc.h:95]: Added comment to the source for any future reader.

Comment (smallinsky) [reply lib/srv/uacc/uacc.h:95]: All right, Thanks for the explanation. Then it LGTM.

**Review by smallinsky — APPROVED** [review]
