### PR TITLE
Attempt to make TestClient_DialHost more reliable

### LINKED ISSUE #32799: `TestClient_DialHost` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/6352583155/job/17255687709#step:6:1179

#### Relevant snippet

```
     client_test.go:465: 
        	Error Trace:	/__w/teleport/teleport/api/client/proxy/transport/transportv1/client_test.go:465
        	            				/__w/teleport/teleport/api/client/proxy/transport/transportv1/client_test.go:494
        	Error:      	Received unexpected error:
        	            	EOF
        	Test:       	TestClient_DialHost/connection_successfully_established_with_agent_forwarding
```

### PR DESCRIPTION
**Pull request by rosstimothy**
Takes inspiration from https://github.com/gravitational/teleport.e/pull/1944 which addressed similar EOF error showing up when driving streams in tests.

From https://pkg.go.dev/google.golang.org/grpc#ClientStream.SendMsg:

> // SendMsg is generally called by generated code. On error, SendMsg aborts
> // the stream. If the error was generated by the client, the status is
> // returned directly; otherwise, io.EOF is returned and the status of
> // the stream may be discovered using RecvMsg.

Closes https://github.com/gravitational/teleport/issues/32799

### CODE REVIEW

File: api/client/proxy/transport/transportv1/client_test.go [hunk 1]
```diff
@@ -360,7 +360,7 @@ func TestClient_DialHost(t *testing.T) {
 				if err := server.Send(&transportv1pb.ProxySSHResponse{
 					Details: nil,
 					Frame:   &transportv1pb.ProxySSHResponse_Ssh{Ssh: &transportv1pb.Frame{Payload: keys[0].Blob}},
-				}); err != nil {
+				}); err != nil && !errors.Is(err, io.EOF) {
```
Comment (espadolini) [inline api/client/proxy/transport/transportv1/client_test.go:363]: We also don't receive after the send here.

**Review by zmb3 — APPROVED** [review]

File: api/client/proxy/transport/transportv1/client_test.go [hunk 2]
```diff
@@ -255,7 +255,7 @@ func TestClient_DialHost(t *testing.T) {
 					if err := server.Send(&transportv1pb.ProxySSHResponse{
 						Details: nil,
 						Frame:   &transportv1pb.ProxySSHResponse_Ssh{Ssh: &transportv1pb.Frame{Payload: bytes.Repeat([]byte{0}, 1001)}},
-					}); err != nil {
+					}); err != nil && !errors.Is(err, io.EOF) {
```
Comment (espadolini) [inline api/client/proxy/transport/transportv1/client_test.go:258]: We don't receive after sending here, are we still good with ignoring EOF?

File: api/client/proxy/transport/transportv1/client_test.go [hunk 3]
```diff
@@ -281,7 +281,7 @@ func TestClient_DialHost(t *testing.T) {
 					if err := server.Send(&transportv1pb.ProxySSHResponse{
 						Details: nil,
 						Frame:   &transportv1pb.ProxySSHResponse_Ssh{Ssh: &transportv1pb.Frame{Payload: f.Ssh.Payload}},
-					}); err != nil {
+					}); err != nil && !errors.Is(err, io.EOF) {
```
Comment (espadolini) [inline api/client/proxy/transport/transportv1/client_test.go:284]: We're not receiving after this.

**Review by espadolini — APPROVED** [review]
