### PR TITLE
Show proper error message when "tsh db env/config" are not supported

### LINKED ISSUE #14782: Incorrect Port and no TLS routing info on tsh db config for MySQL
Expected behavior:

When a connection is using TLS routing the `tsh db config` should give the correct connection information.

Current behavior:

Have a node with TLS routing enabled and only port `443` available and it will recommend to connect via `3036`.  No information is given on the requirement to use `tsh proxy db`.  The `tsh db connect` uses a proxy to connect.

```bash
tsh db config            
Name:      sam-database
Host:      enterprise.example.com
Port:      3036
User:      
Database:  
CA:        /Users/steven/.tsh/keys/enterprise.example.com/cas/tele1c.pem
Cert:      /Users/steven/.tsh/keys/enterprise.example.com/steven-db/tele1c/sam-database-x509.pem
Key:       /Users/steven/.tsh/keys/enterprise.example.com/steven
```

Bug details:
- Teleport version: 10.0.2
- Recreation steps
Deploy a TLS routed Teleport cluster and only expose the web port.  Add a MySQL db.   Use `tsh` to login to the db, get the config `tsh db config` and attempt to connect with a DB GUI like MySQL Workbench.

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #14782
- #14782 

## UX change examples 

`tsh db login`: replaced `tsh db config` with `tsh proxy db` when TLS is enabled
```
$ tsh db login --db-user alice <postgres>
Connection information for database "steve-postgres" has been saved.

You can now connect to it using the following command:

  tsh db connect --db-name=<name> steve-postgres

Or start a local proxy for database GUI clients:

  tsh proxy db --tunnel --db-name=<name> steve-postgres
```

`tsh db config/env` new error message when TLS is enabled
```
$ tsh db config <postgres>
ERROR: "tsh db config" is not supported when TLS routing is enabled on the Teleport Proxy Service.

Please use "tsh db connect" or "tsh proxy db" to connect to the database.
```

`tsh db config/env` new error message when DB protocol is enabled
```
$ tsh db config <mssql>
ERROR: "tsh db config" is not supported for Microsoft SQL Server databases.

Please use "tsh db connect" or "tsh proxy db" to connect to the database.
```

### CODE REVIEW

**Review by EdwardDowling — APPROVED** [review]

File: tool/tsh/db.go [hunk 1]
```diff
@@ -964,3 +1015,40 @@ const (
...
+const (
+	// errDBCmdUnsupportedTLSRouting is the error message printed when some
+	// database subcommands are not supported because TLS routing is enabled.
+	errDBCmdUnsupportedTLSRouting = `"%v" is not supported when TLS routing is enabled on the Teleport Proxy Service.
+
+Please use "tsh db connect" or "tsh proxy db" to connect to the database.`
+
+	// errDBCmdUnsupportedDBProtocol is the error message printed when some
+	// database subcommands are run against unsupported database protocols.
+	errDBCmdUnsupportedDBProtocol = `"%v" is not supported for %v databases.
```
Comment (smallinsky) [inline tool/tsh/db.go:1028]: nit: It is a bit unintuitive  that `err...` prefixed  variable name is used for string where in code seeing `errDBCmdUnsupportedDBProtocol` I will assume that the type of errDBCmdUnsupportedDBProtocol is `error`

**Review by smallinsky — APPROVED** [review]
