### PR TITLE
Change IAM "UnmodifiableEntity" error to a debug log

### LINKED ISSUE #13800: RDS Auto-discovery log entries include errors on protected roles
Expected behavior:

Errors on db service should only include errors that impact the service.

Current behavior:

Each database with auto-discovery receives the sam error regarding `AWSReservedSSO_AdministratorAccess`. This does
not appear to be an actual error and does not impact the expected access behavior.

```
2022-06-23T15:15:34Z INFO [DB:SERVIC] db sam-database matches, creating. services/reconciler.go:148
2022-06-23T15:15:34Z ERRO [IAM]       Failed to auto-configure IAM for Database(Name=sam-postgres, Type=rds, Labels=map[account-id:165258854585 endpoint-type:primary engine:aurora-postgresql engine-version:13.4 region:us-east-1 teleport.dev/origin:cloud]). error:[
ERROR REPORT:
Original Error: trace.aggregate UnmodifiableEntity: Cannot perform the operation on the protected role &#39;AWSReservedSSO_AdministratorAccess_fd5f7f4a0d2b157d&#39; - this role is only modifiable by AWS
	status code: 400, request id: def65274-bdae-4501-a5fa-21058ac11996
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/srv/db/cloud/aws.go:114 github.com/gravitational/teleport/lib/srv/db/cloud.(*awsClient).setupIAM
	/go/src/github.com/gravitational/teleport/lib/srv/db/cloud/iam.go:258 github.com/gravitational/teleport/lib/srv/db/cloud.(*IAM).processTask
	/go/src/github.com/gravitational/teleport/lib/srv/db/cloud/iam.go:122 github.com/gravitational/teleport/lib/srv/db/cloud.(*IAM).Start.func1
	/opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
User Message: UnmodifiableEntity: Cannot perform the operation on the protected role &#39;AWSReservedSSO_AdministratorAccess_fd5f7f4a0d2b157d&#39; - this role is only modifiable by AWS
	status code: 400, request id: def65274-bdae-4501-a5fa-21058ac11996] cloud/iam.go:124
```

Bug details:
- Teleport version: 9.3.7
- Recreation steps
Follow the steps for setting up a RDS db service using the IAM role example.

https://goteleport.com/docs/database-access/guides/rds/

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #13800
- #13800

## UX
#### Before this change
```
2022-07-18T18:04:30Z ERRO [IAM]       Failed to auto-configure IAM for Database(Name=steve-postgres-reader, Type=rds, Labels=map[Env:dev Name:steve-postgres Owner:STeve account-id:xxxxxxx endpoint-type:reader engine:aurora-postgresql engine-version:11.13 region:ca-central-1 teleport.dev/origin:cloud]). error:[
ERROR REPORT:                                                                                                                                                                                          
Original Error: trace.aggregate UnmodifiableEntity: Cannot perform the operation on the protected role &#39;AWSReservedSSO_AdministratorAccess_93acd2fd6bd17005&#39; - this role is only modifiable by AWS
status code: 400, request id: d0905838-f1a1-4793-b7db-5b8e4956e592                                                                                                                                                                                                                                                                                                                                                                    Stack Trace:
```

#### With this change
```
2022-07-18T18:12:34Z DEBU [AWS]       "No permissions to ensure IAM policy: UnmodifiableEntity: Cannot perform the operation on the protected role 'AWSReservedSSO_AdministratorAccess_93acd2fd6bd17005' - this role is only modifiable by AWS\n\tstatus code: 400, request id: 9565c853-1a06-46ce-ad36-d67c5431aeb2." db:steve-postgres cloud/aws.go:109
```
Note that the level is downgraded to `DEBU` so the error will be hidden usually.

## How to reproduce
- Delete existing IAM inline policies added by Database agent
- Use okta to login AWS. Pick the account. Then select "Command line or programmatic access" instead of "Management console"
- Use these credentials to restart the database service.

### CODE REVIEW

**Review by jakule — COMMENTED** [review]
@greedy52 Any chance to add a test or extend some of the existing ones?

**Comment by greedy52** [comment]
> @greedy52 Any chance to add a test or extend some of the existing ones?

Added a new test in `TestAWSIAMNoPermissions`

File: lib/srv/db/cloud/iam.go [hunk 1]
```diff
@@ -217,6 +217,10 @@ func (c *IAM) getPolicyName() (string, error) {
 func (c *IAM) processTask(ctx context.Context, task iamTask) error {
 	configurator, err := c.getAWSConfigurator(ctx, task.database)
 	if err != nil {
+		if trace.Unwrap(err) == credentials.ErrNoValidProvidersFoundInChain {
+			c.log.Debug("No credentials provider. Skipping IAM task for database %v.", task.database.GetName())
```
Comment (smallinsky) [inline lib/srv/db/cloud/iam.go:221]: I Wonder if we should switch to WARN log severity. The `processTask` is triggered only for `RDS` or `Redshift` databases so in case RDS or Redshift  db in database service config or auto dissevered databases  we will silently skip the IMA configuration and add this database as teleport resource. 

Also can we add AWS keyword to the  -> "No AWS credentials provider" string ?

**Review by smallinsky — APPROVED** [review]

File: lib/srv/db/cloud/iam.go (hunk 1 above)
Comment (greedy52) [reply lib/srv/db/cloud/iam.go:221]: When there are no AWS credentials, databases cannot be auto-discovered in the first place. So this would only happen for manually configured RDS or Redshift. That being said, in that case, a WARN is more appropriate. Will update and add the "AWS" part.

**Review by jakule — APPROVED** [review]
