### PR TITLE
Make system roles case-insensitive in provision tokens

### LINKED ISSUE #30768: Make token roles case insensitive or improve error message
The values in the `roles` array must be capitalized (`Node`, `App` and so on) which feels unusual for our configuration.

If you attempt to make [an IAM token](https://goteleport.com/docs/agents/join-services-to-your-cluster/aws-iam/#step-24-create-the-aws-joining-token) with the role `app`, you get "ERROR: role app is not registered".

Instead, we should either make the roles case insensitive or improve the error message. If we detect that the error is due to the role not being registered, we should output an additional note saying that the roles are case sensitive. Or perhaps just list all available roles.

### PR DESCRIPTION
**Pull request by atburke**
This change makes system roles set in a provision token case-insensitive.

Resolves #30768.

### CODE REVIEW

File: api/types/provisioning.go [hunk 1]
```diff
@@ -324,7 +326,12 @@ func (p *ProvisionTokenV2) GetVersion() string {
 // that will be granted to the user of the token
 // in the crendentials
 func (p *ProvisionTokenV2) GetRoles() SystemRoles {
-	return p.Spec.Roles
+	// Ensure that roles are case-insensitive.
+	roles := make(SystemRoles, 0, len(p.Spec.Roles))
+	for _, role := range p.Spec.Roles {
+		roles = append(roles, normalizedSystemRole(string(role)))
+	}
+	return roles
```
Comment (AntonAM) [inline api/types/provisioning.go:334]:
```suggestion
	return normalizedSystemRoles(SystemRoles(p.Spec.Roles).StringSlice())
```

File: api/types/system_role.go [hunk 2]
```diff
@@ -105,6 +105,21 @@ var roleMappings = map[string]SystemRole{
 	"mdm":             RoleMDM,
 }
 
+func normalizedSystemRole(s string) SystemRole {
+	if role, ok := roleMappings[strings.ToLower(strings.TrimSpace(s))]; ok {
+		return role
+	}
+	return SystemRole(s)
```
Comment (AntonAM) [inline api/types/system_role.go:112]: As I understand that's just not to have an error for ease of usage and idea is it will error out upper?

**Review by AntonAM — APPROVED** [review]

**Comment by zmb3** [comment]
Can we reuse some of the parsing code added in #9756? This seems duplicative

**Review by jakule — APPROVED** [review]
