### PR TITLE
tsh/tctl: Improve error message when using --identity without a proxy or auth server

### LINKED ISSUE #19293: improve error message when using tsh ssh with identity file
```
$ tctl auth sign --user=foo --format=file --out=key.pem
$ tsh --identity=key.pem ssh user@node
ERROR: missing parameter hostname
```

In this case, it's not clear _what_ is missing the hostname parameter.

Note: the same happens with `tsh --identity=key.pem ls`.

The cause of the issue is that there is no tsh profile and no `--proxy` flag, so `tsh` doesn't know what endpoint it is supposed to connect to.

Consider checking for an empty proxy value and showing a clearer error. Something like:

```
ERROR: missing proxy address. Specify --proxy or login with tsh login.
```

### PR DESCRIPTION
**Pull request by jof**
Fixes #19293
The error message "missing parameter hostname" wasn't very clear what hostname was missing. Fail faster further up the stack and print a better error message explaining what is happening.

This applies some checks aroung argument parsing while also adding some
belt-and-suspenders validation into `NewClientStoreFromIdentityFile`

Before:
```
% ~/src/teleport/build/tsh --identity=key.pem --insecure ssh root@localhost
ERROR: missing parameter hostname
```

After:
```
% ~/src/teleport/build/tsh --identity=key.pem--insecure ssh root@localhost
ERROR: missing proxy address. Specify --proxy or login with `tsh login`
```

### CODE REVIEW

**Comment by zmb3** [comment]
Seems reasonable to me.

Can you include a before/after example in the PR description so we can see the difference in behavior?

**Review by wadells — APPROVED** [review]
LGTM, but I defer to the teleport reviewers who more regularly work in this repo.

**Review by sfreiberg — APPROVED** [review]

**Review by hatched — APPROVED** [review]

**Comment by jof** [comment]
Some testing errors and more reading have led to me find that I should really be putting this conditional elsewhere.

New commit incoming...

File: lib/client/identityfile/identity.go [hunk 1]
```diff
@@ -614,10 +614,15 @@ func KeyFromIdentityFile(identityPath, proxyHost, clusterName string) (*client.K
 // is also added to its profile store with the limited profile data available
 // in the identity file.
 //
-// Since identity files do not save a proxy address, proxyAddr must be provided
-// to fill in this data gap. clusterName can also be provided to aim the key at
-// a leaf cluster rather than the default root cluster.
+// proxyAddr: Since identity files do not save a proxy address, a host:port-like
```
Comment (zmb3) [inline lib/client/identityfile/identity.go:617]: This `arg: description` format is not super common. I would just refer to the argument in plain sentences.

Maybe something like this:

```
// Use [proxyAddr] to specify the address of the proxy.
// This is necessary because identity files do not store
// the proxy address. Additionally, the optional [clusterName]
// argument can be used to target a leaf cluster rather than
// the default root cluster.
```

File: lib/client/identityfile/identity.go [hunk 2]
```diff
@@ -614,10 +614,15 @@ func KeyFromIdentityFile(identityPath, proxyHost, clusterName string) (*client.K
...
+// proxyAddr must be provided to fill in this data gap.
+//
+// clusterName: may optionally be provided to aim the key at a leaf cluster
+// rather than the default root cluster.
 func NewClientStoreFromIdentityFile(identityFile, proxyAddr, clusterName string) (*client.Store, error) {
+	if proxyAddr == "" {
+		return nil, trace.BadParameter("missing proxy address. Specify --proxy or login with `tsh login`")
```
Comment (zmb3) [inline lib/client/identityfile/identity.go:624]: I'm not sure it makes sense to mention specific CLI flags in an error message this deep. This function is not required to be called from a CLI, so we may get confusing error messages if this is mistakenly raised in the wrong context.

Your previous implementation was better IMO, because you mentioned the `--proxy` flag in a func that accepted a struct with command line flags.

File: lib/client/identityfile/identity.go (hunk 1 above)
Comment (jof) [reply lib/client/identityfile/identity.go:617]: Seems super reasonable. I'll ammend with a format like you suggest.

File: lib/client/identityfile/identity.go (hunk 2 above)
Comment (jof) [reply lib/client/identityfile/identity.go:624]: This one is a bit trickier to resolve, as it seems like there are testing and other usages of tool/tsh/tsh.go/`makeClient` which rely on `(CLIConf)cf.Proxy` being unset (and I guess it gets discovered/set in other ways in those contexts?), so putting this check up in `makeClient` also seems like it'll impact other non-CLI uses of tsh.

At least my thinking here is that only in this `NewClientStoreFromIdentityFile()` context are we in this one context we care about: building a tsh client up from just an identity file.

However, maybe you are right that there are other non-CLI contexts that this tsh Client could be getting built up from an identity file.
Is there some elegant way that we could detect the CLI-usage context and build up the ideal error message (but still here)?

Comment (jof) [reply lib/client/identityfile/identity.go:623]: Maybe a better place for this check is up inside of `Run()` where most of the argument parsing is happening?

I would check up there, but I'm not confident about creating a conditional that could cover all the cases that might eventually try and construct the client from an identity file.

Intuitively, it make sense to put something like `if cf.IdentityFileIn && !(cf.Proxy)` up there, but I wasn't confident about how proxy discovery from the `~/.tsh/*` might interact with this.

Might it be possible that somebody has logged into Teleport, has valid proxy addresses via `~/.tsh/current-profile`, but then also calls `tsh` with an Identity file, such that they're not passing a proxy on the CLI, but they have a proxy address that could be discovered via the local state to use with the identity file?

File: lib/client/identityfile/identity.go [hunk 3]
```diff
@@ -614,10 +614,14 @@ func KeyFromIdentityFile(identityPath, proxyHost, clusterName string) (*client.K
...
-// Since identity files do not save a proxy address, proxyAddr must be provided
-// to fill in this data gap. clusterName can also be provided to aim the key at
-// a leaf cluster rather than the default root cluster.
+// Use [proxyAddr] to specify the host:port-like address of the proxy.
+// This is necessary because identity files do not store the proxy address.
+// Additionally, the [clusterName] argument can ve used to target a leaf cluster
+// rather than the default root cluster.
 func NewClientStoreFromIdentityFile(identityFile, proxyAddr, clusterName string) (*client.Store, error) {
+	if proxyAddr == "" {
+		return nil, trace.BadParameter("missing proxyAddr loading identityFile. Login, configure a proxy address, or pass --proxy on the command line.")
```
Comment (zmb3) [inline lib/client/identityfile/identity.go:623]:
```suggestion
		return nil, trace.BadParameter("missing proxy address loading identityFile. Log in, configure a proxy address, or pass --proxy on the command line.")
```

- Since the user will see this message, use proper words and not variable names
- nit: login is a noun, I think you mean to say "log in"

**Review by zmb3 — APPROVED** [review]
approved with additional suggestions

File: lib/client/identityfile/identity.go (hunk 3 above)
Comment (r0mant) [inline lib/client/identityfile/identity.go:623]: Is the same function called when using `tctl` with the identity file? Because if I think the error message might be incorrect since tctl's flag is `--auth-server`, not `--proxy`.

**Review by r0mant — CHANGES_REQUESTED** [review]

File: lib/client/identityfile/identity.go (hunk 3 above)
Comment (jof) [reply lib/client/identityfile/identity.go:623]: Excellent feedback. Integrating...

Comment (jof) [reply lib/client/identityfile/identity.go:623]: What I'm finding is that when called with an identity file but no proxy, `tctl` calls down to this `NewClientStoreFromIdentityFile` function with an empty (`""`) `proxyAddr`, which `utils.Host()` fails to parse with an even-more-confusing error message to the end user.

I was originally thinking of putting this check in here only, but since it really seems like an argument-parsing requirement, I moved the conditional check up to `Run()` where the rest of the command line argument parsing is happening.

But, then I'm also left thinking that this function doesn't really work with an empty `proxyAddr`, and opted to leave this check in here to leave a better error message in case something calls this with a useless/non-Host-ey `proxyAddr` value.

Comment (r0mant) [reply lib/client/identityfile/identity.go]: Yeah, I get that, so what kind of error do you get when you execute `tctl` with only `--identity` flag?

Comment (jof) [reply lib/client/identityfile/identity.go]: The before and after is in the PR description and the bug that prompted this.

If we only call `tsh` with `--identity`, it prints this confusing error message (since the real error is that there is no proxy set, and it is trying to parse `""` as a hostname):

```
% ~/src/teleport/build/tsh --identity=key.pem --insecure ssh root@localhost
ERROR: missing parameter hostname
```

Comment (jof) [reply lib/client/identityfile/identity.go]: Ah, I see what you mean now -- I was glossing over `tctl` vs. `tsh`

I still get the same confusing error message, though with a different call stack that also goes via `NewClientStoreFromIdentityFile`:
```
% ~/src/teleport/build/tctl  --identity=~/teleport/config/jof.pem users ls
ERROR: missing parameter hostname
```

I suppose I may as well try and address this for `tctl` as well as `tsh`.

File: lib/client/identityfile/identity.go (hunk 2 above)
Comment (jof) [reply lib/client/identityfile/identity.go]: After testing some more cases with local config, this seems even more straightforward than I had initially thought.

I've decided to go with both some conditional checks for this condition when arguments are parsed as well as a check down in `NewClientStoreFromIdentityFile` to give a better error message if `proxyAddr` is empty.

File: lib/client/identityfile/identity.go [hunk 4]
```diff
@@ -614,10 +614,14 @@ func KeyFromIdentityFile(identityPath, proxyHost, clusterName string) (*client.K
...
-// Since identity files do not save a proxy address, proxyAddr must be provided
-// to fill in this data gap. clusterName can also be provided to aim the key at
-// a leaf cluster rather than the default root cluster.
+// Use [proxyAddr] to specify the host:port-like address of the proxy.
+// This is necessary because identity files do not store the proxy address.
+// Additionally, the [clusterName] argument can ve used to target a leaf cluster
+// rather than the default root cluster.
 func NewClientStoreFromIdentityFile(identityFile, proxyAddr, clusterName string) (*client.Store, error) {
+	if proxyAddr == "" {
+		return nil, trace.BadParameter("Missing a Proxy address when loading an Identity File.")
```
Comment (r0mant) [inline lib/client/identityfile/identity.go:623]: Nit: Do not capitalize errors for better embedding (from Go style guide).
```suggestion
		return nil, trace.BadParameter("missing a proxy address when loading an identity file")
```

**Review by r0mant — APPROVED** [review]
