### PR TITLE
fix delete event filtering in fanout

### LINKED ISSUE #3806: Auth Server with cache.enabled does not emit deleted access request events
### Description

**What happened**:

While working on https://github.com/gravitational/teleport-plugins I updated the vendored Teleport version. After this, tests involving access request expiration started failing. I investigated the problem and found that 4e9eed9ac0e38d177a49877ca5c3944a29c9aeba commit brought the change. This commit affects the cache behavior so I tried to turn off the cache and then everything worked as before.

After 4e9eed9ac0e38d177a49877ca5c3944a29c9aeba with cache turned on I don't get `OpDelete` events anymore. The reason is that new fanout implementation doesn't treat `OpDelete` events as 'filterable'. Probably it's right but then behavior must be unified whether cache is enabled or disabled.

**What you expected to happen**:

I expect that it must either work as it worked before, or, with cache disabled, it must ignore `OpDelete` events too.

**How to reproduce it (as minimally and precisely as possible)**:

Start new watcher with `WatchEvents` grpc method with filter on pending requests.

cc @fspmarshall

### PR DESCRIPTION
**Pull request by fspmarshall**
The initial implementation of event fanout logic for the cache was incorrectly applying filters to delete events.  Because the deleted resource cannot be inspected during a delete event, it isn't possible to determine if a filter should match.  Instead of matching all delete events and letting the caller determine their relevance (which is how teleport handles this problem elsewhere) the fanout logic was never matching delete events.

Fixes #3806

### CODE REVIEW

File: lib/services/events.go [hunk 1]
```diff
@@ -66,9 +66,10 @@ func (kind WatchKind) Matches(e Event) (bool, error) {
 		return false, nil
 	}
 	if len(kind.Filter) > 0 {
-		// no filters currently match delete events
+		// we don't have a good model for filtering non-put events,
+		// so just match all of them and let the caller sort it out.
 		if e.Type != backend.OpPut {
-			return false, nil
+			return true, nil
 		}
```
Comment (awly) [inline lib/services/events.go:73]: optional: `if len(kind.Filter) > 0 && e.Type == backend.OpPut { ...`

**Review by awly — COMMENTED** [review]
LGTM
If possible, please also write a unit test for this whole method.

**Review by awly — APPROVED** [review]
