### PR TITLE
Fix web sftp breaking with proxy protocol on unset listen addr

### LINKED ISSUE #60709: Cannot download or upload files to SSH servers via web browser
Expected behavior:
I can download or upload files to SSH servers

Current behavior:
The Teleport web page displays `client source and destination addresses should be valid same TCP version non-nil IP addresses` and the file is not downloaded or uploaded.

Bug details:
- Teleport version: v18.2.10
- Recreation steps:
1. Log in to Teleport via web browser
2. Access an SSH server
3. Try to download or upload file via the buttons on the top-left corner of the web console
- Debug logs
This seems to print on the Teleport server when I try to download a file.
```
Oct 29 01:20:30 teleport teleport[421231]: 2025-10-29T01:20:30.399Z DEBU [CLIENT]    Skipping connection to the local ssh-agent. client/keyagent.go:145
Oct 29 01:20:30 teleport teleport[421231]: 2025-10-29T01:20:30.400Z DEBU [PROXY:SER] Initiating dial request cluster:main dial_params:from: "<user-ip>:49686" to: "<ssh-server-ip>:3022" reversetunnel/localsite.go:314
Oct 29 01:20:30 teleport teleport[421231]: 2025-10-29T01:20:30.401Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer proxy/proxy.go:184
Oct 29 01:20:30 teleport teleport[421231]: 2025-10-29T01:20:30.401Z DEBU [PROXY:SER] Succeeded dialing cluster:main dial_params:from: "<user-ip>:49686" to: "<ssh-server-ip>:3022" reversetunnel/localsite.go:320
```

Let me know if more information is needed.

### PR DESCRIPTION
**Pull request by atburke**
This change fixes a bug where file uploads/downloads in the web ui would fail if a) proxy protocol was active and b) `proxy_service.web_listen_addr` was unspecified. This was caused by the dialer in lib/web/files.go using the config file value directly as the client destination address, which the proxy header signer would reject as not a valid ip address if empty. This is fixed by giving the web handler the actual address of the web listener, instead of just the config value.

Fixes #60709.

Changelog: Fixed web upload/download failure behind load balancers when web listen address is unspecified

Test plan:
- [x] Create a cluster with a node and web listen addr unset (public addr is fine). Put the cluster behind a load balancer. Open a web session to the node and verify that file uploads/downloads work correctly.

### CODE REVIEW

**Comment by atburke** [comment]
Friendly ping @okraport @strideynet

**Comment by strideynet** [comment]
> Friendly ping @okraport @strideynet

Apologies - I was waiting on the "test plan" box to be ticked - but I'm assuming you've already completed that. I'll take a look now.

**Review by strideynet — APPROVED** [review]

**Review by okraport — APPROVED** [review]
Sorry, LGTM!

**Comment by rosstimothy** [comment]
@atburke can you please clarify that you've completed the manual test plan before merging?

**Review by rosstimothy — COMMENTED** [review]
Is it possible to add a unit test that covers this flow?

**Comment by atburke** [comment]
> Is it possible to add a unit test that covers this flow?

Not easily, the web config in `initProxyEndpoint()` we'd want to check is entirely local to the function.

File: integration/integration_test.go [hunk 1]
```diff
@@ -8407,6 +8408,66 @@ func testSFTP(t *testing.T, suite *integrationTestSuite) {
...
+
+			webClient, err := teleport.NewWebClient(helpers.ClientConfig{
+				Login:    suite.Me.Username,
+				Password: password,
+				Cluster:  helpers.Site,
+				Host:     Loopback,
+				Port:     lbFrontend.Port(0),
+			})
+			require.NoError(t, err)
+
```
Comment (rosstimothy) [inline integration/integration_test.go:8467]: I think we should add a check to ensure that the SSH instance is up running and present in the inventory prior to attempting connections to reduce flakiness.

```suggestion
	require.NoError(t, instance.WaitForNodeCount(t.Context(), helpers.Site, 1))
```

**Review by rosstimothy — APPROVED** [review]
Thanks for adding the test @atburke!
