### PR TITLE
Fix the CRL distribution point in Windows certs

### LINKED ISSUE #9292: Windows Smartcard Certs are looking in the wrong location for CRLs
### Description

**What happened**:

Attempting to log in to a Windows desktop shows the following error:

image

This bug was introduced in #9152, where we got rid of the `ldapPath` logic. We're mistakenly generating certs with a CRL that is missing the cluster name.

Correct CRL location: `CN=myclustername,CN=Teleport,CN=CDP,CN=Public Key Services,CN=Services,CN=Configuration,DC=example,DC=com`
Currently published location in certs: `CN=Teleport,CN=CDP,CN=Public Key Services,CN=Services,CN=Configuration,DC=example,DC=com`

### PR DESCRIPTION
**Pull request by zmb3**
A bug introduced in #9152 resulted in us publishing a CRL distribution
point to LDAP which was different than the one encoded in the certs.

Refactor the logic for generating these DNs into shared methods
and add test coverage that verifies the certs meet Windows requirements.

Fixes #9292

### CODE REVIEW

File: lib/srv/desktop/windows_server.go [hunk 1]
```diff
@@ -828,7 +840,7 @@ func (s *WindowsService) generateCredentials(ctx context.Context, username, doma
 	// CRLs in it. Each service can also handle RDP connections for a different
 	// domain, with the assumption that some other windows_desktop_service
 	// published a CRL there.
-	crlDN := "CN=Teleport,CN=CDP,CN=Public Key Services,CN=Services,CN=Configuration," + s.cfg.LDAPConfig.domainDN()
```
Comment (zmb3) [inline lib/srv/desktop/windows_server.go:831]: FYI: the actual bug was here - we weren't adding the cluster name to the DN used in the certificate.

The rest of the changes are just cleanup and tests to help make sure this doesn't happen again.

**Review by r0mant — APPROVED** [review]

**Review by ibeckermayer — APPROVED** [review]

**Review by jakule — APPROVED** [review]
