### PR TITLE
Fix an issue `tsh db connect <mongodb>` does not give reason on connection errors

### LINKED ISSUE #34093: `tsh db connect <mongodb>` gives `127.0.0.1:xxxx closed` error without any context
Expected behavior:
`tsh db connect <mongodb>` should provide proper error messages why it fails to connect

Current behavior:
```
$ tsh db connect --db-user aaaa --db-name test self-hosted-mongo 
Current Mongosh Log ID:	6541507f0c646ca237924f55
Connecting to:		mongodb://localhost:62069/test?serverSelectionTimeoutMS=5000&directConnection=true&tls=true&tlsCertificateKeyFile=%2FUsers%2Fstevehuang%2F.tsh%2Fkeys%2Fteleport.dev.aws.stevexin.me%2FSTeve-db%2Fteleport.dev.aws.stevexin.me%2Fself-hosted-mongo-x509.pem&tlsCAFile=%2FUsers%2Fstevehuang%2F.tsh%2Fkeys%2Fteleport.dev.aws.stevexin.me%2Fcas%2Fteleport.dev.aws.stevexin.me.pem&appName=mongosh+2.0.1
MongoServerSelectionError: connection <monitor> to 127.0.0.1:62069 closed
ERROR: exit status 1
```

Bug details:
- Teleport version: v14
- `mongosh` version: 2.0.1
- Recreation steps:
   - A self-hosted MongoDB 
   - `tsh db connect` with a `--db-user` that doesn't exist.

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #34093 

Before fix:
```bash
$ tsh db connect --db-user not-steve --db-name test self-hosted-mongo-auto
Current Mongosh Log ID:	654956105af843c72720ee2a
Connecting to:		mongodb://localhost:65358/test?serverSelectionTimeoutMS=5000&directConnection=true&tls=true&tlsCertificateKeyFile=%2FUsers%2Fstevehuang%2F.tsh%2Fkeys%2Fteleport.dev.aws.stevexin.me%2FSTeve-db%2Fteleport.dev.aws.stevexin.me%2Fself-hosted-mongo-auto-x509.pem&tlsCAFile=%2FUsers%2Fstevehuang%2F.tsh%2Fkeys%2Fteleport.dev.aws.stevexin.me%2Fcas%2Fteleport.dev.aws.stevexin.me.pem&appName=mongosh+2.0.2
MongoServerSelectionError: connection <monitor> to 127.0.0.1:65358 closed

```
After fix:
```bash
$ tsh db connect --db-user not-steve --db-name test self-hosted-mongo-auto
Current Mongosh Log ID:	654955e278da97e72cc46f5e
Connecting to:		mongodb://localhost:65322/test?serverSelectionTimeoutMS=5000&directConnection=true&tls=true&tlsCertificateKeyFile=%2FUsers%2Fstevehuang%2F.tsh%2Fkeys%2Fteleport.dev.aws.stevexin.me%2FSTeve-db%2Fteleport.dev.aws.stevexin.me%2Fself-hosted-mongo-auto-x509.pem&tlsCAFile=%2FUsers%2Fstevehuang%2F.tsh%2Fkeys%2Fteleport.dev.aws.stevexin.me%2Fcas%2Fteleport.dev.aws.stevexin.me.pem&appName=mongosh+2.0.2
MongoServerSelectionError: error authorizing database access
	please use your Teleport username ("STeve") to connect instead of "not-steve"

```

changelog: Fix an issue `tsh db connect <mongodb>` does not give reason on connection errors

### CODE REVIEW

File: lib/srv/db/mongodb/engine.go [hunk 1]
```diff
@@ -269,7 +273,35 @@ func (e *Engine) checkClientMessage(sessionCtx *common.Session, message protocol
...
+}
+
 func (e *Engine) replyError(clientConn net.Conn, replyTo protocol.Message, err error) {
+	// If an error happens during server connection, wait for a client message
+	// before replying to ensure the client can interpret the reply.
+	// The first message is usually the isMaster hello message.
+	if replyTo == nil && !e.serverConnected.Load() {
+		waitChan := make(chan protocol.Message, 1)
+		go func() {
+			waitChan <- e.waitForAnyClientMessage(clientConn)
```
Comment (bl-nero) [inline lib/srv/db/mongodb/engine.go:291]: If I correctly understand what's happening here, this "side event loop" will compete with the main loop inside `HandleConnection`. Even though you check the `serverConnected` field, there still is a scenario in which first, the check is performed, then `serverConnected` is set to `true`, and this line races with `HandleConnection`. Since the `protocol.ReadMessage` function is not thread-safe, this may result in an undefined behavior.

I know that this scenario may be ruled out by an assumption that `SendError` will not be called concurrently with `HandleConnection`, but then, using an atomic bool sends a different message.

I see two solutions. Perhaps it would be better to implement this part inside `HandleConnection` itself: read messages through a goroutine and a channel, `select` over that channel and another one that injects error messages and/or timeouts. And instead of waiting for a client message here, just inject an expected error to the queue and let `HandleConnection` deal with it.

Another solution is to ignore the problem (if `SendError` is not supposed to be called concurrently), but then, let's not even use the atomic boolean flag, since it just confuses the reader and conveys a wrong message about type safety assumptions; we could also explicitly state that the `Engine` methods should not expected to be type-safe.

Comment (greedy52) [reply lib/srv/db/mongodb/engine.go:292]: It's safe to assume that `SendError` is only called when `HandleConnection` fails. I've added a comment to `replyError`. As for `serverConnected`, I used atomic as I thought I would need it for the UT. Turned out it was not needed so downgraded to a regular bool.

Thanks.

**Review by bl-nero — APPROVED** [review]

**Review by smallinsky — APPROVED** [review]
