### PR TITLE
Fix forwarding of impersonated headers for `kubectl exec/portforward`

### LINKED ISSUE #21088: Kubernetes impersonation not working through Teleport for exec
Expected behavior:
Teleport will work with the `--as` flag with `kubectl exec` commands.

Current behavior:
Teleport errors out from `kubectl exec` commands with the error `please select a user to impersonate, refusing to select a user due to several kubernetes_users set up for this user`

Bug details:
- Teleport version: 11.2.1

~~~
paulschisa:~$ tsh status
> Profile URL:        https://root.teleport-cse.com:443
  Logged in as:       pschisa
  Cluster:            root.teleport-cse.com
  Roles:              access, editor, windows-desktop-admins
  Logins:             ec2-user, ubuntu, root, -teleport-internal-join
  Kubernetes:         enabled
  Kubernetes cluster: "demo-k8s-cluster"
  Kubernetes users:   evan, testtest
  Kubernetes groups:  impersonate, system:masters
  Valid until:        2023-02-02 00:28:35 -0500 EST [valid for 11h3m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy

^[[A%
paulschisa:~$ tsh kube ls
Kube Cluster Name Labels Selected
----------------- ------ --------
demo-k8s-cluster         *

paulschisa:~$ kubectl --as=evan get po -n teleport-agent
NAME               READY   STATUS    RESTARTS   AGE
teleport-agent-0   1/1     Running   0          28d
paulschisa:~$ kubectl --as=evan exec teleport-agent-0 -n teleport-agent -- bash
error: Internal error occurred: error executing command in container: error sending request: Post "https://kube.teleport.cluster.local/api/v1/namespaces/teleport-agent/pods/teleport-agent-0/exec?command=bash&container=teleport&stderr=true&stdout=true": please select a user to impersonate, refusing to select a user due to several kubernetes_users set up for this user
~~~

### PR DESCRIPTION
**Pull request by tigrato**
This PR fixes the impersonation headers propagation when using the SPDY roundtrip. SPDY roundtrip creates a new HTTP request and loses the impersonation headers received from the client. When this happens for users that define multiple `kubernetes_users`, the requests are denied because Teleport forces you to select a user.

With the changes introduced, we keep the headers received from the client.

Fixes #21088

### CODE REVIEW

File: lib/kube/proxy/roundtrip.go [hunk 1]
```diff
@@ -152,9 +157,12 @@ func (s *SpdyRoundTripper) dial(url *url.URL) (net.Conn, error) {
 // connection.
 func (s *SpdyRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
 	header := utilnet.CloneHeader(req.Header)
-	header.Add(httpstream.HeaderConnection, httpstream.HeaderUpgrade)
-	header.Add(httpstream.HeaderUpgrade, streamspdy.HeaderSpdy31)
-
+	// copyImpersonationHeaders copies the headers from the original request to the new
+	// request headers. This is necessary to forward the original user's impersonation
+	// when multiple kubernetes_users are available.
+	copyImpersonationHeaders(header, s.originalHeaders)
```
Comment (smallinsky) [inline lib/kube/proxy/roundtrip.go:163]: Can we cover this in UT ?

Comment (tigrato) [reply lib/kube/proxy/roundtrip.go:163]: Added in [f83a1eb](https://github.com/gravitational/teleport/pull/21102/commits/f83a1eb9fcfa363c5726fe7c627a891a7bb367e6)

**Review by smallinsky — APPROVED** [review]

**Review by EdwardDowling — APPROVED** [review]
