### PR TITLE
[Web] Fix minor sidenav-related UX bugs

### LINKED ISSUE #49210: Nav Sheet resets when clicking the "Keep Expanded" button
### User scenario: 
I'm looking at the resources view and hover over the Policy section of the left nav bar (or any other section besides "Resources") to open the Policy nav sheet. While viewing the sheet, I see the arrow button ("Keep Expanded") in the upper right corner of the nav sheet, and I click on it.

### Expected behavior:
The nav will stay open and the page will reflow to make space for it. The nav sheet I'm currently viewing (Policy) will stay open as long as my mouse is still hovering over the sheet, such that the only changes to the page are 1) the direction of the arrow button and 2) the reflow in the main part of the page.

### Current behavior:
Everything on the page changes. The nav sheet resets to the current page's section, even though my mouse hasn't stopped hovering over the current sheet. 

(I'm guessing that something about either the click event or the page reflow is simulating a mouseout event, since we reset the nav sheet when the user moves their mouse away from the nav.)

See video of the behavior here:
https://github.com/user-attachments/assets/8380487d-77c6-4c6d-adc3-53c508e19f81

Bug details:
- Teleport version: 17.0.1
- Recreation steps: Open any page with the nav in the default-to-collapsed nav state, hover over a _different_ section of the nav, and click the "Keep Expanded" button.
- Debug logs: N/A

### LINKED ISSUE #49212: Cmd+Click doesn't work to open some nav items in new tab
Expected behavior:

When `cmd+click`ing an item in the sidenav, it should be opened in a new tab.

Current behavior:

`Cmd+click`ing only works with nav items in the "Resources" section, other items are opened in the current tab.

Bug details:
- Teleport version: `v17.0.0`

### PR DESCRIPTION
**Pull request by rudream**
## Purpose

This PR resolves https://github.com/gravitational/teleport/issues/49212
This PR resolves https://github.com/gravitational/teleport/issues/49210

This PR fixes two minor UX bugs in the side navigation.

### CODE REVIEW

File: web/packages/teleport/src/Navigation/SideNavigation/Navigation.tsx [hunk 1]
```diff
@@ -350,31 +350,30 @@ export function Navigation() {
...
       handleSetExpandedSection(currentPageSection);
     } else {
       collapseDrawer(false);
     }
   }, [currentPageSection]);
 
-  // Handler for navigation actions
-  const handleNavigation = useCallback(
-    (route: string) => {
-      history.push(route);
```
Comment (rudream) [inline web/packages/teleport/src/Navigation/SideNavigation/Navigation.tsx:362]: This `history.push` was unnecessary since `SubsectionItem`s are already `NavLink`s, meaning they already have native navigation functionality

File: web/packages/teleport/src/Navigation/SideNavigation/Navigation.tsx [hunk 2]
```diff
@@ -350,31 +350,30 @@ export function Navigation() {
 
     // If the page is not part of the sidenav, such as Account Settings, curentPageSection will be undefined, and the drawer should be collapsed.
     if (currentPageSection) {
+      // If there is already an expanded section set, don't change it.
+      if (!!debouncedSection) {
```
Comment (ryanclark) [inline web/packages/teleport/src/Navigation/SideNavigation/Navigation.tsx:354]:
```suggestion
      if (debouncedSection) {
```

**Review by ryanclark — APPROVED** [review]

**Review by gzdunek — APPROVED** [review]
