### PR TITLE
fix access request test cache sync

### LINKED ISSUE #38878: `TestListAccessRequests` flakiness
#### Link(s) to logs

https://github.com/gravitational/teleport/actions/runs/8115646584/job/22183938205

#### Relevant snippet

```
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-([]string) (len=400) {
        	            	+([]string) (len=399) {
        	            	  (string) (len=36) "018dfb4e-7b36-70a7-a5dd-c2c8a6eb004b",
        	            	@@ -399,4 +399,3 @@
        	            	  (string) (len=36) "018dfb4e-94f0-7d43-a14c-547e42e9061d",
        	            	- (string) (len=36) "018dfb4e-950d-7bc0-9928-3f13c9430cc0",
        	            	- (string) (len=36) "018dfb4e-951c-79c2-829b-50a2fc02d41a"
        	            	+ (string) (len=36) "018dfb4e-950d-7bc0-9928-3f13c9430cc0"
        	            	 }
        	Test:       	TestListAccessRequests
```

### PR DESCRIPTION
**Pull request by fspmarshall**
https://github.com/gravitational/teleport/pull/38633 introduced a new access request cache that is always enabled on auth, but one of the tests wasn't properly waiting for changes to propagate to the cache, leading to flakiness.  This PR adds a helper for waiting on access request change propagation and uses it to fix the new test that was flaky.

Note: I looked through the various existing access request tests in `lib/auth` to see if they needed to be updated as well, but it seems like our existing coverage in `lib/auth` was limited to single-request lookups, which are always routed to the real backend.

Fixes https://github.com/gravitational/teleport/issues/38878

### CODE REVIEW

File: lib/auth/access_request_test.go [hunk 1]
```diff
@@ -196,6 +196,43 @@ func TestAccessRequest(t *testing.T) {
...
+			if nextKey == "" {
+				break Paginate
+			}
+		}
+
+		if condition(reqs) {
+			return
+		}
+
+		select {
```
Comment (zmb3) [inline lib/auth/access_request_test.go:228]: Do we need a select here? Can we just check `if time.Since(start) > 30 * time.Second`?

**Review by zmb3 — APPROVED** [review]

**Review by tigrato — APPROVED** [review]

**Comment by nklaassen** [comment]
@fspmarshall do you mind backporting this to the relevant branches? I just hit a flake off branch/v15 https://github.com/gravitational/teleport/actions/runs/8604695481/job/23579352396
