### PR TITLE
Auto page size adjustment for GetUsers

### LINKED ISSUE #60933: Proper users pagination support in FE and tctl
#### Expected behavior:

FE UI, tctl should support listing Users with large  number of traits/ roles. 

 
#### Current behavior:
Have many users with 1-2k of traits

Both UI, tctl list users flow is broken: 

UI: 
Image

tctl:
```bash
tctl  get users
ERROR: grpc: received message larger than max (74256758 vs. 4194304)
```

### PR DESCRIPTION
**Pull request by okraport**
It is possible that the default page size will still exceed grpc
limits when user objects are large enough. This change will
use the auto page size adjustment in this case to attempt to recover
gracefully.

Fixes: #60933

### CODE REVIEW

**Comment by okraport** [comment]
I used a quick script to copy an existing user and create enough users to repro this:
```python
import yaml
import random
import string
import argparse

def generate_username():
    return "user-" + ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))

def generate_traits(n):
    traits = {}
    for i in range(n):
        key = f"trait{i+1}"
        value = [''.join(random.choices(string.ascii_letters, k=64))]
        traits[key] = value
    return traits

parser = argparse.ArgumentParser(description="Generate Teleport users YAML bootstrap file.")
parser.add_argument("input_file", help="user yaml to copy")
parser.add_argument("output_file", help="bootstrap file out")
parser.add_argument("-n", "--num_users", type=int, default=600, help="Number of users to generate")
parser.add_argument("-t", "--num_traits", type=int, default=500, help="Number of traits per user")

args = parser.parse_args()

with open(args.input_file, "r") as f:
    template = yaml.safe_load(f)

with open(args.output_file, "w") as f:
    yaml.dump(template, f, sort_keys=False)
    f.write("---\n")

    for i in range(args.num_users):
        user_copy = template.copy()
        user_copy['metadata']['name'] = generate_username()
        user_copy['spec']['traits'] = generate_traits(args.num_traits)

        yaml.dump(user_copy, f, sort_keys=False)
        f.write("---\n")
```

**Comment by okraport** [comment]
Manual testing:
* Create 600 users with 600 traits each 64 characters each. I have found this was enough 
Before:
Screenshot 2025-11-03 at 3 36 35 PM

After:

Screenshot 2025-11-03 at 3 55 13 PM


Checked tctl, before:
```
 tctl get users        
ERROR: grpc: received message larger than max (24064507 vs. 4194304)
```

```
./build/tctl get users
---
kind: user
metadata:
  name: user-zyy09nl8
  revision: 02b40fe2-6361-47a7-91e5-dc756f0e1b1f
spec:
  created_by:
    time: "2025-10-31T13:25:51.966474931Z"
    user:
      name: a8de2a84-1be7-4930-acce-c50ada85b128.luke.dev
  expires: "0001-01-01T00:00:00Z"
  roles:
  - access
  - editor
  status:
    is_locked: false
    lock_expires: "0001-01-01T00:00:00Z"
    locked_time: "0001-01-01T00:00:00Z"
# ... output cut due to size
    - PaPvPozGMryfEukXkLbECQVgyTaFsBSMAHxvrKPUzZsoUCPPoXBdDquJIgdkAlor
    trait494:
    - pwxkQvUEQpaWghuuUiDyQjkJUUYCSdnLKeFshHBLGRRtEupsUCPwXjDreQKhjNuC
    trait495:
    - BmsCbPkSLknPdLtHTgJxlFPwRqMOjVJAWrTfkrNVmAoTAxosgYgYgDOimSsOAnzH
    trait496:
    - tNFFNyNFKuAMBgfbIsuVtePiJfznRPFPrPVoNjrCcaHNSpcSHbiKbiJoikMFtJJY
    trait497:
    - lUdcNfXAORJdvnXxkuHvGyoCbQlVJsoxRRTXMknGDGHqVXyvFHIaZHMKCuRXgFRq
    trait498:
    - ASWCqJZZhsFyioMdIXuAdduWApEbtmCDHOXDAJHrgOUCbpaZeDxOIlEGQlwPGziW
    trait499:
    - iHbyPrbCuqbJMBViyFPSxxjBneKgblxHYqyvhSYthTGrFNUycLikXRRKbSHPDEPH
    trait500:
    - ZONLFhrDjfolnksRZvuiIvkkGvOWePEHpwPZzZkajuuOXqttkjAJjgPZcoJNVTwW
status:
  mfa_weakest_device: 2
  password_state: 2
version: v2
```

File: api/utils/clientutils/resources.go [hunk 1]
```diff
@@ -180,3 +168,27 @@ func CollectWithFallback[T any](ctx context.Context,
 
 	return out, nil
 }
+
+// Page is a client side utility which implements auto page size adjustment.
+func Page[T any](ctx context.Context, pageSize int, pageToken string,
```
Comment (okraport) [inline api/utils/clientutils/resources.go:173]: @rosstimothy I think we should consider moving this wrapper to each of the list client methods to avoid missing helpers at client sites. 

We may also have to rethink this retry strategy depending on how often we hit this fallback so it could lead to a lot of bogus RPCs (perhaps key based pagesize caching?).

**Review by strideynet — COMMENTED** [review]
I think the approach out-lined is fine - but - I can't help but feel that it may be more efficient if the server could just adjust the number of resources returned? How challenging would it be to measure the size of the resource on the server and keep a running count of the size - and stop once we approach the limit?

**Comment by rosstimothy** [comment]
> I think the approach out-lined is fine - but - I can't help but feel that it may be more efficient if the server could just adjust the number of resources returned? How challenging would it be to measure the size of the resource on the server and keep a running count of the size - and stop once we approach the limit?

Challenging if we have to consider RBAC. I think we should start simple here and reexamine our options for dynamic server controlled page sizes in a separate unit of work.

**Review by rosstimothy — APPROVED** [review]

**Comment by okraport** [comment]
Friendly ping reviewers @strideynet @kopiczko, please take a look! 🙏

File: api/utils/clientutils/resources.go [hunk 2]
```diff
@@ -180,3 +168,27 @@ func CollectWithFallback[T any](ctx context.Context,
...
+	pageFunc func(context.Context, int, string) ([]T, string, error)) ([]T, string, error) {
+	for {
+		page, nextToken, err := pageFunc(ctx, pageSize, pageToken)
+		if err != nil {
+			if trace.IsLimitExceeded(err) {
+				// Cut chunkSize in half if gRPC max message size is exceeded.
+				pageSize /= 2
+				// This is an extremely unlikely scenario, but better to cover it anyways.
+				if pageSize == 0 {
+					return nil, "", trace.Wrap(err, "resource is too large to retrieve")
```
Comment (kopiczko) [inline api/utils/clientutils/resources.go]: Maybe it makes sense to print the nextToken here to make debugging easier. But it's "unlikely" so not a blocker.

**Review by kopiczko — APPROVED** [review]
LGTM, but isn't it possible to add a test for that? I guess there should be a way to create a gRPC service with restrictive limits to not eat some crazy amounts of memory and we can probably approximate the size fairly well with labels or any other value in metadata/spec.

**Review by strideynet — APPROVED** [review]

File: api/utils/clientutils/resources.go (hunk 2 above)
Comment (okraport) [reply api/utils/clientutils/resources.go]: This is a good addition, added, thanks!

**Comment by okraport** [comment]
> LGTM, but isn't it possible to add a test for that? I guess there should be a way to create a gRPC service with restrictive limits to not eat some crazy amounts of memory and we can probably approximate the size fairly well with labels or any other value in metadata/spec.

Thank you that's a good point. I am going to merge this as is to resolve the current issue, but I will make a note for myself to look into this separately.
