### PR TITLE
Fix an issue `context canceled` spams Proxy log for database connections

### LINKED ISSUE #31367: `context canceled` spams Proxy log for every database connection
Expected behavior:
A "normal" database connection shouldn't spam proxy log

Current behavior:
```
2023-09-01T17:36:49Z ERRO [DB:PROXY]  Failed to handle database TLS connection. error:[
ERROR REPORT:
Original Error: *errors.errorString context canceled
Stack Trace:
	github.com/gravitational/teleport/lib/srv/db/proxyserver.go:532 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).Proxy
	github.com/gravitational/teleport/lib/srv/db/proxyserver.go:364 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).handleConnection
	github.com/gravitational/teleport/lib/srv/db/proxyserver.go:303 github.com/gravitational/teleport/lib/srv/db.(*ProxyServer).ServeTLS.func1
	runtime/asm_amd64.s:1650 runtime.goexit
User Message: context canceled] db/proxyserver.go:305
```

Bug details:
- Teleport version: 14.0.0-alpha.2
- Recreation steps: `tsh db connect <redis>` and quit

Test Plan: https://github.com/gravitational/teleport/issues/31122

### PR DESCRIPTION
**Pull request by greedy52**
Fixes #31367

Caused by:
- monitored context is passed to `utils.ProxyConn`
- `utils.ProxyConn` finishes `io.Copy` and calls `clientConn.Close`
- `clientConn.Close` (in this case `TrackingReadConn.Close`) cancels the context
- `utils.ProxyConn` returns `context.Canceled`

The simple fix is to ignore `context.Canceled`. However, in case the connection is killed for a legit reason by the monitor (e.g. expired cert), the proxyserver should still launch an error. Thus the main change of this PR is to cancel and propagate the context with a proper `Cause`, when the monitor kills the connection:

```
2023-09-05T17:00:04Z ERRO [DB:PROXY]  Failed to handle database TLS connection. error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError client certificate expired at 2023-09-05 17:00:04.000143482 &#43;0000 UTC
Stack Trace:
github.com/gravitational/teleport/lib/srv/monitor.go:424 github.com/gravitational/teleport/lib/srv.(*Monitor).disconnectClient
github.com/gravitational/teleport/lib/srv/monitor.go:408 github.com/gravitational/teleport/lib/srv.(*Monitor).disconnectClientOnExpiredCert
github.com/gravitational/teleport/lib/srv/monitor.go:341 github.com/gravitational/teleport/lib/srv.(*Monitor).start
github.com/gravitational/teleport/lib/srv/monitor.go:289 github.com/gravitational/teleport/lib/srv.StartMonitor.func1
runtime/asm_amd64.s:1650 runtime.goexit

```

### CODE REVIEW

File: lib/srv/monitor.go [hunk 1]
```diff
@@ -405,15 +405,26 @@ func (w *Monitor) disconnectClientOnExpiredCert() {
 	w.disconnectClient(reason)
 }
 
+type canCloseWithCause interface {
```
Comment (smallinsky) [inline lib/srv/monitor.go:408]: nit: can we ranme. it like withCauseCloser ? The `canCloseWithCause` should like a function name that returns bool

**Review by smallinsky — APPROVED** [review]

File: lib/srv/db/proxyserver.go [hunk 2]
```diff
@@ -529,7 +530,23 @@ func (s *ProxyServer) Proxy(ctx context.Context, proxyCtx *common.ProxyContext,
...
+	// Ignore context.Canceled errors from monitoring.
+	//
+	// The clientConn is closed by utils.ProxyConn on successful io.Copy thus
+	// possibly causing utils.ProxyConn to return context.Canceled (as monitor
+	// context is closed when TrackingReadConn.Close() is called).
+	//
+	// In cases MonitorConn kills the connection for other reasons (e.g.
+	// expired cert), a proper cause will be returned instead of
+	// context.Canceled.
+	if trace.Unwrap(err) == context.Canceled {
```
Comment (tigrato) [inline lib/srv/db/proxyserver.go:544]: can we use `io.EOF` instead of `context.Canceled`?
Feels like a much better usecase.
Can you also use `errors.Is` instead of `trace.Unwrap`?

File: lib/srv/monitor.go [hunk 3]
```diff
@@ -157,12 +157,12 @@ func (c *ConnectionMonitor) MonitorConn(ctx context.Context, authzCtx *authz.Con
...
+		tctx, cancel := context.WithCancelCause(ctx)
 		tconn, err = NewTrackingReadConn(TrackingReadConnConfig{
-			Conn:    conn,
-			Clock:   c.cfg.Clock,
-			Context: tctx,
-			Cancel:  cancel,
+			Conn:            conn,
+			Clock:           c.cfg.Clock,
+			Context:         tctx,
+			CancelWithCause: cancel,
```
Comment (tigrato) [inline lib/srv/monitor.go:165]: Can we replace Cancel with CancelWithCause instead of adding a new field?

Comment (greedy52) [reply lib/srv/monitor.go:165]: I was trying to avoid refactoring kube forwarder code. But let me give it a try.

Comment (greedy52) [reply lib/srv/monitor.go]: Removed the cancel now and updated kube session code.

**Review by tigrato — APPROVED** [review]
Lovely!
Thank you @greedy52 !

**Review by smallinsky — APPROVED** [review]
