### PR TITLE
preserve explicit local auth disable

### LINKED ISSUE #15441: local_auth Issue in FIPS Mode
**Expected behavior:**
Teleport in FIPS mode should fail to start unless `local_auth: false` is set. 

**Current behavior:**
Teleport starts with no issue and displays a local login option when no` local_auth` configuration is set. When `local_auth: false` is set, Teleport fails to start (see Debug logs)

Bug details:
- Teleport version: 10.1.2 FIPS
- Recreation steps:
  -Start Teleport in FIPS mode without any `local_auth` configuration
  -Observe that you can see a user/pass login option in the WebUI (this should not happen, in previous versions, there is no user/pass displayed)
  -Under the authentication section of the auth service, add `local_auth: false`
  -Observe the logs (see below) to see that the Teleport service fails to start

- Debug logs:
These logs occur when `local_auth: false` is set. The logs look normal when there is no `local_auth:` configuration set. 

```
Aug 11 20:23:06 ip-192-168-12-72 teleport[1519]: Original Error: *trace.BadParameterError non-FIPS compliant authentication setting: &#34;local_auth&#34; must be false
Aug 11 20:23:06 ip-192-168-12-72 teleport[1519]: Stack Trace:
Aug 11 20:23:06 ip-192-168-12-72 teleport[1519]:         /go/src/github.com/gravitational/teleport/lib/config/configuration.go:1862 github.com/gravitational/teleport/lib/config.Configure
Aug 11 20:23:06 ip-192-168-12-72 teleport[1519]:         /go/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:367 github.com/gravitational/teleport/tool/teleport/common.Run
Aug 11 20:23:06 ip-192-168-12-72 teleport[1519]:         /go/src/github.com/gravitational/teleport/e/tool/teleport/main.go:18 main.main
Aug 11 20:23:06 ip-192-168-12-72 teleport[1519]:         /opt/go/src/runtime/proc.go:250 runtime.main
Aug 11 20:23:06 ip-192-168-12-72 teleport[1519]:         /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
Aug 11 20:23:06 ip-192-168-12-72 teleport[1519]: User Message: non-FIPS compliant authentication setting: &#34;local_auth&#34; must be false
```

### PR DESCRIPTION
**Pull request by fspmarshall**
Don't override explicit `local_auth: false` (still defaults to `true` if `local_auth` is unspecified).

Fixes https://github.com/gravitational/teleport/issues/15441

### CODE REVIEW

File: api/types/authentication.go [hunk 1]
```diff
@@ -416,13 +416,9 @@ func (c *AuthPreferenceV2) CheckAndSetDefaults() error {
 		c.SetOrigin(OriginDynamic)
 	}
 
+	// make sure type makes sense
```
Comment (codingllama) [inline api/types/authentication.go:419]: Ditch this? It doesn't help much.

File: api/types/authentication.go [hunk 2]
```diff
@@ -416,13 +416,9 @@ func (c *AuthPreferenceV2) CheckAndSetDefaults() error {
...
 	switch c.Spec.Type {
-	case constants.Local:
-		if !c.Spec.AllowLocalAuth.Value {
-			log.Warn("Ignoring local_auth=false when authentication.type=local")
-			c.Spec.AllowLocalAuth.Value = true
-		}
-	case constants.OIDC, constants.SAML, constants.Github:
+	case constants.Local, constants.OIDC, constants.SAML, constants.Github:
```
Comment (codingllama) [inline api/types/authentication.go:421]: Add this somewhere?

```suggestion
	case constants.Local, constants.OIDC, constants.SAML, constants.Github:
		// Note that "type:local" and "local_auth:false" is considered a valid
		// setting, as it is a common idiom for clusters that rely on dynamic
		// configuration.```

**Review by codingllama — COMMENTED** [review]
Thanks for the quick fix, @fspmarshall.

Could you add tests for:

* unspecified type and local_auth:false
* type:local and local_auth:false

so we document those configs and avoid future regressions?

**Review by r0mant — APPROVED** [review]

**Review by timothyb89 — APPROVED** [review]

**Comment by codingllama** [comment]
Hey @fspmarshall, could we backport this further back? I think we could go as far as v10.

FYI @r0mant too.
