### PR TITLE
Fix UserContext SSO detection in UI for Okta Users

### LINKED ISSUE #47901: Discover: set up principals (traits) fails when user is imported from Okta
When enrolling a new resource using the Discover wizard, one of the last steps is the Set Up Access.
This step asks the user to configure principals (os logins for SSH Access and db_user/name for Database Access). Those principals are added to the user's traits, which can then be used to access the protected resource.

When the user comes from an SSO, it doesn't have traits and so the step only tells the user how can they achieve the same goal (accessing the resource with a given principal) but using the SSO provider.

However, when the user comes from the Okta integration, we still try to update the user, and that fails with:

```
error updating user traits: Must be Okta service to set "okta" origin
```

Expected behavior:
Explain what the user needs to do to add a given principal to their allowed principals.

Current behavior:
Error `Must be Okta service to set "okta" origin` is shown.

Bug details:
- Teleport version: 16.4.6
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by marcoandredinis**
Okta imported users are not being properly identified as SSO users. Okta does not set any of the Users' identities and instead only sets the User.Connector.CreatedBy field.

When building the UserContext, which is used by the WebUI, it was returning `local` user type for Okta users.

As an example of what this fixes in the UI: when setting traits during the Discover flows, User is now correctly asked to change the Teleport Role instead of being allowed to enter principals but then getting an error.

Before
image

After
image

Fixes https://github.com/gravitational/teleport/issues/47901

changelog: During the Set Up Access of the Enroll New Resource flows, Okta users will be asked to change the role instead of entering the principals and getting an error afterwards.

### CODE REVIEW

**Review by smallinsky — APPROVED** [review]

File: lib/web/ui/usercontext.go [hunk 1]
```diff
@@ -104,7 +104,8 @@ func NewUserContext(user types.User, userRoles services.RoleSet, features proto.
 	authType := authLocal
 
 	// check for any SSO identities
-	isSSO := len(user.GetOIDCIdentities()) > 0 ||
+	isSSO := user.GetUserType() == types.UserTypeSSO ||
+		len(user.GetOIDCIdentities()) > 0 ||
```
Comment (greedy52) [inline lib/web/ui/usercontext.go:108]: looks good to me. just curious if `user.GetUserType()` is enough without check other identities?

**Review by greedy52 — APPROVED** [review]

File: lib/web/ui/usercontext.go (hunk 1 above)
Comment (marcoandredinis) [reply lib/web/ui/usercontext.go:108]: It only checks for the `CreatedBy.Connector != nil`.
I did that, but some tests started failing so I'm not sure we should be changing that.

On the other hard, maybe `user.GetUserType()` should check not only for the `CreatedBy.Connector` but also for the OIDC and SAML identities.
