### PR TITLE
Use time-based event index for app session events

### LINKED ISSUE #37049: `app.session.start` events do not appear in DynamoDB backend
### Expected behavior:

When an app session starts, the `app.session.start` should appear in the DynamoDB event backend when configured.

### Current behavior:

The `app.session.start` event does not appear in the DynamoDB events table, but does appear in the `file://` and `stdout://` if they are also configured. It always appears in the `INFO` level log line that is emitted by `events/emitter.go:271`.

While testing on one environment, we did observe one attempt to launch an app session result in the event being populated in DynamoDB. It was a bit strange because it appeared twice, but one second apart. I was not able to reproduce this success condition in my lab.

### Bug details:
- Teleport version: observed on 14.3.0, 14.2.0, 14.1.1
- Recreation steps:
  - set up `audit_events_uri` to have a `dynamodb://` destination. (you can have other destinations appear after)
  - launch an app session in the web UI
  - observe `2024-01-22T20:30:40Z INFO [AUDIT]     app.session.start addr.remote:10.0.0.4:32554 app_name:myapp...` appear in the proxy and auth logs (expected)
  - observe the event appear in stdout, file, or any other backend configured
  - Look in Teleport audit event viewer, and/or search DynamoDB table for `EventType=app.session.start`.
  - No `app.session.start` will be present. Only `app.session.chunk` will appear for the given session. The associated `cert.create` event also appears, which has most of the same information.
- Debug logs - N/A

### PR DESCRIPTION
**Pull request by gabrielcorado**
Closes #37049

As described on the issue, the events were being overwritten on DynamoDB events storage because they had the same key pair (SessionID and Index). The problem is that every time a new session chunk is initialized, it uses a new recorder, which would then have the index start at 0. This would cause any previous event from the session to be overwritten.

The solution proposed on this PR is, for app sessions, to generate an event index based on the session start (here, the time the certificate was issued), removing the necessity of a distributed counter.

In addition, the solution also needed to take into account if different servers handle an app session. For app access, the sessions are not ended if the server handling it changes (HA). In case that happens, the recorder would start over at index 0 and overwrite all the events emitted by the proxy and other app server.

NOTE: This change only affects app session recordings; other resources will still use the incremental method.

This PR also adds a [DynamoDB condition expression](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html#Expressions.ConditionExpressions.PreventingOverwrites) to guarantee events are not being overwritten on the storage layer.

changelog: Fix application access events being overwritten when using DynamoDB as event storage.

### CODE REVIEW

File: lib/events/recorder/recorder.go [hunk 1]
```diff
@@ -87,6 +87,10 @@ type Config struct {
 
 	// BackoffDuration is a duration of the backoff before the next try.
 	BackoffDuration time.Duration
+
+	// StartTime represents the time the recorder statarted. If not zero, this
```
Comment (codingllama) [inline lib/events/recorder/recorder.go:91]:
```suggestion
	// StartTime represents the time the recorder started. If not zero, this
```

File: lib/events/setter.go [hunk 2]
```diff
@@ -60,6 +61,10 @@ type PreparerConfig struct {
 
 	// ClusterName defines the name of this teleport cluster.
 	ClusterName string
+
+	// StartTime represents the time the recorder statarted. If not zero, this
```
Comment (codingllama) [inline lib/events/setter.go:65]:
```suggestion
	// StartTime represents the time the recorder started. If not zero, this
```

File: lib/events/setter.go [hunk 3]
```diff
@@ -135,6 +139,14 @@ func (c *Preparer) PrepareSessionEvent(event apievents.AuditEvent) (apievents.Pr
 	return preparedEvent, nil
 }
 
+func (c *Preparer) nextIndex() int64 {
+	if !c.cfg.StartTime.IsZero() {
```
Comment (codingllama) [inline lib/events/setter.go:143]: Is it possible for all items have a start time, so we don't need to keep the fallback logic?

File: lib/srv/app/server.go [hunk 4]
```diff
@@ -1187,3 +1205,13 @@ func newGetConfigForClientFn(log logrus.FieldLogger, client auth.AccessCache, tl
 		return tlsCopy, nil
 	}
 }
+
+// certFromConnState returns certificate from the connection.
```
Comment (codingllama) [inline lib/srv/app/server.go:1209]:
```suggestion
// certFromConnState returns the leaf certificate from the connection.
```

File: lib/srv/app/server.go [hunk 5]
```diff
@@ -1187,3 +1205,13 @@ func newGetConfigForClientFn(log logrus.FieldLogger, client auth.AccessCache, tl
...
+func certFromConn(tlsConn *tls.Conn) *x509.Certificate {
```
Comment (codingllama) [inline lib/srv/app/server.go:1210]:
```suggestion
func leafCertFromConn(tlsConn *tls.Conn) *x509.Certificate {
```

File: lib/srv/app/server.go [hunk 6]
```diff
@@ -1139,6 +1144,19 @@ func (s *Server) getProxyPort() string {
 	return port
 }
 
+// sessionStartTime fetches the session start time based on the the certificate
+// valid date.
+func (s *Server) sessionStartTime(ctx context.Context) time.Time {
+	var startTime time.Time
+	if userCert, err := authz.UserCertificateFromContext(ctx); err == nil {
```
Comment (codingllama) [inline lib/srv/app/server.go:1151]: I assume we use the certificate NotBefore because we want this to be deterministic for a user, correct?

It would be nice if we could just draw a random number - it's simple, less prone to time clashes (although with nanos precision that is quite difficult) and we could use that to guarantee that this number always exists, dropping the old logic.

File: lib/srv/app/server.go [hunk 7]
```diff
@@ -1139,6 +1144,19 @@ func (s *Server) getProxyPort() string {
...
+		startTime = userCert.NotBefore
+	} else {
+		s.log.Warn("Unable to retrieve session start time from certificate.")
```
Comment (codingllama) [inline lib/srv/app/server.go:1154]: In which situations is this expected to happen? Could we get a comment?

File: lib/srv/app/server.go [hunk 8]
```diff
@@ -1187,3 +1205,13 @@ func newGetConfigForClientFn(log logrus.FieldLogger, client auth.AccessCache, tl
 		return tlsCopy, nil
 	}
 }
+
+// certFromConnState returns certificate from the connection.
+func certFromConn(tlsConn *tls.Conn) *x509.Certificate {
+	state := tlsConn.ConnectionState()
+	if len(state.PeerCertificates) != 1 {
```
Comment (codingllama) [inline lib/srv/app/server.go:1212]:
```suggestion
	if len(state.PeerCertificates) == 0 {
```

There could be a cert chain here, but I don't see why that would be a problem.

File: lib/srv/app/server.go [hunk 9]
```diff
@@ -1139,6 +1144,19 @@ func (s *Server) getProxyPort() string {
...
+// valid date.
+func (s *Server) sessionStartTime(ctx context.Context) time.Time {
+	var startTime time.Time
+	if userCert, err := authz.UserCertificateFromContext(ctx); err == nil {
+		startTime = userCert.NotBefore
+	} else {
+		s.log.Warn("Unable to retrieve session start time from certificate.")
+	}
+
+	return startTime
```
Comment (codingllama) [inline lib/srv/app/server.go:1157]: Maybe: ditch the startTime var and return directly?

```suggestion
	if userCert, err := authz.UserCertificateFromContext(ctx); err == nil {
		return userCert.NotBefore
	}

	s.log.Warn("Unable to retrieve session start time from certificate.")
	return time.Time{}
```

File: lib/events/setter_test.go [hunk 10]
```diff
@@ -0,0 +1,123 @@
...
+	for i := 0; i < 9; i++ {
+		evtOne, err := preparerOne.PrepareSessionEvent(generateEvent())
+		require.NoError(t, err)
+		idxOne := evtOne.GetAuditEvent().GetIndex()
+
+		evtTwo, err := preparerTwo.PrepareSessionEvent(generateEvent())
+		require.NoError(t, err)
+		idxTwo := evtTwo.GetAuditEvent().GetIndex()
+
+		require.NotEqual(t, idxOne, idxTwo)
```
Comment (codingllama) [inline lib/events/setter_test.go:100]: We are counting on the timestamps moving for this to not collide, right? Maybe use/increment a fake clock to be 100% sure?

File: lib/events/setter_test.go [hunk 11]
```diff
@@ -0,0 +1,123 @@
...
+
+func generateEvent() apievents.AuditEvent {
+	return &apievents.AppSessionChunk{
+		Metadata: apievents.Metadata{
+			Type:        AppSessionChunkEvent,
+			Code:        AppSessionChunkCode,
+			ClusterName: "root",
+		},
+		ServerMetadata: apievents.ServerMetadata{
+			ServerID:        uuid.New().String(),
```
Comment (codingllama) [inline lib/events/setter_test.go:113]:
```suggestion
			ServerID:        uuid.NewString(),
```

File: lib/events/setter_test.go [hunk 12]
```diff
@@ -0,0 +1,123 @@
...
+			ServerNamespace: apidefaults.Namespace,
+		},
+		AppMetadata: apievents.AppMetadata{
+			AppURI:        "nginx",
+			AppPublicAddr: "https://nginx",
+			AppName:       "nginx",
+		},
+		SessionChunkID: uuid.New().String(),
```
Comment (codingllama) [inline lib/events/setter_test.go:121]:
```suggestion
		SessionChunkID: uuid.NewString(),
```

**Comment by codingllama** [comment]
Overall looks good, added a few questions as I'm not super familiar with these parts.

File: lib/srv/app/server.go (hunk 6 above)
Comment (greedy52) [reply lib/srv/app/server.go:1151]: Indeed interesting approach. Chunks are every five minutes if I recall. So using nanoseconds ensures chunks are relatively in order. However in HA case, time on different app servers may not be perfectly in sync.

**Review by greedy52 — COMMENTED** [review]
The approach looks good to me. The key index is used in app sessions recordings as well. After this change, ppl will see big numbers as key index instead of 1,2,3, so we need to document this behavior somewhere.

**Comment by codingllama** [comment]
> After this change, ppl will see big numbers as key index instead of 1,2,3, so we need to document this behavior somewhere.

We could also use UnixNano for "smaller" numbers, but it'll still be quite large compared to "1,2,3".

File: lib/events/dynamoevents/dynamoevents.go [hunk 13]
```diff
@@ -446,8 +446,9 @@ func (l *Log) createPutItem(sessionID string, in apievents.AuditEvent) (*dynamod
 		return nil, trace.Wrap(err)
 	}
 	return &dynamodb.PutItemInput{
-		Item:      av,
-		TableName: aws.String(l.Tablename),
+		Item:                av,
+		TableName:           aws.String(l.Tablename),
+		ConditionExpression: aws.String("attribute_not_exists(SessionID) AND attribute_not_exists(EventIndex)"),
```
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply lib/events/dynamoevents/dynamoevents.go:451]: Yes, as soon as they update their auth servers and events from older app servers, they will hit this, at least for the first `app.session.chunk` (which conflicts with `app.session.start`). As mentioned in the PR description, if the app server serving the requests changes, there will be more conflicts (generating more errors).

File: lib/srv/app/server.go (hunk 6 above)
Comment (gabrielcorado) [reply lib/srv/app/server.go:1151]: > I assume we use the certificate NotBefore because we want this to be deterministic for a user, correct?

The idea is to keep the index characteristics as an always-growing number. Since the app sessions are stateless, I relied on the certificate `NotBefore` time since it is consistent during the entire session.

> It would be nice if we could just draw a random number

The random numbers would work here because our events storage doesn't rely on the index to sort (they use the event timestamps). However, it is not guaranteed that the index will always increase within the session. If we're okay with changing this index characteristic, I don't see any problem using a random number.

> However in HA case, time on different app servers may not be perfectly in sync.

We can still have collisions in that case, although they will be rare (given that we're using nanoseconds elapsed time). The solution for this would be to consider the ServerID while generating the index, which is similar to what Snowflake IDs do, or set the index on the proxy/auth servers.

File: lib/events/dynamoevents/dynamoevents.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (greedy52) [reply lib/events/dynamoevents/dynamoevents.go:451]: If we release this check with the patch, customers's auth will be "spammed" with this before app servers are upgraded. As discussed offline, it is preferred to handle this separately and ideally release it in a new major version. By that time, app servers should have been upgraded with this patch already and we can likely catch other events that have the same problem during the release testing.

Though, since this check does not block using the app, and we are losing events before app servers are upgraded anyway, I don't mind if we really want to release this together.

**Review by greedy52 — APPROVED** [review]
Tested today and worked as expected 👍 . Do we expect this change affect other event backend?

File: lib/events/dynamoevents/dynamoevents.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply lib/events/dynamoevents/dynamoevents.go:451]: I prefer having an error log to silently overwriting audit events (current behavior).

@codingllama, Any thoughts on this?

[the remark this answers is not in the document]
Comment (codingllama) [reply lib/events/dynamoevents/dynamoevents.go:451]: I'm afraid I don't have enough context to have a strong opinion here.

**Review by codingllama — APPROVED** [review]
