### PR TITLE
[web] Add lock target matcher and fix button themes

### LINKED ISSUE #24850: Table search field filters the results.
Locks table doesn't properly filter the "Locked Items" column. We would need to have a custom matcher to check the nested fields of the lock targets.

### PR DESCRIPTION
**Pull request by avatus**
Fixes: https://github.com/gravitational/teleport/issues/24850

This PR will enable searching the lock targets. The example below shows a lock target as `user:mfa`, previously, search didnt work for this field at all. the `lockTargetMatcher` will allow us to search by the lock type and lock value, so `user` would show all of the results in the image and `mfa` would keep only the `user:mfa` entry down here.
Screenshot 2023-04-19 at 3 37 40 PM

The message, locked by, and dates still filter as expected. This custom search is additive to the normal filter.

Also, the buttons didn't account for the new themes.
Before
Screenshot 2023-04-19 at 3 34 04 PM

After:
Screenshot 2023-04-19 at 3 34 12 PM

### CODE REVIEW

File: web/packages/teleport/src/Locks/Locks.tsx [hunk 1]
```diff
@@ -43,6 +44,20 @@ function getFormattedDate(d: string): string {
...
 
+function lockTargetsMatcher(
+  targetValue: any,
+  searchValue: string,
+  propName: keyof LockForTable & string
+) {
+  if (propName === 'targets') {
+    return targetValue.some(
+      ({ name, value }) =>
+        name.toUpperCase().includes(searchValue) ||
```
Comment (rudream) [inline web/packages/teleport/src/Locks/Locks.tsx:55]: Shouldn't `searchValue` also be `toUpperCase()`'ed?

File: web/packages/teleport/src/Locks/Locks.tsx [hunk 2]
```diff
@@ -43,6 +44,20 @@ function getFormattedDate(d: string): string {
...
+        value.toUpperCase().includes(searchValue)
```
Comment (rudream) [inline web/packages/teleport/src/Locks/Locks.tsx:56]: We should also add the whole `name: value` string as a valid match that way if someone searches "user: req" they get results as opposed to having to only search by either `name` or `value`.

```
|| `${name}: ${value}`.toUppercase().includes(searchValue)
```

File: web/packages/teleport/src/Locks/Locks.tsx (hunk 1 above)
Comment (avatus) [reply web/packages/teleport/src/Locks/Locks.tsx:55]: searchValue comes in uppercased already

File: web/packages/teleport/src/Locks/Locks.tsx (hunk 2 above)
Comment (avatus) [reply web/packages/teleport/src/Locks/Locks.tsx]: Great idea. added.

**Review by zmb3 — APPROVED** [review]

**Review by rudream — APPROVED** [review]

File: web/packages/teleport/src/Locks/Locks.tsx (hunk 1 above)
Comment (avatus) [reply web/packages/teleport/src/Locks/Locks.tsx]: For future readers, it happens here: https://github.com/gravitational/teleport/blob/master/web/packages/design/src/utils/match/match.ts#L43
