### PR TITLE
Fixes error propagation and resizes during MFA

### LINKED ISSUE #41515: "websocket unavailable" when starting RDP session in full screen mode
Expected behavior:

I'm starting RDP sessions using Chrome/ium's App mode, to provide a more native feel, using the following command:

```
chrome.exe --app=https://teleport.local/web/cluster/teleport.local/desktops/the-hostname/myuser --start-fullscreen
```

After logging in with a Passkey, I'm prompted for MFA auth.

Current behavior:

After touching the yubikey when the Windows MFA prompt appears, I get the following error: "websocket unavailable"

image

devtools error:

image

**This error only occurs when trying to use MFA in full screen mode, if I hit F11 to get out of full screen mode, it works flawlessly.** 

This message is produced when the error occurs:
```
May 14 13:48:03 teleport.local teleport[3068931]: 2024-05-14T13:48:03+02:00 INFO [AUDIT]     mfa_auth_challenge.create challenge_allow_reuse:false challenge_scope:CHALLENGE_SCOPE_USER_SESSION cluster_name:teleport.local code:T1015I ei:0 event:mfa_auth_challenge.create time:2024-05-14T11:48:03.89Z uid:7394e7f6-842e-4209-8fb4-2f33da719448 user:myuser user_kind:1 events/emitter.go:288
May 14 13:48:05 teleport.local teleport[3068931]: 2024-05-14T13:48:05+02:00 ERRO [WEB]       expected MFA message type 10, got 1 cluster-name:teleport.local desktop-name:the-hostname session:6d11 user:myuser web/desktop.go:84

```

My Role has `spec.options.require_session_mfa: true`

This is reproducible reliably with Chrome 123.0.6312.123/32bit and MSEdge 123.0.2420.97 on Windows 10, and sometimes with chromium-121.0.6167.85-1.fc38.x86_64 on Fedora 38.

Previously, with Teleport 15.1.8, this used to work everytime/everywhere.

Bug details:
- Teleport version: 15.3.0, 15.3.4
- Recreation steps: use the above chromium command line for a RDP host with MFA enabled
- Debug logs: see above

### PR DESCRIPTION
**Pull request by ibeckermayer**
Adds mechanisms for withholding resizes

1. A new mechanism is added to withhold all non-MFA TDP messages during the MFA ceremony within lib/web/desktop.go.
2. A new mechanism is added to withhold all resizes when the rdpclient/client.go is not yet ready to receive messages. (Non-resize messages are still just dropped).

This fixes https://github.com/gravitational/teleport/issues/41515

Also fixes the error propagation issue evident in https://github.com/gravitational/teleport/issues/41515, see point 1 in https://github.com/gravitational/teleport/issues/41515#issuecomment-2110326395

changelog: Solved a bug that was causing Windows Desktop sessions to fail when the screen was resized during an MFA ceremony

### CODE REVIEW

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 1]
```diff
@@ -365,7 +368,7 @@ func (c *Client) startInputStreaming(stopCh chan struct{}) error {
 	defer c.cfg.Logger.InfoContext(context.Background(), "TDP input streaming finished")
 
 	// Remember mouse coordinates to send them with all CGOPointer events.
-	var mouseX, mouseY uint32
+	var withheldResize *tdp.ClientScreenSpec
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:371]: The comment about remembering mouse coordinates no longer seems accurate here.

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 2]
```diff
@@ -385,284 +388,310 @@ func (c *Client) startInputStreaming(stopCh chan struct{}) error {
...
-				button = C.PointerButtonNone
-			}
-			if errCode := C.client_write_rdp_pointer(
+		if err := c.handleMessage(msg); err != nil {
+			return trace.Wrap(err)
+		}
+	}
+}
+
+func (c *Client) handleMessage(msg tdp.Message) error {
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:421]: `handleMessage` seems too vague of a name - is it an incoming message or an outgoing message?

File: lib/srv/desktop/rdp/rdpclient/client.go [hunk 3]
```diff
@@ -385,284 +388,310 @@ func (c *Client) startInputStreaming(stopCh chan struct{}) error {
...
-			c.cfg.Logger.WarnContext(context.Background(),
-				fmt.Sprintf("Skipping unimplemented TDP message type %T", msg))
+		if errCode := C.client_handle_tdp_rdp_response_pdu(
+			C.ulong(c.handle), rdpResponsePDU, C.uint32_t(pduLen),
+		); errCode != C.ErrCodeSuccess {
+			return trace.Errorf("RDPResponsePDU failed: %v", errCode)
 		}
+	default:
+		c.cfg.Logger.WarnContext(context.Background(),
+			fmt.Sprintf("Skipping unimplemented TDP message type %T", msg))
```
Comment (zmb3) [inline lib/srv/desktop/rdp/rdpclient/client.go:691]: We no longer need to use Sprintf here. Forrest made a `TypeAttr` utility:
```suggestion
		c.cfg.Logger.WarnContext(context.Background(), "Skipping unimplemented TDP message", "type", logutils.TypeAttr(msg)))
```

File: lib/web/desktop.go [hunk 4]
```diff
@@ -218,7 +226,20 @@ const (
...
 )
 
-func (h *Handler) desktopTLSConfig(ctx context.Context, ws *websocket.Conn, clusterClient auth.ClientI, sessCtx *SessionContext, desktopName, username, siteName string) (_ *tls.Config, err error) {
+// desktopTLSConfig returns a TLS config for connecting to a Windows Desktop Service.
+// It also performs MFA if required.
+//
+// This function returns the TLS config, and a list of withheld TDP messages if MFA was
+// required and any were received before the MFA message was sent. It is the caller's
+// responsibility to send these withheld messages through to the server after the MFA
+// ceremony is completed.
```
Comment (zmb3) [inline lib/web/desktop.go:235]: I think the long confusing comment here is an indicator that `desktopTLSConfig` has become unwieldy. It started out as a way to build a `tls.Config` for the connection, now it withholds messages, does MFA, etc.

At a minimum we should rename it, but I wonder if we can come up with a better design so that we don't have to plumb these withheld messages through.

**Review by zmb3 — COMMENTED** [review]
Feels like this will work fine but I wonder if there's a better way.

Also, it would be great to start to get some test coverage in here, especially as we fix bugs like this one.

File: lib/srv/desktop/rdp/rdpclient/client.go (hunk 2 above)
Comment (ibeckermayer) [reply lib/srv/desktop/rdp/rdpclient/client.go]: f36db5e5f1c7dcaa346b1438557a8b6005c5ba35

File: lib/srv/desktop/rdp/rdpclient/client.go (hunk 1 above)
Comment (ibeckermayer) [reply lib/srv/desktop/rdp/rdpclient/client.go:370]: f36db5e5f1c7dcaa346b1438557a8b6005c5ba35

File: lib/web/desktop.go (hunk 4 above)
Comment (ibeckermayer) [reply lib/web/desktop.go]: I made `withheldMessages` a member of `Handler` and restructured things to make the steps more readily apparent from the function names: 6aa0331cda8fa820514dc896c6e75a7f56f45b30

**Review by zmb3 — APPROVED** [review]
Looks good. Please make sure to test with and without MFA required, and with a resizing desktop as well as a fixed-size one.

**Comment by zmb3** [comment]
Let's try to get the backport merged by EOD Monday so it makes it into the Tuesday release.

**Review by probakowski — APPROVED** [review]
