### PR TITLE
Lookup and return hostname as part of new UI session request

### LINKED ISSUE #4143: Terminal tabs display @SID instead of @hostname
### Description
When terminal creates a new session, it expects an API to return a session object with populated fields. It does not happen because of https://github.com/gravitational/teleport/blob/master/lib/web/apiserver.go#L1483
returns a dummy object. We need to refactor this method (perhaps remove it and add a slight changes to "connect" method) but it's also OK to return a hostname as part of the dummy object  [EDITED] by @alex-kovoy 

**What happened**:
terminal tabs display node server ID, instead of node's hostname. 

image

**What you expected to happen**:
Display hostname name, it is easier to read and relate with.

**How to reproduce it (as minimally and precisely as possible)**:
https://teleport-4-3-oss.practice.io:3080/web
1. Connect to a node via web UI
1. Notice the tabs `login@serverID`

### Environment
- Teleport version (use `teleport version`): Teleport v4.3.2 git:v4.3.2-0-gc6d702ad8 go1.13.2

### PR DESCRIPTION
**Pull request by kimlisa**
closes https://github.com/gravitational/teleport/issues/4143

#### Description
- Get the hostname by looking up nodes by serverID and set the hostname before returning
- Hostname is required to display hostname in UI terminal tab, instead of UUID (which is less readable and relatable)
- Hostname or UUID will both return hostname of node. Except for ip addresses, the hostname will remain the ip address.

#### Related PR
https://github.com/gravitational/webapps/pull/140

#### Manual testing
```
Request URL: https://localhost:8080/v1/webapi/sites/im-a-cluster-name/sessions
Request Method: POST
```
image

### CODE REVIEW

File: lib/web/apiserver.go [hunk 1]
```diff
@@ -1494,12 +1489,27 @@ func (h *Handler) siteSessionGenerate(w http.ResponseWriter, r *http.Request, p
...
+
+		req.Session.ServerHostname = hostname
+	}
+
+	req.Session.ID = session.NewID()
 	req.Session.Created = time.Now().UTC()
 	req.Session.LastActive = time.Now().UTC()
 	req.Session.Namespace = namespace
+
 	log.Infof("Generated session: %#v", req.Session)
```
Comment (alex-kovoy) [inline lib/web/apiserver.go:1511]: > log.Infof("Generated sessi...

lets delete these line (some leftover from earlier implementations)

**Review by alex-kovoy — APPROVED** [review]

File: lib/web/apiserver.go (hunk 1 above)
Comment (kimlisa) [reply lib/web/apiserver.go]: removed
