### PR TITLE
Correctly reissue certificates for leaf resources in tsh proxy kube

### LINKED ISSUE #41022: `tsh proxy kube kube-cluster --cluster=leaf` fails to reissue certs
When connecting to a kube cluster in a leaf cluster, `tsh proxy kube` fails to reissue certs successfully after the kube certs expire. 

Fixing this behavior is especially important when `max_session_ttl` is low, which is common in per-session MFA setups.

Expected behavior:

`tsh proxy kube kube-cluster --clsuter=leaf` should reissue certs whenever the certs expire.

Current behavior:

`tsh proxy kube kube-cluster --cluster=leaf` fails to reissue certs.

Debug logs:

```
2024-04-29T13:12:29-07:00 DEBU             Started forwarding request for "root.example.com:3080". alpnproxy/forward_proxy.go:368
2024-04-29T13:12:29-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-04-29 20:13:25 +0000 UTC". client/client_store.go:111
2024-04-29T13:12:29-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-04-29 20:13:25 +0000 UTC". client/client_store.go:111
2024-04-29T13:12:29-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-04-29 20:13:25 +0000 UTC". client/client_store.go:111
2024-04-29T13:12:29-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-04-29 20:13:25 +0000 UTC". client/client_store.go:111
2024-04-29T13:12:29-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-04-29 20:13:25 +0000 UTC". client/client_store.go:111
2024-04-29T13:12:29-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-04-29 20:13:25 +0000 UTC". client/client_store.go:111
2024-04-29T13:12:29-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2024-04-29 20:13:25 +0000 UTC". client/client_store.go:111
2024-04-29T13:12:29-07:00 DEBU [CLIENT]    MFA requirement acquired from leaf, MFARequired=MFA_REQUIRED_NO client/cluster_client.go:563
2024-04-29T13:12:29-07:00 WARN [TSH]       Failed to reissue certificate for server 6d696e696b756265.leaf.example.com error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError MFA is not required to access resource
Stack Trace:
	github.com/gravitational/teleport/lib/client/cluster_client.go:568 github.com/gravitational/teleport/lib/client.PerformMFACeremony
	github.com/gravitational/teleport/lib/client/cluster_client.go:373 github.com/gravitational/teleport/lib/client.(*ClusterClient).performMFACeremony
	github.com/gravitational/teleport/lib/client/cluster_client.go:486 github.com/gravitational/teleport/lib/client.(*ClusterClient).IssueUserCertsWithMFA
	github.com/gravitational/teleport/tool/tsh/common/kube_proxy.go:578 github.com/gravitational/teleport/tool/tsh/common.issueKubeCert
	github.com/gravitational/teleport/tool/tsh/common/kube_proxy.go:568 github.com/gravitational/teleport/tool/tsh/common.makeKubeLocalProxy.(*kubeLocalProxy).getCertReissuer.func1
	github.com/gravitational/teleport/lib/srv/alpnproxy/kube.go:243 github.com/gravitational/teleport/lib/srv/alpnproxy.(*KubeMiddleware).reissueCertIfExpired.func1
	runtime/asm_amd64.s:1695 runtime.goexit
User Message: MFA is not required to access resource] alpnproxy/kube.go:181
2024-04-29T13:12:29-07:00 DEBU             Stopped forwarding request for "root.example.com:3080". alpnproxy/forward_proxy.go:374
```

### PR DESCRIPTION
**Pull request by rosstimothy**
When renewing certificates the RouteToCluster was always being set to the root cluster instead of the leaf cluster. This causes issues with per session mfa because the root cluster can't find the target kubernetes cluster which causes the renewal process to fail. Now during renewal the RouteToCluster is copied from the active user certificate if it existed.

Closes #41022.

Changelog:  Fix a bug that was preventing tsh proxy kube certificate renewal from working when accessing a leaf kubernetes cluster via the root.

### CODE REVIEW

**Comment by Joerger** [comment]
> @Joerger could you run through the test scenario again off this branch?

It worked for me as well.

**Review by capnspacehook — APPROVED** [review]

**Review by Joerger — APPROVED** [review]

File: lib/srv/alpnproxy/kube.go [hunk 1]
```diff
@@ -240,7 +240,12 @@ func (m *KubeMiddleware) reissueCertIfExpired(ctx context.Context, cert tls.Cert
 	if m.isCertReissuingRunning.CompareAndSwap(false, true) {
 		go func() {
 			defer m.isCertReissuingRunning.Store(false)
-			newCert, err := m.certReissuer(context.Background(), identity.TeleportCluster, identity.KubernetesCluster)
+
+			cluster := identity.TeleportCluster
+			if identity.RouteToCluster != "" {
+				cluster = identity.RouteToCluster
+			}
+			newCert, err := m.certReissuer(context.Background(), cluster, identity.KubernetesCluster)
```
Comment (strideynet) [inline lib/srv/alpnproxy/kube.go:248]: Is there a reason we explicitly use the background ctx rather than the in-scope ctx here - if so - we should add a comment with words to that effect.

**Review by strideynet — APPROVED** [review]
