### PR TITLE
Remove cacert flag from curl output during tsh app login.

### LINKED ISSUE #7518: CA certificate produced by `tsh app login` does not include intermediate certificates, causing default curl invocation to fail
### Description

**What happened**:
Running `tsh app login foo` produces the following output:

```text
Logged into app foo. Example curl command:

curl \
  --cacert /home/ari/.tsh/keys/example.com/certs.pem \
  --cert /home/ari/.tsh/keys/example.com/ari@example.com-app/example.com/foo-x509.pem \
  --key /home/ari/.tsh/keys/example.com/ari@example.com \
  https://foo.example.com:443
```

When running the proposed command (with `--verbose` added, for the sake of this bug report), `curl` complains with:

```text
*   Trying 1.2.3.4:443...
* Connected to foo.example.com (1.2.3.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /home/ari/.tsh/keys/example.com/certs.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**What you expected to happen**:

For the `curl` call to succeed.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Issue a 90-day ACME certificate from ZeroSSL https://zerossl.com/ and configure the Teleport proxy service to use it
2. Note that the certificate issued by ZeroSSL, and therefore the certificate file referenced in `teleport.yaml`'s `proxy_service.https_keypairs[0].cert_file` includes the full certificate chain including root certificate and intermediate certificates
3. Add an Application to proxy, call it `foo`
4. `tsh app login foo`
5. `curl` call as described above
6. Note that the certificate at `/home/<you>/.tsh/keys/example.com/certs.pem` does not include the full certificate chain

### Server Details
- Teleport version (run `teleport version`): 6.2.6
- Server OS (e.g. from `/etc/os-release`): Running within a container on Kubernetes - `quay.io/gravitational/teleport:6.2.6`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

### Client Details
- Tsh version (`tsh version`): 6.2.3
- Computer OS (e.g. Linux, macOS, Windows): Linux
- Browser version (for UI-related issues): N/A
- Installed via (e.g. apt, yum, brew, website download): Nix

### Debug Logs
Not relevant?

### Workaround
Simply remove the `--cacert` line:
```text
curl \
  --cert /home/ari/.tsh/keys/example.com/ari@example.com-app/example.com/foo-x509.pem \
  --key /home/ari/.tsh/keys/example.com/ari@example.com \
  https://foo.example.com:443
```
which works as expected (as ZeroSSL is a trusted public CA).

### PR DESCRIPTION
**Pull request by mdwn**
The cacert flag was removed from the curl output during the tsh app login as most production Teleport clusters are likely to be using publicly trusted CAs, and therefore wouldn't need the flag.

Additionally, some tests have been added for the formatAppConfig function. It was discovered that the YAML output format was outputting two newlines, so a small modification was made to remove this.

Addresses issue #7518.

### CODE REVIEW

**Comment by tigrato** [comment]
Since `tsh` connects to the proxy, can we check if `tsh --insecure` is enabled and append the CACert for the demo on that case?

**Comment by mdwn** [comment]
> Since `tsh` connects to the proxy, can we check if `tsh --insecure` is enabled and append the CACert for the demo on that case?

Just to confirm, you're looking for this behavior?

```
➜  mw-test tsh app login drone
Logged into app drone. Example curl command:

curl \
  --cert /Users/mike/.tsh/keys/platform.teleport.sh/michael.wilson@goteleport.com-app/platform.teleport.sh/drone-x509.pem \
  --key /Users/mike/.tsh/keys/platform.teleport.sh/michael.wilson@goteleport.com \
  https://drone.platform.teleport.sh
➜  mw-test tsh app login drone --insecure
Logged into app drone. Example curl command:

curl \
  --cacert /Users/mike/.tsh/keys/platform.teleport.sh/cas/platform.teleport.sh.pem \
  --cert /Users/mike/.tsh/keys/platform.teleport.sh/michael.wilson@goteleport.com-app/platform.teleport.sh/drone-x509.pem \
  --key /Users/mike/.tsh/keys/platform.teleport.sh/michael.wilson@goteleport.com \
  https://drone.platform.teleport.sh
```

File: tool/tsh/app.go [hunk 1]
```diff
@@ -228,30 +228,42 @@ func onAppConfig(cf *CLIConf) error {
...
 		uri = fmt.Sprintf("https://%v", appPublicAddr)
 	} else {
 		uri = fmt.Sprintf("https://%v:%v", appPublicAddr, port)
 	}
-	curlCmd := fmt.Sprintf(`curl \
+
+	var curlCmd string
+	if insecure {
+		curlCmd = fmt.Sprintf(`curl \
   --cacert %v \
```
Comment (r0mant) [inline tool/tsh/app.go:250]: Hmm, not sure - why do we still want to show this flag in insecure mode?

Comment (tigrato) [reply tool/tsh/app.go:250]: @r0mamt,
My idea was to keep the curl command working if Teleport runs with an untrusted certificate. 
 If users are testing it locally it would be difficult for them to understand what is wrong since we gave them the command to run.

Comment (r0mant) [reply tool/tsh/app.go:250]: Right, my question was how keeping --cacert flag is going to help since curl is still not going to be able to validate self-signed cert presented by Teleport. We can add `-k` flag to curl command when insecure flag is given, but we should also then output a warning saying that curl command will skip cert validation.

Comment (mdwn) [reply tool/tsh/app.go:250]: I think the `-k` and the warning makes a lot of sense. @tigrato, I think I'll go ahead and implement that.

**Comment by mdwn** [comment]
The most recent PR update presents the following:
```
➜  etc git:(stable) tsh app login demo                
Logged into app demo. Example curl command:

curl \
  --cert /Users/mike/.tsh/keys/mw-test.teleport/teleport-admin-app/mw-test.teleport/demo-x509.pem \
  --key /Users/mike/.tsh/keys/mw-test.teleport/teleport-admin \
  https://demo.mw-test.teleport
➜  etc git:(stable) tsh app login demo --insecure
Logged into app demo. Example curl command:

curl -k \
  --cert /Users/mike/.tsh/keys/mw-test.teleport/teleport-admin-app/mw-test.teleport/demo-x509.pem \
  --key /Users/mike/.tsh/keys/mw-test.teleport/teleport-admin \
  https://demo.mw-test.teleport

WARNING: tsh was called with --insecure, so this curl command will be unable to validate the cert presented by teleport.
```

File: tool/tsh/app.go (hunk 1 above)
Comment (mdwn) [reply tool/tsh/app.go]: Let me know what you think about https://github.com/gravitational/teleport/pull/16769#issuecomment-1262313995.

File: tool/tsh/app.go [hunk 2]
```diff
@@ -228,30 +232,40 @@ func onAppConfig(cf *CLIConf) error {
...
 		uri = fmt.Sprintf("https://%v", appPublicAddr)
 	} else {
 		uri = fmt.Sprintf("https://%v:%v", appPublicAddr, port)
 	}
-	curlCmd := fmt.Sprintf(`curl \
-  --cacert %v \
+
+	var curlCmd string
+	if insecure {
+		curlCmd = fmt.Sprintf(`curl -k \
```
Comment (zmb3) [inline tool/tsh/app.go:253]:
```suggestion
		curlCmd = fmt.Sprintf(`curl --insecure \
```

Since the user is probably going to copy this anyway, the more verbose version should be preferred. This gives them more of a warning that what they're doing is not secure.

Comment (mdwn) [reply tool/tsh/app.go:253]: Sounds good, thank you!

File: tool/tsh/app.go [hunk 3]
```diff
@@ -106,13 +106,14 @@ func onAppLogin(cf *CLIConf) error {
 			"appName": app.GetName(),
 		})
 	}
-	curlCmd, err := formatAppConfig(tc, profile, app.GetName(), app.GetPublicAddr(), appFormatCURL, rootCluster)
+	curlCmd, err := formatAppConfig(tc, profile, app.GetName(), app.GetPublicAddr(), appFormatCURL, rootCluster, cf.InsecureSkipVerify)
```
Comment (r0mant) [inline tool/tsh/app.go:109]: Can you get the "insecure" flag from Telelport Client (`tc` variable) instead of passing yet another flag?

File: tool/tsh/app.go [hunk 4]
```diff
@@ -123,7 +124,10 @@ func onAppLogin(cf *CLIConf) error {
 var appLoginTpl = template.Must(template.New("").Parse(
 	`Logged into app {{.appName}}. Example curl command:
 
-{{.curlCmd}}
+{{.curlCmd}}{{ if .insecure }}
+
+WARNING: tsh was called with --insecure, so this curl command will be unable to validate the cert presented by teleport.
```
Comment (r0mant) [inline tool/tsh/app.go:129]:
```suggestion
WARNING: tsh was called with --insecure, so this curl command will be unable to validate the certificate presented by Teleport.
```

**Review by r0mant — APPROVED** [review]

**Comment by r0mant** [comment]
@zmb3 or @tigrato - since you looked at this before, can one of you take another look? It looks good to me now.

File: tool/tsh/app.go [hunk 5]
```diff
@@ -245,15 +249,25 @@ func formatAppConfig(tc *client.TeleportClient, profile *client.ProfileStatus, a
 	} else {
 		uri = fmt.Sprintf("https://%v:%v", appPublicAddr, port)
 	}
-	curlCmd := fmt.Sprintf(`curl \
-  --cacert %v \
+
+	var curlCmd string
+	if tc.InsecureSkipVerify {
```
Comment (tigrato) [inline tool/tsh/app.go:254]: Can we simplify this to something like:

```go
	var curlInsecureFlag string
	if tc.InsecureSkipVerify {
		curlInsecureFlag = "--insecure "
	}

	curlCmd := fmt.Sprintf(`curl %s\
  --cert %v \
  --key %v \
  %v`,
			curlInsecureFlag,
			profile.AppCertPath(appName),
			profile.KeyPath(),
			uri)

```

I think it's easier to read and to understand that the only difference is the `--insecure` flag

**Review by tigrato — APPROVED** [review]
LGTM. 
Only a minor comment to simplify the logic if possible
