### PR TITLE
Lower EC2 label log frequency

### LINKED ISSUE #14593: IMDS metadata service not being enabled on EC2 causes Teleport log spam
**Expected behavior:**
The IMDS metadata service not being enabled should not generate `WARN` level messages inside Teleport; this should fail silently. Alternatively, the message should be emitted at `DEBUG` level.

**Current behavior:**
IMDS metadata service being disabled causes a message to appear repeatedly in the logs:
```
Jul 15 11:51:43 hostname teleport[7699]: 2022-07-15T11:51:43-04:00 WARN [EC2LABELS] Could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance ec2/ec2.go:113
Jul 15 11:52:47 hostname teleport[7699]: 2022-07-15T11:52:47-04:00 WARN [EC2LABELS] Could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance ec2/ec2.go:113
Jul 15 12:51:42 hostname teleport[7699]: 2022-07-15T12:51:42-04:00 WARN [EC2LABELS] Could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance ec2/ec2.go:113
Jul 15 12:52:47 hostname teleport[7699]: 2022-07-15T12:52:47-04:00 WARN [EC2LABELS] Could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance ec2/ec2.go:113
Jul 15 13:51:41 hostname teleport[7699]: 2022-07-15T13:51:41-04:00 WARN [EC2LABELS] Could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance ec2/ec2.go:113
Jul 15 13:52:46 hostname teleport[7699]: 2022-07-15T13:52:46-04:00 WARN [EC2LABELS] Could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance ec2/ec2.go:113
Jul 15 14:51:41 hostname teleport[7699]: 2022-07-15T14:51:41-04:00 WARN [EC2LABELS] Could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance ec2/ec2.go:113
Jul 15 14:52:45 hostname teleport[7699]: 2022-07-15T14:52:45-04:00 WARN [EC2LABELS] Could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance ec2/ec2.go:113
```

**Bug details:**
- Teleport version: 10.0.1

### PR DESCRIPTION
**Pull request by atburke**
This PR makes the error message for when EC2 tags aren't available in instance metadata only emit once, to reduce log spam.

Resolves #14593.

### CODE REVIEW

File: lib/labels/ec2/ec2.go [hunk 1]
```diff
@@ -110,7 +110,7 @@ func (l *EC2) Sync(ctx context.Context) error {
 	tags, err := l.c.Client.GetTagKeys(ctx)
 	if err != nil {
 		if trace.IsNotFound(err) {
-			l.c.Log.Warningf("could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance")
+			l.c.Log.Debug("could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance")
```
Comment (zmb3) [inline lib/labels/ec2/ec2.go:113]: This is just spamming at a different log level, right? Should we change the behavior a bit? Some ideas:

- try up to a maximum number of times and then give up and assume the user doesn't want to fetch tags (at which point we stop logging it)
- only log this warning the first time we encounter it
- implement some sort of backoff so that retries get further apart (and therefore we see the log item less frequently)

WDYT?

Comment (atburke) [reply lib/labels/ec2/ec2.go:113]: I like the idea of trying a max number of times and then assuming the user doesn't want tags.

Comment (zmb3) [reply lib/labels/ec2/ec2.go:113]: The only downside there is if they eventually enable the API on the AWS side, they have to restart Teleport to pick up the change.

Comment (atburke) [reply lib/labels/ec2/ec2.go:113]: True, and I think that's less intuitive than EC2 labels working again once the API is enabled. I might try option 2 instead.

Comment (jakule) [reply lib/labels/ec2/ec2.go]: @atburke I also think that option two makes the most sense. Can you just revert the log level to warning again? I don't think that anyone will notice one extra debug log now.

File: lib/labels/ec2/ec2.go [hunk 2]
```diff
@@ -110,11 +113,16 @@ func (l *EC2) Sync(ctx context.Context) error {
 	tags, err := l.c.Client.GetTagKeys(ctx)
 	if err != nil {
 		if trace.IsNotFound(err) {
-			l.c.Log.Warningf("could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance")
+			// Only show the error the first time around.
+			if !l.loggedInstanceTagsNotFound {
+				l.loggedInstanceTagsNotFound = true
+				l.c.Log.Warning("could not fetch tags, please ensure 'allow instance tags in metadata' is enabled on the instance")
```
Comment (r0mant) [inline lib/labels/ec2/ec2.go:119]:
```suggestion
				l.c.Log.Warning("Could not fetch EC2 instance's tags, please ensure 'allow instance tags in metadata' is enabled on the instance.")
```

**Review by r0mant — APPROVED** [review]

**Review by jakule — APPROVED** [review]
