### PR TITLE
Kube Proxy Forwarder handles kube services with same name

### LINKED ISSUE #5183: Kube service intermittent unavailable
### Description

**What happened**:

Kubernetes requests through `kube_service` can be intermittently unavailable.   In this scenario a kube-agent was deployed to a eu region EKS cluster  with a us-east-1 region teleport proxy/auth.   The majority of requests work with some producing the following issue.

user cli:
```bash
$ kubectl get po
Error from server (InternalError): an error on the server ("Internal Server Error") has prevented the request from succeeding (get pods)
```
in proxy log:
```bash
ERRO [PROXY:PRO] Error forwarding to https://remote.kube.proxy.teleport.cluster.local/api/v1/namespaces/default/pods?limit=500, err: dialing through a tunnel: no tunnel connection found: no kube reverse tunnel for e5e332ab-b4cb-400b-b37f-20701ad79ad4.tele1c found, dialing directly: dial tcp: address 
```

Reducing the keep alive appears to resolve the issue.

```
auth_service:
   keep_alive_interval: 1m
   keep_alive_count_max: 5
```

**What you expected to happen**:

Reverse tunnel with `kube_service` is stable.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy a cluster in a different region and run a kube agent.  

### Environment
- Teleport version (use `teleport version`):5.0.2

### LINKED ISSUE #8402: Gracefully handle unreachable node
### Description

**What happened**:
Assumption: The backend is aware of multiple kubernetes services. 

When one of the kubernetes services is stopped, Teleport continues to throw errors rather than direct request to reachable instances. 

**What you expected to happen**:
Teleport should direct requests to reachable services. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

### PR DESCRIPTION
**Pull request by Joerger**
Update Kube Proxy forwarder to use all available `kube_service` endpoints instead of just a random one. This fixes situations where a `kube_cluster` is registered multiple times, such as due to restarts.

This also makes it possible to intentionally load balance across multiple `kube_services` when you register a `kube_cluster` multiple times. This can be reproduced locally by registering the same `kube_cluster` with everything equivalent except `data_dir`.

Fixes https://github.com/gravitational/teleport/issues/5183
Fixes https://github.com/gravitational/teleport/issues/8402

### CODE REVIEW

File: lib/kube/proxy/forwarder.go [hunk 1]
```diff
@@ -307,6 +308,13 @@ type authContext struct {
 	sessionTTL time.Duration
 }
 
+type endpoint struct {
+	// targetAddr is a direct network address.
+	addr string
+	// serverID is an address reachable over a reverse tunnel.
```
Comment (zmb3) [inline lib/kube/proxy/forwarder.go:314]: Is it an ID or an address?

File: lib/kube/proxy/forwarder.go [hunk 2]
```diff
@@ -307,6 +308,13 @@ type authContext struct {
 	sessionTTL time.Duration
 }
 
+type endpoint struct {
+	// targetAddr is a direct network address.
```
Comment (zmb3) [inline lib/kube/proxy/forwarder.go:312]:
```suggestion
	// address is a direct network address.
```

File: lib/kube/proxy/forwarder.go [hunk 3]
```diff
@@ -1367,13 +1374,39 @@ func (s *clusterSession) monitorConn(conn net.Conn, err error) (net.Conn, error)
...
 }
 
+func (s *clusterSession) DialWithEndpoints(network, addr string) (net.Conn, error) {
+	if len(s.teleportClusterEndpoints) == 0 {
+		return nil, trace.BadParameter("No endpoints to dial")
+	}
+
+	// Shuffle endpoints to balance load
+	shuffledEndpoints := s.teleportClusterEndpoints
+	mathrand.Seed(time.Now().UnixNano())
```
Comment (zmb3) [inline lib/kube/proxy/forwarder.go:1391]: You shouldn't re-seed with each dial.

File: lib/kube/proxy/forwarder.go [hunk 4]
```diff
@@ -1489,22 +1522,21 @@ func (f *Forwarder) newClusterSessionLocal(ctx authContext) (*clusterSession, er
...
 		authContext: ctx,
 		// This session talks to a kubernetes_service, which should handle
 		// audit logging. Avoid duplicate logging.
 		noAuditEvents: true,
 	}
-	// Set both addr and serverID, in case this is a kubernetes_service
-	// connected over a tunnel.
-	sess.authContext.teleportCluster.targetAddr = kubeService.GetAddr()
-	sess.authContext.teleportCluster.serverID = fmt.Sprintf("%s.%s", kubeService.GetName(), ctx.teleportCluster.name)
+	sess.authContext.teleportClusterEndpoints = endpoints
```
Comment (zmb3) [inline lib/kube/proxy/forwarder.go:1539]: Do we need to synchronize access to `sess.authContext` ?

**Review by zmb3 — CHANGES_REQUESTED** [review]

File: lib/kube/proxy/forwarder.go (hunk 4 above)
Comment (Joerger) [reply lib/kube/proxy/forwarder.go:1539]: I could be wrong but I don't see any race conditions as is. It looks to me like the proxy-forwarding logic is all asynchronous since it is all run on each request.

File: lib/kube/proxy/forwarder.go [hunk 5]
```diff
@@ -66,6 +66,10 @@ import (
 	utilexec "k8s.io/client-go/util/exec"
 )
 
+func init() {
+	mathrand.Seed(time.Now().UnixNano())
```
Comment (zmb3) [inline lib/kube/proxy/forwarder.go:70]: What do you think about moving this to `main` instead? It really only needs to be called once, and if we start to do it in a package's `init()` function then we could end up with multiple packages making the same call.

File: lib/kube/proxy/forwarder.go (hunk 1 above)
Comment (Joerger) [reply lib/kube/proxy/forwarder.go]: Yes... a bit of both. Updated comment to clarify here and from original comment in `teleportClusterClient.serverID`.

File: lib/kube/proxy/forwarder.go (hunk 5 above)
Comment (Joerger) [reply lib/kube/proxy/forwarder.go:70]: Hmm In that case it wouldn't be seeded in tests, or any other package outside of `tools/teleport` that might import it. If anything it might be better to move this to a `lib/utils/rand` package and reuse it to avoid this issue. What do you think?

**Comment by Joerger** [comment]
@zmb3 fyi I added tests for `dialWithEndpoints`, and made some other minor changes to do so.

File: lib/kube/proxy/forwarder.go (hunk 5 above)
Comment (zmb3) [reply lib/kube/proxy/forwarder.go:70]: You don't really need to seed it for tests. It's fine if you get the same ordering every time in tests. But if you really wanted to you could put it in a `TestMain`.

Comment (andrejtokarcik) [reply lib/kube/proxy/forwarder.go:70]: I also think it'd be most appropriate to initialize the generator globally by moving this call to `main`. If you wanted to have a scope-limited generator for some reason, consider using a `rand.Rand` instance.

**Review by andrejtokarcik — APPROVED** [review]

**Review by zmb3 — APPROVED** [review]

**Review by klizhentas — APPROVED** [review]
