### PR TITLE
Remove expected `kube_server`, `app`, `database` and `installer` watchers for remote proxies

### LINKED ISSUE #17211: Cannot SSH to nodes connected to a v10 leaf cluster from a v11 root cluster
Expected behavior:
It's possible to use resources connected to a v10 cluster from a parent v11 cluster.

Current behavior:
SSH into a leaf cluster fails because the reverse tunnel access point (and thus the [proxy's node watcher](https://github.com/gravitational/teleport/pull/12014)) fails to ever initialize, due to v10 not knowing about `kube_server` and `kube_cluster`, which were introduced in #14389

Bug details:
- Teleport version: v11.0.0-alpha.2 root, v10.3.1 leaf
- Recreation steps: join a v10 leaf cluster with a ssh node to a v11 cluster, ssh from the root into the leaf
- Debug logs:
v11 proxy
```
{"caller":"cache/cache.go:825","component":"reverse:child.wet-dry.world:1:cache","level":"warning","message":"Re-init the cache on error: watcher is closed: access denied to perform action \"read\" on \"kube_server\".","timestamp":"2022-10-10T13:34:43+02:00"}
{"caller":"cache/cache.go:825","component":"reverse:child.wet-dry.world:1:cache","level":"warning","message":"Re-init the cache on error: watcher is closed: access denied to perform action \"read\" on \"kube_cluster\".","timestamp":"2022-10-10T13:35:23+02:00"}
{"caller":"cache/cache.go:825","component":"reverse:child.wet-dry.world:1:cache","level":"warning","message":"Re-init the cache on error: watcher is closed: access denied to perform action \"read\" on \"kube_server\".","timestamp":"2022-10-10T13:36:03+02:00"}
{"caller":"cache/cache.go:825","component":"reverse:child.wet-dry.world:1:cache","level":"warning","message":"Re-init the cache on error: watcher is closed: access denied to perform action \"read\" on \"kube_cluster\".","timestamp":"2022-10-10T13:36:53+02:00"}
```

v10 auth/proxy (I reckon the error hits before the actual existence of the resources is checked)
```
{"caller":"services/role.go:2403","component":"rbac","level":"info","message":"Access to read kube_server in namespace default denied to roles RemoteProxy,default-implicit-role: no allow rule matched.","timestamp":"2022-10-10T13:34:43+02:00"}
{"caller":"services/role.go:2403","component":"rbac","level":"info","message":"Access to read kube_cluster in namespace default denied to roles RemoteProxy,default-implicit-role: no allow rule matched.","timestamp":"2022-10-10T13:35:23+02:00"}
{"caller":"services/role.go:2403","component":"rbac","level":"info","message":"Access to read kube_server in namespace default denied to roles RemoteProxy,default-implicit-role: no allow rule matched.","timestamp":"2022-10-10T13:36:03+02:00"}
{"caller":"services/role.go:2403","component":"rbac","level":"info","message":"Access to read kube_cluster in namespace default denied to roles RemoteProxy,default-implicit-role: no allow rule matched.","timestamp":"2022-10-10T13:36:53+02:00"}
```

### LINKED ISSUE #17219: Cannot SSH to nodes connected to a v10.2.2 leaf cluster from a v10.2.3 root cluster
Expected behavior:
It's possible to use resources connected to a v10.2.2 cluster from a parent v10.2.3 cluster.

Current behavior:
SSH into a leaf cluster fails because the reverse tunnel access point (and thus the [proxy's node watcher](https://github.com/gravitational/teleport/pull/12014)) fails to ever initialize, due to v10.2.2 and earlier not knowing about `installer`, which was introduced in #13886.

### PR DESCRIPTION
**Pull request by tigrato**
V10 Leaf clusters when connecting to a V11 Root cluster failed to initialize because they do not have `kube_server` resources defined.
This PR bumps the OLD remote proxy to versions <11 and removes the expected `kube_server` watcher.

It also removes `types.KindInstaller`, `types.KindDatabase`, and `types.KindApp` watchers from Remote Proxies since they do not affect remote reverse tunnels tracked from leaf clusters.
Fix incompatibility with pre/post v10.2.1 versions as the `types.KindInstaller` feature did not exist in older versions.

Fixes #17211 
Fixes #17219

### CODE REVIEW

File: lib/reversetunnel/srv.go [hunk 1]
```diff
@@ -1172,7 +1172,7 @@ func newRemoteSite(srv *server, domainName string, sconn ssh.Conn) (*remoteSite,
 // (RFD 28) because older proxy servers will reject that causing the cache
 // to go into a re-sync loop.
 func createRemoteAccessPoint(srv *server, clt auth.ClientI, version, domainName string) (auth.RemoteProxyAccessPoint, error) {
```
Comment (espadolini) [inline lib/reversetunnel/srv.go:1174]: Please update the comment for this.

File: lib/cache/cache.go [hunk 2]
```diff
@@ -202,11 +202,14 @@ func ForOldRemoteProxy(cfg Config) Config {
...
 		{Kind: types.KindTunnelConnection},
+		{Kind: types.KindAppServer},
 		{Kind: types.KindAppServer, Version: types.V2},
+		{Kind: types.KindApp},
 		{Kind: types.KindRemoteCluster},
 		{Kind: types.KindKubeService},
 		{Kind: types.KindDatabaseServer},
-		{Kind: types.KindKubeServer},
+		{Kind: types.KindDatabase},
+		{Kind: types.KindInstaller},
```
Comment (espadolini) [inline lib/cache/cache.go:212]: Is this just taken from the v10 `ForRemoteProxy`? If so, it might be worth mentioning it in a comment (maybe in the godoc for `ForOldRemoteProxy`).

**Review by espadolini — APPROVED** [review]

**Review by espadolini — APPROVED** [review]

**Review by Tener — APPROVED** [review]

**Review by espadolini — APPROVED** [review]
