### PR TITLE
Emit an Audit log event when a Bot or Instance fails to join

### LINKED ISSUE #17948: Delegated Joining (GitHub & CircleCI) should be clearer about what claim did not match
As it stands, we return an extremely opaque error when a token does not meet any allow criteria. This does not help users work out which part of their configuration they need to change to enable joining.

One issue is that multiple allow criteria can be present on a `ProvisionTokenV2`. We need a nice way of logging this that shows what was expected and what the actual value was for each rule. Do we want to show just the keys that differ ? Or also show the keys that match?

 e.g:
```
Provided GitHub IDToken did not match any allow rules: [
  {
    "repository": {
       "want": "foobar"
       "got": "jim/foobar"
    }
  }
]
```

### PR DESCRIPTION
**Pull request by strideynet**
Currently, a failed join is not audit logged or even logged. This makes it really hard to determine why a join failed or to detect a malicious join attempt. This PR introduces an audit log event which is emitted when a join fails for any reason.

For join methods that support returning the attributes of the joining identity, these will also show in the audit log. Not all join methods support this yet, and we ought to return to those and add the appropriate methods so they do surface this information which is extremely useful in diagnosing problems with joining and allow rules.

image

image

changelog: Adds a new Audit log event that is emitted when an Agent or Bot request to join the cluster is denied.

Closes https://github.com/gravitational/teleport/issues/17948

### CODE REVIEW

File: lib/auth/join.go [hunk 1]
```diff
@@ -114,6 +115,92 @@ func setRemoteAddrFromContext(ctx context.Context, req *types.RegisterUsingToken
...
+	}
+	if req != nil && req.Role == types.RoleBot {
+		botJoinEvent := &apievents.BotJoin{
+			Metadata: apievents.Metadata{
+				Type: events.BotJoinEvent,
+				Code: events.BotJoinFailureCode,
+			},
+			Status:     status,
+			BotName:    "unknown",
+			Method:     "unknown",
```
Comment (avatus) [inline lib/auth/join.go:166]: is it our convention to add `"unknown"` in all of these fields instead of leaving them empty?

Comment (avatus) [reply lib/auth/join.go:166]: Hm, I'm unsure as well. To me, `"unknown"` throws a much bigger red flag than empty but I could be wrong. If we've already implemented other unknowns, then perhaps we shouldn't change it here until we have a better idea/plan. If it's a UI thing, we could bring it up at the UX/UI open hours to see if they have a better solution?

**Review by avatus — APPROVED** [review]

File: lib/events/codes.go [hunk 2]
```diff
@@ -420,8 +420,12 @@ const (
 
 	// BotJoinCode is the 'bot.join' event code.
 	BotJoinCode = "TJ001I"
+	// BotJoinFailureCode is the 'bot.join' event code for failures.
+	BotJoinFailureCode = "TJ001E"
 	// InstanceJoinCode is the 'node.join' event code.
 	InstanceJoinCode = "TJ002I"
+	// InstanceJoinFailureCode is the 'node.join' event code for failures.
+	InstanceJoinFailureCode = "TJ001E"
```
Comment (ibeckermayer) [inline lib/events/codes.go:428]:
```suggestion
	InstanceJoinFailureCode = "TJ002E"
```

File: lib/auth/join.go (hunk 1 above)
Comment (ibeckermayer) [reply lib/auth/join.go:166]: It looks like I did something similar in various desktop events e.g.

https://github.com/gravitational/teleport/blob/39882ea520705b8a6ff8114a5b7653117a1a81de/lib/srv/desktop/audit.go#L267

It could make sense to standardize this along the lines of:

- `""`: consider this a bug
- `"unknown"`: typically events of this kind would have this field, but it could not be known at the time of event emission

The idea being that we want to be able to clearly distinguish between data loss due to bugs (which are high priority fixes, due to the security-relevance of audit events) vs data which we explicitly omit by necessity.

However I notice that e.g `BotName` is `"omitempty"`

https://github.com/gravitational/teleport/blob/39882ea520705b8a6ff8114a5b7653117a1a81de/api/proto/teleport/legacy/types/events/events.proto#L3740-L3741

so this particular case might be as @avatus suggested, just worthy of a client side display fix.

File: lib/auth/join.go [hunk 3]
```diff
@@ -144,40 +239,52 @@ func (a *Server) RegisterUsingToken(ctx context.Context, req *types.RegisterUsin
 			"sure your node is configured to use the %s join method", method, method)
 	case types.JoinMethodGitHub:
 		claims, err := a.checkGitHubJoinRequest(ctx, req)
```
[the remark this answers is not in the document]
Comment (strideynet) [reply lib/auth/join.go:241]: I think you might be mistaken - the behaviour of named returns in Go is a little special. Even if you redefine the variable name is a lower scope, the value that is actually returned is "put" into the named variable when executing defer.

https://go.dev/play/p/VZfeCQi7TdH

[the remark this answers is not in the document]
Comment (ibeckermayer) [reply lib/auth/join.go:241]: I stand corrected, thanks!

File: lib/events/codes.go (hunk 2 above)
Comment (strideynet) [reply lib/events/codes.go]: 243bd63ec5

File: lib/auth/join.go (hunk 1 above)
Comment (strideynet) [reply lib/auth/join.go:166]: > It could make sense to standardize this along the lines of:
> 
> - "": consider this a bug
> - "unknown": typically events of this kind would have this field, but it could not be known at the time of event emission

Imho this is a good direction to head in - audit logs contain important information and when this information is missing, we need to act. Distinguishing between audit logs that have been emitted in a place where a certain field is not yet known, and those that are missing the information because of a bug or because they predate the field having been added is useful.

> However I notice that e.g BotName is "omitempty"

I'm not too sure this has a significant impact, at the time when I added these events, I wasn't too sure whether to use omitempty or not.

Comment (strideynet) [reply lib/auth/join.go]: After a chat with Edoardo, I'm going to remove these "unknown" default values for now.

**Review by tigrato — APPROVED** [review]

**Comment by strideynet** [comment]
@rosstimothy 

> https://github.com/gravitational/teleport/pull/40729 added some logging for failed login attempts. Are we now going to log things twice? Does this take any of those changes into account?

I've already resolved the conflicts with this PR, I've removed those log lines in favour of my ones, and added any details that were missing from mine. I feel it still makes sense to move ahead with my PR since 40729 did not add an audit log event, and for our cloud customers, they do not have access to the logs of Teleport. The audit log is therefore the only way we can provide feedback about misconfigured joins.

I'll hold off merging until you've had a chance to see/respond to this :)

File: lib/auth/join.go (hunk 1 above)
Comment (ibeckermayer) [reply lib/auth/join.go]: tl;dr of your chat out of curiousity?

**Review by ibeckermayer — APPROVED** [review]
