### PR TITLE
Retry app access requests in different servers when there is a connection failure

### LINKED ISSUE #9126: App access requests should fail over if agent is unavailable
### Description

**What happened**:

If one of multiple app agents proxying the same application is unavailable, the proxied requests will be failing each time our "random load balancer" algorithm picks the unavailable agent with errors like:

```
2021-11-18T22:32:41Z ERRO [APP:WEB]   "Error forwarding to /favicon.ico, err: Teleport proxy failed to connect to \"app\" agent \"@local-node\" over reverse tunnel:\n\n  no tunnel connection found: no app reverse tunnel for f7261349-a79f-4163-96d5-a803b782822b.proxy.example.com found\n\nThis usually means that the agent is offline or has disconnected. Check the\nagent logs and, if the issue persists, try restarting it or re-registering it\nwith the cluster." forward/fwd.go:179
```

This causes most issues in Kubernetes clusters when, say, upgrading app agents. Since redeployment recreates an app agent pod, the heartbeat for the old pod still lingers on until it expires from the backend.

**What you expected to happen**:

App access forwarder should retry the request on a different application agent in case it got a reverse tunnel error:

https://github.com/gravitational/teleport/blob/v8.0.0/lib/web/app/session.go#L65-L82
https://github.com/gravitational/teleport/blob/master/lib/web/app/transport.go#L184

**Additional info**:

A similar issue was fixed in database access a while ago. Here's a ticket and a PR for reference:

https://github.com/gravitational/teleport/issues/5808
https://github.com/gravitational/teleport/pull/7293

**Other tickets**:

There is another ticket https://github.com/gravitational/teleport/issues/9065 that describes this issue but I think that ticket's description is inaccurate since it's talking about cookie "sticky-ness" which AFAIK we don't have and the error logs indicate that that's the issue with restarting app agents as described here.

### Reproduction Steps

The easiest way to reproduce would be to have 2 app agents proxying the same application, then shut down one of them and keep trying to use the app.

We should also reproduce this in Kubernetes scenario as described above to make sure the fix adequately address it as well.

### PR DESCRIPTION
**Pull request by gabrielcorado**
Closes #9126 by retrying the app requests in different agents.

The solution consists of two parts:
1. Changing the `transport` (`lib/web/app/transport.go`) to receive a list of servers, and when `DialContext` fails, it will try a different server from the list. Note: every time a server has connection issues, it is removed from the list, and when the list is empty, the transport returns an error;
2. When creating the `transport` forwarder, provide an `ErrorHandler` which will (when called) expire the current session, create a new one (with a fresh list of agents) and forward the request using it;

In addition to these changes, the new session process now matches only "healthy" servers. A "healthy" server is a server where the handler could establish a connection.

### CODE REVIEW

File: lib/web/app/transport.go [hunk 1]
```diff
@@ -159,39 +166,62 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
-// over the transport's reverse tunnel.
-func websocketsDialer(tr *http.Transport) forward.Dialer {
-	return func(network, address string) (net.Conn, error) {
-		conn, err := tr.DialContext(context.Background(), network, address)
+// DialContext
+func (t *transport) DialContext(ctx context.Context, _ string, _ string) (net.Conn, error) {
+	t.mu.Lock()
+	defer t.mu.Unlock()
+
+	for i := len(t.c.servers) - 1; i >= 0; i-- {
```
Comment (smallinsky) [inline lib/web/app/transport.go:174]: In this approach in scenario where all app agents are available the we will forward all connection to only one app agent without any LB approach.

File: lib/web/app/session.go [hunk 2]
```diff
@@ -62,30 +63,34 @@ func (h *Handler) newSession(ctx context.Context, ws types.WebSession) (*session
 	if err != nil {
 		return nil, trace.Wrap(err)
 	}
-	server, err := Match(ctx, accessPoint, MatchPublicAddr(identity.RouteToApp.PublicAddr))
+
+	servers, err := Match(ctx, accessPoint, MatchAll(MatchHealthy(h.c.ProxyClient, identity), MatchPublicAddr(identity.RouteToApp.PublicAddr)))
```
Comment (smallinsky) [inline lib/web/app/session.go:67]: Not sure why we need check all app servers healthy status here. 
It looks like the logic in Transport Dial function does already the same thing: https://github.com/gravitational/teleport/pull/9288/files#diff-9dd39725077cc062cbe4ded242810d79af548977d645d288875b70d49d759072R174

File: lib/web/app/handler.go [hunk 3]
```diff
@@ -140,29 +141,63 @@ func (h *Handler) handleForward(w http.ResponseWriter, r *http.Request, session
...
+
+	session, err := h.renewSession(req)
+	if err != nil {
+		w.WriteHeader(http.StatusInternalServerError)
+		w.Write([]byte(http.StatusText(http.StatusInternalServerError)))
+		return
+	}
+
+	session.fwd.ServeHTTP(w, req)
+}
```
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply lib/web/app/handler.go:163]: Not really, the new session flow now only matches "healthy" servers, so if there isn't any, it will return an error on the renew the session function.

However, there can be a case where the server is unstable, meaning that at the session creation, it is healthy, but when the forward happens, it is not. So we'll have the loop you mentioned in this case, and the client will timeout its request.

File: lib/web/app/transport.go (hunk 1 above)
Comment (gabrielcorado) [reply lib/web/app/transport.go:174]: True, I'll add a shuffle on the `Match` function, so we get a new ordination of the server's list every time a new session is created and keep the current behavior.

File: lib/web/app/transport.go [hunk 4]
```diff
@@ -98,17 +102,20 @@ func newTransport(c *transportConfig) (*transport, error) {
...
 	}
 
-	return &transport{
-		c:      c,
-		tr:     tr,
-		dialer: websocketsDialer(tr),
-	}, nil
+	tr.DialContext = t.DialContext
+	tr.TLSClientConfig = t.clientTLSConfig
+	return t, nil
```
Comment (jakule) [inline lib/web/app/transport.go:118]: Here you make some changes to `tr`, but then return `t`? Looks like a typo.

File: integration/app_integration_test.go [hunk 5]
```diff
@@ -1397,6 +1437,73 @@ func (p *pack) waitForLogout(appCookie string) (int, error) {
...
+	log := testlog.FailureOnly(t)
+
+	var err error
+	servers := make([]*service.TeleportProcess, count)
+
+	for i := 0; i < count; i++ {
+		raConf := service.MakeDefaultConfig()
+		raConf.Console = nil
+		raConf.Log = log
+		raConf.DataDir, err = ioutil.TempDir("", fmt.Sprintf("app-server-%d-%s", i, p.rootCluster.Secrets.SiteName))
```
Comment (jakule) [inline integration/app_integration_test.go:1450]: nit: `ioutil` is deprecated, use os.MkdirTemp:
```suggestion
		raConf.DataDir, err = os.MkdirTemp("", fmt.Sprintf("app-server-%d-%s", i, p.rootCluster.Secrets.SiteName))
```

File: lib/web/app/match_test.go [hunk 6]
```diff
@@ -0,0 +1,97 @@
+/*
+Copyright 2020 Gravitational, Inc.
```
Comment (jakule) [inline lib/web/app/match_test.go:2]: nit:
```suggestion
Copyright 2021 Gravitational, Inc.
```

File: lib/web/app/transport.go (hunk 4 above)
Comment (gabrielcorado) [reply lib/web/app/transport.go:118]: Not really, the `tr` is inside the `t` (which is the `*transport` we want to return). I will change the order of the changes to make it more clear.

File: lib/web/app/session.go (hunk 2 above)
Comment (gabrielcorado) [reply lib/web/app/session.go:67]: The idea is to give the transport a more accurate list of servers, and in the case of no healthy status, it would fail before the actual request forward. It is also aligned with the solution, where if the transport's list of servers is empty, the new transport will have only healthy servers to forward requests to, also working as a stop condition of this "renew loop".

Do you think it is better to avoid dialing apps during session creation?

File: lib/web/app/handler.go [hunk 7]
```diff
@@ -140,29 +141,63 @@ func (h *Handler) handleForward(w http.ResponseWriter, r *http.Request, session
...
 		h.log.Debugf("Failed to fetch application session: not found.")
 		return nil, trace.AccessDenied("invalid session")
 	}
 
-	// Fetch a cached session or create one if this is the first request this
-	// process has seen.
-	session, err := h.getSession(ctx, ws)
+	// Remove the session from the cache, this will force a new session to be
+	// generated and cached.
+	h.cache.remove(ws.GetName())
```
Comment (r0mant) [inline lib/web/app/handler.go:197]: If multiple requests reach here simultaneously, what happens? Can one nuke the session created by the other?

File: lib/web/app/transport.go [hunk 8]
```diff
@@ -159,39 +165,62 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
+// DialContext
+func (t *transport) DialContext(ctx context.Context, _ string, _ string) (net.Conn, error) {
+	t.mu.Lock()
+	defer t.mu.Unlock()
+
+	for i := len(t.c.servers) - 1; i >= 0; i-- {
+		conn, err := dialAppServer(t.c.proxyClient, t.c.identity, t.c.servers[i])
 		if err != nil {
+			// Connection problem with the server.
+			if trace.IsConnectionProblem(err) {
```
Comment (r0mant) [inline lib/web/app/transport.go:177]: Similar to above, can we only check for reverse tunnel connection error specifically to avoid inadvertently retrying requests we shouldn't retry?

File: lib/web/app/transport.go [hunk 9]
```diff
@@ -159,39 +165,62 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
+				t.c.log.Warnf("failed to connect to app server: %v.", err)
+
+				// remove the failed server from the list.
+				t.c.servers = append(t.c.servers[:i], t.c.servers[i+1:]...)
```
Comment (r0mant) [inline lib/web/app/transport.go:181]: If you kept `servers` in a map, keyed by e.g. server ID, it would be easier to remove them and you wouldn't need to lock the entire function as per my comment above.

File: lib/web/app/transport.go (hunk 1 above)
Comment (r0mant) [reply lib/web/app/transport.go:173]: I would shuffle here as well, to avoid relying on some external behavior.

File: lib/web/app/transport.go [hunk 10]
```diff
@@ -159,39 +165,62 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
+func (t *transport) DialContext(ctx context.Context, _ string, _ string) (net.Conn, error) {
+	t.mu.Lock()
+	defer t.mu.Unlock()
+
+	for i := len(t.c.servers) - 1; i >= 0; i-- {
+		conn, err := dialAppServer(t.c.proxyClient, t.c.identity, t.c.servers[i])
 		if err != nil {
+			// Connection problem with the server.
+			if trace.IsConnectionProblem(err) {
+				t.c.log.Warnf("failed to connect to app server: %v.", err)
```
Comment (r0mant) [inline lib/web/app/transport.go:178]:
```suggestion
				t.c.log.Warnf("Failed to connect to app server: %v.", err)
```

Also, add server ID to the message.

File: lib/web/app/transport.go [hunk 11]
```diff
@@ -159,39 +165,62 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
+
 			return nil, trace.Wrap(err)
 		}
-		// App access connections over reverse tunnel use mutual TLS.
-		return tls.Client(conn, tr.TLSClientConfig), nil
+
+		return conn, nil
 	}
+
+	return nil, trace.ConnectionProblem(fmt.Errorf("no servers remaining to connect"), "")
```
Comment (r0mant) [inline lib/web/app/transport.go:191]:
```suggestion
	return nil, trace.ConnectionProblem(nil, "no application servers remaining to connect")
```

**Review by r0mant — CHANGES_REQUESTED** [review]

File: lib/web/app/handler.go [hunk 12]
```diff
@@ -171,6 +206,23 @@ func (h *Handler) authenticate(ctx context.Context, r *http.Request) (*session,
...
+	sessionID, err := h.extractSessionID(r)
+	if err != nil {
+		h.log.Warnf("Failed to extract session id: %v.", err)
+		return nil, trace.AccessDenied("invalid session")
+	}
+
+	// Check that the session exists in the backend cache. This allows the user
+	// to logout and invalidate their application session immediately. This
+	// lookup should also be fast because it's in the local cache.
+	return h.c.AccessPoint.GetAppSession(r.Context(), types.GetAppSessionRequest{
```
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply lib/web/app/handler.go:221]: [This behavior hasn't changed in this PR](https://github.com/gravitational/teleport/blob/master/lib/web/app/handler.go#L155), it was just moved to a separated function to be reused.

Not sure if I got your point. Do you mean the `AccessPoint` cache or the [sessions cache](https://github.com/gravitational/teleport/blob/master/lib/web/app/handler.go#L86)?

File: lib/web/app/transport.go [hunk 13]
```diff
@@ -159,39 +165,62 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
-// service over the reverse tunnel subsystem.
-func dialFunc(c *transportConfig) func(ctx context.Context, network string, addr string) (net.Conn, error) {
-	return func(ctx context.Context, network string, addr string) (net.Conn, error) {
-		clusterClient, err := c.proxyClient.GetSite(c.identity.RouteToApp.ClusterName)
-		if err != nil {
-			return nil, trace.Wrap(err)
-		}
+// DialWebsocket dials a websocket connection over the transport's reverse
+// tunnel.
+func (t *transport) DialWebsocket(network, address string) (net.Conn, error) {
```
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply lib/web/app/transport.go:196]: Only if we [update the Oxy library](https://github.com/gravitational/oxy/blob/master/forward/fwd.go#L260) to use the `DialContext` format for WebSocket. [Currently it uses the `Dial` without context.](https://github.com/gravitational/oxy/blob/master/forward/fwd.go#L49)

File: lib/web/app/handler.go (hunk 7 above)
Comment (gabrielcorado) [reply lib/web/app/handler.go:197]: If they are from the same `AppSession`, both requests will remove the same session and generate a new one later.

> Can one nuke the session created by the other?
Yes. It will create a scenario that we already have in the authentication flow where two requests are executed at the same time when there is no cached session: one request will overwrite the session generated by the other.

Although subsequent requests are not affected by this scenario, do you think we should avoid it?

File: lib/web/app/handler.go [hunk 14]
```diff
@@ -140,29 +141,63 @@ func (h *Handler) handleForward(w http.ResponseWriter, r *http.Request, session
 	return nil
 }
 
+// handleForwardError when the forwarder has an error during the `ServeHTTP` it
+// will calll this function. This handler will then renew the session in order
+// to get "fresh" app servers, and then will forwad the request to the newly
+// created session.
+func (h *Handler) handleForwardError(w http.ResponseWriter, req *http.Request, err error) {
+	if !trace.IsConnectionProblem(err) && err != io.EOF {
```
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply lib/web/app/handler.go:149]: I agree with you. `ConnectionProblem` error should be enough here since it is the error that comes from the `DialContext` function. I'll update it.

File: lib/web/app/transport.go (hunk 8 above)
Comment (gabrielcorado) [reply lib/web/app/transport.go:177]: Can the `ConnectionProblem` error happen in other scenarios? [Looking at the code](https://github.com/gravitational/teleport/blob/master/lib/reversetunnel/localsite.go#L328) it seems to be the correct error to check for reverse tunnel connectivity issues.

File: lib/web/app/transport.go [hunk 15]
```diff
@@ -159,39 +165,62 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
 
-// websocketsDialer returns a function that dials a websocket connection
-// over the transport's reverse tunnel.
-func websocketsDialer(tr *http.Transport) forward.Dialer {
-	return func(network, address string) (net.Conn, error) {
-		conn, err := tr.DialContext(context.Background(), network, address)
+// DialContext
+func (t *transport) DialContext(ctx context.Context, _ string, _ string) (net.Conn, error) {
+	t.mu.Lock()
+	defer t.mu.Unlock()
```
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply lib/web/app/transport.go]: I've changed the servers list to a `sync.Map` (since it performs write operations) to reduce lock contention, and now the dials won't be done during locks.

File: lib/web/app/match.go [hunk 16]
```diff
@@ -39,51 +40,70 @@ type Getter interface {
...
 			as = append(as, server)
 		}
 	}
 
-	if len(as) == 0 {
-		return nil, trace.NotFound("failed to match application")
-	}
+	// if len(as) == 0 {
+	// 	return nil, trace.NotFound("failed to match applications")
+	// }
```
Comment (smallinsky) [inline lib/web/app/match.go:61]: uncomment or remove ?

File: lib/web/app/transport.go [hunk 17]
```diff
@@ -83,32 +86,42 @@ type transport struct {
 	// tr is used for forwarding http connections.
 	tr http.RoundTripper
 
-	// dialer is used for forwarding websocket connections.
-	dialer forward.Dialer
+	// clientTLSConfig is the TLS config used for mutual authentication.
+	clientTLSConfig *tls.Config
+
+	// servers servers that the transport can connect to organized in a map
```
Comment (smallinsky) [inline lib/web/app/transport.go:92]: typo

File: lib/web/app/match.go (hunk 16 above)
Comment (gabrielcorado) [reply lib/web/app/match.go]: Removed.

File: lib/web/app/session.go (hunk 2 above)
Comment (gabrielcorado) [reply lib/web/app/session.go:72]: Done.

File: lib/web/app/transport.go [hunk 18]
```diff
@@ -159,39 +173,78 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
-// service over the reverse tunnel subsystem.
-func dialFunc(c *transportConfig) func(ctx context.Context, network string, addr string) (net.Conn, error) {
-	return func(ctx context.Context, network string, addr string) (net.Conn, error) {
-		clusterClient, err := c.proxyClient.GetSite(c.identity.RouteToApp.ClusterName)
-		if err != nil {
-			return nil, trace.Wrap(err)
+	t.servers.Range(func(serverID interface{}, appServerInterface interface{}) bool {
+		appServer, ok := appServerInterface.(types.AppServer)
+		if !ok {
+			return true
```
Comment (smallinsky) [inline lib/web/app/transport.go:185]: log warn

File: lib/web/app/handler.go (hunk 7 above)
Comment (smallinsky) [reply lib/web/app/handler.go:198]: Based on current code I think that handling this situation seems to be "safe". The  `h.cache.remove` called from other goroutine will remove previously  inserted by other goroutine but the new session will be inserted. 
The only concerns that comes to my mind is performance impact because newSession  flow tries to dial all app services to check it services are healthy. 

So maybe we should consider using something like https://pkg.go.dev/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight that allows to block simultaneous code executed based on a key but this probably be done in a separate ticket/PR.

File: integration/app_integration_test.go [hunk 19]
```diff
@@ -871,7 +957,7 @@ func setupWithOptions(t *testing.T, opts appTestOptions) *pack {
 	rcConf := service.MakeDefaultConfig()
 	rcConf.Console = nil
 	rcConf.Log = log
-	rcConf.DataDir, err = ioutil.TempDir("", "cluster-"+p.rootCluster.Secrets.SiteName)
+	rcConf.DataDir, err = os.MkdirTemp("", "cluster-"+p.rootCluster.Secrets.SiteName)
```
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply integration/app_integration_test.go:960]: As far as I understand, each cluster needs its own `DataDir,` so we create a temporary directory based on `SiteName` [(which is the `ClusterName`)](https://github.com/gravitational/teleport/blob/master/integration/helpers.go#L251). I can update this line actually to use the `ClusterName`. Do you think it will be clear?

File: lib/web/app/handler.go [hunk 20]
```diff
@@ -140,29 +141,64 @@ func (h *Handler) handleForward(w http.ResponseWriter, r *http.Request, session
...
+}
+
 // authenticate will check if request carries a session cookie matching a
 // session in the backend.
 func (h *Handler) authenticate(ctx context.Context, r *http.Request) (*session, error) {
-	sessionID, err := h.extractSessionID(r)
+	ws, err := h.getAppSession(r)
 	if err != nil {
-		h.log.Warnf("Failed to extract session id: %v.", err)
+		h.log.Debugf("Failed to fetch application session: %v.", err)
```
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply lib/web/app/handler.go:171]: It should be `Warnf`.

File: integration/app_integration_test.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (gabrielcorado) [reply integration/app_integration_test.go:960]: We can use it since every call returns a different directory.

From [TempDir documentation](https://pkg.go.dev/testing#T.TempDir):
> Each subsequent call to t.TempDir returns a unique directory;

File: integration/app_integration_test.go [hunk 21]
```diff
@@ -918,64 +1002,17 @@ func setupWithOptions(t *testing.T, opts appTestOptions) *pack {
...
-	raConf.DataDir, err = ioutil.TempDir("", "app-server-"+p.rootCluster.Secrets.SiteName)
-	require.NoError(t, err)
-	t.Cleanup(func() { os.RemoveAll(raConf.DataDir) })
-	raConf.Token = "static-token-value"
-	raConf.AuthServers = []utils.NetAddr{
-		{
-			AddrNetwork: "tcp",
-			Addr:        net.JoinHostPort(Loopback, p.rootCluster.GetPortWeb()),
-		},
+	// at least one rootAppServer should start during the setup
```
Comment (smallinsky) [inline integration/app_integration_test.go:1005]:
```suggestion
	// At least one rootAppServer should start during the setup
```

File: integration/app_integration_test.go [hunk 22]
```diff
@@ -633,6 +632,92 @@ func TestAppAuditEvents(t *testing.T) {
...
+			status, err = test.makeRequest(pack, inCookie)
+			responseWithoutError(t, status, err)
+
+			// start an additional app server and stop all current running
+			// ones.
+			pack.startRootAppServers(t, 1, []service.App{})
+			for _, appServer := range servers {
+				appServer.Close()
+
+				// everytime a app server stops we issue an request to
```
Comment (smallinsky) [inline integration/app_integration_test.go:711]:
```suggestion
				// Everytime an app server stops we issue a request to
```

File: integration/app_integration_test.go [hunk 23]
```diff
@@ -633,6 +632,92 @@ func TestAppAuditEvents(t *testing.T) {
...
+					// server.
+					responseWithoutError(t, status, err)
+				}
+			}
+
+			servers := pack.startRootAppServers(t, 3, []service.App{})
+			status, err = test.makeRequest(pack, inCookie)
+			responseWithoutError(t, status, err)
+
+			// start an additional app server and stop all current running
```
Comment (smallinsky) [inline integration/app_integration_test.go:705]:
```suggestion
			// Start an additional app server and stop all current running
```

File: integration/app_integration_test.go [hunk 24]
```diff
@@ -633,6 +632,92 @@ func TestAppAuditEvents(t *testing.T) {
...
+
+	for name, test := range testCases {
+		t.Run(name, func(t *testing.T) {
+			pack := setupWithOptions(t, appTestOptions{rootAppServersCount: 3})
+			inCookie := pack.createAppSession(t, test.publicAddr(pack), pack.rootAppClusterName)
+
+			status, err := test.makeRequest(pack, inCookie)
+			responseWithoutError(t, status, err)
+
+			// stop all root app servers
```
Comment (smallinsky) [inline integration/app_integration_test.go:685]:
```suggestion
			// Stop all root app servers.
```

File: lib/web/app/transport.go [hunk 25]
```diff
@@ -159,39 +173,79 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
-// service over the reverse tunnel subsystem.
-func dialFunc(c *transportConfig) func(ctx context.Context, network string, addr string) (net.Conn, error) {
-	return func(ctx context.Context, network string, addr string) (net.Conn, error) {
-		clusterClient, err := c.proxyClient.GetSite(c.identity.RouteToApp.ClusterName)
-		if err != nil {
-			return nil, trace.Wrap(err)
+	t.servers.Range(func(serverID interface{}, appServerInterface interface{}) bool {
+		appServer, ok := appServerInterface.(types.AppServer)
+		if !ok {
+			t.c.log.Warnf("Failed load AppServer, invalid type %T", appServerInterface)
```
Comment (smallinsky) [inline lib/web/app/transport.go:185]:
```suggestion
			t.c.log.Warnf("Failed to load AppServer, invalid type %T", appServerInterface)
```

**Review by smallinsky — APPROVED** [review]
Left some minor formatting nit comments. I think that there is one open issues 
https://github.com/gravitational/teleport/pull/9288/files#discussion_r768280901 that needs to be confirmed by @r0mant. Otherwise, LGTM

File: lib/web/app/transport.go [hunk 26]
```diff
@@ -159,39 +173,79 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
+	var conn net.Conn
 
-// dialFunc returns a function that can Dial and connect to the application
-// service over the reverse tunnel subsystem.
-func dialFunc(c *transportConfig) func(ctx context.Context, network string, addr string) (net.Conn, error) {
-	return func(ctx context.Context, network string, addr string) (net.Conn, error) {
-		clusterClient, err := c.proxyClient.GetSite(c.identity.RouteToApp.ClusterName)
-		if err != nil {
-			return nil, trace.Wrap(err)
+	t.servers.Range(func(serverID interface{}, appServerInterface interface{}) bool {
```
Comment (r0mant) [inline lib/web/app/transport.go:182]:
```suggestion
	t.servers.Range(func(serverID, appServerInterface interface{}) bool {
```

File: lib/web/app/transport.go [hunk 27]
```diff
@@ -159,39 +173,79 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
-		if err != nil {
-			return nil, trace.Wrap(err)
-		}
-		// App access connections over reverse tunnel use mutual TLS.
-		return tls.Client(conn, tr.TLSClientConfig), nil
-	}
-}
+// DialContext dials and connect to the application service over the reverse
+// tunnel subsystem.
+func (t *transport) DialContext(ctx context.Context, _ string, _ string) (net.Conn, error) {
```
Comment (r0mant) [inline lib/web/app/transport.go:178]:
```suggestion
func (t *transport) DialContext(ctx context.Context, _, _ string) (net.Conn, error) {
```

File: lib/web/app/transport.go [hunk 28]
```diff
@@ -159,39 +173,79 @@ func (t *transport) rewriteRequest(r *http.Request) error {
...
-			ConnType: types.AppTunnel,
-		})
-		if err != nil {
-			return nil, trace.Wrap(err)
+		var dialErr error
+		conn, dialErr = dialAppServer(t.c.proxyClient, t.c.identity, appServer)
+		if dialErr != nil {
+			// Connection problem with the server.
+			if trace.IsConnectionProblem(dialErr) {
+				t.c.log.Warnf("Failed to connect to application server \"%d\": %v.", serverID, dialErr)
```
Comment (r0mant) [inline lib/web/app/transport.go:194]:
```suggestion
				t.c.log.Warnf("Failed to connect to application server %q: %v.", serverID, dialErr)
```

**Review by r0mant — APPROVED** [review]
@gabrielcorado lgtm. Have you tested this fix in the Kubernetes rolling update scenario? To make sure app access keeps working when a Teleport app agent pod gets deleted and another one spinned up during K8s deployment rolling update? Let's please make sure it works in that scenario before merging.

Also, please backport to branch/v8 after this gets merged.

**Comment by gabrielcorado** [comment]
@r0mant Yes, I tested this scenario with app agents deployed in Kubernetes using the Helm chart (`teleport-kube-agent`), and everything worked as expected, with no downtime during rollouts.
