### PR TITLE
Fix flaky operator TeleportUserUpdate test

### LINKED ISSUE #63759: `TestUserUpdate` flakiness
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/21952175132/job/63405769188?pr=55940

#### Relevant snippet

```
=== Failed
=== FAIL: integrations/operator/controllers/resources TestUserUpdate (0.53s)
    user_controller_test.go:395: 
        	Error Trace:	/__w/teleport/teleport/integrations/operator/controllers/resources/user_controller_test.go:395
        	Error:      	Received unexpected error:
        	            	resource revision does not match, it may have been concurrently created|modified|deleted; please work from the latest state, or use --force to overwrite
        	Test:       	TestUserUpdate
```

### PR DESCRIPTION
**Pull request by hugoShaka**
Fixes: https://github.com/gravitational/teleport/issues/63759

The synchronous update operator test was only comparing resource spec to know if a resource got propagated into cache.

However, some updates were not changing the spec (only bumping the revision), hence the operator tests were not waiting for them properly. This allowed the test to proceed while the cache was not up-to-date yet, causing the operator to read stale data and face a conflict when calling the update RPC.

This fix waits for the revision to change before allowing the test to continue. With both the spec and revision change check, we are more confident that the previous reconciliation change entered the cache.

### CODE REVIEW

File: integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go [hunk 1]
```diff
@@ -89,7 +89,7 @@ func ResourceUpdateTestSynchronous[T reconcilers.Resource, K reconcilers.Kuberne
 
 	// Test setup: Wait for the CR to be served by Kubernetes, fail early if Kubernetes is broken.
 	FastEventuallyWithT(t, func(t *assert.CollectT) {
-		_, err := test.GetKubernetesResource(ctx, resourceName)
+		_, err = test.GetKubernetesResource(ctx, resourceName)
```
Comment (tigrato) [inline integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go]: why do you need the error assigned to the outside?

Comment (hugoShaka) [reply integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go]: I don't. That's a leftover of a test I did.
```suggestion
		_, err := test.GetKubernetesResource(ctx, resourceName)
```

File: integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go [hunk 2]
```diff
@@ -298,15 +302,16 @@ func ResourceDeletionSynchronousTest[T reconcilers.Resource, K reconcilers.Kuber
...
 		require.NoError(t, err)
 
 		kubeResource, err := test.GetKubernetesResource(ctx, resourceName)
 		require.NoError(t, err)
 
 		// Kubernetes and Teleport resources are in-sync
-		equal, diff := test.CompareTeleportAndKubernetesResource(tResource, kubeResource)
+		equal, diff := test.CompareTeleportAndKubernetesResource(reconciledResource, kubeResource)
 		require.True(t, equal, "Kubernetes and Teleport resources not sync-ed yet: %s", diff)
+		require.NotEqual(t, test.GetResourceRevision(tResource), test.GetResourceRevision(reconciledResource), "Teleport resource revision did not change.")
```
Comment (hugoShaka) [inline integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go]:
```suggestion
```

File: integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go (hunk 1 above)
Comment (zmb3) [reply integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go]: Looks like we're still assigning to the outer error?

**Review by zmb3 — APPROVED** [review]

File: integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go (hunk 1 above)
Comment (hugoShaka) [reply integrations/operator/controllers/resources/testlib/teleport_reconciler_tests.go]: Yeah, I tried to be smart and use GH suggestions but got github-ed and it closed the comment without applying the diff. I checked out the branch locally and fixed it

**Review by strideynet — APPROVED** [review]

**Comment by hugoShaka** [comment]
~This fix cannot be merged as-is because the bot service doesn't act like the other services and updating the resource doesn't change the revision. I'll have to put up a more complex fix where the controller reports the expected revision (as opposed to us waiting for a change).~

Edit: added a quick workaround to unblock revisionless resources.

**Comment by hugoShaka** [comment]
Note: finally the PR does not solve the operator trusted cluster race, I'll try to merge it as this completely solves the TeleportUserUpdate one (without the PR I have ~ 10% error rate, with the PR the test passed 600 times in a row).

I'll continue to investigate the TC one.
