### PR TITLE
Handle duplicate node names & support UUID based proxying (Version 2)

### LINKED ISSUE #2396: ssh to wrong node
**What happened**:
When i click the root button from web, ssh to wrong node. ifconfig display the different ip to the Address of web. And it is always ssh to the same wrong node. 

**What you expected to happen**:
SSH to right node.

**How to reproduce it (as minimally and precisely as possible)**:
The Hostname of the wrong node  is the same of all. And Tips：'abrt-cli status' timed out

**Environment**:
- Teleport version (use `teleport version`): v3.0.1
- Tsh version (use `tsh version`): v3.0.1
- OS (e.g. from /etc/os-release):Centos 7.2

**Browser environment**
chrome
- Browser Version (for UI-related issues): 70.0.3538.102
- Install tools: 
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

### PR DESCRIPTION
**Pull request by fspmarshall**
This PR implements an alternative strategy to the original UUID based routing strategy seen in #3340.  Rather than explicitly routing by UUID, this implementation checks if the supplied hostname *appears* to be a UUID and guesses the intended behavior:

```
$ tsh ssh alice@example.com
error: ambiguous host could match multiple nodes
  
Node  Name  Node ID                              Address        Labels
----------- ------------------------------------ -------------- ---------
example.com ae79f375-633e-4a81-941e-83faf4a3c966 127.0.0.1:3022 foo=bar
example.com 17a980a9-ce32-4c95-a5c4-c4b4717851e9 127.0.0.1:4022 spam=eggs            
  
Hint: try addressing the node by unique id (ex: tsh ssh user@node-id)
Hint: use 'tsh ls -v' to list all nodes with their unique ids

$ tsh ssh alice@17a980a9-ce32-4c95-a5c4-c4b4717851e9
```

By treating UUIDS *as* hostnames, this PR is (mostly) much simpler than #3340.  There is, however, one major exception:  because clients treat UUIDs as hostnames, certificates now need to include UUIDs.  This PR is currently a WIP since it does not yet include any mechanism for forcing nodes to get their certificates re-issued with UUIDs.

Fixes #2396

### CODE REVIEW

File: tool/tsh/tsh.go [hunk 1]
```diff
@@ -783,6 +823,22 @@ func onSSH(cf *CLIConf) {
...
+			}
+			var nodes []services.Server
+			for _, node := range allNodes {
+				if node.GetHostname() == tc.Host {
+					nodes = append(nodes, node)
+				}
+			}
+			fmt.Fprintf(os.Stderr, "error: ambiguous host could match multiple nodes\n\n")
+			showNodes(nodes, true)
+			fmt.Fprintf(os.Stderr, "Hint: try addressing the node by unique id (ex: tctl ssh user@node-id)\n")
```
Comment (webvictim) [inline tool/tsh/tsh.go]: Maybe we can add a hint here to tell people how to do this again if they need to, something like: "To show node UUIDs in future, run `'tsh ls -v'`" (or whatever the command is)

(and if we aren't exposing this via a flag to `tsh ls`, I think we should be)

**Comment by webvictim** [comment]
Assuming we go with this approach, we should add something to the docs (probably here: https://gravitational.com/teleport/docs/cli-docs/#tctl-auth-rotate) describing what an in-place rotation is, what it does, what it doesn't do and when you might want to use it.

**Comment by fspmarshall** [comment]
> Assuming we go with this approach, we should add something to the docs (probably here: https://gravitational.com/teleport/docs/cli-docs/#tctl-auth-rotate) describing what an in-place rotation is, what it does, what it doesn't do and when you might want to use it.

The rotate-in-place strategy has been shelved for now.  We're opting to have nodes check their certs on startup instead.

File: lib/web/terminal.go [hunk 2]
```diff
@@ -291,6 +299,20 @@ func (t *TerminalHandler) streamTerminal(ws *websocket.Conn, tc *client.Teleport
 	// Establish SSH connection to the server. This function will block until
 	// either an error occurs or it completes successfully.
 	err := tc.SSH(t.terminalContext, t.params.InteractiveCommand, false)
+
+	// TODO IN: 5.0
+	//
+	// Make connecting by UUID the default instead of the fallback.
+	//
+	if err != nil && strings.Contains(err.Error(), teleport.ServerIsAmbiguous) {
+		t.log.Infof("Ambiguous hostname %q, attempting to connect by UUID (%q)", t.hostName, t.hostUUID)
```
Comment (russjones) [inline lib/web/terminal.go]: I would make this debug, we might flood customer logs with this line.

File: lib/service/service.go [hunk 3]
```diff
@@ -555,6 +555,10 @@ func NewTeleport(cfg *Config) (*TeleportProcess, error) {
 		}
 	}
 
+	if uuid.Parse(cfg.HostUUID) == nil {
+		log.Warnf("Host UUID %q is not a true UUID (may interfere with some functionality)", cfg.HostUUID)
```
Comment (russjones) [inline lib/service/service.go]: I would explain what could happen if the value in not unique.

```go
log.Warnf("Host UUID %q is not a valid UUID. If the Host UUID value in not unique, this may lead to clients inadvertently connecting to the wrong node.", cfg.HostUUID)
```

**Review by russjones — APPROVED** [review]

File: tool/tsh/tsh.go [hunk 4]
```diff
@@ -783,6 +787,24 @@ func onSSH(cf *CLIConf) {
...
+			var nodes []services.Server
+			for _, node := range allNodes {
+				if node.GetHostname() == tc.Host {
+					nodes = append(nodes, node)
+				}
+			}
+			fmt.Fprintf(os.Stderr, "error: ambiguous host could match multiple nodes\n\n")
+			showNodes(nodes, true)
+			fmt.Fprintf(os.Stderr, "Hint: try addressing the node by unique id (ex: tsh ssh user@node-id)\n")
+			fmt.Fprintf(os.Stderr, "Hint: use 'tsh ls -v' to list all nodes with their unique ids\n")
```
Comment (benarent) [inline tool/tsh/tsh.go]: 👍 Hints look good.

**Comment by fspmarshall** [comment]
retest this please

File: constants.go [hunk 5]
```diff
@@ -566,6 +566,10 @@ const (
 	// UseOfClosedNetworkConnection is a special string some parts of
 	// go standard lib are using that is the only way to identify some errors
 	UseOfClosedNetworkConnection = "use of closed network connection"
+
+	// ServerIsAmbiguous serves as an identifying error string indicating that
+	// the proxy subsystem found multiple nodes matching the specified hostname.
+	ServerIsAmbiguous = "err-server-is-ambiguous"
```
Comment (benarent) [inline constants.go]: I think we should change this to `NodeIsAmbiguous  = "err-node-is-ambiguous"` to keep consistent.

File: lib/reversetunnel/localsite.go [hunk 6]
```diff
@@ -153,6 +153,10 @@ func (s *localSite) DialAuthServer() (conn net.Conn, err error) {
 		return nil, trace.Wrap(err)
 	}
 
+	if len(authServers) < 1 {
+		return nil, trace.ConnectionProblem(nil, "no auth servers available")
```
Comment (benarent) [inline lib/reversetunnel/localsite.go]: Same here `no auth nodes available`

**Review by benarent — APPROVED** [review]
I left a few comments. I know in the past we've used server, but we should aim to use node/nodes vs servers for consistently.  It's most important for log messages and user facing input.

File: lib/reversetunnel/localsite.go (hunk 6 above)
Comment (fspmarshall) [reply lib/reversetunnel/localsite.go]: From what I can tell, it appears that we typically refer to the `ssh_service` as a node, but always use `server` when referring to the `auth_service` (e.g. `tctl --auth-server=example.com`).

Comment (benarent) [reply lib/reversetunnel/localsite.go]: 👍 Yeah. I see what you mean.. I was just running `tctl status --auth-server=`

**Comment by fspmarshall** [comment]
retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please

**Comment by russjones** [comment]
@gravitational-jenkins retest this please
