### PR TITLE
Fix parsing Kubernetes Resources without `GroupVersionKind`

### LINKED ISSUE #37972: `Object 'Kind' is missing` on Teleport 14.x and above when using Lens "Node Shell"
### Expected behavior:

Using the Node Shell button should work.

### Current behavior:

When launching the node shell via Teleport 14.x and newer, it displays this error:

```
Error ocurred: Object 'Kind' is missing in
'{"metadata":{"name":"node-shell-9725bc39-963b-440e-958a-5e9f32883f78","namespace":"kube-system"},"spec":{"containers":\[{"args":\["-t","1","-m","-u","-i","-n","sleep","14000"\],"command":\["nsenter"\],"image":"docker.io/alpine:3.13","name":"shell","securityContext":{"privileged":true}}\],"hostIPC":true,"hostNetwork":true,"hostPID":true,"nodeName":"mynode","priorityClassName":"system-node-critical","restartPolicy":"Never","terminationGracePeriodSeconds":0,"tolerations":\[{"operator":"Exists"}\]}}'
```

### Additional info

When using the Lens "Node Shell" button, it will create a pod by sending a POST to create a pod, and then it will run an `exec` command to actually start the shell. The JSON document that Lens generates and sends the POST is quite minimal, and is accurately reflected in the error message.

I tested OpenLens with the https://github.com/alebcay/openlens-node-pod-menu extension enabled, and I was able to confirm that when using the "Node Shell" option, that same short POST document is successful with Teleport 13, and direct to the Kubernetes API service. I set up an authenticated tunnel and used `tcpdmup` to inspect the raw request that was sent by lens. In both cases, the CREATE document is identical.

```
POST /api/v1/namespaces/kube-system/pods HTTP/1.1
Host: 127.0.0.1:6480
Content-Length: 493
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{"metadata":{"name":"node-shell-c85cd118-f906-1867-63dc-bd2d99bd5c17","namespace":"kube-system"},"spec":{"containers":[{"args":["-t","1","-m","-u","-i","-n","sleep","14000"],"command":["nsenter"],"image":"docker.io/alpine:3.13","name":"shell","securityContext":{"privileged":true}}],"hostIPC":true,"hostNetwork":true,"hostPID":true,"nodeName":"mynode","priorityClassName":"system-node-critical","restartPolicy":"Never","terminationGracePeriodSeconds":0,"tolerations":[{"operator":"Exists"}]}}
```

The full stack trace as seen in my `teleport-auth` pod in my `teleport-cluster` helm release (where the `kubernetes_service` runs):

<details>
<summary>Click to expand</summary>

```
teleport-proxy-598b747c75-bkbxj teleport 2024-02-08T21:47:04Z INFO [PROXY:PRO] Round trip: POST https://kube-teleport-proxy-alpn.teleport.cluster.local/api/v1/namespaces/kube-system/pods, code: 500, duration: 5.329631ms tls:version: 304, tls:resume:false, tls:csuite:1301, tls:server:kube-teleport-proxy-alpn.teleport.example.com pid:8.1 reverseproxy/reverse_proxy.go:221
teleport-auth-7cb8bb5476-dc846 teleport 2024-02-08T21:47:04Z WARN [KUBERNETE] Unable to setup context. error:[
teleport-auth-7cb8bb5476-dc846 teleport ERROR REPORT:
teleport-auth-7cb8bb5476-dc846 teleport Original Error: *runtime.missingKindErr Object &#39;Kind&#39; is missing in &#39;{&#34;metadata&#34;:{&#34;name&#34;:&#34;node-shell-9725bc39-963b-440e-958a-5e9f32883f78&#34;,&#34;namespace&#34;:&#34;kube-system&#34;},&#34;spec&#34;:{&#34;containers&#34;:[{&#34;args&#34;:[&#34;-t&#34;,&#34;1&#34;,&#34;-m&#34;,&#34;-u&#34;,&#34;-i&#34;,&#34;-n&#34;,&#34;sleep&#34;,&#34;14000&#34;],&#34;command&#34;:[&#34;nsenter&#34;],&#34;image&#34;:&#34;docker.io/alpine:3.13&#34;,&#34;name&#34;:&#34;shell&#34;,&#34;securityContext&#34;:{&#34;privileged&#34;:true}}],&#34;hostIPC&#34;:true,&#34;hostNetwork&#34;:true,&#34;hostPID&#34;:true,&#34;nodeName&#34;:&#34;mynode&#34;,&#34;priorityClassName&#34;:&#34;system-node-critical&#34;,&#34;restartPolicy&#34;:&#34;Never&#34;,&#34;terminationGracePeriodSeconds&#34;:0,&#34;tolerations&#34;:[{&#34;operator&#34;:&#34;Exists&#34;}]}}&#39;
teleport-auth-7cb8bb5476-dc846 teleport Stack Trace:
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/kube/proxy/resource_filters.go:731 github.com/gravitational/teleport/lib/kube/proxy.decodeAndSetGVK
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/kube/proxy/url.go:280 github.com/gravitational/teleport/lib/kube/proxy.extractResourceNameFromPostRequest
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/kube/proxy/url.go:239 github.com/gravitational/teleport/lib/kube/proxy.getResourceFromRequest
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:842 github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).parseResourceFromRequest
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:775 github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).setupContext
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:541 github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).authenticate
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:566 github.com/gravitational/teleport/lib/kube/proxy.NewForwarder.(*Forwarder).withAuthStd.func6
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/httplib/httplib.go:145 github.com/gravitational/teleport/lib/kube/proxy.NewForwarder.(*Forwarder).withAuthStd.MakeStdHandlerWithErrorWriter.func8
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/julienschmidt/httprouter@v1.3.0/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/prometheus/client_golang@v1.17.0/prometheus/promhttp/instrument_server.go:296 github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerResponseSize.func1
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/prometheus/client_golang@v1.17.0/prometheus/promhttp/instrument_server.go:147 github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/prometheus/client_golang@v1.17.0/prometheus/promhttp/instrument_server.go:109 github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/prometheus/client_golang@v1.17.0/prometheus/promhttp/instrument_server.go:60 github.com/gravitational/teleport/lib/kube/proxy.instrumentHTTPHandlerWithPrometheus.InstrumentHandlerInFlight.func1
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:229 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:81 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/kube/proxy/forwarder.go:398 github.com/gravitational/teleport/lib/kube/proxy.(*Forwarder).ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/auth/middleware.go:701 github.com/gravitational/teleport/lib/auth.(*Middleware).ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/oxy@v0.0.0-20221029012416-9fbf4c444680/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	github.com/gravitational/teleport/lib/httplib/httplib.go:102 github.com/gravitational/teleport/lib/httplib.MakeTracingHandler.func1
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:229 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:81 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2136 net/http.HandlerFunc.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:2938 net/http.serverHandler.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport 	net/http/server.go:3546 net/http.initALPNRequest.ServeHTTP
teleport-auth-7cb8bb5476-dc846 teleport User Message: Object &#39;Kind&#39; is missing in &#39;{&#34;metadata&#34;:{&#34;name&#34;:&#34;node-shell-9725bc39-963b-440e-958a-5e9f32883f78&#34;,&#34;namespace&#34;:&#34;kube-system&#34;},&#34;spec&#34;:{&#34;containers&#34;:[{&#34;args&#34;:[&#34;-t&#34;,&#34;1&#34;,&#34;-m&#34;,&#34;-u&#34;,&#34;-i&#34;,&#34;-n&#34;,&#34;sleep&#34;,&#34;14000&#34;],&#34;command&#34;:[&#34;nsenter&#34;],&#34;image&#34;:&#34;docker.io/alpine:3.13&#34;,&#34;name&#34;:&#34;shell&#34;,&#34;securityContext&#34;:{&#34;privileged&#34;:true}}],&#34;hostIPC&#34;:true,&#34;hostNetwork&#34;:true,&#34;hostPID&#34;:true,&#34;nodeName&#34;:&#34;mynode&#34;,&#34;priorityClassName&#34;:&#34;system-node-critical&#34;,&#34;restartPolicy&#34;:&#34;Never&#34;,&#34;terminationGracePeriodSeconds&#34;:0,&#34;tolerations&#34;:[{&#34;operator&#34;:&#34;Exists&#34;}]}}&#39;] pid:7.2 proxy/forwarder.go:543
teleport-auth-7cb8bb5476-dc846 teleport 2024-02-08T21:47:04Z DEBU [KUBERNETE] Handling kubernetes session for user: jeff, users: map[jeff:{}], groups: map[system:authenticated:{} system:masters:{}], teleport cluster: teleport.example.com, kube cluster: kessler using local credentials. pid:7.2 proxy/forwarder.go:2325
teleport-auth-7cb8bb5476-dc846 teleport 2024-02-08T21:47:04Z INFO [KUBERNETE] Round trip: DELETE https://10.43.0.1:443/api/v1/namespaces/kube-system/pods/node-shell-9725bc39-963b-440e-958a-5e9f32883f78, code: 404, duration: 12.681838ms tls:version: 304, tls:resume:false, tls:csuite:1301, tls:server:kube-teleport-proxy-alpn.teleport.cluster.local pid:7.2 reverseproxy/reverse_proxy.go:221
teleport-proxy-598b747c75-bkbxj teleport 2024-02-08T21:47:04Z INFO [PROXY:PRO] Round trip: DELETE https://kube-teleport-proxy-alpn.teleport.cluster.local/api/v1/namespaces/kube-system/pods/node-shell-9725bc39-963b-440e-958a-5e9f32883f78, code: 404, duration: 19.634582ms tls:version: 304, tls:resume:false, tls:csuite:1301, tls:server:kube-teleport-proxy-alpn.teleport.example.com pid:8.1 reverseproxy/reverse_proxy.go:221
teleport-auth-7cb8bb5476-dc846 teleport 2024-02-08T21:47:04Z INFO [AUDIT]     kube.request addr.remote:203.0.113.183:62697 cluster_name:teleport.example.com code:T3009I ei:0 event:kube.request kubernetes_cluster:kessler kubernetes_groups:[system:masters system:authenticated] kubernetes_users:[jeff] login:jeff namespace:default proto:kube request_path:/api/v1/namespaces/kube-system/pods/node-shell-9725bc39-963b-440e-958a-5e9f32883f78 resource_api_group:core/v1 resource_kind:pods resource_name:node-shell-9725bc39-963b-440e-958a-5e9f32883f78 resource_namespace:kube-system response_code:404 server_id:b67414b6-cca6-4d3c-f884-4aacf3b18b29 sid: time:2024-02-08T21:47:04.237Z uid:d700c195-e371-b245-eaea-a28c48fb8f47 user:jeff user_kind:1 verb:DELETE events/emitter.go:274
```

</details>

Notably, the `github.com/gravitational/teleport/lib/kube/proxy/resource_filters.go` file that is at the top of the stack trace is new in Teleport 14.x, and was introduced in https://github.com/gravitational/teleport/pull/26244

### PR DESCRIPTION
**Pull request by tigrato**
Kubernetes API has a concept of `GroupVersionKind` where each payload includes the type identification `(group, version, kind)` that uniquely identifies the resource structure withing Kubernetes itself.

Kubernetes API and `kubectl` always honor this information but custom tools and tools that use equivalents of `json.Marshal` without setting the `GVK` data fail to be decoded when decoding `CREATE` requests targeted to support kinds through Teleport.

This PR aims to fix that by providing an hint to the Kubernetes decoder that aims to be used as fallback GVK when unmarshaling a payload without the specification.

The hint is provided by the API request path that Teleport extracts from the request URI.

Changelog: Resolved sporadic errors caused by requests fail to comply with Kubernetes API spec by not specifying resource identifiers.

Fixes #37972

### CODE REVIEW

File: lib/kube/proxy/scheme.go [hunk 1]
```diff
@@ -98,17 +98,28 @@ func newClientNegotiator(codecFactory *serializer.CodecFactory) runtime.ClientNe
...
 // This schema includes all well-known Kubernetes types and all namespaced
 // custom resources.
 // It also returns a map of resources that we support RBAC restrictions for.
-func newClusterSchemaBuilder(log logrus.FieldLogger, client kubernetes.Interface) (serializer.CodecFactory, rbacSupportedResources, error) {
+func newClusterSchemaBuilder(log logrus.FieldLogger, client kubernetes.Interface) (serializer.CodecFactory, rbacSupportedResources, gvkSupportedResources, error) {
 	kubeScheme := runtime.NewScheme()
 	kubeCodecs := serializer.NewCodecFactory(kubeScheme)
 	supportedResources := maps.Clone(defaultRBACResources)
-
+	gvkSupportedRes := map[gvkSupportedResourcesKey]*schema.GroupVersionKind{}
```
Comment (AntonAM) [inline lib/kube/proxy/scheme.go:120]:
```suggestion
	gvkSupportedRes := make(gvkSupportedResources)
```

File: lib/kube/proxy/cluster_details.go [hunk 2]
```diff
@@ -64,6 +66,9 @@ type kubeDetails struct {
 	// The list is updated periodically to include the latest custom resources
 	// that are added to the cluster.
 	rbacSupportedTypes rbacSupportedResources
+	// gvkSupportedResources is the list of registered API path resources and their
```
Comment (AntonAM) [inline lib/kube/proxy/cluster_details.go:69]: nit: rwMu description needs to be update to include `gvkSupportedResources`.

**Review by AntonAM — APPROVED** [review]

**Comment by tigrato** [comment]
@zmb3 @fheinecke friendly ping

**Review by zmb3 — APPROVED** [review]
