### PR TITLE
Propagate external traits to leaf clusters

### LINKED ISSUE #6389: Apply trait in leafs as in root
### Description

**What happened**:

Within a root cluster you can specify traits within a `node_label`. This may not be intended functionality but it is currently available.  If you attempt to use that same trait setting within a leaf cluster it will not apply.  

```yaml

kind: role
metadata:
  # insert the name of your role here:
  name: new_role_name
spec:
  # This example defines an administrative role. It maps to Kubernetes "admin"
  # group and allows SSH to every node.
  allow:
    # This role is mapped to Kuberntes 'admin' group.
    kubernetes_groups: [admin]

    # List of allowed SSH logins
    logins: [root]

    # List of node labels that users can SSH into
    node_labels:
      tier: '{{external.env}}'


  # The 'deny' section can have similar settings that override their 'allow' counterparts
  deny:
    logins: ['guest']

  options:
      # Limits user credentials to 8 hours. After the time to live (TTL) expires,
      # users must re-login
      max_session_ttl: 8h0m0s
  # The deny section uses the identical format as the 'allow' section.
  # The deny rules always override allow rules.
  deny: {}
version: v3

```

**What you expected to happen**:

Traits are applied in leafs or there is an option to include existing labels. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Create the same role at the root and leaf cluster
2.map the root role to the leaf
3. attempt to access similar labeled nodes.  it will work at the root but not the leaf

### Server Details
- Teleport version (run `teleport version`): 6.0.2
- Server OS (e.g. from `/etc/os-release`): ubuntu 20.04
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### PR DESCRIPTION
**Pull request by r0mant**
This pull request makes sure that external user traits (usually populated from OIDC/SAML claims/attributes) are propagated to leaf clusters and can be used in leaf role templating. I have extracted this part from the larger AAP headers passthrough work since it felt like this could be a somewhat independent change.

This allows users to have, for example, identical roles in both clusters that grant access based on the user's traits, which is the behavior some customers expect. Example role node labels:

```yaml
node_labels:
  env: {{external.env}}
```

Fixes https://github.com/gravitational/teleport/issues/6389.

### CODE REVIEW

File: lib/auth/permissions.go [hunk 1]
```diff
@@ -139,18 +139,25 @@ func (a *authorizer) authorizeRemoteUser(u RemoteUser) (*Context, error) {
...
 		teleport.TraitKubeUsers:  u.KubernetesUsers,
 		teleport.TraitDBNames:    u.DatabaseNames,
 		teleport.TraitDBUsers:    u.DatabaseUsers,
 	}
+	// Prior to Teleport 6.2 no user traits were passed to remote clusters
+	// except for those specified above. To preserve backwards compatible
+	// behavior, filter out any "internal" traits when applying traits from
+	// user identity.
+	for k, v := range u.Identity.Traits {
+		if !teleport.IsInternalTrait(k) {
```
Comment (awly) [inline lib/auth/permissions.go:157]: optional: you could check whether `k` is already in `traits` instead of using a helper function
that way you have 1 fewer places to maintain "internal" traits

File: integration/integration_test.go [hunk 2]
```diff
@@ -5298,3 +5298,120 @@ func TestWebProxyInsecure(t *testing.T) {
 	require.Equal(t, http.StatusOK, resp.StatusCode)
 	require.NoError(t, resp.Body.Close())
 }
+
+// TestTraitsPropagation makes sure that user traits are applied properly to
+// roles in root and leaf clusters.
+func TestTraitsPropagation(t *testing.T) {
+	log := testlog.FailureOnly(t)
+	startPort := utils.PortStartingNumber + (5 * AllocatePortsNum) + 1
```
Comment (awly) [inline integration/integration_test.go:5306]: why this formula?

**Review by awly — APPROVED** [review]

File: integration/integration_test.go (hunk 2 above)
Comment (r0mant) [reply integration/integration_test.go]: It was needed to avoid conflicts with ports allocated by other tests. It was pretty unfortunate, we would just do it by doing `3*AllocatePortsNum`, `4*AllocatePortsNum` etc. in different tests until now.

I have refactored this to allocate ports for all integration tests once when they start so individual tests/suites don't need to do that anymore. Hopefully we don't run out of ports, I made it 5000 but I don't think our integration tests actually need that many.

File: lib/auth/permissions.go [hunk 3]
```diff
@@ -139,18 +139,25 @@ func (a *authorizer) authorizeRemoteUser(u RemoteUser) (*Context, error) {
...
 	}
+	// Prior to Teleport 6.2 no user traits were passed to remote clusters
+	// except for those specified above. To preserve backwards compatible
+	// behavior, filter out any "internal" traits when applying traits from
+	// user identity.
+	for k, v := range u.Identity.Traits {
+		if _, ok := traits[k]; !ok {
+			traits[k] = v
+		}
+	}
```
Comment (russjones) [inline lib/auth/permissions.go:160]: Two questions:

1. I'm not seeing the filtering out of internal traits mentioned in the comment?
2. When can the second condition be met? Looks like you're just copying the map right? Shouldn't get duplicate keys ever?

File: lib/srv/authhandlers.go [hunk 4]
```diff
@@ -460,13 +450,3 @@ func (h *AuthHandlers) authorityForCert(caType services.CertAuthType, key ssh.Pu
...
-
-// extractRolesFromCert extracts roles from certificate metadata extensions.
-func extractRolesFromCert(cert *ssh.Certificate) ([]string, error) {
-	data, ok := cert.Extensions[teleport.CertExtensionTeleportRoles]
-	if !ok {
-		// it's ok to not have any roles in the metadata
-		return nil, nil
-	}
-	return services.UnmarshalCertRoles(data)
-}
```
Comment (russjones) [inline lib/srv/authhandlers.go:472]: I think this was for old style SSH certificates, do you know if we've dropped support for them?

File: lib/auth/permissions.go (hunk 3 above)
Comment (r0mant) [reply lib/auth/permissions.go:160]: @russjones The filtering is the `if _, ok := traits[k]; !ok {` check - we're basically filtering out any traits which are already present in the `traits` above which contains only internal ones. In my original implementation I had an explicit function IsInternalTrait that would check if the trait is one of the "logins", "kube groups/users" or "db names/users", but then Andrew pointed out that I can check if the key is already in that `traits` map, which I did.

> When can the second condition be met?

Not sure which condition you mean? We're copying traits from the certificate essentially into the `traits` map and skipping internal ones to make sure to preserve backwards compatible behavior.

File: lib/srv/authhandlers.go (hunk 4 above)
Comment (r0mant) [reply lib/srv/authhandlers.go:472]: @russjones This logic is still being used - this was just a duplicate function. [ExtractFromCertificate](https://github.com/gravitational/teleport/blob/v7.0.0-dev.9/lib/services/role.go#L894-L920) does pretty much the same as far as I can tell, unless I'm missing something,

**Review by russjones — APPROVED** [review]
