### PR TITLE
Switch underlying protocol used for 'tsh scp' to SFTP

### LINKED ISSUE #2009: scp transfer progress needs to be more granular
Curently `tsh scp` only updates its stdout after processing each file. From @jddonz :

Would it be possible to add a progress meter to tsh scp similar to ssh scp? Currently there is no feedback that the transfer is in progress, only when it finishes:

```
tsh scp file.tgz user@host:
-> file.tgz (0)
```

For small files this isn't an issue but with larger files it is nice to be able to see the progress.

### LINKED ISSUE #3163: tsh scp to Mac host fails
**What happened**: Running `tsh scp file1.txt build@macmini:/Users/build/Desktop` results in an error: `error: ssh: command /usr/bin/scp -t /Users/build/Desktop failed`

**What you expected to happen**: `tsh scp` to work

**How to reproduce it (as minimally and precisely as possible)**:
1) `tsh login` to a cluster that has a Mac host in
2) Run `tsh scp file1.txt build@macmini:~` and watch the command fail.

I think that the `scp` command on Mac may not have a `-t` flag (at least on MacOS 10.15.1)

**Environment**:
- Teleport version (use `teleport version`): `Teleport v4.1.4 git:v4.1.4-0-gc487a75c go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.1.4 git:v4.1.4-0-gc487a75c go1.13.2`
- OS (e.g. from /etc/os-release): `MacOS 10.15.1` and `Fedora 29` (it doesn't work on either source OS)

```
~ » tsh -d scp file1.txt build@macmini:~
INFO [CLIENT]    no host login given. defaulting to gus client/api.go:770
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.vbOncEfEq5/Listeners" client/api.go:2000
DEBU [KEYSTORE]  Returning SSH certificate "/Users/gus/.tsh/keys/cluster/gus@gravitational.com-cert.pub" valid until "2019-11-21 01:39:37 -0400 AST", TLS certificate "/Users/gus/.tsh/keys/cluster/gus@gravitational.com-x509.pem" valid until "2019-11-21 05:39:37 +0000 UTC". client/keystore.go:262
INFO [KEYAGENT]  Loading key for "gus@gravitational.com" client/keyagent.go:108
INFO [CLIENT]    Connecting to proxy to copy (recursively=false)... client/api.go:1221
INFO [CLIENT]    Connecting proxy=cluster:3023 login='root' method=0 client/api.go:1539
DEBU [KEYAGENT]  Validated host cluster:3023. client/keyagent.go:280
INFO [CLIENT]    Successful auth with proxy cluster:3023 client/api.go:1530
DEBU [CLIENT]    Found clusters: [{"name":"cluster","lastconnected":"2019-11-20T17:52:18.340878415Z","status":"online"}] client/client.go:106
INFO [CLIENT]    Client= connecting to node=macmini on cluster cluster. client/client.go:451
DEBU [KEYAGENT]  Validated host macmini:0@default@cluster. client/keyagent.go:280
ERRO [CLIENT]    EOF client/client.go:745

ERROR REPORT:
Original Error: *errors.errorString ssh: command /usr/bin/scp -t ~ failed
Stack Trace:
	/tmp/20191105T162017/src/github.com/gravitational/teleport/lib/client/client.go:758 github.com/gravitational/teleport/lib/client.(*NodeClient).ExecuteSCP
	/tmp/20191105T162017/src/github.com/gravitational/teleport/lib/client/api.go:1295 github.com/gravitational/teleport/lib/client.(*TeleportClient).SCP
	/tmp/20191105T162017/src/github.com/gravitational/teleport/tool/tsh/tsh.go:808 main.onSCP.func1
	/tmp/20191105T162017/src/github.com/gravitational/teleport/lib/client/api.go:310 github.com/gravitational/teleport/lib/client.RetryWithRelogin
	/tmp/20191105T162017/src/github.com/gravitational/teleport/tool/tsh/tsh.go:807 main.onSCP
	/tmp/20191105T162017/src/github.com/gravitational/teleport/tool/tsh/tsh.go:337 main.Run
	/tmp/20191105T162017/src/github.com/gravitational/teleport/tool/tsh/tsh.go:184 main.main
	/usr/local/go/src/runtime/proc.go:212 runtime.main
	/usr/local/go/src/runtime/asm_amd64.s:1358 runtime.goexit
User Message:
```

### LINKED ISSUE #7127: SFTP Support
### What
A few customers have expressed interest in native tsh SFTP support, similar to what we already to with SCP.

### Why
Multiple customers have requested feature to match specific use-cases they have.

### Workaround
Current workaround requires running OpenSSH alongiside Teleport and exporting and adding CAs to every single node manually, which can be burdensome and challenging, especially for customers who rotate CAs periodically for security reasons.

gz#3064

gz#4740

### PR DESCRIPTION
**Pull request by capnspacehook**
SCP code is untouched because we are keeping server-side SCP support for now.

`TeleportClient.TransferFiles` was added so non command-line callers can easily transfer files over SFTP.

Fixes #7127.
Fixes #3163.
Fixes #2009.

### CODE REVIEW

**Comment by capnspacehook** [comment]
Friendly ping @espadolini @ryanclark

File: lib/sshutils/sftp/local.go [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+}
+
+func (l *localFS) Mkdir(path string) error {
+	if err := l.ctx.Err(); err != nil {
+		return err
+	}
+
+	// the permissions used here are somewhat arbitrary, they should
+	// get modified after this is called
+	err := os.MkdirAll(path, 0750)
```
Comment (espadolini) [inline lib/sshutils/sftp/local.go:109]:
```suggestion
	err := os.MkdirAll(path, 0o750)
```

but also

```suggestion
	err := os.MkdirAll(path, teleport.PrivateDirMode)
```

File: lib/sshutils/sftp/sftp.go [hunk 2]
```diff
@@ -0,0 +1,363 @@
...
+		if len(c.srcPaths) > 1 {
+			if err := c.dstFS.Mkdir(c.dstPath); err != nil {
+				return trace.Wrap(err)
+			}
+			dstIsDir = true
+		}
+	} else if len(c.srcPaths) > 1 && !dstInfo.IsDir() {
+		// if there are multiple source paths, ensure the destination path
+		// is a directory
+		return trace.BadParameter("%s file %q is not a directory, but multiple source files were specified",
```
Comment (espadolini) [inline lib/sshutils/sftp/sftp.go:183]: Is this designed to just be advisory? What does the error look like if we get an ENOTDIR later on in `transferFile` or `transferDir`?

File: lib/sshutils/sftp/sftp.go [hunk 3]
```diff
@@ -0,0 +1,363 @@
...
+func getAtime(fi os.FileInfo) time.Time {
+	s := fi.Sys()
+	if s != nil {
+		if sftpfi, ok := fi.Sys().(*sftp.FileStat); ok {
+			return time.Unix(int64(sftpfi.Atime), 0)
+		}
+		return scp.GetAtime(fi)
+	}
+
+	return time.Time{}
```
Comment (espadolini) [inline lib/sshutils/sftp/sftp.go:330]:
```suggestion
	if s == nil {
		return time.Time{}
	}

	if sftpfi, ok := fi.Sys().(*sftp.FileStat); ok {
		return time.Unix(int64(sftpfi.Atime), 0)
	}
	
	return scp.GetAtime(fi)
```

File: lib/sshutils/sftp/sftp.go [hunk 4]
```diff
@@ -0,0 +1,363 @@
...
+
+	n, err := io.Copy(writer, srcFile)
+	if err != nil {
+		return trace.Wrap(err)
+	}
+	if n != srcFileInfo.Size() {
+		return trace.Errorf("short write: written %v, expected %v", n, srcFileInfo.Size())
+	}
+
+	err = c.dstFS.Chmod(dstPath, srcFileInfo.Mode())
```
Comment (espadolini) [inline lib/sshutils/sftp/sftp.go:306]: Is there no way to create the file with the correct mode to begin with? What does OpenSSH sftp do?

File: tool/tsh/tsh.go [hunk 5]
```diff
@@ -2780,21 +2780,25 @@ func onSCP(cf *CLIConf) error {
...
+	cf.Context = ctx
+	defer cancel()
+
+	opts := sftp.Options{
 		Recursive:     cf.RecursiveCopy,
 		PreserveAttrs: cf.PreserveAttrs,
 	}
 	err = client.RetryWithRelogin(cf.Context, tc, func() error {
-		return tc.SCP(cf.Context, cf.CopySpec, int(cf.NodePort), flags, cf.Quiet)
+		return tc.SFTP(cf.Context, cf.CopySpec, int(cf.NodePort), opts, cf.Quiet)
```
Comment (espadolini) [inline tool/tsh/tsh.go:2794]: If we're not even allowing a fallback to scp, can we just delete lib/sshutils/scp?

**Review by espadolini — APPROVED** [review]

File: tool/tsh/tsh.go (hunk 5 above)
Comment (capnspacehook) [reply tool/tsh/tsh.go:2794]: Sadly no, we still want to keep server-side SCP support for now

File: lib/sshutils/sftp/sftp.go (hunk 3 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go]: Done, thanks

File: lib/sshutils/sftp/sftp.go (hunk 4 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go]: Updated fork so that destination files and dirs can be created with source modes.

File: lib/sshutils/sftp/local.go (hunk 1 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/local.go]: Since dir modes are now set upon creation, used `teleport.SharedDirMode` to create the dst dir if it doesn't already exist.

File: tool/tsh/tsh.go (hunk 5 above)
Comment (capnspacehook) [reply tool/tsh/tsh.go:2794]: Updated PR description to make that clear.

File: lib/sshutils/sftp/sftp.go (hunk 2 above)
Comment (espadolini) [reply lib/sshutils/sftp/sftp.go:184]: Someone swapping out a directory for a file after we check but before we start using it as a directory. That sort of error message is fine.

**Review by espadolini — APPROVED** [review]
Thank you for indulging my unix pedantries.

**Review by ryanclark — APPROVED** [review]
Sorry for taking so long to review this!

File: lib/sshutils/sftp/sftp.go [hunk 6]
```diff
@@ -0,0 +1,362 @@
...
+	// (used only on the client)
+	ProgressWriter io.Writer
+	// Log optionally specifies the logger
+	Log log.FieldLogger
+}
+
+// FileSystem describes file operations to be done either locally or over SFTP
+type FileSystem interface {
+	// SetContext sets the context for the filesystem used for cancellation
+	SetContext(ctx context.Context)
```
Comment (jakule) [inline lib/sshutils/sftp/sftp.go:69]: Can you please remove that method and pass context as a parameter to each method that needs it? 
https://github.com/golang/go/wiki/CodeReviewComments#contexts

File: lib/sshutils/sftp/sftp_test.go [hunk 7]
```diff
@@ -0,0 +1,435 @@
...
+			name: "src dir with recursive not passed",
+			srcPaths: []string{
+				"src/",
+			},
+			dstPath: "dst/",
+			files: []string{
+				"src/",
+			},
+			expectedErr: `"%s/src" is a directory, but the recursive option was not passed`,
+		},
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:173]: As we talked earlier, about `~` support. Can you also add a test here to verify the home directory support?

File: lib/sshutils/sftp/sftp.go [hunk 8]
```diff
@@ -0,0 +1,362 @@
...
+		return trace.Wrap(transferErr)
+	}
+	if closeErr != nil {
+		return trace.Wrap(closeErr)
+	}
+	return nil
+}
+
+// initFS ensures the source and destination filesystems are ready to transfer
+func (c *Config) initFS(ctx context.Context, client *sftp.Client) {
```
Comment (jakule) [inline lib/sshutils/sftp/sftp.go]: This looks a bit confusing to me. So you pass a client and you set it on every filesystem that is not remote?

File: lib/sshutils/sftp/sftp_test.go [hunk 9]
```diff
@@ -0,0 +1,435 @@
...
+
+func createFile(t *testing.T, rootDir, path string) {
+	dir := filepath.Dir(path)
+	if dir != path {
+		createDir(t, rootDir, dir)
+	}
+
+	// ensure we can read and write to this file, but give random permissions
+	// to everyone to test that file permissions are retained when transferring
+	mode := os.FileMode(0o660 + rand.Intn(8))
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:303]: I don't think that using random permissions is a good idea. Why just not change permissions on the source and compare it with the destination? This also makes the test non-deterministic.

File: lib/sshutils/sftp/sftp_test.go [hunk 10]
```diff
@@ -0,0 +1,435 @@
...
+	f, err := os.OpenFile(filepath.Join(rootDir, path), os.O_RDWR|os.O_CREATE|os.O_TRUNC, mode)
+	if err != nil {
+		t.Fatalf("error creating file: %v", err)
+	}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:307]:
```suggestion
	require.NoError(t, err, "failed to create file",)
```

File: lib/sshutils/sftp/sftp_test.go [hunk 11]
```diff
@@ -0,0 +1,435 @@
...
+		}
+	}()
+
+	// populate file with random amount of random contents
+	r := rand.New(rand.NewSource(time.Now().Unix()))
+	lr := io.LimitReader(r, r.Int63n(fileMaxSize)+1)
+	_, err = io.Copy(f, lr)
+	if err != nil {
+		t.Fatalf("error writing to file: %v", err)
+	}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:320]:
```suggestion
	require.NoError(t, err, "write failed")
```

File: lib/sshutils/sftp/sftp_test.go [hunk 12]
```diff
@@ -0,0 +1,435 @@
...
+}
+
+func createDir(t *testing.T, rootDir, path string) {
+	// ensure we can read and write to this dir, but give random permissions
+	// to everyone to test that dir permissions are retained when transferring
+	mode := os.FileMode(0o770 + rand.Intn(8))
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:326]: The same as above.

File: lib/sshutils/sftp/sftp_test.go [hunk 13]
```diff
@@ -0,0 +1,435 @@
...
+	if err != nil {
+		t.Fatalf("error creating directory: %v", err)
+	}
+}
+
+func checkTransfer(t *testing.T, preserveAttrs bool, dst string, srcs ...string) {
+	dstInfo, err := os.Stat(dst)
+	if err != nil {
+		t.Fatalf("error getting dst file info: %v", err)
+	}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:337]:
```suggestion
	require.NoError(t, err, "error getting dst file info")
```

File: lib/sshutils/sftp/sftp_test.go [hunk 14]
```diff
@@ -0,0 +1,435 @@
...
+	if !dstInfo.IsDir() {
+		compareFiles(t, preserveAttrs, dstInfo, nil, dst, srcs[0])
+		return
+	}
+
+	for _, src := range srcs {
+		srcInfo, err := os.Stat(src)
+		if err != nil {
+			t.Fatalf("error getting src file info: %v", err)
+		}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:351]:
```suggestion
		require.NoError(t, err, "error getting src file info")
```

File: lib/sshutils/sftp/sftp_test.go [hunk 15]
```diff
@@ -0,0 +1,435 @@
...
+
+		// src is file, compare files
+		if !srcInfo.IsDir() {
+			dstSubPath := filepath.Join(dst, filepath.Base(src))
+			dstSubInfo, err := os.Stat(dstSubPath)
+			if err != nil {
+				t.Fatalf("error getting dst file info: %v", err)
+			}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:359]:
```suggestion
			require.NoError(t, err, "error getting dst file info")
```

File: lib/sshutils/sftp/sftp_test.go [hunk 16]
```diff
@@ -0,0 +1,435 @@
...
+			if dstSubInfo.IsDir() {
+				t.Fatalf("dst file is directory: %q", dstSubPath)
+			}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:362]:
```suggestion
			require.False(t, dstSubInfo.IsDir(), "dst file is directory: %q", dstSubPath)
```

File: tool/tsh/tsh.go [hunk 17]
```diff
@@ -703,7 +703,7 @@ func Run(ctx context.Context, args []string, opts ...cliOption) error {
 	play.Arg("session-id", "ID of the session to play").Required().StringVar(&cf.SessionID)
 
 	// scp
-	scp := app.Command("scp", "Secure file copy")
+	scp := app.Command("scp", "Transfer files over SFTP")
```
Comment (jakule) [inline tool/tsh/tsh.go:706]: nit:
Can you remove the SFTP part? Now I think it's confusing as SCP uses SFTP. I think that the fact that the SCP command copies files should be enough. The underlying protocol is an implementation detail.

File: lib/sshutils/sftp/sftp_test.go [hunk 18]
```diff
@@ -0,0 +1,435 @@
...
+	}
+	if !bytes.Equal(dstBytes, srcBytes) {
+		t.Errorf("%q and %q contents not equal", dst, src[0])
+	}
+}
+
+func compareFileInfos(t *testing.T, preserveAttrs bool, dstInfo, srcInfo os.FileInfo, dst, src string) {
+	if dstInfo.Size() != srcInfo.Size() {
+		t.Fatalf("%q and %q sizes not equal", dst, src)
+	}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:425]:
```suggestion
	require.Equal(t, dstInfo.Size(), srcInfo.Size(), "%q and %q sizes not equal", dst, src)
```

File: lib/sshutils/sftp/sftp_test.go [hunk 19]
```diff
@@ -0,0 +1,435 @@
...
+	if dstInfo.Mode() != srcInfo.Mode() {
+		t.Errorf("%q and %q perms not equal", dst, src)
+	}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:428]:
```suggestion
	require.Equal(t, dstInfo.Mode(), srcInfo.Mode(), "%q and %q perms not equal", dst, src)
	}
```

File: lib/sshutils/sftp/sftp_test.go [hunk 20]
```diff
@@ -0,0 +1,435 @@
...
+
+	if preserveAttrs {
+		if !dstInfo.ModTime().Equal(srcInfo.ModTime()) {
+			t.Errorf("%q and %q mod times not equal", dst, src)
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:432]:
```suggestion
			t.Fatalf("%q and %q mod times not equal", dst, src)
```

File: lib/sshutils/sftp/sftp_test.go [hunk 21]
```diff
@@ -0,0 +1,435 @@
...
+	compareFileInfos(t, preserveAttrs, dstInfo, srcInfo, dst, src)
+
+	dstBytes, err := os.ReadFile(dst)
+	if err != nil {
+		t.Fatalf("error reading dst file: %v", err)
+	}
+	srcBytes, err := os.ReadFile(src)
+	if err != nil {
+		t.Fatalf("error reading src file: %v", err)
+	}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:416]:
```suggestion
	require.NoError(t, err, "error reading src file: %v", err)
```

File: lib/sshutils/sftp/sftp_test.go [hunk 22]
```diff
@@ -0,0 +1,435 @@
...
+			t.Fatalf("error getting dst file info: %v", err)
+		}
+	}
+
+	compareFileInfos(t, preserveAttrs, dstInfo, srcInfo, dst, src)
+
+	dstBytes, err := os.ReadFile(dst)
+	if err != nil {
+		t.Fatalf("error reading dst file: %v", err)
+	}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:412]:
```suggestion
	require.NoError(t, err, "error reading dst file: %v", err)
```

File: lib/sshutils/sftp/sftp_test.go [hunk 23]
```diff
@@ -0,0 +1,435 @@
...
+}
+
+func compareFiles(t *testing.T, preserveAttrs bool, dstInfo, srcInfo os.FileInfo, dst, src string) {
+	var err error
+	if srcInfo == nil {
+		srcInfo, err = os.Stat(src)
+		if err != nil {
+			t.Fatalf("error getting dst file info: %v", err)
+		}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:404]:
```suggestion
		require.NoError(t, err, "error getting dst file info: %v", err)
```

File: lib/sshutils/sftp/sftp_test.go [hunk 24]
```diff
@@ -0,0 +1,435 @@
...
+
+	dstBytes, err := os.ReadFile(dst)
+	if err != nil {
+		t.Fatalf("error reading dst file: %v", err)
+	}
+	srcBytes, err := os.ReadFile(src)
+	if err != nil {
+		t.Fatalf("error reading src file: %v", err)
+	}
+	if !bytes.Equal(dstBytes, srcBytes) {
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:417]:
```suggestion
	require.True(t, bytes.Equal(dstBytes, srcBytes))
```

File: lib/sshutils/sftp/sftp_test.go [hunk 25]
```diff
@@ -0,0 +1,435 @@
...
+				compareFileInfos(t, preserveAttrs, dstInfo, info, dstPath, path)
+			} else {
+				compareFiles(t, preserveAttrs, dstInfo, info, dstPath, path)
+			}
+
+			return nil
+		})
+		if err != nil {
+			t.Fatalf("error walking src dir: %v", err)
+		}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:394]:
```suggestion
		require.NoError(t, err, "error walking src dir: %v", err)
```

File: lib/sshutils/sftp/sftp_test.go [hunk 26]
```diff
@@ -0,0 +1,435 @@
...
+
+			relPath := strings.TrimPrefix(path, srcDir)
+			dstPath := filepath.Join(dst, relPath)
+			dstInfo, err := os.Stat(dstPath)
+			if err != nil {
+				return fmt.Errorf("error getting dst file info: %v", err)
+			}
+			if info.IsDir() != dstInfo.IsDir() {
+				t.Fatalf("expected %q IsDir=%t, got %t", dstPath, info.IsDir(), dstInfo.IsDir())
+			}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:382]:
```suggestion
			require.Equal(t, info.IsDir(), dstInfo.IsDir(), "expected %q IsDir=%t, got %t", dstPath, info.IsDir(), dstInfo.IsDir())
```

**Review by jakule — COMMENTED** [review]
First pass

File: go.mod [hunk 27]
```diff
@@ -323,7 +325,7 @@ replace (
 	github.com/gravitational/teleport/api => ./api
 	github.com/julienschmidt/httprouter => github.com/gravitational/httprouter v1.3.1-0.20220408074523-c876c5e705a5
 	github.com/keys-pub/go-libfido2 => github.com/gravitational/go-libfido2 v1.5.3-0.20220630200200-45a8c53e4500
-	github.com/pkg/sftp => github.com/gravitational/sftp v1.13.6-0.20220706192634-fe0df089a5e3
+	github.com/pkg/sftp => github.com/gravitational/sftp v1.13.6-0.20220926142929-99c2d88f68f3
```
[the remark this answers is not in the document]
Comment (capnspacehook) [reply go.mod:328]: `os.ErrExist` is now passed from SFTP server to client, and `OpenFile`, `Mkdir`, and `MkdirAll` methods of SFTP client now allow specifying mode when creating

File: lib/sshutils/sftp/sftp.go (hunk 6 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go]: As discussed on Slack, I think the interface is valid given it's use case, but changing it as you suggest will make it more idiomatic and flexible, so I agree it does need to be changed. Done

File: tool/tsh/tsh.go (hunk 17 above)
Comment (capnspacehook) [reply tool/tsh/tsh.go]: Done

File: lib/sshutils/sftp/sftp.go (hunk 8 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go]: Just the opposite: give remote filesystems an `sftp.Client`

File: lib/client/api.go [hunk 28]
```diff
@@ -2310,135 +2311,71 @@ func (tc *TeleportClient) SCP(ctx context.Context, args []string, port int, flag
...
 }
 
-func (tc *TeleportClient) downloadConfig(ctx context.Context, tpl scp.Config, port int, args []string) (config *scpConfig, err error) {
-	// args are guaranteed to have len(args) > 1
-	src, addr, err := getSCPDestination(args[0], port)
-	if err != nil {
-		return nil, trace.Wrap(err)
+func (tc *TeleportClient) downloadConfig(args []string, port int, opts sftp.Options) (*sftpConfig, error) {
+	if len(args) > 2 {
+		return nil, trace.BadParameter("only one source file and one destination file is supported when downloading files")
```
[the remark this answers is not in the document]
Comment (capnspacehook) [reply lib/client/api.go]: Good catch, done

**Comment by capnspacehook** [comment]
https://github.com/gravitational/sftp/pull/3 needs to be merged and `go.mod` needs to be updated to point to `github.com/gravitational/sftp@master` before this can be merged

File: lib/sshutils/sftp/sftp_test.go (hunk 9 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp_test.go]: Changed to use static permissions, this should test it well enough.

File: lib/sshutils/sftp/sftp_test.go (hunk 12 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp_test.go]: Fixed same as above.

File: lib/sshutils/sftp/sftp.go [hunk 29]
```diff
@@ -0,0 +1,472 @@
...
+		srcFS.c = client
+		haveRemoteFS = true
+	}
+	dstFS, dstOK := c.dstFS.(*remoteFS)
+	if dstOK {
+		dstFS.c = client
+		haveRemoteFS = true
+	}
+
+	if haveRemoteFS {
```
Comment (jakule) [inline lib/sshutils/sftp/sftp.go:192]: nit: You can revert the condition to remove one nested if.
```suggestion
	if !haveRemoteFS {
		return nil
	}
	...
```

File: lib/sshutils/sftp/sftp.go [hunk 30]
```diff
@@ -0,0 +1,472 @@
...
+		if c.getHomeDir == nil {
+			c.getHomeDir = func() (_ string, err error) {
```
Comment (jakule) [inline lib/sshutils/sftp/sftp.go:194]: Why do we need to cache it? What if the directory changes between calls `usermod -m /home/foo bar` ?

File: lib/sshutils/sftp/sftp.go [hunk 31]
```diff
@@ -0,0 +1,472 @@
...
+}
+
+// needsExpansion returns true if path is '~' or begins with '~/'
+func needsExpansion(path string) bool {
+	if len(path) == 1 {
+		return path == "~"
+	}
+
+	path = filepath.ToSlash(path)
+	return strings.HasPrefix(path, "~"+string(filepath.Separator))
```
Comment (jakule) [inline lib/sshutils/sftp/sftp.go:248]: If this code is used in the client, `filepath.Separator` will fail on Windows. When you copy files on any platform, most likely, you will use Unix format `~/foo`, but on Windows, the separator is different `\`.
I'd just use `~/` to make it explicit.

File: lib/sshutils/sftp/sftp.go [hunk 32]
```diff
@@ -0,0 +1,472 @@
...
+	return homeDirBuf.String(), nil
+}
+
+// transfer preforms file transfers
+func (c *Config) transfer(ctx context.Context) error {
+	var dstIsDir bool
+	dstInfo, err := c.dstFS.Stat(ctx, c.dstPath)
+	if err != nil {
+		if !errors.Is(err, os.ErrNotExist) {
+			return trace.Errorf("error accessing %s path %q: %v", c.dstFS.Type(), c.dstPath, err)
```
Comment (jakule) [inline lib/sshutils/sftp/sftp.go:281]: nit:
```suggestion
			return trace.NotFound("error accessing %s path %q: %v", c.dstFS.Type(), c.dstPath, err)
```

File: lib/sshutils/sftp/sftp_test.go [hunk 33]
```diff
@@ -0,0 +1,434 @@
...
+	lr := io.LimitReader(r, r.Int63n(fileMaxSize)+1)
+	_, err = io.Copy(f, lr)
+	require.NoError(t, err)
+}
+
+func createDir(t *testing.T, rootDir, path string) {
+	err := os.MkdirAll(filepath.Join(rootDir, path), 0o775)
+	if err != nil {
+		t.Fatalf("error creating directory: %v", err)
+	}
```
Comment (jakule) [inline lib/sshutils/sftp/sftp_test.go:353]:
```suggestion
	require.NoError(t, err, "error creating directory")
```

**Review by jakule — APPROVED** [review]

File: lib/sshutils/sftp/sftp.go (hunk 31 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go:248]: Hmm I think I might just check for `~/` and `~\` when on Windows just to be safe

File: lib/sshutils/sftp/sftp.go (hunk 30 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go:194]: We don't have to cache it, but I wanted to avoid extra teleport re-execs. Also, if the remote user's home dir is changed between calls, one or more paths will be using the old home dir and will likely cause the transfer to fail. Given that, do you still think I should not cache the home dir?

File: lib/sshutils/sftp/sftp.go (hunk 32 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go]: Done

File: lib/sshutils/sftp/sftp_test.go (hunk 33 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp_test.go]: Done

File: lib/sshutils/sftp/sftp.go (hunk 29 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go]: Done

File: lib/sshutils/sftp/sftp.go (hunk 30 above)
Comment (capnspacehook) [reply lib/sshutils/sftp/sftp.go]: Nevermind, my logic is flawed... currently only one remote path is ever allowed, so caching is useless. Good catch! Removed.

**Comment by iercan** [comment]
Does this pr will be included to next release?

**Comment by jakule** [comment]
> will this pr be included to next release?

@iercan This PR will be included in the Teleport 11
https://goteleport.com/docs/preview/upcoming-releases/#teleport-11
