### PR TITLE
Fix unrecoverable ssh cert errors in tsh/Connect

### LINKED ISSUE #55251: Connect: Unrecoverable SSH cert errors after logging in as another user without logging out first
Steps to reproduce (this was tested on v18.0.0-alpha.1):

1. Log in to a cluster as `foo`.
2. From the top right menu, select "Refresh session" and log in as `bar`.
3. Log out of the cluster.
4. Add the cluster again.

At this point, after providing the cluster address, the GetAuthSettings RPC should fail with "SSH cert not found":

<details>

```
[29-05-25 12:52:11] 2025-05-29T12:52:11.864+02:00 ERRO [CONN:APIS] Request failed error:[
[29-05-25 12:52:11] ERROR REPORT:
[29-05-25 12:52:11] Original Error: *trace.NotFoundError SSH cert not found
[29-05-25 12:52:11] Stack Trace:
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/client/interfaces.go:602 github.com/gravitational/teleport/lib/client.(*KeyRing).SSHCert
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/client/profile.go:336 github.com/gravitational/teleport/lib/client.profileStatusFromKeyRing
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/client/client_store.go:296 github.com/gravitational/teleport/lib/client.(*Store).ReadProfileStatus
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/client/api.go:1358 github.com/gravitational/teleport/lib/client.(*TeleportClient).ProfileStatus
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/teleterm/clusters/storage.go:254 github.com/gravitational/teleport/lib/teleterm/clusters.(*Storage).loadProfileStatusAndClusterKey
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/teleterm/clusters/storage.go:222 github.com/gravitational/teleport/lib/teleterm/clusters.(*Storage).fromProfile
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/teleterm/clusters/storage.go:78 github.com/gravitational/teleport/lib/teleterm/clusters.(*Storage).GetByURI
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/teleterm/clusters/storage.go:93 github.com/gravitational/teleport/lib/teleterm/clusters.(*Storage).GetByResourceURI
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/teleterm/daemon/daemon.go:318 github.com/gravitational/teleport/lib/teleterm/daemon.(*Service).ResolveClusterURI
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/teleterm/daemon/daemon.go:307 github.com/gravitational/teleport/lib/teleterm/daemon.(*Service).ResolveCluster
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/teleterm/apiserver/handler/handler_auth.go:117 github.com/gravitational/teleport/lib/teleterm/apiserver/handler.(*Handler).GetAuthSettings
[29-05-25 12:52:11] 	github.com/gravitational/teleport/gen/proto/go/teleport/lib/teleterm/v1/service_grpc.pb.go:1414 github.com/gravitational/teleport/gen/proto/go/teleport/lib/teleterm/v1._TerminalService_GetAuthSettings_Handler.func1
[29-05-25 12:52:11] 	github.com/gravitational/teleport/lib/teleterm/apiserver/middleware.go:38 github.com/gravitational/teleport/lib/teleterm/apiserver.New.withErrorHandling.func1
[29-05-25 12:52:11] 	github.com/gravitational/teleport/gen/proto/go/teleport/lib/teleterm/v1/service_grpc.pb.go:1416 github.com/gravitational/teleport/gen/proto/go/teleport/lib/teleterm/v1._TerminalService_GetAuthSettings_Handler
[29-05-25 12:52:11] 	google.golang.org/grpc@v1.72.1/server.go:1405 google.golang.org/grpc.(*Server).processUnaryRPC
[29-05-25 12:52:11] 	google.golang.org/grpc@v1.72.1/server.go:1815 google.golang.org/grpc.(*Server).handleStream
[29-05-25 12:52:11] 	google.golang.org/grpc@v1.72.1/server.go:1035 google.golang.org/grpc.(*Server).serveStreams.func2.1
[29-05-25 12:52:11] 	runtime/asm_arm64.s:1223 runtime.goexit
[29-05-25 12:52:11] User Message: SSH cert not found] apiserver/middleware.go:40
```

</details>

What happens is that logging as another user does not clear the previous certs. After you log out, only the certs of the user `bar` are removed from the `keys/<cluster>` dir. When you then attempt to add the cluster again, tsh gets confused as it sees the certs for `foo`, it creates a yaml profile with `user: foo` and the code for reading cluster details from profile fails with an error.

This is something that has been _probably_ possible for a long time. It might've been made easier to trigger with the addition of the redesigned profile switcher (#51419) which allows you to manually refresh a session and thus change which user is logged in. Previously, it might've been possible to do this by providing another username in the relogin modal or by logging in as another SSO user.

It's something we've discussed in https://github.com/gravitational/teleport/pull/51419#discussion_r1930599747. Unless we get more user reports about it, it is not a high priority because to trigger this issue you need to have access to two accounts, which the vast majority of end users doesn't have.

## Workaround

The workaround is to open the `tsh` dir next to [the `logs` dir](https://goteleport.com/docs/connect-your-client/teleport-connect/#submitting-an-issue) and then from `tsh/keys/<cluster>` remove files prefixed with the old username. Alternatively, the whole tsh dir can be removed but this will cause persisted connections in the top left to be wiped on app restart.

### PR DESCRIPTION
**Pull request by gzdunek**
Closes https://github.com/gravitational/teleport/issues/55251
Contribues to https://github.com/gravitational/teleport/issues/25806

Steps to reproduce:

1. Log in to a cluster with your OS username.
2. From the top right menu, select "Refresh session" and log in as a different user.
3. Log out of the cluster.
4. Add the cluster again.
At this point, after providing the cluster address, the GetAuthSettings RPC should fail with "SSH cert not found".

### Why this happens? 
When you relogin as a different user, tsh/Connect doesn't clear the previous certs, but instead just add new ones for the new login. Then, when you log out in Connect, the certs for the current user are removed, plus the yaml profile.
At this point (3. in the repro steps), the tsh dir looks like below:
```
├── keys
│   └── proxy.127.0.0.1.nip.io
│       ├── cas
│       │   ├── leaf.pem
│       │   └── main.pem
│       ├── certs.pem
│       ├── grzegorz
│       ├── grzegorz-ssh
│       │   └── main-cert.pub
│       ├── grzegorz.crt
│       ├── grzegorz.key
│       └── grzegorz.pub
└── known_hosts
```

When we try to add the cluster again, we first call `Handler.GetAuthSettings` which constructs `TeleportClient`. Because there's no profile, the client is initialized with a default username:
```
INFO [CLIENT]    No teleport login given, using default default_login:grzegorz client/api.go:571
INFO [CLIENT]    no host login given, using default default_host_login:grzegorz client/api.go:581
```

and the `SiteName` is initialized with a `ProfileName`:
https://github.com/gravitational/teleport/blob/cd0a0b330ce8581515e83e0b38d662162de2f82c/api/profile/profile.go#L386-L391

Next, `Storage.loadProfileStatusAndClusterKey()` attempts to load the profile and certs, and it turns out that there is data on disk for the default user.

`Store.GetKeyRing` successfully finds a valid TLS certificate and the SSH private key. However, when we try to read the profile status using `profileStatusFromKeyRing`, it fails with an "SSH cert not found" error.
The failure occurs because we look for the SSH certificate at the wrong path:
`<baseDir>/keys/proxy.127.0.0.1.nip.io/grzegorz-ssh/proxy.127.0.0.1.nip.io-cert.pub`
instead of the correct location:
`<baseDir>/keys/proxy.127.0.0.1.nip.io/grzegorz-ssh/main-cert.pub.`

The SSH certificate is expected to be at:
`<baseDir>/keys/<proxy>/<username>-ssh/<cluster>-cert.pub`
but due to the incorrect `SiteName`, we construct the wrong path and fail to load the cert.

### Proposed fix
1. ~We should remove the default username/hostlogin values from `TeleportClient`. As far as I understand, these defaults make sense only for tsh, where they provide convenience by allowing login without explicitly specifying a username when the Teleport username matches the local OS user.~
~In Connect, however, a username must always be provided explicitly, so the default values do nothing and have caused issues in the past: https://github.com/gravitational/teleport/issues/57956#issuecomment-3210498600. The defaults can be set in the outer layer (`loadClientConfigFromCLIConf` in `tsh.go`).~ 
EDIT: Abandoned this change. Many of `TeleportClient` methods rely on these values being set, and it's quite a lot of work to refactor it. 
2. ~We should remove the incorrect default value for `SiteName`. A profile name is not the same thing as a site name - they only match in certain setups (e.g., Cloud). The default was originally introduced in https://github.com/gravitational/teleport/pull/6257. I'm still not fully certain where `SiteName` is required, but so far I've identified two places:~
    * ~`tc.LoadKeyForCluster()` requires the site name to be set, otherwise `KeyRingIndex.Check()` fails, I added a guard to handle this case.~
    * ~tsh commands that connect to a cluster (like `tsh ls`), now fail with a different error:~
      * ~Now: `connection error: desc = &#34;transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for proxy.127.0.0.1.nip.io, *.proxy.127.0.0.1.nip.io, not 6d61696e.teleport.cluster.local&#34;`~
      * ~Previously (still not great): `connection error: desc = &#34;transport: authentication handshake failed: EOF&#34`~
      * ~I suspect the new error indicates we should return early when no target cluster is set, but I'm not yet sure where the right place is to perform that check.~
      * EDIT: abandoned - it's hard to tell what are the consequences of allowing `SiteName` to empty. Instead, Connect will always initialize the profile with cluster name after pinging the proxy. Thanks to this, we won't run into the incorrect default.
3. Even when all file paths are correct, the SSH certificate file may be missing, which still would cause an unrecoverable error in Connect.
Instead, if the SSH/TLS certificates are not found, we can return a partial profile in `Store.ReadProfileStatus`. I think the callers should naturally interpret this as the user not being logged in, allowing the app to prompt for login rather than failing.

changelog: Fixed "SSH cert not found" errors in Teleport Connect

### CODE REVIEW

File: lib/client/api.go [hunk 1]
```diff
@@ -549,25 +549,9 @@ func (c *Config) CheckAndSetDefaults() error {
 		c.ClientStore = NewMemClientStore()
 	}
 
-	// validate configuration
-	var err error
-	if c.Username == "" {
```
Comment (ravicious) [inline lib/client/api.go:554]: How sure are we that other callsites which used to go through this path (callers of `lib/client.NewClient`) are fine with `lib/client.Config.CheckAndSetDefaults` no longer setting the username and host login?

File: tool/tsh/common/tsh_test.go [hunk 2]
```diff
@@ -3012,7 +3013,10 @@ func TestSSHHeadlessCLIFlags(t *testing.T) {
 			assertErr: require.NoError,
 			assertConfig: func(t require.TestingT, c *client.Config) {
 				require.Equal(t, "other-proxy:3080", c.WebProxyAddr)
-				require.Empty(t, c.Username)
+				currentUsername, err := client.Username()
+				require.NoError(t, err)
+				// A default username is used, not the one from envMap.
+				require.Equal(t, currentUsername, c.Username)
```
Comment (ravicious) [inline tool/tsh/common/tsh_test.go]: This seems to be a change in behavior but I cannot tell if it's okay or not.

File: lib/client/client_store.go [hunk 3]
```diff
@@ -261,6 +261,31 @@ func (s *Store) ReadProfileStatus(proxyAddressOrProfile string) (*ProfileStatus,
 		}
 		return nil, trace.Wrap(err)
 	}
+
+	// If we can't construct KeyRingIndex, find a keyRing to match the profile,
+	// or can't connect to the keyRing (hardware key), return a partial status.
```
Comment (ravicious) [inline lib/client/client_store.go]:
```suggestion
	// If we can't construct KeyRingIndex, find a keyRing to match the profile.
	// If we can't connect to the keyRing (hardware key), return a partial status.
```

File: lib/client/client_store.go [hunk 4]
```diff
@@ -261,6 +261,31 @@ func (s *Store) ReadProfileStatus(proxyAddressOrProfile string) (*ProfileStatus,
...
+	// This is used for some superficial functions `tsh logout` and `tsh status`.
```
Comment (ravicious) [inline lib/client/client_store.go:272]: What do you mean by superficial?

File: tool/tsh/common/tsh.go [hunk 5]
```diff
@@ -4606,7 +4606,10 @@ func makeClientForProxy(cf *CLIConf, proxy string) (*client.TeleportClient, erro
 	// Handle gracefully if the profile is empty, the key cannot
 	// be found, or the key isn't supported as an agent key.
 	profile, profileError := c.GetProfile(proxy)
-	if profileError == nil {
+	if profileError == nil && profile.SiteName == "" {
```
Comment (ravicious) [inline tool/tsh/common/tsh.go]: Does this mean that every caller of `lib/client.Config.GetProfile` must now take into account the possibility that `profile.SiteName` might be empty?

It's also a bit unexpected for me because I've always assumed, maybe incorrectly, that if `siteName` is `""`, then it means "the root cluster".

File: lib/teleterm/clusters/storage.go [hunk 6]
```diff
@@ -274,16 +274,43 @@ func (s *Storage) loadProfileStatusAndClusterKey(clusterClient *client.TeleportC
...
+		return nil, trace.Wrap(err)
+	}
+
+	if status.Cluster == "" {
+		s.Logger.InfoContext(context.Background(), "Could not load key for cluster into the local agent, no cluster set")
+		return status, nil
+	}
+
+	// Load SSH key for the cluster indicated in the profile.
+	// Handle gracefully if the profile is empty, the key cannot
```
Comment (ravicious) [inline lib/teleterm/clusters/storage.go]:
```suggestion
	// Skip if the profile is empty, the key cannot
```

File: lib/teleterm/clusters/storage.go [hunk 7]
```diff
@@ -274,16 +274,43 @@ func (s *Storage) loadProfileStatusAndClusterKey(clusterClient *client.TeleportC
...
+	// be found, or the key isn't supported as an agent key.
+	err = clusterClient.LoadKeyForCluster(context.Background(), status.Cluster)
+	if err != nil && !trace.IsNotFound(err) && !trace.IsConnectionProblem(err) && !trace.IsCompareFailed(err) {
```
Comment (ravicious) [inline lib/teleterm/clusters/storage.go]: This seems a bit rough because `clusterClient.LoadKeyForCluster` calls dozens of methods on many different layers and any of them can start throwing any of these errors for unrelated reasons.

I see that `lib/client` has `IsNoCredentialsError`, maybe we could at least use this instead of `trace.IsNotFound`?

File: lib/client/profile.go [hunk 8]
```diff
@@ -398,6 +402,11 @@ func profileStatusFromKeyRing(keyRing *KeyRing, opts profileOptions) (*ProfileSt
 	sort.Strings(extensions)
 
 	tlsCert, err := keyRing.TeleportTLSCertificate()
+	if err != nil && trace.IsNotFound(err) {
+		tlsCert = &x509.Certificate{}
```
Comment (ravicious) [inline lib/client/profile.go]: How do we know that there are no callsites which assume that `lib/client.Store.ReadProfileStatus` always returns either an error or a profile with a non-empty `tlsID`?

**Review by ravicious — COMMENTED** [review]
Overall I have little confidence that this isn't going to break anything and I don't know how I could actually gain it. It doesn't help that you mentioned that `tsh ls` used to fail with one cryptic error and now starts failing with a different one.

File: lib/client/api.go (hunk 1 above)
Comment (gzdunek) [reply lib/client/api.go:554]: There is a few usages of `client.NewClient`:
* `integration/helpers/instance.go` / `lib/benchmark/benchmark.go` - tests
* `lib/client/conntest/ssh.go` - sets the login/username
* `lib/teleterm/clusters/storage.go` - doesn't need them, you can't interact with the cluster if you are not logged in
* `lib/web/files.go`, `lib/web/terminal.go` - sets the login/username
* `tool/tsh/common/tsh.go` - sets the default login/username

And there is one more that I missed:
* `tool/tsh/common/vnet_client_application.go` - it doesn't set the defaults. When there's no username, `tsh vnet` prompts the user to relogin with an empty username:
`Enter password for Teleport user :`

This happens because the client config isn't created through `loadClientConfigFromCLIConf` (as it is for other tsh commands) but instead is initialized directly.
In theory, we could add the default there, but it's made me reconsider whether removing the default is actually a good idea for `TeleportClient` in the first place.

For example, `TeleportClient.AskPassword` could previously assume that the username is not-empty set because it was initialized when `TeleportClient` was created. 
Now, the default username is initialized only in tsh. Should `AskPassword` check if the username is set? In theory it shouldn't, because it's only called only in tsh, but how would it know that? `TeleportClient` can't provide any guarantees.

This makes me think that having the field set only sometimes is worse than having an unnecessary (for Connect) default. It also doesn't help that `TeleportClient` is used across CLI tools, Connect, server-side, and has a huge API :(

File: lib/client/client_store.go (hunk 4 above)
Comment (gzdunek) [reply lib/client/client_store.go:272]: I only moved this comment a few lines up :p
But I guess it means that these functions only read profiles from disk, and don't really interact with clusters.

File: tool/tsh/common/tsh.go (hunk 5 above)
Comment (gzdunek) [reply tool/tsh/common/tsh.go]: >Does this mean that every caller of lib/client.Config.GetProfile must now take into account the possibility that profile.SiteName might be empty?

Yes, and that worries me, because I'm not sure which parts of the code rely on this value being set.

In this particular place, it's checked because `TeleportClient.LoadKeyForCluster()` calls this function: https://github.com/gravitational/teleport/blob/d1d465444b825e42d5a1bf109a59516aab6f5726/lib/client/keystore.go#L545-L548
where `idx.Check()` checks if `SiteName` is set.

>It's also a bit unexpected for me because I've always assumed, maybe incorrectly, that if siteName is "", then it means "the root cluster".

I think it depends on a place.

For example, take the bug that you encountered when you tried to log in through tsh when a profile was empty 
https://github.com/gravitational/teleport/pull/60884#discussion_r2502906602.
The problem comes from the fact that `client.SSHAgentMFALogin` incorrectly uses the profile name as `RouteToCluster`, which causes: 
```
ERROR REPORT:
Original Error: *trace.NotFoundError remote cluster &#34;teleport-local.dev&#34; is not found
Stack Trace:

Caught:
	github.com/gravitational/teleport/lib/httplib/httplib.go:213 github.com/gravitational/teleport/lib/httplib.ConvertResponse
	github.com/gravitational/teleport/lib/client/https_client.go:125 github.com/gravitational/teleport/lib/client.(*WebClient).PostJSON
	github.com/gravitational/teleport/lib/client/weblogin.go:656 github.com/gravitational/teleport/lib/client.SSHAgentMFALogin
	github.com/gravitational/teleport/lib/client/api.go:4252 github.com/gravitational/teleport/lib/client.(*TeleportClient).localLogin
	github.com/gravitational/teleport/lib/client/api.go:3820 github.com/gravitational/teleport/lib/client.(*TeleportClient).getSSHLoginFunc.func2
	github.com/gravitational/teleport/lib/client/api.go:4012 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSHLogin.func1
	github.com/gravitational/teleport/lib/client/api.go:4083 github.com/gravitational/teleport/lib/client.(*TeleportClient).loginWithHardwareKeyRetry
	github.com/gravitational/teleport/lib/client/api.go:4010 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSHLogin
	github.com/gravitational/teleport/lib/client/api.go:3600 github.com/gravitational/teleport/lib/client.(*TeleportClient).Login
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:2391 github.com/gravitational/teleport/tool/tsh/common.onLogin
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1754 github.com/gravitational/teleport/tool/tsh/common.Run
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:752 github.com/gravitational/teleport/tool/tsh/common.Main
	github.com/gravitational/teleport/tool/tsh/main.go:26 main.main
	runtime/proc.go:285 runtime.main
	runtime/asm_arm64.s:1268 runtime.goexit
User Message: remote cluster &#34;teleport-local.dev&#34; is not found
```
But if this field is empty, everything works fine.

--------
The other option I see, is to change Connect's behavior when it creates the profile for the first time in `GetAuthSettings`. It could read the cluster name from the ping response and store it in the profile. This wouldn't fully resolve the underlying issue of the incorrect default, but it would significantly reduce the likelihood of users encountering it.

What do you think of it?

File: lib/teleterm/clusters/storage.go (hunk 7 above)
Comment (gzdunek) [reply lib/teleterm/clusters/storage.go]: Unfortunately, if there's no SSH cert on disk, `clusterClient.LoadKeyForCluster()` returns `trace.NotFound("SSH cert not found")`.

I agree that's a bit rough, but at least it's not a new behavior. We already have it in tsh:
https://github.com/gravitational/teleport/blob/cfcb4f9e41bd583555a98a6f969769160b532fb3/tool/tsh/common/tsh.go#L4609-L4619

File: lib/client/profile.go (hunk 8 above)
Comment (gzdunek) [reply lib/client/profile.go]: Right, this could be surprising if the fields populated from `sshIdent` are set, but the ones derived from `tlsID` are not.
But I think we can make it safer.
`lib/client.Store.ReadProfileStatus` already returns a partial profile when it fails to read the key ring. We could do the same when `profileStatusFromKeyRing` returns a not-found error.

File: lib/client/api.go (hunk 1 above)
Comment (gzdunek) [reply lib/client/api.go:554]: I decided to revert this change because of the concerns above.

File: tool/tsh/common/tsh_test.go (hunk 2 above)
Comment (gzdunek) [reply tool/tsh/common/tsh_test.go]: Reverted.

File: tool/tsh/common/tsh.go (hunk 5 above)
Comment (ravicious) [reply tool/tsh/common/tsh.go]: > This wouldn't fully resolve the underlying issue of the incorrect default, but it would significantly reduce the likelihood of users encountering it.

Wouldn't that in practice solve this problem completely? Unless someone was editing the profile yaml by hand.

I was also curious how this wasn't happening already. In the `GetAuthSettings` RPC, `Cluster.SyncAuthPreferences` already does a ping followed by saving the profile. But I see now that `lib/client.TeleportClient.Ping` does not update the cluster name based on the ping response? I guess this make sense since technically pinging the proxy is not the same as deciding which cluster you want to use. But in the context of Connect this should make sense. `clusters.Storage.addCluster` could do that tbh because it also pings the cluster and saves the profile.

Comment (gzdunek) [reply tool/tsh/common/tsh.go]: >Wouldn't that in practice solve this problem completely? Unless someone was editing the profile yaml by hand.

Yeah, it should solve the problem. It's easier than fixing the incorrect default and handling the empty value.

However, it turned out that the updated cluster name was not being persisted in the yaml profile. This was caused by https://github.com/gravitational/teleport/pull/60473, where we started to reset the `.SiteName` field for root clusters (and even before that change, the site name could be overwritten when creating a leaf cluster client). As a result, when `TeleportClient.SaveClient` is called, it writes this modified (empty) site name to disk.

Unfortunately, the only way to avoid persisting the modified value is to  re-read the original site name from disk immediately before updating the profile.

File: lib/teleterm/clusters/storage.go [hunk 9]
```diff
@@ -171,6 +171,12 @@ func (s *Storage) addCluster(ctx context.Context, webProxyAddress string) (*Clus
 		return nil, nil, trace.Wrap(err)
 	}
 
+	// There's an incorrect default in [profile.profileFromFile] - an empty SiteName is replaced  with the profile name.
```
Comment (ravicious) [inline lib/teleterm/clusters/storage.go]: For `[profile.profileFromFile]` to work, the package must be imported within this file. Since it's not imported, you'd need to use its full name, but I can't even get `[github.com/gravitational/teleport/api/profile.profileFromFile]` to work. In that case, it might be better to refer to it just as `api/profile.profileFromFile`.

File: lib/teleterm/clusters/storage.go [hunk 10]
```diff
@@ -171,6 +171,12 @@ func (s *Storage) addCluster(ctx context.Context, webProxyAddress string) (*Clus
...
+	// Unfortunately, a profile name is not the same thing as a site name, and they only match in certain setups (e.g., Cloud).
```
Comment (ravicious) [inline lib/teleterm/clusters/storage.go]: This makes it sound like a situation where the cluster name is the proxy hostname is an outlier, but I think it's more common than not. Our getting started docs [explicitly ask the user to set a cluster name](https://goteleport.com/docs/get-started/deploy-community/#configure-teleport) to that of the domain.

I think we'd be better off by explicitly saying that a profile name is not the same thing as a site name and they differ when the proxy hostname is different than the cluster name, no?

File: lib/teleterm/clusters/storage.go
Comment (ravicious) [inline lib/teleterm/clusters/storage.go:1]: Any way we could add a test for both behaviors (resetting the site name in `fromProfile`, bringing it back in `addCluster`)? I don't think we have explicit storage tests, but in integration tests we do have a real cluster and access to storage so maybe it could be tested this way? We already call methods such as `storage.Add` in integration tests.

File: lib/teleterm/clusters/storage.go (hunk 10 above)
Comment (gzdunek) [reply lib/teleterm/clusters/storage.go]: Yeah that's more correct, done.

File: lib/teleterm/clusters/storage.go
Comment (gzdunek) [reply lib/teleterm/clusters/storage.go:1]: I added a test to verify that `addCluster` sets the site name in the profile and then if it's correctly ignored without overwriting.

File: api/profile/profile.go [hunk 11]
```diff
@@ -392,6 +392,10 @@ func profileFromFile(filePath string) (*Profile, error) {
 	// Older versions of tsh did not always store the cluster name in the
 	// profile. If no cluster name is found, fallback to the name of the profile
 	// for backward compatibility.
+	//
+	// TODO: A profile name is not the same thing as a site name, and they differ when the proxy hostname is different
```
Comment (ravicious) [inline api/profile/profile.go]:
```suggestion
	// TODO(gzdunek): A profile name is not the same thing as a site name, and they differ when the proxy hostname is different
```

🤓 😏

File: integration/teleterm_test.go [hunk 12]
```diff
@@ -673,6 +678,54 @@ func testLogout(t *testing.T, pack *dbhelpers.DatabasePack, creds *helpers.UserC
 	require.NoError(t, err)
 }
 
+func testSettingSiteName(t *testing.T, pack *dbhelpers.DatabasePack, creds *helpers.UserCreds) {
```
Comment (ravicious) [inline integration/teleterm_test.go:681]: This test still passes if I comment out this line.

https://github.com/gravitational/teleport/blob/f3b91d8a0cc20d147eb7e5f7a2565ef3a76d0077/lib/teleterm/clusters/storage.go#L174-L179

File: lib/client/client_store.go [hunk 13]
```diff
@@ -308,6 +311,12 @@ func (s *Store) ReadProfileStatus(proxyAddressOrProfile string) (*ProfileStatus,
 		IsVirtual:               !onDisk,
 		TLSRoutingEnabled:       profile.TLSRoutingEnabled,
 	})
+	if trace.IsNotFound(err) {
+		return partialStatus, nil
+	} else if err != nil {
+		return nil, trace.Wrap(err)
+	}
+	return profileStatus, nil
```
Comment (ravicious) [inline lib/client/client_store.go:319]: What's the idea behind this change? Which scenario does it address?

I think it might be worthwhile to update the PR description to get it in line with the solution that we've settled on.

**Review by ravicious — COMMENTED** [review]
It seems to look good, but I'd just like to better understand the change in `lib/client/client_store.go` and if it has the potential to have an impact on tsh.

File: integration/teleterm_test.go (hunk 12 above)
Comment (gzdunek) [reply integration/teleterm_test.go:681]: Ah, it's because of `mustLogin` which stores a profile with the site name, before we even add the profile. Fixed.

File: lib/client/client_store.go (hunk 13 above)
Comment (gzdunek) [reply lib/client/client_store.go:319]: Currently, when a TLS certificate and an SSH private key are present but no SSH certificate, the profile becomes unusable in Connect.
Even attempting to recover by logging out doesn't help. Both tsh and Connect return early when they encounter a `NotFound` error when getting a full profile status/when resolving a cluster, which prevents them from cleaning up the files.
This also means that `tsh status` will show that profile as expired, instead of 'Not logged in' error. This error seems to be wrong, because when you then run `tsh login`, it will get prefilled with the username/proxy from the profile, while the error suggests that there's no expired profile.

In theory, the app shouldn't now go into that bad state (because Connect now saves the site name in the profile) but looking at [the test cases](https://github.com/gravitational/teleport/blob/edb56d6ccb327a6f0c0b3797f4c65e3a2af35982/tool/tsh/common/tsh_test.go#L6068) for the logout function in `tsh_test.go` this seems to be another scenario to handle.

Also, it appears that `Store.ReadProfileStatus` rather tries to gracefully handle "not found" errors, and this change seems to be in line with the existing code.
I think this shouldn't break anything, the callsites already should be able to handle the partial profile status.

**Review by ravicious — APPROVED** [review]

**Comment by gzdunek** [comment]
@nklaassen friendly ping

**Review by nklaassen — APPROVED** [review]
