### PR TITLE
Introduce version checking and fix YAML lists

### LINKED ISSUE #1663: Creating multiple resources does not work with yaml lists
**What happened**:

tctl create -f resources.yaml only created the first resource in the list

**What you expected to happen**:

All resources should be created

**How to reproduce it (as minimally and precisely as possible)**:

tctl create -f list.yaml

```yaml
resource a
---
resource b
```

**Environment**:
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
all versions
- OS (e.g. from /etc/os-release):

Bug is on this line: 

https://github.com/gravitational/teleport/blob/master/tool/tctl/common/resource_command.go#L171

only return if error here

### PR DESCRIPTION
**Pull request by klizhentas**
Fixes #1663, #1665

This commit fixes a couple of issues with tsh and tctl:

* tsh now check the version of the server and prints error
if tsh is newer version than the server.

* tctl did not work properly when yaml file contained
multiple resources in a list

### CODE REVIEW

**Review by kontsevoy — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please

File: lib/client/api.go [hunk 1]
```diff
@@ -190,6 +190,10 @@ type Config struct {
 
 	// AuthConnector is the name of the authentication connector to use.
 	AuthConnector string
+
+	// CheckVersions will check that client version is compatible
+	// to auth server version when connecting.
```
Comment (r0mant) [inline lib/client/api.go]: compatible _with_

**Review by r0mant — APPROVED** [review]

**Review by russjones — APPROVED** [review]

**Comment by klizhentas** [comment]
retest this please
