### PR TITLE
Fix panic when rejecting a headless request

### LINKED ISSUE #58864: Rejecting a headless auth request generates an odd error
## Expected behavior

Rejecting a headless auth request should result in human-readable errors.

Image

## Current behavior

Rejecting a headless auth request displays a red `TypeError: failed to fetch` warning which could confuse users.

Image

## Repro steps

Run `tsh ssh --proxy teleport.example.com --user username --headless hostname` and click the link which appears:

```
gus@apollo:~ % tsh ssh --proxy teleport.example.com --user username --headless hostname
Complete headless authentication in your local web browser:

https://teleport.example.com:443/web/headless/f3e65d3f-c471-5aa9-937d-986184c22538

or execute this command in your local terminal:

tsh headless approve --user=username --proxy=teleport.example.com:443 f3e65d3f-c471-5aa9-937d-986184c22538
```

Bug details:
- Teleport version: 18.2.0

### PR DESCRIPTION
**Pull request by ravicious**
Closes #58864.

changelog: Fixed a server error when rejecting a headless authentication request in the Web UI

This might have been introduced by #53741 but I haven't checked because I wasn't able to build the binary due to Rust issues.

The cause of the issue appears to be that the client uses [the same endpoint when accepting or rejecting a headless request](https://github.com/gravitational/teleport/blob/7b3fe4ce267ee3440dbf03b75a12309736bb4af2/web/packages/teleport/src/services/auth/auth.ts#L245-L264). When rejecting, the MFA response isn't required and the client doesn't send it, but the handler assumed it's always present.

The fix was easy, but I noticed there are no tests that could've catched this regression. I used Claude Code to generate the bulk of them, asking it to look at other tests in `lib/web` (primarily `lib/web/apiserver_test.go`). Of course I had to clean them up a fair amount, but it looks like the general pattern does resemble the patterns that can be seen in [`TestIntegrationsCRUDRolesAnywhere`](https://github.com/gravitational/teleport/blob/4ab822f39df61c16c8fb35726013041ccda04683/lib/web/integrations_test.go#L110) for example (setting up the server and so on).

### CODE REVIEW

File: lib/web/headless_test.go [hunk 1]
```diff
@@ -0,0 +1,318 @@
+/*
+ * Teleport
+ * Copyright (C) 2025  Gravitational, Inc.
```
Comment (atburke) [inline lib/web/headless_test.go]:
```suggestion
 * Copyright (C) 2026  Gravitational, Inc.
```

File: lib/web/headless_test.go [hunk 2]
```diff
@@ -0,0 +1,318 @@
...
+			if tt.expectedStatus == 200 {
+				require.NoError(t, err)
+			} else {
+				require.Error(t, err)
+			}
+
+			if tt.expectedStatus != 200 {
+				require.ErrorContains(t, err, tt.expectedErrMsg, "unexpected error message")
+				return
+			}
```
Comment (atburke) [inline lib/web/headless_test.go]: nit: a little simpler
```suggestion
			if tt.expectedStatus != 200 {
				require.ErrorContains(t, err, tt.expectedErrMsg, "unexpected error message")
				return
			}
			require.NoError(t, err)
```

File: lib/web/headless_test.go [hunk 3]
```diff
@@ -0,0 +1,318 @@
...
+	}
+
+	tests := []struct {
+		name string
+		// setupHeadless creates new headless auth and returns its ID. If an actual headless auth ID
+		// is not needed (e.g. to test a case where the headless auth ID is incorrect), use headlessID
+		// instead.
+		setupHeadless func() string
+		// headlessID is used when setupHeadless is nil.
+		headlessID     string
```
Comment (atburke) [inline lib/web/headless_test.go]: nit: `setupHeadless()` could just always return the string instead of having a separate field

**Review by atburke — APPROVED** [review]

File: lib/web/headless_test.go [hunk 4]
```diff
@@ -0,0 +1,318 @@
...
+	"github.com/gravitational/teleport/lib/auth/authtest"
+	wantypes "github.com/gravitational/teleport/lib/auth/webauthntypes"
+	"github.com/gravitational/teleport/lib/client"
+	"github.com/gravitational/teleport/lib/services"
+)
+
+func TestPutHeadlessState(t *testing.T) {
+	t.Parallel()
+
+	ctx := context.Background()
```
Comment (zmb3) [inline lib/web/headless_test.go]: Use `t.Context()` instead.

File: lib/web/headless_test.go [hunk 5]
```diff
@@ -0,0 +1,318 @@
...
+			RPID: "localhost",
+		},
+	})
+	require.NoError(t, err)
+	_, err = env.server.Auth().UpsertAuthPreference(ctx, ap)
+	require.NoError(t, err)
+
+	// Register a WebAuthn device for the user.
+	userClient, err := env.server.NewClient(authtest.TestUser(username))
+	require.NoError(t, err)
```
Comment (zmb3) [inline lib/web/headless_test.go:64]: Do we need to `userClient.Close()` when we're done?

File: lib/web/headless_test.go [hunk 6]
```diff
@@ -0,0 +1,318 @@
...
+	webauthnDev, err := authtest.RegisterTestDevice(
+		ctx,
+		userClient,
+		"webauthn",
+		authproto.DeviceType_DEVICE_TYPE_WEBAUTHN,
+		nil, /* authenticator */
+	)
+	require.NoError(t, err)
+
+	getMFAResponse := func() *client.MFAChallengeResponse {
```
Comment (zmb3) [inline lib/web/headless_test.go:77]:
```suggestion
	getMFAResponse := func() *client.MFAChallengeResponse {
		t.Helper()
```

File: lib/web/headless_test.go [hunk 7]
```diff
@@ -0,0 +1,318 @@
...
+			}
+
+			request := tt.request
+			if tt.useMFA {
+				request.MFAResponse = getMFAResponse()
+			}
+
+			endpoint := pack.clt.Endpoint("webapi", "headless", headlessID)
+			resp, err := pack.clt.PutJSON(ctx, endpoint, request)
+
```
Comment (zmb3) [inline lib/web/headless_test.go]:
```suggestion
```

File: lib/web/headless_test.go (hunk 4 above)
Comment (ravicious) [reply lib/web/headless_test.go]: I spotted this one but then I forgot to fix it, thanks.

**Review by Joerger — APPROVED** [review]

File: lib/web/headless.go [hunk 8]
```diff
@@ -71,9 +72,14 @@ func (h *Handler) putHeadlessState(_ http.ResponseWriter, r *http.Request, param
 		}
 	}
 
-	mfaResp, err := req.MFAResponse.GetOptionalMFAResponseProtoReq()
-	if err != nil {
-		return nil, trace.Wrap(err)
+	// MFAResponse is required only when accepting a request.
+	var mfaResp *proto.MFAAuthenticateResponse
+	if req.MFAResponse != nil {
```
Comment (espadolini) [inline lib/web/headless.go]: I think I'd rather see an `if r == nil { return nil, nil }` in `(*lib/client.MFAChallengeResponse).GetOptionalMFAResponseProtoReq` rather than nil checks here and there; there's a lot of callers to `GetOptionalMFAResponseProtoReq` and I'm not sure how many of them are susceptible to a client not passing the mfa response field (or passing an explicit `null`).

Comment (ravicious) [reply lib/web/headless.go]: Yeah, I think that makes sense. I was thinking of this too, but with widely used methods like this one I naturally start to look into introducing the least amount of possible behavior changes, so I ended up doing this in the handler.

**Review by espadolini — APPROVED** [review]

File: lib/web/headless.go (hunk 8 above)
Comment (ravicious) [reply lib/web/headless.go]: @Joerger Could you take a look again at the implementation after this change?

Comment (espadolini) [reply lib/web/headless.go]: The new check solves a very similar panic in `(*Handler).deleteMFADeviceHandle`, FWIW.

**Review by Joerger — APPROVED** [review]
