### PR TITLE
fix: add availability checks for instance metadata methods

### LINKED ISSUE #62379: Azure SQL Server connection fails after upgrading to v18
Expected behavior:

After upgrading to Teleport v18, connecting to Azure SQL server should continue working as on v17 without any changes.

Current behavior:

After upgrading from v17.7.11 to v18.5.1 connections to Azure SQL server fails with error about missing `api-version`:

```
$ tsh db connect --db-user test --db-name test --tunnel redacted
mssql: login error: Bad request. api-version is invalid or was not specified in the request. For more information refer to aka.ms/azureimds
        {"error":"Bad request. api-version is invalid or was not specified in the request. For more information refer to aka.ms/azureimds","newest-versions":["2025-04-07","2024-07-17","2024-03-15"]}

mssql: login error: Bad request. api-version is invalid or was not specified in the request. For more information refer to aka.ms/azureimds
        {"error":"Bad request. api-version is invalid or was not specified in the request. For more information refer to aka.ms/azureimds","newest-versions":["2025-04-07","2024-07-17","2024-03-15"]}

ERROR: exit status 1
```

I find the following in the server logs:

```
2025-12-18T13:47:29.340Z ERRO [DB:SERVIC] Failed to handle connection. error:[
ERROR REPORT:
Original Error: *trace.TraceErr {&#34;error&#34;:&#34;Bad request. api-version is invalid or was not specified in the request. For more information refer to aka.ms/azureimds&#34;,&#34;newest-versions&#34;:[&#34;2025-04-07&#34;,&#34;2024-07-17&#34;,&#34;2024-03-15&#34;]}

Stack Trace:
        github.com/gravitational/teleport/lib/cloud/imds/azure/imds.go:141 github.com/gravitational/teleport/lib/cloud/imds/azure.parseMetadataClientError
        github.com/gravitational/teleport/lib/cloud/imds/azure/imds.go:134 github.com/gravitational/teleport/lib/cloud/imds/azure.(*InstanceMetadataClient).getRawMetadata
        github.com/gravitational/teleport/lib/cloud/imds/azure/imds.go:228 github.com/gravitational/teleport/lib/cloud/imds/azure.(*InstanceMetadataClient).GetInstanceInfo
        github.com/gravitational/teleport/lib/cloud/imds/azure/imds.go:243 github.com/gravitational/teleport/lib/cloud/imds/azure.(*InstanceMetadataClient).GetID
        github.com/gravitational/teleport/lib/srv/db/common/auth.go:1156 github.com/gravitational/teleport/lib/srv/db/common.(*dbAuth).getCurrentAzureVM
        github.com/gravitational/teleport/lib/utils/fncache.go:275 github.com/gravitational/teleport/lib/utils.FnCacheGetWithTTL[...].func1
        github.com/gravitational/teleport/lib/utils/fncache.go:347 github.com/gravitational/teleport/lib/utils.(*FnCache).get.func1
        runtime/asm_amd64.s:1700 runtime.goexit
User Message: Bad request. api-version is invalid or was not specified in the request. For more information refer to aka.ms/azureimds
        {&#34;error&#34;:&#34;Bad request. api-version is invalid or was not specified in the request. For more information refer to aka.ms/azureimds&#34;,&#34;newest-versions&#34;:[&#34;2025-04-07&#34;,&#34;2024-07-17&#34;,&#34;2024-03-15&#34;]}
        ] addr:192.168.198.199:36528 db/server.go:1187
```

Inspecting with `tcpdump` I can see that a metadata request is sent without `api-version` set. 

```
GET /metadata/instance/compute?format=json HTTP/1.1
Host: 169.254.169.254
User-Agent: Go-http-client/1.1
Metadata: True
Accept-Encoding: gzip
```

Not sure why this happens but when I remove v18.5.1 and reinstall v17.7.11 I can connect again without any issues.

Teleport is running on a Azure VM connecting to a self-hosted Teleport cluster in AKS with the following config:

```
version: v3
teleport:
  nodename: "redacted"
  data_dir: "/var/lib/teleport"
  proxy_server: "redacted:443"
  auth_token: "/tmp/token"

auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
proxy_service:
  enabled: "no"

db_service:
  enabled: true

  azure:
    - types: ["sqlserver"]
      subscriptions:
        - "*"
      resource_groups:
        - "*"
      regions:
        - "norwayeast"
      tags:
        "*": "*"
```

Bug details:
- Teleport version: Teleport Enterprise v18.5.1
- Recreation steps
- Debug logs

### PR DESCRIPTION
**Pull request by Tener**
Ensures proper initialization of `api-version` by calling `IsAvailable()`.

Fixes https://github.com/gravitational/teleport/issues/62379.

Changelog: Fixed missing initialization of Azure IMDS clients, which could cause operational failures in some Teleport configurations deployed to Azure, in particular when accessing Azure SQL Server.

### CODE REVIEW

File: lib/cloud/imds/azure/imds.go [hunk 1]
```diff
@@ -225,6 +226,10 @@ type InstanceInfo struct {
 
 // GetInstanceInfo gets the Azure Instance information.
 func (client *InstanceMetadataClient) GetInstanceInfo(ctx context.Context) (*InstanceInfo, error) {
+	if !client.IsAvailable(ctx) {
+		return nil, trace.NotFound("Instance metadata is not available")
+	}
```
Comment (greedy52) [inline lib/cloud/imds/azure/imds.go:232]: The downside checking `IsAvailable` on every api call is we will repeatedly attempt to `client.selectVersion` on every call if it fails.

**Review by greedy52 — COMMENTED** [review]
🙏 thanks for the quick fix

File: lib/cloud/imds/azure/imds.go (hunk 1 above)
Comment (Tener) [reply lib/cloud/imds/azure/imds.go:232]: Good point, thank you. Having given it some thought I think this is fine: the check is inexpensive and won't happen frequently.

File: lib/cloud/imds/azure/imds.go [hunk 2]
```diff
@@ -163,7 +163,8 @@ func (client *InstanceMetadataClient) getVersions(ctx context.Context) ([]string
 	return versions.APIVersions, nil
 }
 
-// IsAvailable checks if instance metadata is available.
+// IsAvailable checks if instance metadata is available based on the API version.
+// It also initializes the API version itself, so it must be called before other methods.
```
Comment (greedy52) [inline lib/cloud/imds/azure/imds.go]: nit:
> It also initializes the API version itself, so it must be called before other methods.

This may imply the caller has to call this method "manually", which is no longer necessary after this fix. Maybe tweak the wording a little bit.

File: lib/cloud/imds/azure/imds_test.go [hunk 3]
```diff
@@ -171,14 +170,64 @@ func TestParseMetadataClientError(t *testing.T) {
 	}
 }
 
+type mockIMDS struct {
+	t              *testing.T
+	versionsCalled bool
+	lastAPIVersion string
```
Comment (greedy52) [inline lib/cloud/imds/azure/imds_test.go:177]: nit: should these be locked or atomic?

File: lib/cloud/imds/azure/imds_test.go [hunk 4]
```diff
@@ -171,14 +170,64 @@ func TestParseMetadataClientError(t *testing.T) {
...
+			handler, ok := overrides[r.URL.Path]
+			if ok {
+				handler.ServeHTTP(w, r)
+				return
+			}
+		}
+
+		switch r.URL.Path {
+		case "/versions":
+			m.versionsCalled = true
```
Comment (greedy52) [inline lib/cloud/imds/azure/imds_test.go]: nit:  should `m.versionsCalled` be set when overridden? or maybe don't allow override for `/versions`

**Review by greedy52 — APPROVED** [review]

File: lib/cloud/imds/azure/imds_test.go (hunk 3 above)
Comment (Tener) [reply lib/cloud/imds/azure/imds_test.go:177]: Going through the code slowly I think we are fine right now, no concurrency in sight, but it doesn't take much to add locks which I did.

File: lib/cloud/imds/azure/imds_test.go (hunk 4 above)
Comment (Tener) [reply lib/cloud/imds/azure/imds_test.go]: We can disallow it, but instead I've simply made it its own check. This way we can convert the switch to plain map, which is somewhat easier to read (at least to me).

File: lib/cloud/imds/azure/imds.go (hunk 2 above)
Comment (Tener) [reply lib/cloud/imds/azure/imds.go]: Agreed; tweaked to make it clearer.

**Review by atburke — APPROVED** [review]
