### PR TITLE
Fix getting chart url for non standard releases during EKS enrollment.

### LINKED ISSUE #42335: EKS Discover enrollment can't download correct chart version for non-standard releases
Because of our recent change in artifacts release strategy (non standard releases like -alpha, -dev, -rc etc go to another repo) when EKS enrollment tries to download chart for a non standard release version it can't find it in the main repo.

### PR DESCRIPTION
**Pull request by AntonAM**
Because of recent changes in release policy non standard releases go to the staging repo, so we need to amend the way we get kube chart url for the EKS enrollment.

Fixes #42335

### CODE REVIEW

**Review by kimlisa — APPROVED** [review]

File: lib/integrations/awsoidc/eks_enroll_clusters.go [hunk 1]
```diff
@@ -528,18 +530,31 @@ type installKubeAgentParams struct {
...
+	}
+
+	// pre release tagged charts are located in the staging repo.
+	if ver.PreRelease != "" {
+		repo = agentStagingRepoURL
+	}
 	return &url.URL{
-		Scheme: agentRepoURL.Scheme,
-		Host:   agentRepoURL.Host,
+		Scheme: repo.Scheme,
```
Comment (tigrato) [inline lib/integrations/awsoidc/eks_enroll_clusters.go:545]: Replace this copy with return `repo.JoinPath(fmt.Sprintf("%s-%s.tgz", agentName, version)), nil`

File: lib/integrations/awsoidc/eks_enroll_clusters.go [hunk 2]
```diff
@@ -528,18 +530,31 @@ type installKubeAgentParams struct {
...
-func getChartURL(version string) *url.URL {
+func getChartURL(version string) (*url.URL, error) {
+	repo := agentRepoURL
+	ver, err := semver.NewVersion(version)
+	if err != nil {
+		return nil, trace.Wrap(err, "failed to parse chart version %q", version)
+	}
+
+	// pre release tagged charts are located in the staging repo.
+	if ver.PreRelease != "" {
```
Comment (r0mant) [inline lib/integrations/awsoidc/eks_enroll_clusters.go:541]: FYI `-cloud.X` releases still go to production env. We may need to account for it here because we deploy those to Cloud sometimes.

**Review by r0mant — CHANGES_REQUESTED** [review]
Requesting changes so we can address an extra edge case.

File: lib/integrations/awsoidc/eks_enroll_clusters.go (hunk 2 above)
Comment (r0mant) [reply lib/integrations/awsoidc/eks_enroll_clusters.go:541]: Actually, I take it back. I don't think we publish Helm charts for -cloud releases at all currently, only Docker images.

Comment (AntonAM) [reply lib/integrations/awsoidc/eks_enroll_clusters.go:541]: Should we I future-proof it and still add an exception for "cloud" tag?

Comment (tigrato) [reply lib/integrations/awsoidc/eks_enroll_clusters.go:541]: in that case, it will fail because the chart is missing and we should drop the cloud.x

Comment (r0mant) [reply lib/integrations/awsoidc/eks_enroll_clusters.go:541]: Yeah I'm thinking what is the best way to handle -cloud releases here. My first idea was that we can fallback to previous full version in this case so if control plane is running say 15.3.4-cloud.X, we use 15.3.3. But this might get messy with .0 releases, even though it's an edge case.

Comment (tigrato) [reply lib/integrations/awsoidc/eks_enroll_clusters.go:541]: can't we just use whatever is available in the stable release channel?

Comment (r0mant) [reply lib/integrations/awsoidc/eks_enroll_clusters.go:541]: As discussed in Slack, this might not be an issue since in Cloud we take versions from the bucket lock file when auto-upgrades are enabled.

**Review by r0mant — APPROVED** [review]
