### PR TITLE
Fix verbose mode message in help text

### LINKED ISSUE #3156: tsh ls --help minor documentation issue
There seems to be a copy'n'paste mistake in `tsh ls --help` which shows the same error message for two different flags:
```
(...)
      --cluster             Specify the cluster to connect
  -v, --verbose             Specify the cluster to connect
```
Would be great if the help text for -v would include the information from https://github.com/gravitational/teleport/issues/2264 (about labels not being wrapped).

### PR DESCRIPTION
**Pull request by webvictim**
Fixes #3156

### CODE REVIEW

File: tool/tsh/tsh.go [hunk 1]
```diff
@@ -267,7 +267,7 @@ func Run(args []string) {
 	ls := app.Command("ls", "List remote SSH nodes")
 	ls.Flag("cluster", clusterHelp).Envar(clusterEnvVar).StringVar(&cf.SiteName)
 	ls.Arg("labels", "List of labels to filter node list").StringVar(&cf.UserHost)
-	ls.Flag("verbose", clusterHelp).Short('v').BoolVar(&cf.Verbose)
+	ls.Flag("verbose", "Enable verbose, one-line output, including node UUIDs").Short('v').BoolVar(&cf.Verbose)
```
Comment (benarent) [inline tool/tsh/tsh.go:270]: I would drop 'Enable verbose' , as I would guess it would look like this in the terminal. 

```
  -v, --verbose       Enable verbose, one-line output, including node UUIDs
```

```
  -v, --verbose       One-line output, including node UUIDs
```

Comment (webvictim) [reply tool/tsh/tsh.go:270]: You're correct:

```
~/go/src/github.com/gravitational/teleport(gus/tsh-help-fix*) » build/tsh ls --help
usage: tsh ls [<flags>] [<labels>]

List remote SSH nodes

Flags:
  -l, --login                    Remote host login
...
  -v, --verbose                  One-line output, including node UUIDs

Args:
  [<labels>]  List of labels to filter node list

Aliases:
```

**Review by benarent — APPROVED** [review]

**Review by awly — APPROVED** [review]
