### PR TITLE
do not register Aurora serverless db clusters

### LINKED ISSUE #9372: "tsh db ls" shows serverless aurora cluster even though teleport does not support it
### Description

**What happened**:
- serverless aurora clusters are discovered and shown in `tsh db ls`
- `tsh db connect` to serverless aurora clusters will always fail

**What you expected to happen**:
- `tsh` should not give option to connect to serverless aurora clusters since it's not supported. (as it's already documented in the guide that serverless is not supported)

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. have a serverless aurora mysql/postgres to be discovered by teleport
2. `tsh db connect --db-user=<user> --db-name=<name> <serverless-aurora-db-id>`

### Server Details
- Teleport version (run `teleport version`): `Teleport v8.0.0-alpha.1 git:v8.0.0-alpha.1-254-g207e90720 go1.17.3`
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`): `Teleport v8.0.0-alpha.1 git:v8.0.0-alpha.1-254-g207e90720 go1.17.3`
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### PR DESCRIPTION
**Pull request by greedy52**
closes #9372

### Problem
In rds guides, it's already stated
> Aurora Serverless does not support IAM authentication at the time of this writing so it can't be used with Database Access.

However, we are still auto discoverying them (serverless clusters) and they do end up in `tsh db ls`. And, `tsh db connect <serverless>` will **ALWAYS** fail.

### Change
Checks `DBCluster.EngineMode` when creating RDS database, and errors out if `serverless`.

Quote from [aws sdk doc](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBClusterInput)

>  // The DB engine mode of the DB cluster, either provisioned, serverless, parallelquery,
    // global, or multimaster.

### Testing

Deployed a serverless aurora postgres
- verified it doesn't show up in `tsh db ls`.
- verified "non-serverless" db clusters still show up in `tsh db ls`
- Server log 
```
INFO Could not convert RDS cluster "steve-postgres" to database resource: unsupported Aurora engine mode serverless. labels:map[*:[*]] region:ca-central-1 watchers/rds.go:147                                           
```

### CODE REVIEW

**Comment by codingllama** [comment]
FYI, fixed typos on title, don't forget to update the commit too.

I see you have enough reviewers, so silently sitting out the rest. :)

File: lib/services/database.go [hunk 1]
```diff
@@ -133,6 +133,13 @@ func NewDatabaseFromRDSInstance(instance *rds.DBInstance) (types.Database, error
 
 // NewDatabaseFromRDSCluster creates a database resource from an RDS cluster (Aurora).
 func NewDatabaseFromRDSCluster(cluster *rds.DBCluster) (types.Database, error) {
+	// Aurora Serverless (v1 and v2) does not support IAM authentication
+	// https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations
+	// https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-2.limitations.html
+	if aws.StringValue(cluster.EngineMode) == RDSEngineModeServerless {
+		return nil, trace.NotImplemented("unsupported Aurora engine mode %v", RDSEngineModeServerless)
```
Comment (r0mant) [inline lib/services/database.go:140]: How/where is this "not implemented" error handled? Does it produce an error in the logs when a serverless instance is encountered?

Comment (greedy52) [reply lib/services/database.go:140]: It's currently called by the rds watcher

https://github.com/gravitational/teleport/blob/c9ee98b6af14bed973989e8270c3edf39db8a064/lib/srv/db/cloud/watchers/rds.go#L145

An `info` log is printed when this error happens, I put one sample log in the description

Comment (r0mant) [reply lib/services/database.go:140]: Hmm I see. To be honest, I think that instead of returning an error here, it would be more "graceful" to just skip over serverless instances when we're iterating over all fetched Aurora clusters and just not even attempt to convert, since this is a somewhat expected scenario.

Then we can also print a nice message for users e.g. something like:

```go
for _, cluster := range clusters {
  if aws.StringValue(cluster.EngineMode) == RDSEngineModeServerless {
    f.log.Infof("Aurora cluster %q is serverless which doesn't support IAM authentication. Skipping.")
    continue
  }
  ...
}
```

WDYT?

File: lib/services/database_test.go [hunk 2]
```diff
@@ -189,3 +189,20 @@ func TestDatabaseFromRDSCluster(t *testing.T) {
 	require.NoError(t, err)
 	require.Equal(t, expected, actual)
 }
+
+func TestDatabaseFromRDSCluster_serverless(t *testing.T) {
```
Comment (r0mant) [inline lib/services/database_test.go:193]: Nit: We don't usually separate test names with underscores.

```suggestion
func TestDatabaseFromRDSClusterServerless(t *testing.T) {
```

You run use  `t.Run()` for named "sub-tests".

File: lib/services/database.go [hunk 3]
```diff
@@ -133,6 +133,13 @@ func NewDatabaseFromRDSInstance(instance *rds.DBInstance) (types.Database, error
 
 // NewDatabaseFromRDSCluster creates a database resource from an RDS cluster (Aurora).
 func NewDatabaseFromRDSCluster(cluster *rds.DBCluster) (types.Database, error) {
+	// Aurora Serverless (v1 and v2) does not support IAM authentication
+	// https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations
+	// https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-2.limitations.html
+	if aws.StringValue(cluster.EngineMode) == RDSEngineModeServerless {
```
Comment (r0mant) [inline lib/services/database.go:139]: Also, what about other engine modes you mentioned in the description like `provisioned`, `parallelquery`, `global`, `multimaster`? Do you know if all those support IAM auth or should we skip some of those as well?

File: lib/services/database.go (hunk 1 above)
Comment (greedy52) [reply lib/services/database.go:140]: Ya. I think that's better. Will update

File: lib/services/database.go (hunk 3 above)
Comment (greedy52) [reply lib/services/database.go:139]: Good catch.

As for whether they support IAM, it's gets complicated. for example:

> Aurora MySQL 1.22.2, 1.20.1, 1.19.6, and 5.6.10a **_only_**: Parallel query doesn't support AWS Identity and Access Management (IAM) database authentication.

I will convert this check to a function something like `isIAMAuthSupported` and compile all these scenarios.

Comment (r0mant) [reply lib/services/database.go:139]: @greedy52 `IAMDatabaseAuthenticationEnabled` indicates whether IAM auth is enabled or disabled on the instance. We use it to determine whether we should attempt to enable IAM on the instance ourselves. So it can't be used to determine whether the instance _supports_ IAM or not.

Comment (greedy52) [reply lib/services/database.go:139]: > @greedy52 `IAMDatabaseAuthenticationEnabled` indicates whether IAM auth is enabled or disabled on the instance. We use it to determine whether we should attempt to enable IAM on the instance ourselves. So it can't be used to determine whether the instance _supports_ IAM or not.

That's correct. I guess this is a different topic than the original ticket. So wouldn't `tsh db connect" would also fail if databases that DOES NOT have IAM auth enabled. That said, registering them but direct users to enable iam auth probably better option. 

Will try to capture all the 'not-supported' cases in this pr. 😄

File: lib/srv/db/cloud/watchers/rds.go [hunk 4]
```diff
@@ -196,5 +202,74 @@ func auroraFilters() []*rds.Filter {
...
+			log.Infof("Aurora cluster %q (engine mode %v, engine version %v) doesn't support IAM authentication. Skipping.",
+				aws.StringValue(cluster.DBClusterIdentifier),
+				aws.StringValue(cluster.EngineMode),
+				aws.StringValue(cluster.EngineVersion),
+			)
+			return false
+		}
+
+	// other modes are compatible
+	default:
```
Comment (jimbishopp) [inline lib/srv/db/cloud/watchers/rds.go:232]: I'd remove this. It's clear other modes are compatible without it.

File: lib/srv/db/cloud/watchers/rds.go [hunk 5]
```diff
@@ -196,5 +202,74 @@ func auroraFilters() []*rds.Filter {
...
+	//
+	// general format is: <mysql-major-version>.mysql_aurora.<aurora-mysql-version>
+	// 5.6.10a and 5.7.12 are "legacy" versions and they are returned as it is
+	parts := strings.Split(aws.StringValue(cluster.EngineVersion), ".")
+	for i, part := range parts {
+		if part == "mysql_aurora" {
+			return strings.Join(parts[i+1:], ".")
+		}
+	}
+	return aws.StringValue(cluster.EngineVersion)
```
Comment (jimbishopp) [inline lib/srv/db/cloud/watchers/rds.go:258]: Consider using `strings.Index` instead of `Split/Join`.

```suggestion
	const tag = "mysql_aurora"
	version := aws.StringValue(cluster.EngineVersion)
	if i := strings.Index(version, tag); i != -1 {
		if startIdx := i + len(tag) + 1; startIdx < len(version) {
			return version[startIdx:]
		}
	}
	return version
```

File: lib/srv/db/cloud/watchers/rds_test.go [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+	tests := []struct {
+		name          string
+		engineMode    string
+		engineVersion string
+		isSupported   bool
+	}{
+		{"provisioned", RDSEngineModeProvisioned, "5.6.mysql_aurora.1.22.0", true},
+		{"serverless", RDSEngineModeServerless, "5.6.mysql_aurora.1.22.0", false},
+		{"parallel query supported", RDSEngineModeParallelQuery, "5.6.mysql_aurora.1.22.0", true},
+		{"parallel query unsupported", RDSEngineModeParallelQuery, "5.6.mysql_aurora.1.19.6", false},
```
Comment (jimbishopp) [inline lib/srv/db/cloud/watchers/rds_test.go:48]: nit: most of our tests include keys: `{name: "provisioned", ...}`.

**Review by jimbishopp — CHANGES_REQUESTED** [review]

File: lib/srv/db/cloud/watchers/rds.go (hunk 5 above)
Comment (greedy52) [reply lib/srv/db/cloud/watchers/rds.go:258]: Personally I don't like index calculation unless it's necessary. Is there any particular case you have in mind that it's missing in original implementation?

I do think Split makes logic easier to understand. That said, I probably can do split on `.mysql_aurora.`, and if `len(parts) == 2`, then return `parts[1]`. I can probably look into this.

Performance wise Split/Join definitely uses more memory and cpu but it's probably in `ns` difference and this is not on critical path 😄

File: lib/srv/db/cloud/watchers/rds.go (hunk 4 above)
Comment (greedy52) [reply lib/srv/db/cloud/watchers/rds.go:232]: will do

File: lib/srv/db/cloud/watchers/rds.go (hunk 5 above)
Comment (jimbishopp) [reply lib/srv/db/cloud/watchers/rds.go:258]: Splitting on `.mysql_aurora.` is a good idea. 

As you said, performance isn't really a concern here, but FWIW, there are no allocations for the `Index` version (vs ~8 for split) and `Index` is ~16x faster on my machine using the examples in your comments.

I commented on this because it was more about understanding what it was doing. It took me a few glances because I didn't expect to see a split/join given the description. Had I seen `Index`, I feel like I would've understood right away since `Index` is designed to search for substrings. But accuracy is more important and both versions do the job.

Comment (jimbishopp) [reply lib/srv/db/cloud/watchers/rds.go:258]: Looks like Go 1.18 will add a new [`Cut` function](https://github.com/golang/go/issues/46336) that will make common tasks like this even better.  🙂

```
_, v, ok = strings.Cut(version, ".mysql_aurora.")
if ok {
  return v
}
```

**Comment by greedy52** [comment]
moved helper to `lib/services` with other database stuff

File: lib/srv/db/cloud/watchers/rds.go [hunk 7]
```diff
@@ -142,6 +142,10 @@ func (f *rdsFetcher) getAuroraDatabases(ctx context.Context) (types.Databases, e
 	}
 	databases := make(types.Databases, 0, len(clusters))
 	for _, cluster := range clusters {
+		if !services.IsRDSClusterSupported(cluster, f.log) {
+			continue
+		}
```
Comment (jimbishopp) [inline lib/srv/db/cloud/watchers/rds.go:147]: I'd return an error here and log before the continue rather than require a logger to be passed as an argument. 

I see that @r0mant had suggested we remove the error here and log/continue instead, but the code has since changed from `services.NewDatabaseFromRDSCluster(cluster) ` to use this very simple and clean `services.IsRDSClusterSupported`. Logging is the responsibility of `rdsFetcher`, which would remove the side effect from `IsRDSClusterSupported`.

Sorry to go back and forth on this part.

File: lib/services/database_test.go [hunk 8]
```diff
@@ -189,3 +191,41 @@ func TestDatabaseFromRDSCluster(t *testing.T) {
...
 }
+
+func TestAuroraMySQLVersion(t *testing.T) {
+	require.Equal(t, "5.6.10a", auroraMySQLVersion(&rds.DBCluster{EngineVersion: aws.String("5.6.10a")}))
+	require.Equal(t, "1.22.1", auroraMySQLVersion(&rds.DBCluster{EngineVersion: aws.String("5.6.mysql_aurora.1.22.1")}))
+	require.Equal(t, "1.22.1.3", auroraMySQLVersion(&rds.DBCluster{EngineVersion: aws.String("5.6.mysql_aurora.1.22.1.3")}))
+}
+
+func TestIsRDSClusterSupported(t *testing.T) {
+	logger := logrus.WithField("test", t.Name())
```
Comment (jimbishopp) [inline lib/services/database_test.go:202]: This wouldn't be necessary if a logger was not required for `IsRDSClusterSupported` (see other comment).

File: lib/services/database_test.go [hunk 9]
```diff
@@ -189,3 +191,41 @@ func TestDatabaseFromRDSCluster(t *testing.T) {
...
+	tests := []struct {
+		name          string
+		engineMode    string
+		engineVersion string
+		isSupported   bool
+	}{
+		{name: "provisioned", engineMode: RDSEngineModeProvisioned, engineVersion: "5.6.mysql_aurora.1.22.0", isSupported: true},
+		{name: "serverless", engineMode: RDSEngineModeServerless, engineVersion: "5.6.mysql_aurora.1.22.0", isSupported: false},
+		{name: "parallel query supported", engineMode: RDSEngineModeParallelQuery, engineVersion: "5.6.mysql_aurora.1.22.0", isSupported: true},
+		{name: "parallel query unsupported", engineMode: RDSEngineModeParallelQuery, engineVersion: "5.6.mysql_aurora.1.19.6", isSupported: false},
```
Comment (jimbishopp) [inline lib/services/database_test.go:213]: nit: Thanks for adding the keys. No big deal here, but it would be easier to read, with keys :), when formatted vertically. Most of the tests I've seen use a format like [this db test](https://github.com/gravitational/teleport/blob/18d27232f0838a609ff76db17f3885115464cae9/lib/srv/db/access_test.go#L67).

**Review by jimbishopp — COMMENTED** [review]
LGTM. Just a couple minor comments.

File: lib/services/database.go [hunk 10]
```diff
@@ -225,6 +228,58 @@ func tagsToLabels(tags []*rds.Tag) map[string]string {
...
 
+// IsRDSClusterSupported checks whether the aurora cluster is supported and logs
+// related info if not.
+func IsRDSClusterSupported(cluster *rds.DBCluster, log logrus.FieldLogger) bool {
+	switch aws.StringValue(cluster.EngineMode) {
+	// Aurora Serverless (v1 and v2) does not support IAM authentication
+	// https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations
+	// https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-2.limitations.html
+	case RDSEngineModeServerless:
+		log.Infof("Aurora cluster %q is %s which doesn't support IAM authentication. Skipping.",
```
Comment (r0mant) [inline lib/services/database.go:239]: Let's use debug level here, otherwise I think it might spam the logs on every discovery loop.
```suggestion
		log.Debugf("Aurora cluster %q is %s which doesn't support IAM authentication. Skipping.",
```

File: lib/services/database.go [hunk 11]
```diff
@@ -225,6 +228,58 @@ func tagsToLabels(tags []*rds.Tag) map[string]string {
...
+			aws.StringValue(cluster.DBClusterIdentifier),
+			aws.StringValue(cluster.EngineMode),
+		)
+		return false
+
+	// Aurora MySQL 1.22.2, 1.20.1, 1.19.6, and 5.6.10a only: Parallel query doesn't support AWS Identity and Access Management (IAM) database authentication.
+	// https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-mysql-parallel-query.html#aurora-mysql-parallel-query-limitations
+	case RDSEngineModeParallelQuery:
+		if apiutils.SliceContainsStr([]string{"1.22.2", "1.20.1", "1.19.6", "5.6.10a"}, auroraMySQLVersion(cluster)) {
+			log.Infof("Aurora cluster %q (engine mode %v, engine version %v) doesn't support IAM authentication. Skipping.",
```
Comment (r0mant) [inline lib/services/database.go:249]:
```suggestion
			log.Debugf("Aurora cluster %q (engine mode %v, engine version %v) doesn't support IAM authentication. Skipping.",
```

File: lib/services/database.go [hunk 12]
```diff
@@ -225,6 +228,58 @@ func tagsToLabels(tags []*rds.Tag) map[string]string {
...
+		log.Infof("Aurora cluster %q is %s which doesn't support IAM authentication. Skipping.",
+			aws.StringValue(cluster.DBClusterIdentifier),
+			aws.StringValue(cluster.EngineMode),
+		)
+		return false
+
+	// Aurora MySQL 1.22.2, 1.20.1, 1.19.6, and 5.6.10a only: Parallel query doesn't support AWS Identity and Access Management (IAM) database authentication.
+	// https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-mysql-parallel-query.html#aurora-mysql-parallel-query-limitations
+	case RDSEngineModeParallelQuery:
+		if apiutils.SliceContainsStr([]string{"1.22.2", "1.20.1", "1.19.6", "5.6.10a"}, auroraMySQLVersion(cluster)) {
```
Comment (r0mant) [inline lib/services/database.go:248]: Is `parallelquery` mode only valid for MySQL engine?

Also, if we're checking the substring anyway, do we really need to try and parse our the aurora version?

File: lib/services/database_test.go [hunk 13]
```diff
@@ -189,3 +191,41 @@ func TestDatabaseFromRDSCluster(t *testing.T) {
 	require.NoError(t, err)
 	require.Equal(t, expected, actual)
 }
+
+func TestAuroraMySQLVersion(t *testing.T) {
+	require.Equal(t, "5.6.10a", auroraMySQLVersion(&rds.DBCluster{EngineVersion: aws.String("5.6.10a")}))
+	require.Equal(t, "1.22.1", auroraMySQLVersion(&rds.DBCluster{EngineVersion: aws.String("5.6.mysql_aurora.1.22.1")}))
+	require.Equal(t, "1.22.1.3", auroraMySQLVersion(&rds.DBCluster{EngineVersion: aws.String("5.6.mysql_aurora.1.22.1.3")}))
```
Comment (r0mant) [inline lib/services/database_test.go:198]: Nit: Convert this to a table-format test (like below).

File: lib/services/database_test.go (hunk 9 above)
Comment (r0mant) [reply lib/services/database_test.go:213]: Yeah, with long lines like this it read a bit better when it's formatted vertically.

File: lib/srv/db/cloud/watchers/rds.go (hunk 7 above)
Comment (r0mant) [reply lib/srv/db/cloud/watchers/rds.go:147]: Yeah, I was thinking the same, it's no big deal either way but logging here would be a little cleaner and you wouldn't need to pass log parameter to the method.

```suggestion
		if !services.IsRDSClusterSupported(cluster) {
		        f.log.Debugf("Aurora cluster %q (engine mode %v, engine version %v) doesn't support IAM authentication. Skipping.",
		            aws.StringValue(cluster.DBClusterIdentifier),
		            aws.StringValue(cluster.EngineMode),
			    aws.StringValue(cluster.EngineVersion))
			continue
		}
```

**Review by r0mant — APPROVED** [review]
lgtm after the remaining comments are addressed

File: lib/services/database_test.go (hunk 9 above)
Comment (greedy52) [reply lib/services/database_test.go:213]: Thanks, will do

File: lib/services/database.go (hunk 12 above)
Comment (greedy52) [reply lib/services/database.go:248]: - yes, `parrallelquery` is only for Aurora MySQL
- i am currently comparing the full version string. i feel it's safer than substring.

**Review by jimbishopp — APPROVED** [review]
