### PR TITLE
Forward TELEPORT_HOME to kubeconfig

### LINKED ISSUE #9387: tsh kube login should preserve TELEPORT_HOME when writing kubeconfig
### Description

**What happened**:

If you set the TELEPORT_HOME variable, it tells the `tsh` binary to look in an alternate location instead of `~/.tsh`. Unfortunately, when TELEPORT_HOME is set, and the kubeconfig file is written out, the presence of this setting is not considered. The effect is that kubectl commands don't work properly.

**What you expected to happen**:

The kubeconfig that tsh writes out should preserve the TELEPORT_HOME variable functionality. This will likely mean that the kubeconfig entries will need to have the `env:` key populated with the TELPORT_HOME key and value, and the `tsh kube credentials` command will need to respect it as well.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. set `TELEPORT_HOME` to a non-default location.
2. do a `tsh login` and `tsh kube login`
3. attempt to run any `kubectl` command.

### Server Details
- Teleport version (run `teleport version`): 8.0.0
- Server OS (e.g. from `/etc/os-release`): n/a
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): n/a
- Additional details:

### Client Details
- Tsh version (`tsh version`): 8.0.0
- Computer OS (e.g. Linux, macOS, Windows): mac
- Browser version (for UI-related issues): n/a
- Installed via (e.g. apt, yum, brew, website download): website download
- Additional details:

### PR DESCRIPTION
**Pull request by atburke**
This PR forwards TELEPORT_HOME to kubeconfig in `tsh kube login`.

Fixes #9387.

### CODE REVIEW

File: lib/kube/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -98,6 +100,14 @@ func Update(path string, v Values) error {
 	if v.Exec != nil {
 		// Called from tsh, use the exec plugin model.
 		clusterName := v.TeleportClusterName
+		var envVars []clientcmdapi.ExecEnvVar
+		if v.Exec.Env != nil {
+			envVars = make([]clientcmdapi.ExecEnvVar, 0)
```
Comment (zmb3) [inline lib/kube/kubeconfig/kubeconfig.go:105]: This line is not necessary. `append` will work on a nil slice just fine, so no reason to make a size 0 slice first.

File: lib/kube/kubeconfig/kubeconfig.go [hunk 2]
```diff
@@ -114,6 +124,9 @@ func Update(path string, v Values) error {
 			if v.Exec.TshBinaryInsecure {
 				authInfo.Exec.Args = append(authInfo.Exec.Args, "--insecure")
 			}
+			if envVars != nil {
```
Comment (zmb3) [inline lib/kube/kubeconfig/kubeconfig.go:127]: I would use `if len(envVars) > 0` as it will work for both a nil slice and a non-nil slice with zero elements.

File: lib/kube/kubeconfig/kubeconfig_test.go [hunk 3]
```diff
@@ -215,6 +216,64 @@ func (s *KubeconfigSuite) TestUpdate(c *check.C) {
 	c.Assert(config, check.DeepEquals, wantConfig)
 }
 
+func (s *KubeconfigSuite) TestUpdateWithExec(c *check.C) {
```
Comment (zmb3) [inline lib/kube/kubeconfig/kubeconfig_test.go:219]: Unless the test suite is huge, I generally try to migrate from `check` to standard Go tests when I encounter them as defined in RFD #0001.

This file looks to be only 300-400 lines - care to take a stab at converting it?

**Review by zmb3 — APPROVED** [review]

**Review by rosstimothy — APPROVED** [review]
